### ISSUE TITLE
Brief hang when typing < in ts

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#63701]
This seems to happen anywhere but here's a specific place I see this

- Open SettingsEditor.ts
- On line 50 after `extends BaseEditor` type `<` like to start a generic parameter
- See a pause of 1s or so before the character appears

The profile shows a really long time tokenizing after the keypress

[Profile-20181123T140051.json.txt](https://github.com/Microsoft/vscode/files/2611782/Profile-20181123T140051.json.txt)

**Comment by mjbvz** [comment]
I can't repo this in the latest VS Code insiders:

![jan-02-2019 16-35-45](https://user-images.githubusercontent.com/12821956/50619176-803a9f00-0eac-11e9-9992-0ff59fa37515.gif)

@roblourens Can you please test again to confirm

**Comment by roblourens** [comment]
Yeah looks good now
