### ISSUE TITLE
terminal not working..

### ISSUE THREAD

**Issue by Davengahu007** [Microsoft/vscode#63708]
Issue Type: <b>Bug</b>

when i press ctrl + ` nothing happens....even if i use the long way and go to terminal and select new terminal it refuses to open

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.70GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.10.1

</details>

**Comment by Davengahu007** [comment]
yes it is the same as terminal 60013

**Comment by Tyriar** [comment]
Do you get an error or anything? Does literally nothing happen on the UI?

Can you open devtools (Help > Toggle Developer Tools) and check for console errors?
