### ISSUE TITLE
Is there a method to enforced snippets?

### ISSUE THREAD

**Issue by lhsai9** [Microsoft/vscode#6370]
- VSCode Version: v1.1
- OS Version: windows10

In js , I may use some snippets about html.
For example:
html:
```
<div id="buttonGroup"></div>
```
js:
```
var x=document.getElementById("bottonGroup");
x.append("");//In there, I want to use BootStrap snippets like "bs3-button-primary".
                     //How can I do it? 

```
In SublimText I can use ctrl+shift+P then input "bs3-button-primary".
However , the VS Code is so beautiful that I don't want to use SublimText.
So, I Hope you can improve the snippets about it.
Thanks.

**Comment by isidorn** [comment]
VSCode supports snippets, please checkout this document
https://code.visualstudio.com/Docs/customization/userdefinedsnippets
