### ISSUE TITLE
VSCode Terminal as its own window/app with tabs

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#63709]
With the new  `"terminal.integrated.experimentalBufferImpl": "TypedArray",` vscode integrated terminal performance is brilliant. It seems to outperform both iTerm and MacOSX's built in Terminal app.

I'd love to replace iTerm with vscode's terminal without taking the big perf hit of launching all of vscode and it's extensions.

Just like there is `code <path>` cli shortcut to launch vscode, could we have a `code-term` to launch just the terminal as its own window ?

It seems the terminal already includes split panes, search, e.t.c and tabs seem like it's under discussion. So something like below should be possible by wrapping up the integrated terminal in it's own window.

![image](https://user-images.githubusercontent.com/1018196/48966603-7ce8f500-ef89-11e8-986a-fb99b7425120.png)

I do a lot of development in cli apps via mosh/ssh into a remote machine, I'm guessing I'm not the only one and it's a fairly common use-case.

**Comment by usernamehw** [comment]
duplicate of #34442 ?

**Comment by nojvek** [comment]
You are right. GitHub search didn’t show up that one. Closing this.
