### ISSUE TITLE
Chinese(GBK) Cannot display properly

### ISSUE THREAD

**Issue by a2757326588** [Microsoft/vscode#63706]
VSCode Version: 1.29.1 (user setup)
OS Version: win10 1809 x64

Sorry,my English is not good.

Steps to Reproduce:
Use gcc to compile source file in the terminate

Does this issue occur when all extensions are disabled?: Yes

in VSCode:
![tim 20181124133759](https://user-images.githubusercontent.com/20399194/48965032-fe736e00-efef-11e8-8dfb-82ae85e4592d.png)
in PowerShell:
![tim 20181124133854](https://user-images.githubusercontent.com/20399194/48965033-fe736e00-efef-11e8-8f1c-4b12b1a37024.png)

Chinese file name cannot display properly

**Comment by lrcno6** [comment]
我也是中国人  I am also a Chinese.
一般情况下此类乱码问题是代码页不正确导致的 Garbled problems are usually caused by the wrong code page.
只不过我不能帮更多的忙了 And I am sorry that I cannot help you more.

**Comment by lrcno6** [comment]
而且,在编程时避免使用中文是一个好习惯  It is a good habit that avoid using Chinese when you programme.

**Comment by a2757326588** [comment]
@lrcno6 把代码页设置为936或65001都不能解决问题
这个问题是在我把VSCode更新到1.29.1，把系统更新到1809后才出现的
我只是一个中学生，很抱歉不能熟练使用英语
谢谢

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
