### ISSUE TITLE
Integrated login with github and bitbucket to clone repositories inside vscode

### ISSUE THREAD

**Issue by lucasluizss** [Microsoft/vscode#63711]
List multiple repositories from different's accounts like Bitbucket or GitLab with vscode

**Comment by roblourens** [comment]
You can clone from a URL: 
![image](https://user-images.githubusercontent.com/323878/49047933-dfaade00-f18d-11e8-8d70-b983d1b2f432.png)

Please explain some more if this isn't what you're looking for.

**Comment by lucasluizss** [comment]
Hi,

What I wanted mean is to clone some of my repositories, but listing they all with some screen separated by git account.
Turn possible the vscode save all my configuration when I login with my git account in another's devices.

Sent from my iPhone

On 26 Nov 2018, at 21:15, Rob Lourens <notifications@github.com<mailto:notifications@github.com>> wrote:


You can clone from a URL:
[image]<https://user-images.githubusercontent.com/323878/49047933-dfaade00-f18d-11e8-8d70-b983d1b2f432.png>

Please explain some more if this isn't what you're looking for.
