### ISSUE TITLE
[Suggestion] Unify the UI highlight color of "Default Dark+" theme with the VSCode-icon-blue

### ISSUE THREAD

**Issue by LIXiangChen** [Microsoft/vscode#63715]
![vs](https://user-images.githubusercontent.com/8857634/48969577-816de600-f03b-11e8-9606-397d849d865f.png)

I'm referring to the color of highlight box of the hovered input controls, highlight indicator of the modified tabs, etc., of the software UI.

I hope this color can be unified with the VSCode-icon-blue.

**Comment by usernamehw** [comment]
In Settings
```json
"workbench.colorCustomizations": {
    "[Default Dark+]": {
        "editorGutter.modifiedBackground": "#007acc",
        "tab.activeModifiedBorder": "#007acc",
        "badge.background": "#007acc",
        "activityBarBadge.background": "#007acc",
        "focusBorder": "#007acc",
        "button.background": "#007acc",
        "textLink.foreground": "#007acc",
        "list.highlightForeground": "#007acc",
        "editorSuggestWidget.highlightForeground": "#007acc",
        "settings.modifiedItemIndicator": "#007acc",
        "editor.selectionBackground": "#007acc66",
    }
}
```

**Comment by LIXiangChen** [comment]
@usernamehw Thank you, but I hope that VSCode can officially change these colors. After all, there are two similar blue colors in the UI, which is weird.
