### ISSUE TITLE
Add "Open in vscode" to Right Click menu in Windows 10

### ISSUE THREAD

**Issue by RamonRobben** [Microsoft/vscode#63714]
I have searched for existing issues but they were all about the right click menu in the sidebar. I am talking about the right click menu on folders and files that you get with Windows.

I'd like to have an option in my right click menu saying: Open in Visual Studio Code or Open in vscode
Something like what visual studio has:

![image](https://user-images.githubusercontent.com/12982618/48968595-26fc6780-eff2-11e8-95c3-5d8309d5e05e.png)

I know you can add something like this yourself but its nicer to have if it comes as an option with vscode.

**Comment by usernamehw** [comment]
I haven't tried it but this article looks fine:

https://thisdavej.com/right-click-on-windows-folder-and-open-with-visual-studio-code/

**Comment by myfairsyer** [comment]
It should be possible to toggle the context menu entries as well as `code.exe`'s folder being added to `%PATH%` from the menu after installing `vscode`

**Comment by joaomoreno** [comment]
@RamonRobben You have to reinstall for now, but you can simply install over it, no need to first uninstall.
