### ISSUE TITLE
PHP Xdebug not working

### ISSUE THREAD

**Issue by LJNunes** [Microsoft/vscode#63719]
Hi, I'm using VSCODE in Ubuntu 18.04. I have php and xdebug installed, and they are both working (!).
It just happens that Xdebug does not receive my code! I'll tell you how I know: if I run
   netstat --listen | grep 9000
the result is an empty line. If I launch the debugger in vscode and run the same command again, the output is
   tcp6       0      0 [::]:9000               [::]:*                  LISTEN 
In vscode, the debug console becomes active: if I write "Is Xdebug working?" (without the quotes), the answer is "Cannot evaluate code without a connection". If I write "printf("Hello World!");" the answer is "Cannot evaluate code without a connection". Well... the connection is alive, is just does not get my code :-(.
I tried several things, namely, using putty to create ssh tunnels over port 9000. No Joy!

Any idea what might be wrong? phpinfo() returns the usual correct status, php -v reports that Xdebug is active... it simply is not receiving my code...

Best regards,
Licínio Nunes

**Comment by weinand** [comment]
Please ask this question on Stackoverflow or file this question against the PHP extension repo.
