### ISSUE TITLE
Maintain order of DiagnosticRelatedInformation objects in Diagnostic.relatedInformation

### ISSUE THREAD

**Issue by vector-of-bool** [Microsoft/vscode#63710]
Hello! Thank you for all your hard work!

This is a request regarding the diagnostics API. I was watching closely for #10271, and this may relate to some usages of #1927.

I'm not sure if this is "by design" or just incidental to the way it was implemented, but the ordering of items in the `relatedInformation` array property of `vscode.Diagnostic` objects seems to be ignored when VSCode displays this information in the problems panel.

It seems that the ordering within a single file is honored, but related information objects from different files are not ordered relative to each other.

On a barely related note: Is there any push for arbitrary hierarchies of diagnostics?

**Comment by sandy081** [comment]
@vector-of-bool Can you please provide us an example for related informations from different files and what is the expected order to be?

**Comment by vector-of-bool** [comment]
Here's an example:

![selection_035](https://user-images.githubusercontent.com/17038621/49050943-f90a5500-f1a2-11e8-8192-ad10dc04070e.png)

Here's the relevant code snippet which generates this information:

```typescript
const diags = vscode.languages.createDiagnosticCollection('repro-with-related');
const diag = new vscode.Diagnostic(new vscode.Range(0, 0, 999, 999), 'I am an example diagnostic');
diag.relatedInformation = [];
const files = ['file1', 'file2', 'file3'];
for (const i of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) {
    const related = new vscode.DiagnosticRelatedInformation(
        new vscode.Location(
            vscode.Uri.file(files[i % files.length]),
            new vscode.Position(10, 40),
        ),
        `Message number ${i}`,
    );
    diag.relatedInformation.push(related);
}
diags.set(vscode.Uri.file('file.txt'), [diag]);
```

Looking at it, it appears to sort them first lexicographically by filename, then by original insertion order. Calling `diag.relatedInformation.reverse()` before `diags.set` produces this order:

![selection_036](https://user-images.githubusercontent.com/17038621/49050996-3a9b0000-f1a3-11e8-93ba-4973d80a3761.png)

My intuition is that the original order of the `relatedInformation` array object would be preserved.

I am also seeing that sometimes a large amount of `relatedInformation` can produce wacky layouts in the tree view, but that is probably a different issue.

**Comment by sandy081** [comment]
Should the source of these diagnostics give this information in the correct order? Since it is related info, the source has more context to provide the right order.

**Comment by vector-of-bool** [comment]
In my real use case, I'm generating the `relatedInformation` array from the output of a tool (a compiler), so I do have the order. Between multiple files that order is not maintained in the problems view.

**Comment by fredriklengstrand** [comment]
Hi,

First I just wanted to say thank you for creating this project and it's excellent extension support.

Now, onto the topic of my response, I'm facing the same issue as well. I'm trying to use the `relatedInformation` array to show the whole `include` chain for a file that generated an error in our linter (so you can follow it from the entry point up to where the error was generated). This of course gets quite confusing if you cannot control the order in which the entries appear. One thing I noticed was that it seems like the hover provider does keeps the original order intact when displaying the `relatedInformation` array.

Here are some screenshots of what I'm working on to maybe better illustrate my use case:

Incorrect order in problems tab:
<img width="340" alt="screenshot 2018-11-27 at 21 34 54" src="https://user-images.githubusercontent.com/10126466/49111846-917f0300-f291-11e8-910b-df7854500fce.png">

Correct order in hover provider:
<img width="348" alt="screenshot 2018-11-27 at 21 34 46" src="https://user-images.githubusercontent.com/10126466/49111848-92b03000-f291-11e8-8e25-aa91451a2e85.png">

**Comment by sandy081** [comment]
Yes, I can repro it. Problems view is changing the order. Fixed.

**Comment by vector-of-bool** [comment]
I thank you kindly for the prompt fix!
