### ISSUE TITLE
please dont bloat VS Studio - remove default commit ghost info on idling cursor

### ISSUE THREAD

**Issue by xkunglu** [Microsoft/vscode#63718]
Issue Type: <b>Feature Request</b>

I dont know whose idea is it that I want to see the name and date of every git commit every time my cursor blinks on a line.  Bugs the heck out of me.  This mustve been added recently. 
It should be on only if requested; it isnt useful 99.9% of the time.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.10.0-28-generic

**Comment by GloriousYellow** [comment]
Are you using the GitLens extension?

**Comment by xkunglu** [comment]
My bad. you are right; sorry microsoft; i bloated this not you ;)
Im using GitHistory Diff extension - which is useful at times.
It seems that un checking Settings Githd> Blame View/ show git blame information for each line; will fix the issue.
