### ISSUE TITLE
inotifywait occasionally reports zero-length file

### ISSUE THREAD

**Issue by rcook** [Microsoft/vscode#63720]
Issue Type: <b>Bug</b>

Setup:

```bash
mkdir repro
cd repro
git init
touch test.txt
cat > watch << EOF
#!/bin/bash
path=test.txt
while inotifywait -e modify \$path; do
  stat --printf="%s" \$path
done
EOF
chmod +x watch
code .
```

Inside VSCode, open `test.txt` and open an integrated terminal with ``Ctrl+` ``. Inside the integrated terminal, start the watcher script with `./watch`.

Now make repeated edits to `test.txt`. Occasionally the watcher script will report that the file has zero-length.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (10.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
When saving a file, node.js will first truncate the file to be empty and then fill it up. There is nothing we can do against that.
