### ISSUE TITLE
Strange error. Text added to the left of every sentence

### ISSUE THREAD

**Issue by skanskan** [Microsoft/vscode#63724]
Visual Studio Code 1.29.1 on Windows 10 X64

Hello.
I've been using Julia on Visual Studio Code with language-julia-0.11.0-beta.2.vsix for several days but today it doesn't work. I don't know why.

Whatever I try to run on the main editor it adds it a prefix "200~" and generates an error.

For example:
`using DataFrames, GLM`

produces:
```
200~using DataFrames, GLM
ERROR: MethodError: no method matching ~(::Int64, ::Int64)
```
Has anyone had the same problem?
Do you think is a problem wit VS Code, the extension or with Julia?
running the code directly on the REPL works well.
I've tried reinstalling the extension but the problem is still there.

It only happens with the Julia extension enabled.

**Comment by alexr00** [comment]
If it only happens with the Julia extension enabled then this issue should be filed in the repository for that extension 😊
