### ISSUE TITLE
[performance] terminalProcess.ts: Repeatedly calls to anonymous function every 200ms (polling)

### ISSUE THREAD

**Issue by gladiator001** [microsoft/vscode#63723]
- VSCode Version:
Version 1.29.1 (1.29.1)

- OS Version:
macOS Mojave version 10.14.1

Steps to Reproduce:
https://github.com/Microsoft/vscode/blob/8f688a4ccf7bb996475b71e13693bd5c7b1af0ee/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L100-L105

The porpoise of this code is to update the dropdown list item's text with the current shell process in the integrated terminal. Which is something that I mostly never change, however JS is running every 200ms to detect changes unnecessarily.

**Comment by Tyriar** [comment]
Do you have a proposal to make it faster? I'm not sure there's an event we can hook into for this.

**Comment by gladiator001** [comment]
No, unfortunately not, but IMHO anything that can be done to prevent polling, would be a better/faster solution.

**Comment by jerch** [comment]
@gladiator001 The process name is polled from the kernel process interfaces in node-pty, none of the supported OS has an event driven interface for that (commands like `ps` and `top` also have to poll it).

Still the polling could be made less exp by moving the code in `pty_getproc(int fd, char *tty)` to its own thread and just comparing `tcgetpgrp` (cheap call). If that changes, trigger a callback with the new process name. This works for all common shells since they typically spawn their foreground processes in new process groups. Note that this will not spot process replacements by `exec*`, therefore the process name should still be compared from time to time.

**Comment by Tyriar** [comment]
Pointer to what's being polled: https://github.com/Microsoft/node-pty/blob/912bed984164b85a9531eb83d66b4c7343d44da6/src/unix/pty.cc#L531

**Comment by jerch** [comment]
@Tyriar Just saw that `pty_getproc(int fd, char *tty)` does not cover Solaris and other BSDs beside Darwin. Since there are several preprocessor directives for those all over the code I guess noone really cared?

**Comment by jerch** [comment]
On linux roughly 200 cycles per check can be saved by omitting the process name resolution:
```
tcgetpgrp: 0.016000 ms, 16 clocks
tcgetpgrp + reading name: 0.215000 ms, 215 clocks
tcgetpgrp: 0.015000 ms, 15 clocks
tcgetpgrp + reading name: 0.199000 ms, 199 clocks
tcgetpgrp: 0.006000 ms, 6 clocks
tcgetpgrp + reading name: 0.106000 ms, 106 clocks
tcgetpgrp: 0.011000 ms, 11 clocks
tcgetpgrp + reading name: 0.196000 ms, 196 clocks
tcgetpgrp: 0.016000 ms, 16 clocks
tcgetpgrp + reading name: 0.249000 ms, 249 clocks
tcgetpgrp: 0.016000 ms, 16 clocks
tcgetpgrp + reading name: 0.255000 ms, 255 clocks
tcgetpgrp: 0.013000 ms, 13 clocks
tcgetpgrp + reading name: 0.218000 ms, 218 clocks
tcgetpgrp: 0.015000 ms, 15 clocks
tcgetpgrp + reading name: 0.224000 ms, 224 clocks
```
It would also lift ~0.2 ms per check from the main thread, which is quite alot compared to what it does and that there are effectively only 15 ms for computation within a single frame.

**Comment by Tyriar** [comment]
We should either go with https://github.com/Microsoft/node-pty/pull/243 or at the very least use a similar mechanism to how the Windows title is fetched.

**Comment by Tyriar** [comment]
Disabled the polling on Windows as it doesn't actually every change there.
