### ISSUE TITLE
"Dismiss" X button in the search panel should be aligned to the right edge

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#63726]
![image](https://user-images.githubusercontent.com/1305378/48974334-89d31a80-f055-11e8-9ad3-c0c373274ad1.png)

This would ensure predictability. Currently button is aligned just after the text excerpt. Problem is that can be short or long. So this button can be positioned all the way to the right or left, depending on the text size. 
I personally suffer from this when I quickly want to click to the search result to see it. Instead I often accidentally click the X button and I remove my result. Then I have to rerun the search again and next time I have to make sure not to click the "Dismiss" button.
Also when you need to remove multiple items using a mouse, it's much more complicated when these buttons are misaligned.

The simple CSS change would make the button position much more predictable.

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Run search
2. Observe

Does this issue occur when all extensions are disabled?: Yes

**Comment by karanisverma** [comment]
I would like to contribute on this one!

**Comment by roblourens** [comment]
We already have a PR going for this: https://github.com/Microsoft/vscode/pull/63457

**Comment by sean-mcmanus** [comment]
Thanks a lot for fixing this -- I've also been recently plagued by my search results accidentally being dismissed.
