### ISSUE TITLE
Git commit freezes UI

### ISSUE THREAD

**Issue by svenvNL** [Microsoft/vscode#6372]
- VSCode Version: 1.1.0
- OS Version: Windows 7

Steps to Reproduce:
1. have files to commit
2. type your commit message
3. hit CTRL + enter (or whatever your shortcut is)
4. click on the more menu dots

Git goes on committing my code in my local repo, but the UI freezes. Closing the menu by clicking somewhere unfreezes VSCode.
When things are commited, you have options like push, etc. While commiting, these are grayed out. When Git is done, these stay grayed out. You have to reopen the menu to use these options.

![vscode_git_freeze](https://cloud.githubusercontent.com/assets/13982006/15268998/58ec6864-19f1-11e6-86d2-3d29bae1a08e.gif)
Here I commit files white CTRL + enter and open the menu. The progress / loading bar stops and goes on after closing the menu.

**Comment by joaomoreno** [comment]
Popup menus freeze the UI, the same way alert boxes do. It's just how they are implemented in Electron.
