### ISSUE TITLE
Vscode features stop working suddenly

### ISSUE THREAD

**Issue by reznov11** [Microsoft/vscode#63725]
Issue Type: <b>Bug</b>

The issue started after i upgraded to the latest version of the update.
While i am working on my projects, all extensions including code highlighting, autocomplete paths, brackets highlighting, auto-rename tags, html autocomplete, python, all these features they stops from working, even the plus minus symbols on the left where the number of the rows are showing get disappeared, until i close the program, after that everything will work just fine.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 1, 1|
|Memory (System)|7.70GB (3.55GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
angular1-code-snippets|ale|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
prettier-vscode|esb|1.7.2
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.7
vscode-attrs-sorter|mrm|2.1.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
vetur|oct|0.13.0
material-icon-theme|PKi|3.6.1
java|red|0.34.0
LiveServer|rit|5.2.0
vscode-icons|rob|7.28.0
vuejspack|she|1.3.2
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.11.0
vscode-maven|vsc|0.11.2
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.11.0
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by reznov11** [comment]
Anybody have had the same problem??

**Comment by alexandrudima** [comment]
@reznov11 Can you please try the steps described [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions) to identify which of the extensions is consuming a lot of CPU ?

**Comment by reznov11** [comment]
[CPU-20181126T163323.820Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2616503/CPU-20181126T163323.820Z.cpuprofile.txt)

**Comment by alexandrudima** [comment]
@reznov11 Thank you for the profile, but from looking at it, there is nothing there that appears to consume a lot of CPU. The extension host appears to be busy for a few ms, sometimes 10s of ms, but nothing is eating up CPU, and the event loop is idle for most of the time (>95%):

![image](https://user-images.githubusercontent.com/5047891/49140012-79d86680-f2f3-11e8-87c8-d853fc152e40.png)

I think you have profiled the extension host, but perhaps you have profiled it at a time when it was responsive... So we cannot tell which of the extensions is slow... It would be best if you can profile while you are noticing a lack of responsiveness, so we can see which extension is causing it.
