### ISSUE TITLE
. NET assembly Cache caused the terminal to display word bug

### ISSUE THREAD

**Issue by taminn** [Microsoft/vscode#63729]
Issue Type: <b>Bug</b>

the problem is that the vscode terminal display some empty line when I open the terminal every time.
my system is windows 10 1809 and the problem only meet at 1809 version
I don't know what bring this problem,but when I have cleared .NET assembly Cache by dism++,the problem will be solved.
And the problem will reappear after a few day
hoping this issue can help you repair this problem .
![image](https://user-images.githubusercontent.com/37473907/48975507-a77f9e80-f0ac-11e8-9a52-bd7c74b6f3be.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
cpptools|ms-|0.20.1

(1 theme extensions excluded)

</details>

**Comment by taminn** [comment]
That's how I operate.
![image](https://user-images.githubusercontent.com/37473907/48976464-18ca4c00-f0c3-11e8-9265-0e97c262c10c.png)

**Comment by beastdestroyer** [comment]
This issue happened to me also, except I don't use .NET.

Windows 10 1809 17763.134 
VSCode: 1.30-exploration

**Comment by taminn** [comment]
>           This issue happened to me also, except I don't use .NET.
> Windows 10 1809 17763.134
> VSCode: 1.30-exploration

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
