### ISSUE TITLE
The Tab completion cannot be disabled by setting.json

### ISSUE THREAD

**Issue by E-train-Liu** [Microsoft/vscode#63732]
- VSCode Version: 1.25.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Open "Setting" 
2. Set `editor.tabCompletion` to `false`.
3. Set `editor.acceptSuggestionOnEnter` to `"off"`
4. Save and resume VSCode, the suggestion or completion still will be accepted when the <kbd>Tab</kbd> key is pressed.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/38714576/48976317-4d88d400-f0c0-11e8-8384-de2d0508ecbe.png)
![image](https://user-images.githubusercontent.com/38714576/48976324-7315dd80-f0c0-11e8-858d-4477bd786cd1.png)

**Comment by usernamehw** [comment]
It looks like this option is only working for snippets. If so, this should probably be reflected in option description, currently it is unclear:
```javascript
  // Enables tab completions.
  //  - on: Tab complete will insert the best matching suggestion when pressing tab.
  //  - off: Disable tab completions.
  //  - onlySnippets: Tab complete snippets when their prefix match. Works best when 'quickSuggestions' aren't enabled.
  "editor.tabCompletion": "off"
```

P.S. you can unbind <kbd>Tab</kbd> for suggest in keybindings
```json
{
    "key": "tab",
    "command": "-acceptSelectedSuggestion",
    "when": "suggestWidgetVisible && textInputFocus"
},
```

**Comment by jrieken** [comment]
> suggestion or completion still will be accepted when the Tab key is pressed.

From where? From the IntelliSense widget or from just a prefix in the editor?
