### ISSUE TITLE
Auto Guess Encoding  work incorrectly

### ISSUE THREAD

**Issue by codering** [Microsoft/vscode#63730]
- VSCode Version: 1.29.1
- OS Version:  macOS 10.14.1

Steps to Reproduce:
1. Enable "Auto Guess Encoding"
2. New file then input Chinese characters.
3. Save then close file.
4. Open the file again.

Does this issue occur when all extensions are disabled?: Yes

![vscode](https://user-images.githubusercontent.com/2271825/48975531-8f5c4f00-f0ad-11e8-9297-91f4aac42eea.gif)

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
