### ISSUE TITLE
DiagnosticsCollection#set doesn't merge by resource anymore

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#6373]
As of the vscode 1.1 release, the `DiagnosticsCollection#set` API appears to only use the first item in the array of diagnostics provided to it when showing errors inside VS Code.

See https://github.com/Microsoft/vscode-go/issues/322.

**Comment by lukehoban** [comment]
Here's before and after stepping over a call to `DiagnosticsCollection#set`, showing that only the first item of a three element array is being set in the diagnostics collection.

<img width="960" alt="pic" src="https://cloud.githubusercontent.com/assets/223467/15269371/3bbd557c-19b1-11e6-8bfe-838b00c58a3c.png">

<img width="960" alt="pic2" src="https://cloud.githubusercontent.com/assets/223467/15269372/3f77ff14-19b1-11e6-8028-461cc42dd3a4.png">

**Comment by jrieken** [comment]
Yes and no. The behaviour of [`set([uri,diag[]][])`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2502) has changed such that repeating uris in the array of type-diagnostics tuples aren't merged anymore. Ever since the doc hinted into that direction (sort of) but bringing back that behaviour should be no harm.

**Comment by jrieken** [comment]
[This is](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDiagnostics.ts#L75) where repeated uris in the set of tuples override the previous diagnostic (of that call). [Before](https://github.com/Microsoft/vscode/blob/81456a7212340902825f13985ec0c2867b482aad/src/vs/workbench/api/node/extHostDiagnostics.ts#L83) keeping diagnostics locally we would send them as is.

**Comment by dbaeumer** [comment]
Verified in code.
