### ISSUE TITLE
Configurable delay for problem diagnostics

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#63737]
![error](https://user-images.githubusercontent.com/9638156/48977567-dd715280-f0ad-11e8-9880-ffd5d9ad1065.gif)

I would like to **debounce** decoration rendering for `errors`/`warning`. Not sure about `info`/`hint`.
```javascript
"editor.errorDelay": number, // ms
"editor.warningDelay": number, // ms
```

* This is not a performace issue
* Even when decoration span is 1 line (not like the entire screenshot above) it would still be a good feature

**Comment by sandy081** [comment]
@usernamehw What is the need to make it configurable?

**Comment by usernamehw** [comment]
@sandy081 For the same reason `Zen Mode` exists.

**Comment by sandy081** [comment]
@usernamehw Sorry I did not find the relation. Can you please elaborate?

**Comment by usernamehw** [comment]
@sandy081 To not see anything that can grab your attention. 
Overwhelming majority of warnings will be fixed on save, most of the errors - I'm just not finished typing. 

The conclusion - they are often shown to the user for no reason.

**Comment by sandy081** [comment]
Instead of delay, what you need is not to validate until save? And this has to be supported by the extensions owning diagnostics and not through platform.

**Comment by usernamehw** [comment]
Yes, it should also trigger rendering of errors/warnings on save.

So ... to delay rendering of vscode decorations the only way is to support it - is somehow from language extensions...

**Comment by sandy081** [comment]
Yes.

Hence closing this as it is extension supported feature.
