### ISSUE TITLE
Extending URI (vscode://) to open workspace and multiple file 

### ISSUE THREAD

**Issue by ganeshgore** [microsoft/vscode#63735]
Can we open workspace using URL and specific file in that workplace.
Actually I am using some SFTP and workspace settings and opening just a single file in new windows ignores that. 
I was wondering if something like this can be done

`vscode://open/path/to/project?file=relative/path/to/file1:L:C,relative/path/to/file2:L:C`

I think it will make feature even more useful

**Comment by rebornix** [comment]
@joaomoreno seems this one come back to inbox tracking list, do you mind having some good label for it?

**Comment by bpasero** [comment]
Support for opening workspaces comes with 1.43: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_43.md#open-workspaces-via-application-links

**Comment by Sarcophosaur** [comment]
I would be very interested in seeing this feature implemented.
