### ISSUE TITLE
VSCode call WSL's make

### ISSUE THREAD

**Issue by c4dr01d** [Microsoft/vscode#63741]
When I configured dev environment at WSL, I trying to using tasks.json to call WSL side's make, but, the terminal say: bash: 'make' not found.
My WSL system is Ubuntu 18.04, use zsh(oh-my-zsh)

**Comment by c4dr01d** [comment]
VSCode can add support for WSL's side build tool? Like make,cmake.

**Comment by alexr00** [comment]
What is the output of `make --version` in WSL?

**Comment by c4dr01d** [comment]
bash: make: command not found.

**Comment by c4dr01d** [comment]
When I use tasks to call it

**Comment by alexr00** [comment]
What is the output of `make --version` in WSL when you run it without tasks though?

**Comment by c4dr01d** [comment]
GNU Make 4.2.1

**Comment by alexr00** [comment]
What do you have `terminal.integrated.shell.windows` set to in your settings? Are you setting the terminal exectuable to zsh there, or in your tasks.json?

**Comment by alexr00** [comment]
It looks like we don't do the special handling for wsl.exe that we do for bash.exe. I know bash.exe is no longer recommended for WSL, but could you try setting `terminal.integrated.shell.windows` to bash.exe? I will fix it for wsl.exe, but using bash.exe for now will get you unstuck.

**Comment by c4dr01d** [comment]
Ok,Thanks for your answer.

**Comment by alexr00** [comment]
Verification steps for later:
On Windows, setup WSL.
In settings: `"terminal.integrated.shell.windows": "wsl.exe",`
Run a task. Example: 

		{
			"type": "shell",
			"label": "echo",
			"command": "echo hello",
			"problemMatcher": []
		}

The task should run and *not* have the message: /bin/bash: /d: No such file or directory
The terminal process terminated with exit code: 127

**Comment by chrmarti** [comment]
@alexr00 There is still an error:
![image](https://user-images.githubusercontent.com/9205389/52119970-395ed700-261b-11e9-9c4e-e4a2ca430362.png)

**Comment by alexr00** [comment]
@chrmarti, I can't reproduce this. What version of Windows are you on?

**Comment by chrmarti** [comment]
@alexr00 This is 10.0.17134.

**Comment by alexr00** [comment]
@chrmarti can you try running `wsl.exe -e echo hello` from cmd.exe? Can you paste the output of running `wsl.exe --help` from cmd.exe?

**Comment by chrmarti** [comment]
```
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\chrmarti>wsl.exe -e echo hello
/bin/bash: - : invalid option

C:\Users\chrmarti>wsl.exe --help
/bin/bash: --: invalid option
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
```

**Comment by alexr00** [comment]
Thank you! Looks like there would need to be a Windows version check since the build that you're on appears to just wrap bash.exe and the more recent build that I'm on has different argument options:
````
C:\Users\alros\repos\vscode\vscode>wsl.exe --help
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.
````

This is a different problem, so I opened a new issue: https://github.com/Microsoft/vscode/issues/67855
