### ISSUE TITLE
The SVG-specific CSS attribute "vector-effect" is not highlighted

### ISSUE THREAD

**Issue by LIXiangChen** [Microsoft/vscode#63745]

**Comment by LIXiangChen** [comment]
![999](https://user-images.githubusercontent.com/8857634/49850062-2a2b8c00-fe17-11e8-8dd2-76e60eebbc74.png)

@alexr00

**Comment by alexr00** [comment]
Thank you for the example! It looks like atom is no longer maintaining the CSS grammar we use. I think we might move to https://github.com/octref/language-css so I am moving the issue to that repository.
