### ISSUE TITLE
vs code reveretd when SAVED file!!! Lost Full day of important work!

### ISSUE THREAD

**Issue by nityansuman** [Microsoft/vscode#63746]
- VSCode Version: 1.29.1
- OS Version: MacOs Mojave

**Comment by bpasero** [comment]
@nityansuman how exactly did that happen and is it reproducible?

**Comment by bpasero** [comment]
@nityansuman is it possible that an external tool changed the file? Was the file dirty?

**Comment by nityansuman** [comment]
No not possible. The file was totally fine. It was running with correct output. I didn't make any changes after saturday evening and then when opened sunday night, it got reverted back after it got hanged and it restarted.

**Comment by bpasero** [comment]
So to recap:
* the file was not dirty
* the file was opened in VSCode (visible)
* the file suddenly turned into its previous contents
* Code crashed and restart?

**Comment by nityansuman** [comment]
Yes code crashed and restarted. And code was open in vs code. When i opened i could only see the reverted file on sunday night, when the last time i saw was on saturday evening and it was working fine. No changes made after that.

**Comment by bpasero** [comment]
Ok, please report back if you found steps to reproduce. Closing until then.
