### ISSUE TITLE
Unable to start VS Code on Windows 10 when offline

### ISSUE THREAD

**Issue by MonsieurLeSuisse** [Microsoft/vscode#63748]
Issue Type: <b>Bug</b>

Why are all those similar issues closed when the defect still isn't fixed? Some of them were already raised in September, gosh.

Reproduce it: 
1. Switch off all network/internet connections
2. Try to open VS Code
3. Nothing happens
4. Switch on network/internet adapters
5. Try to open VS Code
6. Editor opens as expected

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz (4 x 1512)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (4.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
ng-template|Ang|0.1.10
xml|Dot|2.3.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
code-runner|for|0.9.5
AngularMaterial|har|6.1.0
Angular-BeastCode|Mik|7.0.16
python|ms-|2018.10.1
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
nativescript|Tel|0.8.3
html-css-class-completion|Zig|1.17.1

</details>

**Comment by usernamehw** [comment]
Because they duplicate it?Because they duplicate it?
Because they duplicate it?Because they duplicate it?
Because they duplicate it?Because they duplicate it?

**Comment by usernamehw** [comment]
That issue is open - that means it's not fixed yet.

**Comment by MonsieurLeSuisse** [comment]
"Why are all those similar issues closed when the defect still isn't fixed? Some of them were already raised in September."

Is this hard to understand?
Fix it, then you don't see more of those duplicates.


please provide help. useless "duplicate, duplicare, duplicate" comments lack of any value.

**Comment by usernamehw** [comment]
> Why are all those similar issues closed when the defect still isn't fixed
* To have 1 issue to refer to (1 issue - 1 problem, easier for users and devs to find the issue and possible solutions)
* To count total number of upvotes for every problem (more upvotes -> bigger priority, comments don't matter)

Did you read that issue #7570? Maybe there are some workarounds or solutions.
