### ISSUE TITLE
使用Monokai 主题时菜单栏icon不能展示

### ISSUE THREAD

**Issue by qifanrui** [Microsoft/vscode#63742]
- VSCode Version: 1.29.1 (1.29.1)
- OS Version:  macos 10.14.1

Steps to Reproduce:

1.使用Monokai 主题时菜单栏icon不能展示

2. 
![image](https://user-images.githubusercontent.com/9126408/48980094-957b1b80-f0ff-11e8-9364-c04307fc8e00.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
