### ISSUE TITLE
Add a way to get removed text in TextDocumentChangeEvent

### ISSUE THREAD

**Issue by wyozi** [Microsoft/vscode#6374]
Seems like there is no way to get the removed text in onDidChangeTextDocument as the document has already been changed at this point.

It would be nice to have eg. `oldText` in the TextDocumentContentChangeEvent.

**Comment by alexandrudima** [comment]
@wyozi What would be the use-case?

The purpose of `TextDocumentContentChangeEvent` is to allow an interested party to correctly maintain a replica of the original document by applying the same edits described in it. We don't include an `oldText` because that would not be needed to maintain a replica.

**Comment by wyozi** [comment]
@alexandrudima my use-case is recreating [smart backspace](http://blog.jetbrains.com/idea/2014/07/the-backspace-key-gets-smarter-in-intellij-idea-14-eap/) in vscode. It should only trigger if you press backspace, delete only whitespace within that edit action and there is only whitespace on the left side of the cursor. I would need `oldText` support for checking that only whitespace was removed in the edit.

**Comment by alexandrudima** [comment]
@wyozi You could simply **take** the backspace key. e.g. 
``` 
"contributes": {
  "keybindings": [
    { "key": "backspace",
      "command":"myBetterBackspace",
      "when":"editorTextFocus && editorLangId==\"java\""
    }
  ]
}
```

And then you would activate your extension `onCommand:myBetterBackspace` and you would register `myBetterBackspace` and implement it better via `activeTextEditor.edit`.

**Comment by wyozi** [comment]
Ooh, I see. That's definitely a nicer way to do it. I guess that solves at least my need for this feature.

**Comment by alexandrudima** [comment]
:+1: Nice. I will close then this issue for now, if the need arises in the future we can create a new one or reopen it.

**Comment by CoenraadS** [comment]
Hello, I have a use-case for this feature

I am writing a bracket parser, to colorize brackets similar to RainBow Brackets extension.

However I am focusing on performance, and only want to trigger an update if a bracket has been added or removed, but currently I do not know when a bracket is removed.

**Comment by atishay** [comment]
Is there a sample class I can use to do the mirroring of the active document. With the changes being an array, this is complicated to set this up. There is no way to clone the TextDocument class.
