### ISSUE TITLE
How can I select whole word used by chain case?

### ISSUE THREAD

**Issue by Shineeeee** [Microsoft/vscode#63757]
I'd like to select word using by Shift+Alt.  
But I can't select that when word use chain case.  

ex.)
Now
chain-case(cursor point) → [Shift+Alt] → chain-(select to)case(select from)

Ideal
chain-case(cursor point) → [Shift+Alt] → (select to)chain-case(select from)

thanks

**Comment by alexandrudima** [comment]
@Shineeeee I'm not sure I follow. What does chain case mean? What commands are you executing precisely?
