### ISSUE TITLE
Sözcük Kaydirma hakkında önemli

### ISSUE THREAD

**Issue by exehakan** [Microsoft/vscode#63752]
Issue Type: <b>Feature Request</b>

Merhabalar kod yazarken kodlar sayfada uzayip gidiyor ve her seferinde ALT + Z yapmak zorunda kaliyoruz bunu kalıcı olarak nasıl tek seferde çözebiliriz. Teşekkürler..

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexr00** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
