### ISSUE TITLE
When debugging, add support for "run to current line"

### ISSUE THREAD

**Issue by 9527KGG** [Microsoft/vscode#63756]
When debugging, add support for "run to current line".

In Visual Studio, the default key mapping is ctrl+f10.

The request is for all debugger, etc, cpp debugger, python debugger ....

**Comment by isidorn** [comment]
There is already context menu in the editor -> Run To Cursor
You can also assign a custom keybinding to it

![screenshot 2018-11-26 at 10 41 25](https://user-images.githubusercontent.com/1926584/49005777-dad33380-f167-11e8-8a56-b98120ef176a.png)
