### ISSUE TITLE
Extensions are not installing even if i have a 4g broadband connections...

### ISSUE THREAD

**Issue by shaikhreza43** [Microsoft/vscode#63758]
Issue Type: <b>Bug</b>

Live server is not at all installing even if i reinstalled it again and again...

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
@shaikhreza43 Can you please enable the log level to trance using `Set Log Level` Command in Command Pallette and open the Shared Process Log in Output panel and check how the installation is going on?

If possible also paste the log here for us to understand what's happening.
