### ISSUE TITLE
Terminal Default View invalid spaces

### ISSUE THREAD

**Issue by tslin306** [Microsoft/vscode#63755]
Issue Type: <b>Bug</b>

Terminal Default View have a lot of new lines with space.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.82GB free)|
|Process Argv|D:\Working Personal\custom-scripts|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.3.2
vscode-icontheme-nomo-dark|be5|1.3.6
tortoise-svn-for-vscode|cds|0.1.1
githistory|don|0.4.3
xml|Dot|2.3.2
git-project-manager|fel|1.7.1
code-beautifier|mic|2.1.0
mssql|ms-|1.4.0
es6-css-minify|olb|2.2.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
