### ISSUE TITLE
Wrong display of title bar in extension debug mode

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#63753]
Issue Type: <b>Bug</b>

Repro: Debug an extension

![image](https://user-images.githubusercontent.com/4033249/48987414-6b136900-f0d3-11e8-8d21-c7c86ae849b3.png)

In Stable and previous versions, VS Code always use native title bar for debugging extensions.

VS Code version: Code - Insiders 1.30.0-insider (04cbc78e23eeddc368d634ed52402dbc6f28ebc9, 2018-11-23T09:59:01.374Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|-psn_0_2626177|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.4.1
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.6.1
prettier-vscode|esb|1.7.2
vscode-pull-request-github|Git|0.3.0
vscode-styled-components|jpo|0.0.25
theme-monokai-pro-vscode|mon|1.1.9
debugger-for-chrome|msj|4.11.1
vetur|oct|0.13.0
polacode|pnp|0.2.2
vscode-sort-json|ric|1.13.0
shader|sle|1.1.4
language-stylus|sys|1.10.0
vim|vsc|0.16.12

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@bpasero is this a result of https://github.com/Microsoft/vscode/commit/3c97c46937d14747b43db928033c90a0824ce1f2
