### ISSUE TITLE
Scrollbar appears with breadcrumbs enabled when not neeed

### ISSUE THREAD

**Issue by lllopo** [Microsoft/vscode#63764]
- VSCode Version: 1.29.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Launch VSCode
2. Create (Ctrl-N) or open several files
3. Click on a side panel button to expand the sidepanel (Explorer for example)
4. Click again to collapse the sidepanel

At this point a horizontal scrollbar appears in the tabs row, even though it is not necessary. The scrollbar disappears if/when you click on some tab (even the active one).

Does this issue occur when all extensions are disabled?: Yes

![clipboard 4](https://user-images.githubusercontent.com/5485902/49003331-61891000-f16a-11e8-9bb3-c1c22cbcd27f.png)

**Comment by bpasero** [comment]
@lllopo can you share your settings?

**Comment by lllopo** [comment]
There you go :

`{    
    "git.ignoreMissingGitWarning": true,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "editor.insertSpaces": false,
    "editor.codeLens": false,
    "editor.minimap.enabled": false,
    "editor.dragAndDrop": false,
    "editor.emptySelectionClipboard": false,
    "editor.hover.delay": 3000,
    "editor.quickSuggestionsDelay": 3000,
    "editor.renderLineHighlight": "gutter",
    "editor.showUnused": false,
    "editor.formatOnType": true,
    "editor.fontSize": 15,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.startupEditor": "newUntitledFile",
    "workbench.statusBar.feedback.visible": false,
    "workbench.settings.openDefaultSettings": false,
    "workbench.colorCustomizations": {
        "foreground": "#333333",
        "editor.background": "#ffffff",
        "editor.lineHighlightBackground": "#EAEAEA",
        "editorIndentGuide.background": "#f3f3f3",
        "editorIndentGuide.activeBackground": "#e0e0e0",
        "editorGutter.background": "#f9f9f9",
        //"editor.selectionBackground": "#cee7ff",
        "editorBracketMatch.background": "#cae5ff",
        "editorBracketMatch.border": "#ffffff00",
        "activityBar.foreground": "#FFFFFFED",
        "activityBar.background": "#232A35",
        "sideBar.border": "#D5D5D5",
        "widget.shadow": "#ffffff00",
        "scrollbar.shadow": "#ffffff00",
        "focusBorder": "#00000000",
        "titleBar.activeBackground": "#fafafa",
        "titleBar.activeForeground": "#333333",
        "titleBar.inactiveBackground": "#fafafa",
        "titleBar.inactiveForeground": "#aaaaaa",
        "tab.activeBorderTop": "#0099E1",
        "tab.activeBackground": "#f9f9f9",
        "tab.inactiveForeground": "#777777",
        "statusBar.noFolderBackground": "#232A35",
        "statusBar.background": "#232A35",
        "statusBar.foreground": "#ffffff",
        "menu.selectionBackground": "#1A7DC4",
        "menu.background": "#FAFAFA",
        "menubar.selectionBackground": "#d0d0d0",
        "breadcrumb.foreground": "#555555",
        "breadcrumbPicker.background": "#f9f9f9",
        "breadcrumb.background": "#f9f9f9",
        "editorLineNumber.foreground": "#B9B9B9",
        "editorLineNumber.activeForeground": "#777777",
        "list.activeSelectionBackground": "#1A7DC4",
        "list.activeSelectionForeground": "#FFFFFF",
        "list.inactiveSelectionBackground": "#e4eef7"
    },
    "window.closeWhenEmpty": true,
    "window.restoreFullscreen": true,
    "window.restoreWindows": "none",
    "window.newWindowDimensions": "maximized",
    "window.enableMenuBarMnemonics": false,
    "files.autoGuessEncoding": true,
    "files.hotExit": "off",
    "files.associations": {
        "*.ctp": "php"
    },
    "explorer.openEditors.visible": 0,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",       
    "html.format.indentInnerHtml": true,
    "html.format.indentHandlebars": true,
    "extensions.ignoreRecommendations": false,        
    "vscode_custom_css.imports": [
        "********************************************"
    ],
    "vscode_custom_css.policy": true,
    "vscode_custom_css.statusbar": true,
    "php.suggest.basic": false,
    "php.validate.executablePath": "*******************************************",
    "breadcrumbs.enabled": true,
    "workbench.iconTheme": "material-icon-theme",
    "sync.quietSync": true,
    "sync.removeExtensions": false,
    "sync.autoUpload": true,
    "sync.gist": "******************************",
    "sync.syncExtensions": true,
    "sync.autoDownload": false,
    "sync.forceDownload": false,
    "beautify.config": {
        "indent_with_tabs" : true,
        "content_unformatted" : ["pre", "textarea", "cms"]
    },
    "workbench.colorTheme": "Boxy Yesterday",
    "explorer.autoReveal": false,
    "explorer.enableDragAndDrop": false,
    "local-history.saveDelay": 1,
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
    "local-history.path": "${workspaceFolder}/.vscode",
    "files.exclude": {
        "**/.history": true,
        "**/.idea": true,
        "**/.vscode": true,
        "**/nbproject": true
    },
    "files.useExperimentalFileWatcher": true
}`

Just replaced some paths and sensitive stuff with "*"

**Comment by lllopo** [comment]
Nope, the issue disappears if I disable the breadcrumbs.

**Comment by jrieken** [comment]
<img width="529" alt="screenshot 2018-11-27 at 10 05 24" src="https://user-images.githubusercontent.com/1794099/49070458-fc95ee80-f22b-11e8-85fa-f22796d9bb95.png">

I cannot reproduce. Please try latest insider: https://code.visualstudio.com/insiders/

**Comment by lllopo** [comment]
> 
> 
> <img alt="screenshot 2018-11-27 at 10 05 24" width="529" src="https://user-images.githubusercontent.com/1794099/49070458-fc95ee80-f22b-11e8-85fa-f22796d9bb95.png">
> 
> I cannot reproduce. Please try latest insider: https://code.visualstudio.com/insiders/

Just tried it with vanilla insiders - still the same. As soon as I enable breadcrumbs the thing happens.

**Comment by lllopo** [comment]
I made a small video to demonstrate the issue. It uses latest insiders, but I can't upload here. Let me know, if it would be of any help and I'll put it somewhere so you can view it.

**Comment by jrieken** [comment]
> It uses latest insiders, but I can't upload here.

zip it

**Comment by jrieken** [comment]
I can still not reproduce, please distill your settings (which I have tried this with) and/or steps so that I can reproduce. There is nothing else I can do before that

**Comment by jrieken** [comment]
I can still not reproduce, please distill your settings (which I have tried this with) and/or steps so that I can reproduce. There is nothing else I can do before that

**Comment by lllopo** [comment]
> 
> 
> I can still not reproduce, please distill your settings (which I have tried this with) and/or steps so that I can reproduce. There is nothing else I can do before that

The video is shot on vanilla insiders - zero custom settings, zero extensions. I only changed the color theme to Light+ for better visibility and the change on the breadcrumbs on/off that is visible on the video itself. 
The other thing I though might be related is that I'm using my display to 125% scaling, but I switched to 100% and repeated the test - all the same, so it is not that either.

**Comment by lllopo** [comment]
What I can add further is what I see in the DevTools inspector - the issue is due to the fact, that the sidebar is closed, the tabs horizontal scrollbar is set to some inadequately small value (like 200-300 pixels) and gets fixed be most actions like changing the windows size, adding a new tab ... even clicking on any tab including the active one (clicking outside the tabs on the tab bar does not fix it, though). So :
- opening sidebar - tabs scrollbar div width calculated properly
- closing sidebar - scrollbar div width calculated totally wrong
- resize something, click on tab, add a tab - scrollbar width recalculated properly

**Comment by lllopo** [comment]
Edit : The "inadequately small width" remains the same for a while. Like if it is 214px, no matter how many times you expand or collapse the sidebar - it remains 214px, but it varies over time - could be 244px, 167px ... anything. Still can't find what causes it to change from one value to another, nor is this value related to something. For now I observed the following :
- changing the sidebar width **changes** the weird value
- changing the number of tabs does **not** change the weird value
- changing the editor size (changing the window size or dragging devtools while docked left) does **not** change the weird value

**Comment by jrieken** [comment]
I have a hard time to follow. How are the last two comments related to breadcrumbs? Also, I do exactly when you say in https://github.com/Microsoft/vscode/issues/63764#issuecomment-442026681 and I cannot reproduce. Please focus and providing repro steps

**Comment by lllopo** [comment]
> 
> 
> I have a hard time to follow. How are the last two comments related to breadcrumbs? Also, I do exactly when you say in [#63764 (comment)](https://github.com/Microsoft/vscode/issues/63764#issuecomment-442026681) and I cannot reproduce. Please focus and providing repro steps

I'm just trying give you all clues and info I can gather. The width of the scrollbar div when collapsing the sidebar is definitely calculated wrongly at my place. How this is related to breadcrumbs I don't know. Have to find and read the relevant vs code source to sort it out, but I don't have the time for that right now. As of reproduction steps - you saw the video - it just happens easily on my machine with a freshly installed latest insiders. For now I haven't found another way to cause this, so you can try it too. If you have any test I can conduct on my copy - just let me know.

**Comment by bpasero** [comment]
@jrieken the size I get is wrong, `offsetWidth` should always be the size of the container as it appears on screen, but I get much smaller width after toggling the sidebar once, which explains why the scrollbar decides to show up, even though the visible space is enough.

**Comment by lllopo** [comment]
> 
> 
> I found out so far that the call to:
> 
> [vscode/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts](https://github.com/Microsoft/vscode/blob/130e81f154d518166d44540432b90af7d8a67368/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L983)
> 
> Line 983 in [130e81f](/Microsoft/vscode/commit/130e81f154d518166d44540432b90af7d8a67368)
>  this.breadcrumbsControl.layout({ width: dimension.width, height: BreadcrumbsControl.HEIGHT }); 
> 
> Makes my call to
> 
> [vscode/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts](https://github.com/Microsoft/vscode/blob/130e81f154d518166d44540432b90af7d8a67368/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L987)
> 
> Line 987 in [130e81f](/Microsoft/vscode/commit/130e81f154d518166d44540432b90af7d8a67368)
>  const visibleContainerWidth = this.tabsContainer.offsetWidth; 
> 
> Go nuts for some reason. I cannot explain that given the breadcrumbs live in a different container than the tabs scrollbars.
> 
> Open for help if someone has clues.

I'm debugging it here with the DevTools console, and the offset width is actually wrong even before the call to 'this.breadcrumbsControl.layout'. I mean - if you put a breakpoint before line 983 and check the offsetWidth - it is already wrong ... at my place at least.

**Comment by bpasero** [comment]
@lllopo ah ok good to know, but I cannot reproduce when I remove that call so it must be related...

**Comment by bpasero** [comment]
fix via https://github.com/Microsoft/vscode/pull/64364

**Comment by sandy081** [comment]
Are there steps to verify this?
