### ISSUE TITLE
Please add Class Viewer

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode#6376]
Please add a Class Viewer for Typescript 
![classview](https://cloud.githubusercontent.com/assets/11835025/15271523/2081d1cc-1a4f-11e6-8096-85b69a0667ad.jpg)
like QT Creator has for C++

**Comment by dbaeumer** [comment]
@chrisdias assigning to you. This is more a general product decision.

**Comment by RobertoMalatesta** [comment]
@chrisdias @dbaeumer @isidorn @egamma 

I've already open this issue on Nov 21st, see:
[https://github.com/Microsoft/vscode/issues/397](https://github.com/Microsoft/vscode/issues/397)

and it went on the backburner as well.

Can you please tell me if you have plans to implement it in a not too distant release
or if it's somehow seen as non-priority or against the product philosophy feature?

Besides, with the current API I don't think a user plugin can:
- add a button under the debugger icon one
- create a vertical split window or substitute the File Lister
- call Typescript compiler API and extract AST+TS files infos.

All this can be only accomplished by intervening in the core code of VSC.

Thank you for the time and all the good work!

-- R

**Comment by egamma** [comment]
@RobertoMalatesta VS Code supports the 'Go to Symbol...' action which allows you to quickly navigate to a method, property inside a typescript file. 

![image](https://cloud.githubusercontent.com/assets/172399/15360578/6d484e34-1d0e-11e6-9bc3-d86c6005e944.png)

**Comment by rakkarage** [comment]
:+1: 
a tree version of that for the whole project or folder would be excellent

**Comment by RobertoMalatesta** [comment]
Problem solved switching back to Webstorm Jetbrain.
Unfortunately as some of my projects reach 30k lines and hundreds of classes VSC is no longer productive. Too many lacking basic features. Will try again in 6 months or so to see if the product matures.

-- R
