### ISSUE TITLE
Vscode source code version management exception

### ISSUE THREAD

**Issue by flyrise** [Microsoft/vscode#63769]
The source code downloaded through git shows that most of the files have changed after opening with vscode, but the command executed through the console (git diff) shows no change.
![20181126175943](https://user-images.githubusercontent.com/7049655/49006910-21934e80-f1a5-11e8-81fd-bb448e48f9c0.png)
VS Code version: 1.29.1(user setup)
![image](https://user-images.githubusercontent.com/7049655/49007182-d168bc00-f1a5-11e8-8a5e-bbf0523ab572.png)

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?

**Comment by flyrise** [comment]
![image](https://user-images.githubusercontent.com/7049655/49008064-e6464f00-f1a7-11e8-88ec-ace104dded35.png)

**Comment by joaomoreno** [comment]
Can you show me the **full output**? Copy/paste

**Comment by flyrise** [comment]
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.16.1.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: d:\bobhbs\feesbFront1
> git status -z -u
> git show :buttons.html
> git check-ignore -z --stdin
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin

**Comment by joaomoreno** [comment]
What does `git status` return?
