### ISSUE TITLE
CallStackFree throws on stopping

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#63774]
- checkout isidorn/debugTrees branch
- run VS Code out of source
- debug any node.js program
- stop debugger by pressing the red stop button.

Observe this error in CallStackDataSource:
![2018-11-26_12-36-02](https://user-images.githubusercontent.com/1898161/49011870-e890b500-f177-11e8-9d57-153f2be79031.png)

**Comment by isidorn** [comment]
This branch is still work in progress let's close as dup of #63773

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/f58495335dbae2d285d0e98ce975a7ec7b1e2774
