### ISSUE TITLE
HTML/CSS Intellisense and Format-on-save not working

### ISSUE THREAD

**Issue by raghavdasila** [Microsoft/vscode#63778]
In the previous version of Code, I disabled all on-save properties for HTML. However, upon deleting (to restore functionality) those user settings, HTML/CSS intellisense stopped working along with format on save. Tried upgrading, re-installing and deleting user-settings , but it didn't help. The same problem does not occur in Windows 10.
Have tried disabling and re-enabling all extensions too.
Also, in-built issue raiser gives Error 500 code in browser.

System Information:
OpenSUSE Leap 42.3
CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3523)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwarevideo_decode: unavailable_softwarevideo_encode: unavailable_softwarewebgl: enabledwebgl2: enabled
Load (avg) | 2, 3, 2
Memory (System) | 7.57GB (4.32GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%

**Comment by raghavdasila** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [White toolbar after upgrading to 1.26.0 (#56427)](https://www.github.com/Microsoft/vscode/issues/56427)
> 
>     * [Opening links from VSCode brings up infinite instances of winebrowser (#63672)](https://www.github.com/Microsoft/vscode/issues/63672)
Tried all I could find, to no avail. Essentially tinkering around the settings to disable format on save, disables intellisense and format on save permanently.

**Comment by octref** [comment]
What's your VS Code version? Does this happen on 1.30.1?
