### ISSUE TITLE
Impossible to type dash (-) in terminal

### ISSUE THREAD

**Issue by wanglzuz** [Microsoft/vscode#63779]
Issue Type: <b>Bug</b>

For the past ~1 month, whenever I use the VS Code terminal, I am unable to type in the character dash "-". Upon pressing the key, nothing happens and I must paste the character in from the clipboard if I need it. (Needless to say, it works fine with other programs and it also used to work fine in VS Code, too.)
OS: Ubuntu 16.04.2 LTS

VS Code Info
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

I would be happy to provide any more feedback necessary. Thanks for looking into this issue.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
plantuml|jeb|2.9.10
docthis|joe|0.7.1
graphql-for-vscode|kum|1.12.1
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.4.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.2
stylelint|shi|0.46.1
autoimport|ste|1.5.3
gitblame|wad|2.6.1
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by Tyriar** [comment]
I can't seem to reproduce. Here are some things you could try:

- Do you have an IME active, and what keyboard layout are you using?
- Close all windows and launch with `code --disable-extensions`
- Share your settings.json file
