### ISSUE TITLE
App wide color picker

### ISSUE THREAD

**Issue by axe-z** [Microsoft/vscode#63777]
Stop saying it's duplicated, IT'S NOT ANSWERED IN ANY WAY #52364

VSCode Version: latest
OS Version: Mac OS Latest
HOW IS THIS EVEN POSSIBLE... AN EDITOR WITH NO COLOR PICKER FOR JAVASCRIPT BUILT IN.
I'M NEW TO VSCODE, BEEN LOOKING FOR AN HOUR, I COULD NOT COME TO REALIZE IT'S NOT THERE... GEEZ. GO BOTS BO ... OH MICROSOFT ...

every avenue ends up with a closed issues request with no answers except you can code your own.
come on. the color picker should be available all over. most css is done in js for a long time now.

Stop saying it's duplicated, IT'S NOT ANSWERED IN ANY WAY #52364

**Comment by rebornix** [comment]
A pull request is always welcomed.

**Comment by axe-z** [comment]
well, there is no answer right now to the problem, always pointing back to a closed case (#52364) that has no info whatsoever. A color picker is a must in an editor, and for MAC, there is nothing available.

**Comment by octref** [comment]
#52364 is open so please just follow that. All caps complaint helps no one.
You can use https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color or https://marketplace.visualstudio.com/items?itemName=lihui.vs-color-picker, or help contribute / build-your-own.

**Comment by axe-z** [comment]
both of them , well one of them is windows only, and mac for devs is not a single digit player, the other one is terrible, slow and an outside window . It's beyond me not to have a color picker working for JS.

**Comment by DavidHanover** [comment]
both extensions are terrible and this functionality should be integrated into the app anyway.
