### ISSUE TITLE
CallStackFree throws on stepping

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#63773]
- checkout isidorn/debugTrees branch
- run VS Code out of source
- debug any node.js program

Observe "data tree node not found" error:
![2018-11-26_12-31-57](https://user-images.githubusercontent.com/1898161/49011736-88017800-f177-11e8-8ddb-cf4e77fdc1bf.png)

**Comment by isidorn** [comment]
Fixed via 767b4302dc
