### ISSUE TITLE
Remap changed folder location

### ISSUE THREAD

**Issue by bahiirwa** [Microsoft/vscode#63771]
I usually change the location of my projects and thus lose their connection to a workspace. 

Can a feature be added to allow for a folder to be re-linked to the workspace without deleting and re-dragging and drop or adding folder afresh?

**Comment by bpasero** [comment]
@bahiirwa you can always just edit the workspace file, no? It is just JSON with the paths inside. When you update the file the explorer will also update. 

![image](https://user-images.githubusercontent.com/900690/49027109-bd21c080-f19f-11e8-9cc6-7accaa035ff3.png)
