### ISSUE TITLE
No syntax highlighting or Intellisense for some languages

### ISSUE THREAD

**Issue by OctarineSorcerer** [Microsoft/vscode#63772]
Issue Type: <b>Bug</b>

Install and enable "elm" extension
Create a directory for project, cd into it
Run `elm init`
Create a Main.elm in /src, copy-paste contents of https://github.com/dwyl/learn-elm/blob/master/examples/counter-reset.elm into it.
Expected: Syntax highlighting and Intellisense
Actual: No syntax highlighting or Intellisense
![image](https://user-images.githubusercontent.com/6842867/49011629-d4948580-f16e-11e8-9ef6-81ddd5b34520.png)

Issue remains with all extensions disabled with window reloaded, and with just the Elm extension enabled. Issue remains with Insiders Edition.
It also seems to happen with F# files, but not for Python. Files involved are syntactically correct, and in the above example, `elm reactor` builds and displays it correctly.

VS Code version: Code - OSS 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-14T00:41:55.375Z)
OS version: Linux x64 4.19.2-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1489)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (1.50GB free)|
|Process Argv|/usr/lib/code/code.js --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
eppz-code|epp|1.2.41
vsc-material-theme|Equ|2.6.1
base16-generator|gol|1.8.0
gc-excelviewer|Gra|2.1.26
r|Iku|1.0.0
Ionide-fsharp|Ion|3.30.0
latex-workshop|Jam|5.17.3
docomment|k--|0.1.2
unity-code-snippets|kle|1.3.0
python|ms-|2018.10.1
csharp|ms-|1.16.2
color-highlight|nau|2.3.0
vscode-icons|rob|7.28.0
elm|sbr|0.23.0
unity-debug|Uni|2.6.6
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by rebornix** [comment]
Please file issue against the elm extension you are using.
