### ISSUE TITLE
different regexp in single and multiple file(s) replace

### ISSUE THREAD

**Issue by usiebig** [Microsoft/vscode#63786]
Issue Type: <b>Bug</b>

the regexp   \[\\'(\d+)\\'\]     works for replace-in-single-file, to replace in multiple files   \['(\d+)'\]    is to be used

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.43GB (6.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.10.1

</details>

**Comment by roblourens** [comment]
What's the purpose of escaping `\'`? It should work without the backslash in single file replace.

Search is more picky about unneeded escapes.

**Comment by usiebig** [comment]
The point is is not about escaping the quote, the point is the different behaviour for single and multi-file substitution

**Comment by roblourens** [comment]
Yes, the editor uses the javascript regex engine, and search uses the rust regex engine (or pcre2) via ripgrep. https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
