### ISSUE TITLE
markdown preview  can not support multiselect ?

### ISSUE THREAD

**Issue by shanyuk** [Microsoft/vscode#63789]
Issue Type: <b>Bug</b>

I edit a markdown as following:
* [] * to do1 .

and the preview cannot display the select effect.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.27GB free)|
|Process Argv|C:\Users\xiao\AppData\Local\Temp\scp38926\home\qu\project\myoauth\myaccounts\models.py|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.3.0
vscode-es-beautifier|dai|1.1.0
vsc-invoke|dch|0.0.9
vscode-html-css|ecm|0.2.0
vue-snippets|hol|0.1.9
ftp-sync|luk|0.3.4
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
python-docs|Muk|0.8.3
vetur|oct|0.14.0
python|tht|0.2.3
vscode-react-native|vsm|0.6.18

</details>

**Comment by mjbvz** [comment]
I don't understand your issue. Please explain:

- The exact steps you are performing 
- The expected behavior
- The actual behavior
