### ISSUE TITLE
安装插件时,在搜索或下载插件页面好慢.切换到另外窗口.就马上把安装插件界面给关了

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#6378]
- VSCode Version:
- OS Version: windows 1.1

Steps to Reproduce:

1. Ctrl+p后.搜索某个插件
2. 比喻填上ext install crane 会进行等待差不多1分钟,才能显示出来插件列表.
3,在这个等待过程中.界面不能失去焦点.不然就取消了插件的下载或安装.
这个体验很不好.希望能在后台自动下载安装.可以最小化或切换到另外的程序或窗口.避免长时间等待...

**Comment by baoziv587** [comment]
😃 我建议你用机器人稍微翻译下把 :) 
另外编辑到相关label下

**Comment by rebornix** [comment]
What he is saying, the extension downloading is kind of slow and if you switch windows while installing extensions, the command pallete is gone.

I suppose this is an known issue and we'll cover this in following sprints.

**Comment by joaomoreno** [comment]
Thanks @lifetin and @rebornix !

**Comment by rhythmer** [comment]
TOO SLOW！！
