### ISSUE TITLE
IDE's edit area always appears a big block to cover it with cursor blinking.

### ISSUE THREAD

**Issue by Lanzz1994** [Microsoft/vscode#63782]
The problem appears usually after changing editing row in last and keeping pressing ‘Enter’ key to add some rows.

**Comment by rebornix** [comment]
@Lanzz1994 can you try run vscode by `code --disable-gpu` and see if it still happens?

**Comment by Lanzz1994** [comment]
> @Lanzz1994 can you try run vscode by `code --disable-gpu` and see if it still happens?

I'm tried, but probram still exists.

![vscode](https://user-images.githubusercontent.com/29368329/49051772-319e4300-f224-11e8-88a7-ffc76172fdda.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
