### ISSUE TITLE
Terminal process didn't stop after closing VS Code

### ISSUE THREAD

**Issue by arex0** [microsoft/vscode#63787]
Issue Type: <b>Bug</b>

The terminal process did not stop, when I ran "sudo go run service.go", but I closed vscode.
Live Server has same bug.
After computer sleep, some components of vscode become all white

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.0-2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3463)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.75GB (0.33GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2
cpptools|ms-|0.20.1
Go|ms-|0.7.0
debugger-for-chrome|msj|4.11.1
gradle-language|nac|0.2.3
java|red|0.34.0
LiveServer|rit|5.2.0

</details>

**Comment by Tyriar** [comment]
> After computer sleep, some components of vscode become all white

This is limitation in Chromium.

**Comment by Tyriar** [comment]
Typically these sorts of issues are related to server software itself not dying when the parent process dies.
