### ISSUE TITLE
Check Angular server 

### ISSUE THREAD

**Issue by trustbkarim** [Microsoft/vscode#63781]
Issue Type: <b>Bug</b>

Hello world !

Very good IDE, but sometimes when i try to check my server in Angular (ng serve), it's bug, hope you solve it ASAP.

Thank you 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3550  @ 3.07GHz (8 x 3066)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|12.00GB (6.83GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rebornix** [comment]
can you elaborate more on "check my server in Angular (ng serve), it's bug" ?

**Comment by trustbkarim** [comment]
Sometimes in Angular, if i would like to set a command in terminal, it's appear a dark page, so i have to restart my vscode to set that command. Thank you for replying 
![capture](https://user-images.githubusercontent.com/10914667/49066386-38778680-f221-11e8-85e3-9777ef91e972.PNG)

**Comment by Tyriar** [comment]
This is Chromium not keeping the canvas texture around, you can see the minimap is also black because it uses canvas.
