### ISSUE TITLE
Auto-Import with aliases not working

### ISSUE THREAD

**Issue by mathieulachance** [microsoft/vscode#63780]
Since the last update of VS Code, I can't use the auto import feature anymore when I try to import modules with path aliases. I am developing a React App and therefore no TypeScript is involved.

- VSCode Version: 1.29.1
- OS Version: Windows 10 (1709)

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a path alias in jsconfig.json :`{ "compilerOptions": "path": { "@components" : ["./src/components/index.js"] } }`. The index file at the specified path imports all the components of the folder.
2. Go in another file and import a component from the specified alias. The expected imported path should be : `import { Component1 } from "@components";`, but the auto imported path ends up having the full path to the component : `import { Component1 } from "src/components/component1 /component1";`. 

I've searched online and tried creating a tsconfig.json with the same path aliases. It seems like this fixes the issue, but my main concern is that I'm not using any TypeScript in my project and therefore should not be using a tsconfig.json file since I already have a jsconfig.json file.

**Comment by mjbvz** [comment]
Can you please check that your js files are part of the jsconfig. In the js file, run the `JavaScript: Go to project configuration` command. Does this open the correct `jsconfig`? 

Also, in the `jsconfig`, try setting `baseUrl` too:

```json
{ "compilerOptions": { "paths": { "@components" : ["./src/components/index.js"] }, "baseUrl": "." } }
```

**Comment by mathieulachance** [comment]
The command opens the correct jsconfig file.

I had the `baseUrl` already set. Here is what my jsconfig file looks like:

```
{
    "compilerOptions": {
        "target": "esnext",
        "baseUrl": ".",
        "paths": {
            "@components": ["./src/components/index.js"],
            // more path aliases here
        },
        "jsx": "react"
    },
    "exclude": ["node_modules", "dist"],
    "checkJs": true
}
```

**Comment by mathieulachance** [comment]
Hey @mjbvz ! I haven't heard back from you. Do you need more information on my setup?

**Comment by patricklafrance** [comment]
Any news on this issue?

**Comment by kallebornemark** [comment]
I am also having this issue. The "auto import" suggestion while typing works as expected:

<img width="494" alt="Screenshot 2019-04-18 at 14 42 40" src="https://user-images.githubusercontent.com/10062735/56362234-aa109b00-61e9-11e9-8dbe-14f0cd8f2f1c.png">

But the "quick fix" does not:
<img width="491" alt="Screenshot 2019-04-18 at 14 53 50" src="https://user-images.githubusercontent.com/10062735/56362315-d1676800-61e9-11e9-9d3f-b380e2be06e7.png">

---

#### Configuration

**`webpack.config.js`**
```js
resolve: {
  alias: {
    '@components': path.resolve(__dirname, '../src/components'),
  },
}
```

**`jsconfig.json`**
```json
{
  "compilerOptions": {
    "baseUrl": "./src/",
    "allowSyntheticDefaultImports": true,
    "paths": {
      "@components": [
        "components"
      ],
    },
    "module": "commonjs",
  },
  "exclude": [
    "dist",
    "node_modules"
  ]
}

```

**Comment by mjbvz** [comment]
@mathieulachance Can you please share a small example project that demonstrates this issue
