### ISSUE TITLE
vs code does not save during coding 

### ISSUE THREAD

**Issue by mlnejib** [Microsoft/vscode#63794]
Issue Type: <b>Bug</b>

1- Write anything
2- Save
3- Open in browser 
4- No changes seen

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.3.9600

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0

</details>

**Comment by rebornix** [comment]
> open in browser

Can you elaborate more on this one?
