### ISSUE TITLE
Open files do not update automatically after performing `git reset` 

### ISSUE THREAD

**Issue by geuis** [Microsoft/vscode#63798]
- VSCode Version: 1.29.0
- OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Check out a branch on a repo. Make changes to a file and save the changes.
2. From the interactive terminal in VSCode, perform a `git reset --hard HEAD` to reset the changed files back to head.
3. From the terminal, `cat <file.ext>` and see the changes have been reset.
4. Examine the file that is open in VSCode. See that the changes have not been reverted. VSCode's text editor is now out of sync with the file system.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
Can you run the same example using `code --verbose`? Check the output to see if Code picks up file events.

**Comment by willashley23** [comment]
I have this issue as well, only it happens when you use the interactive git UI in addition to the terminal. If you revert a file in the git sidebar while that file is still open, it doesn't update and making changes to that file and saving forces you to diff it.
