### ISSUE TITLE
Add more types to CompletionItemKind/SymbolKind 

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#63802]
This would allow our C/C++ extension to show a different icon. Also applies to Objective-C and D. Our workaround is to use the "Struct" icon with additional text "(union)" at the end of the symbol.

This is what Visual Studio shows:
![image](https://user-images.githubusercontent.com/19859882/48880516-b96bf380-edc5-11e8-8723-1d6266671b4e.png)

**Comment by jrieken** [comment]
- [ ] TypeAlias
- [ ] Union

**Comment by jrieken** [comment]
Rule is that enough languages should support a type before it makes it into the API and editor and also into LSP

**Comment by dbaeumer** [comment]
Another one would be Marco for languages that have a pre-processor.

**Comment by sean-mcmanus** [comment]
@dbaeumer I assume you mean "Macro". Our C/C++ extension (and VS) currently uses CompletionItemKind::Constant for that, which seems sufficient so far since nothing else maps to Constant (maybe later we could map constexpr or const variables to Constant).

**Comment by JohanAhlen** [comment]
> Rule is that enough languages should support a type before it makes it into the API and editor and also into LSP

@jrieken How about adding the ability to register custom types (and corresponding icons) to use? It would make it  quite flexible and there would be no need to keep track of when enough languages support a type. I'm currently hitting this issue with SQL where there doesn't seem to be types for database, table, column etc.

**Comment by mike-luabase** [comment]
@JohanAhlen did you find a way around this?

**Comment by Himanshhhu** [comment]
@mike-luabase did you?

**Comment by geekley** [comment]
I've opened a new issue similar to this, requesting more construct types.
If y'all are interested, please upvote it so it doesn't die in 60 days.
