### ISSUE TITLE
Quick open shows duplicate files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#63807]
![image](https://user-images.githubusercontent.com/2193314/49044675-568ea980-f183-11e8-9d63-b6949f0589ef.png)

Seeing this makes me look closer at the folder path though in case there are 3 files in different folders. I think only the first item show up and the file results section be hidden in this case.

**Comment by Tyriar** [comment]
Also note the duplicated files in file results:

![image](https://user-images.githubusercontent.com/2193314/49044875-f77d6480-f183-11e8-896d-8c405feb97e3.png)

**Comment by chrmarti** [comment]
Adding @roblourens as I'm not aware of recent changes.

**Comment by roblourens** [comment]
Do you have multiple workspace folders? Is there a difference in the paths if you open the two dupes or do they open the same tab?

**Comment by Tyriar** [comment]
@roblourens relabelling required 😃

**Comment by roblourens** [comment]
I have no clue and can't repro. I probably just have to debug more on your machine.
