### ISSUE TITLE
The snippets for markdown is not valid.

### ISSUE THREAD

**Issue by AlanWalk** [Microsoft/vscode#6380]
- VSCode Version : 1.1.0
- OS Version : Deepin 15.1.1

I can't use snippets with markdown.

**Comment by startewho** [comment]
I have the same problem,same version,but OS is win10 x64 14342 insider

**Comment by alexandrudima** [comment]
@AlanWalk @startewho Can you please give me more details?

![98ohzmz4yr](https://cloud.githubusercontent.com/assets/5047891/15483584/b646245a-2135-11e6-8512-32773cfc7226.gif)

Do you have this problem when launching VSCode with `code --disable-extensions` ?

**Comment by AlanWalk** [comment]
Hi, The problem remains with `code --disable-extensions`.

- I type `bold`, no any tip display to.
- I add a snippet to `User Snippets`, and I type it, no any tip.

![gif](https://cloud.githubusercontent.com/assets/4654826/15489877/0d7ba8de-2196-11e6-8003-c6158803fc39.gif)

**Comment by alexandrudima** [comment]
Ok, figured it out, markdown was the only mode that completely disables auto-suggest. After discussion with @bpasero we've reached the conclusion that this is not good and markdown should behave like all the rest of the modes.

**Comment by joaomoreno** [comment]
@alexandrudima @bpasero 

Markdown should not behave like all the rest of the modes because it is a lyrical mode. People that write Markdown write in their own language, English, and when the press Enter they want a line break. Automatic suggestions specifically clash with this: I now can't write `link` as part of a sentence and press <kbd>Enter</kbd> to go to a new line, without having to press <kbd>Escape</kbd>. Note that since all the words in the document appear as suggestions, as soon as the document has a considerable size, many words will have this problem...

**Comment by alexandrudima** [comment]
We can discuss with the team, I have no strong feelings about this, I can revert my change... in fact I don't even know why I touched this to begin with...

**Comment by alexandrudima** [comment]
I have pushed a revert to my change for May, I now give the issue to its proper owner :).

**Comment by startewho** [comment]
So many editor can write markdown by snippet. why the VS code do the strange behavior ?

**Comment by alexandrudima** [comment]
@startewho snippets work in markdown and they have always worked. They simply do not show up automatically. They are one `ctrl+space` away.

**Comment by startewho** [comment]
@alexandrudima  Thanks for your reply. in the system whit Chinese language ,the   **ctrl+space** usually switch the English and Chinese input by default. In the last win10 ,I even can't change the short key.SO I define a vs code setting file.it works.

**Comment by AlanWalk** [comment]
It's conflict with chinese input, and no any tips. I think a simple Q&A page is useful for users.

**Comment by bpasero** [comment]
I am closing this because markdown is now a real extension like any other language.
