### ISSUE TITLE
Add PR comment via keyboard shortcut

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#63809]
I'd like to be able to add a comment with a keyboard shortcut, so the thing that happens when I click on the comment margin should be exposed via command. At least I think this is on vscode not the PR extension.

**Comment by RMacfarlane** [comment]
This was implemented with https://github.com/microsoft/vscode/commit/72a18e636b2d9f1ad866f0c9b3563b7d91973809, the action has no default keybinding but is called `workbench.action.addComment`
