### ISSUE TITLE
Add "TypeAlias" CompletionItemKind/SymbolKind

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#63804]
"Type alias" is whenever an identifier is used to reference another type by a different name, aka "typedef" or "using alias" (see https://en.cppreference.com/w/cpp/language/type_alias ).

Applies to the following languages: C, C++, Objective-C, D, C#, Go, Rust, Swift, and probably other languages.

Our C/C++ workaround is to use the "Interface" icon with the text "(typedef)" or "(type alias)" appended.

For Visual Studio with C++ it shows:
![image](https://user-images.githubusercontent.com/19859882/48880491-917c9000-edc5-11e8-9b35-3e19842aaeb8.png)

**Comment by jrieken** [comment]
folding into https://github.com/microsoft/vscode/issues/63802
