### ISSUE TITLE
Ripgrep in latest stable

### ISSUE THREAD

**Issue by shanff** [Microsoft/vscode#63819]
Issue Type: <b>Bug</b>

No matter what I do, and what i'm disabling, ripgrep is starting 3 processes each time I start up vscode, eating cpu for about 30 seconds.  I have it disabled to the best of my knowledge.  This is a recent development.  

had to disable git also, since it was heading down every folder on my system, even WSL and was causing even more slowdowns.  

    "git.autoRepositoryDetection": false,
    "npm.autoDetect": "off",
    "npm.fetchOnlinePackageInfo": false,
    "search.useLegacySearch": true,
    "git.autorefresh": false,
    "git.enabled": false,
    "git.autofetch": false,
    "search.runInExtensionHost": false,
    "search.usePCRE2": false

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.85GB (21.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-database|baj|1.5.2
vagrant|bbe|0.5.0
unique-lines|bib|1.0.0
color-info|bie|0.5.0
vscode-ripgrep|bok|0.2.2
path-intellisense|chr|1.4.2
regex|chr|0.2.0
transformer|dak|1.6.0
autoit|Dam|0.2.0
vscode-jq|dan|1.0.0
vscode-markdownlint|Dav|0.21.0
whitespace-plus|dav|0.0.5
xml|Dot|2.3.2
vsc-material-theme|Equ|2.6.1
json-tools|eri|1.0.2
prettier-vscode|esb|1.7.2
vimL|fal|0.0.3
code-runner|for|0.9.5
vscode-mysql|for|0.3.0
iniwrangler|fri|0.0.1
gc-excelviewer|Gra|2.1.26
ansible|haa|0.2.8
beautify|Hoo|1.4.7
rest-client|hum|0.20.3
reg|ion|0.0.2
vscode-text-pastry|jkj|1.2.0
vscode-insertdatestring|jsy|2.2.3
Lisp|mat|0.1.8
rainbow-csv|mec|0.8.0
prettify-json|moh|0.0.3
python|ms-|2018.10.1
PowerShell|ms-|1.9.0
sqltools|mtx|0.15.1
incrementor|nms|0.1.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
LiveServer|rit|5.2.0
vscode-icons|rob|7.28.0
partial-diff|ryu|1.4.0
text-marker|ryu|1.9.0
preview-vscode|sea|2.0.2
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.3.11
numbermonger|sof|0.3.0
enumerator|swi|0.0.6
html-preview-vscode|tht|0.2.4
pdf|tom|0.4.1
vscode-input-sequence|tom|0.2.0
org-mode|too|0.5.0
json2yaml|tux|0.2.0
markdown-all-in-one|yzh|1.7.0
inserttimestamp|zvl|1.1.3

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Is it rg.exe using high cpu, or windows antimalware (msmpeng.exe)?

**Comment by shanff** [comment]
It's the rg.exe processes that were holding the cpu hostage.  What's concerning to me is that even after  disabling any search related items and GIT, Git for Windows and rg.exe were still firing up.  Now, on a fresh start of VSCode, I'll usually get a handful of rg.exe processes that  ultimately drop to 3 rg.exe processes that each consume about 20% CPU for  however long it takes until they're finished.  

![image](https://user-images.githubusercontent.com/11064799/49183951-c89df480-f323-11e8-97ea-164f9d5ebdab.png)

**Comment by roblourens** [comment]
Can you get the command line arguments from those rg processes from task manager or the vscode process explorer?

Those should be from an extension and should go away if you start with `--disable-extensions`. We can figure out which extension from the command line args.
