### ISSUE TITLE
TERMINAL window become mosaic after resumes from system standby or hibernation.

### ISSUE THREAD

**Issue by shmilyoo** [Microsoft/vscode#63816]
- VSCode Version: All versions so far (≤1.29.1)
- OS Version:Ubuntu 16.04 LTS

Steps to Reproduce:

1.After the system resumes from standby or hibernation, the terminal window of vscode will become a flower screen/mosaic
2. Screen capture is as follows   
![](http://ww1.sinaimg.cn/large/566418e8ly1fxmb6t8vi8j20f3054gqo.jpg)    
3. I think it may be a problem with the graphics card driver, but I updated the driver and still have the same problem.   

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
This is a bug with Chromium's handling of the canvas texture after sleep

**Comment by shmilyoo** [comment]
@Tyriar Thank you, you saved my life. God knows what kind of mood I have to reload and start four project every time.
