### ISSUE TITLE
Git diff of image does not properly show resolution and size

### ISSUE THREAD

**Issue by TheV360** [Microsoft/vscode#63818]
Issue Type: <b>Bug</b>

1. Edit an image.
2. In the source control tab, see that the image has changed.
3. Click the image to view the Git diff.
4. Attempt to check the image's size and size. Unfortunately, it says undefined - undefined instead of 32x32 or something else.

I have attempted this without extensions and it does the same thing.

![image](https://user-images.githubusercontent.com/25177071/49050813-2d860d00-f1b3-11e8-9e86-1786ee7822b1.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (9.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
marshal-command-code|din|1.1.2
asciidecorator|hel|0.2.0
vscode-icon-theme|jtl|1.6.5
Lua|key|0.0.9
gml-support|lia|1.7.0
cpptools|ms-|0.20.1
pixelbyte-love2d|pix|0.1.18
vscode-icons|rob|7.28.0
vscode-autohotkey|sle|0.2.2
ayu|tea|0.17.0
language-pde|Tob|1.2.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Seems to work for me

![image](https://user-images.githubusercontent.com/22350/49136990-81940d00-f2eb-11e8-8e17-00e2c9cb333c.png)

**Comment by TheV360** [comment]
It's appearing on both my home and work installations.
Here's a more detailed description:

* My image is 32x32 with an alpha channel.
* It consists of around 8 colors, but I didn't make it a palette-based image
* It was created with Paint.NET.
* It's named `icon.png`, inside a directory named `resources/`

First, I used Paint.NET to make the image, then save it and commit it. Then, I used MS Paint to edit the image, removing its alpha channel. Then the info became `undefined <-> undefined`.
I reversed that change, and tried using Photoshop to edit the image. Again, the info became `undefined <-> undefined`.

**Comment by joaomoreno** [comment]
@TheV360 Maybe it's easier if you send us the image, so we can reproduce.

**Comment by marchenko-am** [comment]
It is unstable reproduceded bug. I try it whith several picture. In begin result was:
null ↔ null

When I start debug, result was:
1774x1707 224.41KB ↔ 1774x1707 336.80KB
or
1774x1707 224.41KB ↔ undefined
or
undefined ↔ undefined (rarely)

And now result is:
1774x1707 224.41KB ↔ 1774x1707 336.80KB

And bug not reproduced any more...

File for example:

![icon](https://user-images.githubusercontent.com/9570253/49628087-3a94ce80-f9f3-11e8-9a92-e2f051dc7ace.png)
