### ISSUE TITLE
Comment marks broken after edits

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#63812]
Issue Type: <b>Bug</b>

1. Enable adding comments to the document with use of `DocumentCommentProvider` on a editable document.
2. Make some changes in the text above the comments, e.g. insert some new lines.
3. The comment marks (these [+] signs to the left of the text) move with the text as expected.
4. Try to use these comment marks to expand or interact with the comments.

*Expected:*
Comment marks work.

*Actual:*
Comment marks do no work after moving. Clicking on the does nothing.

Even if the `DocumentCommentProvider` keeps track of the comment thread positions and fires `onDidChangeCommentThreads` event when the comment thread lines change, the comment marks still don't work after moving.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IlyaBiryukov** [comment]
@rebornix I can help with the fix for this bug if you are fine with that. Or I can help with another comment bug I just filed, #64042

**Comment by rebornix** [comment]
@IlyaBiryukov definitely go ahead!

**Comment by IlyaBiryukov** [comment]
Also the PR includes the fix to the new comment flow: 
1. User starts adding a new comment
1. User changes the comment position, e.g. by inserting new lines before it
1. User clicks "Add Comment"

With the fix, the comment will be added at the current position, where the comment thread widget is when the user clicks "Add Comment" button.

@rebornix Please review the [RR](https://github.com/Microsoft/vscode/pull/64906)

**Comment by rebornix** [comment]
Close this one as it's already out of date (PR mentioned above is merged and we are now on the new API).
