### ISSUE TITLE
Add "don't show again" to PCRE2 suggestion

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#63814]
The notification can show up for every regex parse error, which is annoying.

Also shows up for a bad character escape, can it be scoped down?

**Comment by isidorn** [comment]
@roblourens can you please add verification steps?

**Comment by roblourens** [comment]
- Ensure `search.usePCRE2: false`
- Search for a regex with backreference or lookahead pattern.
- A notification should show up suggesting that you enable `search.usePCRE2` (if you don't see it you may have hidden it already, try with a clean user data dir)
- The notification should have a "don't show again" option.

**Comment by isidorn** [comment]
Like all notificatinos it has a dont show again as a secondary action under the wrench
I think this is correct behavior, adding verified

![screenshot 2018-12-04 at 18 40 44](https://user-images.githubusercontent.com/1926584/49461507-2767e000-f7f4-11e8-9c1a-6eff99bffb57.png)

**Comment by roblourens** [comment]
It wasn't there until I added it...

**Comment by isidorn** [comment]
Ok, than it seems we only auto-add for extension notifications.
