### ISSUE TITLE
python 写的稍微长一点就很卡

### ISSUE THREAD

**Issue by fragno** [Microsoft/vscode#63825]
Issue Type: <b>Bug</b>

python 写的稍微长一点就很卡

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.20.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
flow-for-vscode|flo|0.8.5
vscode-mocha-sidebar|mat|0.20.20
python|ms-|2018.10.1
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.0
java|red|0.34.0
vscode-java-pack|vsc|0.4.0
vscode-maven|vsc|0.11.2
vim|vsc|0.16.12
vscode-todo-highlight|way|1.0.4

</details>

**Comment by rebornix** [comment]
Please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide more info for troubleshooting, thanks!
