### ISSUE TITLE
Wrong embedded language detected for empty lines

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#63822]
Issue Type: <b>Bug</b>

**Repo**
1. Create a js file:

```js
const a = (<div>

</div>);
```
1. Place cursor on blank line. Make sure there is no whitespace or any chracters on the line
1. Run the toggle comment command

**Bug**
`//` inserted instead of `{* *}`.

The root cause is that we detect the wrong embedded language using `getLanguageIdAtPosition`. For lines with zero tokens, we always seem to return the top level language instead of the current embedded language.

VS Code version: Code - Insiders 1.30.0-insider (456e8e64beb2dceac66743959f6802b66e18e300, 2018-11-26T10:55:58.730Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|50, 45, 23|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_18534828|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
I added a skipped, failing test for this in f0ebaad. The scope inspector seems to have the correct language but `getLanguageIdAtPosition` returns the wrong value

**Comment by alexandrudima** [comment]
:+1: Nice find! I had to remove the test because it was incorrect.
