### ISSUE TITLE
Syntax highlighting after Installation lost

### ISSUE THREAD

**Issue by kkleeberger** [Microsoft/vscode#6382]
- VSCode Version: 1.1.0 
- OS Version: windows 10  rel:14342 (german)

No C# Syntax Highlighting and no IntelliSense  after VS Code Update to Version 1.1.0.0
Same Situation on 2 different Machines

**Comment by isidorn** [comment]
C# is now an extension - https://code.visualstudio.com/Docs/languages/csharp
Please install that extension for a better experience https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
