### ISSUE TITLE
terminal(external)  does not work!!!!!!!

### ISSUE THREAD

**Issue by WangHongSen** [Microsoft/vscode#63820]
Issue Type: <b>Bug</b>

I want to use  external terminal when I hava set the "terminal.external.windowsExec":"terminal.external.windowsExec": "‪C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe". But when I began to use it , there is no response in the terminal , even any warning. 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.5
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
cpptools|ms-|0.20.1
rust|rus|0.4.10

</details>

**Comment by WangHongSen** [comment]
just like this
![default](https://user-images.githubusercontent.com/26568590/49051827-690cef80-f224-11e8-8bb5-5a80154ad235.PNG)
I have tried cmd, wsl bash, but useless.

**Comment by slowvoid** [comment]
I've experienced the same on Windows (cmd or powershell). But the terminal still works, if you type and valid command (such as 'cls' or 'clear') your input will be visible and as soon as you hit enter, the terminal will work as usual.

**Comment by Tyriar** [comment]
This setting sets the external terminal, not the shell for the integrated terminal:

```
"terminal.external.windowsExec": "‪C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
```

Use `terminal.integrated.shell.windows` instead for the integrated terminal.

**Comment by Tyriar** [comment]
Also you might be seeing https://github.com/Microsoft/vscode/issues/57803 which is a Windows 1809 bug.
