### ISSUE TITLE
Unable to open 'XXX.hpp': File not found (file:///c/Users/xxx/Desktop/x'x'x'x/include/XXX.hpp).

### ISSUE THREAD

**Issue by wu1274704958** [Microsoft/vscode#63828]
Issue Type: <b>Bug</b>

Debugging code to get this error 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.2

</details>

**Comment by rebornix** [comment]
It looks like an issue with the project you are running, not VSCode.
