### ISSUE TITLE
Menu item 'Check For Updates' should be disabled when there's no frontmost window

### ISSUE THREAD

**Issue by peter-lau** [Microsoft/vscode#6383]
- VSCode Version: 1.1.0
- OS Version: Mac OS X 10.11.4

Steps to Reproduce:

1. Launch VSCode
2. Close all windows
3. Go to menu 'Code' and select 'Check For Updates'
4. Nothing, no alert, no message.  Like the menu item was never selected.

**Comment by joaomoreno** [comment]
This is OK. The application will still be updated if there is an update in this situation.
