### ISSUE TITLE
Rejected promises with error msg from definition provider don't get shown to the user

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#63831]
- VSCode Version: Both latest Stable and Insiders

Steps to Reproduce:

1. Have an extension that registers a definition provider that always returns a rejected promise with an error message
2. Trigger the `Go to definition` command on a file for which the above provider was registered
3. You will see the standard `No definition found for ...`

<img width="282" alt="screen shot 2018-11-26 at 11 26 15 pm" src="https://user-images.githubusercontent.com/16890566/49065362-afd1f980-f1d2-11e8-9ea7-21991fe8d7a9.png">

The detailed error message from the extension is never shown.

One would think that the developer console would show the message, but that only shows

<img width="495" alt="screen shot 2018-11-26 at 11 27 20 pm" src="https://user-images.githubusercontent.com/16890566/49065425-d728c680-f1d2-11e8-847f-8be84bee7700.png">

Logs in the output channel for Extension Host don't show any errors. The one for "Window" has the below

<img width="795" alt="screen shot 2018-11-26 at 11 28 07 pm" src="https://user-images.githubusercontent.com/16890566/49065459-f32c6800-f1d2-11e8-91f1-15d03ac3c2c9.png">

**Comment by jrieken** [comment]
> The detailed error message from the extension is never shown.

Yes, that's the design and we have no plans to change that. The API doesn't offer a path for human readable error messages and all rejections are equals. All extension/provider failures end up calling this
https://github.com/Microsoft/vscode/blob/07d7409240aca5b1469e5c97727b4adb6840421c/src/vs/base/common/errors.ts#L138-L144

which is your code @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Yes, the design to not show it explicitly is understandable, but not showing the same in the Dev Tools console is not. We used to show these errors in the console, but not anymore. That's why I logged the issue.

The `onUnexpectedExternalError` part of the code hasnt been touched in ages, so I have a feeling that something else is causing this.

Currently, the `An unknown error occurred. Please consult the log for more details.` is not helpful as there is no log to consult.

**Comment by jrieken** [comment]
> Currently, the An unknown error occurred. Please consult the log for more details. is not helpful as there is no log to consult.

Can you check the extension host log? There should be an error message being printed (when running verbose) https://github.com/Microsoft/vscode/blob/2e339afec3cd1ad4d9ee1e622e3d35045fd4a545/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L960

**Comment by ramya-rao-a** [comment]
Changing the log level to `trace` does show the error message in the extension host log.
Given that this is an error, shouldn't it be shown even in the default log level of "Info" which covers the log level of "Error" ?

**Comment by jrieken** [comment]
I have pushed a change that logs provider failure as error.
