### ISSUE TITLE
Code prompt question

### ISSUE THREAD

**Issue by WAMG9264** [Microsoft/vscode#63830]
Issue Type: <b>Bug</b>

Code prompt problem, code prompt does not display text, display error, display is a lot of lines, I hope you can solve as soon as possible!

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3260 @ 3.30GHz (2 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
vscode-language-pack-zh-hans|MS-|1.29.2
vetur|oct|0.14.2
LiveServer|rit|5.2.0
guides|spy|0.9.2

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/43169
