### ISSUE TITLE
Search: Can't select search results

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#63834]
The click only seems handled when clicking on the text label of search results. When clicking elsewhere on tree rows, nothing happens.

**Comment by joaomoreno** [comment]
Caused by https://github.com/Microsoft/vscode/pull/63457

**Comment by roblourens** [comment]
Fixed, I'm not sure this was worth rereleasing insiders, but thanks for jumping on it.

**Comment by joaomoreno** [comment]
Yeah, maybe an overreaction, tho I hit it right in my first 2 minutes of the day. 😨
