### ISSUE TITLE
IntelliSense config option to disable click to accept

### ISSUE THREAD

**Issue by jibbers42** [microsoft/vscode#63849]
I would like to be able to click on an IntelliSense suggestion to select it without it being accepted. The primary use case is for viewing pop-up documentation without having to arrow to the desired member.

In the pic, it would be nice to select and read the documentation for `relative` without having to arrow to it.

![image](https://user-images.githubusercontent.com/797824/49078018-e0358a00-f20a-11e8-8d84-3b21dc5fa4db.png)

Apologies if I've missed how to do this.

### Version Info
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Ubuntu 18.10

**Comment by usernamehw** [comment]
Right mouse click seems to be selecting without accepting...

**Comment by jibbers42** [comment]
Ha! didn't think to try that.

I still think a config option would be cool so I'll leave it open - someone from the vscode team can feel free to close if they don't agree and if right-click is the intended way to do this.

**Comment by jibbers42** [comment]
In newer versions right click is selecting the list item. This seems to be new behavior; is there a setting to change this?
