### ISSUE TITLE
jsconfig.json paths only works with folders and .js file extension.

### ISSUE THREAD

**Issue by marbuser** [Microsoft/vscode#63843]
- VSCode Version: 1.29.1 (1.29.1)
- OS Version: macOS 10.14.1

So the issue I've found is that using the `jsconfig.json` config below, the `paths` option only shows folders and files with the `.js` file extension. This isn't ideal for people using tools other than JS such as VueJS, React, etc...

jsconfig.json
```
{
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": false,
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

So with this config for example, you can see below that folders are shown and that files with the `.js` extension are also shown;
![image](https://user-images.githubusercontent.com/34422459/49073956-941c3100-f26e-11e8-8b94-7dcb3b358782.png)

But if I navigate into a folder like `scss` or `components` where the file extensions are `.vue` and `.scss`, you can see that nothing is shown in the image below despite there being files inside that folder.
![image](https://user-images.githubusercontent.com/34422459/49074000-b746e080-f26e-11e8-956c-fc00a2189919.png)

So, I'm not sure if this is just me missing some option to enable this, or if this is an actual bug, but I figured it's worth posting here. I checked through the docs for `jsconfig.json` and I definitely didn't see any options about 'enabling other extensions'. To further add to this, if it was made like this by design, I don't think that's a very wise decision and there should perhaps be some discussion about changing this since I think we can all agree not everyone works in ONLY `.js` files.

An additional issue that I'm not really sure what it means or if it's something to be worried about, is that my `jsconfig.json` reports this intellisense error.
![image](https://user-images.githubusercontent.com/34422459/49073872-6636ec80-f26e-11e8-8de6-a399d5f2b57d.png)

**Comment by mjbvz** [comment]
Intellisense for non js/ts files is currently not supported. See https://github.com/Microsoft/TypeScript/issues/15146

**Comment by marbuser** [comment]
> Intellisense for non js/ts files is currently not supported. See [Microsoft/TypeScript#15146](https://github.com/Microsoft/TypeScript/issues/15146)

Care to elaborate a bit on this?
I don't really understand the technical aspect of it but I don't really understand how you can have it working for relative paths as shown below, but not for the aliases/paths. Isn't it essentially just looking for the alias and then pointing it to the result?
![image](https://user-images.githubusercontent.com/34422459/49124757-8c08d380-f2f8-11e8-8429-a3e425db4668.png)
