### ISSUE TITLE
CPU usage 100% when searching text or files (rg.exe issue)

### ISSUE THREAD

**Issue by malinengineer** [Microsoft/vscode#63840]
Issue Type: <b>Performance Issue</b>

When doing a test search (CRTL+SHIFT+F) or when trying to open a file with CTRL+P, the CPU usage spikes to 100%.
The process that hogs the CPU is "rg.exe"

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    83	  7848	code main
    0	   167	  3836	   window (fbl_ap.c - C:\Projekte\Ford\Ford_Platform_3\5430_HMI_CCP_Climate_Control_U625\06_Software\02_SW\01_Sources)
    0	    14	 13436	     watcherService 
    0	    89	 15756	     extensionHost
    0	    17	  8712	       c:\Users\micu_a1\.vscode\extensions\ms-vscode.cpptools-0.20.1\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    72	  3772	         c:\Users\micu_a1\.vscode\extensions\ms-vscode.cpptools-0.20.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 8712 0
    2	    68	  7832	   window (Issue Reporter)
    0	   175	  9392	   window (MemMap.h - C:\Projekte\VW_5481_HMI_ECU_37W_sandbox1\06_Software\02_SW\01_Sources)
    0	    14	  6808	     watcherService 
    0	    78	 12624	     extensionHost
    0	    43	 15200	       c:\Users\micu_a1\.vscode\extensions\ms-vscode.cpptools-0.20.1\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    12	  9652	         c:\Users\micu_a1\.vscode\extensions\ms-vscode.cpptools-0.20.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 15200 1
    1	    65	  9880	   gpu-process
    0	    56	 12504	   shared-process
    0	   222	 14880	   window (CM4F_bolo_load.cmm - C:\Projekte\Ford\HMI-CCP-CCH-P702_OTA_BOLO)
    0	    50	  3724	     searchService
    0	   108	 15648	     extensionHost
    0	    44	 15124	       c:\Users\micu_a1\.vscode\extensions\ms-vscode.cpptools-0.20.1\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    46	 12936	         c:\Users\micu_a1\.vscode\extensions\ms-vscode.cpptools-0.20.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 15124 3
    0	    18	 16192	     watcherService 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (MemMap.h - C:\Projekte\VW_5481_HMI_ECU_37W_sandbox1\06_Software\02_SW\01_Sources)
|  Window (fbl_ap.c - C:\Projekte\Ford\Ford_Platform_3\5430_HMI_CCP_Climate_Control_U625\06_Software\02_SW\01_Sources)
|  Window (CM4F_bolo_load.cmm - C:\Projekte\Ford\HMI-CCP-CCH-P702_OTA_BOLO)
|    Folder (01_Sources): 5720 files
|      File types: h(2550) c(1504) MySCMServerInfo(996) py(160) pdf(120)
|                  md(114) yaml(83) xlsx(64) tmb(42) epc(13)
|      Conf files: settings.json(1)
|    Folder (HMI-CCP-CCH-P702_OTA_BOLO): more than 23793 files
|      File types: h(3603) py(3318) opt(2440) a(1331) txt(1032) jar(895)
|                  c(859) MySCMServerInfo(754) xml(729) dll(541)
|      Conf files: makefile(688) package.json(7) cmake(3) settings.json(1)
|    Folder (01_Sources): 4691 files
|      File types: c(1381) h(1215) mak(751) MySCMServerInfo(719) MF(85) s(79)
|                  xml(75) epc(44) lib(41) xdm(40)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
vagrant|bbe|0.5.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.21.0
vscode-dash|dee|2.0.0
githistory|don|0.4.4
xml|Dot|2.3.2
vscode-great-icons|emm|2.1.44
gc-excelviewer|Gra|2.1.26
plantuml|jeb|2.9.10
vscode-rust|kal|0.4.2
VS-code-vagrantfile|mar|0.0.7
prettify-json|moh|0.0.3
python|ms-|2018.10.1
azure-account|ms-|0.6.2
cpptools|ms-|0.20.1
Go|ms-|0.7.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
vscode-icons|rob|7.28.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.2
vscode-hexdump|sle|1.7.2
selectline-statusbar|tom|0.0.2
cmake|twx|0.0.17
cmake-tools|vec|1.1.2
vscode-todo-highlight|way|1.0.4
debug|web|0.22.0

</details>

![image](https://user-images.githubusercontent.com/891515/49072122-38cf4c00-f238-11e8-8502-07028612ee41.png)

**Comment by JohnRiv** [comment]
I'm experiencing the same thing on OSX. Whenever I search in files, the blue searching bar doesn't stop animating and `searchService` hits 100% CPU in the `code --status` report.

```
Version:          Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS Version:       Darwin x64 16.7.0
CPUs:             Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)
```

**Comment by roblourens** [comment]
@JohnRiv you are describing a different problem with a different process. Please file your own issue.

@malinengineer this is expected in a large workspace. Is it worse than it was in 1.28?

**Comment by malinengineer** [comment]
> @malinengineer this is expected in a large workspace. Is it worse than it was in 1.28?

Yes, it's worse. I didn't experience any noticeable performance issues in 1.28.

**Comment by malinengineer** [comment]
Similar new issues:
https://github.com/Microsoft/vscode/issues/63873
https://github.com/Microsoft/vscode/issues/63857

**Comment by zabel-xyz** [comment]
I also notice this problem with rg.exe.
Especially in large workspaces, it's worse than in previous versions.
This problem also occurs when an extension uses workspace.findFiles
(In previous versions, it was almost instantaneous)

**Comment by gauravsaini** [comment]
https://github.com/Microsoft/vscode/issues/63161#issuecomment-444327027

**Comment by gauravsaini** [comment]
@roblourens Maybe a bit better but , multiple rg.exe instances are still being created. Just do 50 search and your pc might crash.

**Comment by roblourens** [comment]
Ok, that is expected. `rg.exe` is the process doing the search, so it has to use lots of CPU.

**Comment by zhhlwd** [comment]
I didn't search for anything, and all of a sudden the CPU usage is 100%, and whether I restart the computer or vscode, it can't be fixed.
![2019-02-12_173836](https://user-images.githubusercontent.com/35592403/52626504-48346c00-2eee-11e9-8815-237a25828c47.png)

In the end I set the "search.followSymlinks": false ,  then restart vscode to return to normal
