### ISSUE TITLE
'ˀ' character is added to text when toggling word wrap

### ISSUE THREAD

**Issue by asverasver** [Microsoft/vscode#63842]
Issue Type: <b>Bug</b>

1. On Mac OS, open some document with somewhat long text (that is over one line long) in VS Code.
2. Press Alt+Z to toggle word wrap. Along with toggling you will get a 'ˀ' character (at least I do).
3. Also, immediate attempt toggle word wrap again (without moving the cursor) is unsuccessful, but still adds 'ˀ'.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
code-runner|for|0.9.5
py-paste-indent|hye|0.0.2
ecdc|mit|0.12.0
python|ms-|2018.10.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1

</details>

**Comment by alexandrudima** [comment]
Let's track in #41024

This is a confirmed upstream bug -- https://bugs.chromium.org/p/chromium/issues/detail?id=887519
