### ISSUE TITLE
Increase history navigation limit (from 20 to 50)

### ISSUE THREAD

**Issue by leeqx** [Microsoft/vscode#63853]
用vscode 浏览项目代码时，往往会经常需要跳转{比如此时我代码在method_here()}  到其他function或者其他的代码片段看相关代码（假设此时我已经在不同的函数之间go todefinition   40次了），此时如果再想回到开始之前浏览代码的地方（method_here()时, 使用go back发现回退了20～25 次之后就不能在回退了。

**Comment by rebornix** [comment]
The description is also saying that “Go Back” has a limition of history.

**Comment by bpasero** [comment]
@leeqx can you repeat in english?

**Comment by leeqx** [comment]
@bpasero 
when i use vscode for read code of project，i will use go to definition to jump to many other code place in other file（measure more then 40 times）.Then it wan to go back to origin source code place ,but I cannot go back any more after i use go back action below  more then 25 time(or less), the other 15 step 
disappear.
![image](https://user-images.githubusercontent.com/931925/49134560-f03e8e00-f31e-11e8-832d-2102c0298572.png)

----------------------------------------
i found another new way to go back, it can use vim-extension's :"ctrl+o"  to go back  and "ctrl+i" to go forward after i install vim-extention then these work fine ,more then the vscode's go back,and go forward.

**Comment by bpasero** [comment]
Thanks, I think its fair to increase this limit. It currently stands at 20 and I have pushed a change to increase it to 50.
