### ISSUE TITLE
Bug #15052 reappeared: Windows Jumplist no longer showing folders/workspaces

### ISSUE THREAD

**Issue by coldino** [Microsoft/vscode#63850]
Issue Type: <b>Bug</b>

VSCode is pinned to the Windows taskbar and right clicking it shows the Jumplist. Normally, this list shows recent folders.

After removing a single folder from that list (right-click on it), no folders are listed and new folders opened do not appear. This was my primary way of launching VSCode for each folder/workspace but is now useless as it only lists files.

This looks like a recurrence of #15052, from the end of 2016.

I will test reinstalling VSCode, then the Insiders version, but wanted to report with details from this install first.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (8.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.4.5
vscode-css-formatter|aes|1.0.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
code-runner|for|0.9.5
vscode-github|Kni|0.30.0
Anyview|luf|0.0.4
xml-format|mik|1.0.1
python|ms-|2018.10.1
PowerShell|ms-|1.9.0
vscode-subword-navigation|ow|1.2.0
vscode-icons|rob|7.28.0
git-autoconfig|shy|0.0.1
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.6.10
vsfire|tob|1.3.2
shell-launcher|Tyr|0.2.0
gitblame|wad|2.6.1
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.11.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by coldino** [comment]
As per #15052 reinstalling clears the issue and all of my previous recent folders now show again in the jumplist.

However, the bug is easily reproduced by removing a single folder from the jumplist and restarting VSCode. This produces an empty jumplist:
![image](https://user-images.githubusercontent.com/28345893/49082030-8059d600-f240-11e8-915b-02590d728479.png)

**Comment by coldino** [comment]
I have not been able to reproduce the issue on Insiders 1.30.0. I will keep experimenting.

**Comment by bpasero** [comment]
@coldino if this does not reproduce in insiders, it can only be an issue with Windows because as far as I can tell we did not fix anything in insiders, so please try.
