### ISSUE TITLE
The function assigned to the constant is visible as a variable. Should be visible as a function.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#63856]
The function assigned to the constant is visible as a variable.

For example:
```javascript
const fn1 = async ()=> {
}

// or

const fn2 = function () {
}

```
is visible as a variable in "Go to Symbol in File..." and in "breadcrumbs".

Should be visible as a function.

**Comment by mjbvz** [comment]
This was discussed in https://github.com/Microsoft/TypeScript/issues/14830.  We decided to treat these as `const` for consistency
