### ISSUE TITLE
Too Slow when use Go to file option ( Ctrl +  P )

### ISSUE THREAD

**Issue by rahulgit** [Microsoft/vscode#63857]
Issue Type: <b>Performance Issue</b>

Recently I update my os to Windows 10 from Windows 7, after this update, I could not use Go to file, it takes too long to respond and using almost 94 % Memory  

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    97	  7544	code main
    1	   117	   988	   gpu-process
    1	    68	  3876	   window (Issue Reporter)
    0	    70	  8120	   shared-process
    0	   140	 11672	   window (Welcome - v1-web-app - Visual Studio Code)
    0	    59	  9324	     extensionHost
    0	    11	 10848	     watcherService 
    0	     9	  4216	       console-window-host (Windows internal process)
    0	    35	 13608	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - v1-web-app - Visual Studio Code)
|    Folder (v1-web-app): 7905 files
|      File types: js(2024) php(1979) tpl(1192) png(732) css(347) svg(237)
|                  gif(236) data(189) html(100) htm(80)
|      Conf files: package.json(9) grunt.js(3) jsconfig.json(1) launch.json(1)
|                  settings.json(1) tasks.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
smarty|imp|0.3.0

</details>

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it's any better there now? 
https://code.visualstudio.com/insiders
