### ISSUE TITLE
Hang on "Open Folder" when disconnected network drive

### ISSUE THREAD

**Issue by chenwardT** [Microsoft/vscode#6385]
- VSCode Version: 1.1.0
- OS Version: Win 8.1

Steps to Reproduce:

1. Map a network drive to a location.
2. Make mapped location unreachable.
3. File > Open Folder...

VS Code will become non-responsive for a period of time, after which several duplicated OS errors pop up regarding inability to connect to the drive.

**Comment by bpasero** [comment]
That is standard OS behaviour, we do not have any chance to change this behaviour imho.

**Comment by bpasero** [comment]
Closing, basic Windows behaviour, unrelated to Electron or VS Code.
