### ISSUE TITLE
Intermittent break on line 1 of bootstrap-fork.js when launching debug of an extension

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#63861]
Issue Type: <b>Bug</b>

When debugging the extension I am developing, sometimes execution suspends at line 1 of bootstrap-fork.js in the main VSCode window immediately after launch, and I have to Continue (F5) there.

![image](https://user-images.githubusercontent.com/6726799/49090634-046a8880-f256-11e8-9c36-ac7b3b6a275f.png)

Other times this doesn't happen. I haven't yet worked out why.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.15063

**Comment by weinand** [comment]
This is a timing issue.

In order to have breakpoints working reliably in the startup phase of a program, we always start node.js with a "--inspect-brk" option, but automatically "continue" if there is no "stopOnEntry" attribute in the launch config.

It looks like that in your case the "continue" is sometimes ignored.

**Comment by chausner** [comment]
I have been experiencing the same problem ever since I started developing extensions (6 months ago). It occurs roughly once in 3 times when I debug my extension and is pretty annoying.

**Comment by roblourens** [comment]
I haven't seen this before. Does it seem like the extension host is starting up very slowly?

Can you set `"trace": true` and upload the log from the path in the debug console?

**Comment by chausner** [comment]
I attached two logs: one where the bug occurs and one where it isn't. Hope it helps debugging the issue.

[vscode-node-debug2-bug.txt](https://github.com/Microsoft/vscode/files/2658966/vscode-node-debug2-bug.txt)
[vscode-node-debug2-ok.txt](https://github.com/Microsoft/vscode/files/2658965/vscode-node-debug2-ok.txt)

**Comment by roblourens** [comment]
Found the problem, thanks for the logs!
