### ISSUE TITLE
workbench.action.quickOpen doesn't work properly since last update

### ISSUE THREAD

**Issue by SholomAber** [Microsoft/vscode#63860]
`Ctrl + P` / workbench.action.quickOpen doesn't seem to be working since the latest update.

This was working fine previously but has since stopped working.

**Comment by chrmarti** [comment]
@SholomAber Which VS Code version and OS are you on?

**Comment by SholomAber** [comment]
> @SholomAber Which VS Code version and OS are you on?

I'm using the latest version of VS Code (not insiders) on Windows 10.

> Can you explain some more about what is not working?

Sure, in the past I've been able to enter part of a file name into the workbench.action.quickOpen input and a list would appear of all files that contained my entry. Currently this is not populating with files unless it's a file that I recently opened.

**Comment by roblourens** [comment]
If you open the developer tools (Help > Toggle Developer Tools), do you see any errors?

**Comment by SholomAber** [comment]
I don't see any errors in the console.

**Comment by roblourens** [comment]
Does this happen in every folder or does it work if you open a different folder?

**Comment by SholomAber** [comment]
I just tried in a smaller folder and it does seem to work.

**Comment by roblourens** [comment]
I pushed a change that will be in tomorrow's insiders that helps one known issue with slow search on windows. Try it tomorrow and let me know whether it helps: https://code.visualstudio.com/insiders

**Comment by SholomAber** [comment]
@roblourens yes it looks like that did it!
Looking forward to seeing that in the next stable release. Thank you!

**Comment by roblourens** [comment]
Great, thanks for testing it.
