### ISSUE TITLE
[Insiders] Could not create temporary directory: Permission denied

### ISSUE THREAD

**Issue by winzig** [Microsoft/vscode#63869]
- VSCode Version: 1.30.0-insider (1.30.0-insider)
- OS Version: macOS Mojave 10.14.1 (18B75)

Steps to Reproduce:

1. Click "Code - Insiders" menu and select Check for Update...
2. Error appears at the bottom of the screen: Could not create temporary directory: Permission denied

<img width="450" alt="screen shot 2018-11-27 at 10 07 53 am" src="https://user-images.githubusercontent.com/127062/49102297-492df980-f22d-11e8-8dde-8ba057ea1cde.png">

I previously had this issue on a code-insiders release from a day or so ago, downloaded the latest insiders build, but having the problem again today.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Please check https://github.com/Microsoft/vscode/issues/7426#issuecomment-425093469

**Comment by winzig** [comment]
@joaomoreno The app is already in the Applications folder...

**Comment by winzig** [comment]
I ran the two commands, the first one failed with:

> chown: /Users/tom/Library/Caches/com.microsoft.VSCode.ShipIt/*: No such file or directory

The second one seemed to run ok, but has had no effect on my ability to update, I still get permission denied.

**Comment by winzig** [comment]
When I run `ps` to see where Code Insiders is running from, it shows that it's running from `/Applications/Visual Studio Code - Insiders.app` as expected. Any other ideas?

**Comment by joaomoreno** [comment]
Make sure Code isn't running. Then, run it from the Terminal as `code --verbose`, then run an update. The specific error should come up in the terminal, maybe it contains more info.

Also what does `ls -la ~/Library/Caches/com.microsoft.VSCode.ShipIt` return?

**Comment by winzig** [comment]
Running in verbose mode I get this when checking for updates:

```
[main 2:29:36 PM] update#checkForUpdates, state =  idle
[main 2:29:36 PM] update#setState checking for updates
[main 2:29:36 PM] telemetry/workbenchActionExecuted { id: 'CheckForUpdate', from: 'menu' }
[main 2:29:36 PM] menubarService#updateMenubar 1
[main 2:29:37 PM] update#setState downloading
[main 2:29:37 PM] UpdateService error: Could not create temporary directory: Permission denied
[main 2:29:37 PM] update#setState idle
[1962:1130/142937.132645:INFO:CONSOLE(2465)] "Could not create temporary directory: Permission denied", source: file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (2465)
[main 2:29:37 PM] menubarService#updateMenubar 1
```

The output from that `ls` command is:

```
drwxr-xr-x   2 tom  staff    64 Nov 19 10:35 .
drwx------+ 88 tom  staff  2816 Nov 30 12:05 ..
```

**Comment by joaomoreno** [comment]
What about `$TMPDIR`, does your user have permissions there?

**Comment by winzig** [comment]
@joaomoreno Yep, just verified I can write there.

**Comment by joaomoreno** [comment]
Oh I just noticed you are on Insiders. Run this one:

`ls -la ~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt`

**Comment by winzig** [comment]
@joaomoreno That command returns nothing at all. I tried to `cd` into it, and received a permission denied, so I then ran:

`sudo chown $USER ~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt/`

Restarted the insiders build, and now the software update works! 

Sorry about the run-around, I didn't realize there was a ShipIt directory for both kinds of builds...
