### ISSUE TITLE
Unable to exit Bug Report screen on a Mac

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#63863]
Issue Type: <b>Bug</b>

There does not appear to be a way to close the Bug Report screen on a Mac....

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 13, 20|
|Memory (System)|4.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
vscode-eslint|dba|1.7.0
beautify|Hoo|1.4.7
vscode-docker|Pet|0.4.0

</details>

**Comment by RMacfarlane** [comment]
Hey @leegee, I recently checked in a fix for making the Cmd+w shortcut work to close this window. Is this bug report for the shortcut? Or are you also unable to close the window using the close button?

**Comment by leegee** [comment]
When on the bug-reporting screen (illustrated), I can't find a 'close'
button, ESC has no effect, nor does CMD+W.  But I' mnot running Insiders.


> [image: image.png]
>

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/57984792-05fe5780-7a14-11e9-9584-c16269cef584.png)

Not sure for how long but there's a close button now. We can probably close this issue?
