### ISSUE TITLE
Esc doesn't close Search

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#63862]
Issue Type: <b>Bug</b>

IIRC correctly, on Windows, one can press the escape key to cancel a search-within-document dialog. This doesn't seem to work on a Mac.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 13, 20|
|Memory (System)|4.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
vscode-eslint|dba|1.7.0
beautify|Hoo|1.4.7
vscode-docker|Pet|0.4.0

</details>

**Comment by rebornix** [comment]
@leegee can you open "Keyboard Shortcuts" and search for "closefindwidget" and see it's bind to `Escape`? I can't reproduce this issue on my mac.

**Comment by leegee** [comment]
Sorry! My ESC key is broken!
