### ISSUE TITLE
Option to remove default Touch Bar controls but leave it enabled for plugins

### ISSUE THREAD

**Issue by designbyadrian** [microsoft/vscode#63865]
![](https://user-images.githubusercontent.com/23492964/32794442-caf8b8a2-c960-11e7-9b01-26c56f39fc9b.png)

Please make these buttons optional. I'd like to either create a plugin myself, or use one of the available Touch Bar plugins, and have access to all available space.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/70174

**Comment by bpasero** [comment]
**Verification:** you can hide individual commands (e.g. "`workbench.action.debug.start`") from the macOS touchbar via `"keyboard.touchbar.ignored": []` setting. Possible IDs:
