### ISSUE TITLE
Extension URL schemes which do not have authorities and are not files can't be opened

### ISSUE THREAD

**Issue by pvh** [Microsoft/vscode#63868]
- VSCode Version: 1.29.1

Before opening a file, the extension _withProvider checks if the path [isAbsolute](https://github.com/Microsoft/vscode/blob/55565d4fe6f38848fb227ca2628d94498a0af8e8/src/vs/workbench/services/files/electron-browser/remoteFileService.ts#L251).

URLs which do not begin with "/" are detected as "non-absolute". For example, vscode.Uri.parse("customscheme:arbitrarycontentgoeshere").isAbsolute() is false.

In my case, I'm able to work around this restriction by modifying my URL format to begin with a "/", but it's an ugly hack and wouldn't be the case for a more established URL scheme.

I'd suggest that performing this check should be the business of the filesystem scheme provider rather than something like remoteFileService.

**Comment by jrieken** [comment]
That's the (somewhat unfortunate) design of the system and the API, e.g. file system providers, need to follow. This note tries to explain it but it could be more explicit about paths starting with a slash: https://github.com/Microsoft/vscode/blob/4dd748b443180e40245aa608bd0d2d2fd5871246/src/vs/vscode.d.ts#L5419-L5420
