### ISSUE TITLE
Clarification and/or grant regarding patents

### ISSUE THREAD

**Issue by jonkri** [microsoft/vscode#63875]
I would like the Visual Studio Code documentation to reflect whether or not Visual Studio Code contains any patented technology. It would also be great if Microsoft licensed Visual Studio Code under an open source license that provides a patent grant, such as the Apache Software License.

Thank you!

**Comment by jonkri** [comment]
@chrisdias: Hi Chris! I'm curious to know if any progress has been made on this issue. Any feedback would be appreciated. Thanks! :slightly_smiling_face:

**Comment by chrisdias** [comment]
Hi @jonkri sorry for taking so long to get back to you. I'm trying to address a number of the licensing issues.  

To answer your question, when we (Microsoft) made this code available as open source under the MIT license, our intent was that anyone in the community can use this code as long as they comply with the license. You do not need any additional patent grants from Microsoft to use this code.

hope this helps.

**Comment by jonkri** [comment]
@chrisdias:

Your clarification (and in general your work with addressing issues surrounding licensing) is much appreciated - thank you!

Regarding your license intent: Is it Microsoft's position that the MIT license implicitly offers a patent grant, for any Visual Studio Code related patents?

If it is Microsoft's intention to provide a patent grant in this way, I think licensing the project under a license with an explicit patent grant would make things a lot less ambiguous. Also, it's still unclear to me whether or not Visual Studio Code contains any patented technology.

Perhaps this issue should be re-opened.

Thanks again!
