### ISSUE TITLE
Extension to be able to notify before update if breaking change

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#63871]
Would be great if extension authors could trigger a notification to users when a new version of the extension brings breaking changes in the way it works. 

Even if the update of the extension cannot be postponed or prevented yet, at least a message explaining why things stopped working would save a lot of time to users trying to find out what just happened. 

Obviously this should not be abused. If extension doesn't change the way it works, it should not notify at all.

https://github.com/vuejs/vetur/issues/992

**Comment by sandy081** [comment]
Not a big fan of notifications.
