### ISSUE TITLE
Installation of vscode-powershell replaced File Explorer right-click menus for .ps1 files

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [Microsoft/vscode#6387]
- VSCode Version:1.1.0
- OS Version:Windows10 Version 1511.

I've installed Visual Studio Code and then on VSCode I've run 
ext install PowerShell.
After this I've noticed that the following items disappeared in File Explorer for .PS1 files:
"Open with PowerGUI Script Editor" and “Run with PowerShell”.
I found workaround by modifying the registry, but installation of a new tool shouldn't break old associations.
I've raised https://github.com/PowerShell/vscode-powershell/issues/176#issuecomment-219061694,
but they advised that it is Visual Studio Code issue.

**Comment by joaomoreno** [comment]
Are you sure that this only started happening between Code's and the extension's installation?

Code doesn't mess with the MRU list... it simply adds itself as an editor of `ps1` files. Windows seems to change the MRU list for some reasone...

**Comment by michael-freidgeim-webjet** [comment]
I am using ps1 on a daily basis. Double-click in File Explorer opens PowerGUI Script Editor. After installing Visual Studio Code and PowerShell add-in double click opened Visual Studio Code and PowerGui and PowerShell menus were not visible.After change in registry menu items were restored and PowerGui menu is a default again.  I don't think, that I done anything else related.

**Comment by bmdixon** [comment]
I have a similar issue. When opening a `ps1` file in VS Code the 'Run with PowerShell' option in the right click menu disappears. I can restore it again by choosing open with 'Windows Powershell' but when i open a `ps1` file it gets removed again.

**Comment by swinster** [comment]
I wonder if there has been any update on this issue in July?

**Comment by bmdixon** [comment]
@swinster I still have the same problem with v1.6.1 so don't think anything has changed since July.

**Comment by joaomoreno** [comment]
I can't figure out what kind of voodoo the Windows PowerShell does on the Explorer context menu that makes that option appear only when the file is associated with Notepad and a few select others.

If you set the file to open with Sublime Text or Internet Explorer or any other app, the context menu option is gone. So, this is not a VS Code issue.

I will keep it open since it creates some friction for a few users, but ultimately this is an issue with the Windows PowerShell tooling in Windows.

**Comment by joaomoreno** [comment]
Seems to be very quiet since October. Closing it.
