### ISSUE TITLE
Hard to figure out how to click on top level folder

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#63876]
My natural inclination is to click on the titlebar, since after all it's titled with the top-level folder name.  B But that does not work as expected.

This has been confusing for both us developers and customers.  See for instance:
https://github.com/Microsoft/vscode/issues/10343
https://github.com/Microsoft/vscode-azurestorage/issues/252

Plus, if the files/folders list takes up all the vertical space, I'm not sure it's possible to get a context menu on the top-level folder at all:
![image](https://user-images.githubusercontent.com/6913354/49110017-23aaeb00-f241-11e8-8115-b08c3b85963f.png)

This is a discoverability issue you guys really ought to look into.  Thanks!

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/1043
