### ISSUE TITLE
Property dependsOn is not allowed in provided task

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#63874]
Issue Type: <b>Bug</b>

I'm trying to provide tasks through my extension (using a `TaskProvider`) and my tasks get several properties "for free" (group, options, presentation, etc.), but I get this error when I try to use dependsOn (npm tasks are just used as a simple example):
![screen shot 2018-11-27 at 10 53 21 am](https://user-images.githubusercontent.com/11282622/49104564-243c8500-f233-11e8-8b52-fda882c81c01.png)

That being said - `dependsOn` _does_ seem to be respected. Must just be a schema issue.
![screen shot 2018-11-27 at 10 59 17 am](https://user-images.githubusercontent.com/11282622/49104720-8301fe80-f233-11e8-91be-b81e8936cf4f.png)

VS Code version: Code - Insiders 1.30.0-insider (456e8e64beb2dceac66743959f6802b66e18e300, 2018-11-26T10:55:58.730Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-azurefunctions|ms-|0.12.1
python|ms-|2018.10.1
azure-account|ms-|0.7.0
csharp|ms-|1.17.1

</details>

**Comment by alexr00** [comment]
Thank you for finding!

**Comment by EricJizbaMSFT** [comment]
@alexr00 I'm still seeing this
![screen shot 2019-01-04 at 2 33 52 pm](https://user-images.githubusercontent.com/11282622/50714527-ff0b1580-102d-11e9-8ac5-a13be3791829.png)


VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:14:03.787Z)
OS version: Darwin x64 18.2.0

Similar to another issue, you can use this to repro: https://github.com/EricJizbaMSFT/helloworldext

**Comment by alexr00** [comment]
@dbaeumer, do you know if modifying an npm task to have a `dependsOn` is supposed to work?

**Comment by dbaeumer** [comment]
@alexr00 I think it works and we should support it.

**Comment by jamesgeorge007** [comment]
@alexr00 I would like to give it a shot. What is to be done further?

**Comment by alexr00** [comment]
The original issue indicates that the `dependsOn` property is being respected, the schema just doesn't allow it. The next steps would be to make sure that the `dependsOn` property is being respected when modifying an npm task. Then, figure out what's wrong with the schema. The schema can be found [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/jsonSchemaCommon.ts) and [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/jsonSchema_v2.ts).

**Comment by DevelAx** [comment]
The same warning **"Property dependsOn is not allowed"** with the **`grunt`** type of task:
```
{
    "label": "Minify and bundle CSS+JS",
    "type": "grunt",
    "task": "default",
    "group": "build",
    "dependsOn": ["Sass compile"]
}
```

**Comment by alexr00** [comment]
To verify add `"dependsOn": "something"` to an npm task in a tasks.json file. No need to run anything, just make sure that there are no squiggles under `"dependsOn`"

**Comment by EricJizbaMSFT** [comment]
No more squiggles for me - thanks!

**Comment by alexr00** [comment]
Thanks for verifying!
