### ISSUE TITLE
100% CPU when running node with debugger

### ISSUE THREAD

**Issue by pr3tori4n** [Microsoft/vscode#63878]
Issue Type: <b>Bug</b>

I'm running a gulp watch in the terminal and running node with a launch configuration.

This is causing my CPU usage to spike to high 90s or 100%. When I run the same server using git bash to start it, the CPU usage is nowhere near that.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (19.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|3.0.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
vscode-instant-markdown|dba|1.4.3
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
beautify|Hoo|1.4.7
java-properties|ith|0.0.2
terraform|mau|1.3.7
HTMLHint|mka|0.5.0
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.6.2
vetur|oct|0.14.2
vscode-docker|Pet|0.4.0
vscode-css-peek|pra|2.1.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
Can you run `code --status` and paste in the output here? That will show which process(es) are the problem

**Comment by pr3tori4n** [comment]
$ code --status


Version:          Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)
Memory (System):  31.88GB (15.64GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       73   39628  code main
    2      294   15128     window (index.js - overwatch-node - Visual Studio Code)
    0        5     700       winpty-process
    0        8    5044         console-window-host (Windows internal process)
    0        4   32644         "C:\Program Files\Git\bin\bash.exe"
    0        9   32232           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0        7    6868       winpty-process
    0       10   31704         console-window-host (Windows internal process)
    0        5   38812         "C:\Program Files\Git\bin\bash.exe"
    0       10   15964           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0       44   26324       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.node2 "{\"common.vscodemachineid\":\"4b0af94da906a3a52b54a1ff9053d47c515af9137941da0fe8a0a7752eab98d7\",\"common.vscodesessionid\":\"4178134d-db3f-43c9-b574-39c5584623961543518270797\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0        6   31868       winpty-process
    0       10   35708         console-window-host (Windows internal process)
    0        5   40796         "C:\Program Files\Git\bin\bash.exe"
    0       10   12448           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0      101   33116       extensionHost
    0       25   12608         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=33116
    0       40   15608         electron_node server.js
    0       24   17884         electron_node server.js
    0       22   33680         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=33116
    0      517   40592         electron_node tsserver.js
    0       54   32752           electron_node typingsInstaller.js typesMap.js
    0        7   34036       winpty-process
    1       10   29944         console-window-host (Windows internal process)
    0        5   37832         "C:\Program Files\Git\bin\bash.exe"
    0       10   41600           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0        7   37368       winpty-process
    0       10   32108         console-window-host (Windows internal process)
    0        5   34692         "C:\Program Files\Git\bin\bash.exe"
    0       10   40308           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
   11      208   37988       electron_node nodeDebug.js
    0        6   39080       winpty-process
    0       10   32236         console-window-host (Windows internal process)
    0        5   34152         "C:\Program Files\Git\bin\bash.exe"
    0       10   29560           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0       19   41276       watcherService
    0        6   39384         console-window-host (Windows internal process)
    0       68   34664     shared-process
    0       85   34800     gpu-process
Workspace Stats:
|  Window (index.js - overwatch-node - Visual Studio Code)
|    Folder (overwatch-node): 3863 files
|      File types: png(1216) svg(1086) jpg(788) js(173) scss(113) gif(104)
|                  html(92) jade(76) mp4(34) webm(32)
|      Conf files: jsconfig.json(1) package.json(1) gulp.js(1) launch.json(1)
|                  settings.json(1)
|      Launch Configs: node(7)

**Comment by pr3tori4n** [comment]
`$ code --status


Version:          Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)
Memory (System):  31.88GB (15.64GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       73   39628  code main
    2      294   15128     window (index.js - overwatch-node - Visual Studio Code)
    0        5     700       winpty-process
    0        8    5044         console-window-host (Windows internal process)
    0        4   32644         "C:\Program Files\Git\bin\bash.exe"
    0        9   32232           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0        7    6868       winpty-process
    0       10   31704         console-window-host (Windows internal process)
    0        5   38812         "C:\Program Files\Git\bin\bash.exe"
    0       10   15964           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0       44   26324       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.node2 "{\"common.vscodemachineid\":\"4b0af94da906a3a52b54a1ff9053d47c515af9137941da0fe8a0a7752eab98d7\",\"common.vscodesessionid\":\"4178134d-db3f-43c9-b574-39c5584623961543518270797\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0        6   31868       winpty-process
    0       10   35708         console-window-host (Windows internal process)
    0        5   40796         "C:\Program Files\Git\bin\bash.exe"
    0       10   12448           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0      101   33116       extensionHost
    0       25   12608         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=33116
    0       40   15608         electron_node server.js
    0       24   17884         electron_node server.js
    0       22   33680         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=33116
    0      517   40592         electron_node tsserver.js
    0       54   32752           electron_node typingsInstaller.js typesMap.js
    0        7   34036       winpty-process
    1       10   29944         console-window-host (Windows internal process)
    0        5   37832         "C:\Program Files\Git\bin\bash.exe"
    0       10   41600           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0        7   37368       winpty-process
    0       10   32108         console-window-host (Windows internal process)
    0        5   34692         "C:\Program Files\Git\bin\bash.exe"
    0       10   40308           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
   11      208   37988       electron_node nodeDebug.js
    0        6   39080       winpty-process
    0       10   32236         console-window-host (Windows internal process)
    0        5   34152         "C:\Program Files\Git\bin\bash.exe"
    0       10   29560           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0       19   41276       watcherService
    0        6   39384         console-window-host (Windows internal process)
    0       68   34664     shared-process
    0       85   34800     gpu-process
Workspace Stats:
|  Window (index.js - overwatch-node - Visual Studio Code)
|    Folder (overwatch-node): 3863 files
|      File types: png(1216) svg(1086) jpg(788) js(173) scss(113) gif(104)
|                  html(92) jade(76) mp4(34) webm(32)
|      Conf files: jsconfig.json(1) package.json(1) gulp.js(1) launch.json(1)
|                  settings.json(1)
|      Launch Configs: node(7)`

**Comment by pr3tori4n** [comment]
@Tyriar I posted the output you requested. Any help would be greatly appreciated.

**Comment by Tyriar** [comment]
The node debug process seems to be using 1 full core (it says 11% but it's an 8 core CPU).

**Comment by pr3tori4n** [comment]
Is there a configuration I need to change to get it utilizing additional CPU cores?

**Comment by weinand** [comment]
@pr3tori4n how does the launch configuration look like?
Are you using VS Code's "auto-attach" feature?
If you stop the "gulp watch" does it make a difference?

**Comment by pr3tori4n** [comment]
{
            "type": "node",
            "request": "launch",
            "name": "Launch Dev",
            "program": "${workspaceFolder}/server.js",
            "console": "integratedTerminal",
            "env": {
                ...
            }
        }

**Comment by weinand** [comment]
Thanks, but there are two additional questions.
