### ISSUE TITLE
Extension update should follow semver

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#63872]
Context: https://github.com/vuejs/vetur/issues/992#issuecomment-442166832

Currently if an extension author published a new version, there's no way for him to notify user (https://github.com/Microsoft/vscode/issues/63871). If there are breaking changes, it might cause a bad experience for users.

I hope the config for extension auto update could provide more granularity. For example, `extension.autoUpdateSemver: 'minor'` should not auto update major versions without explicit user action.

**Comment by sandy081** [comment]
Duplicate of #37162
