### ISSUE TITLE
tsserver.js Possible memory leak

### ISSUE THREAD

**Issue by suspectdoubloon** [Microsoft/vscode#63885]
Issue Type: <b>Bug</b>

I've had vscode open for a few days without closing it, and I've been noticing its memory usage climbing. I've had about 10 - 15 files open at one stage, working across them all. I eventually closed most of them to about 3 but still having approximately 2Gb of memory usage for tsserver.js. I think this was recently introduced as I've only recently noticed increased memory usage.

Attached is screenshot from the process explorer.

![process_explorer](https://user-images.githubusercontent.com/6007286/49121235-abefc580-f2ff-11e8-82bd-2d3b11ddc6b8.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.19.3-300.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.38GB (0.92GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|1.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
vsc-material-theme|Equ|2.6.1
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.7
dotenv|mik|1.0.1
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.4.0
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|1.0.4

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? We've picked up new TS server version

**Comment by amok** [comment]
the same happens to me

```
➜ code --status                                                                                                                                                                                          
Version:          Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS Version:       Darwin x64 18.2.0
CPUs:             Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)
Memory (System):  8.00GB (0.03GB free)
Load (avg):       6, 7, 6
VM:               0%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	    49	 41027	code main
    0	    16	 41038	   gpu-process
    0	    49	 41039	   window (Extension: StandardJS - JavaScript Standard Style — webapp)
    1	    25	 41043	     extensionHost
    0	    16	 41047	       electron_node tslintServer.js
    0	    25	 41048	       electron_node server.js
    0	    25	 41107	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=41043
    0	    25	 41435	       electron_node server.js
   96	  2146	 45297	       electron_node tsserver.js
    0	    25	 45298	         electron_node typingsInstaller.js typesMap.js
    0	    25	 41044	     watcherService
    0	    16	 41050	     searchService
    0	    33	 41040	   shared-process
    0	    41	 47682	   window (undefined)
```

**Comment by suspectdoubloon** [comment]
I've used the insiders build since I reported this yesterday. haven't seen an increase in memory, I would say its its fixed there. Im still noticing a large consumption of memory but this remains ~constant.

![vs_insiders_b](https://user-images.githubusercontent.com/6007286/49187122-68a45e00-f3b6-11e8-800c-92eb2f2fe36d.png)
 
VS Code version: Code - Insiders 1.30.0-insider (d3bb20c3fd1f23c369b80dca2ed25d54efd664e2, 2018-11-27T08:21:55.919Z)
OS version: Linux x64 4.19.3-300.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2461)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.38GB (0.58GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
