### ISSUE TITLE
Don't translate Git command

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#6388]
- VSCode Version: Insider 1.10
- OS Version: Windows 10 version 1511

Steps to Reproduce:

1. Set your VSCode locale to zh-CN
2. Check Git Panel > "···" Button (three dots) > Git command

-  "Pull" translated to "拉"
-  "Pull (Rebase)" translated to "拉取 (变基)" **// PS: looks like "somebody become  a gay" in Chinese...(This is a Joke)**

1. Why same word "Pull" will be translate to different word in Chinese? "Pull" > "拉" / "拉取"
2. We know what is Push, Pull, Rebase ,but we really don't know what is "拉取(变基)"

**Comment by isidorn** [comment]
With the latest VSCode all commands in the command pallette are not translated (when you press F1).
Though I understand you might want to never translate git commands - so even in the git viewlet
