### ISSUE TITLE
Leak powershell process when opening folder contains plenty of c and cpp files

### ISSUE THREAD

**Issue by chraac** [Microsoft/vscode#63889]
- VSCode Version: 1.29.1
- OS Version: Win7 64bit SP-1 with latest update installed

Steps to Reproduce:

1. Open a folder that contain plenty of c and cpp files (like chromium)
2. Wait for 24hour

Does this issue occur when all extensions are disabled?: Yes

Process list of vscode is in attachment
[process.list.log](https://github.com/Microsoft/vscode/files/2622732/process.list.log)

**Comment by chraac** [comment]
The problem was gone when I disable the ms-vscode.cpptools plugin.

**Comment by rebornix** [comment]
Please file issue against https://github.com/Microsoft/vscode-cpptools
