### ISSUE TITLE
Freezes 

### ISSUE THREAD

**Issue by AndreyKonogray** [Microsoft/vscode#63880]
After installation of colorize or all autocomplate, it takes some time and the program hangs, after which the emmet, autocomplete and some other plugins stop working. The problem appears after the finishing of scanning files (on the status bar at the bottom of the workstation)

**Comment by rebornix** [comment]
@AndreyKonogray do you mean vscode hangs when you are installing extensions, or it hangs when you open a workspace?

**Comment by AndreyKonogray** [comment]
It was necessary to remove the extra languages in colorize
