### ISSUE TITLE
i can't delete the new content and write a function

### ISSUE THREAD

**Issue by json-Li** [Microsoft/vscode#6389]
- VSCode Version:1.1.0
- OS Version:win 10

Steps to Reproduce:

1.open a file ,then i delete the content 
2. i want to write a function,so i spell in editor like this func...
3.a strange things happend,the delete content is show,not the function

**Comment by isidorn** [comment]
Please add a gif capturing the behavior you are seeing. Or some screenshots.

**Comment by json-Li** [comment]
![bug](https://cloud.githubusercontent.com/assets/13777181/15286211/3879a706-1b8e-11e6-85e8-723c3f29186f.gif)

**Comment by alexandrudima** [comment]
@json-Li That is most weird. Here is me doing it. I press and hold `Backspace` and then type:

![8apt4usofc](https://cloud.githubusercontent.com/assets/5047891/15483404/ce7e71fe-2134-11e6-925b-d8645c18c583.gif)

Is it possible you have installed some extension that completes things (i.e. does this reproduce when running `code --disable-extensions`) or is it possible you have installed some text-expansion utility in the OS that expands `func` to `this is a test`?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
