### ISSUE TITLE
Duplicated definition references found when `Go to Definition`

### ISSUE THREAD

**Issue by ayqy** [Microsoft/vscode#63895]
Current Behavior:

External extensions contributed definitions are duplicated with build-in extensions (eg. typescript related extensions), and there is no way for external extensions to know whether other definitions exist or not.

![image](https://user-images.githubusercontent.com/12402989/49136706-71008880-f325-11e8-865b-ac6651b45be4.png)

Expected Feature:

-  Provide an option for `vscode.languages.registerDefinitionProvider` to avoid such conflicts with build-in or other external DefinitionProviders.

-  Alternatively, provide an API to get build-in or all other definitions, just lift conflicts to external extensions.

Steps to Reproduce:

1.  Clone the [test-def repo](https://github.com/ayqy/test-def.git)
2.  Open `test-def` folder with VS Code, and then Start Debugging
3.  Open `test-def/src` folder with [Extension Development Host], and open `test-def/src/extensions.ts`
4.  `import * as test from './test/index';` Go to Definition of `./test/index`
5.  Two definitions found

Further More:

The exactly same definitions will be filtered, so I tried to provide the same definition with build-in result, and failed as well:

```
public provideDefinition(
    document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken):
    Thenable<vscode.Location> {
        console.log('trigger GoDefinitionProvider at ' + Date.now());
    return new Promise((resolve) => {

        // ... Do some stuff to find definitions 

        let file = path.join(__dirname, '../src/test/index.ts');
        console.log('resolve some thing ' + file);

        vscode.workspace.openTextDocument(file).then(doc => {
            // default range
            // {startLineNumber: 13, startColumn: 1, endLineNumber: 22, endColumn: 29}
            let range = doc.validateRange(new vscode.Range(new vscode.Position(0, 0), new vscode.Position(99999, 99999)));
            
            //!!! Change startPosition.line to 12 will do the trick,
            // but there's no way to know other definitions exactly.
            // let range = doc.validateRange(new vscode.Range(new vscode.Position(12, 0), new vscode.Position(99999, 99999)));


            console.log(range);
            resolve(new vscode.Location(
                vscode.Uri.file(file),
                range
            ));
        });
    })
}
```

**Comment by ayqy** [comment]
Good idea, and I will investigate this way then.

But from my point of view, it's a common situation: when we are keen to enhance Go to Definition functionality, we will see these duplications quickly. Although there are other options in typescript, if any other languages ?

P.S. Except for our custom build system, Webpack supports [Resolve](https://webpack.js.org/configuration/resolve/) as well, and I think it's worth considering such general cases.

**Comment by jrieken** [comment]
Yeah, there can remove duplicates but I don't wanna stretch the definition of a duplicate too much

**Comment by ayqy** [comment]
Exactly, I know there are no strict duplication problems ( a kind of **conflict** only ), the reason why stress
 'duplicates' here is just a trick for issue searching to someone facing the same situation, because it's not easy to find differences between internal `Range(0,0, 28, 12)` and `Range(0,0, 0, 0) or Position(0, 0)` in the definition result list.

So, just ignore 'duplicates' and focus on the conflict, and it's a feature request only :)

**Comment by ollyhayes** [comment]
We have a similar issue. We have a javascript lerna monorepo and in each package we have babel compiling `/packages/package-name/src` into `/packages/package-name/lib`. When navigating to definition accross packages, it takes you to the compiled version in `/packages/package-name/lib` instead of in `.../src'.

I wrote a `DefinitionProvider` which works and supplies the correct version, but the old `.../lib` definition is still given as well and you have to choose between them. Ideally I'd like to just be taken to the version in `.../src` without being asked, is this not possible?
