### ISSUE TITLE
VSCode suggestions (not a real bug but a "bug" for most of users) 

### ISSUE THREAD

**Issue by TakeByEarn** [Microsoft/vscode#63891]
I hope that you can add the cmake for C++, gradle for java automatically in VSCode by default, just like the Visual Studio, user especially for C++ coder or java coder or C# Coder should never care about project' build file except little speciall library.
Too many configurations make not easy to undestand what they should do. so  must of people choose to follow the defalut advices. Cause not all of people have the knowlegement about VSCode all aspects for requirements.
Expeciton:  
       I hope the extension that could make VSCode to be like VSCode or Ecplise or IDE  with a little configuration such as standard library path, Android NDK path, 3td party libray location etc. i guess VSCode’s C/C++ and C# suggestion should be taken form team of Visual Studio, java from Eclipse team. Python from offical team, tec. Those Giant Tools always carry too much tools that a developer would never access. may be a picture descripe a language's configuration;
such as :
 C/C++ Configuration: 
     C/C++  : Common config:
                   auto comple; path standard library; compiler ;debuger(default)
      Level0 :  should config:
                  project file generation:  such as Visual Studio's sln  file.
                  also provide CMakeLists.txt for other paltform.
     Level1 : .....
                .....
     Levelx:  
            maybe for pro:
            Design Graph -> Package,Library,Class Design --> Generate Code --> Code-->  Version --> Unint Test / bugFix

**Comment by aeschli** [comment]
VSCode aims to be a lightweight editor. That's why we don't bundle any build tools nor any setup wizards.
Of course this can all be added by extensions, but the shipped VSCode focuses on editing.
