### ISSUE TITLE
vscode attach debug configuration question: debug adapter is the same process with the running debugee

### ISSUE THREAD

**Issue by wiener0zyj** [Microsoft/vscode#63896]
I am developing a vscode debug extension for a script language. The script is running in the debugger process. When I configure the package.json, I still need to write the "program" attribute as follows:

windows:{   program: "e:\debugger.exe" }

but the debugee is the running debugger.exe. So if I choose attach, the vscode would open another debugger.exe process, which is not what I want.

The ideal workflow I want is: I choose the running process, the vscode sets the chosen running process as the debugger and communicates with it.

How could I configure the package.json file or write the extension.ts file?

Please help me. Please give me a way!

**Comment by weinand** [comment]
The "program" attribute in the package.json is the path to the debug adapter and not the path to your runtime.
Please see this picture:
![2018-11-28_10-04-17](https://user-images.githubusercontent.com/1898161/49140643-13544800-f2f5-11e8-8e62-c4c428f81caa.png)

**Comment by wiener0zyj** [comment]
@vscodebot it seems i could not enter the slack channel

**Comment by weinand** [comment]
The only way to prevent VS Code from starting a "debug adapter" is to run the "debug adapter" as a server. Please see this documentation: https://code.visualstudio.com/docs/extensions/example-debuggers#_alternative-approach-to-develop-a-debug-extension

**Comment by wiener0zyj** [comment]
@weinand in the documentation, i see this "**This approach is in fact easily doable as long as your debug adapter is implemented in TypeScript/JavaScript**".
It seems the i have to write the "debug adapter" in TypeScript. could i write the adapter in c++? thanks!

**Comment by weinand** [comment]
You do not have to embed the "debug adapter" into your extension.
You can just run the debug adapter as a separate server process written in any language.

If you add an attribute `"debugServer": 12345` to your launch config, VS Code will connect to that port instead of starting a debug adapter.

Instead of this code
https://github.com/Microsoft/vscode-mock-debug/blob/d33d6057c2d7d7f0495e26d6fa8844c8336b2408/src/extension.ts#L68-L76
you can just launch your c++ debug adapter and and make it listen on a specific "port".

And then assign the port to a `debugServer` attribute as it is done here:
https://github.com/Microsoft/vscode-mock-debug/blob/d33d6057c2d7d7f0495e26d6fa8844c8336b2408/src/extension.ts#L79

**Comment by wiener0zyj** [comment]
@weinand thanks for your help! the attach problem has been settled！
there is another question about launch now, after i changed the communication method from stdin/stdout to tcpip. After I press launch, the vsode code tries to connect the server, but the server has not been started. vscode returns connect fail message.
is there a timeout attribute in package.json or other way to solve this problem.

**Comment by weinand** [comment]
No, server-based debug adapters are expected to run if a user starts a debug session.
If there is no debug adapter listening this is considered an error.

That's another reason to separate the debug adapter from the target. The debug adapter could easily implement a timeout for the "attach" operation (because it knows all the details about the target to be debugged. Whereas VS Code knows nothing about the target but only knows how to talk to debug adapters (with defined behaviour).

**Comment by wiener0zyj** [comment]
@weinand I see, thanks for your explanation!

**Comment by wiener0zyj** [comment]
@weinand Hello, weinand! could i get the attribute in package.json in extension.js active function.

**Comment by weinand** [comment]
End users should not have to deal with the package.json. The package.json is a private implementation detail of an extension. Don't tamper with it! 
Modifying the package.json programmatically does not even work because if would violate the package signing and would result in error messages.
What is the reason that you want to modify the package.json?

**Comment by wiener0zyj** [comment]
@weinand  currently, we have two executable for debugAdapter.exe and debugger.exe. this two executable is installed by user. we want let user tell our lisp extension where is the debugAdapter.exe and where is debugger.exe. When we launch or attach debug, extension should find this two exe.
In this situation, how should we write the code?

**Comment by weinand** [comment]
The debugAapter.exe is part of the extension that the user installs. The (relative) path to that executable has to go into the package.json. The user does not install the debugAapter.exe by himself. Instead he installs an extension from the Marketplace which contains the executable.

The debugger.exe is most likely independent from VS Code and is not part of the extension. It is installed by some other mechanism which even might add its location to the uers's PATH environment variable. After this the debugger will be found by its name.

If the debugAdapter inside the extension needs to launch the debugger, it can either launch it by name (via PATH), or it can look up the location by some debugger specific environment variable.

**Comment by wiener0zyj** [comment]
@weinand I see, thanks for your explanation!

**Comment by wiener0zyj** [comment]
@weinand Sorry for distubing again. Currently we have successed to launch and attach. But only the latest release Debugger.exe could be attach. If the customer choosed the older one, we want to show an message on vscode. could Extension know attach failed or could adapter trigger an vscode registered command?

**Comment by weinand** [comment]
The debug adapter is responsible to verify the version of the debugger.exe and report errors back to VS Code.

**Comment by wiener0zyj** [comment]
@weinand  yes, our adapter .exe could get the version information of debugger now. but we do not know how to let adapter communicate with extension.js and show the vscode messagedialog.

**Comment by weinand** [comment]
Three approaches:
- the debug adapter could just return an [error response](https://microsoft.github.io/debug-adapter-protocol/specification#Base_Protocol_ErrorResponse) from the Launch or Attach request request, and VS Code will show this as an error notification. See this [example from node-debug]( https://github.com/Microsoft/vscode-node-debug/blob/8b6d99bf915b77d6b859f939c8acd7c059fd48e0/src/node/nodeDebug.ts#L878).
- the debug adapter could send a custom event which the debugger extension could pick up by using [this API]( https://github.com/Microsoft/vscode/blob/6ea1f72513a50a265a216c3913bdedabefcc0f07/src/vs/vscode.d.ts#L8670)
- in your extension code you could register a `DebugConfigurationProvider` and in its `` method you get access to the launch configuration before the debug adapter is launched. There you could figure out the debugger version and pop up an error notification directly. Here is an [example](https://github.com/Microsoft/vscode-node-debug/blob/8b6d99bf915b77d6b859f939c8acd7c059fd48e0/src/node/extension/configurationProvider.ts#L48) from node-debug.

**Comment by wiener0zyj** [comment]
@weinand   We see,Thank you very much!

**Comment by wiener0zyj** [comment]
@weinand  Hello, Currently. we meet this problem, after we attach to an process. if we have set the breakpoints on our lisp scripts. the vscode would tell debug adapter which document opened currenlly. but If we do not set the breakpoints previously. vscode would not tell debug adapter which is the current active document by the request. but we need this info.
Is there any way to tell debug adapter current active documents when attach. or is there an custom request to do this? 
thanks very much!

**Comment by weinand** [comment]
There is no concept of a "current active document" when debugging.
VS Code sends **all** breakpoints to the DA via multiple `SetBreakpoints` requests (one for each file).
However, VS Code does not send breakpoints automatically. The DA needs to request the breakpoints by first sending a [`initialized`](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized ) event to VS Code. See section "Configuring breakpoint and exception behavior" in https://microsoft.github.io/debug-adapter-protocol/overview.

**Comment by wiener0zyj** [comment]
@weinand hi, our scenario is a little special. we attach to the Debugger firstly. currently, the lisp script has not been run. Then, we tell debugger the lisp script path and make debugger start the lisp script.
we take this step is because the debugger is AutoCAD which would take a long time to launch itself. 
So, is there any way that extension could tell DAP the current active document path?

**Comment by wiener0zyj** [comment]
@weinand Could I add the current active document into attach configuration?

**Comment by weinand** [comment]
yes, that's what I was trying to explain.
