### ISSUE TITLE
regression - explorer doesn't reveal elements nicely anymore

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#63900]
* configure the explorer to not auto-reveal elements
* open two files that are far away
* reveal them using the command
* 🐛 the files are minimally revealed, but not in the centre. this used to be working well

<img width="376" alt="screenshot 2018-11-28 at 09 41 18" src="https://user-images.githubusercontent.com/1794099/49139340-cb7ff180-f2f1-11e8-98f0-06c23fc9b106.png">

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/63406
