### ISSUE TITLE
Settings symlink cannot be deleted

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#63908]
- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Symlink settings, e.g. `mv ~/Library/Application\ Support/Code/User/settings.json ~/Desktop/settings.json && ln -sf ~/Desktop/settings.json ~/Library/Application\ Support/Code/User/settings.json`
2. Close and re-open VS Code
3. Now remove the symlinked file and the settings symlink, e.g. `rm -rf ~/Desktop/settings.json ~/Library/Application\ Support/Code/User/settings.json`
4. Close and re-open VS Code (not via terminal)

Does this issue occur when all extensions are disabled?: Yes

Expected: a new empty settings file will be created but not as a symlink

Actual: a new empty settings file is created but as a symlink

``` sh-session
$ ls -lah ~/Library/Application\ Support/Code/User/settings.json
lrwxr-xr-x  1 oliverjash  staff    78B 28 Nov 19:37 /Users/oliverjash/Library/Application Support/Code/User/settings.json -> /Users/oliverjash/Desktop/settings.json
```

This only appears to occur when I open VS Code outside of the terminal. If I open it with `code` (with or without `--disable-extensions`), the issue does not occur.

**Comment by OliverJAsh** [comment]
Even opening VS Code after a complete reinstall doesn't do the trick:

```
brew cask uninstall visual-studio-code && \
    rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist && \
    rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist && \
    rm -fr ~/Library/Caches/com.microsoft.VSCode&& \
    rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/ && \
    rm -fr ~/Library/Application\ Support/Code/ && \
    rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/ && \
    rm -fr ~/.vscode/ && \
    brew cask install visual-studio-code
```

(Steps from https://stackoverflow.com/a/47561948/5932012)

If I then open VS Code and then inspect the settings file, observe the symlink has been recreated:

```
$ ls -lah ~/Library/Application\ Support/Code/User/settings.json
lrwxr-xr-x  1 oliverjash  staff    78B 28 Nov 16:58 /Users/oliverjash/Library/Application Support/Code/User/settings.json -> /Users/oliverjash/Google Drive/Computer/Preferences/VS Code user settings.json
```

**Comment by roblourens** [comment]
>  a new empty settings file is created but as a symlink

Can you explain what you see exactly? Are you saying it recreated the settings file on your desktop with a symlink, or it recreated the symlink with no target or something else? This doesn't really make sense and I can't reproduce it. If the settings file is not present, vscode simply creates an empty file in the right location. My guess would be that it wasn't actually deleted?

**Comment by OliverJAsh** [comment]
@roblourens 

``` sh-session
$ ls -lah ~/Library/Application\ Support/Code/User/settings.json
lrwxr-xr-x  1 oliverjash  staff    78B 28 Nov 19:20 /Users/oliverjash/Library/Application Support/Code/User/settings.json -> /Users/oliverjash/Google Drive/Computer/Preferences/VS Code user settings.json

$ rm -rf ~/Library/Application\ Support/Code/User/settings.json

$ ls -lah ~/Library/Application\ Support/Code/User/settings.json
ls: /Users/oliverjash/Library/Application Support/Code/User/settings.json: No such file or directory
```

I then close and re-open VS Code, and I'm back to square 1:

``` sh-session
$ ls -lah ~/Library/Application\ Support/Code/User/settings.json
lrwxr-xr-x  1 oliverjash  staff    78B 28 Nov 19:37 /Users/oliverjash/Library/Application Support/Code/User/settings.json -> /Users/oliverjash/Google Drive/Computer/Preferences/VS Code user settings.json
```

An empty settings file is created at `~/Library/Application Support/Code/User/settings.json`, however it is a symlink pointing back to my original settings. It seems there is no way to delete the symlink—VS Code always recreates it! 😕

**Comment by roblourens** [comment]
Any idea @sandy081?

**Comment by sandy081** [comment]
No man.. may be related to node? @bpasero Are you aware of such issues?

**Comment by bpasero** [comment]
No

**Comment by OliverJAsh** [comment]
Can no-one reproduce this by following my steps? This is a fresh install of macOS and VS Code (new laptop).

**Comment by roblourens** [comment]
I followed those exact steps and can't reproduce.

**Comment by OliverJAsh** [comment]
> Did you have that file open in vscode when doing this?

Nope.

I don't know if this matters, but my symlink is in Google Drive (not on my desktop as the steps to reproduce suggest). I would imagine this can't have any effect though.

**Comment by OliverJAsh** [comment]
Can anyone suggest any steps (in addition to the [ones I've already tried](https://github.com/Microsoft/vscode/issues/63908#issuecomment-442522782)) to fix this? There must be some state stored by VS Code that is not being deleted when I try to uninstall it.

**Comment by OliverJAsh** [comment]
Found it! I'm so stupid. I have a `ln -s` in my `.zshrc`. :-|

Sorry for wasting your time!!!
