### ISSUE TITLE
hope to add a restart application under the menu

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#6390]
- VSCode Version:
- OS Version:1.1

Steps to Reproduce:

1, hope to add a restart application under the menu

![66](https://cloud.githubusercontent.com/assets/10474968/15282426/e3ee7198-1b75-11e6-823d-ff78a33ac24f.jpg)

2, Work file area hopes to increase the function of the height can be stretched

![77](https://cloud.githubusercontent.com/assets/10474968/15282479/1f077b26-1b76-11e6-8823-59dc79b100fc.jpg)

**Comment by isidorn** [comment]
I think you tried to upload a screenshot but failed.
Can you please clarify what behavior you are expecting and what behavior you are seeing

**Comment by lifetin** [comment]
Sorry, I didn't find the picture lost lying, now re upload

**Comment by isidorn** [comment]
We already have a restart it is called Reload window, you can find it in the command pallete, and you can also bind a keybinding to it

<img width="551" alt="screen shot 2016-05-16 at 09 15 02" src="https://cloud.githubusercontent.com/assets/1926584/15282899/b3cc0fe0-1b46-11e6-87c7-8e110ca29cc3.png">
