### ISSUE TITLE
Allow to format on save based on file extensions

### ISSUE THREAD

**Issue by andresmgot** [Microsoft/vscode#63909]
The current `Editor > Formatting > Format on Save` allows you to automatically format the current file. The problem is that I want to avoid that behavior for specific file types (in this case YAML files) since the automatic format doesn't complain with my team style. 

It would be great to be able to allow users to either configure how the formatting is applied or to disable it for certain file types.

Thank you for this awesome editor!

**Comment by usernamehw** [comment]
```javascript
"[yaml]": {
	"editor.formatOnSave": false
}
```

**Comment by andresmgot** [comment]
Oh, I didn't know that trick, thanks!
