### ISSUE TITLE
messy code in zsh on Mac

### ISSUE THREAD

**Issue by davelet** [Microsoft/vscode#63911]
- VSCode Version: 1.29.1
- OS Version: mac mojava

Steps to Reproduce:

1. press control + `
2. open the terminal
result:
```
  ~/vscodeProjects/settlement-web   feature/FMS-2198 
```
where the squares are right arrows or git symbol. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by davelet** [comment]
the terminal env is `zsh`, and using plugins of `https://github.com/fcamblor/oh-my-zsh-agnoster-fcamblor.git` and `https://github.com/zsh-users/zsh-syntax-highlighting.git`

**Comment by docbiz** [comment]
I use vscode and zsh (+ oh-my-zsh + powerlevel9k) and have no such issue; the special characters are rendered correctly. Are you sure you're using a typeface for the integrated terminal that contains the special characters required?

**Comment by rebornix** [comment]
You need to set `terminal.integrated.fontFamily` to any font that supports powerline.

**Comment by davelet** [comment]
@rebornix I set `terminal.integrated.fontFamily` to `'Meslo LG L Regular for Powerline'` but got a hit: `the terminal only supports monospace fonts`.
