### ISSUE TITLE
Find does not work after replace

### ISSUE THREAD

**Issue by RajatBanerjee** [Microsoft/vscode#6391]
- VSCode Version:1.1.0
- OS Version:windows 7

Steps to Reproduce:

1.  ctl + h
2.  do some stuff to replace something in the file
3) ctl + f, keeps the replace  option instead of find

**Comment by alexandrudima** [comment]
@RajatBanerjee Can you please provide more detailed steps, I am not sure what the issue is?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
