### ISSUE TITLE
intellisense is not working correctly , git sometimes does not show changes

### ISSUE THREAD

**Issue by Lokendra-rawat** [Microsoft/vscode#63917]
Issue Type: <b>Performance Issue</b>

please guys this is my fav. editor but the recent updates made is worse then ever i <3  the intellisense but its not working sometimes like its used to. please fix it on your next update 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.18.8-041808-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2269)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|11.64GB (1.02GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   131	 27614	code main
    0	    36	 27617	   zygote
    0	   310	 27656	     window (Repayment.test.js - app - Visual Studio Code)
    0	    95	 27698	       extensionHost
    0	   226	 27726	         electron_node tsserver.js 
    0	    95	 27746	           electron_node typingsInstaller.js typesMap.js 
    0	    83	 27711	       watcherService
    0	     0	 27814	       /bin/bash
    0	    95	 27751	     shared-process
    1	   107	 31393	     window (Issue Reporter)
    0	    71	 27649	   gpu-process
    0	     0	 31414	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 31415	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Repayment.test.js - app - Visual Studio Code)
|    Folder (app): 6025 files
|      File types: class(1804) xml(798) png(673) dex(611) jar(577)
|                  strings(241) json(205) h(170) java(157) js(128)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.6.1

</details>

**Comment by rebornix** [comment]
@Lokendra-rawat please provide more information like, what language you are using and how to stably reproduce this issue.
