### ISSUE TITLE
Broken documentation links to wiki page about Multi Root Workspace APIs

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#63912]
At https://code.visualstudio.com/docs/editor/multi-root-workspaces the Common Questions section has a broken link to https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs which I think should now be https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs

The wiki's sidebar TOC also contains the same broken link:

![image](https://user-images.githubusercontent.com/6726799/49148649-cc1f8480-f2ff-11e8-8f0a-1a7d9b4eac2a.png)

**Comment by gregvanl** [comment]
@gjsjohnmurray Thanks for pointing this out. Fixed with https://github.com/Microsoft/vscode-docs/commit/182469e561de11e9d4a52de67e6331c2bcc4fd68.
Also updated the wiki TOC link.
