### ISSUE TITLE
Navigation CTRL + Left Mouse click on React apps

### ISSUE THREAD

**Issue by xonofoxiju** [Microsoft/vscode#63920]
- VSCode Version: 1.29.1, x64
- OS Version: Win10 Pro

Does this issue occur when all extensions are disabled?: Yes

Hi,

I would like to report you bug. I think its a bug because 1 month ago this funtion was ok and now nope.  I have project created with command: create-react-app, and When I want to use navigation to another component clicking CTRL and mouse click there is no way only that vs code scroll up on the import definition for example:

I'm in folder: /src/components/module1 and when I click to navigate to the module 2 navigation only scroll up on the document where I actually am. We are using imports like this
-  import mlStore from 'stores/mlStore'; (without path like ../stores/mlStore).

Project Tree:
app.js
src/components/....
src/store/...

**Comment by mjbvz** [comment]
Try configuring a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) at the root of your project:


```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonJs",
        "baseUrl": "src"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

The important part is `baseUrl`. This lets VS Code know how to resolve non-relative paths
