### ISSUE TITLE
Reduce test runner animation?

### ISSUE THREAD

**Issue by dmke** [Microsoft/vscode#63922]
Is it possible to adjust the speed of the fade-in animation (or to turn it off entirely)?

![run-test-fade](https://user-images.githubusercontent.com/327411/49146317-333e3880-f302-11e8-94d6-271bc91b69ab.gif)

Maybe I'm impatient, but this just takes too long. Especially when I want to *quickly* run a specific test, I'm forced by the UI to take a 1-second break.

Another annoyance is that the animation replays when I switch tabs (i.e. open `foo_test.go`→animation plays, go to `foo.go`, go back to `foo_test.go`→animation plays again).

*N.B. This was first posted here: Microsoft/vscode-go#2159.*

**Comment by rebornix** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/19917

**Comment by dmke** [comment]
Ah, those are called "CodeLenses". Good to know, thanks!
