### ISSUE TITLE
Modify "open changes" button icon 

### ISSUE THREAD

**Issue by 10manjunath** [Microsoft/vscode#63924]
Issue Type: <b>Feature Request</b>

To see the changes i made to a source controlled checked-in file, a user clicks on the "Open Changes" icon on the top right. 

I would like to see a better looking icon that represents git and changes.

The current one looks like a **search button**. 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.14393

**Comment by joaomoreno** [comment]
@misolori What do you think?

Also note that changing this will affect other users and we'll soon get "but I was accustomed to the old icon!" messages.

**Comment by misolori** [comment]
At first glance, the icon does appear to look like some type of "search" button. Upon inspecting it, you can see that there are two files being compared (i.e. a diff). It's hard to see these details at a quick glance, so if there is a better icon we could use I'd be up to changing that. GitHub uses these icons for diffs/compare:

<img width="79" alt="image" src="https://user-images.githubusercontent.com/35271042/49427952-00ce8880-f7a5-11e8-9a9e-0e0671224907.png"><img width="85" alt="image" src="https://user-images.githubusercontent.com/35271042/49427931-f3190300-f7a4-11e8-8aa1-2a9197a1ef28.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/35271042/49428079-67ec3d00-f7a5-11e8-9294-f1f995cde956.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/35271042/49428101-76d2ef80-f7a5-11e8-8934-c81e7b1821f7.png">

I do like the last one the best (though it is an octicon).

**Comment by joaomoreno** [comment]
I like it. If you find me those assets, let's do it together!
