### ISSUE TITLE
Broken Korean in output panel

### ISSUE THREAD

**Issue by KafuChinoDesu** [Microsoft/vscode#63925]
- VSCode Version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Run Python Code in VSCode with Code Runner without Python installed in Korean Windows

Does this issue occur when all extensions are disabled?: No
![default](https://user-images.githubusercontent.com/39993457/49159700-6fa47f80-f368-11e8-8320-4ad682093d7a.png)

**Comment by sandy081** [comment]
Please file an issue against Code Runner extension
