### ISSUE TITLE
Diagnostic should include description field

### ISSUE THREAD

**Issue by ctcampbell** [Microsoft/vscode#63929]
Diagnotics currently only allow a basic message, meaning what is shown in the problems view will be the same as the hover text. I would like to include a title for viewing in the problems view, and a description for more detailed information that appears when hovering over the problem code, or when expanding the problem in the problem view.

**Comment by jrieken** [comment]
@ctcampbell Do you have an example compiler error/warning that works like that? If it's not that what is the use case here?
