### ISSUE TITLE
Missing folding block

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#63927]
Issue Type: <b>Bug</b>

I cannot collapse this anonymous class in https://github.com/Microsoft/vscode/blob/e5a93f37b1d8318bce296632fc87f3b8c3e7f3a6/src/vs/base/parts/ipc/node/ipc.net.ts#L169:L188

![image](https://user-images.githubusercontent.com/5047891/49160254-a6f23c80-f326-11e8-83a5-7e08c9456d17.png)

VS Code version: Code - Insiders 1.30.0-insider (b1d9b0982e78e51167a671908c39e058b343f21f, 2018-11-28T06:19:31.582Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/28709 to track this upstream
