### ISSUE TITLE
Auto-complete block comment duplicates symbols

### ISSUE THREAD

**Issue by zsculpt** [microsoft/vscode#63937]
- VSCode Version: 1.29.1
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. Type anything and put the closing block comment characters at the end (` */ `)
2. Type the opening block characters at the front (` */ `) and observe that extra closing block characters are created: `/*  */________________*/`

![image001](https://user-images.githubusercontent.com/5686852/49170331-194c2800-f2f9-11e8-8ab9-b21794fc53d8.png)
![image002](https://user-images.githubusercontent.com/5686852/49170348-2537ea00-f2f9-11e8-9fd8-43cfc7d64987.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by zsculpt** [comment]
Any feedback on this? Is there a way to disable this feature in the current build?

**Comment by zsculpt** [comment]
Still waiting for a proper response on this. The "feature" is now present on Windows builds as well. Please provide a way to disable this!

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.
