### ISSUE TITLE
Support expanding ~ in task cwd

### ISSUE THREAD

**Issue by Thyix** [microsoft/vscode#63932]
- VSCode Version: 1.29
- OS Version: Mojave 10.14

Steps to Reproduce:

I can not run the usual vscode tasks over sftp even if they operate in the workspace root:

```text
"options": {
                "cwd": "${workspaceRoot}"
            },
```

(in .vscode/tasks.json)
and even if the cwd is not given.

I always get

```text
chdir(2) failed.: No such file or directory
The terminal process terminated with exit code: 1
```

Is this a known issue or does it work for others?
Does this issue occur when all extensions are disabled?: Yes

**Comment by Thyix** [comment]
I just want to know how I can fix this error. I also get it when I'm opening a second terminal in my app, which is pretty annoying. Some people also got this error: https://github.com/mkloubert/vscode-remote-workspace/issues/56.

**Comment by geajack** [comment]
I'm having the same problem on Ubuntu 18.10. If I for instance open up any folder and create a new tasks.json with these contents:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "options": {
                "cwd": "~"
            },
            "type": "shell",
            "command": "echo Hello"
        }
    ]
}
```

then when running that task from Terminal > Run Task, I get OP's error message.

**Comment by alexr00** [comment]
Looks like you're right https://stackoverflow.com/questions/21077670/expanding-resolving-in-node-js

**Comment by geajack** [comment]
Is there an alternative way to write out the paths in the meantime?

**Comment by alexr00** [comment]
You can write out a relative path with ../ or make it an absolute path. I will add the ~ expansion soon!
