### ISSUE TITLE
Can you add a set of related files?

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#6393]
- VSCode Version:
- OS Version:1.1

Steps to Reproduce:

I would like to add a default settings that can be opened at any time.
I am windows, I would like to double click JS, PHP, CSS, JSON, and so on, is directly to use vscode to open it

**Comment by isidorn** [comment]
I think this should be possible by setting VSCode as a default editor on Windows. @gregvanl do we have some documentation on how to do this?

**Comment by gregvanl** [comment]
VS Code by default registers as the default program for .json files.
You can use Windows Explorer, right-click Open With..., Choose default program... to register VS Code for any file extension.
