### ISSUE TITLE
F5 not launching node app

### ISSUE THREAD

**Issue by paulmarshall** [Microsoft/vscode#63933]
Issue Type: <b>Performance Issue</b>

Taking too long to load

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (6.92GB free)|
|Process Argv|--folder-uri file:///c%3A/_src/retig/Orders.API|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   103	 18192	code main
    3	    81	  7664	   window (Process Explorer)
    5	    81	 10732	   window (Issue Reporter)
    0	    68	 16308	   shared-process
    0	   470	 18040	   gpu-process
    0	   221	 18408	   window (app.js - Orders.API - Visual Studio Code)
    0	     6	  3580	     winpty-process
    0	     3	 14728	       C:\WINDOWS\System32\cmd.exe
    0	     9	 18368	       console-window-host (Windows internal process)
    0	    96	 11260	     extensionHost
    0	    34	  4400	       C:\Users\paul.marshall\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\rzls.exe -lsp --logLevel None
    0	     9	  4452	         console-window-host (Windows internal process)
    0	    51	 11412	       electron_node eslintServer.js 
    0	   124	 14436	       electron_node tsserver.js 
    0	    46	 17840	         electron_node typingsInstaller.js typesMap.js 
    0	    34	 17592	       C:\Users\paul.marshall\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.954\dotnet_modules\vsls-agent.exe --autoexit --pipe 7e9389a2ae57471c8a3b0f48d33ca7be --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	     9	 17968	         console-window-host (Windows internal process)
    0	    39	 18004	       electron_node nodeDebug.js 
    0	    41	 18804	         electron_node app.js 
    0	     9	 18412	           console-window-host (Windows internal process)
    0	    14	 11964	     watcherService 
    0	     9	 15312	       console-window-host (Windows internal process)
    0	    37	 12764	     searchService
    0	    13	 15208	     electron-crash-reporter
    0	     6	 16000	     winpty-process
    0	     9	 16004	       console-window-host (Windows internal process)
    0	     3	 16160	       C:\WINDOWS\System32\cmd.exe
    0	    33	 19336	     C:\Users\paul.marshall\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.954\dotnet_modules\Microsoft.Cascade.VSCodeHostAdapter.exe --proxyInfoType64 eyJydW50aW1lIjoibm9kZSIsInByb2dyYW0iOiJjOlxcUHJvZ3JhbSBGaWxlc1xcTWljcm9zb2Z0IFZTIENvZGVcXHJlc291cmNlc1xcYXBwXFxleHRlbnNpb25zXFxtcy12c2NvZGUubm9kZS1kZWJ1Z1xcZGlzdFxcbm9kZURlYnVnLmpzIiwicGlwZU5hbWUiOiI4ZTNkYzRkYzQ2Nzg0MTVmYTI0ZDIzNzNiYWY3NWYyMiIsInR5cGUiOiJub2RlIn0=
    0	     9	 19328	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (app.js - Orders.API - Visual Studio Code)
|    Folder (Orders.API): 83 files
|      File types: js(27) md(19) png(9) css(5) map(4) html(4) json(3) yaml(3)
|                  yml(2) eslintignore(1)
|      Conf files: package.json(2) gulp.js(1);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sequence-diagrams|Ale|0.3.1
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
rest-client|hum|0.20.3
plantuml|jeb|2.9.10
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.954
vscode-zipexplorer|sle|0.3.1
vscode-status-bar-format-toggle|tom|1.4.0

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
