### ISSUE TITLE
VSCode extensions take a long time to activate.

### ISSUE THREAD

**Issue by Friday32** [Microsoft/vscode#63938]
- VSCode Version: 1.29
- OS Version: Windows 10

VSCode takes 3 to 4 seconds to activate an extension no matter what activation event is used.  With such  a long delay, it's very easy to modify a document before the extension starts.  

My extension must activate before user input can occur. The extension activates when a specific file type is opened. ( I also want VSCode to use the first line in determining whether or not it should activate. There is a "firstLine" option in contributions:languages, but it does not work in way that makes sense to me.)

The activation time should be improved.  A switch that prevent user input until activation in my scenario be the minimum fix.

**Comment by jrieken** [comment]
> My extension must active before user input can occur. 

No.

**Comment by jrieken** [comment]
This item contain no actionable information. Please select F1 > Startup Performance and attach the table for extension activation times

**Comment by Friday32** [comment]
-"Please select F1 > Startup Performance and attach the table for extension activation times" 

Here are the details of the relevant entry:
startup : false
codeLoadingTime: 180
activateCallTime: 662
activateResolvedTime: 0
activationEvent: "onLanguage:***"

I assume the times are in ms, but they are irrelevant.  If I set a break point on the first line of my extension's activate method in a debug session, it takes seconds to hit after opening a file that will trigger the activation event. I have enough time to type a sentence in the code editor. It's seems slightly faster if I copy my extension to "%USERPROFILE%\.vscode\extensions" and launch VScode.

- "My extension must active before user input can occur.
 No."

I probably wasn't clear. It's a requirement for my extension.

Here is some more information on my use case. My extension needs to decorate some of the text in a document. It's a color change. This happens almost immediately after the extension activates, but it strikingly annoying to see the color change 4 seconds after opening a document.  I also want to make portions of the document read only. There isn't a direct way to do this, but I can work around it detecting these areas and undoing the input provided the extension is operational.  During startup, the user can type in what should be read only locations.

**Comment by jrieken** [comment]
> Here are the details of the relevant entry:

You have more than just one extension, right? All extension share the same process and if there is another extension consuming all cpu cycles (e.g. on the same activation event) there is no chance for you extension to get excited. So, please attach a screenshot showing the full table.

**Comment by Friday32** [comment]
I can't control what extensions another users have installed or what issues they may have. So it really doesn't matter if another extension is causing a delay. But, you keep insisting on this table.

![image](https://user-images.githubusercontent.com/44408836/49299229-39aceb80-f48d-11e8-8ba0-95aa4fd9aae1.png)

**Comment by jrieken** [comment]
> So it really doesn't matter if another extension is causing a delay.

Yes, it does. You can obviously not control what other extensions are installed but it will help to understand this issue here. I assume that your extension is the one blanked out and that it activates `onLanguage:secret`. 

>  but it strikingly annoying to see the color change 4 seconds after opening a document

From https://github.com/Microsoft/vscode/issues/63938#issuecomment-442932266 it seems that your extension takes roughy 1 second to load its code and to active. So, where are those 3 seconds being spend?. As you can see [here](https://github.com/Microsoft/vscode/blob/4bea1ccfc04b14a3c4d0351288640a9aa6e3ccdc/src/vs/workbench/services/mode/common/workbenchModeService.ts#L150-L152) there is no delay in sending that event - it happens as soon as the mode is loaded (that means as soon as we know what language something is). 

So, I don't think that the 3 seconds happen *before* the activation event fires but *after*. Please share a repro with us so that we can understand where you thing time is being lost. Thanks

**Comment by Friday32** [comment]
My extension will be free, but I want to avoid my company's legal department for the time being. So, I created another project following the directions at: https://code.visualstudio.com/docs/extensions/yocode.

I tried a number of experiments and found that I can  get my extension to activate quickly. 

The real problem is that I want to my extension to respond to all user input.   I'm using  the onDidChangeTextDocument handler.  Data can be lost before the extension starts calling this handler.  There's a small time period when the extension should activate and VSCode won't pass on user input. Actions in the activate() method can greatly extend this period.  In my example, I want to create a webview in column 2. This will cause a significant delay  on my PC.

Here's the steps to reproduce the problem.
- Create an extension following the example at https://code.visualstudio.com/docs/extensions/yocode.
- Replace extension.ts with my file in the zipped attachment.
- In package.json, change activationEvents to "*".
- Build the extension.
- Copy the extension to %USERPROFILE%\.vscode\extensions. 
- Run VSCode, open a text file, and exit . 
- Launch Code again. (The file in the last step should reopen.) Start typing as soon as the file is opened. Eventually, a message will be displayed.

You should notice a considerable delay before a message appears. It displays time information, but doesn't really mean anything other than to demonstrate the delay. 

If you debug the extension , the example displays text entered by the user in the console window. You should notice lost data.

Hope this helps.

[extension.zip](https://github.com/Microsoft/vscode/files/2637673/extension.zip)

**Comment by Friday32** [comment]
"Yes, you don't receive events from the past but the document itself is up-to-date. "

I'm losing the ability to know what's changed; Maybe, there's some other way to determine that.

**Comment by Friday32** [comment]
I think deferring the launch of the web view is the way to get around this. ( I'm using it only because I don't know of another way to add GUI controls.)

**Comment by Friday32** [comment]
My work around is using the document's isDirty flag and discard the changes made by the user before my extension was ready.  I did this by loading the data from disk and using applyEdit.
