### ISSUE TITLE
Debug Console Drop Down broken

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#63939]
Issue Type: <b>Bug</b>

1) run lauch config A that produces output; ensure process finishes and output is visible
2) run lauch config B that produces output
=> output is shown
3) ensure process launched by B finishes
=> output of A shows
=> dropdown still shows A and B but switching between them has no affect, only output of A is shown 

VS Code version: Code - Insiders 1.30.0-insider (b1d9b0982e78e51167a671908c39e058b343f21f, 2018-11-28T06:12:06.315Z)
OS version: Darwin x64 18.0.0

I was a couple of versions behind before updating and saw the same behavior on the old build.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv|-psn_0_7563062|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
markdown-yaml-preamble|bie|0.0.2
solargraph|cas|0.17.6
ssh|chr|0.0.4
gitlens|eam|8.5.6
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.6.1
vscode-pull-request-github-insiders|Git|0.324.0
crazy|kie|0.0.2
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.4.2
python|ms-|2018.10.1
azure-account|ms-|0.7.0
azurecli|ms-|0.4.2
Go|ms-|0.7.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
ruby|reb|0.20.0
vscode-xml|red|0.2.0
vscode-workspacecontains-canary|rob|0.0.2
bash-debug|rog|0.3.3
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by cleidigh** [comment]
@isidorn 
If you think this resides within SelectBox let me know to look at it.

**Comment by isidorn** [comment]
@cleidigh no, I believe the issue here is in the debug console. Especially since Kai is on os x where we use a native select box. But thanks for offering.

**Comment by isidorn** [comment]
@kieferrm great catch, thanks
