### ISSUE TITLE
New settings editor has a "Provide Feedback" button that opens a GH issue which is closed to comments

### ISSUE THREAD

**Issue by kbuchsicf** [Microsoft/vscode#63930]
Don't you think you should have a button that works?

**Comment by roblourens** [comment]
Which version of vscode do you have? That button was removed some time ago.

**Comment by kbuchsicf** [comment]
1.26.0-insider. I see it is dated July 26, 2018. I don't see any updates, so maybe Insiders is not really maintained and I should just go with the regular one.

**Comment by roblourens** [comment]
Insiders is maintained and updated every day, it sounds like you have disabled auto updates or it just stopped working for some reason. Maybe try reinstalling.
