### ISSUE TITLE
Support for Dynamic Menus

### ISSUE THREAD

**Issue by Friday32** [Microsoft/vscode#63940]
You can add items to various menus.   I'd like to show these menu items conditionally, and there doesn't seem to be a way to do this.  An example is with the Explorer tree view.  I'd like to show additional menu options on a right-click when the user selects a specific directory.   

You would need to execute a precondition prior to showing the menu.

**Comment by jrieken** [comment]
You can, check the `when`-conditions: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by Friday32** [comment]
I did look at the when conditions before.  It's not clear to me, from the documentation, how to add my own condition. I did discover via our resources that I can do something like "vscode.commands.executeCommand('setContext', 'myWhenClause', true);" to set a clause, but the problem is that I need evaluate it on right-click event before the menu is displayed.  You need what item is selected in the tree.

**Comment by jrieken** [comment]
Yes, the `setContext`-command is what you need. Tho they must be set when state changes, not when a menu is to be shown. For the explorer that's hard, because you don't control it. You will likely have to see if one of the existing context keys works for you - there are such that reflect the name etc. 

To know do the following: "F1  > Inspect Context Keys", select an element in the UI, then open dev tools, and find all current context keys for that piece

**Comment by Friday32** [comment]
Thanks, I might be able to use this.  Can I use pattern matching in my when clause?

**Comment by jrieken** [comment]
yeah, you can use the `~=` operator with regular expressions

**Comment by Friday32** [comment]
Finally, got time to try it.  I need to use the "resource" context key that is a Uri and pattern match against fsPath.  Sorry, I'm new to this language and can't seem to get the syntax right. All other context keys are a string or boolean , and I could not find an example using resource.  I would expect it to be something like "when": "resource.fsPath =~ ...."

**Comment by jrieken** [comment]
use `resourceFilename` then

**Comment by jrieken** [comment]
Hm, tricky. You can try `resource` without `fsPath` (those are strings not objects) but might wanna file a new feature request for a context key with the full uri, its path, or fspath...

**Comment by Friday32** [comment]
For future reference,  I was originally thinking about adding something like WPF's MVVM pattern for Execute/CanExecute().
