### ISSUE TITLE
Must Restart Visual Studio Code For Html Changes To Appear In Browser When Using http-server

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#6394]
- VSCode Version: 1.1.0
- OS Version: Windows 10

Steps to Reproduce:

1.Create index.html and include button
2 Run http-server at command line (server starts)
3 Navigate in browser to localhost:8080 (view index.html)
4 Press Ctrl + C  (server stops)
5 Close browser
6 Change button to link in index.html
7 Restart server on command line with http-server
8 Navigate in browser to localhost:8080 (view index.html)
9 In dev tools, inspect the html.  The button has not been changed to a link.
10 Press Ctrl + C  (server stops)
11 Close browser
12 Close Visual Studio Code
13 Reopen Visual Studio Code
14 Run http-server at command line (server starts)
15 Navigate in browser to localhost:8080 (view index.html)
16  In dev tools, inspect the html.  The button is **now** changed to a link.

**Comment by Tyriar** [comment]
@MarkPhillips can you open index.html in another editor at the point where you expected it to change? Assigning to @bpasero as it seems to be about saving files.

**Comment by MarkPhillips** [comment]
I am not sure what happened.
I cannot replicate the issue anymore, but I had many times before
contacting you.
If this happens again, I'll let you know.

Thanks for you time,
Mark

**Comment by Tyriar** [comment]
No problems
