### ISSUE TITLE
vscode.debug API should provide the current thread/stack frame ids

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#63943]
Currently the `vscode.debug` API provides a way to send custom events to debug adapters. But it is missing one fairly important thing - there is no way to know what the current thread id / frame id is. So a debug adapter could maybe guess. But it feels like there should really be a way to query this.

**Comment by geajack** [comment]
Hi @hediet, I noticed you self-assigned this recently. I was wondering, is there any kind of plan as to what an eventual API on this might look like? I also wanted to check that this feature request is the same one discussed on a different repo [here](https://github.com/elazarcoh/simply-view-image-for-python-debugging/issues/15). Is the idea here to allow access to the ID of the "current" stack frame in the sense of the one that the user has selected in the VS Code debugger view in the sidebar?

**Comment by hediet** [comment]
It is unclear if this ever gets implemented, but I have a personal interest in it, thus I assigned it to myself to keep track of it.

**Comment by weinand** [comment]
@elazarcoh In principle we are willing to accept a PR. But since this is extension API it has to go through our extension API review process.
The first thing we need is an API proposal.

**Comment by elazarcoh** [comment]
is it something I can start? or it is something that is done only internally

**Comment by PaDebug** [comment]
Hello,
I also need the feature (get the current user selected frame id) in order to update the windows of the debugger extension (especially for multi-core devices). Does this feature make progress? Is there any workaround to get the frame id?

**Comment by elazarcoh** [comment]
@PaDebug if you'd like to help, you can write the API proposal. That would be the first step.

**Comment by elazarcoh** [comment]
> @elazarcoh  What do I need to do to write the API proposal?
> 
> I would propose extending the debug namespace by an event which fires when the user selected a different stack frame in the call stack window. For example:
> 
> export namespace debug {
> 
>     /**
>      * An event which fires when the user selected a different stack frame in the call stack window.
>      */
>     export const onDidChangeSelectedStackFrame: Event<StackFrame>;
>  }
> 
> The interface StackFrame consists of two properties: frameId and associated threadId. This would provide enough information to update the thread and stack frame in the Debug Adapter via custom request.
> 
> export interface StackFrame {
> 
>     /**
>      * Id of the associated thread (DAP id).
>      */
>     readonly threadId: number;
> 
>     /**
>      * Id of the stack frame (DAP id).
>      */
>     readonly frameId: number;
> }
> 
> What do you think about this?
> 

@weinand  will this do?

**Comment by haneefdm** [comment]
If this is implemented, it needs to be specific to a session. As in threadId/frameId are not enough. We have to deal with multiple concurrent debug sessions. Needs DebugSession object or at least the sessionId.

Doesn't frameId encapsulate/include threadId from a DA's perspective?

**Comment by gregg-miskelly** [comment]
> Doesn't frameId encapsulate/include threadId from a DA's perspective?

Yes, but I think you want to expose both so that a VS Code extension could call any DAP API which either took a thread id or a frame id.

**Comment by roblourens** [comment]
@gregg-miskelly @hediet could you tell me what the use case is? And does "current" mean "selected in the UI"?

**Comment by gregg-miskelly** [comment]
Yes, "current" means the one selected in the UI.

I originally ran into this when I wanted to implement Set Next Statement in the C# extension before the VS Code UI added support for it. It has also come up when potentially wanting to support a disassembly window (though again, this was solved by building the feature in VS Code instead). My team doesn't have a current need for this, though I still think this is a good idea as this makes the extension API very limited in terms of building any kind of debugger feature. Without this feature, it isn't possible for an extension to make valid DAP requests for lots of feature areas, especially anything involving looking at variables/expression evaluation.

**Comment by geajack** [comment]
For another use case, I ran into this when trying to develop a debugging extension for Python. One of the features was that you could type in a variable name, or more generally an expression, and you would get back a certain visualization of the value of that expression. In order to do this, the extension sends the expression over the DAP to have Python evaluate it and send the value back. However, the variable, or any variables in the expression have to actually be in scope for this to work.

If the user clicks back to a different stack frame in the UI, they can now view the values of variables in the build-in VSCode debugging panel. Since my extension also allows you to, in a sense, view the values of variables, the user expects to be be able to use it for any variables that they can see in the debugging panel. So I need to know when they switch stack frames to give them that experience. Right now my extension basically maintains a parallel list of stack frames in the UI, so if the user wants to climb back up the call stack and use my extension, they have to click the stack frame in both VSCode's built-in UI and in my extension's UI.

**Comment by hediet** [comment]
My use case is my [debug visualizer extension](https://marketplace.visualstudio.com/items?itemName=hediet.debug-visualizer). When the user selects a different stack frame than the top one, the watch windows and the visualizer window disagree.

**Comment by mblout** [comment]
I also have a use-case for having additional views participate in the debugging; being able to show a custom "registers" view that tracks with selection, for example. We also have some breakpoint functionality that changes if we're in an active session, and would leverage the active thread to 'scope' which threads for which it is active. 
So, I'd want to both interrogate the current/selected thread/stack frame (in session context) and to listen for changes

**Comment by mblout** [comment]
What would be the next step for moving this forward?  It is required for our use-case, where we are moving an existing debugger to vscode, and need to provide functionality that depends on the frame selection context. 
But I believe this would be _required more generally_ for any debugger that wants to provide any custom *views* that should show information for the selected context.

Ive started a branch based on @elazarcoh 's original branch, proposing this UI, just to test, and would propose the API below. 
https://github.com/mblout/hx-vscode/tree/mblout/debug-selection-63943

@weinand How are API change discussions driven, by the issue topic "api-proposal"?
(I haven't attempted to contribute before; can i add "api-proposal". @hediet  Should i assign this to me?)


```
	export namespace debug {
	  /**
	   * An event describing UI selection changes
	   */
		export type DebugFocusType = 'thread' | 'stackFrame' | 'empty';
		export interface DebugFocus {
			readonly type: DebugFocusType;
			/**
			 * Id of the debug session (DAP id). May be undefined if terminated, etc.
			 */
			readonly sessionId?: string;

			/**
			 * Id of the associated thread (DAP id). May be undefined if a session is selected, but no thread of frame is (this
			 * state is not currently possible in the UI)
			 */
			readonly threadId?: number;
			/**
			 * Id of the stack frame (DAP id), if applicable. May be undefined if a thread is selected, but no frame is (this
			 * state is not currently possible in the UI)
			 */
			readonly frameId?: number;
		}
		/**
		 * The currently focused thread or stack frame id, or `undefined` if this has not been set. (e.g. not in debug mode).
		 */
		export let focus: DebugFocus | undefined;

		/**
		 * An {@link Event} which fires when the {@link debug.focus} changes. Provides a sessionId. threadId is not undefined
		 * when a thread of frame has gained focus. frameId is defined when a stackFrame has gained focus.
		 */
		export const onDidChangeDebugFocus: Event<DebugFocus | undefined>;
	}

```

**Comment by haneefdm** [comment]
Hopefully, we get some traction on this. I have been waiting nearly three years for this. So many exciting things can happen with this.

**Comment by roblourens** [comment]
Looking at https://github.com/microsoft/vscode/compare/main...mblout:hx-vscode:mblout/debug-selection-63943, I think this is a reasonable proposal. I think that we could move forward with getting this into vscode as proposed API. I can't give any guarantee on how quickly we can stabilize that API but I think we could give you all something to experiment with and see if it properly fits your scenarios.

Info about frame/thread/session is exposed to API as context for contributed context menu actions in the callstack view. I think we should have extension API that matches that, which is set up here:

https://github.com/microsoft/vscode/blob/80026b700aaa26f1e280678f0011b3f7afa68ee5/src/vs/workbench/contrib/debug/browser/callStackView.ts#L56-L85

And I think I'd like to see three types here instead of one type with some optional properties that are only valid in certain combinations.

Also we should be more specific, maybe say `callstackFocus` and `onDidChangeCallstackFocus`. I wish there was one word that could mean "thread or frame or session", then I would say `focusedX`. 

If you can prepare a PR against the vscode repo, we can get it merged into vscode as proposed API.

**Comment by mblout** [comment]
Thank you very much @roblourens 
I want to make sure I understand; I think you are saying you would like the highlighted code, which sets up the menu item context, to be exposed through this new listener API.  The existing context is 'any' with three properties.
You would also like to see distinct types, and I'm not sure where you mean; 

something like this, where each of these types would be what each of those `assignXContext` functions set up today?
```
onDidChangeCallStackFocus: Event<SessionContext | ThreadContext | StackFrameContext | undefined>
```

**Comment by mblout** [comment]
or are you thinking something like:
```
onDidChangeCallStackFocus: Event<StackFrameContext | undefined>
onDidChangeCallThread: Event<ThreadContext | undefined>
```

**Comment by mblout** [comment]
@roblourens i separated the listener registrations and event types into two more specific ones; hoping this is more like what you're suggesting. (I wasn't sure about: the menu item context example seems to be type-less, with optional properties, and wasn't sure how to reconcile that with the rest of you comment)

Thank you for your comments! Maybe you could take a quick look before I do a PR
https://github.com/mblout/hx-vscode/blob/mblout/debug-selection-63943/src/vscode-dts/vscode.proposed.debugFocus.d.ts

**Comment by roblourens** [comment]
Sorry, I meant more like the way you had it initially with a single event and focus property, like your first example

`onDidChangeCallStackFocus: Event<SessionContext | ThreadContext | StackFrameContext | undefined>`

"Context" doesn't have to be part of the name. Also, instead of `sessionId`, you can use a `session` property of the type  `DebugSession` that already exists

**Comment by mblout** [comment]
@roblourens Thanks again! I still have some questions, but thought it might be easier to just create the PR and work through it there: https://github.com/microsoft/vscode/pull/179132
I did switch back to the one listener registration, and a 'union' event type.  But kept "Focus" in the name for the type to have it be distinct from other types elsewhere, and did not include DebugSession in the union, as that can be listened to elsewhere.  (But maybe the PR it the place...). Happy to hear all feedback.

re: paperwork, wasn't sure how to associate the pr with the issue, not sure if someone needs to assign to me? Let me know if i'm missing some steps, etc, Also let m e know if there's anything I can do to facilitate (meeting, etc).

(Looking forward! This is critical for us to move forward, and I expect it really does open up some interesting and obvious debug enhancements.)

**Comment by roblourens** [comment]
Does anybody also need to react to the selected debug configuration in the dropdown? There is also a feature request for this- I'm less enthusiastic about that, it seems unexpected to have the dropdown do anything other than decide which launch config to start. But another extension has a usecase where it signals which platform and arch you are targeting and so they can change up the UI based on that information. If you would also use that here it might make sense to tackle it at the same time.

**Comment by mblout** [comment]
Seems like an unrelated feature to me; I would suggest it should be a separate API - I think the distinction between selection related to artifacts related directly to debug UI context is different than "debug-related" UI selection (I think its debatable that it belongs in the 'debug' namespace)
I'd prefer to keep the scope of this change minimal - this is must-have for providing UI that can show information for a thread/stackframe context in sync with the existing views.  

(Do you happen to have the issue? I'd like to understand the scenario - i'm not imagining why it changing the UI after launching isn't acceptable. Thanks!)

**Comment by jrieken** [comment]
Verified the proposal exists, re-opening this issue for having a single record of all discussions until finalised. 

There are issues with the form of the proposals, namely us not using discriminated unions but old fashioned classes and instanceof-checks

**Comment by mblout** [comment]
Hi @jrieken , i'm still trying to learn and understand the contribution process, and wanted to understand your comment above; 
is there some action I should take for the changes that were part of this PR? https://github.com/microsoft/vscode/pull/179132/files

I see you added a lint rule, and also disabled it for the discriminators in some of the debug types; do these need to change? Thanks!

**Comment by roblourens** [comment]
Instead of using the discriminated type union interfaces for `stackFrameFocus`, we will use classes, and consumers can check the type with `instanceof`. If you would like to work on that, go for it, but we can also leave it alone while it's in the proposed state.

If you work on it, the class implementations go in `extHostTypes.ts` and you can see how this is handled for other APIs.

**Comment by mblout** [comment]
thanks for the guidance! i took a stab at it here: https://github.com/microsoft/vscode/pull/181244
i was uncertain on:
- is it typical to expose the statis "isXXXXXX" functions as part of the API?
- how should I handle checking the "DebugSession" property? i added a comment to the pull request

Also, how does a "proposed api" get promoted to first-class API?  And is there any process in which i can participate, or anything i can do?

**Comment by mblout** [comment]
Wanted to ask if there is anything I can do to make the discussions about promoting this proposed API easier?
Would a runnable demo help, like a [vscode-mock-debug](https://github.com/microsoft/vscode-mock-debug) pull request?
Animated GIF or other form of doc/example? Thanks again!
