### ISSUE TITLE
[Setting UI] Add ability to change language-specific settings

### ISSUE THREAD

**Issue by V-ed** [Microsoft/vscode#63948]
Type : **Feature request**

VSCode provides the ability to change settings based on the language type using such notation :

```json
"[java]": {
    "files.autoSave": "off",
    "editor.fontFamily": "'Fira Mono', Consolas, 'Courier New', monospace"
}
```

It would be great if the Settings UI be able to change settings based on those languages. Since any setting can be changed under languages, the UI itself wouldn't change - there'd simply be an indicator that you are modifying setting for the language `[LANGUAGE]`.

Quick mockup :
![image](https://user-images.githubusercontent.com/16652915/49179061-735fe400-f31f-11e8-87fc-5f7f49ce06ae.png)

Under the triple dot, a new option would appear : `Change by language` which is either a dropdown for all available languages or a button that opens the language picker (I would prefer the language picker, because it would even be easier to enter custom language id this way).

There would also be a button somewhere to come back to changing settings in general (not language-specific).

The fix for #60055 was to basically open the json setting because the Setting UI does not handle language-specific settings - if this feature would be implemented, the `Configure language specific settings` command could open this new mode automatically, therefore respecting the user's setting ui choice.

**Comment by roblourens** [comment]
I have #58995 for this request
