### ISSUE TITLE
Support additional functionality for logging to output channels

### ISSUE THREAD

**Issue by queeniema** [Microsoft/vscode#63941]
Issue Type: <b>Feature Request</b>

Features that would be nice to have:

- add timestamp by default (label on right?)
- support logging of messages by severity with coloring (e.g., `appendLine(value: string, severity: SeverityType)`)
    - severity types same as what's supported for notification messages: error = red, information = blue, warning = yellow, success = green
- support ability to show/filter by file source (e.g., `appendLine(value: string, source: string)`)
    - when multiple files are logging to a single output channel, it's difficult to determine where messages are coming from)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

**Comment by sandy081** [comment]
@queeniema May be you can use your own logging library and log into a file and we can support showing that file in the output channel? We do the same for our internal logs.

**Comment by queeniema** [comment]
@sandy081 That is an alternative... is there information on how to do that documented somewhere? I guess coloring would have to be done manually by the extension. I think it would be better if there was a standard way built into the API.

**Comment by sandy081** [comment]
Colouring is supported out of the box for log files. Try opening log channels in output panel. 

There is no specific documentation, but you can use any logger. But VS Code is yet to support creating a channel from a log file. If you willing to take this approach we can consider the request creating an output channel from log file.

**Comment by queeniema** [comment]
I see, thanks for pointing that out. Can you consider providing support out-of-box?

**Comment by sandy081** [comment]
> Can you consider providing support out-of-box?

Is it for creating an output channel from log file?

**Comment by queeniema** [comment]
Sorry, I meant to support the original requests... i.e., additional/modification of methods in the API.

**Comment by sandy081** [comment]
@queeniema May be not now. We will get back to it if there is a demand.
