### ISSUE TITLE
Show actual description for commands in Extensions Contributions section

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#63949]
The `Description` section in the Extensions Contributions section for commands shows the command title instead of command description.

I would say 2 most important things for a user in this section is the command title and description. Command id, keyboard shortcuts, menu contexts are all secondary information.

No one needs the id, unless they want to customize the keyboard shortcut.
Most of the commands dont have a default keyboard shortcut, and so that column is mostly empty. 
Most of the commands arent part of any menu, and so the Menu Contexts column is also mostly empty.

A new user or a existing user new to an extension would like to know what the extension can do. Command title and description is what will help. And so, these 2 should get priority in the limited real estate of the Contributions section

Note that there is no place in VS Code where one can see the descriptions of the commands contributed by an extension.

![image](https://user-images.githubusercontent.com/16890566/49181411-27f00a80-f30c-11e8-8c6d-89c6841c3daa.png)

VS Code version: Code - Insiders 1.30.0-insider (d3bb20c3fd1f23c369b80dca2ed25d54efd664e2, 2018-11-27T08:27:31.447Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
Description is not a valid property of the command and it supports only `title`.
