### ISSUE TITLE
${workspaceFolder} can not be resolved when trying to create a new vscode.Task and execute it immediatly

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#63951]
- VSCode Version: 1.29.1
- OS Version: Ubuntu 18.04.1 x86_64

Steps to Reproduce:

1. Create a new TypeScript extension with the following code, also registering `task-test.run` in package.json:
```ts
context.subscriptions.push(vscode.commands.registerCommand('task-test.run', async () => {
    const task = new vscode.Task({"type": "foobar"}, vscode.TaskScope.Global, "hello", "foobar", new vscode.ShellExecution("echo Hello, World!"));
    await vscode.tasks.executeTask(task);
}));
```
```json
{
    "command": "task-test.run",
    "title": "Run test task"
}
```
2. Load the extension and try running the added command.

I'm not sure if this is supposed to work or not. If not, this should at least have a proper clear error message.

P.S. If you don't define a scope for the task you get an unclear "Task is not valid" error.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@alexr00 can you have a look please.

**Comment by alexr00** [comment]
I can repro and I"m looking into it.

**Comment by alexr00** [comment]
There are a few problems here. First, we do have a bug so this won't work anyway(thank you for reporting!). Second, if you want to specify TaskScope.Global, you need to provide ShellExecutionOptions to the task that include a cwd.

Finally, if you want this to work right now, change to use TaskScope.Workspace.

**Comment by segevfiner** [comment]
It's not working in the current stable VS Code even with `TaskScope.Workspace`.

**Comment by alexr00** [comment]
Looks like there might have been some other changes that impacted this from stable to now. Thanks for checking that it works in master!

**Comment by isidorn** [comment]
Adding verfieid label based on the users comment that it is now working nicely
