### ISSUE TITLE
Changing files.associations setting has no effect

### ISSUE THREAD

**Issue by iissmart** [Microsoft/vscode#6395]
- VSCode Version: 1.1.0
- OS Version: Win7 SP1

Steps to Reproduce:

1. Add an entry to files.associations in the user's settings.json file, for example:
```json
"files.associations": {
	"*.bat": "Python"
}
```
2. Close and re-open VSCode
3. Open a .bat file
4. Observe that the detected language (bottom right) is Batch, not Python

**Comment by bpasero** [comment]
Try:

```json
"files.associations": {
	"*.bat": python"
}
```

**Comment by fiendish** [comment]
VSCode 1.4.0 in Fedora 24. Please reopen the issue?
```json
"files.associations": {
    "*.xml": "lua"
}
```
Language is still set to XML instead of Lua after restarting VSCode and re-opening file. Rename attached file to test.xml instead of test.txt.
[test.txt](https://github.com/Microsoft/vscode/files/403594/test.txt)

**Comment by bpasero** [comment]
That I cannot reproduce:

![editors](https://cloud.githubusercontent.com/assets/900690/17472268/65e57636-5d4a-11e6-894e-0f364d99529d.gif)

**Comment by jonlong** [comment]
@fiendish 

Just jumping in to say I had this issue as well, and mine turned out to be a local settings file in a project-level `.vscode` directory that was overriding my user-specific settings. Hope that helps!
