### ISSUE TITLE
Command prompt slow and freezing + layout issue

### ISSUE THREAD

**Issue by FreddyCrugger** [Microsoft/vscode#63961]
Layout in command prompt is broken, I need to press enter at least once to be able to see the first line of text. The second issue is that Visual Studio code freezes on windows 10 since the last update. It is not running smoothly, there is for sure something wrong with the command prompt as even the commands are running slowly compared to usual.

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

CPUs | Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz (4 x 2833)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 6.00GB (3.16GB free)
Process Argv |  
Screen Reader | no
VM | 0%

laravel-docs | aus | 1.3.0
-- | -- | --
vscode-intelephense-client | bme | 0.8.8
laravel-goto-view | cod | 1.2.3
bracket-pair-colorizer | Coe | 1.0.61
jshint | dba | 0.10.20
vscode-eslint | dba | 1.7.0
EditorConfig | Edi | 0.12.5
php-debug | fel | 1.12.6
php-intellisense | fel | 2.3.10
auto-close-tag | for | 0.5.6
vscode-php-cs-fixer | fte | 0.1.0
beautify | Hoo | 1.4.7
vscode-phpfmt | kok | 1.0.30
php-namespace-resolver | Meh | 1.1.0
dotenv | mik | 1.0.1
color-highlight | nau | 2.3.0
vetur | oct | 0.14.2
laravel-blade | one | 1.18.0
laravel-extension-pack | one | 0.4.0
laravel5-snippets | one | 1.5.0
vue-beautify | pea | 2.0.4
laravel-artisan | rya | 0.0.23
html5-boilerplate | sid | 1.0.3

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
