### ISSUE TITLE
Ability to close and folders to reduce resource consumption in multi-root workspaces

### ISSUE THREAD

**Issue by brsanthu** [microsoft/vscode#63963]
Eclipse has a concept of closing and opening projects. Closed projects are still part of the workspace but no files are visible from that project and essentially reduces the resources Eclipse consumes. Also help avoid the clutter (when search for something across workspace or opening file etc).

![image](https://user-images.githubusercontent.com/842964/49196673-a6669f80-f340-11e8-88c8-f03817df517c.png)
_Image is from https://stackoverflow.com/questions/51627864/how-to-close-folderdisabled-in-the-vs-code-workspace-like-eclipse_

Vscode has feature called remove folder from workspace but it completely removes it. If we need it back, we need to browser for it and add it.

I would like to request to add feature to close and open folders similar to Eclipse.

**Comment by 1138-4EB** [comment]
I'd like to have this feature too, since the git integration frequently complains about too large workspaces. However, I would suggest to name it 'enable/disable folder', instead of 'open/close'.

**Comment by jakub-g** [comment]
I'll just paste comment from my dupe ticket:

**There should be a new option: `Disable folder` / `Enable folder`** in the menu below:

When folder is `disabled` it just shows up in the list, but is _effectively dead_ (not searchable etc.)

# Vscode:

![image](https://user-images.githubusercontent.com/1437027/69337295-c9c8df80-0c60-11ea-9511-64234bfa0503.png)

# Eclipse:

![image](https://user-images.githubusercontent.com/1437027/69337099-5aeb8680-0c60-11ea-89ca-b2da660143da.png)
![image](https://user-images.githubusercontent.com/1437027/69337149-79ea1880-0c60-11ea-9240-ea6ee6344234.png)

**Comment by novavsc** [comment]
Please consider adding this feature. It will be extremly useful when working with multiple projects/folders.

**Comment by TheTechOddBug** [comment]
Suggestion: Use one of the "Favorites" extensions available. You can have your "closed-desired" projects/folders to a few clicks/keystrokes.

**Comment by ReeezZ** [comment]
It's been some time. Is there any hope this feature will still come?

**Comment by ahmadi3d** [comment]
I also need this feature, being able to enable and disable workspace folders can really speed up the user's workflow, Thank you.

**Comment by ajay-lines** [comment]
Need this feature in VS Code.

**Comment by kimtiago** [comment]
I want this feature!

**Comment by kimtiago** [comment]
Here's a workaround that's not ideal, but it's better than nothing. You can modify the project settings to hide the unnecessary folders. 

Problem:
--------

I have a workspace in VS Code with the following folders:

    folder1
    folder2
    folder3
    folder4

I only want to work with **folder3.**

Solution:
---------

Add the following to the **.vscode/settings.json** file of your workspace:

    {
      // above your additional configurations
      "files.exclude": {
        "folder1": true,
        "folder2": true,
        "folder4": true
      }
    }

This will make vscode hide these folders. If you want them back, just remove this code from the file. This works for files too.

**Comment by vallsv** [comment]
> Here's a workaround that's not ideal, but it's better than nothing. You can modify the project settings to hide the 
> This will make vscode hide these folders. If you want them back, just remove this code from the file. This works for files too.

Interesting. Any idea if such trick could be used by an extension?

**Comment by ironluca** [comment]
I am many years too late to this but this is a very useful feature to have. For large workspaces when Maven build starts it takes for ever to complete. Give the ability to close workspace folders temporarily

**Comment by Bonnevie** [comment]
even more hacky than the other solution, but it seems to work to just comment out the folders from the workspace file - UI reacted immediately. Don't know if it has downsides, but I guess vscode should be fairly robust to adding/removing folders.

**Comment by gian1200** [comment]
Should this issue be reopen or a new one should be created?

**Comment by ahmadi3d** [comment]
@gian1200 , I'm not sure, but I know that many people have commented on this feature and there is still no official response. The ability to disable folders so they don't exist would be huge. For example, you could open multiple projects, disable all but one, and work on the active one while still being able to visit the disabled ones and incorporate them into your current setup. I also believe that implementing this feature should be relatively easy. If they were to reopen this and actually implement it, it would be great

**Comment by bruno-viva** [comment]
Please add your thumbs up in https://github.com/microsoft/vscode/issues/237353 if this is still a feature you want! Thanks
