### ISSUE TITLE
After opening two Windows, the new page in the first window cannot be edited

### ISSUE THREAD

**Issue by yushuanghe** [Microsoft/vscode#63964]
Issue Type: <b>Bug</b>

Open git project window a, open normal folder window b, and the content cannot be edited in the new TAB page of window a

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.52GB (3.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
scala|dal|0.0.5
mysql-syntax|jak|1.3.1
hive-sql|jos|0.0.4
vscode-json5|mrm|1.0.0
vscode-language-pack-zh-hans|MS-|1.29.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Tyriar** [comment]
I'm not sure I understand the steps, you opened 2 windows in different folders and you can't edit files in one window?

**Comment by yushuanghe** [comment]
Yes, it works when I close the first window and reopen the folder.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Daniel Imms <notifications@github.com>
发送时间: Saturday, December 1, 2018 3:49:25 AM
收件人: Microsoft/vscode
抄送: yushuanghe; Author
主题: Re: [Microsoft/vscode] After opening two Windows, the new page in the first window cannot be edited (#63964)


I'm not sure I understand the steps, you opened 2 windows in different folders and you can't edit files in one window?

―

**Comment by Tyriar** [comment]
Is it just the editor that doesn't work? You mentioned git in your report, does it have something to do with the git integration?

**Comment by yushuanghe** [comment]
I cannot confirm whether git is related or not. The TAB page I created in git folder cannot be edited, but the file that has been opened for editing is normal. Everything works fine in the other window.

**Comment by Tyriar** [comment]
Can you provide a screenshot of the "TAB page" you can't edit?

**Comment by yushuanghe** [comment]
Sorry, I didn't take a screenshot. I can't reproduce it now.
