### ISSUE TITLE
Tree item label allows html injection

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#63968]
Issue Type: <b>Bug</b>

I'm a tiny bit torn on reporting this vs using it for cool new features, but... 😄 

If you set the label of a custom view tree item to a string with HTML it gets injected directly into the DOM. 😱 

/cc @sandy081 

VS Code version: Code - Insiders 1.30.0-insider (d3bb20c3fd1f23c369b80dca2ed25d54efd664e2, 2018-11-27T08:27:31.447Z)
OS version: Windows_NT x64 10.0.18290

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (20.42GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
@eamodio Thanks for reporting. But I was aware of this already while implementing tree view message 😄
