### ISSUE TITLE
Multiline select starting column should be the position of the mouse at the start, not the first selector

### ISSUE THREAD

**Issue by msparica** [microsoft/vscode#63975]
When you make a multiline selection after the end of a line then drag down to others, the starting column for each line isn't the position of the mouse at the start of the selection, but the column of the first selected line's last character, which makes selecting multiple ends of lines difficult for lines of differing length.

How it works in SublimeText 3:
https://gfycat.com/BrilliantBlankAmazonparrot

How it works in VS Code:
https://gfycat.com/LavishEllipticalKronosaurus

It would be awesome if it worked like Sublime's multiselect in this case, since that is my only real gripe with VSCode, after switching from Sublime.

**Comment by othyn** [comment]
This is an annoyance for me too!

**Comment by msparica** [comment]
> This is an annoyance for me too!

This works now, though. It's been fixed at some point, not exactly sure when.

**Comment by othyn** [comment]
No it hasn't been fixed, that behaviour still occurs.

**Comment by msparica** [comment]
> No it hasn't been fixed, that behaviour still occurs.

It's working for me. I'm on version 1.40.2, with the only extensions I use being: 
AutoHotkey, 
Python, 
Rainbow CSV, XML and XML Tools.

https://gfycat.com/vapidselfishchuckwalla

**Comment by othyn** [comment]
By chance are you using the keyboard? This issue is referring to the mouse behaviour, see:

Sublime, expected behaviour:
![sublime](https://i.imgur.com/wyeB6TM.gif)

VS Code, unexpected behaviour:
![vscode](https://i.imgur.com/ek9Pusr.gif)

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

macOS Catalina `10.15.1` build `19B88`.

**Comment by msparica** [comment]
> By chance are you using the keyboard? This issue is referring to the mouse behaviour, see:

Nah, you can see the mouse in the gfycat link. Not sure what's going on. 
My version: 
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Maybe it's a Mac thing, but that shouldn't matter in an Electron app. Reopening since it's apparently still a thing.

**Comment by othyn** [comment]
Thank you! That's really odd then, let's hope it can be looked into 👍

**Comment by othyn** [comment]
By chance, do you have your preferences JSON that I could reference, just to see if there is anything that I have enabled that may cause this compared to your setup?

**Comment by msparica** [comment]
You mean settings.json?

here's the only thing in mine:
```json
{
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true
}
```

**Comment by othyn** [comment]
Damn, was hoping there would be something!

**Comment by Montago** [comment]
+1

**Comment by alexdima** [comment]
@othyn Using the middle mouse button, this works for me:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/101099608-4527d580-35c5-11eb-8b88-3aef6089827f.gif)

Would you mind trying one more time to check if this is still an issue?
