### ISSUE TITLE
Cannot read property tasks of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63973]
Start vscode out of source, notice this exception

![screenshot 2018-11-29 at 10 22 26](https://user-images.githubusercontent.com/1926584/49211829-bb831300-f3c0-11e8-8aa2-2f5ee0a9d701.png)

**Comment by alexr00** [comment]
This should be fixed with e6adb169d0. Do you have it already?

**Comment by isidorn** [comment]
Yup it is fixed now, thanks. Wanted to file this yesterday but forgot.
