### ISSUE TITLE
Support an option to disable-direct-write

### ISSUE THREAD

**Issue by RandScullard** [Microsoft/vscode#6397]
- VSCode Version: 1.1.1
- OS Version: Windows 10

I'm passing the --disable-direct-write command-line option to VSCode to work around the blurry font issue on Windows. This works fine, but every time VSCode updates, the installer overwrites my changes to the VSCode start menu shortcut and registry setting. It would be great if I could put the --disable-direct-write option somewhere in my VSCode settings that doesn't get overwritten when a new update is installed.

**Comment by Tyriar** [comment]
One workaround is to copy the shortcut and use that one instead.

**Comment by joaomoreno** [comment]
@bpasero [BrowserWindows](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) seem to support passing this option `directWrite` on creation. Can we make a setting out of this?

**Comment by Tyriar** [comment]
Instead of another setting, how about a generic command line args setting? `--disable-gpu` is another common one people want.

**Comment by joaomoreno** [comment]
That's what the user already has.

**Comment by Tyriar** [comment]
settings.json:

```json
{
  "window.commandLineArgs": [
    "--disable-direct-write",
    "--disable-gpu"
  ]
}
```

**Comment by RandScullard** [comment]
@Tyriar is that setting already available in the software, or is that a proposed solution?

**Comment by Tyriar** [comment]
@RandScullard just a suggestion

**Comment by RandScullard** [comment]
:thumbsup:

**Comment by joaomoreno** [comment]
Oh I see, I misread your suggestion, sorry! Might be nice, yeha.

**Comment by bpasero** [comment]
Closing, Chrome 52 decided to remove this option. direct write is always on from then on.

**Comment by eladkarako** [comment]
<code>--disable-directwrite-for-ui</code> <sub><a href="http://icompile.eladkarako.com/disable-direct-write-alternative-for-chrome/" title="#disable-direct-write Alternative For Google Chrome"><em>source</em></a></sub>

**Comment by foisonocean** [comment]
@eladkarako This is not work for me

**Comment by eladkarako** [comment]
@foisonocean 
```cpp
// found in the LICENSE file.

#include "build/build_config.h"
#include "ui/gfx/switches.h"

namespace switches {

#if defined(OS_WIN)
// Disables DirectWrite font rendering for general UI elements.
const char kDisableDirectWriteForUI[] = "disable-directwrite-for-ui";
#endif

#if defined(OS_MACOSX)
// Enables the HarfBuzz port of RenderText on Mac (it's already used only for
// text editing; this enables it for everything else).
const char kEnableHarfBuzzRenderText[] = "enable-harfbuzz-rendertext";
#endif
```

only works on Windows, try `--enable-harfbuzz-rendertext` or `--disable-harfbuzz-rendertext` if you're on a different OS.
