### ISSUE TITLE
suggestion: Add Highlights and Transitions to File Explorer to improve visual navigation

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#63979]
Navigating and switching between files in large trees is confusing. Adding **additional highlights** and **transitions** to the File Explorer would help at creating and maintaining of the mental context map of the files.

-> Most important feature for me is that the auto-reveal scroll is transitioned so that it doesn't jump.  
-> Hovering over "Open editors" at the top highlights the file in File Explorer too.  
-> Transition for Current + Previous selections:

  a) the selection box fades out on previous selection or
  b) the selection box physically moves from previous to next selection _(rather complicated)_
![image](https://user-images.githubusercontent.com/2313018/49213992-ede33f00-f3c5-11e8-9fe3-ca4edb95e0a5.png)

-> Highlight Open Editors in File Explorer (box, border, underline, gutter, w/e), similar to modified, unsaved, etc. files

![image](https://user-images.githubusercontent.com/2313018/49216104-84196400-f3ca-11e8-9a29-53587b1ee116.png)

-> More sophisticated truncation of long file paths _(might affect both, Open Editors Explorer and Editor Tab name)_

currently:
![image](https://user-images.githubusercontent.com/2313018/49216585-ba0b1800-f3cb-11e8-87a6-d13f96579778.png)

suggestion:
![image](https://user-images.githubusercontent.com/2313018/49216899-7fee4600-f3cc-11e8-8686-cdb6cfa360a1.png)

I have loosely used this rule.
- Shorten from the begin to ~2 characters
- whenever there is CamelCase, use `MyCamelCaseFile` -> `MyCaCaFi` or -> `MCCF` if more characters need to be saved. _(reverse logic to how fuzzy search works)_
- use `...` when necessary but at the begin of the string, not at the end
NOT: `packages\intermediary\src\screens\NewApplicatio...` _(currently)_
YES: `...\src\screens\NewApplicationScreen\index.js`
BEST: `...\pa\in\sr\sc\NewApplicationScreen\index.js` _for very long paths_

**Comment by isidorn** [comment]
We prefer smaller concise issues.
One large issues which mentions lots of unrelated problems will probably not be tackled. Though leaving this as a feature request for now

**Comment by ackvf** [comment]
I can totally split all the suggestions if you prefer it.
