### ISSUE TITLE
References tree does not render parents text as white when selected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#63977]
As seen in "Find References":

![image](https://user-images.githubusercontent.com/900690/49213575-dce5fe00-f3c4-11e8-9091-6e5ad8ad99b4.png)

**Comment by joaomoreno** [comment]
This is actually an issue with two causes:

1. The `IconLabel` isn't being used here... should it be?
2. That white style is hardcoded in the `IconLabel` CSS: https://github.com/Microsoft/vscode/blob/cabd0e4885e44ceae1d1d782fa2de26b016832f7/src/vs/base/browser/ui/iconLabel/iconlabel.css#L63-L77. This was introduced by @jrieken in https://github.com/Microsoft/vscode/commit/ba873cd5f3244a6142eaa8e9c0259c4e0b4b4c6c

**Comment by jrieken** [comment]
> Also, the IconLabel isn't being used here... should it be?

I wanna use `ResourceLabel` but that locked into the workbench and not available for re-use...

**Comment by jrieken** [comment]
I will just nuke that special color treatment, no clue why we have it in the first place...

**Comment by jrieken** [comment]
I have pushed a fix put @joaomoreno should be on the look out as this is a behaviour change between the old/new tree

**Comment by joaomoreno** [comment]
@jrieken I don't understand why you still have to override anything. The list is already doing the right thing:

https://github.com/Microsoft/vscode/blob/5f914ae2a7f651b82c3d543a8b02e28699775dce/src/vs/base/browser/ui/list/listWidget.ts#L649

So you gotta see who is stealing the default list style, instead of just `!important` override it.

**Comment by joaomoreno** [comment]
@jrieken Here is your culprit:

https://github.com/Microsoft/vscode/blob/5f914ae2a7f651b82c3d543a8b02e28699775dce/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L614

**Comment by jrieken** [comment]
Yes, I know... May plan was to delete the color but it looks like @aeschli added that on purpose so will leave it.
