### ISSUE TITLE
QuickOpen focus behavior

### ISSUE THREAD

**Issue by iliazlobin** [Microsoft/vscode#63985]
QuickOpen is a feature that helps to open necessary views fastly. I mainly use it to switch between recently opened files. It's a big plus in productivity when you can switch fast between files.

I usually open two editor groups one for main work and another to keep additional information. When I am in need of to open a specific file, I use QuickOpen feature and select a file. If the file is placed in the editor group then it refocused. It is the desired behavior. But if the file in another editor group the same file opens in mine. Thus I have two similar files in both editor groups which is not convenient.

It would be nice if there would be a config that set up such behavior. For example:
```settings.json
"workbench.quickOpen.globalFocus": true
```

If the option is true, then it refocuses window if that exists in any of our editor groups.

**Comment by bpasero** [comment]
Can be configured via `"workbench.editor.revealIfOpen": true`
