### ISSUE TITLE
tittle bar custom is not working

### ISSUE THREAD

**Issue by MrMuMu** [Microsoft/vscode#63982]
Custom title bar is not showing.

Version: 1.30.0-insider (user setup)
Commit: cd5b4d1bb3fc7e509fba077095b2b280b8ff7161
Date: 2018-11-29T06:32:54.872Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

It is now like this:
![image](https://user-images.githubusercontent.com/11612804/49219281-d74be080-f3e3-11e8-8b79-cb2e25e2dedc.png)

It was like this:
![image](https://user-images.githubusercontent.com/11612804/49219290-ddda5800-f3e3-11e8-8861-d54f87da4b2a.png)

Title bar style:
![image](https://user-images.githubusercontent.com/11612804/49219396-2d208880-f3e4-11e8-925c-5ce75c69e6ba.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@MrMuMu Can you verify that `window.smoothScrollingWorkaround` is not enabled on the problematic build. It is incompatible with the custom titlebar

**Comment by MrMuMu** [comment]
@sbatten it was enabled, it is fixed when I disabled it. However it was working before when it was enabled. Is there a specific reason for disabling it?

**Comment by sbatten** [comment]
@mrmumu the smooth scrolling workaround does not work when the custom title bar is enabled and a recent refactor introduced this check

**Comment by MrMuMu** [comment]
thank you for explanation, have a nice day, closing the issue.

**Comment by sbatten** [comment]
@lochstar  see comment https://github.com/Microsoft/vscode/issues/64967#issuecomment-446965079
