### ISSUE TITLE
files.watcherExclude not working on latest version!

### ISSUE THREAD

**Issue by GregLarden** [Microsoft/vscode#63989]
NOT multi-root

VS Code :
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:
This is my configuration in 
User Settings:
 "files.useExperimentalFileWatcher": false,
        "files.watcherExclude": {
            "**/src/assets/**": true,
            "**/node_modules/*/**": true
        },
   

Workspace Settings;
 "files.watcherExclude": {
        "**/src/assets/**": true,
        "**/node_modules/*/**": true
    },

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I don't think that's a valid path. Here's the form used in the default value, I suggest copying that:

```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/*/**": true
  }
```

**Comment by GregLarden** [comment]
@Tyriar , I have tried "**/assets/**": true AND **/assets/customstyles/**": true 

None of the suggestions I found online or paths I have tried worked.

**Comment by Tyriar** [comment]
I can repro using both `files.useExperimentalFileWatcher` being true or false and this setting:

```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/*/**": true
  }
```

Changing `./node_modules/somefolder/somefile` fires an event.

@bpasero any ideas what could have caused? I haven't touched the file watcher since April

**Comment by Tyriar** [comment]
This is probably https://github.com/Microsoft/vscode/issues/4089

**Comment by bpasero** [comment]
@Tyriar I can reproduce and I am puzzled too, will have a look.

**Comment by bpasero** [comment]
@Tyriar looks like a red herring to me, I tried on Windows with NSFW and correctly get the ignored message: 

![image](https://user-images.githubusercontent.com/900690/49271742-3efb3d80-f46f-11e8-8083-c8235c547528.png)


The same is true for the C# watcher. Though the output is misleading, I can see that a `NORMALIZED` event is reported, however it is being ignored in our system (thats what the other message shows):

![image](https://user-images.githubusercontent.com/900690/49271789-6baf5500-f46f-11e8-83c1-3d88e37fd8d4.png)
