### ISSUE TITLE
Support high intensity ansi colours in debug console

### ISSUE THREAD

**Issue by MontyBlenheim** [microsoft/vscode#63986]
This issue is basically to revive one I previously found: Microsoft/vscode#21423

The issue was closed when underlining functionality was added, but the original request, for high intensity colours, was never addressed. Any chance these could be added?

I was using the c++ extension and my program would log using the ANSI codes. I saw no visible difference in colour between, for example:

Red (\033[31m)
Bright Red (\033[31;1m)
aixterm Bright Red (\033[91m)

![Colour code output](https://user-images.githubusercontent.com/37301384/49227476-14fb3a00-f3e1-11e8-9a5e-a3d95d3ba8ab.jpg)

Now clearly you've gone for the "bold" interpretation of the "bold or high intensity" option of having ";1" after your colour. But is there any chance of the aixterm versions working?

**Comment by iansan5653** [comment]
Relevant code is https://github.com/Microsoft/vscode/blob/1f64c126721a66f30a7dcc3ac9e605e8115bcca7/src/vs/workbench/contrib/debug/browser/media/repl.css#L130.

I'll submit a pull request for this tomorrow if there's no objections.

**Comment by alexr00** [comment]
I think that they look different, but it's subtle.
```
	console.log('\033[31mRed\x1b[0m');
	console.log('\033[31;1mBright Red\x1b[0m');
	console.log('\033[91maixterm Bright Red\x1b[0m');
```
![image](https://user-images.githubusercontent.com/38270282/58569218-f82bac00-8235-11e9-9726-0bf5d27a3dc1.png)

**Comment by iansan5653** [comment]
The exact colors depend on the theme so it can be pretty subtle but it's there.
![image](https://user-images.githubusercontent.com/2294248/58575652-83924680-8210-11e9-92a5-a4810c931fbd.png)
