### ISSUE TITLE
Open in Terminal with iTerm on Mac

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#6398]
- VSCode Version: 1.1.1
- OS Version: 10.11.4

Steps to Reproduce:

1. Use iTerm2 version: 2.1.4
2. in iTerm2, Make iTerm2 the default terminal: Ctrl-Shift-Cmd-\
2. in VsCode: Right-click on a Folder, Select: Open in Terminal

The terminal opens in the last folder that iTerm was used and not the selected one.

**Comment by Tyriar** [comment]
This will be fixed by https://github.com/Microsoft/vscode/pull/6136
