### ISSUE TITLE
High memory consuption

### ISSUE THREAD

**Issue by PKMNTR** [Microsoft/vscode#63999]
Issue Type: <b>Performance Issue</b>

Usually VSCode use around 1GB ram but from some days ago the ram usage increase to 2GB just in startup and 1.5GB  with all extensions disabled. Hope you can help me. Usually work php, html, css and js.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.10.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.78GB (0.91GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   128	  2706	code main
    0	    39	  2712	   zygote
    0	   112	  2810	     shared-process
    1	   112	  3120	     window (Process Explorer)
    0	     0	 25970	       /bin/sh -c "/usr/share/code/resources/app/out/vs/base/node/cpuUsage.sh" 2706 2712 2774 2810 3120 9118 25765 25968 9285 9303 9402 25969 9626
    0	     0	 25971	         /bin/bash /usr/share/code/resources/app/out/vs/base/node/cpuUsage.sh 2706 2712 2774 2810 3120 9118 25765 25968 9285 9303 9402 25969 9626
    0	     0	 25984	           sleep 1
    0	   213	  9118	     window (voca.css - vocamx - Visual Studio Code)
    0	    89	  9285	       extensionHost
    0	    66	  9626	         /usr/share/code/code /usr/share/code/resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=9285
    0	     4	  9303	       /bin/bash
    0	   112	  9402	       watcherService
    1	   101	 25765	     window (Issue Reporter)
    1	   108	  2774	   gpu-process
    0	     0	 25985	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 25986	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (voca.css - vocamx - Visual Studio Code)
|    Folder (vocamx): 16138 files
|      File types: js(5905) php(5145) png(1258) css(620) md(415) html(283)
|                  jpg(283) txt(247) phpt(243) yml(209)
|      Conf files: package.json(12) makefile(6) grunt.js(4)
|                  webpack.config.js(2);
```

</details>
Extensions: none

**Comment by rebornix** [comment]
Could you please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to help troubleshoot?

**Comment by jrieken** [comment]
The information you have attached doesn't show high memory usage. Please attach process info that do show this, please attach repro steps, like a repo in which this happens
