### ISSUE TITLE
Searching files results in searchService CPU remaining at 100%

### ISSUE THREAD

**Issue by JohnRiv** [Microsoft/vscode#63990]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Search all files in the project for a search term (seems to occur on larger projects rather than small ones)

Expected Results:
- Search results return and the blue progress indicator animation stops

Actual Results:
- Search results return but the progress indicator never stops and searchService hits 100% CPU and stays there

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
lit-html|bie|1.10.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
typewriter|dan|1.0.1
vscode-eslint|dba|1.7.0
githistory|don|0.4.4
gitlens|eam|8.5.6
flow-for-vscode|flo|0.8.5
python|ms-|2018.10.1
polymer-ide|pol|0.6.0
vscode-icons|rob|7.28.0
code-spell-checker|str|1.6.10

</details>

**Comment by roblourens** [comment]
Is this text search or quick open (cmd+p)? Does it ever complete if you leave it for a minute?

Does it happen every time with the same search term

**Comment by JohnRiv** [comment]
Thanks for the quick response... I was able to address this but excluding a couple directories that had some large (30MB) text files
