### ISSUE TITLE
Cannot use backspace or enter after first opening markdown file

### ISSUE THREAD

**Issue by HolisticDeveloper** [Microsoft/vscode#63995]
Issue Type: <b>Bug</b>

When first opening a markdown file or changing the languague mode to markdown, the editor does not respond to the backspace and enter keys. This is correlated to seeing the "Activating Extensions" message in the status bar. Sometimes this activation takes several seconds (10+) to complete.

Repro steps:
1. Open VS Code.
2. Open an existing markdown file.
3. Immediately try to use the enter key or backspace key.

Actual results:
The enter key and backspace keys have no effect. Two small warnings are displayed in the lower right hand corner that state:
command 'markdown.extension.onEnterKey' not found
command 'markdown.extension.onBackspaceKey' not found

Expected results:
Basic keyboard commands like enter and backspace should always work.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.21.0
json-escaper|jos|1.1.0
mssql|ms-|1.4.0
python|ms-|2018.10.1
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.1005
markdown-preview-enhanced|shd|0.3.11
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.6.10
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.7.0
cursorCharCode|zei|0.1.1

</details>

**Comment by mjbvz** [comment]
This is caused by one of your markdown extensions, likely markdown-all-in-one. Please file the issue against them

**Comment by HolisticDeveloper** [comment]
Thanks!

Reference:
https://github.com/neilsustc/vscode-markdown/issues/335
