### ISSUE TITLE
Why wasn't VSCode 1.1.1 tagged?

### ISSUE THREAD

**Issue by fusion809** [Microsoft/vscode#6399]
Hi,

As I maintain a cross-distribution [Linux installer for VSCode](https://github.com/fusion809/VScode-installer) that compiles VSCode from source, depending on user inputs, I was wondering why I am hearing of a 1.1.1 release of VSCode yet not seeing this new release being tagged. 

Thanks for your time,
Brenton

**Comment by Tyriar** [comment]
I don't think tagging has been solidified in our release process yet. @joaomoreno normally handles this but he's out atm so I just added the tag.
