### ISSUE TITLE
French translation wrong when no folder is added to workspace

### ISSUE THREAD

**Issue by JulienGS25** [Microsoft/vscode#63993]
- VSCode Version: 1.29.1
- OS Version: Win10 Pro

Steps to Reproduce:

1. Set VSCode to French
2. Have no folder in the workspace

Actual sentence:
Vous n'avez pas encore **ajouter** un dossier à l'espace de travail.
Should be:
Vous n'avez pas encore **ajouté** un dossier à l'espace de travail.

![image](https://user-images.githubusercontent.com/37316563/49234797-b6c15d80-f3c6-11e8-9ac8-1afde08f643e.png)

**Comment by shawndon** [comment]
We should fix this. Adding Jan for bug triage.

**Comment by lukaschal** [comment]
On review.

SRC: You have not yet added a folder to the workspace.
TGT: Vous n'avez pas encore ajouter un dossier à l'espace de travail.

**Comment by lukaschal** [comment]
Fixed.

New TGT: Vous n'avez pas encore ajouté un dossier à l'espace de travail.
