### ISSUE TITLE
Python extension - has a hang up with f-strings and print()

### ISSUE THREAD

**Issue by kbuchsicf** [Microsoft/vscode#63996]
- VSCode Version: 1.26.0-insiders
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Type in the editor: print(f'   - that is, beginning an f-string in print function call
2. I have the VS Code feature to insert pair quotes enabled, but that quote is not doubled.
3. Further, after I type the contents of the f-string and come to close the quote, a pair of quotes are inserted. You can't delete the first one (easy backspace) or both are deleted. So, I have to fight the editor and it adds an extra step.

**Comment by rebornix** [comment]
@kbuchsicf I'll suggest filing issues against the python extension you are using ;)

**Comment by kbuchsicf** [comment]
Since it is a Microsoft Python extension, maintained in this Git repo, I thought you would want the issue here.
