### ISSUE TITLE
Rounded selection seems broken due to current word highlight

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#64]
editor.roundedSelection is broken

- If our selection doesn't span multiple lines, the selection is still squared.

![snip_20151118224023](https://cloud.githubusercontent.com/assets/10473142/11248132/85ecf492-8e45-11e5-9faa-45626737db89.png)
![snip_20151118224059](https://cloud.githubusercontent.com/assets/10473142/11248133/88d891a2-8e45-11e5-98ab-fb87d1278a19.png)

**Comment by alexandrudima** [comment]
@hashhar I cannot reproduce under windows:

![image](https://cloud.githubusercontent.com/assets/5047891/11393184/714ac5aa-935e-11e5-91d2-6f6819319603.png)

Are you using a specific font or a specific OS?

**Comment by hashhar** [comment]
Upon revisiting this I decided to check again and this time I was able to notice that the reason why the selection seems not rounded is because it gets highlighted twice (once for the selection and the other for the feature where the same text if found anywhere in the file is also highlighted) and then it feels like it's by design.
The wrong one....
![screenshot 42](https://cloud.githubusercontent.com/assets/10473142/11450581/58198b2e-95cb-11e5-9059-491810796732.png)
The one where it gets fixed after I extend my selection....
![screenshot 43](https://cloud.githubusercontent.com/assets/10473142/11450582/5e449390-95cb-11e5-85e1-e0a97b9ed477.png)

**Comment by hashhar** [comment]
I'm using Windows 10 Home November Update. No custom font, no display scaling and the font size is also set to default.

**Comment by alexandrudima** [comment]
@hashhar Thank you for the additional details
