### ISSUE TITLE
Toggle Line Comment on German Keyboard.

### ISSUE THREAD

**Issue by cebor** [Microsoft/vscode#640]
Toggle Line Comment does not work on a german Keyboard on OSX  (CMD + /)

**Comment by mafredri** [comment]
Same here with a scandinavian keyboard. The key combo is `Cmd+Shift+7` which is essentially `Cmd+/`.

**Comment by mafredri** [comment]
I can actually work around this issue by defining the following key binding.

```json
[
    { "key": "shift+cmd+/", "command": "editor.action.commentLine",
                               "when": "editorTextFocus"}
]
```

**Comment by alexandrudima** [comment]
@cebor @mafredri 

On my Swiss German keyboard (laptop), the `/` appears on top of `7` so I use:
```json
{  "key": "ctrl+7", "command": "editor.action.commentLine", "when": "editorTextFocus" 	}
```

Please see #713 for a detailed explanation and I'd like to invite you to help us figure out together good defaults for non-US standard keyboard layouts... possibly in the form of a VSCode extension.
