### ISSUE TITLE
Auto Indent HTML lost capitalized attributes of Angular

### ISSUE THREAD

**Issue by filipemansano** [microsoft/vscode#64009]
Version Detail

> Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

When using auto indentation (pressed Alt+Shift+F) in html, vscode lost capitalized words

eg. 
*ngIf become *ngif
*ngFor become *ngfor
routerLink become routerlink

![iliooi](https://user-images.githubusercontent.com/6247393/49242805-cfe00380-f3f2-11e8-8623-30c171aa0f29.gif)

this causes an error in the application

![capturar](https://user-images.githubusercontent.com/6247393/49242845-eb4b0e80-f3f2-11e8-9475-95d3ed0c0f2d.PNG)

**Comment by rebornix** [comment]
It's very likely caused by a formatter (alt+shift+f formats document) and should be fine when running vs code without any extension enabled.
