### ISSUE TITLE
view/item/context command argument sometimes is undefined

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#64017]
Issue Type: <b>Bug</b>

Our extension registers a command for `view/item/context`, and sometimes, when a user invokes this command on the viewlet, the command argument VSCode passes us is `undefined`, when we always expect an instance of `vscode.TreeViewItem` where the command was invoked on. 

I could not reproduce it locally. But we keep getting bug reports from the users.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
> when we always expect an instance of vscode.TreeViewItem where the command was invoked on.

That's a false assumption. Commands are publicly available to anyone, another extension can execute commands, users can bind keybindings to it etc etc. You must also check the arguments a command is being called with.

Forwarding to @sandy081 to check if there is something wrong when clicking a tree node

**Comment by sandy081** [comment]
I do not see anything wrong in the code while invoking tree item actions. Please check if somebody is invoking the command by associating a key binding as @jrieken said?

**Comment by IlyaBiryukov** [comment]
The command is disabled on the palette, is this sufficient to block key binding to it?

**Comment by IlyaBiryukov** [comment]
Ok, then I guess we should handle the command without parameters and ask users what they want to apply the command to.
