### ISSUE TITLE
Manually Label New Windows 

### ISSUE THREAD

**Issue by bmess** [Microsoft/vscode#64019]
As a regular user of VSCode I would love the ability to manually label windows. 

## Use case:  
I have a working window with a series of directories and all sorts of tabs. Let's say I'm developing a large application.

I open a new window as a scratch pad for something I want to remember that's outside of the context of the development.

A coworker asks for help on a project.  I open a 3rd window and open the working directory to begin helping them.

Given 3 windows now all named VSCode it would be easier to distinguish them in my desktop if they were labeled something specific.

## Current State
Right now each window displays the current opened file

**Comment by bpasero** [comment]
`window.title` can be used to change the title. Since you can store it as a workspace setting, you can have a prefix per window.

**Comment by bmess** [comment]
Thanks! This is a nice feature
