### ISSUE TITLE
bump to electron v1.1.0

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#6401]
https://github.com/electron/electron/releases

**Comment by bpasero** [comment]
We always update electron to newer versions over time, but since 1.1.0 comes with a major Chrome/node.js update, we will likely skip the update for this sprint and look at this the next sprint.

**Comment by Lichtjaeger** [comment]
Please keep your `package.json` in this repository up to date.
I want to know what ESnext features are usable but in the package is written:
```
{
  "electronVersion": "0.37.6",
  "engines": {
    "node": ">= 0.10.0 < 0.11.0"
  }
}
```

**Comment by bpasero** [comment]
I am not sure why we have this engines declaration. @joaomoreno any clue?

**Comment by joaomoreno** [comment]
No one knows. Nothing really uses it.

**Comment by bpasero** [comment]
I took out the engines declaration, lets see what breaks ;)
