### ISSUE TITLE
Comments are low contrast in diffs on Monokai theme

### ISSUE THREAD

**Issue by nyalex** [microsoft/vscode#64013]
- VSCode Version: 1.29.1
- OS Version: macOS Mojave 10.14

Steps to Reproduce:

1. Download the Github Pull Request plugin
2. Go into "Github Pull Requests" panel and double click a pull request.
3. Open one of the changes files and navigate where the diff shows changes (look for the green lines).
4. You'll then notice that comments are hard to see. Screenshot: 

![app 2018-11-26 17-25-12](https://user-images.githubusercontent.com/734910/49045878-5355e680-f1a0-11e8-91fb-10db31784924.png)

Does this issue occur when all extensions are disabled?: No

**Comment by RMacfarlane** [comment]
Thanks! I'm able to see this using the Monokai theme. This looks like an issue with the theme itself.

**Comment by KaeLL** [comment]
Same thing here
https://github.com/Microsoft/vscode-cpptools/issues/3091
