### ISSUE TITLE
Replace doesn't insert captures when finding multible lines

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/vscode#64028]
Issue Type: <b>Bug</b>

If you search in files for regular expressions with capture it doesn't work when matching multible lines.

Example:
find = (x),[\n\s]*(y);
replace = $2 - $1

will change: "x, y;" to: "y - x", so this works.
but it will change:
"x,
y;"
to:
"$2 - $1". This is literally "$1" and "$2".

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|0.0.9
al-toolbox|Bar|0.0.9
todo-tree|Gru|0.0.107
al|Mic|2.0.43900
al|ms-|2.0.56865
team|ms-|1.144.1
al-formatter|ras|3.0.0
al-var-helper|ras|2.0.0
crs-al-language-extension|wal|1.0.8

</details>

**Comment by doughsay** [comment]
I just ran into needing this and was really bummed out that I can't use vscode to do this.  I need to find and replace something across almost 1300 files using a multiline regular expression. I guess I need to use find + sed?

**Comment by rebornix** [comment]
It's already working in latest VS Code now.
