### ISSUE TITLE
Git: All changes are Committed, even if some are unselected

### ISSUE THREAD

**Issue by hughanderson4** [Microsoft/vscode#64029]
Issue Type: <b>Bug</b>

In Source Control: Git tab, I have a changes in 12 files.
I select 10 out of 12 files (with ctrl+click), enter a Commit message, and press Commit command.

Observed: all 12 changes are commited
Expected: only the 10 selected changes should be committed

Use case: I worked on 2 different issues and I want to commit them separately, with 2 separate Commit messages.  First commit is 10 files and second commit is remaining 2 files.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (5.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.11.1

</details>

**Comment by joaomoreno** [comment]
Unfortunately, selecting + committing doesn't do anything. After selecting, you must stage them by clicking on any of the `+` (Stage) inline actions. Once staged, only those changes will be committed.
