### ISSUE TITLE
Composer update in git bash is all messy

### ISSUE THREAD

**Issue by buttflattery** [Microsoft/vscode#64020]
- VSCode Version:1.29.1
- OS Version: windows 10

Steps to Reproduce:

1. open vs code from the start menu
2. browse the project folder
3. press CTRL+` To open terminal 
4. type `composer update` and it displays the text as follows

![image](https://user-images.githubusercontent.com/1536454/49247094-47845180-f438-11e8-97e7-2fcc7f657757.png)

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
