### ISSUE TITLE
Find and Replace unnecessarily uses different colors than Search

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6402]
While this could be considered a feature, the main time it would be useful is in searching minified files which is a pretty uncommon use case. I find it to be an annoyance when moving through the search terms to land on the same line multiple times.

Steps to Reproduce:

1. Create file with "foo" in a line multiple times
2. Find in files "foo"
3. Observe it's shown multiple times

![image](https://cloud.githubusercontent.com/assets/2193314/15302066/d8dbe3ae-1b65-11e6-95c3-f5aeaa275dda.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15302073/e43ae6dc-1b65-11e6-9d17-2f6dc596cbdf.png)

**Comment by jrieken** [comment]
adding @stevencl for more insights.

The behaviour is designed like that the reasoning is that it's otherwise harder to correlate the number we show in the group with the children and easy to miss the 2nd, 3rd, etc match in a file

**Comment by stevencl** [comment]
I think it's important to show all of the results, even when there are multiple on the same line. One of the results for example could be scrolled out of view if it's on a very long line. If we didn't have a separate result for this, it could easily be overlooked.

One thing we could consider doing to improve the experience would be to improve the way we highlight the selected result. When looking at the editor it's hard to see which result is highlighted:

![image](https://cloud.githubusercontent.com/assets/1704059/15324957/7f076944-1c40-11e6-99e8-71ccf38e56e0.png)

**Comment by jrieken** [comment]
@stevencl @bgashler1 Do you have suggestion for a stranger color? Iff so I could make the change this month.

**Comment by stevencl** [comment]
@bgashler1 - could you suggest a stronger colour to better indicate which search result is being highlighted in the editor? For example, in the above screenshot the last instance of foo on line 3 is highlighted in the editor, corresponding to the selected search result. We would need colours for the different themes I imagine.

**Comment by stevencl** [comment]
@bgashler1 - would be great if you could get this soon so that @jrieken can make this change before the end of the month.

**Comment by jrieken** [comment]
I am afraid it's too late already

**Comment by stevencl** [comment]
No worries. Let's get it done for June then

**Comment by jrieken** [comment]
@bgashler1 ping

**Comment by bgashler1** [comment]
@jrieken 

Is there a reason why we shouldn't extend the local Find/Replace colors here?  Find/Replace differentiates what is a match versus what is both a match and currently selected.

Below I'm searching for `foo`, but the Find/Replace for `bar` is much more clear as to what I'm on.
![image](https://cloud.githubusercontent.com/assets/11839736/15693070/43f0f7f0-2747-11e6-9fbf-e533f8427c75.png)

If you have no objection, this seems like a good approach to me.

**Comment by jrieken** [comment]
I didn't define any of the colours. I remember a time when they were aligned, but I don't know why they changed

**Comment by jrieken** [comment]
Assigning @sandy081 since he own the search viewlet

**Comment by bgashler1** [comment]
@sandy081 here are the things that need to be changed...

We need to add the `currentFindMatch` class to whatever is selected in the Search viewlet.  See example below where I did it in the Chrome DevTools.  You'll notice the last result is selected and I'm applying that class to its overlay (it's visible on the bottom left-hand corner of the editor).  This makes Search more consistent with how the Find/Replace widget behaves.
<img width="1440" alt="screen shot 2016-07-22 at 12 51 15 pm" src="https://cloud.githubusercontent.com/assets/11839736/17069349/0e2b25ae-500b-11e6-8630-958071edf100.png">

**Comment by bgashler1** [comment]
Since this is a programmatic change, I'll remove my assignment and let you handle it sicne you own this area.  But if you need any help, please let me know.

**Comment by chrmarti** [comment]
There are still many differences in the latest insiders build (6ef86d5f, 2016-07-28T07:11:34.347Z).

Local search:
![localsearch](https://cloud.githubusercontent.com/assets/9205389/17222691/73127592-54ae-11e6-997a-5d221ff45a76.png)

Global search:
![globalsearch](https://cloud.githubusercontent.com/assets/9205389/17222721/9a54f7a6-54ae-11e6-90e4-e58d88a44396.png)

**Comment by sandy081** [comment]
@chrmarti Thanks for noticing. But, It would be helpful to provide a description of those differences you found with steps. 

Also I should be clear here on what to verify. I think scope of fix/verification for this item is this [comment](https://github.com/Microsoft/vscode/issues/6402#issuecomment-234641128) :
- Verify that current find match has same color representation in Find vs Search.

I would suggest to please open a new issue for the differences you observed.
Thanks.

**Comment by chrmarti** [comment]
Ack, this is only about the _current_ match, I wasn't specific enough in my verification.
