### ISSUE TITLE
Should be able to search for \r in editor find

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64021]
- Have file with CRLF line endings
- Search for `foo\n` as regex
- Get match ✔️ this is ok, people want to search in their editor without thinking about line endings, and we shouldn't change this, it could confuse people
- Search for `foo\r\n` as regex
- No match 🐛 but it should match, because some people want to specify the \r, and since it works in text search, we should be consistent.

As discussed, this is now possible to support with the editor buffer changes

**Comment by rebornix** [comment]
I just figured out that we already have an issue for this one https://github.com/Microsoft/vscode/issues/31449
