### ISSUE TITLE
Latest update is churning too much CPU

### ISSUE THREAD

**Issue by BYUDigger** [Microsoft/vscode#64024]
Issue Type: <b>Bug</b>

Launch VS Code with a normal project that did not churn CPU before the last update. It now puts my CPU aboe 50%

When I kill the offending process in Task Manager it says "Extension host terminated unexpectedly". Looks like something wrong with the Extentsion host.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mocha-test-runner|cst|0.3.3
vscode-whitespacer|dee|1.0.0
githistory|don|0.4.4
vs-code-xml-format|fab|0.1.5
dotnet-test-explorer|for|0.6.0
python|ms-|2018.10.1
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.1005
vscode-docker|Pet|0.4.0
tsimporter|pmn|1.2.14
trailing-spaces|sha|0.2.11

</details>

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance issues.
