### ISSUE TITLE
ripgrep (rg.exe) downloading all my offline files from onedrive

### ISSUE THREAD

**Issue by GZidar** [Microsoft/vscode#64025]
- VSCode Version: 1.29
- OS Version: Windows 10 (1809)

Steps to Reproduce:

1. Open VS Code

Does this issue occur when all extensions are disabled?: Yes

Since updating to the latest version of VSCode I have started getting a notification that rg.exe is downloading files from OneDrive. The result is that all my offline files try to get downloaded and this results in my HDD running out of space.

The first time it happened I marked the files as offline only (using clear space) and the files were deleted from the local PC, but then the issue happened again the next time I opened VSCode. I did a search through the computer file system and the only instance of rg.exe on my machine is the one bundled with VSCode. 

I have now uninstalled the app to keep the problem from coming back.

I can only assume that ripgrep is traversing the local file system for some reason and attempting to open all the files which will trigger the download of offline files. I cannot imagine why VS Code would need/want to search through the entire file system.

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

I fixed an issue which may prevent file searches from triggering this behavior in onedrive.

However, text search will still trigger this. I believe it's possible to disable autodownloading in OneDrive or block rg.exe from triggering it.

**Comment by roblourens** [comment]
It shouldn't leave the workspace folder (unless you have enabled `search.followSymlinks` and it leaves via symlink or something), but I don't know what onedrive's logic for auto downloading is.

**Comment by GZidar** [comment]
@roblourens I have installed the insider version of VSCode, and been using it for a couple of days and I have not seen the problem occur. It is still very strange to me that it did what it did because I don't believe that I have any onedrive folders open in VSCode. In any case, this version seems to be behaving itself. I will let you know if it happens again in the next few days.

**Comment by roblourens** [comment]
Sounds good, thanks!
