### ISSUE TITLE
Git: When resolving a merge conflict allow accepting the default commit message

### ISSUE THREAD

**Issue by mohsen1** [microsoft/vscode#6403]
- VSCode Version: 1.1.1
- OS Version: OS X

Steps to Reproduce:
1. get into a merge conflict 
2. Try accepting Git's default message. It's equal to `git commit --no-edit`
3. There is no way to do that!

**Comment by suan** [comment]
Will mention that it's also equivalent to `git commit` and saving the default message that shows up in your editor - hence a very common workflow

**Comment by borekb** [comment]
My workaround is to invoke `git commit` from a terminal. Maybe if the commit message field is empty, VSCode could just call `git commit` as well and leave it up to user's configuration what happens (in my case, it would open a text editor from my `EDITOR` system variable, which is fine).

**Comment by cbryan-risklens** [comment]
Has the pull request #66522 been reviewed yet?  Can it be pulled in?

**Comment by joaomoreno** [comment]
**Verification:**

When having a merge commit, VS Code should now automatically populate the input box with the default git merge commit message, so the user can just accept it.
