### ISSUE TITLE
CTRL+END in debug console

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#64037]
Can you implement the CTRL navigation keys in the DEBUG CONSOL and TERMINAL windows?  CTRL+END to jump to the bottom would be particularly helpful, thanks.

**Comment by isidorn** [comment]
@joaomoreno Do we have this navigation in the tree?
I can not check since I do not have an END key on my keyboard.

Assigning also to @Tyriar for terminal

**Comment by Tyriar** [comment]
The terminal has commands available some of which have default bindings on some OS's (taking care not to break keys that may be used for terminal apps):

<img width="599" alt="screen shot 2018-11-30 at 10 42 22 am" src="https://user-images.githubusercontent.com/2193314/49308318-ca36fc00-f48c-11e8-80c6-2592f2d2399a.png">

**Comment by joaomoreno** [comment]
@isidorn <kbd>End</kbd> is <kbd>Fn RightArrow</kbd> in your keyboard.

What navigation do you need?

**Comment by isidorn** [comment]
@lovettchris in debug console, shift + tab to focus the output and than just click End will take you to the end.
@Tyriar already gave the command for the terminal, and that one should be customisable.
So i think we are good here, closing
