### ISSUE TITLE
Backticks render as diacritical marks in editor

### ISSUE THREAD

**Issue by cblichmann** [Microsoft/vscode#64034]
Issue Type: <b>Bug</b>

Create an ASCII text file containing backtick characters in order to have them render as code in Markdown.
See below, on relative line 6, the intended representation is `tasks.json`:
![screenshot from 2018-11-29 23-03-43](https://user-images.githubusercontent.com/213059/49255013-18b3ae80-f42b-11e8-9811-7cd520298dbc.png)

The preview renders this correctly, but the editor is always combining the backtick into diacritical marks (see lines number 4 2 and 12).

While I'm normally using the US INTL keyboard (which has dead keys), this issue happens regardless of keyboard layout (I made sure I run with a plain US one and rebooted).
I am using the latest Insiders build, but I believe this issue was also present in earlier builds.
My system has `libfreetype6:amd64` version 2.8.1-2 from Debian testing (don't know if relevant).

VS Code version: Code - Insiders 1.30.0-insider (cd5b4d1bb3fc7e509fba077095b2b280b8ff7161, 2018-11-29T06:14:29.935Z)
OS version: Linux x64 4.16.0-1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2126)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.70GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.21.0
vscode-markdownlint|Dav|0.21.0
cpptools|ms-|0.20.1
Go|ms-|0.7.0
vscode-docker|Pet|0.4.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
It would be great if you can share the content and more details about how to reproduce this issue. I can't reproduce it. BTW, if you are using US INTL keyboard layout, and then pressing backtick and e will always generate è .
