### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by edgaraljuri83** [Microsoft/vscode#64045]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by edgaraljuri83** [comment]
Issue Type: <b>Performance Issue</b>

very slow cpu

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.41GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   109	 12268	code main
    0	   397	  2120	   window (main.yml - automation-scripts - Visual Studio Code [Administrador])
    0	    11	  1704	     electron-crash-reporter
    0	    13	  7668	     watcherService 
    0	     5	 11304	       console-window-host (Windows internal process)
    0	   233	 11624	     extensionHost
    0	    92	  9748	       electron_node server.js 
    0	    25	 11576	       electron_node server.js 
    0	    14	 13600	       "C:\Program Files (x86)\Java\jdk1.8.0_181/bin/java" -jar c:\Users\ebermudez\.vscode\extensions\ibm.xmllanguagesupport-0.0.1\server\ibm-xml-server-all.jar
    0	     5	 10116	         console-window-host (Windows internal process)
    0	    58	 14112	       electron_node server.js 
    0	    75	 14468	       electron_node server.js 
    0	    43	 14608	       electron_node server.js 
    0	    24	 15164	       C:\VSCode\Code.exe c:\VSCode\resources\app\extensions\json-language-features\server\dist\jsonServerMain --node-ipc --clientProcessId=11624
    0	     9	 12580	     winpty-process
    0	     7	  3376	       C:\WINDOWS\system32\cmd.exe /c C:\cygwin\Cygwin.bat
    0	     9	 12768	         bash  --login -i
    0	     9	 11072	       console-window-host (Windows internal process)
    0	    39	 16512	     searchService
    1	   207	  2164	   gpu-process
    0	    75	  6208	   shared-process
    2	    77	 10560	   window (Reportero de tema)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.yml - automation-scripts - Visual Studio Code [Administrador])
|    Folder (automation-scripts): 1568 files
|      File types: yml(246) csv(182) js(148) sh(146) properties(63) xml(61)
|                  gz(53) j2(51) txt(51) conf(31)
|      Conf files: package.json(3) launch.json(1) settings.json(1) grunt.js(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (99)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-caniuse|aga|0.5.0
Bookmarks|ale|10.0.0
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.10
vscode-color|ans|0.4.5
orclapex-autocomplete|apn|0.0.3
shell-snippets|cds|0.1.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
yaml-key-viewer|cyb|0.1.0
angular-schematics|cyr|1.10.0
whitespace-plus|dav|0.0.5
vscode-eslint|dba|1.7.0
angular-extension-pack|dog|6.5.6
bower|don|0.0.3
git-extension-pack|don|0.1.3
githistory|don|0.4.4
jquerysnippets|don|0.0.1
xml|Dot|2.3.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
RunOnSave|eme|0.0.18
LogFileHighlighter|emi|2.4.2
pull-request-monitor|eri|1.7.1
vscode-toggle-column-selection|eri|1.0.3
prettier-vscode|esb|1.7.2
unixtime-converter|esp|0.0.2
vscode-diff|fab|1.3.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.7
githd|hui|2.1.0
rest-client|hum|0.20.3
output-colorizer|IBM|0.1.2
XMLLanguageSupport|IBM|0.0.1
angular2-switcher|inf|0.2.0
java-properties|ith|0.0.2
search-node-modules|jas|1.3.0
vscode-pigments|jas|1.0.2
autofilename|Jer|0.1.3
diff-tool|jin|0.0.1
docthis|joe|0.7.1
vscode-gutter-preview|kis|0.16.4
vscode-github|Kni|0.30.1
refactorix|kri|0.3.6
bash-ide-vscode|mad|1.3.3
select-highlight-minimap|mde|0.0.8
rainbow-csv|mec|0.8.0
vscode-language-babel|mgm|0.0.21
Angular-BeastCode|Mik|7.0.18
ecdc|mit|0.12.0
vscode-language-pack-es|MS-|1.29.2
cpptools|ms-|0.20.1
typescript-javascript-grammar|ms-|0.0.47
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
vscode-extension-auto-import|Nuc|1.4.3
quicktype|qui|12.0.46
vscode-yaml|red|0.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.3.1
vscode-icons|rob|7.28.0
sass-indented|rob|1.4.9
bash-debug|rog|0.3.3
vscode-ansible-linter|rup|0.11.0
edit-with-shell|ryu|1.0.1
partial-diff|ryu|1.4.0
text-marker|ryu|1.9.0
vscode-sql-beautify|sen|0.0.4
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.2.2
trailing-spaces|sha|0.2.11
sonarlint-vscode|Son|1.5.0
javascript-typescript|sou|0.0.7
code-spell-checker|str|1.6.10
move-ts|str|1.11.3
open-in-browser|tec|2.0.0
sort-lines|Tyr|1.7.0
terminal-tabs|Tyr|0.2.0
vscode-arduino|vsc|0.2.23
project-manager|ale|8.0.0
vscode-ansible|vsc|0.5.2
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.1
plsql-language|xyz|1.6.4
markdown-all-in-one|yzh|1.7.0
html-css-class-completion|Zig|1.17.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@edgaraljuri83 the log shows none of VSCode processes is using too much CPU. Can you provide more info about how to reproduce?
