### ISSUE TITLE
使用经常出现插件无发使用

### ISSUE THREAD

**Issue by zeroone2005** [Microsoft/vscode#64043]
使用经常出现插件无发使用，状态栏显示 正在激活插件 然后没什么效果。需要重写打开vscode才能使用，有时候过一阵又不能使用了。又需要关闭重写打开。
windows家庭中文版本  1803

**Comment by rebornix** [comment]
@zeroone2005 please provide more information about how to reproduce this issue and probably screenshots or gifs to help troubleshoot.
