### ISSUE TITLE
Disabling members of an extension pack.

### ISSUE THREAD

**Issue by grbd** [Microsoft/vscode#64044]
I've noticed that when installing / enabling the "Python Extension Pack"
when searching extensions via category:"Extension Packs"
Then disabling the same extension pack
The member extensions such as "Visual Studio Intellicode" or "Python" or others are not disabled

I think others have mentioned this before and there seems to be an auto close duplication message / point towards issues #14440 / #16666

However those issues are currently closed
So maybe this should be classed as a feature request for a change in behaviour

The way I see this working for packs as an example

## Method 1

  * Right Click "Disable member extensions" menu entry for extension packs.
    Member extension is only disabled if it's not a dependency of an extension outside of the pack.

## Method 2

1.  When enabling an individual extension, this is added to the active configuration list.
2.  When enabling an extension pack, the extension pack is added to the active configuration list but not the individual extensions.
    a lump of code picks up that the members are active based on the pack being active.

3.  When disabling an extension pack
    extension pack is removed from the active list.
    if a member was not directly listed in the active list (in other words added via the pack) it's then classed as deactivated since the pack is deactivated.
    If a member was already added to the active list before the pack was activated or as part of a dependency then it's left alone / still active regardless.

**Comment by sandy081** [comment]
@grbd Its because Python Extension Pack is not defined correctly. It should use `extensionPack` instead of `dependencies`. Please file an issue against the pack to define it using `extensionPack` property
