### ISSUE TITLE
Screen starts blinking 

### ISSUE THREAD

**Issue by Yuvrender-Gill** [Microsoft/vscode#64047]
Issue Type: <b>Bug</b>

Screen starts blinking while suing on new ASUS Zenbook S

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (10.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
c-cpp-compile-run|dan|0.4.3
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
code-runner|for|0.9.5
gc-excelviewer|Gra|2.1.26
rest-client|hum|0.20.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.11.0
azure-account|ms-|0.6.2
cpptools|ms-|0.20.1
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
java|red|0.34.0
vscode-yaml|red|0.1.0
javascript-typescript|sou|0.0.7
code-spell-checker|str|1.6.10

</details>

**Comment by Yuvrender-Gill** [comment]
So when I started the VS Code and whenever I would start clicking anywhere (assuming VS Code is the only application on the screen) it would start blinking. Then to get rid of that I need to sign out of the window. 
It got automatically fixed when I changed my resolution settings. I think VS Code doesn't adjust automatically with changed resolution.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
