### ISSUE TITLE
Zooming opens "tasks" section of output panel when problemMatcher can't be found

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64040]
Issue Type: <b>Bug</b>

**Repo**
1. In vscode codebase
1. With all tslint extensions disabled
1. Close panel
1. Zoom in or out

**Bug**
`Tasks` section of output panel opens on zoom.

I see the following in the tasks panel:

```
Error: Invalid problemMatcher reference: $tslint5
```

VS Code version: Code - Insiders 1.30.0-insider (cd5b4d1bb3fc7e509fba077095b2b280b8ff7161, 2018-11-29T06:12:26.485Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by cleidigh** [comment]
I just saw this myself with:
* master                                 2c2ae49145 Merge pull request #64010 from Microsoft/rebornix/commentsgrouping

The error occurs right on opening OSS.
I can also reproduce the error if any changes made within the settings editor.  FWIW

**Comment by jrieken** [comment]
>  is zoom supposed to trigger the eventually lifecycle phase?

Hm, that would be weird... @isidorn knows more about the panel and how it interacts with zooming

**Comment by isidorn** [comment]
I would forward this question to zoommaster @bpasero 
I think it might be other way around, that zooming is triggered only once Evanutally phase is hit.

**Comment by alexr00** [comment]
Actually, zoom is not causing the Eventually phase. Zooming is causing the output panel to open again though.

**Comment by bpasero** [comment]
🔮

**Comment by cleidigh** [comment]
Repeating my comment above for clarity:

Besides this happening on code-open as @roblourens  states, it ALSO happens every time a setting is changed in the new settings editor.  Hopefully the information is helpful...

**Comment by alexr00** [comment]
We have two problems here:
- Tasks it writing this to output and no one likes that. I'm looking for a better place to write this.
- The output panel re-opens at unexpected times, like zoom and settings change. @bpasero, do you know why this could be?

**Comment by bpasero** [comment]
I am seeing this as well, and the panel seems to be opened from `computeWorkspaceFolderTasks` because we found errors. Can we reconsider this for November or does it only happen when running out of sources?

//cc @dbaeumer who added this code to open the panel in the first place

**Comment by dbaeumer** [comment]
Errors that occur through parsing the `tasks.json` file where always printed to the output panel. Things we could change: 

- make diagnostics instead
- Show the output panel only if an error occurs and the user actually runs the task that has the error.

**Comment by bpasero** [comment]
> Show the output panel only if an error occurs and the user actually runs the task that has the error.

Yes please.

**Comment by alexr00** [comment]
It looks straight forward, I can fix it for November.
