### ISSUE TITLE
Comment UI in editor not updated properly after firing change event

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#64042]
Issue Type: <b>Bug</b>

When `DocumentCommentProvider.onDidChangeCommentThreads` event fires with `{ changed: [changed_comment_thread] }` and the change is a removal of a comment from the thread, the comment thread UI is not updated properly in the editor. 

Like for example in this scenario:
1. There is a comment thread with two comments, A and B (has "Reply" text)
1. `DocumentContenProvider.onDidChangeCommentThreads` event fires, it contains the changed thread with only comment B (comment A was deleted).
1. The comment UI in the editor shows that there are two comments B now in the thread. It is expected to show only one.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IlyaBiryukov** [comment]
Here is the data used for `changed_comment_thread`:
```
Object {threadId: "1", resource: t, range: e, comments: Array(1)}
  comments:Array(1) [Object]
    length:1
    0: Object {commentId: "1:1", body: e, userName: "Ilya Biryukov", …}
        range:e {_start: e, _end: e}
           _end:e {_line: 749, _character: 0}
           _start:e {_line: 749, _character: 0}
           end:e
           isEmpty:true
           isSingleLine:true
           start:e
    resource:t {scheme: "vsls", authority: "", path: "/src/repository.ts", …}
       _formatted:"vsls:/src/repository.ts"
       _fsPath:null
       authority:""
       fragment:""
       fsPath:"\src\repository.ts"
       path:"/src/repository.ts"
       query:""
       scheme:"vsls"
    threadId:"1"
```

That's how UI looks after the event fires. Highlighted is the unexpected duplicated reply in place of deleted comment:
![image](https://user-images.githubusercontent.com/15989459/49835763-16b7ec80-fd55-11e8-906f-54d80addb888.png)

**Comment by IlyaBiryukov** [comment]
Fix is in [this PR](https://github.com/Microsoft/vscode/pull/64906).

**Comment by rebornix** [comment]
Close this one as it's already out of date.
