### ISSUE TITLE
bug with turning

### ISSUE THREAD

**Issue by t3946** [Microsoft/vscode#64046]
I have small problem with turning. Please fix this bug.
https://prnt.sc/loryfo

**Comment by t3946** [comment]
No, i want my break don't turning, this wrong. Breakes is not part of code block. It's separate part and it need me when i turning code. I mean it 
![download](https://user-images.githubusercontent.com/26932760/49299841-c083b780-f4d1-11e8-9cdb-072f6b616f4a.png)

**Comment by octref** [comment]
Can you give a reproducible case? Paste your code here.
