### ISSUE TITLE
Preserve all view state when saving untitled file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#64056]
- VSCode Version: 1.30.0-insider
- OS Version: macOS

Steps to Reproduce:

1. Create new untitled file, enable word wrap (via command palette) write a line long enough to wrap
2. Save the file to disk

Line wrapping is lost

**Comment by alexandrudima** [comment]
The wrapped state of a file is stored in `ICodeEditorService` [here](https://github.com/Microsoft/vscode/blob/253a4f6d17dfadd76c1bff0fcc429b8c3274e66d/src/vs/editor/browser/services/codeEditorService.ts#L44:L46).

I am not sure how to best handle the URI change/rename case.

**Comment by bpasero** [comment]
@alexandrudima interesting, I was not aware of that method. The challenge is that the saving of an untitled model happens in a service that is not aware of code editors. As such, neither any view state nor these custom properties are restored when saving to the new model. If a model had the view state somehow associated, I could transfer it to the new model that I am creating [here](https://github.com/Microsoft/vscode/blob/f9703e9/src/vs/workbench/services/textfile/common/textFileService.ts#L603).

**Comment by bpasero** [comment]
Oh, this is https://github.com/Microsoft/vscode/issues/33840.
