### ISSUE TITLE
Angular JS Web App deployement failing for App Service Environment with error unable to verify first Certificate

### ISSUE THREAD

**Issue by Sharuduls** [Microsoft/vscode#64054]
- VSCode Version: Tested in both VSCode 1.29.1 and VSCode Installer 
- OS Version: Window 10

**Issue : Angular Js Web App Deployment is failing to verify the valid certificate in App Service Environment.**

**_Below Setting are in placed:_** 
1. VPN Peering is already in placed for the system which is used for deployment.
2. Workspace setting for http.proxyStrictSSL is set to false.
3. The same Certificate which has been uploaded to ILB Certificate is imported to the Trusted Root Certification Authorities.
4. Azure App Service extension is enabled in VSCode.

Deployment fails with below error message:
**Error : Unable to verify the first certificate.**

**Comment by rebornix** [comment]
Please file issue against the Azure App Service extension you are using.
