### ISSUE TITLE
git annex files do not appear

### ISSUE THREAD

**Issue by jerlich** [Microsoft/vscode#64058]
Issue Type: <b>Bug</b>

I'm not sure this is exactly a bug.

When using VSCode inside a git annex directory if the files are not on the local machine they do not appear in the file explorer even though they do appear in an `ls` on the terminal. This is confusing and maybe a bug.

The files are symlinks. So my guess is that in general that VS Code will ignore symlinks to missing files. Maybe instead they can appear in red or with a little mark.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vsc-material-theme|Equ|2.6.1
matlab|Gim|0.9.0
gc-excelviewer|Gra|2.1.26
r|Iku|1.0.0
mysql-syntax|jak|1.3.1
latex-workshop|Jam|5.17.3
language-julia|jul|0.10.3
python|ms-|2018.11.0
sublime-keybindings|ms-|4.0.0
unicode-latex|oij|1.1.2
vscode-icons|rob|7.28.0
code-spell-checker|str|1.6.10
vscode-mermaid-preview|vst|0.10.1
markdown-all-in-one|yzh|1.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I don't know anything about git annex, but could it be due to this default setting perhaps?

```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
  }
```
