### ISSUE TITLE
search with using PCRE2 doing search only opened files

### ISSUE THREAD

**Issue by burakoztirpan** [Microsoft/vscode#64057]
hi there, I can search any either string or regex among non opened files. But search with using PCRE2 just searched on opened files.Also when I tried to PCRE2 search with opened files,that search showing true results.

**Comment by roblourens** [comment]
Are you trying a regex search or just basic text?

What OS?

**Comment by burakoztirpan** [comment]
i trying a regex search. Windowns 10
