### ISSUE TITLE
Explorer  disappears auto

### ISSUE THREAD

**Issue by garden5538** [Microsoft/vscode#64055]
Issue Type: <b>Bug</b>

Explorer  disappears auto

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel Core Processor (Haswell, no TSX) (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|8.00GB (3.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
gitlens|eam|8.5.6
vetur|oct|0.14.3

</details>

**Comment by Tyriar** [comment]
You need to provide more details.
