### ISSUE TITLE
when working with dual-monitor on windows, editor does not work properly

### ISSUE THREAD

**Issue by 19317362** [microsoft/vscode#64053]
When vscode was dragged to screen 2 1K (resolution 1920*1080)  -- when select/edit, the Cursor postion is error.  I can not do any edit. 
![ko](https://user-images.githubusercontent.com/13182253/49274928-c4eda780-f4b4-11e8-8e84-3d631cbff3c5.png)

When vscode was dragged to screen 1 (4K resolution 3840*2160)  -- works fine.
![ok](https://user-images.githubusercontent.com/13182253/49274943-cdde7900-f4b4-11e8-9c7a-2b6a769b47ae.png)

**Comment by SimonLoir** [comment]
What OS do you use ?

**Comment by 19317362** [comment]
> What OS do you use ?

WIN10 X64 1603

**Comment by 19317362** [comment]
Today, I found this issue is Zoom related. 
After Ctrl + - , It works good. Ctrl+ + , the issue comes again.

**Comment by vainolo** [comment]
Having a similar problem when moving between display with 1920x1080 to a display with 2736x1824.  Cursor is displayed two letters to the right of the location where real cursor is located.
