### ISSUE TITLE
Find in Selection option of Find showing pointer cursor while not active

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6405]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Ctrl+F to bring up Find menu
3. Hover over the Find in Selection option

Its a bit picky, but the Previous and Next match buttons keep the original cursor if they are not available. Previous and Next show the finger pointer icon if active, but the Find in Selection button always displays the finger pointer option when hovered.

![findinselectioncursor](https://cloud.githubusercontent.com/assets/12900364/15306623/137a14e8-1b81-11e6-8113-79fb038bf6fb.gif)

**Comment by isidorn** [comment]
Assigning to @vsccarl to verify the fix which should be available tomorrow
