### ISSUE TITLE
Allow to sort branches alphabetically

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#64077]
I agree that sometimes it is more useful to [sort branches by last commit date](https://github.com/Microsoft/vscode/issues/3564) but I often feel that it makes it hard to find branches when a naming scheme like "user/feature" is used and I want to quickly find all branches of a user. Even without that scheme there are good reasons why having an alphabetical sort option makes sense, if only for personal preference. To avoid a religious discussion, could the sort order be made into a config option?

**Comment by skprabhanjan** [comment]
@joaomoreno , working on this :)
