### ISSUE TITLE
After removing breakpoint, its still stopping the iteration flow

### ISSUE THREAD

**Issue by foresightbabu** [Microsoft/vscode#64072]
Issue Type: <b>Bug</b>

Some time debugging breakpoint is not working correctly.  i removed breakpoint but still its stoping the iteration. (framework express js). Before I start debug, I added few breakpoints then at run time I removed  some breakpoints. but vs code stopping each time. I have to stop the debug and remove all breakpoint then if I start, its going well.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.4
gitlens|eam|8.5.6
git-project-manager|fel|1.7.1
githd|hui|2.1.0
git-tree-compare|let|1.4.0
git-merger|sha|0.4.1
gitblame|wad|2.6.2

</details>

**Comment by dpwolfe** [comment]
What version of node are you using @foresightbabu? A teammate and myself are experiencing this and we're running node 11.3.0. Haven't tried other versions yet. First time I tried Log Points and Conditional Breakpoints too and those don't seem to work at all for me... might be related.

**Comment by foresightbabu** [comment]
Hi,
Im using Node version 10.14.0 and npm 6.4.1. This issue comes when i include break point before starting the debug and remove breakpoint at runtime.

Reproduce steps
1. Add breakpoints in express js code (I'm using async/eachSeries for looping)
2. Start debug go one full flow, breakpoint will stop the iteration
3. Now remove one or two breakpoints, then go full flow (do not restart debug)
4. This time break point stops in the same break point

when i remove a breakpoint, in Breakpoints section its removed correctly, but it will stop the iteration.
if i add breakpoint at runtime and remove it at runtime, its going well.

**Comment by akoltz** [comment]
I'm seeing precisely the same issue as @foresightbabu. I find that I need to reset my debug session frequently in order to clear breakpoints correctly.

**Comment by weinand** [comment]
With "resetting debug session" you mean pressing either the red stop button or the restart button, correct?

**Comment by isidorn** [comment]
@foresightbabu 
Can you reproduce this iwth latest vscode insiders
https://code.visualstudio.com/insiders/

You are currently using a very old vscode stable

**Comment by PowerMogli** [comment]
I have the same issue and I am using the latest insider version.

**Comment by isidorn** [comment]
@PowerMogli then can you please file reproducable steps? Creating a minimalist repo on github for us to repro this would be great.
