### ISSUE TITLE
VS Code is not able to debug using Jest

### ISSUE THREAD

**Issue by RobertoMoralesValencia** [Microsoft/vscode#64079]
Hi,

We are working on a React Native app for Windows. I’m trying to launch Jest from VS Code without success.
 
This is my launch.json configuration:
 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "protocol": "auto",
            "port": 9229,
            "runtimeArgs": ["--inspect-brk=9229", "${workspaceRoot}/node_modules/.bin/jest", "--runInBand", "--coverage"],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "trace": true,
            "autoAttachChildProcesses": true
        }
    ]
}
 
 
However, when I launch the debugger using F5, I hit the following error:
 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
 
PS E:\repos\uo-exp\uo-exp-view\packages\playground> cd 'e:\repos\uo-exp\uo-exp-view\packages\playground'; & 'C:\Program Files\nodejs\node.exe' '--inspect-brk=9229' 'E:\repos\uo-exp\uo-exp-view\packages\playground/node_modules/.bin/jest' '--runInBand' '--coverage'
Debugger listening on ws://127.0.0.1:9229/37cf997e-8a7c-4b5c-b27b-c081bb2e1ddd
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
E:\repos\uo-exp\uo-exp-view\packages\playground\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
 
SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Waiting for the debugger to disconnect...
PS E:\repos\uo-exp\uo-exp-view\packages\playground>
 
I noticed something interesting, please tell me if I’m wrong but I believe this is how VS Code is trying to launch Jest: E:\repos\uo-exp\uo-exp-view\packages\playground\node_modules\.bin\jest:2.  This string ends with :2 which I don’t understand why. If I try to execute like this in a cmd window it fails too:
 
E:\repos\uo-exp\uo-exp-view\packages\playground>E:\repos\uo-exp\uo-exp-view\packages\playground\node_modules\.bin\jest:2
The filename, directory name, or volume label syntax is incorrect.
 
However, if I remove that :2 it works just fine:
 
E:\repos\uo-exp\uo-exp-view\packages\playground>E:\repos\uo-exp\uo-exp-view\packages\playground\node_modules\.bin\jest
PASS  lib\__tests__\Hello.js
  √ First UT (2255ms)
 
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        5.997s
Ran all test suites.
 
I think the “SyntaxError: missing ) after argument list” error is related to that :2.
 
Can you please help me understand why that :2 appears and what does it mean? Also, can you please tell me if I’m missing something in my launch.json configuration?

Thanks.

**Comment by weinand** [comment]
Did you try this setup: https://github.com/Microsoft/vscode-recipes/tree/master/debugging-jest-tests

**Comment by RobertoMoralesValencia** [comment]
Hi Andre,

Thanks for looking into my issue! VS Code is able to launch the tests with that config, but it is not stopping on the breakpoint I added. What do you think could be the issue?

Regards,

Roberto

**Comment by roblourens** [comment]
I'm investigating an issue with Jest debugging that could be related. https://github.com/facebook/create-react-app/issues/5319#issuecomment-443296066

You can try setting `"disableOptimisticBPs": true` in your launch config to see whether that helps.

**Comment by RobertoMoralesValencia** [comment]
I tried that with no luck.

    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Jest All",
        "disableOptimisticBPs": "true",
        "program": "${workspaceFolder}/node_modules/.bin/jest",
        "args": ["--runInBand"],
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "windows": {
          "program": "${workspaceFolder}/node_modules/jest/bin/jest",
        }
      },

VS Code complains that “Property disableOptimisticBPs is not allowed.” I also tried with the underscore and with the insiders version.

**Comment by roblourens** [comment]
Yes it's in Insiders only, and you can ignore the warning that the property isn't allowed (not sure whether you actually tried debugging with it)

**Comment by RobertoMoralesValencia** [comment]
I tried on insiders using
"_disableOptimisticBPs": "true",
And
"disableOptimisticBPs": "true",

In both cases, Jest didn’t stop in the breakpoints.

**Comment by roblourens** [comment]
Can you break on a debugger statement?

**Comment by roblourens** [comment]
If you set a debugger statement at the top of the file, then do your breakpoints get hit?

If you rerun the tests (there should be an option in the terminal to press a key to rerun the tests) do they get hit?

All of this with disableOptimisticBPs set

**Comment by RobertoMoralesValencia** [comment]
So, My ...\__tests__\Hello.tsxHello.tsx test is transformed into ...\lib\__tests__\Hello.js when I press F5. The breakpoints I added are located in the tsx file, so when Jest runs it takes the Hello.js test from lib which doesn't have breakpoints.

That being said, if I set breakpoints in the converted .js file, the execution stops without the need of using "debugger;".

Can you please tell me if it's possible to avoid that conversion from .tsx to .js? Or is it always gonna be the case where I need to work on the transformed .js test?

Thanks.

**Comment by RobertoMoralesValencia** [comment]
Sorry I have a typo in the lib path, I meant ...\lib\__tests__\Hello.js

Thanks.

**Comment by roblourens** [comment]
> The breakpoints I added are located in the tsx file, so when Jest runs it takes the Hello.js test from lib which doesn't have breakpoints.

This is correct, sourcemaps are supposed to map from one to the other, this case should work. If you set a debugger statement does it stop in the tsx file or the js file?

Can you share your project?

**Comment by RobertoMoralesValencia** [comment]
I can't share the project in public. Maybe we can continue this conversation over email or Teams?

Thanks.

**Comment by roblourens** [comment]
I prefer github but feel free to reach out to me on Teams.

**Comment by roblourens** [comment]
Offline, we discovered that something in the build/test chain of this project is removing the `//# sourceMappingURL` comment from the .js file. Without that, the sourcemap can't be loaded.

**Comment by mrmckeb** [comment]
@roblourens, was this sourcemap issue within CRA or this particular project?

**Comment by roblourens** [comment]
In this case, it was within this particular project.
