### ISSUE TITLE
VSCode is blurry on Chrome OS with scaling

### ISSUE THREAD

**Issue by kenchris** [microsoft/vscode#64070]
The below screenshot is running on an external monitor connected to the Pixelbook. It is set to scale to 130%

The Desktop PWA (progressive web app) Twitter running in Chrome is scaled nicely, but VSCode is not.

![screenshot 2018-11-28 at 11 55 21](https://user-images.githubusercontent.com/1101339/49287825-2c98f800-f49f-11e8-8e0e-6c22613e4ec3.png)

As can be read in https://www.reddit.com/r/Crostini/wiki/howto/adjust-display-scaling Linux/Crostini apps in CrOS (Chrome OS) are scaled by sommelier, which I assume scaled the resulting window.

The proper solution is to not scale the window content, but give the scale factor to Electron, as Electron embeds Chrome which can paint at the right scale via Skia. Chrome additionally exposes this as `window.devicePixelRatio` which means that at higher DRP (device pixel ratio) it can use images of higher resolution.

![screenshot 2018-11-28 at 12 02 08](https://user-images.githubusercontent.com/1101339/49287969-a29d5f00-f49f-11e8-9dc2-088fd6d2610b.png)

Electron on Linux additionally uses GTK+ but I assume that GTK as well has a way to paint at the right resolution.

The question is how to make sure that VSCode is not being scaled by sommelier on CrOS and how it should get the scale (also when it changes or window is moved from one display to the other).

**Comment by kenchris** [comment]
Some info about GTK DPI adjustment: https://wiki.gnome.org/HowDoI/HiDpi

**Comment by kenchris** [comment]
Actually experimenting I get pretty good results using

`GDK_SCALE=2 sommelier -X --scale=2 --dpi=208 /usr/share/code/code`

The DPI is calculated as "160 * 1.3" as devicePixelRatio 1 equals a DPI of 160 and I am using a scale of 1.3%. Not sure this is  the right way of doing it and this is all be detected automatically anyways

**Comment by kenchris** [comment]
I wrote a mini medium article on how to work around this issue:
https://medium.com/@kennethrohde/sharp-looking-vscode-on-chrome-os-e8edf7c1411d

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by silenceisgolden** [comment]
Is there a link to the upstream electron issue?

**Comment by ArunRamachandran25** [comment]
Sir, But How can you make it permanent, when I restart visual studio code it reverts.

**Comment by MaxGhenis** [comment]
VSCode is still very blurry on my 4k monitor hooked up to a Pixelbook, whether using low-density or high-density. Please reopen this.

**Comment by envirodatavis** [comment]
I find this workaround the most simple: add `--force-device-scale-factor=2` to the last line in the /usr/bin/code file:

ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@" --force-device-scale-factor=2

**Comment by shahriar0247-telware** [comment]
i use the web one for now as a chorme app, but nothing beats native

**Comment by MoizDev** [comment]
They say that the simplest solution is often the best one. How about we ditch these confusing commands and simply go to the Chromebook's settings > Device > Display Size and set it to 100%. VS Code no longer has a problem after this. 

The Chromebook's UI is only slightly smaller at 100%, and I honestly think it is better.

**Comment by FaikYY** [comment]
> They say that the simplest solution is often the best one. How about we ditch these confusing commands and simply go to the Chromebook's settings > Device > Display Size and set it to 100%. VS Code no longer has a problem after this.
> 
> The Chromebook's UI is only slightly smaller at 100%, and I honestly think it is better.

This worked on my ChromeOS Flex. I was trying to use 90% to have more screen estate but I guess for now I'll keep it at 100%. Thanks for the tip!

**Comment by haohaolee** [comment]
> They say that the simplest solution is often the best one. How about we ditch these confusing commands and simply go to the Chromebook's settings > Device > Display Size and set it to 100%. VS Code no longer has a problem after this.
> 
> The Chromebook's UI is only slightly smaller at 100%, and I honestly think it is better.

Do you mean something like?
![Screenshot 2023-11-12 17 51 23](https://github.com/microsoft/vscode/assets/238419/303b229a-dffe-4690-a5cb-bc9d69c22332)

**Comment by MoizDev** [comment]
> > They say that the simplest solution is often the best one. How about we ditch these confusing commands and simply go to the Chromebook's settings > Device > Display Size and set it to 100%. VS Code no longer has a problem after this.
> > The Chromebook's UI is only slightly smaller at 100%, and I honestly think it is better.
> 
> Do you mean something like? ![Screenshot 2023-11-12 17 51 23](https://user-images.githubusercontent.com/238419/282290808-303b229a-dffe-4690-a5cb-bc9d69c22332.png)

Appears you're using a monitor. Is that 100%? Since the monitor's dimensions are so large, the 100% looks so small. 
Play around with the display size settings. Turn it up, one by one until the blur is gone. Maybe the 100% doesn't work for all displays?
