### ISSUE TITLE
Mathematical white square brackets (⟦⟧) should be treated as breaking punctuation in selections

### ISSUE THREAD

**Issue by varkor** [Microsoft/vscode#64073]
The snippet: `abc⟦def⟧ghi`, when any character is double-clicked, will be entirely selected. `⟦` and `⟧` should be treated as punctuation like any other set of brackets, so that double-clicking on any of the characters in `def`, for instance, will just select the snippet `def`.

This is particularly relevant when theorem proving (e.g. in Coq), where these brackets can be commonly used.

**Comment by rebornix** [comment]
You can put them into `editor.wordSeparators`.
