### ISSUE TITLE
Intellisense icon alignment 

### ISSUE THREAD

**Issue by Pascal-Klinkenbergh** [Microsoft/vscode#64081]
Issue
<img width="509" alt="screenshot 2018-11-30 at 19 25 38" src="https://user-images.githubusercontent.com/41929781/49307563-d7c4a400-f4d5-11e8-8dfd-5009e9993093.png">
 Type: <b>Bug</b>

The selected recommended icon to the keyword of type 'Values and Enumerations' after the 'new' keyword in plain Javascript is not properly aligned.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.98GB free)|
|Process Argv|-psn_0_192559|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
code-runner|for|0.9.5
beautify|Hoo|1.4.7
vscode-simple-icons|Lau|1.9.1
theme-monokai-pro-vscode|mon|1.1.9
cpptools|ms-|0.20.1

</details>

**Comment by Pascal-Klinkenbergh** [comment]
It could be because the additional information on the right of the intellisense window were disabled.
After I pressed that little 'i' icon to enable them there were no more alignment errors.

**Comment by usernamehw** [comment]
Seems to be already fixed in [Insiders](https://code.visualstudio.com/insiders/)
