### ISSUE TITLE
Vscode is automatically changing Keyboard shortcut for a custom shortcut that i created

### ISSUE THREAD

**Issue by tifDev** [microsoft/vscode#64087]
- VSCode Version: 1.29.1
- OS Version: Win 10

I added this custom keyboard shortcut on my keybindings.json:

```
  "key": "ctrl+m",
  "command": "editor.emmet.action.matchTag",
  "when": "editorTextFocus && !editorReadonly"
```

But the editor is automatically changing to "ctrl+º":
https://i.redd.it/u56svc2ida121.png

How can i block this boring thing?

**Comment by alexandrudima** [comment]
I am sorry, I don't understand what the problem is. In the screenshot, you have highlighted a different keybinding. Here is your keybinding (in green):

![image](https://user-images.githubusercontent.com/5047891/49362958-9c49f580-f6e0-11e8-95b8-6dc7c61ab3f2.png)

**Comment by tifDev** [comment]
No im referring to the keybinding "ctrl+m" . Vscode is automatically changing that to "ctrl+º" because of my keyboard layout but i dont want to!

**Comment by alexandrudima** [comment]
@tifDev `ctrl+m` stays `ctrl+m`. You are hovering and highlighting a different keybinding. Look, at line 66 is your keybinding that uses `ctrl+m`. Also, please note that on line 61 nothing is changed, your `keybindings.json` is not touched by VSCode, it is just a hover message that tells you what is most likely printed on your keyboard based on your current keyboard layout.

**Comment by tifDev** [comment]
Oh sorry my mistake in the last message, **im talking of the keybinding " ctrl+' " on line 61**. As you said, that hover message says whats is currently happening: is changing to "ctrl+º" but i dont want to. How can i block it?

**Comment by alexandrudima** [comment]
@tifDev What keyboard layout do you use in your OS?

**Comment by tifDev** [comment]
Portuguese

**Comment by alexandrudima** [comment]
This works correctly. When you configure the following in your `keybindings.json` on Windows:
```
    {
        "key": "ctrl+'",
        "command": "workbench.action.terminal.toggleTerminal"
    }
```

This means you are binding the key that produces `'` on the US standard keyboard layout, i.e. you are binding `Ctrl+VK_OEM_7` (`0xDE`) to the command. Please see the table [here](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes?redirectedfrom=MSDN):

![image](https://user-images.githubusercontent.com/5047891/66413186-306aa480-e9f7-11e9-9589-c943ef3f7d45.png)

Under the Portugues (Portugal) keyboard layout, the key code `VK_OEM_7` produces the character `º`, so we render a hover that invites you to press `Ctrl+º`. That is correct, notice how the keybinding is triggered:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66413408-9ce5a380-e9f7-11e9-8514-da4b9b59170a.gif)
