### ISSUE TITLE
Support workbench.action.openEditorAtLastIndex

### ISSUE THREAD

**Issue by shawnren** [Microsoft/vscode#64089]
Currently VSCode has support for 

- workbench.action.openEditorAtIndex1
- workbench.action.openEditorAtIndex2
- etc.

It would be nice if there was a workbench.action.openEditorAtLastIndex as well, so users could easily go to the last tab open (i.e. how Cmd+9 goes to the last tab in Google Chrome)

**Comment by bpasero** [comment]
Exists: `workbench.action.lastEditorInGroup`
