### ISSUE TITLE
javascript.updateImportsOnFileMove broken on VS mac

### ISSUE THREAD

**Issue by kingces95** [Microsoft/vscode#64082]
**Expected behavior:**
When I move a `.js` file I expect to be prompted to update imports. 

**Actual behavior:**
Prompted on VS windows but not VS mac. On VS mac nothing actually happens whereas I had expected it would prompt me just like windows. 

**Environment**
Mac
Verified using TypeScript 2.9.2 (also tried updating and restarting to load version typescript@3.3.0-dev.20181130)
VS Code 1.25.1

Windows
Verified using TypeScript 3.0.1
VS Code 1.26.1

**Comment by kingces95** [comment]
Cross posted to TypeScript https://github.com/Microsoft/TypeScript/issues/28771.

**Comment by mjbvz** [comment]
Do you see this using the latest typescript versions, 3.1.6 or 3.2.1?

**Comment by mjbvz** [comment]
Also, you are on old VS Code versions. Please update to at least 1.29.1 or, better, the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) build

**Comment by kingces95** [comment]
Nice. Works on the insider build with `typescript@3.3.0-dev.20181130`.
