### ISSUE TITLE
Cursor keeps jumping around

### ISSUE THREAD

**Issue by KMcC7808** [Microsoft/vscode#64086]
Issue Type: <b>Bug</b>

I checked to see if I've recently installed any pluggins that might be causing this. I don't think this is the case. I've also rebooted. My cursor is jumping around and my document is getting reformatted to move commas down one line when they trail a closing braket (JavaScript). If I stop typing for one second, the cursor suddenly jumps to the bottom of the page and when I resume typing I'm typing someplace I wasn't planning on inserting text. 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:11:49.509Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.91GB (16.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
jquerysnippets|don|0.0.1
xml|Dot|2.3.2
docthis|joe|0.7.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
view-in-browser|qin|0.0.5
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by rebornix** [comment]
@KMcC7808 do you have auto format turned on ?

**Comment by rebornix** [comment]
I have a feeling vscode-JS-CSS-HTML-formatter is modifying the content.
