### ISSUE TITLE
No horizontal scrollbars after toggling side by side diff view

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#64090]
- VSCode Version: 1.30 Insiders (doesn't repro on 1.29.1 Stable)
- OS Version: Windows 10

Steps to Reproduce:

1. Open a diff view
2. Toggle back and forth to side by side diff view

Now horizontal scrollbars at the bottom of the editors.

The scrollbars reappear if you close and reopen the diff view.

**Comment by alexandrudima** [comment]
I can reproduce only when using `"breadcrumbs.enabled": true`. I don't think this is a regression, @gregvanl perhaps you have only recently enabled breadcrumbs?

**Comment by bpasero** [comment]
Very likely a regression from https://github.com/Microsoft/vscode/pull/64364

**Comment by alexandrudima** [comment]
@bpasero The bug is from 6 days ago, sorry for being so slow in reacting, I could not reproduce initially and then I forgot to ask for more info... Then today I could repro.

**Comment by bpasero** [comment]
Oh ok, then I take it back.

@jrieken looks like this rule needs to be adjusted for breadcrumbs:

![image](https://user-images.githubusercontent.com/900690/49637194-fdd1d300-fa04-11e8-8005-4b2e8d4ef683.png)

**Comment by jrieken** [comment]
Not a regression, unsure if we should fix this in November but I do have the feeling that this worked some time before...

**Comment by jrieken** [comment]
yeah, this working correctly in 1.28. it seems to have regressed in 1.29 then. @bpasero I don't recalling making changes in breadcrumbs, did the container/titlepart change?

**Comment by bpasero** [comment]
@jrieken I cannot reproduce in stable actually, can you?

**Comment by bpasero** [comment]
I take it back, it reproduces, but only in the diff editor.

**Comment by jrieken** [comment]
👴

**Comment by bpasero** [comment]
hehe ok not so easy:

![image](https://user-images.githubusercontent.com/900690/49639445-4ee4c580-fa0b-11e8-8389-e5db4540929c.png)

@jrieken challenge is that that CSS rule is defined somewhere in the editor grid but the breadcrumb visibility is within the title. Is there some service I can ask to know if the breadcrumb is actually showing or not? Because I see that we do not show the breadcrumb e.g. in the settings (UI) editor, so I cannot just always make the editor height 35+22px if breadcrumbs are enabled...

**Comment by bpasero** [comment]
Actually another idea is maybe to not use CSS at all but set the exact height dynamically, then all I need is a method on the title control to tell me how heigh it wants to be and I guess there I can ask the breadcrumb.

**Comment by jrieken** [comment]
Yeah, this is this https://github.com/Microsoft/vscode/blob/86571ec5a50b5bce09db45f458b407b77a33674a/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L20-L28

**Comment by bpasero** [comment]
Turns out, everything is actually already there via `titleControl#getPreferredHeight()`.

**Comment by jrieken** [comment]
👏
