### ISSUE TITLE
JSDoc suggestions not working with ES6 methods

### ISSUE THREAD

**Issue by seanlaff** [Microsoft/vscode#64097]
Issue Type: <b>Bug</b>

I'm seeing the same behavior as mentioned in this previously addresssed ticket https://github.com/Microsoft/vscode/issues/27729

```jsx
export default class abc {
    myfunc = (myparam) => {
      return myparam
    }
}
```
Typing `/**` above `myfunc` will not trigger the JSDoc snippet

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_7460637|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/28786 to track this upstream
