### ISSUE TITLE
[exploration] "Another instance ... is running but not responding"

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#64091]
Somehow I ended up with a zombie version of VSCode - Exploration that I simply can't get rid of. When I attempt to open VSCode - Exploration I'm presented this dialog:
![screen shot 2018-11-30 at 1 54 18 pm](https://user-images.githubusercontent.com/226872/49317040-d1b7ce80-f4a7-11e8-9544-cf9f43d331ee.png)
Looking at Activity Monitor I can see the offending process:
<img width="912" alt="screen shot 2018-11-30 at 1 58 08 pm" src="https://user-images.githubusercontent.com/226872/49317096-ff9d1300-f4a7-11e8-9375-e20409419014.png">
But I simply can't kill it:
```shell
$ sudo kill -9 79802
$ ps -ax | grep 79802
79802 ??         1:01.08 /private/var/folders/dk/6wr_v2z91hdfz1y2q405wf740000gn/T/AppTranslocation/17463A65-0F32-4318-BAEC-7B2FDE5DBB52/d/Visual Studio Code - Exploration.app/Contents/MacOS/Electron -psn_0_6805117
 3301 ttys000    0:00.00 grep 79802
```

- VSCode Version: VSCode Exploration (can't figure out exact version since it won't open)
- OS Version: macOS 10.14

Steps to Reproduce: unsure

Does this issue occur when all extensions are disabled?: cannot check

**Comment by bpasero** [comment]
@samuela never saw this, `sudo kill -15 79802` should work.

**Comment by samuela** [comment]
@bpasero That doesn't work:
```shell
kumo [master] -> sudo kill -15 79802
Password:
kumo [master] -> ps -ax | grep 79802
79802 ??         1:01.08 /private/var/folders/dk/6wr_v2z91hdfz1y2q405wf740000gn/T/AppTranslocation/17463A65-0F32-4318-BAEC-7B2FDE5DBB52/d/Visual Studio Code - Exploration.app/Contents/MacOS/Electron -psn_0_6805117
 9756 ttys000    0:00.00 grep 79802
```

**Comment by bpasero** [comment]
@samuela whats the full command line of the process?

**Comment by samuela** [comment]
@bpasero What do you mean exactly? I opened it by just opening the app.
