### ISSUE TITLE
VSCode not saving file.

### ISSUE THREAD

**Issue by 2kreate** [Microsoft/vscode#64094]
Version info from VSCode:

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Operating System: Linux Mint 19
Kernel: Linux 4.15.0-39-generic

I can open the file (a python file) in VSCode. When it opens it already shows as unsaved (the dot next to the filename, rather than the x to close). I can make changes and hit save, then immediately reopen the file and the saved changes are gone.

Just to be certain this was a problem with VSCode, I opened the file in Sublime, made changes, saved, reopened and the changes are recorded. Oddly enough, these changes still don't show up in VSCode. I can open the file from the VSCode, or directly from a file folder on the OS, neither makes a difference. I noticed there was another thread with a similar issue that had to do with a Git repo. Running git status inside the directory with the .py file inside of it returns:

fatal: not a git repository (or any of the parent directories): .git

I had left the file open in VSCode for sometime, through several reboots and program restarts after having had working save and close, reopen functionality. Then edited the file, exited and restarted and lost all my changes. Now I'm here.

I have the standard python extension and pylint installed.

Let me know if you need more information.

***EDIT: If I make changes in VSCode, then open the file in Sublime the changes ARE THERE. BUT, if I reopen the file in VSCode again afterwards, the changes disappears and the same version of the file always appears. Then, saving the file will overwrite the previous changes. It seems that VSCode is constantly opening a previously cached version of the file no matter what.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
