### ISSUE TITLE
Support command-Y as "redo" on Mac

### ISSUE THREAD

**Issue by curtw** [Microsoft/vscode#641]
MS Word, Sublime text, and others all support command-Y as the "redo" command on the Mac.
Please support this in VS Code as well.

**Comment by bpasero** [comment]
You can add this to your keyboard settings: `{ "key": "cmd+y", "command": "redo", "when": "editorTextFocus" }`

**Comment by curtw** [comment]
Added above to keybindings.json, which I accessed from Code->Preferences->Keyboard Shortcuts.  Works great.  Thanks.

**Comment by jjsub** [comment]
On windows this work without doing any changes to the settings file.
