### ISSUE TITLE
vscode-tslint errors but isnt installed

### ISSUE THREAD

**Issue by hipstersmoothie** [Microsoft/vscode#64100]
- VSCode Version 1.30.0-insider (1.30.0-insider)
- OS Version: mac 10.13.6

Steps to Reproduce:

1. use typescript project
2. us new tslint typescript plugin
3. Have previously installed and uninstalled vscode-tslint
4. work for weeks
5. suddently stops working and vscode-tslint starts erroring even though not installed

<img width="923" alt="screen shot 2018-11-30 at 5 16 13 pm" src="https://user-images.githubusercontent.com/1192452/49322513-08501200-f4c5-11e8-94dc-3a91a7f726ae.png">

Does this issue occur when all extensions are disabled?: No it is an extension problem

**Comment by mjbvz** [comment]
Is the tslint extension listed in the extensions view? Search `@installed` to see all installed extensions

**Comment by hipstersmoothie** [comment]
vscode-tslint is not installed

<img width="363" alt="screen shot 2018-12-03 at 5 47 07 pm" src="https://user-images.githubusercontent.com/1192452/49413057-890c4980-f723-11e8-9263-20208166efc4.png">

**Comment by mjbvz** [comment]
These error are coming from the TSLint Plugin.

I'll update the error string to remove `vscode-tslint`
