### ISSUE TITLE
VS code extensions takes around 15-20 minutes to load.

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#64107]
- Version: 1.29.1 (user setup)
- Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
- Date: 2018-11-15T19:13:36.375Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64
- OS Version:
![screenshot_2018-12-01 get the pc detils windows](https://user-images.githubusercontent.com/19922707/49324424-1f3d4580-f553-11e8-8c95-28c3cd4941ec.png)

Steps to Reproduce:

1. Turned on system waited for 5 minutes to run all startup programs.
2. Executed VS Code. It opens very quickly but all the installed extensions are not working i.e. inbuilt Source Control, Extensions panel doesn't show any extensions installed.
3. I kept switching **Explorer**, **Source Control** and **Extensions** around 15 minutes later **Source Control** and **Extensions** panel loaded it's content. The time is rendom minimum wait time is 5 minutes.

Here is list of extensions I used.
![extensions i used](https://user-images.githubusercontent.com/19922707/49324550-e652a000-f555-11e8-8ee7-ad1087ad2139.png)

Thank you.

**Comment by rebornix** [comment]
@iyashpal can you follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to produce more info? It would be great to see those numbers for extensions loading.

**Comment by iyashpal** [comment]
![image](https://user-images.githubusercontent.com/19922707/49418264-41c79c80-f7a7-11e8-9018-c5996d084e45.png)

**Comment by iyashpal** [comment]
- VSCode Version: <code>Code 1.29.1  (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)</code>
- OS Version: <code>Windows_NT x64 10.0.17134 </code>
- CPUs: <code>Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)</code>
- Memory(System): <code>7.84 GB(3.31GB free) </code>
- Memory(Process): <code>243.70 MB working set(243.70MB peak, 215.93MB private, 40.63MB shared) </code>
- Load(avg): <code>0, 0, 0 </code>
- VM: <code>0% </code>
- Initial Startup: <code>yes </code>
- Screen Reader: <code>no </code>
- Empty Workspace: <code>no </code>
- Timings:

| Component | Task | Duration(ms) | Info |
| ---| ---| ---| ---|  
| [main]| start => app.isReady| 152| true|
| [main]| nls:start => nls:end| 0| true|
| [main]| app.isReady => window.loadUrl()| 470| true|
| [main->renderer]| window.loadUrl() => begin to require(workbench.main.js)| 1175| NewWindow|
| [renderer]| require(workbench.main.js)| 4099| cached data: NO|
| [renderer]| require workspace storage| 79| |
| [renderer]| require & init workspace storage| 686| |
| [renderer]| register extensions & spawn extension host| 11364| |
| [renderer]| restore viewlet| 0| |
| [renderer]| restore panel| 569| workbench.panel.terminal|
| [renderer]| restore editors| 1367| 0: |
| [renderer]| overall workbench load| 2591| |
| [main->renderer]| workbench ready| 9516| |
| [renderer]| extensions registered| 21049| |
 
---
[prof-3d0a.main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2647073/prof-3d0a.main.cpuprofile.txt)
[prof-3d0a.renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2647074/prof-3d0a.renderer.cpuprofile.txt)
[prof-3d0a.extHost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2647075/prof-3d0a.extHost.cpuprofile.txt)

**Comment by sandy081** [comment]
I do not see any when I load above profiles in the dev tools. 

@jrieken is there a special way to inspect these profiles or they are not created properly?

**Comment by jrieken** [comment]
loading extensions isn't capture by `--prof-startup`.

**Comment by sandy081** [comment]
I see. But when I open the above profiles in my dev tools, I do not see anything, its just empty. I expect to see some call hierarchies atleast.

@iyashpal Can you please try to record the profile for a minute and give us. It will tell us atleast what is hanging on to CPU during then.

**Comment by iyashpal** [comment]
@sandy081 can you please let me know how do I record the profile?

**Comment by sandy081** [comment]
- `f1 -> toggle developer tools` - This opens developer tools
- Go to `Performance` tab and start recording
- You can stop it after doing for a minute or the extensions viewlet is loaded.

**Comment by iyashpal** [comment]
[Profile-20181212T112923.zip](https://github.com/Microsoft/vscode/files/2670649/Profile-20181212T112923.zip)
