### ISSUE TITLE
Not getting object value in debug watch window for imported type "StatusBarItem"

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6410]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open VSCode extension project.
2. Follow instruction to create and debug extension.
https://code.visualstudio.com/docs/extensions/example-word-count
3. Add breakpoint in extensions.ts in updateWordCount() and start debugging.
4. Add _statusBarItem in watch window and verify object values.

Actual: Unable to get object value and showing up "Not available" message.
Expected: User should be able to get object value.
![image](https://cloud.githubusercontent.com/assets/17735796/15309560/bb3476b8-1b9c-11e6-86d0-42e605855533.png)

**Comment by isidorn** [comment]
You should be able to inspect that value by adding `this._statusBarItem` to the watch
