### ISSUE TITLE
Terminal stops drawing some characters/letters

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/vscode#64106]
- OS Version: Windows 10
- VSCode Version:
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

I only had this issue once.

![image](https://user-images.githubusercontent.com/1829149/49324481-45c39800-f4e3-11e8-950f-9379cb424a48.png)

**Comment by Tyriar** [comment]
0.0 I haven't seen this before, let us know if you come up with some repro steps. In the meantime I've been working on a webgl renderer which would fix this (that will take some time to land). https://github.com/xtermjs/xterm.js/pull/1790
