### ISSUE TITLE
Can't update terminal background color with workspace API

### ISSUE THREAD

**Issue by mattmcnabb** [Microsoft/vscode#64101]
Issue Type: <b>Bug</b>

I'm attempting to create a setting in the PowerShell VSCode extension that will automatically set the terminal background color independent of the currently applied theme. Setting the terminal colors works if they are not already currently set in the user settings file. However, if I have manually configured them once, then the call to `workspace.update` has no effect.

Please see the discussion [here](https://github.com/PowerShell/vscode-powershell/pull/1591) for more.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
tslint|eg2|1.0.40
json-tools|eri|1.0.2
live-html-previewer|hdg|0.3.0
powershellprotools|iro|0.3.0
azure-account|ms-|0.6.2
csharp|ms-|1.17.1
PowerShell|ms-|2.0.0
material-icon-theme|PKi|3.6.1
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.2

</details>

**Comment by sandy081** [comment]
@mattmcnabb Can you please provide the sample to reproduce.

**Comment by mattmcnabb** [comment]
@sandy081 [here](https://github.com/mattmcnabb/vscode-powershell/blob/terminalColors/src/features/TerminalColors.ts) is my attempt at getting this to work. Again, it seems to work as long as these values are not already configured. Thanks!

**Comment by sandy081** [comment]
Is not there a programming error here ?

```typescript
  const colors = Object.assign(
                        {"terminal.background": "#141A25", "terminal.foreground": "#F5F5F5"}, colorCustomizations,
                    );
```

Is not the order should be as follows?
```typescript
  const colors = Object.assign(
                        colorCustomizations, {"terminal.background": "#141A25", "terminal.foreground": "#F5F5F5"}
                    );
```

**Comment by mattmcnabb** [comment]
@sandy081 

not according to documents here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by sandy081** [comment]
@mattmcnabb The above link says the same. Values in the first object are overridden by the values from the second object.

It means if `colorCustomizations` has `terminal.background`, it will override the value in the first object. 

Please try the suggestion I made and check if it works?

**Comment by mattmcnabb** [comment]
@sandy081 thanks, I think I have this sorted now!
