### ISSUE TITLE
Unable to open Replace Preview: ModelService: Cannot add model because it already exists

### ISSUE THREAD

**Issue by tschaub** [Microsoft/vscode#64103]
- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. `echo foo > one`
2. `echo foo > two`
3. `code .`
4. Replace in Files: replace `foo` with `bar`
5. Click to view the Replace Preview for `two`, click Replace
6. Click to view the Replace Preview for `one`

Instead of seeing the Replace Preview for `one`, I see an error like this:
> Unable to open 'one ↔ one (Replace Preview)': ModelService:
> Cannot add model because it already exists!.

Does this issue occur when all extensions are disabled?: Yes

![vscode-63347](https://user-images.githubusercontent.com/41094/49323557-4dcb0a00-f4da-11e8-9ea1-8e8d73073fed.gif)

This is a duplicate of #63347, but that was closed because it could not be reproduced.

**Comment by roblourens** [comment]
Thanks for the steps. I still am not seeing that exact error. But I did see `Cannot read property 'getLanguageIdentifier' of null` at

```
(anonymous) (replaceService.ts:74)
then (winjs.base.js:1587)
t.resolve (replaceService.ts:71)
e.provideTextContent (replaceService.ts:51)
(anonymous) (textModelResolverService.ts:103)
o (async.ts:389)
t.first (async.ts:400)
t.resolveTextModelContent (textModelResolverService.ts:105)
t.createReferencedObject (textModelResolverService.ts:46)
e.acquire (lifecycle.ts:77)
e._createModelReference (textModelResolverService.ts:151)
e.createModelReference (textModelResolverService.ts:130)
e.updateReplacePreview (replaceService.ts:143)
t.update (replaceService.ts:87)
(anonymous) (replaceService.ts:76)
e.fire (event.ts:223)
t.updateMatches (searchModel.ts:274)
t.updateMatchesForModel (searchModel.ts:244)
t.onModelWillDispose (searchModel.ts:221)
(anonymous) (searchModel.ts:215)
e.fire (event.ts:223)
o.dispose (textModel.ts:349)
t.destroyModel (modelServiceImpl.ts:570)
t.dispose (textEditorModel.ts:150)
t.dispose (textFileEditorModel.ts:1036)
t.disposeModel (textFileEditorModelManager.ts:316)
t.destroyReferencedObject (textModelResolverService.ts:63)
then (winjs.base.js:1587)
t.destroyReferencedObject (textModelResolverService.ts:60)
(anonymous) (lifecycle.ts:83)
t.once (functional.ts:17)
dispose (textModelResolverService.ts:154)
(anonymous) (lifecycle.ts:22)
i (lifecycle.ts:22)
e.dispose (lifecycle.ts:53)
(anonymous) (replaceService.ts:79)
e.fire (event.ts:223)
o.dispose (textModel.ts:349)
t.destroyModel (modelServiceImpl.ts:570)
t.dispose (textEditorModel.ts:150)
t.destroyReferencedObject (textModelResolverService.ts:65)
Promise resolved (async)
t.destroyReferencedObject (textModelResolverService.ts:60)
(anonymous) (lifecycle.ts:83)
t.once (functional.ts:17)
dispose (textModelResolverService.ts:154)
(anonymous) (resourceEditorInput.ts:120)
Promise resolved (async)
t.dispose (resourceEditorInput.ts:120)
t.close (editor.ts:440)
(anonymous) (editorGroupView.ts:485)
t.onDidEditorClose (editorGroupView.ts:482)
(anonymous) (editorGroupView.ts:435)
e.fire (event.ts:223)
t.replaceEditor (editorGroup.ts:308)
t.openEditor (editorGroup.ts:232)
t.doOpenEditor (editorGroupView.ts:777)
t.openEditor (editorGroupView.ts:739)
t.doOpenEditor (editorService.ts:247)
t.openEditor (editorService.ts:240)
e.openReplacePreview (replaceService.ts:116)
t.onFocus (searchView.ts:1456)
(anonymous) (searchView.ts:542)
e.fire (event.ts:223)
(anonymous) (event.ts:423)
e.fire (event.ts:223)
t.onSelection (listService.ts:554)
(anonymous) (listService.ts:511)
e.fire (event.ts:223)
e.fire (event.ts:225)
e.setSelection (treeModel.ts:1207)
e.setSelection (treeImpl.ts:272)
e.onLeftClick (treeDefaults.ts:187)
e.onMouseDown (treeDefaults.ts:145)
t.onMouseDown (treeView.ts:1254)
(anonymous) (treeView.ts:551)
```

Sounds related @sandy081?

**Comment by sandy081** [comment]
Have to investigate.

**Comment by sandy081** [comment]
I cannot repro either of the errors in insiders

**Comment by roblourens** [comment]
I can, just following the original steps exactly. Not every time though.

**Comment by sandy081** [comment]
Tried couple of times but I cannot. Try disabling extensions?

**Comment by roblourens** [comment]
Today I can't get it to repro at all. I dunno, I think we should just leave this unless anyone sees any issues in 1.30.

**Comment by ccerghed** [comment]
After performing a few global search/replace in several files, the following error is displayed in teh notification area:
"Unable to open <filename> (Replace Preview): ModelService: Cannot add model because it already exists!
I'm running version 1.21.1

**Comment by roblourens** [comment]
1.21 is very old, please upgrade

**Comment by ccerghed** [comment]
Sorry, I meant to say 1.29.1
We cannot upgrade until our internal repos are updated.

**Comment by roblourens** [comment]
Ok, that error appears to be fixed in 1.30 (release next week)

**Comment by johnduffynh** [comment]
I started seeing this error, starting with 1.30 using the https://github.com/formulahendry/vscode-mysql on ubuntu.  
1. Run query
2. Move results window below the query.

**Comment by roblourens** [comment]
Please open a new issue for that @johnduffynh

**Comment by Seanwong933** [comment]
@johnduffynh facing the same error with the same extension, find any solution?
