### ISSUE TITLE
Variable shown declared but never used, while actually it has been used.

### ISSUE THREAD

**Issue by matpadikar** [microsoft/vscode#64113]
Issue Type: <b>Bug</b>

```js
var string = require('../string')
var stub = require('./stub/string')
var chai = require('chai')
var should = chai.should()   //shown as declared but never used but has been used below.

describe('string', function () {
  it('should pass a valid json', function () {
    string({}, {}, stub.json.input, []).should.deep.equal(stub.json.output)
  })
})
```

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (19.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
rest-client|hum|0.20.3
vscode-exec-node|mir|0.5.0
java|red|0.35.0
lorem-ipsum|Tyr|1.2.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
The error is correct; the code never references the local variable `should`. Unless chai is doing something crazy, you should just be able to call `chai.should()` without creating a local variable
