### ISSUE TITLE
Object value is not displaying with mouse hover.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6411]
VSCode Version:1.1.0-alpha
•OS Version: Windows10

Steps to Reproduce:
 1. Launch app and open VSCode extension project.
 2. Follow instruction to create and debug extension.
https://code.visualstudio.com/docs/extensions/example-word-count
 3. Add breakpoint in extensions.ts in updateWordCount() and start debugging.
 4. Once break point hit, hover over on object to verify properties.

Actual: Not getting any info with mouse hover though watch window is showing proper value.

![objectvalueonhover](https://cloud.githubusercontent.com/assets/17735796/15309799/e6b450ae-1b9e-11e6-8beb-f5ff20b1a92d.gif)

**Comment by isidorn** [comment]
Known limitation of the debug hover - the hover is not aware of the AST structure of the document, thus it can not show hover if there are multiple variables named editor across scropes.
In the future we plan to revisit our simple debug hover and that should take care of this limitation
