### ISSUE TITLE
Debug Toolbar Location - floating not visible on Mac

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#64116]
- VSCode Version: 1.29.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Install VSCode
2. Set "Debug Toolbar Location" to "floating"
3. Open some `.js` file
4. Place a breakpoint somewhere
5. Start debugger
6. Profit

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@obrejla  the default setting for the "Debug Toolbar" is "floating" and it looks like this:
<img width="858" alt="2018-12-01_18-46-19" src="https://user-images.githubusercontent.com/1898161/49331179-6d753780-f599-11e8-8e45-479864091fa2.png">

What do you see?

**Comment by obrejla** [comment]
Hi, thanks for such a fast response!

Yep, I know how it looks like and that floating is the default. It also used to work in some previous versions... But now, after some upgrades, it stopped to work. I'm not aware of any changes on my side... I didn't work vis VSCode for several months.

Thanks.

**Comment by obrejla** [comment]
@isidorn 
> Also let us know what is the value of that key?
Unfortunately there is no such a key.
> Also do you not see the debug toolbar for every workspace that you open?
Yes.
> Are you sure you do not have some debug setting set?
I'm not aware of anything :/

**Comment by isidorn** [comment]
Thanks for providing details, however with no reproducable steps there is not much for us to do here.
And it seems that this started to work for you.
If you see it again and you can constantly reproduce let us know and we can reopen this issue
