### ISSUE TITLE
annoying auto completion

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#64115]
- VSCode Version: 1.29.1
- OS Version: 18.04.1
![container](https://user-images.githubusercontent.com/22751352/49334539-c1ebd780-f5d8-11e8-9b67-d4ec9caf01e8.png)

Steps to Reproduce:

1) enter container to an angular component
2) you need to enter "esc" annoyingly to come out from the popup because it inserts an import while entering semicolon after

It's definitely a bug, it's up to you how to solve it.

**Comment by usernamehw** [comment]
This helps?
```json
"editor.suggestOnTriggerCharacters": false,
```

**Comment by usernamehw** [comment]
```json
"editor.acceptSuggestionOnCommitCharacter": false,
```
