### ISSUE TITLE
Git extension API: commit message templates

### ISSUE THREAD

**Issue by apurvaojas** [microsoft/vscode#64119]
I want to write a interactive extension for my organisation which prompt to construct git message using 
"[cz-conventional-changelog](https://www.npmjs.com/package/cz-conventional-changelog)" or any other adaptor compatible for "[commitizen](https://www.npmjs.com/package/commitizen)".

and using event callback pass the message to git extension.

**Comment by apurvaojas** [comment]
@joaomoreno any thoughts.
Should i proceed with this..?

**Comment by axetroy** [comment]
Just need to expose the `git.commit` API in here

https://github.com/Microsoft/vscode/blob/1acabe663a4ec79cb728ea4966278ca4387ac35b/extensions/git/src/api/git.d.ts#L168-L176

This feature can be implemented by third-party extension if we got this API.

**Comment by choppedcode** [comment]
We have a similar use case in our Tasks and Contexts extension to prefill the commit message with the name of the task the user is working on. We have a workaround via git hooks but that requires using git commmit in the terminal as the Git extension doesn’t trigger the git hooks.

**Comment by rusnasonov** [comment]
> prefill the commit message with the name of the task the user is working on. 

Similar usage for branch - prefill branch name with the task name.

**Comment by joaomoreno** [comment]
Will close this with the recommendation to simply use git's commit templates feature, which VS Code picks up.
