### ISSUE TITLE
When we paste powershell script  in VS code, space is getting replaced by Â

### ISSUE THREAD

**Issue by BipulRaman** [Microsoft/vscode#64125]
Issue Type: <b>Bug</b>

Step1: Copy a woking powershell script
Step2: When we paste powershell script  in VS code, space is getting replaced by Â
Note: It is not visible in editor, but during run, error is being thrown as syntex error. This issue is observed specially code is copied from a ps1 file which is copied from one VM to another by putting into ZIP file. This issue is not observed when we paste it in Powershell ISE. I am sharing the sample script here:
https://gist.github.com/BipulRaman/eb598cfaa75d9b077f0e18ba021346a5

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (21.41GB free)|
|Process Argv|D:\DevTest\Block.ps1|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
Angular2|joh|7.0.1
python|ms-|2018.11.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
typescript-javascript-grammar|ms-|0.0.47
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
LiveServer|rit|5.3.1

</details>

**Comment by rebornix** [comment]
@BipulRaman do you see `Â` when you set `"editor.renderControlCharacters": true`? I tried your sample file but can't get `Â` from it.

**Comment by BipulRaman** [comment]
@rebornix , Â will not be visible in the editor, but when you will run the script, you will see exception. "editor.renderControlCharacters" was not set to true for me. I am not able to reproduce the issue repeatedly, but i have captured screenshot for the same code in two different editor. Please have a look on attached screenshots.
![powershell ise](https://user-images.githubusercontent.com/8312486/49424918-12725900-f7c2-11e8-99b6-757ee5de111d.png)
![vs code](https://user-images.githubusercontent.com/8312486/49424920-12725900-f7c2-11e8-8910-c0117daa038a.png)

**Comment by rebornix** [comment]
Looks like an encoding issue in the terminal.

**Comment by Tyriar** [comment]
Please create an issue over at https://github.com/PowerShell/vscode-powershell
