### ISSUE TITLE
PHP tokens are not identified when embedding PHP code in style tags

### ISSUE THREAD

**Issue by ionutvmi** [Microsoft/vscode#64122]
- VSCode Version: 1.29.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new PHP file
2. Insert the following code
```php
<h1>Some html here</h1>

<style>
    <?php if (!empty($links) ) { ?>
        .test {
            <?php echo $links; ?>
        }
    <?php } ?>
</style>
<p>Some other html here</p>
```

Result:
![image](https://user-images.githubusercontent.com/3531898/49328959-5de9f480-f581-11e8-80ab-83556e5e83e8.png)

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/3531898/49328975-870a8500-f581-11e8-8d4c-fb357b789bda.png)

The original issue has been reported here: https://github.com/ionutvmi/spacegray-vscode/issues/12

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/33519
