### ISSUE TITLE
Cursor does not switch back after middle-click on image

### ISSUE THREAD

**Issue by ichbineinNerd** [Microsoft/vscode#64123]
## More Detailed Description: 

after doing the steps described below, the cursor (which should now be the four-directional arrow that usually indicates scrolling on mouse movement) behaves exactly like the "normal" one, not scrolling at all.

## System information:

- VSCode Version: 1.29.1
- OS Version: Win7x64

## Steps to Reproduce:

1. Find an image in any extension description
2. middle-click on it, move the mouse around a bit (while still staying inside the bounds of the image), then release the middle mouse button
3. move the mouse around freely

Does this issue occur when all extensions are disabled?: Yes

**Comment by joekaiser** [comment]
@mjbvz  I'm looking for a first issue to tackle. Is this actively being worked on?

**Comment by mjbvz** [comment]
Looks fixed in insiders? @joekaiser or @ichbineinNerd Can you test on a real windows machine; I only have a VM

**Comment by ichbineinNerd** [comment]
yep, seems fixed.
