### ISSUE TITLE
format php code problem

### ISSUE THREAD

**Issue by cloverzrg** [Microsoft/vscode#6412]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. format this php code error :
preg_match_all('/<table id="xsjbxx"[\w\W]*?>([\w\W]*?)<\/table>/', $resultHtml, $out);

due to ?>

**Comment by cloverzrg** [comment]
preg_match_all('/<table id="xsjbxx"[\**w\W]*?>([\w\W]*?)<\/t**_able>/', $resultHt_ml, $out);

**Comment by cloverzrg** [comment]
preg_match_all('/<table id="xsjbxx"[\w\W]*?>([\w\W]*?)<\/table>/', $resultHtml, $out);

the code change after submit.......

**Comment by aeschli** [comment]
The standard built-in PHP support in VS code has no code formatter. Are you using an extension?
Please file this issue against the extension's source repository.
