### ISSUE TITLE
Next to the git branch button has a vertical line

### ISSUE THREAD

**Issue by marlonfan** [Microsoft/vscode#64127]
- VSCode Version: Version 1.29.1 (1.29.1)
- OS Version: MacOS 10.13.6 (17G3025)

![image](https://user-images.githubusercontent.com/9349370/49331626-4b9ca480-f5db-11e8-8ccd-b0f1085d7271.png)

**Comment by usernamehw** [comment]
/duplicate of #60570 which is a duplicate of #23968
