### ISSUE TITLE
Terminal not usable 

### ISSUE THREAD

**Issue by nilkoushik** [Microsoft/vscode#64128]
Issue Type: <b>Bug</b>

Steps: - 
1) Open a folder via VS Code
2) Pull up the Terminal Panel or use short cut to open it
Result : - 
The terminal open with a scrollbar
cursor vanished, Scrolled up to get the Cursor , now tried to type.. nothing happening , press CTRL+ T , now the terminal is usable, 
For second terminal issue is not there. OR if the terminal panes height is 3/4 th of the screen , able to use it without any glitch.
Problem appears for Insider and Stable build with Latest Windows update.
Same issue with WSL  terminal also.

VS Code version: Code - Insiders 1.30.0-insider (9878edb2a72ed4c4fd64811f9a58f06151810acf, 2018-11-30T06:19:37.226Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (8.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0

</details>

**Comment by LiamD3V** [comment]
This is happening to me on the stable version as well

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
