### ISSUE TITLE
Ugly brackets in the menu 

### ISSUE THREAD

**Issue by Darren** [Microsoft/vscode#6413]
- VSCode Version: 1.1.1
- OS Version: El Captian (10.11.5)

<img width="465" alt="2016-05-17 14 24 23" src="https://cloud.githubusercontent.com/assets/12817/15313107/a7c149ea-1c3b-11e6-8185-b3e2113c08ed.png">

How can I remove those ugly brackets in the menu? are they shortcut hints? No use to me at all.

**Comment by Darren** [comment]
here's another catch:

<img width="422" alt="2016-05-17 14 43 18" src="https://cloud.githubusercontent.com/assets/12817/15313430/d081434c-1c3d-11e6-8048-776b47cc41fa.png">

`Don't save` and `save` with the same hint : (S) ?

**Comment by johnliu2016** [comment]
same to #6184 re duplicate HK of 'S'

**Comment by johnliu2016** [comment]
@Darren the accelerator of "Undo" under "Edit" looks weird, it's supposed to be same as ENU version, can you attach a ENU s/s?

**Comment by johnliu2016** [comment]
@dbaeumer The accelerator looks combination of 'Ctrl' key and 'Z', 'Ctrl' is translated as is in English for Fareast languages, not sure why such appearance on running build.

**Comment by dbaeumer** [comment]
@johnliu2016 The character in parenthesis are for the acceleration key. In language with latin characters this nicely aligns with the text (e.g In German the File menu is called Datei and the acceleration key is d denoted in the translation with &&Datei). However in Chinese we can't use an Chinese character as the acceleration key (would require a different input method and I don't know if this would be feasible at all). So the translators but the accelerator key into parenthesis at the end of the Chinese text as a latin character.

Actually I have to admit that I don't know what the standard is here. @johnliu2016 can you check another product (for example MS Word) and see what they do when running in a Chinese locale.

**Comment by dbaeumer** [comment]
@chrisdias, @egamma: this might be something we need to reconsider as well. I agree that the latin character in parenthesis looks wired.

**Comment by dbaeumer** [comment]
@bpasero is there another way to define an acceleration key than putting && into the text. Can this be done via API?

**Comment by johnliu2016** [comment]
@dbaeumer putting a Latin character surrounded by parenthesis at the string end is the convention of mnemonics localization for Fareast languages (CHS, CHT, JPN and KOR). @Darren usage this mnemonics keys (also known as hotkeys) is pressing key combination (e.g. File menu, 'Alt' + F) to invoke the menu through keyboard. @dbaeumer What seems strange to me is the appearance of accelerator of submenu 'Undo' under menu 'Edit', usually it's like "Ctrl + Z", we localize the short form of the CtrlKey to Fareast languages as is in English.

**Comment by dbaeumer** [comment]
@johnliu2016 the character you see is the Symbol for Command on the Mac.

**Comment by Darren** [comment]
@johnliu2016 
These hotkeys do not work on OSX,  I have tried 'Alt' + F, 'Ctrl'+F and 'CMD'+F, none works for me.
That's the part that confuses me much, looks ugly is another thing, other applications like Safari, Atom do not have such hotkeys hints(ie, hotkeys in brackets instead of on the right).

**Comment by Darren** [comment]
FWIW, OS X Human Interface Guidelines  for menu bars, 

https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html

Since vscode is cross-platform, I think it is important to bring native user experience to users on different platforms.

**Comment by johnliu2016** [comment]
Thanks @Darren. Mistook the OS scenario. @dbaeumer, my previous comment was based on Windows OS (sorry lack of OSX environment to test other product), if same loc work being shared targeting various platforms, I'd agree on separate consideration to fit this case.

**Comment by dbaeumer** [comment]
@bpasero it looks like the Mac doesn't have mnemonic support for Menus (at least Andre isn't aware of any). To make this look nice we either need to strip the last 3 characters "(x)" from a menu label under OS X when running on a fareast language or we need two different keys with different translations. 

Moving to you to consider the best solution.

**Comment by bpasero** [comment]
@johnliu2016 can you clarify what pattern I should look for to remove these mnemonics on Mac? Are you always just adding 3 characters at the end of the label in the form of `(<letter>)`?

**Comment by johnliu2016** [comment]
@bpasero for the 4 Fareast languages, the pattern is like "<Translation String>(<letter>)", with the <letter> denoted with "&&".

**Comment by Darren** [comment]
I am using vscode 1.2 now, it looks so pretty! 
thank you guys all!
