### ISSUE TITLE
Getting SSL error on request

### ISSUE THREAD

**Issue by jookyboi** [Microsoft/vscode#64133]
**I AM THE CREATOR OF THE CACHER EXTENSION**

- VSCode Version: 1.30.0-Insider
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Install Cacher from: https://marketplace.visualstudio.com/items?itemName=Cacher.cacher-vscode
2. Run command `Cacher: Setup`
3. Enter API Key: `6ada540a7faaf0eb`, API Token: `1d28a604ceaa202375251033d9725125`

Expect:
Toast message to show "Successfully set up Cacher.".

Actual:
Request to `https://api.cacher.io/vscode/validate` never seems to complete.

When I try to log the error in Debug mode, I get the following error:
```
Error: write EPROTO 4557563328:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:802:
setup.controller.js:80
	at _errnoException (util.js:1024:11)
	at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

This error does not occur on VSCode v1.29.1.

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
Please file issue against the extension you are using.

**Comment by jookyboi** [comment]
Please re-open this issue. I am the creator of this extension and VSCode-Insider is causing for the request for unknown reasons.

**Comment by rebornix** [comment]
@jookyboi sorry, I misread the error message you sent. This is the same as GitHub Pull Request, which fails when it tries to validate access token, due to the same SSL error. We are already looking into this issue.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by jookyboi** [comment]
@bpasero Thanks for posting. I've confirmed that the build you sent for macOS does indeed fix the request SSL issue for me.

**Comment by rebornix** [comment]
@jookyboi can you try if setting `"http.systemProxy": "off"` can fix the problem in Insiders?

**Comment by chrmarti** [comment]
@bpasero Is the setting enabled in the Electron 3 build?

**Comment by jookyboi** [comment]
@rebornix Turning system proxy to `off` (instead of the default `force`) does fix the problem in Insiders.

**Comment by bpasero** [comment]
@chrmarti I cannot answer your question because I do not know the answer

**Comment by chrmarti** [comment]
Also with Electron 3.

**Comment by chrmarti** [comment]
The affected servers are using SNI (server name identification), meaning: The client must send the server's name with the initial request, which the non-proxied code path was missing. Working on a fix.
