### ISSUE TITLE
Need to reinstall electron when I develop the vscode extention

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#64134]
- VSCode Version: 1.28.0
- OS Version: 10.3.3

Steps to Reproduce:

When the vscode extention function I developed uses electron, after packaging with the `vsce package` command, I need to reinstall the electron package when installing via the` code --install-extension ${source}` command. Otherwise, the electron cannot be turned on.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@chnliquan Not sure if I understand your scenario. What do you mean by 

`When the vscode extention function I developed uses electron` ?

**Comment by chnliquan** [comment]
> @chnliquan Not sure if I understand your scenario. What do you mean by
> 
> `When the vscode extention function I developed uses electron` ?

well, i develop a vscode extention, and one feature i used the [eletron](https://electronjs.org/), when i package (`vsce package`) my extention in local, this feature dose not works, when i reinstall electron `npm install electron` in the extension work dir, it works

**Comment by sandy081** [comment]
@joaomoreno assigning to you as the user is talking about packaging using vsce.

**Comment by chnliquan** [comment]
> I still do not understand what the situation is...
> 
> @chnliquan Why do you install `electron` in your extension? Can you show me your extension repo?

I have developed a vscode extension which has a function when i execute, it will open an electron app. It works normally in the extension host. After development, I package it with the` vsce package` command (not uploaded to the store). When I install the packaged extension locally, This function is invalid, I need to re-install the electron in the extension's directory, restart the vscode and restart the function successfully.

**Comment by joaomoreno** [comment]
But does your extension **need** to ship Electron?

**Comment by chnliquan** [comment]
> But does your extension **really need** to ship Electron? What are you doing for multi-platform?

Some of the features are more complicated, and the extended webview mentioned in the documentation may affect performance, so I used eletron

**Comment by joaomoreno** [comment]
It's not a great idea, since you will not be able to fit Electron for all platforms and still be under the 100MB extension size limit.

**Comment by chnliquan** [comment]
> It's not a great idea, since you will not be able to fit Electron for all platforms and still be under the 100MB extension size limit.

So the reason is that the size of the extension needs to be limited to 100mb, and the dependency of electron exceeds this limit. right ?

**Comment by joaomoreno** [comment]
Yeah. Another reason: the extension should work for all platforms. It's just not practical to ship Electron for Windows, macOS and Linux in your extension.
