### ISSUE TITLE
VSCode reopening error on every time launch

### ISSUE THREAD

**Issue by AyanGhatak** [Microsoft/vscode#64136]
- VSCode Version: 1.29
- OS Version: macOS Mojave 10.14.1

Steps to Reproduce:

1. I was using VSCode for several months now. And for some reason I happen to do something on the terminal I am not sure to remember.
2. But since then I am getting this error message repeatedly.
<img width="427" alt="screenshot 2018-12-02 at 10 01 31 am" src="https://user-images.githubusercontent.com/13015267/49335775-4c086000-f61a-11e8-9a30-5ac6d1ad537f.png">

3. Tried steps mentioned [here](https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec) or even from uninstall and install from HomeBrew.

Doesnt seems to work. It just opens and immediately closes with this error message. 

Does this issue occur when all extensions are disabled?: Yes

I really dont want and wont want to switch other editors. VSCode typescript integration is blazing fast and want to continue use it. Any help is appreciated.

**Comment by bpasero** [comment]
@AyanGhatak does this happen when you run Code from the terminal or from the dock as well?

**Comment by AyanGhatak** [comment]
Hi @bpasero It was caused in all possible situations. 

Seems to be caused due to this . - https://github.com/Microsoft/vscode/issues/60526
Reinstalling and updating Cylance seems to solve the issue.

Thank you. :) It seems so good to be back on VSCode. Had a very painful 4-5 days to code in Typescript without VSCode. 😛 

Closing the ticket.
