### ISSUE TITLE
This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

### ISSUE THREAD

**Issue by waynerQiu** [Microsoft/vscode#64140]
Happy Coding!

_Originally posted by @vscodebot in https://github.com/Microsoft/vscode/issues/63740#issuecomment-441586769_

Extension's Name: "Local History" (xyz.local-history)

**Comment by fourjr** [comment]
Create the issue here: https://github.com/zabel-xyz/local-history/issues
