### ISSUE TITLE
Reuse window not always working for Open Recent

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#64149]
Issue Type: <b>Bug</b>

Launching code with `--reuse-window` flag

Settings
```json
"window.newWindowDimensions": "fullscreen",
"window.openFilesInNewWindow": "off",
"window.openFoldersInNewWindow": "off",
"window.openWithoutArgumentsInNewWindow": "off",
"window.restoreFullscreen": true,
"window.restoreWindows": "all",
```

* Open a workspace (there should be opened editors)
* Close all tabs
* Open recent => switch to another workspace
* New Window is created (2 in total)

If you open a workspace with **0** opened tabs - it will reuse the window
If you open a workspace with **3**(n) opened tabs and do not close them - it will reuse the window

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@usernamehw from your description I do not understand the issue

**Comment by usernamehw** [comment]
I'm trying to force vscode to always use 1 window, unless I explicitly open it as `New Window`.

And it's almost working except for the case:

* Open vscode `--reuse-window`.
* Open 2 or more editors (doesn't matter if workspace is open or not). Or they could be restored from previous session.
* Close them all <kbd>Ctrl</kbd>+<kbd>W</kbd>
* `workbench.action.openRecent`
* Select workspace
* There is now 2 windows

**Comment by bpasero** [comment]
@usernamehw I cannot reproduce and use this command to switch folders/workspaces all the time, I always end up with just one workspace.

Please record what you are seeing and attach it here.

**Comment by usernamehw** [comment]
@bpasero, using the same steps can you try to invoke command from another keyboard shortcut?
```json
{ 
    "key": "shift+alt+p",
    "command": "workbench.action.openRecent" 
},
```

**Comment by usernamehw** [comment]
@bpasero, did you try it?

**Comment by bpasero** [comment]
@usernamehw yes, for me the window loads to the other folder without opening a second window.

**Comment by usernamehw** [comment]
Was it tested on Windows?

I suggest adding a new GitHub label: `needs-repro`/`needs-confirm`. To invite some other vscode team member (or any user) to try to reproduce issue. Failed to get `confirm` label, the issue then should get closed in ~2 weeks and get `not-reproducible` label.

Maybe info about issue not being reproduced under certain circumstances would be helpful too. Some format that can compare and make a decision what are the most probable steps.

Like:

|    |      1      |  2 |  3 | ... |
|----------|:-------------|:------|:------|:------|
| OS |  Windows | Linux | Windows | ... |
| bit |    x64   |   x64 |   x32 | ... |
| OS version | 17134 |    4.18.0-2 |    1809 | ... |
| Empty config | true |    true |  true | ... |
| VM | true |    false |    false | ... |
| ... | ... |   ... |    ... | ... |
| Does it repro? | ✅ |    ❌ |    ✅ | ... |

**Comment by bpasero** [comment]
@usernamehw yeah I like your suggestion, I think we already started to allow for community members to confirm an issue.

I tested this on a Windows machine.

**Comment by usernamehw** [comment]
Found that pressing and releasing <kbd>Ctrl</kbd> before picking workspace workarounds it.

```autohotkey
+!p::
SendInput, +!p
sleep, 100
SendInput {Ctrl Down}{Ctrl Up}
return
```

But the issue is still there...

**Comment by usernamehw** [comment]
@bpasero , **BUT I'M NOT HOLDING <kbd>Ctrl</kbd>**

To review the steps:

* Open vscode
* Open 2 editors
* Close both of them (2) by <kbd>Ctrl</kbd>+<kbd>W</kbd> (When closing tabs by clicking issue doesn't repro)
* Open recent as <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>P</kbd> (When opening recent via <kbd>Ctrl</kbd>+<kbd>R</kbd> or from command palette issue doesn't repro)
* Select the workspace <kbd>↑</kbd> <kbd>↓</kbd>  and press <kbd>Enter</kbd>

**Comment by usernamehw** [comment]
@chrmarti, sorry for dialing. Can you please try to repro this issue on Windows (steps in the comment above)?

Also, does this make sense: https://github.com/Microsoft/vscode/issues/64149#issuecomment-443752200 ?

**Comment by chrmarti** [comment]
Can reproduce on Mac. The issue is that the key-up event for the Ctrl/Cmd key doesn't make it to this listener which should probably just listen on `window`: https://github.com/Microsoft/vscode/blob/0bc965752d99b670ce1ebb9c0d90e5543b588d9b/src/vs/workbench/browser/parts/quickinput/quickInput.ts#L870

**Comment by chrmarti** [comment]
/confirmationNeeded

(Actually turning it around to have `confirm` as a common prefix: `/confirmationNeeded` and `confirmation-needed`.)

**Comment by usernamehw** [comment]
Didn't delete the `confirmation-needed` label.

**Comment by chrmarti** [comment]
I'll look into it. It will need a code change on the bot's side. I'll add it to the wiki page after that. 👍

**Comment by bpasero** [comment]
@chrmarti this would hit quick open pretty bad I think. I locally tested out the change to simply listen on `window` instead and it seems to fix it. My speculation is that somewhere someone listens to keys on `window` scope and then prevents default or bubbling, leading to your listener not getting the call.
