### ISSUE TITLE
Code not launching in Extension Development Host mode

### ISSUE THREAD

**Issue by Yumasi** [Microsoft/vscode#64146]
Issue Type: <b>Bug</b>

### Steps to reproduce:

- Generate a new extension using Yeoman by following the instructions [here](https://code.visualstudio.com/docs/extensions/example-hello-world).
- Open the newly generated project in Code
- Press F5 to start the Extension Development Host instance of Code.

### Expected results:
- A new instance of Code with my Hello World extension loaded
### Actual results
- A generic electron window with electron/chromium/node version information and instructions on how to run electron apps.

Does the problem occurs with all extensions disabled ?
Yes

VS Code version: Code - OSS 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-29T01:21:42.419Z)
OS version: Linux x64 4.19.4-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 960)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.72GB (4.70GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vagrant|bbe|0.5.0
bracket-pair-colorizer-2|Coe|0.0.25
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
git-project-manager|fel|1.7.1
shell-format|fox|2.0.1
theme-monokai-pro-vscode|mon|1.1.9
python|ms-|2018.11.0
cpptools|ms-|0.20.1
Go|ms-|0.7.0
vscode-icons|rob|7.28.0
yo|sam|0.9.3
whitespace|san|0.0.5
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vim|vsc|0.16.13

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@Yumasi Which version of VS Code are you using? Is it stable, insiders or running from sources (OSS) ?

**Comment by sandy081** [comment]
I think we do not support launching an extension from OSS build.

@bpasero / @weinand  Please correct me if I am wrong.

**Comment by weinand** [comment]
Of course we **do** support launching an extension from OSS build.
And we have special code to prevent the problem described above from happening.

**Comment by weinand** [comment]
@Yumasi does this problem reproduce if you run VS Code without extensions?

**Comment by Yumasi** [comment]
@weinand yes, I'm still facing this issue if I run vscode with `--disable-extensions`.

**Comment by Yumasi** [comment]
As I said above, it seems to be the case given the version number given by VS Code, but I'm not the one who built it. It's from the `code` package available in the ArchLinux community repository.

**Comment by weinand** [comment]
If you do not want to use the official builds, I suggest that you build VS Code yourself by running one of the following platform builds after you have cloned the VS Code repo:
```
	npm run gulp vscode-darwin-min
	npm run gulp vscode-win32-x64-min
	npm run gulp vscode-linux-x64-min
```
