### ISSUE TITLE
Is OpenDocumentLinkCommand broken again?

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/vscode#64141]
Hi,

It looks like that the OpenDocumentLinkCommand is not working again in 1.29.1

https://github.com/Microsoft/vscode/issues/51919
https://github.com/Microsoft/vscode/commit/749eb1ebcd536083627f90c7e7abd14b1ef94af3

**Comment by mjbvz** [comment]
To verify:

1. In VS Code workspace, add `[fdsafdasfds](package.json#L100)` in the `Readme.md`
1. Open preview
1. Click link in preview
        * Line 100 of `package.json` should be revealed
1. Click link in markdown editor.
          * Line 100 of `package.json` should be revealed
