### ISSUE TITLE
Leaving a right-click menu open for about 30 seconds causes a This Window Is No Longer Responding error

### ISSUE THREAD

**Issue by whenther** [Microsoft/vscode#6414]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Build 14342

Steps to Reproduce:

1. Right-click in the editor or sidebar to open the context menu
2. Wait about 30 seconds
3. The "The window is no longer responding, You can reopen or close the window or keep waiting" error message appears. 
4. Clicking "Keep Waiting" allows the program to keep working normally.

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/2947

**Comment by tonys5396** [comment]
+1

**Comment by bpasero** [comment]
Fixed with the electron update.
