### ISSUE TITLE
show documentation when writing function like in brackets editor,

### ISSUE THREAD

**Issue by souhaiebtar** [microsoft/vscode#64159]

**Comment by rebornix** [comment]
Please provide more information about this feature request, like screenshots, samples, etc.

**Comment by souhaiebtar** [comment]
in brackets editor when writing code, let say
a file `scripts.js`
we write console, the code editor (brackets ) show the documentation
`The console object provides access to the browser's debugging console, the specifics of how it works varies from browser,..` mdn web docs

**Comment by jrieken** [comment]
We have that with IntelliSense and SignatureHelp
