### ISSUE TITLE
Cannot fold region if indented in C#

### ISSUE THREAD

**Issue by costathi** [Microsoft/vscode#6415]
- VSCode Version: 1.1.1
- OS Version: OSX El Capitan

Steps to Reproduce:

1. Create a C# file
2. add a region with the # in the first column of the line
3. see that you can fold it
4. add a tab or a space before the # 
5. see that you can't fold it

<img width="648" alt="vscode_region_fold_issue" src="https://cloud.githubusercontent.com/assets/11438780/15316095/942d9458-1c1b-11e6-93e5-a53f2b92ce06.png">

**Comment by aeschli** [comment]
So far we only support indent based folding. https://github.com/Microsoft/vscode/issues/3422 is about adding language aware folding.
