### ISSUE TITLE
Launch program with elevated privileges from non-elevated VS Code

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#64157]
I have a program that needs to run elevated. Currently, the only possible way to do this it to run VS Code itself elevated. This has some unfortunate side effects like not being able to drag and drop files onto the editor to open them any more.

Using compile settings to change UAC Execution Level `highestAvailable` or `requireAdministrator` both fail with `Unknown Error: 0x800702e4`. (In the case of `highestAvailable` this seems like a bug.) The same error occurs when setting the exe Compatibility properties to `Run this program as an administrator`.

Can we get an option to request elevation on a launch task without required VS Code itself to be elevated? This appears to possible on Windows.

**Comment by weinand** [comment]
What type of program do you want to launch elevated?
What debugger are you using?

**Comment by akbyrd** [comment]
C++ executable and cpptools vs debbugger, though I'd assume this applies to any executable on Windows and any debugger.

**Comment by weinand** [comment]
VS Code has no builtin support for elevation. Please file this request against the C++ extension.
