### ISSUE TITLE
Expand file match when only one file exists in results

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64158]
- Do search
- Get just one file with any number of matches
- The file should always be expanded (still respecting `search.collapseResults`)

Has broken broken for quite awhile:
https://github.com/Microsoft/vscode/blame/master/src/vs/workbench/parts/search/browser/searchView.ts#L1166

**Comment by jrieken** [comment]
I still see this 68 unique matches in one file

<img width="612" alt="screenshot 2019-01-31 at 18 03 04" src="https://user-images.githubusercontent.com/1794099/52071045-76c35600-2582-11e9-9fc9-64f9785bfa1d.png">

**Comment by roblourens** [comment]
If there are more than 50 it still gets collapsed

**Comment by jrieken** [comment]
> with any number of matches
             ⬆️
