### ISSUE TITLE
I don't want my html properties to move to next line

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [Microsoft/vscode#64150]
- VSCode Version: 1.29.1
- OS Version: Mac Mojave

Steps to Reproduce:

1. I have some html code and when i formatted the code, it is moving the properties of html elements to next line.
2. But i don't want to move them to next line. It is making the code look weird, and it is increase the no.of lines of code as well.
3. I want my code to move the next line only when the line limit exceeds(ex: more than 100 characters per line)
4. I tried with various settings for `"html.format.wrapAttributes"`, but nothing seems working fine.

When i formatted the code it is formatting the code like below, but i don't want this
![screenshot 2018-12-02 at 7 50 04 pm](https://user-images.githubusercontent.com/9896335/49340895-d9c06b80-f66b-11e8-8574-98743b7c0832.png)

I want my code to look like
![screenshot 2018-12-02 at 7 50 25 pm](https://user-images.githubusercontent.com/9896335/49340890-cdd4a980-f66b-11e8-9218-7c0e7b3c3548.png)

Please let me know, how i can fix this?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by octref** [comment]
Disable html formatter in prettier extension: https://github.com/prettier/prettier-vscode, since prettier recently added formatting support.

This does not repro on VS Code without extension.

**Comment by octref** [comment]
Code for repro?

**Comment by rajeshwarpatlolla** [comment]
I have the below settings in my vs code.
````
{
  "editor.tabSize": 2,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.printWidth": 200,
  "prettier.eslintIntegration": true,
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 500,
  "vetur.format.defaultFormatter.html": "js-beautify-html",
  "editor.scrollBeyondLastLine": false,
  "files.insertFinalNewline": true,
  "window.zoomLevel": 0,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "html.format.wrapLineLength": 200,
  "workbench.statusBar.visible": true,
  "html.format.wrapAttributes": "aligned-multiple",
  "html.format.enable": false,
  "editor.minimap.maxColumn": 200
}
````

When i tried to format, it is showing as mentioned above.

**Comment by octref** [comment]
`"html.format.enable": false`, this means you should file bug for whatever formatter you are using, as you are not using VS Code formatter.

If this is a Vue file, read https://vuejs.github.io/vetur/formatting.html.

**Comment by rajeshwarpatlolla** [comment]
Even without using `"html.format.enable": false` also it was not fixed. And it is not only for vue, it is also the same case for react as well.  So please open the issue, we can focus on closing this when it gets fixed. If it gets closed, then no one will try to help on this.

**Comment by octref** [comment]
If you can reproduce this with `code --disable-extensions` I'll reopen it. Otherwise please file bugs for the extensions you are using. We have 4.3k issues and we can't jump to extension issues.

Your behavior looks exactly like prettier extension's behavior.

**Comment by rajeshwarpatlolla** [comment]
If i do that, it is not even recognising the framework, how can it format ?

**Comment by rajeshwarpatlolla** [comment]
I tried uninstalling the prettier now, but still the same issue.

**Comment by octref** [comment]
Are you formatting a Vue file? If so why your issue is saying "Formatting HTML file"?

Have you read https://vuejs.github.io/vetur/formatting.html#settings?

![image](https://user-images.githubusercontent.com/4033249/49461386-91b35d00-f7c1-11e8-872a-a52269edff9b.png)

**Comment by rajeshwarpatlolla** [comment]
Yes, I am using vue file itself.
Tried this, still no luck.

"vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "force-expand-multiline"
    }
  }

**Comment by rajeshwarpatlolla** [comment]
I still have issues with js formatting.

Before formatting(this is how i want it to be formatted)
````
this.sliderLabels.push(`${sd.getMonth() + 1}-${sd.getFullYear()}`);
````

After formatting(which i don't want this formatting)
````
this.sliderLabels.push(
    `${sd.getMonth() + 1}-${sd.getFullYear()}`
);
````
