### ISSUE TITLE
expend function issue ". "(dot) autocomplete

### ISSUE THREAD

**Issue by ferozsho** [Microsoft/vscode#64155]
Issue Type: <b>Bug</b>

Hi,
Unable to load related function while using editor in typescript "." after varaibale name for ex: this.users. showing [loading.....] message but unable to display.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (25.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
ionic3-vs-ionView-snippets|dan|1.0.2
tslint|eg2|1.0.40
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.7
crane|Hvy|0.3.8
php-namespace-resolver|Meh|1.1.0
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
quicktype|qui|12.0.46
vscode-icons|rob|7.28.0
php-ci|sma|0.2.10
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ferozsho** [comment]
After disabled all extensions and still [slow] & 
[autocomplete dot] issue same loading message display but after 2.23 min the autocomplete function work. its taking long time on typescript file

VS Code ver.
```
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by ferozsho** [comment]
Thanks 
@mjbvz its working with [insiders build] version.
but unable to work with VS code default version.
can you please tell me the both differences.

**Comment by mjbvz** [comment]
Thanks for testing. The insiders build has the latest fixes and features. The current insiders build will become VS Code 1.30, which should be released sometime next week
