### ISSUE TITLE
Go Language invalid indentation on return

### ISSUE THREAD

**Issue by uudashr** [microsoft/vscode#64151]
- VSCode Version: 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e)
- OS Version: macOS 10.14.1 (18B75)

Steps to Reproduce:

1. Write source 
```go
package product_test

func ExampleProduct() {
	p, _ := NewProduct(
		"Foo", 
		"Foo is awesome product", 
		decimal.NewFromFloat(10000))|
		
}
```
and put the cursor on column contains "NewFromFloat"

2. Hit return
```go
package product_test

func ExampleProduct() {
	p, _ := NewProduct(
		"Foo", 
		"Foo is awesome product", 
		decimal.NewFromFloat(10000))
		|
}
```
The cursor is under "decimal"

**While expect**, cursor under "p"
```go
package product_test

func ExampleProduct() {
	p, _ := NewProduct(
		"Foo", 
		"Foo is awesome product", 
		decimal.NewFromFloat(10000))
	|
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by uudashr** [comment]
AFAIK Go grammar taken from atom editor. But somehow atom behaviour was correct while incorrect on vscode

**Comment by rebornix** [comment]
In Atom this is controlled by `decreaseNextIndentPattern` which we use `onEnterRule` to control in VS Code. I'll suggest to implement this in the Go extension as it's fairly complicated and requires Go knowledge.
