### ISSUE TITLE
Free memory from long time closed files and too large closed files

### ISSUE THREAD

**Issue by yagotome** [Microsoft/vscode#64156]
## Problem

When you preview a file on editor and closes _preview tab_, vscode free memory allocated for that file.

On the other hand, when you close a file that was really opened (not only previewed), vscode does not free memory spent for that, what is not a problem for small and medium files, but for large files it sounds like a memory leak.

I know it is not bug. Actually, this really improves performance to open recently opened files. However, it is a pain in the neck when working on large files (you need to restart vscode in order to free memory).

## Proposal

My proposal is to free memory used for files that have been closed in a _long time_ and to free (almost) immediately memory for _too large files_. The problem introduced with these ideas is that it will be needed to define what may be considered _long time_ and _too large_ for that purpose.

If it helps, I will remind you that vscode has already some definition for _large files_ as can be seen below.

![notification of large file](https://user-images.githubusercontent.com/16280594/49344708-3b7bd800-f662-11e8-91f2-aa592e36e0cb.png)

**Comment by bpasero** [comment]
@yagotome what you say is not true:

> When you preview a file on editor and closes preview tab, vscode free memory allocated for that file.
> 
> On the other hand, when you close a file that was really opened (not only previewed), vscode does not free memory spent for that, what is not a problem for small and medium files, but for large files it sounds like a memory leak.

Closing a file will free memory.

**Comment by yagotome** [comment]
@bpasero so it seems to be a bug in linux environment (maybe). I've just realised that this problem does not happen when file is not inside a folder opened by vscode. Try openning the containing folder of the file with vscode and then open the file by _vscode explorer_.

**Comment by yagotome** [comment]
@bpasero I have done that by monitoring memory usage of _vscode process_ (`code`) at [htop](http://hisham.hm/htop/) and also at _Ubuntu GNOME System Monitor_.

**Comment by bpasero** [comment]
@yagotome ok, it is well possible that Chrome or even the OS decides to not give back memory that was claimed for whatever reason. I can assure you that closing an editor will dispose its resources from our end.
