### ISSUE TITLE
When cloning / installing VSCode from source, vscode-ripgrep fails with "Bad Credentials"

### ISSUE THREAD

**Issue by matthew-dean** [Microsoft/vscode#64154]
Error from the command line:
```
error [USERPATH]/git/vscode/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: sh
Arguments: -c node ./lib/postinstall.js
Directory: [USERPATH]/git/vscode/node_modules/vscode-ripgrep
Output:
Downloading ripgrep failed: Error: Bad credentials
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

- VSCode Version: Latest
- OS Version: macOS
- Yarn version: 1.12.3

Steps to Reproduce:

1. Clone VSCode
2. Run `yarn`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Hm, there should not be any "credentials" involved. Is it possible that you have an invalid GITHUB_TOKEN variable in your environment?

**Comment by matthew-dean** [comment]
@roblourens Invalid in what way?

**Comment by roblourens** [comment]
In such a way as to trigger `Bad credentials` :) I don't know how that would happen, but we pass in that variable to use as a token for downloading the release from github so it seems suspect.

Does this still happen?
