### ISSUE TITLE
terminal.selectionForeground

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/vscode#64153]
When using `terminal.selectionBackground`, the selection color is _not_ transparent, so I can't see what I'm selecting.

Watch this: https://my.mixtape.moe/moscur.webm

Please add `terminal.selectionForeground` setting so customizing the selection color within the terminal is actually useful.

**Comment by usernamehw** [comment]
It can be transparent `#ff222250` `#f225`

https://code.visualstudio.com/docs/getstarted/theme-color-reference#_color-formats

**Comment by aleclarson** [comment]
@usernamehw Thank you very much!
