### ISSUE TITLE
Unable to minimize window when using `"window.titleBarStyle": "custom"`

### ISSUE THREAD

**Issue by DavidFrahm** [Microsoft/vscode#64165]
Issue Type: <b>Bug</b>

After setting User Preference of `window.titleBarStyle` to `"custom"`, users of Chrome OS Linux (aka Crostini, which currently is Debian 9.6) are no longer able to minimize the application window using the window title bar button or the "Alt + -" keyboard shortcut.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.14.74-07727-g7815dfea1ba2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 1|
|Memory (System)|4.84GB (2.96GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.5
vscode-stencil-tools|nat|2.0.1
vscode-wakatime|Wak|1.2.4

</details>

Reported by numerous users in the Crostini reddit: https://www.reddit.com/r/Crostini/comments/9feqr0/vscode_update/

**Comment by DavidFrahm** [comment]
Just noting that with the recent change in default settings to window.titleBarStyle:custom, this issue is now impacting all new Chrome OS installs.

**Comment by James-Livesey** [comment]
You are also unable to press the Notifications key in the top-right, however I am not sure whether it's Crostini's problem or VSCode's.

**Comment by sbatten** [comment]
@DavidFrahm after getting my hands on a Chrome OS device, it seems this is an issue with the electron API (their minimize call just doesn't work on Crostini). I'll be closing this issue as both upstream and out of scope, but I suggest opening an issue against electron if you would like to see better Crostini support.

**Comment by mhofman** [comment]
I believe this might be a Chrome OS issue, I've filled a bug report there: https://bugs.chromium.org/p/chromium/issues/detail?id=936607

**Comment by James-Livesey** [comment]
Nice 👍
I've starred it to keep track of it!

**Comment by mhofman** [comment]
According to the [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=936607#c7), the fix is in 75.0.3753.0

**Comment by mhofman** [comment]
This was fixed in Chrome 75, currently on the beta channel!
