### ISSUE TITLE
Handle `$tslint5` and `gulp` errors

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#64166]
Repro:

- Clone VS Code
- Open in insiders
- 🚨TSLInt 5 Problem Matcher not found if you didn't install TSLint extension yet
- 🚨`gulp` errors:
	```
	Error: The gulp task detection didn't contribute a task for the following configuration:
	{
	    "type": "gulp",
	    "task": "tslint",
	    "label": "Run tslint",
	    "problemMatcher": [
	        "$tslint5"
	    ]
	}
	```

This is not good for people who are contributing VS Code for first time, or who just cloned a copy of VS Code without deps.

**Comment by alexr00** [comment]
@octref I'm not seeing the gulp error, where is that one?

For the tslint5, that seems like a helpful error to me. One of the tasks that we expect people to use during development is the Run tslint task so letting people know that something is missing seems reasonable.

Something we could do is move the Run tslint task into @egamma TSLint extension.

**Comment by octref** [comment]
IMO I shouldn't be greeted with such an error with I open VS Code source. It would be great if this error can be handled gracefully instead of showing up in the Output channel (this opens up Outuput channel).

**Comment by alexr00** [comment]
We should annotate tasks with errors like this then only send the errors to output when that tasks is run.
