### ISSUE TITLE
Continuing Middle click in explorer to open file

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#64172]
I opened this issue: https://github.com/Microsoft/vscode/issues/55733. For a time the feature worked, but now it doesn't. Nothing happens when I middle click a file in the explorer sidebar.

**Comment by isidorn** [comment]
This works fine for me in the latest vscode insiders.
Can you repro with insiders?
https://code.visualstudio.com/insiders/

**Comment by jamesray1** [comment]
Sorry, forgot about this. I installed it, but middle click doesn't work out of the box, and there is no search result for middle click and scroll click in user settings.

**Comment by isidorn** [comment]
This still works for me both on OS X and on Linux. Let's see if somebody else complains about this and than we can investigate more.
