### ISSUE TITLE
Add a setting so that "Open to Side" continues to creates split editors

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#64175]
Issue Type: <b>Bug</b>

1. Open a file to the side.
2. While selected in the first side, open another file to the side.

Expected result: opens a new tab with the file to the other side.
Actual result: overwrites the existing tab to the other side with the new file.

A workaround is to open the file in the 2nd side in another side (so you have three sides), then move the tab in the 3rd side to the 2nd or 1st side.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.19.4-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz (4 x 2975)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 14, 10|
|Memory (System)|3.72GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
search-crates-io|bel|1.2.1
better-toml|bun|0.3.2
graphviz-preview|EFa|1.3.0
latex-workshop|Jam|5.17.3
rust|rus|0.4.10
crates|ser|0.3.5
vscode-proto3|zxh|0.2.2

</details>

**Comment by bpasero** [comment]
@jamesray1 to be clear, you want "Open to Side" to continue creating new split-editors always? So when you have an editor to the side that is not active and you split the editor, it would create a third split?

**Comment by bpasero** [comment]
Does this help: 
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
