### ISSUE TITLE
Search-and-replace Regex substituted with literal $1 instead of matched text

### ISSUE THREAD

**Issue by joelgenter** [Microsoft/vscode#64178]
- VSCode Version:**1.30.0-insider**
- OS Version: **Linux x64 4.18.0-11-generic**

Steps to Reproduce:

1. Type a search query with regex enabled.
2. Type replace text with reference to matched text (`$1`).
![image](https://user-images.githubusercontent.com/14948437/49351550-d2e42980-f668-11e8-819c-c5f5e3ba7467.png)
3. Click replace.
![image](https://user-images.githubusercontent.com/14948437/49351598-1179e400-f669-11e8-86ab-47fe751751ea.png)

Expected:
![image](https://user-images.githubusercontent.com/14948437/49351717-a086fc00-f669-11e8-9723-8ef364806400.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by roblourens** [comment]
`$1` references a group, your regex must include a group in `()`

**Comment by joelgenter** [comment]
Oh, my bad. Thank you, @roblourens. Do you know why it must include a group? Is there some edge case that the behavior I expected would get hung up on?

**Comment by roblourens** [comment]
That's just how that regex feature typically works.
