### ISSUE TITLE
Opened file should show in the center of the explorer sidebar

### ISSUE THREAD

**Issue by realyze** [Microsoft/vscode#64180]
Issue Type: <b>Bug</b>

1. Open a file
2. Look at the Explorer tab
3. The selected file will appear either at the very top or very bottom which makes the selected file quite hard to find. It used to be centered on the file.

VS Code version: Code - Insiders 1.30.0-insider (0d3a14402d88f0f555ab3250c3ffd4c45a251665, 2018-11-22T06:13:15.521Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.37GB free)|
|Process Argv|-psn_0_6022590|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
rc-beautify|Ato|1.2.0
featurehighlight|Blo|1.4.1
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
vscode-pull-request-github|Git|0.3.0
beautify|Hoo|1.4.7
graphql-for-vscode|kum|1.12.1
terraform|mau|1.3.7
color-highlight|nau|2.3.0
vscode-jest|Ort|2.9.2
postcss|ric|2.0.0
ActiveFileInStatusBar|Ros|1.0.3
stylelint|shi|0.47.0
code-spell-checker|str|1.6.10
move-ts|str|1.11.3
gitblame|wad|2.6.3
wallaby-vscode|Wal|1.0.100
markdown-all-in-one|yzh|1.7.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by realyze** [comment]
BTW I really love VSCode, great work guys! 👍

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/63406
We have reverted the behavior, so you should be good in latest vscode
