### ISSUE TITLE
save new file take long time

### ISSUE THREAD

**Issue by likid1412** [Microsoft/vscode#64181]
Issue Type: <b>Bug</b>

save a new file (even empty) take long time (about 5s), in **Activity Manager**, it shows **Not Responding**.

1. No high CPU
2. Disable all extension.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by likid1412** [comment]
execute: `code --disable-extensions`, and the problem is still reproduces.

Need any more info?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
@likid1412 does it just take long to open the dialog to ask for the file name? does it reproduce when saving an existing file?

**Comment by likid1412** [comment]
does it just take long to open the dialog to ask for the file name? 
-- NO, open the dialog for file name is OK, just `Cmd + S` saving file take long.

does it reproduce when saving an existing file?
-- NO, saving an existing file is OK.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by likid1412** [comment]
Restart seems to solve this problem...

I found my **QuickLook** can't show any file, then restart my mac, and then every thing is fine.
I will post more info if the problem reproduce.
Thanks for answering my question~
