### ISSUE TITLE
When using multiple carets, smart additions get in the way

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vscode#6418]
- VSCode Version: 1.1.1
- OS Version: Windows 7 and Windows 10

Steps to Reproduce:
1. create a piece of code with `'` or `"`. 
2. use `ctrl + d` to select multiple quotes
3. change the quotes
   Expected: no smart closing of quotes
   Actual: smart closing of quotes by adding extra quote.

Image:
![smartcaretonmulticaret](https://cloud.githubusercontent.com/assets/516972/15321671/4278f36a-1c38-11e6-80b6-33fa2fae6e9c.gif)

**Comment by joaomoreno** [comment]
Multiple carets are not the problem.

What we should maybe do is look at the character _before_ the quote and prevent auto closing the bracket if it's alphanumeric. Seems to be what Sublime does.

So the following wouldn't get an automatic close character:

```es6
var y = here|
`````

**Comment by alexandrudima** [comment]
This has been fixed in the meantime. All multiple cursors will now type the same thing.
