### ISSUE TITLE
Splitview needs overflowing behaviour

### ISSUE THREAD

**Issue by blackchoey** [microsoft/vscode#64188]
Issue Type: <b>Bug</b>

I have a 1680x1050 monitor and set to 150% scale. I'm contributing a new view to the Azure view container and found the newly added view could not show up when there're too many views already. I can't shrink spaces for top 4 views any more and the view container can't be scrolled to see the views at the bottom.
![azureview](https://user-images.githubusercontent.com/16605901/49359740-0464ff80-f712-11e8-9e22-64acc30e0113.gif)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (18.44GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.0.1
tslint|eg2|1.0.40
docker-explorer|for|0.1.6
rest-client|hum|0.20.4
vscode-azureappservice|ms-|0.10.0
vscode-azurefunctions|ms-|0.12.1
vscode-azurestorage|ms-|0.4.2
vscode-cosmosdb|ms-|0.9.1
mssql|ms-|1.4.0
azure-account|ms-|0.6.2
azurecli|ms-|0.4.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
vscode-node-azure-pack|ms-|0.0.5
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.4.0
partial-diff|ryu|1.4.0
azure-iot-toolkit|vsc|1.7.1
vscode-arduino|vsc|0.2.23

</details>

**Comment by sandy081** [comment]
@joaomoreno Looks like this is know overflow issue in Split view. Any suggestion how to tackle this?

**Comment by joaomoreno** [comment]
No suggestion really... if the views don't fit in the splitview, there isn't much we could do besides enabling the splitview to scroll. When doing so, you'll risk having scrollbars inside scrollbars... which might end up not being such a big problem. We'd have to try it out.

**Comment by DSotnikov** [comment]
Any update on this? This is painful for extensions using the view because users don't even realize that some of the sections exist. Windows is typically setting 150% or 200% scale on laptops these days so the issue is very common.
