### ISSUE TITLE
It is hard to distinguish vscode from vs2017 in the task bar

### ISSUE THREAD

**Issue by kraiHD** [Microsoft/vscode#64185]
Both the shape and the color of the icon is too close to vs2017.
We are forced to watch them carefully to distinguish one from another. 
The wrong-side click always irritates us. 

I am a newcomer to vscode, and wondered about such a designed feature exists.
I soon understood that you had experienced a long-time journey and may be exhausted.
https://code.visualstudio.com/blogs/2017/10/24/theicon
https://github.com/Microsoft/vscode/issues/35674
https://github.com/Microsoft/vscode/issues/35746
https://github.com/Microsoft/vscode/issues/42836

I am nervous of duplicating this issue.
However, this is not a problem of taste but that of accessibility.
The blue is OK as long as it is possible to identify it easily.

**Comment by misolori** [comment]
Thanks for the feedback, we already have #44931 where we are tracking this. Please feel free to upvote that issue, will close this issue as a duplicate.
