### ISSUE TITLE
Binding element implicitly has an 'any' type.

### ISSUE THREAD

**Issue by chanlito** [Microsoft/vscode#64194]
<img width="627" alt="screen shot 2018-12-03 at 3 54 59 pm" src="https://user-images.githubusercontent.com/15667259/49363271-d2549d00-f713-11e8-8205-2b171c082561.png">

- VSCode Version: 1.29.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Use currently latest vscode (1.29.1)
2. Use currently latest typescript (3.2.1)

If I use VS code typescript 3.1.4

<img width="372" alt="screen shot 2018-12-03 at 3 55 47 pm" src="https://user-images.githubusercontent.com/15667259/49363332-f6b07980-f713-11e8-8493-b67a8ce4acb8.png">

It doesn't show that.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please share some complete, example code (as text)
