### ISSUE TITLE
Some more information about issue #57097(VS Code 1.26.1 recognizing 'htm' extension as opposed to 'html' extension for html docs)

### ISSUE THREAD

**Issue by mea612** [Microsoft/vscode#64196]
I have the same problem with recognizing .html extension (VS Code does not recognize html, but recognizes .htm as .html), but in my situation the problem is with extension Django. I have VS Code 1.29.1. When Django is enabled - VS Code doesn't recognise .html extension(recognizes .hml as .html), when Django is disabled - everything works fine.

**Comment by octref** [comment]
Well, if you follow Django's setup, it doesn't treat `*.html` files as html files:

```json
"files.associations": {
    "**/templates/*.html": "django-html",
    "**/templates/*": "django-txt",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements"
},
```

Open issues for that extension. Thanks.
