### ISSUE TITLE
Filewatcher doesn't detect symbolic links

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#64206]
Issue Type: <b>Bug</b>

When I create a symlink from terminal it is not shown in explorer until I hit refresh button

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.18.0-11-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3762)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (0.26GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
blamer-vs|bea|0.4.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
vscode-dash|dee|2.0.0
java-decompiler|dgi|0.0.2
xml|Dot|2.3.2
gitlens|eam|9.0.1
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
file-icons|fil|1.0.16
code-runner|for|0.9.5
todo-tree|Gru|0.0.107
perl-outline|hit|0.0.4
svn-scm|joh|2.46.2
language-haskell|jus|2.5.0
favorites|kdc|2.4.5
Lua|key|0.0.9
saltstack|kor|0.0.5
sftp|lix|1.7.7
bash-ide-vscode|mad|1.3.3
vscode-todo-parser|min|1.9.1
vscode-remote-workspace|mkl|0.38.0
vscode-language-pack-ru|MS-|1.29.2
python|ms-|2018.11.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.7.0
gradle-language|nac|0.2.3
printcode|nob|3.0.0
vscode-subword-navigation|ow|1.2.0
java|red|0.35.0
vscode-yaml|red|0.1.0
vscode-sort-json|ric|1.13.0
bash-debug|rog|0.3.3
bash-beautify|sha|0.1.1
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.0.6
vscode-java-debug|vsc|0.15.0
vscode-maven|vsc|0.11.3
debug|web|0.22.0
clang-format|xav|1.8.0
vscode-proto3|zxh|0.2.2

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/25547
