### ISSUE TITLE
Test: Proxy Support

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#64202]
Testing #60773

- [x] anyOS @misolori
- [x] anyOS @joaomoreno 

Complexity: 5

This is controlled through the `"http.proxySupport": "override"` setting. Test the following scenarios:
- Proxy with authentication, using the `"http.proxy"` setting.
- Proxy with authentication, using the `HTTP_PROXY`/`HTTPS_PROXY` env variables.
- [Proxy auto-config](https://en.wikipedia.org/wiki/Proxy_auto-config#The_PAC_File) file, using the OS settings to point to a local file.

To run a proxy locally:
```
docker run -e SQUID_USERNAME=foo -e SQUID_PASSWORD=bar -p 3128:3128 robhaswell/squid-authenticated
```

Make sure that all connections initiated from the extension host go through the configured proxy. The `"http.proxy"` setting takes precedence over the env variables which take precedence over the OS settings.

Authentication via OS settings is not supported at the moment.

**Comment by misolori** [comment]
@chrmarti I'm assuming this isn't available on insiders since we reverted yesterday's version?

<img width="258" alt="image" src="https://user-images.githubusercontent.com/35271042/49443201-1c00be80-f7cc-11e8-9637-d145efbb6aba.png">

**Comment by joaomoreno** [comment]
To help with testing, use the following extension:

[http-test-0.0.1.zip](https://github.com/Microsoft/vscode/files/2644595/http-test-0.0.1.zip)

It will put 2 commands in the command palette:

- `Make HTTP Request`
- `Make HTTPS Request`

**Comment by sean-mcmanus** [comment]
@chrmarti @joaomoreno The http.proxySupport set to "override" breaks out C/C++ extension's ability to download our Insider vsix. Please advise us on how we can workaround this issue. I filed https://github.com/Microsoft/vscode/issues/65118 .
