### ISSUE TITLE
Kaspersky Virus Removal Tool detected a HEUR:Trojan.Script.Generic.

### ISSUE THREAD

**Issue by Filgeary** [Microsoft/vscode#64209]
### Kaspersky Virus Removal Tool detected a HEUR:Trojan.Script.Generic.

C:\Users\Filgeary\AppData\Roaming\Code\Cache\f_0000b7.

System Properties

- Date created - 17.11.2018
- Date modified - 17.11.2018

[Link on virustotal.com](https://www.virustotal.com/en/file/44f14e3b299a69060a1e97536d81f0efa7340f3ba13c43f4279c2d13728554fb/analysis/1543832260/)

Windows 7 Ultimate x64 SP1 with all updates.

VSCode

- Version: 1.29.1 (system setup)
- Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
- Date: 2018-11-15T19:13:36.375Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

Extensions

- Beautify 1.4.7
- Bookmarks 10.0.0
- Code Spell Checker 1.6.10
- CSS Peak 2.2.0
- EditorConfig for VS Code 0.12.5
- file-icons 1.0.16
- Live Server 5.3.1
- markdownlint 0.21.0
- One Dark Pro 2.17.7
- Russian - Code Spell Checker 0.2.2
- TODO Highlight 1.0.4

Installed extensions for the last week

- EditorConfig for VS Code
- Russian - Code Spell Checker

Installed soft for my last project for the last week:

[package.json](https://www.dropbox.com/s/drj8oep3iyn3ekd/package.json?dl=0)
[package-lock.json](https://www.dropbox.com/s/vy48c2fzqw8yf1q/package-lock.json?dl=0)
These files from [My last project](https://github.com/Filgeary/demo-website-3)

I have never used before Node.js or npm.

----------------------------------------------
Update

- I reinstall VS Code.
- Install all the same extensions.
- Check system disk "C" by Kaspersky Virus Removal Tool again.
- No problems.

----------------------------------------------
PS: Sorry for my bad English, i am Russian.

**Comment by jrieken** [comment]
@bpasero for what those files are for?

**Comment by Filgeary** [comment]
> @bpasero for what those files are for?

Files from [My last project](https://github.com/Filgeary/demo-website-3)

**Comment by bpasero** [comment]
@jrieken this is a folder owned by Chrome, I think it is the cache for websites.

**Comment by Filgeary** [comment]
> @jrieken this is a folder owned by Chrome, I think it is the cache for websites.

Ok, i will clean my Chrome.

By the way, I have Chrome extensions: uBlock Origin, PerfectPixel by WellDoneCode, Application Launcher for Drive (by Google), Google Docs Offline.

**Comment by bpasero** [comment]
@Filgeary the "Chrome" version we are using in VSCode, not by Google Chrome - the browser. You should be able to delete that Cache folder after closing Code to get out of it.

**Comment by Filgeary** [comment]
> @Filgeary the "Chrome" version we are using in VSCode, not by Google Chrome - the browser. You should be able to delete that Cache folder after closing Code to get out of it.

Ok.
I already reinstall VS Code.

**Comment by bpasero** [comment]
And is the warning gone?

**Comment by Filgeary** [comment]
> And is the warning gone?

Yes. No problems anymore.
