### ISSUE TITLE
Extension viewlet progress is gone

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#64208]
1. Open Extensions viewlet
2. Search for `a`

Nothing shows up for a couple seconds until finally the results show up. An infinite progress bar should've been there.

cc @isidorn @bpasero just in case Composite was touched recently.

**Comment by isidorn** [comment]
I created this issue like a month ago which got closed as a dupe of
https://github.com/Microsoft/vscode/issues/59497
Let me coment there
