### ISSUE TITLE
Something wrong with URIs/tabs on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#64213]
VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:19:31.620Z)
OS version: Windows_NT x64 10.0.18290

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (52.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.3.0
vscode-scss|mrm|0.6.2
PowerShell|ms-|1.9.0
material-icon-theme|PKi|3.6.1
seti-icons|qin|0.1.3
lorem-ipsum|Tyr|1.2.0
vscode-todo-highlight|way|1.0.4
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

Notice the breadcrumbs:

![image](https://user-images.githubusercontent.com/2193314/49378841-7c0b3e00-f6c2-11e8-92c4-a0ac7c3e0fdd.png)

Make a change to the file:

![image](https://user-images.githubusercontent.com/2193314/49378957-da382100-f6c2-11e8-8832-edfce18ee2fb.png)

Switch to the other file:

![image](https://user-images.githubusercontent.com/2193314/49379011-fb990d00-f6c2-11e8-8477-60f29bf95a0a.png)

I originally created https://github.com/Microsoft/vscode/issues/63807 but it turns out it's not a problem with search.

I've been seeing this on and off for the past week in multiple workspaces. The only interesting thing I can think of is my Insiders went ~3 weeks without updating.

**Comment by jrieken** [comment]
> sounds like the URI migration issue (for the drive letter) to me, but that one happened last release already right?

We reverted all of that again, it was in insiders for a two or three weeks only

**Comment by bpasero** [comment]
Ok.
