### ISSUE TITLE
IntelliSense and problems view for Appdata\Local\Temp on Windows

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode#64211]
The Problems View lists problems under C:\Users\USER\AppData\Local\Temp. Is this supposed to happen? If so, how do I ignore it? I tried a few variants for files.exclude but could not get it to work.

![capture](https://user-images.githubusercontent.com/30827238/49378152-31aeaf00-f70c-11e8-8a5d-6e93e559689d.PNG)

VSCode Version: 1.29.1
OS Version: Windows 10 Enterprise

**Comment by mjbvz** [comment]
Did you open that file in VS Code at some point?

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by thernstig** [comment]
@mjbvz It is opened when you do a diff in VS Code. Hence the weird name of it.

**Comment by mjbvz** [comment]
Can you please test this in the latest insiders build or at least 1.30 to see if has been fixed

**Comment by Squiggle** [comment]
I'm seeing the same problem. I have many files in `AppData\Local\Temp\...` which were automatically created when doing a diff/merge, and vscode keeps flagging up 'problems' with them.

I would expect intellisense only to flag problems related to files within my workspace.
