### ISSUE TITLE
Provide better hover feedback for trees that expand/collapse on twisties only

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#64212]
I understand why expanding/collapsing nodes in Outline is special: because each branch node is also an editor position. So, it makes sense that expanding/collapsing a node needs to be distinct from clicking the whole row. The problems is that the tree looks exactly like any other tree in our workbench and I can't tell you how many times I already cursed Outline for clicking something and thinking it was broken because the tree branch did not expand.

There are two main issues, afaik:

- The mouse hover feedback is exactly 100% the same as in the other trees. There should be a better mouse feedback when using Outline: one which gives the indication of two distinct click areas.
- In this mode, double clicking an element should expand/collapse it.

**Comment by jrieken** [comment]
> I can't tell you how many times I already cursed Outline for clicking something and thinking it was broken because the tree branch did not expand.

I would say that you are heavily biased because you have implemented the tree widget. No feedback similar like this has been received from 'normal' tree users so I'd opt to wait a little longer for 3rd party feedback. Also note that the marker panel has now a similar behaviour with related diagnostics

**Comment by jrieken** [comment]
cc @sandy081

**Comment by joaomoreno** [comment]
@jrieken You know people rarely complain on UX annoyances, because the feature is there. That doesn't mean we should do a poor job at UX, right?

**Comment by joaomoreno** [comment]
> Also note that the marker panel has now a similar behaviour with related diagnostics

No, not yet, but it will. It was from that discussion that I decided to finally give some thought to this new pattern of usage.

**Comment by jrieken** [comment]
> You know people rarely complain on UX annoyances

That's what I meant - you call it annoyance but I call it UX that does what I expand without further UX.

**Comment by joaomoreno** [comment]
Well it works, I just need to click twice pretty much every time I visit the outline because it is hardcoded in my brain that can click anywhere in a row to expand/collapse. How does this not happen to you too?

**Comment by jrieken** [comment]
IDK - I guess I always click on the twisty no matter what

**Comment by jrieken** [comment]
I personally would close this as no user has complained to me about this. Leaving it up to the rest

**Comment by joaomoreno** [comment]
I removed some area labels and left it as a tree feature request.

**Comment by joaomoreno** [comment]
Yeah... failed to do anything cool in under 10 minutes, FLUSH :toilet:
