### ISSUE TITLE
Highlight active file in explorer

### ISSUE THREAD

**Issue by fragpit** [microsoft/vscode#64210]
It would be nice to have active opened file highlighted in explorer area. Autoreveal is great, but not very handy on big project. For now explorer leaves  last opened file being highlighted.

So, for clarity: When switching between opened files, explorer should highlight current opened file, and **do not move focus** on it (like in current Autoreveal option). Also it can highlight folder if it not expanded (but **not expand** it automatically)

**Comment by Nowaker** [comment]
Related: https://github.com/Microsoft/vscode/issues/72973. Please upvote @fragpit.

**Comment by jmcbee** [comment]
Hi, any progress on this?

**Comment by sanket-bhalerao** [comment]
Can similar be done in the scm panel as well?

**Comment by isidorn** [comment]
I believe this setting `"explorer.autoReveal": "focusNoScroll"` does what you want. Thus closing this
