### ISSUE TITLE
Hide empty tree from dom, make message not focusable

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64218]
Both focus borders feel wrong, the empty area shouldn't be in the dom and the message shouldn't take focus

![dec-03-2018 16-13-38](https://user-images.githubusercontent.com/1794099/49382341-7e978300-f716-11e8-9598-a645c5054bfe.gif)

**Comment by sandy081** [comment]
Duplicate of #63906. 

I just made message focusable as the fix there.
