### ISSUE TITLE
Another way to switch file/diff opening on clicking from SCM using modifier key

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#64221]
From #63005 

Is it possible to add another way of opening?

`"git.openDiffOnClick": true` - <kbd>Alt</kbd> + <kbd>Click</kbd> - to open file
`"git.openDiffOnClick": false` - <kbd>Alt</kbd> + <kbd>Click</kbd> - to open diff

**Comment by joaomoreno** [comment]
This requires API changes: `altCommand` on `SourceControlResourceState`, something like that.
