### ISSUE TITLE
Not all lines coming through terminal.onLineData()

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#64226]
Not all lines are coming through terminal.onLineData(), which is what tasks uses for problem matchers. This means that some tasks won't report or won't clear problems because some of the lines are missing. This does not occur every time, but about 1 in 5 times. Lines missing is more dramatic when debugging since even more lines a missing.

Easy repro in the vscode repo:
Put a break point in the call to terminal.onLineData in terminalTaskSystem.ts
Run the strict null check watch task
Watch the lines that come through. There should be one about Starting incremental compilation, and it will likely be missing.

**Comment by Tyriar** [comment]
duplicate https://github.com/Microsoft/vscode/issues/57803
