### ISSUE TITLE
Extension API access to recent files/projects

### ISSUE THREAD

**Issue by Phrogz** [microsoft/vscode#64223]
Would like my extension to be able to list recent folders opened by the user. (I'll filter this list to only those folders that are relevant to my extension and provide convenient access to them.) I'd like an API that returns an array of recent files and/or folders.

**Comment by cassiozen** [comment]
Can we reconsider this? Given the popularity of extensions such as [vscode-fuzzy-search](https://github.com/tatosjb/vscode-fuzzy-search), there are real use cases for a recent files API.
