### ISSUE TITLE
Test updating debugAdapter provided sourceReference documents

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64229]
Test for #41362:

- [ ] anyOS: @isidorn 

Complexity: 2

A "loadedSource" event with reason "changed" now properly triggers an update of the "script" node in the LoadedScripts view: added or removed "related" sub-sources will be updated properly.
In addition this event makes VS Code reload the contents of the source behind the script node.

Verify that this works properly:

Setup:
To simplify testing, I've modified mock-debug to provide some "interactive" commands.
- Check out this branch: https://github.com/Microsoft/vscode-mock-debug/tree/aweinand/testbed-64229
- run mock-debug as usual on some markdown file
- every step will create a new "source" in the LoadedScripts view

Verifying content reload:
selecting a Source in the LoadedScripts view will load synthetic contents in the editor and starts a 2 sec interval timer that triggers LoadedScriptsEvents with reason "change" which will make VS Code reload the contents. A backend-generated timestamp shown in the editor should update accordingly.

Verifying that added and removed sub-sources are reflected properly in the view: 
- typing the letter "a" in the REPL creates a new sub-source under the first source
- typing the letter "r" in the REPL removes a sub-source under the first source

**Comment by isidorn** [comment]
This works great as described.
However after adding a new sub-source with `"a"` clicking on it I get an error. I believe this is expected since this is just mock behavior, however let me know if you would like an issue for this and I can create one.

`Unable to open 'bar-1000-source-0': File not found (file:///foo/bar-1000-source-0).`

**Comment by weinand** [comment]
Correct, I did not implement the "sourceRequest" for the sub-sources.
So what you see is the expected behavior.
