### ISSUE TITLE
Test automatic extension host profiling

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64222]
Refs: #60332

- [ ] any @mjbvz
- [x] any @isidorn - will test on os x

Complexity: 4

When an extension takes over the extension host process we now start to profile and to point out those extensions. This is how it works:

* profiling starts when the extension host is unresponsive for 3 seconds already
* profiling lasts for 5 seconds or shorter when the extension host responsive again
* when an extension can be identified as heavy hitter, a log message is printed
* also a telemetry event is send
* last when an extension stole 5 seconds or more a silent notification is shown - a minified notification that shows as number in the statusbar
* selecting that notification will ask you file an issue (only when the extension has a issue-url in its package-json)

With an extension doing heavy work, like dump fibonacci number computation, test the following:

* Trigger the expensive code via a command and listener
* Check the log and confirm that your extension get blamed correctly
* Add a repo-url and check that the editor asks you to file an issue
* Test that the silent notification only shows when your extension took 5 seconds or more
* Check that the file-issue command stores the cpu-profile in your home-dir and that the issue mentions that
* Check that the cpu-profile contains no PII

**Comment by mjbvz** [comment]
Blocked by testing some of this by #64388. Any reason why I would not be seeing the user facing alerts?

**Comment by jrieken** [comment]
@mjbvz you need a repo url - we don't wanna blame extensions that don't have an issue url.

**Comment by mjbvz** [comment]
Thanks. Everything looks good once I added the repo
