### ISSUE TITLE
Implement tree type-navigation support

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#64233]
A tree should be navigable by typing letters which match the row labels, similarly to file explorers.

cc @weinand @isidorn @sandy081 @jrieken

**Comment by jrieken** [comment]
check out this https://github.com/Microsoft/vscode/blob/8ff7181ee758ebf391954ffe802bda59e372f3c3/src/vs/platform/list/browser/listService.ts#L710 and the beefy part which is this: https://github.com/Microsoft/vscode/blob/8ff7181ee758ebf391954ffe802bda59e372f3c3/src/vs/platform/list/browser/listService.ts#L667. Trick is to redirect the key event while its down to an input box

**Comment by joaomoreno** [comment]
Thanks!

**Comment by jrieken** [comment]
>  links are broken tho :P

Needed to push

**Comment by joaomoreno** [comment]
Here's a cool demo:

![peek 2018-12-12 08-36](https://user-images.githubusercontent.com/22350/49853977-1b2de500-fde9-11e8-8778-2964b3f8fba6.gif)

This feature is now available for all lists and new trees. You still need to provide a `TypeLabelProvider` when creating your list/tree, just like what @isidorn has done for debug in https://github.com/Microsoft/vscode/commit/64addbd10dff588d9134ac88a922ee4b6953e13d.

**Comment by weinand** [comment]
@joaomoreno Cool feature, but the name `TypeLabelProvider` is a bit misleading.
And `KeyboardNavigationLabelProvider` is a bit long...

**Comment by joaomoreno** [comment]
Went with `KeyboardNavigationLabelProvider`, not really worried about the length. :+1:
