### ISSUE TITLE
 Uncaught Error: Not an extension entry. Found quickOpenService,openOnPreview,... instead.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#6423]
Issue Id: <b>af6987f6-26ca-8560-c87d-d0f2d2bcae87</b><br /><br />*Versions* <br />- 1.1.0-insider<br />-  def9e32467ad6e4f48787d38caf190acbfee5880<br />*Stack* <br />Error: Not an extension entry. Found quickOpenService,openOnPreview,... instead.<br />[/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.ts#L323:9](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.ts#L323:9)<br />[/vs/base/parts/quickopen/browser/quickOpenViewer.ts#L31:59 (getId)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/quickopen/browser/quickOpenViewer.ts#L31:59 (getId))<br />[/vs/base/parts/tree/browser/treeModel.ts#L1227:56 (getId)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeModel.ts#L1227:56 (getId))<br />[/vs/base/parts/tree/browser/treeModel.ts#L1299:16 (getItem)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeModel.ts#L1299:16 (getItem))<br />[/vs/base/parts/tree/browser/treeModel.ts#L1128:7 (setTraits)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeModel.ts#L1128:7 (setTraits))<br />[/vs/base/parts/tree/browser/treeImpl.ts#L248:13 (setFocus)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeImpl.ts#L248:13 (setFocus))<br />[/vs/base/parts/tree/browser/treeDefaults.ts#L211:8 (setFocus)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeDefaults.ts#L211:8 (setFocus))<br />[/vs/base/parts/tree/browser/treeDefaults.ts#L193:14 (onLeftClick)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeDefaults.ts#L193:14 (onLeftClick))<br />[/vs/base/parts/tree/browser/treeView.ts#L1173:26 (onClick)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeView.ts#L1173:26 (onClick))<br />[/vs/base/parts/tree/browser/treeView.ts#L521:87 (onClick)](https://github.com/microsoft/vscode/blob/c212f0908f3d29933317bbc3233568fbca7944b1/src/vs/base/parts/tree/browser/treeView.ts#L521:87 (onClick))<br />

**Comment by joaomoreno** [comment]
My quick open provider's `DataSource` is being sent data from another input that didn't come from me. Notably, it's getting a [`HelpEntry`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/helpHandler.ts#L20) in the `getId()` call...

Quick open needs some serious rewriting, @bpasero ... I don't want to give you this issue since I was the last to touch the quick open code. But I also don't want to go into it either since the beast is huge as it is, and hard to comprehend...
