### ISSUE TITLE
Cannot install "Winter is Coming" theme

### ISSUE THREAD

**Issue by MarkMeyerMeyerNet** [Microsoft/vscode#64239]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 18.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
vscode-generate-getter-setter|DSK|0.5.0
EditorConfig|Edi|0.11.1
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
json-to-ts|Mar|1.5.5
Angular-BeastCode|Mik|7.0.18
material-icon-theme|PKi|3.6.1
vscode-docker|Pet|0.0.18
path-intellisense|chr|1.4.2
angular2-snippets|dan|1.0.20
vscode-simpler-icons|dav|1.6.5
angular-extension-pack|dog|1.0.2
githistory|don|0.2.3
gitlens|eam|5.5.0
tslint|eg2|1.0.11
auto-rename-tag|for|0.0.14
angular2-switcher|inf|0.2.0
docthis|joe|0.6.0
refactorix|kri|0.3.6
csharp|ms-|1.12.1
typescript-javascript-grammar|ms-|0.0.47
debugger-for-chrome|msj|3.4.0
angular2-inline|nat|0.0.17
tsimporter|pmn|1.2.14
move-ts|str|1.11.3
JavaScriptSnippets|xab|1.7.1

---

Steps to Reproduce:
@johnpapa
1.  try to install Winter is Coming extension
2. get error message: "Couldn't find a compatible version of Winter is Coming Theme with this version of Code."

Reproduces without extensions: Yes/No

**Comment by johnpapa** [comment]
Here is his error message

![img_1142](https://user-images.githubusercontent.com/1202528/49390939-22fdd300-f6df-11e8-882f-10a206528ca1.JPG)

**Comment by usernamehw** [comment]
Since all vscode colors have defaults maybe it's a good idea to ignore minimum vscode version in `package.json`...
```json
"engines": {
  "vscode": "^1.17.0"
},
```

**Comment by MarkMeyerMeyerNet** [comment]
downloading and installing the latest version of code 1.29 resolved the issue

**Comment by johnpapa** [comment]
Glad it works!

Is the vscode version setting required? I could remove it from the `package.json`

**Comment by johnpapa** [comment]
Feel free to close now.
