### ISSUE TITLE
Test new DebugAdapterDescriptorFactory API

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64232]
Test for #62977:

- [x] anyOS: @roblourens

Complexity: 3

In this milestone we have finalized the extension API for intercepting the debug adapters creation:

https://github.com/Microsoft/vscode/blob/7e650bffa7235c5fbaa4b269199d8ac9af4fa83e/src/vs/vscode.d.ts#L8398-L8491

and

https://github.com/Microsoft/vscode/blob/7e650bffa7235c5fbaa4b269199d8ac9af4fa83e/src/vs/vscode.d.ts#L8694-L8703

Verify that:
- the API works as described.
- specifically verify that the 2 constraints are obeyed:
  - an extension is only allowed to register a DebugAdapterDescriptorFactory if the extension defines the debug type. Otherwise an error is thrown.
  - registering more than one DebugAdapterDescriptorFactory for a type results in an error.
- verify that the following cases work:

the default behaviour:
```ts
createDebugAdapterDescriptor(session: DebugSession, executable: DebugAdapterExecutable): ProviderResult<DebugAdapterDescriptor> {
  return executable;
}
```

You can add env vars and cwd:
```ts
provideDebugAdapter3(session, folder, executable, config): ProviderResult<DebugAdapterDescriptor> {
  return new DebugAdapterExecutable(executable.command, executable.args, { foo: "bar" });
}
```

You can emulate VS Code's `debugServer` feature with this:
```ts
createDebugAdapterDescriptor(session: DebugSession, executable: DebugAdapterExecutable): ProviderResult<DebugAdapterDescriptor> {
  const port = session.configuration['debugServer'];
  if (typeof port === 'number') {
    return new DebugAdapterServer(port);
  }
  return executable;
}
```

You can run the DA as a server automatically:
```ts
createDebugAdapterDescriptor(session: DebugSession, executable: DebugAdapterExecutable): ProviderResult<DebugAdapterDescriptor> {

  // start server on launch of first debug session
  if (!this._server) {
    // start listening on a random port
    this._server = Net.createServer(socket => {
      const session = new MockDebugSession();
      session.setRunAsServer(true);
      session.start(<NodeJS.ReadableStream>socket, socket);
    }).listen(0);
  }

  // make VS Code connect to debug server instead of launching debug adapter
  return new DebugAdapterServer(this._server.address().port);
}
```

**Comment by roblourens** [comment]
Works great! Can't find any issues.
