### ISSUE TITLE
Test LoadedScript view based on new Tree

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64230]
Test for #62939:

- [ ] anyOS: @isidorn

Complexity: 3

The Loaded Scripts view has been adopted to use the new tree and need to be retested.

Retest these test items from previous milestones for **node-debug**:

- https://github.com/Microsoft/vscode/issues/54921
- https://github.com/Microsoft/vscode/issues/57249
- https://github.com/Microsoft/vscode/issues/62093

If in doubt about some behavior, please use the stable release for reference.

**Comment by isidorn** [comment]
Works great
