### ISSUE TITLE
ctrl K ctrl F breaks hbs variables

### ISSUE THREAD

**Issue by johngrabner** [Microsoft/vscode#64236]
Issue Type: <b>Bug</b>

Create express with hbs view engine.
Create hbs variable (ie: {{blaw}} in any view file.
ctrl K ctrl F will break hbs file.
![vsc breaks hbs variable 1 of 2](https://user-images.githubusercontent.com/8209285/49387220-ef26ab80-f6e6-11e8-984e-0a4b914b1bdf.PNG)
![vsc breaks hbs variable 2 of 2](https://user-images.githubusercontent.com/8209285/49387223-f2219c00-f6e6-11e8-9a25-e192a6d7246d.PNG)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (15.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.4.0
LiveServer|rit|5.3.1

</details>

**Comment by octref** [comment]
You are probably using the prettier formatter. add below to your setting

```json
	"prettier.disableLanguages": [
		"vue",
		"handlebars"
	]
```

**Comment by octref** [comment]
Unfortunately that's the built-in HTML formatter, which is using js-beautify. You can either open an issue for them, or disable HTML formatting with `html.format.enable: false`.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. It would be great if you can file and issue directly against https://github.com/beautify-web/js-beautify

**Comment by johngrabner** [comment]
The reference utility makes no claims of supporting handlebars/hbs marking for html files.
They also state "existing owners have very limited time to work on this project currently".

So it looks like the error is visual studio using this utility for handlebars/.hbs files.
I can open a ticket for a feature request, but given the above note, it feels kind of pointless.

There appears to be a number of beautifiers for handlebar/hbs.
Maybe this ticket title needs to be changed to "should not use beutifyjs for .hbs .handlebars files, should use one of the beautifiers that target hbs/handlebar files".


Regards,
John Grabner




________________________________
