### ISSUE TITLE
CHrome/Brave browser lag when VS code is opened and mouse is moved

### ISSUE THREAD

**Issue by tmh2211** [Microsoft/vscode#64249]
Issue Type: <b>Bug</b>

1.Open VS code
2.Open Brave browser (0.25.2) or chrome (70.0.3538.110)
3.For a good demonstration open a video player within the browser
4.While the video is playing move the mouse anywhere over the browser window
5.Video lags (as far as I can see the whole rendering of the browser lags, e.g. scrolling while moving the mouse also demonstrates this behavior)

VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:19:31.620Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (23.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment]
please follow this guide:https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by tmh2211** [comment]
Issue Type: <b>Performance Issue</b>

VS Code version: Code - Insiders 1.31.0-insider (d315b31c6b5cdca082b0a6e193306e4001586509, 2018-12-19T08:11:44.094Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (26.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 44308	code-insiders main
    1	    70	 17404	   window (Issue Reporter)
    0	    79	 19160	   shared-process
    0	    78	 53260	   gpu-process
    0	   198	 53968	   window (Welcome - test - Visual Studio Code - Insiders)
    0	    66	 27204	     extensionHost
    0	    12	 33248	     electron-crash-reporter
    0	    11	 38000	     watcherService 
    0	     6	 51520	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - test - Visual Studio Code - Insiders)
|    Folder (test): 0 files
|      File types:
|      Conf files:;
```

</details>
Extensions: none


How should I attach the CPU-Profile of the rendering process?

**Comment by jrieken** [comment]
Sorry, not no action information. The process info show low utilisation. Please us OS level tools to understand where time is spend. The information provided here don't hint towards VS Code
