### ISSUE TITLE
Bug on padStart function hint (NodeJS)

### ISSUE THREAD

**Issue by Platiplus** [Microsoft/vscode#64242]
Issue Type: <b>Bug</b>

When I try to write a padStart() function on a string, the hint shows the incorrect order of args.
First you should write the number of characters intended on the string, and after that, the filler character or string.

On the hint on VSCode, the order is incorrect.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)

![image](https://user-images.githubusercontent.com/1918291/49391791-ca94f880-f713-11e8-9560-36c9aa3ff97b.png)

![image](https://user-images.githubusercontent.com/1918291/49391903-1cd61980-f714-11e8-8c07-06a4f524f5e7.png)

**Comment by mjbvz** [comment]
Seems like https://github.com/Microsoft/TypeScript/issues/23555. I can't repo in latest VS Code build:
![screen shot 2018-12-03 at 4 31 47 pm](https://user-images.githubusercontent.com/12821956/49410287-f5358000-f718-11e8-878c-1e8dfee84e70.png)

* Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? 
* Are you using a custom version of typescript in your workspace?
