### ISSUE TITLE
Incorrect JSX Line Comment of Attribute (Re-open issue #36175)

### ISSUE THREAD

**Issue by sabriele** [Microsoft/vscode#64244]
**VSCode Version: 1.29.1
OS Version: macOS 10.14.1 (18B75)**

I apologise for opening a new issue for an issue that has previously already been closed+locked (and apparently, solved): #36175. I am still experiencing this and suspect that it is due to some flawed extension as mentioned [here](https://github.com/Microsoft/vscode/issues/36175#issuecomment-341557457). Unfortunately, the extension(s) at fault are not mentioned and I have no idea which ones of mine are causing the problem. 

(Also, I don't think this is relevant but I noticed that this issue seems to only happen in js/jsx and not ts/tsx.)

Thank you.

List of extensions in use:

- Tyriar.terminal-tabs
- aaron-bond.better-comments
- AlanWalk.markdown-toc
- alefragnani.Bookmarks
- christian-kohler.path-intellisense
- CoenraadS.bracket-pair-colorizer
- dbaeumer.vscode-eslint
- dinhani.divider
- eamodio.gitlens
- eg2.vscode-npm-script
- esbenp.prettier-vscode
- formulahendry.auto-close-tag
- formulahendry.auto-rename-tag
- gayanhewa.referenceshelper
- Gruntfuggly.activitusbar
- joshpeng.sublime-babel-vscode
- joshpeng.theme-charcoal-oceanicnext
- mikestead.dotenv
- monokai.theme-monokai-pro-vscode
- ms-vscode.sublime-keybindings
- ms-vscode.typescript-javascript-grammar
- ms-vscode.wordcount
- NuclleaR.vscode-extension-auto-import
- PKief.material-icon-theme
- rbbit.typescript-hero
- robertohuertasm.vscode-icons
- Shan.code-settings-sync
- shd101wyy.markdown-preview-enhanced
- timreilly.typewriter-sounds
- wayou.vscode-todo-highlight
- xabikos.JavaScriptSnippets
- xabikos.ReactSnippets

**Comment by mjbvz** [comment]
This is likely caused by the sublime-babel-vscode grammar extension 

I just tried #36175 with all extensions disabled and confirmed we still get the correct comment style

**Comment by sabriele** [comment]
Thank you Matt; you're right, I've been able to verify that disabling the sublime-babel-vscode extension gets the comment style to work correctly.
