### ISSUE TITLE
Please give line numbers a border or different background color

### ISSUE THREAD

**Issue by x62** [Microsoft/vscode#64248]
Issue Type: <b>Feature Request</b>

Line and editor backgrounds are same color.  This causes me to misplace my cursor when starting a new line.  This issue has been raised years ago.  It seems like an easy fix.   Thank you.
(Yes I have tried the editor.renderwhitespace -> boundary
Kinda hokey don't you think?)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
```json
"workbench.colorCustomizations": {
    "editorGutter.background": "#ff0000",
}
```
