### ISSUE TITLE
I hope vscode can open files by mutiple windows such as sublime text

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#6424]
I hope vscode can open files by mutiple windows such as sublime text

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/48

**Comment by biij5698** [comment]
What time is it can support ?

**Comment by biij5698** [comment]
@Tyriar  What time is it can support ?

**Comment by Tyriar** [comment]
@biij5698 follow #48 to track the issue.
