### ISSUE TITLE
Support ~/ paths for typescript.tsdk

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#64253]
Issue Type: <b>Bug</b>

I am getting an error in the workspace:
```
The path /Users/st016lo/github/angular-material-test/~/.nvm/versions/node/v10.1.0/lib/node_modules doesn't point to a valid tsserver install. Falling back to bundled TypeScript version.
```

The first part of the error path is the project in question:  `/Users/st016lo/github/angular-material-test/`   Not sure why this is being appended to what I put in my user  settings.

My global version of Typescript is installed at 
`/Users/st016lo/.nvm/versions/node/v10.1.0/lib/node_modules`

Wherein `/Users/st016lo` is my home directory.  I don't want to use the absolute path as I synchronize settings with another mac with a different home folder name and want this to work on both.

I have added this to my settings.json:
```
  "typescript.tsdk": "~/.nvm/versions/node/v10.1.0/lib/node_modules",
```
What am I missing here?

VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:12:08.874Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-svgo|ajh|0.1.0
Bookmarks|ale|10.0.0
project-manager|ale|10.0.0
ACF-Snippet|ant|1.9.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.45
prettier-vscode|esb|1.7.2
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.13.1
svg|joc|0.1.4
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.9
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.22.0
polacode|pnp|0.2.2
quicktype|qui|12.0.46
LiveServer|rit|5.3.1
code-settings-sync|Sha|3.2.2
stylelint|shi|0.47.0
rewrap|stk|1.9.1
ayu|tea|0.17.0
sort-lines|Tyr|1.7.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
We only support workspace relative or absolute paths for tsdk (not shell conventions like `~`). A few extensions such as python use libraries like [this one](https://www.npmjs.com/package/untildify) to support `~` paths.

I've updated the title and have marked as a feature request. The setting we'd want to support is:

```json
    "typescript.tsdk": "~/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib",
```

**Comment by smlombardi** [comment]
Or, like the project manager extension does it, with a `$home`

**Comment by skprabhanjan** [comment]
@mjbvz , Can i take a look at this?
Some starter points would be helpful ,thanks :)

**Comment by ecraig12345** [comment]
Rather than just supporting ~ in paths for typescript.tsdk, shouldn't it be supported in all setting paths? I'd hope that the code for resolving paths would be shared and used for all settings (not duplicated)--if so, fixing this once for all settings should be straightforward.

**Comment by skprabhanjan** [comment]
@ecraig12345 , CC : @mjbvz 
I agree to the point, So what would be the next step with this issue ?
Thanks :)

**Comment by ecraig12345** [comment]
Did a search and the code to read the raw `typescript.tsdk` setting is [here](https://github.com/Microsoft/vscode/blob/cd5b4d1bb3fc7e509fba077095b2b280b8ff7161/extensions/typescript-language-features/src/utils/configuration.ts#L86) and the code to resolve the path is [here](https://github.com/Microsoft/vscode/blob/92f9f50a93ba278f7bb637386ac1ffcdfd38a55e/extensions/typescript-language-features/src/utils/versionProvider.ts#L162). Part of the path resolution is done with the [RelativePathResolver utility](https://github.com/Microsoft/vscode/blob/92f9f50a93ba278f7bb637386ac1ffcdfd38a55e/extensions/typescript-language-features/src/utils/relativePathResolver.ts), but that's only used within the `typescript-language-features` extension. So unfortunately that means supporting `~` in all setting paths would not be straightforward.

**Comment by mjbvz** [comment]
Thanks @ecraig12345. Yep that all sounds correct

This issue has been discussed in #2809. @sandy081 what are your thoughts about a TS specific workaround? Python and a few other extensions already seem to support paths with `~`, but I don't know if any built-in extensions handle this yet

**Comment by sandy081** [comment]
#2809 is all about supporting variables in settings. Not sure what you mean by TS specific workaround. But one solution I am thinking for #2809 is have an additional API in configuration that returns a resolved value.

**Comment by sandy081** [comment]
@mjbvz Not sure how can this be done only for `tsdk` setting unless we hardcode it in the platform. If so, I would prefer to do it for all and not have inconsistency too.

**Comment by mjbvz** [comment]
@sandy081 The proposal is to have code in the TypeScript extension that reads that string value of `tsdk` and then replaces `~/` with the user's home directory. I think supporting `~/path/to/tsdk` is safer (but less cross-platform) than inventing our own, typescript extension specific variable substitution language, with something like `${home}/path/to/tsdk` 

@skprabhanjan Do you still want to take a look at handling this? As @ecraig12345 mentioned, here's code in the TS extension that would need to be changed (both `extractGlobalTsdk` and `extractLocalTsdk`): https://github.com/Microsoft/vscode/blob/286d1d3a1d0f9323d0be5f5ddfb0e6a336567739/extensions/typescript-language-features/src/utils/configuration.ts#L86

You can use node's [`os.homedir()`](https://nodejs.org/api/os.html#os_os_homedir) to get the home directory.

**Comment by skprabhanjan** [comment]
@mjbvz , I will surely work on this, Was just waiting on your confirmation for going ahead :)
Thanks :)

**Comment by sandy081** [comment]
@mjbvz Ah you want to resolve this in typescript extension. I do not have any issues having your own format, but if #2809 is supported, then we will have support for same variables we already support in debug and tasks land.
