### ISSUE TITLE
Hexadecimal display of a 32-bit value should pad with zeros

### ISSUE THREAD

**Issue by x13pixels** [Microsoft/vscode#64251]
Issue Type: <b>Bug</b>

Open the watch window and use the ",x" suffix to display a 32-bit variable as hexadecimal. Note, for example, that 25165824 displays as 0x1800000 rather then 0x01800000.

This would make it easier to compare values in the watch window if the hex output was a consistent length.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 3.10.0-862.2.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.21GB (19.90GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by weinand** [comment]
VS Code does not format any values. Please file issue against the debugger extension you are using.
