### ISSUE TITLE
Performance Issue submission for #61224

### ISSUE THREAD

**Issue by mjmaldonado** [microsoft/vscode#64258]
@bpasero, per your request on [#61224](https://github.com/Microsoft/vscode/issues/61224)

Issue Type: <b>Performance Issue</b>

I started experiencing issues 19 days ago (11/12).

Since my most recent comment on 11/13, I haven't experienced any problems and the dialogue box has not shown up.

Generally, performance wasn't and isn't bad.  What would happen is the dialog box of "The window is no longer responding" would pop up while working in my Git Bash terminal.  If I said to keep waiting, it wouldn't respond and would eventually crash.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:11:49.509Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.89GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   299	 13200	code main
    0	    55	  1812	   shared-process
    4	   166	  5084	   window (agent-state-detail-report.sql - Visual Studio Code)
    0	     3	  4392	     winpty-process
    0	     1	 11356	       
    0	     6	  7368	         
    0	    66	  5008	     extensionHost
    0	    40	  9844	       
    0	     3	 11208	     electron-crash-reporter
    0	     5	 15612	     winpty-process
    0	     4	  8972	       
    0	    11	  1108	         
    3	    50	 15368	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.21.0
vscode-instant-markdown|dba|1.4.3
code-runner|for|0.9.5
mssql|ms-|1.4.0
python|ms-|2018.11.0
vscode-ai|ms-|0.3.1
azure-account|ms-|0.6.2
team|ms-|1.144.1
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
vscode-icons|rob|7.28.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you try run `code --status` quickly when the window is not responsive? That will tell us is there are some processes that are thrashing the CPU.

**Comment by mjmaldonado** [comment]
If/when it happens again I definitely will.  Thanks for the support thus far.
