### ISSUE TITLE
Add `vscode.startDebugWithoutDebugging`

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6425]
From #4615

Suggestions for better name are welcome

**Comment by isidorn** [comment]
Ping @weinand for possible suggestions

**Comment by isidorn** [comment]
@jcansdale now it will be possible to do the following. Notice the `noDebug` argument which specifies if the start debug should debug or just run

```
vscode.commands.executeCommand('vscode.startDebug', {
            "noDebug": true,
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/hello.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null,
            "internalConsoleOptions": "openOnFirstSessionStart"
        });
```

**Comment by jcansdale** [comment]
Wow, that was quick! :)

BTW, the reason I need to run without the debugger attached, is that when the debugger is attached the node.exe process never exits (VSCode remains in debug mode). Is this by design? Is there an option that would allow the process to exit when the debugger is attached?

**Comment by weinand** [comment]
@jcansdale the problem you are seeing is not a VS Code issue but this node bug: https://github.com/nodejs/node/issues/1788
How would you use the 'run without debug' option to work around ths?

**Comment by jcansdale** [comment]
The process only fails to exit when the debugger is attached. What I'm doing doesn't always require the debugger. It is still an issue when I need the debugger.
