### ISSUE TITLE
Test: Debugging from process explorer

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#64255]
Test for https://github.com/Microsoft/vscode/issues/63147

- [x] anyOS @jrieken
- [x] anyOS @egamma

Complexity: 3

Adds a 'Debug' context menu item to node processes. If an --inspect, --inspect-brk, --debug, or --debug-brk flag is found (with or without port number), a debug session is started against a debug port. If none of the flags are found but the process executable is node a debug session is started via the process ID and the SIGUSR1 mechanism.

**Comment by jrieken** [comment]
Works like a charm - would be even cooler if we can support electron_run_as_node and SIGUSR1

**Comment by egamma** [comment]
Nice!

It is also a convenient way to attach to a node process that you started from the built-in terminal with --inspect.
@weinand this should be documented in our docs as another way for how to debug a node progress.

**Comment by weinand** [comment]
@jrieken if we would stop using Electron's node and shipping an official node.js version, SIGUSR1 would work out of the box...

@egamma yep, makes sense, but I wonder how often regular users would want to open the "VS Code process explorer" to debug their own processes...
