### ISSUE TITLE
Test: GitHub Pull Requests extension

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#64262]
Test for https://github.com/Microsoft/vscode-pull-request-github/issues/678

- [x] macOS @kieferrm
- [x] linux @sandy081
- [x] windows @gregvanl

Complexity: 3

**Set up** 
Install the latest Github Pull Requests extension (0.3.1). The [pullrequest-demo](https://github.com/auchenberg/pullrequest-demo) repo can be used to test against.

**Verify**
The extension now has a "Suggest Edit" command in the SCM context menu. Verify that you can suggest a set of changes by
1. checking out a PR
1. staging some changes
1. optionally adding a message and using the command

This should create a comment on the PR with the diff of those changes, and unstage and revert that set of changes locally.

Then verify the suggested edit can be applied. A button should be displayed on the comment on the PR's description page to apply the changes.

The extension should now show any status checks at the bottom of the description page. 

Please file any issues in https://github.com/Microsoft/vscode-pull-request-github.

// cc @rebornix

**Comment by sandy081** [comment]
Not able to sign in to github from my linux VM. Is there a different mechanism to sign in ?

**Comment by sandy081** [comment]
@roblourens I do not see any errors in console and I have default proxy settings in VS Code.

**Comment by rebornix** [comment]
@sandy081 may I know what's your default browser before? It should work for all browsers as we are just using Uri Handler, if it's not the case, it might be a Code issue.

**Comment by kieferrm** [comment]
@sandy081 @rebornix  the latest insider sets the system proxy to false by default.

**Comment by sandy081** [comment]
@rebornix Its Firefox. But I had some issues with opening firefox in that VM, so it could be related.

**Comment by shana** [comment]
I've tested with GHE and so far everything looks 👍
