### ISSUE TITLE
format selection does not work correctly 

### ISSUE THREAD

**Issue by axe-z** [Microsoft/vscode#64269]
Mac os 10.14.1
Vscode latest 

every function params gets scrammed on formats: 
Post: {  
		author: ( _ , args, ctx, info ) => users.find(user => user.id === _.author ),
        },

becomes : author: (_,args,ctx,info) => users.find(user => user.id === _.author),

params should have spaces, or the option somewhere. Really wished the context menu would have prettier.. The context menu is severely under utilized.

**Comment by jrieken** [comment]
@axe-z what language and what formatter extension is this?

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by axe-z** [comment]
same stuff 
![capture d ecran le 2018-12-05 a 11 04 46](https://user-images.githubusercontent.com/27289270/49526339-9fc6b380-f87d-11e8-92b4-fe31dcf70254.png)
![capture d ecran le 2018-12-05 a 11 04 35](https://user-images.githubusercontent.com/27289270/49526340-9fc6b380-f87d-11e8-9556-832622637926.png)
![capture d ecran le 2018-12-05 a 11 04 27](https://user-images.githubusercontent.com/27289270/49526341-9fc6b380-f87d-11e8-9a62-4c994ae3690a.png)
![capture d ecran le 2018-12-05 a 11 04 17](https://user-images.githubusercontent.com/27289270/49526342-9fc6b380-f87d-11e8-8937-db299a0430a5.png)

**Comment by mjbvz** [comment]
I can't repo this in the current VS Code insiders builds.

Please share some complete example code as text and step-by-step instructions on the exact actions you are performing in the editor

**Comment by axe-z** [comment]
javascript
