### ISSUE TITLE
VS Code stalls for a second or two when triggering suggest on very large js file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64272]
From #63473

0. Use `localityBonus`
1. Open `10000.js` from the repository in #63473 (Either @alexandrudima or I can share this file)
1. Wait for js/ts to finish loading
1. On a blank line near the start of the file, trigger suggestions.

**Bug**
There is a several second long hang for the entire editor. Based on the [profile](https://github.com/Microsoft/vscode/files/2641921/Profile-20181203T170238.json.txt), I see a large number of `WordDistance.creates` happening during the hang:

![screen shot 2018-12-03 at 5 02 11 pm](https://user-images.githubusercontent.com/12821956/49411305-3af44780-f71d-11e8-8e65-5df19f17a9a3.png)

**Comment by jrieken** [comment]
Funny coincidence - I saw this yesterday when working on smart select features. The issue that locality bonus works by using smart select ranges. That appears to be slow in large files... I have added a new provider that is bracket based only, much faster, and more suited for this.

**Comment by jrieken** [comment]
This isn't a regression (we ship locality bonus since summer) and the underlying token tree implementation is unchanged since 4 yrs. As much as I would like to fix this today, it's not a regression and because the changes are bigger it's not worth the risk...
