### ISSUE TITLE
Log levels passed to extension are off by one

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#64273]
Issue Type: <b>Bug</b>

`vscode.env.logLevel`  is supposed to be 1-based (as defined by vscode.LogLevel by reaches the extensions as 0-based value.

VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:12:08.874Z)
OS version: Darwin x64 18.0.0

**Comment by sandy081** [comment]
@roblourens I think you have introduced the `LogLevel` in proposed API, so moving it back to you.

**Comment by roblourens** [comment]
Ok it's been so long I honestly couldn't remember!
