### ISSUE TITLE
Test search via FileSearchProvider and vscode-cached-search-provider lib

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64274]
Test #59922

- [x] Windows @stevencl
- [x] anyOS @jrieken

Complexity: 2

Test that file search via the FileSearchProvider API and the extracted support library works correctly

- Install https://marketplace.visualstudio.com/items?itemName=roblourens.test-search-rg
- Start vscode with `--enable-proposed-api roblourens.test-search-rg`
- Test that quick open search works fine
- Single folder and multiroot scenarios are 👍 
- You can verify that the extension is handling search by setting the log level to "Trace", open `Log (Window)`, do a file search, and you should **not** see logs starting with `SearchService#search rg --files ...` which come from bulitin search

**Comment by jrieken** [comment]
@roblourens the extension is broken because it misses the extension.js file...

**Comment by jrieken** [comment]
I have created a vsix locally after cloning https://github.com/roblourens/test-search-rg. 🤞 that I am testing the right thing now...

[test-search-rg-0.0.3.vsix.zip](https://github.com/Microsoft/vscode/files/2643433/test-search-rg-0.0.3.vsix.zip)

**Comment by roblourens** [comment]
Yeah, sorry guys. Thanks @jrieken that's right. And @stevencl I forgot that the extension would only work on the platform that I published it on...

@stevencl Please test with these steps:

- Clone https://github.com/roblourens/test-search-rg
- npm install
- Run the "Extension" launch config
