### ISSUE TITLE
[Test] SignatureHelpContext

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64278]
Test for #54972

- [x] Any OS @rebornix 
- [x] Any OS @weinand (macOS and linux)

Complexity: 3

**Summary**
Signature help provides now take a context object that includes information about how the provider was triggered. 

Signature help providers can now also be registered with a distinct set of `trigger` characters and `reTrigger` characters. Re-trigger characters are only fired when signature help is already showing.

**Test**
* Read through the `vscode.d.ts` docs on the signature help provider context and try implementing a basic provider. Make sure the documentation makes sense and that the received context is what you would expect.

*  Try using the re-trigger characters for your provider. Confirm they effect how signature help is triggered as you would expect

**Comment by weinand** [comment]
@mjbvz could you please points us to a sample as a starting point.

Please see [here](https://github.com/Microsoft/vscode/issues/64229) how I try to help testers to be successful within a reasonable amount of time (that actually corresponds the complexity).

**Comment by weinand** [comment]
@mjbvz that's helpful, thanks a lot.

**Comment by weinand** [comment]
@mjbvz works great; found only minor issue #64432 in API doc.

**Comment by rebornix** [comment]
The documentation and API work fine to me.
