### ISSUE TITLE
Problems with Cut/Paste shortcut

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#6428]
- VSCode Version: 1.1.1 (insider)
- OS Version: Windows 10

Steps to Reproduce:

1. Select some text with the keyboard
2. Press ctrl+x to cut the text
3. Move the keyboard somewhere else using the cursor keys
4. Press ctrl+v to paste the text

What happens: the text is correctly removed from the editor (step 2) but it isn't pasted at the cursor position

What should happen: text from clipboard should be appended at mouse position

It happened already a few times to. Unfortunately I didn't find a pattern yet.

Note that attempting to paste the text in another app doesn't work either so it seems the problem is in the cut action which for some reason doesn't work correctly: the text is correctly removed from my editor but isn't in the clipboard.

This has been happening for at least 3 updates of VSCode.

**Comment by alexandrudima** [comment]
@warpdesign Does this issue reproduce when running `code --disable-extensions` (i.e. could it be cause by an extension that hijacks `ctrl+x`?). Is it possible that you have installed some other software on your machine that might interact with/watch the clipboard?

**Comment by warpdesign** [comment]
I just noticed I have installed clip-x: that's a Windows app which keeps the clipboard history.

I don't think I have any VSCode extension that interacts with the clipboard.

I have disabled Clip-X to see if it's causing the problem (I noticed that when I encounter the bug, I have an empty entry in clip-x).

Then I'll start VSCode with extensions disabled if I'm still having the problem.

**Comment by warpdesign** [comment]
@alexandrudima After having disabled `clip-x` I no longer had the problem. I guess the problem wasn't with VSCode after all.
