### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by ishrathkkm** [Microsoft/vscode#64287]
Issue Type: <b>Bug</b>

intellisense not working sometimes for automatic import 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.38GB (18.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.20
beautify|Hoo|1.4.7
d3-js-snippets|Hri|1.0.0
Angular2|joh|7.0.1
d3-helpers-snippets|led|0.4.1
Angular-BeastCode|Mik|7.0.18
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.11.1
d3-skeletons|noa|0.0.2
typescript-hero|rbb|3.0.0
D3Snippets|yoy|0.1.11

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
