### ISSUE TITLE
[Test] Menu bar refactor does not regress behavior

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#64282]
Test for #63954 
- [x] macOS @Tyriar
- [x] windows @sandy081
- [x] linux @rebornix

Complexity: 4

**Summary**
This iteration, there was some refactoring of the menu bar code in order to separate much of the VS Code workbench related logic from the menu bar widget itself. This work was merged in PR #63954. While this PR contains the overflow logic as well, this test item is meant to test that the menu bar has not regressed with the new code structure.

**Testing**
Please verify:
- The menu bar functions as expected with both the native and custom title bar setting.
- The menu bar functions as expected with all menu bar visibility settings.
- Try the above in full screen and zen mode.
- The menu bar is populated quickly on launch and functions if you select an item.
- The menu bar updates enablement and shortcuts appropriately. Not every item does this so the best thing to test this with is the terminal menu and updating keyboard shortcuts.
- macOS specific, the menu bar works when no windows are open.
- windows/Linux specific, the mnemonics work and can be disabled.

**Comment by Tyriar** [comment]
Tested with OSS build due to https://github.com/Microsoft/vscode/pull/64365
