### ISSUE TITLE
Lines and file sidebar and bottom status bar is being displayed as dots after installing new VGA Card

### ISSUE THREAD

**Issue by tomavic** [Microsoft/vscode#64283]
I ran into ambiguous problem, After installing new Nivida Geforce VGA card and new LG screen, I opened Vscode then I found this

![image](https://user-images.githubusercontent.com/17650005/49416622-48441d00-f783-11e8-9e36-631d79cd6237.png)

![image](https://user-images.githubusercontent.com/17650005/49416819-f0f27c80-f783-11e8-9168-78cfd4e0709b.png)

Previously I was running old screen and Intel built in VGA card, and I didn't see that happened before
I tried the following:

- Change theme to light
- Disable all plugins
- Add settings `"editor.disableTranslate3d": true`  (It's saying that unknown configuration settings, but I kept it anyway)

But all Failed! 

The only solution left, is to install  an older version!

- VSCode Version: 1.29
- OS Version: Windows 10 x64

Could anyone please help?

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by tomavic** [comment]
Aha! That orange label :+1: 

I downloaded it and will try with/without plugins and themes. I don't know actually where the problem comes from. So I exclude any relation with the new VGA or LG screen. What do you think @bpasero

**Comment by bpasero** [comment]
👍

**Comment by tomavic** [comment]
@bpasero I tried this over the last week and installed the most recommended extensions, and the issue still the same
