### ISSUE TITLE
workspace setting doesn't work.

### ISSUE THREAD

**Issue by ladyrick** [Microsoft/vscode#64284]
Issue Type: <b>Bug</b>

I had set in user setting
```
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
```
and in workspace setting
```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
```
But when I open a new terminal, it's still git-bash.
Open cmd.exe is expected.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.46GB (8.81GB free)|
|Process Argv|E:\rick\Desktop|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.29.2

</details>

**Comment by Tyriar** [comment]
It's a security feature, run this command:

<img width="341" alt="screen shot 2018-12-04 at 2 12 58 pm" src="https://user-images.githubusercontent.com/2193314/49476486-fd4ff700-f7ce-11e8-8a5f-e560a2f5332a.png">
