### ISSUE TITLE
insider 1.30.0 : UI abnormal

### ISSUE THREAD

**Issue by MrHuangJser** [Microsoft/vscode#64292]
- VSCode Version: insider 1.30.0
- OS Version: MacOS 10.14.1

Steps to Reproduce:

1.upgrade vscode insider to 1.30.0
2. open vscode
3.![image](https://user-images.githubusercontent.com/20551693/49423860-c3352400-f7d3-11e8-8c2e-1ae04f4b32bd.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by MrHuangJser** [comment]
ps: can't find anything in the control panel
![image](https://user-images.githubusercontent.com/20551693/49424227-f0ce9d00-f7d4-11e8-890b-43955dbb73e5.png)
also can't open dev tool panel

**Comment by royling** [comment]
same problem here.

**Comment by bm-stschneider** [comment]
For a quick fix here a link to the previous build
https://az764295.vo.msecnd.net/insider/9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096/VSCode-darwin-insider.zip

**Comment by MrHuangJser** [comment]
> For a quick fix here a link to the previous build
> https://az764295.vo.msecnd.net/insider/9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096/VSCode-darwin-insider.zip
> Adjust the link for your os.

have been fix

**Comment by jrieken** [comment]
We have unpublished latest insiders so that things should be back at a working state

**Comment by joaomoreno** [comment]
All of the occurrences I've seen are macOS only.

I also cannot repro on Windows.
