### ISSUE TITLE
Windows not displaying properly

### ISSUE THREAD

**Issue by Erchamion** [Microsoft/vscode#64295]
- VSCode Version: 1.30.0-insider
- OS Version:  MacBook Pro High Sierra 10.13.6

Steps to Reproduce:

1. Get Latest update (07202fb)
2. On restart of VSCode the window layouts are not displaying properly.  See attached screenshot.
<img width="1280" alt="screen shot 2018-12-04 at 2 03 56 am" src="https://user-images.githubusercontent.com/11239968/49424572-027a5b00-f769-11e8-87c6-8a41203efc07.png">

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by TreTuna** [comment]
Insiders just broke... Duplicate of https://github.com/Microsoft/vscode/issues/64292
