### ISSUE TITLE
Cannot start VS code when running a VPN firstly

### ISSUE THREAD

**Issue by BiliKid** [Microsoft/vscode#64290]
- VSCode Version: 1.29.1
- OS Version:  windows 7 SP1

Steps to Reproduce:

1. running a SSL VPN firstly, and I cannot start vs code with no error information.

but after run the "netsh winsock reset"  in windows cmd.exe, and then I could start VS code again. 

This was happened after I took a update, but I cannot remember the specific vision of VS code.

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by BiliKid** [comment]
- there is not output of `code --verbose`
- I cannot start Code , how to open Console
- When I start Code after running `netsh winsock reset`, and then open Console, the output:

> /C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] REMOTE_WORKSPACE_PATH= c:/Users/Administrator/AppData/Roaming/Code/User/ftp-simple/remote-workspace-temp
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1446  INFO standard startup
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] ftp-simple start
workbench.main.js:sourcemap:294 [Extension Host] ApplicationInsights:CorrelationIdManager [{…}]
t.log @ workbench.main.js:sourcemap:294
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3173
(anonymous) @ workbench.main.js:sourcemap:3169
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180

**Comment by BiliKid** [comment]
I compare the output of `netsh winsock show catalog` before and after, I attach the difference, that may be helpful.

> 
Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [MSAFD Tcpip [TCP/IP]]
提供程序 ID:                        {62816A64-DAC2-48DD-B3AD-843C916DDF82}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1019
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x20066
协议链长度:                         2
协议链: 1018 : 1004


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [MSAFD Tcpip [UDP/IP]]
提供程序 ID:                        {F3A080B4-019D-4501-8647-B59695478F9F}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1020
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x20609
协议链长度:                         2
协议链: 1018 : 1005


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [MSAFD Tcpip [RAW/IP]]
提供程序 ID:                        {0B0D29E6-9BD1-4465-9C10-130ED23E363D}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1021
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        3
协议:                               0
服务标志:                           0x20609
协议链长度:                         2
协议链: 1018 : 1006


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [RSVP TCP 服务提供商]
提供程序 ID:                        {C16D9663-8476-4AAC-A3DD-D4F5163FEEFC}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1022
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x22066
协议链长度:                         2
协议链: 1018 : 1008


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [RSVP UDP 服务提供商]
提供程序 ID:                        {EFAF7E21-020D-4B49-A9B2-A8CD43C1EC6C}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1023
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x22609
协议链长度:                         2
协议链: 1018 : 1010


Winsock 目录提供程序项
------------------------------------------------------
------------------------------------------------------
项类型:                             分层服务提供程序
描述:                               SangforLSP_x64
提供程序 ID:                        {C5FABBD0-9736-11D1-937F-00C04FAD860D}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1018
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        0
协议:                               0
服务标志:                           0x20066
协议链长度:                         0

Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [MSAFD Tcpip [TCP/IP]]
提供程序 ID:                        {9A816D90-4627-4C77-B107-31714436AE34}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1013
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x20066
协议链长度:                         2
协议链: 1012 : 1004


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [MSAFD Tcpip [UDP/IP]]
提供程序 ID:                        {748B6248-E917-450C-A2D3-09641B7895EA}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1014
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x20609
协议链长度:                         2
协议链: 1012 : 1005


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [MSAFD Tcpip [RAW/IP]]
提供程序 ID:                        {165F6921-B42A-4719-ABBF-0CA9D44D8E5B}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1015
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        3
协议:                               0
服务标志:                           0x20609
协议链长度:                         2
协议链: 1012 : 1006


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [RSVP TCP 服务提供商]
提供程序 ID:                        {F49BFD08-C206-43A4-ABB5-FFDF3A76D999}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1016
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x22066
协议链长度:                         2
协议链: 1012 : 1008


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [RSVP UDP 服务提供商]
提供程序 ID:                        {45783F62-CB90-4964-B851-84281072560B}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1017
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x22609
协议链长度:                         2
协议链: 1012 : 1010


Winsock 目录提供程序项
------------------------------------------------------
Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层服务提供程序(32)
描述:                               SangforLSP
提供程序 ID:                        {C5FABBD0-9736-11D1-937F-00C04FAD860D}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1012
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        0
协议:                               0
服务标志:                           0x20066
协议链长度:                         0

**Comment by BiliKid** [comment]
I compare the output of `netsh winsock show catalog` before and after, I attach the difference, that may be helpful.

> 
Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [MSAFD Tcpip [TCP/IP]]
提供程序 ID:                        {62816A64-DAC2-48DD-B3AD-843C916DDF82}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1019
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x20066
协议链长度:                         2
协议链: 1018 : 1004


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [MSAFD Tcpip [UDP/IP]]
提供程序 ID:                        {F3A080B4-019D-4501-8647-B59695478F9F}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1020
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x20609
协议链长度:                         2
协议链: 1018 : 1005


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [MSAFD Tcpip [RAW/IP]]
提供程序 ID:                        {0B0D29E6-9BD1-4465-9C10-130ED23E363D}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1021
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        3
协议:                               0
服务标志:                           0x20609
协议链长度:                         2
协议链: 1018 : 1006


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [RSVP TCP 服务提供商]
提供程序 ID:                        {C16D9663-8476-4AAC-A3DD-D4F5163FEEFC}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1022
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x22066
协议链长度:                         2
协议链: 1018 : 1008


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项
描述:                               SangforLSP_x64 over [RSVP UDP 服务提供商]
提供程序 ID:                        {EFAF7E21-020D-4B49-A9B2-A8CD43C1EC6C}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1023
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x22609
协议链长度:                         2
协议链: 1018 : 1010


Winsock 目录提供程序项
------------------------------------------------------
------------------------------------------------------
项类型:                             分层服务提供程序
描述:                               SangforLSP_x64
提供程序 ID:                        {C5FABBD0-9736-11D1-937F-00C04FAD860D}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\31_SangforTcpX64.dll
目录项 ID:                          1018
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        0
协议:                               0
服务标志:                           0x20066
协议链长度:                         0

Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [MSAFD Tcpip [TCP/IP]]
提供程序 ID:                        {9A816D90-4627-4C77-B107-31714436AE34}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1013
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x20066
协议链长度:                         2
协议链: 1012 : 1004


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [MSAFD Tcpip [UDP/IP]]
提供程序 ID:                        {748B6248-E917-450C-A2D3-09641B7895EA}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1014
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x20609
协议链长度:                         2
协议链: 1012 : 1005


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [MSAFD Tcpip [RAW/IP]]
提供程序 ID:                        {165F6921-B42A-4719-ABBF-0CA9D44D8E5B}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1015
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        3
协议:                               0
服务标志:                           0x20609
协议链长度:                         2
协议链: 1012 : 1006


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [RSVP TCP 服务提供商]
提供程序 ID:                        {F49BFD08-C206-43A4-ABB5-FFDF3A76D999}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1016
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        1
协议:                               6
服务标志:                           0x22066
协议链长度:                         2
协议链: 1012 : 1008


Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层链项(32)
描述:                               SangforLSP over [RSVP UDP 服务提供商]
提供程序 ID:                        {45783F62-CB90-4964-B851-84281072560B}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1017
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        2
协议:                               17
服务标志:                           0x22609
协议链长度:                         2
协议链: 1012 : 1010


Winsock 目录提供程序项
------------------------------------------------------
Winsock 目录提供程序项
------------------------------------------------------
项类型:                             分层服务提供程序(32)
描述:                               SangforLSP
提供程序 ID:                        {C5FABBD0-9736-11D1-937F-00C04FAD860D}
提供程序路径:                       C:\Program Files (x86)\Sangfor\SSL\ClientComponent\3_SangforTcp.dll
目录项 ID:                          1012
版本:                               2
地址族:                             2
最大地址长度:                       16
最小地址长度:                       16
Socket 类型:                        0
协议:                               0
服务标志:                           0x20066
协议链长度:                         0
