### ISSUE TITLE
#region do not work for *.vue in typescript

### ISSUE THREAD

**Issue by kenny0002** [Microsoft/vscode#64303]
I want to use region&endregion, but not work for *.vue ( in typescript script ). 

My code:
<script lang="ts">
import { Vue, Component, Prop, Watch } from "vue-property-decorator";
@Component
export default class Index extends Vue {
  //#region props

  /** Data Source*/
  @Prop({ type: Array, required: true })
  source?: any[];

  //#endregion
}
</script>

**Comment by mjbvz** [comment]
Please file this against the vetur extension
