### ISSUE TITLE
Process Explorer Open in FullScreen

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64306]
* macOS
* run in fullscreen mode
* open the process explorer
* 🐛 the prices explorer window also opens in fullscreen mode...

**Comment by agurodriguez** [comment]
Hi 👋🏽

Gonna take a look at this. It seems to be happening for 'Report issue' also.

**Comment by agurodriguez** [comment]
Hi @RMacfarlane. Can I help you somehow to get this merged?

**Comment by RMacfarlane** [comment]
@agurodriguez Yep! Sorry for the delay, your change looks good. I'll merge it now. Thanks!
