### ISSUE TITLE
VScode 能使用 WSL中安装的Git&Python

### ISSUE THREAD

**Issue by insrce** [Microsoft/vscode#64308]
网上有支持：http://blog.plusls.cn/windows/vscode-using-python-in-wsl/
但不够完整，期望官方给予这些功能.
期待：VScode 能直接使用 WSL 下安装的 Git/Python/PHP等。利于集成开发

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
