### ISSUE TITLE
[scss] Uncorrect backlight of SCSS extends

### ISSUE THREAD

**Issue by nikober** [microsoft/vscode#64304]
Issue Type: <b>Bug</b>

like this -

  .digit-sm{
      @extend .digit
  }
  .digit-md{
      @extend .digit
  }
  .digit-lg{
      @extend .digit;
  }

**Comment by octref** [comment]
Well if you wrote standard SCSS, that is, with `;` at the end, then the syntax highlight is fine.

**Comment by dsifford** [comment]
@octref Actually it is not. 

Take a look at the scopes of the syntax...

```
  .thing {
      @extend .foo-bar-baz;
//                ^   ^........source.css.scss meta.property-list.scss meta.at-rule.extend.scss support.constant.mathematical-symbols.scss
//            ^^^^ ^^^ ^^^.....source.css.scss meta.property-list.scss meta.at-rule.extend.scss
  }
```

### Two Problems:
1. Dashes **should not** be receiving `mathematical-symbol`
2. Class name selectors **should** be receiving `entity.other.attribute-name.class.css`

**Comment by octref** [comment]
OK, that makes sense.

**Comment by octref** [comment]
Upstream issue, I reported https://github.com/atom/language-sass/issues/272.

**Comment by aeschli** [comment]
Upstream issue got closed
