### ISSUE TITLE
PPA/deb package out of date

### ISSUE THREAD

**Issue by furai** [Microsoft/vscode#64300]
Hello,

It seems that there are no recent builds of VSCode. 

https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/

They stopped like a week ago. Is it intended?

Cheers,
Furai

**Comment by Tyriar** [comment]
Thanks for the report, we're investigating.

**Comment by chrmarti** [comment]
Started working again. An internal certificate didn’t verify.

**Comment by rajinder-yadav** [comment]
It worked for me and then stopped again.

**Comment by chrmarti** [comment]
@rajinder-yadav `code-insiders_1.30.0-1544221759_amd64.deb` i the latest insiders build and it is listed in our repository: https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders

What do you get for `apt-cache policy code-insiders | head`?
