### ISSUE TITLE
Ctrl + click to follow link in scss when imporing file contains a dash in name

### ISSUE THREAD

**Issue by BeklievParviz** [Microsoft/vscode#64316]
Issue Type: <b>Bug</b>

Here's the screenshot:
https://yadi.sk/i/Uq14W8bS3jmTog

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (5 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|64.00GB (21.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
githistory|don|0.4.4
gitlens|eam|9.0.1
prettier-vscode|esb|1.7.2
vscode-language-pack-ru|MS-|1.29.2

</details>

**Comment by octref** [comment]
Thanks for the great illustration! It's tracked in https://github.com/Microsoft/vscode/issues/58204.
