### ISSUE TITLE
Loaded scripts should have a collapse all action

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#64314]
Refs: #64230

As other debug views that are trees the loaded scripts view should have a Collapse All action in the top of the view.
Here's a code pointer to the action https://github.com/Microsoft/vscode/blob/07202fbfb82bdada89472dd4b1c3c699b0eab0b4/src/vs/workbench/browser/viewlet.ts#L188

**Comment by jnnklhmnn** [comment]
I'd like to give this a shot 🎉
