### ISSUE TITLE
compareItemByScore blocks extension host

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#64312]
re #64274

* run quick open on a huge workspace
* notice the extension is unresponsive and has been profiled
* see that `roblourens.test-search-rg` is using most time running `compareItemByScore`

<img width="718" alt="screenshot 2018-12-04 at 11 44 36" src="https://user-images.githubusercontent.com/1794099/49436744-2ca83900-f7ba-11e8-801f-5d5d6af551d8.png">

[exthost-39af76.cpuprofile.zip](https://github.com/Microsoft/vscode/files/2643572/exthost-39af76.cpuprofile.zip)

**Comment by roblourens** [comment]
It should not be unresponsive because this code yields sometimes to allow other work to happen. How does the EH get detected as unresponsive and after how much time is it considered unresponsive?

**Comment by jrieken** [comment]
The extension host sends and ACK after each message we send it. If that doesn't happen within 3 secs we start profiling until the extension host is responsive again but no longer than 5 seconds. In your profile didn't block the full 3+5 seconds but around 3+3 and above function is the culprit - it ran for seconds sorting or comparing

**Comment by jrieken** [comment]
Not sure what you wanna "discuss" here but I think such high CPU load is a clear sign that we should consider moving things from the extension into a separate executable - just like we have done it already for the current connected-to-renderer solution.

**Comment by roblourens** [comment]
I still think that when someone is in a quickopen session they aren't doing other things at the same time, and so blocking the EH process here for a couple seconds isn't inherently an issue. At least not enough to justify the extra latency, memory usage, and complexity of doing this in a new process. But we should tweak it so it doesn't trigger the unresponsive EH warning.

**Comment by connor4312** [comment]
Is this still relevant? Doesn't look like there's a `compareItemByScore`, and I think that the match limit currently in place prevents this from happening

**Comment by roblourens** [comment]
This is about whether search should run in its own process or the EH directly (like it does in remote). This is discussed in other issues.
