### ISSUE TITLE
Add a command to clear input

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#64315]
Should work in any input: Settings search, Keybindings search, Extensions search, Find Widget, Quick Pick ...

**Comment by roblourens** [comment]
Eh, is it really necessary?

**Comment by usernamehw** [comment]
I'm going to fallback to `autohotkey` for this one. Will be useful not only for vscode.

```autohotkey
CapsLock & Space::
SendInput, ^a
SendInput, {Backspace}
return
```
