### ISSUE TITLE
Automatic extension host profiling does not work if debugging extension

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64322]
Refss: #64222

Have an extension which causes heavy cpu load. Debug that extension and start the command which causes the cpu load.
No notificaiton that the extension host is taking a hit from your extension.

After discussins with @jrieken 
This happens beacuse the extension host allows only one connection, and we can not profile it since the debug is already attached.
In this case we should at least print a message that we failed to profile so the extension author would not get confused.

**Comment by jrieken** [comment]
Actually, I am not sure that we can do anything here. When debugging you are likely causes slowness yourself. So even a warning/log-message might be misleading.

**Comment by isidorn** [comment]
I am fine with not tacklign this for November and we see if actualy extension authors complain about this in the future.

**Comment by jrieken** [comment]
> I am fine with not tacklign this for November 

I wouldn't know what to do in November, December or any other month. For us a paused (on breakpoint) extension host appears as unresponsive and we shouldn't show a warning message then. What would that be? "Extension host is unresponsive. If you are debugging ignore this message, iff not we can also not help you..."

**Comment by isidorn** [comment]
If you can not do anything I suggest to at least pring a message in the console that you can not connect.
