### ISSUE TITLE
Allow to theme native link tooltips

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#64327]
This is more a FYI than a bug:
On Elementary OS (Juno) native hovers are black which results in a discrepancy with VS Code's custom hovers:
https://user-images.githubusercontent.com/1898161/49442612-4cdff400-f7ca-11e8-8f2e-74473bd9bb67.gif

It would be nice if hovers would be consistent within VS Code (even if that doesn't match the style of the underlying platform).

/cc @misolori @aeschli @bpasero

**Comment by isidorn** [comment]
This is not debug specific. But holds true for all our vscode hovers.
Assigning to @misolori to decide if we should do something here
fyi @bpasero

**Comment by misolori** [comment]
Are we able to control the menu styling here for the native menu tooltip? Similar to how Windows uses the same menu style across all hovers we should try to make it consistent here (if we can).

**Comment by isidorn** [comment]
Well we can not change the native hover. But we can change all vscode hovers to match the native ones.
That is what this feature request now reflects I would say.

**Comment by misolori** [comment]
That will be interesting, especially with intellisense hovers as it contains syntax highlighting and can wrap to multiple lines.

**Comment by weinand** [comment]
Actual I suggested the opposite:
> It would be nice if hovers would be consistent within VS Code (even if that doesn't match the style of the underlying platform).
