### ISSUE TITLE
Sequence of opens and closes leads to open folder not being restored

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#64323]
Found testing: #64143

Repro:
Open a folder in VS Code
Open another instance of VS Code. It will correctly open without a folder.
Close the first instance of VS Code
Open a new instance of VS Code

Expected: The new instance should open the originally folder. 
Actual: The new instance opens without a folder.

**Comment by bpasero** [comment]
@alexr00 I am not sure I would agree and I am not sure this is a bug. When you close the first instance, there is no notion anymore of a window that had that folder opened, right? So why should opening another instance restore that folder instead of opening empty?

**Comment by alexr00** [comment]
The only reason the second instance of VS Code opened without a folder was because the first one already had a folder open.  I still expected VS Code to remember that I was last using that folder.

That said, I'm not sure this is a bug either. It might just be bad user expectations :)

**Comment by bpasero** [comment]
@alexr00 in that last step "Open a new instance of VS Code", how do you open that instance?
