### ISSUE TITLE
VSCode Suddenly closes when updating

### ISSUE THREAD

**Issue by augusto630** [Microsoft/vscode#64321]
- VSCode Version: 1.29.1
- OS Version: Windows 10 Pro Version: 1703 Build: 15063.1418

Steps to Reproduce:

1. Select "Update" when update prompt appears, 
2. Request for restart VSCode appears, select "restart later"
3. Close VSCode after some time
4. Open VSCode (no prompt regarding whether is updating or not)
5. VSCode suddenly closes (update is applied and it works normally if opened again)

Thanks

**Comment by joaomoreno** [comment]
What is the timespan between 3 and 4?
