### ISSUE TITLE
windows Blank

### ISSUE THREAD

**Issue by binperson** [Microsoft/vscode#64337]
- VSCode Version: 1.30
- OS Version: windows 10

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/13867836/49447319-30b37580-f811-11e8-868d-c747d5010d49.png)

Blank！！！

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
