### ISSUE TITLE
Toggle Word Wrap does not use user setting editor.wrappingColumn

### ISSUE THREAD

**Issue by The-New-Guy** [Microsoft/vscode#6433]
- VSCode Version: 1.1.1
- OS Version: Windows 10 (Build 10586.318)

Steps to Reproduce:
1. Set user setting `"editor.wrappingColumn": 80` .
2. Code in editor with a really long line wraps correctly after 80 characters.
3. Press Alt+Z to toggle Word Wrap, editor now switches to View Port width wrapping.
4. Press Alt+Z again, editor now turns of word wrapping.
5. Press Alt+Z again, editor now turns on View Port width wrapping.

I'm guessing this is by design at the moment but it would be nice if at least one of the Alt+Z presses would switch me back to word wrapping as specified by my user settings file.

This issue may be moot for me at least if the following feature request is completed as I only need this for Markdown files.  #2253

**Comment by Bill-Stewart** [comment]
In my opinion the behavior should be something like the following:

`wordWrap` | `wrappingColumn` | Effect
-----------|----------------------|------
`false`        | <any value>            | no wrapping
`true`        | 0                              | wrap at viewport
`true`        | > 0                          | wrap at specified column

If vscode adopts the behavior in this table, the defaults would be `editor.wordWrap: true` and `editor.wrappingColumn: 300`.

I find it non-intuitive and confusing that when `wordWrap` is `false` there is sometimes wrapping, and when `wordWrap` is `true` there is sometimes not wrapping.

**Comment by alexandrudima** [comment]
The wrapping settings will get an overhaul with #21262
