### ISSUE TITLE
Auto create issue title for automatic extension host profiling

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64339]
Refs: #64222

After the extension has been flaged as slow if the user clicks the Report Issue button the issue is created in the proper location.
However it does not have a title. As we have seen from our unlucky experiment couple of milestones back users are usually in this case were uncreative when assigning a title since they are not sure what is going on.
To prevent that and to make it easier for extension authors to group issues like this I sugggest we auto create the issue with the following title
"Extension makes extension host unresponsive"
Or just "Extension host unresponsive"

**Comment by jrieken** [comment]
> However it does not have a title. As we have seen from our unlucky experiment couple of milestones back users are usually in this case were uncreative when assigning a title since they are not sure what is going on.

Do you know how that works with GH issue links?

**Comment by isidorn** [comment]
@jrieken I do not, but looking at @RMacfarlane code here
https://github.com/Microsoft/vscode/blob/07202fbfb82bdada89472dd4b1c3c699b0eab0b4/src/vs/code/electron-browser/issue/issueReporterMain.ts#L811

It seems you can just add `title=`. Though to be precise I would try to reuse that code

**Comment by jrieken** [comment]
I will give it a try

**Comment by jrieken** [comment]
Learnt something!
