### ISSUE TITLE
Search viewlet hides replace box when using Ctrl Shift F

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#64330]
Testing #64270

1. Open Search viewlet
2. Show Replace box
3. Open a file, select some text and <kbd>Ctrl Shift F</kbd>

The replace box is now gone!

**Comment by roblourens** [comment]
This is by design. If you want to search/replace, use cmd+shift+h.

Otherwise it's impossible to get rid of the replace box with the keyboard.
