### ISSUE TITLE
Error when typing character in quick open

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#64335]
Issue Type: <b>Bug</b>

When typing in a character in quick open, I get the following error after each character:

spawn C:\Users\stevencl\.vscode-insiders\extensions\roblourens.test-search-rg-0.0.3\node\_modules\vscode-ripgrep\bin\rg.exe ENOENT

While testing https://github.com/Microsoft/vscode/issues/64274

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:34:30.209Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.98GB free)|
|Process Argv|--enable-proposed-api roblourens.test-search-rg azure-cosmosdb-sdk-environment|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.11.0
test-search-rg|rob|0.0.3

</details>

**Comment by roblourens** [comment]
It was only published with the macOS ripgrep binary, see https://github.com/Microsoft/vscode/issues/64274#issuecomment-444213248
