### ISSUE TITLE
watches view: "collapse all" issue

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64332]
testing #64003:

- add a watch expression "x"
- add a watch expression "a"
- run this program on linux:
```ts
var x = { abc: 123 };

x['foo bar'] = "1";
x[' foo'] = "2";
x['  foo'] = "3";

const a = [];

for (var i = 0; i < 1000; i++) {
	a[i] = i;
}

debugger;
```
- drill down into array and expand range notes
- press "collapse all" button

Observe:
not everything is collapsed

The same works fine in stable

**Comment by isidorn** [comment]
This works fine for me.
@weinand let me know what you are doing differenetly than me. Can you repro consistentnly

![collapseall](https://user-images.githubusercontent.com/1926584/49522711-8f77fe00-f8a8-11e8-9a7c-799cbffc3efa.gif)

**Comment by weinand** [comment]
Initially I was seeing this on linux. 
I tried this today, and could reproduce this: it occurs on every second try.

Then I tried to reproduce this on macOS and I see a similar pattern: every third try results in the problem:
![screen recording 2018-12-05 at 16 29 59 2018-12-05 16_31_39](https://user-images.githubusercontent.com/1898161/49524181-92c0b900-f8ab-11e8-942e-9e9e8ac54c84.gif)

and the next try had the same problem:
![screen recording 2018-12-05 at 16 35 30](https://user-images.githubusercontent.com/1898161/49524479-1e3a4a00-f8ac-11e8-8811-93029c3f30f1.gif)

**Comment by isidorn** [comment]
This looks like a tree issue. Assigning also to @joaomoreno 
I am simple calling `tree.collapseAll`

**Comment by isidorn** [comment]
Some candidate for duplicates https://github.com/Microsoft/vscode/issues/63627 and https://github.com/Microsoft/vscode/issues/64074
So best to try to repro out of source

**Comment by joaomoreno** [comment]
@weinand I don't think this repros any more since https://github.com/Microsoft/vscode/commit/1e3e06ae9d6186b10f751d9b6a5bfa2445af7198

Can you give it a retry?

**Comment by weinand** [comment]
yep, works now. 
And something else has changed (which I did not notice before): the "watch" expressions do not auto-expand when they are evaluated. And this seems to be the correct behavior (verified with Stable).

**Comment by joaomoreno** [comment]
Thank you!
