### ISSUE TITLE
Automatic extension host issue should contain a link to explanation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64340]
Refs: #64222

Automatic issue creation should have a link in the issue to our docs or at least release notes where we explain how we auto detect bad extensions by doing profiles.
This way the extension owner will not be puzled and will figure out why his extension got flagged.

The doc should explain how to use the cpu profile and what the extension author should do once he gets an issue like this.

**Comment by jrieken** [comment]
Not sure how much information can be put in there..

**Comment by jrieken** [comment]
I have started this wiki page. @gregvanl please review: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by gregvanl** [comment]
@jrieken I did an edit pass. Looks good.

**Comment by jrieken** [comment]
Thanks
