### ISSUE TITLE
input variables: pressing esc should abort task without generating error notifications 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64342]
testing #64214:

If a user presses ESC to cancel a dialog, I suggest to abort the whole task silently.
Interpreting the result of an cancelled input dialog as an empty string is not helpful.

Using ESC for the node process picker even generates this error:
 
![screenshot 2018-12-04 at 15 34 29](https://user-images.githubusercontent.com/1898161/49449083-6d17af00-f7da-11e8-93a6-e8d6b2f952a6.png)

**Comment by alexr00** [comment]
This makes sense to do.
