### ISSUE TITLE
Running extensions view needs UX love

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#64344]
Refs: #64222

F1 > Show running extensions

You see a view which was done by @alexandrudima @jrieken and me in one afternoon without a lot of UX thinking.
If we are going to navigate users to this view (which we now do - check #64222 for details) I believe it needs more UX thinking and love.
First we should figure out if this should be integreted in the extensions viewlet or it deserves to be a seperate view. After we figure that out we should design this with some more love.

**Comment by misolori** [comment]
Totally agree, I've already added this to the UX backlog :smile:

**Comment by isidorn** [comment]
@misolori that's great to hear. I would be happy to provide feedback and potentially do engineering work after we decide what needs to be done.
I would guess @jrieken also has thoughts to share.

**Comment by usernamehw** [comment]
What about features? It would be nice to sort extensions by `Activation`/`Startup Activation` to find the most hungry of them quicker.

**Comment by isidorn** [comment]
Yeah I guess we should also add some features.
But there are some things which the view already does well, so I would first be intrerested in just making those clearer / nicer before we add functionality on top.

**Comment by misolori** [comment]
The plan was to have this solved by https://github.com/microsoft/vscode/issues/68527 with a "Running" tab + actions. Will close this in favor of that one.
