### ISSUE TITLE
Tree view message: Does not wrap

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#64348]
Issue Type: <b>Bug</b>

Testing #64205

![dec-04-2018 15-41-31](https://user-images.githubusercontent.com/9205389/49449486-4a39ca80-f7db-11e8-8ab8-2f94dbaa0498.gif)

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
It does wrap in references view. Can you provide your message to reproduce

**Comment by chrmarti** [comment]
It stops at the longest non-wrapping part:
```ts
tree.message = new MarkdownString(`[Refresh](command:githubIssuesPrs.refresh) &

- [PRs](https://www.microsoft.com)
- Other

Markdown | Less | Pretty
--- | --- | ---
*Still* | \`renders\` | **nicely**
1 | 2 | 3

Here's our logo (hover to see the title text):

Inline-style: 
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")

Reference-style: 
![alt text][logo]

[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"

\`\`\`javascript
var s = "JavaScript syntax highlighting";
alert(s);
\`\`\`
 
\`\`\`python
s = "Python syntax highlighting"
print s
\`\`\`
 
\`\`\`
No language indicated, so no syntax highlighting. 
But let's throw in a <b>tag</b>.
\`\`\`


1. asdf
2. adfasdf
`);
```

**Comment by sandy081** [comment]
We do not want to support all features of markdown in tree view message which could cause all such sort of issues. This will get fixed by reducing the list or not supporting the markdown at all. Tracking this here - https://github.com/Microsoft/vscode/issues/64406
