### ISSUE TITLE
Tree view message: Support commands

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#64343]
Issue Type: <b>Bug</b>

Testing #64205

Setting `isTrusted` on the MarkdownString is documented as enabling commands, but that doesn't work. Since a lot of other Markdown is already support, it would seem to make sense to also allow commands. (If not: Needs a note in the `message` documentation.)

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
Commands are supported and references view does use it - https://github.com/Microsoft/vscode-references-view/blob/master/src/extension.ts#L116

**Comment by chrmarti** [comment]
@sandy081 I'm missing something, shouldn't this work:
```ts
	const tree = window.createTreeView('githubIssuesPrs', {
		treeDataProvider: new GitHubIssuesPrsProvider(context),
		showCollapseAll: true,
	});
	tree.message = new MarkdownString('[Refresh](command:githubIssuesPrs.refresh)');
	tree.message.isTrusted = true;
```

That doesn't show a link for me.

**Comment by sandy081** [comment]
Ah I see.. I think message should not be a property, instead Tree view should provide a method to set message like `setMessage(message)`. This will avoid above patterns and issues.

**Comment by sandy081** [comment]
There are no plans to support markdown string for message. Hence closing this.
