### ISSUE TITLE
A problem matcher generating a path to a non-existent file and jump to problem leads to an infinite loop

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#64346]
- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Create the following:
    **hello-nested/hello.go**:
    ```go
    package main

    import "fmt"

    foo

    func main() {
	    fmt.Println("Hello, World!")
    }
    ```

    **.vscode/tasks.json**:
    ```jsonc
    {
        // See https://go.microsoft.com/fwlink/?LinkId=733558
        // for the documentation about the tasks.json format
        "version": "2.0.0",
        "tasks": [
            {
                "label": "build",
                "type": "shell",
                "command": "go build",
                "options": {
                    "cwd": "hello-nested"
                },
                "problemMatcher": "$go",
                "group": {
                    "kind": "build",
                    "isDefault": true
                }
            }
        ]
    }
    ```

2. Run the build task.
3. Press `F8`.
4. VS Code seems to enter some infinite loop. The open editors view is flickering and the UI becomes unresponsive.

Does this issue occur when all extensions are disabled?: Yes (except vscode-go).

**Comment by dbaeumer** [comment]
@segevfiner can you please provide a GitHub repository we can clone that demos this. There seems to be more to it (e.g. another folder hello-nested). Makes it easier to ensure we are looking at the same bug

**Comment by segevfiner** [comment]
> @segevfiner can you please provide a GitHub repository we can clone that demos this. There seems to be more to it (e.g. another folder hello-nested). Makes it easier to ensure we are looking at the same bug

@dbaeumer `hello/hello.go` was supposed to be `hello-nested\hello.go`. But sure, here you go: https://github.com/segevfiner/vscode-issue-64346.

**Comment by dbaeumer** [comment]
@segevfiner thanks for the repository. I am able to reproduce, but not the infinite loop. The reason why the file can't be found is the cwd change in the task. Since the go problem matcher works relative to the working directory you need to tell the problem matcher as well the relative path. Something like:

```typescript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "go build",
            "options": {
                "cwd": "hello-nested"
            },
            "problemMatcher": {
                "base": "$go",
                "fileLocation": ["relative", "${workspaceFolder}/hello-nested"]
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by dbaeumer** [comment]
Can you provide more information about the infinite loop you are seeing.

**Comment by segevfiner** [comment]
@dbaeumer It seems this doesn't happen with vscode-go 0.7.0 only with 0.7.1-beta.x.

![vscode-issue-64346](https://user-images.githubusercontent.com/24731903/49640502-6e352000-fa16-11e8-8c41-b9e8a93057c9.gif)

**Comment by dbaeumer** [comment]
@segevfiner this seems to be a problem with the go extension then. Can you please report the issue there.
