### ISSUE TITLE
input variable type names are very generic

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64359]
testing #64214:

input variable type names "prompt" and "pick" are very broad and generic.

Since I can imagine that the next feature request will ask for a file picker, a folder picker, and a general process picker, I wonder whether we could come up with more specific names that leave room for other future pickers and prompts.

**Comment by alexr00** [comment]
How about "promptString" and "pickString"?

**Comment by weinand** [comment]
yep, I like that!
