### ISSUE TITLE
Highlighting the argument name is string matching, instead of highlighting the actual argument number

### ISSUE THREAD

**Issue by qaisjp** [Microsoft/vscode#64351]
This is a resubmission of #10293 (which was moved from https://github.com/Microsoft/vscode-go/issues/327)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
ssh|chr|0.0.4
vscode-eslint|dba|1.7.0
githistory|don|0.4.4
gitlens|eam|9.0.1
EditorConfig|Edi|0.12.5
CppSnippets|har|0.0.13
latex-workshop|Jam|5.17.3
pddl|jan|2.6.12
sublime-babel-vscode|jos|0.2.10
language-haskell|jus|2.5.0
vscode-rust|kal|0.4.2
mips|kda|0.0.2
moonscript|Lyn|1.1.9
python|ms-|2018.11.0
cpptools|ms-|0.20.1
Go|ms-|0.7.0
docker-compose|p1c|0.3.2
vscode-docker|Pet|0.4.0
polacode|pnp|0.2.2
sass-indented|rob|1.4.9
vscode-lua|tri|0.12.4
full-react-snippets|wal|1.1.2
clang-format|xav|1.8.0

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/923242/49450410-d4cafb80-f7d4-11e8-897f-80b3b712d64e.png)

Steps to Reproduce:

1. Use `time.Date()`
2. Fill in arguments until the `minute` argument
3. Start entering `sec` and observe the `nsec` argument get highlighted

**Comment by jrieken** [comment]
Please file this issue against the extension in question. There is now API that allows to get this right.
