### ISSUE TITLE
[themes] Change color of the line number

### ISSUE THREAD

**Issue by JesusAMR** [Microsoft/vscode#6435]
- VSCode Version: 1.1.1
- OS Version: Windows 10

Be able to change the color of the number that represents the lines from the settings.json file

**Comment by alexandrudima** [comment]
@aeschli It appears the current implementation of https://github.com/Microsoft/vscode/blob/master\src\vs\workbench\services\themes\electron-browser\themeService.ts#L317 does not customize the color of the `.line-numbers`. Is this an oversight or is it that TM themes don't contain such a color?

**Comment by aeschli** [comment]
@alexandrudima There's no such color in standard textmate themes.

**Comment by akamud** [comment]
Could this also be included in workbench theming discussion [here](https://github.com/Microsoft/vscode/issues/3112)?

**Comment by smlombardi** [comment]
@aeschli Line numbers can indeed be set in a TextMate theme (for Sublime, anyway):

```xml
        <dict>
            <key>background</key>
            <string>#25292C</string>
            <key>divider</key>
            <string>#3b3a32</string>
            <key>foreground</key>
            <string>#EFEFEF</string>
            <key>selectionBackground</key>
            <string>#4f5b66</string>
            <key>selectionForeground</key>
            <string>#a7adba</string>
        </dict>
```

**Comment by aeschli** [comment]
Line number theming got added for March.
In the settings add:
```json
	"workbench.experimental.colorCustomizations": {
		"editorLineNumbers": "#5544AA",
       }
```
