### ISSUE TITLE
Error Problems

### ISSUE THREAD

**Issue by work-hrf** [Microsoft/vscode#64363]
Issue Type: <b>Bug</b>

The solution has no problem but vscode editor make it error

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.11.0
csharp|ms-|1.17.1

using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace Test1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Console.WriteLine(args);

            Console.WriteLine(GetContent().Result) ;
        }

        async static Task<string> GetContent()
        {
            HttpClient client = new HttpClient();
            Uri uri = new Uri("https://www.baidu.com");
            return await client.GetStringAsync(uri);

            
        }
    }
}
</details>

**Comment by jrieken** [comment]
> The solution has no problem but vscode editor make it error

Steps?
