### ISSUE TITLE
A suggestion to Erich Gamma

### ISSUE THREAD

**Issue by adriatic** [Microsoft/vscode#6436]
Allow me state a very strong support for the improvement suggestion by Rob Eisenberg (of the **[Aurelia](http://aurelia.io/) fame**) written [here](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/13877736-better-support-for-esnext) and repeate below. for reader's convencience:

> VSCode currently does a decent job of supporting ES2015. However, the language is moving fast and technologies like Babel allow us to use future features faster.

> In general, VSCode needs better support for ESNext. This includes a host of features such as class instance fields, decorators, async/await, exponentiation and more. It would be nice if the underlying engine could enable selecting which features were desired and enable the VSCode team to easily and quickly extend supported language features in the future. Regardless, it would be nice if the editor, at least, did not generate red squiggly error messages every time I used a language feature it didn't understand.

**Comment by egamma** [comment]
@adriatic thanks for sharing. 

>Regardless, it would be nice if the editor, at least, did not generate red squiggly error messages every time I used a language feature it didn't understand.

You can turn off the built-in syntax checks this is documented [here](https://code.visualstudio.com/docs/languages/javascript#_disable-syntax-validation-when-using-non-es6-constructs).

In general, VS code JavaScript support is powered by TypeScript and TypeScript follows the rule to only implement features until they are at stage 3 with TC39.  Pls see https://github.com/Microsoft/TypeScript/issues/2103#issuecomment-182195915. 

Actually decorators are supported today. The other ESNext features are on the roadmap https://github.com/Microsoft/TypeScript/wiki/Roadmap.
