### ISSUE TITLE
Bash terminal on Linux "ls" command changes how some switches work

### ISSUE THREAD

**Issue by jeffreybradley1963** [Microsoft/vscode#64360]
- VSCode Version: 1.29.1
- OS Version: Ubuntu 18.04 (Linux 4.15.0-39-generic

Steps to Reproduce:

1. open Terminal
2. type "ls -I *.sh"
3. This should ignore/exclude *.sh files as it does from an Ubuntu Terminal instead it ignores the -I
4. I can put it in a bash script file and when I run from terminal it still ignores it.
5. I can use the long method "ls --ignore='*.sh' and it works

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This has to be environment/config based on something, vscode has no control over bash or ls.
