### ISSUE TITLE
Cursor in debug variable hover is always a text cursor, not a pointer

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64377]
Testing #64003

I can't take a screenshot of my own cursor but

- Debug anything
- At a breakpoint, hover a variable
- Hover text in the popup
- See that the cursor changes to the text cursor, not the arrow pointer. In 1.29 it is always the arrow

![screen shot 2018-12-04 at 11 43 02 am](https://user-images.githubusercontent.com/323878/49468469-d20edd00-f7b9-11e8-869f-26e2afa42faf.png)

**Comment by roblourens** [comment]
Also in the console

**Comment by roblourens** [comment]
I find it really annoying, but we can see if anyone else complains.

**Comment by isidorn** [comment]
If you find it annoying that is good enough for me to change it. But let's react in December

**Comment by isidorn** [comment]
@roblourens do you find it annoying only in the debug hover or in all debug trees?
What would be your ideal cursor look in what case?
Note that text is always selectable.

My personal preference: 
* Pointer curosr in variable, watch and call stack is good as it is now
* Debug console: always use selection curosr, except when hovering over elements that have children - than turn to a pointer
* Debug hover: always use pointer

fyi @weinand

**Comment by roblourens** [comment]
My preference is, if the primary way that I interact with the UI is to click on it, e.g. to expand and collapse it and so on, then it feels wrong to do that with a text cursor. If it's primarily just text, then it should be the text cursor. So I agree with what you describe.

**Comment by isidorn** [comment]
Great, try it out in a couple of days when we release new insiders and let me know how you like it.

**Comment by nealot** [comment]
@isidorn The debug console in the latest insiders uses the selection cursor for everything (even the action label and background) which seems like a regression.

**Comment by isidorn** [comment]
@nealot thank you for reporting this. I have fixed this via 7a0c826121
We will have a new insiders after the holiday break in around 10 days and that should have it fixed.
