### ISSUE TITLE
TS reference code lens should be able to open reference list

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#64376]
Issue Type: <b>Feature Request</b>

Rigth now when clicking the code lens, peek reference is called. I'd like to use the reference list view instead.

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by mjbvz** [comment]
@jrieken What's the references list equivalent of `editor.action.showReferences`? We already have a list of references for the code lens and just need to open it in the references list

**Comment by jrieken** [comment]
Nah, there is nothing yet... The references-view would need to offer such a command. Is the expectation that such 'searches' also go onto the search history or is that something we would treat as transient?

**Comment by mjbvz** [comment]
I don't think they should go in the search history. Keeping the history to explicit user searches makes sense to me

**Comment by wKich** [comment]
Codelens references links are less common, than code for which you can do explicit search. You can search for local variable, but it useless.

**Comment by jrieken** [comment]
I have pushed a change that adds a new setting `reference.codeLens.location` with values `peek` and `view`. The former is the default and todays behaviour, the latter makes code-lens references be opened in the viewlet. Open for suggestion regarding the settings name.

**Comment by jrieken** [comment]
@kieferrm @mjbvz feedback on the name of the setting?

**Comment by mjbvz** [comment]
`"references.preferredLocation": "peek" | "view"`?

I like a more generic name since the action we are overriding can be used outside of code lenses too
