### ISSUE TITLE
Terminal find widget shadow is visible when find widget is hidden

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#64379]
The shadow is visible just under the panel actions

![image](https://user-images.githubusercontent.com/2193314/49468747-a2140980-f7ba-11e8-8e0e-f48da21a32cf.png)

**Comment by agusputra** [comment]
Hi Tyriar, how to reproduce this bug?

I'm using vscode 1.29.1.

**Comment by Tyriar** [comment]
@agusputra I think it was introduced in 1.30 so you should be able to repro it if you build and run the dev build off master https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run

**Comment by marchenko-am** [comment]
Hi. I fixed it. Please, look at [this](https://github.com/Microsoft/vscode/pull/64558).
It is my first contributing to open source. And I open for your remarks.

**Comment by agusputra** [comment]
Hi @Tyriar I'm successfully build the vscode and now run version 1.30.

But I did not see the shadow.

Here is the step I do (I'm using Linux):
1. Run the vscode by run `./scripts/code.sh`
2. Open terminal by press ``Ctrl +` ``
3. On terminal window press `Ctrl + f` to open find widget
4. Close find widget
