### ISSUE TITLE
Ability to have user settings conditional on project type 

### ISSUE THREAD

**Issue by Ryan-Gordon** [Microsoft/vscode#64378]
Here is a prerequisite issue which gives the functionality to change status bar colour : https://github.com/Microsoft/vscode/issues/1884

And here is an issue which requests similar behaviour but at a more abstract level : https://github.com/Microsoft/vscode/issues/62868

As a vscode user
I would like a way to change different settings or have different settings applied depending on language
so that I can have a set of settings applied anytime I open a python project.

One example of this is StatusBar colour, for example  would like to apply a set of settings which makes my status bar gold when a python project is loaded or cyan when a java project is loaded

**Comment by Ryan-Gordon** [comment]
To add onto this
It seems my use-case and goal is more of a
 "I want to have access to workbench and other settings in a per-language manner"
Similar to how I can have different editor settings depending on language

**Comment by sandy081** [comment]
@Ryan-Gordon 

> One example of this is StatusBar colour, for example would like to apply a set of settings which makes my status bar gold when a python project is loaded or cyan when a java project is loaded

This looks to me per project rather per language? Caution that a project can have files with multiple languages. So changing the workbench colours per file is not a good idea.

**Comment by Ryan-Gordon** [comment]
So my ideal use-case would be per language as, exactly like you say, a project can have multiple languages. 
Imagine a flask app with some html and python. I would like to have certain settings only applied to the python aspect of the project. This is already available, albeit limited to things like the editor but I would also like to have it for workbench. 
Do you think having something like this would severely affect anything ? I imagine it would be similar to how when you switch to something written in python, it applies the editor changes and so on
 
Statusbar might not be the best example of something to change depending on language but it would be really cool. 

So I think my main need/want is access to the workbench namespace in a per-language way the same way I can access editor. I was wrong to say depending on project type

**Comment by sandy081** [comment]
> Do you think having something like this would severely affect anything ? I imagine it would be similar to how when you switch to something written in python, it applies the editor changes and so on

Statusbar might not be the best example of something to change depending on language but it would be really cool.

Please provide me a concrete use case that will help you in configuring workbench settings per language?
