### ISSUE TITLE
Should task user input be shell escaped?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64385]
Testing #64214

**Repo**
1. On osx.
1. With tasks.json:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Echo input",
			"type": "shell",
			"command": "echo \"${input:echoPrompt}  ${input:echoPick} ${input:echoPrompt} ${command:extension.pickNodeProcess}\"",
			"problemMatcher": []
		}
	],
	"inputs":[
		{
			"label": "echoPrompt",
			"description": "Please enter a value",
			"default": "test echo",
			"type": "prompt",
		},
		{
			"label": "echoPick",
			"description": "Select one of the values",
			"default": "two",
			"type": "pick",
			"options": ["one", "two", "three"]
		}
	],
}
```

1. Run the task.
1. In the input box, enter: 

```bash
`echo "hi"`
```

1. Run the task

**bug**
Special shell characters not escaped. Not sure if this is expected or how this could be handled better. Backticks probably aren't a real problem but quotes (or spaces) could be

**Comment by dbaeumer** [comment]
@alexr00 we should escape them. There is code in the terminal runner that does the escaping.

**Comment by alexr00** [comment]
Ok, moving to December.

**Comment by alexr00** [comment]
Talked about this one a bit more. We will not escape user input in tasks. If you want user input to be escaped you can put it in an argument array:

    {
        "label": "Echo input",
        "type": "shell",
        "command": "echo"
        "args": ["${input:echoPrompt}"],
        "problemMatcher": []
    }
