### ISSUE TITLE
Issue Reporter login to GH

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#64386]
Issue Type: <b>Feature Request</b>

When a user has the GH PR extension installed, then the user may have a logged-in session with GH. We should think about leveraging this. (I hit rate limited from time to time.)

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/95165
