### ISSUE TITLE
Ruby hash keys highlighting

### ISSUE THREAD

**Issue by amerov** [Microsoft/vscode#64380]
- VSCode Version: 1.29.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open a Ruby file
2. Type hash keys

Does this issue occur when all extensions are disabled?: No
![screenshot from 2018-12-05 01-05-51](https://user-images.githubusercontent.com/196747/49470151-171f2780-f82b-11e8-8cad-2796ead96b55.png)
![screenshot from 2018-12-05 01-04-41](https://user-images.githubusercontent.com/196747/49470152-17b7be00-f82b-11e8-8092-f4207f73bbb1.png)

**Comment by alexr00** [comment]
@amerov, sounds like this is an issue with the extension you're using for Ruby since it doesn't repro without extensions. If you look at the info page for the extension it should have a link somewhere for where to file issues!

**Comment by amerov** [comment]
@alexr00 I don't install any ruby from marketplace.
Is it builtin extension issue for https://github.com/Microsoft/vscode/tree/master/extensions/ruby.

**Comment by alexr00** [comment]
Ah, I saw this and thought that you installed an extension:

> Does this issue occur when all extensions are disabled?: No

I will take a look.

**Comment by alexr00** [comment]
The hash keys are getting identified by the ruby grammar as constant.other.symbol.hashkey.ruby, so this looks like a theming issue. For theming, you can install a ruby theme extension or write one yourself: https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_syntax-highlighting-colors
