### ISSUE TITLE
Tasks schema could alert for inputs where  you try using "options" with "prompt"

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64387]
Testing #64214

**Repo**
Open this `tasks.json` in vscode:

```json
{
	"version": "2.0.0",
	"tasks": [
		{

			"label": "Echo input",
			"type": "shell",
			"command": "echo \"${input:echoPrompt} ${input:echoPick} ${input:echoPrompt} ${command:extension.pickNodeProcess}\"",
			"problemMatcher": []
		}
	],
	"inputs":[
		{
			"label": "echoPrompt",
			"description": "Please",
			"default": "test echo",
			"type": "pick"
		},
		{
			"label": "echoPick",
			"description": "Select one of the values",
			"default": "two",
			"type": "prompt",
			"options": ["x"]
		}
	],
}
```

**Bug**
No warnings in the json file but they fail when you try running them.

Type `prompt` should not allow `options`, while type `pick` should require options. I think you can use json schema conditionals to enforce these

**Comment by isidorn** [comment]
I do similar things in debug land. The trick is to use `oneOf` schema property
Code pointer https://github.com/Microsoft/vscode/blob/1bd823dfb92eabc038786e3aa183f403a620f7f5/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L273
