### ISSUE TITLE
Not seeing any user facing alert for stalled extension 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64388]
Issue Type: <b>Bug</b>

Testing #64222

1. For an extension:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.commands.registerCommand('myExtension.sayHello', async () => {
        const start = Date.now();
        while (true) {
            const now = Date.now();
            if (Math.abs(start - now) >= 30000) {
                break;
            }
        }
        console.log('done');
    });
}
```

1. Install the extension ([test-ext-0.0.2.vsix.zip](https://github.com/Microsoft/vscode/files/2646483/test-ext-0.0.2.vsix.zip)) and run the say hello command.  

**Bug**
During the stall, I see alerts printed in the dev console but not user facing warnings. No hidden notifications or alerts

VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

</details>

**Comment by jrieken** [comment]
> During the stall, I see alerts printed in the dev console but not user facing warnings. No hidden notifications or alerts

I does that because your extension doesn't have a repo-url in its package.json. We figured not to blame those extensions because a user cannot really follow up (except for removing that extension)

**Comment by mjbvz** [comment]
Yes, that was the issue. Everything looks good once I added that
