### ISSUE TITLE
[Windows] [V-Sync] [Nvidia] Very bad flickering and spasms in fullscreen mode (Update)

### ISSUE THREAD

**Issue by Sgt-Nukem** [microsoft/vscode#64383]
When using "gamer settings" for V-Sync on nVidia Hardware on Windows 10...

...Visual Code will flicker and spasm like crazy in fullscreen mode. Heaving many blocks all over the place blinking 10+ times per seconds. VS Code looks like having a seizure then.

I could pinpoint the problem down to why I have this issue on my home computer only. It's because I'm playing games there, too, and have the 3D settings optimized for it (see below).

(It could be difficult to visually capture the symptoms correctly, but I am assuming it shouldn't be too hard to find a VS Code developer with nVidia hardware of current, last, or last-last generation. I am experiencing this issue myself with a GeForce 970 GTX desktop GPU.)

**PROBLEM CAUSE:**
The problem is when [ "Fast Sync" ](https://i.imgur.com/LL8I8KY.png ) is enabled as the default V-Sync setting in the nVidia driver settings.

> (Background info:
> There are two very distinct methods to displaying real-time graphics:
> - No sync, i.e. drawing as fast as you can -> this is the most lag-free way, but produces ugly "tearing" artifacts
> - Sync to monitor refresh, i.e. after drawing to a second framebuffer you wait until the monitor is in it's "v-sync" phase, then quickly switch the framebuffers around -> this has no "tearing" whatsoever, but introduces 1, 2, or even more frame(s) of input lag (as the game simulation could have drawn 3, 4, 5, ... more frames in that time, but is waiting for the monitor's "v-sync" phase instead))

"Fast Sync" is a technique Nvidia introduced in the last year or so to combine the advantages of both variants. It will draw "as fast as it can" into the second framebuffer continously, and then - in the monitor's "v-sync" phase - quickly switch the framebuffers _so that the most current render gets displayed_ on the monitor.
The advantage is, that this introduces 1 frame lag _at maximum_, while still preventing the awful "tearing" artifacts one would get not waiting for the "v-sync" phase.

Quick guess: Because of this setting, VS Code renders far too many screen refreshes per frame and is supposed to max out at 60 fps or such.

- VSCode Version: 1.29.1
- OS Version: Windows 10 1809 October 2018

Steps to Reproduce:

1. Have an nVidia GPU from 2015+
2. Activate "Fast Sync" globally in nVidia settings
3. Toggle VS Code to fullscreen (F11)

**WORKAROUND:**
To the side of "Global Settings" there is another tab with "Progam Settings" where one could override the global settings for one particular application with a "profile".
You have to manually browse to "%LOCALAPPDATA%\Programs\Microsoft VS Code" and choose "Code.exe" as application, as this is not detected by the nVidia driver panel as "last used 3D application".
However, if you then override "Vertical sync" to "Use the 3D application setting" (or possible another), the issue goes away.

P.S.: I refrained from using VS Code in my preferred fullscreen mode for more than half a year now, because I only now detected the REAL culprit. :(((

P.P.S.: I couldn't even find any bug reports that looked like the issue I was experiencing.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by Sgt-Nukem** [comment]
> We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)


Subjectively perceived it flickers NOT THAT MUCH as the current VS Code version.

But it is still impossible to work with in fullscreen mode nonetheless.

I captured some footage with my cellular and converted it to a GIF to demonstrate the implications.
To fit into the 10MB limit of github it is downscaled to just 320px width - but I think you get the idea:

![vs_code_seizure_g1](https://user-images.githubusercontent.com/4144388/50041763-68fd5400-005a-11e9-9ecd-1e20148cebd4.gif)

NOTE: The SPEED of flickering and popping up and disappearing again of UI elements (like the menu bar or context menus) is MUCH HIGHER than the GIF reveals!


As you cannot recognize my zoom-in to the about box at the end anymore, I just copied it (there was one update to your linked WINDOWS build ready that I installed beforehand these tests):

Version: 1.31.0-exploration (user setup)
Commit: 37818ac3597b4afda264b05226b0b77fb8e85f41
Date: 2018-12-13T07:43:53.389Z
Electron: 4.0.0-beta.9
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by Sgt-Nukem** [comment]
Just downloaded the Insider Build:
Version: 1.31.0-insider (user setup)
Commit: 2803a8655cf5e05066a4ee47cce303eefca6408c
Date: 2018-12-20T09:10:39.545Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**-> SAME ISSUES** 👎 

P.S.: I don't understand why I'm supposed to test an even older Electron/Chrome version, as the issue even appears in 4.0.0-beta.9 / 69.0.3497.106 - see comment above.

**Comment by bpasero** [comment]
It will probably go away if you run "`code --disable-gpu`" from the command line?

**Comment by Sgt-Nukem** [comment]
> It will probably go away if you run "`code --disable-gpu`" from the command line?

Yes. 👍

Tested in Electron 3 (Insiders) and Electron 4 (Exploration).
