### ISSUE TITLE
syntax coloring and intellisense very slow

### ISSUE THREAD

**Issue by conleymon** [Microsoft/vscode#64384]
Issue Type: <b>Performance Issue</b>

All of a sudden, intellisense is unusably slow. This becomes noticeable for files  with 150 lines.  It holds true after re-installation and with no extensions installed. 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.91GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 20372	code main
    0	    88	  6280	   gpu-process
    0	   202	  6364	   window (● index.js - Visual Studio Code)
    0	    93	  3120	     extensionHost
    0	   232	 12264	       electron_node tsserver.js 
    0	    54	 13012	         electron_node typingsInstaller.js typesMap.js 
    0	    48	 15236	       "C:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3120
    0	    13	 10528	     electron-crash-reporter
    0	    66	 16432	   window (Issue Reporter)
    0	    63	 19840	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-standard-vscode|num|0.5.0

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by optomux** [comment]
https://github.com/Microsoft/vscode/issues/64681

**Comment by jrieken** [comment]
@optomux Also for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues.

**Comment by conleymon** [comment]
Hi, my problem somehow resolved itself. It may have been after a restart, but I'm not sure.
Thank you for your attention to the problem.Conley
    On Thursday, December 13, 2018, 1:44:42 AM CST, Johannes Rieken <notifications@github.com> wrote:  
 
 
@optomux Also for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues.

**Comment by optomux** [comment]
What are you talking about? He clearly says there is a problem.
https://github.com/Microsoft/vscode/issues/64681
