### ISSUE TITLE
vscode.window.activeTerminal doesn't update when an extension opens a new terminal

### ISSUE THREAD

**Issue by TylerLeonhardt** [Microsoft/vscode#64390]
In [this PR](https://github.com/PowerShell/vscode-powershell/pull/1619), I was attempting to use `vscode.window.activeTerminal` to handle a keybinding differently.

What I noticed is that the `activeTerminal` does not get updated after our extension creates and shows a new terminal. See [this code](https://github.com/PowerShell/vscode-powershell/blob/master/src/process.ts#L102-L110) for how we are doing that:
```typescript
                    this.consoleTerminal =
                        vscode.window.createTerminal(
                            this.title,
                            powerShellExePath,
                            powerShellArgs);

                    if (this.sessionSettings.integratedConsole.showOnStartup) {
                        this.consoleTerminal.show(true);
                    }
```

- VSCode Version: 1.30.0-insiders
- OS Version: macOS High Sierra

Steps to Reproduce:

1. See these lines of code https://github.com/PowerShell/vscode-powershell/blob/master/src/process.ts#L102-L110
2. add a `console.log(vscode.window.activeTerminal.name);` before and after

```typescript
                    console.log(vscode.window.activeTerminal.name);

                    this.consoleTerminal =
                        vscode.window.createTerminal(
                            this.title,
                            powerShellExePath,
                            powerShellArgs);

                    if (this.sessionSettings.integratedConsole.showOnStartup) {
                        this.consoleTerminal.show(true);
                    }

                    console.log(vscode.window.activeTerminal.name);
```

3. see:

```
bash                          process.js:62
bash                          process.js:70
```

get printed out.

cc @Tyriar

**Comment by TylerLeonhardt** [comment]
Let me know if there's anything else you need from me in the form of a repro. Sadly, this issue blocks [my vscode-powershell PR](https://github.com/PowerShell/vscode-powershell/pull/1619)

**Comment by Tyriar** [comment]
I think there are 2 bugs here, but not the one that you actually reported. I think the way it's behaving right now is as design since show is an async request which may or may not change the activeTerminal.

Here are the 2 bugs:

- `onDidChangeActiveTerminal` is not firing unless the terminal is focused, I think it makes more sense to also fire when a new tab appears
- `activeTerminal.name` doesn't get set for terminals created via the API

I've fixed both of these, they should land in tomorrow's insiders build. As for your feature, install a onDidOpenTerminal (before `createTerminal`) or onDidChangeActiveTerminal (before `show`) listener in order to use the terminal when it's ready.

**Comment by TylerLeonhardt** [comment]
Thanks @Tyriar!

**Comment by Tyriar** [comment]
@TylerLeonhardt if you continue on that PR let me know if it all works and I can mark this off as verified, will save someone on the team setting up an extension to do it 😃

**Comment by Tyriar** [comment]
Sounds like this should work then. Yes please test when you can 🙂

**Comment by TylerLeonhardt** [comment]
LGTM 👍
```ts
function checkActiveTerminal() {
    const { activeTerminal } = vscode.window;
    console.log("activeTerminal: " + (activeTerminal ? activeTerminal.name : "<none>"));
}

checkActiveTerminal();
vscode.window.onDidChangeActiveTerminal(checkActiveTerminal);
```
```
activeTerminal: bash                                                        process.js:67
activeTerminal: PowerShell Integrated Console            process.js:67
```

and my feature works too! 😄

Thanks @Tyriar!

**Comment by Tyriar** [comment]
Awesome! 😃
