### ISSUE TITLE
bash: promlsource: command not found

### ISSUE THREAD

**Issue by currentcreative** [Microsoft/vscode#64396]
- VSCode Version: 1.29.1
- OS Version: OS X

Steps to Reproduce:

1. Open VS Code
2. Look at terminal...don't even have to have a document open.

Does this issue occur when all extensions are disabled?: Yes
![screen shot 2018-12-04 at 7 24 25 pm](https://user-images.githubusercontent.com/1802530/49481754-49fcf780-f7fa-11e8-9221-814ba9a8bca7.png)

**Comment by Tyriar** [comment]
promlsource is being run in your bash launch scripts. You either need to tweak those scripts (like `~/.bash_profile`) or set the terminal to run in a non-login shell by adding this setting:

```
"terminal.intergrated.shellArgs.osx": []
```
