### ISSUE TITLE
Editing variable from object to primitive value, expand arrow isn't removed

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64394]
Testing https://github.com/Microsoft/vscode/issues/64003

- Debug this code, set a BP on the console.log:

```js
setInterval(() => {
    let x = { a: 1 };
    console.log(x);
}, 1000);
```

- Expand the `x` object
- Edit `x` to a primitive value like `123` 
- `x` still has the expand arrow in the variables pane

![image](https://user-images.githubusercontent.com/323878/49481333-47d96f80-f7df-11e8-8cc9-ea8df871d010.png)

- The expand arrow goes away correctly in 1.29

**Comment by isidorn** [comment]
@joaomoreno this looks like an issue with the tree.
If the element with the same ID after a refesh no longer has children the expando is left behind.
Assigning to you also if you have time to investigate.

**Comment by joaomoreno** [comment]
Pretty sure it's the same as #64074, but let's see.
