### ISSUE TITLE
Color syntax loss when moving parenthesis

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#6439]
- VSCode Version: 1.1.1
- OS Version: 10.11.4 (15E65)

Steps to Reproduce:

Please see attached image: on the first one when the parenthesis is on same line as 'constructor' colors are ok. On the second one when the parenthesis is below 'constructor' some syntax highlight color is lost.
On 3rd one you can see also missing highlight for object keys.

1:
<img width="316" alt="1" src="https://cloud.githubusercontent.com/assets/5489200/15339737/1ea35f90-1c86-11e6-9809-07fcf2d9f3fe.png">

2:
<img width="331" alt="2" src="https://cloud.githubusercontent.com/assets/5489200/15339736/1e9fb84a-1c86-11e6-9258-6b86f895753c.png">

3:
<img width="812" alt="3" src="https://cloud.githubusercontent.com/assets/5489200/15339735/1e83e48a-1c86-11e6-99f9-7ef02a60e9ac.png">

**Comment by Brakkar** [comment]
Also, another case, inline comment in the third line, removes color of 'private' in the forth line:

<img width="473" alt="capture d ecran 2016-05-19 a 12 00 28" src="https://cloud.githubusercontent.com/assets/5489200/15389928/83fa27dc-1db9-11e6-9b8c-0cc7e72f0b9f.png">

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#171
