### ISSUE TITLE
Tree error from callstack

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64400]
Testing https://github.com/Microsoft/vscode/issues/64003

- Start debugging, pause
- Focus a call stack frame
- Press space
- `Data tree node not found: fulfilled ... `

![image](https://user-images.githubusercontent.com/323878/49482354-a6085180-f7e3-11e8-9996-3497a0074113.png)

**Comment by isidorn** [comment]
This is coming from the tree. And is happening if you press space on any tree, not just the call stack.
Forwarding to @joaomoreno 
@roblourens great catch
