### ISSUE TITLE
debug chrome

### ISSUE THREAD

**Issue by tankzhangying** [Microsoft/vscode#64404]
Issue Type: <b>Bug</b>

ReferenceError: suggestionsSummaryListHeader is not defined
    at HTMLParagraphElement.eval (eval at E (chrome-error://chromewebdata/:14:208), <anonymous>:3:21)
    at w (chrome-error://chromewebdata/:5300:845)
    at L.b (chrome-error://chromewebdata/:5306:231)
    at L.e (chrome-error://chromewebdata/:5305:393)
    at window.jstProcess (chrome-error://chromewebdata/:5308:800)
    at chrome-error://chromewebdata/:5310:56

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
gitlens|eam|9.0.1
tslint|eg2|1.0.40
beautify|Hoo|1.4.7
vscode-language-pack-zh-hans|MS-|1.29.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
vuehelper|oys|0.1.0
sass-indented|rob|1.4.9
language-stylus|sys|1.10.0

</details>

**Comment by roblourens** [comment]
#64405
