### ISSUE TITLE
Navigating multiline debug console input

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64401]
Testing https://github.com/Microsoft/vscode/issues/64003

- Have wrapped lines of text in the debug console input
- arrow up/down only navigates history, I can't use it to move the cursor between wrapped lines

Also
- Have multiple lines of text (with actual newlines via shift+enter)
- Arrow up/down does move the cursor between lines but I can't navigate history

I should be able to navigate through the multiline text, but when the cursor gets to the very top or bottom of the input, then it navigates to the next/previous history item. See the multiline search input.

**Comment by roblourens** [comment]
Actually I see there is just a difference between navigating the history (up/down only goes through history) and editing (up/down only controls the cursor in the input).

I think this is actually not bad, you can close this if you want.

**Comment by isidorn** [comment]
I think I was given less freedome to customise this experience once we started sharing history navigation code.
ANyways the current behavior is not bad, so closing.
Thanks
