### ISSUE TITLE
Tree view markdown message may be too powerful

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#64406]
We discussed this during the api call, I'm not sure whether there was any more discussion about it. Do we really want to let extensions render any markdown in the tree? If they can render lists, tables, images, etc, then some extensions will probably go all-out. But the tree view message isn't a good place for heavy fancy content so it could result in a bad experience.

![image](https://user-images.githubusercontent.com/323878/49486594-eb347f80-f7f3-11e8-9f68-e4d2779251a3.png)

I would propose not allowing markdown. But as a compromise you could post-process the rendered markdown to remove certain features. For example in the settings editor, we disallow images:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/settingsTree.ts#L1309

**Comment by sandy081** [comment]
We discussed about it in couple of other related issues and outcome was either to

- support limited set of markdown features
- do not support at all

CC @jrieken

**Comment by jrieken** [comment]
@alexr00 fyi - I have removed support for markdown formatted messages and only left support for simple messages: 192e15b613dd4f4dab9c735b7556e175580c6011
