### ISSUE TITLE
typescript type is not compatible

### ISSUE THREAD

**Issue by DiamondYuan** [Microsoft/vscode#64410]
code 
```
const type = {
  name: "DiamondYuan",
};

interface Name {
  name: "DiamondYuan";
}

const temp1: Name = {
  name: "DiamondYuan",
};

const temp2: Name = type;
```

![_c57890b2-2b6f-4792-b324-945d43656246](https://user-images.githubusercontent.com/9692408/49494222-d3afd200-f899-11e8-9624-19af4f616863.png)

**Comment by mjbvz** [comment]
This is not a VS Code issue

The type of `type.name` is `string`. To ensure `type.name` has the literal type:

```ts
const type: Name = {
  name: "DiamondYuan",
};
```

or 

```ts
const type = {
  name: "DiamondYuan"  as "DiamondYuan",
};
```
