### ISSUE TITLE
Allow only for some editors to open as preview (from SCM)

### ISSUE THREAD

**Issue by brgrz** [microsoft/vscode#64416]
I'd like to be able to set in settings open working tree files in Preview mode but everything else without preview.

I have Enable Preview disabled so all files remain open after clicking on them once and working tree changes files start to pile up (I often glance over them when staging them for commit).

If I Enable Preview I have to do single/double clicks which is annoying, at least to me.

As such, a setting would be nice to deal with this.

**Comment by joaomoreno** [comment]
@bpasero I'm guessing that if the user disables Preview, there's no way the Git extension could open a preview editor.
