### ISSUE TITLE
Unable to save file with Windows 1252 encoding

### ISSUE THREAD

**Issue by samwincott** [Microsoft/vscode#64419]
Issue Type: <b>Bug</b>

I am trying to save a .CSV file with Windows 1252 encoding, but each time the file is reopened it appears to change back to UTF-8 encoding.

Steps to reproduce:
1) Open CSV file
2) Select the UTF-8 icon on the bottom right of editor.
3) Select the "Save with Encoding" option.
4) Select the "Western (Windows 1252)" option.
5) Save the file.
6) Close and reopen the file.
7) The encoding resorts back to UTF-8.

I have tried reproducing with all extensions disabled, and the problem persists.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
