### ISSUE TITLE
Search view layout in panel can be improved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#64418]
![screenshot 2018-12-05 at 11 36 14](https://user-images.githubusercontent.com/1926584/49508294-9f7ce700-f882-11e8-97a1-83b546155f47.png)

1. Notice the search and replace inline buttons all the way to the right. They look disconnected and far away
2. Notice all the empty space on the right. This space feels unused, and I feel like we could have a better layout / presentation of results in this case
3. Notice how the hover actions jump at the end of each line. Thus their position is not consistent. This was done so they would not be at the very end disconnected. However this does not feel like a real solution for me
4. Notice how the snippet of each result is cropped at the same length as in the sidebar. Even though here we have much more space and could show more context of each result

I think we could give more thought to improving this experience.
Though before we do anything crazy I suggest we wait for the workbench layout using the grid - as we might need a more general story for views.
fyi @bpasero @sbatten

**Comment by roblourens** [comment]
We tried some things earlier and nothing really worked. Maybe @misolori can take a crack at it some day.

3. We do have the setting `search.actionsPosition` for this at least but I'm not crazy about either setting.

4. Yeah there is another issue for this.

**Comment by roblourens** [comment]
Here is the issue with screenshots: https://github.com/Microsoft/vscode/issues/45063

**Comment by andremacola** [comment]
Related to #23931

**Comment by roblourens** [comment]
Probably will focus on search results in a text editor rather than this
