### ISSUE TITLE
Works in "files to include", fails in "files to exclude"

### ISSUE THREAD

**Issue by phistuck** [Microsoft/vscode#64415]
- VSCode Version: 1.29.1 (user setup)
- OS Version: Windows 10 1709

Steps to Reproduce:
1. Search in files in workspace (the workspace is for c:\projects\foo, the workspace file is placed in c:\projects\foo\foo.code-workspace and the `folders: [{path: "."}]`).
2. Put `./foo/` in the includes and `./foo1/` (or `./foo/`) (for example) in the excludes.
3. Search.

Expected -
The search works and excludes that path from the results.

Actual -
Error parsing glob '!/c:\Projects\foo1\': dangling '\'

Appending ** (./foo/**) fixes the error, but still does not exclude it.

Also, might be related, the following glob patterns are simply ignored when placed under `search.exclude` -
`foo`
./foo
Only stuff that begins/ends with ** are appended for me in the trace. Only those that begin with **/ actually exclude. But I just want to exclude a three-level folder from my search (./foo/components/component1/). I cannot find a way.

![image](https://user-images.githubusercontent.com/184400/49499995-40b27000-f878-11e8-817e-ed674a90fb2c.png)
![image](https://user-images.githubusercontent.com/184400/49500450-6724db00-f879-11e8-8b3f-e5be9c0a169b.png)
![image](https://user-images.githubusercontent.com/184400/49500458-6b50f880-f879-11e8-88f2-3022227e2749.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
The `./` issue in exclude is https://github.com/Microsoft/vscode/issues/63303

Can you check whether the other stuff works for you in Insiders? I fixed a similar issue.
https://code.visualstudio.com/insiders
