### ISSUE TITLE
Find in files doesn't look in all opened files

### ISSUE THREAD

**Issue by retepaskab** [Microsoft/vscode#64411]
We have written th
Issue Type: <b>Bug</b>

1. Open 1 file
2. Ctrl-shift-F something
3. open some more files (I used command line for this, not VSCode's menu item)
4. search for something, using the already opened find in files tab
5. not all results are displayed
6. click on each open file's title tab 
7. search for something, using the already opened find in files tab
8. now all results are displayed (hopefully...)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|30.91GB (20.73GB free)|
|Process Argv|c:\Dev\BPet-A180-dev\LibSrc\BuilderFiles\INT_builder.xml|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.0.0
alignment|ann|0.3.0
close-all|ben|1.0.2
tslint|eg2|1.0.40
vs-code-xml-format|fab|0.1.5
vscode-npm|fkn|3.3.0
gdl-xml|pba|1.23.2
guid|kos|0.0.1
vs-color-picker|lih|0.7.0
language-gettext|mro|0.1.1
python|ms-|2018.11.0
cpptools|ms-|0.20.1
color-highlight|nau|2.3.0
printcode|nob|3.0.0
relativegoto|ret|0.0.1
perforce|sle|3.1.0
vscode-hexdump|sle|1.7.2
goto-line-ex|xyz|0.0.4

(1 theme extensions excluded)

</details>
e needed data into your clipboard because it was too large to send. Please paste.

**Comment by roblourens** [comment]
These files are not in an open folder right? If so, https://github.com/Microsoft/vscode/issues/62488
