### ISSUE TITLE
Run task notification tweaks

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#64427]
Testing #64217

![image](https://user-images.githubusercontent.com/172399/49510182-ba9e2580-f887-11e8-90b8-09d112c181bd.png)

To decide whether I want to allow the task to run, it would be helpful to also have a button that opens the tasks.json. This would yet add another button. It could replace the 'Not this time' button. This button is not that useful since the user can just close the notification.

Wording suggestion, since 'automatic task' is not very clear. For example,

>This folder has tasks defined in 'tasks.json' that run automatically. Do you allow these tasks to run when you open this folder.

**Comment by alexr00** [comment]
Let's make the notification more specific: https://github.com/Microsoft/vscode/issues/64355#issuecomment-444609876

**Comment by alexr00** [comment]
Example of how the notification will look:
![image](https://user-images.githubusercontent.com/38270282/49641192-c157a480-fa0f-11e8-8373-b3ff8bb4f58d.png)
