### ISSUE TITLE
Breadcrumb for "out of workspace" files is bad

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#64429]
Just open a file that is no within the workspace and look at the "description" part of a label having a leading `\.\`

![image](https://user-images.githubusercontent.com/900690/49512095-38186480-f88d-11e8-9ad9-c7def4392ce8.png)

This seems to be a regression from this month, thus moving to this month.

**Comment by isidorn** [comment]
Assigning also to you @bpasero if you can investigate. Thanks

**Comment by bpasero** [comment]
Now I realized this only happens when breadcrumbs are enabled, label is fine otherwise. 

**Steps:**
* enable breadcrumbs
* disable tabs
* open a file that is not within the workspace (e.g. settings as JSON)

This does not seem to be a regression from this milestone, I can reproduce in stable as well.

![image](https://user-images.githubusercontent.com/900690/49581108-27312700-f951-11e8-97a5-1894c3483318.png)

**Comment by jrieken** [comment]
Ultimately this is a problem with https://github.com/Microsoft/vscode/blob/fa7e51a33334e31a7913ccc4d81903af87451bdf/src/vs/base/common/resources.ts#L75-L86 not stopping at `c:/` when it the uri is of the `file`-scheme

**Comment by aeschli** [comment]
paths.dirname(`c:/`) returns `.`. Not clear what's the expected result.

**Comment by bpasero** [comment]
Not for me:

![image](https://user-images.githubusercontent.com/900690/50694751-07b61880-103b-11e9-9185-88366f7799a2.png)

**Comment by aeschli** [comment]
What I described is what our own paths util does.

**Comment by jrieken** [comment]
> What I described is what our own paths util does.

Well, don't use that ;-) You might be lucky when calling  `getRoot` first and then call `dirname` only on the none root part

**Comment by jrieken** [comment]
Thanks @aeschli

**Comment by aeschli** [comment]
@jrieken There's still an issue with an unnecessary leading slash. You take over again?

![image](https://user-images.githubusercontent.com/6461412/51043679-8f61d100-15bf-11e9-8b3b-de6bdc464d92.png)

**Comment by jrieken** [comment]
Yeah, will finish that
