### ISSUE TITLE
Git stash icon is a bad fit

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64423]
The new git stash icon isn't a good fit and appears must more heavy/bold than other icons. 

<img width="359" alt="screenshot 2018-12-05 at 12 09 57" src="https://user-images.githubusercontent.com/1794099/49509816-bcb3b480-f886-11e8-862a-8ce2d24c1dcd.png">

**Comment by joaomoreno** [comment]
I agree. But you gotta go talk to GitLens.

**Comment by jrieken** [comment]
🤣

**Comment by eamodio** [comment]
😄 Do you not like the command there or just the icon itself? If just the icon is this any better?

![image](https://user-images.githubusercontent.com/641685/49591687-2098b480-f93d-11e8-874e-a1de2e1db90d.png)

I've definitely struggled with iconifying the stashing. 

Also FYI, I will be adding a setting to turn off those SCM menu additions as I just realized I was missing that control - while I have it for all of the other additions)

**Comment by usernamehw** [comment]
What about `pack` `unpack` sort of icons:

<img src="https://user-images.githubusercontent.com/9638156/49592568-83f90580-f982-11e8-80d8-f69abcffc157.png" width="50" height="50"> <img src="https://user-images.githubusercontent.com/9638156/49592569-83f90580-f982-11e8-9611-9301ffe6e62a.png" width="50" height="50">

⬆️ From: https://www.iconfinder.com/icons/507777/arrow_box_crate_downwards_pack_ship_icon

**Comment by eamodio** [comment]
They would be even heavier than the current icon and at 16px I think they would be really hard to see.

**Comment by jrieken** [comment]
>  Do you not like the command there or just the icon itself? 

Now that you ask me, actually not sure. I always like less UI so yeah, I probably don't want the icon there.

**Comment by eamodio** [comment]
Is the alternative icon less offensive or not an improvement? 😉

**Comment by jrieken** [comment]
yeah, better/lighter but still an icon. I'd prefer a secondary command in the *context*-menu

**Comment by eamodio** [comment]
Here one more alternative
![image](https://user-images.githubusercontent.com/641685/49610551-e34c1b00-f96c-11e8-8783-22f25eb24b30.png)

**Comment by eamodio** [comment]
Fixed in GitLens 9.2.2

**Comment by joaomoreno** [comment]
@misolori We're still having people which are confused by the icon. https://github.com/Microsoft/vscode/issues/65715

I wonder if you have some thoughts?

**Comment by misolori** [comment]
It seems to me that other git clients use some type of arrow:

|GitKraken|Sublime Merge|
|---|---|
|<img width="108" alt="image" src="https://user-images.githubusercontent.com/35271042/50913012-4d326700-13e8-11e9-9f44-a920f8ffc04f.png">|<img width="93" alt="image" src="https://user-images.githubusercontent.com/35271042/50913132-8d91e500-13e8-11e9-9b52-06707b612232.png">

Played around with a few Octicons to see which could work better and this is the only one I found that was decent enough (though not sure if it's any better):
<img width="350" alt="image" src="https://user-images.githubusercontent.com/35271042/50918209-76f18b00-13f4-11e9-8d61-4a4bde19a35e.png">

**Comment by joaomoreno** [comment]
Ohh I like that! What do you think @jrieken @eamodio?
