### ISSUE TITLE
虚拟内存无法释放，磁盘爆满

### ISSUE THREAD

**Issue by udidi** [Microsoft/vscode#64428]
- VSCode Version:  1.29.1 (system setup) bc24f98b5f70467bc689abf41cc5550ca637088e
- OS Version: Windows 10 1809 17763.134

Steps to Reproduce:

1. 电脑的虚拟内存设置为“自动管理所有驱动器的分页文件大小”
2. 工作一段时间（我使用 python 编程和调试大约 2 小时
3. 打开设置-系统-存储-本地储存-系统和保留，可以看到虚拟内存非常不正常，我最大达到过 50G+
4. 此时 C 盘一般容量就满了，然后卡机，我也是因此才发现这个问题

Does this issue occur when all extensions are disabled?: Yes
我已经尝试了禁用所有插件，并再次遭遇了这个问题。

目前的解决办法：
手动设置系统的虚拟内存

**Comment by jrieken** [comment]
Please file issues in English. Thanks.
