### ISSUE TITLE
Duplicates Character When Using Special Characters in Mac OS 

### ISSUE THREAD

**Issue by The33Coder** [Microsoft/vscode#64420]
- VSCode Version: 1.29.1
- OS Version: 10.14.1

Steps to Reproduce:

   1. Use a latin keyboard layout (like English)
   2. Press a letter until appears his variations
   3. Choose one

![dec-05-2018 11-46-30](https://user-images.githubusercontent.com/12548652/49508654-83c61080-f883-11e8-819e-a1e12c6716d7.gif)

Does this issue occur when all extensions are disabled?: Yes

I know there are other same issues open. But they've been around for a long time. And except to see closed Issues. I don't see any solution.

**Comment by alexandrudima** [comment]
@The33Coder I cannot reproduce. I am long pressing the letter and then choosing a variant using 1, 2, 3, etc.:

![kapture 2018-12-05 at 21 59 52](https://user-images.githubusercontent.com/5047891/49543687-28267200-f8d9-11e8-9717-96777d685733.gif)

**Comment by The33Coder** [comment]
What additional information could be of some help?

**Comment by alexandrudima** [comment]
@The33Coder What are the precise (don't spare any details) steps you do?

**Comment by The33Coder** [comment]
Ok sorry. I choice the letter with a number. For example : 
- I long press on key `a`
- The selection display showing
- I press number `1`
- VSCode write `aà`

**Comment by alexandrudima** [comment]
@rebornix Could you please also try to reproduce?

@The33Coder Can you please try to disable all extensions and comment out all the `settings.json`? Does this reproduce in a new, untitled file, or only in specific file types?

**Comment by rebornix** [comment]
Reproduce steps:

* `defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool true` if you changed this before
* Add French input method
* Type a, which is the key with `q` print if you are using ASCII keyboard

I can't reproduce this issue with US Intl, so it might be an IME issue with some specific languages but I need to dig into it more.

**Comment by The33Coder** [comment]
I just found the culprit. It's the [vim](https://github.com/VSCodeVim/Vim) extansion!
I don't know why, but I had it disabled when I tested it.
