### ISSUE TITLE
Deleted branches appear on "Pull from..." select dropdown list

### ISSUE THREAD

**Issue by macbielecki** [Microsoft/vscode#64431]
Deleted branches appear on "Pull from..." select dropdown list (like if they were cached somewhere):
![image](https://user-images.githubusercontent.com/29729527/49516338-ae22c880-f899-11e8-894a-07c49b2e82f2.png)

Version: 1.30.0-insider (user setup)
Commit: 04cbc78e23eeddc368d634ed52402dbc6f28ebc9
Date: 2018-11-23T10:06:54.093Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.15063

**Comment by joaomoreno** [comment]
This is how Git works. If you delete a branch on the server, it doesn't mean it's deleted on your local repository. There's a `Git: Fetch (Prune)` command for that.

https://railsware.com/blog/2014/08/11/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/
