### ISSUE TITLE
Code "touches" the .gitignore file constantly

### ISSUE THREAD

**Issue by druellan** [Microsoft/vscode#6443]
- v1.1.1
- Win7 64bits

I'm using Browser Sync, watching all files, and I've found that Code "touches" the `.gitignore` file constantly:

- At startup, twice.
- When you save a file
- Every X seconds

![2016-05-17_10h38_10](https://cloud.githubusercontent.com/assets/6965667/15340828/eb4bdf10-1c61-11e6-8bf5-51da93ee1660.png)

The file is not changed at all, so this looks like an unwanted behavior or a bug. Any ideas?
Thanks!

**Comment by joaomoreno** [comment]
Code runs `git status` often in order to figure out what the status of the repository is. `git status` touches the `gitignore` file, just because.

**Comment by druellan** [comment]
Thanks @joaomoreno. Fair enough.
