### ISSUE TITLE
Extension Pack: Uninstall dependencies from pack if they are removed in an update

### ISSUE THREAD

**Issue by orta** [microsoft/vscode#64436]
Hi there, we've been running an extension pack [for Artsy](https://github.com/artsy/vscode-artsy) for a few months now and it's been great. 

We've had a bit of churn in our extensions, and hoped that vscode might be able to handle the uninstallation of dependent extensions when we remove a value form the `extensionPack` keys

e.g.: Between v1 and v2

```diff
    "extensionPack": [ 
        "Orta.vscode-danger",
-        "misogi.ruby-rubocop", 
-        "rebornix.ruby", 
        "mjmcloug.vscode-elixir", 
```

VS Code would know that `misogi.ruby-rubocop` and `rebornix.ruby` were installed via this pack (and not a user install) and thus offer (or automatically) remove them from the local setup.

**Comment by sandy081** [comment]
We do not differentiate how an extension is installed. But we uninstall all extensions when the pack is uninstalled. Same can be done when pack is updated.
