### ISSUE TITLE
cpu profile cannot be opened

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64437]
* run slow extension so that it dumps a profile
* open the profile in dev tools
* :bug: the profile doesn't open...

**Comment by roblourens** [comment]
This doesn't seem to work. I just have an extension with 

```ts
while(true) {
    console.log('hi')
}
```

And start it, and the EH spins but I never see a message, what am I missing?

**Comment by roblourens** [comment]
But I do see the message in devtools and I can open the profile, so this particular issue is 👍
