### ISSUE TITLE
Can't modify each file when comparing two different files

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6444]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. In the Explorer viewlet, right click on a file > Select for Compare
2. Right click another file > Compare with 'selected.js'
3. Try to modify the first file (left side compare window)

It makes sense when comparing the changes of a single file, but when two different files are being compared you should be able to modify the first opened one.

**Comment by bpasero** [comment]
@vsccarl please use the issue search to first find duplicates. Thanks.
