### ISSUE TITLE
HTML formatting breaks closing bracket to its own line

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#64446]
Issue Type: <b>Bug</b>

This never used to happen...

I have my html format settings as:
```
  "html.format.unformatted": "wbr,span,code",
  "html.format.wrapAttributes": "force-aligned",
  "html.format.wrapLineLength": 0,
```

For some reason, it's now putting the closing `>` on a line by itself, as in 
```
        <mat-tab label="TabTabHeader2"
          ><p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolores, cumque perferendis molestiae nulla iusto
          </p></mat-tab
        >
```

![cleanshot 2018-12-05 at 13 39 42](https://user-images.githubusercontent.com/835148/49536071-abbd7000-f893-11e8-9a71-86e3eb255c37.gif)

VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T12:13:44.894Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|-psn_0_744609265|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-svgo|ajh|0.1.0
Bookmarks|ale|10.0.0
project-manager|ale|10.0.0
ACF-Snippet|ant|1.9.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.45
prettier-vscode|esb|1.7.2
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.13.1
svg|joc|0.1.4
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.9
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.22.0
polacode|pnp|0.2.2
quicktype|qui|12.0.46
LiveServer|rit|5.3.1
code-settings-sync|Sha|3.2.2
stylelint|shi|0.47.0
rewrap|stk|1.9.1
ayu|tea|0.17.0
sort-lines|Tyr|1.7.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by octref** [comment]
Prettier recently added html support. And it overrode our HTML formatter. You can do this to disable it.

```
    "prettier.disableLanguages": [
      "vue",
      "html"
    ]
```
