### ISSUE TITLE
a bogus "remoteRoot" should not result in file not found errors

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64440]
- use a simple "hello world" node.js program 
- create a launch config for it and set a breakpoint
- add a bogus `remoteRoot` path to the launch config, e.g. `"remoteRoot": "/foobarxxxxxxx"`
- press F5

Observe: 
this error notification shows up:
<img width="469" alt="2018-12-05_17-28-53" src="https://user-images.githubusercontent.com/1898161/49528052-77f24280-f8b3-11e8-9b7e-0cd80380fcfe.png">

A bogus "remoteRoot" path should not result in this type of error because a non-matching "remoteRoot" path should be ignored.

This problem does not occur with node-debug (legacy).

BTW, the value of `${workspaceFolder}` is `/Users/weinand/MS/Projects/REPROS/bug64332`

**Comment by roblourens** [comment]
It seems that node-debug still applies the bogus remoteRoot, it just returns the file as readonly. With legacy if I set the bogus remoteRoot then I can't set BPs in that file but I do hit a debugger statement in a readonly file. The code between the two DAs is basically the same.

https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L3959 I think will return a path starting with `..`.

**Comment by roblourens** [comment]
node-debug will still have this issue

**Comment by jrieken** [comment]
@roblourens I have the config below and it doesn't work - tho I don't see an error. Not sure if that's the expected outcome of this or not

```
{
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "remoteRoot": "/foobarxxxxxxx",
            "program": "${workspaceFolder}/app.js"
        }
    ]
}
```

**Comment by weinand** [comment]
In a remote setup we cannot determine whether a remoteRoot path is bogus or not since we do not have access to the remote filesystem. So Rob's "expected behavior" is correct.
