### ISSUE TITLE
The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)

### ISSUE THREAD

**Issue by kalakandi** [Microsoft/vscode#64449]
Issue Type: <b>Bug</b>

Steps to Reproduce:

Open VSCode
Open a folder
Ctrl + `
Error Message:The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.11.0
vscode-yaml|red|0.1.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/62953
