### ISSUE TITLE
Feature request: Aggregated debug console

### ISSUE THREAD

**Issue by tzachshabtay** [Microsoft/vscode#64445]
I have in my `launch.json` a compound for debugging server and client together.
In older versions of `vscode` I would see both outputs in the same debug console.
Now, however, there's a drop-down in the debug console to select between Client & Server.

I like the split, on one hand, but sometimes I do want to see the aggregated view that we used to have (so I don't need to zig-zag if I'm just looking for an error on either side, for example, or if I'm debugging a complicated workflow between client and server and want a nice ordered output with everything).

I wish the drop-down on the debug console, instead of being a single selection drop-down, would be a multi-selection drop-down (i.e a list with checkboxes), so I could check/uncheck the outputs I would like to see in the debug console.

**Comment by weinand** [comment]
Yes, we need this.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/62419
I see you assigned this to december, so I assigned that one also
