### ISSUE TITLE
All I want to do is run 'npm run debug'

### ISSUE THREAD

**Issue by CannibalKush** [Microsoft/vscode#64447]
I am in the process of setting up a multi-folder workspace and associated launch configuration for debugging.

One launch config just needs to run 'npm run debug' as part of its own launch.json, so that the workspace compound task can run all three simultaneously.

No debugger. No node. Just 'npm run debug'.

So I've created a task that runs the command directly in the shell, but it's proving impossible to just run that task from launch.json.

Can we add a launch configuration that only runs a task, and nothing else?

**Comment by weinand** [comment]
Just press the "Add Configuration..." button in the launch.json editor and select "Launch via NPM".

Make sure that your npm "debug" script configures node so that it uses debug port "9229". If a different port is used, change the "port" attribute in launch config accordingly.

**Comment by weinand** [comment]
debug

**Comment by CannibalKush** [comment]
That's the thing, though, i'm actually running ng serve, not node. Because the debugger never attaches, the launch config fails.

**Comment by weinand** [comment]
The feature doesn't depend on node, but it requires a debug port and the Chrome Debugging Protocol.

**Comment by CannibalKush** [comment]
Thanks, I checked that out too. The problem with that specific guide was that it relies on me the user running 'ng serve' manually which is exactly what I'm trying to automate.

**Comment by weinand** [comment]
The recipe shows how to create a task that runs "ng".
Then add that task as a "preLaunchTask" to the launch config.

**Comment by CannibalKush** [comment]
But that doesn't work because ng serve never really completes as a task? Therefore it never gets to the part where it launches chrome. So that config will run ng serve correctly, that's true, but after i decide to terminate, a random, very-late Chrome window will appear.

If there's some obvious information there I've missed somehow, I'll go add it in myself!

**Comment by weinand** [comment]
Try to run "ng" as a background task that runs indefinitely. 
Here is a similar "watcher" task from an VS Code extension project:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc-watch",
            "isBackground": true,
            "presentation": {
                "reveal": "never"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
You will have to adapt the task from above to your case, e.g. replace "watch" by "debug".

and in your launch config add:
```
            "preLaunchTask": "npm: debug"
```

**Comment by CannibalKush** [comment]
Thanks @weinand I've got it working. In my opinion the tutorial created a lot of confusion, so I made a PR to it, please have a look if you have the time.
