### ISSUE TITLE
PowerShell Terminal cannot find Add-AzureRmAccount after running Install-Module AzureRM.profile 

### ISSUE THREAD

**Issue by bmike** [Microsoft/vscode#64444]
Issue Type: <b>Bug</b>

1. Install VSC Version 1.29.1 (mac)
1. Install PowerShell 6.1.1 (mac)
1. Open a json or ps1 file and then choose the terminal for powershell.
1. Execute commands:
```
     PS /Users/mike> Install-Module AzureRM.profile
     PS /Users/mike> Get-Module (shows 5.8.2)
```
1. Running the Add-AzureRmAccount throws an error
```
    PS /Users/mike> Add-AzureRmAccount
    Add-AzureRmAccount : The term 'Add-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
```
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y31 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv|-psn_0_5768576|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-elixir|mjm|1.1.0
python|ms-|2018.11.0
PowerShell|ms-|1.9.0
team|ms-|1.144.1
elm|sbr|0.24.0

</details>

**Comment by bmike** [comment]
If this is somehow deprecated or I'm not following a setup guide, please point me at the "rtfm" - I don't see any deprecation warning at https://docs.microsoft.com/en-us/powershell/module/AzureRM.Profile/Add-AzureRmAccount?view=azurermps-4.4.1&viewFallbackFrom=azurermps-6.13.0 for this command but I'm not super familiar with Microsoft dev documentation.

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
