### ISSUE TITLE
Support for full file path in "when" clause

### ISSUE THREAD

**Issue by ewanharris** [microsoft/vscode#64451]
I can currently use the filename of a file in a when clause by using `resourceFilename`. But I would like to offer a editor context menu item only for js files under a certain path, I took a look through the [when clauses](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) and nothing appears to offer this functionality right now.

Example:

I would like to only add to the editor context menu for files under the `app/controllers` directory.

```json
{
	"command": "myExtension.openRelatedFile",
	"when": "editorLangId == javascript && resourceFilePath =~ /app\/controllers/"
}
```

Is this something that's currently possible and I'm just missing something 🙂? I tried searching existing issues/SO and found nothing

**Comment by jrieken** [comment]
cc @isidorn @alexandrudima

**Comment by sajinieKavindya** [comment]
What is the status of this feature? I have the same user case where I need to add an editor context menu item only for a specific file path.

**Comment by isidorn** [comment]
This is currently not possible. However it is a fair feature request.
