### ISSUE TITLE
Option for setting "editor.renderLineHighlight" and possibly "editor.renderColumnHighlight" to "background"

### ISSUE THREAD

**Issue by DanielPintilei** [microsoft/vscode#64454]
It would be nice to be able to set the current line's background to something solid. The current style is a bit hard to spot for me.
I know there are themes that do this but I think having this option regardless of a theme's opinion is better.

Also a setting for the active column would be great. Here is an example:
 
![image](https://user-images.githubusercontent.com/9828983/49544980-fc10ee00-f8e4-11e8-8370-3929ff8baa53.png)

**Comment by alexandrudima** [comment]
The vertical ruler part of the screenshot is captured in https://github.com/microsoft/vscode/issues/15027

If you choose a different theme, like Monokai, that one uses a background and not a border for the current line highlight. This can be customized from a theme or from `settings.json`.
