### ISSUE TITLE
* on last line of jsdoc style comment breaks highlighting

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64455]
Have a comment like

``` 		
		/**
		 * */
```

The rest of the file is colored as a comment, related to markdown parsing in the comment? The last line can have anything else in it, if it has a * in it this is triggered.

![image](https://user-images.githubusercontent.com/323878/49545916-e3c4b300-f893-11e8-8998-f043cd4e8269.png)

**Comment by mjbvz** [comment]
Good find
