### ISSUE TITLE
External terminal can be exe with a space in the path

### ISSUE THREAD

**Issue by HaydenSeward** [Microsoft/vscode#64453]
Issue Type: <b>Bug</b>

In vscode you can change the path of your external terminal but if the path contains a space then the path gets cut off were the path is.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.35.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3
vim|vsc|0.16.13

</details>

**Comment by Tyriar** [comment]
I just put cmd.exe in a folder with a space in it and ctrl+shift+c it worked fine?
