### ISSUE TITLE
[theme] color of plain text (and un-scoped code)

### ISSUE THREAD

**Issue by ZYinMD** [Microsoft/vscode#64458]
When developing themes, I couldn't find how to change the default fallback foreground color for colorless texts .

Basically there are two kinds: 
1. Plain text, which are un-scoped.

2. ~~Code pieces that are scoped, but weren't assigned a color in the theme~~
  update: I've found that this kind can usually be colored with the scope `source`

In .tmTheme, it's just the first rule with no name nor a scope:
```
<dict>
  <key>settings</key>
    <dict>
      <key>foreground</key>
        <string>#777</string>
    </dict>
</dict>

```
When converted from a .tmTheme to .json, it'd also be converted into a rule with no name nor scope:
```    
"tokenColors": 
  [
    {
      "settings": {
        "foreground": "#777"
      }
    }
  ]
```
However it seems to have zero effect in VSCode.

Maybe it's style-able not with `tokenColors`, but with `colors`? For instance these two look promising:
```
"colors": {
    "foreground": "#777",
    "editor.foreground": "#777"
}
```
But they also have no effect.
In fact, I believe I have tried every single property from the long long doc: [https://code.visualstudio.com/docs/getstarted/theme-color-reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference), but didn't find the answer.

**Comment by usernamehw** [comment]
`"tokenColors"` is an array. Do you have the brackets somewhere? `[]`

**Comment by ZYinMD** [comment]
Sorry it was a typo, edited.

**Comment by usernamehw** [comment]
`"tokenColors"` is an array. But `"colors"` is an object.

**Comment by ZYinMD** [comment]
Yes, sorry, edited too. But in my theme file they were both correct. It was a full blown theme that is working properly.

**Comment by ZYinMD** [comment]
Update: 

I found that although plain text is not scoped, different themes still have different fall back colors for plain text, which makes me believe this fall back color is indeed defined inside `colors`, not `tokenColors` . 

I deleted everything from the `tokenColors` of a theme, and then this theme loses all colors, but still show plain text as a certain shade of grey, which is different from other themes, which confirms my theory.

However I still can't find which property it is from [the doc](https://code.visualstudio.com/docs/getstarted/theme-color-reference). For example, it's not `foreground` or `editor.foreground`

**Comment by octref** [comment]
Does this work for you?

```
  "tokenColors": [
    {
      "settings": {
        "foreground": "#d8dee9ff",
        "background": "#2e3440ff"
      }
    },
```

In your theme, specify one without scopes and that should be used as default.

**Comment by ZYinMD** [comment]
Hi @octref,  no it doesn't work for me, does it work for you?

**Comment by ZYinMD** [comment]
I've solved it. It indeed is "editor.foreground" in `colors`, not `tokenColors`, as I had guessed above. However, for some reason it doesn't take effect immediately when you change it in settings.json, which was why I thought it wasn't `editor.foreground` before.

For instance, in settings.json:
```
"workbench.colorCustomizations": {
  "[Monokai]": {
    "editor.background": "#000", // changing this will reflect immediately, as with all other color settings
    "editor.foreground": "#0ff", // change to this becomes effective after reload, which is unique
  },
}
```

Closed.
