### ISSUE TITLE
Expanded item in debug console collapses when new output is added

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64460]
I am in a debugging session where when new output is added to the debug console, expanded objects are collapsed. This only happens in EH debugging, not node, for some reason.

Add this code to the activate method of an extension:

```js
    setInterval(() => {
        const obj = {
            added: [],
            removed: [{
                blah: 123,
                foobar: 432
            }],
            changed: []
        };
        console.log({ a: obj, a2: 123, a3: [obj, obj] });
    }, 4000);
```

![dec-05-2018 14-30-56](https://user-images.githubusercontent.com/323878/49548381-66e90780-f89a-11e8-923c-8e58221d0159.gif)

I debugged this enough to verify that nothing is calling "collapse" on the tree, it seems like it's just happening when the DataTree refreshes. https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/tree/asyncDataTree.ts#L524

I can't figure out why this doesn't happen when debugging a simple node script with the same code.

**Comment by isidorn** [comment]
@roblourens nice catch. It was only happening in this case since we comput ids differently in this corner case when the output is coming from the EH
