### ISSUE TITLE
Arrow navigating search history + multiline search input

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64466]
Issue Type: <b>Bug</b>

**Repo**
1. Perform few workspace searches
1. Enter some multiline search text in the workspace search box
1. Use arrows to navigate lines in the expanded search input box
1. Press up arrow to go through the lines on the multiline input. 

**Bug**
When the cursor hits the top of the input, the next up arrow goes to the previous search history entry. This caught me off guard

VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T12:13:44.894Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_7104198|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by roblourens** [comment]
This is by design, what do you expect?

**Comment by mjbvz** [comment]
Main thing since we probably can't change the keybindings: it's not clear when you're at the top of the search input. May fall under #64311
