### ISSUE TITLE
Unterminated template literal error when terminated on same line

### ISSUE THREAD

**Issue by dale-dixon** [Microsoft/vscode#64465]
Issue Type: <b>Bug</b>

When template literal is on single line a "Unterminated template literal" error occurs

![image](https://user-images.githubusercontent.com/20524988/49550692-79733900-f8ba-11e8-9318-9846782a9b88.png)

no error if terminated on new line
![image](https://user-images.githubusercontent.com/20524988/49550822-ec7caf80-f8ba-11e8-827c-c287aef2d0e5.png)

Expected behavior:
```typescript
const map = `U:\`;  // no error
```
VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T06:19:36.555Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.95GB (1.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-wasm|dts|1.2.1
gitlens|eam|9.0.2
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
auto-rename-tag|for|0.0.15
todo-tree|Gru|0.0.107
beautify|Hoo|1.4.7
code-beautifier|mic|2.1.0
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
vetur|oct|0.14.3
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.1
tsimporter|pmn|1.2.14
tslint-vue|pro|1.5.6
code-settings-sync|Sha|3.2.2
ayu|tea|0.17.0
vscodeintellicode|Vis|1.1.0

(11 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Your code is invalid. `\` escapes the next charter inside of template literals so backslash backtick is how you insert a literal backtick in a template string. 

You probably want to escape the backslash:

```js
const map = `U:\\`
```
