### ISSUE TITLE
Issue reporter should prompt for unsaved changes, or persist changes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64462]
After #59845, I can close the issue reporter with cmd+w, but if I have unsaved changes, they are all lost. It should show a confirmation prompt before losing text.

We might even want this for November, it's frustrating to hit the wrong button and lose work.

**Comment by RMacfarlane** [comment]
A confirmation prompt should now be shown if you hit cmd+w with text in the title or description without having submitted
