### ISSUE TITLE
task/launch input arguments: make intellisense use "type" as a discriminator

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64464]
(I could not test this feature earlier because Intellisense was broken in yesterday's build).

Currently Intellisense in the "inputs" section suggests the "options" attribute for both input types.
I suggest to improve the schema so that "options" is only suggested for the "pick" type.

We do this for launch config debug types too.
You can ask @isidorn for details.

**Comment by alexr00** [comment]
Yes, we should do this. Duplicate of #64387
