### ISSUE TITLE
Could not debug typescript when outDir is a symbolic link directory

### ISSUE THREAD

**Issue by chopdown** [Microsoft/vscode#64478]
- VSCode Version: v1.29.1
- OS Version: Windows 10

Steps to Reproduce:

1, check out https://github.com/chopdown/test_vscode_mklink.git
2, exec link.bat
3, set break point on Test.ts
4, run & debug

Does this issue occur when all extensions are disabled?: Yes

I want to build the typescript to another repository ( artist directory). They have no code permission, The program will read the configuration at that directory. So I mklink the directory to the code/dist directory.  (I don't want use  absolute path). It's OK,  except can't debug on this scenarios.

**Comment by roblourens** [comment]
This works with 

```
"runtimeArgs": [
    "--preserve-symlinks",
    "--preserve-symlinks-main",
],
```

added to the launch config. This is documented here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks
