### ISSUE TITLE
Editor indentation autodetection not working and manually set indentation keeps getting reset

### ISSUE THREAD

**Issue by mschuckmann** [Microsoft/vscode#6447]
- VSCode Version:1.1.1
- OS Version: Ubuntu 15.10 64bit

Steps to Reproduce:

1. User settings set like so: 
   "editor.tabSize": 2, 
   "editor.insertSpaces": true,
   "editor.detectIndentation":true,
2. Open a C/C++ project with 4 space indentation. 
3. Open a file in the project, observe on the status bar Spaces:2 (expected: Spaces: 4)
4. Click on the Spaces:2 setting in the status bar and select "Detect Indentation from Content". 
5. Observe that the status bar now says Spaces: 4. 
6. Switch to a different file with indentation of 4 spaces, it doesn't seem to matter. 
7. Observe that the status bar now say Spaces: 2 (expected: Spaces: 4) 
8. Switch back to the original file, observe that the status bar still stays Spaces: 2 (expected: spaces 4)

I've seen similar behavior with Makefiles and tabs, I manually switch to tab mode and every time I toggle back and forth from another file the tab mode is reset to spaces.

**Comment by alexandrudima** [comment]
@mschuckmann From what you are describing, it seems that "Detect Indentation from Content" does the right thing (i.e. guesses spaces@4 when the file contains mostly spaces@4), but it also appears that "Detect Indentation from Content" is not executing or is being overwritten.

The user settings can be overwritten by workspace settings (does the folder you open define `.vscode` settings) and can be overwritten by extensions (do you perhaps have installed an extension that might do something with the indentation settings -- easiest is to check if the issue reproduces after closing all VSCode instances and running `vscode --disable-extensions`).

**Comment by mschuckmann** [comment]
So running vscode with --disable-extensions does appear to fix the problem. 
And it appears that the culprit was the EditorConfig for VS Studio extension. 

Thank you for the suggestion.

**Comment by alexandrudima** [comment]
Cool, just look in your system for an `.editorconfig` file somewhere in your parent directories or in your user folder, most likely settings are being picked up from there.
