### ISSUE TITLE
Need a better grammar support for Rust lang

### ISSUE THREAD

**Issue by zimond** [microsoft/vscode#64488]
This problem is raised up for several times before (#49932, #45628) But not resolved. VSCode team member replies to these issues as: We are using the same grammar with Atom. In fact, Atom has already changed to [tree-sitter syntax](https://github.com/tree-sitter/tree-sitter-rust) as the bundled Rust language grammar support package (https://github.com/atom/atom/tree/master/packages/language-rust-bundled).

However, Vscode's bundled rust support extension is based on Zargony's [package](https://github.com/zargony/atom-language-rust) which is not updated for nearly a year and many issues open with no reply at all.

Currently every highlighting problem in https://github.com/Microsoft/vscode/issues/49932 still happens and that's not simply a "theme" thing as @mjbvz mentioned in the orignal issue, I think.

In the original issue, @mjbvz  also declares that 
> Since we use the same grammar, I believe this is just a matter of theming. As far as I can tell, the atom rust extension injects its own themeing rules to provide better colors.

the plugin he referred to is not even Zargony's package. it's a package from @miqh, who also ported the atom package to vscode, and fails to correctly provide grammar for Rust as well.

Hope that I get everything right, thanks for any help.

**Comment by NateLing** [comment]
me too

**Comment by alexr00** [comment]
As @zimond said and @mjbvz said in #45628, we get our rust grammar from the community. If we tried to provide grammars and theming for every language ourselves then the support would be much worse since we aren't experts in all languages 😊 If there is a better, well supported, TM grammar that we can pull in for rust then I'm happy to pull it in and try it out.

**Comment by zimond** [comment]
This is ridiculous. The bundled rust syntax is not only not complete, but also incorrect (Check [this issue](https://github.com/zargony/atom-language-rust/issues/133) as a crucial bug), with many keywords missing. If you insist of vscode team is not capable of "provide grammars and theming for every language ourselves", then please just remove the bundled package.

And I would like to state it one more time: This is not about "theming". Just mark as duplicate could not make any improvement.

**Comment by zimond** [comment]
I believe that this issue is in fact related to #50140, not just a textmate grammar or theming problem.

**Comment by alexr00** [comment]
@zimond we use the *extension-candidate label to keep track of closed issues that would be best solved by someone writing and maintaining an extension. Since this issue covers both theming (extension solvable) and grammar (also techinically solvable with an extension, but we do provide it inbox) I'll reopen it for the grammar. 

If I thought I could get away with just removing the built in rust extension then I would. However, there are people out there who are using it so I can't just take it away from them even if it has flaws.

**Comment by alexr00** [comment]
Given the community feedback that VS Code's rust grammar has problems, we're looking for a more frequently maintained TM rust grammar. If anyone is interested in contributing a new grammar for rust please reach out!

**Comment by NateLing** [comment]
see this #45628 and this #42145 ， They didn't take it seriously  @alexr00  @zimond

**Comment by zimond** [comment]
@NateLing No need to push it this hard. I think the lack of correct syntax highlighting is due to the limitation of TextMate's grammar format. Now vscode team is thinking about using visual studio's grammar as an upgrade. I think all we could do is wait for it, or maybe tree-sitter support.

**Comment by Geobert** [comment]
There are so many issues with highlighting in so many languages that can be solved by using tree-sitter, I don't get the mentality of keeping TM which is said to be hard, limited etc.

**Comment by georgewfraser** [comment]
I've added support for tree-sitter via an extension: https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter

Rust is supported using the same tree-sitter grammar as Atom:

<img width="1236" alt="rust" src="https://user-images.githubusercontent.com/1369240/57989458-a9209280-7a4f-11e9-9ebc-1f52ed2fd599.png">

**Comment by zimond** [comment]
@georgewfraser you are an angel

**Comment by jk-gan** [comment]
@georgewfraser Thanks for that!

**Comment by Geobert** [comment]
There is another extension base on tree-sitter with Rust support as well:
https://github.com/EvgeniyPeshkov/syntax-highlighter/

I'm not the author, but I've helped him to improve the highlighting by giving him as much info as possible on Rust (as he doesn't know much about Rust). Still some issues in discussion, but out of the box, it does a pretty good job.

**Comment by dustypomerleau** [comment]
@alexr00 I have released an improved TextMate grammar via the [Rust Syntax](https://marketplace.visualstudio.com/items?itemName=dustypomerleau.rust-syntax) extension. I am happy to submit a PR to make this the default in VS Code. The current arrangement, where code comments indicate that the Atom grammar is upstreamed (and therefore PRs should be submitted to Atom instead) I think discourages people from trying to get grammar improvements merged. Given the size of the VS Code community at this point, would you be happy to accept direct PRs on grammars?

**Comment by alexr00** [comment]
@dustypomerleau allowing direct PRs on the grammars means that we are accepting maintenance responsibility for the grammar, which isn't feasible given the size of the team and the diversity of languages we have grammars for.  

I am more than happy to move away from the Atom grammar though. If the Rust Syntax extension provides a grammar file that VS Code can consume, please do provide a pointer to it and I can try pulling it into VS Code and we can see what others think of the new grammar for a month or so.

**Comment by dustypomerleau** [comment]
@alexr00 That would be awesome—the generated JSON is in [this file](https://github.com/dustypomerleau/rust-syntax/blob/master/syntaxes/rust.tmLanguage.json). I appreciate your time.

**Comment by alexr00** [comment]
@dustypomerleau I adopted your grammar in a PR and I have some questions in there: https://github.com/microsoft/vscode/pull/108254

**Comment by alexr00** [comment]
For everyone who has been following this issue, dustypomerleau/rust-syntax is the default Rust grammar for VS Code now. Closing since this issue has been satisfied.

**Comment by alexr00** [comment]
Verification is accomplished through the grammar colorization tests.
