### ISSUE TITLE
Code Helper consumes 100% CPU

### ISSUE THREAD

**Issue by prograk** [Microsoft/vscode#64486]
Issue Type: <b>Bug</b>

It just happens everything I'm using VSCDODE

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 5|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
githistory|don|0.4.4
gitlens|eam|9.0.1
tslint|eg2|1.0.40
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-beautifier|mic|2.1.0
python|ms-|2018.11.0
vscode-css-peek|pra|2.2.0
code-settings-sync|Sha|3.2.2
css-auto-prefix|spo|0.1.7
autoimport|ste|1.5.3
highlight-matching-tag|vin|0.8.4
quokka-vscode|Wal|1.0.170
html-css-class-completion|Zig|1.17.1

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
