### ISSUE TITLE
Intellisense will stop working when use std::bind incorrectly.

### ISSUE THREAD

**Issue by Frank-Shaw-FS** [Microsoft/vscode#64487]
Issue Type: <b>Bug</b>

Auto complement and error detect not work until I reload the windows, but it will soon stop working.

```
typedef std::function<void(const std::string, const std::string)> ReceiveCallBack;

class Parser  {
public:
  void Parse(const std::string & str, ReceiveCallBack cb) {
    cb(str, str);
  }
};

class UseParser {
public:
  void TP(const std::string s, const std::string b) {
    std::cout << "the s is " << s << " the b is " << b << std::endl;
  }

  void TestP() {
    Parser p;
    p.Parse("Hello", std::bind(&UseParser::TP, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3)); 
  }
};

```
The above code pass one unnecessary argument and it will trigger the bug in my PC.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
markdown-preview-github-styles|bie|0.1.4
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.0.2
vsc-material-theme|Equ|2.6.2
autoconf|mae|0.0.7
python|ms-|2018.11.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.7.0
vscode-docker|Pet|0.4.0
code-settings-sync|Sha|3.2.2
cmake|twx|0.0.17
vim|vsc|0.16.13
markdown-all-in-one|yzh|1.7.0
vscode-proto3|zxh|0.2.2

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> I am sorry for submiting the bug in the wrong repo, the bug is for c++ extension, please help to delete it.

No worries - we get that a lot. Thanks for getting back to us.
