### ISSUE TITLE
Built in HTML formatter indents incorrectly following a <br> 

### ISSUE THREAD

**Issue by mredbishop** [Microsoft/vscode#64498]
Ubuntu 18.04
Code Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Steps to Reproduce:**

1. Add the following HTML to a html file:
```
<html>

<head>
    <title>some title</title>
</head>

<body>
    <p>
        <br>
    </p>
    <div></div>
</body>

</html>
```

2. Run the formatter, results in the following indentation:
```
<html>

<head>
    <title>some title</title>
</head>

<body>
    <p>
        <br>
    </p>
        <div></div>
</body>

</html>
```

Does this issue occur when all extensions are disabled?: Yes / **No**
However, manually disabling installed extensions, reloading and running format, the error still occurs:
![indent-error](https://user-images.githubusercontent.com/1096293/49575725-50df5380-f93b-11e8-88b8-7815247b3f24.gif)

**Comment by octref** [comment]
Doesn't happen to me. What's your html formatter setting?

![format](https://user-images.githubusercontent.com/4033249/50244343-8d23a280-0384-11e9-8e37-18ac9c162e90.gif)
