### ISSUE TITLE
Ctrl+D functionality publicizing

### ISSUE THREAD

**Issue by pashute** [Microsoft/vscode#64497]
Issue Type: <b>Feature Request</b>

Somehow let us know that tag rename in html can be done with Ctrl+D. Perhaps add as command:  Tag rename. 

I'm sure it exists somewhere with some other name. Don't rename the option, just add it as an extra option:  

    > Command:   Rename HTML tag or code.  (Ctrl+D)

Thanks.  Or call it refactor. Or both... 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by octref** [comment]
There is no "rename" functionality for HTML tags. What exactly are you asking for?
