### ISSUE TITLE
Shortcut "Ctrl+Shift+F12" is not working in terminal

### ISSUE THREAD

**Issue by CombeeMike** [Microsoft/vscode#64494]
![image](https://user-images.githubusercontent.com/30658772/49571474-afa3cd80-f939-11e8-890a-27fd0122476d.png)

- OS Version: Windows 10, Version 1803

Steps to Reproduce:

1. Bind shortcut `Ctrl+Shift+F12` to command `workbench.action.maximizeEditor`
2. Open terminal
3. Press `Ctrl+Shift+F12`
--> The command is not executed.

I guess the terminal captures the shortcut & won't let it bubble up to VSCode? Can and should this somehow be circumvented or would this break functionality in the terminal? Whilst I see that the terminal captures the shortcut, I don't see nothing useful it "does with it" but print an `@` character if the input is "free".

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
You can work around this by adding `workbench.action.maximizeEditor` to `terminal.integrated.commandsToSkipShell`
