### ISSUE TITLE
vscode.d.ts version 1.1.0 not available (empty)?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#6449]
- VSCode Version: 1.1.1
- OS Version: Windows 10

The `engine` attribute defines the VSCode _compatible version_ for the extension. Since I would like to limit the extension to work with at least version `1.1.0`, I tried to use it, but the `vscode.d.ts` downloads empty

Steps to reproduce:

1) Define `engine` as: 
```json
"engines": {
  "vscode": "^1.1.0"
},
```
2) Define `devDependencies` as:
```json
"devDependencies": {
  "vscode": "^0.11.x",
  "typescript": "^1.6.2"
}
```
3) Run `npm install`
4) Besides the command outputs no error, as you can see in the log below, the `vscode.d.ts` in `node_modules` is empty:
```
> project-manager@0.6.0 postinstall C:\Users\alefr\Documents\GitHub\vscode-project-manager
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.1.0
Found minimal version that qualifies engine range: 1.1.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/1.1.0/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
```
5) `vscode.d.ts` contents in `node_modules\vscode`
```
Not Found
export = vscode;
```

If I use `^1.0.0` it works, but I can't use this version, because only version 1.1.0 has the new `vscode.openFolder` command.

Thanks for your help.

**Comment by bpasero** [comment]
Fixed, please try again. Sorry.
