### ISSUE TITLE
There are many useless blank lines in vscode internal console

### ISSUE THREAD

**Issue by tjx666** [Microsoft/vscode#64499]
- VSCode Version: 1.29.1
- OS Version: win10 pro 1809

Steps to Reproduce:

1.
I want to use yarn in vscode, but there are many useless blank lines which makes me very annoyed。
![snipaste_2018-12-06_17-43-37](https://user-images.githubusercontent.com/41773861/49575822-9a9d5d80-f97e-11e8-99c1-db24c1b425b5.jpg)

2.

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
