### ISSUE TITLE
In-progress decoration issue

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#64492]
On master, but I think I have seen something similar on the gear icon in a recent build:
![image](https://user-images.githubusercontent.com/9205389/49570587-5a66bc80-f937-11e8-8e94-0f722c53d65d.png)

**Comment by chrmarti** [comment]
Better after a `git clean -xfd`, but still an issue (with reload):
![dec-06-2018 09-36-29](https://user-images.githubusercontent.com/9205389/49571780-7d46a000-f93a-11e8-99d4-0af8b1f7517f.gif)

**Comment by bpasero** [comment]
Electron 2 issue fixed in 3. There are duplicates.
