### ISSUE TITLE
Custom workspace shell settings not working anymore in 1.29

### ISSUE THREAD

**Issue by garu57** [Microsoft/vscode#64504]
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
(Portable Installation)

Does this issue occur when all extensions are disabled?: Yes

After installing 1.29.1 I no longer get the prompt to enable `terminal.integrated.shell*` settings in workspace setting and they are simply ignored.

Bug #61394 describes the problem and is closed as fixed in October milestone but in 1.29.1 the problem is still unsolved.

**Comment by garu57** [comment]
Sorry, seen right now #64284.
Using the Allow command as explained there works, so this can be closed.

Just out of curiosity, is the different behavior documented anywhere?

Thanks.

**Comment by Tyriar** [comment]
Hmm, it definitely works in Insiders so it should be fixed in 1.30.
