### ISSUE TITLE
macOS: first entry of context menu is selected with zoom level 1 in editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#64506]
Steps to Reproduce:

1. set zoom level to 1
2. right click into the editor
3. 🐛 the first entry of the menu is selected already

This does not seem to happen e.g. in the explorer and also not when zoom level is 0 it seems.

![image](https://user-images.githubusercontent.com/900690/49579498-ad973a00-f94c-11e8-8f9f-46f6e1ab8058.png)

**Comment by sbatten** [comment]
In editor, @joaomoreno  updated the anchor to be a specific width and shifts it left. This works well for the non-native case. https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/contextmenu/contextmenu.ts#L93

However, the native context menu service does not use this logic and instead shifts it back to the right (where it was clicked) and lets the OS handle it. I believe the non-integer zoom factor is just getting the menu under the cursor causing this.

**Comment by sbatten** [comment]
@joaomoreno we could at least get back to the previous state if in the native case, we calculated the center of the anchor and used that point instead of the top left of the anchor

**Comment by joaomoreno** [comment]
Wouldn't that just break other places where the anchor is really a rectangle, like the `...` menus?

**Comment by sbatten** [comment]
@joaomoreno hmm... maybe it would have some negative cases. I mean specifically in the native context menu handler, we are ignoring the rectangular anchor today so in that case we could use it and use the center. Does that make sense?
