### ISSUE TITLE
Files not saving

### ISSUE THREAD

**Issue by Steffo99** [Microsoft/vscode#64505]
- VSCode Version: 1.30.0 (built from source at 351905fd534abbd66913cb98bb4849f172bf6fbc)
- OS Version: Arch Linux

Steps to Reproduce:

1. Open any file.
2. Make any edit.
3. Save the file (both Ctrl+S and File > Save).
4. The file isn't saved, and the unsaved dot · remains.
5. (Saving with File > Save as... works, but only if a new file is created and nothing is being overwritten.)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Steffo99** [comment]
Also, no errors show up in the Developer Tools or when running `code --verbose --level debug`.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Steffo99** [comment]
The problem persists even with extensions disabled.

I've noticed that every time I try to save, I get the message
```
[7716:1208/180842.925655:INFO:CONSOLE(1503)] "%cTRACE", source: file:///usr/lib/code-git/out/vs/workbench/workbench.main.js (1503)
[7716:1208/180842.926216:INFO:CONSOLE(1503)] "%cTRACE", source: file:///usr/lib/code-git/out/vs/workbench/workbench.main.js (1503)
[7716:1208/180842.926353:INFO:CONSOLE(1503)] "%cTRACE", source: file:///usr/lib/code-git/out/vs/workbench/workbench.main.js (1503)
[7716:1208/180842.926476:INFO:CONSOLE(1503)] "%cTRACE", source: file:///usr/lib/code-git/out/vs/workbench/workbench.main.js (1503)
```
but it doesn't seem particularly useful...

I'm gonna try later with the latest version.

**Comment by Steffo99** [comment]
Problem persists with:

Version: 1.31.0
Commit: e444eaa768a1e8bd8315f2cee265d725e96a8162
Date: 2018-12-08T18:31:18.691Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.7-arch1-1-ARCH

**Comment by Steffo99** [comment]
Running `code` as root does not solve the problem, making me think that it's not a file permissions issue.

Neither does deleting the `".config/Code - OSS"` and the `.vscode-oss` folders.

**Comment by Steffo99** [comment]
I've noticed that https://github.com/Microsoft/vscode/issues/64094#issuecomment-444012307 might be the same problem, but he posted in an issue about a similar but different problem.
Maybe @afiestas has more info that I didn't notice?

**Comment by Steffo99** [comment]
As expected, the problem isn't present in the official Visual Studio Code binary, but only in the OSS versions.

It actually might be a bug with the `code` Arch Linux package, but I'm not so sure; nobody has posted a bug report yet...

Maybe I should try compiling manually, instead of using `pacman` or `pkgbuild`...

**Comment by afiestas** [comment]
Indeed I might be encountering the same problem, I will do more testing during the incoming days.

**Comment by Steffo99** [comment]
The same bug has been reported to the Arch package mantainers [here](https://bugs.archlinux.org/task/60946?project=5&string=code).

**Comment by afiestas** [comment]
Can't reproduce anymore building it with this [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=code-git)

Version: 1.31.0
Commit: f90f0a9e138b809081c45a93eb4e881078b0937f
Date: 2018-12-17T06:54:30.895Z
Electron: 3.0.11
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.0-rc7-g2c411746783a

**Comment by Steffo99** [comment]
Can confirm it's now working again with the latest git build.
No PKGBUILD changes were done in this time, so I suppose something was fixed in the latest commits. Thanks!
