### ISSUE TITLE
The language service could not be started

### ISSUE THREAD

**Issue by darkanezi** [Microsoft/vscode#64512]
Issue Type: <b>Bug</b>

After updating the powershell extension to version 1.10.0, the terminal stopped working

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.52GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.13.0
python|ms-|2018.11.0
azure-account|ms-|0.6.2
azurecli|ms-|0.4.2
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.10.0
team|ms-|1.144.1

</details>

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
