### ISSUE TITLE
Understand why explorer got slower

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64514]
There is signed of the explorer getting slower during the last days: https://msit.powerbi.com/groups/2bb9c256-c8ed-47a3-b1be-ebf0c050fb85/reports/2f5bed71-2607-4e0c-8a83-d0f9de023342/ReportSectionb6070ab4ab59572664e6

<img width="387" alt="screenshot 2018-12-06 at 14 06 20" src="https://user-images.githubusercontent.com/1794099/49585972-29e74880-f960-11e8-9fe6-a8d646dbe3cf.png">

**Comment by jrieken** [comment]
adding @bpasero cos @isidorn is busy and you probably know the explorer well... Not sure that promise adoption caused this - file operation have always been properly async...

**Comment by isidorn** [comment]
One of my suspisions might be the changing of startup phases in addition to promise adoption.
@jrieken has the over startup speed changed, or only the explorer got slower? Also can you see the change when you measure locally? If yes we can do some bisection to find the cause.

**Comment by jrieken** [comment]
Blaming this on the promise-adoption is easy, but we all know by now they run on `nextTick` and it would require loads of them to get 50ms extra...

**Comment by bpasero** [comment]
@jrieken I am not worried about the time a `nextTick` takes, but rather the fact that our execution order of things on startup is changing by adopting `Promise` because we have many places where code is now running on `nextTick` that previously was not in places where we wrapped a complete value into a promise under certain conditions.

**Comment by jrieken** [comment]
> but rather the fact that our execution order of things on startup is changing by adopting Promise 

Maybe I understood `nextTick` wrong but that shouldn't happen unless those things also run via `nextTick`, right? Ticks (multiple) are processes at the end of an event loop cycle and only then comes the next event.

**Comment by bpasero** [comment]
@jrieken yeah that might be true (hopefully is). I am running test now on Linux with a commit from 26th of November vs. today to see if there is something.

**Comment by bpasero** [comment]
Bisecting on Linux I see a slowdown from `~50ms` to `~150ms` for the restoring of viewlet through:

```
ticino@ubuntu:~/development/vscode$ git bisect bad
aedd4402fb7eb0022589012f440b059c6b12f12b is the first bad commit
commit aedd4402fb7eb0022589012f440b059c6b12f12b
Author: SteVen Batten <6561887+sbatten@users.noreply.github.com>
Date:   Mon Dec 3 06:39:58 2018 -0800

    Make menubar its own widget and add overflow (#63954)
    
    * working state
    
    * fix keybindings and add compact submenu mode
    
    * fix blur
    
    * fix mnemonics in overflow menu
    
    * fix issues with window resizing
    
    * switch to ellipsis

:040000 040000 806eed75a901e912ad54ac00b090a020afcd32c7 040ec16ec75644ea4ef91b29d29829bf9278af54 M	src
```

**Comment by isidorn** [comment]
Nice find, I will verify on Windows.
On OS X there is no slowdown, which is correlated to the fact that menus are the cause (since we do not use custom menus on OS X)

**Comment by isidorn** [comment]
@bpasero does the overall startup time get 50ms slower too, or it is just reflected in the explorer?

**Comment by jrieken** [comment]
>  too, or is it just reflected in the explorer?

I'd say that's because 99% of startups open the explorer when opening the editor. These are great findings.

**Comment by bpasero** [comment]
@isidorn it looks like the workbench ready time is actually worse when the native menu is enabled for me, so overall I see no total slowdown. Also the editor restore seems to be roughly the same with custom and native title.

**Comment by bpasero** [comment]
@sbatten this seems to be caused by [`updateOverflowAction`](https://github.com/Microsoft/vscode/blob/86571ec/src/vs/base/browser/ui/menu/menubar.ts#L398) being called during startup which seems to access DOM properties that cause a forced layout. If I comment out that method, I see the normal times reported. 

I suggest you check if this method could be called after a delay, e.g. via `scheduleAtNextAnimationFrame`
