### ISSUE TITLE
Adding a lit.html tag is flagged as an error in TS file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#64510]
Tests: https://github.com/Microsoft/vscode/issues/64279

```
{
	"lit-html.tags": [
		"html",
		"template",
		"dirk"
	]
}
```

```typescript
const d = dirk`
<button>
</button>
`
```

Observe: although code complete works as expected `dirk` is marked as an error

**Comment by mjbvz** [comment]
This is correct. That template string requires a function called `dirk`. If you run this file in node, it would crash because no `dirk` function exists
