### ISSUE TITLE
Support copy and paste via keyboard on integrated terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6451]
Integrated terminal master issue: #143

Might need to use custom keybindings, <kbd>ctrl</kbd>+<kbd>c</kbd> terminates a process. Also it's probably not best to hijack <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>c</kbd> from open in new terminal.

**Comment by Tyriar** [comment]
Probably best left after xterm is adopted.

**Comment by Tyriar** [comment]
Upstream issue blocking configurable copy/paste: https://github.com/sourcelair/xterm.js/issues/118

xterm.js did recently add <kbd>ctrl</kbd>+<kbd>insert</kbd> to copy and <kbd>shift</kbd>+<kbd>insert</kbd> to paste in https://github.com/sourcelair/xterm.js/pull/107, so this will be the 'workaround' until https://github.com/sourcelair/xterm.js/issues/118 gets done.

**Comment by andregsilv** [comment]
I'm also facing Issues with `ctrl`+`C` and other simmilar copy-paste shortcuts in the integrated terminal on Windows. I'm not sure what would be the best solution to this issue. Some people would enjoy copying and pasting using the default OS keyboard shortcuts, but it would be difficult to break a current running process (except for OS X). I strongly use this shortcut.

I'd rather prefer to remove the shortcut indicator in the right-button-menu for copy/paste/cut to avoid misunderstandings.

**Comment by Tyriar** [comment]
Basic support is there for v1.3.0 using:

- <kbd>ctrl</kbd>+<kbd>insert</kbd> to copy
- <kbd>shift</kbd>+<kbd>insert</kbd> to paste

This will be improved in the future with the ability to specify your preference in keybindings.json.

**Comment by bldesign** [comment]
Maybe ntegrated terminal can present same feature as native Windows terminal, on Windows.

In the property options there are edition options with the ability to active <kbd>ctrl</kbd> shortcuts. It's just what we are talking about. It kills the process only if there is no selection. Cool no? *VS Code* can do it.

Sorry my preview is in french, but yours certainly looks the same.
![terminalpropertiesoptions](https://cloud.githubusercontent.com/assets/2221676/16598938/75102700-4300-11e6-8063-0c357febefcb.png)

With all options enabled. You can:

1. Copy paste <kbd>ctrl</kbd> + <kbd>c</kbd> / <kbd>v</kbd> even when a process is running (kills only if no selection)
2. Always paste <kbd>ctrl</kbd> + <kbd>v</kbd> (after process ended)
3. Select text with mouse
4. Select text with keyboard <kbd>shift</kbd> + <kbd>←</kbd> / <kbd>→</kbd>

You can copy, paste and select text only with keyboard on Windows. :)

Can you expose these options to user preferences?

**Comment by andregsilv** [comment]
> Killing the process only if there is no selection

A very good idea

**Comment by Tyriar** [comment]
@bldesign @andregsilv nice suggestion, forked to #8818 to be considered after this.

**Comment by Tyriar** [comment]
Proper keybinding support coming in v1.4.0!

Certain key combinations won't work as the terminal will consume them before VS Code has a chance to respond. This is being tracked in #7269

**Comment by Tyriar** [comment]
Reopening as these keybindings should be disabled on Mac since <kbd>cmd</kbd>+<kbd>c</kbd> and <kbd>cmd</kbd>+<kbd>v</kbd> work there.

**Comment by alexsorokoletov** [comment]
unfortunately ctrl+insert/shift+insert is not the ideal way to have shortcuts on windows. Macbooks don't have insert key.

**Comment by Tyriar** [comment]
@alexandrudima <kbd>cmd</kbd>+<kbd>c</kbd> and <kbd>cmd</kbd>+<kbd>v</kbd> should work on Mac.

**Comment by alexsorokoletov** [comment]
@Tyriar hardware is mac, however the OS is Windows 10. Sorry for the confusion

**Comment by Tyriar** [comment]
@alexsorokoletov ah, I guess you have to wait until next release then or use the Insiders build for ctrl+shift+c/v.

**Comment by superDuperCyberTechno** [comment]
So, it has been implemented, although I cannot seem to change the shortcut. I tried switching it to ctrl+c/ctrl+v without luck. All other custom keybindings work fine.

**Comment by Tyriar** [comment]
@superDuperCyberTechno you can change the keybinding, but you can only change it to certain combinations as the key strokes at handled by the terminal before vscode itself. This is the reason F1 and ctrl+p do no work but ctrl+shift+p works fine. The "fix" for this would be to address https://github.com/Microsoft/vscode/issues/7269#issuecomment-229200962

**Comment by superDuperCyberTechno** [comment]
Alright, thank you for the explanation.

**Comment by Tyriar** [comment]
@superDuperCyberTechno I just pushed a fix for #7269 which will landin Insiders tomorrow (or v1.5.0 stable) to allow a set of commands to skip over the shell processing and be handled by VS Code. This means that you can indeed rebind to ctrl+c and ctrl+v if you want, you will not be able to use ctrl+c to cancel the command anymore though and you cannot remap that (outside of maybe remapping in bash if that's possible).

Conditional ctrl+c/v if probably what you really want, this is still open and captured in https://github.com/Microsoft/vscode/issues/8818
