### ISSUE TITLE
List references: removing items feels lagy and shows progress

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#64523]
1. List all references
2. Click on the x button in the viewlet
3. Notice that removing items is very laggy and it even shows a tiny bit of a progress bar

I guess this is because we are refreshing the whole tree.
Optimally we would be able to refresh just one item. Or we could control if we should show progress
The gif did not capture the progress bar but it is visible on my machine and looks like a screen glitch.

![lag](https://user-images.githubusercontent.com/1926584/48125842-f392ac80-e27f-11e8-8269-12de2bf204a7.gif)

**Comment by alexr00** [comment]
The tree implementation has changed since this issue was filed.
