### ISSUE TITLE
Improve keyboard friendliness of history in Reference List

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#64534]
Testing https://github.com/Microsoft/vscode/issues/64227.

1) search for references
2) give editor focus
3) run `References: Clear` from the command palette
4) <kbd>Cmd+0</kbd> to focus references list
=> I have to use tab to get to the correct history entry to re-run. I'd like to use arrow keys to navigate or even <kbd>F4</kbd> as this is what I would use in this view anyways. When navigating the history, the focus should stay in the view.

**Comment by jrieken** [comment]
we have done that, the history is now normal tree/list entries
