### ISSUE TITLE
readHorizontalRanges ends up in optimisation hell

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#64546]
* typing and everything felt sluggish
* ran a profile
* didn't find anything specific but I did see that `readHorizontalRanges` was be deopt'ed too many times

[CPU-20181206T150932.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2653340/CPU-20181206T150932.cpuprofile.txt)

<img width="466" alt="screenshot 2018-12-06 at 15 09 31" src="https://user-images.githubusercontent.com/1794099/49589226-1be9f580-f969-11e8-9277-c72721068827.png">

**Comment by jrieken** [comment]
There are actually a few more editor related function in hell. All number are low, likely not causes the slowness but something you maybe wanna tackle..

<img width="687" alt="screenshot 2018-12-06 at 15 11 46" src="https://user-images.githubusercontent.com/1794099/49589281-43d95900-f969-11e8-8c24-ebed3136f4a0.png">

**Comment by jrieken** [comment]
hm, maybe there is something off with `_actualrender` - that is in hell and takes quite some time...

<img width="518" alt="screenshot 2018-12-06 at 15 12 50" src="https://user-images.githubusercontent.com/1794099/49589347-708d7080-f969-11e8-831d-d266d27772a6.png">

**Comment by jrieken** [comment]
typing in this file 

```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as assert from 'assert';
import { URI } from 'vs/base/common/uri';
import { Range } from 'vs/editor/common/core/range';
import { Position } from 'vs/editor/common/core/position';
import { LanguageIdentifier } from 'vs/editor/common/modes';
import { MockMode, StaticLanguageSelector } from 'vs/editor/test/common/mocks/mockMode';
import { LanguageConfigurationRegistry } from 'vs/editor/common/modes/languageConfigurationRegistry';
import { ModelServiceImpl } from 'vs/editor/common/services/modelServiceImpl';
import { TestConfigurationService } from 'vs/platform/configuration/test/common/testConfigurationService';
import { javascriptOnEnterRules } from 'vs/editor/test/common/modes/supports/javascriptOnEnterRules';
import { ITextResourcePropertiesService } from 'vs/editor/common/services/resourceConfiguration';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { isLinux, isMacintosh } from 'vs/base/common/platform';
import { TokenTreeSelectionRangeProvider } from 'vs/editor/contrib/smartSelect/tokenTree';
import { MarkerService } from 'vs/platform/markers/common/markerService';
import { TextModel } from 'vs/editor/common/model/textModel';


suite('SmartSelect', () => {

	let model = TextModel.createFromString('{[[]()]}');

	test('bracket selection - basics', () => {
		
	})
});

```

**Comment by alexandrudima** [comment]
Unfortunately IR Hydra is now defunkt and cannot be used to pinpoint the reason for deopt, so I don't think there is anything I can do without that tool anymore...

**Comment by alexandrudima** [comment]
I've taken a look at the code and have pushed a change to avoid using a double where otherwise a SMI is used. That might have triggered a deopt, but I really don't know without a tool such as IRHydra2. Therefore, IMHO, the warnings are non-actionable unless v8 builds some tooling to help understand the deopts...
