### ISSUE TITLE
The whole treeview is rerendered when an update event being triggerred

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#64557]
Issue Type: <b>Bug</b>

* Install GH PR or GitLens
* Go to a tree view contributed by the extension, hit refresh button on the title
* The whole tree view is rerendered.

VS Code version: Code - Insiders 1.30.0-insider (048fdbba9505f64f583e9687806582c519fbdb9d, 2018-12-06T06:17:10.993Z)
OS version: Windows_NT x64 10.0.17134

![refresh-treeview](https://user-images.githubusercontent.com/876920/49604318-6c9a2800-f942-11e8-8499-ed212a5f9783.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (10.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
gitlens|eam|9.0.3
tsl-problem-matcher|eam|0.0.4
tslint|eg2|1.0.40
vscode-pull-request-github-insiders|Git|0.338.0
Angular2|joh|7.0.1
vscode-typescript-tslint-plugin|ms-|0.1.1
debugger-for-chrome|msj|4.11.1
toggle|reb|0.0.1
vscodeintellicode|Vis|1.1.0

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This was caused because of https://github.com/Microsoft/vscode/issues/63906. I am hiding the tree container when it is empty so that there is only focusable container for message.

Fix is to hide tree only when there is a message and tree is empty.

**Comment by sandy081** [comment]
Verify that views with and without message are getting refreshed without getting hidden. Use References List and Github PR tree for testing.
