### ISSUE TITLE
vscode is still deleting my files when merging branches. throwing errors in the terminal about file permissions

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#64559]
You people have been warned endlessly that this happens, so here is more anecdotal evidence. yesterday when merging a branch into staging, it deleted the `package.json`. today, it has deleted 6 different files while merging and spit out some error info into the terminal. I am not sure what to make of it. It goes away for a while and then it comes back and happens multiple times in short order.

also, its worth noting, this project is on a non os drive. (Drive E:), and VSCode ocassionally has latency issues and read errors with this drive. Its also resulted in the dev environment of create-react-app crashing on several ocassions. not sure if it is related, but worth noting

![image](https://user-images.githubusercontent.com/4483325/49606734-bfcba500-f959-11e8-9f96-216420abcba2.png)

**Comment by Tyriar** [comment]
Are you on a personal or a corporate machine?

> You people have been warned endlessly that this happens, so here is more anecdotal evidence. 

Can you link some of this?

**Comment by r3wt** [comment]
@Tyriar I am on a personal machine. Using SSD for OS, with a 1tb internal drive for documents.

----
I first reported this issue here -> https://github.com/Microsoft/vscode/issues/61761
this seems similar, as i've seen ENOENT errors like this as an result -> https://github.com/Microsoft/vscode/issues/61790

the problem is you people don't ever actually fix things. you just have your bot that closes out issues. its clear your team is not interested in fixing problems.

**Comment by Tyriar** [comment]
> the problem is you people don't ever actually fix things. you just have your bot that closes out issues, after some time has elapsed. its clear your team is not interested in fixing problems.

The bot aids our small team to get through the enormous amount of issues we get, that's also the reason some of our responses are terse.

---

- Can you repro this in a regular external cmd/conhost window?
- Can you repro when you're using cmd instead of git bash in the integrated terminal?
