### ISSUE TITLE
Git bugs

### ISSUE THREAD

**Issue by dimovich85** [Microsoft/vscode#64553]
Issue Type: <b>Bug</b>

При push в гитхаб через интерфейс приложения спрашивает пароль постоянно и дважды!! Не понимаю, скорее всего ключ -u при push не установлен, потому что в самом гитхабе ветки нормально не стыкуются. Если писать в терминале, то вообще ничего не получается, в поле пароля нет возможности ничего написать.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3700  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.18
vscode-eslint|dba|1.7.0
beautify|Hoo|1.4.7
vscode-language-pack-ru|MS-|1.29.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
twig|wha|1.0.2

</details>

**Comment by jrieken** [comment]
Please file issues in English. Thanks
