### ISSUE TITLE
Should escape be consumed by the integrated terminal?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6455]
Integrated terminal master issue: #143

Open question: Currently pressing <kbd>esc</kbd> will hide the terminal, this can be a problem for some terminal programs, for example `vim`. Perhaps this should be configurable?

**Comment by joaomoreno** [comment]
Thinking about current terminals, I can only close them via a global shortcut, an `X` button or running `exit` in the shell. <kbd>Escape</kbd> should not bubble outside to the workbench.

**Comment by Tyriar** [comment]
Marked as candidate as it's a very simple change that's been reported a bunch of times.

**Comment by Tyriar** [comment]
Cherry picked to release/1.2
