### ISSUE TITLE
Make Rekit Studio available as a plugin

### ISSUE THREAD

**Issue by BjoernRave** [Microsoft/vscode#64554]
I would like to be able to use the way rekit studio is handling react application development with the power of vscode. Do you think it would be possible to setup an API for Rekit studio to use, so it would be able to do all the nice things it does? 

I know there was already a similar request, but it was closed for not obvious reasons, so I thought I create a new one, because rekit seems really perfect for developing react apps as it is build around the idea of components.

[Rekit Website](http://rekit.js.org/)

[Issue in Rekit Repo](https://github.com/supnate/rekit/issues/74)

[Closed Issue](https://github.com/Microsoft/vscode/issues/43530)

**Comment by roblourens** [comment]
> Do you think it would be possible to setup an API for Rekit studio to use, so it would be able to do all the nice things it does?

Maybe, but we need specific issues and suggestions that would help Rekit do whatever it needs to do.

Like the earlier issue said,

> Please file individual issues for any limitations you are running into with the current VS Code API

Then we can work through those issues to add whatever API is needed.
