### ISSUE TITLE
Stack frame highlight is on top of selection highlights

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/vscode#64555]
I can't always see which characters are selected when my selection is on the same line that is currently paused on by the debugger.

Video: https://files.catbox.moe/yxjl6j.avi

- VSCode Version: __1.29.1__
- OS Version: __macOS v10.14.1__

Steps to Reproduce:

1. Start the debugger and pause on any frame of execution
2. Try selecting a random range within the line highlighted by the debugger
3. See that you can't tell which characters are selected, because the yellow highlight takes precedence.

Does this issue occur when all extensions are disabled?: __Yes__

**Comment by aleclarson** [comment]
@weinand Quick question: What program or CLI command do you run for that? :)

**Comment by weinand** [comment]
I'm on macOS and I used the builtin Quicktime to convert your *.avi to *.mov and then Snagit for macOS to convert the *.mov to *.git.
But Snagit supports to directly convert a screen recording to animated gif.

**Comment by isidorn** [comment]
I can not reproduce this with the default theme with latest vscode insiders
Please file this against the theme author.
Also you can customise all these colors by changing 
`selection.background` and `editor.stackFrameHighlightBackground`
under 
`workbench.colorCustomizations`

**Comment by aleclarson** [comment]
@isidorn Um, `selection.background` does not affect the editor. I think you meant `editor.selectionBackground`.

Is it intended for the following colors to cover `editor.selectionBackground`?

- `editor.stackFrameHighlight`
- `editor.findMatchHighlightBackground`
- `editor.wordHighlightBackground`

This seems totally backwards.

**Comment by isidorn** [comment]
No, the selection color should always be seen.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
