### ISSUE TITLE
Updating with apt-get keeps breaking every other time.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#64567]
Issue Type: <b>Bug</b>

On Linux `apt-get` use to work fine to update `code-insiders` until recently when it stop working consistently.

```
sudo apt-get update
sudo apt-get upgrade
```

This is now forcing me to download a dep package and then do a manual install. 

The last time I installed using a deb package, `apt-get` updates started working and then broke on the following update.

VS Code version: Code - Insiders 1.30.0-insider (048fdbba9505f64f583e9687806582c519fbdb9d, 2018-12-06T06:14:36.426Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (5.69GB free)|
|Process Argv|/home/yadav/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.0.0
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.7.0
java-debug|DSn|0.0.2
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.0.18
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
java|red|0.35.0
language-stylus|sys|1.10.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
We didn't publish code-insiders for some time due to an issue with our publisher https://github.com/Microsoft/vscode/issues/64300
