### ISSUE TITLE
auto-load workspace file if it is the only workspace file in the folder root

### ISSUE THREAD

**Issue by cdaringe** [microsoft/vscode#64565]
# problem

i often `cd /path/to/project && code .` to launch vscode.  it's easy to _forget_ to open the workspace, e.g. `code blah.code-workspace`.  further, when contributors jump into your project, it'd be nice to auto onboard them if they are not aware of the workspace functionality.

# discussion

~100% of the time, i want to use the `.code-workspace` file.  i understand that in some cases you may want a native file browsing experience, i'm not sure how to handle that case, or if it should be handled.

i'd also be willing to sacrifice the ease of onboarding newcomers if i could alias code to be something akin to `alias code="code --always-load-local-workspace"` or similar.

thanks for the consideration!

**Comment by Zyrsha** [comment]
This is a common problem. I have this same problem when opening Folders from inside of VSCode itself. Sometimes they have workspaces, and I have to deal with the prompt asking if I want to load the workspace? This is actually a very upsetting prompt.

Yes, I want to, Every Single Time

And I don't want it to be a 2 step process with the window loading, then having to load the window again.

**Comment by Zyrsha** [comment]
This is a common problem. I have this same problem when opening Folders in separate windows from inside of VSCode itself. Sometimes they have workspaces, and I have to deal with the prompt asking if I want to load the workspace? This is actually a very upsetting prompt.

Yes, I want to, Every Single Time

And I don't want it to be a 2 step process with the window loading, then having to load the window again.

**Comment by melMass** [comment]
There is a prompt so the autodetection is there.  
The dialog does not follow the  
> **`don't ask again` => Auto add a new setting to either workspace or user**

that many other VSCode prompts have.
We need that to be an option which is not the case for now (I think).

I like @cdaringe 's proposal but at settings level rather than adding a flag to `code`'s executable. I don't mind the UI flashing ( while auto reloading on workspace detection ). We should then just post a new notification along the lines `the Workspace **XXX** was detected and autoloaded`

**Comment by cdaringe** [comment]
i started getting the prompt.  for me personally, the prompt is sufficient.  adding the setting would still be a nice-to-have, but i'm now content.  will leave open for the other interested parties

**Comment by mugi-luffy** [comment]
definitely interested!  
I'm using the Project-Manager extension to switch between my projects. But each time I have to click on the popup to load my workspace.
+1

**Comment by entozoon** [comment]
+1 for a "Don't ask me again" which enables a setting for this feature

**Comment by KPECTuK** [comment]
+1

**Comment by EthanNYT** [comment]
I switch between projects very, very often.

Every single one (~50) has no fewer that 1 or more than 1 `.workspace` file1. 

Waiting for VS Code to learn there's a workspace, animate in the prompt, and have me click it actually adds up to a lot of time over the day.

If we don't get the auto-load function, at least please stop animating the slide-in of the dialog, just have it appear instantly, and have and option to focus the "yes" button automatically.

That way I can just press `Enter` to load the workspace (which I do, every single time).

**Comment by ironcladlou** [comment]
Other ideas to throw on the pile:

* When auto-loading a workspace (whether this becomes the default, or whether it's driven by settings or flags), raise a short-lived notification indicating that the window is using an explicit workspace file.
* Add "something" to the UI which visually indicates when the window is using explicit workspace file.

**Comment by EthanNYT** [comment]
6 months after this was opened, just curious if the dev team has any interest in loading a workspace file automatically on page load? Or should I just keep my eyes peeled for an extension?

**Comment by cdaringe** [comment]
given that the team now gives a visual prompt reliably _and_ lets you open a project from the CLI, this may be actually better left open for user land to solve. perhaps thru a bash alias, perhaps through a vscode extension.  I'm closing my issue in efforts to help the core team keep the noise down, and work on those sweet sweet juicy features in the roadmap!

**Comment by entozoon** [comment]
Closing the issue - fair enough, noise is noisy. 
But just to clarify, for future ref, the prompt was present when the issue was created - in fact, this feature request is for it to allow auto-opening of the project workspace, and ideally prevent prompts thereafter. 
Still something people very much want, and this issue hasn't been resolved by VSCode or a plugin.
