### ISSUE TITLE
Cannot launch terminal - "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)"

### ISSUE THREAD

**Issue by AnutaK** [Microsoft/vscode#64562]
- VSCode Version: 
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: 
Windows 10 Enterprise

Steps to Reproduce:

When I try to launch the terminal, I get the following message: 
"The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)"

Under Preferences - > Settings - > Features - > Terminal, I see that "C:\WINDOWS\System32\cmd.exe" is customized as the terminal to run on Windows. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://www.github.com/Microsoft/vscode/issues/62953
