### ISSUE TITLE
Notification section is not showing up properly in Insiders

### ISSUE THREAD

**Issue by pingshunhuang** [Microsoft/vscode#64568]
- VSCode Version: 1.30.0 insiders
- OS Version: Mac Mojave

Steps to Reproduce:

1. Click the bell icon
2. Check the notification section

Does this issue occur when all extensions are disabled?: No

![screen shot 2018-12-07 at 10 54 27 am](https://user-images.githubusercontent.com/32624534/49619052-0f1fdd00-fa0f-11e8-96f7-3aad3bdcbf7e.png)

**Comment by bpasero** [comment]
@pingshunhuang does this reproduce all the time?

**Comment by pingshunhuang** [comment]
@bpasero It's actually fine now after a restart. Feel free to close this issue if found irrelevant. Thanks.

**Comment by bpasero** [comment]
Ok, we can reopen when you found reliable steps to reproduce.
