### ISSUE TITLE
Share code lenses across split editors

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#64572]
Issue Type: <b>Bug</b>

**Repo**
1. Set `"javascript.referencesCodeLens.enabled": true`
1. Enable ts server tracing by setting: `"typescript.tsserver.trace": "verbose"`
1. In a js file:

    ```js
    export function foo() { } 
    foo(); foo()
    ```

1. See code lenses.
1. Open `TypeScript` section of the output panel and clear the output
1. Now split the editor

**Bug**
VS Code asks TypeScript for code lenses again on this file, even though we have already computed them You can see this by the new `references` requests in the `TypeScript` output on the split.

Changes in either editor now also results in the same code lenses being requested and resolved twice

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by jrieken** [comment]
Yes - I like that. Related to this is the fact that we refetch/animate code lenses when switching between two tabs

**Comment by jrieken** [comment]
This is actually fixed with the work for https://github.com/microsoft/vscode/issues/19917
