### ISSUE TITLE
Choppy scrolling in scm view with many files

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64574]
Issue Type: <b>Bug</b>

**repo**
1. With a lot of files in the scm view
1. On a tall monitor so that many files are visible at a time
1. Scroll though the scm file list

**Bug**
Scrolling is noticeably choppy. When profiling, it looks like the creation of context keys is taking a lot of time for each scroll update

<img width="701" alt="screen shot 2018-12-06 at 5 27 08 pm" src="https://user-images.githubusercontent.com/12821956/49621979-83f60700-f97c-11e8-9ecd-bdd7d15c0a70.png">

Here's my profile
[Profile-20181206T173038.json.txt](https://github.com/Microsoft/vscode/files/2655563/Profile-20181206T173038.json.txt)

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by joaomoreno** [comment]
Will be fixed by https://github.com/Microsoft/vscode/issues/64503
