### ISSUE TITLE
Why are integrated terminal colors reset when vim starts? 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6457]
Integrated terminal master issue: #143

Steps to Reproduce:

1. Toggle terminal
2. Launch vim (color scheme changes)
3. Exit vim (vim's changed color scheme remains)

**Comment by romgrk** [comment]
I might be wrong, but from what I recall/understood from recent discussions in neovim:

- In some terminal emulators, the colors can be set by the program; however, there can be *at most* `n` colors, where `n` is usually 16 or 256.
- Some vim colorschemes take advantage of this to approximate #RRGGBB colors, by mapping colors to terminal color-codes [0-255].
- Vim is supposed to save the colors from `termcap`/`terminfo` upon entering, and restore them upon leaving.

**Comment by Tyriar** [comment]
This is fixed in latest, likely to do with colors 16-255 not being defined previously.
