### ISSUE TITLE
Reproducible search history

### ISSUE THREAD

**Issue by dotchev** [Microsoft/vscode#64587]
This is similar to #23099 an others but there is an important difference.

I often need to go back to previous search results.
To do that precisely I need to restore the old values in
* search box
* files to include
* files to exclude

Just keeping history of the search box is not enough. In a larger code base I often need to limit the search using files to include/exclude boxes.

It would be great if each search remembers the values of all 3 boxes. Then there should be a way to see the list of searches in chronological order. When selecting an entry in the list all 3 boxes are restored and the search is repeated. To improve performance it would be nice if the search results are remembered too.

**Comment by roblourens** [comment]
I think this would be best handled by https://github.com/Microsoft/vscode/issues/16488
