### ISSUE TITLE
Reveal References viewlet only once

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#64589]
Verifying #64537

- Start workbench
- Start long-running search
-> References viewlet is revealed 👍 
- Switch to other viewlet to continue work while search is running
-> Search ends and References viewlet is revealed while the user has moved on

It should only be revealed when the user starts the search, not at the end when the user does not trigger it.

**Comment by jrieken** [comment]
@sandy081 this seems to be the default behaviour of `reveal` but that is a little unexpected TBH

**Comment by sandy081** [comment]
Agreed. It is kinda related to #62214. Both needs viewlet to be revealed immediately. I am ok to mark this as dup of the other.

**Comment by jrieken** [comment]
I have pushed a workaround
