### ISSUE TITLE
The cursor dissapearing in the terminal

### ISSUE THREAD

**Issue by AshwInDu** [Microsoft/vscode#64585]
Issue Type: <b>Bug</b>

Whenever I am writing a commend in the terminal the cursor is disappearing from the terminal, it's really dissapointing and also studio code fails to compile my angular project. It compiles for the very first time but if any changes is made and is saved there is no report on the terminal. 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
cpptools|ms-|0.20.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
