### ISSUE TITLE
Floating debug toolbar cannot be moved on menu level

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#64582]
v1.29.1
ubuntu 18.04.1 LTS

There is a relatively big room next to the menu which is begging to fill in and the debug bar is hiding the active edit area or the tab header area.

![image](https://user-images.githubusercontent.com/45578746/49630222-80e72f00-f9ed-11e8-895d-a5ab73dd5c0a.png)

It would be nice if I can drag the debug bar onto the menu row, does not need to be attachable, but I don't need to move this little window constantly if I have 15 files open. (so filling up the tab area left to the right)

To be honest, I think the biggest problem is, that the debug menu is in black and I'm hardly able to see, that's why I tend to move upwards. Theming does not help, as if the theming is lighter all the area will be lighter. The icons must have brighter colours at least, shadows something to make it more visible.

I have checked all the Themes available on the market, but the main criticisms regarding the lighter ones, that the editor area is ok, but the menu and tab area is less contrasty, then what I'm used to in NetBeans or eclipse. Switching back and forth from chrome to vs code my eyes need to accommodate, as I haven't found the perfect light theme.

**Comment by isidorn** [comment]
Please use this setting to customize your toolbar background color
"debugToolBar.background"

Put it under  "workbench.colorCustomizations"

As for the toolbar location please use
debug.toolBarLocation

And we will not put it in the menu, so closing as out of scope.
