### ISSUE TITLE
Support multiple integrated terminals

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6458]
Integrated terminal master issue: #143

**Comment by Tyriar** [comment]
From @bpasero in #6708

> I think pretty early on we will get the feature request to support multiple terminals. As soon as you run a program from the terminal, you cannot use it anymore.

> Maybe we just allow to create new terminals with an action from the terminal panel and show all opened terminals from a dropdown similar to output channels?

> We did this in Monaco on Azure:

> ![e747b8e8-2180-11e6-999f-0e6a822cb5c3](https://cloud.githubusercontent.com/assets/2193314/15519907/906b854e-21b8-11e6-8453-9cc0bade1abe.png)

**Comment by Tyriar** [comment]
I created an issue to look at after this for splitting the terminal panel so you can see multiple at once https://github.com/Microsoft/vscode/issues/7504

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/7705, should land in Insiders in 1-2 hours.

![image](https://cloud.githubusercontent.com/assets/2193314/16327639/3ce5e5fa-3986-11e6-8013-b0eff9366eff.png)

**Comment by davidanthoff** [comment]
I see that UI now on Windows. The drop down shows things like "1: xterm". Why "xterm"? I'm using PowerShell, might make more sense if that term shows up (like "bash" in your screen shot).

**Comment by Tyriar** [comment]
@davidanthoff thanks for the quick feedback, I'll see if I can look at this for June https://github.com/Microsoft/vscode/issues/8116
