### ISSUE TITLE
git 左下角中文字符乱码

### ISSUE THREAD

**Issue by kevinwang04** [Microsoft/vscode#64595]
- VSCode Version: 1.29.1
- OS Version: 10.12

Steps to Reproduce:

1. 分支名称包含特定中文，如“内存”、“造成”
![image](https://user-images.githubusercontent.com/9749428/49644164-ab1f0800-fa52-11e8-8fbb-8172eb302aec.png)

2.左下角git分支名出现乱码
![image](https://user-images.githubusercontent.com/9749428/49644169-b2461600-fa52-11e8-9801-c4371a19d53a.png)

3.git功能里面的放弃更改、放弃所有更改按钮消失
![image](https://user-images.githubusercontent.com/9749428/49644189-bd00ab00-fa52-11e8-8639-dbda8312ebc9.png)

4.切换到其他分支正常
![image](https://user-images.githubusercontent.com/9749428/49644252-e3bee180-fa52-11e8-8ab4-e3c229b120e8.png)

![image](https://user-images.githubusercontent.com/9749428/49644248-de619700-fa52-11e8-9559-41346f8c83f1.png)

之前未遇到，怀疑是否是更新版本造成的。

Does this issue occur when all extensions are disabled?: yes

**Comment by jrieken** [comment]
Please file issues in English. Thanks!
