### ISSUE TITLE
Make it easier to find extensions: hide bundles/packs, hide deprecated extensions

### ISSUE THREAD

**Issue by oocx** [Microsoft/vscode#64591]
When I try to find extensions for Angular, I get a huge list of results. Most of them look like extensions that just bundle other extensions ("Angular Extension Pack", "Angular Essentials", "Angular Productivity Pack",  ...).

Then there are many extensions that look like they are just different implementations of the same feature (there are several Angular snippets packs, several extensions that add Angular schematics support and so on). Some seem to be old and not maintained (something that still has Angular 2 in the name is probably not well maintained).

Then there are extensions that tell me that they deprecate other extensions and that I should uninstall the other extension first, for example the newer angular language service extension (can't even find it right now any more to get the exact name).

I'm totally confused and overwhelmed by the sheer number of extensions.

Some ideas that could make this easier:
- let me filter out bundles. There are so many of them that I don't see the actual real extensions any more
- I also don't want to see snippet packs
- I don't want to see old / deprecated extensions for outdated angular versions
- Maybe there could be something like categories for extensions

There are probably other / better solutions, I just wanted to give some examples to make my problem easier to understand.

**Comment by sandy081** [comment]
@oocx Marking this as a dup of https://github.com/Microsoft/vscode/issues/42890 as this is being discussed about improving searching of extensions. Please add your concerns there.
