### ISSUE TITLE
Let VS Code use the whole screen in Zen mode on vertical 16:10 Monitors

### ISSUE THREAD

**Issue by ThomasSchmidtGF** [Microsoft/vscode#64592]
- VS Code Version: 1.2.9.1
- OS: Ubuntu Mate 18.10
I really like Zen mode and use it quite some time, but since i got new Displays on my Machine, Zen mode doesn't look quite as appealing as before. Thats because my new Displays are 16:10 and i use one of them in vertical mode with VS Code, which is not using the whole screen. It would be nice if vs code would use the whole screen.
Eg:
![image](https://user-images.githubusercontent.com/38254361/49640477-fa8f1500-fa0d-11e8-9676-03acb6db264e.png)

**Comment by usernamehw** [comment]
Do you have `"zenMode.centerLayout": false,`?

**Comment by isidorn** [comment]
@usernamehw thanks for jumping in
