### ISSUE TITLE
Cannot delete .asar file while VS Code is open

### ISSUE THREAD

**Issue by elisee** [Microsoft/vscode#646]
Hi!

It looks like VS Code opens `.asar` files to make them browsable in the workspace tree view. That sounds helpful, except it seems like a file handle is kept open at all times, preventing some packaging script of mine from deleting `.asar` files if I keep VS Code open when running it.

Would it be possible to ensure `.asar` files are only opened by VS Code if they are being browsed explicitely in the tree view? or maybe avoid keeping the file handle open on them while idling?

I'm running VS Code 0.10.2 on Windows 7 64-bit.
Thanks for a great editor! ♥

**Comment by bpasero** [comment]
@elisee not much we can do here really because Electron decides to treat asar files very special. See https://github.com/atom/electron/issues/1658

**Comment by elisee** [comment]
Ah. Reading the bug you linked, I wonder if VSCode could maybe require `original-fs` in the workspace tree code instead of `fs` so that `.asar` files aren't treated special? Obviously I have no experience with the actual code so it might not be manageable, but just putting it out there...

**Comment by bpasero** [comment]
Maybe, but it's ugly to force everyone to remember to not use fs module.

**Comment by stanleyxu2005** [comment]
Hi Team, I have the same issue with the latest build of vscode. I open my project with vscode, the `foo.asar` is located in `dist`. I never intend to open this file in vscode at all. But vscode is able to list its contents. That's why the file cannot be deleted. I'd like to know, if vscode has the possibility not to preview asar file content.

**Comment by bpasero** [comment]
We should try to set the `process.noAsar` flag early on. This will disable any support to view *.asar files in the explorer but this was also never intended.

**Comment by bpasero** [comment]
Actually we cannot set `process.noAsar` because that disables loading of any renderer side electron module...

**Comment by phevose** [comment]
@bpasero This is an annoying problem,every time when I run the build script i have to close vscode first,but my present job require electron,so I have to consider other editor?

**Comment by bpasero** [comment]
I will see if there is a way to prevent the locking from happening.

**Comment by bpasero** [comment]
I opened https://github.com/electron/electron/issues/6251 as related upstream issue.

**Comment by bpasero** [comment]
Pushed a change to treat *.asar as normal files and not directories. It is not 100% possible for us to prevent the locking because it seems a simple `fs.stat` or `fs.readdir` on such a file is sufficient to have it locked. But I went through our places of such calls and handle *.asar specially now. Let's see how it goes.

As a consequence you can no longer expand and browse in *.asar files. But that was also **never** the intent of VS Code to do so in the first place because these files are very special to Electron.

**Comment by weinand** [comment]
I can no longer open *.asar file within VS Code (which is correct), but I'm still able to open an *.asar from the command line. It shows up as an empty project folder and trying to create a file there run into errors:

![2016-07-04_12-10-24](https://cloud.githubusercontent.com/assets/1898161/16557522/a09b1fe0-41e0-11e6-9da6-9166867a0c72.png)

**Comment by bpasero** [comment]
@weinand thanks, can you open a separate issue on this? I think the original issue should be verified.

**Comment by weinand** [comment]
@bpasero I'll create a new issue.
BTW, the *.asar opened from the command line cannot be deleted as long as VS Code is open, so I did verify the original issue.

**Comment by bpasero** [comment]
@weinand good point, though I think that is not a very typical scenario and also not what the users are complaining about.

**Comment by a11smiles** [comment]
I'm running 1.5.3 and this issue still remains

**Comment by bpasero** [comment]
@a11smiles what OS are you on? Here is me not being able to reproduce it by opening an Electron app with VS Code on Mac:

<img width="1187" alt="screen shot 2016-09-30 at 07 36 12" src="https://cloud.githubusercontent.com/assets/900690/18981649/a06f2c6a-86e0-11e6-8a60-d6e3b5a41a54.png">

**Comment by bpasero** [comment]
Extracted https://github.com/Microsoft/vscode/issues/13076
