### ISSUE TITLE
automatically place a semicolon after writing a parenthesis instead of inside

### ISSUE THREAD

**Issue by benjilebon** [microsoft/vscode#64609]
When typing an open parenthesis followed by a semicolon to close the line, it actually types "(;)"

Isnt it better in terms of productivity to automatically place the semicolon after the parenthesis like "();" ? it avoids the user to have to press the right key to move the cursor out of the parenthesis

**Comment by mjbvz** [comment]
Placing the cursor inside the parens is correct in general as it is consistent and make entering arguments easy. If you have `javascript.suggest.completeFunctionCalls` enabled, then when completing functions with no arguments, the cursor will go to the end

Reluctant to do much more special for `;` though. As @jrieken said, handling this correctly requires language specific knowledge and could result in unpredictable text editing
