### ISSUE TITLE
Test confirmation

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#64604]

**Comment by chrmarti** [comment]
@usernamehw @cleidigh FYI: I've added an `/unconfirm` command for you to flag issues that you have looked into, but could not reproduce yourself. (Thanks for the suggestion @usernamehw!)

**Comment by usernamehw** [comment]
The main idea of my comment was to get help in reproducing the issue (the one that's already has steps). Something like:

* tagging a random vscode team member to try to repro
* Putting somewhere alongside existing
`help-wanted` - welcomes PR, 
`unconfirmed` - welcomes info if the issue could be reproduced at all and repro steps

Current label and its description is probably going to discourage people to file bugs.

**Comment by chrmarti** [comment]
@usernamehw Makes sense. What about `/confirmationPending` and `confirmation-pending`? That seems to capture what you propose.

**Comment by usernamehw** [comment]
> What about /confirmationPending and confirmation-pending?

👍
