### ISSUE TITLE
Debug console hangs when many lines are printed in Python code

### ISSUE THREAD

**Issue by VishwaRajGit** [Microsoft/vscode#64600]
Issue Type: <b>Bug</b>

When running the following piece of Python code, the debug console hangs after showing certain amount of lines in the debug console.
In the current example, it always tends to freeze around 14000.

`for i in range(20000):
    print(i)`
 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (16.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
insertnumbers|Asu|0.9.1
multiline-find-and-replace|axl|0.0.1
file-properties-viewer|bru|0.2.0
insert-unicode|bru|0.2.1
bracket-pair-colorizer-2|Coe|0.0.25
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
githistory|don|0.4.4
jupyter|don|1.1.4
gitlens|eam|9.0.3
toggle-excluded-files|eam|1.6.0
LogFileHighlighter|emi|2.4.2
json-tools|eri|1.0.2
path-autocomplete|ion|1.13.1
pubspec-assist|jer|0.3.1
nbpreviewer|jit|1.1.0
asciidoctor-vscode|joa|2.1.0
svg|joc|0.1.4
vscode-simple-icons|Lau|1.9.2
vs-color-picker|lih|0.7.0
code-fragments|mar|1.2.0
rainbow-csv|mec|0.8.0
vscode-todo-parser|min|1.9.1
ecdc|mit|0.12.0
python|ms-|2018.11.0
azure-account|ms-|0.6.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
PowerShell|ms-|1.10.0
autodocstring|njp|0.2.3
vscode-code-outline|pat|0.2.1
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
polacode|pnp|0.2.2
vscode-yaml|red|0.1.0
text-marker|ryu|1.9.0
vscode-smoothtype|spi|1.2.0
sort-lines|Tyr|1.7.0
reopenclosedtab|uyi|1.1.0
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Should be fixed in latest vscode insiders, we are using a new console.
Please try with https://code.visualstudio.com/insiders/ and if it is not fixed let us know and we will reopen

**Comment by dubeg** [comment]
Hi @isidorn, I noticed that the debug console would cause plenty of hangs when it was opened (visible) after it passes a certain number of lines as well. 

I installed the insiders version, and while the hangs seem to be much shorter than in v1.30, they're still a few seconds. It constantly took ~3s when switching from Debug Console to, for example, Output.

**Comment by isidorn** [comment]
@dubeg please open a new issue with clear reproducable steps for the hang. Thank you
