### ISSUE TITLE
Debugging method chains

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#64605]
Given this code:

``` ts
a()
  .b()
  .c()
```

When I place an inline breakpoint before the `c` method is called, I want to see the resulting value from the method chain calls so far (`a().b()`).

Could this be added to the debugger? Given an inline breakpoint just prior to a method call, perhaps the debugger could show the method's parent object under the "Variables" section.

**Comment by weinand** [comment]
VS Code does not have a "debugger" but it only provides a common UI for different debugger backends.
That means that we first have to understand if debugger backends can actually provide the necessary information for this feature.

@roblourens is there are a way to get access to this info via CDP?

**Comment by roblourens** [comment]
No, this is no easier in chrome devtools. You can step into a particular call then see the return value. I'm open to suggestions...

**Comment by weinand** [comment]
@OliverJAsh what debugger are you using?

**Comment by OliverJAsh** [comment]
Node and Chrome

**Comment by weinand** [comment]
Since node.js is not supporting this, we cannot do anything here.
