### ISSUE TITLE
My .html files are not being recognized as plain html

### ISSUE THREAD

**Issue by interglobalmedia** [Microsoft/vscode#64617]
- VSCode Version: 1.29.1
- OS Version: OSX 10.13.6

Steps to Reproduce:

1. Create an app with Node.js and then create a file called index.html.
2. Go to the index.html file and see what it is being recognized as. Currently, mine is being detected as a dust file. And there is nothing to suggest that in my settings.json.

Does this issue occur when all extensions are disabled?: Yes/No Yes

But I really don't know what is causing this issue! I have a lot of extensions and languages I use.
Update: I use React, and I had the following for it:

`
"files.associations": {
        "*.js": "javascriptreact",
        "*.html": "html",
    },
`
But the one I had explicitly for JS was not correctly configured. So I did the following:

`
"files.associations": {
        "*.js": "javascript",
        "*.html": "html",
    },
`
And apparently it seems to be working for now.

**Comment by octref** [comment]
This is probably caused by some extensions you are using. You say it's some "dust file", so disable the "dust extension" or open an issue for it.

**Comment by interglobalmedia** [comment]
I think I have solved the issue. So far no problems now. This started happening when I tried to add Python to the mix. I have since removed Python and re-fixed my React issue which was also causing problems. Thanks for responding and for your suggestion!
