### ISSUE TITLE
VSCode gets non-responsive while using and a dialog comes up to close or restart

### ISSUE THREAD

**Issue by Jayasankar-m** [Microsoft/vscode#64610]
Issue Type: <b>Bug</b>

When using folders with average number of files,vscode is seen to be non responsive after sometime.
Also,a dialog comes up after sometime asking to restart or close vscode.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (6.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
tslint|eg2|1.0.40
beautify|Hoo|1.4.7
robotframework|kei|0.2.8
python|ms-|2018.11.0
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
rf-intellisense|Tom|2.2.1

</details>

**Comment by Tyriar** [comment]
Please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to create an actionable performance issue.
