### ISSUE TITLE
Commenting widget wraps text

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#64616]
Issue Type: <b>Bug</b>

See picture.

![image](https://user-images.githubusercontent.com/4674940/49663044-4a67df00-fa02-11e8-8702-c39c58b51125.png)

VS Code version: Code - Insiders 1.30.0-insider (a152a5c7818a13666a5879b4450eb26a4d45fbde, 2018-12-07T10:25:53.709Z)
OS version: Darwin x64 18.0.0

**Comment by rebornix** [comment]
I'm not seeing this issue for long so closing it for now considering we have pushed fixes to the comment editor layout a couple of months ago.
