### ISSUE TITLE
Wrong C# Icon

### ISSUE THREAD

**Issue by shadykdc** [Microsoft/vscode#64612]
In repository "A" I have two VS Code windows open, one is opened in sub-directory B and one in sub-directory C. "B" has the correct C# icon but "C" does not. When I click on the extensions in both windows, B appears to have more extensions so I try to go to C and enable the same ones but when I search for them they say they're already enabled. 1) Why don't all enabled extensions show up in the list of enabled extensions? 2) Why does the C# icon work in one folder but not another?

![image](https://user-images.githubusercontent.com/8787589/49661209-53a27d00-f9fd-11e8-9607-5f80abd14c51.png)
Same two files in the other window with a different subdirectory open (in the changes list):
![image](https://user-images.githubusercontent.com/8787589/49661230-6026d580-f9fd-11e8-8644-21a6e9432910.png)

The enabled list is different in the two subdirectories but in the one on the left when I go to install, say, Blueberry dark theme, it says it's already enabled.
![image](https://user-images.githubusercontent.com/8787589/49661296-8b112980-f9fd-11e8-8f44-0372d5d31f11.png)
![image](https://user-images.githubusercontent.com/8787589/49661318-97958200-f9fd-11e8-9f5a-3604535f8b85.png)

**Comment by sandy081** [comment]
@shadykdc The left one and the right one has 16 enabled extensions. Can you please scroll down in the panel and check if all of them are there?
