### ISSUE TITLE
Allow copying log output in the Debugger "Watch" pane

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#64626]
In the Watch pane in the Debugger, it is not possible to select the text, which is consistent with the rest of the debugger user interface. This is expected, however this means that the only way to copy output is to expand all the way down to the primitive values. Therefore, you can't even copy an entire list/array. It would be useful to have something like "Copy log output" in the context menu that would allow directly copying the result of logging an expression. Ie, in Python, performing this action on this tuple:
![image](https://user-images.githubusercontent.com/2294248/49669625-f2e06800-fa2f-11e8-9d6f-0a7746432ef9.png)
Would add `(628, 47)` to the clipboard, which is the result of calling `print((628,47))`.

**Comment by iansan5653** [comment]
This is in response to @roblourens [comment ](https://github.com/Microsoft/vscode/issues/63302#issuecomment-444703060) on #63302 .

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/27950
