### ISSUE TITLE
Slow Debug on Mac

### ISSUE THREAD

**Issue by dotnetron** [Microsoft/vscode#64625]
Issue Type: <b>Performance Issue</b>

I recently upgraded my asp.net core project to .net core 2.2 and ever since when I click F5 to debug it takes a long time to launch. Like 30 seconds+.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	    98	   605	code main
    5	    49	   610	   gpu-process
    9	   238	   613	   window (AppSettings.cs — XXXXXX)
    0	    82	   619	     extensionHost
    0	    33	   636	       /Users/xxxxx/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/rzls -lsp --logLevel None
    0	   385	   641	       mono --assembly-loader=strict /Users/param/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/OmniSharp.exe -s /Users/xxxxx/OneDrive/AzureDevOps/XXXXXX/XXXXXXsln --hostPID 619 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin /Users/xxxxxx/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    33	   623	     watcherService
    0	    25	   631	     searchService
    0	    33	  1026	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork ms-vscode.coreclr {"common.vscodemachineid":"f1d0f9c122edb100188776a86a453cf6ea336e98b7ff20c61ae012ab7780ae92","common.vscodesessionid":"f06889e6-7cda-45d2-8695-2d8d62a13fc71544210017114"} AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    57	  1027	     /Users/xxxxxxx/.vscode/extensions/ms-vscode.csharp-1.17.1/.debugger/vsdbg-ui
    0	   238	  1028	       /usr/local/share/dotnet/dotnet /Users/xxxxxx/OneDrive/AzureDevOps/XXXXXXX/src/XXXXXXXX.WebApp/bin/Debug/netcoreapp2.2/XXXXXXX.WebApp.dll
    0	    66	   617	   shared-process
   52	    82	  1074	   window (Issue Reporter)
    0	     0	  1075	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AppSettings.cs — XXXXXXX)
|    Folder (XXXXXXX): 719 files
|      File types: cs(218) js(144) cshtml(86) json(43) png(37) cache(33)
|                  dll(25) md(18) pdb(16) xml(11)
|      Conf files: csproj(3) package.json(2) sln(1) launch.json(1)
|                  tasks.json(1) grunt.js(1) webpack.config.js(1)
|      Launch Configs: coreclr(2);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bower|don|0.0.3
xml|Dot|2.3.2
vscode-azurefunctions|ms-|0.13.0
mssql|ms-|1.4.0
azure-account|ms-|0.6.2
azurecli|ms-|0.4.2
csharp|ms-|1.17.1
typescript-javascript-grammar|ms-|0.0.47
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
cordova-tools|vsm|1.6.0

</details>

**Comment by weinand** [comment]
Please file issue against C# extension
