### ISSUE TITLE
Less intrusive problems' statusbar item

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#64636]
This is what my problems' statusbar item looks like most of the times:

<img width="95" alt="screen shot 2018-12-07 at 22 44 39" src="https://user-images.githubusercontent.com/1812093/49674268-b33a7000-fa71-11e8-838c-bfd4f20efd71.png">

I think the counter and icon about warnings shouldn't be rendered if there aren't any warnings at all. Same with errors. As a consequence if the problems pane is empty there shouldn't be a statusbar item wasting space in my statusbar just so that when I click it I can stare at an empty pane.

Also by showing the statusbar item only when there are actually some warnings/errors it'll be easier not to miss them.

**Comment by dbaeumer** [comment]
I actually disagree with it since it makes a less stable UI. 

I will keep it open to see if other see it the same way.

**Comment by fabiospampinato** [comment]
Good point, but maybe it wouldn't be that much of a distraction after all 🤔

Maybe there could be a setting for enabling this behavior?
