### ISSUE TITLE
ANSI color codes in terminal not working properly

### ISSUE THREAD

**Issue by unic0rn** [Microsoft/vscode#64638]
Issue Type: <b>Bug</b>

some of the escape codes are not working properly.

escape sequence used:
`\[\e[0m\]\[\e[97m\]\[\e[40m\] 15/0 \[\e[96m\]\[\e[41m\] 14/1 \[\e[95m\]\[\e[42m\] 13/2 \[\e[94m\]\[\e[43m\] 12/3 \[\e[93m\]\[\e[44m\] 11/4 \[\e[92m\]\[\e[45m\] 10/5 \[\e[91m\]\[\e[46m\] 9/6 \[\e[90m\]\[\e[47m\] 8/7 \[\e[37m\]\[\e[100m\] 7/8 \[\e[36m\]\[\e[101m\] 6/9 \[\e[35m\]\[\e[102m\] 5/10 \[\e[34m\]\[\e[103m\] 4/11 \[\e[33m\]\[\e[104m\] 3/12 \[\e[32m\]\[\e[105m\] 2/13 \[\e[31m\]\[\e[106m\] 1/14 \[\e[30m\]\[\e[107m\] 0/15 \[\e[0m\] normal \[\e[7m\] inversed \[\e[0m\]`

palette used:
![image](https://user-images.githubusercontent.com/2493246/49674770-65266c00-fa73-11e8-8094-6343eb99f3b4.png)

expected output (from mintty):
![image](https://user-images.githubusercontent.com/2493246/49674801-796a6900-fa73-11e8-96f9-1f1cf8c0173a.png)

actual output:
![image](https://user-images.githubusercontent.com/2493246/49674811-80917700-fa73-11e8-9223-d1ee8e573786.png)

amongst more obvious problems, it seems to assume that certain colors equal to terminal background/foreground - which is entirely wrong. dark theme output:
![image](https://user-images.githubusercontent.com/2493246/49675305-63f63e80-fa75-11e8-83d6-aa12592b95d5.png)

there's a reason default background and foreground colors are separate from the ANSI palette.

terminal is running cygwin's bash, works perfectly fine otherwise.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G   (4 x 3094)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.96GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
linter-gfortran|krv|2.0.1
cpptools|ms-|0.20.1
tcl|sle|0.2.0
vim|vsc|0.16.13

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
