### ISSUE TITLE
Doubled menu items under Ubuntu Unity

### ISSUE THREAD

**Issue by 0matgal0** [Microsoft/vscode#64635]
VSCODE: 1.29.1

Sometimes menu items get doubled, like in the screenshots:
![1](https://user-images.githubusercontent.com/18264503/49674205-68b8f380-fa71-11e8-8335-57c3039f14ef.png)
![2](https://user-images.githubusercontent.com/18264503/49674210-6b1b4d80-fa71-11e8-9eaa-12ac1891e840.png)

It happens (mostly?) by using switchable menu items, like Show/hide minimap - a few switches is enough to trigger this for me.

**Comment by sbatten** [comment]
this has been fixed

**Comment by sbatten** [comment]
l

**Comment by sbatten** [comment]
@0matgal0 would you be able to verify that this issue reproduces with the latest VS Code insiders? https://code.visualstudio.com/insiders/
