### ISSUE TITLE
HIgh CPU usage

### ISSUE THREAD

**Issue by chris-ball** [Microsoft/vscode#64632]
**Performance Issue**

This began today while editing an SVG. VSCode was open when I dragged the SVG to the taskbar icon and into the editor. SVG is only approx 3000 characters in length.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	    84	 18128	code main
    2	    70	  8752	   window (Issue Reporter)
    0	    79	 14888	   shared-process
    2	   419	 17228	   gpu-process
    0	   196	 18004	   window (machine-card.php - redfern - Visual Studio Code)
    0	    11	  4208	     watcherService 
    0	     9	  2876	       console-window-host (Windows internal process)
    0	    36	 10112	     searchService
   24	    66	 14360	     extensionHost
    0	    34	  3032	       electron_node server.js 
    0	    35	 14692	       "C:\Users\chrsj\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\chrsj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=14360
    0	     6	 15864	     winpty-process
    0	     9	 11972	       console-window-host (Windows internal process)
    0	    68	 18828	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	 16796	     electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (machine-card.php - redfern - Visual Studio Code)
|    Folder (redfern): 1503 files
|      File types: php(1022) phpt(265) md(142) scss(34) js(14) json(6) css(3)
|                  txt(3) yml(3) png(2)
|      Conf files: package.json(1) webpack.config.js(1);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.7.0
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-scss|mrm|0.6.2
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.14.3
vscode-status-bar-format-toggle|tom|1.4.0
JavaScriptSnippets|xab|1.7.1

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
