### ISSUE TITLE
Search using './path' include does not exclude properly 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64630]
Issue Type: <b>Bug</b>

**Repo**
1. In the VS Code code base
1. Search for `plugins`
1. Using the include path: `./extensions/typescript-language-features`

**Bug**
Excluded `*.js` files are returned in search results.

<img width="512" alt="screen shot 2018-12-07 at 12 43 31 pm" src="https://user-images.githubusercontent.com/12821956/49671853-17cbdf80-fa1e-11e8-83f0-e7556571c52f.png">

Using the include `extensions/typescript-language-features`, the exclusions are applied as expected

<img width="551" alt="screen shot 2018-12-07 at 12 43 35 pm" src="https://user-images.githubusercontent.com/12821956/49671856-1ac6d000-fa1e-11e8-850b-6571d99949ff.png">

VS Code version: Code - Insiders 1.30.0-insider (a152a5c7818a13666a5879b4450eb26a4d45fbde, 2018-12-07T10:25:53.709Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_9922934|
|Screen Reader|no|
|VM|18%|

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/63303
