### ISSUE TITLE
Look into type errors introduced in proxyResolve by strictBindCallApply

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64641]
#64633 enable strict types for `apply` expressions. This caused a compile error in `proxyResolver` for two `apply` errors

To work around this compile error, I have added two casts: `arguments as unknown as any[]`. Please look into removing these cast if possible as the error suggests the types may be incorrect

**Comment by chrmarti** [comment]
`apply` is typed as taking an array as its second parameter to which `arguments` is not assignable. It does work and looks like an issue with the types. There is a related discussion: https://github.com/Microsoft/TypeScript/issues/29055
