### ISSUE TITLE
Replace "Run Code" button with "Scroll Tab" button

### ISSUE THREAD

**Issue by remoharsono** [Microsoft/vscode#64643]
I have read issue [40770](https://github.com/Microsoft/vscode/issues/40770) and [39059](https://github.com/Microsoft/vscode/issues/39059) - none of them discuss "Run Code button replacement"

Could you replace "Run Code" button with "Scroll Tab" button? because I think "Scroll Tab" button is way more important than "Run Code" button, put "Run Code" on Debug menu or other menus. Thank you, I appreciate your great work.

**Comment by roblourens** [comment]
I don't know what "Run Code" button you're talking about, that might be coming from an extension you've installed. But https://github.com/Microsoft/vscode/issues/39059 was already closed as out of scope.
