### ISSUE TITLE
Language breadcrumbs never show up for the file that's persisted open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64649]
- Open `something.ts`
- Reload the window
- `something.ts` is persisted open
- See that the breadcrumbs for methods, classes, etc don't show up, we only get breadcrumbs for files and folders
- Close `something.ts`, reopen
- Now the language breadcrumbs appear.

**Comment by jrieken** [comment]
Works for my dummy language, must be TypeScript having a problem to recompute this...
