### ISSUE TITLE
Selection color is the same as inserted text in the diff mode

### ISSUE THREAD

**Issue by GTValentine** [Microsoft/vscode#64640]
- VSCode Version: 1.29.1
- OS Version: Windows 10

Steps to Reproduce:

I use the dark mode. I changed the inserted text background in the diff mode:
```
    "workbench.colorCustomizations": {
        "diffEditor.insertedTextBackground": "#011f4b",
    }
```

And then whenever I try to select the text in the diff mode (e.g. when I am reviewing a Github PR where a bunch of code was added) in the code which was inserted, the selection has the same color as my custom background, so I can't see that it's being selected.

`editor.selectionBackground` is ignored for the inserted text in the diff mode, and there's no `diffEditor.selectionBackground`

**Comment by alexandrudima** [comment]
@GTValentine Please define a transparent color for `diffEditor.insertedTextBackground`. That would allow to see the selection under the inserted text.
