### ISSUE TITLE
Allow directory-changing relative paths renames in explorer

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/vscode#64645]
This is particularly inconvenient when you want to move a file to a parent or sibling directory:

> `The name ../MyFile.ts is not valid as a file or folder name. Please choose a different name.

![image](https://user-images.githubusercontent.com/3335181/49678686-ead9f580-fa3a-11e8-8d7d-d7b20cfceea4.png)

Can we move files in the explorer by specifying parent directories? Child directories are already allowed.

**Comment by isidorn** [comment]
This is a fair feature request
Code pointer https://github.com/Microsoft/vscode/blob/cd0ea96e50c5978f299a0c5099e015bf725d2a1a/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L136
