### ISSUE TITLE
[regression] Find all references doesn't scroll to reveal the selected list item

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64654]
- Use find all refs in peek view on some reference
- Navigate focus in the list with up/down arrow keys
- The original reference that triggered this is selected in the list. When I navigate to that item, the editor peek view doesn't scroll to reveal that item.

![dec-07-2018 19-47-25](https://user-images.githubusercontent.com/323878/49681571-f3412900-fa58-11e8-81ff-bcd6d67568d5.gif)

Consider for November?

**Comment by jrieken** [comment]
> When I navigate to that item, the editor peek view doesn't scroll to reveal that item.

I don't understand. What is 'that'? The original selected item?

**Comment by roblourens** [comment]
Correct, whichever item is selected.

**Comment by roblourens** [comment]
I expect that I can reveal the selected item. Actual behavior, it's impossible to reveal it.

Here's another example where the problem is more clear. Once I've revealed the item in settingsTree.ts, it's impossible to get back to the item in treeImpl.ts.

![dec-10-2018 11-34-36](https://user-images.githubusercontent.com/323878/49756792-a8e5c500-fc6f-11e8-9370-9e35cd4350f7.gif)

**Comment by jrieken** [comment]
Thanks, finally understood. Yeah, something we should tackle for Nov.

**Comment by jrieken** [comment]
There is actually another issue here too: https://github.com/Microsoft/vscode/issues/64747
