### ISSUE TITLE
Slow refresh of git viewlet

### ISSUE THREAD

**Issue by staffann** [Microsoft/vscode#64658]
The git viewlet is very slow to update once changes have been done. I have to press the refresh button to avoid waiting for a few minutes. This didn't use to be the case a number of months ago. This makes the impression of VSCode much worse than it used to be.

Even when I press refresh, when I then click the file, the diff can be to an older version than the latest. I'm not sure if this is related or a separate issue.

- VSCode Version: 1.29.1
- OS Version: Linux, Ubuntu 16.04 

Steps to Reproduce:

1. Open relatively large folder where there is a connection to a git repo
2. open a file in vscode and make a file change
3. What for the file change to show up in the git viewlet. It takes a few minutes

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions`?

**Comment by staffann** [comment]
Thanks for the reply.

Yes, it reproduces with --disable-extensions

time git status -zu:
real    0m0.015s
user    0m0.004s
sys     0m0.004s

code --verbose does show if I add a new file from a terminal outside of VSCode.

**Comment by joaomoreno** [comment]
Is the workspace located in a network share, or in any other special location that you can think about?

**Comment by staffann** [comment]
Ubuntu is run in VirtualBox, but the drive is local to that virtual machine. No network drive, not shared with the host OS.

**Comment by joaomoreno** [comment]
Any chance you can send me that VM? Or reproduce in a similar VM and send me a copy of it?

**Comment by staffann** [comment]
I'm afraid that is not possible. It contains proprietary information that is not easily possible to separate.
Any other ideas of things I can try in order to gather more information?
I'll try monitoring the git commands in the output window while adding/removing a file outside vscode, to see if anything happens at all. What is supposed to happen?

**Comment by staffann** [comment]
As expected, the git output showed nothing at all while adding and removing a file from outside vscode.
The complete git output, all of which was present already before I started adding and deleting, looks like:
```
Looking for git in: git
Using git 2.7.4 from git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /home/sni1lud/projects/jenkins_2018-12-11_151710
> git fetch
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git symbolic-ref --short HEAD
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse feature/1511171ESC-2455-robotsanta-unit-test-marks
> git rev-parse --show-toplevel
> git rev-parse --symbolic-full-name feature/1511171ESC-2455-robotsanta-unit-test-marks@{u}
> git rev-parse --show-toplevel
> git rev-list --left-right feature/1511171ESC-2455-robotsanta-unit-test-marks...refs/remotes/origin/feature/1511171ESC-2455-robotsanta-unit-test-marks
> git rev-parse --show-toplevel
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse feature/1511171ESC-2455-robotsanta-unit-test-marks
> git rev-parse --symbolic-full-name feature/1511171ESC-2455-robotsanta-unit-test-marks@{u}
> git rev-list --left-right feature/1511171ESC-2455-robotsanta-unit-test-marks...refs/remotes/origin/feature/1511171ESC-2455-robotsanta-unit-test-marks
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git rev-parse --show-toplevel
```

**Comment by joaomoreno** [comment]
Could you record a screen recording while keeping the git output open and making file changes?

**Comment by staffann** [comment]
I hae tried to upload a video, but failed to attach it to my post. I just get a "Something went really wrong..." message from github.

**Comment by joaomoreno** [comment]
Can you reproduce on other repositories?

**Comment by staffann** [comment]
We have one main repo and I can reproduce on any clone of that repo. I also have a repo where it is not reproducible. The differences I can think of is that the latter repo is smaller and has no commit hook (the others have a hook that adds the branch name to the commit comment). Both are cloned from a bitbucket server.
I can check one or two other repos as well.

**Comment by joaomoreno** [comment]
Are they located in different parts of the file system? Are the repos in a remote file system? What file system format is it?

Do you have perhaps another similar machine you can try this on?

**Comment by staffann** [comment]
They are all located under my home folder, which is local , in the root file system and uses ext4.
My colleague has the same issue. His host computer is Win10 instead Win10, but the guest Linux installations are very similar.

How is this supposed to work? I assume that a file change in the folder opened in VSCode should trigger the git extension to query git for the status? At this point I do not understand where the problem might be located, since VSCode obviously recognizes file created/update/removals (updated in the explorer viewlet) and yet no git command is issued.

**Comment by joaomoreno** [comment]
I also have VirtualBox on my machine, maybe we can figure out a way to repro this? Any chance you can send me a copy of your VM?

**Comment by staffann** [comment]
The VM contains private IP that I am not able to share even in its base installation, so unfortunately I cannot send a copy of the VM.
I will see if I can install a new VM without this, repeat the problem and send you the VM but that will take a bit of time.

**Comment by staffann** [comment]
Maybe related to #42821 ?

I have not yet been able to reproduce with a VM that I can send.

**Comment by staffann** [comment]
I was not able to reproduce using standard ubuntu and open repositories. In addition, the problem has been resolved in the last month or so. I will close the issue.
