### ISSUE TITLE
Context - descriptions not written in clear language (Usability)

### ISSUE THREAD

**Issue by VErwin** [Microsoft/vscode#64656]
RE: JavaScript context description for >  addEventListener("load", "click"):

The copy below is difficult to read.  Please make it accessible to a broader audience of readers (ESL, new technology learners... ect).

It would help if the copy was broken-up into paragraphs and bullet points.    The copy, as written, is currently difficult to scan and therefore less than optimally helpful for all audiences.
_____________________________________

**Copied Verbatim:**  
-------
addEventListener(type: "load", listener: (this: HTMLElement, ev: Event) => any, options?: boolean | AddEventListenerOptions): void

Appends an event listener for events whose type attribute value is type. The callback argument sets the callback that will be invoked when the event is dispatched. The options argument sets listener-specific options. For compatibility this can be a boolean, in which case the method behaves exactly as if the value was specified as options's capture. When set to true, options's capture prevents callback from being invoked when the event's eventPhase attribute value is BUBBLING_PHASE. When false (or not present), callback will not be invoked when event's eventPhase attribute value is CAPTURING_PHASE. Either way, callback will be invoked if event's eventPhase attribute value is AT_TARGET. When set to true, options's passive indicates that the callback will not cancel the event by invoking preventDefault(). This is used to enable performance optimizations described in §2.8 Observing event listeners. When set to true, options's once indicates that the callback will only be invoked once after which the event listener will be removed. The event listener is appended to target's event listener list and is not appended if it has the same type, callback, and capture. Appends an event listener for events whose type attribute value is type. The callback argument sets the callback that will be invoked when the event is dispatched. The options argument sets listener-specific options. For compatibility this can be a boolean, in which case the method behaves exactly as if the value was specified as options's capture. When set to true, options's capture prevents callback from being invoked when the event's eventPhase attribute value is BUBBLING_PHASE. When false (or not present), callback will not be invoked when event's eventPhase attribute value is CAPTURING_PHASE. Either way, callback will be invoked if event's eventPhase attribute value is AT_TARGET. When set to true, options's passive indicates that the callback will not cancel the event by invoking preventDefault(). This is used to enable performance optimizations described in §2.8 Observing event listeners. When set to true, options's once indicates that the callback will only be invoked once after which the event listener will be removed. The event listener is appended to target's event listener list and is not appended if it has the same type, callback, and capture.

**Comment by cristicatalan** [comment]
The same description is appears in Visual Studio 2017. I think it should be fixed there too.

**Comment by jrieken** [comment]
This file against TypeScript, or better the W3C committee from which this doc is taken.
