### ISSUE TITLE
VSCode not prompting unsaved file has changed when starting

### ISSUE THREAD

**Issue by zhanghongce** [Microsoft/vscode#64653]
Issue Type: <b>Feature Request</b>

1. Open an existing file, add modification to it.
2. Exit (w.o. save)
3. Make changes outside VSCode
4. Open VSCode, it will keep the modification done in Step 1, without prompting you the file has changed.
5. If you save in VSCode, all the modifition in Step 3 will be lost, without any notice to the user.

I think, this should at least prompt the user that there are changes outside, and let the user notice, without silently overwriting existing file!

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/15749
