### ISSUE TITLE
Searching for Jest in the Settings gives irrelevant results

### ISSUE THREAD

**Issue by dandv** [Microsoft/vscode#64651]
Issue Type: <b>Bug</b>

1. Go to File -> Preferences -> Settings
2. Type "jest" in the `Search settings` box

I see these unrelated settings:

![image](https://user-images.githubusercontent.com/33569/49680732-ca1a9b80-fa4c-11e8-9c05-3d0a98b01955.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.17.0-3rodete2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 1469)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.39GB (0.61GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.29
vscode-jest|Ort|2.9.2
partial-diff|ryu|1.4.0

</details>

**Comment by dandv** [comment]
In this case, I would much prefer "No results" to the irrelevant/misleading results I'm seeing, because I wouldn't have to manually go though them hoping to find the setting I'm looking for.

I had just installed the Jest plugin so was looking for any settings exposed via this UI before editing the JSON file.

**Comment by roblourens** [comment]
I understand - we have some plans in the works to improve results in general
