### ISSUE TITLE
Joining with multiple cursors on contiguous lines doesn't work as expected

### ISSUE THREAD

**Issue by eykamp** [microsoft/vscode#64655]
Issue Type: <b>Bug</b>

Select several rows of text, convert selection into multiple lines (ctrl+shift-L on my machine).

Join the lines (ctrl+J on my machine).

I expect the lines to be collapsed into a single line, with the mutltipe cursors positioned throughout the lline at the end of what was formerly the end of each line.

What happens in VS Code is you end up with half the lines joining, and some bits becoming selected and some not.  I can see no rhyme or reason to the selection.  If you press ctrl+j again to try to further join the lines, you get an error message.

This works as expected in Sublime Text; try it there if you have that handy.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.83GB (0.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.0.3
Bookmarks|ale|10.0.0
quote-flipper|all|0.0.1
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.3.2
vscode-open-in-github|fab|1.1.3
code-runner|for|0.9.5
rainbow-csv|mec|0.8.0
python|ms-|2018.11.0
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.1013
code-settings-sync|Sha|3.2.2
whiteviz|spy|0.6.0
vscode-arduino|vsc|0.2.23
debug|web|0.22.0
better-align|wwm|1.1.6
cursor-align|yo1|1.0.4

</details>

**Comment by dufferzafar** [comment]
I'm facing this as well, and it is pretty annoying that half of the lines get joined with some bits selected and as you said, trying to press Ctrl + J again results in error: `Overlapping ranges are not allowed.`

The expected behaviour here is just to join all the lines into one (atleast that is what Sublime Text does.)

**Comment by dufferzafar** [comment]
I've tested the join lines implementation in [Zarel/vscode-sublime-commands](https://github.com/Zarel/vscode-sublime-commands) and that seem to work like Sublime.

```json
    {
        "key": "ctrl+j",
        "command": "extension.joinLines",
        "when": "editorFocus"
    }
```

**Comment by irrationalRock** [comment]
Hi, I don’t know if this is the right issue to discuss this but I notice that multicursor works but it only merges in two lines at a time.

![JoinLines-TheIssue](https://user-images.githubusercontent.com/16523071/55293480-ffb10f00-53c4-11e9-8b2c-a0ce7dd44fca.gif)

@alexandrudima  Is Join Lines suppose to join two lines at a time?

I would like to work on having Join Lines merge in more than two lines at a time if possible.

**Comment by alexandrudima** [comment]
Join Lines is implemented here -- https://github.com/Microsoft/vscode/blame/a721a6c23607fd62b441189b23e73e04a8e65b3e/src/vs/editor/contrib/linesOperations/linesOperations.ts#L659 and @rebornix can give advice if necessary.
