### ISSUE TITLE
crashed other running instance when opening a new instance

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#64664]
Issue Type: <b>Bug</b>

I had 2 code-insiders running, when I open a new instance, both running instances just disappeared (crashed) without any warning. Later I was presented with the following error dialog.

![crash](https://user-images.githubusercontent.com/439226/49686443-ad20af80-fac2-11e8-9071-204f81e43679.png)

Here is the process view:

![vscode-process-view](https://user-images.githubusercontent.com/439226/49686444-b742ae00-fac2-11e8-98fa-7261ce505885.png)

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:25:15.966Z)
OS version: Linux x64 4.15.0-42-generic

VS Code has gotten unstable lately.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (4.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.0.0
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.0
java-debug|DSn|0.0.2
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.0.19
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
java|red|0.35.0
language-stylus|sys|1.10.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.15.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you run each instance with `code --verbose` and send us the log as they come crashing down?
