### ISSUE TITLE
Extensions search bar is emptied when reloading window

### ISSUE THREAD

**Issue by dfoverdx** [microsoft/vscode#64669]
Issue Type: <b>Bug</b>

1.  Open Extensions in Side Bar
2.  Type something in search bar (e.g. `@installed javascript`)
3.  Reload window (<kbd>F1</kbd>+`reload window`+<kbd>Enter</kbd>)
4.  Extensions search bar is now empty.

It would be helpful if the search bar in the Extensions Side Bar maintained its value when reloading the window.  Frequently when I don't know which extension is causing adverse behavior, I make a guess at which extensions it might be (e.g. `@installed css`), disable one, click Reload, check whether it worked or not, and repeat.  I find it frustrating that I have to type `@installed css` each time.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by klymenkoo** [comment]
@sandy081 do you work on this issue? If you don't, I'd like to work on it.

**Comment by sandy081** [comment]
@klymenkoo Yes you are.

**Comment by sandy081** [comment]
This is supported now.
