### ISSUE TITLE
OSX prompt to overwrite when changing letter case in file names

### ISSUE THREAD

**Issue by lqueryvg** [Microsoft/vscode#64662]
### Feature request:
**When**: the user changes the case of a file or directory name in the VS Code EXPLORER on OSX
**Result**: prompt the user, warning that they are actually over-writing the same file

### Rationale:
The OSX filesystem is internally case in-sensitive. When you change the case of a filename on the command line, it gives you a reminder of this fact:

```
mv DIR1 dir1
overwrite dir1? (y/n [n]) y
```

However the VS Code EXPLORER hides this warning. This re-enforces the incorrect belief that the user is working on a case-sensitive filesystem, when in fact they aren't.

This can lead to various problems, for example with deployments of the code onto case sensitive platforms, or with git (note that trying to work around the git issues with `ignorecase` leads to further problems and inconsistencies; see https://stackoverflow.com/questions/52369109/git-core-ignorecase-false-in-mac-os-x/52369235#52369235).

I believe that the correct behaviour is to remind the user that they are working on a case insensitive filesystem, rather than hide that fact.

**Comment by isidorn** [comment]
Let me get the steps clear first:
1. Have a file named "file.txt"
2. Rename the file to "File.txt"
3. Expect a warning prompt, however nothing happens

Please confirm if those are trully the steps you are trying to explaing here
Mac finder does not do this. Windows explorer does not do this. Nor does any explorer I know show a warning. Thus we should also not warn.
Users are aware of what file system they are working on, we can not remind that of that fact always

**Comment by lqueryvg** [comment]
When you say it like that, it seems like a silly request :-(

I was hoping for an option to enable the same behaviour as on the command line, which is as you describe.

**Comment by isidorn** [comment]
Unfortunetly this is out of our scope for now.
Thank you for understanding.
