### ISSUE TITLE
Centered mode should keep position when opening sidebar

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#64666]
When opening the sidebar the centered view (editor) is no longer centered in the _window_ so I need to shift my view. I would prefer it to stay where it was. Of course, if the sidebar is too wide then the editor would have to shift to the right to accomodate but not more than necessary. 

I drew a picture to explain :D

![image](https://user-images.githubusercontent.com/1578924/49687018-4a003e80-fafd-11e8-8544-ccedd6d46108.png)

Maybe the current should continue to be the default behavior so I'm proposing that this is added as a setting to VS Code.

**Comment by isidorn** [comment]
Thanks for the artistic picture
Dup of https://github.com/Microsoft/vscode/issues/60900
