### ISSUE TITLE
"workbench.action.terminal.toggleTerminal": "cmd+t" is unknown configuration setting

### ISSUE THREAD

**Issue by IljaDaderko** [Microsoft/vscode#64660]
- VSCode Version: Latest Insiders
- OS Version: macOS

Steps to Reproduce:

1. add `"workbench.action.terminal.toggleTerminal": "cmd+t"` to your settings.json

It will be highlighted with `Unknown configuration setting` message

**Comment by usernamehw** [comment]
Why are putting keybindings in setting tho?

**Comment by IljaDaderko** [comment]
@usernamehw I prefer to just paste settings.json whenever I set up new editor, so I don't have to change it manually every time.

**Comment by Tyriar** [comment]
You setup keybindings.in your keybindings.json, not settings.json, see https://code.visualstudio.com/docs/getstarted/keybindings
