### ISSUE TITLE
Unable to open 'workbench.action.keybindingsReference': resource is not available.

### ISSUE THREAD

**Issue by triklsbg** [Microsoft/vscode#64668]
Issue Type: <b>Bug</b>

Installed on archlinux with 'pacman -S code'. Start the app, Select "Help | Welcome | ... Printable keyboard cheatsheet"  gives "Unable to open 'workbench.action.keybindingsReference': resource is not available."

VS Code version: Code - OSS 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-12-06T23:12:09.502Z)
OS version: Linux x64 4.19.4-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3045)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 1|
|Memory (System)|3.79GB (0.14GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-elixir|mjm|1.1.0

</details>

**Comment by chrmarti** [comment]
You seem to be using a custom build that is missing some configuration (https://github.com/Microsoft/vscode/blob/0baabc8a8b506c92958e286272bb3cb0dded4dc5/src/vs/platform/node/product.ts#L59).

You can download the keyboard references here: https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference

Closing as downstream.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
cc @sandy081
