### ISSUE TITLE
Window resizing stopped working via spectacle

### ISSUE THREAD

**Issue by lockejan** [Microsoft/vscode#64670]
Issue Type: <b>Bug</b>

Since the latest update I'm not able to use my spectacle shortcuts for resizing the code window anymore.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
clojure|avl|0.10.2
paredit-revived|cos|0.1.21
vscode-markdownlint|Dav|0.22.0
prettier-vscode|esb|1.7.2
beautify|Hoo|1.4.7
python|ms-|2018.11.0
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1013
vscode-docker|Pet|0.4.0
LiveServer|rit|5.3.1
vscode-icons|rob|7.28.0
vim|vsc|0.16.13

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This does not sound like an issue with VSCode to me.

**Comment by lockejan** [comment]
I'm sure by now that it has something to do with vs code. I tried that on another fresh user account and a new vs code installation. Must be related to my settings, because it works fine with the new installation. Gonna reset my settings then.

**Comment by daneverson** [comment]
Hey @lockejan, what was your layer 8 bug? I seem to have it too...

**Comment by lockejan** [comment]
> Hey @lockejan, what was your layer 8 bug? I seem to have it too...

Hi @daneverson ,
I unknowingly disabled Spectale for vsc ...haha
hope that might help you, too.

Cheers

![image](https://user-images.githubusercontent.com/25434434/50989967-1b68ef80-1511-11e9-8ba5-e3f480d42fcc.png)

**Comment by daneverson** [comment]
Toggling that and then restarting vscode seems to have worked... 🤷‍♂️

Thanks for the reply!
