### ISSUE TITLE
Hang And Stays Unresponsive During Remote X Session

### ISSUE THREAD

**Issue by serialprimate** [Microsoft/vscode#64675]
Using 64-bit VSCode 1.29.1 over ssh with X running under Arch Linux patched to 9 Dec 18. No VSCode extensions. Fresh install of VSCode and Arch Linux. Fails to generate minidump. Other X applications are working.

1. Create a test folder and cd into it.
2. Start VSCode. (I ignored the bash ioctl messages, previous vscode issue claims that they are just benign messages.)
3. Welcome splash doc appears.
4. Select interactive playground.
5. Try to scroll all the way to bottom of playground page.
6. Hang/Unresponsive at 75% of Scroll (Failed to generate minidump etc)

Session Output:

1.20 test $ ~/Apps/VSCode/code .
[main 1:09:11 PM] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[main 1:09:41 PM] update#setState checking for updates
[main 1:09:41 PM] update#setState idle
Failed to generate minidump.[main 1:10:35 PM] [VS Code]: detected unresponsive

Does this issue occur when all extensions are disabled?: Yes

CPUs	Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (2 x 2903)
GPU Status	2d_canvas: unavailable_software
checker_imaging: disabled_off
flash_3d: unavailable_software
flash_stage3d: unavailable_software
flash_stage3d_baseline: unavailable_software
gpu_compositing: unavailable_software
multiple_raster_threads: disabled_off
native_gpu_memory_buffers: disabled_software
rasterization: unavailable_software
video_decode: unavailable_software
video_encode: unavailable_software
webgl: enabled_readback
webgl2: unavailable_off
Load (avg)	0, 0, 0
Memory (System)	7.79GB (6.33GB free)
Process Argv	--disable-extensions .
Screen Reader	no
VM	0%

Extensions are disabled

Image of Hang/Unresponse State
![vshang](https://user-images.githubusercontent.com/2203553/49693232-e0de0100-fbb8-11e8-8999-bddcabf1d422.JPG)

**Comment by serialprimate** [comment]
I have verified that the above issues do not appear to be duplicates.

**Comment by serialprimate** [comment]
It is possible that the X session has nothing to do with the issue and that the title is misleading. I didn't try without an X session for instance....

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by serialprimate** [comment]
Process explorer stays black screen. However code --status is as follows:
![image](https://user-images.githubusercontent.com/2203553/49720211-f16ea400-fcaa-11e8-9a98-f3abd8166082.png)

**Comment by jrieken** [comment]
process explorer doesn't show any CPU usage. Are you sure this is an issue with VS Code and not your setup?

**Comment by serialprimate** [comment]
Hi Johannes

No I am not 100% sure -- hence the earlier comment stating that the issue might be occuring generally under X, not just with remote access whcih is all I have.

To run code I had to install a few libraries in addition to the basic remote X configuraiton most apps need (afaik these are not listed as dependencies),.This indicates that Arch Linux might not include all dependencies out-of-the-box for VSCode on a base install with only what is needed for remote X to run (although other stuff does). Note that I didn't install the Arch X group of packages for running locally.

However so far most all of code works very well (thanks!) except for the playground item towards the bottom of the page and the process explorer. I am very encouraged by VSCode and although I don't need these things I thought I would send in the issue to help.

Is there a log file or something I could send or try out?

Thanks,

Matt

**Comment by serialprimate** [comment]
If it helps I just installed electron and all deps.

The issue persists.

**Comment by jrieken** [comment]
Please try with another electron app, like Atom, and see how that works in your setup.

**Comment by serialprimate** [comment]
I managed to get Process Explorer working -- it seems that it had something
to do with fonts.

When the bug is hit half of the processes disappear to the extent that it
shows the same as code --status after hitting the bug. Possibly a crash.

There might be a few dependencies outside of the exe linkage, possibly
things used in scripts or called from the exe.
Matt

**Comment by jrieken** [comment]
Please try something like atom
