### ISSUE TITLE
Please make a way to close the error window thing!

### ISSUE THREAD

**Issue by 11William** [Microsoft/vscode#64672]
Issue Type: <b>Feature Request</b>

Please make a way to close the error window thing! 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
