### ISSUE TITLE
Console window showing in case started from c#

### ISSUE THREAD

**Issue by aboodh95** [Microsoft/vscode#64676]
Issue Type: <b>Bug</b>

Hi,

I have an app written in c# that will do some automated task for me in the morning, one of them is to run visual studio code, this is a line of code that starts the app 
`Process.Start(@"C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe");`
the issue is VScode will run with a console window that shows the status of the application like app update status,
update#setState idle
update#setState checking for updates,

and in case I close it will close VSCode

![image](https://user-images.githubusercontent.com/12459798/49693313-83ca5700-fb88-11e8-816b-bd5b76288e2e.png)

this is not a big issue but I thought it will be better if I inform you about it

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (21.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
I think you want to launch the CLI instead of the exe, check the bin dir
