### ISSUE TITLE
step in smart selection for quotes

### ISSUE THREAD

**Issue by pinage404** [Microsoft/vscode#64688]
When i use the keyboard shotcut to use the smart selection, i would like to have a step when i select a string that select the string without quotes (new feature) and another step that select with quotes (current behavior)

**Comment by roblourens** [comment]
You are talking about the "expand select" command right?

**Comment by pinage404** [comment]
I'm talking about this command in my `keybindings.json`
```json
	{
		"key": "ctrl+shift+up",
		"command": "editor.action.smartSelect.grow",
		"when": "editorTextFocus"
	},
	{
		"key": "ctrl+shift+down",
		"command": "editor.action.smartSelect.shrink",
		"when": "editorTextFocus"
	},
```

**Comment by jrieken** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/64004
