### ISSUE TITLE
Should closeTab icon be hidden when highlightModifiedTabs is true?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#64684]
Using this config:
```json
"workbench.editor.tabCloseButton": "off",
"workbench.editor.highlightModifiedTabs": true,
```
\- dirty files still take space for closing button (and shifting all tabs). 

It makes sense that it worked that way when the only option to show `modified` state of files was the icon. 

Should it take into account highlighting option and not change tab width now?

**Comment by bpasero** [comment]
**Verification:** verify that the close button hides when this is configured:

```
"workbench.editor.tabCloseButton": "off",
"workbench.editor.highlightModifiedTabs": true
```

**Comment by bpasero** [comment]
@misolori this seems broken now with latest:

![image](https://user-images.githubusercontent.com/900690/66756130-a3619880-ee99-11e9-85c1-e1e1436f98d0.png)

Idea was to hide the dirty indicator in this case.

**Comment by misolori** [comment]
Fixed:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/35271042/66771502-3fc27580-ee6f-11e9-838d-a3806466510e.png">

**Comment by misolori** [comment]
This should also hide the dirty state when `workbench.editor.highlightModifiedTabs` is set to `true`. Right now it only hides it when `workbench.editor.tabCloseButton` is `off`.

**Comment by misolori** [comment]
Here's all of the states to verify:

When `workbench.editor.highlightModifiedTabs` is `true`:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/35271042/67420665-ec91a680-f583-11e9-8d1b-9e6b802a37da.png">

When `workbench.editor.tabCloseButton` is `off`:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/35271042/67420740-0df29280-f584-11e9-8b33-fb3089909f5d.png">

When `workbench.editor.highlightModifiedTabs` is on and `workbench.editor.tabCloseButton` is `off`:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/35271042/67420811-2b276100-f584-11e9-88dc-211c77078f41.png">

@bpasero @usernamehw let me know if I missed anything

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/67909235-b7fd8c00-fb3b-11e9-972a-444fafbae85d.png)
I see both the dot and the bar with 
```
  "workbench.editor.tabCloseButton": "right",
  "workbench.editor.highlightModifiedTabs": true
```

**Comment by JacksonKearl** [comment]
Actually maybe thats the desired behaviour?
