### ISSUE TITLE
How to reload a file?

### ISSUE THREAD

**Issue by RalfJung** [microsoft/vscode#64680]
- VSCode Version: 1.29.1
- OS Version: Linux, Debian testing

Steps to Reproduce:

1. Open a file
2. Change it on disk (maybe the file watcher was turned off because of too many files, or maybe it didn't work -- I did `git stash` and vscode did not reload automatically).

Now I'd like to reload the file manually.  I found several issues claiming I should do "File - Revert File", but that menu item is grayed out.  All I can do is close and re-open file file, which is terribly unergonomic.

**Comment by bpasero** [comment]
@RalfJung "Revert File" is correct but its a bug that it shows up as disabled

@isidorn looks like it got introduced via https://github.com/Microsoft/vscode/commit/3a1dce69bc1a5b5a6b95aaaf27ae5967324c7271

**Comment by RalfJung** [comment]
Ah, that looks like it would explain this.

FWIW, having items grayed out without any indication how to enable them again is a (rather common) frustrating anti-pattern in UI design.

**Comment by isidorn** [comment]
@bpasero not a lot of users seem to be hit by this, since I made the change in march and nobody complained until december.
Though I am perfectly fine with reverting the change I did.

**Comment by cedric05** [comment]
@isidorn 
can i work on it?

**Comment by isidorn** [comment]
@cedric05 I suggest no. If you would like to work on something please search for issues tagged with feature-request and help-wanted. Thank you

**Comment by kanlukasz** [comment]
I am not sure if this is the right ticket, but I think there should be an option "Ask to reload if the file is changed".

Something like -> https://github.com/microsoft/vscode/issues/79032 (marked as a duplicate, but I don't know where the right ticket is)
