### ISSUE TITLE
CPU usage per extension

### ISSUE THREAD

**Issue by goldingdamien** [Microsoft/vscode#64683]
I have many extensions enabled.
The CPU usage of ExtensionHost can be very high.
However, there is no further information available about what is causing the problem.
Testing out each extension one by one is very tedious and time consuming.
Ideally, I would like the process usage screen to have information on which extension it is being used by.
Any other way of quickly finding out what is slowing Visual Studio Code would be appreciated.

Regards.

**Comment by goldingdamien** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [High CPU usage in ubuntu16.04 (#26702)](https://www.github.com/Microsoft/vscode/issues/26702)

Not a duplicate.

**Comment by jrieken** [comment]
Select F1 > Show Running Extension. Then select the profile command (round button on the top right), let it profile for a bit, and then press it again. Will it have recorded a CPU profile and it will you which extension has taken most time.

**Comment by goldingdamien** [comment]
@jrieken Thank you for your response. I have already tried this and it was a lengthy process that was confusing and didn't seem to work well. 
Chrome has a Task Manager feature which is quick and easy to use.
The process you have suggested takes time, didn't seem to show much usage even though Windows Task Manager did and didn't work when recording while looking at opened files.
