### ISSUE TITLE
syntax highlighting is white and incorrect for html

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#64699]
Issue Type: <b>Bug</b>

Syntax highlighting is white and incorrect for html

![image](https://user-images.githubusercontent.com/2301847/49703747-47b5e700-fbc6-11e8-840f-853da8ad3e1b.png)

Minimal example:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>foo</title>
  </head>
  <body>
    <div></div>
    <script src="http://dummy"></script
    ><script src="http://dummy"></script
    ><!--[if lte IE 9]><script src="http://dummy"></script><![endif]-->
  </body>
</html>
```

An extension formatted it but it appears the syntax highlighting is a code bug?

VS Code version: Code - Insiders 1.30.0-insider (85f805acf9436381b878cab5ab6c5146beec7893, 2018-12-05T12:13:44.894Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
xml|Dot|2.3.2
EditorConfig|Edi|0.12.5
prettier-vscode|esb|1.7.2
flow-for-vscode|flo|0.8.5
python|ms-|2018.11.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.4.0
java|red|0.35.0
sass-indented|rob|1.4.9
vscode-fileutils|sle|2.13.3
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.15.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3

</details>

**Comment by alexr00** [comment]
The html grammar we use doesn't handle the greater than symbol being on the next line like this:

    </script
    ><script src="http://dummy"></script
    >
    
Is this something that you expect to be ok? It isn't a standard way of formatting html as far as I know.

**Comment by alexr00** [comment]
The html formatter is [here](https://github.com/Microsoft/vscode-html-languageservice/blob/master/src/services/htmlFormatter.ts), but I don't know all the details. The html grammar we use for syntax highlighting is here: https://github.com/textmate/html.tmbundle. 

You mentioned that you're using an extension to provide formatting: the build in VS Code html formatting fixed those strange end tags for me. Based on the spec you linked they're allowed, they just aren't what I expected to see.

Since the issue is with the grammar, I can forward this issue to https://github.com/textmate/html.tmbundle.

**Comment by alexr00** [comment]
This issue was moved to textmate/html.tmbundle#97

**Comment by joshunger** [comment]
Thanks @alexr00
