### ISSUE TITLE
Terminal: constant high CPU usage once terminal is open

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6469]
Seeing this on Mac, as soon as I open the terminal, CPU of the renderer is at constant 100%. This might be https://github.com/electron/electron/issues/38

**Comment by Tyriar** [comment]
Looks like that is it, no repro on Linux.

**Comment by kieferrm** [comment]
https://github.com/electron/electron/issues/38 was closed "because nobody cares about it". This pretty much renders the built-in terminal unusable on the Mac.  Two open vscode windows with a terminal take 280% on my 4-core mac making it sound like a helicopter ready for take-off.

**Comment by Tyriar** [comment]
@kieferrm it can be worked around by running the pty.js process in a child process, see https://github.com/atom-archive/terminal/issues/3#issuecomment-21086414

**Comment by Tyriar** [comment]
@bpasero please verify once a new build goes out (tests are currently failing on your side).
