### ISSUE TITLE
Formatting Parameter Hints

### ISSUE THREAD

**Issue by jfinity** [microsoft/vscode#64695]
If my environment has formatting available for the language that I'm working in, it would be awesome if parameter hints (or really any other "generated" syntactic content for tooltips/popovers) was formatted for better readability -- probably according to whatever drives the `formatOnSave` feature.  This would make it easier to parse/use unfamiliar APIs, especially when they have a lot of options.  It could even be opt-in via a toggle in user settings (like `formatOnSave` is).

**Comment by maciejmatczak** [comment]
For such python example with docstrings (!):
```python
def function1(arg1: int, arg2: str) -> str:
    """Very important function

    Args:
        arg1: description1
        arg2: description2

    Returns:
        Some string
    """
    pass
```
I am getting really nice hinting when I am typing the name of the function:
![s1](https://user-images.githubusercontent.com/1786383/59603231-2ac81680-9109-11e9-8dcf-289898c53124.png)
...but the first moment I type "(", it switches into SignatureHelp (command: "Trigger Parameter Hints"), which is not formatted:
![s2](https://user-images.githubusercontent.com/1786383/59603397-9dd18d00-9109-11e9-8d7a-672861f5e283.png)

TBH, I am not sure what triggers first view, but as both of those shares the same information value, I do prefer the one formatted.
