### ISSUE TITLE
Keybindings GUI is ignoring `category` defined in extension command

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#64692]
Issue Type: <b>Bug</b>

Using similar contribution in extension:
```json
"contributes": {
    "commands": [
        {
            "command": "extension.do",
            "title": "title",
            "category": "Category"
        },
    ]
}
```
Command palette is doing it correctly: `Category: title`

Keybinginds is only showing `title`.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by YisraelV** [comment]
I'm going to work on this.
