### ISSUE TITLE
Add Custom Document Well Option (like Productivity Power Tools 2017/2019 extension)

### ISSUE THREAD

**Issue by sponge-b0b** [microsoft/vscode#64690]
The horizontal scrollbar for file tabs is so tiny that it is very difficult to drag it with the mouse or track it using the scroll wheel. Currently there is a setting called Editor: Tab Sizing which only provides two options: fit and shrink.

I would like to propose a feature like the [Custom Document Well](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.CustomDocumentWell) option provided by the [Productivity Power Tools 2017/2019](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ProductivityPowerPack2017) extension.

This feature would allow users to customize the behavior and look of their document tabs.

- Scrollable tabs
    Maintain spatial consistency of the documents that are included in the document well.
- Vertical tabs
    Document tabs are shown vertically, allowing you to fit more tabs than are normally visible when shown horizontally.
- Show close button in tab well
    Show the close document button in the document well that will close the active tab, similar to Visual Studio 2008.
- Tab Commands for Navigation 
    Using Ctrl+Alt+Page Down and Page Up to navigate between tabs (including pinned) in visual order.
    Activate a specific pinned tab by Ctrl+Num Pad 1 through 0
    Activate a specific regular tab by Ctrl+Alt+Num Pad 1 through 0
- Sort by most recently used
    Whenever a tab becomes active, it is moved to the left - such that all tabs will be sorted in most recently used order.
- Sort tabs by project
    Tabs will be sorted by the project they belong to, thus keeping them always together in the document tab well.
- Sort tabs alphabetically
    Tabs will be sorted alphabetically. When Sort By Project is turned on, tabs will be sorted first by project and then alphabetically. 
- Color tabs according to their project or according to regular expressions
    This option permits tabs to be colored according to the project they belong to. This is particularly useful when sorting tabs by project, as it allows you to immediately identify different groups of project documents.
        You can also configure regular expressions and assign a color to each one. If the name of a tab matches the configured regular expression, it will be colored with the assigned color. 
- Show close button in tab
- Modify dirty indicator style
   This option allows you to select from a set of different dirty indicators that you might prefer over the asterisk.
- Modify minimum and maximum tab size
   Allows you to modify minimum and maximum tab size. Try setting minimum and maximum sizes to the same value, and you will have evenly spaced tabs.

Thanks in advance for your consideration.

**Comment by hdkesting** [comment]
Additional sort option: sort by full path. Useful for web projects with multiple "index.cshtml" or "default.aspx" files.
