### ISSUE TITLE
Add "Never pause here" option to breakpoint context menu

### ISSUE THREAD

**Issue by aleclarson** [microsoft/vscode#64696]
Please see [this article](http://www.mattzeunert.com/2016/03/17/devtools-never-pause-here.html) for context. This feature is very useful when you want to use "Pause on all exceptions" and then ignore the caught errors that you're not interested in.

`vscode v1.29.1`

**Comment by isidorn** [comment]
This would first require changes to the debug adapter protocol in case we decide to do it.
Doing a fake implemenation on the ux side sounds ugly (when we stop that we send an immediate continue) and would not always work.

**Comment by dominikschreiber** [comment]
FWIW I was able to recreate the desired effect with a simple conditional breakpoint that breaks on `false` (i.e. never).

**Comment by justingrant** [comment]
FWIW, many common types of apps, especially browser-based React apps, will throw 10+ exceptions upon app startup. Often this is because browser-based libraries will test for various browser capabilities by trying to run some code and catching the exception to determine if the browser supports the capability or not. 

This means that without the ability to exclude some locations, the "Break on all Exceptions" feature is essentially useless (or at least very time-inefficient) for these kinds of apps because every debug session involves hitting Go 10+ times before you get to any "real" exceptions.

**Comment by sovietspaceship** [comment]
I am having the same issues. Certain programs force the debugger to pause (e.g. `debugger` statements, SIGTRAP) even if there's no exception, which forces me to run them without the debugger.

**Comment by orokanasaru** [comment]
This is critical to have. Debugging npm scripts leads to thousands of exceptions when handling `require` statements, which means it is effectively impossible to break on caught exceptions. If the error you're interested in gets caught at some point, you realistically cannot use vscode to debug.

**Comment by weinand** [comment]
Try to use VS Code's "skipFiles" feature: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome

**Comment by justingrant** [comment]
According to https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code, 

> If you have set the option to break on thrown exceptions, then you won't break on exceptions thrown from skipped files unless they bubble up into a non-skipped file.

This is not what I'm seeing in VSCode 1.59. When the entire call stack is skipped (as indicated by grayed-out stack frames), VSCode still stops on these exceptions. Is this expected?

![image](https://user-images.githubusercontent.com/277214/128921104-871246bd-fa56-4a7a-b47d-57e747b4a6fe.png)

**Comment by weinand** [comment]
VS Code's January release has the ["Exclude callers from pausing at breakpoints" feature](https://code.visualstudio.com/updates/v1_64#_javascript-debugging).

This works for exception too: see https://github.com/microsoft/vscode/issues/127775#issuecomment-1030213220

Please give it a try.
