### ISSUE TITLE
Debugger attached fails with Node 11.4.0

### ISSUE THREAD

**Issue by blfuentes** [Microsoft/vscode#64693]
- VSCode Version: 1.29.1
- OS Version: Windows 10 build 10.0.17763.134
- Node: 11.4.0
- Typescript: 3.2.2

Steps to Reproduce:

1. Create typescript file
2. Add package.json, tsconfig.json and launch.json with config for debugging
3. Start debugger

**test.ts**

    let mystring: string = "mytest";

    for (let character of mystring) {
        console.log(`found ${character}`);
    }

**package.json**

    {
        "name": "test",
        "version": "0.1.0",
        "private": "false",
        "devDependencies": {},
        "dependencies": {
            "@types/node": "^10.12.12",
            "ts-node": "^7.0.1",
            "typescript": "^3.2.2"
        }
    }

**tsconfig.json**

	{
		"compileOnSave": true,
		"compilerOptions": {
			"noImplicitAny" : true,
			"strictNullChecks": true,
			"types": ["node"], 
			"lib":[
				"es2018",
				"dom"
			],
			"target": "es2018",
			"module": "commonjs"
		},
		"files":[
			"test.ts"
		]
	}

**launch.json**

	{
		// Use IntelliSense to learn about possible attributes.
		// Hover to view descriptions of existing attributes.
		// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
		"version": "0.2.0",
		"configurations": [
			{
				"name": "Current TS File (Server)",
				"type": "node",
				"request": "launch",
				"args": ["${relativeFile}"],
				"runtimeArgs": ["--nolazy", "-r", "ts-node/register"],
				"sourceMaps": true,
				"cwd": "${workspaceRoot}",
				"protocol": "inspector",
			}
		]
	}

**Error:**

	C:\Program Files\nodejs\node.exe --nolazy -r ts-node/register --inspect-brk=19178 test.ts 
	Debugger listening on ws://127.0.0.1:19178/52758bb2-f70f-4657-9655-42ef3f2d661e
	For help, see: https://nodejs.org/en/docs/inspector
	Debugger attached.
	internal/modules/cjs/loader.js:605
		throw err;
		^
	
	Error: Cannot find module 'test.ts'
		at Function._resolveFilename (internal/modules/cjs/loader.js:603:15)
		at Module._compile (internal/modules/cjs/loader.js:702:31)
		at Object..js (internal/modules/cjs/loader.js:734:10)
		at Module.load (internal/modules/cjs/loader.js:620:32)
		at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
		at Function._load (internal/modules/cjs/loader.js:552:3)
		at Module.require (internal/modules/cjs/loader.js:659:17)
		at internal/modules/cjs/loader.js:844:12
		at prepareUserCodeExecution (internal/bootstrap/node.js:297:7)
		at startExecution (internal/bootstrap/node.js:275:5)
	Waiting for the debugger to disconnect...
	Error: Cannot find module 'test.ts'
	loader.js:603
		at Function._resolveFilename (internal/modules/cjs/loader.js:603:15)
		at Module._compile (internal/modules/cjs/loader.js:702:31)
		at Object..js (internal/modules/cjs/loader.js:734:10)
		at Module.load (internal/modules/cjs/loader.js:620:32)
		at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
		at Function._load (internal/modules/cjs/loader.js:552:3)
		at Module.require (internal/modules/cjs/loader.js:659:17)
		at internal/modules/cjs/loader.js:844:12
		at prepareUserCodeExecution (internal/bootstrap/node.js:297:7)
		at startExecution (internal/bootstrap/node.js:275:5)

If I go back to Node 11.3.0 it works.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
> Error: Cannot find module 'test.ts'

This looks like a problem with ts-node. Can you even run the program from the terminal without vscode debugging involved?

**Comment by blfuentes** [comment]
> > Error: Cannot find module 'test.ts'
> 
> This looks like a problem with ts-node. Can you even run the program from the terminal without vscode debugging involved?

yes, I could compile and run the code directly from the terminal.

**Comment by roblourens** [comment]
With exactly the same command arguments? It's clearly an error from the program so I don't know what the difference is.

**Comment by blfuentes** [comment]
> 
> 
> With exactly the same command arguments? It's clearly an error from the program so I don't know what the difference is.

Sorry for the uncompleted reply.
**Works:**

`tsc
node .\test,js`

**Fails:**
`node .\test.ts --nolazy -r ts-node/register`


    (function (exports, require, module, __filename, __dirname) { let mystring: string = "mytest";
                                                                          ^

    SyntaxError: Unexpected token :
        at new Script (vm.js:83:7)
        at createScript (vm.js:267:10)
        at Object.runInThisContext (vm.js:319:10)
        at Module._compile (internal/modules/cjs/loader.js:686:28)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
        at Module.load (internal/modules/cjs/loader.js:620:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
        at Function.Module._load (internal/modules/cjs/loader.js:552:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
        at executeUserCode (internal/bootstrap/node.js:342:17)`

With another example with a simple import { ModuleName } from "./ModuleName" it waises similar error:

     import { MarbleNode } from "../MarbleNode";
            ^

     SyntaxError: Unexpected token {

Should I create the issue in the ts-node github?

**Comment by roblourens** [comment]
It looks like you got an explanation from upstream. 👍

**Comment by blfuentes** [comment]
> It looks like you got an explanation from upstream. 👍

sorry, but I don't get it. the same was working and works with 11.3.0 and stopped with 11.4.0. What am I doing wrong with my launch.json?

**Comment by roblourens** [comment]
I think you need to ask ts-node that question, they said you are not using the right arguments.

**Comment by blfuentes** [comment]
> I think you need to ask ts-node that question, they said you are not using the right arguments.

I am using the a similar launch.json they have in the github. I modified to make it look like this and it works. Difference is I send the ${workspaceRoot} within the args and no longer using cwd. 
Could it be the new node version has any problems to resolve it?

Generated command is still the same:

**Node 11.3.0** (works)

> C:\Program Files\nodejs\node.exe --nolazy -r ts-node/register --inspect-brk=22234 test.ts 
Debugger listening on ws://127.0.0.1:22234/c6c4c4cb-5af8-477f-a4d3-7ae7cf1931d6

**Node 11.4.0** (old launch.json not working)
>C:\Program Files\nodejs\node.exe --nolazy -r ts-node/register --inspect-brk=40666 test.ts 
Debugger listening on ws://127.0.0.1:40666/bae735eb-e51d-4930-aab4-329c1066fa92

**Works**-->

>C:\Program Files\nodejs\node.exe --nolazy -r ts-node/register --inspect-brk=36677 C:\Users\insan\source\repos\test/test.ts 
Debugger listening on ws://127.0.0.1:36677/6c886e43-efea-4744-9e9b-deb07c1f39c1


    {
        "name": "Launch Program 2",
        "type": "node",
        "request": "launch",
        "runtimeArgs": [
            "--nolazy",
            "-r",
            "ts-node/register"
        ],
        "args": [
            "${workspaceRoot}/${relativeFile}"
        ],
        "protocol": "inspector",
    }

**Comment by roblourens** [comment]
I'm glad you found a workaround. But you are saying that `C:\Program Files\nodejs\node.exe --nolazy -r ts-node/register --inspect-brk=40666 test.ts` works in 11.3 but not 11.4. But the error message is from node/ts-node, so you need to file an issue on them.

**Comment by blfuentes** [comment]
> I'm glad you found a workaround. But you are saying that `C:\Program Files\nodejs\node.exe --nolazy -r ts-node/register --inspect-brk=40666 test.ts` works in 11.3 but not 11.4. But the error message is from node/ts-node, so you need to file an issue on them.

Yes, I know, I commented also there. Just was writing here in case anyone has the same issue. It looks like a problem with the deprecated env variable `${workspaceRoot}`

Thanks for checking this :)

**Comment by roblourens** [comment]
Got it, thanks for following up! 👍
