### ISSUE TITLE
Rejecting the promise returned from provideReferences doesn't display an error to the user

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#647]
If I return a rejected promise from `provideReferences`, no error is displayed to the user and an empty "No results" window is shown.

Is this intentional?  

There seems to be different behaviour of rejected promises across the various providers.  Perhaps the docs could indicate what resolved and rejected promises are expected to mean?

**Comment by jrieken** [comment]
Yes, that is intentional. Because multiple providers can contribute to a result, like multiple document symbol provider, failure of one shouldn't let all fail. That also applies to the case of just 1 provider...

**Comment by lukehoban** [comment]
I see - that makes sense.  

It would be nice to add documentation of the rejected promise behaviour across the various providers since there are differences in how to (or whether it is even allowed to) report errors back to users.

**Comment by jrieken** [comment]
I agree
