### ISSUE TITLE
jar包中文乱码

### ISSUE THREAD

**Issue by zoro-web** [Microsoft/vscode#64708]
Issue Type: <b>Bug</b>

jar包中文乱码

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (2.23GB free)|
|Process Argv|E:\软件\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
GBKtoUTF8|buk|0.0.2
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
vscode-language-pack-zh-hans|MS-|1.25.3
vetur|oct|0.12.6
view-in-browser|qin|0.0.5
java|red|0.30.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3

</details>

**Comment by jrieken** [comment]
Please file issues in English. Thanks!

**Comment by 0xff007** [comment]
> 
> 
> Please file issues in English. Thanks!

jar package encoding error, when the package includes Chinese comment.

**Comment by 0xff007** [comment]
> 
> 
> Please file issues in English. Thanks!
Reproduce issues:
1. init a spring-boot project;
2. add dependency
```
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.0.6</version>
</dependency>```
3. browse the dependency by "JAVAEPENDENCIES"
4. context encoding error
