### ISSUE TITLE
Allow decorations on empty characters

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6470]
Indent guide-related extensions have issues keeping blocks continuously styled because they can't add decorations to empty lines. Is there some way we could enable this? It would be able to have an ideal implementation of indent guides (#2192) encapsulated within an extension.

- https://github.com/spywhere/vscode-guides/issues/1
- https://github.com/oderwat/vscode-indent-rainbow/issues/7

**Comment by alexandrudima** [comment]
By design decorations are clamped to the buffer's text, so I don't plan to ever support this.

**Comment by wmertens** [comment]
@alexandrudima So I suppose this same thing applies to the built-in indentation guides, they will never be able to show the full extent of a block?

Would it be possible to hack around this by adding virtual indentation characters in the editor, that aren't actually stored in the file?

**Comment by wmertens** [comment]
Err oops, I see that VSCode actually draws the indent lines for the entire block, I missed that. So I presume that is implemented in a different way…

**Comment by Tyriar** [comment]
Closing since @alexandrudima mentions he doesn't plan to implement. The problem mostly goes away now since native indent guides have been added.

**Comment by alexandrudima** [comment]
@wmertens Yes, indent guides are a custom view concept - https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/indentGuides/indentGuides.ts

That has the advantage that they don't take the memory usually associated with a decoration (two tracked markers on the line + options) and can be painted custom even on empty lines (with no content). My hope is that, in time, we can enrich this implementation to accomodate all indent guides use cases (e.g. rainbow colors, background colors, etc.)

**Comment by wmertens** [comment]
@alexandrudima that makes me very happy! One implementation I really like is https://atom.io/packages/indent-guide-improved for Atom (doesn't do indents on empty lines)

![gif](https://i.github-camo.com/83f38ef15d0f90120fec4fc21fab18fc3ac0effc/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f68617261692f696e64656e742d67756964652d696d70726f7665642f6d61737465722f646f632f64656d6f2e676966)

So if that would be possible on VSCode too…

**Comment by alexandrudima** [comment]
@wmertens Highlighting the current indent level is a very useful idea - created #9069
