### ISSUE TITLE
The import suggestion should be visible even when the scroll is not at the start

### ISSUE THREAD

**Issue by mike9ar** [Microsoft/vscode#64702]
Issue Type: <b>Feature Request</b>

When I scroll the editor to right side the import hint is not visible beause it always apparear in start position of editor, this is a problem specialy when work with two or more editor open.

![gif_demo2](https://user-images.githubusercontent.com/22224714/49706174-f710af00-fc02-11e8-9303-e8fd9489d1fc.gif)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
> When I scroll the editor to right side the import hint is not visible beause it always apparear in start 

Use `Cmd+.` to get the menu where your cursor is. The lightbulb itself is more to advertise  this feature exists
