### ISSUE TITLE
A Extension Back-Up

### ISSUE THREAD

**Issue by Chawki726** [Microsoft/vscode#64704]
Hello VSCode...
**All of us has the the situation of Uninstalling VScode due to moving to new PC/or resetting current PC**
I too had a situation to reset my PC and after i re-install VSCode i lose my all extension which i had install previous,due to that i wanna install previous extensions again
_Please Try to Update this feature..._
**Thank you.**

**Comment by usernamehw** [comment]
```
code --list-extensions > extensions.list
```

**Comment by usernamehw** [comment]
Install list of extensions #42994

**Comment by sandy081** [comment]
Duplicate of #2743
