### ISSUE TITLE
php定界符里面的内容,无语法错误显示和语法高亮显示

### ISSUE THREAD

**Issue by qq471754603** [Microsoft/vscode#64706]
![image](https://user-images.githubusercontent.com/23146592/49708452-a46add80-fc6a-11e8-8a5f-15066b1ed204.png)

**Comment by qq471754603** [comment]
![image](https://user-images.githubusercontent.com/23146592/49708514-eac03c80-fc6a-11e8-8ff4-33efb3b7aa27.png)

**Comment by qq471754603** [comment]
全是一个颜色,也没有错误提示,我都是粘到别的编辑器里面改好后,复制过来的

**Comment by jrieken** [comment]
Please file issues in English. Thanks!
