### ISSUE TITLE
Add incremental search to Explorer View

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#64701]
The file list in Explorer view tends to become rather long.

It's rather tedious to search for a file in Explorer for editing by using the mouse wheel when using a touch pad.

I know there already is a command available to incrementally search for files in the Command text box, but for it to succeed you need to know the file's name.
<br/>

**So I'd like to suggest to be able to have the cursor go to a file in Explorer by typing the file's first letters.**
<br/>

This would allow to "close in" on any file by typing a neighbour letter, e.g. "`t`" to hit the "`trace.go`" file while actually searching for "`support.go`", without knowing the actual correct file name ("`support.go`" in this example).
<br/>

**The suggested feature would mimic the original Visual Studio behaviour. — To one exception:**

Visual Studio interprets pressing the <kbd>SHIFT</kbd> key in Solution Explorer as a Selection Range Extension marker (in order to select a range of files). So files containing underscore characters cannot be selected on German keyboards (because "`_`" is generated by typing <kbd>SHIFT</kbd>+<kbd>-</kbd> on German keyboards). (I already filed a bug at Microsoft Connect for almost 10 years now, but no-one in the Visual Studio team actually cares, Jesus!)

VS Code should do better and interpret the <kbd>SHIFT</kbd> key **only** as a range extension mode flag when any of the cursor keys (<kbd>ARROWS</kbd>, <kbd>PAGE UP/DOWN</kbd>, <kbd>HOME</kbd>, <kbd>END</kbd>) is pressed. With any other keyboard combination resulting in a printable character, `SHIFT` should not be regarded as a range extension modifier and a file containing the resulting character should be selected instead.
<br/>

**The following table shows two different behaviours when pressing the following keys (on a German keyboard):**

- <kbd>M</kbd>
- <kbd>O</kbd>
- <kbd>C</kbd>
- <kbd>K</kbd>
- <kbd>SHIFT</kbd>+<kbd>-</kbd>
- <kbd>N</kbd>

| undesired behaviour | desired behaviour |
|-|-|
|<img alt="VS Code Explorer Incremental Search - no" src="https://user-images.githubusercontent.com/9283914/49705622-ff2b1780-fc1f-11e8-9ae0-fa09ba7b481c.gif" width="330">|<img alt="VS Code Explorer Incremental Search - yes" src="https://user-images.githubusercontent.com/9283914/49705623-005c4480-fc20-11e8-9c8a-94c11c18abd9.gif" width="330"/>|

**Comment by SetTrend** [comment]
@isidorn: Where's the duplicate? I couldn't find it?

**Comment by isidorn** [comment]
Search for issues tagged with file-explorer and feature-request and you will find it. Sort by upvotes

**Comment by SetTrend** [comment]
Thanks!

/ref: #10026
