### ISSUE TITLE
Show in-progress state for git fetch

### ISSUE THREAD

**Issue by colinpeters** [microsoft/vscode#64700]
I'm in a situation where the git fetch and git fetch from all remotes commands can be quite slow (and for this reason I trigger them manually). There is no indication that these commands are still in progress or when they finish (e.g. overlaying the clock icon on the SCM icon). Could there be an indication of in-progress state for the fetch commands like there is for commit and such?

**Comment by Jakobud** [comment]
This would be a nice feature to have. The synchronize icon in the bottom left status bar spins when doing other git push/pull activities. Would be great if it also did the same while fetching.

**Comment by joaomoreno** [comment]
#62751
