### ISSUE TITLE
Quickly display the file shortcut "shift+ alt+r" in Explorer, which is not available on the editor's editing file

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#64707]
Issue Type: <b>Bug</b>

Quickly display the file shortcut <code>"shift+ alt+r" </code>in Explorer, which is not available on the editor's editing file. But when selecting the file on the sidebar and using <code>"shift+ alt+ r"</code>At the time of the key, you can open the file explorer and display the file in it. If you design this way, then this will not be a bug. But I hope you can add some configuration to let our users choose.

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:31:41.479Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
@czfadmin, if you asking for a way to invoke `Reveal in Explorer` from editor -  it's possible to do with keybindings:

```json
{
	"key": "shift+alt+r",
	"command": "-revealFileInOS",
	"when": "!editorFocus"
},
{
	"key": "shift+alt+r",
	"command": "revealFileInOS",
},
```

**Comment by czfadmin** [comment]
@usernamehw Thank you very much, this method has helped me perfectly.

**Comment by usernamehw** [comment]
/question

I'm just going to close this. Ignore the bot's message.
