### ISSUE TITLE
Auto Save Issue 

### ISSUE THREAD

**Issue by Justonly5** [Microsoft/vscode#64705]
Issue Type: <b>Bug</b>

When I turn on the auto save, once auto save is triggered,the cursor goes to the end of the current file.And I can find anywhere to prevent the cursor changing.It's very  unhuman nature.Hope it can be fixed in the next version.Thanks.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.22.0
githistory|don|0.4.4
javadebugger|don|0.1.5
jquerysnippets|don|0.0.1
xml|Dot|2.3.2
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.45
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
svn-scm|joh|1.46.4
vscode-simple-icons|Lau|1.9.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-zh-hans|MS-|1.29.2
node-debug2|ms-|1.30.1
PowerShell|ms-|1.10.1
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.1.1
vscode-manifest-yaml|Piv|1.1.1
vscode-spring-boot|Piv|1.1.1
material-icon-theme|PKi|3.6.1
vscode-jsp|pth|0.0.2
java|red|0.35.0
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.2
guides|spy|0.9.2
codelf|unb|10.9.0
vscode-java-debug|vsc|0.15.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.11.1
vscode-maven|vsc|0.11.3
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.3
vscode-react-native|vsm|0.7.0
gitblame|wad|2.6.3
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
