### ISSUE TITLE
After windows update auto restart vscode open wrong files

### ISSUE THREAD

**Issue by Daijobou** [Microsoft/vscode#64714]
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Datum: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architektur: x64
Windows 10

I hate windows for this! I go few minutes away from my pc and windows install a update and restarting automatically. All my data all my unsaved files lost. After restart windows open vscode, but that open files from days ago, so I must now search ~50 files I had open in a very big project and check status of this files.

1. After windows update restart I wish that vscode open files before windows restart and not files that was open days ago. That would be a great help.

2. I would like that vscode can stop that damn auto windows update, when here are files not saved. That is not the first time this happen. :(

**Comment by bpasero** [comment]
The UI state loss is tracked in https://github.com/Microsoft/vscode/issues/12058

As for unsaved files lost, that sounds like a hot-exit issue to me.

**Comment by Tyriar** [comment]
@Daijobou can you reproduce this when an update does not happen on your machine when you force kill VS Code using task manager?

**Comment by Daijobou** [comment]
Today this shi* happens again. Windows 10 have make a update, and unsaved files are lost. vscode opens old files and tabs that not exists anymore, because files was long ago moved to other folders:
![image](https://user-images.githubusercontent.com/260343/50471618-d2b02300-09b5-11e9-82f2-2e2ab86054b1.png)
