### ISSUE TITLE
Quick open is not displaying all the matching files.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6471]
- VSCode Version:1.1.0-alpha
- OS Version:Windows10

Steps to Reproduce:
1. Launch app and open smoke test project folder.
https://github.com/Microsoft/vscode-smoketest-express
2. Run "npm install" and "npm install vscode".
3. Launch quick open window by pressing CTRL+P.
4. Enter patter to get info about all the typing files like *.d.ts
5. Verify result for typings file (.d.ts).

Actual: Not getting all the files.
![image](https://cloud.githubusercontent.com/assets/17735796/15348012/b0165b90-1c7b-11e6-921e-577287d16e91.png)

Expected: Should display all the files.

Note: On my MAC machine it is working fine.

**Comment by bpasero** [comment]
Check your settings for excludes:

![image](https://cloud.githubusercontent.com/assets/900690/15348093/c968ab74-1cc7-11e6-9b24-18b54d4af0dc.png)

**Comment by v-pavanp** [comment]
I  already added "**/node_modules": false in settings.json. Looks like it is fixed now as I am getting proper result.
Clarification: 
1. Do we expect recently open files should be display in "quick open" window if it is part of exclusion?
Bug https://github.com/Microsoft/vscode/issues/6502 
2. Why there is file with .yml is showing up in the result when we are targeting for typings file (.d.ts)
3. I could see on MAC Ipaddr.test.coffee file is showing up in the result.
Windows:
![image](https://cloud.githubusercontent.com/assets/17735796/15377625/f60fe508-1d11-11e6-8c4a-4fd07bdb52c8.png)

MAC:
<img width="618" alt="screen shot 2016-05-18 at 4 04 41 pm" src="https://cloud.githubusercontent.com/assets/17735796/15377790/149f51ba-1d13-11e6-8edc-c08f77cde9fb.png">

**Comment by bpasero** [comment]
The search is fuzzy, so *.d.ts matches partially on the path and partially on the file. Please check that the coffee file is really installed on both OS, maybe it was not.
