### ISSUE TITLE
Themes should not Override Explicit Output Colors

### ISSUE THREAD

**Issue by cawoodm** [Microsoft/vscode#64716]
- VSCode Version: 1.29.1
- OS Version: Windows 10 64bit

It seems that dark themes "hijack" the color of terminal output. While this may be desirable in some situations, in general it's incorrect. When a program wants to display green text in a dark theme (e.g. "Solarized Dark") it displays like this:
![image](https://user-images.githubusercontent.com/498834/49723299-c95d5180-fc66-11e8-8b58-0fa816e470f1.png)

With the "PowerShell ISE" Theme the colors are correct:
![image](https://user-images.githubusercontent.com/498834/49723326-d8440400-fc66-11e8-840a-4489c852b286.png)

IMHO a theme should not be affecting such colors. This is a theme overstepping it's reach.

Steps to Reproduce:
1. Choose a dark theme
2. Run `Write-Host "I should be green" -Foregroundcolor green` in a powershell terminal

**Comment by cawoodm** [comment]
Yes, I realised that after the fact. I just find it weird that a theme can overwrite yellow say, and make it gray. I'm sure it's nice to be able to make yellow another shade of yellow but it can break stuff. I guess someone decided this is a feature not a bug.

**Comment by Tyriar** [comment]
Solarized has a weird palette for the terminal https://ethanschoonover.com/solarized/#the-values
