### ISSUE TITLE
Disable debug button if in debugging mode

### ISSUE THREAD

**Issue by RealBuddy** [microsoft/vscode#64710]
Issue Type: <b>Feature Request</b>

Let's disable green play button for certain configuration if the debug configuration is already running.
It interferes with blue play button on the debug panel.
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.0.0

**Comment by isidorn** [comment]
@karanisverma ok. Here's a code pointer https://github.com/Microsoft/vscode/blob/f041bc0c5f05e3b53468b0de0765cbd9a1407c31/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L26

The action is already disabled, it is just now grated out.

Basically if the start debug action is disabled via [this](https://github.com/Microsoft/vscode/blob/f041bc0c5f05e3b53468b0de0765cbd9a1407c31/src/vs/workbench/parts/debug/browser/debugActions.ts#L163) the icon should be faded out.

**Comment by karanisverma** [comment]
Awesome! Thanks @isidorn for code pointer. I will share PR for the same.

**Comment by karanisverma** [comment]
Thanks @RealBuddy!

**Comment by karanisverma** [comment]
Hi @isidorn, I have pulled the changes from master. However I am can't see [ isEnabled function ](https://github.com/Microsoft/vscode/blob/f041bc0c5f05e3b53468b0de0765cbd9a1407c31/src/vs/workbench/parts/debug/browser/debugActions.ts#L163) which you pointed to. master's [isEnabled function](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L135) always returns true!? 
I am confused 🤔 Please help.

**Comment by isidorn** [comment]
@karanisverma sorry but I do not have time this milestone to help with Pull Requests.
If you can try to figure it out, if not I can fix this issue later in January.
Thanks

**Comment by karanisverma** [comment]
Thanks @isidorn, I will try to figure it out :)

**Comment by karanisverma** [comment]
sorry for the delay, I will resume working on it from tomorrow. hopes that's fine 🙄
