### ISSUE TITLE
CachedData folder is eating up my disk. Can it be deleted?

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#64711]
I find the folder `C:\Users\xxx\AppData\Roaming\Code\CachedData` has many children folders and every one is about 30 MB size. In all, this folder uses about 300 MB and is going to be larger with the time increasing. 

I want to know can I just clean these folders? Can vscode make a clean for folders not used recently? Thank you in advance.

**Comment by jrieken** [comment]
>  Can vscode make a clean for folders not used recently

It does that - for insiders everything which is older then 3 weeks and for stable everything that's older than 3 months: https://github.com/Microsoft/vscode/blob/005b5bdaf5bfff5fe2b348875252cc3e2ef0ce81/src/vs/code/electron-browser/sharedProcess/contrib/nodeCachedDataCleaner.ts#L15-L17
