### ISSUE TITLE
Make case sensitive text selection/navigation through words when keeping alt pressed

### ISSUE THREAD

**Issue by charmpitz** [Microsoft/vscode#64726]
The behavior should be the same like the one from Sublime Text when holding `alt` key for navigation or `alt` + `shift` keys for selection in combination with the arrow keys `<-` / `->`.

It's needed when trying to select a piece or multiple ones via multiple cursor from camel cased words allowing the user to be much faster. 
Example: (`alt` + `shift` + `right`) for `camelCaseWork` will select only `camel` instead of the whole word
Right now the only option is to select it letter by letter which is really annoying.

It's something that I miss very much since I replaced Sublime with Visual Studio Code and I think there are lots of other people that feel the same way. I really hope you'll take this into consideration. Keep up the good work :v: !

**Comment by AndreiScheau** [comment]
indeed, this would be very nice

**Comment by alexandrudima** [comment]
This is already implemented. e.g. on macOS we ship with the following keybindings for it:

```
{ "key": "ctrl+alt+left",         "command": "cursorWordPartLeft",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+left",   "command": "cursorWordPartLeftSelect",
                                     "when": "textInputFocus" },
{ "key": "ctrl+alt+right",        "command": "cursorWordPartRight",
                                     "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+right",  "command": "cursorWordPartRightSelect",
                                     "when": "textInputFocus" },
```

**Comment by charmpitz** [comment]
Thank you! You're a life saver, for anybody else who's using Linux for example should use these instead:
```
    {
        "key": "alt+left",
        "command": "cursorWordPartLeft",
        "when": "textInputFocus"
    },
    {
        "key": "shift+alt+left",
        "command": "cursorWordPartLeftSelect",
        "when": "textInputFocus"
    },
    {
        "key": "alt+right",
        "command": "cursorWordPartRight",
        "when": "textInputFocus"
    },
    {
        "key": "shift+alt+right",
        "command": "cursorWordPartRightSelect",
        "when": "textInputFocus"
    }
```
