### ISSUE TITLE
Blank rectangle over screen

### ISSUE THREAD

**Issue by e11en** [Microsoft/vscode#64722]
Issue Type: <b>Bug</b>

Everytime I maximize the window there is a blank (grey) rectangle over Visual Code itself. I can't do much with the top portion of the window missing. Disabling all the extensions doesn't make a difference, neither does restarting my pc.

![image](https://user-images.githubusercontent.com/855939/49734026-52828180-fc83-11e8-8c30-46faec8b3124.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (18.75GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.22.0
githistory|don|0.4.4
gitlens|eam|9.0.3
tslint|eg2|1.0.40
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
debugger-for-chrome|msj|4.11.1
convert-css-in-js|pau|1.1.3
typescript-hero|rbb|3.0.0
vscode-react-native|vsm|0.7.0

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by e11en** [comment]
Unfortunately the bug is also in the build you provided.

**Comment by bpasero** [comment]
Does it reproduce when running `code --disable-gpu`?

**Comment by e11en** [comment]
I do see an improvement but I think the issue is not with VisualCode itself because I'm finding other programs that have the same thing, so I think it's something weird on my system. Thanks for the help anyway!
