### ISSUE TITLE
macOS: certain commands executed twice when focus is in webview

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#64724]
Extracted from https://github.com/Microsoft/vscode/issues/56988#issuecomment-419044926

When invoking a keybinding that also exists on the macOS native menu, while having focus inside a webview, the command is both triggered through the menu and our keybinding forwarder ([here](https://github.com/Microsoft/vscode/blob/ac0b37b2d220e55e76f79be96e3c31a1dbf9e892/src/vs/workbench/parts/webview/electron-browser/webviewElement.ts#L306)). 

It looks like we could possibly use `webContents.setIgnoreMenuShortcuts(true)` to workaround this, but then any menu that is implemented with a `:role` will not work (e.g. cut, copy, paste).

**Comment by mjbvz** [comment]
I wonder if we can use the [`before-input-event`](https://electronjs.org/docs/api/web-contents) here to avoid having the listener in the webview

**Comment by mjbvz** [comment]
@sbatten Suggested that #64228 may also be of interest

**Comment by bpasero** [comment]
@mjbvz with your change, any command that is implemented with a `:role` does not work anymore inside the webview. For example, try to `Cmd+C` or undo/redo in an input field, it will not work because these commands only worked through the menu.

**Comment by bpasero** [comment]
Actually since this issue is addressed, let's move that new issue to https://github.com/Microsoft/vscode/issues/65452
