### ISSUE TITLE
[folding] Disabling plugin removes collapse (+-) of block codes

### ISSUE THREAD

**Issue by PrzemyslawKlys** [microsoft/vscode#64720]
- VSCode Version: 1.29.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open .ps1 file with some code (may work for other files, haven't checked) 
2. Collapse / uncollapse some code block - this works
3. Disable any plugin
4. Option to collapse/Uncollapse is gone (+- is not visible).  

This happens until you reload VSCode. The same thing happens when you reinstall the plugin. Until VSCode is reloaded you can't collapse code anymore. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
I can't reproduce. What extension do you disable? Do you also reload?

**Comment by PrzemyslawKlys** [comment]
It doesn't really matter which. What I noticed just now is that if you Disable extension, Enable it back and Disable again I can use folding again properly. 

Reloading fixes things but the point is that if you disable the plugin and don't reload folding stops working (unless you do a workaround as above). It simply disappears. 

![vscode problem](https://user-images.githubusercontent.com/15063294/50685445-84d09600-1019-11e9-8433-eeb873039e99.gif)

Please notice the movie starts with already "workaround" in place as I started recording after some testing. But after I reload the window .. it shows how the problem looks like. 

Let me know if you need anything else?

**Comment by aeschli** [comment]
Thanks for the great GIF, sadly, I can't reproduce (yet)

**Comment by aeschli** [comment]
dup of #75726
