### ISSUE TITLE
Quick copy lines in diff view, round 2

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#64725]
#22003 is a feature request and deserves to be upvoted by the community the same way as all feature requests do

Now the VS Code bot has closed the isue and no one can vote it up.

Also, the issue is not a duplicate, it is a feature request. 
Yet the _Stage selected ranges_ is useful, we would like this feature working in a regular diff view, without SCM or git involved

Could you please re-open it?

Thank you

**Comment by joaomoreno** [comment]
This is what you want to upvote: https://github.com/Microsoft/vscode/issues/25887
