### ISSUE TITLE
webview: sometimes focus is not passed to editor when clicked into

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#64729]
Extracted from https://github.com/Microsoft/vscode/issues/56988#issuecomment-418677482

Steps to Reproduce:

1. install `negokaz.live-server-preview`
2. have below HTML file
3. "Show Live Server Preview"
4. click into the preview on the right and left a couple of times

=> 🐛 at some point the editor focus is not detected, even though we clicked into the webview

![before](https://user-images.githubusercontent.com/900690/49745421-3391e880-fc9f-11e8-9a78-d9e330311ec2.gif)

**Comment by bpasero** [comment]
Maybe related: https://github.com/electron/electron/issues/13697

**Comment by mjbvz** [comment]
The only way I could find to reliably track focus for webview contents that include iframes is polling. If you have any other ideas here, please let me know as I'm not a fan of this solution

**Comment by bpasero** [comment]
@mjbvz maybe leave in a todo for you to check back on that workaround, it is possible that the webview might get fixes in the future. At least we should check when we update to Electron 4.

I also could not find any good solution and it seems others are having issues too.
