### ISSUE TITLE
[folding] Ctrl-Click to Unfold All Nested

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#6472]
This is a feature request.
Ctrl-Click to Unfold All Nested. Similar to Notepad++.

This is the wanted behaviour:

Start state:
![](http://puu.sh/oW54z.png)

Collapse again:
![](http://puu.sh/oW57K.png)

Ctrl-Click the + button:
![](http://puu.sh/oW5af.png)

**Comment by Tyriar** [comment]
<kbd>ctrl</kbd>+click was also considered to add an additional cursor on Linux but not done because currently <kbd>ctrl</kbd>+click opens links in the document (#3091).

**Comment by burdiyan** [comment]
It's also valid for folding directories in the sidebar. On a Mac for example it's a native behavior, when you fold or expand something pressing `alt (option) + mouse click` all nested elements in that folder are folded or expanded respectively.

It would be nice upgrade for VS Code if it could follow the same rule.

Thanks.

**Comment by doctorsirius** [comment]
Other editors use **Alt + Click** to fold/unfold all nested elements, I think it's pretty standard.

**Comment by aeschli** [comment]
Added `Shift + Click` on the folding icon to fold/unfold recursively (in 1.19)
