### ISSUE TITLE
Inconsistent behavior of context menu in Open editors view when it has regular and new (Untitled) files

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#64735]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:31:41.479Z)
OS version: Windows_NT x64 10.0.17763

When Open editors view has regular and new (not saved, with Untitled-X title) files - incorrect context menu might be rendered depending on order of files you call it for.

Steps to Reproduce:

1. Open some existing file. Right click on it in Open editor  will display **regular file context menu** (Similar options to menu in Explorer view - contains Open to the Side, Reveal in Explorer etc.)
1. Ctrl + N to create new file and type somethin in it.
1. Right-click on `Untiteled-1` in Open editors view. **New file context menu** (Save As..., Compare with selected etc.) will be shown.
1. Right-click on any previously opened existing file. **New file context menu** will be shown for existing file.
See `Context menu for noname-55.svg` below.

Next steps will allow to get regular context menu for new file (continue after steps above). I use this as workaround for issue reproduced above.

1. Right-click on any file in File explorer view.  **regular file context menu** is displayed.
1. Right-click on any `Untiteled-X` file in Open editors view. **Regular file context menu** is displayed. However actions like Open to the side and Open in Terminal doesn't do anything, while Select for compare, Compare with selected - works properly for unsaved files.
See `Context menu for Untiteled-3` below.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (17.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

Extensions: none

<details>
<summary>Context menu for Untiteled-3 file</summary>

![image](https://user-images.githubusercontent.com/1312662/49751202-81b1e680-fcb5-11e8-8835-ca40e962fe9b.png)

</details>

<details>
<summary>Context menu for noname-55.svg</summary>

![image](https://user-images.githubusercontent.com/1312662/49751312-c6d61880-fcb5-11e8-81d7-d9a3a582191c.png)

</details>

**Comment by isidorn** [comment]
@IllusionMH thanks a lot for filling this issue and for using vscode insiders.

**Comment by isidorn** [comment]
@bpasero can you please verify this with the latest vscode insiders. 
Open editors view, make sure the context menu has the appropriate content for:
* regular editors
* untitlated editors
* editor groups
Also verify that context menu focused the list element it was invoked upon.

**Comment by bpasero** [comment]
@isidorn there is still something fishy:
* close all editors
* open untitled file
* open normal file
* right click normal file: OK
* ESC
* right click untitled file: OK
* ESC
* right click normal file: you see the context menu of the untitled file still

Is that expected?

**Comment by bpasero** [comment]
@isidorn there is now a difference of the context menu between insiders and stable: In stable I get a lot of entries (like "Compare with") and in insiders (`3dcdcc3fe0ed44d8c58be03df3c35e1edcb454e9`) I only get 4 entries. Is that expected? E.g. I cannot compare 2 untitled files anymore?

**Comment by IllusionMH** [comment]
I hope that is not intended. I'm comparing 2 untitled files on daily basis (that's how I found this issue).

**Comment by bpasero** [comment]
Reopening based on testing, I think we regressed compared to stable (I tested on Linux).

**Comment by isidorn** [comment]
I have created a PR which should fix this fully https://github.com/Microsoft/vscode/pull/64808
However that PR is a bit risky imho, since it potentially touches the global ResourceContextkey. Though I create it scoped so we should be fine.

IMHO we should take the half baked fix which is already on the release branch and take the pull request for recovery only if more users complain. My suspicion is that nobody will notice it and we can wait unitl next release to ship it.
@IllusionMH you are already using insiders so you will be good in a couple of days

**Comment by IllusionMH** [comment]
Thank you!
