### ISSUE TITLE
Fix ITreeRenderer type

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64732]
Seeing `as any as WorkbenchAsyncDataTree<TreeElement>;` or this ` as any as WorkbenchObjectTree<TreeElement, FilterData>` makes me believe that there is no TypeScript-allowed way to instantiate and assign the new tree...

**Comment by jrieken** [comment]
maybe this is also kind of debt but I in the references view I still see squiggles when removing that stunt..

**Comment by joaomoreno** [comment]
As discussed, this is regarding the typing of the generic parameter of `ITreeRenderer`, as an argument to the List/Tree.

**Comment by joaomoreno** [comment]
Closing this for now:

- We can't really improve the ctor `IRenderer` typing without extra TypeScript features.
- Two ways of instantiating workbench trees:
  - Simply invoke the ctor
  - Or use the instantiation service, but you must explicitly provide the generic types to the `createInstance` call, like in https://github.com/Microsoft/vscode/blob/3fc2c90836d995e46bda6803fe36865282edad94/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L362
