### ISSUE TITLE
Allow a terminal to be launched with an explicit environment

### ISSUE THREAD

**Issue by GabeDeBacker** [Microsoft/vscode#64731]
This request is similar to #18522.

VSCode is configuration a bunch of environment variables before the terminal process is launched. For our terminal scenarios (such as setting up our complex build environment) we need to be in complete control of the environment passed in. 

In other words, have a flag that tells VSCode to not inherit any of the process environment variables and only use the environment passed in.

In our build environment today, some of the VSCode environment variable values (such as LANG) are not in the proper format when starting the build environment.

We have the ability to specifically set the environment to exactly what we want.

The proposal is adding this:
	export interface TerminalOptions {
		/**
		 * When set to true, the process environment from VSCode is ignored and the
		 * terminal process only contains what is in the "env" member.
		 */
		noInheritEnv?: boolean;
}

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/64733
