### ISSUE TITLE
add space when searching for theme

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#64740]
Press `F1`, `Change Color Theme`.
Choose `Install Additional Color Themes` from the quick pick.

The extension viewlet opens with `category:themes` pre-populated in the search box and the caret is at the end of the line, after the `s`:

![image](https://user-images.githubusercontent.com/1487073/49753631-da0ec700-fc68-11e8-965b-9147e055c9ef.png)

If I start typing now (e.g. start looking for a theme) I don't get any results because I need a space between `category:themes` and whatever I'm searching for, in this case `cobalt`:

![image](https://user-images.githubusercontent.com/1487073/49753676-fb6fb300-fc68-11e8-8ee5-40e0f1e953b3.png)

It would be nice to add the space automatically so that I can just start typing, not having to remember to press space first.

**Comment by usernamehw** [comment]
> If I start typing now (e.g. start looking for a theme) I don't get any results because I need a space between `category:themes` and whatever I'm searching for, in this case `cobalt`:

This part is a dup of #40518
