### ISSUE TITLE
Debug variables aren't accessible over an async/promise call

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#64748]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:31:41.479Z)
OS version: Windows_NT x64 10.0.18290

When using the nodejs/extension debugger, variables/watch/etc aren't accessible over an async/promise call.

Before the async/promise call -- variables are accessible
![image](https://user-images.githubusercontent.com/641685/49761886-3dfbb480-fc96-11e8-86e3-80c6ed9ece0d.png)

After the async/promise call -- nothing is accessible
![image](https://user-images.githubusercontent.com/641685/49761910-49e77680-fc96-11e8-8602-6db178164bfb.png)

It would be great to still be able to inspect the context (variables, etc) when walking back the call stack over an async/promise call.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.64GB free)|
|Process Argv|C:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
This is a limitation from chrome/node. When you look into an async frame, you are looking into the past, so the data for those variables doesn't exist anymore. Nothing we can do on our end unfortunately.

**Comment by eamodio** [comment]
Damn :(
