### ISSUE TITLE
Allow inspecting scroll position of the new tree

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64749]
The settings tree uses these API from the old tree to implement syncing the visible elements with the TOC:

- getFirstVisibleElement, onDidScroll

This is also used to handle the case when we tab out of the virtualized tree and have to manually scroll down to get to the next element:

- getLastVisibleElement

**Comment by roblourens** [comment]
I am now using the new tree with the settings editor (much more straightforward than the search view, and the dynamic sizing works great!), but a couple things won't work quite right without this.

**Comment by joaomoreno** [comment]
Verification: please code review.

**Comment by roblourens** [comment]
Awesome, thanks. Is it possible to get the same behavior as the old version where it looks at how far the top element is scrolled off the page:

https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L668

I can try it if you can tell me what's the best way to get the scroll position of an item? `style.top`?

**Comment by roblourens** [comment]
> `this.rangeMap.positionAt(range.start)` will get you the top position of that element (for `firstVisibleIndex`)

**Comment by bpasero** [comment]
We should not do verification through code review. Steps?

**Comment by roblourens** [comment]
- Scroll the settings list
- See the highlighted TOC item as you scroll - it should be accurate and feel natural. When the top item is >= 50% scrolled out of view, then the next item is used as the current item for the TOC.
