### ISSUE TITLE
When zoomed in, sometimes explorers are lost

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#64742]
Install the [Azure Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-node-azure-pack) extension which installs a handful of extensions and the Azure Viewlet.

Set the `window.zoomLevel` to `3`

Expand the explorers in the Azure viewlet.

![image](https://user-images.githubusercontent.com/1487073/49754148-345c5780-fc6a-11e8-89eb-f32d722f4137.png)

Storage, or whatever is last in the list, is lost...

![image](https://user-images.githubusercontent.com/1487073/49754168-3b836580-fc6a-11e8-99f1-e81467e3d330.png)

**Comment by sandy081** [comment]
duplicate of #64188
