### ISSUE TITLE
Too many open issues and `under-discussion` label

### ISSUE THREAD

**Issue by ccinelli** [Microsoft/vscode#64759]
This came up when in #63465 I read: "I left it open with that tag [`under-discussion`] so interested people can keep commenting." from @roblourens. 

### Too many issues

I do not spend a lot of time on [Visual Studio code 's issue page](https://github.com/Microsoft/vscode/issues). Initially I found pretty daunting seeing almost 4,500 open issues. 

I was unsure if posting an issue would receive any attention or change anything. 
It is also time consuming to find if an issue was already reported. When you find it and it is still open after more than a year, you wonder what the status is and if it is worthwhile to write anything. 

In general, I think the first impression is either "they do not maintain the issues here" or "they do not listen here". It takes a little bit to find out that there are both false. 

I would suggest being a "little" more aggressive in closing issues. I do not like when they force you to close issues for some policy or fake metrics. But if there are really 4,000+ relevant issue, VS Code needs  more engineers to solve these issues ;-) 

### `under-discussion` label

It look like that at the moment the `under-discussion` label is used to bring to the surface some issues that are worth to be discussed.

I thought the label was for an "internal" purposes. If you use this label to bring to the surface some issues to prioritize based on people reactions, I think it would be better to make sure that it is clear what it stand for and channel people to "issues with the label `under-discussion`" in some way.

**Comment by roblourens** [comment]
First about #63465 - You'll get a better response if you open smaller issues directed toward specific suggestions. It's hard to handle an issue that encapsulates a list of general issues. It got some attention and good discussion right away, and I didn't have time to write a response, so I left it alone to see if it got more community responses. I try not to leave issues for that long without a response, but again, it's easier when they are more focused.

Regarding issue management, we do put a lot of effort into maintaining a "manageable" set of high quality issues. We triage every incoming issue, end up closing most of them as dupes, not actionable, etc, and periodically we sweep the entire set to close anything which isn't realistically going to happen in the next 6 to 12 months. So any issue that's still open, even if it looks stale, has been reviewed and kept.

If you want to read more, there are some docs about our process here: https://github.com/Microsoft/vscode/wiki/Issue-Tracking and here: https://github.com/Microsoft/vscode/wiki/Issue-Grooming
