### ISSUE TITLE
"Find in files" returns duplicate files

### ISSUE THREAD

**Issue by frostius** [Microsoft/vscode#64756]
- VSCode Version:1.29.1
- OS Version:Win10 x64

Find in files is returning the same file twice.  The first has a relative path, the 2nd a full path

![fif](https://user-images.githubusercontent.com/3818866/49765893-5ae5b700-fc99-11e8-99ae-7ca73d7b0d24.PNG)

**Comment by roblourens** [comment]
Is that file currently open? 

Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by frostius** [comment]
Yes, it appears to only happen when the file is open.  After playing with it for a bit, it seems to be caused by debugging a node.js app.  The debugger opens files by full path instead of the relative (workspace) path and I end up with two tabs pointing to the same file.   Not sure if this should be logged as a separate debugger issue or both?

**Comment by roblourens** [comment]
If you hover the files and look at the full paths, are they _exactly_ the same, even casing? 

You can keep the issue here because as luck would have it, I am also the node debugger person so I can help on both ends 😁

**Comment by frostius** [comment]
Nope, case problems .  Hitting a breakpoint causes the file to be opened by full file path. That portion of the path that precedes the workspace appears to be incorrectly lowercase.  Specifically folder "SW" should be uppercase.

![capture2](https://user-images.githubusercontent.com/3818866/49905324-dc248180-fe32-11e8-81e7-a66a32265001.PNG)
![capture](https://user-images.githubusercontent.com/3818866/49905329-df1f7200-fe32-11e8-842e-f7b8896f7543.PNG)
![capture3](https://user-images.githubusercontent.com/3818866/49905438-49381700-fe33-11e8-8655-27f7ee8941d9.PNG)

**Comment by roblourens** [comment]
Could you 

- Set `"trace": true` in your launch config
- Do the debugging steps that cause that file to be opened
- A path to a log file will be in the debug console, upload it here

Then we can figure out how the bad casing gets into the app, there are many possibilities...

**Comment by frostius** [comment]
Thanks for the help troubleshooting.  The workspace config file has a lowercase path.  Fixing that solved the problem.  

Feel free to close the issue if you don't plan on fixing this in code

**Comment by frostius** [comment]
The config file that defines a workspace.  My project has 2 workspaces.  I can't remember if how I created them (manually or via drag/drop) but I'm regretting not creating all lowercase paths :)

![image](https://user-images.githubusercontent.com/3818866/49909384-485bb100-fe44-11e8-94b0-03989e1e1823.png)

**Comment by frostius** [comment]
I was thinking you might verify and normalize the workspace path on load so that any uses of it are correct

**Comment by roblourens** [comment]
Got it. Yes this is an issue for us, we have https://github.com/Microsoft/vscode/issues/12448

**Comment by frostius** [comment]
Turns out fixing the case in the workspace path did not resolve the issue.  I've attached the trace file. 
The file is opened when the breakpoint is hit.

![image](https://user-images.githubusercontent.com/3818866/50165167-f5ea1c80-02a9-11e9-93a0-8cc05871bc3d.png)

![image](https://user-images.githubusercontent.com/3818866/50165124-dce16b80-02a9-11e9-8aad-75ed17c7dd7c.png)

[debugadapter.zip](https://github.com/Microsoft/vscode/files/2691216/debugadapter.zip)
