### ISSUE TITLE
Escape key does not cancel the move to trash dialog

### ISSUE THREAD

**Issue by osechet** [Microsoft/vscode#6475]
- VSCode Version: 1.1.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Select a file in the explorer
2. Press the Delete key on the keyboard
3. In the confirmation dialog, press the Esc key on the keyboard
=> The file is sent to trash

Expected Behavior:

The confirmation dialog should close and the file should not be deleted.

**Comment by bpasero** [comment]
Great find!
