### ISSUE TITLE
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

### ISSUE THREAD

**Issue by SnarkosaurusRex** [Microsoft/vscode#64751]
I'm having this same thing happen: https://github.com/Microsoft/vscode/issues/46255#issue-307227468

_Originally posted by @vscodebot in https://github.com/Microsoft/vscode/issues/46255#issuecomment-376936452_

**Comment by SnarkosaurusRex** [comment]
I haven't added any extensions, so I'm reasonably sure that it isn't caused by an extension.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
