### ISSUE TITLE
Strict null check 'vs/base/browser/ui/menu/menu.ts'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64754]
Part of #60565

Tracks updating `./vs/base/browser/ui/menu/menu.ts` to have strict null checking

**Steps**

1. Add `./vs/base/browser/ui/menu/menu.ts` to the `files` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works

**Comment by sbatten** [comment]
including `menubar.ts` as well
