### ISSUE TITLE
Support macOS Mojave accent colors

### ISSUE THREAD

**Issue by ScottRudiger** [microsoft/vscode#64758]
- VSCode Version:
- OS Version:

OS settings for `Accent color` are not reflected in VSCode:

Steps to Reproduce:

1. Change `Accent color` to `graphite` in System Preferences -> General
![screen shot 2018-12-10 at 3 10 56 pm](https://user-images.githubusercontent.com/26824724/49768473-5917f580-fc91-11e8-9506-f727087e61f9.png)

2. Confirm that other applications such as Chrome show grey close/minimize/expand buttons
![screen shot 2018-12-10 at 3 06 14 pm](https://user-images.githubusercontent.com/26824724/49768499-67fea800-fc91-11e8-9e4e-2e9a5651d814.png)
3. See that VSCode's buttons are red/yellow/green.
![screen shot 2018-12-10 at 3 09 44 pm](https://user-images.githubusercontent.com/26824724/49768527-81075900-fc91-11e8-8aa7-c8b59b73a6d0.png)![screen shot 2018-12-10 at 3 24 10 pm](https://user-images.githubusercontent.com/26824724/49768554-8b295780-fc91-11e8-8edf-a6b9fd073fd4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Chrome seems to custom draw these buttons. The finder looks the same as VSCode in dark theme:

![image](https://user-images.githubusercontent.com/900690/49780516-257bb080-fd0f-11e8-8ccd-b9e627ac26fc.png)

**Comment by ScottRudiger** [comment]
It's actually not the dark theme that sets the button colors; it's `Accent color` below that.

**Comment by ScottRudiger** [comment]
@bpasero Could you reopen the issue considering the above?

Here's my finder with `Accent color` set to grey:
![screen shot 2018-12-12 at 6 36 35 am](https://user-images.githubusercontent.com/26824724/49876502-64c20400-fdd8-11e8-815d-8aa64d98f5dc.png)

**Comment by jasmeet1999** [comment]
you need to change Title Bar Style from Custom to Native

- **Title Bar Style:** Custom
![custom](https://user-images.githubusercontent.com/16633209/63186759-dc88b280-c07a-11e9-9246-f3cac9058435.png)

- **Title Bar Style:** Native
![native](https://user-images.githubusercontent.com/16633209/63186838-0b9f2400-c07b-11e9-98bf-e2b8b6c86d46.png)

**Comment by ScottRudiger** [comment]
Thanks @jasmeet1999! I'm on a new machine without the issue, but I'll check it out on my other computer shortly.
