### ISSUE TITLE
Double click word selection does not use wordPattern

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64769]
Issue Type: <b>Bug</b>

**Repo**
1. For a markdown file:

```md
abc—xyz
```

1. Double click on `abc` or `xyz`

**Expected**
`abc` or `xyz` selected individually.

Markdown now (in VS Code 1.31) provides its own wordPattern that splits `abc—xyz` properly

**Actual**
The entire string `abc—xyz` is selected

Possible related to #33701

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:24:17.051Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|-psn_0_11606801|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by alexandrudima** [comment]
This is by design. We want word navigation to be consistent across all programming languages / editors, so they are implemented by using the setting `editor.wordSeparators`.
