### ISSUE TITLE
Outline view in Explorer Panel -- support for AsciiDoc

### ISSUE THREAD

**Issue by jegillikin** [Microsoft/vscode#64761]
The Outline section of the Explorer panel automagically offers a document map for Markdown. Which is great. However, other light markup syntax (and I'm thinking especially of AsciiDoc, because that's what I'm using) is better equipped to handle more complex, lengthy documents. Yet the Outline section reports "no symbols found in document" using AsciiDoc syntax.

Given that AsciiDoc (and, presumably, others) are semantically solid, allowing for the Outline section to support more than just Markdown would make for a welcome addition.

**Comment by mjbvz** [comment]
This must be implemented per language. Please file this feature request against the AsciiDoc extension
