### ISSUE TITLE
Visual Studio is Lacking Visual Cues

### ISSUE THREAD

**Issue by Nchaka** [Microsoft/vscode#64763]
Issue Type: <b>Feature Request</b>

For instance, when you try to commit code, it should highlight the input field asking for information in a different color (and some other obvious thing for bipolar folks) to attract the attention of the coder. The reason this is getting trickier than ever before is because in Visual Studio Code, the user input field is popped up in different places, seemlessly, while one may not even pay attention to it.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
We leave things like this on a theme-by-theme basis. Themes can further highlight colors when needed. Also, accessibility readers will announce the change of the input box.
