### ISSUE TITLE
the location of the global search

### ISSUE THREAD

**Issue by imlijq** [Microsoft/vscode#64766]
Issue Type: <b>Feature Request</b>

The global search moves from the activity bar on the left to the panel below. I am not used to it. I hope I can define the location myself and configure the location of the global search.

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:31:41.479Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
You can change this by right clicking on the search view and selecting "Toggle search view position", or with the setting `search.location`. You might have changed this by accident.

**Comment by imlijq** [comment]
thank you
