### ISSUE TITLE
Smile face and frown face have different "characters left" number

### ISSUE THREAD

**Issue by zxzxy1988** [Microsoft/vscode#6476]
- VSCode Version:1.1.1
- OS Version:Windows

Steps to Reproduce:

1.Click the smile face in the bottom right, and you will see the smile face and frown face 
2. Clicking on the smile face, you will see there are 117 chars left, while in frown face you will see 130 chars left.

Not sure if this is a bug, but I am thinking the chars left number should be the same.

**Comment by Tyriar** [comment]
Possibly related: https://github.com/Microsoft/vscode/pull/5116

**Comment by eklavyamirani** [comment]
I think this is intentional. The message being posted is different. The one with the smiley face includes the phrase "#HappyCoding " -> 13 chars.

The one with the frown face doesn't include this hashtag.

**Comment by Tyriar** [comment]
I just tried it out and that is the reason for the discrepancy. Thanks @eklavyamirani!
