### ISSUE TITLE
VSCode becomes extremely slow and laggy after waking up from suspend

### ISSUE THREAD

**Issue by sbstp** [microsoft/vscode#64774]
- VSCode Version: 
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Kubuntu 18.10

Steps to Reproduce:

1. Suspend computer by closing the lid
2. Wake up from suspend, try using VSCode. The interface is unresponsive and laggy, the window is essentially unusable until VSCode is restarted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by sbstp** [comment]
Yes it does. It seems like the amount of time it sleeps for is related. If my laptop only sleeps for a few minutes there's no noticeable lag. If it sleeps for a day VSCode is unusable.
