### ISSUE TITLE
Logo vscode in zen mode

### ISSUE THREAD

**Issue by llkiriell** [Microsoft/vscode#64776]
I suggest that the isotype be visible in zen mode 🙏. Currently, it shows nothing.

![issues_2](https://user-images.githubusercontent.com/12781734/49780752-ff89e800-fcdd-11e8-9b80-6c36f1d7edce.jpg)

**Comment by sbatten** [comment]
although the title bar controls this, I will defer to @isidorn as it is really a zen mode decision. My opinion however is that zen mode is intentionally less cluttered

**Comment by Astrantia** [comment]
Zen mode doesn't need to show icon. It's good as it is.

**Comment by llkiriell** [comment]
Why don't need @Astrantia? For me it isn't that good. 
At least, I suggest that it be optional. Please. 🙏
