### ISSUE TITLE
+ key does not work while in VS code

### ISSUE THREAD

**Issue by kylesaltmarsh** [Microsoft/vscode#64773]
When I try to type + it does not enter anything. I have to navigate to another application and type + and then copy and paste it where I want it in my VS code window. 

- VSCode Version: 1.29.1 (1.29.1)
- OS Version: 10.13.6 (17G65)

Steps to Reproduce:

1. Try to type + in VS code

**Comment by alexandrudima** [comment]
@kylesaltmarsh How do you try to type +? Do you press <kbd>Shift</kbd>+<kbd>=</kbd> ? Can you check your `keybindings.json` and see if you have configured something for "shift+=" ?
