### ISSUE TITLE
Python error: NotImplementedError: cannot determine number of cpus

### ISSUE THREAD

**Issue by MichaelT0** [Microsoft/vscode#6477]
I try to use sklearn package in python and meet this error.

- VSCode Version:1.1.0
- OS Version: Windows 10

Steps to Reproduce:

```
from sklearn.tree import DecisionTreeRegressor
```

**Comment by weinand** [comment]
@MichaelT0 python is not part of VS Code but a separate extension. Please file this error against the python extension you are using.
