### ISSUE TITLE
Wrong icon for word-based suggestions

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#64777]
- VSCode Version: 1.30.0-insider `241923763dbeaf3b64443187e935d55b29f6125d`
- OS Version: macOS

![image](https://user-images.githubusercontent.com/10441177/49781325-f2d7b500-fd1a-11e8-9d1f-da82462defc1.png)

As you can see somehow in suggestions word-based suggestions contains Untitled file icon.

**Comment by mjbvz** [comment]
I don't think should not use file icons but we make it more clear they are text suggestions with a different icon

**Comment by svipben** [comment]
@mjbvz Thank you!

**Comment by svipben** [comment]
@mjbvz If I'm correct this fix is not included in `Version 1.30.0 (1.30.0) c6e592b2b5770e40a98cb9c2715a8ef89aec3d74`?

**Comment by mjbvz** [comment]
Yes, it's marked December/jan so VS Code 1.31
