### ISSUE TITLE
controll shell crtl+c  can't Interrupt

### ISSUE THREAD

**Issue by spitWind** [Microsoft/vscode#64771]
Issue Type: <b>Bug</b>

when run a progame or input some thing in terminal, It cannot be interrupted by "ctrl + c" or "ctrl + z"
![image](https://user-images.githubusercontent.com/18753430/49775758-2e32ad80-fd34-11e8-83df-8216b1559063.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.90GB (11.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
