### ISSUE TITLE
Keyboard events should stop dragging

### ISSUE THREAD

**Issue by kevinresol** [Microsoft/vscode#6478]
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.4

Steps to Reproduce:
1. Hold left mouse button and drag-select some text
2. Press some keyboard key, to replace or delete the selected text
3. Release left mouse button

Actual Result:
Some texts are selected, depending on the location of the mouse release

Expected result:
No texts are selected. (i.e. keyboard events should finish any pending mouse drags)

Notes:
This operation (the delayed mouse release) may sound unnatural at first place. But on OSX one can use a three-finger gesture to represent a mouse drag, which has a slight delay between the finger release and the actual drag finish, causing the problem to emerge.

**Comment by bpasero** [comment]
Verified but found related: https://github.com/Microsoft/vscode/issues/27836
