### ISSUE TITLE
No debug console output in presence of compile errors

### ISSUE THREAD

**Issue by remster** [Microsoft/vscode#64781]
Issue Type: <b>Bug</b>

It's a go project. There is plenty compile problems in the code, yet none of them is shown, see:
![vsc_emptydebugconsole](https://user-images.githubusercontent.com/8327961/49784268-f66c3b80-fd1c-11e8-9334-561559951e5e.png)
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1451)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.39GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.11.0
cpptools|ms-|0.20.1
Go|ms-|0.7.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-go
