### ISSUE TITLE
Explorer: improved copy/paste into another folder 

### ISSUE THREAD

**Issue by DarkLite1** [microsoft/vscode#64784]
Version: 1.30.0-insider (user setup)
Commit: 241923763dbeaf3b64443187e935d55b29f6125d
Date: 2018-12-07T22:31:41.479Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.2.9200

Steps to Reproduce:

1. In the explorer pane copy a folder
2. Paste the folder in the same location
3. The folder already contained that folder name, so vs code creates a new one with the name 'MyFolder1'.

Notice that Windows explorer or vs code explorer is not asking to overwrite the file or merge it. This seems to be normal behavior, because that same action in Windows Explorer renames the pasted folder to 'MyFolder - Copy' and not 'MyFolder1' as vscode-insiders does..  

Expected behavior would be:
- Either ask to merge/overwrite the folders, when the same name is already present
- Or use the same naming convention as Windows does, with the extension '- Copy'

**Comment by anthonyvdotbe** [comment]
Imho, the actual behavior for copy/pasting into the same folder (as requested by @DarkLite1 above) doesn't need to change.

However, for copy/pasting into another folder, I'd like VS Code:
* for files, to prompt "replace/skip"
* for folders, to prompt with 3 options:
  * merge (+ prompt "replace/skip" for files with the same name)
  * replace
  * skip
