### ISSUE TITLE
Make `disposeElement` optional

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64787]
From a quick scan it seems that very few renderer implements `disposeElement` and therefore I'd suggest making this optional. I also wonder if this is an anti-pattern? Isn't the whole point of template vs element that the latter are lightweight and don't require much creation and disposal?

**Comment by joaomoreno** [comment]
Yeah, it's a good point. The use cases for `disposeElement` can also be solved by having an `elementDisposables` collection on the template data and disposing them right at the top of `renderElement`. So I'd even be willing to completely remove it. :+1:
