### ISSUE TITLE
Tag and colorize explorer folders

### ISSUE THREAD

**Issue by Obiwarn** [Microsoft/vscode#64786]
I am not sure if there is already an extension for this.

I often confuse files that are named alike in different folders like test, models, and views.
E.g. Tree.test.js, TreeModel.js and TreeView.jsx.

It would be great to Tag those global folders with a basic color (like in OSX) and then have the background of the files in the folder have that color when I collapse that folder in the explorer.
So I quickly see in which folder I am or which one I have unfolded at the moment.

**Comment by isidorn** [comment]
To find the duplicate search for issues tagged with file-explorer and feature-request
