### ISSUE TITLE
on item tab right click choose open file in explorer, VSCode no response

### ISSUE THREAD

**Issue by msccreater** [Microsoft/vscode#64782]
Issue Type: <b>Performance Issue</b>

open a file, on the item tap right click, choose "open file in explorer", then VSCode is dead, no response

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (5.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    81	 17248	code main
    0	    29	 14552	   shared-process
    0	    75	 17132	   gpu-process
    0	   269	 18480	   window (AloneCopyScene.lua - vscode (工作区) - Visual Studio Code)
    0	     5	  8356	     watcherService
    0	    18	 15028	     extensionHost
    0	    15	  2320	       electron_node main.js 
    0	    18	  3324	       "C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=15028
    0	     1	 16788	     electron-crash-reporter
    0	     1	 17360	     winpty-process
    0	     5	 12076	       console-window-host (Windows internal process)
    0	     3	 12428	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    40	 21356	     searchService
    0	    74	 18992	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AloneCopyScene.lua - vscode (工作区) - Visual Studio Code)
|    Folder (server_script): 439 files
|      File types: lua(439)
|      Conf files:
|    Folder (gui): 2486 files
|      File types: png(1914) lua(426) xml(120) json(12) tps(12) lua_tmpl(1)
|                  ttf(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
vscode-language-pack-zh-hans|MS-|1.29.2
vscode-lua|tri|0.12.4

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
