### ISSUE TITLE
Allow local file path for json.schemas

### ISSUE THREAD

**Issue by spitWind** [Microsoft/vscode#64796]
Issue Type: <b>Bug</b>

url: "E:\\\\a.json"
it prompt can't not find host
![image](https://user-images.githubusercontent.com/18753430/49795377-c81a4a80-fd74-11e8-8f22-f76845db5c32.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.90GB (9.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
jsontotype|dan|0.0.3
docthis-customize-tags|dwe|0.4.5
code-runner|for|0.9.5
vscode-language-pack-zh-hans|MS-|1.29.2
addDocComments|ste|0.0.8

</details>

**Comment by octref** [comment]
What's your config for `json.schemas`? What schema does the current file use?

**Comment by spitWind** [comment]
> 你的配置是`json.schemas`什么？当前文件使用什么模式？

i use url as a Absolute path  ; file model :-rw-r--r--

**Comment by octref** [comment]
@spitWind I mean for this setting. What's your value for it?

![image](https://user-images.githubusercontent.com/4033249/50016129-244fbb00-ff7d-11e8-8ded-ec2e741a91b5.png)

**Comment by spitWind** [comment]
![image](https://user-images.githubusercontent.com/18753430/50216071-c4637500-03bf-11e9-9395-4955b6bee686.png)

**Comment by octref** [comment]
We don't support file URLs yet. I marked this as a feature request.

**Comment by aeschli** [comment]
File URIs sre supported. (`file:///c:/home/aeschli/workspaces/testing/schema/foo.schema.json`).
@spitWind Can you try this?
