### ISSUE TITLE
Detection of duplicate javascript function names !!

### ISSUE THREAD

**Issue by ikourfaln** [Microsoft/vscode#6479]
- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:

if we have two or more functions with the same name, there is no syntax highlighting error !!

![sans titre](https://cloud.githubusercontent.com/assets/9744226/15356433/8dca48ce-1cf0-11e6-83d7-a099d7e9839f.png)

is this feature not yet available in the language services or I miss samething here ?

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8684
