### ISSUE TITLE
Need `isDOMFocused`

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64791]
blocks https://github.com/Microsoft/vscode/issues/64727 

The old tree could be asked for having focus but the new tree doesn't support that.

**Comment by joaomoreno** [comment]
`tree.getHTMLElement() === document.activeElement` :confused:

**Comment by jrieken** [comment]
Ok, lets remove `domFocus` following that logic

**Comment by joaomoreno** [comment]
Fair point. :+1:
