### ISSUE TITLE
Powershell Lag

### ISSUE THREAD

**Issue by MattLParker** [Microsoft/vscode#64806]
Issue Type: <b>Performance Issue</b>

When using powershell (64 or 32) for around 5-10 minutes, running run code snip or debug will result in cpu spikes on powershell, and will hang in the integrated console for multiple minutes, even on a command that runs near real time.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (15.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	 13788	code main
    0	   185	  3184	   window (Migrate-DLs.ps1 - scripts - Scripts - Visual Studio Code)
    0	    13	 14172	     watcherService 
    0	     5	 18464	       console-window-host (Windows internal process)
    0	     6	 14452	     winpty-process
    0	     9	 12120	       console-window-host (Windows internal process)
    0	   323	 24604	       C:\WINDOWS\SysWow64\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& 'C:\Users\mlparker\.vscode\extensions\ms-vscode.powershell-1.10.1\modules\PowerShellEditorServices\Start-EditorServices.ps1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.10.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\mlparker\.vscode\extensions\ms-vscode.powershell-1.10.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\mlparker\.vscode\extensions\ms-vscode.powershell-1.10.1\logs\1544535480-bf4a00a8-d87d-43c0-8d5e-180348539cd91544535341880\EditorServices.log' -SessionDetailsPath 'C:\Users\mlparker\.vscode\extensions\ms-vscode.powershell-1.10.1\sessions\PSES-VSCode-13788-950131' -FeatureFlags @()"
    0	     5	 20156	     winpty-process
    0	    62	 12260	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 21496	       console-window-host (Windows internal process)
    0	    55	 20888	     extensionHost
    0	    22	 25368	       "C:\Users\mlparker\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\mlparker\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=20888
    1	    71	  5656	   window (Issue Reporter)
    1	   195	 19736	   gpu-process
    0	    67	 24644	   window (Process Explorer)
    0	    83	 24724	   shared-process
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.25
vscode-hasher|dee|1.0.1
xml|Dot|2.3.2
gitlens|eam|9.0.3
vscode-pull-request-github|Git|0.2.3
gc-excelviewer|Gra|2.1.26
rest-client|hum|0.20.4
reg|ion|0.0.2
eml|lei|0.3.1
rainbow-csv|mec|0.8.0
mssql|ms-|1.4.0
PowerShell|ms-|1.10.1
material-icon-theme|PKi|3.6.1
code-settings-sync|Sha|3.2.3
sort-lines|Tyr|1.7.0

(2 theme extensions excluded)

</details>

**Comment by MattLParker** [comment]
Also tested with all extensions disabled except powershell.

Ran tests again and is present in insider as well
<details>
<summary>Version: 1.30.0-insider (user setup)</summary>
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74<br>
Date: 2018-12-11T14:37:43.130Z<br>
Electron: 2.0.12<br>
Chrome: 61.0.3163.100<br>
Node.js: 8.9.3<br>
V8: 6.1.534.41<br>
OS: Windows_NT x64 10.0.17763<br>
</details>

**Comment by Tyriar** [comment]
Please report against https://github.com/PowerShell/vscode-powershell
