### ISSUE TITLE
DevTools - Performance tab doesn't work on reload anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#64800]
This surely is a regression from adopting latest electron

* open dev tools, select Performance
* start recording
* hit cmd+r to reload
* after ~5 seconds stop profiling
* 💩 the profile is useless, doesn't show layout, JS info...

<img width="817" alt="screenshot 2018-12-11 at 13 15 45" src="https://user-images.githubusercontent.com/1794099/49800075-e6695180-fd46-11e8-8886-8aae4836ce18.png">

**Comment by bpasero** [comment]
Upstream: https://github.com/electron/electron/issues/14763

**Comment by bpasero** [comment]
I would not put this into the league of blocking us from shipping the update since this is a developer thing and its fixed in Electron 4. Removing the blocker label.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
