### ISSUE TITLE
Let specify language for unsaved/temporary files, and let plugins work for the language.

### ISSUE THREAD

**Issue by fishingry** [Microsoft/vscode#64809]
Especially for JSON formats, most of them are temporary files, I don't want to save any of them, but I have to use some of VS code features to read it, like document format, which is most used for me.

in NotePad ++ , users could specify language for temporary contents. the feature should also provided by Visual Studio Code. since I get used to open vs code more often than instead of opening npp .

**Comment by mjbvz** [comment]
Try setting: `"files.defaultLanguage"`, such as `"files.defaultLanguage": "markdown"`

**Comment by fishingry** [comment]
@mjbvz  Thanks a lot.

I found correct way:
https://stackoverflow.com/a/30776845/2568863

![image](https://user-images.githubusercontent.com/25354610/49829785-4f5bc400-fd5d-11e8-9fc7-484cc9517972.png)
