### ISSUE TITLE
Multiline file search "Copy all" in context menu does not copy multi-line statements

### ISSUE THREAD

**Issue by Larkenx** [Microsoft/vscode#64819]
- VSCode Version: Version 1.29.1 (1.29.1)
- OS Version: macOS Mojave Version 10.14

Steps to Reproduce:

1. Perform a multi-line search with a regular expression.
2. Right-click, "copy all" on a search result.
3. Only the first line that matched is copied in the code results

Example Regular Expression and Test Case:
```regex
/.*<artifactId>atwork-core-utilities.*</artifactId>.*[\n\s]+.*<version>.*</version>/
```
```xml
        <dependency>
            <groupId>com.example.foo</groupId>
            <artifactId>atwork-core-utilities-jar</artifactId>
            <version>${atWork-core}</version>
        </dependency>
```
The multiline expression matches in individual find statements
![image](https://user-images.githubusercontent.com/12945799/49825048-79a78480-fd51-11e8-8dbe-1ee87907597d.png)

Whenever I use the copy all context menu action, it only copies from the first matching line
![image](https://user-images.githubusercontent.com/12945799/49825155-bc695c80-fd51-11e8-988f-f85ff6d6fd3d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you suggest how the multiline text should be copied? Should I just show all the text after the column/line:

```
/file/path.xml
  10,12: this is line 1
this is line 2
line 3
```

or a line number with every line somehow:

```
/file/path.xml
  10,12: this is line 1
  11:    this is line 2
  12:    line 3
```

**Comment by Larkenx** [comment]
I'm thinking it probably makes more sense to keep the line number so that it is consistent with the existing copy all functionality. Keeping the line number will make it obvious to the user that the regular expression result does indeed take up multiple lines, whereas without that it might be obfuscated otherwise. Thanks for the quick response

**Comment by Larkenx** [comment]
Here's another scenario too; consider I have a regular expression spanning multiple lines, but only have capture groups on every odd line. I only want to copy lines and paste them if they're in the capture group of my regular expression (I was attempting this):
```regex
/.*(?<artifactId>atwork-core-utilities).*</artifactId>.*[\n\s]+.*<version>(?.*)</version>/
```
```xml
        <dependency>
            <groupId>com.example.foo</groupId>
            <artifactId>atwork-core-utilities-jar</artifactId> <!-- keep this -->
            <scope>test</scope> <! -- exclude this -->
            <classifier>tests</classifier>
            <version>${atWork-core}</version> <!-- keep this -->
        </dependency>
```
