### ISSUE TITLE
Cannot right click to copy error if there is a quick fix available 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64820]
Issue Type: <b>Bug</b>

**Repo**
1. In a ts file:

```ts
class Foo {}

Foo();
```

1. Open errors panel
1. Try to right click on the error to copy it (without selecting the error in the list)

**Bug**
Only the quick fixes show in the context menu:

![screen shot 2018-12-11 at 11 55 35 am](https://user-images.githubusercontent.com/12821956/49826430-caac7e00-fd3b-11e8-8a24-b02aee8c8d94.png)

VS Code version: Code - Insiders 1.30.0-insider (241923763dbeaf3b64443187e935d55b29f6125d, 2018-12-07T22:24:17.051Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|-psn_0_11606801|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by sandy081** [comment]
@mjbvz I cannot reproduce this, are there specific steps I have to follow to see this?
