### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#64821]
- VSCode Version: 1.30.0-insider
- OS Version: macOS 10.13.3

This happens sporadically but consistently in my project.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed near the end?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
