### ISSUE TITLE
Implement UI optimization options

### ISSUE THREAD

**Issue by optomux** [Microsoft/vscode#64822]
Implement UI optimizations:

- Option to disable all UI animations.
- Option to disable all UI shadows.
- Other stuff to speed up the UI.

**Comment by misolori** [comment]
> Option to disable all UI animations.

The app already has little to no animations so I don't see this being worth the investment unless we add additional animations.

> Option to disable all UI shadows

Can you provide an example?

> Other stuff to speed up the UI

Please be as specific as possible

**Comment by optomux** [comment]
Press CTRL + SHIFT + P to see what I mean.

**Comment by misolori** [comment]
@optomux you can remove that via the `widget.shadow` theme token. Add this to your user settings to see it:

```json
"workbench.colorCustomizations": {
    "widget.shadow": "#00000000"
}
```

<img width="702" alt="image" src="https://user-images.githubusercontent.com/35271042/49849281-a083ac00-fd8d-11e8-913b-a91d883de4aa.png">

**Comment by optomux** [comment]
Chrome Dev tools shows there are a bunch of animations in the UI. 
Again how to disable them?

**Comment by misolori** [comment]
Can you be specific about which animations you are referring to? And there is currently no way to disable animations.
