### ISSUE TITLE
Run button on Touchbar does not start .Net Core application

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#64828]
Issue Type: <b>Bug</b>

Tapping the "run" button with a ASP.Net core application open does not start up the application. The debugging toolbar is displayed along with a dropdown menu of "Select environment". Choosing ".Net Core" hides the debug toolbar and does not launch the application.

Launching the application from within the Debug panel (with the "Run" icon at the top) correctly starts the application.

VS Code version: Code - Insiders 1.30.0-insider (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T14:30:16.007Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (6.25GB free)|
|Process Argv|-psn_0_2007530|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
githistory|don|0.4.4
tslint|eg2|1.0.40
auto-rename-tag|for|0.0.15
Angular2|joh|7.0.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.0

(3 theme extensions excluded)

</details>

<img width="812" alt="image" src="https://user-images.githubusercontent.com/13488/49834712-16c2e700-fd6b-11e8-9831-4a495a0daf84.png">

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/64450
