### ISSUE TITLE
Unable to write into newly opened Untitled file

### ISSUE THREAD

**Issue by TheLifeIsYours** [Microsoft/vscode#64825]
Issue Type: <b>Bug</b>

A vscode window with no workspace folder selected
Open a new document with ctrl+n
Try typing, and nothing is entered.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.45GB (15.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
p5js-snippets|aci|0.0.6
vscode-eslint|dba|1.7.0
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.7
super-replace|jeb|0.3.1
vscode-sshfs|Kel|1.11.2
sftp|lix|1.8.1
MagicPython|mag|1.1.0
vscode-apache|mrm|1.1.1
python|ms-|2018.11.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.1
heroku-command|pko|0.0.8
platformio-ide|pla|1.5.0
LiveServer|rit|5.3.1
vscode-icons|rob|7.28.0
ftp-kr|rua|1.3.16
glassit|s-n|0.1.3
language-stylus|sys|1.10.0
python|tht|0.2.3
unity-debug|Uni|2.6.6
vscode-arduino|vsc|0.2.24
vscode-wakatime|Wak|1.2.4
quokka-vscode|Wal|1.0.172
JavaScriptSnippets|xab|1.7.1
unity-snippets|Ycl|0.1.2

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
