### ISSUE TITLE
[css] place-self not a recognized css property

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#64835]
Issue Type: <b>Bug</b>

**Repo**
1. For the css:

```css
a {
	place-self: center;
}
```

**Bug**
`place-self` is considered an unknown property. It is valid according to mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/place-self

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

</details>

**Comment by rchrdnsh** [comment]
when will this be fixed? it's been a loooooooong time...

**Comment by connorshea** [comment]
Needs a new mdn/data release, which hasn't happened since December. @octref maybe we should ping a friend at Mozilla? :)
