### ISSUE TITLE
Logging to Debug Console via 'debug' package broken after a call to console.log

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/vscode#64840]
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

When running my node app in the vscode debugger, log statements made via the [debug npm package](https://www.npmjs.com/package/debug) successfully print to the Debug Console, up until the moment my app makes a call to `console.log()`. After this call, no further log statements made via `debug` will show up in the Debug Console. They will successfully print when I run my app from the command line, indicating this is an issue with vscode.

Steps to Reproduce:
```js
const debug = require('debug')('app');
debug.enabled = true;

debug('debug message 1'); // <-- Displays in Debug Console
console.log('console message'); // <-- Displays in Debug Console
debug('debug message 2'); // <-- Does not display in Debug Console. Does show up in shell.
```
Repro project here: https://github.com/eanders-MS/vscode-console-bug

**Comment by roblourens** [comment]
The debug module writes directly to stderr, so it is invisible to the debugger. But the node debug extension shows all stderr output until the first normal log message it receives (in this case, from console.log), because that early stderr output may be startup errors. But that's why the first one shows up.

**Comment by roblourens** [comment]
Also you can set `"outputCapture": "std"` in your launch config to get all output from stdout/stderr.

**Comment by roblourens** [comment]
Or configure `debug` to log with console APIs instead: https://www.npmjs.com/package/debug#output-streams

**Comment by eanders-MS** [comment]
Oh interesting. Thank you for the clarification and the workaround suggestions.
