### ISSUE TITLE
Adding verbatim Symbol

### ISSUE THREAD

**Issue by Karlito88** [Microsoft/vscode#64857]
Is there a possibility to add a verbatim symbol/identifier like in c# (@) that a path to a executable can be written without "\\\\" ?

**Example in task.json:**
Without verbatim symbol:

![without](https://user-images.githubusercontent.com/24226141/49862157-d3658880-fdfd-11e8-8440-5504a258e831.png)

With verbatim symbol:

![with](https://user-images.githubusercontent.com/24226141/49862162-d791a600-fdfd-11e8-9c32-82f19bda908e.png)

Link for verbatim symbol in c#: [@ Verbatim](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim)

**Comment by mjbvz** [comment]
We use standard JSON for these files. Adding this symbol would make these files no longer be valid json
