### ISSUE TITLE
Typescript autocomplete crash over time

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode#6485]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Create a  `TypeScript` project with the following structure : 
`tsconfig.json`
`app/`
`app/application.ts`
`app/framework/`
`app/framework/application.ts (included in application.ts)`
`app/framework/some other typescripts files (included in framework/application.ts)`
`app/appNameHere/`
`app/appNameHere/application.ts (included in application.ts)`
`app/appNameHere/some other typescripts files (included in appNameHere/application.ts)`

 So basically : 
 - `app/application.ts` will only contain references to `framework/application.ts` and `appNameHere/application.ts`.

 - `app/framework/application.ts` will only contain references to files from `framework` folder.
 - `app/appNameHere/application.ts` will only contain references to files from `appNameHere` folder.

2. Create a `tsconfig.json` as follow : 
`{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "removeComments": true,
        "outFile": "application.js",
        "sourceMap": true,
        "noImplicitAny": true
    },
    "files": [
        "app/application.ts"
    ]
}`
3. Add some TS files in both directory and play with it, try using intellisense of a class from another file

4. Up at some point, TypeScript intellisense seems to crash and to get it again, we need to restart vscode

The Intellisense is crashing a lot in one day on my side with that settings at my job, it will say it doesn't know what is a class that should be defined, until you restart vscode ...

If you need more informations, I'll be glad to offer them. However, I am not in the ability to share my projet as it is confidential files from my job.

**Comment by MLefebvreICO** [comment]
Forgot to mentionned : 
My tsc is version 1.8.9

**Comment by dbaeumer** [comment]
@MLefebvreICO could you please enable TS logging. This can be done by adding the following setting:
```json
{
    "typescript.tsserver.trace": "messages"
}
```
Then open the output window and switch to the TypeScript channel. Could you provide me with the log data printed there. That would help to understand why intellisense stops working

**Comment by MLefebvreICO** [comment]
I just added it to my `settings.json`file. However, I do not have an option TypeScript in the dropdown of the output window even after restarting vscode. 

Am I missing something here ?

**Comment by MLefebvreICO** [comment]
After playing with my files and everything, it finally appeared.

For now, here's the output, but it didn't crash in that part. Do you prefer that I send one once it stopped working ?

As for now : http://pastebin.com/raw/DZwegjDX

**Comment by dbaeumer** [comment]
@MLefebvreICO yes, I prefer having a trace when it stopped working since the trace will have information why the request failed.

**Comment by MLefebvreICO** [comment]
I have not come across the bug today.
Note that when I did this issue I did check if I had the latest TypeScript version and updated it to `1.8.10`.

Maybe that fixed it ? I'll come back to you tomorrow at the end of the day to tell you if it ocurred or it seems fixed.

`TypeScript` release note : 
> This release fixes an issue in React 15.0 and later by removing a dependency on an internal React API when emitting JSX spread attributes. As a result, TypeScript now emits its own standalone helper function for spread attributes.

**Comment by MLefebvreICO** [comment]
@dbaeumer I have come across an error. This is not the errors I normally get (they seems gone with the new typescript version).

The code that got an error on is : 
`this.someAngularFactory.someFunction(param1, param2).then...` 

Giving me this error on mouse hover : `Supplied parameters do not match any signature of call target`. However, the function name is perfectly fine, same for the parameters number and their types.

Restarting vscode fixed the issue ...

Here is the trace (it is big, but just check at the end) : http://pastebin.com/raw/dXqXQdsD

**Comment by MLefebvreICO** [comment]
I got the error I was talking previously. However, it doesn't give an error in the trace, it only do : 
`Sending request: quickinfo (923). Response expected: yes. Current queue length: 0`
`Response received: quickinfo (923). Request took 2 ms. Success: true`

But it tells me `Cannot find namespace 'angular'` or `Cannot find namespace 'framework'` or `Cannot find namespace 'angular'` ... all of them exists but returns the output that I wrote without error.

All of them exists and even restarting vscode doesn't seems to work for now ...

**Comment by MLefebvreICO** [comment]
Just go an error I normally got when fetching from another branch on git. Seems like git operations screw up the TypeScript intellisense.

I just lost all my references to `angular` and other classes I use.

The only trace that it gives is : 
`Sending request: quickinfo (568). Response expected: yes. Current queue length: 0`
`Response received: quickinfo (568). Request took 2 ms. Success: false . Message: No content available.`

**Comment by dbaeumer** [comment]
@MLefebvreICO thanks a lot for the trace. The trace shows that the tsserver returns failed responses due to a length < 1 violation. Moving to TS team.

**Comment by dbaeumer** [comment]
I also opened https://github.com/Microsoft/TypeScript/issues/8716 to make tracing this more easy.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8717
