### ISSUE TITLE
html代码提示老是莫名失效

### ISSUE THREAD

**Issue by 1032740078** [Microsoft/vscode#64861]
Issue Type: <b>Bug</b>

html代码提示老是莫名失效，vscode不定时的复现这个bug

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eclipse-keybindings|alp|0.10.0
vscode-eslint|dba|1.7.0
vscode-html-css|ecm|0.2.0
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
quickstart|lol|0.1.0
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.11.0
vetur|oct|0.14.3
LiveServer|rit|5.3.1
vue-vscode-snippets|sdr|1.3.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by octref** [comment]
Please report issue in English, explain your issue (with gif or video) and provide a reproducible case.
