### ISSUE TITLE
A re-used terminal doesn't always fire an onExit event.

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#64865]
Related to #54397.

@EricJizbaMSFTcreated an example that shows this very nicely: https://github.com/EricJizbaMSFT/helloworldext
Run the debug launch config to repro. Once the second task in the prelaunch starts, run the `Terminate Task` command. 
Expected: There is a terminal onExit event
Actual: Since the terminal was re-used and some clean up was missed, it thinks that this second call to TerminalInstance `_onProcessExit` is spurious and does not fire the event or do any of the `_onProcessExit` tear down.

The clean up that's missed is in `reuseTerminal`:

		if (this._isExiting && this._shellLaunchConfig.waitOnExit) {
			this._xterm.setOption('disableStdin', false);
			this._isExiting = false;
		}

because `this._shellLaunchConfig.waitOnExit` is `false`. In this case, `waitOnExit` is false because the task terminal reveal is set to Never, and the task is a background task. This is the info for the *new* task, not the old one. It looks like an ordering issue.

**Comment by chrmarti** [comment]
@alexr00 Not sure how to verify. I don't see a second task in the prelaunch.

**Comment by alexr00** [comment]
Verifying #54397 will also verify this one.
