### ISSUE TITLE
List all references from multi-root workspaces

### ISSUE THREAD

**Issue by roms51** [Microsoft/vscode#64867]
Hi
I develop multiple typescript projects depending each other
List all references don't work in my case.

- VSCode Version: 1.29.1
- OS Version: Macosx 10.14.1

Context:
1. workspace folder "library" (typescript project)
2. workspace folder "application1" (typescript project depending on "library")
3. workspace folder "application2" (typescript project depending on "library")

Steps to Reproduce:
1. Right click on a "library" class name
2. Select "List all references"

Result:
All references from "library" and "application1" are shown

Expected result:
All references from "library" and "application1" and "application2" should be shown

**Comment by roms51** [comment]
Problem is same with VSCode Version: 1.30.2

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/30823
