### ISSUE TITLE
setting JSON schema for file named manifest.json not working

### ISSUE THREAD

**Issue by kevincam3** [Microsoft/vscode#64868]
- VSCode Version: 1.29.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Edit the User settings
2. Copy the "json.schemas" over to the User settings
3. Add the following:
"json.schemas": [
        {
            "fileMatch": [
                "/manifest.json"
            ],
            "url": "http://json.schemastore.org/chrome-manifest"
        }
    ]
4. create the file manifest.json in the root of the project

Code complete for key "icons" says the value should be an array but it's defined as an object in the schema definition.

Does this issue occur when all extensions are disabled?: Yes

Attached is my manifest file. This is for building Chrome Extensions
[manifest.zip](https://github.com/Microsoft/vscode/files/2671705/manifest.zip)

**Comment by octref** [comment]
It's working for me though:

![image](https://user-images.githubusercontent.com/4033249/50243783-f6a2b180-0382-11e9-8649-cb531cc49d6b.png)

After completion:

![image](https://user-images.githubusercontent.com/4033249/50243813-0a4e1800-0383-11e9-920a-9882b136ebfb.png)

No errors on your file:

![image](https://user-images.githubusercontent.com/4033249/50243916-5a2cdf00-0383-11e9-900a-627234a67d33.png)

**Comment by kevincam3** [comment]
It's not working for you. Because the value for icons in your screenshot is not an array, it's an object.

**Comment by kevincam3** [comment]
It's actually working now since I upgraded to version 1.30.1 so I'm good, thanks for checking on this.
