### ISSUE TITLE
Add option to disable intelligent multi-line paste

### ISSUE THREAD

**Issue by pjcevans** [microsoft/vscode#64862]
It would be great to have an option to disable the intelligent multi-line paste feature detailed in this issue: https://github.com/Microsoft/vscode/issues/46440

It's a useful feature but on most projects I prefer all text selected to be pasted at all multi-line cursors.

**Comment by pjcevans** [comment]
Indeed @vscodebot! https://github.com/Microsoft/vscode/issues/62974 has the same (unresolved) issue, they expect the default behaviour to be for the whole block of selected text to be pasted at every multi-line cursor.

**Comment by alexandrudima** [comment]
Let's track in #80624
