### ISSUE TITLE
shows menu bar at the bottom occasionlly

### ISSUE THREAD

**Issue by liudaoping** [Microsoft/vscode#64871]
Issue Type: <b>Bug</b>

it will show a menu bar at the bottom occasionlly when switch to debug console

![image](https://user-images.githubusercontent.com/19853499/49868722-3d574f80-fe49-11e8-9f21-a6b4c01fae78.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sbatten** [comment]
@liudaoping can you share repro steps and try on the latest release 1.30? Specifically, what were you doing before this occurred? Did you use the mouse or keyboard to switch to the debug console? Does it exit the state? Is so how?

**Comment by liudaoping** [comment]
@sbatten 
I update to the latest release 1.30,and the issue still occurs. and the steps to repro as below
1. click "output" tab
2. switch to debug console
3. click the area of debug console, and it shows the menu bar
![image](https://user-images.githubusercontent.com/19853499/49909461-040af800-feba-11e8-8a05-25db73903bd5.png)

**Comment by sbatten** [comment]
@liudaoping 
I am unable to reproduce this with the steps:
1. Click output
2. Click debug console
3. Click in debug console area

Is this the only graphical issue you see when this happens?

**Comment by liudaoping** [comment]
@sbatten 
> Is this the only graphical issue you see when this happens?
yes

**Comment by liudaoping** [comment]
@sbatten 
I found other issues, check below images:
![image](https://user-images.githubusercontent.com/19853499/49910694-a75e0c00-febe-11e8-91a4-bc1bbc3f0943.png)
![image](https://user-images.githubusercontent.com/19853499/49910701-acbb5680-febe-11e8-8877-e2eacd786f07.png)
![image](https://user-images.githubusercontent.com/19853499/49910710-b218a100-febe-11e8-8a64-c0144f264230.png)

**Comment by sbatten** [comment]
@bpasero electron?

**Comment by liudaoping** [comment]
@sbatten 
one more similar issue：
1. start vs code
2. select menu：view -> output
![image](https://user-images.githubusercontent.com/19853499/49911726-68ca5080-fec2-11e8-9912-fa2c8b95bed7.png)
3. click welcome area，and shows something like below
![image](https://user-images.githubusercontent.com/19853499/49911805-be066200-fec2-11e8-87ac-5c924dfc4458.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by liudaoping** [comment]
@bpasero 
I have downloaded and tried it, and it works fine! Above issues doesn't occur!
So, how can i fix these issues?

**Comment by bpasero** [comment]
@liudaoping you can switch to our nightly insider builds until we released this fix to stable (end of January):  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by liudaoping** [comment]
@bpasero 
OK, thx
