### ISSUE TITLE
Using Qwertz Keyboard Ctrl + doesn't work 

### ISSUE THREAD

**Issue by smolinari** [Microsoft/vscode#64874]
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Press Ctrl + (or in German Strg +) keys. 
2. The screen zooms in, instead of the Settings page opening up. 

I'm not 100% positive it has to do with the Qwertz Keyboard. 

Workaround: I've now reset the Keyboard Shortcut and it is working. I'll test this evening on my Win 10 Pro computer at home. 

Scott

**Comment by alexandrudima** [comment]
@smolinari What OS are you using? What keyboard layout are you using? What key are you pressing? The key located to the left of backspace?

**Comment by smolinari** [comment]
Windows 1 Pro is the OS. Keyboard layout is the German Qwertz. 

Pressing Ctrl and +. But it isn't located next to the backspace key on a Qwertz keyboard. It's just below it.

Scott

**Comment by smolinari** [comment]
![image](https://user-images.githubusercontent.com/3314957/50099930-86c7e600-021f-11e9-8b87-74a19d179354.png)

scott

**Comment by alexandrudima** [comment]
@smolinari This is expected. <kbd>Strg</kbd>+<kbd>+</kbd> is bound out of the box to zoom in. Here I have an instance running without any keybinding customizations with the German keyboard layout:

![64874](https://user-images.githubusercontent.com/5047891/50244382-1a401900-03d0-11e9-87ff-318ba434b17a.gif)

**Comment by smolinari** [comment]
Uh. Oh. My bad. I saw this in the menu.....

![image](https://user-images.githubusercontent.com/3314957/50245265-51172e80-03d2-11e9-8081-7d1efe6f60b8.png)

...and thought the command was "ctrl" and "+". I missed the comma there. 😊 

Nevermind. Sorry for wasting your time.

Scott
