### ISSUE TITLE
Display current value of a property in settings.json

### ISSUE THREAD

**Issue by depascalis** [microsoft/vscode#64877]
When typing a property in a json settings file, it would be helpful if the suggestion list displayed the current and default value at the top of the list.

**Example:**
The first object in Default Keybindings is
```
{
  "key": "escape escape",
  "command": "workbench.action.exitZenMode",
  "when": "inZenMode"
}
```
If I edit keybindings.json and start typing `{ "key": "escape escape", "command": ""`
The suggestion list should display the current and default value for the key `"command"` which in this case are the same `"workbench.action.exitZenMode"`. The list then continues with other possible values.

**Another example in settings.json:**
```
  "workbench.colorCustomizations": {
    "activityBar.background": ""
```
In this case the suggestion list should display first the default value from the default theme and second, the current value if applied from another theme.
![vscode_sgstlst_03](https://user-images.githubusercontent.com/33980634/49873551-70371e80-fe1c-11e8-94bc-7abf469e67b1.png)

At the moment the suggestion list displays `#ff0000` for all color settings.
![vscode_sgstlst_01](https://user-images.githubusercontent.com/33980634/49867248-2d6c4b00-fe0a-11e8-8559-7fdf819c8121.jpg)

If a property value exists in Default User Settings, the correct default value is displayed in the suggestion list e.g `"editor.tabsize: "` shows the value `"4"`
![vscode_sgstlst_02](https://user-images.githubusercontent.com/33980634/49867294-4c6add00-fe0a-11e8-8ee3-1ab1475dccaf.jpg)

**Comment by roblourens** [comment]
I think the keybindings case is better suited for the UI which already essentially does this.

The theme case specifically feels useful. But it's tough to generalize, some settings can have multiple "current values", and the current value for complex settings is hard to display as a suggestion.

**Comment by depascalis** [comment]
@roblourens 
Yes the keybindings case wasn't the best example. 

I'm trying to figure out how something could have multiple current values, can you point to such a value?

I just thought this could be handy in general, but the themes example is however where I was missing this feature from the beginning, here to be more precise:
`"workbench.colorCustomizations": {}`
`"editor.tokenColorCustomizations": {}`


I was also thinking about what default value to show if your inside a theme
```
"editor.tokenColorCustomizations": {
    "comments": "",      // Show VSCode default
    "[Default Dark+]": {
        "comments": ""  // Show theme default
    }
}
```

**Comment by roblourens** [comment]
> I'm trying to figure out how something could have multiple current values, can you point to such a value?

If something is configured different in multiple workspace folders, or in different languages. There is not one value, it's contextual.

I think our investment for new UI features like will mainly be in the settings GUI but I'll leave this open for now.

**Comment by roblourens** [comment]
Default value is included, "current" value is hard to define.
