### ISSUE TITLE
Choose a different icon color

### ISSUE THREAD

**Issue by sebastiangreco** [Microsoft/vscode#64879]
Issue Type: <b>Feature Request</b>

Hi, it is a minor thing but I think would be good to have a different color icon for visual studio code in order to make it easy to distinguish them. I dont really know if they are already different, but as I'm color blind it's the same for me. for example if vs2017 icon is blue vs code should be green.
Thanks

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
You can already customize the VS Code icon using built-in operating system functionality. See https://github.com/dhanishgajjar/vscode-icons for example
