### ISSUE TITLE
typescript: send project name as argument for getSupportedCodeFixes

### ISSUE THREAD

**Issue by ajafff** [Microsoft/vscode#64872]
Blocks https://github.com/Microsoft/TypeScript/issues/28966

To enable TypeScript LanguageService plugins to intercept `getSupportedCodeFixes`, TypeScript needs to know which project the request belongs to, to forward to the correct LanguageService.

I don't know about the specific implementation details, but a parameter of type `ts.server.protocol.FileRequestArgs` should work.

Maybe VSCode also needs to call `getSupportedCodeFixes` for each project if it doesn't do that already.

**Comment by mjbvz** [comment]
Closing the VS Code side of this issue as there's nothing we can do on our side. If TS makes any changes to the server API, let me know and we'll adopt it
