### ISSUE TITLE
Support terminal links for live share guests

### ISSUE THREAD

**Issue by jberry4** [microsoft/vscode#64881]
When using vscode normally and I run my tests I receive the stack trace of a failing test and the trace appears as a clickable link in the terminal. On holding Ctrl and then clicking, the link takes you to the test file where the failed test is.

This doesn't happen in vscode live share. Are you able to add this feature?

**Comment by Tyriar** [comment]
Please report to live share if there isn't one yet, they could make a proposal to us.
