### ISSUE TITLE
Open editor list renders blank

### ISSUE THREAD

**Issue by spion** [Microsoft/vscode#64883]
Issue Type: <b>Bug</b>

The open editors list is blank. It grows with the number of open editors, but the text inside doesn't render.

![image](https://user-images.githubusercontent.com/502412/49874972-c786c000-fe17-11e8-9bda-68aa7225cfc7.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.16GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-FAKE|Ion|1.2.3
json-to-ts|Mar|1.5.5
vscode-hie-server|ala|0.0.24
vscode-sqlite|ale|0.3.2
markdown-mermaid|bie|1.0.0
solargraph|cas|0.18.0
scala|dal|0.0.5
graphviz-preview|EFa|1.3.0
prettier-vscode|esb|1.7.2
haml|gro|0.0.2
ruby-linter|hoo|1.0.0
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.5.0
theme-dark-plus-contrast|k3a|0.1.101
haml|kar|1.1.0
howdoi|kub|0.1.3
xml-format|mik|1.0.1
ruby-rubocop|mis|0.7.1
python|ms-|2018.11.0
azure-account|ms-|0.6.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1013
ide-purescript|nwo|0.20.0
language-purescript|nwo|0.2.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.4.0
seti-icons|qin|0.1.3
ruby|reb|0.21.0
postcss|ric|2.0.0
code-settings-sync|Sha|3.2.3
typescript-workspace-langserv-extension|spi|1.0.0
dot|Ste|0.0.1
t4-support|zbe|0.4.2

(6 theme extensions excluded)

</details>

**Comment by spion** [comment]
just a note that vscode bot is wrong, this isn't integrated-terminal related

**Comment by isidorn** [comment]
@spion can you reproduce this with latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by spion** [comment]
Actually I'm unable to reproduce it with 1.29.1 either - it seems to happen very rarely.
