### ISSUE TITLE
Install extension of different versions into same path

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#6488]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Enterprise x64

Steps to Reproduce:

1. Install an old version of some extension, like v1.
2. When the extension is updated, update the extension, this  new version like v2, will be installed in a different path.

In this design, it seems hard for extension developer to put necessary files(e.g., a cache/history file needs to persisted during extension usage) into the extension path, since in new version, the file is missing, needs to be regenerated.

So if we could have multiple versions of same extension have same path, in that case the cache/history file can be used when extension is updated.

I am not sure if this request is reasonable, or I just should put this kind of files to a fixed place on machine :blush:

**Comment by rebornix** [comment]
:+1: I love this idea. Currently we don't have real update for extensions, it's just a combination of uninstallation and new installation.

A possible workaround I can come up with for now is storing data to cloud, just like how we handle trace data.

**Comment by joaomoreno** [comment]
Won't happen. Different versions are in different paths for multiple reasons.

If you need a shared space, feel free to create a folder in a place the user owns, eg: `~/.vscode-myextension`.
