### ISSUE TITLE
During Ctrl+multiple file selection, file contents should be shown for every recent click

### ISSUE THREAD

**Issue by 10manjunath** [Microsoft/vscode#64885]
Issue Type: <b>Feature Request</b>

While working on a large number of version controlled files, i often like to revert the changes to multiple files.

The way i do it is to click on the Source Control tab on the left, and then hold down the control button, and select whichever file i want. Once i finish my multi-file selection, i revert my changes. However, during this file-by-file selection while holding down the ctrl button, i would like to see the actual file contents displayed on the right, so that i won't accidentally revert a file that is unintended to be.

Here are 2 GIF's to explain.

1) Just clicking whichever file you want normally.

![justclicking](https://user-images.githubusercontent.com/7700267/49876528-93000d80-fdf1-11e8-837b-a083f0c9447f.gif)

2) Holding down Ctrl button and then selecting files. **Notice, the end user will not be able to see the contents of the file, so there is a possibility that, a wrong file might be reverted accidentally**

![ctrlselect](https://user-images.githubusercontent.com/7700267/49876548-9bf0df00-fdf1-11e8-8358-e20689e61c26.gif)

> **Expected fix: while holding down Ctrl button and during multiple file selection, the file should be displayed on the right**

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.14393

**Comment by joaomoreno** [comment]
Two ways to achieve this:

1. Click the `Open File` inline action to see each file. This will not clear the current selection.
2. Right-click each file and run `Open Changes`. This will also not clear the current selection.

**Comment by 10manjunath** [comment]
works for now. Thank you
