### ISSUE TITLE
tree - have `useAltAsMultipleSelectionModifier`

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64889]
re #64727

Today workbench tree have `useAltAsMultipleSelectionModifier` which is used by the explorer, open editors view, and outline and we need some sort of equivalent for the new tree world

**Comment by jrieken** [comment]
cc @isidorn

**Comment by jrieken** [comment]
> switching the setting does alter its behavior.

You that it reflects that in the corresponding event?

**Comment by jrieken** [comment]
Today I use it like this: https://github.com/Microsoft/vscode/blob/850c03010d475b0b14802ac8811dd1e716846e23/src/vs/workbench/parts/outline/electron-browser/outlinePanel.ts#L593-L613

**Comment by joaomoreno** [comment]
Oh I wasn't aware these workbench lists and trees re-expose that stuff... pushing exposition of that boolean.
