### ISSUE TITLE
tree - support expandAll or equivalent

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64887]
re #64727

When filtering or find items in the outline all matches are highlighted and revealed. See https://github.com/Microsoft/vscode/blob/ca773cb3f27afd57b0bd790d2e2f33f261a31030/src/vs/workbench/parts/outline/electron-browser/outlinePanel.ts#L570-L577

There is no equivalent in the new tree, except for calling `expand` in a loop. After https://github.com/Microsoft/vscode/pull/64807#issuecomment-446542971 I am not sure anymore that's OK to do

**Comment by joaomoreno** [comment]
We can easily do this in the ObjectTree now. I can even add in the <kbd>Alt</kbd> clicking that would do this per subtree.

**Comment by joaomoreno** [comment]
Alright did a pretty big revamp of the collapse feature set in the tree:

- Introduced `expandAll`
- Introduced a `recursive` flag for `setCollapsed` and `toggleCollapsed`
- Holding <kbd>Alt</kbd> while expanding/collapsing a node via mouse click or <kbd>Spacebar</kbd> will now perform the action recursively, just like in native tree widgets (finally we get this!).

Here's the current full extent of collapse related methods of the tree:

```ts
collapse(location: TRef, recursive: boolean = false): boolean;
expand(location: TRef, recursive: boolean = false): boolean;
toggleCollapsed(location: TRef, recursive: boolean = false): boolean;
expandAll(): void;
collapseAll(): void;
isCollapsible(location: TRef): boolean;
isCollapsed(location: TRef): boolean;
```

cc @isidorn @roblourens

**Comment by isidorn** [comment]
@joaomoreno any chance that you support `expandAll(elements?: T[])`
Currently I have to do the following
https://github.com/Microsoft/vscode/blob/ab0b87329f1e5c89f1df6e50c5a4b7e7a37006dc/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L970

Also that expand and others throw errors when an element is not there is forcing me to use these ugly ignoreErrors approach.
