### ISSUE TITLE
Selected row on an unfocused watch tree should not be monochromatic

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#64890]
I see why we set a single color when you select a row in a focused watch tree:

![image](https://user-images.githubusercontent.com/22350/49877843-9792e900-fe26-11e8-80cb-954aac3a855a.png)

But once it goes unfocused, that single color remains and it just looks weird. in the following picture, `hello` should be colored purple:

![image](https://user-images.githubusercontent.com/22350/49877814-82b65580-fe26-11e8-93cb-4127ce2a6b38.png)

**Comment by isidorn** [comment]
Good catch
