### ISSUE TITLE
Settings - Search: Use (Global) Ignore Files -- not working as expected

### ISSUE THREAD

**Issue by notes-jj** [Microsoft/vscode#64895]
- VSCode Version:
  - 1.29.1
  - 1.30.0-insider
- OS Version:
  - Windows 7 (patch level 2018-12-12)

Steps to Reproduce:

1. Launch `code --disable-extensions`
2. Open project in VS Code with "Open Folder"
3. Create Folder tmp inside project
4. Create Text File inside tmp with unique String in Content
5. Add `tmp/` to `.gitignore` File in project root folder
6. Use "Find in Files" or `Shift-Cntr-f`
7. Search for unique String
8. No File will be found (1.29.1)
9. File - Preferences - Setting
  No Matter how you set `Search: Use Global Ignore Files` and/or `Search: Use Ignore Files` the file will **never** be found

Addendum for `1.30.0-insider`

- In `1.30.0-insider` the behavior is slightly different, but still the options don't work as expected:
  - The File is **always** found
  - No Matter how you set `Search: Use Global Ignore Files` and/or `Search: Use Ignore Files` the file will **always** be found

Does this issue occur when all extensions are disabled?: Yes

There is no Error showing up in Developer Console.

**Comment by roblourens** [comment]
Is it possible that you turned this off in 1.30 by toggling off the gear icon button in the "files to exclude" box?

If not please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by notes-jj** [comment]
Sorry, while testing with `User Settings` and `Workspace Settings` I got confused in testing the `1.30.0-insider` version.

Conclusion:
- It's a bug in `1.29.1`
- It is fixed in `1.30.0-insider`

**Comment by roblourens** [comment]
Thanks for following up!
