### ISSUE TITLE
Sort lines should sort entire file when there is no selection

### ISSUE THREAD

**Issue by massung** [microsoft/vscode#64893]
Issue Type: <b>Bug</b>

Using the built-in line sorting, I have a sample case where the lines sort incorrectly. Below is a list of lines sorted how VSCode sorted them (which is wrong). You can put them into Sublime Text and it will sort them correctly.

---

<details><summary>A list of lines</summary>

```
CADD_phred
CADD_raw_rankscore
CADD_raw
clinvar_clnsig
clinvar_golden_stars
clinvar_rs
clinvar_trait
DANN_rankscore
DANN_score
Eigen-PC-raw_rankscore
Eigen-PC-raw
Eigen-phred
Eigen-raw
FATHMM_converted_rankscore
FATHMM_pred
FATHMM_score
fathmm-MKL_coding_group
fathmm-MKL_coding_pred
fathmm-MKL_coding_rankscore
fathmm-MKL_coding_score
GenoCanyon_score_rankscore
GenoCanyon_score
GERP++_NR
GERP++_RS_rankscore
GERP++_RS
GM12878_confidence_value
GM12878_fitCons_score_rankscore
GM12878_fitCons_score
GTEx_V6_gene
GTEx_V6_tissue
H1-hESC_confidence_value
H1-hESC_fitCons_score_rankscore
H1-hESC_fitCons_score
HUVEC_confidence_value
HUVEC_fitCons_score_rankscore
HUVEC_fitCons_score
integrated_confidence_value
integrated_fitCons_score_rankscore
integrated_fitCons_score
Interpro_domain
LRT_converted_rankscore
LRT_Omega
LRT_pred
LRT_score
mcapv1.0
MetaLR_pred
MetaLR_rankscore
MetaLR_score
MetaSVM_pred
MetaSVM_rankscore
MetaSVM_score
MutationAssessor_pred
MutationAssessor_score_rankscore
MutationAssessor_score
MutationAssessor_UniprotID
MutationAssessor_variant
MutationTaster_AAE
MutationTaster_converted_rankscore
MutationTaster_model
MutationTaster_pred
MutationTaster_score
phastCons100way_vertebrate_rankscore
phastCons100way_vertebrate
phastCons20way_mammalian_rankscore
phastCons20way_mammalian
phyloP100way_vertebrate_rankscore
phyloP100way_vertebrate
phyloP20way_mammalian_rankscore
phyloP20way_mammalian
Polyphen2_HDIV_pred
Polyphen2_HDIV_rankscore
Polyphen2_HDIV_score
Polyphen2_HVAR_pred
Polyphen2_HVAR_rankscore
Polyphen2_HVAR_score
PROVEAN_converted_rankscore
PROVEAN_pred
PROVEAN_score
Reliability_index
SIFT_converted_rankscore
SIFT_pred
SIFT_score
SiPhy_29way_logOdds_rankscore
SiPhy_29way_logOdds
SiPhy_29way_pi
Transcript_id_VEST3
Transcript_var_VEST3
VEST3_rankscore
VEST3_score
```

</details>

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
kivy-vscode|Bat|0.5.0
jupyter|don|1.1.4
EditorConfig|Edi|0.12.5
vscode-scalafmt|gab|0.1.2
pig|Gan|2.2.0
cypher-query-language|jak|1.0.2
vscode-sbt-scala|lig|0.2.3
twig-language-2|mbl|0.3.1
rainbow-csv|mec|0.8.0
python|ms-|2018.11.0
cpptools|ms-|0.20.1
PowerShell|ms-|1.10.1
sqltools|mtx|0.15.1
vscode-docker|Pet|0.4.0
biosyntax|rea|0.0.9
scala|sca|0.2.0
shader|sle|1.1.4
vscode-hexdump|sle|1.7.2
shadron|vch|0.1.0
prettify-selected-json|vth|1.0.3
gitblame|wad|2.6.3

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@massung I cannot reproduce, for me the sorting order of VS Code is:

```
CADD_phred
CADD_raw
CADD_raw_rankscore
clinvar_clnsig
clinvar_golden_stars
clinvar_rs
clinvar_trait
DANN_rankscore
DANN_score
Eigen-PC-raw
Eigen-PC-raw_rankscore
Eigen-phred
Eigen-raw
FATHMM_converted_rankscore
FATHMM_pred
FATHMM_score
fathmm-MKL_coding_group
fathmm-MKL_coding_pred
fathmm-MKL_coding_rankscore
fathmm-MKL_coding_score
GenoCanyon_score
GenoCanyon_score_rankscore
GERP++_NR
GERP++_RS
GERP++_RS_rankscore
GM12878_confidence_value
GM12878_fitCons_score
GM12878_fitCons_score_rankscore
GTEx_V6_gene
GTEx_V6_tissue
H1-hESC_confidence_value
H1-hESC_fitCons_score
H1-hESC_fitCons_score_rankscore
HUVEC_confidence_value
HUVEC_fitCons_score
HUVEC_fitCons_score_rankscore
integrated_confidence_value
integrated_fitCons_score
integrated_fitCons_score_rankscore
Interpro_domain
LRT_converted_rankscore
LRT_Omega
LRT_pred
LRT_score
mcapv1.0
MetaLR_pred
MetaLR_rankscore
MetaLR_score
MetaSVM_pred
MetaSVM_rankscore
MetaSVM_score
MutationAssessor_pred
MutationAssessor_score
MutationAssessor_score_rankscore
MutationAssessor_UniprotID
MutationAssessor_variant
MutationTaster_AAE
MutationTaster_converted_rankscore
MutationTaster_model
MutationTaster_pred
MutationTaster_score
phastCons100way_vertebrate
phastCons100way_vertebrate_rankscore
phastCons20way_mammalian
phastCons20way_mammalian_rankscore
phyloP100way_vertebrate
phyloP100way_vertebrate_rankscore
phyloP20way_mammalian
phyloP20way_mammalian_rankscore
Polyphen2_HDIV_pred
Polyphen2_HDIV_rankscore
Polyphen2_HDIV_score
Polyphen2_HVAR_pred
Polyphen2_HVAR_rankscore
Polyphen2_HVAR_score
PROVEAN_converted_rankscore
PROVEAN_pred
PROVEAN_score
Reliability_index
SIFT_converted_rankscore
SIFT_pred
SIFT_score
SiPhy_29way_logOdds
SiPhy_29way_logOdds_rankscore
SiPhy_29way_pi
Transcript_id_VEST3
Transcript_var_VEST3
VEST3_rankscore
VEST3_score
```

i.e.
![image](https://user-images.githubusercontent.com/5047891/50095262-6bf07400-0215-11e9-8868-e6c3add1b3d0.png)


We are using the locale comparator, did you perhaps customize your OS locale to one where the sorting rules are different than EN-US ?

**Comment by OlafvdSpek** [comment]
> We are using the locale comparator,

Looks like you found the bug already. ;)

**Comment by alexandrudima** [comment]
I am not convinced that is a bug. The locale comparator can correctly sort "s" and "ș" next to each other if the locale is Romanian or "u" and "ü" next to each other if the locale is German. So IMHO using the locale comparator is correct.

**Comment by massung** [comment]
OK. Pretty sure I know what the issue is (PEBCAK, although I think I'd argue for UX being partly to blame :smile:).

I was completely unaware that there was a need to _select_ all the lines to be sorted before using the command. The text was already mostly sorted, so I didn't actually notice it not sorting on command until a few minutes ago when I attempted to make a test and noticed the sort command doing _nothing_.

Feel free to close this bug as a non-issue, but - personally - I'd recommend having sort lines either work on the entire file when nothing is selected or at least notify the user that nothing was sorted since nothing was selected.

Thanks for taking the time to double check this, though.

**Comment by OlafvdSpek** [comment]
> So IMHO using the locale comparator is correct.

What locale would it use though?
AFAIK a project (or file) doesn't have a locale.. and Code is a code editor. Would it really make sense to use the locale of the developer's machine?

**Comment by alexandrudima** [comment]
@OlafvdSpek I am not 100% sure. We are calling `String.localeCompare` which is documented [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare). I am not sure how this is implemented in Electron's context.
