### ISSUE TITLE
RPM fails to install on opensuse

### ISSUE THREAD

**Issue by djryan77** [Microsoft/vscode#6489]
- VSCode Version: Current
- OS Version: x86_64 GNU/Linux

Steps to Reproduce:

error: Failed dependencies:
        git is needed by code-1.1.1-1463146452.x86_64

But I have git installed and working perfectly. In fact I can pull the source from github but not sure how to build it.

Dave

**Comment by Tyriar** [comment]
I'll look into it, we haven't tested on openSUSE yet.

**Comment by Tyriar** [comment]
I installed openSUSE Leap 42.1 with Gnome on VirtualBox, then downloaded the rpm and used the YaST2 GUI to install it:

![image](https://cloud.githubusercontent.com/assets/2193314/15371225/59085988-1cef-11e6-9f9a-ea9c28ce85ea.png)

`code` seems to work fine:

![image](https://cloud.githubusercontent.com/assets/2193314/15371246/705eb910-1cef-11e6-9db9-45de9b46c448.png)


Did you install git in some strange way and/or are you disconnected from the internet?

**Comment by djryan77** [comment]
No used yast to install git. I did get the ZIP file version working though. However the installer clearly didn't recognize my installed version of git.

Dave

**Comment by viko16** [comment]
@Tyriar 

Will VSCode add into openSUSE software repository ?

I search in below two ways but got empty:
- `sudo zypper search vscode`
- https://software.opensuse.org/search?utf8=%E2%9C%93&q=vscode

**Comment by Tyriar** [comment]
@viko16 we will not make any improvements to the Linux install until https://github.com/Microsoft/vscode/issues/229 is done, which I believe openSUSE can leverage. This is currently blocked on another team but it's definitely on our radar.
