### ISSUE TITLE
Custom key binding for F11 dont work

### ISSUE THREAD

**Issue by adskjfhasdfhygrfuck** [Microsoft/vscode#64891]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.0-46-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-great-icons|emm|2.1.46
python|ms-|2018.4.0
cpptools|ms-|0.16.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1. File->Preferences->Keyboard Shortcuts
2. Find "Toggle full screen" 
3. Del on "Toggle full screen". This one removes key binding from the list. an option  
{
        "key": "f11",
        "command": "-workbench.action.toggleFullScreen"
    }
appears in keybindings.json
4. Restart code
5. Press F11. See the application still toggles from window to fullscreen mode and back. Note that it keeps working as full screen toggle even in debug mode screening "Step into" option.

**Comment by mjbvz** [comment]
Please update to a newer VS Code build. 1.19.3 is almost a year old.

Does this happen in VS Code 1.30?

**Comment by adskjfhasdfhygrfuck** [comment]
Yes, it does reproduce on 1.30 after upgrade.

**Comment by alexandrudima** [comment]
I cannot reproduce on Windows, so it might be a linux specific issue.
