### ISSUE TITLE
File icon theme tree cleanup

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64894]
At the moment the tree can extend from [`FileIconThemableWorkbenchTree`](https://github.com/Microsoft/vscode/blob/757c5feacc2e2c322b1d8e0ac29d02a8d06179e9/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L314) so it opts into the file icon theme.
This tree basically adds 4 css rules, I believe 2 are for showing icons and 2 are for aligning elements.

Here's an example of breadcrumbs that does it without using the `FileIconThemableWorkbenchTree`
https://github.com/Microsoft/vscode/blob/757c5feacc2e2c322b1d8e0ac29d02a8d06179e9/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L133

Here's the css that gets applied (which will have to get updated for the new tree)
https://github.com/Microsoft/vscode/blob/757c5feacc2e2c322b1d8e0ac29d02a8d06179e9/src/vs/workbench/browser/parts/views/media/views.css#L7

At the end this needs to be cleaned up such that the new trees can easly opt into file icon themes.

fyi @jrieken

**Comment by isidorn** [comment]
Also note that this reference here depends on the outdated css class
https://github.com/Microsoft/vscode/blob/ab0b87329f1e5c89f1df6e50c5a4b7e7a37006dc/src/vs/workbench/services/themes/electron-browser/fileIconThemeData.ts#L199

**Comment by jrieken** [comment]
Yeah, this affects the breadcrumbs tree

**Comment by joaomoreno** [comment]
After discussing this with @aeschli, instead of revisiting, we'll simply get it working as before: overriding CSS rules.

**Comment by isidorn** [comment]
File icons are shown in the explorer -> verified
