### ISSUE TITLE
Don't show save dialog when closing a file when autosave is enabled

### ISSUE THREAD

**Issue by mkay581** [microsoft/vscode#64898]
Copying  #35234 which seem to have been locked from anyone commenting or upvoting. I found it kind of odd that a contributor in the old thread [said they will close it until people complain](https://github.com/Microsoft/vscode/issues/35234#issuecomment-345263161), but a locked thread doesn't give any way for anyone to complain :laughing: 

I think this issue is mainly for people coming over to VSCode from IDE's like IntelliJ.

Quoting @musiKk from the other thread:

> Setting `files.autoSave` to `onFocusChange` seems to replicate IntelliJ's save as close as possible. To me this signifies that I don't want to manually save at all. However, when closing a [file] that is currently dirty, VSCode displays a save prompt with "Cancel", "Don't Save" and "Save" buttons. I would expect it to automatically save as well.

- VSCode Version:  1.29.1
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. Set `files.AutoSave` to `onFocusChange`.
1. Open any file.
1. Make any edit.
1. Close file with the shortcut, e.g., for me this is Ctrl+w (don't open command palette, this already counts as a focus change)

Does this issue occur when all extensions are disabled?: Yes

**Comment by musiKk** [comment]
FWIW I switched to `afterDelay` which curiously also includes `onFocusChange` as well as save on closing as I initially requested. I didn't know about that when I filed my initial request. I still think the behavior of `onFocusChange` is inconsistent or at least unexpected but `afterDelay` works well enough for me.

**Comment by mkay581** [comment]
oh I didn't realize that @musiKk. I wonder if the implied `onFocusChange` behavior when using `afterDelay` is a bug :thinking:

**Comment by musiKk** [comment]
I just noticed I talked crap. It is not implied. I just increased the auto save delay and noticed that files are not saved as I expected. The default time of 1000ms was short enough that I accidentally inferred my wrong statements above. Sorry.

**Comment by jhasse** [comment]
Why not introduce a separate `alwaysSaveOnClose` option instead?
