### ISSUE TITLE
 TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#649]
Issue Id: <b>e2f57c64-fe76-0e60-93ff-11fb814e751f</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/base/common/uri.ts#L167:14 (URI.file)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/uri.ts#L167:14 (URI.file))<br />    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/out/launchTargetFinder.js:10:47 <no sourcemaps><br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />    at __dirname.undefined.t.Class.define._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:8092)<br />    at Object.p.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbenc<br />

**Comment by jrieken** [comment]
Happens when no folder is open
