### ISSUE TITLE
Add Resource Context Key ResourceFsPath

### ISSUE THREAD

**Issue by Friday32** [Microsoft/vscode#64902]
Please add a resource context key for fsPath.  Other items are already exposed. See #63940 

Not sure if I should create a new Feature Request for the following item I'd like to have.
A programmatic way in the extension to configure and change "when" clauses.  A example might be showing a menu when the user right clicks on anything within a specific directory.  Later, I might want to change the directory to something else.

**Comment by skprabhanjan** [comment]
@jrieken , Can i take a look at this ?
Some starter points would be helpful ,Thanks :)

**Comment by gsunit** [comment]
@bpasero @jrieken Any update on this issue? I would like to work on this.

**Comment by jrieken** [comment]
This is the file in which it all happens: https://github.com/Microsoft/vscode/blob/926cfe1c4ac6a438f8fa3c4f164219c7c4bf17b5/src/vs/workbench/common/resources.ts#L27

**Comment by Friday32** [comment]
Thanks for implementing this request.
