### ISSUE TITLE
Terminal doesn't let me type

### ISSUE THREAD

**Issue by Nicbo** [Microsoft/vscode#64908]
Issue Type: <b>Bug</b>

1. Open terminal.
2. Voila.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.87GB (8.09GB free)|
|Process Argv|--disable-gpu --disable-gpu-compositing|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
python|ms-|2018.11.0
csharp|ms-|1.17.1
pygame-snippets|tus|0.0.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/43169
