### ISSUE TITLE
Blank character (no space)

### ISSUE THREAD

**Issue by DanMMX** [Microsoft/vscode#64907]
- VSCode Version: 1.29.1
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Write a `{` and then press spacebar.
2. Notice the blank character introduced instead of space character

Does this issue occur when all extensions are disabled?: Yes

![screen shot 2018-12-12 at 12 25 32 pm](https://user-images.githubusercontent.com/1919322/49890280-550ee380-fe09-11e8-9c39-050c38690763.png)

There you can see the blank space before the `asdasd` and also before `Container`, the other space characters correctly put after the `{` were put manually by me. It's annoying to have to do this every time.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
