### ISSUE TITLE
Incorrect tab cycle with Alt + side arrow shortcut

### ISSUE THREAD

**Issue by fritzlolpro** [Microsoft/vscode#64909]
- VSCode Version: 1.29.1
- OS Version: win 10 1703

Steps to Reproduce:

1. Open multiple tabs
2. Try to cycle between them with Alt+ side arrows

Does this issue occur when all extensions are disabled?: Yes

Hello.
On Mac there is Cmd+Alt+side arrows shortcut to cycle tabs, on Windows looks like it should be Alt+arrows, but it works not correct as it skips some tabs or open some closed ones, I don't understand what is wrong. I made some video in order to explain the problem https://monosnap.com/file/ZOIYJr2vXWzJ5afzJDAPpuESJNODtk

If there is how its intended to work then could you please explain me this feature and how can I achive my goal.
thanks in advance

**Comment by usernamehw** [comment]
<kbd>Alt</kbd>+arrows is `back`/`forward` (where cursor was).

`workbench.action.nextEditor` <kbd>Ctrl</kbd>+<kbd>PageDown</kbd>
`workbench.action.previousEditor` <kbd>Ctrl</kbd>+<kbd>PageUp</kbd>
?
