### ISSUE TITLE
Select a text and find it

### ISSUE THREAD

**Issue by falvarezmagaya** [Microsoft/vscode#64916]
Issue Type: <b>Bug</b>

when you search under text selected example "fast-menu_main" visual studio code encode the text a search "fast\-menu_main" that is wrong

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz (16 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|22.00GB (7.78GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
debugger-for-chrome|msj|4.11.1
gitblame|wad|2.4.4

</details>

**Comment by roblourens** [comment]
I don't understand the problem. Please explain exactly what your issue is.
