### ISSUE TITLE
Terminal not rendered correctly on Windows

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#64910]
Version: 1.30.0 (system setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

![term](https://user-images.githubusercontent.com/4033249/49894948-0e6aba80-fe04-11e8-8bec-e0d0e1d09580.gif)

**Comment by Tyriar** [comment]
Welcome to 1809 🎁 https://github.com/Microsoft/vscode/issues/57803
