### ISSUE TITLE
"catch" auto complete

### ISSUE THREAD

**Issue by Denver80211** [Microsoft/vscode#64913]
Issue Type: <b>Bug</b>

In a try catch block, when I type "catch", [hit return or space] the IDE replaces catch with Copy-Patch -not desired

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (17.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
adamstool|Ada|0.1.7
PowerShell|ms-|1.10.1

</details>

**Comment by mjbvz** [comment]
This is for powershell, correct?

**Comment by Denver80211** [comment]
Yes, powershell.  Sorry I forget how diverse this can be

**Comment by mjbvz** [comment]
Thanks. Please file this issue against the PowerShell extension: https://github.com/PowerShell/vscode-powershell/issues
