### ISSUE TITLE
Terminal in Solarized Dark theme seems to have

### ISSUE THREAD

**Issue by totkeks** [Microsoft/vscode#64912]
I recently upgraded my PowerShell on Windows to use the Solarized colors as well. For this I found this repository https://github.com/neilpa/cmd-colors-solarized. They also provide a script to show all the current console colors and their mapping to the respective Solarized dark/light colors.

When comparing both I noticed, that the colors in the Powershell terminal inside VS Code where off.
Inside VS code:
![image](https://user-images.githubusercontent.com/2941389/49897173-b066c300-fe55-11e8-8a6b-b65b11d8af9b.png)

Regular powershell:
![image](https://user-images.githubusercontent.com/2941389/49897230-d5f3cc80-fe55-11e8-94cb-d1004e3721e2.png)

Do they both use different mappings of the Solarized colors to the 16 console colors or does the terminal inside VS Code just works entirely differently?

- VSCode Version: 1.29.1
- OS Version: Win10 1809

Steps to Reproduce:

1. Select the Solarized Dark theme for VS Code
2. Open the terminal with the powershell shell
3. Run the script Out-Colors.ps1 from https://github.com/neilpa/cmd-colors-solarized

**Comment by Tyriar** [comment]
The VS Code terminal does work a little differently, I'd suggest we hold off on this investigation until conpty ships (see https://github.com/Microsoft/vscode/issues/45693, https://github.com/Microsoft/node-pty/issues/216)

**Comment by totkeks** [comment]
Thanks for the quick reply! Your suggestion sounds good. Looking forward to it in future versions.
