### ISSUE TITLE
Does not support touch or digital pen to select text

### ISSUE THREAD

**Issue by binaryWard** [microsoft/vscode#64925]
Issue Type: <b>Bug</b>

I understand this is still an open issue.   It continues to be a problem that text cannot be selected using a digital pen or with touch.

VSCode is basically usless to use when a user does not have a mouse and keyboard.  I can't select text with the Microsoft Surface digital pen or via touch.

Microsoft Windows 1809 software keyboard has a regression that it will close the software keyboard when the shift+arrow key is pressed to select text.  In the previous release this was an issue but was eventually fixed.

VSCode cannot be limited to mouse and physical keyboard.   

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) x7-Z8700  CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chrisalexander** [comment]
Rather than creating a new issue, I am adding a note here that similar issues can be experienced using a Wacom pen / touch tablet.
