### ISSUE TITLE
In-product release notes sometimes don't highlight fenced code blocks

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#64928]
- VSCode Version: 1.30.0 Stable
- OS Version: Windows 10

Steps to Reproduce:

1. Launch VS Code
2. Help > Release Notes
3. Scroll down until you find a fenced code block

JSON or TypeScript fenced code blocks don't have syntax highlighting.

If you close and reopen the release notes, there is highlighting.

**Comment by mjbvz** [comment]
Anyone seeing this recently?

**Comment by mjbvz** [comment]
Confirmed that @gregvanl is no longer seeing this either

Closing as not reproducible
