### ISSUE TITLE
LSP has no way to indicating to the server that the active signature has been changed on the client.

### ISSUE THREAD

**Issue by tinaschrepfer** [Microsoft/vscode#64927]
* User invoke signature help on VS Code (or any client support LSP) and there are multiple matching signatures.
* User selects a different signature on the client and then starts typing parameter

Expected:
The selected active signature should not change.

Actual:
The selected active signature changes to the first one.

This occurs because there is no mechanism in the LSP for the client to send a message to the server that the active signature has changed.

**Comment by jrieken** [comment]
yes  - this is  #33413

**Comment by dbaeumer** [comment]
Closing as dup then #33413
