### ISSUE TITLE
Editor incorrectly guesses Portuguese words as cyrillic 1251 encoding

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#64931]
Issue Type: <b>Bug</b>

VS Code incorrectly guesses file content as cyrillic, when it should be "Western 1252". 

For the same file, Sublime Text correctly detects encoding. 

To repro: 
1. Open any text editor, such as notepad or even vscode.
2. Save file with word ´´´função´´´ (which means function in Portuguese) in Windows 1252 encoding. Close file.
3. Open file in vscode.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.5
terminal|for|0.0.10
matlab|Gim|0.9.0
r|Mik|0.0.5
python|ms-|2018.11.0
shell-launcher|Tyr|0.2.0
markdown-pdf|yza|1.2.0

(2 theme extensions excluded)

</details>

**Comment by pedrogarcia** [comment]
Sublime Text has a settings parameter that's called "fallback_encoding":

` // The encoding to use when the encoding can't be determined automatically.
    // ASCII, UTF-8 and UTF-16 encodings will be automatically detected.
    "fallback_encoding": "Western (Windows 1252)",`

Perhaps there could be a default fallback encoding for vscode as well in cases where it is known to fail.

**Comment by bpasero** [comment]
We are using https://github.com/ashtuchkin/iconv-lite as library, maybe you could report a reproducible issue to them.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by pedrogarcia** [comment]
How can I identify the cause? I'm not a JavaScript programar, I have no idea where it's coming from! All I know is that I've seen little interest so far into fixing these types of bugs.
