### ISSUE TITLE
search slowed

### ISSUE THREAD

**Issue by memory-chen** [Microsoft/vscode#64939]
Issue Type: <b>Bug</b>

The search slowed down and the machine jammed

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv|-psn_0_7997344|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
es7-react-js-snippets|dsz|1.9.2
gitlens|eam|9.1.0
vue-snippets|hol|0.1.9
vscode-titlebar-less-macos|leh|1.7.1
code-beautifier|mic|2.1.0
vs-code-quick-require|mil|0.2.4
vscode-language-pack-zh-hans|MS-|1.30.2
vetur|oct|0.14.3
LiveServer|rit|5.3.1
px-to-rem|sai|1.2.7

</details>

**Comment by memory-chen** [comment]
![image](https://user-images.githubusercontent.com/17876025/49909905-b98a7b00-febb-11e8-9a30-8aba0039349b.png)
This position

**Comment by memory-chen** [comment]
The search slowed down

**Comment by memory-chen** [comment]
> You have turned off the "use ignore files and exclude settings" button. See the gear icon in the "files to exclude" box? Click that, it will make search much faster. Let me know whether that helps.

good

**Comment by roblourens** [comment]
Does that mean it fixed it?

**Comment by memory-chen** [comment]
no，no，no，Today's search directly crashed my computer

**Comment by memory-chen** [comment]
> Does that mean it fixed it?

no，no，no，Today's search directly crashed my computer

**Comment by memory-chen** [comment]
Oh, my god。it's awful

**Comment by roblourens** [comment]
I need to know exactly what you did and what happened.
