### ISSUE TITLE
Window: Title bar custom style is not working any more.

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#64938]
- VSCode Version: 1.30.0 (user setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Does this issue occur when all extensions are disabled?: Yes

Just after update of version 1.30.0 **Custom window title style** is stopped working. I tried many ways to make it working but unfortunatly it's not working. I disabled all the extensions but it still doesn't working. Kindly fix this as soon as possible. **Custom title style** is one of my loving features list. Looking forward for your feedback.

**Thanks**

![image](https://user-images.githubusercontent.com/19922707/49909225-f2b6f100-fea3-11e8-824c-f7d581c2a45a.png)

**Comment by iyashpal** [comment]
Closing the issue because I got the solution from this issue.

**Tittle bar custom is not working (#63982)**

**Comment by iyashpal** [comment]
Reopening the issue becuase it stopped working again.

**Comment by bpasero** [comment]
@iyashpal do you have `smoothScrollingWorkaround` setting enabled maybe? That one requires the native menu bar.

**Comment by Groude** [comment]
Same problem on os x

**Comment by bpasero** [comment]
@iyashpal does it reproduce if you run `code --user-data-dir <some dir>` to truly have a fresh session without settings? If NOT, can you attach your settings here?

**Comment by iyashpal** [comment]
@bpasero it works now. I don't know it resolved with the above command or not but before running the command I have cleared the user settings file of VS Code.

**Comment by bpasero** [comment]
Ok, I think it could have been a setting you used.

**Comment by iyashpal** [comment]
@iyashpal Yes, I think so. Thanks for the help.
