### ISSUE TITLE
Some "view" and "tools" items are hard to find

### ISSUE THREAD

**Issue by SimpleSamples** [Microsoft/vscode#64934]
Please understand that I originally made a suggestion that was short but I thought complete. The issue [Some help menu items should be view menu items · Issue #64875](https://github.com/Microsoft/vscode/issues/64875) has been closed without much effort by a real person to understand it. Yes, it is working as designed but the design is flawed. Please try to understand why the design is flawed.

I am not answering the questions that normally apply (such as Steps to Reproduce and VSCode Version) because they don't apply here. Obviously it does not matter whether extensions are enabled or disabled.

If I want to find tools such as Developer Tools and a Process Explorer then I would not look in the Help menu. I might look at the documentation but not the help menu items. Probably there should be a Tools menu. The original Visual Studio has an enormous list of items in the view menu and it has a Tools menu.

The menu item to show the "Welcome" page should be in the View menu.

If this is closed without a reply from a real person then I will just create another issue.

**Comment by mjbvz** [comment]
Again, this is as-designed:

`View` — Things for controlling the appearance and layout of the editor
`Help` — Help information and debugging / developer commands

All these are also accessible by the command palette

**Comment by SimpleSamples** [comment]
Thank you for responding.

I think many people will disagree that it is a good design but at least you replied. We can agree to disagree.
