### ISSUE TITLE
Autocomplete widget customization

### ISSUE THREAD

**Issue by Novack** [microsoft/vscode#64944]
Would be great if the autocomplete widget could be customized.

Late coders for web based apps wont likely notice, but programmers coming from more conventional IDEs (Visual Studio, MonoDevelop/Xamarin, Rider, Eclipse, etc) find the suggestions widget very ugly looking (no offense).

Could we have tools for customizing the autocomplete rendering? Icons, font family and background color (font size, and line height are already there it seems, but wont affect the signature help box sadly). Also a layout template would be ideal awesome.

**Comment by jrieken** [comment]
This can all be done by now - there is themes and font configs
