### ISSUE TITLE
 a window always overlay another window 

### ISSUE THREAD

**Issue by ylkjick532428** [Microsoft/vscode#64940]
- VSCode Version: 1.30.0(user step) 
- OS Version: Windows_NT x64 10.0.17134
[screenshort](https://imgur.com/a/ggKpV6v)

Steps to Reproduce:

1. open two vscode window, and open two different folder
2. 1 window always cover 2 window

Does this issue occur when all extensions are disabled?: No

**Comment by ylkjick532428** [comment]
![20181213094039](https://user-images.githubusercontent.com/1235388/49910976-b4c7c600-febf-11e8-98bf-9a3ed4d3e40c.png)

**Comment by bpasero** [comment]
@ylkjick532428 there is a setting to control how the second window opens: `window.newWindowDimensions`. Does that help?
