### ISSUE TITLE
How to debug extensionHost in the javascript?

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#64947]
I am using javascript to develop extension, this is my launch.json
```json
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}/publish/"
            ],
            "sourceMaps": false,
        }
```
But I can't see the correct symbol for the internal code of vscode. If I change sourceMaps to true, my code (javascript) will not be able to be located by the debugger.

**Comment by weinand** [comment]
Please follow these steps for creating a VS Code Extension: https://code.visualstudio.com/docs/extensions/example-hello-world

The launch config looks like this:
```
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        },
```

**Comment by actboy168** [comment]
I have not made any changes, but now it is alright. Maybe I missed something before, always thank you very much.
