### ISSUE TITLE
Too long pathway showing

### ISSUE THREAD

**Issue by igekaratas** [Microsoft/vscode#64942]
- VSCode Version: 1.30
- OS Version: Windows 10 64bit

Hi, when I try to run python code I can see that long in terminal which fill the whole terminal:
`PS C:\Users\mpc> cd 'c:\Users\mpc\Desktop\python\asquest'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'python' 'c:\Users\mpc\.vscode\extensions\ms-python.python-2018.11.0\pythonFiles\experimental\ptvsd_launcher.py' '--default' '--nodebug' '--client' '--host' 'localhost' '--port' '7818' 'c:\Users\mpc\Desktop\python\asquest\oop.py`

I don't want to see that long nonsense. I just want to see output. What should I do?

![vscode](https://user-images.githubusercontent.com/28317005/49911780-8e147b80-fe3c-11e8-9917-ef73e2bc7914.JPG)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
