### ISSUE TITLE
In new release titleBarStyle "custom" not working in Windows

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#64945]
Issue Type: <b>Bug</b>

After updating to the new release in my Windows machine, the custom titlebar was gone and the native titlebar was shown. I checked the deault settings and it is still custom. I manually changed it to custom but did not have any effect.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.1.0
csharp|ms-|1.17.1
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by Summon528** [comment]
I also encountered the same problem

Version: 1.30.0 (system setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.18298

**Comment by Summon528** [comment]
Apparently you should disable `window.smoothScrollingWorkaround`, see #63982

**Comment by gulshan** [comment]
@Summon528 Yes, it is the problem. Thanks.
