### ISSUE TITLE
Transpiled JS file in same DIR is not found in explorer

### ISSUE THREAD

**Issue by jmzagorski** [Microsoft/vscode#6494]
- VSCode Version: 1.1.1
- OS Version: Windows 7

Steps to Reproduce:

1. Created a folder and file ../spec/config/element.spec.ts
2. Transpiled to same dir via gulp so I now have ../spec/config/element.spec.js:

gulpfile.js
```
gulp.task("transpile:test", function () {
  var tsResult = tsProjectTest
    .src()
    .pipe(plug.typescript(tsProjectTest))

    tsResult.js
    .pipe(plug.ngAnnotate())
    .pipe(gulp.dest("/spec/"));

  return tsResult.js
    .pipe(gulp.dest("/spec/"));
});
```

tsconfig.json
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "noEmitOnError": true,
    "noImplicitAny": false,
    "removeComments": false,
    "outDir": "/spec/",
    "sourceMap": false,
    "target": "es5",
    "watch": true,
    "preserveConstEnums": true
  },
 "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```
I can see the JS file in windows explorer and I can search for it (search only found it after exiting VS code and coming back in. A refresh did not work.), but the JS file does not show up in VS code's explorer (I can only see the TS file)

**Comment by weinand** [comment]
@jmzagorski do you have an files.exclude filter in your settings file that hides *.js files?

**Comment by jmzagorski** [comment]
well that was dumb of me ha. I must have set that when I was taking the tutorial on VS code way back when. Sorry!
