### ISSUE TITLE
Custom title bar setting doesn't make any change

### ISSUE THREAD

**Issue by muthukumar143** [Microsoft/vscode#64953]
We have written the needed data into your clipboard because it was too large to send. Please paste.
![screenshot 50](https://user-images.githubusercontent.com/25875778/49933575-02f5bd00-fef2-11e8-8632-8afc623cee60.png)

**Comment by Groude** [comment]
Same problem

**Comment by RaduPetcu** [comment]
same issue on Windows 7 Enterprise

**Comment by NomanGul** [comment]
Remove this from your Settings: "window.smoothScrollingWorkaround": true

**Comment by muthukumar143** [comment]
Try this it works.
"window.smoothScrollingWorkaround": false"
Thanks NomanGul
