### ISSUE TITLE
Elements report hovered without mouse moving when they appear

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#64955]
- Position the cursor near the top of the screen where quickopen will appear
- Open quickopen
- The row under the cursor has the hover highlight color, but it should not be highlighted. It should only be "hovered" if the cursor has moved

In 1.29, the row is not highlighted until I move the cursor.

Tell me if you don't know what I'm talking about and I can attach a gif or something.

**Comment by bpasero** [comment]
@roblourens yeah gif please. the first entry is always selected automatically.

**Comment by roblourens** [comment]
This is just in Insiders so it might be Electron.

See how the row under the cursor is highlighted immediately when quickopen appears. That doesn't happen in 1.30.

![dec-12-2018 23-03-18](https://user-images.githubusercontent.com/323878/49921360-2a04ae00-fe62-11e8-978c-493d5d8bbc0b.gif)

**Comment by bpasero** [comment]
Seems normal to me, looks like this in default light theme:

![image](https://user-images.githubusercontent.com/900690/49921882-42e78080-feaf-11e8-9db7-c3426242b5cc.png)

**Comment by bpasero** [comment]
@roblourens I see what you mean, there is definitely a change, probably due to Electron 3. However I think the behaviour now is the correct one, no? The mouse is over an item and that one shows the hover feedback?

**Comment by roblourens** [comment]
If the cursor is invisible, I think I'm not capable of "hovering". I have a hard time calling it "wrong" for the case when the cursor is still visible (first iteration in my gif).

I keep seeing it in the suggest list too. Partly it's annoying just because Monokai's "focus" color is very close to the "hover" color.

When I type and the cursor hides, that's something the browser does and we don't control, right? It's interesting that it doesn't hide the first time I invoke quickopen, but it does hide when I press esc to hide it...

This does seem to be due to the `:hover` pseudoclass. I guess the only way around would be to watch for mouse movement events which I'm not sure we want to do. 

Like one fix could be

- Add a mousemove listener to each list
- When the list becomes visible, the first time the listener is invoked, add a class `hover` to the list
- Write the css rules like `.list.hover item:hover ...`

**Comment by bpasero** [comment]
I will unfortunately not have time to work on this, but leaving it open as electron 3 issue.

**Comment by matthewwithanm** [comment]
I think this should be reopened. It's a pretty nasty UX issue and that's really confusing and (unless you know what's going on) feels totally arbitrary.
