### ISSUE TITLE
context menu scroll won't allow scrolling to the bottom

### ISSUE THREAD

**Issue by dewdad** [Microsoft/vscode#64958]
We have written the needed data into your clipboard because it was-> too large to send. P
Issue Type: <b>Bug</b>

When there are many items in the context menu for a JS file the context menu yanks up when scrolling past the bottom visible menu items.

![demo](https://thumbs.gfycat.com/ElaborateHastyBoilweevil.webp)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (124)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.0.0
project-manager|ale|10.0.0
vscode-sqlite|ale|0.3.2
copy-relative-path|ale|0.0.2
odatatools|apa|2.0.1
swagger-viewer|Arj|2.1.0
vscode-database|baj|1.5.3
vscode-django|bat|0.17.0
node-json-autocomplete|bhs|0.1.3
django-html|bib|1.3.0
django-snippets|bib|1.1.1
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-css-modules|cli|0.2.3
jsrefactor|cms|2.15.1
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
jsontotype|dan|0.0.3
vscode-eslint|dba|1.7.0
vscode-faker|dee|1.3.0
microsoft-translate-ext|dig|0.1.5
vscode-npm-source|dku|1.0.0
git-extension-pack|don|0.1.3
githistory|don|0.4.4
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
xml|Dot|2.3.2
Vue2|duc|0.1.3
gitlens|eam|9.1.0
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.41
vscode-npm-script|eg2|0.3.5
vscode-dependency-vulnerabilities|eli|1.0.1
LogFileHighlighter|emi|2.4.2
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vscode-yarn|gam|1.6.0
local-history|gay|0.0.3
webpack-snippets|gog|0.0.4
global-config|Gru|0.0.7
vscode-nginx-conf-hint|han|0.1.0
vscode-mocha-test-adapter|hbe|1.5.1
vscode-test-explorer|hbe|2.2.0
jsonnet|hep|0.1.0
beautify|Hoo|1.4.7
rest-client|hum|0.20.4
output-colorizer|IBM|0.1.2
kubesquash|ile|0.0.4
search-node-modules|jas|1.3.0
markdown-touchbar|Jay|1.0.3
markdown-extended|jeb|1.0.3
webpack|jer|2.1.0
docthis|joe|0.7.1
vscode-map-preview|jum|0.4.2
types-autoinstaller|jvi|2.4.0
vscode-gist|ken|1.2.1
vscode-ava-runner|Kni|0.0.3
vscode-github|Kni|0.30.1
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|0.7.0
translatorplus|lky|1.1.2
nodejs-repl|los|0.5.10
MagicPython|mag|1.1.0
json-to-ts|Mar|1.5.5
Kotlin|mat|1.7.0
markdown-shortcuts|mdi|0.9.0
vscode-checkpoints|mic|1.1.0
import-sorter|mik|3.2.0
dotenv|mik|1.0.1
HTMLHint|mka|0.5.0
python|ms-|2018.11.0
node-debug2|ms-|1.30.3
PowerShell|ms-|1.10.1
vsliveshare|ms-|0.3.1013
debugger-for-chrome|msj|4.11.1
nodejs-docs|Muk|0.2.2
color-highlight|nau|2.3.0
node-modules-resolve|nau|1.0.2
json-parse-stringify|nex|1.0.2
vscode-json-editor|nic|0.2.2
peep|nwa|0.0.5
vetur|oct|0.14.3
vscode-json-transform|oct|0.1.2
fix-json|oli|0.1.2
vscode-docker|Pet|0.4.0
vscode-versionlens|pfl|0.22.0
vscode-gitignore-generator|pio|1.0.1
repl-dev|Pip|0.0.6
quicktype|qui|12.0.46
startanyshell|rem|0.3.1
json-organizer|rin|0.0.4
vscode-icons|rob|7.28.0
explorer-excluded-files|sad|1.0.0
ava|sam|0.6.0
vscode-javascript-booster|sbu|0.10.2
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.3
gitconfig|sid|2.0.0
java-generate-setters-getters|soh|4.0.2
vscode-auto-install|spe|1.0.1
es6-mocha-snippets|spo|0.2.2
code-spell-checker|str|1.6.10
vs-code-node-require|tgr|1.2.11
vue-docs|tit|1.0.0
vscode-status-bar-format-toggle|tom|1.4.0
vscodeintellicode|Vis|1.1.0
vscode-java-dependency|vsc|0.2.0
vuetify-vscode|vue|0.2.0
nodejs-extension-pack|wad|0.1.9
jinja|who|0.0.8
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.1
local-history|xyz|1.7.0
blade-runner|yuk|1.0.0
json-helper|zho|1.3.2
vscode-open-in-github|ziy|1.3.6
tslint-snippets|zuo|1.1.0

(1 theme extensions excluded)

</details>
lease paste.

**Comment by sbatten** [comment]
duplicate of #64933
