### ISSUE TITLE
#region cannot be unfolded in .cs file

### ISSUE THREAD

**Issue by biggray** [Microsoft/vscode#64954]
Issue Type: <b>Bug</b>

#region cannot be unfolded after reloading window when #region is folded. There is no "+" glyph on the left side. Sometime it occurs when opening file via left side file explorer after reloading window.
And in each case, you need to wait till omnisharp is ready to reproduce.

Screenshot:
![region-cannot-unfold](https://user-images.githubusercontent.com/22905516/49917994-6674f000-fedc-11e8-89ce-1e4d3eb144c1.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
auto-comment-blocks|kev|1.0.1
csharp|ms-|1.17.1
vs-keybindings|ms-|0.2.0

</details>

**Comment by octref** [comment]
Can you give a repro case?

**Comment by biggray** [comment]
The repo on which I found this problem is not public and cannot be made accessible to you.
I will try to cteate a public example repo for this when I have time. Probabily this weekend or next weekend.
Please wait for several days.

**Comment by octref** [comment]
That's fine, just to clarify: Are you saying that this happened?

- Fold all the `#region`
- Reload VS Code
- You can't unfold all the `#region` until Omnisharp is ready? (Can you unfold them after Omnisharp is ready?)

This might be as-designed. VS Code used to use indentation/marker based folding, and the C# extension is using the newly added language-server based folding.

**Comment by biggray** [comment]
Most of what you listed about the reproducing steps are right, except the last one. I cannot unfold after the omisharp getting ready. I can unfold before it getting ready.

**Comment by octref** [comment]
That's definitely a bug then.

**Comment by biggray** [comment]
Yes it's a bug. Please have a look at it. If you cannot reproduce it, please wait for several days. I will try to provide a public example repo for it. Thanks!

**Comment by biggray** [comment]
@octref 
Sorry that I didn't get time to look at it. And seems it is working correctly in latest version. So I am closing this issue now. I would first investigate and create another issue if I encounter this again.
Really thank you for your time.

**Comment by octref** [comment]
Sure, thank you!
