### ISSUE TITLE
The "Pick a folder to initialize a git repo in" menu does not go away after clicking elsewhere in the Editor

### ISSUE THREAD

**Issue by Jackson5551** [Microsoft/vscode#64951]
- VSCode Version: 1.30.0
- OS Version: Windows 7 Home Premium 64 bit

Steps to Reproduce:

1. Open the source control side panel.
2. In the right hand corner of the header of the panel click on the "Initialize Repository" Button. (A small git icon)
3. The menu will appear and will not go away when you click elsewhere in the editor.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This was an explicit decision, some quick open menus are just like that. It helps users in that they can they alt-tab to a browser, get the git url and simply paste it once back.

**Comment by Jackson5551** [comment]
Oh, thanks for the clarification @joaomoreno .
