### ISSUE TITLE
Chinese language can't display in the new window.

### ISSUE THREAD

**Issue by LiunxPaisley** [Microsoft/vscode#64968]
Issue Type: <b>Bug</b>

When click "new window" to create another window, Chinese language can't display but English displays on the window.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prototxt|dmi|0.0.6
vscode-great-icons|emm|2.1.46
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.20.1
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.3
guides|spy|0.9.2
cmake-tools|vec|1.1.3
clang-format|xav|1.8.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@LiunxPaisley Is the current window is being shown in Chinese ?

**Comment by LiunxPaisley** [comment]
> @LiunxPaisley Is the current window is being shown in Chinese ?

Yes, the current window is still shown in Chinese but the new windows is shown in English.

**Comment by sandy081** [comment]
It works for me.. Are there any particular steps to repro?

**Comment by bal-lon** [comment]
This language pack issue really bothers me。It occurs not only when you click 'new window',but also when you just start the vcs sometimes.
