### ISSUE TITLE
Markdown syntax highlighting for handling C/C++ using code block is abnormal.

### ISSUE THREAD

**Issue by b10102016** [Microsoft/vscode#64966]
Issue Type: <b>Bug</b>

create a fenced code block with the following content:

```c
#define ABC 123
#define ABC 123
#define ABC 123
```

First line is normal, but the following will be abnormal.

As the picture:

![screenshot from 2018-12-13 15-53-30123](https://user-images.githubusercontent.com/6422887/49924027-27509a00-fef0-11e8-8d9e-18af7ff71183.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 1652)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.46GB (0.39GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
scope-bar|amo|0.1.0
xml|Dot|2.3.2
gitlens|eam|9.1.0
intellij-idea-keybindings|k--|0.2.30
favorites|kdc|2.4.5
python|ms-|2018.11.0
cpptools|ms-|0.20.1
indent-rainbow|ode|7.2.4
devicetree|plo|0.1.1
java|red|0.35.0
code-settings-sync|Sha|3.2.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.11.3

</details>

**Comment by mjbvz** [comment]
Same root cause as #34525

Upstream issue with how the c/c++ grammar is written. Make embedding like this not possible
