### ISSUE TITLE
Avoid the use of MouseEvent.toElement

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#64965]
It looks like `MouseEvent.toElement` and `MouseEvent.fromElement` are deprecated and rather `target` and `relatedTarget` should be used. 

See also: https://github.com/w3c/pointerevents/issues/167#issuecomment-375100532

**Comment by skprabhanjan** [comment]
@bpasero , Can i change this ?
I looked through the code and I assume `e.toElement` should be changed to `(<HTMLInputElement>e.target)` in all the occurrences (`src/vs/workbench/parts/preferences/browser/settingsTree.ts , src/vs/base/browser/ui/selectBox/selectBoxCustom.ts , src/vs/base/browser/dom.ts`)

To change fromElement , I am not able to do e.relatedTarget .

**Comment by cleidigh** [comment]
@skprabhanjan it is @bpasero call...

**Comment by roblourens** [comment]
I got it thanks @skprabhanjan
