### ISSUE TITLE
Line comments jump left a tab after return is pressed

### ISSUE THREAD

**Issue by karye** [Microsoft/vscode#64979]
Just updated to 1.30.0.

When editing in Javascript, comments does not respect the indenting.
Line comments jump to the left after pressing return!

For example:
```
function start() {
/* A comment */
    
    let a = 0;
/* A comment */
    
}
```

Expected result:

```
function start() {
    /* A comment */

    let a = 0;
    /* A comment */

}
```

**Comment by mjbvz** [comment]
I can't reproduce this problem. Please describe the exact steps (including keypresses) to reproduce this issue

**Comment by karye** [comment]
Solved!
The culprit is:
"editor.formatOnType": true

Removing this line in settings is the solution.
