### ISSUE TITLE
Error in defaultSettings.json

### ISSUE THREAD

**Issue by KrishnaPrasanthVemuganti** [Microsoft/vscode#64974]
Issue Type: <b>Bug</b>

Getting end of file expected error in defaultSettings.json.

VS Code version: Code - Insiders 1.31.0-insider (7ab53e6d1c7998006bc70f18230178a702598222, 2018-12-13T06:20:30.449Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.1.0
code-runner|for|0.9.5
python|ms-|2018.11.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It should no longer be opening the default settings file by default.

**Comment by usernamehw** [comment]
@roblourens, why was this closed? default settings still have invalid json: `End of file expected.`

![default_settings](https://user-images.githubusercontent.com/9638156/50085593-8aea0880-020b-11e9-87f1-7dfe58897725.png)

**Comment by roblourens** [comment]
Oh yeah, I misunderstood the issue.

**Comment by roblourens** [comment]
@sandy081 any idea why we weren't writing the raw settings json as an array? Looked like it started with a change from me but I have no idea why I did that 🤷‍♂️. I don't think there's any good reason for it.

**Comment by sandy081** [comment]
I raw settings json can be made array, but the default settings object that old default settings editor is using need to have multiple groups.

**Comment by roblourens** [comment]
It's already an array of multiple groups, I didn't change that.

**Comment by sandy081** [comment]
Since we are exposing it as default settings now, I would rather change it to single array - https://github.com/Microsoft/vscode/issues/67642. Will fix it next milestone.
