### ISSUE TITLE
How to ctrl+right arrow and/or ctrl+left arrow, jump words in Visual Studio Code's Terminal

### ISSUE THREAD

**Issue by ericpardee** [Microsoft/vscode#64972]
Issue Type: <b>Feature Request</b>

My fingers are years-programmed to use ctrl+right arrow to jump a word forward, ctrl+left arrow to jump a word back, in Terminal/iTerm. 

I can not figure out how to get this functionality in Visual Studio Code's Integrated Terminal (macOS obviously). vscode/Code Version 1.30

I have disabled Mission Control, https://apple.stackexchange.com/questions/18043/how-can-i-make-ctrlright-left-arrow-stop-changing-desktops-in-lion

How do I accomplish this?

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

**Comment by Tyriar** [comment]
This is the behavior out of the box for bash. If you are using zsh option+left/right will jump words and you can configure the terminal to use ctrl with these keybindings:

```
    {
        "key": "ctrl+left",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "\u001bb" }
    },
    {
        "key": "ctrl+right",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "\u001bf" }
    }
```

**Comment by Tyriar** [comment]
Added to the FAQ on the website https://github.com/Microsoft/vscode-docs/commit/4ae3b801c291365a44b7ce2d07123be941ac321c

**Comment by ericpardee** [comment]
Awesome!!!!!!!
I'm actually using GNU bash, version 4.4.23 (via homebrew: `brew install bash`) and those keybindings **work**!
Thank you, thank you, thank you

**Comment by Tyriar** [comment]
Good to hear 😃
