### ISSUE TITLE
Suggestion: show "in progress" feedback for file moves/renames

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#64986]
When I move/rename a file in a large TypeScript project:

1. VS Code instantly moves the file
2. Then, about 5-10 seconds later (time seems to depend on project size), I get a message asking whether I would like to update imports.

In between 1 and 2, could we show some feedback in the VS Code UI that the move/rename is in progress, aka TypeScript is loading?

Sometimes I immediately move on to some other work after step 1, and then I'm taken back to the previous task when the message pops up. If the UI made it clearer that a rename was still "in progress", it would make for a more explicit user experience.

**Comment by mjbvz** [comment]
Also opened #65112 to track why this takes so long in the first place

**Comment by jrieken** [comment]
verified in code
