### ISSUE TITLE
JSX Auto-format adds unnecessary space in attributes

### ISSUE THREAD

**Issue by AlecBoutin** [Microsoft/vscode#6498]
- VSCode Version: 1.1

The .tsx/.jsx auto-formatter adds an unnecessary space on the end of certain dynamic attributes.

E.g. `<button id={fn()} />` becomes `<button id={fn() } />` after the file is auto-formatted. A space is inserted after the closing parenthesis of the fn() call.

The problem appears to be related to having parenthesis in the attribute.

E.g. <button id={""} /> is left unchanged by auto-format. `<button id={("")} />` becomes `<button id={("") } />` (the space is inserted)

I have also observed the auto-formatter preserves the spaces in the id attribute of `<button id={ ("") } />`

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8683
