### ISSUE TITLE
调试功能有问题

### ISSUE THREAD

**Issue by studyzhanglei** [Microsoft/vscode#64989]
Issue Type: <b>Feature Request</b>

调试有问题，无法新增配置，也打不开调试的配置文件

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

**Comment by studyzhanglei** [comment]
后来能打开了，发现php调试端口号与php-fpm冲突，所以启动不了。请问有规避方法吗？

**Comment by mjbvz** [comment]
> There is a problem with debugging, you cannot add a new configuration, and you cannot open the Debug configuration file

**Comment by isidorn** [comment]
Please file a new issue in english and with nice reproducable steps
