### ISSUE TITLE
Running VSCode as Admin prevents closing tabs with middle mouse button

### ISSUE THREAD

**Issue by parzh** [Microsoft/vscode#64983]
Issue Type: **Bug**

1. Run VSCode as Administrator;
2. Open new tab;
3. Click on the tab's header with middle mouse button.

**Expected result**: the tab is closed.  
**Actual result**: the tab is not closed.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|1.7.0
gitlens|eam|9.2.0
tslint|eg2|1.0.41
python|ms-|2018.11.0
material-icon-theme|PKi|3.6.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by bpasero** [comment]
I cannot reproduce.

**Comment by parzh** [comment]
Apparently, there is a software issue with the touchpad on my laptop (Huawei Matebook D): after connecting an actual mouse, the problem went away. Sorry for the trouble.
