### ISSUE TITLE
Extension host terminated unexpectedly in vs code insiders 1.31.0

### ISSUE THREAD

**Issue by hassanbinsafdar** [Microsoft/vscode#64981]
Hello I am using VS code insiders and recently its updated to v1.31.0 and after reload i am getting error Extension host terminated unexpectedly and I am using mac os mojave.

And Visual studio updated to 1.30.0 and its so slow now .

- VSCode Version: insiders 1.31.0
- OS Version: mac os mojave

Steps to Reproduce:

**Comment by adampolehonky** [comment]
> Hello I am using VS code insiders and recently its updated to v1.31.0 and after reload i am getting error Extension host terminated unexpectedly

Hey, I am having the same issue as you mate! Updated earlier and that when the problem arose!! I am on High Sierra, strangely the Non-insiders version is working fine!!

**Comment by hassanbinsafdar** [comment]
I figured it out when i install (live sass compiler) extension its installing (live server) extension as well and those extensions giving the issue. (Extension host terminated unexpectedly.).But they were installed before but was working perfectly. so basically problem with live server

**Comment by caiceA** [comment]
> I figured it out when i install (live sass compiler) extension its installing (live server) extension as well and those extensions giving the issue. (Extension host terminated unexpectedly.).But they were installed before but was working perfectly. so basically problem with live server

how did you solve it? by removing the extension?

**Comment by lukesUbuntu** [comment]
@caiceA  just open dev tools and see which extension is causing the issue and disable it. I found it was the live server extension.

**Comment by caiceA** [comment]
@lukesUbuntu thanks man, I disabled "**Simple FTP** " and problem solved.
 live server. working fine on my side.

**Comment by ritwickdey** [comment]
This issue is coming due to `fsevents` package. `Chokidar` is depended on `fsevents`. 

Any 3rd party extension that are using `Chokidar` is falling for Mac (only Mac, as `fsevents` is only for Mac).

https://github.com/electron/electron/issues/14841
