### ISSUE TITLE
default html formatter is not working after upgrading to 1.30

### ISSUE THREAD

**Issue by nnmm1711** [Microsoft/vscode#64996]
- VSCode Version:1.30
- OS Version:win10

Steps to Reproduce:

1.auto closing and intelli sense both stopped working and enabling it in setting doesn't help
2.tried in clean os, still the same

Does this issue occur when all extensions are disabled?: Yes

**Comment by nnmm1711** [comment]
always displays a notice: " There is no document formatter for 'html'-files installed."

**Comment by pedro-w** [comment]
This is the same as #64993  I think.

**Comment by LangZhai** [comment]
I encountered the same problem after upgrading to 1.30.

**Comment by nnmm1711** [comment]
simply uninstall 1.30 then reinstall 1.29 won't solve this issus. need to delete this folder 
”users\[username]\appdata\roaming\Code" before reinstalling 1.29. 

this way can get the auto formatter back

**Comment by LangZhai** [comment]
This only happens for HTML files opened on no workspace.
See #64993

**Comment by octref** [comment]
I can repro and I'm looking into this now.

**Comment by octref** [comment]
No-workspace bug: This should be fixed in 1.30.1.
