### ISSUE TITLE
Refresh errors in file explorer

### ISSUE THREAD

**Issue by DanielSWolf** [Microsoft/vscode#64995]
Since #782, the file explorer displays the number of errors next to each file. It seems, however, that these values are only updated when the file in question is open in an editor window. Often, however, the number of errors in a file changes *without* that file being open. In that case, the number number of errors displayed in the explorer doesn't update.

One typical example: In TypeScript, I make a change to the signature of a function. As a result, all code files that contain a call to that function now have errors. But VS code won't show them in the file explorer. If it did, it would be much easier for me to spot the lines I've broken and to fix them.

It would be great if the "Refresh" button not only updated the list of files, but also their error counts.

**Comment by usernamehw** [comment]
Maybe related #13953

**Comment by isidorn** [comment]
Let's close as dup of #13953 since that is required for this
