### ISSUE TITLE
Unable to see intellisense on C/C++ file.

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#6499]
- VSCode Version: latest
- OS Version: OS X

Steps to Reproduce:

1. Create a .cpp or .c file
2. type printf() or cout <<
3. Expected to see intellisense but none.

**Comment by weinand** [comment]
@sumonto VS Code has no builtin functionality for C/C++ intellisense. What extension did you install for C/C++ support?
If you have a C/C++ extension installed but it does not show intellisense please file a bug against that extension.

**Comment by sumonto** [comment]
I am using C/C++ Complete from Microsoft on OS X

Date: Wed, 18 May 2016 13:17:49 -0700
