### ISSUE TITLE
VS Code getting stuck

### ISSUE THREAD

**Issue by hassanbinsafdar** [Microsoft/vscode#64991]
Hello after update of VSCODE its getting stuck everytime.
when i try to write html
I am going to attach image its always saying starting extension and waiting for html document

<img width="1440" alt="screen shot 2018-12-13 at 5 07 06 pm" src="https://user-images.githubusercontent.com/13061479/49938031-6a176f80-fefa-11e8-8385-18ce34830d85.png">

- VSCode Version: 1.30.0
- OS Version: mac os X mojave

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

**Comment by hassanbinsafdar** [comment]
@mjbvz no i disabled all extensions and its seems okay now i am trying to figure it out that which extension is actually doing this.

**Comment by hassanbinsafdar** [comment]
@mjbvz I figured it out when i install (**live sass compiler**) extension its installing (**live server**) extension as well and those extensions giving the issue. **(Extension host terminated unexpectedly.)**.But they were installed before but was working perfectly.

**Comment by mjbvz** [comment]
Ok, please file an issue against that extension
