### ISSUE TITLE
"cwd": "${fileDirname}" on Linux not working

### ISSUE THREAD

**Issue by chiboreache** [Microsoft/vscode#64998]
` "options": {
                "cwd": "${fileDirname}"
            }` 

custom task rule on Linux - not working

**Comment by chiboreache** [comment]
```"presentation": {
                "reveal": "silent",
                "panel": "new"
            }```

also

**Comment by chiboreache** [comment]
```
"presentation": {
                "reveal": "silent",
                "panel": "new"
            }
```

also

**Comment by alexr00** [comment]
@chiboreache, this is the task that I tried to reproduce with:

            {
			"type":"shell",
			"command": "ls",
			"options": {
				"cwd": "${fileDirname}"
			},
			"label": "DIR TASK",
			"problemMatcher": [],
			"presentation": {
				"reveal": "silent",
				"panel": "new",
			}
		}

I can't reproduce the issue though. Can you try with this task and see if it works?

**Comment by alexr00** [comment]
We're exploring how and whether we want to have some UI for tasks. If you want to follow it is this issue: https://github.com/Microsoft/vscode/issues/28235
