### ISSUE TITLE
We need translation support

### ISSUE THREAD

**Issue by HLFH** [Microsoft/vscode#65]
Hi,

@jrieken @chrisdias 

We need translation support.

Btw, I can help with French & German.

Thanks,
HLFH

**Comment by ygorlazaro** [comment]
I can help with Portuguese

**Comment by be5invis** [comment]
I can help with Simplified and Traditional Chinese.

**Comment by calvalugo** [comment]
I can help with spanish

**Comment by FleecyMirror** [comment]
There is a folder named `locales`, but all files in it are blank. I believe translate support will come soon. 

![image](https://cloud.githubusercontent.com/assets/9635792/11365110/4a4e4ef6-92df-11e5-8f11-8a7dc1e2a96f.png)

**Comment by ygorlazaro** [comment]
Is there another issue telling about this folder?

**Comment by suabahasa** [comment]
I can help with Indonesian

**Comment by egamma** [comment]
This is work in progress, this is the corresponding plan item #2041.

**Comment by brayancruces** [comment]
Good, i will help with spanish traslation.

**Comment by alexandrudima** [comment]
@dbaeumer This should now be closed?

**Comment by dbaeumer** [comment]
Closing since we do have translation now for major language. The item still open is that we allow external contributions to the translation which we have on the backlog.
