### ISSUE TITLE
 TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#650]
Issue Id: <b>b2f72267-f7dd-d57b-dc9d-2cb86f4115e2</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />
TypeError: Converting circular structure to JSON 
at Object.stringify (native) 
[/vs/base/common/marshalling.ts#L119:14 (marshallObject)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/marshalling.ts#L119:14 (marshallObject))<br />[/vs/platform/plugins/common/ipcRemoteCom.ts#L131:19 (create.serializeAndSend)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/plugins/common/ipcRemoteCom.ts#L131:19 (create.serializeAndSend))<br />[/vs/platform/plugins/common/ipcRemoteCom.ts#L114:4 (create)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/plugins/common/ipcRemoteCom.ts#L114:4 (create))

**Comment by bpasero** [comment]
Tough to know unless we have the stack of what actually is being sent. Alex any ideas what to do about this error?

**Comment by alexandrudima** [comment]
@SofianHn can you help us figure out what code sits at `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:11:17461`

**Comment by SofianHn** [comment]
@alexandrudima 
`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:11:17461` is actually `/vs/platform/plugins/common/ipcRemoteCom.ts#L114:4 (create)`

The combining logic between minified and de-minifed stack traces had a bug here. I updated the stack for this specific issue. It should be ok to see frames with no sourcemaps if it's coming from extensions. In this case, we should always have a sourcemap. 

As for this issues @bpasero, this is the full stack that we have. Maybe try to catch this issue in the code and use [safeStringify](https://github.com/Microsoft/vscode/blob/6e3703638eecdf70a585302aaa87f603b0bd93b5/src/vs/base/common/objects.ts#L290) to log the payload to help us pin point the issue.

**Comment by SofianHn** [comment]
this issue is happening too in 0.10.2 
68abf37c-ce02-e66a-71cb-9a25a4c0101c

**Comment by bpasero** [comment]
@alexandrudima not sure why I am assigned, I think the marshalling code is yours?

**Comment by alexandrudima** [comment]
@bpasero the marshalling code is indeed authored by me, but this code is called with invalid arguments (circular data structure). The question is where do the invalid arguments come from, which the stack fails IMHO to show.

**Comment by bpasero** [comment]
@alexandrudima maybe we could add code that prints a stacktrace (actually would need to send this via telemetry) when we detect a circular JSON structure?

**Comment by alexandrudima** [comment]
@bpasero The initial issue description contains the stacktrace: it starts at:
[/vs/platform/plugins/common/ipcRemoteCom.ts#L114:4 (create)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/plugins/common/ipcRemoteCom.ts#L114:4 (create))

which I think means something was invoked on the extension host, `then` a result got produced and the result got sent back to the main process. The result could not be serialized for sending back to the main process.

The stacktrace does not show what was invoked. The marshalling code, if it would try to capture the stacktrace would produce the same stacktrace... I think the question is where is the full stacktrace

**Comment by alexandrudima** [comment]
Didn't happen in 6 months => closing
