### ISSUE TITLE
VSCode 1.30.0 reporting TS2607 and TS2339 errors for most TSX in project

### ISSUE THREAD

**Issue by daneast915** [Microsoft/vscode#65006]
Issue Type: <b>Bug</b>

Most TSX is now flagged with either TS2607 or TS2339 errors after installing VSCode 1.30.0. This did not happen with previous VSCode releases. The TS compiler does not report those errors.

message": "JSX element class does not support attributes because it does not have a 'props' property.

Sample:
// Flagged with TS2607
  <SimplePropertiesComponent imodel={options.iModelConnection} rulesetId={options.rulesetId} orientation={Orientation.Horizontal} />

export interface Props {
  imodel: IModelConnection;
  rulesetId: string;
  orientation: Orientation;
}
// this.props flagged with TS2339
export default class SimplePropertiesComponent extends React.Component<Props> {
  public render() {
    return (
      <SimplePropertyGrid
        orientation={this.props.orientation}
        dataProvider={new PresentationPropertyDataProvider(this.props.imodel, this.props.rulesetId)}
      />
    );
  }
}

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (16.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-markdownlint|Dav|0.22.0
gitlens|eam|9.2.0
tslint|eg2|1.0.41
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
code-spell-checker|str|1.6.10

</details>

**Comment by daneast915** [comment]
TypeScript 3.0.0

**Comment by daneast915** [comment]
I need to clarify:

Our build is using TypeScript 3.1.6
VSCode 1.30.0 is using TypeScript 3.2.2

Switching to 3.2.2 for the build results in a couple of TS2345 errors, then our build stops. This TS2345 error did not occur with previous TypeScript versions.

error TS2345: Argument of type 'IArguments' is not assignable to parameter of type 'any[]'.
Type 'IArguments' is missing the following properties from type 'any[]': pop, push, concat, join, and 24 more.
error TS2345: Argument of type 'TDisposable[]' is not assignable to parameter of type 'TArg[]'.
Type 'TDisposable' is not assignable to type 'TArg'.
Type 'IDisposable' is not assignable to type 'TArg'.

**Comment by mjbvz** [comment]
Make sure you use the [same version of TypeScript in your workspace](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions).

I don't know about this specific compiler error but someone on stackoverflow may be able to help. If you believe it is a TS error, please file the issue against typescript
