### ISSUE TITLE
Support lazy resolving of SignatureInformation#documentation

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#65003]
If signature help returns lots of signatures and each have an documentation associated with it resolving the whole signature help can be time costly. Since we only show the documentation on user interaction lazy resolving this information would be beneficial.

**Comment by sean-mcmanus** [comment]
Yeah, our C/C++ extensions can encounter 20+ signatures (i.e. overloads), each of which requires a Go to Def to get the newly added doc comments, which can end up taking too long (e.g. 10+ seconds). Our current workaround is to only return the doc comment for the active signature.

**Comment by mjbvz** [comment]
@sean-mcmanus Is this still an issue for you? If so, could you explain a little more about why computing this information is so expensive? Maybe a more targeted fix can be made for your issue since it doesn't seem like this issue has gotten much traction over the last four years

**Comment by sean-mcmanus** [comment]
Yeah, it's still an issue, but we've worked around it via only returning doc comments for the active signature.

You could "Won't Fix" this if you want. It is some what low priority. It just impacts the documentation comment feature. We're tracking it in our repo at https://github.com/microsoft/vscode-cpptools/issues/6008 and it hasn't gotten any upvotes.

**Comment by mjbvz** [comment]
Thanks. I'm going to close this then since I don't see us getting around to it anytime soon

Just out of curiosity, since you already know the signatures, why does resolving the documentation for them take so long?
