### ISSUE TITLE
Do not steal Cmd + ` shortcut on Mac

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#6500]
- VSCode Version: 1.1.0
- OS Version: OX 10.11.4

Steps to Reproduce:

1. Open two VS Code editors
2. Toggle between them using Cmd + ` 

Expected: I should be able to switch between them
Actual: Instead it toggles Terminal inside the application.

**Comment by weinand** [comment]
@sandy081 I'm not seeing this in VS Code 1.1 on OS X (probably because I use a different keyboard layout).
Who is stealing the Cmd + ` shortcut?

**Comment by sandy081** [comment]
![Terminal] (https://cloud.githubusercontent.com/assets/10746682/15373731/42c7e6f4-1d47-11e6-9cd8-07ba1299cda9.png)

Here is the predefined keyboard short-cut 
{ "key": "cmd+`",                 "command": "workbench.action.terminal.toggleTerminal" },

Bad thing is that, even if I over-ride this with other shortcut say ctrl+` the previous one is still not released.

**Comment by sandy081** [comment]
@weinand There is already a bug filed for this  - https://github.com/Microsoft/vscode/issues/6481

Dup of https://github.com/Microsoft/vscode/issues/6481

**Comment by weinand** [comment]
@sandy081 that's the new integrated terminal (that is only visible in the alpha build).
