### ISSUE TITLE
images in preview does not work in v. 1.30

### ISSUE THREAD

**Issue by snielsson** [Microsoft/vscode#65000]
Images are not still not shown i preview as of version of VSCode is 1.30.0 - see image.

It does not matter how I open VS code on parent folder or not. So not sure this is a duplicate bug. 

Is there any work around for this - seems to have been a problem since 1.21

<img width="455" alt="screenshot_1" src="https://user-images.githubusercontent.com/739723/49942841-b5c01e00-fee6-11e8-8f3b-90eb064c7087.png">

**Comment by mjbvz** [comment]
What is the structure of your workspace? Where is the markdown file and where is the image?

**Comment by snielsson** [comment]
Hi again,

Thanks for your question which led me to an explanation and a workaround:

I have now tried different scenarios. Seems like the problem is due to the workspace being located on a windows UNC path, ie. a folder starting with "\\". If I move the folder to a local drive then it works. 

A workaround is to map a local drive to the network drive and then it works see link in the bottom  https://github.com/shd101wyy/markdown-preview-enhanced/issues/751

Although this problem has a workaround, a fix would be nice, but it is not high prio. Maybe a note on the documentation for markdown preview could be a start.

**Comment by mjbvz** [comment]
Thanks. I believe this is already tracked by #48403
