### ISSUE TITLE
1.30 : Extensions relying on global node do not find it

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#65002]
- VSCode Version: 1.30
- OS Version: MacOs Sierra

Steps to Reproduce:

Happen with eslint / flow and gitlens extensions. Install it and restart.
I worked like charm before 1.30 update.

**Comment by jrieken** [comment]
Can you provide some information? Most of us work with gitlens and there is nothing we miss with 1.30. So, please add a code snippet that reproduces this
