### ISSUE TITLE
In File explorer copy and paste goes to wrong folder

### ISSUE THREAD

**Issue by microhaxo** [Microsoft/vscode#65007]
- VSCode Version: 1.30
- OS Version: windows 7

Steps to Reproduce:

1. Have a project open with a decent amount of folder structure.
2. Copy the contents of a folder containing files from one area and paste them into the folder of another area (OR) copy the folder containing files from one area to another area in the explorer panel.

In my examples I've copied some models from one section of the app and moved them to a different section.

What happens is, the file explorer tree structure glitches out and visually where you thought you were pasting is not where it pastes the contents. It usually re-pastes them back from where you copied them. And the location where you wanted it to paste is selected but your files aren't there. You can keep right clicking and paste and nothing changes until you scroll down and see that you now have 4 copies of what you wanted to paste in the original location now. 
MOST times when i copy and paste a structure that is 2 levels deep, it wont paste it correctly.  Just copy and paste files from within folders to other folders and eventually you'll see it happen. Its been happening for months now and finally i've decided to say something since this latest update.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
In the next vscode version 1.31 we will ship a rewrite of the explorer
So closing this as will not fix
