### ISSUE TITLE
Allow debug adapter to control which frame to focus when stopping (eg. on exception)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#65012]
This is slightly related to #64193. The current expected behaviour is that VS Code walks up the stack frames and focuses the first frame that has source code (though it's not working correctly due to that bug).

However, assuming "the first frame with source" is the one that is most relevant isn't the best option. For example some languages/frameworks may ship source code for their internal libraries which means often the implementation of an `assert` method may have source - and this will result in the user looking at that implementation when it may be more appropriate to be looking at their call to it.

It would be best if the debug adapter could explicitly control which frame to focus when an exception is hit (most simply would probably be a flag on the frame for whether it should be excluded from auto-focus, and that flag used in place of the current "has source" check, but it could also make sense in the `StoppedEvent`).

**Comment by weinand** [comment]
In general this is a valid request.

However, I wonder how realistic it is for a debug adapter to determine the "best frame to focus on" without any help/hints coming from the user.

Based on this observation here is an alternative proposal based on an existing concept:

VS Code has already the concept of "uninteresting" source. This is surfaced in node-debug via the "skipFiles" glob attribute (which is not part of DAP). Whatever source matches that glob gets the special
[presentationHint](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source) `deemphasize`.

VS Code uses this hint to render stackframes in a dimmed style and collapses adjacent frames into one. We could easily extend VS Code notion of "deemphasize" sources by ignoring them when determining the best frame to focus on.

So in your case you could just return the `deemphasize` hint for source/frames that should not be focused. And if you can provide this hint even without introducing something like a "skipFiles" glob attribute, then even better.

**Comment by DanTup** [comment]
> However, I wonder how realistic it is for a debug adapter to determine the "best frame to focus on" without any help/hints coming from the user.

In this case I'm trying to focus on "user code" rather than "framework code", so I think the DA is best placed to know this.

> So in your case you could just return the deemphasize hint for source/frames that should not be focused.

We actually already set this to get the collapsed stack traces, so using this would be perfect for me. We even let the user control this by opting in to debugging framework code if they want, so this would also be more flexible.

**Comment by weinand** [comment]
So then let's go with this approach.
@isidorn please consider this when fixing #64193.

**Comment by isidorn** [comment]
@DanTup I have pushed a fix for this, please try it out in the insiders after we start updating it again after holidays (in 10 days).

**Comment by DanTup** [comment]
@isidorn Tested in insiders, and it now skips the `deemphasize` frames and goes to my source - thanks!

![screenshot 2019-01-03 at 3 58 50 pm](https://user-images.githubusercontent.com/1078012/50647453-7c705080-0f70-11e9-9239-933be63b85a7.png)

**Comment by isidorn** [comment]
Thanks for trying it out. Adding verified label
