### ISSUE TITLE
Visual studio misreads keyboard input when Ctrl is pressed (i.e Ctrl+Z) when using multiple keyboards with different layouts

### ISSUE THREAD

**Issue by mar-ses** [Microsoft/vscode#65015]
Issue Type: <b>Bug</b>

I am using a latop with a Swiss (German) keyboard layout, but I type on an external US (English) keyboard. I use the standard Ubuntu settings to switch between Swiss (German) and US (English) depending on which keyboard I'm using, and it seems to work with all other text editors.

However, in VSCode I am getting the following problem when I try to type on the external keyboard:

- When typing normal text, y and z are layed out as expected (in US English layout)
- When I try to Undo/Redo (Ctrl+Z/Ctrl+Y), the order of the Z and Y is swapped.

This means I need to press Ctrl+Y to Undo and Ctrl+Z to Redo. 

I checked the Keyboard Shortcuts under Preferences, and they are set to the expected configuration (i.e Ctrl+Z should be Undo, not Redo). Furthermore, when switching to my Swiss (German) keyboard, and switching the layout settings in Ubuntu, it also works as expected (on Swiss German keyboards, the Z and Y are swapped around).

It seems that when I hold Ctrl, visual studio code goes back to Swiss German layout or something. This doesn't happen with other editors, or when typing into a web browser. Only with Visual Studio Code.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.18.16-041816-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3252)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (7.14GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
latex-workshop|Jam|5.18.0
python|ms-|2018.11.0

</details>

**Comment by alexandrudima** [comment]
@mar-ses Have you seen the troubleshooting section in the wiki:

https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
