### ISSUE TITLE
Option to only offer "recovery"/stable updates

### ISSUE THREAD

**Issue by poshcodebear** [Microsoft/vscode#65019]
I didn't find this already open after a bit of searching, so I hope this isn't a duplicate...

Anyway, due to the occasional issues that come up in the initial release of a new version (1.##.0), some of which have caused problems like "VSCode won't launch" which keep people from working, it would be good to have the option to not get prompted for update until the "recovery" release comes out (1.##.1).  I don't think I've seen a single release that hasn't had a recovery release a few days later (which also means going through the update twice in a short period of time; another reason to just wait for the recovery).

**Comment by poshcodebear** [comment]
I know you're just a bot and you're doing the best you can, but that is just a merge comment :)

**Comment by joaomoreno** [comment]
Did you ever have a `VSCode won't launch` issue on a stable release/

**Comment by joaomoreno** [comment]
You can get this by simply disabling automatic updates and manually updating when a recovery release comes up.
