### ISSUE TITLE
Apply excludes to editor history quick open too

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6502]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Related #3615

Steps to Reproduce:

I'm working in the smoke test repo ([link](https://github.com/Microsoft/vscode-smoketest-express))
1. Use quick open `Ctrl+P` to open some files in node_modules folder (I just used index.js as it occurs a lot)
2. Add in settings

``` json
"search.exclude": {
    "**/node_modules": true
}
```
1. Use `Ctrl+P` type 'index.js'

The list of recent files still includes files located in /node_modules. I found a previous thread that says using `Ctrl+K W` will remove them, but excluding them in user settings should also apply to recently opened files without having to use a command to close/remove them.

**Comment by bpasero** [comment]
We should apply the excludes to the editor history too.

**Comment by ChuckJonas** [comment]
+1 on fixing this...

**Comment by ChuckJonas** [comment]
I was very committed to using VS Code (authored 3 plugins for apex development and contributed to a 4th) but I'm sad to say abandoning it for now... 

This bug killing my productivity (even caused me to introduce a production bug) and there is no viable work around.

Once you open an search excluded file, it will always seem to pop-up ahead of search included files.  Even, if I exclude the file from the project, it still shows up.

**Comment by bpasero** [comment]
@ChuckJonas as a workaround there is a command "Clear Editor History" (removes all) and "Remove from Editor History" to remove an individual entry.

**Comment by Xerillio** [comment]
@bpasero Thanks for the workaround, I just bumped into this issue in v.1.17.1
I see this issue has been closed, so is there no plan to apply the exclude setting on the history?
