### ISSUE TITLE
No snippets when using tab completion, matching many snippets, not showing snippets in suggest

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#65027]
Issue Type: <b>Bug</b>

```json
"editor.tabCompletion": "onlySnippets",
"editor.snippetSuggestions": "none",
```
Pressing <kbd>Tab</kbd> gives `No suggestions.`

VS Code version: Code - Insiders 1.31.0-insider (7ab53e6d1c7998006bc70f18230178a702598222, 2018-12-13T06:20:30.449Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
in which languages? custom snippet? errors?

**Comment by usernamehw** [comment]
Not a regression. I somehow have 2 similar snippets in 2 files:

#### `typescript.json`
```json
"snippet": {
	"prefix": "snippet",
	"body": "body"
}
```
#### `all.code-snippets` <- global
```json
"snippet": {
	"prefix": "snippet",
	"body": "body"
}
```

**Comment by usernamehw** [comment]
Expected behavior is to insert scoped snippet (the one from `typescript.json`).

**Comment by jrieken** [comment]
> Expected behavior is to insert scoped snippet (the one from typescript.json).

No, the expected behaviour is that it shows IntelliSense with all snippets that match the prefix. That's how it works for me. Does it not show that for you?

**Comment by usernamehw** [comment]
`"editor.snippetSuggestions": "none",`

**Comment by jrieken** [comment]
tough luck...

**Comment by skprabhanjan** [comment]
@jrieken , Can i take a look at this ?

**Comment by usernamehw** [comment]
I just don't think this worth it. Pretty rare configuration with a specific mix-up of global & local snippet.
