### ISSUE TITLE
Cannot find a program to debug on 1.30 but works on 1.29

### ISSUE THREAD

**Issue by ryanpage42** [Microsoft/vscode#65020]
- VSCode Version: 1.30
- OS Version: Mac OS Mojave

Steps to Reproduce:

1. The debug configuration fails on 1.30 but not 1.29 and prints "Cannot find a program to debug" when I click the "Start Debugging" button

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "project",
            "protocol": "inspector",
            "args": ["${workspaceFolder}/project/dist/src/server.js"],
            "runtimeArgs": [
                "--nolazy",
                "-r",
                "ts-node/register"
            ],
            "cwd": "${workspaceFolder}/project/",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "preLaunchTask": "link"
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes

I'm not too sure what changed that led to this debug configuration to start failing but the error message regardless is not helpful much.

**Comment by VictorVicente** [comment]
Same problem here, same OS and VSCode versions.

**Comment by andokai** [comment]
Just to add that this also happens when attempting to start debugging from the touch bar on a MacBook Pro

**Comment by isidorn** [comment]
This is a duplicate and the fix will be done as part of the recovery release in a couple of days.
Sorry about that

Dup of https://github.com/Microsoft/vscode/issues/64450
