### ISSUE TITLE
settings.json unnecessarily opens twice

### ISSUE THREAD

**Issue by importnetminecraft** [microsoft/vscode#65032]
Issue Type: <b>Bug</b>

1. Go to UI Settings
2. Press Open Settings (JSON) button
3. Navigate back to settings tab
4.  Press "Open Settings (JSON)" button or press "Edit in settings.json" link

settings.json is opened again in another split unnecessarily. Default settings just switches tabs so it is inconsistent.

VS Code version: Code - Insiders 1.31.0-insider (7ab53e6d1c7998006bc70f18230178a702598222, 2018-12-13T06:20:30.449Z)
OS version: Windows_NT x64 10.0.17763

**Comment by cedric05** [comment]
can i work on it? 
@roblourens

**Comment by roblourens** [comment]
Apparently fixed now
