### ISSUE TITLE
1.30 on linux picks wrong locale

### ISSUE THREAD

**Issue by gudvinr** [Microsoft/vscode#65037]
- VSCode Version: 1.30
- OS Version: Linux 4.19.8-arch1-1-ARCH  x86_64; KDE 5.14

Steps to Reproduce:

1. Open any other terminal running bash (Konsole, Terminator) and see this:
```
$ locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT=C
LC_IDENTIFICATION="C"
LC_ALL=
$ ls /not
ls: cannot access '/not': No such file or directory
```
2. Open integrated terminal in VSCode and you'll see that:
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=C
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ ls /not
ls: невозможно получить доступ к '/not': Нет такого файла или каталога
```

I have `terminal.integrated.setLocaleVariables` set to `false`. I'm not sure if it became a thing in 1.30 but probably yes.

Does this issue occur when all extensions are disabled?: Yes (And I have zero extensions related to locales).

**Comment by Tyriar** [comment]
I made a change to make the default true to all platforms and removing the fallback when setLocaleVariables is false, so setting it to `terminal.integrated.setLocaleVariables` set to false should leave your setup alone.

**Comment by gudvinr** [comment]
@Tyriar 
Yep, that works.
Hope to see that in 1.30.1

**Comment by dbaeumer** [comment]
Marking as verified based on comment https://github.com/Microsoft/vscode/issues/65037#issuecomment-447502952
