### ISSUE TITLE
Cannot maximize, minimize, or move the window when exported to remote X11 display on version 1.30.0-1544567151 

### ISSUE THREAD

**Issue by phenixrizen** [Microsoft/vscode#65036]
Steps to Reproduce:

1.  I'm running Ubuntu 18.04
2.  I updated the code package to version 1.30.0-1544567151 via apt
3.  I exported my X display to a remote X11 server
4.  I then cannot maximize, minimize, or move the code window

My current solution is to downgrade:
```bash
sudo apt install code=1.29.1-1542309157
```

**Comment by Tyriar** [comment]
This might help:

```
"window.titleBarStyle": "native"
```

**Comment by phenixrizen** [comment]
@Tyriar that works. Thanks!

**Comment by sbatten** [comment]
Thanks @Tyriar

Those using vs code with remote x forwarding will need to change their titlebar style setting to `native` as @Tyriar suggested [above](https://github.com/Microsoft/vscode/issues/65036#issuecomment-447188895).

**Comment by sbatten** [comment]
added
