### ISSUE TITLE
[Windows 10] Title bar permanently white after recent update.

### ISSUE THREAD

**Issue by Joe-Pena** [Microsoft/vscode#65034]
- VSCode Version: 1.30
- OS Version: Windows 1809

Steps to Reproduce:

1. Update to vscode 1.30
2. vscode title bar is now white, changing settings in window.titleBarStyle to "native" or "custom" doesn't have an effect, even after restart.

Does this issue occur when all extensions are disabled?: Yes
![screenshot 7](https://user-images.githubusercontent.com/37708646/49972486-10f60e80-feef-11e8-9b2e-b92c5b0bd95d.png)
![screenshot 8](https://user-images.githubusercontent.com/37708646/49972487-10f60e80-feef-11e8-97f1-e30a11dcfc3c.png)

**Comment by Joe-Pena** [comment]
I toggled the window.smoothScrollingWorkaround option and that fixes it, however, now I cannot have window.smoothScrollingWorkaround enabled while window.titleBarStyle is set to "custom", but this set up used to work perfectly fine before the update.

**Comment by sbatten** [comment]
@Joe-Pena the smooth scrolling fix had no effect with the custom title bar in the past. If you were not having issues with the custom titlebar in the past release, you should be fine to disable it now.

**Comment by sbatten** [comment]
In the previous version, the check was not in place to disable the custom title bar though it should have been because if your machine needs the workaround, the custom title bar would make it ineffective. You must now disable the smooth scrolling workaround in order to use the custom title bar.
