### ISSUE TITLE
Allow extension contributed TS plugins to be loaded for workspace versions of TS

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#65031]
**Background**
Extension contributed typescript plugins are currently only loaded when you are using the bundled version of TS. This is done for compatibility reasons: a malfunctioning ts plugin can break all intellisense and we were concerned that many plugins may not be compatible with older versions of TS that users have installed in their workspace. 

The current solution requires that users install the plugin in their workspace if they are using a workspace version of TS

**Proposed fix**
1. TS plugins should check the TS version at run time and not enable themselves if the TS version is too old

1. We will add a `enableForWorkspaceTypeScriptVersions` flag to the plugins contribution section. This opt-in flag will allow the plugin to be loaded when using workspace versions of TS. Only plugins that do part 1 should set this flag

**Comment by minestarks** [comment]
Thanks!

**Comment by cyrilletuzi** [comment]
@mjbvz Is there an example somewhere of how to do part 1?

Also, I was thinking of the opposite issue: a newer bundled version of TypeScript could break a plugin too. For example, Angular comes with the TypeScript plugin `@angular/language-service`, but Angular supporting newer versions of TypeScript take more time than VS Code.

**Comment by mjbvz** [comment]
To verify:

1. Install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin
1. In a workspace, switch to using a workspace version of TypeScript (3.1+)
1. Verify that tslint errors are still reported without needing any extra configuration
