### ISSUE TITLE
Language-specific commands are not showing up if file is already opened on load 

### ISSUE THREAD

**Issue by queeniema** [Microsoft/vscode#65041]
Issue Type: <b>Bug</b>

This is happening in the new 1.30.0 release but is not happening in 1.29.1.

I have defined a command in my `package.json` that is to be shown in the editor context menu for specific language files.

```
"editor/context": [
    {
        "command": "test.command",
        "when": "resourceLangId == spl"
    },
    ...
]
```

If I have a file of type `.spl` open and I reload VS Code, then the context menu does not show the command. If I open a new file of type `.spl`, then the command appears.

However, if I remove the `"when": "resourceLangId == spl"` specification from `package.json`, then the command appears.

Note: I have `activationEvents` set to `[ "*" ]`.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv|-psn_0_1634703|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DonJayamanne** [comment]
Same problem in Python extension (we can repro this at our end).

**Comment by alexandrudima** [comment]
@jrieken I don't think any fundamental changes went into `contextmenu.ts`, perhaps something changed in the menu service?

**Comment by jrieken** [comment]
The menu is computed properly but the `resourceLangId` isn't set. Not really sure why that is...

<img width="269" alt="screenshot 2018-12-18 at 10 34 16" src="https://user-images.githubusercontent.com/1794099/50144905-95121280-02b0-11e9-81c3-7a3647552d0c.png">

**Comment by jrieken** [comment]
This might have been caused by 8136239d17549061f13909028083315fc91dfa47 which adds an identity check so that we don't repeatedly update the resource context key. I will push a change that makes sure we listen on mode changes - something we should have done from the beginning.
