### ISSUE TITLE
[pug] add auto indent

### ISSUE THREAD

**Issue by joexmdq** [microsoft/vscode#65044]
- VSCode Version: 1.30.0
- OS Version: Windows 10 x64 (1803)

The auto indentation when using pug is not working. Here is an example of **VSCode** (1.30.0) vs **Sublime Text** (3.1.1) and **Atom** (1.33.0) showing the expected behavior:
![example_plug_image](https://user-images.githubusercontent.com/45812155/49979590-75848e00-ff2e-11e8-96cc-a0039fe3b94b.png)

And here a gif showing what happen in each one while typing (the **tab** and **space** keys **were not used**):
![example_pug-2-3](https://user-images.githubusercontent.com/45812155/49979598-787f7e80-ff2e-11e8-9d1d-5d82b6644a43.gif)

Steps to Reproduce:

1. Open a tab and select Pug syntax
2. Type some tags like the next example **without** using **tab** or **space** keys:
```
h1 test
.example
    ul
        li
```

Does this issue occur when all extensions are disabled?: Yes
<details>
  <summary>Extensions enabled:</summary>
  
- advanced-new-file
- Bookmarks
- Bracket Pair Colorizer
- Code Spell Checker
- colorize
- Identical Sublime Monokai C# theme and colorizer
- Path Autocomplete
- Relative Path
- Sublime Text Keymap and Settings Importer
</details>

**Comment by joexmdq** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Pug Highlighting Doesn't Recognize Inline Blocks (#62817)](https://www.github.com/Microsoft/vscode/issues/62817)

It is another bug of the Pug syntax that can be appreciated in my example, but the issue is different since mine is about auto indentation.

**Comment by octref** [comment]
That's because pug has no indentation rules:

https://github.com/Microsoft/vscode/blob/master/extensions/pug/language-configuration.json

PR welcome. The doc for language configuration is not published but can be found here: https://github.com/Microsoft/vscode-docs/blob/8e2d55b0bef13a919324e836275bcf26f961bf64/api/language-extensions/language-configuration-guide.md

**Comment by timdmackey** [comment]
Okay, so I found a complete regex pattern for pug in the original repo that vscode's pug extension is based on: [davidrios/pug-tmbundle](https://github.com/davidrios/pug-tmbundle)

Here's the the original regex definition (from [/Preferences/Miscellaneous.tmPreferences](https://github.com/davidrios/pug-tmbundle/blob/master/Preferences/Miscellaneous.tmPreferences))
```
(?x) # enable free-spacing and comments
^\s*(  # start with any whitespace
    ([\w#.-]+(\(.*?\))?  # first tag
    (:\s*[\w#.-]+(\(.*?\))?)*  # additional tags
    \.?$)  # end tag with . or end of line
    |(:[a-z]\w*($|\())  # filters
    |(//-?$)  # multiline comments
    |(-\s+(if|else|while)(\s+|$))  # embedded js control flow
    |((for|if|else if|else|each|until|while|unless|case|when|block|append|prepend)(\s+|$))  # pug block first-class
)
```

I reformatted the regex pattern, removing the comments, newlines, and free-spacing mode modifier, and properly escaped everything. It appears to be working correctly based on my testing. Anyone else care to try it out?

I made a pull request with the incorporated changes: https://github.com/Microsoft/vscode/pull/66099

**Comment by JordashTalon** [comment]
@timdmackey Where would you include those regex definitions? Is it in settings.json?

**Comment by tarasfigol** [comment]
I found solution!
VSCode internally identifies .pug files as jade (from the older name of the Pug templating language). Because of this, configurations specifically targeting pug may not work as expected.

To fix this, you can add the following to your keybindings.json file:
```
{
    "key": "enter",
    "command": "editor.action.insertSnippet",
    "when": "editorLangId == 'jade'",
    "args": {
        "snippet": "\n\t$0"
    }
}
```

**Comment by aeschli** [comment]
Yes, for historical reasons the Pug language id is still `jade`. When the language was renamed, we didn't want to break existing extension for `jade`
