### ISSUE TITLE
vscode cannot connect to extensions marketplace

### ISSUE THREAD

**Issue by bhaskar-shrestha** [Microsoft/vscode#65045]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

This is what I get when searching for extensions in vs code, windows 10.
![image](https://user-images.githubusercontent.com/44758004/49981556-8aa00200-ffac-11e8-845e-b43b4547a9a0.png)

below is the error message I get. I tried reinstalling vscode but same thing.

Currently, I am using https://marketplace.visualstudio.com/ to get new extensions.

![image](https://user-images.githubusercontent.com/44758004/49981455-20875d00-ffac-11e8-8b24-29b36946d92b.png)

**Comment by sandy081** [comment]
@bhaskar-shrestha Do you see this always or only when looking for some extensions?

**Comment by bhaskar-shrestha** [comment]
This error is always present, even if I am trying to search and already installed extension.

**Comment by sandy081** [comment]
You mean even when you do not search (i.e, when the search box is empty) ?

**Comment by sandy081** [comment]
@bhaskar-shrestha Can you please try using a different extensions-dir? You can do that using cli argument `--extensions-dir`.

**Comment by bhaskar-shrestha** [comment]
I tried that using a brand new empty folder/directory. The result is the same.

I tried a different variation with creating a new folder and using `code . --extensions-dir .` with same results

**Comment by sandy081** [comment]
Just to be sure, you see the error in default extensions view right? May I know which version of VS Code are you using? And can you please try with insiders and see if you can reproduce it too https://code.visualstudio.com/insiders/ ?
