### ISSUE TITLE
"-" character doesn't work for triggering snippets

### ISSUE THREAD

**Issue by insominx** [Microsoft/vscode#6504]
- VSCode Version: 1.1.1
- OS Version: win 10

Steps to Reproduce:
1. Add this snippet
   {
   "Method Comment Header": {
       "prefix": "--",
       "body": [
           "// -------------------------------------------------------------------------",
           "\t$1"
       ],
       "description": "Method Comment Header"
   }
   }
2. Try to trigger it via "--"
   It does not work
3. Try triggering via normal letter characters, say "hh"
   Works fine.

**Comment by aeschli** [comment]
The proposal is actually in the list, but even when entering --, it is at the very last:
![image](https://cloud.githubusercontent.com/assets/6461412/15471734/d9aa6d7c-20f7-11e6-90cd-1a8ad3140729.png)

@joaomoreno @jrieken Joh or Joao?

**Comment by jrieken** [comment]
@aeschli Is the issue that the snippet isn't revealed when typing `--`?

**Comment by aeschli** [comment]
It's not selected. You have to scroll down and look for it and select it yourself.
Thats how it looks after Ctrl+Space:
![image](https://cloud.githubusercontent.com/assets/6461412/15472137/f34ead5e-20f9-11e6-822d-4e6c3ed1b00b.png)

**Comment by jrieken** [comment]
assigning to @joaomoreno who knows how to select

**Comment by joaomoreno** [comment]
Current word madness.

**Comment by jrieken** [comment]
oh, `-` is for sure nowhere a word

**Comment by joaomoreno** [comment]
Yeah, the selection algorithm is selecting the empty string as the current word for sure.

**Comment by jrieken** [comment]
We made filtering already independent of the currentWord but use text selected by `overrideBefore` (which default to the current word). In effect filtering is now custom to each suggestion. I wonder if we can do the same for selecting the best match.

**Comment by jrieken** [comment]
The problem here is that trigger 24x7 IntelliSense only when a word is being typed. Characters like `-` or `#` usually aren't part of a word, at least not with the word definition of that language. Unsure what to do about this...

**Comment by jrieken** [comment]
Closing this as designed. The 24x7 IntelliSense feature works by detecting when a *word* is being typed. What a word is depends on the language being used and can be set by that language. I don't think we should temper with that word-behaviour in favour of some snippets. 

This is what you can do:

* use tab completion after typing `--`
* use insert snippet from F1
* invoke intellisense manually and type `--`


Thanks for understanding and Happy Coding
