### ISSUE TITLE
vs code can not connect the marketplce in China

### ISSUE THREAD

**Issue by JackZhouMine** [Microsoft/vscode#65042]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

I updated vs code to the lastest,bu i can not connect marketplace ,why? i can use google by Shadowscoks ,and others blocked websites as well. Some people have the same problem.
my computer info :
版本: 1.29.1 (system setup)
提交: bc24f98b5f70467bc689abf41cc5550ca637088e
日期: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64

**Comment by sandy081** [comment]
@JackZhouMine Can you please open `F1 -> Toggle Developer Tools` and see if there are any errors in the console?
