### ISSUE TITLE
Strarup time is very slow

### ISSUE THREAD

**Issue by rubendeblas** [microsoft/vscode#65053]
Issue Type: <b>Performance Issue</b>

Strarup time is very slow

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v5 @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (11.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    84	  7276	code main
    0	    73	  9000	   gpu-process
    0	   161	  9268	   window (vs-lives-hare - Visual Studio Code [Administrador])
    0	    35	   940	     searchService
    0	    10	  1000	     watcherService 
    0	    11	  9604	     electron-crash-reporter
    0	   110	  9788	     extensionHost
    0	    37	  7644	       C:\Users\E534952\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.1013\dotnet_modules\vsls-agent.exe --autoexit --pipe 382a5b4c291f4abe8b87efd24831add0 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	    37	 10108	       electron_node server.js 
    0	    99	  9496	   shared-process
    0	    23	  9884	   utility
    0	    67	 10052	   window (Reportero de tema)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (vs-lives-hare - Visual Studio Code [Administrador])
|    Folder (vs-lives-hare): 1 files
|      File types: json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
Bookmarks|ale|10.0.0
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
css-minify|Die|0.1.10
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.4.7
html-tag-wrapper|hwe|0.2.3
smarty|imp|0.3.0
tag-inserter|l7s|1.4.0
vscode-ariatemplates-highlighter|max|0.2.2
easy-less|mrc|1.4.5
vscode-language-pack-es|MS-|1.30.2
atom-keybindings|ms-|3.0.4
vsliveshare|ms-|0.3.1071
material-icon-theme|PKi|3.6.1
vscode-css-peek|pra|2.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.3.1
sass-indented|rob|1.4.9
templex|sle|0.1.1
watch-in-chrome|sne|0.0.2
code-spell-checker|str|1.6.10
code-spell-checker-spanish|str|1.0.1
tplove-extension-pack|tap|1.1.0
tplove-snippets|tap|1.3.3
open-in-browser|tec|2.0.0
vscode-lua|tri|0.12.4
highlight-matching-tag|vin|0.8.4
swig-tpl|zha|0.0.6
html-css-class-completion|Zig|1.17.1

</details>

**Comment by weinand** [comment]
Do you experience "slow startup time" even if you launch with all extensions disabled?

**Comment by weinand** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
