### ISSUE TITLE
Pressing Alt leads to focusing on the editor menu

### ISSUE THREAD

**Issue by mil-ast** [microsoft/vscode#65056]
Issue Type: <b>Feature Request</b>

If at the time of writing the code to press Alt, for example, to switch layouts (Alt + Shift), then continue to continue to type text / code in the editor. It is necessary to put the mouse with the mouse and continue to work.

Ubuntu 18,04

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

---

**Original title**: Нажатие Alt приводит к фокусировки на меню редактора
**Original content**:
Если во время написания кода нажать Alt, например, для переключения раскладки (Alt+Shift), то дальше продолжить набирать текст/код в редакторе невозможно. Приходится мышкой ставить курсор и продолжать работать.

---

**Comment by ex1st** [comment]
Translate: Editor loses the focus when a user does switch a language (alt+shift/ctrl for example).

**Comment by mjbvz** [comment]
> If at the time of writing the code to press Alt, for example, to switch layouts (Alt + Shift), then continue to continue to type text / code in the editor. It is necessary to put the mouse with the mouse and continue to work.

**Comment by ex1st** [comment]
Hello @alexandrudima, I can confirm that. Input lost a focus also.

**Comment by tzurbaev** [comment]
I can confirm this issue exists on Ubuntu 17.10 with 1.30.1:
```
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
ОS: Linux x64 4.13.0-46-generic
```
If you're switching input language with `alt+shift` combination and pressing `alt` first (press&hold `alt`, press `shift`, release both), editor will lose focus on editor window & activate topbar menu.

@alexandrudima not OP, but `alt+shift` in search box leads to losing focus too.

**Comment by tzurbaev** [comment]
This bug was introduced in f9a9e4e748b84c08b19b2c7f82954b559792d133 by defaulting `window.titleBarStyle` value to `native` (from `custom`). You can revert it by creating `"window.titleBarStyle": "native"` entry in your user configuration file (`CTRL+,`).

I guess the main source of such behaviour (losing focus on `alt` keydown with custom menus) lies in the electron codebase, but I'm not familiar with it.

**Comment by sbatten** [comment]
on windows, holding shift with alt to focus the menu is acceptable, but that doesn't appear to be the case on linux, so i'll try to make this better on linux.

**Comment by sbatten** [comment]
not that I expect anyone to relearn the way they hit shortcuts, but as a workaround, if you hit alt, then shift instead of shift, then alt, the menu bar won't be focused.

**Comment by PinkaminaDianePie** [comment]
@tzurbaev Thank you, `"window.titleBarStyle": "native"` works! It brings back old UI, but making editor stay focused on `alt` is much more important than fancy menus :)

**Comment by sbatten** [comment]
there are several ways to address this today. Firstly, linux uses native titlebar by default. If you happen to use custom titlebars still, then, secondly, you can use `window.customMenuBarAltFocus` to disable alt focus of the menu bar.

**Comment by yndx-shri-reviewer** [comment]
I still have this bug =(
`"window.titleBarStyle": "native"` and disabling `window.customMenuBarAltFocus` have no effect.

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic
```

**Comment by phenotropili** [comment]
I still have this bug =(
`window.titleBarStyle: "native"` and disabling `window.customMenuBarAltFocus` have no effect.

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic
```

**Comment by sbatten** [comment]
@phenotropili note the setting is specific to the custom menubar and the native experience is controlled by electron
