### ISSUE TITLE
Custom language settings for zenMode don't work

### ISSUE THREAD

**Issue by GammaGames** [Microsoft/vscode#65050]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Add the following to your `settings.json`:
```json
    "[markdown]": {
        "zenMode.hideTabs": true
    },
```
2. Open a markdown file
3. Observe that there are still tabs

![screenshot from 2018-12-13 23 07 53](https://user-images.githubusercontent.com/7832163/49986161-060d9f00-ff2c-11e8-9b65-ab4bb517d415.png)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz (8 x 3482)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (2.59GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-css-formatter|aes|1.0.1
devhints|brp|0.2.1
bracket-pair-colorizer-2|Coe|0.0.25
comment-anchors|Exo|1.6.1
vs-code-xml-format|fab|0.1.5
vscode-github-notifications-bell|fab|2.1.5
auto-close-tag|for|0.5.6
godot-tools|gee|0.3.7
svgeditor|hen|2.8.0
vscode-cdnjs|Jak|0.14.3
hungry-delete|jas|1.5.0
vscode-dashboard|kru|1.2.0
vscode-format-context-menu|lac|1.0.4
eml|lei|0.3.1
vale|lun|0.6.0
linecounter|lyz|0.2.2
rainbow-csv|mec|0.8.0
python|ms-|2018.12.0
cpptools|ms-|0.20.1
wordcount|ms-|0.1.0
vscode-paste-image|mus|1.0.3
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.4.0
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.6.1
vscode-sort-json|ric|1.13.0
block-travel|sas|0.0.2
MDTools|sea|1.0.1
code-settings-sync|Sha|3.2.4
standard|shi|0.2.3
gitconfig|sid|2.0.0
code-spell-checker|str|1.6.10
ninja|sur|0.0.1
vala|thi|0.3.2
write-good-linter|tra|0.0.9
lorem-ipsum|Tyr|1.2.0
sort-lines|Tyr|1.7.0
use-strict-everywhere|vee|0.1.3
highlight-matching-tag|vin|0.8.4
gitblame|wad|2.6.3
sysinfo-vscode|wra|1.2.1
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.8.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Only editor settings can be over-ridden using Language specific settings. Others are not supported.

**Comment by GammaGames** [comment]
Isn't zen mode an editor setting? It's not from an extension

**Comment by sandy081** [comment]
Sorry for not being clear. Editor settings are those belong to the `text editor` VS Code, to be clear those starts with `editor.` 

![image](https://user-images.githubusercontent.com/10746682/50107431-00b59a80-0233-11e9-9958-cf6b482a1b1c.png)
