### ISSUE TITLE
Add a "recenty used input" to user inputs for tasks.

### ISSUE THREAD

**Issue by N-Bz** [microsoft/vscode#65066]
### Rationale:

The "Task: Run Task" picker puts the most recently used task as the first one in the list (with other recently used tasks), which makes it easy to re-run the same task without typing.

The same behavior is not present for the input pickers (both `"pickString"` and `"promptString"` pickers), which makes it harder to re-run the same task if the arguments were not the default ones.

### Details:

Consider the following tasks.json file:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo free",
			"type": "shell",
			"command": "echo ${input:any}",
			"problemMatcher": []
		},
		{
			"label": "echo list",
			"type": "shell",
			"command": "echo ${input:list}",
			"problemMatcher": []
		}
	],
	"inputs": [
		{
			"id": "list",
			"description": "arguments in a list",
			"default": "a",
			"type": "pickString",
			"options": [ "a", "b", "c" ]
		},
		{
			"id": "any",
			"description": "any arg",
			"default": "",
			"type": "promptString"
		}
	]
}
```

If my development workflow requires me to run "echo list" with argument "c" frequently (i.e. building a specific module in a big project), I can quickly find the right task (it is likely at the top of the recently used tasks inside the Run Task picker), but I will still have to lookup or type the argument (and in my real-life use case, the argument is not a single letter, and the list has ~150 elements). Having a "recenty used input" list would be helpful for this.

The same goes for a "echo free"-like task (I have this case passing custom arguments to a build system script, as I would do in a shell, but with a problemMatcher parsing the output), but as the arguments are not selected from a list, the number of "recently used inputs" would probably have to be limited to a sane level.

**Comment by alexr00** [comment]
There's a Rerun Last Task command, where if you set the task's `"runOptions": { "reevaluateOnRerun": false}` you'll be able to run the last task with the same input. I know that's not quite what you're asking for here, but it might help for now.

**Comment by julian-poidevin** [comment]
I also needed that functionality, for now the `reevaluateOnRerun` setting is fine, thanks !

**Comment by alexr00** [comment]
Related https://github.com/microsoft/vscode/issues/72944

**Comment by muman613** [comment]
Here it is May 2020 and this feature is still not available? I have a use-case which needs the selection of the user to be remembered. In our case we need to get the branch name to update from git, but each user of the tasks.json may be working on other branches. We should be able to remember the last value used to avoid having the user re-select the branch.

**Comment by JustinGrote** [comment]
@alexr00 with input variables supported in debug configurations, there is no "rerun last debug" that remembers it.

A common use case is manually specifying which test I want to run in `golang`, but I have to type it every single time instead of being able to "rerun last debug"

**Comment by jamie-pate** [comment]
If we are entering passwords etc, maybe they could be remembered until next time you start the editor? Unless there's a way to load them from a separate file that doesn't get checked into source control.

**Comment by JakeShirley** [comment]
+1 for this option.  I love having my launch files be configurable in different environments but man is it a pain to re-paste in paths and what not every single time.  At least a session-based cache would be great.

**Comment by bryceschober** [comment]
I apologize for not following up on this feature request after satisfying my own related needs.

I have found that the ["Memento Inputs" (`spadin.memento-inputs`) extension](https://marketplace.visualstudio.com/items?itemName=spadin.memento-inputs) fills my related use-case needs quite well.

**Comment by JakeShirley** [comment]
@bryceschober wow that's exactly what I wanted.  Thanks a ton for the link!

**Comment by denniskb** [comment]
+1 even just remembering the last input per task would be a great help!

**Comment by meganrogge** [comment]
Related: https://github.com/microsoft/vscode/issues/131128

**Comment by meganrogge** [comment]
After investigation, I don't think this is something we need to build into core given @alexr00 's suggestion fixes this issue for running tasks. 

```
"runOptions": { "reevaluateOnRerun": false}
```

This is separate from the debug issue mentioned above. As for that, doesn't `workbench.action.debug.restart` work?

**Comment by meganrogge** [comment]
For the use case mentioned at the start of this issue, creating a task specifically for the command you want to run would avoid having to choose from a long list of inputs.
