### ISSUE TITLE
Black window when starting with external monitor ( notebook is closed )

### ISSUE THREAD

**Issue by JulianRot** [Microsoft/vscode#65061]
Notebook is running attached to docking station, using external monitors, notebook monitor is closed. When I start VS Code  a window opens, but it stays black until I open the notebook monitor, then it works. VS Code starts up without problems, when I just use the notebook (without docking station and external monitors).

CPUs | Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 31.82GB (25.41GB free)
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
vscode-languagetool | ada | 3.8.0
vscode-languagetool-en | ada | 3.8.0
vscode-color | ans | 0.4.5
swagger-viewer | Arj | 2.1.0
vscode-eslint | dba | 1.7.2
githistory | don | 0.4.4
xml | Dot | 2.3.2
tslint | eg2 | 1.0.41
vsc-material-theme | Equ | 2.6.2
semantic-data-model-language | fan | 0.0.1
code-runner | for | 0.9.5
vscode-atom-javascript-snippet | glu | 0.2.1
todo-tree | Gru | 0.0.109
vscode-cypher-ql | ion | 0.0.2
docthis | joe | 0.7.1
sftp | lix | 1.8.3
vscode-filesize | mkx | 2.1.1
theme-monokai-pro-vscode | mon | 1.1.9
vscode-cosmosdb | ms- | 0.9.1
python | ms- | 2018.12.0
azure-account | ms- | 0.7.0
csharp | ms- | 1.17.1
debugger-for-chrome | msj | 4.11.1
vscode-docker | Pet | 0.4.0
remote-vscode | raf | 1.1.0
LiveServer | rit | 5.3.1
vscode-icons | rob | 7.28.0
markdown-preview-enhanced | shd | 0.3.11
stardog-rdf-grammars | sta | 0.0.6
html-preview-vscode | tht | 0.2.5
shell-launcher | Tyr | 0.2.0
quokka-vscode | Wal | 1.0.174
markdown-pdf | yza | 1.2.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
