### ISSUE TITLE
Custom title and menu bar on Windows 7 not dark

### ISSUE THREAD

**Issue by jmsnavarro** [Microsoft/vscode#65067]
- VSCode Version: 1.30.0
- OS Version: 6.1

Steps to Reproduce:

1. File > Settings > "window.titleBarStyle" = "custom"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
@jmsnavarro please provide a screenshot of your experience

**Comment by jmsnavarro** [comment]
Hi @sbatten , below is my current screenshot of vscode 1.30.0

![image](https://user-images.githubusercontent.com/17264947/50042253-763b3280-009c-11e9-9e8f-7b92c2935abb.png)

**Comment by sbatten** [comment]
@jmsnavarro please check your setting for `window.smoothScrollingWorkaround`. If enabled, it will disable the custom title bar due to incompatibilities.

**Comment by jmsnavarro** [comment]
Hi @sbatten , that works! Cheers!
