### ISSUE TITLE
Getting error message when adding file to explorer and performing move, rename and delete operations.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6506]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open smoke test project folder.
2. Perform smoke test steps (add .txt file in explorer them move and delete).
https://github.com/Microsoft/vscode/wiki/Smoke-Test

Actual: Getting error message when deleting Readme.txt or application crashed.
![image](https://cloud.githubusercontent.com/assets/17735796/15379023/84fb82a8-1d1d-11e6-9869-8f6770e48699.png)

**Sometime App crashed:**
![appcrashed](https://cloud.githubusercontent.com/assets/17735796/15379385/89caf4c2-1d21-11e6-9618-b1ba7ee9d720.gif)

**Comment by weinand** [comment]
@v-pavanp this branch is work in progress and not yet meant for testing.
