### ISSUE TITLE
VSCode API: An inline inputs on specific lines

### ISSUE THREAD

**Issue by agjs** [Microsoft/vscode#65076]
I'd like to apologize upfront for asking the question in here, going against guidelines. I have asked this same question on Stackoverflow a week ago and had no response. For that reason, I've decided to try here.

Not to write the same stuff again, please use the link below. 

https://stackoverflow.com/questions/53668684/vscode-api-an-inline-inputs-on-specific-lines

**Comment by jrieken** [comment]
@agjs Is this like the Github PR extension we have? Being able to comment inline?

**Comment by agjs** [comment]
Wow, I haven't seen this one and yes, that's exactly what I need.

**Comment by jrieken** [comment]
Ok - that API is currently proposed. That means its usage is very restricted but not impossible for 3rd parties. See https://github.com/Microsoft/vscode/wiki/Extension-API-process#about-proposed-api. We are happy get your feedback on this.

**Comment by jrieken** [comment]
This is the interesting portion: https://github.com/Microsoft/vscode/blob/edd216eb0cdbe2509d1c035fa12342ebb60399fb/src/vs/vscode.proposed.d.ts#L672-L871

**Comment by agjs** [comment]
Thank you so much @jrieken. This is exactly what I needed and on top of this, I literally envisioned this API before. This API will provide and open many creative ways to build some awesome things.

I will join the slack community now and make sure to get some help there during the creation of this plugin.

**Comment by agjs** [comment]
On a side note, whom can I contact to get invitation to vscode-dev-community on Slack :) ?

**Comment by jrieken** [comment]
Good question... ping @auchenberg

**Comment by usernamehw** [comment]
https://twitter.com/code/status/928316741440045056?lang=en

The link in vscode repo should probably be changed from current `Contact admin` to this public invitation link.

**Comment by agjs** [comment]
Awesome, just got in there by following that Twitter link :-).
