### ISSUE TITLE
Setting to show Menubar on Global Menu Linux

### ISSUE THREAD

**Issue by dhamanutd** [Microsoft/vscode#65070]
- VSCode Version: 1.30 
- OS: Ubuntu Mate 18.04

For linux users with DE that have global menu support like Unity.

As before the VSCode Update 1.30, the menubar is shown on the global menu. But after the update, the menubar has it's own place outside global menu. That's good, but some people want their own setting to keep it on the global menu.

Screenshot example of global menu on Google Chrome.
![selection_005](https://user-images.githubusercontent.com/11476348/49997316-ceeacc80-ffc3-11e8-9233-1198eac6f207.png)

**Comment by c5a1e9d0b3** [comment]
Adding this field to `settings.json` will fix this issue:
```
    "window.titleBarStyle": "native"
```

**Comment by dhamanutd** [comment]
haha, my bad missed that line.
Thanks!
