### ISSUE TITLE
Does not support special character issues

### ISSUE THREAD

**Issue by xuezm01** [Microsoft/vscode#65074]
- VSCode Version: Code 1.30.0 (1.30.0)
- OS Version: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Steps to Reproduce:
  1. Edit the file using vim  on  MAC, hold down Ctrl  and enter the letter v --> a ,  get the result ^A .
  2.Open the file with VScode, can't identify ^A

**Comment by alexandrudima** [comment]
You can use `View > Toggle Control Characters`.
