### ISSUE TITLE
`workspace/didChangeWatchedFiles` is not always sent for deleted folders

### ISSUE THREAD

**Issue by LaurentTreguier** [Microsoft/vscode#65077]
Sometimes, if I delete a folder, I won't get any `workspace/didChangeWatchedFiles` notification. I saw #141, which seemed somewhat similar, but here I'm somehow not even getting a notification about the folder itself being deleted.
I looked directly at the JSON-RPC requests and notifications that my server is receiving, in case I did something wrong, and saw no notification about anything being deleted in a session where I removed a folder.
I noticed this when switching branches in a project, where one branch has a folder that the other doesn't have.

If this is of any use:
- Platform: Linux x64 (Fedora 29)
- VSCode: 1.29.1
- `vscode-languageclient`: 5.1.1

I'll see if I can reproduce this on Windows to know if this is platform-specific.
EDIT: it seems to be doing the same on Windows 10 x64.

**Comment by dbaeumer** [comment]
@bpasero I can reproduce this under Windows as well using the example.

Not sure if this is a watcher or API problem (@jrieken)

**Comment by bpasero** [comment]
@LaurentTreguier please check if this could be https://github.com/Microsoft/vscode/issues/60813

**Comment by dbaeumer** [comment]
Looks like. We do send a delete event in the example but only for `delete: file:///c%3A/Users/dirkb/Projects/mseng/VSCode/Playgrounds/dls/format`
