### ISSUE TITLE
Moving file causes JS/TS features to freeze

### ISSUE THREAD

**Issue by Aliaksei-Martsinkevich** [Microsoft/vscode#65089]
Issue Type: <b>Performance Issue</b>

When I move / copy or remove file from my project directory, it leads to disabling of all JS/TS features, like autocomplite, references and others.
For my project it took ~20 seconds to restore all activity. It is especially slow down refactoring, when I move some file I have to wait those 20 seconds before I get prompted about renaming it's dependencies.
Also, confusing part is, that there is no any loading\reindexing.
This number is ~equals to my fist project load time, when I open VS Code.
Shouldn't it be possible to reindex project in less time, since information of files which were moved is available?

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    69	 24496	code main
    0	   213	 21468	   window (core-web • src\action-types\change-list\create.js - core-web - Visual Studio Code)
    0	     7	  7816	     winpty-process
    0	    64	  6344	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     9	 23248	       console-window-host (Windows internal process)
    0	    38	 14232	     searchService
    0	    61	 20640	     extensionHost
   25	   591	  6088	       electron_node tsserver.js 
    0	    63	 28216	         electron_node typingsInstaller.js typesMap.js 
    0	    39	 27784	       "C:\Users\Aliaksei_Martsinkevi\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Aliaksei_Martsinkevi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=20640
    0	    41	 27772	     watcherService
    1	   198	 23568	   gpu-process
    0	    41	 24192	   shared-process
    0	    68	 28100	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (core-web • src\action-types\change-list\create.js - core-web - Visual Studio Code)
|    Folder (core-web): 4629 files
|      File types: js(2134) jsx(1471) scss(570) svg(265) storyshot(100)
|                  json(43) ts(4) woff(4) png(3) md(3)
|      Conf files: webpack.config.js(2) jsconfig.json(1) package.json(1)
|                  settings.json(1) tasks.json(1)
|    Folder (dns): more than 21271 files
|      File types: i(14564) js(2128) jsx(1466) scss(568) svg(265) xml(208)
|                  csv(205) yaml(192) java(149) bak(146)
|      Conf files: package.json(3) settings.json(2) tasks.json(2)
|                  webpack.config.js(2) launch.json(1) sln(1) jsconfig.json(1)
|      Launch Configs: chrome(4);
```

</details>
Extensions: none

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Actually, have good repo with #65112

Added progress indicator with #64986
