### ISSUE TITLE
Debugger is attaching but then releasing without ever hitting the breakpoints, for Vue CLI & Mocha

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#65087]
Issue Type: <b>Bug</b>

The debugger is attaching but then releasing without ever hitting the breakpoints, for Vue CLI & Mocha

```
// step 1
npm i @vue/cli -g

// step 2
vue create vue-test-mocha

// step 3
// manually choose the options for antyhing you want
// be sure to selet MOCHA for the tests (not jest)

// step 4
Enable "Node: Auto Attach" for the node debugger in VS Code

// step 5 start the unit test
node --inspect-brk ./node_modules/.bin/vue-cli-service test:unit

// step 6
Notice that the debugger attaches, then releases, but no breakpoints are hit (it should break on first line)

// step 7
Try adding a breakpoint, it is not hit either
```

Note this issue frmo the vue cli here that is relevant: https://github.com/vuejs/vue-cli/issues/2590

VS Code version: Code - Insiders 1.31.0-insider (7ab53e6d1c7998006bc70f18230178a702598222, 2018-12-13T06:12:22.414Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (4.12GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
markdown-preview-github-styles|bie|0.1.4
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.41
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
Angular1|joh|0.2.0
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.10.0
vscode-azurefunctions|ms-|0.13.0
vscode-cosmosdb|ms-|0.9.1
azure-account|ms-|0.7.0
azurecli|ms-|0.4.2
vsliveshare|ms-|0.3.1071
vsliveshare-audio|ms-|0.1.45
vsliveshare-pack|ms-|0.2.4
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
vetur|oct|0.14.3
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.1
polacode|pnp|0.2.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.4

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
You need to use `yarn test:unit --inspect-brk` like the upstream issue says, so Mocha won't run tests in a subprocess. But also you have to set a `debugger` statement somewhere in the file.

Since this is compiled on the fly, the debugger can't preload the sourcemaps ahead of time. So the `debugger` statement will give it a brief moment to pause and load sourcemaps.
