### ISSUE TITLE
British keyboard: Backquote and IntlBackslash swapped again

### ISSUE THREAD

**Issue by alexrussell** [Microsoft/vscode#65082]
Ref: #24153

I'm basically getting this issue again now. I use insiders, but have also just recently upgraded to Mojave (and just *yesterday* did the 1.14.2 update) so can't simply tell where this issue is coming from. I'd say it's been happening only very recently - anything from max a week ago to some-point-yesterday.

Pretty much same issue as before, pressing the keys labelled `` ` ``  and `§` on my keyboard in a text editor work as expected, but when part of a shortcut, they go funny. 

Attached is a recording showing the MacOS keyboard viewer showing you what keys I am pressing.

You'll see the following:

- In an editor, unmodified `` ` `` works as expected
- In an editor, unmodified `§` works as expected
- Pressing `` ctrl+` `` doesn't focus the terminal as it should (you'll only see that the focus did not leave the editor)
- Pressing `ctrl+§` *does* focus the terminal, but it shouldn't (you'll see focus leave the editor, take my word for it that the terminal is focussed)
- Switching to the keyboatrd shortcuts page, trying to "redefine" the toggle terminal command shows why it goes wrong:
- Pressing `` ` ``/`` ctrl+` `` is read as `[IntlBackslash]`/`ctrl+[IntlBackslash]` (though displayed as `§`/`^§`)
- Pressing `§`/`ctrl+§` is read as `` ` ``/`` ctrl+` `` (and displayed as  `` ` ``/`` ctrl+` ``)

One thing you will notice is that when `ctrl` is pressed, the MacOS keyboard viewer does show that `§` becomes a `` ` ``. That's interesting.

![keyboard](https://user-images.githubusercontent.com/412784/50003577-fc238480-ff9b-11e8-9cc8-edfda19d3d52.gif)

---

- VSCode Version: 1.31.0-insider (`ece3a90fb58986570d8afdfb16530c4dd8c743af`)
- OS Version: MacOS Mojave 10.14.2

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@bpasero Did we maintain the patch we had for this with the upgrade to Electron 3.x ?

**Comment by bpasero** [comment]
@alexandrudima I think so, but I will ask

@alexrussell so it does not reproduce for you in VSCode stable (1.30)?

**Comment by bpasero** [comment]
Yes, it looks like this patch got missing.

**Comment by bpasero** [comment]
@alexrussell can you please report back with todays insider update if it still reproduces?

**Comment by alexrussell** [comment]
All fixed on 28e7467661d67c05c3662ff900ee1984f7e2fbcc.
