### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by krupenja** [Microsoft/vscode#65088]
Version: 1.31.0-insider
Commit: 7ab53e6d1c7998006bc70f18230178a702598222
Date: 2018-12-13T06:17:20.998Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-12-generic

Steps to Reproduce:
1. Install an extension for insiders from command line, e.g. `code-insiders --install-extension stuart.unique-window-colors`

Extension is installed successfully. However, a DeprecationWarning is reported:

```
Found 'stuart.unique-window-colors' in the marketplace.
Installing...
(node:24572) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'stuart.unique-window-colors' v1.0.5 was successfully installed!
```
No problem with VSCode 1.30 (which has Electron 2.0). Something similar was reported previously in #56171 but that issue was closed as non-reproducible. At my end this reproduces consistently with any extension I have tried.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can be fixed once https://github.com/Microsoft/vscode/issues/64849 lands.

**Comment by bpasero** [comment]
Should be fine now with https://github.com/Microsoft/vscode/commit/ccdd2997a66965c7104fe180207d9a710ea50fa5

**Comment by wellington1993** [comment]
Hi @bpasero . The alert appears still occurring in this version:

```
1.32.0-insider
9441f43636a639aaffa28a9c7e6e36151944c8b3
x64
``` 

Thanks!

**Comment by bpasero** [comment]
@wellington1993 steps?

**Comment by wellington1993** [comment]
@bpasero I can't simulate the problem, please see:

```bash
wellington@wellington-Inspiron-3647:~$
 for ext in $(code-insiders --list-extensions); do code-insiders --uninstall-extension "$ext"; done ;
 for ext in $(code --list-extensions); do code-insiders --install-extension "$ext"; done
```

```bash
# ...
Uninstalling Wosi.omnipascal...
Extension 'Wosi.omnipascal' was successfully uninstalled!
Found 'alefragnani.pascal' in the marketplace.
# ...
Installing...
(node:26581) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'alefragnani.pascal' v8.0.0 was successfully installed!
Extension 'alefragnani.pascal-formatter' is already installed.
Found 'dbaeumer.jshint' in the marketplace.
Installing...
# ...
```

Thanks!
```

**Comment by bpasero** [comment]
That is https://github.com/Microsoft/vscode/issues/67534
