### ISSUE TITLE
reStructuredText: Go to Symbol in File... not supported

### ISSUE THREAD

**Issue by allanleal** [Microsoft/vscode#65083]
vscode currently has limited support for reStructuredText compared to native support for Markdown. Since reStructuredText is also heavily used, it makes sense to have similar level of support compared to Markdown. The extension [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) is very nice, but currently does not provide all.

Particularly interested here in Code Outline support for reStructuredText files (i.e., `Go to Symbol in File...` currently shows no symbols/sections).

**Comment by mjbvz** [comment]
Please file this feature request against the restructured text extension
