### ISSUE TITLE
Search view breaks after starting a search while the previous search is still running

### ISSUE THREAD

**Issue by MarekLew** [Microsoft/vscode#65084]
Issue Type: <b>Bug</b>

When change search text when searching then stop searching and not started again. 

Generate random problem (from this):
- "search again" link d'not work
- show only ex. "3 result in 3 files" but not show result  
- "progress bar" show or not
- refresh button work or not

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.68GB (1.13GB free)|
|Process Argv|C:\Users\marek\AppData\Roaming\Thunderbird\profiles.ini|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Boddlnagg** [comment]
I strongly suspect that this is the same bug that was mentioned as "Problem 2" in #65011.

**Comment by MarekLew** [comment]
@BoddInagg Yes this is "Problem 2". Asynchronues  stop search and change search.

**Comment by roblourens** [comment]
The bug is that starting a new search before the previous one completed can put the search view in a bad state. This is from switching to native promises. Before, the cancellation always finished immediately, now it is async.
