### ISSUE TITLE
[Suggestion] GoTo->SwitchGroup->NextGroup and PreviousGroup should work in round-robin.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6508]
When we are working with multi-screen and active window is to last then command "Goto->SwitchGroup->NextGroup" didn't perform any action. I think it is by design but I personally feel it would be good if we can move focus to the first screen when user perform NextGroup action from last screen.

**Comment by weinand** [comment]
@v-pavanp this branch is work in progress and not meant for testing.
