### ISSUE TITLE
Element match highlight

### ISSUE THREAD

**Issue by ertankara** [Microsoft/vscode#65093]
With the latest update, I can't seem to find a feature that I was using very often. I would check if the item I clicked on is the closing element of the item, For example,

```
1 <View>
2  <View></View>
3  <View></View>
4 </View>
```

If I were to click the `View` element at line 1, it would highlight the `View` at the line 4 too. Same goes for 2 and 3

**Comment by ertankara** [comment]
```
<View>
  <View></View>
  <View></View>
</View>
```

**Comment by usernamehw** [comment]
1. Does it repro without extensions `--disable-extensions`?
1. What programming language?
1. What OS?
1. What value  `"editor.occurrencesHighlight"`?
1. Is it working if you change color theme?
1. Do you have custom `"workbench.colorCustomizations"`?
