### ISSUE TITLE
Linux: ENOENT: no such file or directory, lstat '/snap/code'

### ISSUE THREAD

**Issue by yerzhant** [Microsoft/vscode#65095]
Issue Type: <b>Bug</b>

Today after the Code has been updated to 1.30 I've started to receive the message:
ENOENT: no such file or directory, lstat '/snap/code'
on every start of the VS Code.
On the previous version, which was 1.29.1, there wasn't that issue.

Ubuntu 18.04
Linux azan-dev 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Regards,
Yerzhan.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.10GB (10.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
beautify|Hoo|1.4.7
vscode-scss|mrm|0.6.2
vetur|oct|0.14.3
vuetify-vscode|vue|0.2.0

</details>

**Comment by vsimon** [comment]
Just hit this same bug. Same OS & version as OP. 

'/snap/code' doesn't exist, but '/snap/vscode' does FWIW.

**Comment by Furqan136** [comment]
Same issue with KDE Neon 5.14 and it started with vscode version 1.30.0 just like it happened with you.

**Comment by meddario** [comment]
I think this will be solved by #64392 .

**Comment by joaopauloufal** [comment]
Same issue with Ubuntu 18.04 LTS. VScode 1.30.0 installed from the Snap is fetching from a wrong directory when searching for updates (it should be '/snap/vscode' and not '/snap/code').

**Comment by DanGitOnline** [comment]
I don't know the fix, but I made a 'code' and 'current' sub-folder.  Maybe it'll stop complainin' for the time being.

**Comment by Tyriar** [comment]
@flexiondotorg looks like there's an issue breaking v1.30 in https://snapcraft.io/vscode

**Comment by Tyriar** [comment]
In the meantime you can install the deb package from the website, note that the snap package is currently still experimental.

**Comment by mchameddie** [comment]
Same issue and environment here as with @joaopauloufal.

**Comment by tomnieuwland** [comment]
Alternatively you can just use `sudo snap revert vscode` if you don't have any issues with using VSCode 1.29 for a little bit

**Comment by erakli** [comment]
For now, `sudo ln -s /snap/vscode /snap/code` did the trick.

**Comment by joaomoreno** [comment]
Very likely broken by https://github.com/Microsoft/vscode/pull/63716

**Comment by Kedstar99** [comment]
@joaomoreno 
Can you take a look at the patch first.

These are the environment variables loaded within vscode console.

SNAP_USER_DATA=/home/kd913/snap/vscode/72
SNAP_REVISION=72
SNAP_ARCH=amd64
SNAP_INSTANCE_KEY=
SNAP_USER_COMMON=/home/kd913/snap/vscode/common
SNAP=/snap/vscode/72
SNAP_COMMON=/var/snap/vscode/common
SNAP_NAME=vscode
SNAP_INSTANCE_NAME=vscode
SNAP_DATA=/var/snap/vscode/72
SNAP_COOKIE=NndxyyQKsPjkWB46Hr4dx4mVwmnP3bF3sBmMWKpHqlkP
SNAP_REEXEC=
SNAP_CONTEXT=NndxyyQKsPjkWB46Hr4dx4mVwmnP3bF3sBmMWKpHqlkP
SNAP_VERSION=1.30.0-1544567151
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void

Key thing here is the the environment variable is loading /snap/vscode not /snap/code which people are complaining about here.

The problem in this case is that my PR 64372 isn't merged.

The isUpdateAvailable method is looking as this.
realpath(`/snap/${product.applicationName}/current`, (err, resolvedCurrentSnapPath) => {

Where product.applicationName is set as code.

Running this command:

/snap/vscode/current/usr/share/code/resources/app$ cat product.json | grep 'application'
        "applicationName": "code",

Everyone here can look and run these commands themselves. Please, try PR 64372 before reverting my other one.

**Comment by joaomoreno** [comment]
@Kedstar99 The `vscode` snap is a community driven snap package. The `updateService.snap.ts` functionality isn't meant for that package, but for us to officially ship a snap package ourselves.

I've merged #64392 which fixes this issue and added a check for `snapUpdate.sh` to make sure we stick to our focus.

**Comment by jackTaw88** [comment]
@Kedstar99 SNAP dos not guaranteed to be a valid path, _if snap is under classic confinement._ read here:

https://github.com/snapcore/snapd/wiki/Environment-Variables#home

I had open a bug for snapcrafters here:
https://github.com/snapcrafters/vscode/issues/36

The $HOME directory is wrong. 

The same problem exist for  Atom text editor. I don't think this is a problem about electron based apps. Because insomnia (http client) app is electron based and does not have the same problem.

**Comment by Kedstar99** [comment]
@jackTaw88 That is for SNAP_USER_DATA and SNAP_USER_COMMON. The code is using $SNAP which is always mounted in /snap/<snap name> as far as I am aware. This is even for classic confined snaps. I don't know why you are saying that SNAP isn't always a valid path.

The SNAP environment variables listed above are listed for vscode under classic confinement.
