### ISSUE TITLE
"javascript.preferences.importModuleSpecifier" not working ?

### ISSUE THREAD

**Issue by vdegenne** [Microsoft/vscode#65097]
I am trying to change VSC importation behavior in my project.
My project entry-point is a native `index.html` page that makes use of a `type="module"` `script` that imports objects from other javascript "module" type files. I am not compiling anything.
The problem is that the browser doesn't know how to resolve node type paths and we need to explicitly write the relative path from the `index` up to the js module file.

In one javascript file, if I want to import `html` from the `lit-html` npm package I will write `html` and accept VSC autoImport suggestion and then it will generate this line : 

```javascript
import { html } from 'lit-html';
```
When I need this : 
```javascript
import { html } from '../node_modules/lit-html/lit-html.js';
```

I tried to set `"javascript.preferences.importModuleSpecifier"` in the project settings to `"relative"` but it does nothing.

Is it an issue ? Does not VSC yet support modern browser modules feature ?

**Comment by mjbvz** [comment]
`importModuleSpecifier` only applies to files in your project, it does not effect imports from `node_modules`. This is because you almost never want to reference `node_modules` using a relative path. Even for web, a bundlers will handle regular `lit-html` type imports for you

In your case, if you want to use paths like this, you will have to write them manually

**Comment by vdegenne** [comment]
Ok. But as modern browsers tend to implement module-typed scripts support, should not that be added to the feature request section ?
I have the feeling that this will be a feature of interest in a near feature where many developers try to free themselves from an intermediary compilation/bundling procedure. Also modern browsers try their best to make that code to the host migration path seems seamless.
