### ISSUE TITLE
Improve ObjectTree and AsyncDataTree interop

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#65091]
We need a `SyncDataTree` (name isn't final) which lets users reuse their data providers among different trees.

- [x] Change the `DataProvider.getChildren` result type from `Promise<T>` to `T[] | Promise<T[]>`. https://github.com/Microsoft/vscode/commit/3ccc7a9a1f9fa54dfc696b489461b9c376a3064b
- [x] Create a `DataTree` which, along with a `IDataProvider`, will allow sync tree updates using a data provider pattern. It will also enable people to reuse providers across the `DataTree` and the `AsyncDataTree`. https://github.com/Microsoft/vscode/commit/12682daf54bbf3735f986929a015d5282fd20904
- [x] Bring back the concept of `tree.input` which lets users drop all the references to their model and use the tree as a place to keep that reference.
- [x] Introduce `WorkbenchDataTree` :man_facepalming: 

cc @jrieken @isidorn @roblourens

**Comment by joaomoreno** [comment]
I've introduced the `DataTree`, which is basically an `ObjectTree` which works with a sync data source.

I've brought back the concept of a tree input. This will allow you to stop giving your data provider model objects and just give it to the tree directly. It also means that, in order to keep TypeScript helping us, the `AsyncDataTree` and `DataTree` now have a new generic type `TInput` which lets you type the input. This type bubbles down to the `IDataSource` types in the following way:

```ts
export interface IDataSource<TInput, T> {
	getChildren(element: TInput | T): T[];
}

export interface IAsyncDataSource<TInput, T> {
	hasChildren(element: TInput | T): boolean;
	getChildren(element: TInput | T): T[] | Promise<T[]>;
}
```

This is the proper typing of the same old-tree behavior.

This means `null` no longer represents the tree root element, but instead by an element of type `TInput`. You no longer call `refresh(null)` to set the initial input, but `setInput(input)` or `refresh(input)` if it's already set.

I have migrated all trees in `master` and tested them out as well as I knew how. @jrieken @isidorn @weinand **Please quickly check your specific tree changes** in https://github.com/Microsoft/vscode/commit/419d5bbaedebef63cff9bc248f8407cda5d40562 and sanity check them just to make sure they are still OK.

@isidorn I couldn't migrate `repl.ts` because of the weird `selectSession` hackery you're doing over there, so I left `null` representing the root (`TInput` is `null`). If you're interesting in cleaning it up, check up my changes on `callstackView` for a reference. What you should strive to do is avoid that patter of setting a property on the data source: it should be stateless.

**Comment by isidorn** [comment]
@joaomoreno thanks for converting my trees.
I have tackled the repl via 3f7ff31cb9
