### ISSUE TITLE
Theme color issue

### ISSUE THREAD

**Issue by ShangxuanWu** [Microsoft/vscode#65096]
Issue Type: <b>Feature Request</b>

    "workbench.colorCustomizations": {
        "activityBar.background": "#dedede",
        "activityBar.foreground": "#000000"
    },

Can we add this to the "Light default" theme? Then the side bar would become same light color not dark.

VS Code version: ATG Code 1.25.0 (Commit unknown, 2018-07-19T15:30:46.640Z)
OS version: Linux x64 4.4.0-139-generic

**Comment by usernamehw** [comment]
```json
"workbench.colorCustomizations": {
    "[Default Light+]": {
        "activityBar.background": "#dedede",
        "activityBar.foreground": "#000000"
    },
}
```
