### ISSUE TITLE
Default background img is not displaying and UI looks odd when opening new folder.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6509]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open any folder.
2. Now try to open other project folder without closing previous one (File->Open Folder).

Actual:
![image](https://cloud.githubusercontent.com/assets/17735796/15380126/3c9c4366-1d28-11e6-9d9d-de4b68192959.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/17735796/15380130/483c9428-1d28-11e6-91d1-f94e96ea009e.png)

**Comment by weinand** [comment]
@v-pavanp this branch is work in progress and not meant for testing.
