### ISSUE TITLE
Still cannot auto-update VS Code

### ISSUE THREAD

**Issue by timheuer** [Microsoft/vscode#65099]
With each update to VS code I get the notice to restart to update and it reliably fails and them I'm left with no install of VS code, have to reboot (I'm on Windows) and re-install again hoping that maybe, just maybe, the next update will work again. Narrator: It doesn't.

I get this:
![error1](https://user-images.githubusercontent.com/4821/50016648-9c6ab080-ff7e-11e8-87e8-1ab7a8739bc1.png)
Then I click retry a few times, still fails with the same message.  I then cancel and it tells me to log an issue here with the log file (attached here).  And then upon acknolwedging that dialog I get:
![error2](https://user-images.githubusercontent.com/4821/50016676-b3110780-ff7e-11e8-8639-8347cefa7ee6.png)

And now I'm off hunting again for the installer to finish my work.

HELP!

[vscode-inno-updater-1544806513.log](https://github.com/Microsoft/vscode/files/2681062/vscode-inno-updater-1544806513.log)

**Comment by joaomoreno** [comment]
Hi @timheuer, so sorry to see that. You're not alone: #60697

Meanwhile you can disable background updates with `update.enableWindowsBackgroundUpdates: false`.
