### ISSUE TITLE
 TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#651]
Issue Id: <b>9c0a1fe6-f1ae-7809-8442-04fc1c290480</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/languages/typescript/common/project/projectService.ts#L378:38 (ProjectService._syncProject)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/typescript/common/project/projectService.ts#L378:38 (ProjectService._syncProject))<br />[/vs/languages/typescript/common/typescriptWorker2.ts#L124:24 (TypeScriptWorker2.acceptProjectChanges)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/typescript/common/typescriptWorker2.ts#L124:24 (TypeScriptWorker2.acceptProjectChanges))<br />[/vs/languages/typescript/common/typescriptMode.ts#L291:39 (TypeScriptMode._doAcceptProjectChanges)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/typescript/common/typescriptMode.ts#L291:39 (TypeScriptMode._doAcceptProjectChanges))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />[/vs/editor/common/modes/abstractMode.ts#L122:35 (AbstractMode._worker)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/modes/abstractMode.ts#L122:35 (AbstractMode._worker))<br />[/vs/languages/typescript/common/typescriptMode.ts#L291:14 (TypeScriptMode._doAcceptProjectChanges)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/typescript/common/typescriptMode.ts#L291:14 (TypeScriptMode._doAcceptProjectChanges))<br />[/vs/platform/thread/common/workerThreadService.ts#L93:16 (WorkerThreadService.AllWorkers)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/thread/common/workerThreadService.ts#L93:16 (WorkerThreadService.AllWorkers))<br />[/vs/platform/thread/common/threadService.ts#L81:33 (AllWorkers)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/thread/common/threadService.ts#L81:33 (AllWorkers))<br />[/vs/platform/thread/common/workerThreadService.ts#L51:42 (WorkerThreadService._handleRequest)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/thread/common/workerThreadService.ts#L51:42 (WorkerThreadService._handleRequest))<br />[/vs/platform/thread/common/workerThreadService.ts#L57:21 (WorkerThreadService.dispatch)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/platform/thread/common/workerThreadService.ts#L57:21 (WorkerThreadService.dispatch))<br />    at t.dispatch (out/vs/editor/common/worker/editorWorkerServer.js:14:25163)<br />

**Comment by jrieken** [comment]
This code is gone
