### ISSUE TITLE
Search within Settings does not properly update results

### ISSUE THREAD

**Issue by OnlineCop** [Microsoft/vscode#65103]
Issue Type: <b>Bug</b>

1. Click the Manage gear and select Settings.
2. Under the "Search settings" text input box are three categories:
    [User Settings]  [Workspace Settings]  [Folder Settings]
3. Search for a phrase, such as 'replace'
4. Results under the [User Settings] category for me show:
    Window (1) -> New Window (1)
    Features (1) -> Search (1)
    Extensions (1) -> Git (1)
5. Click on the [Workspace Settings] category
6. Results under the [Workspace Settings] category for me show nothing
6a. Searching for 'replace' while this category is already selected shows:
    Features (1) -> Search (1)
    Extensions (1) -> Git (1)
7. Switch back to the [User Settings] category
8. Results under the [User Settings] category for me show:
    Window (1)

The "Window (1)" is not expandable like it was previously.
8a. Searching for 'replace' while [User Settings] is still selected shows the results from #4 as expected.

Essentially, switching between categories, the search results are not updating properly. the results are correct if the category is already selected before searching for the keyword.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.4.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1352)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.81GB (43.44GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.7.0
code-gnu-global|aus|0.2.2
vscode-quick-select|dba|0.2.7
CppSnippets|har|0.0.13
cmake-tools-helper|mad|0.2.1
mlextension|Mag|0.9.5
cpptools|ms-|0.20.1
remote-vscode|raf|1.1.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
clang-format|xav|1.8.0

</details>

**Comment by roblourens** [comment]
I can't reproduce this. Could you add a few screenshots so to be sure I understand what you are seeing? Can you also open the developer tools (Help > Toggle developer tools) and check for errors?
