### ISSUE TITLE
Typescript Find All References stopped finding references 1.30.0

### ISSUE THREAD

**Issue by mdenson-dayspring** [Microsoft/vscode#65102]
Issue Type: <b>Bug</b>

This is an awesome feature that I used extensively when it was the preview List All References.

With the latest release it stopped finding references with TS.  I am able to command click from a reference to the definition (cool) but the Find all References doesn't list the use I just came from

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.5

</details>

**Comment by mdenson-dayspring** [comment]
Ah! Is this dependent on some parsing process running in the background?

It has started working now after a few minutes.  Maybe an indication that the feature may work after the project is processed, with an indication of progress (maybe).

Thanks for the great tool.

**Comment by mjbvz** [comment]
Was there an `Initializing JS/TS language features...` spinner shown in the status bar when it did not work? Also, does your project have a `tsconfig.json` and are both files part of it?

**Comment by mdenson-dayspring** [comment]
Hi I did not see the spinner.  I did specifically look to see if something was going on in the background.

Yes I do have a tsconfig.json. Multiple actually.  The project is an angular project with multiple (2) apps and several libraries. Each app/lib has a tsconfig.json.

FYI we are using the ng tooling extension by nrwl called nx.

**Comment by mjbvz** [comment]
Do you have an example project that you can share or can you describe the project layout (along with contents of the `tsconfigs`)

**Comment by dcecile** [comment]
I'm also seeing this with a multiple tsconfig.json setup. (Even though technically all of them should be "joined" via a root tsconfig.json that uses project references.)

Here's a minimal repro of my setup: https://github.com/dcecile/typescript-references-test

```
common/
  message.ts
server/
  hello.ts
client/
  sharedMain.ts
```

- Both client and server reference the common project
- "Find references" fails to find the references to the common function
- "Rename symbol" also fails to rename the references
- After loading files from the client and server projects, find references works

**Comment by enzy** [comment]
I'm facing this issue in an Angular 7 project after the recebt VS code update, it did work in the previous version though.

My version:
```Version: 1.32.0-insider (user setup)
Commit: 7ff2398cfd0776409ff687ce811f1d7ff3375dc8
Date: 2019-02-11T11:42:54.142Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18334```

**Comment by qlqllu** [comment]
I have the similar issue, and I narrow down the issue to: only the `export function fn1()` can't find its references, the functions in a class can find their references.

BTW, `rename symbol` on the function that can't find its references will report an error, but I can't find a way to copy the error stack.

**Comment by qlqllu** [comment]
The `find all references` starts working after some operations (I don't which operation make this function work). I am sure waiting for sometime can't make this work.

**Comment by mjbvz** [comment]
@qlqllu @enzy @dcecile Please open new issues.

@mdenson-dayspring If you are still seeing this issue in the latest VS Code insider, let me know. Please include more information about your project contents and structure

**Comment by achimschrepfer** [comment]
@mjbvz the issue (not finding all references of a given symbol throughout the whole workspace) seems to happen on projects with multiple tsconfig.json files. I have an Angular NX Workspace with several libraries in it. Navigation features like find all references, lint messages and errors and warnings never seem to be collected througout the whole workspace.

In simple TS projects I never experience those issues.

**Comment by qlqllu** [comment]
Yes, my project has multiple tsconfig.json and I have this issue.

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [Microsoft/vscode] Typescript Find All References stopped finding references 1.30.0 (#65102)
发件人：Achim Schrepfer
收件人：Microsoft/vscode
抄送：Junshan Liu ,Mention


@mjbvz<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mjbvz&d=DwMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=3AW-ICN55TL8tz2SMsXuf53e6BdEmEOpKpNyTjPFNhQ&m=xs71kYW-ivkk8v3i6PpEAaBgObOGxmKSrWSUlAIzr24&s=FRXSjhdz923p-8ahtamN5i5qFefIsWaDod4FwI86P74&e=> the issue (not finding all references of a given symbol throughout the whole workspace) seems to happen on projects with multiple tsconfig.json files. I have an Angular NX Workspace with several libraries in it. Navigation features like find all references, lint messages and errors and warnings never seem to be collected througout the whole workspace.

In simple TS projects I never experience those issues.

―

**Comment by dcecile** [comment]
@achimschrepfer @qlqllu I created #69001 hoping to track this multiple tsconfig.json issue
