### ISSUE TITLE
Linux custom title bar broken over X11 display forwarding over SSH

### ISSUE THREAD

**Issue by Clockwork-Muse** [Microsoft/vscode#65101]
- VSCode Version:
1.30.0
- OS Version:
Local: Windows 10 Enterprise 1803 17134.407
Remote: Ubuntu 18.04.1

Steps to Reproduce:
1. Ensure "window.titleBarStyle" setting is either default, or set to "custom"
2. Launch code via remote shell

My system is a little daisy-chained together, so I'm not sure what, exactly, is causing this.  And it's possibly a little rare, so I don't know if it should be a big issue.
My local system is an HP ZBook 15 G3 that's attached via Thunderbolt/USB3 to an egpu (Akita node w/ NVidia 1080).  When I SSH into my remote machine - via MobaXTerm - and start code, the custom titlebar is broken:
 - The window cannot be maximized/windowed
 - The window cannot be moved when windowed
 - The window cannot be resized when windowed
 - The window doesn't respond to keyboard shortcuts to manipulate the window (eg, Win+LeftArrow)
 - The window _can_ be closed/minimized
 - It displays strangely; when maximized, there is a gap above the displayed titlebar:
![image](https://user-images.githubusercontent.com/5569508/50020582-3fc1c280-ff8b-11e8-981d-6043689fe9a4.png)

(So my guess would be that there's a "phantom" toolbar being created that's looking for the events)  
Code otherwise appears to work fine.  Changing to the native title bar removes the issues.

**Comment by sbatten** [comment]
@Clockwork-Muse X forwarding requires the native title bar to function. I've added a note about this in the [Linux FAQ Page](https://code.visualstudio.com/docs/setup/linux). You should see the note when that page gets updated.

**Comment by Clockwork-Muse** [comment]
Alright then
