### ISSUE TITLE
Typo for pseudo-selector ::-webkit-outer-spin-button (::-webkit-ouer-spin-button) in intellisense

### ISSUE THREAD

**Issue by benmillhouse** [Microsoft/vscode#6510]
- VSCode Version: 1.1.1
- OS Version: OS X v 10.11.5

Steps to Reproduce:

1. Create a CSS file
2. Start typing the pseudo-element selector ::-webkit-ou...
3. Intellisense displays ::-webkit-ouer-spin-button (missing the t in outer)

**Comment by Tyriar** [comment]
Thanks for reporting, fixed :smiley:
