### ISSUE TITLE
Switching to a powershell file freezes VS Code

### ISSUE THREAD

**Issue by dileepd11** [Microsoft/vscode#65110]
We have written 
Issue Type: <b>Bug</b>

After the latest update VS code is frozen for about 5-10 seconds when i switch from a txt file to a PS1 file

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (6.10GB free)|
|Process Argv|C:\Users\dxd86\Desktop\Script Sync\20181213\UPSManageHR|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
tslint|eg2|1.0.41
angular-bootstrap|her|4.0.9
beautify|Hoo|1.4.7
Angular1|joh|0.2.0
vscode-format-context-menu|lac|1.0.4
mssql|ms-|1.4.0
csharp|ms-|1.17.1
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.10.1
typescript-javascript-grammar|ms-|0.0.47
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.11.1
qub-xml-vscode|qub|1.2.8
vscode-icons|rob|7.28.0
Angular2|UVB|0.4.1

(3 theme extensions excluded)

</details>
the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Sounds like this could be caused by the powershell extension. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
