### ISSUE TITLE
Split editor control is not working with Markdown preview.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6511]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open smoke test project folder.
2. Open readme.md file.
3. Click on "Open Preview" button.
4. Verify preview in split screen and click on split editor button from preview window.
Actual: No action when user click on "Split editor" button.
Expected: Should open new screen with split screen.

![spliteditoronpreview](https://cloud.githubusercontent.com/assets/17735796/15380585/8616e92a-1d2c-11e6-85fb-e2ed35a32a1c.gif)

**Comment by weinand** [comment]
@v-pavanp it looks like you are testing the 'ben/stacks' branch. This branch is work in progress and is not ready for testing.
