### ISSUE TITLE
https.request with a null ClientRequestArgs.agent creates a ProxyAgent instead of Agent on Insiders failing with 403

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#65118]
- VSCode Version: 1.31.0-insiders. The issue doesn't repro with non-Insiders.
- OS Version: Linux/Windows (probably Mac too). Repros for the 3 machines we've tried.

Steps to Reproduce:

1. Use repo https://github.com/Microsoft/vscode-cpptools/tree/seanmcm/debugVsixDownload .
2. Set a breakpoint in Extension/src/common.ts, downloadFileToDestination method, such as line 628.
3. Launch Extension.

Bug: The https.request for "/Microsoft/vscode-cpptools/releases/download/0.21.0-insiders/cpptools-win32.vsix" is failing with a 403, which is preventing users from automatically getting our insider release. We download some other smaller .json files beforehand using the same code and it works. It also works with non-Insiders and we're not able to figure out a reason for the failure.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sean-mcmanus** [comment]
UPDATE: We pass in a "null" agent into the https.request, but in VS Code Insiders that is incorrectly causing a ProxyAgent to be created, but in VS Code a normal "Agent" is getting created. We'll attempt to workaround this regression in behavior via passing in an "Agent" instead of "null".

**Comment by sean-mcmanus** [comment]
UPDATE: We figured out that on Insiders, the http.proxySupport setting is defaulting to "override", which causes the failure for us. How are we supposed to disable the usage of the proxy agent so that our download can succeed?

**Comment by sean-mcmanus** [comment]
UPDATE: I've implemented a workaround at https://github.com/Microsoft/vscode-cpptools/pull/2931 via changing the http.proxySupport setting to "off" if the download fails. Let us know if that is not a good workaround.

**Comment by chrmarti** [comment]
@sean-mcmanus We need to fix this, I assume there will be other requests with the same problem.

I have tried to reproduce it without a proxy, but I get a 302 and then a 200, as you would probably expect.

Are you testing with a proxy configured in the VS Code settings, the environment variables or the OS settings? What kind of proxy are you using?

**Comment by sean-mcmanus** [comment]
Yeah, I'm reproing this bug still (on my 1st try). I just use VS Code 1.30.0 with the http.proxySupport set to "On" . Let me know if there's some way to debug or get logs. Our telemetry shows over 1100 users have hit the "Failed to download vsix" -- we're not sure yet if the proxySupport setting is the cause, but that would explain it.

![image](https://user-images.githubusercontent.com/19859882/50114026-67699280-01f8-11e9-985b-60dedb3b044f.png)

**Comment by sean-mcmanus** [comment]
The agent is always a ProxyAgent, but the 403 only occurs when we try to download our 17+ MB .vsix from GitHub (e.g. https://github.com/Microsoft/vscode-cpptools/releases/download/0.21.0-insiders2/cpptools-win32.vsix ). It successfully downloads everything else we try such as https://api.github.com/rate_limit, https://api.github.com/repos/Microsoft/vscode-cpptools/releases , https://go.microsoft.com/fwlink/?linkid=2026205 , https://go.microsoft.com/fwlink/?linkid=2037609.

It looks like 75% of our Insiders users are failing to download our latest 0.21.0-insiders2 vsix due to this issue. We'll probably just release our non-Insiders in the next couple days because this issue is keeping users stuck on 0.21.0-insiders.

**Comment by chrmarti** [comment]
Due to small differences in how things are working the `Host` request header ended up always including the port. Normally the port would only be included if it was not the default port (like 443). S3 (where the GitHub download URL redirects to) seems to reject such requests.

I'm including a fix in tomorrow's insiders build, please let me know if that fixes it.

**Comment by sean-mcmanus** [comment]
Thanks a lot -- that fixed it. Our Insider usage tripled.

**Comment by chrmarti** [comment]
Great, thanks @sean-mcmanus !
