### ISSUE TITLE
TypeScript debugging randomly does F5/continuing after a breakpoint is hit on the latest Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#65119]
This might be a duplicate of https://github.com/Microsoft/vscode/issues/65087 , except I get breakpoints to be hit (they just sometimes continue after a random time).

- VSCode Version: 1.31.0-insiders
Version: 1.31.0-insider (user setup)
Commit: ece3a90fb58986570d8afdfb16530c4dd8c743af
Date: 2018-12-14T06:19:42.976Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. I'm using https://github.com/Microsoft/vscode-cpptools and I set a breakpoint such as in Extension\src\common.ts .

Bug: VS Code will hit the breakpoint, but then "randomly" it will continue running, preventing me from debugging. It doesn't repro with 1.30.0 and it was working yesterday with insiders.

My debug config is:

```
		{
			"name": "Launch Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"stopOnEntry": false,
			"sourceMaps": true,
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "TypeScript Compile",
		},
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
I can reproduce on macOS and Windows with this simplified setup:
- generate "hello extension" via yeoman
- set breakpoint in line 17 (...`registerCommand('extension.sayHello'`...)
- F5
- in new window run "hello world" action

Observe:
- breakpoint is hit
- after approx. 3 seconds a "continue" occurs whcih makes the "hello world" notification showing.

**Comment by weinand** [comment]
I did a git bisect and found this commit to be the culprit:

**Comment by jrieken** [comment]
Yeah, the automatic extension host profiling does that because after 3secs we think the tool is dead...

**Comment by sean-mcmanus** [comment]
Cool -- thanks a lot for fixing this. I was worried it would get "no reproed" or something, since my co-worker wasn't reproing it on his machine.

**Comment by dbaeumer** [comment]
Starting to verify :-)
