### ISSUE TITLE
Blacked-out Sections while In Fullscreen

### ISSUE THREAD

**Issue by ItsLofus** [Microsoft/vscode#65122]
After hovering over open tabs while in fullscreen, the text area started rendering opaque black squares all over. As the mouse moved, this also occurred with the explorer and bar area, seemingly each updating section failed to render. Finally, the whole screen when black except for the "save dots." Stopped occurring once I pressed alt to see the menu bar.

**Comment by mjbvz** [comment]
Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
