### ISSUE TITLE
The differences between Find all References and Peek References

### ISSUE THREAD

**Issue by saibing** [Microsoft/vscode#65127]
- VSCode Version: 1.30.0
- OS Version:  Windows 10.0.17134.471

Steps to Reproduce:

1. Open a go project with vscode-go extension, use [bingo](https://github.com/saibing/bingo) language server.
2. Run Find All References, Peek References for the same variable

- Find all References result

```bash
--> request #33: textDocument/references: {"textDocument":{"uri":"file:///d%3A/git/go/source/go-langserver/main.go"},"position":{"line":134,"character":5},"context":{"includeDeclaration":true}}
<-- error #33: textDocument/references: {"code":0,"message":"invalid node: ast.AssignStmt (135:3-135:28)","data":null}
[Error - 1:55:44 PM] Request textDocument/references failed.
  Message: invalid node: ast.AssignStmt (135:3-135:28)
  Code: 0 
```
- Peek References result
```bash
--> request #37: textDocument/references: {"textDocument":{"uri":"file:///d%3A/git/go/source/go-langserver/main.go"},"position":{"line":134,"character":2},"context":{"includeDeclaration":true}}
<-- result #37: textDocument/references: [{"uri":"file:///d:/git/go/source/go-langserver/main.go","range":{"start":{"line":155,"character":36},"end":{"line":155,"character":39}}},{"uri":"file:///d:/git/go/source/go-langserver/main.go","range":{"start":{"line":139,"character":2},"end":{"line":139,"character":5}}},{"uri":"file:///d:/git/go/source/go-langserver/main.go","range":{"start":{"line":134,"character":2},"end":{"line":134,"character":5}}}]
```

Peek References works ok, but Find all References not.

The position for the variable that 'Find all References' action send is wrong. 

> Go use tab to indent code

- Find all References
```json
{
"position":{"line":134,"character":5}
}
```
- Peek References

```json
{
"position":{"line":134,"character":2}
}
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
Please provide the code snippet with which you are trying this. The only thing that's different between peek and find is that the latter uses the word start in which the cursor currently is

**Comment by saibing** [comment]
- go.mod
```go
module github.com/saibing/hello
```
- sum.go
```go
package main

// sum add x and y
func sum(a int, b int) int {
	return a + b
}
```
- main.go
```go
package main

import "fmt"
import "net/http"

func main() {
	fmt.Println("hello")
	
	c := http.Client{}
	c.Post("", "", nil)

	sum(1, 2)

	sum(3, 4)

	sum(5, 6)

	sum(5, 6)
	sum(5, 6)
	fmt.Printf("%s", "hello")
	sum(7, 8)
}
```

This problem occurs when I double-click the "sum" function name to execute Find All References, but click the "sum" function name to execute Find All References is no problem.

**Comment by jrieken** [comment]
Can you run "Peek References" like this (`|` is the cursor/selection) `|sum`, `sum|`. Does peek references work in that case?

**Comment by saibing** [comment]
@jrieken 


- |sum 
> click the first position before 'sum'

Peek References: ok
Find all References: ok

- su|m
> click the position during 'sum'
Peek References: ok
Find all References: ok

- sum|
> double-click to select 'sum'
Peek References: ok
Find all References: failed 

message: invalid node: ast.CallExpr

- sum|(
> click the first position after 'sum'
Peek References: failed
Find all References: failed 

message: invalid node: ast.CallExpr

**Comment by jrieken** [comment]
Ok, thanks for clarifying. This is an issue with the go extension because it failed to compute references for `sum|`.

**Comment by jrieken** [comment]
> Was this difference intentional?

Yes, but it shouldn't really matter as that position is still a valid position, right?
