### ISSUE TITLE
Right arrow accepts suggestions in debug console

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65121]
- Type in debug console
- See suggestion widget
- Press right arrow
- The suggestion is accepted and the text is entered into the repl input

The suggestion shouldn't be accepted - the cursor should move to the right instead. This doesn't happen in the editor or other places that use the suggestion widget like the extension viewlet search.

**Comment by isidorn** [comment]
@roblourens I thought it was useful, thus I added it. But I agree that consistency makes sense here
