### ISSUE TITLE
Integrated CMDER Terminal load time is high

### ISSUE THREAD

**Issue by abhijithvijayan** [Microsoft/vscode#65124]
- VSCode Version: 1.30.0
- OS Version: Windows 10 Pro 1803

Steps to Reproduce:

1. Loading the custom integrated Terminal `cmder`
2. Stucks without loading for about a min and then loads

Screenshot
![](https://i.imgur.com/8e4vv2s.png)

User Defined Configuration
![](https://i.imgur.com/PUh5bM6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Seems to launch instantly for me, this is likely an issue with your environment (or you're actually on 1809 and seeing https://github.com/Microsoft/vscode/issues/57803).
