### ISSUE TITLE
some js keyword in solarized heme is distinguishable with variable

### ISSUE THREAD

**Issue by iEverX** [Microsoft/vscode#6512]
- VSCode Version:1.1.1
- OS Version:win10

Steps to Reproduce:

1. open a js file
2. use with solarized dark theme
3. just like this picture, `var`, `let`, `function`, are very similar to variable

![solarized](https://cloud.githubusercontent.com/assets/1268312/15380749/aecc939a-1dab-11e6-802b-b4efc541de8f.png)

**Comment by iEverX** [comment]
http://tmtheme-editor.herokuapp.com/#!/editor/theme/Solarized%20(dark)
i think this color is fine

**Comment by aeschli** [comment]
We got our theme from http://colorsublime.com/?q=solarized.
The one on http://tmtheme-editor.herokuapp.com/#!/editor/theme/Solarized%20(dark) is very different.

**Comment by aeschli** [comment]
I sugest to have a look on how to make an extension for a new theme at https://code.visualstudio.com/docs/tools/yocode and offer the other variant of Solarized Dark as an extension...
