### ISSUE TITLE
Allow to show close button over icon on the left

### ISSUE THREAD

**Issue by winzig** [microsoft/vscode#65139]
Right now tabs in vscode look like this, with the file icon on the left, and the close button always visible (for the active tab) on the right:

<img width="518" alt="screen shot 2018-12-15 at 12 51 23 pm" src="https://user-images.githubusercontent.com/127062/50047357-3eb29300-0068-11e9-8ab3-2ae0b08dbf0b.png">

Has their been any discussion of possibly changing this in a couple ways:

1. Remove the X close icon on the right, including the space reserved for it. 
2. Make the file icon on the left turn into the X close icon when the user is mousing over the tab.

If the above changes were made, there are some benefits:

- All tabs will take up less room, because no space is reserved for the close button.
- Closing sequential tabs is easier, as you can place your mouse over the left side close button, tap close, and the next tab slides over with the close button directly under your mouse, so you may continue closing tabs. (I'm aware of the various Close Tab options available if you right-click on a tab, but sometimes you just want to quickly close a sequence of tabs.)

The only downsides I can think of:

- Might not adhere to some platform UI guidelines. ¯\\\_💩_/¯ 
- User has to mouse over the tab to discover where the close button is. However they probably only need to do this one time before they understand the layout.

**Comment by winzig** [comment]
Yeah the Opera UI you show above is exactly what I had in mind. 

FWIW, Safari has the close button on the left, which makes rapidly closing tabs a lot easier. Safari only recently added the ability to even show the favicon in the tab, and it's not there by default, so it's not surprising they have not adopted Opera's technique, at least year.

**Comment by misolori** [comment]
One issues that does come up with this is that we also use the close button space to show an unsaved file (dot):
<img width="282" alt="image" src="https://user-images.githubusercontent.com/35271042/50131254-2d1ee600-0236-11e9-865a-85c8475682b8.png">

An alternative would be to use the asterisk (*) for unsaved, which would give you:

![gif](https://user-images.githubusercontent.com/35271042/50131839-f26a7d00-0238-11e9-8848-04983fefc87a.gif)

**Comment by bpasero** [comment]
Please keep in mind that many people have icons disabled, so the design would have to work when icons are turned off.

**Comment by misolori** [comment]
I think it could still work, we'd just not show the icon and adjust the spacing so it's even:

![gif](https://user-images.githubusercontent.com/35271042/50136680-644cc180-024d-11e9-8fb7-7f801a01eeca.gif)

**Comment by winzig** [comment]
Another option would be to make the tab font bold if the file's been modified.

**Comment by misolori** [comment]
@winzig someone reminded us that we do have a setting, `workbench.editor.tabCloseButton`, that moves the close button to the left hand side:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/35271042/50238650-dec43100-0374-11e9-99c5-975ea99bfcfc.png">


We also internally discussed the option above (swapping the seti icon with the close button on hover) and decided that it wasn't a good idea due to our implementation when the close button is set to the left that users are used to seeing the dirty state in that same location:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/35271042/50238583-a7558480-0374-11e9-8b7c-f846a94ed4d2.png">

If you still think this is feature you'd like for us to consider we can leave this open, otherwise we can close this.

**Comment by winzig** [comment]
OK that resolves my primary issue (being able to close sets of tabs more rapidly).

I think some optimization could be done to combine the icon/close/dirty indicator into a single location, which would make tabs smaller, and therefore let you fit more into a smaller space. Maybe via an option to let the user choose whether to combine them or not. 

Most of the time I have a bunch of file tabs open, but only a couple are dirty. In those cases, the fact that they are dirty is more useful to me than seeing the filetype icon, so if I had my druthers, it would work like this:

- Default (file type icon visible)
- Mouseover (icon replaced with X)
- Dirty (icon replaced with dot, no mouseover required)

But if this idea is not popular then we can close this out.

**Comment by winzig** [comment]
Actually, poking around the settings, I personally would turn on the highlight over tab option for dirty files, and skip the dot completely. So you either see the app icon, or when mousing over, the close button, no dot. 

Perhaps there is a way to enable that as an option at some point.

**Comment by misolori** [comment]
In that case I’ll leave this open as a feature 😄

**Comment by smlombardi** [comment]
I noticed a  flag in Edge Canary to do exactly this.  I came here to request this very thing. The implementation is excellent. I'd love to have this behavior in Code.  

<img width="282" alt="Screen Shot 2019-07-03 at 8 36 23 AM" src="https://user-images.githubusercontent.com/835148/60592356-749e3700-9d6e-11e9-9e42-f10794259aae.png">

**Comment by smlombardi** [comment]
> Actually, poking around the settings, I personally would turn on the highlight over tab option (Workbench › Editor: Highlight Modified Tabs) for dirty files, and skip the dot completely. So you either see the app icon, or when mousing over, the close button, no dot.

>Perhaps there is a way to enable that as an option at some point.

Exactly, this behavior please.
