### ISSUE TITLE
Extended snippet properties to support automatic import of related libraries

### ISSUE THREAD

**Issue by xuping-huang** [Microsoft/vscode#65133]
Code snippet is a very good feature to speed up programming. A shortcoming is that the third-party library objects that need to be referenced in the inserted code cannot be import together. I am now incorporating the import information into the code snippet as a comment.

For example:
```
	"Angular Module ForRoot": {
		"prefix": "xx.ng.module.forroot",
		"body": [
			"/**",
			" import { ModuleWithProviders } from '@angular/core';",
			"",
			" * need import in app module with forroot()",
			" * imports: [",
			" *   ${1:moduleName}.forRoot({sampleProperty: 'Sample Value'}),",
			" * ]",
			" */",
			"static forRoot(config: ${2:UserServiceConfig}): ModuleWithProviders {",
			"\treturn {",
			"\t\tngModule: ${1:moduleName},",
			"\t\tproviders: [",
			"\t\t\t{provide: $2, useValue: config}",
			"\t\t]",
			"\t};",
			"}"
		],
		"description": "Angular Module ForRoot"
	}
```
I know some extensions like "auto import" can help about this. But it also requires some extra keyboard and mouse action. If vs code snippet can add an extend property to record which third-party libraries need to be imported into the current script file, then vscode editor can complete this action after insert snippet code. That will be perfect!

For example:
```
	"Angular Module ForRoot": {
		"prefix": "xx.ng.module.forroot",
		"imports": [ "ModuleWithProviders|@angular/core" ]
		"body": [
			"/**",
			"",
			" * need import in app module with forroot()",
			" * imports: [",
			" *   ${1:moduleName}.forRoot({sampleProperty: 'Sample Value'}),",
			" * ]",
			" */",
			"static forRoot(config: ${2:UserServiceConfig}): ModuleWithProviders {",
			"\treturn {",
			"\t\tngModule: ${1:moduleName},",
			"\t\tproviders: [",
			"\t\t\t{provide: $2, useValue: config}",
			"\t\t]",
			"\t};",
			"}"
		],
		"description": "Angular Module ForRoot"
	}
```

**Comment by mjbvz** [comment]
More advanced snippet functionality like this is better suited to an extension that implements a `CompletionItemProvider`. Suggestions generated by a `CompletionItemProvider` can make additional text edits in the file to add imports
