### ISSUE TITLE
git extension is NOT asking for secret phrase when ssh key is being used

### ISSUE THREAD

**Issue by jpmolinamatute** [Microsoft/vscode#65135]
Hi!

Since git extension is not longer asking me for the secret phrase the extension just wait for something to happens (which nothing never happens) 

I'm hitting this problem is two places one when I have `"git.autofetch": true,` in setting.  This fire multiple sub-process:

> 5248 tty2     S+     0:00 /usr/bin/git fetch
>  5250 tty2     S+     0:00 /usr/bin/ssh labs git-upload-pack 'jpmolinamatute/labs.git'
> 25501 tty2     S+     0:00 /usr/bin/git fetch
> 25502 tty2     S+     0:00 /usr/bin/ssh labs git-upload-pack 'jpmolinamatute/labs.git'

then I have to kill those process manually because they remain alive even when I close vscode.

the second part that I hit this problem is when I set `"git.autofetch": false`  in setting, and then I try to push my changes to the remote repository I included a screenshot of what happen after I click "push"
![vscode](https://user-images.githubusercontent.com/1550713/50045478-0613b900-006a-11e9-9a91-ebe38548a56f.png)

it just hangs in there...

However when I run  `code --disable-extensions .` I set `"git.autofetch": true,` I see an error right away about `/usr/lib/ssh/ssh-askpass` doesn't exists. In Arch Linux doesn't have that exact package, the closest we have is `/usr/bin/qt4-ssh-askpass`. Same error happens when I disable autofetch and try to push.

This is something that it used to work in previous versions.

What can I do to help to debug this problem?

Version: 1.29 & 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.3-naruto

**Comment by IceXPR** [comment]
I am using this command to add the ssh keys to the MacOS keychain:
``` bash
ssh-add -K ~/.ssh/id_rsa
```
It solved my problem with vscode not asking for the passphrase.  For now its a workaround (I still prefer to prompted), but at least I get to stay on vscode to do my coding.
