### ISSUE TITLE
Copy Property Path from Expanded Variable 

### ISSUE THREAD

**Issue by YisraelV** [Microsoft/vscode#65138]
In the Variables panel, you can expand an expression and go down the properties many levels. Sometimes I would like to add the expanded expression as a watch expression, so I don't have to expand it again next time. 

Also it would be useful to copy the full path to the property into the clipboard so you can paste it in a conditional breakpoint.   

**implementation**: when right clicking a property in the Variables panel. open a context menu with the actions 1. **add property as a watch expression** 2. **copy property path to clipboard.**

optionally just double clicking the property would copy it to the watch panel.

Chrome devtools as a similar option "copy property path".

I would be more than happy to do it myself.

Thanks!

**Comment by isidorn** [comment]
![screenshot 2018-12-17 at 10 45 22](https://user-images.githubusercontent.com/1926584/50079059-e060ee00-01e8-11e9-8161-bb9a19689c7a.png)

Copy as expression is copy property path.
And there is already add to watch.
Thanks
