### ISSUE TITLE
File \ Preferences \ User Snippets gets confused if workspace uses a FileSystemProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#65145]
1. Create a workspace that uses a FileSystemProvider, e.g. [Remote FS](https://marketplace.visualstudio.com/items?itemName=liximomo.remotefs)
2. Use VSCode menu to navigate to File \ Preferences \ User Snippets
3. Choose 'New Snippets file for 'myrootname'...
4. Instead of creating a .code-snippets file in the remote .vscode you are prompted for a local filesystem directory in which to create it.

Now manually create xyz.code-snippets in the correct place (i.e. the .vscode subdirectory of the workspace root). Enter a simple snippet, save it, and confirm it gets offered when Ctrl+space is pressed while on a suitable type of file.

Return to File \ Preferences \ User Snippets. Your xyz.code-snippets is offered to you at the top of the quickpick list. But when you select it VSCode tries to open it using a file:// URI. In the case of Remote FS the correct URI begins ftp://

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.15063

**Comment by jrieken** [comment]
What we are missing is a picker for remote file systems... cc @isidorn

**Comment by gjsjohnmurray** [comment]
@jrieken I'm not clear why we need a picker for remote file systems to resolve this. AFAICT the `createGlobalSnippetFile` function won't be happy if I navigate to a directory other than `defaultPath`, because you [don't support snippets in subfolders of .vscode](https://github.com/Microsoft/vscode/issues/8102#issuecomment-423476360)
https://github.com/Microsoft/vscode/blob/3ccc7a9a1f9fa54dfc696b489461b9c376a3064b/src/vs/workbench/parts/snippets/electron-browser/configureSnippets.ts#L123-L139

So maybe replace the call to windowService.showSaveDialog with a simple `showInputBox` to get the xyz.code-snippets filename (perhaps only expect the name, not the file extension), then append this to defaultPath.

**Comment by jrieken** [comment]
> So maybe replace the call to windowService.showSaveDialog with a simple showInputBox to get the xyz.code-snippets filename

Yeah, that's an option but till today we always show the 'official' file dialog when creating files.

**Comment by gjsjohnmurray** [comment]
With respect, in arguably the most common case of creating files (File\New File) the 'official' file dialog isn't used. Instead, we (sensibly) just get an input box at the point in the Explorer filetree where the new file will be created once the user has entered a name for it.
