### ISSUE TITLE
Tooltip request - when I hover over the main icons, VSCode should tell me what they are called

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#65148]
Currently on MacOS and the November 2018 version of VSCode.

When I hover over these buttons:

![screenshot 2018-12-15 17 01 23](https://user-images.githubusercontent.com/11139560/50048871-3029a300-008b-11e9-9d8f-e9e50ad34211.png)

VSCode should provide a tooltip and tell me what those buttons are called (what view they correspond to), at the very least this helps people when they file tickets/issues so that everyone knows what people refer to when they discuss views in the app.

**Comment by ORESoftware** [comment]
I tried it and it wasnt working for me on MacOS

**Comment by sandy081** [comment]
I tried it on MacOS and it works for me. Did you check if hovers are working at other locations in VS Code?
