### ISSUE TITLE
Hiding icons on Activity bar

### ISSUE THREAD

**Issue by vUdav** [Microsoft/vscode#65144]
If I change color theme to Monokai, Quiet Light or Solarized Light, then in my activity bar hiding all icons.

# Screenshots
## Default Dark+
![Default Dark+](http://dl4.joxi.net/drive/2018/12/16/0031/2030/2033646/46/9bc96a5c56.jpg)
## Monokai
![Monokai](http://dl4.joxi.net/drive/2018/12/16/0031/2030/2033646/46/5ddb2a6ca9.jpg)

- VSCode Version: 1.30.0
- OS Version:  macOS High Sierra 10.13.1

Steps to Reproduce:

1. Open settings
2. Change Color Theme to Monokai/Quiet Light/Solarized Light

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@bpasero Any insights?

**Comment by bpasero** [comment]
use devtools to inspect the element?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
