### ISSUE TITLE
[Linux] terminal does not open

### ISSUE THREAD

**Issue by smac89** [microsoft/vscode#65140]
From dev tools console, here is the error:

```
  ERR ioctl(2) failed.: Error: ioctl(2) failed.
    at UnixTerminal.resize (/usr/share/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:213:13)
    at e.resize (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2917:541)
    at e.setDimensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3494:241)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3656:385
    at <anonymous>
```

<details open>
<summary>Version: 1.30.1</summary>
Commit: dea8705087adb1b5e5ae1d9123278e178656186a<br>
Date: 2018-12-18T18:07:32.870Z<br>
Electron: 2.0.12<br>
Chrome: 61.0.3163.100<br>
Node.js: 8.9.3<br>
V8: 6.1.534.41<br>
OS: Linux x64 4.15.0-42-generic
</details>

### Steps to Reproduce:

1. Terminal > New Terminal

Does this issue occur when all extensions are disabled?: Yes

---
If it helps, my default shell is zsh

**Comment by Tyriar** [comment]
Some questions:

- Can you share your settings.json?
- Does the terminal flash when it opens?
- Is that the only error in the console?

**Comment by smac89** [comment]
@Tyriar 

<details>
<summary><b>settings.json</b></summary>

```json
// Place your settings in this file to overwrite the default settings
{
    "files.autoSave": "afterDelay",
    "workbench.statusBar.visible": true,
    "editor.wrappingIndent": "indent",
    "python.formatting.provider": "yapf",
    "editor.wordWrap": "bounded",
    "editor.wordWrapColumn": 120,
    "editor.rulers": [
        80,
        100
    ],
    "workbench.iconTheme": "material-icon-theme",
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "editor.formatOnPaste": true,
    "telemetry.enableTelemetry": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*.pyc": true,
        ".idea/": true
    },
    "diffEditor.ignoreTrimWhitespace": true,
    "explorer.confirmDelete": false,
    "update.channel": "none",
    "reason.codelens.enabled": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "editor.minimap.enabled": false,
    "breadcrumbs.enabled": false,
    "editor.renderWhitespace": "none",
    "editor.mouseWheelZoom": true,
    "editor.fontSize": 15,
    "editor.suggestSelection": "recentlyUsed",
    "editor.quickSuggestionsDelay": 50,
    "workbench.colorTheme": "One Dark Pro Vivid",
    "explorer.confirmDragAndDrop": false
}
```
</details>

#### Does the terminal flash when it opens?
Yes terminal does flash briefly as if attempting to run the initial user config stuff like my `.zshrc` and whatever else zsh might need to start

#### Is that the only error in the console?
Also yes, that is the only error in the console.

---

![Integrated terminal shell](https://i.imgur.com/yujN0HF.png)

I decided to change the default integrated shell which is ran when I open the terminal. I changed the shell to `/bin/bash`, and now the terminal opens and actually loads. However, I am still getting that error in the developer console.

![Running zsh](https://i.imgur.com/T02yCcs.png)
From this new shell, I tried manually running `/bin/zsh`, and nothing happened - the process simply exited. So I decided to trace the command using `strace`, and here is a [**file**](https://gist.github.com/smac89/3ff9f6d8167adc41fbf74f2c79338a15) containing the output.

**Comment by maty974** [comment]
Hi, 

any news/solutions/workaround on this problem ? I've the same error, and can't execute my python Tasks anymore :(

```log
[2019-05-17 13:42:27.393] [renderer1] [error] ioctl(2) failed.: Error: ioctl(2) failed.
    at UnixTerminal.resize (/mnt/disk/applications/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:216:13)
    at d.resize (file:///mnt/disk/applications/code/resources/app/out/vs/workbench/workbench.main.js:2684:270)
    at C.setDimensions (file:///mnt/disk/applications/code/resources/app/out/vs/workbench/workbench.main.js:3819:56)
    at _processManager._processManager.ptyProcessReady.then (file:///mnt/disk/applications/code/resources/app/out/vs/workbench/workbench.main.js:3666:840)
```

My infos:
```
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.10-200.fc29.x86_64
```

**Comment by maty974** [comment]
Hi @smac89 !

did you find a workaround about this issue ? if yes please let me know how ;)

Thanks!

**Comment by Tyriar** [comment]
After https://github.com/microsoft/vscode/pull/73597 gets merged the Insiders build will log the reason ioctl failed which should help here.

**Comment by smac89** [comment]
@maty974 It's been a while since I posted this issue. I am now using [VSCodium](https://github.com/VSCodium/vscodium) on Arch Linux and this problem is no longer present.

I was initially using the official VSCode and was running Ubuntu

**Comment by maty974** [comment]
Hi @Tyriar , I will post more log when this build will be ready thanks!

**Comment by maty974** [comment]
@smac89 , I've tested VScodium but got the same error :(

And finally I've found what was causing the issue! I was using `LD_LIBRARY_PATH` that was set to a custom lib path in my `tasks.json` for running Python code, and it seems that one or more lib was interferring with system one.

Removed this `LD_LIBRARY_PATH` fixed the bug.....

@Tyriar, I don't know if this will help in the #73597 

Anyway thanks for your help guys

**Comment by Tyriar** [comment]
Closing as logging is improved which should help diagnose future issues.
