### ISSUE TITLE
Allow files.enableTrash setting to be defined at folder level

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#65146]
#14638 added a useful setting called files.enableTrash but it can only be defined at User and Workspace level. Please also permit it at Folder level, so the \.vscode\settings.json of a folder root served by a filesystem that doesn't support the concept of delete-to-trash (e.g. the Remote FS extension) can ensure that users aren't given the false illusion of safety when deleting files.

Better still, please resolve #48259

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.15063

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by gjsjohnmurray** [comment]
Closing this now #48259 is present in Insiders
