### ISSUE TITLE
Editor is closing opened file when try to open a new file.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6514]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1.  Launch an app and open smoke test project folder.
2. Click on style.css file under public\stylesheets\style.css
3. Now click on users.js and verify list of opened files under Open Editors.
Actual: Only one file is showing up e.g. users.js
Expected: Both Style.css and Users,js should be displayed in the Open Editors section.
![replacefileinopeneditor1](https://cloud.githubusercontent.com/assets/17735796/15382016/2446cefa-1d3a-11e6-9d42-68fbdcf406c8.gif)

**Comment by weinand** [comment]
@v-pavanp this branch is not yet meant for testing.
