### ISSUE TITLE
Opening other project in new window is too cumbersome (distinction between Workspace and Folder is useless?)

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#65152]
Right now, as far as I can tell, to open a new project in a new window, I have to:

1. Select File -> New Window
2. Wait for the New Window to open
3. Once the new window is open, l then I choose File -> Open, and open the desired folder

There is a step here that is kinda of waste of time - step 2.

![screenshot 2018-12-15 18 17 50](https://user-images.githubusercontent.com/11139560/50049268-032ebd80-0096-11e9-9eca-776712ea456c.png)

The alternative would be to let the other project open to the desired folder in the background, which takes less of my attention and I can do something else while I wait.

Instead, why not Webstorm/Jetbrains's functionality:

1. Choose Open from the `File -> Open` menu
2. Choose the folder you want to open
3. A dialog opens and you choose whether you want it opened in the current window or in a new window.

### Workspace vs. Folder ?

There is _no real difference_ between the _desired project_ and a _desired folder_, so there should not be a distinction. There is no meaningful distinction. Therefore "Open Workspace" is useless, what is point of that? When I choose "Open Workspace" it doesn't filter the folders on the filesystem to just folders that have a .vscode folder in them, does it? Doesn't seem like it, and that would be fairly useless anyway.

IMO you can get rid of the "Open Workspace" option.

![screenshot 2018-12-15 18 28 15](https://user-images.githubusercontent.com/11139560/50049309-42114300-0097-11e9-8cfb-783c6aa32a84.png)

**Comment by DanielHix** [comment]
[Here is something cool you can do with workspaces as compared to just folders.](https://code.visualstudio.com/docs/editor/multi-root-workspaces)

The difference is opening a folder is just what is says, whereas with workspace it generates a workspace file which you can then change things to better suits your project. 

As for the option to either open a folder/workspace in a new window or the current window would be a good addition I feel instead of having to open up a new window and then open the folder/workspace.

**Comment by ORESoftware** [comment]
@DanielHix ok I don't really understand the Workspace thing, but I can let that slide, re:

> As for the option to either open a folder/workspace in a new window or the current window would be a good addition I feel instead of having to open up a new window and then open the folder/workspace.

yes please

**Comment by drevilxing** [comment]
The concepts of workspace and folder are a little difficult for people to grasp just at this context.  Thanks OREsoftware for pointing out this confusing design. Beyond that, I thinks current GUI design need to be improved for those programmers working on IOT software development that may involve several different programming languages and frequent switching between projects using different extensions installed. The GUI should give enough graphic clue to the programmers which extension is in use and which is on the waiting list.

**Comment by DanielHix** [comment]
I submitted this as a feature request #65167 so feel free to comment or anything on that to help it grab traction. I felt as though yours was more of a bug/complaint instead of a feature request. 

This issue can probably be closed.
