### ISSUE TITLE
Terminal not working correctly with Windows 1809 update

### ISSUE THREAD

**Issue by simpert** [Microsoft/vscode#65151]
Since updating to Windows 1809, the integrated terminal display does not load correctly. Upon opening you see nothing when expecting to see the powershell terminal. If you scoll down probably a dozen lines or so and press enter you can see the default powerhsell prompt.

![vscodeterminal](https://user-images.githubusercontent.com/2422222/50049077-2444dd80-0099-11e9-8d26-7f0999ca074a.gif)

I noticed this first on my work computer and I thought something was seriously wrong since I didnt see anything pull up in terminal so I reinstalled vscode and same problem.

I then updated my laptop running Windows 10 Pro and installed vscode (not insiders) for the first time and the same problem exists.

Both computers run 64-bit windows 10 pro. My laptop is a Asus Zephyyrus M. 

If you need more tests of info feel free to contact me but I think this issue should be really easy to duplicate. Simply update to 1809.

**Comment by beastdestroyer** [comment]
Yh it has been pointed out as a regression from the thing that vscode uses (winpty?) amd has become much more worse in 1809, I have experienced this a couple of times, especially if I changed my command prompt/powershell height in properties.
