### ISSUE TITLE
VSCode Incorrect Syntax Highlight in HTML file

### ISSUE THREAD

**Issue by HaoyangFan** [Microsoft/vscode#65154]
- VSCode Version: 1.30.0
- OS Version: macOS 10.13.3

Steps to Reproduce:
code in VSCode window:
<img width="555" alt="screen shot 2018-12-15 at 7 07 03 pm" src="https://user-images.githubusercontent.com/22490077/50049551-d9c56000-009c-11e9-93ce-2471dfc69b95.png">

Note the highlighting of html comment

code shown in Chrome, which has correct comment highlighting:
<img width="379" alt="screen shot 2018-12-15 at 7 10 06 pm" src="https://user-images.githubusercontent.com/22490077/50049566-11cca300-009d-11e9-9593-19ed5dc6100f.png">

**Comment by octref** [comment]
Code to repro?
