### ISSUE TITLE
Enable theming of quick picker

### ISSUE THREAD

**Issue by DHedgecock** [microsoft/vscode#65153]
Hello, I have a theme and would like to be able to set a theme color for the quick picker background which I don't think is currently possible. (I'd like to be able to theme the quick picker to match the background of editor widgets like breadcrumbs)

I forked the repo and found out where to add the theming values in and would love to open a PR!

**Background of quick picker theming**

<img width="1425" alt="screen shot 2018-12-15 at 7 03 19 pm" src="https://user-images.githubusercontent.com/8461733/50049522-66bbe980-009c-11e9-9004-cf3783a87703.png">

**Theme breadcrumbs use the default editor widget background**

<img width="1207" alt="screen shot 2018-12-15 at 7 04 06 pm" src="https://user-images.githubusercontent.com/8461733/50049530-7e936d80-009c-11e9-9ccd-a852c0ae9f67.png">

Thanks!

**Comment by chrmarti** [comment]
Note: I have renamed the colors to `quickInput.background` and `quickInput.foreground`. (Quick Input is the more generic widget and Quick Open will eventually use that too.)

**Comment by bpasero** [comment]
@chrmarti I verified these colors work but I think to really be different from the sidebar we would also need to expose a way to color all other colors in quick input tree independently. That seems not possible currently so a theme author will always have to find the right balance between quick input and side bar background (which I guess was the default).

**Comment by chrmarti** [comment]
@bpasero It seemed we could add more colors later when there is demand from theme authors.

**Comment by chaseadamsio** [comment]
For posterity, as another commenter (and myself, I was confused why the initial PR's values weren't working) pointed out, `quickOpen` from #74041 is now `quickInput`.
