### ISSUE TITLE
minor stylistic bug

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/vscode#65158]
Issue Type: <b>Bug</b>

HI!
There are inconsistent behaviors when find toolbar is open in editor.
with different scenarios:

 - When I open an empty file, and I press Ctrl+F, the editor is shifted below the find toolbar, and line 1 starts from an inappropriate place, like the find toolbar is shifting what is under it:
![screenshot 16](https://user-images.githubusercontent.com/5755214/50052572-53139000-013b-11e9-91b3-d8cb33d6ab84.png)
    and when I start typing something, a more shifting happens, which (seems) is caused by that little git annotation.

- also there is some inconsistent behavior with this find toolbar on non-empty files. If I have the find toolbar open and then open a non-empty line, git-annotation on first line is not shown. But if I first open the non-empty file and then press Ctrl+F, everything looks fine:
![screenshot 18](https://user-images.githubusercontent.com/5755214/50052620-01b7d080-013c-11e9-8da7-6f44e09d8a04.png)
![screenshot 21](https://user-images.githubusercontent.com/5755214/50052622-03819400-013c-11e9-8f5b-ab65ed990346.png)
![screenshot 19](https://user-images.githubusercontent.com/5755214/50052625-0ed4bf80-013c-11e9-9f54-65ef3b03465f.png)

THANKS! Keep up the good work +1

VS Code version: Code - Insiders 1.31.0-insider (ece3a90fb58986570d8afdfb16530c4dd8c743af, 2018-12-14T06:19:42.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (3.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
gitlens|eam|9.2.0
tslint|eg2|1.0.41
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
vscode-nginx-conf-hint|han|0.1.0
Angular2|joh|7.0.1
camelcasenavigation|map|0.3.51
Angular-BeastCode|Mik|7.0.20
vsliveshare|ms-|0.3.1071
vscode-icons|rob|8.0.0
sass-indented|rob|1.4.9
vscode-nginx|sha|0.6.0
move-ts|str|1.11.3
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Azarlak** [comment]
I did some experimenting, and this is what I found:

It seems that ~2 "virtual" lines of&nbsp;sorts are _always_ added at the top of the editor. These virtual lines are not numbered, cannot be selected or marked in any way that I found, and disappear as soon as the find&nbsp;toolbar does.

The inconsistent behavior seems to stem from the&nbsp;fact that in some cases, the editor scrolls down an appropriate distance to adjust for the added virtual lines, and in other cases it doesn't.

This seems to depend mainly on how many lines there are in the file (leftmost column):

|        | When the find toolbar is opened, the editor automatically scrolls downwards | and as a result, "real" lines shift downwards visually by |
| :---: | :---: | :---: |
| <b>File contains more than 2 lines</b> |            ~2 lines           | <sub>2-2=</sub> 0 lines             |
| <b>File contains exactly       2 lines</b> |            ~1 line&nbsp; | <sub>2-1=</sub> 1 line&nbsp;  |
| <b>File contains exactly       1 line </b> | &nbsp; &nbsp;0 lines | &nbsp;<sub>2-0=</sub> 2 lines |

Or as a list:
* more than 2 lines: The editor scrolls down 2 lines, causing the "real" lines to shift 0 lines down visually.
* exactly 2 lines: &nbsp; &nbsp; &nbsp; The editor scrolls down 1 line, &nbsp;causing the "real" lines to shift 1 line down visually.
* exactly 1 line: &nbsp; &nbsp;&nbsp; &nbsp; The editor scrolls down 0 lines, causing the "real" lines to shift 2 lines down visually.

It does not seem to make a difference whether the lines contain anything or are empty.

I have not tested any effects of the git annotation.

**Comment by Ardeshir81** [comment]
Thanks Azar! Good Job +1

**Comment by amunger** [comment]
I don't see any scrolling happening in the latest release. Extra lines are still added at the top to allow you to scroll to see anything that may be covered by the find widget
