### ISSUE TITLE
JavaScript syntax highlighter mistakes

### ISSUE THREAD

**Issue by qifeng0748** [Microsoft/vscode#6515]
- VSCode Version: 1.1.1
- OS Version: Windows10 x64 10586.318

- This example, wrong.
![image](https://cloud.githubusercontent.com/assets/2580757/15381671/2b0d0cfc-1db4-11e6-941e-4f89ba109ed5.png)

- Remove new, right.
![image](https://cloud.githubusercontent.com/assets/2580757/15381681/433b2e4e-1db4-11e6-8aad-55f7479bccb3.png)

- Add (), right.
![image](https://cloud.githubusercontent.com/assets/2580757/15381764/1f676f4a-1db5-11e6-97bb-5c0d75a13895.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#170

**Comment by qifeng0748** [comment]
This is not .ts file, it is .js file.

**Comment by aeschli** [comment]
Our JavaScript grammar is actually a TypeScript grammar and maintained by the TypeScript team.

**Comment by qifeng0748** [comment]
OK, I understand, thank you.
