### ISSUE TITLE
Global menu in Unity does not work anymore in VSCode 1.30.0

### ISSUE THREAD

**Issue by selivan** [Microsoft/vscode#65150]
### Environment

```
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-42-generic
```

### Steps to reproduce
Install VSCode 1.30.0 on Ubuntu 16.04 with Unity desktop.

### Expected results

Global menu correctly displayed, like this:

![image](https://user-images.githubusercontent.com/1208989/50049027-e8873380-00eb-11e9-9887-99b6dc9d0a13.png)

### Actual results

Global menu is not displayed, instead it appears in maximized  window title, eating space:

![image](https://user-images.githubusercontent.com/1208989/50049021-b2e24a80-00eb-11e9-9b63-60b4a7c649c8.png)

**Comment by smac89** [comment]
There is an option to change to native title bar. Did you try !that?

![Screenshot](https://i.imgur.com/HmOZPX1.png)

**Comment by selivan** [comment]
@smac89 Thanks, that helped!

Got no idea why it switched to "custom" after VSCode update, I didn't touch anything in settings.
