### ISSUE TITLE
Font & color rendering

### ISSUE THREAD

**Issue by Baldomo** [microsoft/vscode#65156]
Could be related to  #65132. Fonts are blurry and discolored on the side of letters. 
![Font rendering in DevTools](https://i.imgur.com/7BUtnbl.png)
Editor background is two different colors (subtle but very noticeable).
![Editor background](https://i.imgur.com/NjAo1Z8.png)

- VSCode Version: 1.31.0-insiders (system setup)
- OS Version: Windows 10 Pro (17134)
<details>
    <summary>Full version info</summary>
Version: 1.31.0-insider (system setup)
<br>
Commit: ece3a90fb58986570d8afdfb16530c4dd8c743af
<br>
Date: 2018-12-14T06:19:42.976Z
<br>
Electron: 3.0.10
<br>
Chrome: 66.0.3359.181
<br>
Node.js: 10.2.0
<br>
V8: 6.6.346.32
<br>
OS: Windows_NT x64 10.0.17134
</details>
<br>
Steps to Reproduce:

1. Update VSCode to Insider 1.31.0
2. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Baldomo** [comment]
Nope, latest build doesn't change anything. `--disable-gpu` does, however, solve the issue.
