### ISSUE TITLE
Typescript not recognized

### ISSUE THREAD

**Issue by Siegrift** [Microsoft/vscode#65166]
- VSCode Version: **1.30**
- OS Version: **Linux Mint 18.1 Serena**

Steps to Reproduce:
1. Create a folder with **tsconfig.json** and **index.ts** according to https://code.visualstudio.com/docs/languages/typescript
2. Reload the editor

Does this issue occur when all extensions are disabled?: **Yes**
+ I have tried reinstalling the editor
+ I have also checked that I have typescript installed (tried both globally or locally)
+ Tried the same steps on Windows (and it worked there)

Maybe it's just some silly mistake, but I was not able to find a similar issue so far...

**Comment by mjbvz** [comment]
Please explain what is not working as expected

**Comment by Siegrift** [comment]
@mjbvz Sorry for vague description.

When you open a TypeScript project in vscode, it shoud autoamtically notice it and provide you TypeScript features (autocompletion, type info upon hover, TS errors...). However, I can't see any of these features. Basically, vscode acts like I didn't open a TS project at all. 

I don't know how is this possible, but I've tried many things (one of them was to try it out on Windows) and there it worked...

I'm also adding a screenshot of my issue (run code from terminal using `code --disable-extensions .`).
![vscode-issue](https://user-images.githubusercontent.com/22679154/50095426-7e3bd380-0250-11e9-9081-470c4db7fbb6.png)

**Comment by mjbvz** [comment]
In the extensions view, search `@builtin javascript`. Is the built-in `TypeScript and JavaScript Language Features` extension disabled?

![screen shot 2018-12-17 at 11 32 12 am](https://user-images.githubusercontent.com/12821956/50110557-6b44e700-01ef-11e9-9a1d-fcfdcd0101b3.png)

**Comment by Siegrift** [comment]
@mjbvz thanks :) 

I don't know how this got disabled in the first place though :/
