### ISSUE TITLE
Unstage and clean selected lines short cut

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#6516]
- VSCode Version: 1.1.1
- OS Version: Windows 10

We support staging selected lines in diff view, while we don't have clean or unstage selected lines accordingly. Unstage selected lines is not that frequent as staging does but cleaning selected lines is somewhat useful. For instance, we always make additional modifications (like unexpected code formating, tab to spaces conversion) to code while fixing bugs or adding features, you might just want to revert those unimportant lines to make the commit clean.

What do you think? Is it a valid feature request?

**Comment by joaomoreno** [comment]
cc @isidorn

**Comment by isidorn** [comment]
Makes sense that we should support this since we have the reverse functionality already there. However this is currently not high on our feature list, so a PR would be welcome 🙂

**Comment by rebornix** [comment]
@isidorn thanks, I'll take it.

**Comment by Tyriar** [comment]
Looks like https://github.com/Microsoft/vscode/pull/6897 is fixing this issue too

**Comment by rebornix** [comment]
@Tyriar we have `Stage` and `Clean` on the treeview of git changes, #6897 is adding these two to the right top of diff editor view, but it's still file level operation. #6896 is focusing on selected lines :smile:

**Comment by tht13** [comment]
@Tyriar @rebornix Clarrification: #6897 is adding staging and unstaging of a current file the the `F1` command pallete which also allows it to then also be assigned to a keyboard shortcut. 

The PR can be extended to detect current text selection in a file and stage/unstage those lines as well. This would then require #6896 to be merged first. It could also be done as a second PR.

**Comment by joaomoreno** [comment]
Fixed by #6896
