### ISSUE TITLE
New window or existing window dialog when opening new file/workspace/folder

### ISSUE THREAD

**Issue by ADustyOldMuffin** [microsoft/vscode#65167]
The new feature is simple, and is something I believe Jetbrains does in their toolset. 

Whenever I click one of the following (all or only folder or workspace I'm unsure about a singular file)

![featurerequest](https://user-images.githubusercontent.com/41391321/50056857-53eef680-0128-11e9-885c-acf0d8a8fb78.png)

then I should be presented with a dialog asking if I wish to open it in the current window or a new window.

If I click new window then it should do exactly that and if I choose current then the already existing behavior for that will happen.

**Comment by DanielHix** [comment]
And I would also like to look into implementing this myself if possible.

**Comment by cedric05** [comment]
can i work on it?
