### ISSUE TITLE
Why not square brackets?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#65161]
Since that #62370 had "too many iterations" – here's a brand new issue:

Why hover doesn't use square brackets (just like inline problems & problems panel)?

![screenshot 5](https://user-images.githubusercontent.com/9638156/50053849-a80bd200-014c-11e9-89d4-5a874bcaa9c3.png)

**Comment by beastdestroyer** [comment]
Or the same font for that matter...

**Comment by sandy081** [comment]
Problems view and Inline widget is also changed to be consistent with hover

![image](https://user-images.githubusercontent.com/10746682/50107609-6d309980-0233-11e9-9b96-7b24f83fd8d8.png)
