### ISSUE TITLE
After "Workspaces: Duplicate Workspace in New Window", the new window's workspace becomes "Untitled"

### ISSUE THREAD

**Issue by x-ji** [Microsoft/vscode#65169]
Issue Type: <b>Bug</b>

Whenever I run the command `Workspaces: Duplicate Workspace in New Window`, the newly opened window seems to contain an untitled workspace, even though it apparently contains the same folders and files as the original workspace. Whenever I close that window, it asks me to save the workspace configuration.

It also doesn't have any files open, while I'd expect it to have the same set of files and tabs I already had opened before I ran the command.

1. Open a saved workspace
2. Run the command `Workspaces: Duplicate Workspace in New Window`

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.19.8-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.43GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-hie-server|ala|0.0.24
project-manager|ale|10.0.0
vscode-database|baj|1.5.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
vscode-dash|dee|2.0.0
xml|Dot|2.4.0
gitlens|eam|9.2.0
tslint|eg2|1.0.41
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vscode-firefox-debug|hbe|1.7.3
elixirlinter|iam|0.4.1
elixir-ls|Jak|0.2.24
language-julia|jul|0.11.0-beta.2
language-haskell|jus|2.5.0
dotenv|mik|1.0.1
language-gettext|mro|0.1.1
mssql|ms-|1.4.0
python|ms-|2018.12.1
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
vscode-docker|Pet|0.4.0
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.1
java|red|0.35.0
LiveServer|rit|5.3.1
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
vscode-eex-snippets|ste|0.0.3
language-stylus|sys|1.10.0
org-mode|too|0.5.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.11.3
vim|vsc|0.16.14
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by x-ji** [comment]
Don't think this is related to the new release as it was there in 1.29 as well.

**Comment by bpasero** [comment]
This works as designed, we leverage an untitled workspace to be able to open the same set of folders into a different window. See https://code.visualstudio.com/docs/editor/multi-root-workspaces and use StackOverflow for questions.
