### ISSUE TITLE
nodejs debugger nodemon crush 

### ISSUE THREAD

**Issue by javadbat** [Microsoft/vscode#65163]
i use nodemon in project and it work smooth and good but when i try to run exact gulp command 'gulp serve' in vs code debugger it cuase following error:
'[nodemon] app crashed - waiting for file changes before starting...'
it work really when i type gulp command but in debug mode i get error.
the code is:
 ```
 var nodemonStream = nodemon({
        script: './Server/Bootstrap.js',
        inspect:true,
        done:done
    });
```

**Comment by roblourens** [comment]
>  but when i try to run exact gulp command 'gulp serve' in vs code debugger

Can you explain some more exactly what you are doing?

**Comment by javadbat** [comment]
![image](https://user-images.githubusercontent.com/11534875/50443884-9b406880-091a-11e9-88c3-a88a5b446003.png)
as you see when i use command everythig work perfectly
![image](https://user-images.githubusercontent.com/11534875/50443957-ea869900-091a-11e9-82ed-a50f4b955ef9.png)
but when i use vscode debug tools i get error

**Comment by roblourens** [comment]
That looks right, I don't know why it's crashing. What does the `nodemon get crushed` message mean? Is that coming from your program?

**Comment by roblourens** [comment]
Does it give you a more specific error message? Like from the `e` argument?

**Comment by javadbat** [comment]
no, its undefined
![image](https://user-images.githubusercontent.com/11534875/50572087-1946b880-0dce-11e9-9fc7-2c9a605f7a91.png)
but i can give you remote to test it 
i think it is becuase nodemon cant find './Server/Bootstrap.js' in debugger mode 
![image](https://user-images.githubusercontent.com/11534875/50572129-d9340580-0dce-11e9-91a6-96469484da7e.png)
and in orginal gulp file : 
![image](https://user-images.githubusercontent.com/11534875/50572132-f36de380-0dce-11e9-878e-7ba3a64ebed1.png)

**Comment by roblourens** [comment]
You could try starting it in exactly the same way from the terminal, with `node node_modules/gulp/bin/gulp.js serve` to see if the same thing happens.

**Comment by javadbat** [comment]
![image](https://user-images.githubusercontent.com/11534875/50586699-ec5ada00-0e8f-11e9-9746-83a67de37674.png)
work perfectly in command

**Comment by roblourens** [comment]
What if you run it in the terminal by adding `"console": "integratedTerminal"`?

**Comment by javadbat** [comment]
Can you explain more?
I don't understand what you expected me to do

**Comment by roblourens** [comment]
Try adding this line to your launch config: `"console": "integratedTerminal"` and see what happens

**Comment by javadbat** [comment]
![image](https://user-images.githubusercontent.com/11534875/50725906-acf3ee00-111a-11e9-8aa7-6b6c6a844dd0.png)
say address already in use .
what that mean?

**Comment by roblourens** [comment]
It means there's another running process using that port. Try again and you should get a different port.

**Comment by javadbat** [comment]
i try too many times but always get the same error with different port

**Comment by roblourens** [comment]
Ok, it seems likely that you are putting the gulp process in debug mode, and the nodemon process is taking the same flag and starting in debug mode on the same port. I see you have the `inspect` flag set for nodemon in your gulpfile. That should start nodemon listening on debug port 9229. Try adding `"port": 9229` to your launch config. That should just attach to nodemon instead of starting gulp with the debug lfag.

**Comment by javadbat** [comment]
its get better and execute bootstrap.js 
and then serve app successfully but after some sec it throw error and stop debugging
 
![image](https://user-images.githubusercontent.com/11534875/50833973-16b50780-1368-11e9-8ea5-6d48417474d8.png)

the project run and served without any problem after that but debug mode disapear after select any option on message box

**Comment by javadbat** [comment]
so it's a nodemon bug?

**Comment by javadbat** [comment]
@roblourens  your solution work without problem when i remove `inspect: true` and add `exec: 'node --inspect=9229',` instead and ty for your help but i think we need to submit issue in nodemon repository for this problem.
can you do it ?

**Comment by javadbat** [comment]
![image](https://user-images.githubusercontent.com/11534875/50958122-361d7300-14d5-11e9-8c35-deabb89d842e.png)
![image](https://user-images.githubusercontent.com/11534875/50958156-4c2b3380-14d5-11e9-8943-18fedcb40a8e.png)

**Comment by roblourens** [comment]
I don't know whether it's a gulp-nodemon or nodemon issue.
