### ISSUE TITLE
Console Crashes when Changing File Type

### ISSUE THREAD

**Issue by jkavanagh58** [Microsoft/vscode#65168]
[vscode-powershell.zip](https://github.com/Microsoft/vscode/files/2683812/vscode-powershell.zip)

Issue Type: <b>Bug</b>

Create New File, Change file type using status bar

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.25
vscode-markdownlint|Dav|0.22.0
docs-article-templates|doc|0.1.4
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.2.1
docs-preview|doc|0.3.16
githistory|don|0.4.4
vscode-PSStackoverflow|Dou|0.0.2
gitlens|eam|9.2.0
vscode-npm-script|eg2|0.3.5
vscode-projects-plus|fab|1.21.0
vscode-projects-plus-todo-plus|fab|1.6.9
vscode-todo-plus|fab|4.11.1
vscode-git-tags|how|1.3.1
vstsservicestatus|jep|1.3.0
vbscript|kar|0.5.5
chat|kar|0.8.2
font-awesome-5-codes-html|mrd|1.0.1
PowerShell|ms-|1.10.1
vsliveshare|ms-|0.3.1071
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.4
team|ms-|1.144.1
sharecode|Rol|0.4.1
html5-boilerplate|sid|1.0.3
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|1.0.4
OiC9|xqk|0.0.1

(15 theme extensions excluded)

</details>

PowerShell Extension logs

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell

**Comment by jkavanagh58** [comment]
My bad, I just used the Bug reporter within VSCode
