### ISSUE TITLE
only CSharp extension cannot install.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Microsoft/vscode#6517]
- VSCode Version:
1.1.1
- OS Version:
RHEL 7.2

Steps to Reproduce:

1.  type ``Ctrl+P`` and ``ext install csharp``
2. The status bar at the left bottom remains "installing" status. It doesn' t finish for several hours.

I get into this situation only csharp extension. I can install other extensions such as go, python.
I have a workaround that I install csharp extension other Linux distro machine and copy ~/.vscode/extensions/ms-vscode.csharp-1.0.11 to RHEL machine. 
However, I'd like to know the root cause. Could you help me?

**Comment by joaomoreno** [comment]
Strange... does it repro after a restart?

**Comment by joaomoreno** [comment]
Duplicate of #6347
