### ISSUE TITLE
Task property "presentation": {"reveal": "never"} is not working

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#65179]
Issue Type: <b>Bug</b>

I created a simple Task and added the presentation item, hoping that that would allow me to never show the integrated terminal (as it is reported in the doc at 
`https://code.visualstudio.com/docs/editor/tasks#vscode`
.but it isn't working. It always shows the integrated terminal.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Py3 Help",
            "type": "shell",
            "command": "C:\\Python354-32\\Doc\\python354.chm",
            "problemMatcher": [],
            "presentation": {
                "reveal": "never"
            }
        }
    ]
}
```

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz (8 x 1596)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.93GB (0.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
vscode-great-icons|emm|2.1.46
git-project-manager|fel|1.7.1
python|ms-|2018.12.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.4

</details>

**Comment by alexr00** [comment]
I can't reproduce this. Can you try running without extensions to see if it still happens then? I'm testing with:

    {
			"type": "shell",
			"label": "Run echo task",
			"command": "echo hello",
			"problemMatcher": [],
			"presentation": {
				"reveal": "never"
			}
		}

The integrated terminal does not show, and when I check the terminals that are currently open I can see the terminal with the task running.

**Comment by jcrmatos** [comment]
Hello,

You are correct. I would never though that the Python extension would have this effect.
If I disable the Python extension the terminal doesn't show.
With it enabled it show again.
I will report it in their issue tracker.

Thanks for the help.

Best regards,

JM
