### ISSUE TITLE
ANSI coloring is off in DOM-based terminal

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#65172]
Issue Type: <b>Bug</b>

The displayed colors do not match the expected colors. If one prints 360 hue values at full saturation and middle lightness (i.e. the fully saturated color wheel) one of the lines gets assigned the `xterm-fg-0` class, which is black. The colors are supposed to get lighter at that point so that makes little sense to me:

![image](https://user-images.githubusercontent.com/834235/50058171-cab1e100-0174-11e9-8b1c-ccc1dc81766f.png)

`gnome-terminal` for reference:

![image](https://user-images.githubusercontent.com/834235/50058197-22e8e300-0175-11e9-98fe-de113bee93e9.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.18.7-arch1-1-ARCH

**Comment by Tyriar** [comment]
Tracked in https://github.com/xtermjs/xterm.js/issues/484
