### ISSUE TITLE
Shrink/expand selection isn't working corretly in Python

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#65177]
Issue Type: <b>Bug</b>

When shrinking/expanding the selection (Shif+Alt+Left/Right) within a function in Python, the expansion isn't working correctly.
This is an example:
```
def start_hash_checker():
    # type: () -> None
    """Start hash checker using prog_launcher.

    () -> None
    """
    if not lcl.msgs['SELECT_HASHES_FILE'] in top_level_windows():
        script_name = ('uniclave_hash_checker.py'
                       if isfile('uniclave_hash_checker.py')
                       else 'uniclave_hash_checker.pyc')  # type: str

        # cmd_line = sys.executable + ' ' + base.APP_DIR + script_name  # type: str
        cmd_line = (dirname(sys.executable) + r'\pythonw.exe ' + base.APP_DIR
                    + script_name)  # type: str

        fops.save_txt(cmd_line, bpl.PROGS_TO_LAUNCH_PN)
        # TODO: Error handling.

```
If I'm on the cmd_line and press Shift+Alt+Right several times, it should select the current line (including the continuation), then the current block inside if (including) and then the current block inside def (including).

But that is not what is happening.

It starts be selecting portions of the line then the continuation of the line and then it jumps to select the all file.

And the opposite (when shrinking) also occurs (Shift+Alt+Left).

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz (8 x 1596)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.93GB (0.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
vscode-great-icons|emm|2.1.46
git-project-manager|fel|1.7.1
python|ms-|2018.12.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.4

</details>

**Comment by jrieken** [comment]
We are in the process of defining extension API for this. Once that's is done, extensions can provide correct data. Something our heuristics cannot.
