### ISSUE TITLE
There is no document formatter for 'django-html'-files installed.

### ISSUE THREAD

**Issue by zaid-khan** [Microsoft/vscode#65189]
Issue Type: <b>Bug</b>

I'm currently working on a django project. Pressed the shortcut of `CTRL + SHIFT + I `(also used the other format selection one through the command palette).

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.44GB (7.03GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.2
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
material-icon-theme|PKi|3.6.1

</details>

**Comment by hehe24h** [comment]
Me to, MACOS version.

**Comment by octref** [comment]
If you are following this setup:

```json
"files.associations": {
    "**/templates/*.html": "django-html",
    "**/templates/*": "django-txt",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements"
},
```

Your html files are marked as `django-html` files, and you need to specify a formatter for it.

Use either https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify or change settings for your prettier extension.

**Comment by thibault** [comment]
Hi,

I know this issue is closed, but since googling the error message leads here, I could not find a better way to ask my question.

@octref You said:

> Your html files are marked as django-html files, and you need to specify a formatter for it.

For the life of me, I could not find a way to do it. Reading [this doc](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) it seems like the only two options are either to associate your file with a known file type (e.g `html` instead of `django-html`) or to install a formatter that specifically targets the custom file type (and there currently seems to exist no formatter that handle `django-html` files).

Would you happen to be able to point me in the right direction in order to allow me to associate an existing formatter with a custom-defined file type?

**Comment by octref** [comment]
js-beautify seems to allow it, for example:

```
{
  "beautify.language": {
    "js": {
      "type": ["javascript", "json"],
      "filename": [".jshintrc", ".jsbeautifyrc"]
      // "ext": ["js", "json"]
      // ^^ to set extensions to be beautified using the javascript beautifier
    },
    "css": ["css", "scss"],
    "html": ["htm", "html", "django-html"]
    // ^^ providing just an array sets the VS Code file type
  }
}
```

**Comment by octref** [comment]
js-beautify seems to allow it, for example:

```json
{
  "beautify.language": {
    "js": {
      "type": ["javascript", "json"],
      "filename": [".jshintrc", ".jsbeautifyrc"]
      // "ext": ["js", "json"]
      // ^^ to set extensions to be beautified using the javascript beautifier
    },
    "css": ["css", "scss"],
    "html": ["htm", "html", "django-html"]
    // ^^ providing just an array sets the VS Code file type
  }
}
```

**Comment by thibault** [comment]
Awesome ! Thank you @octref, that seems to make it.

For a reference purpose, this is the minimal set of changes I added to my user settings for the change to take effect :

```json
    "beautify.language": {
        "html": [
            "htm", "html", "django-html"
        ]
    }
```
