### ISSUE TITLE
opened-file's content overlaps with vscode

### ISSUE THREAD

**Issue by Saitamata** [Microsoft/vscode#65185]
### vscode reopen bug?  
---  

#### vscode version  
---  
```  
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```  

#### Environment  
---  
> `PC: Dell PC`  
> `OS: Win10 X64`   

#### Description  
---  
1. I opened the linux kernel src files with vscode  
```
    ...\linux-2.6.32-431.el6\net\core\dev.c
    ...\linux-2.6.32-431.el6\net\ipv4\ip_gre.c
    ...
``` 

2. dev.c's content looks like:  
![dev_c_ok](https://user-images.githubusercontent.com/28283931/50065166-fc1bc280-01ef-11e9-89c2-6fe1668f98b9.jpg)  

3. ip_gre.c's content looks like:  
![ip_gre_ok](https://user-images.githubusercontent.com/28283931/50065174-0e95fc00-01f0-11e9-9d1d-cc80e4500e75.jpg)  

4. But sometime, dev.c's content shows in ip_gre.c's opening window:   
![bug_here](https://user-images.githubusercontent.com/28283931/50065186-1f467200-01f0-11e9-83c7-78c0d1fe972e.jpg)  

5. Restart vscode once more, it works fine.  

6. This situation may happens between others source file.  

7. I have tried many times, but happens once in a while.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
