### ISSUE TITLE
Git: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Ardeshir81** [microsoft/vscode#65188]
Issue Type: <b>Bug</b>

HI!
Everything was fine until I added two keyboard shortucts to my `Keyboard Shortcuts` settings page (Ctrl+k, Ctrl+s)

I added:
 - `Ctrl + Shift + G` , `Ctrl + A` to `Stage All Changes`
and 
 - `Ctrl + Shift + G` , `Ctrl + S` to `Stage Change`

and now when I open source control pane, I select a file &  do `Ctrl + Shift + G` , `Ctrl + S`, I get this error:
![screenshot 2](https://user-images.githubusercontent.com/5755214/50072836-d42a6000-01eb-11e9-94e8-a95044106f9f.png)

I have done this shortcuts with a previous installation of windows 10 + code insiders and am sure it worked until yesterday morning. But I reinstalled my windows 10 yesterday (same version as before) and installed vs-code-insiders again (same version as before), But this time I'm getting this error

I also tried with my add-ons/extensions disabled, still the same error!

P.S.
But the `Ctrl + Shift + G` , `Ctrl + A`  shortcut (Stage All Changes) works perfectly! Strange :)

THANKS!

VS Code version: Code - Insiders 1.31.0-insider (ece3a90fb58986570d8afdfb16530c4dd8c743af, 2018-12-14T06:19:42.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (3.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.2.1
tslint|eg2|1.0.41
prettier-vscode|esb|1.7.2
camelcasenavigation|map|0.3.51
vsliveshare|ms-|0.3.1071
vscode-docker|Pet|0.4.0
vscode-icons|rob|8.0.0

</details>

**Comment by joaomoreno** [comment]
Unfortunately there is no support to configure the `Stage Change` command to a keybinding.

/duplicate #24916

**Comment by Ardeshir81** [comment]
@joaomoreno Thanks for your reply!
But as I mentioned I did it already in a previous version of Windows & VS-Code (it was just last week) and it worked fine.
I did the same thing exactly with `Ctrl + Shift + G` , `Ctrl + S`

And yes! I'm pretty sure

**Comment by joaomoreno** [comment]
Oh I missed that, let me check...

**Comment by edespong** [comment]
Are you sure that you are not confusing 'Stage Change' with 'Stage Change**s**'. The latter works as expected for me. I cannot find where the former is used.

**Comment by fabb** [comment]
I get the same error when I execute the "Git: Revert Change" command (VSCode 1.40, 1.39). It worked on previous VSCode versions too (I'm not sure when it broke exactly). There is no error output in the Git Log.

![Screenshot 2019-11-08 at 10 20 28](https://user-images.githubusercontent.com/153960/68464834-9d997180-0211-11ea-9430-8618ee870e45.png)

**Comment by Ardeshir81** [comment]
@edespong sorry I missed your question.

I don't encounter this issue anymore and don't know how to reproduce it now. I don't remember that it was `stage change` or `stage changes`

**Comment by wolray** [comment]
> I get the same error when I execute the "Git: Revert Change" command (VSCode 1.40, 1.39). It worked on previous VSCode versions too (I'm not sure when it broke exactly). There is no error output in the Git Log.
> 
> ![Screenshot 2019-11-08 at 10 20 28](https://user-images.githubusercontent.com/153960/68464834-9d997180-0211-11ea-9430-8618ee870e45.png)

Same on my windows 10 (VSCode 1.40.1, Git 2.21.0.windows.1)

**Comment by foursixnine** [comment]
I get also the same problem on Linux, insider's edition, any pointers on where to look to try and fix it?

**Comment by drschwabe** [comment]
Same issue here. Get the error when pressing "CTL+g" after setting that as hotkey for "Git: Stage changes" .   Pressing F1 and then selecting that operation however does work as intended.   

I like "CTRL+g" to stage changes it seems intuitive to me.  

Though being able to map a hotkey to stage a specific block vs the entire fire would be better; in that case I'd probably map CTRL+shift+g to whole file and CTRL+g to single block.

**Comment by fabb** [comment]
> I get the same error when I execute the "Git: Revert Change" command (VSCode 1.40, 1.39). It worked on previous VSCode versions too (I'm not sure when it broke exactly). There is no error output in the Git Log.
> 
> ![Screenshot 2019-11-08 at 10 20 28](https://user-images.githubusercontent.com/153960/68464834-9d997180-0211-11ea-9430-8618ee870e45.png)

I found out that the "Git: Revert Change" command only works when there is an active selection. In IntelliJ it also works without selection, and just resets the hunk at the current cursor position, which is very helpful. Should I create a separate ticket for this?

**Comment by dungmidside** [comment]
Is there any update on this ? 
I also had this issue when binding shortcut for `git.revertChange`
![image](https://user-images.githubusercontent.com/16059174/101569715-94c43200-3a07-11eb-94ca-16a73bf04050.png)
