### ISSUE TITLE
serialport module is not ready of electron 3.0

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#65186]
**This is NOT a VS Code bug, just a notification.**

[serialport](https://www.npmjs.com/package/serialport) is a popular node module to handle serial port, and widely used in node projects. However, serialport hasn't been ready for electron 3.0, yet. (see https://github.com/node-serialport/node-serialport/issues/1672)

Some famous VS Code extensions depend on this module as well (such as [Arduino](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino)). If VS Code apply the change to stable channel, these extensions may break.

Please consider this block issue of serialport before apply the change to the next stable version.

I have also [told](https://github.com/node-serialport/node-serialport/issues/1672#issuecomment-447728865) serialport owners about current VS Code status, and hope them can make electron 3.0 support available soon.

Thank you.

**Comment by bpasero** [comment]
We will ship with Electron 3.0.x early February. node.js 10.x LTS has been out for several months by then. We do not recommend native modules for extensions: https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles#_can-i-use-native-nodejs-modules-with-my-extension

Please work with that module to be compatible with the current LTS of node.js.

**Comment by Sneezry** [comment]
Thanks @bpasero 

We're making tools for IoT devices, so serial port is a must feature. I will keep looking for better ways to make it done instead of using binary dependencies.
