### ISSUE TITLE
Allow to place tabs left, right or bottom of workspace

### ISSUE THREAD

**Issue by stephanmullerNL** [microsoft/vscode#65193]
It would be good for ultra-wide monitors to save vertical space and make more tabs to visible: allow to locate them at left or right edge of the editor. For consistency, I also suggest allowing to place them at the bottom.

**Comment by bstst** [comment]
Wonder why this feature isn't requested more often. It would be such a blessing for people who tend to have more open files. Custom sorting them (by path, by name etc) would also be a amazing.

**Comment by dadvir** [comment]
+1

**Comment by santiagopuentep** [comment]
I just opened a new issue for this. In total the duplicates of this issue have 57 upvotes so this one many be accepted if we like it enough. Please upvote!

https://github.com/microsoft/vscode/issues/108264

**Comment by SheepDomination** [comment]
Isn't there only currently a hack per se for this issue ?
