### ISSUE TITLE
EOL formatting change, from LF to CRLF

### ISSUE THREAD

**Issue by LeonardoSidney** [Microsoft/vscode#65199]
Issue Type: <b>Bug</b>

The file is marked as modified, and it is possible to commit, but the commit is not performed and it has an error.
 - take a file previously commited with EOL using FL
 - change EOL to CRFL
 - save file (ctrl + s)
 - try commit change

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3210 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.96GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
vscode-toggle-quotes|Bri|0.3.2
vscode-standardjs|che|1.2.3
jquerysnippets|don|0.0.1
gitlens|eam|9.2.1
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.7.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
vscode-firefox-debug|hbe|1.7.3
beautify|Hoo|1.4.7
mysql-syntax|jak|1.3.1
vscode-phpfmt|kok|1.0.30
vscode-language-pack-pt-BR|MS-|1.30.2
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.1
vscode-icons|rob|8.0.0
git-merger|sha|0.4.1
bootstrap4-vscode|the|6.0.3
html-snippets|wge|0.1.5
vscode-js-console-utils|wht|0.7.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by octref** [comment]
You probably needed to disable prettier formatter for your HTML files:

```
	"prettier.disableLanguages": [
		"vue",
		"handlebars"
	],
```
