### ISSUE TITLE
workbench.editor.showTabs changed to false after VSCode upgrade to 1.30

### ISSUE THREAD

**Issue by msageryd** [Microsoft/vscode#65197]
- VSCode Version: 1.30 (nov 2018)
- OS Version: OSX 10.14.1 (Mojave)

Efter upgrading to 1.30 my tabs disappeared. After some digging I found that `workbench.editor.showTabs` was set to false. I haven't touched this setting, for sure. Did the upgrade tamper with my workbench settings?

**Comment by bpasero** [comment]
Moving to @sandy081 for settings changes. I did not add code like this, but in theory any extension can write to settings.

**Comment by sandy081** [comment]
@msageryd I would not think so. Can you please check if there are any extensions updating this setting?
