### ISSUE TITLE
[TypeScript] Required properties should be on top of suggest

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#65195]
```typescript
interface Inter {
	a: string;
	b?: string;
	c: string;
	d?: string;
}

const obj: Inter = {
	|
};
```
Invoke suggest at `|`.

Actual (Insiders):
```typescript
a
b?
c
d?
```
Expected (Stable):
```typescript
a
c
b?
d?
```
VS Code version: Code - Insiders 1.31.0-insider (ece3a90fb58986570d8afdfb16530c4dd8c743af, 2018-12-14T06:19:42.976Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
Actually the same issue exists in Stable if they are in multiple files:

**`1.ts`**
```typescript
export interface Inter {
	a: string;
	b?: string;
	c: string;
	d?: string;
}
```
**`2.ts`**
```typescript
import { Inter } from '1';

const obj: Inter = {
	|
}
```

**Comment by usernamehw** [comment]
@mjbvz, not sure if this issue slipped inbox or not since it doesn't have labels...

**Comment by mjbvz** [comment]
Closing this as out of scope since it hasn't had additional feedback since being opened. 

I personally think that the current ordering is more consistent and better matches how intellisense works for other contexts / langauges
