### ISSUE TITLE
Improve folder sort order for Window Menu

### ISSUE THREAD

**Issue by Rycochet** [microsoft/vscode#65198]
VSCode version: 1.30.0

The Window menu lists all open windows, but quite often I'll open a window in a folder (via `code .`) - and then when editing the project I'll have to search to find which actual window I want to swap back to as the menu order changes depending on which files are selected.

Currently the display is -
* `filename1 - folder1`
* `filename2 - folder2`

Then when you change the file being opened it'll re-sort alphabetically -
* `filename2 - folder2`
* `something - folder1`

I'd like to have the option of either putting the folder name first, or choosing to sort by folder, so the filenames look our of order.

`editor.menuWindowSorting` = `"Filename"` (default), `"Folder"`, `"Folders list"`

`"Folder"` -
* `something - folder1`
* `filename2 - folder2`

`"Folder list"` -
* `folder1 - something`
* `folder2 - filename2`

**Comment by ccutrer** [comment]
I found this because this was my number one complaint about VSCode. I have 32 windows open - the Window menu is utterly useless with the current sorting. Then I realized the Switch Window command (^W keyboard shortcut by default for me) completely solves my need to use the Window menu at all.
