### ISSUE TITLE
Ability to format document is lost, specifically XML

### ISSUE THREAD

**Issue by joe-oli** [Microsoft/vscode#65190]
Issue Type: <b>Bug</b>

1. File \ New File (or create new file)
2. select language mode to XML (bottom right hand corner)
3. Paste unformatted XML
4.  Format Document (shift+Alt+F) format entire active file
5. Nothing happens.
I was using version 1.29.1. After upgrading to 1.30.0 this stopped working. 

Problems: 
a) firstly the "Format Document" menu item disappeared from the usual place. I had to waste 5 minutes and googling to find out where it disappeared to, now hidden a few levels inside Command Pallette. Why ? it was conveniently easy to find for such a useful item, why hide it now?

b) Only after disabling all extensions, if I attempt shift+Alt+F again, now I see an info message "there is no document formatter for xml-files installed." I don't recall having to separately install this in earlier versions. For such a common file format as XML shouldn't this be built-into VS?

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.70GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
code-beautifier|mic|2.1.0

</details>

**Comment by mjbvz** [comment]
We don't ship a built-in xml formatter. This would have to come from an extension
