### ISSUE TITLE
make quickFixWidget keyboard shortcuts configurable

### ISSUE THREAD

**Issue by hesxenon** [microsoft/vscode#65191]
Currently (1.30.0) it doesn't seem possible to navigate the quickFixWidget with custom keybindings.

This normally wouldn't be a problem, but as I'm using keybindings to not have to move away from the alphanumeric cluster, it is kinda annoying to have to do it for this single feature; especially when there's a taunting `when` clause for it :slightly_smiling_face:

**Comment by mjbvz** [comment]
By `quickFixWidget`, do you mean the menu that pops up when you click the lightbulb?

**Comment by hesxenon** [comment]
exactly, yes. That is what it's called, isn't it?

**Comment by jrieken** [comment]
It's a native menu which we don't control... Maybe custom menus (only linux/win) could support this.

**Comment by sbatten** [comment]
@hesxenon as a colemak mod-dh user myself, I understand that pain. I actually have an AutoHotKey script that allows me to use CapsLock as a toggle for knei as arrow keys.

**Comment by hesxenon** [comment]
well thats an interesting workaround, will def do that until a solution
arrives
