### ISSUE TITLE
VS is really slow

### ISSUE THREAD

**Issue by mguerrero-strat** [Microsoft/vscode#65205]
Issue Type: <b>Bug</b>

Its really very slow to load now

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.7.2
vscode-new-file|dku|4.0.2
githistory|don|0.4.4
prettier-vscode|esb|1.7.2
file-icons|fil|1.0.16
svn-scm|joh|1.46.4
vscode-gist|ken|1.2.1
dotenv|mik|1.0.1
heroku-command|pko|0.0.8
view-in-browser|qin|0.0.5
guides|spy|0.9.2
bootstrap4-vscode|the|6.0.3
shell-launcher|Tyr|0.2.0
colonize|vms|2.2.2
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by choreno** [comment]
Same issue at here. 
I am still using vs code 1.25 which has no problems to load UI during startup.
From 1.26, it's very very slow. Now it's 1.30, it still slow ~~~~

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by choreno** [comment]
I think you guys are already have lots of information for this slowness issue during startup.
Just get Win7 x64 os and install your VS code latest version(after v.1.25) and try to run it. 
You will see first welcome UI after more than 20 sec !!!!.

**Comment by jrieken** [comment]
@choreno what you are seeing is https://github.com/Microsoft/vscode/issues/56644.

**Comment by choreno** [comment]
yes. similar issue. please check this. it may related on this electron issue. https://github.com/electron/electron/issues/16099

**Comment by jrieken** [comment]
@mguerrero-strat for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thankss

**Comment by choreno** [comment]
OK I download it from #56644, "VSCodeUserSetup-x64-1.31.0-exploration.exe".
It works and fast like 1.25.  |o|
Thanks for your help.

**Comment by choreno** [comment]
I hope see the official version soon with Electron4. Thanks.

**Comment by jrieken** [comment]
ping @mguerrero-strat
