### ISSUE TITLE
White space trigger all snippet suggestions

### ISSUE THREAD

**Issue by sunxen** [Microsoft/vscode#65200]
When an extension use API `registerCompletionItemProvider` like this
```
vscode.languages.registerCompletionItemProvider({ scheme: 'file' }, provider, ' ');
```
Typing white space will trigger all default snippet suggestions, **even the provider return empty list**.
Appears from that version 1.30

![image](https://user-images.githubusercontent.com/1832805/50083423-b3372e80-022e-11e9-98d0-6213e319c461.png)

- VSCode Version: 1.30
- OS Version: Win & Mac

Steps to Reproduce:

1. Build an extension use API `registerCompletionItemProvider` with param `triggerCharacters` = ' '
2. Active the extension, then type white space to trigger suggestions

It's not about the extension but the suggestions feature.
Do empty string make snippet filter not work?

**Comment by jrieken** [comment]
Yes - snippets are always being shown unless you use `"editor.snippetSuggestions": "none"`

**Comment by sunxen** [comment]
> Yes - snippets are always being shown unless you use `"editor.snippetSuggestions": "none"`

**The default performance:**
type 'f' show snippets starts with 'f',
type ' ' do not show snippets.

**but if there is 'registerCompletionItemProvider', performance like this:**
type 'f' show snippets starts with 'f',
type ' ' show all snippets.
