### ISSUE TITLE
Open keybindings icon disappears

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#65204]
Issue Type: <b>Bug</b>

![dis](https://user-images.githubusercontent.com/9638156/50090492-bc69d080-0219-11e9-82bb-53fd7dc4d095.gif)

VS Code version: Code - Insiders 1.31.0-insider (edf1090b8546ad0d17f30bf6f8075613e37e1b37, 2018-12-17T10:06:30.031Z)
OS version: Windows_NT x64 10.0.17763

**Comment by anirudhrb** [comment]
@sandy081 
Adding `tabIndex: -1` to `div.keybindings-editor` makes it focusable and fixes the issue.
In `keybindingsEditor.ts`, line 108 needs to be changed to:
```ts
const keybindingsEditorElement = DOM.append(parent, $('div', { class: 'keybindings-editor', tabIndex: -1 }));
```

Is this an acceptable fix? Shall I raise a PR?

**Comment by sandy081** [comment]
@anirudhrb Yeah it is acceptable. Please create a PR.

**Comment by usernamehw** [comment]
@anirudhrb, there's a yellow border in that case and it breaks <kbd>Shift</kbd>+<kbd>Tab</kbd>.

**Comment by anirudhrb** [comment]
@usernamehw Where is that yellow border? And what exactly is breaking in <kbd>Shift</kbd>+<kbd>Tab</kbd>? Works fine for me.

**Comment by usernamehw** [comment]
![demo](https://user-images.githubusercontent.com/9638156/50643503-6918b180-0f7f-11e9-9366-18766aa68cbc.gif)

**Comment by usernamehw** [comment]
<kbd>Shift</kbd>+<kbd>Tab</kbd> (when focus is on input) should focus menu (three dots). And the icon `{}` should remain in place.

**Comment by anirudhrb** [comment]
Oh I see it now. I am getting a blue border that is barely noticeable. I will fix that. Thanks!

When focus is on input, I believe <kbd>Shift</kbd>+<kbd>Tab</kbd> move focus to the "Record keys" button  (thats on the far right of the input box) and so on. That's how it is happening in the latest release version too.

**Comment by usernamehw** [comment]
@anirudhrb, That's what pressing <kbd>Tab</kbd> should do.

<kbd>Shift</kbd>+<kbd>Tab</kbd> is a reverse command of that and should move focus in the opposite side - in this case to editor actions menu (and the `{}` icon should be in place to be available for pressing by <kbd>Enter</kbd>).

**Comment by anirudhrb** [comment]
Oh! My bad! Will look into it.

**Comment by jeanp413** [comment]
@anirudhrb, I think you should do the same as in settingsEditor2.ts and set the key to true in the setInput method 
https://github.com/Microsoft/vscode/blob/dc261e04364542f6114d0e838b7fedf18ee505b7/src/vs/workbench/parts/preferences/electron-browser/settingsEditor2.ts#L202-L205
and remove this listeners
https://github.com/Microsoft/vscode/blob/dc261e04364542f6114d0e838b7fedf18ee505b7/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L114-L118
