### ISSUE TITLE
Sub menu not working when scrolling menus is enabled.

### ISSUE THREAD

**Issue by healer2030** [Microsoft/vscode#65206]
Issue Type: <b>Bug</b>

To reproduce, resize your VS Code to activate scrolling menu. Go to the file menu, and select a sub menu like preferences

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-5300B APU with Radeon(tm) HD Graphics    (2 x 3394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.20GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-sqlite|ale|0.3.2
vscode-json|and|1.4.2
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
jshint|dba|0.10.20
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
referenceshelper|gay|0.2.3
vscode-phpfmt|kok|1.0.30
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
es6-css-minify|olb|2.2.0
vscode-docker|Pet|0.4.0
java|red|0.35.0
vscode-yaml|red|0.1.0
format-html-in-php|rif|1.3.8
unity-debug|Uni|2.6.6
vscode-java-debug|vsc|0.16.0
vscode-react-native|vsm|0.7.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by sbatten** [comment]
@healer2030 I cannot reproduce this issue, when menus are scrollable, submenus remain working for me.
