### ISSUE TITLE
Cpp gdb launch failure on 1.30 (NullReferenceException)

### ISSUE THREAD

**Issue by TheCoolRob** [Microsoft/vscode#65202]
- VSCode Version: code_1.30.0-1544567151_amd64.deb
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Set up a gdb build project in vs code 1.29
2. Build and debug simple project. Debug startup message appears in debug console:
```
=thread-group-added,id="i1"
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
```
etc.
2. Upgrade to 1.30
3. Try debug exactly the same executable (no rebuild required) 
4. Debug console error message appears: `Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object`
5. Downgrading back to 1.29 resolves the launch issue.

When launching code with --disable-extensions I receive the message `Configured debug type 'cppdbg' is not supported.`

**Comment by blackdeman** [comment]
I am facing exactly the same issue. Environment:
- VSCode: 1.30.0 (code-1.30.0-1544567256.el7.src.rpm)
- OS: CentOS 7.6.1810 (Linux x64 3.10.0-957.1.3.el7.x86_64)

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode-cpptools/issues/2922
