### ISSUE TITLE
Debug Console hangs after getting the focus when many lines are printed

### ISSUE THREAD

**Issue by dubeg** [Microsoft/vscode#65213]
- Version: 1.31.0-insider (user setup)
- Commit: edf1090b8546ad0d17f30bf6f8075613e37e1b37
- Date: 2018-12-17T10:06:30.031Z
- Electron: 3.0.10
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763
- Machine: Surface Book 2 (if it helps)

Steps to Reproduce:

1. Create a new dotnet console app.
2. In Program.cs:
```
using System;
namespace Console1
{
    class Program
    {
        static void Main(string[] args)
        {
            for(int i = 0; i < 5000; i += 1) {
                Console.WriteLine("-");
            }
        }
    }
}
```
3. Run it.
4. Try switching to the Debug Console, then to the terminal, and back. On my machine, it will hang a few seconds everytime I switch to the Debug Console. If I increase the loop iteration count, it will hang for longer.

At 2000 iterations, it's still fast. At 3000, it hangs for ~1s.

Just to clarify, it only hangs when the Debug Console receives the focus and its panel becomes visible, but after the hang, scrolling it doesn't cause any hang, or so it seems at the iteration count I tried.

Does this issue occur when all extensions are disabled?: no, I think I need Omnisharp to debug. It's the only extension installed however.

**Comment by isidorn** [comment]
Yes I can repro this, here's a javascript program for easier repro:
```
for (var i = 0; i < 5000; i++) {
    console.log('-');
}
console.log('END');
```

After profiling this it seems the `AsyncDataTree.setChildren` is taking most of the time.
Thus assigning to @joaomoreno so he can investigate if performance could be improved for trees with 5000+ elements.

Also here's the profile

[Profile-20181218T111334.json.txt](https://github.com/Microsoft/vscode/files/2689981/Profile-20181218T111334.json.txt)

**Comment by joaomoreno** [comment]
@isidorn Was this an issue with the old tree as well?

**Comment by isidorn** [comment]
@joaomoreno I just tried 1.29.1 stable which uses the old tree and I can not reproduce this problem.
So the old tree was behaving better here.

**Comment by dubeg** [comment]
Just tried your patch, doesn't hang even at 1,000,000 lines. Nice & thank you!

**Comment by isidorn** [comment]
It's the magic of Christmas

**Comment by dubeg** [comment]
Was the fix reverted? I started getting this issue again after today's Insiders update.

**Comment by dubeg** [comment]
Ha, I checked the history for asyncDataTree and it seems the fix is there, but I guess something is causing this. Profiling the same Program.cs as above seems to indicate setChildren as still being the culprit. Should I open a new issue?

I found a workaround in the meantime, `"console": "integratedTerminal"` in launch.json.

**Comment by isidorn** [comment]
Let's reopen and investigate again. Thanks!

**Comment by joaomoreno** [comment]
@dubeg Thanks for keeping us on our tippytoes!

**Comment by dubeg** [comment]
@joaomoreno I'm trying your patch right now. Perf is certainly better, but it's not ideal yet I think. With  50,000 lines, after launching a new debugging session, VSCode will open the debug console then take about 10s to complete and print the execution time. If I restart the debug session by clicking the green arrow, VSCode won't automatically open the debug console then, so I have to open it manually, but when I do so, it takes about 1s to complete and print the execution time. It's weird. Do you think you can do something about that initial debug session performance?

I took a video with OBS, I hope it helps.
[CaptureObs.zip](https://github.com/Microsoft/vscode/files/2808488/CaptureObs.zip)

**Comment by dbaeumer** [comment]
Verified by using the steps from https://github.com/Microsoft/vscode/issues/67222
