### ISSUE TITLE
Bad TS syntax coloring

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#65211]
Check out `asyncDataTree.ts:535` in `419d5bbaedebef63cff9bc248f8407cda5d40562`.

Coloring seems broken:

![screenshot from 2018-12-17 15-44-35](https://user-images.githubusercontent.com/22350/50094129-b4f2f900-0212-11e9-924b-bbce4d6f470a.png)

Funnily enough, Github's syntax colorer has exactly the same issue: https://github.com/Microsoft/vscode/blob/419d5bbaedebef63cff9bc248f8407cda5d40562/src/vs/base/browser/ui/tree/asyncDataTree.ts#L535

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/698 to track this upstream
