### ISSUE TITLE
Make "show modified" option of the settings editor more prominent

### ISSUE THREAD

**Issue by MagnusOxlund** [Microsoft/vscode#65214]
With the new settings editor UI, the current way to filter the list of settings to only show previously modified settings is found in the ubiquitous ellipsis/more menu on the top right corner of the editor tab.

It wasn't obvious to me that the ellipsis menu options vary with each editor–usually it only contains the same three options–so it took me a moment to find the "show modified settings" option.

Although I understand the reasoning behind placing the option there, and I value a simple UI, I think the ellipsis menu can be overlooked when looking for an option specific to the settings search box, especially by users who are unaware that the option exists in the first place.

------------

Regular editor ellipsis menu:
![ellipsis 1](https://user-images.githubusercontent.com/10921083/50097616-9690fb80-021a-11e9-83af-ffcaef9a373d.png)

Settings editor ellipsis menu:
![ellipsis 3](https://user-images.githubusercontent.com/10921083/50097628-998bec00-021a-11e9-8011-9225492c45c6.png)

**Comment by MagnusOxlund** [comment]
An alternative would be create another category for modified settings on level with "Commonly Used": 

![possible solution 2](https://user-images.githubusercontent.com/10921083/50101315-bf1cf380-0222-11e9-8b0c-9960dde4eede.png)

**Comment by roblourens** [comment]
The ... button used to be in the editor, but we moved it up there to be consistent with other editors: https://github.com/Microsoft/vscode/issues/61590#issuecomment-432305306

**Comment by roblourens** [comment]
Yes, and it's something that I'm still paying attention to. But we decided

- Moving things always causes some small amount of pain but people will get used to it
- We documented it in the release notes for people who read those at least
- Many people didn't find it before either...

**Comment by MagnusOxlund** [comment]
I can't speak to the previous version of the GUI editor, but I'm sure users will adapt.

With the earlier JSON editor in mind, I think there's a case to be made for the sake of new users. With the editable column exclusively listing modified settings, you reaped the following advantages:
- Immediate access to frequently altered settings.
- Time saved not searching for forgotten or cryptic settings names.
- A fast way to rule out settings-related issues.
- A concise presentation of the way you use the editor.

Obviously the feature is still present, but I think the above when discovered early on is especially valuable to users who haven't yet familiarized themselves with the editor and the various settings that influence its behavior. To reap the benefits, there is now a discoverability challenge in requiring the user to explore and avoid making a wrong assumption about the ellipsis menu options.

On an unrelated note, there seems to be a discrepancy in the terms used between the two current UIs to describe modified and default settings.

I understand this isn’t a high priority and that it's a result of a compromise, so I appreciate that you're still paying attention to the development. I just want to make sure my concerns are represented in the feedback since I came too late for #50249.

**Comment by roblourens** [comment]
You're not wrong, but navigating the JSON still proved to be enough of a hurdle for many new users that we've found that the GUI is still a better default experience for new users.

> On an unrelated note, there seems to be a discrepancy in the terms used between the two current UIs to describe modified and default settings.

Not sure what you mean by that?

**Comment by MagnusOxlund** [comment]
I prefer the GUI too, I'm just concerned with the discoverability of the "modified settings" in its current location.

In 1.30.0 on the special JSON settings editor, "User Settings" is juxtaposed with "Default User Settings" whereas in the GUI, "User Settings" seems to include both modified and default values and appears instead in contrast to "Workplace Settings". 

I just discovered #62964 in Insiders, so I guess it's no longer relevant.
