### ISSUE TITLE
shortcut name: might goToDefinition be better than goToDeclaration?

### ISSUE THREAD

**Issue by legendtkl** [Microsoft/vscode#6521]
Hello, 

About the key shortcut
```son
{ "key": "f12",                   "command": "editor.action.goToDeclaration",
                                     "when": "editorTextFocus" },
```

 We know that `definition` and `declaratoin` are different in programming, and the actual action of f12 is going to definition, not declaration.

Maybe this is a subtle issue, but it will be good for a better vs code.

**Comment by alexandrudima** [comment]
fyi @jrieken we could introduce a new command `goToDefinition` and have `goToDeclaration` forward to it for compatibility reasons.

**Comment by jrieken** [comment]
I totally agree. Tho the problem is that changing the command id will break everyone that has a configuration referring to it. That's why I would leave it untouched and bite the bullet...

**Comment by legendtkl** [comment]
Thanks, I see.
