### ISSUE TITLE
task keybindings not working on mac OS Mojave

### ISSUE THREAD

**Issue by ctin** [Microsoft/vscode#65210]
- VSCode Version: 1.27.2 (1.27.2)
- OS Version: macOS Mojave 10.14.1

Steps to Reproduce:

1. create `tasks.json`:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run tests",
            "type": "shell",
            "command": "ls",
            "args":[
                "-al"
            ],
            "group": "test",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            }
        }
    ]
}
```
2. create `keybindings.json`:
```
[
{
    "key": "ctrl+k",
    "command": "workbench.action.tasks.runTask",
    "args": "Run tests"
}
]
```

Expecting result: by pressing "ctrl+k" task invokes;
Actual result: noting happening;

Does this issue occur when all extensions are disabled?: **Yes**/~~No~~

Notes: I tried different tasks and shortcuts, it did not help.

**Comment by alexr00** [comment]
Can you try this in version 1.30.*? I tried in 1.29, 1.30, and 1.31 (insiders) and I cannot reproduce.

**Comment by ctin** [comment]
just tried 1.30.0 and got same result.
please try my sample project:
[testProject.zip](https://github.com/Microsoft/vscode/files/2686740/testProject.zip)
Steps to reproduce:
* open main.c;
* click by mouse anywhere;
* press cmd+k;
Expected result: task starting;
Actual result: nothing happening;

**Comment by alexr00** [comment]
There were some problems with loading tasks earlier this week. I am wondering if maybe you were hitting that. Can you try again with the latest insiders?
