### ISSUE TITLE
Create setting to limit linting to current file/opened files or workspace dir (or terminal.integrated.cwd if set).

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#65223]
Create setting to limit linting to current file/opened files or workspace dir (or terminal.integrated.cwd if set).

Also, create a keyboard shortcut to lint the workspace dir (or terminal.integrated.cwd if set), no matter the setting above.

**Comment by sandy081** [comment]
This is up to extension to lint complete workspace or only opened files. 

If you want problems view to show problems of active editor only then this is already requested here https://github.com/Microsoft/vscode/issues/30038
