### ISSUE TITLE
Convert Indentation to Spaces

### ISSUE THREAD

**Issue by Subb98** [Microsoft/vscode#65220]
- VSCode Version: 1.30.0 Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
- OS Version: Linux Mint 19 tara x86_64 Linux 4.15.0-42-generic

Steps to Reproduce: just use 'Convert Indentation to Space' feature on file with indentations, like here:

![Convert Indentation to Space work](https://i.imgur.com/ngd1Alx.gif)

My user settings:

```
"workbench.startupEditor": "newUntitledFile",
"editor.renderWhitespace": "boundary",
"files.insertFinalNewline": true,
"files.trimTrailingWhitespace": true
```

**Comment by alexandrudima** [comment]
Indeed, the built-in convertor indeed only handles indentation (which is the whitespace before any non-whitespace character).
