### ISSUE TITLE
[Windows] [V-Sync] [Nvidia] Very bad flickering and spasms in fullscreen mode (Update to #64383)

### ISSUE THREAD

**Issue by Sgt-Nukem** [Microsoft/vscode#65227]
This is an UPDATE to issue #64383 as it has been auto-closed and I cannot re-open it anymore.

(I added the missing info.)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Sgt-Nukem** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Just downloaded https://aka.ms/win32-x64-user-insider
Not sure why I am now testing an even older Electron release than before, but I did, see: https://github.com/Microsoft/vscode/issues/64383#issuecomment-449020109

```
Please re-open the referenced #64383 again - as it contains far more valuable info.
This bounce here can be closed then.
```

Happy Holidays to the VS Code Team, too! 💃 

![image](https://user-images.githubusercontent.com/4144388/50291079-cb48c100-046d-11e9-9101-c26cc455d5a5.png)
