### ISSUE TITLE
npm packages do not refresh after 'npm install' or 'npm update' is ran on the folder

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Microsoft/vscode#6523]
- VSCode Version: Version 1.1.1 (1.1.1)
- OS Version: OS X El Capitan 10.11.4 (15E65)

Steps to Reproduce:

1. Instal an npm package for an older version of a the package
2. Try to update it via the `npm install` or `npm update` commands
3. The package is downloaded correctly but the contents of the 'node_modules' folder are not being refreshed and show the old content (which is no longer available)
4. Restarting VS Code fixes the issue and shows the new updated packages in the 'node_modules' folder

This started happening in the latest version from what I have observed.

**Comment by bpasero** [comment]
You would need to enable watching in the node_modules folder:

```
"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/node_modules/**": false
	}
```

We chose to exclude large folders from watching due to performance issues.

**Comment by VladimirAmiorkov** [comment]
Thank you for the update. 

Just a quick question, is this a new change as I can do not remember seeing this in older versions.

**Comment by bpasero** [comment]
Yeah, I think 1.0.

**Comment by jppellerin** [comment]
Is there a way, or should there be a way to reload without restarting VSCode?

Every time I update a node_module, I have to restart VSCode... sometimes this ends up happening too often.

**Comment by VladimirAmiorkov** [comment]
@jppellerin On PC you can do  Ctrl + Shift + P (mac: Cmd + Alt + P) then type "Reload Window"/"Reload TypeScript Project"/"Reload JavaScript Project" which will do those things without the need of manually close/reopen its kinda handy.
