### ISSUE TITLE
Smoketest: search tests are failing

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#65238]
All 4 search tests are timing out for me:

>Search
** Timeout!
Error: Element not found: div[id="workbench.view.search"].search-view .search-widget .search-container .monaco-inputbox input

Has this selector been updated?

**Comment by roblourens** [comment]
Are you sure you ran the tests from the latest `release/1.30` and built them? Should be fixed already: https://github.com/Microsoft/vscode/blob/release/1.30/test/smoke/src/areas/search/search.ts#L10
