### ISSUE TITLE
Can't resize or move window when running in SSH X11 forwarding to Windows client

### ISSUE THREAD

**Issue by byates** [Microsoft/vscode#65232]
- VSCode Version: 1.30, 1.31
- Install OS Version: Ubuntu 18.04
- Host OS Version: Windows 10

Problem:
Can't resize or move the application window when running SSH X11 forwarding to Windows client.  We run VSCode remotely from WIndows machines to Linux boxes. Normally we use MobaXterm or Bitvise with VcXsrv.  Prior to v1.30 this works very well. The upgrade to 1.30 broke something so that now we can't resize or move the VSCode application window.

Steps to Reproduce:

1. Install 1.30 or 1.31 on Ubuntu 18.04 host machine
2. Run MobaXterm or Bitvise (with VcXsrv X Server) on Windows 10 client machine
3. Remote log in to the host machine from Windows using MobaXterm or Bitvise (enable X11)
4. run vscode from the command line: `code`
5. All attempts to move or resize the window don't work

I have verified that resizing and moving of the application window works if the client machine is another Linux box so this seems to be something with the X11 servers running on windows and whatever changes where done from 1.29 to 1.30.  I have reverted to 1.29 and everything works again.

Does this issue occur when all extensions are disabled?: Yes

===============================================================
**NOTE:** There is a workaround for this issue. See the comments from kasru and tenortim  below:
https://github.com/Microsoft/vscode/issues/65232#issuecomment-460100799

**Comment by yanpads** [comment]
We have the same issue.

**Comment by brettbbonner** [comment]
Issue also occurs using Cygwin's X server on Windows and Ubuntu 16.04 as Linux host running VSCode (again with SSH X11 forwarding).  Also had to revert to 1.29.

**Comment by kasru** [comment]
I too can confirm this with running code v1.30.1 from Debian 9 using MobaXterm on Windows 10. Please fix it !

**Comment by kasru** [comment]
Guys, I found solution at  [Cannot maximize, minimize, or move the window when exported to remote X11 display ...](https://github.com/Microsoft/vscode/issues/65036)
how to fixed this problem
`"window.titleBarStyle": "native"`

**Comment by dlmacedo** [comment]
Where should I add "window.titleBarStyle": "native"?

**Comment by CreeperKong** [comment]
You need GTK+ library

**Comment by tenortim** [comment]
> Where should I add "window.titleBarStyle": "native"?

~/.config/Code/User/settings.json on the Linux box (or 'Code - Insiders' if you're running the insiders build. If the file doesn't exist, then create it with the following line:
`{ "window.titleBarStyle": "native" }
`

**Comment by sittingonthenet** [comment]
Thank you, it works perfectly.

**Comment by lcsondes** [comment]
Workaround confirmed working

**Comment by ThiagoRDO** [comment]
Oh my gosh I have been search for a solution for a week at least, then I found this tip. Thank you so much.
BTW, I'm running VSCode through WSL on W10 and the tip works perfectly.

**Comment by paroque28** [comment]
Workaround worked for me but... Is this going to be fixed?
https://github.com/Microsoft/vscode/issues/65036 has been closed
