### ISSUE TITLE
Keyboard shortcut sent twice

### ISSUE THREAD

**Issue by cipri-tom** [Microsoft/vscode#65235]
Issue Type: <b>Bug</b>

So, in my `keybindings.json` I have :

```json
    {
        "key": "alt+i",
        "command": "workbench.action.focusPreviousGroup"
    }
```
This works correctly, in all files.

Now, when I'm writing Markdown, I want to use some special characters, which on my keyboard are mapped to <kbd>Alt</kbd>+<kbd>i</kbd> (produces `î`, Romanian programmers layout).

So, I decide to add a `when` clause, to ignore the above shortcut when editing markdown, since it would only take me to the preview pane anyway.

```json
    {
        "key": "alt+i",
        "command": "workbench.action.focusPreviousGroup",
        "when": "editorLangId != 'markdown'"
    }
```

### Expected result
I can type `î` (<kbd>Alt</kbd>+<kbd>i</kbd>) in a markdown file

### Actual result
When I press <kbd>Alt</kbd>+<kbd>i</kbd> I get the `î` in the file, and then the focus switches to the previous group. So it is as if the command is parsed twice, once with the clause, once without.

Of course I have tried reloading the window and restarting VSCode, but to no avail. 

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-dash|dee|2.0.0
githistory|don|0.4.4
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
language-cython|guy|0.0.5
MagicPython|mag|1.1.0
code-beautifier|mic|2.1.0
python|ms-|2018.12.1
sublime-keybindings|ms-|4.0.0
autodocstring|njp|0.2.3
vscode-css-peek|pra|2.2.0
vscode-icons|rob|8.0.0
vscode-multiclip|sle|0.1.5
markdown-all-in-one|yzh|1.8.0
html-css-class-completion|Zig|1.17.1

(9 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
:+1: Let's track in #41024

This is a confirmed upstream bug - https://bugs.chromium.org/p/chromium/issues/detail?id=887519

**Comment by cipri-tom** [comment]
I'm sorry, I didn't thing to search specifically for that exact shortcut. Thanks for the reference!
