### ISSUE TITLE
Code won't open on OSX 10.14 machine.

### ISSUE THREAD

**Issue by LifeSizeDeity** [Microsoft/vscode#65231]
- VSCode Version: 1.30
- OS Version: 10.14.2

Steps to Reproduce:

1. Download VS code. 
2. Run VS code application
3. VS crashes immediately, won't open

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by opas2536** [comment]
Yes

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by LifeSizeDeity** [comment]
@bpasero Thanks for the response. I have been trying to get a crash report but I'm getting nothing. I also don't have an ~Application Support/Code path. I downloaded Atom and can't get it to open either, so I was thinking about doing a system restore. Let me know what you think. Thanks again.

**Comment by bpasero** [comment]
@LifeSizeDeity oh ok so maybe you see a different issue than from what I thought.

**Comment by LifeSizeDeity** [comment]
So I did a system restore and that worked. No telling what exactly what was wrong.
