### ISSUE TITLE
Doesn't Restart Kernel. Requires Shutdown and Restart of VS Code 

### ISSUE THREAD

**Issue by DecisionScients** [Microsoft/vscode#65239]
Issue Type: <b>Bug</b>

I'm reopening this issue, because a) the prior issue was closed, b) the issue persists, and c) the resolution given was not intelligible.

Requests to restart the kernel require a restart.  I've waited up to 15 minutes for a kernel restart before shutting down and restarting vs code.  If this is a problem with an extension, specific information would be appreciated.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (12 x 2660)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|128.00GB (118.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.4
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1

</details>

**Comment by alexandrudima** [comment]
@DecisionScients I think this might be a command contributed from the Python extension. Can you please open an issue against https://github.com/Microsoft/vscode-python .
