### ISSUE TITLE
When OutputEvent contains source, it will cause a new line.

### ISSUE THREAD

**Issue by actboy168** [microsoft/vscode#65245]
Issue Type: <b>Bug</b>

https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json#L289-L336

This is the effect of not containing source and containing source.

![1](https://user-images.githubusercontent.com/1836844/50128293-68113000-02af-11e9-9929-cc4f8eca8b89.PNG)
![2](https://user-images.githubusercontent.com/1836844/50128294-68a9c680-02af-11e9-9040-1b3b4074cce4.PNG)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:28:23.833Z)
OS version: Windows_NT ia32 10.0.17763

**Comment by isidorn** [comment]
Can you still reproduce this with latest vscode insiders?

**Comment by actboy168** [comment]
This bug has been fixed, thank you very much.
