### ISSUE TITLE
Automatically pull in references in like in Eclipse or Visual Studio

### ISSUE THREAD

**Issue by lfrodrigues** [Microsoft/vscode#6524]
Is there a way to configure Visual Studio Code so that the intellisence will automatically inset "using" statements (reference to class library) just like in Eclipse or Visual Studio does?

In Visual Studio we can use SHIFT + ALT + F10:

![image](https://cloud.githubusercontent.com/assets/301004/15389248/da270b7c-1dad-11e6-8d39-1a8bbd65cfd5.png)

**Comment by jrieken** [comment]
VS Code as the [apis](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3439) for this and now it's up to the extension to this. Moving this item to omnisharp-vscode.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#366

**Comment by lfrodrigues** [comment]
Do you have an example of any language extension with this feature implemented? 

I wanted to have it also in python and could have a go at implementing it if there a place where I can get working example.

**Comment by jrieken** [comment]
yeah, actually OmniSharp for VSCode does implement some code actions already. The implementation of that is here: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/codeActionProvider.ts

Generally, this is how it works
* from your extension [register commands](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2903) that implement a code actions, like add using statement
* also register a [code action provider](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3439) for the language(s) you target. It's role is to identify a set of commands (see above) for a given range in a document.

With that the editor will know do the following: 

* on an error/warning or when called explicitly it will check with all code action provider
* from their commands it will create context menu
* on selection it will invoke the corresponding command with the given arguments.

**Comment by lfrodrigues** [comment]
Thanks for extra info, do you know any extension that implements fully this feature?
