### ISSUE TITLE
Custom title bar uses Windows styling on Linux distributions

### ISSUE THREAD

**Issue by zachbr** [Microsoft/vscode#65241]
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux (various, see below)

Steps to Reproduce:

1. Install vscode 1.30.0 on any Linux distro and run it
2. Compare vscode's titlebar with native applications.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

While the new title bar is nice, enabling it by default on Linux and having it ignore the distribution and user's desktop themes makes vscode look very out of place. On some distributions it isn't too bad. However on others it can look quite out of place on the system. This is not all that different from a Windows application using a macOS style title bar, or vice-versa.

Ideally, vscode's custom title bar should make an attempt to respect the style set forth by the desktop environment. Failing that, perhaps it would be better to disable this feature by default in order to maintain cohesion with the desktop environment, allowing advanced users or those who don't care to enable it manually in settings.

### Ubuntu 18.10 (`Linux x64 4.18.0-10-generic`)
![screenshot from 2018-12-17 15-54-31](https://user-images.githubusercontent.com/1254957/50125176-b386f800-0235-11e9-80e9-b295e5e77dba.png)
![screenshot from 2018-12-17 16-00-40](https://user-images.githubusercontent.com/1254957/50125177-b386f800-0235-11e9-93d6-7add7e9f9696.png)

### Fedora 29 (`Linux x64 4.18.16-300.fc29.x86_64`)
![screenshot from 2018-12-17 19-14-35](https://user-images.githubusercontent.com/1254957/50125209-cac5e580-0235-11e9-87d1-cbd3ed8da554.png)
![screenshot from 2018-12-17 19-14-55](https://user-images.githubusercontent.com/1254957/50125210-cac5e580-0235-11e9-9ad0-91b56f1edc7c.png)

### KDE Neon (`Linux x64 4.15.0-39-generic`)
![screenshot_20181217_193503](https://user-images.githubusercontent.com/1254957/50125221-d5807a80-0235-11e9-84a4-2946c6be7f5f.png)
![screenshot_20181217_193518](https://user-images.githubusercontent.com/1254957/50125222-d6191100-0235-11e9-96e7-6ecb7475f8dd.png)

### elementaryOS (`Linux x64 4.15.0-42-generic`)
![screenshot from 2018-12-17 20 07 46](https://user-images.githubusercontent.com/1254957/50125678-e6ca8680-0237-11e9-9605-06764275c95b.png)
![screenshot from 2018-12-17 20 08 01](https://user-images.githubusercontent.com/1254957/50125679-e6ca8680-0237-11e9-9de4-30939dc7b4a9.png)

Decided to test vscode insider for this last one.
```
Version: 1.31.0-insider
Commit: edf1090b8546ad0d17f30bf6f8075613e37e1b37
Date: 2018-12-17T10:01:26.915Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-42-generic
```

**Comment by j-james** [comment]
+ 1

Adding onto this, only the [X] does anything on my setup. And as far as I know, there is no option in the "view" menu to hide it like the menu bar.

**Comment by clee** [comment]
I'd like to point out that in addition to `custom` titlebars not matching the window manager's styling on Linux, VSCode *also* doesn't match the button order, which is much more important to me personally. I've attached a screenshot showing a variety of apps showing how they support proper custom button order support here.

- gnome-terminal just uses the standard WM decorations, and gets the proper button order
- nautilus has a funky custom HeaderBar widget, but also gets the proper button order
- chrome, which is only barely more native than vscode, gets the proper button order (and icons!)
- vscode is the odd GUI out, getting the button order and icons wrong

![image](https://user-images.githubusercontent.com/2089/50206952-50c35880-032a-11e9-89e6-a7012d3f5b32.png)

**Comment by kienner-philippe** [comment]
To me the most important thing is that with this custom title bar (or no more title bar?), **the right-click menu** allowing me to move the window to another X11 workspace (virtual display) **disappeared.**
I find this really annoying. The VS Code window has to stick into the workspace it has been started.
Thanks for giving back this (stolen ;-) functionality.

Thanks also for the good job,
I love VS Code.
Philippe

**Comment by kienner-philippe** [comment]
![image](https://user-images.githubusercontent.com/5954439/50355603-8c8b3780-054f-11e9-9221-5d838a0e61e9.png)
This menu is not availble anymore.

**Comment by sbatten** [comment]
/duplicate 
https://github.com/Microsoft/vscode/issues/65241
