### ISSUE TITLE
breadcrumbs not working in vue file

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#65248]
Issue Type: <b>Bug</b>

![](https://upload-images.jianshu.io/upload_images/252050-0775158047ffba49.gif?imageMogr2/auto-orient/strip)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.93GB (0.72GB free)|
|Process Argv|D:\DEV\Github\work\feng-bbs-mobile|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.0.0
turbo-console-log|Cha|1.2.11
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
vue-peek|dar|1.0.2
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
gitlens|eam|9.2.1
tslint|eg2|1.0.41
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
webpack-4-snippets|fwg|0.0.3
npm-dependency-links|her|1.0.0
vue-snippets|hol|0.1.9
path-autocomplete|ion|1.13.1
vscode-postfix-ts|ipa|1.8.1
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|0.0.25
expand-region|let|0.1.2
json-to-ts|Mar|1.5.5
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.0
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
material-icon-theme|PKi|3.6.1
code-settings-sync|Sha|3.2.4
code-spell-checker|str|1.6.10
codelf|unb|10.9.0
vscode-svg-previewer|vit|0.3.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by deepkolos** [comment]
today's update 1.30.1 seems working for me
