### ISSUE TITLE
Solution explorer

### ISSUE THREAD

**Issue by oross** [Microsoft/vscode#65246]
Issue Type: <b>Bug</b>

The .sln files did not work in Ubuntu

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2122)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|15.60GB (7.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-solution-explorer|fer|0.3.0
dotnet-test-explorer|for|0.6.0
vscode-cudacpp|kri|0.1.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
csharp|ms-|1.17.1
material-icon-theme|PKi|3.6.1
vscode-yaml|red|0.1.0

</details>

**Comment by alexandrudima** [comment]
@oross Can you please create an issue directly against the extension at https://github.com/OmniSharp/omnisharp-vscode
