### ISSUE TITLE
New trees don't respect workbench.list.openMode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65252]
This setting controls whether items should open/expand with a single click or double click. The old trees check this via the WorkbenchTreeController/DefaultController. How should we handle it for the new tree?

**Comment by Tyriar** [comment]
Didn't seem to fix it in this build:

7f136b44cff0cd3486ac88b43598b8c72b025d16
2019-01-31T06:07:23.930Z

Can repro in explorer.

**Comment by joaomoreno** [comment]
@Tyriar Which platform?

**Comment by joaomoreno** [comment]
Can't repro on Linux or macOS.

**Comment by joaomoreno** [comment]
Also can't repro on Windows.

**Comment by joaomoreno** [comment]
Oh I see what you mean, this is about folder expansion.
