### ISSUE TITLE
a package notice err

### ISSUE THREAD

**Issue by hjb912** [Microsoft/vscode#65250]
Issue Type: <b>Bug</b>

a.java empty file in package A, i write "package A", then notice me "The declared package "A" does not match the expected package ""Java(536871240)", however, i move this a.java to B directory, then move back to A directory, this notice disappear! why is it..

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_4199425|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.22.0
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
Go|ms-|0.8.0
sublime-keybindings|ms-|4.0.0
java|red|0.35.0
vscode-fileutils|sle|2.13.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1

</details>

**Comment by alexandrudima** [comment]
@hjb912 Can you please create an issue directly against the Java extension at https://github.com/redhat-developer/vscode-java
