### ISSUE TITLE
UPDATE - Context - descriptions not written in clear language (Usability) #64656 

### ISSUE THREAD

**Issue by VErwin** [Microsoft/vscode#65256]
- VSCode Version:  1.30.0
- OS Version: Windows_NT ia32 10.0.17134

Steps to Reproduce:

** NOTE - if you can't fix this for this release - assign to UX.  They can put it into the backlog for a UX Writer to fix this. THIS IS A UX ISSUE!!  Don't just ignore it!  Maybe assign to DavidCul or DonnaWa as they are knowledgeable  in this area.
1.  Following up on bug #64656, I installed the W3C Validation 2.3.0 and CSS Tree validator 0.7.0 from the Extensions Marketplace.
2.  Not only did it NOT FIX the issue; it made it worse!  

Verbatim copy is now:  

> "function addEventListener<"load">(type: "load", listener: (this: Window, ev: Event) => any, options?: Boolean | AddEventListenerOptions): void (+1 overload)

3.  This is a TERRIBLE user experience.  Please get a UX writer to look at this and improve it.  The experience should be tiered on install.  Expert/ Learner with content menus tailored per user-type.  Learners should have  more didactic verbiage.

Does  @this issue occur when all extensions are disabled?: Yes/No
#  Yes and No.  This is UX.  Assign to backlog.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/29083 to track this on the TypeScript side
