### ISSUE TITLE
Markdown Preview incorrectly displays "js-with-links-with-details"

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#65251]
Issue Type: <b>Bug</b>

On GitHub, WebPack uses the MarkDown code tag [`js-with-links-with-details`](https://raw.githubusercontent.com/webpack/webpack.js.org/master/src/content/configuration/index.md).

This style is not displayed correctly in MarkDown preview in Visual Studio Code:

![index](https://user-images.githubusercontent.com/9283914/50132357-063cd000-0287-11e9-9174-3a71da8a5724.png)

The `<details>` tag and hyperlinks are not correctly parsed.

<hr/>

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-twig-pack|baj|1.0.0
gitlab-workflow|fat|1.5.1
vscode-firefox-debug|hbe|1.6.0
vscode-language-pack-de|MS-|1.27.2
Go|ms-|0.7.0
PowerShell|ms-|1.10.1
debugger-for-chrome|msj|4.11.1
markdown-all-in-one|yzh|1.8.0

</details>

**Comment by mjbvz** [comment]
I don't know what WebPack is doing in their docs but that is not standard. An extension could add support for this but it's out of scope of the built-in markdown extension
