### ISSUE TITLE
"ctrl + p" Error finding a file

### ISSUE THREAD

**Issue by Austzhu** [Microsoft/vscode#65259]
Issue Type: <b>Bug</b>

command failed with error code 2: error parsing glob '!\*\*.tags\*': invalid use of \*\*; must be one path component

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:28:23.833Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz (2 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.00GB (1.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
fileheader-plus|che|0.0.2
githistory|don|0.4.4
gitlens|eam|9.2.1
eppz-code|epp|1.2.41
beautify|Hoo|1.4.7
ctags-support|jay|1.0.19
sftp|lix|1.8.4
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
markdown-preview-enhanced|shd|0.3.11
vim|vsc|0.17.0
codescope|xul|0.0.10
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.8.0

(4 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
You are using that glob in your 'files to exclude' search field or one of the `files.exclude` or `search.exclude` settings. Which files do you want to exclude with this?

**Comment by Austzhu** [comment]
> You are using that glob in your 'files to exclude' search field or one of the `files.exclude` or `search.exclude` settings. Which files do you want to exclude with this?
