### ISSUE TITLE
Goto symbol: highlight symbol at current cursor location when opening

### ISSUE THREAD

**Issue by eypsum** [microsoft/vscode#65254]
I posted earlier at https://github.com/Microsoft/vscode/issues/63306
I didn't update due to busy for a while, so the issue got closed by the bot.
When Quick Open is invoked first time for searching a symbol in active editor ( in my case, c/c++ editor),
Mostly tt seems better focus on the symbol where cursor is.

![quicksymbol_need_hilight_current_symbol_on_editor_2](https://user-images.githubusercontent.com/20113770/50134197-41182580-02d2-11e9-9f73-37c667fea78d.png)

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/22689
