### ISSUE TITLE
php syntax highlight is broken after update v1.30.0

### ISSUE THREAD

**Issue by cubictek** [Microsoft/vscode#65255]
- VSCode Version: v1.30.0
- OS Version: Windows 10

Steps to Reproduce:

1. php syntax highlight is broken after update v1.30.0
2. '.php' file has html codes that contain php codes.
![image](https://user-images.githubusercontent.com/19640163/50136022-b2a7a200-02d9-11e9-9f26-01f7a9e2600c.png)

![image](https://user-images.githubusercontent.com/19640163/50135954-75dbab00-02d9-11e9-95d9-78f2ece82107.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you share the broken snippet as text?

**Comment by BrianBakkala** [comment]
Here's an example that you can reproduce


`
<?php echo "hi";?>

<script>
function Jello()
{
	array = [<?php echo "1";?>]
}

</script>

<?php echo "hi"; ?>
 
`



![](https://i.gyazo.com/435d0aab8b96cc1fa8742394342805d6.png)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/65028
