### ISSUE TITLE
visual code fails to open files w/ spaces in filename

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#6525]
- VSCode Version:
_Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:38:00.094Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0_

- OS Version:
_ubuntu 14.04_

Steps to Reproduce:

1. create a file w/ spaces in its filename
2. try to open it via terminal, e.g:
```bash
code "file with spaces.js"
code "file\ with\ spaces.js"
code file\ with\ spaces.js
```
are all dealt as
```bash
code file with spaces.js
```

visual studio code fails to manage argv array and to open the file, instead it opens three different files, like "file with spaces.js".split(' ')

ps: nice editor btw ;)

**Comment by weinand** [comment]
I could verify this issue on linux.

**Comment by Tyriar** [comment]
Seems to be a problem with the bin command, `code-alpha a\ b\ c` doesn't work but `/usr/share/code-alpha/code-alpha a\ b\ c` does.

**Comment by Tyriar** [comment]
Tested using:

```
./bin/code-oss "a b c"
./bin/code-oss a\ b\ c
./bin/code-oss --locale=ja-JP "a b c"
./bin/code-oss --locale=ja-JP a\ b\ c
./bin/code-oss --help a\ b\ c #opens help
./scripts/code-cli.sh a\ b\ c
./scripts/code-cli.sh --wait a\ b\ c # --locale doesn't seem to work on code-cli.sh
```

@weinand please verify when you get a chance

**Comment by zeeshanrealist** [comment]
doesn't work I don't even get the option of visual studio code when I right-click a file and click open with
