### ISSUE TITLE
Menu mnemonics not underlined

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vscode#65267]
Issue Type: <b>Bug</b>

When I click on Help (for example), no mnemonics are shown.
Same for the main menu bar, until i press Alt.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by sbatten** [comment]
@OlafvdSpek this is the intended behavior. Use Alt+Mnemonic to open the menus and see the mnemonics. This is consistent with other windows app menu bars.

**Comment by OlafvdSpek** [comment]
It's not, other apps respect `Underline keyboard shortcuts and access keys`.

https://www.groovypost.com/howto/make-windows-underline-menu-shortcut-keys/

**Comment by OlafvdSpek** [comment]
I really thought the underlines would always be there in sub menus but I was wrong.
