### ISSUE TITLE
Wrong Update Version

### ISSUE THREAD

**Issue by MetallicPickaxe** [Microsoft/vscode#65261]
Issue Type: <b>Bug</b>

The insider version is 1.31 now, when I check update it tell me a new version available, but when I got the NEW version, it is still the 1.31

VS Code version: Code - Insiders 1.31.0-insider (edf1090b8546ad0d17f30bf6f8075613e37e1b37, 2018-12-17T10:06:30.031Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet|for|0.0.4
latex-workshop|Jam|5.18.0
csharpextensions|jch|1.3.0
vscode-language-pack-zh-hans|MS-|1.30.2
extension-manifest-editor|ms-|0.1.5
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
PowerShell|ms-|1.10.1
typescript-javascript-grammar|ms-|0.0.47
vs-keybindings|ms-|0.2.0
wordcount|ms-|0.1.0
vscodeintellicode|Vis|1.1.2

</details>

**Comment by alexandrudima** [comment]
@MetallicPickaxe That is what we do for the insiders version. We keep it at the same version number throughout the month. When we have finished stabilizing and we release stable, the stable always has correct, increasing version numbers.

**Comment by MetallicPickaxe** [comment]
But I have updated it again and over again, the NEW VERION is still that version, including the any other information. Is that right?

**Comment by alexandrudima** [comment]
Until the next stable release, the insiders version will be "1.31.0-insider" and the commit version will always change. The commit version is the string that uniquely identifies a release.
