### ISSUE TITLE
The search on the left, the MAC Pro search and then the computer crashes, there's an infinite loop

### ISSUE THREAD

**Issue by memory-chen** [Microsoft/vscode#65268]
Issue Type: <b>Bug</b>

The search on the left, the MAC Pro search and then the computer crashes, there's an infinite loop
![image](https://user-images.githubusercontent.com/17876025/50141896-a3c5ed00-02e3-11e9-8721-2fad811b871e.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|16.00GB (8.90GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
es7-react-js-snippets|dsz|1.9.2
gitlens|eam|9.2.1
vue-snippets|hol|0.1.9
vscode-titlebar-less-macos|leh|1.7.1
code-beautifier|mic|2.1.0
vs-code-quick-require|mil|0.2.4
vscode-language-pack-zh-hans|MS-|1.30.2
vetur|oct|0.14.3
LiveServer|rit|5.3.1
px-to-rem|sai|1.2.7

</details>

**Comment by roblourens** [comment]
@memory-chen you already filed https://github.com/Microsoft/vscode/issues/64939, I already told you I need more details
