### ISSUE TITLE
suggestion system

### ISSUE THREAD

**Issue by amirhosein5858** [Microsoft/vscode#65266]
Issue Type: <b>Feature Request</b>

in previous version VScode suggest me child of an object in JS,but now it's not and make development harder than past...!

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Please provide a code example that shows what does not work
