### ISSUE TITLE
Tasks discovery not working properly

### ISSUE THREAD

**Issue by zplan** [Microsoft/vscode#65263]
- VSCode Version: 1.31.0-insider
- OS Version:Win10 x64

Steps to Reproduce:

1.Having a tasks.json file with multiple tasks defined in a .vscode folder
2.Press ctrl + shift + b
3. Only the last task is displayed to select
4. Going in the menu to Terminal - Configure Tasks... --> All Tasks are shown

Does this issue occur when all extensions are disabled?:  Yes

**Comment by zplan** [comment]
No, it is not covered by an existing issue.
It also was working until the last insider build.

**Comment by alexr00** [comment]
ctrl + shift + b will only show build tasks (`"group": "build"`). I've tried with a `tasks.json` that contains several build tasks, but they all show up just fine. What does your `tasks.json` look like?

**Comment by zplan** [comment]
This is my tasks.json where I can only see the "Build App3" since the last update of VSCode:

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",

    "type": "shell",
    "presentation": {
        "reveal": "always",
        "panel": "new"
    }, 
    "problemMatcher": [],
       
    "tasks": [
        {
            "label": "Build All Apps",
            "dependsOn": [
                "Build App1",
                "Build App2",
                "Build App3"            ],
            "group": "build"
        },
        {
            "label": "Build App1",
            "command": "${workspaceFolder}\\App1\\Build\\build.ps1",
            "options": {
                "cwd": "App1\\Build"
            },
            "group": "build"
        },
        {
            "label": "Build App2",
            "command": "${workspaceFolder}\\App2\\Build\\build.ps1",
            "options": {
                "cwd": "App2\\Build"
            },
            "group": "build"
        },
        {
            "label": "Build App3",
            "command": "${workspaceFolder}\\App3\\Build\\build.ps1",
            "options": {
                "cwd": "App3\\Build"
            },
            "group": "build",
        }
    ]
}

**Comment by alexr00** [comment]
I can repro. Thank you for the good example.
