### ISSUE TITLE
Some button can not be executed by touching

### ISSUE THREAD

**Issue by MetallicPickaxe** [microsoft/vscode#65262]
Issue Type: <b>Bug</b>

I use VS Code on Surface and some buttons are not work corrwctly always while I am using a Pen or touching operation, whether or not the Cover or other Mice or Keyboards are linking.
Such like the button that I am going to click below the edit area: "Preview in the GitHub", I have to connect a mouse to go next step to feedback my problem, so ironnical.

VS Code version: Code - Insiders 1.31.0-insider (edf1090b8546ad0d17f30bf6f8075613e37e1b37, 2018-12-17T10:06:30.031Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet|for|0.0.4
latex-workshop|Jam|5.18.0
csharpextensions|jch|1.3.0
vscode-language-pack-zh-hans|MS-|1.30.2
extension-manifest-editor|ms-|0.1.5
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
PowerShell|ms-|1.10.1
typescript-javascript-grammar|ms-|0.0.47
vs-keybindings|ms-|0.2.0
wordcount|ms-|0.1.0
vscodeintellicode|Vis|1.1.2

</details>

**Comment by arjunkgit** [comment]
Could you share any screenshot ?

**Comment by MetallicPickaxe** [comment]
![2018-12-18 183135](https://user-images.githubusercontent.com/9762353/50148401-60737a80-02f3-11e9-94ee-d8104ba1686f.jpg)

**Comment by MetallicPickaxe** [comment]
I am not very clear how the shot showed a action well, other than a video

**Comment by TylerLeonhardt** [comment]
Created this issue by using touch (except for typing in title/body): https://github.com/microsoft/vscode/issues/123908

Closing this as fixed. Let us know if you still have trouble!

**Comment by TylerLeonhardt** [comment]
verification steps: using a touch device (like a surface) open the issue reporter and try to create an issue. It should work fine.
