### ISSUE TITLE
empty string should be a valid value for a virtual document

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6526]
* have a document provider that return `""`
* 💥 an error happens, the empty string should be a valid result

**Comment by isidorn** [comment]
The registerTextDocumentContentProvider API is new in the may release of vscode, right?
So my generated extension can not yet use this API until we release our may version?

Is there some other way to verify this - except writing unit tests which I see you already did?

**Comment by jrieken** [comment]
> The registerTextDocumentContentProvider API is new in the may release of vscode, right?

No, we have that since January.
