### ISSUE TITLE
vscode://ext.id/blah links fail with error from within hover docs

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#65269]
I registered a URI handler like this:

```ts
context.subscriptions.push(vs.window.registerUriHandler({
	handleUri(uri: vs.Uri) {
		console.log("test");
	},
}));
```

If I put `vscode://Dart-Code.dart-code/test` into my browser, everything works correctly (I see the log). However, if I add the link inside a Hover comment, like this:

```markdown
[test link](vscode://Dart-Code.dart-code/danny_test)
```

Then when I click the link, I get this error:

![screen shot 2018-12-18 at 8 40 40 am](https://user-images.githubusercontent.com/1078012/50141924-a5ba8c80-02a0-11e9-8730-7bb0307b3892.png)
![screen shot 2018-12-18 at 8 40 50 am](https://user-images.githubusercontent.com/1078012/50141926-a5ba8c80-02a0-11e9-8c27-5ddca92bb2af.png)

**Comment by joaomoreno** [comment]
What version of Code?

**Comment by DanTup** [comment]
@joaomoreno It was using stable 1.30.0.

**Comment by DanTup** [comment]
Just tested in v1.30.1 and it's the same. I thought it might be specific to the dev extension host, but I just installed it as a vsix and it's the same.

**Comment by joaomoreno** [comment]
@DanTup Can you give Insiders a try?

**Comment by DanTup** [comment]
@joaomoreno Same behaviour in the new Insiders build. I tried both using `vscode://` and `vscode-insiders://` since I wasn't sure which Insiders would expect to use, but both did the same.

Putting vscode-insiders://blah into my browser still works fine and opens VS Code and passes the request to my handler.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/2ab6546e02aecb85fd6ddf333081bdbdd19c8852

This should be good already in Insiders, @DanTup can you check?

**Comment by DanTup** [comment]
Yep, this works in Insiders - though VS Code does show the prompt (I suspect this is expected):

![Screenshot 2019-03-25 at 2 39 01 pm](https://user-images.githubusercontent.com/1078012/54928462-d3e8e180-4f0b-11e9-8a6d-53ae6388c479.png)

That said, I think https://github.com/Microsoft/vscode/issues/29076 may be a better way to do what I wanted here now :-)
