### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#65273]
Issue Id: <b>a65f78d7-f1fc-ca30-c896-d230bcc5a65c</b><br /><br />*Versions* <br />- 241923763dbeaf3b64443187e935d55b29f6125d<br />-  c6e592b2b5770e40a98cb9c2715a8ef89aec3d74<br />-  bc24f98b5f70467bc689abf41cc5550ca637088e<br />-  a152a5c7818a13666a5879b4450eb26a4d45fbde<br />*Stack* <br />TypeError: Cannot read property 'appendChild' of undefined<br />    at out/vs/workbench/workbench.main.js:241:10<br />    at Array.forEach (<anonymous>)<br />    at Object.t.append (out/vs/workbench/workbench.main.js:240:1002)<br />    at t.createSubmenu (out/vs/workbench/workbench.main.js:989:25)<br />    at e.runner (out/vs/workbench/workbench.main.js:986:855)<br />    at e.doRun (out/vs/workbench/workbench.main.js:226:447)<br />    at e.onTimeout (out/vs/workbench/workbench.main.js:226:391)<br />

**Comment by alexandrudima** [comment]
Deminified using https://github.com/alexandrudima/vscode-stack-beautifier

TypeError:&nbsp;Cannot&nbsp;read&nbsp;property&nbsp;'appendChild'&nbsp;of&nbsp;undefined<br/>&nbsp;&nbsp;at&nbsp;`appendChild`&nbsp;([./browser/dom.ts:986:34](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./browser/dom.ts#L986))<br/>&nbsp;&nbsp;at&nbsp;`forEach`&nbsp;([./browser/dom.ts:986:10](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./browser/dom.ts#L986))<br/>&nbsp;&nbsp;at&nbsp;`append`&nbsp;([./browser/ui/menu/menu.ts:611:27](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./browser/ui/menu/menu.ts#L611))<br/>&nbsp;&nbsp;at&nbsp;`createSubmenu`&nbsp;([./browser/ui/menu/menu.ts:523:9](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./browser/ui/menu/menu.ts#L523))<br/>&nbsp;&nbsp;at&nbsp;`runner`&nbsp;([./common/async.ts:646:8](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./common/async.ts#L646))<br/>&nbsp;&nbsp;at&nbsp;`doRun`&nbsp;([./common/async.ts:640:8](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./common/async.ts#L640))<br/>

**Comment by joaomoreno** [comment]
@alexandrudima I think you meant @sbatten ?
