### ISSUE TITLE
[loc][Query][DevDiv] Please clarify placeholder 

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6527]
Hi, we have a query from our translator and I was hoping you could help. Thanks!

source:
Cannot launch debug target in terminal ({0}).

File Name:
out\node\nodeDebug.nls.resx

Resource ID:
".resx", 0; "VSND2011"

query:
What are the possible contents of {0}? Does it refer to the terminal or must the position be at the end of the sentence?	DE_Translator2	5/10/2016 9:58:04 PM

**Comment by weinand** [comment]
@mkyjakova '{0}' is a placeholder for an error message from the operating system (which is probably not  translated).

**Comment by mkyjakova** [comment]
Thanks :)
