### ISSUE TITLE
Search variable usage 

### ISSUE THREAD

**Issue by skprabhanjan** [Microsoft/vscode#65277]
@roblourens , Here is something that I would like to suggest as a feature request ( Also, Please Clarify if we cannot do this currently).

The current search uses **string matching and searches all matched strings**.
I would like to suggest a feature (Maybe a setting ? ) to search for a variable only. ( A simple approach is string matching for the complete string and not in the middle of a string )
As per the below screenshot  ( Search just for usage of variable `code` only)

<img width="1440" alt="screen shot 2018-12-18 at 3 21 17 pm" src="https://user-images.githubusercontent.com/17094832/50145902-95260880-02d8-11e9-83c0-c6776cf14b69.png">

**Comment by smbkr** [comment]
You can right click and select 'Find all references' or press opt+shift+F12 to do the same.

**Comment by skprabhanjan** [comment]
@smbkr , I have used find all references but Change all references does not work the same way.
Anyways that is a different part, I will close this.
