### ISSUE TITLE
Configured tasks missing

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#65276]
Issue Type: <b>Bug</b>

It seems that in the current Version the resolution of tasks seems to be faulty. I have 12 Tasks in my tasks.json but only the last one is showing up when I try to run a task.

VS Code version: Code - Insiders 1.31.0-insider (d85a16f2e4354f2850b4171f84fe0c94b0cea338, 2018-12-18T06:13:24.919Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv|-psn_0_4715647|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
pm2-explorer|ale|0.0.6
vscode-intelephense-client|bme|0.8.8
better-phpunit|cal|1.2.2
twigcs|cer|0.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.2
gitlens|eam|9.2.1
toggle-excluded-files|eam|1.6.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
jira-plugin|gio|0.11.0
vscode-pull-request-github|Git|0.3.2
sass-lint|gle|1.0.4
beautify|Hoo|1.4.7
rest-client|hum|0.20.4
phpcs|ika|1.0.5
smarty|imp|0.3.0
jenkinsfile-support|ivo|0.4.1
jenkins-pipeline-linter-connector|jan|1.1.5
docthis|joe|0.7.1
puppet-vscode|jpo|0.14.0
php-cs-fixer|jun|0.1.89
vscode-gutter-preview|kis|0.16.4
vscode-commitizen|Kni|0.8.1
php-symbols|lin|2.1.0
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
references-view|ms-|0.0.19
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
vscode-tap|num|1.0.2
vetur|oct|0.14.3
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.4.0
vscode-versionlens|pfl|0.22.0
errorlens|Phi|1.0.0
material-icon-theme|PKi|3.6.1
ruby|reb|0.21.0
vscode-yaml|red|0.1.0
code-settings-sync|Sha|3.2.4
stylelint|shi|0.47.0
autoimport|ste|1.5.3
easy-snippet-maker|tar|0.0.6
vscodeintellicode|Vis|1.1.2
Snippet|vsc|0.4.3
vim|vsc|0.17.0
quokka-vscode|Wal|1.0.174
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
sort-js-object-keys|zen|1.0.6

(1 theme extensions excluded)

</details>

**Comment by bm-stschneider** [comment]
1. ⌘+⇧+p
2. Tasks: Run Tasks
3. 1 Task shows up instead of 12, the self detected grunt taskes show up as well.

**Comment by bm-stschneider** [comment]
most tasks look like this
```
{
      "label": "Vagrant Grunt",
      "type": "shell",
      "command": "vagrant",
      "args": [
        "ssh",
        "-c",
        "cd /var/www;grunt"
      ],
      "problemMatcher": []
    }
```

**Comment by zplan** [comment]
It looks like this issue is the same as I have seen in #65263

**Comment by alexr00** [comment]
Yes this is likely the same as #65263. Thanks for reporting!

**Comment by bm-stschneider** [comment]
thanks for the quick fix :)
