### ISSUE TITLE
 Cannot read property 'onFocusChangeEventEmitter' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#65274]
Issue Id: <b>6ed8157b-7c09-9cdb-399b-856700aef03d</b><br /><br />*Versions* <br />- 1.30.0<br />-  241923763dbeaf3b64443187e935d55b29f6125d<br />*Stack* <br />TypeError: Cannot read property 'onFocusChangeEventEmitter' of undefined<br />    at out/vs/workbench/workbench.main.js:5807:659<br />    at Array.forEach (<anonymous>)<br />    at t.onFocusChange (out/vs/workbench/workbench.main.js:5807:630)<br />    at t.<anonymous> (out/vs/workbench/workbench.main.js:5806:154)<br />    at out/vs/workbench/workbench.main.js:186:722<br />    at out/vs/workbench/workbench.main.js:186:722<br />    at out/vs/workbench/workbench.main.js:192:796<br />    at e.fire (out/vs/workbench/workbench.main.js:189:512)<br />    at t.e.set (out/vs/workbench/workbench.main.js:860:810)<br />    at e.setFocus (out/vs/workbench/workbench.main.js:880:555)<br />    at e.focusNext (out/vs/workbench/workbench.main.js:880:710)<br />    at i.e.focusNext (out/vs/workbench/workbench.main.js:888:628)<br />    at e (out/vs/workbench/workbench.main.js:3715:730)<br />    at handler (out/vs/workbench/workbench.main.js:3718:197)<br />    at t.e.invokeFunction (out/vs/workbench/workbench.main.js:1480:492)<br />    at t._tryExecuteCommand (out/vs/workbench/workbench.main.js:3134:793)<br />    <br />

**Comment by alexandrudima** [comment]
Deminified using https://github.com/alexandrudima/vscode-stack-beautifier

/Applications/Visual&nbsp;Studio&nbsp;Code&nbsp;-&nbsp;Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185<br/>
&nbsp;&nbsp;at&nbsp;onDidChangeConfiguration&nbsp;([./editor/contrib/codelens/codelensWidget.ts:87:38](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensWidget.ts#L87))
&nbsp;&nbsp;at&nbsp;[./editor/contrib/codelens/codelensWidget.ts:247:24](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensWidget.ts#L247)
&nbsp;&nbsp;at&nbsp;[./editor/contrib/codelens/codelensController.ts:253:23](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L253)
&nbsp;&nbsp;at&nbsp;func&nbsp;([./editor/browser/view/viewImpl.ts:589:9](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L589))
&nbsp;&nbsp;at&nbsp;callback&nbsp;([./editor/browser/view/viewImpl.ts:498:18](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L498))
&nbsp;&nbsp;at&nbsp;func&nbsp;([./editor/browser/view/viewImpl.ts:581:9](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L581))
&nbsp;&nbsp;at&nbsp;safeInvokeNoArg&nbsp;([./editor/browser/view/viewImpl.ts:359:10](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L359))
&nbsp;&nbsp;at&nbsp;_renderOnce&nbsp;([./editor/browser/view/viewImpl.ts:478:7](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L478))
&nbsp;&nbsp;at&nbsp;change&nbsp;([./editor/browser/widget/codeEditorWidget.ts:1247:40](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1247))
&nbsp;&nbsp;at&nbsp;changeViewZones&nbsp;([./editor/contrib/codelens/codelensController.ts:222:16](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L222))
&nbsp;&nbsp;at&nbsp;callback&nbsp;([./editor/common/model/textModel.ts:1502:12](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/common/model/textModel.ts#L1502))
&nbsp;&nbsp;at&nbsp;_changeDecorations&nbsp;([./editor/common/model/textModel.ts:1467:15](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/common/model/textModel.ts#L1467))
&nbsp;&nbsp;at&nbsp;changeDecorations&nbsp;([./editor/browser/widget/codeEditorWidget.ts:1019:31](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1019))
&nbsp;&nbsp;at&nbsp;changeDecorations&nbsp;([./editor/contrib/codelens/codelensController.ts:221:15](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L221))
&nbsp;&nbsp;at&nbsp;_renderCodeLensSymbols&nbsp;([./editor/contrib/codelens/codelensController.ts:121:10](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L121))
&nbsp;&nbsp;at&nbsp;hasListeners&nbsp;([./base/common/event.ts:302:11](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/common/event.ts#L302))

**Comment by alexandrudima** [comment]
Deminified using https://github.com/alexandrudima/vscode-stack-beautifier

TypeError:&nbsp;Cannot&nbsp;read&nbsp;property&nbsp;'onFocusChangeEventEmitter'&nbsp;of&nbsp;undefined<br/>&nbsp;&nbsp;at&nbsp;`onFocusChangeEventEmitter`&nbsp;([./workbench/parts/extensions/electron-browser/extensionsViews.ts:161:50](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./workbench/parts/extensions/electron-browser/extensionsViews.ts#L161))<br/>&nbsp;&nbsp;at&nbsp;`forEach`&nbsp;([./workbench/parts/extensions/electron-browser/extensionsViews.ts:161:29](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./workbench/parts/extensions/electron-browser/extensionsViews.ts#L161))<br/>&nbsp;&nbsp;at&nbsp;`onFocusChange`&nbsp;([./workbench/parts/extensions/electron-browser/extensionsViews.ts:97:36](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./workbench/parts/extensions/electron-browser/extensionsViews.ts#L97))<br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./base/common/event.ts:513:73](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/common/event.ts#L513))<br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./base/common/event.ts:513:73](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/common/event.ts#L513))<br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./base/common/event.ts:486:14](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/common/event.ts#L486))<br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./base/common/event.ts:228:15](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/common/event.ts#L228))<br/>&nbsp;&nbsp;at&nbsp;`fire`&nbsp;([./base/browser/ui/list/listWidget.ts:166:17](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/browser/ui/list/listWidget.ts#L166))<br/>&nbsp;&nbsp;at&nbsp;`set`&nbsp;([./base/browser/ui/list/listWidget.ts:1102:13](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/browser/ui/list/listWidget.ts#L1102))<br/>&nbsp;&nbsp;at&nbsp;`setFocus`&nbsp;([./base/browser/ui/list/listWidget.ts:1109:7](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/browser/ui/list/listWidget.ts#L1109))<br/>&nbsp;&nbsp;at&nbsp;`focusNext`&nbsp;([./base/browser/ui/list/listPaging.ts:170:12](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./base/browser/ui/list/listPaging.ts#L170))<br/>&nbsp;&nbsp;at&nbsp;`focusNext`&nbsp;([./workbench/electron-browser/commands.ts:54:8](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./workbench/electron-browser/commands.ts#L54))<br/>&nbsp;&nbsp;at&nbsp;`focusDown`&nbsp;([./workbench/electron-browser/commands.ts:92:31](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./workbench/electron-browser/commands.ts#L92))<br/>&nbsp;&nbsp;at&nbsp;`apply`&nbsp;([./platform/instantiation/common/instantiationService.ts:54:13](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./platform/instantiation/common/instantiationService.ts#L54))<br/>&nbsp;&nbsp;at&nbsp;`apply`&nbsp;([./workbench/services/commands/common/commandService.ts:63:60](https://github.com/Microsoft/vscode/blob/241923763dbeaf3b64443187e935d55b29f6125d/src/vs/./workbench/services/commands/common/commandService.ts#L63))<br/>
