### ISSUE TITLE
Stopping a debug session does not kill task launched by the Task

### ISSUE THREAD

**Issue by isaacabraham** [microsoft/vscode#65288]
Using latest VS Code. We have a Launch task which starts a background task which in turn launches a web application which is debugged by Chrome (and therefore by VS Code). When you stop the debugger in Code, it does not stop the backround task that was launched - and there's no way to get a handle to that to somehow stop it. The only workaround seems to be to explicitly CTRL + C from the terminal that was initiated by VS Code.

Linking to https://github.com/SAFE-Stack/SAFE-template/issues/191 and https://github.com/Microsoft/vscode-chrome-debug/issues/759.

**Comment by isaacabraham** [comment]
And this isn't a duplicate to that issue above.

**Comment by Desires** [comment]
why not both q

Mr. VictorP.Garza

**Comment by isidorn** [comment]
@Krzysztof-Cieslak let's first design the feature, and than see if we want something like this.
Should this be configurable or we should always kill the task? I think it should be configurable via a launch configuration attribute. For example "autoTerminatePrelaunchTask"

I am still not convinced if we need this. Leaving up to @weinand to decide

Here's the place where the debug should terminate the task https://github.com/Microsoft/vscode/blob/8a390ea608acc6c9a759c3ad7091dd6475c97acc/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L510
Here's the place where a launch configuration attribute should be added with description
https://github.com/Microsoft/vscode/blob/8a390ea608acc6c9a759c3ad7091dd6475c97acc/src/vs/workbench/parts/debug/node/debugger.ts#L283

**Comment by isaacabraham** [comment]
> I am still not convinced if we need this. Leaving up to @weinand to decide

@isidorn what alternative could we use to do accomplish this?

**Comment by peterhuene** [comment]
I am also trying to devise a way to accomplish this.  My `preLaunchTask` runs a background command that eventually launches the process the debugger will attach to.  I'd like to terminate the process started by the `preLaunchTask` when debugging stops.

Right now I have a `postDebugTask` that uses `${command:workbench.action.tasks.terminate}` with an argument for the task to terminate, but the command doesn't seem to respect the argument and instead prompts for the task to terminate.  While selecting the task "works", it is not a good user experience.

**Comment by wpatter6** [comment]
@peterhuene Can you provide the json for the task that you're using with the `${command...` that you mention?  I'm thinking this would still be a better experience than manually killing the terminal for me

**Comment by wpatter6** [comment]
One workaround I've found is to instead of terminating the task, to just kill the terminal with `${command:workbench.action.terminal.kill}`.  Probably not ideal because if you have switched to a different terminal while debugging then it kills that one, but it does work relatively well if you left it on your background task...

**Comment by atljoseph** [comment]
hi all, ```pkill -f gocode```

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/24779
