### ISSUE TITLE
Support environment variables in `.code-workspace` files

### ISSUE THREAD

**Issue by johnmarkwayve** [Microsoft/vscode#65285]
The C/C++ extension has a nice feature where in its `c_cpp_properties.json` you can interpolate environment variables (e.g. `${env:USER_SPECIFIC_PATH}/some/dependency`). It would be great to incorporate this for `.code-workspace` files too (and any other settings file parsing that doesn't currently support it).

**Comment by bpasero** [comment]
There is https://github.com/Microsoft/vscode/issues/44755, but I guess you talk about settings in general. I am quite sure we have a duplicate for this already @sandy081

**Comment by sandy081** [comment]
Duplicate of #2809
