### ISSUE TITLE
macOS: window not maximized anymore with native title

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#65280]
When the custom title bar is disabled (e.g. with native window tabs or simple fullscreen enabled), the VSCode window on an external monitor is sized ~20px smaller around its corners and thus no longer shows fully maximized.

This is reported as https://github.com/electron/electron/issues/16015

**Comment by bpasero** [comment]
Fixed by updating to Electron 3.1.2

**Comment by aeschli** [comment]
Tested with native tabs on Mac and all looks good to me
