### ISSUE TITLE
Disable warning in markdown preview doesn't immediately hide the warning

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#65287]
```markdown
![smth](http://smth.jpg)
```

When previewing not secured content - there's a warning. `Some content has been disabled in this document`.

Choosing the last item - `Disable preview security warning in this workspace` - the warning is still there and requires to close and reopen the preview.

---

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Does not repo on MacOs or Windows in the current insiders build

* Does this happen in the current insiders builds (1.31) with all extensions disabled
* How are you opening the markdown file. Is it in a workspace?

**Comment by usernamehw** [comment]
> Does this happen in the current insiders builds (1.31) with all extensions disabled

Yes.

> How are you opening the markdown file. Is it in a workspace?

Preview to the side. It is a workspace. Not multi-root.

![demo](https://user-images.githubusercontent.com/9638156/50182537-a561d600-0320-11e9-8edd-e0763d6ed074.gif)

**Comment by mjbvz** [comment]
Sorry, I misread which `disable` you were selecting. Confirmed that selecting the last item does not refresh the preview

**Comment by skprabhanjan** [comment]
@mjbvz , fixing this :)
