### ISSUE TITLE
Search in all files doesn't show results when interupted by new search

### ISSUE THREAD

**Issue by Tim-Veestraeten** [Microsoft/vscode#65284]
- VSCode Version: 1.30.0 (user setup)
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Open a large folder in vs code so the search takes a while
2. Click the magnifying glass
3. Search anything
4. Modify the search term of files to include or exlcude
5. Press enter before de previous search is done.

The message 'search was canceled before any results could be found' is shown'.
Clicking 'Search again' or attempting to search by pressing enter or the refresh button does not search again.
After a while the message will change to a number of results, which is te same number as a successful search of the current query, but no results will be displayed. Searching again from this point will work.

![image](https://user-images.githubusercontent.com/33923948/50152070-e3c8a800-02c2-11e9-8b33-cdd4f2d9568a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/65084 Fixed in the new 1.30.1 release
