### ISSUE TITLE
select text - equals are highlighted only to 1000 rows

### ISSUE THREAD

**Issue by nrc34** [Microsoft/vscode#6528]
- VSCode Version:1.1.1
- OS Version: Windows 7 Pro SP1

Steps to Reproduce:

1. Select a text at the editor
2. If you have 2000 rows with equal texts then the one selected, those are highlighted only to 1000 row. The other ones are not highlighted .

**Comment by alexandrudima** [comment]
That is correct, the editor highlights only the first 1000 hits. Dup of #1110
