### ISSUE TITLE
Multiline regex returns incorrect results

### ISSUE THREAD

**Issue by BasKiers** [microsoft/vscode#65281]
Issue Type: <b>Bug</b>

Using multiline regexes results in incorrect results in some use-cases.

### Steps to reproduce
Create a file with the following content: 
```
this/is{
a test
}
```
use search with this regex: `this/\w*[^}]*`

Expected result should be this selection (between `|`)
```
|this/is{
a test
|}
```
Actual result for this search is
```
|this/is{|
a test
}
```

Additionally, when a `\n` is added at the end of the regex (`this/\w*[^}]*\n`) the selection includes `a test` in the result like this:
```
|this/is{
a test|
}
```

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.15.1
bracket-pair-colorizer-2|Coe|0.0.25
vscode-eslint|dba|1.7.2
gitlens|eam|9.2.1
prettier-vscode|esb|1.7.2
php-intellisense|fel|2.3.10
flow-for-vscode|flo|0.8.5
auto-rename-tag|for|0.0.15
shell-format|fox|2.0.2
vscode-yarn|gam|1.6.0
vscode-pull-request-github|Git|0.3.2
phpcs|ika|1.0.5
plantuml|jeb|2.10.1
php-namespace-resolver|Meh|1.1.0
mssql|ms-|1.4.0
cpptools|ms-|0.20.1
vscode-docker|Pet|0.4.0
polacode|pnp|0.2.2
vscode-yaml|red|0.1.0
LiveServer|rit|5.3.1
vscode-icons|rob|8.0.0
code-spell-checker|str|1.6.10
shellcheck|tim|0.6.0
vscode-arduino|vsc|0.2.24
vscode-wakatime|Wak|1.2.5

</details>

**Comment by roblourens** [comment]
@alexdima I don't think this is the right fix. `\w` is for a "word character", it won't match whitespace or a newline. Enabling multiline search has perf impact in text search so I don't want to do it for this case (it also triggers a ripgrep but in https://github.com/microsoft/vscode/issues/131507). Is it ok if I revert this?

**Comment by alexdima** [comment]
😱 I have reverted that, no idea what I was thinking :). Of course `\w` means word character and not whitespace :).

Unfortunately, we're gonna have to live with the original bug, without a better hint for a multiline regex, we will avoid doing a multiline search. There is some discussions right now about find widget UX and maybe multiline could be considered in this discussion cc @rebornix

**Comment by roblourens** [comment]
Yeah I think an explicit toggle would be great and is the only real solution
