### ISSUE TITLE
Support mathJax formula preview in markdown

### ISSUE THREAD

**Issue by skyhiter** [Microsoft/vscode#6529]
- VSCode Version:1.1.1
- OS Version:win10 64

Steps to Reproduce:

markdown code as follows can't preview:
### LaTeX 公式

可以创建行内公式，例如 $\Gamma(n) = (n-1)!\quad\forall n\in\mathbb N$。或者块级公式：
$$  x = \dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a} $$

**Comment by bpasero** [comment]
@kieferrm maybe a case for an extension for the markdown extension?

**Comment by GaZ3ll3** [comment]
maybe this helps those people who wants mathjax.
https://gist.github.com/3846masa/cde99a18a8d7ad225cf7

simply use regex to find the mathjax block and render. It could be total cool to include as an extension.

**Comment by jrappen** [comment]
Please use https://github.com/Khan/KaTeX instead of https://github.com/mathjax/MathJax

**Comment by goessner** [comment]
see ...
[Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath)

**Comment by jrappen** [comment]
@bpasero, @kieferrm maybe you could merge the functionality of the repo linked by @goessner above into the default package?

**Comment by jrappen** [comment]
@goessner: Your repo is top trending repo nr. 6 on Github at the moment. Maybe you could link to this issue so people can vote for it with a :+1: by reacting to the issue description.

**Comment by mjbvz** [comment]
MathJAX is not something we want to add to our core markdown preview extension, but we still do want to support extending the markdown preview in this way. To allow this, I've implemented a proposal for markdown extensions in VSCode 1.11: #22916

This prototype extension demonstrates enabling katex in the preview for example:  https://github.com/mjbvz/vscode-markdown-katex

If someone would be interested in creating a prototype mathjax extension using the proposed API, please let me know. The katex extension is probably a good starting point. The API is also still a WIP, so any feedback on it would be greatly appreciated


// FYI  @snyang

**Comment by kieferrm** [comment]
With the markdown [extensions support](https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/api-markdown.md) this is now an extension candidate.
