### ISSUE TITLE
VSCode folder instead of just Code folder.

### ISSUE THREAD

**Issue by jcs090218** [Microsoft/vscode#65292]
Hi, I just wonder why would the settings file are under `/Code/User/settings.json`? I am totally fine with the User directory because it define user data in it but why name `Code` colder? Would it be better with something more definable? e.g. VSCode. It kind of bothers me while I trying to backup my settings files because I would often need to reckon where are all my settings files located, and surprisingly is located in the `Code` folder and not something more direct or lucid. Just a proposition!

**Comment by bpasero** [comment]
Our editor is called "Code". VS is a prefix that we try to hide in places where possible to keep the name short and lean. I also think its too late now to change that.
