### ISSUE TITLE
Log: why is toLocaleTimeString() used?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#65293]
I noticed the logger is using `toLocaleTimeString()`. This triggers an expensive call to the `Intl ` code and I would expect that a log should always use a consistent date format that we can understand? Can we change it to not respect the locale of each user?

![image](https://user-images.githubusercontent.com/900690/50160118-ba1a7b80-02d8-11e9-817e-c751afcfca1e.png)

**Comment by joaomoreno** [comment]
Traced the usage all the way back to 3 years: https://github.com/Microsoft/vscode/blame/2287885406a34e9f4ee4765134752d197c6f08ce/src/vs/workbench/electron-main/log.ts.

So... :man_shrugging:
