### ISSUE TITLE
Document what the integrated shell executes

### ISSUE THREAD

**Issue by louisabraham** [Microsoft/vscode#65295]
My $PATH is completely shuffled in zsh in the integrated terminal, and I have no idea why. There are several related issues, and having a clear reference would definitely help.

**Comment by Tyriar** [comment]
That's happening because VS Code runs a login shell and then the terminal does as well. You could try adding this setting or otherwise tweak your start up scripts to be idempotent:

```
"terminal.integrated.shellArgs.osx": []
```

**Comment by louisabraham** [comment]
The problem is NOT that I have duplicates. It is that $PATH is shuffled.

Thank you for your solution, I figured it out in the meantime. Out of curiosity, why is the login shell the default on macOS?
