### ISSUE TITLE
Inconsistent mouse cursor when hovering text in 1.30.0

### ISSUE THREAD

**Issue by johananl** [microsoft/vscode#65294]
- VSCode Version: 1.30.0
- OS Version: 4.19.9-arch1-1-ARCH

Upgrading from 1.29.0 to 1.30.0 seems to cause the mouse cursor to behave unexpectedly. For example, when hovering a line of text in the editor there seems to be some kind of "invisible barrier", to the right of which the cursor turns from text cursor to a normal cursor.

Steps to Reproduce:

1. Create a new file (**File -> New File**).
2. Type a long line of text, longer than 50% of the window's width.
3. Hover the line of text from left to right. Somewhere around the middle of the window, the cursor changes from a text cursor to a normal cursor.

Resizing the window moves the point of change.

The expected behavior would be to see a text cursor as long as the user is hovering text inside the editor, and a normal cursor when hovering menus, for example.

This happens also on latest insiders build, with default config and no extensions.

**Comment by alexandrudima** [comment]
@johananl Can you please attach a screen recording? It would make it easier to understand the problem.

**Comment by johananl** [comment]
![output](https://user-images.githubusercontent.com/14969425/50175623-90c01680-02fd-11e9-8403-daee4d328024.gif)

There you go. Please forgive the video quality.

**Comment by alexandrudima** [comment]
That area looks suspiciously like 1/2 the width or 1/2 height of the window. Do you by any chance use a high DPI monitor or do some kind of zoom, etc ?

**Comment by johananl** [comment]
>That area looks suspiciously like 1/2 the width or 1/2 height of the window.

True, noticed that as well.

>Do you by any chance use a high DPI monitor or do some kind of zoom, etc?

Yes, both. My ThinkPad has a high-DPI screen and I run it with scaling (otherwise text is practically unreadable).

>If you resize the window, does the area where the cursor changes also change?

Yes.

**Comment by seesemichaelj** [comment]
I can confirm that I have the same issue on my high DPI laptop monitor (3000x2000). I do not use any scaling/zoom. 

Doing a little of investigative work with resizing the window, I've determined that the cursor renders as `text` given the following parameters:
- The relative (to the entire window) x location of the cursor is <= 0.5*window_width
- The relative (to the entire window) y location of the cursor is <= 0.5*window_height
- The cursor is hovering over the text editing pane (goes without saying, but better to be clear)

Opening up the chrome dev tools, I double checked, and verified, that the CSS said that `cursor: text` over areas that were not rendering as `text`. I have a feeling something else is controlling the cursor CSS

**Comment by alexandrudima** [comment]
@johananl @seesemichaelj Can you reproduce this also when opening a page with Chromium e.g. https://microsoft.github.io/monaco-editor/

I believe this is an upstream bug in Chromium with high DPI monitors. Most likely they have some confusion and compare CSS pixels with screen pixels or something like that...

**Comment by seesemichaelj** [comment]
Going to my LoDPI setup, my horizontal 1080p monitor even shows flickering (that I'm now just noticing) between `normal` and `text` but defaults to text. Moving the window to my vertical 1080p monitor (so a width of `1080` instead of `1920`), I don't notice the flicker.

If I extend my vscode window across my 4 monitors (2 vertical 1080's + 2 horizontal 1080's = 6000 pixels), I'll notice the cursor flicker on the horizontal monitors and not the vertical ones (the vertical ones do slightly, but a much reduced rate). This is on the same, unmoved, 6000 pixel wide vscode window. I do not notice the halfway mark (~3000 pixels) no longer showing the `text` cursor.

I'm not sure what to take away from this, but :man_shrugging:

**Comment by bpasero** [comment]
@johananl are you sure you are on 1.30 and not 1.31 insiders? Because in that build we did change Electron from 2 to 3.

**Comment by bpasero** [comment]
@seesemichaelj does it reproduce when you run `code --disable-gpu` ?

**Comment by seesemichaelj** [comment]
yes, both `1.30.1` and `1.31.0-insider`

**Comment by alexandrudima** [comment]
Thanks @bpasero for the hint. But I did not have at hand an installation of 1.29.0 to check.

---

@johananl You mentioned the issue only reproduces in 1.30.0 and not in 1.29.0? - https://github.com/Microsoft/vscode/issues/65294#issue-392174645 - "Upgrading from 1.29.0 to 1.30.0 seems to cause the mouse cursor to behave unexpectedly"

---

@seesemichaelj @johananl Can you please confirm this was a regression starting with 1.30.0 and 1.29.0 was working fine? Here is a zip download link for 1.29.0 - https://az764295.vo.msecnd.net/stable/5f24c93878bd4bc645a4a17c620e2487b11005f9/code-stable-1542008778.tar.gz

**Comment by bpasero** [comment]
@seesemichaelj does it reproduce when you run code --disable-gpu ?

**Comment by bpasero** [comment]
Are you using zoom?

**Comment by johananl** [comment]
>does it reproduce when you run code --disable-gpu ?

Yes, it does.

>Are you using zoom?

The zoom functionality in Code? No, I'm not.

I am, however, using **scaling** on my displays. I have the Gnome "Scale" setting at 200% (because text is unreadable otherwise). When setting scale to 100% the problem disappears. So, the issue seems to be scaling-related.

Hope this helps troubleshoot this further.

**Comment by seesemichaelj** [comment]
Ah it appears that my distro (elementary OS) was auto scaling my display by 200% as well. Setting the scale factor to 100%, though unusable, does fix the cursor problem.

I noticed in the chrome dev tools that the calculated pixel width for `100%` would be half the pixels that were actually being used (for example, the chrome dev tools thought my full screen code window was 1500px wide, but my display is 3000px wide)

**Comment by iaeiou** [comment]
If you are using Gnome, try to disable the Gnome extensions

**Comment by eevleevs** [comment]
> If you are using Gnome, try to disable the Gnome extensions

:+1: here cursor work again normally after disabling/enabling Dash to Panel
