### ISSUE TITLE
cursorHomeSelect command not working since last update

### ISSUE THREAD

**Issue by thanuzz** [Microsoft/vscode#65300]
Issue Type: <b>Bug</b>

Since the latest VS code the `cursorHomeSelect` command (used inside a macro using geddski's macros plugin) doesn't seem to work anymore. 
I've pinned it to down to the `cursorHomeSelect` by deleting the other steps in the macro. 

# settings.json:
```
{
    "macros": {
        "snippetWithDescriptionAndVariable": [
            "editor.action.clipboardCopyAction",
            "editor.action.insertLineAfter",
            "editor.action.clipboardPasteAction",
            "cursorHomeSelect",
            {
                "command": "editor.action.insertSnippet",
                "when": "editorTextFocus",
                "args": {
                    "snippet": "console.log(`${TM_SELECTED_TEXT}: `, ${TM_SELECTED_TEXT});$0"
                }
            }
        ]
    }
}
```

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.94GB (5.85GB free)|
|Process Argv|--folder-uri file:///c%3A/repos/winq-viewer|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.2.1
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
macros|ged|1.2.1
sass-lint|gle|1.0.4
search-node-modules|jas|1.3.0
svn-scm|joh|1.46.4
code-beautifier|mic|2.1.0
ts-barrelr|mik|1.2.1
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.1
vscode-icons|rob|8.0.0
ftp-kr|rua|1.3.16
iis-express|war|1.1.2

</details>

**Comment by usernamehw** [comment]
Looks just like my old snippet. You can simplify it by using `$CLIPBOARD`. In extension code format:

```typescript
commands.executeCommand('editor.action.clipboardCopyAction');
commands.executeCommand('editor.action.insertLineAfter');
commands.executeCommand('editor.action.insertSnippet', {
	snippet: 'console.log(\'$CLIPBOARD\', $CLIPBOARD);$0'
});
```

**Comment by alexandrudima** [comment]
This is an issue with the extension. As can be spotted [here](https://github.com/geddski/macros/blob/96b0d7b2930c26eea22f2a9acbebba823bc98c5b/extension.js#L34) the extension does not correctly wait for the promises returned by `executeCommand`. The fact that this ever worked is a surprise to me, but it might have been because of our usage of winjs promise which resolve synchronously. Now we are using native promises, which resolve asynchronously and not waiting on promises correctly is a bigger problem. The fix I guess is to return those promises in that code, or, in general, to `await` the call before proceeding with the next command invocation.

**Comment by usernamehw** [comment]
[macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) is dead. There's another one that can specify delay between running commands: [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
