### ISSUE TITLE
MacBook Pro Touchbar Start Debugging Button not working (in Python)

### ISSUE THREAD

**Issue by MaxxRe3** [Microsoft/vscode#65306]
Issue Type: <b>Bug</b>

Regardless of what python code I want to start, the "Play" button in the touch bar does not work. I have to hit fn+F5 to start the debugging. However, when I started the process via fn+F5 all the subsequent touchbar buttons work perfectly fine.
It doesn't make a difference if a Breakpoint is set or not. 
My launch.json and settings.json have only the default settings.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1

</details>

**Comment by isidorn** [comment]
Will be fixed in the recovery release later today / tomrrow.
Closing as dupplicate
