### ISSUE TITLE
Problem file filter doesn't work

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#65302]
Issue Type: <b>Bug</b>

There is a gear is problem view. It seems like it has no effect on problems list. It should filter by filename, not by problem description according to description.
![image](https://user-images.githubusercontent.com/7345761/50162803-379db600-02f0-11e9-808c-64bfdda1d540.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.18.0-12-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3805)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (0.36GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
blamer-vs|bea|0.4.0
better-toml|bun|0.3.2
ccls|ccl|99.1.17
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.2
vscode-dash|dee|2.0.0
java-decompiler|dgi|0.0.2
xml|Dot|2.4.0
gitlens|eam|9.2.1
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
prettier-vscode|esb|1.7.3
file-icons|fil|1.0.16
code-runner|for|0.9.5
todo-tree|Gru|0.0.110
perl-outline|hit|0.0.4
svn-scm|joh|2.46.4
language-haskell|jus|2.5.0
favorites|kdc|2.4.5
Lua|key|0.0.9
saltstack|kor|0.0.5
sftp|lix|1.8.4
bash-ide-vscode|mad|1.3.3
vscode-todo-parser|min|1.9.1
vscode-remote-workspace|mkl|0.38.0
vscode-language-pack-ru|MS-|1.30.2
python|ms-|2018.12.1
csharp|ms-|1.17.1
Go|ms-|0.8.0
gradle-language|nac|0.2.3
printcode|nob|3.0.0
vscode-subword-navigation|ow|1.2.0
java|red|0.35.0
vscode-yaml|red|0.1.0
vscode-sort-json|ric|1.13.0
bash-debug|rog|0.3.3
rust|rus|0.5.3
bash-beautify|sha|0.1.1
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-java-debug|vsc|0.16.0
debug|web|0.22.0
clang-format|xav|1.8.0
vscode-proto3|zxh|0.2.2

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@Yanpas It says it enabling the gear icon will respect the files.exclude setting.

**Comment by Yanpas** [comment]
Meaning is very confusing in russian localization
