### ISSUE TITLE
Conflict decorators do not appear if file is opened

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#6531]
git conflict in JS doc comments 

Please see the image.

![image](https://cloud.githubusercontent.com/assets/512816/15392766/397d3854-1dc1-11e6-8d3a-d4980affb2c7.png)

**Comment by alexandrudima** [comment]
@leegee Can you please share the file or a snippet demonstrating the problem in textual form. 

What is the language indicated at the bottom right?

If it is 'JavaScript', then the text, regardless of its contents will be tokenized with the JavaScript grammar.

**Comment by leegee** [comment]
The language indicated in the bottom right is 'JavaScript'.

I'm afraid I resolved the conflict, so no, I cannot share in textual form.

I thought this was a bug because I thought I had seen your product colour blocks green and red when outside of a comment.

**Comment by alexandrudima** [comment]
You are correct, the merge decorators don't show up if the file is already opened:


![merge-decorators](https://cloud.githubusercontent.com/assets/5047891/15503794/ff33d2b2-21bb-11e6-8533-4df8637c0acd.gif)
