### ISSUE TITLE
Peek view tree sometimes scrolls when collapsing elements

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65319]
- Trigger find all references on something with a long list
- Move focus down in the list with arrow keys
- Expand a row
- Sometimes, the list scrolls back to up to the top. But the focused element stays at the same spot.
- Sometimes it doesn't happen when expanding but does when collapsing

Doesn't happen 100% of the time, not sure what's going on...

This is Severity.Error in severity.ts

![dec-18-2018 11-09-12](https://user-images.githubusercontent.com/323878/50176871-664a6b00-02b5-11e9-92da-24421ddca73c.gif)

**Comment by jrieken** [comment]
@joaomoreno This is the tree giving me a change event for the wrong item. Steps

* peek references on `Severity.Error` (see how `Error` is focused)
* arrow down to `terminalTaskSystem`
* arrow right to expand that node
* :bug: the tree fires a select change event for `Severity.Error`

<img width="1594" alt="screenshot 2018-12-19 at 10 08 22" src="https://user-images.githubusercontent.com/1794099/50210331-1f707a00-0376-11e9-997e-fccb80067e93.png">
