### ISSUE TITLE
Support minimal context menu for text selected within extension README

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#65310]
The README for my extension includes several text fragments designed for copying into settings.json. But when I highlight the text and right-click on it, no context menu appears.

It turns out that the usual Ctrl+C key sequence (I'm testing on Windows) *does* copy the selection to the clipboard. But I wish the right-click would offer a context menu with a 'Copy' option.

**Comment by gjsjohnmurray** [comment]
@mjbvz now that you've closed #86658 maybe we can get this one tackled too. You tagged it 'help wanted', so I might take a look at it. Any pointers?

**Comment by mjbvz** [comment]
I've added cut, copy, and paste actions to the menu. We can consider adding additional actions based on demand (including potentially contributed ones #54285)

**Comment by rzhao271** [comment]
Reopening because it seems that copying using the context menu option doesn't get the text into the clipboard?
![recording (26)](https://user-images.githubusercontent.com/7199958/120402298-ae7b6d80-c2f6-11eb-8525-4910b4d24a6f.gif)

**Comment by rzhao271** [comment]
@mjbvz I'm still unable to copy-paste with the context menu.
I wonder if focus is being lost to the point where `activeEditor` isn't even set?

**Comment by JacksonKearl** [comment]
Works fine for me.

**Comment by mjbvz** [comment]
Also seems to work for me on Windows: a62df5d6c53e844bfdc50694f943c3f34b6ff50e

The fix I checked in yesterday was Windows and Linux specific. I believe it always worked on MacOS

**Comment by bpasero** [comment]
@mjbvz fyi we have a standard context menu that we show in all input fields:

![image](https://user-images.githubusercontent.com/900690/120753133-0094dc80-c50b-11eb-862b-b370f12c8447.png)

I am not sure if you can detect whether the thing under the mouse is editable (= input field) or not and then show either this context menu or one with only things that work in readonly contexts (e.g. not "Cut").

**Comment by bpasero** [comment]
Verified for macOS. If you want cross browser coverage, I suggest a test plan item.
