### ISSUE TITLE
editor.action.clipboardCopyAction no longer works on blank lines after 1.30.1 update

### ISSUE THREAD

**Issue by clayms** [Microsoft/vscode#65328]
editor.action.clipboardCopyAction (`ctrl`+`c`) no longer copies blank lines since updating to version 1.30.1.

Is there a way to change this back to the previous behavior?

I need this behavior to easily run a line of code at the current location of the cursor in the editor in the integrated terminal.  Now I have to constantly manually move the cursor back and forth between the editor and the terminal.

Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.  put the cursor on a blank line or line with only white space.
1.  try to paste that content, and it will only paste what was previously in the clipboard prior to trying to copy the blank line.

**Comment by clayms** [comment]
Is there a way to complete a Boolean test to see if the line is blank?

**Comment by clayms** [comment]
This following is still set to `true`:

```
  // Controls whether copying without a selection copies the current line.
  "editor.emptySelectionClipboard": true,
```

**Comment by usernamehw** [comment]
#55243

**Comment by clayms** [comment]
@usernamehw https://github.com/Microsoft/vscode/issues/55243 is the opposite problem.  How do I go back?  Was it a setting that was added, or is it hard-coded into VS Code now?

**Comment by usernamehw** [comment]
hard-coded

**Comment by clayms** [comment]
here: https://github.com/Microsoft/vscode/blob/50f1bbb049c53c16682ed9fb41e01ef0c798edea/src/vs/editor/contrib/clipboard/clipboard.ts#L151

Why would they do this?!

Why not a user setting that gives the user a choice?

**Comment by usernamehw** [comment]
Can you elaborate this? 

> to easily run a line of code at the current location of the cursor in the editor in the integrated terminal

**Comment by clayms** [comment]
Perhaps a work-around could be had if I had a way to check if the line was blank.

Does anyone know how I can check if the line is blank?

Something that could be put in the user settings with a `when`  like the following?

```
{
    "command": "workbench.action.terminal.sendSequence",  "args": { "text": "\n" } ,
     "when": " (editor.getSelections().length === 1 && editor.getSelection().isEmpty())"
}
```

**Comment by clayms** [comment]
@usernamehw 
I use the macros extension to bind one keystroke `ctrl`+`enter` to send code from the editor to the active terminal. 

keybindings.json:
```
    {
        "key": "ctrl+enter",
        "command": "macros.runLine",
        "args": {"cmd": "ls", "match": ".*"},
        "when": "editorTextFocus"
    }
```


settings.json
```
"macros": {
        "runLine": [
            "editor.action.clipboardCopyAction",
            "cursorDown",
            "workbench.action.terminal.paste",
            {"command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus"}
        ]
    }
```

**Comment by usernamehw** [comment]
Would something like that work?
`keybindings`
```json
{
	"key": "ctrl+enter",
	"command": "macros.runLine",
	"args": {
		"cmd": "ls",
		"match": ".*"
	},
	"when": "editorTextFocus && !editorHasSelection"
},
```
`settings`
```json
"macros": {
	"canCopyEmpty": [
		"expandLineSelection",
		"editor.action.clipboardCopyAction",
		"cancelSelection"
	],
	"runLine": [
		"macros.canCopyEmpty",
		"workbench.action.terminal.paste",
		{
			"command": "workbench.action.focusActiveEditorGroup",
			"when": "terminalFocus"
		}
	],
},
```

**Comment by clayms** [comment]
@usernamehw  That works perfect!  Thanks!
