### ISSUE TITLE
Reopen issue 21518 or 18782 

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#65327]
Please reopen either https://github.com/Microsoft/vscode/issues/21518 or https://github.com/Microsoft/vscode/issues/18782 . The bug still repros with C/C++.

void foo(int, const char*, const char *) { // also repros when the params are subsets, e.g. a, aa, aaa

}

int main()
{
    foo(a, ) // signature Help selects the the 3rd param instead of the 2nd.
}

**Comment by jrieken** [comment]
@sean-mcmanus Did you adopt the new API that required for this?

**Comment by sean-mcmanus** [comment]
@jrieken Okay, thanks for letting me know -- I found that new API thread at https://github.com/Microsoft/vscode/issues/56337 (I wasn't on the thread, but Bob was). We'll try sending back the range result.
