### ISSUE TITLE
Multiline search doesn't work

### ISSUE THREAD

**Issue by govindrai** [Microsoft/vscode#65322]
- VSCode Version:
1.30.0
- OS Version:
10.13.6
- Also tried Insiders version
1.31.0-insider

Steps to Reproduce:

1. Invoke Search CMD + F
2. Enter first line of search, press SHIFT+Enter
3. Expect search box to grow and new line to appear, however, pressing SHIFT+Enter just cycles through any matched text

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This only works in the search view (global search) not in the editor find widget currently.
