### ISSUE TITLE
Comment panel not updating with onDidChangeCommentThreads event

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#65329]
Issue Type: <b>Bug</b>

1. Register a `WorkspaceCommentProvider` and `DocumentCommentProvider`
1. In `DocumentCommentProvider.createNewCommentThread` fire `WorkspaceCommentProvider.onDidChangeCommentThreads` event with the newly added thread in `added` property in the event.

*Expected:*
The comment panel is updated. This works in stable VSCode 1.30.0.

*Actual:*
The comment panel is NOT updated. It looks like an exception is thrown by the event handler, though I couldn't get the details of it from attached VSCode debugger.

VS Code version: Code - Insiders 1.31.0-insider (edf1090b8546ad0d17f30bf6f8075613e37e1b37, 2018-12-17T10:06:30.031Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (4.48GB free)|
|Process Argv|--folder-uri file:///c%3A/src/cascade1/vscode/extension|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by IlyaBiryukov** [comment]
cc @RMacfarlane

**Comment by IlyaBiryukov** [comment]
cc @lostintangent 
Here is the data in the event:
```
{added: [vscodeThread], changed: [], removed: []}

vscodeThread = {
	threadId: "1", 
	resource: t, 
	range: e, 
	comments: Array(1)
}
comments: Array(1) 
0: {
	commentId: "1/0", body: e, userName: "Ilya Biryukov", …}
	body: e {value: "Comment text"}
	canDelete: true
	canEdit: true
	commentId: "1/0"
	userName: "Ilya Biryukov"}
range: e {_start: e, _end: e}
resource: t {scheme: "file", authority: "", path: "/c:/tmp/node/1/app.js" }
threadId: "1"
}
```

**Comment by IlyaBiryukov** [comment]
Ping?

**Comment by IlyaBiryukov** [comment]
@RMacfarlane Do you think you can fix this bug in April?

**Comment by RMacfarlane** [comment]
@IlyaBiryukov Yeah, I'll look at this this week.

But, as an fyi, we are introducing a new version of the proposed commenting API and plan to deprecate the old proposal in the coming months. More info here: https://github.com/Microsoft/vscode/issues/68020

**Comment by IlyaBiryukov** [comment]
@RMacfarlane Is the new API ready to be used? Maybe the issue is already fixed with the new API.

**Comment by RMacfarlane** [comment]
Yes, it's available in the `proposed.d.ts` in the current VS Code Insiders. The GitHub Pull Request extension has just adopted it, there's also sample extension for it here: https://github.com/Microsoft/vscode-extension-samples/tree/master/comment-sample

**Comment by IlyaBiryukov** [comment]
Comment panel is updating just fine with the new API. I'm going to close this issue then.
