### ISSUE TITLE
Hot Exit doesn't work when closing a workspace with unsaved files

### ISSUE THREAD

**Issue by tomprogers** [Microsoft/vscode#65330]
Issue Type: <b>Bug</b>

Hot exit prevents me from closing a workspace with unsaved files in it. I want to switch projects for an hour, and I don't want to be forced to dispose of every unsaved file buffer in my current workspace to do so.

Hot Exit _does_ allow me to quit VS Code completely without disposing of unsaved buffers, but if I want to close a workspace without quitting the app, it forces me to dispose of unsaved buffers.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 5, 3|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
json-tools|eri|1.0.2
vscode-power-mode|hoo|2.2.0
plantuml|jeb|2.10.1
vs-docblock|jer|0.4.2
chat|kar|0.9.0
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.1071
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.4
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
sort-lines|Tyr|1.7.0

</details>

**Comment by Tyriar** [comment]
You probably want to set `"files.hotExit": "onExitAndWindowClose"`, read the setting description for more info.
