### ISSUE TITLE
Extension host crashes for something related to fsevents

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#65335]
- VSCode Version: 1.31.0-insider
- OS Version: macOS 10.14

Steps to Reproduce:

1. Install [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus)
2. Open any directory with some files
3. Open the newly added "Todo" activity bar views container
4. The extension host crashes soon after that

I'm seeing the same problem with another extension of mine, [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus), both of them are using [chokidar](https://www.npmjs.com/package/chokidar), which in turns uses [fsevents](https://www.npmjs.com/package/fsevents) on macOS, this is the error I'm getting in the console:

<img width="1440" alt="screen shot 2018-12-19 at 00 54 43" src="https://user-images.githubusercontent.com/1812093/50190401-62583080-0329-11e9-976f-1f1ab13dd8f3.png">

**Comment by alexandrudima** [comment]
@bpasero you have a lot of experience with file watching, maybe you have some tips?

@fabiospampinato we also expose file watching API, could you use our API?

**Comment by bpasero** [comment]
@fabiospampinato this can be explained by the fact that we updated Electron 3 for insiders which requires any native module to be recompiled.

We DO NOT RECOMMEND to use native modules for extensions for this reason. See also https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles#_can-i-use-native-nodejs-modules-with-my-extension

**Comment by tomrav** [comment]
I'm getting the same error as the OP, while developing my extension (stylable-intelligence).
After some debugging, I've narrowed it down to several 3rd party dependencies bringing an older version of `fsevents` (v1).

I have managed to resolve the issue by replacing the pre-built `fsevents` dependency with a newer version (v2, which uses N-API). 

As a temporary hack/work-around, I am planning on releasing a new extension version with `fsevents` explicitly replaced to a newer version. I'll then proceed to update/replace my problematic dependencies properly.

**Comment by fabiospampinato** [comment]
> @fabiospampinato we also expose file watching API, could you use our API?

Yeah I guess I'll have to switch to that.

@bpasero I'd be helpful if there was a script for finding dependencies that use native modules, I've found this thing: 

```
find node_modules -type f -name "*.node" 2>/dev/null | grep -v "obj\.target"
``` 

but I guess it won't work if run in Todo+'s repo on a non-macOS system 🤔
