### ISSUE TITLE
Autoscroll when saving

### ISSUE THREAD

**Issue by pascalandy** [Microsoft/vscode#65332]
Issue Type: <b>Bug</b>

When I save (CMD -S) the editor scroll down by one line. 

It drives me crasy :-(

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
css-compressor|bes|0.0.2
vscode-markdownlint|Dav|0.22.0
whitespace-plus|dav|0.0.5
vscode-yaml-validation|dja|0.0.1
gitlens|eam|9.2.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
json-tools|eri|1.0.2
prettier-vscode|esb|1.7.3
shell-format|fox|2.0.2
minify|Hoo|0.3.0
vscode-browser-sync|jas|1.3.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.1.0
handlebars-formatter|mfe|0.0.3
prettify-json|moh|0.0.3
vscode-docker|Pet|0.4.0
vscode-icons|rob|8.0.0
whitespace|san|0.0.5
shellcheck|tim|0.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by usernamehw** [comment]
Does it repro without extensions? `code --disable-extensions`

**Comment by egamma** [comment]
@pascalandy this is commonly caused by an extension that modifies a file on save. To narrow this down:

- see https://github.com/Microsoft/vscode/issues/65332#issuecomment-448404905
- what file type are you editing when this happens

**Comment by pascalandy** [comment]
It's a bash-script.
I realized that it was the git extension. I removed it and the issue is gone. 
I guess the issue on under the extension. 

Thanks!
P
