### ISSUE TITLE
the version 1.30.1 debug error

### ISSUE THREAD

**Issue by enjustli** [Microsoft/vscode#65342]
- VSCode Version: 1.30.1
- OS Version: ubuntu 18.10

Steps to Reproduce:
 
1. when i use gdb debug, it crashed. the error message is : stopping due to fatal error: NullReferenceException: Object reference not set 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@enjustli Can you please create an issue directly at https://github.com/Microsoft/vscode-cpptools ?
