### ISSUE TITLE
Option so "match whole word" becomes effectively "match whole name" (exact match)

### ISSUE THREAD

**Issue by ncodefun** [Microsoft/vscode#65347]
I've been bitten way too much by this when batch replacing... 
Most (or all) of the time I use *match whole word* to find exact match, but unfortunately it matches more, e.g. Searching for `background` would match `background-color`.

I think the option could be `use "match whole name" instead of match whole word"` ?

**Comment by alexandrudima** [comment]
I think you should use a regular expression for this use-case. Perhaps something like `background(?=[:\s])`

**Comment by ncodefun** [comment]
I know about regex, but since this is the behavior I want all the time, and that this is a more expected behavior (in my mind anyway), I'd prefer not having to think about entering a regex every time. There's noting that stops me in my flow like having to think about regex! :|
