### ISSUE TITLE
Keyboard shortcut for left side views should toggle view visibility

### ISSUE THREAD

**Issue by ajaygm** [Microsoft/vscode#65343]
Issue Type: <b>Bug</b>

The views displayed on the left side (Explorer, Search, Source Control, Debug, Extensions, Test, etc.) have keyboard shortcuts (e.g. "Ctrl + Shift + E" for Explorer) to show the view. If the view is not displayed you can make it visible by using the keyboard shortcuts. If you use the same keys when the view is already visible it does nothing. The behavior should be to toggle the view like it does for the Console view (keyboard shortcut "Ctrl + Shift + Y"). 

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (5.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.4.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.1.1
vscode-manifest-yaml|Piv|1.1.1
vscode-spring-boot|Piv|1.1.1
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.3

</details>

**Comment by isidorn** [comment]
Nope disagree. And we will not change this.
To toggle use ctrl + B.

**Comment by usernamehw** [comment]
You can do the toggling yourself:
```json
{
	"key": "ctrl+shift+E",
	"command": "workbench.action.toggleSidebarVisibility",
	"when": "explorerViewletVisible"
}
```
