### ISSUE TITLE
New version with uncomfortable bold text for code explanation area

### ISSUE THREAD

**Issue by FaiChou** [Microsoft/vscode#65341]
- VSCode Version: 1.30.0 (1.30.0)
- OS Version: macOS Mojave 10.14.2

Does this issue occur when all extensions are disabled?:  Not check

![image](https://user-images.githubusercontent.com/18500846/50194502-27c8b500-0376-11e9-9e1f-94c7268ca862.png)

Here is a bold text example which in old version it's not the same.

How to change the default behavior of font-weight?

**Comment by infinnie** [comment]
#65339
