### ISSUE TITLE
gulp not found for tasks when using custom location for global installs

### ISSUE THREAD

**Issue by davidmcl** [Microsoft/vscode#6534]
- VSCode Version: 1.1.1
- OS Version: Linux Mint 17.3

Steps to Reproduce:
1. set npm globals to custom location; e.g. **npm config set prefix '~/.npm-global'**
2. change $PATH to put custom npm global folder first
3. install gulp and other globals modules to custom location

If I try to run a task, the following message is received...even though npm ls -g confirms gulp is installed properly...
_Gulp is not installed on your system. Run npm install -g gulp to install it._

If I install gulp as global to the root location, then the task will run properly

Thanks,
David

**Comment by angel-aam** [comment]
I have got the very same issue, (currently running vsCode 1.3.1 over Ubuntu 16.04)
It seems that, when vsCode is launched through .desktop entry created after install, it doesn't seem to recognise this custom npm global folder. When is launched by a terminal like ```code .``` it works perfectly though

Hope it helps

**Comment by dbaeumer** [comment]
@joaomoreno  looks like we still don't source the environment correctly when not launched from a terminal. I guess VSCode does't see the correct path.

@angel-aam could you do the following when started from the .desktop entry.

- F1 > Toggle Dev Tools
- in the console could you check if the process.env.PATH contains your custom global npm bin folder which contains the gulp script.

**Comment by angel-aam** [comment]
Hi @dbaeumer, I've tried what you posted and the PATH wasn't configured as expected, but that has shed some light, and I have found what was happening. I am using Ubuntu, and has the path configured through .bashrc, it looks like vscode configure the environment with .bash_profile, we just need to configure the path in there.

Many thanks!

**Comment by joaomoreno** [comment]
@angel-aam Thanks for your insights.

Also, try updating to the latest VS Code version.

**Comment by dbaeumer** [comment]
OK. Great to hear.  @davidmcl are you still experience the problem?

**Comment by tiansivive** [comment]
I was also experiencing this issue and just updated to the new version. Problem is still there, PATH not loading correctly.

**Comment by dbaeumer** [comment]
@tiansivive do you have the path in the right profile script. See comment https://github.com/Microsoft/vscode/issues/6534#issuecomment-237522618

**Comment by tiansivive** [comment]
@dbaeumer Yes, I configured the PATH in .bash_profile. By the way, I use zsh and launching from terminal works , which is what I ended up doing...

**Comment by dbaeumer** [comment]
@tiansivive when started from the Desktop (not terminal) can you do the following:

- F1 > Toggle Dev Tools
- in the console could you check if the process.env.PATH contains your custom global npm bin folder which contains the gulp script.

**Comment by tiansivive** [comment]
@dbaeumer it doesn't. It has my .rvm folder for gems but not my .nvm folder for npm modules.

I checked my profile files and the .zshrc exports both rvm and nvm, which gets picked up by VScode when I run it in the terminal. .bashrc exports rvm and .bash_profile adds everything from .bashrc and adds npm to it.
I thought vscode might be picking up on .bashrc so I added the nvm there but still nothing :/

**Comment by dbaeumer** [comment]
@joaomoreno can you check this comment pls: https://github.com/Microsoft/vscode/issues/6534#issuecomment-242703168 @tiansivive is using zsh and it looks like his environment isn't sourced into VSCode.

**Comment by joaomoreno** [comment]
@tiansivive Which version are you on? Did you try on the [latest Insiders release](https://code.visualstudio.com/insiders)?

**Comment by tiansivive** [comment]
@joaomoreno v1.4, I'm using ArchLinux so I'm always on the latest version.

I'll try with the insiders release as soon as possible.

**Comment by joaomoreno** [comment]
@tiansivive @davidmcl @angel-aam Is this still an issue on the latest version?

**Comment by kylecordes** [comment]
I think this is related to #1771 and ultimately has the same answer: that  Code would ideally not look for a global install at all, but use the project local install of the build tool (Gulp) sitting right there, locked and specified at the correct version for this particular project. Not all of us have the luxury or practice of ensuring that every project we must touch work with the same global install of something like a build tool. I don't know that this problem comes up specifically with Gulp, but I also don't see any reason that Code would demand a global install that it can find, regardless.

**Comment by joaomoreno** [comment]
This is related to the user env issues. Fixed long ago.
