### ISSUE TITLE
'Copy All' in the search view adds extra CR chars to the copied text.

### ISSUE THREAD

**Issue by inok6743** [microsoft/vscode#65348]
Issue Type: <b>Bug</b>

1. Grep something in the search view, right-click and select 'Copy All'.
2. Create a new file in VS Code and paste the text.
3. You will see extra blank lines.

I found that:
- It doesn't always happen.
- The text in the clipboard has extra CR (0x0D) chars.  

![clipboard](https://user-images.githubusercontent.com/33479253/50201427-66be3100-039d-11e9-8ee1-96289902ebda.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.25GB (0.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Can you give an example of a search result where this happened? I haven't seen it. Was it a multiline search and are you sure those characters don't exist in the document?

**Comment by inok6743** [comment]
For instance, it happend when I searched the source code of FreeImage. (http://downloads.sourceforge.net/freeimage/FreeImage3180.zip)

I see extra blank lines like these:
![blanklines](https://user-images.githubusercontent.com/33479253/50266801-68a0f680-0468-11e9-9efe-a013a43de2a1.PNG)

And I couldn't find extra characters in the files.

**Comment by roblourens** [comment]
Is definitely related to the line ending of the files, but I have no clue.
