### ISSUE TITLE
函数跳转

### ISSUE THREAD

**Issue by chenkunhc** [Microsoft/vscode#65353]
Issue Type: <b>Bug</b>

java工程，函数跳转失败

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.5
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1

</details>

**Comment by alexandrudima** [comment]
Can you please create an issue directly against https://github.com/redhat-developer/vscode-java
