### ISSUE TITLE
Allow extensions to assign Ctrl+K V as their key binding

### ISSUE THREAD

**Issue by tats-u** [microsoft/vscode#65350]
- VSCode Version: 1.30.1
- OS Version: Windows 10 Pro 1809 177763.134 / Ubuntu 18.04 x64 4.15.0-42-generic

Steps to Reproduce:

1. Install `shd101wyy.markdown-preview-enhanced` & `joaompinto.asciidoctor-vscode`
2.  Set the color theme to dark one
3. Create markdown or asciidoc documents
4. Press Ctrl+K V to try to show preview

Does this issue occur when all extensions are disabled?: No

Both of the installed extensions assign Ctrl+K V to showing the preview of documents with them.
However, the default Markdown viewer instead of that of `shd101wyy.markdown-preview-enhanced` appears when a Markdown document is open and  Ctrl+K V is pressed, and the warning “command 'markdown.extension.togglePreviewToSide' not found” appears or nothing happens when asciidoc is opened.

https://github.com/shd101wyy/vscode-markdown-preview-enhanced/blob/4eba9c1940e42c48caa27a8d0681289779b440c1/package.json#L107-L112
https://github.com/asciidoctor/asciidoctor-vscode/blob/cec8ad578b26d553c86a99de668bd318a14bc98b/package.json#L221-L226

**Comment by alexandrudima** [comment]
@tats-u can you please check the contents of your `keybindings.json`, do you have anything relevant to these commands in there?

**Comment by tats-u** [comment]
@alexandrudima Not at all.  It's just an empty array.

```json
// Place your key bindings in this file to override the defaults
[
]
```

**Comment by alexandrudima** [comment]
@tats-u Do you still have this problem? 

I think the built-in markdown extension keybinding was restricted to markdown files via https://github.com/microsoft/vscode/commit/07645a664feb2912620e727d7d2ab0182d6e99f4 so this might have been fixed in the meantime.

**Comment by tats-u** [comment]
- `shd101wyy.markdown-preview-enhanced` is still taken over by the default Markdown viewer.
- Any Markdown viewers don't appear in AsciiDoc mode by pressing `Ctrl+K V` or `Ctrl + Shift + V`, but no viewers including AsciiDoc one appears.

Please reopen this issue.

**Comment by tats-u** [comment]
@alexandrudima

**Comment by tats-u** [comment]
OS: Win 10 Pro 18362.10022
Code: 1.38.1

**Comment by alexandrudima** [comment]
@tats-u I cannot reproduce. I have done the following:
- installed `shd101wyy.markdown-preview-enhanced`
- installed `joaompinto.asciidoctor-vscode`
- open a `simple.adoc` file
- press `ctrl+k v`
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66458431-0f479980-ea73-11e9-97f3-00c547e4adc5.gif)

Here are the keybinding rules for me for `ctrl+k v`, sorted by precedence:
![image](https://user-images.githubusercontent.com/5047891/66458510-3e5e0b00-ea73-11e9-8153-6eeb1872d0f3.png)

**Comment by tats-u** [comment]
Thank you for reopening.
I wonder what is bad with my VSCode.
Could you tell what is your OS?
And could you tell me what did you use for these screenshots?

**Comment by alexandrudima** [comment]
@tats-u I am using Windows 10. I take screenshots using "Snipping Tool" (available in Windows). Can you please search for `"ctrl+k v"` as I did in the keybindings?

**Comment by tats-u** [comment]
What I'd like to ask you is a tool to create GIF animations.
Here are my key bindings.

![image](https://user-images.githubusercontent.com/12870451/66480920-a6940780-eada-11e9-82c2-869cdd080376.png)

**Comment by alexandrudima** [comment]
@tats-u You have one extra keybinding for `Ctrl+K V` than me. Namely, the one at the bottom:

![image](https://user-images.githubusercontent.com/5047891/66493436-5b67fd80-eab6-11e9-8dd4-1b7198765850.png)

The source is marked as "Default" so you must have some more extensions installed and one is contributing this keybinding, besides the keybindings coming in from `shd101wyy.markdown-preview-enhanced`, `joaompinto.asciidoctor-vscode` or from out-of-the-box VS Code. 

You can click on each extension you have installed and go to the "Contributions" tab and figure out which one it is.

![image](https://user-images.githubusercontent.com/5047891/66493724-d6311880-eab6-11e9-89cf-dc3c47852e0b.png)

I use LICEcap for gifs on Windows.

**Comment by tats-u** [comment]
I found the criminal.  It's https://github.com/yzhang-gh/vscode-markdown.
