### ISSUE TITLE
Search: Missing SVG breaks build

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#65355]
I had to comment out this CSS snippet:

https://github.com/Microsoft/vscode/commit/f071a3ecef1f0af6a74314f8c4cb452d32c27c7d

**Comment by joaomoreno** [comment]
I had to really remove it, as it appears it was still breaking even as a comment... we might be doing some regexp magic over here, right @alexandrudima? https://github.com/Microsoft/vscode/commit/d315b31c6b5cdca082b0a6e193306e4001586509

**Comment by alexandrudima** [comment]
Yes, inlining the images inside CSS is done with a simple regex, not with a correct CSS parser.

**Comment by roblourens** [comment]
Looks like I had a bad merge with https://github.com/Microsoft/vscode/commit/3d675f817022a6883bf76ac1b11a9e3a6ed79afa#diff-eb02bbc46fcaa61fd28d73e573b05bcd. Thanks for fixing it!
