### ISSUE TITLE
Debug's error

### ISSUE THREAD

**Issue by projectAPCS** [Microsoft/vscode#65356]
Issue Type: <b>Bug</b>

when I tried to debug my C++ program, the program always suspend and throw the message "Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object". This error was disappeared when I tried using the previous version of visual studio code (the October 2018 version).
I run vscode on Ubuntu 18.04.1 LTS

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.69GB (3.10GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1

</details>

**Comment by alexandrudima** [comment]
@projectAPCS Can you please create an issue directly at https://github.com/Microsoft/vscode-cpptools ?
