### ISSUE TITLE
Very slow and many memory consuming Code Helpers

### ISSUE THREAD

**Issue by CapitanFuture** [Microsoft/vscode#65354]
Issue Type: <b>Bug</b>

A simple react c# template and running nodejs while editing the code

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.5
csharp|ms-|1.17.1
vscode-lldb|vad|1.1.2
vscode-swift-development-environment|vkn|2.6.0

</details>

[2-TypeScript.log](https://github.com/Microsoft/vscode/files/2693708/2-TypeScript.log)
[exthost.log](https://github.com/Microsoft/vscode/files/2693711/exthost.log)

**Comment by CapitanFuture** [comment]
[exthost.log](https://github.com/Microsoft/vscode/files/2693713/exthost.log)
[2-TypeScript.log](https://github.com/Microsoft/vscode/files/2693714/2-TypeScript.log)

**Comment by CapitanFuture** [comment]
Here is my launch.json 
`"version": "0.2.0",
   "configurations": [

        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/ui.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ,]`

and this is my tasks.json  both are standard I think so. 
` "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/ui.csproj"
            ],
            "problemMatcher": "$msCompile"
        }
    ]`

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by Skullnick** [comment]
Reverted back to 1.29 in the meantime.. But here's the link to a default react project with asp net core if you want to check the problem:
[https://docs.microsoft.com/fr-fr/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=netcore-cli](url)

**Comment by CapitanFuture** [comment]
Ok I go back to version 1.29 as you suggested and all is okay. So it's must be a bug somewhere in VSCode with debugging and development a react (npm) project. Hopefully it's fixed in the 1.31 version, we'll see ;)

**Comment by NoahStahl** [comment]
Same performance issues here with 1.30 release. In my case a Vue project from vue-cli and aspnet core hosted webpack dev server, everything up to date. Reverting to 1.29 restored expected performance, so something changed with latest release. Performance degrades while debugging, restarting the debug temporarily restores, then degrade again.

**Comment by mjbvz** [comment]
@NoahStahl and @Skullnick Please open separate issues

@CapitanFuture  Did you run try collecting performance information by following [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues)?
