### ISSUE TITLE
VisualStudioCode is removed from the system after failing update

### ISSUE THREAD

**Issue by euij** [Microsoft/vscode#65357]
- VSCode Version: I can't tell anymore because VSCode is removed
- OS Version: Windows 10

Steps to Reproduce:

1. Use VSCode.
2. I closed VSCode, then VSCode automatically started updating (There was no prompt for update, it just started without my approval). While it was trying to update, it poped up an error box with the message saying that a folder named 'bin' is being used by some processes, and so it asked me to close any existing 'VSCode' instances. I don't remember the exact path for the 'bin' folder, but it was essentially the VSCode's installation path (or something related to VSCode). The error box had two options, Retry and Cancel. I hit Retry first, but it failed again with the same error. (There was no VSCode instances open by the way) Then I hit cancel, because I had no other options and I can always update again. But after hitting the cancel, I realized that VSCode was removed from my system.

Just to be clear, I am NOT filing this bug for the failure of the update. I'm filing the bug for the fact that the update caused VSCode to be removed from the system. It's especially frustrating when I didn't even trigger the update. As far as I am concerned, VSCode basically removed itself after I closed an instance.

**Comment by joaomoreno** [comment]
Please disable background updates with `"update.enableWindowsBackgroundUpdates": false`.
