### ISSUE TITLE
Test: Editor stacks

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6536]
**Note** for endgame master: this test plan item is rather large.

- [x] Win - **@stevencl** 
- [x] OS X - **@jrieken**
- [x] Linux - **@joaomoreno**

Special build download links:
- [Windows](https://az764295.vo.msecnd.net/alpha/0328617088e0e54142521de50ed8c70836b79539/VSCodeSetup-alpha.exe)
- [OS X](https://az764295.vo.msecnd.net/alpha/0328617088e0e54142521de50ed8c70836b79539/VSCode-darwin-alpha.zip)
- [Linux](https://az764295.vo.msecnd.net/alpha/0328617088e0e54142521de50ed8c70836b79539/vscode-amd64.deb)

To prepare for enabling tabs we have introduced **editor stacks** in the workbench. Editor stacks surface in two areas of the user interface: the newly introduced **Opened Editors** view in the explorer (replaces **Working Files**) and generally in the **editor area** to the right. We still support a maximum of 3 editor groups, each having their own stack of editors that were opened.

**Note**: please test with auto save turned off!

**Pro**: you can bind `_workbench.printStacksModel` to a key to print the stacks model as plain text to console. you can bind `_workbench.validateStacksModel` to quickly check if the stacks model is in bad shape. This is helpful when filing a bug when you notice stale state between the stacks model and the UI.

**Verify:**

* each editor group has a **stack of editors** attached to it
    * the stack grows when you open editors and pin them (italics indicates preview state)
    * you can pin editors e.g. by changing contents in the file 
    * closing an editor reveals the previous editor you looked at (MRU order)
    * you can see a list of editors in the stack from the overflow action (double arrow down icon)
    * you can work with the group from the overflow dropdown menu ("..." icon)
    * you can still move groups around to reorder them
    * you can use `Ctrl+Tab` to navigate tabs in MRU order
    * you can use `CtrlCmd+Alt+Tab` to navigate all editors in spatial order
    * you can use <kbd>CtrlCmd Shift T</kbd> to reopen a closed (pinned) editor
    * normal quick open history works as before and shows you a linear history of editors opened even after you closed editors
* the **opened editors** view always reflects the state of stacks in the editor area
    * if you have more than one group, you will see the list separated by groups
    * actions in the context menu on groups and editors make sense
    * you can DND editors between groups, within groups and from the explorer
    * you can configure the maximum number of visible entries and the dynamic sizing in settings
    * you can hide the view completely via settings (`explorer.openEditors.visible`)
* in **general**
    * you see dirty indicators when changing files (or untitled) and get prompted to save on close (including closing all editors or an entire group)
    * all UI state is preserved and restored on restart
    * opened editors view and editors in general t react to file changes (delete, move, etc.)
    * you can still drag and drop multiple files into Code to open them
    * you can still open multiple files when starting from command line

Be **creative** and try to break the editor stacks model by doing some crazy stuff
    * please keep the steps in mind that lead you to breakage if possible when filing issue

**Comment by bpasero** [comment]
@stevencl @jrieken @joaomoreno sorry, it should be Ctrl+Tab on Mac not Cmd+Tab for navigating in MRU order. I guess you figured that out already.

**Comment by bpasero** [comment]
Thanks for the feedback!
