### ISSUE TITLE
incompatible OpenSSL version on Fedora 29

### ISSUE THREAD

**Issue by blazewicz** [Microsoft/vscode#65365]
## Environment
- VSCode Version: 1.30.0 (installed from official MS repo)
- OS Version: Fedora Workstation 29

## Problem
OpenSSL version shipped with Fedora 29 seems to be incompatible with what VSCode expects.

Error I've got while trying to install Python Language Server:

```
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.1.72.nupkg... complete.
Unpacking archive... done.
No usable version of the libssl was found
[Info  - 10:14:55] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Info  - 10:14:58] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Info  - 10:15:00] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Info  - 10:15:02] Connection to server got closed. Server will restart.
No usable version of the libssl was found
[Error - 10:15:04] Connection to server got closed. Server will not be restarted.
```

## Workaround
 I found [similar issue on Live-Share repo](https://github.com/MicrosoftDocs/live-share/issues/1385), workaround found there was to install compat lib:

```
sudo dnf install compat-openssl10
```

It solves the problem with VSCode as well.

## Possible solution
Add `compat-openssl10` to dependencies list, or upgrade openssl version used by VSCode.

**Comment by Tyriar** [comment]
Well code runs, this issue belongs in the python extension repo imo https://github.com/Microsoft/vscode-python
