### ISSUE TITLE
Add an optional color setting for each tasks that would change the statusBar bg when executing.

### ISSUE THREAD

**Issue by deepnight** [microsoft/vscode#65362]
Add an optional color setting similar to ``"workbench.colorCustomizations" -> "statusBar.debuggingBackground"`` for each task in ``tasks.json`` to change status bar background color during the execution of a specific task.

``tasks.json`` example:

```
        {
            "label": "Some foo task",
            "type": "shell",
            "command": "haxe --connect 6001 -debug deadCells2_hl.hxml",
            "presentation": {
                "statusBarBackground": "#9f4b03",
                "reveal": "never",
                "clear": true
            },
            "problemMatcher": "$haxe",
        },
```

![image](https://user-images.githubusercontent.com/1671695/50209897-21860900-0375-11e9-9752-acd26c4cd47e.png)

**Comment by alexr00** [comment]
This is could be a good extension. You could listen for `tasks.onDidStartTask` and then change the color based on some extension defined setting.
