### ISSUE TITLE
Allow to implement IKeyboardNavigationLabelProvider on view elements instead of model elements 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#65367]
I have pushed https://github.com/Microsoft/vscode/commit/2d71824f804a31317bbdd57d991bc434507a450f to support type to navigate in the peek references tree. However, since my tree is partially async I cannot provide a good label for the individual references. IMO it would prefer to work with my rendered item instead of my model item

**Comment by joaomoreno** [comment]
I see.

Can I convince you to fetch the file's contents on the `getChildren` call instead of at render time?

**Comment by jrieken** [comment]
> Can I convince you to fetch the file's contents on the getChildren call instead of at render time?

Ops - I actually do... Feel free to close.
