### ISSUE TITLE
Improve tree/list keyboard type navigation

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#65368]
* have a tree with `IKeyboardNavigationLabelProvider`
* type a character that isn't a prefix on any label
* 😢 nothing happens because `matchesPrefix` is used. it would be better to be more relaxed here

**Comment by joaomoreno** [comment]
Let's just drop `IKeyboardNavigationLabelProvider` and replace that with a features which does the same as Outline when `Filter on Type` is disabled.

**Comment by jrieken** [comment]
:clap:

**Comment by joaomoreno** [comment]
Done!
