### ISSUE TITLE
Align Markdown in-editor syntax and Markdown Preview

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#65374]
- VSCode Version: 1.30
- OS Version: Win10 17134.471

Steps to Reproduce:

1. Combine any two styles in Markdown: example a `raw inline text` and a [link](example.com) like
    [`raw inline text link`](example.com)

2. Only one format is chosen, in fact, the TMScopes will only show one:

![image](https://user-images.githubusercontent.com/5379325/50216302-0d023a80-038e-11e9-9468-88ee01ad5c2a.png)

I know this happens at a minimum with backticked titles and backticked links.

In the preview however they are rendered combined
![image](https://user-images.githubusercontent.com/5379325/50216472-8bf77300-038e-11e9-96ea-7f0073c0c576.png)

**Comment by mjbvz** [comment]
I believe this is tracked upstream by https://github.com/Microsoft/vscode-markdown-tm-grammar/issues/11
