### ISSUE TITLE
Whenever "Error: The npm task detection..." occurs it steals focus by changing tabs

### ISSUE THREAD

**Issue by joma74** [Microsoft/vscode#65371]
- VSCode Version: 1.30.1-1545156774
- OS Version: Ubuntu 16.04.5 LTS

Steps to Reproduce:

1. Have a task in tasks.json which does not correspond to a current package.json script
2. Whenever vscode's internal task detection runs and outputs "Error: The npm task detection..." , it steals focus of the current tab e.g. from "TERMINAL"

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Already fixed in insiders with https://github.com/Microsoft/vscode/issues/64900
