### ISSUE TITLE
Cannot change display local

### ISSUE THREAD

**Issue by Xarkam** [microsoft/vscode#65378]
I changed local to "fr" into locale.json but after restart vscode, local is always "en".
(locale.json is located into %USERPROFILE%\AppData\Roaming\Code\User)

- VSCode Version: 1.30.1
- OS Version: Windows 10:1809
- My vscode is installed on disk d into D:\Microsoft VS Code

Steps to Reproduce:

1. Change local in other language than en
2. Restart vscode

Does this issue occur when all extensions are disabled?: Yes

**Comment by Xarkam** [comment]
Hello,
I'va check today on my linux and it's same as windows.

And I've found the solution. It's because I don't have french language pack for vscode.

I think we should offer to download the extension that corresponds to the language when it is changed.

**Comment by dbaeumer** [comment]
Agree.

**Comment by bpasero** [comment]
I think we can close this, we no longer show the file to the user, rather we have a picker now:

![image](https://user-images.githubusercontent.com/900690/66497650-14c9d180-eabd-11e9-84d0-3679aa52e66e.png)
