### ISSUE TITLE
VS Code Insiders intellisense is too slow

### ISSUE THREAD

**Issue by PavlinGanchev** [Microsoft/vscode#65379]
Issue Type: <b>Bug</b>

Hi guys , in VS Code Insiders intellisense is too slow. 
Open .ts file and type word log for a console.log, for example. CPU consummation of the editor is near 40% until suggestion box popup. 

VS Code version: Code - Insiders 1.31.0-insider (2018-12-19)
OS version: Windows_NT x64 10.0.16299

|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|Memory (System)|15.89GB (5.95GB free)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
