### ISSUE TITLE
Go to Definition feature does not  work  for c++

### ISSUE THREAD

**Issue by dk1301** [Microsoft/vscode#65386]
- VSCode Version: 1.30.1
- OS Version: Ubuntu 16.04 amd64

Steps to Reproduce:

1. Just right click a method and press go to definition it always leads to declaration

Does this issue occur when all extensions are disabled?: Yes

I have asked a revevant question in stackoverflow for 1.29.1 (https://stackoverflow.com/questions/53779636/neither-go-to-definition-nor-peek-definition-features-work-in-vscode-1-29-1-for) but I got no answer. As I mentioned there in version 1.29.1 some times it works only for a couple of times after shutting down and repoening the vscode and afterwards the same faulty behavior, but for version 1.30.1 the go to definition never worked.

The c_cpp_properties.json file I use is the following:
 ```
  {
    "configurations": [
        {
            "name": "Linux",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "includePath": [
                "${workspaceFolder}/include"

            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
   }
```

**Comment by alexandrudima** [comment]
Can you please create an issue directly against the extension at https://github.com/Microsoft/vscode-cpptools ?

**Comment by dk1301** [comment]
Ok I will. I didn't know there was a cpp related link.

**Comment by singcl** [comment]
Version: 1.31.0-insider (user setup)
Commit: e02e44464c02d617b98d0a3265bf5efef7794436
Date: 2018-12-21T06:20:35.852Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

-------
Go to Definition feature  does not work either.
