### ISSUE TITLE
PerfTips on Debug

### ISSUE THREAD

**Issue by killerall** [microsoft/vscode#65384]
Hello,
Is in the roadmap the ability to display diagnostic information, when we are debugging, in the source code?
I'd like to show the elapsed time in the current debug line.

Similar to PerfTips:
![image](https://user-images.githubusercontent.com/4764609/50218826-68bfca00-0374-11e9-8651-7697d36d9816.png)

https://docs.microsoft.com/en-us/visualstudio/profiling/perftips?view=vs-2017

**Comment by isidorn** [comment]
This is not currently on the plan.
Leaving open as a feature request

**Comment by turowicz** [comment]
👍 definitely needed

are there any extensions that do that?

**Comment by turowicz** [comment]
Or perhaps you're worried about VS sales.
