### ISSUE TITLE
Support file problem markers in tasks.json

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6538]
- VSCode Version: 1.1.1

Currently problem can only reported on [file, location]. However for test frameworks it would be nice to report a problem on the file since typically no location information is available. To support this the problem matcher should provide a kind property which support "file" and "location". See also https://github.com/Microsoft/vscode/pull/5416

**Comment by alexr00** [comment]
@dbaeumer, can this one be closed?

**Comment by dbaeumer** [comment]
@alexr00 yes! Thanks for reminding.
