### ISSUE TITLE
deleted from disk.....

### ISSUE THREAD

**Issue by mymem0** [Microsoft/vscode#65387]
Issue Type: <b>Bug</b>

when I open an file from winscp(ftp) sometimes vs code is saying deleted from disk. but with notepad++ not like this something happening.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.99GB free)|
|Process Argv|C:\Users\MyMeMo\AppData\Local\Temp\scp12521\public_html\inc\pages\profile.php|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.10
vscode-apache|mrm|1.1.1

</details>

**Comment by bpasero** [comment]
@mymem0 how does your setup look like for opening remote resources? is it through an extension?

**Comment by mymem0** [comment]
https://winscp.net/eng/download.php I am using it.

**Comment by bpasero** [comment]
@mymem0 yeah so I assume from that tool you right click to open with editor rigth?
