### ISSUE TITLE
Side bar icons view needs a scoll

### ISSUE THREAD

**Issue by barakimam** [Microsoft/vscode#65385]
Issue Type: <b>Feature Request</b>

The side sidebar icons view that contaions icons like `file, git, extensions` and the likes is currently overflowing the view.
Maybe you should add a scrol.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 17.7.0

**Comment by sandy081** [comment]
@barakimam They are moved into `...` menu if they overflow. Please check if they are.

**Comment by barakimam** [comment]
They are not. I will upload screenshots tomorrow.

**Comment by sandy081** [comment]
SUre

**Comment by barakimam** [comment]
<img width="908" alt="screen shot 2019-01-02 at 1 34 23 pm" src="https://user-images.githubusercontent.com/44836329/50592195-5f198480-0e93-11e9-9b52-9b39e818fdba.png">
@sandy081 this is the screenshot when it is not maximised on macOS

<img width="1440" alt="screen shot 2019-01-02 at 1 37 52 pm" src="https://user-images.githubusercontent.com/44836329/50592260-abfd5b00-0e93-11e9-9f23-b675174d5b81.png">
This is the screenshot when it is maximized.

**Comment by sandy081** [comment]
@barakimam Can I have the list of extensions you have installed?

**Comment by barakimam** [comment]
I have quite a lot, here is a link to the list
https://gist.github.com/codeprefect/723e92a5cda1b0ad7130b14c4290b198#file-extensions-json

**Comment by barakimam** [comment]
This issue has been fixed in v1.31.0.
The version introduces an ellipsis `...` which onclick unfolds the remaining extensions.
You may now close this issue.
cc: @sandy081
