### ISSUE TITLE
"editor.fontFamily" different behavior / broken font

### ISSUE THREAD

**Issue by Akuukis** [microsoft/vscode#65389]
In new VSCode there's unreported breaking change for fontFamily config value. Workaround: Write in settings `"'Monospace'"` instead of `"Monospace"`. This fixes except for hover text.

New:
![new](https://user-images.githubusercontent.com/7459419/50220253-830c9e80-039a-11e9-8464-9a113553a969.png)
Old:
![old](https://user-images.githubusercontent.com/7459419/50220254-830c9e80-039a-11e9-8546-8d5af9e58f7d.png)
I don't know if there's something broken with current font or that's just another font. 

----
- VSCode Version: 1.30.1
- OS Version: Linux x64 4.19.0-rc4-amd64

Steps to Reproduce:
1. Have in settings `"editor.fontFamily": "Monospace",`
2. observe new font in 1.30.1
3. Revert to older VSCode (e.g. 1.29.1) and observe old font.

Does this issue occur when all extensions are disabled? Yes

**Comment by alexandrudima** [comment]
@Tyriar @joaomoreno I remember you mentioning something about fonts and the snap package.

**Comment by joaomoreno** [comment]
@Akuukis Are you using the snap package?

**Comment by joaomoreno** [comment]
@alexandrudima I don't think this is related to snap at all.

I can reproduce the fact that `Monospace` and `'Monospace'` produce different results.

This can just be related to the default system configured monospace font...

**Comment by Akuukis** [comment]
@joaomoreno No, I use `apt-get install code`.

So there just has been a change how the config value is parsed? It worked without quotes before 1.30. 
Would be nice to see some popup as "invalid font name" or "font not found", because it just silently fails now.

**Comment by Tyriar** [comment]
> Workaround: Write in settings "'Monospace'" instead of "Monospace". This fixes except for hover text.

I thought this difference was always a thing?

**Comment by joaomoreno** [comment]
Hover font: https://github.com/Microsoft/vscode/issues/65339
