### ISSUE TITLE
Allow for a Breakpoint to be Enabled when breakpoints are deactivated

### ISSUE THREAD

**Issue by JohanssonDaniel** [microsoft/vscode#65394]
- VSCode Version: 1.31.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create a breakpoint
2. Deactivate all breakpoints in the debug view
3. Try to enable one breakpoint
4. The context menu shows Disable Breakpoint
5. Clicking this option correctly switches it to Enable Breakpoint. However, since breakpoints are deactivated, the breakpoint is still not used.

![](https://i.imgur.com/yohzEmt.gif)

Expected Behavior

The context menu shows Enable Breakpoint which would allow for a quick way to disable all breakpoints except one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JohanssonDaniel** [comment]
I have been looking to try to solve this myself, however, the main problem seems to be that the debug view deactivates all breakpoints instead of disabling them. If I could continue to work on this, I think I need to know more about the main reason as to why both deactivating and disabling is used.

**Comment by isidorn** [comment]
Leaving this open as a feature request for now.
Not convinced we need it.
I would prefer that enabling any breakpoint activates all breakpoints, and as that I would treat this as a bug.
Chrome dev tools behaves just like that for example
