### ISSUE TITLE
List selection toggles last selected item unnecesserily

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#65397]
1. Hold down shift and press down until you select all your elements
2. Press shit + down one more time.
3. Nothing should happen - however the last element's selection is toggled

![list](https://user-images.githubusercontent.com/1926584/50226951-dd126180-03a4-11e9-92ba-b7b0eb75d467.gif)

**Comment by itamark** [comment]
@joaomoreno can I take this?

**Comment by joaomoreno** [comment]
@itamark Please check for `help wanted` and `good first issue` issues.

**Comment by isidorn** [comment]
@joaomoreno Now the selection cycles through. So if I select the bottom element and do shit + down, the first element gets selected.
I personally find this behavior strange since no other explorer does this imho.

**Comment by isidorn** [comment]
Works fine with latest -> verified

**Comment by joaomoreno** [comment]
![yeah boii](https://media.giphy.com/media/2RF2GfrnbPdXa/giphy.gif)
