### ISSUE TITLE
Webview doesn't respect smooth scrolling

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#65398]
```json
"editor.smoothScrolling": false,
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
This was discussed previously in #39745

**Comment by mjbvz** [comment]
Added with a `disable-smooth-scrolling` in  #65422
