### ISSUE TITLE
Tree: Support single node refresh

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#65393]
This can replace `AbstractTreeRenderer`.

**Comment by joaomoreno** [comment]
cc @sandy081 for problems panel

**Comment by joaomoreno** [comment]
Pinging all tree users @isidorn @jrieken @roblourens @bpasero @sandy081 

I've introduced a new tree API which lets you simply refresh a single element, including updating its height if there are any height changes. This is a new API which doesn't modify the tree model at all but, at most, simply re-renders a single tree element. This API came up in several use cases, including @isidorn's rename feature in several trees, @jrieken's breadcrumbs, @sandy081's marker panel, etc.

After discussing with @sandy081 and @isidorn, I've decided to call this API `refresh`. Consequentially, I had to rename the current `refresh` call and decided to name it `updateChildren`. I've refactored all code in `master` accordingly. Sorry for the hassle in other branches and for renaming such a well known operation.

The current API now is:

```ts
// tree model modification calls
updateChildren(): Promise; // for (async) data tree
setChildren(); // for object tree
splice(): // for index tree

// tree view re-render call
refresh(element); // for all trees
```

**Comment by bpasero** [comment]
We are getting closer to the good old Eclipse JFace tree :)

**Comment by isidorn** [comment]
Also fyi @weinand

**Comment by isidorn** [comment]
Works fine, I am using it in the explorer -> verified
