### ISSUE TITLE
Introduce extension API for debug mode 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#65390]
As made painfully obvious in #63832 we need robust extension API for figuring out whether an extension host (or one or more extensions) are being debugged.

**Comment by jrieken** [comment]
Something like `vscode.env.debugInfo`? Would information should be in there? That fact that debug mode is on, also the port et al? The things is technically we always run in debug/inspect mode even when you don't run in extension-development mode

**Comment by jrieken** [comment]
>  I'm never quite clear what goes where and why....

`vscode.env` shared environment information about the editor, `ExtensionContext` information "private" for one extension. 

> One thought I had is whether we want to distinguish general debuggability of the EH (and all contained extensions) from a single extension that is debugged in extension-development mode.

That would mean an enum, right? E.g. `DebugMode.None`, `DebugMode.All`, `DebugMode.Extensions`?

**Comment by weinand** [comment]
Since debugging an extension in extension-development mode always requires general debuggability of the EH, I don't think that an enum is a good way to express this. 

Instead we could use `vscode.env.debugInfo` to express general debuggability of the EH, and a `developmentMode` on the `ExtensionContext` to express that this extension is under development.

With this a language extension could only run its own language server in debug mode with this check: `if (vscode.env.debugInfo.debug && extensioonContext.developmentMode) {...`
