### ISSUE TITLE
Pressing Ctrl+P shows Error

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [Microsoft/vscode#65395]
Related to #60960, excpect I encountered the bug in 1.28.2, not 1.28.1. 

When I try to use CTRL+P the following error occurs:
```
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
Reload
```

The developer console does not show any errors, just these two warnings:

```
dom.ts:208 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

This error only occurs in one specific project. In all other projects CTRL+P works normally. I could not find out why only that one project is affected.

The original #60960 issue was closed without a resolution and I could not comment there, so I submit a new issue instead.

- VSCode Version: 1.28.2
- OS Version: Windows 10 x64 18.03

Steps to Reproduce:

1. Open vscode version 1.28.2
2. Press CTRL+P on keyboard

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
Please update to at least VS Code 1.30. 1.28 does not have the fix from #60960
