### ISSUE TITLE
Falha grave

### ISSUE THREAD

**Issue by FelipeDecker** [Microsoft/vscode#65391]
eu crio um arquivo usando o angular, e crio as funcionalidades que esse arquivo vai ter, e tem momentos que aparece um erro que eu ja tinha corrigido, por exemplo: copiei um outro arquivo pra colar no meu arquivo novo, de cara ja vai aparecer alguns erros, pq as variaveis não foram chadas, então eu substituo pelas variaveis que vou usar nesse aquivo novo, e depois de corrigir, ainda fica um sublinhado vermelho, e se eu colocar o mouse pra vero erro, ele fala que o problema e na variavel que tava antes, que no caso ela nao existe, pq ja substitui ela, ele permanece com o erro do anterior, e outra coisa é que quando eu aperto f12, pra ver a referencia da variavel, ele buga tudo, eu tenho meu aquivo "releaseNoteNotification", quando aperto f12, ele cria um novo arquivo "releasenotenotification", faz uma copia igual ao do original e depois disso ele não acha mais as referencias do arquivo original.

**Comment by alexandrudima** [comment]
I am sorry, the development language is English. Please create an issue in English with clear reproducible steps.
