### ISSUE TITLE
Turn off Holidays mode for the 'Manage' Button

### ISSUE THREAD

**Issue by jspure** [Microsoft/vscode#65407]
There is no option to turn off Holidays mode for the 'Manage' Button.
This hat is annoying me.
Thank you.

**Comment by secabstraction** [comment]
If I could work my will, every idiot who goes about with ‘Merry Christmas’ on his lips should be boiled with his own pudding and buried with a stake of holly through his heart. He should!

**Comment by lafe** [comment]
Just as a different opinion: I really like the holiday theme and the holiday wishes. In my opinion, it gives the whole product a personal touch.
BTW: It only "affects" the Insider version, so you can always go back to the stable version and experience a "hat free" manage button.

**Comment by joaomoreno** [comment]
Nice try...

![grinch](https://media.giphy.com/media/ExxrZ4CaGqhMc/giphy.gif)

Apart from jumping back to Stable for a couple weeks (not recommended!), there's no other fix than to embrace the holiday spirit! :christmas_tree: Happy Holidays @jspure!
