### ISSUE TITLE
Draging Visual Code is not working

### ISSUE THREAD

**Issue by rajat29gupta** [Microsoft/vscode#65409]
## Versions
 - Visual Studio version: ... 1.30

### Steps to Reproduce
1. Go to 'Visual code'
2. Click on 'Minimise the tab to make it dragable'
3. Scrolling from the box show in the image is not working 

### Screenshots

![restfulapitutorial-password-reset - visual studio code 2018-12-18 13 43 55](https://user-images.githubusercontent.com/34648003/50140579-38702100-02cb-11e9-8e4e-6d0d753b63fa.png)

![usercontroller js - restfulapitutorial-password-reset - visual studio code 2018-12-18 13 35 39](https://user-images.githubusercontent.com/34648003/50140324-5ab56f00-02ca-11e9-8ca8-cbe7d13564dc.png)

**Comment by sbatten** [comment]
fixed in latest insiders
