### ISSUE TITLE
Unable to open a file with right click and "open with"> "Visual Studio Code" in a folder with spaces in the name.

### ISSUE THREAD

**Issue by sandysnunes** [Microsoft/vscode#6540]
- VSCode Version: 1.1.1-1463146452
- OS Version: Ubuntu 16.04 LTS
- Gnome Nautilus  version: 3.14.3

Steps to Reproduce: Inside a folder with spaces in the name (exemple: "my folder"), try to open the file with "right click" > "open with" > "Visual Studio Code". 

1. The original file
![1](https://cloud.githubusercontent.com/assets/677007/15396595/cf264768-1daa-11e6-8c34-57668e30f546.png)

2. Using "Open with"
![my folder_002](https://cloud.githubusercontent.com/assets/677007/15396615/db9d7250-1daa-11e6-8819-29176f801bf9.png)

3. The result with Visual Studio Code.
![my - visual studio code_002](https://cloud.githubusercontent.com/assets/677007/15396637/ee0d4172-1daa-11e6-8497-6cff48993780.png)

If the file was in a folder with name without space, the file would have been opened normally.

**Comment by phra** [comment]
duplicated -> #6525
