### ISSUE TITLE
Random slowdown when editing React code

### ISSUE THREAD

**Issue by jacobweber** [Microsoft/vscode#65414]
Issue Type: <b>Bug</b>

VSCode started taking up a ton of CPU for about a minute, then went back to normal.

I was just doing some basic text editing in a few React JS files; I'm afraid I can't be much more specific.

It didn't show the "Initializing JS/TS Language Features" message like it sometimes does. I tried to open the Process Explorer, but it didn't show any content.

Submitted log file ID 1701461977.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.1.0
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
dart-code|Dar|2.21.1
mustache|daw|1.1.1
vscode-eslint|dba|1.7.2
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
svn-scm|joh|1.46.4
vs-script-commands|mkl|7.0.0
vscode-apache|mrm|1.1.1
python|ms-|2018.12.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1
jinja|who|0.0.8

</details>

**Comment by jacobweber** [comment]
(Is it at all useful to have these kind of reports? I get a lot of random slowdowns, but haven't been able to narrow it down to something specific.)

**Comment by mjbvz** [comment]
When the slowdown occurs, follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of running `code --status` on the command line while the slowdown is still happening

That should help identify what area of VS Code is causing the slowdown
