### ISSUE TITLE
Unable to call Select Default Shell

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#65411]
Issue Type: <b>Bug</b>

I have moved from fish to zsh, but vscode still has $SHELL cached as `/usr/local/bin/fish`. I'd like to not need to keep `"terminal.integrated.shell.osx": "/bin/zsh"` in my `settings.json`, but the `Select Default Shell` command referenced in https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration seems to be missing for me

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
gitlens|eam|9.2.2
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
insert-incrementing-numbers|jac|0.0.1
Angular-BeastCode|Mik|7.0.20
python|ms-|2018.12.1
cpptools|ms-|0.20.1
vsliveshare|ms-|0.3.1071
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
subtle-brackets|raf|3.0.0
vscode-multiclip|sle|0.1.5
code-spell-checker|str|1.6.10
pdf|tom|0.4.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by JacksonKearl** [comment]
@Tyriar

**Comment by Tyriar** [comment]
@JacksonKearl 👋 

Select Default Shell is only exposed on Windows as it's a lot more complicated than on Linux/macOS. You'll want to update your shell launch scripts to set SHELL to zsh instead of fish, that will then be pulled in as the default value for `terminal.integrated.shell.osx`.
