### ISSUE TITLE
Try better webview focus tracking solution in Electron 6+

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#65413]
From #64729

Tracks revisiting how we track focus of webviews. The focus apis are broken in Electron 3 and as a workaround, we use polling to determine when the webview contents have become focused. This is not a good solution and we should revisit it with Electron 4 to see if the focus apis have been fixed

**Comment by bpasero** [comment]
Our `electron-4.0.x` branch is up to date and running with Electron 4.0.1

**Comment by mjbvz** [comment]
Seems the issue is still in 4.0 in my testing. Here's the electron issue currently tracking this: https://github.com/electron/electron/issues/15718. I'll also test in the exploration builds just to confirm it hasn't been fixed yet, so pushing this to July

iframe based webviews do not seem to suffer from this issue

**Comment by bpasero** [comment]
Ok, updating labels.

**Comment by mjbvz** [comment]
I think the best solution here is actually to not use webviews at all if possible. Here's a branch that uses iframes instead: https://github.com/microsoft/vscode/tree/dev/mjbvz/electron-6-iframe-based-webviews

This requires electron 6 so I'm pushing this issue out to August

**Comment by bpasero** [comment]
E6 has landed on `master` but pending regressions we might need to pull it out again before stable is released.
