### ISSUE TITLE
Backslash can't be escaped in snippet variable transforms

### ISSUE THREAD

**Issue by Shifterovich** [Microsoft/vscode#65412]
- VSCode Version: 1.30.0
- OS Version: Linux x64 4.15.0-42-generic

Steps to Reproduce:

Create a snippet like this (for PHP, for example)

```json
"class": {
	"prefix": "class",
	"body": [
		"namespace ${TM_DIRECTORY/[\\/]/foo/g};",
		"",
		"class $TM_FILENAME_BASE",
		"{",
		"",
		"}"
	],
	"description": "New file with a namespace and a class"
}
```

This snippet works correctly, it replaces `/` with `foo`. However, changing `foo` to any amount of `\` doesn't work. `\` doesn't work,  `\\` doesn't work, `\\\` doesn't work, `\\\\` doesn't work, etc.

I'm trying to replace `/` with `\`.

Thanks.

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
@Shifterovich Thanks for filing this. I have pushed a fix. You will need the following escaping dance: `namespace ${TM_DIRECTORY/[\\/]/\\\/g};`, e.g 3 backslashes. One to make JSON happy, then two for the snippet. The first escapes the second so that the second doesn't escape the forwardslash.

**Comment by mjbvz** [comment]
@jrieken I had to use four backslashes:

```json
{
	"class": {
		"prefix": "class",
		"body": [
			"namespace ${TM_DIRECTORY/[\\/]/\\\\/g};",
			"class $TM_FILENAME_BASE",
			"{",
			"",
			"}"
		],
		"description": "New file with a namespace and a class"
	}
}
```

Reopening because I'm not sure that is expected

**Comment by jrieken** [comment]
Funky, works half/half with three and always with four backslashes... Looks like one backslash gets lost somewhere.

**Comment by jrieken** [comment]
@aeschli can you shed some light into this? how does escaping `\` work in JSON? Is one backslash enough to escape a sequence of them or does every backslash need escaping?

**Comment by Shifterovich** [comment]
Every single one should need escaping. If you want your JSON to contain `\` and a newline, you would do `\\\n`. You don't want the first backslash to escape the backslash before the `n`.

**Comment by jrieken** [comment]
Yeah, that makes sense. I have updated my comment above.
