### ISSUE TITLE
Only opens if I run with sudo

### ISSUE THREAD

**Issue by rjrobinson** [Microsoft/vscode#65416]
- VSCode Version: 1.30.1
- OS Version: MacOS 10.14.1

Steps to Reproduce:

1. Click on VSC icon
2. or terminal run `code --verbose`
```shell
[main 3:44:42 PM] Error: EACCES: permission denied, mkdir '/Users/rjrob/Library/Application Support/Code/User/globalStorage'
[main 3:44:42 PM] Lifecycle#kill()
```

Does this issue occur when all extensions are disabled?: Yes

Seems if I run sudo code --verbose it starts up. any way around this?

**Comment by bpasero** [comment]
@rjrobinson you probably ran Code once as admin and now it fails to create files in that storage area. Simply change the permissions of everything in `/Users/rjrob/Library/Application Support/Code` back to your user name should fix it.
