### ISSUE TITLE
Tasks command line should wrap text

### ISSUE THREAD

**Issue by epicfaace** [Microsoft/vscode#65419]
Issue Type: <b>Bug</b>

Run a task, then click on the split terminal button. Then a terminal opens on the right. The text in the tasks pane should wrap. Instead, I see this:

![image](https://user-images.githubusercontent.com/1689183/50251368-adb62180-03b1-11e9-8d62-f20d1e4e06bb.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
cquery|cqu|0.1.10
vscode-eslint|dba|1.7.2
gitlens|eam|9.2.2
tslint|eg2|1.0.42
vscode-import-formatter|hen|0.1.8
vscode-phpfmt|kok|1.0.30
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-cosmosdb|ms-|0.9.1
azure-account|ms-|0.7.0
vscode-typescript-tslint-plugin|ms-|0.2.1
debugger-for-chrome|msj|4.11.1
format-html-in-php|rif|1.3.8
wordpress-snippet|tun|1.1.5

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
