### ISSUE TITLE
Shift + Tab disable the ability to fold/unfold region

### ISSUE THREAD

**Issue by JefferyHus** [Microsoft/vscode#65427]
- VSCode Version: 1.30.1
- OS Version: Windows 10

Steps to Reproduce:

1. Fold a region that is under a block of code.
2. Shift + Tab the code above.
3. Try to unfold

Does this issue occur when all extensions are disabled?: Yes

To unfold I have to wait at least one minute or try fold/unfold another region of code to activate the feature again.

One other thing is that after I changed the indent using SHIFT + TAB, I saved the file then closed it. After opening it again I found that I lost most of my file content.

**Comment by alexandrudima** [comment]
@JefferyHus Could you please do a screen recording or give the exact example, I could not reproduce what you describe. I mean it is bizzare that the entire code folds, but I guess that's now a single folding area, but I can still expand again:

![kapture 2018-12-20 at 9 46 31](https://user-images.githubusercontent.com/5047891/50273895-2cf03780-043c-11e9-81f0-fdddaac71ecb.gif)

**Comment by JefferyHus** [comment]
Ok I will try to upload a screen record this evening.

**Comment by egamma** [comment]
@JefferyHus any updates?

**Comment by JefferyHus** [comment]
Sorry for the delay. After the latest update the issue has been fixed. Thanks lot.
