### ISSUE TITLE
showInputBox() does not place focus back to OUTPUT panel after dismiss

### ISSUE THREAD

**Issue by bvisin** [microsoft/vscode#65425]
- VSCode Version: 1.30.0
- OS Version: macOS 10.14.2 (18C54)

Steps to Reproduce:

1. Write an extension
```
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('hello', () => {
        vscode.window.showInputBox({});
    }));
}
```
2. Launch
3. Put focus on OUTPUT panel
4. Run command `hello` from command palette.
5. Press Esc to dismiss (or enter any text)
6. Observe focus is not placed back to the OUTPUT panel (and if an editor window is open it places it there).

I found https://github.com/Microsoft/vscode/issues/48847 but this is not the same issue.

**Comment by eamodio** [comment]
I would think/expect that `showInputBox()` and `showQuickPick()` should always return focus to where ever it came from.

**Comment by TwitchBronBron** [comment]
Agreed! As another option, VSCode should provide a command for extension developers to focus the output window programmatically. Something like 
```typescript
vscode.commands.executeCommand('workbench.debug.action.focusOutput', 'Name of output window here')
```

**Comment by chrmarti** [comment]
@TwitchBronBron 'workbench.action.focusPanel' might do what you are looking for. (That also opens the panel if it is not shown yet.)
