### ISSUE TITLE
Support for window.showSuccessMessage

### ISSUE THREAD

**Issue by queeniema** [microsoft/vscode#65420]
Issue Type: <b>Feature Request</b>

The API currently supports:
* `showErrorMessage` (red)
* `showInformationMessage` (blue)
* `showWarningMessage` (yellow)

Can `showSuccessMessage` (green) be added as well? Sometimes, `showInformationMessage` isn't the most accurate for a given scenario...

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

**Comment by jrieken** [comment]
> Can showSuccessMessage (green) be added as well

Can you explain your use-case? Why is success something that needs advertising and why isn't it the default?

**Comment by queeniema** [comment]
The extension I'm creating is to support a new language and here is a typical user scenario:

1. User executes a command to build a source file and generate an application bundle file
2. Show info notification: __Building application archive...__
3. Show info notification: __Application archive created, submitting to build service...__
4. Show info notification: __Building application...__
5. Show __success__ notification: __Build succeeded__
6. Show info notification: __Application bundle downloaded to output directory__

In this case, I want to indicate that the build was successful and I feel that an info notification doesn't capture that well. When users see the green success, they'll immediately know that the command was successful.

It would be nice if the success notification didn't disappear either after a certain timeout too.

**Comment by jrieken** [comment]
This sounds like a use-case for `ProgressLocation.Notification` and `vscode.window.withProgress`

**Comment by queeniema** [comment]
Based on the sample [here](https://github.com/Microsoft/vscode-extension-samples/tree/master/progress-sample), it doesn't seem like that supports buttons. It also isn't shown in the notification center (bell icon) after the task is complete. If a user is not actively looking at the progress notification, it's unclear what the results are. So even if `withProgress` was used, I would still want to show a success notification when it completes so that the user could view the notification in the notification center at their convenience.

**Comment by mjxchange** [comment]
showInformationMessage  Why can't we change lines? 
I need to show multiple lines in showInformationMessage  and change lines.
