### ISSUE TITLE
Inconsistent ctrl+key shortcuts in search box

### ISSUE THREAD

**Issue by Kirlac** [Microsoft/vscode#65424]
Issue Type: <b>Bug</b>

Open the search dialog and type something into the box. Attempt to delete the search term with ctrl+backspace - this deletes text from the editor instead of the search box even though the search box has focus. Then use ctrl+Z to undo the code deletion - but this runs the undo on the search box rather than the editor so the last characters get removed from the search term instead of restoring the code which just got deleted

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (4.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|9.2.2
beautify|Hoo|1.4.7
cypher-query-language|jak|1.0.2
python|ms-|2018.12.1
csharp|ms-|1.17.1
sort-lines|Tyr|1.7.0

(6 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@Kirlac I cannot reproduce this. Have you perhaps customized your keybindings and omitted a `when` condition in your `keybindings.json` ? Can you please comment out your `keybindings.json` and check ?

**Comment by Kirlac** [comment]
Ahh you're right! I remapped the default `ctrl+[left|right|backspace|delete]` for sub-word navigation/deletion instead of the full-word navigation as default. I did this through the `Keyboard Shortcuts interface` which doesn't seem to provide any option that I could find to set the `when` condition for a binding - am I missing something here?

I removed these bindings and the default behaviour works as expected - I will try reconfiguring these in the `keybindings.json` and setting the `when` condition [as described in the release notes for this feature](https://code.visualstudio.com/updates/v1_25#_subword-support) and see if that fixes my issue.

Thanks for your help!

**Comment by Kirlac** [comment]
Setting the `when` condition on the keybindings resolves the focus issues. Unfortunately the sub-word navigation doesn't apply to the search input (I was able to find a few issues reporting this - from what I can tell this feature isn't implemented and is fairly low on the roadmap priorities), but I can live with that now that it's no longer deleting my code.

Thanks again - I'm closing this issue
