### ISSUE TITLE
Cannot arrow through signature help after clicking on widget

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#65435]
Issue Type: <b>Bug</b>

**Repo**

1. For a js file:

```js
import * as fs from 'fs';

fs.readFile(
```

1. Trigger signature help on `readFile`
1. Click on signature help widget
1. Now try using arrow up and down to go through signatures

**Bug**
After clicking on the widget, the arrow keys stop going through the signatures

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by mjbvz** [comment]
This is caused by us using `kbExpr: EditorContextKeys.editorTextFocus` on these commands: https://github.com/Microsoft/vscode/blob/8a58c3e7a67a82f9ef2c0f318d67c411eaed6959/src/vs/editor/contrib/parameterHints/parameterHints.ts#L111

@alexandrudima or @jrieken Is there there's better context key we should use here? Or can we omit the context entirely since the `precondition` already restricts when the parameter hints are active?

**Comment by jrieken** [comment]
You would need your own context key expressing that the widget is visible

**Comment by alexandrudima** [comment]
Yes, I suggest introducing `parameterHintsVisible` (which would be true/false depending on the widget state) and using the keybinding condition `editorFocus && parameterHintsVisible`.

`editorFocus` means you are somewhere in the dom node of an editor.

**Comment by mjbvz** [comment]
`editorFocus` seems to be the way to go but clicking on the signature help currently take focus out of the editor entirely. Will keep looking into this

**Comment by mjbvz** [comment]
The context is correct when the signature help widget first appears but it gets lost as soon as I interact with the arrow buttons. `editorFocus` becomes false but the `activeEditor` context remains `"workbench.editors.files.textFileEditor"`

**Comment by alexandrudima** [comment]
@mjbvz You would need to make the widget focusable (tabIndex > 0) and then add keybinding rules for arrow up and arrow down. I think you are observing how browsers work. i.e. what you describe has nothing in particular to do with VS Code.

**Comment by jrieken** [comment]
I can still reproduce when I click onto the text

**Comment by mjbvz** [comment]
Yeah this issue was only for clicking the arrow but clicking on the text should not block arrowing through sig help. Moving to Feb
