### ISSUE TITLE
Cannot read property 'userSettingsLabel' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#65437]
Issue Type: <b>Bug</b>

**repo**
1. Using current development build from master
1. Open keybindings editor
1. Try using select all command (cmd+a) in keybinding search input box

**bug**
I'm seeing these errors in the console:

```
[main 2018-12-20T02:12:26.544Z] [uncaught exception in main]: TypeError: Cannot read property 'userSettingsLabel' of undefined
[main 2018-12-20T02:12:26.544Z] TypeError: Cannot read property 'userSettingsLabel' of undefined
    at click (/Users/matb/projects/vscode/out/vs/platform/menubar/electron-main/menubar.js:494:50)
    at /Users/matb/projects/vscode/out/vs/platform/menubar/electron-main/menubar.js:570:17
    at MenuItem.click (/Users/matb/projects/vscode/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Users/matb/projects/vscode/.build/electron/Code - OSS.app/Contents/Resources/electron.asar/browser/api/menu.js:30:13)
```

VS Code version: code-oss-dev 1.31.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by mjbvz** [comment]
Also effects quick input boxes and git commit message box. Assigning to January

**Comment by alexandrudima** [comment]
Let's track in #65456
