### ISSUE TITLE
systemProxy cannot work when update to 1.30.1

### ISSUE THREAD

**Issue by yongwn** [Microsoft/vscode#65431]
Issue Type: <b>Bug</b>

when I upgrade to 1.30.1 , the check for update function doesn't work because  my network need proxy and authentitaion . I only set the proxy in IE setting, and it works on 1.29.1 with http.systemProxy = on ; but when I upgrade to 1.30.1 ,it can't work; and I set the  username:password@proxy.xx.xxx it still not work

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
vscode-clang|mit|0.2.3
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.21.0-insiders
color-highlight|nau|2.3.0
vscode-gn|npc|1.0.0
indent-rainbow|ode|7.2.4
highlight-words|rsb|0.0.8
code-settings-sync|Sha|3.2.4
guides|spy|0.9.2
code-spell-checker|str|1.6.10
clang-format|xav|1.8.0
vscode-proto3|zxh|0.2.2

(5 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@chrmarti Did something change here?

**Comment by hcwhan** [comment]
in 1.30.0, I set `"http.proxy": "http://XXXX:8080",` ,  it work
after update 1.30.1, It not work

**Comment by chrmarti** [comment]
@yongwn @hcwhan What exactly does not work? The check for updates for VS Code? Is there an error?

**Comment by hcwhan** [comment]
check update show `net::ERR_PROXY_CONNECTION_FAILED`

**Comment by chrmarti** [comment]
@joaomoreno I'm not aware of any changes affecting the update check. Any idea?

@yongwn The setting `"http.systemProxy"` from 1.29 was renamed to `"http.proxySupport"` in 1.30. Usually `"override"` (`"force"` in 1.29) should work best, can you try that on both machines?

**Comment by yongwn** [comment]
@chrmarti  ，  I degrade to 1.29 , and then upgrade to 1.30 . It works without doing anything . With this configuration ,both machines works ok. 
and current configuration is 
    "http.proxySupport": "override",
    "http.proxyStrictSSL": false,
    "http.proxy": "http://username:pwd@xxx.xxx.xxx:8080/",

**Comment by yongwn** [comment]
@hcwhan  you can try degrade and then upgrade . All my machine works OK. I don't know why.

**Comment by snd3r** [comment]
I have the same issue, proxy works only with `--proxy-server=http://proxy.domain.com:3128` argument.

**Comment by chrmarti** [comment]
Thanks @yongwn, closing this issue then.

@snd3r Make sure your OS has a proxy configured when using your domain account. Please open a new issue if this is still a problem.
