### ISSUE TITLE
Cannot open terminal after VS code update

### ISSUE THREAD

**Issue by tvgfinman** [microsoft/vscode#65433]
Issue Type: <b>Bug</b>

Yesterday (19-12-2018) VS code ran an update after closing the program (shortly shown in a window).
Today I seem to have lost my files/file folder somehow (not a big deal, I was just getting started with VS code), but I also wasn't able to open a terminal to run a Python file. See the error below:
**The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)**

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1

</details>

**Comment by Tyriar** [comment]
@tvgfinman are there any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by tvgfinman** [comment]
See below:
[Errors VS Code.docx](https://github.com/Microsoft/vscode/files/2734665/Errors.VS.Code.docx)

**Comment by Tyriar** [comment]
@TylerLeonhardt any idea what the problem could be?

**Comment by Tyriar** [comment]
@TylerLeonhardt that log shows both command and args, so it looks like there are no args and the exe run is what's in the quotes above

**Comment by TylerLeonhardt** [comment]
from a search... it appears that exit code 2 _might_ be that the executable isn't found.

The actual path to Windows PowerShell is:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

Windows is case-insensitive... but the only thing that stands out is that the path in the error has `WINDOWS` in all caps.
