### ISSUE TITLE
Publish new branch from VS Code with name @JA/feature1 with error

### ISSUE THREAD

**Issue by javed74** [microsoft/vscode#65438]
- VSCode Version: 1.30.1
- OS Version: Windows 10 - build 1803

Steps to Reproduce:

1. Create new branch "git checkout -b @JA/feature1"
2. VS Code display branch like below
![image](https://user-images.githubusercontent.com/3745335/50261052-c1c14980-03d8-11e9-8388-b4061d4142ad.png)
3. Click on publish icon, which spins and does nothing and produces this log.

> git push -u origin refs/heads/@JA/feature1
To https://xxxxxxx.visualstudio.com/MyProject/_git/MyProject
 * [new branch]      @JA/feature1 -> @JA/feature1
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse --symbolic-full-name @JA/feature1
> git rev-parse refs/heads/@JA/feature1
> git rev-parse --symbolic-full-name refs/heads/@JA/feature1@{u}
fatal: no such branch: 'refs/heads/@JA/feature1'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

Issues:
1. Publish works. I can see my branch on server repo but I also get above error. After publish icon remains same.
![image](https://user-images.githubusercontent.com/3745335/50261260-c89c8c00-03d9-11e9-90f7-cdba5af3a186.png)
2. Icon notifications stop working. I don't see any indication if there is any pending commit to push or pull latest changes.

I think it was working fine until 1.28 or 1.29

Note:
If I create branch with name like "feature1", everything works as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by o0rebelious0o** [comment]
I have reproed this locally and tracked down the issue.

git.ts:getBranch receives the branch string, `@test\test`, as an argument, `name`.

The first thing it does it compare the branch name to 'HEAD', else tests if the name of the branch begins with an '@' using the regex `} else if (/^@/.test(name)) {`.

In the case of the branch beginning with an '@', it then replaces the name argument to the function with the symbolic full name. resolved by running `git rev-parse --symbolic-full-name @test/test`.  This resolves to `refs/heads/@test/test`.  To then compute the rest of the branch information, the upstream/downstream changes, the code then runs `git rev-parse --symbolic-full-name <branch>@{u}` which in the case of a branch beginning with '@', fails to resolve.  The code catches the git exception, and throws which the calling code treats as if the upstream doesn't exist, hence showing the publish icon still, even though the branch DOES have an upstream and should show the sync icon.

If I remove the initial regex test `/^@/.test(name)`, the code then works correctly, in this case.

This behavior was changed by @joaomoreno in commit https://github.com/Microsoft/vscode/commit/2c0167ef9906e7ee765f99e3b1244de2e56bd4e8.

The simplest workaround is to not use a branch beginning with '@'.  As for a fix, I can't see the context on why the change was made, the description says 'git: getBranch should resolve @ name syntax', but I'm not sure what '@ name syntax' is.  Reverting this commit would fix this issue, but presumably there was another issue somewhere else which warranted the change in the first place. @joaomoreno do you have more context?
