### ISSUE TITLE
请问下能否在拆分编辑器后每两个栏中间添加一个明显的分割线用来让鼠标控制分割线

### ISSUE THREAD

**Issue by kuaidjun** [Microsoft/vscode#65432]
目前编辑器没有分割线 导致鼠标需要在两个栏中间不断摸索移动才能找到准确的位置去按住鼠标并移动从而改变每个栏的宽度比 希望可以在中间添加一个明显的分割线 让鼠标可以很轻松的找到正确的位置 谢谢

**Comment by ALNY-AC** [comment]
切换换主题试一下

**Comment by alexandrudima** [comment]
@kuaidjun I am sorry the development language of this project is in English. Can you please create an issue in English?
