### ISSUE TITLE
vscode how to use env for windows

### ISSUE THREAD

**Issue by Austzhu** [Microsoft/vscode#65430]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by Austzhu** [comment]
![image](https://user-images.githubusercontent.com/21327212/50258324-2234a300-043a-11e9-822d-0fa4240231c9.png)

**Comment by alexandrudima** [comment]
@Austzhu What is your issue?
