### ISSUE TITLE
The first Korean word before the space is broken on terminal

### ISSUE THREAD

**Issue by ventusjk** [Microsoft/vscode#65441]
Issue Type: <b>Bug</b>

I have newly installed VSCode, compiled and ran very simple code here.

```
#include <iostream>

using namespace std;

int main()
{
    cout << "안녕!" << endl;

    return 0;
}
```

Both compiling and running works well, but the word "안녕!" (including exclamation mark) is broken on terminal.

Fun thing is that if there's a space before the word (e.g. " 안녕!"), it properly outputs the word " 안녕!" with the inclusion of the space. So, I'm guessing that this is happening only to the first word.

I did switch the encoding type to EUC-KR and the problem still persists.

Could I please get any help on this?

Thank you.

<img src="https://i.imgur.com/PWHv8r5.png">

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (27.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1

</details>

**Comment by ventusjk** [comment]
Yeap, I got why...

I think it's the problem with Windows 10 update 1809 (RS5).

I did a test with 2 PC (The main with 1809 and sub with 1803) and 1 laptop with 1803.

The main PC with update 1809, of course, did reproduce such error while the sub PC and a laptop with update 1803 did not.

Then, I did update my laptop to 1809 and it definitely reproduced an error :/

**Comment by Tyriar** [comment]
Thanks for the investigation, unicode support on Windows should hopefully improve when we adopt conpty, see https://github.com/Microsoft/vscode/issues/45693
