### ISSUE TITLE
Second command of macro no longer executed after recent VS Code update

### ISSUE THREAD

**Issue by percygrunwald** [Microsoft/vscode#65443]
Issue Type: <b>Bug</b>

I use the `macros` extension to replicate the `cmd+e` behavior of IntelliJ for Mac. This command opens the "Recent files" dialogue and shifts the cursor to the previously open file (i.e. the second item in the list of recently opened files, where the currently open file is first on the list). 

To do this in VS Code, I created this macro:

```json
    // User Setings
    ...
    "macros": {
        "intellijRecent": [
            "workbench.action.quickOpen",
            "workbench.action.quickOpenNavigateNext",
        ]
    },
    ...
```

And bound it to `cmd+e` in my keybindings:

```json
    // keybindings.json
    ...
    {
        "key": "cmd+e",
        "command": "macros.intellijRecent",
        "when": "!inQuickOpen"
    },
    ...
```

**Up until the most recent update**, this was working as expected: pressing `cmd+e` would open the recently open files dialogue box and move the cursor to the second item in the list. Today, it is opening the recently open files dialogue box, but **not** moving the cursor to the second item in the list.

I tried these changes to see if they would return the expected behavior, but they did not:

```json
    "macros": {
        "intellijRecent": [
            "workbench.action.quickOpen",
            "workbench.action.quickOpenNavigateNext",
            "workbench.action.quickOpenNavigateNext"
        ]
    },
```

```json
    "macros": {
        "intellijRecent": [
            "workbench.action.quickOpen",
            "workbench.action.quickOpenNavigateNextInFilePicker"
        ]
    },
```

```json
    "macros": {
        "intellijRecent": [
            "workbench.action.quickOpen",
            "workbench.action.quickOpenNavigateNextInRecentFilesPicker"
        ]
    },
```

It seems to me that the second command is not being executed in the new update for some reason. 

I have also reported this in the `macros` extension repo (https://github.com/geddski/macros/issues/45). 

Thank you.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.82GB free)|
|Process Argv|-psn_0_1343816|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
relative-path-and-line|bgs|0.1.0
better-toml|bun|0.3.2
gotemplate|cas|0.3.0
gitignore|cod|0.6.0
EditorConfig|Edi|0.12.5
macros|ged|1.2.1
beautify|Hoo|1.4.7
elixir-ls|Jak|0.2.24
intellij-idea-keybindings|k--|0.2.30
terraform|mau|1.3.7
vscode-rufo|mbe|0.1.1
python|ms-|2018.12.1
vetur|oct|0.14.3
erlang|pgo|0.5.0
ruby|reb|0.21.0
java|red|0.36.0
jinjahtml|sam|0.5.0
vscode-sass-format|sas|1.1.6
elm|sbr|0.24.0
code-settings-sync|Sha|3.2.4
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1

</details>

**Comment by alexandrudima** [comment]
This is an issue with the extension. The promises returned by executeCommand are not properly waited upon [here](https://github.com/geddski/macros/blob/96b0d7b2930c26eea22f2a9acbebba823bc98c5b/extension.js#L34)

**Comment by percygrunwald** [comment]
@alexandrudima thank you very much
