### ISSUE TITLE
This issue can be deleted due to troll reply.

### ISSUE THREAD

**Issue by xdvarpunen** [Microsoft/vscode#65457]
This issue can be deleted due to troll reply.

**Comment by zigang93** [comment]
Hey.. does need open an issue for this?

**Comment by xdvarpunen** [comment]
@zigang93 I try to take your comment constructively. The **_amount of features and settings size_** in Visual Studio Code is definitely not the one you find in common code editors. Calling Visual Studio Code IDE gives better grasp of the possibilities the Visual Studio Code provides inside the editor and the amount of work it can need to "master it".

**Comment by xdvarpunen** [comment]
I find this sad.

**Comment by xdvarpunen** [comment]
Keep trolling @zigang93

**Comment by xdvarpunen** [comment]
@alexandrudima  delete this issue 👍

**Comment by xdvarpunen** [comment]
@alexandrudima do you know how to do it?
