### ISSUE TITLE
Removing search result expands collapsed rows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65451]
We refresh the root node which wipes out the expand state on all elements, not sure how to handle it besides always querying the expand state for the element when refreshing.

**Comment by joaomoreno** [comment]
@roblourens Forgot about this. The ObjectTree will preserve the collapsed state if you keep the same objects in the tree. Did that not work?

https://github.com/Microsoft/vscode/blob/09279755650dbc0463757e250451ba898a732487/src/vs/base/test/browser/ui/tree/objectTreeModel.test.ts#L144

**Comment by roblourens** [comment]
It does if I don't set the `collapsed` property, so I am detecting whether it's already in the tree, and if so I leaved `collapsed` as `undefined`.

**Comment by joaomoreno** [comment]
Oh I see... you do that because you want them to be expanded given a condition (number of results per file)... Maybe I can get you a `getDefaultExpansionState(element)` type of functionality in which you could provide the default expansion state for a "new" tree element? Would that be good for you?

**Comment by joaomoreno** [comment]
Actually another idea would be to get another two possible values: `ExpandedIfNew` and `CollapsedIfNew`.
