### ISSUE TITLE
Emmet - Multiplier * causes Emmet to become unresponsive using large number

### ISSUE THREAD

**Issue by samusstrike** [Microsoft/vscode#65455]
Issue Type: <b>Bug</b>

1. Use language type: html
2. Type some tag with multiplier of 100
e.g. br*100
Add more zeroes. Eventually, Emmet will become unresponsive. In some cases it may become responsive again, but mostly I've had to restart VSCode for Emmet to start working again.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.42GB (4.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
handlebars-preview|cha|1.1.0
sql-formatter|cym|1.0.2
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
xml|Dot|2.4.0
pgsql|dou|0.1.3
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.7
vscode-tfs|iva|0.7.2
relativepathrefactor|jak|0.9.0
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.10.1
debugger-for-chrome|msj|4.11.1
vscode-code-outline|pat|0.2.1
markdown-pdf|yza|1.2.0

</details>

**Comment by octref** [comment]
Fix is disabling emmet for `*number` where number > 100. I can't imagine someone find it useful to multiply any tag by more than 100 times.
