### ISSUE TITLE
Code-insider: downloading update never completes

### ISSUE THREAD

**Issue by royling** [Microsoft/vscode#65450]
- VSCode Version: Code-insider 1.30.0-insider
- OS Version: macOS 10.12.x

Steps to Reproduce:

It's always in downloading status, but never completed.
![screen shot 2018-12-20 at 1 49 17 pm](https://user-images.githubusercontent.com/1917351/50266450-88332180-045e-11e9-8882-c1d3f3de5644.png)

Does this issue occur when all extensions are disabled?:
Yes

Is this because there's a previous broken download? Where can I clean it to retry the update?

**Comment by usernamehw** [comment]
Had the same issue today, but it eventually downloaded and updated itself. (OS Win10)

**Comment by royling** [comment]
@usernamehw thanks, I'll retry and leave it for a longer time.

**Comment by royling** [comment]
no luck after I kept it there for one day...
I guess there was a previous broken download causing the downloading would never complete... just want to know the directory where the downloaded files are located so I can clean it first and retry another update.

**Comment by royling** [comment]
I uninstalled the broken one and reinstalled code-insider, the problem is gone.

closing this then.
