### ISSUE TITLE
Allow to show notifications that do not timeout

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#65459]
The Azure ML extension, presents .json files to the user when creating or editing Azure ML artifacts. We call showInformationMessage() with a prompt to the user to edit the json, then click submit on the same information notification message. After a timeout, this information message disappears into the "notification bell" of VSCode. Unfortunately, the user may not be done editing the json file at that point. Once they are done they are consistently flummoxed by what to do next. They're supposed to hit the "Submit" button on the UI presented by showInformationMessage(), but it's hidden and they don't realize they can click on the bell to see it again.

So... Is there an alternative approach for dealing with this problem? If not, I'm suggesting that a parameter to showInformationMessage() should be added to remove the timout to hide the message. It seems that both showWarningMessage() and showErrorMessage() do NOT disappear after a timeout, BUT the icons they use to indicate status (Yellow and red widgets) aren't appropriate for Azure ML extension needs

**Comment by bpasero** [comment]
If you must have user input, then you should use a modal dialog which our API allows you to do.

**Comment by greazer** [comment]
This doesn't work as the modal dialog is indeed modal. The user can't edit the json file that they need to edit.

**Comment by greazer** [comment]
For our extension (Azure Machine Learning) the situation is this: When creating Azure ML resources there is often several steps that need to be taken. To create a particular resource a user must fill in a set of properties to which to submit to the backend. As it stands, those properties are specified in the form of json. This seems to make sense as users in VSCode are likely use to dealing with json and the main alternative (asking a bunch of questions) isn't good either. Here's an example workflow:

- Ask question #1 via a pop down input
- Potentially ask #2 based on the answer to #1
- Ask the use to edit a json file based on the answers given above.
- After the user Submits the json (via a button on the information notification) ask question #3, #4... till done. Note that steps #4 through #X can also potentially cause other property settings to be requested (though we try to minimize this as much as we can).

So, the very frequent feedback we've gotten from users is that while they are editing the json, the informationMessageBox disappears into the notification bell. They don't realize that it's there and just think the experience is broken. 

Using a model dialog box won't work for this situation because the user needs to be able to edit a file. 

Any other suggestions as to what we could use in VSCode to solve this problem are welcome.

**Comment by greazer** [comment]
I did notice that there is one "informationMessage" that does not disappear automatically. That's the one that prompts the user to upgrade VSCode. :)

**Comment by greazer** [comment]
Found out today that the Python VSCode extension suffers from the same problem. During activation of that extension, the user can be presented with a showInformationMessage() (I can't recall the scenario off hand) that also has this same problem. The notification disappears and users are left not realizing they need to do anything. -- Contact @qubitron for details.

**Comment by qubitron** [comment]
There are a few places where the notification has an action for the user to take and it would be nice to have it up until the user explicitly closes it:
- Select Python Interpreter
- Convert Notebook to Python code

In many cases popups are more informational "There was an error, more output is available [View Output]" and auto-dismiss is fine, but in others we're asking the user to take action without having to block them so would like the dialog to persist.

**Comment by DanTup** [comment]
Here's another one... In Dart/Flutter we have a command for the user to start capturing verbose logs to attach to bug reports:

![screenshot 2019-02-28 at 11 21 00 am](https://user-images.githubusercontent.com/1078012/53563114-fecd5900-3b4a-11e9-9521-a2686bb853c7.png)

Building and launching an app takes a lot longer than the timeout on these messages, so the message disappear and the user is confused. Sometimes I get the wrong logs (the output of the debug window), and probably the user just left the log running away in the background for who knows how long.

A modal dialog won't work because the whole point is for the user to reproduce an issue. Putting it in the status bar would be far too subtle. It's supposed to be there, obvious and visible, so the user knows what they're supposed to do after they're reproduced the issue.

**Comment by sameemqiitm** [comment]
Hello all,
Is there any updates/progress on this?
My use Case is I have to show a user Accept and Reject buttons on the message , and based on that the extension performs next steps.
using a model isnt suitable option , as it effects the readability of the editor, and the selection of Accept/Reject would be entirely based on whatever user sees on the editor.
if not the timeout , is there an alternative way to handle this?
