### ISSUE TITLE
Expand select (Ctrl + Shift + A) select a single word instead of whole paragraph

### ISSUE THREAD

**Issue by hihahihahoho** [Microsoft/vscode#65462]
- VSCode Version: 1.30.0
- OS Version: Window 10 ultimate

Steps to Reproduce:

1. Press (Ctrl + Shift + A)
2. Only select a single word, have to press twice to select whole paragraph

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@hihahihahoho  I use <kbd>Ctrl</kbd>+<kbd>D</kbd> to select the word under the cursor. Does that work for you? You can then press it again to select the next word.

**Comment by alexandrudima** [comment]
@hihahihahoho What command are you executing? AFAICT we are not shipping with anything bound to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd> out of the box.

**Comment by hihahihahoho** [comment]
> @hihahihahoho What command are you executing? AFAICT we are not shipping with anything bound to Ctrl+Shift+A out of the box.
> 
> You can find this out, e.g.
> ![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

IT's expand select, maybe it's from my old keyboard setting
![image](https://user-images.githubusercontent.com/29968144/50338384-bab84980-0546-11e9-9fad-f2d654123978.png)

**Comment by jrieken** [comment]
> Only select a single word, have to press twice to select whole paragraph

@hihahihahoho While smart select isn't ideal and while we are working on extension API to make this better the behaviour you describe is extension. The selection grows along some logical bounds, e.g word, expression, etc
