### ISSUE TITLE
Emmet CSS # character

### ISSUE THREAD

**Issue by kamlyuk** [microsoft/vscode#65464]
- VSCode Version: 1.30.1
- OS Version: Windows 10 Pro x64

Emmet doesn't works correct after trying to type character **#**.

Steps to Reproduce:

1. Type `bd1#s`.
2. Press **Tab**.

Emmet must type `border: 1px #000 solid;`, but it doesn't.

![emmet-css](https://user-images.githubusercontent.com/17758812/50274390-d38d0600-0445-11e9-90c3-26dfe9b137e8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Is this a valid emmet abbreviation? Can you point me to the docs?

**Comment by kamlyuk** [comment]
https://docs.emmet.io/css-abbreviations/

Yes, check the first paragraph in Color values section. There is similar expression: `bd5#0s`. It does not works too in the editor.

**Comment by octref** [comment]
OK, it seems to work that way in Atom...

**Comment by RiodeJaneiroo** [comment]
Please make a normal "emmet" in css files.
When i write `dib`, then should write `display: inline-block` and now it is writing `box-decoration-break: `
and so with many rules.

**Comment by octref** [comment]
@RiodeJaneiroo Are you on insider version by any chance? It seems this is broken in Insiders but not 1.31.1.

**Comment by RiodeJaneiroo** [comment]
@octref no, stable version. This setting helped me

`{
  "key": "tab",
  "command": "-acceptSelectedSuggestion"
}`

**Comment by Friksel** [comment]
This issue was already started in december 2018 on version 1.30.1.
It's now 5th of june 2019 and we're in version 1.34.0 of VS Code, but unfortunately emmet abbreviations like 'bd1#s' still don't work in VS Code.

It would be nice if this could get some love and attention, because these css emmet abbreviation really speed up the workflow of a front-end developer a lot and so are very welcome! Thanks!

**Comment by rzhao271** [comment]
I have confirmed that vscode-emmet-helper can now expand the abbreviation properly, but I think there's still an issue with some code in this repo, so I can't call this fixed yet.

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode-emmet-helper/pull/46 fixing this

**Comment by Friksel** [comment]
> 
> 
> Created a PR [microsoft/vscode-emmet-helper#46](https://github.com/microsoft/vscode-emmet-helper/pull/46) fixing this

Thanks!
