### ISSUE TITLE
Linux: clicking on icon in dock opens app again even though already running

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#65460]
This is a continue of https://github.com/Microsoft/vscode/issues/56067, I think the issue is not well understood and has nothing to do with running `code && code` from the command line.

**Steps:**
* add Code to favorites so that it appears in dock
* click it so it starts
* wait until the editor opens
* click the dock again
* :bug: a second window opens which is totally unexpected

**Variant:**
* remove Code from favorites
* start it
* :bug: notice how the icon does not appear in the dock until maybe 10s after startup

I believe both variants have the same issue which is possibly in Electron. I tried with Electron Fiddle and do not see the behaviour of a second app opening though so I wonder if this is related to our desktop shortcut.

**Comment by 0matgal0** [comment]
Could be the way DE's use `*.desktop` files and especially `StartupNotify=true` causing this. Also, all electron apps seem to have this sort of issue on linux, maybe wm's / de's expect the app setting some kind of window handle earlier?

**Comment by bpasero** [comment]
@0matgal0 thanks for chiming in on this, if you have any more ideas how to fix this, be my guest.

**Comment by Tyriar** [comment]
Shift+click is meant to do this (on some display managers), but not just click.

**Comment by bpasero** [comment]
@Tyriar on my Desktop machine with Ubuntu 18 natively running I can no longer reproduce the issue when I configure:

`StartupNotify=false`

In the `code-insiders.desktop` file. However, once I made this change and I got an insiders update today where this was being set back to `true`, it still does not reproduce, so I am not sure where this property is being cached.

**Comment by bpasero** [comment]
Looks like it needs a restart to take effect for me, which explains why changing the property in the running session does not have much of an impact.

**Comment by bpasero** [comment]
@Tyriar ping

**Comment by Tyriar** [comment]
@bpasero I can't reproduce on Ubuntu 18.04.1. What I suspect is happening is that the one you favorited was the cli instead of the exe or a duplicates .desktop file in `~/.local/share/applications/`. I can't reproduce this on my Ubuntu 18.04.1 but I see this happen with other applications as well.

To clarify everything works perfect here:

- When there's no window it opens the app
- When there's one window it focuses
- When there's two windows it shows a chooser popup
- When I shift-click it opens a new window

**Comment by bpasero** [comment]
@Tyriar reproduces easily for me:
* download Ubuntu 18 ISO ([link](http://releases.ubuntu.com/18.04/ubuntu-18.04.1-desktop-amd64.iso))
* install into Parallels 
* download Code deb package and install
* start Code
* add it to favorites
* close Code
* start Code from favorites
* 🐛 notice how there is a spinning cursor a long time after the window of Code has already open
* 🐛 if you click on the application icon as long as the spinning cursor is there, you get another Window open

That does not sound like desirable behaviour to me for an operating system.

**Comment by Tyriar** [comment]
I could repro in my VM, switching StartupNotify to false seems to fix it and make sense so pushed that
