### ISSUE TITLE
[Powershell] Collapse code block not working when a hashtable is defined

### ISSUE THREAD

**Issue by mieel** [Microsoft/vscode#65465]
Collapsing a code block (for example a funtion) does not work as expected when the code contains a declared hashtable.

# 1
```
Function Test {
    code
    code
    code
    code
}

```
collapses as 
```
Function Test {   ....
}
```

# 2
```
Function Test {
    code
    code
    hashtable = @{}
    code
    code
}

```
Collapses as:
```
Function Test {...
    hashtable = @{}
    code
    code
}
```

**Comment by alexandrudima** [comment]
@mieel Can you please create the issue directly against the PowerShell extension at https://github.com/PowerShell/vscode-powershell/issues ?
