### ISSUE TITLE
Insider Edition: Explorer window shows wrong nodes when expanding/collapsing folders

### ISSUE THREAD

**Issue by juristr** [Microsoft/vscode#65463]
- VSCode Version: Version 1.3.1.0-Insider (d2b050911cbf3b6e77584f61b0cf088058a20fe5)
- OS Version: macOS high sierra (10.13.6)

This is what happens

![vscode-explorer-issue](https://user-images.githubusercontent.com/542458/50274137-c0c20380-043c-11e9-9854-b2006ee9020e.gif)

Unfortunately reproducing is kinda' hard. Starts happening after a while of using VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is weird. Let me know if you can reproduce.

**Comment by juristr** [comment]
@joaomoreno well that's exactly the problem 🤔. Any way I can give you some debug info when it happens? Because it starts happening quite immediately when I start VSCode and it started with today morning's update of the insiders edition.

Also for instance, if I tell Code to select the open item in the Explorer, it fails

![image](https://user-images.githubusercontent.com/542458/50277817-bbb58200-0445-11e9-8da0-79b21edc589e.png)

In the screenshot you see the `list-page-base.component.ts` being active, but `vta-detail.component.spec.ts` being selected.

**Comment by bpasero** [comment]
I got this https://github.com/Microsoft/vscode/commit/2803a8655cf5e05066a4ee47cce303eefca6408c

Update to latest insiders to fix.

**Comment by juristr** [comment]
fixed!! 🎉 🎉 🎉 🎉  🙇 🙇 

YOU. GUYS. SIMPLY. ROCK

keep it up 💪

**Comment by sbatten** [comment]
marking as verified due to OP response and erratic repro
