### ISSUE TITLE
Supplementation does not work

### ISSUE THREAD

**Issue by fs-kanayama** [Microsoft/vscode#65468]
Code completion is not displayed.
It happens suddenly.
Restart to fix it.

How can I fix this event?

**Comment by alexandrudima** [comment]
@fs-kanayama What do you mean by "supplementation"? Can you please give steps to reproduce? What programming language are you using? What extensions do you have installed?

**Comment by fs-kanayama** [comment]
this candidacy.

![-1](https://user-images.githubusercontent.com/1792852/50319584-7a87a580-050b-11e9-95ec-a7333dd1b80c.png)

It disappears suddenly
Pressing Ctrl + Space causes "Stitching" to stop working.

It is difficult to reproduce because it happens suddenly.
It happens suddenly when writing a program for about 30 minutes to 1 hour

Poor plugin?

Plugin lists.

- API Blueprint Language 0.0.2
- Auto Close Tag 0.5.6
- Auto Rename Tag 0.0.15
- Bracket Pair Colorizer 1.0.61
- ES7 React/Redux/GraphQL/React-Native snippets 1.9.3
- Japanese Language Pack for Visual Studio Code 1.30.2
- Path Autocomplete 1.13.1
- Path Intellisense 1.4.2
- PHP IntelliSense 2.3.10
- Prettier - Code formatter 1.7.3
- Rainbow CSV 0.8.0
- REST Client 0.20.4
- Smarty 0.3.0
- vscode-icons 8.0.0

I will examine conditions

thanks

**Comment by fs-kanayama** [comment]
![-1](https://user-images.githubusercontent.com/1792852/50416516-78537d00-0864-11e9-9540-0bb5df6f7199.png)
Ctrl + Space Loading does not end.
Is there a way to check the error log?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
