### ISSUE TITLE
Views/Viewlet/Panel - avoid overriding setFocus/setExpanded

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#65475]
We have many views, viewlets and panels. Some override `setVisible`, some also `setExpanded` to do something when visibility changes. Instead of having to override these methods, there is now an event that is fired:
* for viewlets: `onDidChangeVisibility` (will be called when the viewlet gets visible or hidden)
* for views: `onDidChangeBodyVisibility` (will be called when the view gets visible or hidden and also when expanded or collapsed)

With these events, handling visibility changes is much simpler.

I started to adopt these events in some places:
* `commentsPanel` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-716c1016f4f64046272ba0498f06373c) @rebornix @RMacfarlane 
* `breakpointsView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-eae2adda1084d6ae8758f4607e466ecf) @isidorn 
* `loadedScriptsView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-243fa7bec35b458f0289c75ef915a768) @isidorn 
* `callstackView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-8ff36e896660ec181cd2a69971004551) @isidorn 
* `repl` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-375cb3b52dcd2f961b322bd3156fc325) @isidorn 
* `variablesView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-96a99190da1b785bdb276859ccc777c3) @isidorn 
* `watchExpressionsView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-b20a8244b0b3d7a403de2a4c7559a891) @isidorn 
* `extensionsViewlet` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-5531568eeca0e6004c16ca85cf5dddbf) @sandy081 
* `openEditorsView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-175dcd61135308bda1aa5e1b240328a6) @isidorn 
* `markersPanel` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-05f7ab8eb2d4408ed33951751e0def10) @sandy081 
* `searchView` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-896dba18af57f1b39e477b696e3c7898) @roblourens 
* `terminalPanel` (https://github.com/Microsoft/vscode/commit/5eff1e2ede99f34dfa0f509ffc62a06d47d119a1#diff-e2c645917fa0f838bd2884b02f0f03eb) @Tyriar 

@sandy081 there are still some places that need adoption:
* ~~`viewsViewlet.ts` and `customView.ts` (including `updateTreeVisibility` which we could maybe ditch?)~~
* ~~`scmViewlet.ts`~~
* ~~`explorerView.ts` (actually currently does not seem to handle the case properly where it gets expanded after being collapsed)~~
* `outlinePanel.ts` listens on both `setExpanded` and `setVisible`

**Comment by bpasero** [comment]
Actually we might want to leave the explorer as it is because @isidorn is rewriting it anyways.

**Comment by isidorn** [comment]
Simple questions: I still plan to call `this.isVisible()` to figure out if I am hidden, I do not want to keep a local which says "oh you are hidden" by listening on the event.
Will isVisible return false when I am collapsed? I would expect that it does.

Also the ViewPanel which has the WorkbenchTree is gone on my branch. So do not bother with it. I have no clue what is the name since the naming is confusing as F.

**Comment by bpasero** [comment]
I think `isVisible` and "is body visible" are different. A view can be visible but collapsed.

**Comment by bpasero** [comment]
@isidorn we added and adopted `isBodyVisible()`

**Comment by bpasero** [comment]
We also pushed a change that the event is now fired consistently also on creation of the view/viewlet.

**Comment by bpasero** [comment]
All done, I the explorer viewlet is left untouched given the rewrite is coming.
