### ISSUE TITLE
Constant Hanging 

### ISSUE THREAD

**Issue by Skullnick** [Microsoft/vscode#65473]
Issue Type: <b>Performance Issue</b>

1. Create a React template project with ASP.NET Core : 
https://docs.microsoft.com/fr-fr/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=netcore-cli
2. Launch project.

NB: VSCode does not hang or slow down when the project is not launched. It might have something to do with the debug mode.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    81	  8132	code main
    0	    83	  8696	   shared-process
    5	   356	 10672	   window (HomePage.js - Pharos - Visual Studio Code)
    0	    14	  6804	     watcherService 
    0	    10	  5092	       console-window-host (Windows internal process)
    0	    13	 10396	     electron-crash-reporter
    0	   106	 11552	     extensionHost
    0	    43	  6916	       C:\Users\voisi\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\rzls.exe -lsp --logLevel None
    0	     9	  1668	         console-window-host (Windows internal process)
    0	   107	  8320	       electron_node eslintServer.js 
    0	   242	  8664	       electron_node tsserver.js 
    0	    45	  7576	         electron_node typingsInstaller.js typesMap.js 
    0	     5	 12828	       cmd /s /c "C:\Users\voisi\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe -s c:\Work\Webdev\Pharos\Pharos --hostPID 11552 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\voisi\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	   187	  2044	         C:\Users\voisi\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe  -s c:\Work\Webdev\Pharos\Pharos --hostPID 11552 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\voisi\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    10	  9500	         console-window-host (Windows internal process)
    0	    45	 14156	       "C:\Users\voisi\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\voisi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=11552
    0	    34	 12472	     searchService
    0	    49	 13792	     C:\Users\voisi\.vscode\extensions\ms-vscode.csharp-1.17.1\.debugger\vsdbg-ui.exe
    0	     9	 13800	       console-window-host (Windows internal process)
    0	   400	 13956	       "C:\Program Files\dotnet\dotnet.exe" C:\Work\Webdev\Pharos\Pharos\bin\Debug\netcoreapp2.1\Pharos.dll
    0	     5	 13320	         "cmd" /c npm run start -- 
    0	    33	  8068	           electron_node npm-cli.js 
    0	     5	  1348	             C:\WINDOWS\system32\cmd.exe /d /s /c rimraf ./build && react-scripts start
    0	    22	  4992	               node   "C:\Work\Webdev\Pharos\Pharos\ClientApp\node_modules\.bin\\..\react-scripts\bin\react-scripts.js" start
    0	   512	  5448	                 node C:\Work\Webdev\Pharos\Pharos\ClientApp\node_modules\react-scripts\scripts\start.js
    0	   104	 12932	   gpu-process
    0	    69	 14800	   window (Rapporteur du problème)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (HomePage.js - Pharos - Visual Studio Code)
|    Folder (Pharos): 287 files
|      File types: js(94) scss(67) cs(27) json(17) less(14) cache(13) css(6)
|                  pdb(5) dll(5) txt(4)
|      Conf files: csproj(1) launch.json(1) settings.json(1) tasks.json(1)
|                  package.json(1)
|      Launch Configs: coreclr(2) chrome;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.2
es7-react-js-snippets|dsz|1.9.3
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
Ionide-fsharp|Ion|3.30.0
dotenv|mik|1.0.1
vscode-language-pack-fr|MS-|1.30.2
mssql|ms-|1.4.0
python|ms-|2018.12.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.1

</details>

**Comment by CapitanFuture** [comment]
Nice I work with a current MacOs on a MacMini 2018 and have the same problem on a completely different platform ;)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by Skullnick** [comment]
@mjbvz Yes, same problem. I obviously have to enable the C# extension otherwise I can't launch the project.

**Comment by mjbvz** [comment]
@Skullnick Thanks. Since this is C# specific, please file this issue against the C# extension

**Comment by Skullnick** [comment]
@mjbvz Then why am I not getting the same issues with 1.29.1 ? I reverted back and everything is fine.
