### ISSUE TITLE
Search pane exclude filter does not work in multi-root workspaces

### ISSUE THREAD

**Issue by lodybo** [Microsoft/vscode#65477]
- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.16299

When searching for a keyword in a multi-root workspace, and choosing a folder to _exclude_ in the search results, that folder is still visible.

Steps to Reproduce:
I created a very simple sandbox illustrating the problem: https://github.com/lodybo/vscode-multi-root-search-exclude-bug

1. In the search pane: search for the key 'localhost'
![vscode-multi-root-search-bug-no-filter](https://user-images.githubusercontent.com/1598330/50281051-8a8d7f80-044e-11e9-9d70-1845b0e14e67.PNG)

2. When adding the folder 'back-end' to the 'files to exclude' input (like so: `./back-end`, [because it would limit the search to a single root folder](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_search)), the folder still shows up in the search results.
![vscode-multi-root-search-bug-exclude-filter](https://user-images.githubusercontent.com/1598330/50281155-db9d7380-044e-11e9-8b77-125d601a5bf8.PNG)

This also happens if the folder is added to `search.exclude` in workspace settings.

It appears to work for the 'files to be include' filter, strangely enough..
![vscode-multi-root-search-bug-include-filter](https://user-images.githubusercontent.com/1598330/50281194-f96ad880-044e-11e9-93ff-611998b0694b.PNG)

Does this issue occur when all extensions are disabled?: Yes/**No**

I tested this in my normal VS Code instance, as well as in one with all extensions disabled and in an Insiders instance.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/63303
