### ISSUE TITLE
same root folder name can't rename subfolder or file

### ISSUE THREAD

**Issue by payallmoney** [Microsoft/vscode#65482]
Issue Type: <b>Bug</b>

if theres two root folder with same   name , then  can't rename subfolder or file

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.70GB (0.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
vscode-html-css|ecm|0.2.0
intellij-idea-keybindings|k--|0.2.28
code-beautifier|mic|2.1.0
Go|ms-|0.8.0
vetur|oct|0.14.3

</details>

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders?

**Comment by payallmoney** [comment]
latest vscode is ok

**Comment by isidorn** [comment]
Great, thanks for letting us know
