### ISSUE TITLE
VSCode wont capture clicks trough TeamViewer 

### ISSUE THREAD

**Issue by fernandoreyes1** [Microsoft/vscode#6548]
- VSCode Version: 1.1
- OS Version: 10

Steps to Reproduce:
1. Install the latest version of TeamViewer in Windows 10 on Server mode
2. Install teamviewer on computer (in this case, Windows RT on Surface RT
3. Open TeamViewer on Surface RT on terminal mode and connect to Windows 10 remote server.
4. Interact with VSCode, the interface will capture all keystrokes but no clicks

**Comment by alexandrudima** [comment]
@fernandoreyes1 Since VSCode is built on top of Chromium, do you experience these issues when using the Chrome browser, for example?

On our side, we simply listen to mouse and touch gestures given by Chromium/Electron

**Comment by fernandoreyes1** [comment]
I didn't know it was made on Chromium, but chrome has the same effect and
doesn't react to clicks either, so it is an inherithed bug.

**Comment by alexandrudima** [comment]
@fernandoreyes1 Maybe you can report this to Chromium (https://bugs.chromium.org/p/chromium/issues/list) and if they address it, we will probably soon update and benefit from the fix.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
