### ISSUE TITLE
breakpoint problem with files in a directory with /src as name

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#6549]
Typescript: Version 1.8.10
On mac osx 10.11.5
Vscode 1.1.1

I don't know if this is a vscode or typescript issue.

I have a project with ts compiling to js with sourcemaps. 
All was working fine until I decided to move all custom project code files (except app.ts) into a /src directory:

Before: 

/app.ts (in project root)
/apps/directory/controller.ts
/afile.ts

After:

/app.ts (not moved)
/src/apps/directory/controller.ts
/src/afile.ts

After moving the files, any breakpoint set in files in /src would become black with message  “Breakpoint ignored becasue generated code not found (source map problem?). This is strange because project was working properly, which proves js files were generated and used. Breakpoints on unmoved app.ts were ok.

renaming /src to anything else (actually /source ) solved the problem.
Not sure if the problem was because directory was named specifically /src or not.

**Comment by weinand** [comment]
@JonathanMEdwards fix will be available in next Insider build
