### ISSUE TITLE
Vscode terminal problem！

### ISSUE THREAD

**Issue by DS0818** [Microsoft/vscode#65496]
- VSCode Version:   1.30.1
- OS Version: windows 10 1809  X64

Steps to Reproduce:

1.ctrl+~ 
   Terminal does not display current directory

`Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。`

2.
Catalogs are displayed when you enter a command at random`

`Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。`

`PS G:\`

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
duplicate of #57803 ?

**Comment by DS0818** [comment]
对的，和＃57803问题一样！

**Comment by DS0818** [comment]
Yes, the same as #57803!
