### ISSUE TITLE
Intellisense crash C when write function parameter

### ISSUE THREAD

**Issue by Tetrastorm** [Microsoft/vscode#65497]
Issue Type: <b>Bug</b>

Intellisense in C crash when I write a function parameters with pointer or structure.

Frequency : Often

Actual : Microsoft.VSCode.CPP.IntelliSense.Msvc.linux killed by SIGSEGV
Expected : Don't crash

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.19.8-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3296)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (2.46GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.4.4
vscode-gitbuild|grz|1.0.1
chat|kar|0.9.0
vscode-github|Kni|0.30.1
binary-viewer|mom|0.0.1
python|ms-|2018.12.1
cpptools|ms-|0.20.1
vsliveshare|ms-|0.3.1071
epitech-c-cpp-headers|nic|1.11.0
vscode-spotify|shy|3.1.0
pdf|tom|0.4.3

</details>

**Comment by alexandrudima** [comment]
@Tetrastorm Can you please open an issue directly against the extension at https://github.com/Microsoft/vscode-cpptools ?
