### ISSUE TITLE
Clicking in the debugger "Watch" pane text box counts as a click on the expression, preventing double clicking

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#65491]
Version: 1.31.0-insider (user setup)
Commit: 2803a8655cf5e05066a4ee47cce303eefca6408c
Date: 2018-12-20T09:10:39.545Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Start editing an expression in the debugger Watch pane
2. Try to double-click to select a word
3. Instead of selecting the word, the text box exits

Also (less important but still annoying):

1. Start editing an expression in an active debugger Watch pane
2. Click anywhere inside the box
3. The cursor moves, but the expression tree also collapses or expands, which is very distracting and even potentially moves the text box out of view

**Comment by isidorn** [comment]
Thanks for reporting this with nice steps and thanks for using vscode insiders.
