### ISSUE TITLE
The Vim plugin can not edit except i/a/s

### ISSUE THREAD

**Issue by milley** [Microsoft/vscode#65494]
Issue Type: <b>Bug</b>

Issue Type: Bug

When i update my gocode library and the Go plugin, i can not use vim on Visual Studio Code, the version of the Go plugin like this:
name: Go
ID: ms-vscode.go
describe: Rich Go language support for Visual Studio Code
version: 0.8.0
publisher: Microsoft
vs url: https://marketplace.visualstudio.com/items?itemName=ms-vscode.go

I can use the keymap i,s,a to update the text,but can not delete use backspace on insert mode or use dd/x on normal mode.

Extension version: 0.16.14
VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
TabOut|alb|0.1.6
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.22.0
mavensmate|Dav|0.15.0
tab-hero|dev|0.0.1
xml|Dot|2.4.0
gitlens|eam|9.2.2
tortoise-svn|fan|0.1.1
CppSnippets|har|0.0.13
auto-comment-blocks|kev|1.0.1
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
cpptools|ms-|0.20.1
Go|ms-|0.8.0
vscode-code-outline|pat|0.2.1
vscode-docker|Pet|0.4.0
java|red|0.36.0
vscode-icons|rob|8.0.0
go-test-outline|Rom|0.2.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vim|vsc|0.17.0
gitblame|wad|2.6.3
clang-format|xav|1.8.0
plsql-language|xyz|1.6.5
markdown-all-in-one|yzh|1.8.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@milley Can you please open an issue directly against the extension at https://github.com/VSCodeVim/Vim ?
