### ISSUE TITLE
Allow configurable key bindings to any task

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#6550]
For instance. I would like to assign key binding to any task
Other than just test and build.
for instance

``` json
  {
    "key": "ctrl+shift+1",
    "command": "workbench.action.tasks.task1"
  }
```

**Comment by dbaeumer** [comment]
This is actually a nice idea to solve this.

@alexandrudima can I have arguments to a command in the key bindings file. I would like to name the action workbench.actions.task and then have an argument "task1"

**Comment by dbaeumer** [comment]
@alexandrudima ping...

**Comment by dbaeumer** [comment]
Moving. Was very busy with the TS builder exploration.

**Comment by alexandrudima** [comment]
@dbaeumer Not yet, but it is something I wanted to do since more than 1 year. :)

**Comment by dbaeumer** [comment]
@codyrigney92 is working on this here: #10676, but PR is not ready yet. Moving to September.

**Comment by dbaeumer** [comment]
No progress on the pull request. Moving to October.

**Comment by dbaeumer** [comment]
No progress on PR. Moving to November

**Comment by ramya-rao-a** [comment]
@dbaeumer There is progress on the PR, will we be taking this for the current milestone or pushing to Jan 2017?

**Comment by dbaeumer** [comment]
Unfortunately I was not able to get this into November given the LSP work I had to do. For January we want to completely revisit the way tasks work. See the discussion here: #15179. I will make sure that this will make it into the new design.

**Comment by aleksey-bykov** [comment]
tracking at stackoverglow: http://stackoverflow.com/questions/41510632/how-can-i-run-a-custom-task-different-from-test-or-build-from-a-keychord-in-vs/41512460#41512460

**Comment by dbaeumer** [comment]
I re-implemented the task execution engine for Jan to use the terminal instead of the output window. Although not the default yet I will wait until the switch is final to provide support for this request With the new engine this needs more thinking since the new engine support executing tasks in parallel and to compose task out of smaller tasks. I first need to finalize the syntax in the tasks.json for this before allowing to bind key bindings for the composite tasks. Otherwise I might break clients unnecessarily.

**Comment by dbaeumer** [comment]
This will be available in the next version of VS Code.

```
	{
		"key": "ctrl+h",
		"command": "workbench.action.tasks.runTask",
		"args": "tsc"
	}
```

**Comment by origin1tech** [comment]
This is just outstanding...VSCode becoming gold std. IDE.

**Comment by cbrianball** [comment]
Agreed, this opens up a lot of options for me!

**Comment by raldred** [comment]
@dbaeumer is this implemented in 1.11? There was suggesting on #10676 that it was due in 1.10.
Does seem to work as per docs:
https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks

**Comment by dbaeumer** [comment]
This is in but there seems to be problems with it for 1.11.x. I have a bug for it and will investigate.

**Comment by raldred** [comment]
Thought i was going crazy. Thanks @dbaeumer

**Comment by rmilesson** [comment]
The solution is not what @justin-romano asked for. Why is this issue closed?
