### ISSUE TITLE
onDidChangeActiveTextEditor doesn't fire on large documents

### ISSUE THREAD

**Issue by GabeDeBacker** [Microsoft/vscode#65509]
- VSCode Version: 1.30.0 (64-Bit)
- OS Version: Windows 10 64-Bit Build 17763

Steps to Reproduce:

1. Have an extension that registers for vscode.window.onDidChangeActiveTextEditor
2. Open a very large file (such as a 2GB log file)
(Here is the size of the one I'm using)
Directory of S:\dumps\logs
12/18/2018  09:19 PM     1,975,803,272 buildfre.log

The extension does not get called for this file, but it will for larger files.

When using 64-bit VSCode it has no issue displaying this file, but extensions don't appear to be called.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Files >50MB are not currently synchronized to the extension host process for memory usage concerns. Let's track in #31078
