### ISSUE TITLE
VS Code Update fails if an extension's files are broken

### ISSUE THREAD

**Issue by Marshal313** [Microsoft/vscode#65506]
I tried to update VS Code but update kept failing, Even after I restarted the computer. Then I took a look at the log that I uploaded here and realized that I've lost a folder from unity debugger extension when copied it from another computer and that missing folder was the cause of crash on update.

Uninstalling and Reinstalling the extension solved the problem.

- VSCode Version: One version prior to 1.30, Trying to update to 1.30
- OS Version: Windows 10

Steps to Reproduce:

1. Mess with files of an Extension in C:\Users\\\<Username\>\\.vscode\extensions\\\<Extension\>
2. Try to update VS Code using Menus -> Help -> Check for Updates (Restart to Update)

Does this issue occur when all extensions are disabled ? Yes
[vscode-inno-updater-1545325812.log](https://github.com/Microsoft/vscode/files/2699805/vscode-inno-updater-1545325812.log)

**Comment by Marshal313** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Update Fails (#58428)](https://www.github.com/Microsoft/vscode/issues/58428)
> 
>     * [Restart to update always fail (#61085)](https://www.github.com/Microsoft/vscode/issues/61085)
> 
>     * [Update: Updating VS Code should check for updates first. (#44685)](https://www.github.com/Microsoft/vscode/issues/44685)

[Update Fails (#58428)](https://www.github.com/Microsoft/vscode/issues/58428) is quite the same as here, Difference is that it requires permission to edit a file. In my case, It can't find the file / directory.

[Restart to update always fail (#61085)](https://www.github.com/Microsoft/vscode/issues/61085) is not related to extensions or filesystem.

[Update: Updating VS Code should check for updates first. (#44685)](https://www.github.com/Microsoft/vscode/issues/44685) is not related.

**Comment by joaomoreno** [comment]
@Marshal313 Actually the problem is how you have set up VS Code. I suggest to not place the `Extensions` folder inside the `VS Code` installation directory. Keep them siblings instead.
