### ISSUE TITLE
Update Octicons

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#65508]
Related to #36053 #10455 #8017

This issue is to track the progress of updating our version of [Octicons](https://octicons.github.com/) (3.1.0) to the latest version (8.2.0). We'll need to create the work to convert the latest versions (svg) back into an icon font. Below are the requirements for this work:

- [x] Convert svgs into icon font
- [x] Include backward compatibility
- [x] Map old unicodes to new icons
- [x] Remove unnecessary font files
- [x] Add/update proper licenses
- [x] Test new icon font

Working branch can be found under [misolori/octicon-update](https://github.com/Microsoft/vscode/tree/misolori/octicon-update). Below is a list of the new additions:

- `arrow-both`
- `bold`
- `eye-closed`
- `fold-down`
- `fold-up`
- `grabber`
- `italic`
- `kebab-horizontal`
- `kebab-vertical`
- `logo-gist`
- `note`
- `plus-small`
- `project`
- `screen-full`
- `screen-normal`
- `smiley`
- `tasklist`
- `text-size`
- `unverified`
- `verified`

Please refer to [Octicon's Changelog](https://github.com/primer/octicons/blob/master/CHANGELOG.md) for a full list of updates.

:octocat: :heart:

**Comment by NavyAdmiral** [comment]
@misolori Is this also going to address https://github.com/Microsoft/vscode/issues/57237 ?

**Comment by misolori** [comment]
@NavyAdmiral this is only for addressing Octicons, which are only used in the status bar. 

#57237 will be likely be address when we get to #8017, which I'm hoping to start on this iteration.
