### ISSUE TITLE
signatureHelp gives buggy results when one parameter is a subset of another

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#65513]
- VSCode Version: 1.30.1
- OS Version: arch linux

Steps to Reproduce:
```
function foo(aa, aaa) {

}

foo()
```
![image](https://user-images.githubusercontent.com/7345761/50308156-83e12580-04ab-11e9-8da4-7411d78f2b4a.png)

This bug is similar to #21518 , but that one is closed forever
Discovered in https://github.com/Microsoft/vscode-cpptools/issues/1504

**Comment by sean-mcmanus** [comment]
It turns out VS Code added a new API we can use to fix it: https://github.com/Microsoft/vscode-cpptools/issues/2952 . So this VS Code issue can be closed.
