### ISSUE TITLE
Search should use default scope after include and exclude are cleared

### ISSUE THREAD

**Issue by shanimal** [Microsoft/vscode#65510]
Steps to Reproduce: 
1. Open a node project in Visual Studio Code
1. Open global search (Command + Shift + F)
1. Search for something that has results in the standard scope ( i searched for `switch` ) Let's say there were 10 results.
1. Add an excluded folder to "files to include" ( I included `./node_modules` )
1. Press enter to search again with the same query. 
1. The original search results are replaced by items found in the scope provided (as expected) Say 100 results.
1. Clear the "files to include" field and press enter to search again.

Actual Result:
The search results change slightly (Say 9 results) and still have results from the previous scope, even though the field was cleared.

Expected Results:
The search results should show the original search results from Step 3.

Possible work-around:
Sometimes toggling the widget cog at the right of the "files to exclude" field will make it seem like the scope reset, but if you toggle it off again it hasn't. Selecting the cog is non-intuitive. If you clear the "files to include" field (returning it to it's initial state) the intuitive thing is to revert to the initial results.

BTW I originally used the "Issue Reporter" in VSC. When I clicked the button to "Preview it on Github" it linked to an error page. So if this is in the wrong place or the format is strange it's because I had to figure out how to get here to file the bug.

**Comment by shanimal** [comment]
fwiw, it's not completely clear what the cog in the "files to exclude" field does. It seems to tell search to look only in the normal folder scope, but it doesn't always do that...

**Comment by roblourens** [comment]
> The search results change slightly (Say 9 results) and still have results from the previous scope, even though the field was cleared.

Did you open the files between steps? Open files will still be included in the search even if excluded by some pattern.

@RMacfarlane seems that github doesn't like that url for some reason
