### ISSUE TITLE
Param hint popup shows even when disabled.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#65519]
Issue Type: <b>Bug</b>

Here is my setting:

"editor.parameterHints.enabled": false,

Yet popup display, even after I started a new instance of vscode.

![screenshot_20181220_222830](https://user-images.githubusercontent.com/439226/50323215-a6bd0b00-04a6-11e9-89ce-216bb65a4854.png)

VS Code version: Code - Insiders 1.31.0-insider (2803a8655cf5e05066a4ee47cce303eefca6408c, 2018-12-20T09:06:52.404Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.66GB (3.15GB free)|
|Process Argv|/home/yadav/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.0.0
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
java-debug|DSn|0.0.2
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.0.21
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
java|red|0.36.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@rajinder-yadav That looks like the hover. It is a different widget than parameter hints and can be disabled via `editor.hover.enabled`.

**Comment by rajinder-yadav** [comment]
Thanks, that did it!
