### ISSUE TITLE
Default build tasks are mixed in with other tasks

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65511]
Something just changed here, I have a workspace with a few folders and each has a default build task. If I press cmd+shift+b, I see those tasks but also every detected task which I don't care about. 

Then if I type to search, it filters the whole list and sorts alphabetically, and the configured tasks are mixed in with the detected tasks. Not sure if bug or feature.

The main reason I don't want to see the detected tasks is that it finds tons of tsconfig files from test projects that I don't want to run, and also gulp tasks that aren't relevant.

In 1.30 I can press cmd+shift+b, type a few characters of the name of the project and hit enter, and get the right build task.

**Comment by alexr00** [comment]
There were some pretty serious issues with task detection a couple weeks ago. Are you still seeing this? When I do ctrl+shift+b in the this repo now I'm only seeing the "Build VS Code" task.

**Comment by roblourens** [comment]
Works now!
