### ISSUE TITLE
Chinese charater in code can't show normal in Java Swing

### ISSUE THREAD

**Issue by CatchTheDog** [Microsoft/vscode#65528]
Issue Type: <b>Bug</b>

I work with my JAVA Swing project on vscode, some chinese character  on JButton  can't show nomally .help.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.22.0
xml|Dot|2.4.0
intellij-idea-keybindings|k--|0.2.30
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1

</details>

**Comment by alexandrudima** [comment]
@CatchTheDog Do you use Chinese characters in the code editor in a java file and they do not render correctly? Can you please attach a file that shows the problem and a screenshot?

**Comment by CatchTheDog** [comment]
@alexandrudima  yes ,i use Chinese characters in the code ,but they don't render correctly.

[JFrame.java.txt](https://github.com/Microsoft/vscode/files/2711741/JFrame.java.txt)
![screenshot](https://user-images.githubusercontent.com/38939831/50469969-ce056200-09e9-11e9-889d-f08bb2bea1e4.png)

-

**Comment by CatchTheDog** [comment]
@alexandrudima  the vscode screenshot.
![qq 20181227151347](https://user-images.githubusercontent.com/38939831/50470045-1755b180-09ea-11e9-9758-9387e99daad1.png)

**Comment by egamma** [comment]
@CatchTheDog it looks like in the editor the characters are rendered properly. The problem shows up when you run the program. The launching and running the program is not done by the VS Code itself but by the Java extension.

This looks related to https://github.com/Microsoft/vscode-java-debug/pull/484, please follow-up on this issue.
