### ISSUE TITLE
In the visual studio code, a malfunction occurs when i input korean

### ISSUE THREAD

**Issue by chulpyo** [Microsoft/vscode#65526]
I use visual studio code release 1.30.0 

After update, The upper line is copied when [i type korean and press any other keys](https://i.stack.imgur.com/qZTEA.png)

**Comment by alexandrudima** [comment]
@chulpyo What OS are you using?

**Comment by rebornix** [comment]
@chulpyo can you help try our Insiders version, which updates to Electron 3.0 and see if you can still reproduce?
