### ISSUE TITLE
Resolve component's properties and methods inside PUG Angular templates

### ISSUE THREAD

**Issue by Rush** [Microsoft/vscode#65521]
I got the idea from a bug report I found on the Webstorm bug tracker - -https://youtrack.jetbrains.com/issue/WEB-35848 - it seems this feature works fine in the latest version of Webstorm

The feature request is simple - when editing PUG templates VS Code should provide validation for component names, component attributes the same as it works for HTML templates.

**Comment by octref** [comment]
This support should come from the angular extension.

**Comment by octref** [comment]
> so can any template engine plugin export its "attributes" metadata in a way for the Angular plugin to consume? or does Angular plugin need to explicitly implement support for each template engine?

That's up to the Angular extension's choice. You should open issue and engage here: https://github.com/angular/vscode-ng-language-service/issues, although that repo doesn't seem to be actively maintained anymore...
