### ISSUE TITLE
after updating vscode my computer crash and vscode cannot launch anymore

### ISSUE THREAD

**Issue by Soo-Q6** [Microsoft/vscode#65520]
- VSCode Version: version 1.30.0
- OS Version: windows 10 pro 1809

Steps to Reproduce:

1. my vscode old version was version 1.30.0 and today there was a new version 1.30.1 and i update it
2. then after the update installed my system crash (blue screen)
3. then i reboot my computer and found that vscode cannot launch anymore. here is the error
![image](https://user-images.githubusercontent.com/14860771/50323499-d1de4380-0514-11e9-9268-a0f323846dd5.png)
4. launch code in powershell:
![image](https://user-images.githubusercontent.com/14860771/50323515-f3d7c600-0514-11e9-8178-f75415ddc784.png)

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Does it work if you reinstall VS Code from scratch?
