### ISSUE TITLE
Cannot open wrapped link in terminal

### ISSUE THREAD

**Issue by cncolder** [Microsoft/vscode#65525]
- VSCode Version: 1.30.1
- OS Version: OSX 10.14.2

Steps to Reproduce:

1. Command + Click on a link on output below. This link wrap two lines. (`yarn outdated`)
2. It will open `https://github.com/gaearon/react-hot-lo` in my browser
```shell
react-hot-loader 4.6.1 4.6.3 4.6.3 myproj devDependencies https://github.com/gaearon/react-hot-lo
ader
```

Does this issue occur when all extensions are disabled?: Yes/No

<img width="1025" alt="2018-12-21 13 15 31" src="https://user-images.githubusercontent.com/127009/50325926-89c61d80-0522-11e9-99d9-69fcfd634457.png">

**Comment by Tyriar** [comment]
Did you resize the terminal after the link was printed? Also can you reproduce this in the [Insiders build](https://code.visualstudio.com/insiders), we made some changes in this area recently?
