### ISSUE TITLE
Open  folder in new window

### ISSUE THREAD

**Issue by mil-ast** [Microsoft/vscode#65533]
Issue Type: <b>Bug</b>

Open VS Code (№1). Menu > New window. In the new window (№2) Menu > Open folder.
New folder opens in window №1

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3306)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (5.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.1.0
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.4.4
gitlens|eam|9.2.2
tslint|eg2|1.0.42
vscode-language-pack-ru|MS-|1.30.2
Go|ms-|0.8.0
vscode-docker|Pet|0.4.0
vscode-gitextensions|pmi|0.8.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by sbatten** [comment]
@mil-ast I cannot reproduce this issue. Can you verify your `window.titleBarStyle` setting? Also, can you verify that window No. 1 does not already have the folder you are selecting open?

**Comment by mil-ast** [comment]
> @mil-ast I cannot reproduce this issue. Can you verify your `window.titleBarStyle` setting? Also, can you verify that window No. 1 does not already have the folder you are selecting open?

window.titleBarStyle = custom
Noticed that the problem is reproduced if the window №.1 is maximized

**Comment by sbatten** [comment]
@mil-ast still no luck, did you confirm that window No.1 did not already have the folder open? In this case, VS Code will switch focus to the already open folder.

**Comment by mil-ast** [comment]
[Youtube](https://youtu.be/p-ORdtrYxyQ)

**Comment by mistralol** [comment]
I Also Have this problem.

* I start vscode. ref: win1
* Open a project "folder1"
* File -> New Window (ref win2)
* Win2 -> File -> Open Folder -> "Folder2"
* "Folder2" Folder opens in first window.
* Win2 still left with no open folder.

Started at some point in November / December. Just updated this morning still happening. See exactly the same thing as the youtube video that @mil-ast had uploaded.

Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-42-generic

Current workaround Setting

"window.openFoldersInNewWindow": "on"

Means I can open the new folder from the first window and it will be opened in a new window.

**Comment by matjaeck** [comment]
I can confirm this issue on Linux. If you open a new window while another window is maximized in the background and then open a new folder in the not maximized, focused new window, the new folder will open in the maximized window and not in the new window where File -> OpenFolder was clicked.

**Comment by sbatten** [comment]
@matjaeck thanks for the added info, I thought for sure that was going to nail it down, but I still cannot repro on Ubuntu 16.04 or 18.04

**Comment by sbatten** [comment]
just out of curiosity, does this reproduce with `window.titleBarStyle` set to `native`

**Comment by maskarb** [comment]
@sbatten I can reproduce this issue with `window.titleBarStyle` set to `native`.

My environment:
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

**Comment by sbatten** [comment]
@aeschli @chrmarti pinging you guys just by git blaming the `Open Folder Action`. I was unable to reproduce this on any of my Linux machines but I don't think it is related to the menu itself since it reproduces with native

**Comment by chrmarti** [comment]
@bpasero Recently fixed an issue in this area: #65773.

**Comment by matjaeck** [comment]
The bug is fixed in the current insiders build available at https://code.visualstudio.com/insiders/.
