### ISSUE TITLE
默认的亮色主题中html页面蓝色太多，你们是要亮瞎我的眼睛吗

### ISSUE THREAD

**Issue by netmou** [Microsoft/vscode#65530]
Issue Type: <b>Bug</b>

默认的亮色主题中html页面蓝色太多，你们是要亮瞎我的眼睛吗

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.10
vs-color-picker|lih|0.7.0
material-icon-theme|PKi|3.6.2
vscode-input-sequence|tom|0.2.0

(3 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@netmou I am sorry, the development language of VS Code is in English. Can you please create a new issue in English?

**Comment by netmou** [comment]
the color   attr's value width html file in editor is blue , that feel very bad
