### ISSUE TITLE
Wrong Chinese Translation / 错误中文翻译

### ISSUE THREAD

**Issue by xiaoski** [Microsoft/vscode#65534]
Issue Type: <b>Bug</b>

There is a wrong translation item in settings.
ENG:
Settings -> Text Editor -> Formatting
CHN:
设置 -> 文本编辑器 -> 正在格式化

The correct translation of "Formatting" should be "格式化". The "Formatting" is a noun, not a verb in the progressive form.
"Formatting"的正确翻译应该为"格式化".

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.99GB (10.64GB free)|
|Process Argv|--folder-uri file:///d%3A/code/Saturn/MA5800|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
markdown-preview-github-styles|bie|0.1.4
vscode-hexo|cod|1.0.1
bracket-pair-colorizer-2|Coe|0.0.25
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
xml|Dot|2.4.0
gitlens|eam|9.2.2
tslint|eg2|1.0.42
gc-excelviewer|Gra|2.1.26
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.1
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
wecode|NW-|6.0.4
material-icon-theme|PKi|3.6.2
java|red|0.36.0
vscode-icons|rob|8.0.0
highlight-words|rsb|0.0.8
markdown-preview-enhanced|shd|0.3.11
vscode-hexdump|sle|1.7.2
yang-vscode|typ|1.7.0
mib|Ver|0.0.4
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.2.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.12.0
vscode-maven|vsc|0.12.1
vscode-todo-highlight|way|1.0.4

(9 theme extensions excluded)

</details>

**Comment by Joelism** [comment]
I think there're some issues with the transition of the translation platform to Microsoft Localization Community (MLCP), some of the previously translated strings are changed to incorrect ones, including this.

Additionally, there're some term changes that did't touch all instances, leading to more inconsistencies.

**Comment by xiaoski** [comment]
> 你应该去看看翻译插件的介绍 @xiaoski
没注意翻译是插件形式提供的。 看了下原来有个社区翻译平台的
