### ISSUE TITLE
Cmd + a does not select all in input box

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#65537]
Open any input box, for example quick open, or find widget. Press cmd+a, no text gets selected.
Notice that the menu item gets highlighted on mac, so the Select All command does get executed it just does not have any effect
This is a regression in the last 24hrs, thus assigning to this milestone.

Assigning to you Ben since you did the most commits in the last 24hrs sorry

**Comment by usernamehw** [comment]
Duplicate of #65456 ?

**Comment by isidorn** [comment]
Yeah duplicate, thanks a lot
