### ISSUE TITLE
Revisit state service usage for menu bar cache

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#65535]
I am a little bit worried that we [store](https://github.com/Microsoft/vscode/blob/6e923a9df83392053d09d803044ddc826b2ba0bb/src/vs/platform/menubar/electron-main/menubar.ts#L188) the menu bar cache too often on the main side (which always will result in a sync flush to disk of the entire state). Especially if I think about the menu becoming more dynamic soon (e.g. when we respect the active editor). Some thoughts:
* can we only store the state on shutdown instead of always when it changes?
* if that is not possible, could we remove properties that are the most dynamic ones, like the enablement? it seems to me that enablement is nothing we can properly restore anyways because it changes on a startup

**Comment by sbatten** [comment]
there was work done to reduce the amount that the menu updates and it is rather quiet. Unless you feel strongly, I will not investigate further.
