### ISSUE TITLE
GUI disturbed

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#65544]
Issue Type: <b>Bug</b>

In the latest VS Code Insider the graphics of the GUI is disturbed, like looking at a VR picture. As all other apps and Visual Studio do not have that I assume its a bug which was recently introduced.

System: Lenovo T520 notebook with Nvidia 4200M graphics.

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz (8 x 2193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Pummelchen** [comment]
![pix](https://user-images.githubusercontent.com/10000402/50336781-e7e50780-0506-11e9-9ae4-daad12009a11.png)

**Comment by Pummelchen** [comment]
This happens with VSC runs on the notebook display, once I drag the app to the external monitor driven by Displayport which runs over the Nvidia card, than VSC looks just normal. Once I drag it back, its disturbed. So its an issue with the Intel graphics drivers and a new bug in VSC insider,
