### ISSUE TITLE
Watch for deletes in files opened outside workspace

### ISSUE THREAD

**Issue by varunagrawal** [Microsoft/vscode#6554]
- VSCode Version: `1.1.0`
- OS Version: `OSX El Capitan Version 10.11.4`

Steps to Reproduce:

1. Create directory X
2. In X, create file, `test1.cs`
3. Open test1.cs in VS Code
4. In a terminal, run `mv test1.cs ..`
5. Switch to VS Code and edit test1.cs.
6. VS Code creates test1.cs again rather than raising an error.

**Comment by bpasero** [comment]
@varunagrawal Code should move the file as well to its new location unless maybe the file is dirty. Can you attach a video how this behaves for you?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by varunagrawal** [comment]
Hi @bpasero.
I apologize for the delay in responding. I have created the video and you can find it here: https://youtu.be/WlOKSGDQ9rg

As you can see, I create a folder and a file, then open the file in Code. When I move the file to a different folder from the terminal, VS Code does not throw any (clear) warning and on saving the file, creates a duplicate. I am not sure if this is intended functionality or a bug. I would like to see at least a message indicating that the file has moved so that I know I am saving a new copy (similar to how Notepad++ handles it).

**Comment by varunagrawal** [comment]
As you mentioned, it does not save the file to disk unless it is dirty, but neither does it update itself to show that the file has moved. The location bar continues to display the X folder as the location rather than the parent VSCodeTest folder.

**Comment by bpasero** [comment]
Thanks, this is an issue with our file watcher (and should be addressed with https://github.com/Microsoft/vscode/issues/6440). We currently do not detect file deletes (or moves as in this case) for files that are not part of the folder opened, but outside.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4870
