### ISSUE TITLE
Add a workspace option to enforce typescript.tsdk

### ISSUE THREAD

**Issue by ashi009** [microsoft/vscode#65546]
We specified typescript.tsdk in workspace config, but it doesn't apply automatically if a user has another version installed globally (eg. npm install -g). This makes a team-wise update really difficult. As we have to ask everyone to manually pick the "right" version.

Please add an option to enforce tsdk setting in the workspace.

**Comment by oBusk** [comment]
If the workspace settings has the "typescript.tsdk" specified, why would VSCode decide to use the global? 

Could even argue that clicking the version to select which TS version to use (global or workspace) should update the workspace settings.

**Comment by ashi009** [comment]
https://github.com/Microsoft/vscode/issues/30069#issuecomment-312732928 doesn't make sense to me.

The security is assumed by asking the user to manually select the tssdk to use, however, the user has no way to determine if the one in the workspace is safe (also true for any npm package) and the opt-in process is not promoting the potential security risk for using the one in the workspace.  Therefore, this manual step doesn't guarantee the safety.

IMHO, a few better approachs are:

- adding a new option for specifying the version of tssdk to use, and let vscode download that -- from a trusted source
- let vscode could verify the checksum of tssdk files and prompt the user if the one specified is unknown

At least vscode could prompt the user when tssdk is specified in workspace config, and let the user switch the tssdk directly.

**Comment by mjbvz** [comment]
Fixed by #95566

To verify, see #95566 for details on the new `typescript.enablePromptUseWorkspaceTsdk` setting
