### ISSUE TITLE
Goto Symbol is not working for json

### ISSUE THREAD

**Issue by abdulkareemnalband** [Microsoft/vscode#65545]
Issue Type: <b>Bug</b>

1. open any json file
2. press `ctrl+shift+o`
3. type any symbol name
4. No results are found
![image](https://user-images.githubusercontent.com/3139353/50336886-52ad3780-0535-11e9-8759-6e81e965a2a1.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.46GB (1.76GB free)|
|Process Argv|D:\repo\Decisions.Web\web.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.0.0
ng-template|Ang|0.1.11
angulardoc-vscode|Ang|6.1.3
scratchpads|bue|0.0.5
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
mustache|daw|1.1.1
gitlens|eam|9.2.3
EditorConfig|Edi|0.12.5
docthis|joe|0.7.1
csharpfixformat|Leo|0.0.76
csharp|ms-|1.17.1
references-view|ms-|0.0.21
vsliveshare|ms-|0.3.1071
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
debugger-for-edge|msj|1.0.6
vscode-template-literal-editor|pli|0.9.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.1.0
gitconfig|sid|2.0.0
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.17.1

</details>

**Comment by abdulkareemnalband** [comment]
@jrieken 
any file with empty string key

```json
{
    "":"abcd",
    "xyz":"pqrs"
}

```

**Comment by jrieken** [comment]
Thanks
