### ISSUE TITLE
Python Interactive's operator icons don't show up after holiday season update on Insider version

### ISSUE THREAD

**Issue by AeneasZhu** [Microsoft/vscode#65540]
![annotation 2018-12-20 190214](https://user-images.githubusercontent.com/44701446/50333940-bfc6ca00-0541-11e9-8776-3f23153f1d8c.jpg)

After the holiday season update,  Python Interactive icons don't show up any more. And I don't think it's the extension's question.

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/vscode-python/issues/3775
