### ISSUE TITLE
vscode remains in high contrast after back in windows normal contrast

### ISSUE THREAD

**Issue by Xarkam** [Microsoft/vscode#65554]
Issue Type: <b>Bug</b>

Hello,

I went in high contrast in windows. vscode is also in high contrast. (SHIFT + ALT + PrintScreen)

When I returned to normal contrast in windows (SHIFT + ALT + PrintScreen), vscode remains high contrast.

I have to manually reset the vscode theme.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (9.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-caniuse|aka|0.5.3
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
docs-article-templates|doc|0.1.4
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.2.1
docs-preview|doc|0.3.16
githistory|don|0.4.4
gitlens|eam|9.2.3
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.42
LogFileHighlighter|emi|2.4.2
prettier-vscode|esb|1.7.3
vscode-solution-explorer|fer|0.3.0
dotnet-test-explorer|for|0.6.0
minify|Hoo|0.3.0
rest-client|hum|0.20.4
output-colorizer|IBM|0.1.2
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.2
restructuredtext|lex|94.0.0
vscode-discord|max|1.0.2
DocFX|ms-|0.1.3
mssql|ms-|1.4.0
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.8.0
PowerShell|ms-|1.10.2
typescript-javascript-grammar|ms-|0.0.47
vsliveshare|ms-|0.3.1071
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.3
vscode-code-outline|pat|0.2.1
vscode-docker|Pet|0.4.0
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.2
vscode-icons|rob|8.0.0
sass-indented|rob|1.4.9
code-settings-sync|Sha|3.2.4
trailing-spaces|sha|0.2.11
html5-boilerplate|sid|1.0.3
code-spell-checker|str|1.6.10
code-spell-checker-french|str|0.1.3
msbuild-project-tools|tin|0.2.51
cordova-tools|vsm|1.6.0
vscode-wakatime|Wak|1.2.5
quokka-vscode|Wal|1.0.174
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by bpasero** [comment]
I cannot reproduce, for me the HC theme enables and disables when I switch in and out. @Xarkam anything special how you change the theme?

**Comment by Xarkam** [comment]
Hello,
I just did a test right now. The HC theme enables and disables when I switch in and out.
Could an third application have caused this malfunction?

I'll keep that in view after my vacation.
