### ISSUE TITLE
Json settings interface for workspace and directory

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#65563]
In the recent insiders version, I have noticed that `settings.json` for workspace and directories can't be easily find via `ctrl+,` or the `setting` menu term

- VSCode Version: 1.31.0-insider (system setup)
  - Commit: e02e44464c02d617b98d0a3265bf5efef7794436
  - Date: 2018-12-21T06:20:35.852Z
- OS Version: Windows_NT x64 10.0.18305

Steps to Reproduce:

1. Add `"workbench.settings.editor": "json"` in the settings
2. Press `ctrl+,`
3. You only find the user's settings but not workspace and directories. There were a tab for them before.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by usernamehw** [comment]
```json
"workbench.settings.useSplitJSON": true,
```

**Comment by Stone-Zeng** [comment]
Thank you very much @usernamehw
Duplicate: #64932, #65399
