### ISSUE TITLE
Plugin Loading Status

### ISSUE THREAD

**Issue by mikecarr** [Microsoft/vscode#65562]
Upon opening VisualStudio Code it could take several minutes for all plugins to load

I would like to see an easy to see status of all plugin loading progress. During loading it is difficult to tell if a plugin is broke or just taking a long time to load.

Could be as simple as Yellow and Green light, yellow loading, Green all plugins loaded, Red plugins loaded with errors

**Comment by alexandrudima** [comment]
You can run `F1 > Developer: Show Running Extensions`. This will help pinpoint which extension are consuming a lot of time to get activated and perhaps you can reach out to the extension author directly.
