### ISSUE TITLE
Node debug attach processId property not accepting custom commands

### ISSUE THREAD

**Issue by JohnsonMG** [microsoft/vscode#65566]
I am using PM2 to run many node processes and want to setup a debug configuration to attach to running processes that were not started in debug mode. As recommended in [this feature request](https://github.com/Microsoft/vscode/issues/50378) I created my own extension to handle this with a custom command that allows me to select a pid from a dropdown.

No matter how simple I make the command however, even just returning a string synchronously, I get the following error:
![image](https://user-images.githubusercontent.com/11714211/50357599-71570280-0524-11e9-9c09-c952989bbe1f.png)

I have tested this command with other debug configurations (e.g. chrome debugger) and it works totally fine, processId seems to have some type validation which is rejecting it.

Extension package.json
```{
    "name": "pm2support",
    "displayName": "pm2Support",
    "description": "Support for pm2 processes",
    "version": "0.0.1",
    "engines": {
        "vscode": "^1.30.0"
    },
    "categories": [
        "Other"
    ],
    "activationEvents": [
        "onCommand:pm2Support.getPids"
    ],
    "main": "./out/extension",
    "contributes": {
        "commands": [{
            "command": "pm2Support.getPids",
            "title": "Get pm2 pids"
        }],
        "debuggers": [
          {
            "type": "node",
            "variables": {
              "PickPm2Process": "pm2Support.getPids"
            }
          },
          {
            "type": "chrome",
            "variables": {
              "PickPm2Process": "pm2Support.getPids"
            }
          }
        ]
    },
    "scripts": {
        "vscode:prepublish": "yarn run compile",
        "compile": "tsc -p ./",
        "watch": "tsc -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install",
        "test": "yarn run compile && node ./node_modules/vscode/bin/test"
    },
    "devDependencies": {
        "typescript": "^3.1.4",
        "vscode": "^1.1.25",
        "tslint": "^5.8.0",
        "@types/node": "^8.10.25",
        "@types/mocha": "^2.2.42"
    }
}
```

extension.ts: 
```
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import * as fs from 'fs';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {
    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    context.subscriptions.push(vscode.commands.registerCommand('pm2Support.getPids', async ():Promise<string> => {
        // The code you place here will be executed every time your command is executed

        let pidOptions: vscode.QuickPickItem[] = [];
        var pidFiles = fs.readdirSync('/Users/gavinjohnson/.pm2/pids');

        // Pull pids from files
        pidFiles.forEach(path => {
          var contents = fs.readFileSync('/Users/gavinjohnson/.pm2/pids/' + path);
          pidOptions.push({
            label: path,
            detail: contents.toString(),
          });
        });
        
         let pickPromise = vscode.window.showQuickPick(pidOptions);
         let pid = await pickPromise.then(pick => {
            if(pick !== undefined) {
              return String(pick.detail);
            } else {
              return "";
            }
         });
         vscode.window.showInformationMessage(pid);
         return pid;
       }));
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

launch.json: 
```
{
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "processId": "${command:PickPm2Process}"
    },
```

**code --version :** 
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64

**node -v:**
v8.11.3

**ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54**

**Comment by weinand** [comment]
@JohnsonMG does it work if you use the command ID directly?
e.g.
```
{
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "processId": "${command:pm2Support.getPids}"
},
```

**Comment by JohnsonMG** [comment]
> @JohnsonMG does it work if you use the command ID directly?
> e.g.
> 
> ```
> {
>       "type": "node",
>       "request": "attach",
>       "name": "Attach to Process",
>       "processId": "${command:pm2Support.getPids}"
> },
> ```

Using the command ID directly results in the same error message.
I am happy to supply more information, if you could let me know exactly what information is missing.

Do commands work for you in the processId field? I can't seem to use any commands, let alone my custom one.

**Comment by JohnsonMG** [comment]
@weinand Does this still need more information? Please advise on what you would like if so.

**Comment by JohnsonMG** [comment]
@weinand Since there has been no movement on this I decided to poke around and found this:
https://github.com/microsoft/vscode-node-debug/blob/3bb7e131ba706ecb70bd9ae68e6994256c0e4f2a/src/node/extension/processPicker.ts#L49

It looks like the attach handler has hardcoded in a check for the string '${command:PickProcess}' rather than running any passed in command.

For anyone attempting to do something similar, I got around this by having my custom extension just start a debugging session itself, rather than resolving a string.
```
const config: vscode.DebugConfiguration = {
            "type": "node",
            "request": "attach",
            "name": "Attach to PM2 ProcessId",
            "processId": pick.detail,
          };

          vscode.debug.startDebugging(undefined, config).then(...
```
Where pick.detail is the showQuickPick result

**Comment by weinand** [comment]
The hardcoded check for '${command:PickProcess}' will become obsolete in the January release when we release the new 'resolveDebugConfigurationWithSubstitutedVariables' hook that provides access to substituted variables. Please see https://github.com/microsoft/vscode/issues/87450.

**Comment by weinand** [comment]
@connor4312 I have removed the code that resolves command variables (e.g. the process picker) in `resolveDebugConfiguration` and now let VS Code do the resolving. This makes it possible to use any command variable for the `processId` attribute.

**Comment by connor4312** [comment]
Sounds good, updated js-debug similarly.
