### ISSUE TITLE
NPM script explorer running a script from the hover does not work

### ISSUE THREAD

**Issue by gaoyia** [microsoft/vscode#65561]
**Edited by @egamma**

On windows open a package.json file
- hover over a script in the `scripts` section
- click on the `Run Script` link in the hover
![image](https://user-images.githubusercontent.com/172399/66652520-31d5e000-ec36-11e9-8f00-22825d56aa96.png)
-> script is not run on 

This works fine on Mac, only repros on Windows.

-------

Issue Type: <b>Bug</b>

nodejs  file 'package.json' 

mouse hover   "scripts": {***}  then show run tips

mouse left click can't run script,

but right click  it's worked

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (4.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.30.2
vetur|oct|0.14.3

</details>

**Comment by egamma** [comment]
@gaoyia can you please share your package.json. I cannot reproduce this.

**Comment by gaoyia** [comment]
{
  "name": "iview-admin",
  "version": "2.0.0",
  "author": "Lison<lison16new@163.com>",
  "private": false,
  "scripts": {
    "dev": "vue-cli-service serve --open",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "clipboard": "^2.0.0",
    "codemirror": "^5.38.0",
    "countup": "^1.8.2",
    "cropperjs": "^1.2.2",
    "dayjs": "^1.7.7",
    "echarts": "^4.0.4",
    "html2canvas": "^1.0.0-alpha.12",
    "iview": "^3.2.2",
    "iview-area": "^1.5.17",
    "js-cookie": "^2.2.0",
    "simplemde": "^1.11.2",
    "sortablejs": "^1.7.0",
    "tree-table-vue": "^1.1.0",
    "v-org-tree": "^1.0.6",
    "vue": "^2.5.10",
    "vue-i18n": "^7.8.0",
    "vue-router": "^3.0.1",
    "vuedraggable": "^2.16.0",
    "vuex": "^3.0.1",
    "wangeditor": "^3.1.1",
    "xlsx": "^0.13.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-plugin-unit-mocha": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "@vue/eslint-config-standard": "^3.0.0-beta.10",
    "@vue/test-utils": "^1.0.0-beta.10",
    "chai": "^4.1.2",
    "eslint-plugin-cypress": "^2.0.1",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "lint-staged": "^6.0.0",
    "mockjs": "^1.0.1-beta3",
    "vue-template-compiler": "^2.5.13"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.js": [
      "vue-cli-service lint",
      "git add"
    ],
    "*.vue": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}

**Comment by gaoyia** [comment]
en：In fact, this is true of all projects.
cn：事实上，所有项目都是如此

**Comment by gaoyia** [comment]
and I uninstalled all the extensions for this test

**Comment by gaoyia** [comment]
[onedrive-video:https://1drv.ms/v/s!AuuXkvrPNO7djWpCZq7EJdP2KzxJ?e=DGWDzF](https://1drv.ms/v/s!AuuXkvrPNO7djWpCZq7EJdP2KzxJ?e=DGWDzF)

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by gaoyia** [comment]
@egamma

**Comment by egamma** [comment]
@gaoyia thanks for the recording. I think I'm doing the same steps but it works for me. Running the script fails since I do not have the tools installed, but the script is invoked.

![screencast 2019-09-03 12-02-12](https://user-images.githubusercontent.com/172399/64164095-c7659f00-ce42-11e9-8501-d2c1a19f804b.gif)

Do you have the setting below disabled:

![image](https://user-images.githubusercontent.com/172399/64164276-32af7100-ce43-11e9-8c03-70ccca4fbf0f.png)

**Comment by gaoyia** [comment]
nope

![QQ截图20190427094420](https://user-images.githubusercontent.com/17539193/64166862-8e492100-ce7a-11e9-9260-7d2cd146462f.png)

**Comment by gaoyia** [comment]
nope，

![微信截图_20190903184144](https://user-images.githubusercontent.com/17539193/64166917-b59fee00-ce7a-11e9-9b0d-e3c3e3e66cda.png)

**Comment by gaoyia** [comment]
en:   I tried to reinstall VScode ( Stable Build Edition ) in the new system, but it still didn't work.
cn：我试着在新系统中重新安装VScode(Stable Build Edition)，但仍然不行

maybe try Win10_CN_X64_1903?

**Comment by gaoyia** [comment]
@egamma nodejs v10.16.3 LTS

**Comment by egamma** [comment]
@gaoyia I can reproduce this behaviour on Win 10 machine


Script is executed when run from the context menu
![image](https://user-images.githubusercontent.com/172399/66652576-5631bc80-ec36-11e9-8362-05121dd7a2b3.png)

Script is not executed when clicking the hover
![image](https://user-images.githubusercontent.com/172399/66652520-31d5e000-ec36-11e9-8f00-22825d56aa96.png)

**Comment by egamma** [comment]
To analyze the issue:
- set a break point in `extensions/npm/src/scriptHover.ts` in `runScriptFromHover`
- inspect the `documentUri` received as an argument

The URI encoded in the hover in `createMarkDonwLink` is:
![image](https://user-images.githubusercontent.com/172399/66684688-e7c31d80-ec7a-11e9-9102-5852c539025e.png)

The URI received in `runScriptFromHover` is:
![image](https://user-images.githubusercontent.com/172399/66684812-2a84f580-ec7b-11e9-8391-bc4a1882f00e.png)

Notice that the ':' is not encoded, as a consequence the call to `getWorkspaceFolder` doesn't find a corresponding workspace.

The suspicion is that the URI is decoded once too many. When removing the call to `decodeUriComponent` in https://github.com/microsoft/vscode/blob/78fd1e5ec2efa9bd2656f1079d9d9ed88b7e39a0/src/vs/workbench/api/common/extHostTypeConverters.ts#L286 then the link works correctly.

**Comment by jrieken** [comment]
Yeah, maybe that `decode`-call is bad. My theory is that we receive the data (JSON-ified uri), decode it (which decodes the colon), and then we pass the data to `Uri.revive` (which blindly trusts the data)

**Comment by jrieken** [comment]
Yeah, the double decode happens because `Uri.parse` already decodes. Later, when the query-part is massaged we decode again and that's one too much.

**Comment by egamma** [comment]
@jrieken I wonder whether your fix impacts this code and could break it? https://github.com/microsoft/vscode/blob/2fe62e7dfec6fcff6e037e5fbc12082d43d98c0e/extensions/markdown-language-features/src/commands/openDocumentLink.ts#L30

**Comment by jrieken** [comment]
It should not, but I'd accept repo steps :-). This is a bit of a fiddle because we try to detect and extract uris for the uri transformer. Simple markdown-uris (links/images) are easy but [`_uriMassage`](https://github.com/microsoft/vscode/blob/6b0613aabacbce9dc8e96360288706c41d0345bd/src/vs/workbench/api/common/extHostTypeConverters.ts#L280) is called for query-arguments of such uris. There we rely on `JSON.parse`  which should only catch uris on which `toJSON` has been called. In above sample `toString` is called and it should be unnoticed before and after my change.

**Comment by egamma** [comment]
@jrieken makes sense thanks.

>It should not, but I'd accept repo steps :-)

I failed on this...
