### ISSUE TITLE
Settings sharing via login account

### ISSUE THREAD

**Issue by STaRDoGG** [microsoft/vscode#65567]
Issue Type: <b>Feature Request</b>

I run VS Code on several machines (vm's, etc.) and it can get cumbersome having to keep all of my extensions, customizations, etc., the exact way I like to use Code, in sync with each other. Especially painful to have to manually find, install, and configure eveything on a fresh install.

Would love to have something like Chrome/Firefox/Windows's online accounts that automatically sync everything when you login to the acct via the in-app account.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Astrantia** [comment]
NO!

**Comment by sandy081** [comment]
/duplicate

#2743
