### ISSUE TITLE
c++ enum class syntax

### ISSUE THREAD

**Issue by bretzel** [Microsoft/vscode#65574]
Issue Type: <b>Bug</b>

"enum class xclass: uint8_t{"
status = 1,
error,
notice,
//...
};

"xclass" and "uint8_t are "red squigled" 

"xclass" : incomplete class is not allowed
"uint8_t": identifier is not defined ( even if #include <stdint.h> )

VS Code version: Code - OSS 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T22:23:23.072Z)
OS version: Linux x64 4.19.11-arch1-1-ARCH

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools-helper|mad|0.2.1
cpptools|ms-|0.20.1
vscode-icons|rob|8.0.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by alexandrudima** [comment]
Can you please create the issue directly against the extension at https://github.com/Microsoft/vscode-cpptools ?
