### ISSUE TITLE
Invalid syntax highlight in clojure language with #"\\" regexp

### ISSUE THREAD

**Issue by narma** [Microsoft/vscode#6557]
- VSCode Version: 1.1.1
- OS Version:  OS X 10.11.4

Steps to Reproduce:

1. change language mode to clojure in editor
2. Write `#"\\` regexp somewhere, for ex. `'(#"\\" 3 "" 4 5)` or 
```clojure
(defn decode-embed-json
  [^String s]
  (-> s
      (string/replace #"\\" "")
      json/read-str))
```
(even github has this issue, lol)

3. Instead of proper hightlighting we see this 
![image](https://cloud.githubusercontent.com/assets/91045/15409960/1a7accbe-1e39-11e6-8e1a-40b609befa99.png)

**Comment by aeschli** [comment]
This issue was moved to mmcgrana/textmate-clojure#4
