### ISSUE TITLE
Sass TM language: `content`, `cursor`, `backdrop-filter` properties

### ISSUE THREAD

**Issue by atomiks** [Microsoft/vscode#65573]
- VSCode Version: 1.30.1
- OS Version: macOS 10.14.1

1. The Sass TM language is scoping these properties with `entity.name.tag` instead of `support.type.property-name`:

- `cursor`
- `content`

Which makes them a different color from other properties

2. The regular CSS and Sass languages are missing the `support.type.property-name` scope for the `backdrop-filter` property.

**Comment by usernamehw** [comment]
The first part is a duplicate of https://github.com/atom/language-sass/issues/226

**Comment by alexr00** [comment]
This issue was moved to atom/language-sass#264
