### ISSUE TITLE
how can i bind a key to another key?

### ISSUE THREAD

**Issue by cyantedyu** [Microsoft/vscode#65576]
I want to globally map a key to another key,
how can i make it?
Thanks for reply in advance.

**Comment by alexandrudima** [comment]
@ichirika What do you mean? Would you like to change keybinding for actions or would you like to change the produced character when pressing a certain key ?

**Comment by ichirika** [comment]
> 
> 
> @ichirika What do you mean? Would you like to change keybinding for actions or would you like to change the produced character when pressing a certain key ?

Thanks for your reply,
I want to globally map key like 
"Ctrl+F for pressing [key rightArrow]", "Ctrl+G for pressing [key Esc]",

**Comment by alexandrudima** [comment]
@cyantedyu

Here is how you can bind <kbd>Ctrl</kbd>+<kbd>F</kbd> to executing `cursorLeft`, which is the default binding for <kbd>ArrowLeft</kbd>. You can edit all keybindings in your `keybindings.json`.

```js
{
	"key": "ctrl+f",
	"command": "cursorLeft",
	"when": "textInputFocus"
}
```

Please read our extensive documentation at https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by cyantedyu** [comment]
> 
> 
> @cyantedyu
> 
> Here is how you can bind Ctrl+F to executing `cursorLeft`, which is the default binding for ArrowLeft. You can edit all keybindings in your `keybindings.json`.
> 
> ```js
> {
> 	"key": "ctrl+f",
> 	"command": "cursorLeft",
> 	"when": "textInputFocus"
> }
> ```
> 
> Please read our extensive documentation at https://code.visualstudio.com/docs/getstarted/keybindings

Thanks for your reply, This is not the issue,
actually there's also keybinding for ctrl+f in my keybinding json,
but i can't use ctrl+f in quick open,
so i want sth to globally translate a key to another key,
so that i can use ctrl+f, then automatically translated to the arrow key,
