### ISSUE TITLE
Snippets being suggest all the time.

### ISSUE THREAD

**Issue by faldor20** [Microsoft/vscode#65577]
I am not onehundred percent sure this is actually a bug but i dont rember it ever being a problem before. it is especially bad with unity snippets installed. When i type something i get hoards of these snippet suggestions in pointless places. eg: variable names,  places that should take a variable or type. 

- VSCode Version: 1.30.1(user setup)
- OS Version: windows 10

Steps to Reproduce:

1. open c#(or any other code file i think)
2. type something like int or var to create a variable 
3. watch the intellisense suggest an if snippet  for the name.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Nothing has changed, snippets show in IntelliSense by default. Did the snippet extension update and now contain more snippets? Did you change the `editor.snippetSuggestions` setting?

**Comment by faldor20** [comment]
@jrieken Oh I guess it must have been an update to an extension. Context sensitive snippets would be nice to have though. Having piles of snippets showing up in pointless places is very annoying
