### ISSUE TITLE
MarkdownIt plugins (or Rules) called multiple times for one input

### ISSUE THREAD

**Issue by qjebbs** [Microsoft/vscode#65575]
- VSCode Version: Windows 7 & Mac 10.14 (Only these 2 Tested)

A user of my extension reports duplicate html elements in export markdown, I debug & find this issue as described in header. 

It doesn't affect the preview rendering, so I cannot tell the step to reproduce. But I can tell, it's reproducible when all extension (except mine) is disabled, and the issue is gone in extension debugging environment.

Please find more details here: https://github.com/qjebbs/vscode-markdown-extended/issues/28

PS: My extension uses VSCode Markdown render instance to provide WYSIWYG export

**Comment by qjebbs** [comment]
Not really, copy HTML used most in copy & paste to rich text editors, as I know, which could still render right result. Only matters if user cares about the excessive codes, or performance worries (for running many times)

**Comment by mjbvz** [comment]
We have two calls to markdown it:

* Render the markdown to html
* parse the markdown to a set of tokens

Markdown it has an internal render method that takes a list of tokens instead:

```js
md.renderer.render(tokens, md.options, {})
```

We could cache the tokens and use this api instead. Marking as help wanted. Here's where the two calls are: https://github.com/Microsoft/vscode/blob/fa5306d67bb934c42d206fb3c7e028dff00d530f/extensions/markdown-language-features/src/markdownEngine.ts#L96

**Comment by skprabhanjan** [comment]
@mjbvz , I am trying this one :)
