### ISSUE TITLE
Invisible element is focused when SCM split view is collapsed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#65585]
Repro:

1. Open SCM viewlet
2. Collapse git pane
3. Press shift+tab a few times and tab a few times, notice that there's an element that can be focused in between the 2 headers. `document.activeElement` points at this, which appears to be a tree inside the pane:

<img width="320" alt="screen shot 2018-12-21 at 10 19 20 pm" src="https://user-images.githubusercontent.com/2193314/50371382-a38d5200-056e-11e9-8b01-eaa63f8c65da.png">

**Comment by bpasero** [comment]
@joaomoreno PR https://github.com/Microsoft/vscode/pull/67548

**Comment by joaomoreno** [comment]
This applies to all panels.

**Comment by bpasero** [comment]
Oh wow, then I looked at the wrong place (https://github.com/Microsoft/vscode/blob/9606490e26f8cbe4d615305389d45e9b144ded7c/src/vs/workbench/browser/parts/views/customView.ts#L319). 

@sandy081 this would probably be a candidate for moving into a reusable space if possible.

**Comment by sandy081** [comment]
Every view has to show/hide their widgets on visibility change. This will be too much to abstract as each view has its own widgets like tree, list etc.,

**Comment by bpasero** [comment]
@sandy081 well, now that I am thinking about it, why is the splitview not hiding the body on collapse, wouldn't that be the best general solution?

**Comment by joaomoreno** [comment]
Exactly what I came here to say: @bpasero is right. The Panel should take its own body out of the DOM when hidden.
