### ISSUE TITLE
My visual studio code work slowly

### ISSUE THREAD

**Issue by NikhilRajPandey** [Microsoft/vscode#65582]
Issue Type: <b>Performance Issue</b>

When I am writing a python program and importing a module then visual studio code get langing and then it work very slow

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.13.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Dual  CPU  E2220  @ 2.40GHz (2 x 1600)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|5, 3, 3|
|Memory (System)|2.93GB (0.44GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   153	  2277	code main
    0	    42	  2279	   zygote
    0	   120	  2359	     shared-process
    0	   258	  2539	     window (utils.py - visualcodeproject - Visual Studio Code)
    0	     3	  2559	       /bin/bash
    0	   111	  2570	       extensionHost
    0	    36	  2621	         /usr/bin/python3 completion.py
    0	    39	  2625	           /usr/bin/python3 lib/python/jedi/evaluate/compiled/subprocess/__main__.py lib/python
    0	    60	  2582	       watcherService
    0	     3	  3402	       /bin/bash
    5	   108	  3669	     window (Issue Reporter)
    0	     0	  3687	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  3688	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (utils.py - visualcodeproject - Visual Studio Code)
|    Folder (visualcodeproject): 8 files
|      File types: mp3(3) py(3) pyc(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1

</details>

**Comment by alexandrudima** [comment]
@NikhilRajPandey What exactly is slow? Can you please follow the guide at https://github.com/Microsoft/vscode/wiki/Performance-Issues in order to pinpoint the culprit?
