### ISSUE TITLE
did not work return key in korean input properly for mac

### ISSUE THREAD

**Issue by yoondoin** [Microsoft/vscode#65580]
Issue Type: <b>Bug</b>

after input korean in editor and then press return key, a line break occurs after the first character.
for example is shown below.

안녕하세요 <- press return key

안             <- line break
녕하세요

interestingly return key works properly in this bug report window of vscode.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ko|MS-|1.30.2

</details>

**Comment by m1n1me** [comment]
This case occured samely too with VS Code version 1.30.2

**Comment by sanghunka** [comment]
Same issue on Mac Mojave 10.14.2 (18C54)
VS Code version 1.30.2

It is a common issue when Apple updates macOS.
In my opinion, there is a part to judge whether the combination of Korean consonants and vowels is finished or not, and the rules of this part seem to be changed according to the version of OSX. In the old days (prior to El Cap), this was what I experienced on several mac apps(alfred...)

**Comment by yoondoin** [comment]
This issue fixed in 1.31.0-insider

**Comment by gracefullight** [comment]
1.31 릴리즈 될 때까지 엄청 불편하게 써야겠네요..
