### ISSUE TITLE
go live 

### ISSUE THREAD

**Issue by qq6878** [Microsoft/vscode#65589]
### Issue Type
Bug

### Description

go live 那去了 下面怎么不显示了 。还有左边这4个 插件下载 和文件管理 资源管理器等5个那去了，  这个软件编译代码可以。功能 太垃圾太不清晰。
垃圾一个

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|7.85GB (2.74GB free)|
|Process Argv|D:\新建文件夹\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
google-search-ext|ade|0.2.1
vscode-svgviewer|css|1.4.7
vscode-faker|dee|1.3.0
fuzzysearch|gay|0.2.1
search-node-modules|jas|1.3.0
easy-less|mrc|1.4.5
vetur|oct|0.14.3
LiveServer|rit|5.3.1
open-in-browser|tec|2.0.0
quokka-vscode|Wal|1.0.174
ReactSnippets|xab|2.2.1

</details>
Reproduces only with extensions

**Comment by gaoyia** [comment]
丢人现眼 @qq6878

**Comment by qq6878** [comment]
破白菜，垃圾。
本身这个编辑器的功能说明就不如其他。JS编写的会有多高级

**Comment by alexandrudima** [comment]
@qq6878 I am sorry, the development language of the project is English. Can you please create a new issue in English and please remember to follow the template (i.e. if you have a bug, please be sure to include reproducible steps).
