### ISSUE TITLE
Selection shortcut did not works

### ISSUE THREAD

**Issue by vasiliyaltunin** [Microsoft/vscode#65583]
Issue Type: <b>Bug</b>

On Centos 7 did not work keyboard shortcuts:

ctrl+Shift+Left
ctrl+Shift+Right 

to select words to left/right

i did not had such problem on windows 10

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|5.56GB (0.34GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
Go|ms-|0.8.0

</details>

**Comment by alexandrudima** [comment]
@vasiliyaltunin  

It is possible that those keybindings are reserved and consumed by the OS.

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by vasiliyaltunin** [comment]
It did not let me use Ctrl+shift. When i press shift - nothing happends, and BTW i use CTRL+SHIFT to change languages, but it strange if Centos just don

**Comment by alexandrudima** [comment]
@vasiliyaltunin This sounds like a CentOS specific issue/question. Perhaps you can ask this question on StackOverflow or perhaps you are able to search for it online.
