### ISSUE TITLE
Saving a file and the cursor goes to the end of the file

### ISSUE THREAD

**Issue by cduris** [Microsoft/vscode#65588]
Issue Type: <b>Bug</b>

Everytime I hit CTRL+S to save, the cursor goes to the end of file..

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
php-intellisense|fel|2.3.10
laravel-blade|KTa|0.0.1
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
laravel-blade|one|1.18.0

</details>

**Comment by alexandrudima** [comment]
@cduris Does this reproduce when you disable all extensions? Does it happen in all file types? Do you perhaps have an extension which modifies the file on save?

**Comment by alexandrudima** [comment]
@cduris I cannot reproduce this in a fresh install. Perhaps there are more steps than just saving?

![kapture 2018-12-24 at 23 04 29](https://user-images.githubusercontent.com/5047891/50407068-51e40200-07d0-11e9-8801-1b15058a660f.gif)
