### ISSUE TITLE
Tab completion falls back to inserting tab-character

### ISSUE THREAD

**Issue by cooperbaker** [Microsoft/vscode#65587]
Issue Type: <b>Bug</b>

Open a blank file

set 'indent using spaces'
set 'editor.renderWhitespace' to all

type 'test'
press the tab key twice
type 'tabs'
a hard tab is inserted between the words instead of all spaces.

next, 'convert indentation to tabs'
the errant hard tab does not go away

This is unexpected behavior.  When indent using spaces is set, I assume the document will contain no tabs.  I made a dozen new files and only discovered the secret tabs after checking the files into a git repo and noticing horrendous indentation problems.  Files are filled with tabs that seem to be stuck to whatever came before them, and 'convert indentation to tabs' does nothing.  :(

relevant user settings:
"editor.detectIndentation": false,
"editor.tabSize": 4,
"editor.insertSpaces": true,

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4009)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (56.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1
platformio-ide|pla|1.6.0

(1 theme extensions excluded)

</details>

**Comment by cooperbaker** [comment]
Forgot to mention:
This was happening with "editor.tabCompletion": "on",
It stops with "editor.tabCompletion": "off",

**Comment by saran-sasidharan** [comment]
Even i faced the same issue. But it's fixed after disabling Vim emulator (vscodevim).

**Comment by andfk** [comment]
+1. It prints `<tab>`

**Comment by DarrenCook** [comment]
I also have this bug - it has been driving me crazy (I have lint set to complain about tabs). I've got this in my settings:
 
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,

Been manually fixing the tabs, saving, restarting, etc. and still tabs get inserted. (I.e. it should've been okay even with detectIndentation: true, as there were no other tabs in the file.)

I just changed `"editor.tabCompletion": "on",` to `"editor.tabCompletion": "off",` and the problem has gone away. Thanks for that hint.

I'm not using the vim emulator. I have three extensions enabled: gitlens, nobuhito.printcode, and zeithaste.cursorcharcode.
Version 1.30.1, Linux.

**Comment by jrieken** [comment]
I have pushed a change that fixes most pain here. *Before*, when unable to complete we would type tab, not we run the tab-command instead. That's what would have happened mostly likely anyways, but there is no guarantee. Therefore, you can also tweak the keybinding to provide the command that should be executed when no completion can be found. As said, the default should work for 99% of our users. 

This is how a custom fallback command can be configured, e.g. deleteLeft (that doesn't make must sense but illustrates the point). The default is the tab-command which is sensitive to tab- vs space-characters etc.

```json
    {
        "key": "tab",
        "command": "insertBestCompletion",
        "when": "atEndOfWord && !hasOtherSuggestions && !inSnippetMode && !suggestWidgetVisible && config.editor.tabCompletion == 'on'",
        "args": {
            "fallback": "deleteLeft"
        }
    },
```
