### ISSUE TITLE
Complement utile

### ISSUE THREAD

**Issue by LordVenom** [Microsoft/vscode#65591]
Issue Type: <b>Feature Request</b>

Bonjour, voici deux chose qu'il faudrais changer.

L'ouverture d'onglet l'un sur l'autre. j'ai pas trouver d'option pour toujour ouvrir un nouvelle onglet.

Les onglets s'ecrase l'un l'autre je peux passer 3min a esseyer d'avoir deux fichier sur 2 onglet vraiment pas pratique.

La reduction du code automatique si je veut affiche plus de 2000 ligne je doit pouvoir le faire.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment]
@LordVenom I am sorry, the development language of the project is English. Can you please create a new issue in English. Please remember to include reproducible steps.
