### ISSUE TITLE
Visual Studio erscheint nicht in der Taskleiste auf dem Mac

### ISSUE THREAD

**Issue by Friedrichowski** [Microsoft/vscode#65592]
Issue Type: <b>Bug</b>

Nach dem Start von Visual Studio Code sollte es auch in der Taskleiste (Mac) erscheinen, was leider nicht der Fall ist. 

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 12, 11|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.30.2
python|ms-|2018.12.1
cpptools|ms-|0.20.1
code-spell-checker|str|1.6.10
code-spell-checker-german|str|0.1.2
markdown-pdf|yza|1.2.0

</details>

**Comment by bpasero** [comment]
@Friedrichowski can you please use english for filing issues. Can you attach a screenshot how this looks like?
