### ISSUE TITLE
Losses window mode on linux

### ISSUE THREAD

**Issue by samtech09** [Microsoft/vscode#65596]
Issue Type: <b>Bug</b>

1. Run vscode
2. vscode window appears on all activities of KDE plasma desktop
3. Right click over title bar, no context menu revealed

Expected:
1. vscode window should appear on single activity from where vscode app launched.
2. Right clicking over titlebar should reveal standard context menu.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.19.11-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2475)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.60GB (6.58GB free)|
|Process Argv|ost-mvc-pprof/|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by Juje** [comment]
If I understand you correctly you probably want to turn the title bar back to native.
You can do this in the settings by searching for "title bar" and setting the setting to "native".

**Comment by samtech09** [comment]
Ys, exactly. It resolved that issue. Closing it.
Thanks for quick revert.
