### ISSUE TITLE
[cygwin][tasks][cygpath: option requires an argument]

### ISSUE THREAD

**Issue by vincent456** [Microsoft/vscode#65594]
Hello
I try to get a simple configuration to work with cygwin
the configuration is : 
`{
    "terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["/bin/xhere", "/bin/bash"]
}`
It works perfectly when opening a new Terminal (however opening a terminal by command palette opens cmd.exe). The problem is now running task such as :
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello"
        }
    ]
}`
output on the terminal
`cygpath: option requires an argument -- c
Try `cygpath --help' for more information.
Starting /bin/bash`

and start a new cygwin bash prompt with working directory at the root of cygwin

Thank you very much in advance

**Comment by vincent456** [comment]
I don't have the issue #27219

**Comment by alexr00** [comment]
You probably need to do something like this:
```json
	"version": "2.0.0",
	"options": {
		"shell": {
			"args": [
				"-- c"
			]
		}
	},
```

**Comment by vincent456** [comment]
when I try to do as alexr00, I get
`/usr/bin/bash: -- c: invalid option`

**Comment by alexr00** [comment]
````
D:\repos\Microsoft\vscode>C:\cygwin64\bin\bash.exe --help
GNU bash, version 4.4.12(3)-release-(x86_64-unknown-cygwin)
Usage:  /usr/bin/bash [GNU long option] [option] ...
        /usr/bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --protected
        --rcfile
        --restricted
        --verbose
        --version
        --wordexp
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
Type `/usr/bin/bash -c "help set"' for more information about shell options.
Type `/usr/bin/bash -c help' for more information about shell builtin commands.
Use the `bashbug' command to report bugs.

bash home page: <http://www.gnu.org/software/bash>
General help using GNU software: <http://www.gnu.org/gethelp/>
````
Looks like you should use `-c` in the `args` from https://github.com/Microsoft/vscode/issues/65594#issuecomment-451399726
