### ISSUE TITLE
Show system title bar

### ISSUE THREAD

**Issue by jade28** [Microsoft/vscode#65599]
Hi guys,
New release reset my setting. Title bar was hidden and i haven't found a way to show it.
Please help me fix it. Thanks! 🙏
```
VS Code version: 1.30.0
Elementary OS 5.0 Juno
```
![screenshot from 2018-12-22 20-24-29](https://user-images.githubusercontent.com/34389409/50374906-9d0ee100-0627-11e9-964e-778805c0b731.png)

Result i wanted:
![picture1](https://user-images.githubusercontent.com/34389409/50374951-4d7ce500-0628-11e9-822f-6c2b6bc8717e.png)

**Comment by Juje** [comment]
Go to "Settings" type "title bar" and change the setting to "native".
If that is what you want.

**Comment by jade28** [comment]
@Juje, thanks you so much!
