### ISSUE TITLE
Intellisense inserts unwanted suggestion when typing left parenthesis

### ISSUE THREAD

**Issue by realh** [Microsoft/vscode#65597]
Issue Type: <b>Bug</b>

Left parenthesis seems to act as a shortcut key to select the highlighted Intellisense suggestion, but there doesn't seem to be an entry for it in my key settings. I use the vim plugin, but I don't know if that's relevant.

This behaviour is a nuisance because I typically don't leave a space between a method name and the parenthesis. If I'm trying to write a new method, for example one called start in Typescript, I type `start()` and get `StaticRange()` instead.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.17GB free)|
|Process Argv|-psn_0_704684|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
tslint|eg2|1.0.42
vim|vsc|0.17.0

</details>

**Comment by usernamehw** [comment]
/question https://stackoverflow.com/questions/48609354/visual-studio-code-autocomplete-when-i-press-key-any-way-to-disable

**Comment by smalllong** [comment]
really hard to use
