### ISSUE TITLE
Need webview to load remote page

### ISSUE THREAD

**Issue by Jiawens** [Microsoft/vscode#65595]
I think webview should be able to load remote(such as https://stackoverflow.com) page.
If I **download the page** and display it,
![issue](https://user-images.githubusercontent.com/26176350/50373904-6da8a600-0620-11e9-9f11-4e4b1e08d9f1.png)
the image **cannot** load,**cookie**,**external css** are also **unavailable**.(this website is www.baidu.com)

And if I use **iframe** to show websites, the "**X-Frame-Options**" will refuse me to display it.

**Big thanks.**

**Comment by mjbvz** [comment]
Many websites block being embedded in iframes using x-frame-options. This is a security feature that you cannot work around
