### ISSUE TITLE
can't run Code while offline

### ISSUE THREAD

**Issue by dmahugh** [Microsoft/vscode#65609]
I've run into a problem several times where I can't use Code if I don't have an internet connection. It happened a couple of times, then I used Code successfully offline once, and now it has started again.

I have all extensions disabled, and when I click the Code icon it fails silently, and at a command prompt I get the error shown here:

![image](https://user-images.githubusercontent.com/1130262/50380068-c83a0600-0610-11e9-902c-2bc4bd869b70.png)

If I connect to the internet, it runs fine with no errors. Is there any workaround that will allow me to run Code while offline? From the other similar issues I've seen reported, it sounds like there's nothing we can do except wait for Electron 3.0 - is that correct?

Here's my Help/About info:
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
Electron 3 is already in [Insiders](https://code.visualstudio.com/insiders/). People reported some workarounds in that issue https://github.com/Microsoft/vscode/issues/7570#issuecomment-377649496 and in duplicates they created.

**Comment by dmahugh** [comment]
Thanks @usernamehw - I've installed Insiders and confirmed everything works fine while offline.
