### ISSUE TITLE
JSON editor in settings disappeared?

### ISSUE THREAD

**Issue by elgs** [Microsoft/vscode#65605]
I really love the JSON settings editor. Back then a few weeks ago, when the visual settings editor was introduced, I still was able to switch to the JSON editor, but now (1.30.1) it seems it is not possible to switch to JSON editor.

**Comment by usernamehw** [comment]
```json
"workbench.settings.editor": "json",
```

**Comment by elgs** [comment]
@usernamehw thank you! It works!
