### ISSUE TITLE
PowerShell IntelliSense Breaks on Dark (Visual Studio) Colour Theme

### ISSUE THREAD

**Issue by PhilipElder** [Microsoft/vscode#65603]
- VSCode Version: 1.30.1
- OS Version: Windows 10 64-bit Enterprise 1803

Steps to Reproduce:
1: Switch theme to Dark (Visual Studio) and code does not colour
2: Switch them to Dark+ (default dark) and code does colour
Blogged:
http://blog.mpecsinc.ca/2018/12/vs-code-for-powershell-intellisense.html

Does this issue occur when all extensions are disabled?: Does not Matter

**Comment by alexandrudima** [comment]
@PhilipElder I don't think this is a bug. 

The Dark theme is **simpler** than the Dark+ theme and only colours certain syntax constructs. In this case, it looks like the Dark theme does not color that token (or colors it with the default color).
