### ISSUE TITLE
Hiding error messages even though there are no other ones.

### ISSUE THREAD

**Issue by richtera** [Microsoft/vscode#65607]
Issue Type: <b>Bug</b>

i am getting this weird error for typescript.
It says it's not displaying more errors
In this case: "Not showing 231 further errors and warnings."
However it's not showing any other errors. So the file says it has one error and the error just has the above message. This doesn't look right.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-jq|dan|1.0.0
vscode-jq-playground|dav|1.8.0
vscode-eslint|dba|1.7.2
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.3
code-runner|for|0.9.5
gc-excelviewer|Gra|2.1.26
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
python|ms-|2018.12.1
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
sass-indented|rob|1.4.9
gitconfig|sid|2.0.0
mdx|sil|0.1.0
quokka-vscode|Wal|1.0.174

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by richtera** [comment]
Yes same problem happens.
I get one entry that says it will not display another 56 further errors even though it's not even showing one.
![image](https://user-images.githubusercontent.com/708186/50564341-18405900-0cf2-11e9-877d-2444aacafff6.png)

This is the insider build with no installed extensions.
![image](https://user-images.githubusercontent.com/708186/50564351-28f0cf00-0cf2-11e9-9290-dd653bd4d4b4.png)

**Comment by mjbvz** [comment]
Can you try setting: `"editor.showUnused": false`. Do you still see the `Not showing X further errors` message after setting that?

**Comment by richtera** [comment]
That flag doesn't seem to have an effect
![image](https://user-images.githubusercontent.com/708186/50609496-ce947180-0e9d-11e9-80c4-622e5e05b24c.png)

**Comment by mjbvz** [comment]
Can you share the file? 

If not, please share the the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

This should list all diagnostics that are being returned. If you can share it, then I can see what may be triggering this
