### ISSUE TITLE
Show types first rather than last while using CTRL+SPACE

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#65613]
# Feature Request

I am currently using Flutter & when I use some class like `Text()` then it should show its types first but right now it shows the types at last.

Right now it looks like this, this is at start 

# No Types at First

![No Types at First](https://imgur.com/32gqLrC.png)

# Types at Last

![Types at Last](https://imgur.com/5pmEr2y.png)

Whereas it should show it at first then it would be more helpful

PS - Idk if this is related to Flutter Extension

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
aws-amplify-vscode|aws|0.0.4
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
latex-workshop|Jam|5.19.0
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.25
swift|Kas|0.0.3
graphql-for-vscode|kum|1.12.1
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.11.1
awesome-flutter-snippets|Nas|1.0.5
tachyons|oct|0.3.0
vscode-jest|Ort|2.9.2
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.2
vscode-graphql|Pri|0.1.6
code-settings-sync|Sha|3.2.4
markdown-preview-enhanced|shd|0.3.11
velocity|sod|0.1.0
ayu|tea|0.17.0
highlight-matching-tag|vin|0.8.4
vscode-jss-snippets|vis|0.2.2
vscode-svg-previewer|vit|0.3.1
vscode-wakatime|Wak|1.2.5

(6 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
```json
"editor.snippetSuggestions": "bottom",
```

**Comment by deadcoder0904** [comment]
Thanks @usernamehw 

VSCode has so many features that many don't know where to find it 😂
