### ISSUE TITLE
GitHub extension for Visual Studio Code

### ISSUE THREAD

**Issue by tamimmirza** [Microsoft/vscode#65617]
Since there is an extension for Visual Studio that enables the user to create a repository on GitHub without the need to use the Command Prompt or download Git for Windows. There should be a similar extension for Visual Studio Code that performs similarly without the use of any 3rd party tools and other complex methods.

I use VS Code for Python (data science) coding instead of Visual Studio IDE due to the lightning speed of Visual Studio Code and the addition of the IntelliCode extension so its only optimal to add an extension that enables the option to share the project and all project related data on GitHub at the behest of the user without switching to Visual Studio or another IDE for the task

The features to be requested is to add an official GitHub extension which not only creates a repository on GitHub but can also fetch and edit the repository and its contents without disrupting the flow.

**Comment by wsmelton** [comment]
VS Code has direct integration with Git and let's you do the same thing the VS extension does, short a few task.

https://code.visualstudio.com/docs/editor/versioncontrol

https://code.visualstudio.com/docs/introvideos/versioncontrol

**Comment by tamimmirza** [comment]
I have actually looked through those links and have voiced this feature request after using them. Basically, the Git integration is great but it makes the user do much work while the extension of Visual Studio just basically formats the project to a Git project when initializing a repository and taking care of the, for lack of a better word, "paperwork".

I apologize if I have been using the extension wrongly but I kind of wanted the same feature on VS Code where the user imports version control using git that has been installed on the user's system and the user has to initialize the repository in the same way as they do in GitHub or VS extension and then share it with a click of a button.

If by chance I am using it wrong and the built-in git integration extension can already do that. Then please guide me in the way it can help because I can find no quick solution to this issue.

**Comment by wsmelton** [comment]
I think there is a difference in tools that has to be understood. VS Code will not have buttons or a full UI like VS does, it is not built for that. All of the Git integration is done via the Control Palette and covers just about everything you can do with the VS GitHub extension:
![image](https://user-images.githubusercontent.com/11204251/50403742-de59da80-0766-11e9-853c-31522e723aa3.png)

If it does not then you would need to seek out an extension that covers what you are wanting via the [marketplace for VS Code](https://marketplace.visualstudio.com/vscode).

Just a note that this repository is only for VS Code itself, which does not maintain or control creation of the extensions. Each extension will have a repository on GitHub, generally, that host the source code and you can submit issues to that extension's repository to get assistance or request features.

Outside of the above, you will need to be more specific on what you are wanting the integration of Git to cover.

**Comment by tamimmirza** [comment]
From the screenshot you have provided it appears the Git integration is fully capable as its counterpart VS extension which leads me to believe that I am not using it properly because most of the Git commands I see are not even available on a sample project I am using most probably due to incorrect setup of the extension. (I am a beginner on Git so please bear with me)

My purpose is to:
1) Create a project in VS Code
2) Initialize the project as a Git repository with all Git related files, data and metadata
3) Link the Git extension with my GitHub account
4) Publish the repository on GitHub

Is there a series of steps that will enable me to follow the above-mentioned procedure sequentially and produce the final results I desire? I have gone through the official documentation of the Git integration and it does not help me in setting up Git properly but rather it tells me what I can do once it has been set up.
