### ISSUE TITLE
Recommended - No extensions found

### ISSUE THREAD

**Issue by francoism90** [Microsoft/vscode#65615]
- VSCode Version: 1.30.1
- OS Version: Arch Linux

```
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T22:23:23.072Z
Electron: 2.0.15
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.19.11-1-ck-skylake
```

Steps to Reproduce:

1. Open Extensions
2. Recommended list is empty

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by giicre** [comment]
i also have the problem,and my os is ubuntu 18.04

**Comment by giicre** [comment]
> i also have the problem,and my os is ubuntu 18.04
my problem had been solved,but i dont know the reason.I don't know if vscode fixed the problem or beacase the proxy i changed.

**Comment by sandy081** [comment]
Looks like a proxy issue because of which you are not able to connect to marketplace and hence recommendations are empty
