### ISSUE TITLE
assistive technology won't always read the intelly sense suggestions

### ISSUE THREAD

**Issue by tayarndt** [Microsoft/vscode#65610]
When using assistive technology, and you alt tab out of VS code for something, the screen readers don’t read IN telly sense  suggestions. This happens with all screen readers.  To fix the issue you have to close VS code frequently because the screen reader stops reading suggestions.

**Comment by tayarndt** [comment]
I apreciate someone is assigned to this issue. I have a feeling that this issue is related to the electron accessibility API. I found a related issue on github  with electron that is still open. I am a devoloper so i know some code but couldn't figure how to fix this issue. Please let me know if you need more help and i will do the best that i can.

**Comment by jrieken** [comment]
> you alt tab out of VS code for something, the screen readers don’t read IN telly sense suggestions. This happens with all screen readers.

Not sure I understand that? When alt tabbing out of VS Code IntelliSense will stop and needs to be re-triggered, e.g via ctrl+space.
