### ISSUE TITLE
Very difficult to resize views (Output, Explorer, etc.) in latest version of VS Studio

### ISSUE THREAD

**Issue by candersonrf** [Microsoft/vscode#65618]
Issue Type: <b>Bug</b>

After upgrading to the Nov 2018 version of VS Code for Ubuntu, it is now very difficult to resize views using the mouse.  Hovering over a border momentarily changes the mouse cursor to indicate that resize is possible however it appears to only a have a few pixels tolerance before the resize cursor goes away.  Very frustrating!

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.71GB (2.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
cpptools|ms-|0.20.1
vscode-yaml|red|0.2.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by caiges** [comment]
I was able to do a small capture of this (ignore the flickering, it's a video driver issue): https://www.youtube.com/watch?v=_sKnG8v6-RQ
