### ISSUE TITLE
Untiled number always increase

### ISSUE THREAD

**Issue by shang-zd** [Microsoft/vscode#65611]
Issue Type: <b>Bug</b>

The untitled number is always increase...
I suppose this should be cleared to untiled-1 once all unsaved and untiled files are closed and the vs code exits.

Thanks.
Regards.
Zd

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-zh|ada|3.8.0
gc-excelviewer|Gra|2.1.26
latex-workshop|Jam|5.19.0
nc-gcode|ML|0.13.0
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.20.1
markdown-all-in-one|yzh|1.8.0

</details>

**Comment by bpasero** [comment]
Great catch 👍
