### ISSUE TITLE
Cmd+D doesn't select multilines as expected

### ISSUE THREAD

**Issue by aybabtme** [Microsoft/vscode#6561]
- VSCode Version: Version 1.1.1 (1.1.1) def9e32467ad6e4f48787d38caf190acbfee5880
- OS Version: OS X 10.11.4

Steps to Reproduce:
1. Open a buffer with the following content:

```
func noname() {}
panic("lol")

func noname() {}
panic("lol")


func noname() {}
panic("lol")
func noname() {}
panic("lol")
```
1. Select `"func noname() {}\npanic(\"lol\")"` and press `Cmd+D` to try to select the multiple instances of the string `"func noname() {}\npanic(\"lol\")"`.
2. It doesn't work.
3. Try the same thing in Atom or Sublime Text; it works.

A gif that demonstrates the difference in behavior: 

![derp](https://cloud.githubusercontent.com/assets/1189716/15412867/49c595ac-1df9-11e6-8d81-b6f94e1efdd7.gif)

Thanks!

**Comment by alexandrudima** [comment]
Blocked by #313

**Comment by wulftone** [comment]
This should be unblocked now?

**Comment by alexandrudima** [comment]
This works since quite a while
