### ISSUE TITLE
xamp v3.2 for windows 10

### ISSUE THREAD

**Issue by Gotham12** [Microsoft/vscode#65628]
I have windows  10 and xampp - php 5.6.24. phpmyadmin v3.3,  mysql 5.5.  I have installed visual studio code 1.30.1.  I get the following message:

Php executable not found.  Install php7 and add it to your path or set the php.executablepath setting.  Source php intellisense (Extension)

I use xamp (mysql and phpmyadmin) for my books and dvd collection and in regards to php I just want to learn programming and create for personal\hobby interest.  I do not publish  anything on the net.  I have made the following changes:

Under the USer Settings for php and php intellisense 
terminal.integrated.shell.windows":c:\\xamp\\php\\php.exe

I still get the above message.   Does Visual Studio not work with php 5.6 and if so how do I fix this problem?  thankstten the needed data into your clipboard because it was too large to send. Please paste.

**Comment by roblourens** [comment]
The error message refers to the `php.executablePath` setting, please set that setting to the path for php.exe. 

The message is coming from the PHP Intellisense extension, if you have any more issues, please file an issue on that repo: https://github.com/felixfbecker/vscode-php-intellisense/issues
