### ISSUE TITLE
Upload file to server without any confirmation when press ctrl-s

### ISSUE THREAD

**Issue by isnaasharimam** [Microsoft/vscode#65623]
Issue Type: <b>Feature Request</b>

Hello,
I'm using linux neon kde. In this os, I have added my server ssh info and can explorer server through Dolphin browser. When I open a file in server from my dolphin file explorer by Kate software and make some changes in file and Press Ctrl-S the kate saves file into server without any confirmiation and this is greattttt. But in visual studio code I should press Upload and Overwrite Buttons When I press Ctrl-s that annoying me. 
I searched about add-ons for vs code and found some plugins but they require sftp credentional. MAKE IT SIMPLE LIKE KATE to use vs code instead.
Thank you

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-43-generic

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
