### ISSUE TITLE
"Run Python File in Terminal" missing

### ISSUE THREAD

**Issue by LiquidAurum** [Microsoft/vscode#65620]
Issue Type: <b>Bug</b>

"Run Python File in Terminal" will usually disappear from the right click menu for a bit and will magically appear after some time. 

https://imgur.com/a/h4SEX3S

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3503)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.94GB (18.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.46
code-runner|for|0.9.5
theme-monokai-pro-vscode|mon|1.1.9
python|ms-|2018.12.1
code-settings-sync|Sha|3.2.4

(3 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Is this after reload? Is this with new files? Is this with the first python file you open?

**Comment by LiquidAurum** [comment]
I get this whenever I first start VScode, and it usually ends up appearing after like 20-30 minutes by itself. Sometimes I have to open up settings and then go back to my file for it to come back. But it is pretty consistent whenever I first open it up it's not there.
