### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by nbg4-Bilwa** [Microsoft/vscode#65635]
- VSCode Version: 
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

- OS Version: Windows 7

Steps to Reproduce:

1. While launching the Visual Studio code, it is giving me error Extension host terminated unexpectedly. I did clean uninstall of node.js and deleted all files related to node.js and visual studio code
![visual studio code] (https://user-images.githubusercontent.com/42248817/50392270-c0a65a00-0701-11e9-9221-f6d7db70e06a.JPG)

2.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment]
@nbg4-Bilwa To rule out an installation issue, can you please install the [insiders version](https://code.visualstudio.com/insiders/). Does the extension host start with the insiders version?

Is this a recent problem? i.e. Were you successful in using vs code in the past?
