### ISSUE TITLE
syntax highlighting error php source in javascript

### ISSUE THREAD

**Issue by poibis** [Microsoft/vscode#65636]
- VSCode Version:
version: 1.30.1 (system setup)
commit: dea8705087adb1b5e5ae1d9123278e178656186a
date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
- OS Version:
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/30461766/50392797-e03a9280-0794-11e9-91ff-06dc0b3f274b.png)

2.
![image](https://user-images.githubusercontent.com/30461766/50392809-f47e8f80-0794-11e9-97e8-1895ccde188a.png)

This is exactly .html file.
But when I use php syntax in javascript, everything that after using code is showing an error. It doens't work correctly.

I can't see correct highlighting anymore. It even doesn't work making comments shortcuts.
Does anyone get same problem?

**Comment by AnsonYeung** [comment]
This also happens with css code.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/65649
