### ISSUE TITLE
Show Insiders Commit on Download Website

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#65633]
https://code.visualstudio.com/insiders/ should be more verbose. At the very least it should be showing the current commit it is on right now. As a bonus, it could also show the timer until the next build.

**Comment by Astrantia** [comment]
@Tyriar What do you think about this?

**Comment by Tyriar** [comment]
Why do you want the current commit?

**Comment by Astrantia** [comment]
@Tyriar To tell when it was updated last? It's daily but this would be useful nevertheless

**Comment by Tyriar** [comment]
@Astrantia you should get the update notification on the gear in the bottom-left though when there are updates available?

**Comment by Astrantia** [comment]
@Tyriar It's confusing as it is right now. I don't have Insiders installed now and I can't tell what commit it is on. I tried installing and saw that it was last updated 7 days ago.

**Comment by Tyriar** [comment]
@Astrantia but the notification in VS Code will always tell you when there's a new update as it asks the update server. Why would you care if it was last updated 7 days ago if you haven't even installed it yet? 😕 

We turn off Insiders updates during our testing period (to stabilize the release) and at the end of the year (as most people are out).

**Comment by Astrantia** [comment]
@Tyriar I uninstall Insiders after checking some feature updates so I'd like a better transparency over updates without relying on the vscode insiders notification.

**Comment by joaomoreno** [comment]
The latest commit depends on the platform. We don't have this available on the website but we do have it available as a REST API:

https://update.code.visualstudio.com/api/update/PLATFORM/insider/latest

Possible values for `PLATFORM`:

```
"win32-x64",
"win32",
"win32-archive-x64",
"win32-archive",
"win32-x64-user",
"win32-user",
"linux-x64",
"linux-ia32",
"linux-deb-x64",
"linux-deb-ia32",
"linux-rpm-x64",
"linux-rpm-ia32",
"darwin"
```
