### ISSUE TITLE
Faded VS code if I ckicked on Manage icon or somewhere else

### ISSUE THREAD

**Issue by Ebyrdeu** [Microsoft/vscode#65630]
I have this issue like ~2 hours or less. 
This problem occurs only on my PC, on a laptop, such an issue did not appear. The issue appeared after installing the "Material Theme" extension. I deleted it, cleared the cache, re-installed VS code, but all without success...

Video:
https://drive.google.com/open?id=1WEt3dmM7xtSzo1xDxK-w07RQgXcdYHvJ
Images:
https://imgur.com/djgrGqk
https://imgur.com/TvR2OFZ
https://imgur.com/LRg8NkX

**Comment by Tyriar** [comment]
Cool wallpaper 😄 

Duplicate https://github.com/Microsoft/vscode/issues/61940

**Comment by Ebyrdeu** [comment]
@Tyriar Well, I'm fucked up. Somehow  ¯\_(ツ)_/¯ 
Anyway thanks for helping.
![2018-12-27_00-36-16](https://user-images.githubusercontent.com/42122071/50459826-9fe33c00-096f-11e9-8eef-b82e455162bc.png)
