### ISSUE TITLE
Nested string literal highlight error

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#65637]
- VSCode Version: 1.30.1
- OS Version: OSX 10.13.6

![image](https://user-images.githubusercontent.com/3254987/50394259-37971f00-0711-11e9-95c6-1bd929f752d2.png)

Typescript 3.2.2

**Comment by IllusionMH** [comment]
If you about differently colored braces/parenthesis - most likely this is problem with extension.
Try to reload with extensions disabled to see if there are any problems with syntax highlight.

**Comment by mjbvz** [comment]
What is the error?

Also please share the text of the code along with screenshots

**Comment by unional** [comment]
@IllusionMH Yes, it was caused by an extension, "Bracket Pair Colorizer" A new rewrite of that extension "Bracket Pair Colorizer 2" have fixed that issue.

🌷 

For reference: https://github.com/CoenraadS/BracketPair/issues/184
