### ISSUE TITLE
[folding] Make hiding of the folding gutter configurable

### ISSUE THREAD

**Issue by adamcrossland** [Microsoft/vscode#6563]
- VSCode Version: all
- OS Version:all

When I use Code on a touch-enabled device with a stylus rather than a mouse, it is very difficult to use the folding gutter, as it is hidden unless the pointer is hovering over it. While having that gutter hidden when I am not using it nicely reduces visual noise, there are times that I need it to always be there.

Why not provide a configuration item that allows the user to switch between having it be always visible or only visible on hover?

**Comment by jchannon** [comment]
+1

**Comment by 23doors** [comment]
seems like a duplicate of https://github.com/Microsoft/vscode/issues/3911

**Comment by aeschli** [comment]
correct, duplicate of #3911
