### ISSUE TITLE
VScode disables intellisense after changing file association from css to postcss

### ISSUE THREAD

**Issue by rudolfschmidt** [Microsoft/vscode#65631]
Can you please make vscode providing the usual css autocomplete functionalities that exist if you have selected css association also for other css file types like postcss. 

Why not keep using css as filetype? Some plugins require the filetype to be postcss to highlight the syntax .

I have read https://github.com/Microsoft/vscode/issues/17419 that addresses the problem. I mean that problem is known. Plain CSS is not workable. You have to use postcss or similar compilers If you cannot find a way to work with modern css technologies you should not call vscode an editor for web developers. Its not competitive. For me that issue is a reason to switch to another editor.

Hope I get a reasonable answer.

**Comment by octref** [comment]
Because "postcss" is a vague definition. Postcss can mean completely different syntaxes depending on which plugin/parser you are using. There is no way you can support all cases. So we don't associate css language server with postcss and leave it broken for 50% of the use cases.

> Some plugins require the filetype to be postcss to highlight the syntax .

What's your specific use case?

**Comment by rudolfschmidt** [comment]
@octref, I try to explain the issue more clear.

I do not need support for postcss nattily. Like me title says the only issue here is that I do not have css auto completion after changing from file type css to another dialact. I need to have the intellisense functionality and in the same time begin able to change the filetype from css to something else to use certain plugins that support syntax highlighting and other stuff.

For example I like to use the plugin cpylua.language-postcss to have syntax highlighting but it requires to change the file type css to postcss. If I do so I cannot have auto completion anymore that in todays time is a nogo.

**Comment by octref** [comment]
If that's your case, maybe https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language would fit you?
