### ISSUE TITLE
Solution for can't input Chinese in Linux

### ISSUE THREAD

**Issue by so2liu** [Microsoft/vscode#65641]
- VSCode Version: Last
- OS Version: Ubuntu 18.04 LTS

I have met the problem that, I can't input in Chinese in VS Code, but in other software everything is fine. I googled it and there are lots of other people also met it. But the issues were closed without solution. 

Finally I solved it. The problem is the VS Code from Ubuntu Software Apps is snap, not official. Try 
`which vscode` and will get path in `snap`.

Download from [official link](https://code.visualstudio.com/Download) and everything is fine. 

By the way, use `code` in terminal for official version, not `vscode`. 

Hope can help others for saving time.

**Comment by rebornix** [comment]
@joaomoreno @Tyriar FYI, we may need to verify this when publishing snap.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51308
