### ISSUE TITLE
Cut text issue: selection still exist after cutting (very rare)

### ISSUE THREAD

**Issue by Daijobou** [Microsoft/vscode#65645]
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Datum: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Betriebssystem: Windows_NT x64 10.0.17763

This happen very rare and not always reproducible in second try. I select few lines of php code and cut it with CTRL+X or SHIFT+DEL and after cut, the text is cutted, but the selection still exists and selected now the text after the cutted text. 

Its very hard to make a preview gif for this issue, but I will try, when possible. I have this issue since I use vscode (since few months) and its happen max 0-2 per day. Maybe anyone can verify this issue or maybe anyone can take a look in source code what happen with selection after remove cutting text?

**Comment by alexandrudima** [comment]
@Daijobou I have never experienced this so I think it might be something with the way you are using vscode, perhaps you are using the mouse and the keyboard at the same time, holding the left mouse button pressed while you are cutting? 

In any case, please try to capture some reproducible steps if possible, I would like to reproduce and investigate...

**Comment by Daijobou** [comment]
I found this happen too without automatic closed "(" ")" and "[" "]" and "{" "}". Its happen after "return"-key.
![vscodeg](https://user-images.githubusercontent.com/260343/50572767-d550b500-0dc7-11e9-8524-8679d88f828b.gif)

**Comment by alexandrudima** [comment]
@Daijobou I see that something is weird in the gif, but I don't understand the exact steps you are doing. Can you please write down each step as precisely as possible. 

Alternatively, you can run `F1 > Developer: Enable screencast mode` (will make VS Code render the keys that you are pressing). Here I am trying to reproduce but without success:
![kapture 2019-01-07 at 12 16 07](https://user-images.githubusercontent.com/5047891/50765399-0d4b7280-1276-11e9-8c15-6321c4d1a50f.gif)

**Comment by Daijobou** [comment]
I can't find "screencast" mode in german gui. Is here a key shortcut? Here my steps for windows 10, I can everytime reproduce this:

step1. Insert this code:
```
if ()
{

text text text
text text text
text text text
text text text
```
step2. Go after "{" and press return. It should create a new line with tabulator
step3. Go with mouse to beginning of line 6 (thats now the second "text text text"-line)
step4. Selected this line with SHIFT+CURSOR DOWN
step5. Press SHIFT+DEL or CTRL+X for cut line

Now the line is removed, but the selection of this removed line jumps down to line 7. That you see in my GIF.
That happen only one time after step 2. All cuts after the first cut working fine.

**Comment by Daijobou** [comment]
Maybe its a extension, after disable **vscode-numbered-bookmarks** this issue is gone.

But its strange, this issue only happen in saved files or new created tabs in actual session, not in unsaved tabs after vscode was restarted.

I created a ticket, maybe the extension creator can check it.
