### ISSUE TITLE
Consider adopting TSLint's no-unnecessary-type-assertion

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#65646]
Now that #60565 and #65233 are landing strict null checks and `!` assertions in the code base, it's likely that you'll clean those up over time. As you evolve files to have, stricter type declarations (e.g. moving from `string | undefined | null` to `string | undefined`), you'll leave behind a set of `!` assertions. 

Would you accept a PR enabling [`no-unnecessary-type-assertion`](https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/) to help keep those clean?

**Comment by mjbvz** [comment]
Yes, this would certainly be helpful. Are you up to submitting the PR?

**Comment by JoshuaKGoldberg** [comment]
Well, I tried this out locally and hit two issues:

* It's a typed rule _(requires a TypeScript program)_ so that'd involve configuring around in `gulpfile.hygiene.js` to get them to work with the various different tsconfigs
* One blocking bug in `no-unnecessary-type-assertion`: https://github.com/palantir/tslint/issues/3521

Once the strict null checking migration is done and the TSLint bug is resolved, I'd be interested in the work to enable the rule in general. Closing for now 😄 but thanks!
