### ISSUE TITLE
VSCode's menu seems  incorrect

### ISSUE THREAD

**Issue by believe0815** [Microsoft/vscode#6564]
- VSCode Version:1.1.1
- OS Version:Windows 10

Steps to Reproduce:

1. using high-contrast dark theme in Windows 10

2. VSCode's menu can't show correct
![err](https://cloud.githubusercontent.com/assets/5975304/15414348/6ae5494e-1e6c-11e6-91b1-803dc9faf313.png)

**Comment by bpasero** [comment]
@believe0815 please report against https://github.com/atom/electron

**Comment by bpasero** [comment]
Please reopen if you still see this.
