### ISSUE TITLE
A input bug

### ISSUE THREAD

**Issue by Sweechirly** [microsoft/vscode#65658]
Issue Type: <b>Bug</b>

If you enter one at the cursor position and the same character after the cursor, it will not be entered, this automatic feature is bad

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240T CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.32GB free)|
|Process Argv|D:\lanto佛山|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
vscode-element-helper|Ele|0.5.4
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.7.3
path-autocomplete|ion|1.13.1
vscode-language-pack-zh-hans|MS-|1.30.2
vetur|oct|0.14.3
open-in-browser|tec|2.0.0

</details>

**Comment by octref** [comment]
Can you take a screenshot and explain what you mean?

**Comment by rebornix** [comment]
Close as lack of enough information.
