### ISSUE TITLE
Add support for typedoc-style hyperlinks in comments on hover

### ISSUE THREAD

**Issue by aserra54** [microsoft/vscode#65659]
typedoc supports hyperlink in comments using either the double bracket (`[[link]]`) or `{@link}` notation. Neither of these types of hyperlinks are rendered correctly when comments are hovered over in VS Code.

Consider the below example:

```ts
/**
 * Friend of [[Bar]].
 */
class Foo {
}

/**
 * Has a [[Baz|good friend]].
 */
class Bar {
}

/**
 * Reference to {@link Foo}.
 */
class Baz {
}
```

Hovering over each class symbol (`Foo`, `Bar`, and `Baz`) produces the following results:

**Foo**

![image](https://user-images.githubusercontent.com/3211528/50414971-7d71e700-07e6-11e9-8132-da88e23f6171.png)

**Bar**

![image](https://user-images.githubusercontent.com/3211528/50414990-98dcf200-07e6-11e9-8e2c-e7c2dfa5eaef.png)

**Baz**

![image](https://user-images.githubusercontent.com/3211528/50414998-a2fef080-07e6-11e9-9f8f-73f69f1e4ba3.png)

It would be great if these could get rendered properly using hyperlink-style markdown (e.g. highlighted in blue and, when clicked, navigating to the appropriate class). Without this feature, much of our typedoc can look quite ugly; especially those using the same format as `Bar` above.

(May be related to #8223; admittedly I don't understand the context of that issue well enough to judge.)

**Comment by aserra54** [comment]
Hello @mjbvz, is there any update to this? I generally assume it's not prioritized; is this something that is better left to an extension, or is this something VS Code plans to try and integrate natively?

**Comment by mjbvz** [comment]
I have no plans to prioritize this feature
