### ISSUE TITLE
View - Appearance - Show Activity Bar

### ISSUE THREAD

**Issue by Yuuulong** [Microsoft/vscode#65657]
Issue Type: <b>Feature Request</b>

Can this display activity bar give a shortcut key? It is too inconvenient to use

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings

You can `workbench.action.toggleActivityBarVisibility`
