### ISSUE TITLE
Couldn't open another project in new window

### ISSUE THREAD

**Issue by faradoxuz** [Microsoft/vscode#65665]
- VSCode Version: 1.30.1
- OS Version: Ubuntu 18.04

when I open new window and open another project, the project is opened in the window where I work, and new window remains empty

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by skywalker1905** [comment]
Same issue on Ubuntu 18.04, Ver1.30.1

About:
版本: 1.30.1
提交: dea8705087adb1b5e5ae1d9123278e178656186a
日期: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-42-generic

**Comment by octref** [comment]
How are you opening your project? Open recent? Or using the system file picker?

Are you using the custom title bar on Linux, and clicking the Open command from there?

**Comment by bpasero** [comment]
@faradoxuz are you trying to open the same folder in a new window maybe?

**Comment by faradoxuz** [comment]
> @faradoxuz are you trying to open the same folder in a new window maybe?

No, they are different folders. that's why I opened this issue

**Comment by bpasero** [comment]
@faradoxuz are you doing anything different from what I do here?

![before](https://user-images.githubusercontent.com/900690/50687955-843cfd00-1023-11e9-832f-f7fc1d2ac2dc.gif)

Does it reproduce if you configure `"window.titleBarStyle": "native"`?

**Comment by faradoxuz** [comment]
> @faradoxuz are you doing anything different from what I do here?
> 
> ![before](https://user-images.githubusercontent.com/900690/50687955-843cfd00-1023-11e9-832f-f7fc1d2ac2dc.gif)
> 
> Does it reproduce if you configure `"window.titleBarStyle": "native"`?

There is not any difference what you do there. and "window.titleBarStyle": "native"

**Comment by bpasero** [comment]
@faradoxuz so it does reproduce both with native and custom title style?

**Comment by XeniaSiskaki** [comment]
I have the exact same problem in Ubuntu. Configuring `"window.titleBarStyle": "native"` didn't help me either

**Comment by bpasero** [comment]
I am quite certain this is fixed with my fix for https://github.com/Microsoft/vscode/issues/65773

**Comment by matjaeck** [comment]
The bug is fixed in the current insiders build available at https://code.visualstudio.com/insiders/.
