### ISSUE TITLE
command palatte shows commands accordingly

### ISSUE THREAD

**Issue by wjiali6** [Microsoft/vscode#65660]
Issue Type: <b>Feature Request</b>

command palatte shows commands accordingly:
1.according to current file;
2.current project;

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.16299

**Comment by octref** [comment]
Please open issue with clear description as to what feature you want.
