### ISSUE TITLE
Path highlight in WSL terminal

### ISSUE THREAD

**Issue by Tarik02** [Microsoft/vscode#65667]
- VSCode Version: 1.29
- OS Version: Windows 10

Steps to Reproduce:

1. Create file 'file.txt' on disk D:
2. Echo '/d/file.txt' in integrated terminal
![image](https://user-images.githubusercontent.com/12175048/50423556-bef2a880-085f-11e9-9533-c43b5209fa03.png)
3. Echo 'D:/file.txt' in integrated terminal
![image](https://user-images.githubusercontent.com/12175048/50423571-f1040a80-085f-11e9-981a-e0dfec87ae77.png)
4. When you hover 'D:/file.txt', you can navigate to it:
![image](https://user-images.githubusercontent.com/12175048/50423582-011bea00-0860-11e9-99d1-4a1b07aba3ab.png)
While that does not happen to '/d/file.txt'.

NOTE: I use '/d' instead of default '/mnt/d' because I changed WSL disk mount path.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tarik02** [comment]
That's real issue because CLI applications, for example webpack, prints paths which are valid WSL paths, but now Windows's

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
