### ISSUE TITLE
File specific context menu entries not available until the first tab switch

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#65664]
Issue Type: <b>Bug</b>

When you start vscode freshly with certain files already open, the context menu entries contributed specifically for this file type don't show until you first switch editor tabs to something else and back. At least that's what I see with my vscode-antlr4 extension, both with a normal vscode start and when debugging the extension.

In this screen cast you can see the extension is loaded (the tooltip is produced by it):

![context-menu](https://user-images.githubusercontent.com/2398704/50420444-e4b78780-0836-11e9-8d86-8fcb96f0fc84.gif)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|32.00GB (9.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
duk-debug|Har|0.4.1
dot|Ste|0.0.1
numbered-bookmarks|ale|6.1.0
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.2
duk-debug|des|0.4.2
xml|Dot|2.4.0
tslint|eg2|1.0.42
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.7
svg|joc|0.1.4
vscode-phpfmt|kok|1.0.30
vscode-antlr4|mik|2.1.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.11.1
vscode-yacc|se2|1.1.0

</details>

**Comment by mike-lischke** [comment]
Is the base bug something publicly visible? If so, can you reference it here, please?

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/65041
