### ISSUE TITLE
Allow to copy paste files from native explorer into Code explorer

### ISSUE THREAD

**Issue by gaolinfeng** [Microsoft/vscode#6566]
- VSCode Version:1.1.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. copy a file in explorer
2. paste the file in vscode files tree

**Comment by mkszepp** [comment]
+1

**Comment by mbeckenbach** [comment]
drag and drop works. why not copy paste. :-)

**Comment by gaolinfeng** [comment]
ok, acceptable

**Comment by 0x80** [comment]
Where can I track this issue? The link to the milestone doesn't seem to work (https://github.com/Microsoft/vscode/milestone/8)
