### ISSUE TITLE
修改文件git不自动刷新。

### ISSUE THREAD

**Issue by DamonJY** [Microsoft/vscode#65662]
Issue Type: <b>Bug</b>

修改文件后git那里不自动检测是否修改文件并刷新。

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.47GB free)|
|Process Argv|C:\Users\Administrator\Desktop\第一版本1.0\we7_wmall|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.6
typings-autoinstaller|jvi|1.2.0
sftp|lix|1.8.4
vscode-language-pack-zh-hans|MS-|1.30.2
vetur|oct|0.14.3

</details>

**Comment by shane-smith** [comment]
Google Translate:
- **TITLE:** Modifying the file git does not automatically refresh.
- **MESSAGE:** After modifying the file, git does not automatically detect whether to modify the file and refresh it.

Perhaps the file is not being saved, which would explain why Git isn't detecting it. Try enabling the following in settings:

```
"files.autoSave": "afterDelay",
```

**Comment by octref** [comment]
@shane-smith, thanks for helping out!

@DamonJY If that doesn't solve your problem, add more details to your problem and reopen it.
