### ISSUE TITLE
console

### ISSUE THREAD

**Issue by sincsc** [Microsoft/vscode#6567]
- VSCode Version:1.1.1
- OS Version:win7 64bit

Steps to Reproduce:

1. The console always output messy code

2. and I do not  know where to set it correctly

**Comment by sincsc** [comment]
The console always output messy code

and I do not know where to set it correctly

**Comment by weinand** [comment]
@sincsc what console are you talking about? Please provide more details about your problem.

**Comment by jrieken** [comment]
@sincsc please report back - closing until more info is provided

**Comment by sincsc** [comment]
@jrieken @weinand thanks for your answers

**Comment by jianqiaoc** [comment]
I use the keras, but get the output like this
Epoch 1/50

  100/60000 [..............................] - ETA: 301s - loss: 544.4615
  500/60000
