### ISSUE TITLE
Font ligatures for hints/tooltips, debug console, output and problems

### ISSUE THREAD

**Issue by lukas-tr** [microsoft/vscode#65677]
Issue Type: <b>Feature Request</b>

Enabling font ligatures is currently only possible for text in the main text editor. It would be great if there are additional settings for enabling this feature for hints/tooltips, terminal, debug console, output and problems panels. 

`=>` with font ligatures enabled (editor):
![image](https://user-images.githubusercontent.com/36337818/50427086-b8cfec80-089e-11e9-9f23-05f872f2a557.png)

Font ligatures missing:
![image](https://user-images.githubusercontent.com/36337818/50427096-efa60280-089e-11e9-8c2c-cc0fda6a042a.png)

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Terminal tracked here: https://github.com/Microsoft/vscode/issues/34103

**Comment by isidorn** [comment]
fyi @bpasero @alexandrudima

**Comment by alexandrudima** [comment]
fyi @joaomoreno @jrieken

**Comment by coderkhayrul** [comment]
"editor.fontFamily": "Cascadia Code",
   "editor.fontLigatures": true
   // =>
