### ISSUE TITLE
Ctrl+/ not executing as expected

### ISSUE THREAD

**Issue by gggustafson** [Microsoft/vscode#65671]
VS Code Version: 1.30.0 (system setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

If I have a code fragment like:

```
for ( int i = 0; ( i < symbols_list.length ); i++ )
  {
  print ( symbols_list [ i ] );
  }
//     line_list = apply_rules ( symbols_list,
//                               line_ending,
//                               user_preferences );

// for ( int i = 0; ( i < line_list.length ); i++ )
//   {
//   print ( line_list [ i ] );
//   }
```
When I select it and press **Ctrl+/** I obtain:

```
// for ( int i = 0; ( i < symbols_list.length ); i++ )
//   {
//   print ( symbols_list [ i ] );
//   }
// //     line_list = apply_rules ( symbols_list,
// //                               line_ending,
// //                               user_preferences );

// // for ( int i = 0; ( i < line_list.length ); i++ )
// //   {
// //   print ( line_list [ i ] );
// //   }
```
In the documentation, **Ctrl+/** is to "Toggle line comment". So what I was expecting was

```
// for ( int i = 0; ( i < symbols_list.length ); i++ )
//   {
//   print ( symbols_list [ i ] );
//   }
    line_list = apply_rules ( symbols_list,
                              line_ending,
                              user_preferences );

for ( int i = 0; ( i < line_list.length ); i++ )
  {
  print ( line_list [ i ] );
  }
```
What have I done wrong?

**Comment by octref** [comment]
This is working as expected. Imagine you have code like this:

```js
// comment
function foo() {}
```

If toggling on both lines means first line's `//` get removed, the file would become invalid.

**Comment by gggustafson** [comment]
You are wrong!  The word "toggle" is defined as "a setting that can be switched between two different options by performing a single action" [Merriam-Webster]. That toggling a comment may cause a compilation error is not relevant. In my case, I was toggling between a test and a production mode. 

This needs to be fixed or the documentation repaired.

**Comment by octref** [comment]
It's the same behavior in Sublime and Atom. If you don't like it, you can write a command extension and bind it to Cmd+/ for yourself: https://code.visualstudio.com/api/extension-guides/command

**Comment by gggustafson** [comment]
Your response is intellectually disingenuous. You seem to believe that the current action in response to **Ctrl+/** meets the requirements for the shortcut. It does not! Requirements are obtained from published documentation. The documentation specifies "toggle." The current action in response to **Ctrl+/** does not toggle the state of the comment(s). 

"If you don't like it, you can write a command extension and bind it to Ctrl+/ for yourself" is arrogant and immature. You are not responding to the issue report. If you were the author of the code that performs the **Ctrl+/** response, I'd suggest that you accept the comments of others in the light in which they were given. That is the only way that VS Code will improve.

**Comment by octref** [comment]
Well, I’m just saying the way you hope it works would break the functionality for a lot of people. Now they can’t comment out a block with comments inside it. This is by design.

> That toggling a comment may cause a compilation error is not relevant.

It might not be relevant to you but it is to others.

**Comment by gggustafson** [comment]
I fear this discussion is now a distraction. The documentation needs to be repaired if the action is to remain as it currently is.
