### ISSUE TITLE
Intellisense order broken

### ISSUE THREAD

**Issue by qmarquez** [Microsoft/vscode#65675]
Issue Type: <b>Bug</b>

When Intellisense opens the suggestion came worst from the previous version of VSCode. On previous version of VSCode the intellisense sugestions put better results in order 
![image](https://user-images.githubusercontent.com/18141238/50426574-ec475280-086f-11e9-9789-76d8ed1f4ac3.png)
like you can see in the image above i want to acces the router property of this class, but the suggestion of the property appear further down on intellisense
![image](https://user-images.githubusercontent.com/18141238/50426597-cb333180-0870-11e9-9040-26e08799d2bf.png)
As you can see the scrollbar it's really down (like 25° result), the previous version of VSCode do this better

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.73GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
tslint|eg2|1.0.42
latex-workshop|Jam|5.19.0
language-haskell|jus|2.5.0
vscode-language-pack-es|MS-|1.30.2
csharp|ms-|1.17.1
material-icon-theme|PKi|3.6.2
prolog|reb|0.0.4

</details>

**Comment by qmarquez** [comment]
More bugs, i have this JSON 
![image](https://user-images.githubusercontent.com/18141238/50430220-925f8080-08a1-11e9-983e-6e484c56e153.png)
when i use it any of that property appear at the top 
![image](https://user-images.githubusercontent.com/18141238/50430250-ac995e80-08a1-11e9-8dd2-610f69d8fd61.png)

**Comment by jrieken** [comment]
You can control this via `"editor.suggestSelection"`
