### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by amitguptagwl** [Microsoft/vscode#65682]
Ubuntu update was failing to update vscode because of some error. So I'm trying to reinstall it manually by downloading deb file for Ubuntu. But facing the same error.

Package name: code_1.30.1-1545156774_amd64.deb
Error: 
```
dpkg: error processing archive code_1.30.1-1545156774_amd64.deb (--install):
 unable to open '/usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg.dpkg-new': Operation not permitted
```
I can find ths file on the same path

```bash
$ ll /usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/total 2688
drwxr-xr-x 2 root root    4096 Dec 26 11:33 ./
drwxr-xr-x 5 root root    4096 Feb  1  2018 ../
-rwxr-xr-x 1 root root 2742488 Jan 25  2018 rg*
```

- VSCode Version: 1.30
- OS Version: Ubuntu 17.10

**Update**
Same issue with "code-insiders_1.31.0-1545373230_amd64.deb"

**Comment by Tyriar** [comment]
@amitguptagwl did you use sudo to install?

**Comment by amitguptagwl** [comment]
yes

**Comment by Tyriar** [comment]
I just googled and it looks like the deb problem can be caused by anti-virus? It's likely a problem with your environment and not with VS Code https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1739991
