### ISSUE TITLE
code.visualstudio page links to localhost

### ISSUE THREAD

**Issue by besmosman** [Microsoft/vscode#65683]
- VSCode Version: Irrelevant
- OS Version: Irrelevant

Steps to Reproduce:

1. go to https://code.visualstudio.com/api/extension-capabilities/theming#color-theme
2. press "grammer" link

resulting url = http://localhost:3000/api/language-extensions/syntax-highlight-guide
expected url = https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by yume-chan** [comment]
It's best to file documentation issues to https://github.com/Microsoft/vscode-docs.

Anyway I've fixed it and submitted a pull request.

**Comment by octref** [comment]
Fixed and will be published soon. Thanks for noticing!
