### ISSUE TITLE
Integrated terminal crashed with error `Cannot read property 'style' of undefined`

### ISSUE THREAD

**Issue by bambooom** [Microsoft/vscode#65685]
- VSCode Version: Version 1.31.0-insider (1.31.0-insider) 2018-12-21T06:07:14.943Z
- OS Version: macOS Mojave Version 10.14.2

Steps to Reproduce:

1. Not sure how to reproduce, but the integrated terminal sometimes just crashed, I cannot scroll or
type. There is no error message.
2. Then I try to toggle the terminal down and up again, there will be an error alert: `Cannot read property 'style' of undefined` like this:
![screenshot 2018-12-26 at 5 12 10 pm](https://user-images.githubusercontent.com/14840170/50440858-fd0ccc80-0932-11e9-9ce1-c5ab3b87150d.png)

Does this issue occur when all extensions are disabled?: No

Errors from the Dev Tools Console:
![screenshot 2018-12-26 at 5 28 17 pm](https://user-images.githubusercontent.com/14840170/50441019-b9ff2900-0933-11e9-947a-7a4b62818a62.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/65702
