### ISSUE TITLE
Long Json Crashing VSCode

### ISSUE THREAD

**Issue by LarryC42** [microsoft/vscode#65689]
Issue Type: <b>Bug</b>

drag and drop a 49,511KB json document on vs code.  Json is on a single line.  VS Code pauses and then crashes.  Previous version would open and even reformat the document.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
mssql|ms-|1.4.0
python|ms-|2018.12.1
Go|ms-|0.8.0
PowerShell|ms-|1.10.2

</details>

**Comment by matjam** [comment]
also seeing this behaviour.

**Comment by rebornix** [comment]
@sandy081 may I get you help on this as extension host terminated in this case.

**Comment by sandy081** [comment]
Some extension is causing this here.

@LarryC42  Are you able to repro it by disabling all extensions? 

Also disable built in json extensions. You can find them by typing `@builtin json` in extensions viewlet.
