### ISSUE TITLE
Hard to search in user settings

### ISSUE THREAD

**Issue by sgon00** [Microsoft/vscode#65686]
Hi, I found this issue https://github.com/Microsoft/vscode/issues/24063

I think the proper behavior should be:

* search default user settings when the cursor was in left editor when pressing Ctrl/CMD-F
* search user settings when the cursor was in right editor when pressing Ctrl/CMD-F.

Click **Edit** > **Find** to search when the cursor was in right editor is really impossible to find out unless reading that issue's comment. 

Thanks a lot.

**Comment by roblourens** [comment]
You can change the keybinding of the `settings.action.search` command yourself if you want, but I don't plan to make changes to the defaults here.
