### ISSUE TITLE
Ability to hide groups

### ISSUE THREAD

**Issue by GHNewbiee** [microsoft/vscode#65695]
When you have more than one groups of files opened, for example:
- one group which accommodates database file(s),
- one group which accommodates server side file(s), and
- one group which accommodates client side file(s)

the ability to hide groups for saving space in the editor, by selecting group(s) in explorer, right click and choosing (un)hide, would be proved more convenient than switching between different code app instances or opening/closing individual files each time you need them.

**Comment by isidorn** [comment]
This would have to come from the editor group service. Forwarding to @bpasero 
Though I am not a fan of the idea

**Comment by GHNewbiee** [comment]
@isidom 
>Though I am not a fan of the idea

A rhetoric question: "Do I/you have serious grounds to be against that?
