### ISSUE TITLE
Cannot read property 'indexOf' of undefined (yes, again)

### ISSUE THREAD

**Issue by john-cj** [Microsoft/vscode#65696]
- VSCode Version: 1.30
- OS Version: Win 7

Steps to reproduce:

1. Create HTML file
2. Click menu > Terminal > Run Active File. It will be an error: `Cannot read property 'indexOf' of undefined`.

Then, if you try to reproduce second step again, it will work.

Also, another way to make it work is to manually run terminal before second step:

1. Create HTML file
2. Click menu > Terminal > New terminal
3. Click menu > Terminal > Run Active File

[There was closed issue](https://github.com/Microsoft/vscode/issues/60768) about `Cannot read property 'indexOf' of undefined` error, but it seems the error is still here, under described circumstances.

**Comment by Tyriar** [comment]
I can't reproduce on 1.30.1, here are some things that would help with the investigation:

- The file you're using and the selection you're trying to run
- Your settings.json file
- What shell your terminal is running
- When the error occurs, open devtools (Help > Toggle Developer Tools) and check the console. I'm interested in the stack trace and which line the exception is happening on

**Comment by john-cj** [comment]
Visual Studio Code is 1.30.1, was installed just today, on new PC. `settings.json` is blank. Also, no extensions.

> What shell your terminal is running

I suppose it's default terminal. I haven't changed anything.

The file is located at `C:\Users\John\Desktop`. 

![file](https://user-images.githubusercontent.com/18004961/50456406-44ac4c00-0965-11e9-9708-33367d07c39c.png)

The file type is associated with Chrome:

![filetype](https://user-images.githubusercontent.com/18004961/50456495-e59b0700-0965-11e9-83fc-29e02a5231af.PNG)

Here is what I have in console:

![after - copy](https://user-images.githubusercontent.com/18004961/50456619-e4b6a500-0966-11e9-926c-dd9cb7eb1f86.PNG)

I forgot to say, OS version is x86, SP1.

**Comment by Rg111Ga31** [comment]
I have the same problem every time I attempt to run the 'Active file' using Terminal
Windows 10 v. 1809 running on DELL XPS 8900
(base) C:\LearnPython\Projects\Sudoku\Python Scripts>fileInput.py
Python 3.7.1 64-bit ('base':conda)
VS Code 1.30.1 with python extension initiated from Anaconda Navigator 5
If I run using <f5>, program script seems to produce what I expect to see:
(base) C:\LearnPython\Projects\Sudoku\Python Scripts>cd "c:\LearnPython\Projects\Sudoku\Python Scripts" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\Garve\Anaconda3\python.exe c:\Users\Garve\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 64423 "c:\LearnPython\Projects\Sudoku\Python Scripts\fileInput.py" "

   This is file input String?
. . .  Length of line string =
81
Line =
710000000900010400460070902000090005003006100000003009007002050100000206000000070

   This is file input String?  as found in xtr(sVal)

710000000900010400460070902000090005003006100000003009007002050100000206000000070

(base) C:\LearnPython\Projects\Sudoku\Python Scripts>
using the python script:
import sys

def xtr(sVal):
    print( '\n   This is file input String?  as found in xtr(sVal)\n' )
    print(sVal)

if __name__ == '__main__':
  textFile = open("Puzzle.txt","r")
  line = textFile.readline()
  print( '\n   This is file input String?' )
  print(". . .  Length of line string =")
  print(len(line))
  print("Line =")
  print(line)

  if len(line) == 81:
    xtr(line)

  else:
    print( '\n' )     #  Advance 1 line  <CR/LF> on monitor screen
    print( 'Usage:   puzzle is an 81 character string ' ) 
    print( '  representing the puzzle read left-to-right, ' )
    print( '  top-to-bottom, and 0 is a blank' )
When I select 'New terminal' from the Terminal drop-down Menu and then 'Run Active File', the Notepad copy of the input script is displayed {as expected ?}.  If I clear/close all PROBLEMS, OUTPUT, DEBUG CONSOLE and TERMINAL spaces and return to a terminal '1:cmd' and again select Terminal tab and Run Active File
(base) C:\LearnPython\Projects\Sudoku\Python Scripts>"c:\LearnPython\Projects\Sudoku\Python Scripts\fileInput.py"

(base) C:\LearnPython\Projects\Sudoku\Python Scripts>
A second Notepad listing of the input script was generated suggesting the initial error was somehow associated with my not running the script from a unique folder with a unique .vscode folder.

My only remaining need is to determine where the "OUTPUT" from the print() statements is being sent.  Maybe an afternoon learning about the .vscode file contents can solve both of my problems.

**Comment by Tyriar** [comment]
Well the reason I had trouble reproducing is because it's already fixed! There's an if (!exe) check in https://github.com/Microsoft/vscode/commit/d236bfdd52d897f934aec98314a30e8c58e357de which resolves the issue.

**Comment by mikenils** [comment]
@Tyriar Well, good news. That is, the fix will be available for everyone in Code 1.31?

**Comment by john-cj** [comment]
@Tyriar  Well, good news. That is, the fix will be available for everyone in Code 1.31?
