### ISSUE TITLE
Integrated terminal is unusable/unreadable due to transparent or same foreground-background colors

### ISSUE THREAD

**Issue by ceefour** [Microsoft/vscode#65692]
Issue Type: <b>Bug</b>

Run any simple ExpressJS app using nodemon, or run any app in terminal that uses colors.

This seems to be related to #65275 and #57803 . However I believe it's different because the workaround (like `cls`) do not work, and the bug only happens with VSCode, and not with Windows Command Prompt. (see comparison screenshot below)

![image](https://user-images.githubusercontent.com/24123/50448213-59331900-0952-11e9-942e-c4fb82a9d7ab.png)

Changing the theme does not solve the problem. This happens on **all** built-in themes in VSCode, including the dark ones. (i.e., with the dark themes, it becomes black on black)

It happens with Visual Studio Code 1.30.1 and Windows 10 build 1809. However, if Windows 10 build 1809 is at fault, this problem only happens with VSCode, not the Windows cmd. And in my case, typing cls does not return everything to normal.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
cucumberautocomplete|ale|2.12.1
vscode-standardjs|che|1.2.3
erb|Cra|0.0.1
xml|Dot|2.4.0
prettier-vscode|esb|1.7.3
gc-excelviewer|Gra|2.1.26
Scala|itr|0.1.7
latex-workshop|Jam|5.19.0
prettify-json|moh|0.0.3
python|ms-|2018.12.1
azure-account|ms-|0.7.1
vscode-docker|Pet|0.4.0

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
