### ISSUE TITLE
Embedded terminal prints empty lines

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#65691]
Issue Type: <b>Bug</b>

I've updated to Git for Windows 2.20.1 and this started to reproduce. I'm completely unsure if this is related, also some Windows update came in recently. This is all the changes a can remember before bug started to appear, it wasn't reproducing on the same vscode version (1.29.1) before.

Now when i'm starting build job terminal is often printing empty lines instead of actual output. Attached `repro.zip` with example configuration for C/C++ extension. 

[repro.zip](https://github.com/Microsoft/vscode/files/2710331/repro.zip) <----- **attachment**

Steps to reproduce:

1. Open folder (repro)
2. Ctrl-Shift-P > Run Build Task
3. Select "build"
4. Toggle terminal, observe output
5. (Optionally) Repeat steps 2-3

Actual result:

![image](https://user-images.githubusercontent.com/993454/50447545-e5324a00-092c-11e9-975e-51140c49fcf4.png)

As can be observed on screenshot, it works OK in Git bash, but something breaks in embedded terminal.

Additional info:

* I tried switching `terminal.integrated.rendererType` between `dom` and `canvas`, but this doesn't do anything in for me
* Reverting vscode to 1.28.2 or upgrading to 1.30.1 doesn't seem to help either
* Disabling extensions (except C/C++) doesn't help
* Behavior can be changed by removing line `echo this breaks it` in `compile.bat`, if this line is **removed** then terminal starts to print VS version, but not the line "Terminal will be reused by tasks, press any key to close it.". If line re-added, terminal output breaks again.

My `settings.json`:

```json
{
    "telemetry.enableTelemetry": false,
    "update.channel": "none",
    "extensions.ignoreRecommendations": true,
    "workbench.startupEditor": "none",
    "workbench.statusBar.feedback.visible": false,
    "workbench.editor.enablePreview": false,
    "workbench.settings.editor": "json",
    "editor.minimap.enabled": false,
    "editor.insertSpaces": false,
    "editor.detectIndentation": true,
    "editor.renderIndentGuides": false,
    "editor.renderWhitespace": "none",
    "editor.folding": false,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "search.useIgnoreFiles": false,
    "C_Cpp.dimInactiveRegions": false,
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "debug.internalConsoleOptions": "neverOpen",
    "debug.toolBarLocation": "docked",
    "debug.openDebug": "openOnDebugBreak",
    "diffEditor.ignoreTrimWhitespace": false,
    "git.confirmSync": false,
    "git.inputValidation": "off",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "todohighlight.keywords": [
        "TODO",
        "FIXME",
        "XXX",
    ],
    "workbench.colorTheme": "One Monokai",
    "typescript.tsc.autoDetect": "off", // 1.29 thingy
}
```

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by alekseyt** [comment]
Additional info: when running `compile.bat` from actual terminal it prints everything as expected (same as running in Git bash). Reproducible only when terminal is used by build job.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
