### ISSUE TITLE
console layout error

### ISSUE THREAD

**Issue by xuliangzhan** [Microsoft/vscode#65690]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/34864213/50447125-0f4b3280-0954-11e9-9bb3-a69bc4c21a05.png)

Error displaying layout after opening terminal.
There are still problems after reinstallation.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (26.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-language-pack-zh-hans|MS-|1.30.2
color-highlight|nau|2.3.0
vetur|oct|0.14.3
vscode-icons|rob|8.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by Cerlancism** [comment]
Seems like this issue  <https://github.com/Microsoft/vscode/issues/65681> is addressed with <https://github.com/Microsoft/vscode/issues/65415>

I just updated windows to 1809 probably this is the cause.
