### ISSUE TITLE
 Cannot read property 'getLineCount' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#657]
Issue Id: <b> d6581fdb-bcec-43aa-f607-62b83e6d86fa</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/editor/contrib/codelens/browser/codelens.ts#L536:46 (CodeLensContribution.renderCodeLensSymbols)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/codelens/browser/codelens.ts#L536:46 (CodeLensContribution.renderCodeLensSymbols))<br />[/vs/editor/contrib/codelens/browser/codelens.ts#L451:10 (CodeLensContribution.onModelChange)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/codelens/browser/codelens.ts#L451:10 (CodeLensContribution.onModelChange))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1311:0 (_run)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1311:0 (_run))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L2072:0 (complete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L2072:0 (complete))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L2097:0 (argDone)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L2097:0 (argDone))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1440:0 (onComplete))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1176:0 (_notify))<br />    at Object.__dirname.undefined.F.enter (out/vs/workbench/workbench.main.js:1544:6040)<br />

**Comment by alexandrudima** [comment]
Dup of #830
