### ISSUE TITLE
Starting a new terminal has lines "blanking" on Windows 10 RS5

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#65704]
- VSCode Version: VS Code 1.30.1
- OS Version: Windows 10.0.17763.195 x64
- High DPI TV (In case it might be related).
- Nvidia display driver 391.35

Steps to Reproduce:
1. Open a new terminal.
2. Type something.

![vscode-terminal-issue](https://user-images.githubusercontent.com/24731903/50453887-98f70200-094c-11e9-8718-c265864d61d7.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803

**Comment by segevfiner** [comment]
So basically wait for the ConPTY support to land as no one whatsoever wants to debug WinPTY bugs ¯\_(ツ)_/¯
