### ISSUE TITLE
Stop notifying about updates

### ISSUE THREAD

**Issue by samrueby** [Microsoft/vscode#65705]
Issue Type: <b>Feature Request</b>

There's an update notificaiton every time I open the program. I don't wan't to see this notification.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
```json
"update.channel": "none",
```

**Comment by octref** [comment]
As @usernamehw mentioned, you can use that setting to disable updating.
