### ISSUE TITLE
"stash all changes" icon  show error.

### ISSUE THREAD

**Issue by Watson1990** [Microsoft/vscode#65715]
- VSCode Version:  1.30.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:
![tim 20181227102752](https://user-images.githubusercontent.com/21718955/50462731-2d4f7c00-09c2-11e9-932c-38bc28b1102e.png)
![tim 20181227102824](https://user-images.githubusercontent.com/21718955/50462734-304a6c80-09c2-11e9-93c9-f5840c52f510.png)

**Comment by joaomoreno** [comment]
This icon comes from Gitlens. cc @eamodio Maybe we need something more different there?

**Comment by eamodio** [comment]
@joaomoreno I'm open to alternatives. See also: https://github.com/Microsoft/vscode/issues/64423
