### ISSUE TITLE
VSCode terminal removes user from dialout group

### ISSUE THREAD

**Issue by LAK132** [microsoft/vscode#65718]
Issue Type: <b>Bug</b>

I am trying to communicate with /dev/ttyACM0 through the VSCode terminal, however the VSCode terminal seems to "remove" the dialout group from my user which is required to communicate with this device. 
Running `id` in MATE Terminal gives `groups=1000(lak132),4(adm),20(dialout),24(cdrom)...` but from VSCode I get `groups=1000(lak132),4(adm),24(cdrom)...`

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3213)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.73GB (1.06GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
cpptools|ms-|0.20.1
veriloghdl|msh|1.0.0

</details>

**Comment by Tyriar** [comment]
@LAK132 any ideas on what could cause this? I don't know anything about dialout groups. This is the code that's used to launch the pty https://github.com/Microsoft/node-pty/blob/master/src/unix/pty.cc

**Comment by LAK132** [comment]
I'm afraid I don't know much more about this issue, but after ***several*** reboots it appears to be working. Still strange that it took VSCode a while to start working while the MATE Terminal worked after the first reboot. This may well just be an issue on my end!

**Comment by Tyriar** [comment]
@jerch thoughts on this? Environment issue perhaps?

**Comment by jerch** [comment]
Hmm, @LAK132 are you using a containered version of vscode by any chance, like a snap or AppImage build?
A normal build for the platform should not alter the user rights by any means. The containered versions might run behind some app-armor shields, that have different privileges.

**Comment by LAK132** [comment]
@jerch I'm using whatever the .deb on https://code.visualstudio.com/ is

**Comment by jerch** [comment]
@LAK132 Thats odd. Can you check if the executable runs under some app armor or selinux security context? Please also check:
- really the same shells/binaries in vscode and mate terminal
- no other shell setup scripts invoked for either of them

On the background - the terminal in vscode does not magic in here, it does what any other terminal emulator would do (spawn a pseudoterminal with a shell that inherits privileges from the user running it). For a system native build this should not mess with group policies at all. Therefore I wonder whether there is some security thingy going on.
