### ISSUE TITLE
[Fea] Poor native support for existing CMake projects

### ISSUE THREAD

**Issue by yiakwy** [Microsoft/vscode#65719]
see problem https://github.com/vector-of-bool/vscode-cmake-tools/issues/618

VScode has no clear roadmap about integration of existing CMake projects . My worksation is Ubuntu 18.04 and I use clang and modular Cmake system. The most important feature of an editor is files indexing and visual editing. And VScode cannot handle it correctly if the target is an existing CMake project.

By importing CMake projects into the space, there is no clear way about how to configure a taks.json and c_cpp_properties.json. Indexing always broken, even though my cmake projects works very well.

Compared to experiences in Xcode (MacOS), one single instruction, everything will be done. Xcode brings much better experiences in CMake projects integration. Universal usage must not mean ubiquitously cumbersome. I hope a concrete work flow for CMake users provided provided that vscode is intended to support c++.

@bobbrow  @sean-mcmanus

**Comment by sean-mcmanus** [comment]
I think the VS Code team will want this to be reported at https://github.com/Microsoft/vscode-cpptools/issues . I don't think the VS Code team plans to add any support for CMake projects.

**Comment by octref** [comment]
As @sean-mcmanus mentioned, please report those issues to the extensions you are using.
