### ISSUE TITLE
Python Syntax highlighting/colors are still broken?

### ISSUE THREAD

**Issue by RebelCoderRU** [Microsoft/vscode#65713]
Hi!

There was a bug/discussion about this before here: https://github.com/Microsoft/vscode/issues/1467
But reading it, I see no resolution.

VSCode's Python syntax highlighting still broken after all plugins are installed. Here is an example of Monokai themes on VSCode and Sublime:

![](https://i.stack.imgur.com/mZLo1.png)

Is/Can this be fixed at all ? I see no way to modify JUST the syntax color scheme in VSCode. Sublime and Atom do not have that problem.

No matter what theme is selected, none of the methods are highlighted.

![image](https://user-images.githubusercontent.com/20476773/50462488-847f2d80-097d-11e9-8c25-bff176b408c9.png)

Regards.

**Comment by RebelCoderRU** [comment]
@nchammas @aeschli @bpasero @joaomoreno Any news on this ? C++ code highlighting seems to be fine, but not Python.

**Comment by octref** [comment]
Please report to https://github.com/Microsoft/vscode-python, with your Python extension version.

**Comment by RebelCoderRU** [comment]
@octref 
Can you please take a look at this post here: https://github.com/Microsoft/vscode-python/issues/2768

"We actually don't handle the syntax highlighting; it comes from VS Code who gets it from MagicPython."

So it seems it is not an extension bug?

**Comment by octref** [comment]
Ok, sorry. Does this start to happen with 1.30, or sometime earlier?

Can you also paste the py-imports code so I can try it?

**Comment by RebelCoderRU** [comment]
Thanks!

I am running this:

```
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.0-3-amd64
```


I only started using from 1.30.1, but from previous comments/bugs, it seems this problem was there since few version back.

If by py-imports code you mean some code you can copy-past into your editor, then jus tyryu what I have in the image above: 

```
import random
import datetime
import math

class Mapping:
    def init(self, iterable):
        self.items_list = []
        self.__update(iterable)

    def update(self, iterable):
        for item in iterable:
            self.items_list.append(item)

    __update = update

class MappingSubclass(Mapping):
    def update(self, keys, values):
        for item in zip(keys, values):
            self.items_list.append(item)


print(random.randint(1, 10))
print(math.radians(90))
print(math.sin(90))
print(math.degrees(3.5))
today = datetime.date.today()
print(today)

```

This is a basic example. It should at least highlight methods like 
os.**version**
math.**sin**(20)

![image](https://user-images.githubusercontent.com/20476773/50523464-30cd2b00-0ac8-11e9-8125-76e2c22918a6.png)

Also this is still true:
https://github.com/Microsoft/vscode-python/issues/2768

**Comment by octref** [comment]
Try this setting:

```json
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "meta.function-call.generic.python",
        "settings": {
          "foreground": "#FF0000"
        }
      }
    ]
  },
```

You can change the foreground to any color you want.
The problem is our bundled themes do not color that scope, so this syntax highlight is lost.

**Comment by octref** [comment]
@RebelCoderRU Well, that means adding that scope to the theme-extensions https://github.com/Microsoft/vscode/tree/master/extensions. I don't know if we usually do that (the guy maintaining themes is out of office).

**Comment by RebelCoderRU** [comment]
But syntax color scheme selection is absolutely needed. + syntax highlighting is actually broken (if you compare to any other editor) and this has been reported countless times and always has been closed.

What is the best way to go about requesting fix/addition of this?

**Comment by Astrantia** [comment]
@RebelCoderRU Use a different theme or create your own theme

**Comment by RebelCoderRU** [comment]
@Astrantia as it was mentioned in other closed threads on this matter, changing to any theme does not effect syntax highlighting in any way. It is always broken. I have also tried 30+ themes. No changes.

@octref but changing themes still does not fix syntax highlighting issue. Try it, switch between themes and see how functions and methods are never highlighted at all. Now with your little hack it is better but still not good.

So there is obviously a problem with correct syntax highlighting as there were more then 1 bug opened/closed on that matter.

**Comment by RebelCoderRU** [comment]
@octref I can see you have "added this to the Backlog milestone an hour ago"
Hope this will get looked at. Thanks.

**Comment by Astrantia** [comment]
@RebelCoderRU That's because the themes you are using do not color that scope. As I said either create  your own theme or edit the themes you are using. Separate ui color scheme and syntax color scheme is a completely different issue.

**Comment by octref** [comment]
Meanwhile you can take a look at https://code.visualstudio.com/api/extension-capabilities/theming for some info on theme colors vs syntax colors.

**Comment by aeschli** [comment]
The problem is with the scope that MagicPython uses for function references.

The issue is already filed: https://github.com/MagicStack/MagicPython/issues/127

**Comment by 1st1** [comment]
@RebelCoderRU MagicPython **does** parse function calls and assigns them a separate distinct scope "meta.function-call.generic.python".  It's now up to VSCode's syntax color themes to assign a color to that scope.
