### ISSUE TITLE
Simple GDB C++ debugging on VS Code fails with a NullReferenceException

### ISSUE THREAD

**Issue by GaurangTandon** [Microsoft/vscode#65712]
- VSCode Version: 1.30.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

Please refer to [this detailed Stackoverflow question](https://stackoverflow.com/q/53921413/2675672). In short, debugging even a simple C++ program with the following `launch.json` fails:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes/No

Yes (I needed to have C/C++ extension enabled though).

---------

A current workaround [suggested by mrCyborg](https://stackoverflow.com/a/53923420/2675672) is to put `externalConsole` to `false`, but I have no idea why that works. If it matters, I am using Zsh terminal as both my system default and my VSCode integrated terminal.

**Comment by isidorn** [comment]
More details https://github.com/Microsoft/vscode-cpptools/issues/2922
