### ISSUE TITLE
Add blue border to "No folder opened" section for visual consistency

### ISSUE THREAD

**Issue by mikenils** [Microsoft/vscode#65729]
// The original title of this section was "Blue border in outline section", but then I changed it. See comments below.

- VSCode Version: 1.30.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open outline section in Explorer
2. Click somewhere in "blank" space in this area. I marked click area with red circle.
3. It will add blue border to outline section. Looks like a bug.

![border - copy](https://user-images.githubusercontent.com/23511057/50477948-b3c68680-09df-11e9-9842-f9324ee497db.PNG)

Similar, but different: https://github.com/Microsoft/vscode/issues/41174

**Comment by yume-chan** [comment]
I think it just want to tell you where the keyboard focus is, and all views in the side bar have this behavior.

**Comment by mikenils** [comment]
> All views in the side bar have this behavior.

It seems most of them, but I found at least one which doesn't: it's the "No folder opened sections". Clicks on it's blank space doesn't add this border.

![untitled](https://user-images.githubusercontent.com/23511057/50481538-3a389380-09f3-11e9-9f58-e000c5b70d2f.png)

Still inconsistent, from my point of view.

**Comment by john-cj** [comment]
@jrieken  

> ...the sample your are comparing this too isn't a tree.

As I understand, you mean "comparing this to" (not "too")?

**Comment by john-cj** [comment]
@jrieken

...the sample your are comparing this too isn't a tree.

As I understand, you mean "comparing this to" (not "too")?

**Comment by joaomoreno** [comment]
@isidorn This is about the empty state of the explorer. The user expects it to take focus.
