### ISSUE TITLE
Cannot enable brackets matching for .log files even when "editor.matchBrackets": true is set for that language

### ISSUE THREAD

**Issue by GoBigorGoHome** [microsoft/vscode#65725]
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.  Open/create any .log file 
2. type `(xxxx)` or find a matching pair of brackets, and put the cursor at one bracket
3. No mark of matching brackets can be seen (a pair of transparent frames around the matching brackets are expected)

Does this issue occur when all extensions are disabled?: Yes

Maybe it's not a bug but a feature, and if that is the case, then how can I enable brackets matching for .log files?

**Comment by hediet** [comment]
This is because `(`...`)` is not configured for log files.

With the latest insider, you can override that:

```log
"[log]": {
    "editor.language.brackets": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"]
    ]
},
```
