### ISSUE TITLE
Need a customizable toolbar

### ISSUE THREAD

**Issue by DWAK-ATTK** [Microsoft/vscode#65722]
**Please search existing issues to avoid creating duplicates.**
I did.  And I'm extremely disappointed in how this request has been handled thus far.  I expect better from a company I give thousands of dollars a year to.

**Describe the feature you'd like.**
I don't know how a toolbar wasn't the very first thing implemented after the command palette.  It is essential.  Please add a customizable toolbar system:

* multiple toolbar support
* each movable
* each floatable
* each dock-able
* each configurable (with commands from the command palette, or external tools)

**Comment by octref** [comment]
What's the issue you have with custom title bar? https://code.visualstudio.com/updates/v1_30#_custom-title-and-menu-bar-on-linux-by-default

> I did. And I'm extremely disappointed in how this request has been handled thus far.

Can you point to the issues?

**Comment by DWAK-ATTK** [comment]
I don't have an issue with the custom title bar.  I'm not sure where you get that idea.  The issue I have is with the lack of a toolbar.    
But if the menubar was meant to be a replacement/alternative to a proper toolbar, it really missed the mark.

1.  It does not perform like a toolbar.
2.  It does not appear to be available on macOS.

As for the issue I was referring to, see #41309.  
Though that's really neither here nor there.  A proper toolbar is the topic of conversation here.
