### ISSUE TITLE
Terminal is not prompting any thing

### ISSUE THREAD

**Issue by manikantasayana** [Microsoft/vscode#65727]
I opend the terminal but it's not going to prompt any thing

It's not getting after 

"Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved."

not showing any thing to enter

**Comment by HymanZHAN** [comment]
I can confirm this happening on my machine as well. 

VSCode Version: 1.30.1

![vscode_powershell_no_prompt](https://user-images.githubusercontent.com/26806995/50487574-f29f1100-09cc-11e9-846c-7d2cca40c0fc.gif)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803

**Comment by manikantasayana** [comment]
y we need to type clear?
without typing clear it need to open
