### ISSUE TITLE
Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': connect ECONNREFUSED

### ISSUE THREAD

**Issue by HaseenaBegumShabudin** [Microsoft/vscode#65728]
Hi Team,

I have started seeing warnings for JSON files as below:

"_Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': connect ECONNREFUSED_"

This happened after I update the VSC with latest release

Could you please help in fixing this and finding root cause of this issue

Thank you

**Comment by interglobalmedia** [comment]
I am getting the same error. I also don't know if it is causing other issues in my projects as a result. Especially as relates to ports.

**Comment by octref** [comment]
Which version and what platform are you using? What's the repro steps?

**Comment by interglobalmedia** [comment]
I am on:

Version 1.30.0 (1.30.0)

The other thing that shows up in all my projects now is this warning:

Could not create temporary directory: Permission denied

This simply is there when I open VS Code in a directory I have just created via Terminal. Thanks!

As for the former issue, it has suddenly disappeared.

**Comment by octref** [comment]
Can you open that JSON in your browser? Do you have any firewall / proxy rules that filter internet traffic?

**Comment by HaseenaBegumShabudin** [comment]
Thank you octref for your time and response.

I tried to open the json file on browser and i am able to without any issues with firewall/proxy

**Comment by HaseenaBegumShabudin** [comment]
Yes, the issue is consistent
