### ISSUE TITLE
在用node调试js的时候，用console.log()

### ISSUE THREAD

**Issue by ztg-zlu** [Microsoft/vscode#65720]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
![11](https://user-images.githubusercontent.com/26703048/50464532-6391f900-09cc-11e9-8249-f329affb63eb.gif)

**Comment by yume-chan** [comment]
The debugger will evaluate the object when you actually expand it (for performance concern). 

As the debugging session already ended, you can't expand any logged values anymore.

You can make your script keep running (for example, set a breakpoint after logging), then try again.

**Comment by roblourens** [comment]
That is correct, thanks @yume-chan.

**Comment by ztg-zlu** [comment]
Oh, well, sometimes I don't want to debugger, I just want to see the results, okay?

**Comment by ztg-zlu** [comment]
Thank you, but I don't want it yet. If it's too much, it won't work，Just like chrome, it can unfold and collapse
