### ISSUE TITLE
Icon for menus

### ISSUE THREAD

**Issue by Kumar21** [Microsoft/vscode#65723]
Can we add menu icon to our created custom menu at menu bar.
Left side of menu title

**Comment by sbatten** [comment]
@Kumar21 Can you provide a graphic of your idea?

**Comment by Kumar21** [comment]
Sure,, I was talking about this feature..
![icon demo](https://user-images.githubusercontent.com/16679527/50833978-df9b2200-1378-11e9-9924-e51b9ceb124c.png)

I have tried to achive this by using HTML come inside back tick (` `) at  **MenuBar** . But I got issue during build as i can't pass HTML inside back tick for String type menues

**Comment by usernamehw** [comment]
Possible duplicate of #53868

**Comment by sbatten** [comment]
@usernamehw yep, thanks for the pointer
