### ISSUE TITLE
Cannot Open multiple files in seperate tabs

### ISSUE THREAD

**Issue by RajeshSivadasan** [Microsoft/vscode#65721]
Issue Type: <b>Bug</b>

Open folder. Click on a file. Click on another file. The recent file does not open in a separate tab. This was working fine before the latest update.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (4.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
csharp|ms-|1.17.1

</details>

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
