### ISSUE TITLE
window.titleBarStyle breaks global menu

### ISSUE THREAD

**Issue by pecigonzalo** [Microsoft/vscode#65739]
- VSCode Version: Code - OSS 1.30.1 (from Arch repo)
- OS: Arch Linux x86_64
- DE: KDE 
- WM: KWin
Steps to Reproduce:

#### Non Working
1. Set `"window.titleBarStyle": "custom"`
2. Open Code
3. You get "custom" title bar, but also breaks "Global Menu"

#### Working
1. Set `"window.titleBarStyle": "native"`
2. Open Code
3.Native title and global menu works

Does this issue occur when all extensions are disabled?: Yes

I assume this affects AppMenu on Gnome and other DEs

**Comment by sbatten** [comment]
@pecigonzalo I'd probably recommend sticking with native if you have a DE that supports a global app menu.

**Comment by pecigonzalo** [comment]
Ok, maybe we should tag this "wontfix", I dont know if you guys use tags or not, I believe its still a bug as de window decoration should not affect the menu.

**Comment by sbatten** [comment]
@pecigonzalo the setting affects menus and window decorations. all menus in the application are affected by this setting as see the title bar contains the menu bar with the custom setting.
