### ISSUE TITLE
VS Code able & not able to format CSS

### ISSUE THREAD

**Issue by 919Studios** [Microsoft/vscode#65737]
# VS Code able & not able to format CSS

- VSCode Version:  1.30.1
- OS Version:  NA
- Does this issue occur when all extensions are disabled?: ***YES IT DOES***

----------
**STEPS TO REPRODUCE:**

1.Format an HTML document with css inside style tags… ***WORKS NO PROBLEM***.

2.Format a CSS document with the SAME css, and VS Code cannot format.

----------

# THE ISSUE(s)
• VS Code CAN format CSS when syntax is set to HTML.

• When syntax is on CSS it cannot.

**Comment by octref** [comment]
VS Code can't format CSS out of the box. Consider installing one of the CSS formatter extensions: https://marketplace.visualstudio.com/search?term=css%20formatter&target=VSCode&category=All%20categories&sortBy=Relevance.

**Comment by 919Studios** [comment]
**Thank you for helping get this sorted out!**

Im attaching a gif that shows VS Code formatting CSS with its built-in formatter.  It will format CSS but only when that CSS is inside a <style> tag in an HTML document.  Put the same CSS into a CSS file and VS Code cant format it for some reason.  I hope this helps improve VS Code, its a great application :)

![example-of-my-github-issue-vscode](https://user-images.githubusercontent.com/20955174/50501782-d204a480-0a28-11e9-9a6d-d99872a037c4.gif)

**Comment by octref** [comment]
Yeah, that's the HTML formatter we bundled (JSBeautify)...It's working OK for some people, but it has some problems so we didn't continue making it the default formatter. You can install https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify.
