### ISSUE TITLE
Problem when renaming file

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#6574]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Have vscode open with ts compiler running and watching.
2. Create a new ts file.
3. Rename this file

Problem: it didn't rename this file, it created another one, leaving the original one with the old name.
Also ignored js file now appear on the file browser for one of those file.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8752
