### ISSUE TITLE
Using files.defaultLanguage shows wrong icon for untitled tab initially

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#65747]
Issue Type: <b>Bug</b>

1. Set `files.defaultLanguage` to something like `markdown`.
2. Open a new tab. The tab should have the Markdown icon, but it has the Plain Text icon. If you move to another tab then back, the icon will be updated.

This only started happening when I updated to 1.3, and it's still happening in Insiders.

I've got no extensions or settings (other than `files.defaultLanguage`) set.

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:14:53.023Z)
OS version: Darwin x64 18.2.0

**Comment by bpasero** [comment]
This is very likely a consequence of adopting `Promise`: When the tab opens we immediately render the icon, but the resource only gets the mode associated after a `Promise.then()` on the end of the tick.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73680
