### ISSUE TITLE
Not able to debug protractor test with 'sharding'  enabled with mocha framework

### ISSUE THREAD

**Issue by Jayasankar-m** [Microsoft/vscode#65741]
Issue Type: <b>Bug</b>

create a protractor test with mocha and in conf.js  give as  
shardTestFiles: true,
 maxInstances: 2,

try to debug the test
Bug
Not able to debug protractor test with 'sharding'  enabled with mocha framework

Please find the debug console info below
=============================================
C:\Program Files\nodejs\node.exe --inspect-brk=12393 node_modules\protractor\bin\protractor C:\autotest\UIA/conf_key.js 
Debugger listening on ws://127.0.0.1:12393/553fca8b-e59e-4b62-9ae7-a9e672c58aa0
[22:35:30] I/launcher - Running 2 instances of WebDriver
logger.js:158
[22:35:30] I/testLogger - 
logger.js:158
------------------------------------
[22:35:30] I/testLogger - [chrome #01-0] PID: 18968
logger.js:158
[chrome #01-0] Specs: C:\autotest\UIA\sampletest.json
[chrome #01-0] 
[chrome #01-0] Starting inspector on 127.0.0.1:12393 failed: address already in use
[22:35:30] I/testLogger - 
logger.js:158
[22:35:30] E/launcher - Runner process exited unexpectedly with error code: 12
logger.js:158
[22:35:30] I/launcher - 1 instance(s) of WebDriver still running
logger.js:158
[22:35:30] I/testLogger - 
logger.js:158
------------------------------------
[22:35:30] I/testLogger - [chrome #01-1] PID: 1456
logger.js:158
[chrome #01-1] Specs: C:\autotest\UIA\sampletest.json
[chrome #01-1] 
[chrome #01-1] Starting inspector on 127.0.0.1:12393 failed: address already in use
[22:35:30] I/testLogger - 
logger.js:158
[22:35:30] E/launcher - Runner process exited unexpectedly with error code: 12
logger.js:158
[22:35:30] I/launcher - 0 instance(s) of WebDriver still running
logger.js:158
[22:35:30] I/launcher - chrome #01-0 failed with exit code: 12
logger.js:158
[22:35:30] I/launcher - chrome #01-1 failed with exit code: 12
logger.js:158
[22:35:30] I/launcher - overall: 2 process(es) failed to complete
logger.js:158
[22:35:30] E/launcher - Process exited with error code 100
====================================================

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (8.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
vscode-eslint|dba|1.7.2
tslint|eg2|1.0.42
beautify|Hoo|1.4.7
robotframework|kei|0.2.8
python|ms-|2018.12.1
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.4.0
rf-intellisense|Tom|2.2.1

</details>

**Comment by isidorn** [comment]
These are not reproducable steps.
Please create an example minimal repository on github where we can reproduce this

**Comment by Jayasankar-m** [comment]
Please find the sample code [here](https://github.com/Jayasankar-m/sampleprotractortest)

- configure vscode to execute the command protractor conf.js
- on executing with IDE the test does not run. But can be executed in command line from command prompt
- if the 'shardTestFiles' option in 'conf.js' is set as false, then it will run in vscode IDE
(shardTestFiles option is used to run the tests in parallel)

**Comment by isidorn** [comment]
That repository does not have a launch.json. Please include a launch.json which you are using to run these

**Comment by Jayasankar-m** [comment]
added .vscode/launch.json.
I had installed protractor locally and was using 
`"program": "${workspaceFolder}/node_modules/protractor/bin/protractor" `

**Comment by roblourens** [comment]
I suspect that the sharding feature won't work for debugging. Here is some info on debugging Protractor tests in vscode: https://blogs.msdn.microsoft.com/wushuai/2016/08/24/debug-protractor-script-in-visual-studio-code/ and https://www.protractortest.org/#/debugging
