### ISSUE TITLE
"Default user settings" doesn't appear to the left of "User settings" page

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#65748]
Issue Type: <b>Bug</b>

If I go to Settings > Open settings (JSON), in Insiders, the searchable "Default user settings" no longer appears to the left of the "User settings". This was useful, to look up existing settings. 

Is this completely removed, in favor of the new settings UI, with no way of bringing it back?

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:14:53.023Z)
OS version: Darwin x64 18.2.0

**Comment by usernamehw** [comment]
```json
"workbench.settings.useSplitJSON": true,
```
