### ISSUE TITLE
Request for more granular zoom increments

### ISSUE THREAD

**Issue by alanosman** [Microsoft/vscode#65751]
Hello!

I code on a couple of 30" monitors with a resolution of 2560x1600 on each monitor.  On Windows 10, I find that zooming CTRL + [+ key] and CTRL + [- key] jumps too much of an increment and I cannot find a happy medium.  Either the font is too small, or too large.  I have my desktop set to the right font size, but Visual Code doesn't seem to give me that extra in-between zoom level that I would like

It would be nice to have a setting that lets me set the increment, maybe instead of steps of 1 we can define steps of 0.5,

You can see what I mean with the following screens - It would be nice to have a size in between (e.g. a 1.5 increment).

This is my visual code IDE with zoom level 0
![image](https://user-images.githubusercontent.com/2914981/50496893-5b07e580-0a01-11e9-93eb-1812225108dd.png)

This is my visual code IDE with zoom level 1 (the next increment up)
![image](https://user-images.githubusercontent.com/2914981/50496905-6ce98880-0a01-11e9-9416-e91337866aa6.png)

Thanks.

**Comment by usernamehw** [comment]
Have you tried extensions for zooming?

https://marketplace.visualstudio.com/items?itemName=wraith13.zoombar-vscode

https://marketplace.visualstudio.com/items?itemName=craigb85.custom-window-zoom

**Comment by alanosman** [comment]
@usernamehw - well thank you.  That solves my issue.  But, honestly, I never thought to go looking for "zoom" extensions.  Seems like something the IDE should handle properly natively.

**Comment by alanosman** [comment]
@octref not sure why you closed this. so hastily  This was a request to make granular zooming more native.  I still would prefer pressing CTRL+[+ key] and zooming at smaller increments rather than getting a plugin (perhaps a jump in 10% instead of 20%). The plugin requires that you move your mouse and click on a tiny + or - button in the status bar.  I know this sounds insignificant, but when you are coding all day and wear glasses, this minor detail becomes important.  Clicking on a UI widget while it works, is not an optimal solution.  So I would kindly request that this is re-opened and discussed.  Thanks.

**Comment by octref** [comment]
@alanosman Other than that extension, you can also adjust this with a number:

```
  "window.zoomLevel": 0,
```

0 - 1 is 20% increase, so you can choose 0.5, 0.25, etc.

I think many people rely on the current zoom behavior, so I don't think we can easily change the zoom interval for those commands. You can rebind the keybindings to the commands provided by extensions, for example

```
  { "key": "cmd+]",                 "command": "zoombar.selectZoom" },
```
