### ISSUE TITLE
Code outline does not work on remote ssh filesystem

### ISSUE THREAD

**Issue by andy-z** [Microsoft/vscode#65752]
- VSCode Version: 1.30.1
- OS Version: Win10 Pro

Steps to Reproduce:

1. Connect to remote filesystem using SSH protocol (e.g. using kelvin.vscode-sshfs extension)
2. Open any C++/Python or other type of files
3. Outline panel is always empty

Does this issue occur when all extensions are disabled?: Yes

I think there is a general problem with the support of remote filesystems, in addition to code outline spell check is broken too.

**Comment by octref** [comment]
Probably because C++ and Python extensions don't support it for remote files. You should open issues for the C++ and Python extensions instead.
