### ISSUE TITLE
Source.adapterData is not preserved across debug sessions

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#65758]
- VSCode Version: 1.30.1
- OS Version: All 

Steps to Reproduce:
In a debug adapter, I am returning `Breakpoint.source.adapterData` in response to `setBreakpoints`.  This property seems to be lost in subsequent debug sessions.

See also: #34511.

**Comment by isidorn** [comment]
Please try it out in insiders in about a week when there is an update and let us know if the fix solved the issue for you.
Thanks
