### ISSUE TITLE
Task output file links not working

### ISSUE THREAD

**Issue by benmillhouse** [Microsoft/vscode#6576]
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Run a test task with failures
2. Ctrl + click the filename link in the output, link never does anything

**Comment by benmillhouse** [comment]
Update on this, it looks like the link did finally work if I right-clicked while holding ctrl instead of left-click

**Comment by bpasero** [comment]
@benmillhouse how does the link look like?

**Comment by benmillhouse** [comment]
Closing - please disregard.  This was an issue with how my VM was setup.
