### ISSUE TITLE
How to make vscode merge show all merged changes?

### ISSUE THREAD

**Issue by ykfq** [Microsoft/vscode#65765]
- **Bug or Feature ?**  Feature

- **Description**

  We use VSCode to develop our devops pipelines, and keep environment values in different branches，each time I merge new features from **dev** to **master**, the environment values in master branch were overwrited, without any notifications. So I have to find out the wrong ENV values of dev in master 
 branch and reset them back manully.  That's really painful bacause I have no idea which files are changed by the merge action.

Is there a way to solve this ? If no, is it possible to add this feature below ?  
- Merge shows all conflic files and ask for manully modifying.  
  [As it is now]
- Merge shows all changed files and do not ask for manully dealing with.   
  [New feature looking forward to adding]

**Comment by joaomoreno** [comment]
I'm not sure I fully understand what you want. When Git isn't able to automatically merge a file due to conflicts, it keeps it in the Merge Changes group and it must be manually merged. VS Code shows the Merge Changes group. You should go through each file one by one and manually merge them.

**Comment by ykfq** [comment]
> I'm not sure I fully understand what you want. When Git isn't able to automatically merge a file due to conflicts, it keeps it in the Merge Changes group and it must be manually merged. VS Code shows the Merge Changes group. You should go through each file one by one and manually merge them.

Thanks @joaomoreno ,but I still want to make it more clearly.  
The behavior of git merge when it encountered conflicts is fine and I can deal with it.  
What I'm trying to describe is that when there aren't any conflicts, VS Code just merge them silently without showing any infomations. But but I using git branches to store different ENV variables and I don't want them got overwrittened.  So if VS Code shows these changes, I can deal with it mannully and decide that new features should be merged(keep the changes) and the ENV variables should not be (undo the changes).  The default behavior is to merge everything and wait for committing if I don't do any thing.

**Comment by joaomoreno** [comment]
How would you solve this without VS Code, just using the git CLI?

**Comment by ykfq** [comment]
I select **Undo Last Commit** after merge before syncing, the changed files will be listed under "CHANGES" so I can do the merge manully.

![image](https://user-images.githubusercontent.com/20741596/51469237-dfa11600-1dab-11e9-800b-f62be0c8df1e.png)

**Comment by joaomoreno** [comment]
> What I'm trying to say is that when there aren't any conflicts, VS Code just merge them silently without showing any infomations.

It isn't VS Code doing the merge, it's git. So, let me ask this again: how would you solve this without VS Code, just using the git CLI?

**Comment by ykfq** [comment]
Actually I did not find a proper way to undo the merge(include many commits) in one step using the git CLI, But VS Code's **Undo Last commit** did undo all the commits introduced by the merge.

Do you have any experience or suggests doing this using the git CLI ? That would be great appreciate.

**Comment by joaomoreno** [comment]
If you run `Git: Show Git Output` you'll see what git commands get run when running `Undo Last Commit`.
