### ISSUE TITLE
When switching indent mode, the drop-down list shows '使用 \\"Tab\\" 缩进'

### ISSUE THREAD

**Issue by varxzy** [Microsoft/vscode#65766]
Issue Type: <b>Bug</b>

When switching indent mode, the drop-down list shows '使用 \\"Tab\\" 缩进'

![image](https://user-images.githubusercontent.com/20296852/50505645-e93aa500-0aaf-11e9-9912-ab49db5d44c7.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
tslint|eg2|1.0.42
auto-rename-tag|for|0.0.15
vscode-language-pack-zh-hans|MS-|1.30.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.4
code-settings-sync|Sha|3.2.4
open-in-browser|tec|2.0.0

</details>

**Comment by Joelism** [comment]
@yume-chan I think there're some issues with the transition of translation platform to Microsoft Community MLCP.

Please compare the two files linked below using some semantic json diff tool. 

Before the transition:
https://raw.githubusercontent.com/Microsoft/vscode-loc/2e72e24b16bedf742b7ff67168fbe82c2b780d1c/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json

Latest:
https://raw.githubusercontent.com/Microsoft/vscode-loc/master/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json

>Note: Only main.i18n.json is listed above, other files have similar issues.

I asked them about how to modify accepted translations in MLCP, and they said that I needed to open an issue in https://github.com/Microsoft/Localization.

**Comment by aldonetti** [comment]
@dbaeumer can you move this to the https://github.com/Microsoft/Localization/ repo please? we'll fix it there. thanks! /cc @tesheng @shawndon

**Comment by dbaeumer** [comment]
I can't since I am not a member of that GitHub repository. Assigning to @danyeh

**Comment by shawndon** [comment]
Assign to production to validate.

**Comment by lukaschal** [comment]
Fixed as a part of this issue 15 days ago in a MLCP platform.

https://github.com/Microsoft/vscode-loc/issues/56

**Comment by shawndon** [comment]
Closing issue as fixed
