### ISSUE TITLE
Symbolic File Links Show As Modified

### ISSUE THREAD

**Issue by tibmeister** [Microsoft/vscode#65760]
- VSCode Version: 1.30.1 (user setup)
- OS Version: Windows 10 (1809)

I apologize if this ends up being something already asked and answered, my searches didn't reveal anything.

Basically, here's the issue I'm facing.  I have a git repo that I've cloned that actually run on Linux; it's Icinga2 to be precise.  The way they enable features is creating symlinks in the "enabled" folder to the actual feature in the "available" folder.  This is fine and works without issue, except when I open the folder in VSCode on Win10, these symlink files show as modified.

When I open them, it shows the actual path the symlink points to instead of the data of the pointed file.  Now when I do a git status, these files do not show as modified, so this is something in relation to VSCode.  Here's a screenshot of VSCode UI showing this

![image](https://user-images.githubusercontent.com/8305833/50502028-c1046500-0a21-11e9-974d-cc69bea51dc9.png)

git status shows clean, so not sure what's going on exactly but hopefully it's just something simple that's set in the settings and I'm just not seeing it.

Thanks in advance!

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/5970
