### ISSUE TITLE
Cannot configure proxy since the version v1.30.1

### ISSUE THREAD

**Issue by rwxdfbb** [Microsoft/vscode#65769]
Issue Type: <b>Bug</b>

V1.30.1无法配置代理，以前版本可以

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.99GB (9.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
vscode-astyle|chi|0.9.0
tuflow|dan|0.5.0
xml|Dot|2.4.0
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
beauty|yhp|0.0.2

</details>

**Comment by Tyriar** [comment]
> V1.30.1 can not configure the proxy, the previous version can

**Comment by NateLing** [comment]
translation :  The VSCode v1.30.1 cant configure proxy since the version v1.30.1   @Tyriar . @rwxdfbb  I think the better way  is  commiting an issue in english

**Comment by chrmarti** [comment]
@rwxdfbb How do you configure your proxy? Through the OS settings or VS Code settings? What are these set to? Thanks.
