### ISSUE TITLE
Opening a folder in new window is problematic

### ISSUE THREAD

**Issue by radres** [Microsoft/vscode#65773]
Issue Type: <b>Bug</b>

I press `ctrl+shift+N` to create a new window.

A windows pops up presenting me with shortcuts (Links). I press 'Open Folder' under Start section. The folder opens up in my OLD window not the new one.

I expect it to be opened in the new window.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (4 x 2903)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.79GB (4.45GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tasks|act|0.1.5
cpp-snippets|aga|1.0.1
python|ms-|2018.12.1
cpptools|ms-|0.20.1
bash-beautify|sha|0.1.1
vim|vsc|0.17.1

</details>

**Comment by bpasero** [comment]
@radres are you trying to open the same folder in a new window maybe?

**Comment by radres** [comment]
@bpasero, @chrmarti 

Below I linked the recorded representation of the bug.

https://youtu.be/qHQzaKBB52A

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/50695180-400a2680-103c-11e9-9a33-d8a9c0b83f5a.png)

**Comment by radres** [comment]
@bpasero reuploading in 10 minutes

**Comment by bpasero** [comment]
@radres does it reproduce if you configure: `"window.titleBarStyle": "native"` after a restart?

**Comment by bpasero** [comment]
I pushed a fix to ensure that the folder dialog knows from which window the request was made to open to ensure the thing opens in there.

**Comment by matjaeck** [comment]
The bug is fixed in the current insiders build available at https://code.visualstudio.com/insiders/.
