### ISSUE TITLE
Favorite Files

### ISSUE THREAD

**Issue by VladislavKostin** [Microsoft/vscode#65770]
Favorite files. Ability to mark files in a project as favorites and have them displayed in a separate subsection on the left. Or possibly as pinned tabs highlighted in different color and never closing or scrolling away. 

Reasons. I have some files I need to access way more than another, and finding them manually is too difficult, and the [Go to File] feature is nice, but sometimes I'd like to click instead.

**Comment by octref** [comment]
https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks
https://marketplace.visualstudio.com/items?itemName=kdcro101.favorites
