### ISSUE TITLE
crashing after certain amount of time

### ISSUE THREAD

**Issue by audacioustux** [Microsoft/vscode#65779]
- VSCode Version: 1.29.1
- OS Version: manjaro kde
- Installed Extensions:
`aaron-bond.better-comments
ACharLuk.easy-cpp-projects
ajshort.include-autocomplete
alefragnani.project-manager
alexisvt.flutter-snippets
bradlc.vscode-tailwindcss
CADENAS.vscode-glsllint
circledev.glsl-canvas
cpylua.language-postcss
darkriszty.markdown-table-prettify
Dart-Code.dart-code
Dart-Code.flutter
eamodio.gitlens
esbenp.prettier-vscode
formulahendry.docker-explorer
formulahendry.terminal
gcazaciuc.vscode-flow-ide
gencer.html-slim-scss-css-class-completion
jeroen-meijer.pubspec-assist
jock.svg
mhmadhamster.postcss-language
mrmlnc.vscode-postcss-sorting
mrmlnc.vscode-scss
ms-python.python
ms-vscode.cpptools
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
Nash.awesome-flutter-snippets
nickdodd79.gulptasks
Orta.vscode-react-native-storybooks
PeterJausovec.vscode-docker
quicktype.quicktype
robertohuertasm.vscode-icons
shinnn.stylelint
sldobri.daily
slevesque.shader
twxs.cmake
vector-of-bool.cmake-tools`

- Log: 
![image](https://user-images.githubusercontent.com/7238675/50519119-9a0e6780-0ae3-11e9-89bb-53f4a719df0f.png)

Does this issue occur when all extensions are disabled?: Not sure... seems like it doesn't.

**Comment by octref** [comment]
I guess this doesn't happen if you run `code --disable-extension`, right?

**Comment by audacioustux** [comment]
well... the problem isn't occurring anymore even in normal mode... dunno why or how... I was facing this for last 2 days... pfff... I'll give an update if the problem occurs again... thanks <3
