### ISSUE TITLE
lag when replaceing lots of python file

### ISSUE THREAD

**Issue by QingGo** [Microsoft/vscode#65777]
- VSCode Version: 1.30.1
- OS Version:Ubuntu18.04 OS

Steps to Reproduce:

0. My Computer use Ubuntu18.04 OS, with 4G memory and AMD P320 CPU, and my VSCode has installed a pylint plugin.
1. Open vscode at a folder that contain lots of python file (200+)
2. Use Ctrl + Shift + F to find a keyword at this folder, than replace it to another keyword
3. After pressed replace, 200+ of file window was opened and 200+ pylint process started at the same time and then computer become lagger and lagger until you can not do anything but close the power.
4. After restarted computer, open vscode again. VSCode will keep the 200+ files' windows that has been change but not save, and then 200+ pylint process started at the same time again. So I have to close the power again.
5. I think vscode should not open new windows when you do a search and replace at a folder, and limit the plugin to open too many process, and get user a way to open vscode without opening the files has been change but not save last time.

Thank you for reading.

Does this issue occur when all extensions are disabled?: Can not check

**Comment by QingGo** [comment]
After I uninstall pylint using
`pip uninstall pylint`
Finishly I can open the vscode, save all the files and close all the windows.

**Comment by octref** [comment]
Yeah that's really a pylint issue. You should probably open an issue at https://github.com/Microsoft/vscode-python
