### ISSUE TITLE
Spanish translation incorrect

### ISSUE THREAD

**Issue by nopesal** [Microsoft/vscode#65785]
Issue Type: <b>Bug</b>

When opening the Edit options at the top menu bar there is an option that says "Alternar Bloquear comentario". It is wrong, it should say "Alternar comentario en bloque".

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

**Comment by shawndon** [comment]
I confirmed with Spanish speaking support engineers that a previous post on the same matter already had been discussed. We agreed that this and others were incorrect.

"Alternar Bloquear Comentario" means "Toogle lock comment". It should be "Alternar Bloque de comentario."

"Alternar comentario de Linea" means "Toggle comment off the Line". A better translation would be 

"Alternar comentario en linea". ("Toggle comment in Line")

"Alternar Fragmento de codigo del usuario". Has Snippets in singular, should be plural.

They look like little errors, but they really confuse users about those functions.

I am assigning this to our vendor to change to the commercially standard forms

Thank,

Shawn

**Comment by lukaschal** [comment]
First two strings on review.

**Comment by lukaschal** [comment]
Target "Alternar Fragmento de codigo del usuario" not found in a vscode resources.

**Comment by shawndon** [comment]
I was lucky enough to be coincidently on site at the Microsoft Customer Support Center in Costa Rica working with Support Engineers to improve the international customer experience. I showed these terms to some support engineers and they were in agreement with my previous post.

**Comment by lukaschal** [comment]
Regarding the first feedback. Agreed and implemented.

SRC:	Toggle &&Block Comment
New TGT:	Alternar &amp;&amp;bloque de comentario

**Comment by lukaschal** [comment]
Regarding the second feedback. Don't agree. We are talking here about a comment of type "block" or "line", therefore in both cases it should be "de bloque" and "de línea". In Spanish, "en linea" means "online".

SRC:	Toggle Line Comment
TGT:	Alternar comentario de línea

**Comment by shawndon** [comment]
Thanks Luka.
