### ISSUE TITLE
Duplicate / missing font declarations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#65781]
I noticed that we seem to either declare some fonts redundantly or are missing font declarations for CYK languages.

**Redundant Declarations**
* [x] [`.monaco-workbench .terminal-message-widget`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/workbench/parts/terminal/electron-browser/media/widgets.css#L14) @Tyriar this came in via https://github.com/Microsoft/vscode/commit/7bcdf81179a6575082c9536b9c1abb32a4ef6a6f and its not clear to me why the rule in `shell.css` is not good enough
* [ ] [`SuggestEnabledInput`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/workbench/parts/codeEditor/electron-browser/suggestEnabledInput.ts#L284) @sandy081 @roblourens seems to be used in settings editor and extensions view, its not clear to me why the font has to be declared like that
* [x] [`.context-view.monaco-menu-container`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/base/browser/ui/menu/menu.css#L119) and [`.menubar .menubar-menu-items-holder.monaco-menu-container`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/base/browser/ui/menu/menu.css#L184) and [`.monaco-shell .monaco-menu-container .monaco-menu`](https://github.com/Microsoft/vscode/blob/f886dd4fb84bb82478bfab4a68cd3f31b32f5eb5/src/vs/workbench/electron-browser/media/shell.css#L19) @sbatten maybe a leftover from when the context view was not rooted within the shell? I would think we can remove the 2 rules in the widget itself (provided you drop in a rule for the standalone editor) and then we can even remove the third rule in `shell.css` possibly?

**Missing Declarations**
* issue reporter
* process explorer

@RMacfarlane both seem to declare the font as in `shell.css` (which is right because these are in separate windows) but miss the language specific overrides it seems (e.g. `:lang(ja)`, `:lang(ko)`, `lang(zh-Hans)`. If we support localization in these 2 windows as well, we need to have the same font rules. I also noticed that some fonts seem to be declared redundantly (e.g. `html` and `textarea`)

//cc @jrieken

**Comment by Tyriar** [comment]
No longer needed for the terminal 👍

**Comment by bpasero** [comment]
@roblourens I am not sure I can follow, the declaration of fonts for the suggest input seems to match with the workbench font and not the editor font?

**Comment by roblourens** [comment]
@rebornix do you have any idea for how to handle this for the editor? Language-specific font-family overrides in css: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/media/shell.css#L20

**Comment by sandy081** [comment]
I have no idea about this.

**Comment by bpasero** [comment]
This is good for a while now, we share the default font from here:

https://github.com/microsoft/vscode/blob/0681925277df77878322d2ad789b746f462a08c9/src/vs/workbench/browser/style.ts#L195
