### ISSUE TITLE
task.json: whenActive property

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#6578]
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.5

Steps to Reproduce:

```
task.json
{
    "version": "0.1.0",
    "command": "go",
    "isShellCommand": true,
    "args": ["run", "main.go", "index.go", "-name=test"],
    "showOutput": "always",
    "program": "${workspaceRoot}"
}
```

1) Press shift + command + B to start a build task
2)  Press shift + command + B to start a new build task

![image](https://cloud.githubusercontent.com/assets/863731/15429597/e782df7c-1ea1-11e6-9b9f-a5f730f688fd.png)

When you are debugging a web service it would be very handy if there was a json flag that kills the build process without warning.

Now I need to use the mouse to click on terminate every time I am changing a line of code and need to restart my build process that is a web server that never terminates on its own.

**Comment by dbaeumer** [comment]
We should make this a more happy experience. I addition to let the user control this we should add keyboard input to the message as well (e.g mnemonics to select an action)

**Comment by gertcuykens** [comment]
Doesn't need to be anything fancy for me thanks :)

```
task.json
{
    "version": "0.1.0",
    "command": "go",
    "isShellCommand": true,
    "killRunningTask": true,
    "args": ["run", "main.go", "index.go", "-name=test"],
    "showOutput": "always",
    "program": "${workspaceRoot}"
} 
```

I think most people would like it to be true by default? So that they only need to press shift + command + B once to start a new build and kill the current one.

**Comment by dbaeumer** [comment]
Moving to July because of the builder work. I suggest to implement the following:

add property whenActive which takes the following values:

"keepRunning" -> nothing happens the tasks is simply continuing running
"restart" -> terminate and restart
"auto" -> keepRunning if is a watching task, else restart
"showMessage" -> show a message to the user

**Comment by gertcuykens** [comment]
Maybe rename "showMessage" to "alert" and "keepRunning" to "continue" and display a log output `running` in console only without a alert message so you can verify the system is not hanging.

**Comment by dbaeumer** [comment]
Good suggestions.

**Comment by gertcuykens** [comment]
Maybe also add "exit" to simply terminate the running task, that shows a log message in console `task terminated by user`

**Comment by dbaeumer** [comment]
I need to move this to August since I will be out on vacation in July.

**Comment by dbaeumer** [comment]
To much catchup work in August. What I implemented so is to show only a auto closing message if the task is a watch task and the user tries t o start it again. Will also ease this implementation since the task system now tells a caller about the state of the system.

**Comment by use-strict** [comment]
Don't know if this is intended or not, but in the latest insider build, I can find no way to restart a watching task without reloading the window. When pressing CTRL+SHIFT+B I get "The task is already active and in watch mode.", with only a "Close" button. 
```
Version 1.5.0-insider
Commit 18f7fe90aa470ddc632c80388f84bf511afb7078
Date 2016-08-30T05:59:50.261Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

I would expect either the task to restart automatically or show me the "Terminate" button. I would prefer the second option.

If there is some new option affecting this behavior in tasks.json, it's not yet documented.

**Comment by dbaeumer** [comment]
@use-strict good catch. The thing is that most people are pressing Ctrl+Shift+B without remembering that the task was already running and needed to press escape. I will open a issue to provide a restart action.

**Comment by dbaeumer** [comment]
@use-strict you can always do F1 > terminate and select Terminate Task and then restart it.

**Comment by dbaeumer** [comment]
I need to make this a more overall experience. There is another bug around this: https://github.com/Microsoft/vscode/issues/7236. I am more and more leaning towards a status bar item that gives you more informaiton about the running task and what a user can do with it. Simply adding more configuration or changing exisit behaviour seems to make people unhappy.

**Comment by gertcuykens** [comment]
I think your original idea how to tackle this with one extra flag `whenActive` that accepts multiple values will be the best choice. You dont have to implement all values for now, just two options `alert` and `restart` and put alert as default when the flag `whenActive` is omitted in task.json, the alert value is the exact same behavior as in 1.1.1 Note that this solution doesn't affect anybody unless they really want to kill and restart their process when pressing cmd + b We can later reevaluate this behavior and even remove it without affecting any user who like the default

**Comment by mran3** [comment]
I like this feature 👍

**Comment by dbaeumer** [comment]
We decided to totally rework the way the task running system work and how we allow key bindings and especially handle Ctrl+Shift+B. See the discussion started here: #15179. To avoid unnecessary work I will merge this with the work planned for January to implement #15179.

**Comment by dbaeumer** [comment]
I re-implemented the task execution engine for Jan to use the terminal instead of the output window. Although not the default yet I will wait until the switch is final to provide support for whenActive. With the new engine this needs more thinking since the new engine support executing tasks in parallel. So we need to support a case as well to start the same task multiple times.

**Comment by jeremyfa** [comment]
It seems that there hasn't been a lot of activity regarding this feature. The ``whenActive`` option looks great and would be very useful as it would give a lot of flexibility, compared to the current _"task is already active, restart/terminate task"_ pop up, forcing us to click to a button which is pretty annoying imo

Any news on this 🙏😭 ?

**Comment by Gama11** [comment]
I've created a workaround for that annoying popup via a separate command to run tasks + the new tasks API:

https://marketplace.visualstudio.com/items?itemName=vshaxe.terminator

**Comment by alexr00** [comment]
Covered by this issue: #32264
