### ISSUE TITLE
Add option to disable markdown highlighting in JSDoc comments

### ISSUE THREAD

**Issue by futagoza** [microsoft/vscode#65780]
Would it be possible to add an option to disable the markdown highlighting in JSDoc comments?

```js
{
    // can be used to explicitly opt into disabling the default behavour
    "jsdoc.disableMarkdownHighlighting": false,

    // explicitly describes the default behavour, disabling it on `false`
    "jsdoc.highlightMarkdown": true,
}
```

As for my motive (or use case): it's distracting when using JSDoc types in plain JavaScript 😢

**Comment by mjbvz** [comment]
Depends on #53885

**Comment by mjbvz** [comment]
This functionality now ships as an extension: https://marketplace.visualstudio.com/items?itemName=bierner.jsdoc-markdown-highlighting
