### ISSUE TITLE
Context menu automatically gets triggered

### ISSUE THREAD

**Issue by razor09** [microsoft/vscode#65787]
- VSCode Version: 1.30.1
- OS Version: Ubuntu 16.04

It's hard to open context menu (in new design) by clicking mouse right button, because it closes immediately or trigger first point "go to definition". It seems double click triggered. I opened context menu in file system (folder, terminal) and it worked correctly. Probably it's not mouse bug.

**Comment by reishapira** [comment]
@razor09 I have this same problem, it started once the window styling was switched around from native to custom. Try to set **window.titleBarStyle** back to native, it seems to have fixed it for me.

**Comment by razor09** [comment]
@reishapira return to **window.titleBarStyle: 'native'** solves this problem. Thanks a lot.

**Comment by sbatten** [comment]
@razor09 when you hold right click, does the menu draw underneath the cursor? If so, can you provide a screen shot or gif of the entire vs code window?

**Comment by razor09** [comment]
@sbatten @joaomoreno 

On version 1.30.2 i watched the following:

I push mouse right button (holding it, like mousedown event) - context menu appears below, side (right, left) or above the mouse cursor.
If mouseup event was triggered when mouseover on one of the listed items in context menu - triggered that action over which the cursor.
If mouseup event was triggered when mouseout context menu - context menu still open, works correctly.
Probably due to the minimal cursor's movement event like a double click occurs.

Now I observe that the problem occurs on right click and context menu appears right side of the cursor. Below, above or left from the cursor was normally.

**Comment by rakkarage** [comment]
don't think it has anything do to with zoom? happens @ zoom = 1  too
![peek 2019-02-08 11-11](https://user-images.githubusercontent.com/962340/52490365-9403b000-2b92-11e9-85b4-760161ee37fa.gif)

**Comment by MMulthaupt** [comment]
Rather than trying to fix the math, maybe require at least X pixels of mouse movement in order for any of the menu items becoming clickable?

**Comment by joaomoreno** [comment]
The menu only comes up when releasing the mouse, so this appears to be fixed.
