### ISSUE TITLE
THML Snippets is Wrong

### ISSUE THREAD

**Issue by StavinLi** [Microsoft/vscode#65798]
Issue Type: <b>Bug</b>

now I update this product ,but when I edit some html,the plugin THML Snippets no working.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (7.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
vscode-color|ans|0.4.5
open-html-in-browser|cod|0.1.21
vscode-wxml|cod|0.1.9
gitignore|cod|0.6.0
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.2
vscode-stylesheet-formatter|dba|0.2.0
app-migrator|deb|0.0.6
githistory|don|0.4.4
xml|Dot|2.4.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.2.4
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vs-code-xml-format|fab|0.1.5
git-project-manager|fel|1.7.1
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.0
Hap|hap|0.0.8
beautify|Hoo|1.4.7
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.5.0
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
node-debug2|ms-|1.31.1
debugger-for-chrome|msj|4.11.1
gulptasks|nic|1.3.1
vetur|oct|0.14.4
vscode-jsp|pth|0.0.2
java|red|0.36.0
vscode-icons|rob|8.0.0
sass-indented|rob|1.5.1
html5-boilerplate|sid|1.0.3
indenticator|Sir|0.6.0
python|tht|0.2.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1
vscode-react-native|vsm|0.7.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2
gulp-run|yod|0.0.2
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/50551544-0948a080-0c37-11e9-9535-4af990ec535c.png)
