### ISSUE TITLE
TERMINAL can not display Chinese correcly

### ISSUE THREAD

**Issue by jwbecalm** [Microsoft/vscode#65794]
Issue Type: <b>Bug</b>

on windows 10
when writing a comment in code by Chinese, such as: // 错误，拷贝赋值操作符被禁用
then in the TERMINA, try to compile by g++,  if the above line has compiled error, it  can't display correctly in TERMINAL
.\03_2 deleted constructor.cpp:27:10: error: use of deleted function 'Z& Z::operator=(const Z&)'
     z3 = z1;   // é”?èˉˉ?????·è′?èμ??€??“??????|è￠??|??”¨

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.5
plantuml|jeb|2.10.1
cpptools|ms-|0.20.1
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1

</details>

**Comment by jwbecalm** [comment]
the source code is as follows: in the TERMINAL, when you compile it by g++, it can't display Chinese correctly.

#include <iostream>
using namespace std;

class X{ 
public: 
    X(); 
}; 
 
class Z {
public:
    Z();
    Z(const Z&) = delete;   // 声明拷贝构造函数为 deleted 函数
    Z& operator= (const Z&) = delete;   // 声明拷贝赋值操作符为 deleted 函数

};
int main(){ 
    X x1; 
    X x2=x1;   // 正确，调用编译器隐式生成的默认拷贝构造函数
    X x3; 
    x3=x1;     // 正确，调用编译器隐式生成的默认拷贝赋值操作符

    Z z1;
    Z z2(z1);  // 错误，拷贝构造函数被禁用
    Z z3;
    z3 = z1;   // 错误，拷贝赋值操作符被禁用
}

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
