### ISSUE TITLE
Unable to debug jest tests from CRA unless I have run npm run eject first

### ISSUE THREAD

**Issue by nimms** [Microsoft/vscode#65793]
- VSCode Version: 1.30.1
- OS Version: Mac 10.14.2

Creating a new bug request for this because all the other similar ones are closed.  Essentially I can't debug jest tests from an create-react-app app unless I run npm run eject first.  I've gone through all the previous bug requests, have set -disableOptimisticBPs etc and nothing worked until I finally tried running npm run eject
Steps to Reproduce:

1. Run create-react-app jest-test
2. Use the following launch.json
```   
{
      "name": "Debug CRA Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts",
      "args": [
        "test",
        "--runInBand",
        "--no-cache",
        "--env=jsdom"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ],
      "disableOptimisticBPs": true
    }
```

3. Set breakpoint in App.test.js
4. Run "Debug CRA Tests" launch config
5. Observe that breakpoint is not hit.
6. From terminal - run `npm run eject`
7. Add following config to launch.json
```
{
      "type": "node",
      "request": "launch",
      "name": "Jest All",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["--runInBand"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest"
      }
    }
```
8.  Change the following in package.json
` "testEnvironment": "node"`
9. Run "Jest All" debug config
10. Observe that it hits your breakpoint

Does this issue occur when all extensions are disabled?: Yes

I have confirmed this occurs in the vs-code insiders build from yesterday also.

**Comment by roblourens** [comment]
That launch config looks correct. There is some fine print on `disableOptimisticBPs`. You may still not hit the BP until rerunning the tests, or if you can break at a `debugger` statement in your script.

Does it work if you add a `debugger` statement to the top of the test script? Or if you rerun the tests by pressing `a` in the terminal?

**Comment by nimms** [comment]
ah this was my mistake.  I had hit enter to trigger a new run, but didn't press a to trigger re-running all tests that hadn't changed.  Classic...i spent a good 2 days of messing around on this.  I couldn't getting it running with the debugger statement, but pressing a worked for me.

**Comment by nimms** [comment]
I guess the only new piece of info for the record was that ejecting the react build seemed to allow my tests to run.  it's probably a config issue that is fixed by ejecting the jest config

**Comment by denis-ok** [comment]
@nimms 
I have same problem, what does you mean to 'press a' ?

**Comment by nimms** [comment]
Hi Denis
Run your tests with the debug launch config above. Wait for the first test run to finish. Peers enter to trigger a rerun. You’ll then get a message in your console saying that tests weren’t run since there are no changes. Then press a to trigger a full re-run. Took me a while to figure that one. Turns out I’m not great at reading instructions!

nim

**Comment by roblourens** [comment]
Glad that works for you. I added an extra note to our Jest debug recipe: https://github.com/Microsoft/vscode-recipes/tree/master/debugging-jest-tests#debugging-all-tests

**Comment by roblourens** [comment]
Yeah please share a repo, thanks.

**Comment by nimms** [comment]
Here’s the repo.  Just made it public.  git@github.com:nimms/gcuh-ed-intranet.git

If you run npm run eject on it, then jest debugging works, otherwise it doesn’t hit the breakpoints.

**Comment by roblourens** [comment]
Thanks for the repo. There is something very strange going on. It seems that the `--runInBand` flag is ignored, because when I run and attach, the test scripts are clearly not loaded in the process.

If I downgrade some deps to versions that work in another random project I have sitting around,

```
"react": "^16.5.2",
"react-dom": "^16.5.2",
"react-scripts": "2.0.4",
```

then debugging works fine. Gotta file something upstream...

**Comment by nimms** [comment]
hmm have just tried downgrading react/dom/scripts to those versions and it doesn't work for me.  Thank for looking into it, this has been causing me to tear my hair out.

**Comment by roblourens** [comment]
Have you successfully debugged the tests using chrome devtools? For me, it only works consistently when running a single test file, whether in chrome devtools or vscode.

**Comment by roblourens** [comment]
Ok, I'm not insane. That's exactly the problem and it's a bug in Jest that was fixed recently. I guess you just have to wait for that change to come down the pipeline https://github.com/facebook/jest/pull/7518. You should still be able to debug when running a single file at a time in the meantime.

The code makes it look like it should also work when not in 'watch' mode but I don't know how to start it like that.

**Comment by nimms** [comment]
Thanks again Rob.
