### ISSUE TITLE
C# application is built, but writing "dotnet run" in terminal runs another application. 

### ISSUE THREAD

**Issue by FarhadShariatzadeh** [Microsoft/vscode#65797]
- VSCode Version: Version: 1.30.0
- OS Version: Linux x64 4.18.0-13-generic

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by FarhadShariatzadeh** [comment]
I have checked all classes in the project folder and made sure only one class has "main" method.

**Comment by Tyriar** [comment]
What application is run? Also what's your vscode version, os and shell?

**Comment by FarhadShariatzadeh** [comment]
It's a Console application. The application which is run is writing "Hello World!", which I think is the very first console application I created in this project, and got rid of that after a while. I cannot find anything about it, though.
The VSCode Version is 1.30.0, and the OS Version is Linux x64 4.18.0-13-generic, and the shell is ".NET Core Launch (console)".

**Comment by FarhadShariatzadeh** [comment]
Problem solved. I removed all the Reference files and it solved the issue.
