### ISSUE TITLE
Unexecuted text sticks around in readonly debug console text area after session

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#65791]
Issue Type: <b>Bug</b>

Repro:

1. Start debug session
2. Type something into the debug console (don't execute)
3. When debug session ends it results in this:

![image](https://user-images.githubusercontent.com/2193314/50529983-33228b80-0aae-11e9-8153-0f5153e664f4.png)

When it's in this state, this is what it looks like when it's unfocused:

![image](https://user-images.githubusercontent.com/2193314/50529994-4b92a600-0aae-11e9-9a24-dcf5cdea9fa9.png)

I cannot edit/delete the text.

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:15:51.434Z)
OS version: Linux x64 4.15.0-43-generic

**Comment by isidorn** [comment]
By design the input is readonly while you are not debugging.
This feels like a corner case so I decided that when a debug input turns readonly that we only show the decoration if there is no text - since from your screenshot it looks like a glitch.
Otherwise the text will still be readonly.

**Comment by Tyriar** [comment]
👍
