### ISSUE TITLE
Git is showing over 5k changes

### ISSUE THREAD

**Issue by varksh05** [Microsoft/vscode#65808]
Issue Type: <b>Bug</b>

git is showing over 5k changes and it is not allowing to disgard the changes also

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
Can you elaborate?
