### ISSUE TITLE
[Extension API] executeCommand 'editor.action.goToDeclaration' returns immediately

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#65809]
Issue Type: <b>Bug</b>

I expected `executeCommand` to return once the `goToDeclaration` action has completed.

Sample Code:
```
    await vscode.commands.executeCommand('editor.action.goToDeclaration');
    console.log(vscode.window.activeTextEditor!.selection.start);
    await new Promise(resolve => setTimeout(resolve, 2000));
    console.log(vscode.window.activeTextEditor!.selection.start);
```

Console Output:
```
Object
line:502
character:15
Object
line:465
character:8
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.72GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
csharp|ms-|1.17.1
Go|ms-|0.8.0
vscode-docker|Pet|0.4.0
vim|vsc|0.17.2

</details>

**Comment by jpoon** [comment]
Do you have an example of how it should be called (ie. what are the correct arguments)? Don't see any docs or examples of a position being passed to `goToDeclaration`.

**Comment by jrieken** [comment]
Sorry, I had the wrong command in mind. Things should work the way you have written them. The editor must have a file open that support go to declaration, otherwise there are no restrictions.

**Comment by jpoon** [comment]
> The editor must have a file open that supports go to declaration and it must not be an embedded editor, otherwise there are no restrictions.

Yes, and yes. It probably helps if I had the file of where I ran `goToDeclaration`, but seeing the output of the sample code, you'll see that the cursor does move, it just takes a couple seconds to resolve, and there's on way to `await` it.

**Comment by jrieken** [comment]
There is actually one level of promises that we don't await. I will push a fix
