### ISSUE TITLE
emmet doesn't handle expressions with an attribute and multiple sub-elements with sub-elements

### ISSUE THREAD

**Issue by mrg0lden** [microsoft/vscode#65805]
First: I couldn't think of a better title for this issue, but I still think it's bad. I'm sorry for that.

I made sure that this issue is still present in the latest *vscode insiders*

- VSCode Version: 1.30.1 
- OS Version: Windows 10 1803 Build 17134 64bit

Steps to Reproduce:

1. This is the expression I tried `.field.has-addons[dir=auto]>label.label+(.control>input.input)+(.control>button.button.is-static)+p.help`
2. No intellisense pop-up apperas when I finish writing this expression nor does <kbd>tab</kbd> work.

Does this issue occur when all extensions are disabled?: Yes, my vs code insiders is extensions-free and it still occurs.

**Comment by octref** [comment]
That's a **very** long expression...What's the expected outcome?

NVM, found it in Atom...

```html
<div class="field has-addons" dir="auto">
  <label for="" class="label"></label>
  <div class="control"><input type="text" class="input"></div>
  <div class="control"><button class="button is-static"></button></div>
  <p class="help"></p>
</div>
```

**Comment by mrg0lden** [comment]
@octref Do you think it's a ram leakage issue? It always takes time before it happens, and it happens on my laptop (which has less ram) more frequently than my desktop. But I really never monitored ram while using vs code with emmet.

**Comment by octref** [comment]
> It always takes time before it happens, and it happens on my laptop (which has less ram) more frequently than my desktop.

So this bug only happens on one of your laptop but not the other?

I don't think VS Code expands this correctly, but if this does work for you please share your emmet config.

**Comment by mrg0lden** [comment]
@octref No, I'm sorry. I got confused and mixed up between this issue and another one.

**Comment by rzhao271** [comment]
@mrg0lden is the issue here that tab doesn't work? Because when I manually run the command "Expand Abbreviation" with that abbreviation, it works fine.

**Comment by mrg0lden** [comment]
@rzhao271 Yes, in fact, I tried running the command Expand Abbreviation but it didn't work as well. 

System info:
```
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by mrg0lden** [comment]
I just tried it again, it works on vscode insiders but not on my current vscode setup 😞
