### ISSUE TITLE
launch: program '' does not exist.

### ISSUE THREAD

**Issue by mammadkoma** [Microsoft/vscode#65818]
Hi
I can not install any program on my windows for network policies.
So I downloaded VS Code portable and open it.
Also I downloaded dot net core library zip file and extract it in : _C:\dotnet_
I opened vs code and open folder _C:\MVC_ and type _c:\dotnet\dotnet.exe new mvc_ in terminal.
Then _dotnet run_ command and project run perfectly.
Now I just want to start Debugging in vs code but give me error : _launch: program '' does not exist._

launch.json : 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/MVC.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/MVC.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

**Comment by mammadkoma** [comment]
No VS Code can not find dot net core cli because I can not install any program and I can not copy dotnet folder to _C:\Program Files_ because I have not the admin user pass.
Just tell me how can I set a setting for VS Code to define dot net code path to _C:\dotnet_?

**Comment by MarcoRossignoli** [comment]
@mammadkoma actually c# vs code extension is provided by Omnisharp you could try to ask also here https://github.com/OmniSharp/omnisharp-vscode/issues

**Comment by mammadkoma** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/2772
