### ISSUE TITLE
Resolve environment variables in terminal.integrated.shell* and terminal.integrated.shellArgs*

### ISSUE THREAD

**Issue by IonCaza** [microsoft/vscode#65817]
There is a similar bug reported #57452, however environment variables in Windows are not in the scope of the bug. If you have an environment variable with a space, when it is read in `terminal.integrated.shellArgs.windows` it results in the same error as in #57452 

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Create an environment variable with a space in it
2. Call that environment variable in the `terminal.integrated.shellArgs.windows` like so `%env_var%\\path`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I'm pretty sure shell args don't resolve environment variables, are you sure the error isn't saying that the `%env_var%\\path` arg is broken?

**Comment by IonCaza** [comment]
> 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

This is the error I'm getting just like in the other bug mentioned. The %env_var% is C:\Program Files\... So it definitely reads the environment variable but then fails to parse the space in it.

**Comment by Tyriar** [comment]
Can you share the exact setting you're using for `terminal.integrated.shellArgs.windows` and `terminal.integrated.shell.windows`?

**Comment by IonCaza** [comment]
Environment variable
`ProgramFiles = C:\Program Files`
`cmder_root = %ProgramFiles%\Cmder`

This environment variable is valid, given that it works in a `cmd` terminal:

> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
>
> C:\Users\r0ot>cd %cmder_root%
> 
> C:\Program Files\Cmder>

This settings.json doesn't work:
> {
    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k", "%cmder_root%\\\vendor\\\init.bat", "/noautorun"
    ],
}

and yields this error:
> 'C:\Program' is not recognized as an internal or external command, operable program or batch file.

This settings.json works:
> {
   "terminal.integrated.shell.windows": "cmd.exe",
   "terminal.integrated.shellArgs.windows": [
       "/k", "C:\\\Program Files\\\Cmder\\\vendor\\\init.bat", "/noautorun"
   ],
}`

**Comment by Tyriar** [comment]
@IonCaza thanks, looking into it.

**Comment by Tyriar** [comment]
I looked into it and my suspicion was right in that we don't support this yet. So I think cmd.exe is getting the %var% and resolving itself or something. When we do add this we would want to use [the syntax that other settings use](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) and it would end up looking like this:

```
{
"terminal.integrated.shell.windows": "${env:SHELL_PATH}",
"terminal.integrated.shellArgs.windows": [
"/k", "${env:SHELL_PATH}\\vendor\\init.bat", "/noautorun"
],
}`
```

I couldn't find a feature request opened for this so I'll use this issue.

**Comment by IonCaza** [comment]
Glad I could be of help : ) @Tyriar Happy New Year!

**Comment by Tyriar** [comment]
@IonCaza you too 😃

**Comment by skprabhanjan** [comment]
@Tyriar , Can I take a look at this ? 
Some starter points would be helpful :)

**Comment by stannynuytkens** [comment]
> I looked into it and my suspicion was right in that we don't support this yet. So I think cmd.exe is getting the %var% and resolving itself or something. When we do add this we would want to use [the syntax that other settings use](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) and it would end up looking like this:
> 
> ```
> {
>   "terminal.integrated.shell.windows": "${env:SHELL_PATH}",
>   "terminal.integrated.shellArgs.windows": [
>     "/k", "${env:CMDER_PATH}\\vendor\\init.bat", "/noautorun"
>   ],
> }`
> ```
> I couldn't find a feature request opened for this so I'll use this issue.

Any news on this? @skprabhanjan

**Comment by skprabhanjan** [comment]
I am working on it , needed some help from @Tyriar , have posted about the same :)

**Comment by stannynuytkens** [comment]
Great! 😁

**Comment by skprabhanjan** [comment]
@Tyriar , Sorry for the delay .
I was just figuring out on the most effective way to do this . The resolve helper function you told about - is this the one ? https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L80

And also just wanted to know how to get the env variable name from the the two settings ( string values which starts with ${env:SHELL_PATH} )
So should we do some sort of string operations only or is there any other way this is being done ?
Thanks :)

**Comment by Tyriar** [comment]
@skprabhanjan you could call into this function https://github.com/Microsoft/vscode/blob/9d7c89c5763798a909697403c1d90d7f8beed9bf/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L84 which should resolve the ${...} syntax to give us what we want.

**Comment by skprabhanjan** [comment]
@Tyriar 
I used `this._configurationResolverService.resolve(lastActiveWorkspaceRoot!, shellConfigValue.value); `, is this the rite approach ? and here i had to get `lastActiveWorkspaceRoot` by using various services.

And one more major clarification i needed is , I am using Mac and wanted to know **how to Test this** functionality ?

**Comment by Tyriar** [comment]
@skprabhanjan I think you'll get an error when a terminal fails, so you could put bad values in via the variable resolution and check the error to make sure it works. For example:

```
"terminal.integrated.shell.osx": "${env:TEST}" // Set TEST to some value in a terminal before launching code
```

Then try launch the terminal, you should get an error saying that the value in TEST was invalid, it didn't work if it literally says "${env:TEST} isn't valid" or something to that effect.

**Comment by skprabhanjan** [comment]
@Tyriar  , Sorry I was not available for these days.

Will update you on this issue in few days :)
