### ISSUE TITLE
Test: ESLint fix all command

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6581]
- [x] Windows **@kieferm**
- [x] OS X **@kieferrm**
- [x] Linux **@kieferrm**

Steps:
 - install eslint
- see https://github.com/Microsoft/vscode/issues/5654 how to setup eslint to get fixes
- F1>ESLint
- you should get a command to fix all auto-fixable problems
- execute it
- ensure that all problems are fixed.

**Comment by kieferm** [comment]
I believe I was tagged on this accidentally.  @kieferrm  is similar to @kieferm
