### ISSUE TITLE
vscode hangs when debug log level is enabled

### ISSUE THREAD

**Issue by mohamed-el-habib** [Microsoft/vscode#65812]
Issue Type: <b>Bug</b>

I'm using a java/maven spring boot application generated from [https://start.spring.io/](https://start.spring.io/) with web as `dependencies`.
When i enable a verbose log level (for exemple "logging.level.ROOT=DEBUG"), VS Code hangs and finish by stop responding. The only solution is to kill the process.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.43GB (4.03GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
scala|dal|0.0.5
FreeMarker|dco|0.0.9
java-decompiler|dgi|0.0.2
es7-react-js-snippets|dsz|1.9.5
vscode-open-in-terminal|fab|1.3.7
vscode-lombok|Gab|0.9.7
plantuml|jeb|2.10.1
run-in-terminal|kor|0.0.1
vscode-kubernetes-tools|ms-|0.1.14
Go|ms-|0.8.0
docker-compose|p1c|0.3.3
vscode-docker|Pet|0.4.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.2.0
vscode-manifest-yaml|Piv|1.2.0
vscode-spring-boot|Piv|1.2.0
java|red|0.36.0
vscode-yaml|red|0.2.0
markdown-preview-enhanced|shd|0.3.11
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.3
vscode-ansible|vsc|0.5.2

</details>

**Comment by weinand** [comment]
I'm not aware of a VS Code "logging.level.ROOT=DEBUG" setting. This must be an issue with the Java environment you are using.
