### ISSUE TITLE
Make different Icons for C/C++ header files

### ISSUE THREAD

**Issue by DemoCrazer** [Microsoft/vscode#65810]
![vscode_icon1](https://user-images.githubusercontent.com/26616056/50536803-b241bd80-0b9b-11e9-8c39-c02a97c1efc3.png)
![vscode_icon2](https://user-images.githubusercontent.com/26616056/50536805-b8379e80-0b9b-11e9-87b5-355f1a2ff067.png)

C header file's icon is same with C source file.
C++ header file's icon is same with C++ source file.

It would be better if C/C++ header files have different icons.

**Comment by misolori** [comment]
Thanks for the suggestion and we'll keep that in mind. Closing this as we don't want issues for each file type. See https://github.com/Microsoft/vscode/issues/60699#issuecomment-429208011.

**Comment by sean-mcmanus** [comment]
Hmm -- it still seems like showing a "C" icon for .h files (which are often C++ files) is a bug that VS Code itself should fix. Visual Studio correctly shows .h files with a "H" icon and so does the "VS Code Icons" theme extension.

**Comment by sean-mcmanus** [comment]
@misolori Thanks for the info. I filed a bug at https://github.com/jesseweed/seti-ui/issues/522
