### ISSUE TITLE
Terminal Buffer Curruption when resuming from sleep (using powerline font)

### ISSUE THREAD

**Issue by vivichrist** [Microsoft/vscode#65828]
- VSCode Version: 1.29.1
- OS Versions: Ubuntu 17.04 17.10, 18.04, Manjaro Illyria 18.0.1 (Gnome 3.30.2)

Steps to Reproduce:

1. Close lid of laptop or just engage sleep mode, with VSCode still active.
2. Open lid of laptop or resume from sleep mode.

When the PC has resumed from sleep several areas of the still running VSCode have visible graphical corruption. This is usually remedied by moving the side bar divider. But the corruption within VSCodes internal terminal remains and the only way to remove the corruption is to trash it and start a new one. This corruption happens only if Powerline font is not used in the terminal to display a fancy command line.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/58167
