### ISSUE TITLE
Hovers don't work after closing a context menu opened twice

### ISSUE THREAD

**Issue by marcoms** [microsoft/vscode#65821]
- VSCode Version: 1.30.1
- OS Version: Linux 4.18.0-13

Using the following steps I can make hover items impossible to trigger unless I select 'Show Hover' from my F1 menu.

Steps to Reproduce:

1. Right click on the editor to create a context menu
2. Right click elsewhere on the editor
3. Hover over some syntax
4. Click on it

Please see [this video](https://photos.app.goo.gl/7TwBPVhYLAYu6CeP9) for an example. This shows the hovers break regardless of the filetype.

**Comment by marcoms** [comment]
Actually this is less difficult to break than I thought. You can just click anywhere to close the second context menu and hovers will no longer work.

**Comment by isidorn** [comment]
This is due to the custom menus on linux, forwarding to @sbatten 
fyi @bpasero

**Comment by sbatten** [comment]
linux default is native context menus  now
