### ISSUE TITLE
Terminal tab 'Run Active File' option only creates NotePad display of python 3.7 script.

### ISSUE THREAD

**Issue by Rg111Ga31** [Microsoft/vscode#65829]
- VSCode Version:  1.30.1
- OS Version:  Windows 10 version 1809

Steps to Reproduce:

1.  Click Terminal tab
2.  Select 'Run Active file
       If first time for terminal prompt "Cannot read property 'indexOf' of undefiined error occurs.
Repeat a second time using the same terminal and the NotePad display of the .py script file appears.
If 'Run Python File from Terminal' selected from the Right Click menu:  The script produces the results expected.

Does this issue occur when all extensions are disabled?: Yes
The Right Click Menu now has only Change ..., Cut, Copy, Paste and Command Palette

I now hope I can recover the 3 Disabled extensions.  With the Python extensions disabled, I can no longer execute my scripts in any form.

**Comment by john-cj** [comment]
Have you seen Tyriar's answer here: https://github.com/Microsoft/vscode/issues/65696?

From what is answered, it seems it will be fixed in December/January, as I understand.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/65831
