### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by TonyLugg** [Microsoft/vscode#65824]
Issue Type: <b>Feature Request</b>

In VS 2017, you can drag a tab off to another monitor.  It would be nice to do this in VS Code.  Split pane is OK, but multiple windows is better.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

**Comment by TwanLuttik** [comment]
@patrickdemers6 i think @TonyLugg mean to say when you drag a tab out side the VS code window that it will open automatically a new window instead of dragging to another VS code window

**Comment by TonyLugg** [comment]
@patrickdemers6 @TwanLuttik As I mentioned originally, Visual Studio 2017 lets you drag a tab, which creates a separate window with the tab in it.  It does not open another instance of Visual Studio 2017, it is the same instance with a separate code window.
