### ISSUE TITLE
css的 filter: alpha(opacity: 50);参数报错

### ISSUE THREAD

**Issue by x6002z** [Microsoft/vscode#6582]
<trans data-src="- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2. 
" data-dst="- vscode版本：

 os版本：win7 64位
 
步骤。
。">- vscode版本：1.1.1
 os版本：
 
步骤。
。</trans>       css里面写 filter: alpha(opacity: 50);会提示错误，并且他之后的全部提示出错

简易代码：a {
    filter: alpha(opacity: 50);
    width: 13px;
    height: 13px;
    line-height: 13;
    margin-top: 13px;
    margin-right: 13px;
    padding-top: 13px;
}
全部提示有问题

**Comment by x6002z** [comment]
如果可以。。希望能中文回复。。不行的话。。。英文也可以。。。我可以慢慢查翻译。。

**Comment by rebornix** [comment]
I suppose the correct writing should be 

```
filter: alpha(opacity=50);
```

Use `=` inside `alpha` rather than `:`.

**Comment by Tyriar** [comment]
I think this is an old <=IE8 filter so I don't think we would want to tweak the grammar for that when it's long deprecated. https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#Different_opacity_with_hover
