### ISSUE TITLE
Incorrect terminal

### ISSUE THREAD

**Issue by 0jinxing** [Microsoft/vscode#65820]
- VSCode Version: 1.30.1
- OS Version: win10 1809

Steps to Reproduce:

1. select default shell -> PowerShell
2. open terminal
3. input anything (except enter)

Does this issue occur when all extensions are disabled?: Yes

![terminal](https://s1.ax1x.com/2018/12/29/Ff4uOP.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
