### ISSUE TITLE
intelisense ignoring default language choice

### ISSUE THREAD

**Issue by robblah** [Microsoft/vscode#65823]
Issue Type: <b>Bug</b>

set default language to c  (lower case, upper case - no difference)

create new file,
 type a "c" as the first letter of "char" 
but what intelisense it suggest: "class", "class1" or "classt"

why does it ignore default language chosen

only once file saved as .c does it get it right.

if default language is being ignored, why bother having it then?

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-43-generic

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.20.1

</details>

**Comment by octref** [comment]
Please report this to the cpptools extension you are using.
