### ISSUE TITLE
"initializing the JS / TS language resources"

### ISSUE THREAD

**Issue by VenancioAvila** [Microsoft/vscode#65827]
- VSCode Version: 1.30
- OS Version: Osx 10.14

Steps to Reproduce:

Every time I open a .js file is giving it. It keeps loading and eating processing.

**Comment by jurosh** [comment]
Might be related, I also get this `initializing the JS / TS language resources` for very long time when openning project. Performance report which might be related https://github.com/Microsoft/vscode/issues/65857

VS Code is nearly useless now, slowest like never before :o

**Comment by VenancioAvila** [comment]
Hello guys! I was resolve this uninstalling vscode and all installed packages. After that I discovered that the error was in a package called color-exchange, when it uninstalls everything returns to normal.

**Comment by mjbvz** [comment]
Thanks. Please file an issue against that extension so that they can fix this
