### ISSUE TITLE
[Request Change to Feature] Absolute path for Markdown Preview CSS

### ISSUE THREAD

**Issue by tecosaur** [microsoft/vscode#65837]
I would have this as a comment to #45260 but that's limited to collaborators now.

I find it quite anying that I cant give an absolute path such as `~/Documents/Markdown CSS Themes/theme1.css` to the `markdown.styles` setting. I understand the point made (security concern) when it is a workspace setting, and as a workspace setting being limited to local paths and urls isn't an issue for me.

However not being able to set a global `.css` file to use in the user settings is quite irritating for me, and for the User Settings file I don't think the security concern applies.

Thanks for the great work so far :)

tecosaur.

**Comment by tecosaur** [comment]
@mjbvz I can't see how this is "out of scope" myself, would you be willing to explain?

**Comment by mjbvz** [comment]
It's had 3 thumbs in like 8 months. It is not a popular enough request to warrant the cost of adding and maintaining it. We won't be addressed in the  foreseeable future
