### ISSUE TITLE
Fails to start when machine is not connected to the network

### ISSUE THREAD

**Issue by cpdupuis** [Microsoft/vscode#65830]
Issue Type: <b>Bug</b>

1. Enable "airplane mode" to turn off wifi.

2. From PowerShell, run "code"

Expected result: VS Code starts up

Actual result: Process crashes without showing any UI at all and prints this for a stack trace:

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (11.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.22.0
githistory|don|0.4.4
xml|Dot|2.4.0
gitlens|eam|9.2.4
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.8.0
PowerShell|ms-|1.10.2
gradle-language|nac|0.2.3
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1
vscode-wpilib|wpi|2019.0.0-beta0-pre1

</details>

**Comment by joekaiser** [comment]
I have experienced this as well, but I have yet to track down if it is an extension causing the problem or Code itself. @cpdupuis, do you have any extensions installed?

**Comment by joekaiser** [comment]
I have experienced this as well. The bug is even worse when you try to open Code using a shortcut - nothing happens. You only get the error when using the command line.

**Comment by kalpaj12** [comment]
Hi @cpdupuis , please find the open issue at https://github.com/Microsoft/vscode/issues/7570 
Also, this issue hasn't been addressed with any action since 2016. 
P.s. I've seen multiple issues pointing out the same, but all of them are either closed or unaddressed.
