### ISSUE TITLE
format docuement html with script tags

### ISSUE THREAD

**Issue by g8up** [Microsoft/vscode#65833]
- VSCode Version: 1.30.1
- OS Version: win7

Steps to Reproduce:

1.create a html file with script tag
```html
<!DOCTYPE html>
<html>

<head>
  <meta name=charset content=utf-8>
  <meta name=viewport content="width=device-width,initial-scale=1">
</head>

<body>
  <div id=app></div>
  <script type=text/javascript src=./static/js/manifest.f4da758734f1285b9c90.js> </script> <script type=text/javascript
    src=./static/js/vendor.8cab5d4b47dd6f32a39e.js> </script> <script type=text/javascript src=./static/js/getcrx.cn.2b4a14af5b72088a1f15.js>
    </script> </body> </html>
```

2.format document( shift + alt + f)

the formated code appears as above. <script/> tags haven't been once a line.
the html is generated by webpack4 plugin `HtmlWebpackPlugin`

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Well, we use js-beautify, and it's the same result: https://beautifier.io

Please report issue to them: https://github.com/beautify-web/js-beautify
