### ISSUE TITLE
How to link with Anaconda Python

### ISSUE THREAD

**Issue by Rg111Ga31** [Microsoft/vscode#65831]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Had trouble with integrated terminal dropdown Menu 'Run Active File'  selection only opening NotePad with copy of .py script but no execution.  Submitted problem to / MS VS Code.   One of the submission suggestions was to check for a later version of VSCode {Version: 1.31.0-insider (user setup)
Commit: e02e44464c02d617b98d0a3265bf5efef7794436
Date: 2018-12-21T06:20:35.852Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763}
to replace 1.30.1 I was using.   Unless I can connect the Integrated Terminal to my anaconda python (base) I have no way of determining whether the problem has been resolved.  This same problem faced TobiaShaw with a switch to VSCode 1.26.1 {#9960) which was closed by goanpeca with the statement "Not possible at moment.  You need to use the same type of install" which I presume will require a green logo above VS Code 1.31. ? above install [ or update application ] to be activated.

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (10.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   121	   632	code-insiders main
    0	   116	  2116	   gpu-process
    0	    70	  2632	   window (Issue Reporter)
    0	   185	  3768	   window (Settings - Visual Studio Code - Insiders)
    0	     6	 12040	     winpty-process
    0	    64	  7204	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    10	  9928	       console-window-host (Windows internal process)
    0	    55	 12972	     extensionHost
    0	    13	 16268	     electron-crash-reporter
    0	    76	 15148	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
vscode-yaml|red|0.2.0

</details>

**Comment by Tyriar** [comment]
That's because you configured windows to have py files to open in notepad, you need to change that in Windows.
