### ISSUE TITLE
Issue with Terminal placement

### ISSUE THREAD

**Issue by Abhinav3718** [Microsoft/vscode#65838]
Issue Type: <b>Bug</b>

Hello Team,
Command prompt which is like C:\> is not placed correctly. Please find the attachment for your reference. I have clean installed the latest version of VS code.
It is getting some empty space above that prompt.
![screenshot 1](https://user-images.githubusercontent.com/24957075/50548934-c27c9a00-0c7a-11e9-8efb-70ebbe7fcad1.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.88GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by saites** [comment]
What does your terminal look like if you just open `cmd`?

**Comment by arrebole** [comment]
Me too, I thought it was a problem with PowerShell.

**Comment by Abhinav3718** [comment]
> What does your terminal look like if you just open `cmd` outside of VSCode?

It looks normal outside of VSCode.

**Comment by Abhinav3718** [comment]
> Me too, I thought it was a problem with PowerShell.

Don't know...for both Powershell and Command prompt terminal in VS Code, I noticed the same thing.

**Comment by arrebole** [comment]
It still has a space, I have obsessive-compulsive disorder, it’s too bad.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
