### ISSUE TITLE
Something going on when using react

### ISSUE THREAD

**Issue by justisGipson** [Microsoft/vscode#65845]
Issue Type: <b>Bug</b>

Occasionally when writing something in a react app, I'll encounter something where a variable is declared and initialized and then once it's called it will say that it is declared but never read. When I've have confirmed that is was used right the only solution to fix this has been to completely close out visual studio code and re-open it. Once this is done the issue resolves itself.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.2
gitlens|eam|9.2.4
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.7
vscode-exec-node|mir|0.5.0
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.6.2
LiveServer|rit|5.3.1
code-spell-checker|str|1.6.10
language-stylus|sys|1.11.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by justisGipson** [comment]
Not sure, I haven't experienced again since the night I submitted the bug
report and restarting my machine. Could've been a one-off thing. If it
happens again, I'll disable all extensions and try and report on it.

- Justis Gipson
   (317) 605- 4164
   Linkedin <https://www.linkedin.com/in/justis-gipson-00275216a/>

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this. If you are still seeing the issue, please let me know

**Comment by justisGipson** [comment]
No worries, thanks for keeping it open. I'll send an update if it happens
again.
