### ISSUE TITLE
Don't ask for privilege while updating if installed into %ProgramFiles%

### ISSUE THREAD

**Issue by H1KHC** [Microsoft/vscode#65849]
Issue Type: <b>Bug</b>

Can it ask for privilege when updating?

---

I just installed it into my %ProgramFiles%
and each time I want to update it,
it warns like this:
"C:\Program Files\Microsoft VS Code\unins000.exe"
"Error while trying to create directory in the target dir:"
"Access denied"

So each time I want to actually update it, I have to close it and reopen it as administrater, which is not convenient.

---

screenshot:
![temp](https://user-images.githubusercontent.com/30046636/50554172-c64b0380-0cf0-11e9-891e-a30a5a1aa179.png)
(sorry for not using English in the picture)
(But I won't translate it again :P)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.99GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
Please install the System Installer: https://code.visualstudio.com/docs/?dv=win64
