### ISSUE TITLE
typescript intellisense for none imported classes

### ISSUE THREAD

**Issue by mhamri** [Microsoft/vscode#65841]
- VSCode Version: 1.30.1
- OS Version: windows 10

Steps to Reproduce:

1. install `@angular/cli` globaly, create a new fresh app, 
2. `install --save @angular/animations`
3. go to app.module.ts and in the imports type `BrowserAnimationsModule`. while typing you will not get any intellisense
4. when typing finished, all done and correctly, try to press ctrl+. to get autoimport but doesn't work

Does this issue occur when all extensions are disabled?: Yes/No
Yes, i uninstalled all the extension

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
