### ISSUE TITLE
Deadly need the "git view file history" functionnality

### ISSUE THREAD

**Issue by MatthieuScarset** [Microsoft/vscode#6584]
Would you please consider adding this new functionnality to VSCode ?

I would require the following:
1. Right click on a file in the left File Explorer sidebar
2. Select "View file history"
3. A copy of the "Search" panel opens up with all previous commits for the selected file

:+1: 

Thanks

**Comment by Krzysztof-Cieslak** [comment]
Similar functionality implemented in https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

**Comment by joaomoreno** [comment]
#68
