### ISSUE TITLE
Emmet 1.0.0 in VScode 1.30

### ISSUE THREAD

**Issue by markakeller42t** [Microsoft/vscode#65847]
Issue Type: <b>Bug</b>

As I understand it VS Code 1.30 should contain Emmet 2.0. My installation contains Emmet 1.0.0

I tried uninstalling and reinstalling but same thing.

What is not working is the Emmet suggestions which as I understand it is part of Emmet 2.0

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.2
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
tslint|eg2|1.0.42
MagicPython|mag|1.1.0
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|7.0.24
python|ms-|2018.12.1
PowerShell|ms-|1.10.2
vsliveshare|ms-|0.3.1071
LiveServer|rit|5.3.1
vscodeintellicode|Vis|1.1.2
jinja|who|0.0.8

</details>

**Comment by markakeller42t** [comment]
Here's my extension information for the builtin extension Emmet:

Name: Emmet
Id: vscode.emmet
Description: Emmet support for VS Code
Version: 1.0.0
Publisher: vscode
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vscode.emmet

**Comment by markakeller42t** [comment]
I have it working now as documented in Emmet 2.0 on the VSCode site. I found I needed to uninstall the django and python extensions.

**Comment by ramya-rao-a** [comment]
Emmet 2.0 as referred to in https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0 refers to the version of emmet libraries and not the version of the built-in emmet extension.

The python extensions shouldn't have any effect on the emmet features as they essentially work on different file types. The former on python files, the latter on html or css files.

If you see the issue again after installing the python extensions, please re-open this issue
