### ISSUE TITLE
VSCode performance is really bad

### ISSUE THREAD

**Issue by jurosh** [microsoft/vscode#65857]
Issue Type: <b>Bug</b>

VScode is really slow after latest update. It's nearly usable, seconds delays before each action

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.18.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 897)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 8, 5|
|Memory (System)|11.62GB (3.00GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
tslint|eg2|1.0.42
prettier-vscode|esb|1.7.3
reasonml|fre|1.0.38
vue-snippets|hol|0.1.10
search-node-modules|jas|1.3.0
solidity|Jua|0.0.49
hex-rgba-converter|med|1.0.4
vscode-code-outline|pat|0.2.1
vscode-docker|Pet|0.4.0
vscode-versionlens|pfl|0.22.0
vscode-graphql|Pri|0.1.6
vscode-icons|rob|8.0.0
partial-diff|ryu|1.4.0
quokka-vscode|Wal|1.0.174

</details>

**Comment by bcdady** [comment]
I feel the most negative performance impact when I'm trying to use the new OUTLINE panel (in Explorer Side Bar) and while using Code Spell Checker [streetsidesoftware.code-spell-checker]. I most often work with PowerShell and Markdown files, and it seem that when the PowerShell Integrated Console is running (in Terminal, as required for OUTLINE at least), is when Code feels most laggy.

**Comment by jurosh** [comment]
Sorry will try to gather more info soon just was super busy past few days,
in meantime tried to turn off some extensions and looks like that vscode is small little bit faster - still far from ideal.
