### ISSUE TITLE
Line-up, line-down seems to be broken when multiple lines are selected

### ISSUE THREAD

**Issue by FriskyDev** [microsoft/vscode#65854]
When using selecting multiple lines and moving them up/down with the Alt-Uparrow/Alt-Downarrow, the text gets malformed and messes up the buffer.

When doing this with a single line selected, it seems to work fine.

Note that this is not 100% of the time. But, if you select two lines and start moving them up, you will within a few moves see the corruption.

I see the same behavior on Windows, Linux, and Mac.

**Comment by rebornix** [comment]
It's probably messed up with auto indentation, which you can turn off via `editor.autoIndent`.

**Comment by FriskyDev** [comment]
But, why should I have to turn that off? This used to work fine.

You are just closing it, but no real explanation.
