### ISSUE TITLE
Default thread name is displaying "<No Name>" in call stack.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6585]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch an app and open folder which contains code for Multi-threaded app.
2. Debug any multithreaded application (I tried with C#).
3. Verify call stack.

Actual: If user not provided thread name explicitly then call stack it is showing up <No Name> for all the active threads (except main thread).
Expected: Can we provided some default name> May be some thread ID or method name associated with thread.
![image](https://cloud.githubusercontent.com/assets/17735796/15436912/fa6d93da-1e78-11e6-859a-ea0c14cc07f3.png)

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#361
