### ISSUE TITLE
Unreachable code error still exists

### ISSUE THREAD

**Issue by tarakra-kore** [Microsoft/vscode#65853]
Issue Type: <b>Bug</b>

when some code in the program becomes  "Unreachable code detected", It is still showing the same message, when the necessary changes are made.
can you please check? 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2583)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.56GB (0.58GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
gitlens|eam|9.1.0
gitblame|wad|2.6.3

</details>

**Comment by egamma** [comment]
@tarakra-kore please provide detailed steps for how to reproduce the problem.
