### ISSUE TITLE
Why can't I use VSCode?

### ISSUE THREAD

**Issue by ILSYT** [microsoft/vscode#65859]
- VSCode Version:1.30.0
- OS Version:Win7 32bit

I can install it.But when I try to run it, it doesn't work. Is there anything wrong with VSCode, or with my computer?

**Comment by kalpaj12** [comment]
Hi @ILSYT ,
Try connecting to the internet and then start VSCode.
For more info please look into the https://github.com/Microsoft/vscode/issues/7570

**Comment by ILSYT** [comment]
@kalpaj12 Thank you for your advice. But my computer is always online, so it couldn't be the reason.

**Comment by egamma** [comment]
@ILSYT please provide more information on what does not work. Do you see any error message?

**Comment by ILSYT** [comment]
@egamma Nothing at all. I just double click on it.Then I wait for a long time,but nothing happened.

**Comment by ILSYT** [comment]
@egamma Just now I tried again. I can't used it normally,but when I runned it under compatibility mode it worked. Maybe it can't be compatible well with Win7 32bit.(On Win7 64bit it works well)

**Comment by SultanBin** [comment]
@egamma i also have problem with VS Code!Can You Help?

**Comment by egamma** [comment]
Can you try to start VS Code from the command line in a console window, e.g. by typing 'code'. Do you see an error message?

@ILSYT what exactly do you mean by?

>I runned it under compatibility mode it worked

**Comment by ILSYT** [comment]
@egamma Sorry,I'm a Chinese so I can't use English well...Maybe you can try to translate this.
在兼容模式下，它能够正常运行。也许它与Win7 32bit兼容性不够好。

**Comment by SultanBin** [comment]
ok by
