### ISSUE TITLE
 ctrl + shift - not aligning text to rtl/ltr

### ISSUE THREAD

**Issue by danbete** [microsoft/vscode#65855]
Issue Type: <b>Feature Request</b>

when clicking:
left  ctrl + left  shift  - the text should be aligned to the left
right ctrl + right  shift  - the text should be aligned to the right

this is realy important to rtl people as some time its easier to edit text in this way and switch back to coding...

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by itailewin** [comment]
In notepad ++

![image](https://user-images.githubusercontent.com/12676316/53048758-29117d80-349e-11e9-8029-3c268bf921b0.png)

**Comment by NotWearingPants** [comment]
#4994

**Comment by alexdima** [comment]
Let's track in #4994
