### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Karthik-Sharavana** [Microsoft/vscode#65852]
Issue Type: <b>Bug</b>

Hi,

When i open terminal in vs code , it opens the terminal , but there will be no path in the terminal and im not able to write anything in that terminal...

My windows os is 10, and VS code v.1.30...

After updating to latest windows version, it is not working..

Even i should use internet to open VS Code, previously it was offline.. 

Please help me out all these problems..

Thank you.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.2.9200

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
html-slim-scss-css-class-completion|gen|1.2.0

</details>

**Comment by Karthik-Sharavana** [comment]
![annotation 2018-12-31 131028](https://user-images.githubusercontent.com/45279271/50556312-7f173f80-0cfd-11e9-8403-70abc3a57cf1.jpg)

I have opened the terminal neither the path nor i'm able to type in that terminal....

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
