### ISSUE TITLE
Syntax colors removed after VSC update...

### ISSUE THREAD

**Issue by laurengranada** [Microsoft/vscode#65863]
Issue Type: <b>Bug</b>

I updated visual studio code, and now my syntax colors are gone...yet the theme's background color remains, just white text now

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.40GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
gitlens|eam|9.2.4
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.7
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
vetur|oct|0.14.4
LiveServer|rit|5.3.1
trailing-spaces|sha|0.2.11
vuetify-vscode|vue|0.2.0

(2 theme extensions excluded)

</details>

**Comment by egamma** [comment]
@laurengranada 
>and now my syntax colors are gone...yet the theme's background color remains, just white text now

For what language? Do you see the same behaviour for other languages?
Please provide detailed steps so that we can reproduce the problem.

**Comment by laurengranada** [comment]
The language specified is 'Vue'. I just changed it to others to test out the syntax coloring, and it is not an issue for them...seems to be only happening in Vue.

As for steps...I'm not sure what to list out...I literally did nothing but opt in for the VSC update hahah

**Comment by egamma** [comment]
Coloring for vue is provided by the veture extension, please report the issue against this extension.

**Comment by laurengranada** [comment]
Okay, thank you for your help!
