### ISSUE TITLE
Option to put debug control block in title bar

### ISSUE THREAD

**Issue by ucavalcante** [microsoft/vscode#65865]
will be greate if we can dock the debug control in title bar like this image i made.

![vscode new menubar](https://user-images.githubusercontent.com/13587928/50562229-83415e00-0cf9-11e9-94b2-2e41ee1a3446.png)

**Comment by thenem** [comment]
although setting debug.toolBarLocation to "docked" helps me keep the tool bar from hiding my code, it would also be nice to have the option to dock to title bar. is this something that is still in the backlog?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/61336
