### ISSUE TITLE
Info about what "installs" vs "downloads" means

### ISSUE THREAD

**Issue by 76784** [Microsoft/vscode#65874]
The Visual Studio Marketplace provides two metrics for usages of your extension: "installs" and "downloads". But there is no information about what these two metrics really mean. Are people downloading the extension but not installing it? Are "installs" done directly from the editor? Do "installs" equal "downloads" minus uninstalls?

It would be nice if there could be just a little bit of information about what these two things mean. Perhaps a circle-with-question mark next to the metrics, with a popup that tells what they mean. Thanks.

**Comment by egamma** [comment]
please provide your feedback on how to improve the presentation to the marketplace team using: vsmarketplace@microsoft.com.

A user will **install** an extension once, but then there are additional **downloads** whenever there is an update to an extension.

**Comment by 76784** [comment]
That's interesting to know. I think that information should be communicated to the user, which is why I submitted a feature request. 

And knowing what you've told me, I think that "downloads" is a totally irrelevant metric (why should "downloads" matter? what matters is how many users have it installed), and should be considered for removal from display.

**Comment by egamma** [comment]
@76784 I agree with you and showing both numbers is on the migration path towards only showing a single number.

As I mentioned above, please provide this feedback to the market place team using the email address I have provided.

**Comment by jabacchetta** [comment]
Was also confused by this and agree that "active installs" would be a more interesting metric.
