### ISSUE TITLE
TypeScript Language Basics - Module Import Snippet Violates tslint Rules

### ISSUE THREAD

**Issue by tparikka** [Microsoft/vscode#65872]
Issue Type: <b>Bug</b>

In the "TypeScript Language Basics" snippet set, the "import statement, Import external module" snippet reads `import { } from "module";`. However, this violates a tslint rule stating that single quotes should be used in TypeScript strings `" should be 'tslint(quotemark)`.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>
Extensions: Angular v7 Snippets 7.0.1, AngularDoc for Visual Studio Code 6.1.3, C# 1.17.1, Debugger for Chrome 4.11.1, HTML Boilerplate 1.0.3, Powershell 1.10.2, TSLint 1.0.42, XML Tools 2.4.0.

**Comment by mjbvz** [comment]
You can create your own snippet for this or install an extension that provides snippets with the quote type you would like
