### ISSUE TITLE
Error en la Terminal

### ISSUE THREAD

**Issue by jmrp81** [Microsoft/vscode#65880]
Issue Type: <b>Bug</b>

Al abrir la terminal en la última actualización, la pantalla aparece negra ya que no se posiciona al inicio, al hacer scroll se observa como sale la información del copyright pero no se visualiza la entrada de texto.

Al pulsar sobre cualquier tecla es cuando se visualiza el texto  otra vez pero con el scroll desplazado.

Capturas de pantalla en el orden de la descripción:
* Al abrir la terminal
![image](https://user-images.githubusercontent.com/5754543/50572085-20170080-0db9-11e9-8ed5-b5232867eb44.png)

* Desplazar el scroll:
![image](https://user-images.githubusercontent.com/5754543/50572094-3c1aa200-0db9-11e9-9ac3-49f7f3c6e531.png)

* Al intentar escribir una entrada en la terminal:

![image](https://user-images.githubusercontent.com/5754543/50572103-666c5f80-0db9-11e9-832e-682a199383a9.png)

*  Resultado de ejecutar la instrucción:

![image](https://user-images.githubusercontent.com/5754543/50572122-bf3bf800-0db9-11e9-8028-9605b8e6cff8.png)

* Al hacel ctrl + c para cancelar es cuando ya sale la línea de lectura de la terminal:

![image](https://user-images.githubusercontent.com/5754543/50572114-a895a100-0db9-11e9-8417-f5d5a3399e11.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.60GB free)|
|Process Argv|C:\Users\jmrp8\Desktop\Asturias NetConf\AsturiasNetConf|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
git-easy|bib|1.11.0
htmltagwrap|bra|0.0.7
java-run|cao|1.1.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.5
phpcs|ika|1.0.5
angular2-switcher|inf|0.2.0
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|7.0.1
vscode-csharp-snippets|jor|0.3.1
react-native-snippet|jun|0.5.0
vscode-todo|Mat|0.8.0
vscode-language-pack-es|MS-|1.30.2
mssql|ms-|1.4.0
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
jscs|ms-|0.1.9
node-debug2|ms-|1.31.1
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.4
typescript-hero|rbb|3.0.0
java|red|0.36.0
vscode-icons|rob|8.0.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.4
javascript-typescript|sou|0.0.7
autoimport|ste|1.5.3
spellchecker|swy|1.2.13
vscode-arduino|vsc|0.2.24
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1
vscode-react-native|vsm|0.7.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
