### ISSUE TITLE
Sql Server : Unexpected Query behavior Reported @ 'Case When'

### ISSUE THREAD

**Issue by jithuin** [Microsoft/vscode#65883]
-- Type the following Query in SQL Query window
---------------------------------------------
select Entrydate, (Case when Entrydate Between Getdate()-15 And Getdate() then 'D0-D15 Days'
	  when Entrydate Between Getdate()-30 And Getdate()-16 then 'D16-D30 Days'
	  when Entrydate Between Getdate()-60 And Getdate()-31 then 'D31-D60 Days'
	  when Entrydate Between Getdate()-90 And Getdate()-61 then 'D61-D90 Days'
	  when Entrydate Between Getdate()-120 And Getdate()-91 then 'D91-D120 Days'  
	  when Entrydate Between Getdate()-150 And Getdate()-121 then 'D121-D150 Days'  
	  else 'D150 Days +'
	  End) from
(
select cast('2018-12-01 09:25:36.000' as Datetime) as Entrydate
union all
select cast('2018-12-02 09:25:36.000' as Datetime) as Entrydate
union all
select cast('2018-12-03 09:25:36.000' as Datetime) as Entrydate
union all
select cast('2018-12-04 09:25:36.000' as Datetime) as Entrydate
) as X
where Entrydate Between Getdate()-35 And Getdate() 

select getdate()
![bug reported](https://user-images.githubusercontent.com/1970125/50573053-879d7200-0df2-11e9-8e25-7cf0456286ff.png)

**Comment by usernamehw** [comment]
This is vscode repo. Are you sure this is the right place for this issue? It looks like Visual Studio.

https://stackoverflow.com/questions/30527522/what-are-the-differences-between-visual-studio-code-and-visual-studio

**Comment by egamma** [comment]
@usernamehw thanks for chiming in.

**Comment by jithuin** [comment]
> @usernamehw thanks for chiming in.

Thank you any way for the response .. 
It was a mistake. any way we resolved this issue with sql server team

Regards
shijith
