### ISSUE TITLE
Why does clamAV detect code as Trojan Mirai?

### ISSUE THREAD

**Issue by rodelrebucas** [Microsoft/vscode#65886]
I have downloaded this file 

> code-stable-1545156735.tar.gz

 from https://code.visualstudio.com/#alt-downloads. When I scanned the extracted folder with ClamAV it shows:

VSCode-linux-x64/code: Unix.Trojan.Mirai-5932143-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 6672559
Engine version: 0.100.2
Scanned directories: 513
Scanned files: 1195
Infected files: 1
Data scanned: 242.92 MB
Data read: 182.04 MB (ratio 1.33:1)
Time: 59.975 sec (0 m 59 s)

Does anyone also have this problem?

**Comment by joaomoreno** [comment]
I've just downloaded that exact version and ran `clamscan` over it. The result was the following:

```
----------- SCAN SUMMARY -----------
Known viruses: 6756459
Engine version: 0.101.0
Scanned directories: 513
Scanned files: 1195
Infected files: 0
Data scanned: 164.75 MB
Data read: 182.04 MB (ratio 0.91:1)
Time: 25.714 sec (0 m 25 s)
```

Please make sure you have updated your clam DB.
