### ISSUE TITLE
Remove changed flag from expanded folders in explorer to reduce the noise

### ISSUE THREAD

**Issue by aminchoroomi** [microsoft/vscode#65884]
Hi and thank you guys for the awesome job you have done so far.

I'm not sure if there's already an option to config this, so I'm requesting this as a new feature.

Look at this picture

![vscode](https://user-images.githubusercontent.com/1765653/50573030-55cfdf80-0de1-11e9-81c1-12a5b65cdf55.JPG)

When you add a file or change something in the project, there comes a U, A, M, etc flag into the explorer which helps you find the changes since last commit (which is great by the way). 

But there also come quite a few dot flags on the containing folders up to the root. This part is a bit noisy I think and could be better. for example I have now changed only **one** file and there are 5 flags (beside that badge on the Git tab) showing me that.

I believe those dots are only helpful if the folder is collapsed and therefor we are unable to track inside changes. But if the folder and sub-folders are expanded, it's not necessary to flag all the folders in the path.

Thank you

**Comment by usernamehw** [comment]
Just in case this won't be implemented you can try the path of hacks with extension [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css#overview)

```css
.explorer-folders-view .monaco-tree-row.expanded .explorer-item::after {
	opacity: 0 !important;
}
```

**Comment by isidorn** [comment]
`"git.decorations.enabled": false`
