### ISSUE TITLE
Visual Studio Code opens by default instead of File Manager

### ISSUE THREAD

**Issue by guest73** [Microsoft/vscode#65885]
As no one can really help me on [StackOverflow](https://stackoverflow.com/questions/53933288/prevent-opening-visual-studio-code-when-click-show-in-folder-in-chrome) I decided to open an issue.

- VSCode Version:1.30.1
- OS Version: Linux Mint Tara

Steps to Reproduce:

1. Download something in Google Chrome/Chromium/Opera
2. Try to select 'Show in Folder'
3. Visual Studio Code launches instead of my default file manager Thunar.

This is really strange as _xdg-open ~/_ opens my home folder in Thunar. And also when selecting 'Show in folder' in Firefox also works as expected.

**Comment by joaomoreno** [comment]
This appears to be an issue with WebKit based browsers (Chrome/Chromium/Opera). I suggest you file an issue on them instead. Sorry for not being much of help.

**Comment by guest73** [comment]
Ok. Will do. Thanks.
