### ISSUE TITLE
Indentation between the files in repository and actual source code is different.

### ISSUE THREAD

**Issue by NDelt** [Microsoft/vscode#65888]
![pic1](https://user-images.githubusercontent.com/46282492/50575034-b984f780-0e37-11e9-9ac0-aaa8ddc848bc.png)

![pic2](https://user-images.githubusercontent.com/46282492/50575035-bbe75180-0e37-11e9-967d-850d63577c8d.png)

In the file of repository, the indentation is 8-column tabs but it is 2 spaces in actual source file.
Why are they have different code style?

**Comment by usernamehw** [comment]
How is this vscode problem? 

This indentation (in `GitHub`) only affects appearance. It can automatically use your settings if you have `.editorconfig` file in your repo.

https://stackoverflow.com/a/33831598/5590193

**Comment by NDelt** [comment]
I didn't know about `.editorconfig` file. Thanks.

**Comment by egamma** [comment]
This works as intended an designed as pointed out by @usernamehw
