### ISSUE TITLE
PHP Javascript

### ISSUE THREAD

**Issue by CaptainCyril** [Microsoft/vscode#65898]
Issue Type: <b>Bug</b>

Ever since the last upgrade to VC, whenever I have PHP and Javascript in one script, some lines or part of lines randomly turn white. It was working fine in previous versions.
![annotation 2019-01-02 092451](https://user-images.githubusercontent.com/9806265/50583145-45b31100-0e70-11e9-8bd3-6804c7034d24.jpg)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (7.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.6
php-pack|fel|1.0.2
gc-excelviewer|Gra|2.1.26
crane|Hvy|0.3.8
rainbow-csv|mec|0.8.0
debugger-for-chrome|msj|4.11.1

</details>

**Comment by CaptainCyril** [comment]
This is another sample.
![sample2](https://user-images.githubusercontent.com/9806265/50590338-3c876b80-0e93-11e9-8762-c0413138bcd2.jpg)

**Comment by egamma** [comment]
@CaptainCyril please attach the source as well so that we do not have to enter the code manually to reproduce the problem.

**Comment by CaptainCyril** [comment]
Sure!
[phpsample.txt](https://github.com/Microsoft/vscode/files/2720775/phpsample.txt)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/65649

**Comment by CaptainCyril** [comment]
@roblourens Why did you thumb down my question? I tried searching Google a lot for this but could not find an answer. Anyway, thank you for your references.

**Comment by roblourens** [comment]
That wasn't me :)

**Comment by CaptainCyril** [comment]
@roblourens Sorry about that! :)

Happy New Year! Have a great one!
