### ISSUE TITLE
MissMatch between Java SE and JDK selected by VSCode.

### ISSUE THREAD

**Issue by Rg111Ga31** [Microsoft/vscode#65894]
Issue Type: <b>Performance Issue</b>

                                   java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

C:\JAVA\Sudoku\Java_SOURCES\Sudoku>javac -version
javac 11.0.1
causes the  right mouse click 'run code' selection to generate the following
[Running] cd "c:\JAVA\Sudoku\Java_SOURCES\Sudoku\" && javac Sudoku.java && java Sudoku
java.lang.UnsupportedClassVersionError: Sudoku has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
[Done] exited with code=1 in 0.634 seconds

If I attempt to use terminal dropdown to 'Run Active File' I get a file Identifier window 
File: Sudoku.java
Windows can't open your file.  You can search FileInfo.com for programs that open the file, or you can use the default windows service.

What do you want to do.  If Windows default is selected we are directed to the windows 10 'How do you want to open .java files'.  If I select  NotePad then all .java files display a notepad icon in File Explorer {and someone scolds me when I ask why the NotePad display of my input file}.  If I select VS Code, nothing seems to happen since I already have Sudoku.java open in an editor window.

My dilema will be resolved if someone can point me to a means by which I can force MS VS Code to use both zulu11.2.3-JDK11.0.1-win_x64 and the corresponding RE rather than the Oracle 1.8.0_192 SE.  Clearly I am attempting the move to OpenJAVA/JDK.  At present NetBeans only works with Oracle Java 1.8.0_192 and lower versions?

VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (10.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    86	 16564	code-insiders main
    0	   110	  1292	   gpu-process
    0	    83	  9056	   shared-process
    0	   192	 11736	   window (Sudoku.java - Sudoku - Visual Studio Code - Insiders)
    0	    14	  1048	     watcherService 
    0	    11	 13328	       console-window-host (Windows internal process)
    0	    81	  2796	     extensionHost
    0	   528	   876	       "C:\Program Files\Zulu\zulu-11\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\Users\Garve\.vscode-insiders\extensions\redhat.java-0.36.0\server\plugins\org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar -configuration C:\Users\Garve\.vscode-insiders\extensions\redhat.java-0.36.0\server\config_win -data "c:\Users\Garve\AppData\Roaming\Code - Insiders\User\workspaceStorage\f630cbd0552194657ac2968282335169\redhat.java\jdt_ws"
    0	    10	 11972	         console-window-host (Windows internal process)
    0	    35	  7964	     searchService
    0	     6	  9844	     winpty-process
    0	     4	   776	       C:\WINDOWS\System32\cmd.exe
    0	    11	  8472	       console-window-host (Windows internal process)
    0	     6	 15852	     winpty-process
    0	     3	  1580	       C:\WINDOWS\System32\cmd.exe
    0	    11	 15564	       console-window-host (Windows internal process)
    0	     6	 20864	     winpty-process
    0	    10	 20888	       console-window-host (Windows internal process)
    0	     4	 20988	       C:\WINDOWS\System32\cmd.exe
    0	    69	 21492	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Sudoku.java - Sudoku - Visual Studio Code - Insiders)
|    Folder (Sudoku): 3 files
|      File types: class(1) java(1) json(1)
|      Conf files: launch.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.22.0
code-runner|for|0.9.5
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
java|red|0.36.0
vscode-yaml|red|0.2.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1

</details>

**Comment by egamma** [comment]
Please report the issue against the Java extension.
