### ISSUE TITLE
VS Code Becomes Less Intelligent

### ISSUE THREAD

**Issue by Ethan-Zhou** [Microsoft/vscode#65896]
Issue Type: <b>Bug</b>

Since last month, VS Code becomes increasingly less intelligent than before. 
1) I cannot go to the definition by Ctr+clicking on the function. 
2) In debugger mode, the break point jumps around rather than in a sequential manner. 
3) The new-built executive does not give the up-to-date result until I reboot the vs code.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2522)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (9.45GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
togglehs|bbe|0.1.2
code-runner|for|0.9.5
vscode-clang|mit|0.2.3
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by egamma** [comment]
From the installed extensions it looks like your are using VS Code for C/C++ development. Please report the issue against the C++ extension.
