### ISSUE TITLE
Hotkey to get type information for the selected expression

### ISSUE THREAD

**Issue by alisabzevari** [microsoft/vscode#65890]
Intellij has a very useful feature called "[show type info](https://www.jetbrains.com/help/idea/edit-scala-code.html)" that shows type information for the selected expression. For example, consider the following code:

``` typescript
function fn(count: number, str: string) {
	return str + count;
}
```

In Intellij IDEA it is possible to select `str + count` expression and press `alt + =` and get the result type of the selected expression (`string` in the example).

I think this feature would be very beneficial specially in the languages that type inference is very important. Although I am not sure this repository is the right place to ask for this feature.

**Comment by jrieken** [comment]
@alisabzevari You can today already press `Cmd+K Cmd+I` to show the hover programmatically. That will show all hovers - usually it's just the type hover but it rare cases it might be more. Is that enough to make you happy?

**Comment by alisabzevari** [comment]
So, here is a more interesting example:
``` typescript
import _ from "lodash";

const students = [
	{ id: 1, age: 20, points: [10, 12, 15] },
	{ id: 1, age: 25, points: [1, 12, 20] },
	{ id: 1, age: 18, points: [17, 10, 15] }
];

const sumAge = _.chain(students)
	.map(s => s.age)
	.sum()
	.value()
```

Usually, when dealing with chaining of calls, every function call (like `map` and `sum`) accept s certain input type and return a different type. Now, if I want to know what is the result type of `_.chain(students).map(s => s.age).sum()` it is only possible by removing the `.value()` in the end and look at the variable type by using `Cmd+K Cmd+I`.
In intellij it is possible to select a part of the expression and get type information for that selected part.

Here are some screenshots in intellij using this feature:
![screenshot from 2019-01-03 21-19-15](https://user-images.githubusercontent.com/826242/50688339-53f65e00-1025-11e9-9a06-bd4790c4a2aa.png)
As you can see, cursor is on `articleId`. Now if I press `alt+=` the following menu will open:
![screenshot from 2019-01-03 21-19-20](https://user-images.githubusercontent.com/826242/50688376-70929600-1025-11e9-99be-4b36a3d0d5b4.png)
So I can select which expression I want to get type info for. When I select `Favorites.articleId`, it shows the type info (only for that selected expression):
![screenshot from 2019-01-03 21-19-24](https://user-images.githubusercontent.com/826242/50688395-9881f980-1025-11e9-99ff-a7c0bfcbe662.png)
Note that, generic type parameters are resolved here. If I select the other expression from the menu, the following result will appear:
![screenshot from 2019-01-03 21-19-37](https://user-images.githubusercontent.com/826242/50688436-ca935b80-1025-11e9-83a0-a08413c57423.png)
And here is another example, selecting the whole statement:
![screenshot from 2019-01-03 21-19-43](https://user-images.githubusercontent.com/826242/50688457-db43d180-1025-11e9-9a4d-4f76103990eb.png)

This feature does not exist in vscode.

**Comment by mjbvz** [comment]
@jrieken One problem with the VS Code hover api and UX is that hover uses a position instead of a selection range. A hover provider could decide to use the current selection if the cursor position is within it but this could result in a confusing UX

**Comment by alisabzevari** [comment]
I think this feature does not contradict with hover feature. This is how I image them together:
* User can hover over (mouse cursor) an **identifier** and get type information for that identifier.
* User can hit `ctrl+k ctrl+i` while **not selecting** anything and type information should be shown for the identifier currently under the caret (keyboard cursor).
* User can hit `ctrl+k ctrl+i` to get type information for the **currently selected expression**.

**Comment by Ciantic** [comment]
Now this is broken, I can't anymore copy & paste the type definition from the "Ctrl+K Ctrk+i", I get these darn abbreviations with three dots:

```
let ffprobe_video_stream: {
    index: number;
    codec_name: string;
    codec_long_name: string;
    profile: string;
    codec_type: string;
    codec_time_base: string;
    codec_tag_string: string;
    codec_tag: string;
    width: number;
    height: number;
    ... 22 more ...;
    tags: {
        ...;
    };
}
```
This is some new addition, can we disable those? I constantly copy & paste the type definitions.

**Comment by mjbvz** [comment]
Closing this since it has not gotten a significant number of 👍  over the past two years

**Comment by ciuncan** [comment]
This is a pretty significant missing feature in VS Code that I've been missin ever since I started using it. Type annotations are being used more and more frequently even by languages of dynamic nature like Python, TypeScript, etc. Coming from a Scala background, I've been using this feature of IntelliJ idea to get the inferred type of a selected expression. It is quite inconvenient to assign a selection to a variable each time just to see its type, not just coding yourself but especially if you are reviewing a code or reading a library source or a previous work. 

I'd suggest reopening this feature as it is clearly not out of scope of VS Code since the type hint is already a feature of it.

**Comment by Troyx21** [comment]
**Please reopen this!!!**

**Comment by aksh1618** [comment]
I worked around this by remapping `Show or focus hover` (`Ctrl+k Ctrl+i` by default) to `Ctrl+Shift+P` (I'm coming from IntelliJ IDEA). This works for rust, although it shows the check/clippy lint etc. as well.

**Comment by VishalDhayalanN15** [comment]
This is such a significant and useful feature that should be included as basic functionality in any full-fledged IDE. Please re-open this and implement this functionality ASAP
