### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Robmcmon** [Microsoft/vscode#65893]
Terminal in vscode is not working correctly and i've disabled all extensions.. Anytime I try to even run a simple command like npm -v or ionic -v to just get a version number I get the error below. However if I do this in a windows cmd prompt I get no issues so it is something with vscode: 

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'E:\c\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) 
```

**Comment by mjbvz** [comment]
@Tyriar I thought this was a terminal configuration question but please reopen if it is a bug

**Comment by Robmcmon** [comment]
I did ask on stackoverflow and got zero response. It is a bug in my vscode as my directly windows cmd does not have these issues. Only terminals opened in vscode do.

**Comment by Robmcmon** [comment]
any command results in a throw err from the loader.js

**Comment by Tyriar** [comment]
The path says `E:\c\`, how are you importing the module? And do you have an E drive?

**Comment by Robmcmon** [comment]
The files for the application are on my e drive ( this is always the case) VScode is installed on my C drive as well as npm or ionic or any modules I use are on the c drive. Vscode never had this issue previously.

**Comment by Robmcmon** [comment]
there is a local folder typically for node_modules in each application that gets installed.. However a simple cmd like npm -v results in a loader err in a vscode terminal. However inside of a normal windows cmd prompt terminal there are zero issues. This only happens inside of vscode

**Comment by Tyriar** [comment]
What shell are you using?

Can you try run these?

- `echo %cd%`
- `node -e "console.log(require('path').resolve(__dirname))"`

**Comment by Robmcmon** [comment]
I'm just using the same shell that got installed with vscode which is bash. I had checked the settings and it says it is using the windows cmd.exe.. Which is odd because if I use that cmd outside of vscode I do not get the error. 

Your commands returned these results
- %cd% 
-E:\mydirectory\app\

**Comment by Tyriar** [comment]
@Robmcmon could you try run the command "Select Default Shell" in the command palette (F1), set cmd and run them again?

**Comment by Robmcmon** [comment]
@Tyriar Thank you! That was it! I guess it was indeed not a bug. My apologizes. However I do not know why this changed as I can assure you before that in the default bash terminal all the commands previously ran just fine unless this is due to a nodejs or vscode update perhaps? Either thank you for your help in helping me resolving this issue.
