### ISSUE TITLE
VS Code won't run without an internet connection

### ISSUE THREAD

**Issue by GbolahanA** [Microsoft/vscode#65902]
Issue Type: <b>Bug</b>

VS Code v1.30.1 doesn't run when an Internet connection is not present.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

**Comment by egamma** [comment]
duplicate of  #7570
