### ISSUE TITLE
Automatic filetype detection for differently named dockerfiles

### ISSUE THREAD

**Issue by ntippman** [Microsoft/vscode#65903]
Issue Type: <b>Feature Request</b>

Automatic file type detection and thus syntax highlighting for Dockerfiles only works if the file name is exactly "Dockerfile". When working with multiple Dockerfiles names may differ (e.g. DockerfileA, DockerfileB). Current solution is to set the file type manually after every restart.

It would be a quality of life improvement if those were automatically detected too. A good alternative would be saving the type and restoring on restart.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.4.0-141-generic

**Comment by egamma** [comment]
@ntippman the docker extension detects files with the name `Dockerfile` and `*.dockerfile`. 
If you have suggestions for additional file names that should be detected as Dockerfile, then file an issue against the vscode-docker extension.
