### ISSUE TITLE
externalTerminal setting doesn't work with paths containing spaces

### ISSUE THREAD

**Issue by AdamAndersonFalafelSoftware** [Microsoft/vscode#6590]
- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set externalTerminal.windowsExec to any of the following:
    a. "C:/Program Files/Git/git-bash.exe"
    b. "\"C:/Program Files/Git/git-bash.exe\""
2. Try to open the external terminal. Either nothing will happen or the default cmd prompt will open with the title set to the setting above.

This setting _does_ work: "C:/Progra~1/Git/git-bash.exe"

**Comment by Tyriar** [comment]
Windows only, works on linux using:

```bash
ln -s /bin/bash /home/daimms/bash\ symlink
```

```json
"externalTerminal.linuxExec": "/home/daimms/bash symlink"
```
