### ISSUE TITLE
Behaviour of Page Up and Page Down keys is inconsistent with native Windows programs

### ISSUE THREAD

**Issue by torgeirsh** [microsoft/vscode#65907]
If I open a file that is more than one screen long in Visual Studio Code (1.30.1), place the cursor at the top of the screen and press Page Down, the cursor moves to the bottom of the screen without moving the view. This behaviour is inconsistent with native Windows applications like Notepad or Visual Studio 2017. The expected behaviour is that the view should move one screen down, and the cursor should be on the line that is now on the top of the screen. The same goes for moving in the other direction with Page Up. The bug was reported earlier in #17686, but it was closed without a fix and is now locked.

**Comment by lishine** [comment]
I am waiting for this fix as well.
Is there a workaround?

**Comment by EugenNY** [comment]
Moving from another IDE (Visual Studio, Notepad++), I have the same problem.
It's even worse, if you do this somewhere in the middle of your code file:
- Page down to look for something that is a little further down, but not visible on your screen
- Page up to go back to your location

The "page up" won't bring your text file into the exact same position. Instead, the position of your file is exactly the same as before, only the cursor has moved from way down to way up. So now your cursor is somewhere at the top and pressing page down won't move the text file, only the cursor will jump to the bottom.... That's
