### ISSUE TITLE
system menu not appearing when shift+rclicking on the taskbar

### ISSUE THREAD

**Issue by twig** [Microsoft/vscode#65900]
Issue Type: <b>Bug</b>

I use this menu everyday when I begin to shutdown my computer at the end of a working day. It's strange to see that everything works as expected except for vscode, which seems to disable the menu altogether.

steps to replicate:
* hold shift and right-click on vscode in taskbar
* should show menu
* it doesn't

![image](https://user-images.githubusercontent.com/59689/50585868-1e3d6200-0ecb-11e9-802d-5341c1898835.png)

![image](https://user-images.githubusercontent.com/59689/50585910-4f1d9700-0ecb-11e9-9458-97cdcb37235d.png)

doesn't work on the main vscode window, but it does work on the report issues window

potentially related to an over-zealous fix in https://github.com/Microsoft/vscode/issues/52904, https://github.com/Microsoft/vscode/issues/54929, https://github.com/Microsoft/vscode/issues/55656? I do remember that it used to work as expected

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vsliveshare|ms-|0.3.1071
code-settings-sync|Sha|3.2.4

</details>

**Comment by bpasero** [comment]
This is a consequence of using custom title bar. You can disable this behaviour if you configure: 

`"window.titleBarStyle": "native"`

**Comment by twig** [comment]
that worked well, thanks for the tip!

**Comment by myfairsyer** [comment]
Related to this: The [Window Menu](https://docs.microsoft.com/en-us/windows/desktop/menurc/about-menus#the-window-menu) doesn't open either when left clicking the custom titlebar's icon on Windows, nor does of course double-clicking the icon execute the menu's [default item](https://docs.microsoft.com/en-us/windows/desktop/menurc/about-menus#default-menu-items) and close the window.

I did not open an own issue as @bpasero's comment reads to me as if there's currently either no intention or no option to fix this.

**Comment by myfairsyer** [comment]
I found an older and more detailed issue for this that has not been closed: #60769

**Comment by twig** [comment]
yeah I saw that ticket and figured it was somehow related to Electron's wrapping.

I used to do a fair bit of Windows desktop programming and knew there were ways to disable either top-left/taskbar or both system menus. Had a feeling that the implementation for vscode had somehow chosen to kill both
