### ISSUE TITLE
Invert Regex Selection

### ISSUE THREAD

**Issue by JonathanWilbur** [microsoft/vscode#65912]
I would like to see a flag in the Find / Replace modal that inverts the selection. In other words, everything starts out as selected / highlighted, then anything that matches the regular becomes un-selected / un-highlighted.

**Comment by Memphizzz** [comment]
Has this been added? If so, where do I find the option to invert selection?

**Comment by stribizhev** [comment]
This is a standard feature in most editors, it is really a great pity there is no *Inverse Selection* option in VSCode.
