### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by BlueShardSigma** [Microsoft/vscode#65915]
Im doing a simple Python (3.7.1 64-bit) script on VS Code. And for whatever reason none of my scripts seem to work. I get error "Cannot read property 'indexOf' of undefined"
_Script:
print("Let's do some Math, adding first")
num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
result = float(num1)+float(num2)
print("And the answer is: ")
print(result)_

This script ran perfectly on VS Code when it was writen. As Im still learning programming im not sure If its my doing or VS Code Bug

**Comment by isidorn** [comment]
Please try with latest vscode insiders https://code.visualstudio.com/insiders/
And if you can still see the issue please F1 > developer tools > look at the debug console and paste the whole stack trace here
