### ISSUE TITLE
Snippet API

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#65917]
Can an API to get the list of available snippets that are being suggested in the editor be added? Also can an API to trigger the first suggestion programmatically be added?

**Comment by jrieken** [comment]
Yeah, checkout the `vscode.executeCompletionItemProvider`-command as described here https://code.visualstudio.com/api/references/commands. Filter for type `snippet` and use the `TextEditor#insertSnippet` to actually insert the suggestion.
