### ISSUE TITLE
Terminal glitches after suspend

### ISSUE THREAD

**Issue by Iipal** [Microsoft/vscode#65918]
- VSCode Version: 1.30.1
- OS Version: Linux x64 4.18.0-13-generic(Ubuntu 18.10 && 18.04 too)

Steps to Reproduce:

1. Create new terminal window
2. Put your laptop in suspend mode
3. Press any button for exit from suspend mode
4. Complete.

Disabling all extensions doesn't help and in Insiders Editions this glitches work too. (Used `zsh` with `oh-my-zsh` & theme "nebirhos" if it's can help)
![image](https://user-images.githubusercontent.com/31858171/50608311-f2bf7500-0ed4-11e9-8d80-212ca61bce7a.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/58167

**Comment by darekf77** [comment]
Solution for me was to change of color theme.
