### ISSUE TITLE
Generalized keyboard action to toggle config properties

### ISSUE THREAD

**Issue by bsmith-cycorp** [Microsoft/vscode#65922]
My original desire was to toggle problem-underscores with a keyboard shortcut. However, looking through the keybindings docs, I noticed that bindings can take `args`. Given this, I'm surprised there isn't an action along the lines of `toggleConfigProperty`, which would take an arbitrary boolean property name as an argument. This would cover lots of use-cases, including a few that have been requested as tickets here.

If you wanted to take it further, you could even have `setConfigProperty`, which would take a property name and a value, and would work with non-boolean properties. Combined with some clever usage of `when`, the user could do just about anything they might want to do in terms of changing the config with keyboard shortcuts.

**Comment by sandy081** [comment]
This can be implemented through an extension, refer to https://marketplace.visualstudio.com/items?itemName=sandy081.settings-picker.
