### ISSUE TITLE
Lost PHP format extentions functionality, and other buggy extentions.

### ISSUE THREAD

**Issue by tunedin76** [Microsoft/vscode#65924]
Issue Type: <b>Bug</b>

Latest update destroyed all my formatting for PHP.  I have tried resetting VS code - erasing all my settings, and uninstalling all extentions.

On another note over the past two months many extentions have been behaving a little off.. In other words, buggy, but none until this point has been a show stopper. 

I do have the requirements for a complex IDE - as I need SSH filesystem, VUE format, TS and JS linters/formatters, PHP, Laravel and Blade linters and formatters, and CSS/SCSS tools, and it would be nice to have HTML formating and rainbow brackets and auto-close tage too). The editor (or IDE) has been performing above any expectations - but something has happened.  Is it because I have too many extentions?

I have lost a couple of days of work now, and it has become a show stopper for me. If it is my fault I accept the humiliation and would just like to move foreward.  If there has been other reports and I just have to be patient, that will be fine too.

Yours truly,
a defeated dev.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.96GB (6.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
laravel-goto-view|cod|1.2.3
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.7.3
output-colorizer|IBM|0.1.2
vscode-sshfs|Kel|1.11.2
vetur|oct|0.14.4
indent-rainbow|ode|7.2.4
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.6.2
php-formatter|Sop|0.2.4
laravel-56-snippets|Tha|2.2.3

(1 theme extensions excluded)

</details>

**Comment by tunedin76** [comment]
I now, on this new day have vscode completly removed I erased all the extentions and settings in userprofile and appdata, re-installed.

I have tried phpfmt extention, and php-cs-fixer and each report that there are "No coder formatting for php"

This is a show-stopper for me.  Did someting change in the latest update with formatting that I didn't pay attention to?

**Comment by tunedin76** [comment]
Just FYI - I removed all PHP formatting
 updated my config.json to be able to use it....
`{
    "workbench.colorTheme": "Cobalt Next",
    "sshfs.configs": [
        {
           ...
        },
        {
            ...
        }
    ],
    "workbench.iconTheme": "material-icon-theme",
    "php.suggest.basic": false,
    "editor.minimap.enabled": false,
    "editor.fontLigatures": true,
    "editor.fontFamily": "'Fira Code', 'Arial', monospace",
    "php.validate.executablePath": "C:\\wamp64\\bin\\php\\php7.2.4\\php.exe",
    "files.associations": {
        "*.php": "php",
        "*.phtml": "php"
    },
    "php.validate.run": "onType",
    "editor.cursorSmoothCaretAnimation": true,
    "editor.formatOnType": true,
    "editor.smoothScrolling": true,
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    "emmet.includeLanguages": {
        "blade": "html"
    },
}`

and now ctrl-k, ctrl-f now formats a selection...   I am not sure if it is because it is formatting as JS or TS... but how would I make formatting customizations now?

**Comment by tunedin76** [comment]
Just found out the same has happened to ALL third party extension formatters.. VUE - Vetur, with Prettier, phpfmt, 
This is a serious bug. I have posted to the extension authors as well:
phpfmt,
php-cs-fixer
Vetur
Prettier
Prettier-Now

I have tried each of these as the only extension on a fresh install

**Comment by stephanieadwill** [comment]
@tunedin76 I saw you closed this ticket, any news? I'm seeing the same issue with PHP Intellisense, PHP Intelliphense, and phpfmt and noticed it because my formatting failed after the last update. In my case, the only error that presents is vscode won't recognize the php.validate.executablePath setting, even though a valid PHP path is available in my env vars and the path saved to settings is absolutely correct. This has been covered in at least one other recent issue ([#62330](https://github.com/Microsoft/vscode/issues/62330)), now closed to comment with "needs more information" tag.

**Comment by tunedin76** [comment]
Unfortunately no I didn't fix it I tried multiple times asking different questions. I do know is around the November update lot of things stopped working. I'm having the number of other issues I hope get resolved in the next update, hopefully as more people tell them about bugs they won't pass it off as a extension problem. I'm having problems with just about every extension that I use right now. VS code has become nothing more than a text editor for me.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
