### ISSUE TITLE
ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware

### ISSUE THREAD

**Issue by ealsur** [Microsoft/vscode#6592]
- VSCode Version:1.1.1
- OS Version: Windows 10

Using C# Extension 1.0.11 and ASPNET Core RC2 (dotnet cli installed) using net461, I am unable to get Omnisharp to work.

Whenever I open a folder with a project with that version of ASPNET Core I get this error on the Omnisharp Log:

`[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] myproject/.NETFramework,Version=v4.6.1[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#362
