### ISSUE TITLE
custom title and menu bar for linux does not work on cygwin xserver for windows

### ISSUE THREAD

**Issue by ninrod** [Microsoft/vscode#65923]
Issue Type: <b>Bug</b>

# description

The [recently enabled by default](https://code.visualstudio.com/updates/v1_30#_custom-title-and-menu-bar-on-linux-by-default) custom title and menu bar on linux does not work on cygwin xserver (latest version: 1.20). The user cannot move the window nor right click on it. 

The only way to use vscode on this setup is to modify the configuration `window.titleBarStyle` from `custom` to `native`.

A command line option to forcibly start vscode in "native" window.titleBarStyle mode would be welcome in light of this problem.

# steps to reproduce

1. start vscode in a docker container, on windows desktop, using an xserver (e.g. cygwin)
2. try to move or right-click the window and confirm that it cannot be done. 

# system info

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.9.87-linuxkit-aufs

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (4 x 3251)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|5.80GB (1.09GB free)|
|Process Argv|--user-data-dir=/workbench/.conf/vscode --disable-gpu --proxy-server=cache:8080 .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.6
vscode-icons|rob|8.0.0
vim|vsc|0.17.3

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
/duplicate
https://github.com/Microsoft/vscode/issues/62613
