### ISSUE TITLE
HTML / CSS / Less / SCSS semantic selection (balance inward/outward)

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#65925]
### Refs

- Semantic selections: https://github.com/Microsoft/vscode/issues/4795
- LSP: https://github.com/Microsoft/language-server-protocol/issues/613

### Current Status

- HTML: `Emmet: Balance (outward)` works
- CSS/SCSS/LESS: `Emmet: Balance (outward)` doesn't work, but it works in Atom. Probably need to update our dependencies.

The plan now is to use emmet's "balance" commands. The challenge is that HTML/CSS language service need to include emmet. Alternatively, we can implement these commands ourselves.

**Comment by octref** [comment]
This will be available in tomorrow's insiders:

![html-selection](https://user-images.githubusercontent.com/4033249/51643241-a211c980-1f20-11e9-819d-9e28946f30b9.gif)

**Comment by Maxhodges** [comment]
is this suppose to work in Javascript? It's not nearly as nuanced as Webstorm.

**Comment by octref** [comment]
- Vue — it'll be available once we update the dependencies.
- JavaScript — we'll need to wait for TypeScript to add the semantic selection. I don't have any estimate.
