### ISSUE TITLE
preLaunchTask is awkward

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#65938]
I want to understand how to best use VS Code in this case.

Config in question: https://github.com/Microsoft/vscode/blob/master/extensions/css-language-features/.vscode/launch.json

Problem:

- When I develop on css-language-features, I always run `yarn watch` in a terminal
- When I press F5, VS Code still runs the `preLaunchTask`, which can take quite a while
- Currently I comment out `preLaunchTask`, but I had to be careful not committing that to git
- I don't want to use task, since the task compiles but without watching, so each time I make a change, I need to wait fo a full recompile
- I can't just remove the `preLaunchTask`, since Martin uses it
- If I start using tasks by converting the current `compile` task to use `watch`, this will work fine if I "make change, then reload ExtHost window", but this won't work when I stop debugging session, since the next time I debug I need to run the task again

In my own extension, I've completely removed tasks for exactly this reason: https://github.com/vuejs/vetur/commit/502017a7f9925cdb68c961d4b4d88478563b5a41#diff-7fde71560fa9376d2d93a25b42d719f5

My current experience:

- When I open the project, I run `yarn watch` in terminal
- F5 brings up ExtHost instantly
- Recompile is fast

Is it possible to make `preLaunchTask` offer a similar experience?

**Comment by weinand** [comment]
@octref for conflicting needs you can create an additional launch config: just duplicate the launch config and remove the preLaunchTask.

**Comment by octref** [comment]
This seems to be working for me:

- I run the `npm: watch` task manually
- F5 skips `preLaunchTask` since it's exactly the same task

But If I run `npm run watch` or `yarn watch`, is it possible for VS Code to detect that as "running task manually" and skip the `preLaunchTask`?

**Comment by isidorn** [comment]
@octref I think not. But I leave that up to @dbaeumer and @alexr00

**Comment by octref** [comment]
Can I get a custom command that always skips `preLaunchTask` so I can bind it to my F5 then?

**Comment by weinand** [comment]
@octref creating a launch config without the `preLaunchTask` is not an option?

**Comment by octref** [comment]
> creating a launch config without the preLaunchTask is not an option?

I don't like duplicating all launch tasks. I guess I'll go without preLaunchTask and add instructions such as `Run "yarn watch" or the task "Yarn: Watch" before development`.

I'd really hope there's a way for me to hook a terminal's output to a problem matcher, but that's not crucial for me.
