### ISSUE TITLE
Terminal typing slow and caret jumping around

### ISSUE THREAD

**Issue by eKipod** [Microsoft/vscode#65937]
Issue Type: <b>Bug</b>

1. when typing:
Open terminal (ctrl+`)
Start typing
Expected: caret follows text
Actual: caret jumps to top-left corner, then back to text

2. when executing:
Open terminal
Run a command that outputs to stdout (e.g. dir)
Expected: text continuously appears 
Actual: caret keep going back to top-left corner and scans through the terminal.

VS Code version: Code - Insiders 1.31.0-insider (ed5363e8659d142fc170cb978389e34102135e8f, 2019-01-02T17:25:53.371Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is a bug in conpty with powershell, it will be fixed in a later version of Windows. cc @zadjii-msft @bitcrazed
