### ISSUE TITLE
Support overriding the 'role' attribute on a new tree

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65939]
For screenreaders to work properly, the tree needs to have a 'role' of 'form'. Currently we just get the tree's dom element and override the role, but the List resets its role on every focus change: https://github.com/Microsoft/vscode/blob/3e7bb120c786038030de0d284b62a837d204330a/src/vs/base/browser/ui/list/listWidget.ts#L1348. Do you know why it does that @joaomoreno? I think we can also just add a focus listener and override it the same way, but that's not a great solution. I think the list should not reset its role on focus, or we should be able to pass a custom role.

Also see https://github.com/Microsoft/vscode/issues/57315 for details. FYI @cleidigh 

I think this is the only change needed for screen readers to work correctly on the settings page.

**Comment by cleidigh** [comment]
@roblourens 
@joaomoreno 
Based on some of my experience with this, I think keeping the main tree role constant by setting as a constructor option will probably be the most reliable.  I have seen some unhappy screenreader behavior when ARIA attributes change dynamically.

**Comment by joaomoreno** [comment]
> Currently we just get the tree's dom element and override the role

Ugh!

Yeah, let's add a ctor option to specify the role. But this will affect each row role as well... I don't think I should just give you a `ariaRole: string` option, since more is needed.

Apart from setting `role: form` on the root node, what else do you need to set on each row?

**Comment by roblourens** [comment]
We also remove these attributes: https://github.com/Microsoft/vscode/blob/0d1139653803f7acb831a593f816c1278638011b/src/vs/workbench/parts/preferences/browser/settingsTree.ts#L441:L444

But I just tested with voiceover and it still works without those changes so maybe that's not needed anymore.

Then we also set some aria attributes on elements inside the row that it makes sense for the renderer to own.

**Comment by joaomoreno** [comment]
> We also remove these attributes: /src/vs/workbench/parts/preferences/browser/settingsTree.ts@0d11396#L441:L444

It would be great if you just implemented that as list/tree options as you need them. Or just file feature requests and I'll get it done.

> Then we also set some aria attributes on elements inside the row that it makes sense for the renderer to own.

Yeah, if the elements are inside the row, you own them. If you need to customize the row's attributes, you have to let me know so we add options.

**Comment by cleidigh** [comment]
@joaomoreno 
@roblourens 
Since I did the original related issue #57315 I would be happy to take care of this.

We need the root level role option plus ability to set the role on each item.  I cleared the level  related attributes to avoid potential reader noise.

**Comment by roblourens** [comment]
@cleidigh Yeah it would be great if you would add the option to set the tree's role.

But do we need to override the role/attributes on each item? I did a quick test with VoiceOver on mac and NVDA, and it seems to work fine if I just fix `role=form` on the top level and leave everything else alone. But you might have done some more in depth testing.

**Comment by cleidigh** [comment]
@roblourens - happy new year!

Adding the constructor option to set the root role is no problem obviously.  The other changes are into categories:  Removal of Tree attributes (level, posinset...) was a defensive move to avoid possible mixed screen read or output.  Your observation matches mine that currently these get ignored if the root role is not tree.  Since these do not make semantic sense under the form, I still suggest we remove them when not operating as a tree.  The other important attribute is the individual item role.  We have to set that for the drop-down elements.  I will review determine where's the best place to do that.

**Comment by cleidigh** [comment]
looking back at my original issue (same scenario we need for list), I think it is best to pass in an enumeration not an arbitrary string role.  Anywhere we need to change the logic based on role, such as removing the other tree attributes, we can do within the tree widget.

I currently set the role for the drop-down widget within select box but I think we still have to remove role="treeitem" which is currently set for every tree item.  after I look at it more I will bullet point the changes here before I do a PR.

**Comment by cleidigh** [comment]
@joaomoreno 
@roblourens 

I propose four basic changes - will translate to similar required changes in list:

- export new enum constructor option for acceptable ARIA rootAriaRole
- default role = ariaRoleTree - avoid unnecessary client changes
- It looks like we can do all the role logic in treeView in one section quoted below
- Allow 2 valid roles currently tree and form (implemented as enumerations, not arbitrary strings)
- If not tree, do not add aria-setsize, aria-posinset, aria-level, role=treeitem

- Investigate callback to set item role (currently required for selectBox)

If this sounds good I will do a PR for everything but the item role

```ts
// ARIA
		this.element.setAttribute('role', 'treeitem');
		const accessibility = this.context.accessibilityProvider!;
		const ariaLabel = accessibility.getAriaLabel(this.context.tree, this.model.getElement());
		if (ariaLabel) {
			this.element.setAttribute('aria-label', ariaLabel);
		}
		if (accessibility.getPosInSet && accessibility.getSetSize) {
			this.element.setAttribute('aria-setsize', accessibility.getSetSize());
			this.element.setAttribute('aria-posinset', accessibility.getPosInSet(this.context.tree, this.model.getElement()));
		}

```

**Comment by joaomoreno** [comment]
@cleidigh No need for PR. `help wanted` issues are better suited for PRs.

**Comment by cleidigh** [comment]
@joaomoreno 
Both you and @roblourens   gave a thumbs-up to my proposed changes above.
I am confused.  I identified the original issue, I wrote
the workaround for settings and I determined an appropriate solution.
I have been working on these related issues including those
ARIA problems with interactive elements within either list
or tree.  The bulk of these issues were not "help-wanted"
issues, but rather related to issues I've been working on for quite some time.

Can I continue with the PR or is there some reason I should
not contribute this way???

**Comment by joaomoreno** [comment]
@cleidigh I had this assigned to myself and this milestone for a while now, so I had planned to look at it. Feel free to push a PR, but be aware the milestone is ending next week, so we'd have to merge it by today/tomorrow.

**Comment by cleidigh** [comment]
@joaomoreno 
Thanks - should have it by tomorrow morning.

**Comment by cleidigh** [comment]
See PR: #67092

**Comment by dbaeumer** [comment]
Verified in code.
