### ISSUE TITLE
inDebugMode context key seems to be broken

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#65948]
VS Code version: Code - Insiders 1.31.0-insider (ed5363e8659d142fc170cb978389e34102135e8f, 2019-01-02T17:25:53.371Z)
OS version: Windows_NT x64 10.0.17763

I cleared out my keybindings but I keep seeing this error message while I'm paused in a debug session:

![image](https://user-images.githubusercontent.com/2193314/50622913-db2cc000-0ec5-11e9-97ee-2aa2c9696088.png)

Target I was using: https://github.com/xtermjs/xterm.js/blob/740ca9ce6d172c9bd37ca9bca82195cc9c36afcf/.vscode/launch.json#L25

**Comment by isidorn** [comment]
@Tyriar can you please clarify what key where you pressing when you were getting this error?
Or what were you doing to get this error?

**Comment by isidorn** [comment]
@Tyriar great catch, thanks. I broke this a couple of days ago, so only for insiders.
