### ISSUE TITLE
Couldn't scroll to bottom of menu

### ISSUE THREAD

**Issue by EximChua** [Microsoft/vscode#65947]
Issue Type: <b>Bug</b>

1. Reduce the entire VS Code window to less than the height of the Edit menu.
2. Click on the Edit menu, and try to scroll using the mouse scrollwheel to the last item, "Emmet".

EXP: The "Emmet" item is highlighted and on screen.
ACT: The menu initially scrolls down, but then scrolls up.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 955 Processor (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.75GB (2.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
solidity-extended|bea|3.0.2
go-coverage-viewer|def|1.0.3
todo-tree|Gru|0.0.112
golang-tdd|joa|0.0.9
solidity|Jua|0.0.49
auto-comment-blocks|kev|1.0.1
web-browser|mas|0.0.1
terraform|mau|1.3.7
Go|ms-|0.8.0
PowerShell|ms-|1.10.2
go-doc|msy|0.1.1
quicktype|qui|12.0.46
go-test-outline|Rom|0.2.0
HCL|who|0.0.5
omnipascal|Wos|0.17.0
markdown-all-in-one|yzh|1.8.0

</details>

**Comment by SeonHyungJo** [comment]
I do not work either.

**Comment by sbatten** [comment]
this should be resolved in latest insiders
