### ISSUE TITLE
extension  style wrong

### ISSUE THREAD

**Issue by liaoyinglong** [microsoft/vscode#65943]
- VSCode Version: 
- OS Version:
版本: 1.30.1 (user setup)
提交: dea8705087adb1b5e5ae1d9123278e178656186a
日期: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

--- 

Steps to Reproduce:

1. 
![bug1](https://user-images.githubusercontent.com/23382699/50621057-6d70aa80-0f3e-11e9-9ae8-280a091960af.png)

2. ![bug2](https://user-images.githubusercontent.com/23382699/50621030-37332b00-0f3e-11e9-9cd3-cdad05724251.png)

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
Sorry for getting late on this, missed the notification.

I cannot reproduce this. Can you please try to repro with latest bits again and let us know it happens still
