### ISSUE TITLE
Feels sluggish

### ISSUE THREAD

**Issue by 3zzy** [Microsoft/vscode#65944]
Issue Type: <b>Performance Issue</b>

I have a few plugins but I wouldn't consider them "too many" yet the editor feels slow. Cursor is laggy and autocomplete stutters. 

I uninstalled the biggest plugin "GitLens" hoping to improve the performance, but it doesn't seem to have impacted anything at all.

Is there anything I can do to improve the performance?

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   10	   115	 25195	code main
    0	    82	 25196	   gpu-process
    0	    49	 25208	   shared-process
    5	   410	 35669	   window (FormReview.vue — the-hive-5.7)
    0	     0	 35670	     /usr/local/bin/fish -l
    0	     0	 42543	       ssh -i /Users/ibrahimezzy/.ssh/ibrahim_harvest ibrahim@52.65.203.193
    0	   262	 35673	     extensionHost
    0	    98	 35678	       electron_node tsserver.js 
    0	    16	 35699	         electron_node typingsInstaller.js typesMap.js 
    0	   131	 35679	       electron_node vueServerMain.js 
    0	    16	 35680	       electron_node server.js 
    0	    82	 35690	       electron_node server.js 
    0	     0	 35700	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=35673
    0	     0	 35701	       php /Users/ibrahimezzy/.vscode/extensions/felixfbecker.php-intellisense-2.3.10/vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:58969 --memory-limit=4095M
    0	     0	 36850	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=35673
    0	    16	 35675	     watcherService
    0	    82	 42551	   window (Issue Reporter)
    0	     0	 42552	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (FormReview.vue — the-hive-5.7)
|    Folder (the-hive-5.7): more than 21794 files
|      File types: png(12647) php(4932) js(938) svg(715) less(277) css(260)
|                  md(204) xml(201) jpg(145) lesscache(138)
|      Conf files: makefile(8) package.json(4) settings.json(2) grunt.js(1);
```

</details>
<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-caniuse|aga|0.5.0
turbo-console-log|Cha|1.2.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.25
vscode-dash|dee|2.0.0
prettier-vscode|esb|1.7.3
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
todo-tree|Gru|0.0.112
output-colorizer|IBM|0.1.2
phpcs|ika|1.0.5
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.93
vscode-js-annotations|lan|0.10.0
font-awesome-codes-html|med|0.0.7
vscode-language-babel|mgm|0.0.21
vscode-deploy-reloaded|mkl|0.86.0
clear-console|mwo|0.0.3
vetur|oct|0.14.4
gitlink|qez|0.4.5
vscode-javascript-booster|sbu|0.10.2
code-settings-sync|Sha|3.2.4
indenticator|Sir|0.6.0
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
ayu|tea|0.17.0
terminal-tabs|Tyr|0.2.0
es-quotes|vil|0.2.6
vscode-wakatime|Wak|1.2.5
quokka-vscode|Wal|1.0.174
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
better-align|xan|1.1.10

(1 theme extensions excluded)

</details>

**Comment by vincentvictoria** [comment]
I noticed key-input-sluggishness after I updated to 1.29.0.
Anyhow, try reducing os-wise key-repeat interval.
It helped me.
Also, take a look at [https://github.com/Microsoft/vscode/wiki/Performance-Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) if you haven't.

**Comment by egamma** [comment]
@3zzy as pointed out by @vincentvictoria please follow this guide https://github.com/Microsoft/vscode/wiki/Performance-Issues and provide additional information. Ideally we would like to a CPU profile when you experience the slow down.

Another option is to selectively disable extension and narrow down which extension is causing the slow down.

**Comment by shankar-moeng** [comment]
for me it was not related to any plugin. Updating npm module (via brew) on macbook pro resolved the issue for me.
VS -> Version 1.30.2
npm -> 6.5

Hope the change works for you too...
