### ISSUE TITLE
Ctrl+Shfift+F global search is very very slowly

### ISSUE THREAD

**Issue by zmicx** [Microsoft/vscode#65945]
Issue Type: <b>Bug</b>

the latest version vscode is so slowly when using Global search, however the old version has this problem with version 1.28.x

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-project-generator|dan|1.1.1
gitlens|eam|9.3.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
unity-debug|Uni|2.6.6

</details>

**Comment by egamma** [comment]
Please provide more information about your workspace and about the search you are conducting.

Can you confirm that by 'Global search' you refer to this search support
![image](https://user-images.githubusercontent.com/172399/50704711-938a6d80-1058-11e9-9883-56494094be95.png)


To provide more information about the workspace please run `code --status` from a command line while VS Code is running and include the output.

**Comment by zmicx** [comment]
@egamma 
![image](https://user-images.githubusercontent.com/26269444/50767448-dac26980-12b7-11e9-8415-767bdc7ea337.png)
this is code status
![image](https://user-images.githubusercontent.com/26269444/50767475-ee6dd000-12b7-11e9-86f5-edff5670bd08.png)
this is my search view

**Comment by roblourens** [comment]
- How long does it take search to complete? 
- Do you see an `rg.exe` process using lots of CPU while the search is running? 
- Do you see Windows Antimalware using CPU while the search is running? (msmpeng.exe)

**Comment by zmicx** [comment]
Hi @roblourens it takes  more than about 1minute , File opend is listed quickly.

What is rg.exe, I cant fint in in process manager, Animalware using 1% ~ 3% cpu.

A moment ago, I search keyword using ctrl shift f it takes more than a minute, and then search another keyword, it's fast and looks good. I'm not sure it's helpful to you.

**Comment by roblourens** [comment]
It sounds like antimalware is not really consistently working hard during search?

Do you see really slow search in every folder? If you search in a different folder does it complete quickly?
