### ISSUE TITLE
Volume control keys typed in terminal

### ISSUE THREAD

**Issue by galich** [Microsoft/vscode#65949]
Pressing volume buttons on Microsoft Surface Keyboard when Visual Studio Code Insiders terminal is focused produces fun results:

![image](https://user-images.githubusercontent.com/3718155/50623927-cca3d000-0ee8-11e9-91d6-d99f4cc801c4.png)

Version: 1.31.0-insider (user setup)
Commit: ed5363e8659d142fc170cb978389e34102135e8f
Date: 2019-01-02T17:25:53.371Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
😆 Thanks for the quick feedback, this was caused by https://github.com/xtermjs/xterm.js/pull/1849

**Comment by joaomoreno** [comment]
Thanks! :pray:
