### ISSUE TITLE
special characters (<,>,&) not rendered correctly in intellisense preview

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#65956]
We used backtick-enclosed strings for types and since everything is escaped now to render a custom hover window, the error messages are illegible now, for example:

current output

note: expected type `std::option::Option&lt;std::string::String&gt;` found type `std::option::Option&lt;&amp;std::string::String&gt;`

previous output

note: expected type `std::option::Option<std::string::String>` found type `std::option::Option<&std::string::String>`

Ref - https://github.com/rust-lang/rls-vscode/issues/479
Regression from https://github.com/Microsoft/vscode/issues/62370

**Comment by sandy081** [comment]
@jrieken I was assuming we do not support markdown strings in diagnostic message? Was it leaking somehow before?

**Comment by jrieken** [comment]
>  I was assuming we do not support markdown strings in diagnostic message? 

Is this really a diagnostic message and not just a hover?

**Comment by sandy081** [comment]
It is a diagnostic message like follow

`const message = "`std::option::Option<&std::string::String>`";`

**Comment by hokein** [comment]
I encountered this issue (VSCode 1.30.1 ) as well:

1. The C++ LSP server (clangd) sends the hover content `Declared in function main\n\nstd::vector<std::string> s` to vscode
2. The hover dialog renders the content like below, the `<>` around `std::string` is missing

![image](https://user-images.githubusercontent.com/2557445/50706082-19a8b300-105d-11e9-8397-c32442a0548d.png)

**Comment by sandy081** [comment]
Ok, I see the issue. It is because, I am rendering the diagnostic message as markdown and I am escaping the string only for html content. Strangely markdown renderer is not rendering markdown tags always but only some times. For example 

```
"`std::option::Option<&std::string::String>`"
```

Markdown tag (tick) is not considered in above case where as it is in following

```
"this is new line\n\n`std::option::Option<&std::string::String>`"
```

**Comment by sandy081** [comment]
### Analysis

In order to have nice hover for a diagnostic, I was generating the html and sending it using markdown string. While doing this, I am escaping the message, but the markdown tags are not escaped and they are getting rendered.

### Fix

Quick and safe fix is to revert the above change. 

The proper fix would be is to move diagnostic hover rendering as an editor contribution. Otherwise, it is quiet impossible to generate a model hover decoration for a diagnostic that shows message and details (source+code) nicely as I can only provide string or markdown string.

**Comment by sandy081** [comment]
Fix is for Diagnostic messages and not for hover providers. Please verify using a diagnostic provider.

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    const diagnosticsCollection = vscode.languages.createDiagnosticCollection('test');
    vscode.window.onDidChangeActiveTextEditor(e => {
        if (e && e.document) {
            const diagnostics: vscode.Diagnostic[] = [];
            let message = "std::option::Option<std::string::String> found type std::option::Option<&std::string::String>";
            const diagnostic = new vscode.Diagnostic(new vscode.Range(new vscode.Position(10, 1), new vscode.Position(10, 10)), message, vscode.DiagnosticSeverity.Error);
            diagnostic.source = 'test';
            diagnostic.code = 'something';
            diagnostics.push(diagnostic);
            diagnosticsCollection.set(e.document.uri, diagnostics);
        }
    });


}


// this method is called when your extension is deactivated
export function deactivate() {
}
```


![image](https://user-images.githubusercontent.com/10746682/50819178-98397500-1329-11e9-81be-fa5ee1ddeb07.png)

**Comment by joaomoreno** [comment]
LGTM 
![image](https://user-images.githubusercontent.com/22350/50820582-590d2300-132d-11e9-88b9-14c840f7a4ef.png)
