### ISSUE TITLE
C# Method Syntax highlighting issue

### ISSUE THREAD

**Issue by CCludts** [Microsoft/vscode#65951]
Issue Type: <b>Bug</b>

Syntax highlighting breaks when formatting function signatures in certain cases.
Reproduces also with extensions disabled (see screenshot).
Reproduces also on vscode-insiders `1.31.0-insider`

![image](https://user-images.githubusercontent.com/18717967/50624712-21643c80-0f23-11e9-8210-19c35ae7b07e.png)

``` csharp
public class Hello {
    // correct syntax highlighting
    public Task<(string users, string missingUserIds, string unprocessedUserIds)> FetchUsers() {
        return null;
    }

    // different formatting. breaks syntax highlighting
    public Task<(
            string users,
            string missingUserIds,
            string unprocessedUserIds)> FetchUsers() {
        return null;
    }
}
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (4.28GB free)|
|Process Argv|E:\project|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexr00** [comment]
This issue was moved to dotnet/csharp-tmLanguage#146

**Comment by alexr00** [comment]
This issue was moved to davidrios/pug-tmbundle#27
