### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#65950]
live server doesn't work

**Comment by luis12cottom** [comment]
how can I fix this problem

**Comment by oneslash** [comment]
Hi, could you explain in details the issue you are facing?

**Comment by egamma** [comment]
This is not a function that is provided by Visual Studio Code. I assume you are using an extension like https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer. Please file an issue with precise details about what doesn't work against the extension you are using.
