### ISSUE TITLE
Feature request: Toggle inline code and code blocks in comments with a keyboard shortcut

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#65952]
Rendering inline code and code blocks like as displayed on GitHub would be a plus.

**Comment by egamma** [comment]
@jamesray1 can you please illustrate the desired feature with some screen shots.

**Comment by jamesray1** [comment]
`// Highlight inline code like this Foo and press a keyboard shortcut`

This then becomes:
```
// Highlight inline code like this `Foo` and press a keyboard shortcut
```
Example of a code block:
// ```rust
// struct Foo {
//     bar: Bar,
//     baz: Baz,
// }
// ```
This is more useful for Rust doc comments, which have HTML formatting. For block comments you could type a block comment without the backticks above, then highlight and press a keyboard shortcut to toggle the backticks like as shown above. But a toggle for inline code would be more useful, although I guess it's not much more effort to remember to type two backticks.

**Comment by mjbvz** [comment]
Yes, this needs to be implemented per-language. Closing as extension candidate
