### ISSUE TITLE
about Document Localization

### ISSUE THREAD

**Issue by ayatokura** [Microsoft/vscode#6595]
- VSCode Version: Stable, Insiders
- OS Version: Windows, OS X, Linux
- Language: all

Is there any plan for document localization?

**Comment by gregvanl** [comment]
Hello @ayatokura , 
At present we don't have documentation localization scheduled. What languages would you be interested in seeing localized?  Also which topics do you think would be more useful? 
- @gregvanl

**Comment by gregvanl** [comment]
Closing.  Please reopen if you think there is more to do here.

**Comment by ayatokura** [comment]
Sorry for the late reply.  It'll be great if you can provide us Docs in Japanese.  Getting Started, Editor, Customization are very useful. 
https://code.visualstudio.com/docs
