### ISSUE TITLE
Newline missing when pressing Enter between open/close html tags in React files when tags have attributes

### ISSUE THREAD

**Issue by webdevpchoi** [Microsoft/vscode#65955]
- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open .js file and set language mode to Javascript React. 
![image](https://user-images.githubusercontent.com/21182531/50626287-2d7bda00-0ee2-11e9-9be2-eab09c5a050f.png)

2. Configure Emmet to accept Javascript react by adding appropriate object as follow:
```
{
    "materialTheme.accent": "Remove accents",
    "workbench.colorCustomizations": {},
    "workbench.colorTheme": "Material Theme Ocean High Contrast",
    "files.associations": {
        "*.js": "javascriptreact"
    },
    "workbench.iconTheme": "material-icon-theme",
    "emmet.includeLanguages": {"javascript": "javascriptreact"},
}

```
3. Write Emmet abbreviation and hit enter:
![image](https://user-images.githubusercontent.com/21182531/50626165-85661100-0ee1-11e9-9b83-de2750e74c08.png)
4. Which results int the following:
![image](https://user-images.githubusercontent.com/21182531/50626126-4f289180-0ee1-11e9-90be-f3f093357a68.png)
 4. Place cursor in between tags and hit enter:
![image](https://user-images.githubusercontent.com/21182531/50626140-636c8e80-0ee1-11e9-8d46-7790575b89c6.png)
You can see it doesn't indent; instead, I have to use the up arrow and then hit `Tab`. 

5. However, if I do not use an abbreviation, such at a simple `div` and hit `Enter`, and then place the cursor between the tags and hit `Enter` again, it does indent.
![image](https://user-images.githubusercontent.com/21182531/50626228-e4c42100-0ee1-11e9-88be-a8d15fb9931d.png)
![image](https://user-images.githubusercontent.com/21182531/50626234-ed1c5c00-0ee1-11e9-8567-b43f5bb54c10.png)
![image](https://user-images.githubusercontent.com/21182531/50626244-f5749700-0ee1-11e9-9c98-d26bfb17fe41.png)

How can I resolve this so that emmet abbreviations are properly indented in Javascript React files?

Does this issue occur when all extensions are disabled?: Yes!

**Comment by webdevpchoi** [comment]
Yes, I apologize. I thought there would be a new line in between the `<div></div>` tags, and then become automatically tabbed again to show nested code.

**Comment by webdevpchoi** [comment]
> In your step 5, the line with `</div>` does look indented. From that screenshot the problem seems to be that there is no new line between the opening and closing tags. Can you confirm that, that is indeed what you want to report? @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Thanks for confirming that @webdevpchoi 

I see that even typing out `<div className="testing"></div>`, place cursor between open and close tags, press enter doesnt result in the newline + indentation. Therefore, this is related to the `onEnter` rules for js/jsx rather than emmet.

**Comment by webdevpchoi** [comment]
@ramya-rao-a @mjbvz Thank you for your response. Would you be able to guide me to where I can add/edit those rules, in order to indent between elements in a React component? I've tried Googling it, but am coming up short on fixes.

**Comment by mjbvz** [comment]
@webdevpchoi This is a bug. You cannot easily fix it

**Comment by mjbvz** [comment]
@rebornix The root cause of this is that the onEnterRules only look tokens of the current language when determining if they should apply the following jsx we have these languages:

```js
<div style="background: hotpink"></div>
|---|---------------------------|---------|
  |         javascriptreact       jsx-tags
  | jsx-tags
```

This results in us applying the onEnterRules against the `beforeText` of: `>` instead of `<div style="background: hotpink">` as we currently expect

Let me know if this is something that we should fix in VS Code. Otherwise, I'm going to try writing a new onEnterRule that works for the `beforeText` of just `>`

**Comment by mjbvz** [comment]
Actually I think VS Code's behavior is correct. Checking in a fix for the js/ts config

**Comment by domenico-ruggiano** [comment]
hello @mjbvz I'm also having this issue. How is this fixable with js/ts language config?

Thank you
