### ISSUE TITLE
add import action incorrectly adds moment import with a require

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#65964]
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.0-13-generic

Steps to Reproduce:

1. have a code which uses moment, then use:
![image](https://user-images.githubusercontent.com/1305378/50631695-96486e00-0f45-11e9-9ec7-3c84bc205360.png)

2. this is created as the import:

```js
import moment = require('moment');
```

my tsconfig has these configs:
```
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
```

which might be relevant

Does this issue occur when all extensions are disabled?: Yes

This could be a bug in Typescript. If it is, please let me know and I'll gladly reopen this there.

**Comment by mjbvz** [comment]
Thanks. This is already tracked upstream by https://github.com/Microsoft/TypeScript/issues/29038
