### ISSUE TITLE
Allow only official code tidy/beautify extensions

### ISSUE THREAD

**Issue by arunkumar413** [Microsoft/vscode#65963]
Hi Team,

The code tidy/beautify extensions are messing up the code. Seems like most of them are not perfectly implemented. Please allow only the official extensions. I believe Microsoft being a big organization have enough resources to develop and maintain the extensions.  Also focus more on the editor features than the debugger, html server etc,. Compile a list of most commonly used extension use cases and develop them officially.

Here is a screenshot (https://ibin.co/4SELxNtgLBEy.png) of what a code tidy extension has done for a HTML file. I had to manually fix each line.

Thanks,
Arun

**Comment by egamma** [comment]
@arunkumar413 thanks for your feedback. VS Code has rich and diverse ecosystem of extensions and we want to keep it like that. Therefore the best way to improve an extension is to provide feedback by filing issues against extensions with problems, so that the extension author can improve it.
