### ISSUE TITLE
App fails to launch in offline Mode 

### ISSUE THREAD

**Issue by imraiskr** [Microsoft/vscode#65965]
**Version used : 1.30.1**
**Scenario** 1: App fails to launch in offline mode[extension enabled/disabled].

**Scenario** 2: After launching an instance in online mode, again going back to offline mode, app fails to create new instance from start menu, taskbar or from the .**exe** location itself. Works again if toggled back to online, even without reloading the opened instance. 

**Scenario** 3: Even after '**open with code**'  for file and directory' mode is being setup, app fails to launch an instance in offline mode. 

**scenario** 4: **power shell** '**code .**' feature while offline, is also failing with error: 
`dns.js:246
    this._handle = new ChannelWrap();
                   ^
Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13`

otherwise works fine in online mode.

Hope this helps

**Comment by Ash258** [comment]
Dulicate of #7570
