### ISSUE TITLE
Simplify context menu actions on editor/group actions

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#6596]
Related #6536

- VSCode Version: commit 5376d6daa0f74e65fbe425393b8533094e69d9b0
- OS Version: Mac OS X

Steps to Reproduce:

1. Open multiple editor groups
2. Click on the command overflow (ellipses) button

---
I found it a little too easy to accidentally close all the editors in the entire window.

<img width="693" alt="screen shot 2016-05-20 at 3 47 17 pm" src="https://cloud.githubusercontent.com/assets/11839736/15444152/a6b918b6-1ea2-11e6-829b-97410f1b9cc5.png">

This could be detrimental to a user's layout.  Therefore, I think we should prompt confirmation before closing all editors (as it is sort of a destructive change). No need to prompt for closing all editors in group, though, as that is less destructive.

@stevencl do you agree?

**Just my opinion:** Also, what I was expecting to be at the bottom of this list was "Close All Editors in Group,"  as that's a command I would use frequently (and the bottom of a context menu is so easy to hit without thinking).

**Comment by bpasero** [comment]
@stevencl @bgashler1 actually "Close All Editors" would actually close every editor across all groups and not just within the group. I would say it is equally a destructive change of layout as "Close All Editors in Group" is as long as we do not have support for empty groups.

Honestly we did not prompt for closing editors and layouts before and people did not ask for it, I wonder why we would change this now?

**Comment by bpasero** [comment]
@bgashler1 @stevencl when @joaomoreno tested this today (i looked over his shoulder) we also wondered if there should be a "Close All Editors" on the overflow menu of a group because people might misunderstand it as a way to close all editors of the group. Maybe we should not have the other close actions in there?

**Comment by bpasero** [comment]
Outcome from the UX meeting:
* we will shorten the names of the actions when they appear in their context
   * editor: close, close others, (close all?)
   * editor shown as tab: additionally "close left", "close right"
   * group: move left, move right, close all
* we will drop actions that target other contexts (no close all groups, close other groups in the context of editors or groups)

**Comment by bpasero** [comment]
@isidorn by reducing the number of actions in the context menu in "Opened Editors" I decided that we do not need the context menu there anymore. Now it looks like this:

<img width="327" alt="screen shot 2016-05-26 at 08 22 32" src="https://cloud.githubusercontent.com/assets/900690/15565437/062c41a2-231b-11e6-8116-44172cb2045b.png">

Which matches pretty much what we had in working files:

![image](https://cloud.githubusercontent.com/assets/900690/15565460/23872c44-231b-11e6-8339-7a1b3ec0c7d4.png)

**Comment by isidorn** [comment]
Looks good to me, I like that the change from what we had previously is minimal.
