### ISSUE TITLE
Autosave after delay makes cursor jump to beginning of line

### ISSUE THREAD

**Issue by wanglzuz** [Microsoft/vscode#65966]
Issue Type: <b>Bug</b>

This problem started happening after the latest VS Code update.

Whenever I enter a newline (which, thanks to indenting, often takes me to a different position than that of a first character on the line), cursor jumps to the beginning of the line.

This may well be related to the AutoSave feature, because it happens after the number of ms that I have set as delay time for AutoSave; and the problem stopped happening when I turned off the AutoSave / switched to AutoSave on focus change.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1942)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.2
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
plantuml|jeb|2.10.1
docthis|joe|0.7.1
graphql-for-vscode|kum|1.13.0
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.4.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.2
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
stylelint|shi|0.47.0
autoimport|ste|1.5.3
gitblame|wad|2.6.3
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by wanglzuz** [comment]
You are (of course) right, I am sorry. This behaviour is apparently caused by this particular one of my extensions: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
@egamma Should I close this issue and open a new one or can this one be reused?

**Comment by egamma** [comment]
@wanglzuz please file an issue against the repository of the extension https://github.com/editorconfig/editorconfig-vscode. From this issue report you can link to this issue, but I suggest to provide more steps or include a screen recording. I'll close this issue.
