### ISSUE TITLE
Debug Arrow Marker inconsistent rendering

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode#65962]
Issue Type: <b>Bug</b>

When debugging a code file using the Debug Adaptor there's an inconsistent rendering of the step arrow, depending on how a specific source position was reached. This image shows a demonstration:

![](https://raw.githubusercontent.com/mike-lischke/vscode-antlr4/master/images/live-parse-tree.gif)

The step arrow (or what it is called internally) only shows up when a debug step doesn't change source line in the top stack frame. In the image there are 2 debug runs. One with single steps that also change the call stack top entry source line when jumping to subrules and back. As long as the next step remains in the same rule (here `letters` and `digits`) it shows up. The second run uses step-over and hence only uses the top level rule (`start`). As you can see the yellow arrow is shown properly in this case.

Also, when you jump back and forth between stack frames the yellow arrow never shows up.

And the example shows another problem here: there's always that yellow arrow in the gutter, indicating the curent line of the TOS element. It would be better to show that only if the column value in the stack frame is 0. If that value is > 0 the inline arrow should be shown instead (and the gutter arrow should disappear), to support the visualization. That would also correctly show the inline arrow for the first entry of the current line (which is never shown currently).

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (8.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
duk-debug|Har|0.4.1
dot|Ste|0.0.1
numbered-bookmarks|ale|6.1.0
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.2
duk-debug|des|0.4.2
xml|Dot|2.4.0
tslint|eg2|1.0.42
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.7
svg|joc|0.1.4
vscode-phpfmt|kok|1.0.30
vscode-antlr4|mik|2.1.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.11.1
vscode-yacc|se2|1.1.0

</details>

**Comment by mike-lischke** [comment]
Watching the animation I realize it doesn't have to do with the source line at all. In the single step part you can see that no arrow is shown before `LETTER*`. Only when the call stack TOS moves to the semicolon column the arrow is shown again.

**Comment by isidorn** [comment]
Thank you for the nice explanation, however we currently use a heuristic that we only show the arrow inline when a step occured on the same line as the previous step. Reason being: we want to make sure the user is aware that only the column has changed.
We do not always show the inline arrow to not drown the UX in too many details.

I understand there are limitation with this approach but currently we do not plan to change this.

**Comment by mike-lischke** [comment]
Hmm, being myself a UX desktop dev I have a bit of a hard time to accept your explanation :-) I fail to see how the current behavior would be better in any aspect. If less UX changes would be a serious goal here, you could show the debug line background only for every second line. That's nonsense of course, but pretty much the same thing as with the inline arrow showing only if the source line didn't change. And actually, it's not exactly like that as I have shown in my second message. You probably show the arrow only when the source line stayed and same **and** the column changed.

In any case this behavior is only confusing, but thanks anyway.
