### ISSUE TITLE
Debug Panels Location Options

### ISSUE THREAD

**Issue by Novack** [microsoft/vscode#65971]
The Debug Panel location is bound to the side bar, and thus, only can be positioned right or left.
![imagen](https://user-images.githubusercontent.com/1981463/50644757-82eed000-0f50-11e9-8979-07666244c993.png)

I presume web development has less issues with this, but working with C#, we use the debugger a lot. This puts in high evidence how unconfortable the debug panels location results (there are reasons that Visual Studio IDE has by default the debug panels at the bottom), forcing continually to resize the panels width in order to read the content in either of the panels (watchs, callstack, etc). 

So can we have an option to display the debug panels in the section where the consoles currently are, at the bottom?

**Comment by isidorn** [comment]
Dup of use grid for workbench layout.
This shuold be work in progress, adn we might introduce this in the future

**Comment by Novack** [comment]
Thank you, will search for that request and up vote.

**Comment by Novack** [comment]
Hey @isidorn could you point me to the ticket where the task you mention is tracked? By the name of it, looks like should be #50853 but they report is not related to my request.

**Comment by isidorn** [comment]
That's the one

**Comment by isidorn** [comment]
Oh so it will not be covered by that. My mistake. Reopening this one as a feature request

**Comment by Novack** [comment]
Thanks!

**Comment by JordanKadish** [comment]
Hey idk how much priority this is being given to this but I'd really like that debugger sidebar in the panels section at the bottom too because I have to manage large states daily that can be better viewed in a horizontal bar/panel

**Comment by Novack** [comment]
Have come to understand that VSCode, like most other IDEs aout there, its what it is. On this case is worst, because internally, is a behemoth. It is a mashup of different projects where everything depends on something else, vscode, monaco, onmisharp, rosilyn, and so on.

So even the most trivial of fixes will take a year to see the light. You can imagine what would happen with requests like this one. It will only happen if at some point it gets on the drawing table of the steering team, not because we asked, but because some other brilliant mind decided is good for everyone.

In the end VSCode will unlikely shake off the Web-dev ide that identify its genetic lineage, so we only are foreigners here 💔

**Comment by isidorn** [comment]
This is currently possible thanks to work done by @sbatten 
Thus clsoing this.

Please note that moving views is still work in progress and we plan to improve this experience.
Please try it out and let usk now what you think. The new vscode stable should have it in a couple of days.

**Comment by RayKoopa** [comment]
I'd like to test this, but I'm not sure how to achieve it. What do I need to do to, for example, move the Variables view to the bottom panel?

**Comment by JordanKadish** [comment]
I will try this as soon as it's available

**Comment by SidoShiro** [comment]
Good job !
