### ISSUE TITLE
history: mac os x dock shows incorrect history

### ISSUE THREAD

**Issue by clshortfuse** [Microsoft/vscode#65978]
- VSCode Version: 1.31.0-insider - e02e44464c02d617b98d0a3265bf5efef7794436
- OS Version: Mac OS X 10.14.2

Steps to Reproduce:

1. Open multiple project in VS Code
2. Right click on VS Code in dock and contents aren't updated

Does this issue occur when all extensions are disabled?: Yes

File=>Open Recents works as expected as well as the Welcome page. It's just the dock.

The non-insider version (1.30.1) works fine.

**Comment by Fishbowler** [comment]
I'm seeing this same behaviour in the 1.31.0 stable release.

Right-clicking the Dock icon doesn't show any of my regularly accessed projects, or even the one I've just closed.

**Comment by clumsyme** [comment]
I have the same issue in 1.31.1.

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/57272
