### ISSUE TITLE
launch.json: Running an npm script without debugging

### ISSUE THREAD

**Issue by tzachshabtay** [Microsoft/vscode#65975]
I saw this issue: https://github.com/Microsoft/vscode/issues/2780
And apparently there's supposed to be a "noDebug" flag that can be used?

So I tried this:

```
{
    "type": "node",
    "request": "launch",
    "name": "Server- Storybook",
    "noDebug": true,
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": "npm",
    "runtimeArgs": [
        "run-script", "start:storybook"
    ]
},
```

But I'm getting `Property noDebug is not allowed`.

I would like to combine this and a chrome debugger into a single compound, so launching the compound will start the storybook server and debug the client, and stopping will kill them both.
But I don't see a way to tell vscode not to use the debug adapter for the server (and storybook doesn't seem to have an option for specifying a debug hook) so it times out when I try to launch it.

**Comment by isidorn** [comment]
You can run any script wihtout debugging just by execting F1 > start without debugging command.
You co not have to add any attributes to your launch configuraiont.

As for your client / server setup please try out compound debugging. More about that there https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations

**Comment by tzachshabtay** [comment]
@isidorn I know about compound configuration, as I said I want to use it, but I can't, because the server side doesn't work as I can't configure it to not use the debug adapter and the debug adapter times out.
Won't F1 > start without debugging run the entire compound without debugging?
Then it doesn't solve my problem. Like I said, I want to debug the client and run the server without debugging, and I want to do it in a single command, which is why I need a flag like `noDebug` on the server section.

**Comment by isidorn** [comment]
Thanks for providing more details. The following works perfectly for me
`hey.js`
```
console.log('hello');
```

`launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/hey.js"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program2",
            "noDebug": true,
            "program": "${workspaceFolder}/hey.js"
        }
    ],
    "compounds": [
        {
            "name": "Compound",
            "configurations": ["Launch Program", "Launch Program2"]
        }
    ]
}
```

You will get the warning that "noDebug" is not allowed (as you pointed out) but it will get respected. So everything should work just fine.
