### ISSUE TITLE
i am writing a bot for my discord server and it showes a 'module' but i didnt write 'module'. what should i do?

### ISSUE THREAD

**Issue by MimaHD22** [Microsoft/vscode#65972]
Issue Type: <b>Performance Issue</b>

RESTART: C:\Users\saturn\Desktop\mischa ist geilo\programmierung\microsoft visual studio code\discord-bot.py 
Traceback (most recent call last):
  File "C:\Users\saturn\Desktop\mischa ist geilo\programmierung\microsoft visual studio code\discord-bot.py", line 6, in <module>
    bot = commands.bot(command_prefix='/')
TypeError: 'module' object is not callable

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz (2 x 1440)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|1.93GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1

(1 theme extensions excluded)

</details>

**Comment by MimaHD22** [comment]
ich hasse euch auch

Am Do., 3. Jan. 2019, 16:33 hat vscodebot[bot] <notifications@github.com>
geschrieben:

**Comment by MimaHD22** [comment]
> /question

what do you mean?

**Comment by usernamehw** [comment]
That it's not a problem with vscode.

**Comment by MimaHD22** [comment]
with what than?

**Comment by MimaHD22** [comment]
hello?

**Comment by egamma** [comment]
This looks like a problem with your python code. Given the information you provided it is not possible narrow this down further.

**Comment by MimaHD22** [comment]
ok hut can i even fix this?

Am 04.01.2019 20:20 schrieb "Erich Gamma" <notifications@github.com>:

This looks like a problem with your python code. Given the information you
provided it is not possible narrow this down further.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/65972#issuecomment-451541086>,
or mute the thread
