### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by tunedin76** [Microsoft/vscode#65974]
Issue Type: <b>Bug</b>

Formatting feature is now gone. After a complete re-install and removal of all settings in APPDATA and USERPROFILE, I cannot get php to format.  I tried 3 extentions. phpfmt, PHP Formatter, and php cs fixer.  None allowed a Format Document on the context and claimed that no formatter was avail for php

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.96GB (7.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-intelephense-client|bme|0.8.8
vscode-sshfs|Kel|1.11.2
material-icon-theme|PKi|3.6.2
php-formatter|Sop|0.2.4

(1 theme extensions excluded)

</details>

**Comment by tunedin76** [comment]
Just FYI - I removed all PHP formatting
 updated my config.json to be able to use it....
`{
    "workbench.colorTheme": "Cobalt Next",
    "sshfs.configs": [
        {
           ...
        },
        {
            ...
        }
    ],
    "workbench.iconTheme": "material-icon-theme",
    "php.suggest.basic": false,
    "editor.minimap.enabled": false,
    "editor.fontLigatures": true,
    "editor.fontFamily": "'Fira Code', 'Arial', monospace",
    "php.validate.executablePath": "C:\\wamp64\\bin\\php\\php7.2.4\\php.exe",
    "files.associations": {
        "*.php": "php",
        "*.phtml": "php"
    },
    "php.validate.run": "onType",
    "editor.cursorSmoothCaretAnimation": true,
    "editor.formatOnType": true,
    "editor.smoothScrolling": true,
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    "emmet.includeLanguages": {
        "blade": "html"
    },
}`

and now ctrl-k, ctrl-f now formats a selection...   I am not sure if it is because it is formatting as JS or TS... but how would I make formatting customizations now?

**Comment by tunedin76** [comment]
Just found out the same has happened to ALL third party extension formatters.. VUE - Vetur, with Prettier, phpfmt, 
This is a serious bug. I have posted to the extension authors as well:
phpfmt,
php-cs-fixer
Vetur
Prettier
Prettier-Now

I have tried each of these as the only extension on a fresh install

**Comment by tunedin76** [comment]
It seems there is a bug in VS Code for ALL of the extensions that format.

**Comment by roblourens** [comment]
phpfmt works fine for me.

> None allowed a Format Document on the context and claimed that no formatter was avail for php

Please make sure that the extension is installed and that you've reloaded vscode.

**Comment by tunedin76** [comment]
I have tried ctrl-k ctrl-f, F1 - Format Document, and F1 - phpfmt: Format Document here are the results.

You see the phpfmt in the extensions, and I yesterday have completely removed vscode, and the user data / extensions for a re-install. 

With nothing else installed (no extensions) I tried 3 different PHP formatters. I use wamp's PHP 7.2 and it works for the validation - I have set the path and tried to define the absolute path in the settings.json for phpfmt.  CS-Fixer doesn't recognize.

Before I installed Vue.JS Pack, the Ctrl-K Ctrl-F was working without ANY PHP formatter, so I am assuming that it was formatting it as JS.... Is there a setting I am missing? I feel this is on my side, however it all worked until the update in Nov (I think the Oct update).  I do not believe that I made any changes, as I am pretty OCD about my setup, but it is possible.

Either way, I have followed instructions for 3 different PHP formatters to the T as the only extension on a fresh install and I cannot get any PHP formatting to work.

![capture](https://user-images.githubusercontent.com/16789318/50689770-f9470d00-0ff8-11e9-8897-b891b116e9d3.PNG)
![capture2](https://user-images.githubusercontent.com/16789318/50689789-0c59dd00-0ff9-11e9-8d98-842ab14bfea2.PNG)
![capture3](https://user-images.githubusercontent.com/16789318/50689806-209dda00-0ff9-11e9-9ee9-6a450aa4ceb0.PNG)

After all the extensions I need for my Dev work, this is my settings:
`{
  "workbench.colorTheme": "Cobalt2",
  "sshfs.configs": [
    {
     ...
    },
    {
     ...
    }
  ],
  "workbench.iconTheme": "material-icon-theme",
  "php.suggest.basic": false,
  "editor.minimap.enabled": false,
  "editor.fontLigatures": true,
  "editor.fontFamily": "'Fira Code', 'Arial', monospace",
  "php.validate.executablePath": "C:\\wamp64\\bin\\php\\php7.2.4\\php.exe",
  "phpfmt.php_bin": "C:\\wamp64\\bin\\php\\php7.2.4\\php.exe",
  "files.associations": {
    "*.php": "php",
    "*.phtml": "php"
  },
  "php.validate.run": "onType",
  "editor.cursorSmoothCaretAnimation": true,
  "editor.smoothScrolling": true,
  "files.trimFinalNewlines": true,
  "emmet.includeLanguages": {
    "blade.php": "html"
  },
  "vetur.format.options.tabSize": 4,
  "vetur.format.options.useTabs": false,
  "blade.format.enable": true,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatter.postcss": "prettier",
  "vetur.format.defaultFormatter.scss": "prettier",
  "vetur.format.defaultFormatter.less": "prettier",
  "vetur.format.defaultFormatter.stylus": "stylus-supremacy",
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.ts": "prettier",
  "eslint.enable": true,
  "window.zoomLevel": 0,
  "files.trimTrailingWhitespace": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "es5",
  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": [],
  "eslint.autoFixOnSave": true,
  "editor.insertSpaces": true,
  "editor.formatOnSave": true,
  "editor.detectIndentation": true,
  "editor.tabSize": 4,
  "editor.formatOnPaste": false,
  "editor.formatOnType": true,
  "editor.renderControlCharacters": true,
  "editor.renderWhitespace": "none",
  "files.exclude": {
    "**/node_modules": true,
    ".gitignore": true,
    ".eslintignore": true,
    ".eslintrc.js": false,
    ".babelrc": true,
    ".editorconfig": true,
    ".postcssrc.js": true,
    ".jshintrc": true,
    "build": true,
    "config": true
  },
  "eslint.validate": [
    {
      "autoFix": true,
      "language": "javascript"
    },
    {
      "autoFix": true,
      "language": "vue"
    }
  ],
  "attrsSorter.order": [
    "is",
    "v-for",
    "v-if",
    "v-else-if",
    "v-else",
    "v-show",
    "v-cloak",
    "v-once",
    "v-pre",
    "id",
    "ref",
    "key",
    "slot",
    "v-model",
    "v-model.+",
    "v-bind",
    "v-bind.+",
    ":.+",
    "v-text",
    "v-text.+",
    "v-html",
    "v-html.+",
    "class",
    "v-on.+",
    "@.+",
    "name",
    "data-.+",
    "ng-.+",
    "src",
    "for",
    "type",
    "href",
    "values",
    "title",
    "alt",
    "role",
    "aria-.+",
    "$unknown$"
  ],
  "gitlens.currentLine.enabled": false,
  "gitlens.hovers.currentLine.over": "line",
  "gitlens.codeLens.enabled": false
}
`

I took out settings for sshfs for security reasons.
![capture4](https://user-images.githubusercontent.com/16789318/50690280-b71ecb00-0ffa-11e9-8ae7-2d0c3cb0e07c.PNG)

I appreciate all your help, and thank you for not immediately closing this ticket.

James

**Comment by tunedin76** [comment]
I have gotten PHP CS-Fixer to work, and be recognized. It is most likely an error on my end but there is little in the way of documentation troubleshooting multiple independent extensions. 
I hope that it will continue to work, thank you for your time.

**Comment by tunedin76** [comment]
I did a step-by-step installation of PHP formatter one last time I had gotten it working earlier in the day and then something caused it to stop working again I'm sure it's a settings issue I just wish that there was a little bit more collaboration between the extension authors and the vs code contributors for better documentation in either case I'll let you know definitely if I find out more



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
