### ISSUE TITLE
Empty lines after enlarging Debug Console

### ISSUE THREAD

**Issue by mymikemiller** [microsoft/vscode#65980]
Issue Type: <b>Bug</b>

# Repro steps
* Make your vscode window fairly small
* Print a really long message to the Debug Console (one that line wraps a couple times)
* Print another message to the Debug Console
* Notice that there is no space between the two messages
* Enlarge the vscode window so the first message no longer line wraps

# Expected
There should be no space between the two messages.

# Observed
There is an unnecessary blank line between the two messages. Each printed line is allocated however many lines it took to display when the Debug Console was at its initial size. When enlarged, the text takes up fewer lines, but the number of allocated lines stays the same, resulting in unnecessary blank lines.

# Note
The reverse also occurs: If you print to the Debug Console when the window is large, then shrink it, the text gets cut off and only displays whatever text fits in the originally allocated lines (no extra lines are allocated to fit the full message). There's not even a tooltip allowing you to see the full message; the only way to see the missing text is to re-enlarge the window.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.56GB free)|
|Process Argv|-psn_0_5612890|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.21.1
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
tslint|eg2|1.0.42
scriptcsRunner|fil|0.1.0
code-runner|for|0.9.5
vscode-pull-request-github|Git|0.3.2
Kotlin|mat|1.7.0
python|ms-|2018.12.1
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
vscode-typescript-tslint-plugin|ms-|0.3.0
debugger-for-chrome|msj|4.11.1
vscode-wakatime|Wak|1.2.5

</details>

**Comment by isidorn** [comment]
I acknowledge the issue and this should be somewhat tackled via https://github.com/Microsoft/vscode/pull/64797

**Comment by isidorn** [comment]
This should be fixed in latest. if you still see it let me know
