### ISSUE TITLE
Editor Stacks: 2 preview editors possible in same group

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#6598]
Related #6536

- VSCode Version:
- OS Version: Mac OS X

Steps to Reproduce:

1. Open a file as a preview editor (one click)
2. **Save As** somewhere
3. Notice that you now have 2 preview editors at the same time. We should only allow 2.

<img width="223" alt="screen shot 2016-05-20 at 4 20 48 pm" src="https://cloud.githubusercontent.com/assets/11839736/15444574/1eceb456-1ea7-11e6-8ede-2d937757dda2.png">

**Comment by bpasero** [comment]
@bgashler1 actually you are not seeing 2 preview editors, there is still just one. But we do not close the preview editor when it is being saved as another file, which is arguably the bug.

**Comment by bpasero** [comment]
This should be fine now. The rule is that any file (including untitled ones) that gets "Saved As" will be replaced across all editor stacks if found.
