### ISSUE TITLE
Extension search for "vue" is abysmal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#65987]
Previously: https://github.com/Microsoft/vscode/issues/24511

Now if you search for Vue, Vetur doesn't even show up in the first page despite being the most popular Vue extension. The install count of the 24 Vue extensions in first page combined is not even half of Vetur's install count.

![image](https://user-images.githubusercontent.com/4033249/50652857-a6a81b00-0f3c-11e9-95e2-e2838082acfc.png)

A new Vue user coming to VS Code have a hard time finding Vetur by organic search. He might be misled to install a lot of the random extensions in Marketplace and believe VS Code has poor support for Vue files.

/cc @hamenon

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

Merging into https://github.com/Microsoft/vscode/issues/42890

**Comment by kesane-msft** [comment]
@octref - our search algorithm gives more weightage to matches in the extension's display name. If you add the "vue" term in your display name your extension would start showing (mostly) as the top result.
