### ISSUE TITLE
Adding any theme other than the defaults adds a significant lag

### ISSUE THREAD

**Issue by lvegerano** [Microsoft/vscode#65982]
Issue Type: <b>Performance Issue</b>

- Add any theme
- Experience the lag

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   131	 86616	code main
    0	    98	 86650	   gpu-process
    0	   279	 86772	   window (project-tab-column.hbs — coschedule)
    0	   147	 86829	     extensionHost
    1	   377	 86833	       electron_node tsserver.js 
    0	    66	 86891	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 86835	       electron_node eslintServer.js 
    0	    33	 86892	       /Users/luis/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.1071/dotnet_modules/vsls-agent --autoexit --pipe 5076894808474ba8b4aeeb71e462b3de --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	    33	 87107	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=86829
    0	    98	 88288	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=86829
    0	    98	 86830	     watcherService
    0	    66	 86838	     searchService
    0	     0	 87128	     /bin/zsh -l
    0	    66	 86836	   shared-process
    0	    82	 88966	   window (Issue Reporter)
    0	     0	 88972	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (project-tab-column.hbs — coschedule)
|    Folder (coschedule): more than 25463 files
|      File types: js(16500) png(3702) hbs(962) scss(805) css(674) php(483)
|                  gif(473) jpg(394) json(305) html(227)
|      Conf files: package.json(196) webpack.config.js(19) grunt.js(4)
|                  launch.json(1) jsconfig.json(1) gulp.js(1)
|      Launch Configs: node(3) chrome(2);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
gitlens|eam|9.3.0
emberjs|emb|1.0.1
vscode-ember|emb|0.2.0
vsc-material-theme|Equ|2.6.3
vsc-ember-cli|fel|0.3.3
ember-related-files|jos|1.3.1
vsliveshare|ms-|0.3.1071
debugger-for-chrome|msj|4.11.1
EmberES6Snippets|pha|2.3.3
vscode-icons|rob|8.0.0

(1 theme extensions excluded)

</details>

**Comment by lvegerano** [comment]
status with a theme on I get no more that 15 FPS

<details>
<summary>Process Info</summary>

```
CPU %   Mem MB     PID  Process
    0      147   86616  code main
    1      131   86650     gpu-process
    0      279   86772     window (schedule.js — coschedule)
    0      147   86829       extensionHost
    0      360   86833         electron_node tsserver.js
    0       66   86891           electron_node typingsInstaller.js typesMap.js
    0       82   86835         electron_node eslintServer.js
    0       33   86892         /Users/luis/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.1071/dotnet_modules/vsls-agent --autoexit --pipe 5076894808474ba8b4aeeb71e462b3de --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0       33   87107         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=86829
    0       98   88288         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=86829
    0       98   86830       watcherService
    0       66   86838       searchService
    0        0   87128       /bin/zsh -l
    0       82   86836     shared-process
Workspace Stats:
|  Window (schedule.js — coschedule)
|    Folder (coschedule): more than 25463 files
|      File types: js(16500) png(3702) hbs(962) scss(805) css(674) php(483)
|                  gif(473) jpg(394) json(305) html(227)
|      Conf files: package.json(196) webpack.config.js(19) grunt.js(4)
|                  launch.json(1) jsconfig.json(1) gulp.js(1)
|      Launch Configs: node(3) chrome(2)
```
</details>

**Comment by egamma** [comment]
@lvegerano I cannot reproduce this with some themes I've tried. Can you be more specific and name a theme where you observed the slow down.

Please see also https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by egamma** [comment]
@lvegerano you write

>Experience the lag

can you be more specific how you experience the lag? Can you create a performance profile when this happens as described in https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by lvegerano** [comment]
Sorry the lag I experience is while:
scrolling
typing 
clicking tabs
I will get you a performance profile

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Adding @alexandrudima since this seems to be around the editor.

@lvegerano is scrolling also slow when all editors are closed and you try in the file explorer to the left?

**Comment by lvegerano** [comment]
@bpasero 

> is scrolling also slow when all editors are closed and you try in the file explorer to the left?

Yes is significantly slow.

I will try the nightly and report back.

**Comment by bpasero** [comment]
OK
