### ISSUE TITLE
Don't Automatically Expand XAML Folded Code

### ISSUE THREAD

**Issue by Lotharyx** [Microsoft/vscode#65984]
There have been a couple related issues that are not quite the same.  Here is my specific use case:

I am editing a XAML document in the visual designer, in the cases where visual mouse actions are either cumbersome or generate unwanted properties.

If I fold, say, a ComboBox's contents, then drag that ComboBox entity somewhere else in the document, the ComboBox unfolds.  It also unfolds if I do a Ctrl + A, Ctrl + K, F to fix up misaligned tabs after moving stuff around.  Some of my comboboxes have very long lists (but they are static, so a data binding is pointless).

It would be nice to be able to turn off ALL forms of auto-unfolding.

This is my first feature request, so please forgive me if I've omitted anything important; I will of course be glad to add to the conversation whatever is needed.

**Comment by egamma** [comment]
@Lotharyx this is the repository of Visual Studio Code and Visual Studio Code has no visual designer. I therefore suspect that you want to file this feature request against 'Visual Studio' and not 'Visual Studio Code'.
