### ISSUE TITLE
Cannot resize Keyboard Shortcuts column sizes -> Add column resize handle bars and horizontal scroll bar

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#65999]
### Visual Studio Code Version
![vs code version](https://user-images.githubusercontent.com/9283914/50669483-be77b180-0fc5-11e9-983a-d59cdde245c6.png)

### Steps to Reproduce:

1. Open Visual Studio Code with default window size.
2. Create two editor groups horizontally.
3. Open Keyboards Shortcuts editor and resize editor group so the editor's content won't fit.

Does this issue occur when all extensions are disabled?
- [x] Yes
- [ ] No

### Screenshot

![vs code key bindings](https://user-images.githubusercontent.com/9283914/50669579-41990780-0fc6-11e9-9da7-1f520c685454.png)

### Current Result

You are not able to read the columns' contents or get to read the currently selected keyboard shortcut.

### Expected Result

1. Column handle bars should provide for resizing each of the columns. Double-clicking a column's right border should resize the column to optimum width.
2. A horizontal scrollbar should provide for scrolling through the Keyboards Shortcuts table horizontally if the horizontal size of the table exceeds the editor panel's width.

**Comment by sandy081** [comment]
Resizing columns in the keyboard shortcuts editor is supported now - https://github.com/microsoft/vscode/issues/118123
