### ISSUE TITLE
Cmd+O on .code-workspace file should open workspace in new window

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#65990]
Cmd+O + Opening a `.code-workspace` file should open the workspace in a new window, not opening the workspace file in a Text Editor in the existing window.

**Comment by bpasero** [comment]
I disagree, Cmd+O is for opening a file into the editor.

**Comment by octref** [comment]
Although on macOS Cmd+O can also change workspace folder...
I would say when one runs it and choose a workspace file [s]he is never expecting to open that single file.
