### ISSUE TITLE
Unable to start Code on 32-bit Ubuntu 14

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#65998]
- VSCode Version: Latest Insiders. 1.31.0
- OS Version: Ubuntu 14, 32-bit.

Steps to Reproduce:

1. Install and Launch VS Code Insiders.

Does this issue occur when all extensions are disabled?: Yes

Bug: When executed from the command line it shows "/lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/share/code-insiders/bin/../code-insiders". Is this a VS Code bug or do I need to somehow update my OS or dependencies? The non-Insiders VS Code works and so did the previous Insiders from December 17th.

This is how it looks:

![image](https://user-images.githubusercontent.com/19859882/50669105-1c7da800-0f78-11e9-9346-775fb6811979.png)

**Comment by kalpaj12** [comment]
Oh, so this happens on linux as well,
@sean-mcmanus , please try connecting to the internet, and try running VS Code again.
Let me know if that works.

**Comment by sean-mcmanus** [comment]
I am connected to the internet -- that's how I downloaded the latest VS Code Insiders.

**Comment by bpasero** [comment]
@Tyriar can you take this?

**Comment by Tyriar** [comment]
I'm having trouble getting a VM running, does this fix it?

```
sudo apt-get install libdbus-1-3
```

**Comment by sean-mcmanus** [comment]
@Tyriar I ran that command, but it said "libdbus-1-3 is already the newest version" and the same failure occurs afterwards.

**Comment by sean-mcmanus** [comment]
@Tyriar Strangely, VS Code is working now when I run "code-insiders" from the command line (I don't understand why it would be different), but whenever I launch the app from the left-side task launcher it fails. This is what is shows in the developer tools:

![image](https://user-images.githubusercontent.com/19859882/50707591-28b84280-1016-11e9-8af0-72d7a4de2ee8.png)

The same failure occurs with today's Insiders too.

**Comment by bpasero** [comment]
I reported this as https://github.com/electron/electron/issues/16364 for the error output in the command line.

I can however not reproduce any crash or hang, even though I see the error message printed the application seems to work fine.

@sean-mcmanus do you still get the crash?

**Comment by sean-mcmanus** [comment]
I upgraded to the today's insiders and the bug is fixed (or no longer repros). The command line message still occurs, but it seems unrelated.

**Comment by bpasero** [comment]
Ok closing then.
