### ISSUE TITLE
Randomly get current identifier as completion

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#65997]
From Microsoft/TypeScript#24009

To reproduce:

* Type `namespace `
* Type randomly. Every once in a while, the current text will be recommended as a completion. I've gotten this to reproduce with `const `also.

May be a vscode bug. @mjbvz Any idea how this could happen?

![werwke](https://user-images.githubusercontent.com/19274678/39842477-5e260cd2-539b-11e8-8b7a-aad00ef814e5.jpg)

Here is the tsserver log where tsserver returns saying no completion.
[tsserver.log](https://github.com/Microsoft/vscode/files/2725294/tsserver.log)

**Comment by mjbvz** [comment]
We show text based suggestions when no completions are returned from typescript. Here's the typescript request for this case:

```
[Trace  - 3:15:43 PM] Sending request: completionInfo (163). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "untitled:^Untitled-1",
    "line": 3,
    "offset": 14,
    "includeExternalModuleExports": true,
    "includeInsertTextCompletions": true,
    "triggerCharacter": "."
}
[Trace  - 3:15:43 PM] Response received: completionInfo (163). Request took 4 ms. Success: false . Message: No content available.
```

You can disable this by setting: `"editor.wordBasedSuggestions": false`.

I remember discussing with Andy how the TypeScript server could tell us that any text would be a valid completion (such as when defining a new namespace like this). Do you know if that is something that was implemented on the TypeScript side

**Comment by sheetalkamat** [comment]
`isNewIdentifierLocation` is indication for that. I have Microsoft/TypeScript#29316 to respond with that. Notice that I still see those random completions so you would still need to handle at vscode side.

**Comment by mjbvz** [comment]
@jrieken I believe there is a bug in word based suggestion that can cause the current word to be suggested. Repo:

1. With `"editor.wordBasedSuggestions": true`
1. In the following TS file:

```ts
namespace _.| {
}
```

1. With cursor at the `|`. Quickly enter a bunch of letters.
1. Every so often, word based suggestions will show for the word you are currently typing:

![screen shot 2019-01-11 at 4 29 54 pm](https://user-images.githubusercontent.com/12821956/51066293-2f1e5f80-15be-11e9-8a17-9e96f3e2183c.png)

**Comment by jrieken** [comment]
Hm, the logic to filter the current word so that we don't suggest that...
