### ISSUE TITLE
Inconsistent snippet name listing

### ISSUE THREAD

**Issue by yangshuairocks** [Microsoft/vscode#65992]
- VSCode Version:

Version: 1.31.0-insider
Commit: 7805023eaa46db45d3c24a4c38c0d07c087cf1b3
Date: 2019-01-03T06:20:50.629Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

- OS Version:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

Steps to Reproduce:

1. Create several PowerShell user snippets:
```powershell
{
    "ForEach-Object with index on the pipe line": {
        "scope": "powershell",
        "prefix": [
            "for"
        ],
        "body": [
            "${10:%} {\\$${20:i} = ${30:0};\\} {\n    ${0:}\n    \\$${20:i}${40:++};\n\\}"
        ],
        "description": "ForEach-Object with index on the pipe line"
    }
}
```

```powershell
{
    "Process multiple elements in foreach demo": {
        "scope": "powershell",
        "prefix": [
            "foreach"
        ],
        "body": [
            "\\$data = 1, 100, 2, 200, 3, 300\n\nWrite-Host \\$data.GetType()\n\nforeach(\\$x in \\$data) \n{\n    Write-Host \\$x\n    Write-Host \"-------------\"\n\\}\n\nforeach(\\$x in \\$data) \n{\n    \\$col1 = \\$x\n    # We can use the little known automatic variable \\$foreach to move to next element\n    ${10:\\$foreach.MoveNext() | Out-Null}\n    # and get its value. This way, we are processing 2 elements at a time instead of just one.\n    \\$col2 = ${20:\\$foreach.Current}\n\n    [PSCustomObject]@{\n        ColumnOne = \\$col1\n        ColumnTwo = \\$col2\n    \\}\n\\}"
        ],
        "description": "Process multiple elements in foreach demo"
    }
}
```
```powershell
{
    "for loop": {
        "scope": "powershell",
        "prefix": [
            "for"
        ],
        "body": [
            "for (\\$${10:i} = ${20:0}; \\$${10:i} -${30:lt} ${40:\\$${50:array}.${60:Count}${70:}}; \\$${10:i}${80:++}) {\n    ${0:}\n\\}"
        ],
        "description": "for loop"
    }
}
```

2. Open a new editor tab and set its mode to PowerShell. Type `for` and you will see:

![image](https://user-images.githubusercontent.com/39968/50655778-15808500-0fcc-11e9-9595-2c63deea902d.png)

![image](https://user-images.githubusercontent.com/39968/50655788-1d402980-0fcc-11e9-8902-2b8c6b124b59.png)

As you can see, they are all user snippets. But the display in the suggestion list is inconsistent. Need to make them all display the prefix as well as the description. 

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/39968/50655958-a5263380-0fcc-11e9-9c1f-a5f0b8e82fbb.png)

**Comment by jrieken** [comment]
<img width="573" alt="screenshot 2019-01-08 at 14 00 26" src="https://user-images.githubusercontent.com/1794099/50832201-c335c000-134d-11e9-879b-bbd736fa74ce.png">

Doesn't actually reproduce for me... Can you share the full file with me?

**Comment by yangshuairocks** [comment]
I tried on a newly created VM with the three snippets I mentioned and I can't reproduce the issue. So it seems the three snippets is not the reason here. Do you have any suggestion on how can I debug and find the root cause?

**Comment by jrieken** [comment]
Hm, tricky... Do you have any special settings for the suggest widget? What do you see when running F1 > Insert Snippet?
