### ISSUE TITLE
Minimap not hide anymore

### ISSUE THREAD

**Issue by redrbrt** [Microsoft/vscode#65995]
- VSCode Version: 1.30.1 (system setup)
- OS Version: Windows_NT x64 10.0.17134

I can't disable/toggle minimap no more, i tried view->toggle minimap as also settings json settings.json => "editor.minimap.enabled": false

Restart vscode, nothing is working, is there anything i'm doing wrong? not sure with what update stops working

Does this issue occur when all extensions are disabled?: Yes/No
Yes, even when all extensions are disabled

**Comment by egamma** [comment]
I cannot reproduce this, please see the attached movie

![minimap](https://user-images.githubusercontent.com/172399/50703097-58397000-1053-11e9-808a-0e3f0d25a77c.gif)

**Comment by alexandrudima** [comment]
The action uses [`IConfigurationService.updateValue`](https://github.com/Microsoft/vscode/blob/7a835ad2642760345b02d4c8c7b899559926f4c8/src/vs/workbench/parts/codeEditor/electron-browser/toggleMinimap.ts#L26:L30) in a very straight forward way... Otherwise, perhaps editing works and we are not receiving file change events for the `settings.json`...

@sandy081 Giving to you to investigate, since this reproduces also in the UI (look at the GIF from @redrbrt).

**Comment by sandy081** [comment]
@redrbrt Can you please check if there are any errors in the developer tools console? Use command `Toggle Developer Tools`.

**Comment by redrbrt** [comment]
Sure (this is "on ready" vscode reloaded)
![extensions enabled](https://user-images.githubusercontent.com/1587912/50795602-60ccb900-1294-11e9-82b5-a4fec6096371.PNG)
On "toggle minimap" event/action no log is fired

**Comment by sandy081** [comment]
Can you please open the `settings.json` file which is the source of this setting and check if the value of `editor.minimap.enabled` is getting changed when you are updating it from the Settings Editor and View menu ?

Note: You can open the settings.json file using the button mentioned below

<img width="1061" alt="screenshot 2019-01-10 at 10 55 06" src="https://user-images.githubusercontent.com/10746682/50960856-a1ac1400-14c6-11e9-8330-b7d4c9597058.png">

**Comment by redrbrt** [comment]
Ok, looks like the json value is getting changed, but minimap UI does not apply change

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1587912/50975047-35bfb080-14b2-11e9-9eef-25f618724d96.gif)

**Comment by sandy081** [comment]
@redrbrt Looks like you have this configuration `editor.minimap.enabled` is overridden in workspace setting which is taking the precedence. Can you please open workspace settings and check that.

**Comment by sandy081** [comment]
User settings are applied for all instances  and Workspace settings are meant for configuring VS Code for the workspace you opened and they override any settings from user space. 

So removing it from workspace settings fixed it?

**Comment by redrbrt** [comment]
Yes, it fix it, thank you
