### ISSUE TITLE
Git conflict highlighting can get messed up easily

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#66]
Ubuntu 12.04, vscode 0.10.1

Deleting and undoing the line doubles the highlight: (stays after closing and reopening the file)

![highlight1](https://cloud.githubusercontent.com/assets/2193314/11248144/728d1290-8dd4-11e5-843d-b1207570c8e0.png)

Deleting from the end of the line above the `=======` to the end of the line starting with `>>>>>>>`:

![highlight3](https://cloud.githubusercontent.com/assets/2193314/11248233/e578f95e-8dd4-11e5-92a9-603361d90e59.png)

Undoing the above results in this:

![highlight2](https://cloud.githubusercontent.com/assets/2193314/11248196/ad1667fe-8dd4-11e5-989b-0fe74bb599d1.png)

**Comment by joaomoreno** [comment]
Thanks!

**Comment by Tyriar** [comment]
:+1:
