### ISSUE TITLE
Types Defined From a Referenced index.d.ts is not Available Unless index.d.ts is Opened

### ISSUE THREAD

**Issue by nusantara-cloud** [Microsoft/vscode#66008]
- VSCode Version: 1.30.1
- OS Version: 4.18.16-arch1-1-ARCH

I have a fullstack codebase with frontend and backend code on it.
The structure looks like this:

```
/src/index.d.ts // /src is where NodeJS code lives
/browser-js-src/src/index.d.ts  // /browser-js-src is where frontend code lives
```

I have global type definitions defined on /src/index.d.ts. And then I referenced it from /browser-js-src/src/index.d.ts like this:
```
/// <reference path="../../src/index.d.ts" />

```

What is strange is that when editing .ts files under /browser-js-src/ directory, type defined under /src/index.d.ts are not recognized (i.e. underlined red), unless the file /browser-js-src/index.d.ts is opened as one of the tabs on the editor. 

Steps to Reproduce:

1. Create a project root directory, referenced as /
2. Created a backend type definition file, /src/index.d.ts
3. Create frontend type definition file, /browser-js-src/index.d.ts
4. Reference backend type definition from frontend's, through /// <reference path="../../src/index.d.ts" />
5. Try to use type defined on backend definition from frontend directory (i.e. from /browser-js-src/src/test.ts)
6. Notice that the type is undefined
7. Open frontend type definition file /browser-js-jsrc/src/index.ts, try step (5) above again and notice that the type is now defined!

Without /browser-js-src/src/index.d.ts opened on any tab:
![image](https://user-images.githubusercontent.com/32732766/50674689-273d4900-101b-11e9-8591-5fa6a5e96439.png)

With /browser-js-src/src/index.d.ts opened in a tab:
![image](https://user-images.githubusercontent.com/32732766/50674706-420fbd80-101b-11e9-8bc9-afed436c4a8a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share a small example project. I tried setting this up based on your instructions but the instructions are not complete enough to reproduce this issue. As small example project will be much quicker in investigate

**Comment by nusantara-cloud** [comment]
@mjbvz 
Hi matt, I'm attaching a small project to reproduce the issue.

Steps to reproduce:
1. Untar the project ```tar xfz sample.tar.gz```
[sample.tar.gz](https://github.com/Microsoft/vscode/files/2981506/sample.tar.gz)

2. Open the project using vs code ```code app_dynamichosttemplate```

3. Open *only* browser-js-src/src/landing-app/main.ts

4. Notice the type *Category* is not defined
![image](https://user-images.githubusercontent.com/32732766/54579719-633b5400-4a37-11e9-8d04-d1690e619419.png)

5. Now open browser-js-src/src/index.d.ts

6. Notice now the type *Category* is defined fine
![image](https://user-images.githubusercontent.com/32732766/54579846-f6748980-4a37-11e9-8693-1a780d7e1289.png)

**Comment by mjbvz** [comment]
Thanks. It looks like `main` is not actually part of any `tsconfig` project. You can use the `TypeScript: Go to file configuration` command to check this. This means that when you open that file, only that single file is loaded by typescript intellisense. Manually opening the `index.d.ts` then causes it be loaded into the global scope as well which properly resolves the type

To make sure that you get proper intellisense, uake sure that the `main` file under `browser-js` and the `index.d.ts` are in the same tsconfig project. Then when you open `main`, the other files in the project will also be loaded

**Comment by nusantara-cloud** [comment]
Thanks a bunch, Matt @mjbvz 

Creating a new tsconfig.json file under browser-js-src/ folder solves the issue! :)
Really appreciate your help!
