### ISSUE TITLE
How to control the underline range of the jump definition

### ISSUE THREAD

**Issue by paysonTsung** [Microsoft/vscode#66006]
My plugin uses the jump definition API     languages.registerDefinitionProvider 
But I don't know how to control the underline range of the jump definition...

Below is the diagram
I want the underline to cover the entire string...

![image](https://user-images.githubusercontent.com/22448934/50673170-4934cc80-1017-11e9-997a-c75e7bba8e8c.png)

**Comment by egamma** [comment]
@paysonTsung Your DefinitionProvider can control the selected range by returning a DefinitionLink, pls see https://github.com/Microsoft/vscode/blob/d657d0c1366237f7694f8a2ca6bc8ae6b1303023/src/vs/vscode.d.ts#L2241
