### ISSUE TITLE
suddenly any command relate to typescript is missing

### ISSUE THREAD

**Issue by mhamri** [Microsoft/vscode#66003]
- VSCode Version:
- OS Version:

Steps to Reproduce:
i don't know what happened, i'm in an angular project and suddenly the typescript isn't a recognize command. usually i used it to restart typescript server. i uninstalled the vscode, deleted the .vscode folder under the user, and installed again, but still same, i don't know what is broken
![image](https://user-images.githubusercontent.com/8991783/50671329-310b8000-100c-11e9-82a5-daba9b65b92f.png)

Does this issue occur when all extensions are disabled?: Yes/No
yes

i'm on latest version

**Comment by mjbvz** [comment]
The typescript commands only show up if you are in a javascript or typescript file. Try opening one and then running the command
