### ISSUE TITLE
With zh-cn locale, C/C++ Go to Definition replaces the source document with the target contents

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#66004]
- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Use zh-cn in locale.json with the Simplified Chinese language back (also the C/C++ extension).
2. Edit a C/C++ file, and use Ctrl+Click (go to definition) on some target that exists in a different file.

Bug: The user at https://github.com/Microsoft/vscode-cpptools/issues/2980 reports that the contents of the file are overwritten by the target file's contents. I'm not able to repro the bug and our C/C++ extensions just sends back a list of go to definition targets, so I don't believe we could possibly be the cause. The only scenario where we send VS Code edits is when a format request is made.

Does this issue occur when all extensions are disabled?: No -- but we don't believe the C/C++ extension is the cause.

**Comment by egamma** [comment]
@sean-mcmanus the reporter states in this comment https://github.com/Microsoft/vscode-cpptools/issues/2980#issuecomment-451338777

>Go to Definition with Python("locale":"zh-cn") is normal.But C/C++ extension is not.

Since it works fine for Python and not for C++, then I don't think it is a VS Code issue. 

I've added some questions to the original issue that should help us to narrow things down.

**Comment by sean-mcmanus** [comment]
Thanks, your follow up questions sound good to me.

**Comment by sean-mcmanus** [comment]
User stopped communicating. Hopefully, they resolved their issue. We haven't received other reports like this.
