### ISSUE TITLE
ConPty Insiders Cursor Flashing

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#66001]
![here](https://i.imgur.com/rfZPMCL.gif)

**Comment by Astrantia** [comment]
@Tyriar

**Comment by Tyriar** [comment]
This is a bug in conpty using powershell on Windows 1809, it's fixed on Windows Insiders... I'm considering switching the default back because of this and the performance issues.

**Comment by usernamehw** [comment]
Not sure where to put it but Cmder in Insiders is unusable. CPU 100%

![screenshot 22](https://user-images.githubusercontent.com/9638156/50670994-16bbad00-0fe0-11e9-9b9c-68f16cbb8f9b.png)

Open and kill terminal a couple of times => always repro for me.


> VS Code version: Code - Insiders 1.31.0-insider (7805023eaa46db45d3c24a4c38c0d07c087cf1b3, 2019-01-03T06:20:50.629Z)
OS version: Windows_NT x64 10.0.17763

Using a setting helps:

```json
"terminal.integrated.windowsEnableConpty": false,
```

**Comment by Tyriar** [comment]
Just disabled it by default, it's opt in now. The kill problem is probably my bad and I've definitely noticed it as well.

**Comment by Astrantia** [comment]
@Tyriar So basically conpty which was supposed to fix winpty before new Windows Insiders landed faces an issue with 1809 again and needs Insiders too?

**Comment by Tyriar** [comment]
@Astrantia Windows 10 is released every 6 months, these weren't considered critical enough to make it in when I surfaced them earlier. It's one of the largest code bases in the world so I can understand the precautions.

**Comment by Tyriar** [comment]
The fix here is to disable conpty by default in 1809 and enable in the current Windows Insiders, merging into https://github.com/Microsoft/vscode/issues/66158
