### ISSUE TITLE
菜单明明可以通过上移进行显示，但它竟然缩小了！

### ISSUE THREAD

**Issue by yuzexun** [Microsoft/vscode#66009]
Issue Type: <b>Bug</b>

打开一个.cpp文件，我在编辑区上面点击右键弹出菜单，若是在屏幕中间点击，可以完整显示16个菜单选项，但我鼠标再往下移，然后右键弹出菜单，就会发现，越往下移，菜单项就会显示的越来越少，一直会跟随鼠标点击的位置，但菜单项显示不全。
这个显示得下应该自动调整吧，这样的菜单太难使用了。

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|-psn_0_167977|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-snippets|Ycl|0.1.2
android-dev-ext|ade|0.6.2
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
xml|Dot|2.4.0
eppz-code|epp|1.2.41
csharpextensions|jch|1.3.0
webpack|jer|2.1.0
svn-scm|joh|1.47.0
docomment|k--|0.1.2
luaide|kan|0.7.5
node-module-intellisense|lei|1.5.0
cpp-symbols|mir|0.0.1
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
debugger-for-chrome|msj|4.11.1
gradle-language|nac|0.2.3
java|red|0.36.0
LiveServer|rit|5.3.1
shader|sle|1.1.4
vscode-hexdump|sle|1.7.2
factorio-lua-api-autocomplete|svi|0.6.0
unity-tools|Tob|1.0.5
unity-debug|Uni|2.6.6
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1

</details>

**Comment by egamma** [comment]
Please report issues in english.
