### ISSUE TITLE
Some problems of personal habits

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#6601]
- VSCode Version:
- OS Version:1.1

Steps to Reproduce:

1. Is it wrong to be here?

![22](https://cloud.githubusercontent.com/assets/10474968/15446429/51b9f496-1f53-11e6-87f0-a1e8bcf2ce67.png)

2.  Can you add an item to the top that you can manage to open the file?

![55](https://cloud.githubusercontent.com/assets/10474968/15446430/59e8720a-1f53-11e6-8a34-cdfe88db1e5d.png)

3. If you can increase the settings will be left column can be hidden away?

![66](https://cloud.githubusercontent.com/assets/10474968/15446431/61c18958-1f53-11e6-9a1e-6db6d67931f9.png)

Vscode is a good editor, but I have a habit of being forced to correct it.
I like some of ui.'s sublime
Hope vscode can also have these UI

**Comment by weinand** [comment]
@lifetin sorry, but I don't understand your first problem because I cannot read your language. Please explain in English.

Your second problem: are you asking for 'tabs'?

Third problem: no, there is no way to hide the action bar.

**Comment by Tyriar** [comment]
@weinand 

1. Pretty sure this is about the (S) accelerators where it should be (Y) and (N)
2. Tabs https://github.com/Microsoft/vscode/issues/224
3. Hide activity bar https://github.com/Microsoft/vscode/issues/1105

**Comment by bpasero** [comment]
Closing as duplicates, thanks @Tyriar .

**Comment by Tyriar** [comment]
@bpasero is the 1st point a duplicate too?
