### ISSUE TITLE
VSCode  doesnt respect "files.watcherExclude" or "exclude"

### ISSUE THREAD

**Issue by msqaddura** [Microsoft/vscode#66017]
Issue Type: <b>Bug</b>

Tested on this repo:
https://github.com/itslenny/scaffs
These files:
https://github.com/itslenny/scaffs/tree/master/test/data/scaffolds/Example

Knowing that:
1) the scaffold files have to be *.ts so changing file extension wont help

Expected Result:
after putting in settings.json "files.watcherExclude" to exclude this folder and also in tsconfig.json "exclude" the folder,  VSCode's Problem Viewer should not show [ts] errors.

Real Result:
VSCode shows that these files are erronous

settings.json (please note, i tried so many variances until landed ignore whole folder)
![image](https://user-images.githubusercontent.com/11808840/50680661-2c959600-1011-11e9-9121-3be494e551b9.png)

tsconfig.json (as well added the whole folder)
![image](https://user-images.githubusercontent.com/11808840/50680699-53ec6300-1011-11e9-859c-0c9f6733f79b.png)

errors (though VSCode should not look into them)
![image](https://user-images.githubusercontent.com/11808840/50680729-6ebed780-1011-11e9-886d-8f66016c9f4e.png)

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.18.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 976)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|5.73GB (0.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
I think this is related to ts, not the watcher

**Comment by msqaddura** [comment]
yes it does seem so, yet  isnt it supposed at least via tsconfig>exclude to understand that this file is not to be validated? and actually linting errors disappeared after i excluded the files in ts.config.json so there must be a charm

Otherwise, how could I solve the problem, some IDEs (who had the same issue with [ts]) offer the "Mark as Text" functionality, but `I <3 VSCode` and the point is not to compare the IDEs but rather to fix this issue, and this one case is really brutal :D

**Comment by mjbvz** [comment]
Yes, vscode's exclude settings are not related to typescript validation. The `tsconfig` exclude setting just determine the TypeScript project, it will also not disable validation for TS files you open

A few options:

- Disable all TS validation by setting `"typescript.validate.enable": false` 

- Get TS to support a `@no-check` flag: https://github.com/Microsoft/TypeScript/issues/26887

- Use file associations to tell VS Code not to treat these files as TS (won't parse these template files or even colorize them correctly anyways so they really aren't TS)
 
    For this, try setting:

    ```
    "files.associations": {
        "**/path/to/templates/**/*.ts": "plaintext"
    }
    ```

    https://github.com/Microsoft/vscode/issues/12805 Would help with this

**Comment by ghiscoding** [comment]
> * Disable all TS validation by setting `"typescript.validate.enable": false`
> * Get TS to support a `@no-check` flag in files: [microsoft/TypeScript#26887](https://github.com/microsoft/TypeScript/issues/26887)

These 2 options work but are there any better option to exclude certain folder? I want to exclude code validation for all my `__tests__` (Jest Unit Test) and I could go and add `// @ts-nocheck` on top of each file but I find that counter productive since I have hundred of unit test files. If `"typescript.validate.enable"` could exclude certain folders that would be the best option. 

@msqaddura have you found a better alternative?

**Comment by geekley** [comment]
@mjbvz the 3 suggested solutions don't really help with generated files, which I can't edit
I'd like to hide `src-gen/**` error squiggles without having to disable tokenization or validation (sometimes I need to dig into the generated code for debugging)
I think vscode should have a way in settings to ignore errors/warnings/info squiggles generically (regardless of language) while keeping the tokenization. We should be able to hide all squiggles by path pattern and also by error codes.
Do you guys know of some feature request for this that I can upvote?

**Comment by EliasTouil** [comment]
I'm having the same issue with generated files

**Comment by piscopancer** [comment]
any updates on that?
