### ISSUE TITLE
Syntax colouring fail on PHP v7.3 HEREDOC / NOWDOC termination

### ISSUE THREAD

**Issue by Kroc** [Microsoft/vscode#66018]
Issue Type: <b>Bug</b>

Since PHP v7.3 the HERE/NOWDOC syntax allows indentation of the terminator, and the semicolon is no longer required, even allowing for other symbols (comma in the case of docstrings in arrays).

The following code no longer colours correctly

```php
<?php
    echo <<<NOWDOC
The quick brown fox
    NOWDOC
    ;
?>
```

VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:17:20.719Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
spellright|ban|3.0.22
vscode-icontheme-nomo-dark|be5|1.3.6
unique-lines|bib|1.0.0
markdown-preview-github-styles|bie|0.1.4
insert-unicode|bru|0.2.1
better-toml|bun|0.3.2
gitignore|cod|0.6.0
EditorConfig|Edi|0.12.6
php-intellisense|fel|2.3.10
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.1.1
php-docblocker|nei|1.7.0
gitconfig|sid|2.0.0
vscode-hexdump|sle|1.7.2
ignore-gitignore|stu|1.0.1
insert-special-symbol|swi|1.3.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This issue was moved to atom/language-php#346
