### ISSUE TITLE
python pyxb generated binding hangs VS code

### ISSUE THREAD

**Issue by igvls** [Microsoft/vscode#66011]
- VSCode Version: 1.30.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. I have a pyxb library generated XDS binding which is a 32 MB file.
2. I am trying to package and import that file into another file as module. The VS code starts to slow down and total system hangs (or) sometime crashes.
4. My assumption is VS code cannot handle python file greater than 10 MB with multiple function.

![screenshot 8](https://user-images.githubusercontent.com/16795479/50676801-628c4780-101c-11e9-8bfc-c415ff17105e.png)

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment]
This looks like an issue with the Python extension, pls report the issue against this repository.
