### ISSUE TITLE
VScode python 3 pylint: I can import X file in A but not B

### ISSUE THREAD

**Issue by elieobeid7** [Microsoft/vscode#66028]
I'm using the latest version of VScode, using pylint and python 3. I'm using I'm on Ubuntu 16.04 and virtualenv. I can import all python and pip packages correctly, I only face the error when working with files I created.

I have 3 files, all are next to each other sitting in the same folder. `a.py`, `b.py` and `keys.py`, the latter contains nothing but keys as strings.

in `a.py`, I can do

`from keys import X`

But in `b.py` pylint doesn't let me do that, I get

`Unable to import 'keys' [E0401]`

 I can only do

`from .keys import X`

Which is wrong but I mean that would remove the error above.  I asked this question on stackoverflow but it might be a bug, just might so I had to ask it here.

**Comment by mjbvz** [comment]
Please file this issueagainst the python extension
