### ISSUE TITLE
Pressing AltGr in the integrated terminal inserts the string AltGraph

### ISSUE THREAD

**Issue by Endyl** [Microsoft/vscode#66026]
Issue Type: <b>Bug</b>

While typing in the integrated terminal, pressing AltGr inserts the string "AltGraph" on the command line.

VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:14:11.582Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz (24 x 1812)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|31.34GB (24.62GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|9.3.0
latex-workshop|Jam|5.19.0
plantuml|jeb|2.10.1
puppet-vscode|jpo|0.15.0
twig-language|mbl|0.4.3
twig-language-2|mbl|0.4.3
vscode-apache|mrm|1.1.1
python|ms-|2018.12.1
cpptools|ms-|0.20.1
vscode-docker|Pet|0.4.0
ungit-tab|rv1|0.0.9
rewrap|stk|1.9.1

</details>

**Comment by Tyriar** [comment]
Duplicate #65949, will be fixed in the next build 😃
