### ISSUE TITLE
cannot connect to extension marketplace

### ISSUE THREAD

**Issue by harishthakur04** [Microsoft/vscode#66024]
Issue Type: <b>Bug</b>

I am unable to connect to extension marketplace.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-7310 APU with AMD Radeon R4 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.46GB (0.71GB free)|
|Process Argv|--open-url -- vscode:extension/ritwickdey.LiveServer|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by pdaddy26** [comment]
I'm having the same issue where the progress bar under EXTENSIONS just continuously run nothing appears ever .....

**Comment by egamma** [comment]
@harishthakur04 have you checked that you are not behind a proxy?
This is the documentation for how access the marketplace when you are behind a proxy https://code.visualstudio.com/docs/setup/network

**Comment by harishthakur04** [comment]
Thanks for the help.I was behind the proxy then.Now its working properly.
