### ISSUE TITLE
Add scroll bar to integrated terminal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6602]
On Mac I am not getting scrollbars when the content overflows.

**Comment by Tyriar** [comment]
Known issue but valid, not sure scrollbars are going to happen unless we fork term.js.

**Comment by Tyriar** [comment]
Forking term.js would also be necessary if we wanted to do any improvements to the UX inside the terminal. For example improving the selection experience (related to this), adding links or something to terminal for tighter integration with editor (#1037), making the cursor blink without breaking selection, etc.

**Comment by bastienJS** [comment]
I use the integrated terminal only for doing "ng build" and getting an error message about what failed to build. But I am never able to read the cause of the failed build because I can not scroll up. Not every error is in the error windows. Sometimes error appear only at build process.

Thus if you want to justify the existance of the integrated terminal it really needs scrollbars or I have to the CMD.

**Comment by Tyriar** [comment]
@bastienJS you should still be able to scroll using the mouse wheel and <kbd>ctrl</kbd>+<kbd>shift</kbd>+arrows/page up/page down.

**Comment by Tyriar** [comment]
This needs to be tackled upstream first at https://github.com/sourcelair/xterm.js/issues/77

**Comment by gertcuykens** [comment]
OSX 0.11.6 / vscode 1.3.1
- fn + up down arrow doesn't work in terminal it gives a ~ character instead.
- scroll speed per line results into a much faster and choppy scroll then in a normal vscode editor window, try to make sure scroll speed of all different windows are the same in vscode if technically possible.

**Comment by gertcuykens** [comment]
Plan B: Disable mouse scroll completely to prevent accidental scrolling and introduce a new button that opens a new editor tab with a copy of the console buffer outbut. As a bonus you can then keep that output and use it as a copy paste clip board.
![image](https://cloud.githubusercontent.com/assets/863731/17412364/a0c1ef1c-5a7c-11e6-9310-30854a377de1.png)

**Comment by Tyriar** [comment]
@gertcuykens the WIP PR is out for the scroll bar https://github.com/sourcelair/xterm.js/pull/218, it supports mouse wheel events that scroll by pixel, line and page. It's very smooth based on my testing so far.

**Comment by pierznj** [comment]
Scrollbar for the integrated terminal would be awesome.

**Comment by emartinpi** [comment]
I just updated Code to version 1.5 and the scrolling in integrated terminal doesn't work with my mouse wheel. The only way i can scroll is <kbd>cmd</kbd>+<kbd>arrows</kbd>

**Comment by Tyriar** [comment]
@emartinpi are you using oh-my-zsh? The scroll bar should be visible and working whenever application keypad mode is disabled.

**Comment by emartinpi** [comment]
@Tyriar yes, i'm using oh-my-zsh. Application keypad mode was enabled so I disabled it from terminal menu, reset VCode but nothing changed in integrated terminal, the same behavior keeps going

**Comment by Tyriar** [comment]
@emartinpi I suspect this is the root cause of the issue https://github.com/sourcelair/xterm.js/issues/151

**Comment by jcarter** [comment]
@emartinpi this worked for me - https://github.com/Microsoft/vscode/issues/7817#issuecomment-229069151

**Comment by emartinpi** [comment]
Thanks @jcarter It worked for me as well, but I suppose this workaround may break some key bindings...
@Tyriar Will there be a fix for this issue?

**Comment by Tyriar** [comment]
@emartinpi I was hoping someone from the community would be able to chip in on https://github.com/sourcelair/xterm.js/issues/151, I don't use oh-my-zsh personally and won't have time to look at it any time soon.
