### ISSUE TITLE
Can't activate any extension.

### ISSUE THREAD

**Issue by likecreep** [Microsoft/vscode#66020]
Issue Type: <b>Bug</b>

Suddenly I can't use any extensions and when I try to use extensions, the workbench would show "activating extensions" but after that I still can't use any extensions.

The developer tools shows "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303"

How can I fix this? Thx.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

**Comment by likecreep** [comment]
@egamma Hi, thanks for your time. I tried disabled all extensions and reinstall all of them one by one. And I found this problem was caused by one particular extension. After I uninstalling it, now everything works fine. I'll close this issue. Thank you!

**Comment by egamma** [comment]
@likecreep what was the extension that caused this problem?

**Comment by likecreep** [comment]
@egamma The extension is SVG Viewer. I just tried installing it again, and every extension can't be activated again. After uninstalling it, everything works fine.
