### ISSUE TITLE
How to know user wide code installation running or System wide installation

### ISSUE THREAD

**Issue by shanalikhan** [microsoft/vscode#66029]
Is there any way to check if the code is running a user wide or system wide mode via API.

**Comment by joaomoreno** [comment]
There isn't any way of knowing since it is an installation-time feature. Can I ask: what is the goal you are trying to achieve?

**Comment by joaomoreno** [comment]
> Settings sync needs to know in order to setup and get `User` folder and `code` binary for reading / writing the settings and extensions respectively.

You shouldn't need to know about user/system at all. What you need are the paths to two directories: `user-data-dir` and `extensions-dir`.

@jrieken What do you think about exposing them via API?

@sandy081 Any objections?

**Comment by shanalikhan** [comment]
Similar issue opened that also focused on Settings Sync years ago.

https://github.com/Microsoft/vscode/issues/2741

This issue needs to be solved on priority because whenever User Based Installation becomes default way of installing Code, Settings Sync wont work.

**Comment by sandy081** [comment]
Is it safe/ok to assume the parent of the extension dir as `extensions-dir`?

**Comment by joaomoreno** [comment]
@sandy081 Not in extension development scenarios.

**Comment by shanalikhan** [comment]
@joaomoreno whats the update, when you do think it will be fixed ?

**Comment by joaomoreno** [comment]
@shanalikhan Notice this is a feature request, not a bug.

@jrieken What do you think about https://github.com/Microsoft/vscode/issues/66029#issuecomment-451886004?

**Comment by jrieken** [comment]
I think it's dangerous - we don't really want extensions to copy binaries from the extensions folder, right?

**Comment by joaomoreno** [comment]
@jrieken They are already doing it, unfortunately. But the way they get there is through path magic.

**Comment by shanalikhan** [comment]
Settings Sync unable to work with code OSS versions due to this reason that `user-data-dir` and `extensions-dir`. These is no way to get that.

Please discuss this ticket in your upcoming sprint/release planning sessions.

**Comment by gandarez** [comment]
There's already a function to detect if `portable` is set but it seems that's not working because `process.env['VSCODE_PORTABLE']` never been different from `undefined`

https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js#L239
