### ISSUE TITLE
Trigger suggestion shortcut on Mac not working

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#66031]
From here https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

`⌃Space` Trigger suggestion

But `⌃Space` on Mac is for switch keyboard language. It doesn't trigger suggestion, it switches keaboards.

And even after I've changed Mac's keyboard layout shortcut, `⌃Space` doesn't work either

**Comment by egamma** [comment]
@wzup <kbd>Ctrl+Space</kbd> works for me.

Can you please try the recommendations described in this document to address the issue https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-mac-keybindings
