### ISSUE TITLE
Run Script in Active Terminal (powershell, bash, python...)

### ISSUE THREAD

**Issue by harpenden** [Microsoft/vscode#66032]
**Version:** 1.30.1 (user setup)
**OS:** Windows_NT x64 10.0.17134

It would be good to have an option to run whole script (not a script file) in active terminal. Similar to `Run Selection` `f8` for Powershell or `Run Selection/Line in Python Terminal` `Shift + Enter` for Python scripts but without selecting a code.

- It takes time to select whole script and run the selection.
- Running a file from terminal is different, it doesn't allow me to continue to work in the terminal session(access variables etc.) once I run the script.

**Comment by Tyriar** [comment]
You can hit ctrl+a before you run it to do this, you could also build a command to do it as part of the command via an extension.
