### ISSUE TITLE
Textarea in Webview loses caret/focus indication

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#66038]
Issue Type: <b>Bug</b>

I encounter this regularly on Windows when using the GH PR extension.

1) Open a text editor
2) Open a PR overview page
3) Set the cursor to leave a comment (this usually shows the caret)
4) Switch to the text editor
5) Switch back to the PR overview page
6) Set  the cursor to leave a comment 
-> No caret, the text insert position however is tracked correctly

VS Code version: Code - Insiders 1.31.0-insider (ed5363e8659d142fc170cb978389e34102135e8f, 2019-01-02T17:25:53.371Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
solargraph|cas|0.19.1
regex|chr|0.2.0
gitlens|eam|9.3.0
remotehub|eam|0.2.0
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
vscode-pull-request-github|Git|0.3.2
mdmath|goe|2.3.7
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.5.0
mssql|ms-|1.4.0
python|ms-|2018.12.1
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
Go|ms-|0.8.0
vscode-docker|Pet|0.4.0
material-icon-theme|PKi|3.6.2
ruby|reb|0.21.0
notification-tester|svi|2.0.4
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
I believe this falls under #48604

The PR extension does not use `retainContextWhileHidden` but they could implement a custom solution using webview state. For webviews that use `retainContextWhileHidden` , VS Code could track which element is focused and restore the focus to it
