### ISSUE TITLE
[Feature Request] Add multiline description support in user snippets

### ISSUE THREAD

**Issue by zombie110year** [Microsoft/vscode#66036]
While creating a user snippet, the rule must be like this:

```json
"example": {
	"prefix": "example",
	"body": [
		"line 1",
		"line 2"
	],
	"description": "A single line description"
}
```

If I want to show a lot of description, I must write a huge string which includes many escape characters like this:

```json
"toctree": {
	"prefix": ".. toctree::",
	"body": [
		".. toctree::",
		"$0"
	],
	"description": "A toctree item, have these options:\n\t:maxdepth: para\n\t:caption: para
\n\t:numbered:\n\t:titlesonly:\n\t:glob:\n\t:reversed:\n\t:hidden:\n\t:includehidden:",
	"scope": "text.restructuredtext"
},
```

It maybe a good idea that `description` option receive a list value, like the `body`:

```json
"toctree": {
	"prefix": ".. toctree::",
	"body": [
		".. toctree::",
		"$0"
	],
	"description": [
		"A toctree item, have these options:",
		":maxdepth: para",
		":caption: para",
		":numbered:",
		":titlesonly:",
		":glob:",
		":reversed:",
		":hidden:",
		":includehidden:"
	],
	"scope": "text.restructuredtext"
},
```

**Comment by jamesgeorge007** [comment]
@jrieken Can you guide me on resolving this issue?

**Comment by jrieken** [comment]
sure, checkout 

* https://github.com/Microsoft/vscode/blob/3a0a2e90c740b6f4207f0aaa95d5bcae9d434eb9/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L123, and
* https://github.com/Microsoft/vscode/blob/3a0a2e90c740b6f4207f0aaa95d5bcae9d434eb9/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L227

**Comment by jamesgeorge007** [comment]
- [vscode/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts](https://github.com/Microsoft/vscode/blob/3a0a2e90c740b6f4207f0aaa95d5bcae9d434eb9/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L123)
The type of description field is to be made as `string[]`
