### ISSUE TITLE
Provide GlobalStoragePath for large workspace independent extension data

### ISSUE THREAD

**Issue by tboby** [Microsoft/vscode#66030]
This feature request is related to #37137 and #22557, but is more focused on global state.

Some extensions, especially language servers, need global data that cannot be bundled in the extension. There are two main reason I know of:
- Allowing server updates independently of extension updates. E.g. ms-vscode.csharp and omnisharp I believe
- Caching of global data for performance

The current options for storing extension data are:
1. `extensionPath`, which is wiped on extension update
2. `storagePath`, which is not global
3. `globalState`, which is not appropriate for file storage
4. System specific user data storage location, e.g. `%appdata%` and equivalent.

Currently, 4 is the only workable solution. However:
1. It hides the data from the user (not stored in vscode space)
2. It can't be removed by vscode on extension uninstallation (although I'm not sure vscode does this for `storagePath`)
3. It adds fragility (reliance on extension author handling of OS-specific user file storage).
4. It's effectively undocumented

**The addition of a `globalStoragePath`, an extra `workspaceStorage` folder with global scope, would resolve all of above issues**

My context for the requirement:

[My language server extension](https://marketplace.visualstudio.com/items?itemName=tboby.cwtools-vscode) creates 200-300MB of serialized binary data from a system library which is cached to speed up subsequent activation. Creating this data is time-consuming (1-3 minutes) but it is global for the language. The library may not be available on future runs, so loss of the cache is undesirable (hence `extensionPath` wiping on update being a problem). 
My extension is cross-platform, but I have little experience of linux or OSX user data, so would be reluctant to manually implement a cross-platform user file management layer.

**Comment by bpasero** [comment]
I think this is already in proposed: https://github.com/Microsoft/vscode/blob/28e7467/src/vs/vscode.proposed.d.ts#L1123

**Comment by jrieken** [comment]
Yes, @sandy081 added this via https://github.com/Microsoft/vscode/issues/23251

**Comment by sandy081** [comment]
Even though the `globalStoragePath` is added to proposed api in #23251, It has changed a lot in terms of approach and design which I suppose this API is not needed for #23251. Hence will use this issue to drive it to finalised API.

**Comment by jrieken** [comment]
@sandy081 API looks fine to me

**Comment by sandy081** [comment]
Verify the newly introduce property in `vscode.ExtensionContext.globalStoragePath` works as expected.
