### ISSUE TITLE
Issue reporter no longer showing related issues

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#66037]
Issue Type: <b>Bug</b>

Unable to see the list of related issues under the title in the issue reporter:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/35271042/50701258-10d6c380-1002-11e9-9640-ed2baac5e85e.png">

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
Looking at the network requests in that window, they show as "Pending" for a while and then eventually return 502 Bad Gateway. @chrmarti Has anything about the duplicate candidates endpoint changed? I'm still using https://vscode-probot.westus.cloudapp.azure.com:7890/duplicate_candidates

**Comment by chrmarti** [comment]
It has started working again after restarting the similarity container. (It looked like a lot of old requests were stuck either in the Traefik container or the similarity container. Some very old request were listed as complete in the Traefik logs after the similarity container restarted.)

**Comment by chrmarti** [comment]
Closing as obsolete.
