### ISSUE TITLE
For Clojure, auto select identifiers allowed in language

### ISSUE THREAD

**Issue by 0xc0** [Microsoft/vscode#66043]
- VSCode Version: 1.30.1
- OS Version: macOS Mojave

Steps to Reproduce:

1. Clojure file: `(defn is-square? [x] (let [y (Math/sqrt x)] (= (- y (Math/floor y)) 0.0)))`
2. Put text cursor in or double click on `square`
3. `is-square?` should be highlighted, not just `square`

According to https://clojure.org/reference/reader, allowed characters within an identifier are `*+!-_'?<>=`

**Comment by egamma** [comment]
@0xc0 this behaviour needs to be defined by the extension that provides Clojure support (I cannot infer which extension you are using from the information you have provided). Therefore please provide the issue against this extension.

**Comment by 0xc0** [comment]
@egamma I am not using any extensions other than the one shipped with VS Code. https://github.com/Microsoft/vscode/tree/master/extensions/clojure

**Comment by egamma** [comment]
@0xc0 the default behaviour in VS Code is to highlight the word. To make this language aware requires an extension that understands Clojure. 

There are several Clojure extensions in the marketplace and I suggest that you try them out.
