### ISSUE TITLE
Bash on windows crashs on integrated terminal

### ISSUE THREAD

**Issue by VIMGAS** [Microsoft/vscode#66049]
- VSCode Version:
1.31.0-insider
bae6c84d46cd85c911db7e166a74e698a54c8644
x64

- OS Version: Windows 10 1809

Steps to Reproduce:

1. Configured bash to be vscode's integrated terminal
![image](https://user-images.githubusercontent.com/20145874/50705436-f58ba880-1041-11e9-8dc1-6ec20469855f.png)

2. Tried to open the integrated terminal
![image](https://user-images.githubusercontent.com/20145874/50705462-118f4a00-1042-11e9-88fa-01621032c15b.png)

I am using Git for Windows version Git-2.20.1-64-bit.

After trying to make it run as integrated terminal and getting the crash, Git Bash does not load again...

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Does that path run in a regular cmd.exe window?

**Comment by VIMGAS** [comment]
@Tyriar It does, but I already solved the problem... Turns out bash.exe was configured to run as administrator and it caused the bug. Everuthing is working fine after disabling it.
