### ISSUE TITLE
Support filesystem paths using ssh://

### ISSUE THREAD

**Issue by WSLUser** [Microsoft/vscode#66046]
- VSCode Version: 1.31 Insiders
- OS Version: Win 7

Steps to Reproduce:

1. Mount a workspace via ssh using the [SSHFS](https://github.com/SchoofsKelvin/vscode-sshfs) extension.
2. Attempt to initialize and watch it do nothing.

Does this issue occur when all extensions are disabled?: 

When all other extensions are disabled this is still an issue.

I believe the issue is that the SSHFS extension makes use of the FileSystemProvider API to allow workspaces to be mounted using ssh:// that appear as \ to git and thus fails to initialize. Since this API was created, Git and other extensions should be able to recognize when a local workspace created using SSH. Since this affects other extensions such as Python (when attempting to run debug or tests), I believe this is a VS Code actionable to globally allow all extensions to register this file path.

**Comment by egamma** [comment]
Please file the issue against the SSH extension.

**Comment by DarthSpock** [comment]
Per https://github.com/SchoofsKelvin/vscode-sshfs/issues/31 VSCode needs to take action because there's nothing they can do about it.

**Comment by DarthSpock** [comment]
Since builtin git is managed by VS Code, this issue is for the git extension to be updated.

**Comment by DarthSpock** [comment]
Any update on when this will be addressed?

**Comment by WSLUser** [comment]
@egamma I found https://github.com/Microsoft/vscode/issues/68808 has the on-deck tag on it. I would hope this means this issue will also get addressed.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
