### ISSUE TITLE
Broken PHP syntax inside <script> tags

### ISSUE THREAD

**Issue by FrancoCab10** [Microsoft/vscode#66048]
**This happened after the 1.30 update, still happening in 1.30.1.**
As the title says, the syntax highlight breaks when using \<\?php \?\> or \<\?= \?\> tags inside a <script> html tag. Screenshot bellow.

**VSCode:**
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

**You can try it out:**
1- Create a .php file like index.php
2- Open the file with vscode
3- Paste this code inside the file:

\<?php
    $number = 5;
\?>

\<h1>\<?= $number \?>\</h1>
\<p>\<?= site_url(\'some/random/url\') \?>\</p>

\<script>
var number = \<?= $number \?>;
var url = \'\<?= site_url('some/random/url') \?>\';
console.log(number, url);
\</script>

**Screenshot:**

![vscode](https://user-images.githubusercontent.com/46230292/50704810-75f8dc00-1037-11e9-99a7-a9f9ae8c79e6.png)

**Comment by roblourens** [comment]
Thanks for the detailed issue, this is actually fixed in Insiders - https://github.com/Microsoft/vscode/issues/65649
