### ISSUE TITLE
Cannot change fonts

### ISSUE THREAD

**Issue by qiangshi1** [microsoft/vscode#66040]
Issue Type: <b>Bug</b>

As the title said，and my system is ubuntu16.04.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.31GB (0.45GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
What font are you trying to change?

**Comment by dattx0** [comment]
i have the same issue, my font is Consolas (vs code, Ubuntu 16.04.5), i changed 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback' to Consolas in font family setting, i could do this in previous versions

**Comment by qiangshi1** [comment]
> What font are you trying to change and what are you doing to do it?
Well my font family is {'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'}.I want to change it to {'Nimbus Mono L'}.But after I change the setting,it doesn't work.The font isn't changed.

**Comment by usersaurus** [comment]
I'm having the same issue with the last version of vscode stable in Ubuntu 19.04. Could it be related to be using the snap version? I just saw there was a bug with this version in the past.

**Comment by Tyriar** [comment]
Yes there was a problem with fontconfig and the snap package before, closing off assuming that's what this was.
