### ISSUE TITLE
Audio is not supported in webview

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vscode#66050]
I realize this is an unsupported feature as described in #54097.

Is this something an extension can rectify by shipping the appropriate codecs? 

Our extension has this issue here:
https://github.com/Microsoft/vscode-python/issues/3456

Not supporting audio gives us a missing feature as compared to using straight up jupyter.

**Comment by mjbvz** [comment]
Duplicate of #54097

We don't ship with ffmpeg so many common audio and video formats are not supported

**Comment by rchiodo** [comment]
@mjbvz I realize that you don't support this. I would like to know if there is a way for us to add that support in our extension.
