### ISSUE TITLE
Disable or remove "Open Changes" button if no changes to the file

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#66052]
- VSCode Version: 1.30.1
- OS Version: Windows

Steps to Reproduce:

1. Open a file without source control changes.
2. The "Open Changes" button is displayed and enabled on the editor title bar
3. Click the "Open Changes" button and nothing happens

Should we disable or remove the button if it will NOP?

**Comment by joaomoreno** [comment]
Unfortunately, this is not possible via API right now. Depends on https://github.com/Microsoft/vscode/issues/21131
