### ISSUE TITLE
Default line ending for shell scripts should be LF, not CRLF

### ISSUE THREAD

**Issue by scarolan** [Microsoft/vscode#66055]
This is highly annoying...I create a shell script in vscode on one machine, then try to clone the repo and edit on a freshly installed vscode on another machine.  Guess what - it switches my line ending to CRLF and breaks all shell scripts.

Please set the default to LF for bash scripts.  For sanity's sake.

**Comment by egamma** [comment]
@scarolan Are you creating and cloning the files across different platforms (e.g. Windows and OS X)? Have you checked how you configured git's line ending handling  `core.autocrlf` https://help.github.com/articles/dealing-with-line-endings/?

**Comment by scarolan** [comment]
You are 100% correct - it turns out git was the culprit.  Still, it would be nice to be able to force LF all the time, everywhere for certain file types (shell scripts).  I'm going to close this issue.
