### ISSUE TITLE
Stacks: Document changed command ids and how to get old behaviour back

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6605]
**Changed Commands**
* `workbench.action.focusFirstEditor` => `workbench.action.focusFirstEditorGroup`
* `workbench.action.focusLeftEditor` => `workbench.action.focusPreviousGroup`
* `workbench.action.focusRightEditor` => `workbench.action.focusNextGroup`
* `workbench.action.focusSecondEditor` => `workbench.action.focusSecondEditor`
* `workbench.action.focusThirdEditor` => `workbench.action.focusThirdEditorGroup`
* `workbench.action.moveActiveEditorLeft` => `workbench.action.moveActiveEditorGroupLeft`
* `workbench.action.moveActiveEditorRight` => `workbench.action.moveActiveEditorGroupRight`
* `workbench.action.openPreviousEditor` => `workbench.action.openPreviousEditorFromHistory`
* `workbench.files.action.addToWorkingFiles` => `workbench.action.pinEditor`
* `workbench.files.action.closeAllFiles` => `workbench.action.closeAllEditors`
* `workbench.files.action.closeFile` => `workbench.action.closeActiveEditor`
* `workbench.files.action.closeOtherFiles` => `workbench.action.closeOtherEditors`
* `workbench.files.action.focusWorkingFiles` => `workbench.files.action.focusOpenEditorsView`
* `workbench.files.action.openNextWorkingFile` => `workbench.action.nextEditor`
* `workbench.files.action.openPreviousWorkingFile` => `workbench.action.previousEditor`
* `workbench.files.action.reopenClosedFile` => `workbench.action.reopenClosedEditor`
* `workbench.files.action.workingFilesPicker` => `workbench.action.showAllEditors`
* `workbench.action.cycleEditor` => `workbench.action.navigateEditorGroups`

**New Commands**
* `workbench.action.unpinEditor`: turn an editor into preview
* `workbench.action.showEditorsInGroup`: show all editors of a group
* `workbench.action.clearEditorHistory`: clear navigation history and list of recently closed editors
* `workbench.action.closeEditorsInGroup`: close all editors of a group
* `workbench.action.closeEditorsInOtherGroups`: close editors in other groups
* `workbench.action.closeEditorsToTheLeft`: close editors to the left of the active one
* `workbench.action.closeEditorsToTheRight`: close editors to the right of the active one

**Keybindings for Old Behaviour:**
```json
{ "key": "ctrl+tab", "command": "workbench.action.openPreviousEditorFromHistory" },
{ "key": "ctrl+tab", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" },
{ "key": "cmd+w", "command": "workbench.action.closeEditorsInGroup" }
```

**Comment by cthedot** [comment]
Got so used to "Ctrl+Tab to navigate in entire editor history" I added the Keyboard Settings. But seems opening files this way does not add a new tab but replaces a tab? Any way to open a file in a new tab? Thanks!

**Comment by bpasero** [comment]
Yes, set `workbench.editor.enablePreviewFromQuickOpen: false`

**Comment by cthedot** [comment]
Ah, great thanks! ☺ 

Also for quickest than quicker reply 😏

**Comment by maritz** [comment]
Please never remove the "old" way. I tried going back to tabs.... it was painful.

**Comment by varungupta85** [comment]
Is there a way to also remove the tab bar on the top? I have gotten used to the old behavior where there was not tab bar on the top and started to like it. Much less clutter.

**Comment by maritz** [comment]
@varungupta85 

    "workbench.editor.showTabs": false

**Comment by varungupta85** [comment]
Great, thanks!
