### ISSUE TITLE
API: Prevent the webview tab from being replaced

### ISSUE THREAD

**Issue by agentcooper** [Microsoft/vscode#66051]
I didn't find any way to prevent the webview tab from being replaced.

Context: I'm developing an extension with a preview pane that you can interact with. The typical workflow is: open a file, interact with a preview, open a different file. If the user tries to open a different file while the preview is focused, the preview tab will be replaced.

I propose a new option on `WebviewPanelOptions`:

```js
vscode.window.createWebviewPanel(
  "preview",
  "Preview",
  { viewColumn: vscode.ViewColumn.Beside, preserveFocus: true },
  {
    /** Prevent the tab from being replaced */
    preventFromReplace: true
  },
);
```

What do you think?

**Comment by mjbvz** [comment]
I'm not in favor of supporting editors that can't be replaced since it makes the webview too different. Would placing the webview in a sidebar cover your use case, either #46585 or #43049. There's also this request for modal webviews: #47899

**Comment by agentcooper** [comment]
@mjbvz #46585 will definitely solve things for my case.

**Comment by mjbvz** [comment]
Thanks, please upvote #46585. I'm going to close this feature request  as out of scope since I do not think it something we would want to enable
