### ISSUE TITLE
Restarting to update VSC does not work ("Application did not start properly")

### ISSUE THREAD

**Issue by Proxxaaa** [Microsoft/vscode#66065]
Issue Type: <b>Bug</b>

1. Open up Visual Studio Code.
2. Wait until a prompt appears at the bottom right of the screen, prompting you to restart to install an update.
3. Click "Restart Now," attempting to install the update.
4. Visual Studio Code closes to restart and install the update as regular.
5. An error alert appears, saying "The application did not start properly," or something of the sort.
If you click "OK" on the alert, simply nothing happens. This same alert also seems to appear when I regularly close Visual Studio Code. 

EDIT: I wrote this issue with the knowledge that Visual Studio Code doesn't open again, but it seems to now be opening again. However, the prompt still keeps showing up and the same thing happens if you click "Restart Now." If I reload the window with all extensions disabled, the same result occurs with the same exact error code. I currently do not know of a way to see my version number to check if any updating is actually happening. If I attempt to see it by creating a draft of a new bug report and viewing it on Github, the version remains as 1.26.1.

The Error Alerts:
Error
![image](https://user-images.githubusercontent.com/40413110/50717300-60de7600-1054-11e9-8d94-5b7d44953e94.png)
Prompt
![image](https://user-images.githubusercontent.com/40413110/50717291-4dcba600-1054-11e9-8167-d05611dc9d48.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.80GB (1.36GB free)|
|Process Argv|C:\Users\leoJ\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.4.7

</details>

**Comment by joaomoreno** [comment]
Please change the following setting: `"update.enableWindowsBackgroundUpdates": false`. This will avoid using `inno_updater.exe` at all.
