### ISSUE TITLE
Cannot use HTTPS URL for gutterIconPath in window.createTextEditorDecorationType

### ISSUE THREAD

**Issue by queeniema** [Microsoft/vscode#66069]
Issue Type: <b>Bug</b>

I'm trying to use an icon from an HTTPS URL for the gutter icon like so:

```
const iconPathUri = Uri.parse('https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/workbench/parts/markers/electron-browser/media/status-error.svg');
const decoration = window.createTextEditorDecorationType({
    gutterIconPath: iconPathUri,
    gutterIconSize: 'contain'
});
```

But the icon doesn't show up in the gutter when I call `TextEditor.setDecorations`. If I provide a path to the icon file, then it works fine:

```
const iconPath = context.asAbsolutePath('images/markers/status-error.svg');
const decoration = window.createTextEditorDecorationType({
    gutterIconPath: iconPath,
    gutterIconSize: 'contain'
});
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
vscode-markdownlint|Dav|0.22.0
vscode-eslint|dba|1.7.2
githistory|don|0.4.4
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
ginfuru-vscode-jekyll-syntax|gin|0.1.0
beautify|Hoo|1.4.7
output-colorizer|IBM|0.1.2
theme-by-language|jsa|1.1.1
extension-manifest-editor|ms-|0.1.5
debugger-for-chrome|msj|4.11.1
java|red|0.36.0
sort-lines|Tyr|1.7.0
markdown-all-in-one|yzh|1.8.0

</details>

**Comment by alexandrudima** [comment]
I believe for security purposes, we don't load up remote icons inside the editor. As a workaround, I think you can use node's `https` and download them somewhere and then point us to them on the disk... And perhaps convert them to something more safe like `.png` before passing them to us for rendering...

**But**... IIRC the full explanation is that there could be some `.svg` files that are created in such a way as to expose possible vulnerabilities in the rendering engine (Chromium). Such "evil" `.svg` files could lead to 100% CPU usage or so... It is therefore advisable to only render somewhat "trusted" `.svg` files inside VS Code. e.g. `.svg` files that are static and that you ship with your extension.

If you do include this functionality in your extension, you can perhaps think of ways in which someone could attack it. For example, if you parse the user content from a text editor e.g.
```css
.some rule {
  background: url(https://...)
}
```
And pick up the image url from there, it means that you are loading `.svg` images with their address derived from text editor content. In this case, you should warn the users of your extension that they should not copy-paste untrusted code in the editor when using your extension, as someone might have crafted in there a code section which links to an evil `.svg` that could compromise their machine.

**Comment by alexandrudima** [comment]
@queeniema AFAIK I think the MIT license allows you to copy those icons as long as you acknowledge the copyright holder - Microsoft - and include a copy of the MIT license - https://github.com/Microsoft/vscode/blob/master/LICENSE.txt.

**Comment by queeniema** [comment]
Thanks for the info!
