### ISSUE TITLE
Hot Keys for "Open to the Side"

### ISSUE THREAD

**Issue by laddywig** [microsoft/vscode#66068]
Issue Type: <b>Bug</b>

I have two folders each tied to different, but similar GIT remote repositories. They both share similarly named files. When I open one file and then go to Open to the Side option, it only works when I right click and choose the option. In this situation, if I open one file and then chose it's sister file and use "Cntrl+Enter" to execute the Open to the Side option, it opens up the exact same file in the same folder that I opened up before I tried to execute the "Cntrl+Enter". So in essence, I have the same file opened in two tabs. I've tried this a couple of times making sure this wasn't a PEBKAC issue and now I'm reporting it.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.21.0
python|ms-|2018.12.1
team|ms-|1.144.1
vscode-docker|Pet|0.4.0

</details>

**Comment by egamma** [comment]
@laddywig from the description it is not clear what the issue is. Can you please describe the steps that cause the problem in a way that we can reproduce it. Please use screenshot to illustrate what is going on.

**Comment by laddywig** [comment]
Might be as designed, just seems different work flows between using the
context menu and the shortcut keys. Here's a document to highlight what I
was doing and how to reproduce the issue (quirk?).

Hope this helps!

**Comment by laddywig** [comment]
Hmmm, it's showing up on my thread as being attached. It's a word document,
is it getting stripped in transition? I'll try and attach it again. I'll
copy and paste everything in the email if the document doesn't go through
this time.

[image: image.png]
