### ISSUE TITLE
Extension bug reporter not working

### ISSUE THREAD

**Issue by VErwin** [microsoft/vscode#66063]
Issue Type: <b>Bug</b>

Emulator bug reporter is not auto-populating extensions.  Does not let you type in the extension name manually; instead shows blank dropdown.

Instructions to replicate:  

Help > Report Issue > Bug Report 

File on:  An Extension

Extension:  **BUG**

expected - drop down auto-populate of extensions OR manual textbox

actual - blank drop down which does not auto-populator AND DOES NOT allow for manual data entry with extension name

FIX -  please update to pull data from extension library to auto-populate dropdown and have fallback where if auto-populate does not work allow for manual data entry (if you want to have that since it  would cause validation errors in tracking system).

VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:17:23.540Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz (4 x 2666)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.25GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by egamma** [comment]
@VErwin this works for me. You have to select the empty drop down so that the list of installed extensions appears.

@RMacfarlane we can avoid this confusion by showing the text 'Select Extension' rather than leaving the box empty.

![image](https://user-images.githubusercontent.com/172399/50722629-2b786d80-10d2-11e9-95d6-dde0b0831978.png)

**Comment by VErwin** [comment]
Hi @egamma  -  Sounds like this is a User-Experience fix.   I don't have this extension installed.  A user should NOT have to install an extension in order to report a bug against it.  This is definitely a design flaw.

I don't think that changing the text to 'Select Extension' would have helped this scenario.  I understand the desire to limit accepting bugs that only have this field populated, but if the field only pulls from installed extensions that is a problem for reporting if the validation is preventing the user from submitting a bug with a blank field.  Perhaps there could be a check-box for "Extension not installed" that would allow submission of blank-field for uninstalled Extensions?

**Comment by VErwin** [comment]
If you had a check-box like this, it would allow the data-validation to be over-ridden if the checkbox is selected.  It would allow the "Select Extension" field to be blank, thereby allowing users to submit bugs against Extensions that are not installed.

![extensionbugreporter_mod](https://user-images.githubusercontent.com/45025626/50727200-85763480-10cc-11e9-83d3-7c512c5fed61.png)
