### ISSUE TITLE
Vs code 1.1.1 crashes Error message "We are sorry for the inconvienience......"

### ISSUE THREAD

**Issue by SamuelGustafsson** [Microsoft/vscode#6606]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1.cd  "Folder path" 
2. Enter
3. code .
4. less than one minute the program crashes

![vs crash](https://cloud.githubusercontent.com/assets/14292622/15446970/53d37bee-1f30-11e6-8bba-31e7a163603f.PNG)

**Comment by bpasero** [comment]
@SamuelGustafsson does this happen only for this particular folder? do you have extensions installed?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
