### ISSUE TITLE
Errors in deleted php files are still displayed after file deleted

### ISSUE THREAD

**Issue by Thomas1664** [Microsoft/vscode#66062]
If you delete a php-file with Errors in it, they will be displayed at the error-window and the foldername becomes red
- VSCode Version: 1.30
- OS Version: Windows 10 Version 1809

Steps to Reproduce:

1. Create a php-file
2. create an error in it
3. delete the file

Does this issue occur when all extensions are disabled?: No
Used Extensions: PHP Extension Pack V. 1.0.2 by Felix Becker

**Comment by roblourens** [comment]
Please file this on the PHP Intellisense extension's repo.
