### ISSUE TITLE
Path aliases not working as they should be 

### ISSUE THREAD

**Issue by def14nt** [Microsoft/vscode#66064]
- VSCode Version: 1.30.1
- OS Version: `uname -a` yields `Linux lizard 4.12.14-lp150.12.28-default #1 SMP Mon Dec 3 16:46:15 UTC 201
8 (b91289f) x86_64 x86_64 x86_64 GNU/Linux`

Steps to Reproduce:

1. Make a `tsconfig.json` in the base dir of your project, then create a path mapping.
2. Use the path mapping.

Does this issue occur when all extensions are disabled?: Yes

Here's a sample of my code, and my `tsconfig.json`.
`/src/client/weather/WeatherClient.ts`:
```ts
import * as a from '@open-weather/types';
```

`tsconfig.json`:
[Here's a GhostBin](https://ghostbin.com/paste/yf23x).

**Comment by mjbvz** [comment]
The path mapping:

```
"paths": {
      "@open-weather/types": ["client/types/*.ts"]
    }
```

Is not valid. `"@open-weather/types"` must be mapped to a single TS file or module instead of a set of files using `*.ts`.

Try something like:

```
"paths": {
      "@open-weather/types": ["client/types/open-weather-types.d.ts"]
    }
```
