### ISSUE TITLE
不能安裝擴展

### ISSUE THREAD

**Issue by shiyee** [Microsoft/vscode#66078]
Issue Type: <b>Bug</b>

不知道哪裡出了問題，我現在不能安裝任何擴展了。。。

安裝的進度條一直在進行，多久都不會消失。。。

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz (2 x 3066)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (5.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by shiyee** [comment]
重裝了，也刪除了安裝目錄和個人目錄下的文件也不行

**Comment by ddzy** [comment]
安装vscode explore版的试一下

**Comment by egamma** [comment]
please see https://github.com/Microsoft/vscode/issues/66024#issuecomment-451499883
