### ISSUE TITLE
Task bar button(vsc icon) separate view for multiple workspace.

### ISSUE THREAD

**Issue by jayatathi** [microsoft/vscode#66076]
example:
Admin Folder  - vs logo icon gray color 
User Folder - vs logo icon green color 

Each one is separately view in Task bar button.

Suppose i am working on three different Technologies like Angular, React, View i was unable to find in Task bar icon.

**Comment by egamma** [comment]
@jayatathi not clear from the description what the problem is, please illustrate the problem with a screenshot.

**Comment by RandomGHUser** [comment]
+1, having custom taskbar / titlebar icons configurable per workspace (and ability to not combine them in the taskbar) would enhance at-a-glance organization.

**Comment by hmdhasani** [comment]
As VS Code is replacing other tools that had separated icons in taskbar before, being able to have multiple VS Code icons with different colors (or even icons) in taskbar is becoming a need more and more. (A use-case for me is the ability to use Win+Numbers shortcut to quickly switch between windows)

Here has a workaround for that:
https://www.reddit.com/r/vscode/comments/fkplzc/how_do_i_prevent_vscode_portable_copies_from/

But I think it would be nice if VS Code itself provide a straightforward way for that.

**Comment by MaykGyver** [comment]
VSCode has profiles. MSEdge has profiles too. If there was a fairy and I had a wish – a transfer of Edge's taskbar icon behavior to VSCode would be a huge leap forward.
