### ISSUE TITLE
TSDoc Optional Parameters - Different Coloring

### ISSUE THREAD

**Issue by robgraeber** [Microsoft/vscode#66079]
For some reason, it seems like optional tsdoc params as noted by [] braces are colored differently than regular tsdoc params. I'm trying to turn the color off for them, but all the solutions for turning off jsdoc colors doesn't affect optional params. Is there another solution?

- VSCode Version: 1.30.1 (latest)
- OS Version: OS X 10.14

To Reproduce:

Create a tsdoc comment with optional parameters like:
```
/**
 * Wrapper subscribe function that only allows 1 concurrent job.
 * @param jobName Job name in the queue.
 * @param jobHandler Function that accepts a job parameter.
 * @param [jobConcurrency] The number of jobs to run at the same time.
 * @param [pollingFrequency=1000] The polling frequency in ms.
 */
```

Does this issue occur when all extensions are disabled?: Yes

With my theme + jsDoc coloring turned off:
```
"textMateRules": [
      {
        "name": "storage.type.class.jsdoc",
        "scope":
          "storage.type.class.jsdoc,entity.name.type.instance.jsdoc,variable.other.jsdoc",
        "settings": {
          "foreground": "#7f848eff"
        }
      }
    ]
```
<img width="538" alt="screen shot 2019-01-04 at 10 05 16 pm" src="https://user-images.githubusercontent.com/2387719/50721067-92b00680-106d-11e9-9f5b-562af432d951.png">

With all extensions turned off:
<img width="539" alt="screen shot 2019-01-04 at 10 14 04 pm" src="https://user-images.githubusercontent.com/2387719/50721092-4ca77280-106e-11e9-993f-12af7178e8c7.png">

**Comment by KamasamaK** [comment]
It's being colored as a string because it has the `string.other.link.title.markdown` scope applied to it. It seems to be expecting that it be preceded with the type because that fixes it.

**Comment by robgraeber** [comment]
@KamasamaK Thanks that's interesting and was able to fix my issue. This was for a typescript file so it's suppose to not have a type, I updated the issue.

**Comment by KamasamaK** [comment]
I see. If it's for TypeScript, I'm not sure why you would need to indicate optional parameters in the TSDoc since the language supports that constraint already. I'm not sure if that's part of the TSDoc spec and I've personally never seen it.

**Comment by robgraeber** [comment]
@KamasamaK I think you're right, the TSDoc playground didn't recognize it. Never mind seems like this is working as intended. Thanks for the help!
