### ISSUE TITLE
Replace a single file

### ISSUE THREAD

**Issue by q312102408** [Microsoft/vscode#66086]
我做了一个对中文友好的功能.. 需要把<workbench.main.js> 替换掉.但替换后,程序不能运行,我要怎么做才可以运行..

I made a friendly to Chinese. The function of the. Need to put the < workbench. Main. Js > replace. But after replacement, program can not run, how can I do to run..

![u2de x1co33nxhf l2judb](https://user-images.githubusercontent.com/38882827/50725361-6eb8f780-1137-11e9-9684-71ed98fb0e47.png)

**Comment by egamma** [comment]
From the description it is not clear what the problem is. Can describe what you are doing step by step with screen shots and the describe what the expected behaviour is and what the behaviour is that you are seeing.
