### ISSUE TITLE
Issue reporter: force reporter of an issue to make a choice whether the issue is for VS Code or an extension

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#66080]
Currently the issue reporter defaults to filing an issue against VS Code:

![image](https://user-images.githubusercontent.com/172399/50722683-e86aca00-10d2-11e9-98df-f7d880d3f178.png)

To reduce the number of issues filed against VS Code that should be filed for an extension I suggest that the user has to make an explicit choice. That is the drop down should default to something like 'Select Source of Issue' and the dropdown provides the choices 'VS Code, Extension, Don't know'

Then when the user selects Don't know the recommendation to try starting with extension disabled is shown and the user has to check a checkbox.

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/a509265116babc17648c9052eeeb8ae2909fed87#diff-bc2d789381005293245ca139cbdc7821
