### ISSUE TITLE
Failed to start the socket server. (Error: listen EADDRNOTAVAIL 192.168.153.213)

### ISSUE THREAD

**Issue by fangxu622** [Microsoft/vscode#66085]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
![image](https://user-images.githubusercontent.com/16681534/50725015-20552a00-1132-11e9-8a49-f77ffb6389e2.png)

how to resolve this ,and i reinstall vscode and python extension. it doesn't solve the problem . ubunt 18.04

**Comment by egamma** [comment]
@fangxu622 it looks like you have an issue with debugging Python, which is a separate extension, pls file an issue against the python extension and include detailed steps for how reproduce the problem.
