### ISSUE TITLE
Editor prompt to force code  (setTimeout)

### ISSUE THREAD

**Issue by zheng1013757145** [Microsoft/vscode#66082]
- VSCode Version: 1.30.1
- OS Version: Window 

1. Editor input setTimeout forces code to the module
![image](https://user-images.githubusercontent.com/23191825/50724682-69a27b00-112c-11e9-910a-76d44bec8098.png)
The added code is as follows
![image](https://user-images.githubusercontent.com/23191825/50724686-76bf6a00-112c-11e9-9f6c-405b09ec4bc5.png)

**Comment by mjbvz** [comment]
Please file this issue against the vetur extension
