### ISSUE TITLE
Error icon appears clipped in the status bar

### ISSUE THREAD

**Issue by zhongbinfan** [microsoft/vscode#66083]
Just Look like this:
![image](https://user-images.githubusercontent.com/38887536/50724729-f9482980-112c-11e9-88af-b9023389b566.png)

This happen in many themes!!!

**Comment by zhongbinfan** [comment]
OS:  macos

**Comment by egamma** [comment]
>This happen in many themes!!!

@zhongbinfan please define themes that expose this behaviour so that we can reproduce this behaviour.

**Comment by zhongbinfan** [comment]
@egamma 
Color！
It happens except for the default theme.

**Comment by egamma** [comment]
@zhongbinfan what happens when you resize the window?

**Comment by zhongbinfan** [comment]
@egamma  Nothing, I just wrote the code normally, and then I found this phenomenon.
