### ISSUE TITLE
Support Pinch-To-Zoom for changing editor font size / zoom level

### ISSUE THREAD

**Issue by phdoerfler** [microsoft/vscode#66088]
This touchpad gesture currently results in scrolling vertically in the editor which, I assume, nobody wants anyway.
Instead this could be used to temporarily change the editor font size similar to [IntelliJ IDEA on macOS](https://imgur.com/a/7UCTBrB). I hope this short screen cap makes it clear.
What I especially like about this is that it's a very fine adjustment and only in the current editor.
This makes it great for presenting at conferences where you often have limited resolution available, a 4:3 aspect ratio and viewer sitting far away and you want to zoom into the controls but rather the text only.

**Comment by nmggithub** [comment]
https://stackoverflow.com/a/41684631

Turning on this setting should work.
