### ISSUE TITLE
VS Code installation disappeared and now can't download VS Code on my Mac

### ISSUE THREAD

**Issue by interglobalmedia** [microsoft/vscode#66081]
- VSCode Version: 1.30
- OS Version: 10.14 (but problems started with 10.13.6)

Steps to Reproduce:

1. Install on my machine?
2.

Does this issue occur when all extensions are disabled?: Yes/No Yes but can't even it get it downloaded. It opens up in downloads and that is it. Can't use it after that. The whole thing started when I uninstalled a corrupted version of 1.30 and re-installed. Have had problems ever since. That was a couple of weeks ago. I guess I have to use another code editor until the problem is solved or maybe never. This editor was so great, but no longer is reliable!

**Comment by egamma** [comment]
@interglobalmedia please try to delete the existing VS Code installation and then do a fresh VS Code install.
