### ISSUE TITLE
Editorconfig vs auto detection

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vscode#66084]
Issue Type: <b>Bug</b>

Auto detection of tab settings appears to override explicit settings from .editorconfig files.
It should be the other way around..

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

**Comment by egamma** [comment]
@OlafvdSpek do you have the editor config extension installed?

**Comment by OlafvdSpek** [comment]
No.. isn't it installed by default?

**Comment by egamma** [comment]
Not it is a separate extension that needs to be installed https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig.

**Comment by OlafvdSpek** [comment]
Shouldn't it be bundled and enabled by default?

**Comment by egamma** [comment]
@OlafvdSpek we want to keep the bundled extensions to a minimum to keep the VS Code install small. What we do is to recommend the editor config extension as soon as we detect a .editorconfig file. 

It appears that you have overlooked this recommendation?

**Comment by OlafvdSpek** [comment]
Or the detection / recommendation is broken..
Just now I opened a CMakeLists.txt file. The same directory contains .editorconfig but I see no recommendation.

**Comment by OlafvdSpek** [comment]
@egamma ^
