### ISSUE TITLE
Type curly bracket using Czech (QWERTY) keyboard layout.

### ISSUE THREAD

**Issue by machv** [Microsoft/vscode#6609]
- VSCode Version: 1.1.1
- OS Version: Windows 10 1511 (Build 10586.318)

Steps to Reproduce:

1. Use Czech (QWERTY) keboard layout.
2. Press ```Ctrl```-```Alt```-```Shift```-```[``` keys together (or ```AltGr```-```Shift```-```[```)

Problem is that instead of just typing opening curly bracket ```{``` character in editor, VS Code collapses all definitions within curly brackets ```{``` ```}``` block. This behaviour makes writing source code using Czech QWERTY keyboard really uncomfortable.

Same problem is with closing curly bracket (```Ctrl```-```Alt```-```Shift```-```]```).

**Comment by alexandrudima** [comment]
@aeschli 

Offending default keybindings:
```
{ "key": "ctrl+shift+alt+[",      "command": "editor.foldAll",
                                     "when": "editorFocus" },
{ "key": "ctrl+shift+alt+]",      "command": "editor.unfoldAll",
                                     "when": "editorFocus" },
```

ctrl+alt+ combinations should be avoided on Windows, as ctrl+alt+ is sent our way by Chromium when AltGr+ is pressed. AltGr+ is often used on various keyboard layouts.

**Comment by miloush** [comment]
@alexandrudima note that this is not a Chromium thing, Ctrl+Alt is simply the same shift state as AltGr.

**Comment by aeschli** [comment]
i changed it to:
```
{ "key": "ctrl+k ctrl+0",         "command": "editor.foldAll",
                                     "when": "editorFocus" },
{ "key": "ctrl+k ctrl+j",         "command": "editor.unfoldAll",
                                     "when": "editorFocus" },
```

**Comment by alexandrudima** [comment]
@aeschli Be sure to Release Note this change

**Comment by aeschli** [comment]
@alexandrudima Thanks for the reminder, I added an entry to the release notes
