### ISSUE TITLE
API for sending messages to screen readers via live region

### ISSUE THREAD

**Issue by SamKacer** [microsoft/vscode#66091]
While developing extensions that target screen reader users, it would be useful to be able to have the ability to have some text directly and immediatly read by the screen reader. It seems that VS Code uses live regions to achieve this (at least in the case of autocompletion suggestions). It would be useful if setting the text in this live region to be read by screen readers could be done through the API when developing extensions, because it would be more efficient for all extensions to access one central live region, than every extension that wants to send messages directly to screen readers to create its own webview for this purpose.

**Comment by Neurrone** [comment]
This issue is specifically about sending live region events, so I'm wondering if the built-in APIs for visually printing out notifications already do this, without the extension author needing to be explicitly aware that this is happening under the hood.

**Comment by SamKacer** [comment]
@Neurrone
There is API for visually printing notifications and error messages, etc. However the problem for these is that each message is prefixed by "Alert:" or "Error:", so it doesnt meet the need of being able to send arbitrary messages to screen readers.
