### ISSUE TITLE
The selection.background theme colour is different than the defined value and inconsistent

### ISSUE THREAD

**Issue by roydukkey** [Microsoft/vscode#66098]
The colour that is being used for widget's form field selection background is not the colour that is specified. Even adding a alpha channel doesn't mitigate the issue.

- VSCode Version: 1.30.1
- OS Version: MacOS 10.14.1 (18B75)

Steps to Reproduce:

1. Set `selection.background` to `#FF0000FF`
2. Open Find/Replace widget
3. Select a portion of the text in the text field
4. Notice the selection's background colour is not the one specified

Does this issue occur when all extensions are disabled?: Yes

The current file's Find/Replace widget, workspace's Find/Replace widget, and the source control sidebar's commit message form field all have this result.

<img width="557" alt="screen shot 2019-01-05 at 20 31 25" src="https://user-images.githubusercontent.com/1509616/50731035-082cdd00-1129-11e9-8e30-b7d9421d93e8.png">

The VSCode settings panel has the follow result.

<img width="557" alt="screen shot 2019-01-05 at 20 38 12" src="https://user-images.githubusercontent.com/1509616/50731081-162f2d80-112a-11e9-8748-1e7c4c910117.png">

**Comment by aeschli** [comment]
This is about the selection color in the settings editor find box. It seems to take the selection color from `selection.background` but does something to it.

**Comment by roblourens** [comment]
When we set the selection color, it's blended somehow with the color behind it. As you can see, when you set it to `ff0000`, it's not actually that color. This is done by the browser. But the settings input is not a native text input, so we have to set the color manually. I couldn't figure out exactly how the blending works so I had to guess a transparency level and I picked something that seemed to produce decent results across a range of foreground and background colors. I think the real blending mode does more than apply a transparency.

I'm open to suggestions if anyone knows how this actually works. The current code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/codeEditor/electron-browser/suggestEnabledInput.ts#L252

**Comment by roydukkey** [comment]
@roblourens Why would a transparency be applied to the color? Shouldn't this be handled by the theme, especially since color values are allowed to specify an alpha channel?

As a theme creator, I would expect to maintain control of blending. And, since blending isn't (possibly even can't be) applied in the same manner everywhere, would it be better to not make assumptions?

**Comment by roblourens** [comment]
In the settings editor input I'm just trying to emulate what the browser is already doing. We aren't in control of the blending that the browser does there.

**Comment by roydukkey** [comment]
I see.... https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#Accessibility_concerns

This is rather annoying.

**Comment by roblourens** [comment]
Indeed...
