### ISSUE TITLE
Touchpad scroll behaves as arrow keys(yes duplicate;desperate attempt)

### ISSUE THREAD

**Issue by zenVentzi** [Microsoft/vscode#66093]
Please excuse my purposeful opening of a duplicate issue. I understood that it's an issue with Chromium and not VS Code. Starred and commented the issue on chromium. But seeing that it's more than 1 year old and not even confirmed, with only 3 stars.. compared to hundreds of pages with other way more starred & commented issues.. maybe what I am trying to ask is could somehow VS Code's community give a helping hand? I am very aware that what I am doing here is quite a sad attempt but just got my brand new laptop SUPER looking forward to my way, way improved VS Code experience only to find out that the thing that I do 90% of the time has quite a chance of not being fixed any time soon if at all.

I won't judge if you close this issue, since I understand all your efforts for fixing way more global issues but would really, really, really appreciate some support.

Chromium issue [link](https://bugs.chromium.org/p/chromium/issues/detail?id=784329&can=2&start=0&num=100&q=touchpad%20scroll&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=)

**Comment by egamma** [comment]
As you say it is a duplicate. please see https://github.com/Microsoft/vscode/issues/61824#issuecomment-451380300.
Also did you try the window.smoothScrollingWorkaround setting https://code.visualstudio.com/updates/v1_22#_windows-workaround-for-scroll-lag
