### ISSUE TITLE
 Cannot read property 'editOperations' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#661]
Issue Id: <b>5a695e30-92c3-4068-f55a-e693c4cc9970</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/editor/common/model/editStack.ts#L75:31 (EditStack.pushEditOperation)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/model/editStack.ts#L75:31 (EditStack.pushEditOperation))<br />[/vs/editor/common/model/editableTextModel.ts#L92:30 (EditableTextModel.pushEditOperations)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/model/editableTextModel.ts#L92:30 (EditableTextModel.pushEditOperations))<br />[/vs/editor/common/controller/cursor.ts#L744:35 (Cursor._innerExecuteCommands)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/cursor.ts#L744:35 (Cursor._innerExecuteCommands))<br />[/vs/editor/common/controller/cursor.ts#L678:15 (Cursor._internalExecuteCommands)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/cursor.ts#L678:15 (Cursor._internalExecuteCommands))<br />[/vs/editor/common/controller/cursor.ts#L420:33 (Cursor._interpretHandlerContext)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/cursor.ts#L420:33 (Cursor._interpretHandlerContext))<br />[/vs/editor/common/controller/cursor.ts#L314:7 (Cursor._createAndInterpretHandlerCtx)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/cursor.ts#L314:7 (Cursor._createAndInterpretHandlerCtx))<br />[/vs/editor/common/controller/cursor.ts#L340:34 (Cursor._onHandler)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/cursor.ts#L340:34 (Cursor._onHandler))<br />[/vs/editor/common/controller/cursor.ts#L977:52 (Cursor._registerHandlers)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/cursor.ts#L977:52 (Cursor._registerHandlers))<br />[/vs/editor/common/controller/handlerDispatcher.ts#L56:13 (HandlerDispatcher.trigger)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/controller/handlerDispatcher.ts#L56:13 (HandlerDispatcher.trigger))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#L721:47 (CodeEditorWidget.executeCommand)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/browser/widget/codeEditorWidget.ts#L721:47 (CodeEditorWidget.executeCommand))<br />    at t.executeCommand (out/vs/workbench/workbench.main.js:1583:20373)<br />

**Comment by alexandrudima** [comment]
Not reported in more than 6 months => closing
