### ISSUE TITLE
sortText of ItemCompletion are being ignored when comparing to ItemCompletion that doesn't specify the sortText field

### ISSUE THREAD

**Issue by natanfudge** [microsoft/vscode#66109]
Issue Type: <b>Bug</b>

- Create a new Typescript extension with `yo code`.
- In package.json, replace the `actionEvents` field with 

		"activationEvents": [
			"*"
		],
- Replace extension.ts with the following code:
    

		import * as vscode from 'vscode';

		export function activate(context: vscode.ExtensionContext) {

			let provider = vscode.languages.registerCompletionItemProvider("plaintext", {
			provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext){
				return [
					{
						label:"C",
						detail:"Should show above the B",
						sortText :"A"
					},
					{
						label:"B",
						detail:"Should show below the C",

					}
				]
			}
			});

			context.subscriptions.push(provider);
		}

		export function deactivate() {}

- Run the extension and create a new txt file.
- Press ctrl+space to show completion options.

### What I expected:
The `'C'` option will be sorted to be shown above the `'B'` option, because it has a `sortText` of `'A'`.
### What actually happened:
The `'C'` option will be sorted to be shown below the `'B'` option, because its `sortText` is being ignored and the `label `is used for sorting instead. 

You can see that if you just add a sortText of 'B' to 'B' it works as expected. 

	{
		label:"C",
		detail:"Should show above the B",
		sortText :"A"
	},
	{
		label:"B",
		detail:"Should show below the C",
		sortText:"B"

	}

VS Code version: Code - Insiders 1.31.0-insider (bae6c84d46cd85c911db7e166a74e698a54c8644, 2019-01-04T06:17:20.719Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by alshain** [comment]
@jrieken Does that mean, that the documentation is currently outdated?

> A string that should be used when comparing this item with other items. When falsy the label is used.

https://code.visualstudio.com/api/references/vscode-api#CompletionItem.sortText

**Comment by vivlimmsft** [comment]
Another way this can surface is if you have multiple extensions contributing to the same completion list, with one using `sortText` and another not.

IntelliCode uses `sortText` to bring our recommendations to the top of the list. If another extension is providing completion items which omit `sortText`, those can appear above the recommendations. This isn't a great experience since we are also applying `editor.suggestSelection: first` to focus that first item, which we expect to be a recommendation.

@jrieken did you end up trying what you mentioned above?

**Comment by jrieken** [comment]
> @jrieken did you end up trying what you mentioned above?

No, but we should. I will push a change today and then we (that includes your and IntelliCode) need to observe how https://code.visualstudio.com/insiders/ behaves.

**Comment by jrieken** [comment]
@mjbvz Just a heads up that this changed - I believe the original (questionable) behaviour was introduced for TS, or TS as it was years back, and I wonder if you have observed any difference since the last week?

**Comment by vivlimmsft** [comment]
@jrieken Sorry for the delay, I just had a chance to try this and it looks good to me.

**Comment by jrieken** [comment]
Yeah, we haven't seen issues (yet) and I am all in for shipping like this in September.
