### ISSUE TITLE
Emmet expansion with React components

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#66107]
There are currently two ways to expand a React component.

1. Type in the opening bracket, begin typing in the component name, accept the suggestion, type in the closing bracket, and then let VSCode's auto closing tag feature do the rest.

2. Enable the following setting: `"emmet.triggerExpansionOnTab": true,`.  After which we can then just start typing the component name, accept either the word or symbol suggestion, and then `tab` again to have Emmet complete the tag.

**Feature Request**

I believe option 2 is probably preferable to most. However, I wonder if it'd be possible to remove the requirements of that second `tab`, making it behave more like a normal html tag would in emmet (i.e. accept suggestion and done). In other words, if the accepted suggestion is an imported React component, it will automatically expand the tag without having to trigger it.

**Side Note**

The only reason why we are able to select imported React components at all times from the suggestion list is because of the following setting: `"editor.wordBasedSuggestions": true`. Without it, you would only be able to use this when the symbol suggestion appears, which is limited, as [described here](https://github.com/Microsoft/vscode/issues/43266). This is an unnecessary limitation, because an imported component is almost never noise (the [reason given in the docs](https://code.visualstudio.com/docs/editor/emmet#_custom-tags-do-not-get-expanded-in-the-suggestion-list) for why VSCode might ignore suggestions), and should always appear as a suggestion when editing JSX.

**Comment by rzhao271** [comment]
@jabacchetta I think Emmet waits for the second tab so that you can combine multiple HTML nodes into a single abbreviation such as `ul>li.item$*5>span`. If Emmet didn't wait for the second tab, then it can only expand one node at once.

Thoughts?
