### ISSUE TITLE
I build with arm64 but armhf

### ISSUE THREAD

**Issue by muxhub** [Microsoft/vscode#66108]
Device : Jetson Xavier

Processor : ARMv8 Processor rev 0 (v8l) × 8 

OS Type : 64-bit

Version of source code : 1.30.1

My steps:
```
1. ./scripts/npm.sh install --arch=arm64
2. ./scripts/code.h
3. yarn run gulp vscode-linux-arm-build-deb
```
I get a package named "deb/code-oss_1.30.1-1546767579_armhf.deb", and I get an error when I install the package with "dpkg".

```
sudo dpkg -i install code-oss_1.30.1-1546767579_armhf.deb
```

```
dpkg: error processing archive code-oss_1.30.1-1546767579_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
```
It works fun when i run `./scripts/code.h`, but I get armhf packages.

**Comment by joaomoreno** [comment]
You should use `vscode-linux-arm64-build-deb` instead. Give it a try!

**Comment by muxhub** [comment]
> You should use `vscode-linux-arm64-build-deb` instead. Give it a try!

Thank you! I build the deb success, and I can install it ,but I cannot find vscode in my panel!
