### ISSUE TITLE
Make un-pushed changes more obvious

### ISSUE THREAD

**Issue by vcsjones** [Microsoft/vscode#6610]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11

As a feature request, it would be nice if the Git integration would make un-pushed changes more obvious. Similar to the blue-badge when there is uncommitted work, a visible badge for un-pushed changes would be helpful.

**Comment by Tyriar** [comment]
In my dotfiles I show a green up arrow and number for number of commits ahead as well as a red down arrow and number for commits behind the remote. Might be good to integrate something like this?

**Comment by joaomoreno** [comment]
We have this... the following screenshot shows that there is 1 commit yet to be pushed.

![image](https://cloud.githubusercontent.com/assets/22350/15496488/bf0ecbea-2195-11e6-87a1-029f63d1c8e2.png)

**Comment by Tyriar** [comment]
Oh yeah :+1:
