### ISSUE TITLE
Search Window Layout Error

### ISSUE THREAD

**Issue by ayoubkhan558** [Microsoft/vscode#66103]
> When I open VS Codes Search Panel its does not display correct.
> It does nt behave correctly, It left some space between document and search panel.

![error](https://user-images.githubusercontent.com/20210961/50732560-42d15c80-119f-11e9-83e7-a615072e2e60.JPG)
![errr vs cde](https://user-images.githubusercontent.com/20210961/50732561-42d15c80-119f-11e9-96fc-a4e5c1ee1479.JPG)

- VS Code Version: **1.30.1**
- OS Version: Windows **10 (Version: 1709, Build: 16229)**

Steps to Reproduce:

1. It should display like this
![sai](https://user-images.githubusercontent.com/20210961/50732569-85933480-119f-11e9-8829-05df080d3101.JPG)

2. It should not change its layout on Search panel open 

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Are you saying that extra lines should never show up?

**Comment by roblourens** [comment]
The extra space is available so that the find widget doesn't overlap results in the editor. But the extra space shouldn't appear immediately when you press ctrl+f, it should only open if you navigate through results, or scroll to it. Does this match what you see?

**Comment by usernamehw** [comment]
Probably a duplicate of #28390

**Comment by ayoubkhan558** [comment]
> Probably a duplicate of #28390

Yes it's duplicate.
