### ISSUE TITLE
download link for windows is not working

### ISSUE THREAD

**Issue by pablovillauy** [Microsoft/vscode#66101]
- OS Version: WINDOWS

Steps to Reproduce:

1.
https://vscode-update.azurewebsites.net/latest/win32-x64-user/stable

2.
This site can’t be reached vscode-update.azurewebsites.net took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by GriffinAustin** [comment]
Works for me on Windows 10 Google Chrome. What browser(s) have you tried thus far?

**Comment by egamma** [comment]
Works for me as well. @pablovillauy can you try again? Did you work for you before?

**Comment by pablovillauy** [comment]
thanks for your responses.
it is not working either today. it is strange.
i am using chrome in windows 10.

**Comment by egamma** [comment]
I've not seen other reports that the link is not working (checked twitter and other issues). 
Is it the first time you try to download from the web site?

**Comment by pablovillauy** [comment]
yes yes. first time.
but it's strange, it is just an azure site.
i will ask a friend to download and put it in a onedrive or something like that

thanks for your help

**Comment by GriffinAustin** [comment]
@pablovillauy Can you try using another browser?

**Comment by pablovillauy** [comment]
same problem with edge


Hmmm...can’t reach this page                                 Try this                                                                                                           Make sure you’ve got the right web address:  https://vscode-update.azurewebsites.net                                     Search for "https://vscode-update.azurewebsites.net" on Bing                                     Refresh the page                                                                                                                                                Details                                                                                                                                                                             Report this issue                                                                                                   Privacy statement
--

**Comment by GriffinAustin** [comment]
@pablovillauy Can you try another machine on the same network and try your original machine on a different network?

**Comment by pablovillauy** [comment]
thanks Griffin!
I did it from another laptop in the same network and it works.
I am curious about the issue in my laptop...
