### ISSUE TITLE
[terminal] Don't throw error, when you close the terminal through the "exit" command.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#66113]
Issue Type: <b>Bug</b>

The terminal process terminated with exit code: 9009
t.onDidNotificationChange @ /C:/Users/[USER]/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2509

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1

</details>

**Comment by Tyriar** [comment]
We show the alert whenever the shell exits non-zero, you can turn this off all together with this setting:

```
"terminal.integrated.showExitAlert": false
```

We're unable to detect just that case though.
