### ISSUE TITLE
Pressing F5 to continue while on breakpoint does not continue debug session

### ISSUE THREAD

**Issue by dimitryvolkov** [Microsoft/vscode#66111]
- VSCode Version: 1.31.0-insider (commit bae6c84d46cd)
- OS Version: Windows 10 Build 1803

Steps to Reproduce:
1. Press F5 once to start debugging JS code
2. Break on some breakpoint
3. Press F5 again to continue debugging
4. Notification appears on bottom right: "There is already a debug configuration ".. running", and debug session isn't continued.

Does this issue occur when all extensions are disabled?: Yes

Looking at the keyboard shortcuts I do see Continue bound to F5 and "When" set to "inDebugMode", however when going over the menu items I see all the bound keys to "Step in" / "Step over" but nothing for "Continue".

#60191 seems to be related, however it was closed in Oct as resolved and this still shows in a commit from two days ago

**Comment by isidorn** [comment]
Fixed in latest. Dup of https://github.com/Microsoft/vscode/issues/65948
Thanks for reporting and for using insiders
