### ISSUE TITLE
Cannot drag window when clicking empty space in titlebar near the help menu

### ISSUE THREAD

**Issue by pedrogarcia** [Microsoft/vscode#66114]
Issue Type: <b>Bug</b>

1. Click to drag window near the Help button, but outside of the mouseover highlighted area.
2. Window is not dragged.

See screen recording:
![](https://thumbs.gfycat.com/HarshImaginativeAlabamamapturtle-size_restricted.gif)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-path-tools|cg-|0.0.4
code-runner|for|0.9.5
terminal|for|0.0.10
language-julia|jul|0.11.1
r|Mik|0.0.5
python|ms-|2018.12.1
r-lsp|REd|0.0.8
shell-launcher|Tyr|0.3.0
markdown-pdf|yza|1.2.0

(2 theme extensions excluded)

</details>

**Comment by Cybernetixs** [comment]
I just started having the same issue after upgrading to 1.30.1.

VS Code version: Code 1.30.1  2018-12-18T18:12:07:165Z
OS version: Windows_NT x64 10.0.17134  (24G ram)

If there is a window behind VS code I cannot move the VS code window unless I resize the left and right sides of the window first, and then move it.

**Comment by sbatten** [comment]
@pedrogarcia this should be fixed in the latest insiders
