### ISSUE TITLE
[rust] The keyword `where` can't be highlighted like others

### ISSUE THREAD

**Issue by arniu** [Microsoft/vscode#6611]
- VSCode Version:  1.1.1
- OS Version: Ubuntu 16.04

**Comment by aeschli** [comment]
@arniu Can you provide a small code sample that shows the issue?

**Comment by arniu** [comment]
I mean the keyword `where` will not be highlighted, just rendered with no color.

**Comment by aeschli** [comment]
This how it looks to me using the Dark+ (default dark) theme:
![image](https://cloud.githubusercontent.com/assets/6461412/15657109/1cca76f4-26ae-11e6-9f68-7266a491307b.png)

A code sample would help to understand what's different in your setup. What theme do you use? Do you use any extensions for Rust?

**Comment by arniu** [comment]
Hi @aeschli, this is how it looks to me using the default theme:

![rust-where-not-highlight-modified](https://cloud.githubusercontent.com/assets/1286674/15821103/5d332b92-2c20-11e6-928f-7ff538f17e55.png)

I've install `Rusty Code` only for Rust. The problem is still there, no matter whether I install the extension or not.

**Comment by aeschli** [comment]
Oh, I read `while`, but you meant `where`. Sorry for that.

**Comment by aeschli** [comment]
This is https://github.com/zargony/atom-language-rust/issues/57.

I added a fix along https://github.com/zargony/atom-language-rust/pull/66, not sure why that pull request got closed.
