### ISSUE TITLE
can not find function reference ,and  always show loading animation forever

### ISSUE THREAD

**Issue by gaogaolater** [Microsoft/vscode#66124]
Issue Type: <b>Bug</b>

can not find function reference ,and  always show loading animation forever

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.2
gitlens|eam|9.3.0
prettier-vscode|esb|1.7.3
Hap|hap|0.0.8
vue-snippets|hol|0.1.10
code-beautifier|mic|2.1.0
vetur|oct|0.14.5
material-icon-theme|PKi|3.6.2
minapp-vscode|qiu|1.12.0

</details>

**Comment by gaogaolater** [comment]
1、click a function，i want go to its defined row number
2、a loading animation appear on bottom of tabs ，from left to right。 sometimes it not work。but the animation not disappear。

**Comment by egamma** [comment]
@gaogaolater this is a good start, but what is in your workspace when this happens, what file do you have open when this happens. Please add screenshot when this happens.
