### ISSUE TITLE
Unicode and emojis is terminal are sometimes the wrong width

### ISSUE THREAD

**Issue by leejinseok** [microsoft/vscode#66125]
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.15063

Steps to Reproduce:
1.
2.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/7136340/50747655-674d3780-1278-11e9-854e-b51c2fc1915a.png)

**Comment by Tyriar** [comment]
Tracking unicode width issues upstream
