### ISSUE TITLE
Freezes with a triple-split terminal frequently when entering a commit message

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#66130]
My computer has been known to freeze but for the past few months after adjusting the swappiness etc. it hasn't been too bad.

However, when I try to have a triple-split integrated terminal (one to check git diff HEAD, another for git add ., and another for git commit—separating them for convenience by accessing the previous command by pressing the up button), often, when I am editing the commit message, the terminal freezes. I can still open a new terminal, and do other stuff in VS Code, type in the other terminals as per normal, split the terminal window, but the commit 3rd split terminal is non-responsive, while I can delete it and start writing the commit message again.

```bash
[jray@jr-dl ~]$ inxi -Fxz
System:
  Host: jr-dl Kernel: 4.19.12-2-MANJARO x86_64 bits: 64 compiler: gcc 
  v: 8.2.1 Desktop: N/A Distro: Manjaro Linux 
Machine:
  Type: Laptop System: Dell product: Latitude E6410 v: 0001 serial: <filter> 
  Mobo: Dell model: 0HNGW4 serial: <filter> UEFI: Dell v: A16 
  date: 12/05/2013 
Battery:
  ID-1: BAT0 charge: 48.8 Wh condition: 39.6/48.8 Wh (81%) 
  model: Samsung SDI DELL PT43699 status: Full 
CPU:
  Topology: Dual Core model: Intel Core i5 M 560 bits: 64 type: MT MCP 
  arch: Nehalem rev: 5 L2 cache: 3072 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 21288 
  Speed: 2739 MHz min/max: 1199/2667 MHz Core speeds (MHz): 1: 2708 2: 2774 
  3: 2774 4: 2895 
Graphics:
  Device-1: Intel Core Processor Integrated Graphics 
  vendor: Dell Latitude E6410 driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.3 driver: intel unloaded: modesetting 
  resolution: 1440x900~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 18.2.6 
  direct render: Yes 
Audio:
  Device-1: Intel 5 Series/3400 Series High Definition Audio 
  vendor: Dell Latitude E6410 driver: snd_hda_intel v: kernel 
  bus ID: 00:1b.0 
  Sound Server: ALSA v: k4.19.12-2-MANJARO 
Network:
  Device-1: Intel 82577LM Gigabit Network vendor: Dell Latitude E6410 
  driver: e1000e v: 3.2.6-k port: 7040 bus ID: 00:19.0 
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  Device-2: Broadcom and subsidiaries BCM43224 802.11a/b/g/n 
  vendor: Dell Wireless 1520 Half-size Mini PCIe Card driver: wl v: kernel 
  port: 7000 bus ID: 02:00.0 
  IF: wlp2s0 state: down mac: <filter> 
Drives:
  Local Storage: total: 1.20 TiB used: 137.07 GiB (11.1%) 
  ID-1: /dev/sda vendor: Seagate model: ST9320423AS size: 298.09 GiB 
  ID-2: /dev/sdb type: USB vendor: Seagate model: Expansion size: 931.51 GiB 
Partition:
  ID-1: / size: 284.06 GiB used: 10.73 GiB (3.8%) fs: ext4 dev: /dev/sda2 
  ID-2: /home size: 622.48 GiB used: 90.57 GiB (14.5%) fs: ext4 
  dev: /dev/sdb1 
  ID-3: swap-1 size: 8.18 GiB used: 701.0 MiB (8.4%) fs: swap dev: /dev/sda3 
Sensors:
  System Temperatures: cpu: 92.0 C mobo: N/A sodimm: 48.0 C 
  Fan Speeds (RPM): cpu: 4302 
Info:
  Processes: 210 Uptime: 8h 28m Memory: 3.72 GiB used: 2.29 GiB (61.7%) 
  Init: systemd Compilers: gcc: 8.2.1 Shell: bash v: 4.4.23 inxi: 3.0.28 
```

**Comment by Tyriar** [comment]
@jamesray1 what version of VS Code? Could you see if it happens on the latest Insiders build? http://code.visualstudio.com/insiders

**Comment by Tyriar** [comment]
> Date: 2018-12-21T06:15:51.434Z

This is pretty old, a while ago there was a problem where an exception was thrown in core terminal code which bricked it, maybe you're seeing that? Could you update and see if it's all good now?

**Comment by jamesray1** [comment]
Hmm, I updated with `yay` yesterday and before that, not sure why it didn't update. I just ran `yay` again and it didn't install still. There is an [issue with Manjaro / systemd which seems to be related](https://forum.manjaro.org/t/stable-update-2018-12-04-systemd/67536/40?u=jamesray).

**Comment by Tyriar** [comment]
Looks like the package is out of date https://aur.archlinux.org/packages/visual-studio-code-insiders/, cc @dcelasun

FYI this isn't an official dist method.

**Comment by dcelasun** [comment]
Thanks for the ping. As I've mentioned in the pinned comment on that page, the insiders package is self-updating. Simply running `makepkg -i` in the package directory will download and install the latest insider build.

Specifically:

```sh
$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/visual-studio-code-insiders.tar.gz
$ tar -xzvf visual-studio-code-insiders.tar.gz
$ cd visual-studio-code-insiders
$ makepkg -i
```

**Comment by Tyriar** [comment]
@dcelasun sorry, didn't read down that far 😅

**Comment by jamesray1** [comment]
I made a few commits and there have been no issues so far.
