### ISSUE TITLE
Vscode very slow when debugging javascript (macOS)

### ISSUE THREAD

**Issue by linvi** [Microsoft/vscode#66136]
- VSCode Version: 1.30.1
- OS Version: MacOS Sierra 10.12.6

This problem started to appear in November update.

Steps to Reproduce:

1. Start debugging a node process
2. Perform any operation on one of the file open in vscode (scrolling, navigating)
3. The UI becomes totally unresponsive. Any operation takes 5/10/20 seconds. The opened `window` process takes all the CPU as shown on screenshot below.

![image](https://user-images.githubusercontent.com/6107439/50761249-cce1f980-1261-11e9-8533-a56217a69cf5.png)

Does this issue occur when all extensions are disabled?: 

> No as it comes when node debugger is running.

## Notes

* I tried to reinstall vscode without success.
* As soon as I stop debugging vscode gets back to normal.

**Comment by weinand** [comment]
How does your debug configuration (launch.json) look like?
