### ISSUE TITLE
set scope for TS -> Inject Service

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#66135]
Can we set the scope for the TS -InjectService / Event snippets to TypeScript ?

They show up when editing JSON...
![image](https://user-images.githubusercontent.com/6461412/50760317-b343b080-1267-11e9-84d8-a215430612af.png)

https://github.com/Microsoft/vscode/blob/ac39335c816fe2f665e947138dd74b5a5b3147d1/.vscode/shared.code-snippets#L25

**Comment by jrieken** [comment]
True - funny that no one had seen this before...
