### ISSUE TITLE
Can't open deletion and addition merge conflicts

### ISSUE THREAD

**Issue by lucasyvas** [Microsoft/vscode#6613]
- VSCode Version:

1.1.1
- OS Version:

Windows 7

Steps to Reproduce:
1. Initiate a pull rebase or sync (we use git config --global pull.rebase true)
2. If there's a file merge conflict, it's displayed in the merge conflicts, but single clicking won't open the file to show differences.

Workaround:

Right click the file in merge conflicts, then pick open file (show file?). Not at work right now so I'm not sure which menu option will open it, but you can pick one that will open it and show the merge conflict information, fortunately.

**Comment by joaomoreno** [comment]
I cannot reproduce, seems to work for me.

Was your conflicted file also moved among those commits? Can you reproduce? If so, can you provide a sample repository where I could reproduce it too?

**Comment by vasametropolis** [comment]
I may not be able to provide a sample repo because we are using GitHub enterprise and I'm not allowed. I will, however, try to find time to reproduce it today and hopefully offer more details.

**Comment by vasametropolis** [comment]
We've been swamped, but I finally got a screenshot. Just did a pull rebase from our upstream and I can't open the merge conflict by single clicking the file or right clicking and choosing 'Open Change'. If I select 'Open File', it's fine

![capture](https://cloud.githubusercontent.com/assets/3365616/15591814/2a03d994-2354-11e6-8a12-44578d32b329.PNG)

**Comment by joaomoreno** [comment]
Ok, will rename the issue accordingly.

**Comment by egucciar** [comment]
I just had a similar issue. I made some changes (no deletions) to a commit. I then tried to do a pull --rebase in VSCode terminal. Though i had deleted no files, every one of the files i had touched in my commit appeared as deleted. This is not the first time ive witnessed this and i was dumbfounded. But i aborted the rebase and ran the same command from Powershell and it worked without a hitch.

I just tried to take a screenshot of the terminal, but there was another bug in the terminal and it jumped and now it is gone. What happened was, i got the error "please stash these changes as they will be overwritten by merge" on the few files i had added in the commit. I had no working changes when i initiated the rebase :/

Its strange, and I could probably reproduce it if desired by checking out the reflog and trying it again. Any notes you want me to take?

**Comment by joaomoreno** [comment]
Moving forward to #24919

**Comment by cpamp** [comment]
I am getting some errors when trying to open files in the "conflict" state from supporting extensions. Opening the file in staged changes (with the conflict markers) also throws this error but the extension displays a message and the file is shown.

**Comment by Mike-Now** [comment]
The issue still occurs for me in version 1.17.2 on fedora 25.
