### ISSUE TITLE
Provide a way to continue a rebase if there are merge conflicts

### ISSUE THREAD

**Issue by lucasyvas** [Microsoft/vscode#6614]
- VSCode Version:

1.1.1
- OS Version:

Windows 7

Steps to Reproduce:
1.  Pull rebase
2.  If there's a merge conflict, you can resolve it but are stuck after that. Have to go to the command line to continue the rebase.

This seems like half feature request and half 'bug'. If pull rebase is an option, you should be able to make it through the rebase within the editor even if there's a merge conflict.

**Comment by chadbr** [comment]
this one drives me crazy... happens toooo often :/

**Comment by joaomoreno** [comment]
Me too buddy. 😢 

We gotta fix this soon.

**Comment by kvanlaan** [comment]
Pleas fix this.

**Comment by Speedkore** [comment]
it's amazing how such an important thing is still unavailable after 2 years, leaving people stuck every day. The only thing that comes to my mind is that vscode developers don't use vscode git integration at all.

**Comment by lucasyvas** [comment]
I feel like creating a cohesive GUI experience for git is a fool's errand.

I've since drastically reduced the time spent using git in the editor. It's great for basic pulls and merges, and creating and publishing branches.

Besides that it's basically unusable, and I don't know if I can really fault the team too much here. There are 9 billion different use cases and problems that can arise.

**Comment by Speedkore** [comment]
I understand that are many possible cases, but it won't hurt to be able to rebase continue/skip/abort from a simple mouse click, and people could finish the resolve conflict sequence without typing commands in most cases.

**Comment by nekwebdev** [comment]
Please this a million times

**Comment by MatdeB-SL** [comment]
As of 1.26.0 or 1.26.1, clicking commit will do a `rebase --continue` if a rebase is underway. 

The below code from [repository.ts](https://github.com/Microsoft/vscode/blame/master/extensions/git/src/repository.ts) demonstrates it

```
async commit(message: string, opts: CommitOptions = Object.create(null)): Promise<void> {
		if (this.rebaseCommit) {
			await this.run(Operation.RebaseContinue, async () => {
				if (opts.all) {
					await this.repository.add([]);
				}

				await this.repository.rebaseContinue();
			});
		} else {
			await this.run(Operation.Commit, async () => {
				if (opts.all) {
					await this.repository.add([]);
				}

				await this.repository.commit(message, opts);
			});
		}
```

**Comment by kaflan** [comment]
In mac i problem too

**Comment by chadbr** [comment]
@MatdeB-SL can't wait to check it out!

**Comment by kvanlaan** [comment]
Cool!

**Comment by joaomoreno** [comment]
This has been fixed!

**Comment by schollii** [comment]
> As of 1.26.0 or 1.26.1, clicking commit will do a `rebase --continue` if a rebase is underway.
> ...

In 1.27.1 can see in the SCM view, there is a hash and then the word "rebasing", but I'm not seeing anywhere a way to continue the rebase.

**Comment by joaomoreno** [comment]
Once you commit in the viewlet, `git rebase --continue` will be executed instead of `git commit`.

**Comment by schollii** [comment]
I'm not seeing a way to commit. This is what I mean: I do a git rebase from command line (bash on ubuntu), and hits a conflict. I then go to the vs code window where the folder is open, and I can see there are conflict markers in the file. I resolve each conflict. In the Git panel on the left, I can see the file listed under Merge with a C as status, this becomes M once all conflicts resolved. Then I can click the plus and a commit seems to occur as the file disappears from the Merge. But a continue does not happen, there is nothing under Commit, and there is no option to do rebase continue. So I have to go back from the command line and type rebase --continue and repeat the above steps until rebase completes.

**Comment by joaomoreno** [comment]
> Then I can click the plus sign on the file, and the file disappears from the Merge (perhaps a commit occurs then?).

If this happens, you resolved the conflicts in a way that a commit isn't necessary, eg: picked all changes from the same side.

It's a valid issue, I've created #60149
