### ISSUE TITLE
JSDoc does not generate parameters description when function is assigned to object property not in object initialization.

### ISSUE THREAD

**Issue by Dzenly** [Microsoft/vscode#66142]
For this code:
```js
exports.asdf = function asdf(a, b) {
};
```
Automatic JSDoc creation by `/** [Enter]` does not create parameters description and creates just
```js
/**
*
*/
```
For these cases, JSDoc works correctly:

```js
function asdf(a, b) {
}

const asdf = function asdf(a, b) {

}

const a = {
  func(a, b) {

  }
}
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.18.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 985)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.34GB (2.13GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

I know about https://marketplace.visualstudio.com/items?itemName=joelday.docthis
but I don't wish to use hotkey for this. Also this plugin has a hell lot of issues.

**Comment by mjbvz** [comment]
Thanks. This is already tracked by https://github.com/Microsoft/TypeScript/issues/27638
