### ISSUE TITLE
Cannot use Shift+Alt+F to format TS file

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#66140]
Steps:
* open a TS file
* press Shift-Alt-F
* this ends up focusing the search input in the search viewlet

---

Looks like there is a new keybinding that we are shipping with which ends up blocking the keybinding for formatting:

![image](https://user-images.githubusercontent.com/5047891/50763995-b5127180-1271-11e9-939e-5b4df13ebbdc.png)

Looks like it came in via https://github.com/Microsoft/vscode/pull/61526

**Comment by roblourens** [comment]
Thanks, didn't realize this applied when the explorer is not focused.
