### ISSUE TITLE
The vs code is not runing without the internet

### ISSUE THREAD

**Issue by ammarfahad** [Microsoft/vscode#66147]
Issue Type: <b>Performance Issue</b>

After updating the Windows 10 to version 1809, VS-Code is not runing without the internet. Many of the users is facing this problem, please fix this as soon as possible. Looking forward to the reply.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.86GB (8.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    91	  6252	code main
    2	   147	    68	   window (Visual Studio Code)
    0	    66	  8260	     extensionHost
    0	    76	  7260	   shared-process
    0	   116	 11716	   gpu-process
    0	    69	 12104	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|1.9.5

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
