### ISSUE TITLE
Type annotations are incorrectly labelled as variables in TM scopes

### ISSUE THREAD

**Issue by Foxhoundn** [Microsoft/vscode#66149]
- VSCode Version:  1.30.1
- OS Version: 10.14

Steps to Reproduce:

1. Create a theme and assign color to `variable.other.readwrite`
2. Create a function with enough parameters for the function to be broken to multiple lines

![screenshot 2019-01-07 at 15 21 54](https://user-images.githubusercontent.com/8861481/50773238-9b345700-1290-11e9-9fb4-c6ed0eb6ad8c.png)

It works fine if at least **one** of the parameters is inline

![screenshot 2019-01-07 at 15 27 58](https://user-images.githubusercontent.com/8861481/50773320-d6368a80-1290-11e9-99ea-f3822c088f79.png)

Also! The `async` modifier is labelled as function call, which is incorrect as well.

![screenshot 2019-01-07 at 15 30 46](https://user-images.githubusercontent.com/8861481/50773500-4cd38800-1291-11e9-9372-3124f0435401.png)
![screenshot 2019-01-07 at 15 31 14](https://user-images.githubusercontent.com/8861481/50773501-4d6c1e80-1291-11e9-9229-6c44a642c2d6.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Foxhoundn** [comment]
Another occurrence of this bug.

![screenshot 2019-01-08 at 11 52 40](https://user-images.githubusercontent.com/8861481/50826455-f707ea00-133b-11e9-9fce-a8831c74f18f.png)

**Comment by Foxhoundn** [comment]
> Please share the text of the code along with all screenshots

For obvious reason I can't share all of the code but here's the whole function - 

```javascript
const fetchOrders = createAction(
  'ORDERS_FETCHORDERS',
  async (
    id: number,
    fetchMore: boolean,
    offset: number,
    date: string,
    filter: string,
    limit: number,
    sortDir: boolean,
    sort: string,
    searchData: Object
  ): Object => {
    let url: string;
    const status: string = !filter || filter === 'filter' ? '' : filter;

    if (!id || id === 'id') {
      const maxDate: string = searchData.maxDate || '29991231';
      const sendDate: boolean = !(searchData.ids || searchData.keyValue);

      url =
        `${settings.REST_BASE_URL}/orders?` +
        `ids=${searchData.ids || ''}&` +
        `date=${!sendDate ? '' : searchData.minDate}&` +
        `maxmodified=${!sendDate ? '' : maxDate}&` +
        `keyname=${searchData.keyName || ''}&` +
        `keyvalue=${searchData.keyValue || ''}&` +
        `status=${status}&` +
        `sort=${sort}&` +
        `desc=${sortDir.toString()}&` +
        `offset=${offset}&` +
        `limit=${limit}`;
    } else {
      url =
        `${settings.REST_BASE_URL}/orders?` +
        `workflowid=${id}&` +
        `date=${date}&` +
        `status=${status}&` +
        `sort=${sort}&` +
        `desc=${sortDir.toString()}&` +
        `offset=${offset}&` +
        `limit=${limit}`;
    }

    const orders: Array<Object> = await fetchJson('GET', url, null, true);

    return { orders, fetchMore };
  }
);
```

It occurs even if this is the only code in the file.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/705 to track this upstream

**Comment by gerroon** [comment]
Any word on this? This is really annoying :( 

See https://www.python.org/dev/peps/pep-0526/
