### ISSUE TITLE
When typing, sometimes the cursor position will fall back by one character position.

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#66144]
Issue Type: <b>Bug</b>

This problem is similar to #747, but my problem is that the intentional or unintentional cursor automatically returns to the position of the previous character and cannot be correctly positioned.

![error](https://user-images.githubusercontent.com/13393959/50770681-19a9ec80-12c3-11e9-9b54-c308e109eee5.gif)

VS Code version: Code - Insiders 1.31.0-insider (28e7467661d67c05c3662ff900ee1984f7e2fbcc, 2019-01-07T06:20:02.775Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.3.3
ng-template|Ang|0.1.11
masm|blt|0.0.3
path-intellisense|chr|1.4.2
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
microsoft-translate-ext|dig|0.1.5
gitlens|eam|9.3.0
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
vscode-todo-plus|fab|4.11.2
code-runner|for|0.9.5
vscode-pull-request-github|Git|0.3.2
rest-client|hum|0.21.0
apiconnecttools|IBM|0.0.5
ibm-developer|IBM|0.0.14
output-colorizer|IBM|0.1.2
XMLLanguageSupport|IBM|0.0.1
ibm-blockchain-platform|IBM|0.1.0
ionic-preview|ion|0.0.18
Angular2|joh|7.0.1
ibm-assembler|kel|0.2.0
uncrustify|Lau|2.13.5
javascript-test-runner|leg|1.0.0
Angular-BeastCode|Mik|7.0.28
vs-rest-api|mkl|3.0.1
vscode-language-pack-zh-hans|MS-|1.30.2
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
github-issues-prs|ms-|0.9.1
Go|ms-|0.8.0
js-atom-grammar|ms-|0.1.14
PowerShell|ms-|1.10.2
typescript-javascript-grammar|ms-|0.0.47
vscode-typescript-tslint-plugin|ms-|0.3.0
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
material-icon-theme|PKi|3.6.2
platformio-ide|pla|1.6.0
quantum-devkit-vscode|qua|0.3.18112802
java|red|0.36.0
vscode-xml|red|0.2.0
vscode-yaml|red|0.2.0
rust|rus|0.5.3
scala|sca|0.2.0
scala-snippets|sca|0.1.0
bootstrap4-vscode|the|6.0.3
vscode-arduino|vsc|0.2.24
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.13.0
vscode-react-native|vsm|0.7.0
quokka-vscode|Wal|1.0.175
bootstrap-v4-snippets|Zac|0.1.7

(3 theme extensions excluded)

</details>

**Comment by egamma** [comment]
@czfadmin can you reproduce the issue when you have all extensions disabled ([issue reporting guidelines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions))?

**Comment by czfadmin** [comment]
@eamodio ,sorry, this problem does not occur when I disable all extensions, so it should be caused by a plugin that has been installed.

**Comment by egamma** [comment]
@czfadmin then you should try to selectively disable an extension in the Extensions Viewlet to identify the extension and then please file an issue against this extension.
