### ISSUE TITLE
Turn on conpty by default for Windows Insiders

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#66158]
Need to fix kill bug first

**Comment by Tyriar** [comment]
https://github.com/Microsoft/node-pty/issues/253

**Comment by Tyriar** [comment]
I'm setting the default to false for the v1.31 because of a bad performance issue in Windows Insiders right now, we can probably switch it on for 1.32 unless something like this happens again.

**Comment by ghiscoding** [comment]
I'm on the Slow Ring and there are still no insiders build available yet for 19H1. I suggest to wait for at least Slow Ring to be at the minimum 18309 that you mentioned, mine is 17xxxx something
