### ISSUE TITLE
Debugging errors in the console aren't refreshed when debugging the second time

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#66157]
From 
https://github.com/Microsoft/vscode-go/issues/2118#issuecomment-451383018 by @mvrhov 

> I get the output in debug console only when the first error happens. Each further error displays the old error message.
The test would be create a simple file with 2 errors, try to run it with F5... correct one error, pres F5 to run.. old error message remains in debug console. VScode restart is required to see the next error message

From 
https://github.com/Microsoft/vscode-go/issues/2118#issuecomment-451832599 by @ramya-rao-a 

> Clearing the debug console before debugging a second time also results in showing the next error message.

@isidorn This is probably related to 
https://github.com/Microsoft/vscode/issues/61986 and 
https://github.com/Microsoft/vscode/issues/63114. Any idea if this is a known issue?

**Comment by ramya-rao-a** [comment]
VS Code version 1.28 works as expected.
VS Code version 1.29 had the issue of no errors showing up in the debug console
VS Code version 1.30 and Insiders 1.31 (as of today) as the bug currently being described in this issue

**Comment by isidorn** [comment]
@ramya-rao-a how does go write errors to the debug console?
In step 3 when debugging fails do you actually see a drop down of multiple debug consoles?
Does switching the active debug console actually show the error? Is the actual issue that the new debug console does not get focus becuase the session failed?

**Comment by ramya-rao-a** [comment]
> how does go write errors to the debug console?

This particular error is sent via the `sendErrorResponse()` in the `launchRequest()` call

> In step 3 when debugging fails do you actually see a drop down of multiple debug consoles?


No, I don't see any drop down for multiple debug console

> Does switching the active debug console actually show the error? Is the actual issue that the new debug console does not get focus becuase the session failed?

This assumes that there are multiple debug consoles, but I don't see more than 1.

**Comment by ramya-rao-a** [comment]
![debug](https://user-images.githubusercontent.com/16890566/50921306-883e9580-13fc-11e9-80c2-ce80c474d446.gif)

**Comment by isidorn** [comment]
I do not have go installed and I can not repro this with node.
So either try to create a reproducable sample with Node debugging or set the breakpoint [here](https://github.com/Microsoft/vscode/blob/a55fd35137c246f8ba756e871ace362db5d57998/src/vs/workbench/parts/debug/electron-browser/repl.ts#L136) and [here](https://github.com/Microsoft/vscode/blob/a55fd35137c246f8ba756e871ace362db5d57998/src/vs/workbench/parts/debug/electron-browser/repl.ts#L140) and try to figure out why your new session is not being selected.
