### ISSUE TITLE
Implement proper JS layout for settings editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#66151]
From https://github.com/Microsoft/vscode/issues/65981

I've found a couple of problematic things with how the DOM is laid out in the settings editor, which I suggest to fix asap:

1. The `settings-toc-container` and `settings-tree-container` elements, both children of `settings-body` seem to take both full height and width of its parent. We should use a layout scheme there and have them side-by-side. Flex or simple block layout would be sufficient.
2. Because of (1), the settings editor is [overriding internal tree/list CSS rules](https://github.com/Microsoft/vscode/blob/ff157f90a0604521b552afaa41dd8ce9a2e468dd/src/vs/workbench/parts/preferences/electron-browser/media/settingsEditor2.css#L116:L142) just to position and size both lists/trees as you want them to be. This is a big no no. By fixing (1), all these rules become obsolete.
3. The [wrong width is passed along to the settings list](https://github.com/Microsoft/vscode/blob/ff157f90a0604521b552afaa41dd8ce9a2e468dd/src/vs/workbench/parts/preferences/electron-browser/settingsEditor2.ts#L1192). It should be the width of the whole container (up to 1000px) minus the width of the overview tree. Something like `dimension.width < 600 ? dimension.width : Math.min(dimension.width, 1000) - 160`.

**Comment by joaomoreno** [comment]
My intuition tells me that the issue in which the list gets incorrect results from height measurements in the settings editor will also be fixed with this issue:

![screenshot cpma1u](https://user-images.githubusercontent.com/22350/50773601-8efcc980-1291-11e9-81f2-fe44ef7ae021.png)

**Comment by jamesgeorge007** [comment]
@joaomoreno I would like to work on this 👍 
I'm not that comfortable with the `vscode` codebase. It would be great if you could guide me on resolving this issue.

**Comment by joaomoreno** [comment]
@jamesgeorge007 Please look for `help wanted` and `good first issue` issues. More info: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#contributing-to-code

**Comment by roblourens** [comment]
The reason for the weird layout is that we want the scrollable area of the settings tree to cover the whole area of the settings editor under the TOC tree so I can put the cursor in the margin and scroll. Also we want the scrollable element's shadow to cover just the width of the middle part over the TOC and settings tree. The scrollable element is inside the settings tree, and I had to get creative to accomplish this and also keep the content centered and layed out properly. I think this probably isn't  possible without some level of hacks. I'll check out why I'm passing the wrong width.

**Comment by joaomoreno** [comment]
I see, makes sense. It's actually pretty cool once one sees it.

Since we have the `ScrollableElement` and friends we could probably still do that by listening to the events at the right place and just forwarding them to the settings tree dom node. As for the shadow we'd need to disable the shadow on the settings tree and implement a new shadow on the parent element.

**Comment by roblourens** [comment]
That seems hackier than just laying out the tree in a way such that it can be scrolled normally?

**Comment by joaomoreno** [comment]
Yeah, I can definitely see arguments going both ways.

My viewpoint is one based on composition. A widget's CSS should be the sole responsibility of the widget itself. If an outer container is overriding an inner widget's CSS rules, then that would be crossing a boundary and should be implemented as a widget feature instead. This is especially crucial in virtual widgets such as the list and tree and with properties which change positioning and sizing.

I would approach it by creating the following composition:

- Virtual scrolling container (shadow, scroll events get forwarded to the List as `scrollTop` property changes)
  - TOC tree
  - List (shadow disabled)

This creates a clear 3 widget structure, each minding its own responsibilities. There wouldn't need to be any CSS overrides and all interacting between the widgets would happen at each widget's API layer.

In any case, you might just want to fix the issue of #65981. If you're not convinced to refactor this then just do a double check on the width measurements you're passing to the list and if the height issue from #65981 is fixed by that then we're good to go. 👍

**Comment by roblourens** [comment]
I agree with what you say in principle but I'm not sure how to make it work nicely in practice - if we have to do this:

> scroll events get forwarded to the List as scrollTop property changes

that has the same issue as https://github.com/Microsoft/vscode/issues/66237 which is that we have to figure out how far to scroll ourselves, implement smooth scrolling and so on, and it will look different if you are scrolling directly over the list vs scrolling over the margin.

I will try it out because simplifying the CSS here would be 👌. And I do still need to check the layout measurements.

**Comment by joaomoreno** [comment]
Sounds great! :+1:

**Comment by roblourens** [comment]
I think the simplest solution would be just to keep the layout similar to the way it is now but avoid touching the list's own styles. Put the centering and extra padding styles inside each row element's content. Also would have to have styles for the scrollable element's shadows but that seems ok. Simpler than trying to put the scrollbars and shadows outside of the scrollable element's structure.

**Comment by roblourens** [comment]
I implemented that, I think the only styles that might step on the tree are these

https://github.com/Microsoft/vscode/blob/c064781f92ddac447a24cbd4df88f0a61c9a2006/src/vs/workbench/parts/preferences/electron-browser/media/settingsEditor2.css#L263-L268

I don't think I can work around them right now, but if you think they are problematic we can try to do something about that.

**Comment by roblourens** [comment]
So the validation messages can overflow the row:

![image](https://user-images.githubusercontent.com/323878/52353216-edc57800-29e2-11e9-9e2f-9e66814ec5f0.png)

**Comment by joaomoreno** [comment]
Dammmnnn!
