### ISSUE TITLE
Context menu 'Find all references'  on files from file explorer.

### ISSUE THREAD

**Issue by Dzenly** [microsoft/vscode#66150]
There was an issue, but its status is unclear.

https://github.com/Microsoft/vscode/issues/6625
I am surprised why there are so little likes %)

Cases:
* Node.js/JavaScript - all places where the current file is required by `require`.
BTW: if I use "Find all references" on `require('./some-file.js') - VS Code does show me them. So the ability itself is already supported but there is no interface in file explorer.

* Node.js/TypeScript - all places where the current file is imported.
* C++ - all places where the file is included.
* Which HTML uses the current JS file.
* Etc.

For many years I used WebStorm which supports this. But in VS Code I have no idea how to find the place where some file is used but global searching it by some regexp. I was looking for some plugins and workarounds for 2 hours and found nothing %).

I tried to bind shortcut:
```json
  {
    "key": "f12",
    "command": "references-view.find",
    "when": "filesExplorerFocus"
  }
```
but it runs last references search and not search for current file.

There is a question on SO, but no answer:
https://stackoverflow.com/questions/53267307/how-to-find-all-references-of-a-selected-module-in-vs-code

**Comment by alexilyaev** [comment]
@Dzenly Was there any progress on this?

For me, in simple ES6 code with `export` and `import` in several files, there's no way to find the references.

If I right click the `export`ed symbol and click `Find All References`, it will only find references in the open files in the editor, which is not so useful.

**Comment by RVisionAutomerge** [comment]
@alexilyaev I don't know. Mainly I use WebStorm, and from time to time I try VS Code, report another feature request, and continue to use WebStorm.

**Comment by Dzenly** [comment]
@alexilyaev I don't know. Mainly I use WebStorm, and from time to time I try VS Code, report another feature request, and continue to use WebStorm.
