### ISSUE TITLE
Extension Guide by spywhere

### ISSUE THREAD

**Issue by getcodetony** [Microsoft/vscode#66156]
Apparently, this extension Guide by spywhere is causing this issue.

When i installed this extension, vs code prompt me this notification:
<Guides extension has detected that you are using "editor.renderIndentGuides" settings. Guides will now disable all indentation guides by override the style to "none".> It also give me the options to continue to use Guide or use the built in indentation of vs code.

I do not know what to choose and try to click on the built in. Then i decided to uninstall the extension. However, the guide is still active in my files even though i have uninstalled it. I can't remove the guide lines now. 

Any advice on how to go back to the default settings of having no guidelines? We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by usernamehw** [comment]
```json
"editor.highlightActiveIndentGuide": false,
```

**Comment by RMacfarlane** [comment]
If you open the settings page, there is a dropdown of more actions at the top:

![screen shot 2019-01-07 at 10 24 04 am](https://user-images.githubusercontent.com/3672607/50785849-a96d7d80-1266-11e9-95ad-86d2cdbee82c.png)

From there you can choose "Show modified settings" to see all of your settings that have been changed from default values, and then by hovering over them, select the gear and choose "Reset setting".

You can also run the command "Preferences: Open Settings (JSON)" to view your settings JSON file, which should only have entries for settings you or an extension have modified.
