### ISSUE TITLE
Please add support for Qt QML

### ISSUE THREAD

**Issue by TheIndifferent** [Microsoft/vscode#6615]
QML syntax is very simple, JSON-like, with some JavaScript support. Hopefully this is a trivial thing to add but with obvious benefits.

http://doc.qt.io/qt-5/qmlreference.html

**Comment by coooooooooorey** [comment]
https://github.com/bbenoist/vscode-qml

**Comment by chrisdias** [comment]
per @coooooooooorey this would be an extension, closing.
