### ISSUE TITLE
Vue-CLI requires a "npm run serve" to run before i can launch a "chrome" session.

### ISSUE THREAD

**Issue by tuath** [Microsoft/vscode#66160]
Using ng-cli or vue-cli requires something like : npm run serve or npm start...

It would be nice if there were a way to create a tasks.json item that would, upon workfolder opening, automatically launch a npm run serve task so that way can quickly get going.

It's sad i have to "npm run serve" everytime i restart developping (and had closed stuff on my laptop).

**Comment by alexr00** [comment]
I think that the new task run option will do exactly what you want here. https://code.visualstudio.com/Docs/editor/tasks#_run-behavior
Check out the `runOn` property. You can use that to create a task that runs when you open the folder.

**Comment by tuath** [comment]
It's an interesting idea and works, but since I do git pulls from vs code and that might affect a lot of local files, i am not sure that running when vs code opens the workspace is the best.

I have tried adding invoking the task from my launch configuration using (prelaunchTasks) but this mechanism doesn't seem to work with tasks that are basically watchers.

If DotNetCore could recompile as source code changed, it woudl basically require a watcher of some sort. Would the build process for DotNetCore be updated to put a watcher in the build task or the launch process ? 

I think this is the right mecanism to be extended...

Being able to define a few "watcher" tasks for a given launch configuration. That way i could have a Chrome launch configuration and start my watcher task at launch.

**Comment by alexr00** [comment]
You can use a watching (background) task as a prelauncTask. You just need to make sure that it has a background problem matcher too: https://code.visualstudio.com/Docs/editor/tasks#_background-watching-tasks

**Comment by tuath** [comment]
Hi Alex, i appreciate this whole "you could do this or that", but i still think that the overall use case i am trying to achieve isn`t resolved.

I can launch my watcher using a background task from a launch config prelauncTask, but i get this error 👍 
The specified task cannot be tracked.

My launch config looks like this :
      {
           "type": "chrome",
           "request": "launch",
           "name": "Launch TDS Info",
           "url": "http://localhost:8088",
           "webRoot": "${workspaceFolder}/TDS.Web",
           "breakOnLoad": true,
            "sourceMapPathOverrides": {
                "webpack:///./src/*": "${webRoot}/*"
            },
            "preLaunchTask": "npmServe",
       }

And my task like this :
        {
            "label": "npmServe",
            "type": "shell",
            "command": "npm",
            "args": ["run", "serve"],
            "options": {
                "cwd": "${workspaceFolder}/TDS.Web"
            },
            "problemMatcher": {
                "owner": "vue-cli",
                "fileLocation":"relative",
                "pattern":{
                    "regexp": "^([^\\s].*)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\):\\s+(error|warning|info)\\s+(TS\\d+)\\s*:\\s*(.*)$",
                    "file": 1,
                    "location": 2,
                    "severity": 3,
                    "code": 4,
                    "message": 5
                },
                "background": {
                    "activeOnStart": false,
                    "beginsPattern": "qwer",
                    "endsPattern": "adsf"
                }
            },
            "isBackground": true
        }


Once we figure this out i will definatly blog about it, after searching it i seem to be the only guy on earth trying this out...

**Comment by alexr00** [comment]
It looks like the `beginsPattern` and `endsPattern` in the problemMatcher don't match the start and stop text that the npm command use. When the `endsPattern` occurs is when the pre launch task is considered to be "done" so that part is important. 

Regarding this not really solving your use case: We do have a feature request for not having to define a problem matcher for your task and instead only defining the `beginsPattern` and `endsPattern`. https://github.com/Microsoft/vscode/issues/6209.
