### ISSUE TITLE
Preview issue from bot duplicated comment

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#66163]
Issue Type: <b>Feature Request</b>

Current message does not show info on hover:

* [Extension search for "vue" is abysmal (#65987)](https://www.github.com/Microsoft/vscode/issues/65987)

You can just remove `www.` and have a fully working hovercard:

```diff
- [Extension search for "vue" is abysmal (#65987)](https://www.github.com/Microsoft/vscode/issues/65987)
+ [Extension search for "vue" is abysmal (#65987)](https://github.com/Microsoft/vscode/issues/65987)
```

* [Extension search for "vue" is abysmal (#65987)](https://github.com/Microsoft/vscode/issues/65987)

**Comment by roblourens** [comment]
Seems like github should fix that...

**Comment by chrmarti** [comment]
Including `www.` avoids GitHub's backlinking from the referenced issues which would be too noisy. Closing `as-designed`.
