### ISSUE TITLE
Node and Chrome DA localization does not work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#66164]
- Change display language and install appropriate language pack
- The easiest way to see a message from the DA that should be localized is to break the config. e.g open the vscode repo, pick one of the launch tasks, and change `runtimeExecutable` to a path that doesn't exist.
- Run that launch config
- See that the error message is in English.

FYI @weinand @dbaeumer

**Comment by dbaeumer** [comment]
In dev mode it doesn't have an argument. When we produce the produce there is some JS rewriting happening which injects `__filename` as an argument. So localization and language pack only work in the product. Not when running from dev or when developing an extension.

**Comment by roblourens** [comment]
It doesn't work in the product either.

**Comment by dbaeumer** [comment]
@weinand did quite some work to get this working for his debug adapter. Anything you can share. I also remember discussion with @jrieken about difficulties with debug in case it is web packed and uses a dependent npm package that should be localized.

**Comment by roblourens** [comment]
That could be the case for node-debug but node2/chrome are not webpacked yet.

**Comment by roblourens** [comment]
This is still an issue and I don't know what to do about this?

![image](https://user-images.githubusercontent.com/323878/53305775-45b10b00-383a-11e9-8003-3d01bc0c7fca.png)

**Comment by roblourens** [comment]
> When we produce the produce there is some JS rewriting happening which injects __filename as an argument. So localization and language pack only work in the product. Not when running from dev or when developing an extension.

Where is this supposed to happen?

**Comment by dbaeumer** [comment]
During the product build. For debugger adapters this should happen during the `gulp build` execution. Are these adapters using Language Packs or still the old `nls.bundle` format. If the second you might see: https://github.com/microsoft/vscode-nls/issues/23

**Comment by roblourens** [comment]
I use `nls.bundle` and I installed the new vscode-nls and I pass the new `bundleFormat` option and run a product build but it's still not working.

**Comment by roblourens** [comment]
I see that `__filename` is injected, I'll debug it...

**Comment by roblourens** [comment]
Ok I have to use the new bundleFormat option and also call `nls.config` __before__ importing other files. Otherwise they will try to load their bundles before that option has been set, is that expected? I don't think that was the case before.

Also, VS sends the locale as an initialize arg, so we call `nls.config` again from initialize. I am pretty sure this won't work either because it seems like setting the locale dynamically won't cause the loc bundles to be reloaded.

**Comment by dbaeumer** [comment]
You can also go back to the 2.x version of the library which doesn't have any LP support and will only load nls.bundle. The change got introduced when we introduced LP.

You only need to call nls.config(...) once in your main file. But this has to happen before you do any imports. This was always the case in the old 2.x version :-). 

You don't need to change the locale. Even if you call `nls.config(...)` it will still consider the `VSCODE` specific env variable. 

Why are these DAs not shipping LPs?

**Comment by roblourens** [comment]
Node is in the LP and localization does actually work with node. Not sure what I saw in January. I just have issues with Chrome now. I think that doesn't belong in the LP because it doesn't come with vscode.

Anyway I can update this to work with chrome-debug but I think it will still not work with VS. 

> Even if you call nls.config(...) it will still consider the VSCODE specific env variable.

If I remember correctly, VS doesn't set this env variable but can only send the locale over later, that's why I get a 'locale' parameter from the initialize step and call config there. That worked at some point, I assume.

**Comment by dbaeumer** [comment]
Just to understand: the code is running a debug adapter that might not be spawned from VS Code? Otherwise the `VSCODE_NLS_CONFIG` should be present.

**Comment by roblourens** [comment]
Correct, it also runs in VS. We added the second `config` call awhile back at their request.

**Comment by roblourens** [comment]
My point is that if it doesn't work when config is called later, then that's a problem for VS and we should fix it so that it will work.

**Comment by dbaeumer** [comment]
> My point is that if it doesn't work when config is called later, then that's a problem for VS and we should fix it so that it will work.

I am not understanding this. If the process has no `VSCODE_NLS_CONFIG` environment then you need to configure the NLS before first use. How would I know which language to use or whether something has a LP, old bundle or file format?

**Comment by roblourens** [comment]
My assumption would be that it would somehow unload the old strings and load the correct ones, once we know which language to look for. But maybe I misunderstand how this was intended to work. I'll have to check whether it is actually working in VS currently or find that old discussion from when we added that extra config step.

**Comment by dbaeumer** [comment]
How would I unload these strings. They could already be visible somewhere in the UI. There is not concept of dynamic UI switching neither in VS Code nor for any extensions.

**Comment by roblourens** [comment]
I just mean that calls to 'localize' would return strings from the new locale, and the DA or anything else would have to be aware not to call 'localize' until it's figured out what it's locale is.
