### ISSUE TITLE
Search results rendering issues

### ISSUE THREAD

**Issue by gianlucaborello** [Microsoft/vscode#66167]
- VSCode Version: Version 1.31.0-insider (1.31.0-insider)
- OS Version: Mac OS Mojave

This started just in the past few Insider releases. When I search items and then I scroll through the search results (either via the focus commands, or using the mouse), many times the rendering is messed up, like this:

![image](https://user-images.githubusercontent.com/4187028/50790497-f277fe80-1273-11e9-8cea-4908af0508d0.png)

I use the search thousands of times a day every day, and I'm positive I this just started over the past few days, and I am usually on the latest Insiders every time. I didn't change any settings on my computer, or in the editor.

**Comment by gianlucaborello** [comment]
What's interesting is that, once it happens, even if I close/open the panel, or do another search, the bad rendering will keep showing, the only workaround seems to restart the entire editor.

**Comment by roblourens** [comment]
I have seen some issues too but can't reproduce reliably. Let me know if you figure out how to get into that state...

**Comment by gianlucaborello** [comment]
What I can say is that it happens many times using the Insiders version. I have a standard large workspace (Linux kernel tree) and use search many times a day. The rendering issue happens probably at least every 10th-20th search whenever I start scrolling fast through the results (either with the mouse or via "focus next"). Then I'm forced to restart the editor/reload the window.

I unfortunately had to revert to using the stable release of Code for this bug, and, on the same workspace via exact configuration (settings, extensions, ...), it never ever happens.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/66573 was fixed, please let mw know whether you see this again after tomorrow's insiders.
