### ISSUE TITLE
Keep replace history and find/replace options in sync with find history

### ISSUE THREAD

**Issue by bgmort** [microsoft/vscode#66174]
This request applies to both the editor find/replace dialog, and the find in files panel.  Currently there is a history available for both the find fields and the replace fields, (alt+up/down).  It would be very useful if these were kept in sync, along with the match case/whole world/regex options for that search.  In other words, the find history would not just be a history of the contents of the find field, but also the replace field and the options when that search was executed.  Then when you cycle through the history in the find field, the replace field and the options are updated from the same history.

This would be extremely helpful when repeating complex regex find/replace operations, as it can be hard to dig through history finding the expression that worked, and this becomes even more difficult when you must find the right combination of a find expression and a replace expression.

**Comment by roblourens** [comment]
I don't think it makes sense to combine the histories of those two fields because they represent different types of searches in different places, and I don't usually want to mix the two up. 

Keeping the options along with the history probably makes sense, I think it has come up before but I don't think there is an issue for it.

https://github.com/Microsoft/vscode/issues/16488 will also help with that sort of scenario.

**Comment by Zarepheth** [comment]
@roblourens I can see the use case for keeping the "Find" history independent of the "Find/Replace" history; but I think the OP wanted the "Find" box and "Replace" box histories of the "Find/Replace" widget kept synchronized. (Although, having a means to chose a non-synchronized history item would be nice.)

Most of the time I perform a lot of find/replace operations with complex regular expressions, the Find and Replace texts go together, along with the other search options. Unless I am tweaking the find or replace text, it is unlikely that I would want a different find expression for the same replace expression (or vice versa).

**Comment by Zarepheth** [comment]
Where / How do we upvote?
