### ISSUE TITLE
Allow key bindings to chain commands

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6617]
Currently I think the only way to perform multiple commands in succession is to create an extension. It would be good if this was supported by keybindings.json. 

See http://stackoverflow.com/q/37009184/1156119

**Comment by Tyriar** [comment]
Suggested syntax, it also shows how useful it can be:

```js
{
  "key": "ctrl+`",
  "command": [
    "workbench.action.toggleMaximizedPanel"
    "workbench.action.terminal.focus"
  ],
  "when": "!terminalFocus"
}
```

**Comment by Tyriar** [comment]
https://marketplace.visualstudio.com/items?itemName=geddski.macros looks like a workaround for this for now.

**Comment by whitecolor** [comment]
This would be useful to have outof the box.

**Comment by usernamehw** [comment]
@Tyriar, isn't this a duplicate of https://github.com/Microsoft/vscode/issues/871 ?

**Comment by Tyriar** [comment]
@usernamehw looks like it, thanks!
