### ISSUE TITLE
Python Interactive Window / Jupyter window is always 1st or 2nd group from left and can't be permanently moved

### ISSUE THREAD

**Issue by nric** [Microsoft/vscode#66173]
Not sure if this is a bug or a missing feature:

I keep having the problem that I can not have the Python Interactive output on the third or higher group column. If I put the tab there, it jumps back to the 2nd on the next run cell. 

Quite annoying when I want to live my OCD and have the view ordered by layers for example. 

Not subject to the request/report, but at this point thank you guys a million times for making my dev life so much better with VS Code and the Python Interactive feature.

**Comment by RMacfarlane** [comment]
Hi @nric, could you include a screenshot of the UI you're talking about?

**Comment by nric** [comment]
sure, see attached. 
The middle group column is where the Pyhon Interactive output is "fixed". I want it on the right group. Putting the tab on the right group colum will be reverted once I execute the next cell.
![vscode1](https://user-images.githubusercontent.com/35203350/50799687-5551b000-12dd-11e9-935d-9de1b53811fa.png)

**Comment by RMacfarlane** [comment]
Ok, thanks! I think this is actually an issue with the extension itself, and not VSCode. It looks like someone has already reported an issue on the extension: https://github.com/Microsoft/vscode-python/issues/3808
