### ISSUE TITLE
Find all references without /index in the import path

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#66170]
I'm running into an issue where `Find All References` does not work if the import path does not include the `/index`. Is this expected? Is there a workaround available, or a fix on the way?

![references](https://user-images.githubusercontent.com/12591890/50794077-c0749580-128f-11e9-99bc-9030db1fa608.gif)

**Comment by RMacfarlane** [comment]
From the gif, it looks like you have a class `Text` in `index.js` that you're importing somewhere else. I would expect you to need to specify the complete absolute or relative path to the file to be able to import it - is there anything special about your project set up?

**Comment by RMacfarlane** [comment]
What does your `jsconfig.json` look like? Does setting the module like in https://github.com/Microsoft/vscode/issues/36699 resolve the issue?

**Comment by jabacchetta** [comment]
Yes, that did it, thanks @RMacfarlane !

Do you have any suggestions on where to read up on the specifics of why these options are required, to get a better understanding of how VSCode works behind the scenes?

In other words, I don't understand why that feature just wouldn't be baked in by default?

**Comment by RMacfarlane** [comment]
Great! There's some documentation on the `jsconfig` [here](https://code.visualstudio.com/docs/languages/jsconfig). [This](https://code.visualstudio.com/api/language-extensions/overview) has some information about language extensions in general - all built in language support is from extensions that are bundled from VSCode
