### ISSUE TITLE
Incorrect range replaced on multiple cursors when accepting suggestion

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#66180]
From https://github.com/Microsoft/vscode/issues/54586

**Steps to Reproduce:**

1. For a js file:

```js
const abc = 1
const abc123 = 1

abc
abc1234
```

1. Create two cursors: one before `abc` and one before `abc1234`. 
1. Trigger suggestions
1. Accept suggestion for `abc`

**bug**
File becomes:

```js
const abc = 1
const abc123 = 1

abc123
abc1231234;
```

**Comment by mjbvz** [comment]
@jrieken Adding you since the TS extension now sets the replacement range to cover the entire word for the case:

```ts
|abc
```

For `|abc1234` however, it looks like the same range is being re-used. I'm not sure if or how we can support multi-cursors for custom ranges like this

**Comment by jrieken** [comment]
Yeah, that's the designed behaviour as we only ask for the primary curser and try to make it work for secondary cursors. Also not sure what to do here, esp when a range is given...
