### ISSUE TITLE
URL containing + not properly detected in integrated terminal

### ISSUE THREAD

**Issue by aarongable** [Microsoft/vscode#66182]
Steps to reproduce:
**1)** Open the integrated terminal
**2)** Run a command whose output includes a url which contains a "+". For example:
```
$ git push gerrit
remote: Processing changes: refs: 1, new: 1, done
remote:
remote: SUCCESS
remote:
remote: New Changes:
remote:   https://chromium-review.googlesource.com/c/chromium/src/+/1399451 Make install-build-deps more obvious in docs [WIP]
To https://chromium.googlesource.com/chromium/src
 * [new branch]                53883d70c2460778176a32b07297ba7ab43d690f -> refs/for/refs/heads/master
```
**3)** Try to ctrl+click the link which contains a +

Expected result:
**4)** The whole url is detected

Actual result:
**4)** Only the url up to but not including the + is detected. The rest ("+/1399451") is ignored.

![screenshot](https://user-images.githubusercontent.com/2474926/50799159-c8ccd080-128f-11e9-8ecb-1750210edea4.png)

**Comment by Tyriar** [comment]
Merged into https://github.com/Microsoft/vscode/issues/21125
