### ISSUE TITLE
JS/TS completion sometimes replaces next character as well

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#66187]
Issue Type: <b>Bug</b>

**repo**
1. For the js file:

```ts
,null
```

1. Put cursor before the `,` and type `u` and then `n` very quickly
1. Press enter to accept `undefined` suggestion

**Bug**
Sometimes the `,` is also replaced, resulting in:

```js
undefinednull
```

VS Code version: Code - Insiders 1.31.0-insider (28e7467661d67c05c3662ff900ee1984f7e2fbcc, 2019-01-07T06:12:49.904Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_962795|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by mjbvz** [comment]
@jrieken I think there may be a race condition with suggests and document edits here.

After recent change, TS now calls `getWordRangeAtPosition` inside of `provideCompletionItems` in order to compute the range of completion items. Here's what I believe happens in the buggy case:

1. User types `u` and then `n` very quickly
1. Completions are triggered on the `u`
1. The TS completion provider is invoked
1. The TS completion provider calls `getWordRangeAtPosition`
1. In the buggy case, the document already has both `u and `n` in it. This results in the ts completion provider returning a word range of length two.
1. This incorrect range causes the suggestion controller to incorrectly overwrite the next character

Here's the relevant values from `_onDidSelectItem`. In the normal case when typing `u` + `n` slowly:

- `position.column` = 2
- `suggestion.range.endColumn` = 2
- `overwriteAfter` = 0

And in the bug case:

- `position.column` = 2
- `suggestion.range.endColumn` = 3
- `overwriteAfter` = 1

Any thoughts on how to fix this?

**Comment by mjbvz** [comment]
d9e2246 temporarily reverted using the word range for js/ts completions because this bug is pretty annoying while working in the VS Code codebase

**Comment by DanTup** [comment]
> look into a setting so that completions replace entire word #10266

Can't this be fixed in TypeScript by having it return the correct range for the replacement? It seems strange to fix this in VS Code IMO when it works fine in other languages. I'd be worried that VS Code trying to guess what's the correct range to replace will just end in tears (I'm sure there have been many issues before where VS Code made assumptions about the boundaries of symbols).

**Comment by jrieken** [comment]
> I think there may be a race condition with suggests and document edits here.

@mjbvz Likely but I think the race is on the TS side, asking for the current word range asynchronously, e.g after waiting for the server to respond. Having the below snippet as the first thing in [provideCompletionItems](https://github.com/microsoft/vscode/blob/f654e187ce00d3bb61d99cdb454c90816ece7cce/extensions/typescript-language-features/src/features/completions.ts#L344) and the undoing https://github.com/microsoft/vscode/commit/d9e2246c9b867f1bab1730630b474f5581cc2f51 printed the log shown below.

```
let _r = document.getWordRangeAtPosition(position);
if (_r) {
  console.log('TS word', document.getText(_r));
}
```

<img width="897" alt="Screenshot 2019-06-03 at 18 38 40" src="https://user-images.githubusercontent.com/1794099/58818806-05c6a480-862f-11e9-9cdd-81c3e8249b32.png">

This is what happens

1. typing happens
1. we debounce 24x7 Intellisense (this actually repos a little easier when setting `editor.quickSuggestionsDelay` to 100ms)
1. the request is send for `u`
1. the request is received for `u` 
1. TS forwards the request to tsserver
1. more typing happens (`n`) which triggers a refilter on the model (no new request)
1. tsserver replies
1. completion ranges are computed with the changed document (`un` not `u`)
1. filtering/insertion uses the wrong range

**Comment by jrieken** [comment]
So, I think there is nothing wrong on the suggest logic side as it correctly keeps track of edits that happen after a request has been send. TS should be able to implement overwrite right when using the word at request time, not response time, but I would favour a solution that works for all, see https://github.com/microsoft/vscode/issues/10266. 

I am not planning any action on this issue and I am leaving it up to you

**Comment by mjbvz** [comment]
Closing in favor of #10266.
