### ISSUE TITLE
Wrong window focused when opening from command line

### ISSUE THREAD

**Issue by huguesalary** [Microsoft/vscode#66183]
Issue Type: <b>Bug</b>

Open directory one: `code /one`.

Then open directory two: `code /two`.

The focused window after opening directory `/two` will be the 1st window (directory `one`).

In my opinion, the newly opened window should be focused.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|-psn_0_2814639|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.3.0
asciidoctor-vscode|joa|2.3.0
php-cs-fixer|jun|0.1.93
Go|ms-|0.8.0
sass-indented|rob|1.5.1
sourcegraph|sou|1.0.13

</details>

**Comment by huguesalary** [comment]
@bpasero it seems to me you did reproduce it, or maybe I'm not seeing your recording correctly.

But what I see in your recording is you opening `test-ts`, switching back to your terminal, then opening `test-js`, which makes the `test-js` window flash quickly, and right away `test-ts` shows up and is focused.

I would expect `test-js` to pop-up and stay in focus.

**Comment by huguesalary** [comment]
Ok, I think maybe you hit a key in your recording that made the `test-js` window get back in focus, and that's what confused me.

I tried again on my mac and I actually have a better understanding of what's happening:

This bug occurs with multiple monitors.

With the following setup:
- On monitor 1: nothing.
- On monitor 2: my terminal.

1. In my terminal, I run `code ./test1`, which somehow opens on monitor 1.
1. In switch back to the terminal.
1. In my terminal, I run `code ./test2`, which somehow opens on monitor 2.

If I start typing, the focus is on the `test1` window (on monitor 1) and things I type go to `test1` instead of `test2`.

**Comment by bpasero** [comment]
@huguesalary any specific setup like macOS spaces or fullscreen involved?

**Comment by huguesalary** [comment]
@bpasero No specific setup and no fullscreen. I can't do a recording unfortunately. I'll test on a coworker's machine and report back tomorrow

**Comment by bpasero** [comment]
Ok thanks, please do.
