### ISSUE TITLE
Intellisense details cannot scroll vertically the first time it's shown

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#66185]
This only appears to happen the first time it shows up, successive times work fine.

![image](https://user-images.githubusercontent.com/2193314/50800363-c325b980-1294-11e9-84b5-c5bb1a289c93.png)

Using the setting in https://github.com/Microsoft/vscode/pull/66179

**Comment by joaomoreno** [comment]
cc @ramya-rao-a, for when you feel nostalgic 😄

**Comment by italomg** [comment]
@joaomoreno is it OK to try and tackle this? I see you are assigned to it

**Comment by gsunit** [comment]
@Tyriar I am not able to reproduce the error. I am getting the verical scroll each time I hover my mouse over some Class name, for instance. Could you help by elaborating the steps to reproduce?

**Comment by Tyriar** [comment]
@gsunit 

1. Launch Insiders or build from source
2. Open settings `ctrl+,`
3. Click the {} icon to open the json file
4. type `commandsToSkip`

If that doesn't reproduce, try reload the window (via command palette) and try again.

Just repro'd using this on macOS Mojave:

<img width="408" alt="screen shot 2019-01-17 at 10 35 50 am" src="https://user-images.githubusercontent.com/2193314/51340402-b1d26f00-1a43-11e9-8a11-38426926a1b0.png">

**Comment by octref** [comment]
@Tyriar Does this still repro? Doesn't repro for me on latest.

**Comment by Tyriar** [comment]
Seems to work now 👍
