### ISSUE TITLE
Improve experience for really long settings descriptions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#66184]
After https://github.com/Microsoft/vscode/pull/66179 😱 

![image](https://user-images.githubusercontent.com/2193314/50800250-527e9d00-1294-11e9-95dc-068c9e31516e.png)

Some options:

- Have a read more button when things get too long
- Have string that appear only in the JSON/intellisense

**Comment by aeschli** [comment]
@roblourens Can't we find a (markdown)description that works in both UI and intellisense?
IMO we can tune the settings descriptions for the UI, the intellisense experience is now less important

**Comment by Tyriar** [comment]
@aeschli the full list needs to be accessible somewhere so that users know what to add/remove, adding this to the website would be awkward as it changes between versions and would need to be updated manually. The separate descriptions proposed makes sense here because you can't even edit the setting in the UI.

<img width="451" alt="screen shot 2019-01-25 at 8 32 29 am" src="https://user-images.githubusercontent.com/2193314/51758913-ca620b00-207b-11e9-972d-af6b34844224.png">

@roblourens how about a `truncateMarkdownDescription: boolean` flag instead which truncates after x characters on the UI?

**Comment by roblourens** [comment]
How about I just always truncate after x newline characters and add a `[...]` rather than an expand button. And counting newlines instead of figuring out wrapped lines. That should only impact this one setting.

**Comment by Tyriar** [comment]
@roblourens great idea 👍

**Comment by tiliv** [comment]
Hey all, I'm finding this change really complicated to deal with.  When I copy the default setting to put in my own, it's empty, so the truncation makes this a very confusing setting to work with.

**Comment by roblourens** [comment]
You only need to add settings that you want to add or remove from the list. If you want to see the full list for reference, you should be able to see the full list when you hover the setting name in the json editor.
