### ISSUE TITLE
Implementing ISerializableView in VS Code code base causes strange path

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#66191]
Issue Type: <b>Bug</b>

Start in grid.ts
Make a class that implements ISerializableView
Use the code actions to auto implement the interface
:bug: => weird code path in priority import

VS Code version: Code - Insiders 1.31.0-insider (28e7467661d67c05c3662ff900ee1984f7e2fbcc, 2019-01-07T06:20:02.775Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/29406 to track upstream

Looking into creating smaller repo now

**Comment by mjbvz** [comment]
To verify, make sure you are using TS 3.3 in the VS Code workspace
