### ISSUE TITLE
Abnormal indentation on the top hierarchical navigation bar menu in Markdown.

### ISSUE THREAD

**Issue by LittleboyHarry** [Microsoft/vscode#66192]
- VSCode Version: 1.30.1 (user setup)
- OS Version: Windows_NT x64 10.0.17134 (Win10)

Steps to Reproduce:

1. Type some secondary headlines with differ in number of words

<img width="432" alt="untitled-1 - visual studio code 2019_1_8 9_30_15" src="https://user-images.githubusercontent.com/13063376/50804410-c4082b00-1328-11e9-86cf-7413de01b0b2.png">

2. Click the top hierarchical navigation bar item. Then it will show a menu with abnormal indentation.

<img width="432" alt="untitled-1 - visual studio code 2019_1_8 9_30_15" src="https://user-images.githubusercontent.com/13063376/50804527-485aae00-1329-11e9-8a5a-024fb3cf73bd.png">

Does this issue occur when all extensions are disabled: No

**Comment by mjbvz** [comment]
Can you please share the contents of that markdown file. I can't been able to reproduce this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by LittleboyHarry** [comment]
As flowing text:

```markdown
# test
## test test test test test test test test test test test 
## test test test test test 
## test test test test test test test
## test 
## test test test test test test
## test test test test
```

**Comment by mjbvz** [comment]
Thanks. Seems fixed in insiders:

![screen shot 2019-01-17 at 10 36 26 am](https://user-images.githubusercontent.com/12821956/51340443-c9115c80-1a43-11e9-9fdb-656687b0e5fb.png)
