### ISSUE TITLE
Key Input and scope Bug

### ISSUE THREAD

**Issue by LOGANLEEE** [Microsoft/vscode#66193]
- VSCode Version: Version 1.30.1 (1.30.1)
- OS Version: 10.14.2 (18C54)

Steps to Reproduce:

1. CMD + F => Type texts => CMD + A or ESC
2. Arrow Key or ESC key doesn't work while coding in editor sometimes.

Does this issue occur when all extensions are disabled?: yes

using Eclipse Keymap Plug-in over 6month without problem till yesternday.
it works fine for a while after reloading vscode but few sec later it happen.

This is My key Biding Setting.
<img width="796" alt="screen shot 2019-01-08 at 10 46 29" src="https://user-images.githubusercontent.com/26853553/50804733-a93ab400-1332-11e9-93fe-d630b4aff67f.png">
sorry for uploading it as picture cuz i can copy even i selected those lines by mouse cursor. ( mouse-right - copy , CMD + C doesn't work)

i think there is a problem of Key Binding or binding scope something.

But one things that i cant understandable thing is it was fine till yesterday.!!

as last i attach Installed plug-in lists as well. Thank you.

1. and intelligence
2. AsciiDoc
3. Auto Close Tag
4. Babel javascript
5. Debugger for java
6. Docker
7. Eclipse Keymap
8. EsLint
9.GraphQL for VSCode
10. Java Dependency Viewer
11. Java Extension Pack
12. Java Test Runner
13. Language Support for java
14. Material Icon Theme
15. Maven for Java
16. VS Code Redis
17. TerraForm
18. Vtools
19. XML Tools
20. Styled-components

**Comment by RMacfarlane** [comment]
Hmm, there is a bug for this in version 1.31.0 of VSCode, but not 1.30.0: https://github.com/Microsoft/vscode/issues/65456

When this happens, can you see if there is anything in the console by doing CMD+Shift+P `Developer: Toggle Developer Tools`? And just to confirm, you have tried disabling all extensions by running `Reload Window With Extensions Disabled`?

**Comment by LOGANLEEE** [comment]
`345  08/01/19 11:03:42 cd /Users/Logan/Library/Application Support/Code`

i did this and problem solved.

I don't know what exactly happened :(
