### ISSUE TITLE
clicking at the output messages of the compiler (TypeScript) do not navigate to a file/line/column of where the error occurred

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#6619]
- VSCode Version:1.1.1
- OS Version:Windows 7

Steps to Reproduce:
1. Compile a typescript with an error in int
2. Observe an error message in the console output 
3. Click the line with the message in the output
4. Expected: to navigate to the source file/line/column where the error decected. Actual: no action taken

Expected: To navigate to a referred place

**Comment by dbaeumer** [comment]
Dups #21928.
