### ISSUE TITLE
[json] Don't propose keys that are already existing

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#662]
# Problem
When authoring a JSON file, such as a Microsoft Azure Resource Manager (ARM) JSON Template, the Visual Studio Code editor is showing all of the available properties for an object, instead of only showing the properties that the user has *not yet specified*.

<img width="592" alt="screen shot 2015-11-25 at 2 10 22 pm" src="https://cloud.githubusercontent.com/assets/466713/11409632/7d5a79ec-937e-11e5-93ae-75738d3ec7ee.png">

# Expected Result

I would naturally expect that the Visual Studio Code Intellisense returns only the JSON properties that the user hasn't defined yet. I shouldn't be prompted to insert a duplicate key.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by aeschli** [comment]
Fix delivered

**Comment by pcgeek86** [comment]
@aeschli Impressive, thank you.

Cheers,
Trevor Sullivan
