### ISSUE TITLE
Parameter Hints doesn't go away

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#66202]
Not sure what I've done to get into this state. Started happening today in Insiders:

![peek 2019-01-08 09-46](https://user-images.githubusercontent.com/22350/50819446-5bba4900-132a-11e9-8e06-e0e2fa218de5.gif)

Not much in Devtools:

![image](https://user-images.githubusercontent.com/22350/50819472-6b399200-132a-11e9-95fe-6469955e1a1c.png)

Looking into the history of parameter hints, assigning to @mjbvz : https://github.com/Microsoft/vscode/commits/master/src/vs/editor/contrib/parameterHints

**Comment by joaomoreno** [comment]
Repro steps:

1. Open parameter hints with a parens
2. Press <kbd>UpArrow</kbd>

**Comment by joaomoreno** [comment]
Bisecting points to 4a38520d592310b0ec0f4bf4ab1314686e34712d as the culprit.

**Comment by joaomoreno** [comment]
@mjbvz I ended up reverting the commit and re-releasing Insiders.

**Comment by mjbvz** [comment]
Thanks @joaomoreno! Caused by this line https://github.com/Microsoft/vscode/commit/4a38520d592310b0ec0f4bf4ab1314686e34712d#diff-8a4c4868765f5b76405fd127beb9ac6aL79 Will check in again with that line reverted
