### ISSUE TITLE
terminal panel (oh-my-zsh) always duplicate first character after using tab completion

### ISSUE THREAD

**Issue by iAladdin** [Microsoft/vscode#66200]
- VSCode Version:Version 1.30.1 (1.30.1)
- OS Version:Mac OS Mojave 10.14 (18A391)

Steps to Reproduce:

1. using zsh on terminal config
2. type sour and press tab
![2019-01-08 15 33 09](https://user-images.githubusercontent.com/209606/50816312-21b56b00-135b-11e9-8d93-503d7faf4426.gif)
3. zsh same config work perfect with iterm2
![2019-01-08 15 39 10](https://user-images.githubusercontent.com/209606/50816448-9ab4c280-135b-11e9-909a-7fa28b28cd69.gif)

Does this issue occur when all extensions are disabled?: Yes

I had same issue with iterm2, I fixed it with config
`
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
`

I have searched vscode issues, but I don't find solution.

**Comment by Tyriar** [comment]
It's happening because of the emoji at the start of the line, see https://github.com/Microsoft/vscode/issues/66125
