### ISSUE TITLE
SQL Format issue

### ISSUE THREAD

**Issue by MariuzM** [Microsoft/vscode#66211]
I have this SQL query:

```
CREATE TABLE users
(
user_ID INT (11) AUTO_INCREMENT PRIMARY KEY NOT NULL
species varchar(256) NOT NULL
)
```

But when i do format it make it like this:

```
CREATE TABLE users
(
	user_ID INT (11)
	AUTO_INCREMENT PRIMARY KEY NOT NULL
species varchar
	(256) NOT NULL
)

```

Is this a bug?

**Comment by Quentinix** [comment]
It may be a problem on an extension, VSCode does not allow formatting.
I use SQL Formatter from Cymon [https://marketplace.visualstudio.com/items?itemName=cymonk.sql-formatter](https://marketplace.visualstudio.com/items?itemName=cymonk.sql-formatter)

The result of formatting
```
CREATE TABLE users (
    user_ID INT (11) AUTO_INCREMENT PRIMARY KEY NOT NULL species varchar(256) NOT NULL
)
```

**Comment by RMacfarlane** [comment]
Hey @MariuzM, what type of file is this saved in? Out of the box, VSCode does not come with a formatter for SQL files. As @Quentinix says, this may be a problem with an extension you're using. Can you provide a list of extensions you're using?
