### ISSUE TITLE
C++17 namespace attributes break syntax highlighting

### ISSUE THREAD

**Issue by Cre3per** [Microsoft/vscode#66215]
- VSCode Version: 1.30.1 dea8705087adb1b5e5ae1d9123278e178656186a x64
- OS Version: Debian testing buster Kernel: x86_64 Linux 4.18.0-2-amd64

Steps to Reproduce:

1. Using C++ language mode and the Default Dark+ theme, copy/write the following code into the editor
```cpp
// The first angular bracket is purple, the rest are white.
namespace [[deprecated]] S
{
  // "fn" is blue, should be yellow
  void fn(int i)
  {
  }
}
```
Github also seems to have a problem with this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This issue was moved to atom/language-c#317
