### ISSUE TITLE
Diagnostics are not aligned correctly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#66212]
Notice the problem is shifted several pixels down and covers some of the below text.

@rebornix for monaco, @jrieken for diagnostics

![image](https://user-images.githubusercontent.com/2193314/50836243-95c92200-130d-11e9-8730-85b96c3b72e7.png)

VS Code version: Code - Insiders 1.31.0-insider (f599942a5f1ce23445eb1dd7e0ff799ab7a0a175, 2019-01-08T06:19:45.505Z)
OS version: Windows_NT x64 10.0.18305

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (32.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
git-project-manager|fel|1.7.1
vscode-pull-request-github-insiders|Git|1.7.2
vscode-scss|mrm|0.6.2
cpptools|ms-|0.21.0-insiders2
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.2
seti-icons|qin|0.1.3
lorem-ipsum|Tyr|1.2.0
vscode-todo-highlight|way|1.0.4
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
It is like this from many releases, at least it was not introduced recently. It is because of the padding (top/bottom) that the error widget adds. Reduced the padding a bit

![image](https://user-images.githubusercontent.com/10746682/50963411-f18dd980-14cc-11e9-840d-af69762c78a9.png)

![image](https://user-images.githubusercontent.com/10746682/50963421-f6eb2400-14cc-11e9-8ea4-10786d6abcb2.png)
