### ISSUE TITLE
TextEdit.setEndOfLine applies an edit and invalidates redo stack even when no change is made

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#66214]
Repros in 1.30.2 and 1.31.0-insiders, _not_ 1.29.1

Repro:

1. Install Editor Config extension
2. Add .editorconfig file to root with this contents:

   ```
   root = true
   
   [*]
   end_of_line = lf
   ```
3. Open some file
4. Delete 2 lines
5. Save
6. Undo three times (notice that you have to undo 3 times to undo the 2 edits, this is because `TextEdit.setEndOfLine` caused an extra edit)
7. Save
8. Try redo, this doesn't work because `TextEdit.setEndOfLine` caused an edit

Related discussion:

- https://github.com/editorconfig/editorconfig-vscode/issues/208
- https://github.com/Microsoft/vscode/issues/65663

**Comment by jrieken** [comment]
Not sure what has changed, this code has been stable in the last months: https://github.com/Microsoft/vscode/blob/5aba426b77d58dbeedbc539d1780931b917cb8bb/src/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.ts#L92-L104

**Comment by alexandrudima** [comment]
This got introduced via https://github.com/Microsoft/vscode/commit/0ac0c45b29c9c138e39c4b12602302650d9e405c#diff-4b2e90f9fb35dd653ba8b975c7a625f8R450
