### ISSUE TITLE
When saving an open "folder" as a workspace, needless hierarchy is added.

### ISSUE THREAD

**Issue by instanttim** [Microsoft/vscode#66219]
Issue Type: <b>Bug</b>

When opening a folder (dir) in VSCode, the sidebar "section" header becomes the folder name and you can easily open and close it to see all the files or hide them. When you save as a workspace, it changes the header to be the name of the workspace (which is fine) but then puts the single folder as an item inside the section. Now you have two disclosure triangles that essentially do the same thing and you've wasted one level of indenting for no reason.

I think workspaces should be exactly the same as opening the folder, with the exception that the workspace could have a custom name (and would still indicate it was a workspace I suppose).

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|16.00GB (3.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
systemd-unit-file|coo|1.0.2
laravel-blade|one|1.18.0
laravel5-snippets|one|1.5.0

</details>

**Comment by RMacfarlane** [comment]
Hi @instanttim, I think this is by design. The primary purpose of a workspace in VSCode is to allow opening multiple projects at a time, see https://code.visualstudio.com/docs/editor/multi-root-workspaces for more info. If you are only interested in working with a single folder at a time, then you can continue to open just that folder instead of saving it as a workspace.

**Comment by instanttim** [comment]
@RMacfarlane but the workspace-level settings that can be "synced" by committing to the repository is quite useful. Wouldn't it seem reasonable though to only add the additional hierarchy when you add the second folder? So with only one folder, it's just like working with a single folder is already. Once you have more than one folder it pops them in there?

**Comment by instanttim** [comment]
I did some testing. If you don't use workspaces, but open the folder directly, there is still a Settings tab called "Workspace Settings" and changing values there creates the .vscode directory and puts a settings.json in there. This is very odd, since when using workspaces that same behavior indicated with a settings tab called "Folder Settings". Perhaps I should open an issue that the settings UI should consistently refer to that as Folder Settings when not using Workspaces.

**Comment by RMacfarlane** [comment]
Haha, I was in the middle of trying to write up an explanation, but you beat me to it. https://stackoverflow.com/a/51881104/10136042 does a good job of explaining workspaces
