### ISSUE TITLE
Test: New version of Octicons

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#66229]
Refs: https://github.com/Microsoft/vscode/issues/65508

- [x] macOS: @isidorn 
- [ ] Windows: @auchenberg 
- [x] Linux: @roblourens 

Complexity: 2

We've updated our version of Octicons to the latest (3.1.0 => 8.3.0) and we've also added some additions/modifications (see https://github.com/Microsoft/vscode/pull/65989 for the full description). You should be able to use [any Octicon](https://octicons.github.com/) as well as test our new additions: `$(color-mode) $(organization) $(person)`. We also use Octicons in the following areas:

- Status bar
- Quick pick labels
- Issue reporter (related issues)
- Peek view (close button)
- Extensions: workspace recommendations (viewlet header has download all and edit)
- GitHub comment (edit and delete)
- Diff line (show next/prev change)

Verify that the icons show up properly in each of those areas.

For the Status bar, you can create your own extension or [use this basic one](https://github.com/Microsoft/vscode/files/2805449/octicon-test-0.0.1.vsix.zip) that cycles through all of the icons after you click the status bar item. You can additionally install other extensions that add items to the status bar (GitHub PR, vscide-spotify, Live Share, etc.) and verify that the icons show up correctly.

**Comment by auchenberg** [comment]
💥
