### ISSUE TITLE
Files pane wont update if a file or folder added from outside of vscode

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#6622]
- VSCode Version:1.1.1
- OS Version:ubuntu 16.4

Steps to Reproduce:

1. open vscode 
2. open files pane
3. open file manager (in my case nautilus)
4. create a file or folder
5. hit refresh button on right top corner of files pane in vscode 
6. new created file or folder wont take place there untill restarting vscode

**Comment by bpasero** [comment]
@NikosEfthias can you provide more details what file you create and where? can you attach a video showing the issue in detail?

**Comment by NikosEfthias** [comment]
i am compilig typescript and if the compilatiion occured first time the fil is not there untill i resrart vscode

**Comment by bpasero** [comment]
But your "steps to reproduce" sound different from that?

**Comment by NikosEfthias** [comment]
@bpasero somehow it seems to be working now
