### ISSUE TITLE
"debugType" command "when" conditions do not work after a debug session restart

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#66226]
- VSCode Version: Version: 1.31.0-insider (system setup)
Commit: 7b375fcb821bee9342656c39492223c7b5fc8830
Date: 2019-01-08T09:30:46.424Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

### Steps to Reproduce:

1. Create an extension that registers a command with a `when` condition like `"when": "inDebugMode && debugType == 'coreclr'"` ([C# extension example](https://github.com/OmniSharp/omnisharp-vscode/blob/4248b529ce5092983eb67fbec52072a9903cffc0/package.json#L2874))
2. Start debugging and hit a breakpoint
3. Result: command is available
4. Hit the "Restart" button to recreate the debug session
5. Wait for the breakpoint to hit again
6. Test if the command is available

### Result:
Command isn't available

### C# extension repro steps:

1. Follow instructions in https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases to install release https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta4 of the C# extension
2. Open the Terminal, run as follow command to create new console project:
dotnet new console -o myapp
3. Add some code in the program.cs and set a breakpoint
4. Run command ".NET: Generate Assets for Build and Debug" to have the C# extension generate a launch.json/tasks.json
5. F5, wait for the breakpoint to hit
6. Move your cursor to the next statement you would like to execute next, and right click "Set Next Statement(.NET)", it work normally
7. Restart debugging and repeat step6

Expected
"Set Next Statement(.NET)" option display and work normally when right click as following:
![image](https://user-images.githubusercontent.com/32150874/50817093-b9b45400-135d-11e9-836a-8518ac24146e.png)

Actual
"Set Next Statement(.NET)" option disappeared after restarting debugging as following:
![image](https://user-images.githubusercontent.com/32150874/50817103-c2a52580-135d-11e9-998f-9dfea11bc60c.png)

### Notes
I debugged VS Code a little. I _think_ the issue is that 'doCreateSession' is what sets the 'debugType' property via line [`this.debugType.set(session.configuration.type)`](https://github.com/Microsoft/vscode/blob/314cc521d8ce0c55773850ef520095afde33a62c/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L448), but that code doesn't seem to run for restarts. Sorry if I have this wrong.

**Comment by isidorn** [comment]
Good find and great analysis.
We were setting the debug type context key at the wrong place (whenever we create a session).
The proper place to set it is whenever a session is getting focued.
Since you would expect it to change values as focused session changes if a user is debugging C# and node at the same time for example.
