### ISSUE TITLE
Opening a new window/instance presents an unbrowsable environment.

### ISSUE THREAD

**Issue by foodini** [Microsoft/vscode#66220]
- VSCode Version: 1.30.0
- OS Version: Mac OS 10.13.6

Steps to Reproduce:
1. Open a project directory. My project includes a mix of C++/Go/Python. I don't believe the issue is extension-related because it occurs for all languages.
2. Control-click on some identifier and click "Go To Definition"  (This will work.)
3. Hit Control-Shift-O, and enter the name of a file in the project (delete the @ sign you'll be prompted with, first). The predictive list will show your file, and you'll be able to open it.
4. Hit Cmd+Shift+N
5. Open the same file (from step 2) in the new window.
6. In the new window, Control-click on the same identifier, click "Go To Definition" and you'll be told that there's no definition for the identifier.
7. In the new window, hit Control-Shift-O and do step 3 again. It won't find the file.

Does this issue occur when all extensions are disabled?: You can't browse source without extensions, so the question doesn't make sense. However, the issue occurs in every language I have worked with, so I don't believe it to be caused by extensions. In the extensions tab, they all show as active. I'm currently using C/C++ 0.20.1, GitLens, Go 0.8.0, Python 2018.12.1, and vscode-proto3 0.2.2.

It appears as though the source folder isn't open in the new window. Furthermore, attempting to open it explicitly fails silently:
1. In the original window, hit Cmd+Shift+N.
2. In the new window, hit Cmd+O
3. Select the project folder.
4. You'll receive no error or warning message of any kind, but the file explorer will still say "You have not yet opened a folder."

My eyesight isn't exactly what it used to be, so I need the extra space that multiple monitors provides, and OS X doesn't allow you to stretch an application window across displays, so I rely heavily upon having multiple instances open.

**Comment by RMacfarlane** [comment]
Hi @foodini, you can open the same project in a new window by using Cmd+Shift+P and then typing `Workspaces: Duplicate Workspace in New Window`. There's an open feature request for allowing opening the same project in multiple windows more generically, without having to use that command: https://github.com/Microsoft/vscode/issues/2686. But for now I think that command should do what you want.
