### ISSUE TITLE
Run pre-defined rules

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#66221]
Using `.vscode/settings.json` we are define custom settings specific to that repository. Same way...

We can create a `.vscode/rules.json` file to define certain types of rules which will run automatically when we will open that repository.

**For example:**

```json
{
    "rules": [
        [
          "overlay": true
        ],
        [
        "terminal": {
            "command": "Open terminal", // these are commands which are availalbe when we press ctrl + shift + p
            "priority": "2"  // between 0 to 10
        },
        "gitFetch": {
            "command": "Git Fetch Changes",
            "priority": "8"
        }
        ]
    ]
}
```

These are just a few example of the idea, we can even create more complex rules.

**Comment by usernamehw** [comment]
Looks more like an extension idea.

Something of the sort https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command

**Comment by Tyriar** [comment]
Also heck this one out https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals
