### ISSUE TITLE
Code Helper consumes 100% of CPU

### ISSUE THREAD

**Issue by jonpincus** [Microsoft/vscode#66224]
Issue Type: <b>Bug</b>

Issue Type: <b>Performance Issue</b>

This only started happening after I upgraded to version 1.30.1   Now, it happens fairly frequently - enough that it's borderline unusable.  It stays at 100% CPU for anywhere from 5 seconds to a minute or two.  I've disabled all my extensions.  

It seems to happen more often when I'm running the app in the debugger, but also happens spontaneously on its own from time to time.  

Here's that output of core --status

```
CPU %	Mem MB	   PID	Process
   75	    66	 31726	code main
    0	   115	 31727	   gpu-process
   98	   442	 31728	   window (home.pug — jedii-links (Workspace))
    0	    33	 31927	     extensionHost
    0	    16	 31929	       electron_node tsserver.js 
    0	     0	 31941	         electron_node typingsInstaller.js typesMap.js 
    0	     0	 33741	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=31927
    0	     0	 31928	     watcherService
    0	    16	 38631	     searchService
    2	    66	 39241	     electron_node nodeDebug.js 
   30	  1229	 39243	       electron_node server.js 
    0	     0	 39248	         /usr/bin/perl -w /usr/local/bin/exiftool -stay_open True -@ -
    0	    49	 39874	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork ms-vscode.node2 {"common.vscodemachineid":"d4c1d52a63c566ccd178d8e588f3ab7ca937b73748ececbabe12f3fb256d2855","common.vscodesessionid":"5f1a8fa5-9e4b-43fd-9a22-fe51c5489d0e1546555153081"} AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    16	 31944	   shared-process
   62	    49	 35864	   window (Issue Reporter)
Workspace Stats:
|  Window (home.pug — jedii-links (Workspace))
|    Folder (jedii-links): 214 files
|      File types: json(20) js(19) pug(12) txt(2) css(2) env(1) gitignore(1)
|                  sample(1) html(1) backup(1)
|      Conf files: package.json(1) launch.json(1)
|      Launch Configs: node

```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by weinand** [comment]
With "Code Helper" you probably mean the "window (home.pug — jedii-links (Workspace))" in the `code --status` output from above, right?

I see that the VS your program `server.js` puts some load on the CPU but I don't see an issue with the node debugger.

@bpasero does the 98% CPU load of the renderer ring a bell?

**Comment by bpasero** [comment]
@jonpincus 
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

@weinand not without further info. On an average I would say that I get 10-20 issues per week where a process consumes >98% of CPU and I think I never had a case where I would know the underlying issue just by reading the description of the issue.

**Comment by jonpincus** [comment]
> With "Code Helper" you probably mean the "window (home.pug — jedii-links (Workspace))" in the code --status output from above, right?

"Code Helper" is what Activity Monitor shows as the process taking 100% of the CPU.  And yes, in the code --status output it's the "window (home.pug — jedii-links (Workspace))" line that has the unexpectedly high activity.

@bpasero it looks like the next thing for me to do on the wiki page is to install the Insiders version.  I'll do that, see if the problem still occurs, and then start working through the other instructions.  Looks like a good chance to learn the profiler :-|

**Comment by bpasero** [comment]
Thanks.
