### ISSUE TITLE
Move/rename file as a command

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#66233]
I like to use files using the VS Code file explorer, as this is the only way to move/rename a file and then have TypeScript prompt you if you would like to update imports.

However, in a large project, it gets extremely difficult to move files using drag and drop. Folders tend to get very large, with multiple levels of nesting.

Is there an alternative way to move a file? Perhaps this could be done as a command? I'm aware some extensions provide this, however they use the file system directly, which means TypeScript won't prompt to update imports for the moved/renamed file.

**Comment by isidorn** [comment]
Sounds like a feature request against typescript moving to @mjbvz

**Comment by mjbvz** [comment]
@isidorn I don't think this request TS specific. TypeScript handles any file move events, so what @OliverJAsh is asking for is a nicer UI to move the file in the first place.

Such a move file UI would also be useful even without TS's support for updating imports

**Comment by mjbvz** [comment]
Also, if we had API that allowed extensions to perform file moves within VS Code, a "file move" UI could be implemented entirely by an extension. Somewhat related to #48034 but for moves

**Comment by gdh1995** [comment]
I also want a command to rename current edited file by Ctrl+P - it's annoying that currently I have to move mouse to the left file explorer, find the file, click it and then press <kbd>F2</kbd>.

**Comment by OliverJAsh** [comment]
The new version adds support for "Cut" to the context menu, which is a big help: https://code.visualstudio.com/updates/v1_31#_cut-command-in-explorer-context-menu.

**Comment by amiceli** [comment]
To rename a file I use that extension : https://github.com/sleistner/vscode-fileutils
It can be useful.

**Comment by OliverJAsh** [comment]
Does that trigger TS's "update imports"?

**Comment by amiceli** [comment]
I try with es6 imports, no, it just rename file.
