### ISSUE TITLE
Array interpolation in PHP has wrong syntax highlighting

### ISSUE THREAD

**Issue by ChazyTheBest** [Microsoft/vscode#66231]
- VSCode Version: 1.26.0-insider
- OS Version: Manjaro Linux
- No extensions

Steps to Reproduce:

1. Double quote an array (either indexed or asoc).
2. The square brackets don't have the appropriate syntax highlight color (white).

`echo "123$foo[bar]456";`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Moved to https://github.com/atom/language-php/issues/347
