### ISSUE TITLE
Feature Request: generate imports when copying code between files

### ISSUE THREAD

**Issue by Rhobal** [microsoft/vscode#66236]
In eclipse Java editing, copying a code snippet from a class to another also automatically copies the imports required by the copied code.
Would be nice to have this in VS Code for typescript as well. Currently when I copy some code, I have to manually resolve the imports afterwards.

**Comment by mjbvz** [comment]
Needs api proposed in #30066

**Comment by johnculviner** [comment]
This feature is amazing in Webstorm / IntelliJ. It's one of the biggest things I miss coming from there.

I was actually doing some research into how pasteboard works in macOS at least (and the metadata that can live in it. formatting etc.). It's complicated. I think it might be possible to keep that metadata in vscode though and make the implementation easier to be cross OS usable:
- When you do a copy, the string goes into the "ANY_OS" clipboard.
- VSCode simultaenteouly stores the AST metadata (or however it works, need to check that part out) about that code in memory in the vscode process along with the associated string.
- If you paste that string in vscode, vscode looks to see if it has any metadata for that string stored in it's process. If it does it uses the stored metadata to do any applicable imports.

I might see if I can pull this off as I love the direction of vscode but I sorely need this to reach the productivity I've enjoyed in IntelliJ...

**Comment by olegKusov** [comment]
Is there any update? It's WebStorm killer feature must be added to vs code!))

**Comment by pouyarezvani** [comment]
Any update on this @mjbvz? This is a really good feature that we need in vscode. 
Having vscode automatically bring the import when coping code would be very helpful.

**Comment by IgnusG** [comment]
I've been wondering about this every now and then and today finally decided to search for a way to do this on the web. This would really be a cool thing to have. I was actually thinking of simply triggering the import all missing modules code action after paste if that's somehow possible. Otherwise it's just a few more keystrokes but still ^^'

**Comment by Kogs** [comment]
Upvote 👍  would be a huge time saver.

**Comment by dongzhuoyao** [comment]
upvote

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/50187 to track this upstream
