### ISSUE TITLE
'File has unexpected size' on apt update

### ISSUE THREAD

**Issue by Furqan136** [Microsoft/vscode#66238]
- VSCode Version: 1.30.2
- OS Version: KDE Neon 5.14 (Latest)

Steps to Reproduce:
1. Run apt-get update in terminal

It used to occur a month or two ago but got fixed. There are some other issues on this topic but they a a year older and have been closed. 

Yesterday it started again. It was happening with previous vscode version(1.30.1) too. I updated using the deb file. Following is the terminal output. 

```
Get:7 http://packages.microsoft.com/repos/vscode stable InRelease [3181 B]                                         
Get:8 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [86.8 kB]
Err:8 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  File has unexpected size (86623 != 86761). Mirror sync in progress? [IP: 13.80.10.205 80]
  Hashes of expected file:
   - Filesize:86761 [weak]
   - SHA512:71526eaa8862ffdadb52860da68a4cbc9f2f0ff2f9f0c0956eb9b659804b1d398413d4357c57c1b5fbf1845f16b1355a1d0a46f43e335501b57eee5695b216bd
   - SHA256:ab16a3623843d3d1520ba4d389e4c246f984fa2fec47c331ea5194ade81264a6
   - SHA1:5c6c19f0d707738b005d088ac5bb39c072be1bcd [weak]
   - MD5Sum:835c1b15d9af6d94ae8a2336e887b2cc [weak]
  Release file created at: Tue, 08 Jan 2019 16:13:00 +0000
Get:9 http://archive.neon.kde.org/user bionic InRelease [19.0 kB]  
Fetched 19.0 kB in 5s (3873 B/s) 
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (86623 != 86761). Mirror sync in progress? 
   Hashes of expected file:
    - Filesize:86761 [weak]
    - SHA512:71526eaa8862ffdadb52860da68a4cbc9f2f0ff2f9f0c0956eb9b659804b1d398413d4357c57c1b5fbf1845f16b1355a1d0a46f43e335501b57eee5695b216bd
    - SHA256:ab16a3623843d3d1520ba4d389e4c246f984fa2fec47c331ea5194ade81264a6
    - SHA1:5c6c19f0d707738b005d088ac5bb39c072be1bcd [weak]
    - MD5Sum:835c1b15d9af6d94ae8a2336e887b2cc [weak]
   Release file created at: Tue, 08 Jan 2019 16:13:00 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Tyriar** [comment]
I cannot repro in US West, I'll tell the linux repo admin team.

**Comment by TheTeraByte** [comment]
I'm from the linux repo admin team. @kamleshrao , @Furqan136 , could you please tell me which geographic locations you are trying to poll the repo from? It's seems that some of our regional mirrors have an incomplete sync that I'll have to fix manually. The geographic locations would help me pinpoint exactly which mirrors have this problem.

**Comment by Tyriar** [comment]
@TheTeraByte profile says Bangalore, India

**Comment by Furqan136** [comment]
@TheTeraByte I am from Lahore, Pakistan. Though i have edited my software source to be the main ubuntu server rather than the local one. As, the local one had problems(mostly dependency issues) so bad that on a fresh install I couldn't even install g++.

**Comment by kamleshrao** [comment]
@TheTeraByte  Yes  I am from Bangalore, India. 

Today I did package update and I didn't find any issues with VSCode. It went well. 

However, today I am getting a Warning for another software.

`W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY `
