### ISSUE TITLE
predefined variable error on tasks.json

### ISSUE THREAD

**Issue by sbwtw** [Microsoft/vscode#6623]
- VSCode Version: 1.1.1
- OS Version: Archlinux

Steps to Reproduce:

1. create new project and set tasks.json
2. command is set to echo, and args set to ["${file}", "${fileBaseName}"]
3. run task with some file, like a.txt.
4. ${file} and ${fileBaseName} are same string

**Comment by dbaeumer** [comment]
This is what I see under Windows:
```
running command> echo p:\mseng\VSCode\Playgrounds\tasks\.vscode\tasks.json, tasks.json
"p:\mseng\VSCode\Playgrounds\tasks\.vscode\tasks.json, tasks.json"
```

Checking under Linux now.

**Comment by dbaeumer** [comment]
The tasks.json is:
```json
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "echo",
	"isShellCommand": true,
	"echoCommand": true,
	"args": ["${file}, ${fileBasename}"]
}
```

Note that the var for the basename is ${fileBasename}

**Comment by dbaeumer** [comment]
Same is true for Linux (Elementary OS).

**Comment by dbaeumer** [comment]
I am closing the issue. Please ping with steps to reproduce if you still see this.

**Comment by dbaeumer** [comment]
We get the base name using and node function which should be independent of the Linux you use. That is why I closed it. To double check you could execute the following snippet in a node environment:
```js
var path = require('path');
path.basename('/home/dirkb/test.txt');
```
This should print:
```
'test.txt'
```
