### ISSUE TITLE
jsdoc example with import statement breaks syntax highlighting

### ISSUE THREAD

**Issue by Silic0nS0ldier** [Microsoft/vscode#66247]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/17376090/50869876-f63d8980-1409-11e9-8892-c9492fc9d51c.png)

1. Clone https://github.com/developit/stockroom
2. Open src/index.js in VS Code

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (5.85GB free)|
|Process Argv|E:\template-preact|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.6
prettier-vscode|esb|1.7.3
vscode-diff|fab|1.4.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
code-beautifier|mic|2.1.0
vscode-apache|mrm|1.2.0
PowerShell|ms-|1.10.2
php-docblocker|nei|1.7.0
laravel-blade|one|1.18.0
vscode-docker|Pet|0.5.0
twig|wha|1.0.2

</details>

**Comment by mjbvz** [comment]
Simplified example:

```ts
/** x
 *	@example
 *	1 + 1
 */
const a = 1;
```
