### ISSUE TITLE
Control ordering of onDidChangeConfiguration event firing and workspaceFolders being updated when opening/closing workspace folders

### ISSUE THREAD

**Issue by jomiller** [Microsoft/vscode#66246]
When a workspace folder is opened or closed, and that folder contains folder-specific configuration settings, then subscribers to the workspace.onDidChangeConfiguration event are called before workspace.workspaceFolders has been updated.

I'd like a way to control the relative ordering of onDidChangeConfiguration firing and workspaceFolders being updated. For example, I'd like onDidChangeConfiguration to fire _before_ an opened folder has been added to workspaceFolders, but _after_ a closed folder has been removed from workspaceFolders.

ConfigurationChangeEvent.affectsConfiguration returns true for folder-specifc settings even if those settings were just added/removed to the configuration because the folder was just opened/closed, and the settings did not actually change.

In some cases, I require the window to be reloaded when the configuration changes, and I don't want to inform the user to reload the window if it doesn't need to be, because the configuration has not really changed.

**Comment by bpasero** [comment]
> For example, I'd like onDidChangeConfiguration to fire before an opened folder has been added to workspaceFolders, but after a closed folder has been removed from workspaceFolders.

That does not make a lot of sense to me I would think we should always first update the `workspaceFolders` array and then fire events in both cases of a folder being added or removed. Can you clarify?

**Comment by jomiller** [comment]
If the folder were added to `workspaceFolders` before `onDidChangeConfiguration` fired, then my subscriber would think that the window needed to be reloaded, because `affectsConfiguration` would return true for that new folder.

I don't need to reload the window when a folder is opened, because the necessary work is done in the subscriber to `onDidChangeWorkspaceFolders`.

I was thinking that different extensions would desire different behaviour, and that's why I suggested making the behaviour configurable somehow.

**Comment by bpasero** [comment]
@sandy081 what do you think about the ordering?

**Comment by sandy081** [comment]
I think the right order of events is

- Workspace folders change event
- Configuration change event

But folders and configuration should be updated before events are triggered. 

The order was reversed now because currently we are not synching both data onto the extension host at the same time - https://github.com/Microsoft/vscode/issues/34254

If we can sync both data https://github.com/Microsoft/vscode/issues/38315 then we can move to the right order.

**Comment by jomiller** [comment]
@sandy081, assuming that order of events, how can I detect whether `ConfigurationChangeEvent.affectsConfiguration` returns true because the configuration has really been  changed by the user, or only because a folder has been opened (that contains folder-specific configuration)?

**Comment by sandy081** [comment]
May I know why do you need to know the source of change? Can you please explain your scenario of what is happening during both evnets?

**Comment by jomiller** [comment]
During `onDidChangeConfiguration`, I detect whether configuration has changed for each folder in `workspaceFolders` by calling `ConfigurationChangeEvent.affectsConfiguration`. I need to reload the window when certain configuration has changed in order to re-activate the extension. In this case, I show a message to the user prompting to reload the window.

During `onDidChangeWorkspaceFolders`, I process the added and removed folders accordingly.

I don't need to reload the window when a folder has been opened, because all the necessary work is done during `onDidChangeWorkspaceFolders`. So I don't want to show a message to the user unnecessarily.

I suppose the ultimate solution would be to not require the window to be reloaded, but I'm not sure that's practical.

**Comment by sandy081** [comment]
I see. It's bit tricky. There is a need of two events as they are two different things that getting changed. Since workspace folders change first, this event should 
come first.

But I think you can fix it by caching the configuration on your side. Revalidate it when workspace folders or configuration change. But during configuration change you can check if it is changed or not by checking your cache and react accordingly?

**Comment by jomiller** [comment]
OK, I'll do as you suggested. Thanks for your help.

**Comment by bpasero** [comment]
Close?

**Comment by jomiller** [comment]
Yes, I've implemented the caching solution, and it works as expected.
