### ISSUE TITLE
Remove razor support for HTML

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#66242]
https://github.com/aspnet/Razor.VSCode handles Razor files much better. We should remove its support from our built-in HTML language features.

@aeschli What do you think?

**Comment by aeschli** [comment]
I agree! @egamma Ok for you?

But we should add a extension recommendation for to help razor users to move to the new extension.

https://github.com/Microsoft/vscode-distro/blob/master/quality/stable/product.json

**Comment by octref** [comment]
Verification: Verify that cshtml files now prompt C# extension as recommendation

**Comment by alexr00** [comment]
I'm not seeing the recommendation. I uninstalled the C# extension then created a cshtml file. The language in the bottom right corner says Razor.

**Comment by alexr00** [comment]
Should there be a notification, or just C# listed in the Recommended Extensions view? I don't see a prompt.

**Comment by octref** [comment]
I see, I should have made that a strong recommendation...
