### ISSUE TITLE
GoToLine:  getARIALabel only returns gotoLineLabelEmpty string, but no errors

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#66245]
All versions/platforms

GoToLineEntry getARIALabel() method only returns the standard gotoLineLabelEmpty
string "Type a line number to navigate to"

It does not track the quick open label for its errors nor does it
get set for the nontext editor error.

@alexandrudima 
@isidorn 
I discovered this while working on the go to line issue.  I have it fixed in my PR
since I had to handle the related error.

I did not change the fact that the label always seems to use the "line between ..."
even before the user types anything.  I ignored that for the accessibility label.

Question:
Since I created this issue, I am working on it, and it's related to the other issue,
I assume it is okay that I added the labels for this issue and assigned to myself?

I just want to make sure that this is proper.

Steps to reproduce:

- Start screen reader
- Open welcome page
- Execute GoTo Line command
- QuickOpen displays error "Open a text file first to go to a line" - Correct for the quick open label
- Screenreader outputs: " Type a line number to navigate to"

Expected Behavior:
- Track quick open label

**Comment by alexandrudima** [comment]
@cleidigh :+1: Good find.

Yes, I think the rule we follow is that the owner of an issue should own the labels for an issue, so if you're the owner, you own the labels.

**Comment by isidorn** [comment]
This is fixed with the PR. Thanks a lot @cleidigh
