### ISSUE TITLE
Javascript console.log() autocompleting to console..log() when you type in the parentheses.  This occurs when joining live share session.

### ISSUE THREAD

**Issue by jfacoustic** [Microsoft/vscode#66243]
- VSCode Version: 1.29.1
- OS Version: MacOS 10.14.2 (Mojave)

Steps to Reproduce:

1.  Enter an existing live share session
2.  Begin typing console.log()
3. When you get to the first parenthesis, it adds a period before the log.  "console..log()"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
does the issue occur when not using a liveshare session?

**Comment by jfacoustic** [comment]
@weinand no

**Comment by weinand** [comment]
Please file this issue against Liveshare extension.
