### ISSUE TITLE
when markdown edit , Unable to enter backspace, enter

### ISSUE THREAD

**Issue by NingShenTian** [Microsoft/vscode#66257]
Issue Type: <b>Bug</b>

System OS：Ubuntu 18.10
Markdown Edit，backspace、Enter、Tab  key Invalid，but Character can Input。

![default](https://user-images.githubusercontent.com/14068570/50873729-2e3dd000-13fc-11e9-9fc6-121314109275.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.18.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3250 @ 3.20GHz (2 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|3.77GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
vscode-icontheme-nomo-dark|be5|1.3.6
head-file-guard|bjr|0.0.2
vscode-markdownlint|Dav|0.23.0
racket|Dmy|1.2.0
codecpp-full|dod|0.0.1
fileheadercomment|doi|0.0.3
xml|Dot|2.4.0
gitlens|eam|9.4.1
vscode-great-icons|emm|2.1.46
vsc-material-theme|Equ|2.6.3
code-runner|for|0.9.5
vscode-mysql|for|0.3.0
CppSnippets|har|0.0.13
rest-client|hum|0.21.1
csharpextensions|jch|1.3.0
cpp-pack|jew|0.0.2
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.2
racket|kar|0.0.3
vscode-simple-icons|Lau|1.9.3
csharpfixformat|Leo|0.0.77
cmake-tools-helper|mad|0.2.1
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
team|ms-|1.144.1
mysql-inline-decorator|odu|0.0.5
material-icon-theme|PKi|3.6.2
java|red|0.36.0
vscode-icons|rob|8.0.0
markdown-preview-enhanced|shd|0.3.11
syntax-racket|spo|0.0.4
cmake|twx|0.0.17
vscode-iconfont-preview|und|0.1.0
cmake-tools|vec|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-react-native|vsm|0.7.0
ReactSnippets|xab|2.3.0
clang-format|xav|1.8.0
markdown-all-in-one|yzh|1.8.0

(3 theme extensions excluded)

</details>

**Comment by NingShenTian** [comment]
Restarting the vscode still won't solve

**Comment by NingShenTian** [comment]
Uninstall extensions “markdown-all-in-one”，The problem is solved.

**Comment by hollyph** [comment]
> Issue Type: Bug
> 
> System OS：Ubuntu 18.10
> Markdown Edit，backspace、Enter、Tab key Invalid，but Character can Input。
> 
> ![default](https://user-images.githubusercontent.com/14068570/50873729-2e3dd000-13fc-11e9-9fc6-121314109275.png)
> 
> VS Code version: Code 1.30.2 ([61122f8](https://github.com/Microsoft/vscode/commit/61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8), 2019-01-07T22:49:48.319Z)
> OS version: Linux x64 4.18.0-13-generic
> 
> System Info
> Extensions (47)

**Comment by RMacfarlane** [comment]
@NingShenTian Since this issue was caused by an extension, can you reopen this issue in that extension's repository? Thank you
