### ISSUE TITLE
Find all references to files 

### ISSUE THREAD

**Issue by stereokai** [Microsoft/vscode#6625]
- VSCode Version: 1.1.1
- OS Version: Mac OSX

Feature request:

1. Right click on file in sidebar
2. There should be a "Find all references" option
3. It should display a list of references to that file in the open project

**Comment by jrieken** [comment]
> It should display a list of references to that file in the open project

@stereokai Do mean a file references, like a TypeScript import statement or references from all symbols of a file to the whole project? How should it behave with symbols that don't need to correspond to their filenames, like C# namespaces?

**Comment by jrieken** [comment]
@stereokai Please provide the requested information

**Comment by stereokai** [comment]
@jrieken I missed your reply!

I am not sure what you mean by symbols. What I meant was files used in ES6/TypeScript import statements. Maybe at a later stage, also paths in strings (ie. `<img src="path/to/file.jpg">`).

Thanks!
