### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by liugucheng** [Microsoft/vscode#66258]
所需的数据太大，无法直接发送。我们已
Issue Type: <b>Bug</b>

编辑器内部出现主菜单栏

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.84GB free)|
|Process Argv|D:\guanwang-Vue|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
color-info|bie|0.5.0
vscode-standardjs-snippets|cap|0.8.0
vue-css-peek|Cha|1.0.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
vscode-faker|dee|1.3.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.13.1
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.30.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
indent-rainbow|ode|7.2.4
open-html-in-browser|pea|0.0.3
vscode-icons|rob|8.0.0
vue-vscode-snippets|sdr|1.3.0
highlight-matching-tag|vin|0.8.5
quokka-vscode|Wal|1.0.175
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>
经将其写入剪贴板，请粘贴。

![Uploading image.png…]()

**Comment by RMacfarlane** [comment]
> The main menu bar appears inside the editor

Can you provide a screenshot of this? Does this happen all of the time? Does it still happen if you run `Reload Window With Extensions Disabled`?
