### ISSUE TITLE
Problem About Chinese Characters

### ISSUE THREAD

**Issue by winshepherd** [Microsoft/vscode#66265]
Issue Type: <b>Bug</b>

A simple python(3.5) script just as  below can't output Chinese characters correctly. But the same script works well under sublime text(3). I don't know why. I try many kinds of methods and still cannot solve this problem.

#encoding=utf-8
s = '中文'
print(s)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.23.0
code-runner|for|0.9.5
r|Iku|1.0.2
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2018.12.1
java|red|0.36.0
r-lsp|REd|0.0.8
vscode-java-debug|vsc|0.16.0
vscode-java-pack|vsc|0.5.0
vscode-maven|vsc|0.13.0

</details>

**Comment by guhuajun** [comment]
Greetings,

It works from my side. Would you mind to check your file encoding?

![image](https://user-images.githubusercontent.com/14121694/50888061-c0130080-142f-11e9-921d-f1b7be1c9b69.png)

**Comment by winshepherd** [comment]
> Greetings,
> 
> It works from my side. Would you mind to check your file encoding?
> 
> ![image](https://user-images.githubusercontent.com/14121694/50888061-c0130080-142f-11e9-921d-f1b7be1c9b69.png)

Thank you. My file encoding is utf-8.  I guess there are something wrong with vsc extensions. Now i reinstall the extension and anaconda. And it works.
