### ISSUE TITLE
Make TerminalRenderer API public

### ISSUE THREAD

**Issue by Gamadril** [Microsoft/vscode#66269]
I would like to know if the TerminalRenderer API will become public API soon.
Since one year I'm looking for a way to make my extension "interact" with the user. I used the proposed TerminalRenderer API  and it worked perfect in the published extension, until I realized after a new VSCode release that proposed API definitely cannot be used in published extensions, and the fact it was working all the time before seems to be a bug in VSCode implementation...
In my current implementation at least for the output I used vscode.debug.activeDebugConsole.appendLine. However Since 1.30 the call doesn't show anything. A new output channel is the only left possibility, but it doesn't support terminal colour syntax.
For getting user input there is still nothing.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/58660
