### ISSUE TITLE
Add bookmarks

### ISSUE THREAD

**Issue by CHENTsang** [Microsoft/vscode#66263]
Sometimes I would like to edit some files again and again, but I always forgot the filepath. So can you add **Bookmarks** just like browser bookmarks. I think may it's a good feature.

**Comment by usernamehw** [comment]
Do you mean, like, global or workspace-scoped?

**Comment by samael205** [comment]
¿Do you remember the name of the file?, You could use Ctrl+P to search all files inside the folder

**Comment by CHENTsang** [comment]
> Do you mean, like, global or workspace-scoped?

I mean global filepath, not the relative filepath in workspace.

**Comment by CHENTsang** [comment]
> ¿Do you remember the name of the file?, You could use Ctrl+P to search all files inside the folder

I mean global filepath, not the relative filepath in workspace.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=oleg-shilo.favorites

https://marketplace.visualstudio.com/items?itemName=andrew-lis.workbench

**Comment by CHENTsang** [comment]
> [marketplace.visualstudio.com/items?itemName=oleg-shilo.favorites](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.favorites)
> 
> [marketplace.visualstudio.com/items?itemName=andrew-lis.workbench](https://marketplace.visualstudio.com/items?itemName=andrew-lis.workbench)

thank you!!!

**Comment by RMacfarlane** [comment]
Closing this issue since the problem is solved with an extension. Thanks!
