### ISSUE TITLE
horizontal scroll issue.

### ISSUE THREAD

**Issue by LOGANLEEE** [microsoft/vscode#66262]
- VSCode Version: Version 1.30.1 (1.30.1)
- OS Version: 10.14.2

Steps to Reproduce:

[https://youtu.be/hcjKIU7o62w](url)

please check this video. Thank you.

**Comment by npirlot** [comment]
I think the title of the issue can be a bit more specific, like "add horizontal scroll on files tree".
I agree not seeing files with longer paths/filenames is very annoying.

**Comment by RMacfarlane** [comment]
Ok, so to summarize the video, you have the "Horizontal Scrolling" setting turned on, and for a while horizontal scrolling works, but then it stops working. You noted that you have the VTools extension installed - do you still see the problem if you run with extensions disabled? When horizontal scroll stops working, can you run the command `Developer: Toggle Developer Tools` to see if there is anything in the console?

**Comment by RMacfarlane** [comment]
You can use the `Toggle Sidebar Visibility`(Cmd+b) and `Toggle Panel Visibility` (Cmd+j) commands to hide these
