### ISSUE TITLE
Unable to start debugging. GDB failed with message not in executable format.

### ISSUE THREAD

**Issue by caprice24** [Microsoft/vscode#66261]
I'm unable to run Windows VS Code with the MingGW gdb debugger. Getting this Error:
"Unable to start debugging. Program path 'C:\VisualStudioCode\Chap01\main.exe is missing or invalid"
"GDB failed with the message: "C:\VisualStudioCode\Chap01\main.exe": not in executable format: File format not recognized."

I'm able to run the gdb debugger from MingGW 64 bit (Version 7.3.0)  just fine from the command line, but it acts up when invoked from within VS Code using the Debug (gdb) Launch menu command.

Here is my c_cpp_properties.json:
{
    "configurations": [
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE"
    ],
    "compilerPath": "C:/MinGW64/mingw32/bin/gcc.exe",
    "intelliSenseMode": "clang-x64",
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": ""
    }
}
],
"version": 4
}

Here is my launch.json:
{
    "version": "0.2.0",
    "configurations": [
      
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/MinGW64/mingw32/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build hello world"
        }
        

        
    ]
}

Here is my tasks.json

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build hello world",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g", "main.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

main.cpp:
#include <iostream>

int main() {
    int x = 10;
    int y = 20;
    
    std::cout << "hello world" << std::endl;
    system("pause");
}

I looked at other forums that said it might be an issue between running 32 bit version of g++ vs 64 bit gdb, but I don't think that is the issue since it runs fine from the command line.

Extensions were all disabled when I tried to debug the issue, the error still happened.
Here is the list of extensions I have:

![capture2](https://user-images.githubusercontent.com/26287865/50878059-a7e8a600-1389-11e9-9ff1-2168c6f3e570.JPG)
Additional extensions not shown above:
+ Ruby extension
+ SQL Server
+YML

![capture](https://user-images.githubusercontent.com/26287865/50877901-ddd95a80-1388-11e9-9265-a97e63429c4f.JPG)

**Comment by RMacfarlane** [comment]
Hi @caprice24, this debugger support is actually added by the C++ extension (You may have missed hitting 'Reload' when disabling extensions). Can you please open this issue on https://github.com/Microsoft/vscode-cpptools? They should be able to help. Thanks!
