### ISSUE TITLE
Access Code Insiders from terminal

### ISSUE THREAD

**Issue by sbeleidy** [Microsoft/vscode#6627]
- VSCode Version: 1.1.1-insider
- OS Version: Mac OS X 10.11.4

Is there a way to access the insider build from the command line similar to the `code` command for the regular build? If there isn't are there any plans to add it?

**Comment by bpasero** [comment]
Try `code-insiders` from the command line.

**Comment by sbeleidy** [comment]
Thanks - I just found the issue. It wasn't added to my path. (I had tried several variations and just now realized that I should add to path from the command palette) 
Thank you.

**Comment by dawsonbotsford** [comment]
For other people's reference, you can manually add the current build (whether insiders or not) to your PATH by opening the vscode command pallet and entering `Install "<code or code-insiders>" in PATH`.

It'll look like this:

<img width="601" alt="screen shot 2016-12-15 at 1 58 31 pm" src="https://cloud.githubusercontent.com/assets/3408480/21243639/94d30b2c-c2ce-11e6-8f1b-67a1e36e0058.png">
