### ISSUE TITLE
Automatically hangs while compilling

### ISSUE THREAD

**Issue by Ganeshbhatpk34** [microsoft/vscode#66278]
Issue Type: <b>Bug</b>

hangs completly in Lubuntu 18.4

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:21:33.585Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics (4 x 1520)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 3, 3|
|Memory (System)|3.31GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Angular-BeastCode|Mik|7.0.28

</details>

**Comment by Tyriar** [comment]
What hangs? How are you compiling?

**Comment by Ganeshbhatpk34** [comment]
@Tyriar Hey Hi, I am using VS editor for Angular Development , but when it comes to compiling it's hangs and i cannot able to do any things .. Why is that ? What makes it becomes slow ? How to overcome any suggestions ??

**Comment by KK220794** [comment]
@Tyriar The same is happening with me while developing Angular Apps. It sometime automatically compiles and hangs and then asks to either wait or reopen VS code. 
![test1](https://user-images.githubusercontent.com/46670285/58003452-72558580-7afe-11e9-8fbd-b3781e4227fa.png)
![test2](https://user-images.githubusercontent.com/46670285/58003453-72ee1c00-7afe-11e9-9918-6653cbb35270.png)

**Comment by Tyriar** [comment]
This issue is stale and I don't think it's relevant anymore. @KK220794 you're probably seeing https://github.com/microsoft/vscode/issues/71966
