### ISSUE TITLE
Cannot close 'Cannot find a program to debug' with mouse click

### ISSUE THREAD

**Issue by dhyey35** [microsoft/vscode#66274]
Issue Type: <b>Bug</b>

Step 1: Open a node project which does not have a `launch.json`
Step 2: Press F5 and select `Node.js` with mouse left click (don't use keyboard)
Step 3: Modal `Cannot find a program to debug` appears
Step 4: Try closing it with mouse click (don't use `Enter` or `Esc` keys)

Note: This happens only when `Node.js` in step 2 is done with mouse click. If `Node.js` is selected with Enter key this issue doesn't happen.

![vscode-issue](https://user-images.githubusercontent.com/11143604/50896281-9ad1c280-142e-11e9-9308-bb4afa258e57.gif)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.77GB (0.83GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by connor4312** [comment]
Could not reproduce on recent builds of VS Code with the new debugger
