### ISSUE TITLE
Menu popup scrolling up (Pulling up) automatically. 

### ISSUE THREAD

**Issue by Dhineshss** [Microsoft/vscode#66273]
Issue Type: <b>Performance Issue</b>

Menu popup window gravity pulling up even I scrolling down. 

(1366x728) resolution. 

Note: It's working fine without zoom...

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1623)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.71GB (1.88GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   134	 20970	code main
    0	    39	 20974	   zygote
    0	   292	 21013	     window (CacheController.ts - api_mobile - Visual Studio Code)
    0	     0	 21066	       /bin/bash
    0	   111	 21075	       extensionHost
    0	   197	 21201	         electron_node tsserver.js 
    0	    87	 21274	           electron_node typingsInstaller.js typesMap.js 
    0	    95	 21207	         electron_node tslintServer.js 
    0	    63	 21305	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=21075
    0	    55	 21564	         /usr/share/code/code /usr/share/code/resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=21075
    0	    95	 21565	         /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=21075
    0	    63	 21083	       watcherService
    0	    55	 21194	       searchService
    0	   126	 21328	       node /usr/bin/tsc --watch -p /home/dhinesh/_DDrive/_INTEREST/_Programs/WEB/NODE_JS/projects/2018/invoice-temple/apis/api_mobile/tsconfig.json
    0	    95	 21103	     shared-process
    2	   103	 21582	     window (Issue Reporter)
    0	    95	 21006	   gpu-process
    0	     0	 21603	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 21604	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CacheController.ts - api_mobile - Visual Studio Code)
|    Folder (api_mobile): 182 files
|      File types: js(97) ts(74) json(6) txt(2) babelrc(1) gitignore(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1) launch.json(1)
|                  settings.json(1) tasks.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.42
php-intellisense|fel|2.3.10
macros|ged|1.2.1
MagicPython|mag|1.1.0
code-beautifier|mic|2.1.0
es6-css-minify|olb|2.2.0
autolaunch|phi|2.0.2
material-icon-theme|PKi|3.6.2
vscode-icons|rob|8.0.0
wg-getters-and-setters|Wil|1.1.6

(8 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@Dhineshss Can you include a screenshot? I'm not sure what UI you're talking about

**Comment by Dhineshss** [comment]
Please check the screenshot.
Menu window is always going up even if scroll down. 

![scrolling issue - 2019-01-10 11-59](https://user-images.githubusercontent.com/6842173/50950304-93162a80-14cf-11e9-840a-10605e425b64.gif)

**Comment by sbatten** [comment]
this should be resolved in the latest insiders
