### ISSUE TITLE
XML comment formatting issue

### ISSUE THREAD

**Issue by zbendefy** [Microsoft/vscode#66282]
- VSCode Version: 1.28.2
- OS Version: Windows 10

Steps to Reproduce:
1. Open VSCode, 
2. Create a new file
3. Copy the XML sample below, and select the XML formatter
4. The entire code after <breakfast_menu> becomes green

![xml_formatting_issue](https://user-images.githubusercontent.com/9197376/50905098-4a546800-1422-11e9-874a-434340b57836.JPG)

```
<?xml version="1.0" encoding="utf-8"?>
<breakfast_menu>
  <!----------------------------------------------------------------------------
    --                              MyComment                                --
    ---------------------------------------------------------------------------->
<food>
<name>Belgian Waffles</name>
<price>$5.95</price>
<description>
Two of our famous Belgian Waffles with plenty of real maple syrup
</description>
<calories>650</calories>
</food>
<food>
<name>Strawberry Belgian Waffles</name>
<price>$7.95</price>
<description>
Light Belgian waffles covered with strawberries and whipped cream
</description>
<calories>900</calories>
</food>
</breakfast_menu>
```

**Comment by alexr00** [comment]
Please correct me if I'm wrong, but I think that's an invalid comment: https://www.w3.org/TR/REC-xml/#sec-comments.
