### ISSUE TITLE
Let NPM extension warn when git changes package.json

### ISSUE THREAD

**Issue by csvn** [microsoft/vscode#66288]
Something that happens to me and people I've worked with very often is that I change a branch or pull some changes, which changes `package.json`. Often when this happens, it goes unnoticed until some compilation error. It would be extremely helpful if the `Npm support for VS Code` built-in extension could notice when `dependencies`/`devDependencies` in a `package.json` file is changed. It could then display a helpful notification with a "Run install" button.

I think most of the logic for this should already be in place, since the npm extension finds tasks in the workspace already. Adding dependencies as fields it will monitor would hopefully be simple. The main thing would be to monitor when they change as a result of a git operation instead of when the user themselves add packages (manually or via `npm install x`).

- The notification could be configured on/off via user settings
- The button "Run install" could open `npm install` as a task

--------------------------------------------------

* Is this something that could be considered for the built-in npm extension, or should this be left to a regular extension?  
* If this can be considered for the built-in npm extension, would PR's be welcome?

**Comment by jabacchetta** [comment]
WebStorm has a similar feature, and it's very useful for the reasons mentioned by the OP.

It'd be nice if, in general, this notification appeared whenever the package.json is changed and when `node_modules` is removed/modified. Notifying for packages that aren't installed (that appear in the package.json), packages that need to be updated (package.json has changed), and packages that should be uninstalled (they do not appear in the package.json).

There are a couple of extensions that attempt to solve these issues, but none that have done it well so far.
