### ISSUE TITLE
Can't assign a specific color for function parameters in PHP

### ISSUE THREAD

**Issue by kinoute** [Microsoft/vscode#66283]
- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Create a simple php script with a function and parameters
2. No matter what color scheme is applied, the parameters have the same style as the other variables in the script

Does this issue occur when all extensions are disabled?: Yes

Hi,

While trying to import a custom color theme from Sublime to VSCode, I found out that I couldn't associate a color to function parameters in PHP. No matter what color theme I apply (from the most popular ones to mine), the color of the function parameters can't be changed. It doesn't seem to be a problem with other languages such as ruby or javascript:

Ruby
![capture d ecran 2019-01-09 a 15 10 23](https://user-images.githubusercontent.com/623763/50905168-7b349d00-1422-11e9-816d-b05c5d6f1e15.png)

JS
![capture d ecran 2019-01-09 a 15 10 18](https://user-images.githubusercontent.com/623763/50905183-84be0500-1422-11e9-92d1-53d7edac2f07.png)

PHP
![capture d ecran 2019-01-09 a 15 10 11](https://user-images.githubusercontent.com/623763/50905195-8d164000-1422-11e9-99d6-7b0213b91761.png)

Here is what I get when inspecting the TM Scopes:
![capture d ecran 2019-01-09 a 15 12 35](https://user-images.githubusercontent.com/623763/50905210-930c2100-1422-11e9-8040-c82db3c90226.png)

If I use the scope `variable.other.php`, it does change the color of the function parameters, but it also changes the color of all the other variables. I also tried `meta.function.parameter.typehinted.php`, `meta.function.parameters.php`, `meta.function`. None of them worked, the parameters remain like the other variables.

**Comment by usernamehw** [comment]
Can you paste some `php` code?

**Comment by kinoute** [comment]
```php
<?php

function multiply(int $first, int $two) : int
{
    return $first * $two;
}
```

The parameters inside the parenthesis, have the same color/style of the variables inside the function, no matter what scope is used.

**Comment by usernamehw** [comment]
```json
{
	"scope": [
		"meta.function.parameter variable",
		"meta.function.parameter punctuation.definition.variable.php"
	],
	"settings": {
		"foreground": "#4ca03c"
	}
}
```

**Comment by kinoute** [comment]
Well, I must terribly bad with TM grammar. Thank you, it works perfectly!
