### ISSUE TITLE
suggestion result was strange

### ISSUE THREAD

**Issue by wszgrcy** [Microsoft/vscode#66285]
Issue Type: <b>Bug</b>

I use typescript&&angular. I has a property like 'xxx' in class
Before,when I input 'xxx' ,the suggestion is also return first or near the front.
But now the result is not very accurate.The property weight seems to have fallen.
I don't know if it's the reason for the update new version?Or some setting need change

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
Bookmarks|ale|10.1.0
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.0
code-runner|for|0.9.5
beautify|Hoo|1.4.7
vscode-power-mode|hoo|2.2.0
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
json-to-ts|Mar|1.5.5
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|7.0.28
vscode-scss|mrm|0.6.2
vscode-language-pack-zh-hans|MS-|1.30.2
debugger-for-chrome|msj|4.11.1
tsimporter|pmn|1.2.14
view-in-browser|qin|0.0.5
typescript-hero|rbb|3.0.0
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
markdown-preview-enhanced|shd|0.3.11
autoimport|ste|1.5.3
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|1.8.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by wszgrcy** [comment]
@mjbvz all extensions were enabled

**Comment by mjbvz** [comment]
Please try disabling them and using VS Code insiders
