### ISSUE TITLE
[php] Suggest '<?php'

### ISSUE THREAD

**Issue by Leclex** [Microsoft/vscode#663]
When I want to type "<?php", auto completion dosen't suggest 'php', so I had to press Esc key to  keep going.

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/670

**Comment by Leclex** [comment]
**Describe it again:** When I want to type `<?php`, auto completion dosen't suggest `php` but other words of `php_` prefix, e.g. `php_ini_loaded_file`, so I had to press `Esc` key to keep going.

**Comment by zbandhan** [comment]
I am facing the same disturbing problem

**Comment by osjn** [comment]
**Please add this feature quickly, I think it's a basic feature, thank you guys.**

**Comment by aeschli** [comment]
added for the March release with ee9e74c
