### ISSUE TITLE
VS opens 2 instances of the same file when open folder is used to a remote location

### ISSUE THREAD

**Issue by ademyankov** [Microsoft/vscode#66305]
When a remote folder is opened via 'open folder' something is messed up with VS Code's file manager or file finder/intelly-sence/project explorer (whatever)! There is no way for me to pinpoint which/what module fails exactly.

This issue doesn't manifest itself when 'open folder' opens files/folder on a local file system.

- VSCode Version:

![image](https://user-images.githubusercontent.com/13845895/50928990-f725e980-1410-11e9-8caf-4761e06fd728.png)

- OS Version (64-bits):

![image](https://user-images.githubusercontent.com/13845895/50929369-e164f400-1411-11e9-8cdf-bfc6f421fddd.png)

Remote location is an ubuntu machine (Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)); Linux folder is mapped via SMB into Windows.

SMB:
```
PS C:\WINDOWS\system32> Get-SmbConnection
ServerName  ShareName UserName        Credential      Dialect NumOpens
----------   --------     --------    ----------      -------   --------
10.x.x.x           projects       CORP\xxxx        CORP\xxxx     3.1.1    16
```

Steps to Reproduce:

1. Use any C/C++ library/project w/ multiple files to open it via open folder on a remote location
2. Open any C/C++ file
3. Put cursor on an object that has a declaration/definition in a different file within the library/project
4. F12 or context menu => Go To Definition
5. Observe a file opend as a weird instance (All capital letters)
6. If you go to VS Code's File Explorer you can open exactly the same file and it will be opened in a normal way, with proper file name and path.

It is quite hard to explain it, much easier to show. Here is a link to OneDrive w/ video file reproducing the issue.

https://1drv.ms/f/s!AtpTCHofGaP7jEANJuyM85-lSCSc

Does this issue occur when all extensions are disabled?: Yes/No
**YES**

**Comment by bpasero** [comment]
@ademyankov can you copy the path of both files to see if there is a difference? This is probably a duplicate of https://github.com/Microsoft/vscode/issues/12448

**Comment by ademyankov** [comment]
@bpasero The difference is that one file is all caps and another is normal, and then in open editors, it is displayed differently w/ absolute and relative paths respectively.

Right Click => Copy Path:
\\10.1.121.87\PROJECTS\NEPTUNE\SOURCE\CORE\NPTARRAY.H
\\10.1.121.87\projects\Neptune\Source\Core\NptArray.h

![image](https://user-images.githubusercontent.com/13845895/51050872-0dee4c80-1587-11e9-9b34-dd1eec35da6e.png)

And I looked into #12448 thanks for the reference... What very upsetting is that this issue is as old as ... 2 years???
