### ISSUE TITLE
Editor language changing issue

### ISSUE THREAD

**Issue by leeminki02** [microsoft/vscode#66314]
I use Korean for my mother tongue, and once I open another window and get back to the vscode, first input that I type (though IME setting says it's korean) is printed in English.
For Example, when I input "강조합니다", it looks like "rㅏㅇ조합니다"
(This issue is highlighted in magenta color in image)

Also, When I type in Korean in Markdown Editor, I get double cursors, front and behind the text I wrote.
Like this: when I input ㄱ, it shows like |ㄱ|.
(This issue is highlighted in skyblue color in image.)

![vscode error](https://user-images.githubusercontent.com/40240902/50949012-f0b67100-14e7-11e9-971e-72e7ee56dc79.jpg)

Sorry for my short English. I hope this issue gets solved as soon as possible.

**Comment by git4892** [comment]
My mistake.. It was not only a issue for markdown. It's happening for other languages, also. :(

**Comment by rebornix** [comment]
@leeminki02 could you try latest VS Code and see if you can reproduce, I'm wondering if it's a chromium issue which is already fixed upstream.

**Comment by leeminki02** [comment]
@rebornix Yeah, I think it's fixed now! Thanks for the notice! :)
