### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by shailee2409** [Microsoft/vscode#66313]
Issue Type: <b>Bug</b>

the live server is installed but go live function is not shown on the status bar

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.41GB (1.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|3.0.2

</details>

**Comment by beastdestroyer** [comment]
You need to enable it in Live Server in Settings. I believe the option is something like Always show in status bar so look there. Unrelated to VSCode
