### ISSUE TITLE
IDE slows to freeze as more and more output written to internal debug console

### ISSUE THREAD

**Issue by szmcdull** [Microsoft/vscode#66311]
- VSCode Version: 1.30.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Debug a GO program
2. The program writes to the standard output
3. IDE starts to slow down and finally freeze.

**Comment by szmcdull** [comment]
```
$ code --status


Version:          Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)
Memory (System):  15.66GB (9.57GB free)
VM:               40%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       97    3648  code main
    0      148    1080     gpu-process
    0       88    9172     shared-process
    8      361   11536     window (config.go - trade - Visual Studio Code)
    0       13     572       electron-crash-reporter
    0       92    3688       extensionHost
    0       35   15976         "C:\Users\EDZ\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\EDZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3688
    0       36    7536       electron_node goDebug.js
    0       37    2632         c:\golibs\bin\dlv.exe debug coinzone_server --headless=true --listen=127.0.0.1:25764 --api-version=2 -- -debug
    0       15    6024           c:\code\trade\src\coinzone_server\debug -debug
    0        9    7256           console-window-host (Windows internal process)
    0       37    7576       searchService
    0       15   12616       watcherService
    0       10    9984         console-window-host (Windows internal process)
    0        6   12700       winpty-process
    0        9    2884         console-window-host (Windows internal process)
    0        5    8688         "C:\Program Files\Git\bin\bash.exe"
    0       10    8700           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0       62   11540     window (Issue Reporter)

Workspace Stats:
|  Window (config.go - trade - Visual Studio Code)
|    Folder (trade): 2618 files
|      File types: go(2098) md(118) a(59) s(51) sh(33) yml(26) gitignore(16)
|                  c(13) h(11) txt(10)
|      Conf files: makefile(5) launch.json(3) settings.json(1)
|      Launch Configs: go(2) python
```

I checked task manager. The top CPU process is Code.exe --type=render --js-flags=--nolazy ...
This happen for any GO program, as GO only support internal debug console. I have not checked other languages yet.
Yes. This happens only recently, maybe for about a week. That is since the recent 2 or 3 updates of VSCode.

**Comment by sbowler** [comment]
I also see this same issue and was about to report it. In the last month or so I think it started happening. Whenever we save a file webpack automatically re-builds and outputs a lot of the build information to the console. At first everything is fine, but after a while as the console gets longer it starts to freeze vscode for several seconds before the IDE is responsive at all. 

I've recently found that clearing the debug console "fixes" the issue so we are now able to work around this for now by occasionally clearing the debug console.

**Comment by fourpastmidnight** [comment]
This is also happening for me and coincides with the introduction of Electron 3.x.

**Comment by fourpastmidnight** [comment]
I should note, however, that I have no text in my debug console pane.

**Comment by isidorn** [comment]
There was a similar issue we fixed a couple of weeks ago.
Can you please try reproducing with vscode insiders https://code.visualstudio.com/insiders/

**Comment by fourpastmidnight** [comment]
Unfortunately, I failed to mention that I am using VS Code Insider— as I mentioned this slowness really became apparent for me with the introduction of Electron 3.x into VS Code (Insiders).

Sent from my Windows 10 phone

**Comment by isidorn** [comment]
@fourpastmidnight please provide reproducable steps
@szmcdull can you reproduce with vscode insiders?

**Comment by alexpmorris** [comment]
I'm having the same issue since the latest update.  I even set the max scrollback for the debug pane to 100 lines, and it still eventually freezes up with really high CPU usage.  In this case, it's simply the debug output of a nodejs script, also running on Windows 10 x64.

**Comment by szmcdull** [comment]
@isidorn I just have time to install the Insiders. And yes, I can reproduce the problem with the Insiders. It's even getting worse. It is now much sooner for the UI to get frozen.

**Comment by isidorn** [comment]
Sounds like duplicate of https://github.com/Microsoft/vscode/issues/65213
If you have different steps let us know
