### ISSUE TITLE
SCSS compiler fails if @import command path has relative path to upper folder

### ISSUE THREAD

**Issue by hiromi3** [Microsoft/vscode#66310]
For example, in my_test.scss file, 
@import "my.scss";
@import "./myfolder/my.scss";
These commands work fine.

But, the follwoing commands fails
@import "../myfolder/my.scss";
@import "../../myfolder/my.scss";
@import "../../../myfolder/my.scss";

I tested for the following two SCSS compiler extensions,
Easy SASS
Live SASS Compile
For these two compilers, I could reproduce the problem.

I disabled all the extensions except these two, but the problem reproduced.

So, I think that if the @import command path has relative to upper folder, there is something wrong.
If you can reproduce the problem, please fix.

**Comment by RMacfarlane** [comment]
Hi @hiromi3, since these two extensions are responsible for compiling, can you please report this issue in their repositories? I don't think this is a problem with VSCode itself. Thanks!
