### ISSUE TITLE
why can search match nonexisting files ?

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode#66315]
- VSCode Version: 1.30.1
- OS Version: ubuntu 16.04.4

Steps to Reproduce:

1. I have a  `create-cluster-view.ts` file in an angular project( angular cli bootstrapped), then i renamed it to `create-cluster-vo.ts` using `Move TypeScript` provided by `Move TS extension`
2. search any keyword in `create-cluster-view.ts` file, and the search results include the nonexisting  `create-cluster-view.ts` file
3. right-click the first matched file `create-cluster-view.ts` in search results, and click `Copy Path` to get the path, and then run `cat $the-copied-path`, it tells there is no such file
4. snapshot:
![2](https://user-images.githubusercontent.com/1210201/50950208-28bbb500-14e4-11e9-891e-c571463e3809.JPG)

Does this issue occur when all extensions are disabled?: No

**Comment by bruceauyeung** [comment]
i find the reason now:
after i `Move TS` this file, there is still a tab opening `this create-cluster-view.ts` and the tab says `deleted from disk`. if i close this tab, the search results will become what i expect

**Comment by roblourens** [comment]
Thanks for following up!
