### ISSUE TITLE
Click on first non-whitespace character brings cursor to beginning of line

### ISSUE THREAD

**Issue by gcrabbe** [microsoft/vscode#66326]
- VSCode Version: 1.30.2
- OS Version: Linux Mint 19 (Linux x64 4.15.0-43-generic)

Depending on the zoom level (reproduced with Zoom Level = 1 on a 1920 x 1200 screen), clicking on a specific pixel of the first non-whitespace character of a line will unexpectedly place the cursor at the beginning of the line:

![mwe](https://user-images.githubusercontent.com/28896839/50957618-f8155480-14be-11e9-8a4e-8b99b6541605.gif)

However, if the cursor is already placed right before the first non-whitespace character, clicking on the offending pixel will not bring the cursor to the beginning of the line.

The issue occurs for all indentation levels and font sizes, and goes away when the zoom level is reset.

Steps to Reproduce:

1. Set Zoom Level to 1.
2. Click on the offending pixel of the first non-whitepace character of an indented line.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kenny407** [comment]
I was able to reproduce this with the version.
VSCode: Version 1.30.2 (1.30.2)
MacOS Mojave: 10.14 (18A391)

I deleted all the extensions added to my VSCode (around 40) too bad I didn't keep the list, also removed this: 

To delete the extensions stored for your user.
```rm -rf $HOME/.vscode```

Removed it from my Applications (mac specific) and then installed again the 1.30.2 (latest stable version at this time)

**Comment by alexandrudima** [comment]
We are always calling the same method, `document.caretRangeFromPoint`. We have noticed weirdness in the past on Chromium on Linux, where the method would return offset 0 when clicking somehow between lines. I guess the zoom level exposes yet another bug in Chromium's implementation on Linux.
