### ISSUE TITLE
Breakpoints not working for python 2.7

### ISSUE THREAD

**Issue by szmcdull** [Microsoft/vscode#66324]
- VSCode Version: 1.30.2
- OS Version: Windows_NT x64 10.0.17134

Breakpoints work for python 3.x but not python 2.7.15 64bit.

If I use python 2.7.15, the program being debugged runs, but does not pause on breakpoints.

**Comment by RMacfarlane** [comment]
Hey @szmcdull, since the python debugger is contributed by the python extension, can you please open this issue there? (Should be https://github.com/Microsoft/vscode-python). They should be able to help. Thank you!
