### ISSUE TITLE
hit breakpoint but can not pause program, can not show vars/stack frames

### ISSUE THREAD

**Issue by danX-4q** [Microsoft/vscode#66327]
- VSCode Version: 1.30.2
- OS Version: ubuntu 16.04

PS.
1. run vscode within docker, show vscode's gui at ubuntu desktop.
2. vscode run as root, run with --user-data-dir

Steps to Reproduce:
1. code: https://github.com/BankLedger/safe.git | branch 2.1.0-feature-safecode | git commit 7a488bff2083646e4b896a14923815c4a34dcf3b
2. docker-compose up , with cap_add: -ALL
3. docker-compose exec bash, and then run command: code, start vscode gui.
4. switch to ubuntu's desktop, set breakpoint at pow.cpp:CheckProofOfWork
5. vscode, f5.
6. vscode can not pause program, can not show vars/stack frames; debug console can't run -exec bt.

Does this issue occur when all extensions are disabled?: Unknown, must use ms-vscode.cpptools
 to debug.

------------------------------------------------------

--> C (runInTerminal-2): {"command":"runInTerminal","arguments":{"kind":"integrated","title":"cppdbg: safed","cwd":"","args":["sh","/tmp/Microsoft-MIEngine-Cmd-kyfbqvvs.k0r"],"env":{}},"seq":2,"type":"request"}
--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.51030.1","VS.Diagnostics.Debugger.HostVersion":"14.0.51030.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.Duration":3402,"VS.Diagnostics.Debugger.Launch.IsCoreDump":false,"VS.Diagnostics.Debugger.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.SourceFileMappings":0}},"seq":4,"type":"event"}
--> R (launch-2): {"request_seq":2,"success":true,"command":"launch","body":{},"seq":6,"type":"response"}
--> E (initialized): {"event":"initialized","body":{},"seq":8,"type":"event"}
<--   R (runInTerminal-2) [3261 ms]: {"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{"shellProcessId":628}}
<--   C (setBreakpoints-4): {"command":"setBreakpoints","arguments":{"source":{"name":"pow.cpp","path":"/home/bankledger/safe/src/pow.cpp"},"lines":[264],"breakpoints":[{"line":264}],"sourceModified":false},"type":"request","seq":4}
--> R (setBreakpoints-4): {"request_seq":4,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":true,"line":264}]},"seq":12,"type":"response"}
--> E (breakpoint): {"event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"line":264}},"seq":14,"type":"event"}
<--   C (setFunctionBreakpoints-5): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":5}
--> R (setFunctionBreakpoints-5): {"request_seq":5,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":17,"type":"response"}
<--   C (setExceptionBreakpoints-6): {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":6}
--> R (setExceptionBreakpoints-6): {"request_seq":6,"success":true,"command":"setExceptionBreakpoints","body":{},"seq":20,"type":"response"}
<--   C (configurationDone-7): {"command":"configurationDone","type":"request","seq":7}
--> R (configurationDone-7): {"request_seq":7,"success":true,"command":"configurationDone","body":{},"seq":23,"type":"response"}
--> E (output): {"event":"output","body":{"category":"stdout","output":"=thread-group-added,id=\"i1\"\nGNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1\nCopyright (C) 2016 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\nThis GDB was configured as \"x86_64-linux-gnu\".\nType \"show configuration\" for configuration details.\nFor bug reporting instructions, please see:\n<http://www.gnu.org/software/gdb/bugs/>.\nFind the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\nFor help, type \"help\".\nType \"apropos word\" to search for commands related to \"word\".\nWarning: Debuggee TargetArchitecture not detected, assuming x86_64.\n=cmd-param-changed,param=\"pagination\",value=\"off\"\n"},"seq":25,"type":"event"}
=thread-group-added,id="i1"
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
<--   C (threads-8): {"command":"threads","type":"request","seq":8}
--> R (threads-8): {"request_seq":8,"success":true,"command":"threads","body":{"threads":[]},"seq":28,"type":"response"}
--> E (thread): {"event":"thread","body":{"reason":"started","threadId":999},"seq":30,"type":"event"}
--> E (output): {"event":"output","body":{"category":"stdout","output":"Stopped due to shared library event (no libraries added or removed)\n"},"seq":32,"type":"event"}
Stopped due to shared library event (no libraries added or removed)
--> E (breakpoint): {"event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"line":264}},"seq":34,"type":"event"}
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.\n"},"seq":36,"type":"event"}
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"stdout","output":"[Thread debugging using libthread_db enabled]\n"},"seq":38,"type":"event"}
[Thread debugging using libthread_db enabled]
--> E (output): {"event":"output","body":{"category":"stdout","output":"Using host libthread_db library \"/lib/x86_64-linux-gnu/libthread_db.so.1\".\n"},"seq":40,"type":"event"}
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
<--   C (threads-9): {"command":"threads","type":"request","seq":9}
--> R (threads-9): {"request_seq":9,"success":true,"command":"threads","body":{"threads":[{"id":999,"name":"safed"}]},"seq":43,"type":"response"}
--> E (output): {"event":"output","body":{"category":"stdout","output":"\n"},"seq":45,"type":"event"}

--> E (output): {"event":"output","body":{"category":"stdout","output":"Breakpoint 1, main (argc=2, argv=0x7fff8746e448) at safed.cpp:196\n"},"seq":47,"type":"event"}
Breakpoint 1, main (argc=2, argv=0x7fff8746e448) at safed.cpp:196
--> E (output): {"event":"output","body":{"category":"stdout","output":"196\t{\n"},"seq":49,"type":"event"}
196	{
--> E (output): {"event":"output","body":{"category":"stdout","output":"=thread-group-added,id=\"i2\"\n"},"seq":51,"type":"event"}
=thread-group-added,id="i2"
--> E (thread): {"event":"thread","body":{"reason":"exited","threadId":999},"seq":53,"type":"event"}
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New process 1004]\n"},"seq":55,"type":"event"}
[New process 1004]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[Thread debugging using libthread_db enabled]\n"},"seq":57,"type":"event"}
[Thread debugging using libthread_db enabled]
--> E (output): {"event":"output","body":{"category":"stdout","output":"Using host libthread_db library \"/lib/x86_64-linux-gnu/libthread_db.so.1\".\n"},"seq":59,"type":"event"}
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b7b20b700 (LWP 1005)]\n"},"seq":61,"type":"event"}
[New Thread 0x7f0b7b20b700 (LWP 1005)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b7aa0a700 (LWP 1006)]\n"},"seq":63,"type":"event"}
[New Thread 0x7f0b7aa0a700 (LWP 1006)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b7a209700 (LWP 1007)]\n"},"seq":65,"type":"event"}
[New Thread 0x7f0b7a209700 (LWP 1007)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b79a08700 (LWP 1008)]\n"},"seq":67,"type":"event"}
[New Thread 0x7f0b79a08700 (LWP 1008)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b79207700 (LWP 1009)]\n"},"seq":69,"type":"event"}
[New Thread 0x7f0b79207700 (LWP 1009)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b78a06700 (LWP 1010)]\n"},"seq":71,"type":"event"}
[New Thread 0x7f0b78a06700 (LWP 1010)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b6bfff700 (LWP 1011)]\n"},"seq":73,"type":"event"}
[New Thread 0x7f0b6bfff700 (LWP 1011)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b6b7fe700 (LWP 1012)]\n"},"seq":75,"type":"event"}
[New Thread 0x7f0b6b7fe700 (LWP 1012)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[New Thread 0x7f0b6affd700 (LWP 1013)]\n"},"seq":77,"type":"event"}
[New Thread 0x7f0b6affd700 (LWP 1013)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"[Switching to Thread 0x7f0b7c9a9740 (LWP 1004)]\n"},"seq":79,"type":"event"}
[Switching to Thread 0x7f0b7c9a9740 (LWP 1004)]
--> E (output): {"event":"output","body":{"category":"stdout","output":"\n"},"seq":81,"type":"event"}

--> E (output): {"event":"output","body":{"category":"stdout","output":"Thread 2.1 \"safed\" hit Breakpoint 2, CheckProofOfWork (hash=..., nBits=528482303, params=...) at pow.cpp:264\n"},"seq":83,"type":"event"}
Thread 2.1 "safed" hit Breakpoint 2, CheckProofOfWork (hash=..., nBits=528482303, params=...) at pow.cpp:264
--> E (output): {"event":"output","body":{"category":"stdout","output":"264\t    if (fNegative || bnTarget == 0 || fOverflow || bnTarget > UintToArith256(params.powLimit))\n"},"seq":85,"type":"event"}
264	    if (fNegative || bnTarget == 0 || fOverflow || bnTarget > UintToArith256(params.powLimit))
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib/x86_64-linux-gnu/librt.so.1'. Symbols loaded.\n"},"seq":87,"type":"event"}
Loaded '/lib/x86_64-linux-gnu/librt.so.1'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib/x86_64-linux-gnu/libpthread.so.0'. Symbols loaded.\n"},"seq":89,"type":"event"}
Loaded '/lib/x86_64-linux-gnu/libpthread.so.0'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib/x86_64-linux-gnu/libanl.so.1'. Symbols loaded.\n"},"seq":91,"type":"event"}
Loaded '/lib/x86_64-linux-gnu/libanl.so.1'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/usr/lib/x86_64-linux-gnu/libstdc++.so.6'. Symbols loaded.\n"},"seq":93,"type":"event"}
Loaded '/usr/lib/x86_64-linux-gnu/libstdc++.so.6'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib/x86_64-linux-gnu/libm.so.6'. Symbols loaded.\n"},"seq":95,"type":"event"}
Loaded '/lib/x86_64-linux-gnu/libm.so.6'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib/x86_64-linux-gnu/libgcc_s.so.1'. Symbols loaded.\n"},"seq":97,"type":"event"}
Loaded '/lib/x86_64-linux-gnu/libgcc_s.so.1'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.\n"},"seq":99,"type":"event"}
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
--> E (output): {"event":"output","body":{"category":"console","output":"Execute debugger commands using \"-exec <command>\", for example \"-exec info registers\" will list registers in use (when GDB is the debugger)\n"},"seq":101,"type":"event"}
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
--> E (stopped): {"event":"stopped","body":{"reason":"breakpoint","threadId":1004,"allThreadsStopped":true,"source":{"name":"pow.cpp","path":"/home/bankledger/safe/src/pow.cpp","sources":[],"checksums":[]},"line":264,"column":1},"seq":103,"type":"event"}
<--   C (threads-10): {"command":"threads","type":"request","seq":10}
--> R (threads-10): {"request_seq":10,"success":true,"command":"threads","body":{"threads":[]},"seq":106,"type":"response"}

**-exec bt
Cannot evaluate expression on the specified stack frame.**
<--   C (evaluate-11): {"command":"evaluate","arguments":{"expression":"-exec bt","context":"repl"},"type":"request","seq":11}
--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Evaluate","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.51030.1","VS.Diagnostics.Debugger.HostVersion":"14.0.51030.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Evaluate.ErrorCode":1108,"VS.Diagnostics.Debugger.Evaluate.Message":"Invalid frameId","VS.Diagnostics.Debugger.Evaluate.IsError":true,"VS.Diagnostics.Debugger.Evaluate.ExecuteInConsole.ExecuteInConsole":-1,"VS.Diagnostics.Debugger.Evaluate.ExecuteInConsole":true}},"seq":109,"type":"event"}
--> R (evaluate-11): {"request_seq":11,"success":false,"command":"evaluate","message":"Cannot evaluate expression on the specified stack frame.","body":{},"seq":111,"type":"response"}
<--   C (disconnect-12): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":12}
--> E (output): {"event":"output","body":{"category":"stdout","output":"Kill the program being debugged? (y or n) [answered Y; input not from terminal]\n"},"seq":114,"type":"event"}
Kill the program being debugged? (y or n) [answered Y; input not from terminal]
--> E (output): {"event":"output","body":{"category":"console","output":"The program '/home/bankledger/safe/src/safed' has exited with code 0 (0x00000000).\r\n\n"},"seq":116,"type":"event"}
The program '/home/bankledger/safe/src/safed' has exited with code 0 (0x00000000).

--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.51030.1","VS.Diagnostics.Debugger.HostVersion":"14.0.51030.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":1}},"seq":118,"type":"event"}
--> R (disconnect-12): {"request_seq":12,"success":true,"command":"disconnect","body":{},"seq":120,"type":"response"}

**Comment by dbaeumer** [comment]
@danX-4q please report the issue here: https://github.com/Microsoft/vscode-cpptools since this looks like a problem with the VS Code CPP extension.
