### ISSUE TITLE
Compilation Hints Get Scrambled

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#6632]
- VSCode Version: 1.1.1
- OS Version: OSX El Capitan 10.11.4

This has been an annoying issue ever since I started using VS Code in March. I've been living with it and don't want to complain because I love VS Code, but perhaps it will help if I report it.

Steps to Reproduce:

1. Work normally and do a minor refactor, change the signature of a method, or modify a class structure
2. The compilation hints spontaneously get all scrambled and remain that way

Sometimes clicking on the error list and selecting an "error" from the list jumps me to the source location helps to snap VS Code out of it, but most often I need to save everything and restart VS Code to fix it. Then it "re-indexes" the code and the mistaken compilation error hints go away. Executing `dotnet build` doesn't do it.

Attached is a screenshot showing a very weird one that occurred spontaneously just now.

`Type 'ServiceLogRepository' already defines a member called '.ctor' with the same parameter types [netcoreapp1.0]`

I hope I'm getting the terminology decently OK here, there are probably better names for things.

![untitled](https://cloud.githubusercontent.com/assets/16694050/15455190/f9002a1e-2001-11e6-8727-91bbad040c28.jpg)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#559
