### ISSUE TITLE
Search: Can't distinguish input boxes from background when in panel and VS Light Theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#66323]
1. Move Search to the panel
2. Switch to Light or Light+ theme

The input boxes aren't discernible:

![screenshot from 2019-01-10 10-14-46](https://user-images.githubusercontent.com/22350/50958327-b84f6c80-14c0-11e9-90a1-84167eee57a0.png)

**Comment by isidorn** [comment]
@roblourens let me know if you need help with this one. Until then unassigning myself
