### ISSUE TITLE
Hello! There is a shortage of recent search history.

### ISSUE THREAD

**Issue by AndryWJ** [Microsoft/vscode#66320]
Hello! There is a shortage of recent search history.

As in sublimeText
![screenshot](https://user-images.githubusercontent.com/26705761/50953420-fc8c3e00-14bb-11e9-8087-58b8641d022d.png)

**Comment by roblourens** [comment]
I don't understand your issue, please explain in detail.

**Comment by AndryWJ** [comment]
Sorry, maybe I wrote the wrong way. I wanted to offer this functionality. "History of recent searches" as in sublimeText

**Comment by roblourens** [comment]
You can see search history by using the up/down arrow keys.
