### ISSUE TITLE
Folder search behaves different from Ctrl+F

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#66321]
Issue Type: <b>Bug</b>

1. Open a folder containing UTF-8 with BOM files
2. `((^)\w)` should also matchs `a`

![image](https://user-images.githubusercontent.com/4309091/50954784-53ad0580-14f2-11e9-8113-05719b4669db.png)

VS Code version: Code - Insiders 1.31.0-insider (28e7467661d67c05c3662ff900ee1984f7e2fbcc, 2019-01-07T06:20:02.775Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Good catch, I filed this upstream issue: https://github.com/BurntSushi/ripgrep/issues/1163

**Comment by roblourens** [comment]
Fixed upstream.
