### ISSUE TITLE
Cannot search in files for special characters

### ISSUE THREAD

**Issue by Artilaina** [Microsoft/vscode#66336]
Issue Type: <b>Bug</b>

1. Open file search (ctrl+shift+F)
2. Type something like "número de registros". Nothing is found
![buscar1](https://user-images.githubusercontent.com/25099519/50967771-6535e380-14d9-11e9-87e1-6d3332ef3379.png)
3. Change it to: "mero de registros". Lot of files are found, as expected.
![buscar2](https://user-images.githubusercontent.com/25099519/50967791-741c9600-14d9-11e9-99a6-1e1706a03937.png)

Besides, results shows wrong characters where it should be an "ú"

Note:
All files searched are **windows 1252 encoded**.

----

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-icalendar|af4|1.0.1
Bookmarks|ale|10.1.0
orclapex-autocomplete|apn|0.0.3
vscode-markdownlint|Dav|0.23.0
xml|Dot|2.4.0
graphviz-preview|EFa|1.3.0
todo-tree|Gru|0.0.112
vscode-guid|hea|1.4.0
XMLLanguageSupport|IBM|0.0.1
reg|ion|0.0.2
vscode-smart-column-indenter|lmc|0.0.13
rainbow-csv|mec|0.8.0
vscode-oracle-format|mp|0.0.71
vscode-language-pack-es|MS-|1.30.2
mssql|ms-|1.4.0
python|ms-|2018.12.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.8.0
PowerShell|ms-|1.10.2
code-settings-sync|Sha|3.2.4
vba|spe|1.2.0
dot|Ste|0.0.1
msbuild-project-tools|tin|0.2.51
plsql-language|xyz|1.7.0

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Do you have `files.encoding` set? Even though the editor can handle multiple encodings easily, you will need to set that setting for search to work properly.

**Comment by Artilaina** [comment]
I changed that value in the folder settings and it works fine now. So, VS needs to know the encoding before start a search, isn't? I was expecting that VS could guess the file encoding while searching inside the file itself.
I suposse that I could set different folder encoding: logs (utf-8), code (W1252), etc.

Thanks.
