### ISSUE TITLE
On Linux/*nix platforms VSCode not escaping spaces

### ISSUE THREAD

**Issue by mseqs** [Microsoft/vscode#6633]
- VSCode Version: 1.1.1
- OS Version: Ubuntu 16.04 LTS Linux kernel 4.4.0-22

Steps to Reproduce:

1. Try opening a folder which contains spaces

Code does not understand folders with spaces in unix environments, escaping the names in a terminal result the arguments being passed with spaces ("% code ~/my\ folder" results in argument "my folder" to the code application, which being opened inside the application results in two different folders/files).

Passing "my\ scripts\ folder/script.cs" results in four files opened, "~/my", "~/scripts", "~/folder" and "~/script.cs"

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6525 (fixed)
