### ISSUE TITLE
Prevent showing multiple dialogs from commands invocation

### ISSUE THREAD

**Issue by rmsmani** [microsoft/vscode#66331]
When a big project is opened in VS, if ALT+F+S (File Save As) is pressed, by the assumption that the key wasn't pressed, I pressed the key series once again.

The Dialog opened, and cancelled the dialog, the Dialog box is popping up for the 2nd Key series press.

Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:19.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Open a big project in VS
2. Open any file
3.Press ALT+F+S (File save as)
4. Try the step 3 before dialog box opens.
5. Cancel the dialog box
6. Again the Dialog box shown.

Does this issue occur when all extensions are disabled?: Yes/No
Not tried

**Comment by bpasero** [comment]
@rmsmani oh I see, I misunderstood the issue. So you basically manage to trigger the same command right before the dialog shows up?

**Comment by rmsmani** [comment]
Hi

If possible let me know where to fix, I can give a try to fix it.

Note I'm new to vscode contribution.

With Regards
M.Mani
+61 432 461 087

**Comment by bpasero** [comment]
@rmsmani thanks, but this is not up for contribution, sorry. I will look into this eventually as debt item.
