### ISSUE TITLE
VSCode not running 

### ISSUE THREAD

**Issue by oshiole** [microsoft/vscode#66332]
Downloaded VSCode from your site on my window laptop. After the completion of download and installation, VSCode refuses to open again.
It is just installed but doesn't run when I try opening the application

**Comment by mohnjatthews** [comment]
Hey @oshiole, I'm assuming you're trying to run VS Code from an Administrator account. 

Reboot your PC and then open up VS Code again. If VS Code still isn't open, open **Task Manager** and go to the **Processes** tab. Can you see VS Code in that list? If you can then it means something on your computer is blocking VS Code from fully opening. Maybe you have some anti-virus software that's blocking things from running. 

If you can't see VS Code in the **Processes** tab, it sounds like VS Code wasn't installed properly. Try uninstalling and reinstalling the package.

If none of that works, try booting your machine into **Safe Mode** and then opening VS Code.
