### ISSUE TITLE
Hyperlinks cannot be navigated in autocomplete documentation

### ISSUE THREAD

**Issue by trevorade** [Microsoft/vscode#66345]
**monaco-editor version:** v0.15.6
**Browser:** Chrome
**OS:** Linux

Also repros in VSCode on Linux

## Steps to Reproduce:

1.  In VsCode or Monaco, create a function with a comment like `/** [Link](http://link.com) */`
2.  Make the documentation show up via auto-complete (Ctrl-Space Ctrl-Space)
3.  Click the "Link" hyperlink in the autocomplete documentation

### Alt steps:

Open https://microsoft.github.io/monaco-editor/playground.html

Paste in:
```javascript
/** [Link](http://link.com) */
function hello() {}
```

## Result

The documentation closes.

## Expected Result

The hyperlink is opened in a new tab (or default browser in the case of VS Code).

## Note

Clicking links in documentation shown on hovering over a symbol works as expected for VS Code and Monaco. 

## Potentially related issues:

https://github.com/Microsoft/vscode/issues/8223
https://github.com/Microsoft/vscode/issues/65659

**Comment by jrieken** [comment]
This is fixed in master and 1.32

**Comment by trevorade** [comment]
Thanks.  Out of curiosity, what is the Monaco release cadence?  0.15.6 came out late November so it's been 3 months now.
