### ISSUE TITLE
Wrong indendation and wrong color highlight when using flow typing

### ISSUE THREAD

**Issue by mlostekk** [Microsoft/vscode#66344]
Issue Type: <b>Bug</b>

1) Paste the following code and observe the strange indendation

```
type Animations = Array<any>;
type AnimatableApi = {
  animate: Animations => Promise<void>,
    resetAnimation: () => (void | null),
};
```

1) The indendation of the `animate` is wrong
2) The color highlight is different for both objects `animate``resetAnimation`

![bildschirmfoto 2019-01-10 um 15 35 08](https://user-images.githubusercontent.com/10534316/50975232-59541c80-14ed-11e9-862e-738bf3c82057.jpg)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
Bookmarks|ale|10.1.0
project-manager|ale|10.2.0
jest-snippets|and|1.6.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
vscode-dash|dee|2.0.0
flow-for-vscode|flo|1.0.1
vscode-pull-request-github|Git|0.3.2
vscode-smart-column-indenter|lmc|0.0.13
Kotlin|mat|1.7.0
node-debug2|ms-|1.31.2
vscode-icons|rob|8.0.0
sort-lines|Tyr|1.7.0
vscode-react-native|vsm|0.7.0
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.7.0
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the flow extension
