### ISSUE TITLE
${execPath} is /path/electron2 instead of /path/code in linux

### ISSUE THREAD

**Issue by s97712** [microsoft/vscode#66346]
### luanch.json
```
{
	"version": "0.2.0",
	"configurations": [{
			...
			"runtimeExecutable": "${execPath}",
			...
	}]
}
```
above code are generated by this package, but `${execPath}` is `/path/electron2` in linux. When I run the extension, that will open electron2 instead of vscode

**Comment by s97712** [comment]
here is my environment
```
[s97712@s97712-pc backend]$ uname -a
Linux s97712-pc 4.19.13-1-MANJARO #1 SMP PREEMPT Sat Dec 29 15:43:56 UTC 2018 x86_64 GNU/Linux
[s97712@s97712-pc backend]$ code --version
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64
[s97712@s97712-pc backend]$ cat /usr/bin/code
#!/bin/bash

ELECTRON_RUN_AS_NODE=1 exec electron2 /usr/lib/code/out/cli.js /usr/lib/code/code.js "$@"

```

**Comment by phisch** [comment]
Experiencing the same issue. As a workaround until this is fixed, you can just point to the vscode executable yourself, instead of using `${execPath}`.

**Comment by weinand** [comment]
VS Code no longer uses "${execPath}" for extension debugging.
