### ISSUE TITLE
Ability to disable "find word under mouse"

### ISSUE THREAD

**Issue by dnlmzw** [Microsoft/vscode#66341]
I'd like a way to disable that the word under the cursor is copied into the search field, when pressing Ctrl+F.

I prefer that this only happens when I have selected a specific word.

**Comment by RMacfarlane** [comment]
Hi @dnlmzw, you can use the `editor.find.seedSearchStringFromSelection` setting to control this

**Comment by dnlmzw** [comment]
Not really possible as it also happens without the word being selected, only when the cursor is just positioned in the middle of the word.

I like that it seeds from the selection, but not without any selection.
