### ISSUE TITLE
Add files opened within Code to the 'Open Recent' file list

### ISSUE THREAD

**Issue by JensRoland** [Microsoft/vscode#66349]
Issue Type: <b>Bug</b>

It happens quite often that I close a file by accident and wish to reopen it, but I may not recall what it was called (e.g. if I accidentally hit the 'x' next to the tab I wanted to activate).

Instinctively, I look in the 'File>Open Recent' list expecting to see the file at the top of the list, but it is nowhere to be found. I would expect the list to contain the most recently closed files (as in Sublime Text), but it seems to be sorted by something else - perhaps by 'recently opened'? But when I use VS Code I will often have important project files open for weeks at a time while I am opening and closing hundreds of other files. If I close one such long-lasting file by accident, surely that is still a 'recent' file even if it was opened 12 days ago?

To reproduce:
1. Open a file 'important-project-notes.txt'
2. Open and close 10 other files
3. Close 'important-project-notes.txt'
4. Check the File>Open Recent list. You will see the 10 other files, but not the 'important-project-notes.txt' one.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.95GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.26
python|ms-|2018.12.1

</details>

**Comment by RMacfarlane** [comment]
There was another issue filed on this UI being confusing
(https://github.com/Microsoft/vscode/issues/49629), the comment there explains

> That list is populated from opening something into VSCode from outside (e.g. via command line or File > open). It is not meant to change whenever you open an editor from within. In that case Ctrl+P is the best way to open recently opened files.

This seems worth revisiting, I also wasn't sure what the second half of the "Open Recents" was before reading that.

**Comment by sbatten** [comment]
As a solution to the instance you describe `Cmd+Shift+T` will reopen the last closed editor. This isn't a solution to all issues that may arise from the current implementation of recent files, but it should help you if you just accidentally close a tab. Note that it stacks as well. i.e. you can press it 2x to get the last 2 tabs closed back.
