### ISSUE TITLE
Problems panel retains old problems

### ISSUE THREAD

**Issue by jby** [Microsoft/vscode#66343]
- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Edit a (in my case) puppet (.pp) file
2. Make an error
3. Error shown in Problems panel
4. close file and remove file from disk
5. problem is still shown in Problems panel, clicking it offers to create file
6. Restart of vscode clears history

Does this issue occur when all extensions are disabled?: Partly, Yes, since it then disables all checking...

**Comment by sandy081** [comment]
I suspect this is because the extension that creates problems is not clearing the problems. Please file an issue against the extension.
