### ISSUE TITLE
code.exe is locked by System (PID 4) - update/install does not work

### ISSUE THREAD

**Issue by yooakim** [Microsoft/vscode#66348]
- VSCode Version: 1.30.2
- OS Version: Windows 10 1809 (Build 17763.253)

Steps to Reproduce:

1. Try to update / install Visual Studio Code

Does this issue occur when all extensions are disabled?: Yes

I am not able to update nor install from scratch Visual Studio Code now. For some odd reason `code.exe` is locked by process ID 4 (system). Using [Sysinternals Handle](https://docs.microsoft.com/en-us/sysinternals/downloads/handle) shows that code.exe is indeed locked by the system.

```
~> handle64.exe -nobanner code.exe
System             pid: 4      type: File          3014: C:\Users\yooak\AppData\Local\Programs\Microsoft VS Code\Code.exe
```

This is directly after a re-boot of my system.  If I try to close the handle I can't because the `handle is invalid` :
```
~> handle64.exe -c 3014 -p 4 -nobanner
 3014: File  (R--)   C:\Users\yooak\AppData\Local\Programs\Microsoft VS Code\Code.exe
Close handle 3014 in System (PID 4)? (y/n) y
Error closing handle:
The handle is invalid.
```
How come `code.exe` is locked? Any ideas?

I'm only using Windows internal defender, not other anti-virus.

**Comment by yooakim** [comment]
For me the only solution to keep working was to install the *admin* installation. The user installation does not work.

**Comment by joaomoreno** [comment]
Thanks for the investigation. It seems that for now you're bound to use the admin installation, or disable background updates in the user installation: `"update.enableWindowsBackgroundUpdates": false`

/duplicate #47841

**Comment by allenyllee** [comment]
Hi @joaomoreno , here is my finding.

Just restarting your computer, excuting code.exe and opening process hacker to find all handles about code.exe, You'll see there is a system process handle locks the code.exe file (not yet exit code.exe, not under updating).

![snipaste_2019-02-27_21-36-38](https://user-images.githubusercontent.com/3991134/53494821-8f6b5100-3ad9-11e9-81bf-c642e4aabfe1.png)

Then exit code.exe, you'll find there are _two_ system process handle locks the code.exe file.

![snipaste_2019-02-27_21-39-02](https://user-images.githubusercontent.com/3991134/53494849-a0b45d80-3ad9-11e9-9bbb-98067b38504f.png)
![snipaste_2019-02-27_21-39-22](https://user-images.githubusercontent.com/3991134/53494865-a5791180-3ad9-11e9-9453-2330d15c6252.png)

Using process hacker to close these handles, and excuting code.exe again, you'll find no system process handle locks the code.exe file.


![snipaste_2019-02-27_21-43-22](https://user-images.githubusercontent.com/3991134/53495043-10c2e380-3ada-11e9-80a0-047babb120e6.png)

Exiting code.exe, still no system process handle.

![snipaste_2019-02-27_21-43-49](https://user-images.githubusercontent.com/3991134/53495203-68f9e580-3ada-11e9-822e-d6a91b735a50.png)

It seems that the system process locks the code.exe file when its first time excuted, and never release it. But after I manually release it, it can be deleted by update installer without error.
