### ISSUE TITLE
Regex incorrectly matching lowercase on [A-Z]

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#66357]
Issue Type: <b>Bug</b>

Paste some text in a document.
Run ctrl+F, enable regex, find [A-Z] 

Results: Matches lowercase letters when the expression should only match upper case letters. 

The option Match Case in the find box changes the behavior.

 [A-Z] should only match uppercase letters, this behavior is unexpected.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (22.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.0.0
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
xml|Dot|2.4.0
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
trimspaces|igo|0.0.24
vscode-tfs|iva|0.7.2
jbockle-format-files|jbo|3.0.0
Angular-BeastCode|Mik|7.0.28
mssql|ms-|1.4.0
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
csharp2ts|raf|0.0.22
vscode-yaml|red|0.2.1
vscode-icons|rob|8.0.0
angular-template-formatter|str|0.1.2
primeng-6-snippets|Wil|1.0.7

</details>

**Comment by natakazakova** [comment]
I've reproduced this issue, too, and cannot find duplicated capital letters in my files. Please fix it.

**Comment by rebornix** [comment]
Regex searches takes case sensitivity into account as well, so you may want to turn it on

<img width="747" alt="image" src="https://user-images.githubusercontent.com/876920/61917733-7a1d1600-af03-11e9-8c3b-116d6e8a3252.png">
