### ISSUE TITLE
tabs are not saved when re-opening vscode or restarting computer

### ISSUE THREAD

**Issue by girng** [Microsoft/vscode#66354]
- VSCode Version: Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
- OS Version: Windows 10, 64-bit

### Steps to Reproduce:

1. have some files open in the editor, drag the tabs around to a order you like
2. restart computer or re-open vscode

 
### Does this issue occur when all extensions are disabled?:  yes

Restore Windows *settings* is set to **all**

This issue has caused a great deal of pain because vscode works very nice with crystal-lang's formatter. I have around 6+ crystal files open that I use for development and I like to have them all in the same order. Helps with workflow tremendously.  But when re-opening vscode or restarting the computer, all my tabs are gone :/ Please take a look into this issue, thank you.

This has been happening for months, but I finally just decided to make an issue because it's getting really cumbersome to re-open all individual files, then re-order the tabs. This makes me want to use another editor :/. But I don't want to, because vscode has been great so far

**Comment by bpasero** [comment]
@girng 

> restart computer or re-open vscode

I would not expect this issue to happen when you re-open VSCode, does it reproduce reliably when just restarting Code?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
