### ISSUE TITLE
"Cmd+C" command does not copy and waits for second key of chord

### ISSUE THREAD

**Issue by mgurbanzade** [Microsoft/vscode#66355]
Issue Type: <b>Bug</b>

The latest update (1.30.2) spoiled cmd+c shortcut functionality. All 6 key bindings are default ones.

<img width="1063" alt="screen shot 2019-01-10 at 22 07 06" src="https://user-images.githubusercontent.com/27240114/50987835-2e38ef80-1524-11e9-9e9c-18000c6e2e92.png">

Also, shortcut hint for copy disappeared in context menu. But it works.

<img width="238" alt="screen shot 2019-01-10 at 22 08 59" src="https://user-images.githubusercontent.com/27240114/50987916-5c1e3400-1524-11e9-99a9-1df300788fdc.png">

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.19.1
vsc-material-theme|Equ|2.6.3
file-icons|fil|1.0.16
sublime-keybindings|ms-|4.0.0
vetur|oct|0.14.5
material-icon-theme|PKi|3.6.2
ruby|reb|0.21.0
slim|sia|0.1.2
vscode-wakatime|Wak|1.2.5

(5 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
What commands are shown when you search for cmd+c without the quotes? Are there any chords that begin with it? Does this also happen when you run with extensions disabled?

**Comment by mgurbanzade** [comment]
> What commands are shown when you search for cmd+c without the quotes? Are there any chords that begin with it?

Yes. Unfortunately, I forgot to search without quotes before I posted this report. There was custom chord that begin with cmd+c. I already fixed it, thank you very much!
