### ISSUE TITLE
"No console output" mode?

### ISSUE THREAD

**Issue by vors** [Microsoft/vscode#6635]
I could not figure out the following: I'd like to setup VSCode to be run from console (i.e. powershell)
When I do so, VSCode doesn't block the execution, but it start output log into the console, so it became unusable. How can I tell it not to do the logs? Also, I would suggest make it the default behavior and add the opposite flag: `--verbose`

- VSCode Version:

Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:29:20.776Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: Windows 10

### Steps to Reproduce

1. Open powershell.exe
2. Run `Set-Alias code "C:\Program Files (x86)\Microsoft VS Code\Code.exe"` so you can use it as a command.
3. Open current directory with `code .`
4. Control is returned to you

### expected

no output on the console from vscode

### actual
![image](https://cloud.githubusercontent.com/assets/816680/15455627/6dbada1e-200e-11e6-9a38-86d4b4a8aeaa.png)

**Comment by Tyriar** [comment]
This should work when running `./bin/code` or `./bin/code.cmd`, no output should happen and control should return to the terminal. You can use a `--wait` flag if you need to wait for it to terminate. Let me know if this doesn't solve the issue.

**Comment by vors** [comment]
I see, thank you for the pointer!

I still think that running batch file shim to discard output is pretty hacky way to achive the desired behavior. I.e. flash of a black cmd screen doesn't look particularly right.

BTW, where command line flags for code can be found?

**Comment by Tyriar** [comment]
@vors it's done that way to avoid launching Electron when not necessary and to suppress its output once launched, plus the different platforms launch in slightly different ways (plus .sh and .cmd are required just for Windows).

`code --help` will give you the command line flags, provided the `bin/` dir is in your `PATH`. Also see https://code.visualstudio.com/Docs/editor/codebasics#_additional-command-line-arguments

**Comment by vors** [comment]
great, thank you!
