### ISSUE TITLE
File name manipulation

### ISSUE THREAD

**Issue by PDXfoster** [Microsoft/vscode#66365]
Core functionality in every text editor includes the ability to rename a file in the working directory. After seeing it demo'd at a conference earlier this year, and some of the plugin's in the ecosystem I thought I'd give VS Code a shot. The first thing I went to do was to duplicate a file -- no dice. Seems like the hooks are already there: save as, new file, delete -- can't y'all add an option to do this in one workflow as a menu item in the core product? It's left me dumbfounded that I need a plugin in order to do very basic file manipulations like rename or duplicate in a platform that's intended for people that are creating files for a living. Invariably I need to rename or duplicate and change files dozens of times a day across projects.

VS Code's not even keyed into the OS hooks tightly enough to follow when I make _changes_ in finder because I can't do it in the app. This is the result of renaming a file:
![image](https://user-images.githubusercontent.com/45804913/51004577-1fd0e080-14f0-11e9-901a-2cd0c6ecbb3e.png)

I know it's been asked for before, but it's been a couple years...

#30400
#1886

Thanks for taking a look.

**Comment by RMacfarlane** [comment]
Hey @PDXfoster, these may not be exposed as commands for the currently opened editor, but they can be accomplished using the file explorer. For example, you can copy and paste a file there to duplicate it, using your copy+paste keybindings or the context menu:

![duplicate](https://user-images.githubusercontent.com/3672607/51006272-3cbce200-14f7-11e9-8b93-6d0093109a99.gif)

And it's also possible to rename from here, using a hot key or the context menu:

![rename](https://user-images.githubusercontent.com/3672607/51006333-84dc0480-14f7-11e9-81a0-3c1ab6496f4f.gif)

Hope that helps. I don't know much about the history of the feature requests for a command to do these. @bpasero?

**Comment by bpasero** [comment]
https://marketplace.visualstudio.com/search?term=duplicate&target=VSCode&category=All%20categories&sortBy=Relevance
