### ISSUE TITLE
UI elements near window edge are unusable

### ISSUE THREAD

**Issue by seraku24** [microsoft/vscode#66363]
- VSCode Version: 1.30.2 (user setup)
- OS Version: Windows_NT x64 10.0.17134

UI elements very near the window edge become unusable, as Windows assumes you are trying to resize the window.  This is especially problematic for already thin elements like the vertical scroll bar in the integrated terminal, where there are relatively few usable pixels:

![vscode-terminalscrollbar](https://user-images.githubusercontent.com/20533271/50996251-42560000-14d6-11e9-8e4d-1e9e061dba78.gif)

**NOTE:** I do use `"window.zoomLevel": -1`, however this issue is still very present with the default zoom level.

For reference, here is Notepad overlaid on Code, where both windows have been programmatically resized to the same coordinates:

![vscode-nonclientarea](https://user-images.githubusercontent.com/20533271/50996747-9e6d5400-14d7-11e9-8de3-9ee2293b4081.png)

Where Code can be seen is a visual indicator of Notepad's non-client area&mdash;the area where one expects to be able to resize a window.  Code's "frameless window" pushes its client area right up to the limit of the window rectangle, so there is no outside buffer.  This means Code has to give up some its visual space for resizing; and for areas of the UI that have no interactable controls, this is fine.  But something like the terminal's scroll bar is very difficult to access quickly.

**Comment by RMacfarlane** [comment]
@sbatten I'm seeing this when `titleBarStyle` is set to `custom`, but not on `native`

**Comment by sbatten** [comment]
@deepak1556 feel free to close as out of scope. I can still repro in exploration builds
