### ISSUE TITLE
Pressing Ctrl+F in Keybindings GUI should select all in input

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#66364]
Issue Type: <b>Bug</b>

The same way the majority of vscode inputs do.

VS Code version: Code - Insiders 1.31.0-insider (344f4fa361e098b49aeace9602e89275fbbd17bf, 2019-01-10T06:21:21.472Z)
OS version: Windows_NT x64 10.0.17763

**Comment by SpaceHexagon** [comment]
How this used to work: 
⌘+F searches.
⌘+A selects everything in search box so you can paste or erase.

Currently ⌘+A does nothing once you have searched for anything.

**Comment by usernamehw** [comment]
@sandy081, doesn't work like other inputs: when input focused and <kbd>Ctrl</kbd>+<kbd>F</kbd> should select all too.
