### ISSUE TITLE
VScode Ubuntu: How to set the terminal to Konsole?

### ISSUE THREAD

**Issue by elieobeid7** [Microsoft/vscode#66362]
I'm using VScode and Ubuntu 16.04, I need to set Konsole terminal emulator as the default terminal because it's the only one capable of outputting proper RTL support on Linux.

I have left the shell as ZSH, I have put `Terminal › External: Linux Exec: Konsole` and I changed the terminal settings from integrated to external.

That did not work, VScode terminal either crushes or revert back to the default one, which I think is Xterm. Is there a solution? Stackoverflow couldn't solve it so far

https://stackoverflow.com/questions/54128825/vscode-ubuntu-how-to-set-the-terminal-to-konsole

**Comment by Tyriar** [comment]
Works for me, it's probably a problem with your setup. Also if you're using a capital K as you indicate it won't work, maybe that's it?

![image](https://user-images.githubusercontent.com/2193314/51002421-09bf2200-14e8-11e9-9207-066b16bed147.png)

**Comment by elieobeid7** [comment]
How did you launch it? And how did you edit the settings in json, the newest version won't allow me to do that. Please note I'm using unity, I forgot to mention that,  Here's a screenshot

![2](https://user-images.githubusercontent.com/660142/51037864-23c93500-15ba-11e9-8038-f9fcff2ebf2a.png)


Above you see I specified `konsole` with a lower case k, and I specified external. 

I restarted VScode and I did `ctrl + `` and you can see it didn't change.

1-  `ps -o 'cmd=' -p $(ps -o 'ppid=' -p $$)` outputs the emulator you are using
2- The arabic output is still messed up, in konsole, that won't happen, they support Arabic

**Comment by Tyriar** [comment]
ctrl+` is the integrated terminal, ctrl+shift+c is konsole. In case it wasn't clear, you cannot run konsole inside of vscode, the terminal in vscode is it's own terminal emulator. RTL support in vscode's terminal is captured here https://github.com/xtermjs/xterm.js/issues/701
