### ISSUE TITLE
Include TypeScript version in TS Server errors

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#66368]
Steps to Reproduce:

1. In a TS file when using TS typescript@3.3.0-dev.20190110

```ts
console.log()


```

2. Manually request signature help on the last (empty) line of the file using the keyboard shortcut

**Bug**
In the dev tools console, we show an error but do not include the typescript version that causes this error. It would be helpful to know if a user has configured vs code to use and older or newer version of typescript  when they report issues

**Comment by dbaeumer** [comment]
Removed bug label. @mjbvz please correct if this was a bug.
