### ISSUE TITLE
--reuse-window and OS X fullscreen window switching

### ISSUE THREAD

**Issue by mwillsey** [Microsoft/vscode#6637]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.5 (15F34)

Steps to Reproduce:
1. Open VSCode and Terminal
2. Make them both fullscreen (either split screen or same screen)
3. In the fullscreen Terminal, run `code --reuse-window`
4. Observe that OS X snaps you back to the original Desktop that you opened the two apps in, then back to VSCode.

**Comment by bpasero** [comment]
I can reproduce. Weird!

**Comment by bpasero** [comment]
My feeling is that this happens because the main process of VS Code is associated with the first desktop and the second window talks to the main process to bring up the window. I am not sure how to change this.

**Comment by bpasero** [comment]
@mwillsey I think I cannot reproduce this anymore with 1.8. Can you try?

**Comment by mwillsey** [comment]
@bpasero Me neither. I guess it got fixed!
