### ISSUE TITLE
no source control providers registered

### ISSUE THREAD

**Issue by aladdin-add** [Microsoft/vscode#66371]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/13050025/51068761-b53db300-165d-11e9-9fca-a5cd509660d7.png)

VS Code version: Code - Insiders 1.31.0-insider (7b375fcb821bee9342656c39492223c7b5fc8830, 2019-01-08T09:23:09.468Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 23, 16|
|Memory (System)|16.00GB (2.04GB free)|
|Process Argv|-psn_0_1810874|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
eggjs|ati|0.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
githistory|don|0.4.4
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.6
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.3.2
npm-dependency-links|her|1.0.0
vscode-npm-dependency|how|1.2.2
docthis|joe|0.7.1
vscode-github|Kni|0.30.1
vscode-kanban|mkl|1.23.1
mssql|ms-|1.4.0
cpptools|ms-|0.20.1
LiveServer|rit|5.3.1
autoimport|ste|1.5.3
vscode-import-cost|wix|2.12.0
file-size|zh9|0.1.3

</details>

**Comment by RMacfarlane** [comment]
Hi @aladdin-add, can you include more information about what project you have open? What version control system is it using (git, svn)?

**Comment by aladdin-add** [comment]
closing, since it seems the error comes from ext: live server.
