### ISSUE TITLE
Interface gets bugged when creating files/folders in two separate instances

### ISSUE THREAD

**Issue by ribice** [Microsoft/vscode#66389]
- VSCode Version: 1.30.2
- OS Version: OSX 10.14.2

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open two instances (windows)
2. In the first one, right click explorer, new file/folder
3. In the second one, right click explorer, new file/folder (on some occasions it would close the dialog in first window, but not always)
4. In the first window, right click explorer, new file/folder

I expected the previously opened dialog in first window to close, but instead this happens:

![image](https://user-images.githubusercontent.com/5403700/51027154-74c43380-1590-11e9-9f98-5e02b36ff6d8.png)
![image](https://user-images.githubusercontent.com/5403700/51027177-7beb4180-1590-11e9-80cc-ab79c6436849.png)
![image](https://user-images.githubusercontent.com/5403700/51027181-7e4d9b80-1590-11e9-813f-ae32dc97a8b7.png)
![image](https://user-images.githubusercontent.com/5403700/51027184-80aff580-1590-11e9-9c25-43481f7a1f1b.png)

**Comment by isidorn** [comment]
This will be fixed when we merge the new explorer tree to master in a couple of days.
