### ISSUE TITLE
showInformationMessage 

### ISSUE THREAD

**Issue by mjxchange** [microsoft/vscode#66387]
showInformationMessage  Why can't we change lines? 
I need to show multiple lines in showInformationMessage  and change lines.

**Comment by RMacfarlane** [comment]
Hey @mjxchange, can you add some more details? I'm not sure what you mean by "change lines" in this context

**Comment by mjxchange** [comment]
of course ，I need to split a paragraph of text into multiple lines to show it.

**Comment by hokein** [comment]
I believe this issues is about `showInformationMessage` API doesn't support `\n`, if I pass a string `first line\nsecond line`, all the content will be shown in a single line.

@bpasero is there an existing issue tracking this? And I could not found one, the issues mentioned above are not quite related to this issue.

**Comment by bpasero** [comment]
@hokein we could possibly subsume this request under https://github.com/microsoft/vscode/issues/69214

**Comment by hokein** [comment]
@bpasero Thanks, that makes sense.
