### ISSUE TITLE
get 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one error

### ISSUE THREAD

**Issue by jongwu** [Microsoft/vscode#66384]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.I want to build vscode in arm64, after clone the code and yarn, I get 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
how to do with it ?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
Hi @jongwu, have you set the `npm_config_arch` environment variable to `arm`? Please see https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites.

**Comment by jongwu** [comment]
> Hi @jongwu, have you set the `npm_config_arch` environment variable to `arm`? Please see https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites.

hi @RMacfarlane I solve this problem by asking on https://aka.ms/vscodestackoverflow, maybe there is something wrong in installing yarn in ubuntu18.04. I reinstall it then it works. anyway, thank you all the same.
