### ISSUE TITLE
Integrated terminal command search shortcut not working

### ISSUE THREAD

**Issue by avvertix** [Microsoft/vscode#66385]
Issue Type: <b>Bug</b>

After the update to Windows 10 October Update, the integrated terminal is not accepting the Ctrl+R shortcut to search across the history of commands and instead outputs `^R`

![image](https://user-images.githubusercontent.com/5672748/51021752-c06fe080-1582-11e9-97ec-5b838ac44a04.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows 10 1809 x64 (build 17763.253)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz (8 x 2807)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (1.18GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.4.1
php-intellisense|fel|2.3.10
vscode-pull-request-github|Git|0.3.2
rest-client|hum|0.21.1
vscode-language-pack-it|MS-|1.30.2
azure-account|ms-|0.8.0
Go|ms-|0.8.0
vetur|oct|0.14.5
laravel-blade|one|1.18.0
vscode-docker|Pet|0.5.1

</details>

**Comment by Tyriar** [comment]
Works for me? 

![image](https://user-images.githubusercontent.com/2193314/51053552-d2f01700-158e-11e9-80e3-1ad68121b547.png)

/cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
Yeah I can't repro this either:
![image](https://user-images.githubusercontent.com/2644648/51054883-1482c100-1593-11e9-8dc4-e3e6b6c06910.png)

**Comment by avvertix** [comment]
I tried now on another computer with same OS and VSCode version and there it works. Therefore I tried to figure out if there was something different. Seems that is related to the PowerShell, as also in a standalone PowerShell the problem appears 

![image](https://user-images.githubusercontent.com/5672748/51055528-5c7c0500-15e0-11e9-85f8-5c4a229c3fda.png)

**Comment by Tyriar** [comment]
Yay, not my problem 🥂 😉

**Comment by avvertix** [comment]
Just to reference, I reported the problem in https://github.com/Microsoft/console/issues/350 and there I got some reference on similar problem happening only on localized version on Windows and the keyboard layout
