### ISSUE TITLE
Quick Open file order is not proper

### ISSUE THREAD

**Issue by sreevisakh** [Microsoft/vscode#66383]
- VSCode Version: 1.30.2
- OS Version: macOS Sierra 10.12.6 

Quick Files are in not sorted properly
eg: While searching for a file with keyword OTP following is the result

http://i65.tinypic.com/4lg5ua.png

Even though there is a path with "otp" continuously its not the first result.

Steps to Reproduce:

1. Do a file search with quick open 

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Hey @sreevisakh, I'm having problems loading the image you've included (in the future, you can directly attach or paste images into github issues), but I believe this is as-designed and that the file name takes highest precedence for queries. If you search `OTP/` it should find files on that path

**Comment by sreevisakh** [comment]
@RMacfarlane 
Here is the sample image.
![4lg5ua](https://user-images.githubusercontent.com/866258/51071440-d52da080-1676-11e9-8b6e-38ef69ffe897.jpg)
Instead of showing file with name OTP or any path with string otp it is showing Fo**ot**erS**p**ace.js,
it will be better if the file otp.js or OTP/index.js comes first.
