### ISSUE TITLE
Fail to prompt to select project language with Azure Function Extension

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode#66394]
- VSCode Version: 1.30.2(user setup)
- OS Version:Win10

Steps to Reproduce:

1. Install Azure Function Extension form the 'Extensions Explorer'.
2. In Azure Function Explorer, select 'Create New Project' button to create a new project.
3. Check whether it prompts to select a language or not.

Does this issue occur when all extensions are disabled?: Yes

Actual:
Fail to prompt to select a language and it creates a project directly.

More Info:
This issue does not reproduce in VS Code-Insider.
![image](https://user-images.githubusercontent.com/34729092/51028041-54669a00-15cd-11e9-9c1f-5733c843d314.png)

**Comment by RMacfarlane** [comment]
Hey @v-dantch, since this is behavior from an extension, please file it on the extension itself. (Also, I see a language prompt in VSCode 1.30.2 as well, with version 0.13.1 of the extension)
