### ISSUE TITLE
Git Bash sbt encoding on windows

### ISSUE THREAD

**Issue by ErikSteNL** [Microsoft/vscode#66393]
- VSCode Version: 1.30.2
- OS Version: Windows 10

Steps to Reproduce:

Make sure sbt is installed in computer.

1. create new folder
2. Open git bash terminal in vscode
3. run ```sbt```

Output when trying this is:
```
?[0m[?[0m?[33mwarn?[0m] ?[0m?[0mNo sbt.version set in project/build.properties, base directory: C:\Users\myuser\test?[0m
?[0m[?[0m?[0minfo?[0m] ?[0m?[0mLoading settings for project global-plugins from idea.sbt ...?[0m
?[0m[?[0m?[0minfo?[0m] ?[0m?[0mLoading global plugins from C:\Users\myuser\.sbt\1.0\plugins?[0m
?[0m[?[0m?[0minfo?[0m] ?[0m?[0mSet current project to test (in build file:/C:/Users/myuser/test/)?[0m
?[0m[?[0m?[0minfo?[0m] ?[0m?[0msbt server started at local:sbt-server-8994dc6ffd1f3ba345e2?[0m
sbt:test?[36m> ?[0m
```

There are a lot of "?[0m[" and other strings that should not be there (and which do not appear when launching sbt in "normal" git bash window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
