### ISSUE TITLE
Hyperlinks in console are not correctly highlighted when the link contains accented characters

### ISSUE THREAD

**Issue by khalyomede** [Microsoft/vscode#66391]
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce: 

1. Create a new project
2. Create file called `script.js`
3. Copy this content into the script:
  ```javascript
  console.log("https://github.com/Microsoft/vscode-piñata");
  ```
4. In the console, run the following command:
  ```bash
  node script.js
  ```
5. Try to hover with your mouse: only the left part without accent is highlighted, the underlining stops at the first accented character

Does this issue occur when all extensions are disabled?: Most likely (not tested)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/21125
