### ISSUE TITLE
Refactor all Shortcut key

### ISSUE THREAD

**Issue by Olti-B** [microsoft/vscode#66398]
For example when i am working and i have the code in disorder, it will be grate if i refactor the code of all the files that i am working and not doing one by one. 
So a shortcut key to refactor all

**Comment by RMacfarlane** [comment]
Hey @Olti-B, if you just want to add a short cut to an existing command, you can run the `Preferences: Open Keyboard Shortcuts` command and add a keybinding. If you want a new refactoring command to be added, can you describe what it does in more detail and what coding language you are using?

**Comment by Olti-B** [comment]
Hey @RMacfarlane firstly glad that you respond. 
What i want is when i am working 
![working_active_tabs](https://user-images.githubusercontent.com/36789108/51072759-4e70c780-1666-11e9-8de8-bd1544e48e9e.PNG)
like this for example, that i have some tabs in my working place, i don't wont to go every file  and pres refactor . But i would like a shortcut that for all tabs what i am working to make refactor to all of them.
