### ISSUE TITLE
Expose some more commands in the 'Go' menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#66395]
To improve discoverability of some of our navigation commands we should promote them from the Command palette into the 'Go' menu:

- [ ] Add 'Go to last edit location'  
- [ ] Add Go to next/previous problem/error
- [ ] Add Go to next/previous change
- [ ] Add Go to bracket

**Comment by bpasero** [comment]
@egamma where did you see "go to next change"? If that is a command from Git, we would need a way for extensions to contribute to the main menu.

**Comment by Tyriar** [comment]
@bpasero `workbench.action.editor.nextChange` and `workbench.action.compareEditor.nextChange`? I made their keybindings align to alt+f5 so this would be good to teach that.

**Comment by bpasero** [comment]
@Tyriar ah yeah, in the diff editor. I thought there was a way to navigate to changes in the file without having to open a diff.

**Comment by Tyriar** [comment]
@bpasero `workbench.action.editor.nextChange` will do that as the git ext registers diffs in the active file (I think that's how it works).

**Comment by misolori** [comment]
One idea would be to either: 
- Group them together into bigger buckets
- Show a flat list
- Combination of group and flat where the most used actions are flat

## Grouped
<img width="50%" src="https://user-images.githubusercontent.com/35271042/51217572-89c8fb80-18dd-11e9-812c-abe5505aa067.png">

```
Back
Forward
—————
Switch Editor >
Switch Group >
—————
Symbol >
  Symbol in File...
  Symbol in Workspace...
Editor >
  Go to File...
  Go to Line...
  Go to Last Edit Location
  Go to Bracket
Problems > 
  Next Problem
  Previous Problem
  Next Change
  Previous Change
Definitions >
  Go to Definition
  Go to Type Definition
  Go to Implementation
```

## Flat

<img width="50%" src="https://user-images.githubusercontent.com/35271042/51217739-1d023100-18de-11e9-81a4-2d89030e8211.png">



```
Back
Forward
————
Switch Editor >
Switch Group >
————
Symbol in File...
Symbol in Workspace...
————
Go to File...
Go to Line...
Go to Last Edit Location
Go to Bracket
————
Next Problem
Previous Problem
Next Change
Previous Change
————
Go to Definition
Go to Type Definition
Go to Implementation
```

**Comment by bpasero** [comment]
@misolori thanks for the mockups, I think having them ungrouped is fine given the amount of entries is still short.

**Comment by bpasero** [comment]
Yeah we can do that.

**Comment by bpasero** [comment]
@egamma note that the navigation in problems and changes is not global, at least when I tried. In other words these commands can only be used on the currently active file.

**Comment by bpasero** [comment]
**Verification:** bring up the "Go" menu, test all entries and ensure the order makes sense to you.
