### ISSUE TITLE
Task: Searching for task is slow on network drive. Tasks should return tasks from tasks.json before looking for more tasks.

### ISSUE THREAD

**Issue by derekwallace** [microsoft/vscode#66399]
vscode 1.30
Windows

I have a large repository.
I use a network mounted drive (the disk is a linux NAS).
Access to the disk is relatively slow compared to local disk (but fine for browsing, editing files etc...)
I already have reported that finding files with Ctrl-P is slow and unusable since there is no caching of the list of files that are found by ripgrep. It can take N minutes to find a file.

Now im starting to try out tasks. i created my HellowWorld.ts based on the VSCOde documentation.
Using Ctrl-Shift-P i try to run the task.
The issue is that it uses ripgrep to search my workspace for "tasks".
this now suffers the same issue i.e. it can take minutes to find the tasks.
This makes the feature un-usable for me.

Is there any way to run a task that is in a certain folder?
Or is there a way to tell Code that tasks are in folderA, folderB so it only looks in this location

thx
Derek

**Comment by derekwallace** [comment]
Ive created some simple tasks i want to run in the .vscode/tasks.json file.
e.g. run a command in a shell.

What i find is that when you Ctrl-Shift-P - Tasks RunTasks it spawns a rg.exe process to now look for typescript config files tsconfig.json.
In my network drive workspace this can take 10's of minutes.

Meanwhile the static file in the static location .vscode/tasks.json is ignored .....


This is similar issue to Ctrl-P and finding files in a workspace. However in this case at least you are presented with a Recently Used list immediately which is often what you want.

Why for Tasks can it not parse the tasks.json immediately and present a recently used list?

**Comment by alexr00** [comment]
Changes tasks so that tasks are shown as they load is a significant change, but would provide good user value. 

Can you try adding these to your settings and see if it gets faster?
"typescript.tsc.autoDetect": "off",
"grunt.autoDetect": "off",
"jake.autoDetect": "off",
"gulp.autoDetect": "off",
"npm.autoDetect": "off",

**Comment by derekwallace** [comment]
yes that resolved the issue.
the tasks of type shell, in tasks.json are presented immediately.

is it possible to configure it to look for tsconfig.json is a specific folder(s)

**Comment by alexr00** [comment]
The is no way currently to configure a specific location to look for tsconfig.json.

**Comment by alexr00** [comment]
No upvotes + a reasonable work around. Especially now that `resolveTask` is implemented. Closing as out of scope.
