### ISSUE TITLE
Better keyboard control of dialogs

### ISSUE THREAD

**Issue by modestotech** [Microsoft/vscode#66390]
Issue Type: <b>Feature Request</b>

I'm only able to close dialogs with escape (cancel), or accept them with enter. Other options are not available through keyboard.

![image](https://user-images.githubusercontent.com/31730051/51026826-b56f7d00-158f-11e9-85db-54d60a378bd2.png)

I'd like to be able to control this dialogue by d, c, s, or by tabbing through the options, as any native application. 

I also got problems sometimes, when a non-blocking notification appears to the bottom left. Sometimes escape works to close it, sometimes not. I suppose it's focus related.

![image](https://user-images.githubusercontent.com/31730051/51027240-a0471e00-1590-11e9-973a-053158095c7b.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

**Comment by bpasero** [comment]
@modestotech that is configurable in macOS:

![image](https://user-images.githubusercontent.com/900690/51031556-3aad5e80-159d-11e9-89b6-863505d6173e.png)

See also http://osxdaily.com/2010/02/26/use-the-tab-key-to-switch-between-dialog-buttons-in-mac-os-x/

**Comment by bpasero** [comment]
I do not think that exists on macOS, e.g. see https://superuser.com/questions/24159/osx-keyboard-shortcuts-in-dialogs

We cannot focus notifications when they appear, that would move focus out of the editor while typing, which would be horrible. There is commands to focus notifications and then you can tab around.

**Comment by modestotech** [comment]
If anyone would end up on this thread in the future, this can be achieved on Mac by setting `defaults write NSGlobalDomain AppleKeyboardUIMode -int 3`. This setting enable full keyboard access for all controls (e.g. enable Tab in modal dialogs).
