### ISSUE TITLE
[js] Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#664]
Issue Id: <b>6a266d37-8db1-03b7-8dd2-617779dcdcc3</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/languages/typescript/common/typescriptMode.ts#L459:59 (TypeScriptMode.runQuickFixAction)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/typescript/common/typescriptMode.ts#L459:59 (TypeScriptMode.runQuickFixAction))<br />[/vs/editor/contrib/quickFix/browser/quickFix.ts#L35:52 (QuickFixController.getQuickFixController)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/quickFix/browser/quickFix.ts#L35:52 (QuickFixController.getQuickFixController))<br />[/vs/editor/contrib/quickFix/browser/quickFixModel.ts#L344:20 (QuickFixModel.triggerDialog)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/quickFix/browser/quickFixModel.ts#L344:20 (QuickFixModel.triggerDialog))<br />[/vs/editor/contrib/quickFix/browser/quickFixSelectionWidget.ts#L238:3 (QuickFixSelectionWidget.constructor)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/quickFix/browser/quickFixSelectionWidget.ts#L238:3 (QuickFixSelectionWidget.constructor))<br />[/vs/base/common/eventEmitter.ts#L241:18 (EventEmitter._emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L241:18 (EventEmitter._emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L267:8 (EventEmitter._emitEvents)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L267:8 (EventEmitter._emitEvents))<br />[/vs/base/common/eventEmitter.ts#L187:9 (EventEmitter.addEmitter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L187:9 (EventEmitter.addEmitter))<br />[/vs/base/common/eventEmitter.ts#L253:21 (EventEmitter._emitToBulkListeners)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L253:21 (EventEmitter._emitToBulkListeners))<br />[/vs/base/common/eventEmitter.ts#L262:8 (EventEmitter._emitEvents)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L262:8 (EventEmitter._emitEvents))<br />[/vs/base/common/eventEmitter.ts#L285:8 (EventEmitter.emit)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L285:8 (EventEmitter.emit))<br />    at t.e.emit (out/vs/workbench/workbench.main.js:1548:10066)<br />

**Comment by aeschli** [comment]
Fix delivered
