### ISSUE TITLE
Code folding doesn't work with blocks with preprocessor macros (C++)

### ISSUE THREAD

**Issue by indigox4** [Microsoft/vscode#66404]
Issue Type: <b>Bug</b>

Repro steps:

cut and paste the following code snippet into a .cpp file:

```
void blah()
{
    if( 1 ) {
        if( 2 ) {
#ifdef FOO
            int i = 0;
#endif
        }
    }
}
```

Move the mouse to the gutter of the if(1) statement and click on the [-] icon to fold it.

Actual result:
The code folding stops at the #ifdef FOO line. 

Expected result:
The code folding should collapse everything inside the if(1) block.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.74GB (50.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
cpptools|ms-|0.20.1
mel|sat|0.1.2
cmake|twx|0.0.17
clang-format|xav|1.8.0

</details>

**Comment by indigox4** [comment]
#60670 looks like a different issue. Thanks.

**Comment by aeschli** [comment]
You are requesting c++ aware folding which needs to come from a language extensions like Microsoft/vscode-cpptools.
The extension is aware of the request: See https://github.com/Microsoft/vscode-cpptools/issues/407
