### ISSUE TITLE
VS Code insert Php snippet removing all $ symbol

### ISSUE THREAD

**Issue by ottopic** [Microsoft/vscode#66406]
- VSCode Version: 1.30.2 (1.30.2)
- OS Version: OSX 10.14.2

Steps to Reproduce:

1. Create php snippet like this: `$printMe = ${CLIPBOARD}; print_r($printMe);`
2. Insert snippet with macro for example 
`
[
            "editor.action.smartSelect.grow",
            "editor.action.clipboardCopyAction",
            "editor.action.insertLineAfter",
            {
             "command": "editor.action.insertSnippet",
                "args": {
                    "name": "customprintr",
                    "langId": "php",
                }
           },
]
`
3. Result is: `printMe = $myVar; print_r(printMe);`

The problem is that all $ inside snippet are removed. In PHP script is a big problem.

**Comment by usernamehw** [comment]
```json
"\\$printMe = ${CLIPBOARD}; print_r(\\$printMe);"
```

**Comment by RMacfarlane** [comment]
Please escape the `$` as @usernamehw has indicated. Thanks!
