### ISSUE TITLE
Unexpected intellisense behavior & warning in Sass

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6640]
- VSCode Version: Recent alpha 23c927e
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Open .scss file
2. Inside a rule add `"margin: "`
3. Trigger intellisense <kbd>ctrl</kbd>+<kbd>space</kbd>
4. Type `"0 0 0 0;"`
5. Press <kbd>enter</kbd>

![image](https://cloud.githubusercontent.com/assets/2193314/15456943/3a77aee0-2034-11e6-8a95-300426e0ea63.png)

At this point I expect the cursor to go to a new line but it tried to accept "No suggestions" and failed. I also think intellisense should be dismissed after the semi-colon `;` is entered.

**Comment by aeschli** [comment]
Not easy to reproduce, but I was able to do with triggering code assist after `border-width: 0` and entering `k`.
Pressing Enter on the 'No suggestions' window brings you the error dialog.

**Comment by joaomoreno** [comment]
I fixed the error message.

As to why the suggestion box doesn't go away on `;`, I'll leave that up to @aeschli. Moving to backlog.

**Comment by sandy081** [comment]
Assigned to myself for investigation.
