### ISSUE TITLE
A bug in the Shell Script syntax highlighting

### ISSUE THREAD

**Issue by jkmik244752** [microsoft/vscode#66409]
Issue Type: <b>Bug</b>

The following is a valid shell code snippet that currently breaks syntax highlighting.
```
${my_array[$(myprogram ']')]}
```
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-36-generic

Extensions: none

**Comment by alexr00** [comment]
Moved to owning repo
