### ISSUE TITLE
Let favorite folders stick

### ISSUE THREAD

**Issue by VitaliKaiser** [Microsoft/vscode#66402]
I often have projects with a complex folder hierarchy. Could I "star" some of the folder in order to find them faster?
I would prefer to have a separate section like "Open Editors", maybe called "Favorites" where all stared elements appear (and can be "destared"). Then I could click on one of the elements and the folder is selected/highlighted in the file explorer part. Of course these feature could also include files.
This would allow me to jump fast between the most important location for my current dev.

Thanks :D

**Comment by RMacfarlane** [comment]
https://marketplace.visualstudio.com/items?itemName=kdcro101.favorites
