### ISSUE TITLE
Rename Symbol with F2 (Refactor) doesn't extend to all Workspace's files

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/vscode#66417]
We have 2 interdependent projects (Business Central Extensions), each in a different folder, but within the same Workspace opened with VSCode.

When we press F2 to rename a symbol it is only doing it in all the files within the same project when in fact it is expected and necessary that it be done in all the files of the Workspace.

VSCode Version: **1.30.2** (user setup)
Commit: 61122 f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create 2 BC Extension Projects with a dependency but under the same Workspace
2. F2 to rename symbol in Project1 
3. We expect it refactors all ocurrences in both projects and all files, including xml translations

Example:
[WorkspaceRefactorIssue.zip](https://github.com/Microsoft/vscode/files/2751263/WorkspaceRefactorIssue.zip)

Screenshots:
![image](https://user-images.githubusercontent.com/5801847/51061807-cef6e000-15f4-11e9-986e-ddc5973794ed.png)

![image](https://user-images.githubusercontent.com/5801847/51061820-d6b68480-15f4-11e9-9318-72f50e375808.png)

![image](https://user-images.githubusercontent.com/5801847/51062325-dae3a180-15f6-11e9-980a-08c78a2c6fff.png)

**Comment by mjbvz** [comment]
How rename works is up to the extension that implements rename. Please file this issue against the al extension
