### ISSUE TITLE
 Problem with some characters

### ISSUE THREAD

**Issue by fedeemorales21** [Microsoft/vscode#66419]
Issue Type: <b>Bug</b>

I can not write the characters { and [
But if the closing

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 1300X Quad-Core Processor           (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.95GB (0.84GB free)|
|Process Argv|C:\Users\Casa\Documents\Practica\find-the-treasure-javascript-master\index.html|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.42
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
beautify|Hoo|1.4.7
vscode-language-pack-es|MS-|1.30.2
sublime-keybindings|ms-|4.0.0
format-html-in-php|rif|1.4.5
LiveServer|rit|5.3.1
vscode-icons|rob|8.0.0
sass-indented|rob|1.5.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by RMacfarlane** [comment]
Hi @fedeemorales21, do you mean that { and [ are being closed with } and ] when you do not expect them to be? Can you give an example? What kinds of files does this happen for?

**Comment by fedeemorales21** [comment]
> Hola @ fedeemorales21 , ¿quieres decir que {y [se están cerrando con} y] cuando no esperas que lo estén? ¿Puede dar un ejemplo? ¿Para qué tipo de archivos sucede esto?

When I want to insert a { or [ I do not respect the keyboard configuration (Alt Gr + ' and Alt Gr + ` ) but in other editors and in the OS if I respect the writing method

sorry for my english, it's not very good

**Comment by fedeemorales21** [comment]
> Hi @fedeemorales21, do you mean that { and [ are being closed with } and ] when you do not expect them to be? Can you give an example? What kinds of files does this happen for?


When I want to write a {or [I do not respect the keyboard shortcut and I have to write them with Alt + 123 and Alt + 91. In other editors and in the OS if you respect them.
This happened to me in the JS files



sorry for my english, it's not very good

**Comment by fedeemorales21** [comment]
solved
 The vscode-json extension modifies the function of the key

**Comment by RMacfarlane** [comment]
Thanks for the update, glad you were able to fix the problem.
