### ISSUE TITLE
Incorrect search results when using regex + whole-word when the regex ambiguously matches a prefix

### ISSUE THREAD

**Issue by atsymboldot** [microsoft/vscode#66411]
Issue Type: <b>Bug</b>

1) Open a new doc, type "ab"
2) With "Match Whole Word" and "Use Regular Expression" enabled, search for (a|ab)

Expected: 1 result for "ab"
Actual: no results found

Notably, this behavior disappears if the regex is rewritten such that the match for the whole word is found before the match for the prefix; e.g. in the above repro, searching for (ab|a) works

VS Code version: Code - Insiders 1.31.0-insider (ccdd2997a66965c7104fe180207d9a710ea50fa5, 2019-01-11T06:19:08.621Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.42
json-tools|eri|1.0.2
rest-client|hum|0.21.1
debugger-for-chrome|msj|4.11.1
fuljira|nwf|0.0.1
guides|spy|0.9.3
es6-string-html|Tob|1.8.4

</details>

**Comment by roblourens** [comment]
This is a tricky case because the "whole word" is processed as a separate step after the regex match, so "a" will match then be rejected as not a whole word match. `ab|a` will work because "ab" will match first.
