### ISSUE TITLE
Finalize naming of contributes.css / contributes.html and update JSON schema / docs

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#66415]
- [x] HTML: https://github.com/Microsoft/vscode/issues/64022
- [x] CSS: https://github.com/Microsoft/vscode/issues/66414

Once both are done, we should think of consistent names and

- Add them to the JSON schema for package.json.
- Update docs at https://code.visualstudio.com/api/references/contribution-points or in a new topic similar to https://code.visualstudio.com/api/extension-guides/markdown-extension.

**Comment by aeschli** [comment]
Let's brainstorm here for a better name for the contribution point. Neither custom nor data are accurate.

vocabulary
syntax identifiers

**Comment by octref** [comment]
Schemas and docs are published https://github.com/Microsoft/vscode-html-languageservice/tree/master/docs and https://github.com/Microsoft/vscode-css-languageservice/tree/master/docs.
