### ISSUE TITLE
Using VS Code as git's difftool should open one tab per modified file 

### ISSUE THREAD

**Issue by agulen** [Microsoft/vscode#66410]
Issue Type: <b>Feature Request</b>

I have VS Code set up as my default difftool with git. However, it can be cumbersome to use it when there are many modified files in a commit or branch. If I run git difftool, then a new instance of VS Code opens per modified file. So if I have 3 modified files, running git difftool ends up with this workflow:
- File1 opens in a new window showing diff
- I close the window
- File2 opens in a new window showing diff
- I close the window
- File3 opens in a new window showing diff
- I close the window. Done.

Ideally, one instance of VS Code should launch with a tab per modified file and I can browse the files however I want. Once I close that single VS Code window, then my difftool command should complete. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

**Comment by yume-chan** [comment]
You can add `-r` (`--reuse-window`) argument to `code` (or `code-insiders`) command.

**Comment by agulen** [comment]
The `-r` flag will reuse an existing VS Code window, but it still opens only a single tab for the first file diff in a multi-file changeset. In order to view subsequent file diffs, I need to close the current diff tab, then the next diff will auto-open in a new tab. In a changeset with many modified files, this can get cumbersome. 

When I run `git difftool`, I would love if VS Code could open a window (or re-use the same if `-r` is specified) with multiple tabs where each tab is a file diff. I'm guessing that git serves up the diffed files one at a time, but would there be a way to front-load those diffs and display them all at once?

**Comment by bpasero** [comment]
@agulen it does not sound like this is an issue with VSCode but rather with the tool that opens VSCode. You can pass multiple files even with `--wait`

**Comment by agulen** [comment]
Okay, thanks @bpasero. I'm just using the vanilla Mac terminal with git and already had the `git difftool` command mapped to `code --wait --diff $LOCAL $REMOTE`. For anybody who runs into a similar issue, another workaround is to keep an instance of VS Code always open to your git repo folder and track changes through the git tab. Since I'm coding in a separate IDE (Xcode for iOS dev), I was more interested in opening VS Code through CLI to view diffs, but having a constant VS Code window that updates with the diffs is good enough for now.

Thanks!
