### ISSUE TITLE
Unable to debug over VPN, throws ECONNREFUSED 127.0.0.1:5858

### ISSUE THREAD

**Issue by nikhilsharma5** [Microsoft/vscode#66413]
- VSCode Version: 1.30.2
- OS Version: 10.13.6 (High Sierra)
- node Version: v11.5.0
- protractor Version: 5.4.2

Steps to Reproduce:

1. Launch.json file
####
"version": "0.2.0",
    "configurations": [
        {
            "name": "AO Debug",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "protocol": "legacy",
            "runtimeArgs": [
                "run-script",
                "aodebug"
            ],
            "port": 5858,
            "sourceMaps": true
        }
    ]
2. Where the value for "aodebug" is "protractor config/aoFeatures.conf.js --nolazy --debug=5858"
3. The debugging works fine with the "debugger" keyword in office network, but when connected to VPN (outside office network). It throws multiple errors based on protocol we are passing.
4.  Images attached
![error vscode 1](https://user-images.githubusercontent.com/20941160/51056759-8f9aa600-1598-11e9-9e9c-63169c9d9282.png)
![error vscode 2](https://user-images.githubusercontent.com/20941160/51056760-8f9aa600-1598-11e9-84bf-fb3d5058051b.png)

Not sure about disabling extension part or how to disable them.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
What do you mean by "debug over VPN"? Your launch configs use a local port 5858, so they are not going remote.

**Comment by nikhilsharma5** [comment]
@weinand What I meant by VPN is, I am connected to my companies private network while I am out of office building, but I am trying to debug locally on my machine. For example:

**Scenario 1**: I am in office building and connected to network. When I try to debug locally on my machine it launches the chrome browser and it stops at debugger keyword and I am able to perform debugging operations.

**Scenario 2**: I am at home and connected to network through virtual private network just so that I can access companies internal websites. I am still trying to test my tests cases locally on my machine. When I try to triiger scenarios in debug mode, I face above mentioned issues.

**Node Version**: 11.5.0

**Comment by weinand** [comment]
Your initial issue says you are on macOS, but the screenshots shows Windows.

You are using node.js 10.5.0. Why are you using the legacy protocol then (which is no longer supported since node.js  8.0)?

Please provide consistent information so that I can try to reproduce.

If you stop vpn, does everything gets back to normal? 
Please try to reproduce the problem with a simple node.js "hello world" program (without protractor).

**Comment by nikhilsharma5** [comment]
We are facing this issue on both machines, sorry for the confusing screenshots and information tho.

I am using legacy because with that, atleast we are able to debug within office network. With protocol: inspector and switching '--debug=5858' to '--inspect=5858' we get below error:

<img width="1327" alt="screen shot 2019-01-14 at 19 22 35" src="https://user-images.githubusercontent.com/20941160/51156764-deaf3800-1831-11e9-81c7-9f9f1db278f2.png">
Where value for aodebug command is: "protractor config/aoFeatures.conf.js --nolazy --inspect=5858"
&&
**Launch Json**
{
            "name": "AO Debug",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "protocol": "inspector",
            "runtimeArgs": [
                "run-script",
                "aodebug"
            ],
            "port": 5858,
            "sourceMaps": true,
}

Also I tried running a test.js class with console.log in it and I was able to stop the debugger.
Command for Test Scenario: "test1": "node --nolazy --debug-brk=5858 --inspect test.js"
&&
**launch.json**
{
            "name": "test",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "test1"
            ],
            "port": 5858,
            "sourceMaps": true,
}

Screenshot of debugger stopping.
<img width="1349" alt="screen shot 2019-01-14 at 19 31 36" src="https://user-images.githubusercontent.com/20941160/51157142-6a759400-1833-11e9-8f1d-c547bc2fd231.png">

Issue is for protractor command it doesnt stop and throws below error:
_Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858)._

**Comment by weinand** [comment]
If you are able to start node.js with "--debug-brk=5858" then you are definitely using a node.js version < 8.0. Why do you think that you are using node v11.5.0?
What's the result of running `node --version`?

Using both `--debug...` and `--inspect` is again confusing. Either use `node --nolazy --debug-brk=5858 test.js` for node.js < 8.0 and `node --nolazy --inspect-brk=5858 test.js`.
Mixing them asks for trouble...

**Comment by nikhilsharma5** [comment]
The version for node is v11.5.0 and it is working for me with --debug-brk for some reason. I ran the same command to check the version of node and thats how I knew what version of node am running :)

I understand that using debug and inspect together is not the correct behavior, but the command which is failing on vpn does not have debug in it.
> protractor config/aoFeatures.conf.js --nolazy --inspect=5858

More details:
```
nikhilsharma $ nvm list
->      v11.5.0
default -> 11 (-> v11.5.0)
node -> stable (-> v11.5.0) (default)
stable -> 11.5 (-> v11.5.0) (default)
```

**Comment by weinand** [comment]
Please use `protractor config/aoFeatures.conf.js --nolazy --inspect-brk=5858`.
Without the brk it is possile that node.js is already finished before the debugger could attach.

**Comment by nikhilsharma5** [comment]
Hey @weinand inspect-brk is not working for me. I get the same error for ECONNREFUSED: 127.0.0.1:5858. If I change it to inspector protocol.

**Comment by roblourens** [comment]
Have you seen this page?

https://github.com/angular/protractor/blob/master/docs/debugging.md

I'm not sure whether passing the inspect flag to protractor even does the right thing. Also my guess is that the VPN is not actually making a difference here.

**Comment by nikhilsharma5** [comment]
Hey @roblourens, I have tried the vscode debug section from this page. But looks like there is another way to debug await/async tests using chrome inspector and I will look into it.
Also using launch.json along with "debugger;" keyword works fine when am on companies network, but it fails to launch debugger at 127.0.0.1:5858 when trying to do same thing outside of the network.
I am not sure either, that vpn is blocking debugger to start at that ip and port or not. But I will try the other option you mentioned in your comment and will let you know soon.

Ty!!

**Comment by nikhilsharma5** [comment]
@weinand @roblourens I am able to fix this issue using following configurations.
launch.json
```
{
  "type": "node",
  "request": "launch",
  "name": "AicpDebug",
  "runtimeExecutable": "npm",
  "runtimeArgs": [
    "run-script",
    "aicpdebug"
  ],
  "port": 9229
}
```
Command
### #  aicpdebug = protractor config/aicpFeatures.conf.js --nolazy --debug=9229

Closing this defect.. Thanks for all your help!!

**Comment by roblourens** [comment]
Glad you figured it out, thanks for following up!
