### ISSUE TITLE
pass to next selection behaviour after ctrl+d

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#6641]
When i hit `ctrl+d` it selects next matching occurrence this is great but what if the next occurrence  is not something i wanna match.
For example if i want to edit all the whole words "ate" `ctrl+d` will match `donate` too.
In brackets editor theres a great solution to this `ctrl+d` matches next and if its not right match `ctrl+shift+d` skips the match to the next .

**Comment by WangZishi** [comment]
In VSCode, if you want to skip the current selection, you should press `ctrl + k`. And `ctrl + d` again will select next.

**Comment by NikosEfthias** [comment]
well i didnt know that thank you :+1:
