### ISSUE TITLE
weird typescript error

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#6642]
- VSCode Version:1.1.1
- OS Version:ubuntu 16.4

Steps to Reproduce:
i have a function which accepts a parameter with the type `Promise<mongodb.Db>`
![](http://i.imgur.com/hsiumD8.png)
and i call this function  with  right parameter
![](http://i.imgur.com/iyHBJyz.png)
but i get a totally weird error says
`Argument of type 'Promise<Db>' is not assignable to parameter of type 'Promise<Db>'`
![](http://i.imgur.com/8XvfABI.png)

**Comment by WangZishi** [comment]
I think it might be caused by the typings of es6-promise.d.ts that is used by mondbDb's typings and it is incompatible with promise interface that defined in lib.ed6.d.ts

**Comment by NikosEfthias** [comment]
@WangZishi by default wont i add es6-promise package if i reference to mongodb.d.ts because it refferences inside es6-promise ?

**Comment by WangZishi** [comment]
I just try it on my machine and find this solution:
![tmp5ce6e091](https://cloud.githubusercontent.com/assets/8288105/15458688/fe7845ca-20cf-11e6-8e02-4533370fc3fe.png)

**Comment by NikosEfthias** [comment]
@WangZishi  weird thing now it also stopped giving me this error
