### ISSUE TITLE
auto-link tooltip of integrated terminal does not disappear under some conditions

### ISSUE THREAD

**Issue by rinsuki** [Microsoft/vscode#66421]
Issue Type: <b>Bug</b>

gif:
![out](https://user-images.githubusercontent.com/6533808/51068360-3bf38f80-1660-11e9-8c91-6746c3e6e50e.gif)

1. show file path on integrated terminal (e.g. exec `find /` command).
1. open another integrated terminal to the side.
1. hover cursor to file path and wait few seconds.
1. when "cmd+click to follow link" tool-tip is displayed, move the mouse cursor to the other-terminal.
1. tool-tip does not disappear.

VS Code version: Code - Insiders 1.31.0-insider (ccdd2997a66965c7104fe180207d9a710ea50fa5, 2019-01-11T06:13:56.256Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|-psn_0_1622412|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Looks like we don't track when mouse leaves the terminal element?

**Comment by rcbevans** [comment]
I was able to repro this and have created a PR to address the issue.  In my opinion, the bug is in xterm.js, not in vscode though.

**Comment by Tyriar** [comment]
Created https://github.com/xtermjs/xterm.js/issues/1908 to fix the underlying problem
