### ISSUE TITLE
"fontStyle": "italic" - 

### ISSUE THREAD

**Issue by alaminmishu** [Microsoft/vscode#66423]
I can't setup this in version 1.30.1. My OS is Windows 10  64bit.
how to I setup this .
I want to use font - "Fira Code iScript" and set it italic and set editor.fontLigatures as true.
But I can't find how to give font italic style. 

Basically what I want - I want stylaizing my vs code without using "operator mono" font but like like that using free  "Fira Code iScript" font .
I've installed Dark++ Italic theme by  idbartosz.

thanks advance for any kind of help.

**Comment by RMacfarlane** [comment]
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": [
        "comment",
        "entity.name.type.class", //class names
        "keyword", //import, export, return…
        "constant", //String, Number, Boolean…, this, super
        "storage.modifier", //static keyword
        "storage.type.class.js", //class keyword
      ],
      "settings": {
        "fontStyle": "italic"
      }
    }
}
