### ISSUE TITLE
Dual comment issue

### ISSUE THREAD

**Issue by ketanharsodaibl** [Microsoft/vscode#66422]
Issue Type: <b>Bug</b>

When we apply a comment on already commented line then it will not guess already commented line and again wrap that commented line with a new comment.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6400K APU with Radeon(tm) HD Graphics    (2 x 3893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.19GB (2.17GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
vscode-intelephense-client|bme|0.8.8
gitlens|eam|9.4.1
php-intellisense|fel|2.3.10
vscode-phpfmt|kok|1.0.30
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.3
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.6.2
trailing-spaces|sha|0.2.11

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@ketanharsodaibl What language do you see this for? Can you provide some sample code?

**Comment by ketanharsodaibl** [comment]
It's for php language.

**Comment by ketanharsodaibl** [comment]
> @ketanharsodaibl What language do you see this for? Can you provide some sample code?

**Comment by ketanharsodaibl** [comment]
> @ketanharsodaibl What language do you see this for? Can you provide some sample code?

It's for php language.

**Comment by RMacfarlane** [comment]
Can you please provide sample code? I haven't been able to reproduce this with a simple php file

**Comment by ketanharsodaibl** [comment]
> Can you please provide sample code? I haven't been able to reproduce this with a simple php file

![comment_issue](https://user-images.githubusercontent.com/30490022/51368174-3b517200-1b14-11e9-8dac-66229c17e3f1.gif)

**Comment by aeschli** [comment]
That's as designed. The comment feature does not change any of the text that is commented out. That way the uncomment feature can just remove the comment tokens and bring you back to the original result.
