### ISSUE TITLE
Empty OPEN EDITORS

### ISSUE THREAD

**Issue by trileminh94** [Microsoft/vscode#66439]
Issue Type: <b>Bug</b>

I already open some files to edit, but the open editors window is still empty 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.65GB (1.64GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
django-html|bib|1.3.0
indent4to2|Com|0.1.2
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.42
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
beautify|Hoo|1.4.7
rest-client|hum|0.21.1
solidity|Jua|0.0.49
Angular-BeastCode|Mik|7.0.29
python|ms-|2018.12.1
cpptools|ms-|0.20.1
Go|ms-|0.8.0
vetur|oct|0.14.5
proto|pet|0.0.2
vscode-docker|Pet|0.5.1
ejs-language-support|Qas|0.0.1
java|red|0.36.0
format-html-in-php|rif|1.4.5
LiveServer|rit|5.3.1
vscode-icons|rob|8.0.0
html-preview-vscode|tht|0.2.5
lorem-ipsum|Tyr|1.2.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.13.0
vscode-spring-initializr|vsc|0.4.3

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
