### ISSUE TITLE
VSCode is not runing programs when the program file name has space

### ISSUE THREAD

**Issue by Devloper-King** [Microsoft/vscode#66432]
I am trying to runing a simple c program and it is running compleatly fine when the save file doesnt have any space.
![capture](https://user-images.githubusercontent.com/46634323/51078412-ba8f1200-16de-11e9-8b01-158ee0f556ff.PNG)
but the problem start when the file name has space and it is showing errors
![capture2](https://user-images.githubusercontent.com/46634323/51078421-e27e7580-16de-11e9-818a-f8507d5d1d42.PNG)
It can be solved by using dash(-) beside space but want a better solution.
Thank you guys very much.

- VSCode Version:1.30.2 (user setup)
- OS Version:Windows 7 ultimate

**Comment by RMacfarlane** [comment]
What is the value of your `terminal.integrated.shell.windows` setting? `C:\\Windows\\System32\\cmd.exe`? Can you check what happens when you use the same terminal outside of VSCode and run the same commands?

**Comment by Devloper-King** [comment]
It runs fine in external terminal.
![capture1](https://user-images.githubusercontent.com/46634323/51208067-ce34b580-1936-11e9-9c26-d446f6789286.PNG)
But not running in the integrated terminal.

Here is my user settings
![capture2](https://user-images.githubusercontent.com/46634323/51208181-21a70380-1937-11e9-86fb-f5556faa2564.PNG)

**Comment by Tyriar** [comment]
You're using the code runner extension, we have this built in which might work:

<img width="401" alt="screen shot 2019-01-23 at 6 16 15 pm" src="https://user-images.githubusercontent.com/2193314/51649882-fde94c00-1f3a-11e9-9c43-d19186739e25.png">
