### ISSUE TITLE
Shortcut to work with editor moving didn't work

### ISSUE THREAD

**Issue by Iipal** [Microsoft/vscode#66433]
- VSCode Version: 1.30.2
- OS Version: Linux x64 4.18.0-13-generic

Ctrl+Alt+Right do nothing... or i do something wrong ?

![bugga](https://user-images.githubusercontent.com/31858171/51078860-b524ce00-16c4-11e9-8ed5-36f8c037231a.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Iipal** [comment]
woks only with arrows on numpad but not in keyboard

**Comment by Iipal** [comment]
@alexandrudima no action in the system is assigned to these keys

**Comment by alexandrudima** [comment]
From your original gif it looks like VS Code does not receive ctrl+alt+right. The OS or some other software is eating up that key combination. Have you been successful in using ctrl+alt+right in other software on that machine?
