### ISSUE TITLE
exported variable do not return correct type

### ISSUE THREAD

**Issue by FalloutPL** [Microsoft/vscode#6643]
**TypeScript Version:** 

1.8.10 Win10, VSCode 1.1.1

TS config:

```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "outDir": "dist",
        "rootDir": "src",
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Code**

```ts

export interface IDeviceIdentsAttributes {
    id_device: number
    id_ident_type: number
    ident_value: string
}

export interface IDeviceIdentsInstance extends sequelize.Instance<IDeviceIdentsAttributes> { }
export var DeviceIdents = db.connection.define<IDeviceIdentsInstance, IDeviceIdentsAttributes>('device_idents', {model definition}, {options) 
```

**Expected behavior:**

exported DeviceIdents should return type: **sequelize.Model<IDeviceIdentsInstance, IDeviceIdentsAttributes>**

![image](https://cloud.githubusercontent.com/assets/5012042/15458511/8bc0a4ca-209b-11e6-95b0-96f00d7ad72f.png)

**Actual behavior:** 

exported DeviceIdents returns **any**

![image](https://cloud.githubusercontent.com/assets/5012042/15458506/72171158-209b-11e6-944f-9464baec7b42.png)

![image](https://cloud.githubusercontent.com/assets/5012042/15458498/5f8f23e0-209b-11e6-85a4-e7d43c106636.png)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8750
