### ISSUE TITLE
Cmd+\ does not register

### ISSUE THREAD

**Issue by synthecypher** [Microsoft/vscode#66434]
- VSCode Version: 1.30.2
- OS Version: macOS Mojave 10.14.2

Steps to Reproduce:

1. Press <kbd>Cmd</kbd>+<kbd>\\</kbd>.
2. Observe it does not trigger default action of **Split Editor**.

Does this issue occur when all extensions are disabled?: Yes

#### Demo
![jan-12-2019 22-47-33](https://user-images.githubusercontent.com/1833542/51079282-2ad86c00-16bc-11e9-8835-0e5c9e2c85db.gif)

I have also tested with other keyboard layouts and get the same result.

**Comment by sandy081** [comment]
Can you please check if there are other actions bound to this keybinding? You can do this by entering following text in the search `"cmd+\"`
