### ISSUE TITLE
debugging doesn't work

### ISSUE THREAD

**Issue by Apozhidaev** [Microsoft/vscode#66442]
Issue Type: <b>Bug</b>

memory leak occurs when debugging works for a long time (nodejs)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.85GB free)|
|Process Argv|C:\Users\admin\Documents\Projects\quik-terminal\quik-terminal.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
vscode-language-pack-ru|MS-|1.30.2
vscode-lua|tri|0.12.4

</details>

**Comment by weinand** [comment]
This is not actionable, please be more specific.
How do you know that there is a memory leak?
