### ISSUE TITLE
Title bar redrawing issue when using Windows classic theme

### ISSUE THREAD

**Issue by marcbun** [Microsoft/vscode#66441]
Hi,

there are already 2 issues raised
#56630 - Windows 7 (classic theme): Title flashes with custom menubar enabled
#61842 - Window Title bar redraw issue on Win7
but you keep closing them without fixing them.

Apparently you did something between versions 1.25.1 and 1.26.0 what is still causing this issue.

Does this issue occur when all extensions are disabled?: Yes
Issue still appears with the latest insider version and with disabling extensions.
- VSCode Version: 1.31.0-insider
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Switching between files.

This issue is very disturbing, so please fix the issue.

**Comment by RMacfarlane** [comment]
Hi @marcbun, the issue https://github.com/Microsoft/vscode/issues/56630 is still open. Let's track this problem there to avoid having duplicate open issues.
