### ISSUE TITLE
Explorer does not properly show file with backslash in name

### ISSUE THREAD

**Issue by xiaofeng19** [Microsoft/vscode#66447]
My OS is openSUSE Tumbleweed,My VScode version is 1.30.2
When I have a file which has '\\' in its name,the explorer of VScode can not display the file's real name,and can not open it.
![image](https://user-images.githubusercontent.com/28753550/51084300-31212380-1762-11e9-9fb7-d70083ed7110.png)
![image](https://user-images.githubusercontent.com/28753550/51084307-439b5d00-1762-11e9-9bcd-c9b8b4359217.png)

**Comment by Maia-Everett** [comment]
I can confirm this. Only the part of the file name after the backslash is displayed. Furthermore, if the file is subsequently deleted, it stays listed in VSCode until the Explorer is manually refreshed.
