### ISSUE TITLE
Invalid path for multi-root workspace

### ISSUE THREAD

**Issue by AlekSi** [microsoft/vscode#66449]
Issue Type: <b>Bug</b>

![2019-01-13_14-14-06](https://user-images.githubusercontent.com/11512/51084626-1fc62000-173e-11e9-90ae-de800aa1efd6.png)

Output panel contains a valid path:
```
/Users/aleksi/Code/My/vscode-bug-multiroot/project-2/project2.go
```
When ⌘+clicked, it tries to use an invalid path:
```
file:///Users/aleksi/Code/My/vscode-bug-multiroot/project/-2/project2.go
```
Note the extra `/` before `-2`. That seems to happen only with multi-root workspace when one root path is a prefix of another root path.

Example repo: https://github.com/AlekSi/vscode-bug-multiroot
Steps to reproduce:
1. `git clone https://github.com/AlekSi/vscode-bug-multiroot.git`
2. `code vscode-bug-multiroot/bug.code-workspace`
3. Install Go plugin (but that issue is not specific for it).
4. Open project2_test.go, click CodeLens' "run test".
5. `go test` runs `go vet` and notices a bug in project2.go. ⌘+click on the file path in the Output panel.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

**Comment by ramya-rao-a** [comment]
[Input](https://github.com/Microsoft/vscode-go/issues/2183#issuecomment-446973459) from @isidorn from the corresponding issue in the vscode-go repo:

> Might be some link detection issue.
Code pointer so you can investigate more and potentialy provide PRs
https://github.com/Microsoft/vscode/blob/757c5feacc2e2c322b1d8e0ac29d02a8d06179e9/src/vs/workbench/parts/output/common/outputLinkComputer.ts#L58

**Comment by AlekSi** [comment]
This issue affects a group of people, has more than 10 :+1:, has steps to reproduce, and self-contained example. The fix is likely to be small and self-contained too. According to https://aka.ms/vscode-out-of-scope it should be reopened. @jrieken @isidorn @bpasero please reopen.

**Comment by isidorn** [comment]
Sure, we can reopen.

**Comment by AlekSi** [comment]
I re-checked it, and it works now
