### ISSUE TITLE
Distracting Black .5px Line in Bottomn

### ISSUE THREAD

**Issue by itsnzsaad** [Microsoft/vscode#66448]
Issue Type: <b>Bug</b>

http://prntscr.com/m6juth 
![image](https://user-images.githubusercontent.com/8627221/51084605-e817a200-1756-11e9-81cb-333313164260.png)

On Windows 10, when VS Code is Maximised, a black line appears separating the taskbar and vscode status bar.
This is very distracting as I have OCD.

The Problem is since August 2018 (version 1.27) , Custom menu bar - Fully themable title and menu bars on Windows and Linux.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (3.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
vsc-material-theme|Equ|2.6.3
vscode-language-babel|mgm|0.0.21
material-icon-theme|PKi|3.6.2
JavaScriptSnippets|xab|1.7.2

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I can't repro on my machine

**Comment by itsnzsaad** [comment]
Duplicate of #8332
