### ISSUE TITLE
Electron build files locked by VSCode

### ISSUE THREAD

**Issue by physicsLoveJava** [microsoft/vscode#66440]
- VSCode Version: 1.30.2
- OS Version: 
VSCode version: 1.30.2 (system setup)
submit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
date: 2019-01-07T22:53:57.820Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT ia32 10.0.17134

Steps to Reproduce:

1. an electron app to build
2. every time VSCode will locked the app.asar or electron.asar

Does this issue occur when all extensions are disabled?: Yes

I have to setting **files.exclude** and **files.watcherExclude** as follow:
```json
"files.exclude": {
  "**/app.asar": true,
  "**/electron.asar": true,
  "build/**": true
}

"files.watcherExclude": {
  "**/app.asar": true,
  "**/electron.asar": true,
  "build/**": true
}
```
BUT, The previous VSCode version I used in July, that's ok!

**Comment by dharders** [comment]
I can also confirm this happening on Windows. It happens in both the integrated terminal and external terminal (Cmder in my case).

Quitting code and running electron build works successfully (as code has released the file). Starting code again will soon lock the file again (generally after an `npm start` or `npm run` script, so subsequent electron builds fail and you have to repeat the process. Very frustrating!

**Comment by sijakret** [comment]
same here. i also tried disabling extensions (like  ESLint) without any relief..
