### ISSUE TITLE
when white space trigger snippet, intellisense won't work.

### ISSUE THREAD

**Issue by eterlan** [Microsoft/vscode#66443]
- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2
- List of extensions that you have installed
    - C#
    - unity debugger
    - unity snippet

- How to reproduce
1. write a field called " Collider collider;"
2. then try to assign it   "collider = collider" and when I type a white space before the second collider, the intellisense won't tell there is a variable or any other things but just trigger snippet even after I type whole variable.

- How I expect
1. I don't understand why white space should be used to trigger snippet but not variables.
2. This didn't happen in 1.29. Also it's ugly to show so many snippet every time press space.
3. I expect to customize the trigger character, or trigger snippet but also other intellisense with space.
4. I know I can turn off ```Suggest On Trigger Characters``` or  ```Snippet Suggestion```  but it's not as convenient as vscode 1.29.

Thank you, first time report issue, sorry for might be not readable.

Does this issue occur when all extensions are disabled?: No

**Comment by eterlan** [comment]
I'm pretty sure it's not cause by extension. I reinstall 1.29 and 1.30 three times without any extensions for experiment, and the result is 
- in 1.30, without OmniSharp, just open a c# file, tap space, no snippet bump out.
- in 1.30, open a unity project, with OmniSharp running, tap space, snippet bump out.
- in 1.29, whatever I do, snippet won't bump out.
In both case, I try in windows and mac.

**Comment by nerdmax** [comment]
I'm having the same issue. The white space will trigger all the snippets.

**Comment by jrieken** [comment]
This is caused by OmniSharp because they define ` ` as IntelliSense trigger character. That causes snippets to show up.

**Comment by eterlan** [comment]
> This is caused by OmniSharp because they define (space) as IntelliSense trigger character. That causes snippets to show up.

Thanks for your work and reply, I got it. Now I'm using 1.29, and figure out some problem with forced auto-update in Mac, everything just fine. 😂
