### ISSUE TITLE
Number of reviews contributing to rating in vscode?

### ISSUE THREAD

**Issue by rahulguptakota** [Microsoft/vscode#66450]
While the web interface tells the number of users who have given a rating, it would be great if builtin extension browser in vscode also displayed that information. It is annoying to have to click on the review stars to go the web in search of this information.

**Comment by sandy081** [comment]
@rahulguptakota You will see the number of users when you hover on the rating

**Comment by rahulguptakota** [comment]
@sandy081 No, It just says "Rating" when I hover over the rating.

**Comment by sandy081** [comment]
Yes
