### ISSUE TITLE
[js/html] syntax highlighting not correct for javascript multiline comments (/* */)   in html file

### ISSUE THREAD

**Issue by allan-simon** [Microsoft/vscode#66457]
- VSCode Version: 1.30.2
- OS Version:  Windows 10

Steps to Reproduce:

1. open a .html file 
2. write 

```
<button
      onclick="
            /*
                var toto = 'hey i look like normal javascript code';
            */
      "
>
     clickme
</button>
```
the first `/*`  is correctly colored (actually the whole first line is correctly colored if you put additional text) 
but the next lines are not.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@aeschli I think this is an html grammar specific issue related to how is treats event handler attributes as JavaScript. I haven't been able to reproduce in a normal js file

**Comment by mjbvz** [comment]
Caused by this line: https://github.com/Microsoft/vscode/blob/32d22dbace8f2deed5dfb44e19f813f76ff1d0f0/extensions/html/syntaxes/html.tmLanguage.json#L225

I believe the problem is that `matches` will only apply to a single line at a time

**Comment by alexr00** [comment]
This issue was moved to textmate/html.tmbundle#99
