### ISSUE TITLE
Save for react js not possible

### ISSUE THREAD

**Issue by ak-anirudh** [Microsoft/vscode#66455]
Issue Type: <b>Bug</b>

HI
When I try to save a file as a reactjs (in select the language mode), it is saved as  js.
Later when I open the file again, it still shows the syntax errors and the file is only saved as js.

Regards
Kesava

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|

|Process Argv||
|Screen Reader|no|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
code-runner|for|0.9.5
beautify|Hoo|1.4.7
rest-client|hum|0.21.1
xml-format|mik|1.0.1
mssql|ms-|1.4.0
python|ms-|2018.12.1
vscode-docker|Pet|0.5.1
vscode-icons|rob|8.0.0

</details>

**Comment by yume-chan** [comment]
I don't think there is any difference between the "JavaScript` and "JavaScript React" language modes, they both supports JSX syntax.

And the de facto file extension for JSX files is `.js`, so Code always save as `.js`.

Of course you can change the extension to `.jsx`, and Code will open it with `JavaScript React` file mode, but working with other JavaScript tools like webpack will be more difficult.

Can you attach a screenshot about the error you have seen?

**Comment by sandy081** [comment]
Please move/file this issue against react extension
