### ISSUE TITLE
Disable  "Reload" buttons 

### ISSUE THREAD

**Issue by talley** [Microsoft/vscode#66456]
Issue Type: <b>Feature Request</b>

Disable  "Reload" buttons when VS Code is busy adding other extensions

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by talley** [comment]
![disable reload buttons](https://user-images.githubusercontent.com/6354720/51089941-bdbbe980-1742-11e9-8afc-47ab5ac60e8f.png)

**Comment by sandy081** [comment]
You can reload while installing and it finishes in the background So not required to disable them.
