### ISSUE TITLE
pylint

### ISSUE THREAD

**Issue by Damemo** [Microsoft/vscode#66453]
Issue Type: <b>Feature Request</b>

unable to install pylint 

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

**Comment by RMacfarlane** [comment]
Hey @Damemo, can you provide some more details? What happens when you try to uninstall the extension? Is there an error message?
