### ISSUE TITLE
Cannot insert snipped into JSON file

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/vscode#66463]
- VSCode Version: Version 1.30.2 (1.30.2)
- OS Version: macOS Mojave 10.14.2 (18C54)

Steps to Reproduce:

1. Create a snippet of valid JSON and save in json.json
2. Create a JSON file in project.
3. Type prefix name for snippet.
4. Prefix name gets flagged as error because it is invalid JSON, preventing insertion of snippet.

Does this issue occur when all extensions are disabled?: Yes

Here is snippet for JSON data:

```json
{
  "JSConfig": {
    "prefix": "jsconfig",
    "body": [
      "{",
      "  \"compilerOptions\": {",
      "    \"target\": \"es6\",",
      "    \"jsx\": \"react\"",
      "  },",
      "  \"exclude\": [",
      "    \"node_modules\"",
      "  ]",
      "}"
    ],
    "description": "jsconfig"
  }
}
```

**Comment by jrieken** [comment]
works for me. please update your steps

<img width="541" alt="screenshot 2019-01-15 at 07 58 29" src="https://user-images.githubusercontent.com/1794099/51192442-d06f2380-18e6-11e9-9ad5-b0af883f4fa3.png">

**Comment by rbiggs** [comment]
I'm creating a `jsconfig.json` file and trying to populate it with a snippet. However it does not work. Instead I just get this:

<img width="606" alt="screen shot 2019-01-15 at 5 39 47 pm" src="https://user-images.githubusercontent.com/249218/51221079-c05a4280-18ec-11e9-8cdb-e038f33ebda0.png">

However, if I name the file something else other than `jsconfig.json`, say `js.json` or `config.json`, it works. Since VSCode uses the `jsconfig.json` file for understanding a project, there some background process that's preventing the snippet from being triggered when the file is named `jsconfig.json`.

**Comment by jrieken** [comment]
Right, understood. The issue is that you have created the snippet for the "JSON" language and that jsconfig.json are actually of the "JSON with Comments" language, e.g the snippet doesn't apply here. You should consider create a snippet for "JSON with Comments" or a _global_ snippet that targets both JSON variant. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets
