### ISSUE TITLE
Unable to open 'User.java': File not found (file:bla/bla/bla/Model/User.java).

### ISSUE THREAD

**Issue by 4sskick** [Microsoft/vscode#66464]
Issue Type: <b>Bug</b>

I got an update pop up from the right bottom. Then I clicked on the button inside it. I downloaded the file .deb then I installed hopefully I got the latest version of VS Code. After finished I re-opened my project file then I clicked random file got the error pop up "Unable to open 'User.java': File not found (file:bla/bla/bla/Model/User.java).". It happened to al the project folder I opened

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.58GB (3.65GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1

</details>

**Comment by joaomoreno** [comment]
Does the file `User.java` exist in your machine at all?

**Comment by 4sskick** [comment]
> Does the file `User.java` exist in your machine at all?

of course, `User.java` just for example. Every file I opened got that pop up

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
