### ISSUE TITLE
"Expression matches everything" is not an error

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/vscode#66467]
- VSCode Version: Version 1.30.2 (1.30.2)
- OS Version: macOS 10.14.2 (18C54)

# Test case:

1. Enter text into the editor
2. Command-F to find
3. Enable regular expression mode
4. Enter the search term `.*`

# Expected outcome:

All lines are matching the expression

# Actual outcome:

Error message shows:

> Expression matches everything

<img width="694" alt="screen shot 2019-01-14 at 3 58 41 pm" src="https://user-images.githubusercontent.com/382183/51101418-85d1a680-1815-11e9-8022-e62369c9b7c9.png">

# Discussion

Matching everything is not an error condition and therefore the person using VS Code should be allowed to proceed if the `.*` search expression is used. Today my use case is that I need to turn each line of text into a hyperlink. It is something like:

> Find: `.*`
> Replace with: `<a href="https://URL?email=$&>$&</a>`

or 

> Find: `(.*)`
> Replace with: `<a href="https://URL?email=$1>$1</a>`

A workaround for this specific use case is to use Command-A to select all of the file and then try to remember the keybinding for Atom's Command-L feature and then slickly make it work. Unfortunately this fails because that feature is limited to 10,000 lines and my file has much more. Alternatively, today I will use sed or Microsoft Excel for this task.

**Comment by roblourens** [comment]
I think that using it in a find/replace is a bit ambiguous because it can match empty strings or it can match without advancing. Maybe you want to use `.+`? Do you need to match empty lines?

**Comment by fulldecent** [comment]
In my case it doesn't matter, I know there aren't any blank lines. `.*` is good enough.

**Comment by roblourens** [comment]
Hey @sandy081 I'm confused about exactly what issue we are trying to avoid. It does feel like there could be an issue but I don't see exactly what it is.

**Comment by sandy081** [comment]
Its pretty old (even before me), and I think this was because it does not makes sense to match everything. If there is a use case why not remove it.

**Comment by fulldecent** [comment]
`.+` is a workaround for this issue. But I do believe the `.*` is broken because the error message is inconsistent and incorrect.

Yes, `.*` matches everything. But `.+` matches everything too and that does not cause an error. The only way you would learn this is by searching GitHub Issues and finding your comment here.

<img width="1015" alt="screen shot 2019-01-25 at 10 02 07 am" src="https://user-images.githubusercontent.com/382183/51753654-55e19900-2088-11e9-8ac5-f0af5ba40084.png">
<img width="1015" alt="screen shot 2019-01-25 at 10 02 11 am" src="https://user-images.githubusercontent.com/382183/51753655-55e19900-2088-11e9-9c80-b418939b838e.png">

Requesting to please reopen the issue.

**Comment by roblourens** [comment]
@rebornix do you know why we restrict searching `.*` but not in the find widget?

Maybe we just remove this restriction next month in insiders and try it.

**Comment by rebornix** [comment]
@roblourens I don't the reason, probably some performance consideration. IMO we should not restrict this case as in small workspace, ripgrep is fast enough when searching `.*`.

**Comment by roblourens** [comment]
I see that `/.*/g` can loop on an empty string forever. Editor find handles the same case here: https://github.com/Microsoft/vscode/blob/c0c719c6511d15160dd5d20b175f954f34bcc76e/src/vs/editor/common/model/textModelSearch.ts#L547

And since ripgrep handles this regex fine, I'll remove the restriction for search.
