### ISSUE TITLE
How To get Theme head on style.css for wordpress?

### ISSUE THREAD

**Issue by nriddhi** [Microsoft/vscode#66473]
How can i get in visual studio code on style css, theme head like , 
/*
Theme Name: Mark Theme
Theme URI:
Author:Nayeem Hyder
Author URI: www.nayeemriddhi.info
Description: A Nice WordPress Theme
Version: 2.0
License: GPL
License URI: GPL
Text Domain: mark
Tags: one-column, two-columns, right-sidebar, grid-layout, custom-menu, custom-logo, footer-widgets, blog, e-commerce, education, portfolio
*/
any extension there and shortcut key

**Comment by yume-chan** [comment]
You can add it to your user snippets.

1. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>
2. Type `Configure User Snippets`, Press <kbd>Enter</kbd>
3. Type `css` or navigate with arrow keys to `css`, Press <kbd>Enter</kbd>
4. In the opened editor, paste the following codes below the pre-existed comments:

```json
"File Header": {
    "prefix": "fileheader",
    "body": [
      "/*",
      " Theme Name: Mark Theme",
      " Theme URI:",
      " Author:Nayeem Hyder",
      " Author URI: www.nayeemriddhi.info",
      " Description: A Nice WordPress Theme",
      " Version: 2.0",
      " License: GPL",
      " License URI: GPL",
      " Text Domain: mark",
      " Tags: one-column, two-columns, right-sidebar, grid-layout, custom-menu, custom-logo, footer-widgets, blog, e-commerce, education, portfolio",
      " */"
    ]
  }
```

(You can change the prefix to any shortcut as you want)

5. Save the file.
6. In a css file, type `fileheader` (or any prefix you have defined), Press <kbd>Enter</kbd> or <kbd>Space</kbd>, the snippet content will be inserted as cursor position.

For a more detailed documentation, see https://code.visualstudio.com/docs/editor/userdefinedsnippets
