### ISSUE TITLE
Global new file and new folder actions should be scoped by the explorer's focused item

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#66475]

**Comment by bpasero** [comment]
Verified for the view actions. From the command palette I found https://github.com/Microsoft/vscode/issues/67653

**Comment by bpasero** [comment]
Nah something is off...

**Comment by bpasero** [comment]
Seems to fail after a second try. Steps:
* click on a file
* select "New File" from view and see that the context is respected
* ESC
* select "New File" from view

=> :bug: file is ought to be created in root
