### ISSUE TITLE
win10 memory usage is too large

### ISSUE THREAD

**Issue by yisen718** [Microsoft/vscode#66474]
1. I'm not open too large file or project, just three little python script file.
2. I'm using Anaconda 3.6 enviroment, when write django project, no problem here.
3. when I uninstall Python Docs, memory usage is reduced a lot, the problem maybe is that.
Before:
![](http://ww1.sinaimg.cn/large/e2e8c406gy1fz69i88pdkj20zk0jhac1.jpg) 
After uninstall Python Docs:
![](http://ww1.sinaimg.cn/large/e2e8c406gy1fz69k38itbj20zk0jhabx.jpg)

**Comment by oneslash** [comment]
I see Python language server is taking all the memory
