### ISSUE TITLE
There is no document formatter for 'go'-files installed.

### ISSUE THREAD

**Issue by pmalekn** [Microsoft/vscode#66479]
- VSCode Version: 1.30.1
- OS Version: Mac OS 10.14.2

When I launched vs code today I realized that go-langserver is running but doesn't respond to queries (or maybe queries are not being sent at all, I don't see anything in `go-langserver`'s trace log) and formatting doesn't work - when I manually trigger `Format Document` I get 

```
There is no document formatter for 'go'-files installed.
```

Nevertheless I do have all formatters and tools installed (`goimports`, `gofmt` and other) and I can run them outside of vs code (even in the integrated terminal).

**Comment by pmalekn** [comment]
Ok so for some reason when I disable `go-langserver` it works:

```
    "go.useLanguageServer": false,
```

but why? It's installed and running and listening.

**Comment by oneslash** [comment]
@pmalekn do you think it can go to https://github.com/Microsoft/vscode-go/?

**Comment by pmalekn** [comment]
Not sure, I'd prefer someone with more knowledge about vscode to answer that.

**Comment by yume-chan** [comment]
Normally it means the extension crashed during initialization, so it even didn't register a formatting provider (nor other language features).

It should print an error log in "Log (Extension Host)" section, or DevTools (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>, `Developer: Toggle Developer Tools`).
