### ISSUE TITLE
Test goto definition enhancements

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6647]
* [x] any os - **@sandy081**

#5893

We have improved the go to definition behaviour when a symbol as multiple definitions. When having multiple definitions, make sure that
* we reveal the _first_ definition and show the peek window with further definitions
* the first definition is the _nearest_ wrt to position and file path
* selecting an item in the peek window tree (enter/double-click) reveals that definition and closes the peek window
* other peek feature (cmd+click, etc) still work

**Comment by sandy081** [comment]
Done with testing.. it works as expected. Closing.
