### ISSUE TITLE
Copy and paste files from the search tab

### ISSUE THREAD

**Issue by alberto-marin** [microsoft/vscode#66480]
Issue Type: <b>Feature Request</b>

It might be useful to copy a file from the search results tab in one editor and paste it to a folder in a different editor.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Can you explain some more about this? Not actually sure we can paste files across editors. It doesn't work from the explorer view currently at least.

**Comment by alberto-marin** [comment]
Sorry for the delay in my answer, this is what I mean:

1. Open two editors (A, B)
2. Search for something in editor A
3. Copy a file from results
4. Paste the file in editor B. As, you will see Paste option is not available.

We can copy/paste from/to different editors in the explorer but not in search results.
