### ISSUE TITLE
Diagnostics over newline moves position when inserting newlines

### ISSUE THREAD

**Issue by olafurpg** [microsoft/vscode#66481]
- VSCode Version: 1.31.0-insider
- OS Version: macOS 10.14.2 (18C54)

Steps to Reproduce:

- Implement language server and publish diagnostic with start position at end of a line and end position at column 0 for the next line.
```json
        "range": {
          "start": {
            "line": 11,
            "character": 9
          },
          "end": {
            "line": 12,
            "character": 0
          }
        },
        "message": "newline"
      }
```
- It renders as a single space at the end of the line as expected
![screenshot 2019-01-14 at 14 48 01](https://user-images.githubusercontent.com/1408093/51116472-7c434100-180b-11e9-81df-23971b3f384a.png)

- Insert newline at the end of the line, the diagnostic red squiggle moves to the next line when I expected the diagnostic to stay on the same line. I double checked and the language server sends the same original diagnostic on `textDocument/didChange`.

![2019-01-14 14 52 45](https://user-images.githubusercontent.com/1408093/51116681-1dca9280-180c-11e9-933d-661399525ecb.gif)

Does this issue occur when all extensions are disabled?: Yes, I can reproduce with latest Insider but I had to install one extension for my language server to publish diagnostics https://marketplace.visualstudio.com/items?itemName=scalameta.metals

**Comment by alexandrudima** [comment]
I cannot reproduce. The newly set diagnostic is removing the one which gets adjusted with typing. I have tried with the following extension:

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "66482",
    "engines": {
        "vscode": "^1.0.0"
    },
    "version": "0.0.0",
    "activationEvents": [
        "*"
    ],
    "main": "./index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    const collection = vscode.languages.createDiagnosticCollection('66482');
    vscode.workspace.onDidChangeTextDocument((e) => {
      const activeTextEditor = vscode.window.activeTextEditor;
      if (activeTextEditor.document.uri.toString() !== e.document.uri.toString()) {
        return;
      }
      const document = activeTextEditor.document;
      const maxChar = document.lineAt(8).text.length;
      const diagnostics = [new vscode.Diagnostic(new vscode.Range(8, maxChar, 8, maxChar), "max value")];
      collection.set(document.uri, diagnostics);
    });
}
```

**Comment by olafurpg** [comment]
Thank you for looking into this. I haven’t encountered this bug recently so it may have been fixed already. I will reopen if I can find a reliable reproduction.
