### ISSUE TITLE
rimraf node_modules

### ISSUE THREAD

**Issue by vvdspelt** [Microsoft/vscode#66488]
Issue Type: <b>Bug</b>

## Steps:
* have something in node_modules folder (after yarning for example)
* `rimraf node_modules` in powershell while VScode is open

## Expected result:
node_modules folder gets deleted.

## Actual result:
node_modules has 1 folder called '@types' which isn't accessable and can't be deleted. It says I need permission from the admin even though I'm an admin. I also can't change or transfer ownership, since it says 'unable to display current owner'. The folder disappears once I relog on Windows. 
![Console fail](https://i.imgur.com/fqoCQCK.png)
![Owner](https://i.imgur.com/F9oiYsr.png)

VS Code version: Code - Insiders 1.31.0-insider (ccdd2997a66965c7104fe180207d9a710ea50fa5, 2019-01-11T06:19:08.621Z)
OS version: Windows_NT x64 10.0.14393

**Comment by mjbvz** [comment]
Thanks. I believe we are already tracking this with #65753.
