### ISSUE TITLE
Test: Explorer

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66485]
- [x] win @alexr00
- [x] macOS @misolori
- [x] linux @Tyriar

Complexity: 5

We have rewritten the explorer to use the new tree. Open a large workspace, for example vscode and verify the following features works as before. When not sure if something is a bug, open VSCode stable and compare.

* You can change file icon themes
* Git and error decorations are properly rendered
* All the context menu actions are workins as before (also try for multiple selection)
* You can trigger all the actions using the keyboard (delete, rename, open in editor)
* Focus is properly passed to the editor on double click, on cmd click opened to the side
* Contributed context menu actions work (for example Open in GitHub)
* Title area actions works as expected (new file, new folder, refresh, collapse all)
* New file and New Folder action properly work when invoked from the command pallete
* Folder expansion state and tree focus is preserved across vscode sessions (after reload).
* Make sure file events are picked up. For example delete/rename some files on disk and the explorer should pick it up
* Open a workspace on a remote share and verify it is good
* Folders with single children get automatically expanded all the way
* Turn on a screen reader and verify it is good

Drag and drop:
* Hover highlight makes sense
* You can drag and drop from within explorer, from open editors, from outside vscode
* You can rearange workspace roots
* You can drag and drop mulitple elements
* You can drop into not yet expanded folders

New features:
* You can type a key to navigate through explorer
* Alt + click will expand / collapse recursivly

The following settings work as expected:
* `explorer.sortOrder`
* `files.exclude`
* `explorer.autoReveal`
* `explorer.confirmDelete`
* `explorer.decorations.badges`
* `explorer.enableDragAndDrop`
* `workbench.tree.horizontalScrolling`

**Comment by bpasero** [comment]
@isidorn I will assign myself for testing

**Comment by bpasero** [comment]
Did some testing, good job, nothing critical found so far.

**Comment by bpasero** [comment]
@jpoon fyi on the new tree for the explorer for the VIM extension. Things should work as before, but maybe some users noticed issues in insiders.

**Comment by isidorn** [comment]
Good point. Due to that we should probably have a `workbench.list.keyboardNavigation: none | off`
And the vim extension could set that setting
fyi @joaomoreno

**Comment by joaomoreno** [comment]
Relevant https://github.com/Microsoft/vscode/issues/66995

**Comment by bpasero** [comment]
@isidorn @joaomoreno my understanding would be that filtering never kicks in if a command is associated with a (printable) keybinding? Forcing the VIM extension to change this setting seems like the wrong approach to me. Rather we should fallback to filtering if no command is associated with a key that is pressed.

**Comment by Tyriar** [comment]
I assigned most of my issues to @joaomoreno, sorry if I got these wrong 😅

**Comment by isidorn** [comment]
@Tyriar I just went through them and assigned properly. Thanks for testing!
