### ISSUE TITLE
additional Spaces inserted on code php.

### ISSUE THREAD

**Issue by lucastelesx** [Microsoft/vscode#66483]
Issue Type: <b>Bug</b>

After I used the 'Format Document' command from HTML, on my .php file, my php codes had added some spaces, sometimes after **?** sign, after **"**.

Ex: 
```
<? php
 
<?= $textura[" imagem"])

placeholder="Modelo do carro" />
```

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II P650 Dual-Core Processor (2 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jshint|dba|0.10.20
svg|joc|0.1.4
start-git-bash|McC|1.2.1
code-beautifier|mic|2.1.0
sublime-keybindings|ms-|4.0.0
LiveServer|rit|5.3.1
sass-indented|rob|1.5.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Which format extension are you using? Please file an issue on that extension.
