### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by akonchady** [Microsoft/vscode#66498]
Issue Type: <b>Bug</b>

Nothing happens when I do `cmd+click` or select `Go to definition` from the `Go` menu. Trying on JS files which was working before for me.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.4.1
prettier-vscode|esb|1.7.3
RelativePath|jak|1.4.0

</details>

**Comment by mjbvz** [comment]
Please share some example code or small example project that has this issue

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by akonchady** [comment]
Well it's not working with this simple code snippet as well when i cmd+click on reducer in console.log: 
```js 
var reducer = function() {};

console.log(reducer);
```

Just tried the above code in the insiders build and it works fine there.

**Comment by akonchady** [comment]
Not sure what the issue was but disabling all extensions and enabling them back again worked for me. Closing this. Thanks.
