### ISSUE TITLE
PowerShell process 

### ISSUE THREAD

**Issue by MT00x** [Microsoft/vscode#66494]
- VSCode Version: 1.30.2
- OS Version: Windows 7 64 BIT

A lot of PowerShell Process created and do not exit when doing symbol searching. 
Related to issue #60414 the problem is still present.

Language: C/C++ - JS
Extensions:  
ms-vscode.cpptools
mitaki28.vscode-clang
hars.cppsnippets
austin.code-gnu-global
streetsidesoftware.code-spell-checker
plorefice.devicetree
ms-ceintl.vscode-language-pack-it
ms-python.python
fantasytyx.tortoise-svn

[vscode-status.txt](https://github.com/Microsoft/vscode/files/2755972/vscode-status.txt)

![vscode](https://user-images.githubusercontent.com/10209506/51124927-c0d8d780-181f-11e9-9360-76bc0084d27e.jpg)

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#3043
