### ISSUE TITLE
command 'ForceCode.login' not found

### ISSUE THREAD

**Issue by ilhammzr** [microsoft/vscode#66492]
Issue Type: <b>Bug</b>

command 'ForceCode.login' not found

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (1.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
apex-pmd|chu|0.2.2
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.46
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
rest-client|hum|0.21.1
search-node-modules|jas|1.3.0
apex|Joh|0.0.2
forcecode|Joh|3.11.3
visualforce|Joh|1.0.2
force-dev-tool-for-vs|kvn|0.3.0
debugger-for-chrome|msj|4.11.1
indent-rainbow|ode|7.2.4
vscode-subword-navigation|ow|1.2.0
advanced-new-file|pat|1.2.0
nbsp-vscode|pos|0.0.1
typescript-hero|rbb|3.0.0
salesforcedx-vscode|sal|44.15.0
salesforcedx-vscode-apex|sal|44.15.0
salesforcedx-vscode-apex-debugger|sal|44.15.0
salesforcedx-vscode-apex-replay-debugger|sal|44.15.0
salesforcedx-vscode-core|sal|44.15.0
salesforcedx-vscode-lightning|sal|44.15.0
salesforcedx-vscode-visualforce|sal|44.15.0
language-stylus|sys|1.11.0
DeploySFDX|Tom|0.0.1
sfdx-cli|vib|0.0.1
es-quotes|vil|0.2.6
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0

</details>

**Comment by kieferrm** [comment]
This command comes from one of your installed extensions, probably one of those that have **force** in their id. Please file the issue against the extension. Thanks!
