### ISSUE TITLE
VSC can't handle '<' key in key binding (package.json)

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode#665]
See https://github.com/VSCodeVim/Vim/issues/36 for details.

Is there a way to debug which key events/chars VSC receives from the keyboard?

**Comment by jpoon** [comment]
Related https://github.com/Microsoft/vscode/issues/114?

**Comment by alexandrudima** [comment]
@guillermooo @jpoon Just pushed to master a widget that activates when editing `keybinding.json` files that would be great for debugging.

See #713 also for an explanation of why VSCode can't dispatch on `<` at this time (It just sees the key codes when dispatching is happening and cannot get the underlying OS keyboard layout).

**Comment by guillermooo** [comment]
Thanks @alexandrudima. I will take a look asap.
