### ISSUE TITLE
incorrect keyboard hint for new "Tasks: Run Task" menu

### ISSUE THREAD

**Issue by mikelward** [microsoft/vscode#66507]
- VSCode Version: 1.30.2
- OS Version: Debian GNU/Linux testing

Steps to Reproduce:
1. Add a custom keybinding
```
    {
        "key": "ctrl+shift+t",
        "command": "workbench.action.tasks.runTask",
        "args": "test"
    },
```
2. Open palette (Ctrl+Shift+P), Type "tasks"

Actual:
There is a new "Tasks: Run Task" menu.  It shows a keyboard hint on the right saying "Ctrl+Shift+T".

Expected:
The keyboard hint only shows for the "test" task, not for the new menu folder.

**Comment by mikelward** [comment]
Also appears to affect the new Terminal > Run Task... menu item.

**Comment by alexr00** [comment]
Weird. It works on Windows but not on Ubuntu for me.

**Comment by alexr00** [comment]
No longer repros. If you set a keybinding int correctly shows in the Terminal menu.
