### ISSUE TITLE
user-defined tasks not appearing in tasks menu?

### ISSUE THREAD

**Issue by mikelward** [Microsoft/vscode#66508]
- VSCode Version: 1.30.2
- OS Version: Debian GNU/Linux testing

Steps to Reproduce:
1. Define a custom task in tasks.json, e.g.
```
    "version": "0.1.0",
    "command": "ng",
    "isShellCommand": true,
    "tasks": [
        {
            "taskName": "lint"
        },
```
2. Open Command Palette (Ctrl+Shift+P), type "lint"

Actual: There are several "lint" tasks defined by extensions, but my "lint" task does not appear in the list.  It seems to have moved under a new "Tasks: Run Task" submenu, which is not discoverable, not searchable, and takes more steps than necessary.

Expected: "ng lint" appears in the command palette.  Selecting it runs that task.

**Comment by alexr00** [comment]
@mikelward, I copied the json you had into a tasks.json file and then I was able to see the `lint` task after opening the Command Pallette and selecting `Tasks: Run Task`. Do you have any other repro steps?
Tasks version 0.1.0 is deprecated btw. To get the new features that have been added to tasks you should move to 2.0.0.

**Comment by mikelward** [comment]
@alexr00 Yes, it's there, per my first comment. (The title was a simplification.) But it's too hard to access.  My user-defined tasks should be *more* prominent than the irrelevant ones that extensions provide.  Currently, Ctrl+Shift+P, "lint" shows

 * Go: Lint Current Package
 * Go: Lint Workspace
 * Python: Enable Linting
 * Python: Run Linting
 * Python: Select Linter

but not my "lint" task.

It's my recollection that it used to also include any custom tasks matching that taskName/label.  Those are much more useful to me than the others.

Relatedly, I wouldn't mind so much about the menu if I could bind a keyboard shortcut to an arbitrary task like "lint".

**Comment by alexr00** [comment]
Ah. The items you're seeing in the Command Palette are Commands, not Tasks. You can write an extension that contributes a command if you want something to show up there. 

Tasks key binding: https://code.visualstudio.com/Docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks
