### ISSUE TITLE
Can't reorder editor unless it is the currently displayed editor

### ISSUE THREAD

**Issue by dlong500** [Microsoft/vscode#66505]
Issue Type: <b>Bug</b>

I'm not exactly sure when this bug was introduced, but I know it wasn't always the current behavior.

If I try to reorder an editor in the open editors tree by dragging/dropping then it works fine if the editor in question is the currently displayed editor.  However, if I try to reorder an editor that is not the currently displayed editor then it appears to be working until the mouse button is released, at which point in time it behaves as though I tried to drag/drop the displayed editor rather than the one that was actually chosen.

Attached is an animated GIF of the issue.
![vscode-dragdrop-issue](https://user-images.githubusercontent.com/430481/51147079-ed442200-1826-11e9-929f-4bd336cd2b1d.gif)

VS Code version: Code - Insiders 1.31.0-insider (2ab82c12ed809fd1df921d016eed344a18a9ee8f, 2019-01-14T06:18:47.017Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2672)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.99GB (2.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
vscode-eslint|dba|1.8.0
vscode-console-wrapper|fab|0.4.0
hjson|lak|0.3.1
ecdc|mit|1.0.5
vscode-icons|rob|8.0.0

</details>

**Comment by dlong500** [comment]
Can anyone provide feedback?  The issue still exists in the latest insider version (below) and disabling all extensions doesn't change anything.  I'm happy to provide more information if requested.  This issue really affects me as I frequently reorder editors.

Version: 1.31.0-insider (user setup)
Commit: b4fc71b972eae2425d39ac4041df0c36cfa1bb37
Date: 2019-01-15T06:19:08.621Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
fixed via 905f99525d
@dlong500 Thanks a lot for using insiders and for reporting
