### ISSUE TITLE
Change the cursor position after the code is commented

### ISSUE THREAD

**Issue by dxvgef** [Microsoft/vscode#66504]
I used cmd+/ to comment the current code. Can I have a setting to move the cursor to the next line automatically?

**Comment by usernamehw** [comment]
You can run multiple commands with https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command

**Comment by usernamehw** [comment]
* `editor.action.commentLine`
* `editor.action.insertLineAfter`

**Comment by dxvgef** [comment]
@usernamehw THX
