### ISSUE TITLE
Allow ctlr+p to continue searching when I change focus to another window.

### ISSUE THREAD

**Issue by vi-dot-cpp** [Microsoft/vscode#66500]
Let me start by saying that VS Code is the absolute best. I have but a small suggestion:

Ctrl+P search can take some time for large repositories, so I like to do other things in the meantime. However, the search aborts when VS Code loses focus. Would it be possible to change this behavior?

Thanks.

P.S. I would love to take on this work if it is appropriate.

**Comment by roblourens** [comment]
We actually have a setting for this, see `workbench.quickOpen.closeOnFocusLost`
