### ISSUE TITLE
Tab navigation in JSON settings editor is broken

### ISSUE THREAD

**Issue by theduke** [Microsoft/vscode#66509]
The JSON settings editor treats the whole editor split pane as a single tab target and does not allow navigation within the pane.

Targets that should be accessible with TAB:

* Left "Default" pane
* Right pane:
  * User / Workspace tabs
  * content editor

**Comment by sandy081** [comment]
We do not support JSON split settings editor in favour of new settings editor. Hence closing this.

**Comment by theduke** [comment]
You mean the split editor will be removed?

**Comment by sandy081** [comment]
It will not be removed now and the new UI editor will be the main primary editor we will
