### ISSUE TITLE
Group files with the same name but different extensions into a single virtual entry in the File Explorer

### ISSUE THREAD

**Issue by dandean** [Microsoft/vscode#66503]
In the classic Visual Studio's File Explorer it would group `.cs` files with an associated "designer" file, and would collapse them into a virtual folder. This was _great_ for cleaning up the file explorer.

The projects I work on currently have a very similar file pattern where one thing may consist of multiple files – each file serves a different roll around the single entity. Here's an example given a component which represents an Avatar:

* Avatar.tsx
* Avatar.scss
* Avatar.stories.ts
* Avatar.readme.md

What I would _love_ to see is a single `Avatar.tsx` entry. Clicking on the entry would open the TypeScript file by default (but this would also work for `.js` / `.jsx` files where people aren't using TypeScript). You could also expand the virtual folder to get at the associated SCSS, Storybook story, and Readme documentation.

Further, it would be nice to be able to do this by default for any file extensions, with some standard "primary" extensions to group things under. Given this, it would also work with `.css`, `.less`, `.markdown`, etc, etc.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/6328
