### ISSUE TITLE
Expose a way to get the Extension object for my extension

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#66515]
Until https://github.com/Microsoft/vscode/issues/15756 is addressed, I am attempting to ship a preview version of the PowerShell extension to the marketplace called "PowerShell Preview". To do so, I have to change the extension ID from `ms-vscode.PowerShell` to `ms-vscode.PowerShell-Preview`.

Unfortunately, there are a few instances where we reach into the package.json for the version and other things via:

```ts
    vscode
            .extensions
            .getExtension("ms-vscode.PowerShell")
            .packageJSON
            .version;
```

If I don't know what my extension ID is (either preview or stable in our case) how can I know the version, name, if I'm preview, etc about my extension from my extension?

**Comment by TylerLeonhardt** [comment]
Nah. Not if your trying to support a preview extention which has a different name.

If I use the same code for a "PowerShell" and a "PowerShell Preview" extension, how will I know the name of my extension?

**Comment by sandy081** [comment]
You can always have a new entry point for each extension and pass the extension type to the common code? I am trying to see if this can be fixed with tricks like these before introducing an API. Hope you get it.

**Comment by TylerLeonhardt** [comment]
That would be possible, yes... but this makes the code the configuration, when the package.json exists for this reason (configuration). We can agree to disagree on that... 

But I think it would be quite useful if `vscode.ExtensionContext` had reference to the `Extension` object or to the `packageJSON` or even to the name of the extension so that it could provide context (see what I did there 😊) as to what extension this code is running in.

A quick look at the vscode code... It seems that when the `context` is created for the extension, it has the `ExtensionIdentifier` so adding a property:

`vscode.ExtensionContext.name` or `vscode.ExtensionContext.id` or `vscode.ExtensionContext.extensionIdentifier` would be trivial to add.

If I submit a PR to add this to `vscode.ExtensionContext` would that be okay?

**Comment by sandy081** [comment]
@alexandrudima FYI

**Comment by alexandrudima** [comment]
@TylerLeonhardt I agree for this particular use-case us shipping some new API to give the extension its own extension id would be helpful. But we are trying to build "as little API as possible", the reason being that once we add something we can never remove it. We are also looking for synergies where adding API would help two or more different use-cases or different extensions...

I agree the solution suggested by @sandy081 might appear less elegant, but I don't think you are blocked in any way. I would therefore like to wait for other use-cases where this would be helpful before adding anything on our side.

Thanks!

**Comment by alexandrudima** [comment]
I am sorry but I still don't see how the lack of an API which gives you your own extension id is blocking you.
- @sandy081 has offered a valid solution. 
- another solution that I can suggest is to fish for your id in `__dirname`, for example. 
- another possible solution is to hardcode the main extension id in the sources, let's say `blabla` and just before publishing the insiders version do a big replace all in files of `blabla` with `blabla.insiders`.

There are many different ways to tackle this on your side, all of which don't involve us adding and maintaining API... I agree that it is easier if we were to offer such an API, but, again, we are defensive about adding needless API.
