### ISSUE TITLE
[Feature Request] Keybinding command for toggling diff indicator peek view

### ISSUE THREAD

**Issue by jonyeezs** [Microsoft/vscode#66518]
VSCode Version: 1.3.1.0-insider
OS: Windows

As a shortcut keyboard user i would like a command to toggle the _dirty-diff gutter decorator peek view_ (no idea what's the term) with a keybinding

This is what i'm talking about
![image](https://user-images.githubusercontent.com/10862726/51161183-2343dd80-18dd-11e9-8239-dd55951edd9f.png)

**Comment by usernamehw** [comment]
`editor.action.dirtydiff.next` - <kbd>Alt</kbd>+<kbd>F3</kbd>
`editor.action.dirtydiff.previous` - <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F3</kbd>

**Comment by jonyeezs** [comment]
Awesome! Thanks!
