### ISSUE TITLE
Powershell terminal - Cursor not visible

### ISSUE THREAD

**Issue by Disane87** [Microsoft/vscode#66527]
The cursor in a new powershell terminal is not visible.

- VSCode Version: 
```
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Datum: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Betriebssystem: Windows_NT x64 10.0.17763
``` 
- OS Version: Windows 10 x64 1809

Steps to Reproduce:
- Operning new Visual Studio Code 
- Open a new terminal
- Cursor is out of the view port and generally not visible
![image](https://user-images.githubusercontent.com/956158/51167705-8286fb00-18a7-11e9-8c16-ac478cca0506.png)
![image](https://user-images.githubusercontent.com/956158/51167715-89ae0900-18a7-11e9-8d13-9592220d619e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by HigHwindEx** [comment]
same problem...

**Comment by 21Junipers** [comment]
Anyone find the duplicate issue and resolution?
