### ISSUE TITLE
Reopen windows as they were before closing program

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#66525]
When I duplicate my workspace, close and reopen VS Code, only one window opens with just the default welcome tab (although there is a recent section), whereas I would like both windows to open, as they were before I closed the program. I guess this issue would then extend to also opening one or any number of windows as they were before the program was closed. In Firefox and Brave, when you close and reopen the program, it will reopen only one window as it was before. But still, it would be nice to see all previous windows reopen as they were before closing!

It also keeps prompting me to save my Workspace as a configuration file when I have already done so.

**Comment by bpasero** [comment]
@jamesray1 there is a setting: `"window.restoreWindows": "all"` that will reopen any number of windows that were previously opened. Note that duplicating a window will create an "untitled" workspace, so we ask on closing of the window if it should be saved.
