### ISSUE TITLE
rg

### ISSUE THREAD

**Issue by tan215210976** [Microsoft/vscode#66524]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.The rg.exe process causes the computer to take up 100% of the CPU

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please give exact details. What do you do and what do you see? Which version of vscode are you using?

**Comment by roblourens** [comment]
Can you get the command line args of these processes from the process explorer, task manager, etc?

**Comment by tan215210976** [comment]
[](url
![o 689__ ri bk3 8uo 11](https://user-images.githubusercontent.com/44597080/51230950-b5f78180-199c-11e9-8f10-10d038a675e0.png)
)

**Comment by tan215210976** [comment]
![j_w si82iww3n0u aokvhj](https://user-images.githubusercontent.com/44597080/51231048-18e91880-199d-11e9-89e8-bf103cd5002a.png)

**Comment by roblourens** [comment]
- Run `code --status`, it should print info about running processes
- Past the info here
