### ISSUE TITLE
Error 407

### ISSUE THREAD

**Issue by s8iva** [Microsoft/vscode#6652]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Ext Install - displays list of extension
2. On clicking the extension I get a 407 error.
3. I have tried by setting proxy and without, the behavior is the same.

**Comment by joaomoreno** [comment]
407 means your proxy requires authentication. You can specify that in the `http.proxy` configuration setting by using the following format: `http://USER:PASSWORD@proxyurl/`
