### ISSUE TITLE
Lots of console output slows down/freezes UI

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#66528]
Issue Type: <b>Bug</b>

I have an application that generates a lot of console output. I can watch VS Code slow down to a freeze within less than a minute of runtime. When I keep manually clearing the console, the UI does not become unresponsive.

When I pause the code being run, the UI instantly becomes responsive again.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (49.94GB free)|
|Process Argv|core-rpc2/core-rpc2.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal-formatter|ale|2.1.0
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.6
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
code-beautifier|mic|2.1.0
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|4.11.1

(1 theme extensions excluded)

</details>

**Comment by blogcraft** [comment]
I have the same problem with the console.

When debugging a .Net Core with Angular template, there is a lot of output in the Debug Console. I have to clean it way too often to be able to keep VS stable.

**Comment by Tyriar** [comment]
@oliversalzburg are you talking about the debug console?

**Comment by oliversalzburg** [comment]
@Tyriar Yes. I haven't noticed the same behavior with the terminal.

**Comment by isidorn** [comment]
This is fied in latest vscode insiders.
Please try it with vscode insiders and if you can reproduce let us know and we will reopen this issue
https://code.visualstudio.com/insiders/

**Comment by oliversalzburg** [comment]
@isidorn Other than switching to Insiders, are there workarounds for this issue?

**Comment by isidorn** [comment]
No. Sorry.
You can use the externalTerminal as a launch configuration option. So all the output is sent to the external terminal.

There will be a new stable build with this fixed in a week.

**Comment by oliversalzburg** [comment]
> There will be a new stable build with this fixed in a week.

Awesome. Thanks
