### ISSUE TITLE
More powerful code tracking is needed

### ISSUE THREAD

**Issue by IT-Rafi** [Microsoft/vscode#66534]
Can you strengthen your code tracking capabilities?

**Comment by sandy081** [comment]
@IT-Rafi Not sure what you are reporting here as the description looks irrelevant to the summary. Can you please explain in detail about your requirement or bug.

**Comment by IT-Rafi** [comment]
> @IT-Rafi Not sure what you are reporting here as the description looks irrelevant to the summary. Can you please explain in detail about your requirement or bug.

Can you enhance the code tracking function?

**Comment by sandy081** [comment]
> Can you strengthen your code tracking capabilities?

@IT-Rafi Yeah I can.. 😄 

Can you please explain me the requirement in detail with some steps or screenshots or a video?

**Comment by IT-Rafi** [comment]
> > Can you strengthen your code tracking capabilities?
> 
> @IT-Rafi Yeah I can.. 😄
> 
> Can you please explain me the requirement in detail with some steps or screenshots or a video?

![image](https://user-images.githubusercontent.com/14018521/51452262-460a4200-1d74-11e9-8caf-37832ee0f838.png)

Click on the component name to jump into the code for this component, but currently the experiment cannot jump

**Comment by mjbvz** [comment]
Your project likely needs additional configuration. Please ask this on github

**Comment by IT-Rafi** [comment]
> Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

Thanks
