### ISSUE TITLE
Menu scrollbar prevents submenu items to be selected using mouse

### ISSUE THREAD

**Issue by ceefour** [Microsoft/vscode#66537]
Issue Type: <b>Bug</b>

1. Zoom in so that menus show scrollbar
2. Try to select a submenu using mouse
3. It's extremely hard to pick the submenu using mouse (without very good & fast mousing skills), because everytime the pointer hovers over the scrollbar it "scrolls" the menu hiding the submenu.

See video for clarity: https://youtu.be/cA2rHREdvVw

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (3.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
cucumberautocomplete|ale|2.13.0
erb|Cra|0.0.1
xml|Dot|2.4.0
es7-react-js-snippets|dsz|1.9.5
prettier-vscode|esb|1.7.3
gc-excelviewer|Gra|2.1.26
Scala|itr|0.1.7
latex-workshop|Jam|5.20.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
python|ms-|2018.12.1
azure-account|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
vscode-ts-react-redux-mui-snippets|mur|1.0.2
vscode-docker|Pet|0.5.1

</details>

**Comment by sbatten** [comment]
@ceefour menu scroll stability was improved this milestone, you can test it out with the latest insiders.
