### ISSUE TITLE
Cursor still yellow

### ISSUE THREAD

**Issue by workingJ** [Microsoft/vscode#66536]
Issue Type: <b>Bug</b>

i used a dark themes for a long time an changed my cursor color to yellow, 
but now after switching to light themes i chaged the cursor color to black 
but its still yellow....

    "workbench.colorCustomizations": {
        "editorCursor.foreground": "#000000",
        "editorCursor.background": "#000000",

I also commented out all other color customizations but the cursor still remains yellow...

I activated and deactivated some themes before i changed the cursor color, maybe it had some affect...

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
search-crates-io|bel|1.2.1
better-toml|bun|0.3.2
vsc-rustfmt|Con|0.1.0
vscode-markdownlint|Dav|0.23.0
vscode-rust-syntax|dun|0.0.30
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.1
copy-markdown-as-html|jer|1.1.0
vscode-rust|kal|0.4.2
vscode-language-pack-de|MS-|1.30.2
vscode-icons|rob|8.0.0
rust|rus|0.5.3
crates|ser|0.3.6
ayu|tea|0.17.0
markdown-all-in-one|yzh|1.8.0

(13 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please check if you have done colour customisations in workspace settings file which might be taking the precedence?

**Comment by workingJ** [comment]
Yesterday i delete my whole vscode setup, and every file and every thing and started fresh.
vscode seems to start now a little faster. maybe i had too much chached stuff...
now everything works fine.
And yes, today i found that i had a customisation in the workspace i used.
I totally forgott about it and overlookt it yesterday...

so thx.
you can close the issue.
