### ISSUE TITLE
Support using code as file compare tool from CLI

### ISSUE THREAD

**Issue by lhaeger** [Microsoft/vscode#66539]
I very much like the file comparison feature built into Code and would like to request making this available via CLI, e.g. as "code --compare file1 file2" or similar. 
Bonus points for Explorer and Finder extensions that add a "Compare with VB Code" context menu utilizing the above for easy invocation from the UI.
Even more bonus points for supporting folder comparisons in a similar way... :-)

**Comment by bpasero** [comment]
<img width="758" alt="screenshot 2019-01-15 at 14 49 06" src="https://user-images.githubusercontent.com/900690/51184522-ca704700-18d4-11e9-8375-9be72b27d885.png">

**Comment by lhaeger** [comment]
Oops. I did check https://code.visualstudio.com/docs/editor/command-line but only searched for compare, I guess...
