### ISSUE TITLE
Unsaved temp files mess up the Untitled number in their file names

### ISSUE THREAD

**Issue by cateyes99** [Microsoft/vscode#66532]
- VSCode Version: 1.30.1 **_zip_** 64 bit installer
- OS Version: Windows 10 & Windows 7

Steps to Reproduce:

1. Run VSCode and then open a folder in VSCode.
2. Create a new unsaved temp file which VSCode gives a name of `Untitled-1` automatically.
3. Then create another two unsaved temp file, `Untitled-2` and `Untitled-3`.
4. Now close all the three files, `Untitled-1`, `Untitled-2` and `Untitled-3`.
5. Close the VSCode application itself as well.
6. Start VSCode again and open the same folder.
7. Create a new unsaved temp file. Observe the new file name **isn't** `Untitled-1` as expected anymore, but `Untitled-3`!
8. We can repeat it by creating more unsaved temp files...

This is very **annoying**! I think it behaves this way quick recently maybe since `1.30.0` **_zip_** 64 bit installer.

I've tried to delete the folder `C:\Users\MYACCOUNT\AppData\Roaming\Code` completely. This resets back to `Untitled-1` when creating a new unsaved temp file, so looks ok. But when repeating the the above steps, it behaves still exactly the same as described in the above steps, meaning removing that `~\AppData\Roaming\Code` doesn't fix the hehaviour but only resets the count back to `Untitled-1`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This issue was fixed for 1.31. You can switch to our insider builds to benefit from the fix.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
