### ISSUE TITLE
Title Bar Flickers on Pane Switching

### ISSUE THREAD

**Issue by Qrokqt** [Microsoft/vscode#66549]
Issue Type: <b>Bug</b>

When switching panes the title bar flickers when using Windows Classic Theme.

Flicker still occurs with --disable-gpu.

![title_flicker](https://user-images.githubusercontent.com/17385843/51193527-098f9f80-18b7-11e9-8be4-e3f0d8124c95.gif)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.14.5
subtle-brackets|raf|3.0.0
highlight-matching-tag|vin|0.8.5

(1 theme extensions excluded)

</details>

**Comment by hollyph** [comment]
how

**Comment by hollyph** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Screen Flickering (#65762)](https://www.github.com/Microsoft/vscode/issues/65762)
> * [Screen Flickering (#65763)](https://www.github.com/Microsoft/vscode/issues/65763)
> * [Screen Flicker (#65850)](https://www.github.com/Microsoft/vscode/issues/65850)
> * [Menubar: flicker on switch to full screen mode (#55511)](https://www.github.com/Microsoft/vscode/issues/55511)
> * [Flickering issue on Ubuntu Linux (#62128)](https://www.github.com/Microsoft/vscode/issues/62128)

**Comment by bpasero** [comment]
@sandy081 custom title is @sbatten
