### ISSUE TITLE
Intellisense with require

### ISSUE THREAD

**Issue by entr0cks** [Microsoft/vscode#66546]
Issue Type: <b>Bug</b>

Noticed after some months and some updates of not using node.js (at least any external modules) that "require" doesn't offer intellisense even in older projects. Suggests using import, with which intellisense works.

*Edit: forgot to add images*
![import_fs](https://user-images.githubusercontent.com/5465193/51191482-26df6080-18ed-11e9-83a2-84fd83ad6172.PNG)
![require_fs](https://user-images.githubusercontent.com/5465193/51191483-2777f700-18ed-11e9-8e8e-904bd94a8c07.PNG)
Require has a little decoration, because: 
![require_msg](https://user-images.githubusercontent.com/5465193/51192007-41fea000-18ee-11e9-826c-36b208d171c5.PNG)

Have tried removing all extensions and settings, clean installing latest stable vscode 1.30.2 and 1.29.1, and making a new project in another folder - behaved identically. Also tried suggested tsconfig.json.
I've disabled suggestion to import in settings, to not get suggestions for "import {readFile} from 'fs'".
Usually setup with "npm init" and then "npm i -D @types/node" (tried also without -D). Also tried multiple also dev release of typescript.
Didn't notice any errors in TS log.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by entr0cks** [comment]
Interestingly the output .js files have working intellisense for require.

**Comment by jas99** [comment]
@mjbvz Man this is very annoying. Sometime one have to require some function in typescript thats not typed and these is not even function signatues shown in ts file but vscode figures it out in js file. 

More over tslint plugin complains even when I put disable comment for some section.

**Comment by entr0cks** [comment]
Mentioning that vscode 1.31.0 and TS 3.3.1 selected hasn't impacted this.

`import fs = require('fs');` works too, but is still less useful, can't do `import {property} = require('module')`, can do `import {property} from 'module'` - getting bit odd js from it, requires whole thing into a temporary variable and adds another line to assign the property to the name I declared. In the same pattern have to do `import * as module from 'module'` to get regular stuff. Import is just more cumbersome for me. 
Side note: better json support would be nice as well... (I think we used to have this...)

**Comment by mjbvz** [comment]
This sounds similar to https://github.com/Microsoft/TypeScript/issues/30056

@entr0cks Does intellisense for require never work in your project, or only after you make some edits? Also, do you have a small example project that shows this behavior?

**Comment by entr0cks** [comment]
Similar to linked issue.
Never works on the few computers that I have. Just create a new .ts file and require into a var/let/const, the type of that will be any (see my prev comments).
