### ISSUE TITLE
strict null check 'vs/base/parts/tree/browser/treeView.ts'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#66557]
Part of #60565

Tracks updating `vs/base/parts/tree/browser/treeViewModel.ts` to have strict null checking. Related files:

- `vs/base/parts/tree/browser/treeViewModel.ts`
- `vs/base/parts/tree/test/browser/treeViewModel.test.ts`

**Steps**

1. Add `vs/base/parts/tree/browser/treeViewModel.ts` to the `include` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works

**Comment by joaomoreno** [comment]
Also did `treeView.ts` which was the most problematic.
