### ISSUE TITLE
command works differently per-task vs base task

### ISSUE THREAD

**Issue by mikelward** [Microsoft/vscode#66552]
- VSCode Version: 1.30.2
- OS Version: Debian GNU/Linux testing

Steps to Reproduce:

1. Configure a task
```
    "version": "2.0.0",
    "command": "ng",
    "tasks": [ 
        { 
            "label": "lint",
            "args": ["lint"]                                                    
        },
```

Expected results:

It works the same as

```
    "version": "2.0.0",
    "command": "ng",
    "tasks": [ 
        { 
            "command": "ng",
            "label": "lint",
            "args": ["lint"]                                                    
        },
```

i.e. defining "command" on at the per-task level has the same effect as defining it at the base task configuration level.

Actual results:

It runs "ng lint lint" instead of "ng lint".

**Comment by dbaeumer** [comment]
This is old legacy support. In a first version we didn't have a command per task. The support was more to integrate task runners (like gulp) where you have one command and the pass the task name / label as an argument. We still do this in case of a global command.

**Comment by alexr00** [comment]
I see, thanks for the background. @mikelward, this is by design. having a global command is supposed to work differently.
