### ISSUE TITLE
Extension "Contributions" view displays placeholder strings when package.nls.json is used

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode#66551]
The Extension view's Contributions tab doesn't work when strings are externalized to `package.nls.json`. I would like it if this view replaced the `package.json` placeholders with their translated values, because this might look like a bug in my extension to a user (even though this is likely the behaviour the VSC team expects).
![image](https://user-images.githubusercontent.com/8888438/51197233-ea950b80-18be-11e9-85fd-4678bed2e37f.png)

**Comment by sandy081** [comment]
Duplicate of #31993
