### ISSUE TITLE
[folding] Collapse button is too close to text when selecting

### ISSUE THREAD

**Issue by sirmspencer** [microsoft/vscode#66553]
When I am selecting text that starts near a collapse button I way to often hit the collapse button instead.  This may be most prominent on my laptop where the precision of my mouse pad is not as high as a gamers mouse.  

Instead of adding more space, would it be possible to change the event handler of the collapse to mouse up and check to make sure it is still over the button?  For example, if the user accidentally clicks on the button but continues to drag the mouse to select text, the collapse action will not happen.

![image](https://user-images.githubusercontent.com/33734037/51200524-9c780c00-18ae-11e9-9655-18055aca869a.png)

**Comment by aeschli** [comment]
I'm not able to reproduce this. The fold action reacts to mouse up and checks that the mouse down happened on the same line. See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/folding/folding.ts#L407
