### ISSUE TITLE
Test language supports refactorings

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6655]
Test for #xxx:

There have been refactorings to the datastructures of these language supports to align them on the UI side with the extension host side.

Please try the following functionalities once.

It does not matter on which platform you test, as this code is platform independent. 

Please try once with a language that is built-in (e.g. css, less, sass, html, handlebars, markdown, razor) and with a language that is an extension (e.g. javascript, typescript, etc.). It is possible that not all languages implement all supports (e.g. link provider is used by html, handlebars and razor and not the rest, so you might need to pick a different language to check for each support).

* [x] **@bpasero**
* ReferenceProvider
* RenameProvider
* Suggest
* SignatureHelpProvider

* [x] **@isidorn**
* HoverProvider
* DocumentSymbolProvider
* DocumentHighlightProvider
* DefinitionProvider
* CodeLensProvider

* [x] **@aeschli**
* CodeActionProvider
* DocumentFormattingEditProvider
* DocumentRangeFormattingEditProvider
* OnTypeFormattingEditProvider
* LinkProvider

**Comment by bpasero** [comment]
@alexandrudima can you clarify how to test this? and if it is platform independent why do we have 3 testers assigned?
