### ISSUE TITLE
Open with code doesn't work as expected

### ISSUE THREAD

**Issue by ap-r** [Microsoft/vscode#66559]
I clicked right mouse button inside a folder and choosed "Open with Code" from the Windows context menu. It opened the folder I worked with in Code last time and not the one which was opened in the Windows explorer. Also a window with some information about product updates appeared. I closed the programme. I did the same thing again and then it worked - it opened the right folder. I don't think it should work this way. It's quite confusing. I don't trust my Windows anymore. Sorry for potential language errors. Or if I am totally mistaken and shouldn't create this issue.

additional info:
Windows 10
version 1803
OS build 17134.523

I don't know how you add the info about a system, so I paste the content of attachments here:

CPUs | AMD A8-4500M APU with Radeon(tm) HD Graphics (4 x 1896)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: unavailable_softwarevideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 3.20GB (0.54GB free)
Process Argv | C:\Users\aresz\Documents\vuejs-techniki-zaawansowane\zrodla\Start\11ed
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
vetur | oct | 0.14.3
java | red | 0.36.0
vscode-java-debug | vsc | 0.16.0
vscode-java-dependency | vsc | 0.3.0
vscode-java-pack | vsc | 0.5.0
vscode-java-test | vsc | 0.13.0
vscode-maven | vsc | 0.13.0

**Comment by bpasero** [comment]
@ap-r so after the update was applied, does this issue still reproduce?

**Comment by ap-r** [comment]
No.

**Comment by bpasero** [comment]
Ok this makes it hard to understand/reproduce. Please let us know when you see this again.
