### ISSUE TITLE
Extension Host Erroring at start up

### ISSUE THREAD

**Issue by ken-ignidus** [Microsoft/vscode#66555]
Issue Type: <b>Bug</b>

Currently when I start VS Code I get an dialog stating that the Extension Host has errored and asking me to restart the Externsion Host or open the Developers Tools Dialog. When I reviewed the Console Log (see below) it looks like the ms-python extension is trying start a debugging session and is failing because the process is running out of memory. 

A questions come to mind with this error:
1) Why is VS Code starting a debugging listener at start up? This should be an on demand start up process.
2) I've recently reinstalled my node modules. Maybe there is a failure to load an extension because a dependecy isn't available. There might be a need to do a self healthing attempt (npm install) upon certain types of failures.
3) It would be nice to have "Start in Safe Mode" option to note start up with any extensions or present a dialog stating which extension is actually failing allow the user to figure out how to fix the extension.

Console Log:

> [Extension Host] debugger listening on port 18618
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5723 [ms-python.python]: Command `python.datascience.exportoutputasnotebook` appears multiple times in the `commands` section.
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Debugger listening on ws://127.0.0.1:18618/54483b40-b871-4edb-81de-97975ddfee53
> For help see https://nodejs.org/en/docs/inspector
> 
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1504  INFO no standard startup: not a new window
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
> t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Debugger attached.
> 
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1504  WARN UNRESPONSIVE extension host, 'reflectiondm.npmsmartimporter' took 81% of 5168.555ms, saved PROFILE here: '/var/folders/1z/jgfg220j0xb588t1cr6pzrcw0000gq/T/exthost-033eb6.cpuprofile' Array(3)0: id: "gc"percentage: 16total: 841421__proto__: Object1: id: "program"percentage: 3total: 140323__proto__: Object2: id: "reflectiondm.npmsmartimporter"percentage: 81total: 4184378__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()arguments: (...)caller: (...)length: 0name: "get __proto__"__proto__: ƒ ()set __proto__: ƒ __proto__()arguments: (...)caller: (...)length: 1name: "set __proto__"__proto__: ƒ ()length: 3__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Debugger listening on ws://127.0.0.1:18618/54483b40-b871-4edb-81de-97975ddfee53
> For help see https://nodejs.org/en/docs/inspector
> 
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3266 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  2: node::FatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  6: v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(unsigned long, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  7: v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(unsigned long, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  8: v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(unsigned long, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
>  9: v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(unsigned long, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
> 10: v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(unsigned long, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
> 11: 0x3b4907b8463d
> 
> <--- Last few GCs --->
> 
> [94416:0x7fab35001800]   199712 ms: Mark-sweep 2051.8 (2124.0) -> 2051.8 (2096.5) MB, 2680.8 / 1.3 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2681 ms) last resort GC in old space requested
> [94416:0x7fab35001800]   202174 ms: Mark-sweep 2051.8 (2096.5) -> 2051.8 (2096.5) MB, 2460.9 / 0.9 ms  last resort GC in old space requested
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x4d29b42b0a1 <JSObject>
>     1: makeAbs [/Users/kensimeon/.vscode/extensions/reflectiondm.npmsmartimporter-3.0.0/node_modules/glob/common.js:~203] [pc=0x3b4907d410a1](this=0x4d2800d0e29 <Object map = 0x4d2b46d31f1>,self=0x4d2da5d8759 <Glob map = 0x4d28b5697c9>,f=0x4d2de4077d9 <String[111]: /Users/kensimeon/dev/src/testing/qa/results/allure-results/cdc61b44-69f6-4aa9-8cc3-25d89e991fdc-attachment.json>)
>     2: /* anonymous...
> 
> 
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5716 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
> t._onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5716
> /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2508 Extension host terminated unexpectedly.
> t.onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2508
> 
> VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
> OS version: Darwin x64 18.2.0
> 
> <details>
> <summary>System Info</summary>
> 
> |Item|Value|
> |---|---|
> |CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
> |GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
> |Load (avg)|3, 3, 2|
> |Memory (System)|16.00GB (2.02GB free)|
> |Process Argv||
> |Screen Reader|no|
> |VM|0%|
> 
> </details><details><summary>Extensions (7)</summary>
> 
> Extension|Author (truncated)|Version
> ---|---|---
> project-manager|ale|10.2.0
> githistory|don|0.4.4
> gitlens|eam|9.4.1
> python|ms-|2018.12.1
> material-icon-theme|PKi|3.6.2
> npmsmartimporter|ref|3.0.0
> vscode-todo-highlight|way|1.0.4
> 
> (1 theme extensions excluded)
> 
> </details>
>

**Comment by weinand** [comment]
The "debugger-listener" is perfectly fine. It just means that a debugger could be used to attach to the extension host. 

 "Start in Safe Mode" can be achieved by using VS Code's "Disable all installed extension" command.

**Comment by ken-ignidus** [comment]
Thanks for all the information @weinand. I did disable the offending plugin(s) to get past the issues I was experiencing. At some point I'll go back to get the extensions working properly.
