### ISSUE TITLE
Launching VSCode after update crashes Chrome

### ISSUE THREAD

**Issue by BenniG123** [Microsoft/vscode#66554]
Issue Type: <b>Bug</b>

I downloaded VSCode update for the latest version
Click Update Now
VSCode closes and a progress bar shows it updating
The instant VSCode re-opens, Chrome crashes

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (25.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1
PowerShell|ms-|1.10.2

</details>

**Comment by bpasero** [comment]
@BenniG123 you mean an external instance of Chrome crashed unrelated to VSCode?
