### ISSUE TITLE
Live Share undo affects other users' work in their editors

### ISSUE THREAD

**Issue by anjunatl** [Microsoft/vscode#66567]
Issue Type: <b>Bug</b>

I was editing code with a friend using Live Share and noticed my undos were also deleting his work. I only expected to see it remove text from my editor, not his too.

Reproduction steps:

- Start a live share session with one other user
- Write code into the session at the same time
- Stop typing, let the other user continue typing
- Start using(/spamming if you want) CTRL+Z and you both will eventually see the other user's text being removed

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (5.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.0
markdown-emoji|bie|0.0.7
es7-react-js-snippets|dsz|1.9.5
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.6
prettier-vscode|esb|1.7.3
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
python|ms-|2018.12.1
vsliveshare|ms-|0.3.1120
debugger-for-chrome|msj|4.11.1
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Please create an issue against live share extension - https://github.com/MicrosoftDocs/live-share/issues

**Comment by anjunatl** [comment]
@sandy081 Mybad - thanks!

Found it over there: https://github.com/MicrosoftDocs/live-share/issues/1439
