### ISSUE TITLE
Elementary OS static filling canvases after un-suspending machine

### ISSUE THREAD

**Issue by Sammons** [microsoft/vscode#66563]
- VSCode Version: 1.30.1
- OS Version: Elementary OS 5.0 Juno

Steps to Reproduce:

1. Install Visual Studio Code on Elementary OS x64:
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

2. Open integrated terminal, use minimap
3. Suspend elementary OS
4. Wake up the machine
5. Observe excellent static
![screenshot from 2019-01-15 18-32-16](https://user-images.githubusercontent.com/1619603/51216886-f0591400-18f3-11e9-82fb-71a0cde1d91d.png)

6. Minimizing/maximizing vs code does not fix it, but closing reopening does.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by JostCrow** [comment]
I have the same issue on Solus.
I have also tried insiders. Here the same issue continues with the terminal. It will be completely unusable after I suspeneded my laptop. So much so that I started to used the terminal app again.

![screenshot from 2019-01-17 09-22-21](https://user-images.githubusercontent.com/390575/51304810-6adf7c00-1a39-11e9-854e-a4ed23b7fb36.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by JostCrow** [comment]
@bpasero Is here a .tar.gz linux version? I can not install debs

**Comment by bpasero** [comment]
@JostCrow https://az764295.vo.msecnd.net/exploration/584c13e5ff8eed9502f1bce13e5e9f21cbcf6c27/code-exploration-1547629033.tar.gz

**Comment by JostCrow** [comment]
Sadly the issue is still there

![screenshot from 2019-01-17 10-32-39](https://user-images.githubusercontent.com/390575/51308810-48eaf700-1a43-11e9-99fd-d11fd60e6770.png)

**Comment by bpasero** [comment]
@JostCrow does it reproduce if you run "code --disable-gpu" from the command line?

**Comment by JostCrow** [comment]
Running it with `code --disable-gpu` solved the problem for me in version 1.30.2
