### ISSUE TITLE
Very very very slow

### ISSUE THREAD

**Issue by jimblue** [Microsoft/vscode#66560]
Issue Type: <b>Performance Issue</b>

Hello,

I'm using VsCode for 2 years now.
I've always feel that the UI could be more responsive but it's getting worst for a few months.
So I've decided to try the insider version and for some time I've notice some small improvements.

But recently, I would say for 3 weeks, the experience became terrible.
The UI is so slow that I can wait more then 2 seconds when switching from files explorer to search panel or git panel. Even resizing VsCode window is completely lagging... It's nearly impossible to work like that!

I've follow the Wiki post about performance and tried with all extensions disable but it didn't change anything.

I hope you have some kind of fix, it's terrible to have such a nice software lagging that much.

VS Code version: Code - Insiders 1.31.0-insider (b4fc71b972eae2425d39ac4041df0c36cfa1bb37, 2019-01-15T06:12:40.322Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (5.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   147	 21826	code-insiders main
    0	   131	 21827	   gpu-process
    0	   295	 21828	   window (navbar.html — jmbnew)
   12	   197	 22619	     extensionHost
    0	    49	 22622	       electron_node server.js 
    0	    49	 22624	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=22619
    0	    82	 22625	       electron_node server.js 
    0	    98	 22626	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=22619
  137	   721	 22646	       electron_node server.js 
    0	    49	 22620	     watcherService
    0	    49	 22621	     searchService
    0	    98	 22616	   shared-process
    0	    98	 22671	   window (Issue Reporter)
    0	     0	 22672	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (navbar.html — jmbnew)
|    Folder (jmbnew): 12141 files
|      File types: php(5219) json(3976) svg(343) jpg(331) md(313) js(264)
|                  yaml(180) png(165) test(142) vue(127)
|      Conf files: package.json(9) gulp.js(3) makefile(2) webpack.config.js(1);
```

</details>
<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
language-antlers|ahd|0.0.4
markdown-preview-github-styles|bie|0.1.4
vscode-intelephense-client|bme|0.8.8
vscode-tailwindcss|bra|0.1.16
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
mjml-syntax|dig|0.0.1
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
output-colorizer|IBM|0.1.2
svg|joc|0.1.4
contextualduplicate|laf|0.2.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
vscode-icons|rob|8.0.0
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.4
vscode-nginx|sha|0.6.0
stylelint|shi|0.47.0
highlight-matching-tag|vin|0.8.5
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@jimblue Thanks for filing the issue.

Can you please reproduce the slowness and create a cpu profile by following https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process and share it with us

**Comment by jimblue** [comment]
@sandy081 tks for your fast answer.

Here is the cpu profile: https://gist.github.com/jimblue/75925fe24ef831febfb4bbf18437a377

I hope it helps.

**Comment by bpasero** [comment]
```
0	    98	 22626	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=22619
  137	   721	 22646	       electron_node server.js 
```

**Comment by octref** [comment]
Does removing `auto-rename-tag` extension help?

**Comment by jimblue** [comment]
@octref in my first comment:

> I've follow the Wiki post about performance and tried with all extensions disable but it didn't change anything.

**Comment by octref** [comment]
Sorry, missed that. I asked because the extension quadruples the HTML parsing on each input and has been a cause for slowness. The other one that could be problematic is `html-css-class-completion` since it scans your workspace folder.

Does this only happen when you start editing HTML files? If you open an empty folder and only edit CSS files, does VS Code slows down?

Also, can you try `code --disable-extensions --usr-data-dir ./foo`, and see if VS Code slows down?

**Comment by aeschli** [comment]
Can you add `"html.trace.server": "verbose"` in the settings and when you see the slowdown, look at the `HTML Language Server` output view to see whats currently going on?

![image](https://user-images.githubusercontent.com/6461412/51460973-2d426200-1d5d-11e9-9597-8c2a772d270d.png)
