### ISSUE TITLE
vscode insiders 1.31.0 fixes issue 61209

### ISSUE THREAD

**Issue by myron-randall** [Microsoft/vscode#66564]
- VSCode Version: 
Version: 1.31.0-insider (system setup)
Commit: 2ab82c12ed809fd1df921d016eed344a18a9ee8f
Date: 2019-01-14T06:18:47.017Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
- OS Version: Windows 7

Steps to Reproduce:

1. Install vscode insiders 1.31.0
2. Run on windows 7

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
@myron-randall Do not understand what is the intention of this issue?

**Comment by myron-randall** [comment]
A previous issue #61209 was closed due to not enough information and inactivity. This is just to let the community know that this is now fixed with the latest insider build.

**Comment by sandy081** [comment]
Ok.
