### ISSUE TITLE
keyboard layouts switches to US when running as sudo on mac

### ISSUE THREAD

**Issue by rasmus0201** [microsoft/vscode#66578]
**System details:**
OS: MacOS Mojave - 10.14.2
VSCode - 10.30.2
Extensions: None

**Setup / Problem:**
SSH mounted directory, which has some specific permissions that is not allowed to be changed. Due to the VS code always asks for admin user password on save. Because of that i run Code as sudo. with this script `sudo "/Applications/Visual Studio Code.app/Contents/MacOS/Electron" &>/dev/null &`. When Code opens I now have US keyboard layout despite the fact I have a nordic keyboard. This only happens when I tun code as sudo. Code uses the correct keyboard layout (nordic) when I start normally (e.g code in terminal or open by shortcut).

**Reproducible steps:**

1. Have a nordic keyboard (don't know if the bug is present for other non-us keyboards)
2. Start VSCode with the script (`sudo "/Applications/Visual Studio Code.app/Contents/MacOS/Electron" &>/dev/null &`)
3. Try create/edit a file and the keyboard in VSCode is not corresponding to the actual keyboard.
4. Quit VSCode
5. Try to open code with code in terminal
6. Now it is the correct keyboard layout.

Expectation: Adopt keyboard layout from actual keyboard.
Reality: Sudo use forces us keyboard layout

Edit:
I use the Logitech K750-mac keyboard nordic/danish layout

**Comment by Bluezen** [comment]
Hello, I think it forces the us layout when using sudo because the bug is present for fr keyboards as well!

**Comment by alexandrudima** [comment]
Is there any software you use that you can launch with `sudo` which respects the user selected keyboard layout? I think perhaps this is the way macOS works... What happens if you launch Chrome from the terminal as root? What keyboard layout does it use?

**Comment by rasmus0201** [comment]
I think it's a (bug?) in MacOS Mojave because it's working fine opening programs as sudo in MacOS High Sierra 10.13.6 - it respects user keyboard layout. Something happened between this version an MacOS Mojave where opening any program as sudo always forces US keyboard layout. 

I've opened a bug report at Apple 6 months ago - but no answer at all.

This is very frustrating as the majority of the time in my job I require to open IDE's with sudo, but this "bug" really slows my effectivity and productivity because I always have to provide my sudo/user password when eg. saving a file.

So even though Apple might not fix this in the shortrun, I think you could investigate how to improve this - because it's a problem for many users (I've talked to over the past 6 months).

Regards Rasmus.

**Comment by igormuba** [comment]
I am also having this issue on Mojave and it is very annoying... I need to run as sudo, but if I do I can't use my external keyboard because the layout is messed up.....

**Comment by Chrtol** [comment]
I'm having this bug as well. Any updates?

**Comment by igormuba** [comment]
I don't like my solution, but since I run on a virtual environment, my solution, if you are running on Linux, Mac or BSD, is to run on the folder of the project I am working with `sudo chmod -R 777 .`, this gives all rights to edit the project folder, so I do not have to run visual studio as admin. Not a definitive solution and of course not good for all workflows, but to me that suffice. Not what I wanted, but while this bug still exists may help someone.
