### ISSUE TITLE
Dynamic Extension Points

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#66574]
We want to be able to dynamically install/enable or uninstall/disable extensions. For this, we need to adopt that extension points are dynamic. This is done by adding `isDynamic: true` to the `registerExtensionPoint` call.

When an extension is added/removed at runtime, all of its extension points will have their handlers invoked again. The handler conforms to the following type:
```ts
export interface IExtensionPointHandler<T> {
	(extensions: IExtensionPointUser<T>[], delta: ExtensionPointUserDelta<T>): void;
}
```

The first argument will always be the complete list of extensions that use the extension point and the second (newly added) argument will be the delta since last time the handler was called.

---

You can test this by having an extension that exercises your extension point and enabling/disabling the extension.

Extension points:

- [x] viewsContainers @sandy081 
- [x] views @sandy081
- [x] debuggers @isidorn @weinand (let's talk)
- [x] breakpoints @isidorn @weinand
- [x] localizations @sandy081 (should probably never be dynamic)
- [x] snippets @jrieken 
- [x] problemPatterns @dbaeumer @alexr00 
- [x] problemMatchers @dbaeumer @alexr00 
- [x] taskDefinitions @dbaeumer @alexr00
- [x] commands @jrieken 
- [x] menus @jrieken 
- [x] configurationDefaults @sandy081 
- [x] configuration @sandy081 
- [x] jsonValidation @aeschli 
- [x] keybindings @alexandrudima 
- [x] languages @alexandrudima 
- [x] grammars @alexandrudima 
- [x] colors @aeschli 
- [x] themes @aeschli 
- [x] iconThemes @aeschli 
- [x] resourceLabelFormatters @isidorn

**Comment by isidorn** [comment]
I have made the following contributions dynamic: `debuggers`, `breakpoints` and `resourceLabelFormatters`.

If a user disables a debugger of a type that he is currently debugging we will stop that session. Example: user is debugging Pyhtong and disables the python extension -> the python debug session will quit.

**Comment by alexandrudima** [comment]
Thank you! :heart:
