### ISSUE TITLE
New Explorer: focus lost when Shift+Up/Down in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66589]
Refs: https://github.com/Microsoft/vscode/issues/66485

* select a file in the explorer
* shift+up to select to the top
* shift+down to select to the bottom

At one point the explorer seems to loose focus?

![before](https://user-images.githubusercontent.com/900690/51239227-15439a80-1979-11e9-9c19-0a7fd4584ad5.gif)

**Comment by joaomoreno** [comment]
@isidorn I also noticed this. We also seem to have lost in space and time the background color for an item which is both selected and focused!

**Comment by bpasero** [comment]
🤙

**Comment by isidorn** [comment]
@joaomoreno The color issue is tracked here https://github.com/Microsoft/vscode/issues/66612
