### ISSUE TITLE
New Explorer: indentation at root has changed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66580]
Refs: https://github.com/Microsoft/vscode/issues/66485

It looks like the new explorer is no longer nicely aligned with the title:

![image](https://user-images.githubusercontent.com/900690/51237272-656c2e00-1974-11e9-8e36-f8a8ef89582c.png)

![image](https://user-images.githubusercontent.com/900690/51237282-6bfaa580-1974-11e9-8ee8-422df023b370.png)

**Comment by isidorn** [comment]
The indent has changed and became more compact. I personally do not mind this.
While it would be cool to use less space between twistie and element as before.
@joaomoreno I think all the trees should be the same and this shuold not be configurable.

**Comment by bpasero** [comment]
At least visually I would align the tree with the label of the view as before. Not sure about indentation within the tree. A more compact form seems better to me.

**Comment by shreeve** [comment]
@bpasero - The more compact indentation level (10px per level) makes it hard to see the nesting.

<img width="928" alt="abstracttree ts vscode-official 2019-01-16 02-38-40" src="https://user-images.githubusercontent.com/142875/51240154-5c5d6b80-1938-11e9-9e3f-ed7da1675d12.png">

How hard would it be to make this a user configuration setting? It's currently just a hard coded value of `10` in the code. Could you make it something like `explorer.indentPixels` or something like that?

<img width="796" alt="abstracttree ts vscode-official 2019-01-16 02-43-14" src="https://user-images.githubusercontent.com/142875/51240328-b100e680-1938-11e9-959e-f20317c80cd8.png">

**Comment by joaomoreno** [comment]
The new indentation was an arbitrary value set by me. I will get it the same as the old tree.

@shreeve makes a good point, so @isidorn please create a separate issue for that if you agree.

**Comment by isidorn** [comment]
@joaomoreno yeah I agree. Though should this for every tree or only for explorer?
I think for every tree. So we should call it something like `tree.indentPixels`

**Comment by shreeve** [comment]
Sounds great! Making it user-configurable via the setting makes this really
nice.

—
