### ISSUE TITLE
Find in Files: Let's be more explicit about what files are searched

### ISSUE THREAD

**Issue by jtheisen** [Microsoft/vscode#66588]
I just spent 15 minutes to figure out why the search glossed over a file. (That's after the 15 minutes that it took me to figure out that it was glossing over a file.)

There's already a tip that says:

![image](https://user-images.githubusercontent.com/1516294/51238092-51c1c700-1976-11e9-9e84-92967268bb6f.png)

Great, but I didn't consider that "ingore files" could mean `.gitignore`, especially since the button there just gets me to vscode-specific settings, as if those are all I need to check.

A slight rephrasing would probably be enough here, such as inserting "also any version control" before "ignore files" (those are all ignore files there are, right?).

I've also noticed that opened files are searched even if excluded by an ignore file, so the whole logic seems to be even more complex. I think when it comes to Search in Files, it's very important that the set of files being searched over is very clear to the user.

(Having a button in Search in Files that overrides all exclusions and searches everything in the whole opened directory would also be a plus, but I think it's not nearly as important.)

**Comment by roblourens** [comment]
> Having a button in Search in Files that overrides all exclusions and searches everything in the whole opened directory would also be a plus

This exists, it's the button in the "files to exclude" box

**Comment by roblourens** [comment]
I've rephrased this and made it gitignore specific since that's technically the only version control file type we check right now. `.ignore` files are also checked but I don't think many people are using those.
