### ISSUE TITLE
New Explorer: rename not selecting file in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66585]
Refs: #66485

If I right-click "Rename" on a file ".vscodeignore", the file name is not fully selected as it used to be:

![image](https://user-images.githubusercontent.com/900690/51238430-33100000-1977-11e9-980e-160dca4eb580.png)

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode insiders
Do you still see it?

![screenshot 2019-01-16 at 11 14 25](https://user-images.githubusercontent.com/1926584/51242311-eed52d80-197f-11e9-8bd5-5af3204da71d.png)

**Comment by bpasero** [comment]
@isidorn I was using todays insider on Windows.

**Comment by isidorn** [comment]
I can not reproduce also on windows with latest insiders
![screenshot 2019-01-16 at 18 02 51](https://user-images.githubusercontent.com/1926584/51265383-f6fd8f00-19b8-11e9-8d08-4d7a90378e69.png)

Check if you are always seeing it. And if yes put a breakpoint here and check what is wrong with the `lastDot` computation
https://github.com/Microsoft/vscode/blob/5b443958a108be72b50dd61bae6e13eb101360d5/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L202

**Comment by bpasero** [comment]
I cannot reproduce on my Windows laptop, so closing.
