### ISSUE TITLE
New Explorer: ARIA level is not right?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66584]
Refs: https://github.com/Microsoft/vscode/issues/66485

Running the new explorer tree with NVDIA I think the level is no longer reported correctly, it is always "level 1":

![image](https://user-images.githubusercontent.com/900690/51238199-ab29f600-1976-11e9-908e-d097524ac31e.png)

**Comment by shreeve** [comment]
#66580 is following this

**Comment by isidorn** [comment]
This is true for every tree. 
@joaomoreno we should add `aria-level` to every `.monaco-list-row`
Would you like me to look into this?

**Comment by joaomoreno** [comment]
@isidorn Please!

**Comment by isidorn** [comment]
@joaomoreno ok so the list sets aria attributes here https://github.com/Microsoft/vscode/blob/e027751b0873004b74f09949623b794e13053647/src/vs/base/browser/ui/list/listView.ts#L490

And the only place where I found that the tree touches HTML is here for the twisite https://github.com/Microsoft/vscode/blob/e027751b0873004b74f09949623b794e13053647/src/vs/base/browser/ui/tree/abstractTree.ts#L202

However there I do not have acces to the monaco-list-row. Only monaco-tl-row. So I could hack it in and add the aria attribute on the container.parent.

The alternative is to pass some opaque information to the list from the tree, so the list would add it where it sets other aria attributes. This  seems like the most reasonable thing to me. Let me know what you think.

**Comment by joaomoreno** [comment]
@isidorn While looking into it, just ended up implementing it. I verified that the `aria-level` now is set in the DOM. I did not verify that the screenreader actually reads correctly. Leaving that to our champion. 💪

**Comment by isidorn** [comment]
Works great. Just verified with win build. Closing and adding verified
