### ISSUE TITLE
Missing dependency for .deb

### ISSUE THREAD

**Issue by KocsisV** [Microsoft/vscode#66599]
I started a new VM in the Azure cloud and installed the "default" ubuntu 18.04 LTS image.
Then downloaded and installed the .deb package of VS Code. It installed almost all the dependencies, but "libasound2" was missing. I had to install that manually.
Please include that package as a dependency too.

VS Code version:
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-1036-azure

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/13089
