### ISSUE TITLE
High CPU while typing

### ISSUE THREAD

**Issue by Manne990** [Microsoft/vscode#66592]
Issue Type: <b>Bug</b>

While typing code in my Android project visual studio maxes the CPU and everything is slow and hangs for periods of time.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|24.00GB (3.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
json-tools|eri|1.0.2
csharp|ms-|1.17.1

</details>

**Comment by Manne990** [comment]
[Visual Studio_Profile_2019-01-16__10-57-22.txt](https://github.com/Microsoft/vscode/files/2763575/Visual.Studio_Profile_2019-01-16__10-57-22.txt)

**Comment by sandy081** [comment]
@Manne990 Did you see the same when you disable all extensions?
