### ISSUE TITLE
Switch terminal group

### ISSUE THREAD

**Issue by modestotech** [Microsoft/vscode#66591]
Issue Type: <b>Feature Request</b>

I have mapped keybindings to change between terminal tabs in the same group (I don't know the terminology). 

So switching between there works. 
![image](https://user-images.githubusercontent.com/31730051/51240006-1f669880-197b-11e9-9ae5-4f8ad6dd21fb.png)

When I use npm scripts, a new group (2) is started, and then I haven't found any keyboard shortcut to cycle through the groups (to come back to 1). 
![image](https://user-images.githubusercontent.com/31730051/51240055-36a58600-197b-11e9-9867-74b4ac9b6b2d.png)

Is there any command that can be mapped for this?

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

**Comment by usernamehw** [comment]
`workbench.action.terminal.focusNext`
`workbench.action.terminal.focusPrevious`
