### ISSUE TITLE
Dock icon on macOS appears very small

### ISSUE THREAD

**Issue by yinLiangDream** [Microsoft/vscode#66594]
- VSCode Version:1.30.2
- OS Version:MAC OS 10.14.2

Steps to Reproduce:
why???
![image](https://user-images.githubusercontent.com/24502330/51241764-78552180-19b9-11e9-9021-9fe8f2bc5f18.png)
![image](https://user-images.githubusercontent.com/24502330/51241838-9de22b00-19b9-11e9-956a-134aa2b04469.png)
1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@joaomoreno ever seen this?

**Comment by krupenja** [comment]
Something similar was reported before in #59578. Related [AskDifferent question](https://apple.stackexchange.com/questions/338881/there-is-a-tiny-icon-on-macos-dock-that-is-not-clickable) has 13 upvotes so does not like an isolated issue.

**Comment by Robotex** [comment]
Also reported in #63068
