### ISSUE TITLE
Open with Code on drive open as file not folder

### ISSUE THREAD

**Issue by acoshift** [Microsoft/vscode#666]
Open with Code from windows explorer open drive as file (example open "D:\" without folder)

![0019](https://cloud.githubusercontent.com/assets/6111610/11410461/24a11456-93fa-11e5-824e-374a31cb2fed.PNG)

**Comment by bpasero** [comment]
I cannot reproduce from the command line (tried "code C:" and "code C:\") so I wonder if this is something with the context menu entry we provide ("Open with Code").

@acoshift I do not even have a "Open with Code" in the context menu of a root drive. How did you trigger it?

**Comment by joaomoreno** [comment]
@bpasero It's an option in the installer.

**Comment by acoshift** [comment]
I think windows explorer open code with

```
code "C:\"
```
which can produce bug but

```
code "C:\\"
```
is not.

**Comment by joaomoreno** [comment]
@bpasero I could still repro this:

![image](https://cloud.githubusercontent.com/assets/22350/16587920/1f837090-42cd-11e6-8f1f-b388fb591fdc.png)

**Comment by bpasero** [comment]
@joaomoreno show me

**Comment by bpasero** [comment]
Should be ok now as long as "C:\" is passed in with trailing backslash.
