### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by VasRaz** [microsoft/vscode#66604]
Issue Type: <b>Bug</b>

Since we backed up our VSTS by an AAD instead of Microsoft Live accounts, I can not sign in in VS Code to sync with one of our Git repositories. Choosing the professional account login option, after placing in the credencials, the sign in popup just reapears waiting again for the credencials. No message is shown.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.26
rainbow-csv|mec|0.8.0
PowerShell|ms-|1.10.2

</details>

**Comment by joaomoreno** [comment]
VS Code doesn't have a sign in. Is this specific to an extension?

**Comment by VasRaz** [comment]
Yes, it´s related with Git. It happens when I try to sync any Git repository. The login popup keeps showing up even if the credentials I put in are the correct ones.

________________________________
De: João Moreno <notifications@github.com>
Enviado: viernes, 18 de enero de 2019 8:58:22
Para: Microsoft/vscode
Cc: Vasile Razvan Cojocaru; Author
Asunto: Re: [Microsoft/vscode] Can't sign in (#66604)


VS Code doesn't have a sign in. Is this specific to an extension?

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that login popup?

**Comment by VasRaz** [comment]
I would but the problem is that today I am out of my office. I will reply Monday morning with more detailed information. Thank you very much and have a nice weekend!

________________________________
De: João Moreno <notifications@github.com>
Enviado: viernes, 18 de enero de 2019 9:14:30
Para: Microsoft/vscode
Cc: Vasile Razvan Cojocaru; Author
Asunto: Re: [Microsoft/vscode] Can't sign in (#66604)


Can you show me a screenshot of that login popup?

**Comment by TylerLeonhardt** [comment]
@VasRaz - are you still having an issue here?
