### ISSUE TITLE
Allow extensions to set colours in completion items outside of label/description

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#66606]
There's a `CompletionItemKind.Color` but as far as I can tell from the source, it'll only work if the label or documentation matches a specific regex that's hard-coded:

https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L160

<img width="449" alt="screenshot 2019-01-16 at 2 43 33 pm" src="https://user-images.githubusercontent.com/1078012/51256425-4a61e400-199d-11e9-8917-30f9e3d77487.png">

It would be much better if an extension can supply this value in another field that doesn't require that it replaces the entire `label` or `description` with just the hex value.

**Comment by jrieken** [comment]
> It would be much better if an extension can supply this value in another field that doesn't require that it replaces

Why? Do you have a sample? I aren't very keen on adding an API just for that but we wanna be pragmatic here.

**Comment by DanTup** [comment]
Well normally you can provide a description in code completion like this:

<img width="796" alt="screenshot 2019-01-17 at 10 10 28 am" src="https://user-images.githubusercontent.com/1078012/51311157-302d1200-1a40-11e9-9e42-7e65faf9f047.png">

It seems weird to say that if you want to preview the colour in completion we have to stop showing the textual description.

**Comment by jrieken** [comment]
/cc @aeschli for input and as the original implementation. 

Still in favour of something pragmatic, e.g find the color-string as substring

**Comment by DanTup** [comment]
@jrieken if a new field won't be added, could this at least be a sub-string, so we could tag `(#ff0000)` or `\n#ff000` on to the end? It'd a shame to have to remove the descriptions just to get colour previews.

**Comment by DanTup** [comment]
@jrieken @aeschli would you accept a PR for something here? I'd really like to include colors in my completion, but losing the ability to have any other documentation isn't a great trade-off. A substring would be fine for me.. it looks like the current code might support the value being right at the end, however I think it only works for raw strings and not any sort of markdown?

https://github.com/microsoft/vscode/blob/391acf814912c636ca259030e26975df5ee683ed/src/vs/editor/contrib/suggest/browser/suggestWidgetRenderer.ts#L49

**Comment by Number-3434** [comment]
Yeah, this would actually be very useful, but I don't think this issue gets enough traffic.

I think that most people would find this useful, but this issue is quite obscure, so it doesn't get enough attention.

Maybe 2024 is a good time to reconsider this?

**Comment by Number-3434** [comment]
Okay, thanks 🙏!

Could you consider reopening this issue?
