### ISSUE TITLE
Invalid "Report an Issue" Link

### ISSUE THREAD

**Issue by OcasoProtal** [Microsoft/vscode#66603]
- VSCode Version: Does not apply
- OS Version: Does not apply

Steps to Reproduce:

1. Open an invalid link in any browser to code.visualstudio.com, e.g. https://code.visualstudio.com/invalid
2. Check the _report an issue_ link, it points to the wrong URL https://www.github.com.com/Microsoft/vscode/issues instead of https://www.github.com/Microsoft/vscode/issues

Does this issue occur when all extensions are disabled?: Yes /Does not apply

**Comment by octref** [comment]
Thanks, fixed internally, will publish soon.

**Comment by gregvanl** [comment]
@octref Shouldn't this link go to vscode-docs/issues instead of vscode/issues.

**Comment by octref** [comment]
@gregvanl Either is fine. Feel free to move it.
