### ISSUE TITLE
Add visual guide for maximum line-length

### ISSUE THREAD

**Issue by astier** [Microsoft/vscode#66602]
I visual guide-line for a desired line-length would be very handy to stay consistent with a defined maximum line-length. Something what you can see on the right side of the screenshot.
![guideline](https://user-images.githubusercontent.com/36510152/51250011-76796700-1995-11e9-8fe6-afb1e783ba98.png)

**Comment by usernamehw** [comment]
```json
"editor.rulers": [80, 100],
```

**Comment by astier** [comment]
Awesome! Thanks.
