### ISSUE TITLE
Select Language Mode -> REMEMBER based on folder path

### ISSUE THREAD

**Issue by pratikgadhiya** [Microsoft/vscode#66609]
autodetect of language mode works fine.

let say i have html view as .php extension. but i want to parse it as HTML always even if it has .php extension.

so, all my views should parse as html and rest controller and models as php as default.

basically please add path based feature. Thanks.

**Comment by usernamehw** [comment]
Have you tried `"files.associations"` ?

**Comment by pratikgadhiya** [comment]
not yet. just searched for it. it seems it has solution thanx.
