### ISSUE TITLE
Support custom tree indentation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66605]
More details https://github.com/Microsoft/vscode/issues/66580#issuecomment-454716304

**Comment by joaomoreno** [comment]
Actually, let's do the tree work here.

**Comment by joaomoreno** [comment]
@isidorn Added a new `indent` tree option. Also added a `updateOptions` method which will let you dynamically update that `indent` option at runtime.

**Comment by UmanShahzad** [comment]
Thank you!

**Comment by isidorn** [comment]
Adding verfiication need and verified - since I tried it out and works nicely.
Also there is another feature reuqest which will verify this #35447
