### ISSUE TITLE
wordwrap doesn't work

### ISSUE THREAD

**Issue by luishk807** [Microsoft/vscode#66610]
Issue Type: <b>Bug</b>

Hi, i tried all method on google and the text still doesn't wrap.

i'm using a lenovo ultrabook thinkpad T460s laptop windows 10 with two HP monitor, one in portrait mode and the other in landscape mode.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.87GB (12.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by luishk807** [comment]
i already tried to re-install and still doens't work

**Comment by learning** [comment]
It works on macOS 10.14.2, Code 1.30.2 and 1.31.0, maybe it's a bug for windows only?
![image](https://user-images.githubusercontent.com/354626/51311386-c3d40200-1a83-11e9-9ab0-d635230a62a6.png)

**Comment by learning** [comment]
Windows 10 1803 is okay,
![image](https://user-images.githubusercontent.com/354626/51325178-4d48fb80-1aa7-11e9-9da2-fef462869d32.png)

Try `code --disable-extensions` ?

**Comment by luishk807** [comment]
i tried code --disable-extensions and i still can't wordwrap, 

is there any command to clear the vs configuration? i don't even extensions added
![image](https://user-images.githubusercontent.com/1082133/51550888-59ccab80-1e3b-11e9-9deb-1335ca4c8f19.png)

**Comment by luishk807** [comment]
![image](https://user-images.githubusercontent.com/1082133/51550996-8d0f3a80-1e3b-11e9-8778-e8a5acaf22c8.png)

**Comment by alexandrudima** [comment]
@luishk807 Have you tried Alt+Z? Do you perhaps have a workspace setting that is overwriting your user setting for word wrap?

**Comment by luishk807** [comment]
> @luishk807 Have you tried Alt+Z? Do you perhaps have a workspace setting that is overwriting your user setting for word wrap?

that's the first thing i tried, still doesn't work.  what workspace?
