### ISSUE TITLE
VSCode appears to have custom window decorations

### ISSUE THREAD

**Issue by duane** [Microsoft/vscode#66619]
- VSCode Version: 1.30.1
- OS Version: 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Download vscode on linux.
2. Open vscode.
3. Observe that it styles its own window, including its own min/max/close buttons and a menu into the title bar.

How can I disable this behavior and use the window styling the window manager provides?

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
```json
"window.titleBarStyle": "native",
```
