### ISSUE TITLE
Unexpected behavior: `Add Selection To Next Find Match (Ctrl+D)` 

### ISSUE THREAD

**Issue by noppe18** [Microsoft/vscode#6661]
- VSCode Version:1.1
- OS Version: Windows7 Pro. SP1

Steps to Reproduce:
1. select "abc"
   ![iamge1](https://cloud.githubusercontent.com/assets/674208/15466146/172e6fde-2113-11e6-8750-7b68defcd6af.png)
2. press "Ctrl+D" 2 times. this is unexpected behavior.
   ![iamge2](https://cloud.githubusercontent.com/assets/674208/15466178/2d6f45b6-2113-11e6-98d4-f53d55981361.png)

I expected below image.
![image3](https://cloud.githubusercontent.com/assets/674208/15466190/39b1da78-2113-11e6-89ca-e48643069241.png)

**Comment by ElChupacabra26** [comment]
Can confirm this also happens on El Capitán running the latest version of VSCode (1.5.3)

**Comment by unional** [comment]
Another scenario:

```ts
const a = "a";
const b = "b";
const empty = "";
const d = "d";
```
Selecting `"` and [Ctrl+D] would stop at `empty = ""` as the selection is expanded to `""` at that position.

**Comment by zhoudotnet** [comment]
When do you fixed this issue & release to production?
