### ISSUE TITLE
Put snippets at the bottom of suggestions until typing

### ISSUE THREAD

**Issue by johnknoop** [Microsoft/vscode#66621]
Today I can choose to have snippets either at the top or at the bottom of the suggestions list. In order to have them quickly accessible, you need to have the `editor.snippetSuggestions` setting to `top`. Here is an example using the `if` snippet. Image if I didn't have the setting value `top`, then the if-snippet wouldn't be the highlighted item, resulting in a very slow workflow:

![image](https://user-images.githubusercontent.com/3394270/51276049-ec9cbe80-19d3-11e9-85d4-7c6ecb65d800.png)

However, when I hit ctrl+space to see suggestions for what I am allowed to do in a given context, then it's just annoying that the snippets are shown first in the list. In this example, the suggested items with blue icons are what I'm after:

![snippets](https://user-images.githubusercontent.com/3394270/51276293-9a0fd200-19d4-11e9-8044-a1807eae6034.gif)

Feature request: hide the snippets from the list of suggestions unless you've started typing. Or at least add a new option to the `editor.snippetSuggestions` called `topWhenPrefixMatches` or something.

This issue addresses the problem, but proposes a different solution that I don't really agree with:
https://github.com/Microsoft/vscode/issues/62236

**Comment by jrieken** [comment]
So, the default is to re-sort items based on how well they match as soon as you start typing. That's why the default is 'inline'. With that, the prefix `if` will sort the snippet `if` atop because it matches best, but it would not sort snippets atop or to the bottom without prefixes

**Comment by johnknoop** [comment]
@jrieken No, it will not put the if-snippet on top unless you've checked the setting "show snippets first". That's why I've ticked that setting, because when I type "if", I always want the snippet, not that other thing that also matches "if". So the problem is that now I always get snippets on top, even in situations where I haven't typed anything. Get the problem?

**Comment by jrieken** [comment]
> Which is useless for situations where you're looking to execute a snippet.

Well, I'd say that true for *all* duplicated suggestions. Sometimes there are duplicates and tbh you best wait for #45039 which is about filtering certain types of suggestions, e.g. `keywords`, e.g. `if`. Saying "No snippets in suggestions unless typing selects one" is rather special and won't help in the already complicated IntelliSense world. If you want that one snippet, you can always F1>Insert Snippet, enable tab completion, or bind a keybinding to that one snippet.

**Comment by johnknoop** [comment]
#45039 wont solve my problem at all. I'm looking for a far simpler solution:

There are two events that can trigger the suggestions list to show:

a: typing something
b: pressing ctrl+space

For scenario a, it works fine right now. For scenario b, the user is clearly not looking for a snippet, so dont show them until she has typed in a letter.

I speak for at least ten other guys at our office who use VS Code when I say that this would be a huge improvement.

**Comment by usernamehw** [comment]
If you're desperate you can try to temporarily set config before invoking the suggest.

You'll need 2 extensions for that: one to set settings and another to run multiple commands. And `when` context `!suggestWidgetVisible`.

Macro would be:
1. Set `editor.snippetSuggestions` to `bottom`
1. Invoke suggest (only when `!suggestWidgetVisible`)
1. Set `editor.snippetSuggestions` to whatever it was before

**Comment by dbsxdbsx** [comment]
currently with version 1.53.  When setting  `editor.snippetSuggestions` to `top`, snippet is still showing on th bottom.
