### ISSUE TITLE
Function references lookup fails with strange message

### ISSUE THREAD

**Issue by Zephilim** [Microsoft/vscode#66627]
Issue Type: <b>Bug</b>

- Find a function in source code
- click on "references" above the function definition
- see error messages pop up. The pane that usually pops up inside the editor window does not appear showing the function call sites
(Please see attached picture)
![mscode-find-references-failure](https://user-images.githubusercontent.com/2083615/51279223-aeec6580-19d4-11e9-9d24-c37b652cf901.jpg)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.10.2
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0

</details>

**Comment by sandy081** [comment]
Looks to me these references are coming from an extension, please file an issue against it. Thanks.
