### ISSUE TITLE
Formatting json file/content

### ISSUE THREAD

**Issue by PratikTheGameDever** [Microsoft/vscode#66629]
I had a 700+ characters long json in a json file in a single line.

I had my cursor and focus both at the end of the line.

When I pressed Alt+Shift+F it formatted the content fine but the the focus stayed at the same place, even when the reformatted content takes up only 25 characters in a line.

**Comment by jrieken** [comment]
@PratikTheGameDever What version of VS Code are you using?

**Comment by PratikTheGameDever** [comment]
I am using 1.25.0

**Comment by jrieken** [comment]
Please update to a recent version because this issue is fixed there
