### ISSUE TITLE
Test stable peek and peek resize

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6662]
tests #5120

* [x] any os - **@kieferrm**
* [x] OS X - **@joaomoreno**

The peek window go improved for _code in the peek window_-scenarios. Test that

* you can resize peek windows, for _find references_ and _peek definition_ in height and when the tree shows also vertically
* the size adjustments are persisted
* there is a new setting `stablePeek` which  when enabled doesn't close the peek window on Esc or when double clicking the content
* let me know if don't like the name of the setting `stablePeek`

**Comment by joaomoreno** [comment]
Wow!

**Comment by joaomoreno** [comment]
Not super comfortable with the setting name, but I lack a better suggestion.

**Comment by weinand** [comment]
@kieferrm please close item after setting last checkbox.
