### ISSUE TITLE
Connecting to Office 365 PowerShell commands spawns Window that is not on first plan

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Microsoft/vscode#66624]
- VSCode Version: 1.30.2
- OS Version: Windows 10 1809

Steps to Reproduce:

1. `Install-Module AzureAD`
2. Type in `Connect-AzureAD` in PowerShell window
3. Nothing is shown
4. Minimize VSCode -  Office 365 prompt is there

In standard PowerShell window, outside of VSCode, the prompt is shown to the user as a browser window, on top of other windows. 

It would be great if that Window would be brought to TOP.

**Comment by sandy081** [comment]
Is the dialog triggered from VS Code? If so from where?

**Comment by PrzemyslawKlys** [comment]
It's either triggered from .ps1 script via F5 and PowerShell extension or from `Terminal`

![image](https://user-images.githubusercontent.com/15063294/51327232-27a0ff80-1a71-11e9-92f1-f1e083480d54.png)

If you press enter PowerShell appears that it's doing something but nothing happens and it's stuck like that for minutes, but if you minimize VSCode you will see this:

![image](https://user-images.githubusercontent.com/15063294/51327299-5028f980-1a71-11e9-9f17-7952f7b333f2.png)

It's very counter-productive and hard to even know that it's there.

**Comment by Tyriar** [comment]
I think we've already had reports about this dialog appearing behind VS Code but can't find the issue. @chrmarti I think you might have created the issue before, do you know?
