### ISSUE TITLE
Snippets cannot be called within Snippets

### ISSUE THREAD

**Issue by Tomcariello** [Microsoft/vscode#66622]
Issue Type: <b>Bug</b>

Create a user defined snippet:
```
    "flip-flop ": {
        "scope": "plaintext",
        "prefix": "flipflop",
        "body": [
            "flip: first $1 then $2",
            "flop: $2 then $1",
        ],
        "description": "Writes words in opposite order"
    }
```

In VSC versions prior to 12.5.1 you could call a snippet within a snippet. So, after triggering a snippet, while entering data at the $1 point you could write "flipflop" and it would trigger the Intellisense & the flipflop snippet again. This worked for the same snippet or different snippets. 

In version 1.30.2 you can no longer call a snippet within a snippet. Intellisense does not prompt the snippet option at the $1 point.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.89GB (7.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
increment-selection|alb|0.0.3
mssql|ms-|1.4.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
html5-boilerplate|sid|1.0.3

</details>

**Comment by jrieken** [comment]
We added a new setting (`"editor.suggest.snippetsPreventQuickSuggestions": true,`) because most people where deeply irritated by that behaviour. Since a few months, the default is that intellisense-as-you-type is disabled when snippet mode is active and that you have to invoke IntelliSense manually. The aforementioned setting re-enables that.
