### ISSUE TITLE
show preview window on search result

### ISSUE THREAD

**Issue by bennylee123** [Microsoft/vscode#66631]
Issue Type: <b>Feature Request</b>

1. Launch VSCode
2. search for some text and wait until the results are displayed.

Feature request:
As I hover over the search result, it would display a preview window and show the previous and next 5 lines of code around the search result.

This would allow me to quickly view the result w/o the need to open everyone of the result to see if that is what I am looking for.

Thanks.

VS Code version: Code - Insiders 1.31.0-insider (d3024ec0c4eb830eb22a39bc2f2feacd314a952a, 2019-01-16T07:58:52.560Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
Interesting idea, but I just expect people to use the editor to browse the actual code. The search view is not the best place to view code.
