### ISSUE TITLE
Equal text highlighting over multiple rows (like Sublime)

### ISSUE THREAD

**Issue by juristr** [Microsoft/vscode#6663]
- VSCode Version: 1.1.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open this file in VSCode: https://gist.github.com/juristr/0a3a294ce70660f59ba4265f86699fda
2. Select a multi-line code block that from the `activateBaseMap(..)` function that has an identical occurrence in the `onChange(...)` function, like.

   ```javascript
   if (basemap !== vm.emptyBaseMap) {
      vm.emptyBaseMap.olNode.visible = false;
   }
   ```
3. Press `Ctrl+D` (or `Cmd+D`) to enter multi-cursor mode. Actually also just highlighting the line should out-of the box highlight the same multi-line code block in other parts of the file as well.

**Outcome:**

![multiline-vscode](https://cloud.githubusercontent.com/assets/542458/15469884/73b1ff30-20ed-11e6-8d38-19978fa5f38d.gif)

**Expected:**

This is how Sublime does it on the same JavaScript file.
![multiline-sublime](https://cloud.githubusercontent.com/assets/542458/15469932/9e321d76-20ed-11e6-845d-4250dece1cde.gif)

**Comment by alexandrudima** [comment]
Blocked by #313

**Comment by alexandrudima** [comment]
Given #6561, let's track the request there

**Comment by juristr** [comment]
:+1:
