### ISSUE TITLE
Terminal link underlines on lines that start with \t are offset

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#66632]
Issue Type: <b>Bug</b>

I've started noticing the line under the hyperlink looks weird on insiders:
![screen shot 2019-01-16 at 2 45 38 pm](https://user-images.githubusercontent.com/11282622/51283573-81d09080-199d-11e9-9937-c307148156e5.png)

This is what it looks like on non-insiders:
![screen shot 2019-01-16 at 2 46 05 pm](https://user-images.githubusercontent.com/11282622/51283576-84cb8100-199d-11e9-86fe-325820c927c9.png)

I think I narrowed it down to when there's a tab and a link. Here's the simplest task I could create that repros this:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "test",
      "type": "shell",
      "command": "echo '	http://localhost:7071/api/HttpTrigger'",
      "problemMatcher": []
    }
  ]
}
```

VS Code version: Code - Insiders 1.31.0-insider (b4fc71b972eae2425d39ac4041df0c36cfa1bb37, 2019-01-15T06:12:40.322Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
python|ms-|2018.12.1
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
java|red|0.36.0
vscode-java-debug|vsc|0.16.0

</details>

**Comment by Tyriar** [comment]
Upstream PR: https://github.com/xtermjs/xterm.js/pull/1887, too late to pull into 1.31

**Comment by EricJizbaMSFT** [comment]
Fixed for me on latest insiders - thanks!
