### ISSUE TITLE
New launch.json file and .vscode folder not showing in file tree

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#66630]
Issue Type: <b>Bug</b>

1. Create a new Angular application (or open one that does not have a launch.json file)
2.  In the "Debug" panel, click the gear icon to create a new launch.json file.

The launch.json file and it's .vscode folder do not appear in the file tree. Only after reloading the window does the folder and file appear.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/13488/51282492-3c1ec280-19b3-11e9-890b-f272ae1f7b4a.png">

VS Code version: Code - Insiders 1.31.0-insider (d3024ec0c4eb830eb22a39bc2f2feacd314a952a, 2019-01-16T07:51:38.794Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|-psn_0_12573693|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
githistory|don|0.4.4
auto-rename-tag|for|0.0.15
Angular2|joh|7.0.1
csharp|ms-|1.18.0-beta4
vscode-typescript-tslint-plugin|ms-|0.3.0
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.2
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.2

(3 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@alexr00 here's your issue
@jtsom thanks for reporting and for using vscode insiders

**Comment by isidorn** [comment]
fyi @egamma
