### ISSUE TITLE
Allow moving the activity bar to other window edges.

### ISSUE THREAD

**Issue by cjmaria** [Microsoft/vscode#66639]
When working in split-screen view with vscode on the right of the display, the activity bar creates an unpleasant gap between windows. Also, it takes up a lot of space, particularly on non-widescreen displays. If one still wanted to use the activity bar while not interfering with the horizontal screen real estate, the only option is to hide and unhide it repeatedly–which in itself is difficult considering the lack of a keyboard shortcut.
I imagine the greatest challenge to this would be allowing the bar to be placed on the top and bottom of the window, since the panel displayed on click would need to be optimized for a horizontal frame.

**Comment by yume-chan** [comment]
You can move it to right side by setting `"workbench.sideBar.location": "right"`. However all vscode instances share settings and if you want two vscode on both your screen, it's still a problem.

**Comment by sandy081** [comment]
you can move it to right and you can also associate a keybinding for toggling the visibility of side bar from keybindings editor.
