### ISSUE TITLE
Hover lost border which makes it very hard to distinguish from normal text

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6664]
- VSCode Version: alpha
- OS Version: Windows 10

See attached screen shot. I was hovering modesId. The hover looks like a normal text editor line.

![capture](https://cloud.githubusercontent.com/assets/1931590/15470975/e6833384-20f3-11e6-9a58-6290f1961d53.png)

**Comment by dbaeumer** [comment]
@jrieken I actually not sure who is responsible. Starting with you :-)

**Comment by jrieken** [comment]
no clue how made changes here...
