### ISSUE TITLE
Terminal side dock option missing

### ISSUE THREAD

**Issue by kushalmahajan** [Microsoft/vscode#66647]
In release 1.3.0 there is no option to side dock the terminal. That icon to dock itself is missing. What happened? Is this removed intentionally?

**Comment by usernamehw** [comment]
/question

https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu

**Comment by kushalmahajan** [comment]
Well, yes. It's really not figurable even on right click. One has to move to panel header to right click and see an option. Earlier it was available as icon upfront. Your choice and thanks for help @usernamehw
