### ISSUE TITLE
vscoded performance issue debugging

### ISSUE THREAD

**Issue by prabhurangan** [Microsoft/vscode#66645]
Issue Type: <b>Bug</b>

vscode is very slow performing, especially during debugging and could not perform any operation

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
jshint|dba|0.10.20
vscode-eslint|dba|1.8.0
beautify|Hoo|1.4.7
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
autoimport|ste|1.5.3
code-navigation|vik|0.2.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by prabhurangan** [comment]
![image](https://user-images.githubusercontent.com/16012151/51295684-a47a9d80-19cd-11e9-8c78-57edfe6b7aa2.png)

**Comment by prabhurangan** [comment]
<img width="861" alt="screen shot 2019-01-16 at 8 32 21 pm" src="https://user-images.githubusercontent.com/16012151/51295771-09ce8e80-19ce-11e9-82b4-791d59fe42b2.png">

**Comment by sandy081** [comment]
Can you please follow this [wiki](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and provide necessary information?
