### ISSUE TITLE
Add a setting to show the close button on a tab when sizing is set to shrink

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#66642]
Close button is not visible having default dark theme selected when `"workbench.editor.tabSizing": "shrink"`.

#### VSCode Version:
![grafik](https://user-images.githubusercontent.com/9283914/51293134-ba0fb780-1a0d-11e9-8b2b-1fbf92322066.png)

#### Steps to Reproduce:

1. Set VS Code setting: `"workbench.editor.tabSizing": "shrink"`.
2. Select default VS Code dark color scheme.
3. Open an editor in VS Code.

![vs code tab only](https://user-images.githubusercontent.com/9283914/51293238-40c49480-1a0e-11e9-9660-4b469988940e.png)

#### Does this issue occur when all extensions are disabled?
- [x] Yes
- [ ] No

#### This issue has already been reported in #59063 but hasn't been fixed yet.

**Comment by learning** [comment]
@SetTrend When your mouse move over on it, is it shows up?
![image](https://user-images.githubusercontent.com/354626/51294305-4f7e6c00-1a4d-11e9-964e-09becb087f38.png)

**Comment by bpasero** [comment]
Does it?

**Comment by SetTrend** [comment]
Yes, it does.

**Comment by SetTrend** [comment]
What sense does it make to hide information and only reveal it on on-hover?

**Comment by bpasero** [comment]
@SetTrend that is how the feature works, but we can reopen this as feature request.

**Comment by SetTrend** [comment]
Thanks, a bunch, Benjamin.

Actually, the reasoning behind that is that it's not consistent with all other GUI, and even the VS Code title bar itself:
![controls not hiding](https://user-images.githubusercontent.com/9283914/51330372-abf68100-1a77-11e9-98e3-a102297948b5.png)

The current behaviour is irritating. Plus, it's an accessibility issue.

Thanks again, for keeping this open as a feature request.

**Comment by SetTrend** [comment]
There are several issues dealing with the fact that auto hiding visual cues is not helpful:

#37714
#66000
#53942

A setting has already been introduced, `"scm.alwaysShowActions": true`, dealing with one of them.

Wouldn't it make sense to, instead of introducing different settings for each single facet of the same accessibility issue, introduce one single setting, dealing with not hiding visual cues in VS Code in general (I'd suggest to name it `"workbench.autoHideVisualCues": false`) to which all visual cues then adhere (i.e. VS Code intrinsic controls and extensions' controls)? (This suggestion explicitly _excludes_ editor _content_ specific hovers, like, for instance, JDoc comments or variable values while debugging.)
