### ISSUE TITLE
Allow to set background color of tab having focus

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#66640]
### It's utterly hard to distinguish the editor having focus from other panels in VS code.

It's always an annoying matter of Try And Error when switching between other software and VS Code (using <kbd>ALT</kbd>+<kbd>TAB</kbd>) and starting to type.

I examined all VS Code color themes that are included with Visual Studio Code, and they all share the same issue:

![vs code tab only](https://user-images.githubusercontent.com/9283914/51292193-41f3c280-1a0a-11e9-95fd-db87338e3ab0.png)
![vs code tab only-blue](https://user-images.githubusercontent.com/9283914/51292577-92b7eb00-1a0b-11e9-8029-7ba925e563c6.png)
![vs code tab only-green](https://user-images.githubusercontent.com/9283914/51292580-951a4500-1a0b-11e9-9b6e-958db406b4df.png)
![vs code tab only-red](https://user-images.githubusercontent.com/9283914/51292581-96e40880-1a0b-11e9-944c-87d214b577b1.png)

In this example, it's very hard to tell which of the two editors has focus, the left or the right one.

I'm pretty sure y'all won't even recognize the right tab having a vertical squiggly line on the right.

So, I'd like to propose to highlight the editor having focus more vividly, e.g. using the status bar background color as background color for the editor having focus:

### Current Design

![vs code tab current](https://user-images.githubusercontent.com/9283914/51292380-c47c8200-1a0a-11e9-8edb-a6409e6989a0.png)

### Desired Design

![vs code tab desired](https://user-images.githubusercontent.com/9283914/51292388-c9413600-1a0a-11e9-856e-6886e5d914be.png)
<hr/>

#### Current Design
![vs code tab only](https://user-images.githubusercontent.com/9283914/51292193-41f3c280-1a0a-11e9-95fd-db87338e3ab0.png)

#### Desired Design
![vs code tab only-desired](https://user-images.githubusercontent.com/9283914/51292728-24bff380-1a0c-11e9-87f4-1df617bc2699.png)

**Comment by bpasero** [comment]
Can be configured via settings:

![image](https://user-images.githubusercontent.com/900690/51325856-2e7a4300-1a6e-11e9-81d4-32f612323845.png)

```
"workbench.colorCustomizations": {
    "tab.activeBackground": "#0000ff"
}
```

In the future, please post questions over at StackOverflow where we have a large community of VSCode users: https://stackoverflow.com/questions/tagged/visual-studio-code. Thanks!

**Comment by SetTrend** [comment]
@bpasero : I see your point, yet the line is not always clear what's a feature request and what's a question. Thanks.

**Comment by SetTrend** [comment]
@bpasero :

```json
"workbench.colorCustomizations": {
    "tab.activeBackground": "#0000ff"
}
```

Does _not_ set the color of the editor having _**focus**_.

Three tabs cannot have focus at the same time:

![tabactivebackground](https://user-images.githubusercontent.com/9283914/51352666-994b6e80-1aae-11e9-8f47-29f3aedaba8d.png)

**Comment by bpasero** [comment]
True, best you can do today is change the foreground color, which has different values for the tab being active, inactive, focused or not focused.
