### ISSUE TITLE
CSS shorthand tip displayed when not using shorthand

### ISSUE THREAD

**Issue by sjerp-indrukwekkend** [Microsoft/vscode#66649]
- VSCode Version: 1.30.2
- OS Version: Win10 17134

Steps to Reproduce:

1. Write CSS: padding-top: x or border-top: x
2. hover. 

A tip is displayed for shorthand declarations, but these are not shorthand declarations.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
This will be fixed as part of https://github.com/Microsoft/vscode/issues/58391.
