### ISSUE TITLE
Native Tabs: Same versios, same settings, different behaviour

### ISSUE THREAD

**Issue by BartOtten** [Microsoft/vscode#66658]
Issue Type: <b>Bug</b>

This behavior is different on my two laptops, with the same software versions, the same user settings and the same projects.

1. Use the attached user settings
2. Open a project in the editor
3. Click File -> New Window, Open Workspace or Open...

Mac 1: A new tab is created in the tab bar
Mac 2: A new window is opened and I have to use Window -> Merge all windows

Mac 1 does restore the tabs when I close VisualCode, Mac 2 re-opens many windows (even if they were merged). Might be related to #66354

----

VS Code version: Code - Insiders 1.31.0-insider (926cfe1c4ac6a438f8fa3c4f164219c7c4bf17b5, 2019-01-17T06:14:05.649Z)
OS version: Darwin x64 18.2.0

The extentions and config are identical copies (and it also happens with all ext disabled). The relevant part:

` 
    "window.nativeTabs": true,
    "files.hotExit": "onExitAndWindowClose",
    "workbench.enableExperiments": false,
    "workbench.editor.highlightModifiedTabs": true,
    "window.restoreFullscreen": true,
    "window.restoreWindows": "all",
    "window.openFoldersInNewWindow": "on",
`

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/51325720-db07f500-1a6d-11e9-98bc-afdbf3c87177.png)

Please post questions at our Stackoverflow community in the future, thanks.

**Comment by BartOtten** [comment]
This indeed solved it. However....

- This is the first answer (I googled a lot) which solves the 'issue' (so tnx for that!)
- It's in no way clear it is subject to the behavior you have to set in your OS
- It was not a question, but a bug report as I assumed it was cause by an error in the code.

Thanks for the quick answer with solid solution 👍
