### ISSUE TITLE
F8 ("next problem") doesn't work correctly when moving into the Settings file

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#66654]
1. Open your user settings JSON file and make several things invalid
2. Leave the settings JSON open, but switch to another file
3. Press F8 - this will jump you to the first problem in the settings JSON file
4. Press F8 again - nothing happens (expected: go to second problem in file)

This seems to be because the first F8 that takes you to the settings JSON doesn't place focus in there, so pressing F8 again doesn't move you to the next one. If you manually click in the right side of the editor and then press F8, then it works as expected.

**Comment by sandy081** [comment]
- Open settings JSON UI editor
- Have some errors in the settings
- Open another file
- F8 should navigate errors in the settings file.

**Comment by DanTup** [comment]
Fix LGTM in insiders! 👍
