### ISSUE TITLE
Language features not supported for ".pyi" python type files

### ISSUE THREAD

**Issue by erictraut** [Microsoft/vscode#66652]
The "python" language ID does not include the ".pyi" file extension, so python type hint files do not get proper syntax highlighting or other language service support. MagicPython, which is used for python syntax highlighting, supports ".pyi" files, so this should be as easy as updating the package.json file for the python extension.
https://github.com/Microsoft/vscode/blob/master/extensions/python/package.json

- VSCode Version: 1.30.2
- OS Version: MacOS 10.14.2

Steps to Reproduce:
1. Open a ".pyi" file such as any of those found in the [typeshed GitHub repo](https://github.com/python/typeshed)
2. Note that the file is not properly highlighted.

**Comment by aeschli** [comment]
yes, I will add it
