### ISSUE TITLE
The tutorial-flask wrong

### ISSUE THREAD

**Issue by vctea** [Microsoft/vscode#66656]
The Url https://code.visualstudio.com/docs/python/tutorial-flask can’t be accessed. What's wrong?

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/51a65537a467f6f057d087586b70e85ec46a4882
Thanks for finding this!

**Comment by kraigb** [comment]
Yes, thanks for catching that...there was a PR submitted to the sample and I forgot to escape the {{ when I updated the code.
