### ISSUE TITLE
VSCode deletes itself during update

### ISSUE THREAD

**Issue by glucaci** [Microsoft/vscode#66650]
Following the #61390 which was closed, I have hit the same problem today for the second time.

This is what i have in Control Panel / Programs:

![image](https://user-images.githubusercontent.com/13761704/51304300-0a9c0a80-1a38-11e9-94b2-3f212921fa49.png)

Log that I found in temp folder [vscode-inno-updater-1547710361.txt](https://gist.github.com/glucaci/e90a8dbdf2ee38594061998f1adcd7fe)

Found in Windows Event Viewer:
_Information	17 Jan 2019 08:32:50	User Profile Service	1530	None_
_Windows detected your registry file is still in use by other applications or services. The file will be unloaded now. The applications or services that hold your registry file may not function properly afterwards. No user action is required._

**Comment by joaomoreno** [comment]
Please uninstall both versions and reinstall the user version: https://code.visualstudio.com/docs/?dv=win64user

**Comment by joaomoreno** [comment]
I believe it is occurring due having both versions installed.

**Comment by andymule** [comment]
I hit this today. I discovered #61390 before this and found this log in my %TMP% directory that looks a lot like an updater is running and just deleting files.  I do not have more than one version installed. 

[vscode-inno-updater-1547747102.log](https://github.com/Microsoft/vscode/files/2774804/vscode-inno-updater-1547747102.log)

**Comment by glucaci** [comment]
Yes, the same case... and i don't believe that 2 versions installed caused that.
I'm more thinking on Windows Update interrupting the update process and I don't think that VS Code has a rollback strategy.
