### ISSUE TITLE
Un-saved files are not highlighted in the tab bar.  In the previous version there was a circle shown in the tab. Now nothing

### ISSUE THREAD

**Issue by i2chris** [Microsoft/vscode#66665]
Issue Type: <b>Bug</b>
a. Open a file
b. Edit it

There is nothing in the tab for this file that indicates that this file needs saving.    There used to be a filled in circle nex to the filename in the tab.  Now nothing.

I have tried a few different themes and they do the same.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.3-041503-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3602)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (2.43GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
rails-partial|ati|0.0.2
solargraph|cas|0.19.1
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
vsc-material-theme|Equ|2.6.3
json-tools|eri|1.0.2
prettier-vscode|esb|1.7.3
flow-for-vscode|flo|1.0.1
gc-excelviewer|Gra|2.1.26
chat|kar|0.9.2
haml|kar|1.1.0
vscode-rufo|mbe|0.1.1
vsliveshare|ms-|0.3.1121
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.5
ruby|reb|0.21.0
tabnine-vscode|Tab|1.1.0
vim|vsc|1.0.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@i2chris do you maybe have auto save enabled?
