### ISSUE TITLE
File/Workspace Explorer Grouping

### ISSUE THREAD

**Issue by nurbles** [Microsoft/vscode#66666]
[Currently using VS Code Version: 1.31-0-insider on Ubuntu 18]

I spend 99.99% of my time in VS Code working on my project's source code.  I really wish I could hide all of the non-source files (except, perhaps "makefile") -- but sometimes I still need to work on one of another of those other files.  "files.exclude" kinda works (but try hiding files with no '.' in their name) but then the files are "permanently" hidden, which isn't what I really want.

So... what I REALLY want is a way to group the various types/set of file together in collapsible sub-groups within my workspace folder.  For example, something like this:

`"files.groups": {
  "source": {
    "**.*.c": true,
    "**/*.h": true
  },
  "scripts": {
    "**/!(*.*)": true,  ## this is supposed to be a pattern for any file WITHOUT a 'dot'
	"**/*.code-workspace": false,
  },
  "settings": {
    "**/*.json": true,
	"**/*.code-workspace": true,
	"**/.vscode/*": true
  }
}`

(Sorry, I cannot figure out how to get this thing to include the line breaks I typed)

Then the explorer sidebar could show three sub-groups, "source", "scripts", and "settings" that may be expanded to see the matching files.  This could even allow some files to appear in multiple groups and others to never appear.  If there is already an extension that provides this, please point it out because I was unable to locate it.

**Comment by nurbles** [comment]
Gee, since I already tried searching before posting I obviously cannot guess the correct keywords to match the supposed duplicate.  The absolute LEAST you should have done was to include a link to the issue you say I duplicated!  Was that too difficult?

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/41860

**Comment by nurbles** [comment]
Thanks, I will add my thoughts there instead.

**Comment by isidorn** [comment]
Thansk
