### ISSUE TITLE
Add a title variable to show the folder path a file is in

### ISSUE THREAD

**Issue by lodewykk** [Microsoft/vscode#66660]
Issue Type: <b>Bug</b>

**Description:**
Recently, the "folderPath" entry ceased showing the entire folder path, instead, showing the path of the top-level open folder.

**To Reproduce:**
1. In _User Settings_ > _Window: Title_ > enter "${folderPath}"

Result: 
"/Users/Development/myProject"

Expected result:
"/Users/Development/myProject/myFolder"

**Example:**
_Window: Title_ value:
 `${dirty}${rootName}${separator}${activeEditorShort}${separator}${folderPath}`

Expected title:
`dev - ExecutionEnvironmentSection - C:\dev\eclipse.pde.ui\ui\org.eclipse.pde.ui\src\org\eclipse\pde\internal\ui\editor\plugin\ExecutionEnvironmentSection.java`

Title Produced:
`dev - ExecutionEnvironmentSection - C:\dev`

Example image: https://i.imgur.com/eZ1qJkt.png

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.90GB (5.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0
PowerShell|ms-|1.10.2
proto|pet|0.0.2
java|red|0.36.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.13.0

</details>

**Comment by bpasero** [comment]
@lodewykk this never worked like that and should have always just displayed the folder name of the workspace folder (= root):

![image](https://user-images.githubusercontent.com/900690/51325577-89f80100-1a6d-11e9-82ed-5f0fcf6b40d3.png)

But we can change this to a feature request.

**Comment by vedipen** [comment]
To achieve the aforementioned `Expected title`, you can use - 
`${dirty}${rootName}${separator}${activeEditorShort}${separator}${activeEditorLong}`   
  
I think, you mean the expected title should be -
`dev - ExecutionEnvironmentSection - C:\dev\eclipse.pde.ui\ui\org.eclipse.pde.ui\src\org\eclipse\pde\internal\ui\editor\plugin`

**Comment by bpasero** [comment]
@lodewykk does that help?

**Comment by vedipen** [comment]
I will be glad to raise a PR, if this could be added as a feature @bpasero

**Comment by bpasero** [comment]
@vedipen do you have a suggestion for the name of the variable?

**Comment by vedipen** [comment]
Without renaming existing variables (could affect existing users), how about 

* `${activeFolderShort}`: the name of the folder the file is contained in
* `${activeFolderMedium}`: the path of the folder the file is contained in, relative to the workspace folder
* `${activeFolderLong}`: the full path of the folder the file is contained in

**Comment by bpasero** [comment]
@vedipen yeah that sounds like it could work well.

**Comment by bpasero** [comment]
**Verification:** use the new title variables (see https://github.com/Microsoft/vscode/issues/66660#issuecomment-455231699) and ensure they work for you also for non-file editors (e.g. show nothing).
