### ISSUE TITLE
Freezed whole system

### ISSUE THREAD

**Issue by alexis5809** [Microsoft/vscode#66663]
Issue Type: <b>Bug</b>

Pc getting freezed by VS code after random time and getting unresponsible. Only mouse motion is available. No functionality. Each time have to restart the PC 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4390)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 1|
|Memory (System)|15.62GB (11.87GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
smarty|imp|0.3.0
sftp|lix|1.9.1
sublime-keybindings|ms-|4.0.0
php-docblocker|nei|1.7.0

</details>

**Comment by sandy081** [comment]
Can you please follow this [wiki](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and provide necessary information?
