### ISSUE TITLE
New Explorer: cannot expand/collapse using touch

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66678]
Testing with the Thinkpad and touch display: When I long touch on a file in the explorer I cannot open the context menu. This worked with the old tree.

/cc @isidorn

**Comment by isidorn** [comment]
Great find, since regression assigning to this milestone
@joaomoreno probably just some missing event on the tree level, right?

**Comment by bpasero** [comment]
@joaomoreno turns out I can bring up the context menu but touching a node that is expandable does not change the expansion state. I am lost in the code, where should I look at?

**Comment by isidorn** [comment]
@bpasero I would suggest to add the following line
this.view.onTap(this.reactOnMouseClick, this, this.disposables)

**Comment by bpasero** [comment]
Yeah seems to work, pushing.
