### ISSUE TITLE
TypeScript intellisence proposes snippets before properties in object literals

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6667]
- VSCode Version: alpha
- OS Version: Windows 10

See screen shot:

![capture](https://cloud.githubusercontent.com/assets/1931590/15473456/76156f88-2100-11e6-8649-7b9e12283809.png)

**Comment by dbaeumer** [comment]
@jrieken @aeschli the snippets are declared in the package.json pointing to an external file. Who decides to sort them before the properties returned from the intellisense. I always thought language suggestions come first.

**Comment by dbaeumer** [comment]
@jrieken this doesn't seem to be the case for JS. Here is a screen shot with Code Complete in a JS file in our smoke test. Interestingly snippets appear at the end here:

**Comment by dbaeumer** [comment]
I will remove the May milestone since this is nothing we can cleanup for May. However we need to agree on a better story here.

**Comment by jrieken** [comment]
my guess is that that's because of the sortText some suggestions in JS have. we should digg into that...

**Comment by dbaeumer** [comment]
Yes, it is because of the sort text. @aeschli and I debugged it. However from an end user experience this is confusing. We should invest into a better and more consistent story here.

**Comment by jrieken** [comment]
Agree. The idea of the _sortText_ was to give suggestions with complex labels a any chance to get a good sorting. Problem with JS salsa suggestion is that it sets the sort text to either `0` or `1`.

**Comment by emzero** [comment]
Came here to post this issue too.
![image](https://cloud.githubusercontent.com/assets/412489/16389937/b68ddb36-3c76-11e6-99f4-f94cbe5f81e7.png)

As you can see, inside the fetch parameter of type `RequestInit`, snippets are shown in the middle of the properties. I think they should be shown at the end or even not shown at all. I think snippets make sense when in an empty line, not in the middle of a function call, right?

**Comment by heroboy** [comment]
vscode:1.3.0

press tab not complete the property, but show the snippet.

![seterror](https://cloud.githubusercontent.com/assets/54468/16678828/586b04e6-4515-11e6-86b9-c49a581c0e8b.gif)

**Comment by Haemoglobin** [comment]
:+1:
