### ISSUE TITLE
Screen Cast Mode UI Indicator

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#66672]
In screencast mode, show an indicator in the UI that allows toggling on/off (like auto-attach)

**Comment by joaomoreno** [comment]
A status bar icon would be enough. @johnpapa Feel free to submit a PR.

**Comment by usernamehw** [comment]
This is probably easily achievable with an extension. Just invoking `workbench.action.toggleScreencastMode`.

**Comment by mattkwiecien** [comment]
@joaomoreno I'd love to take this one as well @joaomoreno

**Comment by joaomoreno** [comment]
Closing as out of scope.
