### ISSUE TITLE
Screen cast mode - setting to display n characters

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#66675]
show n characters 

when typing `const foo = bar + baz;` it scrolls so fast you only see some at a time

![2019-01-17_11-15-16](https://user-images.githubusercontent.com/1202528/51332214-4d1a1300-1a49-11e9-849d-d29c7f43a551.gif)

**Comment by joaomoreno** [comment]
@johnpapa Feel free to submit PR.

**Comment by joaomoreno** [comment]
Instead of adding a setting, just increased the limit and clipped the screencast less.
