### ISSUE TITLE
Screencast mode - settings for what to show

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#66674]
It would be nice to have control in settings to show non character (control keys) only vs show all. For example, showing CMD, CTRL, SHIFT, ESC, ENTER only vs showing all a, b, c, d .... z etc.

**Comment by alber70g** [comment]
Would be great to have settings for the size and location as well. Maybe some custom css that can modify it to the users' liking?

**Comment by EmmanuelDemey** [comment]
Definitely . Without the possibility to filter characters, I wont use this very fun feature.

**Comment by mkenigs** [comment]
I'll work on this if no one else has!

**Comment by ReactAcademyCa** [comment]
What is stopping this from happening? The pull request was succesfully completed in February, and we are now in June. 

I'd love for this to merge.

**Comment by texastoland** [comment]
The PR was only started not completed.

**Comment by mkenigs** [comment]
Yeah I think @joaomoreno marked it as backlog. But as I wrote it I'd also love for it to merge :)

**Comment by texastoland** [comment]
@mkenigs I sent you a code review back in March.

**Comment by mkenigs** [comment]
Sorry I missed that - don't see it, is it on the PR?

**Comment by joaomoreno** [comment]
Added new setting `screencastMode.onlyKeyboardShortcuts`

**Comment by isidorn** [comment]
Works nice. 
Bloaaaat
