### ISSUE TITLE
Screen cast mode - move the location of the displayed text

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#66676]
it may be helpful to move the location of where the text is displayed based on the screen, layout of the code, and other factors. I would love to see a setting for this at least giving a y coordinate.

**Comment by joaomoreno** [comment]
@johnpapa Feel free to submit PR.

**Comment by mattkwiecien** [comment]
I'd like to tackle this one if it's still available @joaomoreno

**Comment by mattkwiecien** [comment]
@joaomoreno Just submitted a PR for this one.  Sorry for the delay!

**Comment by isidorn** [comment]
Vertical offset works fine -> verified.
Also feels like bloat.
