### ISSUE TITLE
FuzzyScore: createMatches should coalesce ranges

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#66677]
The `createMatches` function isn't coalescing consecutive ranges, potentially creating lots of dom nodes:

![screenshot from 2019-01-17 17-52-39](https://user-images.githubusercontent.com/22350/51334723-b2d5c180-1a80-11e9-8b4d-46b85a5fa525.png)

Actually saw this in HC theme, because highlights have borders in that theme, so each character gets a border:

![screenshot from 2019-01-17 17-54-19](https://user-images.githubusercontent.com/22350/51334822-ec0e3180-1a80-11e9-9dab-ba061b5e7b81.png)

**Comment by joaomoreno** [comment]
@jrieken Please quickly glance over the fix.

**Comment by jrieken** [comment]
Looking good. Thanks
