### ISSUE TITLE
Emmet: hide `link:m` suggestion

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#66680]
Per https://github.com/Microsoft/vscode/issues/63384#issuecomment-455016185

We should only show `link:manifest` suggestion on `link:m`.

**Comment by rzhao271** [comment]
This issue has to do with how suggestions show in vscode-emmet-helper.
Example problem: `link:m` only shows `link:m` as a suggestion, when the suggestions `link:mf` and `link:manifest` should show instead.

**Comment by rzhao271** [comment]
Marking as emmet-revamp because even though I fixed this issue on vscode-emmet-helper, I'm waiting for some more upstream Emmet issues to be merged in.

**Comment by rzhao271** [comment]
\closedWith dc5a3da

**Comment by rzhao271** [comment]
Verifier: Verify that in an HTML document, that `link:m` is not suggested as an Emmet abbreviation when one types `link:m` into the document. Instead, `link:manifest` and `link:mf` should show up as suggestions instead.
