### ISSUE TITLE
Offer a command to hide inline problems view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#66684]
Problem:

- Install Vim extension
- Press F8
- ESC do not work
- You need to use mouse to focus on the inline problem view and dismiss it

If the command to dismiss the inline problem view is added, I can map a custom command to use it.

Alternatively, focus on the inline problem view by default for Go to prev/next Problem.

**Comment by sandy081** [comment]
There are commands already to close inline problems view

![image](https://user-images.githubusercontent.com/10746682/51851373-0fa86600-2324-11e9-843a-6d1f2605fb4c.png)
