### ISSUE TITLE
"Select for compare" and "Compare with selected" commands not shown for virtual documents

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#66681]
- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Compile and run the [virtual-document-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/virtual-document-sample).
2. Extension host window -> Explorer view
3. Ensure you have at least one "untitled" document open in "Open Editors"
4. Create a cowsay virtual document: > cowsay
5. Right-click the virtual document

Actual: the context menu for the virtual doc does not include the compare commands "Select for compare" and "Compare with selected".  The context menu for the the untitled doc does.

Expected: context menu for virtual docs should include the compare commands.

Note: the hard part already seems to be implemented, can already compare a virtual doc with another doc by selecting the other doc first!  But this workaround only works when a non-virtual document is present.  Two virtual docs ought to be comparable in the same way.  Just need to enable the commands.

**Comment by isidorn** [comment]
We will now show these actions for all items that have resources
This is a bit too much I believe, but let's wait for users to complain. I think this is a better approach now.

**Comment by johnspurlock** [comment]
Thank you!

**Comment by isidorn** [comment]
Welcome. Try it out in monday vscode insiders and let us know if it works as you expect
