### ISSUE TITLE
missing focus when triggering search while quick open is open

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6668]
* open an editor
* open quick outline or another quick pick window, like F1
* hit <kbd>Cmd+F</kbd> to trigger file search
* quick open closes, the editor find widget shows, ⚡ but the editor has focus

**Comment by bpasero** [comment]
Tricky, quick open is keen on bringing focus to the editor whenever it closes and I think that is good. But in this case it collides with the find widget wanting to get focus. I am sure there are other actions where this issue would show up, not just find.

Could play around with running editor focus from a timeout and checking if focus is somewhere in the editor but currently I see no API to find out if focus is within the editor in the find widget.

@alexandrudima ideas?

**Comment by alexandrudima** [comment]
I would say if quick open closes in this case due to blur, perhaps it is good to leave the focus alone.
