### ISSUE TITLE
Allow using the quick fix shortcut in the problems view

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#66685]
**Repo**
1. With a TS file:

```ts
export class Food {}
new foo()
```
1. Open problems view and select a problem (make sure the entry is focused)
1. Try using cmd+. to trigger lightbulb

**Current behavior**
Nothing happens

**Feature Request**
Should show quick fix menu in the problems view

**Comment by roblourens** [comment]
Works but the context menu shows up in the top corner, not pretty

![image](https://user-images.githubusercontent.com/323878/52025449-2cc26d80-24b9-11e9-9122-b871cc090f16.png)

**Comment by sandy081** [comment]
Good catch, looks like a timing issue.
