### ISSUE TITLE
Powershell extension terminal keeps crashing

### ISSUE THREAD

**Issue by SeanCoB** [Microsoft/vscode#66688]
- VSCode Version: 1.30.2
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Edit Powershell code. While typing, the terminal will crash and prompt to be restarted.

Does this issue occur when all extensions are disabled?: No

I turned on verbose logging and captured the attached log. It looks to be getting angry at my incorrect syntax that occurs as I'm typing...

[EditorServices.log](https://github.com/Microsoft/vscode/files/2770950/EditorServices.log)

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
