### ISSUE TITLE
"Allow for floating windows" issue no longer allows upvotes

### ISSUE THREAD

**Issue by RoyTinker** [Microsoft/vscode#66683]
The issue https://github.com/Microsoft/vscode/issues/10121 was "locked and limited to collaborators" in response to the last comment, which asked that discussion be closed. That comment also encourages people to upvote the issue to show support.

However, it appears that "locked and limited to collaborators" actually disables further upvotes/downvotes.

Is there any way to prevent comments but allow upvotes/downvotes? If so, then #10121 should be updated to allow further voting.

FYI @markwhitfeld

**Comment by bpasero** [comment]
@RoyTinker I suggest you ask GitHub support about this as I am not seeing this to be an issue with VSCode itself but rather GitHub, I will close this.

**Comment by egamma** [comment]
@RoyTinker please see our new Draft Roadmap https://github.com/Microsoft/vscode/wiki/Roadmap, as you can see that an exploration on this is on the plan.
