### ISSUE TITLE
Show the total number of matches in the Search tab

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#6669]
When I search for a string from the Search tab (<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F</kbd>), the search results are shown grouped by files, and a match _per file_ is shown. But vscode doesn't show **exactly how many** files match, or how many occurrences **in total** are there. I believe this should be added to the default search ui.

Usecases:
1. It helps in estimating the amount of time it might take to refactor.
2. It helps while understanding the impact of a piece of code (more the number of files loosely implies more impact, so I might want to invest more time in optimizing it)

**Comment by bpasero** [comment]
@Microsoft/vscode can I get some +1 or -1, the PR in https://github.com/Microsoft/vscode/pull/6997 suggests to just put the message on top of the results. This would look like:

![image](https://cloud.githubusercontent.com/assets/900690/15645340/1c9e4bac-2658-11e6-90b8-cdec1720d71c.png)

@stevencl @bgashler1 fyi

**Comment by isidorn** [comment]
-1 just a personal preference I never care about that information.
I do not mind though if we include this - if users find it usefil. It nicely alligns with info in find wigdet - I which I also do not use but I see ti can be useful for some people.

**Comment by Tyriar** [comment]
:+1: I find it useful when I do mass find and replaces (#1690 :disappointed:)

**Comment by jrieken** [comment]
I don't like that mockup, how about putting it at the bottom of viewlet? Then it isn't so crowed at the top (buttons, input, details, results...)

**Comment by bpasero** [comment]
I like to show this information somewhere and would suggest to try it out for a while to see how it behaves. I am not sure if the position above the search result is good or bad. I think it is good because that is where I would look for it.

**Comment by kisstkondoros** [comment]
ping

**Comment by kumarharsh** [comment]
Can this be floated in an insider build? Would really be helpful if we could use and give some feedback on this.

**Comment by bpasero** [comment]
The PR cannot be accepted because of a layout glitch I documented in https://github.com/Microsoft/vscode/pull/6997#issuecomment-226732188.

**Comment by joaomoreno** [comment]
:-1: I'd rather just have it inline without any grammar, like the find widget:

![image](https://cloud.githubusercontent.com/assets/22350/16147818/eb8ce046-3485-11e6-8f98-3d1c81d61fcb.png)

Adding a line and writing text makes it both look ugly and take longer to understand since the user'll have to read the sentence.

**Comment by sandy081** [comment]
I think we would need to show the number once we have Replace functionality. 

If it is only count, How about showing in the title bar just like in Problems view? Side bar is already narrow and compressing the search bar by adding more info / details make it more cumbersome.

**Comment by sandy081** [comment]
Also Badge like in Git view?

**Comment by sandy081** [comment]
Updating the summary to include number of files also.

**Comment by kumarharsh** [comment]
@roblourens There is some bug with this feature. It doesn't count properly, or counts too soon (even when search is running)

![image](https://cloud.githubusercontent.com/assets/760112/22819097/98198b18-ef96-11e6-92ce-4c8d1350fd03.png)

**Comment by roblourens** [comment]
There is some problem...#20411
