### ISSUE TITLE
Support numeric input variables

### ISSUE THREAD

**Issue by amcasey** [microsoft/vscode#66697]
I'd like to be able to use [input variables](https://code.visualstudio.com/docs/editor/variables-reference#_settings-command-variables-and-input-variables) to select the port to attach to in my (NodeJS debugging) launch configuration.

```json
        "inputs": [
            {
                "id": "debugPort",
                "description": "Which port do you want to attach to?",
                "default": 9229,
                "type": "pickString",
                "options": [ 9229, 9230, 9239, 9329, 5870 ]
            }
        ]
```

It seems quite likely that substituting a numeric value will be difficult/impossible, so it might be necessary to accept strings for "port" property of launch configurations.

In a perfect world, I'd also be able to alias the ports in the combo box: "default" for 9229, "VS Code Extension" for 5870, etc.

**Comment by weinand** [comment]
Yes, variable substitution in VS Code only works within strings.
If you want to use it for non-string typed launch config properties, you will have to ask the extension author to support strings as an alternative type.
