### ISSUE TITLE
Passing objects to showQuickPick() returns error n.label.replace is not a function: TypeError: n.label.replace is not a function

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#66699]
I am trying to call `showQuickPick()` by passing an array of objects.

```
let itemList = await MyCustomObject.getMyCustomObjectList(); // static method returns Promise<MyCustomObject[]>
let appList = await vscode.window.showQuickPick(itemList, { canPickMany: true });
```

My class is defined as follows:

```
export class MyCustomObject extends vscode.TreeItem implements vscode.QuickPickItem { .... }
```

The error I receive in the Chrome developer tools is:

>  n.label.replace is not a function: TypeError: n.label.replace is not a function

How do I correct this?

**Comment by pcgeek86** [comment]
I also tried implementing a totally separate data structure, just to use with the `showQuickPick()` method, and it's giving me the exact same problem.

```
export class MyCustomObjectQuickPick implements vscode.QuickPickItem {
    label: string;
    description: string;
    detail: string;

    constructor(
        label: string,
        description: string,
        detail: string
    ) {
        this.label = label;
        this.description = description;
        this.detail = detail;
    }
}
```

**Comment by chrmarti** [comment]
@pcgeek86 TypeScript only does compile-time checks. You can still pass arbitrary types at runtime when everything has been compiled down to JavaScript. Maybe you can figure out how the number escaped compile-time checks when it got assigned to a string variable/property. It could have been assigned to a variable/property of type `any` and from there it can be assigned to anything else next.

**Comment by pcgeek86** [comment]
Hi @chrmarti, that makes sense. I'm fetching data from a web API and building the objects from the result. There's no way for it to know the data type of each field. JavaScript was just defaulting to a numeric value, since technically the data is a valid numeric value. I had to wrap the value in a `String()` call to force the numeric field to be a string.

Do you think it makes sense to keep this issue open, to improve the `showQuickPick()` method to perform some additional validation on incoming objects? For example, right now, the `showQuickPick()` method just pukes, if the `label` property is a `Number`. Could this be lightly improved, such that the `showQuickPick()` method checks the type of the `label` property, and throws a more useful error message?

**Comment by pcgeek86** [comment]
@chrmarti Any thoughts? Could the developer friendliness of `showQuickPick()` be improved, per the above?

**Comment by pcgeek86** [comment]
@chrmarti Any thoughts on improving the error message / catching invalid inputs to `showQuickPick()`?
