### ISSUE TITLE
New explorer: File preview does not respect double click to pin file open

### ISSUE THREAD

**Issue by rhefner** [Microsoft/vscode#66695]
- VSCode Version: Version 1.31.0-insider (1.31.0-insider)
- OS Version: MacOS Mojave 10.14

Steps to Reproduce:

1. Enable "Workbench › Editor: Enable Preview"
2. Attempt to double click file

File still is italicized and will be replaced on next single-click of another file

Does this issue occur when all extensions are disabled?: Yes (with `code-insiders`)

**Comment by bpasero** [comment]
@rhefner where do you double click? in the file explorer?

**Comment by rhefner** [comment]
@bpasero Yup. It was always working fine up until at least a day ago.

**Comment by bpasero** [comment]
I cannot reproduce but this could be a regression from the new explorer.

**Comment by bpasero** [comment]
@rhefner can you share a video how to reproduce on your machine?
