### ISSUE TITLE
Latest Windows 10 Update Causes Bad Colors In VSCode Terminal

### ISSUE THREAD

**Issue by radman-x** [Microsoft/vscode#66690]
- VSCode Version: 1.30.2
- OS Version: Windows 10 Home, Version 1809, OS Build 17763.253, Installed on 1/17/2019

Steps to Reproduce:

1. From VSCode, open terminal (PowerShell)
2. Hit enter a few times to create a few lines, then type a few letters of a command.
3. Background turns strange green color, first few letters are invisible, against strange colored background (probably just the same color as the background). See attached where the text "yes there is some text here but first word does not appear and backgr …" was typed and the word "yes " is invisible.
4. This is a BIG problem because many messages (e.g., compiler errors, etc.) are the same strange color and, so, are effectively invisible.
5. This did NOT ever happen until latest Windows 10 update (build 17763.253).
![badvscodeterminalcolors](https://user-images.githubusercontent.com/9258904/51356994-71461600-1a82-11e9-9b1c-e39cbd164d03.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
