### ISSUE TITLE
Outline window won't load document symbols for .py files

### ISSUE THREAD

**Issue by ChristopherLBruce** [Microsoft/vscode#66696]
Issue Type: <b>Bug</b>

Outline view stalls on "Loading document symbols for [filename' when editing .py(python) files.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1090T Processor (6 x 3214)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
autodocstring|njp|0.2.3

</details>

**Comment by sandy081** [comment]
Please file issue against python extension you installed
