### ISSUE TITLE
 Uncaught Error - uri

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#667]
Issue Id: <b>dd7f2b59-2ac5-8d7c-8c81-0f61c7bd5b85</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/base/common/uri.ts#L177:9 (URI.file)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/uri.ts#L177:9 (URI.file))<br />[/vs/workbench/parts/debug/common/debug.ts#L102:36 (Source.fromRawSource)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/common/debug.ts#L102:36 (Source.fromRawSource))<br />[/vs/workbench/parts/debug/common/debugModel.ts#L553:76 (Model.rawUpdate)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/common/debugModel.ts#L553:76 (Model.rawUpdate))<br />[/vs/workbench/parts/debug/common/debugModel.ts#L547:58 (Model.rawUpdate)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/common/debugModel.ts#L547:58 (Model.rawUpdate))<br />[/vs/workbench/parts/debug/browser/debugService.ts#L203:16 (DebugService.registerSessionListeners)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/workbench/parts/debug/browser/debugService.ts#L203:16 (DebugService.registerSessionListeners))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1782:0 (onComplete))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1448:0 (call)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1448:0 (call))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1127:0 (_notify)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1127:0 (_notify))<br />[vs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/srcvs/workbench/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />    at Object.__dirname.undefined.P.enter (out/vs/workbench/workbench.main.js:1544:5535)<br />    at __dirname.undefined.t.Class.define._run (out/vs/workbench/workbench.main.js:1544:7361)<br />

**Comment by isidorn** [comment]
I improved the error message for now so next time we now what is wrong with the passed uri. The error might be comming from debug backend.

**Comment by isidorn** [comment]
Argh forgot that I can not have a path in an error due to privacy issues. Leaving this closed until it happens again since this error currently does not give me enought space to do something
