### ISSUE TITLE
The display breaks when using Japanese characters string in JavaScript mode

### ISSUE THREAD

**Issue by noriokaki** [microsoft/vscode#66705]
- VSCode Version:1.31.0-insider (and 1.30.2)
- OS Version:Windows 10

Steps to Reproduce:
1. Input this text . 
    > console.log("★★★★★★★★★★★★★★★すばしっこい茶色の狐はのろまな犬を飛び越える");
    > console.log("★★★★★★★★★★★★★★★The quick brown fox jumps over the lazy dog"); 
 
    ![ws0016](https://user-images.githubusercontent.com/12603061/51365929-22ea5300-1b26-11e9-9e98-db1c6dd917b5.JPG)

2. Change Language Mode to JavaScript
![ws0017](https://user-images.githubusercontent.com/12603061/51365930-27af0700-1b26-11e9-82eb-efb6d04a98a4.JPG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
What do you mean by collapse japanese language?

**Comment by noriokaki** [comment]
I'm not good at English.
Well, it may be a bad title.

The display breaks when using Japanese characters string in JavaScript mode

Does this give meaning to you?

**Comment by noriokaki** [comment]
Expected display is "console.log("★★★★★★★★★★★★★★★すばしっこい茶色の狐はのろまな犬を飛び越える");".
However, as for the actual display, the bracket closing position is wrong like the second image.

**Comment by alexandrudima** [comment]
Does not reproduce on macOS, so it might be a windows specific issue:

![image](https://user-images.githubusercontent.com/5047891/52018860-141f7b00-24ec-11e9-8927-9549d9d1b536.png)

**Comment by alexandrudima** [comment]
I can reproduce on Windows:
![image](https://user-images.githubusercontent.com/5047891/66311729-75b3a700-e90f-11e9-96ec-7c551c03f4dd.png)

**Comment by alexandrudima** [comment]
This does not reproduce on Chrome v77. But I could reproduce on a Chromium v69 (which matches what VS Code is currently built on):

![image](https://user-images.githubusercontent.com/5047891/66312104-43567980-e910-11e9-8177-7c99c2bab4cc.png)

**Comment by alexandrudima** [comment]
All in all, this will be fixed once we update to a newer Electron version (which contains a newer Chromium version).
