### ISSUE TITLE
Very ugly font on Ubuntu 18.10

### ISSUE THREAD

**Issue by farzadmf** [Microsoft/vscode#66708]
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Install VSCode using snap
2. Start debugging a dotnet core application so that the Debug windows are open

Does this issue occur when all extensions are disabled?: Yes/No
I'm not sure how to perform this step because if I disable all extensions, I cannot start debugging my application

---

I have installed VsCode using `snap` on Ubuntu 18.10, and the fonts seem to be fine on the editor (of course not as good as on Windows!), but for some reason, the editor "tooltip", the debug console and sidebar have extremely ugly fonts. I tried finding a setting to change at least the font in the debug console, but I didn't find anything.

Here's a screenshot with red rectangles around the regions with the weird font:

![ugly-ubuntu](https://user-images.githubusercontent.com/5768792/51368490-a1f77100-1abd-11e9-87c7-8be9cf4577fb.png)

Is this fixable, or I have to live with this appearance if I want to work with VsCode on Ubuntu

**Comment by isidorn** [comment]
This is a known snap issue.
@joaomoreno can point you to the original issue.
To worka around it, do not install vscode via a snap

**Comment by farzadmf** [comment]
Hi @isidorn , I uninstalled my `snap` version, and installed the "normal" version. Although some of the fonts are looking better (for example, the debug sidebar), but the debug console, and the exception popup are still looking weird:

![image](https://user-images.githubusercontent.com/5768792/51415881-67391b80-1b45-11e9-9727-c0914114e45a.png)

(The green rectangle means it looks better)

It seems that it's picking up the `Monaco` font I manually installed before, but why is it so ugly? `Monaco` is one of my favorite fonts, but here, it's not looking good at all

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/63194

@farzadmf Yes, we are working on a official snap release, but we'd like to fix issues like this one first.

**Comment by farzadmf** [comment]
Thank you @joaomoreno , that's good to know
