### ISSUE TITLE
rg process within VS code using more than 50% of CPU

### ISSUE THREAD

**Issue by hitesh11** [Microsoft/vscode#66704]
Issue Type: <b>Bug</b>

Using VS code on remote code using SFTP.. After some time, VS code is using 57.6% of CPU, with rg subprocess taking 33.6% of CPU.. finally taking CPU usage to 100%.. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (5.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
vscode-yaml|red|0.2.1

</details>

**Comment by hitesh11** [comment]
![screenshot 94](https://user-images.githubusercontent.com/2941666/51363865-e9730280-1aa7-11e9-8d7e-9adb1aa5c3d6.png)

**Comment by gjsjohnmurray** [comment]
Any particular reason why you are still using 1.28? AFAIK the current release (1.30.2) includes fixes for high CPU usage by rg

**Comment by hitesh11** [comment]
Thanks.. I upgraded it to latest release and hope it fixes the problem!
