### ISSUE TITLE
macro defined in Makefile and code highlight make an error

### ISSUE THREAD

**Issue by xsjqqq123** [Microsoft/vscode#66701]
some macro value defined in Makefile,  but c/c++ code can not get it's value,  and the highlight make an error.

look follow image, MP4_SUPPORT is only opened by situation.

![image](https://user-images.githubusercontent.com/8264121/51360565-215d6280-1b07-11e9-9780-425920a89f91.png)

Is there any idea to deal with it ?

**Comment by sandy081** [comment]
Please file issue against c++ extension - https://github.com/Microsoft/vscode-cpptools
