### ISSUE TITLE
Color syntax issue for "${" in simple or double quotted string

### ISSUE THREAD

**Issue by ClementUTBM** [Microsoft/vscode#66719]
When a string has "${" inside it, it renders like a template string is used even if we use doube or single quote.

![image](https://user-images.githubusercontent.com/14770781/51379467-c54b0c00-1b0f-11e9-8016-6a89891c03e2.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
