### ISSUE TITLE
TSServer not starting and processing all files

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/vscode#66714]
Issue Type: <b>Bug</b>

After some discussion in stack-overflow, it is my understanding, that the "Initializing TS/JS language features" services should analyze and validate all source files in my TypeScript project when VSCode starts. I only see Problems after a source file has been opened and I must manually invoke a task to validate all source file using the tsc cli to see the results for the complete project. Additionally after tsc shows all problems in the project, when I then open a source file I now see "Initializing TS/JS language features" in the status bar and all other problems in the problems panel disappear.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.14GB free)|
|Process Argv|D:\MyDev\ljs_app\branches\wip\periscope\build|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
python|ms-|2018.12.1
printcode|nob|3.0.0
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
stylelint|shi|0.47.0
language-stylus|sys|1.11.0
stylint|vtf|0.0.2
plsql-language|xyz|1.7.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Also, the first part of your question is #13953

**Comment by doberkofler** [comment]
@mjbvz Looking at #13953 suggests that it is intended by design to always only validate a single file. Is this correct?

**Comment by mjbvz** [comment]
@doberkofler Yes, we currently only show errors for files you have open but we provide project wide intellisense
