### ISSUE TITLE
Failed to set environment variables in task.json in vscode for WSL

### ISSUE THREAD

**Issue by yw5aj** [Microsoft/vscode#66710]
- VSCode Version: 1.30.2
- OS Version: Windows 10 64 bit, using WSL Ubuntu 18.04

Steps to Reproduce:

1. Create a tasks.json with the following content:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "test env",
            "type": "shell",
            "command": "echo",
            "args": [
                "${env:test}"
            ],
            "options": {
                "env": {
                    "test": "Hello world"
                }
            }

        },
    ]
}
```

2. Run task. It seems that the environment variable was not really set.

The ${env:test} was taken from this link: https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

Does this issue occur when all extensions are disabled?: N/A

**Comment by alexr00** [comment]
Environment variables accessed by `${env:test}` are evaulated for VS Code. The environment variable `"test"` that you define is defined only for the process that runs your task. You need to access your environment variable in the standard way for the OS that you're using, not using `${env:test}`.

**Comment by yw5aj** [comment]
Ah I see! Thank you. For example, I'd need to run export test="Hello world!" to set the variable.

**Comment by alexr00** [comment]
You shouldn't need to do an export. You should just be able to have
````
"args": [
                "$test"
            ],
```
where `$test` is how you access environment variables on your OS. On Windows with cmd it would be `%test%.
