### ISSUE TITLE
Enable & Disable a div and all of its elements in it.

### ISSUE THREAD

**Issue by faizanmalik9** [Microsoft/vscode#66713]
need a feature to disable div and all element in it. like if i have a div contains text boxes, check boxes and radio buttons. when i disable div all text boxes,check boxes and radio buttons become disable/not clickable until i enable div again.

**Comment by aeschli** [comment]
Can you add a code sample of before and after?

**Comment by faizanmalik9** [comment]
`<div><input typ"text"></div>`

**Comment by faizanmalik9** [comment]
its like if i have a div containing different input fields like 
`<div id="myDiv">
    	<label>Name:</label>
        <input type="text">
        <label>Gender:</label>
        <label><input type="radio" name="sex"> Male</label>        
        <label><input type="radio" name="sex"> Female</label>
        <label>Hobbies:</label>
        <label><input type="checkbox" name="sports"> Soccer</label>
        <label><input type="checkbox" name="sports"> Cricket</label>
        <label>Address:</label>
        <textarea></textarea>
        <label>Country:</label>
        <select>
            <option>select</option>
        </select>
        <br>
        <button type="button">Submit</button>
        <button type="button">Reset</button>
    </div>` 
now in java script i just write `$("#myDiv :input").prop("disabled", true);` and all of input fields in div gose disabled, and when i write `$("#myDiv :input").prop("disabled", false);` all inputs in div gose enable.
reference link [https://codepen.io/tipsoftheday/pen/JreAp](url)  
hope you understand my point.
