### ISSUE TITLE
Crash at scrolling large files (136MB)

### ISSUE THREAD

**Issue by AndreasLamparter** [microsoft/vscode#66711]
Open large file
Scroll slowly through the file
VS Code crashes

File is too large to attach ....

**Comment by AndreasLamparter** [comment]
It is a log4net log file. VS Code crashes with disabled log extension too.

**Comment by rebornix** [comment]
Close as there is no enough information to help troubleshoot. If possible please provide the file which crashes VS Code, or a sample file which can reproduce the same issue.
