### ISSUE TITLE
It always can not find the definition,but when I restart the software it will be OK

### ISSUE THREAD

**Issue by zhaoqingtao-hik** [Microsoft/vscode#66718]
Issue Type: <b>Bug</b>

It always can not find the definition,but when I restart the software it will be OK

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.49GB free)|
|Process Argv|C:\svn\vscode\cellc.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.0
code-gnu-global|aus|0.2.2
algorithm-mnemonics-vscode|dav|1.0.3
language-ttcn|eal|0.8.0
highlight-icemode|ice|0.0.6
sftp|lix|1.9.1
vscode-clang|mit|0.2.3
python|ms-|2018.12.1
cpptools|ms-|0.20.1
vscode-icons|rob|8.0.0
text-marker|ryu|1.10.0
markdown-preview-enhanced|shd|0.3.11
vim|vsc|1.0.2

(3 theme extensions excluded)

</details>

**Comment by zhaoqingtao-hik** [comment]
If It happend,I find all this file can not find the definition. @sandy081

**Comment by sandy081** [comment]
Looks like an issue with C++ extension, please find an issue against it.

**Comment by zhaoqingtao-hik** [comment]
I just have installed the extension of C/C++ & C/C++ Clang Command Adapter
