### ISSUE TITLE
vscode very very slow with go plugin

### ISSUE THREAD

**Issue by dreamer-nitj** [Microsoft/vscode#66712]
I have been using visual studio code for over a year now with go plugin and recently it has become very very slow to navigate and scroll. I am using MacOS Mojave and `go version` reports this:

`go version go1.11.4 darwin/amd64`

My vscode version is `1.30.2` and go plugin version is `0.8.0` I have also updated all the go tools after i updated my go version. Is anyone else facing this issue?

This also makes my whole MacOS very slow. I also see heavy CPU usage and fan speed when i do editing constantly.

**Comment by sandy081** [comment]
Please file an issue against go extension - https://github.com/Microsoft/vscode-go
