### ISSUE TITLE
Show message that 'Insiders' build is updated more frequently

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6671]
If the Insiders release becomes the new alpha, we'll have to communicate to existing users that they can expect more frequent updates when continuing with the Insiders.

For this a message "The Insider release will be updated more frequently..." should be shown once when starting the new version for the first time.
The message should include a link to the corresponding blog-post.

@chrisdias @seanmcbreen please provide the wording for the message.

/cc @bpasero

**Comment by chrisdias** [comment]
FWLink to the blog post: http://go.microsoft.com/fwlink/?LinkID=798816

"Insider builds to become daily builds! For more information, please see our blog."

**Comment by joaomoreno** [comment]
@chrisdias They will be at least daily. Many days they will be built multiple times. Maybe a different phrase that indicates this?

**Comment by chrisdias** [comment]
@joaomoreno Not sure how to phrase this... I can make the blog post to be more clear about this, and that is a more durable document.
