### ISSUE TITLE
Memory and cpu is too high

### ISSUE THREAD

**Issue by li986390329** [Microsoft/vscode#66717]
Memory and cpu usage is too high, and even cause the system to get stuck. when i open a large file in node_module, about 10000 lines, F12 will be very card, and there are two cases of memory high today, i don't know if is a vscode problem, or plugin issues.

**Comment by sandy081** [comment]
Can you please try to reproduce it by disabling all extensions?

**Comment by li986390329** [comment]
thanks, when i disable all  extensions,  i can't reproduce it.   But i have too many plugins. I can't sure which one can cause this problem. thank you very much.
