### ISSUE TITLE
FuzzyScore should work on accented characters

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#66720]
It would be cool if `joao` would match against `joão` in our FuzzyScore matcher, for example. What do you think @jrieken?

**Comment by jrieken** [comment]
I am scared... I won't be easy because today we compare character codes... It would be nice if we find a way to simplify ã, à, á, â into a

**Comment by jrieken** [comment]
We could be pragmatic and keep some kind of mapping for these characters: https://unicode-table.com/en/blocks/latin-1-supplement/, e.g. `ç, ć, č` map to `c`, `è, é, ê, ..` map to `e` and so on.

**Comment by joaomoreno** [comment]
Yup, thought the same. Related question: https://stackoverflow.com/q/863800

Also, wow, look at this: https://stackoverflow.com/a/37511463

**Comment by jrieken** [comment]
I have changes ready for `strings#removeAccents` which does `jöão` to `joao` transformations. Not eager to bake that into fuzzy score because of the potential perf implementation...

**Comment by joaomoreno** [comment]
I say for fuzzy we just table it!

**Comment by jrieken** [comment]
What could work is the following: in fuzzy score, before filling in the table, we run a fast check to see if the pattern-characters occur in the word at all. That would be a good time to check if all characters are ASCII and iff not do the conversion then.

**Comment by joaomoreno** [comment]
Would be do that both for needle and haystack?
