### ISSUE TITLE
Allow editor.tokenColorCustomizations inside language specific

### ISSUE THREAD

**Issue by mikecentola** [microsoft/vscode#66729]
Currently you can edit the user settings and add `editor.tokenColorCustomizations` to modify certain colors without creating or editing an entire theme.

However, `editor.tokenColorCustomizations` does not work with the scope of language-specific settings... i.e.

```
"[language]": {
    "editor.tokenColorCustomizations": {
    }
}
```

This would be a huge benefit to syntax extension developers. Currently I'm developing an extension for CNC G-Code and I'd like to add a configuration option to add _typical_ cnc g-code editor colors. I can update the user settings directly from the extension but that involves a lot of additional coding to store any current customizations that the user may have put in there already.

**Comment by mikecentola** [comment]
Here's my first iteration of the extension:

[](https://marketplace.visualstudio.com/items?itemName=appliedengdesign.vscode-gcode-syntax)

**Comment by usernamehw** [comment]
Wasn't it always possible?

```js
"editor.tokenColorCustomizations": {
	"textMateRules": [
		// JavaScript
		{
			"scope": "source.js keyword",
			"settings": {
				"foreground": "#FF0000"
			}
		},
		// TypeScript
		{
			"scope": "source.ts keyword",
			"settings": {
				"foreground": "#0000ff"
			}
		},
    ]
}
```

**Comment by usernamehw** [comment]
`source.gcode` in your case, I guess.

**Comment by CameronBieganek** [comment]
> Wasn't it always possible?
> 
> ```js
> "editor.tokenColorCustomizations": {
> 	"textMateRules": [
> 		// JavaScript
> 		{
> 			"scope": "source.js keyword",
> 			"settings": {
> 				"foreground": "#FF0000"
> 			}
> 		},
> 		// TypeScript
> 		{
> 			"scope": "source.ts keyword",
> 			"settings": {
> 				"foreground": "#0000ff"
> 			}
> 		},
>     ]
> }
> ``

It is possible to make language specific color customizations this way (by using `source.ts` or similar as the first scope within the TextMate scope selector). However, it would be convenient if the color customizations could be separated into the language-based settings, as described by @mikecentola.

I'm not sure how this would interact with the **Developer: Generate Color Theme from Current Settings** command.

**Comment by gjsjohnmurray** [comment]
> However, `editor.tokenColorCustomizations` does not work with the scope of language-specific settings

I'd like this enhancement to cover `editor.semanticTokenColorCustomizations` as well.

And if we get #101418 it will become possible to define separate sets of settings for dark, light and high-contrast themes.

**Comment by dkalomoiris** [comment]
> However, editor.tokenColorCustomizations does not work with the scope of language-specific settings

bump for that 😎

**Comment by ian-h-chamberlain** [comment]
In relation to [semantic token customizations](https://github.com/microsoft/vscode/issues/66729#issuecomment-652727577): I found a snippet of the language extension API documentation which shows this is actually possible, but not in the typical configuration manner in the `"[language"]` section of configuration.

The [https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming](Semantic Highlight Guide) shows that it's possible to make a selector match a language with a colon (`:`) and the language name, such as their example:
```json
{
  "semanticTokenColors": {
    "variable.readonly:java": "#ff0000"
  }
}
```
Hopefully this helps if like me you were looking for some way to make language-specific color customizations!
