### ISSUE TITLE
Option to open terminal in current directory

### ISSUE THREAD

**Issue by SMadani** [Microsoft/vscode#66721]
Although going to Terminal -> Open Terminal with a folder open does set the path to current directory, it doesn't when editing a single file. It would be nice if there was an option to open terminal to the path of the currently active file in the editor. If the current editor does not have a file on disk, then the terminal should open in the default directory (currently the user's home).

**Comment by SMadani** [comment]
This is NOT a duplicate! This is an enhancement request to open the terminal in the path of the current file. It is not a bug report.

**Comment by Tyriar** [comment]
You can do this with this extension https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here
