### ISSUE TITLE
attribute align html

### ISSUE THREAD

**Issue by NeylorCesar** [Microsoft/vscode#66723]
Issue Type: <b>Bug</b>

'align' this attribute used in html,
represents visual error in the IDE with red color.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (10.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
sql-formatter|cym|1.0.2
vscode-style-formatter|dwe|1.0.0
apacheconf-snippets|eim|1.2.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
vscode-mysql|for|0.3.0
minify|Hoo|0.3.0
mysql-syntax|jak|1.3.1
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.2.0
vscode-language-pack-pt-BR|MS-|1.30.2
mssql|ms-|1.4.0
vscode-php-getters-setters|php|1.2.3
php-formatter|Sop|0.2.4

</details>

**Comment by aeschli** [comment]
Can you please file compact html code sample that shows the usage of 'align'

**Comment by NeylorCesar** [comment]
![print_01](https://user-images.githubusercontent.com/26494439/51475528-bbbce080-1d69-11e9-9a6c-d32ca51faa08.png)

**Comment by NeylorCesar** [comment]
![print_01](https://user-images.githubusercontent.com/26494439/51476466-c6c54000-1d6c-11e9-8f46-92ca3efd2721.png)

**Comment by NeylorCesar** [comment]
![print_01](https://user-images.githubusercontent.com/26494439/51476715-7ac6cb00-1d6d-11e9-824c-c4dfadb75dd1.png)

**Comment by aeschli** [comment]
'align' is red because it has been deprecated should no longer be used. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#Attributes

**Comment by NeylorCesar** [comment]
Thanks!
