### ISSUE TITLE
when i use outline in sidebar,could you show the response view in the main text editor？thanks ：)

### ISSUE THREAD

**Issue by luqiudi** [Microsoft/vscode#66737]
when i use outline in sidebar,could you show the response view in the main text editor？thanks ：)
when i use up/down key to browse the outline ，can you scroll the editor to the position where the outline label refer to？pls
my english isn very well,sry

**Comment by jrieken** [comment]
Sorry, I don't really understand this request. Are you looking for the 'Follow Cursor' feature?

<img width="363" alt="screenshot 2019-01-21 at 08 32 57" src="https://user-images.githubusercontent.com/1794099/51487050-2ca6cd00-1d57-11e9-90e6-8eeee045509e.png">
