### ISSUE TITLE
No command for Terminal toggle

### ISSUE THREAD

**Issue by szmarczak** [Microsoft/vscode#66730]
- VSCode Version:

```
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64
```

- OS Version: Windows 10

![](https://user-images.githubusercontent.com/36894700/51399922-67d2b180-1b47-11e9-9552-5334bb9bd5fb.png)

Steps to Reproduce:

1. Open the Keybindings window
2. Search for the terminal shortcut: <kbd>ctrl</kbd>+<kbd>`</kbd>

**Comment by usernamehw** [comment]
Why are you searching in `Default Keybindings`? It's a read-only document.

**Comment by szmarczak** [comment]
> Why are you searching in Default Keybindings?

Because *there* the default keybinding should be.

> It's a read-only document.

I know it's read-only. Not sure what you mean.

**Comment by usernamehw** [comment]
I don't know what are you trying to do...

Your title says `Cannot override View->Terminal shortcut`. But you are in read-only document.

You highlighted one command in the menu (focus terminal).

Then you are searching for a different command (create new terminal).

Also, there's an info icon in the command. Are you using different keyboard layout?

**Comment by szmarczak** [comment]
> But you are in read-only document.

But I can override shortcuts in my `keybindings.json` file, right? :)

> You highlighted one command in the menu (focus terminal).

Oh, then it should be named so. I thought it just toggles that.

> Then you are searching for a different command (create new terminal).

Fixed the pic in the main post to <kbd>ctrl</kbd>+<kbd>`</kbd>.

**Comment by szmarczak** [comment]
After pressing random keys on my keyboard and looking at the default keybindings file, this is what I've been looking for:

```json
{ "key": "ctrl+j",                "command": "workbench.action.togglePanel" }
```
