### ISSUE TITLE
More advanced right panel / drag n' drop feature

### ISSUE THREAD

**Issue by szmarczak** [Microsoft/vscode#66731]
This image describes it best:

![image](https://user-images.githubusercontent.com/36894700/51394959-e3c6fc80-1b3b-11e9-9cd8-5350e30c8696.png)

**Comment by usernamehw** [comment]
`workbench.action.togglePanelPosition` ?

**Comment by szmarczak** [comment]
> workbench.action.togglePanelPosition ?

Thank you very much <3

Is it possible to do:

![image](https://user-images.githubusercontent.com/36894700/51400967-fc3e1380-1b49-11e9-860b-f6b81e16b3d7.png)

**Comment by szmarczak** [comment]
I'd like to suggest a drag n' drop feature:

![outline](https://user-images.githubusercontent.com/36894700/51401145-5d65e700-1b4a-11e9-9930-e481c8ae4d2e.gif)

**Comment by usernamehw** [comment]
#49923

**Comment by szmarczak** [comment]
Thank you for your help :)
