### ISSUE TITLE
Issue with launch.json args containing Ampersand character

### ISSUE THREAD

**Issue by BryanWallin** [microsoft/vscode#66738]
- VSCode Version: 1.30.1
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.  Have your launch.json file look like this:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug Main Process",
			"type": "node",
			"request": "launch",
			"cwd": "${workspaceRoot}",
			"osx": {
				"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron"
			},
			"windows": {
				"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
			},
			"args": [
				"test://update?v=2&id=4&param=16",
				"arg2"
			],
			"program": "${workspaceRoot}/js/app/main/main.js",
			"protocol": "inspector"
		}
	]
}
```

2.  On Windows (there is no issue on Mac), launch the app using VS Code and check the `process.argv` array.  The fourth parameter is "test://update?v=2", which is incorrect.  There is no fifth parameter (but there should be, and the value should be "arg2").  Anything past the first ampersand character is cut off, even the second argument of "arg2".

I've tried to use:

- "test://update?v=2^&id=4^&param=16",
- "\\"test://update?v=2&id=4&param=16\\"",
- "\\"test://update?v=2^&id=4^&param=16\\"",

but I'm unable to get anything to work.  Is there a way to pass command line arguments containing ampersand characters on Windows?

**Comment by weinand** [comment]
This works fine for me for a simple node.js program, which proves that VS Code does the right thing:
<img width="1369" alt="2019-01-18_21-27-03" src="https://user-images.githubusercontent.com/1898161/51411453-269ec980-1b68-11e9-8276-974808fc62eb.png">

**Comment by BryanWallin** [comment]
That's good to know, thank you for looking into this.  I'll do some more Electron-specific testing and see what I can find.

**Comment by BryanWallin** [comment]
After some more digging, this appears to be an issue with CMD scripts and the ampersand character.  In order to emulate the behavior I was seeing previously, I've created a file `test.cmd` that contains the following script:

`node %*`

It's essentially passing the arguments to node, similar to how the electron.cmd script works.  I've also added a minimal `test.js` file for easy repeatability:

```
console.log(process.argv);

debugger;
```

From the VS Code terminal, I can successfully pass arguments that contain ampersands:

![terminal](https://user-images.githubusercontent.com/7398314/51774359-a45a5c00-20b7-11e9-87d5-31c430ad252b.png)

My `launch.json` configuration looks like:

```
{
	"name": "TEST",
	"type": "node",
	"request": "launch",
	"cwd": "${workspaceRoot}",
	"windows": {
		"runtimeExecutable": "${workspaceRoot}/test.cmd"
	},
	"args": [
		"\"test://update?v=2&id=4&param=16\""
	],
	"program": "${workspaceRoot}/test.js"
}
```

When I run the `TEST` configuration in VS Code, this is the output I see:

![launch](https://user-images.githubusercontent.com/7398314/51775055-09af4c80-20ba-11e9-9678-74dd85a5e26c.png)

It looks like the command that VS Code is running is almost identical to the command I ran earlier in terminal, with the addition of `--inspect-brk=45777`.  The argument is being cut off after the ampersand this time, and there's an extra quote at the beginning.

The only way I can get it to work from the `launch.json` configuration is if I encase the argument in double quotes like so:

```
"args": [
	"\"\"test://update?v=2&id=4&param=16\"\""
],
```

Then, when I run the `TEST` configuration, I see this:

![launchdoublequotes](https://user-images.githubusercontent.com/7398314/51775235-a7a31700-20ba-11e9-8b0a-9a3427529309.PNG)

Obviously, the entire command is now making it through, but there's two extra sets of quotes I don't want.  I can't understand why running the command in terminal directly works, but running it using `launch.json` doesn't.  Does anyone understand what's going on here?

**Comment by bkeevil** [comment]
This issue also happens with the # character

**Comment by weinand** [comment]
Does it make a difference if you configure your launch config to use VS Code's integrated terminal, by adding a `"console": "integratedTerminal"`?

**Comment by BobVul** [comment]
> Does it make a difference if you configure your launch config to use VS Code's integrated terminal, by adding a `"console": "integratedTerminal"`?

I have the same issue, and `integratedTerminal` does not help - I was already using it to work around an earlier debugger attach issue. For the time being I'm just hardcoding the args in the program under test.

**Comment by christine-e-smit** [comment]
I realize that this issue is about a node script, but I had the same problem with python and I found this bug report for the python extension: https://github.com/microsoft/vscode-python/issues/8432. The diagnosis in that ticket was that the URL needs to be enclosed in quotes or escaped properly. I'm thinking that actually that was the problem here, too. 

I can't tell if @weinand actually inspected the argument passed into his node script or just looked at the command that was executed. For my python script, the full URL was indeed part of the command Visual Studio Code executed, but everything after the ampersand was missing inside python.

Like @BryanWallin, I could not find a work around.

**Comment by christine-e-smit** [comment]
Work around for URLs: use semicolons instead of ampersands as the separator.
