### ISSUE TITLE
Opened Editors: moving an editor leaves duplicated close action active

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6674]
![untitled](https://cloud.githubusercontent.com/assets/900690/15475724/be60d5ce-210b-11e6-9d00-336092f2c5ae.gif)

**Comment by isidorn** [comment]
In this case the monaco tree row still thinks it has `:hover` and this rule gets applied

`.explorer-viewlet .explorer-open-editors .monaco-tree .monaco-tree-row:hover > .content .monaco-action-bar: {
visibility: visible
}`


@joaomoreno any tips on what might be going wrong here? Why would an html element think it is still being hovered over while that is not the case

**Comment by joaomoreno** [comment]
Chromium rendering issue.

**Comment by isidorn** [comment]
Then nothing that can be done here

**Comment by isidorn** [comment]
@bpasero as a workaround for the bug I can refresh the elements on done drag n drop - but not sure if we want to go down that path - especially since I think the bug is not severe

**Comment by bpasero** [comment]
Nah its ok.
