### ISSUE TITLE
Can't drag and drop from VS Code to Mac folder

### ISSUE THREAD

**Issue by Andres-Escobar** [Microsoft/vscode#66747]
Just for today, I don't know...can't drag and drop a file from the "Open Editors" to any of the folders (in macOS); I just can do that but from the folder structure to a folder, this is in the insiders version.

**Comment by isidorn** [comment]
This is on me. I re-wrote the open editors drag and drop to use the list.
@joaomoreno let me investigate first

**Comment by isidorn** [comment]
@Andres-Escobar thanks for using vscode insiders and for filling this issue.
Just pushed a fix, so this should be good in tomorrow's vscode insiders. Let us know if it works for you than.

**Comment by Andres-Escobar** [comment]
Thanks!!! I'll waiting for the update and then I'll let you know.

**Comment by Andres-Escobar** [comment]
I just installed the update today, and it works!, thanks for fixing this bug :)

**Comment by isidorn** [comment]
Great, adding verified label
