### ISSUE TITLE
Support grunt task argument

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/vscode#66748]
I'd like to provide my grunt tasks with a single argument but the VSCode task system doesn't support arguments for grunt tasks. I was shocked to discover this because I rarely have grunt tasks without arguments.

I can of course work around this issue by using the "shell" task type to run grunt with arguments.
Here's [that workaround described on StackOverflow](https://stackoverflow.com/a/49361745/576153).

**Comment by alexr00** [comment]
Starting pointer: https://github.com/Microsoft/vscode/blob/master/extensions/grunt/src/main.ts#L68

**Comment by sohailrajdev97** [comment]
@alexr00, I would like to work on this. Can I start if no one else is on it ?

**Comment by alexr00** [comment]
@sohailrajdev97 thank you, go for it! If you could make a sample repo to test out your change and link it here when you make a PR that would help me review your PR faster :)

**Comment by alexr00** [comment]
To verify, use the [nice sample repo](https://github.com/sohailrajdev97/grunt-sandbox) from the PR to test.
