### ISSUE TITLE
Allow to use `vscode.open` from `keybindings.json`

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#66744]
@jrieken, It appears in autocomplete of `command` in `keybindings.json`. When invoked - there's an error:

> Cannot read property 'scheme' of undefined

Meaning - it doesn't make sense to execute it without `args`. Cannot find what to pass to make it work. Supposedly Uri with `scheme`, `authority`, `path`, `query`, `fragment`. But I fail every time.

**Comment by jrieken** [comment]
@bpasero I guess it needs a simple check and more graceful handling, like all commands that expect argument but that are called with them

**Comment by bpasero** [comment]
@usernamehw you want to associate a keybinding to always open the same file, is that the use case?

**Comment by usernamehw** [comment]
@bpasero, No, I'm using `vscode.openFolder` to open files and folders. This is for PR https://github.com/Microsoft/vscode/pull/66458.

Is it possible to remove it (and similar not working) from keybindings autocomplete?

**Comment by bpasero** [comment]
@usernamehw I do not think we should remove it from the keybindings suggestions, basically any command could get an argument. I would accept a PR to make it work if you are interested.

**Comment by jrieken** [comment]
Yeah, that's how it could work. Whatever is defined in `args` is being passed to the command. For URIs some parsing is required but all the details are up to your command implementation
