### ISSUE TITLE
Make `vscode.open`-command real API

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#66741]
We have the `vscode.open`-command and it's very popular. That makes it a candidate to be lifted into a 'real' API function, thereby being easy to discover and easy to document.

**Comment by usernamehw** [comment]
Can these commands accept `args` in `keybindings.json`: `vscode.open` & `vscode.diff`?

**Comment by jrieken** [comment]
@usernamehw I don't understand. This is about turning a command into an api-function

**Comment by usernamehw** [comment]
@jrieken it appears in autocomplete of `command` in `keybindings.json`. When invoked - there's an error:

> Cannot read property 'scheme' of undefined

So, it doesn't make sense to execute it without `args`. Cannot find what to pass to make it work. Supposedly Uri with `scheme`, `authority`, `path`, `query`, `fragment`. But I fail every time.

**Comment by jrieken** [comment]
Yes, that is all correct but has nothing to do with this issue. Please let's keep it clean and feel free to create a new, separate issue. Thanks

**Comment by jrieken** [comment]
@bpasero The existing command takes some arguments to control some of the workbench behaviour. Do you know why that was added?

**Comment by bpasero** [comment]
@jrieken are you referring to `vscode.TextDocumentShowOptions`?

**Comment by jrieken** [comment]
Yeah, basically this: https://github.com/Microsoft/vscode/blob/dc0e64414e37f8d89ae7ef3b40ce0cb0a949911d/src/vs/workbench/api/node/apiCommands.ts#L83-L90

**Comment by jrieken** [comment]
Given #66797 we can make this use electron's `openItem` (https://electronjs.org/docs/api/shell#shellopenitemfullpath) behind the scenes. That should be the best option, allowing to open urls but also other apps.

**Comment by jrieken** [comment]
Actually moved this onto [`openExternal`](https://electronjs.org/docs/api/shell#shellopenexternalurl-options-callback) with the option to also support `openItem` in the future.

**Comment by jrieken** [comment]
This is the API: https://github.com/Microsoft/vscode/blob/0443e4c95d1a1d473ee5c8cf512de5408af7e034/src/vs/vscode.d.ts#L5925-L5935
