### ISSUE TITLE
Please add a new button to the Debug toolbar to get to the current line while debugging

### ISSUE THREAD

**Issue by Zephilim** [Microsoft/vscode#66740]
Whilst debugging there appears to be no way of getting back to the current line of execution which is a problem if you have browsed other files and now don't know where the current execution point is. Seems to be a glaring ommision. If I remember rightly, the full blown Visual Studio does indeed have a button the gets back to the current execution line. Currently, the only way I know how to do this is to hit either step-in, step-out or step-over button, but doing so may not be possible; ie, you may invoke an exception that you're currently trying to fix.

**Comment by weinand** [comment]
clicking on the top stack frame in the callstack view brings you back to the current line.
