### ISSUE TITLE
Add option to never get asked about NPS survey

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#66753]
Per feedback we should add option to never get asked about NPS survey. 

Today we have an option provided by the general notification system, but it's not very clear.

![image](https://user-images.githubusercontent.com/173559/51415858-254fab80-1b2c-11e9-85c8-e6cfcde6da61.png)

![image](https://user-images.githubusercontent.com/173559/51415864-28e33280-1b2c-11e9-8f3d-832dcea8d1ae.png)

**Proposal:**
Add "Never again" action to the survey notification itself.

**Comment by bpasero** [comment]
@auchenberg I pushed a change to make the action show up prominently as primary button, however I left the wording "Don's Show Again", is that ok?

**Comment by auchenberg** [comment]
@bpasero Yeah, that seems to follow our standard pattern, right? If so, all good.
