### ISSUE TITLE
Alt key captured by menu bar

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/vscode#66756]
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic (Ubuntu 18.04.1 LTS)

I have a somewhat unique setup where I use AutoKey to convert Alt + Left and Alt + Right presses to output Ctrl + Left and Ctrl + Right since these commands will jump the cursor by word anywhere in the OS. However, with VS Code specifically, I run into the problem where if I try to press Alt first, then Left, VS Code will think that I tapped Alt, and change the focus to the menubar. If I set menubar to hidden, then it will work as I intended.

Could you consider adding an option to disable tapping Alt from focusing on the menubar? I've already disabled Enable Menu Bar Mnemonics in the settings, but that doesn't prevent the Alt key from focusing the menu bar. I see that there's a related bug here: https://github.com/Microsoft/vscode/issues/41070, but as of v1.30.2, I still have this problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
for clarification, your key sequence is Alt Down, Left Arrow Down, Left Arrow Up, Alt Key Up? Or are you tapping alt followed by tapping left?

**Comment by sbatten** [comment]
Is AHK doing any other manipulation with the alt key? The menu bar is set to focus only on alt key up. And it shouldn't focus unless that alt key press is clean (no other keys pressed in between).

**Comment by WesleyYue** [comment]
Actually sorry, you're correct. I just tested it again, and the actual sequence is: Alt Down, Left Arrow Down, focus captured by menu bar. So I imagine what is happening is that AutoKey sees the chord, then proceeds to capture it and output Ctrl + Left. At the same time, since AutoKey captured the Alt+Left combo, VS Code thinks the Alt key is released. The focus proceeds to go to the menu bar and the Ctrl+Left output by AutoKey does nothing since the cursor is focused in the menubar.

**Comment by WesleyYue** [comment]
Is there any additional information I could provide to be of more help?

**Comment by Via-profit** [comment]
I can confirm that bug. I`m using left alt + left shift to change typing lagnuage. Code always loosing focus from editing file and put if on menu bar. It`s very annoying, because i should change typing language 30-50 times per hour. Ubuntu 18.04.2 LTS. Code version is 1.31.1

**Comment by rightaway** [comment]
alt is hardcoded to toggle the menu bar, but it should instead be be mapped to `workbench.action.toggleMenuBar` so that we can remove the mapping if we don't want alt to toggle the menu bar.

Otherwise the menu bar pops up when I don't want it to from various keyboard shortcuts. For example when I hold down alt for fast scrolling, I'll get the menu bar popping up every time I release the alt key.

**Comment by sbatten** [comment]
Use `window.customMenuBarAltFocus` setting as false to prevent menubar focus from alt.

**Comment by rightaway** [comment]
@sbatten setting window.customMenuBarAltFocus to false doesn't do anything if you have a `native` window style. So it's still a problem. Can you please reopen this issue?

**Comment by sbatten** [comment]
@rightaway unfortunately we have no way of disabling this in the `native` case as electron does not provide such API.

/cc @deepak1556

**Comment by rightaway** [comment]
alt is hardcoded to toggle the menu bar, but can't it instead be be mapped to workbench.action.toggleMenuBar so that we can remove the mapping if we don't want alt to toggle the menu bar? I think it's a useful feature request for all of us who are using `native`.
