### ISSUE TITLE
ALT+SHIFT+ARROW KEYS doesn't work

### ISSUE THREAD

**Issue by MattEsquivel** [microsoft/vscode#66751]
Issue Type: <b>Bug</b>

I am returning to the original Visual Studio because VS Code is missing ALT+SHIFT+ARROW keys. this is critical when manipulating a lot of code at once.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.18293

**Comment by usernamehw** [comment]
`ALT+SHIFT+ARROW`. What's it doing?

**Comment by MattEsquivel** [comment]
It allows you to make a rectangular selection. I use this to insert spaces to many lines in a row. Rename blocks of variables in code. Produce ascii art comments. And a lot more.

**Comment by usernamehw** [comment]
Like middle mouse drag?

**Comment by MattEsquivel** [comment]
Yes. like that. Thank you for pointing that out, I was not aware you could do that. Please add keyboard support for that as well.

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>← →</kbd>

**Comment by MattEsquivel** [comment]
Thanks for pointing that out. 
Wow, that is a lot of keys to press at once. CTRL + SHIFT should be reserved for jumping selection by whole words though...

**Comment by alexandrudima** [comment]
Keybindings can be customized to move them to shift+alt+arrows
