### ISSUE TITLE
FileSystemProvider proposed read/write api: does it work?

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#66759]
- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Implement a custom [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), including all four lower-level functions `open`,  `close`,`read`, `write` in the proposed api (introduced in fa5922bd304b3d28ee022d4ea814c4a2a67c6766)
2. `open` is called as expected, instead of the current `readFile`
3. `read` is called with pos=0 as expected, but pushing the correct bytes into the provided `data` arg and returning `bytesWritten` results in all zero-bytes (with len=bytesWritten) sent back to the editor!

Can someone kick the tires and make sure this works?  I don't see any public demos in the samples repo.

**Comment by jrieken** [comment]
Yeah, it actually does work... I will push a fix
