### ISSUE TITLE
Failed to Update Vs Code

### ISSUE THREAD

**Issue by shyam2520** [Microsoft/vscode#66762]
[vscode-inno-updater-1547875335.log](https://github.com/Microsoft/vscode/files/2775191/vscode-inno-updater-1547875335.log)

**Comment by joaomoreno** [comment]
Is Code installed in `C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code`?

**Comment by shyam2520** [comment]
No it is installed in d drive

**Comment by shyam2520** [comment]
VSCodeUserSetup-x64-1.30.2



Sent from Mail for Windows 10

**Comment by joaomoreno** [comment]
If you uninstall and reinstall in D: does the issue happen again?

**Comment by shyam2520** [comment]
Some Times it happens but two days ago I reinstalled it now it is working fine with the latest update . I don’t know if it will be able to update  again with giving problems.
Sent from Mail for Windows 10

**Comment by joaomoreno** [comment]
Alright, let me know if it comes back.

**Comment by shyam2520** [comment]
Thanks a lot for your help
