### ISSUE TITLE
Unable to look at other files when debugger has hit a breakpoint when debugging C project

### ISSUE THREAD

**Issue by aakre** [Microsoft/vscode#66769]
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

After updating to the latest version (at least for my system) debugging sessions has become tedious. Whenever a breakpoint is hit, I am no longer able to open and look at other files. If I open another file, the editor automatically switch back to the breakpoint. This was not the case with previous versions and is really annoying. It is possible to split the editor when a breakpoint is hit and look at the file in split view, but that should really not be necessary. 

Steps to Reproduce:

1. Start a debugging session for a C project
2. Ensure you have one editor open (no split-screen)
3. Set a breakpoint and wait for it to be hit
4. Open another file. Editor will automatically jump back to the breakpoint

Does this issue occur when all extensions are disabled?: Yes

**Comment by aakre** [comment]
@isidorn I can confirm it is working as intended with the insiders build

**Comment by isidorn** [comment]
Great thanks. Closing than.
@aakre if I were you I would make sure that not one of your vscode extensions is breaking you. So doulbe check your extensions.

**Comment by aakre** [comment]
ok, thanks!
I really appreciate the quick response from you guys!
