### ISSUE TITLE
Add a shortlex sort order to the file explorer

### ISSUE THREAD

**Issue by leidegre** [Microsoft/vscode#66768]
I just realized the sort order used in VS Code for file explorer is different than for example the Windows File Explorer.

![image](https://user-images.githubusercontent.com/63085/51424524-52a16580-1bcf-11e9-965e-60c746e495d3.png)

This caught me by surprise. The reason for this is that the file name comparison function doesn't take into account the length of the file name. Under [shortlex](https://en.wikipedia.org/wiki/Shortlex_order) rules you would consider a file name of shorter length to be smaller than a file name of longer length.

I like the default layout with folders before files but I would like there to be an option to enable shortlex sorting. I think it's common enough to even argue that it should have been the default it's just an easily overlooked fact.

For example, this is what I get if I traverse the files using the `dir /b` command.

```
C:\Users\leidegre\Source\tessin\tcm\tcm-backend\src\tessin\ddd>dir /b
aggregate.go
aggregate_registry.go
event.go
event_registry.go
README.md
rehydration.go
```

This is exactly the way the files are returned from the file system, in this case NTFS. I could even argue that there is a miniscule benefit from having similar sort in the file explorer view as the files are handed to you by the underlying file system APIs (even if this is mostly a edge case on Windows).

I'm no expert on the VS Code codebase but I would presume that some change to these [functions](https://github.com/Microsoft/vscode/blob/c1d4ea9d89887e58ecae1b10f87c55ea8c42f96f/src/vs/base/common/comparers.ts#L16-L54) would be necessary so that they take length into consideration.

This could either be made as an toggle option, on top of existing sort rules, or it could just be made as a feature enhancement as I don't know for a fact, if the current file sort order was intended to not explicitly use shortlex rules or not. (I obviously think they should 😄)

**Comment by leidegre** [comment]
I'm going to assume it's this one. https://github.com/Microsoft/vscode/issues/27759

**Comment by isidorn** [comment]
Yeah. There's also one about more sorting in the explorer.
Search for issues tagged with file explorer and feature request.
