### ISSUE TITLE
[less] support merge syntax (`+`, '+_`)

### ISSUE THREAD

**Issue by noommii** [microsoft/vscode#66764]
Issue Type: <b>Feature Request</b>

Unknown property: 'box-shadow+'
Unknown property: 'transform+_'

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
Can you add a more complete example?

**Comment by dmgawel** [comment]
@aeschli this syntax is a "merge" feature of LESS: http://lesscss.org/features/#merge-feature
