### ISSUE TITLE
Open .profile under ubuntu then every time it shows ,can not remove it at all

### ISSUE THREAD

**Issue by elliottzhou** [Microsoft/vscode#66765]
Once I open etc/sXXX/.profile to add env variable(with root), Then every time I open vscode, this page shows whatever I do...
![screenshot from 2019-01-19 00-35-52](https://user-images.githubusercontent.com/39450973/51422755-4642eb80-1b82-11e9-8ddb-58503f832e4d.png)

**Comment by bpasero** [comment]
@elliottzhou the file is dirty and thus will reopen. You have to close without saving or save in order to get out of that.
