### ISSUE TITLE
typing assert.anything inside js files will result in MSFIDOCredentialAssertion.anything

### ISSUE THREAD

**Issue by DevotionGeo** [Microsoft/vscode#66766]
Issue Type: <b>Bug</b>

This problem is there from many versions. To know how annoying it can be, just try to type `assert.anything` inside a `js` file. You don't even need to press `tab` to autocomplete `assert` into `MSFIDOCredentialAssertion.`, as soon as you press the `.` key your `assert` will dissappear and `MSFIDOCredentialAssertion` will appear in its place.

![ezgif-1-e37a8d622dce](https://user-images.githubusercontent.com/7348138/51424136-96a26380-1beb-11e9-8d2e-f61fade49373.gif)

This is so annoying that several times I thought of leaving VSCode altogether, even if it's the best code editor in my opinion. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz (4 x 1491)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.71GB (1.77GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.8
Bookmarks|ale|10.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.7.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.6
theme-macos-classic|hua|1.1.1
elixir-ls|Jak|0.2.24
theme-dark-plus-contrast|k3a|0.1.101
vscode-language-babel|mgm|0.0.21
Go|ms-|0.8.0
vetur|oct|0.14.5
advanced-new-file|pat|1.2.0
vscode-css-peek|pra|2.2.0
LiveServer|rit|5.3.1
vscode-icons|rob|8.0.0
elm|sbr|0.25.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.4
code-spell-checker|str|1.6.10
ayu|tea|0.17.0
vscode-status-bar-format-toggle|tom|1.4.0
vim|vsc|1.0.2
vscode-react-native|vsm|0.8.0
JavaScriptSnippets|xab|1.7.2

(41 theme extensions excluded)

</details>

**Comment by DevotionGeo** [comment]
Something similar happened again when I was trying to type `bar()`. As soon as I typed `(` after bar it changed to `BarProp()`.

![ezgif-1-a9bec7bbab09](https://user-images.githubusercontent.com/7348138/51424836-4a5c2100-1bf5-11e9-8605-9c86eafa40eb.gif)


I don't know what are these `MSFIDOCredentialAssertion` or `BarProp()` or a number of other things which automatically replace things you intended to type, but the only solution to this all in my opinion is to make auto-completion triggered only by tab key, because in the above case it triggered with `.` key and in the second case it triggered with `(` key.

**Comment by jrieken** [comment]
Yeah, that because of this setting: `editor.acceptSuggestionOnCommitCharacter`.Turn it to `false` and you'll be happy

**Comment by mikemaccana** [comment]
@jrieken Maybe it's a bad default? How many JS users wish to use `MSFIDOCredentialAssertion`?
