### ISSUE TITLE
VSCode keeping .pyd files locked open

### ISSUE THREAD

**Issue by softwareCobbler** [Microsoft/vscode#66778]
Issue Type: <b>Bug</b>

Developing a Python module in C, compiling to a DLL (simply renamed to .PYD) with MSVS Community 2015. When I have a Python file open in VSCode that references the module I am developing (via `import devmoduleX`), VSCode keeps the DLL file locked and MSVS cannot rebuild the DLL. Closing the Python file does not free the DLL, VSCode must be totally closed, the DLL rebuilt, and VSCode reopened.

quick update: this only occurs after autocomplete has been streamed in at least once (just opening the offending Python file is not enough, one must write `devmoduleX.` and the autocomplete menu must populate).

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (27.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
java|red|0.37.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.13.0

</details>

**Comment by softwareCobbler** [comment]
Yes, disabling the Python extension fixes this problem, but then I can't use autocomplete, either. No biggie, same solution as earlier, just reload the IDE.

**Comment by sandy081** [comment]
Ok please file an issue against Python Extension.
