### ISSUE TITLE
Autocomplete quotes missing on null languages selected.

### ISSUE THREAD

**Issue by jfly28** [microsoft/vscode#66773]
Using version 1.30.2 (1.30.2)
I will reference this issue first to give you an idea of my problem (Let me configure whether to autocomplete single quotes in comments #8850). The problem I am having is that in another text editor I can single or double quote with "leading" whitespace it knows to provide a closing quote and cursor inside(center) the two. When I'm in vscode on a blank document and I have NOT defined the language it doesn't know I need a set of quotes to make a 'string' or closing. I understand the issue in #8850 where it was behaving inside a comment. The other programs handle it differently when you type a quote next to a character t knows an apostrophe is needed not double quotes maybe that is the solutions, but comments are language specific #, //, <!--, so the program can't know what language to assign but, quotes are are not and is common as strings types in many languages and should provide a closing... when I type a bracket or paren with "leading" white space it behaves properly. Why not with quotes?

**Comment by jfly28** [comment]
I will reference this issue first to give you an idea of my problem (Let me configure whether to autocomplete single quotes in comments #8850). The problem I am having is that in another text editor I can single or double quote with "leading" whitespace it knows to provide a closing quote and cursor inside(center) the two. When I'm in vscode on a blank document and I have NOT defined the language it doesn't know I need a set of quotes to make a 'string' or closing. I understand the issue in #8850 where it was behaving inside a comment. The other programs handle it differently when you type a quote next to a character t knows an apostrophe is needed not double quotes maybe that is the solutions, but comments are language specific #, //, <!--, so the program can't know what language to assign but, quotes are are not and is common as strings types in many languages and should provide a closing... when I type a bracket or paren with "leading" white space I should get a closing paren or bracket and cursor in center. Why not quotes?

**Comment by jfly28** [comment]
Also want to add once this problem is fixed, don't forget to include this behavior: if I add a quote inside empty brackets or parenthesis then I should get closing quotes, the program should understand that empty or white space always provide quotes... but not duplicate quotes so if I type the apostrophe key twice then I shouldn't get another set of quotes nested inside, the cursor should overwrite the trailing quote, and I would end on the other side of the quotes. hope this helps

**Comment by alexandrudima** [comment]
@jfly28 Are you using plain text? We currently do not auto-close `'` or `"` in plain text files. If you create a file, like `example.c` or `example.js`, then we will detect the language from the filename and auto-close `'` or `"`. This depends from one file to another because it depends from one programming language to another, and some programming languages use `'` to encompass strings, while others do not.
