### ISSUE TITLE
Search tab index

### ISSUE THREAD

**Issue by umpirsky** [Microsoft/vscode#66770]
My usual use case for search:

1. `Ctrl + Shift + F`
1. Fill in search query.
1. Press `Tab` 5 times.
1. Fill in files to include (usually `src/**/*.yml` or `src/**/*.php`).

As you can see 3. is the problem, I (and I guess many users) rarely change casing/regex settings, but often change files to include.

Tab index should be changed to focus search query, then files to include...

All editors/ides I used before work like that, including Atom.

**Comment by roblourens** [comment]
I recommend using cmd+up/down to move between the inputs.

**Comment by umpirsky** [comment]
That works, thanks!
