### ISSUE TITLE
Cannot debug extension (unknown request 'launchVSCode').

### ISSUE THREAD

**Issue by HelloXZX** [microsoft/vscode#66774]
- VSCode Version: 1.30.2
- OS Version: MacOS 10.14.2 

Steps to Reproduce:

1. Create a new own extension.
2. Debug the extension. Toast 'Cannot debug extension (unknown request 'launchVSCode').'

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What version of node-debug are you using? It should be 1.30.3:
<img width="435" alt="2019-01-19_19-18-27" src="https://user-images.githubusercontent.com/1898161/51430685-11d13d00-1c1f-11e9-98dc-9bae5c44906b.png">

**Comment by ludorival** [comment]
Thanks @weinand.
My node debug version is 1.31.3.
Can I set the correct version on my side ?

**Comment by ludorival** [comment]
Forget it I see where

**Comment by ludorival** [comment]
Thanks @weinand , your workaround works for me, but I had to disable the auto updating extensions to not have the latest version.

**Comment by roblourens** [comment]
Done. @ludorival does `~/.vscode/extensions/ms-vscode.node-debug2-1.31.3` exist? Don't know how that would have happened...

**Comment by weinand** [comment]
@roblourens there seems to be a bug in automatic extension updates: built-in extensions should not be automatically upgraded.

@sandy081 how could that happen?

**Comment by ludorival** [comment]
@roblourens yes it exits for me.

**Comment by daimor** [comment]
Faced the same issue, in my case I also had ms-vscode.node-debug2 version 1.31.3
Installing some previous version was not available, while 1.31.0 not listed 
install previous version when failed offered to download and install manually
manual install failed due to dependencies from [React Native Tools](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native)
After removing this extension, I managed to install previous version of Node debug. After reload debug extensions finally started to work. And Node Debug extension disappeared from @installed but visible in @builtin as version 1.30.4

So, looks like an error because solving extensionDependencies for built-in extensions.  
```JSON
"extensionDependencies": [
		"ms-vscode.node-debug2"
	]
```
[vscode-react-native](https://github.com/Microsoft/vscode-react-native/blob/d638bd45b3b13d9b5e6d391af2ec5c15cce44aec/package.json#L570)

**Comment by alexeyvax** [comment]
Hi everyone!
I have the same issue.

- VSCode Version: 1.30.2
- OS Version: Linux x64 4.15.0-43-generic

Something broken on node debug 1.3.3 version. Extension doesn't launch.
But when I rolled back to version node debug 1.3.2 version. Extension launched as expected.

**Comment by weinand** [comment]
@alexeyvax when using VSCode Version: 1.30.2 you should not be able use a "node debug 1.31.3". 

Did you use a manually installed version of "node debug" before this happened?

**Comment by alexeyvax** [comment]
hmm... It's strange. I don't use manually installed packages, only automatically installed. 
Here my extensions list: 
![selection_083](https://user-images.githubusercontent.com/22244018/51798612-7f382b80-2226-11e9-9b6a-f7d10c1d6217.png)

If I try to launch my extension, I'll get error(this issue), but if I use `node debug 1.31.2`, my extension will launch as expected.
![selection_084](https://user-images.githubusercontent.com/22244018/51798697-d5599e80-2227-11e9-9f9a-945044f823f7.png)

**Comment by wongjiahau** [comment]
Downgrading Node Debug to 1.31.2 works for me.

**Comment by sandy081** [comment]
Disabled such support for built in extensions - https://github.com/Microsoft/vscode/issues/67629

**Comment by roblourens** [comment]
I see it enabled for "node debug" but not "node debug (legacy)"...

**Comment by sandy081** [comment]
I do not see it for either of the extensions. Can you check if you have it in user extensions folder?

**Comment by roblourens** [comment]
I'm confused, now I am not seeing it enabled for either.

**Comment by roblourens** [comment]
You should delete the extension from `~/.vscode/extensions/ms-vscode.node-debug2...`

**Comment by akrantz** [comment]
@roblourens OK, that fixed it for me. Thanks.

**Comment by brandondrew** [comment]
@roblourens  I deleted that directory, but I still have the same problem.  Any ideas?

**Comment by sandy081** [comment]
Those who are seeing this error, is it possible to let us know if you have installed the node debug extension manually by getting it from marketplace directly or through a VSIX?

**Comment by daimor** [comment]
got this error without manual installing this debug extensions, now or any time ago.
After uninstalling some of extensions, and reload I got it worked, without manual installing previous version.

**Comment by akrantz** [comment]
I did not do anything manually to get the extension. I think it got installed indirectly somehow.

**Comment by sandy081** [comment]
Strange, May I know if you have an extension installed that sync extensions for eg., Sync Settings extension?

**Comment by sandy081** [comment]
Only way this can happen is to either

- Manually install the extension using VSIX or from Command Line or
- If there exists an extension that installs it for synchronising extensions for example.

I can block the CLI and have only VSIX way

**Comment by akrantz** [comment]
I don't have any extensions installed that sync extensions.

**Comment by brandondrew** [comment]
@sandy081 I can second what @daimor said: I didn't install this manually, but it seems to have been a dependency of React Native Tools (vsmobile.vscode-react-native).  I disabled React Native Tools in order to remove the offending version of Node Debug.

**Comment by sandy081** [comment]
We are planning to implement updates for built in extensions which can fix all such reported behaviours - https://github.com/Microsoft/vscode/issues/68410

**Comment by sandy081** [comment]
Please let me know if users are still facing this issue? As mentioned, I see this can happen only if built in extension got installed manually or by another extension. So I would close this issue as I do not have any plan of action. It would be great if someone who repro this can provide steps.
