### ISSUE TITLE
XML syntax definition problem

### ISSUE THREAD

**Issue by omochi** [Microsoft/vscode#66776]
I may found bug of syntax.

https://github.com/Microsoft/vscode/blob/10a1d2a50a2882f5ae85bdb51eb04d3064fb9de9/extensions/xml/syntaxes/xml.tmLanguage.json#L354-L363

It should be:

```
 { 
 	"begin": "<%--", 
 	"captures": { 
 		"0": { 
 			"name": "punctuation.definition.comment.xml" 
 		}
	}, 
 	"end": "--%>", 
 	"name": "comment.block.xml"  
 }, 
```

**Comment by alexr00** [comment]
This issue was moved to atom/language-xml#96

**Comment by alexr00** [comment]
We get our grammars from the community. I moved this issue to the repo that owns the grammar.
