### ISSUE TITLE
VSCode is very slow when opening these files

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6677]
From @neilsustc https://github.com/Microsoft/vscode/issues/1001#issuecomment-220302217

- VSCode Version: v1.1.1
- OS Version: 10 pro insider preview build 14342

I can provide 2 versions of that [json file](https://gist.github.com/neilsustc/eaa47016ae8fd792f60c55608f08e5e7) for test

Steps:
* save & open linked files
* interact with VSCode
* observe it is slow/lagging

**Comment by alexandrudima** [comment]
After the change in ca2ca08c63c88f7c0bc2735a37a97ff3b8f600fc that limits the ammount of text we sync to the `<textarea>` these files are no longer slow for me.

**Comment by mjkkirschner** [comment]
not sure if it's okay to comment on a closed issue, :
but I am encountering a similar issue on VS code 1.3.1 with a large single line JSON blob in a typescript file, the text is not highlighted, but attempting to click on a curly brace near the end of the text makes the window non responsive.

**Comment by dbaeumer** [comment]
Moving back to @alexandrudima do comment.

**Comment by alexandrudima** [comment]
@mjkkirschner Please create a new issue with the specific file or a similar file that triggers the freeze.
