### ISSUE TITLE
Can't run pacmd from VS Code terminal

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode#66779]
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.04.1

Steps to Reproduce:

1. Run `pacmd list-cards` in the VS Code terminal.

Does this issue occur when all extensions are disabled?: Yes

---

`pacmd list-cards` produces the output `No PulseAudio daemon running, or not running as session daemon.` when run in the VS Code terminal. From a normal terminal, it produces the usual output. The issue here of course isn't pacmd specifically, it's that the VS Code terminal doesn't behave like an ordinary terminal window, which it should.

**Comment by Tyriar** [comment]
How is the PulseAudio daemon normally run?

**Comment by geajack** [comment]
@Tyriar Ordinarily I would just enter `pacmd list-cards` in the terminal with no further ado. If there's more complicated stuff happening behind the scenes, I'm not aware of it.

**Comment by Tyriar** [comment]
@geajack I'm guessing installing pacmd installs a script somewhere that runs the daemon when you launch your terminal.

Do you run your normal terminals as login shells or non-login shells? This is typically a setting in your terminal. Can you also share your VS Code settings file?

**Comment by geajack** [comment]
@Tyriar Don't really know how to answer your question about login shells and non login shells. I get this behavior with the default Ubuntu terminal with no customizations (as far as I know). I get the same erroneous behavior in VS Code with an empty settings file.

**Comment by Tyriar** [comment]
@geajack check your external terminal settings, the default for vscode on Ubuntu is to run a 'non-login' shell which runs `~/.bashrc` when it's launched. `~/.bash_profile` (login shell) gets run when you log into the system.

**Comment by geajack** [comment]
@Tyriar Can't see anything in `~/.profile` that looks like it's setting up `pacmd`. Is there a VS Code setting I can use to start the terminal as a login shell to see if that works?

**Comment by vhsw** [comment]
I run into this issue and I think there's something to do with snap
With a snap package of vscode, I cannot access pulseaudio daemon, but with the vscode, installed with .deb package pactl and pacmd works fine
![Screenshot from 2019-10-04 23-09-02](https://user-images.githubusercontent.com/7099976/66236993-8d671180-e6fc-11e9-8d29-db577acb7d1d.png)

**Comment by vhsw** [comment]
I've built minimal snap for testing and got the same issue:

```yaml
name: min-snap
base: core18
version: '0.1'
summary: blah
description: blah-blah

grade: stable
confinement: classic

parts:
  dummy:
    plugin: nil

apps:
  sh:
    command: sh pactl stat
```
```console
➜ /snap/bin/min-snap.sh -c "/usr/bin/pactl stat"
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

➜ /snap/bin/min-snap.sh -c "/usr/bin/pacmd list-cards"
No PulseAudio daemon running, or not running as session daemon.
```
So it's maybe not a vscode issue at all

**Comment by Tyriar** [comment]
Please report this to the snap team.

**Comment by fc92** [comment]
> I've built minimal snap for testing and got the same issue:
> 
> ```yaml
> name: min-snap
> base: core18
> version: '0.1'
> summary: blah
> description: blah-blah
> 
> grade: stable
> confinement: classic
> 
> parts:
>   dummy:
>     plugin: nil
> 
> apps:
>   sh:
>     command: sh
> ```
> 
> ```
> ➜ /snap/bin/min-snap.sh -c "/usr/bin/pactl stat"
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused
> 
> ➜ /snap/bin/min-snap.sh -c "/usr/bin/pacmd list-cards"
> No PulseAudio daemon running, or not running as session daemon.
> ```
> 
> So it's maybe not a vscode issue at all

Reinstalling VS Code from .deb package instead of snap worked for me. Ubuntu 20.04.
