### ISSUE TITLE
Allow extension to provide information about the current logic line range

### ISSUE THREAD

**Issue by APerricone** [microsoft/vscode#66783]
In the code often a statement is more than one line, for example in c++:
![image](https://user-images.githubusercontent.com/22457168/51431276-e8b4aa80-1c26-11e9-9a83-0c953daf3587.png)
or in visual basic:
![image](https://user-images.githubusercontent.com/22457168/51431284-ff5b0180-1c26-11e9-825a-5ad9be4f760e.png)
what I propose is to the extensions to show start and end of current line/statement:
![image](https://user-images.githubusercontent.com/22457168/51431270-d175bd00-1c26-11e9-9417-f1cb63eb19f8.png)
![image](https://user-images.githubusercontent.com/22457168/51431308-4943e780-1c27-11e9-87b4-e5549fde041a.png)

**Comment by sandy081** [comment]
Please file the request against the extension in which you need this feature.

**Comment by APerricone** [comment]
is it possible for an extension define it? I don't think so.
then what could do an extension author?

**Comment by sandy081** [comment]
Hmm.. Not sure exactly. Leaving it to @alexandrudima to answer

**Comment by alexandrudima** [comment]
Hm, it is an interesting thought... Today, the current line highlight only highlights the view line (the one ending with `\n` or the wrapped line when wrapping is on)... I believe what you describe could be implemented from an extension by using our text editor decoration API (`createTextEditorDecorationType`).

**Comment by APerricone** [comment]
I think the wrapped line case does not work 
![image](https://user-images.githubusercontent.com/22457168/52521709-5e86c180-2c7b-11e9-813b-2ce422e8a1f1.png)
