### ISSUE TITLE
Not Reporting Problems from Extension

### ISSUE THREAD

**Issue by kmccmk9** [Microsoft/vscode#66782]
Issue Type: <b>Bug</b>

Affects Insider and Non-Insider build

<b>Steps:</b>

- Have a working Go Lang setup
- Install the Go extension for VSCode
- Install Go-MetaLinter and Go-NameCheck
- Change workplace settings to use the go-metalinter as linter
- Edit workplace settings.json to match
```
{
    "go.lintTool": "gometalinter",
    "go.lintFlags": ["--config=.gometalinter.json", "."]
}
```
- Create a .gometalinter.json file as below
```
{
    "Enable": ["go-namecheck"],
    "Aggregate": false,
    "Linters": {
        "dupl": 
        {
            "Command": "dupl",
            "IsFast": true,
            "Pattern": "(?P<path>.*\\.go)\\:(?P<line>[0-9]*\\-[0-9]*)\\:(?P<message>.*\\:[0-9]*\\-[0-9]*)"
        },
        "errcheck":
        {
            "Command": "errcheck -abspath {not_tests=-ignoretests} .",
            "Pattern": "PATH:LINE:COL:MESSAGE",
            "IsFast": false
        },
        "go-consistent": 
        {
            "Command": "go-consistent .",
            "IsFast": false,
            "Pattern": "(?P<path>.*\\.go)\\:(?P<line>[0-9]*)\\:(?P<col>[0-9]*)\\:(?P<message>.*)"
        },
        "go-namecheck": 
        {
            "Command": "go-namecheck -rules .gonamecheck.json .",
            "IsFast": true,
            "Pattern": "(?P<path>.*\\.go)\\:(?P<line>[0-9]*)\\:(?P<col>[0-9]*)\\:\\s(?P<message>[a-zA-Z].*)"
        }
    }
}
```
- Create a .gonamecheck.json file as below in workspace
```
{
    "^context\\.Context$|^\\w+Context$|^[Cc]ontext$": {
        "param+field": {"ctx": "ctxt"}
    },

    "regexp\\.Regexp": {
        "local+global": {
            "^re[A-Z]\\w*$": "use RE suffix instead of re prefix"
        }
    },

    "^func\\(.*?\\)": {
        "param": {"f": "fn"}
    }
}
```
- Have a minimal Go file with a variable that violates one of the rules (as below)
package main
import (
	"context"
	"log"
	"net/http"
	"os"
	"regexp"
)
func main() {
	var reFoo *regexp.Regexp
        log.Println("Done!")
}
- Save file and observe output in VSCode

<b>Actual</b>
- Output displays something similar to
```
D:\GitLab\shelf>Finished running tool: C:\Go\bin\go.exe vet ./...
D:\GitLab\shelf\main.go:48: reFoo declared and not used

D:\GitLab\shelf>Finished running tool: C:\Go\bin\go.exe build -i -o C:\Users\kylec\AppData\Local\Temp\vscode-gocLfW8c\go-code-check .
D:\GitLab\shelf\main.go:48: reFoo declared and not used

D:\GitLab\shelf>Finished running tool: C:\Users\kylec\go\bin\gometalinter.exe --config=.gometalinter.json . --aggregate
D:\GitLab\shelf\main.go:48: reFoo regexp.Regexp: use RE suffix instead of re prefix (go-namecheck)
```
- Note, problems tab only displays problems from the first tool
![image](https://user-images.githubusercontent.com/678335/51431036-91e0ae00-1bf1-11e9-8430-59aede987055.png)

<b>Expected</b>
- Problems tab to display all information from output screen. In this example I would expect to see at least 2 Problems since one is a duplicate.

VS Code version: Code - Insiders 1.31.0-insider (2283b29c695da3163fd4b524617dabcfb8298bbe, 2019-01-18T10:23:02.757Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.8.0

</details>

**Comment by sandy081** [comment]
Please file the issue against the Go Extension
