### ISSUE TITLE
File Explorer: Pressing Shift+Arrow opens file instead of adding it to the selection

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#66792]
Issue Type: <b>Bug</b>

When having 0 selected files and 1 focused => press <kbd>Shift</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>

VS Code version: Code - Insiders 1.31.0-insider (2283b29c695da3163fd4b524617dabcfb8298bbe, 2019-01-18T10:23:02.757Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
@joaomoreno checkout my fix, this is the nicest way I could fix this. I simply ignore selection change events which happen on shift ( also makes it easier for me so  I do not have to remember previous selection)

**Comment by joaomoreno** [comment]
@isidorn At some point you should investigate whether listening to the `open` event is the thing you actually need.

**Comment by isidorn** [comment]
Yeah that might be a better approach. Though not changing it now.
