### ISSUE TITLE
Notification appears on the debug gear for a new workspace

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#66791]
- Launch with clean user data
- Open workspace with a launch config
- The gear has a notification:

![image](https://user-images.githubusercontent.com/323878/51433106-509fcc80-1bf8-11e9-81e8-e31dc5de265b.png)

Is that supposed to be there or only when there is no launch config present?

**Comment by isidorn** [comment]
Good catch. Now I only show the notification when there are 0 configurations which I think makes sense.
