### ISSUE TITLE
"Move to a new file" refactoring removes all blank lines from JS code

### ISSUE THREAD

**Issue by raiskila** [Microsoft/vscode#66794]
### Summary

For some reason, VS Code removes all blank lines from Javascript code when using the "Refactor..." –> "Move to a new file" feature.

### Versions

- VSCode Version: 1.31.0-insider (1.31.0-insider)
- OS Version: macOS 10.14.2 (18C54)

### Steps to Reproduce:

1. Create an empty directory
2. Open that directory in VS Code
3. Create a new file called index.js within that directory with, say, the following contents:
```javascript
const abc = () => {
  const a = 10;
  
  return a;
};

abc();
```
4. Highlight the entirety of the `abc` function.
5. Select "Refactor..." from the command palette.
6. Select "Move to a new file"

### Expected result:

Blank lines inside and between functions are preserved when moving the code to a new file.

### Actual result:

Blank lines are stripped from the code when moving to a new file.

### Does this issue occur when all extensions are disabled?

Yes, tried it with `--disable-extensions` and a brand new user data dir.

**Comment by mjbvz** [comment]
Thanks for the report.

We are already tracking this issue upstream: https://github.com/Microsoft/TypeScript/issues/27294
