### ISSUE TITLE
About fonts

### ISSUE THREAD

**Issue by Code7s** [microsoft/vscode#66790]
Issue Type: <b>Bug</b>

I hope it's italicized

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
prettier-vscode|esb|1.7.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.6
vscode-language-pack-zh-hans|MS-|1.30.2
sublime-keybindings|ms-|4.0.0
vetur|oct|0.14.5
gitpatch|par|0.2.1
LiveServer|rit|5.3.1
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@Code7s May I know which fonts you are talking about?

**Comment by Code7s** [comment]
> @ Code7s我可以知道你在说什么字体吗？



> @Code7s May I know which fonts you are talking about?

A font used when editing code, such as HTML or JavaScript.

**Comment by alexandrudima** [comment]
This can be controlled by the theme.
