### ISSUE TITLE
Add ability to see file size in folder views

### ISSUE THREAD

**Issue by kilasuit** [Microsoft/vscode#66793]
Having looked and could not find this as a feature request I would find it extremely useful to be able to open a folder and see the file size in VSCode as well as the File name

I optionally would find it useful to be able to sort the view on file size as well, however this is more a secondary request as a nice to have additional feature

The benefit is that this would be extremely useful as an IT Pro when opening up a log file directory and could then from quick glance open log files that are the largest in that folder

**Comment by kilasuit** [comment]
No this should be built in to the editor and **not** an extension 

Please reopen @isidorn

**Comment by corbob** [comment]
Is there a way to add to the Explorer view provided by vscode? Or are you suggesting an extension that adds another view to the activity bar and tries to mimic something that's already provided? It appears that extensions can't add to the explorer view except with themes and context menu.

**Comment by isidorn** [comment]
I believe this should be done via an extension and thus I closed it as such.
VSCode is a minimalistic code editor and we have to choose which features to do and which not to do. We can not have all the features.

An extension can add a context menu action which would use the notification service to show the file size. Or an extension can add a new view which would render the files size.
