### ISSUE TITLE
Code becomes highly unresponsive while debugging

### ISSUE THREAD

**Issue by nanookon** [Microsoft/vscode#66799]
Issue Type: <b>Performance Issue</b>

This started to happen since version 1.30 and above. Everything works fine up until I start to debug my code. While in debug, I get a significant delay between the code I type and what displays on the screen. Even after clicking the stop button to stop debugging, it takes 30-40 seconds for it to actually stop.
I downloaded version 1.29.1 and Code becomes responsive again during debug so it's something to do with the new versions.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
vue|jcb|0.1.5
Angular2|joh|7.0.1
cql|Law|0.8.7
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
language-stylus|sys|1.11.0

</details>

**Comment by weinand** [comment]
What debugger are you using?

**Comment by nanookon** [comment]
csharp debugger. version 1.17.1
