### ISSUE TITLE
[json] Uncaught TypeError: Cannot read property 'getResolvedSchema' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#668]
Issue Id: <b>8ccb8f36-e63f-364e-3780-e296638205ee</b><br /><br />*Versions* <br />- 0.10.1-release<br />*Stack* <br />[/vs/languages/json/common/jsonSchemaService.ts#L474:41 (JSONSchemaService.getSchemaForResource)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/json/common/jsonSchemaService.ts#L474:41 (JSONSchemaService.getSchemaForResource))<br />[/vs/languages/json/common/jsonWorker.ts#L150:21 (JSONWorker.doValidate)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/languages/json/common/jsonWorker.ts#L150:21 (JSONWorker.doValidate))<br />[/vs/editor/common/modes/abstractModeWorker.ts#L112:9 (AbstractModeWorker.doValidateOnChange)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/modes/abstractModeWorker.ts#L112:9 (AbstractModeWorker.doValidateOnChange))<br />[/vs/editor/common/modes/abstractModeWorker.ts#L92:7 (AbstractModeWorker._newValidate)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/modes/abstractModeWorker.ts#L92:7 (AbstractModeWorker._newValidate))<br />[/vs/editor/common/modes/abstractModeWorker.ts#L56:59 (AbstractModeWorker.constructor)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/modes/abstractModeWorker.ts#L56:59 (AbstractModeWorker.constructor))<br />[/vs/editor/common/worker/validationHelper.ts#L182:7 (ValidationHelper._invokeCallback)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/worker/validationHelper.ts#L182:7 (ValidationHelper._invokeCallback))<br />[/vs/editor/common/worker/validationHelper.ts#L103:51 (ValidationHelper.constructor)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/common/worker/validationHelper.ts#L103:51 (ValidationHelper.constructor))<br />[/vs/base/common/async.ts#L514:8 (RunOnceScheduler.onTimeout)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/async.ts#L514:8 (RunOnceScheduler.onTimeout))<br />    at e.onTimeout (out/vs/editor/common/worker/editorWorkerServer.js:7:1525)<br />

**Comment by aeschli** [comment]
Fix delivered

**Comment by aeschli** [comment]
Verified by a test case
