### ISSUE TITLE
No such file or directory BUG

### ISSUE THREAD

**Issue by mizanur-rahman** [Microsoft/vscode#66803]
Issue Type: <b>Bug</b>

Getting this error each time when I run my IDE

ENOENT: no such file or directory, lstat '/snap/code'

I am using ubuntu 18.0.4

My IDE details-
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-43-generic

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1596)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 1|
|Memory (System)|7.71GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
python|ms-|2018.12.1
csharp|ms-|1.17.1
vetur|oct|0.14.5

</details>

**Comment by sandy081** [comment]
Can you please check if you see this error by disabling all extensions? You can disable all extensions using the command `> Reload Window With Extensions Disabled`

**Comment by tariqywsf** [comment]
i have used   (Reload Window With Extensions Disabled) ,and i can create file with no error!
so i have to remove extensions ? is there any fix for this in order to be able to use extensions? can i work without needing any extensions?

**Comment by sandy081** [comment]
Please find out the extension that is throwing this error and file issue against it.
