### ISSUE TITLE
Duplicate suggestions on import

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#66804]
Issue Type: <b>Bug</b>

Every time I type `import x from ''` it shows me duplicate lines. I'm not sure what is causing this but check the screenshot below for the bug -

<img width="734" alt="Duplicate Suggestions on Import error" src="https://user-images.githubusercontent.com/16436270/51438332-d68f4680-1cd0-11e9-8939-d114eb5608d3.png">

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
aws-amplify-vscode|aws|0.0.4
color-info|bie|0.5.0
turbo-console-log|Cha|1.2.11
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.21.1
flutter|Dar|2.21.1
vscode-eslint|dba|1.8.0
githistory|don|0.4.4
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.7.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.6
RelativePath|jak|1.4.0
latex-workshop|Jam|5.20.2
search-node-modules|jas|1.3.0
vscode-hacker-typer|jev|0.1.1
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.25
swift|Kas|0.0.3
graphql-for-vscode|kum|1.13.0
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.11.1
awesome-flutter-snippets|Nas|1.0.5
tachyons|oct|0.3.0
vscode-jest|Ort|2.9.2
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.2
vscode-graphql|Pri|0.1.6
ActiveFileInStatusBar|Ros|1.0.3
code-settings-sync|Sha|3.2.4
markdown-preview-enhanced|shd|0.3.11
mdx|sil|0.1.0
velocity|sod|0.1.0
ayu|tea|0.17.0
highlight-matching-tag|vin|0.8.5
vscode-jss-snippets|vis|0.2.2
vscodeintellicode|Vis|1.1.2
vscode-svg-previewer|vit|0.3.1
vscode-wakatime|Wak|1.2.5

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by deadcoder0904** [comment]
Ohh I forgot to check but it works with the current build too when I disable all extensions. Not sure which extension is causing problems because I have lots of them 🤣
