### ISSUE TITLE
ES6 class You cannot rename this element

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode#6680]
- VSCode Version: 1.1.1
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:

1. Create an ES6 class with a constructor

```javascript
export class AppEnvironment {
    constructor(environment) {
        this.environment = environment;
    }
}
```

2. right click the `environment` symbol that's part of the `this.environment` expression -> click rename symbol
3. Rename the symbol
4. "You cannot rename this element"

I'm aware that this probably doesn't work because it's just not implemented yet. Just want to bring it up to hope it gets implemented.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8777
