### ISSUE TITLE
Сonversion to array. Method forEach.

### ISSUE THREAD

**Issue by VladimirLarionov** [Microsoft/vscode#66800]
We have writte
Issue Type: <b>Bug</b>

Hello !!!

 Convert string to array:
 const myArray = '1, 2, 3';
 myArray = Array.from(myArray);
Here -->  myArray.(forEach) have to offer method "forEach" but it doesn't happen.
That's how it's work right ----> Array.from(myArray).forEach
Vs Code not understand  wthat the variable type has changed.
Whis happens with all types  that are converted to an array. 
In prevouse version the code worked correctly.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (1.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
LiveServer|rit|5.3.1
vscode-w3cvalidation|Umo|2.3.0
JavaScriptSnippets|xab|1.7.2

</details>
n the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
You cannot re-assign a constant variable such as `myArray`. The type of `myArray` will always be string here since you first assign it to ` '1, 2, 3'`

You likely want:

```
const myString = '1, 2, 3';
const myArray = Array.from(myString);'
...
```
