### ISSUE TITLE
Markdown line break position 【Not aligned】

### ISSUE THREAD

**Issue by ringcrl** [Microsoft/vscode#66808]
- VSCode Version: 1.30.2
- OS Version: MacOS

Steps to Reproduce:

As you can see, the position of the newline in VSCode is the beginning of the previous line.

<img width="573" alt="wx20190120-204259 2x" src="https://user-images.githubusercontent.com/16740021/51439393-9641bf80-1cf4-11e9-9e4e-fd6b593230f6.png">

However, in MWeb, after the line break, the space of the previous line identifier is left, which is obviously easier to read.

![img_2437](https://user-images.githubusercontent.com/16740021/51439395-9b067380-1cf4-11e9-91b7-c1b127d49dab.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share markdown text from your example screenshots

**Comment by ringcrl** [comment]
Will also reproduce in the English environment：

<img width="783" alt="01" src="https://user-images.githubusercontent.com/16740021/51507095-2c2b3680-1e2a-11e9-8f54-d1ceca44cf52.png">

**Comment by yume-chan** [comment]
As I understand it's a feature request, not a bug.

The reporter want the wrapping indent in markdown lists to be two characters, allowing an extension to set `editor.wrappingIndent` setting per line.

**Comment by mjbvz** [comment]
Ok, I understand this better now. This is same request as #17948

**Comment by ringcrl** [comment]
Yes，that's what I mean. As an markdown heavy user, this is a very helpful feature...
