### ISSUE TITLE
.gitignore not working

### ISSUE THREAD

**Issue by aniketjack** [Microsoft/vscode#66815]
Issue Type: <b>Bug</b>

.gitignore not ignoring included folder, in my case node_modules

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
beautify|Hoo|1.4.7
vscode-JS-CSS-HTML-formatter|lon|0.2.3
dotenv|mik|1.0.1
PowerShell|ms-|1.10.2
vscode-docker|Pet|0.5.1
html5-boilerplate|sid|1.0.3
vscode-gulp|tan|0.0.4

</details>

**Comment by yume-chan** [comment]
Version: 1.31.0-insider
Commit: 2283b29c695da3163fd4b524617dabcfb8298bbe
Date: 2019-01-18T10:23:02.757Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Files ignored by their names are not grayed out in the explorer, only files ignore by extensions are.

![image](https://user-images.githubusercontent.com/1330321/51449087-70a0ce80-1d65-11e9-9a38-b7fdf230f76f.png)
(files ignored by glob)

![image](https://user-images.githubusercontent.com/1330321/51449096-78f90980-1d65-11e9-914d-17b4a55e9c22.png)
(files ignored by extension)

**Comment by aniketjack** [comment]
Thanks for you response. 
My bad, I had copy pasted gitgonore contents and due to this there was added some unicode characters and I found those in editor. Now removed those and my .gitignore working as expected. 

Appreciated your thoughts and responses.
