### ISSUE TITLE
File Explorer: Expand all doesn't work unless folder was previously expanded

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#66811]
#66485 Issue Type: <b>Bug</b>

![alt_click](https://user-images.githubusercontent.com/9638156/51440127-8ca85f80-1cd4-11e9-9b38-c6ec5aad2ac7.gif)

VS Code version: Code - Insiders 1.31.0-insider (2283b29c695da3163fd4b524617dabcfb8298bbe, 2019-01-18T10:23:02.757Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
@isidorn, Quoting test issue:

> Alt + click will expand / collapse recursivly

**`recursively`** - means all de way.

Current logic makes this feature useless.

If it was expanding only 1 level - same as above.

What about a setting?

* `"explorer.forceExpandAll": 0,` // max nesting levels that will be forcefully expanded

**Comment by joaomoreno** [comment]
> @joaomoreno it might make sense to force expand the first level of children

No, because consecutive Alt clicks would slowly expand one more level with each recursive expand.

The tree recursive expand/collapse works correctly.

The async tree doesn't simply because that would potentially be a perf/UX nightmare. Imagine a huge folder structure. Imagine a slow file system. How would you do this? Would a recursive expand trigger enormous amount of `getChildren` calls? Should the tree user (explorer) recursively resolve all children before the tree even gets modified, thus doing so at best performance with the least amount of tree changes?

Definitely not for this milestone, but I believe a limit would be preferable. We actually never experimented with having no limit, so it would be good to see how it performs expanding a full `node_modules` folder and then make informed decisions based on that.

**Comment by Tyriar** [comment]
I'm really confused as to what alt+click is meant to do right now? It sounded like a useful feature to be able to alt+click a folder and recursively expand all sub nodes, then alt+click it again to collapse all sub-nodes.

> No, because consecutive Alt clicks would slowly expand one more level with each recursive expand.

@joaomoreno why not keep expanding until some cap has been hit like search/diagnostic caps in the editor? We should optimize for the common case which in my eyes would be to expand src dirs of small projects/components of < 50 files, or stop after the op has run for 20ms, etc.

**Comment by jonathan-s** [comment]
At some point alt + clicking close parent folder recursively closed all child folders. I found this to be a very useful feature. This no longer works which makes me a bit sad. So following this discussion to see how it progresses.

**Comment by skupjoe** [comment]
This should recursively open and recursively close all folders, in my opinion.

And then the default behavior for clicking through folders should be what the Alt+Click does now in the File Explorer..with Shift+Click to reset the expansion (ie, closing all folders..ie what regular Click does now).

Thanks!

**Comment by LiandriCorp** [comment]
I just found the feature where typing in the Explorer filters files and directories, optionally hiding what doesn't match. My next thought was, "Hey, it would be great if I could expand-all" and be able to see all the dirs/files that match.

I think there should be some option to expand the entire subtree. Recursive expansion is naturally expensive, so there should be some reasonable limit or gate that allows the user to shoot themself in the foot, but not in the head.

**Comment by Zetrick** [comment]
Adding my +1 to get the 'expand/collapse all folders and sub-folders' feature. Used this frequently with Qt Creator and (slightly) disappointed it isn't here.

**Comment by Peter-FB** [comment]
+1 for this feature.

@usernamehw already suggested

> "explorer.forceExpandAll":` 0, // max nesting levels that will be forcefully expanded

Something like that would be a great way to solve the problem of resolving too many folders.

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/66971
As it goes in the same bucket of resolving all items ahead
