### ISSUE TITLE
Folder/File Chooser is Broken

### ISSUE THREAD

**Issue by himanshugarg574** [Microsoft/vscode#66813]
Issue Type: <b>Bug</b>

Folder/File chooser on ubuntu 18.10 is broken. Ubuntu UI gets completely style-less like an html file without css. Issue can be reproduced by opening any folder via **Open Folder** option in File Menu in VSCode.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.18.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 1829)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 2, 2|
|Memory (System)|7.72GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
vsc-material-theme|Equ|2.6.3
beautify|Hoo|1.4.7
vscode-azureappservice|ms-|0.11.0
vscode-azurefunctions|ms-|0.13.1
azure-account|ms-|0.8.0

</details>

Folder chooser as in other apps.
![screenshot from 2019-01-20 20-22-14](https://user-images.githubusercontent.com/10850446/51440847-31d13100-1cf1-11e9-862a-f92f0beae070.png)

Folder Chooser in VSCode
![screenshot from 2019-01-20 20-21-54](https://user-images.githubusercontent.com/10850446/51440854-47def180-1cf1-11e9-9257-20127c5e9c88.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by himanshugarg574** [comment]
Its woking fine in insider build ver **1.31.0-1548224354_amd64**
