### ISSUE TITLE
Flutter compatability issue

### ISSUE THREAD

**Issue by akash-potdar7** [Microsoft/vscode#66812]
### Issue Type
Bug

### Description

Unable to install 'Dart-Code.flutter'; there is no available version compatible with VS Code '1.20.1'.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|/private/var/folders/nx/jq6p1f95205fs5vlr58f5cdh0000gn/T/AppTranslocation/D1184E9F-95F6-497E-9A64-50996DA5E7EA/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.26
vsc-docker|Zim|0.34.0
vscode-eclipse-keybindings|alp|0.10.0
vue-peek|dar|1.0.2
githistory|don|0.4.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
docker-explorer|for|0.1.6
sass-lint|gle|1.0.3
vue-snippets|hol|0.1.10
python|ms-|2018.4.0
vetur|oct|0.12.4
java|red|0.24.0
vscode-nginx|sha|0.6.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.13.0

</details>
Reproduces only with extensions

**Comment by krupenja** [comment]
I think you should update VSCode, 1.20 is almost a year old.

**Comment by usernamehw** [comment]
/question 

You need to update vscode in order to install that extension.
