### ISSUE TITLE
Headless Live Share

### ISSUE THREAD

**Issue by louisabraham** [microsoft/vscode#66814]
It has been noted (https://github.com/MicrosoftDocs/live-share/issues/314) that live share can be used to provide fully remote editing with language server.

I would like to be able to launch a headless VSCode editing session on my server and connect to it through Live Share.

**Comment by hickeng** [comment]
dup of https://github.com/MicrosoftDocs/live-share/issues/74

**Comment by egamma** [comment]
Closing, there now is VS Code Remote.

**Comment by hickeng** [comment]
Headless liveshare is slightly different IMO.

With remote the developer still has to know all of the details of the remote server _and have permissions on it_.
With liveshare it's possible for _one_ person to set up the headless server and for many to connect, while knowing nothing but that it's a vscode remote environment.

Think of it this way (and this is something I've wanted for a while) - an option on github repos to "enable liveshare", resulting in a hosted dev environment that is launched on the backend simply by the devs attempt to connect to it, and garbage collected after xxx time without active clients.
* maintainers would be able to get read-only or read-write sessions.
* public would be able to get read-only sessions.
* session per branch.

This is not something I think the vscode remote is ever going to be able to do as the entire approach is inverted.
