### ISSUE TITLE
File Explorer: rename input shifts when pressing arrows

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#66810]
Issue Type: <b>Bug</b>

![demo](https://user-images.githubusercontent.com/9638156/51439882-6c2ad600-1cd1-11e9-9930-0f47db1df720.gif)

VS Code version: Code - Insiders 1.31.0-insider (2283b29c695da3163fd4b524617dabcfb8298bbe, 2019-01-18T10:23:02.757Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
That's only starting after pressing <kbd>Esc</kbd> inside rename input
* file name is not selected
* pressing arrows shifts input

**Comment by isidorn** [comment]
I can reproduce this issue but only on windows.

**Comment by isidorn** [comment]
@usernamehw great catch, should be fixed in tomorrows vscode insiders. Let us know how it works for you then.

**Comment by usernamehw** [comment]
LGTM

**Comment by isidorn** [comment]
Thanks, adding verified label
