### ISSUE TITLE
Can not user Ctrl+click to follow link, when a space in the link

### ISSUE THREAD

**Issue by OhYee** [Microsoft/vscode#66825]
- VSCode Version:  1.30.2
- OS Version: Windows 10 1809

Steps to Reproduce:

1. A `.py` file contents `raise()` in `E:\\test\\a\\1.py`. 
2. copy it as `E:\\test\\a\\2 2.py`
3. Use the absolute path to run them
  `python "e:\\test\\a\\1.py"`, `python "e:\\test\\a\\2 2.py"`
4. Only the `e:\\test\\a\\1.py` can follow link.
5. We can not use follow link in `e:\\test a\\1.py` too

**Unfortunately, in OneDrive for Business, the root folder name must contain a space.**

![tim 20190121104859](https://user-images.githubusercontent.com/13498329/51450085-3423a180-1d6a-11e9-8e99-160500baab07.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is by design, don't put spaces in your filenames if you want them to work in tools like this 😃

**Comment by OhYee** [comment]
@Tyriar 
However, I have no way to modify the OneDrive for Bussiness folder name. This may be a OneDrive bug.
