### ISSUE TITLE
FileSystemProvider rename flow does not ensure new parents are created

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#66824]
- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Create a custom [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider)
2. Debug using extension host
3. Create file /a
4. Rename /a to /b/c  (assuming /b does not exist)
5. Expect stat/createDirectory calls for /b to come down before the rename call
6. Actual: rename is called before parents are ensured to exist

Note the [contract](https://code.visualstudio.com/api/references/vscode-api#1546) explicitly says that the custom implementation should: "throw FileNotFound when parent of newUri doesn't exist, e.g. no mkdirp-logic required."

This is similar to the create file flow, which does work as expected and described in the contract (ensures intermediate parents exist first).

**Comment by jrieken** [comment]
Thanks. Good catch!
