### ISSUE TITLE
System freezing

### ISSUE THREAD

**Issue by evpobr** [Microsoft/vscode#66836]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Random issue, freezing happens, only mouse moves. Can only restart PC.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.90GB (1.17GB free)|
|Process Argv|D:\Users\evpobr\Source\Repos\SndWave|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	  1868	code main
    0	   140	  2220	   gpu-process
    0	    62	  3008	   shared-process
    0	   212	  4528	   window (CMakeLists.txt - SndWave - Visual Studio Code)
    0	    11	  1784	     watcherService 
    0	   105	  3844	     extensionHost
    0	    11	  5152	       c:\Users\evpobr\.vscode\extensions\ms-vscode.cpptools-0.20.1\bin\Microsoft.VSCode.CPP.Extension.exe
    0	     5	  5712	       "C:\Program Files\CMake\bin\cmake.EXE" -E server --experimental --pipe=\\?\pipe\d:\Users\evpobr\Source\Repos\SndWave\.vscode\.cmserver-pipe
    0	    10	  4708	     electron-crash-reporter
    0	     4	  4760	     winpty-process
    0	     3	  5084	       C:\Windows\system32\cmd.exe
    0	    63	  6080	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CMakeLists.txt - SndWave - Visual Studio Code)
|    Folder (SndWave): 57 files
|      File types: cmake(6) c(5) h(5) log(4) obj(4) txt(4) md(3) exe(3) bin(3)
|                  a(2)
|      Conf files: cmake(6) settings.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
meson|asa|1.1.1
code-gnu-global|aus|0.2.2
toml|be5|0.0.3
vscode-pull-request-github|Git|0.3.2
autoconf|mae|0.0.7
cpptools|ms-|0.20.1
rust|rus|0.5.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by sandy081** [comment]
Can you please follow this wiki for performance issues and provide necessary information - https://github.com/Microsoft/vscode/wiki/Performance-Issues
