### ISSUE TITLE
Improve display of renaming action

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#66832]
Related to new tree probably, only in insiders.

How it should look like (auto selecting filename, bg does not extend to the icon):

![image](https://user-images.githubusercontent.com/4033249/51456945-584c9780-1d04-11e9-9364-44e98c774d15.png)

How it is in Insiders:

![image](https://user-images.githubusercontent.com/4033249/51456965-6ac6d100-1d04-11e9-8f49-57af93ebc42e.png)

**Comment by octref** [comment]
Should probably go to @isidorn instead.

**Comment by isidorn** [comment]
Can you please clarify what is the issue here?
The icon should not get the background color? Everything else is ok?

Thanks

**Comment by octref** [comment]
> (auto selecting filename, bg does not extend to the icon)

Basically the same behavior as Stable:

- Highlight should not include file icon
- If filename is `foo.txt`, `foo` should be auto selected.

**Comment by isidorn** [comment]
Highlight over the icon -> will not fix
Foo should be auto selected -> should be fixed in latest

Closing. Let me know if you foo is still not auto selected for you.
