### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by roser240** [Microsoft/vscode#66835]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by yume-chan** [comment]
@sandy081 Translation:

> ## Crash on startup
>
> We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sandy081** [comment]
@roser240 As it says the description does not have necessary data. Data is copied into your clipboard while creating the issue from VS Code. You have to paste the data here.
