### ISSUE TITLE
Visual studio code Debugger not getting attached with sample express project generated by express generator

### ISSUE THREAD

**Issue by pankajcheema** [Microsoft/vscode#66833]
- VSCode Version: 1.30.2
- OS Version: Ubuntu 16.04 LTS 64 Bit
- Node Version : v8.11.3

Steps to Reproduce:

1.created a directory `myfirstapp`
2. after that executed  a command `express --view=jade myapp` to generate skeleton of express project.
3. cd myapp/
4. npm install for fetching required node js package.
Content of launch.json>>>>>
[]({
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "protocol":"inspector",
            "port":3000,
            "program": "/home/pankaj/myfirstapp/myapp/app.js"
        }
    ]
}  
)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by pankajcheema** [comment]
also asked on stackoverflow https://stackoverflow.com/questions/54284141/visual-studio-code-debugger-not-getting-attached-with-sample-express-project-gen

**Comment by weinand** [comment]
@pankajcheema port 3000 is the application port of your express application. If you specify this in your launch configuration, the VS Code debugger will try to use it as the **debug** port (which obviously cannot work).

In addition, use VS Code variables to specify where your programs lives. E.g. if you have opened VS Code on your `myapp` directory, use `${workspaceFolder}/app.js` for the `program` attribute:
 
E.g.:
```
{
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceFolder}/app.js"
}
```

**Comment by pankajcheema** [comment]
I have tried everything after that landed here @weinand

**Comment by weinand** [comment]
Why are you again adding a "port" attribute? Wasn't my suggested launch config not clear enough?

**Comment by pankajcheema** [comment]
removed but not worked @weinand

**Comment by weinand** [comment]
What error/problem are you seeing?

**Comment by pankajcheema** [comment]
That's a terrible for me also that there is no error . debugger appears for some microseconds on the screen  and then lost  without error.

**Comment by weinand** [comment]
If you run your program from the command line (outside of VS Code) with 
```
node ./myapp/app.js
```
does it keep running?

Can you connect to "localhost:3000" with your browser?

**Comment by pankajcheema** [comment]
yes i can browse.

**Comment by pankajcheema** [comment]
I see the above when i am trying to run debugger from play button inside the debug section  . debugger appears for some microseconds and getting exited with this message.

/home/pankaj/.nvm/versions/node/v8.11.3/bin/node --inspect-brk=30901 myapp/app.js 
Debugger listening on ws://127.0.0.1:30901/565ac755-2eb8-4ac2-91fe-5a27ab3a87ba
Debugger attached.
Waiting for the debugger to disconnect...

**Comment by weinand** [comment]
It looks like your program is just very short running and the debugger quickly connects but then disconnects because the express program finishes.

Please try the following:
- in your launch config change `"program": "${workspaceFolder}/myapp/app.js"` to `"program": "${workspaceFolder}/myapp/app2.js"`
- in your "/myapp" folder create a "/app2.js" with this contents:
   ```js
   var i = 0;
   setInterval(() => {
       console.log("hello: " + i++);    
   }, 1000);
   ```

**Comment by pankajcheema** [comment]
Thanks @weinand  . Let me try . It makes sense .

**Comment by weinand** [comment]
I'm not an express user. So I don't know. I suggest to ask on stackoverflow.

**Comment by pankajcheema** [comment]
Thanks @weinand
