### ISSUE TITLE
最新版vscode fi两个显示问题

### ISSUE THREAD

**Issue by acm2014** [Microsoft/vscode#66838]
- VSCode Version: 1.30.2
- OS Version:  10.14 (18A391)

Steps to Reproduce:

1. 随便打开一个编辑页面
2. 输入  fi   两个字母
3. fi两个字母连在一起, 左右键移动光标可以明显看到

![image](https://user-images.githubusercontent.com/36145929/51462839-9ac1b300-1d9c-11e9-819f-d3e9aca66c15.png)

如图, 很明显, 左边十个字母和右边5个字母显示相同宽度
同样的问题, 还有fl

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Can you please provide the summary and description in english.

**Comment by yume-chan** [comment]
@sandy081 Translation:

> ## Display glitch in latest version of VS Code
>
> Steps to reproduce:
>
> 1. Open any file
> 2. Type "fi"
> 3. These two characters are stuck together
>
> As the screenshot shows, 5 "fi"s are as the same width as 5 "d"s
> It also happens to "fl"

**Comment by acm2014** [comment]
> @sandy081 Translation:
> 
> > ## Display glitch in latest version of VS Code
> > Steps to reproduce:
> > 
> > 1. Open any file
> > 2. Type "fi"
> > 3. These two characters are stuck together
> > 
> > As the screenshot shows, 5 "fi"s are as the same width as 5 "d"s
> > It also happens to "fl"
> 
> Looks like Code doesn't use a mono-space font on the reporter's computer.

I Tried mono-space font like Courier and Fira Code , but it doesn't work

**Comment by alexandrudima** [comment]
Did you try disabling `editor.ligatures`?

**Comment by acm2014** [comment]
> Did you try disabling `editor.fontLigatures`?

I tried it, and it worked, thank you!
