### ISSUE TITLE
chinese xml document comment with CodeLens shows garbled words

### ISSUE THREAD

**Issue by duanyunlun** [microsoft/vscode#66830]
VSCode Version: 1.30.2 (user setup)
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:
1. Comment some C# code (class, method, property, etc.) with XML Document syntax, such as:
    /// <summary>
    /// 自定义节点编辑器的基类实现
    /// </summary>
    public class TestComment : MonoBehaviour
    {
    }
2. Move your mouse cursor hovering the commented object ("TestComment"), the chinese comment words grabled. Such as: 
![image](https://user-images.githubusercontent.com/15923235/51455599-5b3b9c80-1d85-11e9-9fb7-3feaab84963d.png)

Does this issue occur when all extensions are disabled?: Yes

Other things about that:
If I change the Encoding to whatever isn't current Encoding and change back, I can see the comment shows normal, but reopen the VSCode makes it grabled again, so I dont know what makes it so comfused.

**Comment by alexandrudima** [comment]
This is an issue with Omnisharp. Please report against the extension at https://github.com/OmniSharp/omnisharp-vscode
