### ISSUE TITLE
setting.json property expected(bug)

### ISSUE THREAD

**Issue by KimEuntaek** [Microsoft/vscode#66831]
Issue Type: <b>Bug</b>

The setting.json is in error.
 I want to correct the error. settings.json is read-only and cannot be modified.
 Please help me.

[error images](https://i.stack.imgur.com/hr2Xt.jpg)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.25
vscode-eslint|dba|1.8.0
githistory|don|0.4.4
vsc-material-theme|Equ|2.6.3
RelativePath|jak|1.4.0
HTMLHint|mka|0.5.0
vscode-language-pack-ko|MS-|1.30.2
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.2
LiveServer|rit|5.3.1
ActiveFileInStatusBar|Ros|1.0.3
code-settings-sync|Sha|3.2.4
markdown-all-in-one|yzh|2.0.1
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by KimEuntaek** [comment]
Resolved.
Errors disappear after deleting Korean Language Pack for Visual Studio Code extensions .

**Comment by sandy081** [comment]
Closing this issue as it is resolved.
