### ISSUE TITLE
2nd "Untitled" file number starts from previously greatest number of created file

### ISSUE THREAD

**Issue by budihartono** [Microsoft/vscode#66834]
I have searched any existing issues, the closest is #65611. It's a different bug I believe.

The problem is like this, when I start from blank screen then create a new file, I get new file "Untitled-1", then I create 3 new files, it will be "Untitled-2", "Untitled-3", "Untitled-4". After that, I close all the files then I close the VS Code, and start from blank again. I create a new file, I'll get "Untitled-1" which is expected, then I create again a new file, the new file will have name "Untitled-5", it seems like it continues from "Untitled-4" which is the file created before I close the VS Code. If I continue creating it, for example if I create until "Untitled-100" then close the app again, I will get "Untitled-101" after "Untitled-1"

<img width="795" alt="vscode bug" src="https://user-images.githubusercontent.com/1005826/51457438-03e8fc80-1d84-11e9-9c56-32a54f0eaa7a.png">

- VSCode Version: 1.30.2
- OS Version: macOS High Sierra 10.13.16

Steps to Reproduce:

1. Create new file Command + N
2. Get new file named "Untitled-1"
3. Create new file Command + N
4. Get new file named "Untitled-[previous greatest number of created file + 1]"
5. Do Step 3 & 4 for a few times
6. Close VS Code
7. Start again from Step 1

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by budihartono** [comment]
@bpasero I confirm that the bug is fixed in the preview version you've provided. Thanks!
