### ISSUE TITLE
Integrated powershell terminal says it cannot load PSReadline module

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6684]
#143

- OS Version: Windows 10

Steps to Reproduce:

1. Launch terminal with default settings

![image](https://cloud.githubusercontent.com/assets/2193314/15478907/23deee2a-20d2-11e6-97b4-c4d96c85d5ad.png)

**Comment by rebornix** [comment]
It's likely a ExecutionPolicy restriction issue (not quite sure), you can give cmder's default setting a try to see if it helps.

```
PowerShell -ExecutionPolicy Bypass -NoLogo -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''" -new_console:d:"%USERPROFILE%"
```

**Comment by lzybkr** [comment]
Most likely PowerShell is running as a 32 bit process - PSReadline is not installed in Program Files (x86).

**Comment by Tyriar** [comment]
@lzybkr is `\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe` the correct executable?

**Comment by lzybkr** [comment]
Yes.  See my stackoverflow answer if you want to run the 64 bit version of PowerShell: 

http://stackoverflow.com/questions/19055924/how-to-launch-64-bit-powershell-from-32-bit-cmd-exe

**Comment by Tyriar** [comment]
There is no `%SystemRoot%\sysnative`, `%SystemRoot%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe` however does exist but it still prints out the PSReadline warning.

**Comment by lzybkr** [comment]
If you try to load it explicitly `ipmo PSReadline`, what is the error?

**Comment by gerane** [comment]
@Tyriar `%SystemRoot%\sysnative` is a Redirect. It is how a 32bit process on a 64bit OS accesses `%SystemRoot%\System32` . 

If a 32bit process attempts to `%SystemRoot%\System32` it is redirected to `%SystemRoot%\SysWOW64\`

**Comment by Tyriar** [comment]
Since powershell is no longer the default and the fix to this is to correctly specify the 64-bit powershell, I'm going to close this in favor of https://github.com/Microsoft/vscode/issues/7095
