### ISSUE TITLE
bug in explore toggle 

### ISSUE THREAD

**Issue by SoniyaDhanapal** [Microsoft/vscode#66848]
Issue Type: <b>Bug</b>

click terminal-> give  npm i -> and click explore toggele open and close -> terminal window instaillaion will repeat again and again 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.15063

**Comment by Tyriar** [comment]
You will need to elaborate what the problem is, maybe a screenshot of gif would help?

**Comment by SoniyaDhanapal** [comment]
<img width="960" alt="progress bar is repeating while clicking explore button at the time of installtion" src="https://user-images.githubusercontent.com/38656429/51588733-0de93780-1f0b-11e9-839a-97ce27dc8f1d.png">

**Comment by SoniyaDhanapal** [comment]
open terminal is vs code-> give  command  npm i and installation will start after that go and click left side explore toggle menu -> then see terminal window -> progress bar is repeating base on how many times we clicked explore menu .

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
