### ISSUE TITLE
No additional information popup when hover(mouseover) element

### ISSUE THREAD

**Issue by BartekkPL** [microsoft/vscode#66841]
Issue Type: <b>Bug</b>

Hey All,

I have experienced some issue, that strongly decreased my productivity.

On Ubuntu 16.04 when I put mouse over some code after some time (300ms) it shows popup with additional info (e.g. type of variable).

Recently I have installed Ubuntu 18.04 and there is problem with this feature. It simply doesn't work.
I don't know if it can help, but when I install this new Ubuntu ditro I had some problems with Google Chrome and I need to disable GPU hardware acceleration.

I don't know if it is possible in VS Code. Maybe I can check if this can solve my problem.

Best regards,
Bartek

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3429)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.32GB (24.26GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by BartekkPL** [comment]
OK, I found that I can disable hardware acceleration with `--disable-gpu` option.

AND IT HELPS. Popup is here back. I don't know if it is some distro bug, so I don't close this issue yet. If you think that it is my distro fault, close issue yourself.

**Comment by sandy081** [comment]
@bpasero FYI

**Comment by BartekkPL** [comment]
It doesn't work as perfectly as earlier, but it may be CPP extension fault, because I usually use this extension.

**Comment by BartekkPL** [comment]
I reproduced it with Visual Studio Code - Insiders build.
The result is exactly the same. Popup is showed only when I launch editor with `--disable-gpu` option.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by BartekkPL** [comment]
I've just tested exploration version and result is the same as with other versions. Popups are showed only when I've used `--disable-gpu` option.
