### ISSUE TITLE
Filename case after click on class member

### ISSUE THREAD

**Issue by Nakiloe** [Microsoft/vscode#66845]
![vscode_filename](https://user-images.githubusercontent.com/45621005/51471590-6daed980-1d77-11e9-9242-72b16c4f07c6.png)
Issue Type: <b>Bug</b>

When I click on a class member (from controller to model, in PHP), the file is opened, on the correct member, but the filename is shown with first letter in uppercase, while the real file is lowercase (see attached screenshot). I'm on MacOS, so if I make changes and save them, it creates a second file instead of overwriting my file.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.0.0

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
