### ISSUE TITLE
Setting PATH using `options.env` or via a `dependsOn` task doesn't work

### ISSUE THREAD

**Issue by AmanShurafa** [Microsoft/vscode#66844]
- VSCode Version: `1.30.2`
- OS Version: `Windows x64 10.0.17134`

I am using Windows Subsystem for Linux (Ubuntu Distribution). I use rbenv and everything is working fine in bash. But for some reason, my `PATH` isn't loaded properly for tasks (`~/.bashrc` isn't loading).

I tried defining a seperate task for `"export PATH=\"~/.rbenv/shims/:$PATH\"` and include it in dependsOn (tried string, array, and object formats) (also tried defining the task directly in dependsOn) but that didn't work either.

I also tried:
```
    "command": "export PATH=\"~/.rbenv/shims/:$PATH\" && printenv", //WORKS
    "command": "printenv", "options": {"env": {"PATH": "~/.rbenv/shims/:$PATH"}} //FAILS
```

Here is my entire `tasks.json`:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": ".rbenv/shims",
      "type": "shell",
      "command": "export PATH=\"~/.rbenv/shims/:$PATH\"",
      "presentation": {
        "echo": false,
        "reveal": "never",
        "panel": "shared",
        "showReuseMessage": false
      },
      "problemMatcher": []
    },
    {
      "label": "Rails Console",
      "type": "shell",
      "command": "rails console"
      "dependsOn": [".rbenv/shims"],
      "options": {"env": {"PATH": "~/.rbenv/shims/:$PATH"}},
      "presentation": {
        "reveal": "always",
        "panel": "shared",
        "focus": true
      },
      "problemMatcher": []
    }
  ]
}
```
running the Rails Console task results in:
```
> Executing task in folder my-app: rails console <

/bin/bash: rails: command not found
The terminal process terminated with exit code: 127
```
Changing `command` for that task to `~/.rbenv/shims/rails console` results in a successful run.

Does this issue occur when all extensions are disabled? Yes

**Comment by alexr00** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/47235

Are you seeing the same thing that's happening in that other bug? If you change your command to something simple, do you see `~/.bashrc` get loaded first?

**Comment by AmanShurafa** [comment]
I guess I need to fix the title and clear up the post a bit. I saw a number of open and closed issues related to *Path incorrectly copied to tasks.json*. I was trying a couple of workarounds and found possible bugs while doing so:
1. dependsOn task `export PATH=\"~/.rbenv/shims/:$PATH\` isn't executing before the main task `printenv` or `rails console`.
2. Setting env vars via options isn't working as expected: `"options": {"env": {"PATH": "~/.rbenv/shims/:$PATH"}}`

I am not sure these are valid bugs or user errors.

As for the workaround I ended up declaring `options.shell` before my task array:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0", 
  "windows": {
    "options": {
      "shell": {
        "executable": "bash.exe",
        "args": ["-i", "-c"]
      }
    },
  },
  "tasks": [
    {
      "label": "Rails Console",
      "type": "shell",
      "command": "rails console",
    }
  ]
}
```

**Comment by alexr00** [comment]
> dependsOn task export PATH=\"~/.rbenv/shims/:$PATH\" isn't executing before a main task printenv or rails console.

From what I understand about `export` I wouldn't expect that to work, since the task that depends on the export task isn't a child process of the task that runs the export.

> Setting env vars via options isn't working as expected: "options": {"env": {"PATH": "~/.rbenv/shims/:$PATH"}}

I can reproduce this. @Tyriar, I stepped through the terminal code and I could see the environment variable get set and then passed in the `IPtyForkOptions` into `pty.spawn` in `terminalProcess.ts`. However, the environment variable isn't getting set somewhere. I used this task to test and the environment variable was not set. Any ideas why that would happen for WSL with bash.exe ?

````JSON
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "envVar test",
			"type": "shell",
			"command": "echo $MYVAR",
			"options": 
			{
				"env": 
				{
					"MYVAR": "~/.rbenv/shims/"
				}
			},
			"problemMatcher": []
		}
	]
}
````

**Comment by Tyriar** [comment]
@alexr00 only in wsl? I haven't seen this before, can you open WSL and look at your ~/.bashrc to see if that tweaks it?

**Comment by alexr00** [comment]
@Tyriar have you had a chance to look at this?

**Comment by Tyriar** [comment]
This is happening for the same reason setting a variable in cmd.exe and then entering wsl.exe will not carry over the variable. I think this is by design currently.
