### ISSUE TITLE
Collapsing code sections does not work

### ISSUE THREAD

**Issue by powershellking** [Microsoft/vscode#66846]
Hi there,

I'm currently encountering an issue when editing PowerShell code with Visual studio code. The collapsing / uncollapsing of regions, functions etc. The problem is that sometimes the + / - signs are invisible and do not even become visible when hovering the line number. Unfortunately I can't really describe when it works and when it does not. At the moment it's not working. In this case when I have a collapsed region or function I can't access the code in that regions although it's still there.

Here are my system specs:

OS: Windows 10 1709 64 bit with latest patches from 1/19.
Visual Studio Code version: 1.30.2 (system setup)
PowerShell extension version: 1.8.1

What can I do to resolve this issue?

Thanks in advance.
powershellking

**Comment by aeschli** [comment]
Any code sample that shows the issue would be helpful.
Do you use the powershell extension?
