### ISSUE TITLE
SnippetString choices are prefixed with typed text instead of replacing

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#66847]
If you use a choice in a snippet string like this:

```ts
const ss = new vs.SnippetString("${1|one,two,three|} = xxx");
await editor.insertSnippet(ss, new vs.Range(document.positionAt(startPos), document.positionAt(endPos)));
```

It appears like this:

![screenshot 2019-01-21 at 12 19 59 pm](https://user-images.githubusercontent.com/1078012/51474348-e3667580-1d76-11e9-9f3f-028d97f2d931.png)

The cursor is before the text, which means if I start typing I get this (`one` remains after where I'm typing):

![screenshot 2019-01-21 at 12 20 42 pm](https://user-images.githubusercontent.com/1078012/51474384-fd07bd00-1d76-11e9-9f28-5f8a34d2fce6.png)

It does correctly delete the whole lot when you select one, but it looks really wonky and if you want to type a value that's not in the choice list, you end up having to delete the pre-inserted text afterwards.

I think the snippet should be selected and over-typed if I start typing.

**Comment by jrieken** [comment]
Acknowledged but the fix is to complex/risky given this has been reported only once

**Comment by jrieken** [comment]
Recent refactorings made this easy to implement. Now, the default value is all selected and can be overtyped without using "choice-mode"

https://user-images.githubusercontent.com/1794099/160393709-06fb172b-3984-4472-b680-7f480c712ce2.mov

**Comment by DanTup** [comment]
Thanks! I was just recently improving the snippet support in Dart, so being able to include suggestions without the issue here will be neat :-)

**Comment by jrieken** [comment]
Merged, next insiders is likely to arrive end of week

**Comment by aeschli** [comment]
Verified that the cursor is now at the beginning.
Selecting an entry jumps to the next snippet position.
