### ISSUE TITLE
task that does not wait for process to exit

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/vscode#66840]
I wanted to make a task which will build a project and open resulting pdf-file in pdf viewer, for example
```
"tasks": [
    {
        "label": "Build",
        "type": "shell",
        "command": "make",
    },
    {
        "label": "Build and View",
        "type": "process",
        "command": "evince",
        "args": [
            "_build/document.pdf"
        ],
        "dependsOn": ["Build"],
        "group": {
            "kind": "build",
            "isDefault": true
        }
    }
]
```
But it makes VS Code wait until pdf viewer process exists, which is not what I want. In addition when running task again I get
![image](https://user-images.githubusercontent.com/152563/51464043-6387dd80-1d6d-11e9-8341-34c72c6e846e.png)

**Comment by alexr00** [comment]
Related to #32264.

**Comment by alexr00** [comment]
Could you make a script that your tasks runs that opens the pdf and then returns?
