### ISSUE TITLE
The DocumentSymbolAdapter should filter only symbol informations which the location matches with the current editor one

### ISSUE THREAD

**Issue by sam974** [Microsoft/vscode#66853]
- VSCode Version: 1.30.1
- OS Version: 	Ubuntu 18.04.1 LTS

Steps to Reproduce:

1.Provides a Language server which provides documentSymbols as symbol informations (SymbolInformation type). In my case, my grammar allows include files. So the language server sent as response to documentSymbols/request all symbol informations that can have locations which do not match with the one currently being modified in the editor.
2. As you can see on the screencast, the 'buildVars:' and 'PA_DIR' nodes are not part of the opened default.sdef file. They belong to the included files. By the way, I want to keep them in documentSymbols response since they are displayed somewhere else than in the outline.
![wrong-outline](https://user-images.githubusercontent.com/16103808/51483367-305b4380-1d99-11e9-846a-6a3d9298951b.gif)

The problem comes from the [DocumentSymbolAdapter](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L50) which should take into account only symbol informations with the same URI than the current resource.

Does this issue occur when all extensions are disabled?: No, I need my personal extension to reproduce since it's based on the LSP protocol

**Comment by jrieken** [comment]
> The problem comes from the DocumentSymbolAdapter which should take into account only symbol informations with the same URI than the current resource.

I'd argue it's a problem with the extension returning those locations. Why would your extension compute those such that the only thing do is throwing them out?

**Comment by sam974** [comment]
Ok thanks much for your response!
I would answer that my extension provides another view fully based on the same [documentSymbol request](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) and that in my customized view, the SymbolInformation class completely makes sense since it leverages the ability to navigate between included files too.
![customized-treeview-based-on-documentsymbols-request](https://user-images.githubusercontent.com/16103808/51493767-a4581480-1db6-11e9-8d8e-d8428fd8457b.gif)

**Comment by sam974** [comment]
With the attached patch, only the appropriate symbol informations feed the outline view whereas the whole response is used by the customized view .

![filtered-symbol-infos-request](https://user-images.githubusercontent.com/16103808/51499863-230b7c80-1dcc-11e9-97ab-b17c67e7d9ed.gif)

[filtered-symbol-infos.patch.txt](https://github.com/Microsoft/vscode/files/2780561/filtered-symbol-infos.patch.txt)

**Comment by jrieken** [comment]
> I would answer that my extension provides another view fully based on the same documentSymbol request and that in my customized view, 

That still doesn't mean you can provide invalid data from the *Document*SymbolProvider... Why don't you know this when the request is being made and when being asked for the outline don't provide invalid results? I feel this is a common problem/pitfall that justifies full recursive filtering of every symbol
