### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cs-abdulwahab** [Microsoft/vscode#66859]
Jan 21 22:37:04.288 INFO Starting: C:\Users\Abdul Wahab\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Jan 21 22:37:04.300 ERRO Bad arguments: Code path doesn't seem to exist: C:\Users\Abdul Wahab\AppData\Local\Programs\Microsoft VS Code\Code.exe

**Comment by maa3x** [comment]
It seems Windows can't find VS Code executable. Check that `C:\Users\Abdul Wahab\AppData\Local\Programs\Microsoft VS Code` is exists and it contains `Code.exe` file.
Also please change your issue title with more detail about your problem.
