### ISSUE TITLE
Prompt & Cursor on different lines after Clear Terminal

### ISSUE THREAD

**Issue by glawrence** [Microsoft/vscode#66850]
Issue Type: <b>Bug</b>

Install the PowerShell extension, then open a PowerShell script file and execute it in the terminal via "Run active file in active terminal", preferably a script that displays multiple lines of out put. Then click in the Terminal windows, right click and select clear, press the up arrow key to show the previous command, such that you can click enter and run it again.

However at this point after the clear the prompt line is at the top of the window but after the up arrow the previous command is at the bottom, which looks very odd.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (5.30GB free)|
|Process Argv|-psn_0_8849520|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
PowerShell|ms-|1.10.2
java|red|0.37.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.13.0

</details>

**Comment by Tyriar** [comment]
Likely caused by the extension of pwsh itself.

**Comment by glawrence** [comment]
Okay, thanks, much appreciated
