### ISSUE TITLE
Align Method Parameters By Parameter Name

### ISSUE THREAD

**Issue by dkent600** [Microsoft/vscode#66855]
With `Editor: Tab Size` set to "2" and the TypeScript Extension "Format on Save" set to true, when I save a file with the following:

```
  myMethod(
    param1: type
  , param2: type
  , param3: type
  )
```

VS Code produces this:

```
  myMethod(
    param1: type
    , param2: type
    , param3: type
  )
```

Tools like tslint, when checking for alignment, report that the parameter lines are not aligned.

Would be great if the formatter could leave these lines aligned as in the first example.

The rule would be something like "Align Method Parameters By Parameter Name"

**Comment by mjbvz** [comment]
Somewhat related to https://github.com/Microsoft/TypeScript/issues/11865

Try installing one of the third party formatting extensions for more advanced formatter options like this
