### ISSUE TITLE
Wrong scope on function name that starts with 'split'

### ISSUE THREAD

**Issue by esemlabel** [Microsoft/vscode#66869]
There pattern in `php.tmLanguage.json` for `support.function.ereg.php` scope is broken.
Every custom function that start with name split will mistakenly recognize as ereg function. This clearly visible when color scheme uses different color for builtin and custom function name:

<img width="597" alt="2019-01-22 00 22 49" src="https://user-images.githubusercontent.com/17903845/51501750-e34c9100-1ddb-11e9-8ea4-65fa97bc13f4.png">

- VSCode Version: 1.29.1
- OS Version: OS X 10.11.6 (El Capitan)

Does this issue occur when all extensions are disabled?
Yes

**Comment by roblourens** [comment]
This issue was moved to atom/language-php#353
