### ISSUE TITLE
Rename file in explorer styling issue

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#66866]
- Click a file in the explorer to select
- Focus the editor
- Focus the explorer again with the keyboard
- Press enter to rename file
- The row is highlighted but the input box doesn't appear
- Try renaming other rows, sometimes the input box appears, sometimes not

Sometimes the wrong text appears after pressing enter, not sure if that's a separate issue. That happens a couple times in the gif

![jan-21-2019 12-54-20](https://user-images.githubusercontent.com/323878/51498639-1cedaf80-1d7c-11e9-8e5d-3e33b2d3faba.gif)

**Comment by isidorn** [comment]
This works fine for me and should be fixed via 55951f06fa
Can you repro with latest out of source or vscode insiders from Wednesday?

**Comment by roblourens** [comment]
Hm, I can't repro after updating insiders
