### ISSUE TITLE
Unnamed Structure and Union Fields for Intellisense/gcc

### ISSUE THREAD

**Issue by nurbles** [Microsoft/vscode#66861]
I am not sure if I am asking for a feature or reporting a bug.  I believe it is about something that intellisense is doing wrong, but since it could have been intentionally left out (because a developer didn't know gcc supported this feature, perhaps) I may be asking for a new feature.   Or, most likely, I just cannot discover the correct combination of settings to get intellisense to work as I need.

I am using:
    Version: 1.31.0-insider
    Commit: e9bb33f09599753150be897ab81126a620e53b94
    Date: 2019-01-21T06:16:03.813Z
    Electron: 3.0.13
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 4.15.0-43-generic
with the C/C++ 0.21.0-insiders4 Intellisense extension

I started using the **-fms-extension** switch on the gcc command line to allow unnamed struct/union members, but intellisense is flagging all references to those members as errors.  (I'm building on an embedded box, so vscode doesn't get any compiler output [which has zero errors or warnings[).

I have the c_cpp_properties.json settings with compilerPath=/usr/bin/gcc,  cStandard=c11, cppStandard=c++17 and intelliSenseMode=Default

I had learned to like vscode/intellisense's ability to let me know about errors BEFORE I sent the source to the embedded box to be built, but now my code shows too many errors that actually are NOT errors for me to find all the REAL mistakes I make!  Hopefully intellisense can stop flagging these valid statements as errors, at least when told to allow them (but how is that done?)

**Comment by mjbvz** [comment]
Please file this issue against the c++ tools extension
