### ISSUE TITLE
Custom indent in trees: exclude first level

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#66863]
Issue Type: <b>Feature Request</b>

#35447 

Keep first level indentation at `8px`.

VS Code version: Code - Insiders 1.31.0-insider (e9bb33f09599753150be897ab81126a620e53b94, 2019-01-21T06:19:35.291Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
This will be taken care when custom views adopt to new tree.

**Comment by usernamehw** [comment]
@sandy081, but this is about all trees (for instance Explorer now moves 1st level with `"workbench.tree.indent"`).

**Comment by sandy081** [comment]
Internally there are two types of tree implementation old and new. We are currently adopting to new tree one by one. Explorer has done it this milestone. These configurations you mentioned belongs to new workbench tree. Custom view trees are still on old tree implementation.

**Comment by usernamehw** [comment]
I guess the title was confusing. I'm talking about current the new tree indent wherever it applied. Currently in Explorer. In future in all other trees it shouldn't affect the first (initial) level of items.

**Comment by sandy081** [comment]
Sorry for the confusion, assigned to right owner.

**Comment by isidorn** [comment]
This makes sense. Forwarding to @joaomoreno
