### ISSUE TITLE
Editor Stacks do not clean up from file deletes when switching branches

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#6686]
Regarding #6686

- VSCode Version: commit 91f14c441df40b80f14d0a04b3a4db816d579a3e
- OS Version: OS X

Steps to Reproduce:

1. Checkout a branch that has some unique files that no other branch has
2. Open one or more of those unique files
3. Now `git checkout` another branch that does not have these files.
4. Note that the files remain as open editors; however, when you click on any of them you get the unable to open error below.

<img width="1440" alt="screen shot 2016-05-23 at 10 50 43 am" src="https://cloud.githubusercontent.com/assets/11839736/15479343/9bba32fe-20d4-11e6-807d-2fbdec62bfc2.png">

We should just simply close the editors.

**Comment by bpasero** [comment]
@bgashler1 this would rather be an issue with VS Code not detecting file changes. I tried to reproduce with a simple case but failed:

![untitled](https://cloud.githubusercontent.com/assets/900690/15500428/f6db95b8-21a8-11e6-8bf7-d2d7547e60fc.gif)

Does it reproduce all the time for you? Specific steps?

**Comment by bgashler1** [comment]
That's odd, I can't reproduce.  Maybe it was just a weird glitch I got into.  I'll reopen if I can reproduce it again later.

**Comment by bpasero** [comment]
@bgashler1 makes sense, I would think this to be rather an issue with VS Code loosing file events than being related to the tabs work.

**Comment by bpasero** [comment]
Found out how this can happen: reload the vscode with editors open and then do the git operation, it fails to clean up!

**Comment by bpasero** [comment]
Fixed :)

**Comment by bgashler1** [comment]
Awesome!
