### ISSUE TITLE
Completion list is filtered on leading whitespace

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#66860]
Given a language that takes named args with colons:

```
myFunc(foo: 1);
```

It seems sensible to set `:` as a trigger character to open completion. This works fine:

```ts
context.subscriptions.push(vscode.languages.registerCompletionItemProvider("markdown", {
    provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.CompletionItem[] {
        return [
            new vscode.CompletionItem("test"),
        ];
    }
}, ":"));
```

![screenshot 2019-01-21 at 6 32 47 pm](https://user-images.githubusercontent.com/1078012/51492813-f7c46580-1daa-11e9-8a76-fc660d790a7e.png)

However, if you type a space (as shown above, to have whitespace between `:` and the value), the completion list gets filtered and disappears. While it's possible to set `<space>` as a trigger character, that results in the completion provider being called a lot (for example on every space inside comments) which then need to be filtered out by the extension.

Is it reasonable to ignore *leading* whitespace when filtering the completion list to simplify things? It seems almost certain that no provider is ever going to return completion items with leading spaces expecting them to be precisely filtered?

**Comment by jrieken** [comment]
You must `filterText` and `sortText` then, the simple, label-only, completion doesn't cover this case.

**Comment by DanTup** [comment]
@jrieken Do you mean prefix the `filterText` for all entries with spaces? I can certainly try this, but it feels a bit weird as a solution.
