### ISSUE TITLE
Don't write code that doesn't work on IE11

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#66876]
Like this: https://github.com/Microsoft/vscode/blob/e83c7a08a9340f817f708aed0e773d755a7a52f6/src/vs/platform/url/common/urlService.ts#L11-L13.  I know it's not cool, but you'll have to use the [`values`](https://github.com/Microsoft/vscode/blob/e83c7a08a9340f817f708aed0e773d755a7a52f6/src/vs/base/common/map.ts#L12)-util instead. There is no point in running double compiles et all if we just slip declaration like this into the common layer 🚓

**Comment by joaomoreno** [comment]
I must say that was a bit reckless on my part. 🤐
