### ISSUE TITLE
dom#timeout duplicates async#disposableTimeout

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#66878]
See https://github.com/Microsoft/vscode/blob/c52a3010e6f00e6779f4537f6c5a7bc18a6d5176/src/vs/base/browser/dom.ts#L1170-L1174 (younger) and https://github.com/Microsoft/vscode/blob/c52a3010e6f00e6779f4537f6c5a7bc18a6d5176/src/vs/base/common/async.ts#L321-L329 (older)

**Comment by joaomoreno** [comment]
Oh! Funny how there's only one use of the `disposableTimeout` and its return value isn't even saved. 😆
