### ISSUE TITLE
References View Does Not Open

### ISSUE THREAD

**Issue by dill0wn** [Microsoft/vscode#66871]
Issue Type: <b>Bug</b>

In both a C# (Unity), and a TS project, VSCode is correctly able to find references using the "in-line" mode, but I am unable to open the references side panel.

View > Open View... > References doesn't do anything.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
docomment|k--|0.1.2
prettify-json|moh|0.0.3
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
code-settings-sync|Sha|3.2.4
unity-debug|Uni|2.6.6

</details>

**Comment by jrieken** [comment]
> View > Open View... > References doesn't do anything.

Well works for me... You will need to provide *reproducible* steps so that we can understand this issue

**Comment by dill0wn** [comment]
Well, after restarting VSCode a couple times it started working. Going to mark as closed.
