### ISSUE TITLE
markdown.styles missing should not break markdown preview

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#6688]
- VSCode Version: 1.1.1 
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Pick Dark Theme 
2. Open a markdown file and toggle side by side preview, on the preview panel you will see the font color is white and the background color is dark.
3. Open user preference, add below config and make sure `markdown.css` doesn't exist in your workspace.

    "markdown.styles": [
       "markdown.css"
    ]

Now the font color in preview panel becomes black but the background remains dark, which makes the preview unreadable. Toggle develop tools and you'll see the error message saying `markdown.css` is missing. But we shouldn't break the preview, right?

Just open this issue as a reminder, once @kieferrm puts the markdown logic to a separate extension, let's see if this problem still exists.

**Comment by bpasero** [comment]
@rebornix @kieferrm did we loose the ability to provide custom CSS with the markdown preview?

**Comment by kieferrm** [comment]
@bpasero, we still provide the same support. We still need to retest this scenario.

**Comment by bpasero** [comment]
Great, thanks.

**Comment by mjbvz** [comment]
I do not see this happening in the latest insiders builds. There is a message about the missing stylesheet in the preview, but we still load the default `media/markdown.css` file just fine and this is applied to the preview.
