### ISSUE TITLE
Autocomplete prompts contain additional information

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#66880]
- VSCode Version: 1.30.1
- OS Version: 10.3.3

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/34906299/51506600-01d87980-1e28-11e9-868a-d98fbbca54aa.png)

I use registerCompletionItemProvider to implement intelligent tips, but there are a lot of other information, is there a way to remove other information or put my own information on top?

**Comment by jrieken** [comment]
>  is there a way to remove other information or put my own information on top?

There is no way to remove other suggestions because the system is designed to be collaborative. The sorting can be influenced via the `sortText` property, once users start typing sorting is based on match-score.

**Comment by chnliquan** [comment]
> > is there a way to remove other information or put my own information on top?
> 
> There is no way to remove other suggestions because the system is designed to be collaborative. The sorting can be influenced via the `sortText` property, once users start typing sorting is based on match-score.

Thank you for replying to me., but what should i set this property to put my data in the top. I can't understand `sortText` according to the documentation.
```js
return names.map(name => {
        const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Function)
        item.sortText = 'aaa'
        return item
      })
```
Using a dictionary sequence？ it not works @jrieken
