### ISSUE TITLE
Allow to save window layouts

### ISSUE THREAD

**Issue by duanyunlun** [microsoft/vscode#66883]
I have two Screen in my work, everytime I open the VSCode I have to manual drag the split window and check the window layout, hope there can leave an option to save my custom window layout as every text Editor had. e.g:
[Unity]
![image](https://user-images.githubusercontent.com/15923235/51511365-ff801a80-1e3b-11e9-8148-60d1cdc2d992.png)
[Visual Studio 2017]
![image](https://user-images.githubusercontent.com/15923235/51511400-1e7eac80-1e3c-11e9-8d0b-ec9c6f4f776b.png)

**Comment by kanlukasz** [comment]
Save layouts it option that could be really useful. It should be include windows position, opened sidebar, activity bar, etc, etc. etc.

**Comment by ELLIOTTCABLE** [comment]
I'm sad that not only did *this* get closed; but that [an external extension](https://github.com/ctf0/vscode-save-editor-layout) attempting to solve the problem had *their* Issue requesting an API that would allow them to do this closed, as well. (#88612)

The inability to quickly restore different layouts really, really hurts the VSCode editing experience in a myriad of ways.

Just a few situations where this would really save the day:

- Moving your 'primary' VScode instance back and forth between different screen sizes, you probably want to switch between two- and three-column editor-layouts for the same project quickly. In fact, this alone covers a multitude of use-cases:
  - Connecting your laptop to your larger external display when you get to the office
  - Moving your window between two adjacent displays of different physical size
  - Use a feature like macOS's "Split View" to use a second app alongside VScode on the same screen, temporarily
- Having to put complicated, active work on hold for a moment to fix a bug in another file, while being able to *return* to the exact visual/mental context you had before tabbing over to that file
- Getting started more quickly on a particular 'type' of editing-task. (For instance, maybe you often want to open an empty editor pane on the left, where a new file will reside; the `routes.rb` file to the top-right, a new file inside `tests/` below that … etc.)

This is also important for folks transitioning to VScode from other editors. Vim, for instance, supports this natively — and it's a big part of any fullscreen-vim-user's workflow. (Vim's "windows", what we call "editor groups", are subordinate to another level of organization called "tabs." When you switch tabs, the entire "window"-layout swaps out. It's fantastic.)
