### ISSUE TITLE
Memory leak probably

### ISSUE THREAD

**Issue by ocoka** [microsoft/vscode#66886]
Issue Type: <b>Bug</b>

1. Open editor for Angular TypeScript project with 
2. Make find for string in project for 5 times
3. got 
![image](https://user-images.githubusercontent.com/8239290/51514882-b40d4280-1e22-11e9-8e80-342136f687cd.png)
![image](https://user-images.githubusercontent.com/8239290/51514903-cd15f380-1e22-11e9-95c0-a5e49464b906.png)
```bash
user : ~/Project$find -type f | wc -l
129008
user : ~/Project$find -type f -name '*.ts'  | wc -l
7055
user : ~/Project$find -type d | wc -l
13421
user : ~/Project$find -type f -name '*.scss'  | wc -l
291
user : ~/Project$find -type f -name '*.html'  | wc -l
435
user : ~/Project$
```
![image](https://user-images.githubusercontent.com/8239290/51515090-69d89100-1e23-11e9-8ea4-fc45b6b4f0e5.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.20.0-997-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3474)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.53GB (1.69GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.4.1
java|red|0.37.0
vim|vsc|1.0.3

</details>

Maybe this flag that I turned on ?!
![image](https://user-images.githubusercontent.com/8239290/51515381-81644980-1e24-11e9-981c-19edf5613ed6.png)

**Comment by Tyriar** [comment]
Is the issue the 52gb under the selected row? That's eaten by the extension host so it's likely a problem with one of your extensions. Could you run `code --status` when this happens and paste in the output?

**Comment by Leo1003** [comment]
I recently have this issue too. The watcherService is using more and more memory while I was coding... 
And finally, it used all of my memory and made other program being swapped out of memory. 

---
Here are some screenshots: 
Coding for a while...
![ScreenShot1](https://user-images.githubusercontent.com/14937593/58764821-61951d00-859e-11e9-868d-6278ec9e4b74.png)
Coding for a while again...
![ScreenShot2](https://user-images.githubusercontent.com/14937593/58764896-4d055480-859f-11e9-8892-25c870817e1f.png)

Output of `code --status` :
```text
[18345:0603/013240.060680:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS Version:       Linux x64 5.1.5-arch1-2-ARCH
CPUs:             Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 1455)
Memory (System):  7.54GB (0.45GB free)
Load (avg):       2, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  surface_synchronization:      enabled_on
                  video_decode:                 unavailable_off
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	   139	  8640	code main
    0	    39	  8646	   zygote
    0	   301	  8718	     window (ossh_pubkey.rs - osshkeys (工作區) - Visual Studio Code)
    0	   224	  8819	       extensionHost
    0	    23	  9058	         /home/leo/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/Microsoft.VSCode.CPP.Extension.linux
    0	   309	  9228	         /home/leo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls
    0	    54	  9591	         /home/leo/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/Microsoft.VSCode.CPP.Extension.linux
    0	    54	 10903	           /home/leo/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 9591 4
    0	    46	 11066	           /home/leo/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 9591 6
    0	    62	 11727	           /home/leo/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 9591 7
    0	    62	  9636	         /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=8819
    0	  2394	  8844	       watcherService
    0	    54	  8885	       searchService
    0	   108	  8794	     shared-process
    0	    69	  8682	   gpu-process

Workspace Stats: 
|  Window (ossh_pubkey.rs - osshkeys (工作區) - Visual Studio Code)
|    Folder (openssh-portable): 755 files
|      File types: c(265) h(119) sh(95) pub(53) cert(17) fp(14) bb(10) bin(9)
|                  in(9) 1(8)
|      Conf files: makefile(19)
|    Folder (osshkeys): more than 20757 files
|      File types: html(16165) o(639) json(580) timestamp(481) d(419) z(363)
|                  js(269) rlib(186) rmeta(150) bin(91)
|      Conf files:
```
---
Output of `code --list-extensions --show-versions` :
```text
abusaidm.html-snippets@0.2.1
anseki.vscode-color@0.4.5
austin.code-gnu-global@0.2.2
bungcip.better-toml@0.3.2
donjayamanne.githistory@0.4.6
eamodio.gitlens@9.8.1
EditorConfig.EditorConfig@0.13.0
eg2.vscode-npm-script@0.3.7
esbenp.prettier-vscode@1.9.0
HookyQR.beautify@1.5.0
jorgeserrano.vscode-csharp-snippets@0.3.1
MS-CEINTL.vscode-language-pack-zh-hant@1.34.2
ms-python.python@2019.5.17517
ms-vscode.atom-keybindings@3.0.6
ms-vscode.cpptools@0.23.1
ms-vscode.csharp@1.19.1
ms-vscode.mono-debug@0.15.8
octref.vetur@0.21.0
PKief.material-icon-theme@3.8.0
rust-lang.rust@0.6.1
ryu1kn.partial-diff@1.4.0
sadesyllas.vscode-workspace-switcher@1.13.1
serayuzgur.crates@0.4.3
Shan.code-settings-sync@3.2.9
twxs.cmake@0.0.17
vector-of-bool.cmake-tools@1.1.3
vncz.vscode-apielements@0.6.7
xabikos.JavaScriptSnippets@1.7.2
zhuangtongfa.Material-theme@2.24.0
```

**Comment by Tyriar** [comment]
The OP's issue was likely related to the typescript extension which has changed a lot since this was reported so I'm going to close this off.

@Leo1003 please create a new issue if it's not already in https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-watcher
