### ISSUE TITLE
Minor: Find in folder buggy when project name includes parentheses

### ISSUE THREAD

**Issue by dominic-p** [Microsoft/vscode#66889]
- VSCode Version: 1.30.2
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Add a folder to a multi-root workspace and include parentheses in the name property (e.g. `{ "name": "My Cool Website (example.com)" }`)
2. Use the "Find in folder..." feature to try to search within that folder or any of its sub-folders
3. See results from all folders in the entire workspace instead of just the folder you wanted to search in

Does this issue occur when all extensions are disabled?: Yes

This might be related to #61297, but it was different enough that I thought it deserved its own issue. It's not a big deals since you can just remove the parentheses and everything works as expected, but it was pretty hard for me to figure out what was causing the behavior.

**Comment by roblourens** [comment]
This is actually a separate issue, and it should already be fixed in Insiders now.

**Comment by dominic-p** [comment]
Wow, thanks for the quick response. Sorry to report something that's already fixed.

**Comment by roblourens** [comment]
Not a problem at all :)
