### ISSUE TITLE
Assign keyboard shortcut for filter on type mode toggle

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66899]
Two options I see here:

1) Steal Cmd + F to no longer open find widget while the focus is in the list.
2) Use some obscure shortcut like a key chord

I would go with 1) as the filter widget is more scoped find widget, and I think it should replace the cmd + F
When this command is triggered I would expect the widget to expand for some time.

**Comment by joaomoreno** [comment]
> Steal Cmd + F to no longer open find widget while the focus is in the list.

I would not do this. You should start to think about an Explorer/Search integration and you will definitely want to have Cmd F for this.

**Comment by joaomoreno** [comment]
We should at least add a command.

**Comment by joaomoreno** [comment]
Added command: `list.toggleFilterOnType`.
