### ISSUE TITLE
Integrated Terminal not working

### ISSUE THREAD

**Issue by dudiakash1996** [Microsoft/vscode#66894]
- VSCode Version:1.30.2
- OS Version:Microsoft Windows version 1607 (OS Buid 14393.2724)

Steps to Reproduce:

1.Open VSCode
2. Open a folder
3. Ctrl + Shift + `
Error Message: The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)
4. I tried with Powershell also issue is still there.
5. Visual Studio is not running in compatibility mode so please suggest a different solution.
6. I don't have any extensions in the code. 
7. I tried with users and system version both are giving same issue

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dudiakash1996** [comment]
I tried to with these solutions, they didn't work please suggest something else.

**Comment by Tyriar** [comment]
That version of Windows is awfully old, can you update?

**Comment by dudiakash1996** [comment]
This is my company laptop and my colleagues are using same windows and they are able to access terminal without any issues

**Comment by Tyriar** [comment]
Hmm, exit code 2 might mean file not found https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

Does C:\WINDOWS\System32\cmd.exe actually exist? Is Windows installed in some non-standard location? What happens if you run `C:\WINDOWS\System32\cmd.exe` inside a regular cmd.exe window?

**Comment by dudiakash1996** [comment]
The File is there I checked

**Comment by Tyriar** [comment]
@dudiakash1996 what happens if you run C:\WINDOWS\System32\cmd.exe inside a regular cmd.exe window?

**Comment by dudiakash1996** [comment]
It works fine, I am able to run the commands with no issues. Issue is in the vs code terminal only.

**Comment by dudiakash1996** [comment]
It shows me this 
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

**Comment by Tyriar** [comment]
Are you using the system or user install? You can check this in Help > About. If you're on the system install could you try with the user install?

**Comment by Tyriar** [comment]
@dudiakash1996 do you have any errors in devtools? (Help > Toggle Developer Tools > Console)

**Comment by dudiakash1996** [comment]
Now I uninstalled system one and installed user one again but the issue is still there

**Comment by dudiakash1996** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND
extensionHost.ts:329 [Extension Host] debugger listening on port 32532
log.ts:157  INFO no standard startup: not the explorer viewlet
notificationsAlerts.ts:40 The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)
t.onDidNotificationChange @ notificationsAlerts.ts:40
extensionHost.ts:235 Extension Host
extensionHost.ts:236 Debugger listening on ws://127.0.0.1:32532/4dc4b745-556f-4f1b-9473-73262c8f6bec
For help see https://nodejs.org/en/docs/inspector

**Comment by dudiakash1996** [comment]
These are the issues in console

**Comment by Tyriar** [comment]
Can you share your settings.json file?

Something else to try is to set log level to trace (F1 > "log level"), create a new terminal and see what the output is in Output > Log (Window)

**Comment by dudiakash1996** [comment]
{
    "breadcrumbs.enabled": true,
    "python.pythonPath": "C:\\Users\\akashdudi\\AppData\\Local\\Continuum\\anaconda3\\pythonw.exe",
    "terminal.integrated.cwd": "C:\\Users\\akashdudi\\btkyc",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "explorer.confirmDelete": false,
    "diffEditor.ignoreTrimWhitespace": false
}

**Comment by dudiakash1996** [comment]
How to change log level?

**Comment by Tyriar** [comment]
F1 > "log level"

![image](https://user-images.githubusercontent.com/2193314/51642283-7e994f80-1f1d-11e9-8914-f11c0b34db35.png)

---

If this path does not exist it is very likely the problem:

```
"terminal.integrated.cwd": "C:\Users\akashdudi\btkyc"
```

**Comment by dudiakash1996** [comment]
Yes, this path doesn't exist what can I do to solve that?

**Comment by dudiakash1996** [comment]
I removed this "C:\Users\akashdudi\btkyc" and now it's working

**Comment by Tyriar** [comment]
Looks like you were seeing https://github.com/Microsoft/vscode/issues/17450
