### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xinbingyao** [Microsoft/vscode#66891]
Issue Type: <b>Bug</b>

when i modify svg's attribute 'fill' to empty string, after saved, when i use tab to indent html or js, it does not work

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.6
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.7
vscode-language-pack-zh-hans|MS-|1.30.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
vscode-css-peek|pra|2.2.0
vscode-icons|rob|8.0.0
ayu|tea|0.17.0
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.0.3
quokka-vscode|Wal|1.0.177

(2 theme extensions excluded)

</details>

**Comment by ConduciveMammal** [comment]
@xinbingyao Do you use an extension called Auto Rename Tag? I'm encountering this exact issue and found this extension to be causing it.

https://github.com/formulahendry/vscode-auto-rename-tag/issues/87

**Comment by xinbingyao** [comment]
> @xinbingyao Do you use an extension called Auto Rename Tag? I'm encountering this exact issue and found this extension to be causing it.
> 
> [formulahendry/vscode-auto-rename-tag#87](https://github.com/formulahendry/vscode-auto-rename-tag/issues/87)

Yes, i used it. Thank you very much for your important information!
