### ISSUE TITLE
Markdown preview handles escaping incorrectly 

### ISSUE THREAD

**Issue by vors** [Microsoft/vscode#6689]
Markdown preview rendered should treat `\<` as `<`, `\[` as `[` and so on

- VSCode Version:

Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:29:20.776Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: Windows 10

Steps to Reproduce:

1. create a file foo.md with content

```
SYNOPSIS
Add-GistFile -Id \<string\> -Path \<string\[\]\> \[\<CommonParameters\>\]
```

2. Open markdown preview for it

## Expected result

SYNOPSIS
Add-GistFile -Id \<string\> -Path \<string\[\]\> \[\<CommonParameters\>\]

## Actual result

![image](https://cloud.githubusercontent.com/assets/816680/15482457/9fd7a848-20e4-11e6-802c-5bfd58786412.png)

**Comment by rebornix** [comment]
This is the default behavior of Markdown, if you are going to escape `<` or `>`, use `&lt;` or `&gt;`. See https://daringfireball.net/projects/markdown/syntax#autoescape for more info.

**Comment by vors** [comment]
That's true for the original markdown spec that @rebornix referenced. 
I'm not an expert in markdown variations, but I would guess that VSCode / Atom preiew is oriented more to [CommonMark](http://commonmark.org/) then to the original (Jonh Gruber's) markdown.

For example, VSCode supports ``` and ~~~ syntax for codeblocks, which is **not** part of the original markdown [spec](https://daringfireball.net/projects/markdown/syntax#precode).

I would suggest follow CommonMark anyway, because
1) it has a clear spec with test sets
2) it's widely adopted and mostly compatible with GitHub Flavored Markdown.

From that point of view, CommonMark has a clear guidence about [back-slash escaping](http://spec.commonmark.org/0.25/#backslash-escapes).

**Comment by rebornix** [comment]
@vors, thanks your detailed info. Currently we are using markd.js , which targets both the original makrdown and gfm. That's why you can see those fenced blocks work and terrible escaping hack. But good news is, like what you suggested, we are moving the markdown parser to commonmark and we will supporr backslash escaping.

**Comment by vors** [comment]
It looks like markd.js [will switch to CommonMark](https://github.com/chjj/marked/issues/756).

As is, it's not GFM compatible (because horrible escaping hack works just fine on github).
Check it out

\< horrible hack \>

I personally find `"\<"` **way** more readable in the plain-text then `"&lt"`.

**Comment by rebornix** [comment]
Agree, current markd.js GFM support is not 100% compatible (IMHO) but that's Okay. Once we finish #6106 we can revisit this issue.

**Comment by bpasero** [comment]
Seems to work ok for me with our new markdown extension:

![image](https://cloud.githubusercontent.com/assets/900690/16123181/68f4b352-33ea-11e6-9682-f1bfe451536f.png)
