### ISSUE TITLE
Settings search does not search within values

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66893]
1. Open settings, search for "filter"
2. Workbench > list > Keyboard navigation is not found

Notice that one of the values for that setting is "filter" and I would expect it to be found.
@alexandrudima and me were also hitting this couple of days ago

**Comment by usernamehw** [comment]
Duplicate of #56712 ?

**Comment by isidorn** [comment]
@usernamehw looks similar, good find! Though I think the issue there is only for edited values, I see this for all values. So let's leave it up to @roblourens to possibly close
