### ISSUE TITLE
List filter widget should be dragged only in top row

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66897]
I think allowing to drag the widget only on the top but not only in the corners is the way to ge here. So top all the way,  like the debug toolbar does it so we also get some consistency.

The reason I say this is because putting it in the bottom feels really disconnected and I think more users would like to put it top middle, than bottom corner.

**Comment by joaomoreno** [comment]
Will disable the bottom corners.

**Comment by isidorn** [comment]
Makes sense. Bottom corners are disabled -> adding verified label.
