### ISSUE TITLE
Proxy support setting removes GET query parameters from URLs on extension's GET requests

### ISSUE THREAD

**Issue by SounD120** [Microsoft/vscode#66892]
- VSCode Version: 1.30.2 - 1.31-insiders
- OS Version: Windows 10 (1803), macOS 10.14.2 Mojave

Steps to Reproduce:

1. Clone test VS Code extension with `git clone https://github.com/SounD120/proxysupporttest.git` command
2. `cd proxysupporttest`
3. `npm i`
4. `code .`
5. Open VS Code Preferences->Settings, find and enable Proxy Support setting with `on` or `override` option.
6. Open debug tab and run `Run extension`
7. In Extension Developement Host call command pallete and run `Proxy Support Test: Start test HTTP server` command
8. Call `Proxy Support Test: Send HTTP request to server` command from command pallete

You will see the VS Code information message window with URL which hit the server.

In my test repo I used such URL : `http://127.0.0.1:8080?platform=android`

Without Proxy Support setting HTTP get request returns : `/?platform=android`
With Proxy Support setting HTTP get request returns: `/`

Also this setting is enabled in `1.31-insiders` by default, so I want to clarify would it be enabled in release 1.31 version?

Observation: this might be connected to [this code](https://github.com/Microsoft/vscode/blob/2fe9de851100cf6a1d5c3ff41849d8b5b2ebb4a4/src/vs/workbench/node/proxyResolver.ts#L234-L243)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@SounD120 Thanks for the detailed bug report!

The setting will be enabled as 'override' in the upcoming release.
