### ISSUE TITLE
Emmet in XSLT stopped working

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#66895]
Issue Type: <b>Bug</b>

Make an XSLT file with basic structure.

type 'wh'+tab -> it autocompletes to 'when' (not <xsl:when>)
type 'if'+tab -> it autocompletes to 'iframe' (not <xsl:if>)

VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:20:50.343Z)
OS version: Windows_NT x64 10.0.18309

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
Bookmarks|ale|10.2.0
vscode-twig-pack|baj|1.0.0
git-easy|bib|1.11.0
vscode-intelephense-client|bme|0.8.8
vscode-git-grep|bok|0.0.7
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
go-coverage-viewer|def|1.0.3
xml|Dot|2.4.0
gitlens|eam|9.4.1
git-project-manager|fel|1.7.1
php-debug|fel|1.12.6
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.4
package-watcher|Gre|0.0.2
beautify|Hoo|1.4.7
php-cs-fixer|jun|0.1.94
vscode-language-babel|mgm|0.0.21
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.6.2
Go|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
php-docblocker|nei|1.7.0
quicktype|qui|12.0.46
vscode-icons|rob|8.0.0
iferrblocks|rst|1.1.1
vscode-javascript-booster|sbu|0.10.2
git-merger|sha|0.4.1
code-settings-sync|Sha|3.2.4
stylelint|shi|0.47.0
javascript-typescript|sou|0.0.7
twig|wha|1.0.2
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
Please file the bug to the XML extension you are using, thanks.
