### ISSUE TITLE
Support non file workspace URIs

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#66907]
Support non file workspace URIs

**Comment by sandy081** [comment]
@aeschli @bpasero Implemented the delayed loading of workspace folders strategy for non file workspaces. But this will restart extension host because the first folder has changed. 

@bpasero I think we are restarting the extension host because the `rootPath` will change. Shall we not restart the extension host and just update the `rootPath` with first folder?

**Comment by bpasero** [comment]
> I think we are restarting the extension host because the rootPath will change

Yes

> Shall we not restart the extension host and just update the rootPath with first folder?

We cannot, this will break extensions. The contract is that the `rootPath` is set like a constant on startup.

**Comment by sandy081** [comment]
Isn't the root path resembles Single Folder case? How does it break extensions in a Multi root workspace that goes from 0 to 1 (or >1) folders?

**Comment by bpasero** [comment]
It does not, we always restart the extension host currently.

**Comment by sandy081** [comment]
Fixed extension host restarting issue by delaying listening to workspace change until the workspace is complete. 

Second issue to fix is delay starting extension host until workspace is complete so that the `rootPath` is set correctly.
