### ISSUE TITLE
List highlight filter: when there are no matches up/down should traverse all nodes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66904]
1. Have highlight mode on
2. Type somthing which has not matches
3. Up / down are no ops

If there are not matches the up/down arrows should navigate between all elements. Since users could easily end in a situation where they type something bogus and up/down arrows become disabled.

**Comment by IllusionMH** [comment]
A bit related - maybe it makes sense also change the color or border of the widget when there are no matches, for additional visual feedback?

**Comment by joaomoreno** [comment]
Also implemented @IllusionMH's suggestion:

![image](https://user-images.githubusercontent.com/22350/51688959-f2a72680-1ff5-11e9-9ca0-a294d011f0c8.png)
