### ISSUE TITLE
editor.wordwrap doesn't work for java

### ISSUE THREAD

**Issue by zhangqi5** [Microsoft/vscode#66915]
- VSCode Version: 1.30.2
- OS Version: Windows 10

Steps to Reproduce:

1. Specify "editor.wordWrap": "off" in user or workspace settings.
2. Format Java code, which still wraps.

Does this issue occur when all extensions are disabled?: Yes/No
No. But none of the formatting works in this mode.

**Comment by akaroml** [comment]
@yaohaizh please also have look whether this is related to Java LS.

**Comment by alexandrudima** [comment]
@zhangqi5  `"editor.wordWrap": "off"` is a rendering option to avoid having a horizontal scrollbar.

It does not impact in any way any formatter.

**Comment by zhangqi5** [comment]
Thanks for checking this out. It was my wrong. I should have used "editor.rulers" to control the formatter.
