### ISSUE TITLE
List highlight filter: Support other filters

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#66913]
It would be nice to have option to disable fuzzy match on folders/files.
Use case:
I'm looking for Webpack loaders inside `node_modules`. If I type `load` or even `loade` I will have a lot of matchings like `global-modules-path`, `load-json-file`, `lodash.clonedeep` and several files inside opened `src` and `test` folders.
In particular case I can search for `loader` ant it will still match `babel-plugin-transform-es2015-shorthand-properties`, `src/utils/check-local-folder.ts` etc.

Ability to disable fuzzy much for similar cases will drastically reduce number of matches that are not relevant.

As mentioned in #66912 it might be added to added to List filter widget, same panel as "Filter on type" toggle.

**Comment by joaomoreno** [comment]
Good point.

@IllusionMH What filter function would you expect if not fuzzy? Case insensitive substring matching?

**Comment by IllusionMH** [comment]
> Case insensitive substring matching?

Yes, this will be expected behavior. At least for me.

**Comment by joaomoreno** [comment]
@IllusionMH Would a setting be sufficient? I don't want to overpopulate the widget's buttons.

**Comment by IllusionMH** [comment]
@joaomoreno I thought it will be great to have it widget.
In this way it can be switched quickly - as soon as it is clear that fuzzy match bring too much noise, and switch back to fuzzy if it is unclear if filename will have `-` or `_` somewhere in name.

Opening User or Workspace settings each mentioned case seems much slower and not easy to find/use.

**Comment by isidorn** [comment]
I would put it in a setting. This is not something which you change 5 times a day, but once in lifetime imho.
Widget needs to be minimalistic.

**Comment by IllusionMH** [comment]
I use similar approach in Search, during some activities dozen times a day.
As soon as I see that there is to much noise in search, I need only to click on "Match Whole Word" and/or "Much Case" in field above to limit results.
I understand that widget is much smaller, but might be used for the same purpose often.

As I see - at max (with all my proposed items to widget) it will be 4 actions top: Limit to siblings, Toggle fuzzy, Filter, Dismiss).
May be add action to widget with option? So who would need this switch will have more actions, and other users will have minimalistic widget. Harder to implement, but would make toggle more usable.

**Comment by joaomoreno** [comment]
I might just do a dropdown action if we start getting so many actions up at the top.

**Comment by IllusionMH** [comment]
So there is a change to get it in widget instead of settings?
Moving this to dropdown instead of User settings will be awesome!

**Comment by abhijit-hota** [comment]
Are there any real use cases of the current behavior? I don't understand. 

When I search the explorer pane like this, I do so to search for filenames. when I type in "modal", I want all the files containing the word, "modal" in them and not the files containing the individual letters. And if I'm not wrong I don't think anyone wants that as I can see by the number of closed issues.

So can you elaborate on how is this out-of-scope?

**Comment by joaomoreno** [comment]
Thanks for checking. Out of scope means:

> We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.
> 
> If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Thanks for your understanding and happy coding!
