### ISSUE TITLE
List highlight filter: Toggle to highlight/step only on in same folder

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#66912]
List highlight filter (I hope I correctly name this feature) is awesome feature that I have been waiting for! Thank you! 🙌 

Currently it navigates user across all visible folders/files that has fuzzy match.
In case when I want to find some folder inside of long `node_modules` I will be still navigated through all visible filse/folders.

So if I'm typing `lo` inside of `node_modules` (when folder inside of `node_modules` highlighted) I will still have match on `package-lock.json`, `yarn.lock`, and `src/locales`.

Would be nice to have ability to limit match only inside parent folder(node).
So when I have `axios` folder selected inside `node_modules` and type `lo` - it will only highglight `babel-loader`, `lodash`, and `loglevel` package folders, but **not** `package-lock.json`, `yarn.lock`, and `src/locales`.

It might be added to List filter widget, same panel as "Filter on type" toggle.

**Comment by joaomoreno** [comment]
Interesting.
