### ISSUE TITLE
List highlight filter: Scroll highlighted folder/file into view

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#66917]
When I type in explorer view with "Filter on type" disabled - it is usual case that highlighter items won't be in visible area.
I have to scroll down or up to find highlighted items.

Would be nice to have list scrolled to either nearest (to the current view) match, next match (when scrolled down) or first (top) math in whole list (I doubt that it is good option).

As workaround I use `Arrow Down` `Arrow Up` ATM.

UPD. Is it duplicate of "Filtered focus navigator (filter or just highlight and then move up & down)" point in #64231?

**Comment by joaomoreno** [comment]
Same as #67083
