### ISSUE TITLE
Cannot use both dotnet and gulp tasks

### ISSUE THREAD

**Issue by VanKichline** [Microsoft/vscode#6691]
- VSCode Version: 1.1
- OS Version: Linux/Mint

Steps to Reproduce:

1. Install DotNet Core RC2 & upgrade generator-aspnet
2. Scaffold a new Web Application
3. Open app in VS Code 1.1.1
4. Type F1, followed by task, select 'Run Task'

Expected:
List of Gulp tasks

Actual:
Build

Notes:
tasks.json is set up for "command": "dotnet".  If I delete this file and configure a new one for Gulp, I can enumerate my Gulp tasks, but F5 no longer works.
The documentation and file format seem to indicate that there's no way to configure *two* task runners, so I see no way to run my DotNet Core app *and* use Gulp.

I plan to use React.  I don't see how I can accomplish this w/o access to a task runner other than dotnet.  I *must* configure both dotnet and gulp somehow.

**Comment by dbaeumer** [comment]
Dups #981
