### ISSUE TITLE
Test: contributes.resourceLabelFormatters

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66910]
- [x] any os @aeschli 
- [ ] any os @rebornix

Complexity: 3

Now it is possible for extensions to contribute resource label formatters. Have an extension, in the `package.json` under the `contributes` section add a new `resourceLabelFormatters` contribution. Verify:
* Naming and structure of fields make sense
* Authority field is simple glob matched (you can use `*`)
* Once the new `resoruceLabelFormatter` is registered it is respected accross the workbench (you can see this anywhere in the workbench where we display URIs - for example explorer hover)
* If there are more resourceLabelFormatters which match the same URI we choose the most specific match
* Uninstalling your extension and the URIs are no longer displayed according to rules you specified

For examples on `resourceLabelFormatters` check our vscode extensions.

fyi @chrmarti you migth volunteer to test

**Comment by rebornix** [comment]
Not sure if I understand this contribution correctly, but I didn't make it as what's being documented. As the schema says, I can specify scheme as `file` and authority as `*`, which should match local files in explorer, but my `formatting` doesn't seem to take effect. I'd love to know first if I make any wrong assumption.

```
    "resourceLabelFormatters": [
      {
        "scheme": "file",
        "authority": "*",
        "formatting": {
            "label": "MYLABEL:${path}",
            "separator": "-",
            "tildify": true,
            "workspaceSuffix": "*"
        }
      }
    ]
  },
```

**Comment by isidorn** [comment]
@rebornix nice example, however the issue here is that `*` does not match an empty string. This is an issue in our glob match library and @bpasero can comment more if this is unexpected behavior and what should be used to match the empty string.

We have already covered this in self hosting and in unit tests so if you do not find a nice example to test it is fine and feel free to close this test plan item.

**Comment by bpasero** [comment]
Arguable a bug in the glob library, created https://github.com/Microsoft/vscode/issues/67651

**Comment by rebornix** [comment]
Sounds good to me, thanks for the explanation.
