### ISSUE TITLE
Terminal have More Space

### ISSUE THREAD

**Issue by abas619** [Microsoft/vscode#66911]
- VSCode Version: 1.30.2
- OS Version: win 10 64bit

Steps to Reproduce:

Hello
When I open the terminal, I encounter a lot of space. I also sent the photo, I think this can be done.
help me

https://drive.google.com/file/d/17lvBb6UdVkr6yi0AacuEtTC4nDjpeibZ/view?usp=sharing

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
