### ISSUE TITLE
Increase size (width) of minimap is not possible

### ISSUE THREAD

**Issue by s-a** [microsoft/vscode#66929]
It is not possible to increase the size of the minimap. The default setting is a little bit small on very large screens with a high resolution.

```javascript
"editor.minimap.maxColumn": 400
```

Maybe this is related to https://github.com/Microsoft/vscode/issues/20931 where max width is `150px`

Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by philn16** [comment]
https://github.com/Microsoft/vscode/issues/21773

**Comment by connor4312** [comment]
This seems similar to #64477 -- do the changes in https://github.com/microsoft/vscode/pull/82265 do what you're after?

**Comment by s-a** [comment]
@connor4312 That' s it! 💯
