### ISSUE TITLE
A large blank in terminal, work in 2560x1440 resolution

### ISSUE THREAD

**Issue by RobinCodeX** [Microsoft/vscode#66927]
- VSCode Version: 1.30.2
- OS Version: Windows 10 (Windows_NT x64 10.0.17763)

Steps to Reproduce:

1. Open terminal
2. Using Powershell or Git bash
3. Enter command `yarn -v`

Does this issue occur when all extensions are disabled?: Yes

When the height of the terminal window is less than 516px(approximately), I have enter command `yarn -v`, it will appear a large blank, if the height is more than 516px, it's normal.

My screenshot:
Git bash:
![image](https://user-images.githubusercontent.com/8408783/51542108-6da4fb80-1e95-11e9-9ecd-94d08b479cf4.png)

Git bash normal:
![image](https://user-images.githubusercontent.com/8408783/51542149-82818f00-1e95-11e9-86cc-0f72224b004d.png)

Powershell:
![image](https://user-images.githubusercontent.com/8408783/51543213-076da800-1e98-11e9-9fe4-f5352f163849.png)

Powershell normal:
![image](https://user-images.githubusercontent.com/8408783/51543262-21a78600-1e98-11e9-8d23-bbc1d665b7fa.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
