### ISSUE TITLE
List highlight filter: Not all characters from match are highlighterd

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#66923]
Issue Type: <b>Bug</b>

1) Create folders `babel-loader` and `babel-plugin-transform-es2015-shorthand-properties` packages (in my case packages installed in `node_modules`)
2) Expand parent folder (`node_modules`)
3) Type `babel-loader`

Both folders matched, however for `babel-plugin-transform-es2015-shorthand-properties` characters after `transform` are not highlighted.

There are no dependency on "Filter on type" or Tree: Horizontal Scrolling settings, number of separate highlight ranges.

As I see - only first 32 characters can be highlighted.

Is it expected behavior or a bug?

VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:20:50.343Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (21.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

Extensions: none

**UPD.** Added screenshot

![image](https://user-images.githubusercontent.com/1312662/51602460-b4cfd280-1f0f-11e9-9f8c-b6cecc40b3f7.png)

**Comment by joaomoreno** [comment]
@jrieken Does FuzzyScore have a limit here?

**Comment by jrieken** [comment]
Yeah, the max length is 53 so that we can store result as "bitmask" where ones mean character matches and zeros means character doesn't match.

**Comment by joaomoreno** [comment]
Any thoughts on how to unbound this?

**Comment by joaomoreno** [comment]
@jrieken Currently, `FuzzyScore` is `[score, matches, offset]`. What if we change it to `[score, offset, ...matches]` in which matches would be an unbounded collection of bitmasked index positions?

**Comment by jrieken** [comment]
> Any thoughts on how to unbound this?

This is on purpose. It's all optimised for intellisense and it's rare that you type such long prefixes or that you match against such long symbol names. There are currently no plans to change this tho I will look into the 32 character issue

**Comment by jrieken** [comment]
Yeah, that 32 character issue is real. @joaomoreno Would be happy with a limit of 52 or do you want infinite length matches?

**Comment by jrieken** [comment]
Bummer... Turns out I didn't know that bit-operations don't go all the way to `Number.MAX_SAFE_INTEGER` but only to 32. That's the culprit here - I will see what I can do.

**Comment by joaomoreno** [comment]
@jrieken Shouldn't be too much of a hassle if this is unbounded, so I would definitely prefer that way. Let me know if I can help.

**Comment by jrieken** [comment]
The limit is now actually at 53. Closing - let's see how we can go with this.
