### ISSUE TITLE
File Explorer: Adding file to selected by Mouse should not open it

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#66925]
Issue Type: <b>Bug</b>

* Have 0 selected files
* Click on a file while holding <kbd>Ctrl</kbd> `"workbench.list.multiSelectModifier": "ctrlCmd"`

VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:20:50.343Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
Agree this is the behavior. However i am not sure it is undesired.
Not fixing it until more people complain.

**Comment by usernamehw** [comment]
@isidorn, is this an intentional breaking change? Was new behavior considered better?

**Comment by isidorn** [comment]
@usernamehw yeah this is a breaking change, I do not consider the new behavior better. I would just like more feedback from usesr before writing code that changes this.

**Comment by usernamehw** [comment]
Now it's even opening it to the side 😅. Where are those complaining people when you need them...

**Comment by inwardmovement** [comment]
Well I add myself to complainers , but I fear 2 complaints in 5 months is not enough yet? Haha
#74573
