### ISSUE TITLE
vscode taking too  much CPU 

### ISSUE THREAD

**Issue by proudlily** [Microsoft/vscode#66920]
- VSCode Version:1.30.2
- OS Version:Linux x64 4.20.1-arch-1-ARCH
- Electron:2.0.16

Steps to Reproduce:
1. open the vscode
2. then ,see *top* in the shell,the cpu is much more buzy
below:

 process | USER  | PR  |NI  |  VIRT |       RES   |       SHR   |       %CPU  |   %MEM   |  TIME+   |      COMMAND
-- | --| --| --| --| --| --| --| --| --| --
   18233    |      don    |   20   |  0   |   1040056 |   171772  |   51060 R   |   107.6 |    2.2     |   10:32.92   |electron2 
 
the cpu is '107.6' or more .

Does this issue occur when all extensions are disabled?: Yes/No(YES)
# SystemInfo:

Item | Value
-- | --
CPUs | Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Memory (System) | 7.62G(5.8G free )
Process Argv | /opt/visual-studio-code
Screen Reader | no
VM | no

# Extensions(0)

**Comment by sandy081** [comment]
Can you please follow the wiki and provide the necessary information - https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by ddzy** [comment]
> * VSCode Version:1.30.2
> * OS Version:Linux x64 4.20.1-arch-1-ARCH
> * Electron:2.0.16
> 
> Steps to Reproduce:
> i using the vscode to write go.but recently i find that the cpu became much busy.so i see the top.
> this is the below:
> 
> * process  USER   PR  NI    VIRT        RES          SHR        %CPU  %MEM     TIME+        COMMAND
>   18233     don       20   0    1040056  171772  51060 R  86.7      2.2             10:32.92    electron2
> 
> the cpu is '86.7' or more .
> 
> Does this issue occur when all extensions are disabled?: Yes/No(No)

same issue

**Comment by proudlily** [comment]
> Can you please follow the wiki and provide the necessary information - https://github.com/Microsoft/vscode/wiki/Performance-Issues

following :)

**Comment by dbaeumer** [comment]
@proudlily any news?

**Comment by dbaeumer** [comment]
I am closing the issue. Please ping if you have provided additional information.
