### ISSUE TITLE
Column selection is absent

### ISSUE THREAD

**Issue by KANTARMahirSoner** [microsoft/vscode#66922]
Issue Type: <b>Bug</b>

Alt+Click does not work to select text in column mode.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.59GB free)|
|Process Argv|\\mvt\usr\Perso\NR\047\DMW7447\Downloads\C400RV20190110080034 (PARTIEL).txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.23.0
referenceshelper|gay|0.2.3
vscode-azureappservice|ms-|0.11.0
vscode-azurefunctions|ms-|0.13.1
vscode-azurestorage|ms-|0.5.0
vscode-cosmosdb|ms-|0.9.1
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
csharp|ms-|1.17.1
PowerShell|ms-|1.10.2
vscode-node-azure-pack|ms-|0.0.5
team|ms-|1.144.1
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.5.1
azure-iot-toolkit|vsc|2.1.0

</details>

**Comment by alexandrudima** [comment]
The gesture is to drag and then press alt. Or if dragging is not desirable, then shift+alt+ click
