### ISSUE TITLE
List filter: esc should steal keybinding only when filter widget shown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66926]
1. Peek references on something
2. Click in the tree on the right of the peek references widget
3. Press `esc` -> widget does not get closed

This works nicely in stable

**Comment by isidorn** [comment]
Also assigning to @joaomoreno since he might have broken it with the list filtering.
In that case, esc to close filter should only be enabled when I have actually typed something

**Comment by isidorn** [comment]
After https://github.com/Microsoft/vscode/issues/66924 it is clear the issue is that esc is being stolen by the filter widget

**Comment by joaomoreno** [comment]
Great catch!

**Comment by joaomoreno** [comment]
@jrieken Sorry for the disruption.

**Comment by isidorn** [comment]
Works fine now, adding verified label

**Comment by infctr** [comment]
Was it resolved? I still can't close the peek definition window unless I click in the editor again

```sh
❯ code-insiders -v
1.31.0-insider
2d79ffe0cd84515a4c771fcbd7294c2448d97826
x64
```
