### ISSUE TITLE
Keyboard Shortcuts for Non-Modal Dialogs

### ISSUE THREAD

**Issue by elliot-nelson** [Microsoft/vscode#66933]
For modal (system) dialogs, keyboard shortcuts are already supported, depending on operating system.  For example, I can navigate the following popup on MacOS by pressing {Command} plus the first letter of the desired button.

<img width="472" alt="screen shot 2019-01-22 at 12 08 40 pm" src="https://user-images.githubusercontent.com/58273/51552438-9bab2100-1e3e-11e9-8f0e-4096b1ebaaf4.png">

For non-modal (non-system) dialogs, however, I can't interact with them except clicking with the mouse, which can really interrupt flow.  It would be ideal if there was an option I could turn on where any non-modal dialog would "take over" {Command+Key} while it was on screen.  I'd also be ok with a separate shortcut key I could press that highlighted the non-modal dialog and let me tap the appropriate first letter (this might be less disruptive).

<img width="470" alt="screen shot 2019-01-22 at 12 09 18 pm" src="https://user-images.githubusercontent.com/58273/51552433-98b03080-1e3e-11e9-8222-f19b77015cc9.png">

There's a related issue closed in 2017, https://github.com/Microsoft/vscode/issues/31624, but I didn't see a related feature (for the non-modal dialogs).

**Comment by sbatten** [comment]
@elliot-nelson a command does exist to focus notification toasts. It is called `notifications.focustToasts`. You can then use tab to select the option you would like. For any additional info @bpasero

**Comment by elliot-nelson** [comment]
Ah, "toast"!  Learned a new word today, and sure enough, it works like a charm.
