### ISSUE TITLE
Ext host goes away when debugging app service extension

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#66938]
MacOS

`Version 1.31.0-insider (1.31.0-insider)`
`23f534b7b7f439fc39755821ff99ac50fcc10765`
`2019-01-22T06:07:10.804Z`

Steps to reproduce:

git clone https://github.com/microsoft/vscode-azureappservice
cd vscode-azureappservice  && npm install
code-insiders .
Press `F1`, run the build command
Press `F5` to debug
Open the Azure Viewlet

Result: poof, extension host goes away

Works fine in stable.

**Comment by weinand** [comment]
@chrisdias following yours steps resulted in this error message:
<img width="483" alt="2019-01-22_22-15-41" src="https://user-images.githubusercontent.com/1898161/51565935-94623280-1e93-11e9-9b3d-c9b2f3b48b52.png">

After installing "ms-vscode.azure-account" extension I could open the Azure viewlet without problems:

<img width="584" alt="2019-01-22_22-19-40" src="https://user-images.githubusercontent.com/1898161/51566052-e30fcc80-1e93-11e9-8520-67e1cf5c17dc.png">

**Comment by chrisdias** [comment]
yes, sorry, the account extension is required.  @ericjizbamsft cannot reproduce the problem either, but on my machine its 100% of the time. are there things I could try to narrow the problem down?

**Comment by weinand** [comment]
Before pressing F5, open the Dev Tools console. 
Then press F5. Is there any interesting output when the window disappears?

Disable all extensions but the account extension. Does the problem still occur?

Run insiders on a fresh user data:
- quit VS Code Insiders
- (temporarily) rename `~/Library/Application Support/Code - Insiders`
- launch VS Code Insiders and try to reproduce
- If it still fails quit VS Code Insiders and restore previous name
