### ISSUE TITLE
Automatically Update Imports For Moved Files not working

### ISSUE THREAD

**Issue by patelyogesh-in** [Microsoft/vscode#66937]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Have a JS file which is used as import in multiple files
2. Try to move the file to another folder.
3. This shows a message that the file is being moved

But, after that it's expected to show another prompt to confirm auto update all imports or not. I've below settings:

{
    "javascript.updateImportsOnFileMove.enabled": "prompt",
    "typescript.updateImportsOnFileMove.enabled": "prompt",
    "typescript.tsdk": "./node_modules/typescript/lib"
}

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (7.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sitecore-rocks-vscode|ref|0.0.6

</details>

**Comment by mjbvz** [comment]
Please share some example code. What is the project structure? How is the file imported?

**Comment by patelyogesh-in** [comment]
I am using a Sitecore JSS sample application, which is built on React and runs on Node.

In my case, the root file is **Styleguide-Specimen.js**, which has content as below:
```

import React from 'react';
...

```

Another JS file **index.js** refers to this file by importing it as below:

```
import React from 'react';
import StyleguideSpecimen from '../Styleguide-Specimen';
```

This works fine, but when I move the Styleguide-Specimen.js file to other folder, I am expecting the import path for Styleguide-Specimen.js to be updated with newer path.
It prompts for Moving file, but does not prompt for updating all imports.

**Comment by CoralSilver** [comment]
I was having the same issue working with a monorepo. Adding a [`jsconfig.json`](https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson) to each package got it working for me.

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) at the root of your project with the content:


```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells VS Code to treat all files  in  the workspace as part of the same project (instead of just opened files)

After creating this file, I see file moves/renames working properly on VS Code insiders for a project created using `jss create my-react-jss-app react`
