### ISSUE TITLE
Improve UX  for Post extension install/uninstall/enable/disable 

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#66931]
Issue Type: <b>Bug</b>

When disabling/enabling extensions, not every item shows the `Reload` button in the viewlet. See the gif below as an example, `Debugger for Chrome` and `Nunjucks` do not get this button for reload. In some instances, the `Reload` button flashes for a few seconds and disappears.

<img width="50%" src="https://user-images.githubusercontent.com/35271042/51549891-1284f180-1e20-11e9-80ce-d3675fafba44.gif">

VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:13:01.312Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|-psn_0_1290555|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
prettier-vscode|esb|1.7.3
python|ms-|2018.12.1
code-settings-sync|Sha|3.2.4

(3 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This is expected because of the new feature (Dynamic extension points) https://github.com/Microsoft/vscode/issues/66574

Some extensions can be enabled/disabled without window reload and some needs window reload. Hence you are seeing this.

**Comment by misolori** [comment]
Hmm...because the interaction/feedback is inconsistent it's not clear to the user what is happening. Is the end-goal to allow all extensions to not require a reload or will it still require a reload for some?

If it'll still require a reload for some then we should provide better messaging to be clear that the install is completed (i.e. no reload required).

**Comment by sandy081** [comment]
> Is the end-goal to allow all extensions to not require a reload or will it still require a reload for some?

Depends. I assume in future installing/enabling might never require reload except for language packs which need **restart**. But uninstall/disabling might need reload for most. 

> If it'll still require a reload for some then we should provide better messaging to be clear that the install is completed (i.e. no reload required).

I am not a big fan of adding messages or prompts. Does the reload button is not good enough to know it requires reload or not? I think there was discussion about refresh button - https://github.com/Microsoft/vscode/issues/60053. Are we are going in circles 🤔 ? 

Open to suggestions here

**Comment by sandy081** [comment]
Installing/Enabling an extension will not have a reload, but Uninstalling/Disabling will have reload as we cannot stop running the extension with code without reload. There are also exceptions like theme extensions which do not need reload when uninstalled/disabled. So `reload` gonna be a special state. So how about being a bit verbose like follow:

![image](https://user-images.githubusercontent.com/10746682/51670466-f53e5780-1fc6-11e9-9d0b-be1d611138db.png)

**Comment by isidorn** [comment]
A huge issue I am hitting is the following:
1. I install the extension, my muscle memory thinks I need to press the reload button (which the install buton turned in)
2. Now since we do not require a reload sometims, I accidently click Uninstall which is exactly the opposite of what I want

@joaomoreno also hits this
@sandy081 let me know if you would like a new issue for this

**Comment by jrieken** [comment]
It's the first time that I interacted with disabling extensions without reload and while I know that running extensions need a reload it wasn't clear to me. I though the feature is buggy, esp for extensions that activate on startup. Ideas

* indicate that an extension is running
* call the command "Disable after Reload" for those extensions that already run 
* show "Reload to Disable" instead of "Reload"

**Comment by sandy081** [comment]
@isidorn I think your concerns are all related to this issue. I would use this issue to collect the feedback and ideas and get to a conclusion.

**Comment by stevencl** [comment]
I had the same experience. I was convinced that an extension that I had installed wasn't actually installed. It might be good to add a badge to the extension landing page that says 'Active' and ensuring that the extension shows up in the enabled list. For example, here's the state after installing the chrome debugger extension (note that the chrome debugger doesn't show up in the enabled list):

![image](https://user-images.githubusercontent.com/1704059/51910343-d70d9880-23c6-11e9-928c-218d33a27fa3.png)

**Comment by weinand** [comment]
It would help if the extension viewlet would automatically switch to the "Installed Extensions" after an Install. In my case it just stayed on the "Marketplace results".

**Comment by Tyriar** [comment]
In Dark+ this is #767676 on #252526 which fails WCAG AA for normal sized text
