### ISSUE TITLE
Test: Add support for external grammar injections

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6693]
- [ ] Win - **@alexandrudima**

You can now contribute injection grammars using the regular 'grammar' contribution point:

```json
"grammars": [
            {
                "scopeName": "source.todo",
                "path": "./syntaxes/todo.json",
                "injectTo": [  "source.js", "source.ts" ]
            }
```

Check out https://github.com/Microsoft/vscode-textmate/blob/master/test-cases/first-mate/fixtures/todo.json for an example of an injection grammar.

- Try to get the todo example to work.

**Comment by alexandrudima** [comment]
I could not get it to work
