### ISSUE TITLE
Right click on workspace folder doesn't pass uri to extension command

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#66942]
Issue Type: <b>Bug</b>

Repro steps:
1. Contribute a command to a folder's context menu:
    In package.json:
    ```
    "menus": {
        "explorer/context": [
            {
                "command": "extension.sayHello",
                "when": "explorerResourceIsFolder == true"
            }
        ]
    }
    ```
    In extension.ts:
    ```
    vscode.commands.registerCommand('extension.sayHello', (target: vscode.Uri) => {
        vscode.window.showInformationMessage(JSON.stringify(target));
    });
    ```
1. Right click on the _root_ of the workspace (doesn't repro for sub folders)
![screen shot 2019-01-22 at 10 58 38 am](https://user-images.githubusercontent.com/11282622/51558944-88478800-1e35-11e9-9647-2ab78ecf714d.png)

Expected: Uri is passed as target
![screen shot 2019-01-22 at 10 58 27 am](https://user-images.githubusercontent.com/11282622/51558918-7b2a9900-1e35-11e9-86e9-89578bbc0427.png)

Actual: Empty object is passed (Only repros on insiders)
![screen shot 2019-01-22 at 10 57 53 am](https://user-images.githubusercontent.com/11282622/51558930-81207a00-1e35-11e9-8a4e-a840de85c053.png)

Full repro here (branch ej/uri): https://github.com/EricJizbaMSFT/helloworldext/tree/ej/uri

VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:13:01.312Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
python|ms-|2018.12.1
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
java|red|0.37.0
vscode-java-debug|vsc|0.16.0

</details>

**Comment by bpasero** [comment]
Adding @isidorn given that the explorer was recently rewritten. I would expect this should work.

**Comment by isidorn** [comment]
I can repro this. And am looking into a fix

**Comment by isidorn** [comment]
@EricJizbaMSFT thanks for nice steps and for using vscode insiders.
You can try the fix in tomorrows vscode insiders and let us know if it fixes the issue for you.

**Comment by EricJizbaMSFT** [comment]
Fixed for me now - thanks!

**Comment by isidorn** [comment]
Thanks, adding verified label
