### ISSUE TITLE
Copying a text file into the Explorer window adds extra line

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6694]
- VSCode Version: 1.1.0-alpha
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. Create a txt file on the desktop containing some text (ex. "test") on one line
2. Drag the file into the explorer window to copy it into the open folder in Code

When the file opens in Code there is an added newline at the end of the file. Opening the file on the desktop still shows the text on one line without any other lines.

**Comment by bpasero** [comment]
I am not sure if this is a node issue but if I:
* `echo "hello" > info.txt`
* `fs.readFileSync("info.txt")`

The resulting buffer contains a terminating `\n`
