### ISSUE TITLE
VS Code Snippets: Snippet substitution does not happen when typing into the tab stop

### ISSUE THREAD

**Issue by pudupa** [Microsoft/vscode#66949]
I was trying out snippets, and need to nest one snippet as content inside of another at the use point. Here is an example:

	"oj-test1": {
		"scope": "html",
		"prefix": "ojt1",
		"body":
		  "<oj-test1 value='$1'>\n\t$2\n</oj-test1>"
		,
		"description": "test1 element."
	},
	"oj-test2": {
		"scope": "html",
		"prefix": "ojt2",
		"body":
		  "<oj-test2 value='$1'></oj-test2>"
		,
		"description": "test2 element."
	}

In HTML editor of VSCode, type ojt1, let the snippet substitute, tab until the tab stop $2. Here if I type ojt2, I expect the second snipped to be substituted, but it does not recognize the prefix and do so. As workaround, I have to hit other keys like back space, wipe out the placeholder, or press enter and then start typing ojt2.

**Comment by jrieken** [comment]
It's this setting: `"editor.suggest.snippetsPreventQuickSuggestions"`
