### ISSUE TITLE
Cannot enable/disable extensions when running from source

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#66945]
It used to be possible for me to have extensions in `$HOME/.vscode-oss-dev/extensions` which I could then manage using our UI. I could also manage built-in extensions. Now, I cannot do this anymore:

![image](https://user-images.githubusercontent.com/5047891/51560900-1cd9d680-1e86-11e9-8d18-0c5da959b3cb.png)

**Comment by sandy081** [comment]
@alexandrudima This works for me when running from sources. Do you see any errors in the console?

**Comment by alexandrudima** [comment]
I'm sorry I cannot reproduce anymore. I don't know what was different.
