### ISSUE TITLE
Open URL command not working

### ISSUE THREAD

**Issue by patelyogesh-in** [Microsoft/vscode#66940]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open Command Pallete.
2. Select Open Url (Which is shown as Developer: Open Url)
3. Type a valid URL, press enter.

This does not show preview bar for the URL opened. If you enter an invalid URL format, it throws an error notification.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (7.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sitecore-rocks-vscode|ref|0.0.6

</details>

**Comment by Tyriar** [comment]
Anything prefixed with developer is meant for debug purposes? You probably want an extension or something.
