### ISSUE TITLE
javascript/ts parser bug with json

### ISSUE THREAD

**Issue by frevds** [Microsoft/vscode#66947]
Issue Type: <b>Bug</b>

Any valid JSON file should also be valid JavaScript, but is somehow not, see following picture: 

![image](https://user-images.githubusercontent.com/5341447/51564895-c756f700-1e90-11e9-8a33-4ceb4ba820f8.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (17.05GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
references-view|ms-|0.0.23
vscode-icons|rob|8.0.0
vscode-java-dependency|vsc|0.3.0

</details>

**Comment by mjbvz** [comment]
This is not correct, json files are not valid javascript. In your example js, the braces define a block containing `"i": ...`, not an object literal

**Comment by frevds** [comment]
Hm, you're right, sorry, didn't think about the ambiguity with regular scope blocks and literal object expressions. Too bad though.
