### ISSUE TITLE
Support hyperlinks to specific file line numbers in the terminal

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#66957]
Would it be possible to support hyperlinks that open to a specific file and line number in the terminal?

For example, if the output below displayed in the terminal -

```
/Users/.../Foo.js
  9:35  error  'children' is missing in props validation  react/prop-types
````

I could click on `9:35` and it would open the `Foo.js` file and move focus to line 9.

**Comment by IllusionMH** [comment]
VSCode already supports links to pisition in file, however filename should be immediately followed by line (and column). Since output is plain text it is impossible to tell that it is line:number in file, and not time stamp on general case.

You can try [unix](https://eslint.org/docs/user-guide/formatters/#unix) formatter that will output compatible path:line:column, and you'll be able to Ctrl+click on them to navigate to the exact position

**Comment by Tyriar** [comment]
Yeah since the text is separated it's very difficult to associate it with the link, there are several formats supported for line/col but they're all on the same line something like this `file:line:col`, `file (line:col)`, etc.

**Comment by joshunger** [comment]
Thanks @Tyriar @IllusionMH

**Comment by keyvan-m-sadeghi** [comment]
Hi @Tyriar 
[AVA](https://github.com/avajs/ava) produces text in the `file:line:col` format that you mentioned. Though they are not rendered as links. Am I missing something?
<img width="247" alt="screenshot" src="https://user-images.githubusercontent.com/1758649/52457082-04281c80-2b26-11e9-8a50-274888ba5274.png">

**Comment by IllusionMH** [comment]
@keyvan-m-sadeghi if you are about file names in stack trace - that's not enough info to make it a link.
It should be either absolute path (as in ESLint unix formatter mentioned above) or at least path relative to workspace folder.

For example in out project we have about 200 `index.js` files, and having just name of the file as string won't be enough info to open correct file.

**Comment by Tyriar** [comment]
@keyvan-m-sadeghi see https://github.com/Microsoft/vscode/issues/22772, if ava changed to it to print ./index.js:line:col instead then it would work. https://github.com/Microsoft/vscode/issues/22772 may not be able to get resolved, at least with the current design of validating the paths, as doing so would require pinging the disk basically for every single word in the terminal.
