### ISSUE TITLE
"Error: Overlapping ranges are not allowed" when regex replacing after 10000 items

### ISSUE THREAD

**Issue by RomanKornev** [microsoft/vscode#66953]
- VSCode Version: 1.30.2
- OS Version: Windows 10 x64 1809

Steps to Reproduce:

1. Open a big project like this one
1. Search and Replace in files Ctrl+Shift+F
1. Turn regex on
1. Search `^.*import.*$` or any query that captures from beginning or to the end of the line
1. About 10000 matches
1. Click Replace All
1. Wait until it's finished
1. All replaced perfectly fine
1. Now hit enter and click "Replace All" again
1. ERROR:
```
  ERR Error: Overlapping ranges are not allowed!
    at e.applyEdits (pieceTreeTextBuffer.ts:216)
    at o._applyEdits (textModel.ts:1314)
    at o.applyEdits (textModel.ts:1271)
    at e.pushEditOperation (editStack.ts:168)
    at o._pushEditOperations (textModel.ts:1264)
    at o.pushEditOperations (textModel.ts:1173)
    at e.apply (bulkEditService.ts:96)
    at e.apply (bulkEditService.ts:213)
    at e.<anonymous> (bulkEditService.ts:355)
    at errors.ts:237
    at Object.s.__generator.a.label [as next] (errors.ts:237)
    at s (errors.ts:237)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
 ```
11. Some files now have multiple copies of the same result on the left
1. 17548 results instead of 10000
1. Files are not being changed after clicking Replace All

Queries I've tried with restarting each time (all affected):
`^.*var.*\n`
`^.*var.*$`
`.*\(\).*`
`\{.*\n`

It's irrelevant whether there are multiple matches on the same line or not.
Screenshot:
![desktop screenshot 2019 01 23 - 01 33 56 26](https://user-images.githubusercontent.com/5807561/51570884-6a1f6d80-1eb1-11e9-9e19-2ae8943ed6c8.png)
Clearly visible: 
* Multiple search results on the same line that shouldn't be there
* More than 10000 results overall instead of roughly 10000

Does this issue occur when all extensions are disabled?: **Yes**
 **NOT** a duplicate of https://github.com/Microsoft/vscode/issues/51624
 **NOT** a duplicate of https://github.com/Microsoft/vscode/issues/55606

**Comment by roblourens** [comment]
Something weird going on here...

**Comment by roblourens** [comment]
Now I'm not able to repro it

**Comment by RomanKornev** [comment]
I'm still able to repro.
It seems like it became even worse with the new update 1.31.0.
Now it gets stuck in an infinite loop. I'm seeing Windows hourglass cursor appearing and disappearing 10 times per second and the vscode process maxing out the CPU core. Main window is still responsive though.
![desktop screenshot 2019 02 07 - 15 27 19 50](https://user-images.githubusercontent.com/5807561/52411739-d7581300-2aed-11e9-9a62-204b91cc73be.png)
Still unable to regex replace anything over 10000 results.

**Comment by sandy081** [comment]
@roblourens You can repro it using steps [here](https://github.com/microsoft/vscode/issues/73276#issuecomment-489580516)

**Comment by roblourens** [comment]
Thanks for the steps @sandy081! This turned out to be a bug that I don't know why it doesn't come up more often. It could have resulted in missing search results and other issues.
