### ISSUE TITLE
Extensibility API command for moving cursor to line.

### ISSUE THREAD

**Issue by PatoBeltran** [Microsoft/vscode#6695]
I'm working in a vscode extension and I would like to open a file with the cursor in a given line (just as the `-g` flag of the command line tool). I've been looking at the API commands and I don't see any command that does this.

The solution that I was looking at was the following:

```
private openFileAtLocation(filename: string, lineNumber: number): Q.Promise<any> {
    return Q(vscode.commands.executeCommand("vscode.openFolder", vscode.Uri.file(filename))).then(() => {
        vscode.commands.executeCommand("workbench.action.gotoLine", lineNumber);
    });
}
```

but the `workbench.action.gotoLine` only opens the `Go to Line` dialog. Is there any support for this feature in the API? or can this command be modified so that if a line number is provided as an argument it automatically jumps to the line?

Thanks!

**Comment by f111fei** [comment]
Maybe you can try to do like this.
```
let editor = vscode.window.activeTextEditor;
let range = editor.document.lineAt(lineNumber-1).range;
editor.selection =  new vscode.Selection(range.start, range.end);
editor.revealRange(range);
```

**Comment by jrieken** [comment]
`revealRange` is the way to go on this.
