### ISSUE TITLE
Can you replace all #0000ff  with #0000aa in  theme-defaults

### ISSUE THREAD

**Issue by netmou** [Microsoft/vscode#66959]
The color #0000FF is not health for humen's eye, it's too bright，i think #0000aa is better.

#0000ff:
![image](https://user-images.githubusercontent.com/7068058/50338544-91e88200-054f-11e9-86d8-7024ea647fba.png)

**Comment by misolori** [comment]
Thanks for the suggestion, we'll keep this in mind. You can install or create themes that better fit with what you're looking for. In this case I'm closing this as "as designed".
