### ISSUE TITLE
Why Visual Studio Code import sucks!!!! Why! Just tell me why

### ISSUE THREAD

**Issue by temurih** [Microsoft/vscode#66952]
I don't care if this is already been addressed or not. I am so frustrated with Visual Studio Code import problems. It works one day and does not work the next day. Like why!!!! Does not make any sense! If I do an update, that would make a bit of sense. I could tell myself, maybe this patch has introduced the bug. But VSCode is so incredible and breaks for no reason whatsoever! Sometime it can't even import from a file next to it. I have to manually write the imports. Even reloading the whole VSCode does not help once it decided not import something.

**Comment by mjbvz** [comment]
This is not a proper issue report. See https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

**Comment by temurih** [comment]
I am not sure how I can make something reproducible which works sometimes and does not work the other times. The import wasn't working few minutes ago. As soon as I want to capture a video of it, it starts working again! Sounds strange!? That's how the VSCode works for me!

**Comment by mjbvz** [comment]
Start by providing some example code or sample project

**Comment by temurih** [comment]
It works fine when I try to replicate the problem. I will make a video of it next time it acts up!
