### ISSUE TITLE
add closeSidebar action

### ISSUE THREAD

**Issue by EricTetz** [Microsoft/vscode#66956]
Add `workbench.action.closeSidebar`. It's inconsistent to have `closePanel` but not `closeSidebar`.

`toggleSidebarVisibility` exists, but that can't be used to write a macro that *closes* any open panel or sidebar: it might *open* the sidebar.

Note that this is a duplicate of https://github.com/Microsoft/vscode/issues/60241 which was opened 3 months ago then (apparently erroneously) closed as if it was a question about existing functionality when in fact it was a request for functionality that currently does not exist.

**Comment by usernamehw** [comment]
```json
{
    "key": "ctrl+shift+8",
    "command": "workbench.action.toggleSidebarVisibility",
    "when": "sidebarVisible"
}
```

**Comment by EricTetz** [comment]
@usernamehw That is *not* the same as having a `workbench.action.closeSidebar` action.

There are other contexts where actions can be executed. For instance, I have a macro extension and a Vim emulation (vscodevim) extension, both of which let me execute chains of actions, but don't have per-command when clauses.

What I want is a hotkey that closes both the panel and/or the sidebar, if either are open.  With a macro or Vim command mapping, I could easily map `workbench.action.closePanel` and `workbench.action.closeSidebar` to the same key. But the latter doesn't exist.

**Comment by usernamehw** [comment]
closePanelMacro:

`closePanel`

closePanelSidebarMacro:

`closePanel`
`toggleSidebar`

`keybindings.json`

```json
{
    "key": "",
    "command": "macro.closePanelMacro",
    "when": "!sidebarVisible"
},
{
    "key": "",
    "command": "closePanelSidebarMacro",
     "when": "sidebarVisible"
},
```

**Comment by EricTetz** [comment]
Again, you're relying a conditional mechanic which is not available in all contexts.  For instance, `vscodevim`'s keybindings don't support them, so your solution doesn't help me at all. More broadly, why make users jump through flaming hoops to do something that could be trivial if you added 3 lines of code? Why do both `togglePanel` and `closePanel` exist, if there's no value in the latter?

**Comment by usernamehw** [comment]
How do you live there in vim without `when`? I'm out then. @bpasero

**Comment by bpasero** [comment]
I think @usernamehw did a good job in explaining the solution. We have contexts for this reason.
