### ISSUE TITLE
not able to get back default color scheme. 

### ISSUE THREAD

**Issue by revoorunischal** [Microsoft/vscode#66965]
Hi ,

I have been using visual studio code and terminal from 6 months and it was working fine but all of a sudden now text is coming in highlighted mode and not able to read the text. Can you please suggest any solutions. Have attached screenshot for reference

![](https://user-images.githubusercontent.com/10596777/51423942-167cfd80-1bed-11e9-90c8-269069ceb62a.png)

**Comment by Tyriar** [comment]
You might have set the background color of your powershell.exe/cmd.exe windows?

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
