### ISSUE TITLE
workspaceState can not store Map persistently

### ISSUE THREAD

**Issue by LiPinghai** [Microsoft/vscode#66963]
- VSCode Version:  1.31.0-insider
- OS Version: win10

Steps to Reproduce:

1. store a Map in workspaceState
2. refresh, and get the Map from workspaceState
3. get a object, not a Map

Does this issue occur when all extensions are disabled?: Yes

if I do that 
```ts
	const map = new Map();
	map.set('a', 1);
	context.workspaceState.update('map', map).then(()=>{

		const _map = context.workspaceState.get('map'); // _map is a Map
		debugger
	
	});	
```
then change and refresh:
```ts
	 const _map = context.workspaceState.get('map'); // _map is a empty object
	 debugger

	const map = new Map();
	map.set('a', 1);
	context.workspaceState.update('map', map).then(()=>{

		// const _map = context.workspaceState.get('map'); 
		// debugger
	
	});	
```

if I store a **Array** instead of a **Map**，then there is no mistake

**Comment by bpasero** [comment]
@jrieken I doubt we ever supported this, should we document this better that only JSON serializable things can be stored?

**Comment by jrieken** [comment]
Yeah, thing must be JSON-serializable, there is no other way to get stuff to disk. @LiPinghai You should use `[...myMay.entries()]`

**Comment by jrieken** [comment]
I actually think that we are pretty explicit already: https://github.com/rdeline/vscode/blob/1bffc3c022bdc4016ba2cbdc21a28227d89df176/src/vs/vscode.d.ts#L4736
