### ISSUE TITLE
Code Lens does not accurately count override references.

### ISSUE THREAD

**Issue by JonathanPalmerGD** [Microsoft/vscode#66960]
Create an empty Unity Project (U2018.2 for my test case). Unity may or may not be a related part of the problem.
Create a script, make it an abstract base class. Give it an abstract public function.
Create a child class script. Have it override the abstract function.
Create a third class, it utilizes the child class's override function.

Code Lens should show all 3 references of that function's override hierarchy, instead it will only show the utilizer's reference if you click on the grey Code Lens text of (1 reference).

Here is an example:
![image](https://user-images.githubusercontent.com/2644214/51577936-85b65400-1e70-11e9-9acb-d8f852eeec50.png)

![image](https://user-images.githubusercontent.com/2644214/51577975-98308d80-1e70-11e9-8c1f-eb9615d382ac.png)

---

VS Code version: Code - Insiders 1.30.2 (user setup)
commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-1-07
Chrome: 61.0.3163.100
OS: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Please file this against the C# extension
