### ISSUE TITLE
Automatically insert line break between letters when I hit ENTER at end of full text with only Korean

### ISSUE THREAD

**Issue by jsstar522** [Microsoft/vscode#66967]
- VSCode Version: 1.30.2
- OS Version: MacOS Sierra 10.12.6 

I have a error with vscode. When I hit ENTER at end of full text, automatically insert line break between letters. This error appear when I type with only Korean, not with English. Please let me know.

* Before hit ENTER
![before](https://i.stack.imgur.com/zQedj.png)

* After hit ENTER
![after](https://i.stack.imgur.com/xdcq8.png)

**Comment by HongseokKwon** [comment]
It has been resolved in Vscode 1.31.1.

**Comment by rebornix** [comment]
Close as @HongseokKwon pointed out it's fixed in latest VS Code, we can reopen the issue if you can still see it.
