### ISSUE TITLE
Quick Open file order

### ISSUE THREAD

**Issue by sreevisakh** [Microsoft/vscode#66964]
VSCode Version: 1.30.2
OS Version: macOS Sierra 10.12.6
Quick Files are in not sorted properly
eg: While searching for a file with keyword OTP following is the result

![4lg5ua](https://user-images.githubusercontent.com/866258/51071440-d52da080-1676-11e9-8b6e-38ef69ffe897.jpg)

Even though there is a path with "otp" continuously its not the first result.

Steps to Reproduce:

Do a file search with quick open
Does this issue occur when all extensions are disabled?: Yes

**Comment by sreevisakh** [comment]
Its a duplicate of the other issue. But it closed before I submitted the photo. I couldn't reopen that.

**Comment by roblourens** [comment]
It prioritizes file names, but if you include a `/` at the end, it will try to match a folder.
