### ISSUE TITLE
Korean text is not the same font weight in markdown preview

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6696]
- VSCode Version: 1.1.0-alpha
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open the smoke test repo
2. Open readme.md
3. View markdown preview

![selection_011](https://cloud.githubusercontent.com/assets/12900364/15487711/4646ffde-2104-11e6-974b-88509008b3ff.png)

**Comment by Tyriar** [comment]
Same inside the editor too which is a bit annoying. Plus it's not monospace, not sure if that's an issue or not.

![image](https://cloud.githubusercontent.com/assets/2193314/15528873/02599490-21fd-11e6-97eb-c754ce24a928.png)

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension.

**Comment by Tyriar** [comment]
![image](https://cloud.githubusercontent.com/assets/2193314/16130061/59c50446-33bc-11e6-98cb-dcd7bc4584b0.png)
