### ISSUE TITLE
List highlight filter: Unexpected behavior on New file action when Filter on Type is enabled

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#66979]
Issue Type: <b>Bug</b>

1. Type in Explorer list to highlight matches
1. Turn on Filter on Type in widget
1. Click on `New file` or `New folder` action
1. Filtered list is dimmed (as usually), name input is not visible, and typed characters are added to the filter.

In this case I would expect that file tree will exit from highlight/filter mode and new file/folder input will be visible.

VS Code version: Code - Insiders 1.31.0-insider (2d79ffe0cd84515a4c771fcbd7294c2448d97826, 2019-01-23T06:20:52.488Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (20.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
Great catch.

**Comment by joaomoreno** [comment]
@isidorn Two options:

1. I add a `clearTypeFilter(): void` API on the tree. You find a way to call that when necessary. Problem with this is somehow wiring all of that from the file actions down to the tree. One good option would be to add a new event `onWillSetEditable`.
2. We make editable stats always visible, no matter what the type filter it. Problem with this is the file will be invisible as soon as the user types a name which doesn't match the type filter and presses <kbd>Enter</kbd>.

Your choice.

**Comment by isidorn** [comment]
@joaomoreno I am starting to like atom's model of having an input box in the middle of the screen more and more.

Before we make a decision please note that there are input boxes not only in the explorer but also in watch, breakpoints and variables view.
Since doing 1 would mean we have to do that for all the views.
It sounds more straightforwad that a tree client can specify that an element is always visible. So I would go with 2.

**Comment by joaomoreno** [comment]
@isidorn Did you consider the problem with 2?

**Comment by isidorn** [comment]
@joaomoreno yeah I thought about it and does not seem like that common scenario:
user has filter
wants to add a new file / folder -> adds it
the file / folder is invisible -> however if it is a file, we open it in the editor (so the user will get visual feedback something happened)
If it is a folder is the only case which sounds really corner.

Though calling clearTypeFilter also works for me.
What would you  prefer?

**Comment by isidorn** [comment]
@IllusionMH you can check out the behavior in tomorrow's insiders. It should work fine now

**Comment by dbaeumer** [comment]
But created: https://github.com/Microsoft/vscode/issues/67723
