### ISSUE TITLE
PowerShell doesn start normally, it shows empty strings

### ISSUE THREAD

**Issue by SardukarSilver** [Microsoft/vscode#66973]
Issue Type: <b>Bug</b>

powershell terminal doesn show dir on start, show just empty lines

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (15.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
prettier-vscode|esb|1.7.3
vscode-wrap-console-log|mid|1.7.1
vetur|oct|0.14.5
material-icon-theme|PKi|3.6.2
LiveServer|rit|5.3.1

(1 theme extensions excluded)

</details>

**Comment by SardukarSilver** [comment]
![image](https://user-images.githubusercontent.com/15904391/51600736-57398700-1f0b-11e9-9cba-1cf7a98eff70.png)

**Comment by SardukarSilver** [comment]
and after press something
![image](https://user-images.githubusercontent.com/15904391/51600777-6c161a80-1f0b-11e9-80d4-a113a56fa9c1.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
