### ISSUE TITLE
Can I modify the vscode global configuration in the extension?

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#66970]
- VSCode Version: 1.30.2
- OS Version: 10.3.3

I want to put the snippet suggestion on top, the global configuration `editor.snippetSuggestions` can be set to `top`(need customer to set), can I change this property to what I need in the extension?

**Comment by sbatten** [comment]
https://www.reddit.com/r/vscode/comments/74qmvu/extension_writing_is_there_a_way_to_update_user/
