### ISSUE TITLE
First item in suggest widget selected but selection not rendered

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66977]
I do not have consistent repro steps but I see this every day for the last 20 days.
I get into a state that the selection only on the first item in the suggest widget is not rendered.

@jrieken please let me know what details I can provide once I get into this state and I will happily add them. Getting a repro is a bit hard so sorry for not steps.

fyi @joaomoreno

**Comment by jrieken** [comment]
> I get into a state that the selection only on the first item in the suggest widget is not rendered.

Yeah, I have seen that to. Repro steps would help 🤓

**Comment by joaomoreno** [comment]
> the selection only on the first item in the suggest widget is not rendered

Maybe share a screenshot when it happens.

**Comment by isidorn** [comment]
Here's a fresh screenshot
![screenshot 2019-01-24 at 10 52 21](https://user-images.githubusercontent.com/1926584/51670097-2ff3c000-1fc6-11e9-8d5c-73a00def01e9.png)

This happened by invoking sugggest [here](https://github.com/Microsoft/vscode/blob/f6e44e88a3ce63aeabaf7f7b11a0de7c38e09628/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L982)
I was invoking suggest via ctrl+space after the dot even though `finally` has already been typed.
After I took the screenshot the selection started rendering again.

I hit this issue every day and it only started happening in this milestone.
I suggest that we try to fix this (since many more users might hit it in stable)
Let me know what else do you want me to do once I hit it. Thanks

**Comment by joaomoreno** [comment]
@isidorn Your mouse is over the element isn't it?

**Comment by isidorn** [comment]
@joaomoreno yes! That is the way to repro!
It becomes confusing becauase the mouse also does not get rendered.

**Comment by joaomoreno** [comment]
:man_facepalming: That's a theme issue.

**Comment by isidorn** [comment]
I understand. However it looks broken because the mouse is not getting rendered.
I think themes can easily fuck this up since there are a lot of list selection / hover colors.

**Comment by joaomoreno** [comment]
Actually something is wrong with the suggest widget itself: in terms of background colors, hover seems to take precedence over focus/selection. This doesn't happen for any other lists/trees.

@jrieken I did not investigate why suggest breaks this but I've made the CSS stricter and made sure the hover style doesn't get precedence over focus/selection.

**Comment by isidorn** [comment]
Thanks for fixing this, it was driving me nuts.

**Comment by joaomoreno** [comment]
![brando](https://media.giphy.com/media/BVsb82R2lFLlC/giphy.gif)

**Comment by isidorn** [comment]
Works great, adding verified label
