### ISSUE TITLE
Intellisense in not showing up when trying to add setting for "eslint.trace.server" and "tslint.trace.server"

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6697]
- VSCode Version: Latest alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open any folder which has .ts or .js file.
2. Update settings.json file for below properties (for Typescript add tslint and for JavaScript add eslint)
"tslint.trace.server":"messages" ,
or
 "eslint.trace.server":"messages"
3. Build solution or launch output window View->Toggle output.
4. Verify in the drop down you will get option for eslint or tslint.

Actual: The final output is coming properly but not getting any intellisense when trying to add property in settings.json file.
 
![eslint traceissue](https://cloud.githubusercontent.com/assets/17735796/15488624/12476558-210d-11e6-97c9-4b833b38e4eb.gif)

**Comment by dbaeumer** [comment]
@v-pavanp please file separate issues for eslint and tslint in the following GitHub repositories:

https://github.com/Microsoft/vscode-eslint
https://github.com/Microsoft/vscode-tslint

Thanks.
