### ISSUE TITLE
file not displayed 

### ISSUE THREAD

**Issue by vinayproses** [Microsoft/vscode#66978]
Issue Type: <b>Bug</b>

when i try to open files from Explorer it's not open in view

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|8.00GB (0.43GB free)|
|Process Argv|-psn_0_475252|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
string-converter|ada|0.1.1
vscode-color|ans|0.4.5
nestjs|ash|1.1.0
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.42
css2react|got|0.0.6
docthis|joe|0.7.1
ionic1-snippets|jus|1.0.1
vscode-jira|Kni|0.6.0
vscode-scss|mrm|0.6.2
cpptools|ms-|0.20.1
node-debug2|ms-|1.31.3
color-highlight|nau|2.3.0
ionic2-snippets|oud|1.0.0
vscode-docker|Pet|0.5.1
vscode-icons|rob|8.0.0
partial-diff|ryu|1.4.0
standard|shi|0.2.3
code-spell-checker|str|1.6.10
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
/needsMoreInfo could you please provide a gif of your experience or more details?

**Comment by vinayproses** [comment]
uninstall and install it's working normally now i think some files get corrupted ones i switch off my mac accidentally.
