### ISSUE TITLE
Terminal is out of alignment

### ISSUE THREAD

**Issue by seradork** [Microsoft/vscode#66974]
Issue Type: <b>Bug</b>

When you open the terminal, the starting position is out of alignment.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3399)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-br-tag|1na|0.0.4
path-intellisense|chr|1.4.2
regex|chr|0.2.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.0.15
rainbow-csv|mec|0.8.0
HTMLHint|mka|0.5.0
vscode-language-pack-ja|MS-|1.30.2
debugger-for-chrome|msj|4.11.1
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.2
trailing-spaces|sha|0.2.11
stylelint|shi|0.47.0
vscode-npm-scripts|tra|0.2.1
html-css-class-completion|Zig|1.17.1

</details>

<br>

![screenshot](https://user-images.githubusercontent.com/16128236/51601372-80780880-1f47-11e9-8e77-6aaa0552bab5.jpg)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
