### ISSUE TITLE
Additional grouping capabilities for listed problems

### ISSUE THREAD

**Issue by Glober777** [Microsoft/vscode#66983]
Issue Type: <b>Feature Request</b>

It would be really handy if there was a way to have an abbility to group problems by some additional criteria (other than a file name). It would be really handly if there was a way to group problem records based on a regex execeuted against a problem message. Say we have the following problems (supposedly produced by Pester): 
```
<MyPesterScript.Test.ps1>:
- [MyScript1.ps1]: The script has help article
- [MyScript1.ps1]: The script is signed
- [MyScript1.ps1]: The script has no Script Analyzer findings
- [MyScript2.ps1]: The script is signed
- [MyScript3.ps1]: The script has no Script Analyzer findings
- Calling this thing never fails
- Running that other thing should throw and error
```

And if I group by `^\[.+\]` expression I get this:
<MyPesterScript.Test.ps1>:
- <[MyScript1.ps1]>:
  - [MyScript1.ps1]: The script has help article
  - [MyScript1.ps1]: The script is signed
- <[MyScript2.ps1]>:
  - [MyScript2.ps1]: The script is signed
- <[MyScript3.ps1]>:
  - [MyScript3.ps1]: The script has no Script Analyzer findings
- \<Other Problems\>:
  - Calling this thing never fails
  - Running that other thing should throw and error

That would make working with a long problem list more convenient.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

**Comment by sandy081** [comment]
Hmm.. I see your requirement but does not look to me a most often case. So we would have to wait until we get more such requests.
