### ISSUE TITLE
List highlight filter: "No elements found" text is missing when after removing files when Filter on Type is enabled

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#66981]
Issue Type: <b>Bug</b>

1. Type in Explorer list to highlight matches
1. Turn on Filter on Type in widget
1. Select all matches and remove these files
1. File tree is empty - no items, no text, only filter widget visible
1. Type any character
1. `No elements found` appears

Would be nice to see same feedback as for filtering witn no matches.

VS Code version: Code - Insiders 1.31.0-insider (2d79ffe0cd84515a4c771fcbd7294c2448d97826, 2019-01-23T06:20:52.488Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (19.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
Good catch.
