### ISSUE TITLE
BUg Terminal Display and Lateral Bar

### ISSUE THREAD

**Issue by DorianMaliszewski** [Microsoft/vscode#66985]
- Version : 1.30.2
- Date : 2019-01-07T22:49:48.319Z
- Électron : 2.0.12
- Chrome : 61.0.3163.100
- Node.js : 8.9.3
- V8 : 6.1.534.41
- OS : Linux x64 4.15.0-39-generic (Ubuntu 18.04 LTS)

Steps to Reproduce:

1. Lock the screen (or Sleep)
2. Wait (for me it's about 1h)
3. Unlock
4. Terminal and Lateral Bar (preview of the current editor opened) display multiple colors, to resolve that i need to change the current editor and kill the integrated terminal.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by DorianMaliszewski** [comment]
I took a screenshot :
![capture d ecran de 2019-01-23 14-35-44](https://user-images.githubusercontent.com/24531136/51610162-5c530200-1f1c-11e9-9cd3-d6d15435f043.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by DorianMaliszewski** [comment]
It still doesn't work in the Insider version
