### ISSUE TITLE
Insider - extension host debugging, breakpoint not hit in the webpack-sample

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#66988]
- git clone vscode-extension-samples
- open vscode-extension-samples/webpack-sample in code-insiders
- run npm install
- set a breakpoint in src/math.ts inside the add() function
- F5
- Execute 'Hello Webpack'

-> the breakpoint seems to be hit, the notifiation does not appear, but the editor doesn't show that the execution has stopped.

This works fine in the stable version.

**Comment by weinand** [comment]
@egamma hitting breakpoints in extension.ts works fine for me (and I don't have a src/math.ts).

**Comment by weinand** [comment]
hitting breakpoints work fine for me.

**Comment by egamma** [comment]
Can no longer reproduce, closing.
