### ISSUE TITLE
unable to move the window when mouse close to Help menu

### ISSUE THREAD

**Issue by stevencollinscn** [Microsoft/vscode#66992]
- VSCode Version: 13.0.2
- OS Version: Windows 10

![vscode](https://user-images.githubusercontent.com/33796896/51615490-ff445580-1ef5-11e9-9c3c-46c05bf92826.gif)

The problem still exists with all installed extensions disabled.

**Comment by sbatten** [comment]
this is fixed in the latest insiders
/duplicate
