### ISSUE TITLE
Object definition detail popup was blocked by main window.

### ISSUE THREAD

**Issue by ericchan1336** [Microsoft/vscode#6699]
- VSCode Version: 1.1.1
- OS Version: win7 64bit

Steps to Reproduce:

1. When the object is a little bit large, and you hover the instance of that object, vsc will show a popup window to show the definition of that object. But sometimes it's blocked by the main window border since it's a little bit big.

**Comment by aeschli** [comment]
@ericchan1336 Can you add a screenshot?

**Comment by ericchan1336** [comment]
Sorry, but I tried many times uploading screenshots and it all failed...

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
