### ISSUE TITLE
Switch window does not work

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#66991]
Issue Type: <b>Bug</b>

![snap](https://user-images.githubusercontent.com/439226/51613774-357fd600-1ef2-11e9-9919-df3d2ce554b8.png)

1. Open multiple instances of code-insider.
1. Press CTRL+W to switch window.
1. Select a different listed instance.

Notice the switching does not happen on Linux, using Kubuntu18.04.

Expect: Should switch to selected window, bring it to the top and give it edit focus.

VS Code version: Code - Insiders 1.31.0-insider (e9bb33f09599753150be897ab81126a620e53b94, 2019-01-21T06:16:03.813Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (4.02GB free)|
|Process Argv|/home/yadav/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.0
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
java-debug|DSn|0.0.2
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.0.30
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
java|red|0.37.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.13.0
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by BairDev** [comment]
Same for me, VSCode (`code -v`):

    1.31.0
    7c66f58312b48ed8ca4e387ebd9ffe9605332caa
    x64

I use *F7* for switching windows of VSCode, but this should not make a difference.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
