### ISSUE TITLE
Allow extensions to access code outline via an API

### ISSUE THREAD

**Issue by Fraser-Greenlee** [Microsoft/vscode#66990]
This would allow extensions to utilise the current variables & modules in the code.

**Comment by jrieken** [comment]
Do you need the UX or the data model?

**Comment by Fraser-Greenlee** [comment]
Just the data model would be great!

**Comment by jrieken** [comment]
Ok, check this: https://code.visualstudio.com/api/references/commands. There will a command to run that returns the document symbols data model
