### ISSUE TITLE
Electron-Build has wrong filename for the .exe

### ISSUE THREAD

**Issue by tonyarkles** [Microsoft/vscode#67]
When I run `scripts/code`, I get the following output:
```
C:\Users\Owner\Documents\vscode>scripts\code
[11:17:09] Using gulpfile ~\Documents\vscode\gulpfile.js
[11:17:09] Starting 'electron'...
[11:17:09] Finished 'electron' after 459 μs
'..\Electron-Build\Code.exe' is not recognized as an internal or external command,
operable program or batch file.
```

Looking in the Electron-Build directory, there's no executable named `Code.exe`, but there is one named `Code [OSS Build].exe`. Is this an oversight from open sourcing the application?

Edit: Running `"..\Electron-Build\Code [OSS Build].exe" .` from the vscode checkout works, so it's not a blocker, just a stumbling block.

**Comment by bpasero** [comment]
@joaomoreno ???

**Comment by joaomoreno** [comment]
@tonyarkles Can you pull, delete the `..\Electron-Build` directory and try again?

**Comment by tonyarkles** [comment]
@joaomoreno works great, thanks!
