### ISSUE TITLE
File Explorer: `Shift`+arrows not always removes selection

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#67001]
* Go <kbd>Shift</kbd>+<kbd>↓</kbd>
* Then go up <kbd>Shift</kbd>+<kbd>↑</kbd>
* Stable toggles selection, Insiders keeps it

|   Stable      | Insiders          |
| ------------- |-------------|
| ![stable](https://user-images.githubusercontent.com/9638156/51624759-963bfc80-1f4c-11e9-99c7-bce0af939e48.gif) | ![insiders](https://user-images.githubusercontent.com/9638156/51624779-9fc56480-1f4c-11e9-9ecf-8403db857688.gif) |

VS Code version: Code - Insiders 1.31.0-insider (2d79ffe0cd84515a4c771fcbd7294c2448d97826, 2019-01-23T06:20:52.488Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
This is tree specific behavior. Forwarding to @joaomoreno

**Comment by admosity** [comment]
@usernamehw try switching to "simple" mode. You will see the functionality restored. #66995

```json
    "workbench.list.keyboardNavigation": "simple"
```

**Comment by usernamehw** [comment]
@admosity this setting has no effect for this case.

**Comment by joaomoreno** [comment]
Good catch.
