### ISSUE TITLE
vscode does not allow to type / keyboard not working inside vscode / vscode does not allow to edit files

### ISSUE THREAD

**Issue by victorabraham** [microsoft/vscode#67013]
** Keyboard is not working inside vscode **
After I updated vscode to version 1.30.2, I am not able to edit/type in any files opened in it. It just does not recognize keyboard strokes.

**Describe the bug**

OS and Version: OSX High Sierra
VS Code Version: 1.30.2

Extensions you installed (and if the issue persists after disabling them): Salesforce extension pack, ESLint, Python, Chrome Debugger

Does not allow to type inside editor.
**vscode is a very good editor. I was seeing this error in my mac and windows machines occasionally. Usually this error went away when I restarted vscode. But this time in my Mac, it is not allowing me to edit the file at all even after multiple restarts.
Please come up with a permanent fix for this issue for all OS platforms. This is actually the only frustrating issue with vscode and makes it unusable and leaves people with no option other than than going for some other editor.**

**To Reproduce**
Open any project folder
Open any file
Start typing inside file

**Expected behavior**
Typed characters should show in UI

**Comment by sbatten** [comment]
@victorabraham does the application accept other keyboard input? such as F1 to open the Command Palette

**Comment by visheshsummitsync** [comment]
For me, it's not working only in new files

**Comment by visheshsummitsync** [comment]
> For me, it's not working only in new files

I tracked it down to mavensmate extension

**Comment by victorabraham** [comment]
> @victorabraham does the application accept other keyboard input? such as F1 to open the Command Palette

I am on a new mac without function keys. Keys like delete are not working.

**Comment by victorabraham** [comment]
@sbatten It is allowing me to edit existing files now. But not allowing to type if I started a new file with Command+N. This issue is totally random. But it occurs too often to ignore. Also when it is not working, it makes the editor useless :(

**Comment by tomaszbroniewski** [comment]
I got the same problem. I had to use command: Developer: Reload Window.

**Comment by sbatten** [comment]
can you try with extensions disabled? `Developer: Reload with Extensions Disabled`

**Comment by Maduflavins** [comment]
why close the issue when it happening to almost everybody this day
