### ISSUE TITLE
Won't Load Page in Browser- Fan begins to Rev UP

### ISSUE THREAD

**Issue by Jonjacksf** [microsoft/vscode#67016]
Issue Type: <b>Bug</b>

I am trying to open items created from Visual Studio in the browser, but it just freezes and the fan/hard drive begins to rev up faster than I have ever hear it before?

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.12.1
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@Jonjacksf what kinds of items are you trying to open? Can you explain more of your process or provide a short clip of your experience?
/needsMoreInfo
