### ISSUE TITLE
Reveal active file does not pass focus to the explorer

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67024]
Commit: 2d79ffe0cd84515a4c771fcbd7294c2448d97826

I'm using Nord theme. It specifies `"list.focusBackground": "#88c0d099"`:

https://github.com/arcticicestudio/nord-visual-studio-code/blob/5ba2ac57d114030ec45f77ba24a7dd8d9eb6e33e/themes/nord.json#L112

Stable tree uses that color:

![image](https://user-images.githubusercontent.com/4033249/51642569-886f8280-1f1e-11e9-9e61-d227d596d520.png)

Insider doesn't:

![image](https://user-images.githubusercontent.com/4033249/51642590-93c2ae00-1f1e-11e9-91be-9d697c3cf151.png)

Repro:
- Use Nord theme.
- Run `Reveal active file in Side Bar`.

**Comment by isidorn** [comment]
Good catch, thanks for reproting this.
Let me know if Friday insiders fixes this nicely for you.

**Comment by octref** [comment]
Working great, thanks!
