### ISSUE TITLE
Adopt Promise#finally

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67027]
This is the continuation of #65059. With Electron 3.x `Promise#finally` came to us. It replaces `async#always` and should be adopted. Lean all about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

- [x] @isidorn 
```
src/vs/workbench/parts/files/electron-browser/fileActions.ts
  986,11:			return always(this.editorService.openEditor({ leftResource: resource.with({ scheme: CompareWithClipboardAction.SCHEME }), rightResource: resource, label: editorLabel }), cleanUp);
  10,10:import { always } from 'vs/base/common/async';
```

- [x] @sandy081 
```
src/vs/platform/extensionManagement/node/extensionManagementService.ts
  467,12:						e => always(pfs.rimraf(extractPath), () => null)
  456,14:						return always(pfs.rimraf(extractPath), () => null).then(() => Promise.reject(e));
  305,22:						.then(local => always(pfs.rimraf(installableExtension.zipPath), () => null).then(() => local)))
  27,19:import { Limiter, always, createCancelablePromise, CancelablePromise, Queue } from 'vs/base/common/async';
```

- [X] @mjbvz 
```
src/vs/editor/contrib/codeAction/codeActionWidget.ts
  57,11:			return always(
  8,10:import { always } from 'vs/base/common/async';
```

@jrieken 
```
src/vs/editor/browser/editorExtensions.ts
  269,11:			return always(new Promise((resolve, reject) => {
  7,10:import { always } from 'vs/base/common/async';
```

---

### :warning: Can't do this for `vs/base` :warning:

@joaomoreno 
```
src/vs/base/parts/ipc/test/node/ipc.cp.test.ts
  77,10:		return always(result, () => client.dispose());
  52,10:		return always(result, () => client.dispose());
  30,10:		return always(result, () => client.dispose());
  8,10:import { always } from 'vs/base/common/async';
```

@joaomoreno 
```
src/vs/base/parts/ipc/node/ipc.ts
  451,3:		always(result, () => this.activeRequests.delete(disposable));
  8,10:import { always, CancelablePromise, createCancelablePromise, timeout } from 'vs/base/common/async';
```

@joaomoreno 
```
src/vs/base/parts/ipc/node/ipc.cp.ts
  135,3:		always(result, () => {
  8,19:import { Delayer, always, createCancelablePromise } from 'vs/base/common/async';
```

@joaomoreno 
```
src/vs/base/common/cache.ts
  26,3:		always(promise, () => cts.dispose());
  7,10:import { always } from 'vs/base/common/async';
```

@jrieken 
```
src/vs/base/common/async.ts
  336,17:export function always<T>(promise: Promise<T>, callback: () => void): Promise<T> {
```

@joaomoreno 
```
src/vs/base/browser/ui/tree/asyncDataTree.ts
  635,10:		return always(result, () => this.refreshPromises.delete(node));
  567,10:		return always(result, () => this.currentRefreshCalls.delete(node));
  12,19:import { timeout, always, CancelablePromise, createCancelablePromise } from 'vs/base/common/async';
```

**Comment by bpasero** [comment]
🔴 Please keep in mind that you cannot use `finally` in standalone editor, it will fail the build.

**Comment by joaomoreno** [comment]
@bpasero Thought exactly the same. Updated @jrieken's comment.

Also, @jrieken, there was an infinite loop on the CancelablePromise: https://github.com/Microsoft/vscode/commit/8f8e1fb2664c02a409ad77fb6dbeb0c9be84af72

I've adopted finally on all places but `vs/base`.

**Comment by joaomoreno** [comment]
OK, even 8f8e1fb2664c02a409ad77fb6dbeb0c9be84af72 breaks everything because that's in base...

Reverting everything and let's see if we can get an Insider build today...

**Comment by jrieken** [comment]
> ⚠️ Please keep in mind that you cannot use finally in standalone editor code, it will fail the build. That probably rules out any usage in base.

❗️ Not really - it was just a matter of adding `"typings/lib.es2018.promise.d.ts"` to [`tsconfig.monaco.json`](https://github.com/Microsoft/vscode/blob/d9fb14589188e5706221f02f2b6dc5e321285424/src/tsconfig.monaco.json#L22). Sorry for the oversight, but there no more reason to use `async#always`
