### ISSUE TITLE
Space as end of hyperlink isn't always good idea

### ISSUE THREAD

**Issue by john-cj** [microsoft/vscode#67022]
- VSCode Version: 1.30.2
- OS Version: Win 7

Currently, any space after hyperlink automatically breaks it. Generally it's OK, but it breaks link highlighting in AsciiDoctor.

Example:

```
https://foo.bar/[this is foo site]
```

And here is how it will look inside VS Code:

![bug](https://user-images.githubusercontent.com/18004961/46442449-57522300-c772-11e8-8620-1d04416fa460.PNG)

As you see, the syntax highlighting isn't correct. Aslo, if you click this link, it will open incorrect address:

```
https://foo.bar/[this
```

This issue was originally posted here: https://github.com/asciidoctor/asciidoctor-vscode/issues/116

> VSCode seems to recognize as link any uri identifier (`file:`, `http:`, etc...) followed by any non-space characters. Something like this I guess: `(https?|file)://\S+`

It would be nice to have an option to manually adjust this regex in app's settings (File > Preferences > Settings).

**Comment by alexandrudima** [comment]
@john-cj if this file type is known to your extension, have you considered registering a link provider ?

**Comment by john-cj** [comment]
Hmm. No, I don't anything about it.
