### ISSUE TITLE
Pressing esc in peek view doesn't close it

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67030]
Esc in peek widget should close it, it's scrolling to the top of the list.

ctrl+f12:

![image](https://user-images.githubusercontent.com/2193314/51644871-a3de8b80-1f26-11e9-9c32-281114ff6481.png)

esc:

![image](https://user-images.githubusercontent.com/2193314/51644886-ae008a00-1f26-11e9-9231-8b2187ef5a54.png)

Version: 1.31.0-insider (user setup)
Commit: 2d79ffe0cd84515a4c771fcbd7294c2448d97826
Date: 2019-01-23T06:20:52.488Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18317

**Comment by Tyriar** [comment]
@usernamehw ❤️

**Comment by infctr** [comment]
Why is it a duplicate? It doesn't seem to be resolved, still can't close the peek def window, unless I click in the editor

```sh
❯ code-insiders -v
1.31.0-insider
2d79ffe0cd84515a4c771fcbd7294c2448d97826
x64
```
