### ISSUE TITLE
When I execute Ctrl + = / -,

### ISSUE THREAD

**Issue by luoxixi** [Microsoft/vscode#67034]
- VSCode Version: 1.30.2 (user setup)
- OS Version:Windows_NT x64 10.0.17763
Steps to Reproduce:
1.When I execute Ctrl + = / -, I don't want the entire interface including the UI to be zoomed in and out; I want it to be controlled only by the editing area.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
`editor.action.fontZoomIn`
`editor.action.fontZoomOut`

**Comment by sbatten** [comment]
@luoxixi as @usernamehw points out, there are commands for zooming the editor only which he has listed above. You can remap the keybindings to these commands instead if you wish
