### ISSUE TITLE
Add some support for C++ builder

### ISSUE THREAD

**Issue by pal98** [Microsoft/vscode#67031]
I'm using vs code to read the C++ builder project, 
however, the "__property" is a keyword in C++ builder, which cannot be recognized in vs code. 
     The vs code report errors and I cannot use "Ctrl+Left Clike" to quick find the variable definition.
     It looks like this.

![default](https://user-images.githubusercontent.com/46981447/51647363-6c6bef80-1fb7-11e9-8574-9fdadc800b64.png)

      In C++ builder IDE, it looks like this

![default](https://user-images.githubusercontent.com/46981447/51647438-c8367880-1fb7-11e9-96b2-77452a5ae168.png)

      Is it possible to add some support for C++ builder?

**Comment by sbatten** [comment]
@pal98 check out the C++ extensions in the marketplace and file issues on them please.
