### ISSUE TITLE
Debugger does not respect skipFiles

### ISSUE THREAD

**Issue by garu57** [microsoft/vscode#67039]
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

Version: 1.31.0-insider
Commit: 2d79ffe0cd84515a4c771fcbd7294c2448d97826
Date: 2019-01-23T06:20:52.488Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

node v11.7.0

Debug launch config:
```
    {
      "type": "node",
      "request": "launch",
      "name": "Debug server",
      //"console": "integratedTerminal",
      "program": "${workspaceFolder}/example/server.js",
      "protocol": "inspector",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ],
      "stopOnEntry": false
    },
```

Does this issue occur when all extensions are disabled?: Yes

Debugger is ignoring `skipFiles` with 1.30.1 and behaving erratically with 1.31.0-insider.
Consider the following situation:
![fig-1](https://user-images.githubusercontent.com/15155315/51667804-0f753700-1fc1-11e9-8c91-27e4c29c6bcf.png)

Given what is witten in [Skipping uninteresting code](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome),
> If you step into a skipped file, you won't stop there - you will stop on the next executed line that is not in a skipped file.

I assume that being the debugger stopped at line `35`, either pressing `Step Over` or `Step Into` I'd immediately stop at line `37`.
Here's instead what happens.

## 1.30.1

- `Step Over`, debugger stops at line `37`
- `Step Into`, debugger ignores `skipFiles` and stops into `${workspaceFolder}/node_modules/lunr/lunr.js`

![fig-2](https://user-images.githubusercontent.com/15155315/51667958-6713a280-1fc1-11e9-9312-14b893a6087d.png)

You can see in the call stack that `lunr.js` is grayed, ie considered skipped, but nonetheless debugger stops in it.

## 1.31.0-insider

- `Step Over`, debugger stops at line `37`
- `Step Into`, the stop indicator in the gutter and the line highlight turn greenish and debugger stays stopped there.

![fig-3](https://user-images.githubusercontent.com/15155315/51668079-b8239680-1fc1-11e9-8c4d-89e95db5fbf9.png)

From this moment on, any further press of either `Step Over` or `Step Into` or `Step Out` is ignored and the debugger is stuck there.

**Comment by garu57** [comment]
Sure, it's not mine, it is the [Hazel](https://github.com/wkallhof/hazel) project.
I think it has a very clean code, easy to read and I choose it to experiment with [lunr](https://www.npmjs.com/package/lunr) package.
I updated the node_modules and I had to make some small changes to account for lunr v2 changes but you can reproduce the problem at [searchProvider.js](https://github.com/wkallhof/Hazel/blob/master/app/providers/searchProvider.js) line `33`.

**Comment by garu57** [comment]
You said you were able to reproduce the problem but the issue was closed without a solution...

**Comment by roblourens** [comment]
Sorry, I forgot to remove the needs-more-info label.

**Comment by Spown** [comment]
this does look like what I am facing now. ``<node_internals>/**`` is skipped fine (garyed out, marked as skipped in the tooltip...). but node_modules can't be skipped neither with pattern nor explicitly, Regardless of unix or win path scheme is used

![](https://drive.google.com/uc?id=1z_aNX3Ipm_nJqp963ayOgEzRtVDPyVjf)

**Comment by roblourens** [comment]
Hey @Spown have you tried the preview of the new debugger? Could you try it there and see if it works better for you?
https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by Spown** [comment]
yes, I am using usePreview.

**Comment by roblourens** [comment]
Could you open an issue on the vscode-js-debug repo then with some details? I am not sure whether this old issue is still relevant, I will have to look at the repro project again

**Comment by connor4312** [comment]
Fixed things in the linked issue, and the new debugger is now the default in VS Code. Please open a new issue if you continue to run into problems.
