### ISSUE TITLE
how to put my own registerCompletionItemProvider item on top

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#67032]
the `CompletionItem` has a `sortText` property, I don't know how to use it to put my data in front according to the documentation

```js
return names.map(name => {
    const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Function)
    item.sortText = 'aaa'
    return item
})
```
Using a dictionary sequence？ it not works

**Comment by jrieken** [comment]
String comparison is used, e.g. `>` and `<`, The letter `a` isn't the first letter in the ASCII alphabet

**Comment by jrieken** [comment]
Did you try `String.fromCharCode(0)`?
