### ISSUE TITLE
List/Tree: no longer opens on mouse-down

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67040]
Steps to Reproduce:

1. open search or extensions view
2. mouse down

=> 🐛 nothing happens

This looks like a regression from stable where this works.

**Comment by joaomoreno** [comment]
Yup, I was forced to change this and open on mouse up only. I'd rather have consistency here and all lists and trees now open on mouse up.

**Comment by bpasero** [comment]
🐼
