### ISSUE TITLE
Copy value in Debug window not working

### ISSUE THREAD

**Issue by Abonia1** [Microsoft/vscode#67047]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
jsonified  pickle joblib data copy value failed while trying from debug window

**Comment by isidorn** [comment]
I can not reproduce this.
Can you repo with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, please provide nice reproducable steps so I can investigate on my machine

**Comment by Abonia1** [comment]
so here is screenshot of debug window where I would like to all the values of stopwords variables
![github debug](https://user-images.githubusercontent.com/22887323/51749839-c13f6100-20b0-11e9-9f12-e4566f8aea9f.PNG)

**Comment by Abonia1** [comment]
Note:i found this review recently.So i hope its beyond the scope of the vs code current version ?
https://github.com/Microsoft/vscode/issues/36704#issuecomment-345281563

**Comment by isidorn** [comment]
Yeah, we would like this feature to be provided by extensoins.
For example node debug could provide this command. However for this we would need first #36891
Until we have that there is nothing we can do here.
Thus closing as out of scope for now.
