### ISSUE TITLE
[JS] Autocomplete should sort based on local variables

### ISSUE THREAD

**Issue by pedroassis** [Microsoft/vscode#6704]
- VSCode Version: 1.1.0
- OS Version: OSX El Capitan 10.11

The autocomplete should always prefer displaying the user variables, if possible sort by scope, local variables first.

I find frustrating to type a couple of letters and still get a bunch of code snippets I never use.

You might have a reason for that, maybe other people use those snippets far more than the local variables, then it would be great to be able to disable the snippets and `window.*`.

Steps to Reproduce:

1. Open a JavaScript file, 
2. Add `var eventData = "hi";` and `var eventName = "hello"`
3. Type `ev` in the next line.

![screen shot 2016-05-23 at 11 19 22 pm](https://cloud.githubusercontent.com/assets/4248124/15492065/d3189656-213c-11e6-8977-783deba745af.png)

**Comment by dbaeumer** [comment]
The sorting is actually done in the UI.

**Comment by joaomoreno** [comment]
We've long decided to have lexicographic sorting.

cc @jrieken

**Comment by pedroassis** [comment]
@joaomoreno is it possible to disable all the other options and keep only user variables?

**Comment by joaomoreno** [comment]
I don't think that is possible. The contents of the widget come from TypeScript, though, so you'd have to request that in https://github.com/Microsoft/vscode-typescript

**Comment by dbaeumer** [comment]
Small correct. You can request it here: https://github.com/Microsoft/TypeScript
