### ISSUE TITLE
Can't exit zen mode when restarting vscode

### ISSUE THREAD

**Issue by idarbuashvili** [Microsoft/vscode#67059]
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.10 

Steps to Reproduce:

1. Enter zen mode, close vscode.
2. Open vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Have you tried, like, toggling it back?

**Comment by idarbuashvili** [comment]
Yes I tried ctrl+k z multiple times, tried all possible options but still nothing

**Comment by idarbuashvili** [comment]
It's something similar to https://github.com/Microsoft/vscode/issues/52550 this bug

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by idarbuashvili** [comment]
Hi sorry for such delayed response, so problem is same on insider, but small correction to the problem, the zen mode stays on not when exiting vscode normally like using alt+f4, but when you are in zen mode and PC is turned of from system or pc gets halted because of no power, I am on laptop. You can reproduce that pretty easily. BTW is there a quick fix? So I could get back normal window? Thanks

**Comment by idarbuashvili** [comment]
Basically, I would prefer zen mode to be off by default, so on start up if there is no config in the json for zen mode start vscode without it

**Comment by isidorn** [comment]
Just F1 > toggle zen mode
If that does not help do F1 > toggle full screen

Zen mode is off by default, and it is not restored by default.
Closing as desgined. If you disagree provide exact steps.

**Comment by idarbuashvili** [comment]
I don't understand why you closed this thread it is a problem and I provided exact steps needed to reproduce, on ubuntu 18.10 get into zen mode and restart pc from system, when booted open vscode and zen mode is still on and you can't get back to normal. I don't know what I can add more to this

**Comment by isidorn** [comment]
Ok, let's reopen and see if anybody else is hitting htis.

**Comment by idarbuashvili** [comment]
Can't you reproduce the above problem on your machine? It should be easily reproducible at least from my tests.

**Comment by isidorn** [comment]
No I can not. Bot on ubuntu and os x.

**Comment by idarbuashvili** [comment]
Hi, more news about the problem, so turned out that this was happening for a single project, opening new window ctrl + shift + n was getting everything back to normal, but still it's kind of strange why this was happening for a single project. Anyway thanks for the support and I believe this can be closed.

**Comment by isidorn** [comment]
Thanks. Check if you have any project level settings
