### ISSUE TITLE
VsCode does not work offline

### ISSUE THREAD

**Issue by costaeverton** [Microsoft/vscode#67052]
The VS Code only opens / runs when I'm with the PC connected to the Internet., On line.
When I'm working off line I try to open the VSCode, the software neither the "sign of life".
Then I have to use PSPAD to edit files when I'm offline.
Summary:
VS Code only works onLine.
OffLine does not work

**Comment by angelicjoe** [comment]
Please My Vscode just stopped working offline... 

When I run "code -- version" offline i see this result:

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13


Please HELP!
