### ISSUE TITLE
Opening VSCode from terminal prevents closing the terminal

### ISSUE THREAD

**Issue by brunolm** [Microsoft/vscode#67058]
- VSCode Version: Insiders for at least 6 months (I think it also happens on stable version)
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. open terminal (powershell)
1. go to a dir (`cd dir`)
1. open dir in VSCode (`code .`)
1. ** VSCode opens **
1. close terminal (`exit`)

The terminal doesn't close until I close VSCode. It tries to execute `exit` forever

Does this issue occur when all extensions are disabled?: Yes

---

Is there at least a workaround for this?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/66750
