### ISSUE TITLE
Middle-click paste in peek view pastes in main document

### ISSUE THREAD

**Issue by RossBrunton** [microsoft/vscode#67056]
Issue Type: <b>Bug</b>

* Be on Linux
* Open up a peek view (I used the C++ intellisense thing)
* Select some text
* Middle click at a point inside the peek view

I expect this to paste the selected text at the point at which I click inside the peek window.

Instead, it pastes the selected text "outside" the peek view at wherever the cursor is in the main document.

CTRL+V style pasting inside the peek window works as expected.

VS Code version: Code - Insiders 1.31.0-insider (50854c0a705745bbf50982fab3c30fd6bd1f7b19, 2019-01-24T10:16:12.982Z)
OS version: Linux x64 4.4.0-141-generic

**Comment by m93a** [comment]
I can replicate not only in peek view, but also when middle-clicking in the explorer to open up a new tab when the focus was previously in the editor.

**Comment by alexandrudima** [comment]
@rebornix Let's please use the `bug` label only when we have reproduced.

**Comment by alexandrudima** [comment]
I can not reproduce. I believe it was fixed in the meantime.

**Comment by RossBrunton** [comment]
Just tested it on a recent version, looks like something fixed this on my end. Thanks.
