### ISSUE TITLE
Typescript / Javascript Syntax: Coloring function declarations vs function calls

### ISSUE THREAD

**Issue by feluxe** [Microsoft/vscode#67050]
I was fiddling with this for a while... It looks like you can't use different highlighting for *function declarations* vs *function calls* in JS / TS.

Both *function declarations* and *function calls* appear in dark-red:

![highlighting_js](https://user-images.githubusercontent.com/6545589/51675247-6edc4280-1fd3-11e9-9e41-628b2f7bf962.png)

In Python I can use different highlighting for *function declarations* vs *function calls*:

![highlighting_py](https://user-images.githubusercontent.com/6545589/51675400-de523200-1fd3-11e9-8606-f882ed57979c.png)

I think it would be awesome, if this was possible for JS/TS as well.

Please excuse me if there is something I'm missing.

**Comment by usernamehw** [comment]
It's possible. Use this command to find scopes: `Developer: Inspect TM Scopes`.

**Comment by mjbvz** [comment]
This is up to the theme. Calls are scoped differently than definitions in our grammar so a theme can color them differently. Or you can override this yourself: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
