### ISSUE TITLE
the termnal window isn't showing the path of command line

### ISSUE THREAD

**Issue by ravigomez** [Microsoft/vscode#67065]
Issue Type: <b>Bug</b>

When you open the VCS for the first time, the terminal window isn't showing the path of command line at the first line.

VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:20:50.343Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
node-module-intellisense|lei|1.5.0
team|ms-|1.144.1

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
