### ISSUE TITLE
Grid: title bar appears much larger

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67063]
Steps:
* Enable grid layout in the workbench on macOS
* restart

=> the title part appears larger compared to stable:

Stable:
![image](https://user-images.githubusercontent.com/900690/51683527-59264780-1fea-11e9-9f00-d2db2d4f01cf.png)

Insiders:
![image](https://user-images.githubusercontent.com/900690/51683537-5e839200-1fea-11e9-9043-a76d79211841.png)

**Comment by bpasero** [comment]
@sbatten the height is still wrong for me when I compare stable to running out of sources:

![image](https://user-images.githubusercontent.com/900690/51822689-5de64680-22dd-11e9-9b49-49d370e6f8b9.png)

**Comment by sbatten** [comment]
@bpasero hmm... no repro, sources behind?

**Comment by bpasero** [comment]
@sbatten `"window.zoomLevel": 1`

**Comment by sbatten** [comment]
fixed by https://github.com/Microsoft/vscode/commit/e795093995c7382d0fb0f2e126f6f91aa81637c2

**Comment by sbatten** [comment]
for verification, please check with zoom:

1. macOS custom titlebar
2. windows or linux custom titlebar with hidden & non-hidden menu bar, hidden menu bar should function like macOS, non-hidden should zoom
