### ISSUE TITLE
Ligaratures are not working

### ISSUE THREAD

**Issue by cfanoulis** [Microsoft/vscode#67061]
Issue Type: <b>Bug</b>

1) Use `Fira Code` as your font with ligaratures enabled
2) Type `const true = true === true`

Expected result: The triple equality sign follows the ligaratures as in https://github.com/tonsky/FiraCode/blob/master/showcases/all_ligatures.png

Actual result: Ligaratures don't work and the triple equality sign stays as-is

VS Code version: Code - Insiders 1.31.0-insider (2d79ffe0cd84515a4c771fcbd7294c2448d97826, 2019-01-23T06:20:52.488Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
expressjs|ama|2.0.0
klasa-vscode|bdi|0.2.7
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.3
vsc-travis-ci-status|fel|1.1.0
discord-vscode|icr|3.2.1
path-autocomplete|ion|1.13.1
vsliveshare|ms-|0.3.1134
material-icon-theme|PKi|3.6.2
typescript-hero|rbb|3.0.0
rust|rus|0.5.3
crates|ser|0.3.6
vscode-wakatime|Wak|1.2.5
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by scottymcraig** [comment]
This either was already fixed or is something with your system.  I am assuming from your extensions you are running material theme.  I installed that and tried the line you suggested and got the correct ligature.  I'm running on 9fe48f, though which is 1/24's build.

![image](https://user-images.githubusercontent.com/6181734/51750685-d13f4c80-2080-11e9-8f6e-73b70b8890dd.png)

**Comment by cfanoulis** [comment]
Yeah, blame me, I didn't know I had to install the font on my laptop. Thanks yall 🙉
