### ISSUE TITLE
UX of Integrated: Commands to Skip Shell is horrible

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#67072]
Issue Type: UI/X
Version: 1.31.0-exploration (user setup)
Commit: 2af86da220e2b4c213d8b81ec5232e37e015054b
Date: 2019-01-24T10:02:57.458Z
Electron: 4.0.2
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Windows_NT x64 10.0.17763 (.253)

The Setting: `Integrated: Commands To Skip Shell` has horrible UI design. I have noted a few things about this:

Markdown isn't working:
  - `ctrl+p` could be put in inline fence
  - The list of `Default Skipped Commands` should have bullet points and be in fence blocks

And the description is just horribly long. If there is really a need to list all of them, how about making it (and possibly other settings too) collapsible OR put it in a settings reference (if one exists for that matter). It shouldn't be so long, especially with the static and small nature of the GUI

Here are some screenshots to demonstrate. Note I now have a 1920x1080 screen, and I had to take 3 different screenshots to capture them all. (I used the new Snip & Sketch so my whole screen isn't displayed, just the Settings area)

![image](https://user-images.githubusercontent.com/30497573/51694401-a5788400-1ff8-11e9-9f2c-cef0b548bd97.png)
![image](https://user-images.githubusercontent.com/30497573/51694414-ac9f9200-1ff8-11e9-8900-45f1f36fa689.png)
![image](https://user-images.githubusercontent.com/30497573/51694423-af9a8280-1ff8-11e9-899c-aee95c289195.png)

**Comment by roblourens** [comment]
Agreed, https://github.com/Microsoft/vscode/issues/66184
