### ISSUE TITLE
Exclude files by right clicking result in search panel

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode#67079]
Right now we can dismiss files and folders in the search result, but it would be a nice shortcut to be able to add them to the excluded files by right-clicking the file or folder in the results:

![screenshot from 2019-01-24 12 24 37](https://user-images.githubusercontent.com/7832163/51704494-73eec100-1fd6-11e9-86af-f7d6cfdeb397.png)

That way you could easily exclude them to let you tweak your search string and ignore any results that you don't want. This would be especially helpful for large projects or multi-folder workspaces.

**Comment by andreamah** [comment]
We now have an context menu option called "Exclude folder from search" that does this for folders at least, but not files
<img width="293" alt="image" src="https://user-images.githubusercontent.com/31675041/207948021-1e111dc3-cdb0-4a4d-a6ca-17c3d216f5a4.png">

**Comment by eleanorjboyd** [comment]
Closing as stale
