### ISSUE TITLE
Keep history in integrated terminal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6707]
It would be nice to keep some state of the terminal between restarts:
* the history of commands typed
* the last output

**Comment by Tyriar** [comment]
Right now we don't mess with any input/output at all, it's all deferred to the shell. This works perfectly for bash, just how it works via `gnome-terminal`.

```
$ history
...
 1981  npm init
 1982  npm install open
 1983  node
 1984  history
 1985  ls
 1986  history
 1987  exit
 1988  history
```

**Comment by bpasero** [comment]
I am using the default terminal on Mac OS.

**Comment by Tyriar** [comment]
Seems to work fine for me, <kbd>&uarr;</kbd> to go to recent commands, <kbd>ctrl</kbd>+<kbd>r</kbd> to do a lookup. Regardless, this sort of stuff we can't mess with at the moment as input and output is done by external libs. Restoring any state would also be very difficult currently. There's the possibility for this to change in #6838
