### ISSUE TITLE
Floating dropdowns in Settings UI

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#67073]
Version: 1.31.0-exploration (user setup)
Commit: 2af86da220e2b4c213d8b81ec5232e37e015054b
Date: 2019-01-24T10:02:57.458Z
Electron: 4.0.2
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Windows_NT x64 10.0.17763.253

NOTE: `workbench.useExperimentalGridLayout` was set to true
EDIT: Still occurs when set to False

Steps to Reproduce:

1. Open Settings GUI
2. Find Settings with dropdown, and click to open
3. Scroll the screen, you'll see dropdown doesn't close

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
These are supposed to hide when a scroll happens, but this broke from my tree changes. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/electron-browser/settingsEditor2.ts#L640
