### ISSUE TITLE
Improve hover presentation for complex errors

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67076]
Error hover is good in representing simple errors. But when it comes to complex and descriptive errors, inline error widget can represent them well. But inline error widget is not discoverable. 

- Ability to navigate to inline error widget from hover.
- Make hover look good with consistent font for the complete message.

**Comment by sandy081** [comment]
@jrieken Was there a reason for applying editor font in the hover error message? Currently editor font is applied only for message and not for related information.

**Comment by sandy081** [comment]
Did following improvements

- Used default font
- Increased the width
- Added `Go to Problem` and `Show Quick Fixes...` actions
- Improved related information rendering

![image](https://user-images.githubusercontent.com/10746682/52967552-c1c6d100-33aa-11e9-9fdf-d35d97552d9f.png)

![image](https://user-images.githubusercontent.com/10746682/52967591-dc994580-33aa-11e9-87cd-e615c8884e16.png)

**Comment by sandy081** [comment]
Following are the some examples of hovers and peek error widget after improvements.


![image](https://user-images.githubusercontent.com/10746682/53117653-ad6e0a00-354b-11e9-85e6-8f985ec2ffee.png)

![image](https://user-images.githubusercontent.com/10746682/53117762-ec03c480-354b-11e9-954e-446419800a7a.png)

![image](https://user-images.githubusercontent.com/10746682/53117567-7c8dd500-354b-11e9-9ffd-efbf5be7340b.png)

**Comment by sandy081** [comment]
Added the requested feedback

![image](https://user-images.githubusercontent.com/10746682/53161175-c3221480-35c9-11e9-8b23-38cc01b6ef31.png)

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode/issues/67076#issuecomment-464819660 looks amazing! This would make my life so much easier.

I see the latest screenshot uses the editor font again, why is that? The error message is prose and the diagnostics panel doesn't use the editor font either, nor do hovers..

**Comment by eamodio** [comment]
It looks like the lightbulb and go to problems actions are gone in the most recent insiders -- are they coming back?

**Comment by nealot** [comment]
I find the bottom bar really distracting since it's always the first thing I see when hovering over a problem. My preference would be to just have the icons attached to the top right corner or some other position that isn't so prominent.

**Comment by sandy081** [comment]
@felixfbecker Using normal or editor font for the error message is under discussion.

@eamodio It is back in the latest insiders

@nealot Keeping it at the bottom because it is easy to click these actions. Keeping it far away from the mouse makes it hard to click them as the hover can disappear when you move away mouse.
