### ISSUE TITLE
Filtering in explorer should reveal the match

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67083]
I typed this vscode-x and expected it to focus the result:

<img width="491" alt="screen shot 2019-01-24 at 1 13 25 pm" src="https://user-images.githubusercontent.com/2193314/51708888-e2814e00-1fd9-11e9-8ca4-59c2d662d310.png">

**Comment by eamodio** [comment]
The behavior I'm seeing with this is odd -- sometimes it works correctly and other times it won't focus even on a 100% match.

Also related, if you have it set to filter and select one of the items and then hit escape to clear the filter, the item isn't revealed properly (assuming there are enough items to push it off screen when not filtering)
