### ISSUE TITLE
option+delete to delete current word in explorer filtering input

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67087]
Issue Type: <b>Bug</b>

**Repo**

1. Using the new explorer filtering
1. type `node` in the explorer to start filtering 
1. Press `option + delete` (on MacOS)

**Bug**
Only a single character is deleted. `option + delete` normally deletes the current word on MacOS. I'd expect that while filtering, this keyboard shortcut could be used to clear previous work in the filter text

VS Code version: Code - Insiders 1.31.0-insider (50854c0a705745bbf50982fab3c30fd6bd1f7b19, 2019-01-24T09:09:43.349Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|-psn_0_15269519|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by joaomoreno** [comment]
Actually there are no words... since the spacebar is a no-op... so Option + delete would delete the whole thing, which would be the same as Escape. But yeah, we can do it.

**Comment by jrieken** [comment]
Doesn't work with `acc7365e41f9cb380e79bf78d7d102184f1ffe0d `. Pressing `Cmd+Delete` does nothing, pressing `Cmd+Backspace` moves focus

**Comment by jrieken** [comment]
It actually does work...
