### ISSUE TITLE
The ability to force an ansible ssh folder sync from a Task without requiring input

### ISSUE THREAD

**Issue by wasserman** [Microsoft/vscode#67084]
I have an Ansible task that updates a "static" inventory file.  This means the file is being changed on disk, not from within VS Code.  As a result I have to force a sync or do a trivial edit to the file and save it.  I want to streamline this from a Task, but the vscode-ansible.sync-folder-ssh dialog always requires interaction even though I just keep hitting ENTER to accept the defaults.  This required input makes the automation in the Task pointless.  Can you include some way to call it from a Task and passing in the values or some flag to accept defaults?

Here's a simple example of my Task:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Sync to remote ssh host",
            "type": "process",
            "command": "${command:vscode-ansible.sync-folder-ssh}"
        }
    ]
}
```

**Comment by wasserman** [comment]
I apologize, I meant to put this in the vscode-ansible repo.  But now that I think about it, maybe this is something that can be done at the VSCode level for any command?

**Comment by alexr00** [comment]
If you use insiders until the next release then this should give you what you're looking for: https://github.com/Microsoft/vscode/issues/64362. The documentation isn't updated yet, but for context here's the old documentation on inputs https://code.visualstudio.com/docs/editor/variables-reference#_settings-command-variables-and-input-variables.
