### ISSUE TITLE
cannot open jsconfig.json. Detail: file already exists on disk

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#6709]
- VSCode Version: 1.1.1- insider
- OS Version: win7

Steps to Reproduce:
1. project path: D:\#MYGIT\ndk
2. click to add jsconfig.json in popup message

ERROR:
cannot open untitled:d%3A%5C#MYGIT%5Cndk%5Cjsconfig.json. Detail: file already exists on disk
![2016-05-24_08h47_15](https://cloud.githubusercontent.com/assets/3082812/15493410/94454cee-218c-11e6-8534-5f32aee566db.png)

**Comment by jrieken** [comment]
The issue is stupid URI math we do here: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/utils/projectStatus.ts#L103. The path we simply concat contains a `#` and therefore becomes a fragment path.

**Comment by jrieken** [comment]
We should consider adding more uri modification methods: #6678

**Comment by jrieken** [comment]
**verifier** have a workspace folder that contains a `#` character
