### ISSUE TITLE
Why always screen on this tip when I debug the C# program.

### ISSUE THREAD

**Issue by SorashitaInnei** [Microsoft/vscode#67097]
- VSCode Version: 1.29.1
- OS Version: MacOS14.3

Steps to Reproduce:

1. C# debug with mono in Terminal
2. when vscode want to open the Terminal to debug and input the debug command automatically.

Does this issue occur when all extensions are disabled?: No

This window appears every time you click debug. and I always click the allow.
![image](https://user-images.githubusercontent.com/41265413/51728460-47f13f80-20ab-11e9-8068-3d858be31b74.png)

**Comment by weinand** [comment]
Could you please translate the alert to English.

**Comment by yiny0liuyin** [comment]
Sorry. This is prompt.
![image](https://user-images.githubusercontent.com/41265413/51742517-f6f64100-20d4-11e9-96c4-196759f96cb0.png)
