### ISSUE TITLE
Emmet: Wrap with abbreviation in jsx not producing className

### ISSUE THREAD

**Issue by wenfangcn** [Microsoft/vscode#67098]
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Should produce `className` not `class`
Steps to Reproduce:
![vscbug2](https://user-images.githubusercontent.com/28700378/51730224-9acdf580-20b1-11e9-8e83-7418039264f1.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Context here is React actually uses `className` instead of `class`.

**Comment by Vinnl** [comment]
Note that it did support this behaviour before, and regular Emmet expansions in JSX files _do_ generated `className` instead of `class`. In other words: it does look more like a bug than a feature request to me.

(Not sure how much it matters, but just mentioning it to be sure.)

**Comment by octref** [comment]
I see the problem — completion expands to `className`, but wrapping doesn't.

**Comment by burtek** [comment]
Any progress on that? @octref

**Comment by octref** [comment]
Contribution welcome, otherwise I'll get to this when I have time: https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/abbreviationActions.ts#L33-L35

**Comment by ramya-rao-a** [comment]
The link @octref shared is the right place to start for the Wrap with abbreviation feature.

https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/abbreviationActions.ts#L582 is where one should set a breakpoint to see what is the syntax being returned from the `getExpandOptions` call. The syntax property should `jsx` here for emmet to use `className` and not `class`

**Comment by mattkwiecien** [comment]
@ramya-rao-a I'd love to tackle this one if you don't mind.

**Comment by mattkwiecien** [comment]
@octref  Solved and in open PR https://github.com/Microsoft/vscode/pull/68326
