### ISSUE TITLE
Gnu/Linux Sensibilidad del click derecho en ventanas

### ISSUE THREAD

**Issue by HorusBlack** [microsoft/vscode#67096]
Issue Type: <b>Bug</b>

En Gnu/Linux: Al dar click derecho dentro de cualquier archivo abierto, en automatico, si el cursor esta apuntando a una opción del desplegable, se auto-selecciona la opción que este señalando el cursor. Se tiene que mantener precionado el boton derecho y mover el cursor fuera de las opciones para que funcione normal. 
NOTA: En windows no se genera ese error. Se probo si no era problema del hardware, pero al usar otros editores semejantes a vscode, el error no se replica.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.14.92-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1090T Processor (6 x 3214)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.79GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|10.2.0
numbered-bookmarks|ale|6.1.0
vscode-color|ans|0.4.5
theme-verdandi|be5|1.9.0
githistory|don|0.4.4
jquerysnippets|don|0.0.1
vscode-great-icons|emm|2.1.46
vsc-material-theme|Equ|2.6.3
php-intellisense|fel|2.3.10
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
ftp-simple|hum|0.6.8
crane|Hvy|0.3.8
vscode-pigments|jas|1.0.6
theme-karyfoundation-themes|kar|18.2.1
vscode-simple-icons|Lau|1.9.3
theme-monokai-pro-vscode|mon|1.1.9
vscode-language-pack-es|MS-|1.30.2
material-icon-theme|PKi|3.6.2
format-html-in-php|rif|1.5.1
LiveServer|rit|5.3.1
vscode-icons|rob|8.0.0
ayu|tea|0.17.0
highlight-matching-tag|vin|0.8.6
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.17.1

(6 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
From Google Translate:
In Gnu / Linux: By right clicking inside any open file, in automatic, if the cursor is pointing to a drop-down option, the option that is pointing at the cursor is auto-selected. You have to keep the right button pressed and move the cursor out of the options so that it works normally.
NOTE: In windows, this error is not generated. It was tested if it was not hardware problem, but when using other editors similar to vscode, the error is not replicated.

**Comment by joaomoreno** [comment]
@HorusBlack What window manager do you use?

**Comment by HorusBlack** [comment]
I work in XFCE.
As I commented when I open the options with the right mouse button and the cursor touched some option of the removable this is activated instantly. It can not be my mouse because the same hardware in Windows works well.
And in Manjaro XFCE only happens in Vscode. In other editors or IDE everything works fine.
(google Translate)

**Comment by HorusBlack** [comment]
(UPDATE 2019)
https://www.youtube.com/watch?v=dEBkO0ecKzY&feature=youtu.be

*ENGLISH (google translate)

* When loading the editor does not present problems. These appear when the extensions finish loading. When you right click with the mouse, the options open but the cursor automatically activates the option that you are currently dialing.
* You have to keep the right button pressed and move the cursor out of the options to avoid the error.
* We have tried to reproduce the same bug in other similar text editors and in some IDE, but without success, deducting that the error is in vscode.
* Comparing the behavior of vscode in windows 10,
  the difference is that when using said S.O when doing the same procedure as in linux, the options have a small time lapse before appearing, while in seconds they appear immediately without the possibility of avoiding automatic activation.

ESPAÑOL

*Al cargar el editor no presenta problemas. Estos aparecen cuando terminan de cargarse las extensiones. Al hacer click derecho con el mouse se abren las opciones pero el cursor automáticamente activa la opción que este marcando en ese momento.

*Se tiene que mantener presionado el botón derecho y mover el cursor fuera de las opciones para evitar el error.

*Se ha intentado reproducir el mismo bug en otros editores de texto semejantes y en algunos IDE, pero sin éxito, deduciendo que el error se encuentra en vscode.

*Comparando el comportamiento de vscode en windows 10, la diferencia radica en que al usar dicho S.O al hacer el mismo procedimiento que en linux, las opciones tienen un pequeño lapso de tiempo antes de aparecer, mientras que en en segundo aparecen de manera inmediata sin posibilidad de evitar la activación automática.

**Comment by HorusBlack** [comment]
Acabo de darme cuenta que el error lo provoca en entorno de escritorio XFCE. Al abrir vscode en otros entornos diferentes (KDE, Deepin) no se produce el mismo error. Que en resumidas cuentas se produce por la sensibilidad del boton derecho dentro de vscode
