### ISSUE TITLE
intellicode example doesn't load after enable but no reload of window

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#67093]
Insiders, MacOS

* Create an express app

```
npx express-generator myexpressapp
cd myexpressapp && npm install
code-insiders .
```
* Install the [IntelliCode extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)
* Disable the IntelliCode extension
* Press Reload to reload the environment
* In `app.js` add a line to get intellisense against `app`:

![image](https://user-images.githubusercontent.com/1487073/51720830-0bb6d400-2004-11e9-9322-9e5bbf2880a8.png)

* Enable the IntelliCode extension, note that you don't have to reload the window, there is no reload button

* In `app.js` try to get completions against `app.` again
result: The IntelliCode suggestions are not there (e.g. no starred items at top of list)

* Reload the window
* Try to get completions against `app.` again
result: you get IntelliCode suggestions at top of list

![image](https://user-images.githubusercontent.com/1487073/51720940-70722e80-2004-11e9-9656-6c18cff78f9f.png)

I'm not seeing anything in the devtools console.

**Comment by sandy081** [comment]
VS Code window is no longer required to reload after installing or enabling an extension. 

I see the extension is getting activated. Assigning to @jrieken for further investigation of suggestions.

**Comment by jrieken** [comment]
Please check with IntelliCode - suggestions can handle dynamic registration/unregistrations of providers but the IntelliCode might rely on TypeScript being restarted

**Comment by alexandrudima** [comment]
Indeed, it might be needed that we restart the TypeScript server:

From their `package.json`:
```
		"typescriptServerPlugins": [
			{
				"name": "@vsintellicode/typescript-intellicode-plugin",
				"languages": []
			}
		],
		"javaExtensions": [
			"node_modules/@vsintellicode/vscode-intellicode-java/server/com.microsoft.jdtls.intellicode.core-0.3.8.jar"
		]
```

I can add proposed API for when the `extensions.all` changes.

**Comment by alexandrudima** [comment]
fyi @mjbvz @aeschli I've added proposed API for `vscode.extensions.onDidChange`. When this fires, it means `vscode.extensions.all` has modified.

**Comment by lostintangent** [comment]
Are you thinking that VS Code will automatically detect the use of the `typescriptServerPlugins`, and restart the TS Server? IntelliCode also supports Java and Python in VS Code, so we'd need to validate those scenarios and see how they behave when installing/enabling IntelliCode without a reload.

**Comment by alexandrudima** [comment]
@lostintangent VS Code is not aware of "3rd party" extension points like `typescriptServerPlugins` or `javaExtensions`, so each extension that supports an extension point would need to add code to react to the change event... But the change event is proposed API for now, so it is easily available only to builtin extensions like typescript or json... I'm not sure what we're going to do for this milestone to avoid bugs in this area. I will bring it up with the team in our standup.

**Comment by mjbvz** [comment]
I've opened #67575 to track making the `typescriptServerPlugins` extension point dynamic. I don't want to try fixing this issue late in this iteration
