### ISSUE TITLE
Task config supports unknown options

### ISSUE THREAD

**Issue by actboy168** [microsoft/vscode#67095]
I have an extension that allows the task to support some new options.

E.g.
```json
        {
            "label": "Debug",
            "command": "start ${workspaceFolder}/runtime/windows/lua.exe",
            "args": [
                "-stopOnEntry"
            ],
            "options": {
                "statusbar": "hide"
            }
        }
```

My current implementation is parsing tasks.json. And I noticed that VSCode added a new task api `vscode.tasks.fetchTasks`. But it doesn't recognize the options I added.

Can fetchTasks read unknown options?

**Comment by alexr00** [comment]
Task configuration does not support anything like this right now.

**Comment by alexr00** [comment]
This is as designed. We do not support passing arbitrary options into tasks.
