### ISSUE TITLE
Add Some New Features in MarketPlace and Codeing Style

### ISSUE THREAD

**Issue by wmtjaychhatrola** [Microsoft/vscode#67099]
##I m not insulting any developer, I just want to share some information.

-> In marketplace provide filter like sorting using rating extensions.
-> The second one is completely missing bracket automatically.
-> Code Formatting is good but one change is the remaining space cannot automatically set.

**Comment by sbatten** [comment]
@wmtjaychhatrola It seems like this feedback contains various points about different areas of the product. Would you mind opening separate issues for each and elaborating on them for clarity. Thank you.

As for sorting extensions, you can add `@sort:rating` to your query to sort by rating. 

![image](https://user-images.githubusercontent.com/6561887/51762783-8bd14e00-2085-11e9-90fd-4d6a8c79ced8.png)
