### ISSUE TITLE
The scrollbar thumb is not working correctly when opening a large document.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/vscode#6710]
- VSCode Version: 1.1.1
- OS Version: windows 8.1

Steps to Reproduce:
1.  open a very large document, like typescript.js
2.  drag the vertical scrollbar thumb.

When mouse button click the thumb and start to move, the thumb will move up some pixels.

**Comment by heroboy** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/54468/15496354/4ab4612e-21c7-11e6-93e8-c822cab3f984.gif)

**Comment by heroboy** [comment]
Finally, it closed. Thanks.

**Comment by Tekbr** [comment]
Thank you so much @alexandrudima . 👏 👏 😄
