### ISSUE TITLE
The [S]uspend option for a Write-Debug statement does not seem to work.

### ISSUE THREAD

**Issue by autocloudarc** [Microsoft/vscode#67102]
Issue Type: <b>Bug</b>

When using the PowerShell integrated console and during script execution, when a write-debug command is reached, after selecting S to suspend execution, the script continues to prompt me instead of transitioning to the nested prompt for debugging.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (1 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|3.50GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.0
gitlens|eam|9.4.1
PowerShell|ms-|1.11.0
team|ms-|1.144.1

</details>

**Comment by autocloudarc** [comment]
![debug-suspend-option-does-not-seem-to-work-25jan2019](https://user-images.githubusercontent.com/15109536/51735764-2464cf80-2080-11e9-8042-a0491b2d133c.png)

**Comment by autocloudarc** [comment]
Thanks for the quick response @weinand :-)

**Comment by weinand** [comment]
@autocloudarc You don't have to thank me. It was the bot... ;-)
