### ISSUE TITLE
"editor/title" icons do not show up when vscode opens

### ISSUE THREAD

**Issue by roonyh** [Microsoft/vscode#67104]
- VSCode Version: 1.30.2
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. Have an extension with contributions to "menus: editor/title"
~~~
"contrubutes": {
        "menus": {
            "editor/title": [
                {
                    "when": "resourceLangId == ballerina",
                    "command": "ballerina.showDiagram",
                    "group": "navigation"
                }
            ]
        }
}
~~~

2. When vscode opens up at first these icons are not visible. Only when you open a second file they become visible.  The "when" condition is met even the first time.

The Git lens extensions icons also suffer from this.

**Comment by roonyh** [comment]
Here's a minimum verifiable example extension for the problem. https://github.com/roonyh/icon-bug

Following is a .gif showing the problem.
![iconbug](https://user-images.githubusercontent.com/3872221/51893817-0672d400-23cc-11e9-8dc0-f523baa5241f.gif)

**Comment by bpasero** [comment]
@roonyh thanks for providing a full test extension to reproduce. I can see this bug in our stable release but not in our insiders release so I am assuming we fixed it. Though I cannot tell which commit caused it.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
