### ISSUE TITLE
Bad alignment in extension editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67105]
The uninstall button should be left-aligned

![screenshot from 2019-01-25 10-33-18](https://user-images.githubusercontent.com/22350/51737378-b83c9880-208c-11e9-8ee9-7288742eebdc.png)

**Comment by sandy081** [comment]
@joaomoreno button is aligned with the text above. Aligning the `button` label will push the button not to be aligned which might look not good.

**Comment by sandy081** [comment]
Hmmm 🤔 you got a very sharp eyes 👀 😄 . 

By looking at it I felt they are aligned and thought you want to align the label inside the button with the text above.
