### ISSUE TITLE
Extension host stopped working

### ISSUE THREAD

**Issue by morlandi-jss** [Microsoft/vscode#67110]
Issue Type: <b>Bug</b>

Extension host continue to crash even if I've a very minimal set of plugins  (Typescript hero, TypeScript ast outline, material icon theme and psioniq file header). 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-ast-outline|can|0.0.5
material-icon-theme|PKi|3.6.2
psi-header|psi|1.6.6
typescript-hero|rbb|3.0.0

</details>

**Comment by alexandrudima** [comment]
@morlandi-jss From the attached log, it looks like the extension host is running out of memory. Did you try to disable `typescript-hero`? Did you try to disable `vscode-typescript-ast-outline` ? It does not matter the extension count, even a single extension can cause an out of memory situation if it contains a memory leak.
