### ISSUE TITLE
Right click on line match in Search results opens editor tab

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#67114]
Issue Type: <b>Bug</b>

1. Perform any global search
1. Right click on file match - only context menu appears
1. Right clicks on line match - file is opened in editor tab(same as left click) and context menu appears.

Current behavior is a bit distracting if I only want to dismiss file or Copy results.

Stable version `1.30.2` doesn't have this problem

VS Code version: Code - Insiders 1.31.0-insider (9fe48f15b1a252a0e9e1ef5975301203baf10b8a, 2019-01-25T08:19:36.277Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (16.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Good catch

**Comment by roblourens** [comment]
This also affected comments and markers trees @RMacfarlane @sandy081 @joaomoreno
