### ISSUE TITLE
Menu not translated

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6711]
- VSCode Version: latest alpha
- OS Version: OS X

Steps to Reproduce:

1. VSCode > Configure language > set DE
2. Restart VSCode - notice everything is in german except the menu

![screen shot 2016-05-24 at 09 47 30](https://cloud.githubusercontent.com/assets/1926584/15496294/bbfb0f50-2194-11e6-9748-893daf9443f5.png)

**Comment by dbaeumer** [comment]
Joao moved the workbench code and we haven't received any translations back so far. Closing since it will be fixed with the next translation drop.
