### ISSUE TITLE
AutoImport not working for NPM packages, only in JS/JSX

### ISSUE THREAD

**Issue by CharlieIGG** [Microsoft/vscode#67126]
Issue Type: <b>Bug</b>

I have this weird issue where AutoImport won't work for NPM packages when using JS or JSX. However it DOES work for:
- Local files
- when using Typescript instead of JS

I haven't found any issue quite like this, so I finally decided to ask for clues. Any hints at how to fix this would be greatly appreciated. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.8
rails-partial|aki|0.1.0
jest-snippets|and|1.6.1
ng-template|Ang|0.1.11
rails|bun|0.8.6
vscode-gemfile|bun|0.0.2
solargraph|cas|0.19.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
ionic3-vs-ionView-snippets|dan|1.0.2
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.7.3
todo-tree|Gru|0.0.115
beautify|Hoo|1.4.7
RelativePath|jak|1.4.0
vscode-styled-components|jpo|0.0.25
rspec-snippets|kar|0.0.4
coffeelinter|lky|1.4.0
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
ruby-rubocop|mis|0.7.1
vscode-elixir|mjm|1.1.0
vscode-postcss-sorting|mrm|3.0.1
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.5
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
vscode-docker|Pet|0.5.1
material-icon-theme|PKi|3.6.2
ruby|reb|0.21.0
slim|sia|0.1.2
addDocComments|ste|0.0.8
highlight-matching-tag|vin|0.8.6
simple-ruby-erb|vor|0.2.1
vscode-js-import|wan|0.15.4
change-case|wma|1.0.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by CharlieIGG** [comment]
I'll check it out tomorrow early @mjbvz , thanks for the followup

**Comment by mjbvz** [comment]
Closing as we need more information to investigate. @CharlieIGG if this still occurs in the latest VS Code release, please let me know

**Comment by CharlieIGG** [comment]
Guys, my bad. This was in the docs. 
For the reference of anybody else who stumbles into this:

👉TS projects seems to have no issue regardless of the config, but
👉More often than not, Javascript projects will require the presence of a `jsconfig`, with at least a basic config as this:
```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
