### ISSUE TITLE
Running debug launch config causes unresponsive window

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67128]
Issue Type: <b>Bug</b>

I encounter this when running the "Download Extensions" launch config in the "vscode-tools" repository. Quickly after the start the window becomes totally unresponsive and after a while I get the modal telling we the same.

In stable, the window also slows down badly but never becomes totally unresponsive. When running the process explorer I see high CPU usage in the launched node process (expected) and high CPU usage in the window process (unexpected).

This used to run without issues, at least I don't remember any.

VS Code version: Code - Insiders 1.31.0-insider (9fe48f15b1a252a0e9e1ef5975301203baf10b8a, 2019-01-25T08:11:48.342Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|-psn_0_27904667|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
markdown-yaml-preamble|bie|0.0.2
solargraph|cas|0.19.1
ssh|chr|0.0.4
gitlens|eam|9.4.1
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
vscode-pull-request-github-insiders|Git|1.24.0
crazy|kie|0.0.2
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.5.0
python|ms-|2018.12.1
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
Go|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.1
material-icon-theme|PKi|3.6.2
ruby|reb|0.21.0
vscode-xml|red|0.2.0
bash-debug|rog|0.3.3
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by weinand** [comment]
@kieferrm does this repro when running with extensions disabled?

**Comment by weinand** [comment]
I'm pretty sure that this issue is unrelated to debugging but is an issue with the file watcher (because the extension are downloaded into the workspace).
Since I'm sitting in a RhB train I cannot easily verify...
@kieferrm does it make a difference if you change the argument passed to the "--extension" to a location outside of the workspace, e.g. `/tmp/xxx`.

**Comment by weinand** [comment]
I've ran the program three times and downloading of the 100 extensions took 4 minutes each but I never experienced any issues.

**Comment by weinand** [comment]
running with 14 MBit (LTE) connection: downloads all extension in under 1 minute and still no issues.

**Comment by roblourens** [comment]
I can't repro. Took maybe 30-40s to download extensions

**Comment by weinand** [comment]
@kieferrm please try to repro with disabled extensions

**Comment by weinand** [comment]
@joaomoreno maybe another tree issue?

**Comment by joaomoreno** [comment]
@kieferrm We found a perf issue when an app was creating quite some output in the repl. Does that app generate a considerable amount of output?

**Comment by kieferrm** [comment]
I reran the launch config (it runs for hours...) and it's fine now. No, more issues.
