### ISSUE TITLE
Issues when creating news files and when having read/write implemented

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#67120]
- VSCode Version: Version 1.31.0-insider (1.31.0-insider)
9fe48f15b1a252a0e9e1ef5975301203baf10b8a
2019-01-25T08:04:51.283Z

- OS Version: macOS 10.14.3

Downloaded insiders to test out fix to #66759, but now it's failing with a different issue.

Steps to Reproduce:

1. Implement a custom [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), including all four lower-level functions `open`,  `close`,`read`, `write` in the proposed api (introduced in fa5922bd304b3d28ee022d4ea814c4a2a67c6766)
2. Add a uri under the provider as a workspace root
3. Create a new file in the explorer view and name it.
4. Note `FileSystemProvider.close` (?) is called with a null (!) fd
5. Note `write` is never called (nor the older `writeFile`)
6. Note `stat` is then called for the non-existent file
7. That's it, results in 'Failed to create' error in the ui

**Comment by johnspurlock** [comment]
Thanks! I will check it out in an upcoming insiders build.

**Comment by johnspurlock** [comment]
Seems to work in today's insiders.

Note that `read` seems to be called twice, even when returning a positive n < `length` for the first `read` call.  Is that intentional?

**Comment by jrieken** [comment]
> Note that read seems to be called twice, even when returning a positive n < length for the first read call. Is that intentional?

Yeah, only when `0` is returned we stop asking. The `length` argument is our wish but if the providing side cannot off a chunk of that size we cannot assume that everything has been read.
