### ISSUE TITLE
Right click on Type

### ISSUE THREAD

**Issue by TomSputz** [Microsoft/vscode#67125]
A when clause for context menus that depends on the type of the right-clicked variable

something like

```json
"editor/title": [{
    "when": "textType == object",
    "command": "extension.Command",
    "group": "myGroup@1"
}]
```

This would enable better integrations where code means something to another application. It came up in the context of tabletop simulator modding, where it would be useful to have access to the intellisense info to act on specific in-game objects through their types

**Comment by jrieken** [comment]
> that depends on the type

What type? The language id?

**Comment by TomSputz** [comment]
I was thinking the 'type' of the text returned by the language server. I'm not sure how tied to each specific language it would be. Being able to check if it is a variable or type of structure, and maybe see the line the variable was defined on. In this case

`input`:

```lua
const_id = 'MyID'
const_obj = Objects[const_id] -- or getObject(const_id)

obj.doThing()
```

`extension`:

```js
editor.on('rightClick', element => {
  console.log(element.key /* or element.args */) // => MyID
})
```
, it would be to allow right clicking on the final instance of 'obj' and having a set of entries in the context menu that can make use of the `const_id` string.

~~In case its not painfully obvious, I have no idea how intellisense works internally. Just say if this is completely unreasonable~~

**Comment by jrieken** [comment]
It kind of is unreasonable :-) Menus (as well as keybindings) work of context keys and they must be know at the time of execution (when clicking and creating the menu). That makes everything asynchronous, like going to a language service, a headache. What you could do is the set that context as the selection changes. Extension can do that using the `setContext`-[command](
https://github.com/Microsoft/vscode/issues/10471#issuecomment-239764839) but it will be hard to get this right.
