### ISSUE TITLE
Clickable URL in terminal appends a single quote in the browser

### ISSUE THREAD

**Issue by Tazeg** [Microsoft/vscode#67139]
Issue Type: <b>Bug</b>

When a URL is between single quotes in the terminal, we can open it with CTRL+CLICK but an encoded quote is added at the end in the browser.

To reproduce, type in terminal :

    echo "{ url: 'https://example.com?test=123456'}"

The url in the brower is :

    https://example.com/?test=123456%27

I tried with 2 different default browsers on system.
No problem with double quote.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz (8 x 3324)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.62GB (4.41GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-PSStackoverflow|Dou|0.0.2
better-toml|bun|0.3.2
vscode-eslint|dba|1.8.0
latex-workshop|Jam|5.21.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
python|ms-|2018.12.1
vetur|oct|0.14.5
vscode-docker|Pet|0.5.1
vscode-php-getters-setters|php|1.2.3
java|red|0.37.0
vscode-icons|rob|8.0.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.0
twig|wha|1.0.2

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/21125
