### ISSUE TITLE
False Error Messages

### ISSUE THREAD

**Issue by gbracey** [Microsoft/vscode#67142]
Issue Type: <b>Bug</b>

VS Code shows error messages in my code.  Building and running works fine however.  I have to close VS Code and restart it for the errors to go away (no code changes were made - just restarting VS Code).

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|31.90GB (25.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.2

</details>

**Comment by mjbvz** [comment]
What language are you writing?

**Comment by mjbvz** [comment]
Please file this against the c# extension
