### ISSUE TITLE
File extensions affect Explorer's sort order

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#67154]
From a discussion with @Rojuinex on Gitter:

In a VS Code project create 2 folders with 3 files each:
```
with extensions
    aaa.txt
    bob.txt
    bob_test.txt
without extensions
    aaa
    bob
    bob_test
```

Observe:
VS Code sorts the files differently if they have extensions:

<img width="244" alt="2019-01-26_10-13-59" src="https://user-images.githubusercontent.com/1898161/51785103-1fbd1b80-2153-11e9-94bb-0979ff08fc8d.png">
This is unexpected and IMO an error.

---

Interestingly the macOS Finder suffers from the same problem:

<img width="214" alt="2019-01-26_10-16-51" src="https://user-images.githubusercontent.com/1898161/51785125-88a49380-2153-11e9-82d5-5f0f88b72a38.png">

But Windows does not:

<img width="372" alt="2019-01-26_10-19-51" src="https://user-images.githubusercontent.com/1898161/51785160-ed5fee00-2153-11e9-8be6-33634e9073f8.png">

And ubuntu linux does not:

<img width="263" alt="2019-01-26_10-25-39" src="https://user-images.githubusercontent.com/1898161/51785229-dcfc4300-2154-11e9-8321-99f26622b8c0.png">

**Comment by kzhui125** [comment]
macOS compare file names with file extension (.txt)
bob_ < bob.
Windows compare file names without file extension(.txt)
bob_ > bob

**Comment by weinand** [comment]
I'm reopening this because it is not a duplicate of #27759 but an independent bug.
