### ISSUE TITLE
A very serious CPU leak problem!!!

### ISSUE THREAD

**Issue by ddzy** [Microsoft/vscode#67150]
Issue Type: <b>Performance Issue</b>

## Source
Since version 1.29 of vscode, my workbench often stop working just like this:

![vscode_issue_7](https://user-images.githubusercontent.com/33921398/51781535-bf2ede00-2154-11e9-9f7d-08a9620a09d2.jpg)

**_It usually appears when I am working and every 30-50 minutes_**

## Current Feature
When this happens, my CPU will increase to 100% and last for two minutes. Then I open the process manager of vscode and saw this phenomenon...

![vscode_issue_1](https://user-images.githubusercontent.com/33921398/51781590-b2f75080-2155-11e9-9c0f-a8eeea3b47af.jpg)
![vscode_issue_2](https://user-images.githubusercontent.com/33921398/51781591-b38fe700-2155-11e9-8f14-1b0123fcbfa4.jpg)
![vscode_issue_3](https://user-images.githubusercontent.com/33921398/51781592-b38fe700-2155-11e9-9308-0217455b2527.jpg)
![vscode_issue_4](https://user-images.githubusercontent.com/33921398/51781593-b4287d80-2155-11e9-9399-be03bf04f9f1.jpg)
![vscode_issue_5](https://user-images.githubusercontent.com/33921398/51781594-b4c11400-2155-11e9-9add-60a0c8b05a69.jpg)
![vscode_issue_6](https://user-images.githubusercontent.com/33921398/51781596-b559aa80-2155-11e9-88d8-7aed4821c326.jpg)

## Expected Feature
I don't know what caused this problem, it is very serious, I need your help.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|7.89GB (2.37GB free)|
|Process Argv|--disable-gpu --enable-use-zoom-for-dsf --disable-directwrite-for-UI|
|Screen Reader|no|
|VM|50%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   193	 14140	code main
    0	    70	  9872	   shared-process
    0	   282	 11144	   window (BrowserRouter.tsx - 无标题 (工作区) - Visual Studio Code)
    0	    10	  8456	     winpty-process
    0	    72	 14076	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 19332	         C:\WINDOWS\system32\cmd.exe /c ""D:\nodeJs\npm.cmd" start"
    0	    35	   576	           electron_node npm-cli.js 
    0	     5	 18836	             C:\WINDOWS\system32\cmd.exe /d /s /c react-scripts-ts start
    0	    26	  1976	               node   "D:\Code\yyg-react-router-dom\node_modules\.bin\\..\react-scripts-ts\bin\react-scripts-ts.js" start
    0	   122	 15192	                 node D:\Code\yyg-react-router-dom\node_modules\react-scripts-ts\scripts\start.js
    0	   169	 13516	                   electron_node service.js 
    0	    12	 16284	       console-window-host (Windows internal process)
    0	    10	  8824	     winpty-process
    0	    71	  3548	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	 14716	       console-window-host (Windows internal process)
    0	    93	  9296	     extensionHost
    0	    48	  2648	       "F:\Microsoft VS Code\Code.exe" "f:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=9296
    0	   180	 11508	       electron_node tsserver.js 
    0	    51	  3880	         electron_node typingsInstaller.js typesMap.js 
    0	    52	 11020	     watcherService
    0	    47	 14960	     searchService
    2	    86	 14488	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (BrowserRouter.tsx - 无标题 (工作区) - Visual Studio Code)
|    Folder (webpack_study): 8 files
|      File types: ts(3) json(3) js(1) css(1)
|      Conf files: package.json(1) tsconfig.json(1) webpack.config.js(1)
|    Folder (ts-utility-plugins): 20 files
|      File types: ts(6) js(6) json(3) gitignore(1) md(1) yml(1) html(1)
|      Conf files: package.json(1) tsconfig.json(1)
|    Folder (yyg-react-router-dom): 22 files
|      File types: tsx(12) json(6) gitignore(1) ts(1) md(1) html(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|    Folder (react-router): 248 files
|      File types: js(155) md(47) json(12) png(7) eslintrc(5) gitignore(4)
|                  prettierignore(3) babelrc(3) yml(2) prettierrc(1)
|      Conf files: package.json(4) webpack.config.js(1)
|    Folder (ts-web-diary): 260 files
|      File types: tsx(174) ts(59) jpg(13) json(6) png(2) gitignore(1) js(1)
|                  md(1) html(1) ico(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|    Folder (blog): 403 files
|      File types: jpg(79) html(62) styl(52) swig(40) js(32) ejs(29) md(20)
|                  yml(20) png(13) css(11)
|      Conf files: package.json(3) grunt.js(1);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-great-icons|emm|2.1.46
vscode-power-mode|hoo|2.2.0
vscode-styled-components|jpo|0.0.25
types-autoinstaller|jvi|2.4.0
easy-less|mrc|1.4.5
vscode-language-pack-zh-hans|MS-|1.30.2
vetur|oct|0.14.5
LiveServer|rit|5.3.1
px-to-rem|sai|1.2.7
autoimport|ste|1.5.3
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.0.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> When this happens, my CPU will increase to 100% and last for two minutes.

Of which process?

**Comment by ddzy** [comment]
> > When this happens, my CPU will increase to 100% and last for two minutes.
> 
> Of which process?

Oh, maybe my statement is a bit problematic. The truth is, when I work, it happens every 30-50 minutes. When I open the process manager of vscode, there will be a lot of unnamed process...

**Comment by ddzy** [comment]
> > When this happens, my CPU will increase to 100% and last for two minutes.
> 
> Of which process?

I am using vscode-exploration now, I have not found this situation yet.

**Comment by ddzy** [comment]
I am using vscode-exploration now, I have not found this situation yet.

**Comment by jrieken** [comment]
> vscode-exploration

What is that? An extension? Again, what is the name/command of the process that goes crazy?

**Comment by ddzy** [comment]
> > vscode-exploration
> 
> What is that? An extension? Again, what is the name/command of the process that goes crazy?

All crazy processes have no name

**Comment by jrieken** [comment]
Weird... So when this happens, please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by ddzy** [comment]
> Weird... So when this happens, please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

🤔
