### ISSUE TITLE
Running Visual Code prevents H/W acceleraed graphics in other (!) applications on the PC.

### ISSUE THREAD

**Issue by c-smile** [microsoft/vscode#67151]
When Visual Code application is running on Windows 10 desktop it causes D3D11CreateDevice(D3D_DRIVER_TYPE_HARDWARE) API to fail in other (sic!) applications.

- VSCode Version: 1.30.2 (system setup)
- OS Version: Windows 10, Version 1803 (Build 17134.523)  

Steps to Reproduce:

1. Run Code.exe ( Microsoft Visual Code executable )
2. Run any other application that has code like this to create DirectX 11 device:
```
HRESULT hresult = D3D11CreateDevice(
        nullptr, D3D_DRIVER_TYPE_HARDWARE, 0, D3D11_CREATE_DEVICE_BGRA_SUPPORT, nullptr,0, 
        D3D11_SDK_VERSION,  &_device_3D, nullptr, nullptr); // ID3D11Device* _device_3D;

```
note that hresult will be E_FAIL - D3D11CreateDevice fails to create device.

For the note this works:

```
HRESULT hresult = D3D11CreateDevice(
        nullptr, D3D_DRIVER_TYPE_WARP, 0, D3D11_CREATE_DEVICE_BGRA_SUPPORT, nullptr,0, 
        D3D11_SDK_VERSION,  &_device_3D, nullptr, nullptr); // ID3D11Device* _device_3D;

```

Therefore Visual Code effectively prevents H/W acceleration of all other applications running on the PC.

Does this issue occur when all extensions are disabled?: Yes

To verify you can use https://github.com/c-smile/sciter-sdk/tree/master/bin/32/usciter.exe executable  (you will need sciter.dll to be present in the same folder). The application shows _GFX backend_ mode, Value of the field can be either "direct2d" (H/W accelerated backend is on) or "direct2d-warp" ( if D3D11CreateDevice fails - WARP is used).

UPDATE: 

It may happen not always, closing Code.exe and reopening it again increases the chance of the issue.

UPDATE #2:
Seems like common Electron issue:  GitHub Desktop exhibits the same effect.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
