### ISSUE TITLE
Autoclose old issues

### ISSUE THREAD

**Issue by thecodingdude** [Microsoft/vscode#67157]
Hi. I decided to make a quick script to understand the scope of issues in this repo. Here is a breakdown:

```
{ totalOpenIssues: 4565,
  noLabel: 131,
  noComments: 1019,
  noAssignee: 1343,
  noMilestone: 2430,
  created2015: 53,
  created2016: 449,
  created2017: 1082,
  created2018: 2589,
  created2019: 392 }
```
In %'s that's:

noLabel: 2.86%
noComments: 22.32%
noAssignee: 29.41%
noMilestone: 53.23%
created2015: 1.16%
created2016: 9.83%
created2017: 23.70%
created2018: 56.71%
created2019: 8.58%

We can see of the open issues a lot have no comments or an assignee/milestone. Is it worth reviewing these older ones and closing them, perhaps encouraging users to file new issues if they still persist? I notice a lot of Github repos have issues/PR's spanning years with no input from project members.

**Comment by Mlocik97-issues** [comment]
that mean nothing... every opened issue (with real problem) needed to be solved.

**Comment by sbatten** [comment]
@thecodingdude while we appreciate the insight here, we do take time to look at the breakdown of issues and close old ones that we deem no longer relevant. some issues regardless of age are still relevant and should stick around for tracking purposes. thanks for looking out :)
