### ISSUE TITLE
Autocomplete suggestions on shortcut (ctrl + space) only

### ISSUE THREAD

**Issue by zzador** [Microsoft/vscode#67159]
It would be very helpful to have a flag in the settings.json to set under what conditions the autocomplete kicks in. I more and more often finding myself accidentally changing the last word of the currently written line to another word by just pressing enter to come to the next line.
As I have already seen the option to disable autocomplete on enter and only accept suggestions with the tab key it seems much more convenient to only bring up the suggestions on the shortcut (ctrl + space) in my opinion. The shortcut to show the autocomplete suggestions is already "learned" by most developers out in the field while I personally haven't seen someone who accepts the autocomplete suggestions with tab on a daily basis.

**Comment by sbatten** [comment]
```
"editor.suggestOnTriggerCharacters": false,
"editor.quickSuggestions": {
  "other": false,
  "comments": false,
  "strings": false
}
```

@zzador I think the following settings will help you.

**Comment by zzador** [comment]
Yes, this sets exactly the behaviour I was looking for. Thank you.
