### ISSUE TITLE
VSCode工作区域项目文件夹吸顶

### ISSUE THREAD

**Issue by StriverF** [Microsoft/vscode#67153]
我的工作区里面添加了多个项目，当我浏览项目文件列表的时候，我不能一眼看出当前浏览的文件是哪个项目，所以我建议工作区内的项目文件夹悬浮吸顶。
![image](https://user-images.githubusercontent.com/12794684/51784339-15fedc80-2182-11e9-8890-1e077ccf8289.png)
![wx20190126-154832](https://user-images.githubusercontent.com/12794684/51784345-2adb7000-2182-11e9-8e91-f3bb587061f4.png)

**Comment by tsangint** [comment]
https://code.visualstudio.com/updates/v1_26#_breadcrumbs
