### ISSUE TITLE
VS Code (Regular and Insiders) Settings Got Wiped Out

### ISSUE THREAD

**Issue by fourpastmidnight** [Microsoft/vscode#67162]
- VSCode Version:
    - Regular:
        > Version: 1.30.2 (user setup)
        > Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
        > Date: 2019-01-07T22:54:13.295Z
        > Electron: 2.0.12
        > Chrome: 61.0.3163.100
        > Node.js: 8.9.3
        > V8: 6.1.534.41
        > OS: Windows_NT x64 10.0.17763

    - Insiders:
        > Version: 1.31.0-insider (user setup)
        > Commit: 79663a770d1fdc90a91e51a52f1bee85653555b2
        > Date: 2019-01-18T06:20:31.475Z
        > Electron: 3.0.13
        > Chrome: 66.0.3359.181
        > Node.js: 10.2.0
        > V8: 6.6.346.32
        > OS: Windows_NT x64 10.0.17763

## Steps to Reproduce:

Not sure how to reproduce it, after all, all of my settings got wiped out! I can tell you that unfortunately, my organization gives us 500GB SDDs and my hard disk space was at/near 0 (_literally_) this morning. For some reason, Windows gives me back ~50GB, then steadily consumes it until nothing is left--then reboot, and magically, 50GB is back.... :|  Anyway, being out of disk space is most likely what caused them to get wiped out--when VS Code tried to write settings back to the file and couldn't (though, why VS Code would be trying to write settings to the file is beyond me since I wasn't actively editing any settings. Though, I do have the Settings Sync (`shan.code-settings-sync`) extension installed, so that may be something to look into since it could be doing some "background" writes to the settings file unbeknownst to me.)

Anyway, the point is, my settings are all wiped out for both Regular and Insiders VS code. Both were running. I switched applications (ALT+TAB) and when I switched to VS Code, there was a dialog saying that the PowerShell session needs to be restarted because of a settings change--so I clicked Yes. I did this in _each_ of my VS Code (regular and Insiders) windows that I had opened, not understanding what had just happened. I am NOT happy.

BTW, this is technically a dup of #25427 and #26381, but since you guys have a habit of locking issues that haven't seen activity, I now need to create yet another issue for this bug.

## Does this issue occur when all extensions are disabled?: Yes/No

Since I can't reproduce this issue "on-demand", I cannot answer this question.

**Comment by sandy081** [comment]
@bpasero Any insights about this? User says running out of disk space caused it.

**Comment by bpasero** [comment]
@sandy081 that can happen due to the nature how files are written to disk by first truncating them and then trying to write. If the write fails, the file ends up empty. Already reported for normal files here: https://github.com/Microsoft/vscode/issues/34915

**Comment by bpasero** [comment]
Yeah the trick of writing to a temporary file first and then overwriting the existing one is possible. However has the downside of external file watchers typically failing to record this operation as a change to the file. That is one of the reasons we are not doing this for normal saves in the editor.

**Comment by fourpastmidnight** [comment]
_Ahhhh_. Hmmm. 😐

**Comment by fourpastmidnight** [comment]
OK, it happened again today. This time, though, I managed to have ~2GB of free HDD space.... At least this time, I was smart and backed up a copy elsewhere. ;)

**Comment by fourpastmidnight** [comment]
VS Code Insiders got updated today, too, so here's the new version info for that:

- VS Code Insiders:
    > Version: 1.31.0-insider (user setup)
    > Commit: 1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c
    > Date: 2019-01-28T06:21:00.148Z
    > Electron: 3.1.2
    > Chrome: 66.0.3359.181
    > Node.js: 10.2.0
    > V8: 6.6.346.32
    > OS: Windows_NT x64 10.0.17763

**Comment by fourpastmidnight** [comment]
Hmm, just closed VS Code after "restoring" my settings, and upon startup, it got wiped out again--still with ~2GB free space. I guess I need to see if there's some extension not playing nice.... I'll report back after restarting with no extensions enabled.

**Comment by fourpastmidnight** [comment]
After disabling all extensions, my settings stopped getting wiped out. I've re-enabled a few, but so far, the settings are sticking.

But I still maintain that perhaps there could be found a better way for VS Code to manage how the settings file is accessed by extensions to help prevent errant (or even malignant) extensions from wiping out user settings?

(Other than that open question above, I'm OK with this issue being closed since the "thing" causing settings to get wiped out is not VS Code proper.)

**Comment by sandy081** [comment]
@fourpastmidnight Thanks for nailing it down. Can you please do it further and see which extension is causing it?

**Comment by sandy081** [comment]
No worries. Please take your time and get back to us.

**Comment by fourpastmidnight** [comment]
OK, so I painstakingly re-enabled all the extensions, one-by-one, reloading VS Code after each. I did this in the "regular" VS Code instance (i.e. not Insiders) because a) it exhibited the same issue as the Insiders instance and b) it had about 2/3 less the number of extensions. 😉 

I did this today because a) My computer BSOD'd anyway, so today was "update day" and b) after having 0 bytes diskpace this morning and my computer BSODing, I had 44GB free (amazing how that happens), but still, opening VS Code today (which still had all extensions enabled), the settings were being blown out.

Anyway, nothing caused the settings to be blown out after re-enabling all the extensions. Unfortunately, not a true test, because I did find some extensions that contained duplicate functionality and decided to get rid of the less "popular" extension--so perhaps I removed the very extension causing the issue.

I still need to go through this exercise again on my Insiders instance. So, I'll report back again once I have done that.

**Comment by fourpastmidnight** [comment]
OK, so, for a day or two, things were good. All my extensions were enabled and my settings were sticking around. I managed to free up 70GBs of HDD space, so right now, that's not an issue. But just today, after getting the latest Insiders update, once again the Settings are getting wiped out on _every open_ of VS Code Insiders. The console logs are a mess, and I can't make heads/tails of what is writing to the settings file and blowing it out.

Honestly, I think more control is needed with respect to access of user's settings--i.e. to provide better logging and instrumentation so when things go wrong, it's immediately noticeable who did what and when to the settings file.

**Comment by fourpastmidnight** [comment]
Each time this happened today, the closest extension error I could find in the Console was `skacekachna.win-opacity`([VS Marketplace](https://marketplace.visualstudio.com/items?itemName=skacekachna.win-opacity), [GitHub](https://github.com/SkaceKamen/vscode-win-opacity)). I can't definitively say that this extension is causing the problem because nothing in the console indicated that this extension attempted to write to the file. However, after disabling the extension, the settings stopped getting truncated. I'll post back if settings happen to get truncated again.

**Comment by fourpastmidnight** [comment]
OK, so I changed the access to my settings file so that under my normal credentials (i.e. non-elevated), I am not able to write to the file. Sure enough, an alert popped up in VS Code that it was unable to write to the settings file. Good!

Looked in the Developer Tools Console. I can see the error, but there is not enough information to know _what_ is writing to the file.

Here's a portion of the console output just before and after the attempted write:

```log
[Extension Host] Event[file] 1 - c:\src\git\...\.git (at SolutionExplorerFileWatcher.raiseEvent (C:\Users\...\.vsi-ext\fernandoescolar.vscode-solution-explorer-0.3.1\out\SolutionExplorerFileWatcher.js:32:17))
extensionService.ts:800 Activating extension 'evilz.vscode-reveal' failed: Cannot read property 'server' of undefined.
t._logMessageInConsole @ extensionService.ts:800
console.ts:134 [Extension Host] Activating extension 'evilz.vscode-reveal' failed: Cannot read property 'server' of undefined. (at Object.showMessage (c:\Users\...\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:735:501))
t.log @ console.ts:134
console.ts:134 [Extension Host] Activating extension `evilz.vscode-reveal` failed:  Cannot read property 'server' of undefined (at c:\Users\...\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:331:101)
t.log @ console.ts:134
console.ts:134 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'server' of undefined
    at StatusBarController.updateAddress (C:\Users\...\.vsi-ext\evilz.vscode-reveal-2.0.3\out\src\StatusBarController.js:24:21)
    at StatusBarController.update (C:\Users\...\.vsi-ext\evilz.vscode-reveal-2.0.3\out\src\StatusBarController.js:11:14)
    at activate (C:\Users\...\.vsi-ext\evilz.vscode-reveal-2.0.3\out\src\extension.js:27:25)
    at Function.t._callActivateOptional (c:\Users\...\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:354)
    at Function.t._callActivate (c:\Users\...\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:25)
    at c:\Users\...\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:206 (at c:\Users\...\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:331:183)
log.ts:173   ERR doSave(1) - exit - resulted in a save error: Error: Permission denied writing to file (file:///c:/Users/.../AppData/Roaming/Code - Insiders/User/settings.json) tauthority: ""fragment: ""fsPath: (...)path: "/C:/Users/.../AppData/Roaming/Code - Insiders/User/settings.json"query: ""scheme: "file"_formatted: "file:///c%3A/Users/.../AppData/Roaming/Code%20-%20Insiders/User/settings.json"_fsPath: "c:\Users\...\AppData\Roaming\Code - Insiders\User\settings.json"__proto__: e
notificationsAlerts.ts:40 Failed to save 'settings.json': Insufficient permissions. Select 'Retry as Admin' to retry as administrator.
t.onDidNotificationChange @ notificationsAlerts.ts:40
console.ts:134 [Extension Host] Event[file] 1 - c:\src\git\...\.git (at SolutionExplorerFileWatcher.raiseEvent (C:\Users\...\.vsi-ext\fernandoescolar.vscode-solution-explorer-0.3.1\out\SolutionExplorerFileWatcher.js:32:17))
```

I see several mentions of `fernandoescolar.vscode-solution-exporer`. I'll try disabling that.

**Comment by fourpastmidnight** [comment]
One more thing to note, in addition to normal user settings getting wiped out, apparently other settings are getting wiped out, too. Like, previously disabled extensions, and last open documents/windows. I got errors in the console for an extension I was pretty sure I disabled--and then another one which I _know_ I disabled. They were both re-enabled. So something is really screwing with all the various metadata files that VS Code uses.

**Comment by fourpastmidnight** [comment]
OK, I have an extension installed called `Task Runner` (`sanaajani.taskrunnercode`). It's a great extension in terms of it's usefulness, listing in an explorer pane the tasks in your `tasks.json` file, allowing you to single click a task to activate it. However, now that I've made my `settings.json` file read-only to myself, as soon as I clicked on a task, it attempted to write to the `settings.json` file. Why? So, this is a leading candidate now, too.

Perhaps there are many extensions which attempt to write to the `settings.json` file. Again, I ask why? I could see extensions such as `Settyngs Sync` would need to do this, but a task runner extension? Or a (possibly) Solution Explorer extension?

**Comment by fourpastmidnight** [comment]
OK, it _may_ be these extensions are merely attempting to open the file to read it, but in opening the file, they're also requesting read/_write_ access--and I've blocked my account from being able to write the file in an attempt to 1) not have it get blown away; and 2) find the culprit. So, I don't know what to say other than what I've already said: better instrumentation around who's doing what, when, with the settings.json file, ideally in the console so it's clearly identifiable (and auditable) about who is making what changes to that file. Perhaps this "audit tracing" should be put behind a command line option to keep the verbosity down?

**Comment by sandy081** [comment]
@fourpastmidnight I appreciated your time and effort. Extensions also own some settings and they would like to update them. But you have to check with them why they are updating without you triggering any action.
