### ISSUE TITLE
vscode to mimic IDEA Webstorm or IntelliJ

### ISSUE THREAD

**Issue by asura1990** [Microsoft/vscode#67160]
Hi,

Is there a way to have vscode to mimic behaviour of Intellij / webstorm ?

What I mean is suggestions for method completion etc, when I press "." suggestions for javascript methods are not available, I've installed extensions - method suggestions for React are available but not native Javascript.

Here's an example - screenshot of vscode.
![screenshot from 2019-01-26 17-28-36](https://user-images.githubusercontent.com/7633562/51790658-3f266980-2190-11e9-8910-90ab057d56db.png)

screenshot of intellij.
![screenshot from 2019-01-26 17-28-15](https://user-images.githubusercontent.com/7633562/51790662-49e0fe80-2190-11e9-8544-8bb8f679661f.png)

**Comment by mjbvz** [comment]
In your example, none of those suggestions are helpful IMO. We provide intellisense for known properties (but not properties like `toString` that exist on every object) or show suggestions for other words in the file

**Comment by asura1990** [comment]
What sort of example should I provide then? I mean whenever I use a the dot notation to see which method exists, vscode provides me with none, it's not just toString that doesn't exist - any methods for Objects doesn't exist. Methods for other types such as Arrays, Dates,String, Sets etc all exists.

**Comment by asura1990** [comment]
I've created a object with property in it.

![screenshot from 2019-01-28 17-30-47](https://user-images.githubusercontent.com/7633562/51854452-bbe94d00-2322-11e9-9039-1d899efc50de.png)

As you've shown and as I've mentioned before methods for other types, however when creating an object via the constructor methods are available.
![screenshot from 2019-01-28 17-34-24](https://user-images.githubusercontent.com/7633562/51854613-184c6c80-2323-11e9-893f-6546ad6e0146.png)

**Comment by mjbvz** [comment]
Yes, for an object literal the properties from the `Object` prototype just add noise to the suggestions. You can use these properties safely and we provide hover info for them but we consciously do not suggest them because they would show up in almost every suggestion list and it is relatively rate to actually use any these properties

**Comment by asura1990** [comment]
OK cool thanks!
