### ISSUE TITLE
Syntax highlighting failure on C++ UDL with '

### ISSUE THREAD

**Issue by mpusz** [Microsoft/vscode#67161]
Issue Type: <b>Bug</b>

If UDL uses ' signs to separate parts of the number like here:
  static_assert(3.2_GHz == 3'200'000'000_Hz);
than the code highlighting is lost until the end of the file.

You can find the exact code here:
https://github.com/mpusz/units/blob/master/test/test_units.cpp

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.38GB (5.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.28
autoconf|mae|0.0.7
python|ms-|2018.12.1
cpptools|ms-|0.21.0
vsliveshare|ms-|0.3.1136
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.5
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by DrPizza** [comment]
This is very debilitating, as a number of my source files are substantially string coloured.

**Comment by sean-mcmanus** [comment]
The root cause is being tracked at https://github.com/atom/language-c/issues/127 . Can you upvote that? If https://github.com/Microsoft/vscode/issues/68392 is fixed then maybe we could get a fix that way.

**Comment by sean-mcmanus** [comment]
FYI, the "Better C++ Syntax" extension just added support for this. If you could try out that extensions and let the author know if you find any issues with it that would be great.

**Comment by alexr00** [comment]
We've switched to a different grammar for C++ and it looks like it fixed this issue! @jeff-hykin thanks for fixing this.
