### ISSUE TITLE
Opening csv files from a cloud drive

### ISSUE THREAD

**Issue by gehrenfeld** [Microsoft/vscode#67163]
Using VS Code to write python files.
I use pandas to import CSV files
`
    import pandas as pd
    df = pd.read_table('summary.csv', skiprows=3, header=None, names=['id', 'rdate', 'rtype', 'hist', 'scan'], 
    usecols=[0, 1, 2, 3, 4])
`
When I run the above on my PC c: drive I can access summary.csv and the script run

I copied the python file and summary.csv to my google drive and tried to run it I get this error:

no such file b'summary.csv

When I run the same file using PyCharm it works.

Thanks

**Comment by sbatten** [comment]
@gehrenfeld If you are running this file using the python extension, please file an issue with that extension. If you are running this file from the integrated terminal, the issue likely has to do with your environment and not VS Code. 

Python extension:
https://github.com/Microsoft/vscode-python

**Comment by gehrenfeld** [comment]
That would be a no on both counts and why did you close this before knowing what the answer was going to be.
1. It works with PyCharm.
2. Is Pandas an extension?
3. Why does it work on a local drive and not a cloud drive?
4. I looked at the link and no idea what I am supposed to look at there.

Thank you

**Comment by gehrenfeld** [comment]
Thank you for your reply, but I have decided to use PyCharm which works with the cloud drive.
You can go ahead and close this ticket.
