### ISSUE TITLE
regex (?<=) is not supported

### ISSUE THREAD

**Issue by heqyoufree** [Microsoft/vscode#67167]
Issue Type: <b>Bug</b>

i can't use (?<=) in vscode and found no results
example :
(?<=isFinished\(\)) // RVA can't match "// RVA" in "public bool isFinished() // RVA"

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.18317

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) X4 760K Quad Core Processor      (4 x 3791)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.70GB free)|
|Process Argv|D:\Downloads\Compressed\Il2CppDumper-v3.5.0\dump_x86.cs|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-json|and|1.4.2
vscode-standardjs|che|1.2.3
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.23.0
githistory|don|0.4.4
vsc-material-theme|Equ|2.6.3
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
url-encode|fle|1.1.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.6
beautify|Hoo|1.4.7
phpcs|ika|1.0.5
python|ms-|2018.12.1
csharp|ms-|1.17.1
material-icon-theme|PKi|3.6.2
java|red|0.37.0
html-preview-vscode|tht|0.2.5
pdf|tom|0.4.3

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
You can enable this setting to use features like that: `search.usePCRE2`
