### ISSUE TITLE
JSON edit doesn't honour indent style

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6716]
#6657

* have settings.json indented with spaces
* run the File Association action
* the new portion is formatted using tabs

<img width="300" alt="screen shot 2016-05-24 at 10 15 53" src="https://cloud.githubusercontent.com/assets/1794099/15497004/ac6221ec-2198-11e6-9c80-c84c186c444e.png">

**Comment by aeschli** [comment]
Should have taken 'insertSpaces' and 'tabSize' from model.

We removed the feature that 'Configure File Association' adds a settings string due to the unresolved issues with the configuration open in a dirty editor.
