### ISSUE TITLE
createFileSystemWatcher potentially not working properly in Windows?

### ISSUE THREAD

**Issue by njpanderson** [Microsoft/vscode#67172]
Issue Type: <b>Bug</b>

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

I've created the following code:

```
function _watcherChangeApplied() {
	console.log('_watcherChangeApplied');
}

// initialisation code...
let watcher = vscode.workspace.createFileSystemWatcher(
	new vscode.RelativePattern(
		vscode.workspace.getWorkspaceFolder(
			vscode.window.activeTextEditor.document.uri
		),
		'**/*'
	),
	false,
	false,
	false
);

watcher.onDidChange(_watcherChangeApplied);
watcher.onDidCreate(_watcherChangeApplied);
```

Yet while the watcher works perfectly on Mac OS, it seems to never trigger in Windows (Latest 10, Edge VM from MS).

I've created a standalone test case for this here:
https://github.com/njpanderson/fswatcher-test

I would *love* for someone to tell me I'm just doing it wrong here but I've tried quite a few different glob patterns, instantiation patterns and fiddling with the first argument (`RelativePattern` vs `Uri` vs `string` etc) — nothing seems to stick.

I realise this is a borderline bug/question but as there appeared to be so little activity surrounding createFileSystemWatcher on stackoverflow I thought it best to eliminate the possibility of it being buggy first.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (2.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cdnjs|Jak|0.14.3
project-manager|ale|10.3.0
vagrant|bbe|0.5.0
vscode-intelephense-client|bme|0.8.8
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
applescript|idl|0.14.2
classic-asp|ili|0.0.4
theme-karyfoundation-themes|kar|18.2.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
debugger-for-chrome|msj|4.11.1
push|njp|0.6.1
block-travel|sas|0.0.2
twig-for-craft-2|sel|0.5.0
vscode-fileutils|sle|2.13.5
vs-code-node-require|tgr|1.2.11
vcl|tho|0.1.2
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2

(1 theme extensions excluded)

</details>

**Comment by njpanderson** [comment]
Thought I'd also add details of the VM/Code in which the issue is occuring:

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (2 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by bpasero** [comment]
@njpanderson I cannot reproduce on Windows where I just created the following extension (from the generator):

```ts
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "test-ts" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.showInformationMessage('Hello World!');

        function _watcherChangeApplied() {
            console.log('_watcherChangeApplied');
        }

        const uri = vscode.window.activeTextEditor!.document.uri;

        console.log(vscode.workspace.getWorkspaceFolder(uri))

        // initialisation code...
        let watcher = vscode.workspace.createFileSystemWatcher(
            new vscode.RelativePattern(
                vscode.workspace.getWorkspaceFolder(uri)!,
                '**/*'
            ),
            false,
            false,
            false
        );

        watcher.onDidChange(_watcherChangeApplied);
        watcher.onDidCreate(_watcherChangeApplied);
    });

    context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

Then I opened a file of a folder, started the extension and typed into the file. Upon saving I got the output.

Anything you do differently?

**Comment by njpanderson** [comment]
Ok - I've had to create a new TS extension with the above code although I used `yo` (as you probably have as well).

On testing the extension, I got a message in the host environment saying "The terminal process exited with code: 1" — not sure if that's an issue or not as I'm not too experienced with typescript.

The extension did load however, and the "hello world" command was made available (although I had to adjust the default command in `package.json` to match your registration above). On loading a file and using the command a console log of the object (`console.log(vscode.workspace.getWorkspaceFolder(uri))`) did appear, but when I saved the file, nothing further happened. I.e. `_watcherChangeApplied` did not appear to fire.

i'm not sure if there is a great deal of difference between the code I've written and yours, so I can only assume something else is going on in either my vscode environment — which is pretty default as I _only_ use it for testing my extension — or within windows itself.

Any ideas? Happy to provide any VM/env information you might need as this is preventing me from releasing an update to an extension as it's currently failing the last few integration tests.

**Comment by njpanderson** [comment]
Tried with this build:

```Version: 1.31.0-insider (user setup)
Commit: acc7365e41f9cb380e79bf78d7d102184f1ffe0d
Date: 2019-01-29T06:20:23.551Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134```

Still no luck I'm afraid — either with my extension or yours, on editing a file within or outside of code.

Both tests ran the binding function no bother, but no events would fire.

**Comment by bpasero** [comment]
@njpanderson I cannot reproduce with your sample extension. Last idea I have is to check if there is any suspicious output, e.g. try by running with `--verbose` flag and check dev tools for output.

**Comment by njpanderson** [comment]
Not sure which dev tools you mean here but I assume you meant the console? Either way, here's the output from my test — mac on the left, windows on the right. 

You can see the result of me activating the watcher (Extension Host ... `{baseFolder...` `{_onDidCreate...`), and then the result of me saving a file (`[CHANGED]...`). The difference being that the change event doesn't seem to occur in windows at all.

<img width="1169" alt="screenshot 2019-01-30 at 19 06 08" src="https://user-images.githubusercontent.com/12379690/52005829-8e3b0a00-24c2-11e9-8530-1bb852369262.png">

Interestingly there is an earlier error in the windows version regarding the `.vscode` file. Not sure if that might have something to do with anything?

**Comment by bpasero** [comment]
@njpanderson do file events in general work for you on windows? E.g. watch the file explorer update when you change something outside VSCode?

**Comment by njpanderson** [comment]
Ok I think I've figured this out @bpasero — it seems to be caused when code opens a folder on a mapped drive. Whether or not this is specifically within vbox or _any_ kind of mapped drive I'm not sure, but either way, bringing the test folder into the vm as a local folder seemed to resolve all of the problems.

To answer your last question: No, it didn't appear to be able to watch the files when the workspace pointed to a mapped drive location.
