### ISSUE TITLE
Feature request: One installer (or two) to rule them all

### ISSUE THREAD

**Issue by skycommand** [Microsoft/vscode#67173]
Right now, Visual Studio Code for Windows is available in six different packages: There are per-machine, per-user and raw portable packages for both IA-32 and x64. Packages made for the same CPU architecture have a lot of files in common.

But why six? If I am not mistaken, Inno Setup has been used to create setup packages. Therefore, it is possible to reduce the number of packages to just two: IA-32 and x64. The unified installer can install either of the three configurations depending on the user's choice.

With a unified installer, the configuration choice has to be made at installation time instead of download time. The package can be re-used regardless of the deployment scenario. And there is no risk of the user downloading the wrong package (because there are no "wrong" packages).

I am aware that in the past, there have been other feature requests with partial similarity to this. However, in each of those requests, unifying the installer has been a secondary concern.

**Comment by joaomoreno** [comment]
We gave it a try and it was impossible at the time. There have been Inno Setup developments since then but unfortunately we have other priorities at the moment. Closing this since it's not in our near future plans.

**Comment by joaomoreno** [comment]
It was hard to produce a setup that combined user+system, details in http://news.jrsoftware.org/news/innosetup/msg104628.html Like I said, I know there have been improvements, but we're just focused on other areas right now.

Would not be open to this since enabling this for the OSS build would be 20% of the work, there would have to be much more engineering and process work for the actual product to come out the doors.

**Comment by skycommand** [comment]
Well, the way I see it, you have a lot of options to do it with Inno Setup, and you have a lot of other options. Martijn Laan and Gavin Lambert were eager to help too. I even offered to do it for you.

But it all comes down to this: You don't want to; reason unknown.

Fine. I make myself scarce. Bye-bye.

**Comment by joaomoreno** [comment]
> reason unknown

Not unknown at all, just busy. You can check our [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) as well as our [iteration plans](https://github.com/Microsoft/vscode/wiki/Iteration-Plans) to see what we're up to.

I don't want to seem ungrateful, it's great that you come with ideas for improvement and offer to help even. But at the end of the day, time is a scarce resource and we simply can't do it all.
