### ISSUE TITLE
Duplicating lines or Selection with Shortcut key Feature

### ISSUE THREAD

**Issue by AgentPerfect10** [Microsoft/vscode#67179]
OS: Window 7
Version: 1.30.2
                                     **User Demand**
I can't find any duplicating feature in it. Except Copy and Paste there should be a duplicating lines or selection like sublime text,Brackets,etc. Hope you understand.
**User Demand**

**Comment by Mlocik97-issues** [comment]
it's already is... you only need to read manual. ;-)
