### ISSUE TITLE
changing file association doesn't reflect in open editor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6718]
#6657

* open a file `foo.brutalo`
* in settings.json map the `*.brutalo` ending to TypeScript
* the editor showing `foo.brutalo` didn't update its mode

<img width="701" alt="screen shot 2016-05-24 at 10 22 01" src="https://cloud.githubusercontent.com/assets/1794099/15497135/63ba7e02-2199-11e6-86de-c11457ffa100.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1097

**Comment by bpasero** [comment]
Actually fixed for September 👍
