### ISSUE TITLE
Extensions: jsonValidation json schema urls should support self-registered schemes

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#67189]
Version: 1.30.2

Extensions are currently able to declare schemas for json files using the [jsonValidation](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation) contribution point.  The `url` property can point to an http or https url, or a static local resource.  This works for simple, static scenarios.

However, it would be nice if the `url` could also point to a scheme registered by the extension as providing text content, so the schema could be generated (locally) dynamically.  e.g. allow urls of the form `custom:/path/to/file.json` where `custom` is a scheme declared in the same extension's package.json.

**Comment by aeschli** [comment]
That already works, and is what we do for schemas of our configuration points.
e.g. see https://github.com/Microsoft/vscode/blob/33783baaa19ba89e30cf72469ba2086243997f51/extensions/configuration-editing/package.json#L45
the vscode:// resources come from a document content provider

use `workspace.registerTextDocumentContentProvider` to register a document content provider.

The document that is returned then ca contain the schema content, and can fire a document change event if the schema changes.

(for vscode the document content provider is registered with different APIs in the renderer, but it's basically the same)

**Comment by johnspurlock** [comment]
Can you please make sure vscode:// doesn't use a special code path?

Custom schemes do not work for me in 1.30.2.  The provider is never called.  I tried uris with and without an authority (e.g. `custom:foo` and `custom://authority/foo`) with no luck.  Changing the `url` back to a local resource works.

**Comment by johnspurlock** [comment]
Can you please re-check this?  It is still not working in Version 1.31.0.

**Comment by aeschli** [comment]
You are correct, I realised like the JSON language server only forwards the `vscode` protocol.

**Comment by johnspurlock** [comment]
Seems to be working in Version: 1.32.0-insider
Commit: 11416de365a1e96302e171c9eebc2547872ac230
Date: 2019-02-23T08:16:36.706Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Thanks!

**Comment by aeschli** [comment]
Thanks for verifying!
