### ISSUE TITLE
Find all references tree selection changes when expanding new element

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67188]
- Open find all references
- Expand a file that hasn't been expanded before
- Focus of that item is lost

![jan-27-2019 12-14-33](https://user-images.githubusercontent.com/323878/51806294-2c15a700-222d-11e9-90b0-6a91fce06fd1.gif)

**Comment by jrieken** [comment]
@joaomoreno I didn't change a thing...

**Comment by joaomoreno** [comment]
Yeah, I can take this!
