### ISSUE TITLE
Add TextDocumentSaveReason to did-save event

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#67190]
Currently `TextDocumentSaveReason` only seems to be available in `TextDocumentWillSaveEvent` but it would be useful in did-save too. In Dart we have a feature to fetch packages when you modify `pubspec.yaml`, but if you have auto-save then it fires quite a lot. It'd be better if we could run it immediately if it was a manual save, but delay/debounce it for auto-saves.

**Comment by jrieken** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/5305
