### ISSUE TITLE
Some keybindings do not work when autocomplete is triggered

### ISSUE THREAD

**Issue by goofle** [Microsoft/vscode#67192]
I have some keybindings for cursor navigation like below:

```
    {
        "key": "alt+i",
        "command": "cursorUp",
        "when": "editorTextFocus"
    },
    {
        "key": "alt+k",
        "command": "cursorDown",
        "when": "editorTextFocus"
    },
```

When autocomplete is triggered, I like to press `alt+i/alt+k` to move the "select" to up/down inside the suggestion pane. But instead, pressing `alt+i/alt+k` closes the suggestion pane, and moves the cursor away from the place which triggered the autocomplete.
If I wanted this to happen, I'd press `esc`  to close the suggestion pane first, before navigating the cursor, right?

**Comment by usernamehw** [comment]
You are using the wrong commands `selectNextSuggestion` `selectPrevSuggestion`

**Comment by goofle** [comment]
@usernamehw Do you know what should I use for `when` context so I'll be able to use the same `alt+i/alt+k` for those commands?

**Comment by usernamehw** [comment]
* Open keybindings GUI https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor
* Search for command ids from my previous comment

You can copy the command from context menu and get a complete `when` from it.

**Comment by goofle** [comment]
Thanks for the hint!
I did it like: 
```
    {
        "key": "alt+i",
        "command": "selectPrevSuggestion",
        "when": "suggestWidgetVisible"
    },
    {
        "key": "alt+k",
        "command": "selectNextSuggestion",
        "when": "suggestWidgetVisible"
    },
```

**Comment by usernamehw** [comment]
/question

Will close this then.
