### ISSUE TITLE
Bug on Mutiple Select

### ISSUE THREAD

**Issue by Sunnysit** [microsoft/vscode#67195]
Issue Type: <b>Bug</b>

I use the Chinese Version VS code, there is a bug on mutiple select, when I press Alt or Cmd to select mutiple lines, it works. But after that, the bug happen, all other funsctions break down and I have to  restart vs code to make it work again.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
path-intellisense|chr|1.4.2
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.46
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.7
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.5.0
vscode-language-pack-zh-hans|MS-|1.30.2
open-html-in-browser|pea|1.0.2
LiveServer|rit|5.3.1

</details>

**Comment by rebornix** [comment]
sorry for coming back to the issue so late. Could you please provide more info about how to reproduce or if it still reproduces with latest VS Code?
