### ISSUE TITLE
Strange build behaviour building TypeScript from VSCode with Node v6 on Windows

### ISSUE THREAD

**Issue by yortus** [Microsoft/vscode#6719]
- VSCode Version: 1.1.1
- OS Version: Windows 7, Windows 10

Steps to Reproduce:

See https://github.com/yortus/repro-build-bug for full repro details and a cut-down project.

From the README:

### Problem Description

- Building a project with `Shift+Ctrl+B` puts some built files in the wrong location

### Environment

- **O/S**: Windows 7 and Windows 10
- **VSCode**: v1.1.1
- **Node.js**: v6.2
- **TypeScript**: v1.9.0-dev.20160524-1.0

##### Project setup

1. `git clone https://github.com/yortus/repro-build-bug.git`
2. `cd repro-build-bug`
3. `npm install`

##### Baseline build/run (this should work fine)

1. Open a command prompt
2. Build from the command prompt using `npm run build`
  - should be no errors, and `/built` will contain built `.js` files
3. Run from the command prompt using `node .`
  - should be no errors, outputs `"Hello, World!"` to console

##### VSCode build/run (this should repro the bug)

1. Open the project folder in VSCode
2. Delete the `/built` directory created in the previous steps
2. Build from VSCode by pressing `Shift+Ctrl+B`
  - should be no errors, but one `.js` file is output to `/built` and the other to `/src`
3. Run from the command prompt using `node .`
  - should show an error `"cannot find module..."` because of the wrong placement of built files
  
  

### Further Notes

- Bug could not be reproduced on linux
- Bug could not be reproduced with node v4 or v5.
- Bug goes away if `"options": {"cwd": "<absolute project path>"}` is added to `.vscode/tasks.json`

**Comment by yortus** [comment]
Update: Executing `npm run build` using the new integrated terminal in VSCode 1.2 also puts some built files in the wrong location. Seems to be the same odd behaviour as building from `tasks.json`.

**Comment by dbaeumer** [comment]
@yortus trying this from the command line results in the following error for me:

error TS5009: Cannot find the common subdirectory path for the input files.

Interestingly I frist tried this under node version 5.10.0 and there it worked in both command line and VS Code. 

Do you see the same error in the console ?

**Comment by dbaeumer** [comment]
The task frameworks sets cwd to the workspace folder by default if not provided. So I don't understand why setting it explicitly makes it work. Need to investigate.

**Comment by yortus** [comment]
@dbaeumer I don't get TS5009, the build runs successfully for me. I had a colleague repeat the repro steps on his machine and he has the same results as I've written up in the OP.

I don't have `tsc` installed globally, not sure if that makes a difference?

**Comment by yortus** [comment]
I've just followed the repro steps on another machine (Windows 10, Node 6.2, VSCode 1.1) and got the same results again. Repros consistently for me so far on three machines now.

**Comment by dbaeumer** [comment]
I do have tsc installed globally. Will uninstall and try again.

**Comment by dbaeumer** [comment]
Using the local installed tsc produces the same TS error for me.

````
P:\mseng\VSCode\Playgrounds\bugs\repro-build-bug>.\node_modules\.bin\tsc.cmd -p src
error TS5009: Cannot find the common subdirectory path for the input files.
```

No idea what makes the difference here.

**Comment by dbaeumer** [comment]
When I change tsconfig.json to:

```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "../built",
        "rootDir": "../src"
    }
}
```

and compile using

```
.\node_modules\.bin\tsc.cmd -p src
```

I get 

```
error TS5009: Cannot find the common subdirectory path for the input files.
error TS6059: File 'C:/Users/dirkb/Projects/mseng/VSCode/Playgrounds/bugs/repro-build-bug/src/other/thing.ts' is not under 'rootDir' 'P:/mseng/VSCode/Playgrounds/bugs/repro-build-bug/src'. 'rootDir' is expected to contain all source files.
```

**Comment by dbaeumer** [comment]
Using tsc version 1.8.10 works without any problem.

**Comment by yortus** [comment]
Yep, TS1.8 works fine for me too. I can only repro the problem with ts@next (it repros with today's nightly build for me).

I can't get a TS5009 however I try, nor would I expect a TS5009 for such a trivial project structure where the two source files clearly share the common root `src/`.

Could you try expanding out the `build` script inside `package.json` to the equivalent long form:

```
tsc --target es6 --module commonjs --outdir built src/index.ts src/other/thing.ts
```

That repros the same error for me.

**Comment by yortus** [comment]
I've just repro'd this on another different machine (Windows 7). This was a clean machine, I had to install Node, GIT and VSCode. Behaves exactly as described in OP.

Is it possible the TS5009 error you get is somehow related to the bug? The problem is path confusion after all. And clearly the two files `src/index.ts` and `src/other/thing.ts` have the common root `src/`, so the TS5009 is very strange and suspicious.

I mean, how else could you structure a two-file project, with one file nested in a subdirectory, if tsc can't work out the common root? Do you still get TS5009 on your machine if you run `tsc index.ts subdir/index.ts` in a fresh directory with those files created?

**Comment by yortus** [comment]
A clue... in `index.ts`, if I comment out the `import Thing...` and `let thing...` lines, both built files are correctly placed under `../built`.

**Comment by Seikho** [comment]
This may be an issue in TypeScript instead. I've tracked the issue down to https://github.com/Microsoft/TypeScript/commit/cd1af127aa2088fa01917d0044e960ef6c02b542

**Comment by yortus** [comment]
I think @Seikho is onto something in [this comment](https://github.com/Microsoft/TypeScript/issues/8837#issuecomment-224797213).

If I add `"options": {"cwd": "V:/temp/repro-build-bug"}` to my `tasks.json` (that's my project directory), the problem goes away and the build works normally. But if I lower-case the drive letter (so, `"options": {"cwd": "v:/temp/repro-build-bug"}`), then the build bug reoccurs.

**Comment by yortus** [comment]
@dbaeumer are you using symlinks? The commit referenced by @Seikho affects symlink behaviour, and you reported getting an error like:
```
error TS6059: File 'C:/.../src/other/thing.ts' is not under 'rootDir' 'P:/.../src'. 'rootDir' is expected to contain all source files.
```
...which looks like a symlink expanded in one place but not in another.

**Comment by dbaeumer** [comment]
@yortus @Seikho very good insights. 

I am not using symlinks. I use subst to create a new drive letter that points into my C-Drive. E.g. P:\ => 'C:/Users/dirkb/Projects. I should have spotted that in the error message as well.

Regarding setting the cwd as pointed out in comment https://github.com/Microsoft/vscode/issues/6719#issuecomment-224800465: VS Code by default sets the cwd to the workspace folder. However we set the cwd with a lower case drive letter.

**Comment by dbaeumer** [comment]
On top of that there seems to be issue with drive letter in node 6.x: See https://github.com/nodejs/node/issues/6624.

@yortus @Seikho any objection to close this issue. IMO there is little VS Code can do here. The fix should be on TS side to deal correctly with drive letter casing. We internally consistently make it lower case when normalizing paths.

**Comment by yortus** [comment]
@dbaeumer agreed - will follow up in [Microsoft/TypeScript#8837](https://github.com/Microsoft/TypeScript/issues/8837).

**Comment by Seikho** [comment]
I was just writing a post that came to the same conclusion. Thanks @dbaeumer

**Comment by dbaeumer** [comment]
Closing in favour of Microsoft/TypeScript#8837
