### ISSUE TITLE
Debugging C# code with Debug window open results in  unresponsive window

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#67197]
Issue Type: <b>Bug</b>

Running a C# (ASP.Net core application) with the Debug window open / showing, results in an unresponsive VS Code window. The "This window is unresponsive, do you wish to close?" prompt shows. Also, the process is using 100% CPU. Running the application, but making sure the Debug window is not showing (either the panel is closed or another tab is showing - Terminal, etc.) and the application runs fine.

VS Code version: Code - Insiders 1.31.0-insider (9fe48f15b1a252a0e9e1ef5975301203baf10b8a, 2019-01-25T08:11:48.342Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
githistory|don|0.4.4
auto-rename-tag|for|0.0.15
Angular2|joh|7.0.1
csharp|ms-|1.18.0-beta4
vscode-typescript-tslint-plugin|ms-|0.4.0
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.2
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.2

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
I'm not so sure this is caused by an extension. I have been using the extensions listed for a few weeks, the only thing that changed was updating to the latest Insiders VSCode.

**Comment by jtsom** [comment]
Also may not be due to the C# extension - reference: https://github.com/Microsoft/vscode/issues/67222

**Comment by weinand** [comment]
@joaomoreno please see this one too.

**Comment by jtsom** [comment]
It does output a fair amount of text (the usual output for an ASP Dotnet Core application)

**Comment by joaomoreno** [comment]
Excellent, definitely a dupe of #65213, comes out tomorrow in Insiders. Let me know if you keep getting the issue by then.

**Comment by jtsom** [comment]
Thanks! I will check it out and let you know.
