### ISSUE TITLE
VS Code fails to launch on Ubuntu

### ISSUE THREAD

**Issue by sursu** [Microsoft/vscode#67193]
I've installed the latest version of VS Code available from the Snap Store:

- VSCode Version: 1.30.2-1546901646
- OS Version: Ubuntu 18.04

After installation has completed I have tried to launch the application. It did not launch.

`code --verbose` spits out:
```
[main 11:15:30 PM] Error: EACCES: permission denied, mkdir '/home/ursus/.config/Code/logs/20190127T231530'
[main 11:15:30 PM] Lifecycle#kill()
```
I am reluctant to start vscode as a super user. The more so, as previously I did not have to use `sudo` to start the application, and also because the Details field in the says: "This application is unconfined. It can access all personal files and system resources."

**Comment by joaomoreno** [comment]
What are the permissions of the following folders?

```
/home/ursus/.config
/home/ursus/.config/Code
/home/ursus/.config/Code/logs
```

**Comment by sursu** [comment]
In the requested order:
```
drwx------
drwxr-xr-x
drwxr-xr-x
```

**Comment by joaomoreno** [comment]
Which user is the owner?

**Comment by sursu** [comment]
`ursus` is the owner. There are no other users on this machine.

**Comment by joaomoreno** [comment]
`ursus` is the owner of all those tree folders? If you home folder in some special network share?

**Comment by sursu** [comment]
`ursus` is the owner of `/home/ursus/.config`
`root` - owner of `/home/ursus/.config/Code`
`root` - owner of `/home/ursus/.config/Code/logs`

**Comment by joaomoreno** [comment]
Right, there's your problem. Did you execute Code as root the very first time you started it?

**Comment by sursu** [comment]
`sudo code` tells me:
```
You are trying to start vscode as a super user which is not recommended. If you really want 
to, you must specify an alternate user data directory using the --user-data-dir argument.
```

That coupled with the error which comes with `sudo snap install vscode` (below) raises some questions.

```
error: This revision of snap "vscode" was published using classic confinement
       and thus may perform arbitrary system changes outside of the security
       sandbox that snaps are usually confined to, which may put your system at
       risk.

       If you understand and want to proceed repeat the command including
       --classic.
```

**Comment by joaomoreno** [comment]
@sursu When you first ran Code, did you run it as `sudo code`? If so, did Code come up at all?

**Comment by sursu** [comment]
I installed vscode. 
I tried to start it with `code`. Did not launch. 
I ran `code --verbose` got the message I described.
I tried `sudo code`. Got the warning from the previous message: `You are trying to start ...`
Since my last installation I have not managed to open VS Code.

**Comment by joaomoreno** [comment]
> Did not launch.

No output at all at the time?

This is pretty strange. Can you try to delete the `~/.config/Code` folder and retry running `code` again?

**Comment by sursu** [comment]
No output at all at the time.

After `~/.config/Code` I was able to open vscode.

Thank you!

**Comment by joaomoreno** [comment]
Not really sure. Closing this for now.

**Comment by msarahan** [comment]
We have closed this issue at Anaconda because we believe the "original sin" if you will, was using sudo to install Anaconda.  Doing so should absolutely be expected to create files with root permissions.  Removal of dotfiles is the user's responsibility.  We provide a utility that may assist with that, anaconda-clean (https://github.com/ContinuumIO/anaconda-clean), but that hasn't been updated recently and definitely doesn't support VS Code.
