### ISSUE TITLE
Add isRunning for keybinding when-context

### ISSUE THREAD

**Issue by jtakalai** [Microsoft/vscode#67207]
Went through "keybinding when-context is:issue is:open", not found

Let's say I want to both Pause and Continue by pressing F8, like in Chrome Web-developer Tools. I can add either and set when-context to "isDebugMode", but I can't have both (I think?), since Pause would be used when the program is running and Continue when it's paused. So there could be a "isRunning" when-context for when the program is running in debug mode, so the "isDebugMode && !isRunning" would be when the program execution is broken and the program is being examined in debugger.

It could be also be inverse and called "isPaused" or "isDebugging" or "inDebugger" or "pausedInDebugger" or something like that.

**Comment by isidorn** [comment]
Try this context key `debugState`
It has the following values: `inactive`, `initializing`, `stopped` and `running`

**Comment by jtakalai** [comment]
thanks for the tip!
