### ISSUE TITLE
Coderunner ignoring selected python version

### ISSUE THREAD

**Issue by djhyman** [Microsoft/vscode#67205]
Issue Type: <b>Bug</b>

Coderunner is ignoring the Python version set in json. The json file is set to the following: python.pythonPath": "/usr/local/bin/python3", but it still runs all .py files in Python 2.7. This is on macOS High Sierra

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.6
python|ms-|2018.12.1
Go|ms-|0.8.0

</details>

**Comment by sbatten** [comment]
please file your issue with the extension https://github.com/formulahendry/vscode-code-runner
