### ISSUE TITLE
Case insensitive file name bug

### ISSUE THREAD

**Issue by crissy25** [Microsoft/vscode#67208]
Hello,

Issue 1
1. File name saved was UserFeedbackModel.js
2. Imported it as UserFeedBackModel (B is capital)
3. File was imported nonetheless

Expectation:
File shouldn't have got imported

Issue 2
1. Changed filename from UserFeedbackModel to UserFeedBackModel (B is capital)
2. This change didn't reflect in Source control
3. Said there was nothing to commit

Expectation:
File name change should have showed in Source Control and should've been able to commit this change

Thanks!

**Comment by dbaeumer** [comment]
@crissy25 for the import case please file a bug against the Typescript project here: https://github.com/Microsoft/TypeScript

Moving to @joaomoreno to comment on the Git problem.

**Comment by joaomoreno** [comment]
This is how Git works. Try changing the case of a file which is in a Git repo and running `git status`. It will not report a change.

https://stackoverflow.com/a/47832160
