### ISSUE TITLE
Allow to use `resourceLangId` configuration for in-memory files

### ISSUE THREAD

**Issue by zhaoyi0113** [microsoft/vscode#67203]
- VSCode Version: 1.30.2
- OS Version: Mac 10.14.2

Steps to Reproduce:
I am working on a vscode extension but found an issue with `resourceLangId`. Below is my configuration. It tries to render a title on editor when it open a file which has language id as `mongodbRunner`.

```
"editor/title": [
        {
          "when": "resourceLangId == mongodbRunner",
          "command": "mongoRunner.launchEditor"
        }
      ]
```
It works for the file loaded from disk but it doesn't work for in-memory file. 

`vscode.workspace.openTextDocument({ content: text, language: 'mongodbRunner' });
`

The editor title is not shown until I save the file on disk.

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by jrieken** [comment]
When you open that untitled files what language is detected? E.g. what does the editor show in the lower right corner?

**Comment by zhaoyi0113** [comment]
It is shown as `mongodbRunner` in the lower right corner.

**Comment by jrieken** [comment]
Assigning to @bpasero because it seems that we don't have a "good" filename yet that allows to retrieve the lang id.
