### ISSUE TITLE
Task runner can't run npm build using wsl.exe

### ISSUE THREAD

**Issue by aaronadamsTO** [Microsoft/vscode#67202]
On Windows 10, with my default shell set to WSL Bash (`"C:\WINDOWS\System32\wsl.exe"`), I can execute `npm run build` in the terminal without error; but when I try Run Build Task in VS Code (Ctrl+Shift+B), it fails.

Error output:

```
> Executing task: npm run build <

/bin/bash: /d: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

It looks like the problem is probably that Windows-style `/d` argument being passed to a shell script. I don't know where it's coming from, though.

tasks.json:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
@aaronadamsTO this is already fixed in Insiders, and should be included in the next release of VS Code.

**Comment by aaronadamsTO** [comment]
Great, thanks! Hopefully this ticket helps anyone else experiencing this issue, because I could not find a thing about it myself.
