### ISSUE TITLE
VS Code breaks `<pre>` indention when pasting, even with "Format on Paste" turned off.

### ISSUE THREAD

**Issue by garretwilson** [microsoft/vscode#67200]
VS Code 13.0.2 on Windows 10.

If I copy and paste in a section of HTML which includes `<pre>` block, VS Code converts the spaces inside the `<pre>` block to tabs!! VS code should never touch the indentation inside the `<pre>` blocks. For example:

```html
	<figure>
		<pre class="line-numbers"><code class="language-turf">*FooBar:
  length = 1234
  valid = true
  status = "processing"
  results = [false, 5, "dog", {"code" = 9.8}]
;</code></pre>
	</figure>
```

This code section has a combination of tabs and spaces for indentation. The space indentation is crucial for the preformatted `<pre>` blocks. But VS code changes them to spaces when I paste; basically my editor is corrupting my content!

What adds insult to injury is that I have `Editor: Format on Paste` _turned off_. So VC Code should paste my content _exactly as I give it_. It has no business making _any_ changes, because I have told it not to.

People can debate all day about tabs vs spaces, about how the editor should guess the indentation, what happens with mixed indentation, etc. But when turn off `Editor: Format on Paste`, it should make _no changes_. Surely no one can argue with that.

Please fix this huge bug which corrupts content.

**Comment by rebornix** [comment]
This can be turned off by setting `editor.autoIndent` to `advanced`.
