### ISSUE TITLE
Grid: cannot make sidebar/panel visible by dragging from the edge

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67209]
Steps to Reproduce:

1. hide sidebar and/or panel
2. move the mouse to where these components hide to and try to drag them out using the mouse
3. 🐛 not possible

//cc @joaomoreno

**Comment by sbatten** [comment]
panel seems to work, sidebar still having issue @joaomoreno

**Comment by joaomoreno** [comment]
@sbatten Seems to work over here, what doesn't work over there?

**Comment by sbatten** [comment]
Dragging sidebar back out

**Comment by joaomoreno** [comment]
Works OK here, from both left and right side... sure you got latest?

**Comment by sbatten** [comment]
Are you snapping them away or toggling them, then dragging them out? Also not at my machine so am not reverifying

**Comment by joaomoreno** [comment]
Both. The latest splitview changes make those two gestures the same, model-wise. Give it a try again tomorrow. :+1:

**Comment by sbatten** [comment]
seems good in todays build

**Comment by joaomoreno** [comment]
Just needed some extra proofing time.
