### ISSUE TITLE
tasks: Only strings are supported as results for commands used for variable substitution.

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#67206]
Command 'workbench.action.files.save' did not return a string result. Only strings are supported as results for commands used for variable substitution.

```json
        {
            "label": "vscSaveFile",
            "type": "process",
            "command": "${command:workbench.action.files.save}",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "problemMatcher": []
        }
```

**Comment by alexr00** [comment]
This is deliberate. A `command` can only be a string, so it makes sense to ensure that it's value is a string.

**Comment by kzhui125** [comment]
@alexr00 I want VSCode tasks run workbench.action.files.save command.
I don't care its value is a string or not.

The design is not reasonable.

**Comment by alexr00** [comment]
Potential work around: `"command": " echo saving${command:workbench.action.files.save}"`
