### ISSUE TITLE
No notification in running vscode when extension installed / uninstalled from command line

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6721]
#6099

- VSCode Version: alpha
- OS Version: OS X

Steps to Reproduce:

1. having vscode running
2. uninstall / install extension from the command line
3. try to use the uninstalled / installed extension from vscode - get an error or see that it does not appear to be installed. I would expect that I get notified that an extension got installed / uninstalled and that a reload is required (same as in the regular extension experience)

**Comment by joaomoreno** [comment]
Uh.

**Comment by joaomoreno** [comment]
This will likely not happen in the near future.
