### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by marlonvpaula** [Microsoft/vscode#67219]
Começou nessa ultima atualização o terminal está iniciando com algumas linhas para baixo.
É necessário alguns Enter para começar a trabalhar com ele.

![2019-01-28_08h27_25](https://user-images.githubusercontent.com/7363774/51830457-093fcd00-22d7-11e9-80ee-78ec0bf1d095.png)

Mas está funcionando.. apenas um detalhe.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
