### ISSUE TITLE
Debug Console ignores colors if in 8-bit/256-color format

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#67217]
The Debug Console seems to support ANSI colour codes in the 8-color format but not if specified in the 256-color format.

For example:

```
const t1 = "\x1B[32m       test   \x1B[0m";
const t2 = "\x1B[38;5;2m   test   \x1B[0m";
console.log(t1);
console.log(t2);
```

Outputs:

<img width="139" alt="screenshot 2019-01-28 at 10 01 09 am" src="https://user-images.githubusercontent.com/1078012/51828524-a7399480-22e3-11e9-9042-a503db70d208.png">

Here's how it looks from a node script:

<img width="353" alt="screenshot 2019-01-28 at 10 00 30 am" src="https://user-images.githubusercontent.com/1078012/51828490-99840f00-22e3-11e9-98e0-db110d97ca0e.png">

**Comment by isidorn** [comment]
fyi @danielfrankcom

**Comment by flurmbo** [comment]
Hi, I'm going to try working on this!

**Comment by Daniel-McCarthy** [comment]
![image](https://user-images.githubusercontent.com/4957200/52511423-7c91ea80-2bc5-11e9-8e30-d07b44c16862.png)
I'm having trouble reproducing this issue. Has this been addressed, or might there be an issue due to how I am trying?

**Comment by flurmbo** [comment]
@Daniel-McCarthy looks like you're using node in the built-in terminal. The issue is with the debug console (in the same view panel as terminal). To reproduce save the code in index.js, then press F5 and select node for the debug environment. That should display the output on the debug console

**Comment by iansan5653** [comment]
I can work on this one. I should be able to submit a PR tomorrow or this weekend.

**Comment by isidorn** [comment]
@iansan5653 cool. I see that you are looking into multiple issues. However if they are independent I always prefer smaller multiple PRs than 1 large one. However if the 1 PR is pretty straighforward feel free to go ahead with that approach. Thanks

**Comment by iansan5653** [comment]
Yeah I plan to resolve several issues but I can submit an individual PR for each.

**Comment by iansan5653** [comment]
Still working on it. Just have a couple unit tests to resolve and I'll submit the PR.
