### ISSUE TITLE
Please add Line wrapping for Shell Script functions

### ISSUE THREAD

**Issue by xenadmin** [Microsoft/vscode#67211]
I write both Linux Bash and Windows PowerShell Scripts in Visual Studio Code. While writing Shell Scripts in Visual Studio Code I noticed that Line wrapping for functions is missing. I made a screenshot, where you can see that it is added for `IF` but not for `function`.

![grafik](https://user-images.githubusercontent.com/12057348/51822823-bae1fc80-22dd-11e9-8beb-1b8f69267235.png)

Updated Image to show that I'm missing the little [-] sign in the annotation bar. Sorry, that really wasn't clear. 
![grafik](https://user-images.githubusercontent.com/12057348/51828207-66457e00-22eb-11e9-8b40-a538ff66d0eb.png)

**Comment by dbaeumer** [comment]
@xenadmin you are talking about folding right (e.g. the little [-] sign in the annotation bar) ?

**Comment by aeschli** [comment]
Need more information...

**Comment by xenadmin** [comment]
I'm sorry, but I think it was unwise from me to add the missing information through an EDIT in my very first post. I answered the questions of @dbaeumer in my updated image in the first post. 

But to make it 100% clear: I miss the folding (the little [-] sign in the annotation bar) for the keyword `function` in vscode when the language is set to `shell script`.

**Comment by aeschli** [comment]
Ah, ok, this is about folding.

The default folding strategy for bash is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

However, we allow extensions to provide language aware folding range providers. I have just seen that for bash there's and extension called Bash IDE that has a syntax tree for bash. I suggest you file a request there: https://github.com/mads-hartmann/bash-language-server
