### ISSUE TITLE
Trusting a *selected* self-signed HTTPS cert / cert generated by local (non-internet) Root CA

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#67223]
- VSCode Version: 1.30.2
- OS Version: Win 7 x64

Steps to Reproduce:

1. Install this extension: https://github.com/kenhowardpdx/vscode-gist

2. Configure it for **Enterprise** Github with **self-signed** / **local Root CA-generated** certificate.

3. On inserting/creating a gist get error:

```
GIST ERROR: Could Not Insert > Reason: request to https://github.example.com/api/v3/gists?per_page=9999 failed, reason: unable to verify the first certificate
```

History of this problem: https://github.com/kenhowardpdx/vscode-gist/issues/83

Now, there's a workaround:

https://stackoverflow.com/questions/33820733/error-unable-to-verify-the-first-certificate-how-to-trust-all-certificates

But it's a bad solution to this problem since it obviously defeats the purpose of HTTPS in the first place...

A better solution would be accepting selected self-signed certs.

A **correct** solution would be ability to add your local Root CA certs.

**Comment by joaomoreno** [comment]
/duplicate #12588 Cert trust comes with proxy support.

**Comment by mrkafk** [comment]
I *have* set HTTPS proxy first, as described in https://github.com/kenhowardpdx/vscode-gist/issues/83 . It has not helped. Please reopen the issue.
