### ISSUE TITLE
Terminal input problems with Insiders and MINGW zsh on Windows 10

### ISSUE THREAD

**Issue by Xjs** [microsoft/vscode#67227]
Issue Type: <b>Bug</b>

Steps to reproduce:

* Install VS Code Insiders
* Install a MINGW zsh. (I have zsh 5.4.2 (x86_64-pc-msys))
* Execute zsh in VS Code's integrated terminal
* Notice keyboard input in the terminal sometimes flickering, and sometimes keystrokes getting ignored or in the wrong order

I can reproduce that the second character I type after the prompt will always flicker and the cursor will shortly jump. I will provide a video if necessary. I can't pinpoint when exactly characters are ignored, but it happens often enough to be a nuisance.

It only happens with zsh in VS Code Insiders (not the regular release) on Windows 10 (not under Linux, haven't tested macOS yet, but can do later). I can reproduce it under a fresh Windows user account with zsh reading no configuration files (zsh -f) and a fresh VS Code Insiders installation. I may be able to test it on a different Windows 10 machine later this week.

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:21:00.148Z)
OS version: Windows_NT x64 10.0.18323

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v6 @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
xml|Dot|2.4.0
gitlens|eam|9.4.1
python|ms-|2018.12.1
cpptools|ms-|0.21.0
Go|ms-|0.8.0
PowerShell|ms-|1.11.0
ruby|reb|0.21.0
java|red|0.37.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by Xjs** [comment]
NB: I think this started to happen on Thursday or Friday.

**Comment by Tyriar** [comment]
@Xjs does this reproduce if you set this?

```
"terminal.integrated.windowsEnableConpty": false
```

If not can you create an issue against https://github.com/Microsoft/console ideally with a gif that demonstrates the problem?

**Comment by Xjs** [comment]
@Tyriar Does not reproduce with `terminal.integrate.windowsEnableConpty = false`. I'll create a video and file it against Microsoft/console, any additional info I should be giving there?

**Comment by Tyriar** [comment]
Tracked in https://github.com/microsoft/terminal/issues/364
