### ISSUE TITLE
December/January 2019 Endgame

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#67225]
## Schedule Template
- End game master: @dbaeumer / Zurich
- End game body: @roblourens  / Redmond
- *01/28* Code freeze for the endgame
- *02/01* [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- *02/06* Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) @dbaeumer 
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

##### Wednesday
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A%2Aduplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+sort%3Aupdated-desc+milestone%3A%22December%2FJanuary+2019%22)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A%2Aduplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+sort%3Aupdated-desc+milestone%3A%22December%2FJanuary+2019%22)
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **owner**

##### Friday
- [x] Pause scheduled `insider` builds @dbaeumer 
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
- [x] All issues [verified](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A%2Aduplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+sort%3Aupdated-desc+milestone%3A%22December%2FJanuary+2019%22)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @dbaeumer 
  - [x] OS X - @isidorn 
  - [x] Linux - @chrmarti 
- [x] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@auchenberg**
  - [x] localization **@shawndon**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **endgame master**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **endgame master**

##### Friday/Monday
- [x] Branch code to `release/1.31 **endgame master** 
- [x] Bump up the version in package.json - **endgame master** 
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **endgame master**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [x] Build stable for all platforms as new candidate issues come in **endgame master**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [ ] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [x] Build stable for all platforms **endgame master**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@Tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit @dbaeumer 
    - [x] signed installer 64-bit @dbaeumer 
    - [x] signed user installer 32-bit @dbaeumer 
    - [x] signed user installer 64-bit @dbaeumer 
    - [x] zip 32-bit @alexr00 
    - [x] zip 64-bit @alexr00
  - [x] OS X - @weinand 
  - [x] Linux
    - [x] deb package 32-bit @joaomoreno 
    - [x] deb package 64-bit @joaomoreno
    - [x] rpm package 64-bit @joaomoreno
    - [x] rpm package 32-bit @joaomoreno
    - [x] archives @joaomoreno
- [x] Publish website **@gregvanl**
- [x] Publish Localization language pack **@shawndon**
- [x] Publish to stable **endgame master**
- [x] Add a git tag to `HEAD` of `release/1.31` in format `1.31.0` (for vscode.d.ts download)  **endgame master**
- [x] Publish rpm to repository manually **@Tyriar**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@auchenberg**

### Recovery Build

We release a recovery build with a handful of critical fixes and translation updates a few days after a release. The candidate fixes are reviewed by the development team and are assigned to the recovery milestone. We want to be restrictive about the included candidates. The mindset is "we will lose users if we do not include the fix". Here are some examples:
- data loss
- a regression that users complain loudly about in issues or twitter
- a significant performance regressions
- an issue that impacts many users as indicated by telemetry data
- an embarrassing UI glitch
- critical security fixes
- an issue that impacts extensions or is an API regression

#### Check list
- [x] Create a milestone `<Month> Recovery <year>` **owner**
- [x] Bump the version number **owner**
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Make rpm signing request **@Tyriar**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits
  - [x] Windows - **@Tyriar**
  - [x] OS X - **@rebornix**
  - [x] Linux - **@roblourens**
- [x] Sanity check installable stable bits that have not been smoke tested
  - [x] Windows
    - [x] signed installer 32-bit **owner**
    - [x] signed installer 64-bit **@Tyriar**
    - [x] zip 32-bit **owner**
    - [x] zip 64-bit **owner**
  - [x] OS X - **owner**
  - [x] Linux
    - [x] deb package 32-bit **owner**
    - [x] deb package 64-bit **owner**
    - [x] rpm package 64-bit **owner**
    - [x] rpm package 32-bit **owner**
    - [x] archives **owner**
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [x] Publish rpm to repository manually **@Tyriar**
- [x] Add a git tag to `HEAD` of `release/1.31` in format `1.31.x`

**Comment by shawndon** [comment]
Signing off on localization for February 2019 release (v1.31 Loc)

**Comment by Tyriar** [comment]
rpm published

**Comment by mysticatea** [comment]
Hi. "Find in selection" button looks still broken: https://github.com/Microsoft/vscode/issues/68190
