### ISSUE TITLE
Object Destructuring Assignment Syntax Error

### ISSUE THREAD

**Issue by SourceBoy** [Microsoft/vscode#67226]
- VSCode Version: 1.30.2
- OS Version: Linux x64 (any)

Steps to Reproduce:

```javascript
let foo;
// This is supposed to be perfectly valid syntax in ES6+
{ foo } = { foo: 'bar' } // [ts] Declaration or statement expected. [1128]
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by SourceBoy** [comment]
^^^ vscodebot experimental duplicate detection failed.

**Comment by mjbvz** [comment]
Our built-in js support targets standardized ES. Your example does not work in current versions of Chrome or node

**Comment by SourceBoy** [comment]
@mjbvz  I specifically said it's a valid syntax in ES6+; in addition, it works both in the current version of Chrome and Node. See attached screenshots. Your claim is invalid.
![chrome](https://user-images.githubusercontent.com/791200/51859283-c4328f80-2304-11e9-815a-a8cb2a78e30c.png)
![node](https://user-images.githubusercontent.com/791200/51859289-c98fda00-2304-11e9-813d-ce3bc2b15973.png)

**Comment by mjbvz** [comment]
I'm not event sure anything has changed in the spec. It seems the repl is evaluating these statements differently than a normal program does. Try this more representative code instead:

```js
function a() { let foo;  { foo } = { foo: 'bar' }; return foo; }
```

This does not work in node v11.8.0

**Comment by SourceBoy** [comment]
@mjbvz  That would seem to be the case. I apologize and retract previous statements. Where would one file this bug if it's even considered as a bug?

**Comment by mjbvz** [comment]
Start with chromium or node. I suspect they are both using a common api to implement their interactive consoles but someone on those repos should be able move the bug upstream if needed. 

Then again, this might be the intended behavior for the consoles
