### ISSUE TITLE
File Association action doesn't work if settings file is dirty

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6722]
* have a dirty user settings file
* open another file, run the file association action
* the settings files open, a message appears but no chance is made

**Comment by jrieken** [comment]
and on save i got a conflict warning which makes me believe that we make those modification without consulting the editor model

<img width="997" alt="screen shot 2016-05-24 at 10 30 57" src="https://cloud.githubusercontent.com/assets/1794099/15497355/a8eea600-219a-11e6-9df1-1f564658efb7.png">

**Comment by aeschli** [comment]
We removed the feature that 'Configure File Association' adds a settings string due to the unresolved issues with the configuration open in a dirty editor.
