### ISSUE TITLE
Julia REPL style special symbol import

### ISSUE THREAD

**Issue by KsRyY** [microsoft/vscode#67229]
This idea is inspired by the way that you type in special symbol in the Julia REPL.

## Example

In the Julia REPL, type in `\xor` and press `TAB`, you will get `⊻`, the symbol of XOR. I have an idea that if the text editor detects anything like `\xor` or `\delta` the text editor could give a auto-completion that will replace the string into the corresponding symbol.

**Comment by alexandrudima** [comment]
This could be implemented by an extension.
