### ISSUE TITLE
Keybinding conflict for ctrl+` on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6723]
Testing #6654

![image](https://cloud.githubusercontent.com/assets/5047891/15497394/df149ffa-219a-11e6-9e96-563657fa8d48.png)

**Comment by Tyriar** [comment]
Yes the plan was to remove this after adding it to stable (which I did yesterday). Thanks for the reminder :)

**Comment by Tyriar** [comment]
Fixed https://github.com/Microsoft/vscode/commit/8fc7a0974317188faf8906097940b72b1537360c
