### ISSUE TITLE
DevTools close when opened while stuff is loading

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67245]
this might just be https://github.com/Microsoft/vscode/issues/62719 again

* run `scripts/code.sh`
* reload the window
* while that happens press cmd+alt+i to open dev tools
* wait a little and see how dev tools are closed again

**Comment by bpasero** [comment]
A regression from https://github.com/Microsoft/vscode/commit/a0b7054cb04d61fe3ddaba04ba0da092dc7264cf
