### ISSUE TITLE
vs window crash in windows(vs code version 1.30.2)

### ISSUE THREAD

**Issue by Abonia1** [Microsoft/vscode#67244]
Issue Type: <b>Bug</b>

while I do data operation with large size using python vs code windows close automatically 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2689 v4 @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|10.00GB (4.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.6
python|ms-|2018.12.1

</details>

**Comment by dbaeumer** [comment]
@Abonia1 what exactly are you meaning by **while I do data operation with large size**. Large files. Could you provide us with the file that causes the crash?

**Comment by Abonia1** [comment]
And it was caused because of insufficient system memory once I tried after upgrading my memory it works without crash.Thank you for your time to respond to this issue
