### ISSUE TITLE
Test dynamic views and view containers

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67243]
Testing: #66598 #66653

- [x] macOS @isidorn 
- [x] anyOS @RMacfarlane

Complexity: 2

## Installing

- Open an new empty window, go to extensions view
- Install an extension that has custom views and custom view containers. Eg: [Docker](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker)
- Verify that Docker icon is shown in the activity bar without reloading window
- Click on Docker icon and verify that docker views are shown with proper content

## Uninstalling
- Reload the window
- Go to extension views (Do not click on Docker icon so that Docker extension is not activated)
- Uninstall the Docker extension
- Verify that Docker icon disappears from activity bar

**Comment by isidorn** [comment]
Works nice!
