### ISSUE TITLE
View state still restored when closing inactive tab

### ISSUE THREAD

**Issue by urraka** [Microsoft/vscode#67246]
Issue Type: <b>Bug</b>

1. Set `workbench.editor.restoreViewState` to `false`.
2. Open a file and scroll away from the top.
3. Switch to a different editor tab.
4. Close the first file while tab is inactive.
5. Reopen the file.

Expected: scroll position should not be restored.

Actual result: scroll position is restored.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (1.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.8.0
vscode-subword-navigation|ow|1.2.0
subtle-brackets|raf|3.0.0

</details>

**Comment by bpasero** [comment]
Good catch. Tricky...

**Comment by bpasero** [comment]
Interesting that this was not reported before, I pushed a fix.
