### ISSUE TITLE
Integrated Terminal: do not use 'Esc' to close panel 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6724]
testing https://github.com/Microsoft/vscode/issues/6654:

- VSCode Version: 1.1.0 alpha
- OS Version: Windows 10

When using the integrated terminal it is common to use the 'ESC' key when interacting with command line tools. But in VS Code 'ESC' is used to close the panel which hides the integrated terminal.
With this behaviour it is very hard to use some command line tools.

I suggest that almost all keyboard input (or at least 'ESC') is directed to the integrated terminal if it has keyboard focus.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6455
