### ISSUE TITLE
Language Extension not recognizing "@"

### ISSUE THREAD

**Issue by dehilsterlexis** [microsoft/vscode#67249]
I'm writing a new language extension for NLP++ and have run across a problem with colorization. The language has keywords like `"@CODE"` or `"@RULE"` are not highlighting whereas "_xWILD" and "_xWHITE" are using the same regex statement. Here is the code. The first match does not work. The second does.

```
"name": "NLP",
    "patterns": [
        {
            "include": "#expression"
        },
        {
            "name": "keyword.other.nlp",
            "match": "\\b(?i:(fails|match|matches|lookahead|s))\\b"
        },
        {
            "name": "keyword.region.nlp",
            "match": "\\b@(CODE|DECL|NODES|PATH|POST|RULES)\\b"
        },
        {
            "name": "keyword.constants.nlp",
            "match": "\\b_(ROOT|xWILD|xNUM|xALPHA|xWHITE)\\b"
        },
```

Here is the highlight:

![image](https://user-images.githubusercontent.com/10133951/51846603-e8cc3e80-22e7-11e9-877c-5445d988d9d8.png)

**Comment by alexandrudima** [comment]
It looks like the `\b` before `@` is not really liked by regular expressions engines.

Here I have tried it: https://regex101.com/r/NuDSWn/1
![image](https://user-images.githubusercontent.com/5047891/60720926-87f70100-9f2c-11e9-8f38-31a0886bbe1c.png)

`\b@PATH` does not match `@PATH`.
