### ISSUE TITLE
Dynamic snippet contributions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67256]
Refs: n/a

- [x] any @sbatten (Windows)
- [x] any @weinand (macOS)

Complexity: 2

We have now dynamic extension points and test is needed. This is for snippets.

* Write an extension contributes snippets
* Disable/enable that extension
* Make sure snippets disappear/appear in IntelliSense and in the F1>Insert Snippet picker

**Comment by weinand** [comment]
I ran again into #67362 when installing and #67369 when disabling a snippet extension.

**Comment by dbaeumer** [comment]
Closing
