### ISSUE TITLE
Test that output isn't shown when there is a tasks error on start up

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67259]
- [x] windows @dbaeumer
- [x] anyOS @jrieken

Complexity: 2

Tests #64900.

1. Enable automatic tasks in the VS Code repository via the Tasks: Allow automatic tasks in folder command.
2. Disable the npm task provider by setting `"npm.autoDetect": "off"`. 
3. Reload the window.

Verify that the Tasks output panel is not shown on start up.

**Comment by jrieken** [comment]
Check - tho I find it rather weird that the default is `"reveal": "always"`.
