### ISSUE TITLE
Git repo in sub directory of other Git repo is not added to SCM

### ISSUE THREAD

**Issue by reijin90** [microsoft/vscode#67252]
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

Apparently this is supposed to work: #15341
However in my git repo (added to workspace), there is an other repo in a subfolder which is not found in SCM, even after adding it specifically to the workspace. Even specifically opening it with the Git open repo command from the palette, does not yield any results. Am I doing something wrong? And yes, I have a file opened from the sub-dir repo. 

edit: when I copy the sub-dir into a different folder and add it to the workspace from there it is added to SCM without issue. 

Does this issue occur when all extensions are disabled?: Yes/No
Haven't tested.

**Comment by joaomoreno** [comment]
Can you provide exact file/folder paths and steps, so I can attempt to reproduce?

**Comment by reijin90** [comment]
Sure! :)

Setup:
```
mkdir --parents gittest/sub/
touch gittest/file #not sure if needed
touch gittest/sub/file #not sure if needed
cd gittest/
git init
echo "/sub" > .gitignore
cd sub
git init
```

Then add `gittest `to the workspace --> will be added to SCM, but sub is untracked
Then add `sub `to the workplace --> will not be added to SCM

**Comment by paulocoliver** [comment]
+1

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/37947
