### ISSUE TITLE
C/C++ system types found by the tag parser aren't syntax highlighted as types

### ISSUE THREAD

**Issue by johanngerell** [Microsoft/vscode#67253]
Issue Type: <b>Bug</b>

C/C++ system types (Win32 API, std::, etc.) that are "found" by the tag parser aren't syntax highlighted as other C/C++ types (bool, char, float etc), as if the two concepts were disconnected, which I don't think they should/need to be.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (3.97GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.6.0
markdown-toc|Ala|1.5.6
recore|ali|0.1.11
Doxygen|bbe|1.0.0
theme-verdandi|be5|1.9.0
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-preview-github-styles|bie|0.1.4
macos-modern-theme|dav|1.1.3
githistory|don|0.4.4
vscode-great-icons|emm|2.1.46
enki-vscode-theme|enk|0.5.0
vsc-material-theme|Equ|2.6.3
file-icons|fil|1.0.16
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
vscode-flatland-icon-theme|geb|0.0.6
vscode-test-explorer|hbe|2.4.0
easy-icons|jam|0.3.1
csharpextensions|jch|1.3.0
vscodeilviewer|jos|0.0.1
vscode-icon-theme|jtl|1.6.5
theme-karyfoundation-themes|kar|18.2.1
autodocblocker|mad|1.0.2
markdown-shortcuts|mdi|0.9.0
python|ms-|2018.12.1
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
material-icon-theme|PKi|3.6.2
polacode|pnp|0.2.2
seti-icons|qin|0.1.3
try-material-icon-theme|raf|3.9.0
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
markdown-preview-enhanced|shd|0.3.11
ninja|sur|0.0.1
ayu|tea|0.17.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
file-icons-mac|way|1.0.1
vscode-icons-mac|way|7.25.2
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.0.1

(19 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
Can you please report the issue here since this very likely needs attention in the CPP extension: https://github.com/Microsoft/vscode-cpptools
