### ISSUE TITLE
JSON edit deletes comments

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6725]
#6657

* take your personal VS Code configuration file and make everything line comments
* run the stupid _file association_ action
* *all* of you previous (commented out) configuration is deleted

**Comment by aeschli** [comment]
Note that we removed the feature that 'Configure File Association' adds a settings string due to the unresolved issues with the configuration open in a dirty editor.

**Comment by aeschli** [comment]
Currently only verifiable in code. I added a test in `jsonEdit.test.ts, line 87`.
@jrieken Can verify this matches your scenario. I assume you had everything commented out, also the array brackets.

**Comment by jrieken** [comment]
correct - I had everything commented out

**Comment by joaomoreno** [comment]
Verified by code review. Test looks good.
