### ISSUE TITLE
Peek Definition jump to last definition

### ISSUE THREAD

**Issue by stanley0xffff** [Microsoft/vscode#67260]
When peek definition of "c_5" on line 10, the result should be shown the definition "cursor c_5 is" on line 2, but actually, the result of peek definition is jumped to "cursor c_8 is", not the proper one.

![image](https://user-images.githubusercontent.com/35367122/51782302-23f03580-2161-11e9-8771-73c608014411.png)

```js
//extension.ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "hello" is now active!');
	context.subscriptions.push(vscode.languages.registerDefinitionProvider(
		{scheme: 'file', language: "aaa"}, new GoDefinitionProvider()));
}

class GoDefinitionProvider implements vscode.DefinitionProvider {
    public provideDefinition(
		document: vscode.TextDocument,
		position: vscode.Position,
		token: vscode.CancellationToken):
        Thenable<vscode.DefinitionLink[]> {
		return new Promise((resolve, reject) => {
			var defs = [];
			for (var i = 0; i < document.lineCount; i++) {
				var line = document.lineAt(i);
				var perLine = line.text.toLowerCase().trim();
				if (perLine.startsWith("cursor")) {
					defs.push({
						targetUri: document.uri,
						targetRange: line.range
					});
				}
			}
			console.log(defs);
			resolve(defs);
		});

    }
}

// this method is called when your extension is deactivated
export function deactivate() {}
```

```
//package.json
{
	"name": "hello",
	"displayName": "hello",
	"description": "",
	"version": "0.0.1",
	"engines": {
		"vscode": "^1.30.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
		"onLanguage:aaa"
	],
	"main": "./out/extension.js",
	"contributes": {
		"commands": [
			{
				"command": "extension.helloWorld",
				"title": "Hello World"
			}
		],
		"languages": [{
			"id": "aaa",
			"extensions": [ ".aaa" ],
			"aliases": [ "aaa", "AAA" ]
		}]
	},
	"scripts": {
		"vscode:prepublish": "npm run compile",
		"compile": "tsc -p ./",
		"watch": "tsc -watch -p ./",
		"postinstall": "node ./node_modules/vscode/bin/install",
		"test": "npm run compile && node ./node_modules/vscode/bin/test"
	},
	"devDependencies": {
		"typescript": "^3.1.4",
		"vscode": "^1.1.25",
		"tslint": "^5.8.0",
		"@types/node": "^8.10.25",
		"@types/mocha": "^2.2.42"
	}
}
```

```
//text.aaa
cursor c_4 is
cursor c_5 is
cursor c_6 is
cursor c_7 is
cursor c_8 is

    c_2
    c_3
    c_4
    c_5
    c_6
    c_7
```

**Comment by gregvanl** [comment]
Moved to VS Code product repo as looks like product issue/question and not related to VS Code documentation.

**Comment by jrieken** [comment]
What version of VS Code is this?

**Comment by stanley0xffff** [comment]
> What version of VS Code is this?

1.30.2

**Comment by jrieken** [comment]
Please try this with insiders as some fixes have gone it that affecting this area

**Comment by jrieken** [comment]
> the result should be shown the definition "cursor c_5 is" on line 2, but actually, the result of peek definition is jumped to "cursor c_8 is", not the proper one.

Why would you expect this to be on line 2? All lines starting with "cursor" are always returned as definition. The UI always picks the nearest reference to be revealed first (and that's "cursor c_8")

**Comment by stanley0xffff** [comment]
> > the result should be shown the definition "cursor c_5 is" on line 2, but actually, the result of peek definition is jumped to "cursor c_8 is", not the proper one.
> 
> Why would you expect this to be on line 2? All lines starting with "cursor" are always returned as definition. The UI always picks the nearest reference to be revealed first (and that's "cursor c_8")

sometimes the peek definition refers to line2 correctly, but I don't know how to trigger it. The most case of peeking definition I tried is referring to the last definition.

**Comment by jrieken** [comment]
> sometimes the peek definition refers to line2 correctly, but I don't know how to trigger it. The most case of peeking definition I tried is referring to the last definition.

Can you put "sometimes" into reproducible steps?
