### ISSUE TITLE
Unable to add watch in debugger

### ISSUE THREAD

**Issue by brianmccarty** [Microsoft/vscode#67265]
Issue Type: <b>Bug</b>

I'm able to reproduce in both Python and Powershell scripts.  While using the debugger I am attempting to add a watch item and nothing happens in VS Code.  In the Developer Tools I see an error that increments with each attempt of adding a watch.  "Async data tree node is disposed"

![2019-01-28_10-30-43](https://user-images.githubusercontent.com/5996164/51857749-e669e480-22e7-11e9-9a41-285f6d701c40.gif)

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:21:00.148Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.41GB (7.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.4.4
xml|Dot|2.4.0
gitlens|eam|9.4.1
git-project-manager|fel|1.7.1
gc-excelviewer|Gra|2.1.28
vscode-journal-view|Gru|0.0.22
beautify|Hoo|1.4.7
vscode-gist|ken|2.1.2
PowerShell-Preview|ms-|2.0.0
team|ms-|1.144.1
indent-rainbow|ode|7.2.4
vscode-journal|paj|0.9.1
material-icon-theme|PKi|3.6.2
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
shell-launcher|Tyr|0.3.0

</details>

**Comment by isidorn** [comment]
@brianmccarty thanks for using insiders and for filling this issue.
However I can not reproduce it on my machine.
Can you please paste the exact error call stack that you see in the Developer Tools.
Also some steps would be great.

**Comment by chestertonic** [comment]
Same happened when debugging with cpptools. It seems to be fixed in the next insiders update.

**Comment by brianmccarty** [comment]
I'm in the debug tree, and if I click on the plus to watch a variable or if I right-click and select "add expression" I get nothing.  In the debug tools I do get an error that increments with each attempt.

![2019-01-29_09-39-04](https://user-images.githubusercontent.com/5996164/51928038-d7e40180-23a9-11e9-9adf-01014a31a29b.gif)


here is the text from the debugger:

(anonymous)	@	asyncDataTree.ts:549
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
n	@	errors.ts:184
e.queueRefresh	@	asyncDataTree.ts:547
(anonymous)	@	asyncDataTree.ts:557
Promise.then (async)		
(anonymous)	@	asyncDataTree.ts:557
(anonymous)	@	asyncDataTree.ts:555
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
n	@	errors.ts:184
e.queueRefresh	@	asyncDataTree.ts:547
(anonymous)	@	asyncDataTree.ts:540
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
n	@	errors.ts:184
e.refreshNode	@	asyncDataTree.ts:539
(anonymous)	@	asyncDataTree.ts:543
(anonymous)	@	asyncDataTree.ts:543
(anonymous)	@	errors.ts:184
(anonymous)	@	errors.ts:184
s	@	errors.ts:184
Promise.then (async)		
c	@	errors.ts:184
(anonymous)	@	errors.ts:184
n	@	errors.ts:184
e.refreshNode	@	asyncDataTree.ts:539
e.updateChildren	@	asyncDataTree.ts:388
(anonymous)	@	watchExpressionsView.ts:89
e.fire	@	event.ts:567
e.addWatchExpression	@	debugModel.ts:1040
e.addWatchExpression	@	debugService.ts:799
t.run	@	debugActions.ts:612
t.runAction	@	actions.ts:209
t.run	@	actions.ts:201
t.onClick	@	actionbar.ts:169
(anonymous)	@	menu.ts:408

**Comment by brianmccarty** [comment]
confirmed issue is no longer present in today's build

Version: 1.31.0-insider (system setup)
Commit: acc7365e41f9cb380e79bf78d7d102184f1ffe0d
Date: 2019-01-29T06:20:23.551Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by brianmccarty** [comment]
confirmed issue is no longer present in today's build

Version: 1.31.0-insider (system setup)
Commit: acc7365
Date: 2019-01-29T06:20:23.551Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
