### ISSUE TITLE
Test automatic task notification timing

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67262]
- [x] windows @dbaeumer
- [x] anyOS @sbatten

Complexity: 2

Tests #64355.

The automatic tasks notification should only show when you run a task, not on startup. To test:
1. Create an automatic task in a folder where you have never responded to the automatic task notification or allowed/disallowed automatic tasks.
2. Reload the window and confirm that the notification is not shown.
3. Start to run any task in from that folder. Verify that you see the automatic task notification.

**Comment by dbaeumer** [comment]
Closing
