### ISSUE TITLE
Settings tree colapses on single click

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67266]
Issue Type: <b>Bug</b>

See image. 

![image](https://user-images.githubusercontent.com/4674940/51857494-42803900-22e7-11e9-83bf-ab2f17b3d987.png)

Click on `Editor Management` node.
-> tree collapses but shouldn't

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:14:22.178Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|-psn_0_42760389|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/66796
