### ISSUE TITLE
All text/input has background color in Integrated Terminal

### ISSUE THREAD

**Issue by sethrr** [Microsoft/vscode#67264]
- VSCode Version: 1.30.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open Integrated Terminal 
2. All input and returned text comes with highlighted grey background.
3. If using WSL external terminal or CMDer, the issue is not present.

Does this issue occur when all extensions are disabled?: Yes

![capture2](https://user-images.githubusercontent.com/14112889/51856535-9560ed00-22f5-11e9-8d4e-b9cb19bc4cac.PNG)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
