### ISSUE TITLE
New pytest feature of the Python extension doesn't work in VS Code Insiders

### ISSUE THREAD

**Issue by luabud** [Microsoft/vscode#67270]
There'll be a new release for the Python extension that includes a new feature that highlights failed tests run with pytest, and when you hover over it, it shows a window that allows you to navigate to the failed test method and specific line, like this:

![jan19-pytesthover](https://user-images.githubusercontent.com/45497113/51859947-38613900-22ed-11e9-8604-b9d504ccd794.gif)

This works fine in the stable version of VS Code, but in the Insiders one it doesn't allow you to navigate to the failing test method nor line. 

- VSCode Version: 1.31.0-insider
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Download the 2019.1.0 version of the Python extension here: https://pvsc.blob.core.windows.net/extension-builds/ms-python-release.vsix
2. Open VS Code Insiders and install the new release version of the Python extension 
3. Create a folder (e.g. "Test") and open it in VS Code Insiders 
4. Create a file named "test_1.py" with this:
````
def test_failure():
    assert 42 == -13
````
5. Run "Discover Unit Tests" through the Command Palette
6. A "No test framework configured" message should pop up. Click on "Enable and configure a Test framework"
7. Select pytest and then root directory
8. Click "Run Test" from CodeLens or right click + "Run current unit test file"
9. Hover over the highlighted method and you'll see that you can't click on the displayed lines as you can using the stable version of VS Code 
![pytesthoverinsiders](https://user-images.githubusercontent.com/45497113/51860832-81b28800-22ef-11e9-89b9-ac453f1f9750.gif)

Since we're releasing tomorrow and this feature will be announced in our blog post, it'd be good to have this working in VS Code Insiders as well

**Comment by mattacosta** [comment]
This appears to affect all diagnostic tooltips, not just those from the Python extension.

A simpler method to reproduce it in TypeScript is to just call any method with an incorrect number of arguments:

![tooltip-links](https://user-images.githubusercontent.com/1007463/51873325-f8647b00-2319-11e9-8da1-47f9e979144a.png)

**Comment by dbaeumer** [comment]
@sandy081 starting with you. Not sure if you own this.

**Comment by sandy081** [comment]
Steps to verify:

- Open `src/vs/workbench/services/preferences/browser/preferencesService.ts`
- Comment following line
https://github.com/Microsoft/vscode/blob/1d2b3be2feb1700ba94d46de9c3024015a62de41/src/vs/workbench/services/preferences/browser/preferencesService.ts#L55
- Go to the line that has errors and hover on it to see the related information links
- Clicking on related information links should take to right location
