### ISSUE TITLE
Test: Keyboard navigation in trees

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67274]
Tests #64233, #64231

- [x] macOS @sandy081
- [x] linux @roblourens
- [x] windows @alexandrudima

Complexity: 3

New trees now support fancy keyboard navigation. These include Explorer, Search, all Debug trees, Problems. 

As you start typing when focused on the Explorer you should get a type label widget appearing in the top-right corner of the Explorer. This tracks the text you type which is matched against all _known_ files and folders (this does not recurse into folders which were never expanded, there's a separate issue tracking that).

There are three different behaviours:

- Highlight: as you type, the matching items should be rendered with highlights and keyboard arrow navigation should navigate only through those elements (Up, Down).
- Filter: as you type, the non-matching items get filtered out of view.
- Simple: this is the native File Explorer keyboard navigation experience; typing the first few characters of a file name will make focus jump there.

You can change between Highlight and Filter in the widget using the mouse (keyboard is #66899). You can also clear the whole type filter widget using the mouse or <kbd>Escape</kbd>.

You can change the default behaviour for all trees using the `workbench.list.keyboardNavigation` setting.

Known Issues:

- https://github.com/Microsoft/vscode/issues/67279
- https://github.com/Microsoft/vscode/issues/67280
- https://github.com/Microsoft/vscode/issues/67233

**Comment by dbaeumer** [comment]
Closing
