### ISSUE TITLE
Test: New Git extension API

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67276]
Tests #62609

- [x] anyOS @misolori  
- [x] anyOS @egamma

Complexity: 2

There have been a few Git extension additions via #62609. Let's properly test them.

You'll need to create a new extension using `yo code`. Then, in your extension's `activate` method, [reach out to the Git API](https://github.com/Microsoft/vscode-pull-request-github/blob/ca8204b9084b5786df351b6a1102eca8719733a9/src/git/model.ts#L11). Use [the typings](https://github.com/Microsoft/vscode/blob/b257ca20788c639d99790649f931f3b0fcccb331/extensions/git/src/api/git.d.ts), if using TypeScript.

Once you can reach the Git Extension API from your extension try using the API additions listed in the [PR, file `git.d.ts`](https://github.com/Microsoft/vscode/pull/64826/files#diff-4cd87ddd59c0be5eaf2cefce7a8f4a70):

1. `getGlobalConfig`
1. `log`
1. `diffWithHEAD` (0 args), `diffWith` (1 arg), etc.
1. Check `readonly authorEmail?: string | undefined;` property in `Commit` objects.

**Comment by joaomoreno** [comment]
It's interesting that both stderr and stdout are empty in your case... Do you have a `core.editor` setting configured at all, or is it a setting you don't have configured?

**Comment by misolori** [comment]
Running into the same issues as @egamma for `getGlobalConfig` & `getConfig`:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/35271042/52011979-44d0c780-248e-11e9-9f6c-75beb81482bc.png">
