### ISSUE TITLE
Format on save breaks Go template markup

### ISSUE THREAD

**Issue by ShaneLillieRAD** [Microsoft/vscode#67272]
- VSCode Version: 1.30.2
- OS Version: Windows 10

Steps to Reproduce:

1. HTML similar to this, using Go template markup:
`                        {{ safeHTML "<!-- /ko -->" }}`
2. Observe that saving with format on save feature turns it into this:
`                        {{ safeHTML "
                        " }}`
3. Note that the formatting as saved produces an error when run and it's an unexpected decision to break the string like that.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
