### ISSUE TITLE
Show only the first line when folded in Problems view

### ISSUE THREAD

**Issue by ctcampbell** [Microsoft/vscode#67273]
(Re-opening issue that was closed)

Diagnotics currently only allow a basic message, meaning what is shown in the problems view will be the same as the hover text. I would like to include a title for viewing in the problems view, and a description for more detailed information that appears when hovering over the problem code, or when expanding the problem in the problem view.

Example of this is shown in the screenshot. Veracode static analysis results can include lengthy descriptions of the security issue found that currently clog up the problems list view making them difficult to visually parse.

Image using multi-line diagnostics from Insiders. Ideally the second line of each diagnostic would only be visible in the hover.

<img width="1792" alt="screenshot 2019-01-28 at 20 24 57" src="https://user-images.githubusercontent.com/808531/51864310-4dfd4f80-233b-11e9-8769-a0647614cf05.png">

**Comment by ctcampbell** [comment]
@sandy081 I did try that, but it doesn't help me. The issue is that in my case the 'description' text is lengthy and clutters up the problems view, making it hard to understand the types of problems that have been found. I still need access to the description though as it contains useful remediation advice, ideally this would be visible when hovering over the problem in the source code or similar.

**Comment by sandy081** [comment]
@ctcampbell I think it did not help you because we are trying to show complete message in single line. Will it be helpful if we show just first line when you use the command `Problems: Show message in single line` ?

**Comment by ctcampbell** [comment]
That would be a good solution yes :)
