### ISSUE TITLE
editor.showFoldingControls stopped working in 1.30.2

### ISSUE THREAD

**Issue by getsetgopi** [Microsoft/vscode#67282]
- VSCode Version: 1.30.2
- OS Version: Windows 10

Steps to Reproduce:
1. Open any html/js/css
2. mouse over on the line number
3. expand/collapse icon does not appear

Does this issue occur when all extensions are disabled?: YES

**Comment by aeschli** [comment]
I'm not able to reproduce.
Installed fresh 1.30.2, new user data dir (no extension, no settings)
Open html file, hover over lines, folding appears.

Please check:
- is the content valid, has folding ranges, does it appear with all files. Note that there's a maximum of 5000 ranges per file.
- set `html.trace.server' to 'verbose, open the `HTML Langauge Server` output view and check whether you messages about foldingRange send
