### ISSUE TITLE
Folders open in the wrong window if you have 2 overlapping vscode instances

### ISSUE THREAD

**Issue by acberk** [Microsoft/vscode#67289]
Issue Type: <b>Bug</b>

The same issue as these, reproducible:
#3572
#13790

Expected:

1. File > New Window
2. Switch to new vscode window in the foreground
3. File > Open Folder
4. The Folder should now be opened in the active foreground vscode window

Actual:
1. File > New Window
2. Switch to new vscode window in the foreground
3. File > Open Folder
4. The Folder actually opened in the original vscode window instead.

Notes:
- Looks to be related to the "active" window as interpreted by vscode. It only occurs when 2 windows are opened and the "active" one is in front of the other.
- If the new window is on a different screen, the issue does not occur.
- If the new window is maximized to full screen, the issue does not occur.

![screencast from 01-28-2019 04_28_55 pm](https://user-images.githubusercontent.com/7095712/51868511-2ea2fa00-231c-11e9-9ca2-722508fdb12e.gif)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 3390)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.12GB (1.50GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by acberk** [comment]
Hey guys, I don't think there are any open duplicates of this bug. If so, would you mind referencing it here?

Thanks,
Alex

**Comment by bpasero** [comment]
@acberk 

https://github.com/Microsoft/vscode/issues/65773
https://github.com/Microsoft/vscode/issues/65665
https://github.com/Microsoft/vscode/issues/65533

You owe me 5 minutes now.

**Comment by acberk** [comment]
No need to be sarcastic. I've already seen each of those issues, but the bug still exists in the newest version 1.30.2 (which you can see I'm using).

Just trying to help you guys solidify your product. It takes a bit more than 5 minutes of my own time to submit an issue with a repro gif.  This is a minor bug and doesn't interrupt my workflow, but it should still be addressed.

**Comment by bpasero** [comment]
@acberk 1.30.2 is the version we released last year and you can see that the bugs I mention target our upcoming release. To benefit from the fix right now you can use our insiders release (nightlies): https://code.visualstudio.com/insiders/

Please understand that we typically receive 100-200 issues per day (not just in this repository, also in others) and we have to keep the amount of time we spend on each issue to an absolute minimum to actually be able to get work done. With a repository of 50.000 issues it is unfortunately not easy to find the exact duplicate issue even for me who owns the issue.

**Comment by matjaeck** [comment]
Can confirm the bug is fixed in the current insiders build.
