### ISSUE TITLE
window.zoomLevel causes font's to shift up or down

### ISSUE THREAD

**Issue by drewhamlett** [microsoft/vscode#67288]
I've narrowed this down to the zoomLevel setting.  It doesn't happen if it's not set.

- VSCode Version: 1.31.0-insider (and stable)
- OS Version: MacOS 10.14.2

Steps to Reproduce:
1. Set  "window.zoomLevel": 1 (to increase sidebar size)
2. Scroll down then back up
3. Delete a line
4. Random lines will shift up or down

![untitled-2 mov](https://user-images.githubusercontent.com/1056587/51867990-e59e7600-231a-11e9-926e-1fd4ae620c0f.gif)

Does this issue occur when all extensions are disabled?: Yes

I pulled down master of vscode and ran it locally.  It seems setting the css property zoom, or transform to zoom the editor makes this go away.  Everything in the editor is based off the window zoom level so it messes up a lot of things.  Might be helpful

**Comment by drewhamlett** [comment]
Just a heads up.  I can't reproduce this in the exploration build

Version 1.31.0-exploration (1.31.0-exploration)
https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip

**Comment by alexandrudima** [comment]
Since we now ship with Electron 4.x, this must be fixed...

**Comment by drewhamlett** [comment]
Yes, not seeing this anymore.  Thanks!
