### ISSUE TITLE
Test: workspace saving 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#67286]
Testing: n.a

- [ ] anyOS @bpasero 
- [x] anyOS @egamma

Complexity: 2

There have been refactorings in the code that creates and saves workspaces

- create a new unsaved workpace by opening VSCode on a folder and adding a folder
- test that `Save Workspace As...` works as expected on a new unsaved workspace
- test that `Save Workspace As...` works as expected on an existing workspace
- close a window that has an unsaved workspace and save the workspace
- create a workspace at location that is parent to the folders it contains. Verify that the `.code-workspace` file contains paths that are relative to the workspace file
- test that saved workspaces show up in the `Open Recent` list.

**Comment by egamma** [comment]
Tested the above scenarios and they worked as expected.

**Comment by bpasero** [comment]
Seems to still work nicely.
