### ISSUE TITLE
VS Code Incorrectly detects Angular Errors

### ISSUE THREAD

**Issue by waelkdouh** [Microsoft/vscode#67284]
VS Code detects that there is an error in my Angular application (html, ts, etc.) whereas the angular compiler compiles the project successfully. The solution is to close the file and reopen it. In some cases I have to restart VS Code to resolve the issue. I do have Angular Language Service Extension installed so I am not sure if its the culprit. Its really a huge inconvenience right now that needs to be resolved. I am surprised no one else brought up this issue as it seems to be widespread.

**Comment by mjbvz** [comment]
Since this sounds angular specific, please file this issue against the angular extension
