### ISSUE TITLE
Test GitHub Pull Request Live Share support

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#67299]
Test for https://github.com/Microsoft/vscode-pull-request-github/pull/836

- [x] macOS @weinand
- [ ] linux @Tyriar
- [x] windows @dbaeumer

Authors: @rebornix, @RMacfarlane

The GitHub Pull Request is now using the vsls API to proxy git calls when a user is in a Live Share session. Please test that these continue to work when you are either the host or guest of a session:
* File change diff views are displayed correctly
* Can check out a PR
* Can navigate to comments using the comments panel when a PR is checked out

Please use the [nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) of the extension to test, and file issues at https://github.com/Microsoft/vscode-pull-request-github. You can use [this repo](https://github.com/auchenberg/pullrequest-demo) for testing

Complexity: 3

**Comment by dbaeumer** [comment]
Couldn't test the comments part since the nightly build extension claims on all PRs that they are closed after checkout. See https://github.com/Microsoft/vscode-pull-request-github/issues/852

**Comment by dbaeumer** [comment]
@RMacfarlane please ping if there is something I can retest

**Comment by weinand** [comment]
Couldn't test the "comments" part either.
Since I'm out for the rest of the week I won't be able to test that even if fixed...

**Comment by Tyriar** [comment]
I couldn't test this, it just seems to not work at all on Linux https://github.com/Microsoft/vscode-pull-request-github/issues/898
