### ISSUE TITLE
Test GitHub Pull Request GraphQL changes

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#67297]
Test for https://github.com/Microsoft/vscode-pull-request-github/issues/762

- [x] anyOS @auchenberg
- [x] anyOS @misolori 

Authors: @rebornix, @RMacfarlane 

We have migrated much of the communication with GitHub from the REST version of their API to the new GraphQL version. This item is to test that there have been no regressions in the extension's behavior. This includes
* The PR tree view should list PRs and associated file changes
* The description webview should present all commits and comments of the PR, and all links on it should be functional
* Creating, editing, and deleting comments should work (There is a separate test item for the new reviews flow beginning with `Start Review`, this is adding individual comments as before)

Please use the [nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) of the extension to test, and file issues at https://github.com/Microsoft/vscode-pull-request-github. You can use [this repo](https://github.com/auchenberg/pullrequest-demo) for testing

Complexity: 3

**Comment by auchenberg** [comment]
I take MacOS!
