### ISSUE TITLE
The integrated terminal appears to be bottom-aligned, which makes it wobbly

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6729]
Testing #6654 

* resize the terminal panel
* observe how the text "jumps" up or down when enough space is created for a new line

![terminal-wobbly](https://cloud.githubusercontent.com/assets/5047891/15497713/4fa566fe-219c-11e6-87fe-77dfce1dc3e0.gif)

**Comment by Tyriar** [comment]
It's wobbly when there is not enough content to fill up the panel. I made it bottom aligned to prevent the wobbliness when the terminal had content.

Not sure there is a way around this unless we fork term.js and change the way that the terminal is represented. Doing so would also enable improvements to selection and enable scroll bars (#6602).

**Comment by Tyriar** [comment]
Resolving as designed.
