### ISSUE TITLE
 Cannot set property 'selectedIndex' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#673]
Issue Id: <b>6af7ca20-c779-2639-367c-1a3ac64248dc</b><br /><br />*Versions* <br />- 0.10.1-release<br />-  4536038a3a72c694bc793ffeea83b2e54eae6308<br />*Stack* <br />[/vs/editor/contrib/suggest/browser/suggestWidget.ts#L346:60 (SuggestWidget.constructor)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L346:60 (SuggestWidget.constructor))<br />[/vs/base/common/eventEmitter.ts#L241:18 (EventEmitter._emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L241:18 (EventEmitter._emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L267:8 (EventEmitter._emitEvents)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L267:8 (EventEmitter._emitEvents))<br />[/vs/base/common/eventEmitter.ts#L187:9 (EventEmitter.addEmitter)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L187:9 (EventEmitter.addEmitter))<br />[/vs/base/common/eventEmitter.ts#L253:21 (EventEmitter._emitToBulkListeners)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L253:21 (EventEmitter._emitToBulkListeners))<br />[/vs/base/common/eventEmitter.ts#L262:8 (EventEmitter._emitEvents)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L262:8 (EventEmitter._emitEvents))<br />[/vs/base/common/eventEmitter.ts#L285:8 (EventEmitter.emit)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/common/eventEmitter.ts#L285:8 (EventEmitter.emit))<br />[/vs/base/parts/tree/common/treeModel.ts#L1031:7 (TreeModel.setSelection)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/tree/common/treeModel.ts#L1031:7 (TreeModel.setSelection))<br />[/vs/base/parts/tree/browser/treeImpl.ts#L209:13 (Tree.setSelection)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/base/parts/tree/browser/treeImpl.ts#L209:13 (Tree.setSelection))<br />[/vs/editor/contrib/suggest/browser/suggestWidget.ts#L607:14 (SuggestWidget.acceptSelectedSuggestion)](https://github.com/microsoft/vscode/blob/df352367df2efcfa9d602d471e4e2f42140a0f05/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L607:14 (SuggestWidget.acceptSelectedSuggestion))<br />    at e.acceptSelectedSuggestion (out/vs/workbench/workbench.main.js:1587:16304)<br />

**Comment by dudeofawesome** [comment]
I'm experiencing this error when editing a Typescript file and trying to select a suggestion from intellisense.

VSCode 1.3.1
Extensions related to TS:
TSLint

**Comment by joaomoreno** [comment]
@dudeofawesome Can you reproduce it all the time? Can you show me a video/screenshot?
