### ISSUE TITLE
Test: Search view with new tree

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67302]
- [ ] any os @octref
- [x] any os @sbatten

Complexity: 2

The search view now uses the new tree. Take it through its paces and look for any oddities.

- Search in single folder and multiroot
- Remove matches
- Replace
- Modify open file and see search tree update
- Type to filter

**Comment by sbatten** [comment]
After talking with @roblourens, there appear to be existing issues around the type to filter experience with search and it may need further thought. In this case, I am not focusing on the filtering functionality.

**Comment by octref** [comment]
My only issue is type-to-filter, but @roblourens mentioned that we need more tree API to include filenames' children, search results, in the filter output:

![image](https://user-images.githubusercontent.com/4033249/51943576-a893bb80-23ce-11e9-8133-1fea61d41e9f.png)
