### ISSUE TITLE
Test: Custom data for HTML and CSS

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67306]
Testing #62976 and #64164

- [x] Windows @dbaeumer 
- [x] anyOS @kieferrm

Complexity: 3

Instructions:

- Read https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_31.md#html-and-css-custom-data-support and understand what it does.
- These two samples should illustrate the usage of the custom data: https://github.com/octref/simple-customdata and https://github.com/octref/svg-data
- Here are the more detailed doc:
    - [HTML Custom Data](https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md)
    - [CSS Custom Data](https://github.com/Microsoft/vscode-css-languageservice/blob/master/docs/customData.md)

Test the following:

- With `html.experimental.customData` and `css.experimental.customData`, you can make VS Code understand custom HTML tags/attributes and custom CSS properties/atDirectives/pseudoClasses/pseudoElements
- You are able to pack the JSON files into an extension using `contributes.html.experimental.customData` and `contributes.css.experimental.customData`.

**Comment by dbaeumer** [comment]
@octref this is blocked by #67544

**Comment by octref** [comment]
@dbaeumer Do you mind testing starting from https://github.com/octref/simple-customdata? I've added precautions against the wrong settings, but it won't be available until next insider.

The settings should look like ([example](https://github.com/octref/simple-customdata/blob/master/.vscode/settings.json)):

```json
{
  "html.experimental.customData": ["./html.json"],
  "css.experimental.customData": ["./css.json"]
}
```
