### ISSUE TITLE
C++ Intellisense doesn't re-compile after git pull

### ISSUE THREAD

**Issue by decitrig** [Microsoft/vscode#67305]
Issue Type: <b>Bug</b>

1. On computer A, write some c++ code with a compile eror.
2. Push to remote git repository.
3. On another machine, fix the code & push to the repository.
4. On computer A again, pull the fix.

I expect that the red squiggles would go away when I pulled the fix, but they don't, and I couldn't find a way to manually re-trigger intellisense without editing.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
vscode-bazel-tools|dpr|0.0.8
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0

</details>

**Comment by dbaeumer** [comment]
This is a problem with the CPP Tools extension. Please report the issue here: https://github.com/Microsoft/vscode-cpptools
