### ISSUE TITLE
Auto guess encoding should not supersede language specific configurations 

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#67303]
Issue Type: <b>Bug</b>

When 
```  "files.autoGuessEncoding"``` is set to ```true``` language specific encoding is ignored. 
It should not be the case. Language specific encoding on user preferences should always be enforced. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-path-tools|cg-|0.0.4
code-runner|for|0.9.6
terminal|for|0.0.10
matlab|Gim|0.9.0
language-julia|jul|0.11.4
nim|kos|0.6.2
r|Mik|0.0.5
python|ms-|2018.12.1
cpptools|ms-|0.21.0
sublime-keybindings|ms-|4.0.0
r-lsp|REd|0.0.8
code-settings-sync|Sha|3.2.4
shell-launcher|Tyr|0.3.0
markdown-pdf|yza|1.2.0

(2 theme extensions excluded)

</details>

**Comment by FrancoisMongeau** [comment]
I have the same issue. I searched and there are many similar issues (eg #34943, #34769, #19890) but these are not exactly the same (I think there is some confusion between these related issues). It's difficult to understand the issue ( well described above by @pedrogarci ) as you need to toggle multiple settings. 

Plus the app does not behave the same when the user drags the file onto the opened app as opposed as using Open With from Explorer. 

This issue becomes dangerous as you can save the file with the wrong encoding if you do not look as the encoding displayed in the bottom right corner of the screen.

**Comment by pedrogarcia** [comment]
> I have the same issue. I searched and there are many similar issues (eg #34943, #34769, #19890) but these are not exactly the same (I think there is some confusion between these related issues). It's difficult to understand the issue ( well described above by @pedrogarci ) as you need to toggle multiple settings.
> 
> Plus the app does not behave the same when the user drags the file onto the opened app as opposed as using Open With from Explorer.
> 
> This issue becomes dangerous as you can save the file with the wrong encoding if you do not look as the encoding displayed in the bottom right corner of the screen.

I think in one of the issues @bpasero said that the problem was with a dependency, and therefore they would not fix it. 

I guess that not all text editors are born equal, as this one does not consider text editing an important feature enough for a reproducible bug that corrupts file to be treated as important? 

Anyway @FrancoisMongeau, you shouldn't be using vscode fora ny important text editing, where you absolutely cannot have a file completely corrupted.

**Comment by extratype** [comment]
Language-specific `"files.autoGuessEncoding": false` setting is working by the way.
