### ISSUE TITLE
Ability to install / uninstall multiple extensions at once

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6730]
#6099

- VSCode Version: alpha
- OS Version: OS X

It would be cool if I could pass multiple extensons to the install-extension / uninstall-extension command and we would install / uninstall multiple extensions at once.
Currently only the first argument is respected, while the others are ignored.

![screen shot 2016-05-24 at 10 42 16](https://cloud.githubusercontent.com/assets/1926584/15497705/44335f2e-219c-11e6-8fec-b129b5c3d434.png)

**Comment by joaomoreno** [comment]
`--uninstall-extension foo.bar --uninstall-extension monkey.baboon` works.
