### ISSUE TITLE
Blank titlebar briefly rendered when changing from custom to native titlebar with grid layout

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#67300]
Issue Type: <b>Bug</b>

```json
"workbench.useExperimentalGridLayout": true,
"window.titleBarStyle": "custom"
```

When changing the titlebar from custom to native, on restart the old custom titlebar is briefly rendered before the workbench loads:
![custom_to_native_titlebar](https://user-images.githubusercontent.com/3672607/51874481-fe585d00-2315-11e9-919a-53b5f103b7a6.gif)

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:14:22.178Z)
OS version: Darwin x64 18.0.0

**Comment by sbatten** [comment]
@joaomoreno this might actually be a dupe. it happens regardless of grid layout

**Comment by joaomoreno** [comment]
@sbatten Workbench is @bpasero

**Comment by jrieken** [comment]
@sbatten rapid render relies on parts being parts. what's going on when the new grid is active?

**Comment by sbatten** [comment]
@joaomoreno a classic jo* mix-up in assigning you sorry lol

@jrieken the parts are still parts in the new grid, they are just added to a grid so the dom structure is different. this issue reproduces in stable however

**Comment by jrieken** [comment]
> this issue reproduces in stable however

thanks - I will investigate

**Comment by jrieken** [comment]
This is actually a bit of a known limitation as the old state is persisted...

**Comment by sbatten** [comment]
@jrieken I don't know exactly where this logic lives, but if you have access to this function, https://github.com/Microsoft/vscode/blob/52fb9079e9da9583eee211da275e9e7887ef90fe/src/vs/platform/windows/common/windows.ts#L253, can you update the state after reading.

**Comment by jrieken** [comment]
Hm, will that return the correct value *before* restarting? Data is written on shutdown and then used to render the parts way before loading our sources...

**Comment by alexr00** [comment]
I'm still seeing the blank titlebar briefly rendered when switching from custom to native on Windows.
