### ISSUE TITLE
Custom view icons are rendered incorrectly when using grid layout

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#67301]
Issue Type: <b>Bug</b>

1. Grid layout on
2. Enable extension that contributes custom view

![screen shot 2019-01-28 at 4 11 13 pm](https://user-images.githubusercontent.com/3672607/51874828-5f346500-2317-11e9-8d7d-4df7b1faa664.png)

(this is gitlens and liveshare)

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:14:22.178Z)
OS version: Darwin x64 18.0.0

**Comment by sbatten** [comment]
fixed by https://github.com/Microsoft/vscode/commit/7ca3f253db3371604e390ef1ceca88cc6dff95f5
