### ISSUE TITLE
Support when clause for viewContainer contributions to the activity bar

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67311]
When contributing a view, for example, to the explorer I can specify a when clause of the form `config.<myConfigurationKey>`. Depending on the value of the setting, the view either shows up in the explorer's view context menu or not.

I'l like to be able to same with viewContainer contributions to the activity bar. I.e. I'd like to hide them until they are enabled in settings.

**Comment by sandy081** [comment]
@kieferrm View container is not shown if none of the views it contained are shown/enabled. So, defining the `when` context for your views should be enough for your use case.

**Comment by kieferrm** [comment]
@sandy081 that worked. Thanks. Do we have any documentation around this?

**Comment by sandy081** [comment]
No.
