### ISSUE TITLE
We should change the build system.     "gulp-atom-electron": "^1.19.2", is deprecated

### ISSUE THREAD

**Issue by frank-dspeed** [Microsoft/vscode#67319]
"gulp-atom-electron": "^1.19.2", got deprecated and references manual build script as successor

https://github.com/joaomoreno/gulp-atom-electron

this issue here is some how related https://github.com/Microsoft/vscode/issues/67180

**Comment by frank-dspeed** [comment]
this issue here is some how related https://github.com/Microsoft/vscode/issues/67180

**Comment by joaomoreno** [comment]
Yeah... I deprecated it such that no one _else_ uses it. :laughing: 

It's fine for us for now.

**Comment by frank-dspeed** [comment]
@joaomoreno why don't you simply put information like not maintained or no support on that then ? As you see you keep people busy with that style of information :D
