### ISSUE TITLE
Automatic update for VS Code does not work

### ISSUE THREAD

**Issue by mehul19851** [Microsoft/vscode#67318]
![screenshot_vscode_updatedialog](https://user-images.githubusercontent.com/3696360/51887813-0c13ee00-23bb-11e9-9b4c-378fb9b2d207.png)
Issue Type: <b>Bug</b>

Hello Team,

Whenever there is a new update available and VS Code starts downloading the udpate. When the download is completed a dialog is shown at bottom right of the screen asking to "Restart VS Code to apply the latest udpate". However, when clicked on "Update Now" button, nothing happens further. There is no udpate installer to be seen (which is expected post restart of VS Code). After waiting a while, and when trying to launch again the version is still the old one.

Can someone look into this behavior and let me know the fix for it? 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
alexa-skills-kit-toolkit|ask|1.0.0
ask-cli-configure|mar|0.2.1
csharp|ms-|1.16.2
quicktype|qui|12.0.46

</details>

**Comment by joaomoreno** [comment]
Please check whether Code is in quarantine. Check https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150

**Comment by mehul19851** [comment]
how do i check that?

**Comment by joaomoreno** [comment]
Read https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150

**Comment by mehul19851** [comment]
@joaomoreno Thank you, the 2 steps mentioned in the comment fixed the issue. VS Code is now updated to 1.30. Cheers!
