### ISSUE TITLE
Tree twisties should not be rendered when all children are filtered out

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#67315]
Is this the responsibility of the tree or should I call setChildren again without these children?

- In the settings editor search `commandpalette`
- See "workbench" in the TOC which has children but they are hidden by the filter

![image](https://user-images.githubusercontent.com/323878/51886188-90c32580-2343-11e9-9885-800c68d2ce74.png)

**Comment by roblourens** [comment]
Also I added some code that sets `collapsed` and `collapsible` explicitly but this happens even when those are not specified.

**Comment by joaomoreno** [comment]
It should be the tree, you shouldn't have to setChildren, since all you're doing is filtering. Pushing to to February tho, hope that's fine.

**Comment by joaomoreno** [comment]
The current implementation resets the whole model and you do the filtering yourself. In that example, the `workbench` tree element is created with `collapsible = true`, which adds a twistie to it.

![screenshot from 2019-02-22 10-24-34](https://user-images.githubusercontent.com/22350/53232757-1d83a980-368c-11e9-828c-58c945f750dc.png)

---

@roblourens You can solve it by simply fixing the `collapsible` value or, better, by using the tree's filtering mechanism and then I can see what I can do from my side.

**Comment by roblourens** [comment]
I am using the filter to do the search filtering: https://github.com/Microsoft/vscode/blob/59ba3f853d19d572d6cb3b8919d99990de338e51/src/vs/workbench/contrib/preferences/browser/tocTree.ts#L164

The other filtering is just to get the group nodes. So what I was thinking is that any node with children should be "collapsible" but when the tree filters out a child, the twistie would be removed.

But, what I'm asking for doesn't make sense in all cases. Like I think here, the twistie should stay

![image](https://user-images.githubusercontent.com/323878/53263890-8587bf00-368f-11e9-99a4-9f1627176c6c.png)

So to "fix the collapsible value" I have to invoke the tree filter myself to check whether the element has visible children, or I can just actually do all the filtering myself. Right? Or if not what do you mean?

**Comment by joaomoreno** [comment]
I see. You seem to be using the filter yet calling `setChildren` all the time. I have since then introduced a `refilter` method which is better performing than `setChildren`. Given that the TOC tree model doesn't really change during its entire lifecycle, you're better off just calling `refilter` after the user has typed anything in the input box.

Now, for the twistie: we probably need a new concept in the tree. Maybe `collapsible` can have a third value which would mean "collapsible if any children are visible". What do you think?

**Comment by roblourens** [comment]
> Maybe `collapsible` can have a third value which would mean "collapsible if any children are visible". What do you think?

That sounds great!

**Comment by joaomoreno** [comment]
This setting came in via another request: `hideTwistiesOfChildlessElements`. Added it to the TOCTree, @roblourens can you review and verify?

**Comment by roblourens** [comment]
Works great! Thanks!

**Comment by joaomoreno** [comment]
@roblourens Verified? 👍
