### ISSUE TITLE
VS Code doesnt run without internet

### ISSUE THREAD

**Issue by pratik037** [Microsoft/vscode#67323]
We have written the needed d
Issue Type: <b>Performance Issue</b>

**Switch off the internet and try starting the VS Code again**

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    88	  1936	code main
    0	    66	  2156	   shared-process
    0	    69	 12048	   window (Issue Reporter)
    0	   167	 12748	   window (question_text.dart - trial - Visual Studio Code)
    0	    13	   652	     electron-crash-reporter
    0	    67	  6752	     extensionHost
    0	     4	  1316	       C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter\bin\flutter.bat" "daemon""
    0	   155	 13336	         "C:\flutter\bin\cache\dart-sdk\bin\dart.exe"   "C:\flutter\bin\cache\flutter_tools.snapshot" "daemon" 
    0	    11	 13868	         console-window-host (Windows internal process)
    0	     4	 11400	       C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\flutter\bin\cache\dart-sdk\bin\dart.exe" "C:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=Dart-Code.dart-code" "--client-version=2.22.1""
    0	   252	 12092	         "C:\flutter\bin\cache\dart-sdk\bin\dart.exe"  "C:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=Dart-Code.dart-code" "--client-version=2.22.1"
    0	    11	 14104	         console-window-host (Windows internal process)
    0	    37	  9192	     searchService
    0	    11	 10252	     watcherService 
    0	    11	 12632	       console-window-host (Windows internal process)
    0	     6	 13504	     winpty-process
    0	    66	 12944	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	 13676	       console-window-host (Windows internal process)
    0	   178	 13672	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (question_text.dart - trial - Visual Studio Code)
|    Folder (trial): 189 files
|      File types: png(23) json(20) xml(15) bin(10) dart(9) dex(9) class(7)
|                  properties(7) jar(7) flat(7)
|      Conf files:;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.22.1
flutter|Dar|2.22.1
vscode-eslint|dba|1.8.0
beautify|Hoo|1.4.7
vscode-language-babel|mgm|0.0.21
python|ms-|2018.12.1
cpptools|ms-|0.21.0
vscode-react-native|vsm|0.8.0

</details>
ata into your clipboard because it was too large to send. Please paste.

**Comment by dbaeumer** [comment]
@bpasero not sure if it can be folded of the closed #7570
