### ISSUE TITLE
Rewriting in C/C++

### ISSUE THREAD

**Issue by hkcorac** [Microsoft/vscode#67320]
Hello VSCode developers,

May I suggest to rewrite the entire project in C/C++? For example GTK for cross-platform support.

I guess Microsoft is able to fund the rewrite effort.

Thank you Sirs.

**Comment by francoism90** [comment]
@hkcorac Fork the project and rewrite into the language that you prefer. Let us know when you've finish.

**Comment by dbaeumer** [comment]
This is currently out of scope of the VS Code project.
