### ISSUE TITLE
Exception thrown when installing the same extension twice

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6732]
#6099

1. code-alpha --install-extension lukehoban.Go --install-extension lukehoban.Go
2. notice exception

![screen shot 2016-05-24 at 10 50 42](https://cloud.githubusercontent.com/assets/1926584/15497952/73681f7c-219d-11e6-8fc0-98ab78917414.png)

**Comment by joaomoreno** [comment]
Easy, tiger.
