### ISSUE TITLE
Settings: tree shows scroll shadow immediately

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67329]
Refs: https://github.com/Microsoft/vscode/issues/67304

* open settings (I have zoom level 1)
* click on an entry to the left which is not "Commonly Used"
* :bug: I see the scroll shadow immediately:

![image](https://user-images.githubusercontent.com/900690/51895365-40cb7980-23aa-11e9-93b7-c1adee869d68.png)

**Comment by roblourens** [comment]
I don't understand the issue...

**Comment by bpasero** [comment]
@roblourens why? I did not scroll down, just opened

**Comment by roblourens** [comment]
You said you clicked an entry in the TOC and that causes the settings editor to scroll to that section

**Comment by bpasero** [comment]
Wow, I completely did not see that we are not filtering the settings, but scrolling down.
