### ISSUE TITLE
How could I enable backdrop filters in Visual Studio Code?

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#67328]
Backdrop filters in the tab bar would be a great feature if the scrollable editing area blends into underneath the tab bar. However, Chrome does not support it unless with a certain flag enabled.

This feature also requires that the code editing area have a padding and be under the tab bar when scrolled.

**Comment by dbaeumer** [comment]
Not sure if editor or workbench

**Comment by infinnie** [comment]
@dbaeumer Both the editor tab bar and perhaps the menu.

**Comment by infinnie** [comment]
![image](https://user-images.githubusercontent.com/8168391/51895870-29aa7d00-23e6-11e9-8cf6-91f7de1ba4c1.png)
I wonder whether it would look better if a backdrop filter were applied to the toolbar background and the inactive tabs, revealing the code being edited in a gaussian blur.

Something like
![image](https://user-images.githubusercontent.com/8168391/51896115-ae959680-23e6-11e9-9e7a-c574177aeaf7.png)
