### ISSUE TITLE
Visual Studio Code very slow with dotnet

### ISSUE THREAD

**Issue by pathak1005** [Microsoft/vscode#67325]
Issue Type: <b>Bug</b>

C:\Users\apathak>dotnet restore[

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.4.2
plsql|cas|0.0.5
python-preview|don|0.0.4
code-runner|for|0.9.7
vscode-test-explorer|hbe|2.4.0
beautify|Hoo|1.4.7
r|Iku|1.0.2
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.2
vscode-python-test-adapter|lit|0.2.8
dotenv|mik|1.0.1
r|Mik|0.0.5
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.12.1
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
notepadplusplus-keybindings|ms-|1.0.2
material-icon-theme|PKi|3.6.2
vscode-yaml|red|0.2.1
plsql-language|xyz|1.7.0

</details>

**Comment by dbaeumer** [comment]
@pathak1005 what exactly is slow for you. Running `dotnet restore`? If it is with VS Code itself please follow the steps provided here https://github.com/Microsoft/vscode/wiki/Performance-Issues to report performance issues.

**Comment by dbaeumer** [comment]
I am closing the issue. Please ping if you have provided additional information.
