### ISSUE TITLE
"Null Extension Description" shown in the notification

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#67326]
- install the Material Icon theme
- the extensions prompts you to activate the theme

-> the notification shows 'Null Extension Description' in the source field of the notification

![image](https://user-images.githubusercontent.com/172399/51894637-a3bc1100-23a8-11e9-8514-7c985396fe7c.png)

**Comment by bpasero** [comment]
@sandy081 this is `nullExtensionDescription` it seems, please advise.

**Comment by sandy081** [comment]
@alexandrudima FYI

**Comment by alexandrudima** [comment]
Nice find! We were forgetting to update the trie that identifies which extension requires vscode..
