### ISSUE TITLE
Settings: can select multiple entries

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67332]
Refs: #67304 

* open settings
* shift-select multiple entries
* :bug: it works

![image](https://user-images.githubusercontent.com/900690/51895765-407fae00-23ab-11e9-94d5-40cae5797253.png)

**Comment by roblourens** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/cdfaca550685dd60923247e2aadfe7023e45c716
