### ISSUE TITLE
JSON semantic selection should expand to line before selecting ','

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#67339]
Testing https://github.com/Microsoft/vscode/issues/67277

See screen shot:

<img width="428" alt="capture" src="https://user-images.githubusercontent.com/1931590/51899858-2c8c7a00-23b4-11e9-8dcc-90fbfe7fa2b8.png">

Expanding the selection should not first expand `"search.exclude"` to cover the whole line before selecting the trailing `,`

**Comment by aeschli** [comment]
Line selections are provided by a default provided and merged without JSON's control -> @jrieken
