### ISSUE TITLE
Settings: weird expansion state when searching

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67333]
Refs: #67304

* search for "linenu"
* click into the results
* :bug: the expansion/collapse of things is weird at best

![peek 2019-01-29 09-53](https://user-images.githubusercontent.com/900690/51895976-c00d7d00-23ab-11e9-82e4-1a2f666f610c.gif)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/67315
