### ISSUE TITLE
'ng' is not recognized

### ISSUE THREAD

**Issue by CodeLoverTech** [Microsoft/vscode#67337]
Hi Team,

I am getting Error Message below: 
--------------------------------------------------------------
Program 'ng' failed to run: No application is associated with the specified file for this operationAt line:1 char:1
+ ng
+ ~~.
At line:1 char:1
+ ng
+ ~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
---------------------------------------------------------------------------
I have updated Angular 7.2.3 , node 10.15.0 and npm 6.5.0 globally install.

So please Suggest me for Further Update.

Thanks & Regards,
Rahul Kumar
+91-6381996475
info.rajinfotech@gmail.com

**Comment by dbaeumer** [comment]
@CodeLoverTech does this work for you in a normal PowerShell terminal ?

**Comment by Tyriar** [comment]
Are you on Windows? This means that the shell (powershell) doesn't see ng on your path.

**Comment by CodeLoverTech** [comment]
Hi Daniel,

In Visual Studio Code, Powershell is not working for "ng" tag. but Bash is
working fine.
So thank you so much for your valuable response. we will further update if
any kind of issue found.

**Comment by Tyriar** [comment]
Oh ok, you probably didn't configure powershell right or something (which I'm no expert in).
