### ISSUE TITLE
Settings: bold selected element should not jump

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67334]
Refs: #67304

* click into settings TOC
* each selected element jumps up a bit because it gets bold

=> I would prefer if the element stays visually on the same line and not jump upon clicking

**Comment by roblourens** [comment]
Seems like this should be disabled by default because most trees will not be expecting to handle it? @joaomoreno

**Comment by roblourens** [comment]
This is the wrong issue 🤦‍♂️

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/67332

**Comment by joaomoreno** [comment]
I can't repro the jumping on macOS. Also, you might be able to fix this by setting line-height === row height.

**Comment by roblourens** [comment]
Did this involve zoom or something? Haven't been able to repro.
