### ISSUE TITLE
Settings: keyboard navigation is janky

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67331]
Refs: #67304

* open settings editor
* click into the new tree
* arrow up and down and notice very weird behaviour
* :bug: at the end I cannot even navigate up anymore

![peek 2019-01-29 09-47](https://user-images.githubusercontent.com/900690/51895656-fdbdd600-23aa-11e9-99e7-90bd912b8c77.gif)

**Comment by roblourens** [comment]
Fixed by improving the tree's `firstVisibleElement` this month
