### ISSUE TITLE
Seperate Menu Header Color for Different Windows

### ISSUE THREAD

**Issue by MukundhanSampath** [Microsoft/vscode#67343]
Seperate Menu Header Color for Different Windows can enable user to quickly identify the tabs they are in while switching tabs instead of looking at the actual code to identify the workspace we are in.

**Comment by dbaeumer** [comment]
There is an extension that does this. See https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors

Does this satisfy your needs ?

**Comment by dbaeumer** [comment]
Closing assuming that the extension is satisfying the needs.
