### ISSUE TITLE
[api] 'openExternal` instead of `open`

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#67344]
Testing #67234

 `open` is very general. What about calling it openExternal?

We already have a commands like 'vscode.openFolder' and I see that we will soon need something like `openWindow`

**Comment by jrieken** [comment]
@mjbvz Objections? We could call it `openExternal` and it would only do that. From a quick scan that's what most extensions want to do anyways and others can still use the vscode.open-command, e.g. when you want to open a png inside the editor

**Comment by jrieken** [comment]
I have pushed a rename to `vscode.env.openExternal` which means we cannot use this function for that portion of the `vscode.open`-command anymore that opens things *inside* VS Code, like png-files. That wasn't implemented anyways and iff we want to offer something similar in the future it will likely be something like `vscode.window.showItem(target: Uri, options: { viewColumn, preserveFocus, ...}): Promise<void>`
