### ISSUE TITLE
Wrong entry gets deleted

### ISSUE THREAD

**Issue by istvand-aam** [Microsoft/vscode#67349]
Issue Type: <b>Bug</b>

Hi,

When I right-click on an entry in the Explorer tree structure, sometimes the selection doesn't follow, and another file gets deleted. I lost a yet-to-be-versioned file on this. Could you please look into it?

Thanks!

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2715)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.40GB (1.20GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-django|bat|0.17.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
gitlens|eam|9.4.1
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.5.0
rpm-spec|Lau|0.2.3
MagicPython|mag|1.1.0
python|ms-|2018.12.1
docker-compose|p1c|0.3.3
vscode-docker|Pet|0.5.1
vscodeintellicode|Vis|1.1.2
jinja|who|0.0.8

</details>

**Comment by mcarpenterjr** [comment]
Experiencing the same issue, I believe this has to do with how files are selected and the visual representation. It looks like it is possible to select multiple items unintentionally and in some cases, the selected item is misrepresented. Just ran into a case where I used CTRL+Click to select a block of items and then right click->delete to remove them, except a file open in the editor was removed and the selected items remained. Visually they were all still selected and I again tried with the delete key on the keyboard, no response.

**Comment by isidorn** [comment]
@istvand-aam can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by istvand-aam** [comment]
Hi @isidorn , sorry for the late response - it seems to work correctly with Insiders (version below).
It has a second, darker selection for the actual item now which is the one I right-click on and also the one I move with the keyboard, and this is the one that gets deleted, as expected.

Thank you for the fix!

```
Version: 1.32.0-insider
Commit: 52306b406d9231a0667c758e536bd177e5570180
Date: 2019-03-01T06:14:49.135Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 3.10.0-957.5.1.el7.x86_64
```

**Comment by isidorn** [comment]
Thanks for letting me know
