### ISSUE TITLE
[scss] instellisense doesn't work when importing variables from separate file

### ISSUE THREAD

**Issue by jkanczler** [microsoft/vscode#6734]
- VSCode Version: 1.1.1
- OS Version: Windows 7

Steps to Reproduce:
1. Create an scss file with a simple variable
2. Create another scss file that is importing the previously created scss file
3. Try to implement a class in the second scss file and try to use the variable in there. Intellisense is not working inside a class, just outside a class:

![image](https://cloud.githubusercontent.com/assets/10925650/15498007/bd27f006-219d-11e6-8ea7-5b0c514503ac.png)

![image](https://cloud.githubusercontent.com/assets/10925650/15498050/f7c6356a-219d-11e6-9f24-d967cb598863.png)

**Comment by aeschli** [comment]
Yes, our css/less/sass supports are single file only.

**Comment by towertop** [comment]
I was looking for this and got told that visual studio 2013 ever support this with additional comments:

https://blogs.msdn.microsoft.com/webdev/2013/11/06/a-high-value-undocumented-less-editor-feature-in-visual-studio/

It would be gorgeous if vscode inherit it. :)

**Comment by third774** [comment]
Definitely +1 for this feature request! :+1:

**Comment by tgrosh** [comment]
+1

This is a must have feature for me. Every time I sit down to do my LESS work, I always end up switching back to Visual Studio so I can get the references for my variables and mixins. This needs to happen.

**Comment by mattez** [comment]
What about suggest variables from another opened file also? not only from linked ones.

**Comment by mattez** [comment]
Similar thingss are discussed in these issues https://github.com/Microsoft/vscode/issues/10762 and https://github.com/Microsoft/vscode/issues/6820

**Comment by mattez** [comment]
Both popular editors - Brackets and Sublime - support this via extensions. I'm just want to switch to VSCODE and lack of this functionality is pretty big blocker for me. I'm really surprised that this essential feature for front-end developers is still missing in so clever editor which vscode surely is.

**Comment by mattez** [comment]
How can I support this feature to be done? It should have higher priority.

**Comment by mrmlnc** [comment]
Firsly, @mattez, thank you for your interest. I think developers would like to add all requested features, but now it is impossible.

> From @bpasero 
>
> Since we are a small team of developers, there is only so many feature requests and issues we can work on for one milestone. Nevertheless we always welcome pull requests and are happy to accept them if they meet our quality standards.

I'm not an employee of Microsoft, but writing [extensions for this editor](https://marketplace.visualstudio.com/search?term=mrmlnc&target=VSCode&sortBy=Relevance). 

I also use Less in their projects and even wrote a [book about Less](https://mrmlnc.gitbooks.io/less-guidebook-for-beginners/content/) in my native language. I am also waiting for this functionality.

And now let's talk about functionality. Please @aeschli tell me, this functionality should be implemented in `vscode-css-languageservice` or as separate extension?

If as an extension, then I'm ready to create it. Anytime Soon.

**Comment by mattez** [comment]
**Thank you** @mrmlnc for your support.
I'm really happy to see fist attempt to begun **to solve this specifically**. Hurray.

I know nothing about development strategies, but don't you can start on developing _extension_ which could then later can be integrated to and became part of _vscode_? 

BTW I have not tested jet (I'm more LESS user) but there is [SASS extension](https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented) already.
But in general as a user I prefer "implemented" solution or very very good writen :) extension witch no interfere with existing features of _vscode_ mainly it's _IntelliSense_.

And there is such a big part in _default-settings.json_ dedicated to _SASS_ and _LESS_ so it looks like _vscode_ want to support these languages deeply.

**Comment by mattez** [comment]
Hi @mrmlnc have you got any hints from @aeschli ?

**Comment by mrmlnc** [comment]
@mattez, nope, but I'm working on an extension for Less (Sass later) 🌵

**Comment by mrmlnc** [comment]
@mattez, please, help me testing [vscode-less](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less) extension ❤️.

**Comment by mrmlnc** [comment]
@towertop, @tgrosh. @mattez, please, help me testing [vscode-less](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less) extension ❤️.

**Comment by mattez** [comment]
@mrmlnc I just installed you brand new hot extension. **IT JUST WORKS** so far. So I'm going to use it on a real projects.
I looks gr8. Thank you very much @mrmlnc .

**Comment by bgashler1** [comment]
This would come in very handy, especially if we as VS Code are going to switch our styling to SCSS #8589.  It would already help us today on our website (I've ran into much of the same pain as mentioned here).

**Comment by mrmlnc** [comment]
@bgashler1, I planned SCSS IntelliSense for next week. Now I want to identify problems in the current solution (performance [important], information in popup's and more cases).

**Comment by mrmlnc** [comment]
@netopolit, @mattez, @bgashler1, @druellan, @marvinhagemeister,

Please, help me test testing [vscode-scss](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss) extension ❤️.

**Comment by druellan** [comment]
Seems to work pretty well!

![2016-10-25_11h02_44](https://cloud.githubusercontent.com/assets/6965667/19689145/bd8a1a64-9aa2-11e6-92f1-4e7aeffdc36e.png)

In fact, too well:

![2016-10-25_11h04_29](https://cloud.githubusercontent.com/assets/6965667/19689159/ce41e22e-9aa2-11e6-86a1-b7377c9ebda4.png)

Perhaps a way to ignore a path is needed. Also, not sure if the "implicitly" is so useful that worth taking up space for the path and the variable contents.

Another thing I noticed, and this can be a VScode problem:
![autocomplete](https://cloud.githubusercontent.com/assets/6965667/19689954/753a30ac-9aa5-11e6-9798-faf794cff362.gif)

If you write the property, hit ctrl+space and then you keep typing, the autocomplete is not refreshed.

**Comment by MaximeDesRoches** [comment]
It seems to be working fine.

I'm getting this in the panel:

```[Error - 10:27:01 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'type' of null
  Code: -32603```

**Comment by druellan** [comment]
Another thing, I'm getting contextual help on every item inside a mixin:

![2016-10-25_12h13_12](https://cloud.githubusercontent.com/assets/6965667/19692025/c1deb660-9aac-11e6-92c5-1b5ed6e25d6a.png)

**Comment by mrmlnc** [comment]
@druellan, @MaximeDesRoches,

Thanks for help! I really appreciate this.

I have repository for this plugin (https://github.com/mrmlnc/vscode-scss) and progress over your comments you can check there.

**Comment by sjova** [comment]
+1

**Comment by lynnchen1020** [comment]
vscode-scss just works perfectly !  
Would like to know if it is possible for sass version? Thanks.

**Comment by Ne-Ne** [comment]
Have there been any updates on this issue?

Thanks.

**Comment by smspivak** [comment]
solved
https://github.com/Microsoft/vscode/issues/23815

**Comment by PixelT** [comment]
No, it's not solved

**Comment by felixfbecker** [comment]
With `@import` and variables being a native concept in CSS, imo this really needs to be part of the built-in CSS/SCSS/Less support. I love @mrmlnc's extension but it is unable to resolve files in many cases when using `@import`, which makes me wish this was supported natively.

**Comment by mirkea** [comment]
Why is the SCSS format the unwanted child of stylesheets when it's arguably the best syntax to use? I feel like I'm getting punished for using the optimal solution

**Comment by mrmlnc** [comment]
@octref, I correct understand that the VS Code team wants to work on a solution that will work as drop-replacement for my plugins (`vscode-scss` & `vscode-less`)?

**Comment by aeschli** [comment]
I assume you use the Seti icon theme.

The reason is the way our Seti icon theme associates the icons. The elm icon is contributed to all files with file extension '.elm', for for the language mode elm.

That can be improved, but IMO it's not most urgent. I hope you agree.

**Comment by octref** [comment]
@mrmlnc Just looking into the problem to understand it better before committing to any promises.
What's some of your biggest pain points in maintaining vscode-scss/less? Are any existing issues impossible to fix or requested features impossible to do?

Merging might make sense, but that involves converting css-language-service to support projects instead of single files. This is a lot of change.

**Comment by onetrev** [comment]
I'd love to see a merge into css-language-service, as then I'd assume there would be support across projects for things like CSS variables, which are very much the future.

**Comment by octref** [comment]
SCSS variables and CSS variables are very different in scopes. So let's not confuse things here.

**Accurate** CSS variable completions require understanding of the DOM tree since CSS variables are scoped based on DOM structure.
CSS `@imports` can even be remote files. The way you serve the CSS files on your website could also have different structure than the CSS source files.

On the other hand for SCSS variables/mixins/functions, it's possible to analyze them, resolve dependencies and output suggestions accurately. However that would take quite some effort.

So my suggestion would be to use https://github.com/mrmlnc/vscode-scss for now, which scans through your working dir and outputs completions globally. Anyway in SCSS variables are global by default.

**Comment by Haemp** [comment]
@octref Unfortunately that plugin is quite broken - won't even resolve @import paths as it stands now. Would love to see some attention put on this since SCSS is still a major tech for most devs.

**Comment by octref** [comment]
@Haemp Just as we were speaking! https://github.com/Microsoft/vscode/pull/55971

**Comment by cduivis** [comment]
Issues have been created stating that the same thing happens for the less filetypes, but are closed as duplicate referencing this issue.
Variables in less are still not auto-completed when `@import`ing other files.
Could the title be adjusted to be more generic, or to also include less ?

**Comment by KytoSai** [comment]
I hope anyone continue develop vscode-scss extension
https://github.com/mrmlnc/vscode-scss/issues/78

Currently vscode does not have the scss extension good enough and is still developing...

**Comment by BradCandell** [comment]
Glad to hear that it's making its way into #83930 

It's making SCSS development less ideal following conventions like externalizing variables and code completion of functions. The extensions that are recommended just don't seem to be cutting it!

**Comment by rjgotten** [comment]
> Glad to hear that it's making its way into #83930

Just hope it's _also_ making its way into there for **Less** and not just scss.

**Comment by octref** [comment]
I [helped](https://github.com/mrmlnc/vscode-scss/issues/83) vscode-scss with its development for a bit. I prepared a new release, [0.8.0](https://github.com/mrmlnc/vscode-scss/releases/tag/v0.8.0) and @mrmlnc could release it to Market Place.

During my test I think vscode-scss works pretty well. So instead of copying over its features I helped with its development. Over the time we might consider adding multiple file support in VS Code's CSS/SCSS/Less support, but we don't want to commit to it yet.

For Less, you can checkout [vscode-less](https://github.com/mrmlnc/vscode-less), by the awesome @mrmlnc as well.

**Comment by aeschli** [comment]
To verify, install the vscode-scss extenssion
