### ISSUE TITLE
Grid: Snap hiding a part isn't properly propogated to parts

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67355]
Refs: #67308

* show sidebar and an editor
* make window small enough that sidebar hides (this seems like a new feature to me)
* make the window large
* 🐛 the activity bar is still indicating the explorer is active
* 🐛 clicking the explorer icon does not show the sidebar

**Update:** figured out that hiding a grid view by using the mouse is not calling into the same code as toggling. E.g. `ISideBar.closeViewlet` is not triggered as it is when doing it through an action.

**Comment by sbatten** [comment]
fixed by c952a8876d6010a85ba66dc46864405d8ae441c3

**Comment by sandy081** [comment]
Verified that side bar is not getting hidden when reducing the size of the window.
