### ISSUE TITLE
Grid: sidebar/panel size is not persisted and restored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67354]
Refs: https://github.com/Microsoft/vscode/issues/67308

* change size of sidebar or panel
* reload window
* 🐛 size is not restored

**Comment by bpasero** [comment]
I think this is even true for toggling sidebar/panel during the running session.

**Comment by awittaker** [comment]
Bonus prize opportunities!
- Ability for extension to override sidebar size (so different views can have different sidebar widths)
- Reduce/remove minimum sidebar size 
Use case for this: Implement a tool bar like extension, that doesn't chew real estate, but still lets other views open to default sidebar width.

**Comment by bpasero** [comment]
Seems to work fine now.
