### ISSUE TITLE
Extension update is calling extension point handlers even though window reload is required

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67350]
- Run VS Code from sources
- Enable Marketplace (ping me if you want to know how you can do it)
- Install `999 Test Extension`. This contributes a view and activates on `*`
- No reload is shown 👍 . Running extensions has an entry for this. 👍 
- Open Dev tools and keep a break point here - https://github.com/Microsoft/vscode/blob/af608864808988ed5c6ef7259514d9386864f2b6/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L343
- Install another (previous) version of this extension by using the action `Install Another Version...` under gear icon.

🐛  View extension point handler is called even though the extension was activated and the reload button is also shown after completing.

**Comment by alexandrudima** [comment]
@sandy081 The steps are a bit fuzzy because the extension does not really activate on *... Or perhaps you have pushed more changes to it since you've created the issue..?

**Comment by sandy081** [comment]
@alexandrudima True, I changed the extension after. I will publish a new version.

**Comment by sandy081** [comment]
Verified in sources
