### ISSUE TITLE
Grid: toggle editor area is dangerous

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67356]
Refs: #67308

I would strongly advise to not introduce an action that removes the editor area from the view of the user without a clear indication how to get back to it. This brings up memories where we once allowed to hide the explorer view and we constantly got bugs from users complaining that the list of files was gone.

To showcase the power of the grid I would suggest to rather expose more locations of the panel (e.g. to the left or above the editor). 

![image](https://user-images.githubusercontent.com/900690/51902536-8abc5b80-23ba-11e9-89a7-bbfc65907eb0.png)

**Comment by sbatten** [comment]
@bpasero toggling the editor area only has an effect with the experimental flag enabled and currently the same command should bring it back, but there is an issue with size restoration in today's build causing a lot of issues. additionally, I could have the editor unhide if a new editor is opened, thoughts?

**Comment by bpasero** [comment]
> I could have the editor unhide if a new editor is opened, thoughts?

👍 💯

**Comment by sbatten** [comment]
better with https://github.com/Microsoft/vscode/commit/1fb26f9b5791f612e322589383fb99fbcb005e7b

**Comment by sbatten** [comment]
@bpasero I added that one as well, I'm not sure what it adds, but it shouldn't harm anything because we were already listening to it for other reasons

**Comment by bpasero** [comment]
Should verify that the editor shows (if hidden) when interacting with it.
