### ISSUE TITLE
Installing a (debugger) extension requires reload

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#67362]
Issue Type: <b>Bug</b>

Testing #67231

After installing the Python debugger, I was presented a "reload" button.
This is unexpected since adding extensions should not require reload.

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
@aeschli Looks like you forgot to set the extension point to be dynamic 

https://github.com/Microsoft/vscode/blob/9c510825d6a7f8b9d428c35378dc4adb1900dd6e/src/vs/workbench/services/jsonschemas/common/jsonValidationExtensionPoint.ts#L16

**Comment by aeschli** [comment]
@sandy081 Pushed a fix
