### ISSUE TITLE
Empty space in Source Control Providers view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67378]
Testing #67275

- Enable `workbench.tree.horizontalScrolling`

![image](https://user-images.githubusercontent.com/10746682/51905490-aa0ab700-23c1-11e9-8ac4-5a094f0f0335.png)

![image](https://user-images.githubusercontent.com/10746682/51905519-b5f67900-23c1-11e9-90d3-d9a7e831fd57.png)

**Comment by joaomoreno** [comment]
This was hard to figure out, disabled horizontal scrolling for that view for now.

**Comment by joaomoreno** [comment]
Nevermind, figured it out!
