### ISSUE TITLE
When using NVDA screen reader, hovering over a file in the explorer no longer reads the file name.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#67374]
Found while testing #66485 on Windows using the NDVA screen reader.
Accessibility support is off (not sure if this matters)	`"editor.accessibilitySupport": "off"`

In stable, when you hover over a file in the explorer the name of the file is read. In insiders it reads the name of the currently open file, not the file being hovered over.

**Comment by isidorn** [comment]
I can not reproduce this on my VM. 
However I see it on @alexr00 machine. I have verified that we set the correct `arialabel` on the element on her machine.
Leaving open to see if more people actually hit this, not sure if something wrong with nvda, Alex's machine or our electron update.
