### ISSUE TITLE
Horizontal scroll bar is not seen in references widget

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67376]
Testing #67275

- Enable `workbench.tree.horizontalScrolling`
- Open references widget by triggering peek all references
🐛 I do not see horizontal scroll bar for the tree

![image](https://user-images.githubusercontent.com/10746682/51905164-d4a84000-23c0-11e9-978e-2eba2bd78220.png)

**Comment by chrmarti** [comment]
Works on Linux.
