### ISSUE TITLE
Grid: panel and sidebar right does not work?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67372]
Refs: #67308

* set panel and sidebar to be on the right
* 🐛 I cannot get both the panel and sidebar to show

![image](https://user-images.githubusercontent.com/900690/51904959-4df36300-23c0-11e9-8f7c-ac5eb5436bae.png)

**Comment by sbatten** [comment]
this might be the case where the viewlet is snapped closed so dragging it out should work in this case.

@joaomoreno i'm not 100% on this but it looks like the snapping capability is biting us a little in that moving items in the grid causes items to snap on their own. I believe snapping should only happen on the item i am shrinking with the mouse

**Comment by sbatten** [comment]
fixed

**Comment by ctf0** [comment]
thanx @sbatten for the fix.

small note about decreasing the panel size, the top right icons will become hidden, if possible maybe they can be grouped under a 3 dots or something menu.

again thanx for the fix
