### ISSUE TITLE
vscode.env.open with empty string opens Windows explorer window

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#67373]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67234

Passing in an empty string to vscode.env.open:

`vscode.env.open(vscode.Uri.parse("")).then(response => { ... 
`

results in a Windows Explorer window being opened. This was a bit surprising and wasn't documented. Should this not open anything and return false? I'm not sure, was just a bit surprised by what it did.

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:20:23.551Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.27
python|ms-|2018.8.0
azure-account|ms-|0.8.0
test-search-rg|rob|0.0.3

</details>

**Comment by jrieken** [comment]
That URI shouldn't be allowed to begin with - for extensions we are less strict but for this function we should enforce at least a scheme is given. However, when actually happens with the URI depends on the OS and its implementation of open

**Comment by jrieken** [comment]
I pushed a change that enforces uris to have a scheme. What happens then is up to the OS
