### ISSUE TITLE
Inconsistent expansion of selection to line/object

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67383]
Issue Type: <b>Bug</b>

Testing #67277

Here we expand to the line first:
![jan-29-2019 12-33-44](https://user-images.githubusercontent.com/9205389/51905856-b6dbda80-23c2-11e9-9aa1-c559f016c3bb.gif)

Here we skip expansion to the line and immediately select the surrounding object:
![jan-29-2019 12-34-29](https://user-images.githubusercontent.com/9205389/51905826-a1ff4700-23c2-11e9-8ba7-2a4bc6b067db.gif)

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none

**Comment by aeschli** [comment]
The line selections are coming from the default selection provider. But there seems to be an inconsistency as to when line selections are added by the default selection provider.
I see line expansion when the editor selection is on a single line.but not when the editor selection spans multiple lines (as in the first screencast). IMO we should also provide it for multi-line editor selections for both the first and last line.
