### ISSUE TITLE
Inconsistency in list/tree settings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67387]
Testing #67274

There are couple of list/tree settings those get applied for tree only or lists only or for both.

- `workbench.tree.horizontalScrolling` - Both lists and trees
- `workbench.list.keyboardNavigation` - Only for trees (if I am not wrong)

It is confusing what gets applied to tree and lists. We should either have consistent prefixes for both or have specific settings for each but not mixed.

**Comment by joaomoreno** [comment]
The problem is that `workbench.tree.horizontalScrolling` already existed. At best we can deprecate it in favor of `workbench.list.horizontalScrolling`. But that can only happen next month.

**Comment by joaomoreno** [comment]
@sandy081 Since it's the second time this week I've migrated an issue, I've created a util to `getMigratedSettingValue`:

https://github.com/Microsoft/vscode/commit/3e70d8c62d80030a56cd4887298e3dca9215a4e4#diff-800a35d2b141a47ddf9bb3008ce1fb4e

I couldn't get it simpler than that. Please review and let me know if it's incorrect.

**Comment by sandy081** [comment]
Looks good.

**Comment by sandy081** [comment]
@joaomoreno Following are the issue I observed moving from old to new setting and if users have old setting enabled

- UI shows horizontal scrolling disabled, but the trees show horizontal scrolling

![image](https://user-images.githubusercontent.com/10746682/53405374-04466a00-39b8-11e9-93d7-95e4a42b1426.png)

- Enabling horizontal scrolling triggers restart even though it is already enabled.

- May be not so important, but the settings file now shows `Unknown Configuration Setting` for the old setting. May be a deprecation message might be useful?

**Comment by joaomoreno** [comment]
@sandy081 Is that possible?

**Comment by sandy081** [comment]
Yeah you can add a deprecation message like follows

```
'problems.autoReveal': {
			'description': Messages.PROBLEMS_PANEL_CONFIGURATION_AUTO_REVEAL,
			'type': 'boolean',
			'default': true,
			'deprecationMessage': 'this is deprecated'
		}
```

This will not suggest the setting in the intellisense and also show a deprecation warning when used.

**Comment by joaomoreno** [comment]
@sandy081 https://github.com/Microsoft/vscode/commit/c4bb8788e9f6f8363d624430f9ee2147864a3a8d
