### ISSUE TITLE
Actions at the end of the entries are not shown when horizontal scrolling is enabled

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67380]
Testing #67275

We have some trees and lists those have actions on hover and these are shown at the end (right). If horizontal scrolling is enabled these actions are not shown/discoverable on hover. For eg: SCM view.

![image](https://user-images.githubusercontent.com/10746682/51905689-27362c00-23c2-11e9-9bfa-7b8633b67cfe.png)

**Comment by joaomoreno** [comment]
Closing as designed. This is a limitation already disclosed when horizontal scrolling was initially implemented.
