### ISSUE TITLE
Grid: switching to HC theme does not initially show border from sidebar to editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67384]
Refs: #67308

* be in normal dark theme (note that I have zoom level 1)
* enter HC theme
* 🐛 not all borders are showing until you resize or reload:

![image](https://user-images.githubusercontent.com/900690/51905922-e7237900-23c2-11e9-927f-10883902ab8b.png)

Should be:

![image](https://user-images.githubusercontent.com/900690/51905933-f0ace100-23c2-11e9-92ab-01575c502aea.png)

**Comment by sbatten** [comment]
not able to repro on linux or macOS, please re-open if this is still an issue you can reproduce
