### ISSUE TITLE
.git folder not showing in explorer even when setting the files.exclude setting

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#67388]
Found while testing #66485 on Windows.
This is also happening in stable.

Setting: 
````
	"files.exclude": {
		"**/.git": false,
		"**/.svn": true,
		"**/.hg": true,
		"**/CVS": true,
		"**/.DS_Store": true
	}
````
I expect to see the .git folder in the explorer. I can see it in the native file explorer, but not in VS Code explorer. I tried refreshing the explorer and reloading the Window, but it does not show up.

**Comment by isidorn** [comment]
Since it is also happening on stable -> february to investigate then
