### ISSUE TITLE
Scrolling to the bottom sometimes makes the terminal jump under the file explorer

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6738]
Testing #6654

This is sort of what I did:
* `cd .\src\vs\languages\typescript\common\lib`
* `node generate.js`
* `cls`
* scroll down
![terminal-under-explorer](https://cloud.githubusercontent.com/assets/5047891/15498182/d244be00-219e-11e6-8503-926dc590e10b.gif)

**Comment by Tyriar** [comment]
From @kieferrm in #6846 

> OS: Windows

> 1) open the built-in terminal 
> 2) run command that produces a bunch of output such as 'npm list' or cat a file
> 3) try to scroll up to reveal text that was already scrolled out of sight
> -> content is scrolled to the left (and then gets stuck)
> -> there is no reliable way to get the terminal back into a 'normal' state; sometime Enter works, sometimes not

> Here is a [screen recording](https://www.dropbox.com/s/y0x7m77ys8xne3v/scroll-issue.mov?dl=0).

**Comment by Tyriar** [comment]
This could very well be fixed with transition to xterm.js, need to wait for repros in insiders
