### ISSUE TITLE
Alt+click on a folder in explorer is unpredictable.

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67382]
Found testing #66485.

Starting point:
![image](https://user-images.githubusercontent.com/38270282/51905568-d8889200-23c1-11e9-98bd-65a086166bfb.png)
Expand actionbar with regular click:
![image](https://user-images.githubusercontent.com/38270282/51905608-f0f8ac80-23c1-11e9-8436-c84bf45e1d96.png)
Collapse actionbar with regular click:
![image](https://user-images.githubusercontent.com/38270282/51905631-0372e600-23c2-11e9-94fd-7f99c775d7fc.png)
Collapse ui with regular click:
![image](https://user-images.githubusercontent.com/38270282/51905666-1e455a80-23c2-11e9-9e08-1add30372f49.png)
**Expand ui with alt+click**
![image](https://user-images.githubusercontent.com/38270282/51905711-3f0db000-23c2-11e9-8c30-04dd73571d64.png)

It seems like actionbar should not be expanded. I didn't have any files from this subtree open while testing.

**Comment by isidorn** [comment]
Combination of dup of https://github.com/Microsoft/vscode/issues/66811 and as designed
