### ISSUE TITLE
Filter highlights overlap with search highlights

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#67398]
Testing #67274

![image](https://user-images.githubusercontent.com/10746682/51910125-931e9180-23ce-11e9-99c1-47b55f09d210.png)

IMO in Search view, simple and filter options only makes sense.

**Comment by joaomoreno** [comment]
Related to #67397

@roblourens Should we just disable this feature in Search?

**Comment by roblourens** [comment]
I'm not that concerned about this issue, at least for a month, but I would support disabling it for #67397

**Comment by joaomoreno** [comment]
Agree, moving to you then. 👍

**Comment by myk3v** [comment]
I am sorry to hit you up on this again. This feature certainly makes search more accessible via keyboard. Is there any possibility to let the user configure filtering search results? Competing editors even allow editing search results to implement global search-and-replace

**Comment by connor4312** [comment]
This feature is disabled in search (for quite a while now), so am closing this for grooming.
