### ISSUE TITLE
No remove delta received when disabling extension

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#67391]
Testing #66910

- install eamodio.remotehub
- restart code and open from console with `code-insiders --folder-uri remotehub://github/Micorosoft/vscode-nls`
- in the explorer, note that the title shows `VSCODE-NLS (REMOTEHUB)`
- install the `aeschli.remotehub-companion` [vsix (remove zip file extension)](https://github.com/Microsoft/vscode/files/2807533/remotehub-companion-0.0.1.vsix.zip). It contains only a `resourceLabelFormatters` contribution, which is a dynamic contribution point
- reload (file different issue #67389)
- explorer label has already changed to `VSCODE-NLS (GI*)`, that means the contribution has received a delta
- in the extensions viewlet  'disable'  the remotehub-companion extension
-  `VSCODE-NLS (GI*)` still shown

Setting a breakpoint in labelService.ts, line 86 shows that the delta received has an empty removed delta.

**Comment by alexandrudima** [comment]
Nice catch!
