### ISSUE TITLE
Settings search doesn't find a match

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#67396]
- VSCode Version: 1.30.2, 1.31.0
- OS Version: macOS High Sierra

I was looking for a setting that I was sure must be there. The key words were "markdown tab size" and in retrospect, I was looking for this:

```
  // Whether to use different indentation sizes on different context
  //  - adaptive: Use 2 spaces for unordered list and 3 for the ordered
  //  - inherit: Use the configured tab size of the current document (see vscode status bar)
  "markdown.extension.list.indentationSize": "adaptive"
```

All three search terms appear in this snippet. However, VSCode doesn't find it:

<img width="772" alt="screenshot 2019-01-29 at 13 44 06" src="https://user-images.githubusercontent.com/101152/51909542-340c4d00-23cd-11e9-90f0-321f6b0e7a80.png">

Is it because the term "tab size" is only in a value description? In any case, from a human point of view, the setting should almost certainly come up with the search terms I'm using, right?

**Comment by rzhao271** [comment]
Closing as that setting doesn't exist anymore and because we have newer search providers now.
