### ISSUE TITLE
Highlighted match is not visible 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67392]
Testing #67274

- `workbench.list.keyboardNavigation: "highlight"`
- Open VS Code repository/folder
- Open file `src/vs/workbench/parts/preferences/common/preferences.ts`
- Scroll the file explorer to the top so that the entry is not shown in the view
- Now type for that file - `preferences`

🐛 Highlighted entry is not shown in the view
Expected to reveal the first known highlighted entry

![image](https://user-images.githubusercontent.com/10746682/51906779-38346c80-23c5-11e9-85cd-cc9bb54f03fa.png)

**Comment by joaomoreno** [comment]
#67083
