### ISSUE TITLE
Up and Down arrow is navigating in explorer tree 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67395]
Testing #67274

- Open VS Code repo
- Type `preferences` in explorer tree
- Up and down arrow navigates to results
- Change the `workbench.list.keyboardNavigation` to `simple`
- Type `preferences` in explorer tree
🐛 Up and down arrow does not work

![kapture 2019-01-29 at 13 45 28](https://user-images.githubusercontent.com/10746682/51909172-3c17bd00-23cc-11e9-99e8-58dad9e33d04.gif)

**Comment by joaomoreno** [comment]
Great catch!!
