### ISSUE TITLE
Enter to navigate highlighted results

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67394]
Testing #67274

- Start typing in explorer tree
- Now press enter

Rename appears. I would expect to navigate at least.

![kapture 2019-01-29 at 13 04 57](https://user-images.githubusercontent.com/10746682/51907268-96158400-23c6-11e9-9932-d05dca789db5.gif)

**Comment by joaomoreno** [comment]
The action to open on macOS is Cmd Down, just like Finder.
