### ISSUE TITLE
Integrated terminal cursor is not centered vertically

### ISSUE THREAD

**Issue by lolimay** [Microsoft/vscode#67405]
- VSCode Version: 1.3.02
- OS Version: Linux deepin 15.9
- VS Code Integrated terminal screenshot

![image](https://user-images.githubusercontent.com/32427260/51911936-03003c80-240e-11e9-82e3-abd924ed4057.png)

- deepin terminal screenshot

![image](https://user-images.githubusercontent.com/32427260/51911984-21663800-240e-11e9-8039-a0e201778c8c.png)

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
This is related to the default font on your distro is offset, selecting a different font should fix it
