### ISSUE TITLE
Integrated terminal wraps incorrectly

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6740]
Testing #6654 

* Resize the window to make the width pretty small
* Type 12345678901234567890
* Observe portions of the text not displaying

![terminal-wrapping](https://cloud.githubusercontent.com/assets/5047891/15498304/65d785e4-219f-11e6-8546-d83a071b955a.gif)

**Comment by Tyriar** [comment]
Behavior is different now, the lines are chopped off and not restored when resizing back https://github.com/Microsoft/vscode/issues/8336
