### ISSUE TITLE
Display snippets even if autocompletion is not ready yet

### ISSUE THREAD

**Issue by titouancreach** [microsoft/vscode#67408]
# Problem I encounter
Currently, when autocompletion is not ready, the completion menu shows: "Loading...". 
I work on a large codebase and the autocompletion (provided by tsserver) is very long to show up (about 30s). The problem I encounter is the "Loading..." prevents the snippets to be shown. So this is very painful to wait 30s for a snippet. 

# Possible solution
Maybe, it would be helpful to show items in autompletion menu as they are available. Show first:
  - snippets
  - emmet
  - ...
And when the "real" autocompletion info is ready, append it to the list

Thanks for reading

**Comment by jrieken** [comment]
Fair request and that's actually true for all suggestions, not just snippet-suggestion. E.g. word based suggestion are often there immediately.
