### ISSUE TITLE
Bogus config "channel: manual"

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67407]
re #12817

We now `"update.channel": "manual"` which is so weird. What does "channel" and "manual" mean in this context? It hardly makes sense and I think its time to rename that setting

**Comment by joaomoreno** [comment]
It's always hard to rename settings... so I don't think I'll do that... :cry: 

But we can definitely improve the documentation:

![image](https://user-images.githubusercontent.com/22350/51919290-66c14000-23e3-11e9-89f9-63658cd3c961.png)
![image](https://user-images.githubusercontent.com/22350/51919279-61fc8c00-23e3-11e9-90c5-436f4942118c.png)
![image](https://user-images.githubusercontent.com/22350/51919264-5d37d800-23e3-11e9-8aee-207b9fe4dced.png)

**Comment by jrieken** [comment]
> It's always hard to rename settings...

Are you kidding? It's super easy:

1) remove the schema for the old setting
2) add new setting that defaults to the old setting

I am actually surprised that we don't have some automatic helper util for this

**Comment by joaomoreno** [comment]
Hm... I never did that before.

**Comment by joaomoreno** [comment]
Maybe `update.type`, since there are other `update.*` settings. Or `update.frequency`. `update.trigger`.

Or `update.enabled`? With values `true`, `false`, `manual`.

**Comment by jrieken** [comment]
Yeah, dislike the `workbench` prefix. It always smells like our internal names leak to customers. :+1: for `update.enabled`, just `update`, or `update.mode`. Somehow, `enabled` makes me expect true/false.

**Comment by joaomoreno** [comment]
@jrieken Unfortunately we can't use `update`, since it's a prefix for other settings. I'll use `update.mode` and rename values to `disabled`, `automatic` (default), `manual`.

**Comment by bpasero** [comment]
What is a "setting name migration"?

**Comment by jrieken** [comment]
> users who have manually set update.mode to the default setting or haven't set it at all...

Don't you remove the default value once you remove the schema?

**Comment by bpasero** [comment]
What I have been doing in the past is to support the old setting by reading it, but not by having the schema still in.

**Comment by joaomoreno** [comment]
> Don't you remove the default value once you remove the schema?

@jrieken I need to know it for the new setting, since I can only respect the old setting if the new setting isn't set at all.

> What I have been doing in the past is to support the old setting by reading it, but not by having the schema still in.

@bpasero And you take the old setting value in case the new setting was never set. But how do you distinguish between the new setting never been set vs. being set to its default?

**Comment by bpasero** [comment]
@sandy081 can probably comment to that, I think we have an `inspect` method to find out where a setting is defined.

**Comment by sandy081** [comment]
Yes, You can use `inspect` method 

```ts
inspect<T>(key: string, overrides?: IConfigurationOverrides): {
		default: T,
		user: T,
		workspace?: T,
		workspaceFolder?: T,
		memory?: T,
		value: T,
	};
```

**Comment by joaomoreno** [comment]
This was far from trivial. I've created a util for migrating settings:

https://github.com/Microsoft/vscode/commit/3e70d8c62d80030a56cd4887298e3dca9215a4e4#diff-800a35d2b141a47ddf9bb3008ce1fb4e

cc @jrieken
