### ISSUE TITLE
Incorrect HTML Syntax highlighting on SVG with Line break

### ISSUE THREAD

**Issue by marcelcremer** [Microsoft/vscode#67402]
- VSCode Version:
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Datum: 2019-01-07T22:53:57.820Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Betriebssystem: Windows_NT ia32 10.0.17134

- OS Version: Windows 10

Steps to Reproduce:

Insert the following code in an HTML-File:
```html
<div>
    <svg class="fi">
        <use xlink:href="/assets/feather/feather-sprite.svg#edit" /></svg
        >
</div>
```

Mind the Line break between \<\/svg and \>.

The syntax highlighting will break for everything after the SVG:
![image](https://user-images.githubusercontent.com/6123724/51910574-e9d89b00-23cf-11e9-8c70-fab6e9a0c44a.png)

Found through strange SVG formatting by prettier: https://github.com/prettier/prettier/issues/5541

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This issue was moved to textmate/html.tmbundle#101
