### ISSUE TITLE
Integrated terminal cursor style is still block when the focus is lost

### ISSUE THREAD

**Issue by lolimay** [microsoft/vscode#67410]
I changed integrated terminal cursor style by adding `"terminal.integrated.cursorStyle": "line"` to my user settings file. It works well and the integrated terminal cursor was changed to **line**.
The problem is that the cursor is still **block** when the integrated terminal lost the focus.

Please see the screenshot:

![peek 2019-01-29 21-56](https://user-images.githubusercontent.com/32427260/51913082-b36f4000-2410-11e9-8366-285d132c56bc.gif)

 

- VSCode Version: 1.30.2
- OS Version: Linux deepin 15.9

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is by design, do you have an alternative where you can still see where the cursor is and it's clear it's inactive? What do you expect to happen?

**Comment by lolimay** [comment]
My expectation is the integrated terminal cursor should still be a `line` when it is inactive if you have added `"terminal.integrated.cursorStyle": "line"` to `setting.json`.

The traditional terminal design is that the cursor blinks if the window is activated, and it does not blink if the window is inactive instead of being a `block`.

**Comment by Tyriar** [comment]
I'll open this up for PRs to show the non-blinking alternative for line/underline only when `terminal.integrated.cursorBlinking` is set to true. That should make everyone happy and be able to differentiate focus both for the blinking and non-blinking case.

**Comment by KarandikarMihir** [comment]
@Tyriar Is this taken? Can I give it a shot?

**Comment by Tyriar** [comment]
@KarandikarMihir sure, this will actually be an upstream issue and need to be fixed for both the DOM and canvas renderers:

- https://github.com/xtermjs/xterm.js/blob/db9aa5c88be6d6cbe043098f32467db9f45527dd/src/renderer/dom/DomRendererRowFactory.ts#L65-L76
- https://github.com/xtermjs/xterm.js/blob/db9aa5c88be6d6cbe043098f32467db9f45527dd/src/renderer/CursorRenderLayer.ts#L191-L219

**Comment by mflan48** [comment]
Hi! I'm new here and would like to work on this issue!

**Comment by Tyriar** [comment]
@mflan48 great! The believe the comment above is still relevant 🙂

**Comment by Tyriar** [comment]
Upstream issue https://github.com/xtermjs/xterm.js/issues/2356

**Comment by JeffreyCA** [comment]
I've created a PR to address the upstream issue: https://github.com/xtermjs/xterm.js/pull/2455

**Comment by JeffreyCA** [comment]
> I'll open this up for PRs to show the non-blinking alternative for line/underline only when `terminal.integrated.cursorBlinking` is set to true. That should make everyone happy and be able to differentiate focus both for the blinking and non-blinking case.

Should this behaviour be implemented in upstream or vscode? My change would still show the bar/underline when unfocused and blinking is off.

**Comment by Tyriar** [comment]
@JeffreyCA I'll pull in your change soon and it should work
