### ISSUE TITLE
VSCode overwrites ${LANG} in terminal

### ISSUE THREAD

**Issue by optnfast** [microsoft/vscode#67414]
Issue Type: <b>Bug</b>

My system local is `en_GB.UTF-8`, configured via the `LANG` environment variable. However in a VSCode terminal, I find `LANG=en_US.UTF-8` (which doesn't exist here). There doesn't seem to be any way to correct this but I don't think VSCode should even be setting an incorrect locale in the first place.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 2441)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.34GB (4.22GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
gotemplate|cas|0.3.0
vscode-markdownlint|Dav|0.23.0
python|ms-|2018.12.1
cpptools|ms-|0.21.0
Go|ms-|0.8.0
proto|pet|0.0.2
vscode-docker|Pet|0.5.1
pegs|the|0.0.5
opa|tsa|0.2.0

</details>

**Comment by Tyriar** [comment]
Does setting `terminal.integrated.setLocaleVariables` to false fix it?

**Comment by optnfast** [comment]
As far as I can see it is already set to false, i.e. no, it doesn't fix it.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/65037

**Comment by optnfast** [comment]
Why does it need to mess with the locale anyway?!

**Comment by Tyriar** [comment]
@optnfast because many users haven't configured this correctly and complain about non-English locales being broken.

**Comment by optnfast** [comment]
Err, surely the answer then is that they configure their system to their taste, rather than breaking the locale setting of everyone else?
At the very least it could not set LANG to a locale which doesn't even exist.

**Comment by Tyriar** [comment]
> At the very least it could not set LANG to a locale which doesn't even exist.

@optnfast how do you verify whether a locale exists?

**Comment by optnfast** [comment]
```
rackheath:junk$ cat t.c
#include <locale.h>
#include <stdio.h>

int main(int argc, char **argv) {
  return puts(setlocale(LC_ALL, argv[1]) ? "ok" : "nope") < 0;
}
rackheath:junk$ gcc -o t t.c
rackheath:junk$ ./t en_US.UTF-8
nope
rackheath:junk$ ./t en_GB.UTF-8
ok
rackheath:junk$ 
```

**Comment by Tyriar** [comment]
In v1.39 this will no longer replace if you have a good looking UTF-8 LANG variable
