### ISSUE TITLE
VS Code colors change when switching monitors

### ISSUE THREAD

**Issue by drewhamlett** [Microsoft/vscode#67413]
I think this is related to https://github.com/Microsoft/vscode/issues/65816 but I'm not sure.

- VSCode Version: 1.30.2 Insiders and Stable
- OS Version: 10.14.2

Steps to Reproduce:

1. Launch VS Code on Laptop
2. Close laptop and plug in external monitor
3. Colors will be slightly off in the editor.

These steps could be done reverse too.  Launch on external monitor, switch to laptop.

I have to re launch the editor to get the colors right

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by rv2900** [comment]
Electron version 4.0.x fixed the color profile. I have tried it.
