### ISSUE TITLE
Ctrl+Alt+ keybindings should not be used by default under Windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67411]
Offender:  e  for  `editor.action.autoFix`

**Comment by Tyriar** [comment]
Now it's using the windows key which is also a no-no? Related: https://github.com/Microsoft/vscode/issues/67695

**Comment by mjbvz** [comment]
Dang Joh for stealing cmd+shift+. for breadcrumbs... Let's try alt+shift+. on windows
