### ISSUE TITLE
Total number showing references or definitions count during Go to or Find all references is misleadig

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#6741]
- VSCode Version: Alpha
- OS Version: Windows 8

Steps to Reproduce:
1. In a Typescript (or any project that supports Go to and Find all references), make sure you have a symbol (eg: class) referred more than in one file
2. Go to a file where this symbol is referred and do Find all references
3. A peek dialog is shown with all references and total count.

I see that in the right side of the peek window we have count per files and on the top we have total count. Since on the top, we show file name / path with total count, it is misleading that count is for file. 
Probably we should show the total count also on the right or update the label 

![references](https://cloud.githubusercontent.com/assets/10746682/15498432/edcb66fa-219f-11e6-91ea-d39f8b75054b.PNG)

**Comment by jrieken** [comment]
sort of by design
