### ISSUE TITLE
Badge showing counts per file is clipped in the bottom

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#6742]
- VSCode Version: Alpha
- OS Version: Windows 8

Steps to Reproduce:

1. In the references / go to definition dialog, count badge at the right is clipped in the bottom. See the attached screenshot:

![references](https://cloud.githubusercontent.com/assets/10746682/15498523/3fe7fc0a-21a0-11e6-9be3-12e4c51212ae.PNG)

**Comment by jrieken** [comment]
@sandy081 What editor font setting do you use? It looks very small

**Comment by sandy081** [comment]
Following are my custom user settings:

// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 10,
    "files.autoSave": "afterDelay",
    "editor.renderWhitespace": true
}
