### ISSUE TITLE
Color themes still show in Workbench: Color Theme options after disabling the extension that provides them

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67425]
Found while testing #67283.

Install Material Theme.
See new Material themes in Workbench: Color Theme 🎉
Disable Material Theme.
Still see Material themes in Workbench: Color Theme.

The themes still show up in every place there is a list of them. I'm guessing it's because the extension was already activated and that this is by design, but seems worth checking.

**Comment by aeschli** [comment]
Material theme is a special as it also contains code. Such extensions can not be hot enabled/disabled.
Another theme that has code is VSCodeicons

@alexr00 Can you try with another theme?

**Comment by alexr00** [comment]
Tried with another theme and it works!
