### ISSUE TITLE
Disabling the theme that contains the active theme does not change theme to default

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67426]
Found testing #67283.

Install Material Theme and apply a theme without reloading.
Theme is applied!
Disable Material Theme.
Reload is now required to revert to default theme.

**Comment by alexr00** [comment]
Same for icon theme.

**Comment by aeschli** [comment]
@alexr00 Material Theme is special as it contains code as well and reload is required.
Do you see the same with other themes?

**Comment by alexr00** [comment]
Works for other themes!
