### ISSUE TITLE
With sidebar on the right and grid layout enabled, sidebar viewlet can take up half the window

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67420]
Found testing #67308
![giantviewlet](https://user-images.githubusercontent.com/38270282/51917920-de41a000-23e0-11e9-87f2-2bb8f0f826c1.gif)

**Comment by alexr00** [comment]
Actually, this happens even if the sidebar is on the left.

**Comment by sbatten** [comment]
should be fixed with some changes from @joaomoreno for restore
