### ISSUE TITLE
Toggle editor command does not bring back the editor

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67422]
Found testing #67308.
If I run the toggle editor command it makes the terminal take up the whole editor area. Cool.
If I run the toggle editor command again it does not bring the editor back 😱
The only way to get the editor back was to hit the X on the panel.
But, I still want the terminal visible so ctrl + ` to bring it back.
Now my window looks like this with a giant terminal/panel:
![image](https://user-images.githubusercontent.com/38270282/51918383-c3bbf680-23e1-11e9-9253-1872e48681ab.png)

**Comment by sbatten** [comment]
fixed with https://github.com/Microsoft/vscode/commit/1fb26f9b5791f612e322589383fb99fbcb005e7b
