### ISSUE TITLE
Terminal brakes when opening

### ISSUE THREAD

**Issue by Colin7860** [Microsoft/vscode#67428]
Issue Type: <b>Bug</b>

I changed my setting to run terminal in .cmd for my mac now i cannot change back as i launch the terminal option it just breaks now after reloading additional stuff, i want to change it back to default bash.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
robotf-extension|kmk|1.6.8
python|ms-|2018.12.1
bitbucket-pull-requests|Ram|0.3.3
rf-intellisense|Tom|2.3.0
robotframework|viv|0.1.3

</details>

**Comment by Tyriar** [comment]
What does "in .cmd" mean? The shell is pulled from $SHELL, you can override it in your settings via `terminal.integrated.shell.osx`.

**Comment by Colin7860** [comment]
Hi there,

Issue resolved.
