### ISSUE TITLE
VSCode git sync fails because of tags

### ISSUE THREAD

**Issue by alejandroiglesias** [microsoft/vscode#67424]
Issue Type: <b>Bug</b>

I'm having an issue with the git sync (which uses `--tags`). The project I work on relies on certain tags in order to do some deployments to QA servers. The tags are always the same name but they're constantly pointing to different refs so I get an error in VSCode when I try to sync. Output log:

```
> git pull --tags origin features/LITE-1050-more-options-for-showinfo-param
> git show HEAD:imports/startup/client/scripts/components/sections-layout-cards.component.js
From github.com:mapmelabs/mapme-lite
 * branch              features/LITE-1050-more-options-for-showinfo-param -> FETCH_HEAD
 ! [rejected]          qa2        -> qa2  (would clobber existing tag)
> git show HEAD:imports/startup/client/scripts/components/sections-layout-cards.component.js
```

In order to "fix" it, I need to run `git pull --tags -f` and VSCode sync works until the tags change again. Since I don't need to pull tags, **is there any way to instruct VSCode not to use `--tags` when it pulls?** I already looked in the settings but haven't found anything.
This has been a big drawback for me lately. Thanks.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
vscode-browser-preview|auc|0.2.7
turbo-console-log|Cha|1.2.13
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.6
tslint|eg2|1.0.42
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.7.3
vscode-browser-sync|jas|1.3.1
Angular1|joh|0.2.0
vscode-github|Kni|0.30.1
rainbow-csv|mec|0.8.0
dotenv|mik|1.0.1
ecdc|mit|1.0.5
vscode-attrs-sorter|mrm|2.1.0
vscode-lebab|mrm|2.6.0
vscode-postcss-sorting|mrm|3.0.1
vscode-scss|mrm|0.6.2
vscode-cosmosdb|ms-|0.9.1
azure-account|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.2
vscode-sort-json|ric|1.13.0
annotator|ryu|0.11.0
salesforcedx-vscode-core|sal|44.17.0
salesforcedx-vscode-visualforce|sal|44.17.0
linter-xo|sam|2.3.2
vue-vscode-snippets|sdr|1.3.0
language-stylus|sys|1.11.0
vscode-meteor|vuh|0.1.1
quokka-vscode|Wal|1.0.181
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>

**Comment by nakibmark** [comment]
I have been having this issue as well since they changed the pull command used by VSCode by default and it is making VSCode's Git features nearly unusable for me! Thank you for bringing this up.

**Comment by LRodge** [comment]
Agreed! making git sync unusable on every commit 👎

**Comment by TrevorBurnham** [comment]
PR: #70704
