### ISSUE TITLE
Disable/enable extensions automatically

### ISSUE THREAD

**Issue by yossefEl** [Microsoft/vscode#67429]
VSCode is really great but it takes a lot of RAM and several minutes to start extensions so i'm just **looking for a way to disable and enable extensions automatically to save ressources**.. for example if i'm a working on web development project only installed extensions on 'web developement category' should work and the rest should still disabled, or if i'm working on a flutter project, only extensions related to flutter should be enabled like dart and flutter and flutter snippets...
thank you in advance for your consideration guys, have a niceDay ;

**Comment by sandy081** [comment]
Duplicate of #57548
