### ISSUE TITLE
Dynamic themes: enable a color/icon theme after installation

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67434]
As discussed in the UX channel I suggest that when installing just one file or color theme, it gets enabled automatically.

//cc @egamma

**Comment by aeschli** [comment]
implemented by 823e747e683e4d9b478521af3ea9e86ad3fe2d9f, in todays i-build.

@bpasero Do you want to validate?

- when one or more themes are installed, enable the first of them.
- set the `workbench.color/iconTheme` settings in the scope (user/workspace/ws folder) where the setting is already defined
- remember the theme that was replaced by the installed theme
- when themes are uninstalled, switch back to the theme that was replaced by an installed theme

Same for color themes and icon theme.

**Comment by bpasero** [comment]
@aeschli works great. One minor nit with the extension editor that is a bit unhappy because a large portion of the UI is not adjusting to the theme color after installation:

![peek 2019-01-31 09-38](https://user-images.githubusercontent.com/900690/52041871-f24de480-253b-11e9-94a9-85d079002e3d.gif)

Filed https://github.com/Microsoft/vscode/issues/67628
