### ISSUE TITLE
Allow multiple preLaunchTasks to be defined

### ISSUE THREAD

**Issue by akrantz** [microsoft/vscode#67431]
I would like to be able to have the launch.json preLaunchTask be an array of tasks rather than just one. While it is possible to create a compound task, this requires that the compound task also have a label which pollutes the tasks shown when choosing to run a task. Instead, I would like just have the launch config just be able to launch more than one.

In my scenario, I have tasks defined with labels "Watch", and "Dev Server". On debug launch, I want to be able to both ensure the Watch and "Dev Server" tasks have started (if not already running).

**Comment by isidorn** [comment]
@akrantz this is a fair feature request.

@alexr00 would this be possible by using task groups? For example the user would put "Watch", and "Dev Server" in one task group and then reference that task group from the preLaunchTask?

**Comment by alexr00** [comment]
The only way this is possible right now is with a compound task (`dependsOn`). The group is not exposed in this way for preLaunchTask. How would we know if the value of preLaunchTask is a group or a task name/label.

**Comment by akrantz** [comment]
You can see an example of how preLaunchTask is currently being used here: https://github.com/OfficeDev/Excel-Custom-Functions/tree/master/.vscode

I had made this feature request because while I was able to do things with preLaunchTask, it pointed out that it would be better to be able to have multiple preLaunchTasks. The reason is that the complexity can easily get out of hand in the task definitions if you want different launch configs with different preLaunchTask combinations and you then have to define compound tasks for them all.

**Comment by akrantz** [comment]
In the example above, we've documented that users should run Watch themselves first, and the Dev Server task is optional because the "office-addin-debugging start" command will start the dev server if not running. However, it would be more ideal if we could add DevServer and Watch to the preLaunchTask so they would both be run first, followed by the current preLaunchTask which starts debugging.

**Comment by isidorn** [comment]
Please note that this is now possible https://github.com/microsoft/vscode/issues/45676
It does not give you 100% what you want but might help

**Comment by royhershkovitz** [comment]
https://stackoverflow.com/questions/51599106/visual-studio-code-running-prelaunchtask-with-multiple-tasks
hey it should work for you.

In addition-if you are using unix command line then you can put as text in the args the rest of the tasks separated with ';' to be execute sequentially.

**Comment by codeoflin** [comment]
I need this too

**Comment by LunkwillAndFook** [comment]
Please make postDebugTasks work with multiple as well (this makes sense if preLaunchTasks will support it).

**Comment by akrantz** [comment]
@isidorn While I respect the VS Code team's decision as to whether it is reasonable to implement, is it possible to get information about why it was considered "out of scope"? Is this a problem with the request itself, or do resource or schedule constraints simply preclude this from being done? It would be nice to have more of your thoughts about this. Thanks.

**Comment by isidorn** [comment]
Sure. I consider this out of scope because as a workaround a user can use compound tasks and than depend on the compound task from the prelaunch task. While I guess this is not ideal, I think it brings a kind of workaround.
Also I have no plans to work on this area in the immediate future.

**Comment by akrantz** [comment]
@isidorn Sure, compound tasks can be used but what I tried to point out is that it does lead to problems. Is this something where an outside contributor could do the work? It seems you have the expertise here but you don't view it as a priority -- which I can understand -- but I am wondering if it would be realistic to have someone else look to doing the work if it is important enough to them.

**Comment by ssmall** [comment]
I know this has already been closed over a year go, but my team (https://github.com/GoogleCloudPlatform/cloud-code-vscode) is is being seriously hindered by the lack of support for multiple preLaunchTasks. We are using the workaround suggested in https://github.com/microsoft/vscode/issues/67431#issuecomment-666481125 but it is haphazard and error prone. If the VSCode team would reconsider the decision to ignore this feature request, we would greatly appreciate it!
