### ISSUE TITLE
Terminal incremental search doesn't handle shortening search term sometimes

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#67438]
- VSCode Version: 1.31 Insiders
- OS Version: Windows 10

Found during testing of https://github.com/Microsoft/vscode/issues/67307

Steps to Reproduce:

1. Add "asdfasdf" text to the terminal.
2. Search for "asdf" and match is found.
3. Search for "asdfx" and match is not found.
4. Backspace in search box to remove the 'x' so back to "asdf".

Match is not found. If you then remove 'f', match for "adf" is found.

**Comment by skyway777** [comment]
Just created a PR into xterm.js repo
