### ISSUE TITLE
TypeError: Cannot read property 'displayParts' of undefined

### ISSUE THREAD

**Issue by ewingrj** [Microsoft/vscode#67430]
Issue Type: <b>Bug</b>

I'm not exactly sure how to reproduce this, but it happens often and the editor becomes really slow.

It seems to happen when intellisense is opened.

It appears to be a "core" extension, thus why I'm filing the bug report here.

```
[2019-01-29 08:51:15.908] [exthost] [error] TypeError: Cannot read property 'displayParts' of undefined
	at w.resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:99172)
	at <anonymous>
```

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.4.1
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
solidity|Jua|0.0.49
auto-comment-blocks|kev|1.0.1
vscode-cosmosdb|ms-|0.9.1
azure-account|ms-|0.8.0
Go|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.6.2
code-spell-checker|str|1.6.10
vim|vsc|1.0.3
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.0.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ewingrj** [comment]
also, to reproduce try:

1. Edit JSX file
2. insert a tag `<div>`
3. Delete the autofilled closing tag
4. Insert the closing tag `</d`

At that point intellisense pops ups and the error appears in the logs.

I thought this was causing an issue w/ extensions freezing after this error occurred, but it was another extension that caused the freezing.

However this error still appears in the logs, so may be confusing to users
