### ISSUE TITLE
Cut item in explorer does not pass color contrast ratio

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#67436]
Refs: #66485

See `.editorconfig`:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/35271042/51929143-5e014780-23ac-11e9-9e6f-543bab1a0227.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/35271042/51929175-6c4f6380-23ac-11e9-8606-201775fa5ed7.png">

Note: "ignored" folders use `#8c8c8c` which barely pass the minimum, to give you an idea. We'd at least need to match that.

**Comment by isidorn** [comment]
Yeah we can use that color. Nice catch
