### ISSUE TITLE
Accessibility actions not accurate in file explorer when a file is selected

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#67448]
Refs: #66485

Unsure if this is related to the macOS screen reader (voice over) or whether the wrong labels, but the screen reader prompts me to use `Control + Option + Shift + Down Arrow` to navigate into a table (which i am not in). It also doesn't tell me how to open the file, which I assumed it would (it's typically enter).

![image](https://user-images.githubusercontent.com/35271042/51930585-c4d43000-23af-11e9-81b8-9e7fe1b72742.png)

**Comment by isidorn** [comment]
@misolori do you also see this in vscode stable?

**Comment by misolori** [comment]
Yes, this appears in stable as well so it's likely a problem we've previously had.

**Comment by isidorn** [comment]
This is Voice OVer behavior and I think you get more details when you change the Voice Over verbosity. Closing as designed
