### ISSUE TITLE
Contextual actions hard to reach with horizontal scrolling enabled

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67447]
Issue Type: <b>Bug</b>

Testing #67275

It's not enough to hover over the row, you have to scroll all the way to the right to reach the toolbar on the row. Can we place the toolbar always inside the visible area?

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:14:22.700Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.77GB (0.14GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
beautify|Hoo|1.4.7
theme-karyfoundation-themes|kar|18.2.1
azure-account|ms-|0.8.0
lsp-inspector|oct|0.0.1
vscode-open-in-github|sys|1.10.1
ayu|tea|0.17.0

</details>

**Comment by joaomoreno** [comment]
This was a known limitation already with the horizontal scrolling feature on the old tree. It was documented at the time. If you want that fixed, please submit issues for each area since the tree does not control what people render inside each element.
