### ISSUE TITLE
Explorer filter is unintuitive to Windows users

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#67440]
https://github.com/Microsoft/vscode/issues/66485

Just a suggestion, might be by design. I thought it was weird when I did this:

1. Filter
2. Click to expand an unrelated item
3. Press down

**Comment by isidorn** [comment]
This is a general tree question. Also assigning to @joaomoreno

**Comment by joaomoreno** [comment]
I wouldn't say it should... but I can take more opinions.

**Comment by Tyriar** [comment]
As a side note, I don't plan on using this feature as I want an exact prefix matcher like how explorer works as @joaomoreno and I have talked about.

**Comment by joaomoreno** [comment]
@Tyriar https://github.com/Microsoft/vscode/issues/66913

**Comment by isidorn** [comment]
Should we just close this?

**Comment by Tyriar** [comment]
I think my underlying issue is that I want the filter to be a very temporary thing, purely to jump to the folder I'm interested in. Right now whenever I use this I need to type "foldername", press enter and then escape to move focus to the folder. What I would like to be able to do is type "foldername" see that the folder is focused and press right to start navigating through it.

**Comment by Tyriar** [comment]
I still think that the current tree filter is not what a lot of people including me would want. I want exactly what Windows Explorer does, specifically:

- No fuzzy finding, I'm strictly searching from the start of the folder/file
- The search term goes away a couple of seconds after I stopped typing so I don't need to worry about clearing the filter (or when the level changes)
- The filter should not affect how up/down work

The current way filter messed with muscle memory because it changes up/down and makes it hard to chain together filters as you need to clear it every time.

Reopening as it still warrants further discussion imo.

**Comment by gjsjohnmurray** [comment]
@Tyriar would the title of this be better as 'Explorer filter is **un**intuitive to Windows users' ?
