### ISSUE TITLE
Filter on type behavior is unexpected

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67445]
#66485

Repro:

Turn filter on type on

Click node_modules

![image](https://user-images.githubusercontent.com/2193314/51930317-2778fc00-23af-11e9-9442-5bf578a03a17.png)

Type node-pty

![image](https://user-images.githubusercontent.com/2193314/51930343-2ea00a00-23af-11e9-856e-5185392a4358.png)

Press down to select the entry, press enter to make sure it's selected, press it again to expand:

![image](https://user-images.githubusercontent.com/2193314/51930386-51cab980-23af-11e9-813e-16ff14245403.png)

Press escape

![image](https://user-images.githubusercontent.com/2193314/51930395-58593100-23af-11e9-900b-11b479b41eaf.png)

I get the impression I'm meant to search for files but this isn't what I was expecting. I thought that it would include all sub-nodes of matching items.

Also pressing escape in this view should reveal the focused item

**Comment by joaomoreno** [comment]
> I get the impression I'm meant to search for files but this isn't what I was expecting. I thought that it would include all sub-nodes of matching items.

https://github.com/Microsoft/vscode/issues/66971#issuecomment-458023065

> Also pressing escape in this view should reveal the focused item

👍

**Comment by joaomoreno** [comment]
Fixed.
