### ISSUE TITLE
Add theme keys for explorer filter

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67446]
#66485

It appears right now it's using `editor.findMatchHighlightBackground`. It should have its own value since the viewlet has a different background color in most themes. It might also not have good contrast with the list selection color. It should probably live under the list. namespace.

**Comment by joaomoreno** [comment]
That's already in:

https://github.com/Microsoft/vscode/blob/b21209d92c4934dc0a3664a71a36c1acc9a2f20a/src/vs/platform/theme/common/styler.ts#L226-L230

**Comment by Tyriar** [comment]
@joaomoreno ?

![image](https://user-images.githubusercontent.com/2193314/51939510-8006c400-23c4-11e9-9e05-c16679f0a443.png)

**Comment by joaomoreno** [comment]
Oh there are more places to register 🤦‍♂️

**Comment by Tyriar** [comment]
I'm not sure we should have a extra shadow key here but rather use `widget.shadow`, @bpasero please advise.

Also I don't think there is a theme key for the match highlighting with the list? It still uses `editor.findMatchHighlightBackground`?

**Comment by alexr00** [comment]
@joaomoreno, I still don't see the theme key for the match highlighting within the list.

**Comment by Tyriar** [comment]
@alexr00 we had a chat on Slack, problems shares the highlight color in the list as well, let's consider theming the list a separate feature https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/customView.ts#L616
