### ISSUE TITLE
Multi-line diagnostics: Move 'source(code) [ln, col]' to the right

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67455]
Issue Type: <b>Bug</b>

Testing  #67255

It feels like it should be placed more to the right, such that it stands out similarly to the single-line case:
![image](https://user-images.githubusercontent.com/9205389/51932584-bb72b400-23ff-11e9-91fb-b2851959d145.png)

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none

**Comment by sandy081** [comment]
Showing at the end of the message is consistent with other places. This is how a real multiline message looks like

![image](https://user-images.githubusercontent.com/10746682/51946510-0998af00-2422-11e9-8801-c7223b0c8c8d.png)
