### ISSUE TITLE
Setting UI for color theme is not updated correctly

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67459]
Testing #67283

- Install Nord theme and Material Theme
- Use Nord
- Disable Nord extension
- VS Code falls back to Dark+ color theme
- Setting UI shows Color Theme: Material Theme despite in Dark+ theme (In plain text editor, the value is still `Nord`:

![image](https://user-images.githubusercontent.com/4033249/51933221-a4a76f80-23b5-11e9-8829-2987ca9249f6.png)

![image](https://user-images.githubusercontent.com/4033249/51933168-8ccfeb80-23b5-11e9-8ee9-efc7a768fda7.png)

**Comment by aeschli** [comment]
I did that intentional, in case you just enable the extension again. But I guess this can be discussed

**Comment by aeschli** [comment]
fixed by 823e747
