### ISSUE TITLE
Feature: support Chrome console extensions in debug console output

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#6745]
Chrome has been supporting some nice improvements for the console, like:
- console.group('foo'): starts to group console content
- console.groupEnd('foo') stops the 'foo' group

As well as colors inside console text using c-like printf parameters where you may specify css styling:

console.log('Controller: %c%s', 'color:#008;', $route.current.$$route.controller); 

This results in much more readable console output:

![consolechrome](https://cloud.githubusercontent.com/assets/199648/15498841/93761fb8-21a1-11e6-8b23-31e70e9d15f3.png)

Since VSCode does not parse these layout/color instructions, the end result is barely readable:

![vscodeconsole](https://cloud.githubusercontent.com/assets/199648/15498867/b9f36e34-21a1-11e6-9efd-9f67623e9b6a.png)

**Comment by eppsilon** [comment]
Firefox and Safari support styling console output too. As a temporary fix, VS Code could just ignore `%c` tokens and their associated values - then the log messages would be readable.

**Comment by jonaskello** [comment]
I use redux-logger to log actions in redux and it's output looks good in chrome but not so much in vscode. Is there a way I could write an extension that can format the output in the debug console?

**Comment by weinand** [comment]
@jonaskello no, this is not yet possible (and this item covers this feature request).

**Comment by jonaskello** [comment]
Thanks! So any news on the status of this issue? is it under discussion or would you accept a PR to implement this? Should debug output formatting be extensible by third party plug-ins or should chrome console formatting be built in?
