### ISSUE TITLE
Duplicate options in settings UI for themes when disabling a theme

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#67452]
Testing #67283

- Use Nord theme
- Setting looks alright:
  ![image](https://user-images.githubusercontent.com/4033249/51932004-1af6a280-23b3-11e9-80d3-f2d6f2ebe930.png)
- Disable nord theme
- :bug:
  ![image](https://user-images.githubusercontent.com/4033249/51932057-35c91700-23b3-11e9-9cd8-f3591b850f64.png)

**Comment by aeschli** [comment]
It's a issue with the settings UI. It needs to listen to schema changes 

IConfigurationRegistry.onDidSchemaChange

**Comment by alexr00** [comment]
I'm still seeing the color theme drop down include extension themes when I uninstall the extension. If I close and re-open the settings UI then the drop down correctly does not have the themes.

**Comment by roblourens** [comment]
Yeah I see it's still an issue with search results sometimes. Notes for myself

- In onConfigUpdate, we trigger a search again to rebuild the results for the new config
- But for some reason, when many extensions are installed and one gets disabled, onDidSchemaChange is triggered multiple times, and after the first instance, colorTheme still has the theme of the disabled extension
- The search is debounced, so after multiple updates in a row, the search results might not be updated with the most recent version of the setting (?)

**Comment by roblourens** [comment]
I think the only remaining issue is that when I disable the theme, it isn't removed from the setting list in search results. This is vaguely annoying but a pain to fix currently and I'm just going to close this.

**Comment by roblourens** [comment]
Actually this was fixed by 3006b97f30e0b8ec1cfe6fea490b314412b30cdf
