### ISSUE TITLE
Explorer filter box style issues

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#67451]
#66485

![image](https://user-images.githubusercontent.com/2193314/51930902-72dfda00-23b0-11e9-8226-437c61260771.png)

![image](https://user-images.githubusercontent.com/2193314/51930970-9a36a700-23b0-11e9-84eb-5b15c16706f1.png)

![image](https://user-images.githubusercontent.com/2193314/51931631-30b79800-23b2-11e9-8b71-e6a1ea7c8cdc.png)

![image](https://user-images.githubusercontent.com/2193314/51931642-37dea600-23b2-11e9-9f86-954876dcb9f2.png)

![image](https://user-images.githubusercontent.com/2193314/51931734-6d838f00-23b2-11e9-85b6-1dcbd96a572b.png)

![image](https://user-images.githubusercontent.com/2193314/51931748-74aa9d00-23b2-11e9-84ec-67bdc70d2291.png)

Some observations:

- Both the list highlight and the filter box in the top-right are based on `editor.findMatchHighlightBackground`, but the filter box is far darker
- The filter box has a 45 degree drop shadow, I don't think we do this anywhere
- The filter box has rounded edges
- The icons are very blurry and not vertically aligned
- The filter options were very difficult to discover, I would not have come across them if I wasn't testing the feature

This is a similar UI component we have which maybe we should copy some style from?

![image](https://user-images.githubusercontent.com/2193314/51931185-10d3a480-23b1-11e9-9163-1cc94adf1d7c.png)

![image](https://user-images.githubusercontent.com/2193314/51931208-19c47600-23b1-11e9-917b-d996a7684441.png)

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/51932261-a96b2400-23b3-11e9-8960-e7daa9898c63.png)

Another one: Where does this orange border color come from?

**Comment by joaomoreno** [comment]
>  is far faster

faster?

Yeah I like the idea of copying from

![img](https://user-images.githubusercontent.com/2193314/51931185-10d3a480-23b1-11e9-9163-1cc94adf1d7c.png)

> The icons are very blurry and not vertically aligned

@misolori had some ideas for the icons. Also, are you zoomed in/out?

> Another one: Where does this orange border color come from?

It comes when there are no matches. Theme key is `listNoMatchesOutline`.

**Comment by Tyriar** [comment]
> faster?

darker*

> Also, are you zoomed in/out?

I was at zoomLevel -1, it's still much blurrier than the x on zoomLevel 0:

![image](https://user-images.githubusercontent.com/2193314/51939735-0f13dc00-23c5-11e9-83c6-c4d1fd661267.png)


> It comes when there are no matches. Theme key is listNoMatchesOutline.

See https://github.com/Microsoft/vscode/issues/67446#issuecomment-458701876

**Comment by misolori** [comment]
@joaomoreno I can explore some icons for that and fix the sizing/blur, will make a PR for it

**Comment by cawoodm** [comment]
I'm sorry to ask this here but: WHERE is there a filter box in the explorer view? The exact feature I've been trying to find for an hour and which led me here...

![image](https://user-images.githubusercontent.com/498834/54821058-6e91b800-4ca1-11e9-8638-12a10585edf6.png)

**Comment by Tyriar** [comment]
@cawoodm click on a folder in the explorer and start typing

**Comment by joaomoreno** [comment]
@Tyriar Mind if we close this?

**Comment by Tyriar** [comment]
The only remaining problems I still see are the drop shadow and rounded edges look out of place, deferring to @misolori for these last bits.

**Comment by misolori** [comment]
The rounded edges match the labels styles we have in other places:

![image](https://user-images.githubusercontent.com/35271042/98302458-45569600-1f71-11eb-8e4f-49d564ab530b.png)

And shadow uses the same color token as `widget.shadow` so I think we're fine closing this.
