### ISSUE TITLE
Material Theme octicons are not in color on Linux

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67457]
Testing #66229

- Install material theme extension, see its commands:

Linux: 
![image](https://user-images.githubusercontent.com/323878/51932826-ce13cb80-23b4-11e9-80d3-dff79db4ffee.png)

Mac:
![image](https://user-images.githubusercontent.com/323878/51932798-c2280980-23b4-11e9-8a77-9575a1631a62.png)

**Comment by roblourens** [comment]
Maybe these are just emoji and not octicons

**Comment by misolori** [comment]
Yea, those are system emojis and not octicons (didn't know you could use emojis). Same would apply on Windows.

**Comment by auchenberg** [comment]
Shows up in color in Windows using system emojies.
