### ISSUE TITLE
Disabling an icon theme still shows it in `Preferences: Select Icon Theme`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67467]
Testing #67283 

Although I have disabled the theme:

![image](https://user-images.githubusercontent.com/4033249/51934483-8d1db600-23b8-11e9-8ea2-2f948e537c63.png)

![image](https://user-images.githubusercontent.com/4033249/51934459-7e370380-23b8-11e9-8f98-48b88bdff73d.png)

**Comment by octref** [comment]
Also, the icon on file explorer is still Material Theme Icon:

![image](https://user-images.githubusercontent.com/4033249/51934534-aaeb1b00-23b8-11e9-9466-ecccfec251d8.png)

**Comment by aeschli** [comment]
The material theme is special as it contains code. Reloading is required to update the UI (as shown in https://github.com/Microsoft/vscode/issues/67466)
