### ISSUE TITLE
Feature: add jump to file and line number to debug console output

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#6746]
In Chrome (& Edge) console, when something is printed, the file + line number where it occured is printed, and clicking on it opens up the corresponding file at the correct position.

![consolechromefile](https://cloud.githubusercontent.com/assets/199648/15499063/842fe33a-21a2-11e6-91b7-6165b3b4f95e.png)

In VSCode you get no such information: the log is printed without any information.

**Comment by aeschli** [comment]
Can you add a screenshot that shows where you would like to get that information?

**Comment by aeschli** [comment]
I assume this is about printing in the console view.

**Comment by isidorn** [comment]
Assigning first to @weinand to see if we can extend the protocal such that output events could have source and line. If we have that the debug console could render this source to the side like chrome does it

**Comment by weinand** [comment]
Extending the protocol is easy. But before we do this we need some evidence that debug adapters can actually provide that information.
In case of node.js I do not see a way to provide source and line information. `console.log()` statements in the debuggee result in information sent to stdout (or stderr) which is picked up by the debug adapter and sent as OutputEvents to VS Code. The debug adapter has no way to add source and line information by itself. Only an enhanced version of `console.log()` in the debuggee could get source and line position from the callstack and add this to the output data. 
 
@roblourens, @felixfbecker, @rebornix could you provide source and line information for anything sent as OutputEvents?

**Comment by felixfbecker** [comment]
No, I only read stdout/stderr stream. And that is only for CLI apps, webapps don't even have stdout/stderr

**Comment by rebornix** [comment]
I'm just directing the console output to OutputEvent, there is no such line information...

**Comment by roblourens** [comment]
Yeah, the Chrome debug protocol provides the URL/line/column of the source of the log message. I could easily resolve the URL to the original path and pass that back.

**Comment by SamiChab** [comment]
This would be really great if you could add this feature!! Apart from that issue, debugging with Code is really nice

**Comment by roblourens** [comment]
This is actually implemented for the next release, https://github.com/Microsoft/vscode/issues/24490
