### ISSUE TITLE
Enter behaves strange when a filter is active in the explorer

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67460]
#66485

Repro:

Open mainThreadTerminalService.ts

Reveal in tree

Type "node-pty"

![image](https://user-images.githubusercontent.com/2193314/51933366-02d45280-23b6-11e9-896b-fb1ace9b9113.png)

Press enter

![image](https://user-images.githubusercontent.com/2193314/51933408-1f708a80-23b6-11e9-92c8-5464e68a1658.png)

Press enter

![image](https://user-images.githubusercontent.com/2193314/51933429-27302f00-23b6-11e9-8c44-44b2e629eed0.png)

**Comment by Tyriar** [comment]
This was Windows

**Comment by joaomoreno** [comment]
I'm gonna close this as a consequence of not revealing the element: #67083
