### ISSUE TITLE
Alt+click in explorer doesn't expand recursively

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67464]
#66485

It seems like it only follows the first child or something?

Normal click:

![image](https://user-images.githubusercontent.com/2193314/51933796-f8668880-23b6-11e9-890a-c25049e5c099.png)

Alt+click:

![image](https://user-images.githubusercontent.com/2193314/51933750-dd941400-23b6-11e9-8ee7-be793f8c07c6.png)

**Comment by Tyriar** [comment]
It also seems inconsistent as well, the next time I tried it only expanded addons 1 level (not attach)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/66811
