### ISSUE TITLE
Multi-line diagnostics: Arrows when showing related information

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67461]
Issue Type: <b>Bug</b>

The 3 (!) arrows are hard to read:
![image](https://user-images.githubusercontent.com/9205389/51933270-31c3e600-2401-11e9-82b7-f2f6c0d5a1d4.png)

Should the second tree node's arrow be top-align to the node? 

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none

**Comment by sandy081** [comment]
Aligning to the top will make it confused with toggling multiline message action. I would prefer to have like now.
