### ISSUE TITLE
Change file association is doing too many things at once and it is not clear what's going on

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6747]
Testing #6657 

IMHO the experience is bad. Clicking this action pops over two message boxes and does an edit in an untracked file that gets autosaved immediately.

IMHO this should show a preview of what it will do before jumping in and doing it and not pop over 2 message boxes! Preferably it would select the new added text.

![association-insane](https://cloud.githubusercontent.com/assets/5047891/15499131/d515a942-21a2-11e6-8790-fdec374a61eb.gif)

**Comment by bpasero** [comment]
I am opting for now showing settings at all...

**Comment by bpasero** [comment]
We reverted the change in favour of the real solution which needs more work and is outlined in https://github.com/Microsoft/vscode/issues/6789
