### ISSUE TITLE
Installing, enabling then uninstalling an Icon Theme do not disable the Icon Theme

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67470]
Testing #67283.

- Install VS Code Icons
- Select VS Code Icons
- So far, so good

![image](https://user-images.githubusercontent.com/4033249/51935131-0c5fb980-23ba-11e9-8b19-43e24a1143aa.png)

- Uninstall VS Code Icons
- VS Code suggests "Reload", and file icons are still "VS Code Icons"

![image](https://user-images.githubusercontent.com/4033249/51935160-239ea700-23ba-11e9-8b34-752c54d692c2.png)

This works fine for Color Themes.

**Comment by aeschli** [comment]
VS Code Icons is special as it contains code... Reload is required.
