### ISSUE TITLE
Terminal rendering failure

### ISSUE THREAD

**Issue by galich** [Microsoft/vscode#67475]
Issue Type: <b>Bug</b>

Quite often after opening terminal (both cmd.exe and powershell.exe on Windows) it shows nothing until scrolled or ENTER is hit. It feels like initial batch of content fails to render.

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:20:23.551Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (21.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by galich** [comment]
similar to https://github.com/Microsoft/vscode/issues/67313

![image](https://user-images.githubusercontent.com/3718155/51936117-75a0f600-23d5-11e9-9b2f-001f5fcce2bc.png)

![image](https://user-images.githubusercontent.com/3718155/51936128-7cc80400-23d5-11e9-9733-896cd603d0df.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
