### ISSUE TITLE
Platform specific workspace settings

### ISSUE THREAD

**Issue by chparimi** [Microsoft/vscode#67476]
We work on projects or repositories where part of the code is cross platform (Windows/Linux) and rest is limited to one platform (Windows). Now I want to have workspace settings on Linux that would filter out all the Windows files that are not cross platform relevant. Whereas on Windows I would like to have those files appearing in the project apart from the cross platform code.

Can we have platform specific `files.associations` and `files.exclude` in workspace settings to allow this? If there is an alternative for this please do tell.

**Comment by chparimi** [comment]
**5595** is for key bindings. This is for **Workspace Settings**

**Comment by sandy081** [comment]
@chparimi #5595 is to support platform specific settings which you are also asking for.
