### ISSUE TITLE
Settings editor search links don't work if option currently filtered out

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#67479]
- VSCode Version: 1.31 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Filter down Settings editor with "double".
2. Window: Double Click Icon To Close has a link to Window: Title Bar Style
3. Click the link.

Settings editor goes back to starting view (Commonly Used) and doesn't find Window: Title Bar Style.

If no filtering is applied, clicking the link goes to Title Bar Style and correctly displays the gear icon. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Fixed last month
