### ISSUE TITLE
Intellisense for variable declarations

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6748]
From testing #6656

``` css
:root {
  --foo: // code assist hee


}
```

Code assist could show possible values such as colors, numbers

**Comment by sandy081** [comment]
Looks like this has to be supported across CSS, SASS and LESS.

**Comment by pim013** [comment]
The referenced issues don't make sense to me. Any update on this? This one is currently holding me back from transferring to VSCode form PHPStorm.

**Comment by aeschli** [comment]
@pim013 Just to make sure, is it this issue that holds you back?

**Comment by octref** [comment]
For variables the values can be literally anything. I don't think it's possible to provide any reasonable suggestions over here.
