### ISSUE TITLE
"Hot" installing the GitHub Pull Request extension results in a blocked proposed API activation error

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67481]
Notice no SCM view and no status bar entry:

![image](https://user-images.githubusercontent.com/2193314/51937298-25b73480-23bf-11e9-8e78-4d50c53eaa7c.png)

After reload via command palette:

![image](https://user-images.githubusercontent.com/2193314/51937338-3c5d8b80-23bf-11e9-97ef-a4afcf076648.png)

**Comment by sandy081** [comment]
@alexandrudima I see following error while installing github pull requests extension

![image](https://user-images.githubusercontent.com/10746682/51943023-c423b400-2418-11e9-8aae-edd18aeeeed8.png)

Looks like we are not massaging the extension for proposed api flags upon adding.

**Comment by alexandrudima** [comment]
This might share the same root cause as #67326

**Comment by Tyriar** [comment]
I don't think I saw a notification pop up

**Comment by alexandrudima** [comment]
Yes, this is fixed also by updating the trie (Done for #67326), but I'd still like another person to verify please.

**Comment by sandy081** [comment]
Verified - I do not see the notification and the extension is running (view is shown)
