### ISSUE TITLE
cannot update Node debug

### ISSUE THREAD

**Issue by MAXMASTER001** [Microsoft/vscode#67486]
cannot update Node debug. I think this gievs me the error "Debug adapter process has terminated unexpectedly (exit code: 1)"

![image](https://user-images.githubusercontent.com/11816983/49395763-748e7800-f748-11e8-9c78-287f9085cf21.png)

**Comment by weinand** [comment]
@sandy081 We'll have to investigate this issue. More users are seeing this.

**Comment by sandy081** [comment]
Duplicate of #66774
