### ISSUE TITLE
Invalid index while arrowing through settings TOC

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67492]
Issue Type: <b>Bug</b>

Testing #67304

**Repo**
1. Open settings editor
1. Search `zoom`
1. Focus the toc
1. Hit right arrow to go through toc to the last entry. Press right arrow again

**Bug**
Pressing right arrow on the last item results in:

```
  ERR Invalid index 2: Error: Invalid index 2
    at e.reveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:886:493)
    at t.e.onRightArrow (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1016:460)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:76:205
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:996
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:76:205
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:81:312)
    at HTMLDivElement.r (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87:1001)
```

Possibly related #67233

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|-psn_0_19362422|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by roblourens** [comment]
This is a general tree issue

- Apply a filter to a tree
- Select an element with filtered-out children
- Press right arrow

I can also repro this in the explorer. I select `clojure` and press right and get `Error: Invalid index -1`

![image](https://user-images.githubusercontent.com/323878/52031802-1f19e180-24d3-11e9-816a-4f9eca433e62.png)
