### ISSUE TITLE
Selected tree item is using wrong color

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67497]
Testing #67302

New tree:

![image](https://user-images.githubusercontent.com/4033249/51943086-7c2b6f80-23cd-11e9-8f97-3154338c3870.png)

Old tree:

![image](https://user-images.githubusercontent.com/4033249/51943100-85b4d780-23cd-11e9-9e45-dad78feb5bb5.png)

I'm using Nord theme.

**Comment by roblourens** [comment]
I actually can't repro that, please show me tomorrow
