### ISSUE TITLE
Default smart selection for html should handle self-closing tags

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67490]
Testing #67236.

Currently for `<my-tag />`, the default smart selection would include `my-tag /` as a range, which is not very useful.

The HTML smart selection would provide `my-tag`, `<my-tag />`.

**Comment by jrieken** [comment]
Yeah, understood. The challenge is that the default provider works just with brackets. Best would be to disable this when having another (smart) provider

**Comment by jrieken** [comment]
I have pushed a change that makes sure we don't register the bracket range provider when another (extension) provider exists. In that case only word ranges are used.

**Comment by joaomoreno** [comment]
@jrieken What's a good extension to test this with?

**Comment by jrieken** [comment]
html? the one we bundle with the product

**Comment by joaomoreno** [comment]
I'm not sure what to verify here. There's definitely a difference between txt and html, but @octref's comment doesn't look addressed:

> The HTML smart selection would provide `my-tag`, `<my-tag />`.

![peek 2019-02-01 15-59](https://user-images.githubusercontent.com/22350/52130458-8605da80-263a-11e9-80e6-cf76b981cc14.gif)

Leaving it to @octref to verify.
