### ISSUE TITLE
Don't show twisty in settings editor TOC if there are no subsections

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67494]
Issue Type: <b>Bug</b>

Testing #67304

**Repo**
1. Open settings editor
1. Open `workspace settings`
1. Try exapnding the `Window` section in the TOC by clicking on it

**Bug**
The twisty works but there are no subsections.

There are subsections of `window` in the user settings

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|-psn_0_19362422|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/67315
