### ISSUE TITLE
Proposal: Shrink after initial Expand for sub-word smart selection

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#67496]
Testing #67236.

While thinking about a solution for #67495, I came up with an idea:

- Make the first "Expand Select" to always select the whole word. This is the a preferred behavior for a majority of cases.
- Subsequent "Shrink Select" would use VS Code's built-in smart select to select intra-words
  - `Foo` in `FooBar`
  - `foo` in `foo-bar`
  - `foo` in `foo_bar`
- Language Server is only responsible for handling smart selection beyond word level

@jrieken what do you think?

**Comment by octref** [comment]
An example:

- `FooBa|rBaz`
- Expand
- `FooBarBaz` is selected
- Shrink
- `Bar` is selected

**Comment by jrieken** [comment]
Hm... interesting but it also makes it harder/impossible to go back to the state in which you started.

**Comment by octref** [comment]
Don't think so, when you are on `Foo[BarBaz]` after expand -> shrink, another expand should give you `[FooBarBaz]`.

**Comment by aamarks** [comment]
At the very least shouldn't smart-select honor changes to editor.wordSeparators? If dash is removed from the list then select all of foo-bar first. (Sorry if this is a naive remark, I've searched through some of the smart-select issues for wordSeparators... addSelectionToNextFindMatch also seems to ignore separators setting.)
