### ISSUE TITLE
Default selection should select current word/hump first in camelCase

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67493]
Testing #67236

On the world `AbstractSmartSelect`

- `|AbstractSmartSelect` yields `Abstract`, `AbstractSmart`, `AbstractSmartSelect` 👍 
- `AbstractSmartSele|ct` yields `AbstractSmartSelect` only. IMO it should yield `Select` and `AbstractSmartSelect`
- Similarly `AbstractSma|rtSelect` should yield `Smart` and `AbstractSmartSelect`

**Comment by jrieken** [comment]
Actually not so sure about this anymore. Currently the expansion works left to right, e.g the current position determines what is "preselected" and everything following will be another range. With this proposal it becomes harder to understand, e.g `AbstractSma|rtSelect` with `Smart` and `AbstractSmartSelect` is "inside-out" expansion whereas `Ab|stractSmartSelect`  with `Abstract`, `AbstractSmart`, and `AbstractSmartSelect` is left to right expansion. I don't think that we can both

**Comment by jrieken** [comment]
I have changed things to inside-out approach which makes more sense considering smart select is always about inside-out selection. 

![jan-31-2019 14-48-46](https://user-images.githubusercontent.com/1794099/52058478-cfd1c080-2567-11e9-9646-44782a39144a.gif)
