### ISSUE TITLE
Animated open editors make me open two files on double click

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6749]
#6536

See attached screen shot. 

* find an item in the explorer
* perform a slow double click in the upper part of an item
* two files open (one as preview, one a open file)

![may-24-2016 11-31-44](https://cloud.githubusercontent.com/assets/1794099/15499194/35212988-21a3-11e6-950a-92bb602c0a7f.gif)

**Comment by jrieken** [comment]
this is really annoying.

**Comment by bpasero** [comment]
Yes, drives me nuts as well.

**Comment by bpasero** [comment]
@isidorn moving to you so that we address this very specific to the explorer problem: can we play around with a delay that only applies when you click from the explorer that allows me to still double click without the thing moving down?

**Comment by joaomoreno** [comment]
@bpasero Do you mean delaying the moving down when double clicking?

**Comment by bpasero** [comment]
@joaomoreno yes. this issue is very specific to the explorer only, if you have another idea how to solve it, please let us know,

**Comment by joaomoreno** [comment]
Maybe do not use double click as the action to pin a file, but rather a contextual action in the explorer items or the editor title?

**Comment by bpasero** [comment]
I would only consider that an option if we cannot find a good solution for this problem. There is a global action to pin a file and you can double click on the editor title to pin it. We could add more context menu actions too, but at some point it gets messy there.

**Comment by bpasero** [comment]
@isidorn @joaomoreno I had another idea how to solve this: what if the tree actually adjusts the scrolling position when it is being pushed down by the animation from the "Opened Editors" view? We could keep all the animation and smooth transition if the element under the mouse pointer stays exactly at the same position. Might be as easy as restoring the scroll position right after opening the editor from the mouse-down click in the explorer.

**Comment by joaomoreno** [comment]
There might be animation jank, but worth a try. Up to the tree user.

**Comment by isidorn** [comment]
@bpasero nice idea but this would not work if the tree does not occupy the whole vertical space and there is nowhere to scroll to. 
I think we need a more general solution that would also cover the case with a small tree. Investigating some delayed open editor section expansion

**Comment by isidorn** [comment]
To experiment I have pushed the change that we update the open editors tree with 250ms, this improves the annoying behavior for me. However now there is always lag when the tree gets updated - I did not find this too bad. But it might not be the best idea. Try it out and let me know how it feels.

An alternative was that I just expand the tree with the delay - but the issue there is if I update the tree immedatly and expand after some time temporary a scroll bar gets rendered in the open editors view which is a little pesky.

**Comment by isidorn** [comment]
Though changing the tree behavior that the scroll bar does not get rendered when added if tree does not have focus would make it the delayed expansion a good strategy imho.

**Comment by bpasero** [comment]
@isidorn good point. with the new delay a refresh looks weird though because you do not get an animation but the elements in the view only get visible after like 250ms. So the initial tree input should load instantly.

**Comment by bpasero** [comment]
The delay works for me.
