### ISSUE TITLE
Consider remove the current line smart selection

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67491]
Testing #67236

For normal users, they can use `Fn + Left` + `Fn + Shift + Right` to select whole line.
For Vim users, they can use `V`.
We also have command to delete, move, duplicate current line. These commands cover the majority cases people want to achieve by "selecting current line".

I'm looking through HTML, CSS, JS, JSON, and there aren't many cases where this selection is useful.

**Comment by jrieken** [comment]
Yeah, I took inspiration from how others do it. We could add a setting to enable/disable this?

![jan-30-2019 12-02-48](https://user-images.githubusercontent.com/1794099/51977205-11d70580-2487-11e9-94cd-1095dccbbd50.gif)

**Comment by jrieken** [comment]
So, what might be better is a post processing steps (configurable) that add full line/block selections whenever two ranges differ in start/end lines. Today, only the current line gets this treatment.

**Comment by octref** [comment]
That would work for me.

**Comment by jrieken** [comment]
this fix for https://github.com/Microsoft/vscode/issues/67390 actually implements this. closing as dupe
