### ISSUE TITLE
[C#] colorizer - syntax highlighting error when curly brace in a comment after an assignment

### ISSUE THREAD

**Issue by glennc** [Microsoft/vscode#675]
With the following code:

```c#
var a = 0; // {
```
the `// {` isn't green like the other comments.

**Comment by aeschli** [comment]
For C# tokenization we use the text mate grammar from https://github.com/atom/language-csharp.
I verified that Atom has the same issue, so it's really a grammar issue (and not problem with our text mate engine).
I suggest to file the issue there as well.

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#42

**Comment by aeschli** [comment]
@glennc With just the one line, all looks fine; the comment is in green.
![image](https://cloud.githubusercontent.com/assets/6461412/11484482/7a43731a-97ae-11e5-960c-30b47d5111c4.png)

Same with a more complete example:
```c#
class A {
  foo() {
    var a = 0; // {
    var b = 0; // hello
  }
}
```

Can you give a full example that shows the issue?

**Comment by aeschli** [comment]
Closing. Please add a code example, so I can reopen
