### ISSUE TITLE
selection problem in integrated terminal

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6750]
for https://github.com/Microsoft/vscode/issues/6654:
- VSCode Version: 1.1.0 alpha
- OS Version: Window 10

When selecting lines of text in the integrated terminal, if you drag the mouse below the bottom of the integrated terminal's viewport, some text in the editor becomes part of the selection:

![may-24-2016 11-28-52](https://cloud.githubusercontent.com/assets/1898161/15499224/5f9fcebc-21a3-11e6-93bb-508fec8d18fe.gif)

**Comment by Tyriar** [comment]
This no longer happens. Here are some selection-related upstream issues:

- https://github.com/sourcelair/xterm.js/issues/69
- https://github.com/sourcelair/xterm.js/issues/68

**Comment by bpasero** [comment]
I am still seeing this though I am not sure if it is terminal related.

**Comment by Tyriar** [comment]
I didn't do anything to resolve this but I certainly see it less now for some reason (maybe Windows only?). xterm.js is probably moving towards a virtual selection model similar to monaco which would fix this by disabling selection https://github.com/sourcelair/xterm.js/issues/207

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6755
