### ISSUE TITLE
can't turn on search exclude cog

### ISSUE THREAD

**Issue by brandonjah** [Microsoft/vscode#67501]
Issue Type: <b>Bug</b>

my search exclude has stopped working, it includes node modules etc. i think it is due to a recent update. the cog icon is turned off however clicking on it does nothing

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rails|bun|0.8.6
vscode-gemfile|bun|0.0.2
gitlens|eam|9.4.1
prettier-vscode|esb|1.7.3
vscode-pull-request-github|Git|0.3.2
rails-snippets|Hri|1.0.8
vscode-rufo|jnb|0.0.1
haml|kar|1.1.0
vscode-rufo|mbe|0.1.1
rainbow-csv|mec|0.8.0
vscode-elixir|mjm|1.1.0
vscode-duplicate|mrm|1.2.1
atom-keybindings|ms-|3.0.5
ruby|reb|0.21.0
sass-indented|rob|1.5.1
slim|sia|0.1.2

</details>

**Comment by roblourens** [comment]
Not sure what you mean "clicking on it does nothing", maybe you can show a screenshot or something?

**Comment by roblourens** [comment]
Also make sure you see the troubleshooting tips page https://github.com/Microsoft/vscode/wiki/Search-Issues
