### ISSUE TITLE
Right click meu disappears with D2C messages from Azure IoT Devices

### ISSUE THREAD

**Issue by edrickwong** [microsoft/vscode#67506]
Issue Type: <b>Bug</b>

1. Have an IoT Edge that is sending a stream of D2C messages.
2. Right click on the device in Azure IoT Hub Device and click Monitor D2C Messages.
3.  Right click on the terminal for menu.
4. Menu disappears when a new message appears.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.8.0
vscode-docker|Pet|0.5.1
azure-iot-edge|vsc|1.8.0
azure-iot-toolkit|vsc|2.2.0

</details>

**Comment by Tyriar** [comment]
Can you provide a gif or screenshots?

**Comment by edrickwong** [comment]
The gif is kinda choppy but basically when there is a right click, the menu disappears, probably because the terminal is refreshed from a new D2C message.

![record_trim](https://user-images.githubusercontent.com/5561985/52019800-d565d280-24a3-11e9-85b4-c2259a78020e.gif)

**Comment by isidorn** [comment]
Custom menu, forwarding to @sbatten 
Output is not doing anything special

**Comment by sbatten** [comment]
@edrickwong does this issue still reproduce in latest?
