### ISSUE TITLE
Can not paste true contents of clipboard.

### ISSUE THREAD

**Issue by rolance** [Microsoft/vscode#67515]
Issue Type: <b>Bug</b>

Whenever I go to paste from the clipboard I get the following instead of the clipboard contents: C:\Users\lmont\AppData\Local\Temp\PRODUCT_NAME_UNKNOWN_CrashDumpPRODUCT_VERSION_MAJOR_UNKNOWN-PRODUCT_VERSION_MINOR_UNKNOWN-2019-01-29--20-51-24_.dmp

The clipboard works fine in other applications.

This follows a crash (blue screen) that ocurred while visual studio code was running.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (8.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
docker-explorer|for|0.1.6
Angular2|joh|7.0.1
Angular-BeastCode|Mik|7.2.1
python|ms-|2019.1.0
vscode-docker|Pet|0.5.1
vscode-yaml|red|0.2.1
vsc-docker|Zim|0.34.0

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rolance** [comment]
Thanks. Behavior stopped after two reboots.  Perhaps a feature and not a bug? Not sure who to send the .dmp file to though, (which points the finger at NahimicSvc32.exe for trying to read from or write to a virtual address for which it does not have the appropriate access).

**Comment by rolance** [comment]
OK so I traced this down to a bad actor (an audio driver called Nahimic32.exe) unrelated to Visual studio code that was crashing and filling my clipboard every five seconds. I deleted the offending software and the problem has resolved. Thanks for your help.
