### ISSUE TITLE
无法使用插件在浏览器种对html文件浏览

### ISSUE THREAD

**Issue by 1046118935** [Microsoft/vscode#67518]
在vscode上使用open in browser插件对html文件预览在有浏览器的情况下报Open browser failed!! Please check if you have installed the browser  correctly!
![image](https://user-images.githubusercontent.com/34113928/51961782-e0ffcc00-2498-11e9-9729-71944772a574.png)
![image](https://user-images.githubusercontent.com/34113928/51961791-eceb8e00-2498-11e9-8a4c-ffcfbd3bd5e3.png)

**Comment by infinnie** [comment]
Open an issue in the plugin developer’s repo instead of here.

**Comment by dbaeumer** [comment]
@infinnie thanks! Your advice is correct.
