### ISSUE TITLE
Open the integrated terminal in a new window as it was when I left off.

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#67519]
Issue Type: <b>Feature Request</b>

For more efficient workflow I am using a 4-way split integrated terminal, for:

1. `git add .`
2. `git diff HEAD`
3. `git commit`
4. `git push`

This way I can just press the up arrow key and enter in each window for each command. I also have another two-way split window for `touch Cargo.toml` (to restart the RLS for rls-vscode), and other commands. Because I use the first window every session it would be great if it would open that way every time.

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:14:17.311Z)
OS version: Linux x64 4.20.1-1-MANJARO

**Comment by Tyriar** [comment]
There are extensions for things like this such as https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals, they can't do splits yet though.

For your case, why not use aliases or run `git add . && git diff HEAD && git commit && git push`?

**Comment by jamesray1** [comment]
> For your case, why not use aliases or run `git add . && git diff HEAD && git commit && git push`?

Thanks for the suggestion, but I think I would at least like to be able to have the diff and commit message side-by-side, so I can write the commit message as I read the diff. That way if it's a detailed diff I can make sure that I don't forget to include anything (as a summary). So I could have one terminal with `git add . && git diff HEAD` and another with `git commit && git push` which is an improvement.
