### ISSUE TITLE
Setup was unable to create the directory %USERPROFILE% Error 5: Access Denied

### ISSUE THREAD

**Issue by wandyezj** [Microsoft/vscode#67516]
- VSCode Version:
- OS Version: Windows 10

Steps to Reproduce:

1. rename user profile
2. launch visual studio code

Does this issue occur when all extensions are disabled?: Yes/No

This pops up an annoying window, it would be great if Visual Studio concealed the error since it is super annoying.

**Comment by joaomoreno** [comment]
Can you share a screenshot of the error?

**Comment by wandyezj** [comment]
![capture](https://user-images.githubusercontent.com/4239645/52103700-d0844a00-259b-11e9-80b7-ef7b90d28943.PNG)

**Comment by joaomoreno** [comment]
Please uninstall VS Code and reinstall. It won't support renaming the user profile, unfortunately.
