### ISSUE TITLE
Terminal open

### ISSUE THREAD

**Issue by osky9913** [Microsoft/vscode#67513]
Issue Type: <b>Bug</b>

Hello, when I open terminal powershell with keyshortcuts, the terminal is still loading and I  cant access to the actual writting and than stop wit exit code 
"The terminal process terminated with exit code: 4294967295"
I tried to reset all setting but still has a problem to do it 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.65GB (9.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
theme-monokai-pro-vscode|mon|1.1.9
python|ms-|2019.1.0
cpptools|ms-|0.21.0

</details>

**Comment by osky9913** [comment]
https://ibb.co/wy1h0jw here is a picture , when is opening i need to type enter for stop some kind of process then is working correctly but if I do not type enter , powershell will crash with that exit code

**Comment by osky9913** [comment]
https://ibb.co/4tzyY3b with cmd there is a different story... First cmd will start , then are a infinite whitespace and after enter there it will stop

**Comment by Tyriar** [comment]
Press enter a couple of times to fix this, it's a bug in Windows.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803

**Comment by osky9913** [comment]
> Press enter a couple of times to fix this, it's a bug in Windows. #57803

Will be a fix from Microsoft? Or will it help  to clean install Windows 10 ?
