### ISSUE TITLE
Question: Would a wiki page about setting up Intellisense be useful?

### ISSUE THREAD

**Issue by mattdufeu** [Microsoft/vscode#6751]
I recently struggled to get Intellisense working for React.js.

I *think* I've done it now, so wrote the steps I followed here http://mattdufeu.co.uk/setup-intellisense-vscode-react-js/

Is that correct or am I missing something?

Would something like this be useful on the wiki? I'd be more than happy to create a PR if you think it's useful.

**Comment by aeschli** [comment]
@mattdufeu You maybe want to ask this question on stackoverflow.

**Comment by mattdufeu** [comment]
@aeschli sorry, the title might have been misleading. I've changed the title to hopefully reflect better what I mean.

Unless you are saying, there's no need for a wiki page?

**Comment by gregvanl** [comment]
Closing vscode issue.  Will be covered with vscode-docs issue: https://github.com/Microsoft/vscode-docs/issues/495
