### ISSUE TITLE
Text becomes hidden when using >= 5 Splits with an ultrawide screen monitor

### ISSUE THREAD

**Issue by AyyygoRhythm** [Microsoft/vscode#67525]
Issue Type: <b>Bug</b>

Actual Behavior:
* Connect to a 32:9 display (5120x1440)
* open vscode with extensions disabled and open any file
* split right to create 5 splits
* observe no text being shown in the editor split

Expected behavior
* Connect to a 32:9 display (5120x1440)
* open vscode with extensions disabled and open any file
* split right to create 5 splits
* observe your files text being shown

Occurs with and without extensions disabled.
Here is a video demonstrating it:
https://gfycat.com/AstonishingObedientBarracuda

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (85)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.2
react-pure-to-class-vscode|ang|1.1.7
vscode-custom-css|be5|3.0.0
vscode-node-readme|ben|3.0.2
lit-html|bie|1.7.0
markdown-preview-github-styles|bie|0.1.3
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
react-definition|Chr|0.0.1
regex|chr|0.2.0
jsrefactor|cms|2.15.1
bracket-pair-colorizer|Coe|1.0.60
vs-component-app|cva|0.2.1
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
vscode-generact|Den|1.0.5
javascript-ejs-support|Dig|0.3.2
es7-react-js-snippets|dsz|1.8.7
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.6.1
vscode-open-multiple-files|fab|1.2.2
vscode-todo-plus|fab|4.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
docker-explorer|for|0.1.6
macros|ged|1.2.1
gc-excelviewer|Gra|2.1.26
activitusbar|Gru|0.0.14
save-without-format|Gru|0.0.3
todo-tree|Gru|0.0.92
rest-client|hum|0.20.2
vscode-postfix-ts|ipa|1.8.0
fuzzy-search|jac|0.0.2
react-component|jer|1.0.1
vscode-redux-devtools|jin|0.0.11
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.22
vscode-fix-checksums|leh|1.1.0
sftp|lix|1.6.3
fish-ide|lun|0.4.0
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.0
HTMLHint|mka|0.5.0
vs-script-commands|mkl|7.0.0
vscode-apache|mrm|1.1.1
mssql|ms-|1.4.0
python|ms-|2018.11.0
cpptools|ms-|0.20.1
vsliveshare|ms-|0.3.834
debugger-for-chrome|msj|4.10.2
vscode-open-iterm2|mus|0.0.4
vscode-paste-image|mus|1.0.2
color-highlight|nau|2.3.0
vscode-json-editor|nic|0.2.0
vscode-json-transform|oct|0.1.2
react-proptypes-intellisense|OfH|1.0.3
vscode-react-native-storybooks|Ort|2.5.1
vscode-docker|Pet|0.3.1
ejs-language-support|Qas|0.0.1
quicktype|qui|12.0.46
htmlescape-vscode-extension|ray|0.0.4
vscode-sort-json|ric|1.13.0
json-organizer|rin|0.0.4
vscode-icons|rob|7.27.0
git-merger|sha|0.4.1
fish-vscode|sky|0.2.1
vscode-fileutils|sle|2.11.0
rewrap|stk|1.9.1
ayu|tea|0.17.0
theshukran-react-utils|the|1.0.2
shellcheck|tim|0.6.0
terminal-tabs|Tyr|0.2.0
vim|vsc|0.16.10
vscode-react-native|vsm|0.6.18
vscode-todo-highlight|way|1.0.4
vscode-js-console-utils|wht|0.7.0
glean|wix|3.3.2
react-playground-vscode|wmi|0.0.11
clang-format|xav|1.8.0
markdown-pdf|yza|1.2.0

(15 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by terminull** [comment]
Apologies, I mistakenly left out that I did try that before posting and it
still occurs.

**Comment by bpasero** [comment]
Thanks
