### ISSUE TITLE
Incorrect New File Names

### ISSUE THREAD

**Issue by ramiseren** [Microsoft/vscode#67524]
Issue Type: <b>Bug</b>

When I open VS Code, I keep getting incorrect new file names. Such as Untitled-7 or Untitled-6 or whatever it's. I close all the VS Code windows and tabs, I quit it completely and restart my PC but still I get "Untitled-7" as a new page number.

New pages continue increasing number but if I close it again, this time I get "Untitled-8" as a new page number.

1) Open VS Code
2) Start a New Page
3) Get file name "Untitled-8"
4) Close all and quit VS Code
5) Open VS Code
6) Start a New Page
7) Get file name "Untitled-9"

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Lisp|mat|0.1.8
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1

</details>

**Comment by bpasero** [comment]
We fixed this.
