### ISSUE TITLE
editor.wordwrap in markdown editor is always 'on' when I set word wrap off.

### ISSUE THREAD

**Issue by FAAAAT** [Microsoft/vscode#67526]
Issue Type: <b>Bug</b>

When I set the file format to plain text, auto wrap works fine. But when I set the file to markdown, auto wrap is always on no matter what options I choose in settings.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (12.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|0.8.0
vscode-language-pack-zh-hans|MS-|1.30.2
partial-diff|ryu|1.4.0

</details>

**Comment by dbaeumer** [comment]
@mjbvz starting with you. Not sure if this is markdown or editor related.

**Comment by mjbvz** [comment]
Markdown provides some language specific default for word wrap. You need to override these using a language specific json setting:

```json
	"[markdown]": {
		"editor.wordWrap": "wordWrapColumn"
	}
```

Improving how this shows in the setting UI is tracked by #65844
