### ISSUE TITLE
ftp-sync

### ISSUE THREAD

**Issue by louuyan** [Microsoft/vscode#67530]
Issue Type: <b>Bug</b>

安装ftp-sync插件 
启动ftp-sync ：init 报错
Running the contributed command:'extension.ftpsyncinit' failed

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.6
code-runner|for|0.9.7
ftp-simple|hum|0.6.8
docthis|joe|0.7.1
ftp-sync|luk|0.3.9
vscode-language-pack-zh-hans|MS-|1.30.2
python|ms-|2019.1.0
Go|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
remote-vscode|raf|1.1.0
vscode-icons|rob|8.0.0
mark-jump|spy|0.8.2
rf-intellisense|Tom|2.3.0
vscode-icons-mac|way|7.25.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
Please report the issue against the `ftp-sync` extension.
