### ISSUE TITLE
git: warn before commiting if there are pending commits to download/pull

### ISSUE THREAD

**Issue by salgiza** [Microsoft/vscode#67536]
The sync status on the bottom bar is quite nice, but way too small and, now that we are migrating one of our development teams to Visual Studio Code + git (they used a different IDE and source control system before), we are finding that our repositories are full of "automerges", due to the fact that it is very easy to commit some changes before realising that someone else had also made changes to the project.

It would be nice if there was an option, say *fetchBeforeCommit* or something similar, that run the "git fetch" command before confirming the commit and, if there are commits that have not been pulled yet, ask the user whether they want to continue commiting (and thus requiere a merge), or cancel the action.

**Comment by joaomoreno** [comment]
You seem to have an expectation of git to work like TFS (or similar). In Git, merge commits are your everyday tool. Each dev should be able to commit at any time and pick up changes from a central location at any point in time.

If you do not like merge commits and would like a clean history, I recommend reading about Rebase: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by salgiza** [comment]
We know about rebase, thanks.

Will this be useful for big projects with dozens of developers? I do not know.

I do know that this is a feature that is useful to very small projects (such as the ones we do frequently to customise Microsoft Dynamics 365 Business Central for our customers), were usually only 1-2 developers are working on a project at a time, the total number of commits is low, automerges are more of an annoyance than anything else, and the projects are so small that no auto builds or any other processes are configured.

Will this be useful for you? It certainly doesn't look like it.

Does this changes the fact that a dev should be able to commit and pick up changes at any time? No, and I don't know what that has to do with this request at all. 

What I asked for is configurable warning if you push commit when there are changes in the server, so that you can choose whether you want to merge, or pull the changes first to check that everything works before doing your commit. Even if you go for the merge, at least you know there are changes and you have to check that everything works.

But do not worry Joao, it is clear from your message that either we must use git as you do, and it is our problem if our projects have nothing in common with the ones you work in.

**Comment by joaomoreno** [comment]
@salgiza Git rebase will do exactly what you want: it will bring each developer's commits on top of whatever is on the server, without having the developer to pull before she commits. This is what we use every day, just look at our git history, you'll find very few merge commits. We do not pull before committing to achieve this, we just rebase when pulling. Have you given this a try?

**Comment by salgiza** [comment]
> Yet, we do not pull before committing to achieve this, we just rebase when pulling instead of merge.

@joaomoreno Ok that comment make me realise that there is an option in VS Code to do rebase instead of merge when syncing, which makes sense and, yes would be a solution to our problem.

I thought that auto merging was the way that VS Code sync worked, and thus my suggestion (and my total puzzlement at your first comment).

Thanks for your help, and sorry for the tone of my previous comment.

**Comment by joaomoreno** [comment]
No worries.

VS Code simply spawns git, it doesn't reimplement git features. So, the Sync action actually only runs `git pull && git push`.

If you would like to always use rebase both in VS Code and the command line, you can do what we do:

```
git config pull.rebase true
```

That way, every time `git pull` is run, it will always use rebase, unless you use `--no-rebase`.
