### ISSUE TITLE
Buffer() deprecation warning when installing a vsix through the command line

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#67534]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/9205389/51976227-72187800-2484-11e9-80f2-ad19019e96df.png)

VS Code version: Code - Insiders 1.31.0-insider (2c987b20a4d65ee51c48b9e4eb8f50c926199468, 2019-01-30T06:17:39.118Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
vscode-eslint|dba|1.8.0
Spot|der|0.4.0
ghlink|dt|1.0.2
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.7
tslint|eg2|1.0.42
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.3.2
rest-client|hum|0.21.1
solidity|Jua|0.0.49
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.13.0
vscode-azureappservice|ms-|0.11.0
vscode-azurefunctions|ms-|0.13.1
vscode-cosmosdb|ms-|0.9.1
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
cpptools|ms-|0.21.0
github-issues-prs|ms-|0.9.1
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.1
vscode-versionlens|pfl|0.22.0
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.10.1
ayu|tea|0.17.0
vscodeintellicode|Vis|1.1.2
azure-iot-toolkit|vsc|2.2.0

</details>

**Comment by bpasero** [comment]
This is coming as deprecation from our Electron update. If its unclear where this deprecation is coming from, I can help to print a stack from the place where it happens (this requires Electron 4 though from our exploration builds).

**Comment by sandy081** [comment]
The stack trace would be helpful to know.

**Comment by bpasero** [comment]
@chrmarti @sandy081 to this:
* open command line
* `export NODE_OPTIONS=--throw-deprecation`
* use `code-exploration`

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by chrmarti** [comment]
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:160:11)
    at new Buffer (buffer.js:175:3)
    at fromRandomAccessReader (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/node_modules.asar/yauzl/index.js:103:16)
    at /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/node_modules.asar/yauzl/index.js:55:5
    at FSReqWrap.oncomplete (fs.js:155:5)

**Comment by sandy081** [comment]
This is coming from `yauzl` lib. @bpasero Will this gets fixed upstream?

**Comment by bpasero** [comment]
@sandy081 I suggest you check if there is a newer version of yauzl lib that has this fixed. It should get fixed if a popular node lib wants to support node 10

**Comment by sandy081** [comment]
@bpasero I do not see this warning when running from sources? How can I repro this on dev?

**Comment by bpasero** [comment]
@sandy081 it should show up, I saw it in devtools at least, but never from the comand line.

**Comment by tristanbarcelon** [comment]
I can confirm that this is still happening for me when using code.cmd on Windows to install latest versions of following extensions: ms-azure-devops.azure-pipelines, ms-vscode.powershell, ms-mssql.mssql, ms-vsts.team, ms-vscode.csharp, ms-vscode.azure-account, peterjausovec.vscode-docker, davidanson.vscode-markdownlint, eamodio.gitlens, qezhu.gitlink, yzhang.markdown-all-in-one.


```
code.cmd : (node:7192) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), 
or Buffer.from() methods instead.
```

nodejs is at version 8.9.3 and npm is at 5.5.1.

**Comment by shubh3695** [comment]
I too can confirm regarding existence of the issue 
`(node:1592) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
nodejs 10.9.0
npm 6.2.0
vscode system installer 1.33.1

**Comment by David-Else** [comment]
When I install extensions on the command line in Fedora 30:

```
Found 'ban.spellright' in the marketplace.
Installing...
(node:11254) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'ban.spellright' v3.0.38 was successfully installed!
Found 'bierner.comment-tagged-templates' in the marketplace.
Installing...
(node:11280) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'bierner.comment-tagged-templates' v0.2.1 was successfully installed!
Found 'dbaeumer.vscode-eslint' in the marketplace.
Installing...
```

**Comment by kitforbes** [comment]
On WIndows 10:
```powershell
code --version
1.34.0
a622c65b2c713c890fcf4fbf07cf34049d5fe758
x64
```
```powershell
'EditorConfig.EditorConfig','hashhar.gitattributes','jirkafajfr.vscode-kitchen','mauve.terraform','ms-python.python','ms-vscode.cpptools','ms-vscode.csharp','Pendrica.chef','vscoss.vscode-ansible','waderyan.gitblame','wholroyd.jinja' |
    % { code --install-extension $_ }
Installing extensions...
Installing extension 'editorconfig.editorconfig' v0.13.0...
(node:18360) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'editorconfig.editorconfig' v0.13.0 was successfully installed.
Installing extensions...
Installing extension 'hashhar.gitattributes' v0.4.1...
(node:1664) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'hashhar.gitattributes' v0.4.1 was successfully installed.
Installing extensions...
Installing extension 'jirkafajfr.vscode-kitchen' v0.5.0...
(node:7060) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'jirkafajfr.vscode-kitchen' v0.5.0 was successfully installed.
Installing extensions...
Installing extension 'mauve.terraform' v1.3.11...
(node:9464) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'mauve.terraform' v1.3.11 was successfully installed.
Installing extensions...
Installing extension 'ms-python.python' v2019.4.12954...
(node:11280) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'ms-python.python' v2019.4.12954 was successfully installed.
Installing extensions...
Installing extension 'ms-vscode.cpptools' v0.23.1...
(node:10328) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'ms-vscode.cpptools' v0.23.1 was successfully installed.
Installing extensions...
Installing extension 'ms-vscode.csharp' v1.19.1...
(node:16184) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'ms-vscode.csharp' v1.19.1 was successfully installed.
Installing extensions...
Installing extension 'pendrica.chef' v0.7.1...
(node:6276) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'pendrica.chef' v0.7.1 was successfully installed.
Installing extensions...
Installing extension 'vscoss.vscode-ansible' v0.5.2...
(node:7520) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'vscoss.vscode-ansible' v0.5.2 was successfully installed.
Installing extensions...
Installing extension 'waderyan.gitblame' v2.7.0...
(node:3320) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'waderyan.gitblame' v2.7.0 was successfully installed.
Installing extensions...
Installing extension 'wholroyd.jinja' v0.0.8...
(node:168) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'wholroyd.jinja' v0.0.8 was successfully installed.
```

**Comment by DanTup** [comment]
FWIW I see this showing up inside Code in the developer tools now during normal use, if I installed from a VSIX (through the command palette). That is, the error is occurring during extension *usage*, not just during installation.

<img width="769" alt="Screenshot 2019-05-23 at 11 43 56 am" src="https://user-images.githubusercontent.com/1078012/58246846-11bd8700-7d50-11e9-89a8-284e70fc0951.png">

In the packed version of my extension, there is no instance of "Buffer()" in the code, so I don't think it's my code directly triggering it.
