### ISSUE TITLE
angular modules

### ISSUE THREAD

**Issue by ShavonneHarripersadh** [Microsoft/vscode#67531]
Issue Type: <b>Bug</b>

not  finding modules wih '@' sign

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.43GB (8.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.7.1
start-git|pol|0.0.6
javascript-typescript|sou|0.0.7

</details>

**Comment by dbaeumer** [comment]
Assuming this happens in a JS or TS file.

**Comment by ShavonneHarripersadh** [comment]
@dbaeumer yes in my ts files, if I try to ng serve , it doesn't recognise it as an angular project,
any idea why?

**Comment by mjbvz** [comment]
Please share some example code

**Comment by ShavonneHarripersadh** [comment]
![image](https://user-images.githubusercontent.com/44608234/52037041-b2d0c980-2536-11e9-80ba-287384125461.png)

**Comment by ShavonneHarripersadh** [comment]
fixed it, was calling npm install one directory outside the app, thanks guys
