### ISSUE TITLE
Why is it that sometimes `Go to definition` will go to file AND peek the same file

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#67533]
Say I activate `Go to definition` here:

![2019-01-30 at 11 40](https://user-images.githubusercontent.com/6391776/51975989-e6065080-2483-11e9-8fb6-1fd5ffc0fe9e.png)

It will do this:

![2019-01-30 at 11 41](https://user-images.githubusercontent.com/6391776/51976019-f8808a00-2483-11e9-9df1-7b4f50e36e48.png)

I don't understand why. It just shows peek definition of the same file it jumped too. Which is quite annoying.

Any way to remove this behavior?

**Comment by nikitavoloboev** [comment]
I looked into them, it wasn't helpful.

**Comment by mjbvz** [comment]
Can you please share the full file path of the file you have open and of the peek view file. I suspect that while the paths are the same, the casing may be different

**Comment by nikitavoloboev** [comment]
The file I jumped from: 

![2019-01-30 at 20 42](https://user-images.githubusercontent.com/6391776/52007824-a36a6580-24cf-11e9-9536-18b33b67c8a3.png)

The file I jumped to:

![2019-01-30 at 20 41](https://user-images.githubusercontent.com/6391776/52007793-8e8dd200-24cf-11e9-96e7-3cd5e2b088d6.png)

The paths and file names are on the top of the window.

**Comment by mjbvz** [comment]
Please share the full file path by right clicking on the file's tab and selecting `copy path`

**Comment by nikitavoloboev** [comment]
The full path of first screenshot's file:

`/Users/nikivi/src/orgs/enpicom/igx-ui/src/components/Login.tsx`.

And full path of the second screenshot's file:

`/Users/nikivi/src/orgs/enpicom/igx-ui/src/components/Login.tsx`

They are identical.

**Comment by nikitavoloboev** [comment]
The behavior I wish to stop is for VSCode not to show small peek window of code when I jump to definition of file. It does it when there are multiple occurrences I guess. Like when I go to definition from here:

![2019-02-01 at 11 53](https://user-images.githubusercontent.com/6391776/52118966-049d5080-2618-11e9-9aeb-66730b7a570a.png)

And get this:

![2019-02-01 at 11 53](https://user-images.githubusercontent.com/6391776/52118990-10891280-2618-11e9-92ab-9b09f8fc9143.png)

It jumps to the definition but instead of giving me the code focus I get the popup that I always have to `esc` out of. Please allow users to not have this happen and jump to the definition instantly with code in focus. If I wanted to see `Peek definition` I would activate it instead.

Thank you.

**Comment by mjbvz** [comment]
Ok, I missed that there are two definitions. This is currently expected behavior if there are more than 1 definitions

An alternative to the peek is tracked by #53164
