### ISSUE TITLE
explorer looses mouse over hover

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6753]
#6536

* reveal explorer
* notice how files change background on mouse over
* select a file for preview
* close file from then Open Editors group
* the last files has no background mouse over behaviour anymore

![may-24-2016 11-35-51](https://cloud.githubusercontent.com/assets/1794099/15499364/223d78a2-21a4-11e6-9583-ff298c8af0c3.gif)

**Comment by isidorn** [comment]
Can not repro any more. There have been a lot of changes coming in regarding open editors so some might have fixed this. Please reopen if you still see this.
