### ISSUE TITLE
Menu bar - help menu appears twice

### ISSUE THREAD

**Issue by RishabhParashar** [Microsoft/vscode#67545]
![screenshot from 2019-01-30 17-31-43](https://user-images.githubusercontent.com/30437194/51980244-77da8180-24b5-11e9-87ae-996e06573d25.png)
help Menu is appearing twice in menu bar.

**Comment by bpasero** [comment]
@RishabhParashar this is unfortunate upstream/electron behaviour but you can easily change this if you configure `"window.titleBarStyle": "custom"` in settings. Did you change this setting intentionally?
