### ISSUE TITLE
[python-jupyter] I want to display the re-executed cells at the original place but not the end of all cells.

### ISSUE THREAD

**Issue by xjnotxj** [Microsoft/vscode#67546]
* VSCode Version: 1.30.2
* OS Version: MacOs 10.12.6

For example, there are three cells A, B, and C, which are executed in sequence. The executed result is normally displayed in Python Interactive: A result -> B result -> C result

Now I modified the code in B cell and re-executed B cell. The result is: A result -> B result -> C result -> B result

But this is not what I want, my original thought about the display would be: A result -> B result (new) -> C result , meaning the new B cell might replace the original B cell's result. But obviously VSCode provides another result display method.

Is there anything I can do to make it more reasonable? Much gratitude in advance.

Reproduces without extensions: No

**Comment by roblourens** [comment]
This sounds like an issue with the Python extension or the Jupyter extension. Please file an issue on the repo for the right extension. https://github.com/DonJayamanne/vscodeJupyter
