### ISSUE TITLE
"Stage Changes" command should be called "Add" 

### ISSUE THREAD

**Issue by gabrielclimb** [Microsoft/vscode#67547]
You have closed the resquest create by James, so I'm opening a new one, cause it was not been fixed.
There are many Git commands listed in the command palette, but the only result for "add" is "Add file to .gitignore". This is not what I want. I want the equivalent of git add $CURRENT_FILE. Such a command is provided, for example, by the git-plus extension to Atom.

You guys should care about this and not only ignore the people are asking for some enhancements

**Comment by Nirajn2311** [comment]
I can work on this.

**Comment by joaomoreno** [comment]
> Such a command is provided, for example, by the git-plus extension to Atom.

Feel free to contribute an extension which adds such a command alias and just invokes `git.stage`.
