### ISSUE TITLE
php syntax highlighting

### ISSUE THREAD

**Issue by osben** [Microsoft/vscode#67540]
Issue Type: <b>Bug</b>

http://prntscr.com/me6thj

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.45GB (7.50GB free)|
|Process Argv|C:\Users\osben\Downloads\iworld_iworld.sql|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-formatter|cym|1.0.2
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.7
prettier-vscode|esb|1.7.3
smarty|imp|0.3.0
vscode-jetbrains-keybindings|isu|0.1.8
mysql-syntax|jak|1.3.1
chat|kar|0.10.0
vscode-apache|mrm|1.2.0
vsliveshare|ms-|0.3.1151
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.5
code-settings-sync|Sha|3.2.4
php-formatter|Sop|0.2.4
cordova-tools|vsm|1.7.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by alexr00** [comment]
@osben does this reproduce with all extensions disabled? Can you paste in some code that this reproduces with that I can copy/paste for testing??

**Comment by osben** [comment]
Sorry that I hurried and did not check. Indeed, jakebathman / mysql-syntax breaks. Here is their [issue](https://github.com/jakebathman/mysql-syntax/issues/21)

**Comment by alexr00** [comment]
Excellent, thank you for checking!
