### ISSUE TITLE
Cannot select and scroll beyond the bounds of the viewport in integrated terminal

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6755]
for https://github.com/Microsoft/vscode/issues/6654:
- VSCode Version: 1.1.0 alpha
- OS Version: Windows 10

to reproduce:
- launch integrated terminal
- run several 'dir' commands to fill the terminal with more lines than visible
- select the lines with the mouse and drag the mouse outside to the viewport to initiate autoscrolling.

Observe: there is no autoscrolling but some other text gets selected.

**Comment by Tyriar** [comment]
This one is related to limitations of term.js

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/69

**Comment by Tyriar** [comment]
Was added quite a while ago
