### ISSUE TITLE
Directory with many files (400+) is excluded from search if not explicitly included

### ISSUE THREAD

**Issue by fortytw2** [Microsoft/vscode#67558]
- VSCode Version:
```
code --version
1.30.2
61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
x64
```

```
rg --version
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

- OS Version:
Arch Linux

Steps to Reproduce:

1. Have a folder with a ton of files in it (in my case, a migrations/ dir with 400 or so)
2. Hit cmd+shift+f and search for strings that should be within that folder, they don't show up, but if you change to only search within that directory it works A OK

Does this issue occur when all extensions are disabled?: Yes

edit: apologies for all the edits, github is super jumpy on filing a new issue if you fat finger enter

**Comment by roblourens** [comment]
I haven't seen this

> but if you change to only search within that directory it works A OK

Can you explain what you are doing? 

Is this a project that could be shared?

**Comment by fortytw2** [comment]
If I set `files to include` to be `./migrations` it then searches within that directory, otherwise it seems magically excluded from all results.

Unfortunately not able to be shared :/

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by fortytw2** [comment]
```
code-insiders --version
1.31.0-insider
f125fdfa20b217dea34001eac9866322418226ce
x64
```

Just tried again with insiders, from the same project searching for the same thing

![image](https://user-images.githubusercontent.com/10286538/52132720-643e3080-2605-11e9-87a0-bb69b7f8b61c.png)

![image](https://user-images.githubusercontent.com/10286538/52132742-715b1f80-2605-11e9-9200-0e73161ea3ef.png)

Could it be that there's some hidden cap on results from within a folder?

**Comment by roblourens** [comment]
Are you sure that the folder isn't excluded by some setting or gitignore pattern? See some troubleshooting tips here: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results
