### ISSUE TITLE
Use TreeResourceNavigator2.onDidOpenResource in ExplorerView

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67554]
We should use the navigator instead of listening to the selection change event.

https://github.com/Microsoft/vscode/blob/00d1ec8778bd7fa6c5b4f49e4337516547deae78/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L292

**Comment by isidorn** [comment]
Sure. Assigning for february
