### ISSUE TITLE
Parenthesis Inside of <blockquoute> Tag Creates Function

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#67557]
Issue Type: <b>Bug</b>

It's strange but within the `<blockquote></blockquote>` tags if I type normal text and then add `()` the text right before it is rendered as a function and all text, tags, code after that is grayed out as if it's normal plain text.

The file language is auto-detected as aspnetcorerazor.

```
<div class="row">
    <blockquote>Please input the required fields marked with an asterisk (*).</blockquote>
</div>
```

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.50GB free)|
|Process Argv|\\srcvmiistest01\d\websites\panoplytest.chs.local\Web.config|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
gitlens|eam|9.4.1
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.46
prettier-vscode|esb|1.7.3
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
dotnet-test-explorer|for|0.6.1
minify|Hoo|0.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
docomment|k--|0.1.2
dotnet-core-essentials|Kis|0.0.6
vscode-azureappservice|ms-|0.11.0
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1151
vsliveshare-audio|ms-|0.1.48
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
debugger-for-edge|msj|1.0.6
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.14.5
vscode-docker|Pet|0.5.1
vscode-gitignore-generator|pio|1.0.1
tslint-vue|pro|1.5.6
vscode-format|rya|0.0.6
yo|sam|0.9.3
vscodeintellicode|Vis|1.1.2
wilderminds-aspnetcore-snippets|wil|0.2.1
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
@DanJ210 Thank you for the example!  I can't reproduce this. Can you try disabling all extensions and see if it still reproduces?
