### ISSUE TITLE
256 Color Support Missing for WSL Ubuntu on Windows

### ISSUE THREAD

**Issue by scarolan** [Microsoft/vscode#67551]
Issue Type: <b>Bug</b>

1.  Open Ubuntu.exe in its own window.  Run the 256color.pl perl script. Bask in the glory of your multi-hued rainbow. https://gist.github.com/hSATAC/1095100

2.  Now open Visual Studio Code and fire up WSL in the integrated terminal.  Run 256color.pl and feel sad because the palette can only render 16 colors.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
terraform|mau|1.3.7
PowerShell|ms-|1.11.0
vscode-icons|rob|8.0.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
