### ISSUE TITLE
All files don't seem to be indexed until they have been opened

### ISSUE THREAD

**Issue by Banb4n** [Microsoft/vscode#67555]
Issue Type: <b>Bug</b>

- 1 Open a big directory (more than 100 000 files for me)
- 2  Search for an existing file (e.g. src/components/products/List.js) => no result
- 3 Open src/components/products/List.js in the editor
- 4 Search again and the file should be found

VS Code version: Code - Insiders 1.31.0-insider (2c987b20a4d65ee51c48b9e4eb8f50c926199468, 2019-01-30T06:17:39.118Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 5, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_10201530|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
See these troubleshooting tips for search and tell me whether any of this helps: https://github.com/Microsoft/vscode/wiki/Search-Issues
