### ISSUE TITLE
C++ Syntax Highlighting gets confused by apostrophes

### ISSUE THREAD

**Issue by damyanp** [Microsoft/vscode#67568]
Issue Type: <b>Bug</b>

For example:

```
#error Don't do this
void foo() { }
```

The syntax highlighter thinks that a string starts from the apostrophe betwee the "n" and "t" in "don't" and highlights the rest of the file as a string until it reaches the next single quote.

Visual Studio gets this correct, since the entire line for the preprocessor directive is highlighted separately and it doesn't look for strings inside it.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (18.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
wrap|dt|0.0.1
cpptools|ms-|0.21.0

</details>

**Comment by damyanp** [comment]
Live screenshot: 
![image](https://user-images.githubusercontent.com/8118402/52003272-e6e5b500-2478-11e9-8f11-db03d5949bd8.png)

**Comment by alexr00** [comment]
This issue was moved to atom/language-c#320
