### ISSUE TITLE
arrow down and dots icon look similar

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6756]
#6536

<img width="184" alt="screen shot 2016-05-24 at 11 41 29" src="https://cloud.githubusercontent.com/assets/1794099/15499434/83fb8bf6-21a4-11e6-8e63-d9e677eadcaa.png">

The arrow down icon we now show in the editor header looks like a context menu icon (what the `...`-icon does). I think we need a better icon for that

**Comment by bpasero** [comment]
Agree.

**Comment by bgashler1** [comment]
I'll look into this.  Do you have any input on what you would be expecting instead of an ellipses icon?

**Comment by jrieken** [comment]
I do like the ellipses - it nicely represents the fact that there is more/a context menu. The issue is that the down arrow has the same meaning to me. So, I think we should have the down/double down arrows.

**Comment by bpasero** [comment]
We decided to not show the arrow down if it does not apply.
