### ISSUE TITLE
New Project Error

### ISSUE THREAD

**Issue by Oskar2601** [Microsoft/vscode#67562]
Issue Type: <b>Performance Issue</b>

When i press file and hover on new file nothing is there i want to open a new project please help.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (4.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	 16564	code main
    0	   153	 10056	   window (Visual Studio Code)
    0	    64	 11500	     extensionHost
    0	    12	 15068	     electron-crash-reporter
    0	   144	 13188	   gpu-process
    0	    65	 13624	   shared-process
    3	    68	 14580	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.3.1

</details>

**Comment by dbaeumer** [comment]
I am closing the issue. Please ping if you have provided additional information.
