### ISSUE TITLE
Login window do not appears at top

### ISSUE THREAD

**Issue by BipulRaman** [Microsoft/vscode#67564]
Login window do not appears at top when `Connect-MicrosoftTeams` command or any similar command is entered which opens login window.

**Comment by dbaeumer** [comment]
@BipulRaman can you clarify where you type the command ?

**Comment by BipulRaman** [comment]
I was using below command in  *.ps1 file 
`Connect-MicrosoftTeams -AccountId $ParametersJson.TenantAdminAccountID`
The office365 login window should have been appeared on top of VS code, but it was not. I had to switch tab to access that window to put password.

**Comment by dbaeumer** [comment]
@BipulRaman did you type the command in the integrated terminal inside VS Code ?

**Comment by BipulRaman** [comment]
No, it was in ps1 file. I executed ps1 file through PowerShell terminal on VS code.

**Comment by dbaeumer** [comment]
@BipulRaman and it works as expected when executing in a normal PowerShell terminal ?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/42356
