### ISSUE TITLE
FileSystemProvider: Dragging provided files from explorer to Finder produces ".textClipping" files instead of file contents

### ISSUE THREAD

**Issue by johnspurlock** [microsoft/vscode#67567]
- VSCode Version: 1.31.0-insider 2019-01-30T06:11:27.450Z 2c987b20a4d65ee51c48b9e4eb8f50c926199468 
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Create a custom [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider), mount a custom uri as a workspace root.
2. Drag any file under the provided root from the main explorer view out to the Finder.
3. Note a `.textClipping` file is created, with the custom uri as text contents.

The entire file should be reconstituted out here, the FileSystemProvider api provides enough info to create it, and it's weird that it behaves differently than explorer drags from other `file:` workspace roots.

**Comment by jrieken** [comment]
depends on #41543

**Comment by bpasero** [comment]
@jrieken how is that? I do not think we can support this easily, after all we rely on Chrome to copy the file to some location on disk and afaik that file has to be on disk already. I don't think we can ever support this for non files. The area where we enable this for files only is [here](https://github.com/Microsoft/vscode/blob/65c775918b54a18310b61c40d3138bccb68d361f/src/vs/workbench/browser/dnd.ts#L332).

I believe the reason for seeing a resource being created is our resource transfer right after ([here](https://github.com/Microsoft/vscode/blob/65c775918b54a18310b61c40d3138bccb68d361f/src/vs/workbench/browser/dnd.ts#L338)).

**Comment by johnspurlock** [comment]
Save temporarily to disk, then copy to custom fs under the hood?

**Comment by bpasero** [comment]
@johnspurlock that would be a bit crazy because of this operation not giving us any callback. We need to set the drag data when the drag is starting and we do not know when it is dropped to the desktop so we would always need to copy the contents down into a temporary file (sync) upon drag start.

**Comment by johnspurlock** [comment]
That drag data is "DownloadURL"?  Couldn't that pull from a self-hosted http server that streamed from the fs?

**Comment by jfperusse** [comment]
Has there been updates to this since 2019? Dragging files from Explorer to our local file system also results in weird XML files with a path to our remote files instead of the files being read from the FileSystemProvider and written to disk. Are there any known workarounds, such as implementing some drag and drop handler?
