### ISSUE TITLE
Folder and File /out/extension.js Not Being Created

### ISSUE THREAD

**Issue by trebleCode** [Microsoft/vscode#67572]
- VSCode Version: 1.28.2
- OS Version: Windows 10

Steps to Reproduce:

1. Generate an extension scaffolding with yeoman generator-code
2. Edit extension.ts to implement a single command
3. Edit package.json to include a publisher field with a string value
4. Update activationEvents and contributes: commands: command entries to support the name of my implemented command
5. Run debugger, press Ctrl+P  in the new VS Code window and bring up my command in the palette, select it and hit Enter
6.  Receive 'Activating extension <PublisherName>.<extensionName> failed: Cannot find module 'Path\to\mygeneratedextension\out\extension.js'
7. The \out\extension.js is never created and my command is never executed

Please let me know any additional information required
Thank you!

Does this issue occur when all extensions are disabled?: Yes

**Comment by trebleCode** [comment]
My guess here is that the tsc compiler is not on my Windows PATH system variable. I have installed typescript via npm globally on my corporate machine, and have attempted adding C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8 to the path dynamically by using a PowerShell profile to add some items to Path each time a terminal is loaded, but this still seems to fail. Writing the exact same code on a personal machine appears to work without any issues at all. Any suggestions?

**Comment by dbaeumer** [comment]
@trebleCode actually this looks like a pretty old installation of the TSC compiler. I recommend that you uninstall it and install tsc using npm (e.g.`npm install -g typescript`).

The the compiler is automatically called when launching the extension.

Let me know if this helps.

**Comment by trebleCode** [comment]
That worked, thanks!

**Comment by dbaeumer** [comment]
Closing the issue then.
