### ISSUE TITLE
No indication that cut and paste over existing file didn't succeed

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#67570]
- VSCode Version: 1.31 Insiders
- OS Version: Windows 10

Found when testing https://github.com/Microsoft/vscode/issues/66905

Steps to Reproduce:

1. Create a folder1 with blah.md in it.
2. Create another folder2 and also have a file blah.md
3. Cut blah.md from folder1 and try to paste through the Explorer context menu in folder2.

Not indication (dialog box) that paste didn't work. Should this result in a copy over, a new file blah1.md (like copy) or simply block the paste?

The cut blah.md is still shaded and available for pasting but that's pretty subtle.

**Comment by gregvanl** [comment]
Turns out if you use the keybinding Ctrl+V for the paste, there is a notification.

![image](https://user-images.githubusercontent.com/12818376/52004796-e5b68700-247c-11e9-99cc-ad4f81c4f433.png)

There is no notification if you use the Explorer context menu Paste

**Comment by isidorn** [comment]
@gregvanl good catch, thanks!
