### ISSUE TITLE
Multiline Diagnostics: Trim Whitespace/Empty Lines correctly

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#67573]
Issue Type: <b>Bug</b>

Testing  #67255

Created multiline diagnostics with some empty lines at the end

```
cannot assign twice to immutable variable `x`\n\tabc\ndef\n\n\n\n\n
```

We still render all empty lines. If this is expected, then the line info `[3, 5]` is positioned at the wrong place probably.

![image](https://user-images.githubusercontent.com/876920/52005784-62e2fb80-247f-11e9-889f-74ab47aebf1d.png)

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:13:57.866Z)
OS version: Windows 10

<details>
<summary>System Info</summary>

</details>Extensions: none

**Comment by sandy081** [comment]
We have to render the message as it is. Let me see if the empty lines are not rendered.
