### ISSUE TITLE
Make the typescript plugins extension point dynamic

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67575]
Part of #66574

Tracks making the typescript plugins extension point dynamic

We should restart the TS server if contributed plugins change.

**Comment by mjbvz** [comment]
Final part of fix in [d73fdb0](https://github.com/Microsoft/vscode/commit/d73fdb0593b08349dc24f7c188ab1e5a09d4c1a7)

**Comment by octref** [comment]
@mjbvz Ping for verification steps

**Comment by mjbvz** [comment]
1. In a workspace with tslint setup, such as the vscode source (but without any tslint extension installed)
1. Open file and delete a semicolon. Confirm no tslint alerts
1. Install the tslint extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin
1. Now the tsserver should restart and tslint should be enabled and alert about the missing semicolons

**Comment by octref** [comment]
Verified.
