### ISSUE TITLE
"workbench.tree.indent" should have sensible minimum and maximums

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67576]
From https://github.com/Microsoft/vscode/issues/35447

The new setting `"workbench.tree.indent"` should have a minimum and a maximum in the schema declaration so that

- The UI will prevent you from setting negative values
- Or you get a warning in the JSON file
- And to prevent weird issues where someone managed to set it to 10000 on accident

And you can also set it to only allow integers but non-integers work so maybe you want to leave that

**Comment by isidorn** [comment]
Yeah makes sense to me.
Assigning to february

**Comment by joaomoreno** [comment]
Clamped between 0-20.

**Comment by realuser** [comment]
20 seems a little restrictive IMHO.  Seems the original intention was to prevent wild values like 10000. I think this should be higher, like 50 or 100.  There's no reason not to give users the flexibility.  When I set it to 20 it doesn't feel like an excessive indent by any stretch.

**Comment by joaomoreno** [comment]
@realuser What's the value you personally like best?

**Comment by sguillia** [comment]
@joaomoreno Before even knowing about this issue, I had the indent set to 24.

People are weird. Put it to 100

**Comment by realuser** [comment]
@joaomoreno I have it set to 20 now, but if you're asking what value the max should be, then I think 100.  I don't think the purpose of the max is to arbitrarily impose our own sense of what a good/reasonable indent should be but rather to prevent values that might cause confusion to the user (e.g. they accidentally set it to 900 and now they don't know what's wrong with the workbench/file explorer)

**Comment by quentinsf** [comment]
Yes, I agree - I have mine on 20 and I like to think I'm a moderate kind of guy, so others may be more extreme :-)

By the way, this is my favourite new setting of the last year!

**Comment by alexcroox** [comment]
Yes please, 20 is too restrictive, I want to get closer to my ST3 setup (on the right)

![ss](https://camo.githubusercontent.com/40fabd157276f67f1ec295007faef7229dfa1e0b/68747470733a2f2f636c2e6c792f3339623134376666323732622f53637265656e73686f74253230323031392d30322d3132253230617425323030372e35312e30372e706e67)

**Comment by joaomoreno** [comment]
Raised to 40

**Comment by realuser** [comment]
I mean that's better but I don't get why you wouldn't set this to 100.  There's no reason to impose a sense of a "good indent" when we can't know what users will want. What is the benefit of restricting it to 40 vs 100?

**Comment by sguillia** [comment]
Now I'm able to set it to 40, the indent goes to 40, but the user interface shows a warning.

![bug-vscode](https://user-images.githubusercontent.com/15984272/53016395-dc05bb00-344d-11e9-995c-5638e16d79ec.PNG)

@joaomoreno I think you forgot to update `src/vs/base/browser/ui/tree/abstractTree.ts` as you did in 79b4ea2

I submitted PR #68980

**Comment by joaomoreno** [comment]
@sguillia Thanks.
