### ISSUE TITLE
There is no document formatter for 'css'-files installed.

### ISSUE THREAD

**Issue by razafinarivohanania** [Microsoft/vscode#67579]
Hello! I have seen this [bug](https://github.com/Microsoft/vscode/issues/55359). It has been closed but i still have the issue even though i have uptated my VSC with the last version.

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:53:57.820Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT ia32 6.1.7601

Sorry for the inconvenience.

**Comment by usernamehw** [comment]
There is no built-in formatter for `CSS` in vscode. You need to install extension that implements it.

**Comment by razafinarivohanania** [comment]
Thanks for the response.
