### ISSUE TITLE
Deb package not installable on Elementary OS anymore - claims package is of bad quality

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6758]
- VSCode Version: alpha
- OS Version: Elementary OS

Steps to Reproduce:

1. Download deb package
2. Try to install. You get the following dialog

![capture](https://cloud.githubusercontent.com/assets/1931590/15499580/3b66cda0-21a5-11e6-9717-35a5fa5c92b5.png)

**Comment by Tyriar** [comment]
Curious, from all my reading `#!/usr/bin/env bash` is superior and more portable than `#!/bin/bash`.

**Comment by Tyriar** [comment]
I verified I could install and remove after 096221c
