### ISSUE TITLE
Include file name in references search history quick pick

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67584]
**Feature request**
When running `References: View History`, include the search file name in the quick pick:

<img width="743" alt="screen shot 2019-01-30 at 2 44 40 pm" src="https://user-images.githubusercontent.com/12821956/52017904-97fe4680-249d-11e9-94a1-bd68d1b42ba9.png">

**Comment by mjbvz** [comment]
Maybe put the file name next to the search term and put the full line below?

**Comment by misolori** [comment]
Not a fan of that either (takes up too much space). Can we append the file name in the description?

`{file} • {string}`

<img width="595" alt="image" src="https://user-images.githubusercontent.com/35271042/52151366-b6904900-2627-11e9-98ce-87fdf4474752.png">

**Comment by jrieken** [comment]
Yeah, looking good. I will go with that. Thanks

<img width="774" alt="screenshot 2019-02-04 at 12 36 59" src="https://user-images.githubusercontent.com/1794099/52206113-92c44180-2879-11e9-9d06-92648f50c4de.png">
