### ISSUE TITLE
Inconsistent looks between Installed badge and Install button

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67585]
![image](https://user-images.githubusercontent.com/4033249/52017847-74d39700-249d-11e9-854b-ba5dcdf06c39.png)

The badge looks like a button. It shares the color as "Install", but is using a rounded corner.

**Comment by roblourens** [comment]
Yeah I would prefer a different color. Maybe just a label with no background color.

**Comment by sandy081** [comment]
Went with this style after discussing with the team. Reason being the feedback needs to be prominent. 

@misolori Any feedback?

**Comment by aeschli** [comment]
@sandy081 There's also a small aligment issue (on Linux). The height of the new box is larger than the existing buttons

![image](https://user-images.githubusercontent.com/6461412/52044807-4c05dd00-2543-11e9-84b1-7c10557b1b37.png)

**Comment by joaomoreno** [comment]
IMO the button should look exactly the same except with a more faded out green background color.

**Comment by sandy081** [comment]
Here it is when faded a bit.

![image](https://user-images.githubusercontent.com/10746682/52055481-d3614980-255f-11e9-88b1-b5c1f7a04370.png)

Here it is when transparent or no colour

![image](https://user-images.githubusercontent.com/10746682/52055675-584c6300-2560-11e9-9d93-a1ea54ae625b.png)

I kind of liked the second (no colour), not much catchy at the same time serves the intend of feedback. 

@misolori Final call?

**Comment by misolori** [comment]
I prefer no background color on the button since it’s a confirmation/state rather than an action.

**Comment by sandy081** [comment]
Changed to no background colour

**Comment by joaomoreno** [comment]
Looks good!
