### ISSUE TITLE
Mouse focused item flickers as command palette is filtered even if results do not change

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67597]
Issue Type: <b>Bug</b>

**Repo**
1. Open the command palette
1. Mouse over one of the listed commands
1. Now type a bunch of spaces

**Bug**
Even though the list of commands has not changed, the highlight for the moused over command flickers slightly on each keystroke 

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_20636589|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by bpasero** [comment]
Even though the result does not change, we do call into the tree to update the number of elements. There is no logic in quick open to diff the items and avoid updates, given that the tree is super fast in rendering updates. 

I am not planning to change this, closing.
