### ISSUE TITLE
Renaming an Image File Acts Oddly

### ISSUE THREAD

**Issue by bobber205** [Microsoft/vscode#67593]
![bookmarked png legit 2019-01-30 15-31-02](https://user-images.githubusercontent.com/5841107/52019929-3e4d4a80-24a4-11e9-9ad2-41fd5009ed8d.png)
![bookmarked png legit 2019-01-30 15-30-55](https://user-images.githubusercontent.com/5841107/52019930-3ee5e100-24a4-11e9-8a22-3404f0794fc5.png)

Issue Type: <b>Bug</b>

Whenever I try to rename an image the command appears just fine but when I select it I get some random word that doesn't exist anywhere else in the project. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
autofilename|Jer|0.1.3
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.2.0
project-manager|ale|10.3.0
copy-relative-path|ale|0.0.2
jshintrc-generator|ben|1.0.0
sublime-duplicate-text|bri|0.2.5
simple-react-snippets|bur|1.2.2
prettier-vscode-standard|bys|0.22.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
es7-react-js-snippets|dsz|1.9.5
gitlens|eam|9.4.1
vscode-npm-script|eg2|0.3.5
copy-relative-path|eno|0.1.1
json-tools|eri|1.0.2
url-encode|fle|1.1.0
ruby|gro|0.0.6
vscode-import-formatter|hen|0.1.8
beautify|Hoo|1.4.7
better-line-select|kai|1.0.1
haml|kar|1.1.0
VS-code-vagrantfile|mar|0.0.7
uuid-gen|mat|0.0.1
dotenv|mik|1.0.1
nc-gcode|ML|0.13.0
atom-keybindings|ms-|3.0.5
heroku-command|pko|0.0.8
view-in-browser|qin|0.0.5
vscode-icons|rob|8.0.0
partial-diff|ryu|1.4.0
vscode-fileutils|sle|2.13.5
haml|vay|1.0.1
vscode-react-native|vsm|0.8.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
Doesn't look like native rename box. Is this an extension command you are invoking?

**Comment by bobber205** [comment]
Could very well be an extension but I don't remember a time I didn't have it available. Is there an easy way to find where a command is coming from?

**Comment by usernamehw** [comment]
Search for it in Keybindings GUI https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor . Hopefully the extension uses prefix before the command itself.

Just a blind guess: that it's probs `sleistner.vscode-fileutils`.
