### ISSUE TITLE
Task lists do not render in markdown preview

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#67596]
Issue Type: <b>Bug</b>

Task lists do not render in markdown preview.

See https://help.github.com/articles/about-task-lists/.

1. Create `task-list.md`
2. Add the following content

```
- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request
```

3. Open preview

EXPECTING: rendered as a task list with checkboxes
ACTUAL: renders `[x]`

As a comparison, this works in -
- Github
- https://dillinger.io/
- https://stackedit.io/
- Atom

![image](https://user-images.githubusercontent.com/2301847/52020752-bb31f180-24af-11e9-8486-dd8ae84640a0.png)

![image](https://user-images.githubusercontent.com/2301847/52020690-86259f00-24af-11e9-9a6e-6f2488a5910e.png)

![image](https://user-images.githubusercontent.com/2301847/52020551-ea942e80-24ae-11e9-9bf5-3bc18ae698a7.png)

VS Code version: Code - Insiders 1.31.0-insider (1b575168183b8e1d3a988f4cc8a5c7d15bce3c7c, 2019-01-28T06:14:22.178Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.17GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.7
prettier-vscode|esb|1.7.3
flow-for-vscode|flo|1.0.1
vscode-auto-open-markdown-preview|hnw|0.0.4
sort-selection|jmr|1.0.1
vscode-styled-components|jpo|0.0.25
python|ms-|2019.1.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.5.1
java|red|0.37.0
sass-indented|rob|1.5.1
mdx|sil|0.1.0
vscode-fileutils|sle|2.13.5
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1

</details>

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

**Comment by joshunger** [comment]
@usernamehw thank you 👍
