### ISSUE TITLE
FileSystemProvider: Explorer cannot copy/move directories from disk to provider, only files

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#67590]
- VSCode Version: 1.31.0-insider 2019-01-30T06:11:27.450Z 2c987b20a4d65ee51c48b9e4eb8f50c926199468 
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Create a custom [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider)
2. Open a workspace with one disk-based folder, and one custom uri root.
3. Drag/alt-drag any file from disk to the provider.  Note that it works as expected.
4. Drag/alt-drag any folder from disk to the provider.  Note that it fails with `File is directory: Error: File is directory`.

Moving/copying folders is supported for disk folders in the explorer view, it seems like the provider api as is should make this possible for provider uris as well.

**Comment by bpasero** [comment]
via https://github.com/Microsoft/vscode/commit/deab785846dae90cf7a72b8aaaec35945be8303c I also added support for recursive copy of folders.
