### ISSUE TITLE
Integrated terminal fails to launch after opening folder

### ISSUE THREAD

**Issue by wallacewinfrey** [Microsoft/vscode#67594]
Issue Type: <b>Bug</b>

Integrated terminal works fine until I open a folder. After opening a folder, it fails to launch a terminal and returns this error:

`The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)`

Unlike the conditions reported in #62953, this is in the absence of any missing files. To verify the behavior, I created a new folder, **test**, with no files in it. Then I opened the integrated terminal in VSCode, no issues, but after I opened the newly-created **test** folder, the integrated terminal would fail to launch.

FWIW, if I enable the [shell-launcher](https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher) extension, I am able to open powershell, in the **test** folder directory, without issue, via the shell-launcher shortcuts. Note that the path to powershell is the same in both:

**_integrated shell:_**

`"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"`

**_shell-launcher extension:_** 
```
"shellLauncher.shells.windows": [{
    "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "label": "PowerShell",
    "launchName": "powershell"
  }]
```
Given the difference in behavior between the integrated terminal the shell-launcher extension, we can rule out any path issues (i.e. #65433), at least as far as the executable is concerned.

Finally, it should be mentioned that the behavior occurs with or without the shell-launcher extension enabled.

Here's a gif that demonstrates the behavior:

![vscode-issues-opening-terminal-after-opening-folder](https://user-images.githubusercontent.com/1929725/52012620-48694c00-2498-11e9-8b5c-cd55ad3b6a27.gif)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (12.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-launcher|Tyr|0.3.0

</details>

**Comment by Tyriar** [comment]
Could you set log level to trace (F1 > "log level") then open the terminal that fails and check this output tab:

<img width="629" alt="screen shot 2019-02-01 at 6 18 44 am" src="https://user-images.githubusercontent.com/2193314/52128239-45ca3c00-25e9-11e9-896a-29b54dc691f1.png">

It should give more details on how the terminal is launching.

You could also check the output for the shell launcher one so we can see the difference.

**Comment by rorypeck** [comment]
delete the whole folder "C:\Users\roryp\AppData\Roaming\Code" can fix it
