### ISSUE TITLE
`git.autofetch` does not match setting `git.autoFetchPeriod`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67599]
While verifying #57910 on Insiders 1.31:

![image](https://user-images.githubusercontent.com/4033249/52021579-9a1ad200-24aa-11e9-8d03-0361230cd4f2.png)

One character less and both show up

![image](https://user-images.githubusercontent.com/4033249/52021582-a30ba380-24aa-11e9-9342-a32f44006be5.png)

**Comment by roblourens** [comment]
If there is an exact setting match, then we don't show any other matches. It can be confusing where there is a setting that is a substring but this is by design.
