### ISSUE TITLE
'Select all' in Open Editors view selects all views

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#67592]
Issue Type: <b>Bug</b>

Testing #63717

**Repo**
1. With multiple view groups
1. In the open editors panel
1. Run `select all`

**Bug**
Everything is selected. I'd expect that only the elements of the current group are selected first

VS Code version: code-oss-dev 1.31.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by joaomoreno** [comment]
@isidorn Another good reason to move to a tree over there. Maybe next month?

**Comment by isidorn** [comment]
@joaomoreno not convinced yet. Also next month I am out, so let's discuss in March.
