### ISSUE TITLE
Select all in explorer also selects parent folder 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67591]
Issue Type: <b>Bug</b>

Testing #63717

**repo**
1. In the file explorer
1. Select a sub folder
1. Run select all

**Bug**
The parent folder is also included in the selection

![screen shot 2019-01-30 at 3 07 12 pm](https://user-images.githubusercontent.com/12821956/52018921-e5c87e00-24a0-11e9-816a-6a008011966c.png)

Here I started with the `syntaxes` folder selected. After the first `select all`, the `csharp` parent folder is now also selected. I'd expect that only the child items would be selected

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|-psn_0_20636589|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by joaomoreno** [comment]
Yeah good point.
