### ISSUE TITLE
Issues with html customData schema

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67609]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67306.

I had the following issues with the [html custom data schema](https://raw.githubusercontent.com/Microsoft/vscode-html-languageservice/master/docs/customData.schema.json) when using it to drive intellisense and validation of my customData definitions:

- no intellisense for valueSet for global attributes
- no intellisense in the top level array of globalAttributes and valueSets
- no intellisense in the top level array in valueSets
- no validation warning when defining a valueSet like this
```json
            "values": [
                "_value21",
                "_value22"
            ]
```
     

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.0.0

**Comment by octref** [comment]
I'm using `anyOf` for Array's items, so it provides a basic completion

![image](https://user-images.githubusercontent.com/4033249/52086011-b413ed80-255a-11e9-82d5-331f10e2c1ee.png)

However, ideally it should complete like the `configuration` in `launch.json`. 

![image](https://user-images.githubusercontent.com/4033249/52086040-c8f08100-255a-11e9-98a0-97a4db716471.png)

Expanded:

![image](https://user-images.githubusercontent.com/4033249/52086058-d279e900-255a-11e9-963c-061e5a3fcde8.png)

Will do that once I figure out what's the magic JSON schema I need to write.

**Comment by octref** [comment]
Tracked in #67609.

**Comment by aeschli** [comment]
Verified that values are not verified against string.

To get richer code completion proposals, use [defaultSnippets](https://github.com/Microsoft/vscode/blob/f125fdfa20b217dea34001eac9866322418226ce/src/vs/base/common/jsonSchema.ts#L55)

I mentioned this in #67747
