### ISSUE TITLE
Welcome page extension suggestions should not be hardcoded into our source code

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#67600]
Issue Type: <b>Bug</b>

**Bug**
On the welcome page, we hardcode some recommended extensions for the `Tools and languages` section.

**Request**
Pull these recommendations from the `product.json` instead

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_20636589|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by chrmarti** [comment]
The problem with making this configurable is / might be that the UI doesn't scale well, so one has to be careful not to put too many extensions in.

Do you have a specific use case in mind?

**Comment by bhavyaus** [comment]
We no longer recommend extensions in the welcome page.
