### ISSUE TITLE
Incomplete colorization when opening files

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67607]
I have been seeing this randomly, I think just the past week or so. I can't repro it consistently. Reopening the file fixes it. Lmk if I can collect more info.

- Open a file
- Scroll to the bottom
- See that the colorization stops at some point or is incomplete

Example:

extensionsActions.ts
![image](https://user-images.githubusercontent.com/323878/52025348-d2291180-24b8-11e9-969e-112834545c63.png)

**Comment by alexandrudima** [comment]
I've changed something in this area, and I want to investigate...

**Comment by alexandrudima** [comment]
I could finally reproduce in that file when leaving the viewport around an unmatched `}` and scrolling up and down next to `}` until tokenization catches up:

![kapture 2019-01-31 at 22 45 11](https://user-images.githubusercontent.com/5047891/52087507-ef89d880-25a9-11e9-9d99-95cc1f833e59.gif)

**Comment by roblourens** [comment]
You turned my "random thing I saw once" report into real repro steps, nice! 👏
