### ISSUE TITLE
Expanded folders are not sorted when code is opened

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#67606]
Issue Type: <b>Bug</b>

Summary:
Already expanded directories in the explorer view do not appear to be sorted when VSCode is first opened. Directories that start collapsed, and are then expanded, do get sorted properly. Additionally, hitting the refresh button or changing explorer's sort order to something else and then back to the default causes everything to get sorted correctly again.

(I've shortened the names of the files/directories below.)

Actual:
```
+ lib
+ nod
- src
    Err.json
    ILo.ts
    (more files)
  + bin
    bin.yaml
  + com
  + dec
  + dia
    dia.yaml
  + mod
  + sym
    tsc.json
+ tes
(more files)
```

Expected:
```
+ lib
+ nod
- src
  + bin
  + com
  + (more directories)
    bin.yaml
    dia.yaml
    Err.json
    (more files)
+ tes
(more files)
```

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:20:25.145Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by isidorn** [comment]
@joaomoreno just pushed a fix for this afaik

**Comment by mattacosta** [comment]
Yep, appears to be fixed.

xref: #67633

**Comment by isidorn** [comment]
Thanks, adding verified label
