### ISSUE TITLE
Add schemas to customData samples

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67608]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67306.

Since we have JSON schemas, we should make it easier for people to use them.  We should add them to the samples and also tell people how to use them in the docs.

I added the following to my workspace settings:
```json
    "json.schemas": [
        {
            "fileMatch": [
                "/custom-data/html.json"
            ],
            "url": "https://raw.githubusercontent.com/Microsoft/vscode-html-languageservice/master/docs/customData.schema.json"
        },
        {
            "fileMatch": [
                "/custom-data/css.json"
            ],
            "url": "https://raw.githubusercontent.com/Microsoft/vscode-css-languageservice/master/docs/customData.schema.json"
        }
    ]
```

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.0.0

**Comment by octref** [comment]
Good point on using the URL to check against latest version of the schema. I updated both samples to use this setting and updated docs to suggest using `json.schemas`.

**Comment by aeschli** [comment]
See https://github.com/Microsoft/vscode/issues/67742 on how to improve that even more so that users don't need to add an association anymore.
