### ISSUE TITLE
[json] Multiline json keys can cause document symbols view to look weird 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67612]
Issue Type: <b>Bug</b>

Found while testing #65545

**Repo**
1. Open the following JSON file:

```json
{
    "a\nb": "abcd",
    "xyz": "pqrs"
}
```

1. Open document symbols

**Bug**
<img width="100" alt="screen shot 2019-01-30 at 6 29 38 pm" src="https://user-images.githubusercontent.com/12821956/52026586-3d74e280-24bd-11e9-8b18-d1cdf5616ca3.png">
 view

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|-psn_0_20636589|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by mjbvz** [comment]
Seems ok in both the breadcrumbs view and the outline panel view

**Comment by mjbvz** [comment]
This is a super low priority bug but I'm still the layout weirdness in 2e173fabe821d06a60f532b90d6e5d95c0e09a9c:

![screen shot 2019-02-26 at 2 39 22 pm](https://user-images.githubusercontent.com/12821956/53451730-5ac1a180-39d4-11e9-9af8-a7949f4dd512.png)

**Comment by aeschli** [comment]
Oh, yes, one more case...

**Comment by aeschli** [comment]
fixed by 5e85248c562fde9b5f0908731983caa89798dd83
