### ISSUE TITLE
can't require `vscode` on unit test

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#67619]
- VSCode Version: 1.30.2
- OS Version:  Mac 10.14.2

Steps to Reproduce:
I am building vscode extension in javascript. The unit tests are managed by `jest` and whenever there is a `require('vscode')` get run in the unit test, I will get this error:  `Cannot find module 'vscode' from xxx.js`. I have tried to remove `node_modules` directory and run `yarn install`, but it doesn't solve the issue. Other unit tests which don't dependent on `vscode` have no problem to run.

**Comment by dbaeumer** [comment]
Not sure if we support unit testing using `jest`. The recommended way right now is to use mocha.

**Comment by bpasero** [comment]
https://code.visualstudio.com/api/working-with-extensions/testing-extension
