### ISSUE TITLE
css customData: status not shown

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67611]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67306.

I cannot make status show up in intellisense or hover no matter which value I use.

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.0.0

**Comment by octref** [comment]
Updated schema so `status` is one of the four:

![image](https://user-images.githubusercontent.com/4033249/52082518-dc4b1e80-2551-11e9-9de1-7314924254e7.png)

And pushed a fix for not reading `property.status` (It's reading the old data format, `property.data.status`).

**Comment by kieferrm** [comment]
This was also an issue (but is being tracked separately. This on is about that the status that I defined for my custom property does not show up in when the property is proposed in IntelliSense or when I use the property in a css file and I hover over it.

**Comment by octref** [comment]
@kieferrm Schema fix is https://github.com/Microsoft/vscode-css-languageservice/commit/a348121775b8e7fbd28118c8a6b25a133cae8c14 whereas code fix is https://github.com/Microsoft/vscode-css-languageservice/commit/27f369f0d527b1952689e223960f779e89457374.

![image](https://user-images.githubusercontent.com/4033249/52093537-5e4a4000-2570-11e9-8120-ecc513ac8968.png)
