### ISSUE TITLE
PHP No Code Outline

### ISSUE THREAD

**Issue by HowdyMcGee** [Microsoft/vscode#67616]
- VSCode Version: 1.30.2
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a new PHP file
2. Add functions or classes.

```
<?php

Class Foo {

    public function bar() {
        
        // Run

    }

}
```

Does this issue occur when all extensions are disabled?: Yes
I have no extensions installed at this moment ( active or inactive )

At one point I had the outline working, an update in the last couple months has disabled it. It happens on more than just my specific system. All the issues I've run across which experience a similar problem point to extensions but that doesn't seem to be the issue here.

I've tried the same with VSCode Insiders but I experience the same problem. This occurs with small classes or large classes. **Is there a setting I need to set for this to work properly?**

> There are no editors open that can provide outline information.

**Comment by roblourens** [comment]
You need to install an extension for this. Try the "PHP Intellisense" extension
