### ISSUE TITLE
Tree ranking broken

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67623]
![image](https://user-images.githubusercontent.com/4033249/52035813-34493d00-24e0-11e9-9671-6fc433f43ca5.png)

Just after today's Insider update. Yesterday it was still 1-9, then 10-30 ranking.

**Comment by joaomoreno** [comment]
@octref Is this the explorer?

![image](https://user-images.githubusercontent.com/22350/52040576-24f5de00-2538-11e9-84cf-c2add19169c1.png)

Can you reproduce?

**Comment by joaomoreno** [comment]
Is this maybe SCM?

**Comment by joaomoreno** [comment]
Dupe of https://github.com/Microsoft/vscode/issues/67633

**Comment by octref** [comment]
Yeah it's explorer. Thanks for fixing it!
