### ISSUE TITLE
Files from other project may not be modified or at least a warnning message ~

### ISSUE THREAD

**Issue by clor09** [Microsoft/vscode#67622]
I'm currently working on my go project which was created and managed by `go mod`, but i think it may be the same with others like 'php composer'. 
Problem is:
I import a thirdparty lib and use it somewhere in my project, then `go mod` to download and cache the code in `cache dir`. When `Command + click` to goto defination of an interface which belongs to that lib, i noticed that i just can edit that file. As i expected i may not edit that file or at least some message may show to warn me that you are editing a file that not belongs to your current project, its dangerous.

**Comment by dbaeumer** [comment]
The part in the system that should make the file readonly would IMO be the corresponding language extension. However this first needs API. Moving to @jrieken

**Comment by gjsjohnmurray** [comment]
@jrieken - agreed, but AFAIK even with suitable OS level permission restrictions set (or Windows readonly bit) VSCode doesn't make the document readonly. Only when you try and save the changes do you discover you've wasted time editing the wrong document.

**Comment by bpasero** [comment]
I disagree with this request, I am not even sure how it would work. Imho the editor should not show files as readonly that are not readonly on disk.

**Comment by clor09** [comment]
well, like how it works in phpstorm(vendor dir for composer), i still think it's much better if i could get be warned when i edit a file that not belongs to the current project(the thirdparty lib source code in vendor dir as i think does not belongs to the current porject, at least it lies in my .gitignore).
Actually, i dont think this issue is really much about system level permission control.  it's about project level file access control. i would never modify a file in a lib that npm installed, what i should do is to PR my modify on github, when the lib dev team accept and PR merged, i go back to my project and just npm update.
