### ISSUE TITLE
`exit` in integrated terminal should collapse the panel or present a button to restart it

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6762]
Testing #6654 

![terminal-exit](https://cloud.githubusercontent.com/assets/5047891/15499740/08af10ce-21a6-11e6-95c3-0fe1aca14ae4.gif)

**Comment by Tyriar** [comment]
Good suggestion, that would also work around the problem of it not repainting correctly. Not super high priority so moving to June.
