### ISSUE TITLE
Themes: enabling after installation shows glitch in extension editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67628]
Refs https://github.com/Microsoft/vscode/issues/67434

- OS Version: Ubuntu 18

Steps to Reproduce:

1. be on a light theme
2. find the "Nord" theme
3. click the install button directly (do not open theme first)
4. :bug: the workbench switches to the theme but the extension editor stays white

![peek 2019-01-31 09-38](https://user-images.githubusercontent.com/900690/52041936-1a3d4800-253c-11e9-9769-b1032467b19a.gif)

**Comment by sandy081** [comment]
@bpasero I cannot repro it.

Even though it repros I suspect, probably a timing issue or web view is not handling it correctly.

**Comment by mjbvz** [comment]
Yes, timing related since it only happens sometimes in my testing

**Comment by mjbvz** [comment]
I tested my fix by reverting 65cc37aba6794f065debdbc83244532996522811. If we don't ship with auto theme enablement, I'm not sure this bug is relevant anymore (but this race could technically be hit in other flows as well)
