### ISSUE TITLE
VariablesResponse that have different IDs but same name and type causes second item to be hidden

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode#67624]
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

and 

Version: 1.31.0-insider (user setup)
Commit: 9606490e26f8cbe4d615305389d45e9b144ded7c
Date: 2019-01-30T15:20:25.145Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Tested with Cpptools extension 0.21.0

[vscode.zip](https://github.com/Microsoft/vscode/files/2815976/vscode.zip)

Download the attached sample and set a breakpoint on main.cpp:20
When the breakpoint hits, expand the variable `v`.

You should get two items named `<anonymous union>` but theres only one. Notice in the protocol log we send back two with variablesReference 1002 and 1003.

Protocol log:
```
<--   C (variables-14): {"command":"variables","arguments":{"variablesReference":1000},"type":"request","seq":14}
--> R (variables-14): {"request_seq":14,"success":true,"command":"variables","body":{"variables":[{"name":"v","value":"{...}","type":"tvec2<int>","evaluateName":"v","variablesReference":1001}]},"seq":80,"type":"response"}
<--   C (variables-15): {"command":"variables","arguments":{"variablesReference":1001},"type":"request","seq":15}
--> R (variables-15): {"request_seq":15,"success":true,"command":"variables","body":{"variables":[{"name":"<anonymous union>","value":"","type":"union {...}","evaluateName":"v","variablesReference":1002},{"name":"<anonymous union>","value":"","type":"union {...}","evaluateName":"v","variablesReference":1003}]},"seq":83,"type":"response"}
```

**Comment by pieandcakes** [comment]
You can probably do this on Linux also or WSL if you don't want to download MinGW or Cygwin.

**Comment by isidorn** [comment]
Yeah, we do not support two variables with the same name in the same "scope".
Since we do not treat variablesReference as an ID, but the name.
Leaving this open as a feature request.

**Comment by weinand** [comment]
@pieandcakes could you number your `<anonymous union>?`, e.g. `<anonymous union #1>` etc.

**Comment by pieandcakes** [comment]
@weinand We are looking at doing something about it since it breaks a bunch of c++ debugging.

**Comment by weinand** [comment]
This is not a regression, right?
VS Code always had this limitation.

**Comment by pieandcakes** [comment]
This is a newly reported customer issue. If what @isidorn is saying is true, then it probably existed before. In this case, since there can be multiple <anonymous unions> we are seeing this behavior.
