### ISSUE TITLE
vscode double click blocking doesn't work.

### ISSUE THREAD

**Issue by LOGANLEEE** [Microsoft/vscode#67621]
- VSCode Version: Version 1.30.2 (1.30.2)
- OS Version: 10.14.2 (18C54)

Steps to Reproduce:
![double click issue](https://user-images.githubusercontent.com/26853553/52031529-5387af00-2560-11e9-9950-23be424aa99e.gif)

i just want to block the word  by double click not going under line.
i can i fix this?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by LOGANLEEE** [comment]
If you double click the word then you can select the word 
and triple click the word then you can select line right?

Ok here is my point.

When i double click the word the mouse cursor get down to line 13 from line 12.

**I want to prevent or change the setting you select the word that i want to select not down the line.**

**Comment by alexandrudima** [comment]
@LOGANLEEE Can you please write down steps as precisely as possible? Here I am double clicking on words, and this works as expected for me, i.e. I cannot reproduce any jumping of the selection from one line to another:
![kapture 2019-02-01 at 9 01 27](https://user-images.githubusercontent.com/5047891/52110145-01966600-2600-11e9-8f81-9a0cbcb8ff75.gif)

**Comment by LOGANLEEE** [comment]
@alexandrudima sadly there is no steps. just it happened to any code in vscode
sometimes it worked as i expected, sometimes it not work as i expected.
![feb-01-2019 17-45-30](https://user-images.githubusercontent.com/26853553/52112279-5c07e480-2649-11e9-91ab-573288a6ccb2.gif)

**Comment by alexandrudima** [comment]
What are your settings? (`settings.json`)

**Comment by LOGANLEEE** [comment]
hello?

**Comment by alexandrudima** [comment]
@LOGANLEEE I have tried with your settings, and unfortunately, I still cannot reproduce.

**Comment by LOGANLEEE** [comment]
hello?
