### ISSUE TITLE
Workbench panel default location setting ignored

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#67639]
* open workbench
* add workspace or user setting `"workbench.panel.defaultLocation": "right"`
* :bug: nothing happens, the panel stays at the bottom (also after reload)

<img width="1282" alt="screenshot 2019-01-31 at 11 40 35" src="https://user-images.githubusercontent.com/1794099/52049110-372e4700-254d-11e9-9d1c-0e8c4c6f3d0e.png">

**Comment by isidorn** [comment]
The setting is "defaultPosition" so it takes precedence only in a new window.
It stays there after reload since you probably changed panel position in your workspace and is written in lcoal storage which takes precedence.
I understand how this can be confusing, and we should fix.

**Comment by Alisusu** [comment]
I hava the same question , and I set workbench.panel.defaultLocation default , but the panel always stays at the right

**Comment by jimmyko** [comment]
I got the same problem. I close the VScode and reopen it. The integrated terminal just remains to the bottom even I changed to right.

**Comment by simax** [comment]
Still broken :(

**Comment by Qadosch** [comment]
doesent work with local project settings, even after clearing cache

only works in global usersettings

**Comment by isidorn** [comment]
@sbatten forwarding to you since you own the layout now.

**Comment by sbatten** [comment]
fixed by e5054d1d42fb0d3ea6f5b4ba95545c26375847eb and 5b488cc2f87acb78a658ff3c84555b6ca33aaa80

**Comment by jrieken** [comment]
@sbatten Is the verification to check that the setting is flagged as deprecated?

**Comment by sbatten** [comment]
Yes, actually when I closed this, there was a change in behavior of the setting. The now behavior is that the setting is deprecated and has no effect since panel location is no longer a concept.
