### ISSUE TITLE
Custom data not hot updated

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#67636]
Test: https://github.com/Microsoft/vscode/issues/67306

- follow the test scenario.
- change the html.json file by for example renaming a value
- go back to the HTML file
- use code complete.

It still shows the old values.

**Comment by octref** [comment]
This is as-designed. This JSON custom data is mostly for framework compilers / static analyzer to emit metadata about components and ship it as part of a library. So HTML/CSS only load this on startup.

Also, invalidating old entries would bring in a lot more complexity.
