### ISSUE TITLE
Restarting the session is not respecting internal console options

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#6763]
- VSCode Version: Alpha
- OS Version: Windows 8

Steps to Reproduce:

1. Set the internal console options to openOnSessionStart
2. Launch the session
3. Console is shown as expected
4. Close the console
5. Restart the session

Expected to show the console after restart

**Comment by isidorn** [comment]
To verify: make sure the `openOnSessionStart` behaves as expected both when launching and when restarting debug sessions.
