### ISSUE TITLE
Custom CSS data: classes not proposed

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#67638]
Tests: https://github.com/Microsoft/vscode/issues/67306

- follow steps
- open css file
- empty it and type `:my-l`

Observe code complete is empty

<img width="567" alt="capture" src="https://user-images.githubusercontent.com/1931590/52048376-8b382c00-254b-11e9-8dd1-c35af3ed278b.png">

**Comment by octref** [comment]
Thanks, I fixed schema but forget to update the JSON parser, so it was reading `pseudoclasses` instead of `pseudoClasses`.

Fixed via https://github.com/Microsoft/vscode/commit/ef0f902787952638317d709e0c1c5030b47a79ac.

**Comment by octref** [comment]
For verifier: ensure this custom data would propose `:my-link` on completion:

```json
{
  "version": 1,
  "pseudoClasses": [{
    "name": ":my-link",
    "description": ":any-link pseudo class. See details at https://preset-env.cssdb.org/features#any-link-pseudo-class"
  }]
}
```
