### ISSUE TITLE
Cannot see the file path

### ISSUE THREAD

**Issue by WafeiBaBa** [Microsoft/vscode#67631]
Issue Type: <b>Bug</b>

When I create a powershell,  I cannot see the file path.

My PC is Win 10, and my vscode is setup version.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.56GB free)|
|Process Argv|C:\Users\Administrator\Desktop\MyRepository\test-vscode-go|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
intellij-idea-keybindings|k--|0.2.31
node-module-intellisense|lei|1.5.0
vscode-language-pack-zh-hans|MS-|1.30.2
cpptools|ms-|0.21.0
Go|ms-|0.8.0
PowerShell|ms-|1.11.0
java|red|0.37.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
