### ISSUE TITLE
Align Open Editor and double arrow down

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6764]
#6536

I understand the double arrow down action as an alternative UI to the open editor model. I would

* use the prefixes `left`, `right`, and `center` instead of the `~>` sequence
* use the same sort order
* have the same actions (close)

<img width="722" alt="screen shot 2016-05-24 at 11 50 55" src="https://cloud.githubusercontent.com/assets/1794099/15499719/edf01e40-21a5-11e6-9b23-73e80cbbe7fd.png">

**Comment by bpasero** [comment]
@jrieken can you clarify how this would work? 
* are you saying that ~ shows all editors and ~left shows all editors of the left group
* are you suggesting to have a close action within quick open?
* are you suggesting to use the same sort order for navigating across all groups vs a single group?

**Comment by jrieken** [comment]
> are you saying that ~ shows all editors and ~left shows all editors of the left group

No, first I suggest to not use `~`, then yes `left` shows all editors from the left group, `right` all editors from the right group (corresponding to the title the Open Editors section). 

> are you suggesting to have a close action within quick open?

Yes, like Cmd+P is having an icon to open to the side

> are you suggesting to use the same sort order for navigating across all groups vs a single group?

No, I suggest that the sorting of left/center/right groups equals the sorting of the corresponding quick open piece.

**Comment by bpasero** [comment]
+1 for making the groups more explicit in quick open and accessible.

@jrieken currently we also have `~` for showing a list of all opened editors in their spatial order (tabs like, `Cmd+Alt+Tab`) and then we have `~>` for showing editors in their MRU order per group (corresponds to pressing `Cmd+Tab`). Would you still expect `~` to work as today (with maybe added close actions)?

**Comment by jrieken** [comment]
I am slowly grasping the full complexity of this. So we have (1) spatial and (2) temporal order and we have listing of editors per group (L,C,R) and of all editors (*). That make it 2x4. I wonder if we can achieve the grouping by typing. ala `editors` shows spatial or temporal order and the `editor left` keeps the order but does further filtering and likewise with another prefix for the other sort order.

**Comment by bpasero** [comment]
@jrieken well we do not show spatial order per group, and we do not show MRU order across all groups, so we have 1 spatial across all and 1 MRU per group. I like the idea of having a way to type into a group (e.g. editors to show all and editors left to search within a group). I would not think there is a strong use case for MRU order across all editors or spatial order within a group (for now at least).

**Comment by jrieken** [comment]
> MRU order across all editors

Well, Cmd+P is showing that, right? I am not saying we need all of those. I am aiming for an inventory and then we might have different ideas.

**Comment by bpasero** [comment]
@jrieken Cmd+P is yet another source of navigation which does not match any of the ones we have for stacks/tabs because it is is a history of any editor you ever opened regardless of the editor being closed or not. Ctrl+Tab and Cmd+Alt+Tab get their items removed when you close an editor.

So, I think we end up having three: MRU in group, spatial across all groups and MRU in general editor history.

**Comment by bpasero** [comment]
I propose the following:

**Ctrl+Tab**
We allow to type something like `editor <left|center|right> <name>` to open a file from a group. We keep MRU sorting.

**Cmd+Alt+Tab**
We change this to `editor <name>` to pick an editor from any group. We keep spatial sorting.

**Cmd+P**
We do not change the behaviour from how it works today.

**Comment by bpasero** [comment]
Small update from ux meeting, we think "edt" is better than "editor" because faster to type. We already use short form "ext" for extensions.

**Comment by bpasero** [comment]
@jrieken we triggered a build if you want to verify this new behavior
