### ISSUE TITLE
editor.action.showReferences is 1 or 0 based?

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode#67649]
I'm a bit confused.

Here, this command is called with 0-based positions: https://github.com/Microsoft/vscode/blob/5dc52f0617cce8398dfbae9a081fd188b84fc352/extensions/typescript-language-features/src/features/referencesCodeLens.ts#L40-L45

Here, it seems to be implemented with 1-based:
https://github.com/Microsoft/vscode/blob/3e2dd462014cb56cb36f26ea33326bd6232e1328/src/vs/editor/contrib/referenceSearch/referenceSearch.ts#L158-L170

I cannot find where conversion happens? Is it a bug?

Am I right that [commands](https://code.visualstudio.com/api/references/commands) started from `vscode.` prefix are 0-based and which are not 1-based?

**Comment by jrieken** [comment]
Zero-based, e.g use the API-types not our internal types. There is some automatic massage for some types when appearing as command args. See https://github.com/Microsoft/vscode/blob/70160d0e580d0588e37c93fe8724014d76b00939/src/vs/workbench/api/node/extHostCommands.ts#L110-L138

**Comment by akosyakov** [comment]
@jrieken thank you
