### ISSUE TITLE
Search `retry` in Workspace Settings page shows incorrect result

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [Microsoft/vscode#67645]
- VSCode Version: 1.30.2
- OS Version: Debian 9 (hosted on VMWare Player 14 on Windows 10 1709)

Steps to Reproduce:

1. Open Workspace Settings page (`settings.json`) of an existing folder.
![image](https://user-images.githubusercontent.com/12868093/52056878-6de07d80-259e-11e9-8ccc-7302529a8313.png)

2. type in `retry` in `Search Settings` text box

3. watch the search result below, it shows `no settings found` first, then shows a lot of irrelevent settings.
![image](https://user-images.githubusercontent.com/12868093/52057020-e3e4e480-259e-11e9-82df-c8e3546e3819.png)
This makes me confused, the meaning of the search result almost have nothing to do with `retry`.

4. when search something definitely not exist (and not meaningful), the result is empty as expected
![image](https://user-images.githubusercontent.com/12868093/52058073-af265c80-25a1-11e9-97a8-d068d3c46ac4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
We also search a Bing service for settings that might be relevant. Sometimes it's not clear why a result shows up, especially for really short queries. They might have a word in the setting that differs from `retry` by a character or two, making a fuzzy match.
