### ISSUE TITLE
Vertical scrollbar is shown even if not needed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#67643]
- Enable `workbench.tree.horizontalScrolling`

![image](https://user-images.githubusercontent.com/10746682/52056007-4cad6c00-2561-11e9-82eb-faf18ec8842d.png)

**Comment by joaomoreno** [comment]
Same as https://github.com/Microsoft/vscode/issues/67441

**Comment by carlocardella** [comment]
It has another annoying side effect: on all my machines (Windows and macOS, Stable and Insiders), when opening a new VSCode window the Open Editor list is always scrolled to be bottom even if there is only one item in it (the Welcome view for example): 

![image](https://user-images.githubusercontent.com/5784415/88463740-dd6cbb80-ce69-11ea-9400-0ffb28db7277.png)

![image](https://user-images.githubusercontent.com/5784415/88463743-e52c6000-ce69-11ea-8bc4-eb71bbf68246.png)
