### ISSUE TITLE
Default settings json should be a single array of settings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#67642]
Default settings json should be a single array of settings

**Comment by roblourens** [comment]
I don't understand what you mean by a single array

**Comment by sandy081** [comment]
Currently I see this when the default settings are opened. 

![image](https://user-images.githubusercontent.com/10746682/52077473-5ea70300-2591-11e9-9465-81ab24f7ec7c.png)

This should be single array of settings and properly formatted.

**Comment by roblourens** [comment]
Without commonly used settings it could be a flat object, yeah.
