### ISSUE TITLE
Send perf.mark as telemetry

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67650]
We have `perf.mark` to measure things. However, for telemetry we use a processed (condensed) variant of that data. We more querying power we should send marks as they are

**Comment by jrieken** [comment]
fyi @isidorn

**Comment by isidorn** [comment]
Yes this would be great.
As a debt item we should go through our perf.mark and make sure they are measuring the correct thing. At least for my perf mark explorer I should measure from point 0 (not constructed) to fully ready. Currently I measure from contructud to fully ready.

**Comment by jrieken** [comment]
Well, some perf-marks build our reports. So we shouldn't change those too much. For the rest it's your responsibility. Think of it like a unit test.

**Comment by jrieken** [comment]
To verify: Set log level to trace, open telemetry output channel, restart and make sure a `startupRawTimers` event is send
