### ISSUE TITLE
Investigate SIGUSR1 usage

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#67655]
It seems `SIGUSR1` can be used with electron 3.x (see https://github.com/electron/electron/issues/11287). We should see if that's true and iff so adopt it where needed.

**Comment by jrieken** [comment]
This indeed seems to work (tested on macOS), apparently there is no support for windows. Still, I think it's worth to consider for automatic extension host profiling

**Comment by jrieken** [comment]
Some work did already happen: https://github.com/microsoft/vscode/commit/67ffab8dcd1a6752d8b62bcd13d7020101eef568

**Comment by weinand** [comment]
No plans to work on this since js-debug provides this functionality in new ways.
