### ISSUE TITLE
I can't set the font to fantasque Sans Mono

### ISSUE THREAD

**Issue by eatradish** [Microsoft/vscode#67663]
- VSCode Version: OSS 1.30.2
- OS Version:
```
 🌝👍 [ ~ ] uname -a && lsb_release -a
Linux eat-x220i 5.0.0-aosc-main #1 SMP PREEMPT Thu Jan 24 10:39:13 CST 2019 x86_64 GNU/Linux
LSB Version:	n/a
Distributor ID:	AOSC OS
Description:	AOSC OS
Release:	5.3.2
Codename:	eMMC

```

Steps to Reproduce:

1. set the font to "Fantasque Sans Mono"
2. Can actually see that it fallback to the second font in the font-family list

Does this issue occur when all extensions are disabled?: Yes/No: No

**Comment by eatradish** [comment]
I found the problem with the extensions...close this issue.

**Comment by paurullan** [comment]
@eatradish what extensions did you found were the culprit?
Did you finally made the font work?
