### ISSUE TITLE
Source Control Extension Crashes

### ISSUE THREAD

**Issue by dagrooms52** [Microsoft/vscode#67665]
Issue Type: <b>Bug</b>

Source Control extension (using git) crashes upon any interaction. This is after installing the Settings Sync extension, which creates a GitHub Gist of VS Code settings.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.79GB (46.18GB free)|
|Process Argv|~/.gitconfig|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
gitlens|eam|9.4.1
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.8.0
import-sorter|mik|3.2.0
vscode-autoprefixer|mrm|2.2.0
vscode-azureappservice|ms-|0.11.0
vscode-azurefunctions|ms-|0.13.1
vscode-azurestorage|ms-|0.5.0
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|0.4.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.1
material-icon-theme|PKi|3.6.2
tsimporter|pmn|1.2.14
vscode-css-peek|pra|2.2.0
code-settings-sync|Sha|3.2.4
bootstrap4-vscode|the|6.0.3
vscode-docker-registry-explorer|Tqr|0.1.3
scss-to-css|yut|1.2.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by joaomoreno** [comment]
What does "crashes" mean? Please provide more details, maybe a screenshot?

**Comment by dagrooms52** [comment]
Sorry for my brevity, I've reproduced the issue and have some better information now.

After enabling the Settings Sync extension again and visiting the source control tab, it hangs for a while on the message "No source control providers registered".

I then interact with the source control tab by trying to pull, push, or click in the "revert changes" dash, and get a popup stating "Extension host terminated unexpectedly" as seen in this screenshot:

![source_control_crash](https://user-images.githubusercontent.com/8743446/52088397-90ec3c80-2560-11e9-8dae-05c8e39f4240.PNG)

This is the console output from the crash, which I was not able to copy out of the debugger:

![extension_host_errors](https://user-images.githubusercontent.com/8743446/52088399-934e9680-2560-11e9-9cbc-7f2f142657f0.PNG)

**Comment by joaomoreno** [comment]
Does this reproduce without enabling the Settings sync extension?

**Comment by dagrooms52** [comment]
No, Settings Sync extension being enabled causes this issue to occur. I've been running Code with the extension disabled and the crash has not occurred since disabling.

**Comment by alexandrudima** [comment]
@dagrooms52 In this case, please open an issue directly against the Settings sync extension
