### ISSUE TITLE
integrated terminal: customizing colors through user settings is a bit weird

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6766]
Testing #6654 

Our story so far when it comes to customizing colors is through themes (fyi @aeschli ). Exposing color values in the user settings makes our story inconsistent. e.g. it would be nice to share a theme as an extension that also customizes the integrated terminal, I think the theme format is open-ended to support any amount of additional keys? This also opens the door for requests such as: "I want to change the color of keywords from my settings", which is a path we don't really want to go to

It is also needed that each color would have a light and a dark variant in the settings. if I tweak the values in the light theme, they might not look good when I switch to a dark theme, etc.

**Comment by Tyriar** [comment]
It wouldn't make sense to pull the values from themes. tmThemes, while not very strict, simply would not have these new values when migrating from other editors, so the majority of themes would not have the values we desire. Also, currently 2 themes cannot be applied at once.

This situation, while not ideal, allows the user to customize the colors in isolation on their theme.

Possible steps forward:

- UI themes #1231
- Terminal themes/extensions that set these values?

There is also more customization that may be added in the future, I believe it's possible to set a 255 color palette for the terminal as well.

**Comment by alexandrudima** [comment]
I think #1231 is the best way forward, we need to have VSCode specific themes. I was suggesting TM themes as they have an open format, but you have a very good point: lots of people would like to have a vscode theme A (that changes file explorer colors, terminal colors (maybe even icons?), etc.) + a TM theme B (that changes tokens, selection color, etc).

My recommandation for now is to remove the colors from the settings, and maybe increase the priority of #1231.

@aeschli Your thoughts?

**Comment by aeschli** [comment]
"integratedTerminal.ansiColors.brightBlack"
"integratedTerminal.ansiColors.cyan"
"integratedTerminal.ansiColors.blue"

I also think it make no sense to have these colors as user settings. A user would not choose to have 'blue' being a red color.
VS Code should define these colors, in three flavors, for the light and dark and hc_black (high contrast) base theme.

I agree that once we add theming the workbench we can look into this again.

Also in general, let's not add a configuration setting before we get multiple requests for it. We want to keep the number of settings small to keep the product slick and avoid feature creep.

**Comment by Tyriar** [comment]
I'm all for increasing the priority of #1231, was going with settings values as that's what most other editors. I'll remove the colors for now, it was trivial to add.

**Comment by Tyriar** [comment]
@alexandrudima @aeschli is there some event I can listen to for when the theme changes?

**Comment by Tyriar** [comment]
Nevermind, I found `ThemeService` :smile:

**Comment by Tyriar** [comment]
Improved light theme in https://github.com/Microsoft/vscode/commit/a38efd89f992b75644cb0e8f997bab2543d2bd65

**Comment by Tyriar** [comment]
FYI I closed #1231 in favor of #76
