### ISSUE TITLE
Type checking doesn't update when using "npm link"

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/vscode#67664]
- Create two node projects, A & B, with A dependant on B (i.e. A includes B in package.npm)
- Run "npm link" on B
- Run "npm link B" on A
- Make a change to B and recompile
- Make change to A that depends on new change in B
- Project A will show errors as if change to B didn't happen.  A still compile fine (so it has change to B), but type checking in VSCode UI acts as if B wasn't updated
- Only way to get VSCode to update is to close VSCode and reopen it

**Comment by mjbvz** [comment]
I can't repo this with this example project: https://github.com/mjbvz/vscode-67664

Please share more information about your project setup and more detailed steps to reproduce the problem. Also, be sure to test on the latest vscode build

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
