### ISSUE TITLE
Scroll bar jumpy when mouse moves away from window

### ISSUE THREAD

**Issue by nmoinvaz** [Microsoft/vscode#67669]
This issue is about the scroll bar being jumpy when scroll dragging is not precise with the scroll bar. Sometimes when scrolling the editor window, the mouse can go outside of the window's tracking area. It might be an underlying Electron issue but the bug hurts the development experience when tracking through source files that have tons of lines of code - especially when the scrollbar is so tiny. The Chrome browser (also chromium based) is able to handle this scenario properly by tracking the mouse movement across the desktop when the mouse is dragged during scrolling. 

I have included an animated gif to show this behavior and compare both Chrome and VSCode:

![vscode-mouse-tracking](https://user-images.githubusercontent.com/1364432/52078149-5f1aac00-2547-11e9-84b3-8b3a51756536.gif)

Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-44-generic

Steps to Reproduce:

1. Drag the editor's scroll bar 
2. While dragging move the mouse outside of the window's immediate tracking area - outside of the window by maybe 20 pixels.

Does this issue occur when all extensions are disabled?: NA

**Comment by escaner** [comment]
I was about to report this issue. It happens in Linux (tried in OpenSuse Tumbleweed and Fedora 28), but does not happen in Windows 10.
Happens also with all extensions disabled.

**Comment by nmoinvaz** [comment]
It does not happen on macOS.

**Comment by escaner** [comment]
It is fixed in 1.31.0. Thanks! :)

**Comment by nmoinvaz** [comment]
It is fixed for me in 1.31.0 also. I think it is probably fixed due to Electron 3 upgrade in that release.
