### ISSUE TITLE
Double comment

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#67677]
Refs: https://github.com/Microsoft/vscode/issues/67294

1. Start review from VSCode 
2. Add a comment -> finish review
3. The comment is double posted

![double](https://user-images.githubusercontent.com/1926584/51906997-dd4f4500-23c5-11e9-93d1-5578025f524d.gif)

**Comment by rebornix** [comment]
We will create a comment when starting the review and since it's not finished yet, clicking finishing review will create another comment with the same content in the comment widget.

**Comment by RMacfarlane** [comment]
I'm no longer able to reproduce this, looks like it's been fixed. The comment widget now collapses and clears the text area immediately
