### ISSUE TITLE
Git status bar fails to show branch of current file, on startup

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode#67670]
Issue Type: <b>Bug</b>

When you open vscode-insder and you have two folders in the workspace on different branches it is automatically positioned on the first folder git branch also if the active file tab is of another folder. 
You need to deselect and select the file tab again to see the correct branch/git. This seems to happen only at vscode startup.

VS Code version: Code - Insiders 1.31.0-insider (7f136b44cff0cd3486ac88b43598b8c72b025d16, 2019-01-31T06:15:21.895Z)
OS version: Linux x64 4.18.0-13-generic

**Comment by k-zhai** [comment]
Hi, is this taken?

**Comment by bhack** [comment]
I don't know exactly the full perimeter of the bug. But you can reproduce in this way:

- Create a workspace with two folder (one on a git branch and the second one with a worktree folder on another branch)
- Open a file from the first folder (in order as you see in the workspace view)
- Open a file from the second folder (in order as you see in the workspace view)
- Close vscode
- Open the application and you are positioned on the file on the second folder  but the git branch in the bottom left panel is the one of the first folder.
- If you change the focus between the two opened file tabs and back the git branch in the panel it is refreshed correctly.

**Comment by k-zhai** [comment]
@flurmbo Can I take this?

**Comment by zhaomiing** [comment]
same issue on macOS

**Comment by NizamLZ** [comment]
@k-zhai Are you still working on this issue? Else I would like to give it a try. I could reproduce the bug.

**Comment by k-zhai** [comment]
Yeah, I'm close to a fix.

**Comment by callummr** [comment]
Saw it had been a while since there was progress on this so had a stab. Haven't found any issues with this fix so far.
