### ISSUE TITLE
VS Code - IntelliSense suggestions consistently being incorrectly selected while typing- 

### ISSUE THREAD

**Issue by JaimeStill** [Microsoft/vscode#67679]
**Visual Studio Code Details**  
- Version: 1.30.2 (user setup)
- Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
- Date: 2019-01-07T22:54:13.295Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- OS: Windows_NT x64 10.0.17763

**Issue**  
When typing `this.` in TypeScript, IntelliSense suggestions are intermittently (but frequently enough to be quite frustrating) being automatically selected without prompting. At first, I thought I may have been accidentally hitting another key while typing, but it is now apparent that this is not the case.

I was able to capture a clip of this happening:

![intellisense](https://user-images.githubusercontent.com/14102723/51202927-d99fc680-18cd-11e9-8843-767094708dc1.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
