### ISSUE TITLE
Open large files in new window by default

### ISSUE THREAD

**Issue by Revadike** [Microsoft/vscode#67675]
Open large files in new window by default, because with tabs if you want to switch between them, vscode has to load the large file every time it selects the tab of the large file. This leads to a bad user experience.
A separate window keeps the large file open, which then doesn't have this issue.

**Comment by bpasero** [comment]
You can easily just split the editor into 2 and keep the one always open while having multiple tabs on the left:

![image](https://user-images.githubusercontent.com/900690/52111576-5fc54800-2604-11e9-813a-b339b6e608fc.png)
