### ISSUE TITLE
Explorer Files not sorted

### ISSUE THREAD

**Issue by Erchamion** [Microsoft/vscode#67674]
Issue Type: <b>Bug</b>

files and directories not sorted correctly.
![file_sort](https://user-images.githubusercontent.com/11239968/52080517-f7278e00-2565-11e9-8b1a-39684aa192c9.png)

VS Code version: Code - Insiders 1.31.0-insider (7f136b44cff0cd3486ac88b43598b8c72b025d16, 2019-01-31T08:03:26.905Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Erchamion** [comment]
Not sure if it is one of the above but when I switched from Explorer => Search => Explorer the sorting was corrected.  I don't know what actions led to the tree being unsorted.

I also double checked my explorer search settings and it was set to default.

If / when I can reproduce at will I'll post back.

**Comment by isidorn** [comment]
This is fixed in the latest insiders. Thanks a lot for using insiders and let us know if you see this issue again.
fyi @joaomoreno
