### ISSUE TITLE
Middle mouse click in scroll bar pastes text in file area (Linux)

### ISSUE THREAD

**Issue by escaner** [microsoft/vscode#67671]
Issue Type: <b>Bug</b>

Steps to reproduce in Linux:

1. Open a file in vscode
2. Double left click or left click and drag with the mouse in the text to select something, it auto-copies to the X clipboard
3. Middle click with the mouse in the vertical scroll bar area, the croll bar moves the clicked position
4. When releasing the middle button, the selected text gets pasted into the file

The text should only be pasted when you middle click in the text window, not in the scroll bar.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.20.2-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T5870  @ 2.00GHz (2 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|3.75GB (1.43GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by escaner** [comment]
I see that this problem was also commented in the 5th (last) suggested duplicate, but that issue is for a similar issue in another part of the vscode window.

**Comment by escaner** [comment]
Bug still present in vscode 1.35.1

**Comment by alexandrudima** [comment]
@escaner I cannot reproduce this anymore. Can you please also try with the latest insiders - https://code.visualstudio.com/insiders/

**Comment by escaner** [comment]
It is still present in 1.39.1, but seems fixed to me in the 1.40.0-insider version of your link.
Thanks a lot! :)
