### ISSUE TITLE
Disabled extensions are enabled when there are updates

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#67687]
Issue Type: <b>Bug</b>

* Install an old version of Vim extension (or any extension needs a reload of the window)
* Disable the extension
* Trigger extension updates
* Vim extension is enabled, and the extension viewlet saying `reload required`

We may want to check enablement here.

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv|-psn_0_1831359|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
solargraph|cas|0.19.2
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.3
vscode-pull-request-github-insiders|Git|1.31.0
ocaml|hac|0.6.43
beautify|Hoo|1.4.7
references-plusplus|jri|0.0.5
graphql-for-vscode|kum|1.13.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.9
vscode-language-pack-zh-hans|MS-|1.31.2
python|ms-|2019.1.0
azure-account|ms-|0.8.0
Go|ms-|0.8.0
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|0.4.0
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
debugger-for-ios-web|msj|0.1.2
color-highlight|nau|2.3.0
vetur|oct|0.14.5
subtitles-editor|pep|1.0.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.2
seti-icons|qin|0.1.3
project-snippets|reb|0.5.0
ruby|reb|0.21.0
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.5.3
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.0

(10 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@alexandrudima We have to check if an extension is enabled before adding it.

**Comment by sandy081** [comment]
Created a PR with the fix - https://github.com/Microsoft/vscode/pull/67710.
