### ISSUE TITLE
Unable to deploy VSCode to AZURE ILB ASE

### ISSUE THREAD

**Issue by abdulrm** [Microsoft/vscode#67681]
Issue Type: <b>Bug</b>

Error : unable to verify first certificate

There is no issue with certificate and the issue is only with VScode. And i believe that VScode is not reading my cert from local machine.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2397)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|4.00GB (1.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.11.0
azure-account|ms-|0.8.0

</details>

**Comment by Tyriar** [comment]
I'm going to need a little help in identifying what component is the problem. Do you think this is an extension issue, proxy problem, terminal or something else?

**Comment by Tyriar** [comment]
@abdulrm how is the cert being used exactly? Through the vscode-azureappservice extension?

/cc @joaomoreno
