### ISSUE TITLE
code --installl-extension needs id which is not very user friendly

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6768]
- VSCode Version: code-alpha
- OS Version: Linux

To install an extension via the command line you need to know the extensions id which is currently not very visible (only available in the URL). We should either state that this way to install and extension is for pure automation or we should make the feature more user friendly. If I for example type code --install-extension vscode-eslint it should tell me that it knows about dbaeumer.vscode-eslint and if I want to install that plugin.

**Comment by joaomoreno** [comment]
Closing as designed. There are now help messages that guide the user towards knowing what ID to use.
