### ISSUE TITLE
Can't select/highlight text in Extensions search bar

### ISSUE THREAD

**Issue by fourpastmidnight** [Microsoft/vscode#67689]
- VSCode Version:

Version: 1.31.0-insider (user setup)
Commit: 7f136b4
Date: 2019-01-31T08:03:26.905Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Enter some text into the search bar in the extensions pane. Any text will do.
2. Ensure your cursor is at the end of the text input
3. Press SHIFT+HOME to select all text.
4. None of the text is selected, but the cursor has moved to the beginning of the input box.

Does this issue occur when all extensions are disabled?: Yes

**Comment by fourpastmidnight** [comment]
Hmm, it just started working again? I  don't know whether to leave this open or close it....

**Comment by fourpastmidnight** [comment]
It's definitely hit or miss whether or not selecting text in the search box works.

**Comment by sandy081** [comment]
@fourpastmidnight It works for me, do you see any errors in the console?

**Comment by fourpastmidnight** [comment]
It seems to be working today--though, I did restart it twice, and so it updated twice. I'll close for now.
