### ISSUE TITLE
Issues with css customData schema

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#67686]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/67306.

I had the following issues with the [html custom data schema](https://raw.githubusercontent.com/Microsoft/vscode-css-languageservice/master/docs/customData.schema.json) when using it to drive intellisense and validation of my customData definitions:

- no mentioning of `spec` in the doc so I don't know what it is
- no intellisense for `status` although it's an enums
- can we better support value for `browsers`?

VS Code version: Code - Insiders 1.31.0-insider (9606490e26f8cbe4d615305389d45e9b144ded7c, 2019-01-30T15:15:08.172Z)
OS version: Darwin x64 18.0.0

**Comment by octref** [comment]
> spec

That came in as part of MDN SVG data. I removed it because we don't use it in anyway yet.

We might in the future allow `links` of the form

```
[
  { name: 'MDN', link: 'https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning' },
  { name: 'W3C', link: 'https://drafts.csswg.org/css-fonts-3/#propdef-font-kerning' }
]
```

And render them as Markdown links in the bottom of the description.

> no intellisense for status although it's an enums

https://github.com/Microsoft/vscode/issues/67611#issuecomment-459552538. IntelliSense now works in both JSON and CSS.

> can we better support value for browsers?

Can you elaborate? Do you mean something like `{ name: 'Chrome', version: '30' }` instead of `C30` for the items?

**Comment by kieferrm** [comment]
I was wondering whether we could be more helpful to compose the actual strings such as "FF30". There is only a fixed number of prefixes allowed. I haven't checked whether in a json schema you can say something like `[FF|S|O|C]\d\d`. If that's not possible, your proposal `{ name: 'Chrome', version: '30' }` makes good sense.

**Comment by aeschli** [comment]
It's possible to define a regex in the schema that validates for syntaxes like 'C30,I9'... also with a specific error message. Use `pattern` and `patternErrorMessage` for that.

The advantage of supporting the `C1,IE9..` syntax is that it saves quite a lot of space as well as standardises the way of how browsers and versions are called. Having them standardised will allow us to represent them as icons like in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#Browser_compatibility

**Comment by octref** [comment]
OK, did this instead:

![image](https://user-images.githubusercontent.com/4033249/52138649-a87c0180-2602-11e9-99e0-0fb64e0e4088.png)

@aeschli `patternErrorMessage` is not suggested when editing the schema, FYI.
