### ISSUE TITLE
How do I utilize the entire space with text only?

### ISSUE THREAD

**Issue by foundationalnotes** [Microsoft/vscode#67684]
I would like to wordwrap to the edge or near the edge of the window in VSC. I've tried changing many settings in both settings and user settings specific to markdown. But nothing changes. I believe there might be an invisible column/pane?

In sublime text I simply add wrap_width of 0 and remove the minimap. 

[Here is a screenshot.][1] **You can see there is a large amount of space not being utilized. Can you help me wrap my text into this empty area?**

Thank you for your help.

  [1]: https://i.stack.imgur.com/MIDOa.png

**Comment by alexandrudima** [comment]
This is due to using a non-monospace font. You can change your font family to a monospace font. Let's continue tracking in #2654
