### ISSUE TITLE
Cannot drag explorer list filter widget back to right side

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#67685]
Issue Type: <b>Bug</b>

Testing #66902

**repo**
1. In explorer
1. Start filtering to type
1. Drag the filter widget to the left side.
1. Now try dragging it back to the right side

**Bug**
Widget is now stuck on left side. I can't drag it back to the right side 

VS Code version: Code - Insiders 1.31.0-insider (7f136b44cff0cd3486ac88b43598b8c72b025d16, 2019-01-31T06:13:53.077Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.08GB free)|
|Process Argv|-psn_0_22394202|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by isidorn** [comment]
Can not repro. Forwarding to @joaomoreno to try to repro

**Comment by joaomoreno** [comment]
I can repro weird behaviour when zoomed in... it also gets worse when sidebar is on the right. Could that be it @mjbvz?

**Comment by mjbvz** [comment]
I can only repo this reliably on a multi-monitor setup. I am using zoom level zero with the bar on the left side

**Comment by joaomoreno** [comment]
OK that was embarrassing!
