### ISSUE TITLE
Tip not showing in read-only

### ISSUE THREAD

**Issue by freakdran** [microsoft/vscode#67682]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:** OSX

**Steps or JS usage snippet reproducing the issue:**
1. Create a readonly editor with some preset code in it
2. Press "Delete Left/Right" (or "Delete/Backspace" on Windows where this also appears) in the editor
Expected: A message that the editor is read-only appears like when pressing any other key that would modify the content.
Actual: No message is shown.
Problem: When not having an actual message that an editor is read-only the user gets confused when tries to delete something and gets no message why nothing is happening.

**Comment by octref** [comment]
In the left side of diff view, pressing any character would show the popup but pressing delete doesn't.

**Comment by alexdima** [comment]
@octref I cannot reproduce. Perhaps you have bound Delete to another command? The pop-up shows for me when pressing Delete or Backspace
