### ISSUE TITLE
Webview reveal api has no method for just making visible.

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vscode#67691]
The webview reveal API is what we use to display a webview when a user adds new content to it. However the only way we can present it is to force it to move to a specific ViewColumn (either the same as the active editor, or a hardcoded value). 

We'd really love a way to just have it activate wherever it happens to be.

Maybe something like:

```
    /**
     * Makes the webviewpanel show up.
     * @return A Promise that can be waited on
     */
    show(): Promise<void>;

```

Here's an example of reveal not working the way a customer needs:
https://github.com/Microsoft/vscode-python/issues/4237

**Comment by mjbvz** [comment]
The `WebviewPanel.reveal` signature is:

```ts
reveal(viewColumn?: ViewColumn, preserveFocus?: boolean): void;
```

If you pass no arguments, the webview should show in its current column. Is this not what you see?

**Comment by rchiodo** [comment]
Nope. If I pass no arguments, it activates next to the window that currently has focus.

So if the webview was in view column 2, the active editor is view column 1 and I call 'reveal()' it activates the webview in view column 1. Additionally it steals the focus. Although since it covers the active editor, it kinda has to steal the focus.

What we'd like is to have reveal(undefined, true) just bring the webview to the front of the list of windows in whatever column it's already in.

**Comment by mjbvz** [comment]
As a workaround until this is fixed,  pass `webview.viewColumn` as the first argument
