### ISSUE TITLE
TS server "initializing" again

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67699]
I think this happens from time to time. I've had this window open for awhile, then I switch files, and this pops up again and if I trigger the suggest widget it says "Loading".

![image](https://user-images.githubusercontent.com/323878/52098279-37e1d000-2583-11e9-8a12-2c9f9d3f83d8.png)

Is there a known issue for this?

**Comment by mjbvz** [comment]
Yes, we show this if we are loading a new project (such as switching between somewhere in `extensions` and `src` in the vscode code base)

**Comment by roblourens** [comment]
Do you unload the previous project when loading a new one?

**Comment by mjbvz** [comment]
Yes, we unload projects if there are no files open from them
