### ISSUE TITLE
Windows key in default keybindings on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#67695]
I don't think we shouldn't be doing this, it's reserved for OS-level actions unlike cmd on mac.

```
{ "key": "ctrl+win+w",            "command": "workbench.action.toggleTabsVisibility" }
{ "key": "win+l",                 "command": "workbench.debug.panel.action.clearReplAction",
                                     "when": "inDebugRepl" }
```

editor.action.autoFix is also, tracked in https://github.com/Microsoft/vscode/issues/67411

**Comment by bpasero** [comment]
@alexandrudima thoughts on using the Windows key on Win?

**Comment by alexandrudima** [comment]
@bpasero I think it's just asking for trouble. No application I've ever used on Windows tries to bind with that modifier, and even if we find a free one, new Windows versions sometimes bind new ones to the `Win+` key combination... Moreover, if you press `Win+` and change your mind after a split second, you get the start menu popping up, which is kind of horrible, imagine if that would happen when pressing `Ctrl+`...

**Comment by bpasero** [comment]
Removed one: https://github.com/Microsoft/vscode/commit/1ad028dfa956522dbd4ddabf5551092ca40fac19

**Comment by isidorn** [comment]
Removing it. Also it now overlaps with repl filtering
Sorry @octref you can still customise it

**Comment by Tyriar** [comment]
@isidorn @octref you could only enable it just for Mac, there are a bunch of terminal commands that only work on mac.
