### ISSUE TITLE
Explorer - confusing styles for focused row vs selected open file row

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67697]
- Open a file with cmd+p
- In the explorer, the file is focused but not selected, so the row has `list.inactiveFocusBackground`

looks like this:
![image](https://user-images.githubusercontent.com/323878/52097574-70cc7580-2580-11e9-91cc-b530780cea0e.png)

---

- Click a file in the explorer
- Click in the open file to set focus
- In the explorer, the file is selected and focused and inactive, so it has `list.inactiveSelectionBackground`, which Monokai defines as a nicer lookin color than `list.inactiveFocusBackground`

Looks like this:
![image](https://user-images.githubusercontent.com/323878/52097602-8b9eea00-2580-11e9-9647-ac5fb50ff29e.png)

This difference is new in 1.31, it seems that in 1.30 the row got selected when using cmd+p. I think we should do the same in 1.31.

**Comment by isidorn** [comment]
We made this change on purpose, to only focus and not select when the active file changes.
I understand it is a change from stable, but I believe it is for better. Since these actions should not destruct the user set selection.
Leaving this open to see if more users complain.

@bpasero If this needs to be changed while I am on vacation also select the file stat here
https://github.com/Microsoft/vscode/blob/b6bef453a01e4c2b1aa44abacfc39eed117fa4ac/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L509
And make sure that the https://github.com/Microsoft/vscode/blob/b6bef453a01e4c2b1aa44abacfc39eed117fa4ac/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L303 is ignored if it gets fired

fyi @joaomoreno

**Comment by joaomoreno** [comment]
I can see good arguments from both sides. I'm not sure you shouldn't ruin the user's selection or the user's focus...

**Comment by karlhorky** [comment]
I found this issue after a ton of searching (I searched for "highlight" with variations of the terms "side bar", "sidebar", "tree", "workbench", "workbench list", without any success).

There is definitely a source of confusion here, although I would say that for me the confusion stems from the fact that there are two highlighted items in the explorer side bar.

From a quick glance I can no longer tell in the side bar which `resolvers.js` is open (the shade difference is too subtle):

<img width="656" alt="screen shot 2019-02-14 at 12 02 40" src="https://user-images.githubusercontent.com/1935696/52782909-80ec5680-3050-11e9-90eb-a17e41d4a4bf.png">

---

I am not sure I understand the description of this issue completely, but I think that the problem I'm describing here is different than the one described here.

For this reason I've opened a new issue for this with lots of keywords to try to make it possible for other users to find it: Microsoft/vscode#68697

**Comment by usernamehw** [comment]
It would be nice to differ `selection` vs `focused` by some other means than background. Border, for instance:

![screenshot 67](https://user-images.githubusercontent.com/9638156/52786235-6a9fc400-306b-11e9-86e9-7c3e69fbf82f.png)

Or ... some other way. There's too many backgrounds and each theme chooses how to style them. 

One theme maker decides that `focused` element bright and `selection` - dim. Others - vice versa. Some people choose to make them almost identical that you can't even see the difference unless you zoom it in.

**Comment by karlhorky** [comment]
Definitely, I would support making the style even more distinct, as mentioned in #68697 (I proposed an arrow over there, if something like that would be a possibility).

**Comment by isidorn** [comment]
I have brought back the old behavior. Try it out in insders and let me know if it works nice for your now.

**Comment by karlhorky** [comment]
Thanks @isidorn!

Could you post a screenshot with the two styles (focused and current open file) here for reference?

**Comment by karlhorky** [comment]
I just updated to the latest Insiders and it appears to be the same @isidorn (or at least, not noticeably different):

<img width="695" alt="screen shot 2019-02-25 at 14 11 05" src="https://user-images.githubusercontent.com/1935696/53339682-4bc0ed80-3907-11e9-9d6c-f564ea4ade03.png">

Here's the previous screenshot for comparison:

<img width="656" alt="screen shot 2019-02-14 at 12 02 40" src="https://user-images.githubusercontent.com/1935696/52782909-80ec5680-3050-11e9-90eb-a17e41d4a4bf.png">

**Comment by isidorn** [comment]
Yeah the styles are still the same. The difference is that when items get auto revelead they both get selected and focused and it is harder to end up in a situation like this.

As for the exact styling if you are passionate about that please file an issue and ping @misolori so we potentially change colors.

**Comment by karlhorky** [comment]
Ok, I have requested that #68697 be reopened.
