### ISSUE TITLE
suggestion menu should not automatically select the first suggestion

### ISSUE THREAD

**Issue by alexch** [microsoft/vscode#67698]
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 3, 3|
|Memory (System)|4.00GB (0.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>
<details>
<summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
dotenv|mik|1.0.1
vsliveshare|ms-|0.3.1151
</details>

Steps to Reproduce:

1. open a JS file
2. type `cy.get(` at a rate sufficient for the suggestion menu to appear
3. notice that `crypto.getRandomValues(` appears instead

Does this issue occur when all extensions are disabled?: Yes

---

In JavaScript, when I type <kbd>c</kbd><kbd>y</kbd><kbd>.</kbd><kbd>g</kbd><kbd>e</kbd><kbd>t</kbd><kbd>(</kbd> and then look at the screen I should see `cy.get(`. Instead I (sometimes!) see `crypto.getRandomValues(` instead.

This is an #a11y issue; the suggestion menu should not select or fill anything until/unless I press <kbd>↓</kbd> while it's up. Any setting that *takes control away from the user* and types extra characters that they did not intend is a bad default setting, and the fact that this behavior is timing-dependent is even more maddening.

I note that similar bugs have been reported before and not fixed. Please reconsider. I teach programming classes and in every class so far, the majority of students find this behavior astonishing and frustrating; power users who prefer it should be competent enough to change a setting to their preference, but (I repeat) the *default behavior* of a text editor should be to faithfully enter the keys that were typed.

A common answer to this problem is to disable the `acceptSuggestionOnCommitCharacter` and/or `acceptSuggestionOnEnter` settings, but this bug is really about the default values of those settings being wrong for most users.

Also, the `editor.acceptSuggestionOnCommitCharacter` setting sounds like it's intended to type the **selected** suggestion and a dot when I press <kbd>↓</kbd><kbd>.</kbd>, which is actually desirable behavior; the advice to disable `editor.acceptSuggestionOnCommitCharacter` is more of a workaround than a solution since it disables .-to-accept in all cases, not just this overly-aggressive autocomplete scenario.

Is this issue sufficient to track both the fact that this setting is wrong by default, and that you might need a new setting e.g. "automaticallySelectFirstSuggestion" (which should also be false by default)?

Related issues:
* #41641
* #66868
* #52444
* https://twitter.com/joshwcomeau/status/1035947291813720064
* https://stackoverflow.com/questions/51199397/vscode-editor-accepting-suggestions-on-typing-parenthesis
* https://www.reddit.com/r/vscode/comments/7acy1y/disable_period_autocompleting_intellisense/

**Comment by jrieken** [comment]
> the suggestion menu should not select or fill anything until/unless I press ↓ while it's up.

I disagree with that. Selecting the best match is good and forcing people to down arrow slows down everything.

**Comment by alexch** [comment]
@jrieken  You are free to disagree, but please respect my experience and observations. The current behavior is observably, empirically confusing and flow-breaking for a majority of my students, as well as many bug-reporters and SO-question-askers. If you want to speed things back up (and risk the insertion of bogus code which you might then need to break your train of thought to correct), then you should be free to toggle the aggressive autoselection back on.

By default, a suggestion should be just that: a suggestion, not a decision.

**Comment by mjbvz** [comment]
It sounds like the root problem is that commit characters are sometimes unreliable for js. Typing the same sequence of characters should theoretically always result in the same text being inserted. Disabling commit characters makes the behavior more repeatable.

When typing `cy.`, if you type `.` before suggestions are shown, we do only insert `cy.` instead of `crypto.`. Not sure if there's anything we can do about this since we don't want suggestions to block typing

**Comment by alexch** [comment]
> Not sure if there's anything we can do about this since we don't want
suggestions to block typing

I was with you up to this point. Suggestions dont block typing; instantly
selecting the first suggestion does -- or at least it sets it up so the
next "commit character" inserts characters that the typist does not intend.

> It sounds like the root problem is that commit characters are sometimes
unreliable for js.

I think the commit characters are probably reliable once the suggestion
popup appears, but the timing of that popup is variable, which makes typing
unreliable.
-- 
Alex Chaffee - alexch@gmail.com
http://burlingtoncodeacademy.com
http://alexchaffee.com
http://codelikethis.com
http://twitter.com/alexch
