### ISSUE TITLE
De-indenting multiple lines should remove a consistent number of spaces

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#677]
Windows 10, VSCode 0.10.0/0.10.2 (`"editor.insertSpaces": true`)

It seems like vscode is trying to be clever by only de-indenting the comment portion of this block 1 space while de-indenting the rest 2 spaces, but this is not what I expect when using `shift+tab` on multiple lines of code.

![weird-deindent](https://cloud.githubusercontent.com/assets/2193314/11411910/d2c755c4-938a-11e5-9fd2-15957c1aba08.gif)

It also happens when a leading `/**"` with 2 spaces is included as the first line.

**Comment by alexandrudima** [comment]
This now works for me as expected after 53186e97a62d059d8bc6bcffd88896ea7a531571 with `"editor.tabSize": 2` and `"editor.insertSpaces": true` :

![1cuza5b1fr](https://cloud.githubusercontent.com/assets/5047891/11740327/038f83c0-9ff2-11e5-84ff-25c9c4740921.gif)
