### ISSUE TITLE
`unixLike` is probably better, but inconsistent?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6770]
Testing #6654 

I am not an expert in unix distributions, and most likely `unixLike` is a better term than `linux`/`osx`, but then we should align and use `unixLike` everywhere.

For example, in `tasks.json` (@dbaeumer) and in `package.json` keybindings contributions we use `linux` and `osx` separately. I am not sure about the `launch.json` (@weinand knows better)

**Comment by dbaeumer** [comment]
For tasks I think it is actually useful yo distinguish between Linux and OS X since it refers to programs to be executed which can be different. However thinking about it tasks should even distinguish between different Linux distributions since they can have different disk layouts.

**Comment by weinand** [comment]
@alexandrudima where are you seeing the 'unixLike' ?

**Comment by alexandrudima** [comment]
`integratedTerminal.shell.unixLike` configuration option. My point is that in the rest of VSCode we have two explicit settings/options for osx / linux. I wasn't sure what you do for the `launch.json` (i.e. can there be platform specific settings and how does it look like)

**Comment by weinand** [comment]
Yes, I agree keeping Linux and OS X separate is preferred. For debug adapters we use these names:

![2016-05-24 14-40-43](https://cloud.githubusercontent.com/assets/1898161/15504110/a6f6a8c0-21bd-11e6-9315-1fa384d5475d.png)

**Comment by joaomoreno** [comment]
`unixLike` felt strange to me, when I first saw it. I would keep it separate too.

**Comment by Tyriar** [comment]
:+1:
