### ISSUE TITLE
TSDoc @example indentation not working

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#67703]
- VSCode Version: 1.30.2
- OS Version: macOS High Sierra

Steps to Reproduce:

I've created a TSDoc comment on one of my functions like this

```ts
/**
 * Test an object to match the `shape` partially.
 *
 * @param shape Shape to test the object against.
 *
 * @example
 *
 * ow({unicorn: '🦄'}, ow.object.partialShape({
 * 	rainbow: ow.string,
 * 	stars: {
 * 		value: ow.number
 * 	}
 * }));
 */
```

The indentation of the example is not taken into account. I tried using tabs, spaces, basically everything, but the output looks like this.

![image](https://user-images.githubusercontent.com/1913805/52107440-a57b1400-25f6-11e9-8eb4-4a1891f467f2.png)

I've tried wrapping it in backticks, and then the indentation works, but the `*` of my comments are also shown.

![image](https://user-images.githubusercontent.com/1913805/52107421-95fbcb00-25f6-11e9-91c2-0f5f4351f3b8.png)

Do I miss something?

@mjbvz I think you already helped me out with something regarding TSDoc, so tagging you just in case :).

**Comment by mjbvz** [comment]
Thanks. I believe that https://github.com/Microsoft/TypeScript/issues/15749 is already tracking this upstream. We've marked it as a priority for the TS team to investigate
