### ISSUE TITLE
Insider split integrated terminal failing with "Cannot read property '_data' of undefined"

### ISSUE THREAD

**Issue by adamelliottsweeting** [Microsoft/vscode#67704]
Issue Type: <b>Bug</b>

I am using the latest Insider and the integrated terminal.

When I split the terminal, sometimes it's failing with the error:

> Cannot read property '_data' of undefined

In my case, I had 1 terminal split into two panes, and the right pane was active. After I split:

- The new right terminal is blank
- The error notification pops up
- The terminal I split from (now middle) is unusable
- The left terminal continues to function
- I cannot close my terminals `ctrl+d`
- I cannot close my terminals with the trash icon in the terminal pane's top right. Also, selecting this results in VS Code crashing with "The window is no longer responding"

VS Code version: Code - Insiders 1.31.0-insider (7f136b44cff0cd3486ac88b43598b8c72b025d16, 2019-01-31T06:13:53.077Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 8|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-jira|Kni|0.6.0
project-manager|ale|10.3.1
cucumberautocomplete|ale|2.13.0
jest-snippets|and|1.6.1
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.8
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
gitlab-workflow|fat|1.9.1
flow-for-vscode|flo|1.0.1
wordcounter|kir|1.4.0
javascript-test-runner|leg|1.0.0
vscode-typescript-tslint-plugin|ms-|0.4.1
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.5.1
vscode-versionlens|pfl|0.22.0
vscode-icons|rob|8.0.0
vscode-javascript-booster|sbu|0.10.2
node-modules-viewer|see|0.0.3
code-settings-sync|Sha|3.2.4
vscode-fileutils|sle|2.13.5
typescript-workspace-langserv-extension|spi|1.0.0
code-spell-checker|str|1.6.10
vscodeintellicode|Vis|1.1.2
vim|vsc|1.0.5
vscode-mermaid-preview|vst|0.10.2
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.0.1

(3 theme extensions excluded)

</details>

**Comment by adamelliottsweeting** [comment]
After updating to the latest build just released, I'm unable to reproduce again.

However, while testing splitting and closing panes, I did end up with one of my panes being completely empty.

Looking at the scrollbar for that pane, I can run commands like `ls -la` which results in the scrollbar shortening (implying more output) but the content is still not visible.

![screenshot](https://user-images.githubusercontent.com/8907331/52109072-ebac9380-2647-11e9-9eff-dd35f424def9.png)

**Comment by Tyriar** [comment]
This is the _data issue https://github.com/Microsoft/vscode/issues/67439

@adamelliottsweeting if you have a good repro for that other problem you ran into can you respond here? Also if it happens again could you check if there are any exceptions in the devtools console? (Help > Toggle Developer Tools)
