### ISSUE TITLE
C++ Code formatter: Inconsistent behavior with curly braces

### ISSUE THREAD

**Issue by EmbersArc** [Microsoft/vscode#67709]
The default c/c++ formatter turns an initializer list from this

{
    {1, 30},
    {21, 20}
};

into this

{
    {1, 30},
    {21, 20}};

Putting the last curly brace not below the first is inconvenient for two reasons:

- It doesn't look good and is harder to read.
- It is inconsistent with the behavior in functions and loops, where matching braces are placed in the same column.
- Some codechecks like Vera insist on the braces being in the same column, effectively making the otherwise great formatter unusable.

---

- VSCode Version: 1.30.2
- OS Version: Linux x64 4.4.0-141-generic

Steps to Reproduce:

1. Create a .cpp file with an initializer list as in the example above
2. Format the file with the default VSCode C++ formatter.

Does this issue occur when all extensions are disabled?: No, C/Cpp extension specific

**Comment by dbaeumer** [comment]
Please report the issue here: https://github.com/Microsoft/vscode-cpptools
