### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by zklwzh** [Microsoft/vscode#67701]
- VSCode Version: 1.30.2
- OS Version:Windows_NT x64 10.0.10240

Steps to Reproduce:

1. down quartznet-3.0.7 source code from https://codeload.github.com/quartznet/quartznet/zip/v3.0.7
2.unzip and open 
3.install Docker Extension
4 .See the OUTPUT view
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �İ�...
  ���ڰ�װ Microsoft.Build.Tasks.Git 1.0.0-beta-63127-02��
  ���ڰ�װ Microsoft.SourceLink.Common 1.0.0-beta-63127-02��
  ���ڰ�װ Microsoft.SourceLink.GitHub 1.0.0-beta-63127-02��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\obj\Quartz.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\obj\Quartz.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 18.31 sec ����ɡ�
Done: 0.
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\Quartz.Plugins.csproj �İ�...
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Examples\Quartz.Examples.csproj �İ�...
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj �İ�...
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �İ�...
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\obj\Quartz.Jobs.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\obj\Quartz.Serialization.Json.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\obj\Quartz.Plugins.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\obj\Quartz.Jobs.csproj.nuget.g.targets��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\obj\Quartz.Plugins.csproj.nuget.g.targets��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\obj\Quartz.Serialization.Json.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\Quartz.Plugins.csproj �Ļ�ԭ�� 1.85 sec ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 1.85 sec ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj �Ļ�ԭ�� 1.85 sec ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 37.9 ms ����ɡ�
  ���ڰ�װ Microsoft.NETCore.DotNetAppHost 2.0.0��
  ���ڰ�װ Microsoft.NETCore.DotNetHostResolver 2.0.0��
  ���ڰ�װ System.Threading.Overlapped 4.0.1��
  ���ڰ�װ Microsoft.NETCore.DotNetHostPolicy 2.0.0��
  ���ڰ�װ Microsoft.NETCore.App 2.0.0��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Examples\obj\Quartz.Examples.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Examples\obj\Quartz.Examples.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Examples\Quartz.Examples.csproj �Ļ�ԭ�� 12.89 sec ����ɡ�
Done: 0.
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 77.83 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 77.83 ms ����ɡ�
Done: 0.
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 96.82 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 96.79 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\Quartz.Plugins.csproj �Ļ�ԭ�� 96.79 ms ����ɡ�
Done: 0.
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins.TimeZoneConverter\Quartz.Plugins.TimeZoneConverter.csproj �İ�...
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 44.31 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 41.54 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\Quartz.Plugins.csproj �Ļ�ԭ�� 49.66 ms ����ɡ�
  ���ڰ�װ TimeZoneConverter.StrongName 2.3.0��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins.TimeZoneConverter\obj\Quartz.Plugins.TimeZoneConverter.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins.TimeZoneConverter\obj\Quartz.Plugins.TimeZoneConverter.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins.TimeZoneConverter\Quartz.Plugins.TimeZoneConverter.csproj �Ļ�ԭ�� 2.4 sec ����ɡ�
Done: 0.
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 105.59 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj �Ļ�ԭ�� 105.59 ms ����ɡ�
Done: 0.
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Server\Quartz.Server.csproj �İ�...
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj �Ļ�ԭ�� 138.96 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 138.96 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\Quartz.Plugins.csproj �Ļ�ԭ�� 138.96 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 14.25 ms ����ɡ�
  ���ڰ�װ System.Reflection.DispatchProxy 4.4.0��
  ���ڰ�װ System.Net.Http.WinHttpHandler 4.4.0��
  ���ڰ�װ System.Private.ServiceModel 4.4.1��
  ���ڰ�װ System.ServiceModel.Http 4.4.1��
  ���ڰ�װ System.ServiceModel.Primitives 4.4.1��
  ���ڰ�װ System.ServiceModel.NetTcp 4.4.1��
  ���ڰ�װ System.ServiceModel.Security 4.4.1��
  ���ڰ�װ System.ServiceModel.Duplex 4.4.1��
  ���ڰ�װ System.ServiceProcess.ServiceController 4.5.0��
  ���ڰ�װ System.Threading.AccessControl 4.5.0��
  ���ڰ�װ System.Runtime.Caching 4.5.0��
  ���ڰ�װ System.ServiceModel.Syndication 4.5.0��
  ���ڰ�װ System.IO.Packaging 4.5.0��
  ���ڰ�װ System.Data.SqlClient 4.5.0��
  ���ڰ�װ System.IO.Ports 4.5.0��
  ���ڰ�װ System.IO.Pipes.AccessControl 4.5.0��
  ���ڰ�װ Topshelf 4.1.0��
  ���ڰ�װ TopShelf.ServiceInstaller 4.1.0��
  ���ڰ�װ Microsoft.Windows.Compatibility 2.0.1��
  ���ڰ�װ Microsoft.Win32.Registry.AccessControl 4.5.0��
  ���ڰ�װ System.ComponentModel.Composition 4.5.0��
  ���ڰ�װ System.Diagnostics.EventLog 4.5.0��
  ���ڰ�װ System.Data.DataSetExtensions 4.5.0��
  ���ڰ�װ System.Data.Odbc 4.5.0��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Server\obj\Quartz.Server.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Server\obj\Quartz.Server.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Server\Quartz.Server.csproj �Ļ�ԭ�� 16.33 sec ����ɡ�
Done: 0.
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Integration\Quartz.Tests.Integration.csproj �İ�...
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 44.76 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 13.46 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj �Ļ�ԭ�� 13.67 ms ����ɡ�
  ���ڰ�װ SQLitePCLRaw.lib.e_sqlite3.linux 1.1.7��
  ���ڰ�װ SQLitePCLRaw.lib.e_sqlite3.osx 1.1.7��
  ���ڰ�װ SQLitePCLRaw.lib.e_sqlite3.v110_xp 1.1.7��
  ���ڰ�װ SQLitePCLRaw.provider.e_sqlite3.netstandard11 1.1.7��
  ���ڰ�װ MySql.Data 6.10.6��
  ���ڰ�װ SQLitePCLRaw.core 1.1.7��
  ���ڰ�װ SQLitePCLRaw.bundle_green 1.1.7��
  ���ڰ�װ System.Text.Encoding.CodePages 4.0.1��
  ���ڰ�װ System.Data.SQLite.Core 1.0.105.2��
  ���ڰ�װ FakeItEasy 4.6.0��
  ���ڰ�װ Npgsql 3.2.5��
  ���ڰ�װ FirebirdSql.Data.FirebirdClient 5.11.0��
  ���ڰ�װ Oracle.ManagedDataAccess 12.2.1100��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Integration\obj\Quartz.Tests.Integration.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Integration\obj\Quartz.Tests.Integration.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Integration\Quartz.Tests.Integration.csproj �Ļ�ԭ�� 26.91 sec ����ɡ�
Done: 0.
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins\Quartz.Plugins.csproj �Ļ�ԭ�� 83.62 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Plugins.TimeZoneConverter\Quartz.Plugins.TimeZoneConverter.csproj �Ļ�ԭ�� 83.62 ms ����ɡ�
  ���ڻ�ԭ f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj �İ�...
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Jobs\Quartz.Jobs.csproj �Ļ�ԭ�� 14.42 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj �Ļ�ԭ�� 12.57 ms ����ɡ�
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz\Quartz.csproj �Ļ�ԭ�� 11.12 ms ����ɡ�
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Unit\obj\Quartz.Tests.Unit.csproj.nuget.g.props��
  �������� MSBuild �ļ� f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Unit\obj\Quartz.Tests.Unit.csproj.nuget.g.targets��
  f:\myself\quartznet.git\quartznet-3.0.7\src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj �Ļ�ԭ�� 4.09 sec ����ɡ�
Done: 0.

Does this issue occur when all extensions are disabled?: No

**Comment by dbaeumer** [comment]
I am closing the issue. Please ping if you have provided additional information.
