### ISSUE TITLE
Grid: toggling editor area should have some kind of indication

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67707]
I feel like there should be an indication when the editor area is toggled to be hidden. Since we are building everything around the editor it seems weird to end up in a state where the editor is not visible at all. 

//cc @misolori

**Comment by bpasero** [comment]
I think the easiest would be a new entry to the menu to toggle visibility:

![image](https://user-images.githubusercontent.com/900690/62703408-6edce680-b9e9-11e9-9265-906b8de7d145.png)

Everything else works already pretty nicely:
* editor comes back when you open anything
* editor can be dragged back with the mouse

**Comment by bpasero** [comment]
Actually: if we have a way to hide the editor area I think we should make sure that the panel becomes visible to fill the remaining space, even if the panel was not visible before. Otherwise you would end up with a weird sidebar that fills the entire space.

**Comment by sbatten** [comment]
@bpasero this is already in place? Currently, the if the editor or panel is hidden, the other is automatically shown regardless of current visibility.

**Comment by sbatten** [comment]
I was considering removing the editor visibility command altogether and just having the the chevron on the panel toggle its visibility. In master today (not today's insiders), the chevron will now not have a gap remaining for the editor. What do you think?

**Comment by bpasero** [comment]
@sbatten you mean the arrow icon in the panel would hide the editor? keep in mind that there is also a command to "Toggle Maximized Panel". Would that hide the editor area? I think that could work but might confuse users that are used to how it works today.

@Tyriar didn't you recently file an issue to do this?

**Comment by sbatten** [comment]
Yes to both @bpasero ... Effectively toggle maximized panel and toggle editor become the same command

**Comment by bpasero** [comment]
@sbatten I kind of like that, why don't we run that through a UX meeting. 

cc @misolori

**Comment by bpasero** [comment]
The only downside I can think of that hiding the editor means you loose all opened editor titles and you might want to refer to a specific file from the terminal e.g. So that could be annoying and maybe warrants a setting.

**Comment by Tyriar** [comment]
I think toggle maximize panel should restore the panel to its previous position when you press cmd+1 or click a link to a file in the terminal/explorer.
