### ISSUE TITLE
Tree viewState should contain scrollTop

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67719]
* disable automatic reveal of files (`"explorer.autoReveal": false,`)
* open `src/vs/base/browser/ui/breadcrumbs/collpased-dark.svg`
* reveal the file manually and notice that it is positioned in the center
* reload window
* :bug: the file is now in the lower third

![feb-01-2019 10-55-20](https://user-images.githubusercontent.com/1794099/52115848-ea5f7480-260f-11e9-8caf-0abfa2ec83c3.gif)

**Comment by isidorn** [comment]
I would expect that tree preserves scroll top as part of the saved view state. Forwaring to @joaomoreno

**Comment by isidorn** [comment]
Not a regression from stable, so not for endgame.

**Comment by joaomoreno** [comment]
@isidorn I've implemented this, but with auto reveal enabled it is basically worthless in the explorer.

**Comment by isidorn** [comment]
Lot of people have auto reveal disabled. So thanks

**Comment by joaomoreno** [comment]
Verification: please code review.
