### ISSUE TITLE
code --unistall-extension: incorrect extension hint.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6771]
- VSCode Version: code-alpha
- OS Version: Linux

Steps to Reproduce:

1. code --uninstall-extension xxxx

Observe: you get a message:
```
Extension 'xxxx' is not installed.
Make sure you use the full extension id, eg: ms-vscode.csharp
```

The last line would be better:
```
Make sure you use the full extension id, including the publisher, e.g.: ms.vscode-csharp
```

Note that the sample should be ms.vscode-csharp and not ms-vscode-csharp

**Comment by joaomoreno** [comment]
Concerning your last comment, the id is indeed [`ms-vscode.csharp`, isn't it](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)?

**Comment by dbaeumer** [comment]
You are correct. My mistake. ms-vscode is the publisher and csharp the extension name. Got confused since our extensions all begin with vscode- in the name which actually is somehow bogus.
