### ISSUE TITLE
Cannot copy-dnd file in/to root folder

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67716]
Issue Type: <b>Bug</b>

With a single root folder:
- Drag file from Explorer (from root folder or subfolder).
- Hold `Alt` for copying.
- Bug: Cannot target root folder, other folder work.

Note that moving a file from a subfolder to the root folder using DnD works. Maybe 'Copy' is just missing from the allowed operations on the root folder.

This works in 1.30.

VS Code version: Code - Insiders 1.31.0-insider (371c853fa9c6def40b6fa51071d0ba03c9f62ebb, 2019-02-01T06:13:49.192Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscodeintellicode|Vis|1.1.2

</details>

**Comment by isidorn** [comment]
@chrmarti good catch!
Fixed by Joao

**Comment by bpasero** [comment]
This broke again: https://github.com/Microsoft/vscode/issues/68095
