### ISSUE TITLE
VS Code not display on Kali when connected using XRDP

### ISSUE THREAD

**Issue by mxdh** [Microsoft/vscode#67715]
- VSCode Version:1.30.2
- OS Version:WSL Kali

Steps to Reproduce:

Sorry,my English is not good.
Like this:https://github.com/Microsoft/vscode/issues/3451
I can see "code" in taskmgr,but it doesn't display.
Changing libxcb.so.1 can't solve the problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
I will mark this as a dup of #3451 since this seems to have a general problem on XRDP.
