### ISSUE TITLE
Remember last opened files

### ISSUE THREAD

**Issue by Somebi** [Microsoft/vscode#67728]
Issue Type: <b>Feature Request</b>

It keeps opening files which i left opened around week ago, but doesn't remember recently opened files...

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

**Comment by Somebi** [comment]
Using ctrl + p

**Comment by Somebi** [comment]
Every morning i'm opening my editor and see files, which i have opened more than a week ago. Every time same files. Not the files i was working yesterday. I'm not closing editor, i'm just restarting system right away. So there must be a problem with that. 

Maybe saving listener/handler is attached to wrong signal?

Maybe that feature should be triggered each time file is opened or closed?

**Comment by bpasero** [comment]
> I'm not closing editor, i'm just restarting system right away. So there must be a problem with that.

Yeah, that wont work. Duplicate of https://github.com/Microsoft/vscode/issues/12058

**Comment by Somebi** [comment]
Ok ty, waiting for the fix then.
