### ISSUE TITLE
Refreshing the root also triggers getChildren on folders which have been resolved yet are collapsed

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67722]

**Comment by alexr00** [comment]
I tried having a tree view in an extension with a refresh button. getChildren was only called once for the root.

**Comment by joaomoreno** [comment]
Extension trees use the old tree, so this doesn't apply to them.

Best way to verify is to read the associated unit test. The `getChildrenCalls` array tracks all calls to `getChildren`. The test asserts that `getChildren` should never be called for collapsed tree nodes, even when refresh is recursive.
