### ISSUE TITLE
The default html template is not html 

### ISSUE THREAD

**Issue by alexandrLamdan1995** [Microsoft/vscode#67724]
Hi, I noticed that there is a bug in the program, which is not fixed for a couple of updates, I tried to understand why this bug is not fixed and decided to get into the settings of the program, but the settings as such is not present.

At your discretion

The problem is that the default HTML, is Django template even if I use ONLY HTML.
![screenshot_20190201_124110](https://user-images.githubusercontent.com/38505847/52118347-bb9cca80-261e-11e9-800c-ac84cebf72a0.png)

I using the KDE Neon Linux which is the 18.04 version of Ubuntu. I don't know if that bug is worked on another system, but why you don't just find it?

**Comment by Hrafven** [comment]
This is due to the Django extension. Try disabling it

**Comment by alexandrLamdan1995** [comment]
> This is due to the Django extension. Try disabling it

Yeah, thanks. But I think the extension don't need to overwrite the default setting
