### ISSUE TITLE
Remember last text zoom

### ISSUE THREAD

**Issue by Somebi** [Microsoft/vscode#67727]
Issue Type: <b>Feature Request</b>

Every day i start vscode and zoom is always reseted to default value. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

**Comment by Somebi** [comment]
Yeah, but add an option to bind on scroll up and scroll down. ctrl + scroll up or ctrl + scroll down
This how it works in sublime editor, you can give it a try yourself.

**Comment by sandy081** [comment]
@Somebi How do you set the zoom value?

**Comment by Somebi** [comment]
Previously with ctrl + num plus, now with a scroll. In any case, settings are not saved after system restart.

**Comment by Somebi** [comment]
And after installing some extension and pressing "reload" inside installed extension window.

**Comment by sandy081** [comment]
> Previously with ctrl + num plus, now with a scroll.

Can you please check in the settings immediately after doing above? To make sure if it was written into settings or not.
