### ISSUE TITLE
[mac] cannot select special characters with arrow keys

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#67739]
* goal is to type `föo`
* type `f`
* long press `o`, the mac shows the selector
* use arrow keys to select `ö`
* :bug: a newline and a character is inserted

![feb-01-2019 14-14-06](https://user-images.githubusercontent.com/1794099/52125106-a8dcc280-262b-11e9-82b1-fa3c6840e7e1.gif)

**Comment by alexandrudima** [comment]
Interestingly, this doesn't reproduce the same bug for me (I get a double `o` situation):

![kapture 2019-02-01 at 14 35 57](https://user-images.githubusercontent.com/5047891/52126132-be072080-262e-11e9-97c9-897a0ba92f8e.gif)

**Comment by rebornix** [comment]
I didn't get the same bug @jrieken ran into but @alexandrudima 's one is valid.
