### ISSUE TITLE
New Explorer: ERR Data tree node not found

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67733]
Steps to Reproduce:

1. Multi Root Workspace (exmaple vscode and vscode-docs)
2. Open a file from a multi root workspace  (example debug-service.ts)
3. New Untitled File
3. Save the untitled file as a sibling to the opened file from step 2

=> 🐛  

```
 ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.AsyncDataTree.getDataNode (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:609:23)
    at WorkbenchAsyncDataTree.AsyncDataTree.reveal (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:581:35)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/electron-browser/views/explorerView.js:493:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by isidorn** [comment]
Can not repro.
@joaomoreno can you?
@bpasero you save the utntile file, not the workspace correct? Do you save the file inside one of those workspaces? No combination reproed the issue for me?

**Comment by bpasero** [comment]
@isidorn seems to only reproduce when you click on a file first that is inside a folder

**Comment by isidorn** [comment]
@bpasero great catch, you are great!

**Comment by mjbvz** [comment]
Actually this may be a different crash; hard to tell with the insiders stack trace. I see this when just opening `debugService`. Here are my repo steps:

1. Start with opening  `vscode-docs` as a  folder
1. Add `vscode` to the workspace
1. Open `debugService`

**Comment by joaomoreno** [comment]
Yeah I can repro the stack, but not the ten second hang... Can you reliably repro the hang?

**Comment by joaomoreno** [comment]
This was a pretty innocent error. No actual behavior breakage. Nevertheless I think we should still include it in the build, to prevent getting these stacks in telemetry.
