### ISSUE TITLE
Improve code block commenting

### ISSUE THREAD

**Issue by Somebi** [microsoft/vscode#67732]
Issue Type: <b>Feature Request</b>

Improve codes block commenting for .js files. It's easier to comment code block with // instead of /* */ . Commenting all involved lines, no matter how much code on these lines are selected, even if partially selected/highlighted.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

**Comment by Somebi** [comment]
Can you partially select multiple lines and use ctrl + /?
It's commenting exactly selected part with /**/ and not the whole involved lines with //.
See how commenting works in sublime editor. At least make that feature in settings, to be able to control this settings ourselves. Something like "block comment settings" and two options:
- comment exactly selected/highlighted multilines code with /* */
- comment all involved lines, no matter how much of them is selected/highlighted, with //

**Comment by Somebi** [comment]
Why have you closed this issue? It's not resolved...

**Comment by dbaeumer** [comment]
Reopening the issue (I now understand what the request is)

**Comment by Somebi** [comment]
Thanks
