### ISSUE TITLE
Renaming a file to its own name has a weird effect on the editor

### ISSUE THREAD

**Issue by alexrussell** [Microsoft/vscode#67734]
- VSCode Version: 1.31.0-insider (1.31.0-insider) - `371c853fa9c6def40b6fa51071d0ba03c9f62ebb`
- OS Version: macOS Mojave 10.14.2

Steps to Reproduce:

There are actually a few interesting scenarios here but they all revolve around attempting to rename a file in the explorer and then just hitting enter without having changed its name.

1. Open a file into an editor
2. Select it in the Explorer, press enter to rename (or use mouse), press enter to accept current name
3. File's open editor disappears

That happens whether it's a temporary/preview (i.e. filename in italics) editor or a permanent one.

But here's where it gets interesting...

1. Open a file into an editor
2. Open a new file into an editor
3. Select the active editor's file in explorer and do the rename-to-itself thing.
4. Editor disappears and the first file's editor shows, but is blank (actually, if I'm reading the colouring properly, the first editor's *tab* gets shown as active as the second one's tab was closed, but there's no actual editor open on the screen - in fact I have just confirmed this with devtools: the `editor-instance` div is empty at this point, rather than containing a `monaco-editor` as it should.).

Okay so so far same old same old. But try this:

1. Open a file into an editor
2. Open a new file into an editor
3. Edit that file so it's dirty and unsaved
4. Select the active editor's file in explorer and do the rename-to-itself thing
5. Editor disappears and the first file's editor shows - but with the contents of the dirty file that just closed
6. If you now click on the file that corresponds to that tab (i.e. the one from step 1, not step 2) the contents will be replaced with the actual file contents
7. Now if you open the file you left dirty, it'll open a new editor (good) but with the unsaved dirty contents, but the file will not appear dirty. The file on disk is the original unmodified version, but code shows the dirty one as it's not dirty.

And there's are various variants of this - try doing the rename trick on a non-active (but open) editor. The tab goes away. I haven't tried it like that but with a dirty editor, but I imagine the same would happen as above regarding the dirty contents persisting (though not the editor).

So what I imagine is happening is that during a standard rename the tab/editor is closed and reopened, but in the case of a self-rename, the logic that would normally do that somehow manages to close the tab and editor, but fails to reopen it (race condition whereby code thinks the file is already open so doesn't open it in the reopen stage of that process?). In the case of a dirty editor, the editor has a safeguard that prevents it from closing (as it has unsaved contents), despite the fact that the tab is removed, but the the tab/editor isn't reopened so the visible tab switches to the next editor down the stack and the actual editor that never got closed stays open. As for the dirty contents somehow persisting, I imagine this is something to do with the standard dirty-state-persisting-on-close feature. The odd part about that is that when the editor is reopened, the dirty contents persist, but not the *fact* that it's dirty (e.g. in tab indicator/closing editor).

Variations to consider:

- Is only editor versus is active editor with at least one other versus is open but not active editor
- Is dirty (modified but not saved to disk) versus is clean
- Multiple panes - I haven't fully delved into this, but I noticed it with a file that was open it its own pane, and when I clicked the file to "reopen" the editor, I think it appeared back in another pane with blank contents.

---

Does this issue occur when all extensions are disabled?: I haven't yet tried as I am working and don't want to disrupt my current open editors/windows. (I know I'll get marked down for this, but I figured it best to report without this confirmation and try to confirm later.)

**Comment by alexrussell** [comment]
☝️  may be related, but certainly not a dupe so far as I can tell, as this appears to be very much an actual bug.

**Comment by bpasero** [comment]
Good catch, I saw this earlier. There are two issues:
* the file service is not very smart when it comes to copy/move of same paths
* the editor part is not very smart when replacing editors (that explains why the editor shows up empty - that I would fix separately)

**Comment by isidorn** [comment]
@alexrussell great catch. You can verify in the next vscode insiders that this issue is fixed.
I tried it locally for me and it works fine now -> adding verified label.

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/67738

**Comment by alexrussell** [comment]
Confirmed fixed on latest insiders (`f125fdfa20b217dea34001eac9866322418226ce`). Nice fast turnaround!!

**Comment by isidorn** [comment]
Thanks for using insiders and for filling good issues.
