### ISSUE TITLE
Integrated Terminal: after exiting PowerShell, a new PowerShell process is lingering

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6773]
while testing https://github.com/Microsoft/vscode/issues/6654:

- VSCode Version: 1.1.0 alpha
- OS Version: Windows 10

Steps to Reproduce:

- launch integrated terminal
- open Task Manager and remember process id of PowerShell process
- in integrated terminal type 'exit'

Observe:
- integrated terminal becomes empty (and unusable)
- in Task Manager a new PowerShell process exists

**Comment by Tyriar** [comment]
This is intentional, closing in favor of #6683 and #6762
