### ISSUE TITLE
Erro na inicialização VSCode

### ISSUE THREAD

**Issue by Guilherme808** [microsoft/vscode#67737]
![37638087-1808c58c-2c31-11e8-8426-6cdaf9625de9](https://user-images.githubusercontent.com/33419490/52124146-6c9b6900-260f-11e9-8ffc-49de5bc9cfec.JPG)

HELPP..... error ao abrir VSCode direto da unity.
HELPP ..... Error When Opening VSCode Direct From Drive.

**Comment by Ronkiro** [comment]
Please include more info about your error.

I recommend following the guidelines:
[Click here - Contributing.md](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md)

It's very hard to find errors without any guide.
-----------------
[PT-BR translation of what i said above]
Por-favor inclua maiores informações sobre o seu problema.

Eu recomendo seguir o guia:
[Clique aqui - Contributing.md](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md)

É bem complicado encontrar erros sem ao menos uma guia.

**Comment by dbaeumer** [comment]
Closing since no additional information has been provided.
