### ISSUE TITLE
Associate custom data schemes with file suffixes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#67742]
To help custom data authors we should recommend particular file suffixes/extensions (e.g. `.html-data.json`) . When using these extensions they then will automatically get the schema association with the proper schema..

To support that. we add to `package.json` of `html-language-features`:
```
{
	"fileMatch": "*.html-data.json",
	"url": "https://raw.githubusercontent.com/Microsoft/vscode-html-languageservice/master/docs/customData.schema.json"
}
```

Note, it's what we do for color-themes already:
https://github.com/Microsoft/vscode/blob/555727f1c7c82d55503ff15021a83ade8ef858a0/extensions/extension-editing/package.json#L37

**Comment by aeschli** [comment]
Alternatively, add the schema association directly to the custom data file:
```json
{
    "$schema": "https://raw.githubusercontent.com/Microsoft/vscode-html-languageservice/master/docs/customData.schema.json",
    "version": 1,
    "tags": [
           {
            "name": "my-button",
            "description": "My button",
```

**Comment by octref** [comment]
Sure, let's do this when we move HTML/CSS data out of backlog.
