### ISSUE TITLE
Smoke Test fails: CSS - verifies that warning becomes an error once setting changed failed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#67746]
It failed for me under Windows 3 times out of three runs.

**Comment by dbaeumer** [comment]
Test manually with @aeschli and it works

**Comment by aeschli** [comment]
Problem is with `settingsEditor.addUserSetting`
`{}"css.lint.emptyRules": "error"`

Only seems to happen on Dirks machine, works for me on Linux and Windows

**Comment by aeschli** [comment]
Closing as not reproducible
