### ISSUE TITLE
Improve custom data schemas

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#67747]
html:
- add descriptions to all properties so we get nice hovers
- [version](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L12) can be `const: 1`. 
- [properties.name](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L34) should be required
-  can there be both values and valueSet?
- unnecessary  [attributes.anyOf](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L31), [globalAttributes.anyOf](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L73, ) and [valueSets.anyOf](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L97)
- [globalAttributes.required](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L72) and [itemSet.required](https://github.com/Microsoft/vscode-html-languageservice/blob/17ed5418f248d7cf0dcb6dbd5b65a55974dedde3/docs/customData.schema.json#L96) need to be next to the `properties`
- add `default` values and [defaultSnippets](https://github.com/Microsoft/vscode/blob/f125fdfa20b217dea34001eac9866322418226ce/src/vs/base/common/jsonSchema.ts#L55) for better code completion experience (as requested in #67609)

css:
- version can be `const: 1`. 
- simplify [`oneOf:[{enum`](https://github.com/Microsoft/vscode-css-languageservice/blob/ed177aac88351c2a0f84207c321cd2332c5be019/docs/customData.schema.json#L28) with `"enum": ["standard", "experimental",...]``
- add `pattern` and `patternErrorMessage` to verify `browsers`
- use `$ref` to have avoid multiple definitions for definitions for `browsers` and `status`

**Comment by octref** [comment]
`enum` doesn't show suggestion for me, that's why I changed to `oneOf`. Others make sense, I'll update them.

**Comment by aeschli** [comment]
enum shows suggestions, we use it everywhere, there must have been some other issue.

**Comment by octref** [comment]
Verifier:

- For setup, see https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md
- Verify `version: 2` show error
- Verify that you get completions for each array, such as `tags`, `globalAttributes`, `valueSets`, `tags.attributes` in HTML custom data JSON files
- Verify that you get completions for each array, such as `properties, `atDirectives` in CSS custom data JSON files

**Comment by octref** [comment]
> can there be both values and valueSet?

Yes. Attribute value completion gets values from both.
