### ISSUE TITLE
Can not read property then of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6775]
#6655

- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. open .html file
2. find all references -> notice exception

![screen shot 2016-05-24 at 12 18 28](https://cloud.githubusercontent.com/assets/1926584/15500606/b9b514c4-21a9-11e6-91f7-de607cd2f902.png)

**Comment by alexandrudima** [comment]
Dup of #6739
