### ISSUE TITLE
Smoke-test for localization fails on Linux

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67751]
Issue Type: <b>Bug</b>

`Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.`

The window was all in German.

VS Code version: Code - Insiders 1.31.0-insider (f125fdfa20b217dea34001eac9866322418226ce, 2019-02-01T14:24:26.003Z)
OS version: Linux x64 4.15.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|5.77GB (1.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
beautify|Hoo|1.4.8
theme-karyfoundation-themes|kar|18.2.1
azure-account|ms-|0.8.0
lsp-inspector|oct|0.0.1
vscode-open-in-github|sys|1.10.1
ayu|tea|0.17.0

</details>

**Comment by isidorn** [comment]
I also see this on mac

**Comment by isidorn** [comment]
@dbaeumer maybe some .css changed and the smoke test was not updated. I suggest to check the css path of the item that can not be found.

**Comment by dbaeumer** [comment]
I reran the test and they fail bitterly now because of the refactoring we did. This needs to be tested manually for now. We first need to get new translations.

**Comment by dbaeumer** [comment]
Reran the test today and they passed. Closing.
