### ISSUE TITLE
Peek definition and goto definition for css?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6776]
#6655

- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. open a .css file notice that there are 'Peek definition' and ' goto definition'
2. These actions do not do anything in css - why do we have them in the context menu?
3. I would expect them not to be in the context menu - same as for .html

**Comment by sandy081** [comment]
These are used for variables see #3077. Hence they are enabled.

**Comment by pranaygp** [comment]
Hopefully helpful https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek :)
