### ISSUE TITLE
Add a command to copy VS Code version/commit and OS version to clipboard

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#67764]
This would be super useful for me. A lot of times I want to directly edit on GitHub instead of having to go through issue reporter.

Guess we can use the new clipboard API?

@RMacfarlane I can send a PR for this.

**Comment by RMacfarlane** [comment]
There's currently a two-step way of doing this - running `Help: About code` and then `Copy` from that dialog, so I'm not sure we need another command for this. I guess it would be more discoverable to have a `Copy version information` command

**Comment by octref** [comment]
On macOS I only get this window, and I can only copy version and name one by one:

![image](https://user-images.githubusercontent.com/4033249/52372667-97b9fa00-2a0d-11e9-8dce-3a08052cadda.png)

I want a command that puts this in my clipboard:

```
VS Code version: Code - Insiders 1.31.0-insider (b313db6c58f8c02181a33cd3b5b4b17c64a5b85d, 2019-02-05T10:10:06.179Z)
OS version: Darwin x64 18.2.0
```

**Comment by RMacfarlane** [comment]
Ah, I meant literally running the command `Help: About code`:

![screen shot 2019-02-06 at 12 51 51 pm](https://user-images.githubusercontent.com/3672607/52372856-0e56f780-2a0e-11e9-9424-e9892d401636.png)

which seems to have different behavior than the About menu

**Comment by octref** [comment]
I see. On the one hand I feel we should not provide multiple ways of doing essentially the same thing, but on the other hand I want the copied data to follow the issue reporter's format:

```
VS Code version: Code - Insiders 1.31.0-insider (b313db6c58f8c02181a33cd3b5b4b17c64a5b85d, 2019-02-05T10:10:06.179Z)
OS version: Darwin x64 18.2.0
```

Your call, I'm fine either way.

**Comment by RMacfarlane** [comment]
I'd prefer to avoid introducing another command, so am closing this issue.
