### ISSUE TITLE
Make code examples in Doc less distracting

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/vscode#67763]
Issue Type: <b>Feature Request</b>

as screenshot, I found that the syntax highlighting in the doc has the same style as the real code, which easily distracts me when reading code.

It would be great if the example code in doc has slightly different style, for example, fainted a bit, smaller fonts, different background, etc., I am not sure.

![image](https://user-images.githubusercontent.com/7583839/52142230-fb5ab680-260c-11e9-8370-53d138941494.png)

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.18323

**Comment by mjbvz** [comment]
Themes can customize the highlighting of code in jsdoc comments (or even disable the highlighting entirely)
