### ISSUE TITLE
Implementers of implements vscode.FileSystemProvider should be able to redirect

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#67760]
When implementing vscode.FileSystemProvider it would be useful to be able to redirect to another scheme.

Here is a concerete scenario (and is actually one of 3 we are actually employing today):

Your repository (such as the Windows OS code repository) is exteremly large. Because of its size, "file system virtualized" is used so that all of the code is not actually placed on your local file-system until a request is made to read the file.  So, searching the code base is actually done using an Azure web service. The results you get back have relative URIs to the source code. A URI is constructed (call it "azureSearchResult:<dataFromTheSearchReqeust>".

When the item is clicked on (whether it be in the problems pane, search pane, etc.) VSCode currently expects the "azureSearchResult:" to do all of the "stat\read\write\watch" operations. But, what the provider really wants to do is something like "hey, the local file system copy of the file (hash) is exactly the same as the search result (has), so let's just show the local file". But, the file system provider has no way to "redirect" from "azureSearchResult:" to "file:". As a result, it must essentially re-implement all the functionality that the "file" provider in VSCode already provides. (This also doesn't include the fact that if a file system provider IS actually just reading\writing a local file system file that VSCode's other UI - the explorer window, etc - does not properly select it do to the URI being different).

So.... to that end.. This is what I'd like to propose:

```Typescript
export enum FileType {
    Redirect = 128
}

export interface FileSystemProvider {
    resolveRedirection(uri: Uri): Uri | Thenable<Uri>;
}
```

This allows the implementation of the File-System-Provider to inspect\perform some work during the "stat" call to see if it wishes to redirect, or not. (For example, in a code-search scenario it may be desirable to show the remote contents, or the local contents).

Other options could be a FileSystemError class that supports redirection.

**Comment by jrieken** [comment]
What about using `SymbolicLink` and adding something like [readlink](http://man7.org/linux/man-pages/man2/readlink.2.html)?

**Comment by GabeDeBacker** [comment]
I thought about that as well. I think that it would some confusion as it is valid to return "SymbolicLink" and still implement the other file-system provider methods (read, write, etc.), So overloading "SymbolLink" like with a method like "readLink" or "resolveLink" would also require an affordance for the file system provider to say that it doesn't want to resolve the link.

I think a more prescriptive approach is best for this.

Thoughts?

**Comment by GabeDeBacker** [comment]
@jrieken - Any thoughts on this? Our team could really use it and I'm totally willing to do the leg work to implement it. Just wanted to get API buyoff before starting.

**Comment by jrieken** [comment]
The challenge is that redirection isn't really something that well-known in the domain, e.g there is no posix equivalent to it (or I don't know it) which makes it harder to build good, stable API. 

An alternative approach for the redirection problem might be #48034. That's about exposing "reading" apis for known file systems, e.g. you will be able to call `await vscode.workspace.writeFile(uri, blob)` making a forward-to-local-disc-implementation very simple.

**Comment by GabeDeBacker** [comment]
@jrieken - Hmm, that doesn't address the fact that VSCode's UI (such as the file explorer) cannot sync with URI schemes from other providers. That's the goal I am after. Our scheme foo: knows that in some cases it really wants to be a "file:" and have all the VSCode UI goodness, and in other cases, it wants to do a write.

I..e.
```TypeScript
export class MyFooFileSystemProvider implements vscode.FileSystemProvider {
    public stat(uri: vscode.Uri): vscode.FileStat | Thenable<vscode.FileStat> {
        return new Promise<vscode.FileStat>((resolve, reject) => {
            if (fs.existsSync(uri.fsPath)) {
                fileType |= vscode.FileType.Redirection;
                resolve({
                    ctime: fsStats.ctimeMs,
                    mtime: fsStats.mtimeMs,
                    size: fsStats.size,
                    type: fileType
                });
            } else {
                  // Do custom stuff.
            }
        });

    public readDirection(uri: vscode.Uri): Thenable<[string, vscode.Uri[]> {
      /// Convert the "foo" URI to "file" URI
    }
}
```

**Comment by jrieken** [comment]
> Hmm, that doesn't address the fact that VSCode's UI (such as the file explorer) cannot sync with URI schemes from other providers. That's the goal I am after.

**Comment by GabeDeBacker** [comment]
@jrieken - Certainly. Leaving out specific names and file names to protect our internal details.

In our scenario we have a file-system provider with a scheme "X:'. The scheme is used to show present diagnostics in the problems pane. So an example would be "X:e:\myGitRepos\someRepo\someFile.cpp".

An importnat note that the same scheme is used to represent things other than files objects.

When the problem is clicked on in the problems pane, and VSCode calls "stat" the file system provider for scheme "X:", the "stat" implementation makes some decisions based on the URI present. In almost all cases, the file system provider for scheme "X:" will end up reading an actual file-system object (which may or may not be the one present in the URI).

Now, when VSCode presents an editor for say "X:e:\myGitRepos\someRepo\someFile.cpp" it creates a "tab" for that resource, but what it does not do is expand the explorer tree and select the file on the left-hand side of the UI because it does not know that the resource represents a "file:" scheme object. This is an important clue to the user that they are indeed editing a file system object.

Also, the "open editors" section in the "Explorer" does show what it "believes" to be a path to "e:\myGitRepos\someRepo\someFile.cpp" but even that is not correct as it shows the full-path instead of the workspace relative paths it normally shows.

By allowing a file-system-provider to do an actual redirection to another provider (instead of just calling through to it) would allow all this to function normally.

I'm sure there are more pieces of UI that I just haven't recognized yet that would also benefit from this.

Does this help?

**Comment by jrieken** [comment]
> Now, when VSCode presents an editor for say "X:e:\myGitRepos\someRepo\someFile.cpp" it creates a "tab" for that resource, but what it does not do is expand the explorer tree and select the file on the left-hand side of the [...]

Okay. I think I understand. In your scenario you aren't opening the folder `X:e:\all\and\some\part\of\it` but you open `file:///e:/and/some/part/of/it` and have `X:e:\all\` somewhere else for which problems et al are computed. It's correct that revealing files and editors in the explorer won't work when used like that. Did you try opening the `X:`-schemed folder instead of a local folder? E.g. start vs code like so `code --folder-uri X:e\all`? VS Code should just behave like "normal" when running in that mode, alternatively you can create a workspace file listing those "remote" folders. 

> By allowing a file-system-provider to do an actual redirection to another provider (instead of just calling through to it) would allow all this to function normally.

Apart from this being a bit exotic in the file system world, this is challenging as most UX decisions are made synchronously, often based on the scheme. Context menus are such a case, we don't populate them asynchronously when right clicking. Language feature selection works of schemes and nowhere in our code we have async-hooks before looking at the scheme. While we might be able to wire this in before stat'ing and reading we won't be able to wire this in correctly into the UX. I also expect API carnage: making an open request with uri *A*, will return a document with uri *B* - something no-one expects today.

**Comment by GabeDeBacker** [comment]
@jrieken - I see your point about truly supporting this in VSCode as far as all the consumers of the file-system providers.

I would like to clarify that I don't think the scenario is exotic at all. Below is another example of where we would like to use this.

Another scenario that we would like to use this for is code-search. Our repository is so large that code-search is done using Azure and not done locally.

Our extension is currently making use of the proposed code-search APIs.

So, when the results come back, we have a couple of options we'd like to consider.
If the file is exactly the same as the local file, then, just show the user the local file (and have VSCode know it is the local file)
If the files are different, the user should have the option of just viewing the remote or viewing the local file, or even a diff of the two.

A comment I'd make is that VSCode's "file system provider" isn't locked down to "file system" files. Even in the documentation it says:

` It allows extensions to serve files from remote places,
	 * like ftp-servers, and to seamlessly integrate those into the editor.`

So it can handle all kinds of URIs. Things like HTTP for example certainly support redirection.

**Comment by jrieken** [comment]
> So it can handle all kinds of URIs. Things like HTTP for example certainly support redirection.

Yes, but you didn't answer my question why you cannot open the X-scheme folder and why you have to open a folder on disk. That's what's meant here, be a resource provider and be integrated just like the file-scheme

**Comment by GabeDeBacker** [comment]
@jrieken - I think I am not communicating something very clearly. The "x-scheme" URI doesn't necessaryily point to a file-system type object at all, but it could redirect to one.

For example, our a code-search URI scheme that we have implemented can look like this:
adoCodeSearchResult:<guid>/<remoteId>/<hash>

And that (plus other metadata) is what we give to VSCode.

When VSCode then calls "stat" on our "adoCodeSearchResult" object, we make a decision as to whether to return "text content" back from a cloud service OR ask the cloud service what "local file path" the object is supposed to represent. In both cases, our ```FileSystemProvider``` has to implement both local read\write file operations, and cloud read file operations (as cloud writes are not allowed).

It is a little confusing as to why it is called ```FileSystemProvider``` as URIs (which is what it deals with) are not restricted to being backed by an actual "file system".
