### ISSUE TITLE
git push -u doesn't work after git remote add origin <originrepo>.git

### ISSUE THREAD

**Issue by zoperator** [Microsoft/vscode#67765]
- VSCode Version:1.30.2
- OS Version: OEL 7.5, Windows 10

Steps to Reproduce:

Per steps noted here: https://code.visualstudio.com/docs/editor/versioncontrol#_i-initialized-my-repo-but-the-actions-in-the-menu-are-all-grayed-out 

1. run > git remote add origin https://github.com/<repo owner>/<repo name>.git in integrated terminal
2. run > git push -u origin master 
3. failure text
4. you also cannot stage, commit, or push to your code, an origin does not show up
5. restart VSCode after the stage, commit, and push attempt
6. run git push -u origin master  works
7. stage, commit, and push to, an origin shows up and is able to run as well as the cloud icon in the bottom left is now showing up.
![capture](https://user-images.githubusercontent.com/33821072/52146900-bc3b5e00-262a-11e9-97e9-eeaa01a83ee8.PNG)

**Comment by joaomoreno** [comment]
Isn't that an issue with Git instead of Code?

**Comment by zoperator** [comment]
I would have expected Code to be able to pick up a new origin from the terminal without having to reload the app. Even the terminal does not seem to be able use the new origin until after Code is reloaded. As shown in my screen shot, it can see it, just cannot use it. This extra step is a hassle and makes one consider not using Code if they are not aware of this additional step. 

Running those Git commands outside of Code does not have this issue. i am able to immediately do a push after adding an origin.

**Comment by joaomoreno** [comment]
> Running those Git commands outside of Code does not have this issue. i am able to immediately do a push after adding an origin.

I am absolutely sure this reproduces without VS Code.

I just understood what's happening here. After `git init`, there is no `master` branch until you do your first commit. So git is right to complain: `src refspec master does not match any`. The `master` branch doesn't exist at that point.
