### ISSUE TITLE
vscode stopped responding to keyboard, and started taking the wrong keys when pressed

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#67767]
vscode from time to time starts freaking out when receiving keyboard input. after some time or restarting vscode the problem is gone. 

just now i was working and:
- backspace and delete did not work. 
- pressing ctrl + z resulted in a bunch of 0's being entered. 
- numpad wasn't working. 
- minimizing vscode and switching to chrome to open this bug report caused the problem to go away.

this is the 3rd time this has happened.

**Comment by alexandrudima** [comment]
@r3wt What OS are you on? Are you using remote desktoping or something like that? This is the first time I hear of such an issue, do you have a special environmental setup?
