### ISSUE TITLE
Strict null check 'quickOpenWidget.ts'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67774]
Part of #60565

Tracks updating `./vs/base/parts/quickopen/browser/quickOpenWidget.ts` to have strict null checking. This should be the last file in `vs/base` that needs strict null checking

**Steps**

1. Add `./vs/base/parts/quickopen/browser/quickOpenWidget.ts` to the `include` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works

**Comment by bpasero** [comment]
I think it makes little sense to invest more into this widget which is going to be replaced by @chrmarti implementation ideally (see https://github.com/Microsoft/vscode/issues/29096).

@chrmarti is there something that would prevent us from using your widget for quick open in general? E.g. something missing? We also need to keep in mind that the standalone editor is using this widget, so your solution would have to live in base as well.

**Comment by chrmarti** [comment]
@bpasero The feature gaps should be small by now. Moving quick open over will still be a major refactoring. If it is not much work, we can do the strict null checks to keep that effort unblocked.

**Comment by bpasero** [comment]
I pushed a half-baked strict null solution knowing that this widget has reached EOL.
