### ISSUE TITLE
Terminal in Latest Stable Release is Buggy

### ISSUE THREAD

**Issue by AdmiralCode** [Microsoft/vscode#67773]
- VSCode Version:  Version 1.30.2 - user version
- OS Version:  Windows 10 Build 1803 (Windows hasn't prompted me to upgrade) / Ubuntu 18.04 Server

Steps to Reproduce:

1. Create an Ubuntu 18.04 Virtual Machine (I did this in VMWare workstation)
2. Use the Windows version of OpenSSH to ssh into a machine with the settings below (I use workspace settings, is there a way to not have to do this at a workspace level btw?):
3. Share a folder with the Windows host and put your code in there.  In my case it's Ruby code.
```
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\OpenSSH\\ssh.exe",
    "terminal.integrated.shellArgs.windows": [
        "user@192.168.1.3",
        "-t",
        "cd ~/Documents/Projects/MyProject;bash --login"
    ],
```
Occasionally an external terminal window will open along with the integrated terminal.  It has a very tiny font.  If you close it, the integrated terminal closes.

**Comment by AdmiralCode** [comment]
Oh and I get random freezes as well and I have to close the terminal.

**Comment by Tyriar** [comment]
Sounds like winpty issues: https://github.com/Microsoft/vscode/issues/45693 (these should hopefully go away in Windows 190x)
