### ISSUE TITLE
Create method quick fix java generics fails

### ISSUE THREAD

**Issue by CrispyDrone** [Microsoft/vscode#67778]
Issue Type: <b>Bug</b>

1. Use a method using generics in java without first declaring it
2. Use the quick fix (ctrl + .) option to create the method

This results in a method signature and body being generated without the necessary generic parameters.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpextensions|jch|1.3.0
csharp|ms-|1.17.1
java|red|0.38.0
LiveServer|rit|5.3.1
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1
vim|vsc|1.0.6

</details>

**Comment by mjbvz** [comment]
Please file this against the java extension
