### ISSUE TITLE
Endless requests for json config files

### ISSUE THREAD

**Issue by dataspun** [Microsoft/vscode#67779]
Issue Type: <b>Bug</b>

With files open in vscode from a remote file share, vscode or related underlying process will make endless requests for tsconfig.json and jsconfig.json files -- these requests are logged as 404s on the file share server at roughly 1 request per second.

Example request:
https://www.foobar.com:443/tsconfig.json

Logged with user-agent:
Microsoft-WebDAV-MiniRedir/10.0.17134

VS Code version: 
Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/28426
