### ISSUE TITLE
Variables in debug viewlet blink on every keypress for type to filter

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67770]
- Type in variables view
- The highlighted variable values do a blink animation with every keypress

![feb-01-2019 14-29-15](https://user-images.githubusercontent.com/323878/52153160-c7dc5400-262d-11e9-83d6-8acf8fea613e.gif)

**Comment by isidorn** [comment]
Fancy!

**Comment by isidorn** [comment]
@joaomoreno the issue here is that whenever a user types we re-render all the elements And whenever a variable box gets rendered we trigger the animation.
Not really sure how to fix. Any ideas?

**Comment by joaomoreno** [comment]
@isidorn Don't flash if the value doesn't actually change.
