### ISSUE TITLE
Allow Rust core types to be highlighted just like user types

### ISSUE THREAD

**Issue by nox** [Microsoft/vscode#67788]
I'm tired of seeing `char`, `bool`, etc being highlighted differently than `Arc<T>` etc, especially when `char` and friends can appear in module paths, where they don't refer to the core type. Is there any chance the theme could be updated to stop doing that?

**Comment by dbaeumer** [comment]
Not sure if this is a theme or grammar problem.

**Comment by alexr00** [comment]
I see, thanks for the example. This is an issue with the grammar we use for Rust. It categorizes `char` in `core::char::DecodeUtf16Error` as storage.type.core.rust and it should probably just categorize it as source.rust.

**Comment by alexr00** [comment]
This issue was moved to zargony/atom-language-rust#142

**Comment by nox** [comment]
No no no, the problem is double: the Rust syntax badly highlights `char` as part of `core::char::DecodeUtf16Error`, *but* I also don't want `char` on its own to be highlighted differently than `foo`. How can I tell VS Code that I don't want `storage.type.core` to be any different from other kind of identifiers?
