### ISSUE TITLE
weird cursor-word space issue with zsh, oh-my-zsh

### ISSUE THREAD

**Issue by heyask** [Microsoft/vscode#67789]
- VSCode Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

- OS Version: Windows 10 Pro (1809)
OS Build: 17763.292

Steps to Reproduce:

1. Windows Subsystem for Linux (ubuntu 18.04).
2. install zsh, oh-my-zsh on WSL.
3. install VS Code and run.
4. Terminal: Select Default Shell -> WSL Bash
5. configure ->` { "terminal.integrated.shell.windows": "C:\\Windows\\System32\\wsl.exe" }`
5. open VS Code integrated terminal
6. typed... (word-cursor spacing bug)
7. change terminal font-family to "Ubuntu Mono derivative Powerline" in configuration.
8. typed... (same Bug)

Does this issue occur when all extensions are disabled?: Yes

----

This problem occured in Hyper Terminal too. exactly same. (maybe Electron apps are have same problem?)
in Hyper, I changed font to "Ubuntu Mono derivative Powerline", and problems solved.
but in VSCode, no effect with changing font.
the bug is not occured in cmd, bash but in zsh with oh-my-zsh.

here is my video capture.

![3](https://user-images.githubusercontent.com/13181635/52165834-2ea26000-2749-11e9-8e27-787b198286c8.gif)

![4](https://user-images.githubusercontent.com/13181635/52165835-3104ba00-2749-11e9-9093-6484e5715181.gif)

**Comment by Tyriar** [comment]
Can you tweak your `$PS1` to remove the powerlines and special characters from the prompt? This is likely caused by https://github.com/xtermjs/xterm.js/issues/1709 where some character in the prompt is being assigned the incorrect width.

**Comment by heyask** [comment]
@Tyriar I found that something wrong with vscode terminal and oh-my-zsh theme "agnoster".
because, the other oh-my-zsh themes or bash are ok.
agnoster theme's `$PS1` is `%{%f%b%k%}$(build_prompt)`

so I looked up the source code of the theme.

**~/.oh-my-zsh/themes/agnoster.zsh-theme**
```
## Main prompt
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_git
  prompt_bzr
  prompt_hg
  prompt_end
}
```
in build_prompt(), removing **prompt_end**, works.


```
SEGMENT_SEPARATOR=$'\ue0b0'

# End the prompt, closing any open segments
prompt_end() {
  if [[ -n $CURRENT_BG ]]; then
    echo -n " %{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
  else
    echo -n "%{%k%}"
  fi
  echo -n "%{%f%}"
  CURRENT_BG=''
}
```
in prompt_end(), removing $SEGMENT_SEPARATOR resolve problem. 
`$SEGMENT_SEPARATOR` is `$'\ue0b0'`
$SEGMENT_SEPARATOR is triangular. 



This is with $SEGMENT_SEPARATOR. space bug issue.
![e09684a0-fcfd-49bd-93c0-f09c9253478c png](https://user-images.githubusercontent.com/13181635/52287204-1894d980-29ad-11e9-8f7d-e65cf3b3ce65.jpg)

this is removing $SEGMENT_SEPARATOR. works fine but triangle is hidden.
![e37b87c2-92a0-4a4d-8aae-3e43af5758ec png](https://user-images.githubusercontent.com/13181635/52287209-1a5e9d00-29ad-11e9-95b9-849d35d94e88.jpg)


I think the cause of the spacing bug is something wrong with `$'\ue0b0'` character, maybe?

**Comment by crupest** [comment]
This also happen in PowerShell.

My system info:
Version: 1.32.2 (user setup)
Commit: e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951
Date: 2019-03-13T02:00:46.035Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Also notice that my system's locale is simplified Chinese (GB2312), while I use vscode in English, which I think might help.

I'm willing to provide any other info!

![ezgif-1-b5d9f3879e37](https://user-images.githubusercontent.com/15831781/54339412-b6945780-466f-11e9-81bb-7c8cd5eb64bf.gif)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
