### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by homayon1369** [Microsoft/vscode#67785]
Issue Type: <b>Bug</b>

I'am not connect to nox for emulator android and use for flutter

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
android-emulator-launcher|343|0.9.0
html-snippets|abu|0.2.1
flutter-snippets|ale|0.0.2
flutter-view-vscode|blu|1.1.0
dart-code|Dar|2.22.3
flutter|Dar|2.22.3
emulate|Die|0.0.7
bloc|Fel|0.1.3
flutter-stylizer|gml|0.0.9
pubspec-assist|jer|0.3.2
dart-import|lua|0.1.0
awesome-flutter-snippets|Nas|1.0.5
dart-syntax-highlighting-only|osc|1.0.0
mvvm-flutter-widget|pan|0.2.1

</details>

**Comment by lamka02sk** [comment]
That is a very descriptive title :100:

**Comment by dbaeumer** [comment]
@homayon1369 please follow the steps here to write a good bug report. Otherwise we can't help you: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests
