### ISSUE TITLE
PHP EXECUTABLE NOT FOUND

### ISSUE THREAD

**Issue by Jidezzz** [Microsoft/vscode#67796]
PHP executable not found. Install PHP 7 andadd it to your PATH or set the php.executablePath setting
Source:PHP IntelliSense

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by roblourens** [comment]
That is correct, add it to your path or set that setting.
