### ISSUE TITLE
Suggestion menu writes the first suggestion after write a dot

### ISSUE THREAD

**Issue by darthzyklus** [Microsoft/vscode#67793]
- VSCode Version: 1.30.0
- OS Version: Manjaro 18.0

Steps to Reproduce:

1. Write the word process on a js file and then write a dot
2. The editor will write the first suggestion without press enter

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
/question

https://stackoverflow.com/questions/48609354/visual-studio-code-autocomplete-when-i-press-key-any-way-to-disable

**Comment by darthzyklus** [comment]
@usernamehw thank you!
