### ISSUE TITLE
Don't close suggest widget when cycling with tab completion

### ISSUE THREAD

**Issue by dschuessler** [Microsoft/vscode#67795]
I really like the `"editor.tabCompletion": "on` setting, but as soon as I insert a suggestion the suggest widget closes and I am no longer able to see the suggestions I am cycling through while pressing `Tab`.

I would expect the suggest widget to stay open, mainly because I consider the concept of tab completion as indifferent to the presence of the widget. When I turn `tabCompletion` on and from then on the widget disappears as soon I am choosing what to insert, this kind of feels like a surprising side effect.

I would prefer the widget to stay open as long as I am cycling through suggestions, close/refresh it with the next Non-tab keystroke and therefore have it open as long as I am using tab completion. This way I instantly see how often I have to press tab until I reach the suggestion I want to insert.

Therefore I suggest an additional option to keep the widget open when using tab completion.

Also I guess this is what #59828 was actually about, but I don't use Xcode, so I am not 100% sure.

**Comment by jrieken** [comment]
> I really like the "editor.tabCompletion": "on setting, but as soon as I insert a suggestion the suggest widget closes and I am no longer able to see the suggestions I am cycling through while pressing Tab.

That's what this feature is all about. Inserting suggestions *without* the suggest widget visible...

**Comment by dschuessler** [comment]
> If you disagree, please explain what is expected and what is not in more detail.

I would not expect to have `tab` cycling coupled with the visibility of the suggestion widget. The disappearance of the widget is neither what I'd expect when turning `"editor.tabCompletion"` to `"on"`, nor what I'd expect when I read the feature documentation: "Enables tab completions."

When I turn `"editor.tabCompletion"` to `"on"` I'd expect to be able to insert completion suggestions with `tab`. I would not expect "inserting suggestions without the suggest widget visible..."

If it is a design decision, not to have the possibility to swap out suggestions with the tab key _and_ keep the suggestion widget open at the same time, I disagree with it.

My argument is the following: Logically separating the visibility of the suggestion widget and the ability to cycle the suggestions with the `tab` key increases the users degrees of freedom on customizing the editor.

In my case I would like to be able to have this:

![2019-02-02 23-09-48 2019-02-02 23_11_19](https://user-images.githubusercontent.com/5774545/52223781-afc33980-28a6-11e9-9af1-bfb5d1fa107e.gif)

Please correct me, if I'm wrong, but as far as I can see, this is currently not possible with VS Code.

**Comment by jrieken** [comment]
> Please correct me, if I'm wrong, but as far as I can see, this is currently not possible with VS Code.

You assign `tab` instead of `arrow-up/down` to cycle through the suggestion list which does some of what you want

**Comment by dschuessler** [comment]
Yes, I know. But I have to confirm every suggestion with `Enter` instead of just being able to type on.

I would be grateful if you could briefly confirm my understanding that by design there is and will be no option enabling what I want.

**Comment by octref** [comment]
Unlocking since my request was marked as duplicate of this one: #74111

>  That's what this feature is all about. Inserting suggestions without the suggest widget visible...

I thought this feature is all about I can use `tab` rather than
- using up/down which are at more awkward keyboard positions than `tab`
- typing out the full suggestion

Currently if I'm using tab to select non-first item, then my subsequent `tab` are all guesses in the dark because I can't memorize all the list. This isn't really what I want...

![gif](https://user-images.githubusercontent.com/4033249/58186673-363f3380-7c6a-11e9-9b11-61b6a373f52f.gif)

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/70532
