### ISSUE TITLE
Commit (amend) will commit staged and unstaged changes.

### ISSUE THREAD

**Issue by superhawk610** [Microsoft/vscode#67797]
- VSCode Version: 1.31.0-insider (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project inside a Git repository.
2. Make some changes and then create a commit using the source control panel.
3. Change 2 files and then stage one of them.
4. Make an amend commit using the source control panel.
5. Note that both files will be committed, not just the that was staged.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
There are two commands:

- Commit All (Amend)
- Commit Staged (Amend)

Which one did you run?

**Comment by superhawk610** [comment]
D'oh, the first! Thanks for the tip.
