### ISSUE TITLE
Emmet quick suggestions are distracting when entering text

### ISSUE THREAD

**Issue by mhoelzel142** [Microsoft/vscode#67790]
- VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
- OS version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. edit settings.json and set editor.quickSuggestions: "strings" to false. 
2. Create an HTML document and create an element (a `<p>` element for example)
3. Start typing a string between the opening `<p>` and closing `</p>`. 

Does this issue occur when all extensions are disabled?: Yes

Anything typed as a literal string between HTML tags opens the quick suggestions box. It seems the only way to disable this is to turn off "other" suggestions. This is undesirable as disabling "other" suggestions also removes access to snippets within tags (such as when using the Angular snippets extension, the code <li a-ngF should suggest *ngFor, but with "other" disabled it shows no snippet suggestions at all). 

![2019-02-02-09-27-19](https://user-images.githubusercontent.com/15573387/52166016-b21e6b80-26cd-11e9-832e-a5c74297bd2a.gif)

Edited to include proper (VS generated) Code and OS version info.

**Comment by aeschli** [comment]
The element content is not really a string, and it would be wrong treating it like that.

The proposals you see here are all from Emmet and they are not wrong, but I agree that they are distracting when entering text as there are so many proposals.

It would be good if Emmet could be configure to not show up as quick suggestions.

**Comment by ramya-rao-a** [comment]
To avoid emmet from appearing in the quick suggestions, use the below setting 

`"emmet.showExpandedAbbreviation": "never"`

**Comment by mhoelzel142** [comment]
> 
> 
> To avoid emmet from appearing in the quick suggestions, use the below setting
> 
> `"emmet.showExpandedAbbreviation": "never"`

I tried this for HTML-specific user settings as well as globally in settings.json, it made no difference. Emmet quick suggestions still persist inside HTML tags.

**Comment by octref** [comment]
But imagine I'm writing `<div>Here is my link: a</div>`, then Emmet would be useful.

Whatever default we choose, it'll annoy 50% of people.

> "emmet.showExpandedAbbreviation": "never"

This does work for me though.

![image](https://user-images.githubusercontent.com/4033249/52666236-903d9980-2ec2-11e9-9596-247fd2ba9353.png)
