### ISSUE TITLE
Call Stack appears broken

### ISSUE THREAD

**Issue by importnetminecraft** [Microsoft/vscode#67791]
Issue Type: <b>Bug</b>

If you debug a program the call stack is empty. I tested with java and go.

VS Code version: Code - Insiders 1.31.0-insider (8f56013e8f66650c1b0b65cc5c502691e307db21, 2019-02-01T18:34:04.940Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
vscode-multi-line-tricks|big|0.0.3
bracket-pair-colorizer-2|Coe|0.0.25
vscode-clock|Com|0.0.1
marshal-command-code|din|1.1.2
vscode-html-css|ecm|0.2.0
vscode-hacker-typer|jev|0.1.1
auto-comment-blocks|kev|1.0.1
selected-character-count|mou|0.0.1
cpptools|ms-|0.21.0
Go|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
cursor-tools|nau|2.0.0
material-icon-theme|PKi|3.6.2
java|red|0.38.0
vscode-xml|red|0.3.0
vscodeintellicode|Vis|1.1.2
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1
vscode-wpilib|wpi|2019.2.1

</details>

**Comment by weinand** [comment]
I can reproduce this for Java.
Variables and watches tree work fine.

**Comment by weinand** [comment]
I saw this once:
![2019-02-04_14-10-36](https://user-images.githubusercontent.com/1898161/52211833-497ced80-288b-11e9-9edb-cc550e5781b0.png)

and this error in the dev tools console:
![2019-02-04_14-11-36](https://user-images.githubusercontent.com/1898161/52211850-539eec00-288b-11e9-9a26-20b68c9a5b96.png)

**Comment by weinand** [comment]
Added Verified label after @joaomoreno had approved the corresponding PR #67856
