### ISSUE TITLE
[JavaScript] Incorrect 'new' keyword warning

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#678]
I'm seeing this warning complaining about me calling a non-void function with the `new` keyword, when it actually is a void function.

![void_function](https://cloud.githubusercontent.com/assets/2193314/11412024/49d59198-938c-11e5-8c88-f0b761601310.png)

Reproduces with this code:

```js
var BinomialHeap = function (customCompare) {
  this.head = undefined;
  this.nodeCount = 0;

  if (customCompare) {
    this.compare = customCompare;
  }
};

function removeTreeRoot(heap, root, prev) {
  // Remove root from the heap
  if (root === heap.head) {
    heap.head = root.sibling;
  } else {
    prev.sibling = root.sibling;
  }

  // Reverse the order of root's children and make a new heap
  var newHead;
  var child = root.child;
  while (child) {
    var next = child.sibling;
    child.sibling = newHead;
    child.parent = undefined;
    newHead = child;
    child = next;
  }
  var newHeap = new BinomialHeap();
  newHeap.head = newHead;

  heap.union(newHeap);
}
```

It actually goes away when I add `undefined` as an argument but that means the warning is complaining about the wrong thing. Also I don't think it's appropriate for the linter to warn on optional arguments in JavaScript like this by default as that's very strict.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa.
