### ISSUE TITLE
Code hint UI tweek

### ISSUE THREAD

**Issue by dipacs** [Microsoft/vscode#67805]
I really like code hints, I use it a lot. What can be better is, that the code hint badge is visible only when the cursor is on the word with hints. This is not too comfortable, because Usually, my cursor is after that word when I want to use the code hint. Instead, you can replace the code line with a badge which is always visible, and opened when I hit CTRL+. when my cursor is in that line (not just the word). A good example is Eclipse, NetBeans, and IntelliJ.

**Comment by dbaeumer** [comment]
@dipacs could you please attach some screen shots that clarify demo what you expect. I assume you are talking about Code's signature help feature.
