### ISSUE TITLE
VsCode 无法实时预览 Markdown 文件

### ISSUE THREAD

**Issue by MN-WangXiaoNao** [Microsoft/vscode#67800]
每次安装完有关 Markdown 插件，有关的 Markdown 实时预览全部失效

**Comment by KexyBiscuit** [comment]
Translated:
VSCode can't preview Markdown file in real time
Markdown real-time preview is broken after every installation of extensions about Markdown.

**Comment by MN-WangXiaoNao** [comment]
> Translated:
> VSCode can't preview Markdown file in real time
> Markdown real-time preview is broken after every installation of extensions about Markdown.

How to solve Markdown real-time preview failure problem

**Comment by CreeperKong** [comment]
我用的insider版本是好的

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
