### ISSUE TITLE
Markdown base64 not displayed entirely in the documentation panel

### ISSUE THREAD

**Issue by qutreson** [microsoft/vscode#67806]
**Description**

We are developing the 'AL language' extension in VS Code and we are using MarkupContent in order to display our intellisense/on hover documentation as specified on the Language Server Protocol [specifications](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md).

As part of our documentation, we also display some images. We are using Markdown and base64 images (ex: `![MyImage](data:image/png;base64,myImageValueInBase64)`). This works, but, the size of the documentation panel is not correct when displaying the image the first time (when visiting the second time, this is fixed). 

![image](https://user-images.githubusercontent.com/31541422/52174569-05f48780-2796-11e9-8e01-12bc9e62c14f.gif)

**Version**
- VS Code Version: 1.31.0-insider (system setup)
- Commit: 8f56013e8f66650c1b0b65cc5c502691e307db21
- Date: 2019-02-01T18:34:04.940Z
- Electron: 3.1.2
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

**Steps to Reproduce:**

1. Download the 'AL Language' extension from the marketplace.

Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 2.1.79379
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

2. Create a new AL project.
- Ctrl + Shift + P - to open the command bar
- Select 'AL:Go' - to create a new AL project

3. When asked to choose a server or do enter user credentials, just skip it, this is not needed in order to reproduce the issue.

4. Open the HelloWorld.al that was auto-generated, and replace it by the following code:
(the character ^ represent the cursor location for the next step).
```
page 50120 MyPage
{
    actions
    {
        area(Processing)
        {
            action(ActionName)
            {
                Image = ^
            }
        }
    }
}
```

5. Remove ^ and trigger intellisense at this location.

**Expected**: The image (sent as base64 image) should appear.
**Actual**: The image is only partially displayed as the display window is too small. This gets fixed the second time the image is displayed (see gif above). 

Does this issue occur when all extensions are disabled?: I have no other extension installed than the AL one.

**Related issue in our repository**: [Image preview of action Image property not fully visible](https://github.com/Microsoft/AL/issues/4413)

**Comment by dbaeumer** [comment]
@jrieken not sure who owns this now that @ramya-rao-a is gone. Can you please forward if not you. If you think that is pure LSP related please assign back to me.

**Comment by jrieken** [comment]
Seems to be working now

![Oct-28-2020 17-27-10](https://user-images.githubusercontent.com/1794099/97465937-dced3080-1942-11eb-84ad-6ea3eacc2da9.gif)

**Comment by qutreson** [comment]
I just tried with the latest developer preview and it still reproduces:

**Version**:

Version: 1.51.0-insider (user setup)
Commit: bb16786cff3d231facbdcee90741ac25fcffd3ac
Date: 2020-10-28T05:57:23.779Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Screenshots**:

First time displaying the image:
![image](https://user-images.githubusercontent.com/31541422/97469554-d496f480-1946-11eb-8495-3269f685a843.png)

Second time displaying the image:
![image](https://user-images.githubusercontent.com/31541422/97469774-1162eb80-1947-11eb-9db8-aade073bc859.png)


Are you sure that the image in the gif you sent is big enough to trigger the issue?

**Comment by jrieken** [comment]
> @jrieken are you sure that the image in the gif you sent is big enough to trigger the issue?

No - I am not sure. You didn't provide an easy repo sample and I have taken any. 

Also, there were many changes on master today, please try again with next (tomorrow) insiders and iff you still see this then provide the image source

**Comment by qutreson** [comment]
Still reproducing with the one from today

Version: 1.51.0-insider (user setup)
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:01:21.160Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

This is an example of an image that we are sending as Markdown and that would be cropped.

`![New_Image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIISURBVFhHxZZBZ1xhFIaHMmQVQiihzKqE/oBssxq6Gkp/QAllKKGrUCZCKKWUrEopXXXVH9BNd6VkFcqsSlazmlVX4fY5fN8498z7zXy3i5vFY+Z7z3nPecfcuXcGTdPcK1LsEyn2iRRrWPw4fwynMFL1WqRYA4sX0MBc1WuRIkNfp+FX8EDUd1PdWMZ66hnCF7iDV6rHkCKGW8gLPkMrBOeNAdBs+TfX8zv2ZKSI4cKZDfskqxC8LwbgHJcbZ77HI0UD0/swZBWCVxmA92r521xXSDGDWYaAtQC8quWXcWZEih6GqBBjd/4Lz6DzckOKEYbFEBlbrvSq5YYUFQzNIexnZRfpXtIP4CN0Xm5IUcHgw7TgTaFuX43Vp6peonXA/BTyHU6xhKH3OO8j16cw78voax1o+OQMihvfHxH9kZ/R0zrQcATXzhCxi27He5x35PoUf2ASfa3DJjA/SYNmhfrXVP//a6AEQ+NN5h08TDX75PkCNCzI2gOshBQ9DFN3uG1Uh5BihiFq+QyO3dmui+cQb1ZVIaRoYJbLU630MOocQoqYistTfdPjuFMIKWKI94PWlc+5GCDVY4gPsScjRQz+H9Hazw5tY4DU40MUb2BSxDCB7/CiUN8awKA2BZszVnVDijUwdA4W4Jeq1yLFGlhsj+ET2Ff1WqTYJ1LsEyn2iRT7oxn8A/nO4A8FACibAAAAAElFTkSuQmCC)`

That can also be reproduced by installing the AL extension and triggering intellisense as explained in the original post

**Comment by jrieken** [comment]
🤔 

![Oct-29-2020 10-21-36](https://user-images.githubusercontent.com/1794099/97549365-97774480-19d0-11eb-80a9-6ba39059823d.gif)

**Comment by chrmarti** [comment]
Reproduced with the steps in the description on:

Version: 1.51.0-insider
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:00:13.428Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

![Oct-29-2020 15-30-01](https://user-images.githubusercontent.com/9205389/97587605-dbcc0a00-19fb-11eb-8988-c4d6baf832a6.gif)

**Comment by jrieken** [comment]
🤷

**Comment by jrieken** [comment]
The height of the details are measured using `clientHeight`. No idea why this isn't working with images. Adding help-wanted for someone to investigate/teach me

**Comment by tamuratak** [comment]
I think you have to use [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver). The timing of getting `clientHeight` is too early. You have to wait for images to be loaded. With the following patch, it works anyway.

```diff
diff --git a/src/vs/editor/contrib/suggest/suggestWidgetDetails.ts b/src/vs/editor/contrib/suggest/suggestWidgetDetails.ts
index 08b9c064ed..8fb72805a0 100644
--- a/src/vs/editor/contrib/suggest/suggestWidgetDetails.ts
+++ b/src/vs/editor/contrib/suggest/suggestWidgetDetails.ts
@@ -17,6 +17,8 @@ import { Emitter, Event } from 'vs/base/common/event';
 import { ResizableHTMLElement } from 'vs/editor/contrib/suggest/resizable';
 import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
 
+declare const ResizeObserver: any;
+
 export function canExpandCompletionItem(item: CompletionItem | undefined): boolean {
 	return !!item && Boolean(item.completion.documentation || item.completion.detail && item.completion.detail !== item.completion.label);
 }
@@ -43,6 +45,7 @@ export class SuggestDetailsWidget {
 	private readonly _renderDisposeable = new DisposableStore();
 	private _borderWidth: number = 1;
 	private _size = new dom.Dimension(330, 0);
+	private _docsClientHeight = 0;
 
 	constructor(
 		private readonly _editor: ICodeEditor,
@@ -65,7 +68,12 @@ export class SuggestDetailsWidget {
 		this._type = dom.append(this._header, dom.$('p.type'));
 
 		this._docs = dom.append(this._body, dom.$('p.docs'));
-
+		const resizeObserver = new ResizeObserver( () => {
+			this.layout(this._size.width, this._type.clientHeight + this._docs.clientHeight);
+			this._docsClientHeight = this._docs.clientHeight;
+			console.log(`height: ${this._docs.clientHeight}`);
+		});
+		resizeObserver.observe(this._docs);
 		this._configureFont();
 
 		this._disposables.add(this._editor.onDidChangeConfiguration(e => {
@@ -171,7 +179,7 @@ export class SuggestDetailsWidget {
 			this._docs.appendChild(renderedContents.element);
 			this._renderDisposeable.add(renderedContents);
 			this._renderDisposeable.add(this._markdownRenderer.onDidRenderCodeBlock(() => {
-				this.layout(this._size.width, this._type.clientHeight + this._docs.clientHeight);
+				this.layout(this._size.width, this._type.clientHeight + this._docsClientHeight);
 				this._onDidChangeContents.fire(this);
 			}));
 		}
@@ -191,7 +199,7 @@ export class SuggestDetailsWidget {
 
 		this._body.scrollTop = 0;
 
-		this.layout(this._size.width, this._type.clientHeight + this._docs.clientHeight);
+		this.layout(this._size.width, this._type.clientHeight + this._docsClientHeight);
 		this._onDidChangeContents.fire(this);
 	}
```

**Comment by jrieken** [comment]
Thanks @tamuratak!

**Comment by jrieken** [comment]
\closedWith f5a7eb38489b4a27f3dd73dba6c4d04289aa0da8

**Comment by qutreson** [comment]
I can confirm it all works as expected now! Thank you 👍 

![ImageRenderingWorks](https://user-images.githubusercontent.com/31541422/102116005-a01ac180-3e3c-11eb-89ab-8dfa21401302.gif)

**Comment by jrieken** [comment]
All thanks to @tamuratak!
