### ISSUE TITLE
VSCode Exploration [4.0.x] Cannot update due to "Hash Mismatch"

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#67807]
Version: 1.31.0-exploration (user setup)
Commit: 2af86da220e2b4c213d8b81ec5232e37e015054b
Date: 2019-01-24T10:02:57.458Z
Electron: 4.0.2
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Windows_NT x64 10.0.17763.253

Steps to Reproduce:

1. Go to gear on bottom left and click "Check for Updates"
2. Get notification showing "Hash mismatch" with no extra info when expanded
![image](https://user-images.githubusercontent.com/30497573/52176269-6f7d9180-27a8-11e9-9b8d-40f830d91735.png)

Opening DevTools shows this error:
![image](https://user-images.githubusercontent.com/30497573/52176278-90de7d80-27a8-11e9-911d-e74b3bc5746a.png)

And clicking on the file takes me to `workbench.main.js` line 2530

Don't know what's happening, just booted up VSCode for the first time in a week, worked the last time

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by bpasero** [comment]
@joaomoreno this is not electron dependent right, I think its all code from us? E.g. the error seems to originate from:

https://github.com/Microsoft/vscode/blob/a455381/src/vs/base/node/crypto.ts#L11

**Comment by joaomoreno** [comment]
Sure. But if the checksum doesn't match it means the downloaded bits aren't correct, which could happen due to anything in the network request.

**Comment by beastdestroyer** [comment]
> Are you behind a proxy?

No proxy. Using normal router connected to Internet. I'll try again today and see what I get
