### ISSUE TITLE
integrated terminal shows its text in black on MacOS Sierra (same on High Siearra)

### ISSUE THREAD

**Issue by biixiid** [microsoft/vscode#67803]
- VSCode Version: 1.30.2
- OS Version: 10.12.3 (same on 10.13)

Steps to Reproduce:

1. Launch VSCode
2. View -> Terminal

Does this issue occur when all extensions are disabled?: Yes/No
Yes

See screenshots:
1.
![1](https://user-images.githubusercontent.com/37418522/52173904-90a1aa80-27c7-11e9-9882-be38d137b96c.png)
Integrated terminal (iterm for abbr.) could not show its text in proper color. so it looks like blank. but cursor is there and its interactive.

2.
![2](https://user-images.githubusercontent.com/37418522/52173905-90a1aa80-27c7-11e9-926f-fdfbe37e3354.png)
When you resize window/pane, at some point , cursor in iterm disappears and iterm becomes non interactive.

3.
[logs.zip](https://github.com/Microsoft/vscode/files/2825284/logs.zip) - Logs of launch by /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --log trace.

**Comment by Tyriar** [comment]
Can you run this command via the command palette:

<img width="362" alt="screen shot 2019-02-05 at 6 45 38 am" src="https://user-images.githubusercontent.com/2193314/52280874-b0dd8080-2911-11e9-835f-b4b237e02216.png">

Then copy and paste the messages output in the console when typing into the prompt? (Help > Toggle Developer Tools > Console)

**Comment by matfricker** [comment]
> Can you run this command via the command palette:
> 
> <img alt="screen shot 2019-02-05 at 6 45 38 am" width="362" src="https://user-images.githubusercontent.com/2193314/52280874-b0dd8080-2911-11e9-835f-b4b237e02216.png">
> 
> Then copy and paste the messages output in the console when typing into the prompt? (Help > Toggle Developer Tools > Console)

Here you go:

![screenshot 2019-02-05 at 15 00 14](https://user-images.githubusercontent.com/1778412/52281815-c6c16480-2956-11e9-9a2b-0b871feea42d.png)

**Comment by Tyriar** [comment]
@matfricker can you include the prompt as well, so turn on the logging then press enter and type a message?

**Comment by matfricker** [comment]
Sorry, is this what you are after? When you say prompt I am assuming you want to see what I am typing into the terminal window? Have included the log file, but that does not look helpful either. 

![screenshot 2019-02-05 at 15 48 53](https://user-images.githubusercontent.com/1778412/52285067-992be980-295d-11e9-91c2-9a6d78768346.png)


[-1549381824047.log](https://github.com/Microsoft/vscode/files/2832753/-1549381824047.log)

**Comment by biixiid** [comment]
@matfricker thanks.

i switched to light theme and terminal text appeared. switched back to dark+ and now it shows text.
![now_ok](https://user-images.githubusercontent.com/37418522/52394848-ca83f100-2ae6-11e9-832b-e41fbd687775.png)


@Tyriar 
I could not remember exactly, but i guess dark+ theme was chosen when i install VSCode. Was it reason of this issue?

**Comment by trondarild** [comment]
I have the same issue on Ubuntu 18.04, vsc 1.30. The terminal goes dark after screensaver, but goes back to normal when flipping between color themes.

**Comment by Tyriar** [comment]
@matfricker the logs say [30m before the text, that is an instruction from your shell to draw the text black. Looks like that's working as expected.

@biixiid does it happen always or only after waking your system up from sleep?

**Comment by biixiid** [comment]
@Tyriar 
Ok. Let me tell what was happened.

1. i installed vscode in sierra. chose dark+ theme.
2. noticed iterm(integrated terminal) is not working properly. Showing text in background color, so no contrast. but cursor is there and i can type, means its interactive. also resizing pane/window makes cursor in iterm disappears, means it is non interactive.
3. complained here and @matfricker suggested switch between theme will solve it.
4. Followed it then my iterm problem is gone and solved.

i can tell it is not because of sleep because my computer is configured as non sleep mode

just recently, yesterday or prior yesterday i cant remember exact date, iterm became non-interactive and went completely blank when i was resizing pane. So i had to quit vscode and launch it again, then iterm worked properly.

**Comment by matfricker** [comment]
Just to confirm, when I mentioned changing theme to a lighter theme text was still black. My suggestion was more that the black text was more ledgable against a white background. If I switched back to a dark theme it didn't change the text colour. The text colour stayed black and still hard to read due to the contrast between background of the terminal window and text colour.

@Tyriar would you suggest it's the colour settings in iterm? I thought it may be my terminal profile settings so fiddled with those, but no luck. I have also ended up switching to bash instead, which again points to iterm and not vscode.

On a side note and probably not one for this issue. I noticed some wierd behaviour in terminal on my windows 10 build with vscode.

**Comment by eyalk5** [comment]
There is a similar issue in VimR . https://github.com/qvacua/vimr/issues/719

The solution in case of VimR was `set termguicolors` in Vim. Maybe it would be somehow helpful.

**Comment by Tyriar** [comment]
OP's issue appears to be solved now so closing.
