### ISSUE TITLE
File Explorer does not Scale Well

### ISSUE THREAD

**Issue by HymanZHAN** [Microsoft/vscode#67801]
Issue Type: <b>Bug</b>

When on a 4k screen, the file explorer (the one that pop up when trying to open a folder) does not follow my system DPI setting and does not scale well. See the screenshot below: left is the file explorer of VSCode and the right one is the system file explorer. You may also see the VSCode UI to get a sense of the scaling issue.

![vscode_file_explorer_dpi_issue](https://user-images.githubusercontent.com/26806995/52172344-84700b80-273b-11e9-9362-9e385d277963.jpg)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.1.6
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.23.0
githistory|don|0.4.6
xml|Dot|2.4.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
gc-excelviewer|Gra|2.1.28
markdown-preview-bitbucket|hbr|1.0.0
angular2-switcher|inf|0.2.0
tera|kar|0.0.2
Angular-BeastCode|Mik|7.2.1
dotenv|mik|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.8.0
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.2
vscode-yaml|red|0.2.1
live-sass|rit|3.0.0
LiveServer|rit|5.3.1
rust|rus|0.5.3
markdown-preview-enhanced|shd|0.3.11
code-spell-checker|str|1.6.10
vim|vsc|1.0.7
vscode-wakatime|Wak|1.2.5
markdown-all-in-one|yzh|2.0.1

(1 theme extensions excluded)

</details>

**Comment by CreeperKong** [comment]
I have the same trouble

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
