### ISSUE TITLE
Git in VSCode shows uncommitted changed to files that are not changed

### ISSUE THREAD

**Issue by EfstathiadisDimitris** [Microsoft/vscode#67808]
I am using the latest version of VSCode. I also use WSL, just in case this is the cause of the problem. I am opening VSCode from WSL, (Ubuntu and WLinux) have the same behavior, and I see just after I cloned my repo, changes to it. Files that haven't changed since forever. Every repo has one or two of those files.

Then I do `git status`, in order to see the uncommitted changes, but nothing. I can do everthing in VSCode and git, but those files keep there and they are growing in number with each commit and push.

When I first opened my main git repo, I had 6 files there. Now after a few commits, I have 9. It keeps my committed changes, there and when I click the diff nothing happens.

**Comment by joaomoreno** [comment]
Can you give me some reproducible steps, so I can reproduce the issue on my side?

**Comment by EfstathiadisDimitris** [comment]
Not really. I can give you the steps I made in order to download VSCode and Git on both Sides(WSL and Windows) but that is about it:

1. Download WSL(Ubuntu and WLinux) set up Ubuntu with this guide [here](https://medium.com/@johnbwoodruff/epic-dev-environment-with-wsl-dc81e234ae61), and the `wlinux-setup` according to WLinux documentation.
2.Set up ssh keys no Windows.
3. Downloaded VSCode on Windows only and Git for both Sides.
4. The cloned my repo with ssh, from GitLab, and just after the clone, I do `code .` in my repo directory and I see 6 changes right of the butt. Every repo I do with ssh is like that. Changes with https are not present.
5. I don't know what else, I can say that will help you.

Also, commit by commit, I see more changes in my left Sidebar, but in the diff, I see nothing. If I do `git status` I see nothing. Hope I helped.

**Comment by joaomoreno** [comment]
Is your repo inside WSL?

**Comment by EfstathiadisDimitris** [comment]
The repos are inside `mnt/c` for Ubuntu, and `c` in WLinux, since WLinux maps it there for some reason. I beleive that is outside WSL. I could be wrong though...

**Comment by joaomoreno** [comment]
What's the output of `git status` when running from WSL and `git status` when running from Windows?

**Comment by EfstathiadisDimitris** [comment]
From WSL nothing, for Windows on the other hand. If I do `git status` I see the changes. If I do `git diff`, I see this changes:


`$ git diff                                                                                                                                                                                                                                                                      warning: LF will be replaced by CRLF in src/lenses/common/angular/components/header/header.html.                                                                                                                                                                                The file will have its original line endings in your working directory                                                                                                                                                                                                          warning: LF will be replaced by CRLF in src/views/common/footer.html.                                                                                                                                                                                                           The file will have its original line endings in your working directory                                                                                                                                                                                                          warning: LF will be replaced by CRLF in src/views/common/layout.html.                                                                                                                                                                                                           The file will have its original line endings in your working directory                                                                                                                                                                                                          warning: LF will be replaced by CRLF in src/views/common/sidebar-panel.html.                                                                                                                                                                                                    The file will have its original line endings in your working directory                                                                                                                                                                                                          warning: LF will be replaced by CRLF in src/views/common/toggle-offscreen.html.                                                                                                                                                                                                 The file will have its original line endings in your working directory                                                                                                                                                                                                          diff --git a/src/assets/icons/avatar.jpg b/src/assets/icons/avatar.jpg                                                                                                                                                                                                          old mode 100755                                                                                                                                                                                                                                                                 new mode 100644                                                                                                                                                                                                                                                                 diff --git a/src/lenses/common/angular/components/header/header.html b/src/lenses/common/angular/components/header/header.html                                                                                                                                                  old mode 100755                                                                                                                                                                                                                                                                 new mode 100644                                                                                                                                                                                                                                                                 diff --git a/src/views/common/footer.html b/src/views/common/footer.html                                                                                                                                                                                                        old mode 100755                                                                                                                                                                                                                                                                 new mode 100644                                                                                                                                                                                                                                                                 diff --git a/src/views/common/layout.html b/src/views/common/layout.html                                                                                                                                                                                                        old mode 100755                                                                                                                                                                                                                                                                 new mode 100644                                                                                                                                                                                                                                                                 diff --git a/src/views/common/sidebar-panel.html b/src/views/common/sidebar-panel.html                                                                                                                                                                                          old mode 100755                                                                                                                                                                                                                                                                 new mode 100644                                                                                                                                                                                                                                                                 diff --git a/src/views/common/toggle-offscreen.html b/src/views/common/toggle-offscreen.html                                                                                                                                                                                    old mode 100755                                                                                                                                                                                                                                                                 new mode 100644                                                                                                                                                                                                                                                                 diff --git a/src/views/connect/connect.controller.js b/src/views/connect/connect.controller.js                                                                                                                                                                                  old mode 100755                                                                                                                                                                                                                                                                 new mode 100644`

It appears to be some end of line inconsistency, but I have set the entire repo to LF instead of CRLF... any thoughts??

**Comment by joaomoreno** [comment]
> I have set the entire repo to LF instead of CRLF...

How have you done this?

**Comment by EfstathiadisDimitris** [comment]
With this command `"files.eol": "\n"` in settings.

**Comment by joaomoreno** [comment]
You should instead configure Git to force the use of a certain EOL, not VS Code: https://help.github.com/articles/dealing-with-line-endings/
