### ISSUE TITLE
openEditors.visible and openEditors.maxVisible

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6781]
#6536

We have two competing/overlapping settings with  "explorer.openEditors.maxVisible" and "explorer.openEditors.visible". I suggest to remove the latter and embrace the already implemented behaviour of `maxVisible = 0`.

**Comment by isidorn** [comment]
Not sure about that. Assigning to @bpasero to get his opinion

**Comment by bpasero** [comment]
I think this is fine as long as we put a proper comment in settings to explain this.

**Comment by isidorn** [comment]
We already have a proper comment in settings
ping @stevencl to also get his opinion

closing for now

![screen shot 2016-05-24 at 15 02 40](https://cloud.githubusercontent.com/assets/1926584/15504713/94565352-21c0-11e6-8fbd-0ac55d68e994.png)

**Comment by bpasero** [comment]
@isidorn I meant it is fine for me to merge both options. we can add it if people are confused.

**Comment by isidorn** [comment]
I have merged the configurations as Joh suggested.
Notice that for maxVisible having a negative value I still show the open editors seciton - not sure if that is the desired behavior or I should just treat that as 0. I want the hide thing to be explicit so the user could not get it hidden by accident.

**Comment by jrieken** [comment]
@isidorn @bpasero Is there a new build for verification?

**Comment by isidorn** [comment]
@jrieken build is just triggered should be out in 20mins
