### ISSUE TITLE
Support for doxy-style /// comments - comment.line.documentation, comment.line.triple-slash

### ISSUE THREAD

**Issue by Yzrsah** [microsoft/vscode#67818]
_Sorry, my issue got closed+locked before because I didn't respond in time, so I am re-posting._

The doxygen style /// comments are great. They can help separate documentation comments from code comments with a distinct visual color and style.

But VSCode theming does not seem to support these these wonderful /// comments -- it is not possible to style them using something like comment.line.triple-slash

It would be excellent if we could support the /// comments and theme them distinctly.

**Comment by Yzrsah** [comment]
> @jrieken 
in what language do you wanna use these comments?

Any language that supports // comments, as the /// comments are also compatible.
I use them in JavaScript, TypeScript, and C++, and a few other languages.

**Comment by mjbvz** [comment]
This can be provided by language extensions that ship a enhanced language grammar
