### ISSUE TITLE
accesing go from windows sub system linux from vs code

### ISSUE THREAD

**Issue by chrisbudi** [microsoft/vscode#67816]
Issue Type: <b>Feature Request</b>

i want to use golang with linux bash as default terminal so i can use some open source project in git 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-go
