### ISSUE TITLE
[Keybindings GUI] Use selection foreground for keys

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#67813]
Issue Type: <b>Feature Request</b>

The color of keys stays the same for selected items, which is not perfect with selected background.
![screenshot 47](https://user-images.githubusercontent.com/9638156/52180385-995da500-27f6-11e9-9d25-393f6eb47ad4.png)

VS Code version: Code - Insiders 1.31.0-insider (8f56013e8f66650c1b0b65cc5c502691e307db21, 2019-02-01T18:34:04.940Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
The focused element is changed, but selected elements are still not using it:

![screenshot 56](https://user-images.githubusercontent.com/9638156/52658240-a02d9b80-2f0b-11e9-8961-c2ad98f64f0f.png)

**Comment by sandy081** [comment]
I do not think Multi-select is needed in keybindings editor.

**Comment by sandy081** [comment]
Supports now all kinds of list foreground colours.
