### ISSUE TITLE
live preview

### ISSUE THREAD

**Issue by sharifulmilan** [Microsoft/vscode#67810]
Issue Type: <b>Bug</b>

live preview is not working . 

VS Code version: Code - Insiders 1.31.0-insider (8f56013e8f66650c1b0b65cc5c502691e307db21, 2019-02-01T18:34:04.940Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.2.7
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.6.3
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
elmmet|nec|1.0.1
open-html-in-browser|pea|1.0.2
material-icon-theme|PKi|3.6.2
vscode-css-peek|pra|2.2.0
LiveServer|rit|5.3.1
vscode-csstree|sme|0.7.0

(2 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@sharifulmilan can you please provide more details about which live preview is not working.
