### ISSUE TITLE
Open recent should report items in order of usage not opening

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#67815]
- Open folder A
- Open folder B
- Close folder B
- From A, open folder C
- From C, see the "Open recent" list

The order is C, B, A
It should be C, A, B

**Comment by Sshirsha** [comment]
Yup, this is happening.

**Comment by sbatten** [comment]
Tested a very old version of code (1.21) to see if this is related to the custom titlebar interference bug we had a while back, but this is the same order shown that long ago. The history service reports in order of opened and not used it seems.
