### ISSUE TITLE
Weird terminal color behaviour

### ISSUE THREAD

**Issue by douglasangeli** [Microsoft/vscode#67824]
Issue Type: <b>Bug</b>

When I open the PowerShell terminal it seems normal, but when I type two or more characters the background color goes pink (default color theme).

If i simply type Enter or single character this behaviour does not occur.

The same occurs on WSL terminal, but doesn't on windows CMD

![vscode](https://user-images.githubusercontent.com/14776862/52184068-c6f61e80-27f5-11e9-984b-00f89507197e.gif)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.95GB (2.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.22.3
flutter|Dar|2.22.3
tslint|eg2|1.0.42
Angular-BeastCode|Mik|7.2.1
material-icon-theme|PKi|3.6.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
