### ISSUE TITLE
[json] emphasize default setting in label

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#67820]
Currently, Visual Studio Code JSON IntelliSense does not highlight (or in any other way emphasize) default values:

![IntelliSense doesn't highlight defaults](https://user-images.githubusercontent.com/9283914/52182923-e182c480-2802-11e9-9dd8-4c5e14fea8cf.png?classes=shadow)
_(`es3` in this example)_

I'd like to suggest to highlight default values, so the programmer is aided in what values will be used when (s)he lints (probably large) configuration files for redundant entries.

**Comment by aeschli** [comment]
We put the label 'default' to the detail attribute of completion item. Unfortunately these are only seen when the entry is selected.

**Comment by aeschli** [comment]
@jrieken Any tips/tricks on how to better emphasize certain items?

**Comment by jrieken** [comment]
@aeschli Sorting? Make it so that es3 goes on top?

**Comment by SetTrend** [comment]
Or adding a `(default)` text to the corresponding value?

![Visual Studio Code IntelliSense suggestion](https://user-images.githubusercontent.com/9283914/52242777-e1082d80-28d7-11e9-9789-79bd3361ce5c.png)

**Comment by aeschli** [comment]
The default value is not the most preferred proposal, so sorting isn't helpful here.
Default is really just additional information here. I guess we can put it in the regular label.
