### ISSUE TITLE
Strange behavior of a right-click mouse when workbench.action.zoomin

### ISSUE THREAD

**Issue by terradek** [Microsoft/vscode#67822]
- VSCode Version:
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-45-generic

- OS Version: Ubuntu 18.04.1 LTS x64 Gnome

**Steps to Reproduce:**
1.Increase a size of the VSCode window clicking _Ctrl+ '='_
2.Right click of the mouse button somewhere on a JS code

PFA video file with the exact VSCode behavior.
[mouse_right_click-2019-02-03_23.39.41.zip](https://github.com/Microsoft/vscode/files/2826036/mouse_right_click-2019-02-03_23.39.41.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@dbaeumer menus is typically Steven

**Comment by sbatten** [comment]
also @joaomoreno  in this case

**Comment by joaomoreno** [comment]
Dupe #65787
