### ISSUE TITLE
Scrolling sluggish when lots of unused code

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#67826]
Issue Type: <b>Bug</b>

@mjbvz I recall a discussion way back when that the desaturation effect for unused code could cause slow scrolling when lots of code is marked unused. At the time we justified this with the idea that not much code should be unused at a given point, as ideally the user would delete it. 

However, in some cases, such as the C/C++ extension, code which is unused due to preprocessor guards is registered as "unused", causing sluggish behaviour in cases where there are large stretches of code hidden behind the ifdef's. 

Is this something that could be fixed on Code's side, or should the C++ extension just avoid marking ifdef'd code as unused?

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Sounds like #67846

@JacksonKearl Can you please test in insiders to see if the update to electron 3 also fixed the issue for you

**Comment by JacksonKearl** [comment]
@mjbvz fixed it!
