### ISSUE TITLE
Configure file association action insert broken rule for default settings file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6782]
- VSCode Version: code-alpha
- OS Version: Linux

Steps to Reproduce:

1. Configure setting
2. Put cursor into 'Default Settings' editor
3. Press on JSON in the status bar and execute 'Configure File Association....'

Observe: a rule like this is inserted:
```json
    "": "json"
```

Either the action should be disabled for the default settings editor or the property should be something like "Default Settings"

**Comment by aeschli** [comment]
We removed the feature that 'Configure File Association' adds a settings string due to the unresolved issues with the configuration open in a dirty editor.
