### ISSUE TITLE
Remove "Experimental setting" from proxy support setting

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#67832]
![http-proxy-support](https://user-images.githubusercontent.com/9205389/52197439-d7db7a00-285f-11e9-8d62-23b349ded915.png)

**Comment by dbaeumer** [comment]
<img width="552" alt="capture" src="https://user-images.githubusercontent.com/1931590/52266930-f4e37c00-2937-11e9-97a0-f9c8c064e007.png">
