### ISSUE TITLE
Allow to define checked badge background

### ISSUE THREAD

**Issue by johnbester** [microsoft/vscode#67830]
After trying to change the look of badges on the left of code (Explorer, Search, Source Control, Debug etc - see attached screenshot below and mock-up below) by going through themes, I found that none of the themes changes the color or background color of these badges. Then I opened developer tools to see what styles were used and it seems to me like the background colors are hard-coded. For example: 

&lt;li class="action-item" ...
&lt;a class="action-label debug" ... style="background-color: rgba(255,255,255,0.6)" .../&gt;
&lt;div class="badge" ...
&lt;div class="badge-content" ... style="color: rgb(255,255,255) background-color: rgb(0,122,204)"

This seems to have the side effect that the checked / selected item can only be grey or white and I often find myself pressing the already selected icon, because there is not a clear distinction between the selected and not selected icons, which hides the complete panel. This is very frustrating. 

I would suggest that the theme should be able to define the "background-color" or maybe event the "color" for both unchecked and checked modes of these badges. This would allow someone developing a theme to have the selected badge stand out more.

![screenshot](https://user-images.githubusercontent.com/6064526/52196262-d7dd7900-2863-11e9-8052-bfbddaeaf89f.png)
![mock-up](https://user-images.githubusercontent.com/6064526/52196583-10318700-2865-11e9-924e-b8d4cf492c15.png)

**Comment by aeschli** [comment]
You can change the foreground color of the activityBar icons with `activityBar.foreground` and `activityBar.inactiveForeground

Badges are actually the counts that are added om top (blue 1 in your screenshot. `badge.foreground` and `badge.background` are for these.

You are asking for something like `activityBar.activeBackground`

**Comment by bpasero** [comment]
I think @misolori is working on this now.

**Comment by misolori** [comment]
See https://github.com/microsoft/vscode/pull/82198 for progress on this, closing this in favor of https://github.com/microsoft/vscode/issues/75435
