### ISSUE TITLE
Configure file associations not inserting value when settings is dirty and value got removed before

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6783]
- VSCode Version: alpha
- OS Version: Linux

Steps to Reproduce:

1. auto save off
2. open JSON file
3. Configure File Association
4. Remove inserted association but don't save
5. redo step 3

Observe: nothing is inserted into the settings file. I know why, but from a user presepctove not expected.

**Comment by dbaeumer** [comment]
Actually that doesn't even work if 3 and 4 are left out.

**Comment by dbaeumer** [comment]
... when the settings.json file is dirty.

**Comment by aeschli** [comment]
We removed the feature that 'Configure File Association' adds a settings string due to the unresolved issues with the configuration open in a dirty editor.
