### ISSUE TITLE
Eating up 100% CPU and too much of RAM

### ISSUE THREAD

**Issue by aatman-bhatt** [Microsoft/vscode#67836]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Just open the VSCode, and let it freeze your system, woring with Core i5 and 16Gigs of RAM, still it shows lags and freezes completely even copy and paste stops working :( :( :(

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    72	  9952	code main
    0	    63	  6332	   shared-process
    0	   148	 11812	   gpu-process
    0	    69	 12176	   window (Issue Reporter)
    0	   368	 13588	   window (account-address-single-popup.component.html - v3 - Visual Studio Code)
    0	   563	  8464	     extensionHost
    0	    49	  6428	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=8464
    0	    22	 10340	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=8464
   23	   814	 11796	       electron_node server.js 
    0	    43	 12076	       electron_node server.js 
    0	    41	 12172	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=8464
   14	   121	 13128	       electron_node tslintServer.js 
    1	    27	  9144	         "C:\Program Files\Microsoft VS Code\Code.exe" -e console.log(require.resolve('tslint'));
    0	   628	 14048	       electron_node tsserver.js 
    0	    17	   824	         electron_node typingsInstaller.js typesMap.js 
    0	    34	 11732	     searchService
    0	    12	 12868	     watcherService 
    0	     5	 11472	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (account-address-single-popup.component.html - v3 - Visual Studio Code)
|    Folder (v3): more than 20859 files
|      File types: sql(6427) class(3842) java(3127) ts(2162) xml(2015)
|                  feature(542) prefs(496) scss(434) html(390)
|                  properties(276)
|      Conf files: sln(2) package.json(2) launch.json(1) csproj(1)
|                  tsconfig.json(1) tslint.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
html-snippets|abu|0.2.1
Bookmarks|ale|10.2.2
ng-template|Ang|0.1.11
angulardoc-vscode|Ang|6.1.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|1.16.0
gitlens|eam|9.4.1
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
json2ts|Gre|0.0.6
angular2-switcher|inf|0.2.0
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
theme-karyfoundation-themes|kar|18.2.1
angular-extension-pack|loi|0.6.0
Angular2Tests|Mar|0.7.3
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
ng-fortytwo-vscode-extension|NG-|0.0.9
material-icon-theme|PKi|3.6.2
typescript-hero|rbb|3.0.0
copy-copy-paste|roc|0.0.6
angular-follow-selector|san|1.2.0
autoimport|ste|1.5.3
move-ts|str|1.11.3
Angular2|UVB|0.4.1
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>
****

**Comment by dbaeumer** [comment]
@aatman-bhatt from the process info this looks like a problem with one of your extensions. Can you please start with all extensions disabled (--disable-extensions) to see if it disappears. If yes, try to find the extension that causes the problem and report the issue there. This https://github.com/Microsoft/vscode/wiki/Performance-Issues might be helpful as well.
