### ISSUE TITLE
Handling a clicable URL with a full stop

### ISSUE THREAD

**Issue by yaruson** [Microsoft/vscode#67840]
Issue Type: <b>Bug</b>

## Steps to Reproduce

1. Open built-in terminal
1. Execute `echo Click this link: http://example.com. See what you get`
1. Move mouse pointer above the link

## Actual result

The full stop at the end of the URL is underlined `http://example.com.`

## Expected result

Only the part of the link before the full stop is treated as URL.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2190)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.44GB (0.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/21125
