### ISSUE TITLE
Show number of matching occurrences

### ISSUE THREAD

**Issue by Stadly** [microsoft/vscode#67841]
Issue Type: <b>Feature Request</b>

When selecting some text, all matching occurrences are highlighted. The matches can be fine-tuned using for example `Alt+W` (Match Whole Word) and `Alt+C` (Match Case), but I can't see the number of matching occurrences anywhere.

The number of matching occurrences would be particularly useful to know when using `Ctrl+F2` to change all the occurrences.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Stadly** [comment]
This is not covered by those issues.

**Comment by rdhar** [comment]
Mentioning @ramonbakker-rambit's [Highlight counter](https://marketplace.visualstudio.com/items?itemName=rambit.highlight-counter) extension which is a must-have for anyone, until this feature request is implemented.
