### ISSUE TITLE
`<` and `>` are not matched in TypeScript

### ISSUE THREAD

**Issue by ajafff** [microsoft/vscode#67847]
- VSCode Version: 1.30.2
- OS Version: macOS mojave

Steps to Reproduce:

1. Set `editor.matchBrackets: true`
2. Open a TypeScript file with the following content:

```ts
type T = Readonly<Record<string, string>>;
```

Placing the cursor on any of the angle brackets doesn't highlight the corresponding bracket.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ajafff** [comment]
Seems like this was removed in https://github.com/Microsoft/vscode/commit/c5251468766314f6ed634303adc3a765cf621966 to "fix" an issue with false-positives.

**Comment by ajafff** [comment]
At least for JavaScript and TypeScript there is a LanguageServer command `brace` that returns the matching brace. This avoids false positives with arrow functions and binary operators.

**Comment by SuperV1234** [comment]
+1, this is super useful for C++ templates as well.

**Comment by alexandrudima** [comment]
This cannot be supported from the core bracket-matching functionality due to the overload of the characters `<` and `>`, which are used both in the context of generics and in the context of comparisons. 

The core editor functionality uses some tokenization information to skip over strings and comments when matching brackets, but we don't have anything that would help with disambiguating comparisons/generics.

**Comment by SuperV1234** [comment]
I guess this issue is to request support to be added to the core editor which would help with disambiguating comparisons and generics. Is this something you're not interested in?

**Comment by alexandrudima** [comment]
The core bracket-matching functionality is programming language agnostic and does not have an AST for TypeScript at hand. The only smartness the core bracket matching logic has is that it will skip over tokens that are comments, regular expressions or strings and not look inside that text for matching brackets. IMHO there is nothing short of building an AST for TS to get correct disambiguation in the case of `<`, `>`.

Also, the highlighting of `<` and `>` in generics could be implemented by an extension (which can be TS specific) by creating text editor decorations.
