### ISSUE TITLE
Integrated terminal cursor is in the wrong position after resize

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6784]
Testing #6654

![terminal-resize-cursor](https://cloud.githubusercontent.com/assets/5047891/15503889/8ea06f78-21bc-11e6-87ed-b82ec2435930.gif)

**Comment by Tyriar** [comment]
Upstream issue after xterm switch: https://github.com/sourcelair/xterm.js/issues/103

**Comment by Tyriar** [comment]
I believe this has been fixed, cannot repro on Windows or Linux.
