### ISSUE TITLE
Filtering for new files requires folder refresh

### ISSUE THREAD

**Issue by potatoqualitee** [Microsoft/vscode#67845]
- VSCode Version: See below
- OS Version: See below

![image](https://user-images.githubusercontent.com/8278033/52197069-82529d80-285e-11e9-9851-6ef5b7e1cf7c.png)

Related: https://github.com/Microsoft/vscode/issues/66971

Steps to Reproduce:

1. Expand a folder in VS Code
2. Create a new file outside of VS Code (like a copy and paste into a repo) into that folder
3. Use the new filtering
4. Does not find the new file until you close the folder then open it again

Does this issue occur when all extensions are disabled?: my terminal reported code not found

I saw in another issue that there may be workarounds but I'm hoping that the default filter behavior is to refresh in the same way that VS Code refreshes when I change my git workspace.

**Comment by joaomoreno** [comment]
After step (2), does the file appear in the tree?
