### ISSUE TITLE
Unresponsive editor in SCSS

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#67858]
Issue Type: <b>Bug</b>

Continuation of #61138

Editor becomes unresponsive in SCSS.
After a while of eating battery and my laptop becoming a forced air heater, the editor _may_ become unstuck and I _may_ be able to resume working.

* I _don't know_ how the reproduce this problem. Just make it never unresponsive, I guess?
* I _don't know_ what causes this problem, because by the time I found out how to diagnose it, the problem had dissappeared.
* I _do know_ the problem will return at some magically random point, if history told me anything.
* I _do know_ the problem can occur without extensions, but again, difficult to reproduce.
* I _did not_ see a notification, as mentioned in #61138 near the end of the conversation.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (15.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.2.2
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.8
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.8
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.4
vscode-svg-previewer|vit|0.3.1

</details>

**Comment by kieferrm** [comment]
Sorry to hear about your troubles but there is nothing in here we can react to.  Next time it happens, pls run `code --status` from a terminal. This at least will tell us which of the processes is consuming the CPU. 

One thing that sticks out is that you use the Auto Close Tag extension. This one has been causing the same symptoms you describe in numerous situations but not for SCCS files: https://github.com/formulahendry/vscode-auto-close-tag/issues?utf8=✓&q=is%3Aissue+is%3Aopen+Extension+causes+high+cpu+load

**Comment by thany** [comment]
The Auto Close Tag has no effect on this problem, as it appears. I've disabled it at one point, and it would still freeze the editor. Maybe it interferes even when disabled, or I'm horribly mistaken, both of which I cannot vouch for :)

More importantly, I did not get a notification. One of the improvements in the last or pre-last update was a notification when an extension is making Code slow, so if nothing else, that notification doesn't work properly.

So before diving in, one question I'd like clarification on is: *should I have gotten a notification?*

I'll update with status information if (when) this issue resurfaces.

**Comment by aeschli** [comment]
There's no guarantee of a notification. There many ways of slowing down the extension host. 
Please try to run without extensions to verify that this is caused by extensions.

`html-class-suggestions`may cause this by loading too many files in parallel.

**Comment by thany** [comment]
Finally caught a status while the editor was frozen for a good couple of seconds.

```
Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS Version:       Windows_NT x64 10.0.17763
CPUs:             Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)
Memory (System):  31.74GB (12.90GB free)
VM:               67%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       71   11616  code main
    0      245   15568     window (_gallery.scss - Landal - Visual Studio Code)
   14      505    5860       extensionHost
    0       27   10420         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=5860
    0       28   13576         electron_node eslintServer.js
    0       69   18608         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=5860
    0      154   20128         electron_node tsserver.js
    0       39   13548           electron_node typingsInstaller.js typesMap.js
    0       42   22180         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=5860
    0       87    6040       searchService
    0       16   18576       watcherService
    0        8   18812         console-window-host (Windows internal process)
    0       52   15620     shared-process
    0     1032   17784     gpu-process

Workspace Stats:
|  Window (_gallery.scss - Landal - Visual Studio Code)
|    Folder (Landal): more than 20982 files
|      File types: dll(6297) cs(3747) xml(3621) config(1502) pdb(1420) _(991)
|                  txt(495) cache(284) nupkg(245) gif(198)
|      Conf files: csproj(115) package.json(14) sln(6) grunt.js(5) gulp.js(4)
|                  tsconfig.json(1) webpack.config.js(1)
```

Hopefully this helps.

I'm on a hexacore CPU, so those 14% is actually blowing one whole core.

**Comment by aeschli** [comment]
Ok, great. Now we know it's not json, html or css, but some extension.
Please run `Developer: Show running extensions`. In that view's toolbar there's an action to start profiling.
When pressing 'Stop' again (also available in the status bar) you can see detailed information which extension was active and has potentially consumed the time.

**Comment by thany** [comment]
It never freezes long enough for me to do that. And I also prefer not to leave the profiler running all the time, since this issue pops up only once in a while.

On top of that, after stopping the profiler, I don't get to see its results, like I do when I profile javascript in a browser...

**Comment by thany** [comment]
It doesn't (anymore) freeze long enough for me to do that, as I just found out. And I also prefer not to leave the profiler running all the time, since this issue pops up only once in a while.

Also after stopping the profiler, I'm not sure where to get its results, but that'll be a different issue.

I would also be happy if the automatic slow/freezing extension notification feature would start working in this case, because even now, with version 1.32.1, it doesn't.
