### ISSUE TITLE
git repository as external in svn is misinterpreted as main repo

### ISSUE THREAD

**Issue by ygrange** [Microsoft/vscode#67853]
Issue Type: <b>Bug</b>

We have an svn repository in which a colleague has put a git repository as an external. If I open the direcotry of this svn repo, VSCode gives me all information on the git repo but I don't seem to have access to the svn repo it's part of. 
Expected behaviour is that the main repository is shown as an svn repo, and not the git repo that is managing one of the subdirectories.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_680102|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ygrange** [comment]
Oh wait. It is a bit more complex. My directory structure looks something like:
${HOME}/work/root_of_repo/branch_1/gitrepo
${HOME}/work/root_of_repo/branch_2/gitrepo
${HOME}/work/root_of_repo/branch_3/gitrepo
(where the branches all are different svn branches and gitrepo is the external).
Now if I open directory ${HOME}/work/root_of_repo in vscode, it will give me some git information that applies to gitrepo
If I open ${HOME}/work/root_of_repo/branch_1 it sees it as an svn repo

**Comment by joaomoreno** [comment]
Do you have the SVN extension installed? If so, you should send them the issue, not VS Code.
