### ISSUE TITLE
Tasks always adds -e for wsl.exe, but should be Windows build dependent.

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#67855]
See #63741.
Turns out that wsl.exe used to wrap bash.exe, and in more recent builds the command line argument options changed.

**Comment by alexr00** [comment]
You'll need to have multiple versions of Windows to really verify this. Since the behavior shouldn't have changed for the latest regular Windows release just making sure that it still works there should be good. Set:
`	"terminal.integrated.shell.windows": "wsl.exe",`

And try to run this task:
````json
		{
			"type": "shell",
			"command": "echo hello",
			"label": "My Task",
			"problemMatcher": []
		}
````
Verify that the task executes and you can see hello get echoed.

**Comment by davidwin** [comment]
I can add that on Windows 10 16299, the verification as described above fails. If I set `"terminal.integrated.shell.windows": "wsl.exe"`, Code tries to launch 
`wsl.exe -c "echo hello"` 
, which fails with error
`/bin/bash: - : invalid option`. 

Specifying `wsl.exe` as the shell in the tasks.json file results in Code trying to launch 
`wsl.exe "echo hello"`
, which fails with error
`/bin/bash: echo hello: command not found`

A recent Windows version works as expected in both cases.
