### ISSUE TITLE
Failed to install VS COde update

### ISSUE THREAD

**Issue by UTexas80** [Microsoft/vscode#67869]
Failed to install VS Code update: I think it has something to do with a Workspace that I tried to replace: Here are the log files from when the issue started to persist.

[vscode-inno-updater-1548708156.log](https://github.com/Microsoft/vscode/files/2828777/vscode-inno-updater-1548708156.log)
[vscode-inno-updater-1548792889.log](https://github.com/Microsoft/vscode/files/2828778/vscode-inno-updater-1548792889.log)
[vscode-inno-updater-1548959051.log](https://github.com/Microsoft/vscode/files/2828779/vscode-inno-updater-1548959051.log)
[vscode-inno-updater-1548962054.log](https://github.com/Microsoft/vscode/files/2828780/vscode-inno-updater-1548962054.log)
[vscode-inno-updater-1549054296.log](https://github.com/Microsoft/vscode/files/2828781/vscode-inno-updater-1549054296.log)
[vscode-inno-updater-1549293533.log](https://github.com/Microsoft/vscode/files/2828782/vscode-inno-updater-1549293533.log)
[vscode-inno-updater-1549296172.log](https://github.com/Microsoft/vscode/files/2828783/vscode-inno-updater-1549296172.log)

**Comment by KexyBiscuit** [comment]
Did you try to restart Windows?
