### ISSUE TITLE
I can recursively peek definitions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#6786]
Testing #6662

Recursively peeking definitions ends in this state:

![image](https://cloud.githubusercontent.com/assets/22350/15504256/689ea630-21be-11e6-82f7-4afb8f934690.png)

After the first peek, the trees in the following peeks are always empty.

Is this expected?

**Comment by jrieken** [comment]
> Is this expected?

It's cool but it should not be like that ;-)

**Comment by stevencl** [comment]
It would be great to be able to cascade peek definition (and references). Visual Studio supports cascading peek and shows a breadcrumb above the peek window to indicate how deep you have gone:
![peek](https://cloud.githubusercontent.com/assets/1704059/15505464/9484b59e-21bb-11e6-8acc-e9c57b18b51f.png)

**Comment by kieferrm** [comment]
Recursive peeking is useful in a lot of situations. However, I'd expect it to reuse the existing window and on ESC or close box to take down only the most topmost one.

**Comment by jrieken** [comment]
That's in line with @stevencl suggestion. I have created a separate issue for this: https://github.com/Microsoft/vscode/issues/6857
