### ISSUE TITLE
File Encoding for markdown

### ISSUE THREAD

**Issue by atilkan** [Microsoft/vscode#67866]
- VSCode Version: 1.30.2
- OS Version: Mac Majove

Steps to Reproduce:

1. Create md file inside editor
2. Save
3. Check encoding

If my setting is below; file encoding will be **us-ascii** 
(This is default)
`"[markdown]": {
    "files.encoding": "utf8"
  }`

But if setting is below; file encoding will be **utf-8**.
`"[markdown]": {
    "files.encoding": "utf8bom"
  }`

Same thing also doesn't work if i use editor's command palette.

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
