### ISSUE TITLE
Need tree collapse/expand events

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67864]
re #64727

The breadcrumb picker resizes based on the the number of visible items, e.g. it starts small when only having one folder but relayouts when expanding that. I didn't find events that correspond to `onDidExpandItem` and `onDidCollapseItem` and I would need them in both data tree (sync/async)

**Comment by joaomoreno** [comment]
Got these ones instead:

https://github.com/Microsoft/vscode/blob/9deb608cc6c152d091484aebd9efcbbb35206f73/src/vs/base/browser/ui/tree/asyncDataTree.ts#L348

For height in pixels:

https://github.com/Microsoft/vscode/blob/9deb608cc6c152d091484aebd9efcbbb35206f73/src/vs/base/browser/ui/tree/asyncDataTree.ts#L344

For height in number of rows:

https://github.com/Microsoft/vscode/blob/9deb608cc6c152d091484aebd9efcbbb35206f73/src/vs/base/browser/ui/tree/asyncDataTree.ts#L570
