### ISSUE TITLE
Freezing when opening HTML File

### ISSUE THREAD

**Issue by casey-spires** [Microsoft/vscode#67868]
When working on or sometimes opening and HTML file, VSCode just hangs as if the file were in some kind of limbo. It refuses to save the file and in fact when i try to run 'ng serve', this is an angular cli project, it will hang on that specific file when building the project for the development server. The problem even occurs when all extensions are disabled. Any advice on how to hunt down what is going on?

**Comment by kieferrm** [comment]
Instructions for performance issues are here: https://github.com/Microsoft/vscode/wiki/Performance-Issues. It would also help if you add information about platform, VS Code version, installed extensions, etc.
