### ISSUE TITLE
unable to create new file using the explorer icon and right click and new file.

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#67860]
Unable to create new file after the latest update visual studio code insiders.
it does not work for right for clicking the new file icon in explorer as well as right click and selecting new file.

**Comment by usernamehw** [comment]
/confirm not possible to create file/folder in root folder.

**Comment by bpasero** [comment]
@sanket-bhalerao thanks for the fast bug report, we literally broke this a few hours ago

**Comment by sanket-bhalerao** [comment]
@bpasero thanks for fixing it quickly :)

**Comment by bpasero** [comment]
@joaomoreno is the man of the hour

**Comment by sanket-bhalerao** [comment]
all hail @joaomoreno 🥇

**Comment by joaomoreno** [comment]
**Verification**:

1. Right click on empty explorer space, `New File`

Should work.
