### ISSUE TITLE
Markdown preview stops Ctrl+` from toggling terminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67879]
Issue Type: <b>Bug</b>

![webview](https://user-images.githubusercontent.com/4033249/52227883-a9609d80-2865-11e9-82e4-ffcfb70922fb.gif)

Repro:

- Open Markown preview
- <kbd>Ctrl</kbd> + <kbd>`</kbd> for a few times

VS Code version: Code - Insiders 1.31.0-insider (5ab047b584d974033e0c5ce529ea74a869355b87, 2019-02-04T15:24:24.455Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.05GB free)|
|Process Argv|-psn_0_1364301|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
I can repro, the panel flickers for me sometimes. I don't think this meets the bar for 1.31 though as there's many workarounds (run command, focus an editor, etc.) and only happens sometimes.
