### ISSUE TITLE
Leaving backup/temp file behind on save intermittently

### ISSUE THREAD

**Issue by keathmilligan** [Microsoft/vscode#67870]
Issue Type: <b>Bug</b>

Save a modified file (I see this with Python files, not sure if it affects other file types or not).

When saving a file, a duplicate file with same name with a guid appended to it will sometimes get left behind in the same directory. For example:

![image](https://user-images.githubusercontent.com/2936304/52222125-5cca9180-2868-11e9-819a-5d0270144e4d.png)

The file has to be deleted manually.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.89GB (46.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-apache|mrm|1.2.0
python|ms-|2019.1.0
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.1
vscode-icons|rob|8.1.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Does it happen when you disable your extensions? I.e. `code --  --disable-extensions`.  I'd suspect that this is caused by the python extension.
