### ISSUE TITLE
[html] Error when using handlebars in style attribute

### ISSUE THREAD

**Issue by tomires** [microsoft/vscode#67871]
- VSCode Version: 1.30.2
- OS Version: Linux x64 4.15.0-43-generic

Using handlebars in style attribute causes VS Code to report an error.

Steps to Reproduce:
1. Create a new HTML file
2. Paste the following snippet:
`<input type="text" name="user_name" placeholder="Enter user name" class="textbox_with_icon" style="background-image: url({{ url_for('static', filename='images/icon_user_gray.svg') }});">`
3. VS Code now shows an error

![image](https://user-images.githubusercontent.com/7209990/52223150-54447c00-28a5-11e9-9415-b4c7bf00b1e8.png)

Does this issue occur when all extensions are disabled?: Yes

I believe it is the same issue as https://github.com/Microsoft/vscode/issues/53314 , however that issue has been closed due to apparent lack of reproducibility (however the original snippet does too throw an error on my setup).

**Comment by ntotten** [comment]
I would propose that some sort of setting be added to the language server that allows identifying template characters. For example, if we could specify template characters similar to how we specify folding characters in a custom language - although in this case its not applying to a custom language, but rather to a set of HTML files - we could simply tell the HTML language server (and sub-languages for JS and CSS) to not validate those strings.

This is a simplification but if we could provide something like this to tell the language server which files this applies to and what the templating patterns are, this would allow eliminating these errors.

```
  "templating": {
    "paths": [
       "**/lwc/*.html"
    ],
    "matches": [
        "(\"|'|=){#(.+)}",
        "(\"|'|=){{(.+)}}"
     ]
  }
```

There is certainly more we could do in terms of extending the HTML language server to provide code completion and validation for these types of templates, but I think this is a good-enough solution to start.

**Comment by aeschli** [comment]
#49210 is the issue to make the HTML support either configurable to it knows about template languages, or make it easy to create a template language server by parameterizing the  HTML language support.
