### ISSUE TITLE
Integrated Terminal wrong output with powershell

### ISSUE THREAD

**Issue by symant233** [Microsoft/vscode#67873]
- VSCode Version: 1.30.2 (user setup)
- OS Version: Windows10 Home 1809 (Windows_NT x64 10.0.17763)
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41

**This will happen every time I launch a new integrated terminal (with powershell).**
![image](https://user-images.githubusercontent.com/25316350/52223437-95a64d00-28e0-11e9-9696-c6a6673a77f1.png)
Then I expand it:
![image](https://user-images.githubusercontent.com/25316350/52223581-e7e76e00-28e0-11e9-9ec4-940ceebb0b84.png)
Unexpand the terminal goes back to first picture. Then I press enter that will be ok.
![image](https://user-images.githubusercontent.com/25316350/52223738-401e7000-28e1-11e9-8136-9ce4b41d3f6d.png)

Why I emphasis the powershell? Because when I set the wsl terminal in default works fine.
This problem happen when I install the VSCODE (first install). I even didn't edit the settings file...
I search on the internet for solution and I found one works but not good for me.
![image](https://user-images.githubusercontent.com/25316350/52224072-1285f680-28e2-11e9-8412-40aa28adb416.png)
Enable this will solve the problem. BUT this make my windows terminal very hard to use.
I'm spending half a day solve this but there is no other way to solve the problem.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by symant233** [comment]
In additional, when I use Code Runner the first line of current PATH will not show like this:
![image](https://user-images.githubusercontent.com/25316350/52224435-f9ca1080-28e2-11e9-999e-8ee54713fb5d.png)

**Comment by symant233** [comment]
@Tyriar I found you got the same problem in #57803. Any solution yet?

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803

**Comment by Tyriar** [comment]
@symant233 unfortunately the solution is to wait for the first 2019 Windows update
