### ISSUE TITLE
Add Tree#resort

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67876]
re #64727

There is `refilter` but when no `resort`. My challenge is that the sort order of outline/breadcrumb items is user-defined and when that changes I need to resort the tree.

**Comment by joaomoreno** [comment]
Yeah we definitely need this.

**Comment by jrieken** [comment]
currently working around this with `updateChildren`

**Comment by joaomoreno** [comment]
@jrieken: https://github.com/Microsoft/vscode/commit/4eda5af1471409971e3884da1d31abfd90d9b78d

**Comment by joaomoreno** [comment]
Verification: please code review.
