### ISSUE TITLE
Sidebar view doesn't show subdiretory of a exluded dir in files.exclude

### ISSUE THREAD

**Issue by LC43** [microsoft/vscode#67884]
Issue Type: <b>Bug</b>

hi,
no matter what combination i try, i can't show a a specific subdiretory of a excluded dir.

I mean, it can show, but its either all subdirs, or none.

Example:
The excluded dirs are set in user settings:
```
    "files.exclude": {
        "**/.DS_Store": true,
        "**/.git": true,
        "**/.svn": true,
        "**/node_modules": true
    },
```
then, on this particular workspace:

```
	"files.exclude": {
		"**/node_modules": false,
		"**/node_modules/*": true,
		"**/node_modules/moduleA": false
	},
```

In this combination, the dir `node_modules` shows up, but is empty ( as in the attached screenshot ).
![screenshot_2019-02-04_19-28-23](https://user-images.githubusercontent.com/48201/52232451-785b8980-28b4-11e9-9f38-7c3f147b0830.png)

Same for swapping the subdirs:

```
		"**/node_modules/moduleA": false,
		"**/node_modules/*": true
```

If i remove `"**/node_modules/*": true`, the full list of modules are shown.

Tried using `"**/node_modules/**": true`, `"**/node_modules": true`, `"**/node_modules/.*": true`,with and without the prefix "**/" ...

Any suggestions on how to get around this?

VS Code version: Code - OSS 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T22:23:23.072Z)
OS version: Linux x64 4.19.4-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 1340)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.34GB (4.37GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
Handlebars|and|0.4.1
path-intellisense|chr|1.4.2
gitlens|eam|9.4.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
phpcs|ika|1.0.5
vscode-scss|mrm|0.6.2
php-docblocker|nei|1.7.0
code-settings-sync|Sha|3.2.4
guides|spy|0.9.3
php-phan|Tys|0.8.3
gitblame|wad|2.6.3
wordpress-toolbox|wor|1.3.0
markdown-all-in-one|yzh|2.0.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
It is currently not possible to override the exclude of a specific folder, we simply do not merge these patterns.

**Comment by LC43** [comment]
ok, thanks @bpasero, looking forward to see this happening :)

just a note: **it is** _possible to override the exclude a specific directory_ :
on the main config has `"**/node_modules": true`, and the workspace config `"**/node_modules": false`. 

What's missing is being able to include a specific subdirectory from a excluded directory. sorry if i misunderstood your comment.
