### ISSUE TITLE
Project scope definition lookup

### ISSUE THREAD

**Issue by Somebi** [Microsoft/vscode#67886]
Issue Type: <b>Feature Request</b>

Search methods definitions through whole project. Currently it can't find where method is defined.
Sublime editor is able to find where it is defined.
It is offering found matched and provide an option to choose one of found matches from dropdown menu with filtering input in the dropdown menu to shrink results to exatly what you want.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

**Comment by kieferrm** [comment]
@Somebi please provide a description that helps us understanding your proposal/issues. Right now, we don't event know which programming language you are working with, how you try to get the method definitions etc.

**Comment by Somebi** [comment]
I'm using javascript and node.js without typescript. Using simple require and partial classes are written with old %Class%.prototype.%method% = function() {} syntax.
What else is required?

**Comment by Somebi** [comment]
The thing is, that Sublime editor is able to find definition. Maybe peek on their implementation? :)

**Comment by Somebi** [comment]
It's working in single file scope, but when class or object is required from a different file it is saying that this definition is not found.

**Comment by Somebi** [comment]
It's interesting, it's actually working, but not always. But there is definitely a bug somewhere in that feature. I'll try to catch that situation to reproduce.

**Comment by Somebi** [comment]
Aha! So when some class instance is provided as arguments in a constructor, then saved in the class as a property and that class instance is a collection of other class instances, then it can't figure out what that instance is and says that there is no definition found. It seems it is only working with definitions that are available or defined in the current file scope. For instance if imported class was used in current file.

**Comment by mjbvz** [comment]
@Somebi Can you please share some example code so we can investigate this

**Comment by Somebi** [comment]
Sorry can't, i'm under NDA. You can try playing with requiring classes.
Here are some tips:
- do every step in a separate file
- make class
- make collection of those classes
- make class, that will accept that collection in a constructor
- require() all these files into one final file
- now try to press F12 on some method from any instance from collection inside final file
- it should fail to locate definition of that method

**Comment by Somebi** [comment]
Don't have time to reproduce, sorry. But play around in that direction and you will definitely spot that issue.
Maybe later i'll create an example myself on a free time.

**Comment by Somebi** [comment]
I have discovered a basic issue. I'm using node.js and there is old implementation which is using util.inherits(Class1, Class2); and in constructor of Class1 there is Class2.apply(this, arguments);

This way it can't find definitions and methods of Class1.

You can try it yourself.

**Comment by mjbvz** [comment]
Thanks.

We don't even support normal es5 style class inheritance today: https://github.com/Microsoft/TypeScript/issues/13206

Making our intellisense understand that `util.inherits` is similar to of `extends` is out of scope. It would be a lot of work for relatively little payoff.
