### ISSUE TITLE
No feedback when dragging views in explorer

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67880]
- Theme: Monokai
- Drag views in explorer to rearrange
- See that the view titles are not highlighted when dragging, I think they used to be. This gives the user some hint as to where views are being dragged to

**Comment by joaomoreno** [comment]
They are not highlighted in stable, only the body contents. Do you confirm?

**Comment by joaomoreno** [comment]
There was definitely a problem in the light theme... there was absolutely no drag feedback.

@sandy081 Maybe you forgot to test light themes when adding theme colors to this? https://github.com/Microsoft/vscode/commit/c09cab276266ac4cff090418bb5f1d256fc30a2b

**Comment by joaomoreno** [comment]
Closing for now. Some themes force header background colors, not much I can do there.

**Comment by sandy081** [comment]
@joaomoreno Looks like 😕
