### ISSUE TITLE
Not possible to reopen closed editor if editor fails to open

### ISSUE THREAD

**Issue by Somebi** [Microsoft/vscode#67882]
Issue Type: <b>Bug</b>

I'm talking about "Ctrl + Shift + T" feature, which re-opens closed files.

When file is deleted and it was in opened files history. It's impossible to re-open files below that file. It stops exactly on that deleted file and always throw an error "File not found".

It should just skip that file and proceed to the next file in history. Possibly deleted file should be removed from history, to avoid that error re-appearing.

But anyway, it should allow to open files below that point.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 3094)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 1, 1|
|Memory (System)|7.75GB (0.49GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
vscode-eslint|dba|1.8.0
bettercomment|Gru|0.0.8
beautify|Hoo|1.4.8
terraform|mau|1.3.7
debugger-for-chrome|msj|4.11.1
go-to-method|tri|0.1.1
disable-eslint-rule|Woo|0.0.2

</details>

**Comment by bpasero** [comment]
New strategy is to try the next recently closed editor if the current one fails.

**Comment by Somebi** [comment]
Good, ty.
