### ISSUE TITLE
Code Snippets for C++ does not preview after I press Ctrl+space | Visual Studio Code

### ISSUE THREAD

**Issue by gauravlohia** [Microsoft/vscode#67889]
Issue Type: <b>Bug</b>

I enter 'class' and it  intelliSense shows the suggestions for code snippets but if I want more info and I click on the 'i' icon or press Ctrl+Space, it wont the preview for the code snippet. Please help.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2994)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-yaml|red|0.2.1

</details>

**Comment by kieferrm** [comment]
The VS Code API allows extensions to contribute what should be shown in the details view when a completion item is selected. Please file the issue against the C++ extension (or the extension that contributed the snippets).
