### ISSUE TITLE
Restart TS Server cmd no longer shows up

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#67892]
Issue Type: <b>Bug</b>

The "restart ts server" cmd no longer shows up in the cmd palette.  The is very frustrating, because after switching package version, I often have errors in my project because the ts-server doesn't pick up the new packages.  I have to reload the project to resolve them, which means I have to restart the web-pack-dev server task that I have running in the integrated terminal.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
mavensmate|Dav|0.15.0
apex-autocomplete|chu|0.2.13
apex-debug|chu|1.0.3
apex-pmd|chu|0.2.2
language-postcss|cpy|1.0.5
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
xml|Dot|2.4.0
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
auto-close-tag|for|0.5.6
vscode-react-typescript|inf|1.0.17
TypeScriptImport|kev|1.17.0
vscode-mocha-sidebar|mat|0.20.22
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
antlr4|nct|0.0.1
typescript-hero|rbb|3.0.0
vscode-icons|rob|8.1.0
salesforcedx-vscode|sal|44.18.0
salesforcedx-vscode-apex|sal|44.18.0
salesforcedx-vscode-core|sal|44.18.0
salesforcedx-vscode-visualforce|sal|44.18.0
stylelint|shi|0.48.0
Align|ste|0.2.0
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.10
markdown-all-in-one|yzh|2.0.1

</details>

<img width="636" alt="loadaction_ts_ _quote-tool-v2" src="https://user-images.githubusercontent.com/5217568/52238742-0706e100-288a-11e9-9d4b-10f99247a613.png">

**Comment by mjbvz** [comment]
Are you in a on disk JS/TS file or a remote one (such as from liveshare)?

**Comment by ChuckJonas** [comment]
@mjbvz on disk.  I've tried multiple different files & projects... Weird thing is if I run the command AS SOON as I open the project it shows up.  I think it may be an extension conflict

**Comment by ChuckJonas** [comment]
Confirmed that reloading with extensions disabled and it now shows up
