### ISSUE TITLE
Layout flicker when toggle sidebar with debug console visible

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67896]
- Show the debug console
- Toggle the sidebar
- See brief layout flicker

![feb-04-2019 15-14-12](https://user-images.githubusercontent.com/323878/52243855-de81e580-288f-11e9-8443-f738ccc4a31b.gif)

**Comment by bpasero** [comment]
@roblourens I cannot reproduce. are you possibly running with `"workbench.useExperimentalGridLayout": true`?

**Comment by roblourens** [comment]
Nope

**Comment by bpasero** [comment]
@roblourens can you reproduce from a fresh run (empty `--user-data-dir`)?

**Comment by roblourens** [comment]
No...

**Comment by bpasero** [comment]
Ok thanks for having reproducible steps.

**Comment by bpasero** [comment]
@roblourens actually does it reproduce with the new grid enabled? because we will likely make that the default soon.

/cc @sbatten

**Comment by roblourens** [comment]
Ah no it doesn't. Nice work @sbatten
