### ISSUE TITLE
It would be great to be able to change the color / opacity of the hover state in the integrated terminal

### ISSUE THREAD

**Issue by darudude** [Microsoft/vscode#67893]
Currently there is a mild opacity / color change when you hover over a line in the integrated terminal. That's nice when dealing with multi-line outputs as it helps me see the block that was outputted together. 

However, I don't believe that hover opacity / color is configurable (atleast it doesn't seem to be listed in: https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors). I would love to be able to modify it to make it more apparent.

**Comment by Tyriar** [comment]
@darudude can you take a screenshot of what you mean by hover state?

**Comment by darudude** [comment]
Sure - here you go. 
![hover-terminal](https://user-images.githubusercontent.com/7749565/52278527-3d456e80-2925-11e9-9600-cfaa88d9a038.png)

I'm hovered over line wiht the slightly greyer background. Would love to make that grey more prominent or change the hover color altogether

**Comment by isidorn** [comment]
This is already possible, simply configure
`"list.hoverBackground": "#ff0000"`
