### ISSUE TITLE
F-strings cause incorrect quotation mark injection - trailing quotes get duplicated

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/vscode#67894]
@Vlad-Shcherbina commented on [Mon Feb 04 2019](https://github.com/Microsoft/vscode-python/issues/4264)

### Steps to reproduce
1. Open empty Python file.
2. Type the following: `print(f'hello {0}` . The result should look like this:
   ```python
   print(f'hello {0}|')
   ```
   `|` here denotes cursor position. Note that closing quotation mark and closing paren were injected automatically.
3. Now press `Del` to delete closing quotation mark. The result should look like this:
   ```python
   print(f'hello {0}|)
   ```
4. Finally, press `'` to insert quotation mark.

### Expected result
```python
print(f'hello {0}'|)
```

### Actual result
```python
print(f'hello {0}'|')
```
So it seems it incorrectly deduced that my quotation mark was the opening one, and injected the closing one.

### Environment data

- VS Code version: 1.30.2 (user setup)
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: Windows_NT x64 10.0.17134
- Python version: CPython 3.7
- Type of virtual environment used: N/A

### Logs

Nothing that I consider relevant. Let me know if you need more details.

---

@d3r3kk commented on [Mon Feb 04 2019](https://github.com/Microsoft/vscode-python/issues/4264#issuecomment-460427787)

This is indeed happening, but it happens in VS Code itself, even when the Python Extension is (and all other extensions installed are) disabled.

![4264_trailing_quotes_duplication](https://user-images.githubusercontent.com/11466735/52239780-1aaf4900-2884-11e9-9701-ed6ef4cd04a9.gif)

Moving to the upstream issues for VS Code.

**Comment by WSLUser** [comment]
Ping

**Comment by alexandrudima** [comment]
Let's track in #6841
