### ISSUE TITLE
Logpoint intellisense is not complete

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#67897]
![image](https://user-images.githubusercontent.com/323878/52244426-610ba480-2892-11e9-9faa-4a9ea18d4ffd.png)

It seems like it gets lost after a `.`. Seen it in other places, this example is ripgrepTextSearchEngine.ts:57

**Comment by isidorn** [comment]
We do quite some workarounds in order to get inteli-sense to work in the breakpoint widget. 
Due to that there are some limiations including this one.
