### ISSUE TITLE
possible to make all the extension sync with one drive/dropbox/google drive?

### ISSUE THREAD

**Issue by thyeun** [Microsoft/vscode#679]
want to request a features to sync all the extension into cloud drive, meaning that when changing a new PC or new device, all the extension from the previous PC can be easily get back, no need to be re-install all the extension again.

**Comment by Tyriar** [comment]
Some things that people do to accomplish extension/settings sync with other editors:

- Copy extensions to Google Drive and then [symlink](https://en.wikipedia.org/wiki/Symbolic_link) the directory to the config dir (`~/.vscode/extensions`)
- Setup extensions in your dotfiles

These are a little harder to automate on Windows though.

**Comment by thyeun** [comment]
i'm not sure how to make it work on VS code, but for sublime text 2, can use the below line to make it work, for sync with dropbox.

ln -s /Users/yeun/Dropbox/Packages /Users/yeun/Library/Application\ Support/Sublime\ Text\ 2/

**Comment by Tyriar** [comment]
Should be just a matter of finding the config path on your OS, try:

- `/Users/yeun/Library/Application\ Support/vscode/`
- `/Users/yeun/.vscode/`
- or similar

**Comment by thyeun** [comment]
thanks, will try it out on mac and windows, see either it possible to make it work!!

**Comment by Tyriar** [comment]
For Windows 10 the extensions are located in `C:\Users\<user>\vscode\extensions`, and the settings are located in `C:\Users\<user>\AppData\Roaming\Code\User`. Not sure about mac.

**Comment by Tyriar** [comment]
Also, I sync the settings in my dotfiles like [this](https://github.com/Tyriar/dotfiles/blob/master/vscode/index.js), I haven't looked at syncing extensions yet, I'm hoping it will be possible eventually to do it with a series of calls to `vsce` like you can with `apm install` for Atom ([like this](https://github.com/Tyriar/dotfiles/blob/master/atom/index.js)).

**Comment by thyeun** [comment]
yup, and one more things, the dropbox folder should in the correct path too, i mean in windows environments (i'm testing it on dropbox). =.=

**Comment by joaomoreno** [comment]
This doesn't seem to be an inherent issue with Code. But I'm glad people are finding solutions.

**Comment by petsuter** [comment]
On Windows start `cmd.exe` as Administrator and run `mklink /D C:\Users\YOURNAME\AppData\Roaming\Code\User C:\Dropbox\CloudSettings\VSCode\User`.
