### ISSUE TITLE
vscode.executeSignatureHelpProvider sends the command but no UI gets shown when the results are returned

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#67901]
- VSCode Version: 1.30.2
- OS Version: Windows.

Steps to Reproduce:

1. Put the cursor at some location in code that will get signature help results.
2. Invoke some typescript code that does something like
```
vscode.commands.executeCommand("vscode.executeSignatureHelpProvider", activeEditor.document.uri, activeEditor.selection.active, "(");
```
. See https://github.com/Microsoft/vscode-cpptools/commit/0f6741b2b422c49e31644015f7177de614ce18ab .

Bug: The signature help command gets sent to the language server and it sends the results back, but no UI appears to the user with the result.

You can repro this with the C/C++ extension at https://github.com/Microsoft/vscode-cpptools/tree/seanmcm/signatureHelpCommand , and invoking the C_Cpp.Navigate command.

This prevents us from making signatureHelp appear when "(|)" gets added to completion results, because the user never types the (. If we could just set the CompletionItem.command to "vscode.executeSignatureHelpProvider" without any arguments that would be even better, but that doesn't currently work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> The signature help command gets sent to the language server and it sends the results back, but no UI appears to the user with the result.

Yes, that's the design: Execute providers just like the UI, return the model but don't show UI. The command the UI (keybinding) invokes is `editor.action.triggerParameterHints`

**Comment by sean-mcmanus** [comment]
Thanks a ton -- that works great.

Feedback for anyone wanting to improve the developer documentation: The documentation at "https://code.visualstudio.com/api/extension-guides/command" says "VS Code includes a large set of [built-in commands](https://code.visualstudio.com/api/references/commands) that you can use to interact with the editor, control the user interface" and that doc showed "vscode.executeSignatureHelpProvider - Execute signature help provider.". That page doesn't mention anything about not showing UI or any link to the keyboard commands that list the other UI invoking commands, and sending results to VS Code without showing anything seemed buggy since it had no effect (it wasn't clear that the "promise that returns a SignatureHelp" mean the call was expected to do something with the results...providing examples of how the results would be used usefully by an extension would make it clearer). A link to the keyboard commands that invoke the UI would be useful on those pages. The 2 different names for the same feature in the API (ParameterHints versus SignatureHelp) could be more explicitly called out in the docs in case users forget, because it makes it harder to search (or for search engines to link the 2 different search terms).
