### ISSUE TITLE
Start installation of multiple .vsix files simultaneously

### ISSUE THREAD

**Issue by ember91** [microsoft/vscode#67905]
#### Version of VS Code
1.29.1

#### Your operating system
Ubuntu MATE 16.04

#### List of extensions that you have installed:
None

#### Reproducible steps (1... 2... 3...) that cause the issue
1. File->Preferences->Extensions
2. Click ellipsis button (...)
3. Click "Install from VSIX..."
4. Try to choose multiple .vsix files, e.g. with Shift+click or Ctrl+click. It is not possible.

#### What you expected to see, versus what you actually saw:
I expect to be able to choose multiple .vsix files and install them all simultaneously. Instead I had to click "Install from VSIX..." once for each extension.

**Comment by ember91** [comment]
This is possible from the command line, though.

**Comment by COD3BREAK3R** [comment]
This feature will be good. Need be implemented
