### ISSUE TITLE
VSCode ZSH Glitch when pressing tab

### ISSUE THREAD

**Issue by rogierv** [Microsoft/vscode#67904]
- VSCode Version: 1.30.2 (1.30.2)
- OS Version: Mac OS 10.14.2

Steps to Reproduce:
![vscode_zsh_glitch](https://user-images.githubusercontent.com/593509/52258266-be4d3780-291e-11e9-99c9-9a8b152e449d.gif)

1. When using Zshell in the integrated terminal, pressing tab will show incorrect presentation of the input.
2. I am using ZSH Theme "avit", but it happens as well for the default theme "robbyrussell"

**Comment by Tyriar** [comment]
I suspect this is related to https://github.com/xtermjs/xterm.js/issues/1709, it'll probably get fixed if you change the triangle prompt character.

**Comment by rogierv** [comment]
> I suspect this is related to [xtermjs/xterm.js#1709](https://github.com/xtermjs/xterm.js/issues/1709), it'll probably get fixed if you change the triangle prompt character.

Thanks for you quick response. Although I do not understand how I can fix this by changing the triangle prompt character. Could you give me a hint? :)

**Comment by Tyriar** [comment]
@rogierv I don't know how zsh and its themes work, but normally this means your `$PS1` env variable includes the character.
