### ISSUE TITLE
Terminal: Can't press Escape key

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#6790]
Testing #6654

The escape key surfaces to the workbench, closing the terminal. This is bad in situations where commands really need the escape key, such as vim.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6455, I'm interested in your thoughts on this @joaomoreno if you want to comment. <kbd>esc</kbd> to dismiss would certainly be useful to close the terminal, and vim is the only example I could think of. Not sure if it should be a setting or what.
