### ISSUE TITLE
Minimize window isn't working

### ISSUE THREAD

**Issue by tarun04** [Microsoft/vscode#67902]
Issue Type: <b>Bug</b>

The window doesn't minimize.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.14.74-07776-gac52e5f750c8

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|4.84GB (2.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?w

**Comment by Tyriar** [comment]
@tarun04 https://code.visualstudio.com/insiders/#linux, I don't think we officially support Chromebooks yet though
