### ISSUE TITLE
Remove tree.visibleNodeCount

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#67907]
The `visibleNodeCount` property is a little misleading, I want to remove it:

https://github.com/Microsoft/vscode/blob/9deb608cc6c152d091484aebd9efcbbb35206f73/src/vs/base/browser/ui/tree/asyncDataTree.ts#L570

It is currently being used in two places. First: 

https://github.com/Microsoft/vscode/blob/9deb608cc6c152d091484aebd9efcbbb35206f73/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L256

@isidorn We should use `tree.contentHeight` in here, instead of number of rows multiplied by row height.

Second:

https://github.com/Microsoft/vscode/blob/9deb608cc6c152d091484aebd9efcbbb35206f73/src/vs/workbench/parts/debug/electron-browser/callStackView.ts#L237

@isidorn This is misleading since the tree can be empty due to type filtering. I suggest you do a different check in here.

When you remove both let me know so I remove the property.

**Comment by isidorn** [comment]
I am not using `tree.visibleNodeCount` any more.
Leaving this item up to you then.
