### ISSUE TITLE
[Windows 10][Insider build] Conpty cannot be enabled in Feb.4 Insider build

### ISSUE THREAD

**Issue by fsworld009** [Microsoft/vscode#67903]
- VSCode Version:
```
Version: 1.31.0-insider (user setup)
Commit: 5ab047b584d974033e0c5ce529ea74a869355b87
Date: 2019-02-04T15:32:22.547Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
- OS Version:
Windows 10 ver 1809

Steps to Reproduce:

1. Set `terminal.integrated.windowsEnableConpty` to `true` to enable Conpty
2. launch integrrated terminal, I can see the color bugs from winpty backend.

I'm pretty sure Conpty was working during 22:00~23:00, Feb.4, GMT+8 time, looks like this update just rolled out, and now Conpty is not working anymore.

I tried to roll back to a Jan.18 build (I still have the installer on my machine so I tried it), Conpty can be enabled in this version and there is no color bug.

The version info:
```
Version: 1.31.0-insider (user setup)
Commit: 2283b29c695da3163fd4b524617dabcfb8298bbe
Date: 2019-01-18T10:23:02.757Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

I had background update checked so I'm not sure what version I was using last night.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by Tyriar** [comment]
This is by design, it had too many issues on versions below the build number mentioned in the setting.
