### ISSUE TITLE
Settings UI: Improve `Edit in settings.json` experience

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#67908]
For the settings that have non standard types, the settings UI show a `Edit in settings...` link. Clicking opens the settings file.

It would be nice if that experience could be improved.

- if the settings doesn't yet exist in the settings, add it with the default value and select the value. Right now I have to figure out the key of the setting.
- If the settings already exist, reveal it
- provide a way to see the value of the setting in the settings UI. If not the full value, it's interesting to know that the settings is set. A hover could provide the full setting.
- instead of opening the setting file, bring up an embedded text box on demand

**Comment by iansan5653** [comment]
Absolutely agree with this one. It's really jarring to click to edit a setting only to be taken to a text file with nothing relevant to that setting. If you're intimately familiar with JSON it might be ok for you, but most aren't.

From the UI, we don't even get to see the key of the setting or the format of the setting - these have to be copied from a hidden gear menu and inferred from the setting description respectively.

**Comment by fireattack** [comment]
It's kinda of weird this feature ships this way in the new Settings interface, almost feel like it's unfinished (i.e. not intended to be like this). 

Like others have already said, I think it is *supposed to* copy/reveal the ID (and format) for the setting you're trying to modify, otherwise it makes no sense to insert the link after every single non-standard settings.

**Comment by zoechi** [comment]
I just started with VSCode and searched 1/2h why the entry is not added when I click "Edit in settings.json" while this looked differently in YouTube videos I followed.

**Comment by roblourens** [comment]
This was actually improved nicely recently

**Comment by iansan5653** [comment]
@roblourens am I missing something? It seems like the "Edit setting in JSON" option was removed altogether:
![image](https://user-images.githubusercontent.com/2294248/82085870-a6d13280-96bb-11ea-99f7-a159b3d2a103.png)
Was it moved?

**Comment by roblourens** [comment]
I don't think we've ever had that option under that menu. I am just referring to the button that shows up on settings that can't be edited in the GUI editor.

**Comment by fireattack** [comment]
> I don't think we've ever had that option under that menu. I am just referring to the button that shows up on settings that can't be edited in the GUI editor.

It's not under that menu indeed, but there used to be a link right after each option for that:

![image](https://user-images.githubusercontent.com/4130991/82099183-48608000-96cc-11ea-9885-f42adf80a736.png)

This issue ticket is actually about this very feature. 

So it's not really "improved", but totally "removed".

**Comment by iansan5653** [comment]
I see, thanks!
