### ISSUE TITLE
IDataSource and hasChildren

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67912]
re #64727

<img width="603" alt="screenshot 2019-02-05 at 10 27 37" src="https://user-images.githubusercontent.com/1794099/52263958-c4e4aa80-2930-11e9-94c0-81be079ee082.png">

I have implemented `IDataSource` which only declares `getChildren` and now *some* of my children have a twisty where it doesn't make sense to have one. Not sure how to control that...

**Comment by joaomoreno** [comment]
Fixed! Got a bit confused while looking at this and found an issue in the branch: the panel forgets to save the tree's view state when switching to a file which has no outline at all (.txt).

**Comment by jrieken** [comment]
> Got a bit confused while looking at this and found an issue in the branch: the panel forgets to save the

Good catch. That's something the outline never did...

**Comment by jrieken** [comment]
> Good catch. That's something the outline never did...

Pushed a fic
