### ISSUE TITLE
Missing event when toggling between type to filter/find 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67910]
re  #64727

The outline has a check box that toggled between filter/find. I don't wanna take that away and to keep in sync with the flyover I need to know when the filter/find has changed via that button.

**Comment by joaomoreno** [comment]
Exposing `tree.onDidUpdateOptions`, option name to look for is `filterOnType`.

**Comment by joaomoreno** [comment]
Verification: please code review.
