### ISSUE TITLE
Sub menu arrows are not visible when using a light theme

### ISSUE THREAD

**Issue by dmtweigt** [Microsoft/vscode#67918]
Issue Type: <b>Bug</b>

1. Start VS Code
2. Go to *File > Preferences > Color Theme*
3. Pick a **light** theme
4. Open the *File* menu (or any other with sub menus)

Observed: *Preferences* and *Open Recent* menu items have invisible arrows, unless the mouse is hovered over them
Expected: *Preferences* and *Open Recent* menu items have arrows that are always visible

|dark theme|light theme|
|---|---|
|![dark2](https://user-images.githubusercontent.com/47352196/52272483-39c2df00-2947-11e9-8bbd-e293eb4078bd.png)|![light2](https://user-images.githubusercontent.com/47352196/52272482-392a4880-2947-11e9-9ff7-2e33d4e1bc1f.png)|

VS Code version: Code - Insiders 1.31.0-insider (b313db6c58f8c02181a33cd3b5b4b17c64a5b85d, 2019-02-05T10:16:27.989Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
I can reproduce:

![image](https://user-images.githubusercontent.com/900690/52288697-faa78480-296c-11e9-8546-115dfc51b26b.png)

@sbatten @misolori didn't we change the arrow icons in this release to be smaller?

**Comment by sbatten** [comment]
@bpasero this actually reproduces in stable as well, and I think I know why

**Comment by sbatten** [comment]
@bpasero worse, I tried to debug it from dev tools and now I can no longer repro

**Comment by sbatten** [comment]
got it. as a workaround, just reload the VS Code window after switching to the default light themes. 

When the menu gets styled at launch, the styler picks either the theme's menu fg color or falls  back to the default fg color. since the built-in dark theme has a menu fg color, this is what is set. Later when you switch to the light theme, there is no menu fg color so it gets set to null. It needs to fallback here.
