### ISSUE TITLE
Terminal shortcut in View menu is displayed differently than rest

### ISSUE THREAD

**Issue by whobbes** [microsoft/vscode#67913]
Issue Type: <b>Bug</b>

When opening the View menu on VSCode on Mac, the keyboard shortcut for Terminal confusingly appears in brackets and on the left i.e. - Terminal[^'] - rather than on the right like others e.g. - Output      [arrow_up][cmd]U -

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
rainbow-csv|mec|1.0.0
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-arduino|vsc|0.2.25
debug|web|0.22.0

</details>

**Comment by whobbes** [comment]
This is what I have -->

[
<img width="214" alt="screenshot 2019-02-05 at 13 04 11" src="https://user-images.githubusercontent.com/5123368/52275146-9a055100-2946-11e9-8c9f-39a03f19dce1.png">
](url)

**Comment by shungo27** [comment]
Not yet fixed in 1.36.1
![terminal](https://user-images.githubusercontent.com/7065076/62072965-b4c3dd00-b27a-11e9-9c27-a53931aedb18.png)

**Comment by sbatten** [comment]
@deepak1556  as I recall this has to do with what macOS can display, don't recall if this is electron or macOS limitation.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/161347
