### ISSUE TITLE
Global Code Snippets should use Scope Name

### ISSUE THREAD

**Issue by esemlabel** [Microsoft/vscode#67920]
Current implementation of global snippets allows us to set language option only, but not exact scope name.

Setting scope name is useful when mixing code in php files.
`php` typed trigger with snippet below will invoke `<?php ?>` suggestion snippet not only inside php files with html markup, embedded js or css, but in .html, .js and .css files as well - which is way wrong. 

```javascript
"<?php … ?>": {
    "scope": "html,javascript,css",
    "prefix": "php",
    "body": "<?php $1 ?>$0"
},
```

In global snippets It would be correct to set the scope name or names, separated with comma:

```javascript
"<?php … ?>": {
    "scope": "html,javascript,css",
    "scopeName": "text.html.php",
    "prefix": "php",
    "body": "<?php $1 ?>$0"
},
```

**Comment by jrieken** [comment]
Agreed but the only scopes the editor knows are `string`, `comment`, `regex`, and `other`. Scopes as defined by a Textmate grammar aren't exposed in the editor.

**Comment by esemlabel** [comment]
Can we unload snippets in editor later in a state when they becomes available, if they doesn't match provided scope name?

**Comment by jrieken** [comment]
> Or the scope names never recognized by editor?

Never.

**Comment by esemlabel** [comment]
Closed for now.
