### ISSUE TITLE
Title does not update after reload when active file got deleted

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#67922]
Issue Type: <b>Bug</b>

Reproducibility 100%
Reproduces without extensions

**Steps to Reproduce:**

1. Create an empty file with VS Code
2. Save it to disk
3. Keep it open in the editor
4. Delete that file with something else than VS Code
5. Observe that VS Code title is `<filename> (deleted from disk)`
6. Reload VS Code
7. The editor has been closed but the title is still `<filename> (deleted from disk)`
8. At that point, VS Code window title does not reflect what is actually happening inside it.

I can join a screenshot if you fail to reproduce

<details>
VS Code version: Code - Insiders 1.31.0-insider (b313db6c58f8c02181a33cd3b5b4b17c64a5b85d, 2019-02-05T10:16:27.989Z)
OS version: Windows_NT x64 10.0.15063
</details>

**Comment by bpasero** [comment]
Open for help if someone wants to investigate.

**Comment by bpasero** [comment]
I would say this behaviour counts as a bug, no?:

> 7\. The editor has been closed but the title is still `<filename> (deleted from disk)`

**Comment by sguillia** [comment]
It is useful that the files deleted from disk are being kept in cache. Point 7 is the actual bug.

What fix would you want @bpasero?

a) After reloading, the editor is closed and the window title is the default one
b) After reloading, the file is still kept in cache and the `deleted from disk` editor is still open

I haven't contributed yet, any hint as to where to start to look from is welcome :-)

**Comment by bpasero** [comment]
Yeah I think so too, the window title should reset properly when the editor closes because of the error. I would check somewhere in `titlebarPart.ts`

**Comment by bpasero** [comment]
Oh I see, this one is a bit tricky timing wise. I think I would not expect an easy fix here, removing "help wanted".

**Comment by sguillia** [comment]
If it might save you time, the closest code I could find is this one:
https://github.com/Microsoft/vscode/blob/9cf141830f4ff3b83ddce29b42240a55a927905e/src/vs/code/electron-main/window.ts#L506-L512

Code only sets title if we did not reload.
