### ISSUE TITLE
little drop when transitioning from preview to pinned

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6792]
#6536

* open a file in preview
* when pinning it, it's representation in the Open Editors view drops by a pixel or so

![may-24-2016 14-57-54](https://cloud.githubusercontent.com/assets/1794099/15504591/fb6aec52-21bf-11e6-9082-eda9fac1959e.gif)

**Comment by bpasero** [comment]
Also noticed it and might be font related again.

**Comment by bpasero** [comment]
@bgashler1 also related to https://github.com/Microsoft/vscode/issues/6759

**Comment by isidorn** [comment]
Forwarding to @bgashler1 to get advice on how to hande this font issue

**Comment by bgashler1** [comment]
@isidorn it looks like a font-weight change is occurring, e.g. Segoe UI semi-bold to Segoe UI regular (just from looking at the GIF).  I will need to look more closely and inspect the element in the dev tools.

**Comment by bgashler1** [comment]
Please see this https://github.com/Microsoft/vscode/issues/6759#issuecomment-223628796 for the solution.

**Comment by bpasero** [comment]
Note that with https://github.com/Microsoft/vscode/issues/7123 we are using "San Francisco" font on OS X now. We never used Segoe on OS X because that is a Windows font. Instead we did fall back to Helvetica.

**Comment by bgashler1** [comment]
This should be addressed, now that we're using  San Fransisco font.

It's possible that on older versions of Mac OS that this will remain an issue, due to Helvetica Neue-Light.  The fix would be to switch from Helvetica Neue-Light to Helvetica Neue (regular).  Any objections on changing that as a fallback for San Fransisco?

**Comment by bgashler1** [comment]
Verified that San Fransisco fixes this.  While this remains a problem for machines that use Helvetica Neue, this would only a problem for people who are not upgrading their Mac operating system.  It seems to be an issue with that particular font.
