### ISSUE TITLE
type to select doesn't update

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67936]
re #64727

* get changes in `joh/o2`
* start typing in the outline view
* on first type the selection updates
* on subsequent types the selection doesn't change to the better match

![feb-05-2019 17-56-01](https://user-images.githubusercontent.com/1794099/52290078-9639f480-296f-11e9-9f19-c26afabbebb8.gif)

**Comment by jrieken** [comment]
this only seems to be an issue with the *sync* tree, the async data tree that I use in breadcrumb file pickers does work fine

**Comment by joaomoreno** [comment]
Actually this happened for all trees. Repro:

1. Create `foo` and `foobar` files in Explorer
2. Type `foo`, `foo` should be focused
3. Type `b` to get `foob`, `foobar` should be focused and isn't
