### ISSUE TITLE
--extensionHomePath not working in last insiders update

### ISSUE THREAD

**Issue by dicaetano** [Microsoft/vscode#67937]
Version: 1.31.0-insider (user setup)
Commit: b313db6c58f8c02181a33cd3b5b4b17c64a5b85d
Date: 2019-02-05T10:16:27.989Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.  Set "--extensionHomePath "C:\folder" in vscode shortcut 
2. vscode still open using the default extension folder. "F1 -> Extensions: Open Extension Folder" proves it 

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
The actual command line option is `--extension-dir`. We used to have an alias that we kept around for the last two years that we lost with https://github.com/Microsoft/vscode/commit/efc4d938188e90852c5c25dd96dd9412288c4fc5.

**Comment by aeschli** [comment]
I corrected @kieferrm comment, it's `--extensions-dir` with an `s`

**Comment by dicaetano** [comment]
thanks guys!
