### ISSUE TITLE
Terminal: tab completion is weird in zsh

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#6793]
Testing #6654

Maybe this should be filed to the original JS tty implementation.

When typing a command name in the prompt like:

![image](https://cloud.githubusercontent.com/assets/22350/15504680/6996eb86-21c0-11e6-9e9f-003ec158bf3b.png)

And tabbing, I get a few characters repeated:

![image](https://cloud.githubusercontent.com/assets/22350/15504683/6cb80b42-21c0-11e6-94c0-044d6ae77980.png)

Only seems to happen in zsh, not bash.

**Comment by Tyriar** [comment]
I can't repro this, perhaps something in your prompt script is causing it?

**Comment by Tyriar** [comment]
Toggling the terminal continually puts zsh in a weird state too:

![image](https://cloud.githubusercontent.com/assets/2193314/15524184/ed10a2a4-21d4-11e6-85cd-f7e896d7dcbd.png)

**Comment by Tyriar** [comment]
@joaomoreno does this still happen?

**Comment by joaomoreno** [comment]
LGTM
