### ISSUE TITLE
Improve File Creation Dialog

### ISSUE THREAD

**Issue by SirNovi** [Microsoft/vscode#67943]
I think the `File: New File Relative to Project Root` function could be greatly improved by providing it with a similar functionality that is available for file opening via `cmd + p` 

Right now I rather navigate the file tree in the sidebar to create a new file because the creation is so cumbersome. But if I would be able to hit that command and type "pub res js" and it would propose "public/resources/js" and I could just hit enter, that would be amazing and a big time saver. And a further step for more screen real estate as the sidebar would become even more irrelevant.

**Comment by kieferrm** [comment]
@SirNovi `File: New File Relative to Project Root` is not part of VS Code out of the box. It must comes in through an extension. Please file the issue against the extension. Thanks!
