### ISSUE TITLE
Data loss bug: vscode overwrites newer version of file if file did not exist at first

### ISSUE THREAD

**Issue by russelldavis** [Microsoft/vscode#67946]
If you open a new (nonexistent) file in vscode from the command line, and the file then gets created externally, vscode will overwrite the file without any warning about a conflict.

Steps to Reproduce:

1. Make sure `foo` does not exist.
2. In a terminal, run `code foo`
3. VSCode will open a new editor for `foo`.
4. In a terminal, run `echo blah > foo` (or write to `foo` in a different editor)
5. Switch back to VSCode and save the file. 
6. The contents written in step (4) will be overwritten without any warning.

- VSCode Version: 1.30.2
- OS Version: macOS 10.14.2
- Does this issue occur when all extensions are disabled?: Yes

While searching I found a different but related data-loss bug that seems pretty bad (and has been open for over two years): https://github.com/Microsoft/vscode/issues/15749.

I'm pretty frustrated after losing a bunch of work, so apologies if this comes off the wrong way, but: where does preventing data-loss stand in terms of priorities for vscode?

**Comment by bpasero** [comment]
I can reproduce, thanks for the steps. We typically guard against this case by showing an error message if we detect that the file got changed on disk. However in this particular case we fail to do so. Will look into how to fix that.

**Comment by bpasero** [comment]
Pushed a change that will show the following prompt, if:
* an untitled file is saved
* that has an associated file path
* who's file path exists on disk (which can pretty much only happen if the file was created after VSCode has started)

![image](https://user-images.githubusercontent.com/900690/52522027-53826000-2c80-11e9-9a9e-7af96fea3f4e.png)

**Comment by russelldavis** [comment]
Thanks!
