### ISSUE TITLE
Keyboard freeze

### ISSUE THREAD

**Issue by gohar94** [microsoft/vscode#67944]
Issue Type: <b>Bug</b>

While typing sometimes I stop seeing what I am inputting and then all of a sudden after a few seconds it sometimes shows up or sometimes doesn't show up at all.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (4.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.116
vscode-nmake-tools|Mic|1.1.190128002
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
vim|vsc|1.0.7

</details>

**Comment by kieferrm** [comment]
@gohar94 I suspect that this is caused by one of your extensions monopolizing the extension host so that your VIM extension doesn't get a chance to react to your input.
