### ISSUE TITLE
Unable to block auto indent of html in multiple ways

### ISSUE THREAD

**Issue by markFromMST** [Microsoft/vscode#67954]
If you use electron-forge init --template=react you will end up with an index.html that has the javascript needed to get your app up.  

![image](https://user-images.githubusercontent.com/7367024/52312462-9f7b8f00-2978-11e9-9339-af79cc068a43.png)

The problem is that when you save and it auto formats, it breaks the ability of electron to render it.  So, I tried a bunch of different things and none worked.

I tried blocking it within the script tag:

  "html.format.contentUnformatted": "pre,code,textarea,script",

and

  "html.format.unformatted": "script",

I tried turning it off just for html:

    "[html]": {
        "editor.formatOnSave": false
    }

I tried turning off auto format for everything:

    "editor.formatOnSave": false,

The only way I can get it to not format the file at all is to switch the file type to plain text down in the lower right hand corner of the VS Code UI.

![image](https://user-images.githubusercontent.com/7367024/52312507-cafe7980-2978-11e9-9af1-01804232b7dc.png)

**Comment by usernamehw** [comment]
Most likely not the solution, but there's command `workbench.action.files.saveWithoutFormatting`

**Comment by octref** [comment]
What's the output from `code --list-extensions`?
