### ISSUE TITLE
Merge markers left in file but hidden by editor

### ISSUE THREAD

**Issue by aaronclarke** [Microsoft/vscode#67959]
Issue Type: <b>Bug</b>

I'm not sure how I managed to get this, but I messed up a git merge and accidentally left merge markers in the file. But VSCode was very weird in that it collapsed all of the merge markers and hid them so that I couldn't tell there was a problem when I visually inspected before committing.

Pictures attached. One where my yaml file has seemingly no issues except for a small red arrow near the top of the file (mergemarkers_hidden.png), and one where I have clicked on that arrow and it was expanded out (mergemarkers_expanded.png). 

This was very non-intuitive. I never expect a code editor to high code away without a stronger visual indicator. And I would certainly not want it to happen automatically without me pressing a button to do it.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (7.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0
team|ms-|1.144.1

</details>

![mergemarkers_expanded](https://user-images.githubusercontent.com/22897312/52317266-29752900-2974-11e9-8344-38018cd8b780.PNG)

![mergemarkers_hidden](https://user-images.githubusercontent.com/22897312/52317267-2a0dbf80-2974-11e9-8bd4-0d1737130440.PNG)

**Comment by joaomoreno** [comment]
VS Code is telling you that you used to have a `<<<<<< HEAD` line and you just deleted it. Great. Just commit that change and you're good to go.

The red marker is not an "issue", it's an indication of deleted code, done by you.

VS Code did not hide any code. You just deleted that line.

**Comment by aaronclarke** [comment]
Maybe that's the intended behavior, but the merge markers were definitely in the file. Looking at the file in Notepad / Wordpad both showed the merge markers still in the file, and I had even committed and pushed that file to my remote and broke my automated build in Azure DevOps because it couldn't load the yaml file because of the merge markers.

**Comment by joaomoreno** [comment]
The merge markers are supposed to be in a file. That's what git does when there's a merge conflict 

https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
