### ISSUE TITLE
Closing all files in a group except for a markdown file does not update overflow control icon

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#6795]
- VSCode Version:1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open multiple files into one group, ensure a markdown file is open
2. In the open editors list, close all files except the markdown file

Expected: Markdown editor overflow control should indicate that the group only contains one file
Actual: Overflow control indicates that there are multiple files in the group

**Comment by bpasero** [comment]
@stevencl having a hard time reproducing this, any more reproducible steps? can you reliably reproduce?

**Comment by stevencl** [comment]
Yes, I can repro it each time. For example:
![overflow](https://cloud.githubusercontent.com/assets/1704059/15505169/24a0cf70-21ba-11e6-87bc-1bb2bdb8ece2.gif)

**Comment by bpasero** [comment]
Ah good, the important part is that you close hidden editors :)

**Comment by alexandrudima** [comment]
I see no sergeant icon at all anymore, so I guess that verifies it

**Comment by bpasero** [comment]
@alexandrudima it is still there, just changed icon (now indicating a stack).

**Comment by bpasero** [comment]
But yeah, I see how Steven points are obsolete now. Marking as verified.

**Comment by alexandrudima** [comment]
@bpasero - This is what I mean:

(I tried to reproduce the original issue which was without tabs enabled from the screenshot)

![image](https://cloud.githubusercontent.com/assets/5047891/16563363/e1ce9016-4201-11e6-95f7-67d4310ea51e.png)

**Comment by bpasero** [comment]
@alexandrudima yup you are right
