### ISSUE TITLE
gridTemplateAreas syntax error

### ISSUE THREAD

**Issue by anlexN** [Microsoft/vscode#67961]
- VSCode Version: latest
- OS Version: windows 10 pro

Steps to Reproduce:

## Expected Behavior 🤔
grid layout css is suppoted

## Current Behavior 😯
![image](https://user-images.githubusercontent.com/8686739/52177724-69b39a80-2800-11e9-98cb-3a9838b00c15.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is invalid JS syntax. You should use backtick strings for multiline string content

**Comment by anlexN** [comment]
@mjbvz, i know backtick but how to do? excuse me. i am trouble
