### ISSUE TITLE
VSCode says there are unsaved files, deletes the content of the file on save.

### ISSUE THREAD

**Issue by IrregularProgrammer** [Microsoft/vscode#67963]
VSCode gives the notification that there is X Number of unsaved files when opened. On clicking the Save All Icon in the Open Editors Panel, it deletes the content of the files that it says need to be saved. Also, it only says that X Files need to be saved but doesn't tell which files need to be saved and those files aren't also opened in the Editor sometimes, so the Open Editor doesn't show the unsaved icon beside those files. Once the content is deleted, you will only realize that after you open that file for editing. The content can be restored by using CTRL + Z in case you just opened the file. 

This only happens to files that you create and edit. Doesn't happen to files that are copied but not edited, like Bootstrap, jQuery, etc. 

Windows 10 + Linux (Ubuntu 18.04 + Linux Mint)

**Comment by kieferrm** [comment]
@IrregularProgrammer pls provide step by step instructions that help us reproducing the problem without guessing the steps. Thanks!

**Comment by IrregularProgrammer** [comment]
I have been using VSCode as it was installed, no extensions.
The issue can be reproduced following the steps.
1. Open a Folder Using the "**code FOLDER_NAME**" from the Terminal (Inside and Outside Visual Studio)
2. Create a New File using the "**code FILE_NAME**" command. (I use the command to create files and only used the Menu Option once or twice since it is more work)
3. Write your code in the file and save it using CTRL + S
4. Repeat Step 2 and 3 until you are done with the files that you wanted to create and edit.
5. Close VSCode using the "X" close button in the corner.
6. Open VSCode using its Desktop Icon or the Taskbar Icon when you return to your work later.
7. VSCode will open the project folder and files that you had closed it with before.
8. There will be a notification saying that "**There are some unsaved files**" in the Open Editors Panel. It won't tell what files to save. The files open in the Editor Panel might or might not be among the files that need to be saved.
9. Save the Files using the "Save All" button in the Open Editors Panel and the files will be blank when you open them. 
10. When the Blank Files are open, click CTRL + Z to restore the content of the files. (This doesn't guarantee that the content will be restored. It didn't work for me once or twice.)

Note: I only use VSCode for PHP, HTML, CSS, and Javascript/Node files. I can't tell if other files will be affected or not.

**Comment by bpasero** [comment]
@IrregularProgrammer I tried this without being able to reproduce:
* open a terminal
* create a fresh empty folder ~/Desktop/foo
* type code ~/Desktop/foo
* type code ~/Desktop/foo/1.txt
* enter some text and save
* type code ~/Desktop/foo/2.txt
* enter some text and save
* type code ~/Desktop/foo/3.txt
* enter some text and save
* quit
* start code

=> I see no dirty files.

Can you try to reproduce this also by disabling all extensions via:

From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by IrregularProgrammer** [comment]
Update: The issue stopped after I updated VSCode to Version 1.31.0
