### ISSUE TITLE
file:/// URLs don't work correctly on Linux

### ISSUE THREAD

**Issue by perlun** [Microsoft/vscode#67969]
Issue Type: <b>Bug</b>

As reported in #62777, I have problems with launching URLs from `gnome-terminal`. The issue was never resolved there but it still persists and I now have managed to find some more information about it.

So, my problem is when clicking/ in `terminator` or `gnome-terminal` on a URL like `file:///home/per/git/some-project/gatling-benchmarks/build/reports/gatling/dblatencysimulation-1549445991628/index.html`, this is what I get:

![image](https://user-images.githubusercontent.com/630613/52336200-f8950280-2a0c-11e9-9657-43834d9645e7.png)

When clicking on some other file, like a `file:///foo.txt` URL, some other program opens, so it's likely that it's _specifically_ file URLs with `.html` ending that triggers this.

I've noted that I can also reproduce this elsewhere, like in the Nemo file manager (I'm using Cinnamon on Debian GNU/Linux), depending on how I choose to open the file.

### Nemo: Open With Visual Studio Code - works fine

Right click an `.html` file, `Open With` -> `Visual Studio Code`:

![image](https://user-images.githubusercontent.com/630613/52336380-78bb6800-2a0d-11e9-8789-9bc2831ea816.png)

### Nemo: Open with Visual Studio Code - URL handler - fails

Right click, select "Open with Visual Studio Code - URL Handler", this gives me the exact same behavior as when ctrl-clicking from the terminal:

![image](https://user-images.githubusercontent.com/630613/52336200-f8950280-2a0c-11e9-9657-43834d9645e7.png)

###  /usr/share/applications/code-url-handler.desktop 

My ` /usr/share/applications/code-url-handler.desktop` looks like this:

```
$ cat /usr/share/applications/code-url-handler.desktop 
[Desktop Entry]
Name=Visual Studio Code - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --open-url %U
Icon=code
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode;
Keywords=vscode;
X-Desktop-File-Install-Version=0.23
```

I've also tested with ` /usr/share/code/code --open-url file:///home/per/git/some-project/external/gatling-benchmarks/build/reports/gatling/dblatencysimulation-1549445991628/index.html`, but interestingly enough _this does nothing whatsoever_ - vscode doesn't even open. If I replace the URL with an absolute path, I get the same `Untitled - 1` result.

If I instead do `firefox file:///home/per/git/some-project/external/gatling-benchmarks/build/reports/gatling/dblatencysimulation-1549445991628/index.html`, it loads without problem so I'm quite certain that the URL is right and the file definitely exists.

I really don't know how to debug this further, but I'm open to suggestions. It could certainly be a misconfiguration on my system, but I honestly don't know where to fix it in that case so please point me in the right direction.

Many thanks in advance.

### Version info

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.19.0-1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2198)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.93GB (4.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
haproxy|bma|0.1.1
better-toml|bun|0.3.2
solargraph|cas|0.19.2
gitlens|eam|9.5.0
beautify|Hoo|1.4.8
Scala|itr|0.1.7
mysql-syntax|jak|1.3.1
puppet-vscode|jpo|0.16.0
restructuredtext|lex|100.0.0
VS-code-vagrantfile|mar|0.0.7
code-beautifier|mic|2.1.0
xml-format|mik|1.0.1
binary-viewer|mom|0.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.5.2
ruby|reb|0.21.0
java|red|0.38.0
vscode-yaml|red|0.2.1
vscode-icons|rob|8.1.0
vscode-nginx|sha|0.6.0
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
code-spell-checker-swedish|str|0.1.1
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1
vscode-wakatime|Wak|1.2.5
vscode-proto3|zxh|0.2.2

(4 theme extensions excluded)

</details>

**Comment by perlun** [comment]
(#66940 is unrelated)

**Comment by perlun** [comment]
FWIW, this is still a problem with a recent version of vscode:

```
$ code --version
1.32.2
e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951
x64
```

**Comment by joaomoreno** [comment]
I've reopened https://github.com/Microsoft/vscode/issues/62777
