### ISSUE TITLE
Find All References doesn't return all instances at first but Find in Files does

### ISSUE THREAD

**Issue by jodymbrooks** [Microsoft/vscode#67962]
Issue Type: <b>Bug</b>

I have doing Find All References (FAR) from the definition of a function in JS. It shows me the definition and sometimes one reference almost as if it's only showing me the instances in my open files.

However I can do Find In Files (FIF) and see there are more as I expected. Once I open one of those instance that were not previously found, not Find All References does find them all, even ones in files I didn't open.

Just now I found the definition only with FAR, but once I did FIF and opened one of them (a reducer file in React), then did FAR from that instance (so not the definition), then it did find all the references including the reducer I just started from, the definition it was already finding, and now also the action file that also contained a reference.  I went back to the definition of the function and did FAR again and it does still find all of them indeed now. Note that I never opened the action file so it's not about just finding the references in the open files. In other words, when it kicks into working, it does find the references even in non-open files.

My project is this: https://github.com/jodymbrooks/brave
and I am doing FAR and FIF for getCardFromKey in the src/cardUtilities.js file.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.25
vscode-eslint|dba|1.8.0
prettier-vscode|esb|1.8.1
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.11.1
highlight-matching-tag|vin|0.8.6

</details>

**Comment by mjbvz** [comment]
Thanks for the project example.

I think you need a [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) file. This makes VS Code treat all js files in your workspace as part of the same project (even if they have not been opened yet) Just create a file called `jsconfig.json` at the root of your project:

```
{
    "compilerOptions": {
        "target": "es6"
    },
    "exclude": [
        "node_modules"
    ]
}
```

See the [jsconfig docs](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) for more info

**Comment by jodymbrooks** [comment]
Yes that corrected it for me. I'll have to look into that documentation on jsconfig as this means I'm missing some understanding on how VS Code considers the files in your workspace, that open files have meant something different than other files in the WS is interesting. Have to study what that means.

Thanks for the answer.
