### ISSUE TITLE
New Explorer: jumping back to last used file does not seem to always work

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67972]
I am not sure how I get there but often I end up with a diff editor even though I clicked back on the explorer:

![image](https://user-images.githubusercontent.com/900690/52338856-d058d400-2a0b-11e9-8c74-9bac4d6e4435.png)

My flow is typically:
* click on SCM view
* click on stages files for diffing
* click back on explorer

**Comment by bpasero** [comment]
Possibly related: in this case when I close all files that are open and click on the explorer, there is no file selected. So maybe I had no selection in the explorer? But previously I think we always had a pointer to the last opened file independent from selection/focus in the tree.

**Comment by isidorn** [comment]
I can not repro this.
Also I believe that us aligning selection and focus should take care of this.
Thus closing. Please let me know if you still see this from wednesday and than we can reopen and investigate what is going on.
