### ISSUE TITLE
Special case for index files - only display parent folder name in tabs

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#67974]
related [Provide an option to always show parent folder for files in tabs #12965](https://github.com/Microsoft/vscode/issues/12965) However, I like my tabs concise so I keep `labelFormat=default`

/edit
[Provide API to access and change editor tab labels #41909](https://github.com/Microsoft/vscode/issues/41909)
This issue is somewhat related, but my proposal does not require a feature rich API. Instead, another option for `labelFormat` could be introduced for this solution.

---

The `index` pattern is very much valid and also pretty common. The module system supports it out of the box, so I keep wondering why there already isn't an official IDE support for it in the wide world (not only VSCode).

**So I would like to take this further and remove all those `index`es altogether.**

BEFORE:
![image](https://user-images.githubusercontent.com/2313018/52339335-17939480-2a0d-11e9-9871-f8a770c39937.png)

AFTER:
**16% shorter**
![image](https://user-images.githubusercontent.com/2313018/52339344-1b271b80-2a0d-11e9-9c2e-3a2e6beb0586.png)

`index.tsx ..\Container` becomes `tsx Container`
`index.css` becomes `css Container` <- this here is a special case as the `labelFormat=default` won't show parent folder name if there is no other `index.css` file open.
`index.react.js ..\AFolder` should perhaps become `react.js AFolder`

_note: This substitution **really only** occurs when the file name starts with `index.`_

With this change, when searching, a matching index file should be displayed as top result, since the index file really represents the folder if no file is specified.
![image](https://user-images.githubusercontent.com/2313018/52340114-398e1680-2a0f-11e9-9866-d38353b218c8.png)

EXTRA:
before
![image](https://user-images.githubusercontent.com/2313018/52339892-a9e86800-2a0e-11e9-81e7-e3c30f653d03.png)

after # 1 - _preferred_
![image](https://user-images.githubusercontent.com/2313018/52339893-abb22b80-2a0e-11e9-8d4d-92c19be1735f.png)

after # 2 - _if someone prefers to index by the alphabet_
![image](https://user-images.githubusercontent.com/2313018/52339983-e320d800-2a0e-11e9-80a3-e80a72ed6a9a.png)

**Comment by mjbvz** [comment]
Good proposal. 

I don't think we want to hardcode a js/ts specific solution into the core editor, so #41909 would allow an extension to provide this functionality
