### ISSUE TITLE
VSCode takes ages to startup up on 16GB ram PC but starts in seconds on 8GB ram pc

### ISSUE THREAD

**Issue by CookieCrumbles** [Microsoft/vscode#67977]
- VSCode Version: 1.30.2

OS: | Windows 10 Enterprise  (64 bit)
Build: | 10.0.16299.904
Version: | 1709

Hardware specs:

Memory: | 8 GB
Processor: | Intel Core i5-8250U CPU @ 1.60GHz
Motherboard: | HP 83B2

So i have 2 cleans pc's with a basic configuration (portable version) of the latest VS code.
I have 2 identical computers a part from the amount of memory.
The computer with only 8GB of Ram opens VS Code in a matter of seconds whereas the powerful computer with 16 GB (same CPU and MOBO) takes minutes, 3 to 5 !

Is there a fix for this ? My main machines has 16 GB so this is an issue for me.
My older version 1.25 fires up in seconds on the 16GB machines so i'm using that as a "solution". But since i code mainly powershell i now can't update the PS extension.

Edit :
i have no extensions installed.
Yes this is also the case on the latest insider version

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by CookieCrumbles** [comment]
Thanks i posted a performance issue via that way : https://github.com/Microsoft/vscode/issues/67986
