### ISSUE TITLE
emmet always places lorem child first

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#67971]
Issue Type: <b>Bug</b>

Use emmet to expand "div>p+lorem3". It should expand to (according to docs.emmet.io)
```
<div>
  <p></p>Lorem ipsum dolor.
</div>
```
Or even better:
```
<div>
  <p></p>
  Lorem ipsum dolor.
</div>
```
Instead, it expands to
```
<div>
  Lorem, ipsum dolor.
  <p></p>
</div>
```

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vscode-test-explorer|hbe|2.4.0
live-html-previewer|hdg|0.3.0
cmake-tools-helper|mad|0.2.1
autoconf|mae|0.0.7
vscode-catch2-test-adapter|mat|2.3.16
python|ms-|2019.1.0
cpptools|ms-|0.21.0
LiveServer|rit|5.3.1
vscode-icons|rob|8.1.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by rzhao271** [comment]
\closedWith dc5a3da
