### ISSUE TITLE
Minimizing the bottom function of a file leaves a giant gap at the bottom.

### ISSUE THREAD

**Issue by dxf** [Microsoft/vscode#67978]
Issue Type: <b>Bug</b>

To reproduce:
Make a big file full of functions (mine is ~175 lines of Python)
Collapse the bottom one
Witness massive gap. 
Gif/Jif/Graphics Interchange format: https://downloadmoredownloads.download/i/ohff.gif

Expected behaviour:
Lines disappear until function is maximised again in which they are filled with code

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.6.3
gc-excelviewer|Gra|2.1.28
python|ms-|2019.1.0
material-icon-theme|PKi|3.6.2

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@dxf there is a setting for that called "Editor: Scroll beyond last line" (editor.scrollBeyondLastLine). It's `true` by default. Set it to false.
