### ISSUE TITLE
Format on Save breaks Template Literal Variables

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/vscode#67989]
- VSCode Version: Version 1.30.2 (1.30.2)
- OS Version: macOS Mojave 10.14.3 (18D42)

Steps to Reproduce:

1. Create a template literal with a variable `<h1>${msg}</h1>`
2. Save document.
3. Format on save converts this to: `<h1>$ {msg}</h1>` (Notice the space between the dollar sign and the curly brace. This means that of course the template literal doesn't work as expected.

Although I can avoid this by turning off Format on Save in Settings, I'd like to use the feature. Unfortunately there is no way to control what gets formatted. Not sure why you choose to separate the dollar sign from curly braces since this is the only way to designate a variable when using template literals.

**Comment by kieferrm** [comment]
@rbiggs in a `ts` file?  Which extensions have you installed?

**Comment by rbiggs** [comment]
It's a `.js` file. Template literals are just JavaScript.

**Comment by rbiggs** [comment]
The format `${variable}` is used to define template literal variables in ES6. These don't get compile during build time but interpreted by the browser. So separating the dollar sign from the following curly brace means the browser doesn't know what it is an can't interpolate the value. Hope that's clear.

**Comment by rbiggs** [comment]
The thing is, I use Prettier for formatting in my build, and it doesn't do this. It leaves the template literals alone.

**Comment by rbiggs** [comment]
By the way, even with all extensions turned off it continues to break things.

**Comment by rbiggs** [comment]
Here is an image of before save:
<img width="587" alt="screen shot 2019-02-06 at 10 43 45 am" src="https://user-images.githubusercontent.com/249218/52365454-61c04a00-29fc-11e9-82e1-bfae45f18b3a.png">
And after save:
<img width="587" alt="screen shot 2019-02-06 at 10 44 34 am" src="https://user-images.githubusercontent.com/249218/52365460-67b62b00-29fc-11e9-9ad2-7c33f34c4481.png">

**Comment by mjbvz** [comment]
@rbiggs I can't repo this. Are you sure have no active extensions? Can you please share some example code that demonstrates this issue (as text, not screenshots)

**Comment by rbiggs** [comment]
VSCode Version 1.30.2 had this problem. However, it looks like VSCode Version 1.31.0 fixed this problem--with and without extensions running.
