### ISSUE TITLE
breakpoint position is incorrect.

### ISSUE THREAD

**Issue by fantasy525** [Microsoft/vscode#67987]
version: 1.30.2 (user setup)
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.
![break](https://user-images.githubusercontent.com/22516157/52353100-d9c45980-2a68-11e9-82fc-e7a12bd62f3e.gif)

2. I set breakpoint at line 29 ,but red breakpoint  appears at line 66.

**Comment by weinand** [comment]
What debugger are you using?

**Comment by fantasy525** [comment]
> What debugger are you using?

vscode-react-native.
Although the location is not correct, the debug program running correctly
![break](https://user-images.githubusercontent.com/22516157/52355786-f8791f00-2a6d-11e9-8bfd-6471e0b0d5b6.gif)
