### ISSUE TITLE
Badge using incorrect foreground color in filter input on Problems Panel

### ISSUE THREAD

**Issue by jacobcassidy** [Microsoft/vscode#67983]
Issue Type: <b>Bug</b>

When adding text to the filter input on the Problems Panel, it will show a badge when it finds a match, such as "Showing 1 of 2". The background color of this badge is pulled from the "badge.background": property, but the foreground color is not being pulled from the "badge.foreground": property like all the other inputs (e.g., User Settings search input badge). Instead, it is using the default base "foreground": property. 

This causes an issue when the base foreground is light (as it will be on any dark theme) and the badge background color is also light.

The solution is to have this badge pull the foreground color from the "badge.foreground": property (ideal), or add a property that allows this badge to override the default "foreground": property.

<b>STEPS TO REPRODUCE:</b>

1. Open the Problems Panel (Menubar > View > Problems).
2. Create 2 or more of the same type of errors in any file in the editor so the errors will show in the Problems Panel (see screenshot for example of 2 errors of the same type showing).
3. Add a word to the Problems Panel filter input that matches a word in the error message.
4. Badge will show in the right of the filter input when the filter matches a 2 or more words in the error message (panel window width needs to be wider than 1240px or the badge will not show).

![screenshot_of_problem_panel](https://user-images.githubusercontent.com/1895973/52345927-f6ed2e00-2a50-11e9-96ab-5961f61b5077.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

**Comment by sandy081** [comment]
To verify use the `"badge.foreground": "#ff0000"` colour in settings and make sure it is applied in problems panel filter badge

**Comment by jacobcassidy** [comment]
No change detected after updating to release 1.31.0. The problems panel filter badge is still pulling its foreground from the base "foreground": property.

![screenshot of update](https://user-images.githubusercontent.com/1895973/52383388-b8389180-2aab-11e9-8463-1ec42335a0a4.png)

**Comment by sandy081** [comment]
@jacobcassidy It will be available in 1.32 (February) release. You can start using our insiders if you want to have the fix immediately - https://code.visualstudio.com/insiders/

**Comment by jacobcassidy** [comment]
@sandy081 thanks for clarifying. I downloaded the insiders version and it is indeed working correctly now.
