### ISSUE TITLE
.htaccess not work on Live Server

### ISSUE THREAD

**Issue by viditvarshney** [Microsoft/vscode#67995]
### When the .htaccess is created to access the 404 error page  and removal of the extension in address bar .
It doesn't work on the Live Server of the Vs Code  ..
- version of vs code --> 1.30.2
- OS --> Windows
- live server by ritwikdev  and one more from ritiwikdev

**now what i expect from the live server that : when i attached the `.htaccess` file to my code to redirect to the 404 error Page and remove the extensions from the address bar , it should do this thing but unfortunately it don't**

> SO why this happens , as we are on the live server which have my whole project 

-  as i upload the project to the Github and  check my Website it works great

**Comment by viditvarshney** [comment]
see the edited issue @kieferrm

**Comment by viditvarshney** [comment]
@kieferrm  Remove the label

**Comment by kieferrm** [comment]
Please move the issue to the LiveServer extension. Thanks!
