### ISSUE TITLE
Public directory doesnt show files in file explorer

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#67993]
- VSCode Version: 1.30.2
- OS Version: macOS Mojave 10.14.2

Description: My public folder used to be able to show the contents within in. It is not many files either. Currently though, every time I attempt to open the public folder in the file explorer tree view it shows nothing. All the other directories are working fine and opening. When I check finder to verify that the files are there they are. I have verified in my settings and workspace settings that I am not excluding it in the 'files.exclude' setting. Again, this was working a couple days ago but currently isnt.

Steps to Reproduce:

1. Have a public folder
2. Have a few files and sub directories in that folder.
3. Notice that it is not showing the contents of that folder when attempting to expand it.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/6380855/52359285-38ed8400-29ff-11e9-8460-138f5969ec7b.png)

![image](https://user-images.githubusercontent.com/6380855/52359403-73efb780-29ff-11e9-975e-7f16b65a38b0.png)

### **_UPDATE_**
I was able to get it to show again because the developer console showed this error that was specific to a folder inside. After removing that directory, they started showing again. This should probably still be looked into

![image](https://user-images.githubusercontent.com/6380855/52360057-c1205900-2a00-11e9-9499-fe857847df6a.png)

**Comment by imoby** [comment]
Posted an update in the description

**Comment by bpasero** [comment]
This could be related to permissions on macOS 10.14.x mojave and nothing we can do about.

@imoby is there anyoutput in the logs?

**Comment by imoby** [comment]
are you referring to the console logs in dev tools? @bpasero

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by imoby** [comment]
I'm closing this since I no longer see this issue after upgrading to the latest
