### ISSUE TITLE
Code is asking to save files that I don't have open

### ISSUE THREAD

**Issue by robunoki-microsoft** [Microsoft/vscode#67994]
Issue Type: <b>Bug</b>

I'm not sure what's going on, but sometimes VS Code will ask me to save files that I don't have open when I'm closing all windows or exiting Code.  Happens sporadically. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz (16 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (24.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|1.1.190128002
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
ninja|sur|0.0.1
cmake|twx|0.0.17

</details>

**Comment by robunoki-microsoft** [comment]
I think VS Code may be opening files that were previously open - but I can't see all of them.  The ones I can see are empty (and if I save them I lose all the changes that were not committed).

**Comment by kieferrm** [comment]
@robunoki-microsoft same happens when you disable the extensions you have installed? 
```
code --disable-extensions
```?
