### ISSUE TITLE
All extensions stopped working after 02-06 update

### ISSUE THREAD

**Issue by wilfredinni** [Microsoft/vscode#67999]
Issue Type: <b>Bug</b>

Updated and every extension stopped working

Notification when vscode is open: 
![captura de pantalla 2019-02-06 a la s 16 32 54](https://user-images.githubusercontent.com/23016174/52368383-065a8000-2a2d-11e9-85b1-4a200fe111a1.png)
Extension host terminated unexpectedly.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
better-toml|bun|0.3.2
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
prettier-vscode|esb|1.8.1
pyre-vscode|fb-|0.0.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
markdown-shortcuts|mdi|0.10.1
python|ms-|2019.1.0
autodocstring|njp|0.2.3
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.2
LiveServer|rit|5.3.1
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.10
vscode-djaneiro|the|1.4.2
quokka-vscode|Wal|1.0.182
vscode-todo-highlight|way|1.0.4
markdown-pdf|yza|1.2.0
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

![captura de pantalla 2019-02-06 a la s 16 27 30](https://user-images.githubusercontent.com/23016174/52368175-93e9a000-2a2c-11e9-8e92-a3b6b7a02c75.png)
![captura de pantalla 2019-02-06 a la s 16 28 33](https://user-images.githubusercontent.com/23016174/52368176-94823680-2a2c-11e9-9bec-36441271d33f.png)
![Uploading Captura de pantalla 2019-02-06 a la(s) 16.30.07.png…]()

**Comment by kieferrm** [comment]
One of your installed extensions takes down the extension host. Pls try with `code --disable-extensions` first. This disables the external extensions but leaves the built-in extensions enabled. See if you then can open the markdown preview. Thanks!

**Comment by patrickblackjr** [comment]
Same issue

**Comment by wilfredinni** [comment]
Seems to be the Live Server extension
![Live Server extension](https://user-images.githubusercontent.com/23016174/52369622-e1b3d780-2a2f-11e9-8b3e-588be71ccff4.png)

**Comment by MarkPolivchuk** [comment]
Disabling Live Server fixed the issue for me

**Comment by MarkupUa** [comment]
> Disabling Live Server fixed the issue for me

But I need Live Server

**Comment by MarkupUa** [comment]
need use old version
https://code.visualstudio.com/updates/v1_30

**Comment by linda-lai** [comment]
Confirming not working for me with latest release, disabling Live Server in the interim as a workaround is a good temporary fix.

**Comment by jousmo** [comment]
Live Server and Ftp-Simple not working.

**Comment by nerdmax** [comment]
Disable live-server works for me.

**Comment by krupenja** [comment]
Workaround n comments here https://github.com/ritwickdey/vscode-live-server/issues/273
Basically, you need to install a new version of vscode-live-server from their releases page

**Comment by ritwickdey** [comment]
I've published LiveServer@5.4.0 to marketplace. Please try to upgrade it

**Comment by nerdmax** [comment]
> I've published LiveServer@5.4.0 to marketplace. Please try to upgrade it

Updating live-server to @5.4.0 fixes the issue.

**Comment by wilfredinni** [comment]
> I've published LiveServer@5.4.0 to marketplace. Please try to upgrade it

Thanks! works perfectly now.

**Comment by MarkupUa** [comment]
All ok now. :)
Thanks!
