### ISSUE TITLE
[Extension API] Make it possible to remove current selections

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#680]
I would like to experiment with an extension that removes a selection (provided there are multiple selections active). I don't think that's possible with the current [api](https://code.visualstudio.com/docs/extensionAPI/vscode-api).

I want to do something like this:

```js
var textEditor = vscode.window.activeTextEditor;
var selections = textEditor.selections;
if (selections.length > 1) {
  textEditor.removeSelection(selections[selections.length - 1]);
}
```

**Comment by jrieken** [comment]
It is, by just setting a different selection array

Remove the first selection:
```
var textEditor = vscode.window.activeTextEditor;
var selections = textEditor.selections;

textEditor.selections = selections.slice(1);
```

**Comment by Tyriar** [comment]
Thanks, I assumed it was readonly.

**Comment by jrieken** [comment]
In general readonly properties have the `@readonly` jsdoc tag
