### ISSUE TITLE
[1.31] .deb package is not working

### ISSUE THREAD

**Issue by Torvaldi** [Microsoft/vscode#68008]
- VSCode Version: 1.31
- OS Version: Ubuntu 18.04.1 LTS on Linux 4.15.0-45-generic

Steps to Reproduce:

1. Download .deb package form official website
2. Run `sudo dpkg -i vscode.deb`

The .deb package seems to be not complete, with a weight of 3.3Mo.

**Comment by Tyriar** [comment]
I'll tell the Linux repo team, might be a regional problem.

**Comment by Torvaldi** [comment]
I'm from France if it can be helpful 🙂

**Comment by mbearup** [comment]
I checked all the mirrors and the file size/hashsum is the same on all mirrors. 
1. Could you clarify what you mean by "official website? Is it packages.microsoft.com?"
2. Could you do an nslookup of whatever server you're fetching this from (presumably packages.microsoft.com)?
Thanks,

**Comment by Torvaldi** [comment]
I'm downloading from https://code.visualstudio.com, and I have checked with my 4G to with the same result even if I am on another computer

**Comment by Tyriar** [comment]
The official website is https://code.visualstudio.com, which looks like it points at our update server:
 
![image](https://user-images.githubusercontent.com/2193314/52377371-84ad2700-2a19-11e9-95f2-97dcb2f0df9a.png)

@mbearup sorry about the ping, probably a problem on our side.

@octref any ideas why someone may not be able to download a file from the update server from France?

**Comment by octref** [comment]
@joaomoreno Manages the update server. I just tried downloading it, the deb file is 48.7MB for me.

@Toliveira97 Does opening https://update.code.visualstudio.com/1.31.0/linux-deb-x64/stable download the correct file for you?

**Comment by Torvaldi** [comment]
I have this files from the 2 download sources 
![screenshot_20190206-232642_crop_540x172](https://user-images.githubusercontent.com/7703951/52378162-44749580-2a67-11e9-8a40-33767613f91d.jpg)

**Comment by Tyriar** [comment]
Similar report https://github.com/Microsoft/vscode/issues/68009

**Comment by Tyriar** [comment]
@joaomoreno the update server doesn't appear to be sending the full file. OP is based on France.

**Comment by joaomoreno** [comment]
@Tyriar Our files come from a CDN, which the update server forwards requests to.

@Torvaldi If you run

```
wget https://update.code.visualstudio.com/1.31.0/linux-deb-x64/stable
```

Do you get more than 3MB?

**Comment by Torvaldi** [comment]
@joaomoreno Yes I keep getting a 3,30Mo package...

**Comment by joaomoreno** [comment]
Right. So it's a network problem. I suggest you investigate what is going on in your system/network that the request is simply cut off.

**Comment by alacambre-yseop** [comment]
Same problem here. I'm in France too.

**Comment by joaomoreno** [comment]
Here's what I see: 

```
$ wget https://update.code.visualstudio.com/1.31.0/linux-deb-x64/stable
--2019-02-07 13:29:23--  https://update.code.visualstudio.com/1.31.0/linux-deb-x64/stable
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 104.42.78.153
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|104.42.78.153|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://az764295.vo.msecnd.net/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb [following]
--2019-02-07 13:29:24--  https://az764295.vo.msecnd.net/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb
Resolving az764295.vo.msecnd.net (az764295.vo.msecnd.net)... 152.199.19.160
Connecting to az764295.vo.msecnd.net (az764295.vo.msecnd.net)|152.199.19.160|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48713574 (46M) [application/x-debian-package]
Saving to: ‘stable’

stable                              100%[================================================================>]  46.46M   104MB/s    in 0.4s    

2019-02-07 13:29:24 (104 MB/s) - ‘stable’ saved [48713574/48713574]
```

**Comment by alacambre-yseop** [comment]
Here, for me: ↓
![image](https://user-images.githubusercontent.com/15327919/52413188-277ca880-2ae1-11e9-9ac9-ee329686daca.png)

**Comment by marob** [comment]
What is the expected md5sum?
On my end, I have the same corrupted .deb file with the following md5sum: 42f6d50af5a5b983ccef4de5c04c292b

**Comment by JCAguilera** [comment]
I got 1.87M from Chile:

![code_1 31](https://user-images.githubusercontent.com/20048847/52415582-1b372200-2ac6-11e9-892c-1dd59519a2fc.png)

**Comment by Torvaldi** [comment]
@joaomoreno I've tried on 3 different networks, connected to 3 different devices, same thing appears

**Comment by joaomoreno** [comment]
@Torvaldi Can you show me how you used 3 different locations?

**Comment by Torvaldi** [comment]
1. My personal computer, connected to Internet with Bouygues Telecom
2. My phone as you can see a little bit above
3. In my school, where I have tested on a Debian computer this morning

**Comment by joaomoreno** [comment]
So, all from France, got it. Let me run some tests as well.

**Comment by joaomoreno** [comment]
Hm just created two VMs: one in France, another in Brazil. Both location report a correct size when downloading... 🤔

**Comment by joaomoreno** [comment]
- @JCAguilera gets 1965598 bytes
- @alacambre-yseop gets 3456435 bytes

@Torvaldi Can you show me the full output of wget?

**Comment by JCAguilera** [comment]
I used a [free VPN](https://chrome.google.com/webstore/detail/betternet-unlimited-free/gjknjjomckknofjidppipffbpoekiipm) to download the file, I set the location to Canada and it worked.

**Comment by Torvaldi** [comment]
@joaomoreno Here is the output of the wget : 
```--2019-02-07 17:51:38--  https://update.code.visualstudio.com/1.31.0/linux-deb-x64/stable
Résolution de update.code.visualstudio.com (update.code.visualstudio.com)… 51.144.164.215
Connexion à update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 Found
Emplacement : https://az764295.vo.msecnd.net/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb [suivant]
--2019-02-07 17:51:38--  https://az764295.vo.msecnd.net/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb
Résolution de az764295.vo.msecnd.net (az764295.vo.msecnd.net)… 152.199.19.160
Connexion à az764295.vo.msecnd.net (az764295.vo.msecnd.net)|152.199.19.160|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 3456435 (3,3M) [application/x-debian-package]
Enregistre : «stable»

stable                                              100%[================================================================================================================>]   3,30M   622KB/s    ds 5,3s    

2019-02-07 17:51:44 (639 KB/s) - «stable» enregistré [3456435/3456435]
```
And here the sha1sum : `97b0ba2cba287470807e63445e819573734c2f72  stable`

**Comment by Torvaldi** [comment]
@JCAguilera @joaomoreno When I use the VPN connected in Canada, the file seems to be good... A nslookup on update.code.visualstudio.com returns that : 
```> 51.144.164.215
** server can't find 215.164.144.51.in-addr.arpa: NXDOMAIN
> update.code.visualstudio.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
update.code.visualstudio.com	canonical name = vscode-update.trafficmanager.net.
vscode-update.trafficmanager.net	canonical name = vscode-update-westeurope.azurewebsites.net.
vscode-update-westeurope.azurewebsites.net	canonical name = waws-prod-am2-193.sip.azurewebsites.windows.net.
waws-prod-am2-193.sip.azurewebsites.windows.net	canonical name = waws-prod-am2-193.cloudapp.net.
Name:	waws-prod-am2-193.cloudapp.net
Address: 51.144.164.215
```

**Comment by mbearup** [comment]
Looks like a CDN (msecnd.net) is being used in France, where azure websites are being used in Canada. It's possible that the CDN has a "bad" file stuck in it's cache. One trick you can try is wget's `--no-cache` option which (assuming the CDN uses a lazy cache) forces it to get a fresh copy from origin.
When I download from msecnd.net (in Western US) I get the 48MB file. So it seems like the CDN is at least aware of the right file.
```bash
$ wget https://az764295.vo.msecnd.net/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb
--2019-02-07 09:42:32--  https://az764295.vo.msecnd.net/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb
Resolving az764295.vo.msecnd.net (az764295.vo.msecnd.net)... 152.199.4.33
Connecting to az764295.vo.msecnd.net (az764295.vo.msecnd.net)|152.199.4.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48713574 (46M) [application/x-debian-package]
Saving to: ‘code_1.31.0-1549443364_amd64.deb’

100%[=====================================================================================================================================================================>] 48,713,574  46.5MB/s   in 1.0s

2019-02-07 09:42:33 (46.5 MB/s) - ‘code_1.31.0-1549443364_amd64.deb’ saved [48713574/48713574]
```

**Comment by Torvaldi** [comment]
Unfortunately, the --no-cache option doesnt solve the problem

**Comment by mbearup** [comment]
Yeah, the CDN may not use a "lazy" cache unfortunately :(
- Your VPN workaround is one way to get around this
- Another hacky workaround is to edit your /etc/hosts file so that `az764295.vo.msecnd.net` points to a "good" server elsewhere in the world (e.g. `152.199.4.33`).  
But the real fixes are *server side*. Either:
1. Modify `update.code.visualstudio.com` to use `vscode-update.trafficmanager.net` in Europe, as it does in the US (to work around the CDN issue). 
2. Reach out to the CDN team to investigate their endpoint at `152.199.19.160`

**Comment by cedx** [comment]
Exactly the same issue here using two different locations: my workstation in France, and my dedicated server in Netherlands.

```shell
$ curl -L -o vscode.deb https://go.microsoft.com/fwlink/?LinkID=760868
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   187  100   187    0     0    172      0  0:00:01  0:00:01 --:--:--     0
100   133  100   133    0     0    103      0  0:00:01  0:00:01 --:--:--   103
100 3375k  100 3375k    0     0  1631k      0  0:00:02  0:00:02 --:--:-- 5221k
```

**Comment by aurelien-reeves** [comment]
Same issue for me.
I am in France too.

```shell
$ curl -L -o vscode.deb https://go.microsoft.com/fwlink/?LinkID=760868
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   187  100   187    0     0    185      0  0:00:01  0:00:01 --:--:--   185
100   133  100   133    0     0     74      0  0:00:01  0:00:01 --:--:--   271
100 3375k  100 3375k    0     0  1420k      0  0:00:02  0:00:02 --:--:-- 9669k
```

**Comment by joaomoreno** [comment]
@cedx Can you show me the full output of wget? Also, can you sha1sum the downloaded file?

**Comment by joaomoreno** [comment]
@Torvaldi After downloading the deb on my machine, I truncated it to the 3456435 bytes and verified I got the same sha1sum as you.

I'll reach to our CDN guys and see what's up.

**Comment by joaomoreno** [comment]
I've issued a CDN purge on `/stable/7c66f58312b48ed8ca4e387ebd9ffe9605332caa/code_1.31.0-1549443364_amd64.deb`. Let me know during the course of the day whether anything changes.

**Comment by Torvaldi** [comment]
It seems to work now

**Comment by marob** [comment]
I confirm, it's fixed on my side too.

**Comment by Torvaldi** [comment]
The link provided in the vscode website is not actualized everywhere but the wget works fine now, thank you !

**Comment by cedx** [comment]
Issue fixed on my two machines (France + Netherlands) :+1:

**Comment by joaomoreno** [comment]
Great to know! Thanks for understanding guys.
