### ISSUE TITLE
AltGr+ is no longer Ctrl+Alt+ starting with 1.31

### ISSUE THREAD

**Issue by youssefhad** [microsoft/vscode#68003]
Issue Type: <b>Bug</b>

vscode reset my keyboard shortcuts after 1.31 upgrade

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
vscode-database|baj|1.5.3
spellright|ban|3.0.22
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|9.5.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
beautify|Hoo|1.4.8
vscode-icon-theme|jtl|1.6.5
php-symbols|lin|2.1.0
code-beautifier|mic|2.1.0
vscode-language-pack-fr|MS-|1.31.4
material-icon-theme|PKi|3.6.2
live-sass|rit|3.0.0
LiveServer|rit|5.3.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.4
vscode-todo-highlight|way|1.0.4
vinala-ext|You|0.2.6
file-size|zh9|0.1.3

(1 theme extensions excluded)

</details>

**Comment by Acelator** [comment]
It happens to me too

**Comment by youssefhad** [comment]
i guess the shortcuts starting with alt gr doesn't work

**Comment by Acelator** [comment]
Yes I have just tried it, and I can't use shortcuts starting with alt gr but with alt everything is perfect

**Comment by mdmazzotti** [comment]
I can confirm alt gr shortcuts don't work anymore

**Comment by rebornix** [comment]
Keyboard events from Chromium on Windows changed after we upgraded from Electron 2.x to 3.x

Tiny script to reproduce this issue
```javascript
document.body.addEventListener('keydown', logKey);
function logKey(e) {
  console.log(e)
}
```
On Electron 2.0.8, pressing AltGr generates below keyboard event, `altKey` and `ctrlKey` are both true

```
KeyboardEvent {
	altKey : true
	bubbles : true
	cancelBubble : false
	cancelable : true
	charCode : 0
	code : "AltRight"
	composed : true
	ctrlKey : true
	currentTarget : null
	defaultPrevented : true
	detail : 0
	eventPhase : 0
	isComposing : false
	isTrusted : true
	key : "AltGraph"
	keyCode : 18
	location : 2
	metaKey : false
	repeat : false
	returnValue : false
	shiftKey : false
	type : "keydown"
}
```

On Electron 3, pressing AltGr generates below keyboard event, `altKey` and `ctrlKey` are both false

```
KeyboardEvent {
	altKey : false
	bubbles : true
	cancelBubble : false
	cancelable : true
	charCode : 0
	code : "AltRight"
	composed : true
	ctrlKey : false
	currentTarget : null
	defaultPrevented : true
	detail : 0
	eventPhase : 0
	isComposing : false
	isTrusted : true
	key : "AltGraph"
	keyCode : 18
	location : 2
	metaKey : false
	type : "keydown"
}
```

Related chromium code change https://www.chromestatus.com/feature/5059438092222464 , https://bugs.chromium.org/p/chromium/issues/detail?id=25503, they did this by purpose to align with other OS so `AltGr` no longer behaves the same way as `Ctrl+Alt`. @alexandrudima knows if we can call it a breaking change or a bug.

**Comment by roni** [comment]
I can confirm this too.

It it not just that `AltGr` is not recognised as `Ctrl + Alt` it is recognised as a weird `Alt`. When one tries to make new shortcuts and presses `AltGr` VSCode inputs as `Alt` + but all subsequent keypresses reset this to the new key press, For example `AltGr` + `e` yields `e`.

**Comment by alexandrudima** [comment]
We don't plan to do anything here. `AltGr+` is no longer `Ctrl+Alt+` and we will just live with this.
