### ISSUE TITLE
[VSCode 1.31] ES2018 RegExp lookbehind assertions are now supported

### ISSUE THREAD

**Issue by ExE-Boss** [Microsoft/vscode#68004]
As&nbsp;a&nbsp;result of&nbsp;moving to&nbsp;**Electron&nbsp;3.0**, `RegExp` lookbehind assertions are now supported, since they’re supported since **Chromium&nbsp;62** and&nbsp;**Node&nbsp;8.10.0**, and&nbsp;**Electron&nbsp;3.0** uses&nbsp;**Chromium&nbsp;66** and&nbsp;**Node&nbsp;10.2.0**, so&nbsp;they’re&nbsp;now&nbsp;supported, but&nbsp;the&nbsp;[release&nbsp;notes](https://code.visualstudio.com/updates/v1_31) don’t&nbsp;mention that&nbsp;lookbehind&nbsp;assertions are&nbsp;now&nbsp;supported.

**Comment by roblourens** [comment]
You're right, I even tweeted about it back in December. But since I didn't have an issue about it, I completely forgot to mention it in the release notes.

**Comment by ExE-Boss** [comment]
So, is&nbsp;it&nbsp;going to&nbsp;be&nbsp;added to&nbsp;the&nbsp;release notes?

**Comment by roblourens** [comment]
Maybe, we don't usually edit them after releasing (but we don't usually forget about features either)
