### ISSUE TITLE
passing a non-existing launch config to 'vscode.startDebug' does not return an error

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6800]
While testing https://github.com/Microsoft/vscode/issues/6248:

- VSCode Version: 1.1.0 alpha
- OS Version: OS X

Passing a non existing launch config name to the 'vscode.startDebug' command does not result in an error but launches the first launch config instead.

Since the 'vscode.startDebug' command has become part of our 'official' API, we have to protect ourselves against incorrect values and we have to produce meaningful errors.

**Comment by isidorn** [comment]
This is now fixed, as the first launch config is not launched but the action is just ignored.
There is still issue #6809 that errors are not propagated properly - looking into that one now

**Comment by weinand** [comment]
@isidorn just make sure that the error message passed to the following error handler is something like "launch config 'foobar' doesn't exist": 

```ts
    vscode.commands.executeCommand('vscode.startDebug', 'foobar').then(() => {
        vscode.window.showInformationMessage('OK!');
    }, err => {
        vscode.window.showInformationMessage('Error: ' + err.message);
    });
```
