### ISSUE TITLE
Explorer open by arrow not working

### ISSUE THREAD

**Issue by amarchino** [Microsoft/vscode#68010]
- VSCode Version: 1.31.0 (user setup)
- OS Version: Windows 10 Professional, version 1809, build 17763.292

Steps to Reproduce:

1. In Settings, set the option `workbench.list.openMode` to `doubleClick`
2. Try to open a folder in the Explorer view by clicking once the little 'arrow head' next to folder name

Does this issue occur when all extensions are disabled?: Yes

Previous VSCode versions allows the folder to be opened, even in doubleClick mode, by simply clicking once on the little 'arrow head' next to the folder name.
This no longer seems to work, for I need to click twice on the folder to actually open it.
Maybe this was done to parallelize the user experience with the double click required to open the folder by clicking on its name.

On the same page, clicking twice on the 'arrow head' opens the folder only most of the times. Not always. Yet I'm doubtful whether this should be a separate issue: in such case, I ask for forgiveness and will open a new issue.

**Comment by bpasero** [comment]
I assume this is tree specific @joaomoreno
