### ISSUE TITLE
precommit hook should give diff when file not formatted

### ISSUE THREAD

**Issue by flurmbo** [Microsoft/vscode#68017]
When making a commit from the command line to my local copy of the vscode source, sometimes I'll get an error saying that a file is not formatted correctly. This originates from [this line](https://github.com/Microsoft/vscode/blob/4e0537740332cb432c9a17ed1a7c23f11635612b/build/gulpfile.hygiene.js#L231) of `build/gulpfile.hygiene.js`. It would be nice if at that point it logged a diff of `original` and `formatted`. 

It also appears that these linting issues are not being caught by the task defined in tasks.json. I'm not really sure about that though since I've been getting ENOSPC errors on my machine when working in vscode, so I might be having this issue because those tasks aren't running.

**Comment by alexr00** [comment]
@joaomoreno, do you own the hygiene file?

**Comment by joaomoreno** [comment]
@flurmbo Just run <kbd>F1</kbd>, `Format Document`. No need to look at diffs.
