### ISSUE TITLE
File name "did you mean"s

### ISSUE THREAD

**Issue by fifn2** [Microsoft/vscode#68014]
When I'm naming a file, I commonly misspell the name. For example, the prettier config file is named ".prettierrc", and I frequently name the file ".prettierc" (without the extra r). I think that if I create a file with no configured grammar association and that file's name closely matches a filename that has an association. For example, when I create a file called "pacage.json", I should get a dialog in the bottom right that says "Did you mean _package.json_?".

**Comment by usernamehw** [comment]
Don't you file icon theme that applied as you type?

![file_name](https://user-images.githubusercontent.com/9638156/52379197-d508a100-2a7a-11e9-921f-96a353fc0544.gif)

**Comment by fifn2** [comment]
I do, but sometimes I `touch` them, or I press enter by accident, and I make typos. I kind of forgot to mention this part, but I think that this should work with not just configured languages, but with common file types, like `gulpfle.js` correcting to `gulpfile.js`.

**Comment by usernamehw** [comment]
IDK, Have you tried CLI aliases?
```ini
glp=touch gulpfile.js
pck=touch package.json
```
