### ISSUE TITLE
CMD+Return/CMD+Down on search result no longer focuses editor

### ISSUE THREAD

**Issue by scarlac** [Microsoft/vscode#68018]
Issue Type: <b>Bug</b>

After Feburary update it's no longer possible to keyboard navigate from a search result into the editor area. This means that doing a Find in Files search can no longer be performed with keyboard only. It's possible to Open Results in Side view but not open in active view.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.58GB free)|
|Process Argv|-psn_0_4092903|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
vscode-eslint|dba|1.8.0
json-pretty-printer|eus|1.1.0
graphql-for-vscode|kum|1.13.0
mssql|ms-|1.4.0
csharp|ms-|1.17.1
Go|ms-|0.9.0
sublime-keybindings|ms-|4.0.0
color-highlight|nau|2.3.0

</details>

**Comment by roblourens** [comment]
In 1.30 I see it focus the editor with just 'enter' or 'cmd+down' but not 'cmd+enter', is that right?

You can use a workaround like 'cmd+1' to focus the editor in the meantime.

**Comment by scarlac** [comment]
@roblourens Sorry, I may have different keybindings. Both Return, CMD+Down, and CMD+Enter does not work to focus the text field. 
CMD+1 doesn't work well as a workaround, as it makes changes focused line away from the highlighted search result.

**Comment by josh08h** [comment]
I've encountered the same issue in `Version 1.31.0`.

I've bound `enter` to the following:
```
{
        "key": "enter",
        "command": "list.select",
        "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
    }
```

`list.select` no longer focuses the editor.

**Comment by roblourens** [comment]
FYI @joaomoreno @isidorn this is goes back to https://github.com/Microsoft/vscode/issues/64743 and the tree resource navigator vs open event, etc.

My proposed fix would be that the `list.select` handler would put some property on the keyboard event that we can check downstream that would mean "preserveFocus = false". But have any similar issues come up?

**Comment by roblourens** [comment]
This also affects the callstack and loaded scripts views @isidorn

**Comment by scarlac** [comment]
Thank you, @roblourens 🌟

**Comment by Tyriar** [comment]
Verified, found this though https://github.com/Microsoft/vscode/issues/68469

**Comment by scarlac** [comment]
I just confirmed that 1.31.1 fixed this. Thank you to all for the quick turnaround here! 👏 💯

**Comment by Spown** [comment]
this is probably causing #68515

**Comment by akbyrd** [comment]
This does not seem to be fixed.

* Enter does absolutely nothing in the search results (Expected: focus the editor. I'm pretty sure this was the default behavior previously and has now changed.)
* Ctrl + Enter doesn't do the same thing as double clicking (Expected: they do the same thing.)
* Ctrl + Enter opens a *second* editor next to your current one. So if you use arrow keys to select a search result it moves the current editor to the result line, then when you press Ctrl + Enter it opens an entirely new editor next to the current one. Now you have two editors open to the same place next to each other. wat. (Expected: go to the search result in the current editor).

More broadly speaking, keyboard navigation in the search results is wildly unintuitive and non-standard. The UX is just *bad*.

**Comment by roblourens** [comment]
There have been several issues due to swapping out the tree implementation with this release. Do you have `workbench.list.openMode` set to `doubleClick`? If so, https://github.com/Microsoft/vscode/issues/68469 is fixed in Insiders.

Ctrl+enter is "Open to side" so that's expected. Other file trees have the same behavior. It just seems weird because as you point out, the item is also opened automatically when you focus it.

**Comment by akbyrd** [comment]
Yes, I'm set to `doubleClick`. Sounds like `ctrl + enter` is working as expected then. but plain old `enter` doesn't work. I can't actually open search results in an the editor. The linked issues doesn't appear to cover this problem.

**Comment by roblourens** [comment]
cmd+down is the same as enter, so https://github.com/Microsoft/vscode/issues/68469 should cover it.
