### ISSUE TITLE
Strict null check 'src/vs/workbench/parts/comments/*'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#68012]
Part of #60565

Tracks updating `src/vs/workbench/parts/comments/` to have strict null checking. There are about 100 errors in these files

You do not need to fix errors outside of `src/vs/workbench/parts/comments/`

**Steps**

1. Add `src/vs/workbench/parts/comments/**/*.ts` to the `include` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works
1. If there are still errors outside of `src/vs/workbench/parts/comments/`, don't include  the changes to  `tsconfig.strictNullChecks.json` when checking in

**Comment by rebornix** [comment]
@RMacfarlane we can postpone the work after we refactor the whole API work.

**Comment by mjbvz** [comment]
These files were accounting for a quarter of the remaining the strict null errors in VS Code so I did a quick brute-force strict null check pass to get them enabled.

Because of the large number of errors and structure of this code—and because I did not want to heavily refactor in this pass—I had to use a number of null suppressions. Please revisit these when you can
