### ISSUE TITLE
settings.json Broken after update to 1.31.0

### ISSUE THREAD

**Issue by yankyhoffman** [Microsoft/vscode#68013]
- VSCode Version: 1.31.0
- OS Version: Windows 10 1809, Ubuntu 18.04, Ubuntu 18.10

Issue is that when opening settings to `settings.json` it only opens the user customized `settings.json`, It does not open it in 2 panes with the defaults on the side. and it does not open the `${workspaceFolder}/.vscode/settings.json` when there is one.

Steps to Reproduce:
1. Open Settings page (json, not UI) through any method

I have tried it on my Windows 10 PC, my Ubuntu 18.10 Laptop and on my Ubuntu 18.04 VM (hyper-v) on the Windows 10 PC

Issue occurs even when extensions are disabled

**Comment by yankyhoffman** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [settings.json unnecessarily opens twice (#65032)](https://www.github.com/Microsoft/vscode/issues/65032)

Nope, I checked and these are different issues

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_31#_use-simple-text-editor-for-editing-settings-as-json

**Comment by yankyhoffman** [comment]
You are 100% correct, I just updated and wanted to try whether the title bar was fixed in Ubuntu 18.10 (it is), so I went into settings even before I read the release notes.
My mistake.

Thanks @usernamehw !
