### ISSUE TITLE
Attribute 'program' does not exist with multi root workspace

### ISSUE THREAD

**Issue by sstone1** [Microsoft/vscode#68011]
- VSCode Version: 1.31.0
- OS Version: MacOS 10.14.1

Steps to Reproduce:

1. Have a workspace configuration that specifies a `name` that is different to the directory name in the `path`, for example:

```json
{
    "folders": [
		{
			"path": "fabric-samples/chaincode/fabcar/typescript",
			"name": "fabcar-contract-typescript"
		},
		{
			"path": "fabric-samples/fabcar/typescript",
			"name": "fabcar-app-typescript"
		}
	]
}
```

2. Have a TypeScript project in one of these folders

3. Have no `launch.json` in that TypeScript project

4. Open a TypeScript file in the TypeScript project, and hit F5

5. The following error appears:

`Attribute 'program' does not exist ('/Users/sstone1/Downloads/fabric-samples/fabcar/typescript/fabcar-app-typescript/src/invoke.ts').`

Note the `fabcar-app-typescript` seems to have been added to the program path, even though it's not a real directory. The `program` attribute should be `/Users/sstone1/Downloads/fabric-samples/fabcar/typescript/src/invoke.ts`. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
I believe this is coming from the node extension since it is generating a launch.json on the fly.
It should take into account the MR workspace scnearion.
Forwarding to @weinand

**Comment by weinand** [comment]
This bug is a result of the ill-defined semantics of `vscode.workspace.asRelativePath`(see  https://github.com/Microsoft/vscode/issues/68929).

**Comment by sbatten** [comment]
seeing this on windows
![image](https://user-images.githubusercontent.com/6561887/53441363-87b58a80-39bb-11e9-90a6-6546750db104.png)

**Comment by sbatten** [comment]
```
{
	"folders": [
		{
			"path": "ts1",
			"name": "TypeScript-Project-1"
		},
		{
			"path": "ts2",
			"name": "TypeScript-Project-2"
		}
	]
}
```

**Comment by weinand** [comment]
fixed with https://github.com/Microsoft/vscode-node-debug/commit/502423ed8a9d06144f9802b7853ca6fa0e2e9515
