### ISSUE TITLE
Node modules are looked up in global paths

### ISSUE THREAD

**Issue by ModernWebService** [microsoft/vscode#68024]
- VSCode Version: Version 1.31.0 (1.31.0)
- OS Version: MacOS Mojave

I had an update notification pop up which I did not realize it was going to run when I closed my editor and then re-opened it shortly after. Since the latest released up, all my extensions will not run and on start up i get "Extension host terminated unexpectedly."
<img width="401" alt="screen shot 2019-02-06 at 21 27 30" src="https://user-images.githubusercontent.com/24275844/52386918-0ae75e80-2a56-11e9-9784-95826e34e5e3.png">

No matter how many times I click restart extension host it continues showing the failed message.

To clarify when this happened to me I was using 1.30 and restarted VSCode got the prompt for the January Changes skimmed it and then started noticing that no plugins were working. 

- Restarted a few times and got the screenshotted prompt above.
- Tried restarted my laptop and then getting back in vscode
- Checked if there was another update after to fix it
- Then decided to re-install vscode while using another editor/terminal to ssh into a server to deploy the project I was working on when this happened

Since the re-install I do believe all my extensions are working as expect and do not believe I removed any. Most of my extensions are Larave, PHP, 1 or 2 Python, couple RoR, and then some Node/angular.

**Comment by ModernWebService** [comment]
Some of the errors thrown
dyld: lazy symbol binding failed: Symbol not found:
dyld: Symbol not found:

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3362 

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4634 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.

**Comment by ModernWebService** [comment]
Re-installed vscode and extensions appear to be working again. But this did break extensions on my old install

**Comment by tkhwang** [comment]
I've got the same problem with the latest vscode.
I'm not sure, but it seems that it is same as before.. that of @ModernWebService.

I just share it again.
Log message after pressing `Open Developer Tools` in `Extension host terminated unexpectedly` popup.

At first
```
[Extension Host] debugger listening on port 50687
```

Repeated for several plugins.
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4634 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/tkhwang/.vscode/extensions/jakebathman.mysql-syntax-1.3.1/syntaxes/MySQL.tmLanguage

... repeated

Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3362 
Debugger listening on ws://127.0.0.1:50687/2294b3d3-2cd3-494e-b84f-c8902faf76fa
For help, see: https://nodejs.org/en/docs/inspector
```

SIGABRT
```
Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ extensionService.ts:457

Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
```

```
extensionHost.ts:231 Extension Host
extensionHost.ts:232 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/tkhwang/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/tkhwang/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

**Comment by alexandrudima** [comment]
@ModernWebService @tkhwang Does this reproduce if you disable all extensions? (Most likely you have an extension installed that is causing this). You can also look for the extension host log to see which extension was being loaded when the crash occured. (`F1 > Developer: Show Logs... > Extension Host`).

With this stable release, we have updated our Electron version and if you are using any extension that uses native node modules, it will stop working and could cause extension host crashes.

**Comment by tkhwang** [comment]
@alexandrudima , As I checked, the crash dosn't occur after uninstalling the following plugin as you said.

**VS Code for Node.js - Development Pack**
https://marketplace.visualstudio.com/items?itemName=nodesource.vscode-for-node-js-development-pack

You may reproduce after installing this plugin, I guess.

**Comment by renarsvilnis** [comment]
<img width="732" alt="screenshot 2019-02-07 at 14 01 10" src="https://user-images.githubusercontent.com/3515099/52410380-da003b80-2ae0-11e9-8c0f-9c79a4e3cc02.png">

Tried reinstall trough brew, didn't help.

**Text version:**

<details>
```
[Extension Host] debugger listening on port 29729
extensionHost.ts:231 Extension Host
extensionHost.ts:232 Debugger listening on ws://127.0.0.1:29729/cdf2c22a-577b-4491-b25a-e85569d055d4
For help, see: https://nodejs.org/en/docs/inspector

extensionHost.ts:231 Extension Host
extensionHost.ts:232 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/renarsvilnis/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/renarsvilnis/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace


log.ts:161  INFO no standard startup: not a new window
extensionService.ts:457 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ extensionService.ts:457
(anonymous) @ extensionService.ts:451
e.fire @ event.ts:567
t._onExtHostProcessExit @ extensionHost.ts:487
(anonymous) @ extensionHost.ts:246
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:237
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:567
t.notify @ notifications.ts:113
t.notify @ notificationService.ts:52
t.prompt @ notificationService.ts:91
t._onExtensionHostCrashed @ extensionService.ts:482
(anonymous) @ extensionService.ts:451
e.fire @ event.ts:567
t._onExtHostProcessExit @ extensionHost.ts:487
(anonymous) @ extensionHost.ts:246
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:237
extensionHost.ts:325 [Extension Host] debugger listening on port 52754
extensionHost.ts:231 Extension Host
extensionHost.ts:232 Debugger listening on ws://127.0.0.1:52754/e24a6a98-5f4b-4650-860d-bb34156f8400
For help, see: https://nodejs.org/en/docs/inspector

extensionHost.ts:231 Extension Host
extensionHost.ts:232 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/renarsvilnis/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/renarsvilnis/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace


extensionService.ts:457 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ extensionService.ts:457
(anonymous) @ extensionService.ts:451
e.fire @ event.ts:567
t._onExtHostProcessExit @ extensionHost.ts:487
(anonymous) @ extensionHost.ts:246
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:237
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:567
t.notify @ notifications.ts:113
t.notify @ notificationService.ts:52
t.prompt @ notificationService.ts:91
t._onExtensionHostCrashed @ extensionService.ts:482
(anonymous) @ extensionService.ts:451
e.fire @ event.ts:567
t._onExtHostProcessExit @ extensionHost.ts:487
(anonymous) @ extensionHost.ts:246
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:237
```
</details>

**Comment by Ravi448** [comment]
![image](https://user-images.githubusercontent.com/29150136/52429585-553a0f80-2b2a-11e9-8168-ce177eb3d8be.png)

Having this problem after update

**Comment by JM-Mendez** [comment]
I was having problems with the `Settings-Sync` extension. I was able to get it working by uninstalling `fs-extra` and `fs-events` from my global `node_modules`.

**Comment by acwo** [comment]
My extensions broke too. Most of them. Seems that they don't work on a new version of vscode. Not cool.

**Comment by ModernWebService** [comment]
For me I went straight to re-installing VSCode fresh and seems to have cleaned out whatever was causing my issue. I still have the same extensions as before I believe, since I have it setup for laravel Node and some Go development. However, my dev tools were throwing similar errors as screenshot above. It seems like it may have broke something that these plugins were listening on, was in the middle of deploying a long project when this happened so I did not have time to mess around with dissecting what the root cause was.

**Comment by ModernWebService** [comment]
@Ravi448  look at @acwo 's comment, has a link to 1.30 which is the previous version

**Comment by tamuratak** [comment]
The cause is that node.js called by a VSCode extension host process tries to load modules in `/Users/username/node_modules` if it cannot find modules in `/Users/username/.vscode/extensions/.../node_modules` for each extension. This is a default behavior of node.js. See [Loading from `node_modules` Folders](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders).

I think VSCode should clear some entries of [module.paths](https://nodejs.org/api/modules.html#modules_module_paths) on extension host processes to prevent this behavior.

To workaround this issue, I recommend  moving `/Users/username/node_modules` to `/Users/username/npm/node_modules`.

**Comment by renarsvilnis** [comment]
For now, I just downloaded [v1.32](https://code.visualstudio.com/updates/v1_30) version and disabled updates in `settings.json`.

> Didn't have to reinstall the extensions

```json
{
  "extensions.autoUpdate": false,
  "update.channel": "none"
}
```

**Comment by malun666** [comment]
> @alexandrudima , As I checked, the crash dosn't occur after uninstalling the following plugin as you said.
> 
> **VS Code for Node.js - Development Pack**
> https://marketplace.visualstudio.com/items?itemName=nodesource.vscode-for-node-js-development-pack
> 
> You may reproduce after installing this plugin, I guess.
> 
> (update) Actually the above plugin consists of a lot of plugins. As I tested, the crash dosn't occur after installing each of them. The crash only occurs after installing the the plugin itself.
> 
> (update2) I found another plugin which crashes.
> 
> **Settings Sync**
> https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
> 
> * related issue : [shanalikhan/code-settings-sync#762](https://github.com/shanalikhan/code-settings-sync/issues/762)

--- 

thanks, disabled the `Settings Sync` extension ,my vscode was backed in business!

**Comment by shanalikhan** [comment]
I'm the author of Settings Sync.

Users has been reporting about extension host killed by Settings Sync.

We removed the chokidar dependency from `Settings-Sync` which caused this problem, by replacing the vscode file watcher api.
But later found in documentation that vscode File Watcher only works for the workspaces file change events.

Its only broken On Mac, but works on Windows and Linux.
Why some extension should be able to kill vscode extension host itself?

**Comment by tamuratak** [comment]
@shanalikhan, see my comment https://github.com/Microsoft/vscode/issues/68024#issuecomment-461707138.

**Comment by hdiggens** [comment]
I was having a similar issue with Microsoft Remote-Shell.
tamuratak post with regards to the node_module, resolved my issue.

![image](https://user-images.githubusercontent.com/16612143/65969651-282ccb00-e433-11e9-9b9e-997018a318a3.png)

VS-Code version 1.38.1

**Comment by alexdima** [comment]
Here is a easier repro for the global paths:
* `package.json`:
```
{
    "publisher": "alex",
    "name": "68024",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js",
    "dependencies": {
        "fast-plist": "^0.1.2"
    }
}
```
* `index.js`:
```
exports.activate = function (ctx) {
    const Module = require('module');
    console.log(Module._resolveLookupPaths('$$$test$$$', module));
}
```

Observe how 3 global lookup folders are present (the last 3):
```
0: "/Users/alex/.vscode-oss-dev/extensions/68024/node_modules"
1: "/Users/alex/.vscode-oss-dev/extensions/node_modules"
2: "/Users/alex/.vscode-oss-dev/node_modules"
3: "/Users/alex/node_modules"
4: "/Users/node_modules"
5: "/node_modules"
6: "/Users/alex/.node_modules"
7: "/Users/alex/.node_libraries"
8: "/Users/alex/src/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper (Renderer).app/Contents/lib/node"
```
