### ISSUE TITLE
Emmet tab complete not working with .tsx files

### ISSUE THREAD

**Issue by eriknelson** [Microsoft/vscode#68021]
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.13-300.fc29.x86_64

Steps to Reproduce:

1. Open basic TSX file
2. Type `.foo` or `div`, expect to see emmet intellisense and tab complete options that will expand using emmet abbreviations.

I expect this setting to say "enable emmet in typescriptreact files using the support from javascriptreact, and display the abbreviations in suggestions":

```
  "emmet.includeLanguages": {
    "typescriptreact": "javascriptreact",
  },
  "emmet.showExpandedAbbreviation": "always"
```

**Comment by octref** [comment]
Are you not seeing this? This should be available without any configuration.

![image](https://user-images.githubusercontent.com/4033249/52388034-678c4e80-2a41-11e9-97d3-8306bf01a74e.png)

**Comment by eriknelson** [comment]
I was not seeing that previously, but testing it out now it seems to be working? I suppose I might have applied the above setting and then restarted vscode or something, but that was not functioning previously. I will close and reopen if it continues to occur.
