### ISSUE TITLE
Support TypeScript Server's  per-file setting for rename configuration

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#68029]
Support the rename operation flags added with https://github.com/Microsoft/TypeScript/pull/29593

This fixes https://github.com/Microsoft/TypeScript/issues/29238 for VS Code but will require TS 3.4+, which we won't bundle until March

**Comment by mjbvz** [comment]
For verification:

1. Install and enable typescript@next in your workspace
1. Use the example code from Microsoft/TypeScript#29238
1. Verify the renames introduce aliases for shorthand by default.
1. Now set `"typescript.preferences.renameShorthandProperties": false` and verify that renames don't introduce alias

**Comment by alexr00** [comment]
I'm still seeing the aliasing even with the setting:
````typescript
// before rename
const x = {
    y: 'value'
}
const { y } = x;
console.log(y);

// after rename
const x = {
	z: 'value'
};
const { z: y } = x;
console.log(y);
````
From package.json: `"typescript": "^3.4.0-dev.20190226",`. I made sure to yarn.

**Comment by mjbvz** [comment]
@alexr00 I can't repo it not working. Did you enable TS 3.4 in your workspace by running: `select typescript version`? Also, if in a js file make sure to set `"javascript.preferences.renameShorthandProperties": false` instead of ``"typescript.preferences.renameShorthandProperties"``

**Comment by alexr00** [comment]
I had not done the select typescript version. However, even with that it still isn't working.
