### ISSUE TITLE
SCM: Allow individual horizontal scrolling setting

### ISSUE THREAD

**Issue by jlave-dev** [microsoft/vscode#68027]
Issue Type: <b>Bug</b>

1. Save a change to a file with a decently long name in a git-enabled project.
2. Open the source control side panel.
3. Hover over "Changes" header and notice that buttons to stage or discard all changes are hidden unless the sidebar is expanded.

In previous version, buttons were visible no matter the sidebar width:
![old version](https://i.imgur.com/FaNak8r.png)

In version 1.31.0, the buttons are hidden when file name or path is long:
![narrow sidebar - 1.31.0](https://i.imgur.com/SzKnRkp.png)

The buttons become visible again when the sidebar is expanded:
![expanded sidebar - 1.31.0](https://i.imgur.com/7D7CrHz.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|8.00GB (1.56GB free)|
|Process Argv|-psn_0_294984|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
@jameslave You have enabled `workbench.tree.horizontalScrolling`. As mentioned in the [release notes](https://code.visualstudio.com/updates/v1_31#_new-tree-widget), this now also works in SCM, so you should be able to scroll horizontally there as well.

**Comment by jameslave** [comment]
@joaomoreno OK, but now with having to scroll, I can't see the filenames to tell which files I'm actually adding. This is a terrible behavior:

![image](https://user-images.githubusercontent.com/30740613/52450282-fb245480-2aff-11e9-964b-a068dd8b44c6.png)

Why isn't there an option for whether to horizontally scroll the source control pane only? Horizontal scrolling is great for the main project tree; for source control... not so much.

**Comment by njkevlani** [comment]
@joaomoreno 
I think we need something like `workbench.tree.horizontalScrollingSCM` with options `inherit`, `true` and `false`. `inherit` meaning respect value of `workbench.tree.horizontalScrolling`.

I'd be glad to help if I could get some pointers to code.

**Comment by IllusionMH** [comment]
Not sure if it is possible to map every list to its own setting, so `horizontalScrollingSCM` won't help with scrolling in Search panel etc. Basically horizontal scroll interferes with lists that have actions/labels on the right side and they better to be in view all the time.

Is it possible to bring back setting that controlled only project tree only (as it was before all lists had scroll support). May remove some (or _most_ in my case) problems with new scrolling behavior.

In my case it is deeply nested structure (that follows convention that we can't change) so horizontal scroll is must have for explorer, however it will great to have search results or path (in SCM view etc.) cropped to have easy access to actions without scroll.
