### ISSUE TITLE
Commands for next/previous debug console

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#68022]
We should have commands to go to the next/previous debug console. I'd like to hook up keybindings the same as what I use for the terminal. Or do we already have something like that?

**Comment by isidorn** [comment]
We do not have a command for this.
We need to add a new workbench global command for this. Adding to backlog until more users want this.
PR adding this also welcome

Code pointer https://github.com/Microsoft/vscode/blob/34cfe460e781a72cb488cd80150d82618b565211/src/vs/workbench/contrib/debug/electron-browser/repl.ts#L855

**Comment by isidorn** [comment]
If more users asks for this I would be willing to add it, however since nobody cares it seems closing as out of scope.
