### ISSUE TITLE
Badly formed version information in the VSCodeSetup.exe

### ISSUE THREAD

**Issue by Maximus5** [Microsoft/vscode#6802]
- VSCode Version: 1.1.1
- OS Version: Win 8.1

Just downloaded `VSCodeSetup-stable.exe`.
Sadly it shows version `0.0.0.0` in numerical file and product versions, and "0.0.0.0" in string file version.
Only string product version contains proper "1.1.1".
Please clean up them to let users see proper version in file managers.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/15507816/5ec175ca-21cd-11e6-977c-45e5241ba58a.png)

As long as it shows in the product version, this is OK.

**Comment by Maximus5** [comment]
That is **not** OK! The product version is useless. Imagine, I have thousands of PE files in folder, and as I've said, file manager is able to show **file version**. What meaning has **product** version if I'm browsing **files**?
Don't you suggest to open properties of each file to realize what is it? Instead of take a look in column "file ver"?
So...

**Comment by Maximus5** [comment]
![2016-05-24_18-43-08](https://cloud.githubusercontent.com/assets/1222388/15510350/9e4212a6-21df-11e6-87e2-4e6617e6b488.png)

Even within Explorer. I just do not want to have spare column to see the version.

**Comment by joaomoreno** [comment]
Ok, I didn't know that the **file version** was shown more often...

**Comment by joaomoreno** [comment]
Future version of Code will have a correct version in there.

**Comment by Maximus5** [comment]
Nice, thanks!
