### ISSUE TITLE
cursorWordPartLeftSelect and cursorWordPartRightSelect should not include underscore when selecting

### ISSUE THREAD

**Issue by ajcastro** [Microsoft/vscode#68034]
- VSCode Version: Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.10586
- OS Version: Windows 10 Pro

Steps to Reproduce:
Let's say we have a word `snake_case`, 
when using this feature it should not include the underscore

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
Duplicates #68043
