### ISSUE TITLE
Unable to copy files across VSCode windows in 1.31

### ISSUE THREAD

**Issue by mooncake4132** [Microsoft/vscode#68031]
- VSCode Version: Confirmed in 1.31 and the latest insider.
Version: 1.32.0-insider
Commit: d9f81c831c6e97cd9423ca7c85b7b6bf6e3d58cf
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa

- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open an arbitrary folder in vscode (call it vscode 1)
2. Create a new vscode window (call it vscode 2) and open another arbitrary folder.
3. Create a file in vscode 1.
4. Ctrl+C or select copy from the right-click menu of the file in vscode 1.
5. Attempt to paste the file in vscode 2 with Ctrl+V doesn't work. The "paste" menu item in the right-click menu is also grayed out.

This used to work in 1.30.2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IainVM** [comment]
Even dragging the files instead of `ctrl+c` and `ctrl+v` it will only move files, not folders. 

Open all the directories `ctrl+a` (which is a nice new feature). Drag over to the 2nd windows workspace, and all you'll get is files, not folders.

**Comment by bpasero** [comment]
PR: https://github.com/Microsoft/vscode/pull/68104
