### ISSUE TITLE
Panel that offers insights for which language feature/services are initialized. 

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#68037]
Issue Type: <b>Feature Request</b>

Panel that offers insights for which language feature/services are initialized.
- should be able to request for language service initialization.

Reason: from past couple of weeks i am facing issues with the language servers, many times it does not get initialized. restarting VSC or reloading the window does not do the trick most of the time.
issue also appears after reloading the window after installing/updating the extension.
work around: 1. close vsc 2. go to task manager and close all vsc processes.
3. start vsc (and hope language service gets initialized)
4. repeat 1-3 till language service gets initialized.

VS Code version: Code - Insiders 1.32.0-insider (d9f81c831c6e97cd9423ca7c85b7b6bf6e3d58cf, 2019-02-06T21:10:41.427Z)
OS version: Windows_NT x64 10.0.15063

**Comment by kieferrm** [comment]
Here are a couple of helpers that you can use:
- Command Palette > Open Process Explorer
- `code --status`
- Command Palette > Show Running Extensions
