### ISSUE TITLE
New Explorer: Keyboard shortcut for New File ('A') no longer creates a new file but activates Filter

### ISSUE THREAD

**Issue by DrianHillman** [Microsoft/vscode#68030]
- VSCode Version: 1.31.0
- OS Version: MacOS Mojave 10.14.2

#### Steps to Reproduce:

1. CMD+Shift+E to go to Explorer
2. Press `A` to create a new file in a directory

The new filtering feature is great! But is the plan to change this keyboard shortcut? Right clicking on a folder still says `A` Creates a New File.

> ![Screenshot](https://cldup.com/W1gDek3E7D.png)

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_31#_new-tree-widget

**Comment by DrianHillman** [comment]
Got it, I'm looking for the `simple` flag under options.

Thanks for the link @usernamehw, I must've missed that— it was a little confusing since the presented shortcut displays by default but is actually opt-in now.
