### ISSUE TITLE
Content assist/intellisense box opens with scrolled to some random location.

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#68035]
Content assist/intellisense box opens with scrolled to some random location.
issue is observed with Typescript and javascript.

**Comment by mjbvz** [comment]
Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to submit a proper issue report. This should include:

- What are you trying to do?
- What went wrong?
- Steps to reproduce the problem

Screenshots would also be helpful

**Comment by sanket-bhalerao** [comment]
issue resolved after updating VSC
