### ISSUE TITLE
Usage of terminal.integrated.env is now showing 'Do you allow this workspace to modify your terminal shell? env' info message

### ISSUE THREAD

**Issue by lcampos** [Microsoft/vscode#68032]
Our extension sets some environment variables in `.vscode/settings.json` by using `terminal.integrated.env.{platform}`. In the latest version of vscode & vscode insiders this is now showing the users an info message asking them to allow/disallow these configurations. I think this was introduced as part of these changes (https://github.com/Microsoft/vscode/commit/cf381901e4ba011c5954a7caaad28d97f2055cec#diff-501a9c519970fc99a12e4f5cdfdfa29f). Is there a way in which the configuration my extension needs can be pre-approved so that the info message is not shown to users ? Thanks

- VSCode Version: 1.31.0 & 1.32.0-insiders
- OS Version: mac os High Sierra (10.13.6)

Steps to Reproduce:

1. Create a project using the salesforcedx extensions, this will create a `settings.json` with some terminal config on it.
2. Reload and focus on the terminal window.

Does this issue occur when all extensions are disabled?: No

**Comment by anothernode** [comment]
For me the `terminal.integrated.env.osx` settings stopped having any effect on macOS since VS Code 1.31.0.

So, having this in `settings.json`:

```
{
    "terminal.integrated.env.linux": {
        "VSCODE_INTEGRATED_TERMINAL": "true"
    },
    "terminal.integrated.env.osx": {
        "VSCODE_INTEGRATED_TERMINAL": "true"
    }
}
```

Works fine in Linux:

```
echo $VSCODE_INTEGRATED_TERMINAL
true
```

But on macOS, the variable remains empty:

```
echo $VSCODE_INTEGRATED_TERMINAL

```

It used to work fine on macOS, too, before VS Code 1.31.0.

**Comment by WyattGosling** [comment]
I am seeing this as well.

VSCode Version: 1.31.0
OS Version: Ubuntu 14.04.5 LTS (Trusty)

I define my environment variable in a .workspace file. When I first create a terminal window for a workspace, I get the same warning dialog. When I click Allow and check my terminal, the variable isn't set. If I create a new terminal session, those will have the variable set correctly. I create new workspaces a few times per week, so this is mildly annoying.

**Comment by pzelnip** [comment]
How does one "retrigger" the "Do you allow this workspace to modify your terminal shell?" dialog for a project?  I accidentally clicked Disallow, and now any changes to `"terminal.integrated.env.osx"` in my workspace settings.json seem to be completely ignored when opening a new integrated terminal.

**Comment by Tyriar** [comment]
This is by design for security reasons. If you don't see the message you likely said don't ask me again when prompted about workspace shell settings. You can allow or disallow using these commands:

![image](https://user-images.githubusercontent.com/2193314/53364806-7b1a2f00-38f4-11e9-86c1-f29a5a5cbafe.png)

**Comment by anothernode** [comment]
Turns out in my case the variable name was just too long. `$VSCODE_INTEGRATED_TERMINAL` doesn't work, but just `$VSCODE` (or `$VS_CODE`) works fine...

**Comment by Tyriar** [comment]
@anothernode weird, not sure what's happening there. FYI VS Code creates `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` environment variables so that you can detect if it's a VS Code terminal, you might be able to just use that.

**Comment by anothernode** [comment]
@Tyriar Cool, I can indeed use `TERM_PROGRAM` for my purpose instead. Thanks for the info!

**Comment by ssilverman** [comment]
For the last few recent releases, I've seen these messages but have no idea whether to "allow" or "disallow". It's a new feature and I can't figure out the ramifications of either. What are the effects of hitting "allow" and what are the effects of hitting "disallow"?

Also, how do I get the terminal to ask with the "allow or disallow" buttons again?

**Comment by Tyriar** [comment]
@ssilverman allow will use the terminal settings (env, shell, shellArgs) in the folders `.vscode/settings.json` file, disallow will prevent it and stop showing the message.

**Comment by ssilverman** [comment]
What are the use cases for allowing and for disallowing?

**Comment by Tyriar** [comment]
Without an explicit opt-in for trusting the repo, you download a repo with a malicious settings.json file, you open the terminal and it does bad things. VS Code should not let that happen purely by opening a folder and a terminal on it.
