### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by mmphego** [Microsoft/vscode#68044]
Version: 1.31.0 x64
Date: 2019-02-07T08:43:20.998Z
OS: Ubuntu 18.04.1 LTS, 4.15.0-45-generic

`Bug still persists.`

Steps to Reproduce:
```
    1. Install an extension for vscode from command line, e.g. `code --install-extension stuart.unique-window-colors`
```

Extension is installed successfully. However, a DeprecationWarning is reported:

```
Found 'stuart.unique-window-colors' in the marketplace.
Installing...
(node:6349) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'stuart.unique-window-colors' v1.0.23 was successfully installed!

```

No problem with VSCode 1.31. Something similar was reported previously in #65088 but that issue was closed as fixed [ccdd299](https://github.com/Microsoft/vscode/commit/ccdd2997a66965c7104fe180207d9a710ea50fa5). At my end this reproduces consistently with any extension I have tried.

Does this issue occur when all extensions are disabled?: Yes

**Comment by DanTup** [comment]
Seeing the same (macOS, 1.31.0):

```
$ code --version

  1.31.0
  7c66f58312b48ed8ca4e387ebd9ffe9605332caa
  x64


$ code --install-extension dart-code-2.23.0-beta.3.vsix

  (node:6514) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security
  and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or
  Buffer.from() methods instead.

  Extension 'dart-code-2.23.0-beta.3.vsix' was successfully installed!
```
