### ISSUE TITLE
Display text cut while no notification

### ISSUE THREAD

**Issue by avisodiya** [Microsoft/vscode#68040]
Issue Type: <b>Bug</b>

Notification text cut while there is no notification in list.

![2019-02-07 10_48_58-](https://user-images.githubusercontent.com/2350981/52392029-268a4d80-2ac6-11e9-95cc-a7cffce2fc81.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.18
php-autocomplete|bsc|0.4.2
gitlab-workflow|fat|1.9.3
php-intellisense|fel|2.3.10
dotenv|mik|1.0.1
laravel-blade|one|1.18.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@avisodiya is this reproducible?

**Comment by avisodiya** [comment]
Now text showing properly. Whenever i have updated the VS Code then it's happened.
