### ISSUE TITLE
I'm no longer able to create files with the 'A' key it just searches the file tree

### ISSUE THREAD

**Issue by mesa123123** [Microsoft/vscode#68047]
- VSCode Version: January 2019
- OS Version: Windows 10

Steps to Reproduce:

1. Update to January 2019
2. Try to create a file in your project

Desired outcome: file created
Actual outcome: explorer searches the tree for a file name containing the letter a

I've tried switching the list mode back according to the docs but the settings file functionality has also gone haywire, I can't find the setting to switch it to a simple tree view

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mesa123123** [comment]
Well, I'm a total noob, switched the workbench.list.keyboardnavigation setting back to simple.
Quite a fitting setting it turned out to be... -_-

**Comment by roblourens** [comment]
I think this is related to this issue: https://github.com/Microsoft/vscode/issues/68083
