### ISSUE TITLE
cursorWordPartLeftSelect and cursorWordPartRightSelect keyboard shortcut not working in renaming file

### ISSUE THREAD

**Issue by ajcastro** [microsoft/vscode#68043]
- VSCode Version: Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.10586
- OS Version: Windows 10 Pro

Steps to Reproduce:
I set my keyboard shortcut for `cursorWordPartLeftSelect ` and `cursorWordPartRightSelect`. 
Then I rename my PascalCase file and use the keyboard shortcut and it didn't work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
The rename input box is a native browser input, which does not implement sub-word navigation.
