### ISSUE TITLE
Font position changes on moving text cursor in integrated terminal

### ISSUE THREAD

**Issue by ziishaned** [Microsoft/vscode#68045]
- VSCode Version: 1.31.0
- OS Version: Mac OSX 10.14.3

Steps to Reproduce:

1. Open integrated terminal
2. Type something and move the text cursor left right

Does this issue occur when all extensions are disabled?: Yes

![2019-02-07 10-50-41 2019-02-07 10_51_44](https://user-images.githubusercontent.com/16267321/52395327-23dc2800-2ac7-11e9-9432-ae1fbd93019d.gif)

**Comment by bdougherty** [comment]
Appears to be related to the `terminal.integrated.lineHeight` setting. I normally have it set to 1.3 and I see this issue, but I tried changing it back to 1 and it doesn't happen.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1937
