### ISSUE TITLE
WinSCP: Code not working as external editor anymore

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#68057]
Issue Type: <b>Bug</b>

I just updated to the 1.31.0 release and now I'm not able to use Code as external editor within WinSCP anymore. (This worked just fine since the birth of VSCode)

Error:
![image](https://user-images.githubusercontent.com/7961978/52400260-f5f2e580-2abe-11e9-88ec-17fb5060396b.png)
(German for: The procedure entry point "??0TryCatch..." not found in DLL "C:\User...")

WinSCP config:
![image](https://user-images.githubusercontent.com/7961978/52400521-a8c34380-2abf-11e9-9a95-259eb2184f89.png)
The command is: `"C:\Users\morgy\AppData\Local\Programs\Microsoft VS Code\Code.exe" !.!`
If I run this on CMD it works just fine, so I have no clue how to resolve this.
Since it's due to the 1.31.0 I tried it here first before blaming WinSCP. :-)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
vscode-multi-line-tricks|big|0.0.3
htmltagwrap|bra|0.0.7
vscode-toggle-quotes|Bri|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.5.0
prettier-vscode|esb|1.8.1
php-debug|fel|1.12.6
auto-rename-tag|for|0.0.15
php-cs-fixer|jun|0.1.95
debugger-for-chrome|msj|4.11.1
indent-rainbow|ode|7.2.4
vscode-versionlens|pfl|0.22.0
nested-comments|phi|2.2.6
vscode-fileutils|sle|2.13.5
sensitive-replace|vil|0.1.1
glean|wix|4.5.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.0.1

</details>

**Comment by dbaeumer** [comment]
@bpasero assigning to you because of the Electron update.

**Comment by bpasero** [comment]
@Morgy93 what is that `!.!`?

@nairby is that your setup too?

**Comment by Morgy93** [comment]
@bpasero Let me quote:

> If you need you may specify a command-line parameters for your editor. Use pattern !.! to specify where should WinSCP place name of the file to edit (quotes around filename containing spaces are added automatically).
https://winscp.net/eng/docs/ui_editor_preferences#editor_type

So it's basically the placeholder of the file to edit.
Maybe something like 
`"C:\Users\morgy\AppData\Local\Programs\Microsoft VS Code\Code.exe" C:\Users\morgy\AppData\Local\Temp\scp21773\var\www\vhosts\domain.com\index.php`
If I run this via cmd it opens up perfectly by the way.

**Comment by bpasero** [comment]
I am open for help as I am clueless.

**Comment by Morgy93** [comment]
Alright, I am going to ask on the WinSCP forum for help then.
My workaround is to use `code !.!` (instead of full path to exe) at the moment, so a cmd opens and then vscode is opened with the specified file.
Sometimes the cmd window remains opened for whatever reason, but at least I am able to safely close it manually without the closure of vscode itself.

**Comment by nairby** [comment]
@bpasero - My problem is that Code will not start after installing the 1.31.0 update. This is directly after setup has run (no third party launcher involved).

**Comment by bpasero** [comment]
Your issue was: https://github.com/Microsoft/vscode/issues/68065

@nairby does it run from the command line "`code --verbose`"?

**Comment by nairby** [comment]
It didn't want to run at all. I have now switched back from 'user' to 'system' install and it now works once more. (One day I will re-install this computer from scratch …)

**Comment by bpasero** [comment]
@nairby that sounds a bit like a broken installation to me. Can you try again with a fresh install. Also @Morgy93 ?

**Comment by nairby** [comment]
User install doesn't want to work. It keeps getting stuck on this file:

Name              : Code.exe
Length            : 67665152
Directory         : C:\Users\brian\AppData\Local\Programs\Microsoft VS Code
CreationTime      : 18/10/2018 10:22:47
LastAccessTime    : 21/10/2018 12:25:55
LastWriteTime     : 17/10/2018 00:30:32

Keeps saying file is locked.

**Comment by bpasero** [comment]
@nairby restart your computer?

**Comment by Morgy93** [comment]
Same error after "fresh" reinstall.
I just don't understand why all my settings were preserved after deinstall.
The folder `C:\Users\morgy\AppData\Local\Programs\Microsoft VS Code\` was completely removed, I checked.
So settings are stored somewhere else?

**Comment by bpasero** [comment]
@Morgy93 if you run with `--user-data-dir <some empty dir>` it will be a fresh start

**Comment by nairby** [comment]
@bpasero I've tried rebooting several times. Cannot remove the file lock.
I've decided to stick with the 'system' installer with the no background updates.
Reference:
https://github.com/Microsoft/vscode/issues/47841#issuecomment-433968487

**Comment by bpasero** [comment]
@joaomoreno any clue?

**Comment by Morgy93** [comment]
I was just about to post a comment to this and then the vscodebot kicked in. =D

Well the author of WinSCP can't reproduce this issue either.

Seems I'm alone with this then. =(

https://winscp.net/forum/viewtopic.php?t=27379

**Comment by Morgy93** [comment]
I have one last idea to this. (Except asking the node team for the dll stuff)
Recently I turned on the Windows Defender Ransomware Protection.
Maybe that one broke the installation.

I'll try a fresh installation without that protection.

**Comment by Morgy93** [comment]
I seriously can't get it to work using the user installer.
Windows Defender Ransomware Protection turned off.
Deinstalled using apps & features.
Deleted 
`C:\Users\morgy\.vscode` 
`C:\Users\morgy\AppData\Local\Programs\Microsoft VS Code`
`C:\Users\morgy\AppData\Roaming\Code`
`C:\Users\morgy\AppData\Roaming\Visual Studio Code`
and installed it again using the user installer
Same error..


The system installer and standalone zip both work fine out of the box.
@bpasero fyi
