### ISSUE TITLE
Intellisense still goes in "Loading" state after updating to "1.31"

### ISSUE THREAD

**Issue by KartikSulane54** [Microsoft/vscode#68055]
Issue Type: <b>Bug</b>

This happens for typescript files for me.
Just start typing in the file and the intellisense goes in infinite "Loading" state when i press Ctrl + Space.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
angular2-snippets|dan|1.0.21
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
angular2-switcher|inf|0.2.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
vscode-github|Kni|0.30.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.6.2
vscode-icons|rob|8.1.0
vsc-angular-cli|web|1.0.0

(2 theme extensions excluded)

</details>

**Comment by KartikSulane54** [comment]
If this is because of any existing extensions that i am using,please feel free to educate me on the same.

**Comment by mjbvz** [comment]
@KartikSulane54 Does this still happen if you disable all extensions?

Can you also please share some details about your workspace by running `code --status` from the command line while VS Code is running

**Comment by KartikSulane54** [comment]
Is there a option to disable all extensions at once or do i have to do it for each one separately ?

Strange thing is that this issue goes away if open VSC after a fresh reboot, but comes back after my PC has been ON for some time.

This is the output from code --status
_____________________________________________________________________________________________________________

Version:          Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)
Memory (System):  15.89GB (5.34GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       79   18448  code main
    0       63   15756     shared-process
    0      113   17852     gpu-process
    0      188   23272     window (member-detail.resolver.ts - DatingApp - Visual Studio Code)
    0      126    9512       extensionHost
    0       80   11860         electron_node tslintServer.js
    0        2   12540         cmd /s /c "C:\Users\kartik.sulane\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe -s d:\Projects\DatingApp --hostPID 9512 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\kartik.sulane\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0        9   28368           console-window-host (Windows internal process)
    0      137   28944           C:\Users\kartik.sulane\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe  -s d:\Projects\DatingApp --hostPID 9512 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\kartik.sulane\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
   21      222   20156         electron_node server.js
    0      181   24932         electron_node tsserver.js
    0       57   15404           electron_node typingsInstaller.js typesMap.js
    0       38   27188         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=9512
    0       44   32476         C:\Users\kartik.sulane\.vscode\extensions\ms-vscode.csharp-1.17.1\.razor\rzls.exe -lsp --logLevel None
    0        9   34024           console-window-host (Windows internal process)
    0       32   20468       searchService
    0       13   27776       watcherService
    0        9   28272         console-window-host (Windows internal process)
    0       12   33184       electron-crash-reporter

Workspace Stats:
|  Window (member-detail.resolver.ts - DatingApp - Visual Studio Code)
|    Folder (DatingApp): 137 files
|      File types: ts(38) cs(33) json(20) css(10) html(10) cache(7) dll(2)
|                  targets(2) js(2) gitignore(2)
|      Conf files: tslint.json(2) tasks.json(1) launch.json(1) csproj(1)
|                  package.json(1) tsconfig.json(1)
|      Launch Configs: coreclr(2)

**Comment by dominik-selmeci** [comment]
I have the same problem. Disabling all extensions fixes the problem.
I tried to found out, which one has the problem with intellisense and it looks like its `Angular Language Service`.

**Comment by KartikSulane54** [comment]
> I have the same problem. Disabling all extensions fixes the problem.
> I tried to found out, which one has the problem with intellisense and it looks like its `Angular Language Service`.

Yes, that service seems to be the issue and the common extension for us then. Any idea how to do without it though ? @dominik-selmeci

**Comment by dominik-selmeci** [comment]
> 
> 
> > I have the same problem. Disabling all extensions fixes the problem.
> > I tried to found out, which one has the problem with intellisense and it looks like its `Angular Language Service`.
> 
> Yes, that service seems to be the issue and the common extension for us then. Any idea how to do without it though ? @dominik-selmeci

Not really :). I'm just using it.

**Comment by fen89** [comment]
I can confirm that it the `Angular Language Service` is indeed the root cause here, disabling it makes intellisense working again like a charm!

**Comment by mjbvz** [comment]
@KartikSulane54 Did you confirm this issue was caused by an extension? Do you still see it in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by KartikSulane54** [comment]
> @KartikSulane54 Did you confirm this issue was caused by an extension? Do you still see it in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Yes as pointed out by @fen89, it was Angular Language Service that was causing the problem for me too.Disabling it alone makes the intellisense work as per normal.
