### ISSUE TITLE
References view does not respect activity bar settings

### ISSUE THREAD

**Issue by binkiesjoris** [Microsoft/vscode#68052]
We have written the needed data into your clipboard because it was t
Issue Type: <b>Bug</b>

- Disable 'References' in the activity bar
- Perform 'Find all reference' on a code element
- Observe 'Reference: Results' tab being opened in the activity bar

In the latest update (1.31.0) when you 'Find all references' on a code element it now automatically always shows the References view in the activity bar, even when you dont want it to (i.e. you explicitly disabled the References tab). There is also no option to have it display somewhere else, there is no location setting as there is for the things like the search bar.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (8.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.1
vshaxe|nad|2.4.5

</details>

**Comment by jrieken** [comment]
> i.e. you explicitly disabled the References tab

You didn't disable the references tab, you told it to hide when not active/selected. That's how activity bar entries works
