### ISSUE TITLE
expanding and collapsing of folders in explorer is no longer available with the arrow icon

### ISSUE THREAD

**Issue by kobibentata** [Microsoft/vscode#68050]
- VSCode Version: 1.31.0
- OS Version: Win 10 64-bit

Ever since my update of VSCode to version 1.31.0, expanding and collapsing of folders in the Explorer pane is no longer available by clicking the little arrow icon! Only by double clicking the folder itself, it can be expanded and collpased.
In all the previous versions of VSCode I've worked with, the expansion and collapse actions was done by simply clicking the arrow icon next to the folder, exactly like it works in all standard systems, where there is a tree of folders and files.

If this is a bug, it should be fixed ASAP of course, and this is a feature by design, then it's a very wrong and un-standard decision, in my opinion. Is such a case, the user should be able to control that via the Settings, at least...

**Comment by dbaeumer** [comment]
This works for me:

![cast](https://user-images.githubusercontent.com/1931590/52400802-7403bc00-2ac0-11e9-9265-6184ee6542e5.gif)

**Comment by joaomoreno** [comment]
@kobibentata Do you have `workbench.list.openMode` set to `doubleClick`, by any chance?

**Comment by joaomoreno** [comment]
I was not aware that on `doubleClick` mode, the folder should still expand when clicking the twistie. cc @bpasero

**Comment by tgquan67** [comment]
I also have this problem on VSCode 1.31 on Windows 10 x64. I have always had `"workbench.list.openMode": "doubleClick"` and single-clicking those small arrow icons should expand/collapse on any previous version.

**Comment by kobibentata** [comment]
@joaomoreno - if I understand correctly, you submitted the code that fixes this issue and now you're just waiting for a pull request on it, in order to get it included in the next version release??...

**Comment by joaomoreno** [comment]
@kobibentata Yes, we are considering including it in a recovery release coming soon.

**Comment by DianaNites** [comment]
Was just about to make my own issue for this, hope a new release is out soon.

In my case it's annoying me while debugging, because double click ALSO edits variables, so i have to deal with that every time i want to expand a value.

**Comment by Fortidude** [comment]
I have v1.31.0  and it's broken on my side as well.

According to this: https://github.com/Microsoft/vscode/issues/42621
I thought it's fixed, but no - it's not.

the "twistie" (or "arrow" next to the folder name) still requires doubleClick to expand / collapse in "double click mode", which is wrong and so "non user friendly".

**Comment by tgquan67** [comment]
No this is a new bug introduced in version 1.31.0, the fix maybe released in January Recovery 2019 (maybe version 1.31.1) or February 2019. 
Track the progress of January Recovery 2019 [here](https://github.com/Microsoft/vscode/milestone/87?closed=1).
