### ISSUE TITLE
All my files were deleted!

### ISSUE THREAD

**Issue by AngelinCalu** [Microsoft/vscode#68058]
Issue Type: <b>Bug</b>

When I opened a folder, all the files I had in the previously opened folder were deleted. They are nowhere to be found!

Extra information (most likely relevant): The files where under the `Extensions` Path of the `Visual Studio Code`

This is outrageous!!

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.8.1
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.8
dotenv|mik|1.0.1
python|ms-|2019.1.0
vetur|oct|0.14.5
laravel-blade|one|1.18.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.3.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@AngelinCalu does this happen for every folder you open. Can you create a test folder with some files and open it from the command line using `code.cmd .`

**Comment by kieferrm** [comment]
@AngelinCalu  can you also please give more details about
> Extra information (most likely relevant): The files where under the `Extensions` Path of the `Visual Studio Code`

Thanks!

**Comment by AngelinCalu** [comment]
> @AngelinCalu can you also please give more details about
> 
> > Extra information (most likely relevant): The files where under the `Extensions` Path of the `Visual Studio Code` (vscode)
> 
> Thanks!

I started working on a vscode  extension a couple of days ago. At first I was working in some folder and copying the extension folder to the `%LocalAppData%\Programs\Microsoft VS Code\resources\app\extensions\` to check how the changes are looking. Then I realised that I could just make the changes directly to the files from that the before-mentioned folder and just restart vscode to see the changes in actions. That was fine until one time when I wanted to open a folder (interactively using `File -> Open Folder ...`  from the menu. When opening a folder in vscode all opened files are getting closed and vscode seems to be restarted. At that point all my (extension) files were removed. I tried recovering them using a few 3rd party softwares without any luck.

I have tried replicating the issue in a different folder than the extensions path and I didn't had any problems.

**Comment by bpasero** [comment]
@AngelinCalu just to be clear, you added files to a location where VSCode itself is installed? That is not a good idea because during installation this directory will be replaced. You should never put files in there.

Can you explain what you are trying to do?

**Comment by AngelinCalu** [comment]
> @AngelinCalu just to be clear, you added files to a location where VSCode itself is installed? That is not a good idea because during installation this directory will be replaced. You should never put files in there.
> 
> Can you explain what you are trying to do?

I'm not sure what else I could explain more than I already have. 
I wanted to work on a new VS Code extension in the `%LocalAppData%\Programs\Microsoft VS Code\resources\app\extensions\my-extension-name` folder. Those files "didn't make it" to a new vscode extension, so there is no question about something installed over that folder.

Could it be something related to the fact that in `version 1.31` there is a new feature which automatically load newly installed extensions (without being needed to reload VS Code) ?

**Comment by bpasero** [comment]
@AngelinCalu can I ask why you choose to create that extension in `%LocalAppData%\Programs\Microsoft VS Code\resources\app\extensions\my-extension-name`? That is not the location where installed extensions come from (only built in ones). The extension directory is `%USERPROFILE%\.vscode\extensions`

**Comment by AngelinCalu** [comment]
@bpasero Can't seem to find the link where it was written that that's the way to go when starting a new extension development.
However that might be, it worked (development and debugging) until my files were deleted and I'm not sure that deleting files is in any way the expected or desired behavior in such case.

**Comment by bpasero** [comment]
Ok please check https://code.visualstudio.com/api/get-started/your-first-extension

Closing for now.

**Comment by AngelinCalu** [comment]
The extension I was working on was a "Programming Languages" one, used to syntax highlight some new file format. There is no real need to compile using `F5` I guess, isn't it?

You can, of course, close it, but the problem still exist.
