### ISSUE TITLE
Atom key map OR vscode problem?

### ISSUE THREAD

**Issue by Tonysmark** [Microsoft/vscode#68053]
I'm currently using windows10 and I used to press `a` to creat a file
but now , somehow, I just got this thing here. And It's really knock me out!
![default](https://user-images.githubusercontent.com/22767695/52399715-fbb8ed00-2af7-11e9-824e-44c1405633b0.png)
![default](https://user-images.githubusercontent.com/22767695/52399727-05daeb80-2af8-11e9-805f-f7e0c31a5d2b.png)

what is the thing? Can I turn it off ??

**Comment by bpasero** [comment]
@joaomoreno we might need your PR on more extensions

**Comment by NeelPi** [comment]
the issue seems to be with the new tree widget introduced in the January Update, if you set the keyboard navigation setting to simple it works as a temp fix.

**Comment by Tonysmark** [comment]
Is there any solutions ? This mess kind drive me crazy.
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.31GB free)|
|Process Argv|E:\Spiders\python\imgScraper|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vue-peek|dar|1.0.2
git-extension-pack|don|0.1.3
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.5.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
vue-snippets|hol|0.1.11
comment|kar|7.0.1
code-beautifier|mic|2.1.0
easy-less|mrc|1.4.5
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.1.0
atom-keybindings|ms-|3.0.5
PowerShell|ms-|1.11.0
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.14.5
material-icon-theme|PKi|3.6.2
live-sass|rit|3.0.0
LiveServer|rit|5.4.0
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.3.0
language-stylus|sys|1.11.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by auchenberg** [comment]
We have an issue oven for this in https://github.com/Microsoft/vscode-atom-keybindings/issues/56. Fix on it's way to the atom key map.

**Comment by auchenberg** [comment]
We shipped a new release of the atom keybindings, let us know if this doesn't solve this for you. Closing for now.

**Comment by Tonysmark** [comment]
problem solved！！ Thanks
