### ISSUE TITLE
API: findFiles ignores files listed in `search.exclude`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#68056]
This is a breaking change in the current insiders d9f81c831c6e97cd9423ca7c85b7b6bf6e3d58cf. Does not reproduce in our latest stable 1.31.0.

Using the `findFiles` API, the latest Insiders decided to start respecting the `search.exclude` setting.

I've found the issue because the [Mocha Test Explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) simply does not work any more on the latest Insiders, when using it on the [VSCE](https://github.com/Microsoft/vscode-vsce) repo which, understandably, excludes `out/**` from search, since all generated code ends up in there. But now, the extension can't find the tests any more, because they are all inside that folder.

cc @jrieken

**Comment by joaomoreno** [comment]
cc @hbenl

**Comment by sandy081** [comment]
@roblourens I still do not see the tests populated in the test explorer which works correctly in stable. Hence reopening.

**Comment by roblourens** [comment]
Oh and .gitignore...
