### ISSUE TITLE
settings broken after upgrade to 1.31.0

### ISSUE THREAD

**Issue by linocatucci** [Microsoft/vscode#68064]
- VSCode Version: 1.31.0
- OS Version: macOs 10.14.1

Steps to Reproduce:

1. Start VSCode
2. open an Angular 6, 7 project

Does this issue occur when all extensions are disabled?: Yes

Hello,
After upgrading to VSCode version 1.31.0 I see .js and .js.map files in my project folder. 
I have tried to add the extension to the files.exclude in my workspace settings and user settings but I still see the files.
Also when opening my code (one of my branches) I see deleted folders, it looks like it's not up to date.

Br,
Lino
![schermafbeelding 2019-02-07 om 11 01 49](https://user-images.githubusercontent.com/17801374/52403787-dca26700-2ac7-11e9-9881-74f06b6d3eb6.png)
![schermafbeelding 2019-02-07 om 11 01 41](https://user-images.githubusercontent.com/17801374/52403788-dca26700-2ac7-11e9-8e24-8570d8c405e5.png)

**Comment by dbaeumer** [comment]
@joaomoreno starting with you because of the tree.

**Comment by linocatucci** [comment]
@dbaeumer, I also see that VSCode shows my compiles .ts files in my working folder instead of my .ts files

**Comment by joaomoreno** [comment]
> @dbaeumer, I also see that VSCode shows my compiles .ts files in my working folder instead of my .ts files

What do you mean?

**Comment by linocatucci** [comment]
Hello @joaomoreno, when I start up my angular project, I don't see any .ts files in my project structure.
I do see javascript files which are the compiled .ts files.

**Comment by joaomoreno** [comment]
Can you reproduce in a smaller, sample repository?
