### ISSUE TITLE
Code.exe will not start

### ISSUE THREAD

**Issue by nairby** [Microsoft/vscode#68065]
Code will not start after updating to 1.31 stable build.
Error dialog:

---------------------------
Code.exe - Entry Point Not Found
---------------------------
The procedure entry point ??0TryCatch@v8@@QEAA@XZ could not be located in the dynamic link library C:\Users\brian\AppData\Local\Programs\Microsoft VS Code\Code.exe. 

Running on Windows 10 Enterprise v1809

**Comment by Morgy93** [comment]
Same error as mine: #68057
