### ISSUE TITLE
Formatters not working

### ISSUE THREAD

**Issue by rodrilink** [Microsoft/vscode#68066]
Issue Type: <b>Bug</b>

Since last version, html, typescript or any other type the formatter not working anymore

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
ftp-simple|hum|0.6.9
Angular-BeastCode|Mik|7.2.2
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.4

(3 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@aeschli assigning to you for a start.

**Comment by aeschli** [comment]
I tried to reproduce with the version you mentioned
Version: 1.31.0 (user setup) Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa Date: 2019-02-05T22:35:56.624Z

I tried formatting HTML, TypeScript, JSON, all worked.
I used the context menu from the editor.

@rodrilink Can you
- disable prettier-vscode (or all extensions) and try again 
- if you still see this, please give more information on how you invoke the formatter and give a sample file where you see the problem.

**Comment by andyWynyard** [comment]
I had this, went in and disabled then enabled all extensions, restarted vs-code, and it worked again, hope that helps @rodrilink

**Comment by rodrilink** [comment]
Hi guys, i did what you said, disabled prettier and restarted and start working again and there is no more messages that extension fail, by the way i did not have prettier when it started to failing after update.

Thank you
