### ISSUE TITLE
Integrated terminal not displaying anything when started

### ISSUE THREAD

**Issue by KirilRusev** [Microsoft/vscode#68060]
- VSCode Version: 1.31
- OS Version: Windows 10 

Steps to Reproduce:

1. Open VS code
2. Click on terminal tab 
![image](https://user-images.githubusercontent.com/19993495/52402919-23935b00-2ace-11e9-8d87-2c5919348893.png)
3. AFTER you press 'enter' - the terminal shows 
![image](https://user-images.githubusercontent.com/19993495/52403008-5f2e2500-2ace-11e9-99f0-c6c5ad298fe3.png)

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by frobinsonj** [comment]
I have a similar issue on Windows 10 also. It will allow me to run commands. I cannot consistently reproduce this. Pressing enter fixes it.

![image](https://user-images.githubusercontent.com/16726902/52403581-ebd0e700-2abe-11e9-916f-07b8c40d6d37.png)

**Comment by thomas-darling** [comment]
Yep, I'm consistently seeing the same thing as @frobinsonj - definitely a bug there.

When I open the console, it is either blank, or becomes blank the moment I start typing, with only the text I just typed being visible.

```
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
