### ISSUE TITLE
Offensive language in translation author's name

### ISSUE THREAD

**Issue by mfloryan** [Microsoft/vscode#68078]
Issue Type: <b>Bug</b>

In the release notes for Jan 2019 version the list of translation contributors for the Polish language:
```Polish: grzegorz m, chujcie toobchodzi, Jakub Jedryszek.```
Includes the middle name which is vulgar and offensive in Polish (and certainly not a real name).

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

**Comment by David-Else** [comment]
So what does it mean? That needs to be stated to decide if it is offensive. Maybe it is funny, the author must have thought so :) Google or Google translate won't tell me anything.

**Comment by gregvanl** [comment]
Removed Polish contributors for now. Will add back once sorted out.

**Comment by kejwmen** [comment]
@David-Else I would say "chujcie toobchodzi" is something like "not your fuc*ing business"

**Comment by David-Else** [comment]
@kejwmen Cheers! 

I have no idea why this issue would be labelled 'important' unless it was going to be read out in Church... in Poland... with a particularity aged conservative congregation :)

**Comment by mfloryan** [comment]
Yes, that's a very good translation @kejwmen

I would like to think you consider important to not offend your users. I personally find it offensive and arrogant and I'm neither in a church nor in Poland ;-)
