### ISSUE TITLE
Failed to create terminal for task clean

### ISSUE THREAD

**Issue by spaelling** [Microsoft/vscode#68077]
Issue Type: <b>Bug</b>

Latest insider build, no extensions installed. Same issue on january 2019 update.
No issue on december 2018 update.

Once I have run a build task once, and closed the "build terminal" any subsequent builds will fail with the error "Failed to create terminal for task clean".
If I do _not_ close the build terminal I can run the build again.

I get no output anywhere explaining what went wrong.

The issue is on a dotnet core Azure functions app.

tasks relevant

```
    {
      "label": "clean",
      "command": "dotnet clean",
      "type": "shell",
      "problemMatcher": "$msCompile"
    },
    {
      "label": "build",
      "command": "dotnet build",
      "type": "shell",
      "dependsOn": "clean",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": "$msCompile"
    },
```

if I comment out the `dependsOn` I can build (without cleaning first), then remove the comment and build again, the clean task runs fine (because the terminal is now already spawned)

output from developer tools console:
```
Failed to create terminal for task clean
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:567
t.notify @ notifications.ts:113
t.error @ notificationService.ts:48
t.handleError @ task.contribution.ts:1826
(anonymous) @ task.contribution.ts:875
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
t.run @ task.contribution.ts:874
(anonymous) @ task.contribution.ts:2074
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
t.runBuildCommand @ task.contribution.ts:2070
(anonymous) @ task.contribution.ts:579
e.invokeFunction @ instantiationService.ts:54
t._tryExecuteCommand @ commandService.ts:63
(anonymous) @ commandService.ts:52
Promise.then (async)
t.executeCommand @ commandService.ts:52
t._doDispatch @ abstractKeybindingService.ts:208
t._dispatch @ abstractKeybindingService.ts:167
(anonymous) @ keybindingService.ts:324
log.ts:173   ERR Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
    at e.createTerminal (file:///C:/Users/spael/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3316:796)
    at l (file:///C:/Users/spael/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3310:873)
    at new Promise (<anonymous>)
    at e.executeInTerminal (file:///C:/Users/spael/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3310:834)
    at file:///C:/Users/spael/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3307:394
    at process._tickCallback (internal/process/next_tick.js:68:7)
log.ts:173   ERR Failed to create terminal for task clean: Error: Failed to create terminal for task clean
    at e.executeInTerminal (file:///C:/Users/spael/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3313:152)
    at file:///C:/Users/spael/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3307:394
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

VS Code version: Code - Insiders 1.32.0-insider (d9f81c831c6e97cd9423ca7c85b7b6bf6e3d58cf, 2019-02-06T21:10:41.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexr00** [comment]
Fix: 37d7baa7ac

**Comment by RoderickQiu** [comment]
I found this problem too. (But for C++, though) Really hope a new release can come out soon.
Thanks you guys.

**Comment by ptsneves** [comment]
I just updated the latest release and it contains this bug. Do you have stable tree or something that ensures that this kind of fresh bugs does not pop?

**Comment by ptsneves** [comment]
I just updated the latest release and it contains this bug. Do you have stable tree or something that ensures that this kind of fresh bugs does not pop?

**Comment by alexr00** [comment]
@ptsneves what version do you have? This should be fixed starting with 1.31.1.

**Comment by ptsneves** [comment]
@alexr00  1.32.1

**Comment by alexr00** [comment]
@ptsneves, can you create a new issue with your repro steps? Since this issue was caused by a value not getting checked for existence it can't be the same root cause.
