### ISSUE TITLE
Angular Language Service crashes after update to 1.31.0

### ISSUE THREAD

**Issue by v1per** [Microsoft/vscode#68079]
Issue Type: <b>Bug</b>

Hi,

when I open file with Angular inline template CPU consumption increases significantly and in less that a minute I get the notification from editor:

"The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted. "

  

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
diff-tool|jin|0.0.1
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
vscode-simple-icons|Lau|1.11.0
dotenv|mik|1.0.1
azure-account|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
snippet-creator|nik|0.0.5
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.2
sass-indented|rob|1.5.1
projector-language-support|sph|0.0.5
quokka-vscode|Wal|1.0.182

(2 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
Duplicates https://github.com/angular/vscode-ng-language-service/issues/312
