### ISSUE TITLE
Find input - Too much padding on markdown rendered tab

### ISSUE THREAD

**Issue by frobinsonj** [Microsoft/vscode#68074]
Issue Type: <b>Bug</b>

On a markdown rendered tab, the Find input has too much padding.
![image](https://user-images.githubusercontent.com/16726902/52405431-26d51980-2ac3-11e9-99bb-afe44ec10eb5.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.85GB (5.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
jshint|dba|0.10.20
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
php-intellisense|fel|2.3.10
beautify|Hoo|1.4.8
ftp-sync|luk|0.3.7
vscode-apache|mrm|1.2.0
vscode-autoprefixer|mrm|2.2.0
debugger-for-chrome|msj|4.11.1
php-docblocker|nei|1.7.0
es6-css-minify|olb|2.2.0

</details>

**Comment by mjbvz** [comment]
Looks like the same as the find widget in the editor. Please submit a PR if you don't think this is the case

**Comment by frobinsonj** [comment]
Yes, it is the same, that's what causes the issue. Sorry for the lack of detail on the initial comment.

When search options are displayed the padding is necessary, however, they are not always displayed. To my knowledge, by default they are not. Therefore by default, `padding-right` should not be applied to the input element.
