### ISSUE TITLE
Python won't start

### ISSUE THREAD

**Issue by udoheuser** [Microsoft/vscode#68070]
`
[100_parse_excel.zip](https://github.com/Microsoft/vscode/files/2840332/100_parse_excel.zip)

PS` D:\Lehre\Sem 1\Python> cd 'd:\Lehre\Sem 1\Python'; ${env:VAR1}='1'; ${env:VAR2}='2'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\heuser\.conda\envs\sem1env\python.exe' 'c:\Users\heuser\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '12036' '-m' 'module.name' 'arg1' 'arg2'
C:\Users\heuser\.conda\envs\sem1env\python.exe: Error while finding module specification for 'module.name' (ModuleNotFoundError: No module named 'module')

I use VS Code v 1.31.0 launched from Anaconda v 2018.12 with Python 3.7.1 (OS: Windows 10 Pro)
The error occurs with and without activated virtual environment.

**Comment by kieferrm** [comment]
Please file the issue against the Python extension here: https://github.com/Microsoft/vscode-python/issues Thanks!
