### ISSUE TITLE
Suggestions need a kick to show documentation

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6807]
Type `subs` on a string, after moving down and up again the documentation shows...

![suggestions-doc](https://cloud.githubusercontent.com/assets/5047891/15506457/01a544b6-21c8-11e6-80e4-f5f125577c9a.gif)

**Comment by joaomoreno** [comment]
Got broken somehow...

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by alexandrudima** [comment]
It works if you type slowly...

**Comment by joaomoreno** [comment]
I can't reproduce this. Maybe you show me at your desk @alexandrudima?

**Comment by alexandrudima** [comment]
Have you tried in the built version in our project (maybe it matters for timing purposes?)

Every other time when I type `.ac` it happens, but you gotta type `.ac` quickly.

![suggestions](https://cloud.githubusercontent.com/assets/5047891/15566860/7e47e850-2323-11e6-949e-e7ce9262c1cc.gif)

**Comment by joaomoreno** [comment]
I did... my machine is just too fast. 👍 

Show me in the office.

**Comment by jrieken** [comment]
This could also be the tsserver not being able to compute the details fast enough. If I remember correctly, they sometimes don't return a result

**Comment by joaomoreno** [comment]
@dbaeumer Is this true?

**Comment by dbaeumer** [comment]
@joaomoreno not to my knowledge (at least it is not spec'd that way). 
@zhengbli can you please comment/clarify.

**Comment by alexandrudima** [comment]
@joaomoreno I tried reproducing again today, it only happens sometimes, here I am typing `ca` and then using backspace + `ac`:

![sczr0ngsx3](https://cloud.githubusercontent.com/assets/5047891/15604882/f02e9150-2402-11e6-85d5-a9d01564bc15.gif)

**Comment by joaomoreno** [comment]
Got it!

![image](https://cloud.githubusercontent.com/assets/22350/15608044/81749998-2417-11e6-91aa-4057cf331e16.png)

**Comment by zhengbli** [comment]
I got the repro as well (also happens very occasionally), and the corresponding trace is as follows:
[treacing_completion_entry_detail.txt](https://github.com/Microsoft/vscode/files/287358/treacing_completion_entry_detail.txt)

It seems that even in the repro cases, the `completionEntryDetails` request still successfully returned the documentation (only took 6~7 ms). So something else might have caused the issue?
