### ISSUE TITLE
Cannot create file/folder

### ISSUE THREAD

**Issue by danielcooke1996** [Microsoft/vscode#68085]
- VSCode Version: 1.31.0-insider
- OS Version: MacOs Mojave 10.14

**Description**
This is difficult to reproduce because it only seems to happen in one of my projects, some information about the project that is "bugged"

1. It was working fine yesterday when I left work
2. I was using the "search directory" function a lot - and may have had some text in the box when I left for the day. ie. this is the feature where you can start typing while focused on the left panel directory structure and VScode will highlight your search text.
3. It seems this bug is tied to the search directory function

Steps to Reproduce:
1. Play with search directory function, leave a filter in and close VScode
2.  Open project (with `--disable extensions`)
3. Click create file icon

**Expected Results:**
User should be presented with the following text box to enter the filename
![image](https://user-images.githubusercontent.com/22816887/52408937-f34abd00-2acb-11e9-9afc-0c0eae1ce6c7.png)

**Actual Results**
User is presented with the search directory input 
![image](https://user-images.githubusercontent.com/22816887/52409280-f98d6900-2acc-11e9-9ada-1f598e2fa7ed.png)
Here I have typed in "file.test" to demonstrate

**Workaround**
You can actually click the create file again after the search input is displayed to proceed with the expected workflow, a minor inconvenience.

Edit: This workaround has since stopped working. I cannot create new files in this project anymore so I have switched back to the stable build.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@danielcooke1996 I don't understand the **Actual Results**. As soon as you `Click create file icon`, the **type filter** comes up with the contents `file.test`?

**Comment by danielcooke1996** [comment]
> @danielcooke1996 I don't understand the **Actual Results**. As soon as you `Click create file icon`, the **type filter** comes up with the contents `file.test`?

Apologies, I should have made that clearer - i have updated my original post. I typed "file.test" to demonstrate. But it is merely the **type filter**

**Comment by joaomoreno** [comment]
So the issue is: sometimes you click `New File` and the input box doesn't show at all?

**Comment by danielcooke1996** [comment]
> So the issue is: sometimes you click `New File` and the input box doesn't show at all?
Its not "sometimes" - its more like 99% of the time
I'm not sure how I can reproduce this issue for you, I have given as much detail as I can in my post - sorry If its not enough.
