### ISSUE TITLE
Tree filtering breaks atom-keybindings

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#68083]
Issue Type: <b>Bug</b>

Last update just broke my workflow with files tree. I tried to use `workbench.list.keyboardNavigation="simple"` as it was reffered [here](https://github.com/Microsoft/vscode/issues/68030) but it still broken. In `simple` mode pressing <kbd>A</kbd> does trigger the filter and focusing first file with name beginning on the `A` letter and **in the same time** it triggers new file creation on the same level with the highlighted file.

So it produces some problems

1. Focusing on the opened file lost and jumped to the first found file.
2. After that the input for filename of the newly created file placed in wrong position, near this focused file.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
vscode-color|ans|0.4.5
snapshot-tools|asv|0.2.2
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.12.8
vscode-npm-script|eg2|0.3.5
vscode-pull-request-github|Git|0.3.2
beautify|Hoo|1.4.8
vscode-styled-components|jpo|0.0.25
typescript-duck-snippet|Ky6|1.0.0
zero-reference|Ky6|1.1.0
atom-keybindings|ms-|3.0.5
vscode-typescript-tslint-plugin|ms-|0.4.1
debugger-for-chrome|msj|4.11.1
vscode-versionlens|pfl|0.22.0
vscode-icons|rob|8.1.0
code-settings-sync|Sha|3.2.4
stylelint|shi|0.48.0
gitblame|wad|2.6.3
vscode-proto3|zxh|0.2.2

(1 theme extensions excluded)

</details>

### References
* https://github.com/Microsoft/vscode/issues/68030
* https://github.com/Microsoft/vscode/issues/68085

**Comment by joaomoreno** [comment]
> **in the same time** it triggers new file creation on the same level with the highlighted file

Did you assign <kbd>A</kbd> to create a new file?

**Comment by Ky6uk** [comment]
@joaomoreno I'm not, but it can be done by other extension like `atom-keybindings`. I'm not sure because I'm using it for years. So is it possible to bring back `keyboardNavigation` behaviour for files tree, or disable it completely or some other workaround?

**Comment by Ky6uk** [comment]
I also did read changelog more closely. So as I understand it can be done only by setting `listAutomaticKeyboardNavigation` to `false` by any extension. Isn't it? Or can I set `listAutomaticKeyboardNavigation` manually by settings?

**Comment by joaomoreno** [comment]
As a user, you cannot change it. But we can certainly let the `atom-keybindings` guys know, just as we did with VIM: https://github.com/VSCodeVim/Vim/pull/3432 and every `atom-keybindings` user would have to press a keybinding to go into that mode. What do you think?

**Comment by Ky6uk** [comment]
@joaomoreno I did create [a PR](https://github.com/Microsoft/vscode-atom-keybindings/pull/57) for this. But for some reasons it's not working for me. Maybe I forgot about something.

Also I can say an user should be able to disable this behaviour I think. Because nothing to stop the user to assign single key as a hotkey of `explorer.newFile` command for example.

**Comment by joaomoreno** [comment]
> Because nothing to stop the user to assign single key as a hotkey of `explorer.newFile` command for example.

That's correct. But so far users have assigned simple letter keybindings in lists simply because they were no-ops so far. It's true that they might already have them assigned today, but I'm pretty sure they are easily convinced to simply add a modified key to they keybinding in order to benefit from this feature.

**Comment by joaomoreno** [comment]
@Ky6uk OK Got your PR to atom-keybindings merged after a small fix, found why it wasn't working: https://github.com/Microsoft/vscode-atom-keybindings/commit/b1e3f3349cc8f0835f4e7b1bfc8d88b8d336fe05

Thanks for all the help, a new extension version should be coming out any time now!

**Comment by Ky6uk** [comment]
@joaomoreno btw multikeys also don't work. Like <kbd>Shift<kbd> + <kbd>A<kbd>. It's also changing focus to first found file on the top of the tree when my focus was on the deep level before pressing combination of <kbd>Shift<kbd> + <kbd>A<kbd> and after this VSCode opens input for file name. =\

**Comment by Ky6uk** [comment]
@joaomoreno Unfortunately `atom-keybindings` `v3.0.6` doesn't fix anything. That bug still exists. 😞

**Comment by Ky6uk** [comment]
@joaomoreno also maybe it's just different bug actually. 🤔 

![bug](https://user-images.githubusercontent.com/46930/52437906-b78e1280-2b20-11e9-9a53-842a4ed5d486.gif)

**Comment by Andorbal** [comment]
I'm seeing the behavior that @Ky6uk just described.  I'd LOVE a way to turn this new list behavior off because it breaks my keybindings which are Atom-like, but not quite the same.

**Comment by joaomoreno** [comment]
@Ky6uk Good bug

@Andorbal Right. If we were to add such a setting, you would need to configure a key binding to toggle filter mode.
