### ISSUE TITLE
Object.entries is not recognised in JS code

### ISSUE THREAD

**Issue by qwelias** [Microsoft/vscode#68089]
- VSCode Version: 1.30.2
- OS Version: 4.20.6-arch1-1-ARCH

Steps to Reproduce:

1. Type `Object.` in a `*.js` file
2. No `Object.entries` in suggestions

Does this issue occur when all extensions are disabled?: Yes

**Comment by frobinsonj** [comment]
`Object.entries` was added in es2017, have a read here: https://code.visualstudio.com/docs/languages/jsconfig

**Comment by qwelias** [comment]
Well ok, but why would I need compiler options JS in the first place?
And since ES2018 is the current standard why isn't it enabled by default?

**Comment by mjbvz** [comment]
@qwelias Changing the default for everyone is a big change. es6/2015 is a conservative default. As noted, you can easily configure other targets if you wish
