### ISSUE TITLE
Иероглифы в подсказке

### ISSUE THREAD

**Issue by spkoder** [Microsoft/vscode#68087]
Здравствуйте. У меня есть проблема. В свой проект я подключил другой модуль, в котором я задокументировал русскими символами методы, используя javadoc.  При этом подсказки к методам в этом проекте в VS Code отображаются в виде иероглифов, т.к. VS Code декодирует символы, используя кодировку ANSI (Win-1251), хотя сам исходник сохранен в UTF-8 . Открывая этот же проект в Idea, такой проблемы не наблюдается. Пробовал разные настройки прописывать, ничего не помогает.

**Comment by Miigon** [comment]
Can you provide a screenshot?

**Comment by spkoder** [comment]
![default](https://user-images.githubusercontent.com/15929530/52415243-0cc62600-2b19-11e9-8a26-063703f5f791.png)
![2](https://user-images.githubusercontent.com/15929530/52415244-0d5ebc80-2b19-11e9-905e-98a7767032d3.png)
[TestLogic.zip](https://github.com/Microsoft/vscode/files/2841044/TestLogic.zip)
[TestUseOtherModule.zip](https://github.com/Microsoft/vscode/files/2841048/TestUseOtherModule.zip)

**Comment by spkoder** [comment]
Also when I press "Go to definition (F12)"
![3](https://user-images.githubusercontent.com/15929530/52415579-ebb20500-2b19-11e9-88c6-d5a2a548f75e.png)
then I see this
![4](https://user-images.githubusercontent.com/15929530/52415646-274ccf00-2b1a-11e9-9a42-ef658f213527.png)

**Comment by Miigon** [comment]
Did you check your default encoding setting?
I've tested it on macOS and didn't encounter this problem. The file opens in UTF-8 correctly.

**Comment by spkoder** [comment]
Where I can see this setting?

**Comment by spkoder** [comment]
Source file is Logic.java. This file opens normally. But then I press F12 then open file Logic**.class**

**Comment by kieferrm** [comment]
Please file the issue against the Java extension. Thanks!

**Comment by spkoder** [comment]
Ok. Thanks
