### ISSUE TITLE
[AngularJS] [Suggestions / IntelliSense] Can You return back suggestion for AngularJS / angular1 as extension?

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#68086]

**Comment by kieferrm** [comment]
There are angular extensions in the marketplace: https://marketplace.visualstudio.com/search?term=angular&target=VS&category=All%20categories&vsVersion=vs15&sortBy=Relevance

**Comment by Mlocik97-issues** [comment]
@kieferrm Angular2+ not AngularJS...
