### ISSUE TITLE
Cannot duplicate a file at the top-level folder using alt+drag.

### ISSUE THREAD

**Issue by kroton** [Microsoft/vscode#68095]
- VSCode Version: 1.32.0-insider
- OS Version: macOS High Sierra

**Description**
I cannot duplicate a file at the top-level folder using alt+drag on the sidebar.
On the other hand, I still can duplicate a file at the subdirectory.

*behavior at v1.30*
![v1.30](https://user-images.githubusercontent.com/2750695/52411811-52d2b800-2b20-11e9-8012-d9801a8415d0.gif)

*behavior at v1.32-insiders*
![v1.32-insiders](https://user-images.githubusercontent.com/2750695/52411912-a1805200-2b20-11e9-802b-9ceb534b2ae4.gif)

Steps to Reproduce:

1. Try to duplicate a file at the top-level folder using alt + drag on the sidebar.
2. Cannot duplicate.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Recovery only if change is small.
