### ISSUE TITLE
indentation not working

### ISSUE THREAD

**Issue by malurahul549** [Microsoft/vscode#68093]
Issue Type: <b>Bug</b>

not able to indent html, js code using ctrl+shift+i . tried everything. even installed prettier and still not able to indent my code.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
prettier-vscode|esb|1.8.1
python|ms-|2019.1.0
debugger-for-chrome|msj|4.11.1

</details>

**Comment by dbaeumer** [comment]
@malurahul549  `Ctrl+Shift+I` is not the standard keyboard shortcut to indent code. It is `Ctrl+]`. However you can tweak it using the key bindings editor.

Did  `Ctrl+Shift+I` work for you before.
