### ISSUE TITLE
Curse words in changelog :(

### ISSUE THREAD

**Issue by dzienisz** [Microsoft/vscode#68097]
Hey, VS coder. I have bad news :( somebody fools you and made you merge curse words.

![zrzut ekranu 2019-02-7 o 13 43 28](https://user-images.githubusercontent.com/3521624/52412578-76294300-2adf-11e9-8a88-e1121db3f5dc.png)

That's not name and surname.

Please remove it :(

**Comment by Ky6uk** [comment]
https://github.com/Microsoft/vscode/issues/68078
