### ISSUE TITLE
passing launch config without a 'type' attribute to 'vscode.startDebug' does not return an error

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6809]
testing https://github.com/Microsoft/vscode/issues/6248:

- VSCode Version: 1.1.0 alpha
- OS Version: OS X 10

Steps to Reproduce:

- use the setup from https://github.com/Microsoft/vscode/issues/6806
- remove the 'type' attribute
- run 'Hello' command

Observe:
no error is reported.

'type' is a mandatory attribute that should result in error if missing.
But it should be possible to omit attribute 'name' without error.

**Comment by isidorn** [comment]
Currently the command returns the errors, after consulting with Joh it is the extensions responsibility to handle this error in any way the extension writer wants. Closing as designed. More details:

![screen shot 2016-05-25 at 11 39 38](https://cloud.githubusercontent.com/assets/1926584/15535401/7b2d12a0-226d-11e6-903b-57788d5aaa2f.png)

**Comment by weinand** [comment]
@isidorn What error is returned if attribute 'type' is missing?

**Comment by isidorn** [comment]
With the commit I just pushed it returns a proper error message 😊

![screen shot 2016-05-25 at 11 53 32](https://cloud.githubusercontent.com/assets/1926584/15535893/80d48448-226f-11e6-8c64-c7ae15b95dcf.png)

Maybe we should tune the error message such that it does not refer to `launch.json`
