### ISSUE TITLE
Terminal window turns blank

### ISSUE THREAD

**Issue by ajit555db** [Microsoft/vscode#68096]
Issue Type: <b>Bug</b>

Windows 10 64 bit
Can not reproduce it consistently. I use WSL for terminal window and log into another linux machine. Sometimes, if I switch the panel view or leave the compute on for sometimes, the terminal window becomes blank / unresponsive, can not see the command line.

VS Code version: Code - Insiders 1.32.0-insider (45c7f29565821668f4d010b25e3289953bd9ac71, 2019-02-07T10:25:31.179Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.86GB (5.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.5.2
markdown-all-in-one|yzh|2.0.1

</details>

**Comment by tavrez** [comment]
1809 is known to have terminal problems, and MS stuff at console team said they won't backport fixes into it. You should use 1803 or go to latest insider

**Comment by pedrogarcia** [comment]
> 1809 is known to have terminal problems, and MS stuff at console team said they won't backport fixes into it. You should use 1803 or go to latest insider

There are no known issues with the terminal listed in the [Windows 10 update history](https://support.microsoft.com/en-us/help/4464619/windows-10-update-history). I would definitely have prevented my computer from upgrading to 1809 if I knew the terminal would be consistently broken like this.

**Comment by tavrez** [comment]
check [issues](https://github.com/microsoft/console/issues?q=is%3Aissue+1809+is%3Aclosed+milestone%3A19H1), this will list all the 1809 bugs which fixed on 1903 or insiders, there are comments from team said they wont backport bugs.

**Comment by pedrogarcia** [comment]
> check [issues](https://github.com/microsoft/console/issues?q=is%3Aissue+1809+is%3Aclosed+milestone%3A19H1), this will list all the 1809 bugs which fixed on 1903 or insiders, there are comments from team said they wont backport bug fixes.

This is just truly awful from Microsoft's devs part. 
Shipping a known broken version of a very important tool, just because there wasn't enough publicity shaming the company about this particular issue.

**Comment by Tyriar** [comment]
This issue actually looks like fallout from adding reflow support to the terminal and should be fixed in https://github.com/Microsoft/vscode/issues/68721

The major issue in 1809 is https://github.com/Microsoft/console/issues/270 (https://github.com/Microsoft/vscode/issues/57803) which unfortunately slipped through the cracks, the true impact of it was only discovered too late when only critical fixes were going into 1809. As I understand it, this didn't count as it's purely a visual glitch.
