### ISSUE TITLE
Add better extension error diagnostics for internal errors

### ISSUE THREAD

**Issue by ruslan-bikkinin** [microsoft/vscode#68094]
Hello guys, I am going to tell you about problem that I've faced. Our team owns [Cordova Tools](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools) extension and during prerelease testing of the new version extension was getting crashed permanently. Extension was bundled into .vsix file and installed on VS Code 1.30.2 and when I tried to use it in VS Code I got such error:
![image](https://user-images.githubusercontent.com/30265843/52411326-7a0f9200-2aec-11e9-84eb-b42e3aee4e43.png)
No output in `Debug Console`, because, apparently, something went wrong on a step before extension started to activate.

I tried to dig into error stacktrace, but there was only one stack frame without any useful info:

![image](https://user-images.githubusercontent.com/30265843/52411449-f1452600-2aec-11e9-9765-70e009dbaef8.png)

As a result I had to manually search for broken commit, undo changes piece by piece until I found out the cause of error: there was regexp flag `s` used in the extension code which isn't supported in NodeJS v8.9.3 that is used inside VS Code v1.30.2.

If internal node js error had been forwarded into VS Code error instead of showing completely confusing ECONNRESET error I would have learned about the source of a problem more quicker. In my case I would have seen something like this: 

```js
SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

So, It would be better to have internal NodeJS stacktraces/error messages to diagnose such kind of errors. 

Please, let me now if you need more information/clarifications.

**Comment by alexandrudima** [comment]
@ruslan-bikkinin I cannot reproduce what you are describing. I have tried with the following:

* `package.json`
```js
{
    "name": "68094",
    "publisher": "alex",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": ["*"],
    "main": "./index.js"
}
```

* `index.js`:
```js
exports.activate = function() {
    // making a syntax error
    !@#
}
```

When I run the extension, I get the following in the console:
![image](https://user-images.githubusercontent.com/5047891/52553202-11bdfa80-2de3-11e9-9ebd-e334f4c404cf.png)

**Comment by ruslan-bikkinin** [comment]
@alexandrudima thanks for replying! I'll come back soon with detailed repro steps.
