### ISSUE TITLE
Go to definition, but how to go back quickly? any short key?

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#681]
Go to definion, but how to go back quickly? any short key?
Press F12 or CTRL +click will go to the definition. but we want go back quickly.
such as CTRL+ALT+backspace?

**Comment by Tyriar** [comment]
There is a `Back` command in the `Goto` menu which goes back to the last cursor position. I think it defaults to `alt+leftarrow`.

**Comment by netroby** [comment]
Thanks, but the right key was ```CTRL+ALT+-```
