### ISSUE TITLE
New explorer: do not re-select files that got deleted

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#68101]
I am not sure if this was a missing file event, but I noticed that when returning back to the explorer from an "undo all changes" in the SCM view, many errors popped up about a file no longer existing when trying to open it.

I know we should reopen the last selected file in the explorer when returning to it, but we also need to check if that file got deleted meanwhile.

Filing this as a reminder to check if that logic is still in.

**Comment by isidorn** [comment]
@bpasero looking at the code it is not possible for something like that to happen.
We just take what is focused in the explorer and try to open it
This might be a dup of missing file events https://github.com/Microsoft/vscode/issues/68316

My point is, are you still seeing this and if yes can you give exact steps?
Or at least errors from console?

**Comment by bpasero** [comment]
@isidorn yes reproduces:
* create a file "1" in a folder
* do not open it
* right click it so that it gets focus
* click on SCM view
* undo all changes
* click back to explorer

=> error pops up
