### ISSUE TITLE
Multicursor no longer works on RDP session

### ISSUE THREAD

**Issue by anttiah** [Microsoft/vscode#68109]
After the latest update, multicursor cannot be activated over RDP session using only keyboard.

I'm aware that multicursor has always been troublesome with RDP, but up to version 1.30.2 it was possible to use key combination AltGr + Shift + Up/Down arrow to activate it. After the 1.31.0 update I haven't found key combo that would work.

The setting `editor.multiCursorModifier` has no effect on this.

Using Alt + mouse click is not an option due to number of lines I need to edit.

- VSCode Version:
**Version**: 1.31.0 (user setup)
**Commit**: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
**Date**: 2019-02-05T22:35:56.624Z
**Electron**: 3.1.2
**Chrome**: 66.0.3359.181
**Node.js**: 10.2.0
**V8**: 6.6.346.32
**OS**: Windows_NT x64 6.3.9600

- OS Version:
**Server**: Windows Server 2012 R2 running Remote Desktop Session Host role
**Client**: Windows 10 1809 mstsc.exe

Steps to Reproduce:
1. Press AltGr + Shift + Down arrow.

Expected result:
Multicursor editing is enabled.

Actual, incorrect result
Lines of text get selected as if only Shift + Down arrow was pressed.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by rebornix** [comment]
Shares the same root cause as https://github.com/Microsoft/vscode/issues/68003
