### ISSUE TITLE
Sidebar pushed out of view when window is very small

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6810]
- VSCode Version: alpha
- OS Version: OS X

Steps to Reproduce:
1. open vscode, do not have it full screen, have it just occupy a portion of the screen
2. open developer tools
3. open editors side by side -> layout get broken due to limited size

As you pointed out wokrbench is not aware that the developer tools got opened and thus the layout gets broken.

![screen shot 2016-05-24 at 15 48 14](https://cloud.githubusercontent.com/assets/1926584/15507897/aafe25fa-21cd-11e6-87bd-b85d1e5eed1d.png)

**Comment by bpasero** [comment]
This is likely because I am not aware of the fact that developer tools steel vertical space from me.

**Comment by bpasero** [comment]
Reproduces in stable already.

**Comment by bpasero** [comment]
Behaves like this since our initial release actually.

**Comment by bpasero** [comment]
Not sure this still happens with all the layout changes. But also feel free to close.

**Comment by isidorn** [comment]
Of course my awesome changes fixed this :D
