### ISSUE TITLE
"maximum amount of lines" setting for debug console

### ISSUE THREAD

**Issue by tinemlakar** [Microsoft/vscode#68100]
"maximum amount of lines" settings exists only for Integrated Terminal.

In case of many lines of debug outputs VSC starts freezing. I think the max amount of lines should be limited for better performance.

**Comment by isidorn** [comment]
@tinemlakar we already have a hardcoded limit at 10000 lines. 
However we shippped some fixes in this area. Can you still reproduce this with the latest vscode insiders?
https://code.visualstudio.com/insiders/

**Comment by kinex** [comment]
It would be nice to have this limit configurable in settings also with "unlimited" option (unlimited=clear only when a new debugging session starts). My app just hit the 10000 lines limit but I would like to see the log from the beginning.
