### ISSUE TITLE
Extra vertical spacing is incorrectly added in markdown preview when a list contains a fenced code block

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#68108]
Issue Type: <b>Bug</b>

Extra vertical spacing is incorrectly added in markdown preview when a list contains a fenced code block.

![image](https://user-images.githubusercontent.com/2301847/52417938-3300ad00-2aaa-11e9-909e-48f38c2e5e53.png)

![image](https://user-images.githubusercontent.com/2301847/52418039-722efe00-2aaa-11e9-93d7-7be34b074989.png)

VS Code version: Code - Insiders 1.31.0-insider (b313db6c58f8c02181a33cd3b5b4b17c64a5b85d, 2019-02-05T10:10:06.179Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
prettier-vscode|esb|1.8.1
flow-for-vscode|flo|1.0.1
vscode-auto-open-markdown-preview|hnw|0.0.4
sort-selection|jmr|1.0.1
vscode-styled-components|jpo|0.0.25
python|ms-|2019.1.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.5.2
java|red|0.38.0
sass-indented|rob|1.5.1
mdx|sil|0.1.0
vscode-fileutils|sle|2.13.5
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.8.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1

</details>

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by joshunger** [comment]
@mjbvz here is the text [vscode-68108-extra-spacing.md.txt](https://github.com/Microsoft/vscode/files/2842240/vscode-68108-extra-spacing.md.txt)

**Comment by mjbvz** [comment]
Thanks. Our rendering seems to match github and [commonmark](https://spec.commonmark.org/dingus/)

---

#### List with fenced code block

- List item 1
- List item 2

  ```
  fenced code block
  ```

#### List without fenced code block

- List item 1
- List item 2

---

The reason is that the first example with the fenced code block produces:

```html
<li><p>List item 1</p></li>
<li><p>List item 2</p></li>
```

while the second produces:

```html
<li>List item 1</li>
<li>List item 2</li>
```

This is covered in the commonmark spec: https://spec.commonmark.org/0.28/#list-items
