### ISSUE TITLE
Tree UI: Double click to select all + rename file doesn't work

### ISSUE THREAD

**Issue by ahinkle** [Microsoft/vscode#68105]
Issue Type: <b>Bug</b>

Something new within 1.31 - When double clicking a file within the Tree UI it doesn't allow you to select all  (within a shortened file type e.g: `example.blade.php`) to rename the file and instead forces you to single click, backspace all characters, and then rename the file.

Demo:
![demo](https://media.giphy.com/media/LTHe0hUTeCj0rcb3zC/giphy.gif)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-model-snippets|ahi|1.0.2
vscode-intelephense-client|bme|0.8.8
vscode-toggle-quotes|Bri|0.3.2
better-phpunit|cal|1.3.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.5.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
discord-vscode|icr|3.2.1
vscode-phpfmt|kok|1.0.30
dotenv|mik|1.0.1
python|ms-|2019.1.0
vsliveshare|ms-|0.3.1151
php-docblocker|nei|1.7.0
vetur|oct|0.14.5
laravel-blade|one|1.18.0
vscode-docker|Pet|0.5.2
vscode-icons|rob|8.1.0
alphabetical-sorter|ue|2.0.1
php-docblock-generator|vin|0.0.1
vscode-wakatime|Wak|1.2.5

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This is probably fixed with your changes @joaomoreno
