### ISSUE TITLE
Typescript expand selection doesn't properly handle if/else blocks 

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#68112]
Issue Type: <b>Bug</b>
```
function foo() {
        let t = 0;
        if (c) {
            foo();
        } else {
            bar();
        }
        let y = 0;
}
```

I expect Expand Selection to expand the selection to the next larger semantically significant block. However, with the cursor in one of the conditional branches, expanding the selection will never step to include only the entire conditional. It instead steps from including an entire branch of the conditional to the body of the function. Along the way it steps through including the branch but with some extraneous curly braces from the other side of the branch, which I think it should never hit.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (7.01GB free)|
|Process Argv|-psn_0_1687964|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
insert-incrementing-numbers|jac|0.0.1
Lisp|mat|0.1.8
Angular-BeastCode|Mik|7.2.2
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
vetur|oct|0.14.5
subtle-brackets|raf|3.0.0
colored-console-log|reh|1.0.7
code-settings-sync|Sha|3.2.4
vscode-multiclip|sle|0.1.5
code-spell-checker|str|1.6.10
pdf|tom|0.4.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/29071
