### ISSUE TITLE
explorer jumps around

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#68117]
* open vscode workspace
* expand node_modules-folder
* type 'typescript' and notice how it is reveal/selected
* type `arrow_right` to expand the node
* type `esc` to cancel find mode
* type `arrow_down` to navigate into 'node_modules/typescript'
* :bug: the first node_module-entry is revealed

**Comment by joaomoreno** [comment]
@jrieken I would say the issue was the scrolling up on the `esc` step. Do you agree?
