### ISSUE TITLE
new json settings UI removed significant functionality

### ISSUE THREAD

**Issue by af4jm** [Microsoft/vscode#68119]
- VSCode Version: 1.31
- OS Version: Windows 10

Steps to Reproduce:

1. File > Preferences > Settings

I've read https://code.visualstudio.com/updates/v1_31#_use-simple-text-editor-for-editing-settings-as-json... but now when I open settings, I get the global user settings only, with no way to get to the workspace or folder settings.  Is that seriously the expected behavior?  Surely the menu-like bar for User/Workspace/Folder settings should still be there, no?

Using the command pallet is a lot of extra keystrokes, and defining extra keyboard shortcuts also seems a bit over the top (and wasteful of the scant few unassigned key combinations).

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tlm-2501** [comment]
You can still get to area-specific settings by selecting the appropriate tab in the main settings UI *before* you click the "Open Settings (JSON)" icon. There is, however, no sane way to switch between setting types if you have `workbench.settings.editor: "json"` set. I will say that I am also not happy with this and it seems to be a pointless change altogether. For now, I would suggest setting `workbench.settings.useSplitJSON: true` to get the old behaviour back, at least until this is addressed properly.

**Comment by af4jm** [comment]
I did set `workbench.settings.useSplitJSON: true`, specifically because I have `workbench.settings.editor: "json"`, which means I never see the settings UI, thus always get the user settings unless I go spelunking through the file system for my workspace files.  When jumping from the UI into JSON, I can almost see the change as reasonable, but for folks like me who bypass the UI altogether, it like "wtf?"

**Comment by krupenja** [comment]
I also find this a regrettable and very unexpected change. Consider the following use case:

1. Install a new extension, say Latex Workshop.
2. You want to review the installed extension's settings and modify anything if needed.

Previously, you could do so in JSON by opening JSON settings and doing a search for "latex". With the latest change, this is no longer possible and you have to fiddle with Settings UI.

**Comment by regs01** [comment]
I just wonder, why would anyone want to use JSON settings without split editor, i.e. without seeing settings at all? It's illogical. Sounds like we are being pushed to use UI. It wouldn't be a problem if that UI wouldn't be a massive bloat. It's unusable in current state.

**Comment by cooper1x** [comment]
@tlm-2501
I have seen it, but there is only one set that I have modified. How can I see all the Settings?

**Comment by ReekyStive** [comment]
add `"workbench.settings.useSplitJSON": true` in User Settings to use the old split editor.
I think the split editor is more reasonable to change settings because we can see all the default settings on the left.

**Comment by roblourens** [comment]
Thanks for the feedback, I am going to merge this with https://github.com/Microsoft/vscode/issues/68386
