### ISSUE TITLE
"New File" does not appear in explorer view

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#68126]
Issue Type: <b>Bug</b>

This might be hard to reproduce, but in some cases, sometimes, making a new file from the Explorer tree (by right-click on a folder and selecting "New File") allows you to name the file but then the file disappears from the explorer view. I tried reopening the folder in the explorer view and I don't know of any other way to refresh the view.

Specifically I have a nested subfolder called "Views" with a bunch of files in it. I right-clicked on this folder and clicked "New File", which then allowed me to name the new file. I entered "QueryStatisticsView.cs" and hit enter. The new file opened in an editor tab, but the explorer view does not show the new file.

Additionally when I go to Windows' own explorer (I'm on Windows) I do see the new file in the "Views" folder.

I did add a new file in another folder about 10 minutes before this happened and it worked fine the first time.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
vscode-css-formatter|aes|1.0.1
csharp|ms-|1.17.1
unity-debug|Uni|2.6.6

</details>

**Comment by klick-barakgall** [comment]
Right after writing this task I found the "refresh" button hidden behind a hover over the explorer tree. I hit it and the file appears then. This is still an issue in my mind though as it should have added the file immediately to the list when we created it (or immediately after Windows finished the file creation/rename op).

**Comment by fullstackzach** [comment]
I am also experiencing this on MacOS 10.13.6 using VS Code Version 1.31.0 (1.31.0)

**Comment by isidorn** [comment]
Clsoing as dup of https://github.com/Microsoft/vscode/issues/68691 since that one has nice gif and shorter description

**Comment by klick-barakgall** [comment]
@isidorn in #68691 the new file textbox doesn't appear, and the file can not be created, no editor window is opened (if I understand correctly...)

If my impression is correct this is very different symptomatically from my issue (although maybe you have determined that the underlying issue is somehow the same, and fixing one issue will fix the other?)

Could you elaborate on how that task is related to this one?
