### ISSUE TITLE
"Add Configuration..." only works if launch.json has `configurations`

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#68128]
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create a `launch.json` with this content:

     ```json
    {
	
    }
   ```
2. Click the "Add Configuration..." button in the lower right corner.
3. Other than the cursor, flashing, nothing happens.

If there's an empty `configurations` array, it works as expected. I'm not sure if it's always been like that or if it's a recent problem.

**Comment by JoBrad** [comment]
This is still an issue for me in version 1.36.0 (not Insider's). I have to manually create a launch.json file, because VSCode won't create one at all.
