### ISSUE TITLE
Pin source control header elements when tree horizontal scroll enabled

### ISSUE THREAD

**Issue by leetosc** [microsoft/vscode#68131]
With version 1.31, horizontal scroll is now enabled for more trees and lists, including the source control view.  While this is nice, the buttons are all the way at the end, which is not ideal when there are long filenames or deeply nested files which go out of the view and require scrolling.  
Would it be possible to have the on-hover buttons for the actions (discard changes, stage changes, etc) to be fixed to the current view similar to the explorer buttons?  It is harder to use the source control as is.

Buttons are out of the view
![image](https://user-images.githubusercontent.com/13279967/52427985-ab756700-2ac6-11e9-983f-8bea4f9081fc.png)

When buttons are in view, the filename is out of view.
![image](https://user-images.githubusercontent.com/13279967/52428097-e8d9f480-2ac6-11e9-9394-a03c1908a568.png)

Fixed buttons independent of scroll:
![image](https://user-images.githubusercontent.com/13279967/52427301-56852100-2ac5-11e9-87a8-5829184c284f.png)

**Comment by joaomoreno** [comment]
Related to #68027
