### ISSUE TITLE
"Kill terminal" as last voice of context menu

### ISSUE THREAD

**Issue by teohub** [Microsoft/vscode#68133]
Issue Type: <b>Feature Request</b>

I've noticed the context menu in the Terminal tab has the voice "Kill terminal" now as last voice, whereas previously the last voice was "Clear". So now, every time I want to clear the terminal, I click "Kill terminal" because by instinct I click the last item.

So my suggestion is to not change UX behaviour when you update version.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

This is related to https://github.com/Microsoft/vscode/issues/67033

**Comment by Tyriar** [comment]
This was by design as per #67033, if you're on mac there's a default keybinding of cmd+k for clear which is typically used in more terminals so I'd recommend getting used to that.
