### ISSUE TITLE
Settings error message is cropped off

### ISSUE THREAD

**Issue by ducktin** [Microsoft/vscode#68134]
Issue Type: <b>Bug</b>

1. Go to settings
2. Search for 'tree'
3. Add invalid value to the Tree:Indent setting (last item in the settings list)

The error message is not be fully visible:
![vs code bug](https://user-images.githubusercontent.com/12184079/52429248-f5c90900-2b03-11e9-8151-73b778a3e9d6.PNG)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
FYI @joaomoreno I will also need to override `overflow` on `monaco-list-rows`

**Comment by joaomoreno** [comment]
Sure, go for it.
