### ISSUE TITLE
Have webview taking the full available space

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#68137]
currently there is some space on right and left sides

I noticed that the padding is set to 20px https://github.com/Microsoft/vscode/blob/35523f6c51bdc1edae1696a586dadd021fe47096/src/vs/workbench/contrib/webview/electron-browser/webview-pre.js#L420

i think it would be better to 0.

for instance we will have:
![image](https://user-images.githubusercontent.com/1105127/52429568-95869700-2b04-11e9-9573-50c753822fe8.png)
instead of truncated top bar:
![image](https://user-images.githubusercontent.com/1105127/52429610-aafbc100-2b04-11e9-8134-172de7c757f3.png)

**Comment by mjbvz** [comment]
We provide some reasonable default styles so that content without good stylesheets doesn't look terrible. You can use css in your webview to override these
