### ISSUE TITLE
contentprovider-sampler: remove 'out' folder from repository

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6813]
testing https://github.com/Microsoft/vscode/issues/6675:

- Remove 'out' folder from contentprovider-sampler sample. The other samples do not have the generated code and maps either.

- The contentprovider-sampler does not have a '.vscode' folder with launch configuration. This is inconsistent with the other sample folders.

**Comment by jrieken** [comment]
fixed by https://github.com/Microsoft/vscode-extension-samples/commit/aa698ac289915429556b462b75fb3a5a3cc901dd

**Comment by weinand** [comment]
@jrieken oops, I just noticed another inconsistency and added it here while you were closing this...

**Comment by jrieken** [comment]
ok - reopen

**Comment by weinand** [comment]
@jrieken where does the folder 'etc' come from?

**Comment by jrieken** [comment]
I have no clue, maybe @aeschli knows?

**Comment by jrieken** [comment]
added the `.vscode` folder with https://github.com/Microsoft/vscode-extension-samples/commit/e08c1d4bc04ac74e998217c3ae2344bc889dc045

**Comment by aeschli** [comment]
I'm also puzzled by the occasional showing up of the etc folder.
