### ISSUE TITLE
Problem with Node debugger inside Vagrant machine in 1.31.0

### ISSUE THREAD

**Issue by NoodleSmythe** [microsoft/vscode#68139]
- VSCode Version: 1.31.0
- OS Version: Ubuntu 18.04

Since today's update to 1.31.0, VSCode can't see Node source maps for my TypeScript server project, and therefore can't hit any breakpoints.

I have 2 separate projects, that use similar structure and are both broken. Node is running inside an Ubuntu 18.04 VM scripted with vagrant. Nothing has changed in either project, but both have died coinciding with this release.

The debugger works on other non-upgraded machines on the same source.

```
{
    "version": "0.2.0",
    "configurations": [        
        {     
            "localRoot": "${workspaceFolder}/Web/Server/src",
            "remoteRoot": "/home/vagrant/Web/Server/src",                                
            "type": "node",
            "request": "attach",
            "name": "Attach to Server on 9229",
            "address": "192.168.101.7",
            "port": 9229,
            "stopOnEntry": true,
            "sourceMaps": true
        }    
    ]
}


```

Steps to Reproduce:

1. Boot Vagrant box, start node server
2. Attach debugger - all breakpoints greyed out. Intellisense tells me "Breakpoint ignored because generated code not found. (Source map problem)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you set `"trace": true`, run it again, and upload the log here?

**Comment by NoodleSmythe** [comment]
Hi Rob,

Here's the file. I hope it's what's needed.

[telemetry.log](https://github.com/Microsoft/vscode/files/2842420/telemetry.log)

**Comment by NoodleSmythe** [comment]
For completeness, here's log with extensions disabled.

[telemetry_noextentions.log](https://github.com/Microsoft/vscode/files/2842450/telemetry_noextentions.log)

**Comment by NoodleSmythe** [comment]
My mistake, try this one.
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2842894/debugadapter.txt)

**Comment by roblourens** [comment]
Are you sure it started successfully that time? The log shows that the debugger never actually attached and errored with "Cannot connect to runtime process, timeout after 10000 ms". I need a log where you attempted to set a breakpoint and it failed.

**Comment by NoodleSmythe** [comment]
Lesson: never attempt to multi-task late at night.
[debugadapter_1.31.0.txt](https://github.com/Microsoft/vscode/files/2844241/debugadapter_1.31.0.txt)
[debugadapter_1.30.2.txt](https://github.com/Microsoft/vscode/files/2844242/debugadapter_1.30.2.txt)

Here is the log running identical code from the same repo on 2 different (K)Ubuntu 18.04 machines.
One has 1.31.0, the other (that still works) is running 1.30.2.
A third machine, running 1.31.0 on Ubuntu 18.04 also failed.

**Comment by roblourens** [comment]
It seems like now it's looking for the sourcemap with the remote path instead of the local path.

```
SourceMaps.loadSourceMapContents: Could not read sourcemap file - ENOENT: no such file or directory, open '/home/vagrant/Web/Server/dist/Modules/API/prescriptions/controllers/api.order.controller.js.map'
```

**Comment by roblourens** [comment]
Can you try making your localRoot/remoteRoot less specific by removing the 'src' part? Not sure what changed on my end.

**Comment by NoodleSmythe** [comment]
It works!
I changed
```
            "localRoot": "${workspaceFolder}/Web/Server/src",
            "remoteRoot": "/home/vagrant/Web/Server/src",
```
to
```
            "localRoot": "${workspaceFolder}/Web/Server",
            "remoteRoot": "/home/vagrant/Web/Server",
```

**Thank you** for your help. 

I suppose we could do with knowing what's going on that causes this, so others don't experience the same. Was there anything that pointed to my hosts, or is this a Code issue?

**Comment by drakenfly** [comment]
Hi! I got the same problem with remote debugging, where VScode always opens the inlined source maps instead of using the source files; even though localRoot and remoteRoot are configured properly.

`
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Remote",
            "address": "10.2.1.2",
            "port": 9229,
            "localRoot": "${workspaceFolder}/frontend",
            "remoteRoot": "/code"
        },`

Where the package.json is on the Windows host is in ${workspaceFolder}\frontend\package.json and inside the remote machine in '/code/package.json'.
