### ISSUE TITLE
Keymaps nonfunctional after tree widget update

### ISSUE THREAD

**Issue by NeelPi** [Microsoft/vscode#68138]
Issue Type: <b>Bug</b>

install any keymap like atom keymap, press a in the workspace on create new file, type in tree instead

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.18329

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (4.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.23.0
jshint|dba|0.10.20
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.6.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.8
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|7.2.2
python|ms-|2019.1.0
atom-keybindings|ms-|3.0.5
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1151
vscode-docker|Pet|0.5.2
java|red|0.38.0
LiveServer|rit|5.4.0
code-settings-sync|Sha|3.2.4
vscodeintellicode|Vis|1.1.2
vscode-react-native|vsm|0.8.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by NeelPi** [comment]
Current fix is to set the Keyboard Navigation setting to simple

**Comment by auchenberg** [comment]
We shipped an update to the atom keymap which should be fixing this, https://github.com/Microsoft/vscode-atom-keybindings/releases/tag/v3.0.6
