### ISSUE TITLE
Exception breakpoint turns line invisible with high contrast theme

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#68136]
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open any workspace with a launch configuration and a debugger that supports exception breakpoints, in this example an empty VSCode extension that just throws an exception timeout (after a timeout so the extension doesn't fail to activate).

    ```ts
    'use strict';
    import * as vscode from 'vscode';

    export function activate(context: vscode.ExtensionContext) {
        setTimeout(() => {
            throw "foo";        
        }, 1000);
    }
    ```
2. Check the "Uncaught Exceptions" breakpoint filter.
3.  Start Debugging.
4. Observe that when the debugger breaks, the line the exception is thrown on is now invisible. Selecting the text makes it show up again.

    ![](https://i.imgur.com/Hj2Ivak.png)

Not sure how long it's been like that, but this was already an issue with 1.30.

**Comment by v-kydela** [comment]
I have just experienced this myself. What a coincidence that this bug was only submitted two hours ago.

**Comment by isidorn** [comment]
Thanks for catching this. You can try it out from Thursdays vscode insiders and let us know if this fixed the issue for you.

**Comment by Gama11** [comment]
Yep, appears to work fine now in the current Insider's build. 👍

**Comment by isidorn** [comment]
Great, thanks. Adding verified label
