### ISSUE TITLE
closeActiveEditor shortcut no longer working on Version 1.31.0

### ISSUE THREAD

**Issue by gabrielbull** [Microsoft/vscode#68144]
- VSCode Version: 1.31.0
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Use closeActiveEditor shortcut
2. Does nothing

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@gabrielbull what keyboard layout do you use and what shortcut is the action bound to? The default works for me.

**Comment by gabrielbull** [comment]
Keyboard layout is "Français canadien (CSA)" and shortcut is CMD+W, assigning other shortcuts does nothing.

**Comment by gabrielbull** [comment]
Any update on this one? This is a pretty big deal breaker, this is probably one of the most used shortcuts in VSCode.

**Comment by alexandrudima** [comment]
@gabrielbull I cannot reproduce, after installing the "Canadian French - CSA" keyboard layout, pressing `cmd+w` works for me and closes the current active editor.

![Kapture 2019-03-28 at 22 46 31](https://user-images.githubusercontent.com/5047891/55194976-65c24a00-51ab-11e9-88af-895e09414fdc.gif)

Does VS Code receive the keybinding on your machine?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
