### ISSUE TITLE
Code.bat fails on JPSoft's TCCLE terminal

### ISSUE THREAD

**Issue by TMox** [Microsoft/vscode#68141]
Issue Type: <b>Bug</b>

In scripts\code.bat, line 11, we search product.json for 'nameShort' and tokenize the line with ':,'. The second token (%%a), is now '<space>"Code - OSS"'. The use of %%~a in setting NAMESHORT is supposed to strip the quotes, but in cmd.exe (Windows 10) it doesn't, so the following two lines (12 & 13) work around this by replacing '<space>"' with '' and '"' with '.exe' respectively. In cmd.exe, this gives us what we want: 'Code - OSS.exe". In my favorite terminal, JPSoft's tcc (I use TCCLE14x64), the %%~a does strip the quotes, so line 12 does nothing and line 13 simply adds '.exe' to the end. I get NAMESHORT = '<space>Code - OSS.exe' which is an invalid file name. 
To fix the problem, replace %%~a with %%a, which doesn't strip the quotes in line 11 on terminals which behave correctly. In this case, the cmd.exe work-around lines 12 & 13 work as planned in cmd.exe as well as tcc.

VS Code version: code-oss-dev 1.32.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (3.27GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by msftrncs** [comment]
In Batch, the notation `%%~a` on a FOR statement does remove the outside quotes only (they must be on the outside edges of the string, and the string must start with a quote!, In this case, it does not.).    Anything that is emulating Batch needs to perform the same way, or scripts will definitely not work the same.  However, I fail to see why TCC wouldn't work here.  Both situations should result in `Code - OSS.exe`, which then becomes `".build\electron\Code - OSS.exe"` in the variable %CODE%.

**Comment by TMox** [comment]
OK. Since the line in product.json has a space after the colon, %%~a doesn't remove the quotes (now I see why this isn't a bug in cmd.exe--quote isn't the first character!). I guess tcc is the buggy one, in that it (seemingly) ignores that leading space and goes ahead and removes the quotes, but it leaves the space in. tcc's final %CODE% is ".build\electron\<space>Code - OSS.exe". Removing the ~ fixes this, and it serves no purpose in cmd.exe, so removing it doesn't break cmd, though it's a cludge rather than an actual fix. I wonder how other terminal programs handle this.
