### ISSUE TITLE
"add cursor above/below" broken; right alt isn't captured as ctrl+alt

### ISSUE THREAD

**Issue by MikeKovarik** [Microsoft/vscode#68149]
- VSCode Version: 1.31 (Janury 2019)
- OS Version: Windows 10 1809

Steps to Reproduce:

1. click into editor
2. press right alt + arrow up
3. cursor moves to line above instead of extending it into the other line.

or

1. edit any keybinding so that the "press desired key combination" popup appears
2. press right alt
3. only "alt" appears instead of "ctr+alt"

I do not have any specific graphics driver or any exotic software. Nearly clean installation of the OS. Things broke once I upgraded to latest VSC. Downgrading to 1.30 fixed it for me.

**Comment by rebornix** [comment]
Shares the same root cause as https://github.com/Microsoft/vscode/issues/68003
