### ISSUE TITLE
File is not highlighted in type to filter after renaming

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#68147]
- Rename a file in the explorer
- Type its name
- Its matching name is not highlighted

![image](https://user-images.githubusercontent.com/323878/52433760-a1516980-2ac2-11e9-9a2f-0712e763c713.png)

- Use filter mode
- "No elements found" but the row is visible

![image](https://user-images.githubusercontent.com/323878/52433785-af9f8580-2ac2-11e9-8e44-f28f65180e40.png)

**Comment by isidorn** [comment]
@joaomoreno do I need to do something on the explorer side for this?
It is the same element, just with a different keyboardNavigationLabel.
Do I need to notify the tree somehow that the keyboardNavigationLabel has changed?

**Comment by joaomoreno** [comment]
This seems fixed.
