### ISSUE TITLE
API Request - Snippet mode in the background

### ISSUE THREAD

**Issue by jamesplease** [Microsoft/vscode#68143]
### Issue Type

Feature request

### What is the feature?

I am requesting that non-active editors be updated to support entering Snippet mode _without_ making the editor active.

### What is the current behavior?

If the following LoC is run from an extension

```js
const snippet = new vscode.SnippetString('Snippet $1');
const position = new vscode.Position(0, 0);

nonActiveEditor.insertSnippet(snippet, position);
```

then the `nonActiveEditor` will become active. I would like an API that allows the editor to remain inactive but in Snippet mode.

### How would this behave?

When the user manually navigates into an inactive editor that is in snippet mode, the snippet mode "editing behavior" would be initiated.

If the user closes the file before navigating, then the behavior would be the same as pressing "Esc" while editing a Snippet: the current values of all of the placeholders will be applied to the file.

### What is the use case?

Sometimes I create `n` files of a similar type at a time. These files sometimes share the same name and values. For instance, I might create:

```
- some-component.css
- some-component.js
```

I'm trying to make an extension that allows a user to define templates that are arrays of files, so that a collection of related files could be created in one command.

When they enter a file name, such as `some-component`, the extension loops through the array of files and creates each file. Given the power of VSCode snippets, I would like to be able to leverage that experience when it comes to updating the created files.

However, right now I'm unable to create `n` files in Snippet mode. If you call `insertSnippet` in a tight loop on numerous editors, the behavior can be strange!

### Possible API

A `makeEditorActive` boolean (the name could be whatever y'all think is best) could be added to the `options` object of `insertSnippet`. It would default to `true` for backwards compatibility.

```js
nonActiveEditor.insertSnippet(snippet, position, {
  makeEditorActive: false
});
```

### Next steps

Although I haven't contributed to VSCode, I might be able to give it a go to try and change this behavior. Before I do, though, would any maintainer consider merging a PR that introduces this behavior? If so, do you have a general sense of the scope of the change? Do you think it could be straightforward, or would it be a massive undertaking?

If you don't think that this change makes sense for VSCode, it's no big deal. I know y'all are super busy, and this is probably a niche request. I appreciate you taking the time to read this issue and consider it either way!

**Comment by jrieken** [comment]
Apart from the user experience that I think is questionable, this isn't implementable with the vscode API. Reason being is that a `TextEditor` is always a *visible* editor showing a document, the is *no* representation for "editors" that don't show.

**Comment by jamesplease** [comment]
No problem. Thanks for reviewing this @jrieken !

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/53280 is something you might interested in. It's about enter snippets mode "after the fact". E.g you make your (textual) change and after that you can enter snippet mode on that.

**Comment by jamesplease** [comment]
Oh, cool. Thanks for linking that issue here! I can see how I could potentially use something like that to create this plugin.
