### ISSUE TITLE
Terminal warning running code when there is an apostrophe's in the program path

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/vscode#68151]
@martinohanlon commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4311)

## Environment data

- VS Code version: 1.30.2 (user setup)
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: Windows 10 version 1803
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
- Relevant/affected Python packages and their versions: n/a

## Expected behaviour

When I run a Python program using Ctrl F5 I dont expect to see an error.

## Actual behaviour

When I run a Python program using Ctrl F5 I see the error / warning in the terminal.

```
PS C:\Users\Martin O'Hanlon-LT> cd 'c:\Users\Martin O'Hanlon-LT\Documents\temp'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\Martin O''Hanlon-LT\AppData\Local\Programs\Pyt:\Users\Martin O''Hanlon-LT\AppData\Local\Programs\Python\Python36\python.exe' 'c:\Users\Martin O''Hanlon-LT\.vscode\extensions\ms-python.python-20lient' '--host' 'localhost' '--port' '62982' 'c:\Users19.1.0\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '62982' 'c:\Users\Martin O''Hanlon-LT\Documents\temp\helloworld.py'                                                                                                                                        ppData\Local\Programs\Python\Python36\python.exe' 'c:\>> cd 'c:\Users\Martin O'Hanlon-LT\Documents\temp'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\Martin O''Hanlon-LT\Alocalhost' '--port' '62985' 'c:\Users\Martin O''HanlonppData\Local\Programs\Python\Python36\python.exe' 'c:\Users\Martin O''Hanlon-LT\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py' '--default' '--nodebug' '--client' '--host' 'localhost' '--port' '62985' 'c:\Users\Martin O''Hanlon-LT\Documents\temp\helloworld.py'      NBUFFERED}=1; & C:\Users\Martin'.
Set-Location : A positional parameter cannot be found that accepts argument 'Hanlon-LT\Documents\temp; ${env:PYTHONIOENCODING}=UTF-8; ${env:PYTHONUNBUFFERED}=1; & C:\Users\Martin'.
At line:1 char:1
+ cd 'c:\Users\Martin O'Hanlon-LT\Documents\temp'; ${env:PYTHONIOENCODI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

## Steps to reproduce:
1. Create a folder with an apostrophe `'` in the name
2. Save a Python program to that folder
3. Run the Python program

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
[blank]
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[blank]
```

---

@d3r3kk commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4311#issuecomment-461548769)

Upstream to VS Code itself, shell quoting for paths sent to the debugger provider.

**Comment by DonJayamanne** [comment]
@weinand 	
Not sure how this is caused by the extension, the extension is passing the information to the debugger (via the protocol ) to launch the debugger in the terminal.
At this point it is VSC that sets the `cd` command, i.e. problem lies with VS Code not the extension.
Here's the code:
https://github.com/Microsoft/vscode/blob/314cc521d8ce0c55773850ef520095afde33a62c/src/vs/workbench/parts/debug/node/terminals.ts#L365

**Comment by weinand** [comment]
@DonJayamanne since we do not know how an extension is implemented, we let the extension author investigate issues like this first. If you are sure that an issue is not an extension issue, just let us know and we take the issue back.

**Comment by meganrogge** [comment]
@weinand when I follow these steps, I get:

$ C:/Users/Megan/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Megan/vscode/.vscode/notebooks/meg's/test.py
> C:/Users/Megan/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Megan/vscode/.vscode/notebooks/meg's/test.py
C:\Users\Megan\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'c:\Users\Megan\vscode\.vscode\notebooks\megs\test.py
C:\Users\Megan\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Megan\vscode\.vscode\notebooks\megs\test.py': [Errno 22] Invalid argument

**Comment by weinand** [comment]
@meganrogge I do not quite understand what you did to verify my fix, but your result from above suggests that you did not use PowerShell.

To recapitulate you have to:
- ensure that you use PowerShell in the integrated terminal,
- install the Python extension
- either create a launch config for running a Python program or open a Python program in the editor
- press "Ctrl F5" to "Run Without Debugging".

In the integrated terminal you should see something similar to the PowerShell output from the [initial comment](https://github.com/microsoft/vscode/issues/68151#issue-407843140). The fix should escape the problematic `'` character in the "cd" command by doubling it.
