### ISSUE TITLE
venv activation has 1 second delay

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode#68157]
@jonashaag commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4312)

## Environment data

- VS Code version: 1.31.0 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
- Extension version: 2019.1.0
- OS and version: macOS 10.14.1
- Python version: 3.7
- Type of virtual environment used: venv 
- Relevant/affected Python packages and their versions: none

## Expected behaviour

`source` command has no delay.

## Actual behaviour

`source` command has 1 second delay. See demo video: https://imgur.com/a/YJIX6sC

## Steps to reproduce:

Open terminal.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

Nothing

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
(3x) [Extension Host] Python Extension: Cached data exists getEnvironmentVariables, /Users/j/dev/cl/cashlink/cl-backend
```

---

@d3r3kk commented on [Thu Feb 07 2019](https://github.com/Microsoft/vscode-python/issues/4312#issuecomment-461558448)

This delay is introduced when we send information to the VS Code terminal provider.

**Comment by DonJayamanne** [comment]
@tyriar please close this issue.
It wasn't meant to be filed upstream

**Comment by Tyriar** [comment]
Should be an extension issue, I'm commenting over there.
