### ISSUE TITLE
Option click on a typescript definition in a monorepo jumps to the definition file instead of the original source file

### ISSUE THREAD

**Issue by natew** [Microsoft/vscode#68154]
This has been a persistent frustration so figured it’s time to log it. 

With a monorepo of typescript packages that have generated definition files, when you option click on VSCode to see one definition, it jumps to the out/*/.d.ts instead of the corresponding src/*/.ts file. It would be nice to have an option to make it look for the input file rather than definition as that would be far more productive.

**Comment by mjbvz** [comment]
Does this work properly if you enable the `declarationMap` feature in typescript? See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html for an overview of the feature. It should enable the generation of map files that map between the generated `d.ts` and the original `ts` file

**Comment by natew** [comment]
Woah. This should be strongly recommended in VSCode! Thanks for pointing out.

**Comment by mjbvz** [comment]
Ok, closing this issue since it sounds like adding that flag fixed the problem
