### ISSUE TITLE
package.json of development extension installs is modified in 1.31

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#68156]
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

This is closely related to #25159, but I feel like this is still a distinct problem. While VSCode hasn't officially supported the concept of "development extension installations", this has still worked fine in the past for many developers. Now with 1.31, VSCode has introduced some problems with this workflow.

Steps to Reproduce:

1. Clone an extension into the `.vscode/extensions` directory.
2. Start VSCode 1.31 - a diff will show that the `package.json` has been modified. This was not the case with VSCode 1.30 or earlier.

    ![](https://i.imgur.com/ZkbbZSx.png)

I'm not sure if there's any negative effects of publishing an extension with this `__metadata` field already present, but it's bound to happen to some developers. Beyond that, it's also annoying to always have uncommitted changes due to this behavior.

If the `package.json` was formatted with spaces instead of tabs prior to VSCode modifying it, the entire file will show as changed.

**Comment by kieferrm** [comment]
This is an unsupported workflow. The `.vscode` directory is internal to VS Code and we'll make any kind of changes in there we see fit. We keep #25159 open to discuss.
