### ISSUE TITLE
VSCode version distribution dashboard for extension authors

### ISSUE THREAD

**Issue by johnspurlock** [microsoft/vscode#68162]
It would be nice to have a regularly-updated published breakdown of the pct of active vscode installs by stable version, similar to Android's [Platform Version Distribution Dashboard](https://developer.android.com/about/dashboards/#Platform).

This would give extension authors information on which versions of the extension api to support at a given point in time.

Thanks!

**Comment by dlebu** [comment]
Any update here?

**Comment by anurbol** [comment]
Since I have this [issue](https://github.com/microsoft/vscode/issues/85939) I'd like so much to see what is the version distribution among the users, in order to decide should I focus on the latest versions or should I support some old versions as well if they are still popular.

**Comment by chrisdias** [comment]
@fiveisprime don't we have this now for publishers?

**Comment by fiveisprime** [comment]
We don't, but I'll get this on the list for the metrics work.

**Comment by fiveisprime** [comment]
FYI @prashantvc

**Comment by fiveisprime** [comment]
Just so you all know. This is closed on VS Code, but it's still being tracked on the marketplace side.

**Comment by johnspurlock** [comment]
Not sure I understand, is there a link to that issue?  If not, why not leave this one open?  It's still unresolved.

**Comment by fiveisprime** [comment]
@prashantvc any updates on a public issue tracker?
