### ISSUE TITLE
"Search: Refresh" triggers the error "Cannot read property 'isSearchSubmitted' of undefined"

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/vscode#68168]
Issue Type: <b>Bug</b>

1- Open a new Vscode window.
2- Ctrl+Shift+P to open the command menu 
3- Run the command "Search: Refresh"

The error "Cannot read property 'isSearchSubmitted' of undefined" is displayed.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (7.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kieferrm** [comment]
This happens when the Search viewlet has not been created yet.
