### ISSUE TITLE
Configure Tab Size is not working

### ISSUE THREAD

**Issue by ratanahing** [microsoft/vscode#68163]
Issue Type: <b>Bug</b>

After latest update, vscode break on indentation. I tried to change tab size to 4, but it always come back to 2.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (2.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.10
python|ms-|2019.1.0
laravel-blade|one|1.18.0
java|red|0.38.0

</details>

**Comment by kieferrm** [comment]
Can you pls provide concrete steps? What file you open, what setting you change etc. Thanks!
