### ISSUE TITLE
Control backspace/delete in powershell and cmd terminal should delete word

### ISSUE THREAD

**Issue by damongr-msft** [Microsoft/vscode#68167]
Issue Type: <b>Bug</b>

Repro: 
1. Open terminal (powershell or cmd)
2. type "dir foo"
3. Press control-backspace
Result: dir foo^W
Expected: dir

Generally the same thing happens with control-delete when cursor is on the "f" in foo, it should delete the foo word, in the terminal it doesn't do anything.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (12.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
gc-excelviewer|Gra|2.1.28
vscode-antlr4|mik|2.1.1
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
java|red|0.38.0
vim|vsc|1.0.7

</details>

**Comment by Tyriar** [comment]
I actually spoke with @TylerLeonhardt from the PowerShell team yesterday about exactly this and now know why it doesn't work. PSReadLine does not have a keybinding when set toe "Windows" edit mode for ^W which is what our terminal emits. To get this to work by manually assigning the right keybinding to ctrl+w or run this:

```
Set-PSReadLineOption -EditMode Emacs
```
