### ISSUE TITLE
Window Crash

### ISSUE THREAD

**Issue by ohlfsen** [Microsoft/vscode#68178]
Issue Type: <b>Bug</b>

Get this

***
"Microsoft Visual C++ Runtime Library 
(5) Assertion failed! 
Program: ...es.asar.unpacked\node-pty\build\Release\winpty.dll File: d:\aVI \Anode_modules\node-pty\deps\winpty\...\winpty.cc Line: 924 
Expression: ASSERT_CONDITION("wp != nullptr && cols > 0 && rows > 0") 
For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts 
(Press Retry to debug the application - AT must be enabled) 
Afbryd 
Forsog igen 
Ignorer"
***

When running release  installed  with VSCodeUserSetup-x64-1.31.0

followed by message of "Window Crash". 

Some times pushing retry will then open VS Code, sometimes it can not be started at all.

Uninstalling and reverting back to version 1.30.2 seems to fix the issue.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (25.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
al|Mic|2.0.56865
PowerShell|ms-|1.11.0

</details>

**Comment by limonte** [comment]
Same here. This is happening every 15-30 minutes. Extremely annoying.

**Comment by jimpriest** [comment]
Same here.  Have been disabling extensions to see if it's related but the crashes occur very randomly.  

Windows 10.  v1.31.1.  I was not seeing crashes with 1.30.

**Comment by rickbutton** [comment]
I am also seeing this bug in the new build, did not see it in 1.30

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
