### ISSUE TITLE
Built-in git extension is disabled. Jan 2019 update

### ISSUE THREAD

**Issue by SFDCPirate** [Microsoft/vscode#68179]
**version** 1.31

**Issue**: Git extension gets disabled with the new update but it shows as enabled when you go to settings.

To fix, I had to disable git option => quit vscode => re-open vscode => enable git => quit vscode => re-open vscode.

**Comment by sandy081** [comment]
@SFDCPirate What do you mean by disable git option? Are you doing it in settings or in extensions view?

**Comment by MG-RX93** [comment]
This setting under the git extension.

![image](https://user-images.githubusercontent.com/33265241/52670512-9b49f700-2ecd-11e9-9f2e-d6b6d724a16f.png)

**Comment by sandy081** [comment]
@joaomoreno Looks like git is enabled/disabled from settings. Forwarding it to you.

**Comment by joaomoreno** [comment]
@SFDCPirate What makes you say the extension is disabled?

**Comment by SFDCPirate** [comment]
Well, git didn't work when I made changes on a file in git repo. The blue line I see on the left of margin just stopped showing up. I can't remember what happened when I tested with git commands but it was wonky. 

As I've described, it was showing as enabled but I had to disable and re-enable the Git: Enabled setting and I happen to have a mac.

**Comment by joaomoreno** [comment]
Alright. Closing for now since you're unblocked.
