### ISSUE TITLE
Git installation not found on Mac OS Mojave when launched from Finder or Spotlight

### ISSUE THREAD

**Issue by rossipedia** [Microsoft/vscode#68172]
- VSCode Version: 1.31.0 (also reproduced on Insiders 1.32.0-insider)
- OS Version: Mac OS 10.14.2
- XCode Version: 10.1
- Git Version: 2.17.2 (Apple Git-113)
- Shell: ZSH 5.7

Steps to Reproduce:

1. Ensure XCode 10.1 is installed, including Command Line Tools (accept the license agreement)
2. Disable all VS Code extensions
3. Create empty folder
4. Initialize a git repository with `git init .`
5. Open VS Code from either Finder, Launchpad, Spotlight, or the Dock
6. Open the folder you created

A message pops up saying "Git not found"

* _Does this issue occur when all extensions are disabled?:_ Yes

This does not occur at all when code is launched from the command line

I've created a screen recording that demonstrates the issue:

[![](https://img.youtube.com/vi/j9J-bQKw5gY/0.jpg)][1]

[1]: https://www.youtube.com/watch?v=j9J-bQKw5gY

**Comment by joaomoreno** [comment]
Where is git installed? `which git`?

**Comment by rossipedia** [comment]
Git is from XCode. Install path is `/usr/bin/git`, which you can see in the screen recording I took.

`process.env` from Code opened via Finder is:

```json
{
  "TMPDIR": "/var/folders/sf/h2ltsw412b7855b0vq54rybcqm06kp/T/",
  "__CF_USER_TEXT_ENCODING": "0x2F401A56:0x0:0x0",
  "SHELL": "/bin/bash",
  "HOME": "/Users/bryan.ross",
  "Apple_PubSub_Socket_Render": "/private/tmp/com.apple.launchd.PA7nmd3b6B/Render",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.8ifTJ4QLow/Listeners",
  "PATH": "/Users/bryan.ross/.cargo/bin:/Users/bryan.ross/.cargo/bin:/usr/local/opt/llvm/bin:/usr/local/opt/mysql-client/bin:./node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS",
  "LOGNAME": "bryan.ross",
  "XPC_SERVICE_NAME": "com.microsoft.VSCode.31700",
  "USER": "bryan.ross",
  "XPC_FLAGS": "0x0",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}",
  "VSCODE_NODE_CACHED_DATA_DIR": "/Users/bryan.ross/Library/Application Support/Code/CachedData/7c66f58312b48ed8ca4e387ebd9ffe9605332caa",
  "VSCODE_LOGS": "/Users/bryan.ross/Library/Application Support/Code/logs/20190210T012846",
  "VSCODE_IPC_HOOK": "/Users/bryan.ross/Library/Application Support/Code/1.31.0-main.sock",
  "VSCODE_PID": "91171",
  "CLICOLOR": "1",
  "EDITOR": "gvim -f",
  "GPG_TTY": "not a tty",
  "JABBA_HOME": "/Users/bryan.ross/.jabba",
  "LSCOLORS": "exfxcxdxcxegedabagacae",
  "PWD": "/",
  "SHLVL": "1",
  "_": "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"
}
```

**Comment by fabriciomirandabr** [comment]
I have the same problem here.

**Comment by joaomoreno** [comment]
What git version do you have installed?

**Comment by fabriciomirandabr** [comment]
I gave up and reinstalled my system, my git version was 2.20.1

**Comment by rossipedia** [comment]
```sh
$ git --version
git version 2.17.2 (Apple Git-113)
```

**Comment by joaomoreno** [comment]
Can you show me what's on the git output? Command palette, `Git: Show Git Output`

**Comment by upugo-dev** [comment]
I also had this issue. Seemed to have an installation of git because `which git` yielded to `/usr/bin/git` but this was merely a simlink/path, I'm unsure where the actual installation was (probably from XCode), and I thought maybe VScode was having a hard time following the simlink. 

So I tried installing git from the recommended location https://git-scm.com/, so there was an actual installation in /usr/bin/git, still receiving the error git not found.

I tried running git status in a terminal (outside of VScode) and found to my surprise: 

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

A quick google yielded https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-mojave-update-xcrun-error-invalid-active-devel

Simply running `xcode-select --install`, updating Xcode Command Line tools and reloading VScode fixed the problems for me

**Comment by jnelken** [comment]
@upugo-dev I already have `xcode-select` installed and so this did not fix the problem for me. However, putting `"git.path": "/usr/local/bin/git",` in my `settings.json` does fix the error. It's still unclear as to why i need to do this however.

**Comment by upugo-dev** [comment]
> @upugo-dev I already have `xcode-select` installed 

From memory, the `--install` command is equivalent to updating Xcode CLI, if you have an existing installation. I also already had it installed, did you try the update?

Strange that hardcoding your path worked though, I tried that too with no success, also ensured that `git` was in my system PATH. The update worked perfectly for me though, even after reverting all the additional settings I had made to try and fix this

**Comment by jnelken** [comment]
When I run `xcode-select --install` I see `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`. Eventually found out that xcode did need to be updated using `softwareupdate --list` and updated it with `softwareupdate --install -a`. Not entirely straightforward but this is now fixed for me! Thanks @upugo-dev
