### ISSUE TITLE
"Open to side" opens search result twice

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#68176]
- Set `"workbench.list.openMode": "doubleClick"`
- cmd+click search result
- It opens twice

**Comment by zachlitz** [comment]
This also affect opening single files. It only happens if the `workbench.list.openMode` is set to double click.

* Set `"workbench.list.openMode": "doubleClick"`
* Go to the explorer and double click on a file while holding the "alt" key

The file will open two new side by side editors.

**Comment by roblourens** [comment]
I think this is actually a tree bug because the tree fires `onDidChangeSelection` multiple times. It also reproes on the explorer (use alt+click)
