### ISSUE TITLE
Git extension picks up unopened folder

### ISSUE THREAD

**Issue by vnl** [Microsoft/vscode#68173]
- VSCode Version: Version 1.31.0 (1.31.0)
- OS Version: macOS 10.14.4 (Beta)

Steps to Reproduce:

Just opening the vscode picks up the Android cache for some reason. 
<img width="418" alt="screenshot at feb 07 21-20-20" src="https://user-images.githubusercontent.com/1355466/52444120-69c4da80-2b1f-11e9-8be3-7e04176aef6f.png">
<img width="464" alt="screenshot 2019-02-07 at 21 17 08" src="https://user-images.githubusercontent.com/1355466/52444164-86611280-2b1f-11e9-871b-2877fb911913.png">

I have uninstalled and re-installed vscode but still picks up the same folder, if I open any git repo. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
It seems that you opened your home directory as a folder in VS Code. When you quit and relaunch we restore the window. Launch VS Code either with a new window using
```
code -n
```

or directly from the folder you want to open:
``` 
cd <your folder>
code .
```

**Comment by vnl** [comment]
Understandable, but is there a way to just clear all the cache and start fresh?

**Comment by chrisdias** [comment]
Is the `learningmenubarapp` a folder beneath your home folder?  As @kieferrm mentioned above, it looks like your home folder is a git repository.  you may have run `git init` in that folder at some point in the past.  When you are in a sub folder of a git repo that will get picked up.

You can confirm by seeing if there is a `.git` folder in your home directory; 

```
cd
cd .git
```

You probably don't want that folder to be a repo, so you can probably just delete the `.git` folder, but that is up to you to decide :)

**Comment by vnl** [comment]
Thanks, @chrisdias That was it... problem solved.
