### ISSUE TITLE
Outline has stopped working

### ISSUE THREAD

**Issue by 11JoseMarcos11** [Microsoft/vscode#68175]
Hello, everyone. I upgraded my vscode to version 1.31, but after this update the outline stopped working. The variables and methods of PHP no longer appear. How do I activate the outline?

![screenshot_20190207_200637](https://user-images.githubusercontent.com/27087437/52446054-07b2a800-2b14-11e9-8fd7-47c7817c2611.png)
![screenshot_20190207_200804](https://user-images.githubusercontent.com/27087437/52446076-1c8f3b80-2b14-11e9-9949-26a349930230.png)

**Comment by 11JoseMarcos11** [comment]
I found no open post with the same problem as my.

**Comment by kieferrm** [comment]
This seems to be an issue with your PHP extension. Please file an issue there. Thanks!

**Comment by 11JoseMarcos11** [comment]
Perfect kieferrm. The extension has actually been disabled. Thank you.
