### ISSUE TITLE
When VSCode crashes it should automatically restart

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#6818]
It seems this is a very frequent occurrence. It seems like this is a slow freeze crash, which means it happens when editor is left alone overnight.

I understand there is a bug to track but it seems related to the limitation of node giving only 1GB memory. Rather than showing the crash popup, how about just auto-restarting it to the state it was after 30 seconds?

**Comment by bpasero** [comment]
We talked about this and while it seems like a good solution for users, it hides the fact that we crash. I hope that with the tabs work we can improve this because closing an editor will cause memory to get freed.

**Comment by bpasero** [comment]
Closing, I find this not a good idea.
