### ISSUE TITLE
Keyboard Shortcut for Clear Console not working

### ISSUE THREAD

**Issue by calvn** [Microsoft/vscode#68181]
Issue Type: <b>Bug</b>

The keyboard shortcut (^L) to clear the debug console does not seem to work. Clearing the console can only be done by clicking on the the actual icon.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.23.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.8
Go|ms-|0.9.1
vscode-docker|Pet|0.5.2
vscode-icons|rob|8.1.0
vscode-table-formatter|shu|1.2.1
rewrap|stk|1.9.1
vscode-react-native|vsm|0.8.0
vscode-todo-highlight|way|1.0.4
HCL|who|0.0.5
vscode-proto3|zxh|0.2.2

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I can reproduce. Instead of clearing, I get presented a chord. Possibly we lost the `inDebugRepl` context @isidorn ?

**Comment by isidorn** [comment]
Decided to remove it due to https://github.com/Microsoft/vscode/issues/67695
@calvn you can add a custom keybinding and add any context you want
The inDebugRepl context is only true when you are actually in the debug input
