### ISSUE TITLE
macOS: Background Refresh Issues on Short Lines

### ISSUE THREAD

**Issue by the-real-tokai** [microsoft/vscode#68189]
- VSCode Version: 1.31.0/ 1.32.0-insider
- OS Version: Mac OS X 10.10.5 (14F2511)

Steps to Reproduce:

1. Launch the app and load a(ny) file with short lines
2. Navigate through the text

The background color in areas behind shorter lines flashes in a different color. A block of around 14 lines around the currently active line seems to work/look okay, but everything else on the screen suffers from the problem. In some cases (e.g. settings) the problem goes all over the place. I encounter the issue mostly with the dark color schemes; the default bright schemes seem to be unaffected by the issue. Obviously it is somewhat irritating. The previous version of vscode didn't have the issue.

Does this issue occur when all extensions are disabled?: Yes

![screenshot](https://user-images.githubusercontent.com/8261828/52455684-998cd600-2b51-11e9-8847-12f0cc10c85b.png)

**Comment by kieferrm** [comment]
@the-real-tokai does the issue go away of you run with `code --disable-gpu` or `code-insiders --disable-gpu` ?

**Comment by the-real-tokai** [comment]
@kieferrm:

Yes, the issues goes away, if launched with the `--disable-gpu` parameter.

Hardware is a Mac mini (late 2014 model) with an Intel Iris GPU (Vendor: Intel (0x8086)/ Dev.ID: 0x0a2e/ Rev.ID: 0x0009).

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by the-real-tokai** [comment]
@bpasero:

This exploration build seems to work all right (only tested it for 5 minutes though). It doesn't seem to trigger any kind of background refresh issues at least.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by the-real-tokai** [comment]
I confirm that the issue is fixed in the current version.
