### ISSUE TITLE
'Organize Imports' runs after code formatters and after file was saved

### ISSUE THREAD

**Issue by paustint** [Microsoft/vscode#68193]
- VSCode Version: 1.31.0
- OS Version: OSX 10.14.2

Steps to Reproduce:

1. Install prettier extension
1. Enable format on save
1. Enable organize imports on save
1. Create typescript file with lots of imports, causing prettier (or any other code formatter) to move imports onto individual lines
1. Save file (ensure that code formatter runs on save)
    - prettier formats code
    - Organize imports are performed after code is formatted ;(
    - File is saved to disk
    - THEN imports are organized again
        - The file remains dirty (white circle showing file was modified since last save)
        - The imports modified by the code formatter were completely ignored

This started happening immediately after updating to 1.31.0 and worked fine before that, and I have not made any setting changes or added/removed any extensions since the update.

Does this issue occur when all extensions are disabled?: ~~Yes/No~~ Probably not, since the native code on 1.31.0 conflicts with extensions, but it is core VSCode that changed

![vscode-auto-import-after-save](https://user-images.githubusercontent.com/5461649/52458735-6bda6980-2b1e-11e9-9a2b-9a3166a1a935.gif)

**Comment by mjbvz** [comment]
Please start by filing an issue with the Prettier extension
