### ISSUE TITLE
Duplicate lines displayed in editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6819]
No solid repro for this unfortunately. What I recall doing (Ubuntu 16.04):

1. Copying:

  ```
  a {
    background-color: var(--css-var);
  }
  ```
2. <kbd>ctrl</kbd>+<kbd>n</kbd>
3. Save as "b.scss"
4. Paste

![image](https://cloud.githubusercontent.com/assets/2193314/15514479/0e72bda6-219e-11e6-9c4d-9cecbfb524c8.png)

**Comment by alexandrudima** [comment]
Any repro steps would be welcome, I am very interested in tracking this down. You can also open Developer tools to see if there's any exception in there...

**Comment by Tyriar** [comment]
I could not reproduce it a second time :(

**Comment by Tyriar** [comment]
I reproduced again randomly, I created a `.editorconfig` file in root and copy and pasted (from github.com) one of my `.editorconfig` files from another repo.

![image](https://cloud.githubusercontent.com/assets/2193314/15648425/6c5f6b14-261f-11e6-844f-1f19c129a713.png)

It gets weirder, <kbd>ctrl</kbd>+<kbd>z</kbd> (undo) did this:

![image](https://cloud.githubusercontent.com/assets/2193314/15648445/90917c5c-261f-11e6-9f28-6c8d09d40886.png)

One more undo:

![image](https://cloud.githubusercontent.com/assets/2193314/15648454/9c05b300-261f-11e6-9d84-f8ec4bf92569.png)

Using <kbd>ctrl</kbd>+<kbd>y</kbd> (redo) I could go back and forth between these invalid states. Clicking on the last line did not set the cursor anywhere.

<kbd>enter</kbd> a few times just moved the broken line down:

![image](https://cloud.githubusercontent.com/assets/2193314/15648487/e2c13788-261f-11e6-85d5-6ef4038fd545.png)

And here's the DOM:

![image](https://cloud.githubusercontent.com/assets/2193314/15648517/017e389c-2620-11e6-8c0f-b880e92daec8.png)

**Comment by Tyriar** [comment]
Console output:

![image](https://cloud.githubusercontent.com/assets/2193314/15648549/319fbc58-2620-11e6-9a7e-fc0d6e9ebb05.png)

**Comment by Tyriar** [comment]
The `Detect Indentation from Content` command put the editor back into a good state.

**Comment by Tyriar** [comment]
It's definitely to do with pasting multiple lines into the editor, which language seems irrelevant (repro'd in CSS and ini).

**Comment by alexandrudima** [comment]
I've rewritten the logic in the handling of model events by the ViewLayer and wrote as many tests as I can. Please try to reproduce again if you can, I could never reproduce

**Comment by weinand** [comment]
I could not reproduce this either.
