### ISSUE TITLE
How to enforce indenting of all child elements in Emmet?

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [Microsoft/vscode#68191]
I love emmet it makes my life easier. However, I would love to configure my Visual Studio Code to enforce an always indent policy on ALL childs when using Emmet.

Example:
`#remember.checkbox>label>input:checkbox{Remember me}`

When the above emmet expression is expanded it turns into this:

```html
<div id="remember" class="checkbox"><label for=""><input type="checkbox" name="" id="">Remember Me</label></div>
```

I don't want it in a single line, I want it indent it like this:

```html
<div id="remember" class="checkbox">
    <label for="">
        <input type="checkbox" name="" id="">Remember Me
    </label>
</div>
```

It does it correctly for certain child elements, like ul>li or div>div , but not for others like a label tag. 

Also, one more question how come the `input` tag when expanded doesn't include a closing tag like this `<input type="checkbox" name="" id"">Remember Me</input>`

**Comment by ramya-rao-a** [comment]
> It does it correctly for certain child elements, like ul>li or div>div , but not for others like a label tag.

Yes, this depends on whether the child element is a block or inline element. If you want the same behavior for inline elements as well, then add the below to your settings:

```
"emmet.syntaxProfiles": {
		"html": {
			"inline_break": 1
		}
	}
```

For more on syntax profiles, see https://docs.emmet.io/customization/syntax-profiles/

> Also, one more question how come the `input` tag when expanded doesn't include a closing tag

Please look up "self closing tags". `input` and `img` tags are such tags.

**Comment by octref** [comment]
@ramya-rao-a Thanks for answering the question!

@IAlwaysBeCoding With the `inline_break` setting this works as you expected:

![image](https://user-images.githubusercontent.com/4033249/52665852-810a1c00-2ec1-11e9-8fef-346f2268f969.png)
