### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by Moemay** [microsoft/vscode#68192]
I am trying to install extension on market place , i can search the extension but the image of the extension is not showing and after i clicked the install button its failing to install, i even try downloading the extesion manually and installing an error show with the message "The install of 'NameOfProduct' was not successful for all the selected products.  For more information, click on the install log link at the buttom of the dialog. And the content of the log has an error of 

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Please see the issue.
Thank you

**Comment by kieferrm** [comment]
@Moemay can you add screenshots or a screen recording? I wonder if you try to install the wrong kind of extension or whether you talk about a different product. Thanks!
