### ISSUE TITLE
Cmd+F Not searching in selection broken

### ISSUE THREAD

**Issue by setek** [Microsoft/vscode#68190]
Issue Type: <b>Bug</b>

Cmd + F (Find) has gotten worse. Deselecting “search in selection” still only searches in selection, have to select entire document and select “search in selection” to get it to work. Since last update.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_1323331|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
alignment|ann|0.3.0
snapshot-tools|asv|0.2.2
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
vsc-material-theme|Equ|2.6.3
sass-lint|gle|1.0.4
vscode-styled-components|jpo|0.0.25
sort-selection-concentrically|min|1.0.0
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
sublime-keybindings|ms-|4.0.0
vetur|oct|0.14.5
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.4
stylelint|shi|0.48.0
vscode-fileutils|sle|2.13.5
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.8.0
twig|wha|1.0.2
vscode-import-cost|wix|2.12.0
ReactSnippets|xab|2.3.0

</details>

**Comment by mysticatea** [comment]
I have encountered this bug, too. I'm on Windows 7 pro.

"Find in selection" button is broken.

![vscode-find-in-selection](https://user-images.githubusercontent.com/1937871/52463903-181e5d80-2bbc-11e9-95e0-d2d56a51a2ea.gif)

**Comment by mysticatea** [comment]
This is still problem in vscode 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60).

I'm worried if this regression bug that was introduced since 1.31.0 has been overlooked because [January 2019 Recovery](https://github.com/Microsoft/vscode/milestone/87) doesn't include this issue.

**Comment by rebornix** [comment]
The regression was introduced in https://github.com/Microsoft/vscode/commit/f9775c5fe8ae78ec791d13a71e581850e60ab0d5.
