### ISSUE TITLE
After download files from server, display empty files

### ISSUE THREAD

**Issue by MSDevelops** [Microsoft/vscode#68194]
I have this issue for 20h, my vscode worked perfect but when i restart my PC and open Vscode, all files all empty but on my server same files are not empty ( have lines of code )... I was reinstaled vscode several time, reinstal windows 10 pro twice, but i have same issue. I don't know what to do, to remove this problem and start to code again in this software. Is anyone have this issue?

**Comment by kieferrm** [comment]
@MSDevelops are your files on a server or on your local machine? If they are a server how do you connect to the server?
