### ISSUE TITLE
Node Debug extension is shown twice

### ISSUE THREAD

**Issue by levani** [Microsoft/vscode#68202]
- VSCode Version: 1.31.0
- OS Version: WIndows 10 (Same on macOS)

Steps to Reproduce:

1. Install Node Debug extension and go to the Extensions panel.

![screenshot_4](https://user-images.githubusercontent.com/184472/52462732-be06a380-2b8d-11e9-9ed9-7cd2d140880b.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by timhibberd** [comment]
I am experiencing this issue as well.

**Comment by sandy081** [comment]
@levani How did you install Node Debug extension?

**Comment by levani** [comment]
@sandy081 
Not quite sure to be honest. It's been there for a long time and when I try to delete it I'm getting the following error:

<img width="476" alt="screen shot 2019-02-12 at 11 21 10 pm" src="https://user-images.githubusercontent.com/184472/52662203-269ea900-2f1d-11e9-9a31-cfa28355b8fb.png">

React Native Tools is an extension from marketplace: https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native

**Comment by sandy081** [comment]
I think you are having the same issue as this https://github.com/Microsoft/vscode/issues/66774

**Comment by timhibberd** [comment]
@sandy081 please reopen this issue. It is not a clear duplicate. #66774 clearly shows two unique instances... Node Debug and Node Debug Legacy which is as per design since one builds on the other. My issue and the issue of @levani is that we have two instances of Node Debug...no Node Debug Legacy is sight. Additionally, it can't be uninstalled.

**Comment by sandy081** [comment]
@timhibberd Root cause of this issue is same as others which is that getting this extension installed again.  

You cannot uninstall it because it is a built in extension. Only way to remove it is to open your extensions folder and delete the folder which is mentioned in the other issue.

**Comment by timhibberd** [comment]
Cheers @sandy081 but why are there two instances with the exact same name vs. Node Debug and Node Debug Legacy?

**Comment by sandy081** [comment]
I would ask @weinand to answer this.

**Comment by weinand** [comment]
The node debug extension are built into VS Code. There is no need to install them manually (and there should be no way to actually install them manually). 

What you are seeing looks like a bug to me: somehow you've managed to install node-debug but there is already the built-in version. As a result of this you are seeing two.

**Comment by timhibberd** [comment]
@weinand - you can see from the following screenshot that there is an uninstall option.

![image](https://user-images.githubusercontent.com/18463324/52706727-316b4380-2fda-11e9-8533-7144e64cb901.png)

**Comment by sandy081** [comment]
This is because you got this extension installed some how from market place - which is tracked in other issue.

**Comment by timhibberd** [comment]
ahhh...sorry to have been slow to the party. Thanks for clarifying @sandy081 much appreciated :-)
