### ISSUE TITLE
Emoji "disappeared" after 1.31.0 update

### ISSUE THREAD

**Issue by bimbo1989** [microsoft/vscode#68207]
Some of the emojis no longer "work" and they appear as empty squares instead.
I'm 100% sure they were showing correctly in the previous versions.

- VSCode Version: 1.31.0
- OS Version: Windows 10 Professional (latest version)

Steps to Reproduce:

1. Paste the swan emoji 🦢 in the editor

Does this issue occur when all extensions are disabled?: Yes/No
Yes

---

## 🦢🦢🦢 workaround 🦢🦢🦢
Define your font family e.g. `"editor.fontFamily": "Consolas, Segoe UI Emoji"`

---

**Comment by bpasero** [comment]
@bimbo1989 exact steps what you are doing please

**Comment by bimbo1989** [comment]
You just need to open any file in VSCode and paste the swan emoji (  🦢 ), that is the one no longer working for me.
You will see that, insted of the swan, an empty square will appear.

**Comment by bpasero** [comment]
Works fine on macOS at least.

**Comment by bimbo1989** [comment]
Maybe it's Windows related?
I'm using Windows 10. Not a strictly OS  problem though, the emoji is working fine in any other program. Just VSCode seems to suffer this issue. No extensions enabled.

**Comment by bpasero** [comment]
@bimbo1989 I do not even see that emoji appearing on my Windows in IE nor Chrome, so I think this is rather a Windows issue.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/52466583-15534680-2b83-11e9-832b-391d59d983a5.png)

**Comment by bimbo1989** [comment]
@bpasero that's weird: I see the emoji correctly in Chrome, Firefox, even in Microsoft Word 🤔

**Comment by frobinsonj** [comment]
![ezgif-1-1e5c6152cc7a](https://user-images.githubusercontent.com/16726902/52467599-fc946200-2b7d-11e9-88f8-e16aef606b9e.gif)

On Windows 10 Professional also. Opened the emoji menu using `Win + Period`.

**Comment by bimbo1989** [comment]
@frobinsonj exactly that 😁

**Comment by usernamehw** [comment]
Possible workaround https://github.com/Microsoft/vscode/issues/32840#issuecomment-345923580

**Comment by bimbo1989** [comment]
@usernamehw it kind of works! Only in the editor though (it doesn't work for example in extensions where it used to work before), but still better than nothing!

**Comment by usernamehw** [comment]
@bimbo1989, didn't notice that. Using custom CSS to fallback to emoji where I can (since some emoji didn't work even before this update 🖥 for instance):
```css
.monaco-shell.windows, .monaco-shell.windows .monaco-menu-container .monaco-menu {
    font-family: Segoe WPC,Segoe UI,sans-serif, Segoe UI Emoji;
}
```
![screenshot 52](https://user-images.githubusercontent.com/9638156/52477561-5cf1c680-2bb3-11e9-8a12-b3262f66e064.png)

**Comment by bimbo1989** [comment]
@usernamehw seems nice! Where do I need to put that css? Do I need to create a theme?

**Comment by usernamehw** [comment]
Nah, it's an extension (not recommended by vscode team because it modifies the source) [Custom CSS](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css).

**Comment by bpasero** [comment]
I suspect this is https://github.com/electron/electron/issues/16530

**Comment by alexandrudima** [comment]
A workaround for the editor is to use `"editor.fontFamily": "Consolas, Segoe UI Emoji"`. I have updated the issue description to capture this workaround.

**Comment by burkeholland** [comment]
Confirmed this is happening on Mac as well.

![2019-02-21_10-11-50](https://user-images.githubusercontent.com/686963/53183664-586cdb00-35c1-11e9-9b68-a69ace472f8a.gif)

**Comment by harrygr** [comment]
Can confirm this is also an issue for me on Mac.

VSCode version: 1.33.0
Font Family: IBM Plex Mono

![ezgif-5-a8c7942f5319](https://user-images.githubusercontent.com/5128200/55799363-16441e00-5ac9-11e9-8fee-bf97d2e5b1aa.gif)

**Comment by mdschweda** [comment]
Setting the editor font is one thing. I like to use emojis to keep track of long task lists or launch configurations. Couldn't you just extend the UI `font-family` list to fix the UI - outside the editor - like so:

```diff
.windows {
- font-family: Segoe WPC, Segoe UI, sans-serif;
+ font-family: Segoe WPC, Segoe UI Emoji, Segoe UI, sans-serif;
}
```

Meanwhile, here is a posh script:

```powershell
$path = Join-Path (Split-Path (Get-Command "code").Source) "..\resources\app\out\vs\workbench" -Resolve
$stylesheet = Join-Path $path "workbench.main.css"
Copy-Item $stylesheet "$stylesheet.bak"
((Get-Content $stylesheet -Raw) -replace ".windows{font-family:Segoe WPC,Segoe UI,sans-serif}", ".windows{font-family:Segoe WPC,Segoe UI Emoji,Segoe UI,sans-serif}") | Set-Content $stylesheet
```

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by bimbo1989** [comment]
Hi @bpasero , the emoji now seems to work, to be fair also on the "regular" release
