### ISSUE TITLE
venv drops from integrated terminal on window reload.

### ISSUE THREAD

**Issue by jaxxor44** [Microsoft/vscode#68203]
- VSCode Version: 1.31.0 (user setup)
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.open a work space with a defined venv. Integrated terminal displays traditional venv pretext, and tests as if its working inside the correct venv.
2. ctrl+shift+p and restart the window.
3. restarted window uses correct interpreter (venv selected) and debug does as well, terminal drops the venv.

Does this issue occur when all extensions are disabled?: Yes

I realize this may be more of a nuance than anything, but I figured id bring it up.

**Comment by Tyriar** [comment]
venv support is handled by the python extension.
