### ISSUE TITLE
Ignores "Search in Folder" within specific extensions 

### ISSUE THREAD

**Issue by Mestika** [Microsoft/vscode#68205]
- VSCode Version: `1.31.0`
- OS Version: `MacOS 10.14.2`

Steps to Reproduce:
The issue seem to begin yesterday (7th of February 2019) after VS Code had upgraded itself to `1.31.0`.

_EDIT_  
The issue **only** seem to be when searching a child-folder.  
If searching from the root of the project (`./`) it works fine but going into a subfolder it strips of the extension filter.  
[I've made a screencast of it for better explanation	](https://www.dropbox.com/s/jynuimvf0b4ls9g/Screen%20Recording%202019-02-08%20at%2008.35.46.mov?dl=0)

1. Open project
2. Right-click folder and choose "Find in Folder"
3. Enter search criteria
4. In field "files to include" append to folder-path `,*.extension` (where extension be the extension of the files you only want to search in)
5. Search
6. It performance the search but searches in all files, ignoring the specific extension set.

Does this issue occur when all extensions are disabled?: Yes/No
**YES**

**Comment by kompot** [comment]
Seems like a related issue — patterns in `.gitignore` files are ignored when searching within a subfolder.

When searching from root everything works fine and `.gitignore` entries are correctly excluded from search results.

**Comment by roblourens** [comment]
@Mestika this is actually the expected behavior, although it might have changed with 1.31. You are saying "search inside this folder and also search `*.extension`". You can combine them like `./folder/**/*.extension` to only get files of that extension in that folder.

@kompot I have https://github.com/Microsoft/vscode/issues/26574 to track that issue

**Comment by Mestika** [comment]
@roblourens Since I started using VS Code which was about 8 month ago, I've been using the search pattern I described (`./folder,*.extension`) which has worked perfectly up until the update.

I'll try out your recommendation for the new search pattern and see how that goes.
