### ISSUE TITLE
VS Code all grey with HDR screen

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#68200]
- VSCode Version: 1.31.0
- OS Version: Windows 10 Pro 1809

Steps to Reproduce:

1. Install latest version of VS Code
2. Turn on HDR Settings (right click on desktop -> Display Settings ->Windows HD color settings. Select HDR capable screen where VS Code is currently. Switch the "Play HDR games and apps" 
3. VS code window will turn all dark grey. Can't find a way to fix that without turning HDR off

Does this issue occur when all extensions are disabled?: Yes

Attach is a photo of the screen with HDR on and off. Note on how grey the VSCode window is.
Note that on both picture, the window on the left looks exactly the same with HDR on or off, it just looks a tad darker when next to the grey VS Code due to bad autowhite balancing on the phone I used to take the photo.

![20190208_171009 2](https://user-images.githubusercontent.com/505748/52461906-23c25200-2bc5-11e9-9e2c-c3534cda1bf8.jpg)
![20190208_171031 2](https://user-images.githubusercontent.com/505748/52461913-291f9c80-2bc5-11e9-82f3-76912a3fa5fa.jpg)

**Comment by jyavenard** [comment]
BTW, this is a regression of VSCode 1.31.0, the previous version didn't have this problem

**Comment by dbaeumer** [comment]
Dups #68069
