### ISSUE TITLE
Webview lost some css variables

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#68211]
Issue Type: <b>Bug</b>

In the latest insiders, it looks like some base css variables are missing (`--color`, `--font-size`, etc)

/cc @mjbvz 

VS Code version: Code - Insiders 1.32.0-insider (1c50a87561055485d93a3961160902308497f1e3, 2019-02-08T06:16:17.233Z)
OS version: Windows_NT x64 10.0.18329

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (20.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
This was an intentional break early in this iteration. Please switch over to using the `--vscode-*` prefixed variables instead as they are part of the official API: https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content.

Example variables: `--vscode-editor-font-family` and `--vscode-editor-font-size`

**Comment by eamodio** [comment]
@mjbvz is there any place extension devs can find out about intentional breaks right when they happen? I spent a lot of time figuring out the problem, fixing it, writing up a bug report, etc. Also now until we get a new release out, CodeStream is basically completely busted and GitLens' settings and welcome ui are useless as well.

I have no issue with breaks, it would just be nice to get a heads up somewhere -- and ideally even before it lands -- even if its a short window.

**Comment by mjbvz** [comment]
Sorry but these old css variables were never official api; they were more of an implementation detail. We do document changes to our real apis and generally provide at least one release to alert extension authors if we are intentionally breaking them

**Comment by ppezaris** [comment]
That's a pretty unsatisfying answer, FWIW. "Intentional break" was your phrase, not Eric's.
