### ISSUE TITLE
New explorer: disallow dropping of root file onto empty space in multi root workspace?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#68210]
Follow up from https://github.com/Microsoft/vscode/issues/68095

With my change you can now:
* enter multi root with multiple folders
* drag a root file of one folder onto empty space of explorer
* drop it

I think we should probably not allow that and I verified this used to be like that before but now changed due to my recovery fix in https://github.com/Microsoft/vscode/issues/68095

**Comment by isidorn** [comment]
I think we should allow. This would put the root at the end.
However when I now drop it to the empty space the order is not changed, it is a no-op. Assigning to february to investigate

**Comment by bpasero** [comment]
@isidorn isn't that weird though? I drag a file from the first root folder all the way down to empty space (which is highlighted) and it ends up at the root of the last folder?

**Comment by isidorn** [comment]
Aaaa I thought it only happens for the dragged roots, not for files. Yeah that is weird. Will fix that.

**Comment by isidorn** [comment]
I can not repro. Please let me know what you are doing differently
Only when dropping roots do I get drop feedback and something actually happens

![cannotrepro](https://user-images.githubusercontent.com/1926584/53088110-1ed89900-3509-11e9-84b9-c79091383132.gif)

**Comment by bpasero** [comment]
@isidorn it should not be possible to drag a FILE of one folder onto the empty space below the last root folder in a multi root workspace:

![grid-tw](https://user-images.githubusercontent.com/900690/53089910-28183480-350e-11e9-948b-4ba5229f9a0b.gif)

**Comment by bpasero** [comment]
@isidorn I also see lots of issues trying to reorder root folders with drag, can you check?

**Comment by bpasero** [comment]
![grid-tw](https://user-images.githubusercontent.com/900690/53090021-6f9ec080-350e-11e9-9e2c-e55b670d42e9.gif)

**Comment by isidorn** [comment]
@bpasero reordering issues I see and I can fix them. The original issue I do not see

**Comment by bpasero** [comment]
@isidorn yeah now I also cannot reproduce those anymore
