### ISSUE TITLE
Autoupdates are ON, but new update only allows me to download it as .zip.

### ISSUE THREAD

**Issue by zed-b** [Microsoft/vscode#68212]
I can't update VSCode, even though it's set to auto. It gives me a .zip file to download, and no instructions what to do with it. Next time I open vscode, it agains tells me there is this update and whether to download now ...

- VSCode Version: 1.29.1
- OS Version: Windows 7

![vscodeproblem](https://user-images.githubusercontent.com/44090070/52467993-f8714000-2b8f-11e9-870c-43ef00d99027.png)

**Comment by kieferrm** [comment]
You seem to run a version of VS Code that you installed as a `zip` (for example a portable setup). In this case we don't automatically update the installation. We inform you that there is a new version available. However, you still need to install it manually.

**Comment by zed-b** [comment]
No, I didn't install it as a zip, and it used to update itself previously.
