### ISSUE TITLE
Developer Tools contains Google Chrome icons and info

### ISSUE THREAD

**Issue by CSharperMantle** [Microsoft/vscode#68213]
### Maybe this can't be called a 'bug'. It's just an interesting fact.
Issue Type: <b>Bug</b>

1. Open _Developer Tools_ of VS Code
2. Click _Customize and control DevTools_ icon (3 dots in vertical way)
3. Point the nouse to _More tools_, and then click _What's new_.
4. You can see the words 'Highlights from the Chrome 66 update' and a hyperlink to a video player on the window popped up

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (11.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.5.0
php-intellisense|fel|2.3.10
beautify|Hoo|1.4.8
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.4
vscode-icons|rob|8.1.0

(1 theme extensions excluded)

</details>

**Comment by cfanoulis** [comment]
Possible cause could be the fact that electron users Chromium under the hood
