### ISSUE TITLE
Open new files overwrite old file tab

### ISSUE THREAD

**Issue by sarath196** [Microsoft/vscode#68223]
Issue Type: <b>Bug</b>

I'm trying to open new HTML files or python files, it open on old file tab (overwrite old tab), so I lose my old open tab files.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|5.89GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.3.0
django-snippets|bib|1.1.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-sshfs|Kel|1.12.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
vscode-yaml|red|0.2.1
vscode-djaneiro|the|1.4.2

</details>

**Comment by gjsjohnmurray** [comment]
See accepted answer to https://stackoverflow.com/questions/43705543/how-to-open-file-in-new-tab-in-visual-studio-code/43707807 for an explanation of Preview Mode, which is what you are seeing.

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
