### ISSUE TITLE
Search shows results from deleted files

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#68221]
- VSCode Version: Insider 1.31.1 b313db6c58f8c02181a33cd3b5b4b17c64a5b85d
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. press cmd+shift+f
2. type something and validate search

Does this issue occur when all extensions are disabled?: Yes

Search results contains results from files that have been deleted from the disk.

I tried to disable `Include History` option but it still shows results from deleted files.

![image](https://user-images.githubusercontent.com/199648/52471924-5ef75d80-2b92-11e9-82f5-f2a11472c07d.png)

**Comment by roblourens** [comment]
Did you have that deleted file tab open already? If not you may have an extension which is keeping the model open.
