### ISSUE TITLE
Explorer will not open anymore using shortcut if release notes is already shown

### ISSUE THREAD

**Issue by joseluisq** [microsoft/vscode#68225]
Issue Type: <b>Bug</b>

1. Open some project
2. Show release notes, typing: `cmd+p` > Show release notes
3. Toggle explorer pressing once, typing: `cmd+b`
4. Now, try to toggle the explorer more times and you will see (after the third pressing) that the explorer will not open anymore.

__VS Code version:__ Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
__OS version:__ Darwin x64 18.2.0

**Comment by Nabav** [comment]
I use the VSCode for Latex with the help of the extension Latex Workshop. Editing is in tabs in group 1 and PDF preview tab is in group 2.
As soon as the focus is on the PDF preview tab, the normal key bindings are deactivated. For example, I switch from editor group 1 to 2 with Ctrl+2 and navigate through the PDF document. However, I cannot return to editor group 1 by Ctrl+1. I think this happened with the latest Visual Studio Code update to version 1.31.1.

**Comment by mjbvz** [comment]
Can you please test this again the [latest VS Code insiders build](https://code.visualstudio.com/insiders/). I can't repo it anymore

**Comment by lamBOOO** [comment]
I can confirm the behavior of @Nabav using the latest CS Code insiders build (`2e4d4a6bb16a65303b460795fa4ac734f9aea43e` `2019-02-21T06:07:20.691Z`). VSCode's global keystrokes are deactivated when focussing the PDF tab. I downgraded to 1.30.2 to overcome this issue.
![feb-22-2019 10-16-21](https://user-images.githubusercontent.com/19747233/53232237-f5477b00-368a-11e9-8857-acb93dc62479.gif)

**Comment by Zayin** [comment]
Same issue as @Nabav on Windows 10, vscode 1.33.1 . Fedora 30 running vscode 1.33.1 does not have this issue.

**Comment by mjbvz** [comment]
Tested on MacOs and linux (using VS Code insiders, 1.45) but the keyboard shortcuts always work for me now. If you still see this, please share which OS you are on and how to reproduce the issue

**Comment by dbaeumer** [comment]
Verified under Windows.
