### ISSUE TITLE
Issue with SFTP connections after Update

### ISSUE THREAD

**Issue by baloeng** [Microsoft/vscode#68228]
I'm having issues opening files on my remote server. The SFTP connects fine as I can see and open the folders, sub-folders and files on my sidebar. But, the files (php, js, xml etc.) fail to open and just keeps loading on the workspace.
This issue started after the recent update.
I have restarted the VScode application several times, all to no avail.

**Comment by ACheshirov** [comment]
+1
FTP extensions have some problems with the new update.
FTP-Simple doesn't work for example.

**Comment by kieferrm** [comment]
Please file the issue against your FTP extension(s). Thanks!
