### ISSUE TITLE
The "Changes" pane inside the main Git pane is not auto resizing correctly

### ISSUE THREAD

**Issue by madprops** [Microsoft/vscode#68229]
- VSCode Version: Tried in stable 1.31.0 and in todays' 1.32.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. In my case I added 6 projects to the workspace, each being git controlled.
2. All 6 projects are correctly tracked by the git plugin
3. It starts looking like this https://i.imgur.com/BO7yD31.jpg (The changes bottom pane is nicely place).
4. Hide the git plugin.
5. Show the git plugin again
6. Now it looks like this https://i.imgur.com/VoZNztJ.jpg
7. Picking different git projects on the top makes it go a little above https://i.imgur.com/12e64Ak.jpg
8. Try to set position manually.
9. Hide/show git plugin. Doesn't remember position. Again at an awkward bottom position.

Does this issue occur when all extensions are disabled?:  I couldn't check because adding a directory to the workspace to check opens a new normal window.

**Comment by joaomoreno** [comment]
It auto resizes until it hits 5. From then on, it lets the user resize it.

**Comment by madprops** [comment]
Right, the thing is, the specified resize position set by dragging is not remembered after going back to the Git pane.

**Comment by joaomoreno** [comment]
That shall be fixed with https://github.com/Microsoft/vscode/issues/49054
