### ISSUE TITLE
Explorer opens all projects when searching

### ISSUE THREAD

**Issue by mebibou** [Microsoft/vscode#68227]
- VSCode Version: 1.31.0
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Close all the top-level projects in the explorer
2. Do a global search Cmd + Shift + F
3. Go back to the Explorer
=> every project is now open, so need to close the ones I didn't want open before

This did not happen before today (the last version)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lzambarda** [comment]
This also happens whenever switching from Explorer to Debug and back.

**Comment by isidorn** [comment]
I can not reproduce this.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes can you please share a gif/video showing this behavior

**Comment by mebibou** [comment]
This does not happen anymore with version `1.31.1`, so I guess it was patched up. Thanks
