### ISSUE TITLE
[bug] VSCode update 1.31.0  breaks pymakr addin 

### ISSUE THREAD

**Issue by Josverl** [Microsoft/vscode#68230]
Issue Type: <b>Bug</b>

Start : working environment with pymakr
>  VSCode updates to 1.31.0 

After update pymakr addin does not work anymore 
any attempt to use results in an error such as: 
`command 'pymakr.listCommands' not found`

Tried : 
- re-installation of add-in does not resolve the issue 

Cross reference : https://github.com/pycom/pymakr-vsc/issues/28 

Extension version: 1.0.5
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
@bpasero very likely causes by the Electron update. Also you can't do anything I assign to you then we at least have one person knowing about them.

**Comment by Josverl** [comment]
I already filed the issue with pycom as well so that they can look into this. 
i have been working with some of their devs so im happy to help  where relevant.

**Comment by curtis-hendrix** [comment]
Workaround:
1. Uninstall Visual Studio Code
2. Delete the `Code` folder from `%appdata%`.
3. Delete the `.vscode` folder from `%userprofile%`
4. Download Visual Studio Code version 1.30 from here: https://code.visualstudio.com/updates/v1_30
5. Install Visual Studio Code
6. Install the Pymakr Plugin.
