### ISSUE TITLE
Installing a vsix through CLI does not update the extension

### ISSUE THREAD

**Issue by randrade23** [Microsoft/vscode#68234]
- VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
- OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Install an extension
2. Produce a vsix of the same extension with a higher version code
3. Install the vsix through CLI: code --install-extension extension.vsix
4. The extension does not update in opened VSCode instances, requiring a restart or a window reload

Does this issue occur when all extensions are disabled?: Yes

The latest VSCode update implements installation of extensions without requiring a restart or reload, be it from the Marketplace or through a local file. However, if we try to update an existing extension through a local vsix file and the command line (as described above), the extension is not updated immediately in currently opened VSCode instances, requiring a restart or reload.

**Comment by sandy081** [comment]
@randrade23 Reload is required if an extension that is running is updated.
