### ISSUE TITLE
Bad button layout in Keybindings JSON editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#68231]
1. Open Keyboards Shortcuts (JSON)

![image](https://user-images.githubusercontent.com/22350/52474768-b1884800-2b99-11e9-8c2a-ab98576b5a73.png)

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode/commit/92eedf890c66994783e785b00321189d70e55228
