### ISSUE TITLE
Multi-line messages in the problems panel can't always be collapsed

### ISSUE THREAD

**Issue by dan1994** [Microsoft/vscode#68235]
- VSCode Version: 1.31.0
- OS Version: Windows_NT x64 10.0.17134

The issue:
When collapsing specific messages, they don't collapse, but instead expands/collapses another message. When I've seen it, the affected message was always 2 messages before the one I was trying to collapse.

![vscode_collapse_bug](https://user-images.githubusercontent.com/6225230/52475360-f3b68700-2ba3-11e9-8881-796c459e81f2.gif)

Steps to Reproduce:
1. Get to a state where you have multiple messages in the problems panel
2. Start collapsing one by one

Does this issue occur when all extensions are disabled?: 
Without extensions, my build won't run so It's hard to check...

Specifically, I'm building using the latex workshop extension

**Comment by sandy081** [comment]
@dan1994 I cannot reproduce it, can you please provide steps to repro? May be an sample extension code would be helpful.
