### ISSUE TITLE
after update of visual studio code ,no buid on save,no go to defination,every things is messed up

### ISSUE THREAD

**Issue by manipise** [Microsoft/vscode#68232]
Issue Type: <b>Bug</b>

Updated vscode to version 1.30.2
after thati am not able to peek defination ,auto indendation is not working,
build on save is not happening.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 3.10.0-862.9.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (2 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|5.67GB (1.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by manipise** [comment]
Error: Error: spawn EACCES
after reinstalling go extension

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by manipise** [comment]
can you please suggest how to install it in centos

**Comment by manipise** [comment]
when tried to install manually 
```
Installing 1 tool at /root/bin
  gocode

Installing github.com/mdempsky/gocode FAILED

1 tools failed to install.

gocode:
Error: spawn /bin/go EACCES
```

**Comment by bpasero** [comment]
Sorry I am confused by your response. I believe you are using the Go extension and they do not work properly for Go files?

**Comment by manipise** [comment]
yup

**Comment by manipise** [comment]
things were fine before installing updates,after vscode update i am facing these issues
