### ISSUE TITLE
List/tree: Support setting to set keyboard navigation to toggle model

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#68233]
Similar to `listAutomaticKeyboardNavigation` contextkey, but as a setting.

**Comment by evenfrost** [comment]
Another reason it would be great to have such option is that [Vim navigation](https://github.com/VSCodeVim/Vim/issues/3466) is currently broken with this feature.

**Comment by joaomoreno** [comment]
VIM navigation is independent of this. It works on startup, but stops working as you switch viewlets around. More info on https://github.com/VSCodeVim/Vim/issues/3466#issuecomment-465481730. Fixed by https://github.com/Microsoft/vscode/commit/5e54b2574b0703aa9437363294f8fd2db63f3e10.

**Comment by joaomoreno** [comment]
Verification:

1. Set setting `workbench.list.automaticKeyboardNavigation` to `false`
2. Verify that filtering in the tree no longer works until you
3. Create a keybinding for the `list.toggleKeyboardNavigation` command and
4. Press that keybinding

Once you press it, there's no UI feedback, but you can start typing to highlight/filter a tree. Once you <kbd>Escape</kbd> or clear the highlight/filter, you have to use the keybinding once more to highlight/filter once more.

**Comment by controversial** [comment]
When will this feature land?
