### ISSUE TITLE
Task in terminal outputs gibberish after prolonged usage.

### ISSUE THREAD

**Issue by JAciv** [Microsoft/vscode#68236]
- VSCode Version: 1.31.0
- OS Version: Windows 7 

Steps to Reproduce:

1. Have a build task with tsc: watch.
2. Build.
3. Normal use for some time (maybe hours).
3. Gibberish shows in the integrated terminal.

Does this issue occur when all extensions are disabled?: Yes

Note about the gibberish, it seems that links to files are still active (and show on mouse hover). 
I will try and take a screenshot next time it happens.

**Comment by alexr00** [comment]
@Tyriar, do winpty issues exist on Windows 7?

**Comment by alexr00** [comment]
@JAciv can you give an example of the gibberish and what the gibberish should look like? I use tsc watch all the time and I've never seen this.

**Comment by JAciv** [comment]
@alexr00 Since posting the issue I've had a hard time reproducing it (figures), since I wanted to provide a screenshot.
It seems that it had something to do with low working memory situations.

**Comment by alexr00** [comment]
@JAciv thanks for the update. I'm going to close the issue, but if you do see it again please create another issue!

**Comment by Tyriar** [comment]
> do winpty issues exist on Windows 7?

@alexr00 winpty issues exist Windows 7-10, this is likely in the class of issues we're not going to action as conpty should fix it.
