### ISSUE TITLE
open workspace btn in code pane

### ISSUE THREAD

**Issue by Dovernh** [Microsoft/vscode#68239]
Issue Type: <b>Bug</b>

update to latest vc and an Open Workspace btn shows in the coding pane. The btn does nothing when clicked

VS Code version: Code - Insiders 1.32.0-insider (1c50a87561055485d93a3961160902308497f1e3, 2019-02-08T06:16:17.233Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v3 @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (5.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.22.3
flutter|Dar|2.22.3
gitlens|eam|9.5.0
tslint|eg2|1.0.42
vsliveshare|ms-|0.3.1151
team|ms-|1.144.1
material-icon-theme|PKi|3.6.2
csharp2ts|raf|0.0.22

</details>

**Comment by alefragnani** [comment]
Duplicate of #68216
