### ISSUE TITLE
PWD in terminal window is chopping off when changing vscode display position to different resolution (multi monitor scenario)

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6824]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps:
1. Make sure you are working with multiple monitor.
2. Launch VSCode and update setting in settings.json to powershell terminal.
3. Launch terminal window and change VSCODe position to other monitor (From 1280x1024 to 1280x800) and make it full size.

Actual: Once user drag and drop vscode to other monitor then path for the present working directory is not displaying full path.
![image](https://cloud.githubusercontent.com/assets/17735796/15514744/6ef727f6-219f-11e6-8184-c26484b67012.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/17735796/15514789/a6006046-219f-11e6-84d4-021b7f0a2ee4.png)

**Comment by Tyriar** [comment]
I believe this is no longer an issue, upstream resizing logic has been changed significantly since 1.1.0
