### ISSUE TITLE
JavaScript built in features not working

### ISSUE THREAD

**Issue by caedes** [Microsoft/vscode#68248]
Hello! 👋

On a pretty new installation of VSCode, I don't have any of [the JavaScript features announced](https://code.visualstudio.com/Docs/languages/javascript) by Microsoft.

**VSCode Version:**
```
1.31.0
7c66f58312b48ed8ca4e387ebd9ffe9605332caa
x64
```

**OS Version:** `MacOS Mojave v10.14.2`

Steps to Reproduce:

1. Uninstall previous VSCode
1. `rm -rf ~/.vscode`
1. Install VSCode
1. Open a big 3-years-old JavaScript project with no `jsconfig.json`
1. Trying some of the features listed: Intellisense completion, Snippets, JS Doc support, Hover info, Go to definition, Auto imports, Refactoring.
1. None works (I can produce some GIF-screnshots but IMHO useless as it shows nothing…)
1. Adding a `jsoncfig.json` with just:
```json
{
  "compilerOptions": {
    "target": "es6"
  }
}
```
1. Trying some of the features listed above
1. None works

I try launching with `code --disable-extensions .` to check, and it also fails.
Does this issue occur when all extensions are disabled? **Yes**

Thanks for any help!

**Comment by kammce** [comment]
I'm in the same boat. I'm on the latest downloadable build of VSCode and javascript Intellisense doesn't for me.

**Comment by mjbvz** [comment]
Please check that you have not disabled the built-in `TypeScript and JavaScript Language Features` extension. In the extensions view, search `@builtin javascript`. Is `TypeScript and JavaScript Language Features` enabled?

Please also check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed in it?

**Comment by caedes** [comment]
Indeed. It was disabled.
<img width="449" alt="xmtul0rpzujuwjubrwtagpd1fdqvhgdegwromaarc80s6uxtoks6cdu5mbqxtbhz8i19kcvyrw1aduumcw5kskmpahyx6axcehhh" src="https://user-images.githubusercontent.com/1019321/52520337-bf58ce80-2c68-11e9-9afa-bb937c777e2e.png">

Works perfectly now! Thanks a lot!
<img width="553" alt="m9edh8ozoqxdhk1dulmmdijciaqit5jjsqioo6f42qajo0asagc6mo2x7ne5kn8vrl3tbsvl0tib9akgvzuiu8e7fhu0vtwk0yhr" src="https://user-images.githubusercontent.com/1019321/52520346-e4e5d800-2c68-11e9-9bc9-1a805af94725.png">
