### ISSUE TITLE
Open Workspace button in editor

### ISSUE THREAD

**Issue by creighton** [Microsoft/vscode#68249]
Issue Type: <b>Bug</b>

Just updated and now a "Open Workspace" button is in the lower right of my editor pane. Clicking it does nothing, nor will it go away. I already have a workspace open and some files.

VS Code version: Code - Insiders 1.32.0-insider (1c50a87561055485d93a3961160902308497f1e3, 2019-02-08T06:15:19.612Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.27GB free)|
|Process Argv|-psn_0_1552763|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.4.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
gc-excelviewer|Gra|2.1.28
vscode-styled-components|jpo|0.0.25
vscode-random|jre|1.5.0
language-julia|jul|0.11.4
graphql-for-vscode|kum|1.13.0
unicode-latex|oij|1.1.2
code-spell-checker|str|1.6.10
ReactSnippets|xab|2.3.0
cursorCharCode|zei|0.1.1

</details>

**Comment by ddzy** [comment]
> Issue Type: Bug
> 
> Just updated and now a "Open Workspace" button is in the lower right of my editor pane. Clicking it does nothing, nor will it go away. I already have a workspace open and some files.
> 
> VS Code version: Code - Insiders 1.32.0-insider ([1c50a87](https://github.com/Microsoft/vscode/commit/1c50a87561055485d93a3961160902308497f1e3), 2019-02-08T06:15:19.612Z)
> OS version: Darwin x64 18.2.0
> 
> System Info
> Extensions (13)

Same issue
