### ISSUE TITLE
Terminal Display Issue

### ISSUE THREAD

**Issue by rmeans** [Microsoft/vscode#68258]
Issue Type: <b>Bug</b>

When I open the terminal (configured to powershell), it adds a bunch of empty lines, so it appears the terminal did not initialize. If I scroll up then I see the Windows powershell Copyright... lines. Also, I do not see the prompt with the current directory, so when I start typing my text appears to be floating in the middle of the terminal window.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (21.65GB free)|
|Process Argv|--folder-uri file:///d%3A/Code/AgDirect/AgDirect/Source/WebUI|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.21
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
terminal|for|0.0.10
beautify|Hoo|1.4.8
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
vscode-versionlens|pfl|0.22.0
vscode-icons|rob|8.1.0

(1 theme extensions excluded)

</details>

**Comment by Sovgut** [comment]
I have same issue without extensions and clearly reinstalled of vscode 1.31.

Windows 10 Pro x64 with all latest updates

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
