### ISSUE TITLE
__linux__ is not defined according to GUI but is used as if it was

### ISSUE THREAD

**Issue by Donpampa** [Microsoft/vscode#68252]
Issue Type: <b>Bug</b>

I have this embedded code with following lines:

#if defined(\_\_linux\_\_ )
#include <osapi_linux.h>
#endif

\_\_linux\_\_ is not in defined any of the project files and VS Code also shows it as not set. However code under the #if check is processed and we try to include header

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 2889)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.55GB (7.34GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
githistory|don|0.4.6
xml|Dot|2.4.0
python|ms-|2019.1.0
cpptools|ms-|0.21.0

</details>

**Comment by kieferrm** [comment]
Please file the issue against the C++ extension. Thanks!

**Comment by Donpampa** [comment]
Thank you.
