### ISSUE TITLE
Expanding a CSS variable within var() sometimes add another var inside

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6825]
#6656 

This is the most reliable repro I found:

![image](https://cloud.githubusercontent.com/assets/2193314/15514901/3ccf3ad8-21a0-11e6-9109-a54f88fbf344.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15514912/477ad53c-21a0-11e6-9e80-a901f911250a.png)

**Comment by sandy081** [comment]
Dup of #6754
