### ISSUE TITLE
Message not found message visible in .ts files.

### ISSUE THREAD

**Issue by sanket-bhalerao** [Microsoft/vscode#68259]
Message not found message are currently visible in typescript files.
please see the snapshot attached.
![image](https://user-images.githubusercontent.com/9264813/52490502-dce75300-2bea-11e9-9c82-0fccf4a2e43d.png)

**Comment by mattacosta** [comment]
I'm also seeing this. Devtools shows a bunch of error messages for each extension file similar to:

`Messages for file c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\features\jsDocCompletions not found. See console for details. (at Object.w [as loadMessageBundle] (c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:7339))`

I'm also seeing this message in the output panel select box:
![output-bug](https://user-images.githubusercontent.com/1007463/52528186-458b0a00-2c95-11e9-84f1-7cff382017f1.png)

The output panel itself doesn't have anything interesting.

**Comment by sanket-bhalerao** [comment]
in the settings json, following setting is showing the message
`"typescript.referencesCodeLens.enabled": true,`
it it is changed to false then the entire message is hidden.
I am not sure of the cause of the issue. 
let me know how i can provide more details on this.

**Comment by mjbvz** [comment]
Duplicate of #68393
