### ISSUE TITLE
Go To Definition doesn't work until VS Code restart after switching branch

### ISSUE THREAD

**Issue by rohansekhri** [Microsoft/vscode#68256]
Preconditions:
----------------
1. Python workspace has 2 folders, each aligned to a different repo. for eg: AB and XY 
2. git is installed and user is on master branch in folder AB. It also has a branch dev1
3. dev1 has a method foo() in import_me.py but is not there on the master branch yet
4. In folder XY user is on dev1 [note this is not the same as dev1 of AB], user imports import_me and uses foo() in qwerty.py --> foobar()

Steps:
----------------
1. User realizes he is on the wrong branch in folder AB and switches to dev1 in AB
2. User then goes to foobar() and CTRL + Clicks on foo() or right click on foo() and selects 'Go to Definition'

Expected result:
-----------------
Files should be re-indexed when branch was switched and either of the two actions in Step #2 should take the user to AB -> import_me.py -> foo()

Actual result:
----------------
Unless VS Code is restarted, none of the actions result in the user being taken to AB -> import_me.py -> foo()

Note: Started happening since Jan 2019 update 1.31.0

Extension list: 
----------------

```
vscode-markdownlint | Dav | 0.23.0
-- | -- | --
githistory | don | 0.4.6
xml | Dot | 2.4.0
gitlens | eam | 9.5.0
git-project-manager | fel | 1.7.1
vscode-pull-request-github | Git | 0.4.0
python | ms- | 2019.1.0
cpptools | ms- | 0.21.0
csharp | ms- | 1.17.1
notepadplusplus-keybindings | ms- | 1.0.2
material-icon-theme | PKi | 3.6.2
quicktype | qui | 12.0.46
vscode-icons | rob | 8.1.0
open-in-browser | tec | 2.0.0
rf-intellisense | Tom | 2.3.0
vscode-open-in-github | ziy | 1.3.6
```

**Comment by kieferrm** [comment]
Please file the issue against the python extension.
