### ISSUE TITLE
 IoTHub-lab2-bis is not currently in Active state.

### ISSUE THREAD

**Issue by Maurodipa** [Microsoft/vscode#68251]
I am not currently able to create an IoT Hub. I receive the following messages in the Ouput tab: 
Try the request again after it is in Active state. If you contact a support representative please include this correlation identifier: e4c764fe-a8af-44ef-b906-1adc0a61bb90, timestamp: 2019-02-08 15:07:08Z, errorcode: IH409002.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.70GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.13.1
azure-account|ms-|0.8.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
azure-iot-edge|vsc|1.9.0
azure-iot-toolkit|vsc|2.2.0
azure-iot-tools|vsc|0.0.1
vscode-arduino|vsc|0.2.25
vscode-iot-workbench|vsc|0.2.3

</details>

**Comment by dbaeumer** [comment]
@Maurodipa I would recommend that you report this against Azure. I don't see how this is related to VS Code. If you see this from an extension you use, please file it against that extension. 

If you still think this is an issue with VS Code please provide steps on how to reproduce this.
