### ISSUE TITLE
Moving lines changes indentation of copyright statement

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#68253]
Steps to Reproduce:

1. have a file with just copy right statement
2. auto import a module (not required)
3. move it down using "Move Line Down" commands

=> 🐛 the copyright statement changes its indentation

![grid-tw](https://user-images.githubusercontent.com/900690/52488292-c8419580-2bbf-11e9-9b35-d381ffb0ee79.gif)

**Comment by rebornix** [comment]
The block indentation structure is handled by `onEnterRules` but the indentations rules don't understand it. Improving the indentations rules to support this scenario is difficult (as it's not multiple-line aware). The workaround here is changing `editor.autoIndent` to `advanced`. Closing it as it's not actionable.
