### ISSUE TITLE
Clickable links stripping %0a character codes from link

### ISSUE THREAD

**Issue by trailstrider** [Microsoft/vscode#68254]
We have written the neede
Issue Type: <b>Bug</b>

Create a link that opens and prefills a webform, for example:

https://www.myfqdn.com/coolsSystem/main/new?keyword=BOB&SummaryText=My%20Explanation:%0a%0aMore%20Text%20Here.

When the form gets filled from clicking the link in Notepadd++ or email link, it works just fine and the Summary Text field fills appropriately with the newline, like the following:

My Explanation:

More Text Here.

When clicking from Visual Studio Code I get this:

My Explanation:More Text Here.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (5.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.9.0
cpptools|ms-|0.21.0
vsliveshare|ms-|0.3.1151

</details>
d data into your clipboard because it was too large to send. Please paste.

**Comment by dbaeumer** [comment]
Were do you click on that link. In the editor or the terminal ?

**Comment by trailstrider** [comment]
In the editor.

**Comment by kieferrm** [comment]
The url `https://www.myfqdn.com/coolsSystem/main/new?keyword=BOB&SummaryText=My%20Explanation:%0a%0aMore%20Text%20Here.` when cmd+clicked in the editor is opened as `https://www.myfqdn.com/coolsSystem/main/new?keyword=BOB&SummaryText=My%20Explanation:More%20Text%20Here.` Same happens in the terminal.   In both cases we go through the `OpenerService`.
