### ISSUE TITLE
Proxy Support for Extensions should also include NO_PROXY

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode#68260]
Issue Type: <b>Feature Request</b>

The support for Extensions using the proxy setting is great! Unfortunatly for some things like "ms-vsts.team" extension or others where you need to connect to internal resources the proxy settings need to be ignored. This can be done through the NO_PROXY variable, or maybe even just a custom list in the settings to reproduce the NO_PROXY list so that internal extensions don't fail when requesting resources inside a firewall

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 6.1.7601

**Comment by chrmarti** [comment]
Related: #12588

**Comment by miguellira** [comment]
@nschonni I am running into an issue with `ms-vsts.team` when attempting to sign in to a local TFS server and I believe it surfaced after updating VS Code. Unfortunately, I am not able to find any logs that clearly state the error. The only indication is a (!) next to Team in the status bar and when I hover over I see the  message `Failed Request: Temporary Redirect(307) -`:

![image](https://user-images.githubusercontent.com/1449255/53042800-19ba1200-3455-11e9-9070-fcfa7ea21ccc.png)

Are you experiencing a similar issue. If so, what is your current workaround? Downgrade to a previous version of VS Code?

**Comment by miguellira** [comment]
@nschonni Please disregard. After I posted this message I found the following [issue](https://github.com/Microsoft/vscode/issues/68442#issue-408888870) that resolved my error.

Visual Studio Code now provides a Proxy Support setting that can be disabled.

**Comment by chrmarti** [comment]
Related: https://github.com/Microsoft/azure-repos-vscode/issues/465

**Comment by chrmarti** [comment]
There does not appear to be any agreement between different tools on how to interpret `NO_PROXY`.

Would the following work:
- `NO_PROXY` is a comma-separated list of hostnames and domains.
- A hostname (e.g., `mail`, `company.com`, `www.company.com`) matches only that one hostname.
- A domain starts with a `.` (e.g., `.company.com`) and matches all hostnames in that domain, including the hostname equal to the domain (e.g., `.company.com` matches `company.com`, `www.company.com`, `mail.company.com`).

/cc @joaomoreno

**Comment by nschonni** [comment]
I'd suggest looking at/using the request implementation https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
It is the most used network library for node, and is well tested for edge cases.

**Comment by chrmarti** [comment]
Good point, I'll go with that. They additionally:
- Let hostnames match all hosts in subdomains (e.g., `company.com` matches `www.company.com`).
- Let `*` match all hostnames.
- Let `hostname:port` match only if the port matches too.

**Comment by joaomoreno** [comment]
@chrmarti Also relevant:

```
# Disable proxy per host
--proxy-bypass-list=(<trailing_domain>|<ip-address>)[:<port>][;...]
```

https://code.visualstudio.com/docs/setup/network#_ssl-certificates

**Comment by chrmarti** [comment]
@joaomoreno I think we should get these through Electron's API already.

**Comment by chrmarti** [comment]
@nschonni This is in the latest Insiders build. Could you give it a try and let me know if it works for you?

**Comment by chrmarti** [comment]
To verify:
- Prepare a test extension with two requests and verify they work:
  - `http.get('http://microsoft.com', res => console.log(res.statusCode)).on('error', console.error);`
  - `http.get('http://github.com', res => console.log(res.statusCode)).on('error', console.error);`
- Start VS Code with environment variable `HTTP_PROXY=http://localhost:9999` (without anything listening on that port) and verify both requests fail.
- Start VS Code with environment variables `HTTP_PROXY=http://localhost:9999` (without anything listening on that port), `NO_PROXY=microsoft.com` and verify only the `github.com` request fails.
