### ISSUE TITLE
CSS color completion doesn't show color sample

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#68269]
_Reported on twitter_

* MacOS
* open a CSS file
* press # to bring up color completions

result: in 1.31.0 we don't see the color preview

1.30.2

![image](https://user-images.githubusercontent.com/1487073/52496793-3323aa00-2b89-11e9-843e-9b0cb00168b9.png)

1.31.0
![image](https://user-images.githubusercontent.com/1487073/52496867-71b96480-2b89-11e9-927b-0b770c357bdf.png)

**Comment by csgrant83** [comment]
Same problem, except I am on Windows 10

**Comment by octref** [comment]
@jrieken Any idea? Seems #67029 wasn't verified since we forgot to add it to milestone.

**Comment by jrieken** [comment]
<img width="559" alt="screenshot 2019-02-13 at 08 37 06" src="https://user-images.githubusercontent.com/1794099/52694606-8e2f1580-2f6a-11e9-8fbf-a9dd4cc3f8dd.png">


doesn't reproduce for me. @octref steps? settings?

**Comment by jrieken** [comment]
Ha, you need to get a hex value proposed. Didn't know we support that. @octref feel free to investigate and fix. This feature is has been added for css only and I think its fair if css maintains it

**Comment by jrieken** [comment]
Muahaha, I think we broken this feature three times with strict-null-works. I am confident this time it's better 🤞
