### ISSUE TITLE
Issue when typing "~" and accented characters on a French/Belgian keyboard in terminal

### ISSUE THREAD

**Issue by gdlx** [microsoft/vscode#68262]
- VSCode Version: 1.31.0
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Try to type the "~" character on a french keyboard (AltGr-é) in the terminal
2. You get the "é" character, then by pressing space, you get the "~" character.

Note that the normal behavior on a french keyboard is to type AltGr-é, then press space to get the character (because it's supposed to be used as a character accent, keyboards aren't made for coders).

The real issue is that th "é" character shouldn't be inserted.

The issue only happens in the terminal, not in the editor.

**Comment by roonie007** [comment]
+1, this is super annoying, and it started just after the update 1.31 on Windows, for my case I am using a WSL bash integrated in vscode

**Comment by gdlx** [comment]
@roonie007 I'm using WSL bash too.

**Comment by Tyriar** [comment]
Does tweaking the setting `terminal.integrated.setLocaleVariables` help?

**Comment by roonie007** [comment]
@Tyriar Tried it with, true and false, restarted terminal and vs-code each time, same problem

**Comment by loganmzz** [comment]
For information, it happens with any terminal type and only in terminal pane.

**Comment by bcxpro** [comment]
I have the same problem with the Spanish keyboard. ~ is co-located with the "4" key So instead of getting ~ I get 4~ on the terminal.
It happens on Windows  and not on Linux to me (vscode 1.33.1 and insider 1.34.0, Windows 10 1809)
