### ISSUE TITLE
VSCode imports don't work properly

### ISSUE THREAD

**Issue by temurih** [Microsoft/vscode#68267]
Last time when reported the same problem, I have been told that I need to provide the steps to reproduce. I wasn't sure how I can describe the steps to reproduce when sometimes it works, and sometimes it does not. I have recorded a video when it wasn't working with the files right next to each other, and it took me a minute to manually import.

Here is the video: https://www.youtube.com/watch?v=ZMaf1b5j0U8

**Comment by mjbvz** [comment]
Yes please provide an example project or example code. You can also check the TypeScript Server trace to see if there is are any errors:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

But without an example, we cannot investigate this
