### ISSUE TITLE
Presented intellisense for variable definitions is not useful

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6826]
#6656 

![image](https://cloud.githubusercontent.com/assets/2193314/15514959/85f3bb6c-21a0-11e6-8df9-59be4980c1dd.png)

Expanding add the border snippet:

![image](https://cloud.githubusercontent.com/assets/2193314/15514987/a654bece-21a0-11e6-939f-8654e8107d1a.png)

**Comment by sandy081** [comment]
Dup of #6748

**Comment by sandy081** [comment]
duplicate #6748

**Comment by sandy081** [comment]
duplicates #6748
