### ISSUE TITLE
Variable with repository name in Snippets

### ISSUE THREAD

**Issue by mrclolveira** [Microsoft/vscode#68261]
It would be really helpful if a variable with the repository name (workspace name or opened folder) that was available to use in the snippets.

In my case, i use the snippets to create copyright  messages, and i am using the project name (the same of the repository) as part of this message.

**Comment by gmertk** [comment]
Hey @jrieken, 
I'd like to work on this. Can I give it a shot? 
I appreciate if you have any quick guidance.

**Comment by jrieken** [comment]
* Snippet variables are implemented [here](https://github.com/Microsoft/vscode/blob/41c7d3788f254be5fa75c4738086cf037f9ff7ab/src/vs/editor/contrib/snippet/snippetVariables.ts#L210) and instantiated [here](https://github.com/Microsoft/vscode/blob/41c7d3788f254be5fa75c4738086cf037f9ff7ab/src/vs/editor/contrib/snippet/snippetSession.ts#L409).
* add a variable resolver that uses the [workspace service](https://github.com/Microsoft/vscode/blob/41c7d3788f254be5fa75c4738086cf037f9ff7ab/src/vs/platform/workspace/common/workspace.ts#L30) (like the `ClipboardBasedVariableResolver` and `IClipboardService`)

**Comment by mrclolveira** [comment]
Thanks :)
