### ISSUE TITLE
"Dirty" font display bug introduced in latest update

### ISSUE THREAD

**Issue by PatrickHollweck** [microsoft/vscode#68264]
- VSCode Version: 1.31
- OS Version: Windows 10.0.17134 Build 1734

Steps to Reproduce:

1. Update to latest version
2. Set font to "Inconsolata-g" ( yes, this issue only happens with this font. It worked in 1.30 )
3. Type a lowercase "k"
4. Observe text artifact ( screenshot below ) - Text seems more pixelated overall

Happens only in the latest update. I reverted back to the previous version and it worked fine again.
Only happens with said font and all themes.

![capture](https://user-images.githubusercontent.com/20997737/52493451-c2ea4800-2bcb-11e9-9668-afee398bb8dd.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
I can't reproduce this issue on macOS but will try Windows later.

**Comment by rebornix** [comment]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/876920/52580085-788be580-2ddc-11e9-82e7-f83fd76ce406.png">

I can't reproduce this issue with 1.31 on Windows 10, it would be great if you can provide more detailed information about how to reproduce.

**Comment by FetzenRndy** [comment]
To investigate this bug alittle more I fired up a fresh install of vscode insiders and I found that the bug only appears with these settings:

```json
{
  "editor.fontFamily": "Inconsolata-g",
  "editor.fontWeight": "600",
}
```

**Comment by waynebloss** [comment]
I have been getting this in the titlebar on Arch Linux (Manjaro):

![Screenshot_2019-05-15_12-54-04](https://user-images.githubusercontent.com/623736/57794334-65f1b700-7711-11e9-991a-8305b85caf4c.png)

**Comment by PatrickHollweck** [comment]
Closing this, since it can not be reproduced in latest version.

**Comment by waynebloss** [comment]
What's the latest version? I can reproduce with the version that I have.

Here are my details:

```
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.49-1-MANJARO
```

**Comment by waynebloss** [comment]
![Screenshot_2019-06-17_10-12-06](https://user-images.githubusercontent.com/623736/59610980-79b18400-90e8-11e9-9146-40a448ac4c4a.png)

**Comment by PatrickHollweck** [comment]
My version is: 1.35.1

What font are you using? @waynebloss

**Comment by waynebloss** [comment]
@PatrickHollweck 1.35.1 - My other details are in [a previous comment](https://github.com/microsoft/vscode/issues/68264#issuecomment-502683665)

**Comment by waynebloss** [comment]
Is there anything that I can do to help? Do you want me to run with some verbose logging on until it happens or something?

**Comment by rebornix** [comment]
I'll try to reproduce this on a Linux machine.

**Comment by waynebloss** [comment]
It’s no big deal. It doesn’t happen with the native titlebar so I just switched to that.
