### ISSUE TITLE
Breakpoints Line Number State is Lost 

### ISSUE THREAD

**Issue by interpegasus** [Microsoft/vscode#68265]
- VSCode Version:Version 1.31.0 (1.31.0)
- OS Version: 10.14.2 (18C54)

**Steps to Reproduce:**

1. Create a Node.js project 
2. Create some breakpoints.
3. Launch the Visual Studio Code built-in debugger

**Result**
Some breakpoints are erased, and some others change line number.
Usually one breakpoint is automatically added in the first lines of the file.
Breakpoints have to be recreated.

**Expected behavior** 
The app should remember the line numbers, and status of each break point.

**Does this issue occur when all extensions are disabled?**
Yes

`VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* code --disable-extensions`

**Comment by interpegasus** [comment]
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "nodemon",
            "restart": true,
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "name": "Launch Debugger",
            "program": "${workspaceRoot}/bin/www"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858
        },
    ]
}
```

**Comment by roblourens** [comment]
Can your project be shared? If not can you set `"trace": true` in your launch config, try this again, then upload the log from the path it writes to the debug console?

**Comment by interpegasus** [comment]
I have created a sample project without sensitive data. For debugging the breakpoint issue on Visual Studio. Thank you! :
https://github.com/interpegasus/BreakPointDebug

**Comment by roblourens** [comment]
I can't run this, it looks like it's expecting a mongo server or something, how can I run it without that?

```
/Users/roblou/Documents/BreakPointDebug/node_modules/mongo-express/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at Pool.<anonymous> (/Users/roblou/Documents/BreakPointDebug/node_modules/mongo-express/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/Users/roblou/Documents/BreakPointDebug/node_modules/mongo-express/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/Users/roblou/Documents/BreakPointDebug/node_modules/mongo-express/node_modules/mongodb-core/lib/connection/connection.js:175:49)
```

**Comment by interpegasus** [comment]
Good morning, 

The project has been updated and the dependency has been removed. https://github.com/interpegasus/BreakPointDebug

The issue can be tested by adding breakpoints in` app.js `. After starting/restarting the debugger, the breakpoints are rearranged and the state (enabled / not enabled) is sometimes lost.

Please let me know in case you have any other questions. Thank you!

**Comment by roblourens** [comment]
Thanks. You just have to add two lines to your launch config:

`"disableOptimisticBPs": true` for this issue: https://github.com/facebook/create-react-app/issues/6044 because app.js is the name of the script in the runtime and also the sourcemapped source name.

And `"smartStep": false` for this issue: https://github.com/Microsoft/vscode/issues/68127
