### ISSUE TITLE
Add button to run/compile application

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#68270]
This is a feature request coming from NPS:

"Better to integrate build & run buttons."
"Add the ability to run compilers when needed (like textpad did with Java back in the day)"
"more VS Code supplied options to run code"

**Proposal:**
Extend UI for debug toolbar to include a way to run/compile an application without debugging. This could be in a new generic toolbar available from the editor

**Comment by rei-vilo** [comment]
The tool-bar has been debated at #1833.
