### ISSUE TITLE
vscode.env.openExternal not available

### ISSUE THREAD

**Issue by cillroy** [Microsoft/vscode#68275]
- VSCode Version:1.31.0
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Create an Extension
1. `vscode.env.openExternal(SomeUri);`
   1. Property 'openExternal' does not exist on type 'typeof env'.
   1. Same with `vscode.env.open(SomeUri);`
      1. Property 'open' does not exist on type 'typeof env'.

Does this issue occur when all extensions are disabled?: Yes/No
YES

If I choose to "DEBUG ANYWAY" the functionality does work as expected, the concern is the error messaging

**Comment by bpasero** [comment]
Make sure you ran npm install and have this in the extension:

	"engines": {
		"vscode": "^1.31.0"
	}

**Comment by cillroy** [comment]
thanks so much - changing from 1.30.0 to 1.31.0 in package.json and then `npm install` fixed it!  First extension published!
