### ISSUE TITLE
Keyboard shortcut search results for "focus terminal" have odd ordering

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/vscode#68271]
Issue Type: <b>Bug</b>

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

### Steps and results
1. Open keyboard shortcuts settings
2. Search for "focus terminal"

**Expected:** The command called "Terminal: Focus Terminal" should be at/near the top of the list, since the command name contains an exact match for what I typed (and closely-related commands like "Terminal: Focus _____" should be soon after).

**Actual:** It's waaayyyyy down at the bottom. Seems like an issue with the search ranking engine.

Even if I search specifically for "terminal: focus terminal" the command which is an exact match is listed last.

<details>
<summary>Expand for screenshots of "focus terminal" search</summary>
<img src="https://user-images.githubusercontent.com/5864305/52497050-e4c2db00-2b89-11e9-81aa-7843719c423f.png"/>
<img src="https://user-images.githubusercontent.com/5864305/52497194-4d11bc80-2b8a-11e9-8c9d-d0e34e9aba2b.png"/>
<img src="https://user-images.githubusercontent.com/5864305/52497144-2f445780-2b8a-11e9-9eda-d469d3195a95.png"/>
</details>

<details>
<summary>Expand for screenshots of "terminal: focus terminal" search</summary>
<img src="https://user-images.githubusercontent.com/5864305/52497517-21db9d00-2b8b-11e9-9e03-c857adb7bdc2.png"/>
</details>

### System details

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
format-php|Kas|1.1.2
githistory|don|0.4.6
tslint|eg2|1.0.42
vscode-pull-request-github|Git|0.4.0
python|ms-|2019.1.0
vscode-docker|Pet|0.5.2
annotator|ryu|0.11.0
partial-diff|ryu|1.4.0
gitblame|wad|2.6.3
quokka-vscode|Wal|1.0.182

</details>

**Comment by sandy081** [comment]
There is no sorting of results in Keybindings Editor.

**Comment by ecraig12345** [comment]
Well they're clearly being ordered somehow... Is it just based on the order that they're declared in the built-in keybindings file?

**Comment by sandy081** [comment]
Yes, there are only two orders for now. Sort by Precedence & Sort by Command name.

**Comment by ecraig12345** [comment]
How is precedence determined?

**Comment by sandy081** [comment]
User defined keybindings are first and then followed by the defaults.
