### ISSUE TITLE
supprime mes fichiers

### ISSUE THREAD

**Issue by Brade82** [Microsoft/vscode#68278]
Issue Type: <b>Bug</b>

Bonjour quand j'ai mon espace de travail ouvert et des fichiers ouvert ou non à chaque mise à jour de microsoft visual code cela me supprime tout mon dossier définitivement et je ne peux rien faire pour récupèrer les dossiers et les fichiers. 

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.6.2
Bookmarks|ale|10.2.2
alignment|ann|0.3.0
love|bsc|0.3.6
indent4to2|Com|0.1.2
vscode-markdownlint|Dav|0.23.0
vscode-language-pack-fr|MS-|1.31.4
pixelbyte-love2d|pix|0.1.19
markdown-preview-enhanced|shd|0.3.11
corona-tools|Tob|0.1.0
vscode-lua|tri|0.12.4
markdown-all-in-one|yzh|2.0.1

</details>

**Comment by kieferrm** [comment]
Please add concrete steps that allow us to reproduce you problem. Thanks!

**Comment by Brade82** [comment]
When there is an update to perform, I make it and after updating my workspace that was open with all my files were removed from my computer, this is the second time that it's me come

**Comment by Brade82** [comment]
So for the moment I think I will use another code editor because I do not want to lose my job every update

**Comment by kieferrm** [comment]
@Brade82 I'm sorry to hear that this is happening to you. Among all of our users, we don't have any other reports about this. Without concrete steps we cannot reproduce the problem.
