### ISSUE TITLE
"Open Editors" context-menu should include commands contributed via "editor/title/context"

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#68285]
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:32:14.164Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Steps to Reproduce:

1. Create an extension that contributes a command via `editor/title/context`.
2. Launch extension host.
3. Open a file for editing (something that appears in `Open Editors`) for which the command is applicable.
4. Right-click on editor tab title, note the command appears as expected.
5. Right-click on the same file in `Explorer` > `Open Editors`, note the command does not appear.

These should be more or less the same commands, right?  There is no other way to target custom commands to this `Open Editors` area according to the current docs.

Important since file/resource-level commands can be useful on files that are open, but not part of the current workspace, where they can be targeted via `explorer/context`.

**Comment by johnspurlock** [comment]
cc @bpasero from comment over on https://github.com/Microsoft/vscode/issues/14014#issuecomment-256550401

**Comment by isidorn** [comment]
Dup of make the open editors context menu contributable

**Comment by johnspurlock** [comment]
@isidorn Dup of which open issue?

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/52713

**Comment by johnspurlock** [comment]
Ah ok, thanks!
