### ISSUE TITLE
Terminal rename doesn't work

### ISSUE THREAD

**Issue by marianmaria2222** [Microsoft/vscode#68287]
- VSCode Version: 1.31.0
- OS Version: Windows 7
- Note I am using Cygwin bash: "terminal.integrated.shell.windows": "C:\\Users\\Prgs\\cygwin\\bin\\bash.exe",

Steps to Reproduce:

1. Select Terminal | New Terminal
2. Command Palette | Terminal : Rename
3. Change name to anything, press Enter.
4. In the Terminal's selection box the name changes correctly, but
5. The moment you type anything in the teminal window, the name changes back to "1: bash"

Note this worked correctly in previous versions of vscode

Does this issue occur when all extensions are disabled?: *Yes*

**Comment by Tyriar** [comment]
Can repro on Windows 10.

**Comment by awdltd** [comment]
Could also reproduce since most recent upgrade on Windows 10. Glad to see there is a fix already - thanks!

**Comment by marianmaria2222** [comment]
Still broken in 1.32.1
