### ISSUE TITLE
Comparing Multiple Files

### ISSUE THREAD

**Issue by cpeterson-esi** [Microsoft/vscode#68286]
Issue Type: <b>Bug</b>

I open a folder with fileA, fileB, and fileC. Holding Ctrl while selcting fileA and fileB, then right clicking and selecting "Compare Selected" allows me to compare those two files successfully.
I then select fileA and fileC, then right click and select "Compare Selected".

Sometimes this correctly results in 2 tabs for comparing files. Other times, this ends up closing the first tab (fileA and fileB) when it opens the second. Once this error happens, it's nearly impossible to have two comparison tabs again. 

I think this error happens sometimes when I close VS code without shutting down each comparison file first. Once the error occurs, creating a new file starts at what the previous file number was. If I closed had a Untitled-1 and Untitled-2 open, then closed them without saving, then closed VS code then the next time I create a new file it is Untitled-3.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz (8 x 2926)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.93GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.28
cpptools|ms-|0.21.0

</details>

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
