### ISSUE TITLE
Insiders: cannot close application

### ISSUE THREAD

**Issue by derekwallace** [microsoft/vscode#68280]
windows 10
insiders 1.32.0
when i open the UI is semi frozen.
The C
i cannot close the application.
i have to kill process in task manager.

i have killed , un-install and re-install.

i have 1.31.0 installed with no issue.
im using the same worspace settings file in insiders.

**Comment by derekwallace** [comment]
What more information can i provide?
Windows 10
Version 1.32.0 Insiders.
Open Insiders.
I Cannot close the application and have to kill the process.

I also have 1.31.0 of code and it is working fine.

![image](https://user-images.githubusercontent.com/5574230/52548555-4ec7c400-2dc6-11e9-808a-845365463879.png)

![image](https://user-images.githubusercontent.com/5574230/52548567-5edfa380-2dc6-11e9-82ae-96a4204e25bb.png)

No extensions
![image](https://user-images.githubusercontent.com/5574230/52548580-774fbe00-2dc6-11e9-95f7-4bd072b09a51.png)

Nothing happens.
![image](https://user-images.githubusercontent.com/5574230/52548624-a6662f80-2dc6-11e9-84e3-3a693597edda.png)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by derekwallace** [comment]
What i now notice is that File - Exit is not working for some long window of time (it is 5 min +)
after this the command does work and the application exits .

there are other un-responsive things.
For examle Ctrl+,. I have enabled the split json view (      "workbench.settings.useSplitJSON": true,
)
it doesnt work. the json files are not opened for user, worksace and folder settings. they are just empty.
After some long time, this starts to work aswell.

My objective with insiders build is to test the new setting
     "search.maintainFileSearchCache": true,

I dont know if the changes made here have impacted the startup of the application.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by derekwallace** [comment]
tried teh exploration build and it does not have the issue.

**Comment by derekwallace** [comment]
retruned to retry this. still finding the application is not reponding correclty.
- cannot file -exit
- the settings explorer in json viewer does not work. it will not display the user/workspace/folder settings.
latest insiders has the issu.e
latest exploration build has the issue.

**Comment by derekwallace** [comment]
.\code-insiders -verbose
1.32.0-insider
804373ac4d5c84e96c8086cee5b9be132df88837
x64

In the Output Console there is no log information for any of the options Tasks|Extensions|Log (*) 

Developer Tools - COnsole output

[Extension Host] debugger listening on port 51121
console.ts:134 [Extension Host] Git installation not found. (at t.activate (c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\git\dist\main.js:1:126952))
t.log @ console.ts:134
log.ts:161  INFO standard startup
2lifecycle.ts:61 Registering disposable on object that has already been disposed.
_register @ lifecycle.ts:61
3lifecycle.ts:61 Registering disposable on object that has already been disposed.
_register @ lifecycle.ts:61
_getOrCreateWorker @ editorWorkerServiceImpl.ts:350
_getProxy @ editorWorkerServiceImpl.ts:363
_withSyncedResources @ editorWorkerServiceImpl.ts:378
computeLinks @ editorWorkerServiceImpl.ts:403
p._workerManager.withWorker.then.t @ editorWorkerServiceImpl.ts:65
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
provideLinks @ editorWorkerServiceImpl.ts:65
r.LinkProviderRegistry.ordered.reverse.map.s @ getLinks.ts:75
c @ getLinks.ts:74
computePromise.s.createCancelablePromise.t @ links.ts:249
a @ async.ts:23
(anonymous) @ links.ts:249
(anonymous) @ errors.ts:184
n @ errors.ts:184
beginCompute @ links.ts:238
onModelChanged @ links.ts:226
listenersToRemove.push.e.onDidChangeModel.e @ links.ts:207
fire @ event.ts:584
setModel @ codeEditorWidget.ts:421
e.resolve.then.s @ textResourceEditor.ts:79
_tickCallback @ internal/process/next_tick.js:68

**Comment by derekwallace** [comment]
ive noticed that any file i open is not rendered.
they all appear blank.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
