### ISSUE TITLE
the default setting cannot see

### ISSUE THREAD

**Issue by yxsh01** [Microsoft/vscode#68281]
Issue Type: <b>Bug</b>

I try to open setting.json, but previously it shows both setting.json and default setting. currently it just open setting.json file. Even I reinstall VS code and delete AppData\Roaming\Code it doesn't work.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.6.0
include-autocomplete|ajs|0.0.4
vscode-fileheader|mik|0.0.2
cpptools|ms-|0.21.0
csharp|ms-|1.17.1

</details>

**Comment by yxsh01** [comment]
It's different with that issue * setting.json property expected(bug) (#66831)

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_31#_use-simple-text-editor-for-editing-settings-as-json

**Comment by johnnytemp** [comment]
Could you give the reason behind for the change to only show settings.json in version 1.31.0 ?  As a user I strongly disagree.  If I want to edit the settings by json, I have no default settings to search the options name so as to copy it and change it.

**Comment by johnnytemp** [comment]
Ok, I found a way to open the default settings which makes this acceptable:

Cmd-Shift-P, type `default` and locate "Preferences: Open Raw Default Settings"
