### ISSUE TITLE
Close Notification keyboard shortcut is no longer working

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#68289]
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

 Attempt to close any notification using the default keyboard shortcut on Windows (Delete) or OSX (cmd+backspace)

When you hover over the X in the notification it confirms the shortcut to use in the tooltip (Delete)

![image](https://user-images.githubusercontent.com/8161247/52513873-7d754d00-2bc2-11e9-9745-f5a479d7cef2.png)

Note: this appears to be breaking some of the VS Live Share UI tests that rely on these shortcuts.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@jramsay carefull, that keyboard shortcut will only work if you have focus in the notification (e.g. click into it). You can see the contexts here:

![image](https://user-images.githubusercontent.com/900690/52518210-63318280-2c47-11e9-8c45-2f8219bbfafd.png)

Can you provide more details how you think this used to work in 1.30?

**Comment by jramsay** [comment]
Thanks - you're right. It appears to be a timing issue with the tests where the click into the notification isn't always happening before we dispatch the keyboard shortcut to dismiss.  When I was testing it manually I wasn't doing the explicit click,  Sorry about that - closing the issue.
