### ISSUE TITLE
Emmet html boilerplate no longer automatically showing up?

### ISSUE THREAD

**Issue by oleersoy** [Microsoft/vscode#68284]
[I got most of it to work as documented in the SO post](https://stackoverflow.com/questions/54601233/vscode-emmet-html-boilerplate).  However the intellisense no longer shows me the snippets even though I have turned that on.  Thoughts?

**Comment by ramya-rao-a** [comment]
I do see the suggestions for `!`

<img width="924" alt="screen shot 2019-02-09 at 6 40 22 pm" src="https://user-images.githubusercontent.com/16890566/52528730-2e9ae680-2c9a-11e9-8871-99aac6d2fa51.png">

Do you see emmet suggestions showing up for other abbreviations?

**Comment by oleersoy** [comment]
No ... but I'm starting to think that this has something to do with the plugins I have installed.  When I select `ctrl+shift+p` and the `format document` it says:
> There is no document formatter for 'nunjucks'-files installed.

Even though the file is an `html` extension file ... Thoughts?

**Comment by octref** [comment]
Whatever your filetype is (Run "Change Language Mode" to see a list), use https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types to make Emmet available for that html-like filetype.
