### ISSUE TITLE
Slow to log into Azure extensions

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#68283]
```
Version: 1.32.0-insider (user setup)
Commit: 709bf352b12de8284683bef94cb5984129bfc776
Date: 2019-02-08T14:53:26.555Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

It's taking upwards of 3 minutes from when I click on the Azure icon in the activity bar until I see the list of subscriptions in the trees.  I see "activating extensions" for < 0:10 in the status bar, then it seems to hang for a long time until we're signed in.

Profiled the extensions:

![image](https://user-images.githubusercontent.com/1487073/52507432-5a3ca480-2ba6-11e9-9cfd-62f6eda66315.png)

[CPU-20190208T212944.556Z.cpuprofile.zip](https://github.com/Microsoft/vscode/files/2846962/CPU-20190208T212944.556Z.cpuprofile.zip)

//cc @EricJizbaMSFT

**Comment by EricJizbaMSFT** [comment]
A webpacked version of Functions should release soon (probably next week).

@Stephenweatherford for other extensions.

**Comment by StephenWeatherford** [comment]
Cosmos is about to ship, Docker and App Service have already shipped. Storage and ARM should be soon.

**Comment by jrieken** [comment]
> see "activating extensions" for < 0:10 in the status bar,

Yeah, we hide that message because of https://github.com/Microsoft/vscode/issues/61846. Not sure how we can improve that. For once people say it feels slower in the presence of that message and sometimes extensions never finish, meaning we have to stop it.

**Comment by jrieken** [comment]
@chrisdias Can you add the "F1 > Startup Performance" numbers *after* things have settled? It will allow us to know how much time was spend loading extension code and running it.

**Comment by chrisdias** [comment]
## System Info

* Code - Insiders: 1.32.0-insider (d18d0edce11ac396bf7654ac96e0d522681b5553)
* OS: win32(10.0.17134)
* CPUs: Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz(4 x 2494)
* Memory(System): 7.98 GB(3.08GB free)
* Memory(Process): 177.74 MB working set(177.74MB peak, 150.56MB private, 38.85MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                    | Duration | Process          | Info                                 |
| ------------------------------------------------------- | -------- | ---------------- | ------------------------------------ |
| start => app.isReady                                    | 68       | [main]           | initial startup: true                |
| nls:start => nls:end                                    | 0        | [main]           | initial startup: true                |
| require(main.bundle.js)                                 | 404      | [main]           | initial startup: true                |
| app.isReady => window.loadUrl()                         | 988      | [main]           | initial startup: true                |
| require & init global storage                           | 182      | [main]           | initial startup: true                |
| window.loadUrl() => begin to require(workbench.main.js) | 487      | [main->renderer] | NewWindow                            |
| require(workbench.main.js)                              | 1601     | [renderer]       | cached data: YES                     |
| require & init workspace storage                        | 200      | [renderer]       | -                                    |
| init workspace service                                  | 50       | [renderer]       | -                                    |
| register extensions & spawn extension host              | 437      | [renderer]       | -                                    |
| restore viewlet                                         | 29       | [renderer]       | workbench.view.explorer              |
| restore panel                                           | 0        | [renderer]       | -                                    |
| restore editors                                         | 102      | [renderer]       | 1: workbench.runtimeExtensions.input |
| overall workbench load                                  | 263      | [renderer]       | -                                    |
| workbench ready                                         | 3693     | [main->renderer] | -                                    |
| extensions registered                                   | 4167     | [renderer]       | -                                    |

## Extension Activation Stats

| Extension                            | Eager | Load Code | Call Activate | Finish Activate | Event                         |
| ------------------------------------ | ----- | --------- | ------------- | --------------- | ----------------------------- |
| vscode.debug-auto-launch             | true  | 56        | 0             | 8               | *                             |
| vscode.emmet                         | true  | 71        | 2             | 6               | *                             |
| vscode.git                           | true  | 126       | 4             | 60              | *                             |
| vscode.merge-conflict                | true  | 56        | 2             | 3               | *                             |
| vscode.configuration-editing         | false | 80        | 1             | 36              | onLanguage:jsonc              |
| vscode.extension-editing             | false | 225       | 1             | 6               | onLanguage:markdown           |
| vscode.json-language-features        | false | 152       | 34            | 2               | onLanguage:jsonc              |
| vscode.markdown-language-features    | false | 166       | 6             | 0               | onLanguage:markdown           |
| vscode.typescript-language-features  | false | 201       | 2             | 0               | onLanguage:jsonc              |
| ms-azuretools.vscode-azureappservice | false | 939       | 32            | 163             | onView:azureAppService        |
| ms-azuretools.vscode-azurefunctions  | false | 1251      | 37            | 126             | onView:azureFunctionsExplorer |
| ms-azuretools.vscode-azurestorage    | false | 29161     | 92            | 34              | onView:azureStorage           |
| ms-azuretools.vscode-cosmosdb        | false | 34943     | 30            | 4               | onView:cosmosDBExplorer       |
| ms-vscode.azure-account              | false | 777       | 3             | 0               | onView:azureAppService        |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1549928798302	0	0
main:appReady	1549928798370	68	68
willLoadMainBundle	1549928798372	2	70
didLoadMainBundle	1549928798776	404	474
main:willInitGlobalStorage	1549928798891	115	589
main:didInitGlobalStorage	1549928799073	182	771
main:loadWindow	1549928799358	285	1056
renderer/started	1549928799799	441	1497
willShowPartsSplash	1549928799822	23	1520
didShowPartsSplash	1549928799824	2	1522
willLoadWorkbenchMain	1549928799845	21	1543
didLoadWorkbenchMain	1549928801446	1601	3144
main/startup	1549928801446	0	3144
willInitWorkspaceService	1549928801525	79	3223
willInitWorkspaceStorage	1549928801531	6	3229
didInitWorkspaceService	1549928801575	44	3273
didInitWorkspaceStorage	1549928801731	156	3429
willStartWorkbench	1549928801732	1	3430
willRestoreEditors	1549928801844	112	3542
willRestoreViewlet	1549928801844	0	3542
willResolveExplorer	1549928801855	11	3553
LifecyclePhase/Ready	1549928801871	16	3569
didRestoreViewlet	1549928801873	2	3571
didRestoreEditors	1549928801946	73	3644
LifecyclePhase/Restored	1549928801946	0	3644
didStartWorkbench	1549928801995	49	3693
willLoadExtensions	1549928802032	37	3730
didResolveExplorer	1549928802330	298	4028
extensionHostReady	1549928802460	130	4158
didLoadExtensions	1549928802469	9	4167
LifecyclePhase/Eventually	1549928804463	1994	6161
```

**Comment by chrisdias** [comment]
The webpack'd Functions extension just shipped, so now the first startup of the Azure Extension Pack (App Service, Functions, Storage, and Cosmos)is about 1:07 using the stopwatch.  Here's the `Show Running Extensions` info:

![image](https://user-images.githubusercontent.com/1487073/52601809-f79d1000-2e14-11e9-89fa-a7e06e635486.png)

if i uninstall Cosmos and Storage, which are not webpack'ed yet, I get down to about < 3 seconds. Here's the `Show Running Extensions` info:

![image](https://user-images.githubusercontent.com/1487073/52601859-2dda8f80-2e15-11e9-89cf-64e8fb75abe8.png)

**Comment by chrisdias** [comment]
@EricJizbaMSFT are there webpack'd versions of storage and cosmos I could try out locally?

**Comment by EricJizbaMSFT** [comment]
Cosmos is already in master. Latest build is here: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2869

@StephenWeatherford just submitted a PR for storage today: https://github.com/Microsoft/vscode-azurestorage/pull/296, but I don't see a passing build from that branch

**Comment by chrisdias** [comment]
thanks @EricJizbaMSFT!  With this webpack'd cosmos extension, the *first* rough stopwatch timing was about 5 sec, probably more like 4.5. Here is the startup perf report for the extensions:

![image](https://user-images.githubusercontent.com/1487073/52602731-8f502d80-2e18-11e9-85b5-f85a21f8840e.png)

When things were warmed up a bit (stopped VS Code, waited, then started again), it was about 1 sec from clicking on the Azure icon to seeing the subscriptions in the tree.

![image](https://user-images.githubusercontent.com/1487073/52602883-32a14280-2e19-11e9-9df0-86f675a4e4ca.png)

**Comment by StephenWeatherford** [comment]
Cosmos performance isn't as good as the others - lots of webpack issues, ending up excluding more modules than I'd like.  I can work on improving that after ship if needed.

The webpack'd storage extension now has a passing build: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3083

**Comment by chrisdias** [comment]
thanks @StephenWeatherford !  with the referenced storage extension, stopwatch timing on windows was < 3sec for the very first load.  here's `F1` > `Show Running Extensions`:

![image](https://user-images.githubusercontent.com/1487073/52660605-e572ae80-2eb4-11e9-83e4-38a2c9aa08ed.png)

So i think it is fair to conclude that webpack'ing the Azure extensions helps considerably. 

Closing.

**Comment by StephenWeatherford** [comment]
That's great, thanks. I'll let you know when Cosmos and storage ship.
