### ISSUE TITLE
share .vscode/launch.json in configurable location

### ISSUE THREAD

**Issue by remkohdev** [Microsoft/vscode#68294]
This relates to https://github.com/Microsoft/vscode/issues/47753, which was closed by saying: "you're not supposed to do it, do as we say"
but i will argue there is a very good reason for wanting to change and edit my own launch.json, which is collaboration. It's good 12-factor app development practice to remove configuration from the sourcecode, but also to share development i want to be able to have a configuration repo and add ide settings there for the development team to share.

**Comment by weinand** [comment]
Please explain why you cannot share configurations like launch.json via your workspace folder and describe in detail how you would use a "configuration repo" to solve these issues. 
And don't forget to cover the other configurations files as well (e.g. task.json, settings.json).
