### ISSUE TITLE
Single Click doesn't expand folder in latest update(v1.31)

### ISSUE THREAD

**Issue by saileshkush95** [Microsoft/vscode#68299]
I just updated my vs code, It's working fine but I'm facing little bit problem.
Before this version when I clicked on drop down menu, folder expand just with single click, but in this version it is not working same as previous. 
![deepinscreenshot_select-area_20190209114722](https://user-images.githubusercontent.com/28560875/52517267-22466780-2c61-11e9-9aed-93ef39e47f95.png)

**Comment by saileshkush95** [comment]
I mean I want to select file or folder just with single click and expand folder after clicking on drop down icon open file on double click , Is there any way to achieve this setting after tweaking settings file.

**Comment by saileshkush95** [comment]
But vs code insider is working fine as before.

**Comment by bpasero** [comment]
Yeah we fixed this and it should arrive in stable soon. But feel free to keep on using insiders.
