### ISSUE TITLE
Lots of spaces when starting in powershell

### ISSUE THREAD

**Issue by Dispersia** [Microsoft/vscode#68297]
- VSCode Version: 1.32.0-insider
- OS Version: Windows_NT x64 10.017763

Steps to Reproduce:
open terminal 

Does this issue occur when all extensions are disabled?: Yes

I see these issues: https://github.com/Microsoft/vscode/issues/57803 and https://github.com/Microsoft/vscode/issues/59893 however both are closed, I tried to disable conpty and it still does it, happens in both regular vscode and insiders. Powershell runs fine if i run it manually

![capture](https://user-images.githubusercontent.com/7254623/52517009-5eda7a80-2bf1-11e9-87f9-8a41f1379d9c.PNG)

**Comment by Dispersia** [comment]
Of course I find an open issue right after I posted :) https://github.com/Microsoft/vscode/issues/68258

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
