### ISSUE TITLE
Unable to view git different, getting error

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#68292]
Issue Type: <b>Bug</b>

Getting error when trying to view Git different, see attached picture of error. Also in the picture I've done a "git status" which show modified files.

I had to close code-insider to get this working again, this has happened to me on a few occasions.

![image](https://user-images.githubusercontent.com/439226/52515015-cb02b180-2be4-11e9-9f7f-5743c29dbbe9.png)

VS Code version: Code - Insiders 1.32.0-insider (709bf352b12de8284683bef94cb5984129bfc776, 2019-02-08T14:50:08.266Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (0.61GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.2
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
java-debug|DSn|0.0.2
EditorConfig|Edi|0.12.8
tslint|eg2|1.0.42
markdown-preview-bitbucket|hbr|1.0.0
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.2.2
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
java|red|0.38.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.1
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you easily reproduce this issue?

**Comment by rajinder-yadav** [comment]
This happens randomly, not sure how to reproduce it.

**Comment by joaomoreno** [comment]
Does it occur with any file? In any workspace?

**Comment by rajinder-yadav** [comment]
Once it happens, all changed files will give this error.

**Comment by joaomoreno** [comment]
> Once it happens

So... it doesn't happen for a while and then it happens? How much is a while?

Does it happen in any workspace, or just this specific one?

**Comment by rajinder-yadav** [comment]
It's happened a few times, not often but enough times to warrant logging a bug. 

I am not sure what causes it to happen, in terms of operations.

**Comment by rajinder-yadav** [comment]
Frequency is low.

**Comment by joaomoreno** [comment]
Does it happen in any workspace, or just this specific one?

**Comment by rajinder-yadav** [comment]
That I don't know.

**Comment by joaomoreno** [comment]
Please test.

**Comment by rajinder-yadav** [comment]
This is the lamest bug support ever.
