### ISSUE TITLE
autoReveal bug

### ISSUE THREAD

**Issue by chimit** [Microsoft/vscode#68298]
- VSCode Version: 1.31.0 (1.31.0)
- OS Version: macOS Mojave 10.14.2 (18C54)

Steps to Reproduce:

1. Open any project
2. Choose any file in the Navigator
3. Click anywhere in the Navigator, choose another folder in the Navigatior or put a focus to the code

Does this issue occur when all extensions are disabled?: Yes

When `explorer.autoReveal` is false the current active file is not highlighted in the Navigator which makes keeping track on a file very hard:

![autoreveal_off](https://user-images.githubusercontent.com/839349/52516908-bfa79880-2c6d-11e9-8528-1498186a8146.gif)

But when `explorer.autoReveal` is true the behaviour is still very strange and illogical. As you see on the video below when you choose different files by clicking on tabs **for a few iterations nothing changes** in the Navigator. After that the second file becomes highlighted in the Navigator, but the first one **doesn't lose the highlighting**. So we get two highlighted files at the same time which is very confusing:

![autoreveal_on](https://user-images.githubusercontent.com/839349/52516912-cd5d1e00-2c6d-11e9-8861-2e1d3d8d5dd1.gif)

Compare with the Atom:

![atom](https://user-images.githubusercontent.com/839349/52517008-12ce1b00-2c6f-11e9-9b45-4236c302cd9f.gif)

Moreover the Atom filetree behavior is much more correct in general. It doesn't have additional options like `explorer.autoReveal`, but is still more intuitive. For example, if you select a file in tabs the whole tree doesn't toggle folders and jump to the file, but the file is still highlighted if you manually scroll to it:

![atom2](https://user-images.githubusercontent.com/839349/52517114-f8953c80-2c70-11e9-85c7-ae4f0e4ae390.gif)

Very simple and intuitive behaviour. Hope VS Code will pick up this example of good UX.

**Comment by bpasero** [comment]
@isidorn duplicate/related: https://github.com/Microsoft/vscode/issues/67970
