### ISSUE TITLE
Lost my work on unix mount 

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#6830]
I have a mounted remote drive with sshfs.
I edit files from this drive with vscode.

At some moment the mount disconnected and then connected again.
When it was disconnected I tried to access one of my remote files in "vscode working files".

Unfortunately I do not remember exact sequence and I cannot repro. 
The fact is that after the mount restored, vscode showed me a version of the remote file that was older than version that I saved. I edited this old version and saved it. So I lost about one hour of my work. 

I know for sure that I saved newer version, because after saving I run tests on my remote box. I remember running tests on the newer version that was restored.

If you, guys, can find out how could it happen and fix, my trust to vscode will restore and I will continue using it.

I will be happy to give you as much details as you need, share my screen with you, and do tests for you.
Thank you!

**Comment by bpasero** [comment]
@pcherkasova sorry to hear that. first thing to try out is if you are able to reproduce this with some reliable steps. 

Next time it would also be interesting if the file contents on disk are really the same version as remote. In the end VS Code will always try to fetch the contents from disk if it sees that the modification time is different. Could it be that the modification time did not change for some reason?

**Comment by pcherkasova** [comment]
Benjamin,

Thank you for your answer. I will watch for it and if i find a way to repro i will let you know.
I will also check modification time.

Sent from Outlook Mobile<https://aka.ms/qtex0l>

_____________________________

**Comment by bpasero** [comment]
Ok, meanwhile I am closing this.

**Comment by pcherkasova** [comment]
Benjamin,

I lost another hour of my work and got little more details how it happened:

1. I made updates to a remote file
2. I saved the updates and I saw that the black dot near the file name disappeared
3. I lost connection to the remote mount
4. I recovered connection
5. The file in the section 'Working Files' started having the black dot and showing old version
6. I saved the file and override my changes.

I hope this will help you to fix this.
Thank you.

Polina

________________________________

**Comment by bpasero** [comment]
Sorry to hear that, thanks for the steps.

**Comment by bpasero** [comment]
@pcherkasova could you give our insider build a try to see if the situation improved? we did quite some changes in there including a major update of the fs library:

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by pcherkasova** [comment]
Benjamin,


Thank you for working on this. I downloaded new version with link you provided. Unfortunately, the bug is still here.

This is video recording for the test: https://www.dropbox.com/s/d2pj7whbua3a2l9/vscode%20bug%206830.mov?dl=0


This is my vscode version:

[cid:dd1e7110-7709-4c7b-a5ff-689d1e0f0a33]

[https://cf.dropboxstatic.com/static/images/icons128/page_white_film.png]<https://www.dropbox.com/s/d2pj7whbua3a2l9/vscode%20bug%206830.mov?dl=0>

vscode bug 6830.mov<https://www.dropbox.com/s/d2pj7whbua3a2l9/vscode%20bug%206830.mov?dl=0>
www.dropbox.com
Shared with Dropbox






________________________________

**Comment by pcherkasova** [comment]
Benjamin,


Could you, please, confirm, you received this and can see the video?

Thanks.


Polina.


________________________________

**Comment by bpasero** [comment]
@pcherkasova yes I did, thanks for giving it another try.

**Comment by bpasero** [comment]
@pcherkasova is this still happening with our latest insider build? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
