### ISSUE TITLE
VSCode unable to find Node under NVM

### ISSUE THREAD

**Issue by nosuchip** [Microsoft/vscode#68305]
Report Issue to prefill these. -->
- VSCode Version:  1.30.2
- OS Version:  Linux x64 4.19.16-1-MANJARO
- Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
- Date: 2019-01-08T23:10:56.746Z
- Electron: 2.0.16
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41

Steps to Reproduce:

1. Open VSCode using launcher
2. Open empty folder and create file test.js
3. Add Node launcher:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/test.js"
    }
  ]
}
```
4. Start app

**Expected**: program running
**Actualt**: alert box "Cannot find runtime 'node' on PATH. Is 'node' installed?"

Does this issue occur when all extensions are disabled?: Yes

In integrated terminal `node` works:
```
[alp@mobby test]$ which node
/home/alp/.nvm/versions/node/v8.11.3/bin/node
[alp@mobby test]$ echo $PATH
/home/alp/.nvm/versions/node/v8.11.3/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[alp@mobby test]$ nvm alias
default -> node (-> v8.11.3)
node -> stable (-> v8.11.3) (default)
stable -> 8.11 (-> v8.11.3) (default)
```
VSCode's PATH does not contains path inserted by `nvm.sh` (as shown by dev tools):
```
> process.env.PATH
"/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
```

If VSCode started from terminal where nvm already populated PATH with current node path it works and finds everything.

Actually VSCode started from UI launcher unable to find and "globally" installed packages (saying "globally" I mean "globally for user because it works under NVM).

**Comment by weinand** [comment]
@Tyriar what needs to be done on linux that a VSCode started from "UI launcher" finds "globally" installed packages. What shell profile is available for applications started from the "UI launcher"?

Your "integrated terminal" seems to read the correct shell profile but the "UI launcher" does not.

**Comment by Tyriar** [comment]
@weinand when run through the launcher a login shell is run which generates the window's environment:

https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/shellEnv.ts#L24

This should run `~/.bashrc` (or `~/.zshrc` if `$SHELL=/bin/zsh`).

Alternatively nvm could be setup in `~/.bash_profile` which runs when the user logs into Linux.

@nosuchip can you share your settings.json file, what `$SHELL` is set to and where exactly nvm's init script is being run?

**Comment by nosuchip** [comment]
@Tyriar here it is:
- `settings.json`: https://pastebin.com/hkp7D1Gp
- `$SHELL` is `/bin/bash`
- nvm script called at the end of `~/.bashrc`

**Comment by weinand** [comment]
One problem could be that NVM not only relies on env vars but uses bash functions as well.
So the result of https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/shellEnv.ts#L24 is just a set of env variables that is passed along. This misses any functions defined by NVM.

**Comment by nosuchip** [comment]
@weinand I just tried to fix `process.env.PATH` manually. As expected VSCode from that moment could find Node executable.

**Comment by nosuchip** [comment]
Some additional info that could be useful and probably affects initial issue.
- distro: Linux Manjaro x64 (Arch based)
- VS Code package: *unonfficial open source build* [`community/code`](https://www.archlinux.org/packages/community/x86_64/code/)

I cannot check now whether [official binary distribution](https://aur.archlinux.org/packages/visual-studio-code-bin/) suffers from the same issue but it could be a clue.

Actually for me specifying argument [runtimeVersion](https://code.visualstudio.com/updates/v1_21#_node-debugging) in `launch.json` with `nvm` installed did the trick.

**Comment by Tyriar** [comment]
Yeah aliases and the like won't get carried over, looks like you worked around it with runtimeVersion though 👍
