### ISSUE TITLE
Issue while debugging

### ISSUE THREAD

**Issue by gtzinos** [microsoft/vscode#68308]
![screenshot from 2019-02-09 13-33-12](https://user-images.githubusercontent.com/11459192/52520184-6d677700-2c6f-11e9-9dd7-0ea425992a93.png)

Sometimes it stops in a removed breakpoint and even if I will restart the process or not, I can't stop this situation.

APP: NodeJS
vscode-insiders (last)
os: ubuntu 16.04

**Comment by weinand** [comment]
Your report does not contain enough information for reproducing the problem.

- What kind of program are you debugging?
- Do you have a small reproducible case that you can share with us?
- Provide a screenshot with the CALLSTACK view when this happens (the header of the CALLSTACK shown the reason for the stop)

**Comment by gtzinos** [comment]
Hi @weinand 

- NodeJS 6.11
- I don't think that the problem is related with our code, I have this issue in random times, in general when I add and remove breakpoints during the debugging.
- I will debug multiple times until I will reproduce it again and I will reply you with the screenshot of the callstack window.


It makes me believe that if I will remove the breakpoint at the same time cursor is going to be there, then it will have this issue.

**Comment by gtzinos** [comment]
![screenshot from 2019-02-11 10-24-06](https://user-images.githubusercontent.com/11459192/52551953-3ae08a00-2de7-11e9-9895-d8e7fbb45300.png)
![screenshot from 2019-02-11 10-23-58](https://user-images.githubusercontent.com/11459192/52551956-3f0ca780-2de7-11e9-8bf1-3af6b5088b4e.png)

**Comment by weinand** [comment]
@gtzinos so you are saying that there is no "reason" showing up in the top right corner?
![2019-02-11_09-49-37](https://user-images.githubusercontent.com/1898161/52553020-893f5a00-2de2-11e9-82e2-c44c70a2fbf4.png)

You are using an extremely old version of node.js (6.11). Could you upgrade to a version >= 8.0 (or at least >= 6.3) and try again?

(Please note if you use node.js >= 6.3 and < 8.0 you will have to add a `"protocol": "legacy"` to the launch config.

**Comment by gtzinos** [comment]
Yes, I can upgrade to 7.11. Is it enough to be fixed?

**Comment by gtzinos** [comment]
Yes, I can upgrade to 7.10.1. Is it enough to be fixed?

**Comment by gtzinos** [comment]
Yes, I can upgrade to 7.10.1 and I updated the protocol in launch.json. Is it enough to be fixed?

**Comment by weinand** [comment]
In my previous comment I made mistake: instead of "legacy" you should specify "inspector" in your launch config. 
Without that you will probably see the same problem as with NodeJS 6.11.

**Comment by gtzinos** [comment]
Thank you! I will debug to test if it works as expected now!

**Comment by weinand** [comment]
Please open a new issue if you still see this problem.
