### ISSUE TITLE
Common settings are missing .v1.31.0 (win10)

### ISSUE THREAD

**Issue by 3038922** [Microsoft/vscode#68301]
![image](https://user-images.githubusercontent.com/33926386/52517473-bff86180-2c76-11e9-83f3-0d565e55610e.png)
His previous version has a common setting on the left. It's not available now. This version only has `settings. json'.
![image](https://user-images.githubusercontent.com/33926386/52517479-cd155080-2c76-11e9-90ec-e140831c9bc2.png)

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_31#_use-simple-text-editor-for-editing-settings-as-json

**Comment by 3038922** [comment]
"workbench.settings.useSplitJSON": true,
thank you!
