### ISSUE TITLE
Document for internal command

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#68314]
Issue Type: <b>Feature Request</b>

somethings we need apply internal command (eg. `git.commit`/`git.push`) in VS Code extension.

there is problem: **I don't known what argument it need**

and I have to search the source code and find it out.

I am thinking: **Can it automatically generate documentation for extensions those registed commands?**

If this can be achieved, it will be great for developer.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

**Comment by kieferrm** [comment]
If commands are internal then we don't want anyone to use those. So, we won't document them. However, the git extension recently started exposing API and that needs documentation.

**Comment by axetroy** [comment]
I found this to be impossible to achieve.

Just write the `d.ts` file for the interface that needs to be exposed.
