### ISSUE TITLE
Allow to launch terminal window without file extension.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6831]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Make sure you are working with multiple monitor.
2. Launch VSCode and update setting in settings.json to powershell terminal without extension "exe".
![image](https://cloud.githubusercontent.com/assets/17735796/15515260/1c7b7be6-21a2-11e6-81a0-915c406082f2.png)
3. Launch terminal window by pressing CTRL+` and verify app behavior.

Actual: Terminal window launched but user can't perform any action. Mouse pointer is keep blinking and showing loading icon all the time. when hover over on terminal window.
Note: I observed this with powershell only for native command prompt cmd and cmd.exe both working properly.
![image](https://cloud.githubusercontent.com/assets/17735796/15516088/0457208e-21a6-11e6-8ac9-7e621fefb8a0.png)

**Comment by Tyriar** [comment]
I'm assuming you need the .exe because the smarts to check for .bat, .cmd, .exe, etc. are built into `cmd`, not Windows. I'd prefer not to work around this on our side.

The blinking/locking up thing is fixed now https://github.com/Microsoft/vscode/issues/6683

**Comment by v-pavanp** [comment]
I brought this up because ExternalTerminal is working without file extension. Basically if you see all these terminals are part of environment variables, so I think it should work with IntegratedTerminal as well without providing file extension (i.e. .exe for windows).

**Comment by Tyriar** [comment]
The reason for this is because it's launched from the cmd process `process.env['comspec'] || 'cmd.exe'` (full shell path or cmd.exe) with args `['/c', 'start', '/wait', '""', exec]`. I don't think it's possible to do this for the integrated terminal unfortunately.
