### ISSUE TITLE
New workbench treeview fail to update properly

### ISSUE THREAD

**Issue by koliyo** [Microsoft/vscode#68316]
The new workbench treeview in January 2019 update fails to synchronize state properly when moving/changing file structure from command line

- VSCode Version: 1.31.0 (1.31.0)
- OS Version: Mac OS Mojave

Steps to Reproduce:

1. Make modifications to workspace file structure from command line. Eg moving a file from one directory to another
2. Observe the outdated state in the workbench tree view

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
@koliyo can you run with --verbose to and check the logs if the file events are recorded at least?

**Comment by koliyo** [comment]
It is very reproducable when moving files

```
touch MyTask/foo
```

tree view is updated

```
mv MyTask/foo .
```

Now the `foo` file is both visible in the root directory and in the previous `MyTask` subdirectory.

In the console I see that there is a delete event for `MyTask/foo` but it is still there in the treeview.
```
console.ts:134 [IPC Library: File Watcher (chokidar)] [ADDED] /Users/silok/Work/brick/MyTask/foo
console.ts:134 [IPC Library: File Watcher (chokidar)]  >> normalized  [ADDED] /Users/silok/Work/brick/MyTask/foo
console.ts:134 [IPC Library: File Watcher (chokidar)] [DELETED] /Users/silok/Work/brick/MyTask/foo
console.ts:134 [IPC Library: File Watcher (chokidar)] [ADDED] /Users/silok/Work/brick/foo
console.ts:134 [IPC Library: File Watcher (chokidar)]  >> normalized  [DELETED] /Users/silok/Work/brick/MyTask/foo
console.ts:134 [IPC Library: File Watcher (chokidar)]  >> normalized  [ADDED] /Users/silok/Work/brick/foo
```

If I manually push the refresh button in the treeview it synchronizes properly.

Sidenote: What is the purpose of the refresh-button? The state should always be synchronized automatically? Is it just a fallback for failing synchronization?

**Comment by jtsom** [comment]
I've noticed this if you do a 'git pull' and new files are added to a project. They won't be in the file tree view until I click the Refresh button.

Even dragging files from one folder to another in tree view will sometimes not update.

**Comment by fwcd** [comment]
For reference, this does not only occur when files are changed from the command line. I have remapped `Ctrl + N` to `explorer.newFile` (since it is a lot more convenient to be able to create files directly in the explorer) and the explorer does not update properly after creating a file. The bug seems to have been introduced in the latest major release (1.13 - January 2019).

**Comment by mk-pmb** [comment]
Mine seems a bit moody about when it does or doesn't pick up new files created by "Save as".

```text
$ code --version
1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64

$ lsb_release -dc
Description:    Ubuntu 16.04.5 LTS
Codename:       xenial
```

**Comment by isidorn** [comment]
I can not reproduce any of this following your exect steps. I am on macOS
Can anyone reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
If someone can reproduce with insiders please let me know and we can investigate further
@bpasero did you see something like this?

**Comment by bpasero** [comment]
@isidorn yes reproduces for me:

![image](https://user-images.githubusercontent.com/900690/53349020-7bc6bb80-391c-11e9-88d1-cdae00a24380.png)

**Comment by i2chris** [comment]
I have the same issue for files created within vscose using the treeview.  Also, copying and pasting a file into the same folder using vscode doesn't work at all.  The file is not copied.

**Comment by isidorn** [comment]
@bpasero great steps, thanks a lot!
Everyone please try out vscode from Wednesday and if you hit issues please let me know with exact reproducable steps. Thanks!
