### ISSUE TITLE
View > Show explorer doesn't focus the current file, anymore

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#68318]
View > Show explorer (`workbench.view.explorer`, bound to <kbd>Ctrl + shift + E</kbd>) used to focus the current file in the explorer. It doesn't work this way, anymore.

Is this a bug? Is their a workaround?

**Comment by bpasero** [comment]
@dorian-marchal can you explain what you see if you try?

**Comment by dorian-marchal** [comment]
I reloaded VSCode and it seems to work fine, for now: the explorer automatically focuses the current file. It was not the case before I reload.

I'm trying to reproduce the steps that lead to this weird behavior.

**Comment by paustint** [comment]
@dorian-marchal - is this other issue the same thing happening to you? https://github.com/Microsoft/vscode/issues/67970#issuecomment-463072726

Since 1.31 - I have not been able to confirm if the random and inconsistent explorer focus is a bug or if it is some intended feature.

**Comment by dorian-marchal** [comment]
Yes, it looks like this is what happened to me.

https://github.com/Microsoft/vscode/issues/67970#issue-407186087
> Now I can be in two states:
>
> * either **I get the currently active file not as selected**
> * or I see the folder and the file as being selected which imho is not very useful

I close this issue as it's a duplicate. :+1:
