### ISSUE TITLE
Open vscode with windows run opens a terminal

### ISSUE THREAD

**Issue by atabaksahraei** [microsoft/vscode#68319]
Issue Type: <b>Bug</b>

if you open vscode from Run ("windows + R") there is always a cmd windows in background. can you probably fix thah?

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (10.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|5.21.0
python|ms-|2019.1.0
latex-snippets|sab|0.0.8

</details>

**Comment by bpasero** [comment]
@atabaksahraei what do you type into the run box?

**Comment by atabaksahraei** [comment]
i typed “code”

**Comment by bpasero** [comment]
I see the same. I do not think we can control that though. Maybe @joaomoreno has a clue.

**Comment by the-ress** [comment]
duplicate: #33256, #66750

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/66750
