### ISSUE TITLE
jsx syntax highlighting for fenced code block doesn't always work

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#68310]
Issue Type: <b>Bug</b>

jsx syntax highlighting for fenced code block doesn't always work

Markdown
<pre>
```jsx
const element = &lt;h1&gt;Hello, world!&lt;/h1&gt;;
```

```jsx
&lt;input name=&quot;name&quot; placeholder={fbt('name', 'name field')} /&gt;
```
</pre>

![image](https://user-images.githubusercontent.com/2301847/52521368-75a1c100-2c33-11e9-8771-a659c9038fd2.png)

![image](https://user-images.githubusercontent.com/2301847/52521323-c95fda80-2c32-11e9-91c7-a51dbc7319de.png)

VS Code version: Code - Insiders 1.31.0-insider (b313db6c58f8c02181a33cd3b5b4b17c64a5b85d, 2019-02-05T10:10:06.179Z)
OS version: Darwin x64 18.2.0

**Comment by mjbvz** [comment]
This is an upstream issue with highlight.js which we use to power the built-in markdown preview's highlighting

Please file this issue upstream: https://github.com/highlightjs/highlight.js/issues

**Comment by mjbvz** [comment]
Also, there's now this extension https://marketplace.visualstudio.com/items?itemName=bierner.markdown-prism that providers uses prism  for highlighting instead
