### ISSUE TITLE
Custom tree view: `Collapse` should be named `Collapse All`

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#68315]
Issue Type: <b>Bug</b>

Using extension code:
```typescript
vscode.window.createTreeView(`${EXTENSION_NAME}.tree`, {
	treeDataProvider: provider,
	showCollapseAll: true,
});
```
Button title is showing `Collapse`.

![screenshot 53](https://user-images.githubusercontent.com/9638156/52522235-78340300-2c93-11e9-981a-865dbdcc7389.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
I'm still seeing this using the vscode tree view sample extension:

![screen shot 2019-02-25 at 2 54 00 pm](https://user-images.githubusercontent.com/12821956/53374450-35b62b80-390d-11e9-9603-2a214ba14f24.png)
