### ISSUE TITLE
Blurry icons (zoom on click)

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#68311]
Issue Type: <b>Bug</b>

![blurry](https://user-images.githubusercontent.com/9638156/52522059-841ec580-2c91-11e9-9880-bf4d81dd6ca9.gif)

They are svg and easily could be rendered in max workbench zoom with sharp edges. But zoom on clicking is using something that makes them extremely blurry. Not a regression.

Maybe related #8017.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
@misolori yeah this is an area where I would think we should also look at when changing icons.

**Comment by misolori** [comment]
This should be fixed once we switch over to an icon font, we're not complete yet and it depends on https://github.com/microsoft/vscode/issues/78889. Here's what it looks like in the areas that's using an icon font:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/35271042/66419057-38efba80-e9b8-11e9-84bc-50656fd7b017.png">

**Comment by usernamehw** [comment]
I don't actually think this issue is worth of any effort.
