### ISSUE TITLE
explorer.sortOrder: "filesFirst" option doesn't work when opening projects

### ISSUE THREAD

**Issue by karamfd** [Microsoft/vscode#68323]
- VSCode Version: 1.31
- OS Version: Mac OS Mojave 14.3

Steps to Reproduce:

1. Open new project in vscode
2. Reload window when disabling or installing a new extension

Does this issue occur when all extensions are disabled?: Yes/No  Yes

"explorer.sortOrder": "filesFirst" option does not work properly at the moment.

Default option is chosen when a new project is opened or when the window is reloaded. I always have to disable this setting and re-enable it, which is pretty annoying as you can imagine.

**Comment by rav2040** [comment]
I have the same issue. Until it's fixed, just clicking on "Refresh Explorer" at the top of the Explorer panel is enough to show the correct order. No need to disable and re-enable the setting.

**Comment by karamfd** [comment]
> I have the same issue. Until it's fixed, just clicking on "Refresh Explorer" at the top of the Explorer panel is enough to show the correct order. No need to disable and re-enable the setting.

That makes a lot of sense. Thank you very much 👍
