### ISSUE TITLE
Go To Next Problem scope/popup doesn't fit editor screen

### ISSUE THREAD

**Issue by hinell** [Microsoft/vscode#68328]
![screenshot_1](https://user-images.githubusercontent.com/8136158/52525515-f99f8b80-2cbb-11e9-8979-1214f8b8a225.jpg)

### In short 
* **Next problem scope/popup (red box)** doesn't fit code editor screen rendering the problem description unreadable even using large screens: sidebar or edge of the editor just overlap the problem popup
* Please make it wrap-able, otherwise it forces to check terminal constantly or use hover over error instead
* It's unrelated to the #49843 issue cause it reports on the "height" restriction

### Steps to Reproduce:

1. Make a mistake with long error description (using typescript for instance)
1.1. `$ npm i @types/opn opn`
1.2. `echo 'import * as opn from "opn"' > index.tsx`
2. Use `Go to next Problem` (usually `F8` keystroke)

Does this issue occur when all extensions are disabled?: **Yes**

<details>
<summary>System and App Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.30GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
Version | 1.31.0 (system setup)
Commit | 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date| 2019-02-05T22|35|56.624Z
Electron| 3.1.2
Chrome| 66.0.3359.181
Node.js| 10.2.0
V8| 6.6.346.32
OS| Windows_NT x64 10.0.17134 (Windows 10 Pro x64)

</details>

**Comment by sandy081** [comment]
@hinell You can scroll it horizontally to see the complete error. May I know if you can scroll or not?

**Comment by hinell** [comment]
@sandy081 
Yeah I can, by using `shift+scroll`
Though it would be better to wrap it rather then using keystrokes but I think I can close the issue safely.
Thanks.
