### ISSUE TITLE
WorkspaceFolder Uri.fsPath drive letter normalization to lowercase on Windows causing extension issues

### ISSUE THREAD

**Issue by enlyth** [Microsoft/vscode#68325]
I'll give an example where this behaviour creates issues, which I think is fairly common, e.g. spawning Jest by running a command like `npm test` via process.spawn, like the `vscode-jest` extension does, while using a transformer like `babel-jest`.

The extension gets its path via `vscode.workspace`, and WorkspaceFolder.Uri.fsPath is normalized to a lower-case drive letter.

The following code demonstrates this issue:
```js
const childProcess = require("child_process");

// Uppercase drive letter, tests will run fine
const cwd = "C:\\src2\\myproj";

// Lowercase drive letter, this will FAIL, unable to resolve modules when running
// const cwd = "c:\\src2\\myproj"; 

const proc = childProcess.spawn(
  "npm",
  [
    "test",
    "--",
    "--json",
    "--useStderr",
    "--outputFile",
    "C:\\Users\\BORIS~1.POP\\AppData\\Local\\Temp/jest_runner.json",
    "--watch",
  ],
  { cwd: cwd, shell: true, env: process.env }
);
```
fsPath returning an uppercase drive letter on Windows seems to have been already suggested here:
https://github.com/Microsoft/vscode/issues/42159#issuecomment-360533151

- VSCode Version: 1.32.0-insider
- OS Version: Windows 10 Build 17134

Steps to Reproduce:

1. Set up any project which uses babel-jest, and Jest
2. Run code above from command line

Does this issue occur when all extensions are disabled?: Irrelevant

**Comment by jrieken** [comment]
This is the designed and something we cannot change anymore. It's is explicitly [spelled](https://github.com/Microsoft/vscode/blob/c110d84460b3e45842a8fe753562341003595e1d/src/vs/vscode.d.ts#L1304) out in the docs. 

If your downlevel code depends on the casing of the windows drive letter (which IMO is questionable) you should enforce the case yourself.
