### ISSUE TITLE
Debugging is *painfully* slow when using readline.on

### ISSUE THREAD

**Issue by bkbonner** [Microsoft/vscode#6832]
- VSCode Version:  1.1.1
- OS Version:  OSX  10.11.2 (15C50)
- Using Nodejs 5.4.1 or 6.2.0

Steps to Reproduce:

`
const fs = require('fs');
const readline = require('readline');

const rl = readline.createInterface({
    input: fs.createReadStream('accounts')
});

rl.on('line', (account) => {
    console.log('checking account: ', account);
});
`

accounts file has a list of strings:
00133883
00281479
00287363
00289717
00290434
00290769
00297306
00297392
00332887
00371563
00513623
00513625
00513629
00514177
01012914
01023036
01027778
01029492
01086616
01117383
01117461
01117527
01117587
01125284
01152315
1. Set a breakpoint on the console.log inside rl.on....and debugger never reaches this line.

VS Code shows the error:  Request 'continue' was cancelled because Node.js is unresponsive.
1. if you limit the file to just 3 lines, it does reach the line, but stepping through the code is painfully slow.

**Comment by bkbonner** [comment]
From the description of the release notes, this appears like it will take care of the issue.  I will test it later today.

**Comment by weinand** [comment]
@bkbonner I could still see the slowness sporadically, which indicates that our workaround not always works. In your case the debugger inside node.js sends a 3 MB json object (most likely a Buffer) over the wire as part of the callstack. This slows down stepping considerably.

**Comment by serraventura** [comment]
I have some ETL APPs done in Node which needs to handle huge amount of data. Every time I try to debug with Visual Studio Code I got "unresponsive" errors. It seems that the editor does not work very well on debug mode.

I'm back to "console.log", so painful :(

![unresponsive](https://cloud.githubusercontent.com/assets/2728093/16686675/a64e8a66-450b-11e6-990d-976b3efd6a3c.png)
![unresponsive2](https://cloud.githubusercontent.com/assets/2728093/16686674/a64b44c8-450b-11e6-958e-fb6d22bf2b2f.png)

**Comment by weinand** [comment]
@serraventura was node version are you using?
One part of the problem is that node's debugging protocol does not handle large data structures well. It always sends the whole data structure over the wire.
This will improve with node 7.x.

**Comment by weinand** [comment]
Please try this on node.js >= 6.5 and use the 'inspector' protocol by adding `"protocol": "inspector"`to your launch config. You should see any slowness.

**Comment by bkbonner** [comment]
Ok, I'll schedule to give this a try.  Thanks!

**Comment by bkbonner** [comment]
and you meant, "You should NOT see any slowness", right?

**Comment by weinand** [comment]
@bkbonner correct!
