### ISSUE TITLE
New grid: hiding editor should propagate visibility change to editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#68320]
Since this is a new feature from the grid, we properly need to hook in visibility changes to the active editor. E.g. via [`EditorControl.onHide()`](https://github.com/Microsoft/vscode/blob/7c1fe9a/src/vs/editor/common/editorCommon.ts#L278)

**Comment by sbatten** [comment]
The editor has a handler for this change at https://github.com/Microsoft/vscode/blob/a70abbbfb107b45d105776d7a2282a60c5eacc0d/src/vs/workbench/browser/parts/editor/editorPart.ts#L994

**Comment by bpasero** [comment]
Ok, adding verification label for me to check this 👍

**Comment by bpasero** [comment]
This is not fixed. Trying on Linux to hide editor, I see no call to [`baseEditor#setVisible()`](https://github.com/Microsoft/vscode/blob/2447892/src/vs/workbench/browser/parts/editor/baseEditor.ts#L120).

I would think there is code changes needed because so far we never supported to hide the editor area. I can review a PR for this change.

**Comment by sbatten** [comment]
@bpasero The handler I sent you is the only one triggered by the grid. What the editor part does with that event, I do not know what or where you would like to propagate this which is why I shared the pointer.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/d3066ce7c50cc034f200efc4c7a29227d11794ed
