### ISSUE TITLE
Markdown outline displays incorrect ordering

### ISSUE THREAD

**Issue by zachvalenta** [Microsoft/vscode#68338]
**Versions**

- VSCode Version: 1.31.0
- OS Version: macOS 10.14.3

---

**Steps to Reproduce**:

first header (located on line 1) is displayed as second header in Markdown outline

![screen shot 2019-02-09 at 7 27 34 pm](https://user-images.githubusercontent.com/11388735/52528058-d7007900-2ca1-11e9-9818-ed85bfedc1c7.png)

This is the only Markdown file I have in which this happens. I checked the file to see if an incorrectly nested header could be the culprit (i.e. `## bar` inside `### foo`) but don't see any.

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by zachvalenta** [comment]
I just checked the above-mentioned issue #53992, this is an issue of display styling vs. the problem I noticed, which is incorrect ordering.

**Comment by mjbvz** [comment]
Try changing the sort order to `by position` using the `...` button of the outline view header:

<img width="200" alt="screen shot 2019-02-11 at 8 25 49 am" src="https://user-images.githubusercontent.com/12821956/52577324-b2f28400-2dd6-11e9-88c2-d65dc5e47a11.png">

**Comment by zachvalenta** [comment]
@mjbvz cheers! newb issue from a newb user 🙂
