### ISSUE TITLE
I am unable to add extensions to my VS Code editor.

### ISSUE THREAD

**Issue by shivam-kapila** [Microsoft/vscode#68331]
My VS Code editor is unable to connect to the marketplace. Please help. I need to install some extensions.

**Comment by kieferrm** [comment]
The marketplace is up and I just tried that my client can connect to it. In case you are behind a proxy, here is the doc how access the marketplace: https://code.visualstudio.com/docs/setup/network

**Comment by shivam-kapila** [comment]
The problem was solved when I installed VS Code from Ubuntu Software Center. If I download .deb file and extract it then that VS Code editor does not connect to marketplace

**Comment by sandy081** [comment]
@shivam-kapila Did you try again with the installation from .deb file, it could be that Marketplace was down then. If you see it again, can you please open the console using the command Toggle Developer Tools and let us know if there are any errors there.

**Comment by shivam-kapila** [comment]
Ok sure. I will check

**Comment by sandy081** [comment]
ok
