### ISSUE TITLE
New file/folder inputs don't disappear if they out of viewport

### ISSUE THREAD

**Issue by Sominemo** [Microsoft/vscode#68339]
Issue Type: **Bug**
- VSCode Version: 1.31.0
- OS Version: Windows 10 1903 (18329.1)

Steps to Reproduce:

1. Get a long project tree that doesn't fit in screen and has a scrollbar with multiple folders
2. Enter a file or folder creation mode by clicking the corresponding icon on project tree toolbar
3. Scroll the files tree with mouse wheel so the input for new file hides from viewport (doesn't work with scrollbar)
4. Project tree stays darken-out, click another one folder
5. Click create new file/folder icon again (doesn't matter which one you chosen before)
6. Second input appears, in that time previous one stays. Can be repeated few times
7. As soon as both of inputs get in viewport at the same time they disappear

Does this issue occur when all extensions are disabled?: Yes

![2019-02-10_03-15-19](https://user-images.githubusercontent.com/19842935/52528236-29618a00-2ce2-11e9-972a-6b45307c0ddc.gif)

**Comment by isidorn** [comment]
@Sominemo good catch.
@joaomoreno we introduced this regression via https://github.com/Microsoft/vscode/commit/6d6082a2b9b52b8286d15345784d0a671f53ed40
That commit was pushed so we fix when a user New Files on an collapsed folder (previously the blur event would come and destroy the input box).

@joaomoreno However as this issue demonstrates some blur events shuold not be ignored [here](https://github.com/Microsoft/vscode/blob/c764deb22f68d3c6b4bbe006bc66a2140be5b724/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L236) and am not sure how to fix this. Any ideas?

**Comment by isidorn** [comment]
Fixed but caused #69468 which we can investiate tomorrow
@Sominemo thanks for filling this
