### ISSUE TITLE
open URL with keystroke in the editor

### ISSUE THREAD

**Issue by zachvalenta** [Microsoft/vscode#68333]
The Sublime extension [ClickableURLs](https://github.com/leonid-shevtsov/ClickableUrls_SublimeText) allows one to open a URL with a keystroke. 

> This plugin underlines URLs in Sublime Text, and **lets you open them with a keystroke (Cmd+Option+Enter by default).**

I'd like to see something similar in VS Code.

**Comment by zachvalenta** [comment]
as far as I can tell this issue is not covered by an existing one

**Comment by Tyriar** [comment]
@zachvalenta which URLs are you referring to exactly?

**Comment by zachvalenta** [comment]
URLs in a text or source file

For example, with the Sublime ClickableURLs extension, if the cursor is on any part of a URL, `CMD ALT RETURN` will open the URL in the browser

![subl](https://user-images.githubusercontent.com/11388735/52569803-00272380-2de0-11e9-99f6-93798bfb882d.png)

![browser](https://user-images.githubusercontent.com/11388735/52569811-02897d80-2de0-11e9-8e7f-e3703962f1c6.png)

**Comment by Tyriar** [comment]
Let's track this for URLs in the editor as above. This could also be a feature request for the terminal but the implementation would be much more involved as the cursor cannot be moved freely through the buffer.

**Comment by zachvalenta** [comment]
Exactly, I'm asking only for the editor, not the terminal.

**Comment by rebornix** [comment]
@zachvalenta it's a great idea ;)

**Comment by pelmers** [comment]
Is this not already covered by the 'open link' command? https://github.com/Microsoft/vscode/blob/ebf55c18b8002684212960c5c9807894422f25ce/src/vs/editor/contrib/links/links.ts#L396-L429

**Comment by njkevlani** [comment]
@pelmers Nice catch!!

@zachvalenta This can be achieved by putting following `keybindings.json` :
```json
{
    "key": "ctrl+shift+t",
    "command": "editor.action.openLink"
}
````

You can use keystroke of your choice.

**Comment by zachvalenta** [comment]
awesome! thanks for the help everyone!
