### ISSUE TITLE
Menu disappears/won't appear on Release Notes focus

### ISSUE THREAD

**Issue by 4s7r0** [microsoft/vscode#68335]
I'm using Linux Mint 16.04 and the latest VSCode.

When focus is on Release Notes, the menu disappears and the hotkey does not make it reappear.

I do not know why the menu must disappear or how much programming went into making it (not) work this way, but I would argue that it is better if you could use the menu while reading the release notes.

This has only been tested with regular files already open when the release notes appear.

**Comment by 4s7r0** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Link to new settings from Release Notes (#63301)](https://www.github.com/Microsoft/vscode/issues/63301)

Nope. But it's clear that the release notes were programmed like they were old school easter eggs. Also, instead of a bot looking for dupes, maybe offer a better way for issue submitters to pre-organize their issue better suited to how you handle areas of concern. Try attacking the problem from the other end.

**Comment by sbatten** [comment]
@mjbvz Webviews are eating alt-key press

**Comment by mjbvz** [comment]
This seems to be caused by the menubar `ModifierKeyEmitter` class listening for alt key presses using `domEvent(document.body, 'keydown')`. Our webview implementation has to re-dispatch all keyboard event, but it does so using the keybinding service. This means that the keydown event for alt key presses never triggers `ModifierKeyEmitter`.

@bpasero or @sbatten Any ideas on how we can workaround this?

**Comment by sbatten** [comment]
@mjbvz so only commands with keybindings will be received outside of the webview when one is focused?

**Comment by mjbvz** [comment]
The webview converts key presses into commands. The raw key presses themselves however are captured by the webview. I tried rebroadcasting the key press events using dispatchEvent but it didn’t work properly

**Comment by mjbvz** [comment]
Never mind, 8009f4e  doesn't seem to fix this properly

**Comment by sbatten** [comment]
using mnemonics in webviews works, alt focusing does not. as a workaround use alt+f to get to the menu or focus outside of the webview such as the sidebar or panel.
