### ISSUE TITLE
UI glitches after coming out of suspend mode

### ISSUE THREAD

**Issue by mcrajah** [Microsoft/vscode#68346]
Issue Type: <b>Bug</b>

leave vscode open before going into suspend. Once you come out of suspend, there are numerous boxes in vscode that do not have the correct UI. Resizing, maximizing, minimizing etc does not fix these boxes. You have restart vscode to fix.

Each time the issues are different, for example, sometimes, the sidebar map will be all white or the scroll bars are messed up. Almost always, the terminal window does not show any text except the line with prompt.
![vscode](https://user-images.githubusercontent.com/11020250/52530815-f73f3080-2cbf-11e9-9ae4-2b404a227422.png)

VS Code version: Code - Insiders 1.32.0-insider (709bf352b12de8284683bef94cb5984129bfc776, 2019-02-08T14:50:08.266Z)
OS version: Linux x64 4.20.6-arch1-1-ARCH

Version: 1.32.0-insider
Commit: 709bf352b12de8284683bef94cb5984129bfc776
Date: 2019-02-08T14:50:08.266Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.6-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 1857)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.75GB (2.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.22.0-insiders

</details>

**Comment by Pilzschaf** [comment]
Same here on manjaro. For me primarily the terminal is broken. Opening a new terminal session works for me but it is annoying nevertheless. The terminal doesn't even show the prompt in my case. Only some single characters are sometimes visible. I am using zsh but the problem also happen with bash. The sidebar map actually reappeared on window resize in my case. 
I also wanted to note that the bug is not new, so it is nothing that has been introduced with a patch lately.
![screenshot_20190210_101547](https://user-images.githubusercontent.com/9831266/52531969-e32a1c00-2d1d-11e9-8643-5dd1aeaa0d47.png)

**Comment by felubra** [comment]
@Pilzschaf  please see https://github.com/Microsoft/vscode/issues/43169#issuecomment-460296785

![image](https://user-images.githubusercontent.com/25326257/52544792-3346c400-2d9a-11e9-9ae1-bae819dba1f9.png)

Boxes of subtle colors are appearing randomly across the screen, they appear and disappear according to the scroll position. Some of them over ui elements. I saw this problem on a machine with WIndows 10 and another one with Linux (Fedora 29)

On the Windows machine:

> Version: 1.31.0 (user setup)
> Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
> Date: 2019-02-05T22:35:56.624Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

**Comment by flschaves** [comment]
I'm issuing this as well, I'm using Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/4398231/52587360-fd005780-2e20-11e9-98d0-81ac618b29c3.png)

**Comment by supirman** [comment]
> Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

I have the similar issue for the terminal. Some terminal text if not all becomes invisible after suspend.

![After Suspend](https://user-images.githubusercontent.com/329333/52861765-0d3c6d80-3166-11e9-9697-78b9c490b0eb.png)

I found a workaround for my issue by changing the color scheme.

**Comment by sustained** [comment]
This is happening to me too, on Fedora 29. I'll provide a screenshot shortly.

**Comment by sustained** [comment]
This is happening to me too, on Fedora 29.

Though mine looks rather different to the others.

![screenshot from 2019-02-23 18-27-05](https://user-images.githubusercontent.com/5995080/53290266-3d54c380-3799-11e9-8764-1240e0177b2a.png)

**Comment by NeMO84** [comment]
Encountering the same issue as described by many here.

System:
```
Ubuntu 18.04.2
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic
```

**Comment by Tyriar** [comment]
I didn't expect issues related to the minimap to pop up, but it makes sense that the terminal is still seeing this issue. We need to clear the texture cache when a resume happens and redraw everything, right now just a redraw is happening using corrupted textures.
