### ISSUE TITLE
False warning message (typescript + workspace + decorators)

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#68349]
- VSCode Version: 1.31.0
- OS Version: WIndows 10

Steps to Reproduce:

1.  Create workspace with two projects (A + B)
    * Project B is using experimental decorators
    * Both projects have the same tsconfig settings (except the references section, where Project A references Project B):
    * `tsc --build` in Project A emits 0 errors
```
{
    "extends": "../tsconfig.settings.json",
    "compilerOptions": {
        "rootDir": "./src",
        "outDir": "./lib-umd",
        "declarationDir": "./types"
    },
    "include": [
        "./src/**/*"
    ],
    "references": [
...  (Project A reference Project B)
   ]
}

//  tsconfig.settings.json
//  Shared by Project A and Project B
{
    "compilerOptions": {
        "composite": true,
        "target": "es5",
        "module": "umd",
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "declarationMap": true,
        "noImplicitAny": false,
        "noEmitOnError": false,
        "noUnusedLocals": true,
        "strictNullChecks": false,
        "importHelpers": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "lib": [
            "dom",
            "es5",
            "es2015.promise"
        ],
        "types": []
    }
}
```
2.  Create a new workspace with both projects:
    *  `tsc --build` in either Project A or B emits 0 errors
    *  Opening a file from Project B with decorators produces the following error in the `problems pane`:
```
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by GordonSmith** [comment]
Note:  Adding `"experimentalDecorators": true` to both `tsconfig.json` files explicitly does not help.

**Comment by GordonSmith** [comment]
I tried to create a minimal project to reproduce, but have failed to do so.  Here are the instructions to reproduce using my full repo (apologies for the size):
```
git clone git@github.com:GordonSmith/Visualization.git
cd Visualization
git checkout VSCODE-68349 
npm install
npm run build-dev
code ./demos/dashy/dashy.code-workspace
```
Then open the following file:  `marshaller/ddl2/model/element.ts` wait for a few moments and you will see the issues in the Problems Pane.

But if you open the same file, within the "marshaller" project you don't get any errors:
```
code ./packages/marshaller/
```
and open file "src/ddl2/model/elements.ts"

Further - you can build (tsc --build) "dashy" which includes marshaller as a dependency in tsconfig by pressing ctrl+shift+b and it doesn't produce any errors.

**Comment by mjbvz** [comment]
If you open `marshaller/ddl2/model/element.ts` and run `go to project` configuration, you can see that this file is not considered part of any tsconfig project.

This is because VS Code will only load tsconfig files from within your workspace; it will not attempt to search up into higher directories. Try including all of `marshaller` instead of just the src directory:

```json
		{
			"name": "marshaller",
			"path": "../../packages/marshaller"
		}
```

That way the tsconfig is also in the folder
