### ISSUE TITLE
Git: Option to ignore file locally

### ISSUE THREAD

**Issue by whirish** [microsoft/vscode#68340]
When right-clicking a changed file in the Source Control pane, there is an option to "add this file to `.gitignore`". I frequently use `.git/info/exclude` for local files (it's particularly helpful for db dumps), and it would be great to have a context menu option such as "ignore this file locally" that works in the same manner. I'm willing to implement on this.

**Comment by joaomoreno** [comment]
I'm no longer convinced that this should be a core product feature. I recommend creating an extension which does this. Sorry for the delay.

**Comment by FiredLight** [comment]
You can achieve this using the exclude file that is in your .git folder. The .git folder is at the root of your repository (where you ran git init). The .git folder isn't committed, so it's safe to put local only changes in here.

open .git/info/exclude and add your entry, reload vscode if it isn't picked up immediately

**Comment by oenseling** [comment]
> I'm no longer convinced that this should be a core product feature. I recommend creating an extension which does this. Sorry for the delay.

Could you elaborate please? SourceTree implements this and it has been very useful to me. As I am not able to use SourceTree on Linux I am exploring git functionality in VSCode / gitlens and I am really missing this?

Does anything know of a plugin that implements this?

**Comment by zhaoxu-lingoace** [comment]
see https://github.com/jellyedwards/gitsweep

**Comment by zhaoxuyll** [comment]
see https://github.com/jellyedwards/gitsweep
