### ISSUE TITLE
Can't split terminal

### ISSUE THREAD

**Issue by Lwenli1224** [Microsoft/vscode#68342]
Issue Type: <b>Bug</b>

error: 终端进程命令“/bin/zsh  -l”无法启动 (退出代码: 1)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
ejs-language-support|Qas|0.0.1
vsc-material-theme-italicize|Ser|0.0.14
ejs-snippets|Tao|0.1.0
terminal-tabs|Tyr|0.2.0
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.3
vscode-javascript-snippet-pack|aka|0.1.5
vscode-color|ans|0.4.5
eggjs|ati|0.3.1
mpvue-snippets|ban|1.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-wxml|cod|0.1.9
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
app-migrator|deb|0.0.6
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.0.1
gitlens|eam|9.5.0
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
we-app-vscode|eme|0.8.0
react-native-react-redux|EQu|2.0.1
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.8.1
file-icons|fil|1.0.16
flow-for-vscode|flo|1.0.1
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
terminal|for|0.0.10
vscode-yarn|gam|1.6.0
vscode-flow-ide|gca|1.2.0
vscode-nginx-conf-hint|han|0.1.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.8
vscode-favorites|how|1.4.0
path-autocomplete|ion|1.13.1
search-node-modules|jas|1.3.0
webpack|jer|2.1.2
azure-functions-tools|joh|0.3.3
intellij-idea-keybindings|k--|0.2.31
auto-comment-blocks|kev|1.0.1
vscode-codemetrics|kis|1.17.4
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
sftp|lix|1.9.3
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.5.0
prettify-json|moh|0.0.3
vscode-autoprefixer|mrm|2.2.0
vscode-azurefunctions|ms-|0.13.1
vscode-language-pack-zh-hans|MS-|1.31.4
azure-account|ms-|0.8.0
js-atom-grammar|ms-|0.1.14
vsliveshare|ms-|0.3.1151
vsliveshare-audio|ms-|0.1.48
debugger-for-chrome|msj|4.11.1
vscode-paste-image|mus|1.0.4
vscode-for-node-js-development-pack|nod|2.0.1
prettier-standard-vscode|num|0.5.0
vetur|oct|0.15.0
code-rhythm|onv|1.0.6
vuehelper|oys|0.1.0
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
minapp-vscode|qiu|1.12.1
LiveServer|rit|5.4.0
vscode-icons|rob|8.1.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.4
vscode-nginx|sha|0.6.0
markdown-preview-enhanced|shd|0.3.11
code-spell-checker|str|1.6.10
language-stylus|sys|1.11.0
react-beautify|tai|0.3.0
vscode-markdown-paste-image|tel|0.12.0
stylus-supremacy|thi|2.12.7
react-redux-es6-snippets|tim|2.1.0
vscode-npm-scripts|tra|0.2.1
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(14 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
The error message said `can't launch “/bin/zsh -l” (Exit Code 1)`

**Comment by Lwenli1224** [comment]
终端进程命令“/bin/zsh  -l”无法启动 (退出代码: 1)   version: 1.32.2

**Comment by Tyriar** [comment]
This means that running `/bin/zsh -l` exited with code 1, it's likely a problem with your environment.

**Comment by joeldenning** [comment]
I'm seeing this too on osx. I have confirmed that `/bin/zsh -l` does not exit with code 1 when I run it manually in a terminal
