### ISSUE TITLE
The colors are not consistent across the editor. Some colors are faded

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode#68341]
- VSCode Version: 1.31
- OS Version: Solus 3.X

![image](https://user-images.githubusercontent.com/11936772/52528658-5e051f80-2ca9-11e9-9eab-e0ffb52b6eb6.png)

Steps to Reproduce:

1. Open file with Solarized Dark theme

Does this issue occur when all extensions are disabled?: Yes

**Comment by tristan957** [comment]
Possibly related to Electron or Monanco?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/68001

**Comment by tristan957** [comment]
@bpasero for what its worth it has not been a problem today

**Comment by tristan957** [comment]
Wait I don't think these issues are the same based on what I read in the thread. Mine has to do with colors being inconsistent across the background. Notice in the Northeast and Southeast quadrants of the editor, they are different colors than the the area along the x-axis.

**Comment by tristan957** [comment]
This also isn't specific to Solarized Dark. It is visible on other default themes but not all

**Comment by tristan957** [comment]
Seems to only happen on my external monitor, but it displays colors fine in other applications

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by tristan957** [comment]
I used the linux build. I added my settings, and I could not reproduce the behavior
