### ISSUE TITLE
Vetur, VSCode and TypeScript issue

### ISSUE THREAD

**Issue by eyalsk** [microsoft/vscode#68343]
About 8 months ago I made an issue on the [Vetur repo](https://github.com/vuejs/vetur/issues/815) and on [StackOverflow](https://stackoverflow.com/questions/50782749/typescript-vue-and-experimentaldecorators/50788348) that causes an error and degrades the experience in VSCode when working with Vue and still no fix and the workarounds don't work for everyone.

As far as it seems the issue is when you open the project from a directory that has no `tsconfig.json` then TypeScript will complain about it and will result the following message:

> Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

VSCode then will add red squiggles and mark the directories in red which makes the experience really unpleasant, one way to "solve" it is open the project from the location of the `tsconfig.json` but then you need to have two instances of VSCode one to work on `.vue` files and another to work on other parts of the project and  as I mentioned before there are other workarounds provided on the Vetur repo but they don't work for everyone due to different setups and whatnot.

This might not be a VSCode problem per se but because we don't really know where it should be solved and what's the best approach to take here I decided to post this here, hoping that the VSCode team would know or at least shed some light on it.

p.s. It doesn't seems to happen in Visual Studio 2017 but then I don't need to install anything there for it to work as [VS2017](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#improved-vuejs-support) support Vue out of the box.

**Comment by octref** [comment]
Yeah, I need to revive https://github.com/vuejs/vetur/issues/385#issuecomment-349272564.

@mjbvz Do you do any special handling for `tsconfig.json` on TS extension side, when it's not on the top level or if there are multiple tsconfigs? Or are they all handled by TSServer automatically?

**Comment by mjbvz** [comment]
The TSServe finds tsconfigs in sub directories and correctly handles when there are multiple tsconfigs in a project. However we do not pick up tsconfigs that are not named `tsconfig.json` (so `tsconfig.dev.json` or `my-tsconfig.json` would not be picked up)

**Comment by octref** [comment]
I took a look of TS extension, seems you are calling `compilerOptionsForInferredProjects` on TS Server for each project's inferred options. However, I didn't find such API on TS's `LanguageServiceHost`, guess it's just a matter of finding the right API...

**Comment by octref** [comment]
I enabled `experimentalDecorator` in the case no jsconfig/tsconfig can be found https://github.com/vuejs/vetur/issues/1289. Reading tsconfig from non-top level is not easily doable.
