### ISSUE TITLE
Should/can we move the electron executable?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6835]
I've seen a lot of people have legacy/manual symlinks that point at code, not bin/code. Should we move `code` to another directory so they break and it's more clear that bin/code is the right one?

**Comment by joaomoreno** [comment]
Not trivial, since that location is set by Electron.

**Comment by Tyriar** [comment]
How about requiring `VSCODE_CLI` or something?

**Comment by joaomoreno** [comment]
Also doesn't work, because we still need to execute the executable directly when double clicking it or launching it via an application launcher.

**Comment by Tyriar** [comment]
Ah ok, I guess the answer is no :)

**Comment by joaomoreno** [comment]
I'd like to do it... but not really sure how to. Maybe a warning at startup if detected that it is a tty... but still...
