### ISSUE TITLE
C# Syntax Highlighting Incorrect in Markdown Preview

### ISSUE THREAD

**Issue by tonysneed** [Microsoft/vscode#68358]
- VSCode Version: 1.31.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Enter a cs code block in a markdown file.
2. Open Preview

Does this issue occur when all extensions are disabled?: Yes

Markdown:
![cs-markdown](https://user-images.githubusercontent.com/2836367/52534714-896c2680-2d0a-11e9-9e2b-69fa5d2f1125.png)

Preview:
![cs-markdown-preview](https://user-images.githubusercontent.com/2836367/52534718-98eb6f80-2d0a-11e9-9b64-907087247e1d.png)

**Comment by mjbvz** [comment]
We use highlight js to render code the preview so it will not match what you see in VS Code

**Comment by tonysneed** [comment]
For others stumbling across this, try a vscode extension, such as [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced).
