### ISSUE TITLE
Failed to move file to trash after upgrade to 1.31

### ISSUE THREAD

**Issue by faelv** [microsoft/vscode#68359]
Issue Type: <b>Bug</b>

**Steps to reproduce**
Delete a file from the file Explorer

**Actual result**
A dialog with the fellowing message is displayed "Failed to delete using the Trash. Do you want to permanently delete instead?"

**Expected result**
File is moved to the trash

**Extra info**
- It worked on 1.30.
- ```gvfs-trash path/to/file``` works.
- Linux Mint 18.3 Cinnamon x64

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 882)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.74GB (3.61GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
vscode-intelephense-client|bme|0.8.8
gitlens|eam|9.5.0
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.6
Go|ms-|0.9.1
php-docblocker|nei|1.7.0
material-icon-theme|PKi|3.6.3

(2 theme extensions excluded)

</details>

**Comment by faelv** [comment]
I think none of the above exactly covers this one.

**Comment by user414** [comment]
Great, we were just investigating this after upgrading to 1.31 as well. Thanks @faelv for reporting the issue and saving us time. For information we are on Ubuntu 16.04 LTS and gvfs-trash works for us as well.

**Comment by faelv** [comment]
It seems an electron issue. In  "`shell.moveItemToTrash`" electron tries to infer the correct trash command for the current environment and for non-KDE distros it picks (or defaults to) `gio` which is not available in older versions.

You can test this by creating an executable shell script named `gio` with these few lines:

```bash
#!/bin/bash

if [ $# -lt 2 ]; then
  echo "invalid parameter count"
  exit 1
fi

CMD=$1
FILE=$2
if [ "$CMD" = "trash" ]; then
  echo "Moving to trash: $2"
  gvfs-trash "$2"
  exit 0
fi

echo "only \"trash\" is supported"
exit 1
```

and making it available in your path.

**Comment by entr** [comment]
`export ELECTRON_TRASH=gvfs-trash` fixed it for me

**Comment by isidorn** [comment]
I think there is a duplicate for this, @bpasero would know better

**Comment by erkanarslan** [comment]
I have this problem on Ubuntu 16.04 with version 1.31.1 of Vscode. @entr What should I do with that command? Do i need to run in the shell? Is it a permanent solution?

**Comment by faelv** [comment]
@erkanarslan, for now the best fix is the @entr answer:
`export ELECTRON_TRASH=gvfs-trash`
In your `.profile` file (or equivalent for your distro).

**Comment by liteultom** [comment]
`export ELECTRON_TRASH=gvfs-trash` worked for me also. Thank you for the quickfix, this was getting annoying !

**Comment by naderdl** [comment]
> `export ELECTRON_TRASH=gvfs-trash` fixed it for me

thanks a lot after installing gvfs-trash and exporting it as you said my problem fixed.
I'm using ubuntu 16.04. and vscode 1.34.

**Comment by bpasero** [comment]
Closing as workaround exists.

**Comment by williamsp** [comment]
I still have the same problem, using Ubuntu 16.04. Using gvfs-trash is fine on Terminal, but not working on vscode. Exporting the electron trash does not help.
