### ISSUE TITLE
External code-workspace file changes not picked up until reload

### ISSUE THREAD

**Issue by iciclesoft** [Microsoft/vscode#68351]
Issue Type: <b>Bug</b>

Changes to the `.code-workspace` file by external sources (extensions/manual edit) are not picked up anymore until VSCode is relaunched. For instance, if you use notepad to add a workspace folder to the `.code-workspace` file, VSCode won't show the new workspace folder until the workspace is relaunched in VSCode. This also means that if you then add another workspace folder through VSCode, and save the workspace, the workspace folder added with notepad is removed. Using the `Refresh Explorer` button doesn't trigger a re-read of the `.code-workspace` file either. This renders the extension `WorkspaceSort` rather useless.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a new workspace
2. Add 2 folders to the workspace, called `B` and `A`
3. Save the workspace
4. Edit and save the `.code-workspace` file, changing the order of the folders using notepad or the extension `WorkspaceSort`
5. Notice that the order in VSCode has not been changed
6. Close and reopen VSCode, notice that the order in VSCode did change

**Comment by bpasero** [comment]
I was not able to reproduce this on macOS at least.

**Comment by iciclesoft** [comment]
In the screenshot below you can see that VSCode shows a different order of the folders than the `.code-workspace` file.

![folder-test](https://user-images.githubusercontent.com/7295446/52583320-9898c480-2e2f-11e9-9b52-1c5ee6650ccc.png)

**Comment by isidorn** [comment]
@iciclesoft Can you reproduce this with latest vscode insiders?
https://code.visualstudio.com/insiders/

**Comment by iciclesoft** [comment]
@isidorn Yes, I can. The screenshot below shows the difference in the order of the folders between the content of the `.code-workspace` file within the latest insiders, in this case there are also no extensions active. Changes are not shown in VSCode until it is restarted.

![folderorderinsiders](https://user-images.githubusercontent.com/7295446/52978156-5d1e6d00-33d0-11e9-944a-a81989790b97.png)

**Comment by isidorn** [comment]
I can reproduce this also on the mac.
The issue here is that the `contextService` does not fire a `onDidChangeWorkspaceFolders` event when the order of workspace roots is changed in the code-workspace since. Since the order changed I would expect this event to arrive.
Thus forwarding to @bpasero and @sandy081

**Comment by bpasero** [comment]
@sandy081 could be the case of a missing file event, if so, please forward back to me.

**Comment by isidorn** [comment]
@bpasero The file event does not seem to go through. if I start out of source with --verbose flag.

**Comment by bpasero** [comment]
@sandy081 I assume you setup custom file watching for the workspace file right? Where is that code? Does it check for changes?

**Comment by sandy081** [comment]
I think this would have caused by my changes moving away from node based file watching to file service watch. Will investigate further and figure it out.

**Comment by iciclesoft** [comment]
Thanks for the fix, I just tested it in the new insiders build and everything seems to be working correctly. I am looking forward to the next release!
