### ISSUE TITLE
[v1.31] Markdown preview not working

### ISSUE THREAD

**Issue by MatteoCampinoti94** [Microsoft/vscode#68354]
## Description:
The markdown extension doesn't seem to work anymore on the Arch (Linux) version. This only happens in version 1.31

Whenever it is called a `command 'markdown.[command]' not found` message shows up. The extension is properly installed however and is loaded correctly.

I've also tried to make a clean install, removing all user files, settings and extensions, but the problem persisted.

## Additional info:
* Version: 1.31.0
* Commit: bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce
* Date: 2019-02-09T14:23:42.615Z
* Electron: 2.0.16
* Chrome: 61.0.3163.100
* Node.js: 8.9.3
* V8: 6.1.534.41
* OS: Linux x64 4.20.6-arch1-1-ARCH

## Steps to reproduce:
Simply open a markdown file and try opening the preview, either via keyboard shortcuts or the preview button on the upper right.

**Comment by yory8** [comment]
I can confirm, same configuration

**Comment by mjbvz** [comment]
@MatteoCampinoti94 Please try checking the developer console for errors:

1. The run `Developer: Toggle developer tools` command in VS Code. This should open developer tools
1. Open the developer tools console.
Please share any errors or stack traces printed in that console

**Comment by MatteoCampinoti94** [comment]
Done, it seems to be a regexp error.

```
[Extension Host] Here is the error stack:  SyntaxError: Invalid regular expression: /(\p{Alphabetic}|\p{Number})+/: Invalid escape
	at new RegExp (<anonymous>)
	at t.activate (/usr/lib/code/extensions/markdown-language-features/dist/extension.js:1:49711)
	at Function.t._callActivateOptional (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:741:354)
	at Function.t._callActivate (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:741:25)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:206
	at <anonymous>
```

**Comment by mjbvz** [comment]
@bpasero This error seems related to the electron update. Our previous version of node did not support unicode classes in regular expressions but Node 10 should

**Comment by deuscode** [comment]
Updated to 1.31 and on Arch Linux as well, here are my error output if it helps.

```
Error: command 'markdown.showPreviewToSide' not found
    at Proxy.t._tryExecuteCommand (workbench.main.js:3226)
    at workbench.main.js:3225
    at <anonymous>
t.onDidNotificationChange @ workbench.main.js:2561
(anonymous) @ workbench.main.js:2561
e.fire @ workbench.main.js:81
t.notify @ workbench.main.js:2621
t.error @ workbench.main.js:3778
t.onError @ workbench.main.js:3211
(anonymous) @ workbench.main.js:3211
Promise rejected (async)
(anonymous) @ workbench.main.js:3210
setTimeout (async)
t.runAction @ workbench.main.js:3210
t.run @ workbench.main.js:3210
e.run @ workbench.main.js:1066
t.elementSelected @ workbench.main.js:1129
(anonymous) @ workbench.main.js:1123
```

**Comment by bpasero** [comment]
@mjbvz can you try to reproduce in standalone Electron running as node?

**Comment by mjbvz** [comment]
@bpasero It will take me time to setup an arch linux machine with gui. Can't find a pre-build container

@MatteoCampinoti94 Back in the developer tools, can you please share the output of running `process.versions` in the developer console:

<img width="662" alt="screen shot 2019-02-12 at 12 08 10 pm" src="https://user-images.githubusercontent.com/12821956/52664971-3ab3bd80-2ebf-11e9-96c2-6a164326d890.png">

**Comment by MatteoCampinoti94** [comment]
@mjbvz Here it is

![screenshot from 2019-02-12 21-18-38](https://user-images.githubusercontent.com/5142004/52665414-d408c100-2f0b-11e9-890d-e908c00f777a.png)

**Comment by MatteoCampinoti94** [comment]
I've also tried to install the binary from Microsoft via the AUR and that version does work properly. I'm starting to think the error might be in the Arch package itself, I've checked its PKGBUILD and it seems it's using the lts version of nodejs (which is at version 8.9 if I remember correctly).

**Comment by mjbvz** [comment]
Thanks. Looks like that package is still using electron 2 https://www.archlinux.org/packages/community/x86_64/code/ but VS Code 1.31 requires electron 3. 

Since I believe code package is maintained by the community, please file an issue against them so that they can pick up electron 3

**Comment by MatteoCampinoti94** [comment]
Yeah, seems like it. Thanks for the help, I'll send a bug report to the maintainer and build the package myself for the time being.

**Comment by MatteoCampinoti94** [comment]
Discussion for the update to electron 3 has already started  https://bugs.archlinux.org/task/61691

**Comment by eli-schwartz** [comment]
The updated package using electron 3 has now been released to the archlinux community repository.

**Comment by MatteoCampinoti94** [comment]
Thank you for the update @eli-schwartz !

**Comment by yory8** [comment]
Thank'you, I can confirm that now it works

**Comment by j-james** [comment]
Yup, that fixes it for me. Thank you for the quick turnaround!
