### ISSUE TITLE
[eslint] Parsing error: The keyword 'const' is reserved

### ISSUE THREAD

**Issue by sgon00** [Microsoft/vscode#68352]
I have `.eslintrc.json` with the following contents:

```json
{
    "env": {
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    }
}
```

But it doesn't work at all. VSCODE still reports this error `[eslint] Parsing error: The keyword 'const' is reserved`

I read https://github.com/Microsoft/vscode/issues/880, but I still don't understand how to fix it and how to make vscode to use my `.eslintrc.json` config file. Sorry that since I cannot comment on that issue, I have to open a new one. 

**Edited:**

I even tried `eslintConfig` in `package.json`, but it still doesn't work. 
So far, only adding `/* eslint-env node, es6 */` to the target js file works.

**Comment by mjbvz** [comment]
Please file this against the eslint extension
