### ISSUE TITLE
VSCode ignores display language when opening a new window from within VSCode

### ISSUE THREAD

**Issue by L0g4n** [Microsoft/vscode#68350]
- VSCode Version: 1.31.0, bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce
- OS Version: Linux 4.20.3, Solus

Steps to Reproduce:

1. Display language is set in VSCode to german.
2. Launch a new window of VSCode from that application with CTRL+SHIFT+N or the menu. A VSCode window shows up with the display language set to english instead of german.

Does this issue occur when all extensions are disabled?: Yes

If this is a Solus Linux related issue that only happens in their OSS package of VSCode, please let me know.

**Comment by kieferrm** [comment]
When you call `Configure Display Language` from the command palette the following json file opens. It tells you to restart VS Code.

```
{
	// Defines VSCode's display language.
	// See https://go.microsoft.com/fwlink/?LinkId=761051 for a list of supported languages.
	// Changing the value requires to restart VSCode.
	"locale":"en"
}
```

Did you restart? Your instructions don't say so.

**Comment by L0g4n** [comment]
Yes, I know that. I have that locale configured a long time to german and my VSCode is in german (so yes when I did that I restarted it back then). I just observed that with new update, when I open a new VSCode window within my "german" VSCode 1.31.0 the display language is english instead of my configured language.

**Comment by dbaeumer** [comment]
I tried to reproduce this with updating to 1.31.1 but was not able to do so. @L0g4n I understand you problem as follows:

- after an update to 1.31.0 your display language was English

Is this still the case for you?

**Comment by L0g4n** [comment]
@dbaeumer 
With Update 1.31.1 i no longer have this problem. So basically it was either an upstream or a downstream issue.
