### ISSUE TITLE
Reordering members through outline view

### ISSUE THREAD

**Issue by FreHu** [microsoft/vscode#68353]
Hi,

I would like to be able to drag and drop contents in the outline view. This would be useful for example to rearrange xml files or class methods.

**Comment by FreHu** [comment]
I don't believe this is covered.

**Comment by taciturasa** [comment]
After some tedious rearranging, I definitely agree that this would be a fantastic feature!

**Comment by cachius** [comment]
@jrieken In whose scope is it?

**Comment by sauce-code** [comment]
I would love to see a feature like this. I don't see at all why this would be out-of-scope.

**Comment by MartinBernstorff** [comment]
Another supporter here! Would love to see it.

**Comment by jrddp** [comment]
This is a feature in Obsidian, was disappointed to see it wasn't possible in VSCode. Would be amazing!

**Comment by sophie-du-couedic** [comment]
Why is it out-of-score? That would definitively be so useful!!

**Comment by patricktducat** [comment]
@jrieken yes, I too am curious how such a requested feature is out of scope. At least some rationale would be nice.

**Comment by xpeuvr327** [comment]
It seems that rules as in CSS are already draggable, but without effect. It would be really convenient if this feature was implemented!
