### ISSUE TITLE
Error Unable to find project.json or *.csproj

### ISSUE THREAD

**Issue by intiux** [Microsoft/vscode#68356]
Issue Type: <b>Bug</b>

I was unable to create / generate C# class, or Interface. 

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
razor-snippets-for-asp-net-core|ale|0.0.3
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.11
razor-plus|aus|0.1.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
tslint|eg2|1.0.42
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
angular2-switcher|inf|0.2.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|7.0.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.3
blazorsnippets|Sco|0.4.4

</details>

**Comment by kieferrm** [comment]
Please file the issue against the C# extension. Thanks!
