### ISSUE TITLE
Search: show notification around PCRE2 in context

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#68355]
I just got this:

![image](https://user-images.githubusercontent.com/900690/52534013-167ba380-2d3c-11e9-8211-6ff5fa3a941a.png)

Imho it would be much nicer if the hint would show in the search input field and not as notification. E.g. why not show it as part of the red error message?

**Comment by roblourens** [comment]
I think the "Open Settings" button is useful, otherwise the user has to figure out what that means and find the setting on their own. The search input error can't currently be interactive. Do you think it's confusing as a notification?

**Comment by bpasero** [comment]
I prefer notifications in context but I see the issue with that not being interactive.

**Comment by roblourens** [comment]
It was also a false positive in this case. The Rust regex engine just doesn't like things being escaped that don't need to be escaped (`\/` here)

**Comment by bpasero** [comment]
Ah ok, then maybe we can fix that. Either way I was just suggesting, feel free to close if not easy to do.

**Comment by roblourens** [comment]
Yeah I decided not to try to parse the regex myself to figure out which features it's using, and rg doesn't give us any other details about why it failed to parse, so that current state is basically by design.
