### ISSUE TITLE
Moving or Deleting files not refresing in treeview

### ISSUE THREAD

**Issue by danbord** [Microsoft/vscode#68361]
Issue Type: <b>Bug</b>

When moving or deleting files in the explorer treeview.  It does not refresh and the item stays there unless we refresh the tree.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1

</details>

**Comment by Maledong** [comment]
Ref：https://github.com/eamodio/vscode-gitlens/issues/606#issuecomment-462007732

**Comment by ntotten** [comment]
We are seeing similar reports from the users of the Salesforce extensions: https://github.com/forcedotcom/salesforcedx-vscode/issues/1036

**Comment by nchanged** [comment]
Same here! It also creates a dark overlay when you try to rename a file, and then the only way to get rid of it, is to restart VSCode. It's a real blocker

**Comment by chrislessard** [comment]
For what it's worth, I've noticed that if you trigger a file deletion through the Source Control pain, it refreshes properly in that the deleted file doesn't show up in the tree.

**Comment by isidorn** [comment]
@danbord I can not reprodce this. Can you repro with latest vscode insiders? https://code.visualstudio.com/insiders/

@nchanged As for the the rename a file overlay please file a new issue with reproducable steps (I also can not reproduce that one)
