### ISSUE TITLE
shan.code-settings-sync crashes the extension host

### ISSUE THREAD

**Issue by chiuan** [microsoft/vscode#68365]
Issue Type: <b>Bug</b>

/Applications/Visual…kbench.main.js:3532 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.3
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
shaderlabvscodefree|aml|1.1.3
uas|aml|1.0.5
go-builder-help|ans|2.4.3
shell-snippets|cds|0.1.2
tslint|eg2|1.0.42
code-runner|for|0.9.7
terminal|for|0.0.10
referenceshelper|gay|0.2.3
beautify|Hoo|1.4.8
output-colorizer|IBM|0.1.2
sproto-support|ily|0.0.1
path-autocomplete|ion|1.13.1
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.3
csharpfixformat|Leo|0.0.78
vscode-fileheader|mik|0.0.2
prettify-json|moh|0.0.3
csharp|ms-|1.17.1
Go|ms-|0.9.1
vetur|oct|0.15.0
proto|pet|0.0.2
classynaming|ref|1.2.0
vscode-icons|rob|8.1.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.4
markdown-preview-enhanced|shd|0.3.11
shader|sle|1.1.4
vim|vsc|1.0.8
unity-snippets|Ycl|0.1.2

(4 theme extensions excluded)

</details>

**Comment by jkwchui** [comment]
This is the same issue as reported.

```
Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3532
```


- VSCode Version: 1.31.0
- OS Version: macOS mojave 10.14

Steps to Reproduce:

1. Launch VS code with any extensions, or
2. After disabling all extensions to start, enabling any extensions.

No amount of extension host restarts help this issue.  AFAIK the issue is new to 1.31.0. 


Does this issue occur when all extensions are disabled?: **No**

**Comment by kieferrm** [comment]
Can you please attach the list of extensions you have installed and also tell us which extension (after having disabled all extension before) you then enable? Do you see the crash immediately or do you reload the window before it happens?

**Comment by chiuan** [comment]
> Can you please attach the list of extensions you have installed and also tell us which extension (after having disabled all extension before) you then enable? Do you see the crash immediately or do you reload the window before it happens?

i just update the newest version 1.31 and aways failed...
i need to disable the plugin one by one until the all disable ??

**Comment by alexandrudima** [comment]
@chiuan Can you please look at the extension host log and see which extension was last being loaded right before the crash?

`F1 > Developer: Show Logs > Extension Host`

**Comment by mscottnelson** [comment]
Not @chiuan, but I am seeing this same issue. There was no log listing for Extension Host, just logs for Main, Shared, and Window, maybe because the Extension Host never started and didn't generate logs? So, I disabled all of my extensions and started re-enabling them one by one. In my particular case, the Extension Host crashed when I started up the extension Settings Sync (shan.code-settings-sync). It looks like @chiuan also has this extension installed. Disabling that extension resolved the issue for me.

**Comment by chiuan** [comment]
> Not @chiuan, but I am seeing this same issue. There was no log listing for Extension Host, just logs for Main, Shared, and Window, maybe because the Extension Host never started and didn't generate logs? So, I disabled all of my extensions and started re-enabling them one by one. In my particular case, the Extension Host crashed when I started up the extension Settings Sync (shan.code-settings-sync). It looks like @chiuan also has this extension installed. Disabling that extension resolved the issue for me.

oh no。。。
i have backto 1.30 , works fine...

**Comment by alexandrudima** [comment]
Duplicate of #68024
