### ISSUE TITLE
Extension folder should be deleted when an extension is uninstalled

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode#68369]
It took me quite a while to figure out why an extension had stopped working. When I noticed the following error in the developer console:

```
[Extension Host] Activating extension 'ikappas.phpcs' failed: Cannot find module './configuration'.
```

... I found [this](https://github.com/Microsoft/vscode-go/issues/1612) issue via Google, and followed the suggestion made by Ramya. Problem solved. The extension installation must have somehow become corrupt, and I don't think that this is the first time that something like this has happened.

It's *very* unexpected that uninstalling an extension would leave the extension files in place, and not delete them. The fact that uninstalling and reinstalling an extension continues to use the exact same files on disk prevents users from "refreshing" an installation, which means that a simple fix becomes completely ineffective.

*Please* consider removing the extension folder from disk, or providing an option to do so when uninstalling the extension.

Somewhat-related: #66837.

**Comment by sandy081** [comment]
It was mentioned in this issue why it is needed https://github.com/Microsoft/vscode/issues/47164. There is also a command to reinstall an extension by deleting it.

**Comment by glen-84** [comment]
@sandy081,

Thanks for the additional information, but it doesn't change the fact that this violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

If it's not possible to delete the folder immediately (more than one window open), then I think that the user should be notified that a restart is required in order to complete the uninstall.

This may even lead to fewer issue reports, as users will be empowered to solve the issue by themselves (in cases of corrupt installations).

**Comment by sandy081** [comment]
@glen-84 I do not think restart is required when an extension is uninstalled. If I understand correctly, you got into a corrupted installation state which should not happen. I would rather concentrate on how you get into that state first.

**Comment by glen-84** [comment]
> I do not think restart is required when an extension is uninstalled.

I'm fairly sure that I went through an uninstall/reload/reinstall/reload cycle, and that the problem remained until I manually deleted the extension folder.

> If I understand correctly, you got into a corrupted installation state which should not happen. I would rather concentrate on how you get into that state first.

That's a bit beside the point – I'm not the only person to have had a similar issue. There could be many causes, from interrupted downloads, to disk failures, etc., and as things stand, it's non-obvious that you can't perform a simple reinstall to fix a broken installation.

Anyway, if you don't think that this is a problem, I'll say no more. 🙂

**Comment by sandy081** [comment]
Suggested steps are 

- Use `Reinstall` command from the Command Pallette
- Restart VS Code.


Regarding various reasons for corrupted installing, we tried to avoid them by first installing into a temp folder and rename it to real name. Install is not complete until the rename is done. Since rename is atomic there are no chances to have corrupted install. Hence checking with you that how did you get into this state.

**Comment by glen-84** [comment]
> Suggested steps are

I know this now, but not before pulling my hair out trying to understand why the extension was not working, even after uninstalling and reinstalling it using the most obvious methods.

> Hence checking with you that how did you get into this state

I have no idea – all I know is that deleting the extension folder and reinstalling the extension immediately fixed the issue.
