### ISSUE TITLE
Clear list of opened editors when clearing recently opened

### ISSUE THREAD

**Issue by byyxx128** [microsoft/vscode#68366]
Issue Type: <b>Bug</b>

See the GIF directly.
![bug](https://user-images.githubusercontent.com/20079289/52535671-3ea8d980-2d1f-11e9-9b1f-e7882dcaf90d.gif)
Even if I cleaned up the folder history, it seems some operation history is still recorded.

I have the following settings.
`    "files.hotExit": "off",    "window.restoreWindows": "none"`

VS Code version: Code - Exploration 1.32.0-exploration (9a424426327a0662529fd8c5d7e0d476f67f6aab, 2019-02-08T07:31:22.415Z)
OS version: Windows_NT x64 10.0.18334

**Comment by bpasero** [comment]
@byyxx128 what is the actual issue here?

**Comment by byyxx128** [comment]
@bpasero 
As shown above. If I open a folder, then open a file, next time when I open the folder with VS Code again, everything will restore. This is normal. However, even if I clear recent history, and make sure there is nothing in the recent list, then I open the folder again, everything will still restore. That is what I confused.

**Comment by bpasero** [comment]
@byyxx128 I see, that command is not for clearing the opened editors.

**Comment by byyxx128** [comment]
@bpasero That's it. So it can be a feature request. However, I don't there needs an additional command to achieve this. Just improve the current one.
