### ISSUE TITLE
Import error when importing json file in Vue, with checkJs enabled

### ISSUE THREAD

**Issue by DevMcC** [Microsoft/vscode#68363]
- VSCode Version: 1.31.0
- OS Version: Windows 10

Issue:
I just started adding a _jsconfig.json_ file to my project and I've enabled the `checkJs` option.
One of my Vue components is importing a json file, but the editor is showing me a `Cannot find module` error.

Steps to Reproduce:

1. Configure a `jsconfig.json` file, see below.
2. Make a Vue component.
3. Have the component import a json file.
4. See the import underlined with an error - `Cannot find module`.

Does this issue occur when all extensions are disabled?: Yes

jsconfig.json:
```json
{
    "compilerOptions": {
        "baseUrl": "./src/",
        "checkJs": true,
        "paths": {
            "@/*": ["./*"]
        },
        "resolveJsonModule": true
    },
    "include": [
        "src"
    ]
}

```

Additional info:
* Importing a js file works fine.
* Importing a json file from a js file works fine.

**Comment by octref** [comment]
`resolveJsonModule` is not available until TS 2.9, follow https://github.com/vuejs/vetur/issues/682.
