### ISSUE TITLE
Code Helper Causing 100% CPU usage

### ISSUE THREAD

**Issue by patientplatypus** [Microsoft/vscode#68373]
I'm opening this issue because the issue here (https://github.com/Microsoft/vscode/issues/51776) was closed without resolution or links to a new thread. This is a major and significant problem that could cause potential damage to my computer (I am currently running the latest version of vscode as of this posting). The issue was closed because "High CPU usage is a symptom with a very large number of potential root causes...", which, while true, is unhelpful. If I knew how to debug this myself this wouldn't be an issue needing to file a bug report for.

Please open this issue or provide a link to a new thread. Thank you.

**Comment by kieferrm** [comment]
Please see the following instructions on how to provide us actionable information. Thanks a ton!

https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by patientplatypus** [comment]
k

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
