### ISSUE TITLE
Draw the status bar's background in different colors (eg red, yellow) if the program has errors/warnings

### ISSUE THREAD

**Issue by jrheard** [microsoft/vscode#68376]
Hi! I've just started using VS Code this week. I've done several searches for this feature or a similar feature request and haven't found anything, please let me know if I've missed something.

I think that it should be possible for themes to affect the status bar's background color if the program has an error or warning. https://code.visualstudio.com/api/references/theme-color#status-bar-colors has a list of properties that can be used to affect the status bar's color, but as far as I can tell, none of these properties allow me to accomplish this.

If the program in the current editor window has an error, I want my theme to be able to color the status bar red. If the program has a warning, I want my theme to be able to color the status bar yellow. If there are both, I think that the error state should take priority, and so the status bar should use my red background color.

Does something like this exist and I've just missed it?

Thank you! :)

**Comment by auchenberg** [comment]
Idea: You could look into the setting `workbench.colorCustomizations` that allows you to override theme colors. 

Via our extension API you could built an extension that detects the error, and set the setting on a temp basis.

Try setting in your settings.json:
```
    "workbench.colorCustomizations": {
        "statusBar.background":"#ff0000"
    }    
```

**Comment by rchisholm** [comment]
how can I change that setting in typescript?

**Comment by ArturGajowy** [comment]
FWIW one can change a setting in this plugin to change the statusbar colors:
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.awooga#review-details
It changes the window background color by default (:joy:)
