### ISSUE TITLE
File Open Keyboard Shortcut broken

### ISSUE THREAD

**Issue by mwiora** [Microsoft/vscode#68370]
- VSCode Version: 1.32.0-insider (user setup)
- Commit (last 8 characters): 29bfc776
- OS Version: Windows_NT x64 

Steps to Reproduce:

1. Install the latest Visual Studio Code Insider
2. Try to open a file using Ctrl+O

The result will be a system dialog allowing you to select a folder instead of the expected file selector.
Does this issue occur when all extensions are disabled?: Yes (no extensions installed)

Even the File Menu does not show the Option anymore:
Current Code Insider:
![code_insider](https://user-images.githubusercontent.com/2744285/52537495-da5e3800-2d67-11e9-8ea7-04f1085b9fe0.png)

Current Code Stable:
![code_stable](https://user-images.githubusercontent.com/2744285/52537537-3032e000-2d68-11e9-9d16-6bd02b2b5426.png)

Expected behaviour:
Pressing Ctrl+O should open the File Selector

**Comment by kieferrm** [comment]
As a workaround you should be able to define your own keybinding.

**Comment by bpasero** [comment]
@mwiora what is the output of the keybinding:

![image](https://user-images.githubusercontent.com/900690/52549738-02d04b80-2dd5-11e9-8aa6-9704bcf63805.png)

**Comment by mwiora** [comment]
thanks for your answers. Keyboard Shortcuts looks good
ctrl + o still opens folder selector - update from today has been installed (...614defa0)

![image](https://user-images.githubusercontent.com/2744285/52561419-aa607480-2dfb-11e9-82f8-9e98a72cf139.png)

**Comment by bpasero** [comment]
@mwiora so everything is fine?

**Comment by mwiora** [comment]
@bpasero actually not - ctrl+o should open the file selector as defined in the keyboard shortcuts, but opens the folder selector window

**Comment by bpasero** [comment]
Looks like a regression from @alexr00 work (https://github.com/Microsoft/vscode/commit/04271d109111b06b51653d3637db2c46dee57a95#diff-f94f1afb81f5817de2bcd4e20f3d076fR64). I no longer see the `isMacintosh` check.

**Comment by mwiora** [comment]
just obtained the latest verison - FIXED - THX!
