### ISSUE TITLE
Have a more comfortable cursor/scroll position on undo

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#68374]
When I hit undo and the scroll changes, the cursor is set to the very top, making it hard to quickly see relevant code, making me have to scroll up a bit. Would be better in my opinion if it scrolled somewhere near the middle.

**Comment by alexandrudima** [comment]
@madprops When doing undo, the cursor is revealed with exactly the same logic like when pressing arrow up / arrow down, i.e. the viewport is changed only just enough to reveal the cursor. I believe this is common practice in all kind of editors, for example I have just tested Word and it behaves in the same way.

**Comment by madprops** [comment]
Check Sublime's behavior: https://dl.dropboxusercontent.com/s/87yizympb3uw8el/2019-02-11_07-10-49.mp4

When I scroll down and then hit ctrl+z the cursor is scrolled to the middle. In my opinion giving more context of where the cursor is, easier to edit.
