### ISSUE TITLE
1.31 fails to find linter and launch correctly tensorflow (keras) under Ubuntu, Mint

### ISSUE THREAD

**Issue by JuanVargas** [Microsoft/vscode#68375]
Last night I was happily using VSC 1.30 to test code I have running under Python 3, keras and tensorflow in boxes running Ubuntu and Mint. This morning VSC updated itself to 1.31, and since then VSC can't work with files that as of yesterday were fine. The diagnostic message is that Linter pylint is not installed, which is actually not true.

**Comment by kieferrm** [comment]
@JuanVargas please file the issue agains the Python extension. Thanks!
