### ISSUE TITLE
extensions.all does not correctly update when extensions.onDidChange fires

### ISSUE THREAD

**Issue by golf1052** [Microsoft/vscode#68379]
- VSCode Version: 1.31.0
- OS Version: Windows 10 1809 (build 17763.253)

Steps to Reproduce using an extension that is listening to `extensions.onDidChange`

1. Store list of `extensions.all`
2. Disable an extension
3. When `onDidChange` fires the extension will not be in the list of `extensions.all` (comparing the two lists)
4. Re-enable the same extension.
5. When `onDidChange` fires not that the extension will still not be in the `extensions.all` list.

The above steps also works for uninstalling then reinstalling an extension. I've tested this with Polacode (a non theme extension) and a theme extension.

Does this issue occur when all extensions are disabled?: No as this is related to extensions.

Related issues: #14444

**Comment by sandy081** [comment]
@golf1052 When you disabled the extension, does it show a reload is required?

**Comment by golf1052** [comment]
No for both extensions it did not prompt for a reload.

**Comment by sandy081** [comment]
May I know the extensions you are trying to disable?

**Comment by golf1052** [comment]
[Polacode](https://marketplace.visualstudio.com/items?itemName=pnp.polacode) and [Eva Theme](https://marketplace.visualstudio.com/items?itemName=fisheva.eva-theme)

**Comment by sandy081** [comment]
@golf1052 I tried with a simple example 

```ts
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.extensions.onDidChange(() => {
        vscode.extensions.all.forEach(e => console.log(e.id));
    });
}
```

Disabling the extension - Disabled extension is not there in the list
Enabling the extension - Enabled extension is in the list
