### ISSUE TITLE
Support to navigate between debug views using keyboard shortcuts

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#6837]
We should expose commands to navigate between the different viewlets of the debugger (variables, watch, call stack, exceptions/breakpoints).

Having that I could setup the keybindings and thus debug more efficiently.

**Comment by isidorn** [comment]
Currently you are able to navigate between the debug views by pressing ctrl + shift + D and than tab between views. Ctrl + shift + D will focus the first view, or the last focussed view if there was some. I think this experience is not that bad.

Are you looking for something that would for instance focus the breakpoints view directly?

**Comment by isidorn** [comment]
Closing until more info is provided

**Comment by kieferrm** [comment]
I was looking for something that allows me to jump for example directly between the back points call stack view and the variables view. But let me use the tab order for a while and see how that's working out.
