### ISSUE TITLE
Investigate term.js alternatives

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6838]
term.js is showing its limitations, the two options are to either fork it ourselves to suit our use case, or go with one of its more prominent forks:

- Community fork, converted to TypeScript https://github.com/sedwards2009/extraterm
- Built for commercial product https://github.com/sourcelair/xterm.js
- https://github.com/IonicaBizau/web-term
- https://github.com/shockone/black-screen

sedwards2009/extraterm looks very active https://github.com/sedwards2009/extraterm/graphs/contributors

Here are some of the problems that have sparked this issue:

- Integrated terminal cursor is in the wrong position after resize #6784
- Autoscrolling does not work in integrated terminal #6755
- selection problem in integrated terminal #6750
- Integrated terminal wraps incorrectly #6740
- Using cls in integrated terminal sometimes freezes it #6735
- The integrated terminal appears to be bottom-aligned, which makes it wobbly #6729
- Terminal: I am not getting scrollbars for scrolling? #6602

**Comment by rozzzly** [comment]
Might I suggest:
https://github.com/shockone/black-screen

It's an electron/react app that seems to do a really nice job of enhancing the traditional TUI. I haven't had a chance to try it, but never have I seen anything coming close to bridging CLI and GUI. This is really fkn cool, Imagine that intergrated with VS Code!

That project appears to be pretty mature, and it's even written in typescript! :wink: TBH, I don't know anything about the Electron api, but I would assume(/hope) that it would be possible to run that console in an isolated process, which renders its gui to a container docked within the VS Code editor . Then create some mechanism to enable communication between the editor/terminal via some new IPC interface. But then again, it might just be easier to merge the two projects completely, I don't know enough about either backend to offer any meaningful conjecture on the implementation.... 

However, I recently started using ConEmu, which has this render to pane feature and it's awesome. Yet, the two apps are oblivious of each other. There is no _out-of-the-box-way_ to facilitate communication between the two. Just to launch a task I would have to write some contrived daemon that runs in the shell waiting for vsc to run some other script that _pokes_ that daemon into performing some action within the active shell... yuck. :hear_no_evil: Imagine a unified workspace / intellisense bridging that gap. **damn.**


### Few cool features (but definitly checkout the repo itself!!)

Intellisense-esque completion when typing into the shell (and theres is  a custom completion provider api in `black-screen`) 
![intellisense-esque completion in shell](https://raw.githubusercontent.com/shockone/black-screen/b946b041a0fa4198f76826351fb427d48ed8dcfb/README/main.png)
JSON explorer like in chrome devtools:
![JSON explorer like in chrome devtools](https://raw.githubusercontent.com/shockone/black-screen/59aaf2c14c243469b4bedb8bb453a8e343a6d0fc/README/json_decorator.png)
Still works with your favorite tools:
![Still works with your favorite tools](https://github.com/shockone/black-screen/raw/59aaf2c14c243469b4bedb8bb453a8e343a6d0fc/README/htop.png)

Obviously this would be a wayyyyy larger investment (in terms of manhours) than `term.js` but the possibilities are mind boggling when you consider some of the possible workflows you could set up with this...

My friends, just.......<img src="https://data.whicdn.com/images/231792319/large.gif" width="150" align="middle"/>

**Comment by Tyriar** [comment]
Thanks for the suggestion @rozzzly, my main concern with something like that is that it's not leveraging people's terminal setups. For example, I would probably be losing some information I find most useful as I have a custom prompt to display git status for me. Will check it out though.

**Comment by Tyriar** [comment]
I have actually tried black-screen before, it seemed kind of cool but it was different to what I was used and didn't particularly want to change :P

**Comment by romgrk** [comment]
@Tyriar totally agree with your concerns. 
I wrote an atom package for embedding a terminal (github.com/romgrk/termrk) (using term.js, but definitely not the best solution), and a recurrent point of attraction for users was to have their usual terminal setup available from Atom, be it zsh, bash, or other.

**Comment by rajeevkumarsharma** [comment]
We can mix black-screen and xtrem feature into out vscode terminal

**Comment by Tyriar** [comment]
Spend a while bashing at xterm.js and created a bunch of issues https://github.com/sourcelair/xterm.js/issues. It certainly seems to be in a better state than term.js imo, I haven't played much with it actually within vscode yet though.

**Comment by be5invis** [comment]
@Tyriar I can confirm that term.js cannot handle DBCS characters well.

**Comment by Tyriar** [comment]
@be5invis we're likely going to go with xterm.js, I created a bunch of i18n issues over there after playing with it a bit:

- Pasting in 日本語 adds an unexpected line break after 本 which puts the cursor off screen https://github.com/sourcelair/xterm.js/issues/61
- CJK characters are not treated as double width chars https://github.com/sourcelair/xterm.js/issues/62
- Moving over CJK text jumps 2 characters at a time https://github.com/sourcelair/xterm.js/issues/70

I think they're all related to the width and byte size of the characters.

**Comment by danekan** [comment]
I am seeing my integrated terminal does not honor line breaks... example in notepad:
mkdir directory 1[enter]
mkdir directory2

copy paste the above into terminal, it will run as one command with line breaks removed: mkdir directory1mkdir directory2

This happens on windows term with both cmd.exe and powershell so I assume it relates to the integrated terminal functionality itself?

**Comment by Tyriar** [comment]
@danekan can you open a new issue for that and mention your on Windows? It seems to be working find on Linux.

**Comment by danekan** [comment]
sure

**Comment by be5invis** [comment]
Oh there's another problem: term.js treats `〈` and `〉` as full-width, while Windows measures the real character width and layout them (at least under CP936),

**Comment by Tyriar** [comment]
Put out a big PR that fixes the major scrolling issues with xterm.js https://github.com/sourcelair/xterm.js/pull/101

Since I've already merged in xterm, I'm going to close this issue off.
