### ISSUE TITLE
Since January update, copy and paste folder between 2 vscode instances doesn't work

### ISSUE THREAD

**Issue by lepinekong** [Microsoft/vscode#68380]
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open 2 VScode on 2 differents projects
2. Copy folder from first project
3. Right-Click to Paste in 2nd project: Paste option is greyed

Does this issue occur when all extensions are disabled?: Yes

**Comment by heppa** [comment]
Not sure that this is a duplicate... This was a feature, that got introduced in 1.21 (Feb 2018 update) and I used it quite a lot...

https://code.visualstudio.com/updates/v1_21#_copypaste-files-across-windows

When I select a single or multiple files in one instance, and CTRL-C (or copy via menu), I can't paste them in another instance. 

Dragging / Dropping works, but differently. With copy-paste, when the file already existed, it would create it with a different name when pasting. With drag / drop, it would ask if it should replace.
