### ISSUE TITLE
Cannot use "Output Colorizer" and "Code Runner" except you should be able to because it's a basic thing a person would want to do

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode#68382]
Sorry to have to fight for what is obvious but this is a basic thing a person would want to do in VSCode:
**Have colored output. Have a code runner.**

It is not possible to use Output Colorizer and Code Runner.

IBM Output Colorizer
- https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

Code Runner
- https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

Code Runner causes Output Colorizer to be disabled.

**Comment by Yzrsah** [comment]
@sandy081 

The extension authors are unable to solve the issue:

https://github.com/Microsoft/vscode/issues/19561

**Comment by Yzrsah** [comment]
@sandy081 

The extension authors are unable to solve the issue due to lack of support in VSCode

https://github.com/Microsoft/vscode/issues/19561

**Comment by sandy081** [comment]
I see.

Please continue your discussion in that item.
