### ISSUE TITLE
not able to create new branch in Git

### ISSUE THREAD

**Issue by rajkumar49** [Microsoft/vscode#68389]
Issue Type: <b>Bug</b>

when you click the bottom left Git Branch name in Visual studio code and click " create new branch" and then if you give the new branch name and then press Enter button, " not working "- Error

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.5.0
git-project-manager|fel|1.7.1
PowerShell|ms-|1.11.0
team|ms-|1.144.1
vscode-docker|Pet|0.5.2
vscode-java-dependency|vsc|0.3.0
vscode-maven|vsc|0.14.1

</details>

**Comment by ashvin777** [comment]
+1

**Comment by joaomoreno** [comment]
What error do you see?

**Comment by ashvin777** [comment]
I am talking about the flow triggered from "Create branch" option under `Cmd` + `Shift` + `p` menu

Now I understood why it is not working. Earlier I used to create a new branch in just 2 steps and now I see that another step is introduced to select ref branch. Not sure why there is a need of selecting the additional ref branch, it makes more sense take the current branch as reference just like it does in `git branch -b xx` command.

**Comment by xblitz** [comment]
Seems to be the same issue as https://github.com/Microsoft/vscode/issues/68918 ,  Create Branch workflow now has an additional step.  which might be confused by current users that it didnt work :/  maybe this could become a setting
