### ISSUE TITLE
Window going TOP inside if my task bar position is top

### ISSUE THREAD

**Issue by mansres** [Microsoft/vscode#68387]
Issue Type: <b>Bug</b>

1. Set Top to Tasksbar location on screen.
2. Open a vscode.
3. File -> New Window.
4. Look where is window head? it is not in proper position.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@mansres can you attach a screenshot

**Comment by mansres** [comment]
Please do refer steps which is I mentioned before. You can get it.

**Comment by bpasero** [comment]
Looks ok to me:

![image](https://user-images.githubusercontent.com/900690/52577206-e7d7f880-2e21-11e9-960c-86c5dd91edf1.png)

**Comment by mansres** [comment]
It is looks like this to me.
![bug](https://user-images.githubusercontent.com/12108539/52618061-2f5c9400-2eb7-11e9-8333-744a4a0de6a2.png)
