### ISSUE TITLE
JSDoc info not showing in VSCode on `exports.default`

### ISSUE THREAD

**Issue by Hocdoc** [Microsoft/vscode#68390]
Issue Type: <b>Bug</b>

As described in this [issue](https://github.com/jsdoc3/jsdoc/issues/1573) the JSDoc info is not showing when using `exports.default`. It works for named exports but not for the default export. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.8.1
php-debug|fel|1.12.6
jbockle-format-files|jbo|3.0.0
graphql-for-vscode|kum|1.13.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.2
vscode-graphql|Pri|0.1.6

</details>

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/24033
