### ISSUE TITLE
Poor fuzzy matching for multi word command

### ISSUE THREAD

**Issue by koliyo** [Microsoft/vscode#68396]
- VSCode Version: 1.31.0 (1.31.0)
- OS Version: Mac OS Mojave

Steps to Reproduce:

I'm trying to launch the `VSNotes: Search notes` command, and I type `note search` in the command navigator and it finds nothing. If I only type `note` I get all the relevant commands + some more.

See example screenshots

![screenshot 2019-02-11 at 10 02 32](https://user-images.githubusercontent.com/770348/52553682-a6752800-2de4-11e9-8bb9-8f1c318a64a4.png)
![screenshot 2019-02-11 at 10 02 53](https://user-images.githubusercontent.com/770348/52553683-a8d78200-2de4-11e9-9d02-0101eb081b4a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by myfonj** [comment]
Same observation with commands from File Utils ext:
- ![](https://user-images.githubusercontent.com/1761395/52554683-dc67db80-2de7-11e9-9143-024d476ce433.png)
(`move file` input yields "no commands matching")
- ![](https://user-images.githubusercontent.com/1761395/52554729-00c3b800-2de8-11e9-9004-a2e3fb011676.png)
(while `file move` correctly finds "File: Move" command)

**Comment by koliyo** [comment]
Aha, yes, it seems like it either matches the extension name (string on the left of `:`), or command name (right of `:`)

So if I search for `search note` I get a match.

![screenshot 2019-02-11 at 10 51 55](https://user-images.githubusercontent.com/770348/52555883-3ae28900-2deb-11e9-8403-3a107acf79c0.png)


But I really want to use the combination! That is, fuzzy matching the name of extension + part of the command name.This interaction model is very useful

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/27317, https://github.com/Microsoft/vscode/issues/1964
