### ISSUE TITLE
VS Code keeps crashing after update

### ISSUE THREAD

**Issue by iamawhe** [Microsoft/vscode#68398]
Hello guys, VS Code had forcefully hanged and restarted like 7 times the last 3 days after update ships on Feb 03, 2019 and like 2 times the past 3 hours. 

I don't know if any person experienced same issue.

Any suggestions?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by iamawhe** [comment]
Okay. I've done the installation and would be waiting for the next possible crash report. Thanks

**Comment by bpasero** [comment]
Thanks

**Comment by iamawhe** [comment]
[Code__PID__27044__Date__02_12_2019__Time_12_43_08PM__348__Log.txt](https://github.com/Microsoft/vscode/files/2855651/Code__PID__27044__Date__02_12_2019__Time_12_43_08PM__348__Log.txt)

Hello @bpasero , though I kind of noticed the crash happens when am versioning with git in the inbuilt terminal. Kindly find here attached, is the latest of the crash report.
