### ISSUE TITLE
crash after multi-search-replace, dismissing last replace in list

### ISSUE THREAD

**Issue by retepaskab** [Microsoft/vscode#68399]
Issue Type: <b>Bug</b>

1, search and replace with Ctrl-shift-f
2, view each occurence one-by-one in the result list by clicking on them
3, accept or reject each occurence using the icons in the list
4, crash when the list gets empty

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|30.91GB (19.68GB free)|
|Process Argv|c:\Dev\BPet-22Main\Sources\ArchiCADLibrary\INT\Object Library Superset\4. ADD-ON LIBRARY\Grasshopper\Grasshopper Sweep object.xml|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.2.2
alignment|ann|0.3.0
close-all|ben|1.0.2
tslint|eg2|1.0.42
vs-code-xml-format|fab|0.1.5
vscode-npm|fkn|3.3.0
gdl-xml|pba|1.23.3
guid|kos|0.0.1
vs-color-picker|lih|1.0.0
language-gettext|mro|0.1.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
color-highlight|nau|2.3.0
printcode|nob|3.0.0
relativegoto|ret|0.0.1
perforce|sle|3.1.0
vscode-hexdump|sle|1.7.2
goto-line-ex|xyz|0.0.4

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you explain what you mean by "crash"? I can't reproduce this. Does it happen every time?

**Comment by retepaskab** [comment]
1. open file
2. ctrl-shift-f
3. type something that is in the file, enter
[image: image.png]
4. click on the dismiss button
[image: image.png]

Yes, it happens every time.

Rob Lourens <notifications@github.com> ezt írta (időpont: 2019. febr. 12.,
K, 2:18):

**Comment by roblourens** [comment]
Thanks for the details. It looks like your images were not included. Is there an error message that you see?

**Comment by retepaskab** [comment]
![image](https://user-images.githubusercontent.com/5570057/52695010-af443600-2f6b-11e9-9323-d3d3bac9aaa6.png)
![image](https://user-images.githubusercontent.com/5570057/52695032-b8cd9e00-2f6b-11e9-973f-2f476aec210d.png)

**Comment by roblourens** [comment]
I can repro this with the steps from https://github.com/Microsoft/vscode/issues/68716 using an unsaved file.
