### ISSUE TITLE
VSCode version 1.31.0 - wrong marking in Explorer of currently open file in editor

### ISSUE THREAD

**Issue by kobibentata** [Microsoft/vscode#68394]
- VSCode Version: 1.31.0
- OS Version: Win 10 64-bit

Steps to Reproduce:

1. Open any file in the editor, making sure it is in a visible view of the Explorer pane on the left side.
2. Now pick another file, close to the previous one and open it too. It is crucial to have both files "close" to each other for this reproduction, in order to see them both in the same visible view of the Explorer.
3. Switch back to the first file using CTRL + TAB.
4. You will see both files marked as "current" in the Explorer pane.
5. If you switch back to the second file, the marking works correctly. Switch back again to the first file, and the marking is wrong again...

Expected behavior:
Only one file should be marked as currently open in the Explorer pane at any given time, regardless to the way the user switches between files.

[Illustration of a single file selected in the Explorer pane](https://i.imgur.com/4XSYUSK.jpg)

[Illustration of "double selected" file in the Explorer pane, as described above](https://i.imgur.com/9NQtwfw.jpg)

PS:
I've also checked if this wrong behavior is related to the way a file is opened from the Explorer pane (single or double click), and it's not related to that. It is also not a matter of a certain extension.

**Comment by isidorn** [comment]
Will be fixed as part of https://github.com/Microsoft/vscode/issues/67970
