### ISSUE TITLE
Terminal shown error

### ISSUE THREAD

**Issue by hupo376787** [Microsoft/vscode#68391]
Issue Type: <b>Bug</b>

There is a biiiiiiiiiiiiiiiiiig white space in my terminal

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.22.3
flutter|Dar|2.22.3
xml|Dot|2.4.0
vscode-language-pack-zh-hans|MS-|1.30.2
csharp|ms-|1.17.1
ayu|tea|0.17.0

</details>

**Comment by hupo376787** [comment]
![default](https://user-images.githubusercontent.com/14960168/52551581-06d18d00-2e18-11e9-80a4-fbca52d4b364.jpg)

**Comment by joostshao** [comment]
+1

**Comment by coldens** [comment]
Versión: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Fecha: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/20484707/52586505-af2a2600-2e05-11e9-8eda-761e5d5ffab4.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
