### ISSUE TITLE
No response issue when open large compressed js

### ISSUE THREAD

**Issue by sorrymeika** [Microsoft/vscode#684]

**Comment by egamma** [comment]
Please verify that this isn't the same issue as #94.

If it isn't then please attach the file so that we can reproduce.

**Comment by guan6** [comment]
I have encountered the same problem. vscode trying code Highlight of large compressed js?

My English is not good.

**Comment by egamma** [comment]
duplicate of #139, which is fixed by now

**Comment by guan6** [comment]
Thank you
