### ISSUE TITLE
Unable to update to the latest version

### ISSUE THREAD

**Issue by IcedAnt** [Microsoft/vscode#68404]
![image](https://user-images.githubusercontent.com/27441619/52556809-e391e800-2ded-11e9-94ae-501f780629e8.png)

![image](https://user-images.githubusercontent.com/27441619/52556598-5ea6ce80-2ded-11e9-9b20-3571d4fe1802.png)

[vscode-inno-updater-1549875846.log](https://github.com/Microsoft/vscode/files/2850539/vscode-inno-updater-1549875846.log)
[vscode-inno-updater-1549626528.log](https://github.com/Microsoft/vscode/files/2850538/vscode-inno-updater-1549626528.log)
[vscode-inno-updater-1549879322.log](https://github.com/Microsoft/vscode/files/2850533/vscode-inno-updater-1549879322.log)
[vscode-inno-updater-1549879619.log](https://github.com/Microsoft/vscode/files/2850557/vscode-inno-updater-1549879619.log)

**Comment by af-lra** [comment]
Same here :/
[vscode-inno-updater-1549881744.log](https://github.com/Microsoft/vscode/files/2850694/vscode-inno-updater-1549881744.log)
