### ISSUE TITLE
Python: ImportError: No module named psutil

### ISSUE THREAD

**Issue by ramaagcp** [Microsoft/vscode#68405]
Issue Type: <b>Bug</b>

I could Run the Program in Python Terminal but not under output. The following is the error

[Running] python -u "/Drives/My Drive/Rapid/Python Lab/Head First Python/000.Temp.py"
Traceback (most recent call last):
  File "/Drives/My Drive/Rapid/Python Lab/Head First Python/000.Temp.py", line 1, in <module>
    import psutil
ImportError: No module named psutil

Cod as follows:

import psutil
cpuper = psutil.cpu_percent()
print(cpuper)
memorykb = psutil.virtual_memory()
print(memorykb)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.19.13-300.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3481)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (9.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|1.0.8
vscode-eslint|dba|1.8.0
python-preview|don|0.0.4
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
code-runner|for|0.9.7
python|ms-|2019.1.0
PowerShell|ms-|1.11.0
python-docs|Muk|0.8.3
python|tht|0.2.3
python-extended-snippets|tus|0.0.1

</details>

**Comment by ramaagcp** [comment]
but what extension you are referring to

**Comment by Tyriar** [comment]
@ramaagcp code-runner
