### ISSUE TITLE
PHP / HTML / JS Dim inactive Code

### ISSUE THREAD

**Issue by smika78x** [Microsoft/vscode#68407]
Is there a way to dim inactive code in a .php file? I found something similar with cpp files.
![image](https://user-images.githubusercontent.com/47524364/52560467-bbf44d00-2df8-11e9-9c8c-c3e45233a280.png)
If you click the php-part of the script it changes the highlights.
![image](https://user-images.githubusercontent.com/47524364/52560642-4046d000-2df9-11e9-970a-0f93d064136c.png)
This was possible in a software called phpDesigner8
Any way to do this in vscode?

**Comment by roblourens** [comment]
It's kind of an interesting idea to only syntax highlight the language under the cursor but I think that would be best handled by an extension.
