### ISSUE TITLE
Improve user experience while installing themes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#68408]
Improve user experience while installing themes

**Comment by sandy081** [comment]
![switch theme](https://user-images.githubusercontent.com/10746682/52560692-6a988d80-2df9-11e9-8989-ec0522e423fd.gif)

**Comment by smbkr** [comment]
It would be cool if you could preview themes in the store, maybe with a split view hosting some example code, or even with the files you have open.

**Comment by sandy081** [comment]
@smbkr Please open a feature request for it
