### ISSUE TITLE
[regression]Auto detection of gulp command no more working for user having space in name

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#68413]
- VSCode Version: 1.31.0
- OS Version: Windows 10

Steps to Reproduce:

1. have a system with user home containing a space
2. have some gulp task configured
you will have:
```
Auto detecting gulp for folder vscode-atlasmap failed with error: Error: Command failed: C:\Users\Aurelien Pupier\AppData\Roaming\npm\gulp.cmd --tasks-simple --no-color
'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
```

Does this issue occur when all extensions are disabled?: Yes/No

I think it was introduced by this commit: https://github.com/Microsoft/vscode/commit/272c6827f1e15dea7097c2b73bf9d0752135b7ee#diff-7c470ab4f4141bf44222125e9685fa35

it is now using a global gulp which is installed in user home instead of local one.
The command has never escaped space in path though

**Comment by alexr00** [comment]
Thank you for catching this! The fix will be available in the next Insiders build.

**Comment by roblourens** [comment]
Why are you looking in `appdata/npm - Copy` now?

**Comment by roblourens** [comment]
Ah that was already fixed
