### ISSUE TITLE
Executing task created through api doesn't print "Executing"

### ISSUE THREAD

**Issue by mickeypearce** [Microsoft/vscode#68411]
If you create task through "new vscode.Task()" task api and then execute it with "executeCommand runTask" or "executeTask" it doesn't print "> Executing task: ...." into the terminal as it does when task is created with "tasks.json".

- VSCode Version: 1.31.0 (1.32.0-insiders)
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1.  create task with new vscode.Task()
2.  execute with vscode.commands.executeCommand("workbench.action.tasks.runTask, "taskname"))

If it was an intentional change, maybe an optional parameter for printing "executing task..." to terminal would be beneficial.

**Comment by alexr00** [comment]
Caused by ffab77a9f8d
