### ISSUE TITLE
Run tests in an environment using a user home containing space

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#68414]
it will force to think of enclosing commands with quotes.

**Comment by bpasero** [comment]
@apupier what is the test you would run?

**Comment by apupier** [comment]
> what is the test you would run?

all tests. it is to detect that there is no code using path without putting quotes around it.
What leads me to ask for it is that I think it would have avoided this regression https://github.com/Microsoft/vscode/pull/68418
I also hit similar issue with external extensions (but for these ones you can't do anything, at least easily)

**Comment by apupier** [comment]
As VS Code usage is growing, it will start to reach users that doesn't have hands on their installation and which have user home containing spaces
