### ISSUE TITLE
On closing, prompt to save a file that is not opened sometimes appears, which saves empty file over existing file

### ISSUE THREAD

**Issue by rjones27** [Microsoft/vscode#68416]
I am using version:
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.4.0-142-generic

The extensions I have enabled are:
C/C++: 0.21.0
Python: 2019.1.0

Sometimes, when I close VSCode it sometimes prompts that there are unsaved files, usually ones that I had open recently, but are not open in the window that I am closing. If I click "Save", then it overwrites the existing file with an empty file.

**Comment by bpasero** [comment]
@rjones27 it would be great if you can find reproducible steps around this as this was reported before without clear steps. Does it reproduce with extensions disabled?
