### ISSUE TITLE
collapseExplorerFolders opens highlighted file and doesn't collapse folders

### ISSUE THREAD

**Issue by dvanscott** [Microsoft/vscode#68420]
Issue Type: <b>Bug</b>

1. Set a key binding for `workbench.files.action.collapseExplorerFolders`
2. Open a file nested in a folder
3. Close the file
4. Use the key binding to collapse all explorer folders

The file that was just opened will open and the explorer won't collapse. In the last version, the file would not open and the explorer would fully collapse.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
laravel-model-snippets|ahi|1.0.2
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|0.8.8
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.1.16
better-phpunit|cal|1.3.3
laravel-blade|cjh|1.1.2
vscode-eslint|dba|1.8.0
vsc-material-theme|Equ|2.6.3
php-debug|fel|1.12.6
php-file-types|fet|1.2.1
file-icons|fil|1.0.16
docker-explorer|for|0.1.6
vscode-text-pastry|jkj|1.2.0
php-cs-fixer|jun|0.1.95
vscode-simple-icons|Lau|1.11.0
tailwind-sass-syntax|mac|1.1.1
php-import-checker|mar|0.2.8
dotenv|mik|1.0.1
vsliveshare|ms-|0.3.1151
vetur|oct|0.15.0
laravel-blade|one|1.18.0
advanced-new-file|pat|1.2.0
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
vscode-icons|rob|8.1.0
laravel-artisan|rya|0.0.24
vscode-fileutils|sle|2.13.5
vscode-field-lights|sve|0.0.11
php-docblock-generator|vin|0.0.1
vscode-todo-highlight|way|1.0.4
save-and-run|wk-|0.0.21
city-lights-icon-vsc|Yum|1.1.3

(2 theme extensions excluded)

</details>

**Comment by fotonmoton** [comment]
same here. I use shortcut `ctrl+1` to collapse folders and now this shortcut collapses as before but also opens highlighted file and, I think, this forces explorer to expand back.   [Settings](https://gist.github.com/fotonmoton/154983b038e15461d7054b7cb940a9bd).

VS Code:
```
1.31.0
7c66f58312b48ed8ca4e387ebd9ffe9605332caa
x64
```

System:
```
Linux machine 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by isidorn** [comment]
Great catch, thanks for reporting this.
You can try out tomorrow's vscode insiders which will include the fix for this.
