### ISSUE TITLE
Internal link in addons view show HTML encoded hard to read for humans

### ISSUE THREAD

**Issue by Porkepix** [Microsoft/vscode#68425]
- VSCode Version: Rolling Release 1.31.0
- OS Version: ArchLinux (Rolling Release)

Steps to Reproduce:

1. Go for example on any extension page
2. Hover a link

You'll see the same as the following screenshot displayed in the tooltip:
![screenshot from 2019-02-11 14-27-29](https://user-images.githubusercontent.com/709500/52566513-3bd6e300-2e0a-11e9-8c3a-1b00bc00a097.png)

Does this issue occur when all extensions are disabled?:
STR doesn't seem to be testable in this mode

**Comment by mjbvz** [comment]
This only happens for anchor links. External links seem to work fine
