### ISSUE TITLE
[feature-request] Hide files from Explorer sidebar, but do not exclude them from search or Ctrl-P navigation

### ISSUE THREAD

**Issue by narfanar** [Microsoft/vscode#68427]
Right now we can exclude files from search and/or exploration (the explorer sidebar and the Ctrl-P or Ctrl-E action).

What I'm looking for is a granularity that allows, for example, to exclude `__init__.py` files from the Explorer sidebar but include them in Ctrl-P navigation.

So you can go there when you really need them, but they don't clutter up the interface on the side.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/67168
