### ISSUE TITLE
Refresh Explorer when last refresh is not completed causes crash

### ISSUE THREAD

**Issue by hdomos** [Microsoft/vscode#68424]
I have a folder which is mounted via a samba share, and it takes its time sometimes to refresh.
If I click the "refresh explorer" button and I click it again when it is still refreshing, I get a "window crashed" error and have to reload the whole window to continue.

It worked before version 1.31, now it is broken.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
