### ISSUE TITLE
When deleting on a new line cursor fails to move to last indentation

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#6842]
- VSCode Version:1.1.1
- OS Version: Linux 4.4.0-22-generic

When hitting delete, and the line is blank, cursor should move back to last tab-stop
Steps to Reproduce:

1. Create some code blocks, with each line indented
2. Press enter
3. Press backspace

Issues: cursor moves back only single character, the expected behavior is to move back to previous indentation.

**Comment by alexandrudima** [comment]
This will come out of the box with the May release thanks to @outcoldman in PR #5423

![u0ntokj0xj](https://cloud.githubusercontent.com/assets/5047891/15567047/696efcb0-2324-11e6-835c-1f297fb9756b.gif)

**Comment by rajinder-yadav** [comment]
Nice work :+1:  thanks for getting this in!
