### ISSUE TITLE
Allow extensions to control default expanded state of contributed views

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#68438]
Currently, contributed views are always collapsed when inside core viewlets (explorer, SCM, debug, and extensions), and are expanded by default when inside custom view containers. Extensions being collapsed by default causes discoverability issues for some extensions and some extensions already try to work around this using `reveal` on the tree view.

I propose adding an "expanded" property on the views contribution point that allows extensions to set the default behavior. If not set, the default behavior is the same as now. One thing to note is that if extensions opt-in to expanding, this will cause them to activate on startup if their containing viewlet is open.

**Comment by Rajsmit** [comment]
+1

**Comment by alexr00** [comment]
We have this now!
