### ISSUE TITLE
Installing extensions from command line does not prompt for restart

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6843]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open Code 
2. Install an extension from the command line (e.g. `--install-extension ms-vscode.csharp`)
3. Go back to Code

Does installing from the command line not require restarting Code?

**Comment by Tyriar** [comment]
I took this as a given personally, I guess the CLI could ping the instances to show the popup, not sure it's worth it though.

**Comment by vsccarl** [comment]
For some extensions, for example C/C++, a warning is displayed on Windows saying debugging is not supported. It will not show this message until Code is restarted.

**Comment by vsccarl** [comment]
Also items added on the lower status bar do not show until restarting.

**Comment by joaomoreno** [comment]
I'll leave this unimplemented for now. These flags were introduced for people to automate integrations. They like a way to install extensions programmatically... it's not really meant for more users, sicne they have the in-product experience.
