### ISSUE TITLE
[Feat. req.] Support for iframe selection when debugging

### ISSUE THREAD

**Issue by undavide** [microsoft/vscode#68439]
When debugging with Chrome Dev Tools, it is possible to target a specific `<iframe>`, as [shown here](https://stackoverflow.com/questions/3275816/debugging-iframes-with-chrome-developer-tools):

![](https://i.stack.imgur.com/nR0Cj.png)

It would be useful to have a prop in `launch.json` that specifies the target `iframe`.

Context about my feature request is found in this [StackOverflow topic](https://stackoverflow.com/questions/54628136/vscode-debugger-targeting-an-iframe).

Thank you!

**Comment by roblourens** [comment]
We have been actively working on improving multi-target debugging for the chrome debug extension. Closing this but stay tuned! 

https://github.com/microsoft/vscode-chrome-debug-core/issues/529
