### ISSUE TITLE
Pos1 key not working as expected in git commit message text field

### ISSUE THREAD

**Issue by anschluss80** [Microsoft/vscode#68437]
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Expected behaviour (Windows version):
The cursor should move to the first character of the git commit message field when pressing 'pos1' key. 'End' key is working fine.

Steps to Reproduce:
1. Open a git based project
2. Press 'Ctrl+Shift+G' to switch to Source Control tab
3. Enter something into the message box
4. Press 'pos1' key

Does this issue occur when all extensions are disabled?: Yes

TIA & best regards, 
Alex.

**Comment by joaomoreno** [comment]
What is the <kbd>Pos1</kbd> key? I never heard about such a key.

**Comment by anschluss80** [comment]
Oh sorry, it's the 'home' key (on german keyboard layouts it's labelled 'pos1')..

**Comment by joaomoreno** [comment]
Do you have any keybinding configured to that key?

**Comment by anschluss80** [comment]
Ah yes, I do. Relevant entries from `keybindings.json`:
```json
[
    {
        "key": "home",
        "command": "cursorHome",
        "when": "textInputFocus"
    },
    {
        "key": "home",
        "command": "cursorLineStart"
    }
]
```
I configured this as I like to position the cursor always on editor row 1, instead to the first character in the current line (and to the first row by pressing the key again). 

When I remove the above configuration, the 'home' key works as intended in git commit message text field. Thanks for pointing me to it!
