### ISSUE TITLE
supporting Emacs universal-argument (c-u by default)

### ISSUE THREAD

**Issue by cpryland** [microsoft/vscode#68433]
Before I start digging into how to implement the Emacs universal-argument (c-u), which none of the Emacs packages support and which is painful to lose after 40+ years of Emacs finger habits, including in the macOS built-in text editing support --

http://www.gnu.org/software/emacs/manual/html_node/emacs/Arguments.html

-- it seems to me it would need in-built support in VSCode to work, since it introduces the notion of repeating a following command _n_ times (where the argument is _n_, either implied or typed), whether built-in or added by an extension.

Is there any hope that this could be implemented entirely in an extension? I.e., is there any way for an extension to capture and map the next keyboard command, however invoked, and run it multiple times?

**Comment by alexandrudima** [comment]
Currently, there is no VS Code API to accomplish this.

**Comment by cpryland** [comment]
OK, thanks for the confirmation.

What are the chances of getting this added to the core API?

**Comment by cpryland** [comment]
More discussion here:

https://github.com/tuttieee/vscode-emacs-mcx/issues/59

**Comment by cpryland** [comment]
I think this is actually fairly important for the global product, if you want to fully embrace Emacs users, who form a fairly substantial "alpha user" pack.
