### ISSUE TITLE
Invisible text buttons on delete file form [Closed]

### ISSUE THREAD

**Issue by simone98dm** [microsoft/vscode#68440]
Issue Type: <b>Bug</b>

I installed vscode from the snap store (snapcraft, via "classic" channel), I'm using ubuntu 18.04 with a custom theme called "Arc-Dark".
The problem comes out when I try to delete a file from the side panel: vscode shows the form to confirm the deletion of the file, but the text of the "Confirm" and "Cancel" buttons is not displayed. The buttons work, but the text is invisible.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.44GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>

**Comment by simone98dm** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/ZKYDQ1S/issue.png" alt="issue" border="0"></a>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by simone98dm** [comment]
Well, the problem seems to be solved.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/w0PxNyJ/Screenshot-from-2019-02-11-19-21-10.png" alt="Screenshot-from-2019-02-11-19-21-10" border="0"></a>

**Comment by simone98dm** [comment]
Obviously, I mean "solved" with the new version of Electron. Thank you

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
