### ISSUE TITLE
⌘R chords not working, when integrated terminal has focus

### ISSUE THREAD

**Issue by heihachi88** [Microsoft/vscode#68444]
It's present in insiders build.

- VSCode Version: 1.31
- OS Version: OSX 10.14.2

Steps to Reproduce:

Open integrated terminal and focus it, then use chords ⌘R, Shift+R => you'll see it doesn't open available scripts from package.json. It stucks on `⌘R was pressed. Waiting for second key of chord...`, then i press Shift+R and it just prints "R" in a terminal.

![image](https://user-images.githubusercontent.com/5739191/52583281-6c923900-2e59-11e9-81e7-d5de80f7eb5c.png)

As you can see from a screenshot, i don't have anything else mapped on ⌘R and `When` condition is empty, so it should work when integrated terminal has focus, but it doesn't. It's been working in a previous version, but not in 1.31.

Does this issue occur when all extensions are disabled?: Yes/~~No~~

**Comment by usernamehw** [comment]
You probably need to add command Id to the skipShell commands in Settings:

https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

**Comment by heihachi88** [comment]
Just found an issue with this approach: https://github.com/Microsoft/vscode/issues/63271

**Comment by usernamehw** [comment]
> - editor.action.toggleTabFocusMode
> - workbench.action.debug.continue
> - workbench.action.debug.pause
> - workbench.action.debug.restart
> - workbench.action.debug.run
> - workbench.action.debug.start
> - workbench.action.debug.stepInto
> - workbench.action.debug.stepOut
> - workbench.action.debug.stepOver
> - workbench.action.debug.stop
> - workbench.action.firstEditorInGroup
> - workbench.action.focusActiveEditorGroup
> - workbench.action.focusEighthEditorGroup
> - workbench.action.focusFifthEditorGroup
> - workbench.action.focusFirstEditorGroup
> - workbench.action.focusFourthEditorGroup
> - workbench.action.focusLastEditorGroup
> [...]

You don't need to add all these lines.

**Comment by heihachi88** [comment]
@usernamehw they fixed it already?

**Comment by usernamehw** [comment]
Fixed what, exactly? 

These commands excluded by default (the big list)
`"terminal.integrated.commandsToSkipShell"` from your settings are added to that list.

**Comment by heihachi88** [comment]
@usernamehw i've read, that you needed to paste all these actions in order to override default ones for `commandsToSkipShell`.

**Comment by usernamehw** [comment]
That was before vscode **1.31.0**.

**Comment by Tyriar** [comment]
@usernamehw actually improved that 💪 https://github.com/Microsoft/vscode/pull/66179

See the release notes: https://code.visualstudio.com/updates/v1_31#_improvements-to-commandstoskipshell-setting
