### ISSUE TITLE
Pull request Treeview ThemeIcon returns exception

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#68446]
Issue Type: <b>Bug</b>

when I try to look up the changed files I get this.

![image](https://user-images.githubusercontent.com/30625381/52566180-5f4d5e00-2e09-11e9-9da8-69f65a4459c1.png)

Extension version: 0.4.0
VS Code version: Code - Insiders 1.32.0-insider (7ff2398cfd0776409ff687ce811f1d7ff3375dc8, 2019-02-11T11:40:52.304Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_19132990|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rebornix** [comment]
We can see the same exception when running Find All References, which probably use ThemeIcon as well.

**Comment by rebornix** [comment]
It seems https://github.com/Microsoft/vscode/pull/68121 is the trigger.
