### ISSUE TITLE
Providing translations for Visual Studio Code Language Pack is hell - Please return to Transifex

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#68445]
The current [VS Code translation contribution platform](Microsoft/Localization), hosted on GitHub, is of no use at all:

https://github.com/Microsoft/Localization/issues/43

Please return to Transifex until that platform matures.

**Comment by dbaeumer** [comment]
@danyeh assigning to you.

**Comment by danyeh** [comment]
This is same request. Aldo is the owner. Let's continue follow up there.
https://github.com/Microsoft/Localization/issues/43
