### ISSUE TITLE
Cannot debug Node launch config using "--" to pass args to npm script

### ISSUE THREAD

**Issue by akrantz** [Microsoft/vscode#68443]
Issue Type: <b>Bug</b>

Launch config:

    {
      "name": "Excel Desktop",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run", "start", "desktop", "--", "--app", "excel"]
    },

Because "--" is used so that arguments after it are passed to the npm script, when debugging starts the "--inspect-brk" param is added at the end. It needs to be added before "--".

```
C:\Program Files\nodejs\npm.cmd run start desktop -- --app word --inspect-brk=14771 
error: unknown option `--inspect-brk'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-taskpane@0.0.1 start: `office-addin-debugging start manifest.xml "desktop" "--app" "word" "--inspect-brk=14771"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the office-addin-taskpane@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
prettier-vscode|esb|1.8.1
rest-client|hum|0.21.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.1
debugger-for-edge|msj|1.0.6
vscode-icons|rob|8.1.0
vscode-react-native|vsm|0.8.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by weinand** [comment]
Just try this:
```ts
{
  "name": "Excel Desktop",
  "type": "node",
  "request": "launch",
  "runtimeExecutable": "npm",
  "runtimeArgs": ["run", "start", "desktop"],
  "args": ["--", "--app", "excel"]
},
```

**Comment by akrantz** [comment]
Thanks, that does resolve it.
