### ISSUE TITLE
Can't toggle comment with key binding @ linux mint 17.3

### ISSUE THREAD

**Issue by octohedron** [Microsoft/vscode#6844]
- VSCode Version:

Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:38:00.094Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
- OS Version: Linux Mint 17.3

Steps to Reproduce:
1. Plug in a Spanish keyboard (from Spain, pic below)
2. Try to use the key-bindings to comment (Ctrl + /)

Description:
I'm trying to select text and comment it, which is "Ctrl + /" and it's giving me an info message "For your current keyboard layout press " Ctrl + - ", this is annoying since it's not what I need (Ctrl + /), it doesn't work, and it's also wrong, since "my keyboard layout" works fine (as in / is /) in every application and IDE (tested in more than 20 IDEs and text editors in more than 10 different operating systems)

btw, "/" is the numpad slash in my keyboard, the one on top of the numbers, to the right, not the one on top of the number 7.

This is the exact keyboard
![image of DELL keyboard](http://www.stuartconnections.com/Products/Computers/Peripherals/Keyboards/Dell_J4612/DSC02421bigw.jpg)

key binding (same as default, but trying it anyways)

```
[
    { "key": "ctrl+/",          "command": "editor.action.blockComment",
                                     "when": "editorTextFocus" }
]
```

All I need is to set "comment block" or "comment line" to Ctrl + /, if I'm missing something, let me know.

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) appear to behave correctly for this keyboard layout (at least on Ubuntu, but I believe we are fine on Linux Mint too)

![image](https://cloud.githubusercontent.com/assets/5047891/24254005/1a0d4018-0fe2-11e7-9c2e-cf5f433c1799.png)


---
### Analysis of default keybinding for `editor.action.commentLine`
* `editor.action.commentLine` is bound by default to the key code binding `` ctrl+/ ``
* `` / `` can be produced through one scan code combination: `` Shift+[Digit7] ``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24254259/b55d5058-0fe2-11e7-9bdd-b64c7c859a76.png)
* The key code binding `` ctrl+/ `` is therefore mapped to the scan code binding `` Ctrl+Shift+[Digit7] `` and the `F1` command picker now correctly reflects that:
![image](https://cloud.githubusercontent.com/assets/5047891/24254383/12c5d044-0fe3-11e7-946b-383da0cfa8e0.png)
![image](https://cloud.githubusercontent.com/assets/5047891/24254330/ebc733f2-0fe2-11e7-870e-67d3cff502c1.png)
* That is unfortunate, but correct. We don't ship with keyboard layout specific default keybindings, that is something you can upvote in #1240

---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue. Please double check in tomorrow's insiders build.
