### ISSUE TITLE
Team signin: Unauthorized although TFS credential is valid

### ISSUE THREAD

**Issue by Yeg-A** [Microsoft/vscode#68442]
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393

[Main Instruction]
Visual Studio Code

[Content]

Although VS code is tracking changes from source control, there is a bug preventing it from connecting to TFS (this happened after upgrading to 1.31.0)

[OK] [Copy]

![image](https://user-images.githubusercontent.com/29289853/52580511-86e6fb00-2df6-11e9-9b4a-38af72ed9c2a.png)

Steps to Reproduce:

1. Upgrade to 1.31.0 
2. Try signin in to TFS

Does this issue occur when all extensions are disabled?: Yes

**Comment by peni4142** [comment]
Same for SharePoint, using node-sp-auth

```
		spauth
			.getAuth(url, {
				username: UserName,
				password: password,
				domain: UserDomain
			})
			.then(data => {
				let headers: any = data.headers;
				headers.Accept = "application/json;odata=verbose";
				let requestOpts: any = data.options;
				requestOpts.json = true;
				requestOpts.headers = headers;
				requestOpts.url = uri;
				requestOpts.form = postOptions.form;

				request.get(requestOpts).then(response => {
					this.logSuccess(response);
				}).catch(er => {
					console.log(er);
					}
				}).then(() => {
					console.log("end");
				});
			});
```

**Comment by peni4142** [comment]
Reporting a bug to Microsoft is like hell.
-- Not my bug... Report it to xyz. (Mostly another Microsoft repository. Can't you write a bot for something like that?)

Yeah please reopen this. I have exactly the same code running in a VSCode extension, without VSCode. Without VSCode it is working. Till version 1.30.2 is it working. With Version 1.31.0 it is not working.

In the end, our customer and partners will not update VSCode until it is fixed. And I think that is not in your interest.

**Comment by thezuliano** [comment]
Solved!

My version of Code: 

![image](https://user-images.githubusercontent.com/13154217/52791467-c5272900-3047-11e9-87a2-4a6aa8ee1ca4.png)

Steps to fix:

1)- Open VS Code settings (Ctrl + ,)
2)- Search by **"Proxy"**
3)- Change Http Proxy support from **Override** to **OFF**

![image](https://user-images.githubusercontent.com/13154217/52791674-41ba0780-3048-11e9-8fd3-52b0caf5fae8.png)

:D

**Comment by chrmarti** [comment]
This should be fixed in current insiders builds of VS Code with the Proxy Support setting set to 'override'. Let me know if you still see any issues with that. Download: https://code.visualstudio.com/insiders/

**Comment by erikread** [comment]
I was experiencing this issue. I followed the instructions (set proxy to off) and downloaded the insiders build. While I can now authenticate, either VS Code or the Azure Repos extensions sees all of my local workspaces as server.

**Comment by Yeg-A** [comment]
> This should be fixed in current insiders builds of VS Code with the Proxy Support setting set to 'override'. Let me know if you still see any issues with that. Download: https://code.visualstudio.com/insiders/

There is also another bug associated with v 1.31: https://github.com/angular/vscode-ng-language-service/issues/312#issuecomment-462230536

**Comment by erikread** [comment]
I have downloaded the latest insider build. All of my workspaces are local. For a minute or so VS Code acts like everything is fine then it pops up the error.
![image](https://user-images.githubusercontent.com/2592538/53116143-8c86c400-350d-11e9-9c6e-5abd605bcf4f.png)
![image](https://user-images.githubusercontent.com/2592538/53116178-a58f7500-350d-11e9-8209-4c87a5979990.png)
![image](https://user-images.githubusercontent.com/2592538/53116228-c3f57080-350d-11e9-9ef2-c198a69c472a.png)
[workspaces.txt](https://github.com/Microsoft/vscode/files/2886053/workspaces.txt)
![image](https://user-images.githubusercontent.com/2592538/53116312-0454ee80-350e-11e9-87f9-595271a77823.png)

**Comment by chrmarti** [comment]
@erikread That looks like an issue with the extension, could you check if they have an issue open for this and create one if they don't at https://github.com/Microsoft/azure-repos-vscode/issues ?

**Comment by erikread** [comment]
Normally I would agree with you but I went back to 1.29.1 (October Release) and all is good. Same version of the extension. So, at the very least, it is a combination of changes in the release and something in the extension. There is an open issue for this problem and have added my information.
