### ISSUE TITLE
Proposal: Add "It" word before commit text area

### ISSUE THREAD

**Issue by mazyvan** [Microsoft/vscode#68448]
I think it would be nice if before this line...   
![image](https://user-images.githubusercontent.com/10915753/52584935-0970ba00-2df9-11e9-8ba1-edebadcc0714.png)

there was a simple text saying "**It**" as in some tests frameworks. To force the use of the imperative mood in the git commit subject line

Or maybe "**Go**" could be more precise 🤔 

https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n133

**Comment by joaomoreno** [comment]
"It Message" ?
