### ISSUE TITLE
Debugging NodeJs doesnt highlight lines when breakpoints hit

### ISSUE THREAD

**Issue by danpetitt** [Microsoft/vscode#68451]
Issue Type: <b>Bug</b>

This worked until i upgraded VSCode to latest version.

When i place a breakpoint in a TypeScript file and press F5, the breakpoint is hit, but the line is not highlighted; if I F10 over a couple of statements the highlighted line will start to reappear after a couple of key presses; then it might disappear again.

Sometimes you can sit waiting for ages and then you realise its hit a breakpoint because you have noticed the stack list has appeared; the active file tab hasnt changed to the right file either.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (15.25GB free)|
|Process Argv|D:\Projects\EBS\Pawa API|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
prettier-vscode|esb|1.8.1
vscode-docker|Pet|0.5.2

</details>

**Comment by danpetitt** [comment]
I have downgraded and its working again now, so its certainly something to do with 1.31.0

**Comment by ip** [comment]
I confirm, 1.30.2 works, it occurs for me in a TypeScript project too.

**Comment by mad-it** [comment]
I can also confirm. For me the breakpoint is hit but nothing happends. Call stack is being populated but its not even going to the breakpoint and not loading the variables.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.18.0-15-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 3585)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.48GB (4.67GB free)|
|Process Argv|Projects/Dott/backend/functions/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
vscode-sort-json|ric|1.13.0
code-spell-checker|str|1.6.10
vsfire|tob|1.4.1


</details>

**Comment by weinand** [comment]
When this happens could you please open the "Dev Tools" with the "Toggle Developer Tools" action and see whether there are any errors in the console.

**Comment by mad-it** [comment]
@weinand I just tested it. There are no errors in the console.

**Comment by weinand** [comment]
Please see https://github.com/Microsoft/vscode/issues/68616#issuecomment-463248717
and try whether the workaround to add a `"smartStep": false` helps.

**Comment by johnspurlock** [comment]
seeing this for extension projects in 1.31.1 - the `"smartStep": false` does not help in my case

breakpoints are never hit (become "Unverified Breakpoint" when debugging)

**Comment by danpetitt** [comment]
@weinand Thanks for the info; just trying again so i updated and now its on 1.31.1 and seems to be working again without smartStep change. I will keep checking and if i get it failing again i will try the `smartStep` change

**Comment by danpetitt** [comment]
Just reproduced it on a specific function; disabling "smartStep" worked for me; yay

**Comment by ip** [comment]
`"smartStep": false` didn't help me

**Comment by weinand** [comment]
What debugger are you using?
