### ISSUE TITLE
Workspace Extensions Configuration & Install

### ISSUE THREAD

**Issue by jamiekyle-eb** [Microsoft/vscode#68450]
Right now workspace configurations are limited to editor settings, but it would be great if that was extended to also allow configuration of workspaces:

- Add extensions to a `.vscode/extensions.json` or `*.code-workspace` file
- When user opens workspace for the first time:
	- Check if they have the extensions installed at the right version
  - Prompt them if they want to install the miss-matching extensions
  - Enable/Disable the appropriate extensions

The format could look vaguely like this:

```json
{
  "samverschueren.ava": "^0.6.0",
  "dbaeumer.vscode-eslint": "^1.8.0",
  "esbenp.prettier-vscode": "^1.8.0",
  "mgmcdermott.vscode-language-babel": "^0.0.21",
  "jpoissonnier.vscode-styled-components": "^0.0.25"
}
```

It would be really great if you could specify version ranges to avoid having to update this file all the time.

Combined with workspace settings, you can ensure that developers working in a particular workspace have a really great default setup.

Also combined with #68007, it'd be very easy to ship these configs to teams without causing team members frustration that they cannot further customize their editor.

**Comment by sandy081** [comment]
VS Code already supports workspace recommendations - https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

But we do not support versions. Please go through that feature and update this issue with what is still missing for you with proper use cases.
