### ISSUE TITLE
Problem with ansi color codes with decoration part in debug console

### ISSUE THREAD

**Issue by jabaz** [Microsoft/vscode#6845]
- VSCode Version: 1.1.1
- OS Version: Windows 10 x64

Steps to Reproduce:

In nodejs application, when i use console.log with ansi color codes.

Example, when i use `console.log(\x1b[36m%s\x1b[0m, 'working')`, it works correctly.
![image](https://cloud.githubusercontent.com/assets/13858505/15523170/3295fa1c-2221-11e6-9213-3e8dba93ceaa.png)
But if i use `console.log(\x1b[36;1m%s\x1b[0m, 'working')`, it just prints out **[36;1mworking**.
![image](https://cloud.githubusercontent.com/assets/13858505/15523159/11bc6a60-2221-11e6-9102-1f3f0600d9bd.png)

**Comment by jabaz** [comment]
In windows cmd, when i run same app, it prints:
![image](https://cloud.githubusercontent.com/assets/13858505/15523433/f2b31b9e-2222-11e6-9439-1e3182646500.png)

**Comment by isidorn** [comment]
Yes, debug console currently has limited ansi support.
We recommend using `"externalConsole": true` in your `launch.json` to use the native console for full ansi coloring.

**Comment by jabaz** [comment]
I know that I can use external console, but it's not so useful.

**Comment by dzearing** [comment]
I'd love to see this fixed.

**Comment by DanielRamosAcosta** [comment]
Mee too, specially with those beautiful mocha reporters... 😢

**Comment by isidorn** [comment]
Accepting PR to fix this
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L285

**Comment by isidorn** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/38981
Thanks a lot @dyc3
