### ISSUE TITLE
Sometimes it's hard to quickly tell which section is active in the main panel

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#68453]
Since the only way to tell is a slight color difference, I've found myself several times not being sure which section is active, usually to close it. Perhaps this could be implemented in a more effective way, maybe apart from a color difference have some other subtle artifact on the active one.

**Comment by tigerhawkvok** [comment]
Stumbled across thins and just thinking out loud here, maybe something simple like a optional n% opacity reduction would do the job?

**Comment by misolori** [comment]
This is slightly similar to #75435 but not the same. I think we can slightly tweak the opacity of active/inactive elements in the panel. @isidorn @sandy081 @Tyriar thoughts?

Current
<img width="357" alt="image" src="https://user-images.githubusercontent.com/35271042/66418203-6f2c3a80-e9b6-11e9-9897-7e94cd0b215c.png">

Proposed
<img width="378" alt="image" src="https://user-images.githubusercontent.com/35271042/66418066-25dbeb00-e9b6-11e9-8c54-5484171b53c7.png">

**Comment by Tyriar** [comment]
👍 for underline, make sure the inactive items pass the WCAG AA contrast though.

**Comment by misolori** [comment]
@Tyriar inactive items would be `#878787` so they pass:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/35271042/66423442-9851c880-e9c0-11e9-8474-f88fe2ea07b7.png">

**Comment by isidorn** [comment]
LGTM

**Comment by misolori** [comment]
Made the border have the same color as active foreground text, this aligns with the Settings UI:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/35271042/66599418-07155a00-eb58-11e9-8150-ef9ba302fb0f.png">
