### ISSUE TITLE
Simple Variable Substitution for Debug and Tasks

### ISSUE THREAD

**Issue by richardenelson** [Microsoft/vscode#68454]
I'd like to define simple key:value pairs in the launch.json and use them. Here's an example of what that might look like if I wanted to add `myCustomVar` to all my URLs:

```
{
    "version": "0.2.0",
    "myCustomVar": "my_value",
    "configurations": [
        {
            "name": "Page 1",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/page1.html?customVar=${myCustomVar}",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/dev"
        },
        {
            "name": "Page 2",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/page2.html?customVar=${myCustomVar}",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/dev"
        }
}
```

For our usage, workspace settings (e.g. *.code-workspace) aren't allowed to be committed to project repos.  Folder settings (e.g. [root]/.vscode/settings.json) can't be reference through ${config:...}.  Also, it seems to make more sense to have it in the launch.json anyway.

**Comment by weinand** [comment]
You can already use environment variables for that e.g. `${env:myCustomVar}`.

**Comment by richardenelson** [comment]
Thanks, that tells me how to retrieve an environmental variable, but...

How do you set/define the environment variable?  Ideally, variables would be set once outside of the `configurations`, so they could be used in multiple configurations.

The only documentation I can find on setting them seems to be for node apps for each individual configuration.  And this is for chrome (web).  The following doesn't work:

```
        {
            "name": "Page 1",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/page1.html?customVar=${myCustomVar}",
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/dev",
            "env": {
                "myCustomVar": "my_value"
            }
        },
```
Thanks!

**Comment by weinand** [comment]
Typically you set env variables for your shell either via your login profile automatically or manually in your shell. This approach ensures that the launch.json or task.json do not contain the env var values and can safely checked into the repository. 

Setting env vars for node.js (as you try to do in the launch config from above) cannot work because the env var value is needed for the substitution process **before** node.js is actually started.
