### ISSUE TITLE
Files to exclude being ignored

### ISSUE THREAD

**Issue by shaehn** [Microsoft/vscode#68459]
Issue Type: <b>Bug</b>

It appears that node_modules folder is still being searched even with the  exclude pattern set in user settings set at **/node_modules.  I searched for the word DEVELOPER and was getting hits in files under the node_modules folder.

Hmm... this appears to be similar to #46718

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2660)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.99GB (7.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
alignment|ann|0.3.0
solargraph|cas|0.19.3
rainbow-csv|mec|1.0.0
debugger-for-chrome|msj|4.11.1
ruby|reb|0.21.0
vscode-icons|rob|8.1.0

</details>

**Comment by imcotton** [comment]
This happens on v**1.31.1** as well.

**Comment by burtek** [comment]
Same here.
![image](https://user-images.githubusercontent.com/2940958/53005569-d13e2c80-3433-11e9-8cd1-b3266d88b8dc.png)
![image](https://user-images.githubusercontent.com/2940958/53005450-963bf900-3433-11e9-9da7-897403d4b650.png)

**Comment by roblourens** [comment]
@burtek you have toggled off the button to use exclude settings, please click the button in the "files to exclude" box.

Others please check whether you've done the same. Or see the wiki page for troubleshooting tips https://github.com/Microsoft/vscode/wiki/Search-Issues

**Comment by imcotton** [comment]
@robertohuertasm 

By changing the setting of `search.quickOpen.includeHistory` from **default** `true` to `false` fixed issue to me, so my reproduction were:

1. Leaving `search.quickOpen.includeHistory` as default setting as `true`
1. Open one file manually which in the excluding list (e.g.: `node_modules/foobar/dist/index.min.js`)
1. Close that tab
1. Bring up **Quick Open view** and searching for `index`
1. `node_modules/foobar/dist/index.min.js` shows up in the list of quick open as recently opening

I recall that **step 5** was not the case in any of previous versions, seems behavior changed a little here.

**Comment by shaehn** [comment]
@burtek That was indeed my problem. The interface is subtle, different from what I have encountered elsewhere. Usually one expects a check mark somewhere, as opposed to a lightly colored rectangle to indicate on/off.
