### ISSUE TITLE
--diff command line support uri's

### ISSUE THREAD

**Issue by chadgrant** [Microsoft/vscode#68466]
Would like to re-use the awesome vscode diffing and would like to be able to:

`code --diff http://mysite.com/config1.json http://mysite.com/config2.json`

Currently --diff doesn't appear to support uri's

**Comment by aeschli** [comment]
We don't support opening `http://` and `https://` uris from the command line, but it's actually possible to write an extension that allows to does that by providing a [file system provider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider) for these protocols.
When that is present you could use

`code --diff --file-uri http://mysite.com/config1.json --file-uri http://mysite.com/config2.json`
