### ISSUE TITLE
Debugging with smartStep disabled still shows frames labeled as "skipped by smartStep"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#68464]
Forked from https://github.com/Microsoft/vscode/issues/68127

- Disable smartStep in a node launch config
- Debug async/await code
- See that non-sourcemapped frames are still grayed out and labeled as "skipped by smartStep"

**Comment by roblourens** [comment]
Verification steps: 

- Clone https://github.com/roblourens/repro65025
- Disable smartStep in the launch config
- Debug and verify that frames are not grayed out as "skipped via smartStep"

**Comment by cnshenj** [comment]
@roblourens I see the changelog of 1.31.1 says #68464 is fixed. But this is what I'm seeing:

Version: 1.31.1 (system setup)
Launch.json:
```
        {
            "type": "chrome",
            "request": "launch",
            "name": "Client",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*"
            },
            "smartStep": false
        }
```
![grayed call stack](https://user-images.githubusercontent.com/8441956/52693674-310c7300-2f1c-11e9-8b07-bb4b27b00653.PNG)

**Comment by roblourens** [comment]
What do you see if you hover the filter-box.tsx row?

**Comment by roblourens** [comment]
I haven't released this for the chrome extension yet, I'll do that now.
