### ISSUE TITLE
As of 1.31.0, data we store in Memento storage is being deleted.

### ISSUE THREAD

**Issue by HenokAddis** [Microsoft/vscode#68468]
- VSCode Version: 1.31.0
- OS Version: 19h1_release
Details: 
This issue seemed to be super transient during a VSCode upgrade. Perhaps they were migrating the memento storage?? For whatever reason, we cannot reproduce this.

Related bug in Windows: 
[Bug 20461987:](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/20461987) Stored razzle configurations are not being found

Steps to Reproduce:
1. Upgrade VSCode to 1.31.0
2. Default configurations in WAVE are deleted

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
@HenokAddis it is true that we migrated (workspace) storage in 1.30 and we stopped doing so in 1.31 because we had 8 weeks of migration support out there with version 1.30. Are you saying you see this when updating from 1.29 to 1.31?

**Comment by HenokAddis** [comment]
@bpasero To clarify further, the reports we have see are only with the *first* launch after 1.31.0 install, it says “configs not found”, but it didn’t reoccur on subsequent reloads of the window. Our repro and user telemetry showed this happening from 1.30 to 1.31.

What does it mean that the team has stopped migrating storage in 1.31?

**Comment by bpasero** [comment]
@HenokAddis ok so that sounds like only the update from 1.30 to 1.31 means storage got lost, but is afterwards persisted.

> What does it mean that the team has stopped migrating storage in 1.31?

We updated to a new storage solution end of November and did migration until 1.31. However this would mean it would happen when going from 1.29 to 1.31 and not 1.30 to 1.31.

If you can provide a test case on a hello world extension then I can check. But since this issue seems to be gone after the update to 1.31 it is probbaly hard to pin down.

**Comment by HenokAddis** [comment]
I have a user that hits this issue on subsequent launches of VSCode 1.31.0 and can follow-up if we have any information we can pull from his machine. I cc-ed you on the thread with the issue for FYI and added our team to help investigate.

**Comment by GabeDeBacker** [comment]
What I am seeing appears to be a string casing issue with the SQL lite database being used to store the global storage.

Assuming the migrated new pattern is storing the state here:
%USERPROFILE%\AppData\Roaming\Code\User\globalStorage

What I am seeing is that the keys in the database have both (notice the casing):
**"Microsoft.vscode-nmake-tools"**
and
**Microsoft.vscode-nmake-tools**

The correct full-identity of our extension is
**Microsoft.vscode-nmake-tools**

I have verified that we have not changed the "publisher" casing in our package.json, and none of the code that is setting values here has changed.

I've noticed a "toLowerCase" call in:
src\vs\workbench\api\node\extHostExtensionService.ts

Is this recent?

**Comment by GabeDeBacker** [comment]
@sandy081 - Any chance this is related to your recent changes?

**Comment by bpasero** [comment]
@GabeDeBacker yes your analysis sounds about right, unfortunately the migration was not able to account for extensions that use upper case. I was not aware Microsoft was publishing with uppercase, sorry for that.

Can you please let me know if you still see issues AFTER the update?

**Comment by bpasero** [comment]
@GabeDeBacker ah, so this is about `globalStorage` and not `workspaceStorage`. In that case, there is indeed a migration step between `1.30` and `1.31` that is still active. As you already figured out from the source code we do some tricks to find out the valid storage keys to migrate. Previously with our old storage solution (`localStorage`), all keys were lowercased when stored and as such, we need to lowercase the key to find it in the old data. However, the new storage solution is not lowercasing keys and as such we do store the actual value with proper casing back to the new store.

I just did a quick test to see if data is migrated properly and I think it is. Here is what I did:
* use VSCode 1.30 that still used the old storage format
* create a simple hello world extension with `publisher: Microsoft` and `name: vscode-nmake-tools`
* use `context.globalStorage.update()` to store a simple key/value
* open VSCode 1.31 on that same home directory 
* find the key stored with the proper casing `Microsoft.vscode-nmake-tools`

So I conclude that the migration was OK.

PS: when migrating we do preserve the previous localStorage DB in a file called `file__0.vscmig` in the user directory. It would certainly be possible to migrate the data out of that backup to the new solution, e.g. by using a tool such as SQLiteBrowser (https://sqlitebrowser.org/). If the data is not critical, I would be interested in getting hold of such a DB to test the migration.The data dir on Windows is `C:\Users\<username>\AppData\Roaming\Code\Local Storage`

**Comment by saqadri** [comment]
Thanks for looking into this @bpasero! All of our devs ran into this when updating from 1.30 to 1.31, and we have started seeing reports from various users as well, so trying to figure out what happened.

As requested, I've attached the contents of the Local Storage folder from my Code AppData. The zip also contains my globalStorage.vscdb which shows that migration didn't succeed for `microsoft.vscode-nmake-tools`. In it there are 2 entries of interest:

- `microsoft.vscode-nmake-tools` <-- this contains the correct contents, but doesn't seem retrievable by our extension anymore, and
- `Microsoft.vscode-nmake-tools` <-- this doesn't contain anything yet, and this was *not* created by the migration code (our extension saves some state on each run, and so I believe this entry was created when it couldn't find the previous entry, and so went on to save whatever empty state was present in the session).

This is how we interact with the storage API:
For retrieval:
`const savedSettings: RazzleConfigurationSettings[] | undefined = await extensionContext.globalState.get<RazzleConfigurationSettings[]>("nmake.saved.razzleConfigurations");`

For update:
`this.extensionContext.globalState.update("nmake.saved.razzleConfigurations", razzleConfigurationSettingsList);`

And here's a snippet of our `package.json`:
`{
    "name": "vscode-nmake-tools",
    "displayName": "WAVE For VS Code",
    "description": "Provides NMake support in VS Code.",
    "version": "1.0.0",
    "icon": "resources/cosine_transparent_reflection.png",
    "publisher": "Microsoft",
    "enableProposedApi": true,
    "preview": true,
    "private": true,
    "engines": {
        "vscode": "^1.31.0"
    },
...`

We haven't touched the `publisher` field at all. We have updated our Node/vscode dependencies recently (from 1.30.2 to 1.31.0). You can [see the entire file here](https://microsoft.visualstudio.com/DefaultCollection/ES.SCM/_git/nmake.tools?_a=contents&path=%2Fclient%2Fpackage.json&version=GBmaster).

Please let me know if there's anything else I can provide to help with the investigation!

[State.zip](https://github.com/Microsoft/vscode/files/2861702/State.zip)

**Comment by bpasero** [comment]
@saqadri @GabeDeBacker how do I find your extension on the marketplace?

@sandy081 when installing extensions, are we lowercasing the publisher and extension name on disk? Or do we preserve the exact casing?

**Comment by sandy081** [comment]
It is lower cased/

**Comment by bpasero** [comment]
@sandy081 thanks

@saqadri @GabeDeBacker this is the explanation for the issue. Since we lowercase all extensions, the migration code fails to properly restore the original case of the extension. Unfortunately at the place of the migration I do not have access to the real case of the extension. 

@sandy081 is there any way I can get the real case of extension [here](https://github.com/Microsoft/vscode/blob/3d662dd0e1eb1e89e3dd10c3235a8f9a87f58e53/src/vs/platform/storage/node/storageMainService.ts#L167). Currently I just loop over the directories of the extension home path.

**Comment by sandy081** [comment]
You have to read the `package.json` of the extension to get the identifier

https://github.com/Microsoft/vscode/blob/9ef682db65812bfbd5c45cc4472db73eb1855ba0/src/vs/platform/extensionManagement/node/extensionManagementService.ts#L780-L796

You have to be careful if you read extensions by yourself, that there could be two different versions (folders) for the same extension. 
Why can't you use `IExtensionManagementService` to read extensions? It lies in Shared process.

Also, why do you need the real case ?

**Comment by bpasero** [comment]
@sandy081 I am in the electron-main process, I am migrating extension global state from local storage to the SQLite DB and we used to lowercase all keys in the old solution. Now in order to migrate properly I have to know the real value of the extension storage ID which is case sensitive.

**Comment by saqadri** [comment]
@bpasero with regard to where to find our extension, it's internal Microsoft (so it's not on marketplace); you should be able to install it using the folllowing:
https://osgwiki.com/wiki/WAVE_VSCode#Installation

**Comment by saqadri** [comment]
Also, if we wanted to unblock our users before the next VSCode update, what would you recommend as a workaround?

We have considered a couple of options:
- implement a one-time migration from the old db entry to the new one by directly accessing the sqlite db.
- lowercase our publisher name to "microsoft" (don't know of unintended side effects of this).
- any other options?

**Comment by bpasero** [comment]
@saqadri as a fix for our next release I will push a change to explicitly support the migration for extensions that use uppercase letters in their extension publisher or name. However, this will not help your existing users. For those I cannot really offer a fix from our end because once the migration was done, I would somehow have to merge the old data with the new data.

You can probably just copy the code from https://github.com/Microsoft/vscode/blob/1ae6aaa/src/vs/platform/storage/node/storageMainService.ts#L237 to get going and find your data. The location of that data is:
* Windows: `C:\Users\<name>\AppData\Roaming\Code\Local Storage\file__0.vscmig`
* macOS: `/home/<name>/.config/Code/Local Storage/file__0.vscmig`
* Linux: `/Users/<name>/Library/Application Support/Code/Local Storage/file__0.vscmig`

**Comment by bpasero** [comment]
I pushed a change that will take care of migrating well known extensions and publishers. This will go out first week of March.

**Comment by bpasero** [comment]
**To verify:**
* write a extension with "Microsoft" as publisher (in package.json)
* use storage APIs to store data (see https://github.com/Microsoft/vscode/issues/68468#issuecomment-463104921)
* install the extension into VSCode version 1.29 or older
* verify your data is there
* install the extension into VSCode insiders and open the same user data dir
* verify your data is still there
