### ISSUE TITLE
Highlight URLs without traditional TLDs in Terminal

### ISSUE THREAD

**Issue by TimoSta** [microsoft/vscode#68475]
In our local network, we run some servers on custom domains, e.g. GitLab under something along the lines of `http://company-gitlab/`, without a traditional TLD.

Those URLs currently don't get highlighted in the integrated terminal, and have to be copied to a browser manually.

It would be very helpful to make such links clickable, like other URLs are.

**Comment by Tyriar** [comment]
Tracked in https://github.com/microsoft/vscode/issues/21125
