### ISSUE TITLE
Markdown preview fenced code block syntax language highlighting of JavaScript is broken beyond simple examples

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#68470]
Issue Type: <b>Bug</b>

Markdown preview fenced code block syntax language highlighting of JavaScript is broken beyond simple examples.

<pre>
```js
async function fetchMyAPI() {
  let url = 'http://something';
  let config = {};
  const response = await myFetch(url);
  console.log(response);
}

useEffect(() => {
  fetchMyAPI();
}, []);
```
</pre>

![image](https://user-images.githubusercontent.com/2301847/52600794-105bf480-2e1a-11e9-8118-4eefaadb3e07.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.8.1
code-spell-checker|str|1.6.10

</details>

**Comment by mjbvz** [comment]
Again, this is highlight.js. It does not highlight function calls or symbols like `=>`. If you put other text the block, you can see that highlighting is still working:

<img width="1067" alt="screen shot 2019-02-11 at 4 46 19 pm" src="https://user-images.githubusercontent.com/12821956/52603651-9ed17580-2e1c-11e9-99b3-a10f0e408c96.png">

**Comment by joshunger** [comment]
@mjbvz gotcha, is there a way to toggle vscode so the markdown preview closely resembles GitHub? The current markdown preview just doesn't work well.

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview It however also uses highlight

Extensions can contribute custom syntax highlighters for the markdown preview if you would like to use a different code highlighter: https://code.visualstudio.com/api/extension-guides/markdown-extension
