### ISSUE TITLE
Search's Collapse All and Clear Search Results Buttons Swapped Places

### ISSUE THREAD

**Issue by jeffgabhart** [Microsoft/vscode#68472]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Edit > Find in Files
2. See order of buttons (Refresh, Clear Search Results, Collapse All)
![image](https://user-images.githubusercontent.com/2814/52601015-2621e780-2e23-11e9-9afd-93640e8b7e73.png)

Expected:
The previous order was Refresh, Collapse All, Clear All Search Results
Here is a screenshot from the November 2018 release notes
![image](https://user-images.githubusercontent.com/2814/52601109-56698600-2e23-11e9-9ea7-51ce4c6bc630.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 6.1.7601

I mean, I'm sure I will get used to this and it's not that big of a deal, but I've been immediately clearing all of my searches since the 1.31.0 release. :angel:

**Comment by roblourens** [comment]
Yeah, this was on purpose to try to match some other places where those buttons appear. Sorry for breaking your muscle memory.
