### ISSUE TITLE
Debugger call stack sometimes is missing frames with no "Load More Stack Frames" button

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#68474]
- VSCode Version: 1.31.0
- OS Version: Windows 10

Steps to Reproduce:

1. Attach the debugger to some process. I used the C/C++ to attach and attached to Microsoft.VSCode.Cpp.Extension.exe.
2. Pause the debugger while certain work is occurring. I have a 100% repro without our code base when completion is being computed with large document (sqlite3.c).

Bug: The call stack is incomplete (with 15 missing stack frames) with no "Load More Stack Frames" button.

The call stack looks like:
![image](https://user-images.githubusercontent.com/19859882/52601183-c9b6cc00-2e12-11e9-89d0-cfa2522092a7.png)

And it's missing the frames in the image below (the bottom stack frame in the above image is the same as the top stack frame in the image below).

![image](https://user-images.githubusercontent.com/19859882/52601219-e5ba6d80-2e12-11e9-8074-db5c24d81c44.png)

Does this issue occur when all extensions are disabled?: Yes, but requires the C/C++ extension to debug -- the C/C++ debugger team doesn't think it's their bug.

**Comment by sean-mcmanus** [comment]
This is not a duplicate of that vscodebot reported issue.

**Comment by isidorn** [comment]
I can not reproduce this when debugging node.
Can you reproduce with latest vscode insiders?
If yes, put a breakpoint [here](https://github.com/Microsoft/vscode/blob/275d2a02ca922738b58cea7dbf9dce229ea75f21/src/vs/workbench/contrib/debug/electron-browser/callStackView.ts#L658) and try to figure out why the `ThreadAndSessionIds` object is not added to the array. That object will be converted to the Load More Stack Frames button in the UI.
