### ISSUE TITLE
When creating a folder named 'icons' it's automatically git ignored / greyed out 

### ISSUE THREAD

**Issue by jcohenho** [Microsoft/vscode#68476]
- VSCode Version: 1.31.0 (1.31.0)
- OS Version: Mac OS High Sierra 10.13.6 

Steps to Reproduce:

1. create a folder named `icons` anywhere in project
2. Folder automatically greys out as if its defined in a .gitignore file

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Please run this command in your repo: https://git-scm.com/docs/git-check-ignore
