### ISSUE TITLE
导航树设置缩进，再次打开后不能生效

### ISSUE THREAD

**Issue by heimii** [Microsoft/vscode#68478]
打开设置，选择工作台-->外观，找到 Tree: Ident, 在下面的输入框中输入缩进的值，比如 16。保存后关闭 vscode 再次打开，节点的缩进又恢复到默认状态。

**Comment by bernie-ning** [comment]
> 打开设置，选择工作台-->外观，找到 Tree: Ident, 在下面的输入框中输入缩进的值，比如 16。保存后关闭 vscode 再次打开，节点的缩进又恢复到默认状态。

还可以中文提交问题，哈哈
