### ISSUE TITLE
Integrated terminal unable to determine cwd on launch

### ISSUE THREAD

**Issue by huijing** [Microsoft/vscode#68488]
- VSCode Version: 1.32.0-insider
- OS Version: 10.14.3

Steps to Reproduce:

1. Was using fisher v2, update to fisher v3 via `curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish`
2. Restart VSCode

I'm not sure how reproducible this error is because it seems like a rather narrow use-case. On load, the terminal's working directory defaults to `/`, however, `ls` lists the default cwd for VSCode, which is `~/Sites`. I am though, unable to navigate within my `~/Sites` because the `pwd` is indeed `/`.

![](https://i.imgur.com/lQwZwyq.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by huijing** [comment]
I tried clean uninstalling vscode and reinstalling but that did not fix the problem.

**Comment by jorgebucaran** [comment]
Does this issue occur if you remove/uninstall your prompt and use something else or the fish shell default prompt?

**Comment by philipposslicher** [comment]
Happening to me as well. The combo of fish + omf + vscode seems to not be working. Only broken with the vscode terminal though, works fine in Terminal and Hyper.

**Comment by huijing** [comment]
No issue if I revert to `bash`. However, after I encountered the issue, even removing fisher and just using fish shell alone did not fix the problem.

**Comment by jorgebucaran** [comment]
@huijing Yeah, the issue must be somewhere in your VSCode configuration.

**Comment by alessandrodimarco** [comment]
I'm seeing the same issue but this occurred when I updated `fish` from `3.0.0` to `3.0.1`. I was already using fisher 3. Now every time I open the terminal the cwd is `/`.

**Comment by jorgebucaran** [comment]
It could be fish too, now that it seems more than one person is having this issue. I suggest affected users ask in the official [gitter channel](https://gitter.im/fish-shell/fish-shell) too.

**Comment by faho** [comment]
This is https://github.com/fish-shell/fish-shell/issues/5647.

**Comment by lephuongbg** [comment]
Workaround that I'm using for now:

```json
{
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.shellArgs.linux": ["-c", "exec fish"]
}
```

**Comment by AlekSi** [comment]
fish 3.0.2 with the fix is released (https://github.com/fish-shell/fish-shell/issues/5671) and available in Homebrew. It works for me.

**Comment by huijing** [comment]
I can also verify 3.0.2 resolves the problem. I will close this issue now.
