### ISSUE TITLE
Incorrect path in callstack when two scripts have the same path

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#68480]
While fixing https://github.com/Microsoft/vscode/issues/68321

- Debug adapter sends a callstack where two frames have the same `source.path` but one has a `sourceReference` set and the other does not.
- The callstack formats the row to show the full path instead of just the file name.

![image](https://user-images.githubusercontent.com/323878/52604436-af371f80-2e1f-11e9-958b-45a5b9f77d18.png)

My guess is that this triggers the code that detects identical file names and adds more context to disambiguate, but if they are identical, I guess we should just not do that.

The scenario is that a js script in the runtime is named `foo.ts` and its sourcemapped source is also named `foo.ts`.

The DA doesn't currently send this correctly but if I fix the DA, I encounter this issue.

**Comment by roblourens** [comment]
If you don't understand what I'm talking about I can try to put together a better repro case.

You can probably just modify something to add a sourceReference to a frame that doesn't have it, where another frame has the same source path.

**Comment by isidorn** [comment]
Your assumption is correct, that code is probably to blame.
Here's a code pointer so you can potentially provide a PR that fixes this 
https://github.com/Microsoft/vscode/blob/34cfe460e781a72cb488cd80150d82618b565211/src/vs/workbench/contrib/debug/common/debugModel.ts#L344
