### ISSUE TITLE
Request for "alway on top most" feature in right click context on title bar

### ISSUE THREAD

**Issue by CalosChen** [microsoft/vscode#68482]
Issue Type: <b>Feature Request</b>

On the title bar, I hope that VS code can integrate the "always on front most"  feature in right click menu, just like in cmder and notepad2,  it is more convenient to copy text from browser without hiding the window

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by oliverdrummond** [comment]
This would be really useful for me as well, so I can reduce the amount of Ctrl + Tab :).

**Comment by bpasero** [comment]
This sounds like a feature that can only be done by using a new option in Electron to put the window to the top. We will no longer use new features from Electron to reduce the risk of breaking when we update to newer versions. Closing.
