### ISSUE TITLE
Debugging broken for imported PowerShell modules

### ISSUE THREAD

**Issue by happywino** [Microsoft/vscode#68481]
- VSCode Version: 1.31.0
- OS Version: Server 2012 R2

Since upgrading to 1.31.0 I am no longer able to step-through imported modules in PowerShell.  Previous behavior was that I would set a breakpoint on the call to the module in question and when "stepping into" the call (using F11) the module source would be loaded and I could step through.  New behavior is that I can use F11 to step through the module code but I am doing so "blind", the module source isn't opened, if I opened it previously it is not given focus, if I manually give it focus there is no highlight of the current line and when I hit F11 again the main script window is given focus again.

Setting breakpoints in the open module window doesn't change anything.

I'm using the integrate PowerShell terminal

**Comment by weinand** [comment]
When this happens could you please open the "Dev Tools" with the "Toggle Developer Tools" action and see whether there are any errors in the console.

**Comment by happywino** [comment]
I've never used the Dev Tools before so hopefully I did it correctly, this is all I see in the Console tab;

[Extension Host] debugger listening on port 4614
extensionHost.ts:231 Extension Host
extensionHost.ts:232 Debugger listening on ws://127.0.0.1:4614/33fc9633-232d-4004-818d-e91f2fc619d8
For help, see: https://nodejs.org/en/docs/inspector
log.ts:161  INFO no standard startup: not a new window

**Comment by weinand** [comment]
Most likely this is a duplicate of https://github.com/PowerShell/vscode-powershell/issues/1750 which happens to be a duplicate of https://github.com/Microsoft/vscode/issues/68616.
