### ISSUE TITLE
Built-in terminal super jittery on vertical resize and even disappears sometimes

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#6848]
OS: Windows

1) open the built-in terminal
2) run a command with a whole bunch or output such as 'npm list' or cat a file
3) grab the sash at the top of the terminal and resize
-> the terminal content flickers wildly
It seems the terminal window jumps back and forth between a minimal size and the actual size indicated by the sash.

Here is a [video of the issue](https://www.dropbox.com/s/67iw8agepi75q5h/jitter%20screenrecording.mov?dl=0).

**Comment by Tyriar** [comment]
@kieferrm are you on a VM?

**Comment by kieferrm** [comment]
@Tyriar Yes, I ran the test in a VM.

**Comment by Tyriar** [comment]
@kieferrm anything Chromium-based behaves pretty poorly in a VM I find, `--disable-gpu` or `--disable-direct-write` normally help the problem.

**Comment by kieferrm** [comment]
@Tyriar we should verify that we don't have the issue when not running in a VM. This is the only part of vscode I have experienced issues with running in a VM. Everything else is fast and smooth.

**Comment by Tyriar** [comment]
@kieferrm I've tested the terminal on Windows 10, OSX and various Linux distros and haven't seen anything like that. I worked on a VM for a month or 2 and saw that sort of thing all the time in VS Code, Atom and Chrome.
