### ISSUE TITLE
CodeActionParams#range didn't pass the cursor line when exec source action

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#68487]
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

When exec Source Action, the parameter `CodeActionParams#range` of LSP request `textDocument/codeAction` doesn't regard the cursor line any more, it always starts with line 0 and ends with the last line.

See the screenshot below, click `Source Action` menu at line 6, but the LSP request returns the line 0. The expected value is the cursor line 6. This works in the previous version 1.30.1 (2018 November). Looks like a regression bug.
![image](https://user-images.githubusercontent.com/14052197/52609618-d3930a80-2eb8-11e9-9a65-bc659ebef011.png)

**Comment by mjbvz** [comment]
This was an intentional change requested in #53525. If there is no selection, source actions now expand to the entire document. 

@testforstephen What is your use case?

**Comment by testforstephen** [comment]
One java file could contain multiple classes (inner class, anonymous class). When exec Source Action, for example, `Generate Getter and Setter`, `toString()`, `Override/Implement Methods`, we expect it's targeting to the class near to the cursor position instead of the whole file (the top class). This behavior is both supported by eclipse and intellij.

Besides, source action is a very common feature for java developers. If you remove the mouse context info for source action, it has a big impact on java language server.

**Comment by mjbvz** [comment]
@dbaeumer I'm feeling that we should not be clever for source actions. Can we revert #53525 and leave it up to extensions to get diagnostics for the entire file if they wish, or is there some issue that #53525 is really needed for?

**Comment by fbricon** [comment]
+1 to revert that change, it definitely has a negative impact on the java support

**Comment by dbaeumer** [comment]
@mjbvz As I was pointing in #53525 not having the diagnostics has bad side effects if you try to compute stuff for the whole file. 

The doc clearly says:

```
		/**
		 * Base kind for source actions: `source`
		 *
		 * Source code actions apply to the entire file and can be run on save
		 * using `editor.codeActionsOnSave`. They also are shown in `source` context menu.
		 */
		static readonly Source: CodeActionKind;
```

Should these Java code actions be quick fix actions and no source code actions. May be we need an entry in the menu to make this more clear.

**Comment by testforstephen** [comment]
Put these Java code actions into quick fix, they are possibly confused with the normal quick fix.

Generally Quick-fix appears associated with a particular highlighting (a warning or an error).
For example, when hover at line 6, it shows a quick fix saying "Create getter and setter for 'age'".
![image](https://user-images.githubusercontent.com/14052197/53002436-a53c9e80-3467-11e9-9d63-c7494ecdc8ae.png)

But the Java source actions we provides, such as `Generate Getters and Setters`, `Override/Implement Methods`, they are targeting to a code block (naming a class) and provide bulk operation.
For example, when click the context menu "Source Action..." at line 7, it shows the sub menu "Generate Getters and Setters". This action will bulk generate the accessor methods for all three members. 
![image](https://user-images.githubusercontent.com/14052197/53002979-ed0ff580-3468-11e9-9037-ed742e086660.png)
![image](https://user-images.githubusercontent.com/14052197/53003051-10d33b80-3469-11e9-8fa8-c4e2ae9c84ec.png)

Make all these actions under quick fix, feel like a little weird.

**Comment by dbaeumer** [comment]
Whatever we do I think we need to stay consistent with what we do in regards of range and diagnostics. If we use the selection for the source action the diagnostics can only overlap with the range. Otherwise we have different behavior if something is a source or quick fix action. 

We never clearly specified that code actions should only be computed for the provided range but I know that quite some LS do that. So we need to clarify this for source action or even add a property to the context.

**Comment by mjbvz** [comment]
I think not altering the range is the most consistent (which means reverting #53525). The code API involves requesting code actions at a given position, so whole document source actions—such as organize imports—choose to say that organize imports is available at every position in the file. We do not filter out results at all based on the range, that is left entirely up to the provider

Starting with a selection, a code action provider can choose to access the entire document's diagnostics instead but there is no way to recover the original selection if we discard the selection as we are currently doing.

**Comment by dbaeumer** [comment]
Just to clarify: which diagnostic do you now provide. Only the once around the selection. Right?

**Comment by mjbvz** [comment]
Yes, this now behaves the same as all other code actions: only the diagnostics in the selection are provided
