### ISSUE TITLE
BEM expansion settings

### ISSUE THREAD

**Issue by noahsscott** [Microsoft/vscode#68497]
Hi

I am trying to create standalone elements within existing HTML using BEM naming convention. The desired output would be:

`<div class="block__element"></div>`

but instead I get

`<div class="block block--element"></div>`

Steps to Reproduce:

1. Input `.block__element`
2. Expand using tab

Does this issue occur when all extensions are disabled?: Yes

My syntax settings are as follows:

`{"emmet.syntaxProfiles":  { "html":  { "filters": "bem"}},
    "emmet.preferences":  { "bem.elementSeparator": "__",  "bem.modifierSeparator": "--",  "bem.shortElementPrefix": "-"},}`

Any ideas?

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/52664629-55396700-2ebe-11e9-9e16-085baba555a2.png)

You need to turn **off** the BEM filter:

```
  "emmet.syntaxProfiles": {
    "html": {
      "filters": "html"
    }
  },
```

Read more at https://docs.emmet.io/filters/ and https://docs.emmet.io/filters/bem/.

When you have `bem` filter on (which is default), it'll use logic on this page to create output: https://docs.emmet.io/filters/bem/.

**Comment by noahsscott** [comment]
Thank you!
