### ISSUE TITLE
Restore Ignore Recommendation

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode#68496]
Issue Type: <b>Feature Request</b>

hi
when i Ignore recommendation for some extensions , later i want to see them and install , i dont know witch them is recommendation , sorry for bad english , 

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

**Comment by sandy081** [comment]
You can find all recommended extensions in the extensions view by applying Recommended filter.
