### ISSUE TITLE
FOLDing not working(not even showing)

### ISSUE THREAD

**Issue by emildatcu** [Microsoft/vscode#68499]
Issue Type: <b>Bug</b>

I struggle to activate this feature. it's my second reinstalation, and i;ve also tried to install it on my laptop and it doesn't show... and i've tried also with plugins/extensions, but without success

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (11.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.26

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Are you in the screen reader mode? Folding is not available in it.
![image](https://user-images.githubusercontent.com/6461412/52627691-4353c600-2eb6-11e9-9185-f3b4cdf8f3ec.png)

Otherwise, make sure that `editor.folding` is enabled, and open a document with various levels of indentation.
If you still don't see anything, please add a code sample of a file where you expect folding.

**Comment by emildatcu** [comment]
Hi @aeschli , yes, the setting was turned on from codebase settings...

I've messed my brains trying to figure out what the problem is...
You saved my life :D thanks a lot and have an awesome day
