### ISSUE TITLE
Renaming a file creates an overlay that cannot be closed (it blocks everything)

### ISSUE THREAD

**Issue by nchanged** [Microsoft/vscode#68494]
Issue Type: <b>Bug</b>

Renaming a file creates a dark overlay that cannot be closed, the only way to get rid of it is to restart VSCode.  Similar issue #68361

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-tabs|Tyr|0.2.0
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
shaderlabvscodefree|aml|1.1.3
Handlebars|and|0.4.1
vscode-color|ans|0.4.5
indent4to2|Com|0.1.2
EditorConfig|Edi|0.12.8
prettier-vscode|esb|1.8.1
live-html-previewer|hdg|0.3.0
github-pr|jas|1.0.0
docthis|joe|0.7.1
docomment|k--|0.1.3
vs-color-picker|lih|1.0.0
vue|liu|0.1.5
share|lyu|0.4.4
python|ms-|2019.1.0
debugger-for-chrome|msj|4.11.1
vscode-code-outline|pat|0.2.1
vscode-icons|rob|8.1.0
code-settings-sync|Sha|3.2.4
trailing-spaces|sha|0.2.11
shader|sle|1.1.4
addDocComments|ste|0.0.8
launchterminal|tes|0.4.0
gitblame|wad|2.6.3

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@nchanged can you please provide exact reproducable steps for this? Thanks

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68691
