### ISSUE TITLE
Folder Delete not syncing

### ISSUE THREAD

**Issue by KalDhondup** [Microsoft/vscode#68491]
Issue Type: <b>Bug</b>

case 1: the deleted folder was still showing in the system file explore but not in vs code file explore

case 2: same file i have added in system file explore with copy-replace but not showing in the vs code explore. 

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
@KalDhondup does this reproduce reliably?

**Comment by KalDhondup** [comment]
Hi,

It didn't happened for the second time i tried. May be my system was in the heavy task mode. Sorry any way.

kind regard,
k.d
________________________________
