### ISSUE TITLE
Icons in file explorer disappeared after killing tsserver 

### ISSUE THREAD

**Issue by blurHY** [Microsoft/vscode#68490]
- VSCode Version:1.32.0
- OS Version:win10

Steps to Reproduce:

1. Kill tsserver

Does this issue occur when all extensions are disabled?: Yes

**Comment by blurHY** [comment]
Since there is no suggestions while I'm typeing, I thought there must be something comsuming my cpu and not responding. So I killed tsserver. After restarting, icons in file explorer and on opened files bars doesn't appear.

**Comment by aeschli** [comment]
@blurHY You closed and reopened the VSCode window?
So you are saying there was a icon theme configured before, but after reload it was no longer set. Did it revert to the seti theme, or the no-icon theme?
What was that icon theme?
Can you still see the icon theme in the list of available themes?

**Comment by blurHY** [comment]
I deleted all my configuration files and reinstalled vscode.
