### ISSUE TITLE
Execute function before save on disk

### ISSUE THREAD

**Issue by AtomGrafiks** [Microsoft/vscode#685]
exemple: 
```javascript
vscode.workspace.onDidSaveTextDocument(updateHeader, this, []);
```
updateHeader is call after save but this function update document and set the document on unsaved :/

it's possible to call function before save on disk ?

**Comment by SamVerschueren** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/239

**Comment by jrieken** [comment]
Thanks @SamVerschueren
