### ISSUE TITLE
Syntax highlighting for sql breaks in php after string dot binding 

### ISSUE THREAD

**Issue by blackstormx** [Microsoft/vscode#68508]
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. create a php file
2. write a simple query:  `$children = "SELECT * FROM forum_forums WHERE id =".$id." SORT BY id DESC";`
2. observe the error. 

(no syntax highlighting in SQL after ` $id."`

**no extensions installed. vanilla settings.**

[picture of bug](https://i.imgur.com/SzoxNK8.jpg)

**Comment by roblourens** [comment]
I don't think this is really possible to fix with current grammars. The sql string context just comes from the SELECT at the start.

**Comment by blackstormx** [comment]
> I don't think this is really possible to fix with current grammars. The sql string context just comes from the SELECT at the start.

Impossible is nothing. sql context starts with SELECT? I am not sure what you mean, I wrote $sql = "AND" and "AND" was highlighted blue.

**Comment by blackstormx** [comment]
> I don't think this is really possible to fix with current grammars. The sql string context just comes from the SELECT at the start.

Then just ask your friend from monaco editor department to fix this
