### ISSUE TITLE
Why can only the network address be used for the iframe in vscode

### ISSUE THREAD

**Issue by developers-youcong** [Microsoft/vscode#68500]
Why can only the network address be used for the iframe in vscode?
I opened it locally through the browser, and the display was normal, but the webview in vscode was blank, and the corresponding HTML page could not be seen. But I will be changed to the network address, for example: http://www.youcongtech.com, there is no problem. What is the reason? Is it because of the limitations of vscode or?

**Comment by mjbvz** [comment]
What local address are you trying to load and how are you trying to load it in the webview? Please share some example code

**Comment by developers-youcong** [comment]
example:
<iframe src="index.html" width="300" height="300"/>

That's what I want to load

**Comment by mjbvz** [comment]
You need to say where it is being loaded from: `<iframe src="http://localhost:3000/index.html" width="300" height="300"/>`

**Comment by developers-youcong** [comment]
Mainly in the same directory, in HTML, should be able to see directly ah.

For example, why is it that when I open it with a browser, it appears normal, but it does not appear in vscode?

It shouldn't be the path. Also, does the SRC in the iframe have to be either external or local to a web server?

**Comment by developers-youcong** [comment]
By the way, my webview is not ts but HTML
