### ISSUE TITLE
Open Recent menu is sometimes empty

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#68505]
- reproduces on mac
- open a window
- in the current window, go to File > Open Recent  and pick a different folder
- quickly, while the current window is still loading, press cmd+shift+n to open a new empty window
- quickly go to the File > Open Recent menu when the new empty window is focused

Sometimes, the File > Open Recent list is empty.

**Comment by DanTup** [comment]
I'm seeing this a *lot* lately (also macOS). I very often hit Cmd+Shift+N to get a new window then File -> Open Recent, but the menu is pretty much always blank the first time. I don't know whether it's a new issue or if startup got slower so it happens more, pretty frustrating though.

**Comment by alexandrudima** [comment]
I can reproduce this also on Windows:
- Ctrl+Shift+N
- File > Open Recent
- Oftentimes, the list is empty

![image](https://user-images.githubusercontent.com/5047891/53671001-f6753b00-3c7c-11e9-9b9e-42bbadc86636.png)

**Comment by alexandrudima** [comment]
Thanks for fixing!
