### ISSUE TITLE
Exception popup doesn't appear until navigating to another frame/file then back

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#68503]
This may be related to the changes for #64193 (cc @isidorn). I'm seeing the exception popup not appearing when the top frame has deemphasized source - but if I navigate to another frame (for another file) then back, then it appears.

I've made a repro here:

https://github.com/DanTup/vscode-repro-68503 ([changes from mock debug](https://github.com/DanTup/vscode-repro-68503/commit/dd42455cc0780d9f4997f61270b488fbe84162ff))

It's the Mock Debug project, but I changed it to stop with `reason=exception` when it hits a breakpoint, and returns deemphasized source for the top frame (I also added a column, since the exception popup didn't seem to show at all without it).

Add a breakpoint somewhere in a .md file and run the debugger. When it gets to the breakpoint it'll show "Stopped on exception" in the call stack, but there is no exception popup:

![screenshot 2019-02-12 at 8 56 47 am](https://user-images.githubusercontent.com/1078012/52623599-9de42680-2ea4-11e9-989b-232acc499b23.png)

However, if I navigate to the top stack frame (which has no source, and shows an appropriate message) and then *back* to the second stack frame, then the exception popup appears:

![screenshot 2019-02-12 at 8 56 58 am](https://user-images.githubusercontent.com/1078012/52623615-ac324280-2ea4-11e9-97df-50388c74264d.png)

**Comment by isidorn** [comment]
Thanks for nice repro steps. Try it out in tomorrow's vscode inisders and let us know if the issue is fixed for you.

**Comment by DanTup** [comment]
Super, will do - thanks!

**Comment by DanTup** [comment]
@isidorn Fix looks good, thanks!

**Comment by isidorn** [comment]
Thanks, adding verified label.
