### ISSUE TITLE
Git does not track file name case changes

### ISSUE THREAD

**Issue by bibblebabl** [Microsoft/vscode#68506]
Issue Type: <b>Bug</b>

Git does not track file name case changes. I do not know, maybe it should be so, but the register is very important in many cases and there are cases when it is not fixed and all imports are broken.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
When you rename the case of a file, what does `git status` return?
