### ISSUE TITLE
Cancelling snippet mode should discard added cursors

### ISSUE THREAD

**Issue by randrade23** [Microsoft/vscode#68512]
Issue Type: <b>Bug</b>

I am the author of an extension for a custom programming language and I have contributed the following snippet:

snippetString = new vscode.SnippetString(".REGION ${2:FUNCTION_NAME}\nCREATE.FUNCTION ${1:VOID} ${2:FUNCTION_NAME}(${3:})\n\t${4:}\nEND\n.ENDREGION");

When I press tab to change into the 2nd placeholder, if I move the caret to the right, it breaks out of the snippet and leaves me with two carets in different places, which I can only fix by pressing esc. 

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|11.92GB (3.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

![screenshot_3](https://user-images.githubusercontent.com/2223723/52630609-9af13200-2eb4-11e9-96d2-43e59b463a5a.png)

**Comment by jrieken** [comment]
The problem is that one cursor stays inside a placeholder and that one isn't inside a placeholder...

**Comment by jrieken** [comment]
So, the issue is that additional cursors that were added for repeated placeholders aren't removed. This is actually not easy to fix and I am also not sure if others depends on this behaviour.

**Comment by jrieken** [comment]
Sublime falls back to the primary cursors even when having started with multiple cursors. That could be option here.

**Comment by jrieken** [comment]
Actually, comparing this to SublimeText what happens is: pressing ESC to cancel snippet mode resets all cursor to the primary cursor, arrow-keying out of a placeholder cancels snippet mode *without* resetting cursors. That's contrary to what's stated here but I think it makes more sense, move cursors shouldn't reset them, explicitly cancelling snippet mode should.

**Comment by jrieken** [comment]
I have pushed a change (as described above) that aligns us with the ST behaviour. Have multiple cursor in snippet mode

* use arrow key to move out of a placeholder -> snippet mode ends, cursors stay
* use `ESC` to cancel snippet mode -> snippet mode ends, cursors collapse to single, primary cursor
