### ISSUE TITLE
Project navigator does not refresh automatically

### ISSUE THREAD

**Issue by scssyworks** [Microsoft/vscode#68517]
- VSCode Version: 1.31.0
- OS Version: Mac OS X High Sierra (10.13.6)

### Steps to Reproduce:

1. Create files using terminal using touch command
2. On left side check the project navigator

Does this issue occur when all extensions are disabled?: Yes

### Expected behavior:

File navigator should immediately show the files that were created

### Actual Bahavior:

Created files only show up when refreshed using the refresh button

**Comment by isidorn** [comment]
I can not reproduce this. Can you repro using vscode insiders 
https://code.visualstudio.com/insiders/
