### ISSUE TITLE
Crashes when dismissing unsaved file search result

### ISSUE THREAD

**Issue by GuiRitter** [Microsoft/vscode#68516]
Issue Type: <b>Bug</b>

1. Download latest Insiders version, Windows x64, zip.
1. Open VSCode Insiders.
1. Change terminal to CMD (probably not important).
1. Open the folder of a new project or an existing one (tested with Java and JavaScript).
1. Open one of the project's file.
1. Copy some piece of text.
1. Create a new file.
1. Paste the copied text in the new file.
1. Open Search.
1. Paste the copied text and search for it.
1. In the results, there will be one tree node for the project and another for *Other files*. Dismiss the last one.
   1. If you dismiss by clicking on the `X`, the window crashes.
   1. If you dismiss by right clicking and choosing *Dismiss*, sometimes it crashes, sometimes nothing happens.
   1. If you dismiss by clicking on the node and pressing *Delete*, a warning message shows *Cannot read property 'matches' of undefined*.

VS Code version: Code - Insiders 1.32.0-insider (9441f43636a639aaffa28a9c7e6e36151944c8b3, 2019-02-12T06:16:54.110Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
I think this was fixed already

**Comment by GuiRitter** [comment]
Yep, seems fixed. Thanks!
