### ISSUE TITLE
Find all references doesn't show default export

### ISSUE THREAD

**Issue by khoomeister** [Microsoft/vscode#6851]
- VSCode Version: 1.1.1
- OS Version: Mac 10.11.5
(latest as of May 24 2016)

Steps to Reproduce:

1. Create file `blah.ts` with a default export (e.g. `export default whatever = 123`)
2. In another file, `import someDefault from './blah'`.
3. If you right click on `someDefault` and select "Find all References", should it show the reference to the default export in `blah.ts`?  Right now, it doesn't.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8805
