### ISSUE TITLE
Opening terminal with 'ctrl+~' crashes VSCode

### ISSUE THREAD

**Issue by kmeshavkin** [Microsoft/vscode#68513]
- VSCode Version: 1.31.0 (occurs in 1.32.0 insiders too)
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Open VSCode (doesn't matter if any file or tab is open or not);
2. Quickly press 'ctrl+`' (open and then close terminal). Second press must occur before terminal opened (easier to reproduce on slow machines). VSCode crashes with this error:

`Microsoft Visual C++ Runtime Library

Assertion failed!

Program: ...es.asar.unpacked\node-pty\build\Release\winpty.d11
File: d:\a\1\s\node_modules\node-pty\deps\winpty\...\winpty.cc
Line: 924 

Expression: ASSERT_CONDITION("wp != nullptr && cols > 0 && rows > 0")
 
For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts 

(Press Retry to debug the application -JIT must be enabled)`

After pressing any button it asks to reopen VSCode.

Occurs on latest insiders version without extensions.

**Comment by imorrish** [comment]
I had the same problem. Fixed it by add this to my settings file
{
"terminal.integrated.windowsEnableConpty": false
}

**Comment by Tyriar** [comment]
@imorrish that setting should only do anything on Windows Insiders right now and the default true is to turn on conpty and not use winpty, it's winpty that's causing the error.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by puneetpr** [comment]
> I had the same problem. Fixed it by add this to my settings file
> {
> "terminal.integrated.windowsEnableConpty": false
> }

This fixed the issue, the terminal crashing issue was with Conpty

**Comment by Tyriar** [comment]
@puneet97 make sure you update to the 64-bit build if you're on 32-bit as well, there have been a few reports about that.
