### ISSUE TITLE
When installing extension, the focus can not be dismiss, I only waiting install completely.

### ISSUE THREAD

**Issue by wsg36236** [Microsoft/vscode#6852]
- VSCode Version:1.1.1
- OS Version:Win10

Steps to Reproduce:

1. When i am installing extension, I must wait for it complete, if I change to do another work, the installing will be abort, and I must to do it again.
2.

**Comment by joaomoreno** [comment]
The extension will keep installing while Code is running. If you shutdown Code, it will stop obviously. If you reload your window or open a different folder with it, it will continue installing.
