### ISSUE TITLE
Develop and Debug in a local Docker Container

### ISSUE THREAD

**Issue by turowicz** [Microsoft/vscode#68521]
I would love to have the following experience while developing (.NET Core) apps in VS Code:

https://blog.jetbrains.com/dotnet/2018/07/18/debugging-asp-net-core-apps-local-docker-container/

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
