### ISSUE TITLE
Word wrap disables unexpectedly while writing code

### ISSUE THREAD

**Issue by vincentreynaud** [microsoft/vscode#68522]
Issue type: **Bug**

- VSCode Version: 1.30.2 & older
- OS Version: macOS 10.12.6 & macOS 10.13.6

Word Wrap keeps disabling itself although I have it set ON by default or although i just toggled Word Wrap back on. 

Steps to Reproduce:
Working on a file, i notice the word wrap is off

1. Turn it back on with Toggle Word Wrap / [Alt] + [Z]
2. Continue coding
3. Notice Word Wrap is off again! 

It might get deactivated by another key combination, maybe by [Enter], [Backspace] or else, although these key bindings are not defined for that purpose. In some attempts the toggle is triggered by a simple swipe up/down the trackpad i use.

I didn't find any reports of that issue. I don't understand what is going on, and this is a pretty frustrating bug. In last resort is there even a way to totally disable the Toggle Word Wrap feature to get rid of this issue? 

Does this issue occur when all extensions are disabled?: No

I did a test, the GitLens extension may be triggering this.

**Comment by newtonmunene99** [comment]
Any feedback on this? I'm facing the same issue on Linux

**Comment by vincentreynaud** [comment]
Yes! 
The setting `gitlens.currentline.scrollable` needs to be set to `false`. 
Issue #43940 addresses the problem in vscode, and this one eamodio/vscode-gitlens#290 reports it on the gitlens repo. No plan to change how the setting messes up with the word wrap feature so far.

**Comment by alexdima** [comment]
Let's track in #32856
