### ISSUE TITLE
engines.vscode not respected 

### ISSUE THREAD

**Issue by kjeremy** [Microsoft/vscode#68528]
- VSCode Version: 1.31.0
- OS Version: Win 10

Steps to Reproduce:

1. Manually install extension with `engines.vscode` set higher than your current vscode version
2. It installs fine but shouldn't.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
@kjeremy How are you installing the extension? Is the extension available in the marketplace? After it got installed, can you please open the extension in the installed extensions folder and see the `engines.vscode` value in `package.json`.

**Comment by kjeremy** [comment]
It is not in the marketplace (it's https://github.com/rust-analyzer/rust-analyzer where I bumped up the `engines.vscode`). Installed via `cargo install-code` which runs `code.cmd --install-extension ./ra-lsp-0.0.1.vsix --force`.

Now that I'm looking at this perhaps `--force` is the reason.

**Comment by sandy081** [comment]
I would doubt so. Can you please try without `--force` and see if it fails?
