### ISSUE TITLE
updateWorkspaceFolders doesn't activate folder-specific settings for FileSystemProvider extension

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#68525]
- VSCode Version: 1.31.0
- OS Version: Windows_NT x64 10.0.16299

Testing using [Remote FS](https://github.com/liximomo/vscode-remote-fs) extension (liximomo.remotefs) 0.0.13

Steps to Reproduce:

1. Install Remote FS extension.
2. Add a remotefs.remote entry to User Settings, per the extension's instructions. For my testing I connected to an empty FTP server.
3. Open command palette and run 'Remote FS Add Folder to Workspace'. Choose the connection defined in step 2 above.
4. Once connected, create two subfolders New1 and New2.
5. Use command palette to run 'Preferences: Open Folder Settings'.
6. Add a files.exclude entry to hide New2, i.e.

```
    "files.exclude": {
        "**/New2": true
    }
```
7. Save the change. Observe that New2 correctly disappears from File Explorer, and that /.vscode/settings.json got created on the FTP server.
8. Close the workspace, opting not to save it.
9. Repeat step 3 above. The remote folder is correctly added as the first root of the workspace, but the /.vscode/settings.json has not been applied.

If you now make an insignificant edit to that file and re-save it, the files.exclude takes effect and the New2 folder disappears.

The 'Remote FS Add Folder to Workspace' command simply invokes vscode.workspace.updateWorkspaceFolders
https://github.com/liximomo/vscode-remote-fs/blob/14979554229e3dc01270537578358e4d7285f47c/src/host.ts#L17

Shouldn't that cause the newly-visible folder settings to take effect? Or must some further API call be made?

**Comment by sandy081** [comment]
@gjsjohnmurray May I know if reloading the workspace at step 8, excludes the folders correctly?

**Comment by gjsjohnmurray** [comment]
@sandy081 I'm not clear what you mean by "reloading the workspace". But if at step 8 I save the workspace, close it and reopen it, the New2 folder is correctly excluded.

**Comment by sandy081** [comment]
@gjsjohnmurray May I know if adding/changing other settings work?

**Comment by gjsjohnmurray** [comment]
@sandy081 I can no longer reproduce the original issue so am closing this. Sorry to have wasted your time.
