### ISSUE TITLE
After update VS Code hangs on typing several chars in typescript code

### ISSUE THREAD

**Issue by drweb86-work** [Microsoft/vscode#68536]
We have written the 
Issue Type: <b>Performance Issue</b>

Hello

After recent update my insider version of Visual Studio Code hangs after typing something in typescript files for about 20 seconds. Then it releases and than hangs again after input. It is unusable now.

VS Code version: Code - Insiders 1.32.0-insider (9441f43636a639aaffa28a9c7e6e36151944c8b3, 2019-02-12T06:16:54.110Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    72	 18648	code-insiders main
    0	   207	  5588	   window (● dashboard.state.ts - QuoteBuilder.Frontend - Visual Studio Code - Insiders)
    0	    26	  9592	     searchService
    0	   149	 11592	     extensionHost
    0	   540	 13040	       electron_node tsserver.js 
    0	    16	 18676	         electron_node typingsInstaller.js typesMap.js 
    0	    19	 13104	       "C:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=11592
    0	    46	 17344	       electron_node server.js 
    0	    37	 23412	       electron_node tslintServer.js 
    0	     9	 18860	     electron-crash-reporter
    0	    11	 22356	     watcherService 
    0	     5	 16496	       console-window-host (Windows internal process)
    0	   212	  9500	   window (Process Explorer)
    0	    65	 13752	   window (Issue Reporter)
    0	   347	 14228	   gpu-process
    0	    48	 20028	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● dashboard.state.ts - QuoteBuilder.Frontend - Visual Studio Code - Insiders)
|    Folder (QuoteBuilder.Frontend): 3800 files
|      File types: ts(1200) dll(493) cs(429) html(373) scss(367) xml(234)
|                  pdb(157) resources(95) resx(95) config(91)
|      Conf files: csproj(11) package.json(2) tsconfig.json(1) tslint.json(1)
|                  settings.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
tslint|eg2|1.0.43
vscode-scss|mrm|0.6.2
tsimporter|pmn|1.2.14
typescript-hero|rbb|3.0.0
vscode-icons|rob|8.1.0
stylelint|shi|0.48.0
vscodeintellicode|Vis|1.1.3

</details>
needed data into your clipboard because it was too large to send. Please paste.

**Comment by drweb86-work** [comment]
Window becomes about 40% after typing something.
40%	   207	  5588	   window

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by wildart** [comment]
I had the same issue, `code` hangs in a matter of seconds after start and `code --status` some times would hang as well. After sometime a prompt pops up asking for waiting or closing app. Here is a successful attempt of status info:
```
Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS Version:       Linux x64 4.4.0-142-generic
CPUs:             Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz (4 x 1126)
Memory (System):  3.76GB (0.50GB free)
Load (avg):       0, 0, 0
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  surface_synchronization:      enabled_on
                  video_decode:                 unavailable_off
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %	Mem MB	   PID	Process
    1	   123	 15788	code main
    0	    39	 15795	   zygote
    1	   196	 15839	     window (quiz1.md - Visual Studio Code)
    0	    96	 15867	       extensionHost
    0	   100	 15884	     shared-process
    0	    92	 15827	   gpu-process

```

But after using `--disable-gpu` flag on startup, `code` stopped hanging any more.

**Comment by drweb86-work** [comment]
Hello

I can't execute this command because vs code is hanging. There're 2 processes that hangs

"C:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --type=renderer --no-sandbox --enable-features=FixAltGraph --service-pipe-token=8C863131AE42839404695F23D9F42785 --lang=en-US --app-user-model-id=Microsoft.VisualStudioCodeInsiders --app-path="C:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=8C863131AE42839404695F23D9F42785 --renderer-client-id=4 --mojo-platform-channel-handle=2224 /prefetch:1

"C:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\SERGEY~1\AppData\Local\Temp\vscode-typescript\tscancellation-62cd592ffca271fd318b.tmp* --logVerbosity verbose --logFile "c:\Users\Sergey Kuchuk\AppData\Roaming\Code - Insiders\logs\20190213T095022\exthost1\vscode.typescript-language-features\tsserver-log-7ZrWlr\tsserver.log" --globalPlugins @vsintellicode/typescript-intellicode-plugin --pluginProbeLocations "C:\Users\Sergey Kuchuk\.vscode-insiders\extensions\visualstudioexptteam.vscodeintellicode-1.1.3" --locale en --noGetErrOnBackgroundUpdate

**Comment by drweb86-work** [comment]
![image](https://user-images.githubusercontent.com/29063147/52692587-57aac800-2f75-11e9-8c07-598811ae6e4a.png)

**Comment by drweb86-work** [comment]
Issue is not appearing if to type in field name

**Comment by mjbvz** [comment]
@drweb86-work 

1. Do you see this issue if you disable all extensions?
1. Can you also check the developer console to see if there are any errors. To do this, run the `Developer: Toggle Developer tools` command in VS Code and look in the console section of the developer tools window that opens.

**Comment by drweb86-work** [comment]
Hello

That happens because of TypeScript Importer plugin
https://github.com/starkevin/VSCode-TypeScript-Importer/issues/14

Thanks.
