### ISSUE TITLE
`Enter` doesn't toggle folder collapse in breadcrumbs

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#68539]
Issue Type: <b>Bug</b>

Almost the same as #66566. Only for breadcrumbs.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
@usernamehw does this repro with insiders?

**Comment by usernamehw** [comment]
Yes.

**Comment by jrieken** [comment]
> VS Code version: Code 1.31.0 ([7c66f58](https://github.com/Microsoft/vscode/commit/7c66f58312b48ed8ca4e387ebd9ffe9605332caa), 2019-02-05T22:35:56.624Z)

Really?

**Comment by usernamehw** [comment]
Yes?

**Comment by usernamehw** [comment]
Wait, was it like that before the update? If it's `as-designed` then nevermind.

**Comment by jrieken** [comment]
idk what the design is, forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
The default expand/collapse keybinding is <kbd>Space</kbd>. For some reason, the Explorer decided to also use <kbd>Enter</kbd>, that's an exception.
