### ISSUE TITLE
Searching node_modules is broken

### ISSUE THREAD

**Issue by EddyVinck** [Microsoft/vscode#68534]
I tried searching my `node_modules/bootstrap` folder for "@mixin font-size" and nothing came up, even though the mixin is declared in `node_modules/bootstrap/scss/vendor/_rfs.scss` on line 198.

![image](https://user-images.githubusercontent.com/23434753/52650850-4ddc8280-2eeb-11e9-8a9b-1a20b1a743f9.png)

Please see this issue for more context: https://github.com/twbs/bootstrap/issues/28233#issuecomment-462829227

I was missing some scss imports after updating my Bootstrap version, however the VSCode file-search wasn't showing where the mixins I was missing were defined.

- VSCode Version:
Version: 1.32.0-insider
Commit: 709bf352b12de8284683bef94cb5984129bfc776
Date: 2019-02-08T14:50:08.266Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic
- OS Version: Ubuntu 18.04

Steps to Reproduce:
1. Search node_modules

Does this issue occur when all extensions are disabled?: **Yes**

![image](https://user-images.githubusercontent.com/23434753/52651684-e9222780-2eec-11e9-86bd-45013ec4d02b.png)

**Comment by roblourens** [comment]
The node_modules folder is excluded by the `search.exclude` setting. You can either modify that setting or toggle off the gear button in the `files to exclude` box to ignore that setting.
