### ISSUE TITLE
[read-only]: cannot apply workspace edit for read-only workspace provider

### ISSUE THREAD

**Issue by legomushroom** [Microsoft/vscode#68549]
Reopening https://github.com/Microsoft/vscode/issues/65324 as it still repros and breaks the very important read-only scenario for VS Live Share. Related: https://github.com/Microsoft/vscode/issues/57032.

- VSCode Version: `1.32.0 Insider`, `1.31.0 Stable`
- OS Version: `10.14.2`

Steps to Reproduce:

Use the modified `MemFS` extension: [fsprovider-sample.zip](https://github.com/Microsoft/vscode/files/2852928/fsprovider-sample.zip)

1. Lunch the extension and run `MemFS: Workspace Setup` in the command palette.
2. Run `MemFS: Create Files` in the command palette.
3. Run `MemFS: Start Bash` using VSCode stable(1.31.0).

The extension will try to insert a current timestamp string into the beginning of the `file.yaml` in the root of the workspace with an interval of `1 second`. It logs the same message to the `debug console` for testing purposes. Notice that if the `file.yaml` is open in the background, the edits come through, but if a user makes the file active, the edits no longer applied.

Does this issue occur when all extensions are disabled?: Yes

`Note:` The related pieces in the extension source code marked with `/* EDIT */` markers.

cc. @IlyaBiryukov

**Comment by legomushroom** [comment]
cc @IlyaBiryukov

**Comment by isidorn** [comment]
My fix is not good. Reopening.
Though found the change which caused this. More details https://github.com/Microsoft/vscode/pull/69858

**Comment by jrieken** [comment]
This is the underlying discussion item https://github.com/Microsoft/vscode/issues/57032 which is about the editing-of-readonly-documents-paradox.

**Comment by isidorn** [comment]
@legomushroom can you please verify this is working fine with the latest vscode insiders that has just been released? Thank you

**Comment by legomushroom** [comment]
@isidorn I can confirm that it works as expected in the latest `VSCode Insiders` release, thanks for fixing! 👍

**Comment by isidorn** [comment]
@legomushroom thanks for verifying. Adding verified label
