### ISSUE TITLE
Workbench Color Themes drop down list box is empty

### ISSUE THREAD

**Issue by anthonylamark** [Microsoft/vscode#68544]
Issue Type: <b>Bug</b>

I was trying different workbench color themes and after I changed it 3 times, then the drop down list box went empty (i.e. I cannot change the workbench color theme any more because there are now 0 listed).  I am stuck in the last one I chose.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.85GB (57.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aeschli** [comment]
Did you make ant changes to the installed extension?
Can you verify that the default themes are still installed?
![screenshot from 2019-02-13 09-52-51](https://user-images.githubusercontent.com/6461412/52699097-419d0780-2f75-11e9-867c-a5803cef7ea0.png)

**Comment by anthonylamark** [comment]
Hi,

I did not make any changes to the installed extension.
I have verified that the default theses are still installed.
I was able to work around the bug after noticing that there was "color theme" menu item hanging directly off the "option gear" in the lower left hand corner of the left vertical icon bar.  This showed all the themes and I was able to change my theme repeatedly using this menuitem.

________________________________

**Comment by aeschli** [comment]
Where was the empty color theme drop down list box that you saw?
Settings UI? Settings.json editor?

**Comment by anthonylamark** [comment]
Settings ui

Anthony LaMark
562.221.3079
Squadra Technologies

Sent from phone

________________________________

**Comment by roblourens** [comment]
This is covered by https://github.com/Microsoft/vscode/issues/67452 and https://github.com/Microsoft/vscode/issues/67462
