### ISSUE TITLE
Failed to save 'test.txt': A system error occured (ESPIPE: invalid seek, write)

### ISSUE THREAD

**Issue by roadyyy** [Microsoft/vscode#6854]
- VSCode Version: Version 1.0.0
- OS Version: Ubuntu Linux 16.04, Ubuntu Linux 15.10

Steps to Reproduce:
1. connect to ftp using nautilus
2. open any text file with vs code from nautilus
3. add some changes to the file and save it

When you are trying to save the file you get the error saying: "Failed to save 'test.txt': A system error occured (ESPIPE: invalid seek, write)" and the file on the host gets blanked out.

![screenshot from 2016-05-25 09-59-29](https://cloud.githubusercontent.com/assets/13145179/15527975/653b793e-2261-11e6-933a-b6b311b09b0f.png)
![screenshot from 2016-05-25 10-08-18](https://cloud.githubusercontent.com/assets/13145179/15527976/653bf878-2261-11e6-9d89-2cc1d70b7676.png)

**Comment by bpasero** [comment]
@roadyyy would you be able to write a simple node.js script using `fs.writeFileSync()` API to see if it reproduces with node.js already?

**Comment by roadyyy** [comment]
I'm a noob to the nodejs, but I will try and let you know of the outcome

**Comment by bpasero** [comment]
@roadyyy odd, did you try with node.js 6? please report to them!

**Comment by roadyyy** [comment]
Thanks.

**Comment by friimaind** [comment]
Same problem here with the last version 1.2.0-1465219835
The exact same problem is present on Atom editor https://github.com/atom/atom/issues/2539 and could be related to this NodeJS issue https://github.com/nodejs/node-v0.x-archive/issues/6877

There you can find a possible fix.

**Comment by craft37** [comment]
Same problem.

**Comment by bpasero** [comment]
@roadyyy @friimaind could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by friimaind** [comment]
@bpasero I tried the release code-insiders_1.6.0-1474012735_amd64.deb but the problem is still there :(

- mounted an ftp host via Nautilus
- edit a file test.php with vscode
- save => "Non è stato possibile salvare 'test.php': A system error occured (ESPIPE: invalid seek, write)"

My system is: Dell XPS 9350 with Ubuntu 16.04 LTS with kernel 4.4.0-36-generic

**Comment by bpasero** [comment]
Thanks for giving this a try 👍

**Comment by yanike** [comment]
Has this issue been fixed yet?

**Comment by kentanilsson** [comment]
This issue is more severe. When failing to "seek" the result is a crashed file (empty) in the server. 
Atom 1.13.1 x64 on Ubuntu 16.04 LTS (updated)

**Comment by friimaind** [comment]
Tried without luck with the last version:

> Versione 1.10.2
> Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
> Data 2017-03-08T14:00:46.854Z
> Shell 1.4.6
> Renderer 53.0.2785.143
> Node 6.5.0

Same error "invalid seek" :(

**Comment by cawa-93** [comment]
Same issue if used plain JS in node 
* node - v7.7.4
* Ubuntu 16.04
```javascript
 fs.writeFileSync('/run/user/1000/gvfs/ftp:host=192.168.1.100,user=user/www/example/test', 'string')
```
```javascript
Error: ESPIPE: invalid seek, write
    at Object.fs.writeSync (fs.js:745:20)
    at Object.fs.writeFileSync (fs.js:1326:24)
    at repl:1:4
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
```

**Comment by darginyegor** [comment]
Is anybody going to fix this?

**Comment by cawa-93** [comment]
An error does not occur if you connect via ssh

**Comment by DougTy** [comment]
Just started getting this today, swear it used to work fine before. Any word on a fix?

**Comment by bpasero** [comment]
Are people still seeing this?

**Comment by darginyegor** [comment]
@bpasero tried to reproduce a minute ago, looks like everything's fine.
