### ISSUE TITLE
no source control available

### ISSUE THREAD

**Issue by Andrew199617** [Microsoft/vscode#68542]
Issue Type: <b>Bug</b>

git will randomly stop working forcing me to close videual studio and reopen it so that i can commit and push. Happens about everyday i code. 

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:53:57.820Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.54GB free)|
|Process Argv|D:\Self Taught\React\PortfolioSite|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
turbo-console-log|Cha|1.2.13
githistory|don|0.4.6
vscode-nginx-conf-hint|han|0.1.0
docthis|joe|0.7.1
dotenv|mik|1.0.1
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
vscode-nginx|sha|0.6.0
vscode-js-import|wan|0.15.4

</details>

**Comment by Madmax0647** [comment]
@B-)=-O:-P:-DO:-)(^^)^_^(+_+)

**Comment by joaomoreno** [comment]
Can you reproduce with `--disable-extensions`?
