### ISSUE TITLE
Extensions do not activate when unknown schema is used in the workspace file

### ISSUE THREAD

**Issue by legomushroom** [Microsoft/vscode#68546]
- VSCode Version: 1.32.0-insider [7d0c9e6fa0bedcf71bdae86c02611b65362795a3]
- OS Version: Mac OSx 10.14.2

## Steps to Reproduce:

Use the MemFS extension [fsprovider-sample.zip](https://github.com/Microsoft/vscode/files/2852928/fsprovider-sample.zip):

1. Execute `MemFS: Setup Workspace` in the command palette.
2. Execute `MemFS: Reload Window` in the command palette.
3. Notice that extension host does not activate or keeps reloading, the `activate` callback on the extension is never called.

Does this issue occur when all extensions are disabled?: Yes

## Repro steps 2:

1. Create a VSCode workspace file that uses a custom file system provider schema. (e.g. [Visual Studio Live Share.code-workspace.zip](https://github.com/Microsoft/vscode/files/2857132/Visual.Studio.Live.Share.code-workspace.zip))
2. Take the `MemFS` extension above, set a breakpoint on the first line of the `activate` function, launch the debugging.
3. Open a the workspace file in the experimental instance of the VSCode.
4. Notice that the `activate` callback never gets called, in fact, *not a single extension* is loaded.

**Comment by jrieken** [comment]
Tried with memfs, everything works as expected

**Comment by jrieken** [comment]
cc @sandy081 Is this what you mentioned in todays standup?

**Comment by legomushroom** [comment]
Fixed in today's release, thanks!

**Comment by legomushroom** [comment]
@jrieken reopening this as it starts showing up in the latest insiders again.

**Comment by legomushroom** [comment]
Please let me know if you need any more info on this.

**Comment by jrieken** [comment]
Yes, the provided steps don't reproduce this for me. Can you create a dummy extension that does reproduce this?

**Comment by legomushroom** [comment]
@jrieken I'm surprised both repro steps don't work for you as we have a 100% repro on our side. I've created the minimum possible extension for another repro:

1. Download the [dumb-extension.zip](https://github.com/Microsoft/vscode/files/2915979/dumb-extension.zip), unpack and `cd` into the folder then do `npm i` to install dependencies.
2. Set the breakpoint on the first line in the `activate` function of the `extension.ts` file.
3. Hit `F5`, the experimental instance of VSCode will run and the breakpoint will be hit.
4. Continue execution by hitting `play` in the debugger controls.
5. Do not stop debugger, take workspace file from this zip file and drag-n-drop the file into the experimental instance. [Visual Studio Live Share.code-workspace.zip](https://github.com/Microsoft/vscode/files/2915986/Visual.Studio.Live.Share.code-workspace.zip), the instnace will reload.
6. Notice that the breakpoint in the activate function never gets called anymore after VSCode instance loads with the workspace. In fact, any extension installed will never be activated. This happens with any workspace file that has a virtual file system provider shceme in their root folder.

In case you are confused with the repro steps, I've created the recording of my screen with the repro (minus the installation steps): [video](https://drive.google.com/file/d/1bv41Yb56u39kpjN9rz70OFQYllERhDuE/view?usp=sharing).

Thanks!

**Comment by jrieken** [comment]
Simple steps:

* open workbench
* open the a workspace file with a scheme for which no provider is known (like this https://github.com/Microsoft/vscode/files/2915986/Visual.Studio.Live.Share.code-workspace.zip)

@isidorn the explorer doesn't handle the no-provider-error well

@bpasero it seems that the lifecycle service gets stuck somewhere

**Comment by bpasero** [comment]
@jrieken 

> it seems that the lifecycle service gets stuck somewhere

May I know what to look for?

**Comment by bpasero** [comment]
@alexandrudima @sandy081 related to recent changes in your area? I see the extension host starting (looking at the console) but it looks like no extensions activate. It is easy to reproduce by executing the "Hello World" extension command from our yo generator after having opened the liveshare workspace.

**Comment by bpasero** [comment]
I see this in the status bar for a couple of seconds which seems fishy:

![image](https://user-images.githubusercontent.com/900690/53642434-0c114300-3c32-11e9-8e21-a5a5f41677b4.png)

**Comment by jrieken** [comment]
> I see this in the status bar for a couple of seconds

The couple of seconds to be expected as we hide this message after N seconds

**Comment by bpasero** [comment]
Ah yeah true.

**Comment by sandy081** [comment]
@bpasero Can you please verify this?
