### ISSUE TITLE
Searching in currently open file

### ISSUE THREAD

**Issue by underr-ua** [microsoft/vscode#68559]
Issue Type: <b>Bug</b>

Select text -> press Ctrl-f 
VS Code shows that there is only one instance matched
But if change the tab and then come back - it shows all matched instances

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.66GB (0.70GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
vscode-twig-pack|baj|1.0.0
vscode-html-css|ecm|0.2.0
shell-format|fox|4.0.4
beautify|Hoo|1.4.8
php-cs-fixer|jun|0.1.95
python|ms-|2019.1.0
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.21.0
trailing-spaces|sha|0.2.11
markdown-preview-enhanced|shd|0.3.11
bbcode|Squ|0.0.2
bootstrap4-vscode|the|6.0.3
highlight-matching-tag|vin|0.8.6
twig|wha|1.0.2

</details>

**Comment by lesha1201** [comment]
I have the same issue when doing this:

1. Press Ctrl+F and search something
2. Select something and press "Find in selection"
3. Now turn "Find in selection" off

After these steps, it seems "Find in selection" does not turn off. As said @underr-ua, if change a tab and then come back - it shows all matched results.

**Comment by underr-ua** [comment]
It seems the issue has gone after reset the parameter Editor > Find: Seed Searching From Selection

@lesha1201, i had the same issue and after disable the parameter Editor > Find: Auto Find In Selection it seems this issue has gone too

**Comment by lesha1201** [comment]
@underr-ua It was disabled by default but I still have the issue.

**Comment by atiris** [comment]
Can be related to: https://github.com/Microsoft/vscode/issues/69819

**Comment by rebornix** [comment]
@lesha1201 I didn't reproduce this issue in latest Insiders, can you help confirm that?

**Comment by lesha1201** [comment]
@rebornix Can't reproduce neither in `1.36.1`. I think it could be closed if no one experience this issue

**Comment by rebornix** [comment]
@lesha1201 thanks!
