### ISSUE TITLE
Cannot read property 'value' of undefined during vscode.tasks.fetchTasks

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#68550]
Issue Type: <b>Bug</b>

Originally filed by @ilkka in https://github.com/Microsoft/vscode-azurefunctions/issues/990, but I've simplified the tasks.json a bit so that it's not related to the Functions extension.

Call `await vscode.tasks.fetchTasks();` from a VS Code extension when this is the tasks.json of the open workspace:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo1",
      "command": "echo 1",
      "type": "shell"
    },
    {
      "label": "echo2",
      "command": "echo 2",
      "type": "shell"
    },
    {
      "label": "Test",
      "type": "process",
      "dependsOn": ["echo1", "echo2"]
    }
  ]
}
```

Error: Cannot read property 'value' of undefined

To quote @ilkka:
> either a) that tasks.json is invalid and should be marked as such in the editor, which it is not, or b) the task handling code should take this edge case (?) into account.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-antlr4|mik|2.1.1
python|ms-|2019.1.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
vscode-typescript-tslint-plugin|ms-|1.0.0
java|red|0.38.0
sort-lines|Tyr|1.8.0
vscode-java-debug|vsc|0.16.0

</details>

**Comment by alexr00** [comment]
@EricJizbaMSFT thank you for the simple to repro bug steps!
@ilkka, I looked at your original bug. Is this something that used to work, or did you just recently try it out? I ask because I'm trying to figure out if I should update the schema to match what the code is expecting, or update the code so it works despite this.

**Comment by alexr00** [comment]
Verification steps: Use the json in the original issue posting. Verify that there is a validation error. Fix the validation error by changing the type of the last task to `shell` then verify that you can run the last task.

**Comment by EricJizbaMSFT** [comment]
Verified I'm getting the validation error on latest insiders. thanks!

**Comment by alexr00** [comment]
Thank you for verifying!
