### ISSUE TITLE
Ability to disable icons and details in suggestions

### ISSUE THREAD

**Issue by svipas** [Microsoft/vscode#68557]
Hi,

I'm switching between `"editor.quickSuggestions"` true and false, but mostly I miss the suggestions list. The issue is in VS Code it's too much noisy and distracting. But it can be easily fixed by adding an ability for users to decide if they want to see icons and details in suggestions list. Also, `maxSuggestionsToShow = 12` in my opinion is too much, it should be an `8` like it's in Sublime.

In my opinion, these settings should be adjustable by the user:

```
const maxSuggestionsToShow = 12; // suggestWidget.ts
iconsInSuggestions: true, // editorOptions.ts
this.details = new SuggestionDetails(...); // suggestWidget.ts
.monaco-editor .suggest-widget { width: 430px; } // suggest.css
```

Suggestion for configurations:

```
"editor.suggest.showDetails": boolean, // by default true
"editor.suggest.showIcons": boolean, // by default true
"editor.suggest.maxSuggestionsToShow": number // by default 8
```

# Before

<img width="1071" alt="screen shot 2019-02-12 at 21 51 59" src="https://user-images.githubusercontent.com/10441177/52663932-7aef5c00-2f10-11e9-958f-c5e7f370e4f9.png">

# After

<img width="1071" alt="screen shot 2019-02-12 at 21 41 06" src="https://user-images.githubusercontent.com/10441177/52663953-8a6ea500-2f10-11e9-9fae-d03cab7bcd89.png">

I'm not touched `.monaco-editor .suggest-widget { width: 430px; }`, but I think then details are disabled this should be smaller than `430px`.

**Comment by svipben** [comment]
I want this feature so badly, I can even try all my best to create a PR if any of VS Code team agrees on this. 🔥

**Comment by svipben** [comment]
@joaomoreno Hi, since you're back, maybe you can give your opinion on this? I can definitely create a PR.

**Comment by svipas** [comment]
@jrieken Since you're in charge now, maybe you can give your opinion on this? As I already mentioned I'm willing to create a PR if you're alright with these suggestions.

**Comment by svipas** [comment]
@jrieken  Maybe I can create a PR to control these two settings?

```js
const maxSuggestionsToShow = 12; // suggestWidget.ts
iconsInSuggestions: true, // editorOptions.ts
```
Settings will look like this:

```json
"editor.suggest.showIcons": boolean, // by default true
"editor.suggest.maxSuggestionsToShow": number // by default 12
```

**Comment by jrieken** [comment]
@svipas Sure!

**Comment by svipas** [comment]
@jrieken OMG, thanks!!!

**Comment by svipas** [comment]
Created a PR https://github.com/Microsoft/vscode/pull/69942

**Comment by jrieken** [comment]
👏 to @svipas

**Comment by jrieken** [comment]
fyi - we have renamed the setting to `editor.maxVisibileSuggestions` to align better with other setting names

**Comment by svipas** [comment]
@jrieken Thank you for info and the support, I really appreciate it. These settings will be released in 1.32 or 1.33?

**Comment by jrieken** [comment]
the setting in action, life: ![mar-07-2019 15-30-32](https://user-images.githubusercontent.com/1794099/53963657-ff876180-40ed-11e9-97ad-9cf8dbc653c4.gif)

**Comment by jrieken** [comment]
This is for 1.33. We plan to release 1.32 today so that tomorrow we have insider builds for 1.33 include this change

**Comment by svipas** [comment]
@jrieken I saw you missed some renaming:

<img width="1080" alt="screen shot 2019-03-07 at 19 02 05" src="https://user-images.githubusercontent.com/10441177/53974591-8e56a700-410b-11e9-8670-39715bfa3f7c.png">

This should be `maxVisibileSuggestions` right?

**Comment by jrieken** [comment]
Yeah, missed that. I have change ready for it

**Comment by svipas** [comment]
@jrieken cool! I will definitely use them in tomorrow insiders 😄

**Comment by svipas** [comment]
Also, seems there's a typo: `maxVisibileSuggestions` should be a `maxVisibleSuggestions`.

**Comment by jrieken** [comment]
Good catch, pushed a fix
