### ISSUE TITLE
Invoke vscode commands from task.json

### ISSUE THREAD

**Issue by magpier84** [Microsoft/vscode#6855]
Is it possible to invoke vscode commands from task.json?
For example, invoke build command (or call extension) before launch debugger.
Thanks!

**Comment by isidorn** [comment]
It is possible to invoke a task (build command) before launching, for instance you can use `preLaunchTask` in your `launch.json`. More details can be found here https://code.visualstudio.com/docs/editor/debugging

Automatically invoking any vscode command before starting debug is currently not supported.
