### ISSUE TITLE
Can't run gulp to compile extensions

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#68564]
I'm getting this error on CLI:

```
 css-language-features > npx gulp watch-extension:css-language-features-client
[12:52:35] Working directory changed to ~/Code/work/vscode
Task requires a name that is a string
 css-language-features > 
```

Seems related to https://github.com/Microsoft/vscode/commit/bb6a7907119e54031523d4f9898cd179f65fc225

**Comment by alexandrudima** [comment]
@octref this works for me on Windows:
![image](https://user-images.githubusercontent.com/5047891/52672570-877ab100-2f1e-11e9-99f9-0d33d6d4851f.png)

**Comment by alexandrudima** [comment]
Do you perhaps have a global installation of `gulp` that is outdated ?

**Comment by octref** [comment]
Sorry my bad, that's exactly what went wrong. I was on gulp 3 in `./node_modules` and I only reinstalled dependency for `extensions/css-language-features` after `git pull`.
