### ISSUE TITLE
Unable to debug python code

### ISSUE THREAD

**Issue by RajeshSivadasan** [Microsoft/vscode#68560]
Issue Type: <b>Bug</b>

Python code was running file but after an VSC upgrade (which I guess is automatica) things are not working. I am unable to run a single program through the editor.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (5.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0
csharp|ms-|1.17.1

</details>

**Comment by RajeshSivadasan** [comment]
Below is the commandline that appears in the terminal and the editor is stuck.
D:\RAJESH\TRADING\ZERODHA\Python>cd D:\RAJESH\TRADING\ZERODHA\Python && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" &&
D:\Python\Python36\python.exe c:\Users\Admin\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 50629 d:\RAJESH\TRADING\ZERODHA\Python\t2.py "

**Comment by tomaxsas** [comment]
have you tried reinstall extension? it helps me sometimes :)

**Comment by underdogadmin** [comment]
same thing is happening with the ms-vscode.go extension even after reinstalling it.

**Comment by RajeshSivadasan** [comment]
I tried uninstalling and reinstalling vscode and python extension as well but its still the same. Attaching the debug file created (I saw this was asked in another similar thread)
[debug6004.log](https://github.com/Microsoft/vscode/files/2866533/debug6004.log)
