### ISSUE TITLE
Inline Conditional Causes Editor to Not Render C# Properly

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#68568]
Issue Type: <b>Bug</b>

When I have this line of code, `bool shouldSkip = asObjectResult ? .StatusCode >= 400 || asObjectResult ? .Value == null || asObjectResult ? .Value as Resource == null;`

All of the C# underneath it is not rendered properly. If statements, methods, the var keyword, all change to green and red text. If I comment out the above line then everything gets picked up properly.

I've got no C# extensions except for the main one that you have to have. If I am supposed to disable all extensions, can someone tell me how to disable them all without doing each one individually? Otherwise, I don't have any for C# anyways and this is happening off of the conditional statement above. I have used them before.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
gitlens|eam|9.5.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.46
prettier-vscode|esb|1.8.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
dotnet-test-explorer|for|0.6.2
minify|Hoo|0.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
docomment|k--|0.1.3
dotnet-core-essentials|Kis|0.0.6
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.14.0
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1151
vsliveshare-audio|ms-|0.1.48
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
debugger-for-edge|msj|1.0.6
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.15.0
vscode-docker|Pet|0.5.2
vscode-gitignore-generator|pio|1.0.1
tslint-vue|pro|1.5.6
yo|sam|0.9.3
vscodeintellicode|Vis|1.1.3
wilderminds-aspnetcore-snippets|wil|0.2.1
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Can you try running without extensions per instructions here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled ?
Since there are extensions enabled it is possible this is extension related.

**Comment by DanJ210** [comment]
@alexr00 This one is very hard to debug because sometimes it fixes itself with a VS Code restart. So I can go through and disable each extension which is tedious but until I restart nothing changes. Then if I do restart and it changes there's no way for me to know if it was an extension that did it or simply restarting. I see this issue often and my extension usage is pretty light probably compared to most. I only use major ones that I hope would be very clean. But I don't really know.

**Comment by alexr00** [comment]
@DanJ210, you don't need to disable each extension individually: https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled

**Comment by DanJ210** [comment]
@alexr00 Oh well I guess I've never know that was there. When the issue comes up again I'll try and see what happens. I'll report here just for the investigation side of things.

Thanks!
