### ISSUE TITLE
Clearing the terminal ("cls") does not clear the terminal.  It just scrolls down.

### ISSUE THREAD

**Issue by Murtaya** [Microsoft/vscode#68565]
Step 1: Get a lot of terminal output.  With react/redux/jest/etc., this is easy
Step 2: type "cls" into the terminal and return

Expected: The terminal and its history should be cleared, so when I get the next several pages of terminal spew, I can tell exactly where it started

Actual: The terminal is only scrolled down.  As soon as I get more terminal output, when I scroll up to see the beginning, I can't tell where the last session starts and the previous session (which I wanted to clear) ends.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
