### ISSUE TITLE
Screencast started using serif font

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#68567]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.32.0-insider (0d50120c71dcb9430997d6cd9c0ed1daaf65ce5c, 2019-02-12T18:31:10.402Z)
OS version: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
@sbatten Maybe some workbench change?

**Comment by bpasero** [comment]
I pushed a change to put the screencast div into the workbench element. This was related to my CSS changes.
