### ISSUE TITLE
find in files does not search files until they have been brought to the front

### ISSUE THREAD

**Issue by michaeladamkatz** [Microsoft/vscode#68570]
Issue Type: <b>Bug</b>

Start VS Code with a set of files opened automatically because you are set to open files from the previous session. These files appear in the OPEN EDITORS list on the right. In my case I have about 20 files listed.

shift-control-f to go to the search in files prompt

search for a word that is in several of your files

result: it only finds matches in the file that is frontmost for editing

then use the any mechanism to bring each of the windows to the front in turn (e.g., click each window name one by one in the OPEN EDITORS list)

shift-control-f to go to the search in files prompt

search for the same word again

this time you get results in all of the OPEN EDITORS files that contain the word

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (11.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
binary-viewer|mom|0.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-docker|Pet|0.5.2
vscode-hexdump|sle|1.7.2

</details>
large to send. Please paste.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/62488
