### ISSUE TITLE
Creating file via shortcut puts the file in the wrong place

### ISSUE THREAD

**Issue by midgethoen** [Microsoft/vscode#68574]
- VSCode Version: 1.31.1
 OS Version: osx 10.14.2

Steps to Reproduce:

1. set up shortcuts for creating files/folders in 

```json
 ...
  {
    "mac": "a",
    "win": "a",
    "linux": "a",
    "key": "a",
    "when": "filesExplorerFocus && !inputFocus",
    "command": "explorer.newFile"
  },
  {
    "mac": "shift+a",
    "win": "shift+a",
    "linux": "shift+a",
    "key": "shift+a",
    "when": "filesExplorerFocus && !inputFocus",
    "command": "explorer.newFolder"
  },
 ...
```
1. select folder or file in File explorer
2. press `a` or `shift+a`
3. observe how the file is suggested in the wrong place; i.e. other than:
   1. inside the selected folder 
   2. next to the selected file

I could not reproduce this in a clean workspace with extensions disabled.  so I recorded a small video to show what is going on. 

[vscode.mov.zip](https://github.com/Microsoft/vscode/files/2858020/vscode.mov.zip)

In de video i in sequence: 
- click the folder
- press shift+a
- press escape 
- press a
- press escape

this is happening to me since I noticed the 1.31 release this morning. I upgrdaded to 1.31.1 and the problem persists

**Comment by midgethoen** [comment]
I actually can reproduce this in a clean workspace with extensions disabled.

- create new window
- reload window with extensions disabled
- add folder to workspace
  - select empty folder
- create following directory structure (4 directories:
  - ./a/b
  - ./c/d
- select directory d in file explorer
- press `a` or `shift+a`
- observe that the suggested location is in directory A

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode insiders
and setting "workbench.list.automaticKeyboardNavigation": false

I believe the setting fixes this issue
@midgethoen please try insiders with the setting and let us know if the issue is still not fixed for you and we will reopen

**Comment by midgethoen** [comment]
yes, I forgot to mention `"workbench.list.automaticKeyboardNavigation": false`. I was also using this setting. 

I can still reproduce this with 1.32.0-insider  build `393b48d4a5de85b6fa1d2ad0a59588d6715e12ea`. although it does not happen very consistently. 

<details> 

`settings.json`

```json
{
"workbench.list.automaticKeyboardNavigation": false
}
```

`keybindings.json`

```json
// Place your key bindings in this file to override the defaults
[
    {
        "mac": "a",
        "win": "a",
        "linux": "a",
        "key": "a",
        "when": "filesExplorerFocus && !inputFocus",
        "command": "explorer.newFile"
      },
      {
        "mac": "shift+a",
        "win": "shift+a",
        "linux": "shift+a",
        "key": "shift+a",
        "when": "filesExplorerFocus && !inputFocus",
        "command": "explorer.newFolder"
      },
]
```
</details>

I wil try to find some time to troubleshoot this further

**Comment by midgethoen** [comment]
Ok, I think I know what is going on;  my reproduction wasn't entirely accurate.

I ran vscode from source and messed around in [fileActions.ts](vscode/src/vs/workbench/contrib/files/browser/fileActions.ts) a bit.

at some point in running `explorer.newFile`/`explorer.newFolder` getContext is called. 

https://github.com/Microsoft/vscode/blob/55ece57154078974bf4c25b0eeb92057eecc9298/src/vs/workbench/contrib/files/browser/fileActions.ts#L1024-L1033

I noticed the focus was sometimes empty when I didn't expect it to be. this happens in 2 cases:

1. when I remove focus from the explorer (clicking outside of it). the last selected file remains highlighted in grey. but it is not used as context.

**Comment by midgethoen** [comment]
Ok, I think Im a bit closer to what is going on;  in 1.32.0-insider I can't reproduce [what I demonstrated in 1.31.1](
https://github.com/Microsoft/vscode/issues/68574#issuecomment-462983995). So the original issue seems to be resolved. But I ran into something else an our ago. 

I now ran vscode from source and messed around in [fileActions.ts](vscode/src/vs/workbench/contrib/files/browser/fileActions.ts) a bit.

at some point in running `explorer.newFile`/`explorer.newFolder` getContext is called. 

https://github.com/Microsoft/vscode/blob/55ece57154078974bf4c25b0eeb92057eecc9298/src/vs/workbench/contrib/files/browser/fileActions.ts#L1024-L1033

I noticed the `focus` constant was sometimes empty when I didn't expect it to be.

When I cancel an addFolder/addFile action by pressing escape, the explorer seems to remain focussed and the previously selected folder is highlighted in blue. but if you now run addFolder/addFile agin, the getContext's focus is empty. 

This causes the file/folder to be added in the root. this behavior seems to be different from 1.31.1

**Comment by isidorn** [comment]
@midgethoen that behavior Is different but imho is not so bad. The behavior is when you cancel new file / new folder dialog focus is returned to the tree, not to the tree element.
I would wait for more users to complain before I change this as I personally do not mind the new behavior.
It is good when the user wants to create an element top level but has first mistankly triggered a creation in some folder (due to tree focus).
