### ISSUE TITLE
Maximizing trims bottom (status bar)

### ISSUE THREAD

**Issue by mottykohn** [microsoft/vscode#68572]
Issue Type: <b>Bug</b>

Just maximize VS code window. See the status bar and a little above is missing!

![image](https://user-images.githubusercontent.com/17966568/52671140-4a93c780-2ee8-11e9-93c3-c46c05e5e45e.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
alignment|ann|0.3.0
githistory|don|0.4.6
xml|Dot|2.4.0
gc-excelviewer|Gra|2.1.28
live-html-previewer|hdg|0.3.0
rainbow-csv|mec|1.0.0
Angular-BeastCode|Mik|7.2.2
mssql|ms-|1.4.0
vsliveshare|ms-|0.3.1151
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
ng-refactor|ng-|0.1.0
vscode-versionlens|pfl|0.22.0
vscode-scss-formatter|sib|1.4.0
quokka-vscode|Wal|1.0.182

</details>

**Comment by bpasero** [comment]
@mottykohn what are your settings?

**Comment by mottykohn** [comment]
Here is my settings:
`{
    "mssql.connections": [
        {
            "server": "***",
            "database": "***",
            "authenticationType": "Integrated",
            "profileName": "SQL 2016",
            "password": ""
        }
    ],
    "files.autoSave": "off",
    "window.zoomLevel": 0,
    "git.confirmSync": false,
    "git.autofetch": true,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": true,
    "[typescript]": {
        
    },
    "typescript.preferences.quoteStyle": "single",
    "csv-preview.lineNumbers": true,
    "workbench.editor.enablePreview": true,
    "breadcrumbs.enabled": true,
    "workbench.colorTheme": "Visual Studio Dark",
    "emmet.includeLanguages": {
        "ng-template": "html"
    },
    "editor.multiCursorModifier": "ctrlCmd",
    "workbench.startupEditor": "newUntitledFile"
}`

**Comment by bpasero** [comment]
@mottykohn is that reproducible all the time?

**Comment by mottykohn** [comment]
On my computer yes - it's always happening. Regardless of theme, or disabling extensions. Did not try any other computer. My work around is to not maximize rather I just drag my form to all the edges of my screen.
Actually I just changed my display settings from extend to other screen to show on one screen (I have two screens.) Then I changed back and the problem disappeared. So I guess issue could be closed.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by mottykohn** [comment]
No issues not with the above download 1.31 -exploration nor with 1.32-exploration.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by mottykohn** [comment]
In the end it has nothing to do with vs code. Here is a thread about it https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/windows-10-multi-monitor-maximized-window/3c2042ef-73df-401c-9a59-65b347d4dbea
