### ISSUE TITLE
"Installing Update..." in context menu should change to "Restart to Update..." without reactivating context menu

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode#68571]
When doing a check for updates and VS Code begins the update, in the Manage context menu the text changes from **Check for updates...** to **Downloading update...** to **Installing update...** to **Restart to update...** but the text changes only when you reactivate the Manage menu.

If you leave the context menu as is the text will never change. It should automatically change so that I can click **Restart to update...** without having to click the Manage icon (gear icon).

On Windows:

![2019-02-12 at 01 58 pm](https://user-images.githubusercontent.com/9157833/52671269-748cc000-2ecf-11e9-8a31-f792d1a3fbda.jpg)
![2019-02-12 at 01 58 pm 2](https://user-images.githubusercontent.com/9157833/52671270-748cc000-2ecf-11e9-9303-4b433b899f03.jpg)

**Comment by joaomoreno** [comment]
There's currently no infrastructure support for this in the menu, I believe, right @sbatten ?

**Comment by sbatten** [comment]
@joaomoreno I think we could make this work for custom menus. The base action item in the menu supports listening for action changes and updating the label. Current the update action is implemented as dicrete actions, but they could be combined and get updated dynamically. I don't know what would happen if we tried to do the same approach in the native case.

**Comment by joaomoreno** [comment]
Right, given that native menus wouldn't work... I'll just close this as designed.
