### ISSUE TITLE
Could not get external grammar injections to work

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6858]
Testing #6693

Modified `$\extensions\typescript\package.json`, added to the `grammars` section:
```
{
	"injectTo": ["source.ts"],
	"scopeName": "text.todo",
	"path": "./syntaxes/todo.json"
}
```

Added `$\extensions\typescript\syntaxes\todo.json`:
```
{
	"fileTypes": [],
	"injectionSelector": "comment, text.plain",
	"name": "TODO",
	"patterns": [
		{
			"match": "\\b(TODO|FIXME|CHANGED)\\b",
			"name": "storage.type.class.${1:/downcase}"
		},
		{
			"captures": {
				"1": {
					"name": "markup.underline.link.radar"
				}
			},
			"match": "<(ra?dar:/(?:/problem|)/(?:[&0-9]+))>",
			"name": "storage.type.class.radar"
		}
	],
	"scopeName": "text.todo"
}
```

I don't see it being picked up in TypeScript comments (inspecting the tokens also did not show it being picked up):
![image](https://cloud.githubusercontent.com/assets/5047891/15531100/b4f2008c-2258-11e6-96ad-b022373b1738.png)

**Comment by aeschli** [comment]
At the moment injects are only applied to tokens generated by begin/end rules.
I'm investigating if that's a bug or not.

**Comment by aeschli** [comment]
To verify, inject against the string scope in typescript.

**Comment by kumarharsh** [comment]
@aeschli - i'm trying to get this working for a graphql plugin, but can't get it to work. It's unclear to me what you mean by
>  injects are only applied to tokens generated by begin/end rules.

does that mean that the injected grammar will only work when the `begin` and `end` properties are specified on the top level?

also,
> inject against the string scope in typescript
I tried injecting agains the string scope (by setting the `injectionSelector` to `string.graphql`, but nothing seems to change. Is there any resource I can refer to learn more about injection grammar?

If it helps, this is my config:

```json
/* package.json */
  "grammars": [
      {
        "language": "graphql",
        "path": "./syntaxes/graphql.json",
        "scopeName": "source.graphql"
      },
      {
        "scopeName": "text.mxyzptlk",
        "path": "./syntaxes/gql-query.json",
        "injectTo": [
          "source.graphql"
        ]
      }
    ],
```

```json
/* gql-todo.json */
{
    "fileTypes": [],
    "injectionSelector": "comment.graphql",
    "name": "TODO",
    "patterns": [
        {
            "match": "\\b(TODO|FIXME|CHANGED)\\b",
            "name": "storage.type.class.${1:/downcase}"
        },
        {
            "captures": {
                "1": {
                    "name": "markup.underline.link.radar"
                }
            },
            "match": "<(ra?dar:/(?:/problem|)/(?:[&0-9]+))>",
            "name": "storage.type.class.radar"
        }
    ],
    "scopeName": "text.mxyzptlk"
}
```

**Comment by mjbvz** [comment]
@aeschli I also gave this a try recently and was unable to get it working. Are there any example extensions that have a grammar with `injectTo` working? Thanks.

**Comment by wholroyd** [comment]
@aeschli It seems like the behavior in 1.8.0-inside is following the begin/end injection. This needs to be expanded somehow to allow the injection to happen on the entire document. Take for example a YAML document using the Jinja templating language - the first value in the document could be a Jinja comment and not necessarily part of the YAML syntax.

**Comment by aeschli** [comment]
@wholroyd We're using the text mate injection mechanism. Are you saying we lack a feature of it, or are you saying the injection mechanism (restricted to begin/end rules) is too limited?

**Comment by wholroyd** [comment]
@aeschli The later half

**Comment by kumarharsh** [comment]
@aeschli running into same problems with [graphql-for-vscode](https://github.com/kumarharsh/graphql-for-vscode/issues/6) plugin. The regex to match starting of the `Relay.QL`/`gql` is not powerful enough on its own. It also needs info about the scope of the matching (it should not apply the rules if it's matching within a string, for example).

**Comment by wholroyd** [comment]
@aeschli - I guess the biggest issue I have, which I have not figured out over a couple months of playing with it on the weekends here and there - is how to inject a language syntax regardless of where it is present in the other language's file or syntax structure. How would I inject at the document level instead of within established language patterns? If I have `{{ something }}`` present anywhere in a file, regardless of the language colorized the way I want, how would I go about doing that?

**Comment by aeschli** [comment]
You can choose a very open selector such as 'source.ts', but unfortunately injected rules will only be looked at when inside a begin/end rule.

**Comment by kumarharsh** [comment]
I suppose you can put something equally open like `"begin": ".*"` and `"end": ".*"` for begin and end rules in the injected grammar?
