### ISSUE TITLE
Missing command substitution in args from tasks.json

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#68587]
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create any task
2. In the `args` field add an arg with command substitution. e.g. $(pwd)
3. See in the terminal $(pwd) being wrapped by '

``` json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Build C++ App",
      "type": "shell",
      "command": "g++",
      "args": ["-g", "app.cpp", "$(pkg-config --cflags --libs gtk+-3.0)"],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/7959437/52686937-cc521800-2f1d-11e9-86d4-b1211965fe6d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
We quote any `args` that have spaces in them, so I don't have a good solution for this. If we stop quoting them then we'll break people who are currently counting on that. 
Can this be worked around with `"command": "g++ -g app.cpp $(pwd)"`?

**Comment by sant123** [comment]
![image](https://user-images.githubusercontent.com/7959437/52717762-cdac3080-2f6f-11e9-885a-c134ef326c31.png)

Works awesome. Thank you!
