### ISSUE TITLE
Cannot highlight word with mouse when renaming file in explorer

### ISSUE THREAD

**Issue by jwongnz** [Microsoft/vscode#68580]
I am not sure which exact repo this is relevant to sorry. Disabled all my extensions and still have this problem.

Issue example:
Say I have a file named helloworld.component.js.
As of recent, if I right click > rename the file in explorer, I cannot then double click on "component" to highlight that part of the text, nor can I highlight it with the mouse. VSCode insiders will instead just exit the renaming context.

Have tried on Windows and MacOS.
Version 1.32.0-insider

**Comment by Spown** [comment]
dup #68028 
pls close
