### ISSUE TITLE
The second installed extension doesn't auto display in 'Installed Extension' view till reloading VS Code

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode#68584]
- VSCode Version:
- OS Version: Mac & Windows10

Steps to Reproduce:

1.Install one extension--> prompt that installing is completed --> the installed extension auto displays.
2. Install the second extension -->prompt that installing is completed --> check whether the extension auto displays or not.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/67603
