### ISSUE TITLE
Open editors title cuts off first editor in list

### ISSUE THREAD

**Issue by ludvigeriksson** [Microsoft/vscode#68591]
- VSCode Version: 1.31.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Open an editor
2. It's being cut off by the title

Does this issue occur when all extensions are disabled?: Yes

<img width="1921" alt="vscode-open editors-cut-off" src="https://user-images.githubusercontent.com/7629496/52696284-f08a1500-2f6e-11e9-9845-bb6ff555e9c1.png">

**Comment by isidorn** [comment]
Disable tree horizontal scrolling
