### ISSUE TITLE
CMake/Build Output scrolling doesn't work after error in build

### ISSUE THREAD

**Issue by jepessen** [Microsoft/vscode#68594]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Pro 64

Steps to Reproduce:

1. Start a CMake build for a C++ CMake project
2. build is completed successfully
3. Create an error in a source file.
4. Build the project. The error is reported
5. Fix the error
6. Build again

In step 6 the CMake/Build output scroll stop working and I have to scroll the output manually.

Does this issue occur when all extensions are disabled?: Cannot verify because I need the CMake extension.

**Comment by isidorn** [comment]
Do you have output scroll lock toggled?
Also can you reproduce with vscode insiders? https://code.visualstudio.com/insiders/
