### ISSUE TITLE
Why it will open the last file when after `refresh explorerer` icon button clicked?

### ISSUE THREAD

**Issue by luozt** [Microsoft/vscode#68598]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

I installed vscode version 1.31.1, but it will open the last file when `refresh explorerer` icon button clicked, which is a new situation to me because it will not happen in older versions.

If this feature was added recently by some man, please help me call him to cancel it.

Thanks!

**Comment by luozt** [comment]
Is it underconstructing? I am looking forward to see the next version! ^_^

**Comment by isidorn** [comment]
This is by design, we always did this. To prevent it set
explorer.autoReveal: false

**Comment by luozt** [comment]
Ok, I see. But I still not support this design as `refresh explorer` feature does not mean to open the last closed file.

**Comment by isidorn** [comment]
This is probably fixed now. Try it in tomorrow's vscode insiders. Thanks!

**Comment by luozt** [comment]
Yeah, it is fixed now in the latest version. Great! Good!

版本: 1.32.1 (user setup)
提交: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
日期: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
