### ISSUE TITLE
Missing side-by-side keybindings experience

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#68592]
It seems on master there is no way to open side-by-side the default keybindings and the user keybindings. Can we have this back please?

**Comment by sandy081** [comment]
@alexandrudima Change the setting `workbench.settings.openDefaultKeybindings` to `true`. By default it is `false` now. 

This is now in sync with settings editor.

**Comment by alexandrudima** [comment]
Thanks!
