### ISSUE TITLE
Trusted Publisher Verification & Verified Publisher Filtering for Extensions

### ISSUE THREAD

**Issue by REPNOT** [microsoft/vscode#68590]
With a high volume of extensions available for VS Code, it would be great to know
if extension publishers are both trusted and verified.  In addition to this, the ability to
filter extension searches to display verified trusted extension publishers only, would be
great!  Ratings aren't enough, I personally would feel more comfortable downloading
extensions verified by Microsoft using a process to ensure proper due diligence has 
been exercised to guarantee some level of quality and security.

**Comment by sandy081** [comment]
@joaomoreno Not sure if you already have an issue for this, if so please close this as duplicate. Thanks.

**Comment by joaomoreno** [comment]
> Ratings aren't enough, I personally would feel more comfortable downloading
extensions verified by Microsoft using a process to ensure proper due diligence has
been exercised to guarantee some level of quality and security.

The current state of things is: every single extension in the marketplace is scanned for malware and security issues. So by downloading it from the Marketplace you already have that guarantee. There's not much more we can do here besides implementing end-to-end signing which won't give you any added benefits. Closing this as out of scope.
