### ISSUE TITLE
New explorer: does not reveal active file if no file was opened

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#68597]
I think I finally found some steps about this issue that hunted me down:
* close all editors
* collapse all in the tree
* reload
* open a file from quick open

=> 🐛 it gets not revealed in the explorer

Subsequent opens work with revealing so it seems to be related to having no editor open initially.

**Comment by rdsedmundo** [comment]
I'm also experimenting with this one. I have to refresh the explorer using the icon in order to it to go to the file I'm at the moment.

**Comment by Yanpas** [comment]
I face this issue when open file from Ctrl+P. I have many editors open, but autoreveal still doesn't work

**Comment by fredrik-lundin** [comment]
I'm also experiencing problems with auto reveal after the latest update (1.31.1). 

I frequently use `ctrl+shift+e` to go from an active editor window to the corresponding file in the file explorer. After the latest update, `ctrl+shift+e` won't take me to the active file, but to the latest selected file in the file explorer instead.

Things I have tried but with no success:
* Explicitly set `explorer.autoReveal = true` in my settings file
* Run vscode with all extensions disabled

Any ideas?

**Comment by isidorn** [comment]
@bpasero god bless you for your nice reporting with steps
