### ISSUE TITLE
expose git commit API for other extensions

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#68599]
Issue Type: <b>Feature Request</b>

https://github.com/Microsoft/vscode/blob/1acabe663a4ec79cb728ea4966278ca4387ac35b/extensions/git/src/api/git.d.ts#L168-L176

third-party extension needs this API for custom commit.

Why third-party extension does not implement the commit interface by itself?

calling the built-in Git extension interface is to keep Commit's behavior consistent and maintain a consistent user experience

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
PR welcome. Until then, closing this.
