### ISSUE TITLE
avoid 'integratedTerminal' and 'externalTerminal'. Rather use 'terminal'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6859]
For #6654.
Right now the settings are called
"integratedTerminal.shell.linux": "/bin/bash"
"externalTerminal.windowsExec": "cmd",

If you look at other settings, we avoid camelcase in the first segment.
I'd suggest to group everything under terminal.

-> One setting that chooses which terminal type to use (e.g. when invoking 'Open in terminal').
'external', 'integrated'. IMO intergrated should be the default.
-> terminal.external.windowExec ...
-> terminal.integrated.shell

**Comment by Tyriar** [comment]
I like it

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/commit/8c1dff7ee7bd8a1b5914a474aa69879878d9db04

**Comment by Tyriar** [comment]
I think I changed the important places where I mentioned it in:

- https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md
- https://github.com/Microsoft/vscode/issues/143#issuecomment-221054202
