### ISSUE TITLE
Flashing minimap

### ISSUE THREAD

**Issue by BraveThrasher** [Microsoft/vscode#68596]
Issue Type: <b>Bug</b>

The minimap is constantly flashing and is only showing the document outline for about 40% of the time. It also seems to scroll slightly up and down by itself when I'm obviously not scrolling.

I am using VS code on VMWare.

This started happening after updating to the lastest VS code version. Earlier version was working fine.

VMWare Workstation 14 Player (14.1.5 build-10950780)
VMWare Host OS: Windows 10 Version 1803 (OS Build 17134.523)
VMWare Guest  #OS: macOS High Sierra version 10.13.6 (17G5019)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (4 x 2677)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (3.42GB free)|
|Process Argv|-psn_0_241723|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
vscode-eslint|dba|1.8.0

</details>

**Comment by BraveThrasher** [comment]
I tried creating a screen recording and while doing that I noticed improvement, the flashing was a lot less dramatic. At the same time I also noticed that the flashing is at its worst when the terminal is active and hiding the panel with the terminal even almost stops the flashing, so it is possibly related to issue #68553.

Another thing I noticed is (even when the terminal panel is not visible) when going with your mouse cursor from the file explorer over the line numbers to the code section and back repeatedly (like creating circles with your mouse cursor over those areas) also makes the minimap flash. While doing the same action not just the minimap flashes but in the code section also squares with darker and lighter background flash up momentarily but the code stays visible. This however is a bit less annoying.

In the end I cannot add the screen recording because of proprietary code in it.

**Comment by alexandrudima** [comment]
@BraveThrasher Does this reproduce when launching code with `--disable-gpu` ?

**Comment by BraveThrasher** [comment]
Sorry for the delayed response.
Launching with `--disable-gpu` practically makes the flashing of the minimap (and terminal) itself stop but the entire window flickers when typing and moving the mouse cursor between panels (code window, file explorer, terminal/output,...).

**Comment by Tyriar** [comment]
Let's close in favor of https://github.com/Microsoft/vscode/issues/15211, Chromium is bad when GPU acceleration is enabled in VMs.
