### ISSUE TITLE
Some wrong when delete

### ISSUE THREAD

**Issue by KaoImin** [Microsoft/vscode#68593]
Issue Type: <b>Bug</b>

While delete some blank line one after another, the first time it works normally, and the second time and third time the cursor will move to the last line and delete the things in the last line.

VS Code version: Code - Insiders 1.32.0-insider (a509265116babc17648c9052eeeb8ae2909fed87, 2019-02-13T06:15:00.223Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|-psn_0_1376592|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.24.0
vscode-dash|dee|2.0.0
jupyter|don|1.1.4
vscode-rust-syntax|dun|0.0.32
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
mdmath|goe|2.3.9
asciidoctor-vscode|joa|2.3.3
language-julia|jul|0.11.4
Lisp|mat|0.1.8
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.1.0
cpptools|ms-|0.21.0
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
ide-purescript|nwo|0.20.8
language-purescript|nwo|0.2.0
vscode-docker|Pet|0.5.2
erlang|pgo|0.5.0
vscode-icons|rob|8.1.0
rust|rus|0.5.3
vscode-hexdump|sle|1.7.2
latex-support|tor|2.1.0
codelf|unb|11.3.0
tensorflow-snippets|vah|0.3.3
vim|vsc|1.0.8
markdown-all-in-one|yzh|2.0.1
vscode-proto3|zxh|0.2.2

(2 theme extensions excluded)

</details>

**Comment by KaoImin** [comment]
This might be caused by the Vim extension.

**Comment by KaoImin** [comment]
Ignorance is bliss; temporarily suppressing log messages. For more permanence, please configure `vim.debug.suppress`.

**Comment by alexandrudima** [comment]
@KaoImin Can you please create an issue directly against the vim extension at https://github.com/VSCodeVim/Vim?
