### ISSUE TITLE
CLI: --add stops working

### ISSUE THREAD

**Issue by Irthen** [Microsoft/vscode#68595]
- VSCode Version: 1.32.0-insider a509265116babc17648c9052eeeb8ae2909fed87 x64
- OS Version: macOS Mojave 10.14.3 (18D109)

Steps to Reproduce:

1. Open Terminal.
2. Navigate to a directory and type "code-insiders --add ."
3. The current path is not added to the opened editor.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Regression caused by 61fc467
