### ISSUE TITLE
tasks for single file

### ISSUE THREAD

**Issue by keyring** [Microsoft/vscode#686]
I want to make a task to build a single file, like a lua script file. But seems like, the `tasks.json` must under a folder's `.vscode`. 

I don't want to open a folder and create many same `tasks.json` each time when I just new a temp single file.

May `tasks.json` become a extension option like sublime's `build system`?

**Comment by colbyrussell** [comment]
Needs "tasks" tag?

**Comment by egamma** [comment]
@ghost  added the label, thanks

**Comment by dbaeumer** [comment]
Dups #1435.
