### ISSUE TITLE
Window size bug

### ISSUE THREAD

**Issue by toki-geez** [Microsoft/vscode#68607]
Issue Type: <b>Bug</b>

You open Visual Studio, go to settings, go into users setting and finally change the window size to 80%. Now try to scroll or leave this size and please help me!!

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Yikes, I guess this is what you see?

![image](https://user-images.githubusercontent.com/323878/52918316-67464b80-32aa-11e9-8e68-6efea30e9984.png)

I think `window.zoomLevel` needs a sensible default?

**Comment by toki-geez** [comment]
Hello,
Could someone give me a link to the duplicate as i am new to github and don't know how to find it.

Thanks a lot for the help provided.

**Comment by roblourens** [comment]
I think https://github.com/Microsoft/vscode/issues/48357

**Comment by toki-geez** [comment]
Thanks

So do I get back to the normal size window?

**Comment by roblourens** [comment]
You should be able to zoom out with `cmd -`, or by opening your settings file in another editor - `/Users/roblou/Library/Application Support/Code/User/settings.json`

**Comment by toki-geez** [comment]
I'm sorry I'm on windows and I have no idea where the file is and ctrl - doesn't work either even ctrl mouse scrool down can I solve it in another way?

**Comment by roblourens** [comment]
Open the settings UI, click the `{}` button, find `window.zoomLevel` and delete that line.

Or find the path at `C:\Users\roblou\AppData\Roaming\Code - Insiders\User\settings.json`
