### ISSUE TITLE
Manually change EOL to LF for many files at once

### ISSUE THREAD

**Issue by jescowuester** [microsoft/vscode#68601]
type: feature request

Right now there is no integrated tool to convert all line endings for existing files in a project to LF from CRLF. You either have to change them manually for every file or resort to command line scripts as in #25209. 

Requested feature: One-click solution to convert the EOL of many existing files in a folder/workspace.

* VSCode Version: 1.31.1
* OS Version: Windows 10 Home 64

**Comment by Anaizing** [comment]
I second that motion... It's a huge pain
