### ISSUE TITLE
(MacOS Yosemite) Background rendering issue

### ISSUE THREAD

**Issue by UC101** [microsoft/vscode#68606]
Issue Type: <b>Bug</b>

This only became an issue after I updated yesterday. 
I've seen the workarounds (and a few of them work) but by default this is an issue on MacOS Yosemite using both the normal build and insider build
When using a theme the background has rendering issues. Rectangles of a similar, but different color to the background cover the right-hand side of the screen, sometimes covering text. 

Steps to reproduce are simple:
- Use MacOS Yosemite
- Open VSCode
- Select a theme
- The background will be glitched

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 14.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.03GB free)|
|Process Argv|-psn_0_3449674|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.0.0
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
pico8vscodeeditor|Gru|0.2.3
vscode-github|Kni|0.30.1
electron-debug|kod|18.11.1
krom|kod|18.11.1
krom-debug|kod|18.11.3
python|ms-|2019.1.0
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.1
pixelbyte-love2d|pix|0.1.19
reloaded-cpp|rel|0.1.9
bash-debug|rog|0.3.3
codedox|wig|1.2.9

(3 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by UC101** [comment]
The Electron 4 build does fix the issue, background issues are completely gone.

**Comment by jdsimcoe** [comment]
@bpasero @UC101 I've been having exactly the same problems with VSCode Stable and Insiders and this build perfectly solves the background color rendering issues that I've been having too. Should we continue to use this Exploration build until the changes get merged back in?

**Comment by peregrinogris** [comment]
I'm also experiencing these issues on Ubuntu 18.10, using the exploration build with electron 4 fixed the problem here too.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
