### ISSUE TITLE
Have to delete twice to remove a multi-level folder containing JavaScript/TypeScript files

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#6861]
- VSCode Version: 1.1.1
- OS Version: Windows 10 10586.318

Steps to Reproduce:

1. Open a folder.
2. Create file `f/f/f.js`.
3. Delete top folder `f`.

  Then it prompts a message asking whether I would want to move it to recycle bin.

4. Click "Move to Recycle Bin".

  Explorer prompts "File Access Denied".

5. Click "Continue" (to gain administrator permission), and "OK" on UAC prompt.

  Code prompts "Failed to move `f` to the trash".

6. Delete it again or retry in anyway, success.

**Comment by bpasero** [comment]
This is because TypeScript is locking folders.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/TypeScript/issues/7762 which is fixed in the upcoming TS 2.0 release.
