### ISSUE TITLE
Quickly include/exclude filetypes on search

### ISSUE THREAD

**Issue by Martinspire** [microsoft/vscode#68613]
So right now the search has a few features to include files and to exclude files once you've pressed on the 3 dots. On these you can add something like `**/*.d.ts` to exclude various filetypes. When developing I quickly move from one task to the next, making me look for different things inside projects. So I'm requesting a new feature to quickly include/exclude items. Be it from history, items that you pre-define or when scanning through the files and setting depending on how often they are included is up to you guys.

Basically if I can switch between searching inside my TS files on one moment and switch to searching in HTML files in the next, it would help me a lot. I know I can exclude `.d.ts` files from coming up, but often I do not want results from a `.js` file to be included in one search but I need it in the next.

Perhaps it would be easier to add this as filtering of the list without really including/excluding them from search, but I can see this starting small and moving from there. I'm not sure if its possible to adopt this in an extension but my knowledge of file searches and regex isn't good enough to get a prototype working.

**Comment by roblourens** [comment]
Would this cover your case? https://github.com/Microsoft/vscode/issues/16488 Like if you can have multiple search "tabs" that keep their different filters.

**Comment by apfelschaeler** [comment]
I would say yes, issue #16488 would cover this case. I got the same challenges like Martinspire has described in here.
VSC would be great with multiple searches.

**Comment by Martinspire** [comment]
@roblourens Well, having multiple searches would be nice, but I have way too many filetypes that I do or do not need to match that it would be easier to have a selection of filetypes to include/exclude.

I also thought that the results itself could have better filters because perhaps that would be used to match the filetypes in the search results directly giving me a way to enable/disable whatever I do or do not need.

Having another bar between the `Files to exclude` item and `2 results in 2 files` text or next to the `2 results in 2 files` text, to exclude files would also be a neat solution. And I can also see myself wanting to exclude like our test files which aren't really just `.ts` or `.js` files but with `test.ts`, and right now excluding those are not as easy too. Same happens with my `.d.ts` and my `.js.map` files.

**Comment by roblourens** [comment]
History does exist in these fields, if that helps.
