### ISSUE TITLE
Input of type promptString should accept an empty string

### ISSUE THREAD

**Issue by gpassero** [microsoft/vscode#68617]
The feature introduced in 1.31 to support prompting strings when launching a debug configuration is something I've expected for a long time. I changed my `launch.json` to use it right away after the update to VSCode v 1.31. 

I could make it work, but I found a small issue. When launching my debug configuration that uses an input of type "promptString", I see this dialog as expected:
![image](https://user-images.githubusercontent.com/4478523/52710267-136bf780-2f76-11e9-9a79-23726a3cc8e5.png)

Eventually, I'd like to leave the prompt field empty (to run all tests), but if I do that the launch config won't run.

- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add an input of type "promptString" in your `launch.json` and add it to a configuration
Example:
```json
{
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Unit Tests",
      "program": "${workspaceRoot}/../../../node_modules/jest/bin/jest.js",
      "args": [
        "--runInBand",
        "--testNamePattern",
        "${input:pickUnitTest}"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      }
  ],
  "inputs": [
    {
      "id": "pickUnitTest",
      "type": "promptString",
      "description": "Filter unit test names by the following string:"
    }
  ]
}
```
2. Run your debug configuration and press enter in the input dialog
3. The launch is canceled, but shouldn't (the dialog says pressing "Enter" is to confirm the execution, and "Escape" to cancel)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jorisvanderpol** [comment]
I would expect the same behavior of input for tasks. I need different tasks for running the same script with or without arguments.

**Comment by lbrugnara** [comment]
I'm interested in this feature too. Should the behavior be configurable through an attribute? Something like:
```
"inputs": [
    {
      "id": "pickUnitTest",
      "type": "promptString",
      "description": "Filter unit test names by the following string:",
      "allowEmptyString": true
    }
  ]
```
That way we avoid breaking changes on people expecting the current behavior to be the default one.

**Comment by zombiezen** [comment]
As of VSCode 1.36.1 (on Windows_NT x64 10.0.18362), the behavior seems to have changed, but not in a way I would have expected: leaving the string empty or hitting escape runs the task but does not substitute in the variable. Minimal repro tasks.json for me:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo",
      "type": "shell",
      "command": "echo",
      "args": ["${input:foo}"],
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "foo",
      "type": "promptString",
      "description": ""
    }
  ]
}
```

(In case it's significant, using Remove Development - WSL + zsh.)
