### ISSUE TITLE
Impossible to import module (even if path is set correctly) and "run in terminal" not present

### ISSUE THREAD

**Issue by filipporemonato** [Microsoft/vscode#68614]
In my file `main.py` I am importing a module `utilities.py` located in another folder.
The directory structure is
```

Project_folder
        |-- execution_folder
        |          |-- main.py
        |-- util_folder
                   |-- utilities.py
```

I have
```
import sys
sys.path.insert(0, '../../project_folder/util_folder/')
import utilities as util
```
but the last import statement is underlined in red and raises "unable to import utilities" error.
This resembles the question posted here: https://github.com/Microsoft/vscode/issues/10391
Note that I have no problem running the script as-is in Spyder (!)

Additionally, when I open my `main.py` script, the "run Python file in terminal" option is missing from the context menu. If I navigate and open another script, then return back to `main.py` then the option reappears. This is exactly the same as the issue here https://github.com/Microsoft/vscode-python/issues/3694

**Comment by Tyriar** [comment]
"run Python file in terminal" is a command from the vscode-python extension, please go through the extension team first as they might have an idea on what the underlying cause is if it is indeed a vscode issue.

**Comment by filipporemonato** [comment]
> "run Python file in terminal" is a command from the vscode-python extension, please go through the extension team first as they might have an idea on what the underlying cause is if it is indeed a vscode issue.

Sure, but what about the other - and way more important - problem?

**Comment by filipporemonato** [comment]
Wow, you closed it... amazing. Love this cherry-picking style to "fix" issues.

**Comment by Tyriar** [comment]
@filipporemonato all python support is provided by vscode-python, you should report it there as I said https://github.com/Microsoft/vscode-python. https://github.com/Microsoft/vscode/issues/10391 is about typescript support which is built in so this is the right repo for that.

**Comment by filipporemonato** [comment]
Oh, I apologise, I understood wrong. My wrong. I will report the Python issue there then, and at least now you know about the typescript thing.
