### ISSUE TITLE
Failed to update visual studio code under proxy environment

### ISSUE THREAD

**Issue by geekonloose** [Microsoft/vscode#68619]
- VSCode Version: 1.31
- OS Version: Windows 10

Steps to Reproduce:

1. My office PC is under corporate proxy environment. 
2. Visual studio code automatically tries to update, however, it failes (even the proxy credentials are provided during proxy prompt)

Does this issue occur when all extensions are disabled?: Yes/No
[](url)
[vscode-inno-updater-1550062144.log](https://github.com/Microsoft/vscode/files/2860413/vscode-inno-updater-1550062144.log)

**Comment by joaomoreno** [comment]
Do you see any errors in the devtools?

**Comment by geekonloose** [comment]
Update: 
Hi,
I don't know what happened, but yesterday it automatically got updated. 
So I am closing this issue.
