### ISSUE TITLE
Open file at line and row number by html link

### ISSUE THREAD

**Issue by Disane87** [Microsoft/vscode#68620]
It would be nice, if we can open vscode with a specific file and line/row number with a link.

Background:
We have a npm script which gets us all files with sepecific regex matches and put them in a html page and we want to open these files (with line/row numbers) from a link.

Is there a chance to get this feature?

We image something like this:
`<a href="vscode://C:/temp/file.txt:51:120">`

**Comment by octref** [comment]
@joaomoreno Giving to you since you did #4883. Also I can't find the doc you wrote for it anymore.

**Comment by octref** [comment]
Actually this is possible, see https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls.

**Comment by Disane87** [comment]
Wow thanks! Didn‘t saw that at the docs! Thank you!
