### ISSUE TITLE
Markdown preview scrolling smoothness not synced

### ISSUE THREAD

**Issue by marnovo** [Microsoft/vscode#68623]
- VSCode Version: 1.31.1
- OS Version: macOS 14.3

Steps to Reproduce:

1. Open any markdown file long enough you can scroll through it.
2. Open the command palette and run `Preview to the side`.
3. Scroll through the document with the cursor over either the editor or preview panes.
   3.1. If the cursor is over the editor pane while scrolling (thus "focused"), the editor scrolling will be very smooth (i.e. minimal steps) while the synced preview scrolling will "jump" steps (i.e. +- line-sized steps).
   3.2. If the cursor is over the preview pane while scrolling (thus "focused"), the preview scrolling will be very smooth (i.e. minimal steps) while the synced editor scrolling will "jump" steps (i.e. +- line-sized steps).

Does this issue occur when all extensions are disabled?: Yes.

**Comment by marnovo** [comment]
@vscodebot thanks but it is not a duplicate of these.

**Comment by mjbvz** [comment]
The current VS Code apis used for scroll sync are all line based. I don't think we'll be changing this anytime soon but if you notice any egregiously choppy scrolling in the preview, please open a issue with some example markdown code

**Comment by marnovo** [comment]
Understood; will do so, thanks for the quick reply.
