### ISSUE TITLE
Editor removes auto inserted indentation when formatting on type

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6862]
- VSCode Version: alpha
- OS Version: Windows 10

Steps to Reproduce:

1. settings.json
```json
{
	"editor.formatOnType": true,
	"typescript.tsserver.trace": "verbose",
	"files.trimTrailingWhitespace": true,
	"editor.trimAutoWhitespace": true
}
```
2. TypeScript file
```ts
function foo (params: string) {<cursor>}
```
Observe the blank between foo and ( which causes the formatter to kick in
3. Press enter

Observe: the newly inserted line has no indentation anymore.

The TS server trace looks like this:
```json
Sending request: change (130). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/TS6700/test.ts",
    "line": 1,
    "offset": 32,
    "endLine": 1,
    "endOffset": 32,
    "insertString": "\r\n\t\r\n"
}

Sending request: formatonkey (131). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/TS6700/test.ts",
    "line": 2,
    "offset": 2,
    "key": "\n"
}

Response received: formatonkey (131). Request took 5 ms. Success: true 
Result: [
    {
        "start": {
            "line": 1,
            "offset": 13
        },
        "end": {
            "line": 1,
            "offset": 14
        },
        "newText": ""
    }
]

Sending request: change (132). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/TS6700/test.ts",
    "line": 2,
    "offset": 1,
    "endLine": 2,
    "endOffset": 2,
    "insertString": ""
}

Sending request: change (133). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/TS6700/test.ts",
    "line": 1,
    "offset": 13,
    "endLine": 1,
    "endOffset": 14,
    "insertString": ""
}
```

The inseresting request is 132: this removes the indentation on line 2 although we haven't received any such edit from the TS server. The edit that we received from the TS server is applied via 133. So it looks like the editor is removing the indentation again although line two contains the cursor.

**Comment by alexandrudima** [comment]
Yep, it most likely is the auto whitespace removal, after pressing Enter the line number 2 is marked as containing auto-whitespace. The next edit is on line 1, so the model assumes the auto whitespace on line number 2 is safe to remove (it assumes the user voluntarily edited line number 1 and doesn't care anymore about line number 2).
