### ISSUE TITLE
Cmd fails to run when opening a terminal

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#68639]
Issue Type: <b>Bug</b>

Whenever I open a terminal I get the error `The terminal process command C:\Windows\System32\cmd' failed to launch (exit code: 2)"` . 

cmd.exe is there and works fine from from Explorer etc :(

I'm sure it broke after an upgrade and I've not knowingly changed any terminal config.

I always launch code from Git 4 Windows bash - so it picks up the git SSH credentials keys.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
toggle-format-on-save|cbr|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.5.0
EditorConfig|Edi|0.12.8
vscode-npm-script|eg2|0.3.5
html-slim-scss-css-class-completion|gen|1.5.12
vscode-pull-request-github|Git|0.4.0
gc-excelviewer|Gra|2.1.28
vscode-firefox-debug|hbe|1.7.6
search-node-modules|jas|1.3.0
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.11.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.3
stylelint|shi|0.48.0
vscodeintellicode|Vis|1.1.3
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by frobinsonj** [comment]
Related: Issue #62953

**Comment by SteveALee** [comment]
I can;t comment on that issues as it is locked.
But nothing there helped
 
> Just remove deleted files from your work space in vs code it works for me

I do not understand this

**Comment by SteveALee** [comment]
It also happens in all my projects/workspaces

**Comment by Tyriar** [comment]
> C:\Windows\System32\cmd'

It doesn't say exe, you might have a bad shell configured in your settings.json file?

**Comment by SteveALee** [comment]
Oh, great spot! I'll check. I guess I assumed would use the standard extension list that cmd uses, but is almost certainly using an API call that doesn't do that

**Comment by SteveALee** [comment]
@Tyriar 

yeah

```
Terminal › External: Windows Exec
Customizes which terminal to run on Windows.
C:\WINDOWS\System32\cmd.exe
```

but
```
Terminal › Integrated › Shell: Windows
The path of the shell that the terminal uses on Windows. Read more about configuring the shell.
C:\Windows\System32\cmd
Terminal › Integrated › Shell Args: Lin
```

Thank you very much! 

I'd forgotton there were 2 settings. The descriptions give no clue about that but the settings paths do.
