### ISSUE TITLE
Menu Bar Missing Items While Open Lang Name Files

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#68637]
Issue Type: <b>Bug</b>

1. Open a file with long name.
2. Open a file with short name.
3. Then you will see something missing in the menu bar.
4. If you maximize the window then restore, the menu bar will be normal.
Otherwise, if you open a file with short name first, this issue won't occur.

**See the GIF directly. It's easy to reproduce.**

![bug](https://user-images.githubusercontent.com/20079289/52723499-9fcce900-2f7b-11e9-94a7-fdd79591d38b.gif)

VS Code version: Code - Exploration 1.32.0-exploration (d0aafbad741c2316c92b369113abe0205f41e84e, 2019-02-13T07:02:19.413Z)
OS version: Windows_NT x64 10.0.18334

**Comment by kieferrm** [comment]
@sbatten note this is the exploration build.

**Comment by byyxx128** [comment]
@kieferrm @sbatten The stable and insider have the same issue.

**Comment by byyxx128** [comment]
@kieferrm @sbatten The stable and insider have the same issue. This issue has existed for a long time.

**Comment by sbatten** [comment]
@byyxx128 if you get the chance, please verify on the next insiders

**Comment by byyxx128** [comment]
@sbatten Yes, it has been fixed in the latest insiders.
