### ISSUE TITLE
Indentation changes is not highlighted in diff-editor

### ISSUE THREAD

**Issue by mrclolveira** [Microsoft/vscode#68633]
- VSCode Version: 1.31.1
- OS Version: Linux x64 4.15.0-45-generic

Steps to Reproduce:

1. Change any indentation of the code (white space at start of the lines)
2. Open the diff of the edited file

Does this issue occur when all extensions are disabled?: Yes
![indentation_diff](https://user-images.githubusercontent.com/10092172/52720443-89d11f80-2f9f-11e9-9fb8-4b6f78d01ff8.png)

**Comment by usernamehw** [comment]
![screenshot 63](https://user-images.githubusercontent.com/9638156/52723782-340c6f80-2fbf-11e9-8c98-a618674389e8.png)

`toggle.diff.ignoreTrimWhitespace`
