### ISSUE TITLE
Launch.JSON error

### ISSUE THREAD

**Issue by Sandy921** [Microsoft/vscode#68630]
- VSCode Version: January 2019 (version 1.31)
- OS Version: Windows 7 (64bit)

Steps to Reproduce:

1.In Launch.Json file , StoponEntry=true is this not working., when ever user has pressed PF5 the program isn't stopped in first line of code. previously it was working fine. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by Sandy921** [comment]
this is my launch.json file
![image](https://user-images.githubusercontent.com/42238008/52720325-69b85500-2fcd-11e9-98e3-6a82fd966c64.png)

**Comment by Sandy921** [comment]
could you please explain quite detail! what i need to do exactly?

**Comment by weinand** [comment]
Use VS Code's "Report Issue" command and file the issue against the Python extension.

**Comment by Sandy921** [comment]
done. thanks
