### ISSUE TITLE
Code outline not working properly

### ISSUE THREAD

**Issue by petewulf** [Microsoft/vscode#68631]
- VSCode Version: 1.30.2
- OS Version: Windows 10

From one day to another, code outline is no more working.

I always get the info "There are no open editors which have information about the code structure". 

Here is a screenshot:

![message](https://user-images.githubusercontent.com/6872322/52719335-bbe58000-2fa5-11e9-8b8f-0ba64becbe04.PNG)

Its no matter which file i have opened, it just stopped working.

**Comment by jrieken** [comment]
> From one day to another, code outline is no more working.

Since this is an old version which doesn't change it must be an extension causes this (which is what actually provides the information here). However, this issue lacks any actionable information. Please update with steps and details
