### ISSUE TITLE
Preview Markdown when language selected is "Markdown React (MDX)"

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#68635]
Issue Type: <b>Feature Request</b>

[MDX](https://mdxjs.com) support would be wonderful for side-by-side preview. Even if it just shows `Markdown` rather than not showing anything at all is probably good.

I would love to see that icon even when language `Markdown React` is shown so I can preview my Markdown even when language `Markdown React` is selected :)

<img width="218" alt="Markdown Preview Icon" src="https://user-images.githubusercontent.com/16436270/52720830-66719900-2fce-11e9-8dec-8dc535fbc9c2.png">

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by mjbvz** [comment]
MDX support is better provided by an extension. You can treat mdx files as plain markdown by setting

```json
	"files.associations": {
		"*.mdx": "markdown"
	}
```

Or changing the language mode manually. This should enable preview features.
