### ISSUE TITLE
There are two installed extensions that is the same one.

### ISSUE THREAD

**Issue by Onion-Shen** [Microsoft/vscode#68634]
Issue Type: <b>Bug</b>

the extension "Node Debug" is installed by React Native Tools,I installed it firstly.The "Node Debug" extension show again with the newest VSCode installed.It can not install only once?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|4.00GB (0.15GB free)|
|Process Argv|-psn_0_421991|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
include-autocomplete|ajs|0.0.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
gitlens|eam|9.5.0
vscode-npm-script|eg2|0.3.5
search-node-modules|jas|1.3.0
typings-autoinstaller|jvi|1.2.0
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.1.0
cpptools|ms-|0.21.0
node-debug2|ms-|1.31.6
vscode-lldb|vad|1.2.1
vscode-react-native|vsm|0.8.0
c-cpp-snippets|wlh|0.1.0

</details>

**Comment by Onion-Shen** [comment]
![image](https://user-images.githubusercontent.com/11938525/52720824-57491600-2fe3-11e9-9e30-f637ab51d643
![pic](https://user-images.githubusercontent.com/11938525/52720942-95ded080-2fe3-11e9-8687-2e82aa3fff74.png)
.png)

**Comment by sandy081** [comment]
@Onion-Shen May I know how do you installed React Native Tools extension that ends up installing Node Debug again?

**Comment by Onion-Shen** [comment]
The react native tools extension is installed in 2017, the node debug extension is a dependency of it.I don't remember  node debug extension is installed at VSCode before I installed react native tools extension. The node debug extension show again in extensions after an updating of VSCode at someday.

**Comment by sandy081** [comment]
@Onion-Shen I think you are seeing the same issue as https://github.com/Microsoft/vscode/issues/66774
