### ISSUE TITLE
Cannot debug code extension

### ISSUE THREAD

**Issue by sgwozdz** [Microsoft/vscode#68649]
Something is heavily wrong with code on my laptop. I saw you have few similar issues bot I couldn't find the same. Opening it as question for now.

I've got my own code extension, of course i tt's node.js server + client. It's done very similar to samples.
But from some time I cannot debug. Scripts are not loaded for any node.js application, which implies that I cannot set brakepoint.
![image](https://user-images.githubusercontent.com/5880551/52739033-4fcc4180-2fd0-11e9-8083-308d32a4a680.png)

Any ideas how to proceed with it ?

I've tried insider, I've tried previous versions but no luck.
Also I played for a long time with settings, but also no luck on this.

**Comment by johnspurlock** [comment]
Seeing this as well in 1.31.1

**Comment by weinand** [comment]
@sgwozdz please provide more information so that we can actually investigate this.
What version of VS Code?
What platform?
How does your launch config look like?
What version of node.js are you using?

**Comment by sgwozdz** [comment]
@weinand sorry for late response.
vscode 1.31.1
node 10.15.1
Windows 10 x64
I will just provide repository url. I have a feeling that it's something minor but I cannot find it. 
Repo: [link](https://github.com/sgwozdz/jenkinsfile-support/tree/dev)

Looks like now I'm able to debug for example [lsp-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample). So I tried to use it's settings but without success.
