### ISSUE TITLE
Seems string continuous when opened a single quote inside double quotes

### ISSUE THREAD

**Issue by gBragamonte** [Microsoft/vscode#68644]
Version: 1.31.0
Commit: bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce
Date: 2019-02-07T17:34:29.315Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

Steps to Reproduce:

1. Using PHP, create a variable of type string that concat with a string function
2. Like this:

```php
$tst = "UPDATE TABLE SET ACTIVE ='S' WHERE ID IN ('" . implode("', '", [1, 2, 3]) . "')";
```

Works well but editor ignore double quote closure, see:

![image](https://user-images.githubusercontent.com/30661999/52732691-f2bc9580-2fa7-11e9-82b2-b9c45a355e89.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This issue was moved to atom/language-php#355
