### ISSUE TITLE
Go to Definition no longer reveals file in sidebar

### ISSUE THREAD

**Issue by uphlewis** [Microsoft/vscode#68641]
Issue Type: <b>Bug</b>

Previous to v1.31, clicking `Go to Definition` on a symbol would also reveal the "jumped to" file in the sidebar. This is useful in large projects when wanting to dig into how a vendor package works, since the sidebar jumps to the vendor package directory, so accessing other files in the package is quick and simple.

This is no longer the case- the sidebar does not focus on the current file, so instead I have to right click on the file's tab and select `Reveal in Sidebar`.

Intentional or not, I can't find any settings which change this behaviour back to how it was before.

Thanks for the awesome software :)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2058)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (0.57GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
htmltagwrap|bra|0.0.7
regex|chr|0.2.0
vscode-gitignore-syntax|dun|0.1.2
apacheconf-snippets|eim|1.2.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.28
composer|ika|0.7.1
smarty|imp|0.3.0
twig-language-2|mbl|0.5.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.1
php-docblocker|nei|1.7.0
vetur|oct|0.15.0
vscode-docker|Pet|0.5.2
phpstorm-snippets|phi|1.1.1
phpdoc-comment-vscode-plugin|rex|1.1.0
vscode-icons|rob|8.1.0
code-settings-sync|Sha|3.2.4
open-in-browser|tec|2.0.0
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This works for me.
Do you have explorer.autoReveal setting set?
Can you repro with vscode insiders? https://code.visualstudio.com/insiders/

**Comment by uphlewis** [comment]
Yes, explorer.autoReveal was the first thing i checked.

Haven't tried with the insider build.

Since my initial post, i've realised that the issue is intermittent. I'll try and work out the pattern and will let you know

**Comment by isidorn** [comment]
Please let me know the exact reproducable steps since I can not repro it.

**Comment by uphlewis** [comment]
I cant seem to reproduce it at all now ! 

Only thing i've changed since posting is reboot my machine, so must have been an issue on my end.

Sorry to waste your time
