### ISSUE TITLE
Powershell variable $env:VSCODE is gone from recent releases.

### ISSUE THREAD

**Issue by jwhipp** [Microsoft/vscode#68643]
VScode used to (I'd say it disappeared in 1.31) set a Powershell environment variable: $env:VSCODE which seems to have disappeared.   I was using it to set various things when PS was loaded using the integrated terminal.  Wondering why it was removed. 

- VSCode Version:  1.31.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open VScode
2. Launch an integrated terminal preset to launch Powershell
3. Run:  $env:VSCODE

I'll be honest, I don't remember what was in this variable, I just checked that is was not null.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I didn't know this variable existed, but we do set TERM_PROGRAM and TERM_PROGRAM_VERSION for this very reason:

https://github.com/Microsoft/vscode/blob/73ff13f5debf91fc1d7a89a2f336543b2baa1ee5/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L53-L54

They are also a relatively standard thing to set across terminals.
