### ISSUE TITLE
insertLineAbove/Below negate Soft Undo

### ISSUE THREAD

**Issue by targetcreature** [microsoft/vscode#68646]
Cursor sticks to new line and cannot be soft undone.

- VSCode Version: 1.31.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. <kbd>ctrl</kbd>+<kbd>enter</kbd> or  <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>enter</kbd>
2. <kbd>ctrl</kbd>+<kbd>u</kbd>

Does this issue occur when all extensions are disabled?: Yes

**Comment by NotWearingPants** [comment]
This is not a bug.
Every change to the document's text is undo-able, and not soft-undo-able.

This is the same as:
1. type `a`
2. ctrl+u

I believe this is the expected behavior.

**Comment by alexdima** [comment]
That is expected behaviour. Cursor undo will only undo the cursor position up until the last file edit.
