### ISSUE TITLE
Make panels easier to resize when using touch and mouse

### ISSUE THREAD

**Issue by brokenthorn** [Microsoft/vscode#68652]
I would really like VSCode to allow us to resize panels in the same way that some other IDEs like those from JetBrains allow us to do.

Here is an example from JetBrains DataGrip:
<img src="https://user-images.githubusercontent.com/2119004/52740849-a770aa00-2fdc-11e9-8619-aeec1dc110a1.png" width="50%"/>

Currently, VSCode requires us to hit the 1px border that separates the panels from the rest of the UI elements. With a mouse it's fairly easy but could be made easier. With touch input I imagine it's a lot harder.

In VSCode this would probably be one of (by CSS selector):

- `#workbench\2e parts\2e panel > div.composite.title` to allow dragging the entire toolbar regardless of where you drag from, including starting a drag operation on a button or other control,
- `#workbench\2e parts\2e panel > div.composite.title > div.title-actions > div` to allow dragging from the monaco-toolbar's empty parts.

**Comment by isidorn** [comment]
Dup of some issue assigned to me and sbatten. If you want to find it search for issues tagged with workbench-layout
