### ISSUE TITLE
F11 binding is taken by System on Mac

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#68655]
Issue Type: <b>Bug</b>

The default key binding for step into is "F11", which at least on my Mac is already wired by the system to show the desktop, so I always have to rebind this.  Should there be a better default shortcut on Mac?

VS Code version: Code - Insiders 1.32.0-insider (d18d0edce11ac396bf7654ac96e0d522681b5553, 2019-02-11T17:46:35.980Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
vscode-antlr4|mik|2.1.1
vscode-azurestorage|ms-|0.5.0
azure-account|ms-|0.8.0
vscode-docker|Pet|0.5.2

</details>

**Comment by weinand** [comment]
By default all function keys are bound on macOS. That's the reason why software developers typically enable the "Use F1, F2, etc. keys as standard function keys" option:
<img width="668" alt="2019-02-15_08-35-42" src="https://user-images.githubusercontent.com/1898161/52841538-df6f0e80-30fc-11e9-982e-002f006fbdde.png">

**Comment by StephenWeatherford** [comment]
I do have that setting set.  Without it, F11 decreases volume.  With it, F11 shows the desktop.  As far as I can tell, no other function key has a system binding in both modes.  So again, I still have to rebind F11 on Mac either way.
