### ISSUE TITLE
breakpoint shown in editor is too high to see the important information

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#68654]
Issue Type: <b>Bug</b>

When you have break on all exceptions turned on, and it stops at an exception, it's nice that you can see the breakpoint info right in the editor, but frequently the call stack is so long that you see the bottom of the stack and have to scroll up several screens to see anything useful. In the example below, I had to scroll up about 6 full screens (!) to get to the code and top of the call stack.  This is especially annoying when you stop at a bunch of expected exceptions from within vscode that you can't do anything about (common when debugging extensions), because you can't just F5 past them without having scrolled up first to figure out what the problem is.

Please display the top of the call stack rather than the bottom.  Thanks!

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/6913354/52743323-9dc05580-2f8e-11e9-8c98-f1de4206cb0f.png">

VS Code version: Code - Insiders 1.32.0-insider (d18d0edce11ac396bf7654ac96e0d522681b5553, 2019-02-11T17:46:35.980Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
vscode-antlr4|mik|2.1.1
vscode-azurestorage|ms-|0.5.0
azure-account|ms-|0.8.0
vscode-docker|Pet|0.5.2

</details>

**Comment by isidorn** [comment]
I limited the height of the stack to 500px. Try it out in Thursday vscode insiders and let us know how it owkrs for you

**Comment by roblourens** [comment]
@isidorn it looks like you were already truncating the stack to 10 lines, and this prevents the widget from growing past 500px when the text wraps, is that right?

This helps but it still depends on the size of the editor window. It would be better if we can reveal the top line after showing the exception widget, is that possible at all? 

Made up example:

Decent size editor window:

![image](https://user-images.githubusercontent.com/323878/53454168-30271700-39db-11e9-98c8-27f865b6c8e4.png)

Still not a good experience when breaking on exception:
![image](https://user-images.githubusercontent.com/323878/53454188-3ae1ac00-39db-11e9-90dd-fc3e254a4d27.png)

**Comment by isidorn** [comment]
Good catch. Now I am revealing the editor line so the top is always shown
