### ISSUE TITLE
Hover misses border in Dark theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#6865]
![image](https://cloud.githubusercontent.com/assets/22350/15536515/eeb16f06-2271-11e6-80d1-011f0bb2e78c.png)

**Comment by joaomoreno** [comment]
Not really sure who owner is... cc @bgashler1 @aeschli @jrieken

**Comment by jrieken** [comment]
@alexandrudima knows - we have a few dups by now ;-)

**Comment by alexandrudima** [comment]
Dup of #6247
