### ISSUE TITLE
CLI code snippets do not change font color

### ISSUE THREAD

**Issue by MashaMSFT** [Microsoft/vscode#68659]
When I use a code block for something like powershell or t-sql, the colors of the font change, making it easier to parse the text. 

For example
```powershell
```
![image](https://user-images.githubusercontent.com/32783170/52749662-b59fd580-2f9e-11e9-98be-dc733873df04.png)

Font color changes in accordance to powershell standards. 

However, when I do so for CLI, the color doesn't change, and it should be changing, right?

```cli
```
![image](https://user-images.githubusercontent.com/32783170/52749679-be90a700-2f9e-11e9-84d2-a0923fa98df1.png)

No font color change in accordance to CLI standards.

**Comment by mjbvz** [comment]
Where else is `cli` supported? It doesn't seem to work on github

**Comment by MashaMSFT** [comment]
Sorry, I'm not sure I understand the question..  How does it not work in github? When I paste code CLI code into Powershell ISE, it changes color.. is that what you mean?

**Comment by mjbvz** [comment]
What other sites or tools support using `cli`as a language identifier in markdown?

**Comment by MashaMSFT** [comment]
oh... i'm not sure that any do, to be honest with you :( i don't know enough about cli to have seen it anywhere else. it just looks odd on the page in vs code when we have t-sql in color, and then az cli is allt he same color.

**Comment by mjbvz** [comment]
Try using `shell` or `powershell` instead. 

There's also https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example that covers how extensions can contribute support for new fenced code block languages
