### ISSUE TITLE
root directory 

### ISSUE THREAD

**Issue by ROHITkumaw** [Microsoft/vscode#68650]
Issue Type: <b>Bug</b>

i dont understand when i opening live server root directory file is opening i dont understand why 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|1.8.1
LiveServer|rit|5.5.1
vscode-icons|rob|8.1.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by kieferrm** [comment]
Please file the issue against the live server extension. Thanks!

**Comment by ROHITkumaw** [comment]
Thanku sir ....as I am a begginer in javascript what shoud I do after i will complete my javascript help me sir ...I will work hard  on this ...
