### ISSUE TITLE
Intellisense stops providing suggestions for further properties from an interface after any property is fulfilled

### ISSUE THREAD

**Issue by vladfrangu** [Microsoft/vscode#68656]
Issue Type: <b>Bug</b>

1. Open up the suggestion box (CTRL + Spacebar)
2. Select any of the properties of an interface, and insert it with the proper value
3. Try auto-completing another property via the same UI

This wasn't an issue in VSCode 1.29.1 but IS present on both latest stable build (1.31.1) and latest Insiders build

![GIF Showing the Bug](https://breaker.party/js3o3ihkbbf0dbd.gif)

Typings for Klasa Module: https://github.com/dirigeants/klasa/blob/1d5c5df8b620cb70ecc0497d9fdacaf1e9fac3ff/typings/index.d.ts#L1002-L1028

VS Code version: Code - Insiders 1.32.0-insider (0d50120c71dcb9430997d6cd9c0ed1daaf65ce5c, 2019-02-12T18:31:10.402Z)
OS version: Windows_NT x64 10.0.17763

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 3010)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
klasa-vscode|bdi|0.3.0
emojisense|bie|0.4.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.7.0
discord-vscode|icr|3.2.1
git-indicators|lam|2.1.1
prettify-json|moh|0.0.3
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1182
debugger-for-chrome|msj|4.11.2
vetur|oct|0.15.0
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
polacode|pnp|0.2.2
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.4
vscode-wakatime|Wak|1.2.5
quokka-vscode|Wal|1.0.183

</details>

**Comment by mjbvz** [comment]
I'm not able to reproduce this in the current VS Code insiders build with the simple JavaScript code:

```js
// @ts-check

import { Client } from 'klasa';

const client = new Client({
    commandEditing: true,
    
});
```

![screen shot 2019-02-13 at 5 18 17 pm](https://user-images.githubusercontent.com/12821956/52755638-7334c380-2fb3-11e9-85d8-c22fe4dd68f2.png)

Can you please share the code from your example

**Comment by vladfrangu** [comment]
I forgot to mention this in my main issue description, and I apologize.

You are correct, in a `.js` file, this doesn't occur

![](https://join-the.gawesome.club/js4ccwxlb716707.png)

My issue happens in a `.ts` file (which I didn't specify, and I apologize for it 😅)

![](https://join-the.yiff.fun/js4ce3xubbd90c1.png)

Is this a TypeScript issue? Or am I doing something wrong? I can share the tsconfig, tslint and my VSCode settings, if needed

**Comment by mjbvz** [comment]
Yes please share your tsconfig. I cannot repo this in a ts file either:

![screen shot 2019-02-14 at 6 32 10 pm](https://user-images.githubusercontent.com/12821956/52830752-e78c6700-3086-11e9-8655-ad6780cebdfe.png)

**Comment by vladfrangu** [comment]
My tsconfig is available here: https://gist.github.com/vladfrangu/b7849837d3495bc32ad6e161ac763ce4

I also forgot to mention that I am using the master version of klasa (`yarn add dirigeants/klasa discordjs/discord.js` or `npm i dirigeants/klasa discordjs/discord.js`). It is possible that the current npm version (0.4.0) doesn't have this issue.

**Comment by vladfrangu** [comment]
Update: After some quick testing, it seems like this is affected only at the top-level, that means nested properties have auto completes, but their base does not.

Gif:

![](https://i-would-love-some.yiff.fun/js7wid97bfe645a.gif)

**Comment by mjbvz** [comment]
This sounds like a duplicate of https://github.com/Microsoft/TypeScript/issues/30138

Can you please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) to see if this has been fixed

**Comment by vladfrangu** [comment]
Seems like the latest Insiders version (which comes with TypeScript 3.4.0-dev.20190306) fixes this, so I'll close thi. Thank you so much!
