### ISSUE TITLE
Strict null check 'vs/workbench/contrib/debug/*'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#68657]
Part of #60565

Tracks updating files under `vs/workbench/contrib/debug/` to have strict null checking. The current files are currently eligible: 

-`'vs/workbench/contrib/debug/common/debugModel.ts'`
-`'vs/workbench/contrib/debug/electron-browser/breakpointWidget.ts'`
- `'vs/workbench/contrib/debug/node/debugger.ts'`
-`'vs/workbench/contrib/debug/node/terminals.ts'`

Other files under `debug` may become eligible once these files are strict null checked

**Steps**

1. Add target file to the `files` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works

**Comment by isidorn** [comment]
@weinand let me know if you would like to help out here?
`debugger.ts` would be a good candidate to start

**Comment by weinand** [comment]
@isidorn I can look into debugger.ts...

**Comment by isidorn** [comment]
@weinand cool, if you like it feel free to pick up other files.
I finished /common and plan to continue with /browser tomorrow.

**Comment by weinand** [comment]
no, I won't like it.

**Comment by isidorn** [comment]
@weinand could you look into `loadedScriptsView.ts`? I can also look into it if you prefer.

**Comment by weinand** [comment]
@isidorn will do

**Comment by weinand** [comment]
`loadedScriptsView.ts` done

**Comment by isidorn** [comment]
This is done.
Only 3 test files remain which depends on `contrib/files` to be null check aware (which I am looking into right now as part of https://github.com/Microsoft/vscode/issues/70338)

@weinand thanks for help!
