### ISSUE TITLE
Add API to focus on the specified folder in explorer

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#68667]
Issue Type: <b>Feature Request</b>

In some scenarios, we need to switch the tree view of the workspace through an API call.

Of course, there is no such API at present.

From this we can introduce: Focus on any workspace/arbitrary files

```ts
export function focus(workspaceUri: URI, options?: FocusOptions): Thenable<void>;

vscode.workspace.focus(workspaceUri)
```

This API should be very useful for third-party extensions.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by sandy081** [comment]
@axetroy Not sure what you want to focus here? Do you mean the custom tree view?

**Comment by axetroy** [comment]
@sandy081
I am developing an extension

Suppose a scene, like I have N workspaces

I need to call an API to focus on the resource manager, then expand the specified workspace, and close the other workspaces.

But unfortunately, it seems that there is no such API.

This may require a series of APIs about the resource manager.

for example:

```typescript
// defined API
export function focus(workspaceUri: URI, options?: FocusOptions): Thenable<void>;

// focus on resouce explorer and expand the specified workspace
vscode.workspace.focus(workspaceUri)
```

**Comment by bpasero** [comment]
@axetroy with "close the other workspaces" you mean collapsing their tree nodes in the "File Explorer"?

**Comment by axetroy** [comment]
@bpasero 
Yes. that's what I mean
