### ISSUE TITLE
Value of `this` when debugging Typescript

### ISSUE THREAD

**Issue by vakrilov** [Microsoft/vscode#6866]
- VSCode Version: 1.1
- OS Version: Windows

[Link to original issue](https://github.com/NativeScript/nativescript-vscode-extension/issues/47)
I'm using the [NativeScript extension for VisualCode](https://github.com/NativeScript/nativescript-vscode-extension) and I have the following issue when debugging:

Lambda/arrow functions that have `this` inside their body can be confusing.
Here is and example TS code.

```
promise.then((value) => {
  console.log("message: " + this.message);
  // ...  
})
```

I stop on break point after the `console.log()` and add a watch expression for `this.message` and here is the conflict:
- watch expression result: `undefined`
- console output: `message: hi there`

The reason for this is that TS code gets transpiled to the following:

```
var _this = this;
promise.then(function (value) {
  console.log(_this.message);
});
```

Now its obvious now that my watch expression should have been `_this.message`. However, this can get quite confusing is you forget that you are currently debugging a lambda function. 

I am wondering if there is someway to handle that.

**Comment by weinand** [comment]
see discussions in #23143 and #13967
