### ISSUE TITLE
Formatting  html document remove all html tags after new update

### ISSUE THREAD

**Issue by devikprod** [Microsoft/vscode#68660]
Issue Type: <b>Bug</b>

After installing version 1.31.1 when I format an HTML document all content is cleaned.
I'm using the popup menu opened with the mouse right-click.
It seems due to an extensions with the new ver.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6498DU CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|11.89GB (6.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
mapfile|chi|0.0.1
sql-formatter|cym|1.0.2
tslint|eg2|1.0.43
html-to-javascript-string|evi|0.0.6
php-debug|fel|1.12.6
html-slim-scss-css-class-completion|gen|1.5.12
live-html-previewer|hdg|0.3.0
raml|jep|1.0.1
twig-language|mbl|0.5.1
dotenv|mik|1.0.1
hg|mrc|1.3.0
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.11.2
oracle-plsql|myc|1.0.3
php-docblocker|nei|1.7.0
vscode-php-getters-setters|php|1.2.3
LiveServer|rit|5.5.1
php-formatter|Sop|0.2.4
html-snippets|wge|0.1.5
twig|wha|1.0.2

</details>

**Comment by kieferrm** [comment]
To make sure it's the built-in html formatter, please disable all extensions (`code -disable-extensions`) and verify that it's still happening. If so, if possible, pls attach a sample HTML file that shows the issue for you. Thanks!

**Comment by octref** [comment]
Can you run `Ctrl + Shift + P` and `Developer: Print Available Formatters`? Then run the command `Developer: Toggle Developer Tools` and paste the result.

Whatever formatter extension you are using is likely the culprit.
