### ISSUE TITLE
F12在部分情况下未能跳转到定义

### ISSUE THREAD

**Issue by NeroCho** [Microsoft/vscode#68664]
Issue Type: <b>Bug</b>

下面是我的使用场景。全局 NODE_PATH=/Users/nero/Project/winner2 配置多个模块时。winner2文件夹下面包含两个文件夹node_modules,winner-common。node_modules下也有个文件夹叫winner-common（因为一些原因里面部分内容需要分开）
当require('winner-common/common/ErrCode');跳转定义是成功的。
当require('winner-common/redis/redisServer01');跳转定义失败。
项目运行是OK的，程序也能加载到对应的模块。但就是不能再编辑器里面跳转到定义

Below is my usage scenario. Global NODE_PATH=/Users/nerocho/Project/winner2 When configuring multiple modules. The winner2 folder contains two folders node_modules, winner-common. There is also a folder called winner-common under node_modules (for some reasons, some of the content needs to be separated)
When require('winner-common/common/ErrCode'); the jump definition is successful.
When require('winner-common/redis/redisServer01'); the jump definition failed.
The project operation is OK, and the program can also be loaded into the corresponding module. But just can't jump to the definition inside the editor.

希望解决

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.4
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.24.0
gitlens|eam|9.5.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
vscode-guid|hea|1.4.0
docthis|joe|0.7.1
solidity|Jua|0.0.49
node-module-intellisense|lei|1.5.0
sftp|lix|1.9.3
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.31.4
cpptools|ms-|0.21.0
Go|ms-|0.9.2
vetur|oct|0.15.0
code-rhythm|onv|1.0.6
vscode-docker|Pet|0.5.2
vscode-css-peek|pra|2.2.0
java|red|0.38.0
prettier-now|rem|1.4.9
LiveServer|rit|5.5.1
vscode-icons|rob|8.1.0
code-settings-sync|Sha|3.2.4
code-spell-checker|str|1.6.10
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-maven|vsc|0.14.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
We don't support intellisense based on NODE_PATH, see #28707
