### ISSUE TITLE
error code 183. movefile fail. file already exist. inno_updater.exe

### ISSUE THREAD

**Issue by kyul1029** [Microsoft/vscode#68666]
Issue Type: <b>Bug</b>

movefile fail. error code 183. file already exist.
...\AppData\Local|Programs\Microsoft VS Code\tools\inno_updater.exe

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.6.2
vscode-eclipse-keybindings|alp|0.10.0
jsonviewer|cci|1.2.2
gc-excelviewer|Gra|2.1.29
open-file-from-path|jac|1.2.5
Kotlin|mat|1.7.0
vscode-html-format|moh|0.0.3
vscode-language-pack-ko|MS-|1.30.2
quicktype|qui|12.0.46
java|red|0.38.0
open-in-browser|tec|2.0.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.2

</details>

**Comment by joaomoreno** [comment]
Where did you see this error?
