### ISSUE TITLE
Clicking on an error in the Problems tab does not open the file

### ISSUE THREAD

**Issue by prime31** [Microsoft/vscode#68675]
[VSCode.mp4.zip](https://github.com/Microsoft/vscode/files/2863349/VSCode.mp4.zip)

Issue Type: <b>Bug</b>

- create an error in a C# file
- compile and notice in the Problems tab the error will appear
- click on the problem which should jump you to the file but instead it just flickers a tab (seems t open it and then close it immediately)

Video attached showing the bug in action.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
make-hidden|dev|2.3.3
vscode-solution-explorer|fer|0.3.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.3
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
vscode-icons|rob|8.1.0
code-settings-sync|Sha|3.2.4
ayu|tea|0.18.0
unity-debug|Uni|2.6.6

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Problems are created for the files which does not exist. Please file an issue against c# extension - https://github.com/OmniSharp/omnisharp-vscode/issues
