### ISSUE TITLE
Attaching to language server no longer shows output

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#68670]
- Clone [this branch](https://github.com/Microsoft/vscode-extension-samples/commits/octref/log-bug) of vscode extension samples
- Open `lsp-sample`
- `npm i && npm run build`
- Run the compound `Client + Server` config, open a `*.txt` file
- :bug: Notice the `console.log` statements in [this commit](https://github.com/Microsoft/vscode-extension-samples/commit/320a96b4fa452eea6ba30ff6c3c30727101c1a5c) neither show up in the host window's `Output -> Language Server Example`, nor in the Debug Console of the development window. It should print `test` on both initialization and completion.

**Comment by darkbasic** [comment]
I confirm that console.log messages are not shown. It pauses if I set a breakpoint, but nothing is shown in the server debug console.

**Comment by octref** [comment]
ping @weinand

**Comment by darkbasic** [comment]
In can be easily verified with the lsp example: https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample

**Comment by weinand** [comment]
@roblourens @isidorn 
I can reproduce this with the simple hello world extension:
- console.log messages no longer appear in the debug console
- I see an object "ApplicationInsights:CorrelationIdManager" instead:

![2019-03-19_16-30-10](https://user-images.githubusercontent.com/1898161/54619225-8a5c4a80-4a64-11e9-87de-27d8a38c6d2d.png)

**Comment by isidorn** [comment]
Yes I see the same.
The issue is that I am not getting the Output event from the node debug extension neither I am getting the extension log from the broadcast service `vscode:extensionLog`. Forwarding to @roblourens 

@roblourens if you are unaware of any changes in this area then we should bisect to find what change caused this regression
fyi @bpasero for broadcast service

**Comment by weinand** [comment]
Since `console.log` works for simple node.js programs (non-EH-debugging), I suspect the issue is with the broadcast service.

**Comment by bpasero** [comment]
I cannot reproduce, for me it works:

![image](https://user-images.githubusercontent.com/900690/54624768-4a01ca00-4a6e-11e9-9954-124bdad0959b.png)

**Comment by roblourens** [comment]
I haven't tried it yet but I assume you guys have selected the correct debug console? Looks like this is about logs from the server and I think the broadcast service is only for EH not an LSP server.

**Comment by bpasero** [comment]
I tested this:
* yo code
* typescript extension
* run it

**Comment by roblourens** [comment]
Normal EH logging works fine for me, I can repro the issue with logs from the language server. That's weird, I don't get events from node. Reproes with chrome devtools too. I'll look into it.

**Comment by darkbasic** [comment]
Probably it depends on which vscode version you are using, because updating the deps did the trick for me: https://github.com/Microsoft/vscode-extension-samples/pull/166

I still don't see any logging in the server debug console, but at least I can see it in the client output.

**Comment by darkbasic** [comment]
![10](https://user-images.githubusercontent.com/1047358/54627459-c5b24580-4a73-11e9-9ce2-56300a2eb82f.png)

**Comment by roblourens** [comment]
That still doesn't fix it for me. I'm very confused tbh. I don't see anywhere that are are intercepting console logging. Debugging into the `console.log` call, it seems to do the normal thing. I don't know how it gets lost.

**Comment by roblourens** [comment]
It looks like the client wants to get stdout/err from the server, I guess to pipe logs through to the client. But it seems to not work? And we should still get logs through the debug protocol, and I don't. https://github.com/Microsoft/vscode-languageserver-node/blame/master/client/src/main.ts#L379

@dbaeumer do you know anything about this?

**Comment by octref** [comment]
FYI the old sample has code similar to this in the server entry point:

```ts
import { createConnection, InitializeParams, InitializeResult } from 'vscode-languageserver';

const connection = process.argv.length <= 2 ? createConnection(process.stdin, process.stdout) : createConnection();

console.log = connection.console.log.bind(connection.console);
console.error = connection.console.error.bind(connection.console);
```

**Comment by roblourens** [comment]
Where is that? I don't see it in the version that I have cloned.

**Comment by dbaeumer** [comment]
@octref Did you write this. I am pretty sure I never added such code 

```ts
import { createConnection, InitializeParams, InitializeResult } from 'vscode-languageserver';

const connection = process.argv.length <= 2 ? createConnection(process.stdin, process.stdout) : createConnection();

console.log = connection.console.log.bind(connection.console);
console.error = connection.console.error.bind(connection.console);
```

The stdout from the language server is written to the server's output channel here https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L385. This has always been the case. I haven't changed this code in a long time. So I am confused that the output every made it to the debug panel.

**Comment by octref** [comment]
Oh that's because I forked Vetur from html server, the original code belongs to @aeschli: https://github.com/Microsoft/vscode/commit/cb5a6e77db41283e8dc6bc8ab5c75c439d04320d#diff-953fd93988b92567bdca7e583d0c7373R20.

**Comment by octref** [comment]
OK for people who want this to continue work as it was, add this to server entry point:

```ts
console.log = connection.console.log.bind(connection.console);
console.error = connection.console.error.bind(connection.console);
```
