### ISSUE TITLE
Provide Syntax Highlighting information for clipboard (for @paste_app)

### ISSUE THREAD

**Issue by dutzi** [microsoft/vscode#68673]
Currently when copying stuff and opening [Paste App's](https://pasteapp.me/) clipboard dashboard there's no syntax highlighting:

![image](https://user-images.githubusercontent.com/927310/52763080-f4776f00-3022-11e9-9285-d891ba380aef.png)

That's not the case when copying text from Xcode:

![image](https://user-images.githubusercontent.com/927310/52763094-035e2180-3023-11e9-81de-42fad75c91e4.png)

Looking at [this thread](https://twitter.com/yohasebe/status/770804360976617472) it seems like it's up to the app setting the clipboard's content.

I know this is a silly feature request, and might be app-specific. But it would be great if syntax highlighting worked globally :)

**Comment by kieferrm** [comment]
@rebornix for comment.

**Comment by rebornix** [comment]
We did put code with syntax highlight into the clipboard and the target app can read them from the clipboard by accessing HTML content.

![syntax-highlight-copy](https://user-images.githubusercontent.com/876920/62405316-cb0abb00-b550-11e9-8276-058e1d38c9c5.gif)
