### ISSUE TITLE
New terminal lines rendering is not at the same level when I set the line height greater than one

### ISSUE THREAD

**Issue by x1nfly** [Microsoft/vscode#68678]
- VSCode Version: 1.31.1 (1.31.1)
- OS Version: 10.14.3
- Terminal Version: iTerm2 Build 3.2.7
- Use zsh and oh-my-zsh

Steps to Reproduce:

1. Set the setting pair like: `"terminal.integrated.lineHeight": 1.5`
2. Open the terminal window, it is shown like below.
![image](https://user-images.githubusercontent.com/17685647/52766307-bea5ab00-3061-11e9-8f25-8ee2e513f732.png)

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
Should be fixed already, sorry about the delay.

**Comment by x1nfly** [comment]
Yep, It's work now. This bug caused me do not use the terminal of vsc these days. Anyway, thx for ur works. Love this editor so much :P
