### ISSUE TITLE
Internal error: illegal access for variables and watch expressions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6867]
- VSCode Version: alpha
- OS Version: os x
- node version: had node 6.2 installed but reverted back to 6.1 and still see this behavior

Steps to Reproduce:

1. Debug any simple js application
2. Try to evaluate `console` in watch or repl -> get an 'Internal error: illegal access'
3. I also get this error for some variables in the variables view

![screen shot 2016-05-25 at 12 53 14](https://cloud.githubusercontent.com/assets/1926584/15537594/ac5df358-2277-11e6-913a-943446dfbb75.png)

**Comment by rostacik** [comment]
Hi gents.
Same error here. Windows 8.1, VS Code 1.1.1 + insides also. 
![vscode](https://cloud.githubusercontent.com/assets/429190/15651447/02528268-2680-11e6-9107-cf8395bf42a3.png)

**Comment by weinand** [comment]
@rostacik that's [a V8 bug in node 6.x](https://github.com/node-inspector/node-inspector/issues/864). Our workaround for this problem seems to work for most, but not for all. Until node 6.2.1 arrives the workaround for those that are hit by this is to use node 5.x.

**Comment by rostacik** [comment]
@weinand yes sir, I can confirm that with v4.4.5 VS Code behaves as expected, thanks for quick reply.

**Comment by weinand** [comment]
This problem no longer occurs in node v6.2.1.
