### ISSUE TITLE
No textDocument/completion messages get sent when typing at the start/middle of an identifier

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#68672]
- VSCode Version: 1.31.0
- OS Version: Windows

Steps to Reproduce:

1. I'm using the C/C++ extension for completion, but I observe the same behavior with TypeScript (I don't know if the root cause is the same).
2. Use some .cpp code like
```
struct ss { int abc; int aab; };
void main()
{
ss s;
s.ab
}
```

Bug: Then typing "a" before "ab" fails to send a textDocument/completion and typing "a" in the middle also fails, but typing "c" at the end succeeds. Our C/C++ extension would prefer to be sent more completion messages so we can decide whether or not to offer completions.

Does this issue occur when all extensions are disabled?: Yes (reproed via the C/C++ extension).

**Comment by jrieken** [comment]
Yes, quick suggestions are designed to work at the *end* of words only

**Comment by sean-mcmanus** [comment]
Can this issue be morphed into a feature request to allow extensions to enable completion events to be sent when edits are made to the start/middle of an identifier. It should be up to the extension whether they have enough language info to provide suggestions or not. The user report at https://github.com/Microsoft/vscode-cpptools/issues/3169 shows use cases where our extension would be able to give completions were we to be sent the messages. If there is some reason why enabling this behavior would give unexpected, undesirable results, let me know so I can explain that to our users.
