### ISSUE TITLE
System versioning on tables doesn't generate correct script

### ISSUE THREAD

**Issue by Michaeljohannessen** [Microsoft/vscode#68684]
- VSCode Version: 1.31
- OS Version: Win 10 16299.904

Steps to Reproduce:

If you have a table with "system-versioning on" you would like to drop-script, the result will be the following:

ALTER TABLE [DBO].[Tablename] SET ( SYSTEM_VERSIONING = OFF  )
GO
DROP TABLE [DBO].[Tablename]
GO

But this doesn't generate the drop table for the system-versioning table itself.

Generated with SSMS it looks like:

alter table [DBO].[Tablename] set ( system_versioning = off  )
go

drop table [DBO].[Tablename]
go

drop table [DBO].[TablenameHistory]
go

Minor issue, but would be good to handle when script is generated by ADS ;)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
Please file the issue against the extension you have installed for handling this. Thanks!
