### ISSUE TITLE
Remove and rename watch expression keypoard shortcuts have no effect 

### ISSUE THREAD

**Issue by ersteller** [Microsoft/vscode#68687]
Issue Type: <b>Bug</b>

Open debug view and create a new watch expression.
Select it and press delete (default debug.removeWatchExpression). 
Result: No effect
Expected result: The watch expresseion is deleted.

also press F2 (default for debug.renameWatchExpression). 
Result: No effect
Expected result: The watch expresseion is in edit mode.

this is observed since version 1.30. 
correct behavior up to version 1.29. 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.5.0
python|ms-|2019.1.0

</details>

**Comment by isidorn** [comment]
I confirm this issue.
We need to contribute the command with the proper `when` context.

**Comment by jjasoncool** [comment]
This issue still happening with extension PHP Debug installed.

**Comment by roblourens** [comment]
It's fixed in Insiders and will be fixed in the next stable release.

**Comment by jjasoncool** [comment]
Thanks a lot!

**Comment by ErnestoBorio** [comment]
Confirmed working on 1.33.0 stable
