### ISSUE TITLE
Unknown language in `contributes.*.language`. Provided value: x

### ISSUE THREAD

**Issue by blurHY** [Microsoft/vscode#68685]
- VSCode Version:1.32.0
- OS Version:win10

Steps to Reproduce:

Do nothing

![image](https://user-images.githubusercontent.com/33171396/52772667-09302300-3074-11e9-992f-325fca943ab4.png)

**Comment by kieferrm** [comment]
It's only logging that snippets have been registered for languages that are unknown to VS Code.

**Comment by blurHY** [comment]
So, is it an error?

**Comment by jrieken** [comment]
> So, is it an error?

The issue is that snippets are registered for a language that isn't known, making the snippets useless because they will not show.
