### ISSUE TITLE
Tsserver or extension host sometimes consumes much CPU

### ISSUE THREAD

**Issue by blurHY** [Microsoft/vscode#68682]
- VSCode Version: 1.31.0
- OS Version: win10

Steps to Reproduce:

I don't know.It just happens

1.32.0 has this bug too

Does this issue occur when all extensions are disabled?: DK

![image](https://user-images.githubusercontent.com/33171396/52769948-d171ad00-306c-11e9-853a-28996dff4c8d.png)

**Comment by blurHY** [comment]
It happens again
![image](https://user-images.githubusercontent.com/33171396/52770895-54940280-306f-11e9-91ff-87af3f5909ab.png)

**Comment by blurHY** [comment]
![image](https://user-images.githubusercontent.com/33171396/52771008-ae94c800-306f-11e9-8da7-7881d4e8501c.png)
I killed extension host

**Comment by blurHY** [comment]
Some extensions aren't working when it eats up my CPU.

**Comment by blurHY** [comment]
It still happens on extensionHost

**Comment by mjbvz** [comment]
Your screenshots don't seem to show unreasonable amounts of cpu or memory usage considering that you are running multiple extensions. Try disabling some of your extensions if you feel they are causing resource usage issues
