### ISSUE TITLE
it always report "Please install python and pip first" even if I already installed

### ISSUE THREAD

**Issue by shenli7** [Microsoft/vscode#68683]
Issue Type: <b>Bug</b>

In my win10 system I already installed python2.7 and pip19.0.1 in anaconda. But the alios-studio always report cannot find python and pip and report "Please install python and pip first". It cannot recognize my anaconda python system . Is there any way to setup the python path manually?

Extension version: 0.10.8
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.59GB (2.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by shenli7** [comment]
negative, this has nothing related with the #50286

**Comment by kieferrm** [comment]
Please file issue against the alios-studio extension. Thanks!
