### ISSUE TITLE
staged changes are in memory models

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6869]
- make a change in a TS files
- open diff editor
- hover over the RHS and enjoy type hover and other language features
- stage the changes
- repeat the hover etc and notice they are all gone

The attached gif shows the URI of the active editor in the console. Note how the `ts` files becomes an in-memory model

![may-25-2016 12-56-24](https://cloud.githubusercontent.com/assets/1794099/15537702/38a43494-2278-11e6-800b-1ba89f7f78c5.gif)

**Comment by joaomoreno** [comment]
This has been the behaviour since inception.

Even after staging, you can make further changes in `url.ts`. Thus, there is a need for 3 models: the HEAD version, the index version (staged) and the working tree version. The first two are in memory.

What is the real issue here?

**Comment by jrieken** [comment]
The issue is that I don't get any language service feature on the RHS after staging. No hover, no mark occurrences etc

**Comment by joaomoreno** [comment]
How do you propose to solve this?

Lowering *severity*.

**Comment by jrieken** [comment]
Then either use a file on disk or convince @dbaeumer to work with files that aren't on disk.

**Comment by joaomoreno** [comment]
@dbaeumer Thoughts?

**Comment by dbaeumer** [comment]
@joaomoreno I would if I could :-). See https://github.com/Microsoft/TypeScript/issues/4526

**Comment by joaomoreno** [comment]
Models are now extension contributed.
