### ISSUE TITLE
Microsoft Visual C++ Runtime Library Error

### ISSUE THREAD

**Issue by bfriebel** [Microsoft/vscode#68693]
Issue Type: <b>Bug</b>

VS Code installed under Windows "Program Files":
Getting Microsoft Visual C++ Runtime Library Error everytime, a file is modified or added in the workspace.
Error code: R6034
Error message: "An Applicattion has made an attempt to load the C runtime library incorrectly."

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
code-runner|for|0.9.7
plantuml|jeb|2.10.3
plantuml|jke|1.8.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
vscode-yaml|red|0.2.1
vba|spe|1.2.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@bfriebel This also happens when you have all extensions disabled and it doesn't matter which type the file you modify has?
