### ISSUE TITLE
Tree Explorer Focus vs. Current File Highlighting Confusing

### ISSUE THREAD

**Issue by karlhorky** [Microsoft/vscode#68697]
Issue Type: <b>Bug</b>

1. Open a file by double-clicking on it in the explorer tree in the sidebar
2. Click back to the same file in the side bar to enable up + down keyboard navigation around the tree
3. Navigate to a different file with the same name (good example: index.js or readme.md, for projects with lots of those)
4. Focus in to the file that is open
5. Glance at the results in the explorer tree. Which file is currently open?

Actual Results:

The highlight style of the cursor indicator is almost exactly the same to the highlight style of the currently opened file. This makes it very difficult to distinguish which file is currently open, especially with a quick glance:

<img width="656" alt="screen shot 2019-02-14 at 12 02 40" src="https://user-images.githubusercontent.com/1935696/52783645-daee1b80-3052-11e9-85df-bdd7414669d1.png">

Expected Results:

The highlight style of the cursor indicator should be very different than the highlight style of the currently opened file and possible to be distinguished from a quick glance.

Keywords for search: workbench, list, sidebar, side bar

Similar: Microsoft/vscode#67697

cc @joaomoreno @isidorn @roblourens

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_577677|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.2.2
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
wordcounter|kir|1.4.0
graphql-for-vscode|kum|1.13.0
rainbow-csv|mec|1.0.0
vsliveshare|ms-|0.3.1182
vscode-docker|Pet|0.5.2
mdx|sil|0.1.0
vscode-open-in-github|sys|1.12.0
vim|vsc|1.0.8

</details>

**Comment by karlhorky** [comment]
I would propose that a completely separate style should be developed for the "cursor" in the tree view, to make it visually distinct at a glance (don't know what the design language permits here, but potentially some kind of light arrow or something?)

**Comment by roblourens** [comment]
Agreed, tracking this in https://github.com/Microsoft/vscode/issues/67697

**Comment by karlhorky** [comment]
Oh ok, then our issues did describe the same problem/solution pair.

@roblourens Do you think you could reword your description and maybe also title in #67697 to be more clear?

I read it three times, and was still unsure whether you were proposing a change to the style to make them distinct or whether you wanted to make the two styles exactly the same.

**Comment by karlhorky** [comment]
@roblourens, as per @isidorn's latest comment in #67876 (which has been closed as fixed), it appears that the visual style is not changing, making this not a duplicate of the other issue. Can we reopen this?

cc @isidorn @misolori

**Comment by isidorn** [comment]
Sure. @misolori assigning to you as I am not passionate about this

**Comment by misolori** [comment]
We can dim `list.inactiveFocusBackground` a bit so it doesn't stand out as much:

![image](https://user-images.githubusercontent.com/35271042/53372882-dbb36700-3908-11e9-99bb-ad83929cd0d8.png)


Or we can also apply `list.activeSelectionForeground` to `list.inactiveSelectionForeground`:

![image](https://user-images.githubusercontent.com/35271042/53372920-fb4a8f80-3908-11e9-894e-0dafc16604d2.png)


@isidorn @joaomoreno @bpasero thoughts?

**Comment by bpasero** [comment]
My personal feeling is that there is not much value in showing both the selected and focused items when the tree does not have focus. I think we never did that in the past, e.g. here is a video from the old tree times:

![before](https://user-images.githubusercontent.com/900690/53393652-3a2a2500-399d-11e9-926c-b1c44cb1fd11.gif)

**Comment by isidorn** [comment]
@bpasero this makes somehwhat sense and is probably the main cause of confusion. So I +1 it.

**Comment by misolori** [comment]
What was the main reason we added both focus and selection in the inactive state?

**Comment by isidorn** [comment]
It's something the new tree added. So @joaomoreno would be the best to answer this one.

**Comment by joaomoreno** [comment]
We used to have it in the old tree. We then made it the same in the list. Then it was removed from the old tree and left in the list. The new tree is based on the list. 🤷‍♂️

**Comment by misolori** [comment]
Since we've already introduced this color token (and there are several themes that define this) do we just need to set the default to `null` in our color registry?

https://github.com/Microsoft/vscode/blob/2e173fabe821d06a60f532b90d6e5d95c0e09a9c/src/vs/platform/theme/common/colorRegistry.ts#L230

**Comment by karlhorky** [comment]
Thanks @misolori and everyone else!

**Comment by mkenney** [comment]
I realize this is closed but, my $.02, the most frustrating part is the style priority. `list.inactiveSelectionBackground` should have a lower priority than `list.inactiveFocusBackground`, that way the inactive selection background can be set to something fairly muted and when it's focused by switching files a less-muted current file highlight will make it clear what's going on.

At the moment, the reverse is true which behaves like loosing the `inactiveFocusBackground` entirely when you happen to switch to the currently selected file...
