### ISSUE TITLE
Vscode link bug in a Vue project

### ISSUE THREAD

**Issue by hfffy** [Microsoft/vscode#68692]
I want to follow a link by pressing ctrl + click in Vue project, but it failed and prompt 'Unable to open xxx:File not found'
![image](https://user-images.githubusercontent.com/45376342/52778638-6b435500-3081-11e9-976e-654e75ee9cc6.png)
![image](https://user-images.githubusercontent.com/45376342/52778653-772f1700-3081-11e9-869b-05dc99f4043f.png)

**Comment by octref** [comment]
Please open Vue related issues in https://github.com/vuejs/vetur, thanks.
