### ISSUE TITLE
Track extension es6 output migration

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#68698]
We have changed our compile to emit [ES6](
https://github.com/Microsoft/vscode/pull/68121) JavaScript, instead of ES5. That means `let` or `const` don't become `var` etc, it also means that classes are emitted as classes, not as functions. 

There are extensions that emit ES5 JavaScript *and* that extend from our API types. The code usually looks like this:

```js
var PathCompletionItem = (function (_super) {
    __extends(PathCompletionItem, _super);
    function PathCompletionItem(filename, isfile) {
        _super.call(this, filename);
        this.foo = 1;
    }
    PathCompletionItem.prototype.bar = function () {
        this.foo += 1;
    };
    return PathCompletionItem;
}(vscode.CompletionItem));
```

The challenge is that calling a `class`-constructor from a `function` extending it, isn't possible and requires a workaround. We have the [`es5ClassCompat`](https://github.com/Microsoft/vscode/blob/af2bd48a62e81a9c9970bd8e6ad889ff325e281b/src/vs/workbench/api/node/extHostTypes.ts#L18-L28)-util for that. However, there are only eight extensions that use this pattern and this issue track the migration to emitting ES6 code.

* [ ] https://github.com/vscode-contrib/vscode-versionlens/issues/132
* [x] https://github.com/pmneo/ts-importer/issues/51
* [x] https://github.com/iann0036/cloud9-sync/issues/16
* [ ] https://github.com/xiaogangya/markdown-authoring/issues/6
* [ ] https://github.com/LambdaFactory/Neptune-public/issues/25
* [ ] https://github.com/bbenoist/vscode-quicktips/issues/1
* [ ] https://marketplace.visualstudio.com/items?itemName=QuantumSheep.now-vscode (GH link broken)
* [ ] https://github.com/JeisonJHA/vscode-shortcut/issues/1
* [x] https://github.com/vshaxe/vshaxe/issues/317

Calling static functions using the `new` keyword (see https://github.com/Microsoft/vscode/issues/69533)

* [x] https://github.com/inu1255/vscode-easy-greenjs/issues/1
* [x] https://github.com/Gruntfuggly/todo-tree/issues/133
* [x] https://github.com/Gruntfuggly/vscode-journal-view/issues/11
* [x] https://github.com/mikeburgh/vscode-xml-format/issues/5

**Comment by jrieken** [comment]
Types that are being extended by classes (this includes only extension code, not code that is in node_modules programmed against vscode-API)

```
CompletionItem
Disposable
TreeItem
CodeLens
````

**Comment by iann0036** [comment]
Done. Good luck!

**Comment by Gama11** [comment]
>However, there are only eight extensions that use this pattern and this issue track the migration to emitting ES6 code.

I think your detection method might be flawed and there might actually be more extensions affected. The [Haxe extension](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe) (naturally) uses Haxe-generated JS, which uses this pattern:

```js
vshaxe.view.dependencies.Node = function(parent,label,path,type) {
	vscode.TreeItem.call(this,label);
	...
}
vshaxe.view.dependencies.Node.prototype = $extend(vscode.TreeItem.prototype,{
	...
}
```

Where Haxe defines `$extend` as:

```js
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
```

>The challenge is that calling a `class`-constructor from a `function` extending it, isn't possible and requires a workaround. We have the [`es5ClassCompat`](https://github.com/Microsoft/vscode/blob/af2bd48a62e81a9c9970bd8e6ad889ff325e281b/src/vs/workbench/api/node/extHostTypes.ts#L18-L28)-util for that.

I'm a bit confused by this - does that mean that with that workaround in place, extensions using ES5 style JS should continue to work fine (but you're looking to remove the compatibility layer soon)? That already seems to not be the case, there's [an error](https://i.imgur.com/SUn3wBQ.png) when expanding a node in the Haxe Dependencies View with current Insider's Builds (a509265116babc17648c9052eeeb8ae2909fed87).

**Comment by jrieken** [comment]
Good catch @Gama11. I obviously don't know all patterns how functions extend classes/function. I have created a tracking item for the haxe extension. 

> does that mean that with that workaround in place, extensions using ES5 style JS should continue to work fine (but you're looking to remove the compatibility layer soon)?

Yes, everything should still work (your code won't load if not) but we are keen on removing the workaround because so few extensions rely on it.
