### ISSUE TITLE
AutoTab size in 8 digits when 'ENTER' pressed to next line

### ISSUE THREAD

**Issue by C-PyLx** [Microsoft/vscode#68709]
Issue Type: <b>Bug</b>

When i pressed 'ENTER' from line: 20 to line: 21

editor will change AutoTab size to 8 digits and my line comes to 8 digits tab

How can i fix this issue and the pointer comes under the same line?
Ty so much.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.18.0-15-generic

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.46
python|ms-|2019.1.0

(4 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@C-PyLx can you attach a screen recording? Thanks!

**Comment by C-PyLx** [comment]
> /needsMoreInfo

I solved my problem from the "TabSize" part of settings.

Thanks

**Comment by C-PyLx** [comment]
I have just a problem with opening "github.com" in my chrome browser!

I tried all the ways to solve it, bu did not: my error is in (Establishing secure connection...).
Can you help me about this issue?

**Comment by kieferrm** [comment]
@C-PyLx  you last comment seems to be about some interaction in Chrome. I.e. unrelated to VS Code. Sorry, nothing I can do about it with the information you provide.
