### ISSUE TITLE
VS Code files deleted after windows update

### ISSUE THREAD

**Issue by monkeytrick** [Microsoft/vscode#68701]
- VSCode Version:  
- OS Version: 10.0.17134 

This the third time VSC has been deleted from my system after a Windows 10 update, leaving only an empty logs file in roaming. 

The returned error is "there was an error while deleting 15500674 windows update". I'd be grateful for any help, otherwise I'm switching back to Sublime.

**Comment by kieferrm** [comment]
@monkeytrick just rephrasing to make sure I understand correctly: 
1) install VS Code
2) update Windows through the normal Windows Updater
-> No VS Code

Correct?

**Comment by monkeytrick** [comment]
kieferrm,

Yes, that's right. I had to re-install VSC after the previous update and the same thing happened - nothing remaining except an empty logs folder.

**Comment by kieferrm** [comment]
@monkeytrick not sure what we can do here. But we'll have a look.

**Comment by monkeytrick** [comment]
Thanks

**Comment by joaomoreno** [comment]
Where are you installing VS Code in?
