### ISSUE TITLE
Fix documentation for matcher "loop" flag

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#68705]
- VSCode Version: 1.31.1
- OS Version: Ubuntu16.04

If I use `"loop":true`, I just get multiple problems:
Config:
```
       "pattern": [
           {
              "regexp": "^(.*):(\\d+):\\s+(Failure)",
              "file": 1,
              "line": 2,
              "message": 3
           },
           {
              "regexp": "^(\\s*.+:\\s.*)$",
              "message": 1,
              "loop": true
           }
      ]
```

Output:
```
0/61] Building CXX object CMakeFiles/ut-asl-emcs-subsystem-cms.dir/ut-EventGenerator.cpp.o 
[61/61] Linking CXX executable ut-bin/ut-asl-emcs-subsystem-cms 

[==========] Running 37 tests from 4 test cases.
../ut-EventGenerator.cpp:104: Failure
      Expected: writer.events_[ 0 ].info.size()
      Which is: 0
To be equal to: 11
[==========] 37 tests from 4 test cases ran. (26 ms total)
[  PASSED  ] 36 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EventGenerator.LooksUpAssociatedAssetData
```

Problems:
```
ut-EventGenerator.cpp
  Failure
    Expected: writer.events_[ 0 ].info.size()
  Failure
    Which is: 0
  Failure
    To be equal to: 11
```

**Comment by Gruntfuggly** [comment]
These aren't three problems - there is only one. 

The documentation says 
"To make this work, the last regular expression of a multiline pattern can specify the loop property. If set to true, it instructs the task system to apply the last pattern of a multiline matcher to the lines in the output as long as the regular expression matches."

This doesn't happen - if I manually repeat the pattern it works as expected - if I use the "loop" flag it turns the one problem into multiple problems.

**Comment by alexr00** [comment]
The documentation here is confusing. `loop` doesn't create a single problem, it creates several problems (one problem per line matches the looped regex). I'll update the documentation.
