### ISSUE TITLE
Recommend extension from extension tab

### ISSUE THREAD

**Issue by AlexAegis** [microsoft/vscode#68702]
I'd like to add extensions to the extensions.json's "recommendations" array by the context menu of an extension.

"Add to recommendations"

If it's already there change this to "Remove from recommendations"

Right now it's quite cumbersome to add a recommendation as I have to copy the extensions name from the label (or by the url if I opened it) and manually copy it. And even then I don't know If I already added that to the recommendations or not.

**Comment by kieferrm** [comment]
@ramya-rao-a  Didn't we have that already?

**Comment by ramya-rao-a** [comment]
We have a command for it. But its not exposed via the context menu

**Comment by bryceschober** [comment]
:+1: FWIW, I'm a relative newbie, but also a curious exploratory "power user" that is leading our team in adopting VS Code for more contexts, and it never occurred to me to use the command palette from this context.

**Comment by sandy081** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/10746682/98553606-13f70680-22a0-11eb-8ac9-fa46562508be.png">

**Comment by ppezaris** [comment]
will there be a command that can be invoked by the extension to do this?

**Comment by sandy081** [comment]
Yeah here are the commands

`workbench.extensions.action.addExtensionToWorkspaceRecommendations`
`workbench.extensions.action.removeExtensionFromWorkspaceRecommendations`
