### ISSUE TITLE
Focus on editor by pressing ESC

### ISSUE THREAD

**Issue by hyeonjae** [microsoft/vscode#68706]
By IntelliJ experiences, I expect to be focused on the main editor when pressing `ESC`, but vscode doesn't.

Moving any focus of viewlet to the main editor will be good user experience. :smile

**Comment by usernamehw** [comment]
```json
{
	"key": "escape",
	"command": "workbench.action.toggleSidebarVisibility",
	"when": "sidebarVisible"
},
```
