### ISSUE TITLE
Screen freezes or worse

### ISSUE THREAD

**Issue by medhickey** [Microsoft/vscode#68710]
This has occurred several times.  while in VS Code, everything freezes.  Several error logs produced and one included.

Issue Type: <b>Bug</b>

This has happened several times now, I have about 20 log files.  

# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 186736 bytes for Chunk::new
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (allocation.cpp:390), pid=1640, tid=0x00000000000078f8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode windows-amd64 compressed oops)
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#

---------------  T H R E A D  ---------------

Current thread (0x000000001a574800):  JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=30968, stack(0x000000001d100000,0x000000001d200000)]

Stack: [0x000000001d100000,0x000000001d200000]
[error occurred during error reporting (printing stack bounds), id 0xc0000005]

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

Current CompileTask:
C2:  96959  717       4       net.sourceforge.plantuml.command.regex.RegexConcat::<init> (66 bytes)

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x000000001d63a000 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=31324, stack(0x000000001da40000,0x000000001db40000)]
  0x000000001d304800 JavaThread "Service Thread" daemon [_thread_blocked, id=31032, stack(0x000000001d700000,0x000000001d800000)]
  0x000000001a5cc800 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=30996, stack(0x000000001d200000,0x000000001d300000)]
=>0x000000001a574800 JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=30968, stack(0x000000001d100000,0x000000001d200000)]
  0x000000001a56f800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=30928, stack(0x000000001d000000,0x000000001d100000)]
  0x000000001a56d800 JavaThread "Attach Listener" daemon [_thread_blocked, id=30924, stack(0x000000001cf00000,0x000000001d000000)]
  0x000000000356e000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=30920, stack(0x000000001ce00000,0x000000001cf00000)]
  0x0000000003565800 JavaThread "Finalizer" daemon [_thread_blocked, id=30872, stack(0x000000001b7d0000,0x000000001b8d0000)]
  0x0000000003560800 JavaThread "Reference Handler" daemon [_thread_blocked, id=30868, stack(0x000000001b6d0000,0x000000001b7d0000)]
  0x0000000002e7e800 JavaThread "main" [_thread_in_Java, id=12804, stack(0x0000000003370000,0x0000000003470000)]

Other Threads:
  0x000000001a538800 VMThread [stack: 0x000000001b5d0000,0x000000001b6d0000] [id=30724]
  0x000000001d306000 WatcherThread [stack: 0x000000001d800000,0x000000001d900000] [id=31056]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x0000000702800000, size: 3032 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
Narrow klass base: 0x0000000000000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x00000007c0000000

Heap:
 PSYoungGen      total 105984K, used 91716K [0x0000000780d80000, 0x0000000787c80000, 0x00000007c0000000)
  eden space 98304K, 85% used [0x0000000780d80000,0x0000000785f92e10,0x0000000786d80000)
  from space 7680K, 99% used [0x0000000787500000,0x0000000787c7e230,0x0000000787c80000)
  to   space 7680K, 0% used [0x0000000786d80000,0x0000000786d80000,0x0000000787500000)
 ParOldGen       total 130048K, used 22832K [0x0000000702800000, 0x000000070a700000, 0x0000000780d80000)
  object space 130048K, 17% used [0x0000000702800000,0x0000000703e4c360,0x000000070a700000)
 Metaspace       used 7827K, capacity 7960K, committed 8192K, reserved 1056768K
  class space    used 925K, capacity 1018K, committed 1024K, reserved 1048576K

Card table byte_map: [0x0000000012930000,0x0000000012f20000] byte_map_base: 0x000000000f11c000

Marking Bits: (ParMarkBitMap*) 0x0000000058114ce0
 Begin Bits: [0x0000000013720000, 0x0000000016680000)
 End Bits:   [0x0000000016680000, 0x00000000195e0000)

Polling page: 0x0000000001020000

CodeCache: size=245760Kb used=3300Kb max_used=3300Kb free=242459Kb
 bounds [0x0000000003570000, 0x00000000038b0000, 0x0000000012570000]
 total_blobs=1108 nmethods=731 adapters=290
 compilation: enabled

Compilation events (10 events):
Event: 81.017 Thread 0x000000001a5cc800  714       3       net.sourceforge.plantuml.project3.NaturalCommandAndAnd::create (263 bytes)
Event: 81.024 Thread 0x000000001a5cc800 nmethod 714 0x0000000003886a10 code [0x00000000038871e0, 0x000000000388cb68]
Event: 91.151 Thread 0x000000001a5cc800  715       3       java.util.ArrayList$Itr::next (66 bytes)
Event: 91.151 Thread 0x000000001a5cc800 nmethod 715 0x000000000387ec90 code [0x000000000387ee40, 0x000000000387f2e8]
Event: 91.151 Thread 0x000000001a5cc800  716       3       java.util.ArrayList$Itr::checkForComodification (23 bytes)
Event: 91.151 Thread 0x000000001a5cc800 nmethod 716 0x0000000003886590 code [0x0000000003886700, 0x0000000003886928]
Event: 91.156 Thread 0x000000001a574800  717       4       net.sourceforge.plantuml.command.regex.RegexConcat::<init> (66 bytes)
Event: 91.164 Thread 0x000000001a5cc800  718       3       net.sourceforge.plantuml.project3.ComplementDate::toRegexA (153 bytes)
Event: 91.170 Thread 0x000000001a5cc800 nmethod 718 0x0000000003891e90 code [0x0000000003892400, 0x0000000003895c68]
Event: 91.170 Thread 0x000000001a5cc800  719       3       net.sourceforge.plantuml.project3.ComplementDate::toRegexB (129 bytes)

GC Heap History (4 events):
Event: 69.587 GC heap before
{Heap before GC invocations=1 (full 0):
 PSYoungGen      total 56832K, used 49152K [0x0000000780d80000, 0x0000000784c80000, 0x00000007c0000000)
  eden space 49152K, 100% used [0x0000000780d80000,0x0000000783d80000,0x0000000783d80000)
  from space 7680K, 0% used [0x0000000784500000,0x0000000784500000,0x0000000784c80000)
  to   space 7680K, 0% used [0x0000000783d80000,0x0000000783d80000,0x0000000784500000)
 ParOldGen       total 130048K, used 0K [0x0000000702800000, 0x000000070a700000, 0x0000000780d80000)
  object space 130048K, 0% used [0x0000000702800000,0x0000000702800000,0x000000070a700000)
 Metaspace       used 7792K, capacity 7960K, committed 8192K, reserved 1056768K
  class space    used 923K, capacity 1018K, committed 1024K, reserved 1048576K
Event: 72.706 GC heap after
Heap after GC invocations=1 (full 0):
 PSYoungGen      total 56832K, used 7672K [0x0000000780d80000, 0x0000000787c80000, 0x00000007c0000000)
  eden space 49152K, 0% used [0x0000000780d80000,0x0000000780d80000,0x0000000783d80000)
  from space 7680K, 99% used [0x0000000783d80000,0x00000007844fe230,0x0000000784500000)
  to   space 7680K, 0% used [0x0000000787500000,0x0000000787500000,0x0000000787c80000)
 ParOldGen       total 130048K, used 7816K [0x0000000702800000, 0x000000070a700000, 0x0000000780d80000)
  object space 130048K, 6% used [0x0000000702800000,0x0000000702fa2360,0x000000070a700000)
 Metaspace       used 7792K, capacity 7960K, committed 8192K, reserved 1056768K
  class space    used 923K, capacity 1018K, committed 1024K, reserved 1048576K
}
Event: 86.419 GC heap before
{Heap before GC invocations=2 (full 0):
 PSYoungGen      total 56832K, used 56824K [0x0000000780d80000, 0x0000000787c80000, 0x00000007c0000000)
  eden space 49152K, 100% used [0x0000000780d80000,0x0000000783d80000,0x0000000783d80000)
  from space 7680K, 99% used [0x0000000783d80000,0x00000007844fe230,0x0000000784500000)
  to   space 7680K, 0% used [0x0000000787500000,0x0000000787500000,0x0000000787c80000)
 ParOldGen       total 130048K, used 7816K [0x0000000702800000, 0x000000070a700000, 0x0000000780d80000)
  object space 130048K, 6% used [0x0000000702800000,0x0000000702fa2360,0x000000070a700000)
 Metaspace       used 7811K, capacity 7960K, committed 8192K, reserved 1056768K
  class space    used 923K, capacity 1018K, committed 1024K, reserved 1048576K
Event: 91.140 GC heap after
Heap after GC invocations=2 (full 0):
 PSYoungGen      total 105984K, used 7672K [0x0000000780d80000, 0x0000000787c80000, 0x00000007c0000000)
  eden space 98304K, 0% used [0x0000000780d80000,0x0000000780d80000,0x0000000786d80000)
  from space 7680K, 99% used [0x0000000787500000,0x0000000787c7e230,0x0000000787c80000)
  to   space 7680K, 0% used [0x0000000786d80000,0x0000000786d80000,0x0000000787500000)
 ParOldGen       total 130048K, used 22832K [0x0000000702800000, 0x000000070a700000, 0x0000000780d80000)
  object space 130048K, 17% used [0x0000000702800000,0x0000000703e4c360,0x000000070a700000)
 Metaspace       used 7811K, capacity 7960K, committed 8192K, reserved 1056768K
  class space    used 923K, capacity 1018K, committed 1024K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 28.994 Thread 0x0000000002e7e800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000003747bf4 method=java.lang.String.startsWith(Ljava/lang/String;I)Z @ 25
Event: 28.994 Thread 0x0000000002e7e800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000003764e14 method=java.lang.String.indexOf([CII[CIII)I @ 3
Event: 34.037 Thread 0x0000000002e7e800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000000000374fc50 method=java.util.regex.Pattern.has(I)Z @ 6
Event: 43.850 Thread 0x0000000002e7e800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000000037c5648 method=java.util.regex.Pattern$Start.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z @ 44
Event: 43.852 Thread 0x0000000002e7e800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000000037c5648 method=java.util.regex.Pattern$Start.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z @ 44
Event: 43.852 Thread 0x0000000002e7e800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000000037c5648 method=java.util.regex.Pattern$Start.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z @ 44
Event: 43.852 Thread 0x0000000002e7e800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000000037c5648 method=java.util.regex.Pattern$Start.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z @ 44
Event: 43.857 Thread 0x0000000002e7e800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000037d1bb4 method=java.util.regex.Pattern.closure(Ljava/util/regex/Pattern$Node;)Ljava/util/regex/Pattern$Node; @ 182
Event: 46.269 Thread 0x0000000002e7e800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000037f0878 method=java.util.regex.Pattern.sequence(Ljava/util/regex/Pattern$Node;)Ljava/util/regex/Pattern$Node; @ 536
Event: 55.027 Thread 0x0000000002e7e800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000037fcdcc method=java.util.regex.Pattern.closure(Ljava/util/regex/Pattern$Node;)Ljava/util/regex/Pattern$Node; @ 138

Classes redefined (0 events):
No events

Internal exceptions (10 events):
Event: 1.674 Thread 0x0000000002e7e800 Exception <a 'java/security/PrivilegedActionException'> (0x0000000780fdc088) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jvm.cpp, line 1502]
Event: 1.674 Thread 0x0000000002e7e800 Exception <a 'java/security/PrivilegedActionException'> (0x0000000780fdc480) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jvm.cpp, line 1502]
Event: 1.674 Thread 0x0000000002e7e800 Exception <a 'java/security/PrivilegedActionException'> (0x0000000780fdd8b8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jvm.cpp, line 1502]
Event: 1.674 Thread 0x0000000002e7e800 Exception <a 'java/security/PrivilegedActionException'> (0x0000000780fddcb0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jvm.cpp, line 1502]
Event: 1.674 Thread 0x0000000002e7e800 Exception <a 'java/security/PrivilegedActionException'> (0x0000000780fdf108) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jvm.cpp, line 1502]
Event: 1.675 Thread 0x0000000002e7e800 Exception <a 'java/security/PrivilegedActionException'> (0x0000000780fdf500) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jvm.cpp, line 1502]
Event: 1.678 Thread 0x0000000002e7e800 Exception <a 'java/io/FileNotFoundException'> (0x0000000780fe0db0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.949 Thread 0x0000000002e7e800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000007810b1b08) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\methodHandles.cpp, line 1167]
Event: 1.969 Thread 0x0000000002e7e800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000007810bf2c8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\methodHandles.cpp, line 1167]
Event: 2.464 Thread 0x0000000002e7e800 Exception <a 'java/io/FileNotFoundException'> (0x0000000781143ea8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u201\12322\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 86.419 Executing VM operation: ParallelGCFailedAllocation
Event: 91.140 Executing VM operation: ParallelGCFailedAllocation done
Event: 91.151 loading class net/sourceforge/plantuml/project3/CommandGanttArrow
Event: 91.151 loading class net/sourceforge/plantuml/project3/CommandGanttArrow done
Event: 91.152 loading class net/sourceforge/plantuml/project3/CommandGanttArrow2
Event: 91.152 loading class net/sourceforge/plantuml/project3/CommandGanttArrow2 done
Event: 91.153 loading class net/sourceforge/plantuml/project3/CommandSeparator
Event: 91.153 loading class net/sourceforge/plantuml/project3/CommandSeparator done
Event: 91.153 loading class net/sourceforge/plantuml/project3/CommandPage
Event: 91.153 loading class net/sourceforge/plantuml/project3/CommandPage done

Dynamic libraries:
0x00007ff7272b0000 - 0x00007ff7272e7000 	C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
0x00007ffde3130000 - 0x00007ffde3311000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffde0780000 - 0x00007ffde0832000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffddff30000 - 0x00007ffde01a3000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffde1aa0000 - 0x00007ffde1b41000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffde1b50000 - 0x00007ffde1bee000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffde0840000 - 0x00007ffde089b000 	C:\WINDOWS\System32\sechost.dll
0x00007ffde1640000 - 0x00007ffde1764000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffde05c0000 - 0x00007ffde0750000 	C:\WINDOWS\System32\USER32.dll
0x00007ffde04f0000 - 0x00007ffde0510000 	C:\WINDOWS\System32\win32u.dll
0x00007ffde1860000 - 0x00007ffde1888000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffde02b0000 - 0x00007ffde0442000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffde0450000 - 0x00007ffde04ef000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffde01b0000 - 0x00007ffde02aa000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffdd1850000 - 0x00007ffdd1ab9000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.523_none_fb409dd930672a56\COMCTL32.dll
0x00007ffde0900000 - 0x00007ffde0c22000 	C:\WINDOWS\System32\combase.dll
0x00007ffddfcc0000 - 0x00007ffddfd3a000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffde0c30000 - 0x00007ffde0c5d000 	C:\WINDOWS\System32\IMM32.DLL
0x00007ffdbb940000 - 0x00007ffdbb9f1000 	C:\Program Files\McAfee\Endpoint Security\Threat Prevention\Ips\EpMPApi.dll
0x00007ffddfc10000 - 0x00007ffddfc67000 	C:\WINDOWS\System32\WINTRUST.dll
0x00007ffddf460000 - 0x00007ffddf472000 	C:\WINDOWS\System32\MSASN1.dll
0x00007ffddfd40000 - 0x00007ffddff22000 	C:\WINDOWS\System32\CRYPT32.dll
0x0000000058d20000 - 0x0000000058d2c000 	C:\Program Files\McAfee\Endpoint Security\Threat Prevention\Ips\EpMPThe.dll
0x00007ffdb7800000 - 0x00007ffdb781b000 	C:\Program Files\McAfee\Endpoint Security\Threat Prevention\Ips\HIPHandlers64.dll
0x00007ffde08a0000 - 0x00007ffde08f1000 	C:\WINDOWS\System32\SHLWAPI.dll
0x00000000581a0000 - 0x0000000058271000 	C:\Program Files\Java\jre1.8.0_201\bin\msvcr100.dll
0x00000000578f0000 - 0x0000000058194000 	C:\Program Files\Java\jre1.8.0_201\bin\server\jvm.dll
0x00007ffde13f0000 - 0x00007ffde13f8000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffdc02b0000 - 0x00007ffdc02b9000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffde1770000 - 0x00007ffde17dc000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffdd7580000 - 0x00007ffdd75a3000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffdd1ad0000 - 0x00007ffdd1ada000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffdd7550000 - 0x00007ffdd757a000 	C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffddfc70000 - 0x00007ffddfcb9000 	C:\WINDOWS\System32\cfgmgr32.dll
0x00007ffdda940000 - 0x00007ffdda94f000 	C:\Program Files\Java\jre1.8.0_201\bin\verify.dll
0x00007ffdcf630000 - 0x00007ffdcf659000 	C:\Program Files\Java\jre1.8.0_201\bin\java.dll
0x00007ffdcf610000 - 0x00007ffdcf626000 	C:\Program Files\Java\jre1.8.0_201\bin\zip.dll
0x000000001b9c0000 - 0x000000001ce00000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffde1890000 - 0x00007ffde1939000 	C:\WINDOWS\System32\shcore.dll
0x00007ffddf500000 - 0x00007ffddfc0d000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffddf440000 - 0x00007ffddf451000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffddf4e0000 - 0x00007ffddf4ff000 	C:\WINDOWS\System32\profapi.dll
0x00007ffddf490000 - 0x00007ffddf4dc000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffddf480000 - 0x00007ffddf48a000 	C:\WINDOWS\System32\FLTLIB.DLL
0x00007ffd8c9a0000 - 0x00007ffd8cb39000 	C:\Program Files\Java\jre1.8.0_201\bin\awt.dll
0x00007ffde11a0000 - 0x00007ffde1262000 	C:\WINDOWS\System32\OLEAUT32.dll
0x00007ffddcf20000 - 0x00007ffddcfab000 	C:\WINDOWS\SYSTEM32\apphelp.dll
0x00007ffddd330000 - 0x00007ffddd359000 	C:\WINDOWS\system32\DWMAPI.DLL
0x00007ffddd050000 - 0x00007ffddd0e8000 	C:\WINDOWS\system32\uxtheme.dll

VM Arguments:
jvm_args: -Duser.dir=c:\Users\ed.hickey\Documents\EdsStuff\Marketing-Digital\Digital\11163-ApptScheduling\SeqDiagrams -Djava.awt.headless=true 
java_command: C:\Users\ed.hickey\.vscode\extensions\jebbs.plantuml-2.10.3\plantuml.jar -pipeimageindex 0 -charset utf-8 -pipe -tsvg -filename CostarInteractionsSeq.wsd
java_class_path (initial): C:\Users\ed.hickey\.vscode\extensions\jebbs.plantuml-2.10.3\plantuml.jar
Launcher Type: SUN_STANDARD

Environment Variables:
CLASSPATH=C:\JDBC
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\CTC_Support\Tools;C:\Program Files (x86)\Common Files\EMC\;C:\Program Files\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\Users\ed.hickey\AppData\Local\Microsoft\WindowsApps;
USERNAME=Ed.Hickey
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 17134 (10.0.17134.1)

CPU:total 4 (initial active 4) (2 cores per cpu, 2 threads per core) family 6 model 78 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 12417996k(217944k free), swap 43556424k(34696k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.201-b09) for windows-amd64 JRE (1.8.0_201-b09), built on Dec 15 2018 18:36:39 by "java_re" with MS VC++ 10.0 (VS2010)

time: Wed Feb 13 15:31:36 2019
timezone: Eastern Standard Time
elapsed time: 97 seconds (0d 0h 1m 37s)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.84GB (6.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.2.0
plantuml|jeb|2.10.3

</details>

**Comment by kieferrm** [comment]
The log shows that the JVM runs our of memory and that the JVM is used by the `jebbs.plantuml-2.10.3` extension.  Please file the issue against the extension. Thanks!
