### ISSUE TITLE
Unsaved file: window crash when closing search results match

### ISSUE THREAD

**Issue by alnico2001** [Microsoft/vscode#68716]
Issue Type: <b>Bug</b>

Create a new file (untitled-x).
Add some text to file (do not save).
Search for a word in untitled-x (file search...ctrl+shift+f).
Search result will show match in 'Other files'...use x on this level or untitled-x level to close.
Window crashes with: 
"The window has crashed
We are sorry for the inconvenience! You can reopen the window to continue where you left off."

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|10.2.2
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|0.8.8
htmltagwrap|bra|0.0.7
bracket-pair-colorizer-2|Coe|0.0.26
divider|din|1.1.7
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
json-tools|eri|1.0.2
vscode-highlight|fab|1.3.3
vscode-todo-plus|fab|4.11.4
code-runner|for|0.9.7
vscode-mysql|for|0.3.0
vscode-sort|hen|0.2.5
beautify|Hoo|1.4.8
vscode-git-tags|how|1.3.1
ssmacro|joe|0.6.0
sftp|lix|1.9.3
gitignore|mic|1.0.1
es6-css-minify|olb|2.2.0
vscode-css-peek|pra|2.2.0
filenamecomplete|qin|0.0.3
LiveServer|rit|5.5.1
ActiveFileInStatusBar|Ros|1.0.3
preview-vscode|sea|2.0.3
org-mode|too|0.5.0

</details>

**Comment by roblourens** [comment]
I think this is the same as https://github.com/Microsoft/vscode/issues/68399 which I haven't been able to repro.

**Comment by alnico2001** [comment]
> I think this is the same as #68399 which I haven't been able to repro.

I don't think they are the same issues.
I do not get a crash when 'list gets empty' as mentioned here: #68399.

My crash occurs when new/unsaved file (untitled-x) is closed from search list (regardless of other items in list).

**Comment by roblourens** [comment]
Looking at the code, I think they are technically the same issue, but the crash may not happen all the time.
