### ISSUE TITLE
Compound launch configs broken for multi-root workspaces

### ISSUE THREAD

**Issue by markfinlabs** [Microsoft/vscode#68718]
Issue Type: <b>Bug</b>

Use .code-workspace file as below which refers to two launch configurations ("Api" and "Ws") from folder Api. The compound configuration "Api + Ws" will not show up in VS Code whereas a standard workspace-level configuration will.

```json
{
	"folders": [
		{
			"name": "Api",
			"path": ".."
		},
		{
			"name": "Processing",
			"path": "../../client/Processing"
		}
	],
	"launch": {
		"compounds": [
			{
				"name": "Api + Ws",
				"configurations": [
					"Api",
					"Ws"
				]
			}
		]
	}
}
```

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|32.00GB (11.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.2.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
ruby|reb|0.21.1
bash-debug|rog|0.3.3
vscode-proto3|zxh|0.2.2

</details>

**Comment by isidorn** [comment]
This works for me.
Let me know what you are doing differently than me
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
Is the issue still there if you restart vscode?

![screenshot 2019-02-20 at 11 37 27](https://user-images.githubusercontent.com/1926584/53085787-ee423080-3503-11e9-95e6-20dca4ee6022.png)

**Comment by markfinlabs** [comment]
Hi there,
Thanks very much for the response.
I've worked out what the issue is: I omitted the line ```"configurations": [],``` in my workspace-level config file (as shown in my initial post). Leaving this out causes the problem I saw without any error flagging that I observed. Adding this line fixes the issue.
Thanks again for your time looking at this.
Mark

**Comment by markfinlabs** [comment]
Just to be very clear, this is the config that works.

```json
{
	"folders": [
		{
			"name": "Api",
			"path": ".."
		},
		{
			"name": "Processing",
			"path": "../../client/Processing"
		}
	],
	"launch": {
		"configurations": [], // this line essential!
		"compounds": [
			{
				"name": "Api + Ws",
				"configurations": [
					"Api",
					"Ws"
				]
			}
		]
	}
}
```

**Comment by isidorn** [comment]
Ok, thanks for claryfing. This makes sense.
We decided to not show invalid compounds in the drop down (the ones that reference 0 configuraitons).

**Comment by markfinlabs** [comment]
Sure. Just to note though the issue is not an invalid compound that references 0 configurations but rather that ```configurations`` is a required field of launch even when there are no configurations being specified (since, as in my case, they may be specified at folder level). Perhaps the JSON schema  should be changed to make configurations an *optional* field of launch?

An unexpected side-effect of leaving out ```configurations``` is that valid compounds (which reference folder-level configurations) fail to be shown. Which is what caught me out.

**Comment by Emobe** [comment]
@markfinlabs spent hours trying to find this solution. worked for me, thank you
