### ISSUE TITLE
Trying to load a script file causes crash of FSI

### ISSUE THREAD

**Issue by halcwb** [Microsoft/vscode#68717]
Issue Type: <b>Bug</b>

Trying to load a script file with references ends with a crash of the fsi.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
gc-excelviewer|Gra|2.1.29
Ionide-fsharp|Ion|3.33.0
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.2
fantomas-fmt|pao|0.0.20
open-html-in-browser|pea|1.0.3
vscode-docker|Pet|0.5.2
stylelint|shi|0.48.0

</details>

**Comment by kieferrm** [comment]
Please file the issue against the F# extension. Thanks.
