### ISSUE TITLE
Add reverse command for addSelectionToNextFindMatch

### ISSUE THREAD

**Issue by Merott** [Microsoft/vscode#6872]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.4

I know WebStorm does this, but I don't know about other editors. I find it really useful to be able to undo the last selection when using `cmd+d` to select words. It's common to accidentally select one too many words, and then having to start all over.

I'd propose the name `addSelectionToNextFindMatchReverse` for clarity and to make it easily relatable.

I'll try to work on a PR myself unless somebody else wants this more than I do and does it before me 😃

**Comment by alexandrudima** [comment]
@Merott Would the existing `cursorUndo` (`cmd+u`) do the trick? (it also works in other contexts)

**Comment by Merott** [comment]
@alexandrudima It does the trick, I didn't know the command existed.

I wonder though, is there still a case for this feature? I guess with a dedicated command, you could keep pressing or hold a shortcut to undo all selections, although that doesn't seem very useful, and you could do the same with `esc` anyway. I can't think of any use cases where `cmd+u` won't do the trick - I'm trying. I think I may be concluding that this issue may be moot.

The only real benefit is probably that it will be easier to find and more appropriate as a dedicated command. The fact that there is a [question on SO without answers](http://stackoverflow.com/questions/36613291/undo-editor-action-addselectiontonextfindmatch) is an indication that this is not easy to figure out.

**Comment by yisibl** [comment]
The cursor position is not correct after the selected(used cmd+shift+z).

![demo](http://ww3.sinaimg.cn/mw1024/534b48acgw1f5es77q98gg20a409un2b.gif)

**Comment by alexandrudima** [comment]
Here they are:
* `editor.action.addSelectionToPreviousFindMatch`
* `editor.action.moveSelectionToNextFindMatch`

**Comment by yisibl** [comment]
`editor.action.addSelectionToPreviousFindMatch` https://github.com/Microsoft/vscode/pull/8677

**Comment by danseethaler** [comment]
@Merott the one drawback from the undoCursor is that the window scrolls to the first cursor when backing off a selection rather than to the latest cursor.

I published an extension to solve this exact issue and add a few other features like being able to tab through your multiple cursors, remove all multi-cursor selections except the very last one, etc.

Check it out here https://marketplace.visualstudio.com/items?itemName=danseethaler.tab-through-selections
