### ISSUE TITLE
Scrolling too fast using touchpad

### ISSUE THREAD

**Issue by kshitij-agarwal** [Microsoft/vscode#68725]
Issue Type: <b>Bug</b>

I use Lenovo IdeaPad 320 and when I scroll using touchpad in the settings then it scrolls around 5-6 pages at a time!! Please fix this.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
code-gnu-global|aus|0.2.2
python-preview|don|0.0.4
gitlens|eam|9.5.0
code-runner|for|0.9.7
py-paste-indent|hye|0.1.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-icons|rob|8.1.0
code-settings-sync|Sha|3.2.4
indenticator|Sir|0.6.0
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Also, not sure if it's related, in 1.31. we introduced fast scrolling. It's activated when you hold the <kbd>Alt</kbd> modifier while scrolling. The setting `editor.fastScrollSensitivity` defines the sensitivity. I wonder whether in your case fast scrolling kicks in by default.

**Comment by kshitij-agarwal** [comment]
It only happens in Windows10 as I also use Ubuntu 18.10 in which this problem is not there. On Ubuntu, it works fine and on both systems, it's 1.31(i.e. updated).

**Comment by alexandrudima** [comment]
@kshitij-agarwal Can you try configuring `"editor.mouseWheelScrollSensitivity"` to something like 0.1 ?

**Comment by kshitij-agarwal** [comment]
Yes @alexandrudima I did "editor.mouseWheelScrollSensitivity" to 0.009 but it only works for the editor part (the place where we write the code) and in the settings, it still scrolls 5-6 pages at a single scroll of touchpad

**Comment by roblourens** [comment]
@kshitij-agarwal do you see the same in other non-editor parts of vscode, like the file explorer or list of extensions?

**Comment by kshitij-agarwal** [comment]
Yes!! @roblourens

**Comment by roblourens** [comment]
Looks like we have a request for this: #37727
