### ISSUE TITLE
Cannot select theme

### ISSUE THREAD

**Issue by NickMele** [Microsoft/vscode#68728]
Issue Type: <b>Bug</b>

I am unable to select my color theme. When the select box appears, i cannot click on anything. it is just empty with no options.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|3.0.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.26
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
prettify-json|moh|0.0.3
atom-keybindings|ms-|3.0.6
nested-comments|phi|2.2.6
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.0.1

(1 theme extensions excluded)

</details>

**Comment by NickMele** [comment]
![image](https://user-images.githubusercontent.com/2179012/52810911-b8afca00-3061-11e9-966c-27eee55472e5.png)

**Comment by kieferrm** [comment]
Can't reproduce on my mac.

Just in case, there is also a `Color Theme` command available in the Command Palette (CMD+Shift+P).

**Comment by roblourens** [comment]
If you just installed a theme, this is https://github.com/Microsoft/vscode/issues/67462. It will go away after reloading the window or using the command to select a theme.
