### ISSUE TITLE
Precompiled header

### ISSUE THREAD

**Issue by Kittkatt88** [Microsoft/vscode#68723]
Issue Type: <b>Feature Request</b>

I can not find the precompiled header option in this version 1.31.1. I need to turn it off in order to use #include (...) in my C++ documents.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:21:36.727Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by kieferrm** [comment]
Please file this issue against the C++ extension. Thanks!
