### ISSUE TITLE
Linux: Maximize window vertically with middle click, horizontally with right click

### ISSUE THREAD

**Issue by panzi** [Microsoft/vscode#68726]
Under Linux in most (all?) window managers you can vertically maximize a window with a middle click on the maximization button in the window decoration. This is very useful when editing code and you want to display windows of different applications side by side. I'd really like to have this feature under Linux/Unix.

And for completeness: using the right mouse button on the maximize button you can horizontally maximize windows under Linux/Unix.

In both cases a second click of the same mouse button toggles the state back to a normal non-maximized window.

Thank you for your great work!

**Comment by sbatten** [comment]
closing as designed, the latest insiders and next release will ship using the native title bar as default which should bring back all the functionality of your WM.
