### ISSUE TITLE
typing cls in the terminal window doesn't work as expected

### ISSUE THREAD

**Issue by zebslc** [Microsoft/vscode#68722]
Issue Type: <b>Bug</b>

Run something that will create a reasonably large number of terminal log lines e.g. ng t for a large angular application.  
Type `cls` to clear the terminal window
run the task that created lots of entries again.  

expected: only the new entries will exist
actual: the previous entries appear again before the new log items 

There are a number of similar issues reported but the cls function is still not working.  The only current workaround is to bin the current terminal and create a new one 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (6.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
cucumberautocomplete|ale|2.13.0
featurehighlight|Blo|1.7.0
githistory|don|0.4.6
xml|Dot|2.4.0
vsc-material-theme|Equ|2.7.0
code-beautifier|mic|2.1.0
sort-typescript-imports|mic|1.4.1
vscode-azurefunctions|ms-|0.14.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
vsliveshare|ms-|0.3.1182
debugger-for-chrome|msj|4.11.2
code-settings-sync|Sha|3.2.4
ab-html-formatter|zov|0.0.2

</details>

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>K</kbd> ?

**Comment by kieferrm** [comment]
@zebslc `Terminal: Clear` from the command palette or as said above <kbd>Ctrl</kbd>+<kbd>K</kbd>.

**Comment by zebslc** [comment]
Ctrl+K doesn't work for me but Terminal:Clear does as a workaround so thanks for that.  

It still isn't the expected behaviour of `cls` which should be to act the same as `terminal:clear`

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
