### ISSUE TITLE
I can't install extensions, and downloaded and instaled VSIX are also giving me an error ((

### ISSUE THREAD

**Issue by Parker888** [Microsoft/vscode#68727]
Hi guys, so look, I has downloaded Microsoft Visual Studio, and has tryed to instal C++ extension ( i have installed already mingw and other compilers features on my system ), so I tried to install a C++ extensions from " Extensions " in Visual Studio Code, and I am are receiveng alway an error ( look to the screen )
And when I'm trying to download VSIX format from this link: https://github.com/Microsoft/vscode-cpptools/releases
I am are also receiveng an error, because the reason is that " The Identity element has an invalid value for the version attribute "
![screenshot_15](https://user-images.githubusercontent.com/47256334/52810001-3ee80280-309a-11e9-809c-7a5d0435612e.png)

Windows 10 LTSB 1607 build.
Thank you in advance for help.

**Comment by sandy081** [comment]
This is from c++ extension, please file an issue here - https://github.com/Microsoft/vscode-cpptools/issues
