### ISSUE TITLE
Allow to exclude history entries via workspace relative glob patterns

### ISSUE THREAD

**Issue by johnspurlock** [microsoft/vscode#68720]
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:16:38.656Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Steps to Reproduce:

Re-opening #6502, see the good description there.  This was never actually fixed, just closed too soon.  Having to clear edit history is not a proper fix.

**Comment by bpasero** [comment]
@johnspurlock can you give an example where this does not work?

**Comment by johnspurlock** [comment]
I mostly see this problem with files unintentionally opened by the debug view.  For example, when developing an extension, `dist/extension.js` is excluded (the entire `dist` folder is excluded), but if the debugger ever once opens that file, it will continue to appear as an option in quick open, even ahead of `extension.ts` in `src`.

That is:
1. Create an extension project, entry point source in `src/extension.ts`, webpack to `dist/extension.js`.
2. Ignore the `dist` folder using `files.exclude` and `search.exclude` in `.vscode/settings.json`.
3. Debug it.
4. Somehow open `extension.js` in the debugger, one way to force it is using the loaded scripts view.
5. Stop debugging, close everything.
6. `workbench.action.quickOpen`, type `ex..` to quick open `extension.ts`.
7. Note `extension.js` is shown (it should be excluded), presumably because it was marked as recently opened.

You have to clear edit history to fix.

Thanks!

**Comment by bpasero** [comment]
> 2\. Ignore the `dist` folder using `files.exclude` and `search.exclude` in `.vscode/settings.json`.

How do you do that?

**Comment by johnspurlock** [comment]
`${workspaceFolder}/.vscode/settings.json`

```jsonc
// Place your settings in this file to overwrite default and user settings.
{
    // excludes folders in file explorer
    "files.exclude": {
        "out": true,
        "dist": true,
        ".vscode-test": true
    },

    // excludes folders in search results
    "search.exclude": {
        "out": true, 
        "dist": true,
        ".vscode-test": true
    },
    // Turn off tsc task auto detection since we have the necessary tasks as npm scripts
    "typescript.tsc.autoDetect": "off"
}
```

**Comment by bpasero** [comment]
@johnspurlock you will have to use absolute patterns, e.g. `dist/**`

**Comment by johnspurlock** [comment]
@bpasero Unfortunately `"dist/**" : true` doesn't help, can still easily reproduce this in current stable and insiders.

![image](https://user-images.githubusercontent.com/528937/53020891-90d3b400-341d-11e9-8568-728c352186cb.png)

**Comment by bpasero** [comment]
Yeah, you need to use absolute glob patterns. I reopen this issue to reflect the support for matching against workspace relative paths.

**Comment by johnspurlock** [comment]
Tried `"**/dist/**": true` and even `"/Users/full/path/to/dist/extension.js": true` with no success.  Cleared edit history before each test, and the `dist\extension.js` file still appears in quick open after the test.

My guess is the quick open logic always contains recently opened files, regardless of these exclusion filters.
