### ISSUE TITLE
Secure storage for extensions

### ISSUE THREAD

**Issue by tetchel** [Microsoft/vscode#68738]
Looking to bump this now-closed feature request: https://github.com/Microsoft/vscode/issues/15414

We are looking for a way to securely store user access tokens on disk. In our Eclipse plugin, we will use their [Secure Storage API](https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-securestorage-start.htm).
Does a similar API exist in VS Code? Otherwise we'll have to roll our own, likely using [`node-keytar`](https://github.com/atom/node-keytar).

Thanks!

**Comment by jrieken** [comment]
> Otherwise we'll have to roll our own, likely using [`node-keytar`](https://github.com/atom/node-keytar).

Yes, that's the current recommendation

**Comment by tetchel** [comment]
Hey @jrieken 

I got around to trying keytar from within VS Code, it sounds like what I am trying to do is not supported.

https://github.com/Microsoft/vscode/issues/658
https://github.com/atom/node-keytar/issues/106

However, I also can't find any official documentation that confirms or denies extension support for native modules.

It seems it could be done by pulling down the package on activation, and building it for the user's platform. But I'm not willing to open that can of worms.

Let me know if this is possible.

**Comment by jrieken** [comment]
Yeah, no good support for native modules. There are ideas but nothing concrete yet. Using the keytar from within VS Code can be done but might stop working on day - it's not API

**Comment by queeniema** [comment]
@jrieken I know this issue has been closed, but I have a question about `keytar` specifically. In the [vscode-pull-request-github](https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/authentication/keychain.ts) extension, it doesn't look like they built their own version of `keytar` but instead pick it up from the VS Code source since the product ships with it:

```
return vscodeRequire(`${vscode.env.appRoot}/node_modules.asar/${moduleName}`);
```

Is this an acceptable way for an extension to use `keytar`? It seems to work okay for me based on a quick test.

**Comment by jrieken** [comment]
> Is this an acceptable way for an extension to use keytar? It seems to work okay for me based on a quick test.

Yeah, that the currently used workaround. It will work but there is no guarantee that it stays like that.

**Comment by wjs4572** [comment]
Is there any update to when keytar or at least a secure storage method will be added to the vscode extension API?

The solutions listed above do not appear to be working.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/684a4526059fd58f19a6d0f1ee59699e40c6084a/src/vs/vscode.d.ts#L5963
