### ISSUE TITLE
code helper takes CPU

### ISSUE THREAD

**Issue by HuguesRousseau** [Microsoft/vscode#68734]
Issue Type: <b>Bug</b>
380%

I know there are a few of those on github already, but I would like to add that it started after i updated to this latest version 1.31. Steps: open a decent size folder full of source.

I downloaded the November 2018 version and installed over the January 2019 and the problem is gone.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-amplify-vscode|aws|0.0.4
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.1
tslint|eg2|1.0.43
graphql-for-vscode|kum|1.13.0
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.2
ruby|reb|0.21.1
licenser|ymo|1.3.1

</details>

**Comment by kieferrm** [comment]
@HuguesRousseau please follow the steps in https://github.com/Microsoft/vscode/wiki/Performance-Issues. We can't help if we don't have any details. Thanks!

**Comment by HuguesRousseau** [comment]
I do not know how to reproduce other than sharing my code or project. I understand it lacks basic information for you to find what is going on. Nevertheless, I thought it would give you a hint about a regression if I told you the problem is not reproducible by going back to previous version. Of course, if it is not of any value, I will go ahead and close the issue, and reopen it with more valuable information if I can get it. Kind regards.

**Comment by HuguesRousseau** [comment]
Reopening because I found: tslint	eg2	1.0.43 removing that extension made the problem go away. Thank you.
