### ISSUE TITLE
vscode automatically updated a extension  without my permission

### ISSUE THREAD

**Issue by girng** [Microsoft/vscode#68735]
- VSCode Version:  Version: 1.31.1 (user setup)
- OS Version: Win 10, 64-bit

#### Steps to Reproduce:
1. my case is kinda specific, but FWIW: i  use  VSCode   with the [crystal-lang extension](https://github.com/crystal-lang-tools/vscode-crystal-lang). been using that extension for almost a year now with no issues. it's awesome!

2. i restarted vscode today, and it automatically updated vscode (which is always done occasionally and normal/fine), but this time.. it updated the crystal-lang extension roguely and without my permission. thus, changing the entire formatting and syntax colors of all my code. there was a reason i did not update that crystal-lang extension cause syntax colors were different 

i don't know if it's possible to revert this, but i've been using vscode for a long time and workflow has been great. now it's ruined 😿. when i literally did nothing and did not ask for an extension to be updated

with that said, i still love vscode and want to use it..  is it possible to edit a extension to use a specific version? i also don't think it should auto update extensions like that imo.  or, at least let the developer decide beforehand

**Comment by kieferrm** [comment]
@girng regarding auto-updating an extension, what is your setting for `extensions.autoUpdate` ? If you don't want auto-update it should be set to `false`.

Regarding installing another version: In the extension viewlet, choose the gear and select `Install Another Version...`:

![image](https://user-images.githubusercontent.com/4674940/52830672-99776380-3086-11e9-92e2-c6a6107441ba.png)

**Comment by girng** [comment]
@kieferrm    thank you. gonna try that.

**Comment by sandy081** [comment]
@girng Let us know if it solves your issue after trying out.

**Comment by regs01** [comment]
Also have same issue. extensions.autoUpdate is set to false, but some, though not all, installing automatically. When i launch VS Code it shows an icon on extension that updates are available. But when i switch to Extensions, number of updates is decreasing or icon just disappears with no updates available at all.
