### ISSUE TITLE
Update fails due to 'Hash mismatch' on windows

### ISSUE THREAD

**Issue by pedrogarcia** [Microsoft/vscode#68736]
Update fails due to Hash mismatch on windows

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Check for updates
2. Error message saying "hash mismatch" pops up. 

![snipaste_2019-02-14_18-22-39](https://user-images.githubusercontent.com/2473545/52815415-caa36400-3085-11e9-8e45-766b948fb227.jpg)

**Comment by pedrogarcia** [comment]
The freshly downloaded installer VSCodeUserSetup-x64-1.31.1.exe also fails.

**Comment by Tyriar** [comment]
@pedrogarcia where are you located? It could be a regional issue.

@chrmarti can you check this out?

**Comment by chrmarti** [comment]
I have flushed the CDN for the reported downloads. @pedrogarcia and @juanmcutrera Could you retry?

(TIL: Go to portal, open az764295 CDN endpoint and 'purge' either all or just the affected paths as found in our internal download links. @joaomoreno to confirm.)

**Comment by pedrogarcia** [comment]
I tried to download the installer again from Brazil and it installs without errors.

**Comment by joaomoreno** [comment]
@chrmarti I'll file an issue to the CDN.

**Comment by URF62** [comment]
the same problem exists in germany since 3 or 4 month
it happens only when you press "search for updates" in "help" menue.
installing the editor with a normal downloaded installation program works without problems
