### ISSUE TITLE
Html code formatting weird behavior

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#6873]
- VSCode Version: 1.1.1
- OS Version: current osx

Steps to Reproduce:

Original code:
<img width="618" alt="before" src="https://cloud.githubusercontent.com/assets/5489200/15540411/83175132-2287-11e6-9d12-90dd9691c2ec.png">

Then select all this code and chose "Format code":
<img width="758" alt="after" src="https://cloud.githubusercontent.com/assets/5489200/15540410/82f19140-2287-11e6-8fa9-5c12b36fb84a.png">

Not sure if this is a bug, but it seems there are problems all options values that are not indented correctly.

**Comment by aeschli** [comment]
@Brakkar Can you paste the html snippet here?

**Comment by Brakkar** [comment]
<div class="form-group">
                        <label for="exampleInputEmail1">link source language:</label>
                        <select name="linkSourceLanguage" class="form-control">
                            <option value="{javascript}" selected="selected">Javascript</option>
                            <option value="typescript">Typescript</option>
                            <option value="java">Java</option>
                            <option value="python">Python</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">link target language:</label>
                        <select name="linkTargetLanguage" class="form-control">
                            <option value="javascript" >Javascript</option>
                            <option value="{typescript}" selected="selected">Typescript</option>
                            <option value="java">Java</option>
                            <option value="python">Python</option>
                        </select>
                    </div>

**Comment by aeschli** [comment]
We use https://github.com/beautify-web/js-beautify for formatting. By default, the html formatter does not format inside [html inline elements](http://www.htmlhelp.com/reference/html40/inline.html). `select` is such a inline element.
You can change the list of unformatted element with the `html.format.unformatted` setting.
I'm also not sure why inline elements are not to be formatted. Feel free to file an issue against the formatter directly.

**Comment by bgyhnddr** [comment]
html.format.unformatted is now not working at all,why?

**Comment by aeschli** [comment]
I just tried on the latest insider and `html.format.unformatted` works for me.

Please open an new issue contain a small code snippet and the settings you use that demonstrate the problem.
