### ISSUE TITLE
Index tooltip (mouse hover) for enums

### ISSUE THREAD

**Issue by ikathegreat** [Microsoft/vscode#68740]
When editing a C# .cs file, it would be helpful to display a mouse hover tooltip over enums with the corresponding index, This would be especially helpful when there are lots of enum values or the first enum is specifically forced to not start at 0, for whatever reason.

An example:
```
public enum AlphaCode
{
  AlphaA = 1,  
  AlphaB,  
  AlphaC,  
  AlphaD,  
  AlphaE,  
  AlphaF,  
  ...
  AlphaW,  
  AlphaX,  
  AlphaY,  
  AlphaZ
}
```  
Hovering the mouse over `AlphaY` should display something like 

`AlphaCode.AlphaY = 25`

This way, I don't have to count from a known enum's index up to the one I am interested in.

This feature is comparable to the same tooltip in Visual Studio.

![image](https://user-images.githubusercontent.com/4453090/52819464-3540a980-305e-11e9-9c6d-721fe5175bb1.png)

**Comment by kieferrm** [comment]
Please file the issue against the C# extension. Thanks!
