### ISSUE TITLE
Terminal Display Crash

### ISSUE THREAD

**Issue by alejo-moreno** [microsoft/vscode#68746]
Issue Type: <b>Bug</b>

When I updated vscode to 1.31 my terminal started to crash, displaying weird colored backgrounds and distortioned fonts. I already disabled all extensions and this keeps happening. it  just crashes in the terminal area, the other editor areas work just fine.

If I kill terminal and open a new one, it takes a few commands to start crashing. Also the shapes and colors change when scrolling the terminal.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X2 560 Processor (2 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.79GB (0.63GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

<img src="https://user-images.githubusercontent.com/18426406/52822111-d2abd580-307e-11e9-9c8b-ec7e0138ebc6.png" />

![screenshot from 2019-02-14 17-50-56](https://user-images.githubusercontent.com/18426406/52822937-33d4a880-3081-11e9-946e-6243e3948902.png)

**Comment by alejo-moreno** [comment]
Switching to the 'fallback renderer' seemed to have fixed the issue. However the standard renderer still has it.

**Comment by alejo-moreno** [comment]
Switching to the 'fallback renderer' seemed to have fixed the issue. However the standard renderer still has it.

**Comment by Schnilz** [comment]
I think i have encountered the same bug.
It flickers and sometimes shows the actual terminal.
The "fallback renderer" seems to work fine all the time.

![code_error](https://user-images.githubusercontent.com/47043622/58368917-f33bc500-7ee2-11e9-959e-90c1776d7bd7.png)

version: code 1.34.0-2
OS: linux x64 5.1.4

**Comment by Tyriar** [comment]
This probably means your graphics drivers are broken. Options:

- Update drivers 🤞 
- Disable GPU in vscode by launching with `code --disable-gpu`
- Set rendererType to dom
