### ISSUE TITLE
CompletionItem - multiple text edits, onDidAcceptCommand

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6874]
We should investigate if we should allow running a command on suggest. That would allow for more advanced code actions, like 'add import', 'download typing files' etc on completion. An alternative would be the `onDidExecuteCommand` event which folks ask for. Internally accepting a completion is a command - if we broadcast that someone else could run a followup command.

**Comment by jrieken** [comment]
[`onWill|onDidExecuteCommand`](#1431)

**Comment by dbaeumer** [comment]
I like the idea of running a command since it allows for cases like downloading a typings file. But there are lot of cases as well that only need to apply multiple edits. Could we have both, providing an array of edits or an command.

**Comment by jrieken** [comment]
yes - I came to the same conclusion, esp when a command also wants to modify the current text document. Coordinating a command and a text edit would be hairy...

**Comment by dbaeumer** [comment]
Agree on the coordination command and text. That is why I would do exclusive or.

**Comment by jrieken** [comment]
@DustinCampbell fyi

**Comment by DustinCampbell** [comment]
sounds great!

**Comment by jrieken** [comment]
Also, there is a little know thing with completions and that is placeholders... It's undocumented and somewhat internal but it would be easy to make it like snippets. That is a completion can contain placeholders, tab positions, and the final cursor position. Like so:

```
foo(${value}, ${another}${_}
```

**Comment by buehler** [comment]
I really like this idea. I'm currently at the state that I'm inserting the wanted symbol at the place with the CompletionItemProvider and then let the `CodeActionProvider` add the import reference. But actually it would be very nice to use the completion item to add the import to the document.

👍 

Cheers

**Comment by jrieken** [comment]
@DustinCampbell @buehler We have a way to get into a  'snippet mode' when accepting a completion - that's multiple potentially linked cursors after selecting an item. We have them to help with subsequent edits and we plan to make them official (#3210). Snippet mode does conflict with additional edits and we will likely not allow both in one completion. Would that be a problem for you guys?

**Comment by buehler** [comment]
For now, fine by me :-)
For my actual usecase, it's cool to insert code at multiple lines (i.e. write the selected type and insert an import at the beginning of a file).

I dunno if this answers your question...

Cheers

**Comment by jrieken** [comment]
Yeah, thanks. Multiple text edits is definitely on our list, the import-scenario is what we are looking at but also want to think a little out of the box

**Comment by buehler** [comment]
Cool!
I don't get the "problem" with the snipped mode, could you elaborate the problem? It would be nice to understand your thinking.
So one can add multiple selections to edit several parts of the document at once with snippets?

**Comment by jrieken** [comment]
There is an undocumented feature which we lend from text mate snippets. Basically, you can use a special syntax in your completion and the editor will enter a snippet mode. See this sample:

```
...
new CompletionItem('bar{{foo}}bar{{foo}}{{}}')
...
```

![aug-22-2016 16-24-50](https://cloud.githubusercontent.com/assets/1794099/17858215/1f74e128-6885-11e6-9565-3a32133f28f9.gif)

The double-curly-bracket is somewhat internal but we plan to allow more of the [text mate](https://manual.macromates.com/en/snippets) snippet syntax in completions. Combining that with additional edits is somewhat tricky

**Comment by DustinCampbell** [comment]
I'm primarily looking for a way to provide C# completion on `override`, which looks like so:

**1. Before completion:**

![image](https://cloud.githubusercontent.com/assets/116161/17861476/24c12cb6-6846-11e6-9a7b-2c45faee630f.png)

**2. After completion:**

![image](https://cloud.githubusercontent.com/assets/116161/17861567/699db908-6846-11e6-8eee-9da795e1387e.png)

Implementing this properly requires the following:

1. Multi-line completions
2. Multiple edits (for the using directive at the top of the file)
3. Ability to move the caret

I'm not sure snippets will achieve the desired result.

**Comment by buehler** [comment]
Oh shiny 👍 
Thanks for the explanation.

**Comment by jrieken** [comment]
fyi @DustinCampbell

![aug-24-2016 09-55-30](https://cloud.githubusercontent.com/assets/1794099/17922794/237724a4-69e1-11e6-81ac-e30549a39617.gif)

With this  hacked-up completion item provider (note that the filter text must be set)

```js

    languages.registerCompletionItemProvider('csharp', {
        provideCompletionItems(doc, pos) {
            const range = doc.getWordRangeAtPosition(pos);
            const word = doc.getText(range);
            if (word === 'override') {

                const item = new vscode.CompletionItem('M1()', vscode.CompletionItemKind.Method);
                item.textEdit = vscode.TextEdit.replace(range, 'protected override void M1()\n{\n\tthrow new NotImplementedException();{{}}\n}')
                item.additionalTextEdits = [vscode.TextEdit.insert(new vscode.Position(0, 0), 'using System;\n')];
                item.filterText = word;

                return [item];
            }
        }
    });
```

Still on my list

* use the 'official' text mate snippet syntax, so instead of `{{}}` it should be `$0` for the final tab stop
* (stretch) make all textual changes happen in a single operation (single undo)

**Comment by nwolverson** [comment]
@jrieken I notice your current implementation has a command running after the text edit is made - I think that should enable my use case, where the additional edit (again inserting/modifying an import statement) is made via an external language service (ie provided asynchronously only after an individual completion is selected).

Am I right in that? I think it could be a common enough case.

**Comment by jrieken** [comment]
Yes and no. If you want to make additional modifications to the document I d recommend to use the `additionalTextEdit`-property. It will make you life easier wrt to subsequent edits, touching/overlaping edits, undo, keeping selections/multiple cursors stable etc. 

> is made via an external language service (ie provided asynchronously only after an individual completion is selected).

I'm obviously just guessing because I don't know anything about your language service but if you have a chance to compute those additional edits during the first request do it ;-) 

Last, you might be interested in #10561 which is about expanding a snippet when being inserted.

**Comment by nwolverson** [comment]
@jrieken Unfortunately that's not possible if all edits must be provided for all completion items up front - rather than eg as a promise on the completion item (or at least the downsides you list are more acceptable than having to do so).

**Comment by jrieken** [comment]
Running an async aftermath command isn't a show stopper. Make sure to use small edits and compare the document version before and after the long running operation.

**Comment by DustinCampbell** [comment]
Very pretty @jrieken!

**Comment by jrieken** [comment]
Closing. The remaining work is  #10561
