### ISSUE TITLE
PS Terminal Colors Missing or Transparent

### ISSUE THREAD

**Issue by jcitarello** [Microsoft/vscode#68743]
All of my terminal colors were fine until they were not and just seemed to disappear one day without any reason I can determine.  After checking every single available option in "workbench.colorCustomizations", I managed to get nearly all of them to a place where I can work again, but there is still one missing that I cannot identify.

Does anyone know how to get color back in to this section of the screen? I would greatly appreciate knowing how to fix it!

Raw text should read:
~\Projects\modules\tibcoadm.old [master +36 ~0 -0 ~]>

See image for what is displayed.

![ps_terminal](https://user-images.githubusercontent.com/6476294/52821384-44caed00-3074-11e9-902e-aa4bf837e842.jpg)

Thanks and I appreciate any assistance you could provide.

**Comment by Weasy666** [comment]
I'm on Windows 10 and it's the same for me. Since a few days (i think since the last vs code update) my colors and emojis are gone from the terminal. And i also have a lot of lines between the terminal header and the input line, see the picture:
![image](https://user-images.githubusercontent.com/11967542/53189783-8de8e700-3608-11e9-941b-7a1198ffa746.png)

**Comment by jcitarello** [comment]
Here are the two customizations I added to get *most* of them back.

Edit > Preferences > type: workbench.colorCustomizations and "Edit in settings.json"

    "workbench.colorCustomizations": {
      "terminal.ansiGreen": "#1E1E1E",
      "terminal.ansiBrightYellow": "#ffffff"

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

@Weasy666 that one is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803

**Comment by Weasy666** [comment]
@Tyriar thanks for the info
