### ISSUE TITLE
Debug hover inspector closes when dragging the horizontal scrollbar with the cursor outside the window

### ISSUE THREAD

**Issue by charlesg99** [microsoft/vscode#68749]
* VSCode Version: 1.31.1
* OS Version: Ubuntu 18.04

Continuation of #64620

When debugging, dragging the **horizontal** scrollbar of the hover inspector window outside of the popup closes the inspector.

Steps to Reproduce:

1. Start debugging
2. Hover a variable
3. drag the **horizontal** scrollbar and move the cursor outside of the variable window

**Comment by gibberishbc** [comment]
Confirmed - When dragging the new horizontal scrollbar - if the dragging mouse cursor drops outside the object inspector window longer than about 0.5 secs, the object inspector window will close - even though the mouse button is still held down.

Frankly, a larger object inspector window (or a user-selectable size changeable via Settings) would be of enormous assistance. **Is there already a separate issue request for this (i.e. for a user-selectable size for the object inspector that is changeable via Settings)?**

**Comment by alexagranov7** [comment]
This would be a nice addition!

**Comment by isidorn** [comment]
This is fixed in latest.
