### ISSUE TITLE
Terminal disapper 

### ISSUE THREAD

**Issue by bbteam17** [Microsoft/vscode#68745]
terminal disappears after a few  time
 
![unvisibleterminal](https://user-images.githubusercontent.com/32478068/52821819-44504780-30b0-11e9-9118-3ea52c6b223c.jpg)

Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by s1291** [comment]
In Windows 10,  v. 1.31.1 when I start a new integrated terminal : **Terminal** > **New Terminal**, the terminal appears as below:

![empty_terminal](https://user-images.githubusercontent.com/17838489/52901804-5513d100-3208-11e9-93da-8addc4575929.png)

I have to press `ENTER` key in order for the terminal to appear normally.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
