### ISSUE TITLE
VS Code colors change when use two monitors

### ISSUE THREAD

**Issue by ifirsov** [microsoft/vscode#68741]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch VS code
![image](https://user-images.githubusercontent.com/38044437/52820087-1a9d1d80-30bc-11e9-96e4-98a785ed9bb5.png)

2. Drag it to the second monitor
![image](https://user-images.githubusercontent.com/38044437/52820108-2a1c6680-30bc-11e9-91dc-5c5353a7bf1a.png)

Contrast changes every time i drag IDE between monitors. I have the same color profile on each monitor, the contrast changes only in VS Code.

it is appeared after 1.30.x update.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sagarthakore** [comment]
I have the same issue. The colors in vs code IDE are appearing "purpleish" on the external monitor. I am running Ubuntu 18.10. The colors look correct on the laptop monitor, but when I drag the window over to the external monitor, the blues appear purple. I can clearly make out the difference in colors. This only happens with the VS Code windows and not with other applications.

**Comment by anlupat** [comment]
I discovered that version 1.31 now supports color profiles. So you could check if the color profile is the same for both monitors. To bad the release notes did not mention this.

**Comment by sagarthakore** [comment]
Thanks @anlupat, after messing around with the color profiles, I learned that this is not VS Code specific and affects other applications too - just that it is more noticeable in VS Code (the blue logo and bottom bar really stand out when the colors shift). There is something off with the way Ubuntu is handling my external monitor. Good to know it is not an issue with VS Code (or at least for me). Thanks once again.

**Comment by IvanChanDev** [comment]
I have the same problem.

VS Code Version: 1.33.0
OS Version: Win 10 x64 10.0.17763

first monitor:
![image](https://user-images.githubusercontent.com/47861597/55678541-6175f980-592e-11e9-8bd8-bf1098e3dd65.png)

second monitor:
![image](https://user-images.githubusercontent.com/47861597/55678546-6cc92500-592e-11e9-9615-5aa7f2d349da.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
