### ISSUE TITLE
edit python code, can not jump to definition

### ISSUE THREAD

**Issue by hehaorong** [Microsoft/vscode#68753]
i just use vs code edit python code, however, this editor is not good for use.

my code just like that:
import os
import sys
import psutil

if __name__ == "__main__":
    print("hello, world.")

the mouse move to string 'psutil', and press ctrl+left, the progress bar runing but it can't jump to definition while waiting for a long time, then, i press 'run code' button to run program without any effect.

i guess vscode start 'Microsoft Windows Search' to find the label's definition, if this process running, i can't run my python program yet.
i wanna to know, how can i run my program?

**Comment by kieferrm** [comment]
@hehaorong please file the issue against the python extension [here](https://github.com/Microsoft/vscode-python/issues) Thanks!
