### ISSUE TITLE
Using PgUp in Powershell w/ integrated terminal inserts weird text

### ISSUE THREAD

**Issue by thehans** [microsoft/vscode#68750]
Issue Type: <b>Bug</b>

I found an issue with integrated terminal using Powershell: when there are many lines of output, using PgUp key a dozen or so times inserts strange lines of text into the output, with one character per line looking like this:
```
S
*
Y
*
N
*
C
*
0
0
0
0
0
0
2
d
```

If I scroll using the mousewheel or dragging the scrollbar this odd text does not get inserted.

I tried with VS Code Insiders and get the same results.

Here is a basic python script I use to make some output to scroll through:
test.py
```
from __future__ import print_function

for i in range(1, 10000):
	print(i)
```

From integrated terminal:  `c:\Python27\python.exe test.py`

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (8.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
lex-flex-yacc-bison|fau|0.0.3
cpptools|ms-|0.21.0
vscode-docker|Pet|0.5.2
cmake|twx|0.0.17

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
