### ISSUE TITLE
Activity Bar Missing

### ISSUE THREAD

**Issue by ismet94** [Microsoft/vscode#68759]
Issue Type: <b>Bug</b>

My activity bar is missing after I selected the "hide activity bar" please help. When I right click I can't seem to activate it again as there is no option for that.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.87GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
mithril-emmet|Fal|0.7.1
file-icons|fil|1.0.16
terminal|for|0.0.10
rainbow-csv|mec|1.0.0
LiveServer|rit|5.5.1
sidebar-activity-toggler|Ult|1.0.1

</details>

**Comment by vinnlee** [comment]
Just go to `View` → `Appearance` → `Show Activity Bar` to activate it again.
