### ISSUE TITLE
I am not sure this is a little problem with vscode.

### ISSUE THREAD

**Issue by itibbers** [Microsoft/vscode#68757]
- VSCode Version: 1.31.1 (1.31.1)
- OS Version: macos 10.14.3

Steps to Reproduce:

1. run `eslint --init` in Terminal tab
2. ![](https://ws2.sinaimg.cn/large/006tKfTcly1g072i4fl5oj30gn03ddgg.jpg)
the ')' should not belong to the link.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/21125
