### ISSUE TITLE
Search feature not available

### ISSUE THREAD

**Issue by slumder** [Microsoft/vscode#68756]
Issue Type: <b>Bug</b>

Search feature not available

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.66GB free)|
|Process Argv|C:\Users\KEN\AppData\Local\Temp\scp47321\pmst117_ajax.php|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.5.3
xml|Dot|2.4.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
vscode-language-pack-zh-hant|MS-|1.31.4
snippet-creator|nik|0.0.5

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@slumder Please see [search documentation](https://code.visualstudio.com/docs/editor/codebasics#_search-across-files). There's also `Find in file`, `Find References`, `Go to Definition`, `Go to Symbol in File`, and `Go to Symbol in Workspace`. Please see [our keyboard shortcuts](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf).
