### ISSUE TITLE
Intellisense Makes Suggestions When Writing Comments

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#6875]
- VSCode Version: 1.1.1
- OS Version: OSX El Capitan 10.11.4

Steps to Reproduce:

1. Working on a C# file, add /* ... */ to make a block comment or // to make an inline comment
2. Start typing a comment

Intellisense suggest hints based on what I'm typing in the comment. I don't find this helpful, in fact it's distracting and possibly a somewhat wasteful use of resources.

**Comment by jrieken** [comment]
for may we will add an option to disable word based suggestions. dupe of #5574
