### ISSUE TITLE
Cannot Go to file with Ctrl+P

### ISSUE THREAD

**Issue by yuanda26** [Microsoft/vscode#68751]
Issue Type: <b>Bug</b>

I didn't know if i have extentions that prevent or override this shortcut, but i can't use Ctrl+P to go to file I want. Little help?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.15GB free)|
|Process Argv|D:\Workspace\Sandbox|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
Handlebars|and|0.4.1
handlebars-preview|cha|1.1.0
bracket-pair-colorizer-2|Coe|0.0.26
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
handlebars-formatter|mfe|0.0.3
dotenv|mik|1.0.1
EmberES6Snippets|pha|2.3.3
polacode|pnp|0.2.2
vscode-icons|rob|8.1.0
bootstrap4-vscode|the|6.0.3

</details>

**Comment by kieferrm** [comment]
@yuanda26 

Click on the gear and select `Keyboard Shortcuts`. Check which commands are bound to <kbd>Ctrl</kbd>+<kbd>P</kbd>.

**Comment by yuanda26** [comment]
@kieferrm thanks for the help, I need to override the default shortcut, even nothing is change or overridden by the extentions, but it works now! Thanks.
