### ISSUE TITLE
Not able to sync my code in remote directory

### ISSUE THREAD

**Issue by NeonHax** [Microsoft/vscode#68758]
After I have installed the latest update, I am not able to sync my codes to a remote directory which is working fine before.
It is able to connect and I am able to see the files and folders but when I open the file, the contents are not loading. It just start to sync again but until now I am not able to view the content.

**Comment by kieferrm** [comment]
@NeonHax please provide us with steps that allow us to reproduce the problem.  What version of VS Code, what extension, how to you connect to the remote server, ... Thanks!
