### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by sean0894286** [Microsoft/vscode#68760]
Issue Type: <b>Bug</b>

1. set "files.Encoding" = "cp950" and "files.autoGuessEncoding": false
2. "ctrl + shift + f" for searching in coding area
3. search for any words
4. it will show error : "Unknown encoding :cp950"

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.9
vscode-language-pack-zh-hant|MS-|1.31.4
cpptools|ms-|0.21.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I am guessing that you were previously using the legacy search mode which supports legacy text encodings. We no longer support that setting unfortunately. I recommend upgrading to a more modern text encoding if possible.
