### ISSUE TITLE
Surprise bell ring

### ISSUE THREAD

**Issue by zichen2011** [microsoft/vscode#68762]
Issue Type: <b>Bug</b>

I use ctrl+cmd+left ctrl+cmd+right to navigate on workspace, but there is a surprise bell ring.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.92GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0
cmake-tools|vec|1.1.3

</details>

**Comment by kieferrm** [comment]
Same happens in `slack`, so this might be related to electron.
