### ISSUE TITLE
Terminal panel stops responding

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#68768]
Issue Type: <b>Bug</b>

Never seen this on OSX, but on WIndows 10, the Terminal panel stops responding randomly.

I open a Terminal panel, work a while, come back to the panel where bash is doing nothing but waiting, and -- no response, not even a blinking cursor.

At the same time, editor panels are fine.e

No idea what info to offer you over that automatically supplied.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vetur|oct|0.15.1
vscode-npm-scripts|tra|0.2.1
sort-lines|Tyr|1.8.0

(1 theme extensions excluded)

</details>

**Comment by pavelloz** [comment]
Confirm.

This is extremely annoying and makes me want to revert to previous version - hurts my productivity.

Version 1.31.1 (1.31.1) ( 1b8e8302e405050205e69b59abb3559592bb9e60 )


CPUs | Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: enabledrasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
Load (avg) | 3, 2, 2
Memory (System) | 16.00GB (2.30GB free)
Process Argv | -psn_0_1745322
Screen Reader | no
VM | 0%


Extension | Author (truncated) | Version
-- | -- | --
project-manager | ale | 10.3.2
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
bracket-pair-colorizer | Coe | 1.0.61
vscode-eslint | dba | 1.8.0
vscode-docker-syntax | dun | 0.1.5
vscode-babel-coloring | dza | 0.0.4
EditorConfig | Edi | 0.13.0
vscode-npm-script | eg2 | 0.3.5
prettier-vscode | esb | 1.8.1
vscode-open-in-finder | fab | 1.1.8
testcafe-snippets | hdo | 1.63.0
search-node-modules | jas | 1.3.0
jenkins-declarative-support | jmM | 0.1.0
graphql-for-vscode | kum | 1.13.0
vscode-wrap-console-log | mid | 1.7.1
vscode-elixir | mjm | 1.1.0
sublime-keybindings | ms- | 4.0.0
language-liquid | nei | 0.1.1
material-icon-theme | PKi | 3.6.3
ruby | reb | 0.21.1
vscode-icons | rob | 8.1.0
sass-indented | rob | 1.5.1
jenkinsfile-support | sec | 0.1.0
slim | sia | 0.1.2
vscode-fileutils | sle | 2.13.5
sonarlint-vscode | Son | 1.5.0
python | tht | 0.2.3
nodejs-extension-pack | wad | 0.1.9
JavaScriptSnippets | xab | 1.7.2
vscode-open-in-github | ziy | 1.3.6
