### ISSUE TITLE
Search bar is auto filled with previous search query

### ISSUE THREAD

**Issue by alsorokin** [Microsoft/vscode#68769]
Issue Type: <b>Bug</b>

1. Have a large workspace (VS repository will do :wink:)
2. Ctrl+Shift+F to start a search. The search text box is auto-populated with the selected text
3. Enter your own search query (not the same as auto-populated)
4. Start search
5. Switch to Explorer view, then back to search view (while the search is still running)

Expected: search box is still containing your query
Actual: search box is containing the previous, auto-populated query

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (5.29GB free)|
|Process Argv|C:\Users\User\YandexDisk\Akvelon\Xamaring|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by kieferrm** [comment]
@alsorokin how do you perform step 5? Using keyboard shortcuts?

**Comment by roblourens** [comment]
This is by design. If you have a selection when opening the search view, we put that text into the search input box. This obviously isn't perfect, as you can see in this situation, but we can't tell the difference between "I opened the search view to start a search with this selected text" and "I opened the search view to look at my results".
