### ISSUE TITLE
Add working Sets in Tree Explorer and Open/Close Project like Eclipse 

### ISSUE THREAD

**Issue by goxr3plus** [Microsoft/vscode#68770]
1) Eclipse has a very useful Eclipse which is named Working Sets . So i have many different projects which i organize in working sets so they don't get on my way  , below is a picture :) 

![eclipse_2019-02-15_12-33-23](https://user-images.githubusercontent.com/20374208/52851098-eb1efd00-311d-11e9-8b78-9fdf06f55697.png)

2)The ability to close projects like in Eclipse

As we can see in the above picture some projects are closed . In vs code when i have many projects it's a mess . Let's say i want only one project opened and all the others closed . When i open git view i don't want to see the other projects which i am not interested . So if i open them i want to be able to see them in git view .

**Comment by kieferrm** [comment]
Working sets is a feature exploration on our [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap).

**Comment by goxr3plus** [comment]
Where is the duplicate link mister robot?
