### ISSUE TITLE
Underscores not visible in integrated terminal (possible regression)

### ISSUE THREAD

**Issue by krystan** [Microsoft/vscode#68777]
- VSCode Version: 1.31.1
- OS Version: Centos 7

Steps to Reproduce:

1. Open vscode
2. Open a basic text file
3. Open integrated terminal (bash)
4, type "hello_world"
5. note that the _ is not visible

Looks like the workaround of setting zoom level to -0.001 works to make it visible again,

I do appreciate this has been reported before but is marked as closed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/35901
