### ISSUE TITLE
Compiling Rmarkdown files and tables listing in a side panel for sql server databases

### ISSUE THREAD

**Issue by leox31** [Microsoft/vscode#68775]

**Comment by roblourens** [comment]
More details needed

**Comment by leox31** [comment]
I put forward a feature request if vscode  developers will be willing to add RMarkdown for compiling R scripts to Word, HTML and PDF using the existing pandoc convert package for Markdown files.  Having Rmarkdown in vscode would be very attractive extension to the many of 200,000 + R users. For SQL server, currently there is no table listing of MSSQL schemas. This feature is currently only available in MySQL tools extension. 

Vscode is a great product and will continue to use it. 
Many thanks 



Sent from Mail for Windows 10

**Comment by roblourens** [comment]
An extension could do this.

**Comment by leox31** [comment]
It will be fantastic for vscode users to have  such extenstions.

Sent from Mail for Windows 10
