### ISSUE TITLE
cmd+click skip typescript definition and go to source?

### ISSUE THREAD

**Issue by jsumners** [Microsoft/vscode#68782]
When I cmd+click on an entity it is supposed to go to the definition of that entity. When said entity is an npm installed module it will go to the source code of that module within `node_modules` iff the module does not have TypeScript definitions. I cannot read TS definitions and would really rather just go to the source code for the entity I need to learn about. How do I make it so that TS definitions are ignored and I am always taken to the source?

**Comment by mjbvz** [comment]
See https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition for why we do this

In general, you cannot jump to the js implementation of a npm module

**Comment by jsumners** [comment]
I'm sorry. What are you expecting me to learn at that link? I don't care about the typings. I want to see the source code when I try to view the definition.

**Comment by RyanCavanaugh** [comment]
It's not that TypeScript types are blocking you from jumping to the implementation, it's that there in general is not logic to examine the code of an arbitrary node module and figure out which external invocations map to which implementations in the module.

**Comment by jsumners** [comment]
I fail to understand that. If I have:

```js
const foo = require('foo')

console.log(
  foo.bar()
)
```

I can cmd+click on `'foo'` and be taken to the source of the `foo` module. As soon as a `.ts.d` file is present that describes the `foo` module, by whatever mechanism, then cmd+clicking `'foo'` takes me to that `.ts.d` file instead of the source code. I simply want to ignore that `.ts.d` file altogether.

**Comment by lvl99** [comment]
I was just about to report this as a bug as well.

I'm unsure why we can CMD + click on code in JS files and it points us to the entity's assignment/definition within a file in the `node_modules` folder, however when coding in TS files, CMD + clicking on entities will point to the TS definition. It would be nice to have the difference between viewing the assignment and the type definition (CMD + ALT + click to view type definition?).

The extra problem that I have is when using external packages that don't have TS definitions. To get around the TS errors, I'd put in a `declare module "package-name"` into the `globals.d.ts` file. This means that CMD + clicking on any entity related to that module will point me to the `declare module "package-name"` line, and not the actual code in the `node_modules` folder. Which then means I need to manually search for the code in the `node_modules` folder, which is quite frustrating!

**Comment by jkrems** [comment]
> It's not that TypeScript types are blocking you from jumping to the implementation

As others have pointed: This is exactly what is happening though. Jumping to the implementation does work perfectly fine in vscode. Until type definition files enter the picture. Then the only thing that's possible is manually browsing the files and trying to find the implementation the old fashioned way because the type definition file intercepts any attempt to jump to definition using editor commands.
