### ISSUE TITLE
New tree eating Ctrl+Shift+Backspace

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#68786]
Issue Type: <b>Bug</b>

```json
{
	"key": "ctrl+shift+backspace",
	"command": "workbench.action.reloadWindow",
}
```

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
Verified in explorer
