### ISSUE TITLE
C and C++ syntax highlight grammar doesn't support multiline comment and asterisk

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#68784]
- VSCode Version: 1.31.1
- OS Version: linux

Steps to Reproduce:

1. Insert:
```c
bool aaaa(const char */* comment */) { return true; }
```
Result:
![image](https://user-images.githubusercontent.com/7345761/52861792-a0fd4200-3144-11e9-98f9-8462ac6f8d10.png)

No matter if you have any c/c++ extensions installed

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
We're going to try moving to a new C grammar soon. Once the move is done I'll see if this still reproduces.

**Comment by alexr00** [comment]
Looks like this one is still occuring moving to jeff-hykin/cpp-textmate-grammar.

**Comment by alexr00** [comment]
This issue was moved to jeff-hykin/cpp-textmate-grammar#11

**Comment by sean-mcmanus** [comment]
@alexr00 What's the schedule for pulling in the latest fixes into Insiders?

**Comment by alexr00** [comment]
I updated again from  jeff-hykin/cpp-textmate-grammar this week! You can see all the changes in Insiders.
