### ISSUE TITLE
local server is running if you close VSCode on 'X', server not stopping

### ISSUE THREAD

**Issue by romanshutsman** [Microsoft/vscode#68781]
- VSCode Version: 1.31.
- OS Version: WIN10 pro x64

Steps to Reproduce:

1.Run any Angular/React app via `npm start`
2.Close VSCode on "X" (without stopping server)
3.Open browser and go to localhost  with specific port that server opened
VSCode dont kill procces of localhost, unless you will not stop server manualy

**Comment by kieferrm** [comment]
@romanshutsman how do you perform step 1? Through the integrated terminal?

**Comment by romanshutsman** [comment]
yes, through the integrated terminal
1)open anyway Angular/React app in VSCode, and in integrated terminal run `npm start` ![image](https://user-images.githubusercontent.com/29098174/52935584-7688d000-3362-11e9-965c-39fe17b9568f.png)
2) then app is running 
![image](https://user-images.githubusercontent.com/29098174/52935733-e4cd9280-3362-11e9-8e61-53740f3eb446.png) 
and is opened in browser:
![image](https://user-images.githubusercontent.com/29098174/52935788-0890d880-3363-11e9-8398-53d8110471cb.png)
3)then you should close VSCode without stopping opened server
![image](https://user-images.githubusercontent.com/29098174/52935941-7806c800-3363-11e9-8e8c-ce8ea1bfc836.png)
4) then when VSCode is closed, go to browser and refresh page and app is running 
![image](https://user-images.githubusercontent.com/29098174/52936034-b43a2880-3363-11e9-9dbc-187951248db5.png)

**Comment by romanshutsman** [comment]
@kieferrm

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
