### ISSUE TITLE
[Feature Request] Allow use of PATs for Azure DevOps Server

### ISSUE THREAD

**Issue by jordan-clark** [Microsoft/vscode#68788]
We are operating in a smart card only (client certificate authentication) environment, and it would be fantastic to enable PATs for on prem ADS, vs forcing NTLM authentication. I have tested PATs utilizing the ADS API against my server, and it works great.

As it stands now, we are unable to utilize this extension because of the NTLM only authentication requirement.

**Comment by kieferrm** [comment]
> this extension

Can you please file the issue against the extension? Thanks!
