### ISSUE TITLE
VS Code freezes on any minified js file opening 

### ISSUE THREAD

**Issue by oodboo** [Microsoft/vscode#6878]
- VSCode Version: 1.1.1-insider
- OS Version: Windows 10

If you try opening any javascript that is minified it will brick VS Code. At first I thought it is due to size but now I am getting the same thing with files small as 10K.

Steps to reporduce:
npm init
npm install dragula --save

Go to node_modules folder and find folder dragula and try opening dragula.min.js.

**Comment by ChazyTheBest** [comment]
Do you have `"editor.wrappingColumn": -1`?

I do also get freezes because of this. And I think there's a global wrapping limit, because I can see javascripts like Jquery cutted at the end of the row with three dots.

**Comment by oodboo** [comment]
In my case setting is :
```
"editor.wrappingColumn": 300,
```

**Comment by ChazyTheBest** [comment]
That's the default setting. My VS Code doesn't brick nor freeze with that setting, only if I set it to -1 and start moving horizontally. Also I have multiple minified plugins in the same file.

If you've upgraded recently try cleaning the old config and start fresh (save your config in your project folder) and see what happens.

**Comment by oodboo** [comment]
Install is already clean ...

**Comment by ChazyTheBest** [comment]
Oh sorry, you're in Windows, in Linux you have the config in a different folder.

**Comment by alexandrudima** [comment]
This is caused by us writing the text on the current line to the `<textarea>` we use for input and because we mirror the selection in the editor as a selection in the `<textarea>`. We do so in order to support screen readers, and this is the only way to support screen readers in an editable body of text in Chromium/Electron.

**Comment by alexandrudima** [comment]
I have filed electron/electron#5709 to ask if it's feasible to get on the JS side of things an event so we can do this only when really needed.

**Comment by oodboo** [comment]
@alexandrudima If anything can you just ignore `*.min.js` file and read them as plain text ? Without any formatting/parsing etc.

**Comment by alexandrudima** [comment]
@oodboo If you add the following setting `"editor.experimentalScreenReader": false` are things faster?

**Comment by oodboo** [comment]
@alexandrudima Thank you that works, does not brick the Studio and also it will do formatting till some point and then everything will be mostly green. But, I am fine with that, as I would have been fine with the plain text display as well. Thank you.
Are we closing this or you will still leave it as bug?

**Comment by alexandrudima** [comment]
That flags controls the behaviour of how we synchronize the editor text with the native `<textarea>`. It has no impact feature-wise unless you use a screen reader (except ofcourse the time it takes and stalls the UI).

So you can use it for now as a workaround, but I need to make sure our synchronization is not causing stalls in all cases. I'm looking into limiting the amount of text we write to `<textarea>`

**Comment by alexandrudima** [comment]
To verify: please also check that using NVDA on the editor text still works.

**Comment by oodboo** [comment]
@alexandrudima I do not have Non Visual Desktop Access “screen reader” why should I install that!? :confused:

**Comment by alexandrudima** [comment]
@oodboo Someone from our team will verify this fix, no need for you to do anything.

**Comment by oodboo** [comment]
@alexandrudima ah, sorry I had not realized that you've left a team note ... thanks again...
