### ISSUE TITLE
non trova flle quando si lavora con django

### ISSUE THREAD

**Issue by pipolo23** [Microsoft/vscode#68796]
I dati necessari sono stati scritti negli appunti perché erano eccessivi per l'invio. Incollarli.

Issue Type: <b>Bug</b>

from app_conta.views import contatti, homepage
urlpatterns = [
    path('admin/', admin.site.urls),
]
the problem is:
{
	"resource": "/c:/Users/F/Desktop/Django_Atom/contatto/pro_contatti/pro_contatti/urls.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "unresolved-import",
	"severity": 4,
	"message": "unresolved import 'app_conta.views'",
	"source": "Python",
	"startLineNumber": 19,
	"startColumn": 6,
	"endLineNumber": 19,
	"endColumn": 21
}
while I was creating a file urls.py did not find the file views that is inside the app_conta I tried the same passage with Atom and did not give me problems, already used Visual Code to finish other projects but never gave me problems, this problem has now come out with a new project started by Visual Code

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.89GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-it|MS-|1.31.4
python|ms-|2019.1.0
vscodeintellicode|Vis|1.1.3

</details>

**Comment by kieferrm** [comment]
@pipolo23 please file the issue against the Python extension. Thanks!

**Comment by pipolo23** [comment]
Thanks very much

Il giorno ven 15 feb 2019 alle ore 20:10 vscodebot[bot] <
notifications@github.com> ha scritto:
