### ISSUE TITLE
"Search in Files" doesn't search across all files

### ISSUE THREAD

**Issue by cppcraze** [Microsoft/vscode#68797]
Issue Type: <b>Bug</b>

Opened a folder and search a term, it only shows partial results. After I opened the file which doesn't show in result, and search the same term again, this file is now shown in search result page.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (8.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|2.0.2
jsonnet|hep|0.1.0
azure-functions-tools|joh|0.3.3
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.13.1
vscode-azurestorage|ms-|0.6.0
vscode-azureterraform|ms-|0.2.2
vscode-cosmosdb|ms-|0.10.0
vscode-kubernetes-tools|ms-|0.1.16
mssql|ms-|1.4.0
python|ms-|2019.1.0
vscode-ai|ms-|0.4.2
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
PowerShell|ms-|1.11.0
vscode-azureextensionpack|ms-|0.0.9
team|ms-|1.144.1
azurerm-vscode-tools|msa|0.4.2
azure-hdinsight|msh|1.1.1
vscode-docker|Pet|0.5.2
vscode-yaml|red|0.2.1
usql-vscode-ext|usq|0.2.14
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.9.0
azure-iot-toolkit|vsc|2.2.0
t4-support|zbe|0.4.2

</details>

**Comment by rmariuzzo** [comment]
Just happened to me.

**Comment by roblourens** [comment]
Please see this page on troubleshooting search issues, and let me know if you still have issues: https://github.com/Microsoft/vscode/wiki/Search-Issues

**Comment by cppcraze** [comment]
Thanks Rob. It is due to the expected file is part of gitignore. I feel it is better to disable using gitignore as default setting. Users will only think the button in the lower right corner is related to Exclude settings since it is next to "Exclude" textbox. This UI design is not user friendly. As long as "using ignore" is more visible, user will know give it a try.

![image](https://user-images.githubusercontent.com/5673860/52919259-49caaf00-32b5-11e9-8a7e-dc78c1635256.png)

**Comment by roblourens** [comment]
I know it confuses some people but I've found that more expect it to be the default than not.
