### ISSUE TITLE
tmux terminal resizes randomly

### ISSUE THREAD

**Issue by Mellbourn** [microsoft/vscode#68792]
- VSCode Version: 1.31
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. have tmux running in the integrated terminal, looking good
2. launch debugging with the setting `"console": "integratedTerminal",`
3. Now the tmux terminal seems to be temporarily resized, so that it displays as if the terminal had a much smaller size. This leaves the display screwed up. See image below. 

![tmux displays weirdly since it has had the wrong size](https://user-images.githubusercontent.com/1785727/52874301-74035c00-3151-11e9-8716-0078cdcf3779.png)

If I issue the tmux `refresh-client` command (ctrl-b r) tmux resizes and displays correctly again.

This was not an issue before 1.30. The behaviour is not consistent, sometimes tmux renders fine, sometimes it does not. I think the problem has happened on other occasions than debugging.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Could you see if this reproduces in the Insiders build? https://code.visualstudio.com/insiders

**Comment by Mellbourn** [comment]
The problem is a lot less pronounced in insiders. It still manifests sometimes, but much less than in stable.

**Comment by Tyriar** [comment]
Might be related to reflow

**Comment by Tyriar** [comment]
It might be a good idea not to use tmux as a debug shell? There's a new setting "automationShell" which lets you use a more stripped down one for debug and tasks.

**Comment by Mellbourn** [comment]
I like it a lot having debug in one of my tmux panes. It lets me do things in other panes while I see the result of test debugging in the separate pane.
