### ISSUE TITLE
Clicking anywhere on the "debug console" pane should "focus" on the entry point for the console

### ISSUE THREAD

**Issue by benlesh** [microsoft/vscode#68793]
Nearly every day I click somewhere in the middle of the debug console thinking it's going to put the focus on the entry field at the bottom. And then I start typing. And nothing! :rofl: 

Can we please implement this? It would be a productivity win. At least for me.

Prior art:

- Chrome console
- Terminal (or at least every terminal I use)

:pray: Thanks for the awesome tools!

**EDIT: for clarification**

I understand that "focus" is a bit of a misnomer. The real behavior I want is just to mimic what I have in the developer console in Chrome et al. The idea being, that if I'm engaged and interacting with that debug console panel (having clicked on something or focused on it in some way), and then I start typing, it should type in the console entry field at the bottom. (and ideally show a blinking cursor or something). Basically a "terminal-esque" behavior.

**Comment by isidorn** [comment]
Thanks for feedback.
However we do want to have the navigation and filtering option in the debug console.
E.g turn on "workbench.list.keyboardNavigation": "filter"
Click on the debug console and start typing -> it should filter out content

Note that this experience is still not fully polished, however since we do want to polish it we can not go back to the old click on content -> forward focus to input.
Though leaving this open to gather more feedback

**Comment by bersbersbers** [comment]
Some random user input, in case anyone is interested: I am highly in favor of being able to click (mostly) anywhere in the debug console to focus the input text area. Any terminal is indeed a good comparison.

Quantitatively, I have fallen for typed text gone missing in the debug console for this very reason dozens, if not hundreds of times. I found this such a basic requirement that I didn't even consider filing a bug for it - I was just waiting for it for a couple of releases to appear, it just had to. (Only it didn't.)

By contrast, I am not even aware of "filtering" capabilities of the debug console.

**Comment by isidorn** [comment]
We have gone back to the old behavior of clicking anywhere focusing the debug console input.
To focus the tree we have introduced a new command (ctrl/cmd + F)

Note to self: mention this in release notes.
