### ISSUE TITLE
iferr snippet in go creates problems 

### ISSUE THREAD

**Issue by pathcl** [Microsoft/vscode#68795]
- VSCode Version: Version 1.31.1 (1.31.1)
- OS Version: 10.12.6 (16G1815)

Steps to Reproduce:

1. type iferr to use go snippet for if/err 
2.
![screen shot 2019-02-15 at 20 01 50](https://user-images.githubusercontent.com/3768896/52878296-8cc53f00-315c-11e9-9346-8e23f93b1c9f.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
Please file the issue against the go extension. Thanks!
