### ISSUE TITLE
change name file , not change in code!!

### ISSUE THREAD

**Issue by mojtabakheyri1997** [Microsoft/vscode#68803]
- VSCode Version: 1.31.1
- OS Version: ubuntu18.04

Steps to Reproduce:

1. For example copy file "style.css" in project
2. Use this file in my code For example "<\link rel="stylesheet" href="style.css"\>"
3. I rename file for example to "myStyle.css" in file explorer

when step 3 done , I expected that every part of the project I used to use the name of this file would automatically change its name.
It's mean that for example if I use this code in my Html file : 
`<\html\>
<\head\>
<\link rel="stylesheet" href="**style.css**"\>
<\/head\>
<\body><\/body\>
<\/html\>`
when I rename the file to "style2.css" , should my coed change to (automatically) : 
`<\html\>
<\head\>
<\link rel="stylesheet" href="**style2.css**"\>
<\/head\>
<\body><\/body\>
<\/html\>`
But it doesn't .
If I use for example 20 times this code in my project , if name file change , I should change my project code Manually !!!! but it dose't good ;(
Please Help ME :+1: 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mojtabakheyri1997** [comment]
### **No one really wants to help me ?**

**Comment by octref** [comment]
> that every part of the project I used to use the name of this file would automatically change its name

There is no such feature, sorry.
