### ISSUE TITLE
Find in Files - files to exclude is case sensitive

### ISSUE THREAD

**Issue by patrick-bsgindustries-com** [Microsoft/vscode#68802]
Issue Type: <b>Bug</b>

I have some files with the extension "reportType", so I added "&ast;.reporttype" (lower case "t") to the files to exclude text box in the Find in Files search dialog.  When I did so, it didn't filter out those files, but when I changed it to "&ast;.reportType" (upper case "T"), it filtered them out.  FYI, in the search dialog, I had not chosen my search to be case sensitive.

My expectation is that the search would be case sensitive/non-case sensitive based on the options I specify in the search but the file filter text boxes would always be non-case sensitive.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.08GB free)|
|Process Argv|C:\src\Repos\Amazon HVH\Environments\TeamBDev|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
tslint|eg2|1.0.43
vscode-great-icons|emm|2.1.46
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1182
vscode-docker|Pet|0.5.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.3.0
vscode-manifest-yaml|Piv|1.3.0
vscode-spring-boot|Piv|1.3.0
java|red|0.38.0
vscode-xml|red|0.3.0
salesforcedx-vscode|sal|45.2.0
salesforcedx-vscode-apex|sal|45.2.0
salesforcedx-vscode-apex-debugger|sal|45.2.0
salesforcedx-vscode-apex-replay-debugger|sal|45.2.0
salesforcedx-vscode-core|sal|45.2.0
salesforcedx-vscode-lightning|sal|45.2.0
salesforcedx-vscode-lwc|sal|45.2.0
salesforcedx-vscode-visualforce|sal|45.2.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.2
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.4

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/10633

**Comment by dmitrivMS** [comment]
This is done.
