### ISSUE TITLE
Search progress animation issue

### ISSUE THREAD

**Issue by nidheesh-cl** [Microsoft/vscode#68809]
Issue Type: <b>Bug</b>

Search progress animation always shows even after the search is completed. This goes away only when the VS code is closed and reopened.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz (8 x 2526)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 9, 7|
|Memory (System)|31.31GB (0.89GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
vscode-eslint|dba|1.8.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
flow-for-vscode|flo|1.0.1
vscode-flow-ide|gca|1.2.0
flow-language-mode|goz|0.0.2
beautify|Hoo|1.4.8
ReactFlowSnippets|lsa|0.2.17
MagicPython|mag|1.1.0
python|ms-|2019.1.0
vsliveshare|ms-|0.3.1182
python|tht|0.2.3
vscodeintellicode|Vis|1.1.3
gitblame|wad|2.6.3
jinja|who|0.0.8

</details>

**Comment by roblourens** [comment]
It sounds like the search is not actually completing. If you open the process explorer (Help > Process Explorer), do you see the searchService process or an `rg` process using lots of CPU?

Or, if you open the developer tools (also under Help) do you see any errors in the console?
