### ISSUE TITLE
bootstrap-fork.js sourcemap should not have the "sources" property

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#68805]
- Debug an extension
- Step into a `console.log` line
- End up on a nonexistent line of the minified bootstrap-fork.js file

We are trying to debug the mapped lines of the minified file. The reason is that the sourcemap has `"sources": ["bootstrap-fork.js"]` so it points back at itself. It does have the source content inlined. So if it doesn’t have that property set then we would show the real source.

I assume we just throw all these js files into a minifier at some point. I think that whatever generates the sourcemaps is probably doing the right thing based on the info it has. Is it possible to post-process the sourcemaps that come out to patch this? I'm happy to investigate if someone can tell me where this happens.

cc @kieferrm

**Comment by joaomoreno** [comment]
The file goes through the build over here: https://github.com/Microsoft/vscode/blob/a3dc4be0e016ac65a7549f45af0ee85d547e01cf/build/gulpfile.vscode.js#L61

> I'm happy to investigate if someone can tell me where this happens.

:clap: !

**Comment by roblourens** [comment]
Thanks! I have a fix, not sure how far to go with it. I could apply this to all .js files that get minified. But it looks like bootstrap-fork.js is the only file that normal users might step into besides loader.js. loader.js is technically wrong too but its relative path gets screwed up another way and ends up called `vs/vs/vs/loader.js` so it works.

For now I'll just rename bootstrap-fork.js. It will look like this:
![image](https://user-images.githubusercontent.com/323878/53060137-3d3d8680-346e-11e9-87f5-2abeb666b8be.png)
