### ISSUE TITLE
Catch clause identifier cannot be watched in async function

### ISSUE THREAD

**Issue by kkeri** [Microsoft/vscode#68801]
Issue Type: <b>Bug</b>

__Steps to reproduce__:

1. Copy the following code into test.ts.
~~~js
async function catches (f) {
  try {
    await f()
  }
  catch (e) {
    console.error(e)
  }
}
catches(() => { throw new Error() })
~~~

2. Transpile the code for ES5 target. (I used Typescript version 3.3.3)
3. Set breakpoint on the `console.error(e)` line.
4. Launch program, let the debugger pause at the breakpoint.

__Expected behavior__: if I move the cursor over the identifier `e`, or add a new watch, I see the value of `e`.

__Actual behavior__: I can't see the value of `e`. If I try to add a watch, I get `e: not available`.

_Notes:_

- If I remove `await` from the code, the issue doesn't occur. 
- If I add watch for the identifier `e_1` instead `e`, it works. The obvious reason is being the compiler has changed the variable name. See the relevant part of the transpiled file:
~~~js
function catches(f) {
    return __awaiter(this, void 0, void 0, function () {
        var e_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    _a.trys.push([0, 2, , 3]);
                    return [4 /*yield*/, f()];
                case 1:
                    _a.sent();
                    return [3 /*break*/, 3];
                case 2:
                    e_1 = _a.sent();
                    console.error(e_1);
                    return [3 /*break*/, 3];
                case 3: return [2 /*return*/];
            }
        });
    });
}
~~~

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4100 Quad-Core Processor             (4 x 3607)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (2.44GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/12066
