### ISSUE TITLE
Behavior between Find in Selection in Find Widget and Alt + L is not consistent

### ISSUE THREAD

**Issue by irrationalRock** [microsoft/vscode#68800]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select a line of text and click on the `Find in Selection` in the Find Widget.
2. Click on the `Find in Selection` again. It doesn't remove the `Find in Selection` search scope.

Try steps again with `Alt + l`.

When you use `Alt + l` on step 2 it removes the `Find in Selection`.

It would help if the button mirrored how `Alt + l` works.

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
I can't reproduce this issue anymore.
