### ISSUE TITLE
Go to/Peek definition in WSL based project

### ISSUE THREAD

**Issue by danilaml** [Microsoft/vscode#68815]
- VSCode Version: 1.31.1
- OS Version: Win 10 x64 1803

Steps to Reproduce:

1.  Open some WSL-based project, i.e. the project that is built using WSL. In my case, this was an OCaml project.
2. Try to peek/go to definition of some standard symbol (i.e. from installation inside WSL).
3. VS Code tries to open WSL-based path (like `(file:///usr/lib/ocaml/pervasives.ml)`) and fails.

Does this issue occur when all extensions are disabled?: This depends on language extensions.

In theory, a smart extension could try to translate the paths but I'm not sure if it's the right solution or if it's easy to implement. It'd be much nicer if VS Code could try to translate those paths into the ones that could be opened from windows (maybe behind an option).

**Comment by kieferrm** [comment]
Related to https://github.com/Microsoft/vscode/issues/63155.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
