### ISSUE TITLE
Complete freeze on macOS

### ISSUE THREAD

**Issue by philipmat** [microsoft/vscode#68813]
- VSCode Version: 1.31.1,  1.32.0-insider,  1.31.0-exploration
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Try to load any window that renders HTML (HTML view), for example clicking on an extension to bring up its description.
2. The beachball of death starts spinning and Code becomes completely unresponsive, including Dev Tools window, and Process Explorer; even the trace log stops.
3. The only way to stop it is by force quitting.

Does this issue occur when all extensions are disabled?: Yes.

Couple of notes:

- **Does not occur when started with `sudo`.**
- Does not produce an entry in the Console under User Reports

Gist with log file and macOS crash report at: https://gist.github.com/philipmat/46902e4f559ba2ce49c96764f223f77f

Ran with `code --no-extensions --verbose --log trace`

---

I don't think this is VSCode's fault as much as something installed on this corporate laptop, likely a tool like McAfee Endpoint Security for Mac or similar.

I'm hoping that by looking at log and the error report someone would be able to point me in the direction of further troubleshooting or identify some issues that cause this freeze.

**Comment by jrieken** [comment]
@philipmat So with which of the two versions you have mentioned does this happen?

**Comment by philipmat** [comment]
Sorry the formatting was a bit weird in the original report. 

It happens with all 3 versions: 1.31.1 (normal release), 1.32.0-insider, and a 1.31-exploration (I think this was the Electron 4 build?)

**Comment by jrieken** [comment]
> 1. Try to load any window that contains HTML inside,

And that means html source code, right?

**Comment by philipmat** [comment]
It's not when loading HTML source code, but when trying to render it.

Here's a screenshot of it freezing (not included: beachball cursor):
![Screenshot of VS Code freezing](https://user-images.githubusercontent.com/709928/52888473-61812680-3141-11e9-863a-0ed62a5532ea.png)

**Comment by jrieken** [comment]
Ah, showing web views... Forwarding to @mjbvz

**Comment by mjbvz** [comment]
@philipmat Does this also happen for the markdown preview? It also uses a webview

**Comment by philipmat** [comment]
Good test and yes, it does and it seems to happen even on a new window with no markdown in the document.

1. File -> New file
2. change file type to Markdown
3. Click the split preview button or Cmd-Shift-P -> Open preview (either to the side or in full windows).
4. => Beachball

**Comment by mjbvz** [comment]
Closing this as I've never been able to repo this issue and given that there have been no thumbs up on this issue, it seems few users are impacted by ut
