### ISSUE TITLE
TypeScript task detection is not cross-platform

### ISSUE THREAD

**Issue by TimMensch** [microsoft/vscode#68812]
Issue Type: <b>Bug</b>

If your `tsconfig.json` is in a subfolder, the folder path has to match the system file separator (\\ on Windows, / on Mac/Linux) in order for it to work.

Steps to Reproduce:

1. Create a project with a folder in it.
2. Put tsconfig.json in the subfolder along with a test TypeScript file.
3. Create a build task for that tsconfig.json. On Windows it will get a backslash, on Mac/Linux a forward slash.
4. Switch the slash to that of the opposite platform.
5. Note that now you can't build that task, and that instead you get an error similar to the following:

```
Error: The typescript task detection didn't contribute a task for the following configuration:
{
    "label": "tsc-api",
    "type": "typescript",
    "tsconfig": "api/tsconfig.json",
    "option": "watch",
    "options": {
        "cwd": "${workspaceFolder}/api"
    },
    "promptOnClose": true,
    "problemMatcher": [
        "$tsc-watch"
    ],
    "group": "build"
}
The task will be ignored.
```

The only workaround I've found is to create TWO tasks for each desired task, where one has forward slashes and the other backslashes. But a recent VS Code update made a warning box appear for those configurations _every time I build or debug_, which is annoying. Please address the underlying issue.

Honestly, this would be _yet another situation_ where simply using forward slashes _all the time_ would fix everything. This would also fix, for instance:

https://github.com/Microsoft/vscode/issues/35593

...a bug that's been around for a year and a half now. :(

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (2.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexr00** [comment]
I think we should be able to normalize the paths for `"tsconfig"` and `"cwd"`. It won't solve everything, but it will help.

**Comment by gmertk** [comment]
Hey @alexr00,
Are you working on this? If not, can I give it a shot?

**Comment by alexr00** [comment]
@gmertk, I'm not working on it right now, please do give it a shot! Starting info is in the comment [above](https://github.com/Microsoft/vscode/issues/68812#issuecomment-464655513).

**Comment by alpalla** [comment]
@gmertk are you still working on this? If not I'd like to help out.

**Comment by NizamLZ** [comment]
I was looking at this issue, I like the idea of [https://code.visualstudio.com/docs/editor/tasks#_custom-tasks](url), where there is a section for windows specific command. Typescript task template can be updated to support something like this: 
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "windows": {
                "tsconfig": "subfolder\\tsconfig.json"
            },
            "tsconfig": "subfolder/tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ]
        }
    ]
}
```

I had a hard time finding the typescript template definition! Any help in the right direction would be appreciated.

**Comment by TimMensch** [comment]
That seems like solving the wrong problem.

Changing the pattern match from `/` to `[/\\]` would solve this without the above hack/additional work for Windows support/DRY violation (because the paths _should_ be identical between platforms, and it's only a bug that VS Code uses `\` to begin with that's causing the problem).

**Comment by alpalla** [comment]
@NizamLZ I haven't started implementing a fix yet, I just wanted to check whether anyone was already working on it first. I'll leave you to it at this point but please let others know if you are working on an issue as was suggested to you already [here](https://github.com/Microsoft/vscode/issues/72601#issuecomment-486211162).

**Comment by NizamLZ** [comment]
@alpalla Wanted to mention that I am working on it once I had a clear solution. Thanks for leaving this issue to me. I am glad to work on it till it's resolved.

**Comment by TimMensch** [comment]
@NizamLZ It's great if you'll work on the problem, but _please_ don't solve it by making unnecessary work for Windows cross-platform support.

**Comment by NizamLZ** [comment]
@TimMensch Ofcourse I won't. I will look into the suggestion you posted above.
