### ISSUE TITLE
When opening a file and no workspace is open, ask if user wants to open directory as workspace

### ISSUE THREAD

**Issue by gramster** [microsoft/vscode#68819]
I searched for workspace and file and got over 4k matches. Ouch, sorry guys. 

I think this might help with getting started experience. If someone has no file or workspace open, and they open a file instead of a workspace, it might be worth asking if they want to open the file's directory as a workspace.

**Comment by roblourens** [comment]
Not sure I agree. Opening a file or multiple files without opening a folder is a valid and common scenario and I don't think that a noisy notification is solving a problem.
