### ISSUE TITLE
Language mode should default to project language for new unsaved files

### ISSUE THREAD

**Issue by thisismydesign** [microsoft/vscode#68814]
I find myself often creating unsaved files as a temporary playground. It would be very useful if these files could assume the language mode "of the project" (i.e. language most of my workspace files have). I understand this could be accomplished via [workspace settings](https://github.com/Microsoft/vscode/issues/8729) but I think this would be a very nice convenience feature.

**Comment by karanisverma** [comment]
I think what would be even better is that VS Code should have ability to select Language mode based on text of unsaved file. For instance if we write

```
.banner{
margin: 10px;
}
``` 
language mode should be selected as css/scss or 

```
<div>
  <p>yay!
</div>
```
language mode should be selected as html.

@bpasero I am not aware of feasibility of such feature. If it's possible. I would love to contribute make it happen.
