### ISSUE TITLE
Razor syntax highlighting incorrect when await/parentheses used in foreach loop

### ISSUE THREAD

**Issue by ascott18** [Microsoft/vscode#68810]
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Write the following code:
```cshtml
                        @inject UserRepository users
                        @foreach (var team in (await users.GetUserAsync(User)).Teams)
                        {
                            <span class="team-name">
                                @team.Name
                            </span>
                        }
```
2. Observe that syntax highlighting is nonfunctional for the rest of the document after that code:
![image](https://user-images.githubusercontent.com/5017521/52885866-78b31a80-3127-11e9-88ff-a6107355b9b1.png)

If I change the code around a little bit so the foreach contains no nested parens or `await`s, syntax highlighting is fine:
![image](https://user-images.githubusercontent.com/5017521/52885914-9aac9d00-3127-11e9-833e-a913c1c3f40a.png)

It seems to be related to both the `await` and the nested parentheses inside the foreach statement. Adding any parentheses, or an `await` without any parenthesis, will cause this to not work.

With just an `await` (code is silly in order to demonstrate the point):
![image](https://user-images.githubusercontent.com/5017521/52886299-bc5a5400-3128-11e9-809e-c9d2dc159328.png)

With just nested parentheses (again, silly code):
![image](https://user-images.githubusercontent.com/5017521/52886398-0b07ee00-3129-11e9-87b5-469e90b71dcc.png)

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

**Comment by alexr00** [comment]
This issue was moved to demyte/language-cshtml#27
