### ISSUE TITLE
Selecting a text copies it to the clipboard

### ISSUE THREAD

**Issue by Chieze-Franklin** [microsoft/vscode#68828]
Issue Type: <b>Bug</b>

Simply selecting a text copies it to the clipboard without me pressing Command+C.
This is really really annoying.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
learning-extension-vscode|dev|1.3.0
gc-excelviewer|Gra|2.1.29
docthis|joe|0.7.1
dotenv|mik|1.0.1
csharp|ms-|1.17.1
addDocComments|ste|0.0.8
open-in-browser|tec|2.0.0

</details>

**Comment by rebornix** [comment]
sorry for reaching out late, do you reproduce this issue with all extensions disabled?
