### ISSUE TITLE
Incorrect display of icons in the list of Windows 10 applications

### ISSUE THREAD

**Issue by Rakleed** [microsoft/vscode#68825]
- VSCode Version: 1.31.1
- OS Version: Windows 10 v. 1809

Steps to Reproduce:

1. Open Settings of Windows 10
2. Select Apps
3. Select Apps & features
4. Find Microsoft Visual Studio Code

Does this issue occur when all extensions are disabled?: Yes

<details><summary>Screenshot</summary>

![2019-02-16 08-53-45 settings](https://user-images.githubusercontent.com/19418601/52895482-35f74e00-31cc-11e9-9c5c-6eef914f4969.png)

</details>

**Comment by bpasero** [comment]
@Rakleed how does it look like?

**Comment by Rakleed** [comment]
@bpasero I attached a screenshot in the first message. Or something else you want?

**Comment by bpasero** [comment]
@Rakleed thanks, yeah that is weird. Does a uninstall and reinstall help?

**Comment by Rakleed** [comment]
@bpasero no, it doesn't.

**Comment by Rakleed** [comment]
@bpasero maybe you have [the same problem](https://www.kcsoftwares.com/bugs/view.php?id=5277). [Here](http://www.jrsoftware.org/ishelp/index.php?topic=setup_uninstalldisplayicon) you can read about it in more detail.

**Comment by bpasero** [comment]
Closing optimistically given https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon. Please report back otherwise.
