### ISSUE TITLE
Bookmark/Marker on Terminal Panel

### ISSUE THREAD

**Issue by rizamarhaban** [microsoft/vscode#68822]
When we use the Terminal/PowerShell/CMD panel, sometimes it has a very looooong history and require to go back at some lines which we probably forgot where. Simple example, when installing Kubernetes clusters and the there is a token from the master and we need to get that token later when installing other nodes. **A simple marker that we need to jump to that line**. Similar like in Visual Studio 201x which has Bookmark for codes capabilities.

The bookmark should be simple, can use mouse on the left side of the line on the Terminal or just like `Ctrl+Shift+B+[Space]` to mark the line. `Ctrl+Shift+B+[Backspace]` to remove bookmarks and `Ctrl+Shift+B+[Del]` to delete All Bookmark. Clearing the terminal windows will also delete all of the Bookmark/Marker.

**Comment by Tyriar** [comment]
We don't support bookmarks just yet but we do mark lines that commands run on which might solve your problem:

![image](https://user-images.githubusercontent.com/2193314/53246796-7dfff000-3666-11e9-8410-8b3b9bb36460.png)

They only have default keybindings on macOS but you can add custom one if you use it often:

```
	{ "key": "ctrl+up",          "command": "workbench.action.terminal.scrollToPreviousCommand", "when": "terminalFocus" },
	{ "key": "ctrl+down",        "command": "workbench.action.terminal.scrollToNextCommand", "when": "terminalFocus" },
	{ "key": "ctrl+shift+up",    "command": "workbench.action.terminal.selectToPreviousCommand", "when": "terminalFocus" },
	{ "key": "ctrl+shift+down",  "command": "workbench.action.terminal.selectToNextCommand", "when": "terminalFocus" },
```
