### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iamdebasis** [Microsoft/vscode#68827]
Issue Type: <b>Bug</b>

Visual Studio Code is unable to watch for file changes in this large workspace

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1196)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|4, 2, 2|
|Memory (System)|15.57GB (4.54GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
You probably need to follow this https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by iamdebasis** [comment]
I have already gone through these steps but the issue stays the same..

**Comment by Tyriar** [comment]
It might be one of the existing file-watcher issues then https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-watcher
