### ISSUE TITLE
"Find" breaks after toggling "Find in selection"

### ISSUE THREAD

**Issue by aleph-naught2tog** [Microsoft/vscode#68820]
Issue Type: <b>Bug</b>

* behavior persists with/without extensions enabled (just confirmed that it's independent of syntax/filetype, and also is still an issue with all extensions off + reloaded)
* independent of _how_ you choose to find a term -- e.g., starting from selecting the word and finding, or just opening find and typing it in
* behavior is independent of whether `autoFindInSelection` is enabled, as was suggested in another issue
* behavior is independent of whether the "Seed search string" option is selected
* I am *almost* positive this is from the latest release; I don't remember it ever being an issue, and it's constant now, and has the end result of making the local (e.g., _not_ 'find in project' version) find actually entirely unusable. 

The smallest, most reproducible version is this (but then I noticed related weirdness, which is below):

Steps:
1. Open the find (small, in-editor) tool.
2. Enter some text to find.
3. At this point, it behaves normally. `lorem` finds all instances of `lorem`, etc.
4. Toggle "find in selection" on: at this point, 1 instance will be found if you have "lorem", as an example, selected.
5. Toggle "find in selection" off: at this point, it will be broken completely, independent of if you turn find-in-selection on/off, try a different word, go for a single letter, highlight/unlight otherwords, etc.
6. To fix, `esc` shuts the find window, and we're okay; re-opening the find window works as before (and will predictably break again under the same conditions.)

Using my most recent attempts, I'm noticing this, which I think is the issue:

Assuming "lorem" is what you were looking for, and say 1 was found-- 
1. Hit backspace a bunch of times -- the "find" backs up, e.g., "lorem" is found, then "lore", then "lor", etc.
2. You hit backspace; *no characters are present in the text box at this moment*.
3. The other "l" (lowercase L) in the document are ghost-highlighted as if you had searched for them. However: nothing appears as "found" in the place next to the find (e.g., 1 of 1, etc, never appears)
4. Hit escape to close the find window.
5. Reopen the find window -- it will now have an "l" in it with all of those instances that were ghost-found now _actually_ found, although you never searched for the character.

eta, more notes:
* Focusing a different tab and then refocusing on the tab in question "fixes" it the same why closing the find widget and reopening it does (which makes sense)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by AlansCodeLog** [comment]
Just updated and ran into this. I downgraded to 1.31.0, but in 1.31.0 it gets stuck in "find in selection" and only switching tabs fixes it. Went down to 1.30.2 and now it's working again.

**Comment by roemhildtg** [comment]
Confirmed, switching tabs back and forth fixes the issue temporarily as @AlansCodeLog noted.

**Comment by rebornix** [comment]
Already fixed in Insiders and will be released with next Stable update. Thanks all for your feedback!
