### ISSUE TITLE
explorer bug

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#68821]
Issue Type: <b>Bug</b>

![bug](https://user-images.githubusercontent.com/20104656/52893415-deaaab00-31d6-11e9-8dc3-7c2cf5e3d687.gif)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|0.8.8
jsrefactor|cms|2.15.1
template-generator-vscode|Den|0.4.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
php-debug|fel|1.12.6
gitbook-kit|hoy|0.6.2
vscode-sshfs|Kel|1.12.3
markdown-shortcuts|mdi|0.11.0
hex-rgba-converter|med|1.0.4
php-namespace-resolver|Meh|1.1.4
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.1.0
cpptools|ms-|0.21.0
php-docblocker|nei|1.7.0
vetur|oct|0.15.1
vscode-php-getters-setters|php|1.2.3
view-in-browser|qin|0.0.5
minapp-vscode|qiu|1.12.1
vscode-formatall|rat|0.0.2
vscode-lowercase|rui|1.0.1
vscode-uppercase|rui|1.0.1
code-settings-sync|Sha|3.2.5
vscode-preview-server|yui|1.2.1
markdown-all-in-one|yzh|2.0.1
html-css-class-completion|Zig|1.18.0

</details>

**Comment by byyxx128** [comment]
老哥，你多说一句话能累死不……我看了半天才看懂……
***
**Let me explain some details.**
1. Create a new file in the explorer, and input any name. Do NOT press Enter.
2. Roll the mouse wheel to scroll.
3. Roll back.
You will see the new file has lost its file name.

**Comment by Yurunsoft** [comment]
> 老哥，你多说一句话能累死不……我看了半天才看懂……
> 
> **Let me explain some details.**
> 
> 1. Create a new file in the explorer, and input any name. Do NOT press Enter.
> 2. Roll the mouse wheel to scroll.
> 3. Roll back.
>    You will see the new file has lost its file name.

不知道用英文如何描述，中文老外看不懂，直接上图简单粗暴

**Comment by isidorn** [comment]
Closing as desgined / will not fix. Tree is virtual we dispose of the template as it goes out of view.
