### ISSUE TITLE
installed extension not working [Superuser]

### ISSUE THREAD

**Issue by baganaakh** [Microsoft/vscode#68834]
- VSCode Version:1.31.1
- OS Version:Debian9 Linux x64 4.9.0-8-amd64

installed extension not found in root user

**Comment by sandy081** [comment]
Extensions are installed in the user home directory where VS Code is installed. Let me know where did you install VS Code?

**Comment by baganaakh** [comment]
now I understand regular launch extension and launch VScode as root extension has both seperate different installation
i installed extension on regular launch but cannot edit on /var/www/html/
so I launched as root but there is no extension then install again on root
