### ISSUE TITLE
Feature request: Add Ctrl+Alt+N as a default shortcut for explorer.newFile

### ISSUE THREAD

**Issue by fwcd** [Microsoft/vscode#68836]
In larger workspaces it is very convenient to create new files directly in the explorer tree rather than having to navigate the default "Save As"-UI, especially since folders can easily be created by appending the directory path.

![image](https://user-images.githubusercontent.com/30873659/52900133-aca74200-31f2-11e9-8042-a1b444595ec8.png)

![image](https://user-images.githubusercontent.com/30873659/52900127-9e592600-31f2-11e9-83ab-54e93183af83.png)

Since `Ctrl+N` already binds to `workbench.action.files.newUntitledFile`, it would be nice to have `Ctrl+Alt+N` as a default shortcut for `explorer.newFile`. Although this is trivial to configure, it would ease setting up a new instance of Code and probably be useful to many users.

**Comment by isidorn** [comment]
Thanks for the suggestion but I would not change the current behavior, since this is easily configurable and if we change the shortcuts it might mess with other shortcuts existing users already set.
Closing as will not fix
