### ISSUE TITLE
VS Code doesn't inform why the file wasn't renamed

### ISSUE THREAD

**Issue by bona-petite** [microsoft/vscode#68835]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder with VS Code. The folder should contain the file you want to rename, say it's `a.txt`.
2. Open `a.txt` with another application (I gave it as input to a program running with Visual Studio).
3. While the program is running, try to rename the file in VS Code source tree.

Result: The file is not renamed (as it's used by another application) but there's no way to know why it wasn't renamed.
Expected result: The file is not renamed and a message box appears (or in some other way) to inform that the file cannot be renamed as it is being used by another application.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is probably an electron issue that the rename error is not popping up.
Right @bpasero ?
We had a similar thing for the delete error

**Comment by bpasero** [comment]
@isidorn negative, the "file does not move to trash" error is Linux/Electron specific due to the usage of the trash.
