### ISSUE TITLE
Black screen after update to 1.31

### ISSUE THREAD

**Issue by mrausch** [microsoft/vscode#68839]
Issue Type: <b>Bug</b>

* After updating to VS Code 1.31, starting the program only displays a black screen (as also described in issue #61624). This breaks the update for me.
* Hovering over the window with the mouse reveals some flickering tooltips, but that's everything that is displayed.
* starting with `code --disable-gpu` works properly, but I consider it a dirty and tedious workaround
* Rolling back to version 1.30.2 is my workaround, as graphics are working properly on that version.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3311)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (2.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mrausch** [comment]
Note: I also disabled automatic updates in settings, so VSCode does not automatically break again by auto-applying updates.

**Comment by mrausch** [comment]
The update works flawlessly on another computer.
Notice the differences in OS version.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by AlexTemina** [comment]
I have the same issue and I can confirm it does not happen with the exploration build. (Left is exploration build, right is normal version)
![image](https://user-images.githubusercontent.com/14157093/52937372-3ffd8600-335f-11e9-83f8-73d5d1d9ac8c.png)

**Comment by AlexTemina** [comment]
I can also confirm that it works properly on the insiders version.

**Comment by mrausch** [comment]
Thanks for your efforts and the feedback so far!
Unfortunately, this problem still persists in the latest release version. A recent update to 1.32.3 made me uninstall and rollback again.
Is there a roadmap for usage of electron 4.0 in "production"?

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by mrausch** [comment]
Still broken for me as of version 1.36.1

![image](https://user-images.githubusercontent.com/473925/62204664-f85b3b80-b38d-11e9-8887-af63b18efd4d.png)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
