### ISSUE TITLE
Command "Toggle terminal" not working through key combination, character ` is not Unrecognized.

### ISSUE THREAD

**Issue by fabiuz** [Microsoft/vscode#68830]
When you try to use the `` ctrl + shift + ` `` key combination, the built-in terminal does not open.
However, if I go to the menu, and click on the option, the integrated terminal opens normally.
I was also given the option to configure the control keys, and there appears `` "ctrl + shift +` " ``, however, if I try to change the key to the same keys, the window waiting for me to press the key combinations does not recognize the character `` ` ``, if I press the `` ` `` character a second time, unknown is displayed.
If I change the key combination to any other that does not have the ` character, everything works normally.

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: Linux Fedora 28

**Comment by alexandrudima** [comment]
@fabiuz What keyboard layout have you configured?

**Comment by fabiuz** [comment]
keyboard-layout: abnt br Portuguese Brazil.

**Comment by alexandrudima** [comment]
@fabiuz Can you please try to reproduce with the On Screen Keyboard as well? It does not reproduce for me:

With that keyboard layout, the toggle terminal is bound to `` ctrl + ' ``, as painted in the View menu:

![image](https://user-images.githubusercontent.com/5047891/55108508-0a715880-50d4-11e9-8da7-586ee5be0a9a.png)

When I press the key combination `` ctrl + ' ``, the terminal comes up:

![Kapture 2019-03-27 at 21 03 53](https://user-images.githubusercontent.com/5047891/55108445-eada3000-50d3-11e9-9873-31eb5a9985a0.gif)
