### ISSUE TITLE
It's so much lazzy and inefficient

### ISSUE THREAD

**Issue by Pomplad** [Microsoft/vscode#68838]
It's the most wonderful TE I found. But unfortunately it's **really slow** to lead and sometimes it seizes the whole computer and I have to reboot. I'm using it on Linux. Usually I work with HTML and CSS and 2-3 files stay open. I'm just using 5 plugins. But it behaves like super bulky game and slows down my computer which is no good I wish if you code it any lower level language to make it much efficient.

- VSCode Version: 1.31.1
- OS Version: Linux 

Does this issue occur when all extensions are disabled?: Yes. But with a little bit less bad

**Comment by lukechadwick** [comment]
What kind of hardware are you using? This runs smoothly even on my tablet.
