### ISSUE TITLE
Go to definition doesn't work

### ISSUE THREAD

**Issue by ChechoPerezH** [Microsoft/vscode#6883]
- VSCode Version: 1.1.1
- OS Version: Ubuntu 15.10

when i press F12 (or click on "go to definition" on menu) 

![screenshot from 2016-05-25 11-34-19](https://cloud.githubusercontent.com/assets/19575512/15548155/ba949342-226c-11e6-9361-05248acc53d0.png)

doens't work, what can i do?

**Comment by aeschli** [comment]
@ChechoPerezH What language is that?

**Comment by ChechoPerezH** [comment]
@aeschli I'm working with php.

**Comment by aeschli** [comment]
Sorry, the out-of-the box PHP extension doesn't support goto definition.
Please check out the marketplace for a PHP extension.
