### ISSUE TITLE
调试 JS 时 提示 program": "${workspaceFolder}/app.js" 不存在，为何，请问那里出错了？

### ISSUE THREAD

**Issue by Gumx1066520** [Microsoft/vscode#68842]
调试 JS 时 提示program": "${workspaceFolder}/app.js" 不存在，为何，请问那里出错了？

我的 launch.json 配置文件，如下：

{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/app.js", //这个配置成要调试的文件
            "stopOnEntry": false,
            "args": [],
            "cwd": ".",
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "preLaunchTask": "",
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858
        }
    ]
}

**Comment by Maledong** [comment]
@Gumx1066520：Please check whether you've got your 'app.js' file under your opened workspace.

**Comment by byyxx128** [comment]
/question
1. Please speak English here.
2. Do NOT ask questions here.
3. Read the link you mentioned above. If you have more questions, do as the following.

**Comment by byyxx128** [comment]
1. Please speak English here.
2. Do NOT ask questions here.
3. Read the link you mentioned above. If you have more questions, do as the following.

> Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

**Comment by weinand** [comment]
@Gumx1066520 Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
