### ISSUE TITLE
Update show error when running 2 instances of VS Code

### ISSUE THREAD

**Issue by mrbuds** [Microsoft/vscode#68846]
Issue Type: <b>Bug</b>

Having 2 instances of vs code started at once, i casually get this error:

Setup has detected that Setup is currently running.
Please close all instances of it now, then click Ok to continue, or Cancel to exit.

![preview](https://i.imgur.com/J6nMVoR.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (5.47GB free)|
|Process Argv|C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\140126336#2\SavedVariables\Transcriptor.lua|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.7.3
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
git-difftool|elp|0.1.0
prettier-vscode|esb|1.8.1
vscode-gitbuild|grz|1.0.1
discord-vscode|icr|3.2.1
Lua|key|0.0.9
python|ms-|2019.1.0
vetur|oct|0.15.1
wow-bundle|Sep|1.3.0
stylelint|shi|0.48.0
vscode-lua|tri|0.12.4

</details>

**Comment by joaomoreno** [comment]
> Having 2 instances of vs code started at once

Do you have 2 instances, each pointing to a separate user data dir?
