### ISSUE TITLE
Support more CSS for decorations before/after properties: border-radius, padding, border-width

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#68845]
I'd like to be able to make decorations that use `before`/`after` to insert little badges, but they look bad without rounded corners or padding:

<img width="183" alt="screenshot 2019-02-16 at 16 17 43" src="https://user-images.githubusercontent.com/1078012/52902262-678d0b00-3206-11e9-96d3-ec446f1aacbf.png">

`borderRadius` and `borderWidth` are both available on the decoration itself, but not on the `after` content. Padding would be better, though just having radius/width for borders would probably allow me to do the job by just using left/right borders.

**Comment by usernamehw** [comment]
You can simply inject them:
```ts
after: {
    textDecoration: ';border-radius:0.25rem;padding:0.2rem 0.5rem;',
},
```

**Comment by DanTup** [comment]
If that works, I'm sure that's a bug! 🤔

**Comment by usernamehw** [comment]
@DanTup So, you are not going to use it?

**Comment by DanTup** [comment]
Not unless someone from the Code team confirms it's not a bug so it's not likely to randomly break on me in the future (which I think is unlikely). @alexandrudima ?

**Comment by DavidLGoldberg** [comment]
I'm with @DanTup on this, it looks like a bug, I saw a similar approach, and was worried it wouldn't always be supported.

**Comment by DanTup** [comment]
@alexdima if this won't be implemented, is it safe for us to use the "workaround" posted above or is that likely to be fixed?
