### ISSUE TITLE
Increase the space between mouse and right-click menu

### ISSUE THREAD

**Issue by cand126** [Microsoft/vscode#68847]
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Right click on a word
2. An option is selected immediately because the mouse is on the right-click menu

I attached a short screen recording. I didn't move the mouse and the option was selected after right-clicking. This does not happen in every place where I right click.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6241921/52903193-31f21d00-321a-11e9-9144-006896258979.gif)

Does this issue occur when all extensions are disabled?: No

After I disabled all the plugins, the problem is gone because the menu is short, and the menu is always at the right-bottom or right-top direction of the mouse. It seems like my right-click menu is too long, so sometimes the mouse is on the middle of the right-click menu. It would be great to increase a small space between the mouse and the right-click menu.

**Comment by joaomoreno** [comment]
#65787
