### ISSUE TITLE
terminal appearance - text input has white background a

### ISSUE THREAD

**Issue by BurakAy** [Microsoft/vscode#68848]
When terminal opens the screen in blank due to text area having multiple new lines, must scroll up to see terminal has initialized . No visible cursor and first character input appears to be in middle of blank space. The issue appears to be intermittent, sometimes it initializes properly, sometimes it doesn't.

![first_char](https://user-images.githubusercontent.com/14030652/52903492-e02ea000-31e3-11e9-8d9c-e4cae992d496.jpg)

However, the following issues are always present. After entering second character, background of inputted text turns white. 

![white_second_char](https://user-images.githubusercontent.com/14030652/52903493-e3c22700-31e3-11e9-9b49-1bfa5f9f0d6d.jpg)

When backspace is used to delete inputted text, the white background remains up to the furthest previously inputted character.  Also, after inputting the first character, if you input a white space (press spacebar) the input following the space becomes invisible/disappears.

![backspace_white](https://user-images.githubusercontent.com/14030652/52903497-e6248100-31e3-11e9-8fae-408c4dd8ac18.jpg)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz (2 x 2793)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
jquerysnippets|don|0.0.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
beautify|Hoo|1.4.8
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
node-debug2|ms-|1.31.3
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.2
LiveServer|rit|5.5.1
vscode-icons|rob|8.1.0
sass-indented|rob|1.5.1
vscode-react-native|vsm|0.8.0
vscode-wakatime|Wak|1.2.5
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>
ste.

**Comment by BurakAy** [comment]
Here is another image showing the appearance after a command is run. In this example I ran 'npm start'.

![input](https://user-images.githubusercontent.com/14030652/52903600-7ca57200-31e5-11e9-9a05-5193c9b6903c.jpg)

**Comment by jevenson** [comment]
Same here but its all blue!
![image](https://user-images.githubusercontent.com/9632520/53142126-68040980-3558-11e9-9f98-5516db523a4d.png)

**Comment by Tyriar** [comment]
This normally happens when you've tweaked cmd.exe's default colors.

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by l1xnan** [comment]
In the windows 10 v1809 environment, many third-party terminals have this problem(https://github.com/felixse/FluentTerminal/issues/108#issuecomment-433807013). This problem can be resolved by removing `HKEY_CURRENT_USER\Console\ScreenColors`  in the registry.
