### ISSUE TITLE
Unable to connect to extension marketplace behind proxy

### ISSUE THREAD

**Issue by emilime** [Microsoft/vscode#68843]
Issue Type: <b>Bug</b>

1 Open marketplace inside VSCode
2 wait for error message in extensions bar

Yes I'm behind a proxy but it always worked up to the version 1.31, starting from version 1.32 it seems broken (in the same LAN obviusly).

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.87GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chrmarti** [comment]
@bpasero This shouldn't be affected by my work which only targets the extension host. Did anything change on Electron's side? /cc @joaomoreno

**Comment by bpasero** [comment]
Yes, proxy is reimplemented in Electron 3, it is a possible regression from that update.

**Comment by joaomoreno** [comment]
#34385

**Comment by emilime** [comment]
I've just installed last Insiders and the bug is still there, sadly from this version I can not use anymore extensions marketplace at work...

**Comment by chrmarti** [comment]
@emilime What kind of proxy is it? What's in your OS' proxy settings?

**Comment by emilime** [comment]
@chrmarti the corporate proxy is Squid
In my OS' proxy settings at work, proxy is obviously set in Internet Options so Chrome and all the other sw can see it. My idea is that with version 1.32 these system settings are not read.
Is there any debugging log where I can verify it?

**Comment by chrmarti** [comment]
@joaomoreno This seems to be a regression in 1.32, not #34385. Did anything change? We are using the XHR for extensions, don't we?

**Comment by joaomoreno** [comment]
Did not change anything. Did Electron update?

**Comment by chrmarti** [comment]
Found it: https://github.com/Microsoft/vscode-remote/commit/357efea93b0ff0529f02ebe8ee0728043700038b#r32496338

**Comment by emilime** [comment]
It works now! Thank you!
