### ISSUE TITLE
Clear User‘s Data While Uninstalling

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#68841]
Issue Type: <b>Feature Request</b>
Add a option for the uninstaller to clear user‘s data and settings.

This is a feature request. I'm not sure if anyone has reported this yet, but I didn't find any.
I think this feature could be considered after this issue https://github.com/Microsoft/vscode/issues/3884 is done, because currently the user's data locations are very complicated.

VS Code version: Code - Exploration 1.32.0-exploration (d0aafbad741c2316c92b369113abe0205f41e84e, 2019-02-13T07:02:19.413Z)
OS version: Windows_NT x64 10.0.18334

**Comment by usernamehw** [comment]
#66837

**Comment by byyxx128** [comment]
Duplicate. Close now.
