### ISSUE TITLE
Screencast: Some keys do not get special treatment

### ISSUE THREAD

**Issue by knyzorg** [microsoft/vscode#68849]
Currently, if I mash backspace a bunch, this is what happens:

![image](https://user-images.githubusercontent.com/10255546/52903625-30126480-31ee-11e9-82bd-4a1a2712558e.png)

However, for arrow keys, it only shows up a single time.  This seems unintended and backspace needs to be treated the same way as enter and the arrow keys regardless of how long I press it.

**Comment by joaomoreno** [comment]
Also <kbd>Escape</kbd>

**Comment by devilirium** [comment]
I was unable to reproduce this at commit e96ab81. Has it been fixed already?
OS: Windows 10 Enterprise N - 1803 (17134.590)

**Comment by dyc3** [comment]
I am able to reproduce this issue and I'd like to fix it. Any code pointers would be a great help.

**Comment by dyc3** [comment]
@joaomoreno, Would it be better to have counters for the number of times `Backspace` or `Escape` is pressed? Or to just display the key once without any counters?

Here what I mean by counters:
![vscode-new-screencast-bahavior-with-counters](https://user-images.githubusercontent.com/1808807/53783041-fc1d8b80-3edd-11e9-9e55-014fbecd2495.gif)

**Comment by joaomoreno** [comment]
I don't think we need counters at all. Wouldn't simply `Backspace` suffice, no matter how many times you press it?

**Comment by dyc3** [comment]
Yeah, you're right. I'll fix it up and send a pull request.

**Comment by adamtajti** [comment]
It seems like other screencasting applications have the counter concept as well. I think it might be better to make it configurable.

Carnac (Windows app) seems to have this behavior by default: https://youtu.be/kSL-DhACBEk?t=293

Screencast (Linux app) notes:
> Compress repeats
> When enabled, contiguous repeated sequences are truncated after the requested threshold. A counter of total occurrences is shown instead, which is generally more legible.

Screenkey (Linux app). It's a configurable setting. Demonstration:
https://youtu.be/OkD0VkGe20I?t=269

**Comment by dyc3** [comment]
That's certainly another option. We'll leave it off by default. How would I go about adding it to the settings?

**Comment by dyc3** [comment]
Also, I think it would be more readable if letters/numbers/symbols didn't have spaces in between them. What do you guys think?

**Comment by adamtajti** [comment]
I had the same idea about the spaces and casing too, but I didn't want to go overboard. Maybe the counters were a bit too much for this bug fix as well and it should've been handled in a seperate feature request issue.

I agree with leaving it off by default. I'm trying to figure out how to modify the settings now. I think it should be under the Text Editor > Screencast category or Features > Screencast (they don't exist)

Lets see what @joaomoreno says.

**Comment by joaomoreno** [comment]
I really don't have an opinion. We should make the simplest thing possible. I'm not keen on adding settings, since VS Code is not a screencasting tool. ;)

**Comment by adamtajti** [comment]
I'm not sure if that reasoning stands now that VS Code became a tool that has screencasting capabilities. Although I think we all agree that the focus should be on making the tool better for coding, I think we can make this feature better with the suggested changes and make the most of it. Who knows, maybe this will be a feature that will persue someone on a conference to give VS Code a try :) (I'm thinking about teachers, streamers)

I think that we should create another issue though with the feature-request tags to discuss and track those changes there, while we fix the issue with a single `Backspace` or `Escape` output here. I'll have to work now, but I could create the issue later.

Would that work for you @dyc3 ?

**Comment by dyc3** [comment]
Sounds like a plan. I'll send the pull request with the simple fix later today.
