### ISSUE TITLE
Map key event labels to alternative representations

### ISSUE THREAD

**Issue by knyzorg** [microsoft/vscode#68850]
Currently, backspace, arrow keys, shift, etc. show up as their text label representation. 

While [this is not a problem on (what I'm assuming) are Macs](https://code.visualstudio.com/raw/images/1_31/screencast.gif), it is a problem on Linux where I see "Backspace", "Enter", "RightArrow", and so on.

A solution I would like to propose is to have configurable options as to how to map the text label which is currently displayed to something else. For example:

```json
{
  "Backspace": "⌫",
  "Shift": "⇧"
}
```

And so on. This would make for a platform-agnostic opt-in approach.

**Comment by knyzorg** [comment]
If possible, I'd like to implement this myself to learn about the vscode code-base. If someone would be willing to mentor me in this regard, I would really appreciate it.

**Comment by yume-chan** [comment]
*I don't know the codebase well either, but I want to help as much as I can*

A quick search for "workbench.action.toggleScreencastMode" leads to

https://github.com/Microsoft/vscode/blob/df619d25b2d9d04d6b341d15570ee2e2d2e7ad50/src/vs/workbench/electron-browser/actions/developerActions.ts#L111-L113

And the related codes are:

https://github.com/Microsoft/vscode/blob/df619d25b2d9d04d6b341d15570ee2e2d2e7ad50/src/vs/workbench/electron-browser/actions/developerActions.ts#L183-L191

So the screencast mode uses same logic as the keybinding editor.

After digging into how `IKeybindingService.resolveKeyboardEvent` is implemented, it seems it's fairly complicated. I don't sure where you should start at.

**Comment by knyzorg** [comment]
Despite my burning desire to dig into vscode, I simply do not have the time for the next couple of months. I wouldn't want to hold up people interested in fixing it with my expressed desire to do it myself.
