### ISSUE TITLE
File with long lines cause severe performance issues

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#6885]
1. Open the following [two test files](https://github.com/Microsoft/vscode/files/282544/test.zip) in vscode.
2. Change user/workspace settings to include:  "editor.wrappingColumn": -1
3. Scroll to a column larger than 1500 -> selecting text with the mouse becomes painfully slow
4. Scroll to a column around 9500 -> typing is not working anymore (or it's so slow that I didn't wait long enough)

For the regular text editor that's an esoteric case but it hits you with all it's might when you compare the two files. 

-> scrolling up and down has painful delays
-> editing in the right pain is impossible
-> since this is happening in the UI thread everything is blocked

**Comment by alexandrudima** [comment]
First slowest thing noticed when selecting some text on line 84 in external-file-59.txt:

rendering decorations:
![image](https://cloud.githubusercontent.com/assets/5047891/15580994/0442f872-236b-11e6-9c10-7f74085cfd88.png)

**Comment by alexandrudima** [comment]
`"editor.selectionHighlight": false` has a huge impact of making things faster again

**Comment by alexandrudima** [comment]
A single query to `TextRange.getClientRects()` for line 84 in `external-file-59.txt` takes **6ms**!! We call that all the time in order to render decorations / selection at the right spot. It looks like Chromium has a `O(N)` algorithm tucked away in there, even if the text is layouted.

**Comment by alexandrudima** [comment]
And this explains why `wrappingColumn: 300` is the default :). I will follow up on this with filing bugs against Chromium...
