### ISSUE TITLE
Integrated Terminal: Environment Path not expanded correctly

### ISSUE THREAD

**Issue by kjathey** [Microsoft/vscode#68852]
Issue Type: <b>Bug</b>

### Scenario:
- an exe is installed to `C:\Users\<User>\AppData\Roaming\local\bin`
                (this path was not in my path before)
- added User path  `C:\Users\<User>\AppData\Roaming\local\bin` to Environment Path
               (use any method you want to do this)
- Restarted all instances of  VSCode
- Open Integrated Terminal (run the following steps individually)
```powershell
$env:path -split ';' | sls 'roaming'  #... path not found
[Environment]::GetEnvironmentVariable("Path") -split ';' | sls 'roaming   #... path not found
[Environment]::GetEnvironmentVariable("Path","Process") -split ';' | sls 'roaming'  #... path not found (this is equiv to prior step)
[Environment]::GetEnvironmentVariable("Path","User") -split ';' | sls 'roaming'   #... path found
```
     
### Workaround:
in settings add:
```json
    "terminal.integrated.shellArgs.windows": [
      "-NoExit",
      "$env:path+=';' + [Environment]::GetEnvironmentVariable(\"Path\",\"User\")"
    ]
```
### Notes:
This seems to be #26048 [all the comments there are relevant]  still happening... 
no idea whether this is really OS issue or not but thought this information would help.

Impact:  extensions that need access to other user installed executables may not find them unless the extension provides a path setting...

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
odatatools|apa|2.0.1
vscode-open-file-folder|auc|0.0.4
vscode-django|bat|0.19.0
converter|bey|0.0.3
django-html|bib|1.3.0
django-snippets|bib|1.1.1
color-info|bie|0.5.0
markdown-mermaid|bie|1.1.2
open-html-in-browser|cod|0.1.21
vscode-markdownlint|Dav|0.24.0
githistory|don|0.4.6
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
xml|Dot|2.4.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.5.1
restore-editors|eam|0.2.1
windows-explorer-context-menu|ele|2.0.0
rightclick-git|Eve|1.0.0
code-runner|for|0.9.7
day-night-theme-switcher|fre|0.1.2
graphviz-markdown-preview|gee|0.0.7
mdmath|goe|2.3.9
yuml|Jai|3.3.0
markdown-extended|jeb|1.0.5
plantuml|jeb|2.10.3
nbpreviewer|jit|1.2.2
ssmacro|joe|0.6.0
language-julia|jul|0.11.4
testing-api|jus|0.0.4
vscode-erd-preview|kai|4.0.3
chat|kar|0.11.0
vs-color-picker|lih|1.0.0
MagicPython|mag|1.1.0
OpenVim|mat|0.0.8
vscode-azurefunctions|ms-|0.14.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1182
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.7
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.2
live-server-preview|neg|0.1.4
printcode|nob|3.0.0
vscode-json-transform|oct|0.1.2
markdown-checkbox|PKi|1.4.2
project-snippets|reb|0.5.0
toggle|reb|0.0.1
LiveServer|rit|5.5.1
vscode-icons|rob|8.1.0
partial-diff|ryu|1.4.0
vscode-open|san|0.1.0
powerquerymlanguage|sea|1.0.0
code-settings-sync|Sha|3.2.5
markdown-preview-enhanced|shd|0.3.11
vscode-table-formatter|shu|1.2.1
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
vscode-odata|sta|0.1.0
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
open-in-browser|tec|2.0.0
vscode-markdown-paste-image|tel|0.12.0
vscodeintellicode|Vis|1.1.3
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
markdown-pdf|yza|1.2.0

(7 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I think I'll reopen the old issue.
