### ISSUE TITLE
Terminal "ansiBrightYellow" has very poor readability on light themes

### ISSUE THREAD

**Issue by pedrogarcia** [Microsoft/vscode#68853]
Issue Type: <b>Bug</b>

The terminal color `terminal.ansiBrightYellow` has very poor readability on light themes. Terminal apps only uses yellow because they usually have a dark background. While the description calls it yellow, wouldn't be better if it defaulted to blue or some other color that's not yellow for light themes?

![vsode_bright_yellow_light_theme](https://user-images.githubusercontent.com/2473545/52904691-b04cc000-3216-11e9-8f05-9bee66a5a9c3.jpg)

![vsode_bright_yellow_dark_theme](https://user-images.githubusercontent.com/2473545/52904690-adea6600-3216-11e9-9d4d-f20927c3ba69.jpg)

![terminal_yellow](https://user-images.githubusercontent.com/2473545/52904688-a925b200-3216-11e9-9d12-02636b71ea11.jpg)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
code-runner|for|0.9.7
terminal|for|0.0.10
matlab|Gim|0.9.0
language-julia|jul|0.11.4
nim|kos|0.6.3
r|Mik|0.0.6
python|ms-|2019.1.0
cpptools|ms-|0.21.0
sublime-keybindings|ms-|4.0.0
r-lsp|REd|0.0.8
vscode-fileutils|sle|2.13.5
markdown-pdf|yza|1.2.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
It has to be yellow as that's what powershell is telling the terminal to render. This is a tricky problem as the color needs to work as a background color as well. For now I'd say either override the color in your settings via `workbench.colorCustomizations` or switch themes.

This is the best solution for this: https://github.com/xtermjs/xterm.js/issues/1514
