### ISSUE TITLE
Inserting tab spaces in a new line when using \n

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#68856]
I'm using vscode with python and every time I use \n in a string and hit enter to make a new line, this new line comes with a 4 blank spaces as a tab. E. g.:

v1 = str(input('Type something: ')) [enter]
(new line without tab sapces)
v2 = str(input('Type something\n ')) [enter]
....(4 tab spaces)

![vscode-issue](https://user-images.githubusercontent.com/15204313/52905479-bc8a4a80-3221-11e9-9ef5-af62cb8831a7.gif)

**Comment by rebornix** [comment]
No longer reproducible in latest VS Code.
