### ISSUE TITLE
問題が過剰

### ISSUE THREAD

**Issue by yukkuriemilin** [Microsoft/vscode#68859]
Issue Type: <b>Bug</b>

対して意味のない問題とかを消したりできないためものすごく問題部分がうるさくて少し使いづらい

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
vscode-twitter|aus|0.7.1
regex|chr|0.2.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.4.6
gitlens|eam|9.5.1
LogFileHighlighter|emi|2.4.3
prettier-vscode|esb|1.8.1
vscode-todo-plus|fab|4.11.4
vscode-pull-request-github|Git|0.4.0
rest-client|hum|0.21.1
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.1
plantuml|jeb|2.10.3
rainbow-csv|mec|1.0.0
gitignore|mic|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-language-pack-ja|MS-|1.31.4
python|ms-|2019.1.0
vscode-icons|rob|8.1.0
bash-debug|rog|0.3.3
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.5
trailing-spaces|sha|0.2.11
addDocComments|ste|0.0.8
vscode-todo-highlight|way|1.0.4
vscode-proto3|zxh|0.2.2

</details>

**Comment by Maledong** [comment]
@yukkuriemilin：For better support and easy to be understood, please attach your English statement :)
