### ISSUE TITLE
Display color error after newest release on surface

### ISSUE THREAD

**Issue by vomyrak** [microsoft/vscode#68854]
Since the latest update, the colour display of my vscode on surface is very wrong. The default colour scheme now look like this
![20190216202914](https://user-images.githubusercontent.com/16241056/52905088-cf564c80-322c-11e9-9fd9-b73d413d8657.png)
In fact the display of all themes are wrong, just another example:
![20190216205429](https://user-images.githubusercontent.com/16241056/52905103-16dcd880-322d-11e9-83e1-51605fdcc51e.png)

Reinstallation and reset settings have no effect.

**Comment by vomyrak** [comment]
I'm using surface pro 5 running windows 10 17134.590. No issue is observed on my other pc running the same system

**Comment by vomyrak** [comment]
Update: Rolling back to version 1.30.2 the problem disappears, but if I try to update again the the same problem is reproduced.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by vomyrak** [comment]
No, the problems are not reproduced with the windows exploration build

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
