### ISSUE TITLE
selecting all <div> in PHP when select a div

### ISSUE THREAD

**Issue by ziaurabdirahman** [Microsoft/vscode#68869]
- VSCode Version: 1.32.0-insider
- OS Version: Ubuntu 16.04 (32bit)

Steps to Reproduce:

1. When select  a html <div> it selected all div. it should select only the <div> that i am working.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@ziaurabdirahman how are you selecting the div? Are you using the smart select feature?

**Comment by ziaurabdirahman** [comment]
I am selecting a div using mouse click
