### ISSUE TITLE
Chinese input mehod bug in terminal console

### ISSUE THREAD

**Issue by imaginezz** [Microsoft/vscode#68865]
- VSCode Version:1.31
- OS Version:OSX 10.14.3

Steps to Reproduce:
0. I use capslock to change Chinese/English input mode(Sougou IME) in my Mac. If I use Chinese, the capslock light is off, and for English, is on.
1. If I use English Mode(capslock light is on) input English in terminal, the characters in terminal is captial letters. If I use Chinese Mode(capslock light in off) input English in terminal, the characters in terminal is lowercase letters. 
2. My IME works well in previous VSCode versions (in Chinese/English mode, the character in terminal is always lowercase, unless shift is pressed).

Does this issue occur when all extensions are disabled?: Yes

**Comment by yutent** [comment]
same bug for me.
vsc: 1.31.1
os: macos 10.14.3

**Comment by lxx2013** [comment]
same bug for me.
os: macos 10.13.4

**Comment by lxx2013** [comment]
A temporary solution : download v1.30.2 from [https://code.visualstudio.com/updates/v1_30](https://code.visualstudio.com/updates/v1_30).After install,  set the 'UPDATE CHANNEL' to 'none' in the preference.

**Comment by yutent** [comment]
@lxx2013 
![image](https://user-images.githubusercontent.com/11972650/53391191-8478c980-39d0-11e9-9a80-2ad9fb595191.png)
Set this config to be `true`, or remove  . It will works.
