### ISSUE TITLE
Newly created file with '/' didn't show up automatically

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/vscode#68864]
Issue Type: <b>Bug</b>

1. Click 'New File' button in Explorer
1. Type a name with `/`. E.g. `dirName/filename.txt`

File created but didn't show up in the explorer automatically.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (16.58GB free)|
|Process Argv|D:\SharedData\Non-Monetization.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.6.2
Bookmarks|ale|10.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.26
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
xml|Dot|2.4.0
scala-lsp|dra|0.2.3
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
lintlens|ghm|2.3.0
vscode-pull-request-github|Git|0.4.0
mdmath|goe|2.3.9
gc-excelviewer|Gra|2.1.29
todo-tree|Gru|0.0.118
beautify|Hoo|1.4.9
rest-client|hum|0.21.1
ilspy-vscode|ics|0.7.5
latex-workshop|Jam|5.21.0
csharpextensions|jch|1.3.0
webpack|jer|2.1.3
nbpreviewer|jit|1.2.2
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
vscodeilviewer|jos|0.0.1
docomment|k--|0.1.3
Lua|key|0.0.9
remotefs|lix|0.0.13
latexcompile|mat|0.7.1
rainbow-csv|mec|1.0.0
azure-pipelines|ms-|1.147.1
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.14.0
vscode-azurestorage|ms-|0.6.0
vscode-cosmosdb|ms-|0.10.0
vscode-kubernetes-tools|ms-|0.1.16
mssql|ms-|1.4.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-node-azure-pack|ms-|0.0.5
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1182
team|ms-|1.144.1
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.11.2
vetur|oct|0.15.1
vscode-docker|Pet|0.5.2
view-in-browser|qin|0.0.5
java|red|0.38.0
vscode-yaml|red|0.2.1
vscode-icons|rob|8.1.0
bash-debug|rog|0.3.3
rust|rus|0.5.3
partial-diff|ryu|1.4.0
aspnet-helper|sch|0.6.4
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.2.5
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.6.10
msbuild-project-tools|tin|0.2.53
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
unity-debug|Uni|2.6.6
usql-vscode-ext|usq|0.2.14
vscode-bond|vic|0.0.9
vscode-scope|vic|0.0.15
vscode-sed|vic|0.0.4
vscodeintellicode|Vis|1.1.3
azure-iot-toolkit|vsc|2.2.0
vscode-java-debug|vsc|0.16.0
vscode-maven|vsc|0.14.2
vscode-import-cost|wix|2.12.0
t4-support|zbe|0.4.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by isidorn** [comment]
Duplicate. Will be fixed this milestone.
