### ISSUE TITLE
[Split Terminal] Text overlaps terminal boundary

### ISSUE THREAD

**Issue by martellaj** [microsoft/vscode#68861]
Issue Type: <b>Bug</b>

1. Open a terminal with a long path such that it goes to the end of the line.
2. Split the terminal.

![image](https://user-images.githubusercontent.com/1019478/52909005-7d65f480-3235-11e9-9338-662989dfc892.png)

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (6.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.2.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.5.1
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
sort-typescript-imports|mic|1.4.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.2
polacode|pnp|0.2.2
vscode-icons|rob|8.1.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.5
vscode-todo-highlight|way|1.0.4

(3 theme extensions excluded)

</details>

**Comment by tdwright** [comment]
I also have this issue. Seems to have started with v1.31.1.

Possibly related to the new reflow behaviour?

**Comment by ctcampbell** [comment]
Same issue, running 1.31.1 on macOS 10.14.3

<img width="1446" alt="screenshot 2019-02-19 at 12 31 34" src="https://user-images.githubusercontent.com/808531/53015215-66482200-3442-11e9-89e0-30e105c30676.png">

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
