### ISSUE TITLE
File Manager Bug for ubuntu 18.04

### ISSUE THREAD

**Issue by abusedcharacter** [Microsoft/vscode#68860]
- VSCode Version: Ubuntu 18.04.2 LTS
- OS Version: 1.31.0

Steps to Reproduce:

1. Download "Visual Studio Code" from "Ubuntu Software". 
2.  Go to "open file" and then the file manager is buggy the cancel and open buttons do not show up but they are there definitely there. I think in general visual code file manager is broken.
![bug](https://user-images.githubusercontent.com/32622534/52908021-efccd980-3221-11e9-911e-add11f0bf102.png)
.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)
