### ISSUE TITLE
Vscode 2019 Windows Speech Bug

### ISSUE THREAD

**Issue by BoxOfCereal** [Microsoft/vscode#68873]
Using WSR on Windows 10 causes consistent .5-1 second  'hiccups's of unresponsive. What's interesting is that this same issue happens when using recent versions of FireFox except the .5-1 seconds becomes 10-15 seconds.

- VSCode Version: January 2019
- OS Version: Windows 10

Steps to Reproduce:

1. Open Windows Speech Recognition program 
2. Click the microphone to turn on WSR
3. Make VScode active and try to use as normal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This might be electron related or WSR related. Please file the issue against those products.
There is nothing in vscode which we can do to fix this
