### ISSUE TITLE
Windows 10, multiple monitors, VScode window size

### ISSUE THREAD

**Issue by precisonline** [microsoft/vscode#68879]
All I've read says that if you change the size of the vscode window and then close and restart the program, it should reappear with the same size and position that it last had.  It does in fact keep the position, but the window size returns to a default size.  See screencast;

https://www.screencast.com/t/45DLktEY

VSCode 1.31.1
Windows 10 build 1809 (OS Build 17763.292)

**Comment by bpasero** [comment]
@precisonline does it reproduce when you configure `"window.titleBarStyle": "native"` ?

**Comment by precisonline** [comment]
Thank you sir. I changed "window.titleBarStyle" to "native", resized the window larger, closed VSCode, reopened, and it opened with the smaller window size.  So this change has had no appreciable impact on the issue.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by precisonline** [comment]
Thank you for the build.  This version has the same issue.  See this screencast:

https://www.screencast.com/t/n9sfgKQ2tCsX

**Comment by precisonline** [comment]
I also tried setting the "window.titleBarStyle" to "native" with the exploration build - no change.  The VSCode starting window still starts small.

I don't know if this is related to the issue but my environment is a laptop with a 34" extension monitor running at 3440x1440 via HDMI.  The window height appears to be limited to the max height of my laptop screen which is running at 1366x768.  Just for grins, I resized the VSCode(E) window to be **wider** than my smaller screen, and when I reopened the program it was sized to fit on my laptop screen, even though I run VScoe on a monitor that is much larger.

**Comment by precisonline** [comment]
New information: Following on my earlier tests, I swapped monitors so that the larger one was the primary monitor.  Following this change, VSCode opens the window at the size I want. So it does tend to suggest that the window size is being filtered through the geometry of the primary monitor.

**Comment by seraku24** [comment]
I can confirm this behavior on my machine.  I have two monitors of different sizes (1280x1024 and 1920x1080).  My primary is the smaller of the two, but I often work on the larger secondary.  While Code does open on the correct monitor with the expected position, its size is initially constrained to the smaller monitor's dimensions.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by precisonline** [comment]
Thank you sir.  I was traveling last week so I didn't have my
multiple-monitor setup until today.  I am testing this now and the problem
remains.  In short, when my big monitor is not the primary monitor, VSCode
starts up with a window size that would fit on my smaller (laptop) screen.
When the larger extension monitor is primary, VSCode starts up with the
window size as expected - not smaller.

Here's what I did.  Before I installed the Exploration version, I had my
large HDMI monitor as the primary on my system and the laptop screen as
#2.  Before installing anything I swapped the primary and secondary
monitors in the Settings on Windows 10.  Then I installed the Explorer
version and allowed the program to open after install.  It opened up on the
primary (smaller) monitor and was slightly smaller than maximized and
halfway scrolled off the left of the screen.  I dragged the window to the
secondary (larger) monitor and resized the window to be top to bottom of
that screen, which is 1440 pixels in height.  I then closed VSCode and
reopened, and the size was once again about 720px high, suitable for the
smaller screen.

I recorded this video to demonstrate:

https://www.screencast.com/t/KNZT5qafGj






*Kevin King, President / Chief Technologist*
Precision Solutions, Inc.
630 15th Ave Suite 201, Longmont, CO 80501
Phone: 303-651-7050  Fax: 720-442-9204
Kevin@PrecisOnline.com | https://www.PrecisOnline.com
<https://www.precisonline.com/>

**Comment by bpasero** [comment]
Thanks, the videos are helpful. This issue sounds somewhat familar. I think this could be the same as https://github.com/electron/electron/issues/20351

**Comment by precisonline** [comment]
I would agree, they are related. Maximized is no problem but not maximized
and larger than the default display does clamp the size to the max of that
display.

**Comment by sv-vv** [comment]
Installed the `.deb` exploration build [linked above](#issuecomment-539530419) on Linux Mint 18 and it behaves as follows.
I have two identical screens on my computer, placed side-by-side horizontally.
I resized the VSCode window to be larger than one screen then quit VSCode and started it again.
I tested both cases when the top-left corner of the window (larger than one screen) is on the left and on the right screen.

Using `native` (my preferred value) for "Title Bar Style", VSCode restores only the Y position of the window and places it on the left-hand side of the screen that contained its top-left corner before restart.
Regarding the size, only the window height is restored, the width is constrained to the width of the monitor.

Using `custom` Title Bar Style, the window is restored at its original position when the top-left corner was on the left screen. It is restored on the left-hand side of the right screen when the original position of its top-left corner was on the right screen. The vertical position is restored in both cases.
In both cases the height is restored correctly but the width is constrained to the width of the monitor.

---
The `.deb` package listed above installs VSCode Explorations 1.37. It notified me about a new version being available and I upgraded it to 1.39 but the behaviour exposed above didn't change.

**Comment by danmarshall** [comment]
Hello, since the 1.40.0 update, my VSCode window will not resize vertically correctly. I have 2 monitors, one with high pixel density and one with low. When VSCode is moved to the low density monitor, the height is about 80% of the screen and cannot get smaller 😐.

```
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by bpasero** [comment]
@precisonline
