### ISSUE TITLE
Explorer file tree filtering does not show files named index.js

### ISSUE THREAD

**Issue by beaugunderson** [Microsoft/vscode#68886]
Issue Type: <b>Bug</b>

Focusing the explorer file tree, then typing `/.js` and ensuring that the mode is "filter" (as opposed to highlight) shows me all of my JavaScript files, except the ones named `index.js`.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
chat|kar|0.11.0
dotenv|mik|1.0.1
extension-manifest-editor|ms-|0.1.5
python|ms-|2019.1.0
vsliveshare|ms-|0.3.1182
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
autolaunch|phi|2.0.2
vscode-sort-json|ric|1.13.0
vscode-icons|rob|8.1.0
multi-command|ryu|1.3.0
stylelint|shi|0.48.0
vscode-fileutils|sle|2.13.5
vim|vsc|1.0.8
vscode-wakatime|Wak|1.2.5
quokka-vscode|Wal|1.0.183
convert-object-to-jsx|zac|0.3.0
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by beaugunderson** [comment]
Ah, not a bug, just a misunderstanding on my part that filtering would show files in collapsed folders (I managed to find the files I expected by expanding every folder). If that's the correct behavior then this isn't a bug, but I'll let a maintainer decide whether it is or not.

**Comment by isidorn** [comment]
Yeah expected behavior.
There is a seperate feature request to resolve all files before filtering which would help with your confusion
