### ISSUE TITLE
Sidebar explorer folder name update from uppercase to a generic name 

### ISSUE THREAD

**Issue by nadeemkhedr** [Microsoft/vscode#68889]
## Proposal: 

changing the structure of the headers in the sidebar by changing the existing `FOLDER_NAME` header to a generic name like:
- Folders
- Project

## Reasoning:  

I understand the folder name is uppercase for consistency but I think it is confusing and different from the rest of the headers

Rest of the headers are vscode generated but this one is referencing project's information

![image](https://user-images.githubusercontent.com/180256/52923833-adf87c00-3364-11e9-86a9-d0bb7f7a2eb0.png)

The example above is that I was in folder `test` and it took me a minute to understand that this is not a vscode panel for test, but it is actually my folder

related to #47213

**Comment by isidorn** [comment]
Thanks for your suggestion.
However we would not change this as it would piss off a lot of our users.
Also the name of the workspace folder is important and imho deserves a spot there.

So closing as designed.
