### ISSUE TITLE
Explorer simple navigation should reset filter when focus lost

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#68880]
Currently, navigating Explorer view in simple mode doesn't clear the navigation filter text when focus is lost (including opening any other panel or deactivating VS Code program window).

I suggest to clear the Explorer view navigation filter in simple mode when Explorer view loses focus.

**Comment by isidorn** [comment]
This is tree specific, forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
Not sure...
