### ISSUE TITLE
Markdown preview does not respect set font size

### ISSUE THREAD

**Issue by GeekForged** [Microsoft/vscode#68887]
Issue Type: <b>Bug</b>

Steps to reproduce

* Set a font size such as 20 in your settings.
* Open and edit a new markdown file.
* Open a markdown preview of the file you just created.

The font size appears to be at the default of 14.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3310)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (3.38GB free)|
|Process Argv|--disable-direct-composition|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Use the `markdown.preview.fontSize` setting instead

**Comment by GeekForged** [comment]
Thank you for pointing me in the correct direction.
