### ISSUE TITLE
Filtering breadcrumbs to no results shows floating filter popup

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#68881]
- Open breadcrumbs picker
- Enable "filter on type"
- Type a query with no results

![image](https://user-images.githubusercontent.com/323878/52920444-2a398380-32c1-11e9-99a6-1f06e76eacd6.png)

The breadcrumbs popup disappears and you see "no elements found" and the filter on type popup floating over the editor

**Comment by joaomoreno** [comment]
@jrieken I can fire the `onDidChangeContentHeight` event in this case. I can take this.
