### ISSUE TITLE
"Filter" not persisted in breadcrumbs

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#68882]
- Open breadcrumbs
- Type a search query, enable "Filter on type"
- Close breadcrumbs
- Open again and type something
- "Filter on type" mode is disabled, but it should remember my preference like other trees do.

**Comment by jrieken** [comment]
@joaomoreno Is there some automatic trick to make the tree remember this?

**Comment by joaomoreno** [comment]
@jrieken I assume you're disposing the tree when closing breadcrumbs. We can consider putting this into the tree's view state, but are you saving/restoring view state in breadcrumbs at all?

The other solution: the tree exposes the `filterOnType` boolean property and accepts it in the ctor options or in an `updateOptions` call. The tree's owner can save and restore that value.

**Comment by jrieken** [comment]
I do nothing but I was hoping/asking that the use of the workspace-tree-wrapper does that...

**Comment by joaomoreno** [comment]
@jrieken But the workspace-tree-wrapper is a subclass of tree. It also gets disposed, right?

**Comment by jrieken** [comment]
> having the ctor callers pick those ids and use them to store mementos or smth.

Yeah, that was my naive assumption but I see that it lacks ids et all. I can make a breadcrumb change to persist the state
