### ISSUE TITLE
January Update : Color error or different or changed

### ISSUE THREAD

**Issue by taufiqshamad** [Microsoft/vscode#68893]
Issue Type: <b>Bug</b>

I don't know why, but after upgrading to the latest version of visual studio code, my code window has changed it's color look, and i think it is a color compression or somewhat that the browser engine does and it looks bad, it breaks my color scheme and changed the color of image preview

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.16.1-041601-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.73GB (1.51GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
java-debug|DSn|0.0.2
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|0.8.8
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-power-mode|hoo|2.2.0
vscode-colorize|kam|0.8.6
laravel-blade|one|1.18.0
java|red|0.38.0
LiveServer|rit|5.5.1
bunker|sld|1.1.6
ayu|tea|0.18.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.5.0
vscode-java-test|vsc|0.14.0
vscode-maven|vsc|0.14.2

(16 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by bpasero** [comment]
Make sure to let it update once to latest.

**Comment by josecrmrz** [comment]
> We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
> * Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)


I also see the color seems washed out on Windows 10. I'm just using the default Dark+(default dark) theme. I tried both user and system installs and they're both washed out. The exploration download provided here is way better.

**Comment by bpasero** [comment]
OP?

**Comment by josecrmrz** [comment]
After looking some more. [This fixed the issue](url) for me

**Comment by taufiqshamad** [comment]
> After looking some more. [This fixed the issue](https://github.com/Microsoft/vscode/issues/51791#issuecomment-397527146) for me

Oh, Thanks. It fixed mine too, thank you @bpasero @josecrmrz
