### ISSUE TITLE
After upgrade to 1.31, HTML features no longer work

### ISSUE THREAD

**Issue by English3000** [Microsoft/vscode#68891]
Issue Type: <b>Bug</b>

For example, `p` doesn't prompt IntelliSense for a paragraph tag anymore.

Additionally, pressing enter between two tags doesn't create an extra newline with a tab, and I can't comment out a line with `ctrl + /`

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-add-brackets|ali|0.7.0
vscode-hex-pm-intellisense|ben|0.2.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
elixir-ls|Jak|0.2.24
atom-keybindings|ms-|3.0.6
node-debug2|ms-|1.31.6
ruby|reb|0.21.1
vscode-icons|rob|8.2.0
code-settings-sync|Sha|3.2.5
vscode-eex-snippets|ste|0.0.3
vscode-react-redux-snippets|tha|0.3.3
vscode-react-native|vsm|0.8.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by sanket-bhalerao** [comment]
intellisense is also failing for typescript as well.

**Comment by octref** [comment]
Does this reproduce with `code --disable-extensions`?

If so, what's the output from Help -> Toggle Developer Tools and from Output -> HTML Language Server?

**Comment by English3000** [comment]
Help -> Toggle Developer Tools
![image](https://user-images.githubusercontent.com/29601050/53145272-69cbce00-3554-11e9-82b4-0371ca6703de.png)

**Comment by octref** [comment]
Can you give sample code (language and content) that shows the problem? Or take a recording https://support.apple.com/en-us/HT208721 and upload it here.

**Comment by English3000** [comment]
I tried switching back to the previous version... and had the same issue.

I think what happened is the `html-snippets` extension [was disabled](https://github.com/abusaidm/html-snippets/blob/master/snippets/snippets.json) when the new release came out.

I think this issue--

> Additionally, pressing enter between two tags doesn't create an extra newline with a tab, and I can't comment out a line with ctrl + /

--probably just wasn't there from the get-go. I've just recently switched to VSCode and it just happened that my first time working with an HTML file was when the `html-snippets` was disabled!

---
That said, I notice for React files, a tab is auto-added if I hit enter when between an opening and closing tag. I guess I can take a look at the extensions, but if this is something that can easily be added in `setting.json`, I'd appreciate the hint. 

Additionally, I notice that if I put JavaScript in a `<script>` tag in an `.html` file, I don't get the editor features I would in a `.js` file. So same story if you know any good extensions for that.

Thanks!

**Comment by English3000** [comment]
> Follow-up

[Now I got it working!](https://elixirforum.com/t/visual-studio-code-html-eex-support/12712/9)

Added to `settings.json`:

```json
"emmet.includeLanguages": {
    "HTML (Eex)": "html"
}
```

So VSCode wasn't recognizing the `.html.eex` extension
