### ISSUE TITLE
Always Consuming 20% of CPU on Windows

### ISSUE THREAD

**Issue by blurHY** [Microsoft/vscode#68895]
- VSCode Version: 1.32.0
- OS Version: win10

Steps to Reproduce:

1. Install some extensions
2. Open vscode

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/33171396/52931429-44d63000-3387-11e9-82ab-1fd65083aed9.png)

![image](https://user-images.githubusercontent.com/33171396/52931569-d5ad0b80-3387-11e9-9f55-860f5bdf3a9d.png)

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by blurHY** [comment]
[CPU-20190218T070742.368Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2874371/CPU-20190218T070742.368Z.cpuprofile.txt)

**Comment by bpasero** [comment]
@blurHY sorry I actually meant to say this:

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!

**Comment by blurHY** [comment]
```
PS C:\Users\blurHY> start "C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --status
PS C:\Users\blurHY>

Version:          Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.89GB (9.02GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       73   15492  code-insiders main
    0       84   10488     gpu-process
    0      220   13388     window (SettingsLoader.js - HorizonSpider - Visual Studio Code - Insiders)
    0       34    7048       searchService
    0       12   11048       electron-crash-reporter
    0       11   12320       watcherService
    0       10    8492         console-window-host (Windows internal process)
   13      292   16996       extensionHost
    0       65    1948         electron_node tsserver.js
    0       44   17124           electron_node typingsInstaller.js typesMap.js
    0       60    2684         electron_node server.js
    0       31   16000         electron_node eslintServer.js
    0       87   16896     shared-process

Workspace Stats:
|  Window (SettingsLoader.js - HorizonSpider - Visual Studio Code - Insiders)
|    Folder (HorizonSpider): 20 files
|      File types: js(12) json(2) babelrc(1) env(1) gitignore(1) tmp(1) md(1)
|                  lock(1)
|      Conf files: package.json(1)
```

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

**Comment by blurHY** [comment]
> Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Then please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to track down which extension is causing the performance issue, and report the issue against them
