### ISSUE TITLE
Information for each extension in process explorer of vscode

### ISSUE THREAD

**Issue by blurHY** [microsoft/vscode#68897]
Some extension may cause high CPU usage. But process explore shows:

![image](https://user-images.githubusercontent.com/33171396/52931658-1f95f180-3388-11e9-93a5-cfa12d5fe0df.png)

It's unable to know which extension caused this

**Comment by blurHY** [comment]
#68895

**Comment by Yzrsah** [comment]
This feature request is one of the most important features you could request, its importance cannot be underestimated.

In the mean time,

**Steps to resolve Extension CPU Usage issues:**
1) Resolve Errors
- Open the workspace
- command `Developer: Toggle Developer Tools`
- command `Reload Window`
- VSCode will reload with Developer Tools open at extension load time - this will show all extension errors
- Open *Console* tab
- Go through, and resolve all errors
- Extensions with high CPU usage tend to produce errors
2) Reduce Source Complexity
- Search in VSCode Settings for 'exclude' and 'ignore'
- Many extensions need exclude globs added manually
- Add exclude globs and ignores for all of your third party and source-heavy folders that may cause extension processing, such as node_modules and build directories

**Comment by Yzrsah** [comment]
This feature request is one of the most important features you could request.
Its importance cannot be underestimated.

In the mean time,

**Steps to resolve Extension CPU Usage issues:**
1) Resolve Errors
- Open the workspace
- command `Developer: Toggle Developer Tools`
- command `Reload Window`
- VSCode will reload with Developer Tools open at extension load time - this will show all extension errors
- Open *Console* tab
- Go through, and resolve all errors
- Extensions with high CPU usage tend to produce errors
2) Reduce Source Complexity
- Search in VSCode Settings for 'exclude' and 'ignore'
- Many extensions need exclude globs added manually
- Add exclude globs and ignores for all of your third party and source-heavy folders that may cause extension processing, such as node_modules and build directories

**Comment by Yzrsah** [comment]
This feature request is one of the most important features you could request.
Its importance cannot be underestimated.

In the mean time,

**Steps to resolve Extension CPU Usage issues:**
1) Resolve Errors
- Open the workspace
- command `Developer: Toggle Developer Tools`
- command `Reload Window`
- VSCode will reload with Developer Tools open at extension load time - this will show all extension errors
- Open *Console* tab
- Go through, and resolve all errors
- Extensions with high CPU usage tend to produce errors
2) Reduce Source Complexity
- Search in VSCode Settings for 'exclude' and 'ignore'
- Many extensions need exclude globs added manually
- Add exclude globs and ignores for all of your third party and source-heavy directories that may cause extension processing, such as node_modules and build directories

**Comment by Yzrsah** [comment]
This feature request is one of the most important features you could request.
Its importance cannot be underestimated.

In the mean time,

**Steps to resolve Extension CPU Usage issues:**
1) Resolve Errors
- Open the workspace
- command `Developer: Toggle Developer Tools`
- command `Reload Window`
- VSCode will reload with Developer Tools open at extension load time - this will show all extension errors
- Open *Console* tab
- Go through, and resolve all errors
- Extensions with high CPU usage tend to produce errors
2) Reduce Source Complexity
- Search in VSCode Settings for 'exclude' and 'ignore'
- Many extensions need exclude globs added manually
- Add exclude globs and ignores for all of your third party and source-heavy directories that may cause extension processing, such as node_modules and build directories
3) Rebuild your Setup
- Disable all extensions and start fresh
- Re-enable known-good extensions
- Watch CPU consumption each time you re-enable a set of extensions
