### ISSUE TITLE
auto surround selected word with quotes stopped working for php

### ISSUE THREAD

**Issue by ChazyTheBest** [Microsoft/vscode#6889]
- VSCode Version: 1.1.1
- OS Version: Manjaro 16.06 (rc1)

I don't know what happened but yesterday I was writing some code and when I selected a word and pressed ' the word was quoted, now the word is replaced by one ' instead.

Brackets are still auto closing though...

If I change the language mode from php to another, like c++, then it'll work but if I change it back it won't...

If I rename my settings file (the one inside .vscode) and I restart vscode then it'll work, but if I restart again it won't. Strange behavior... I can reproduce this (renaming and restarting).

These are my settings:

```json
{
    "editor.detectIndentation": false,
    "editor.wrappingColumn": -1,
    "editor.renderWhitespace": true,
    "emmet.triggerExpansionOnTab": false,
    "css.lint.compatibleVendorPrefixes": "warning",
    "css.lint.duplicateProperties": "warning",
    "css.lint.universalSelector": "warning",
    "css.lint.zeroUnits": "warning"
}

**Comment by aeschli** [comment]
@ChazyTheBest Did you install any PHP related extensions?
You can try to run VS Code without extensions with `code --disable-extensions`

Surrounding with quotes is disabled in PHP comments and strings. Is that maybe what you see?

**Comment by ChazyTheBest** [comment]
I'm not sure that feature is disabled for comments and strings for php at all, I can surround any selected text, when VS Code wants to ofc.

Do you need visual proof? I could make a video or gif, I can surround any selected text with quotes.

But the problem still remains, when I close and open VS Code again the feature stops working completely with php.

**Comment by aeschli** [comment]
A screenshot or animated gif would would be great. I have no clue so far what it could be. I tried to reproduce what you are seeing, but for me surrounding with quotes works for me in PHP.

**Comment by ChazyTheBest** [comment]
I also have no clue why is it acting like that. It's like "now I want to work, but the next time I start... who knows"? :P

I'm creating the gif file.

**Comment by ChazyTheBest** [comment]
The following gif demonstrates that, sometimes, autoclosing quotes doesn't work for PHP. I also noticed that it became less frequent, only 1 out of 10 times it fails. Yesterday was just the opposite...

![out](https://cloud.githubusercontent.com/assets/654229/15620273/9cbe12d2-2459-11e6-8017-e9da82837298.gif)

**Comment by aeschli** [comment]
@ChazyTheBest Thanks a lot, now I see it too.

The problem was the merging of the settings in php.configuration.ts and the settings is code.
It was a timing issue, depending on what came first, the results from the file or from the extension.

**Comment by ChazyTheBest** [comment]
You're welcome, I'm glad I could help.
