### ISSUE TITLE
git.inputValidationSubjectLength should default to 50

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#68894]
The widely accepted standard for Git commits is the 50/75 rule, in which the subject line is 50 characters, followed by a blank line, followed by 75 character or less lines. VSCode is great at handling this with its warning about line limits in the commit message box, but the `git.inputValidationSubjectLength` defaults to inheriting from `git.inputValidationLength`, which doesn't make much sense. GitHub truncates subject lines that are 75 character, and in general that's just not the accepted standard. Therefore, the default value should be the standard `50`.

**Comment by scottclayton** [comment]
In 2016 VS Code had it set to 50 for the validation, but I think it got bumped up to 72 in 2017 at some point. There was much discussion on it in various threads—e.g. #21144, #31322, #18807, #2718. Eventually I changed my tune and said, "meh… 72 is fine… I only look at commits in my cli or github anyway" and just lived with 72.

I was quite astonished when I committed last night and realized in the new release the length got bumped back down to 50. After having done a length of 72 for the last year or so, it's hard to go back. In case anyone else reads this, modifying this setting will restore it as it was prior to the new release this week: `"git.inputValidationSubjectLength": 72`
