### ISSUE TITLE
VSCode crashes regularly since update to 1.31.1

### ISSUE THREAD

**Issue by robmandoe** [Microsoft/vscode#68890]
Issue Type: <b>Bug</b>

Reproducing can only be done by using it for a few hours with multiple terminals open while editing and running an Angular app. After a while the terminal freezes up and usually goes blank, and then VSCode crashes. Happens continuously since the last update.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (9.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
tslint|eg2|1.0.43
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
debugger-for-chrome|msj|4.11.2
vscode-css-peek|pra|2.2.0
move-ts|str|1.11.3

</details>

**Comment by jfly28** [comment]
For what it's worth same experience as well.  at first it lost all my settings kept restarting and they came back.

VS Code version: Code 1.131.1
1b8e830, 2019-02-12T02:10:22.500Z
OS version: macOS Sierra 10.12

**Comment by TheryFouchter** [comment]
Same, I have this error regularly when I split my terminal.

**Comment by robmandoe** [comment]
Yes it may be a split terminal problem. I stopped splitting my terminal and it hasn't crashed for a few days

**Comment by robmandoe** [comment]
Actually no. She just crashed again without using split terminals.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/68721
