### ISSUE TITLE
terminal prompt doesnt work under windows

### ISSUE THREAD

**Issue by ravi005e** [Microsoft/vscode#68892]
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

launch vscodde on windows
click on terminal tab

you will see prompt is not there to typein

**Comment by Frankzhaopku** [comment]
Quite curious why @vscodebot assigned this issue to @Tyriar automatically.

**Comment by yume-chan** [comment]
> Quite curious why @vscodebot assigned this issue to @Tyriar automatically.

@Frankzhaopku because @Tyriar is the main maintainer of xterm.js which powers the integrated terminal in Code.

**Comment by Frankzhaopku** [comment]
> @Frankzhaopku because @Tyriar is the main maintainer of xterm.js which powers the integrated terminal in Code.

But where does this configured? Or the configure is not open sourced?

**Comment by yume-chan** [comment]
> But where does this configured? Or the configure is not open sourced?

@Frankzhaopku configuration is in this repository, but the bot itself is not open sourced
 https://github.com/Microsoft/vscode/blob/8755bcf0d350dc78f90ae3f3ae7a5470cfa3d9ef/.github/classifier.yml#L84

**Comment by Frankzhaopku** [comment]
> @Frankzhaopku configuration is in this repository, but the bot itself is not open sourced
> [vscode/.github/classifier.yml](https://github.com/Microsoft/vscode/blob/8755bcf0d350dc78f90ae3f3ae7a5470cfa3d9ef/.github/classifier.yml#L84)
> 
> Line 84 in [8755bcf](/Microsoft/vscode/commit/8755bcf0d350dc78f90ae3f3ae7a5470cfa3d9ef)
> 
>  integrated-terminal: [ Tyriar ],

@yume-chan got it, thanks very much.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
