### ISSUE TITLE
Incorrect type warning on object parameters of type { [key: string]: any; }

### ISSUE THREAD

**Issue by andyhall** [Microsoft/vscode#689]
This issue occurs when coding with a definition file that declares a function which takes a parameter object with properties like:

```ts
// in d.ts file:
propertyName?: { [key: string]: any; };
```

When passing this parameter as a plain object, VScode is happy:

```js
// from javascript - no warning
functionCall({
    propertyName: { foo: "bar" }
})
```

But I get a warning when doing the same thing thusly:

```js
// from javascript - VScode shows warning
var obj = { foo: "bar" };
functionCall({
    propertyName: obj
})
```

The warning is: 

> Types of property 'propertyName' are incompatible. Type '{ foo: string; }' is not assignable to type '{ [key: string]: any; }'.

To reproduce, try putting [ractive.d.ts](https://github.com/codler/Ractive-TypeScript-Definition/blob/master/RactiveTypeScriptDefinition/ractive.d.ts) into a project, and then enter code like this:

```js
// ok:
var a = new Ractive({
	partials: {foo: 'bar'}
});

// ng:
var obj = {foo: 'bar'};
var b = new Ractive({
	partials: obj
});
```

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
