### ISSUE TITLE
RTL when arabic text

### ISSUE THREAD

**Issue by TaymoorAbdeen** [Microsoft/vscode#68901]
Issue Type: <b>Feature Request</b>

it's very imprtant if is here RTL when arabic text

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment]
Duplicate of #11770
