### ISSUE TITLE
Find in folder

### ISSUE THREAD

**Issue by odelvalle** [Microsoft/vscode#68905]
Issue Type: <b>Bug</b>

Find in folder fail to detect "files to include"

Result in "files to include" using context menu from a workspace subfolder (api-v2 is a root folder)
```
./api-v2/function(e,t){if(e.scheme===t.scheme&&d(e.authority,t.authority)){if(e.scheme===r.Schemas.file){const s=n.relative(e.path,t.path);return a.isWindows?i.toSlashes(s):s}return n.posix.relative(e.path||"/",t.path||"/")}}
```

VS Code version: Code - Insiders 1.32.0-insider (4e68ba25fbc752e3d7da488b8d3db374029577d6, 2019-02-18T06:18:01.607Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
beautify|Hoo|1.4.9
workspacesort|ici|1.5.0
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
python|ms-|2019.1.0
vscode-docker|Pet|0.5.2
code-settings-sync|Sha|3.2.5

</details>

**Comment by samuela** [comment]
I just came across the exact same issue and was about to file this bug report:

## "Find in Folder" sets "files to include" to some javascript mess




- VSCode Version: Version 1.32.0-insider (1.32.0-insider) a75cf6e4b4317de0bf38284af255bdf0089deb68
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Go to a folder in the file explorer.
2. Right click and select "Find in Folder"
3. Observe that the "files to include" text box includes something like
```
./nuvemfs/function(e,t){if(e.scheme===t.scheme&&d(e.authority,t.authority)){if(e.scheme===r.Schemas.file){const s=n.relative(e.path,t.path);return a.isWindows?i.toSlashes(s):s}return n.posix.relative(e.path||"/",t.path||"/")}}
```


Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
#68966
