### ISSUE TITLE
Created folder won't appear until the tree view is manually reloaded

### ISSUE THREAD

**Issue by nchanged** [Microsoft/vscode#68902]
Issue Type: <b>Bug</b>

Created folder won't appear until the tree view is manually reloaded. It happens at random, and I can't give you the exact steps to reproduce it.  

Looks like `1.31.1` tree view is broken, there are so many issues with it.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-tabs|Tyr|0.2.0
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
shaderlabvscodefree|aml|1.1.3
Handlebars|and|0.4.1
vscode-color|ans|0.4.5
indent4to2|Com|0.1.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.8.1
live-html-previewer|hdg|0.3.0
github-pr|jas|1.0.0
docthis|joe|0.7.1
docomment|k--|0.1.3
vs-color-picker|lih|1.0.0
vue|liu|0.1.5
share|lyu|0.4.4
python|ms-|2019.1.0
debugger-for-chrome|msj|4.11.2
vscode-code-outline|pat|0.2.1
vscode-icons|rob|8.2.0
code-settings-sync|Sha|3.2.5
trailing-spaces|sha|0.2.11
shader|sle|1.1.4
addDocComments|ste|0.0.8
launchterminal|tes|0.4.0
gitblame|wad|2.6.3

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
