### ISSUE TITLE
Terminal Line-height problems (like #36599 & #13230) are occurring again.

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#68909]
- VSCode Version: 1.31.1
- OS Version: OS X 12.2

Thanks a lot for your awesome job as always.

Some special characters like &#x2724; are not rendered with the right line height within the new release

<img width="399" alt="screen shot 1397-11-29 at 1 14 40 pm" src="https://user-images.githubusercontent.com/2157285/52942160-aeead700-337f-11e9-8eff-e952f6cf75d2.png">

And also the cursor on active mode gets the line heights wrong:

<img width="192" alt="screen shot 1397-11-29 at 1 18 55 pm" src="https://user-images.githubusercontent.com/2157285/52942258-e6598380-337f-11e9-8030-dd843ceba47d.png">

This is similar to #36599 & #13230

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/68045, should be fixed in insiders
