### ISSUE TITLE
Screencast mode shows multiple words "Escape"

### ISSUE THREAD

**Issue by rafaelfilholm** [Microsoft/vscode#68916]
When you repeatedly enter the "esc" key, multiple "Escape" words are inserted on the screen, forming a huge chain, coming to "exit" the screen, and from display area of ​​the commands.

- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:

1. Open vscode
2. Enable screencast mode (ctrl+shift+p -> Toggle screencast mode)
3. Press the "esc" key several times

Does this issue occur when all extensions are disabled?: Yes

Screenshot:

![Screenshot of bug](https://snag.gy/gxrJPL.jpg "Screenshot of bug")

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/68849
