### ISSUE TITLE
PowerShell syntax highlighting issues for dot notation.

### ISSUE THREAD

**Issue by cblackuk** [Microsoft/vscode#68910]
- VSCode Version: >1.27.2
- OS Version: Win10, 2016, 2019 - does not matter

Steps to Reproduce:

On VSC with no extensions 1.27.2
![image](https://user-images.githubusercontent.com/28607803/52943793-d3d25080-3365-11e9-99cb-37f93e2398bd.png)

On VSC with no extensions >1.27.2
![image](https://user-images.githubusercontent.com/28607803/52943898-0e3bed80-3366-11e9-8951-157a930b5c1a.png)

The code after "." should be in different colour.

This used to work but no longer does. Not only for PowerShell but Python too. I am a bit perplexed as to why that is.

PowerShell extensions even in Preview make no difference - this is definitely a VSC issue.

Why was this changed and is it a bug?

**Comment by alexr00** [comment]
This issue was moved to PowerShell/EditorSyntax#160
