### ISSUE TITLE
when trying to create branch - nothing happens

### ISSUE THREAD

**Issue by shootermv** [Microsoft/vscode#68918]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. click git icon at left bottom
2. choose "new branch" at dropdown on the top
3. type new branch name and press "enter"
4. Nothing happens (no branch is created)
5. Only after typing the branch name again and pressing enter - the new branch finally created

Expected Behavior:
New branch should create after enter pressed (s it was in previous versions)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_1331525|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0
vscode-docker|Pet|0.5.2

</details>

**Comment by xblitz** [comment]
I also have the same issue

**Comment by joaomoreno** [comment]
@shootermv @xblitz Can you show me a screen recording?

**Comment by shootermv** [comment]
![vscode-brnach-bug](https://user-images.githubusercontent.com/1336862/53088373-31a39b80-3512-11e9-8e30-7652f1a1e662.gif)

**Comment by xblitz** [comment]
Ahh it seems the git create branch workflow has changed recently,   when you enter the new branch name,  it ask you to *pick* a ref branch instead of just using the one you are currently on. but the box appear exactly like the one before so it *looks* like it didn't work...  

so yeah, this is confusing a bit.   can this become a setting where we can set it to ref  the current checked out branch so it behaves like it did before?

**Comment by joaomoreno** [comment]
Yeah, great insight.

**Comment by earlkrygier** [comment]
I noticed the same issue. Spent a few hours trying figure out if it was a permissions issue or I was doing something wrong. The option "+Create new branch" in the dropdown indicates to me that I'm creating a new branch. But that is not the behavior. After typing in the name of my new branch and hitting Enter, nothing happens. Kind of frustrating.

**Comment by joaomoreno** [comment]
@earlkrygier @xblitz @shootermv Addressed in https://github.com/Microsoft/vscode/issues/70812
