### ISSUE TITLE
Debug 'attach' doesn't work if execution is too fast (--inspect-brk is ok)

### ISSUE THREAD

**Issue by icetbr** [Microsoft/vscode#68915]
This is a very minor issue, but I cracked my head around this one. Is this expected?

Steps to reproduce:
1) create test.js
2) add any code
3) put a breakpoint on it
4) create a launch 'attach' configuration or turn on auto attach
5) `node --inspect test.js`

Workarounds
- use `--inspect-brk`. This isn't perfect because when calling `node lab`, the first line isn't my code
- put a `debugger;` statement
- use a lengthy operation, like a loop 100k times. Eventually it attaches.
- don't use attach. It's what I'm using, and its OK. It has some limitations invoking my npm scripts (nodemon + lab issues)

I saw a request in node.js to allow to specify which file --inspect-break would first stop. The devs suggested this is a feature better left for "client land".

If this is expected, maybe add something to the "My breakpoints aren't working" FAQ.

**Comment by weinand** [comment]
Yes, the behavior you are seeing is expected. The "auto attach" polls for newly spawned processes only 2 times per second. So if your process has already terminated, "auto attach" will not even see it.
Node's "--inspect-brk" only exists for exactly this problem: if you need to debug startup code, "--inspect-brk" stops the target program until a debugger has attached to it (and has successfully registered all early breakpoints).
