### ISSUE TITLE
Recent files created doesn't show in folder  #68204 persists

### ISSUE THREAD

**Issue by ctfrancia** [Microsoft/vscode#68914]
- VSCode Version: 1.31.1 
- OS Version: Mojave 10.14

Steps to Reproduce:

1. go to folder
2. click "add new file"
3. "name file"
4. Shown in the Explorer "Open Editors" but not the tree underneath
5. only shown after restarting VS code.
6. checked for updates.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of #68204
