### ISSUE TITLE
Allow to navigate to symbols globally within a file

### ISSUE THREAD

**Issue by guifelix** [microsoft/vscode#68919]
I would like to navigate through files more like sublime, for example:

let's suppose I have a file called "_SomeController.php_" and inside this file, I have a method called "_someMethod_". Even if I have no opened file in the editor I can open the file navigator with "_ctrl+p_" command and type "_somecon@someme_" and the navigator can find the file and the method and open the file with the cursor selecting the name of the desired method.

![screenshot from 2019-02-18 10-06-28](https://user-images.githubusercontent.com/12631274/52953002-00d23380-3365-11e9-8a39-31fe87ca3e69.png)
(Image from sublime)

Currently, if I do this same process in _vscode_, the file navigator does find the selected file if I had typed "_somecon_", but when I try to insert the symbol "_someme_" it fails to find the file and the method. Even if I type the whole filename and the symbol (eg: "_SomeController.php@someMethod_") the editor cant find the file/method.

![screenshot from 2019-02-18 10-08-07](https://user-images.githubusercontent.com/12631274/52953082-35de8600-3365-11e9-9bfe-598aaeea1aa5.png)
(image from vscode)

**Comment by bpasero** [comment]
@guifelix try with Ctrl+T for "Open Symbol"?

**Comment by guifelix** [comment]
same result for the syntax "somecon#someme":
![screenshot from 2019-02-18 11-08-47](https://user-images.githubusercontent.com/12631274/52956387-d173f480-336d-11e9-8aed-b4f985c3ca07.png)

if I just type "#someme" it finds the method, but it's not the desired result. In sublime editor it looks for the method only inside the specific file, otherwise it happens to find duplicate methods throughout the project as the picture shows:

![screenshot from 2019-02-18 11-10-27](https://user-images.githubusercontent.com/12631274/52956508-1bf57100-336e-11e9-85d4-3d0dcbdee1ae.png)

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/78920
