### ISSUE TITLE
Execute specific test

### ISSUE THREAD

**Issue by peni4142** [Microsoft/vscode#68920]
I have the problem, that I have already many tests. Some are async and take up to 2 seconds. Doesn't sound that many time yet, but I have more than 150 tests. Waiting while developing for all tests is very hard.
Would be nice if I could have a parameter for the name of the test-file or something like that.

I using something like that for my UI-tests where some of them taking up to 2 minutes:

```
glob("./out/**/**.test.js", { cwd: uiTestFolder }, function (error, files) {
    if (error) {
        throw error;
    }
        if (!specificTest) {
            files.forEach(function (f) { return mocha.addFile(join(uiTestFolder, f)); });
        } else {
            files.forEach(function (f) {
                if (f.includes(specificTest + ".test")) {
                    return mocha.addFile(join(uiTestFolder, f));
                }
            });
        }
        mocha.run();
});
```

I hope the code make clear what I am looking for.

**Comment by alexr00** [comment]
If you are using tasks to run your tests you can solve this with input variables. https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by peni4142** [comment]
I think I know what you meant, but that didn't work out for me.
But I used launch.json, I have no experience with tasks yet.
Maybe I try that later.
```
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}/ext",
                "--extensionTestsPath=${fileDirname}"
            ],
            "outFiles": [
                "${workspaceFolder}/ext/out/**/*.js"
            ],
        },
```
I think the problem is some test helper functions are outside of the directory `${fileDirname}`
