### ISSUE TITLE
SCM view size lost

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#68924]
Issue Type: <b>Bug</b>

When switching viewlets:
![feb-18-2019 15-36-44](https://user-images.githubusercontent.com/9205389/52958037-810f8d80-3393-11e9-86d0-01a22bc59ba0.gif)

VS Code version: Code - Insiders 1.32.0-insider (bbe40c8cb0901c439b3b61221a0197fb6723783e, 2019-02-18T10:48:16.325Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_14990923|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
vscode-eslint|dba|1.8.0
Spot|der|0.4.0
ghlink|dt|1.0.2
remotehub|eam|0.2.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.4.0
rest-client|hum|0.21.1
solidity|Jua|0.0.49
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.13.0
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.14.0
vscode-cosmosdb|ms-|0.10.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
cpptools|ms-|0.21.0
github-issues-prs|ms-|0.9.1
debugger-for-chrome|msj|4.11.2
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.12.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.1.3
azure-iot-toolkit|vsc|2.2.0

</details>

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/49054
