### ISSUE TITLE
Tooltip remanence glitch

### ISSUE THREAD

**Issue by lepinekong** [Microsoft/vscode#68922]
- VSCode Version: all
- OS Version: Windows 10

Steps to Reproduce:

1. switch from VSCode to another application
2. sometimes if not often vscode tooltip still shows up out of vscode
[](https://i.imgur.com/RCaZ0Es.png)

Does this issue occur when all extensions are disabled?: [Yes]

**Comment by Tyriar** [comment]
Which tooltip? Can you provide a screenshot?
