### ISSUE TITLE
Git: Add remote 

### ISSUE THREAD

**Issue by adityasovani** [Microsoft/vscode#68925]
Issue Type: <b>Feature Request</b>

Provide option to add Git remote from VSCode console. For configuring remote we have to use command prompt.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.10240

**Comment by KexyBiscuit** [comment]
Dup of #21189

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/21189
