### ISSUE TITLE
Inconsistent highlighting for certain C++ function names

### ISSUE THREAD

**Issue by EmbersArc** [Microsoft/vscode#68926]
The first few letters are highlighted in a different color for the following function names in C++:

- iterate()
- riterate()
- enumerate()

![picture](https://i.imgur.com/JtNx9QW.png)

Issue might be from [here](https://github.com/Microsoft/vscode/blob/master/extensions/cpp/syntaxes/cpp.tmLanguage.json#L157).

- VSCode Version: 1.31.1
- OS Version: Linux x64 4.4.0-142-generic

Steps to Reproduce:

1. Create new `.cpp` file.
2. Write a function call with any of the following names: `iterate`, `riterate`, `enumerate`.
3. The first letters are in a different color than the rest of the word.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Looks like this is fixed as part of #68392.
