### ISSUE TITLE
Test: Reverting the default titlebar setting on Linux

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#68933]
- [x] Linux @bpasero 
- [x] Linux @aeschli

Complexity: 2

Verify that:
* the default setting for Linux is once again the native title bar. 
* you can switch between settings successfully.
* the notification explaining the change shows and works correctly:
  * for existing users only
  * who have not configured the title bar manually
  * using the native title bar currently
* the notification only shows once

Refs: #68640

**Comment by bpasero** [comment]
Seems to work fine. Even though i would probably remove the "Do not show again" button because my understanding is you take care of never showing it again.
