### ISSUE TITLE
Cannot close editor with too long file name

### ISSUE THREAD

**Issue by Oceanedge** [Microsoft/vscode#68937]
I was using vscode 1.31.1 on Ubuntu 18.04.2 LTS. While I was testing my script which output a long string, for unknown reason, Ubuntu launch code to open that long string as a file. When I try to close that editor on vscode, it shows a dialog with error: A system error occurred (ENAMETOOLONG: name too long, open '/home/user/LS0tLS1CRUdJTiBQU...  and refused to close that dialog.
After I restart vscode, that editor always there and I can't close it.
This block me from using vscode. Please help. Thanks!

**Comment by bpasero** [comment]
@Oceanedge can you paste the filename here?

**Comment by Oceanedge** [comment]
The filename is just the content of base64 formated a X.509 certificate in PEM format. The length is 4219, and you don't need to use mine but use any string with that length could reproduce this issue.
Well, I just found a workaround. I just right click on that editor and select "Save as", change the filename in short string, after save, I can close that editor.

**Comment by bpasero** [comment]
@Oceanedge can I ask what exactly happens? Here is what I see:
* I open Code on a random file name that has > 4000 characters
* the file opens as dirty empty file (because it does not exist)
* I close the file
* a dialog seems to appear but does not show anything, possibly because the dialog is too large
* I am not seeing the `ENAMETOOLONG` error

Do you see a proper dialog? When do you see the error?

**Comment by Oceanedge** [comment]
Right, what you see is what happens if I tried to close on editor. Instead I don't see a dialog, but the main window blured, which means there should be a dialog in front but it wasn't shown. Then I press Enter, and the main window returns.
The  `ENAMETOOLONG` error is shown when there are multiple editor opened with too long filename, in my case there are 4. And after I click close all button on the top right side of opened editor list sub window, the  `ENAMETOOLONG` error is shown.

**Comment by bpasero** [comment]
I pushed a change to treat filenames (basename) of >255 length as invalid on all platforms. That seems to be unsupported in most typical file systems.

**Comment by Oceanedge** [comment]
Thank you very much!

**Comment by sbatten** [comment]
@bpasero there is no notification that this is why the "file" isn't opening?

**Comment by bpasero** [comment]
Yeah, we never had a notification if you open an invalid name. I do not understand how this is a "verification-found"?

**Comment by bpasero** [comment]
Opened https://github.com/Microsoft/vscode/issues/69507
