### ISSUE TITLE
VS code not using conda environment when running pylint

### ISSUE THREAD

**Issue by alexespencer** [Microsoft/vscode#68931]
Issue Type: <b>Bug</b>
<b>Steps to reproduce:</b>
Create a blank workspace, setup a conda environment with python, pylint, numpy and afterwards install opencv-python. Create a .pylintrc file and add cv2 as a whitelisted package.

Select the conda environment as the python interpreter. Run linting - it will IGNORE the .pylintrc file.

Now, use command prompt to activate the conda environment and then launch VS code from here with "code" - everything works as expected.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
sshextension|kon|0.5.0
sftp|lix|1.9.3
vscode-kubernetes-tools|ms-|0.1.16
python|ms-|2019.1.0
azure-account|ms-|0.8.0
vscode-docker|Pet|0.5.2
vscode-yaml|red|0.2.1
code-settings-sync|Sha|3.2.5

</details>

**Comment by alexespencer** [comment]
Should launching VS code via an already activated conda environment give different behaviour to a workspace that has a properly defined conda interpreter?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
