### ISSUE TITLE
Test: Recommend the custom title bar when using accessibility support mode

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#68934]
- [x] Linux @bpasero 
- [x] Windows @egamma

Complexity: 1

Verify that:
* A notification appears when the user launches with or changes the setting to use accessibility support or the user launches with a screen reader and the setting is auto.
* The notification only appears once.

Refs: #68640

**Comment by bpasero** [comment]
Seems to work. The only slightly weird experience is if you had accessibility support enabled ("on") and update to latest you see 2 potentially competing notifications:

![image](https://user-images.githubusercontent.com/900690/53330417-b0238300-38ee-11e9-8c88-ec54368c9042.png)
