### ISSUE TITLE
Add `open in new window` button/option after doing a git clone

### ISSUE THREAD

**Issue by abbychau** [microsoft/vscode#68945]
After doing `git clone`, it will ask if you want to open the repository.
If users try to open, it will use the current windows (and ask if users need to save unsaved documents).

If users cancelled the operation because users want to continue editing, then cloned repository has to be opened manually later(like finish editing or open a new vscode windows manually).

It will make this case better by adding a new button/option that could open cloned repository in a new window.

**Comment by flurmbo** [comment]
Hi, I'm going to try working on this!

**Comment by abbychau** [comment]
@flurmbo thank you. thanks for ur contribution on OGS too.

**Comment by flurmbo** [comment]
thanks @abbychau!

**Comment by abbychau** [comment]
oops.
mine changed the question so to make buttons shorter and displayable without "..." and buttons are also added to `git init` as well.
