### ISSUE TITLE
Alt+Click on Explorer file panel header should collapse all folders

### ISSUE THREAD

**Issue by dutzi** [microsoft/vscode#68943]
Hi all,

I think the behavior should be the same as it is when Alt+Clicking a folder (i.e., it collapses all expanded folders within it).

![image](https://user-images.githubusercontent.com/927310/52977916-d1a8da00-33d7-11e9-8d42-6c8aefa5cefb.png)

So if I Alt+Click on WLA-RN-DOM and then click it again, `android` and `app` folder should be collapsed.

**Comment by dutzi** [comment]
I don't think this is a duplicate #18109 since it's not *adding* a component to the view, it just takes a familiar behavior and applies to other view components.

**Comment by sanmaopep** [comment]
I'm looking forward to this feature too

**Comment by sanmaopep** [comment]
Let me have a try on this, thanks

**Comment by isidorn** [comment]
We will accept a PR only if it is nice and simple. No hacks and workarounds.
