### ISSUE TITLE
Can't use ${env:HOME} or ${workspaceFolder} with markdown.styles setting

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode#68948]
**Feature/Bug**

I'd like to specify `${workspaceFolder}` in the path for `markdown.styles` setting

This would allow to specify a project-specific `markdown.styles` .css

The ${vars} can't be used, so there's no way to configure project markdown styles.

**Comment by mjbvz** [comment]
Duplicate of #2809
