### ISSUE TITLE
How do I use html.format.unformatted for comments?

### ISSUE THREAD

**Issue by pillaiindu** [Microsoft/vscode#68941]
Issue Type: <b>Question</b>
I filed an issue at this repo and also at the formatter's repo which VSCode uses for formatting HTML, months ago.
I wanted my comments on the same line as the closing tag. For Emmet I have the following setting which works fine,
```
"emmet.preferences": {
    "filter.commentAfter": " <!-- /[#ID][.CLASS] -->"
  },

```
but for formatter I didn't find any good solution. I think `html.format.unformatted` may provide a solution for it, but I don't know how may I write this setting?
I don't know if the setting should be `"html.format.unformatted": "comment"` or `"html.format.unformatted": "<!-- -->"` or how?

---

VS Code version: Code 1.31.1
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (2.02GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.8
Bookmarks|ale|10.2.2
vscode-gemfile|bun|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
eppz-code|epp|1.2.41
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
theme-macos-classic|hua|1.1.1
elixir-ls|Jak|0.2.24
theme-dark-plus-contrast|k3a|0.1.101
theme-karyfoundation-themes|kar|18.2.1
edge|luo|0.3.1
vscode-language-babel|mgm|0.0.22
theme-monokai-pro-vscode|mon|1.1.9
Go|ms-|0.9.2
vetur|oct|0.15.1
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.6.3
vscode-css-peek|pra|2.2.0
LiveServer|rit|5.5.1
vscode-icons|rob|8.1.0
elm|sbr|0.25.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.5
slim|sia|0.1.2
code-spell-checker|str|1.6.10
ayu|tea|0.18.0
vscode-status-bar-format-toggle|tom|1.4.0
vim|vsc|1.0.8
vscode-react-native|vsm|0.8.0
JavaScriptSnippets|xab|1.7.2

(79 theme extensions excluded)

</details>

**Comment by octref** [comment]
Unfortunately the included formatter (js-beautify) does not support this. You might enjoy [prettier HTML formatter](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5dqQGYdevak6l8AvmwEAlIZfEgArjABm0gBzaWp-fgAkvjcpAycAJ7kMMF0pKgA9EEhYX6m5pbWAHICFs4AJnDyYABOAJYADjBl0BLkkLAIMM6RfBBZMKRQ+L66+glshsZpqABGEPkRJunEDGxwdHQQ5ADuECV0+eioAEJ2DOT4lGWKJ+QcPACs5DsQZXRwJRV0AIbwAHSJs2lmQrh2gWI+Gm-hWZSg+QgK3eAHMXuRROR3C4oGBqtByAAKACU5GA5Dh7wAju8Ki55JRMS8SjCXDQmvJcQBfADcBJexIR5AA2gBdNmEuhcgDUUDgK3ImDecBZP1McMxAHJSnBpYqADTkRUAVQE0gAGobDdJCBqtS83BBFdiBS8lfIEPkzYqKi8YXAAG5lcXWuWJYrlKog-wYaTScgJbkAYkCmF53Pe-GEQl55DDwdQfwBQPI8hKYGc1BgFXkSASCRWldhEAgMIe0heUBedAi1TA8nekBoCUbzdbZXb7wUdWEhCyuElpAAYqR9v7SpUYNNEuNJjpEhduAwQOqQBAqjUoPJkKBqSUocRqQhjygXh67vkdyBRiUXmAANZwGBCV1gcEw5AYBKFw4F3ah6AAdWOeB5F-OAhGvMpqi9GAImQcB5GPXdwQdEoYGIV8YRoF5kHcZsHV3BQAA8dlfD8vyEF56W4cE4FI8jQJAaihH-B4AEUXAgeB2LoCiQFdEpcPQ8C6CfCpylgCCynyGBKGQLwAAZd3kiAHQg18KnQ+SikeD02N3Eo4CJFwyksgi3WIkSxIdGgykA4DOPkXi4AEoS2KQMjRM4mAXlGJSVLUpAACZdyAl57n-XAIBoRyUCkMUn3JOB8FCm9AodJkmSAA).
