### ISSUE TITLE
Context menu expands under cursor on Linux

### ISSUE THREAD

**Issue by hoehrmann** [Microsoft/vscode#68944]
Issue Type: <b>Bug</b>

I am using Linux Mint 19.1 xfce edition.

When I position the cursor over something and press the »right-click« key on my notebook's touchpad, the context menu quite often expands under the cursor even if I do not move the cursor at all. When I then release the key, the editor performs the action "selected" from the context menu.

But there is no chance to select anything. I would expect that I can position the cursor, press and release the key, and then select an option from the context menu. That sometimes works when the context menu is expanded next to the cursor instead of somewhere under it, but that is not usually the case.

This is after https://github.com/Microsoft/vscode/commit/723ef6123e543bc890ad4b389c409aaaa1bd3fbe I believe, and 1 or 2 pixels probably would not help much either, with a notebook's touchpad it is quite normal that the cursor moves a couple of pixels when performing this action.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.15.0-45-generic

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/65787
