### ISSUE TITLE
Parameter Hints Not Rendering Properly

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#6895]
- VSCode Version: 1.1.1
- OS Version: OSX El Capitan 10.11.4

Steps to Reproduce:

1. Write the code to create a new object

Expected: Intellisense parameter hints show different signatures with available parameter names.

Actual: blank area shows (see screenshot)

![image](https://cloud.githubusercontent.com/assets/16694050/15557436/d408c008-2287-11e6-8756-100f6061a67d.png)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#377
