### ISSUE TITLE
API for switching activities on Activity Bar

### ISSUE THREAD

**Issue by xen22** [Microsoft/vscode#68951]
Extensions can now use the Activity Bar on the left to place their UI in a separate activity tab. However it doesn't seem to be possible to switch the active activity programmatically.

One example that comes to mind is the Test Explorer UI extension, which lists the tests present in the current folder. It would be really great if when I want to run all tests for example, I could simply press the configured hot-key for the corresponding command exposed by the extension and vscode would switch automatically to the "Test" activity. This would improve the UX as it would reduce the number of mouse clicks I have to perform in this case.

**Comment by sandy081** [comment]
The extension can do this already by calling the reveal API on the view. Please file an issue against the extension.

**Comment by xen22** [comment]
Thanks @sandy081, I hadn't realized this was possible already.

**Comment by MrKou47** [comment]
@xen22 so..how to switch to the extension avtivity bar view use keybindings?

**Comment by xen22** [comment]
Ctrl-Shift-X switches to the Extensions view on the sidebar.

**Comment by xen22** [comment]
Unless you meant the activity bar view created by an extension (eg test activity), which is what this issue was about, in which case the extension developer needs to expose a command that does that. The command can then be mapped to a keybinding.

**Comment by MrKou47** [comment]
@xen22 Oh,i got it.So the work of keybinding should be done by extension developers.Thanks
