### ISSUE TITLE
linux: invalid location of .vscode folder

### ISSUE THREAD

**Issue by dibalavs** [Microsoft/vscode#68958]
Currently on my lnux (ubuntu) distributive  I see a garbage in my home folder.
~/.vscode/
But XDG specification requires some fixed locations for different cases:

**$XDG_CONFIG_HOME**  (default $HOME/.config/) for configuration files
**$XDG_DATA_HOME** (default $HOME/.local/share) for user specific files
**$XDG_CACHE_HOME** (default $HOME/.cache) for cache files.
whole list of requirements can be found at:

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Good article, which describes why is it good idea to follow specifications:
https://0x46.net/thoughts/2019/02/01/dotfile-madness/

**Comment by gusbemacbe** [comment]
The `~/.vscode` is not garbage, it is a folder which stores and keeps the extensions. There is already a folder called `Code` in the `~/.config/` which stores backups, caches, cookies, logs, snippets, workspaces and user config

**Comment by dibalavs** [comment]
> The `~/.vscode` is not garbage, it is a folder which stores and keeps the extensions. There is already a folder called `Code` in the `~/.config/` which stores backups, caches, cookies, logs, snippets, workspaces and user config

As I understand  it should be next locations:

**$XDG_DATA_HOME**/vscode - for extensions, logs
**$XDG_CONFIG_HOME** /vscode - for configurations
**$XDG_CACHE_HOME**/vscode - for caches, backups...

**Comment by dibalavs** [comment]
I just checked and found cache location at:
**$XDG_CONFIG_HOME** /Code/Cache*
Looks like it is also incorrect

**Comment by gusbemacbe** [comment]
Here, on my Manjaro Linux, everything worked. 

But if it is important to follow the standard specifications required by GNOME and KDE, let the developers like @bpasero know.

**Comment by dibalavs** [comment]
on my Ubuntu 18.04, locations are different

**Comment by bpasero** [comment]
Add your comments to https://github.com/Microsoft/vscode/issues/3884

**Comment by lsl** [comment]
Workaround until the bug is fixed:

`export VSCODE_EXTENSIONS="${XDG_DATA_HOME:-~/.local/share}/code-oss/extensions"`
