### ISSUE TITLE
Webview shows string 'null' if enableScripts is true

### ISSUE THREAD

**Issue by itowlson** [Microsoft/vscode#68953]
Issue Type: <b>Bug</b>

When I create and reveal a webview with `enableScripts` set to true, it displays `null` at the top left.

Here is a function to create a simple webview:

```
export function createWebview(tabTitle: string): void {
    const html = `<div id='wvcontent__' />HELLO</div>`;

    const w = vscode.window.createWebviewPanel('sample', tabTitle, vscode.ViewColumn.Active, {
        enableScripts: true,
    });

    w.webview.html = html;
    w.reveal();
}
```

When I call this from my extension, I see:

![image](https://user-images.githubusercontent.com/865538/52987517-4162a780-3460-11e9-9156-0974b2996b57.png)

If I change `enableScripts` to `false` and try again, I get the expected view with no 'null':

![image](https://user-images.githubusercontent.com/865538/52987548-648d5700-3460-11e9-9dbe-131d7e81975f.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18332

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.93GB (38.38GB free)|
|Process Argv|--folder-uri file:///d%3A/temp/test-npm-package-k8s-api-helper|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vscode-pull-request-github|Git|0.4.0
terraform|mau|1.3.7
duffle-vscode|ms-|0.0.4
python|ms-|2019.1.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-docker|Pet|0.5.2
vscode-yaml|red|0.3.0

</details>

**Comment by mjbvz** [comment]
Also make sure you are using a full html document for the webview, not just a fragment

**Comment by itowlson** [comment]
@mjbvz Using a full HTML document didn't make a difference in my case, but I'll make the change anyway as it seems safer - thanks for the tip, and for the quick fix!

**Comment by Almenon** [comment]
Also ran into this issue in https://github.com/Almenon/AREPL-vscode/issues - thanks for the fix @mjbvz ! Looking forward to it.

**Comment by RocketPride17u5** [comment]
Logistical Solutions LLC.

Computer Science DEPT.

David J Lester

Lesterjohndavid@hotmail.com

1-209-495-7245

________________________________
