### ISSUE TITLE
Debuge not workink properly

### ISSUE THREAD

**Issue by yantrab** [Microsoft/vscode#68954]
- VSCode Version: 
- OS Version:
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
Steps to Reproduce:

1.Start debugging 
2.wait to to breakpoint
3.vscode stoped, but not tracking to breakpoint location.

![image](https://user-images.githubusercontent.com/12247800/52989370-beaffd00-340b-11e9-8c32-1d8a14fb7bf3.png)
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Andrianina007** [comment]
I had also this issue. 
I revert back my version to 1.30.2 and will be back until this issue will be fixed :)

**Comment by weinand** [comment]
Workaround: just add `"smartStep": false` to your debug configuration.
