### ISSUE TITLE
终端清除

### ISSUE THREAD

**Issue by DraCod** [Microsoft/vscode#68952]
Issue Type: <b>Bug</b>

win10操作系统，打开vscode终端，打开网易有道词典，点击利用有道词典的截屏翻译功能，然后在vscode的终端位置右键鼠标，才会显示可以清除终端的信息

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (11.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.31.4

</details>

**Comment by byyxx128** [comment]
大哥，我都没看懂……你让一帮子老外用翻译怎么看……而且老外也不用有道词典……你看看有没有更容易重现的方式，尽量不涉及特定软件的，可以上图说明。
***
### **Cannot understand, unable to translate.**
