### ISSUE TITLE
Including subviews when navigating between views

### ISSUE THREAD

**Issue by joeoe** [Microsoft/vscode#68957]
**Problem**
Navigating between views using the commands 'navigate to the view on the left' etc can be confusing as it involves jumping over certain subviews. 

For example if the focus is on the right window of a split integrated terminal and I execute 'navigate to the view on the left' I expect to land on the left terminal, not on the sidebar (or not move at all if the sidebar is on the right). I tried to illustrate that in these screenshots:

_Actual behavior:_
![2019-02-19_07-21-52_code](https://user-images.githubusercontent.com/12350897/52997026-992cee80-341f-11e9-9089-6ddc7a7330b3.png)

_Expected:_
![2019-02-19_07-21-52_code_expected](https://user-images.githubusercontent.com/12350897/52997035-9fbb6600-341f-11e9-8268-0f7a48b39e3d.png)

This however does not apply to multiple editor groups, I assume because every group is treated as a full view. It seems to be a matter of personal preference how the navigation behaves so I would propose a setting that makes jumping respect subviews as well as full views.

**Comment by isidorn** [comment]
@octref you did a pr similar to this, forawrding to you. I have no plan to tackle this

**Comment by octref** [comment]
There are two commands "Select Previous Pane" and "Select Next Pane" for the terminal.

The whole Panel is a View, and the splitting only happens inside the sub-view which is terminal, so `navigate to the view on the left` wouldn't be able to navigate through that.
