### ISSUE TITLE
Export/import user settings and extensions

### ISSUE THREAD

**Issue by kgbph** [Microsoft/vscode#68961]
Can we have the feature to export and import settings, same with visual studio?

**Comment by kgbph** [comment]
No this is not a duplicate.
Both of the issues are closed for being duplicate of (https://github.com/Microsoft/vscode/issues/2743), which asks for settings synchronization support.
What I ask for is a file with all my settings and extension, so I can make backup of my current settings.

**Comment by mjbvz** [comment]
See https://stackoverflow.com/a/49706409/306149
