### ISSUE TITLE
possible bug on enter and tab button

### ISSUE THREAD

**Issue by thomas66690801** [Microsoft/vscode#68968]
Issue Type: <b>Bug</b>

I recently experiencing problems when I'm working on md file.
which after a while, return button, tab no longer works. 

When this happened, i resorted into switching off code and restarting it again, until the next one happened.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.5.0
markdown-emoji|bie|0.0.7
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.26
javascript-ejs-support|Dig|0.4.1
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
rest-client|hum|0.21.1
vscode-cosmosdb|ms-|0.10.0
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
color-highlight|nau|2.3.0
quicktype|qui|12.0.46
ruby|reb|0.21.1
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1
vscode-paste-and-indent|Rub|0.0.8
lorem-ipsum|Tyr|1.2.0
quokka-vscode|Wal|1.0.189
vscode-todo-highlight|way|1.0.4
ReactSnippets|xab|2.3.0
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.1.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by thomas66690801** [comment]
Thanks Matt.
I'm using the std VSCode.
I have disabled all extension, and for now it looks like they are stable.

Thomas.

**Comment by mjbvz** [comment]
Ok, if you can narrow down which extension may be causing this please file an issue against them. You can use the `Developer: Show Running Extensions` command to see a list of currently active extensions

**Comment by thomas66690801** [comment]
Thank you Matt.
