### ISSUE TITLE
Splitview: Support customizable sash width

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#68962]
Issue Type: <b>Feature Request</b>

currently i am facing  a lot of trouble while resizing the spit-windows as the resize cursor only appears on the tiny border of the window. I would like to have a wider target for the resize cursor. it could be the tabless entire tabless part of the tab-bar.

VS Code version: Code - Insiders 1.32.0-insider (a75cf6e4b4317de0bf38284af255bdf0089deb68, 2019-02-19T06:18:01.215Z)
OS version: Windows_NT x64 10.0.15063

**Comment by w9jds** [comment]
I have been looking into this and already created a setting for it, as well as modified the sash to take in a size option and apply it, and default to the `4px` that is currently used. Is there any suggestions on how I get the setting down to the sash? Everything that creates a sash doesn't get passed in a `IConfigurationService`
