### ISSUE TITLE
Can't assign hotkey to create new file/folder

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#68960]
Issue Type: <b>Bug</b>

The latest insider build doesn't allow me to assign hotkeys to create new file or directory. I did use hotkeys <kbd>A</kbd> and <kbd>Shift + A</kbd> for years but for some reasons it will broken since VSCode `1.31.0`.

I think the issue related to #68161. Instead of fixing the bug that fix just hides input field for typing new file/folder name.

```json
[{
  "key": "a",
  "command": "explorer.newFile",
  "when": "listFocus && !inputFocus"
}, {
  "key": "shift+a",
  "command": "explorer.newFolder",
  "when": "listFocus && !inputFocus"
}]
```

Keyboard navigation mode: **simple**.

VS Code version: Code - Insiders 1.32.0-insider (a75cf6e4b4317de0bf38284af255bdf0089deb68, 2019-02-19T06:15:45.796Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--extensions-dir /tmp/vscode_test --user-data-dir /tmp/vscode_test|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by isidorn** [comment]
This is because the tree is eating up those keybindings. Forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/68233

**Comment by Ky6uk** [comment]
@joaomoreno @isidorn Issue #68233 is a feature request when this issue is the bug. Does that mean the impossibility to assign hotkeys to `explorer.*` commands was designed feature? If yes I'll just use `v1.30` of VSCode awaiting this feature to release.

**Comment by joaomoreno** [comment]
@Ky6uk This has nothing to do whether the command is `explorer.` or `list.`. Is has to do whether the user has focus on the list.

If you want to keep using those keybindings, you have to disable keyboard navigation otherwise <kbd>A</kbd> would execute your command and every other letter would be forwarded to the list filter. #68233 is what will enable you to disable keyboard navigation.
