### ISSUE TITLE
Find in folder broken for MR workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#68966]
VSCode insiders, mac

1. Any multi root workspace, right click find in folder on any folder inside a root
2. Search viewlet opened but files to inlcude has funky content

./vscode/function(e,t){if(e.scheme===t.scheme&&d(e.authority,t.authority)){if(e.scheme===r.Schemas.file){const s=n.relative(e.path,t.path);return a.isWindows?i.toSlashes(s):s}return n.posix.relative(e.path||"/",t.path||"/")}}

![screenshot 2019-02-19 at 11 30 46](https://user-images.githubusercontent.com/1926584/53008505-d69e7580-3439-11e9-99e0-55c26fb1ec6f.png)

**Comment by roblourens** [comment]
That's kind of funny. FYI @aeschli https://github.com/Microsoft/vscode/commit/a06dbfc3f2a0a69a890583bc77abd36567d5864e#diff-4a12537872685c49f4dc5c42f1537c45
