### ISSUE TITLE
Open and close quotes and wrap with quotes not working

### ISSUE THREAD

**Issue by MorenoMdz** [microsoft/vscode#68975]
Issue Type: <b>Bug</b>

* VSCode Version: January 2019 (version 1.31)
* OS Version: OSX Mojave

Steps to Reproduce:

1. Try to quote any time it won`t add the second quote.
2. Try to wrap with quotes or double quotes it will replace the text selection with a single of the used quote.

It works fine in Windows 10, it only happens in US international, which I need because of the accents.
Other editors like Sublime and Atom handle the auto closing quotes and wrap with quotes just fine in the same machine.

This is a very important issue for non english users, please do not ignore this as the previous issue about this was closed last year.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 7, 8|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|-psn_0_1352010|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
jest-snippets|and|1.7.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.8.0
es7-react-js-snippets|dsz|2.0.1
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
ReactCodeSnippets|haz|1.2.1
vscode-styled-components|jpo|0.0.25
vscode-gist|ken|3.0.3
graphql-for-vscode|kum|1.13.0
node-module-intellisense|lei|1.5.0
theme-monokai-pro-vscode|mon|1.1.10
vscode-jade-snippets|mrm|1.0.1
snippet-creator|nik|0.0.5
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
polacode|pnp|0.2.2
vscode-graphql|Pri|0.1.7
LiveServer|rit|5.5.1
vscode-icons|rob|8.2.0
RocketseatReactJS|roc|1.0.1
RocketseatReactNative|roc|1.0.2
nunjucks|ron|0.2.3
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.5
code-spell-checker|str|1.6.10
ayu|tea|0.18.0
vscode-import-cost|wix|2.12.0
ReactSnippets|xab|2.3.0
txt-syntax|xsh|0.0.3

(26 theme extensions excluded)

</details>

**Comment by andremacola** [comment]
#73828

**Comment by Buzunda** [comment]
This happens for me also on OSX Mojave
vscode Version 1.34.0

**Comment by alexandrudima** [comment]
Let's track in #34407
