### ISSUE TITLE
Diagnostic message list and marker are not updated after didChange

### ISSUE THREAD

**Issue by sergiuilie** [Microsoft/vscode#68971]
## Problem:
If a publishDiagnostic message is sent with the same properties, exactly the same, because we change something in the document but not fixing the errors, then nothing is supposed to change, that`s right and it is working out of the box, normal behaviour until the error message is new, contains the same properties and should be displayed on the same position. The issue here is that the position is shifting with the old wrong token and not with the new one as we can see in the following gif:

![issue](https://user-images.githubusercontent.com/23320888/52717987-ad499980-2fa2-11e9-9463-83b380acfc55.gif)

My diagnostic message is always the same because of the same wrong token position.

![5](https://user-images.githubusercontent.com/23320888/52717994-b5093e00-2fa2-11e9-8fe5-8517448cd50c.PNG)

I think that the problem is coming from `extHostDiagnostics.ts` class which can be accesed during debug by calling `setDiagnostics(uri, diagnostics)` from `client.js`, the boolean `hasChanged` is exiting the condition on `line 118`, which seems logic, but not in this case. 

![7](https://user-images.githubusercontent.com/23320888/52718002-bb97b580-2fa2-11e9-8db5-d6118dbeb61e.PNG)

# Solution:
I was thinking what can be one of the simplest solution, bare in mind that I am not a typescript person, so a refresh of the `Marker `seems acceptable; the second but more complex solution from many points of view is to add a new property to `Diagnostic`, like a message id.

**Comment by dbaeumer** [comment]
Moving to VS Code since this doesn't seem to be a problem with the LSP node libraries.

**Comment by jrieken** [comment]
Please provide repro steps, best a code snippet demonstrating this issue

**Comment by sergiuilie** [comment]
The error appears in one case, when you use LSP JSON-RPC communication to send an error message (so called publishDiagnostic) from the server to the client, if the message contains same Position, same Severity and same String message as previous publishDiagnostic message, than the bug occur. Please check the above mention classes from vscode client code plus the LSP specification. Here you have the diagnostic message which is sent over LSP.

![image](https://user-images.githubusercontent.com/23320888/53740969-a8874f80-3e95-11e9-8a18-c0e3de9cd5db.png)

Please let me know if you have more concerns.

**Comment by jrieken** [comment]
Yeah, if a diagnostics message doesn't change we update the extension-side data structure but we don't send a message to the UI. That's because no change would be observable. What is the desired behaviour?

**Comment by jrieken** [comment]
Oh, wait I understand..

**Comment by sergiuilie** [comment]
thank you 👍
