### ISSUE TITLE
monorepo: git side panel should show only changes under workspace folder(s)

### ISSUE THREAD

**Issue by digeomel** [Microsoft/vscode#68972]
We're working on a monorepo, and each project is in a different folder under the one repository.
I have a different vscode workspace for each project, containing only the folders that are relevant to the project.
When I work on multiple projects (so, I have more than one vscode windows/workspaces) at the same time, the Git sidebar shows me all the files that have changed (to be committed) across all folders (projects), including folders that are not in my workspace.

I would like to see only the files that have changed below the folder(s) of my workspace.

There is a git command for this:

https://stackoverflow.com/questions/4104764/git-show-list-of-files-changed-in-recent-commits-in-a-specific-directory

https://stackoverflow.com/questions/16343659/how-to-show-git-log-history-for-a-sub-directory-of-a-git-repo

**Comment by joaomoreno** [comment]
I'll merge this one into #30199, which essentially contains this.
