### ISSUE TITLE
Type check issue

### ISSUE THREAD

**Issue by jsavinash** [Microsoft/vscode#68982]
Issue Type: <b>Bug</b>

Type check is slow in typescript file.
I am working on react js project, it has ton's of file include test case and source code. if some props get updated in any of the files. i need to restart for type check error detection.
 
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.50GB free)|
|Process Argv|-psn_0_61455|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.23.0
flutter|Dar|2.23.0
vscode-eslint|dba|1.8.0
es7-react-js-snippets|dsz|2.0.1
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-great-icons|emm|2.1.46
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
git-project-manager|fel|1.7.1
terminal|for|0.0.10
beautify|Hoo|1.4.9
vscode-styled-components|jpo|0.0.25
dart-import|lua|0.1.2
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.2
vetur|oct|0.16.1
dart-syntax-highlighting-only|osc|1.0.0
material-icon-theme|PKi|3.6.3
LiveServer|rit|5.5.1
vscode-icons|rob|8.2.0
stylelint|shi|0.48.0
vscode-react-native|vsm|0.8.0

</details>

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this

**Comment by harry-sm** [comment]
I was having the same issue until I changed my vscode TS version 3.3.1 to a workspace version of 3.3.333.
