### ISSUE TITLE
Support directory diffs

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#6898]
The side-by-side diff view of staged & unstaged changes is completely fantastic. I want to use it for all my `git diff` commands. Frequently I'm diffing against something other than `HEAD`, though. For example, I'd like to see the equivalent of `git diff master` in vscode.

I realize that you can set up vscode as a git difftool, but this forces you to view the files one-by-one, rather than en masse. 

A way around this would be to support directory diffs. Then I'd be able to run `git difftool --dir-diff` to see all the diffs at once with vscode.

My `.gitconfig` looks like this:

```
[difftool "vscode"]
    cmd = code --wait --diff $LOCAL $REMOTE
```

I'm using vscode 1.1.1.

For comparison, the webdiff project does [something like this](https://github.com/danvk/webdiff/blob/62606f262895ea49005a01b450f0c1d60362ac95/webdiff/gitwebdiff.py) to support running `git webdiff` instead of `git diff` at the command line. It works great.

**Comment by joaomoreno** [comment]
Code is probably not going to implement this. I suggest implementing an extension which supports it or using a Git tool for that purpose.
