### ISSUE TITLE
Window is too dark on Ubuntu

### ISSUE THREAD

**Issue by monotwist** [Microsoft/vscode#68981]
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04 x64

Steps to Reproduce:

1. Install Ubuntu 18.04
2. Install VS Code 1.31.1
3. Run VS Code
![scrn](https://user-images.githubusercontent.com/25460660/53018228-e1b9cb80-3462-11e9-8bfc-35af7d80c356.png)
No extensions were installed 

Same problem was with Chrome 72, fixed by adding  `--use-gl=angle` to shortcut parameters

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Those colors are driven by themes, and that doesn't look like a default bundled theme to me. You might also want this setting:

```
"window.titleBarStyle": "native"
```
