### ISSUE TITLE
Let VS Code users Vote on github proposals!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [Microsoft/vscode#68985]
Let VS Code users Vote on github proposals!
Since MS now owns github, I think it will be better to urge .NET developers to vote on features proposed in .NET repos. So, I suggest VS Code frequently shows a startup window asking the developer:
> Do you agree with <<Subject>>? Join the discussion here <<Link>>. 

The window can also view a brief of the topic and a Yes\No links that are mapped to Like/dislike response on the topic.

You can have the user an option to stop viewing this window at startup, with an alternative command on the help or tools menu to show a report on topmost proposals. User also can choose the repos that interests him most to show their topics on the window/report. VS can make some assumptions about that from the types of projects he usually opens. Issues and proposals can be filtered based on numbers of reactions and comments, the milestone labels or any other suitable factors. Team members can also mark some issues to be viewed in VS.
If this happens, it can grantee participation of ten thousands , or even millions of developers in dissuasions. This will give a more realistic votes about each new feature and encourage developers to participate in writing the code of these features.

**Comment by Tyriar** [comment]
I think an awful lot of users wouldn't appreciate this sort of thing, regardless that's a different MS team and they could approach us if they thought it was a good idea.
