### ISSUE TITLE
Multi Replace Shortcut F12 (or fn+F12 for Mac) doesn't work for half-selection

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#68986]
Issue Type: <b>Bug</b>

This is my code -

```js
import * as React from "react";

export interface CounterProps {}

export interface CounterState {
  count: number;
}

class Counter extends React.Component<CounterProps, CounterState> {
  state: CounterState = { count: 0 };

  private _increment = () => {
    this.setState(prevState => ({ count: prevState.count + 1 }));
  };

  private _decrement = () => {
    this.setState(prevState => ({ count: prevState.count - 1 }));
  };

  render() {
    const { count } = this.state;
    return (
      <>
        <div>{count}</div>
        <button onClick={this._increment}>+</button>
        <button onClick={this._decrement}>-</button>
      </>
    );
  }
}

export default Counter;
```

I want to replace `Counter` by `ClassCounter` using `fn+F12`

So I select `Counter` at the top by half-selecting `CounterProps` then I press `fn+F12`, it completely selects `CounterProps` while I wanted just `Counter` to be selected.

In short, I want to replace every `Counter` occurrence with `ClassCounter` using `fn+F12`.

Currently, the only way I can do it is by selecting `Counter` in `CounterProps` & then `Ctrl+D` all the occurrences one by one.

Hope I explained well 😂

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
alignment|ann|0.3.0
spellright|ban|3.0.24
vscode-icontheme-nomo-dark|be5|1.3.6
color-info|bie|0.5.0
simple-react-snippets|bur|1.2.2
turbo-console-log|Cha|1.2.13
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.23.0
flutter|Dar|2.23.0
vscode-markdownlint|Dav|0.24.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
vscode-highlight|fab|1.3.4
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
gc-excelviewer|Gra|2.1.29
RelativePath|jak|1.4.0
latex-workshop|Jam|6.0.0
search-node-modules|jas|1.3.0
vscode-pigments|jas|1.0.6
pubspec-assist|jer|0.3.3
vscode-hacker-typer|jev|0.1.1
vscode-styled-components|jpo|0.0.25
swift|Kas|0.0.3
auto-comment-blocks|kev|1.0.1
graphql-for-vscode|kum|1.13.0
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.11.2
awesome-flutter-snippets|Nas|1.0.5
vscode-jest|Ort|2.9.2
advanced-new-file|pat|1.2.0
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.3
vscode-graphql|Pri|0.1.7
ActiveFileInStatusBar|Ros|1.0.3
code-settings-sync|Sha|3.2.5
mdx|sil|0.1.0
velocity|sod|0.1.0
ayu|tea|0.18.0
highlight-matching-tag|vin|0.8.6
vscodeintellicode|Vis|1.1.3
vscode-svg-previewer|vit|0.3.1
vscode-wakatime|Wak|1.2.5
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(16 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Do you have custom keybindings? F12 defaults to go to definition, nothing to do with selections?

**Comment by deadcoder0904** [comment]
Nope, no custom keybindings at all. `fn+F12` replaces all occurrences. It's like `Find and Replace All` with `fn+F12`.

**Comment by Tyriar** [comment]
This must be one of your 59 extensions overriding the keybinding, you'll need to find which one and report the issue there.

**Comment by deadcoder0904** [comment]
Sorry, @Tyriar it was `fn+F2` & not `fn+F12` 😂 & the issue remains as I've checked again by disabling all extensions.
