### ISSUE TITLE
Provide commands to expand selection up to semantic block

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#68992]
The selectionRange API allows `kind` on the ranges returned.

```ts
export class SelectionRange {
	kind: SelectionRangeKind;
	range: Range;
	constructor(range: Range, kind: SelectionRangeKind);
}
```

Can we offer commands for "selecting up to the next `${SelectionRange.kind}`"?

For example, in Vim I have `vi(`, `vi[`, `vi{` for selecting up to the next **syntactical** enclosing `()`, `[]`, or `{}` blocks. I would like to have commands for selecting up to the next **semantical** blocks.

@dbaeumer fyi, would like to know what you think too

**Comment by dbaeumer** [comment]
If I remember correctly being able to support something like this was the idea of having a kind.
