### ISSUE TITLE
Don't debounce searches in the type-to-filter-menus

### ISSUE THREAD

**Issue by DelvarWorld** [Microsoft/vscode#6899]
- VSCode Version: Version 1.1.1 (1.1.1)
- OS Version: OSX

Steps to Reproduce:

1. Open any menu, like the find files menu, with ⌘P
2. Type the name of the file

Expected:

The file should show up almost instantly, as I'm typing, since after the first 3 keystrokes it should match, **as I'm typing**

Actual:

I have to stop typing and wait 500ms - 1000ms for the file to show up. It looks like you're debouncing the search function from the menu. This makes the editor feel sluggish. It should be based on an interval instead.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5638
