### ISSUE TITLE
Exiting zen mode focuses the terminal

### ISSUE THREAD

**Issue by awmottaz** [Microsoft/vscode#68993]
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open an editor with the terminal open. Put focus in the editor (not the terminal)
2. Enter and then exit zen mode using the keyboard shortcuts or from the command palette
3. The focus is now in the terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
You can try the fix in tomorrow's vscode insiders and let us know if it fixes your problem
