### ISSUE TITLE
Several wrong pt_BR translations in version 1.31.1 on Mac OS

### ISSUE THREAD

**Issue by nighto** [Microsoft/vscode#68995]
- VSCode Version: 1.31.1 1b8e8302e405050205e69b59abb3559592bb9e60
- OS Version: Mac OS Mojave 10.14.3

Steps to Reproduce:

1. Update VSCode to this version (current)
2. See broken translations.

Does this issue occur when all extensions are disabled?: Yes

Several pt_BR (brazilian portuguese) translations are broken in this release. This is weird because those strings used to be correct in previous versions if I correctly recall (could be wrong though, didn't double check).

![image](https://user-images.githubusercontent.com/397851/53034710-88e23700-3452-11e9-84a7-f381ef76cb8b.png)
(Space before and lack of capitalization in ` seleção`, the same in ` encolher seleção`, `Co  py linha para baixo` and so on)

The same happens in other menus, lack of capitalization, strings untranslated, poorly translated or half-translated, and random spaces.

![image](https://user-images.githubusercontent.com/397851/53034796-bb8c2f80-3452-11e9-9f98-6e31c9a07dfa.png)

What happened?

**Comment by gusbemacbe** [comment]
Check https://github.com/Microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-pt-BR/translations/main.i18n.json

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project for contributing to the community-driven pt-BR translations
