### ISSUE TITLE
Editor not scrolling to cursor position undo/redo

### ISSUE THREAD

**Issue by madprops** [Microsoft/vscode#68996]
Latest stable release. Windows 10.

I'm not sure if it happens without extensions because I don't know how to replicate this, it just happens sometimes.

But basically, this is a BIG problem for me. When I start making undos or redos, the operations happen but the editor is not scrolled to the changes. So basically im in a different portion of the editor and I can't see what the changes were, I'm completely blinded of the changes, and don't know what is happening.

I tried searching for issues involving this but the ones I found seem different.

**Comment by alexandrudima** [comment]
@madprops Do you press `Ctrl+Z` to execute undo? Can you please search for `Ctrl+Z` in your keybindings editor and check if any extension is stealing that keybinding:

![image](https://user-images.githubusercontent.com/5047891/53166299-367d5380-35d5-11e9-8d04-c1e40e56bd2e.png)

**Comment by madprops** [comment]
![code_2019-02-21_12-11-20](https://user-images.githubusercontent.com/206498/53191619-e6e95880-35d1-11e9-9d45-9faa7bf7cb39.jpg)

Good news though! I can replicate it now. Basically if I select a bunch of stuff with ctrl+d, and then make changes to them, after I do undo the cursor doesn't move to any of them.

**Comment by madprops** [comment]
Correction: The cursors move but they are not scrolled into view.

**Comment by alexandrudima** [comment]
Aha! Let's track in #6995
