### ISSUE TITLE
Sorting is not applied on start, or always default sorting is applied on start.

### ISSUE THREAD

**Issue by charJKL** [Microsoft/vscode#68990]
Sorting is not applied on start, or always default sorting is applied on start.

- VSCode Version: 1.31
- OS Version: Windows 10

Steps to Reproduce:
1. Change "explorer.sortOrder" setting to "filesFirst", or other than default.
2. Close VSCode.
3. Open VScode, default sorting is applied. If we perform action, which trigger explorer refresh everything sorting back to our first choice.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
dup of https://github.com/Microsoft/vscode/issues/68323

**Comment by charJKL** [comment]
Yes, you are right it's duplicate. My apologies for that.

**Comment by isidorn** [comment]
np, will be fixed in tomorrow's vscode insiders
