### ISSUE TITLE
Find in Files not Working in Folder with Multiple Large Files

### ISSUE THREAD

**Issue by robmonte** [Microsoft/vscode#68994]
Issue Type: <b>Bug</b>

I am searching logs for an error string (using Cmd+Shift+F) in my folder workspace, which has ~30 files each at around 100,000 lines. I know what I am searching for is present in these files, yet searching for it via this method returns no results. When I do regular Cmd+F in one file at a time, I find 5 occurrences.

~Cmd+Shift+F finds some results when I search a small piece of the error. For example "getReturn" find many results, but "getReturnR" (R is just the next letter of the function name) returns zero results. There are actually many occurrences of this function throughout the logs though.~ [Updated info about this here.](https://github.com/Microsoft/vscode/issues/68994#issuecomment-467080868)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by robmonte** [comment]
I forgot to include that I tried this on the Insiders version and it was the same result.

**Comment by roblourens** [comment]
So this isn't a regex search right? Is it possible that there is a hidden character or something else in that file? Would be awesome if you can upload the file and the search string. Being a large file is probably not the issue.

Or we can try to reduce it, e.g. delete everything around that function name, check if it still happens, and then upload the file.

**Comment by robmonte** [comment]
I have something to add: The Cmd+Shift+F search does not work when there are no editors open. As soon as a file with the search string is opened into an editor, it will find the results in the file. It's not a big revelation as I already put that Cmd+F works which implies an open editor to begin with.

-----

So... nope, it is not a regex search. There is definitely no hidden character(s), in fact if I delete it out of the log and manually type it back in to the same line, it still shows no results.

If I copy the line into a separate file, it comes up in the results.

If I copy the error to the top of the same log, the search finds that error I copied (line 2) but not the original. (The original in this one particular log happens on like 33,704).

**Comment by robmonte** [comment]
I found out something in relation to my original comment where I stated "getReturn" vs "getReturnR" having results vs no results.

Just "getReturn" finds many results but still DOES NOT return results for my desired line. This took a long time to find out because there were an extreme number of matches on getReturn but there's only 5 expected "getReturnR..." search results. In other words, the last 'R' really has no bearing on the search working or not and has turned out to be a misleading piece of information.

**Comment by robmonte** [comment]
Okay so I figured out a part of the issue but discovered another facet of this problem.

1. The good news) You were right about hidden characters, I was only thinking to search for them inside the line my search string was looking for. But about 32,000 lines beforehand are two hidden null characters (0x00). So my assumption is it's causing a preemptively null-terminated string that is used in the search logic. Removing this line causes "getReturnR" to show results inside the file now as expected.

2. The bad news) I discovered that adding any characters from the line *above* my expected search result makes the search to work correctly - and that's *with* the null characters still present. So I have no idea why the null character wouldn't still break that search.
For example, it goes something like this:
```
line 33684: <timedate stamp> Class.function() java.lang.NullPointerException
line 33685: (tab)at com.blah.blah.blah.Class.getReturnRecognition(Class.java:100)
```
If I copy it and search for:
```
java.lang.NullPointerException(newline)
(tab)at com.blah.blah.blah.Class.getReturnRecognition(Class.java:100)
```
It finds results.

Even if I just search for the last 'n' of of the word "exception" to the 'a' in "at", it works.
```
n(newline)
(tab)a
```
Shows all my expected search results.

**Comment by roblourens** [comment]
Thanks for the investigation, yes, a null byte would explain it. When ripgrep enounters a null byte, it decides that the file is binary data and silently stops searching it.

I'm not sure why you still got a result from the line before. rg is probably searching the file in chunks in parallel, and the behavior may not be 100% predictable here.

Also note that if the file is open it's searched by the editor, and you will probably always get results then, so make sure you aren't comparing a search where the file was open to one where it was not.

**Comment by robmonte** [comment]
For future reference, I was _not_ comparing an open editor to a closed editor. Unfortunate that it turns out to be an intended feature of ripgrep, but it does seem that it contains a flag to allow searching of binary files. Hopefully this can be possibly supported in the future.

**Comment by roblourens** [comment]
Hey @rebornix I'm curious, how does the editor decide that a file is a binary file? I guess one annoying thing is that ripgrep and the editor have different definitions so that the file renders fine in the editor but isn't searched by ripgrep.

I'm not sure I can enable that flag on rg anyway since it might change how normal newlines are processed, 

> Enabling this option causes ripgrep to use NUL as a line terminator instead of the default of '\n'.

And it would end up spending a lot of time searching all the .pngs or whatever in a workspace.

**Comment by rebornix** [comment]
@roblourens AFAIK the file/editor service will treat the file as Binary if the auto detection failed, and that's probably when it disagrees with ripgrep on whether the file is binary or not https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L517 .
