### ISSUE TITLE
Ability to re use a view across view containers

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#69004]
Issue Type: <b>Bug</b>

In an extension, I have a tree view that is registered to one of two view containers based on a setting:

```
    "viewsContainers": {
      "activitybar": [
        {
          "id": "github-pull-requests",
          "title": "GitHub Pull Requests",
          "icon": "resources/icons/github.svg"
        }
      ]
    },
    "views": {
      "github-pull-requests": [
        {
          "id": "pr",
          "name": "GitHub Pull Requests",
          "when": "!config.githubPullRequests.showInSCM && config.git.enabled && github:hasGitHubRemotes && workspaceFolderCount != 0"
        }
      ],
      "scm": [
        {
          "id": "pr",
          "name": "GitHub Pull Requests",
          "when": "config.githubPullRequests.showInSCM && config.git.enabled && github:hasGitHubRemotes && workspaceFolderCount != 0"
        }
      ]
    },
```

When the setting is false, I get the error `Error: view descriptor pr not found` when trying to use the reveal API. Looks like when trying to get the view container, the `when` context isn't considered and the first match is used:
https://github.com/Microsoft/vscode/blob/5076c35a534f9ee03a4fead0ad5b858fcaa260eb/src/vs/workbench/common/views.ts#L222-L230

VS Code version: Code - Insiders 1.32.0-insider (a75cf6e4b4317de0bf38284af255bdf0089deb68, 2019-02-19T06:15:45.796Z)
OS version: Darwin x64 18.2.0

**Comment by sandy081** [comment]
@RMacfarlane I do not think there is a support for contributing a view with same id (irrespective of contributing to different view containers). View id should be unique across for now.
