### ISSUE TITLE
Wrong acronym on Blog post

### ISSUE THREAD

**Issue by caiotoon** [Microsoft/vscode#69002]
Quite a simple one, but the first time the acronym for Language Server Index Format appears, it's misspelled LISF, which makes the pronunciation make no sense.

Third paragraph, first phrase, between parenthesis
https://code.visualstudio.com/blogs/2019/02/19/lsif#_rich-code-navigation-without-checkout

**Comment by gregvanl** [comment]
https://github.com/Microsoft/vscode-docs/commit/03e979ce07b93b9c5d69fc31d29114565f4cc6cb
Thanks for pointing this out.
