### ISSUE TITLE
Git repository details in window.title

### ISSUE THREAD

**Issue by grantbowering** [microsoft/vscode#69003]
When one has a folder open in VS Code, it always seems to be aware it's in a git repo, even if the folder you opened isn't the root of the repo.  
It would be useful to be able to have the name of that repo available as a variable in the `window.title` setting.  And perhaps also, the folder path relative to the root of the repo.

My use case is: on Windows, with labels on taskbar buttons, say I have the following folder structure:
```
source
└─ git 
   └─ someProject
      ├─ .git
      ├─ doc
      └─ src
         ├─ Api
         ├─ Data
         └─ Web
   └─ otherProject
      ├─ .git
      ├─ doc
      └─ src
         ├─ Api
         ├─ Data
         └─ Web
```    
I may open a VS Code window for each Web folder and switch between them.

If I use `${folderName}` or `${rootName}`, I just see 
`[Web   ] [Web   ]` 
in my taskbar and I can't tell them apart.

If I use `${folderPath}` or `${rootPath}`, depending on what else I have open I just see 
`[C:\source\git\...] [C:\source\git\...]`
same problem.

What I would like to see is 
`[someProject - Web] [otherProject - Web]`, or 
`[someProject/src/Web] [otherProject/src/Web]`, 
something like that.

Repo name would be one way to accomplish that, in my case.  
(Another possibility would be to allow some sort of syntax for a simple string replace, so I could get rid of "`C:\source\git\` when using `${rootPath}`.)

**Comment by joaomoreno** [comment]
Why don't you simply open the `someProject` and `otherProject` folders?

**Comment by grantbowering** [comment]
Ah, perhaps I oversimplified the example a little too much for anyone to actually see the point! Sorry.

These are large multi-project .NET solutions actually, and in each solution, one project hosts a react&redux SPA.

When I'm working in VS Code, it's because I'm working in the client-side code and want a lean and fast experience editing it, and am not interested in any of the server-side stuff.  I don't want to load any of the C# code at all.  
I'm typically opening `source/git/someSolution/src/Web/ClientApp/`, which is just TS code, and if I were to open `source/git/someSolution/` instead just for the sake of the title bar, I would be involving not only the server-side parts of the Web project but also a half dozen other .NET projects that I'm not interested in at that time either.

Here's a more representative example of what these look like on-disk, including some of the myriad projects I'm not looking at.  (The arrows show the folders I typically open in VS Code.)
```
 source
 └─ git 
    └─ someSolution
       ├─ .git
       ├─ README.md
       └─ docs
          └─ [buncha markdown files]
		  
       └─ src
          ├─ someSolution.sln
          └─ CoreApi
             └─ Configuration
                └─ [buncha C# config classes]
				
             └─ Controllers
                └─ [buncha C# controller classes]
				
             └─ Models
                └─ [buncha C# model classes]
				
             ├─ CoreApi.csproj
             ├─ Program.cs
             ├─ Startup.cs
             └─ [etc.]
			 
          └─ CoreApi.Tests
             └─ ControllerTests
                └─ [buncha C# xunit test classes]
				
             ├─ CoreApi.Tests.csproj
             └─ [etc.]
			 
          └─ DataAccess
             └─ Models
                └─ [buncha C# EF classes]
				
             └─ Repositories
                └─ [buncha C# repository classes]
				
             ├─ DataAccess.csproj
             └─ [etc.]
			 
          └─ DataAccess.Tests
             └─ RepositoryTests
                └─ [buncha C# xunit test classes]
				
             ├─ DataAccess.Tests.csproj
             └─ [etc]
			 
          └─ Web
             └─ Configuration
                └─ [buncha C# config classes]
				
             └─ ClientApp                        <------------------------------
                ├─ package.json
                └─ [all the typescript src]
				
             └─ Controllers
                └─ [buncha C# controller classes]
				
             └─ Pages
                └─ [some cshtml for bootstrapping]
				
             ├─ Web.csproj
             ├─ Program.cs
             ├─ Startup.cs
             └─ [etc.]
			 
          └─ Web.Tests
             └─ ControllerTests
                └─ [buncha C# xunit test classes]
				
             ├─ Web.Tests.csproj
             └─ [etc]
			 
    └─ otherSolution
       ├─ .git
       ├─ README.md
       └─ docs
          └─ [buncha markdown files]
		  
       └─ src
          ├─ otherSolution.sln
          └─ CoreApi
             └─ Configuration
                └─ [buncha C# config classes]
				
             └─ Controllers
                └─ [buncha C# controller classes]
				
             └─ Models
                └─ [buncha C# model classes]
				
             ├─ CoreApi.csproj
             ├─ Program.cs
             ├─ Startup.cs
             └─ [etc.]
			 
          └─ CoreApi.Tests
             └─ ControllerTests
                └─ [buncha C# xunit test classes]
				
             ├─ CoreApi.Tests.csproj
             └─ [etc.]
			 
          └─ DataAccess
             └─ Models
                └─ [buncha C# EF classes]
				
             └─ Repositories
                └─ [buncha C# repository classes]
				
             ├─ DataAccess.csproj
             └─ [etc.]
			 
          └─ DataAccess.Tests
             └─ RepositoryTests
                └─ [buncha C# xunit test classes]
				
             ├─ DataAccess.Tests.csproj
             └─ [etc]
			 
          └─ Web
             └─ Configuration
                └─ [buncha C# config classes]
				
             └─ ClientApp                        <------------------------------
                ├─ package.json
                └─ [all the typescript src]
				
             └─ Controllers
                └─ [buncha C# controller classes]
				
             └─ Pages
                └─ [some cshtml for bootstrapping]
				
             ├─ Web.csproj
             ├─ Program.cs
             ├─ Startup.cs
             └─ [etc.]
			 
          └─ Web.Tests
             └─ ControllerTests
                └─ [buncha C# xunit test classes]
				
             ├─ Web.Tests.csproj
             └─ [etc]
```

**Comment by joaomoreno** [comment]
Also git branch: https://github.com/Microsoft/vscode/issues/69584

**Comment by mrtnbrst** [comment]
I'd like to display the active branch / worktree in the window.
This could be usefull if you are working with different worktrees of the same git repo in different windows and want to see which one is which on first sight without checking the absolute path of the file. 

```json
"window.title": "${dirty}${activeEditorShort}${separator}${rootName}${separator}${worktree}",
```
