### ISSUE TITLE
Folder expand states are loaded from storage when adding/removing new folders to workspace

### ISSUE THREAD

**Issue by ragrag** [microsoft/vscode#69005]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Create a workspace and add one or more folder in it
2. Expand one or more folders from the workspace in the explorer and close VS Code to save the folder expansion state
3. Run VS Code and collapse the expanded folder from (2) then add a new folder to the workspace (or remove a folder from workspace)
4. Notice that the collapsed folder is expanded again (Expansion state loaded from storage rather than keeping the current state)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is a fair bug. Pushing it to the backlog since not mayor.

**Comment by atomboyd** [comment]
Is there a setting attribute I can duct tape this with? I use the add/remove feature pretty frequently in my workflow and this can get maddening.
