### ISSUE TITLE
Tree: option to show all descendants of a filtered match

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#69013]
#4338 Issue Type: <b>Bug</b>

```json
"workbench.list.keyboardNavigation": "filter"
```

* Output objects of objects into debug console.
* Expand some of them (only 1 level)
* Filter by typing
* Try to expand filtered item property (object/array)

VS Code version: Code - Insiders 1.32.0-insider (a75cf6e4b4317de0bf38284af255bdf0089deb68, 2019-02-19T06:18:01.215Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
Works for me.
Let me know what you are doing differently than me

![console](https://user-images.githubusercontent.com/1926584/53075785-538b2700-34ee-11e9-9cb1-eac8c924617d.gif)

**Comment by usernamehw** [comment]
I guess, my objects are nested deeper.

Can you try this object?
```javascript
const obj = {
    first: {
        second: {
            third: {
                item: "stuff"
            }
        }
    }
};
console.log(obj);
```

**Comment by isidorn** [comment]
Ok, great find. This is a tree issue.

@joaomoreno have the following program 

```
const obj = {
	first: {
		second: {
			third: {
				item: "stuff"
            }
        }
    }
};
console.log(obj);
debugger;
```
Start debugging, expand object. Have `"workbench.list.keyboardNavigation": "filter"`. Type first, try to click on first

Since all the children are filtereted out there is no feedback that the item got expanded / collapsed.
I would at least expect the twitstie icon to change. This way it is very confusing

**Comment by joaomoreno** [comment]
@isidorn Can you get repro steps?

**Comment by isidorn** [comment]
* @joaomoreno have the following program```
  const obj = {
  	first: {
  		second: {
  			third: {
  				item: "stuff"
              }
          }
      }
  };
  console.log(obj);
  debugger;
  ```Start debugging, expand object. Have `"workbench.list.keyboardNavigation": "filter"`. Type first, try to click on firstSince all the children are filtereted out there is no feedback that the item got expanded / collapsed. I would at least expect the twitstie icon to change. This way it is very confusing

**Comment by usernamehw** [comment]
The twistie already changing.  

![twistie](https://user-images.githubusercontent.com/9638156/53173711-4575fd00-35f9-11e9-8388-10ef304c9559.gif)

Are you saying that this is never going to work?

**Comment by isidorn** [comment]
@usernamehw what would you expect to see there. You filtered to see only the elements "first" none of the children have it.

Leaving up to @joaomoreno to decide what to do here

**Comment by usernamehw** [comment]
A setting
```javascript
"workbench.tree.showFilteredNestedItems": false
```
Be able to expand anything if the filters matches any of the ascendants.

**Comment by isidorn** [comment]
Ok, so this seems to be tree specific configuration.
Renaming the issue and setting it to be a feature request
