### ISSUE TITLE
Resolve all before filtering debug console (include nested search results)

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#69015]
#4338 Issue Type: <b>Feature Request</b>

Currently it doesn't support searching in nested items.

**Comment by isidorn** [comment]
Basically dup of https://github.com/Microsoft/vscode/issues/66971
Since when we have this for the explorer we can have it for the debu console
Not sure how feasabile though since expanding everything might be computanionaly heavy on the debug adapter
