### ISSUE TITLE
VS Code Recommending Deprecated Extension (TSLint)

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode#69014]
As you can see, TSLint is deprecated but VS Code keeps on recommending it.

<img width="453" alt="screen shot 2019-02-20 at 8 17 45 am" src="https://user-images.githubusercontent.com/16755094/53057444-7287ba00-34ea-11e9-97fc-4add8364cb38.png">

Please recommend [this one](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) published by Microsoft.

**Comment by mjbvz** [comment]
@akaroml Which version of VS Code is this?

Also, if you open the extension page, why does it say it is being recommended? See below for example

![screen shot 2019-02-19 at 4 50 13 pm](https://user-images.githubusercontent.com/12821956/53058058-7a9e1600-3466-11e9-81ef-74ab1a3abc58.png)

**Comment by VishalMadhvani** [comment]
looks like a workspace recommendation: https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by mjbvz** [comment]
Please update `.vscode/extensions.json` to recommend `"ms-vscode.vscode-typescript-tslint-plugin"` instead
