### ISSUE TITLE
Add a setting to collapse editor actions panel or to make it have fixed width 

### ISSUE THREAD

**Issue by n1313** [microsoft/vscode#69018]
VSCode has "editor actions" panel to the right of the tab bar, that displays buttons for actions such as "Open Changes" or "Split Editor Right". 

![editor actions panel](https://i.stack.imgur.com/575LD.png)

This panel also dynamically adds other buttons depending on currently active file type, such as "Open Preview to the Side" for markdown files. I dislike this behavior because it makes the width of the tab bar change from file to file and it makes tabs shift around as I switch between them.

![changes in editor actions panel make tabs jump](https://i.stack.imgur.com/IKnAq.gif)

I have searched in VSCode settings but couldn't find any way to control this. I think it would be nice to be able to fix the maximum width (or the maximum number of action buttons) that the editor actions panel can take, or to force it to collapse all the actions into "more actions" dropdown.

**Comment by jagij** [comment]
I'd like to add to this. Preferably, all editor file tabs (or however that's called) should have the exact same width. Just like browser tabs, they should have a preferred width and shrink when too many tabs can't fit anymore in the bar.

Please also make sure that the 'x' button to close a tab is always visible, even when the tab isn't currently the active one.

Why? Closing multiple tabs with the mouse is very tiresome when you have to move the mouse pointer to the next x (once you closed the previous one). When all tabs have the same width, closing multiple adjacent tabs is just pointing to the x, then click-click-click.

Almost essential byfeature: keep the tab width for as long as the mouse pointer is hovering over the tabs. This way the tabs don't get larger when by closing a tab there's suddenly enough space to make the tabs wider.

For a good example of how tabs should behave: have a look at how Firefox handles tabs. Although do note that they currently hide the close button when running out of space, which is not ok.

**Comment by JakeCooper** [comment]
Chrome's method of handling tabs is quite solid. The workflow should likely be:

- Have all tabs be a uniform size.
- When the x is clicked, set a 1s timeout. If another x is clicked, clear that timeout and set another.
- When the setTimeout actually fires, perform a tab expansion if (tabs[0].width * tabs.length) > editorBar.width. Otherwise, noop.

This should be pretty straightforward to implement. Are there other tickets tracking this issue?

**Comment by sgehrman** [comment]
i want more space for Editor Actions.  annoying
