### ISSUE TITLE
On Linux: it changes the default mime-type action in Google Chrome for opening folders of downloaded things. Now "open folder" in Google Chrome opens vs code instead of the file explorer (e.g. Nautilus). 

### ISSUE THREAD

**Issue by guillaume-chevalier** [Microsoft/vscode#69010]
On Linux: it changes the default mime-type action in Google Chrome for opening folders of downloaded things. Now "open folder" in Google Chrome opens vs code instead of the file explorer (e.g. Nautilus). 

Cmon. Why?

**Comment by Tyriar** [comment]
This is where we register in the alternatives system, AFAIK we are doing this correctly as the priority is 0:

https://github.com/Microsoft/vscode/blob/e105391b9936054a0205c8aeec0e0d5886d1e3f0/resources/linux/debian/postinst.template#L10-L13
