### ISSUE TITLE
Provide setting to disable baseUrl style imports

### ISSUE THREAD

**Issue by dantman** [Microsoft/vscode#69021]
If a `baseUrl` is set vscode uses `src/foo.js`. In NestJS `baseUrl` is set so that tsconfig-paths works. The author [discourages](https://github.com/nestjs/typescript-starter/issues/74#issuecomment-464698726) the `src/` imports, but cannot remove `baseUrl` because that would disable `paths`.

Please provide an option to disable the `baseUrl` imports so only relative and paths imports are used.

**Comment by mjbvz** [comment]
Try setting `"javascript.preferences.importModuleSpecifier": "relative"` for this

**Comment by dantman** [comment]
I can try it again, but I already tried that and it did not work.
