### ISSUE TITLE
Kill terminal always kills the last one

### ISSUE THREAD

**Issue by ialhashim** [Microsoft/vscode#69020]
Issue Type: <b>Bug</b>

Split a terminal, click kill terminal.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (48 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|511.88GB (498.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.9.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-yaml|red|0.3.0
cython|tcw|0.1.0

</details>

**Comment by Tyriar** [comment]
It kills the last _active_ terminal by design

**Comment by ialhashim** [comment]
Sorry it wasn't clear, it was closing the last one on the right (last spawned) not as you say and as intended the active one. This behavior seem to be inconsistent though, once I reopened the window in another instance it was working fine.

**Comment by Tyriar** [comment]
> Split a terminal, click kill terminal.

Split then kill should definitely kill the one on the right as the new split terminal is always focused.
