### ISSUE TITLE
Integration of tools

### ISSUE THREAD

**Issue by deadmann** [Microsoft/vscode#69024]
Issue Type: <b>Feature Request</b>

How to integrate plugins and feature between multiple computer?
it was nice if i could get an option to:
1. login
2. choose a workspace - local / <named work space1> / <named work space 2> / <named work space N>
3. load all plugin that should be used within that work space no matter where i am...

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.10240

**Comment by Tyriar** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
