### ISSUE TITLE
cmd+right in integrated terminal triggers zsh ctrl+e keybinding

### ISSUE THREAD

**Issue by fhemberger** [Microsoft/vscode#69025]
Issue Type: <b>Bug</b>

1. Use zsh as default shell
2. Bind ctrl+e to "edit-command-line"
    ```sh
    autoload -U edit-command-line
    zle -N edit-command-line
    bindkey '^E' edit-command-line
    ```
3. `bindkey | grep edit-command-line` should show
    ```
    "^E" edit-command-line
    "^X^E" edit-command-line
    ```
4. Start Code, open Terminal and press cmd+right
5. Default editor opens for editing the current command line.

The problem persists even after disabeling all extensions.

I also tried adding the following to my `settings.json`:
```js
"terminal.integrated.commandsToSkipShell": [
    "workbench.action.terminal.moveToLineEnd",
    "cursorEnd"
]
```

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by Tyriar** [comment]
Solution on twitter: https://twitter.com/Tyriar/status/1098215015914455045

**Comment by fhemberger** [comment]
@Tyriar Sorry, issue is not completely fixed. Now `cmd+right` outputs `C` in the terminal. (ESC-C is the sequence for cursor right.)

**Comment by Tyriar** [comment]
@fhemberger that's as designed as it's being directed to the terminal now, if you want cmd+right to do something, assign it to a command and add the command to terminal.integrated.commandsToSkipShell

**Comment by fhemberger** [comment]
@Tyriar Well, I want it to move the cursor to the end of the line. The same as cmd+left moves it to the beginning. But when I do so, it opens the editor for the command line … which I reported as a bug. 🤷‍♂️

**Comment by Tyriar** [comment]
@fhemberger you overwrote the zsh keybinding that does that though `^E`? You can have cmd+right send whatever you want to the shell by binding it to the sendSequence command, I can't help with what to send though or configuring zsh to get it working though.

https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding

**Comment by fhemberger** [comment]
zsh is perfectly fine. The key binding works correct in Terminal.app and iTerm2.
cmd+left and cmd+right are not bound there. Navigating to beginning/end of line are done with fn+left and fn+right. That's not the point.

Code's integrated terminal **additionally** binds cmd+left/cmd+right for that (which is fine for me), but cmd+right also triggers the zsh keybinding for `^E` and opens the default editor. `^E` is not an escape sequence related to cursor movement (only `^A` to `^D` are, which are **just** the cursor keys. There isn't an ansi sequence for Apple's `cmd` key). So this seems to be a bug.

Also, there seems no way to suppress sending **anything** to the Terminal on this key combination.

**Comment by Tyriar** [comment]
Looks like I found this back in 2017 😄 https://github.com/xtermjs/xterm.js/issues/597

**Comment by fhemberger** [comment]
@Tyriar So can we agree this is an unwanted behavior on macOS?

**Comment by Tyriar** [comment]
@fhemberger yep

**Comment by fhemberger** [comment]
Ok, so let's re-open this issue or set up a proper bug report together.

**Comment by Tyriar** [comment]
@fhemberger it's open upstream https://github.com/xtermjs/xterm.js/issues/597
