### ISSUE TITLE
Input command not working in launch.json - env sections is not invoking input command for python program

### ISSUE THREAD

**Issue by neshdev** [Microsoft/vscode#69027]
- VSCode Version:
- OS Version:

Steps to Reproduce:

I am trying to automate one of my workflows where I need to pass in a dynamic environment variable.

I created a tasks for generating the dynamic string

I tried to configure the launch.json to call the workbench.action.tasks.runTasks.

This command seems to be never invoked. I also have a problem passing default arguments to the workbench.action.tasks.runTasks command.

When I pass this input command in the args section. Its getting invoked but is not registering the string from the dynamic process.

# launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": [
                "others",
            ],
            "env": {
                "test":"${inputs:test}"
            }
        },
    ],
    "inputs": [ 
        {
            "id" : "test",
            "type": "command",
            "command": "workbench.action.tasks.runTask",
            "args": ["echo"]
        },
    ]
}
```

# tasks.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "${config:python.pythonPath} ${workspaceFolder}/runner.py"
        },
    ],
}
```

# runner.py
```
print("hellopython")
```

# temp.py
```
import os
import sys
print(os.environ["test"])
print("test")
print(sys.argv)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@neshdev the syntax for input variables is `${input:variableID}` (without a plural 's').
Please see https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by neshdev** [comment]
@weinand - Is there any way to create a dynamic environment variable without creating a custom command/extension?

**Comment by weinand** [comment]
@neshdev no, this is not possible.
