### ISSUE TITLE
Not able to scroll horizontally with mouse

### ISSUE THREAD

**Issue by himhimlo** [microsoft/vscode#69028]
- VSCode Version: 1.31.1
- OS Version: Windows 10 64Bit v1809

Steps to Reproduce:

1. Open VS Code
2. Scroll horizontally with mouse that come with horizontal scroll -> not able to scroll
(however it is able to scroll when using <shift - [vertical scroll]>)

3. Minimize and then restore VS Code window
4. Horizontal scroll works again

Does this issue occur when all extensions are disabled?: Yes.

**Comment by alexandrudima** [comment]
> 3\. Minimize and then restore VS Code window

This reminds me of the mouse wheel workaround. Perhaps another Electron fluke... ?

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by edrandall** [comment]
Still an issue in 1.40.1
A bot that automatically closes issues on the backlog - in just a week!  What's the point?
