### ISSUE TITLE
Window crashed on multiple explorer refresh

### ISSUE THREAD

**Issue by Baidya123** [Microsoft/vscode#69023]
Issue Type: <b>Bug</b>

Clicking on "Refresh Explorer" (more than 2 times) present at leftside toolbar, popup shown "window crashed"
I think it is a bug and should be handled.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
I can not reproduce.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, can you share your workspace for which the window crashes?

**Comment by rebornix** [comment]
@isidorn for your information, here are duplicates I saw during last few days

* https://github.com/Microsoft/vscode/issues/69451
* https://github.com/Microsoft/vscode/issues/68424
* https://github.com/Microsoft/vscode/issues/69426

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68424
