### ISSUE TITLE
Can't use yarn install and build error

### ISSUE THREAD

**Issue by zhangxy1035** [Microsoft/vscode#69026]
According to the documentation, I installed various environments
when I use yarn ,it made a mistake
my environment:
node 10.15.1
npm 6.4.1
node-gyp 3.8.0
python 2.7.15
windows-build-tools vs2015

os version win32 x64
`
F:\work>cd vscode

F:\work\vscode>yarn
yarn install v1.13.0
$ node build/npm/preinstall.js
warning package-lock.json found. Your project contains lock files generated by t
ools other than Yarn. It is advised not to mix package managers in order to avoi
d resolution inconsistencies caused by unsynchronized lock files. To clear this
warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.10: The platform "win32" is incompatible with this modu
le.
info "vscode-fsevents@0.3.10" is an optional dependency and failed compatibility
 check. Excluding it from installation.
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check.
Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-tsb@2.0.6" has incorrect peer dependency "typescript@^2.0.10".
[4/4] Building fresh packages...
[1/16] ⠄ gc-signals
[2/16] ⠄ keytar
[3/16] ⡀ native-is-elevated
[4/16] ⡀ native-keymap
error F:\work\vscode\node_modules\gc-signals: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: F:\work\vscode\node_modules\gc-signals
Output:
F:\work\vscode\node_modules\gc-signals>if not defined npm_config_node_gyp (node
"E:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | win32 | x64
gyp http GET https://atom.io/download/electron/v3.1.3/iojs-v3.1.3-headers.tar.gz

gyp http 200 https://atom.io/download/electron/v3.1.3/iojs-v3.1.3-headers.tar.gz

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:
27)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\work\vscode\node_modules\gc-signals
gyp ERR! node -v v10.15.1
`

**Comment by zhangxy1035** [comment]
@weinand Thank you very much for your reply, but my question is different from what you sent. I have also reviewed other relevant issues, but I have not found relevant solutions.

**Comment by weinand** [comment]
@zhangxy1035 the (wrong) guesses were not me. It was a bot...
