### ISSUE TITLE
code-alpha won't start on Windows

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6902]
- VSCode Version:latest code-alpha
- OS Version:Windows 10

Steps to Reproduce:

1. Take the latest update.
2. close down code-alpha.
3. try 'code-alpha .'  Doesn't launch alpha, Task Manager doesn't show process running.

Just started happening on the latest update 34ccc760e4ae61cbd17b1d894cb10a8e4fbc3fc5

**Comment by Tyriar** [comment]
Reproduced, I likely caused it in https://github.com/Microsoft/vscode/pull/6588 because `code --wait` and `code --verbose` works. Looking into it.

**Comment by Tyriar** [comment]
Should be fixed, I queued new Windows and Linux builds, OSX build servers seems to have an issue.

**Comment by gregvanl** [comment]
Verified fixed on Windows.
