### ISSUE TITLE
vscode 窗口定位问题

### ISSUE THREAD

**Issue by 653560701** [Microsoft/vscode#69032]
Issue Type: <b>Bug</b>

使用windows10时 win+p 在拓展屏幕上使用vscode  然后关闭拓展屏幕后  当前桌面就找不到打开的vscode了

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.21.1
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hans|MS-|1.31.4
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.1.0

</details>

**Comment by Tyriar** [comment]
Translation:

> When using windows10 win+p After using vscode on the extended screen and then closing the extended screen, the current desktop can't find the open vscode.

I can't reproduce this, does alt+tab let you focus the window and then win+up let you maximize to the screen?

**Comment by rebornix** [comment]
Close for now as lack of information.
