### ISSUE TITLE
Integrated Terminal: problems with the prompt when resizing the panel

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#69039]
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3

There seem to be multiple problems with resizing:

 - console escape sequences may appear
 - cursor position seem to be wrong so typing may erase the prompt

![vscode-prompt](https://user-images.githubusercontent.com/199648/53089131-faca8700-350b-11e9-9723-1298843c8c4f.gif)

Steps to Reproduce:

1. Open the integrated terminal (using the split function may be a source of problem, no idea)
2. Display a rather long prompt
3. Resize VSCode window so that the prompt wraps onto the next line

**Comment by SteveZhangBit** [comment]
A related issue for the integrated terminal is that: after maximizing the terminal panel and resizing it, the terminal just freezes. It seems that the terminal process is still alive, but it does not respond to any keyboard input.

- Version: 1.31.1 (user setup)
- Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
- Date: 2019-02-12T02:20:54.427Z
- Electron: 3.1.2
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

Step to reproduce:

1. open an integrated terminal (I'm using WSL on windows).
2. click 'Maximize panel size'.
3. click 'restore panel size'.
4. try type in some command, it does not respond.

**Comment by Tyriar** [comment]
@SteveZhangBit your problem should be fixed in Insiders (and 1.32 when it drops).

@warpdesign what shell do you use?

**Comment by warpdesign** [comment]
@Tyriar: the default one. Bash I believe.

**Comment by Tyriar** [comment]
@warpdesign I believe in 1.31 the prompt line is not affected by reflow at all, so all wrapping logic is handled by the shell. Also other terminals I tested also experience these problems so I think I'm going to close this one as designed.
