### ISSUE TITLE
Search viewlet showing duplicate result

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#69034]
See search results. 2 `main.contribution.ts` files

![image](https://user-images.githubusercontent.com/6561887/53081139-85a28600-34fa-11e9-9a9c-2443583ea8af.png)

**Comment by roblourens** [comment]
- Is that file open?
- If you click each one do you get two tabs of the same file, and if you hover the tab is the location exactly the same (casing, etc)
- Are there any tree errors in the dev tools?

**Comment by sbatten** [comment]
@roblourens as is the case with these, I can no longer repro, but I did check casing and location to be the exact same. Clicking both resulted in the same tab being focused. The file was open already and I didn't check dev tools for errors.
