### ISSUE TITLE
registerAction() should be a reusable thing in vs/platform/actions

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69036]
Looks like there exist almost identical utility methods of `registerAction()` that should use the same thing possibly from `vs/platform/actions`:

* [`markers.contribution.ts#registerAction()`](https://github.com/Microsoft/vscode/blob/058e5e01dc1e85d55ac6f573e65d5efacbbaf1bb/src/vs/workbench/contrib/markers/electron-browser/markers.contribution.ts#L273)
* [`output.contribution.ts#registerAction()`](https://github.com/Microsoft/vscode/blob/058e5e01dc1e85d55ac6f573e65d5efacbbaf1bb/src/vs/workbench/contrib/output/electron-browser/output.contribution.ts#L120)

**Comment by jrieken** [comment]
I think that's from a time *before* we migrated workbench actions onto the new menus/commands world. We should simply adopt that here.

**Comment by jrieken** [comment]
@isidorn for output

**Comment by jrieken** [comment]
@isidorn I ended up moving the `registerAction` function into `common/actions.ts`

**Comment by jrieken** [comment]
I have adopted both places. In a way `registerAction` now competes with workbench actions. The former tho are simpler and don't require to provide an action-class

**Comment by isidorn** [comment]
@jrieken thanks!
