### ISSUE TITLE
"php.validate.executablePath": "/usr/bin/php",

### ISSUE THREAD

**Issue by miguelamello** [Microsoft/vscode#69046]
Issue Type: <b>Bug</b>

Hi There. I am trying to make VS Code to lint PHP, however setting "php.validate.executablePath": "/usr/bin/php" has no effect. PHP is im my path indeed...

[~]$ which php
/usr/bin/php

Cheers

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.20.8-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 1869)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.62GB (0.48GB free)|
|Process Argv|--extensions-dir=/home/miguel/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.10

</details>

**Comment by roblourens** [comment]
You will have to use an extension for that

**Comment by miguelamello** [comment]
Hi. I have found my installation of VSCode from Flathub that was not seeing the PHP in environment path. I just installed VSCode from official download page, and everything is okay now. Thanks.
