### ISSUE TITLE
Coping files in VSC Explorer sometimes dosen't work 

### ISSUE THREAD

**Issue by lukasz21** [Microsoft/vscode#69040]
We have written the needed data into your clipbo
Issue Type: <b>Bug</b>

Since I updated to new version of VSC 1.31.1 the following problem keeps apearing:
When I'm coping files (CTRL + C or using mouse Copy, Paste) in VSC Explorer (tree view) sometimes it dosen't work.  After I close and open VSC it starts to work. Could you please fix it?

===
There is another problem I didn't add. Sometimes when I copy files in Explorer or 'add na new file' VCS doesn't show it in the Explorer (tree view), but after restarting VSC the new file is shown.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3997)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (11.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
vscode-sublime-importer|auc|1.0.1
color-info|bie|0.5.0
file-templates|brp|1.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-faker|dee|1.3.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-todo-plus|fab|4.11.4
seito-openfile|Fr4|1.8.4
macros|ged|1.2.1
beautify|Hoo|1.4.9
minify|Hoo|0.3.0
ftp-simple|hum|0.7.0
compareit|in4|0.0.2
path-autocomplete|ion|1.13.1
ssmacro|joe|0.6.0
vscode-random|jre|1.5.0
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
gulptasks|nic|1.3.1
snippet-creator|nik|0.0.5
material-icon-theme|PKi|3.6.3
vscode-css-peek|pra|2.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
vscode-icons|rob|8.2.0
sass-indented|rob|1.5.1
text-marker|ryu|1.10.0
git-merger|sha|0.4.1
html5-boilerplate|sid|1.0.3
vscode-csstree|sme|0.7.0
open-in-browser|tec|2.0.0
html-css-class-completion|Zig|1.18.0

(6 theme extensions excluded)

</details>
ard because it was too large to send. Please paste.

**Comment by isidorn** [comment]
I can not reproduce any of those issues.
Can you reproduce in vscode insiders https://code.visualstudio.com/insiders/
If yes, please provide **exact** reproducable steps.

**Comment by lukasz21** [comment]
Don't know why but for now VSC works fine. I will write if the issue occurs again.
