### ISSUE TITLE
Open second VSCode from CL - blank screen

### ISSUE THREAD

**Issue by tkivisik** [Microsoft/vscode#69048]
Issue Type: <b>Bug</b>

Replication script explains the situation best:
```bash
cd
mkdir RemovableFolder
cd RemovableFolder
# open the first VS Code from command line
code .
sleep 2
cd ..
# remove the folder the first VS Code was started from
rmdir RemovableFolder
cd
# try to open a second VS Code from a different existing folder
# witness the window open with no content (blank screen)
code .
sleep 2
```

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.18.0-14-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.62GB (7.00GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.3.0
Go|ms-|0.9.2

</details>

**Comment by Tyriar** [comment]
Can repro on mac:

<img width="1228" alt="screen shot 2019-03-05 at 11 50 01 am" src="https://user-images.githubusercontent.com/2193314/53833196-d4114500-3f3c-11e9-80aa-d38042f5b970.png">
