### ISSUE TITLE
Node.JS Debug - Waiting for the debugger to disconnect... after changing directory 

### ISSUE THREAD

**Issue by TurhanG** [Microsoft/vscode#69045]
Debugger was working fine untill I decided to move the workspace to a parent directory. 

Now whenever I decide to start debugging I see this:

Debugger attached.
Waiting for the debugger to disconnect...

Things I have tried:

-Installed Insider version.
-Made sure the paths were correct.
-Ran from the console with npm start, works fine.
-Setted stoponentry to true. (read somewhere that would work)

launch.js file:

![launchjs](https://user-images.githubusercontent.com/32984173/53094780-28bfc380-352c-11e9-8f61-17fd1caab100.PNG)

EDIT: Image of the error.

![capture](https://user-images.githubusercontent.com/32984173/53094839-4db43680-352c-11e9-848d-af2c10d0c3f0.PNG)

**Comment by TurhanG** [comment]
I think I have to post that I have checked other threats. Which I did, and I couldn't find the solution.

**Comment by roblourens** [comment]
It looks like the app ran and finished. Can you explain what you are expecting to happen?

**Comment by TurhanG** [comment]
It does stop at the first line, forgot to mention that, but when I continue debugger gets disconnected.

@roblourens Where is that log file located?

**Comment by weinand** [comment]
@TurhanG and your program is actually long-running? If not, then it is expected that the debugger gets disconnected.

If you use the "trace" option, you can find the log path in the debug console.

**Comment by TurhanG** [comment]
@weinand Sorry I'm not sure what is long-running is. But I guess it isn't since application worked perfectly fine before I moved it to a another directory. (Parent Directory)

This is the log file. (It was too long to paste here)

https://paste.ubuntu.com/p/v7xKmwCPhB/

**Comment by weinand** [comment]
"long running" means that the program does not terminate by itself. So a program consisting of just a simple "console.log('hello')" is not "long running".

**Comment by TurhanG** [comment]
Thanks for the explanation.

Yes it is a long running application.

**Comment by TurhanG** [comment]
I just figured out that this is a Node.js/Express issue. Thank you all for your time.
