### ISSUE TITLE
.js files does not get colored

### ISSUE THREAD

**Issue by MustafaErgul** [Microsoft/vscode#69043]
Issue Type: <b>Bug</b>

Hello, previously i could use vs code perfect with .js files but now editor does not color .js files as it is used to be.

Only white and blue colors are appearing. 

I have already chose Javascript language mode on the right bottom.

Thanks

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.3.9600

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
prettier-vscode|esb|1.8.1
code-runner|for|0.9.7
prettify-json|moh|0.0.3
vscode-duplicate|mrm|1.2.1
python|ms-|2019.1.0
material-icon-theme|PKi|3.6.3

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by MustafaErgul** [comment]
No. When i download insiders build and run without extensions, I do not face with same problem. What about if i want to continue to use regular build of VS code ?

**Comment by mjbvz** [comment]
Try disabling extensions to see which one is causing this or wait for the next VS Code update

**Comment by MustafaErgul** [comment]
just downloaded 1.32 version and still having same problem with coloring js files.
