### ISSUE TITLE
The lastest version use node 10.x, it make some issue in my extension

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#69042]
- VSCode Version:  1.31.1
- OS Version: 10.3.3

The latest version uses the node 10.x version. My extension uses `process.execPath` to execute the script. This script supports the node 8.x version. The version upgrade should be compatible with the previous node version or provide an API to let the user specify the required node version

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
> The version upgrade should be compatible with the previous node version or provide an API to let the user specify the required node version

I don't see that happening, we have to use whatever version of node is built into Electron.

FYI @bpasero
