### ISSUE TITLE
Execute tasks with elevated privileges from non-elevated VS Code

### ISSUE THREAD

**Issue by MaliusArth** [microsoft/vscode#69053]
Yes, this is a duplicate of https://github.com/Microsoft/vscode/issues/64157#issue-386602877
No, it has nothing to do with extensions.

In tasks.json under "runOptions" add the option "runAsAdmin" or "runElevated", enabling the execution of a command which needs to be elevated, e.g. installing/deploying into the /usr/local directory on Linux systems, the default install directory for cmake and generally considered the go to directory for third-party and self-compiled software.

Some reference:
http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/usr.html

**Comment by MaliusArth** [comment]
I have found a workaround:

**Comment by MaliusArth** [comment]
I have found a workaround:

```
{
    "label": "run task elevated",
    "type": "shell",
    "presentation": {
        "focus": true,
    },
    "problemMatcher": [],
    "command": "sudo",
    "args": [
        "<command-to-run-elevated>",
        "<options-and arguments-to-elevated-command>",
    ],
}
```
This focuses the terminal for credential input and executes the command with elevated privileges when the password is correct.

**Comment by alexr00** [comment]
Given that there is a reasonable work around and this issue hasn't gotten any upvotes I'm going to call it out of scope since there will never be any action on it.
