### ISSUE TITLE
Git installation not found - install directory listed

### ISSUE THREAD

**Issue by socratisator** [Microsoft/vscode#69056]
Issue Type: <b>Bug</b>

Install VS Code in "C:\APPLIS\Microsoft VS Code"
Install Git in "C:\APPLIS\Git"
Start VS Code and open folder containing git projet.

- Source Controle panel display : "No source control providers registered"
- "git.path" redefined as "C:\\APPLIS\\Git\\cmd\\git.exe"
- Windows 7 system "Path" including Git directory
- OUTPUT display (after opening the git project directory) :
Looking for git in: C:\APPLI\S\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Users\smaye\AppData\Local\Programs\Git\cmd\git.exe
Looking for git in: C:\APPLIS\Git\cmd\git.exe
Git installation not found.

The right path is listed, but VS code still not acknowledging Git install...

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0
PowerShell|ms-|1.11.0

</details>

**Comment by socratisator** [comment]
Due to typo, the 1st path listed is obviously wrong, the last one otherwise is right.

**Comment by socratisator** [comment]
Also, i tried this :
Let's try something. Hit Ctrl Shift P, type `developer` and select `Developer: Toggle Developer Tools`. In there, go the Console and type `process.env.PATH`
"C:\oracle\ora112030_32b\bin;C:\oracle\ora112030_64b\bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\APPLIS\Microsoft VS Code\bin;C:\APPLIS\Git\cmd;"

**Comment by joaomoreno** [comment]
In your workspace, what does `C:\APPLI\S\Git\cmd\git.exe --status` return?

**Comment by socratisator** [comment]
In cmd windows and in the TERMINAL view of VS Code, "C:\APPLIS\Git\cmd\git.exe --status" returns :
error launching git: Nom de fichier ou extension trop long.
(error launching git: the filename or extension is too long)

**Comment by socratisator** [comment]
Btw I tried setting "core.longpaths=true" but I still got the same error. Git bash working as expected nonetheless.

**Comment by joaomoreno** [comment]
Can you try these steps?

https://stackoverflow.com/a/49080763

**Comment by socratisator** [comment]
I already did actually (that's my comment just above yours) and no improvement.
Should I focus on solving this "error launching git: the filename or extension is too long" error first ?

**Comment by joaomoreno** [comment]
I meant "as Administrator".

In cmd, does `C:\APPLI\S\Git\cmd\git.exe --version` return the same error?

**Comment by socratisator** [comment]
Yes, same error. My guess it's something related to privilege or session but cannot pinpoint it.

**Comment by joaomoreno** [comment]
Yeah. Can you try installing Git on another path?

**Comment by socratisator** [comment]
I sticked to the default install path (C:\Program Files\Git), with all default options using windows installer (Git-2.20.1-64-bit.exe).
Git Bash working fine. Started it as admin and executed "git config --system core.longpaths true".
Opened a cmd console : still the same error (...too long)

**Comment by joaomoreno** [comment]
Not really sure... maybe file an issue on Git's issue tracker? Once you fix that, VS Code will simply follow. StackOverflow would be a good idea as well.

**Comment by socratisator** [comment]
ok, i'll try that. Thanks.
