### ISSUE TITLE
VS Code Insider - Space Indentation

### ISSUE THREAD

**Issue by meeech** [microsoft/vscode#69051]
Issue Type: <b>Bug</b>

Hi

I seem unable to set the indentation when spaces. It seems stuck on whatever value it opens with (and in one file the is incorrect) As far as i can tell, I do not have auto detect enabled. I have also confirmed with all extensions disabled. This is in a .py file. Let me know what other info I can provide.
Everything works fine when I launch VS Code regular edition.
Thanks

VS Code version: Code - Insiders 1.32.0-insider (aeaef41d51201e555735f5e8d2f38a9d0ddb9026, 2019-02-20T06:14:30.644Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by hardjonn** [comment]
I have the same issue. And I was forced to disable the editor.formatOnSave option because it works unpredictably now

**Comment by greggilbert** [comment]
I opened #69185, which I think is the same bug as this.

**Comment by greggilbert** [comment]
@meeech @hardjonn Do you have a workaround for this yet? I think I'm going to have to drop back down to the stable version. :(

**Comment by meeech** [comment]
@greggilbert no workaround that i know of. just patience :D

**Comment by hardjonn** [comment]
@greggilbert @meeech Hey, I've just checked this out and it seems like it's working now. At least for me (Windows 10x64)

**Comment by greggilbert** [comment]
@hardjonn: Same here, actually on OSX (1.32.0-insider, 52306b406d9231a0667c758e536bd177e5570180)

**Comment by rebornix** [comment]
Could you please provide code/file sample which can reproduce this issue?
