### ISSUE TITLE
Ubuntu: When used as git editor, always opens a new window, even when initiated from integrated terminal

### ISSUE THREAD

**Issue by outoftime** [Microsoft/vscode#69052]
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:

1. From an integrated terminal, invoke `GIT_EDITOR='code --wait' git commit --allow-empty`
2. Expect that a new editor tab will open in the current window (this is the behavior on Mac OS)
3. Observe that a new window opens with the commit message editor open
4. Note that this happens even when the `--reuse-window` option is supplied

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by outoftime** [comment]
@bpasero I cannot reproduce the issue on Code Insiders, but I have switched to Arch Linux since originally reporting the bug. The bug does not happen on the [stable release](https://aur.archlinux.org/packages/visual-studio-code-bin/?O=10&PP=10) of Code on Arch either.
