### ISSUE TITLE
Visual studio code - Intellisense auto complete behaviour

### ISSUE THREAD

**Issue by sakthirajesh** [Microsoft/vscode#6905]
- VSCode Version: 1.1.1
- OS Version: Windows 7 x64

I'm pretty new to Visual studio code. I am using Visual studio code for AngularJS application development. As I am from a .NET development background, I'm much fond of intellisense feature in visual studio code. But I could feel something is missing in this. When I type any Object name, autocomplete box pops up with suggestion, when I select the respective item and press period, the object name is not complete. Example: assume the object name is SampleObject. When I start typing "Sam", suggestion pop up lists "SampleObject". Once I select this name and press period, the output is "Sam." and not as "SampleObject." Any setting has to be added for the expected behaviour? Your help is much appreciated.
![screenshot](https://cloud.githubusercontent.com/assets/19584295/15564551/0c1ec5d8-2331-11e6-814e-66b6e86c2b18.jpg)

**Comment by jrieken** [comment]
@sakthirajesh You can add the snippet below to your keyboard shortcut configuration to the VS Code to accept a suggestion _and_ insert the dot when pressing `.`

```
{ "key": ".",                     "command": "^acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible && suggestionSupportsAcceptOnKey && editorLangId == 'javascript'" },
```

**Comment by sakthirajesh** [comment]
Thanks. This settings worked.

**Comment by dbaeumer** [comment]
OK. Closing then.
