### ISSUE TITLE
Multilayer folder files are generated

### ISSUE THREAD

**Issue by liuhaoxin10** [Microsoft/vscode#69058]
Issue Type: <b>Feature Request</b>

When open a folder that contains multiple folders, execute the generated file on the secondary task, the file will not generate secondary folder, folder will be generated in level, set up as if there is no such option can be changed

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by Tyriar** [comment]
It sounds like you're having problems with a script that created folders in the wrong level? This doesn't sound like a vscode problem?

**Comment by liuhaoxin10** [comment]
When writing a c + +, open one level, may contain multiple secondary directory, when compiling c + + in the secondary directory file, compile the file will be generated in the directory, I mean, can you change in the set

**Comment by Tyriar** [comment]
Report against https://github.com/Microsoft/vscode-cpptools if you have an issue with C++ support
