### ISSUE TITLE
Allow to configure that "Go to symbols" sorts symbols by fuzzy match

### ISSUE THREAD

**Issue by nachocab** [microsoft/vscode#69062]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/27538/53104957-8f46e080-3530-11e9-9773-28bd2b1a1e78.png)

In the above screencapture I'm opening the "Go to Symbol" panel and I'm typing "Memento" in a markdown file, you can see by the scrollbar that there are many other entries suggested before the "Memento" perfect match. I tried playing with the `symbolOutline.sortOrder` and `doSort` but it didn't do anything.

Is there a way to prioritize perfect matches in this panel?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|-psn_0_159783|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
replace-smart-characters|DrM|0.0.2
output-colorizer|IBM|0.1.2
rmd|nac|0.0.1
vscode-paste-and-indent|Rub|0.0.8
html-snippets|abu|0.2.1
Bookmarks|ale|10.2.2
snapshot-tools|asv|0.2.2
unique-lines|bib|1.0.0
vscode-tailwindcss|bra|0.1.16
vscode-selection-extended|cg-|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
transformer|dak|1.6.0
vscode-eslint|dba|1.8.0
vscode-quick-select|dba|0.2.7
githistory|don|0.4.6
gitlens|eam|9.5.1
sort-lines-by-selection|ear|0.0.3
graphviz-preview|EFa|1.3.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
php-debug|fel|1.12.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
macros|ged|1.2.1
graphviz-markdown-preview|gee|0.0.7
pug2html|gin|0.0.5
gc-excelviewer|Gra|2.1.29
vscode-import-formatter|hen|0.1.8
githd|hui|2.1.0
nbpreviewer|jit|1.2.2
vscode-styled-components|jpo|0.0.25
nearley|kar|1.0.3
wordcounter|kir|1.4.0
graphql-for-vscode|kum|1.13.0
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
python|ms-|2019.1.0
debugger-for-chrome|msj|4.11.2
highlight-dodgy-characters|nac|1.0.0
nacho|nac|0.1.0
run-external|nac|0.1.2
select-paragraph|nac|0.1.1
color-highlight|nau|2.3.0
vetur|oct|0.16.1
vscode-code-outline|pat|0.2.1
material-icon-theme|PKi|3.6.3
markdown-preview-theme-one-dark|rae|0.0.1
subtle-brackets|raf|3.0.0
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.0
exchange-selection-start-end|san|2.0.0
vscode-sass-format|sas|1.1.6
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.2.5
markdown-preview-enhanced|shd|0.3.11
vscode-fileutils|sle|2.13.5
vscode-hexdump|sle|1.7.2
guides|spy|0.9.3
delayedcommand|sqr|1.0.1
dot|Ste|0.0.1
rewrap|stk|1.9.1
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
hipsum|thi|1.0.7
tmlanguage|Tog|0.9.0
vscode-input-sequence|tom|0.2.0
wordpress-snippet|tun|1.1.5
sort-lines|Tyr|1.8.0
es-quotes|vil|0.2.6
vscode-react-native|vsm|0.8.0
gitblame|wad|2.6.3
wallaby-vscode|Wal|1.0.114
change-case|wma|1.0.0
cursor-align|yo1|1.0.4
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
I think it's the designed of quick open not to resort while typing...

**Comment by bpasero** [comment]
@jrieken @nachocab each quick open handler can do the sorting as they like but in this case, "Go to symbol in file..." never sorts the results actually because we want to preserve the order as the symbols appear in the document. E.g. you can arrow up/down and we reveal the location in the editor in the order of appearance.

**Comment by nachocab** [comment]
Having a setting for that would be great. Thanks!

**Comment by jrieken** [comment]
<img width="642" alt="Screenshot 2019-10-08 at 18 23 34" src="https://user-images.githubusercontent.com/1794099/66413960-bf2bf100-e9f8-11e9-8265-eca3b2a77f9b.png">


I actually recently changed this... Quick outline is now resorted, no one complained so let's skip the option and keep this ;-)
