### ISSUE TITLE
Workspace Tree does not refresh after creating files/folders within VSCode

### ISSUE THREAD

**Issue by JLewis1** [Microsoft/vscode#69068]
Issue Type: <b>Bug</b>

When I create files and folders inside VSCode in my Workspace, the tree does not refresh until I restart the program.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.68GB (2.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.3
jsrefactor|cms|2.15.1
angular2-snippets|dan|1.0.21
jshint|dba|0.10.20
vscode-eslint|dba|1.8.0
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.5.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
bootstrap-4-cdn-snippet|eve|1.1.5
mithril-emmet|Fal|0.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
webpack-snippets|gog|0.0.4
beautify|Hoo|1.4.9
animate-css|Hri|1.0.0
vscode-lebab|jer|1.0.4
webpack|jer|2.1.3
Angular1|joh|0.2.0
Angular2|joh|7.0.1
auto-comment-blocks|kev|1.0.1
console-log-snippet-javascript|lev|0.1.0
angular1-code-snippets-johnpapastyle|lpe|0.1.0
font-awesome-codes-css|med|0.1.1
font-awesome-codes-html|med|0.0.7
Angular-BeastCode|Mik|7.2.2
vscode-scss|mrm|0.6.2
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.2
JavaScriptSnippets|nat|0.2.0
snippet-creator|nik|0.0.5
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|3.6.3
easy-compile|ref|1.1.3
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1
css-auto-prefix|spo|0.1.7
vscode-gulp|tan|0.0.4
bootstrap4-vscode|the|6.0.3
shell-launcher|Tyr|0.3.0
vscode-jss-snippets|vis|0.2.2
bootstrap-3-snippets|wcw|0.1.0
vsc-jsonsnippets|wmo|0.1.4
JavaScriptSnippets|xab|1.7.2
gulp-run|yod|0.0.2

</details>

**Comment by isidorn** [comment]
Can not repro, also tehre are already issues for this. So just search for issues assigned to me with tag file-explorer if you want to find them.
Also let me know if you have 100% repro steps

**Comment by alexander-zolotykh** [comment]
Same issue, steps:
- New file from context menu on parent-folder
- write `folder-name/file-name`, enter
- parent-folder doesn't contain `folder-name/file-name` visually

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68204
