### ISSUE TITLE
Unable to save file without extension

### ISSUE THREAD

**Issue by deltatriple** [Microsoft/vscode#69065]
Issue Type: <b>Bug</b>

When trying to save a file locally, I am unable to save it without an extension. I work with Pick Basic and programs, text or binary, don't have extensions (i.e. "SEND_MAIL"). Currently I have to save a file locally with a .txt extension, then rename it and reopen it.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|5.95GB (1.58GB free)|
|Process Argv|C:\Users\dholte\OneDrive - 1MAGE SOFTWARE INC\Dev Content\SEML\cURL.txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.1
pick|Tra|1.1.2

</details>

**Comment by cwdaniel** [comment]
@deltatriple How are you saving the file? When I `save as` I have an option named "No Extension (*.)" which allows me to save a file as SEND_MAIL. Can you test it out and update whether you are able to save? Thanks! Also, can you please close #69069 as it's a duplicate to this question. 
![image](https://user-images.githubusercontent.com/16778973/53118069-497f1d80-351a-11e9-88d2-ea171de442a5.png)

![image](https://user-images.githubusercontent.com/16778973/53118048-38361100-351a-11e9-8acb-e3dd39b3d174.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/69069
