### ISSUE TITLE
FortiClient sees Ruby VSC extension as a threat

### ISSUE THREAD

**Issue by MonsieurDart** [microsoft/vscode#69060]
I don't know if this is relevant here, but my anti virus thinks the Ruby VSC extension contains a threat:

https://github.com/rubyide/vscode-ruby/issues/432

**Comment by wingrunr21** [comment]
Update on this:

Looks like something on the Marketplace side automatically pulled the version. I figured out where it was coming from and will push a corrected release for it later tonight.

**Comment by wingrunr21** [comment]
@Tyriar @rebornix full details are in the `vscode-ruby` issue

**Comment by MonsieurDart** [comment]
BTW, maybe it could be nice to update the blog post listing the problematic packages with the infected version of the Ruby ext?
