### ISSUE TITLE
Enable Hover: sticky on RGB Color picker only

### ISSUE THREAD

**Issue by charbelnicolas** [microsoft/vscode#69066]
Issue Type: <b>Feature Request</b>

As of right now if you disable Hover: Sticky in the preferences, you lose the ability to select a color on the RGBA color picker pop-up.

Please enable Hover: sticky by default on the color picker pop up or let us click on the small colored square for a color selector window pop-up.

This is a must, because by default, Hover: sticky makes for some annoying tooltips and must be disabled.

Thank you, I really hope you consider this.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

**Comment by davidlower8** [comment]
I would like to +1 this feature. What is the status of this feature being added, if any.
Thanks.

**Comment by aiday-mar** [comment]
I believe this issue has been resolved in previous iterations earlier this year. This issue will be closed. 

https://github.com/microsoft/vscode/assets/61460952/69cfee6f-45aa-445a-b8e9-b4e1c52fc580

**Comment by charbelnicolas** [comment]
Four years to fix something as crucial as a color picker, thank god I migrated to neovim a few years ago.
