### ISSUE TITLE
Unable to save file without extension

### ISSUE THREAD

**Issue by deltatriple** [Microsoft/vscode#69069]
Issue Type: <b>Bug</b>

When trying to save a file locally, after it has been opened from another source, I am unable to save it without an extension. I work with Pick Basic and programs, don't have extensions (i.e. "SEND_MAIL"). Currently I have to save a file locally with a .txt extension, then rename it and reopen it.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|5.95GB (1.58GB free)|
|Process Argv|C:\Users\dholte\OneDrive - 1MAGE SOFTWARE INC\Dev Content\SEML\cURL.txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.1
pick|Tra|1.1.2

</details>

**Comment by isidorn** [comment]
This works for me. Forwarding to @bpasero

**Comment by bpasero** [comment]
On Windows you have to pick "Save without extension" from the dropdown.

**Comment by deltatriple** [comment]
I tried using the dropdown for 'All Files (*)', but I still can't save:
![image](https://user-images.githubusercontent.com/13327474/53184164-cca38080-35b9-11e9-9361-28ad5998378c.png)

Is there another selection I need?

**Comment by deltatriple** [comment]
I did find that any '.' in the filename would permit it to be saved, so 'GGIME.somethingORanything' would be permissible, while 'GGIME' is not.
