### ISSUE TITLE
Opening file with Ctrl + P opens file but doesn't reveal its location in the sidebar

### ISSUE THREAD

**Issue by Quest-AliHassan** [Microsoft/vscode#69073]
- VSCode Version: 1.31.1
- OS Version: Windwos 10

Steps to Reproduce:
This is tough to reproduce and happens some of the times after using VS Code for quite some time.

1. Press Ctrl + P, open a file.
2. The file opens but the sidebar is still highlighting the last opened file.

Continuing to open files with Ctrl + P does not jump to the new file's location. I noticed this happening recently.

Does this issue occur when all extensions are disabled?: Yes/No

Did not try this because it happens some of the times.

**Comment by Quest-AliHassan** [comment]
![vscodebug](https://user-images.githubusercontent.com/35071563/53124956-bc909000-352a-11e9-8678-e1f1e69036ae.gif)

It happens after having it open for some time, only way to fix it is to restart.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68627
