### ISSUE TITLE
Use non-nullable types in vscode.d.ts

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6907]
TypeScript will introduce support for strict null check and explicit handling of `null` and `undefined` - https://github.com/Microsoft/TypeScript/pull/7140. This is a great opportunity for us to make the API more explicit and hopefully a chance to prevent programming errors. Parts of the API can move from _jsdoc_ comments into type annotations. For instance, the active editor is declared like this today:

```
/**
 * The currently active editor or `undefined`. ...
 */
export let activeTextEditor: TextEditor;
```

and we can move _jsdoc type info_ back into code like so

```
/**
 * The currently...
 */
export let activeTextEditor: TextEditor | undefined;
```

**Comment by jrieken** [comment]
depends on https://github.com/TypeStrong/typedoc/issues/234

**Comment by jrieken** [comment]
@egamma @dbaeumer  Looking for some guidance here. Challenge is that many of the providers define method return types ala `Foo | Thenable<Foo>`. The current behaviour (spec'd in jsdoc) is that they are allowed to return `undefined` or `null` sync or async from with in the promise. That results in the following, very verbose, strict-null-aware signature:

```ts
// option 1a, inline
interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): CodeLens[] | undefined | null | Thenable<CodeLens[] | undefined | null>
}

// option 1b, inline but even more verbose
interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): CodeLens[] | undefined | null | Thenable<CodeLens[]> | Thenable<undefined> | Thenable<null>
}

// option 2, generic result-type
type Result<T> = T | undefined | null | Thenable<T | undefined | null>
	
interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): Result<CodeLens[]>
}
	
// option 3, generic nullable-type
type Nullable<T> = T | undefined | null;	
	
interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): Nullable<CodeLens[]> | Thenable<Nullable<CodeLens[]>>
}

```

Options 2 and 3 have the advantage that they can be applied to all providers and make a shorter method signature. On the downside that add another indirection and might make things harder to understand... Tho, also option 1 isn't exactly easy to read and understand

**Comment by jrieken** [comment]
Actually, I forgot option 1c which uses type that combines `undefined` and `null`

```ts

	type Nully = null | undefined;

	interface CodeLensProvider {
		provideCodeLenses(document: TextDocument, token: CancellationToken): CodeLens[] | Nully | Thenable<CodeLens[] | Nully>
	}
```

**Comment by dbaeumer** [comment]
@jrieken hard call: I would actually go for 2.) and name it ProviderResult. Using Nullable<T> makes it bound to nullable. If TS comes up with another feature we might need to change the signature again. With ProviderResult we might be able to simple change that type then.

**Comment by dbaeumer** [comment]
@jrieken hard call: I would actually go for 2.) and name it ProviderResult. Using Nullable<T> makes it bound to nullable. If TS comes up with another feature we might need to change the signature again. With ProviderResult we might be able to simple change that type then.

**Comment by dbaeumer** [comment]
@jrieken hard call: I would actually go for 2.) and name it ProviderResult. Using Nullable<T> makes it bound to nullable. If TS comes up with another feature we might need to change the signature again. With ProviderResult we might be able to simple change that type then.

**Comment by bpasero** [comment]
+1 for option 2 (`generic result-type`)

**Comment by joaomoreno** [comment]
I'd combine 2 and 3, each a different problem in itself, but composable with each other:

```ts
type Maybe<T> = T | undefined | null;
type Result<T> = Maybe<T> | Thenable<Maybe<T>>;

interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): Result<T>;
}
```

**Comment by aeschli** [comment]
Wanted to suggest Optional<T> but actually like Maybe<T> even better.
+1 for option 3 with Maybe<T>.
I'd rather not combine it with 2, too many types, and, especially, 'Result' is too general.

**Comment by joaomoreno** [comment]
```ts
type Eventually<T> = Maybe<T> | Thenable<Maybe<T>>;
```

😄

**Comment by chrmarti** [comment]
Keeping the two concepts separate might be easier to read and would allow for more variants of reuse:
```ts
type Maybe<T> = T | undefined | null;
type Eventually<T> = T | Thenable<T>;

interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): Eventually<Maybe<CodeLens[]>>;
}
```

**Comment by jrieken** [comment]
Just as a reminder - We aren't just targeting TypeScript-ninjas but also folks that haven't seen a type annotation before. 

From my experience, even things like OR-types aren't fully understood/made use of so I am not so sure if a 'double nested generic or-type' is the way to go.

**Comment by sandy081** [comment]
+1 for option 3

```
type Nullable<T> = T | undefined | null;

interface CodeLensProvider {
  provideCodeLenses(document: TextDocument, token: CancellationToken): Nullable<CodeLens[]> | Thenable<Nullable<CodeLens[]>>
}
```

IMO, this makes it API more readable for all kinds of users with out many references. In fact, Nullable<T> is a bit straight so that user do not need to look for its reference.

**Comment by chrmarti** [comment]
+1 for option 3 then (don't hurt the ninjas!)

**Comment by alexandrudima** [comment]
+1 for option 2 with a different name for `Result`, such as `ProviderResult`.

Reasons:
* It reduces the burden of reading each and every provider signature, `CodeLens[]` only appears once
* It makes that I need to understand only one more concept (i.e. no need to follow through to look up two new concepts `Eventually` and `Maybe`)

**Comment by jrieken** [comment]
@Mircorsoft/vscode I am looking for volunteers that migrate their extensions to use `strictNull`-checks such that we can verify our API

**Comment by weinand** [comment]
@jrieken how do I migrate my extension?

**Comment by jrieken** [comment]
@weinand  - to program against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2

*note* tho that this no also depends on TypeScript 2.0

**Comment by weinand** [comment]
@jrieken done. That was easy.
But I have to set `"strictNullChecks": true`in my tsconfig.json so that the compiler actually checks for this.

**Comment by ramya-rao-a** [comment]
@jrieken The test item #16515 is linked here, but the test item does not have anything on non-nullable types.

**Comment by jrieken** [comment]
@ramya-rao-a This was meant for `verification-needed` but I have special verifier in mind: those that have already updated their extensions to use strict null checks. I have @mjbvz (ts/js) and @joaomoreno (git exploration) in mind
