### ISSUE TITLE
[folding] Add setting to allow to show first N lines (not 1) of folded block

### ISSUE THREAD

**Issue by 4mitch** [microsoft/vscode#69078]
During work with XML files I usually want to fold all complex elements of one type. And normally each of them has some ID element at the first-two position inside it.

At the moment I move such ID tags in one line with parent tag - to be able to see it when complex element is folded. But I'd like to have setting which allow me to show first N lines of each folded region. 
May be language dependent.

**Comment by aeschli** [comment]
I think the right approach is if we allow folding providers to define a custom text for the folded line: #70794. That way it can contain a summary that contains tags and id.
