### ISSUE TITLE
Error hover text too small not very readable

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69070]
Insiders:

![image](https://user-images.githubusercontent.com/4033249/53116652-07e07980-34fe-11e9-98b8-fd5ed32721b1.png)

Stable:

![image](https://user-images.githubusercontent.com/4033249/53116697-1d55a380-34fe-11e9-8fee-89990705a801.png)

**Comment by beastdestroyer** [comment]
Also noticed for insiders where it says 'error' and 'any', should me monospace since it's direct reference to code?. Then again it does say it after..

**Comment by sandy081** [comment]
It is because of using normal font. It was only for short time and now I am using the editor font again.
