### ISSUE TITLE
How to fix the issue that different editors have different lines count?

### ISSUE THREAD

**Issue by Imputes** [Microsoft/vscode#69075]
I found an issue, in macOS, I used Vim to insert 5 blank lines in a file and save this file, then I used vscode to read this file, I found this file has 6 blank lines.

And I used vscode to insert 5 blank lines in a file and save this file, then I used Vim to read this file, I found this file has only 4 blank lines. And I used wc -l command line in this file, it showed this file has 4 blank lines.

I tried to download a file in the GitHub, and this file has 81 lines and has no blank line in the end of file, after download, I used Vim to read this file, it showed this file has 81 lines, but I used vscode to read this file, it showed this file has 82 lines, because there has a new blank line in the end of file.

How to fix this issue?

**Comment by Tyriar** [comment]
I think vim always inserts an empty line at the end and doesn't show it:: https://stackoverflow.com/a/16114535/1156119

For the last part you probably exited using `:wq`, not `:q`.

**Comment by Imputes** [comment]
@Tyriar Please tell me how to don't render this blank line, just like Emacs.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/69143#issuecomment-466065732
