### ISSUE TITLE
terminal misbehaving on powershell

### ISSUE THREAD

**Issue by MohakChugh** [Microsoft/vscode#69072]
Issue Type: <b>Bug</b>

On pressing the ctrl + ` key, the terminal opens.
But when powershell is set to default terminal, it shows a blank screen until i start to type on it.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (4.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.26
c-cpp-compile-run|dan|0.4.3
CppSnippets|har|0.0.13
vscode-gnu-global|jay|0.2.6
cpptools|ms-|0.21.0
material-icon-theme|PKi|3.6.3

(2 theme extensions excluded)

</details>

**Comment by AlQuraian** [comment]
Related #57803

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
