### ISSUE TITLE
High Contrast Theme Selection Does Not Highlight

### ISSUE THREAD

**Issue by SethRzeszutek** [microsoft/vscode#69077]
When you are previewing high contrast themes and using the down and up arrow to see them. The High Contrast selections are not highlighted.
Example:
![vscode-bug](https://user-images.githubusercontent.com/23585575/53122310-49841b00-3524-11e9-9d2f-129f13f3d42d.gif)

**Comment by SethRzeszutek** [comment]
Bad bot, this is unrelated to those.

**Comment by aeschli** [comment]
Looks like the quick picker doesn't render the high contrast selection border

**Comment by MagTun** [comment]
Is there a way to solve this?

I tried manny settings like `"menu.selectionBackground", "selection.background", "list.activeSelectionBackground", "editor.selectionBackground": "#758df7", "terminal.selectionBackground"` but none of them worked.
