### ISSUE TITLE
Bottom Panel visibility

### ISSUE THREAD

**Issue by FlavienBusseuil** [microsoft/vscode#69074]
I'm writing an extension and I'm struggling with toggling the bottom panel though the API.

I'm able to `hide()` or `show()` a terminal that leads to open and close the panel, but there is no `toggle()` feature or a way to test terminal or panel visibility to call either `hide` or `show`.

I saw that the Panel object has a `visible` member, but I can't find a way to access the panel instance through the API.

**Comment by Tyriar** [comment]
Why do you want to test visibility or toggle?

**Comment by FlavienBusseuil** [comment]
Giving a bit more of context here:

I'm adding a `StatusBarItem` that watch some terminal activity based on keywords. When user click on the StatusBarItem, it shows the terminal. I would like to hide the terminal with the same action instead of clicking the X.

![feb-21-2019 09-29-12](https://user-images.githubusercontent.com/5766884/53176014-34a69680-35bb-11e9-8824-3df3491ea79c.gif)

In order to achieve that I need to know if panel is already visible or not (or a toggle API that would handle it for me).

Note that exactly the same behaviour that the error/warning built-in problems watcher StatusBarItem.

**Comment by albelin** [comment]
Hi, I am looking to contribute to the repo and this issue looked interesting. Is there a specific file to look into/edit to begin?

**Comment by isidorn** [comment]
We currently do not accept PRs in this area.
Please search for issue tagged with `help-wanted`. Thank you
