### ISSUE TITLE
[json] $ref breaks validation of additionalItems

### ISSUE THREAD

**Issue by openreply-dleinhaeuser** [microsoft/vscode#69071]
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Create a JSON-Schema where a `$ref` is used inside `additionalItems`
```json
{
  "type": "array",
  "items": [
    {
      "type": "string"
    }
  ],
  "additionalItems": {
    "$ref": "#/definitions/Number"
  },
  "definitions": {
    "Number": {
      "type": "integer"
    }
  }
}
```
2. Create a JSON file where the additional items in the array do not conform to the schema
```json
[
  "A string",
  "Definitely not an integer"
]
```
3. Set VSCode up to validate the JSON file against the schema

Expected result:

Squiggly lines below the second item in the array.

Actual result:

JSON file passes validation

Does this issue occur when all extensions are disabled?: Yes

**Comment by paillave** [comment]
Any news about this bug?
