### ISSUE TITLE
Unable to write program user data. Please make sure XXX/Code is writeable. 

### ISSUE THREAD

**Issue by autohub7** [Microsoft/vscode#69084]
- VSCode Version: 1.31.1 
- OS Version: macOS Mojave (10.14.3)

Steps to Reproduce:

1. Download Visual Studio Code Mac Version on the official side. 
2. Received a message 'unable to write program user. Please make sure the directory xxx/Code is writeable'
3. chmod -777 xxx/Code and confirmed that it has read/write access (terminal & directory info). 
4. Received the same error message. 
5. Created new mac user account. Downloaded and installed Visual Code. It worked with this new user account. 
6. Went back to my main user account on Mac. Tried it again, then it failed with the same message. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
This sounds like a problem with your configuration and not VSCode.

**Comment by autohub7** [comment]
> This sounds like a problem with your configuration and not VSCode.

Any clue on the issue? I recently bought a new Macbook and transferred all the files including system configurations from my old Macbook. I gave a write/read permission to XXX/Code as the warning message showed

**Comment by lsl** [comment]
@autohub7 per https://github.com/Microsoft/vscode/issues/68744#issuecomment-469546491 you might want to check perms elsewhere, it could be a ~/.vscode/extensions folder that had its permissions messed with during the migration as well.

**Comment by thebarbershop** [comment]
I had the same issue on a newly-installed Ubuntu 18.04, code installed by `sudo apt install code` wouldn't open with the same message. Got over by removing the folder indicated by the error message (it was ~/.config/Code) and re-installing.
