### ISSUE TITLE
can not connect to Extensions ...

### ISSUE THREAD

**Issue by zhongzhong0505** [Microsoft/vscode#69087]
- VSCode Version: 1.32.0-insider 
- OS Version: macOS 10.14.3 

Steps to Reproduce:

1. switch to Extension window
2. search something..

![image](https://user-images.githubusercontent.com/15847574/53135338-d2976280-35b5-11e9-96bc-92dce623e26d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@zhongzhong0505 Are you behind any network proxies?

**Comment by zhongzhong0505** [comment]
@sandy081  emmm, yes ,but vscode release version is work, insides version not.

**Comment by chrmarti** [comment]
@zhongzhong0505 What kind of proxy is it? What's in your OS' proxy settings? Related: #68843

**Comment by zhongzhong0505** [comment]
@chrmarti  Same iMac computer, same network, the release version work , insides version not work.
Is proxy problem?
