### ISSUE TITLE
Script tag closing color

### ISSUE THREAD

**Issue by Nothing-Works** [Microsoft/vscode#69085]
- VSCode Version: 1.31.1
- OS Version:Win_64 
![1](https://user-images.githubusercontent.com/18606648/53134427-fbcae980-35db-11e9-98f7-21b60bd4c94a.png)

anyone have the same issue?

**Comment by Nothing-Works** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Colors in PHP in script tags (#65649)](https://www.github.com/Microsoft/vscode/issues/65649)

it's not php though

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by Nothing-Works** [comment]
very sorry, this is  [Sublime Babel plugin](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) issue. there is nothing to do with vscode
