### ISSUE TITLE
Incorrect search results after applying a multiline search and replace

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#69082]
- VSCode Version: 1.31.1
- OS Version: Windows

Steps to Reproduce:

1. Open the [visualstudio-docs repo](https://github.com/MicrosoftDocs/visualstudio-docs) at the docs/vsto folder. 
2. Try the multiline search:

```
(- \[(.)*)
*\s?[^-]*\s?[^-]*\[
```
replacing with 
```
$1
- [
```
Should see 32 results in 27 files.

3. Replace All and run the search again.

There are now 2 results in 11 files. 

4. Try to open one of the Search result files which didn't have a match. 

The search results twisty changes but no file or results opens

**Comment by gewarren** [comment]
Thanks for logging it Greg!

**Comment by gewarren** [comment]
Note that the search is a RegEx search.
