### ISSUE TITLE
进行C#扩展后，运行C#程序出错

### ISSUE THREAD

**Issue by airenXiao** [Microsoft/vscode#69088]
输出信息：OmniSharp server started.
    Path: C:\Users\gm941600\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 16140

ϵͳ�Ҳ���ָ����·����

使用F5运行项目时：Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' Failed to download from https://download.visualstudio.microsoft.com/download/pr/515dbb33-d644-4ba6-9ee4-8ca7227ab580/bdfde5788994e381c9a3efe5777081bd/omnisharp-win-x64-1.32.8.zip. Error code '407')
	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.32.8.zip' Failed to download from https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.32.8.zip. Error code '407')
Failed at stage: downloadAndInstallPackages
407

**Comment by ljporljp** [comment]
It's obviously your net connection problem(the error 407).

**Comment by abbychau** [comment]
propose to close this one.

**Comment by airenXiao** [comment]
Thank you for your help. Is this error due to the agent? This problem prevents me from using VS Code。

**Comment by abbychau** [comment]
@airenXiao try to get helps in https://github.com/OmniSharp/omnisharp-vscode
