### ISSUE TITLE
Only use tab or enter to commit autocompletion

### ISSUE THREAD

**Issue by Geon-Gyu** [Microsoft/vscode#69093]
I prefer visualstudio-like autocompletion style to vsc-style.

In Visual Studio 2017, whenever I type certain character (dot, parenthesis, space) Visual Studio autocompletes to what I selected.

Taking intelliJ, It can be controlled in Preference Settings. You can check "Insert selected suggestions by pressing space, dot, or other context-dependent keys"

But I can't find this in any settings on Visual Studio Code.

It seems that It doesn't support this feature.

Are there any workarounds?

If not, please add this feature for someone like me!

**Comment by jrieken** [comment]
Do you mean the `editor.acceptSuggestionOnCommitCharacter` setting?
