### ISSUE TITLE
Hover text on a problem shows "undefined" when source is set on the corresponding diagnostic 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#69091]
Below is a screenshot of a linting error when using the Go extension

![default](https://user-images.githubusercontent.com/6797881/53017682-9d79fb80-3461-11e9-879a-5742bd3014f5.png)

The source on the diagnostic is set to "go-lint" as seen in the Problems view.
The hover text has "undefined" though.

cc @inliquid

**Comment by sandy081** [comment]
@ramya-rao-a I cannot repro it with other languages (TS). It would be great if you can provide me steps to repro.

**Comment by ramya-rao-a** [comment]
Use the below in the `activate` function of your extension

```
    const diagnosticCollection = vscode.languages.createDiagnosticCollection('boo');
    context.subscriptions.push(diagnosticCollection);
    vscode.window.onDidChangeActiveTextEditor(() => {
        diagnosticCollection.clear();
        const diagnostic = new vscode.Diagnostic(new vscode.Range(0,0,0,0), "Dummy error", vscode.DiagnosticSeverity.Error);
        diagnostic.source = "my-source";
        diagnosticCollection.set(vscode.window.activeTextEditor.document.uri, [diagnostic]);

    }, null, context.subscriptions);
```

**Comment by sandy081** [comment]
Thanks @ramya-rao-a for the steps. Fixed.

**Comment by ramya-rao-a** [comment]
Thanks @sandy081 

@inliquid You should be able to see the fix on Monday's [Insiders](https://code.visualstudio.com/insiders) build
