### ISSUE TITLE
extension file issue

### ISSUE THREAD

**Issue by SachinGaura** [Microsoft/vscode#69098]
Issue Type: <b>Bug</b>

i am not able to add extension file on visual studio whenever i am apllying for extension error showing.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.87GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --open-url -- vscode:extension/ms-azure-devops.azure-pipelines|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Can you clarify what you mean by extension file? A screenshot might help explain.
