### ISSUE TITLE
code --list-extensions-json, --list-extensions-enabled, --list-extensions-disabled

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode#69090]
I want to quickly save my list of extensions so that I can resolve an issue.

It does not work because `--list-extensions` loses all status of Disabled / Enabled.

When I restore the `extensions.list` file, the VS Code installation gets blown up, because all disabled extensions are now enabled, startup is freezing, multiple versions of language extensions are now conflicting, etc.

It would be very helpful to work with extensions if we had:
- `--list-extensions-json`
- `--list-extensions-enabled`
- `--list-extensions-disabled`
- `--install-extensions-json`
- `--install-extension-disabled`

**Comment by sandy081** [comment]
> I want to quickly save my list of extensions so that I can resolve an issue.

May I know the reason behind to save and what you are trying to do?

**Comment by Yzrsah** [comment]
@sandy081 

- I have different extensions installed, like *Sublime Babel* and *Babel JavaScript*, but only one of them is enabled.
- I have different versions of extensions *vs* forked versions installed, like *Prettier*, *Prettier-MyForkedVersion*, but only one of them is enabled.
- I do not want to login or receive notices about certain services when we are not working on them, so they are currently disabled.
- Some extensions have a bug or performance issue, so they are disabled. I.e. "Node.js REPL" - this is a great extension, but it's disabled at the moment.
- You ask me to respond with `needs more info` to something like "Initializing JS/TS Language Features..." which requires me to test with *"all extensions disabled"* - but I cannot do that without spending the next hours of configuration / re-configuration
- Because in the process of checking & testing the setup, the Disabled list is lost every time

**Comment by Yzrsah** [comment]
@sandy081 

- I have different extensions installed, like *Sublime Babel* and *Babel JavaScript*, but only one of them is enabled.
- I have different versions of extensions *vs* forked versions installed, like *Prettier*, *Prettier-MyForkedVersion*, but only one of them is enabled.
- I do not want to login or receive notices about certain services when we are not working on them, so they are currently disabled.
- Some extensions have a bug or performance issue, so they are disabled. I.e. *Node.js REPL* - this is a great extension, but it's disabled at the moment.
- You ask me to respond with `needs more info` to an issue like "Initializing JS/TS Language Features..." which requires me to test with *"all extensions disabled"* - but I cannot do that without spending the next hours of configuration / re-configuration
- Because in the process of checking + testing the setup, the Disabled list is lost every time

**Comment by Yzrsah** [comment]
@sandy081 

- I have different extensions installed, like *Sublime Babel* and *Babel JavaScript*, but only one of them is enabled.
- I have different versions of extensions *vs* forked versions installed, like *Prettier*, *Prettier-MyForkedVersion*, but only one of them is enabled.
- I do not want to login or receive notices about certain services when we are not working on them, so they are currently disabled.
- Some extensions have a bug or performance issue, so they are disabled. I.e. *Node.js REPL* - this is a great extension, but it's disabled at the moment.
- You ask me to respond with `needs more info` to an issue like "Initializing JS/TS Language Features..." which requires me to test with *'all extensions disabled'* - but I cannot do that without spending the next hours of configuration / re-configuration
- Because in the process of checking + testing the setup, the Disabled list is lost every time

**Comment by sandy081** [comment]
I understand your set up but would like to know the feature request you are asking for? Can you please explain the new feature you need from VS Code and how would you like to use it?

**Comment by usernamehw** [comment]
Similar issue: #19083

**Comment by Yzrsah** [comment]
@sandy081 There's so much stuff going on with VSCode, many different issues can arise when working with extensions.

I spent the past 12 hours resolving problems in my VSCode setup, fixing, restarting, and filing issues.

I believe that I could reduce that amount of time if there was a way to get the list of Enabled/Disabled extensions.

**Comment by Yzrsah** [comment]
@sandy081 There's so much stuff going on with VSCode, many different issues can arise when working with extensions.

I spent the past 12 hours resolving problems in my VSCode setup, fixing, restarting, and filing issues.

I believe that I could reduce that amount of time spent if there was a way to get the list of Enabled/Disabled extensions.

**Comment by sandy081** [comment]
Sure I can provide that. But would like to know how that will solve your issue. Would be interested to know.

**Comment by ackvf** [comment]
Not being able to restore previous set of enabled/disabled extensions after a session to resolve extension interference/wrong settings proven to be uncomfortable for me as well. I propose that there is a json list consisting of disabled extensions similar to `.vscode/extensions.json` that can be edited by hand, allowing to use comments to quickly toggle the states of batches of extensions.
