### ISSUE TITLE
Explorer-Tree: Add toggle/setting to disable progressive search

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#69094]
Add new command (possibly setting) to enable or disable the progressive search within Explorer or other widgets with similar functionality.

Premise: 

Using voice dictation for programming heavily mixes both commands and code entry.  Unfortunately all systems are far from perfect and "stray, artifact"  keystroke events can happen frequently.  This is something one has to deal with, but some glitches have worse consequences than others.

The new tree features are great, but I have found personally that progressive searches can happen relatively easily when not intended.  I frequently have to Escape out of a search.

This is an important accessibility issue for me , but probably not applicable to many.

Given my interest, I would be happy to do a PR if acceptable.

**Comment by joaomoreno** [comment]
This was pushed earlier this week: https://github.com/Microsoft/vscode/issues/68233

**Comment by cleidigh** [comment]
@joaomoreno 
Awesome, I missed that.  good I'm not the only person.  
Thanks 👍
