### ISSUE TITLE
File Comparison OS Shell Integration

### ISSUE THREAD

**Issue by dmt0** [microsoft/vscode#69097]
I'd like to be able to select files from my OS's file manager for comparison, similar to BeyondCompare or other differs. 

Selecting the first file, I'd have a right-click menu option "Select first file for comparison", selecting second file I'd have "Compare with the first file". That would open the VS Code's diff view with the two selected files side by side.

![image](https://user-images.githubusercontent.com/2717746/53150817-6bf75200-357f-11e9-9a54-5c08a62c67d9.png)

I know this can already be done from command line: https://github.com/Microsoft/vscode/issues/1768

**Comment by gulshan** [comment]
My similar feature request was #15081
But it was closed.
