### ISSUE TITLE
Make folding work inside the commented blocks of code.

### ISSUE THREAD

**Issue by DevotionGeo** [Microsoft/vscode#69096]

**Comment by aeschli** [comment]
Example? Which language?

**Comment by DevotionGeo** [comment]
Any language.

comment a block of code containing a function, then try to fold that function.

**Comment by aeschli** [comment]
Each language has it's own folding provider, so this request has to be filed against each language.
But I don't think this is a very feasible request. Comment content is not bound to any syntax, so it's very hard do detect structure in there. 
No plans from our side to invest in this direction, but the folding range providers can be contributed from the outside so one could experiment with that in an extension.
