### ISSUE TITLE
Revisit need for electron-browser in workbench/contrib/codeEditor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69102]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/codeEditor` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by alexandrudima** [comment]
@bpasero I've moved everything except some code which forces an editor repaint when we receive an `vscode:osResume` ipc event. Not sure where that code should move now?

**Comment by bpasero** [comment]
@alexandrudima thanks for the prompt move, I agree the remaining stuff seems very specific to fixing that issue for us so we can leave it like this for now.

Would it make sense to have 2 contribution files (`codeEditorContribution.ts`) so that we can split up between `browser` contributions and `electron-browser`?

**Comment by alexandrudima** [comment]
> Would it make sense to have 2 contribution files (`codeEditorContribution.ts`) so that we can split up between `browser` contributions and `electron-browser`?

:+1:

**Comment by bpasero** [comment]
@alexandrudima just a small nit, there is a [`process.nextTick`](https://github.com/Microsoft/vscode/blob/11416de/src/vs/workbench/contrib/codeEditor/browser/selectionClipboard.ts#L53) usage still which unfortunately our layering rules does not capture.

**Comment by bpasero** [comment]
Nevermind, I can change this in debt week. My idea is to introduce a `vs/base/common/process` that simply delegates to `platform.setImmediate()`. I would then also use that module from `vs/base/common/path`.
