### ISSUE TITLE
Revisit need for electron-browser in workbench/contrib/debug

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69104]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/debug` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by isidorn** [comment]
I have moved everything that makes sense to /browser.
Now electron-browser only has the files that spawn process and are tightly coupled with a launching of a debug adapter.
