### ISSUE TITLE
Revisit need for electron-browser in workbench/contrib/comments

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#69103]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/comments` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by RMacfarlane** [comment]
This was fixed by https://github.com/microsoft/vscode/pull/70939
