### ISSUE TITLE
Revisit need for node/electron-browser in workbench/contrib/watermark

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69117]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/watermark` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by chrmarti** [comment]
@bpasero It only references `OpenRecentAction.ID`. I can inline that and use `CommandRegistry.getCommand()` to check if the command exists to avoid the dependency.

**Comment by bpasero** [comment]
@bpasero wouldn't that result in a link on the welcome page that possibly does not work if the command is not there?

**Comment by chrmarti** [comment]
@bpasero I'll use the `CommandRegistry` to make sure the command exists. In the web 'open recent' will not be shown for now. We can update that once the web has an open recent command.
