### ISSUE TITLE
Revisit need for node/electron-browser in workbench/contrib/terminal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69115]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/terminal` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by Tyriar** [comment]
@bpasero I've moved heaps of stuff up to common/browser in https://github.com/Microsoft/vscode/pull/69816, electron-browser/TerminalService and the new electron-browser/TerminalInstanceService are both tiny (~150, 50 lines) and the files in node/ are responsible for interfacing with with processes are fairly small as well. This was a fun refactor 😃 

I'll merge it in tomorrow if tests pass.
