### ISSUE TITLE
Revisit need for node/electron-browser in workbench/contrib/preferences

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#69111]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/preferences` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by roblourens** [comment]
I need a RequestService. Not sure why the XHR one is in electron-rowser?

**Comment by bpasero** [comment]
Yeah it does not look trivial to move it because it seems the interface it returns has some node dependencies. 

Any takers? @chrmarti with your recent proxy work? @joaomoreno ?

**Comment by bpasero** [comment]
@roblourens to clarify, this service is being used for Bing search support?

**Comment by chrmarti** [comment]
There already is `xhrRequest: IRequestFunction` in the requestService.ts, that should be independent of Node. `IRequestOptions` mixes in an `Agent` which is Node, but that is not used by `xhrRequest` which just relies on the browser's proxy support.

**Comment by bpasero** [comment]
@chrmarti yeah, I was more referring to the Stream usage in `IRequestOptions` and `IRequestContext`

**Comment by roblourens** [comment]
Yes @bpasero

**Comment by bpasero** [comment]
@sandy081 is working on bringing the `IRequestService` into the `browser`.

Related/Duplicate: https://github.com/microsoft/vscode/issues/75087

**Comment by sandy081** [comment]
Request service is now available in web and the interface is moved to `common`.

Adopted this and now In web, Settings also support bing search. 

Closing it.

**Comment by sandy081** [comment]
Reopening as the request service is not yet functional in web.

**Comment by sandy081** [comment]
After investigating, figured out that request service is functional but the bing results server should be adopted. Will add more details in the other issue.

Since this issue is about moving Preferences search service to browser which is done. So closing this.
