### ISSUE TITLE
Revisit need for node/electron-browser in workbench/contrib/welcome

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69116]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/welcome` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by chrmarti** [comment]
Moved everything to `browser` or `common`, but the 'getting started' code which depends on the experiment service in `node`.

**Comment by chrmarti** [comment]
@bpasero The remaining code in 'gettingStarted' is:
- The automatic opening of our web page on first launch.
- The telemetry opt-out. (Depends on experiment service.)

Should we leave these as-is for now?

**Comment by bpasero** [comment]
Yeah I think so 👍

**Comment by chrmarti** [comment]
Closing, thanks.
