### ISSUE TITLE
Revisit need for node/electron-browser in workbench/contrib/output

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69110]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/output` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

**Comment by isidorn** [comment]
This is due to the RotatingLogger in spdlog.
Forwarding to @sandy081 since he introduced this with @joaomoreno and might know best if there are alternatives
