### ISSUE TITLE
Highlight changed files in the explorer tree for a branch

### ISSUE THREAD

**Issue by mikeCGrant** [Microsoft/vscode#69127]
It would be nice to see any files (uncommitted or commited) that have changed in a branch highlighted in the explorer tree.

The following scenario is quite common for me:

Create Branch A.
Edit some files.
Commit those files.
Close those files in the editor (commonly due to working on another branch).
Switch to Branch B, or close VSCode.

Some time later come back to Branch A.
I now cannot see which files have ever changed in that branch, therefore I have to remember which files I've edited.

It would be much easier if those files were highlighted in some way in the explorer tree.
Maybe a solid colour fill behind the filename and icon in the explorer tree?

**Comment by Cirieno** [comment]
I use TortoiseGit to do this in Explorer and it's really handy to see which files/folders have changed (or are git-ignored).  Something similar in the Explorer panel would be nice.
