### ISSUE TITLE
Allow different font size in different instances

### ISSUE THREAD

**Issue by ImLixp** [Microsoft/vscode#69126]
Sometimes I need open two vscode and display in two screen, they are the same font size, but the two screens have different resolution.

**Comment by Tyriar** [comment]
Are you saying your monitors have different resolutions? Maybe a screenshot would help explain.

**Comment by ImLixp** [comment]
> Are you saying your monitors have different resolutions? Maybe a screenshot would help explain.

Yeah, one is big, and anthor is small. I use  "zooming in / out" to change font size in the big monitor, but the vscode in the small monitor was also changed.
<img width="1440" alt="2019-02-25 13 58 59" src="https://user-images.githubusercontent.com/5905653/53317662-7f037c80-3907-11e9-9bbd-dd942d06140d.png">
![2019-02-25 13 58 59 2](https://user-images.githubusercontent.com/5905653/53317668-81fe6d00-3907-11e9-90a4-c9e15c63a88b.png)

**Comment by bpasero** [comment]
The window zoom level can be set as a workspace setting, thus you can have different font sizes  / zooming per window.

**Comment by ImLixp** [comment]
I open two vscode at same time,  when  I use "zooming in / out" to change font size in one, the other also changed. Can the two be independent?
