### ISSUE TITLE
Line number not displayed when inserting a line after the last line

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#69129]
Version: 1.32.0-insider
Commit: 2e4d4a6bb16a65303b460795fa4ac734f9aea43e
OS: Linux x64 4.20.8-arch1-1-ARCH

Steps to Reproduce:

1. Press enter or insert a line after the last visible line in the editor and notice how the line number isn't visible

Does this issue occur when all extensions are disabled?: Yes

I'm pretty sure this only started happening after yesterday's insiders.

**Comment by nealot** [comment]
Just noticed this:
https://github.com/Microsoft/vscode/blob/f095776d671e7cee6e7017ce420765f4618b835a/src/vs/editor/common/config/editorOptions.ts#L251-L255

Why is it false for Linux?

**Comment by jeanp413** [comment]
nealot is right. Why is it false? It even isn't mentioned in the release notes.
I was about to open a new issue about it but hopefully found this first.

**Comment by nealot** [comment]
@jeanp413 I closed this issue because I found the main discussion over at https://github.com/Microsoft/vscode/issues/1027.
