### ISSUE TITLE
I want to add the ability to push to remote branches

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#69134]
I want to add the ability to push to remote branches

Now there's only push, no remote branch shown.

Reference pictures
![44](https://user-images.githubusercontent.com/10474968/53165661-42d1d280-360e-11e9-82b0-1b60a06e63cc.png)
![55](https://user-images.githubusercontent.com/10474968/53165662-436a6900-360e-11e9-90bf-aff608df40be.png)

**Comment by lifetin** [comment]
None of this is true.

My idea is to push it to a remote branch.

**Comment by lifetin** [comment]
![66](https://user-images.githubusercontent.com/10474968/53165843-b7a50c80-360e-11e9-8476-d86ad6ae2c6a.png)

**Comment by joaomoreno** [comment]
I'm not sure what that editor is, but it definitely doesn't seem like VS Code.
