### ISSUE TITLE
It is not possible to create a snippet that outputs multiple backslashes

### ISSUE THREAD

**Issue by Will-W** [Microsoft/vscode#69130]
The problem here is well understood and has been reported multiple times:
#32020
#59668
#33933
#47529

For background - textmate backslash handling combined with JSON backslash handling results in multiple backslashes being elided into one. This means you can't create snippets that output multiple backslashes. In my case that's an issue because that's the syntax for default args in elixir.

These issues have all been closed as dupes of  (as far as I can tell) #32020. That has been closed as #25661 would sort it out, except that #25661 has also been closed as out-of-scope.

This leaves us with no way to write these snippets, no issue tracking fixing that problem and no workaround in the meantime.

My proposal to fix this would be to add an option to the snippet syntax. If the property `"textmate_backslashes": false` was set on the snippet object, then textmate backslash elision wouldn't happen and `\\\\` in JSON would output as `\\`.
This would add the functionality, while not breaking anyone's existing snippets.

**Comment by jrieken** [comment]
> This means you can't create snippets that output multiple backslashes. In my case that's an issue because that's the syntax for default args in elixir.

That isn't correct, you can insert as many backslashes as you as like but it's just an escaping orgy. For instance the snippet below inserts three backslashes

```
	"Print to console": {
		"scope": "javascript,typescript",
		"prefix": "fog",
		"body": [
			"console.log('a\\\\\\\\\\\\a');",
			"$2"
		],
		"description": "Log output to console"
	}
```
