### ISSUE TITLE
Code should not complete when pressing `.`

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#6913]
- VSCode Version: 1.1.1
- OS Version: Mac OSX 10.11.4

Steps to Reproduce:

1. Create a TypeScript file `test.ts`
2. Start typing `console.log`
3. Then type a `.` as if you want to type `console.log.bind(console)`

**Current behaviour**

It auto completes to `console.log(., optionalParams)` instead of letting the developer continue with `console.log.`

![vscode](https://cloud.githubusercontent.com/assets/1913805/15571211/da8f1ee2-2339-11e6-9804-6acf7aaf9f12.gif)

**Expected behaviour** 

To be able to continue typing and get `function` suggestions like `bind`, `apply`, `call`, ...

![vscodejs](https://cloud.githubusercontent.com/assets/1913805/15571248/056c8eba-233a-11e6-9bd2-33ef275199db.gif)

**Extra notes**

This only applies in TypeScript `.ts` files and not in `.js` files. That's how I recorded the second screen capture.

I'm not sure if this actually is an issue in VS Code or somewhere in another package.

**Comment by dbaeumer** [comment]
@alexandrudima could we use your cool new - keyboard shortcut feature to unbind . as a completion accept character ?

**Comment by alexandrudima** [comment]
Yes, starting with the May release it will be:
```
{ "key": ".",                     "command": "-acceptSelectedSuggestion" }
```

**Comment by SamVerschueren** [comment]
Cool! Great work.

**Comment by SamVerschueren** [comment]
This started happening again in the latest release and is quite annoying.

![autocomplete](https://cloud.githubusercontent.com/assets/1913805/19760603/b2f71be2-9c32-11e6-94ed-0568e62170f7.gif)

I looked into the keyboard shortcuts and I found that the command for the `.` key was set to `^acceptSelectedSuggestion`. Not sure what that means @alexandrudima? I fixed it by changing it back to `-acceptSelectedSuggestion` in my custom `keybindings.json` file.

**Comment by alexandrudima** [comment]
@SamVerschueren The default keybindings always shipped with:

```
{ "key": ".",                     "command": "^acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible && suggestionSupportsAcceptOnKey && editorLangId == 'typescript'" },
```

The `^` means execute the command, but let the key code fall through, thus generating an internal type event for `"."`. In other words, pressing `"."` (`VK_OEM_PERIOD`) executes `acceptSelectedSuggestion` and **then** results in the character produced by `VK_OEM_PERIOD`.

My suggestion above was that you can customize your `keybindings.json` to remove this entry via an easy syntax:

```
{ "key": ".",                     "command": "-acceptSelectedSuggestion" }
```

So @SamVerschueren I'm not sure what exactly changed?

**Comment by SamVerschueren** [comment]
Strange, I thought the `-acceptSelectedSuggestion` shipped with VS Code since May, but I might be wrong here. I never configured it to be `-acceptSelectedSuggestion` and it never selected the suggestion when I pressed `.`. Since the latest release it started happening again so I thought that it was reverted for some reason.

It works now when I add use the `-` sign so I'm fine with how it works now. Apparently it's expected behaviour, just wanted to make sure it wasn't a regression bug or something.

**Comment by alexandrudima** [comment]
Yeah, in my comment above I was saying how one can **customize** their keybindings.json to remove this keybinding item.

It would not make sense to ship with the `-acceptSelectedSuggestions`, we might as well ship without that keybinding item to begin with.

**Comment by SamVerschueren** [comment]
> It would not make sense to ship with the -acceptSelectedSuggestions, we might as well ship without that keybinding item to begin with.

Good point! Probably something changed locally. Thanks for the explanation :).
