### ISSUE TITLE
Compound can not run twice the same configuration

### ISSUE THREAD

**Issue by canvas-J** [Microsoft/vscode#69139]
Issue Type: <b>Bug</b>

I don't know if it's a Bug or the latest optimization strategy for the editor, but when I open multiple programs in one single window, I can't run them at the same time. Sometimes when I debug a program, I want to run it immediately after a brief modification while keeping the running program running until it comes out, but now as long as I want to run more than one program at the same time. It's very inconvenient for me to have to open a new window or even multiple windows to implement the preface.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.5.1
diff-tool|jin|0.0.1
vs-color-picker|lih|1.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
vscode-yaml|red|0.3.0
markdown-preview-enhanced|shd|0.3.11
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by Tyriar** [comment]
Have you read about multi-target debugging and compound launch configs? https://code.visualstudio.com/docs/editor/debugging#_multitarget-debugging

**Comment by weinand** [comment]
@canvas-J I don't really understand what you are trying to do. Please provide exact steps for what you are trying to do, what do you expect and what is actually happening.

**Comment by canvas-J** [comment]
@weinand @Tyriar Thank you for your reply, here I made a ![Gif of the problem](https://github.com/canvas-J/my_proj/blob/master/why.gif). Obviously, I can only run one program under a single window. But before about two versions, I could run multiple programs in one window at the same time.

**Comment by macromaniac** [comment]
Basically 1.28.1 and earlier you could run multiple instances of the same program, but now you cannot. In my launch.json the following used to launch 3 servers and a master server, but any version after 1.28.1 it only launches 1 server and a master server

        {
            "name": "x3 launch all",
            "configurations": [ "server", "server", "server", "master_server", "client" ],
        },

A temporary workaround would be creating a bunch of launch configurations like server_1, server_2, server_3.. but this becomes impractical when you are doing stress tests with like 9 servers and a master server.
