### ISSUE TITLE
Very slow screen update on Python projects

### ISSUE THREAD

**Issue by glauber-md** [Microsoft/vscode#69136]
Issue Type: <b>Performance Issue</b>

Opening the tooltips, menus, scrolling the code... seems to be very slow, with many lags.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	  7616	code main
    0	   199	  1348	   window (model.py - lightup-ws-backend - Visual Studio Code)
    0	     6	  5932	     winpty-process
    0	    11	  7752	       console-window-host (Windows internal process)
    0	     4	 11772	       C:\Windows\System32\cmd.exe
    0	    32	  3220	         python  
    0	    87	  6248	     extensionHost
    0	    47	  1288	       e:\SOURCES\GIT\lightup-ws-backend\venv2\Scripts\python.exe completion.py
    0	    11	  9820	         console-window-host (Windows internal process)
    0	    21	 13440	         e:\SOURCES\GIT\lightup-ws-backend\venv2\Scripts\python.exe lib\python\jedi\evaluate\compiled\subprocess\__main__.py lib\python
    0	    11	  6940	           console-window-host (Windows internal process)
    0	   194	 12488	       "C:\Program Files\Java\jdk-11.0.1\bin\java" -jar c:\Users\glaub\.vscode\extensions\sonarsource.sonarlint-vscode-1.5.0\server\sonarlint-ls.jar 57713 file:///c:/Users/glaub/.vscode/extensions/sonarsource.sonarlint-vscode-1.5.0/analyzers/sonarjs.jar file:///c:/Users/glaub/.vscode/extensions/sonarsource.sonarlint-vscode-1.5.0/analyzers/sonarphp.jar file:///c:/Users/glaub/.vscode/extensions/sonarsource.sonarlint-vscode-1.5.0/analyzers/sonarpython.jar file:///c:/Users/glaub/.vscode/extensions/sonarsource.sonarlint-vscode-1.5.0/analyzers/sonarts.jar
    0	    11	  9800	         console-window-host (Windows internal process)
    0	    31	  8984	     watcherService 
    0	    11	  4132	       console-window-host (Windows internal process)
    0	     6	 10976	     winpty-process
    0	    11	  4020	       console-window-host (Windows internal process)
    0	     4	 13188	       C:\Windows\System32\cmd.exe
    0	    13	 13260	     electron-crash-reporter
    2	    56	  5144	   window (Issue Reporter)
    0	    65	 13084	   shared-process
    3	   372	 13844	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (model.py - lightup-ws-backend - Visual Studio Code)
|    Folder (lightup-ws-backend): 7992 files
|      File types: py(2709) pyc(2561) json(586) txt(487) msg(145) tcl(128)
|                  rc(122) h(100) enc(78) exe(42)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0
sonarlint-vscode|Son|1.5.0
vscode-react-native|vsm|0.8.0

</details>

**Comment by Tyriar** [comment]
Not sure who owns this, doesn't seem like an extension problem if it's talking about UI responsiveness.

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
