### ISSUE TITLE
InstantiationService with proxys: allow to be used in browser namespace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69141]
Refs #68302

I will need to be able to use the `src/vs/platform/instantiation/node/instantiationService.ts` when node is disabled, can we move it to `browser` land? Possibly in workbench maybe if the challenge is about standalone editor usage?

**Comment by jrieken** [comment]
Yeah, not easy without tricks. Our browser-layer is IE11 and that doesn't support ES proxies...

**Comment by bpasero** [comment]
Maybe we should revive that "IE11-support" discussion...

**Comment by jrieken** [comment]
Trying to avoid the IE11-discussion. I pushed a fix that ghetto-hacks around this by locally declaring `Proxy` and by running feature detection inside the service.
