### ISSUE TITLE
Linux: json settings button {} will not open both Default and custom settings side by side

### ISSUE THREAD

**Issue by wyattbiker** [Microsoft/vscode#69158]
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic
(I am using Linux Mint 1.9, Cinnamon if that matters)

**Issue #1: json formatted Defaults does not open**
1. Launch VS Code 
2. Navigate to File >Preferences > Settings 
3. See all the Default settings (in the form style) under User Settings.
4. Click on {} to view them as json. Only the custom settings file opens up as json formatted while the Default settings remains as is.. 

FYI:
Under Mac OS X, the same steps above will open a split window and show the json formatted Default and custom settings, side by side. 

**Linux VS Code Screen Shot**
![image](https://user-images.githubusercontent.com/930478/53189366-5745a900-35d5-11e9-86d1-fafed534c3ad.png)

Mac OS X Screen shot
![screen shot 2019-02-21 at 12 47 06 pm](https://user-images.githubusercontent.com/930478/53190189-08007800-35d7-11e9-882a-511465f9a48c.png)

**Comment by torreyr** [comment]
This is also an issue in the Windows 32-bit VS Code, version 1.31.1.


![image](https://user-images.githubusercontent.com/19395461/53201085-f7043680-35d7-11e9-887d-3d49f0975f9d.png)

**Comment by gjsjohnmurray** [comment]
@wyattbiker - are you certain your Linux and macOS instances are both running the same VSCode version?

What you're describing seeing in your Linux one (which we can see is the latest version, 1.31.1) sounds like it might be resolvable by checking https://github.com/Microsoft/vscode/issues/68386#issuecomment-462247156

**Comment by AlexeiMet** [comment]
![vs-code-no-settings-ui png](https://user-images.githubusercontent.com/37084849/53205049-382f3180-363e-11e9-8135-8674300fde4e.jpg)
The same problem on Windows10 Version 10.0.17763 / VSCode Version 1.31.1

**Comment by wyattbiker** [comment]
> @wyattbiker - are you certain your Linux and macOS instances are both running the same VSCode version?
> 
> What you're describing seeing in your Linux one (which we can see is the latest version, 1.31.1) sounds like it might be resolvable by checking [#68386 (comment)](https://github.com/Microsoft/vscode/issues/68386#issuecomment-462247156)

Yep, Mac OS X is on the older version (1.30). And yes setting workbench.settings.useSplitJSON in 1.31 fixed it. Not sure why you thought it would simplifies things. But maybe at least default shoulve been set to true and let people set it false. Thanks for quick reply. Ill close this ticket.
