### ISSUE TITLE
Duplicate symbolic link not indicated/identified

### ISSUE THREAD

**Issue by heyheyjc** [microsoft/vscode#69157]
Issue Type: <b>Bug</b>

I have two symbolic links to the same file elsewhere within the project, but only one of them is indicated with the link arrow in the explorer, and only that one has 'Symbolic Link' in its toolbar text.

This screenshot shows the two links to "Message.js", only the second of which is indicated:

![symlink_issue_1](https://user-images.githubusercontent.com/28930874/53188600-987c8f80-35ba-11e9-858b-d8e29dc30455.JPG)

The un-indicated link in windows explorer (to show I haven't screwed up somehow...):

![symlink_issue_2](https://user-images.githubusercontent.com/28930874/53188602-987c8f80-35ba-11e9-8858-8d2deed10d4a.JPG)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:21:36.727Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2196)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.95GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
vscode-npm-script|eg2|0.3.5
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.2

</details>

**Comment by Gruntfuggly** [comment]
I have the same problem running under Ubuntu (1.36) . It's not consistent though. Some files show the links but other don't.
