### ISSUE TITLE
Visual Studio Code Open 3 times in a row  when using cmd

### ISSUE THREAD

**Issue by pierrelstan** [Microsoft/vscode#69154]
Issue Type: <b>Bug</b>

When I go to the path of the project that I wanted to work on using cmd and I enter " code ."  the Visual Studio Code opened 3 times in a row.
1- the project i wanted to work on 
2- the last project i worked on 
3- An empty Visual Studio Code from the root of my C: \\  computer 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.3.9600

**Comment by Tyriar** [comment]
You might want to tweak the settings `files.hotExit`, `window.openFoldersInNewWindow` and `window.restoreWindows` which drive this behavior.
