### ISSUE TITLE
Actions in the debug toolbar should be properly contributed

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69153]
The base debug actions should also be contributed via menu registry.
To allow intermingling with actions contributed by extensions.

**Comment by DanTup** [comment]
> To allow intermingling with actions contributed by extensions.

It'd be good to ensure this can work consistently with the touch bar too. When I tried to add buttons in between (using group `9_debug` or something) the spaces between the buttons disappeared and it all became a mess.

Specifically I'm interested in adding a "hot reload" button next to the "restart" button both in the touch bar and debug toolbar :-)

**Comment by isidorn** [comment]
Also as part of this we should support rendering separators in the debug toolbar.
@bpasero @misolori do we already have some horizontal seperator somewhere that I can reuse? Not to my knowledge.

**Comment by isidorn** [comment]
Now all the debug actions are properly contribued using groups and orders.
All the debug commands are in the `navigation` group which is primary. Now it is possible to also insert items in between the built in debug commands. @DanTup try it out and let us know. You can use the order, here are the orders that debug commands use https://github.com/Microsoft/vscode/blob/05f926991c9c52dff838d542c0014acd756833e2/src/vs/workbench/contrib/debug/electron-browser/debug.contribution.ts#L262

Adding feature request label so I mention this in the relase notes.

**Comment by DanTup** [comment]
@isidorn Cool, thanks! I'll take a look inInsiders later in the week :-)

Do you know off-hand whether I should be able to do the same for TouchBar (I know it's not part of this work, but I'm not sure if it's expected to work - as when I tried, strange things happened, like missing dividers between buttons). If it's supposed to work, I'll repro and open bugs, otherwise I'll open a request to support it there too.

Thanks!

**Comment by isidorn** [comment]
This is currently not supported for the TouchBar.
If you would like this please open a feature request (thought not sure if we will tackle it)

**Comment by DanTup** [comment]
@isidorn LGTM, thanks!

![Screenshot 2019-03-19 at 8 06 41 am](https://user-images.githubusercontent.com/1078012/54589589-f5cef980-4a1d-11e9-8ad0-a40ca24655b5.png)

I opened new issues about the Touch Bar (https://github.com/Microsoft/vscode/issues/70737 and https://github.com/Microsoft/vscode/issues/70735).

**Comment by isidorn** [comment]
@DanTup great that it works for you!
