### ISSUE TITLE
New File Explorer: not always highlighting active file in the tree

### ISSUE THREAD

**Issue by JosiahWitt** [Microsoft/vscode#69152]
- VSCode Version: 1.31.1 (also in insiders build 1550729941)
- OS Version: Linux x86 (Solus)

Steps to Reproduce:

1. Open two files (file1 and file2) by double clicking each of them
2. Click again on the active file in the explorer tree
3. Switch to the second file by clicking on its tab (you could also use `ctrl + p`)
4. The second file is not highlighted in the tree

This changes the behavior from version 1.30.1. In the previous version, the active file would always be highlighted in the explorer. Now, there are some cases, as described previously, where another file is highlighted. This gets confusing with a large project when I glance at the tree and it appears that I'm somewhere else.

This may be partially related to #68597, #68790, and  #68747.

Does this issue occur when all extensions are disabled?: Yes

New behavior:
![New behavior](https://user-images.githubusercontent.com/7329219/53184451-08931180-35cb-11e9-8127-0d0e72779621.gif)

Old behavior:
![Old behavior](https://user-images.githubusercontent.com/7329219/53184466-0f218900-35cb-11e9-8b88-c2ac6b3dfbcd.gif)

**Comment by SetTrend** [comment]
### I might have a similar issue:

File Explorer seems to (erroneously) cache a list of some previously opened files.

When I go to Git for VS Code and open a file from there, Explorer doesn't reveal the opened file (which I presume it should). Instead it opens some file I previously opened and already closed again:

![fix explorer auto reveal](https://user-images.githubusercontent.com/9283914/53298838-95400880-3833-11e9-906f-aa184c29129c.gif)

**Comment by isidorn** [comment]
@JosiahWitt great catch. Thanks! Try it out in tomorrow's vscode insiders and let us know if it is better now.

**Comment by JosiahWitt** [comment]
@isidorn Thanks! Will do!

**Comment by JosiahWitt** [comment]
@isidorn It seems to work great! Thanks!

**Comment by isidorn** [comment]
@JosiahWitt thanks for letting us know all is good!
