### ISSUE TITLE
Support for Dart in code snippets

### ISSUE THREAD

**Issue by jwiese-ms** [Microsoft/vscode#69159]
I would like to see 'dart' as one of the supported languages in VS Code.  There is a Snippet Creator (https://github.com/nikitaKunevich/vscode-snippet-creator) that does not work because 'dart' is not in the current list of supported languages.

**Comment by beastdestroyer** [comment]
Just wondering, do you use the Dart extension?

**Comment by jwiese-ms** [comment]
Yes, I do 😊

// John Wiese /  Partner Technology Strategist / 414-978-5926

**Comment by jwiese-ms** [comment]
um, not sure how this is caused by an extension.  The documentation clearly does not list 'dart' as one of the supported languages. https://code.visualstudio.com/docs/languages/overview**** so how do we get it listed?  What does using the extension have to do with it not being listed in the list of languages when I try to create a snippet?

**Comment by Gama11** [comment]
Are you talking about the "Select Language Mode" dropdown? If you have the Dart extension installed, it should be listed.

**Comment by jrieken** [comment]
> In Visual Studio Code, we have support for almost every major programming language. Several ship in the box, for example, JavaScript, TypeScript, CSS, and HTML but more rich language extensions can be found in the VS Code Marketplace.

Dart isn't listed because we don't ship support this out of the box nor do we have a special getting started guide here. Tho that doesn't mean VS Code doesn't support it. What is you question? What is you issue here?

**Comment by jwiese-ms** [comment]
ok, that is what I thought.  Here's what I would expect to happen:  

1. install VS Code
2. install the Dart extension (https://github.com/Dart-Code/Dart-Code)
3. install the Snippet Creator extension (https://github.com/nikitaKunevich/vscode-snippet-creator)
4. write some code, highlight it, right-click, choose 'create code snippet'
5. in the list choose, 'dart' (then fill in the info needed)
6. be able to use that snippet alias in any '*.dart' file

It seems to break at #4, is that an extension issue? Which extension, then Dart extension or the Snippet extension? Is it because of lack of support for Dart OOTB with VS Code?  I'm just trying to figure out how to get this experience better as many people are using VS Code for their development of Flutter apps and one of the complaints I am hearing is that the snippet experience is horrible compared to Intelli-J. I think if it works like I outlined that then there is no issues.  But I don't know where to start to fix it.

**Comment by jwiese-ms** [comment]
I do, and it isn't in the list:

![image](https://user-images.githubusercontent.com/1899813/53354015-887eeb80-38eb-11e9-9c53-50b5f3951d67.png)

**Comment by jwiese-ms** [comment]
so, to make it a little more interesting I **do** have 'dart' in the list on my MacBook but not on Windows.  So perhaps it is an issue with the Dart extension?

**Comment by jwiese-ms** [comment]
ok, I take that back, it is there when I just go to **File -> Preferences -> User Snippets**  on my Mac, but not on Windows. It doesn't show up on either machine when I run the "Create Snippet" command.

**Comment by DanTup** [comment]
@jwiese-ms on Windows where you see this, does Dart appear in the list if you run the **Change Language Made** command with a file open?

**Comment by jwiese-ms** [comment]
@DanTup yes, if I run the **Change Language Mode** command I do see dart in the list.  If I select that and then create the snippet it appears to work.  Not sure if there was something just messed up with my config or if there is something else going on, but at least at this point it appears to work like it should.   I'll find a clean machine and start from scratch to see if it is an issue or was something funky with my setup.

**Comment by DanTup** [comment]
@jwiese-ms Ok, cool. If you do hit any issues that may be related to the Dart extension, feel free to ping me!
