### ISSUE TITLE
PHP syntax highlight snafu

### ISSUE THREAD

**Issue by josephzidell** [Microsoft/vscode#69156]
- VSCode Version: 1.30.2
- OS Version: Win 10 Pro

Steps to Reproduce:

1. Type this PHP code:
```php
true ? A::a : A::b;
```

Does this issue occur when all extensions are disabled?: Yes

The syntax coloring is weird:
![vscode_php_syntax_highlight_snafu](https://user-images.githubusercontent.com/1812443/53188137-bbb33900-35d2-11e9-88ae-4228c207e07b.png)

**Comment by roblourens** [comment]
Nice one, I filed https://github.com/atom/language-php/issues/356 upstream
