### ISSUE TITLE
Drop down in title bar not (auto hide) when click somewhere in extension tap

### ISSUE THREAD

**Issue by atallah-salah** [Microsoft/vscode#69150]
Issue Type: <b>Bug</b>

open any extension tap then click on any title bar drop down element (e.x : Help ) and keep it open when I try to select text or any content of the extension the drop down list not hide correctly , It's work fine in editable content tap

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|1.2.13
bracket-pair-colorizer|Coe|1.0.61
babylon-js-viewer|jul|1.3.0
vscode-checkpoints|mic|1.1.0
colored-regions|mih|0.0.3
syncing|non|2.1.3
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.3
terminal-tabs|Tyr|0.2.0
haxe-checkstyle|vsh|1.3.0
quokka-vscode|Wal|1.0.189

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@mjbvz I think this is webview eating the click? We can adopt the fix we did for context menus in the menubar by blocking the rest of the UI with an invisible div so that can get the click.

**Comment by mjbvz** [comment]
Yes I think webviews capture most interaction events so we'd have to re-broadcast clicks much as we already do for keyboard events. Adding an invisible div would be the easier and more stable fix

**Comment by sbatten** [comment]
This issue must have been fixed incidentally elsewhere. I can no longer repro. Please verify @atallah-salah
