### ISSUE TITLE
Setting to suppress confirmation prompt when opening an Extension URI

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#69166]
Extension URIHandlers currently prompt users to confirm opening, "Allow an extension to open this URL?" This is inconvenient for some workflows, having some method for users to "Always Allow" would be an improvement.

### Example use case:
- In a code browsing web interface, we want to provide an "Open in VSCode" button
- We support remote editing via a FileSystemProvider

Due to the FileSystemProvider, built-in `vscode://file/...` URLs don't seem to solve this problem. I have been able to use `registerURIHandler` for this, but the extra click on every file open hurts usability.

### Ideas:
- "Always Allow"
  - Option: Extension level setting. (E.g. accept all URLs like `vscode://my-extension/...`)
  - Option: Path level setting. (E.g. accept all URLs like `vscode://my-extension/open/...`)
  - Add a checkbox or button to the confirmation dialog to enable the chosen setting.
- /file/ URIs do not currently prompt people. Design a hook for extensions to integrate with these.

**Comment by joaomoreno** [comment]
> Due to the FileSystemProvider, built-in `vscode://file/...` URLs don't seem to solve this problem.

It doesn't work because file system providers have separate schemas?

**Comment by dalongi** [comment]
@joaomoreno: Correct, the FileSystemProvider will expect a different scheme from `vscode://`.

I also plan to have other Web UI integrations in addition to 'Open File' where the confirmation may become cumbersome for people doing that do those actions frequently.

If the scheme issue is solved, there are a couple other challenges with the /file/ approach as well:
- My current FileSystemProvider expects a hostname in the URI, but the web UI containing "Open in VSCode" wouldn't know which hosts are locally connected to construct that URI. This is solvable on my end by adding logic to FileSystemProvider.
- In the above scenario, if there is not a matching remote connected, I'd want to launch a different workflow in my extension to connect.
  - I don't know offhand if launching a workflow (via VSCode command) from `readFile()` would work. Since readFile() returns a generic `Thenable`, I suppose it might. 
  - If that is possible, it feels like FileSystemProvider can be abused to accomplish anything that URI handler can but avoiding the confirmation prompt.

**Comment by dalongi** [comment]
@joaomoreno: I have been able to implement with two approaches, or can combine them. Let me know if you have a preference which PR I send.

1) "Don't ask again" checkbox on the confirmation dialog that saves via `StorageService`
    - Discoverable for extension users.
    - Cannot be undone to "un-remember".

2) Configuration entry `"extensions.confirmedUriHandlerExtensionIds"`  backed by `ConfigurationService`. 
    - Not as discoverable for extension users.
    - Can be managed by workspace owner / enterprise.

3) Combine both to support Config and UI Checkbox.

**Comment by joaomoreno** [comment]
UI + config sounds good.

**Comment by roblourens** [comment]
Is the dialog supposed to have an extra button or checkbox?

![image](https://user-images.githubusercontent.com/323878/62251497-c73a3580-b3a4-11e9-8e15-ef04ea2fbf01.png)

Otherwise, works fine with the setting

**Comment by dalongi** [comment]
@roblourens: Interesting, that dialog looks different from what I see. Screenshot from OSS running on Mac. Insiders looks the same but with a different icon:

![Screen Shot 2019-08-01 at 10 56 02 AM](https://user-images.githubusercontent.com/1166263/62315964-5568f700-b44b-11e9-8b4c-9e5b1d28fa3a.png)

My hunch is that SimpleDialogService supports the checkbox rendering, but it looks like DialogService ignores it. I'm not sure offhand how VS Code chooses which DialogService to use so I will take a closer look here.

**Comment by roblourens** [comment]
Oh yeah, I have set a setting to opt into that. I filed https://github.com/microsoft/vscode/issues/78343 for this
