### ISSUE TITLE
Emmet Expansion: Count down ($@-) doesn't work

### ISSUE THREAD

**Issue by MrDevinB** [microsoft/vscode#69168]
Using a multiplier with the count down syntax, ($@-), produces incorrect results. Per the example on [docs.emmet.io](https://docs.emmet.io/cheat-sheet/ ) under `Item numbering: $`:

`ul>li.item$@-*5` should expand to:

```
<ul>
    <li class="item5"></li>
    <li class="item4"></li>
    <li class="item3"></li>
    <li class="item2"></li>
    <li class="item1"></li>
</ul>
```

Actual output:

```
<ul>
    <li class="item1@-"></li>
    <li class="item2@-"></li>
    <li class="item3@-"></li>
    <li class="item4@-"></li>
    <li class="item5@-"></li>
</ul>
```

**Comment by ramya-rao-a** [comment]
@octref I believe this is a regression and therefore a bug not a feature request.

@gushuro made a PR upstream to get this feature last year. See https://github.com/emmetio/html-transform/pull/10

**Comment by octref** [comment]
Thanks for the info. Will take a look.

**Comment by DanielRuf** [comment]
This is still not fixed. Is there some open PR to fix this in VSCode or is some new release of the emmet library needed?

**Comment by DanielRuf** [comment]
Currently using VSCode 1.36.1

https://github.com/microsoft/vscode/issues/35296 when will this land?

**Comment by pytkr** [comment]
I tested VSCode **1.39.2** , and with the same bug of this emmet grammar. 

> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134

**Comment by blachawk** [comment]
Any takers from the vscode team willing to take this task on and make it rain?

**Comment by Ezokia** [comment]
I have the same problem with VSC 1.48!

**Comment by anburocky3** [comment]
Does this issue still persist? It's not working on `1.51.1` release.

**Comment by DanielRuf** [comment]
> Does this issue still persist? It's not working on `1.51.1` release.

Obviously it is still not fixed as you can see (the issue is still open and like you write, it is not working in 1.51.1).

**Comment by rzhao271** [comment]
\closedWith dc5a3da

**Comment by rzhao271** [comment]
Verifier: In an HTML document, expand the abbreviation given in https://github.com/microsoft/vscode/issues/69168#issue-413110763 and confirm that the "Expected" result shows up rather than the "Actual" result.
