### ISSUE TITLE
Doc issue: launch.json "outFiles" isn't documented

### ISSUE THREAD

**Issue by diberry** [Microsoft/vscode#69161]
While trying to debug a node.js project on Win10 that uses a `Makefile`, the launch.json looks like:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Makefile Debug",
            "program": "C:\\ProgramData\\chocolatey\\bin\\make.exe",
            "args": ["test"],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

The error is `Cannot launch program 'C:\ProgramData\chocolatey\bin\make.exe`; setting the 'outFiles' attribute might help.

[This](https://code.visualstudio.com/Docs/editor/debugging#_launchjson-attributes) is where I'm looking for outFiles but can't find it.

**Comment by weinand** [comment]
@diberry you tried to find "outFiles" in the generic debug documentation. But you are using the node.js debugger so it would make more sense to look into the specific "Node.js Debugging" documentation: https://code.visualstudio.com/docs/nodejs/nodejs-debugging and specifically the attribute "outFiles": https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps.

So "outFiles" is documented, but it does not really help in your case. You tried to debug a "*.exe" file with the Node.js debugger. But a *.exe is not a source file that Node.js understands.

What are you trying to do?

**Comment by diberry** [comment]
I'm trying to add a unit test to [js-yaml](https://github.com/nodeca/js-yaml/blob/master/package.json) which is built and run tests from Makefile. I've done a lot of debugging with VSCode for Node, .Net but not with a Makefile so that part is new to me. 

I'm trying to figure out how to construct the launch file to run the mocha test (controlled by Makefile), so I can have the breakpoints hit. 

I've looked for any example of a launch file that uses a Makefile but can't google my way to an answer.

**Comment by weinand** [comment]
Use the "runtimeExecutable" and "runTimeArgs" if you want to run arbitrary programs with the node debugger. See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools

**Comment by diberry** [comment]
@weinand I see you closed this bug. I'm adding info in case someone else stumbles across it. 

I didn't get this to work with a Makefile on Windows 10 or on Mac. I did wind up using the NPM launch, as noted in this [StackOverflow](https://stackoverflow.com/questions/54758787/how-to-debug-node-js-mocha-test-built-with-makefile/54819158#54819158) issue.
