### ISSUE TITLE
Open editors tab pushes down file explorer

### ISSUE THREAD

**Issue by EWhite613** [microsoft/vscode#69169]
Issue Type: <b>Bug</b>

## Steps:
* Click on file in file explorer (below OPEN EDITIORS)
* Open Editors grows pushing file explorer down

## Why it's really annoying
Try double clicking on an item. First click opens item. Second click (open editor expands moving item down) opens another file you weren't intending on click

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
ember-module-snippets|can|1.1.0
path-intellisense|chr|1.4.2
vsc-ember-frost|cie|0.0.2
vscode-eslint|dba|1.8.0
ember-syntax|dhe|0.5.0
gitlens|eam|9.5.1
vscode-ember|emb|0.2.0
vsc-ember-cli|fel|0.3.3
beautify|Hoo|1.4.9
vscode-ember-unstable|lif|0.2.15
vsliveshare|ms-|0.3.1225
indent-rainbow|ode|7.2.4
vscode-versionlens|pfl|0.22.0
EmberES6Snippets|pha|2.3.3
vscode-icons|rob|8.2.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@isidorn this appears to only be a problem when you do not have a preview/unpinned tab (and if you double click slowly)
