### ISSUE TITLE
Fails to use default browser

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#69167]
Issue Type: <b>Bug</b>

I have both firefox and chrome installed on my Linux system. firefox is set as the default browser, but code-insiders will always use chrome when opening links.

VS Code version: Code - Insiders 1.32.0-insider (2e4d4a6bb16a65303b460795fa4ac734f9aea43e, 2019-02-21T06:15:09.350Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.66GB (0.44GB free)|
|Process Argv|/home/yadav/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.2
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
java-debug|DSn|0.0.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
markdown-preview-bitbucket|hbr|1.0.0
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.2.2
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.2
angular2-inline|nat|0.0.17
java|red|0.38.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
We use Electron's API to open links, you should try repro against and report to https://github.com/electron/electron (after searching existing issues)
