### ISSUE TITLE
VS Code Logs directory filling my hard drive

### ISSUE THREAD

**Issue by ThomasMichon** [Microsoft/vscode#69160]
Issue Type: <b>Bug</b>

In the course of ony a week, VS Code has filled my poor hard drive with 342 GB of log files! Last week, I had low disk space and discovered 300+ GB of log files and deleted them, and now they're all back!

I don't see any place in the UX to clear the log files, nor does there seem to be any mechanism to keep the space usage low. Any way to tamp down on this rampant disk usage?

The folder in question is `%APPDATA%\Roaming\Code\logs`, specifically *one file* in the TypeScript Language service logs!

![image](https://user-images.githubusercontent.com/6828233/53190401-60774b80-35be-11e9-96fd-b52930ba26d2.png)

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (9.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
tslint|eg2|1.0.43
docthis|joe|0.7.1
python|ms-|2019.1.0
vsliveshare|ms-|0.3.1225
debugger-for-chrome|msj|4.11.2
java|red|0.38.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
vscode-import-cost|wix|2.12.0

</details>

**Comment by mjbvz** [comment]
These are the Typescript logs. They are not enabled by default and only intended for debugging issue. You may have accidentally left them enabled.

Make sure you reset the setting `"typescript.tsserver.log": "off"` in vs code if you no longer need logging enabled

**Comment by iulo** [comment]
give some tips about the used space of hard disk my better? `tsserver-log` has already used my 60g space.... @mjbvz
