### ISSUE TITLE
February 2019 Endgame

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69177]
This is the endgame schedule for [February 2019 Iteration](https://github.com/Microsoft/vscode/issues/68293).

## Schedule

- End game master: @octref / Redmond
- End game buddy: @dbaeumer / Zurich
- *02/22* Code freeze for the endgame
- *03/01* [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- *03/07* Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Friday 02/22
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) **@octref**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Monday 02/25
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

##### Tuesday 02/26
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22February+2019%22+)

##### Wednesday 02/27
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22February+2019%22+)
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **owner**

##### Thursday/Friday 02/28 – 03/01
- [x] Pause scheduled `insider` builds **@octref**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
- [x] All issues [verified](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22February+2019%22+)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @RMacfarlane
  - [x] OS X - @octref
  - [x] Linux - @Tyriar
- [x] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [x] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **@octref**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@auchenberg**
  - [x] localization **@shawndon**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **@octref**
- [x] Acknowledge issue trackers from the community **@chrmarti**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@octref**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **@octref**
- [x] Bump up the version in package.json - **@octref**
- [x] Announce master is open for business **@octref**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@octref**
- [x] Build `Insider` from `release/<x.y>` **@octref**
- [x] Manually release `Insider` **@octref**
- [x] Build stable for all platforms as new candidate issues come in **@octref**
- [x] Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [x] Build stable for all platforms **@octref**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@Tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit @alexr00 
    - [x] signed installer 64-bit @alexr00
    - [x] signed user installer 32-bit @alexr00
    - [x] signed user installer 64-bit @alexr00
    - [x] zip 32-bit @dbaeumer 
    - [x] zip 64-bit @dbaeumer
  - [x] OS X - @jrieken 
  - [x] Linux
    - [x] deb package 32-bit @aeschli 
    - [x] deb package 64-bit @weinand 
    - [x] rpm package 64-bit @weinand 
    - [x] rpm package 32-bit @aeschli 
    - [x] archives @aeschli & @weinand 
- [x] Publish website **@gregvanl**
- [x] Publish Localization language pack **@shawndon**
- [x] Publish to stable **@octref**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **@octref**
- [x] Publish rpm to repository manually **@Tyriar**
- [x] Enable scheduled `insider` builds **@octref**
- [x] Twitter announcement **@auchenberg**

**Comment by connorshea** [comment]
Should this issue be pinned like #68293?

**Comment by octref** [comment]
Shipped.
