### ISSUE TITLE
Show breadcrumb match count and add option to only show bread crumbs matching the filter text

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/vscode#69181]
When using the bread crumbs you can start typing to search through the methods. This seems to begin filtering the results however it doesn't remove non matches only brings the topmost match into view.

This can be misleading since you can't see the other matches are even know if there are any and wrongly conclude those items showing must be the ONLY matches when in fact there might be other matching methods farther down the list.

I show example video below where I am searching for a method named `onChangedActionType`
As I being to type `onChanged` it shows three method but they are not thing one I'm looking for.  I only could find it by scrolling down or using the arrow keys to see it.

This is why I think the minimal solution is to add a match count number.

A better solution might be to not show items that do not match. I could see the issue with people forgetting that have entered search text and thinking the file has less methods that they can see but I will leave that up to designers and it's why I think it should be optional so people can pick what they like.

Video: http://recordit.co/bqJNC8t7KD

**Comment by jrieken** [comment]
This is fixed in latest insiders by adopting the new tree widget. That allows to toggle between filter and find
