### ISSUE TITLE
ターミナル

### ISSUE THREAD

**Issue by kappa1892** [Microsoft/vscode#69186]
Issue Type: <b>Bug</b>

ターミナルを起動させようとすると強制終了します
終了コード2

VS Code version: Code 1.31.1 (2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

vscode-language-pack-ja|MS-|1.31.4
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0

</details>

**Comment by Tyriar** [comment]
Are you using the 64-bit version of VS Code? (Check Help > About)

Also can you share your settings.json file?
