### ISSUE TITLE
Preferences menu shows open recent

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69189]
1. VSCode out of source
2. Preferences menu > it shows the recently opened list

![screenshot 2019-02-22 at 09 04 01](https://user-images.githubusercontent.com/1926584/53228252-ed82d900-3680-11e9-96a1-6e7a701b2c75.png)

**Comment by bpasero** [comment]
I cannot reproduce, so removing "important".

**Comment by isidorn** [comment]
Can not repro after running yarn. Sorry
