### ISSUE TITLE
vscode overwrites externally edited filed

### ISSUE THREAD

**Issue by tradeA** [Microsoft/vscode#69180]
- VSCode Version: Version: 1.31.1
- OS Version: Linux x64 4.4.0-141-generic
Much like #41120, which was closed (hence, I couldn't comment)
1. opened some files vscode
2. edited them externally
3. reopened them in vscode, and everything was overwritten to the version that was last viewed in vscode

This is 10 hours of time-critical work! Is there way I can recover my files?

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@tradeA can you distill more specific steps to reproduce? does it happen all the time?

**Comment by tradeA** [comment]
Here is what seems to produce this problem,
1. open a file in vscode and make an edit ___but don't save___
2. close vscode
3. open the same file in another editor and make more edits
4. save and close that editor 
5. open vscode (at this point you will not see your most recent edits)
6. opening the same file in another editor will also not show the most recent edits

**Comment by bpasero** [comment]
@Tyriar annoying data loss, this is still https://github.com/Microsoft/vscode/issues/15749
