### ISSUE TITLE
when terminals opened in multi view first terminal screen went black after some time while 2nd terminal is working fine. 

### ISSUE THREAD

**Issue by krajr97** [Microsoft/vscode#69188]
i'm using two terminal at the same time . one for angular server localhost and one for my node js server localhost . to monitor each terminal's activity i open two terminals side by side but after some time while 2nd terminal is working fine first terminal (angular server) goes full black screen however angular server is still listening and working technically . please fix this issue asap as i have to restart everytime this happens. thank you microsoft in advance for assistance.
![screenshot 89](https://user-images.githubusercontent.com/22749307/53226873-8a09a300-36a2-11e9-9f01-1fc5c97d3627.png)

**Comment by postspectacular** [comment]
FYI. this also happens w/ just a single terminal instance, though i've yet not figured out the pattern... the terminal is just blank (even if there was previous output) and none of the toolbar buttons are responsive (i.e. clicking the trashcan does nothing).

FWIW. i've only encountered this issue after updating VSCode to latest stable and OSX (10.14.3) (both updated on same day)...

**Comment by Tyriar** [comment]
OP is likely seeing https://github.com/Microsoft/vscode/issues/68721
