### ISSUE TITLE
C# syntax highlight does not work properly

### ISSUE THREAD

**Issue by xcap2000** [Microsoft/vscode#69184]
- VSCode Version: 1.31.1
- OS Version: Debian 9 (Stretch)

Steps to Reproduce:

1. Create C# Contact class accepting string name and int phone.
2. Put its contructor's parentheses and parameters on its own lines.

Working Scenario:
![image](https://user-images.githubusercontent.com/620133/53216711-411b0580-3634-11e9-8657-b7aa40d7c88a.png)

Problematic Scenario:
![image](https://user-images.githubusercontent.com/620133/53216771-6f98e080-3634-11e9-88a9-3650028d2f54.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/OmniSharp/omnisharp-vscode

**Comment by xcap2000** [comment]
@Tyriar Would you be so kind as to provide a direct link to the duplicated issue so that I can subscribe to it and know when it is solved?

**Comment by Tyriar** [comment]
@xcap2000 C# support is handled by this extension: https://github.com/OmniSharp/omnisharp-vscode, there is a very barebones grammar built-in but support beyond that is up to the extension and their team.
