### ISSUE TITLE
VSCode is slow when used as the git editor

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/vscode#69182]
- VSCode Version: 1.31.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Set vscode as default git editor: `git config --global core.editor "'C:\Users\john\AppData\Local\Programs\Microsoft VS Code\Code.exe' --wait --new-window --disable-extensions"`
2. cd into a repo and do `git commit --amend`

It takes ~5 seconds to open an empty vscode window, which seems a bit slow (my machine is reasonably fast).

Let me know if you want me to record traces, and how.

**Comment by Tyriar** [comment]
Can you follow https://github.com/Microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers to get startup timers?

**Comment by cdmihai** [comment]
## System Info

* Code: 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60)
* OS: win32(10.0.17763)
* CPUs: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz(12 x 3492)
* Memory(System): 31.90 GB(16.35GB free)
* Memory(Process): 191.61 MB working set(191.61MB peak, 169.34MB private, 43.38MB shared)
* VM(likelyhood): 0%
* Initial Startup: false
* Has 2 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                    | Duration | Process          | Info                                       |
| ------------------------------------------------------- | -------- | ---------------- | ------------------------------------------ |
| start => app.isReady                                    | -        | [main]           | initial startup: false                     |
| nls:start => nls:end                                    | -        | [main]           | initial startup: false                     |
| require(main.bundle.js)                                 | -        | [main]           | initial startup: false                     |
| app.isReady => window.loadUrl()                         | -        | [main]           | initial startup: false                     |
| require & init global storage                           | 45       | [main]           | initial startup: false                     |
| window.loadUrl() => begin to require(workbench.main.js) | 1258     | [main->renderer] | NewWindow                                  |
| require(workbench.main.js)                              | 1319     | [renderer]       | cached data: YES                           |
| init global storage                                     | 14       | [renderer]       | -                                          |
| require workspace storage                               | 9        | [renderer]       | -                                          |
| require & init workspace storage                        | 10       | [renderer]       | -                                          |
| init workspace service                                  | 12       | [renderer]       | -                                          |
| register extensions & spawn extension host              | 2309     | [renderer]       | -                                          |
| restore viewlet                                         | 0        | [renderer]       | -                                          |
| restore panel                                           | 0        | [renderer]       | -                                          |
| restore editors                                         | 1149     | [renderer]       | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                  | 1232     | [renderer]       | -                                          |
| workbench ready                                         | 3880     | [main->renderer] | -                                          |
| extensions registered                                   | 5112     | [renderer]       | -                                          |

## Extension Activation Stats

| Extension                         | Eager | Load Code | Call Activate | Finish Activate | Event               |
| --------------------------------- | ----- | --------- | ------------- | --------------- | ------------------- |
| vscode.debug-auto-launch          | true  | 31        | 0             | 5               | *                   |
| vscode.emmet                      | true  | 37        | 1             | 4               | *                   |
| vscode.git                        | true  | 64        | 3             | 184             | *                   |
| vscode.merge-conflict             | true  | 33        | 1             | 16              | *                   |
| vscode.extension-editing          | false | 103       | 0             | 4               | onLanguage:markdown |
| vscode.markdown-language-features | false | 173       | 4             | 0               | onLanguage:markdown |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1550186450965	0	0
main:appReady	1550186451065	100	100
willLoadMainBundle	1550186451068	3	103
didLoadMainBundle	1550186451310	242	345
willRequireSQLite	1550186451381	71	416
main:willInitGlobalStorage	1550186451381	0	416
didRequireSQLite	1550186451398	17	433
willSetupSQLiteSchema	1550186451410	12	445
didSetupSQLiteSchema	1550186451425	15	460
main:didInitGlobalStorage	1550186451426	1	461
main:loadWindow	1550186451523	97	558
main:loadWindow	1550254935388	68483865	68484423
main:loadWindow	1550274040847	19105459	87589882
main:loadWindow	1550795224059	521183212	608773094
main:loadWindow	1550795591183	367124	609140218
main:loadWindow	1550796503886	912703	610052921
main:loadWindow	1550879874441	83370555	693423476
renderer/started	1550879875669	1228	693424704
willShowPartsSplash	1550879875684	15	693424719
didShowPartsSplash	1550879875686	2	693424721
willLoadWorkbenchMain	1550879875699	13	693424734
didLoadWorkbenchMain	1550879877018	1319	693426053
main/startup	1550879877018	0	693426053
willInitWorkspaceService	1550879877065	47	693426100
willInitGlobalStorage	1550879877065	0	693426100
didInitWorkspaceService	1550879877077	12	693426112
didInitGlobalStorage	1550879877079	2	693426114
willInitWorkspaceStorage	1550879877079	0	693426114
willRequireSQLite	1550879877079	0	693426114
didRequireSQLite	1550879877088	9	693426123
didInitWorkspaceStorage	1550879877089	1	693426124
willStartWorkbench	1550879877089	0	693426124
willRestoreEditors	1550879877160	71	693426195
LifecyclePhase/Ready	1550879877165	5	693426200
willLoadExtensions	1550879877244	79	693426279
willSetupSQLiteSchema	1550879877248	4	693426283
didSetupSQLiteSchema	1550879878232	984	693427267
didRestoreEditors	1550879878309	77	693427344
LifecyclePhase/Restored	1550879878309	0	693427344
didStartWorkbench	1550879878321	12	693427356
extensionHostReady	1550879879550	1229	693428585
didLoadExtensions	1550879879553	3	693428588
LifecyclePhase/Eventually	1550879880810	1257	693429845
```
