### ISSUE TITLE
terminal text are not in the same line

### ISSUE THREAD

**Issue by litong534** [Microsoft/vscode#69197]
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3

Steps to Reproduce:

1.
```code
  "terminal.external.osxExec": "iTerm.app",
  "terminal.integrated.shell.osx": "/bin/zsh",
  "terminal.integrated.fontSize": 13,
  "terminal.integrated.fontWeight": "bold",
  "terminal.integrated.lineHeight": 2,
```
these are my settings in settings.json, after updated my vscode I found that my terminal shows like this
2.
<img width="250" alt="wx20190222-181004 2x" src="https://user-images.githubusercontent.com/9899445/53235605-3791ac00-36cd-11e9-809d-c5002ecfcd9b.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/68045
