### ISSUE TITLE
Terminal: refresh problem

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#69199]
- VSCode Version: 1.31.1 (1.31.1)
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. open a terminal
2. type nano ~/bash_profile to edit the profile
3. move the cursor to the end of the file
4. now use the up cursor to move up a few pages

What happens?
Some part of the display isn't refresh correctly:

![vscodeterminalrefresh](https://user-images.githubusercontent.com/199648/53236811-786dce80-3695-11e9-9523-7e4f1b965ea2.gif)

The problem doesn't happen with default Mac Terminal app, nor with iTerm.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eddyb** [comment]
Originally posted in #69248:
I may have a simple reproduction (assuming this is the same problem): `clear -x; echo test; clear -x`.

In konsole, this results in `test` being present in the scrollback, but in VS Code's terminal, "test" is being overwritten by the second `clear -x`.

To reproduce without using `clear -x`:
```sh
echo -ne '\e[H\e[2J test \e[H\e[2J'
```

**EDIT**: as a workaround (in my build tasks, specifically), I do this:
```sh
yes '' | head -n $(tput lines) && clear -x
```

**Comment by Tyriar** [comment]
This appears to be fixed now

**Comment by eddyb** [comment]
@Tyriar On what version? My reproduction still works on 1.33.1.

**Comment by Tyriar** [comment]
I tested on 1.35.0-insiders https://code.visualstudio.com/insiders/
