### ISSUE TITLE
Extension host or language server unresponsive

### ISSUE THREAD

**Issue by amaneer94** [Microsoft/vscode#69194]
Issue Type: <b>Bug</b>

VS code intellisense usually does stop working (only loading shows in autocomplete). Git change detection tool also doesn't work properly. System is Ubuntu 16.04 LTS with 8GM RAM.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.4.0-141-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.66GB (1.06GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
randomeverything|hel|0.0.3
angular2-switcher|inf|0.2.0
cpptools|ms-|0.21.0
typescript-javascript-grammar|ms-|0.0.49
vscode-yaml|red|0.3.0
vscode-add-angular2-files|seb|2.0.1
autoimport|ste|1.5.3

</details>

**Comment by Tyriar** [comment]
@amadare42 what language are you trying to use?

@sandy081 maybe an ext host problem?

**Comment by sandy081** [comment]
@Tyriar Not sure unless we know what language extension it is and I would report the issue against it.

**Comment by emileber** [comment]
I'm having the same problem with `.js`, `.jsx` and `.scss` (though possibly others, these are just the ones that I use).

Using the `reload window` command makes it work again.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.90GB (39.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
snapshot-tools|asv|0.2.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
gitlab-workflow|fat|2.0.0
git-project-manager|fel|1.7.1
code-eol|jef|0.4.3
sublime-babel-vscode|jos|0.2.10
vscode-styled-components|jpo|0.0.25
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
material-icon-theme|PKi|3.6.3
polacode|pnp|0.2.2
stylelint|shi|0.48.0
gitconfig|sid|2.0.0
reopenclosedtab|uyi|1.1.0
vscode-import-cost|wix|2.12.0

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
@amadare42 what language are you trying to use?

**Comment by amadare42** [comment]
@amaneer94 looks like devs accidentally pinging me instead of you. Could you please answer their question about the language you are using? :)

**Comment by jrieken** [comment]
Thanks 🤦‍♂️

**Comment by amaneer94** [comment]
I am using typescript, js

**Comment by amaneer94** [comment]
@jrieken 
Also noted one more thing, when intelli-sense doesn't work, files are saved with delay of 800ms to 1second.

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by amaneer94** [comment]
what if I need those extensions too? :-)

**Comment by jrieken** [comment]
Well, if you disable an extension and the problem doesn't occur anymore then you should talk to the extension author, not us

**Comment by amaneer94** [comment]
OK. I hope VS code would have built-in tools that are commonly used by MEAN STACK developer.

**Comment by jrieken** [comment]
Closing because this issue isn't actionable.
