### ISSUE TITLE
TypeScript Autocomplete Import

### ISSUE THREAD

**Issue by ashot11091950** [Microsoft/vscode#69192]
Issue Type: <b>Bug</b>

After clicking 'Move to a new file', VSCode add import with text (import {Class} from "./Class") but after it there are recomendation to change "./Class" to './Class'

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:21:36.727Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.82GB (1.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
gitlens|eam|9.5.1
git-project-manager|fel|1.7.1
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
smarty|imp|0.3.0
vscode-duplicate|mrm|1.2.1
cpptools|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.2
material-icon-theme|PKi|3.6.3
LiveServer|rit|5.5.1
twig|wha|1.0.2
ReactSnippets|xab|2.3.0

</details>

**Comment by mjbvz** [comment]
Have you configured `"typescript.preferences.quoteStyle": "single"`?

**Comment by ashot11091950** [comment]
No

**Comment by mjbvz** [comment]
Try setting that

**Comment by ashot11091950** [comment]
Ok, thanks!
