### ISSUE TITLE
Changing modified tab circle color

### ISSUE THREAD

**Issue by webia1** [microsoft/vscode#69193]
First of all thank you for this great editor. A simple thing like changing the color of circle on modified tab should be possible (for those they need better contrast). Thank you for your effords,..

kind regards
@webia1

**Comment by webia1** [comment]
that's very pity :/

**Comment by UnknownMasterCoder** [comment]
This feature would be a nice one. Customizing just the modified circle would be nice to diff between the circle and the tab name.
Would it be useful if you guys decide to develop it
