### ISSUE TITLE
Strange maxVisible behaviour

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6919]
I would probably just adjust the height based on the number of things shown in the tree, independently from groups or not. Currently it does not seem to work reliably.

When setting maxVisible: 0 I would expect all elements to hide, like working files did. It is ok to ask the user for a restart in that case.

**Comment by joaomoreno** [comment]
Yes, when the value is `>0`, the number of visible items doesn't seem to match it at all.

Also, the setting's name is awkward, but I guess we're past the point where we can fix that. The documentation for it, though, could be much improved:

> Maximum number of open editors to show before scrollbars appear. If set to 0 open editors section gets hidden - only applied after VSCode restart.

How about:

> Maximum number of editors shown in the Open Editors pane. Set it to 0 to hide the pane.

Requiring a restart is incredibly bad UX, please just implement swapping out the contents of the viewlet with the split pane, and vice-versa, whenever the value toggles between `0` and non `0`.

**Comment by isidorn** [comment]
We can change the setting name - feedback is welcome. This is not public yet - why do you think we can no longer change that?

Will look into not requring a restart.

**Comment by joaomoreno** [comment]
I thought the setting was there already before this feature.

**Comment by isidorn** [comment]
It was called `explorer.workingFIles.maxVisible` we are changing it to `explorer.openEditor.maxVisible`, so if we want to change the name completley now is the time. So let me know your ideas.

**Comment by joaomoreno** [comment]
`explorer.openEditor.visible`

**Comment by isidorn** [comment]
`explorer.openEditors.visible` works for me. @bpasero let me know if you have some objections

**Comment by joaomoreno** [comment]
And message:

> Number of editors shown in the Open Editors pane. Set it to 0 to hide the pane.

**Comment by bpasero** [comment]
Didn't we agree that we want to avoid having 2 settings for the same thing? I think less settings are good, why introduce another one that you can do with maxVisible = 0?

+1 to do the UI update without restart.

**Comment by isidorn** [comment]
No, Joao does not want an aditional setting but just to change wording of `maxVisible` to `visible`

**Comment by bpasero** [comment]
Ah ok I like that 👍
