### ISSUE TITLE
Test: debug toolbar is contributable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69196]
Refs: #45116

- [x] any os @sandy081 
- [ ] any os @RMacfarlane

Complexity: 3

Now it is possible to contribute actions to the debug toolbar.
Write an extension and contribute a command with an icon the debug toolbar by using the `debug/toolbar` id.
It would be cool if your command actually takes the active debug session using the vscode api and does something with it.

Here's an example of how this looks in the extensions `package.json`, but try to be creative and change this as much as possible.

```
"contributes": {
		"commands": [
			{
				"command": "extension.closeAll",
				"title": "Close All Editors in Group",
				"icon": {
					"light": "media/closeall.svg",
					"dark": "media/closeall_inverse.svg"
				}
			}
		],
		"menus": {
			"debug/toolbar": [
				{
					"command": "extension.closeAll",
					"group": "navigation",
					"when": "debugType == node2"
				}
			]
		}
	}
```

fyi @weinand

**Comment by GordonSmith** [comment]
@isidorn - Having added the custom command to the `debug/toolbar` how does one handle that command inside the active debug session?

**Comment by isidorn** [comment]
@GordonSmith from next milestone please start using `debug/toolBar` since we are deprecating the old id.
Use context keys to control when to put your commands in the debug toolbar. You can not remove the default commands that are alrady there.

**Comment by GordonSmith** [comment]
@isidorn - Noted (but not answering my question, I will rephrase):  Having added a new custom command to the debug toolbar (in my case I want a "detach") how do I trap that command from within the active debug session?  I was kind of expecting a new virtual method similar to:  
* stepInRequest
* stepOutRequest
* stepBackRequest

Maybe:
* customCommandRequest 

???

**Comment by weinand** [comment]
@GordonSmith you have to implement and register a command. For details see this: https://code.visualstudio.com/api/extension-guides/command

**Comment by GordonSmith** [comment]
Ok - so basically I have to handle the command in my VS Code Client extension and then format a custom message and send that to my Debug Session (Server) - I don't think I have access to the vscode namespace there?  If I can register the handler directly in the Debug Server Session please let me know!

(This does feel a bit counter intuitive when you consider how all the other buttons on the debug/toolBar are handled and presented to the debug session via the DebugSession class)

**Comment by weinand** [comment]
With "Debug Server Session" you mean "debug adapter"?

**Comment by GordonSmith** [comment]
```
import { DebugSession } from "vscode-debugadapter";
import { ECLDebugSession } from "./ECLDebugSession";

DebugSession.run(ECLDebugSession);
```
Where 
```
export class ECLDebugSession extends DebugSession {
 ...
}
```

**Comment by weinand** [comment]
VS Code's extension API (and its contributable debug toolbar) are orthogonal (independent) to debug adapters and the corresponding node modules (like vscode-debugadapter). 

Since debug adapters exist independently from VS Code and are used in completely different eco-systems like Visual Studio, Vim, emacs, Eclipse they cannot talk to UIs directly. That's the reason why a debug adapter has no access to VS Code's extension API (in addition to the fact that DAs run as an independent process outside the extension host).

**Comment by GordonSmith** [comment]
Yup that was my understanding, so it sounds like my previous comment stands (handle command in vscode extension - create custom message and send to active debug session).
