### ISSUE TITLE
TypeScript: wrong strict null error

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69198]
Steps:
* uncomment `"./vs/workbench/electron-browser/window.ts"` in strictNull config
* run strict null checks

=> 🐛 

```
src/vs/workbench/electron-browser/window.ts:236:107 - error TS2345: Argument of type '(URI | undefined)[]' is not assignable to parameter of type 'URI[]'.
  Type 'URI | undefined' is not assignable to type 'URI'.
    Type 'undefined' is not assignable to type 'URI'.

236  		const listenerDispose = this.editorService.onDidCloseEditor(() => this.onEditorClosed(listenerDispose, resourcesToWaitFor, waitMarkerFile));
```

How can `const resourcesToWaitFor = filesToWait.paths.map(p => p.fileUri);` ever be `URI[] | undefined`?

Maybe came in with the recent TS update?

**Comment by alexandrudima** [comment]
@bpasero I think the new compiler is smarter and double checks inside implementations:

It looks like URI.revive can return undefined if passed in undefined (the first if). And it looks like `IPathData.fileUri` is optional.

```
	static revive(data: UriComponents | any): URI {
		if (!data) {
			return data;
		} else if (data instanceof URI) {
			return data;
		} else {
			let result = new _URI(data);
			result._fsPath = (<UriState>data).fsPath;
			result._formatted = (<UriState>data).external;
			return result;
		}
	}
```
