### ISSUE TITLE
updateChannel reset to stable on restart

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vscode#692]
I tried to change `updateChannel` in the `storage.json` file from `stable` to `none` as described [here](https://code.visualstudio.com/Docs/supporting/FAQ). As soon as I restart Visual Studio Code the value in the file is changed back to `stable`.

**Comment by joaomoreno** [comment]
Unfortunately, you've got to make sure to close VS Code before changing the `storage.json` file. This will soon change.

**Comment by pascalberger** [comment]
Unfortunately I also doesn't work if Code is closed.

- Close Visual Studio Code
- Run the following PowerShell Script
  ```
$codeSettingsPath = $(Join-Path $env:APPDATA "code") 
$storageFilePath = $(Join-Path $codeSettingsPath "storage.json")

$storageFileContent = ConvertFrom-Json "$(Get-Content $storageFilePath)"

$storageFileContent.updateChannel = "none"

$storageFileContent | ConvertTo-Json | Out-File $storageFilePath
  ```
- Open Visual Studio Code
- `updateChannel` is set back to `stable`

Installed Visual Studio Code is at 0.9.2.0 and OS is Windows 8.1

**Comment by joaomoreno** [comment]
If you use Notepad, does it work? Are you sure there are no Code.exe processes running in the background?

**Comment by pascalberger** [comment]
It works if editing with Notepad. So seems to be a problem with the way the PS writes back the JSON

**Comment by joaomoreno** [comment]
I know [Powershell is keen on putting UTF BOMs in everything](http://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom).

**Comment by pascalberger** [comment]
Yeah, the written file is Unicode. The storage.json needs to be an ANSI encoded file?

**Comment by joaomoreno** [comment]
[A JSON document must be Unicode encoded always. But it does not support BOM.](http://tools.ietf.org/html/rfc4627#section-3)

**Comment by pascalberger** [comment]
Thanks it works if I use `Set-Content` (which encodes it in Ascii) instead of `Out-File`.
