### ISSUE TITLE
debug console shows top of window every time entering expression in console

### ISSUE THREAD

**Issue by XiaodiJin** [Microsoft/vscode#69207]
- VSCode Version: 1.32.0-insider
- OS Version: ubuntu 18.04

Steps to Reproduce:

1.I'm working a project with py3.6.7 
2. When I debugging at a breakpoint, and enter an expression in debug console and Enter, the console will show values of expression, this works well;
3. However, every time I enter expression, console will return the top of console output window, I must scroll it to bottom to check value.
4. This problem only occurs in 1.32.0-insider, 1.31.0 does not have this problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Can you attach a gif / video showing this
Also please try tomorrow's vscode insiders, we did some changes to the debug console which might influence this.

**Comment by XiaodiJin** [comment]
@isidorn  It works well now. Thank you.
