### ISSUE TITLE
Move polling based file listener into file service

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#69205]
Move polling based file listener into file service. Follow up item from the fix of https://github.com/Microsoft/vscode/issues/68351

**Comment by sandy081** [comment]
@bpasero Are you sure you want to replace the existing listener with this polling listener?

**Comment by bpasero** [comment]
@sandy081 no, I was not suggesting that. I was suggesting to add an option to the watch method to use a polling solution (disabled by default).

**Comment by sandy081** [comment]
@bpasero I revisited the fix I did in #68351. I figured out that just using the existing watcher from the file service is enough to fix instead of using a polling based file watcher. Not sure why I did not try that while fixing it before. It leaves only output services need polling listener because of spdlog. I do not think replacing existing watcher with polling based watcher just because of spdlog. So, I would not move the polling listener to file service until we have a second usecase.
