### ISSUE TITLE
Git status bar fails to track current branch

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#69208]
Issue Type: <b>Bug</b>

Switching branches in a terminal panel, or external terminal, fails to update the current branch indicator in the lower left of the window. Switching branches by clicking on the current branch, and choosing a branch in the menu that appears, does update the status bar.

VS Code version: Code - Insiders 1.32.0-insider (b64026839eed3dd03a6d6fe0ba3910255490c279, 2019-02-22T08:34:22.116Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|32.00GB (16.09GB free)|
|Process Argv|-psn_0_10361313|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
auto-rename-tag|for|0.0.15
csharpextensions|jch|1.3.0
Angular2|joh|7.0.1
azure-account|ms-|0.8.0
csharp|ms-|1.18.0-beta7
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.2
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
quicktype|qui|12.0.46
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.3

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
Nope, not a duplicate of those.

**Comment by joaomoreno** [comment]
Same root cause as #69149
