### ISSUE TITLE
Git source control provider too big

### ISSUE THREAD

**Issue by LeNouveau** [Microsoft/vscode#69210]
Every time I reopen the Git panel, it is reset to default size. 
And probably because I have submodules, but "Source Control Panel" takes (almost) all the high. 

To illustrate : 
![image](https://user-images.githubusercontent.com/3670305/53245545-49178b80-36ae-11e9-81e3-d6cefd3366a8.png)
To view changed files, I have to drag "IoT Localhost GIT" higher. 

Solutions : 
- Save the position (probably better)
- Only take required high for Source Controller Providers (but could be the same problem with huge among of submodules)

Configuration : 
Version: 1.32.0-insider (system setup)
Commit: aeaef41d51201e555735f5e8d2f38a9d0ddb9026
Date: 2019-02-20T06:17:32.389Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Regards, 
LeNouveau

**Comment by joaomoreno** [comment]
Fixed by #49054
