### ISSUE TITLE
Breadcrumb dropdown sort by type

### ISSUE THREAD

**Issue by CoderJason123** [Microsoft/vscode#69215]
Love the breadcrumbs!  Didn't realize they were clickable, which turned out to be an awesome discovery.  

It would be great for a future version if the types could be sorted in the breadcrumb tree -- maybe grouped by "type".  For example.... all fields sorted together, all methods sorted alphabetically together.  

Thanks for the great features and keeping VS code loading and running fast.  Always always super important.

**Comment by gjsjohnmurray** [comment]
Did you discoverthe ```breadcrumbs.symbolSortOrder``` setting? Try typing 'breadcrumb' into the search box on the Settings page.

**Comment by CoderJason123** [comment]
That's awesome!  Definitely missed that.  Fantastic feature.  Thank you.
