### ISSUE TITLE
Tasks, integrated terminal, command without extension results in exit code 2

### ISSUE THREAD

**Issue by Antriel** [Microsoft/vscode#69213]
Issue Type: <b>Bug</b>

With the following task setting:
```
{
    "label": "My Task",
    "type": "process",
    "command": "program",
    "problemMatcher": []
}
```
Where `process.exe` is in the cwd, the task will result in `The terminal process terminated with exit code: 2`. Renaming command to `program.exe` works.
I think it might have something to do with situations where there's `<name>.exe` executable and `<name>/` folder in the same location (Windows).

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (5.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.11.2
vshaxe|nad|2.6.0
spellchecker|swy|1.2.13
codedox|wig|1.2.9

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@alexr00 might have regressed?

Before:

https://github.com/Microsoft/vscode/blob/c0c9ea27d6e8d660d8716d7acee82cf3c00fa3e5/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L512

After:

https://github.com/Microsoft/vscode/blob/0bcaf897a59fbeafc18758c70bafe2bb9b6bcb6d/src/vs/workbench/contrib/tasks/electron-browser/terminalTaskSystem.ts#L791

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/node-pty/issues/112

**Comment by alexr00** [comment]
@Antriel, this matches the behavior of cmd.exe. If you just try to execute your exe by name only (without the extension) from the command line or from the Windows Run dialog then it will usually not work using tasks.

**Comment by Gama11** [comment]
Hm, I'm struggling to reproduce that behavior in cmd.exe:

![](https://i.imgur.com/IOQWzNt.png)

**Comment by alexr00** [comment]
Is haxe added to your path? When I was testing this it didn't seem to be related to having a directory with the same name. For example, I copied and renamed notepad.exe then tried to run it using `c:\users\alros\renamedNotepad`. That doesn't run, but when I try running `c:\users\alros\renamedNotepad.exe` it does work.

**Comment by Gama11** [comment]
Hm... I'm struggling to get a copied notepad.exe to run at all. `haxe` was in my PATH in that example, but that doesn't seem to make any difference:

```batch
C:\Users\Jens\GitHub\haxe>copy haxe.exe haxe2.exe
        1 file(s) copied.

C:\Users\Jens\GitHub\haxe>haxe2 -version
4.0.0-rc.1+2316b62be
```

____

The original issue here with tasks definitely is related to there being a directory of the same name. This works:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "My Task",
			"type": "process",
			"command": "haxe",
			"args": ["-version"],
			"problemMatcher": []
		}
	]
}
```

```
> Executing task: C:\Users\Jens\GitHub\haxe\haxe.exe -version <

4.0.0-rc.1+2316b62be
```

However, that same task stops working once I create a directory named `haxe` in `C:\Users\Jens\GitHub\haxe`:

```
> Executing task: C:\Users\Jens\GitHub\haxe\haxe -version <

The terminal process terminated with exit code: 2
```

**Comment by Gama11** [comment]
(actually, that previous example was a bit silly, of course renaming the .exe couldn't have made any difference as it's still in the same directory that is in `PATH`. However, even after making sure it's not in my `PATH`, I was unable to find a case where `command.exe` works while `command` fails)
