### ISSUE TITLE
Set Language Mode from cli

### ISSUE THREAD

**Issue by jjavierdguezas** [Microsoft/vscode#69212]
It would be nice if we can set the language mode from the cli and open a file, no mater the extension, and see the content as if we open the file and change the language mode (to see the syntax colors, the ability to format the file, etc)

This would be util for example in a task that make a curl request and pipe the output to vscode. If the response if a json it would be nice open it and format it quickly

`curl --request GET --url http://get/json/url | code - --lang-mode json`

or

`code json.txt --lang-mode json` and open json.txt file as a json

**Comment by usernamehw** [comment]
#61804
