### ISSUE TITLE
inbuilt terminal input scrolled at bottom

### ISSUE THREAD

**Issue by rohansohonee** [Microsoft/vscode#69216]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new or even existing terminal in VSCode.

![terminal](https://user-images.githubusercontent.com/20875177/53249756-f1454880-36de-11e9-9da7-adbff5fe014e.jpg)

- Entering commands like this is very annoying. The cursor always is starting from below the terminal line as shown in the above image.
- The issue get's resolved after entering the very first command, but reappears only if you close the terminal and bring it back up again, which I do mostly and thus the frustration.

- There were never any problems such as this before with the terminal.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
