### ISSUE TITLE
Allow to use markdown in notifications

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#69214]
Version: 1.32.0-exploration (user setup)
Commit: 7ecc511083c881fa4319f35f743f5ea43e01bf49
Date: 2019-02-22T08:53:52.866Z
Electron: 4.0.5
Chrome: 69.0.3497.106
Node.js: 10.11.0
V8: 6.9.427.24-electron.0
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/30497573/53248423-9b0be180-36ad-11e9-80c7-a0694f2ba0ee.png)

Steps to Reproduce:

1. Get yourself a notification with markdown code, in my case I used the token notification
2. Look at markdown code not renderedm in this case it is the backticks not making `editor.maxTokenizationLineLength` not monospace.

Does this issue occur when all extensions are disabled?: Yes

**Comment by glouischandra** [comment]
Is there any recommendation of showing code snippet in VSCode Plugin?
