### ISSUE TITLE
Deselect Left Nav?

### ISSUE THREAD

**Issue by SeaDude** [Microsoft/vscode#69217]
- VSCode Version: 1.31.1
- OS Version: Windows 10

## Issue

- My left navigation (Explorer) is filled with folders. 
- I'm using Blueprint Folder Templates extension which requires you to right click in the Explorer and choose `Create File From Template`
- PROBLEM: There is no blank space in my Explorer to right click on to Create File From Template.

## Question:

- How do I right click on blank space in the Explorer so I can Create File From Template at the root of my Explorer?
- Wherever I right click, a folder is selected. 
- Need blank space!!

## Example:
- No blank space in Explorer:
![image](https://user-images.githubusercontent.com/8636973/53250638-a5a78600-366f-11e9-8143-7b2eee672452.png)
- Whenever I right click and select Create File From Template, it places the folder IN THE FOLDER I CLICKED ON rather than at the ROOT OF MY EXPLORER
![image](https://user-images.githubusercontent.com/8636973/53250739-db4c6f00-366f-11e9-8e3a-4ea69b533e22.png)

**Comment by isidorn** [comment]
There some old bug similar to this.
I have no clue what is the actual name but there is one. If you want to find it search for all issues with tag file-explorer
