### ISSUE TITLE
PHP autocompletion shouldn't work outside <?php ?> tags or should add <?php $code ?> automatically

### ISSUE THREAD

**Issue by pycarlos** [Microsoft/vscode#69218]
Issue Type: <b>Bug</b>

I have created file.php and I try to write an php expression vscode list all available commands but I think outside the `<?php ?>` shouldn't list it because it will not work.

Or if I select for example and echo outside the `<?php ?>` should add 
`<?php echo | ?>`  as sublime text do.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-blade|cjh|1.1.2
dart-code|Dar|2.23.1
flutter|Dar|2.23.1
EditorConfig|Edi|0.13.0
VS-code-drupal|mar|0.0.12
VS-code-vagrantfile|mar|0.0.7
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
python|ms-|2019.1.0
sublime-keybindings|ms-|4.0.0
php-docblocker|nei|1.7.0
vetur|oct|0.16.2
vscode-yaml|red|0.3.0
vscode-icons|rob|8.2.0
vscode-fileutils|sle|2.13.5
vscode-djaneiro|the|1.4.2
gitblame|wad|2.6.3
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by roblourens** [comment]
I recommend disabling the builtin php intellisense with `php.suggest.basic` because it is very simple, and using an extension such as "PHP Intellisense" which is smarter
