### ISSUE TITLE
Issues #69162 marked as caused by extension but doesn't appear to be?

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#69211]
Issue Type: <b>Bug</b>

I authored issue #69162, and vscode bot has closed it as being caused by an extension, but I just tried the issue again with all extensions disabled and it's still there.

I know Omnisharp provides a lot of code insights/services to VSCode, but it seems syntax coloring is not part of it? Or am I missing something?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexr00** [comment]
Closing and reopening the original.
