### ISSUE TITLE
Keep .js file & breakpoints open when rebuilding with tsc

### ISSUE THREAD

**Issue by RichardJECooke** [Microsoft/vscode#6921]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Write any .ts file
2. Compile it
3. Open the compiled .js file and add a breakpoint
4. Delete the compiled .js output and compile again
5. VSCode closes the .js file and loses all breakpoints. Now you have to navigate all the way through your folder tree to find and open the file, and readd all your breakpoints. This gets exponentially more tedious in large projects.

**Comment by isidorn** [comment]
I understand the pain point but our main scenario with ts is to use source maps.

**Comment by RichardJECooke** [comment]
I'm sorry but I don't understand. Are you saying somehow I can use a map to put my breakpoints in the .ts file instead?

**Comment by isidorn** [comment]
Yes - please check this document https://code.visualstudio.com/Docs/editor/debugging ***JavaScript Source Maps*** section
