### ISSUE TITLE
Zen: searching while in zen mode looks weird

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69223]
Steps to Reproduce:

1. enter zen mode
2. cmd+shift+f to bring up search

🐛 

![image](https://user-images.githubusercontent.com/900690/53253571-dd3f1e00-36c1-11e9-931f-55fcd70c1e79.png)

**Comment by isidorn** [comment]
That is becuase of your theme.
Forwarding to @misoguy to potentially change the colors of our default theme - add some border colors if we think this is funky.

Here are the important colors for this
"editorPane.background"
"sideBar.background"

**Comment by misoguy** [comment]
@isidorn I think you meant @misolori 😅

**Comment by isidorn** [comment]
Yeah. Sorry miso crew.

**Comment by misoguy** [comment]
No worries 👍

**Comment by bpasero** [comment]
@isidorn so it is intentional that zen mode is preserved when opening a viewlet?

**Comment by isidorn** [comment]
@bpasero yes. Was always like that.
One does not simply exit zen mode like that

**Comment by bpasero** [comment]
Ah ok, so this is then indeed just color tweaks needed.

**Comment by misolori** [comment]
@bpasero what theme is this in? I'm not seeing this in our default light theme:

![image](https://user-images.githubusercontent.com/35271042/53371544-5c706400-3905-11e9-901d-799d52994879.png)

**Comment by bpasero** [comment]
@misolori default light+

I realized this is due to me configuring `"editorPane.background": "#f3f3f3"`
