### ISSUE TITLE
File is reopened after closing then switching viewlets

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#6922]
- VSCode Version:1.1.0-alpha
- OS Version: Windows 10

If I close a preview file, then switch from the explorer viewlet to another viewlet and then back to explorer, the file I closed reopens again:

![reopenfile](https://cloud.githubusercontent.com/assets/1704059/15577374/2cf62936-2354-11e6-86d3-24b68a739246.gif)

**Comment by bpasero** [comment]
@stevencl we briefly talked about this during my time in Edinburgh, the explorer is very keen on restoring the context you are in when switching views. 

Since now we have an explicit way of closing editors we should maybe revisit this.

**Comment by stevencl** [comment]
Right, but here the context when I leave the explorer is that there are no files open. So I would expect that remains when I go back to the explorer. But instead the file that I had closed before switching to another viewlet is reopened.

**Comment by bpasero** [comment]
@stevencl would you expect the explorer to also behave this way when it was not visible and you closed all files? So:
* open search
* open a file
* close the file
* focus explorer

=> should the last file opened in the explorer get visible again?

I now pushed a change to not reopen any file if you closed all files even if the explorer was not visible. I think that helps clearing the clutter.
