### ISSUE TITLE
Open "Big" Interactive Parameter Hints Widgets in Collapsed State

### ISSUE THREAD

**Issue by josebrwn** [microsoft/vscode#69227]
I see a [related issue](https://github.com/Microsoft/vscode/issues/13480) involving font size, however I would like to suggest that the parameter widget (intellisense box) open in an interactive collapsed state.

Problem: 

Currently the parameter hints widget is ginormous and pops up in an almost random fashion when working primarily with the keyboard (i.e. largely mouseless, vim-style editing). When it does start popping up, it is relentless and pops up for the exact same thing over and over while you're editing. The _worst_ problem is just how big it is. It obscures _fully a quarter of the editor screen_, on my laptop. 

Solution:

When the widget wants to display an enormous amount of information, the parameter hints widget should render itself smaller by opening it in an interactive, collapsed state consisting of a single line of (semi-opaque?) text or an ellipsis that the user could hover over to reveal.

Also, it might be nice to be able to simply toggle parameter hints on and off from the menu!

**Comment by octref** [comment]
https://github.com/microsoft/vscode/issues/16221 would solve this problem.
You can also use ESC to quit parameter hints.

If you have a better idea than #16221, please open a new issue or follow up with it. "Interactive" itself is very vague.
