### ISSUE TITLE
Logic around Explorer highlighting is unclear or buggy

### ISSUE THREAD

**Issue by joshball** [Microsoft/vscode#69225]
- VSCode Version: 1.31.1
- OS Version: 10.0.17134

Steps to Reproduce:
First, I haven't completely figured out how to make this deterministic.
Extensions are disabled and default dark theme is on (it happens with all themes)
Also, I have a keybinding which I will use in the reproducing
        "key": "ctrl+l",
        "command": "workbench.files.action.showActiveFileInExplorer",
        "when": "editorTextFocus && !editorReadonly"

1. Open a new directory in vs code with nothing in it.
2. In the Explorer, under the the "open folder bar?", click the File New Icon (not sure it matters that you do it this way), and create a three files in the directory.
3. Open all three 
4. Switch around your selections, focusing one, then another, and occasionally hit ctrl+l to show the active file in the explorer.
5. Eventually you will get to a state where the explorer shows the active file with a brighter highlight and yet has a dimmed highlight for another file that is open, but not in focus and no highlight for the third file that is open (and not in focus).

![image](https://user-images.githubusercontent.com/127526/53253872-76007a00-367f-11e9-868f-bfb6b77b80bd.png)

I am not sure if this is a bug or feature that I don't understand. If it is the latter, can you explain what the logic is behind it. Looking at https://code.visualstudio.com/api/references/theme-color#lists-and-trees, I imagine it is one of these states, but not sure which (without cloning an theme and messing around). But the logic probably should be documented. 

The catalyst for this question is that in real projects, there are many (dimly) highlighted files throughout my tree and it gets really confusing. I was hoping to turn it off (or at least understand it), if it is not a bug.

Thanks!

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Fixed in latest insiders
