### ISSUE TITLE
Twistie does not change on click

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69224]
1. Start debugging a simple javascript
```
console.log('hello');
debugger;
```
2. Type console in the repl and evaluate it
3. Expand it and some of its children. Notice how the twisties are not changing on click. They are constantly in the collapsed state (even though the object actually gets expanded)

**Comment by joaomoreno** [comment]
This is related to dynamic heights. First bad commit: https://github.com/Microsoft/vscode/commit/2b5beb356ce872b1ecf59f9dbce3ed12fb59c16c
