### ISSUE TITLE
Suggest widget: right-click select broken

### ISSUE THREAD

**Issue by Marko-Petek** [microsoft/vscode#69234]
- VSCode Version: 1.31.0
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Open Intellisense/Suggest widget so that at least two suggestions appear.
2. Right click an item that is not currently selected.

This used to select an item under the pointer without closing the widget and you could read the extended description. Now it inserts the suggestion under pointer (same as left click) and opens the context menu.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Actually not sure if that's how it should work? @joaomoreno what do other lists do?

**Comment by joaomoreno** [comment]
Other lists probably work fine. Right click on them sets the focus and doesn't change selection, it would work quite nicely here. But suggest disables all built-in mouse handling from the list, so we gotta copy that behavior over.

**Comment by octref** [comment]
I haven't found any other list where right click doesn't open a context menu. IMO right click should be associated with that action, not "selecting without committing an item in a list".
