### ISSUE TITLE
Diff should use both columns

### ISSUE THREAD

**Issue by pwinston** [Microsoft/vscode#69237]
When I have 2 editor panes/columns up and then bring up a diff, both columns of the diff appear in the first pane, and thus those diff's two columns are way too small. I have to resize that first pane and make it much bigger to see anything.

It would be nice if when viewing two panes a two-column diff would use *both* panes. After all if I have two panes up, I've probably sized them to both display one file each. So squeezing two columns (two files) into one pane is not going to fit.

**Comment by pwinston** [comment]
> * [Provide a way (command) to switch between panes of a diff view (#22412)](https://www.github.com/Microsoft/vscode/issues/22412)

Not the same thing. That's just about switching panes. This issue is that the 2-pane diff is visually squished into the space occupied by one pane of text. When the user had 2 panes already nicely sized to hold one column of text each.

**Comment by alexandrudima** [comment]
Unfortunately, that is not how our grid layout works. For example, one could have a grid layout configured like this:

![image](https://user-images.githubusercontent.com/5047891/53485910-c0bb3100-3a87-11e9-8802-1d3f46495206.png)

Also, the diff editor is a single editor in the sense that it gets one tab in the tab list and it can be closed by a single x button. Also, the scrollbar must be in sync...

All in all, I have to be honest and say that I don't expect us to ever implement the behaviour you suggest, where we would then need to have the diff editor depicted by two distinct tabs, which are somehow linked, when closing one the other one would need to close, etc.

**Comment by pwinston** [comment]
Thanks for the thorough explanation. It's a shame, because it is awkward and silly looking how the diff pops up squished and unusable when there's plenty of room on the screen. But I can't suggest the right way to fix it.
