### ISSUE TITLE
Can't run npm in visual stuido integrated terminal

### ISSUE THREAD

**Issue by endrik2700** [Microsoft/vscode#69235]
Open the terminal in visual studio
type in  command npm-start
type in npm install -g create-react-app 
try out npm -v

Just doesn't recognise npm, typical npm is not recognosed as a ... command

**Comment by endrik2700** [comment]
Well, can someone help me!?

**Comment by Tyriar** [comment]
What OS are you on? If you're getting this message it means that npm is not on the PATH.

**Comment by endrik2700** [comment]
Windows 10, it has worked in the VSC before. Probably the update messed something up. I can't even get my debugger to work in VSC:  {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }, standardised setting based on the support page. previously this worked, they were kind of deleted, typed in manually and it gives me a weird error message

**Comment by Tyriar** [comment]
Does it fix itself if you close all VS Code windows and open them again? (the environment doesn't refresh without a full restart)

Can you check your PATH environment variable in the terminal and see whether the npm path is missing? This is `echo %PATH%` if you're using cmd.exe

**Comment by endrik2700** [comment]
That's the result: %PATH%

Tried to install jquery in vsc with npm install. Says, it doesn't find the package.json

**Comment by Tyriar** [comment]
@endrik2700 if you're using powershell I think you use `$env:path`

**Comment by endrik2700** [comment]
PS C:\Users\endri> $env:path
C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\IDEMIA\AWP\Dlls;C:\Program Files\IDEMIA\AWP\Dlls;C:\Program Files\nodejs\;C:\Users\endri\AppData\Local\Microsoft\WindowsApps;;C:\Users\endri\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\endri\AppData\Roaming\npm

**Comment by Tyriar** [comment]
Where is npm installed and does the directory  show up in the path you just pasted in?

**Comment by endrik2700** [comment]
Should be global. Sent an order via the terminal: npm install --save npm-install-global. Saw errors couldn't find package.json...

**Comment by Tyriar** [comment]
npm must be on your path in order for it to be runnable in a terminal, this is an issue related to your environment/setup that you'll need to investigate yourself.
