### ISSUE TITLE
When using Quick Open, have last open file be the Default Selection.

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#6923]
When using <kbd>ctrl</kbd> + <kbd>p</kbd> OR <kbd>ctrl</kbd> + <kbd>e</kbd> to access "workbench.action.quickOpen" the default selection is the currently open file. When opening a file, the last file I want to open is the one currently open. Other Editors have the default set to the last open file, which is the second option for VSCode. 
- VSCode Version: 1.1.1-insider
- OS Version: Windows 10

Steps to Reproduce:
1. <kbd>ctrl</kbd> + <kbd>p</kbd> OR <kbd>ctrl</kbd> + <kbd>e</kbd>
2. The current file is the first selection.

**Comment by bpasero** [comment]
@gerane maybe what you actually want to use is Ctrl+Tab to quickly access the last opened file?

**Comment by gerane** [comment]
I use ctrl+tab, but I also use ctrl + p to search for files, and sometimes the file I am looking for is the last open file. So if I am unsure if the File I want was the last one I open, I usually would use Ctrl+P instead of ctrl+tab. I have a habit of using ctrl + p in this manner from other editors as well.

From a User's perspective, If I have a File open, and I use a command to Quickly Open a different File, having my first choice be the File I already have open is counter-intuitive and kind of goes against the Commands name "QuickOpen". 

Other editors use this behavior, and it just makes sense to have the Default be a File that the User might actually want to open. Having the Default as the currently open file, benefits the user 0% of the time. I recommended the last open file, because there is likely a very high percentage that it would be beneficial to the end user.

**Comment by bpasero** [comment]
@gerane can you give me an example of an editor that behaves the way you describe? Ctrl+P is mainly meant to start a search so I think for most users it does not matter what file you opened previously. For that usecase we have Ctrl+Tab.

**Comment by gerane** [comment]
Sublime Test and Atom both have this behavior, which I would say are the closest editors to Code. 

Ctrl+P is a quick search, but often times, the thing I am searching for might be the first or second selection. It would be beneficial for users if the default selection was something they might actually want to open, instead of the most convenient selection being something selected 0% of the time.

**Comment by bpasero** [comment]
Ok I see it now, i was not pinning the editors. I am not sure it is a good idea to remove the current editor from the list because someone might expect it to be there. We might need a setting for this to not break other users. So far noone complained about this, so it is not something very obvious to change it seems.

**Comment by thekidder** [comment]
Tried VS Code for the first time today and this confused me a fair bit. I'm very used to the Sublime/Atom behavior so I'm definitely biased; but it seems very odd that the first choice in this menu is something that will never be used. When is it useful to navigate to the file I'm already in? This behavior just adds another keystroke when I want to open a recently-accessed file.

**Comment by m3l7** [comment]
+1
I don't see any reasons on setting the current file as a first choice.

**Comment by bpasero** [comment]
Btw in Sublime Text when I do Cmd+P I see no file selected by default so I still have to arrow down to go to the previous file. In that regard I argue that ST and Code are identical: You need one arrow down to pick the previous file to open. The difference is that Code makes it explicit in what file you are currently in (by selecting it).

**Comment by m3l7** [comment]
nope.
in sublime text, even if no files are selected, you can press enter and the last file opened will be chosen.

**Comment by bpasero** [comment]
Wow, very intuitive...

**Comment by smarter** [comment]
This is also how buffer switching ("ctrl+x b") behaves in emacs

**Comment by morganhein** [comment]
I use CTRL+E/P to switch between editors often, and while using CTRL+TAB is the exact action I'm usually performing (open last editor), I agree that it makes it very weird to have the current open file be the default selection. In what context would that ever be helpful?

Personally I can see having the current editor/context as the second item (honestly I don't see a reason to have it listed at all in that dropdown, but that's a regression). IntelliJ, and all variants by default, highlights the last open file when using the CTRL+E hotkey, as an example.

**Comment by sapegin** [comment]
JetBrains behaves the same: selects the previous file by default.

**Comment by sapegin** [comment]
Actually there’s some code in [quickOpenController.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts) that supposed to do that but it’s not executed. If I comment these lines it works as expected (second file is selected):

```diff
             let autoFocus: IAutoFocus;
-             if (!quickNavigateConfiguration) {
-                 autoFocus = { autoFocusFirstEntry: true };
-             } else {
+             // if (!quickNavigateConfiguration) {
+             //  autoFocus = { autoFocusFirstEntry: true };
+             // } else {
                 const visibleEditorCount = this.editorService.getVisibleEditors().length;
                 autoFocus = { autoFocusFirstEntry: visibleEditorCount === 0, autoFocusSecondEntry: visibleEditorCount !== 0 };
-             }
+             // }
```

**Comment by ZackMFleischman** [comment]
+1 for this. It's driving me nuts

**Comment by jd20** [comment]
+1, very confusing coming from Sublime / Atom / JetBrains. This adds an extra key stroke, or forces you to use ctrl+tab, which doesn't see tabs that were opened in preview mode.

**Comment by bpasero** [comment]
The main reason why we do not select the second entry by default is because you can:
* hit `Cmd+P`
* leave the `Cmd` key pressed
* hit `P` again
* release all

and it will open the second file. I think that is a nice way of quickly selecting something without leaving the keys you are already using.

Nevertheless we could introduce a new command that people can use that would simply select the second entry by default.

**Comment by drehimself** [comment]
+1, I'm just trying out VS Code for the first time (coming from Sublime) and this is one of the first things I googled hoping there was an option for it.

**Comment by sanggonlee** [comment]
Hello, I tried to address this issue and created a pull request. Could anyone have a look?

**Comment by calebporzio** [comment]
+1

**Comment by cameront** [comment]
FWIW, I don't think a new command should be added that would select the second item by default.

But it is good to know that Cmd+P,P can come close to replicating the 'sublime/atom' behavior.

But even if you can progress down the list of open editors by continuing to hit P (while Cmd pressed), I still don't understand any use case for starting with the currently open editor.

The command for "Go To Current File" should be &lt;do nothing&gt;, &lt;wait&gt;, &lt;be happy&gt; 
:)

**Comment by bpasero** [comment]
You can assign `workbench.action.quickOpenPreviousEditor` for this purpose now. We also make sure that this gets into our Sublime and Atom keymap extension.
