### ISSUE TITLE
Using `nano` in terminal causes lines to be lost

### ISSUE THREAD

**Issue by zfields** [Microsoft/vscode#69248]
OS: Ubuntu 18.04
VSCode: 1.31.1

When you scroll up in the terminal window, lines get lost. They mostly reappear when scrolling down.

Arrowing up or down works appropriately.

**Comment by Tyriar** [comment]
Can you create a gif screen recording to show the problem? Not clear what the problem is exactly.

**Comment by zfields** [comment]
This is similar to my other post. You need 1000's of lines in the VSCode terminal application on a Linux machine. What steps are you using to reproduce this bug/behavior?

**Comment by Tyriar** [comment]
It's not clear to me what the problem is, you're not talking about lines from the top being cut off as designed are you (see the `terminal.integrated.scrollback` setting)?

**Comment by Tyriar** [comment]
After looking at https://github.com/Microsoft/vscode/issues/69249 I think that's you're problem. Add more lines to scrollback if you want to keep more around:

```
"terminal.integrated.scrollback": 10000
```

**Comment by zfields** [comment]
That is absolutely not the problem. The lines are there, they do not render correctly. They literally write over the top of each other.

Also, don't close an issue, unless you have confirmed it resolved.

**Comment by Tyriar** [comment]
Can you post a screenshot or screen recording?

**Comment by zfields** [comment]
I'll confirm this, but it naively it seems as if this begins to occur when the value of "terminal.integrated.scrollback" has been overrun, and terminal lines have been dropped from the window.

**Comment by Tyriar** [comment]
Please post some screenshots of screen recording illustrating the issue. I cannot reproduce this as the only steps you provides was scroll up and scroll down.

**Comment by zfields** [comment]
Are you using a Linux machine to reproduce, or at least a VM?

**Comment by Tyriar** [comment]
Yes

**Comment by zfields** [comment]
Okay. I will record the screen next time it happens

**Comment by zfields** [comment]
I have discovered this is more easily reproducible when you use `nano` to edit a file from the terminal.

**Comment by eddyb** [comment]
I'm not sure where the right place to report this is, but I may have a simple reproduction (assuming this is the same problem): `clear -x; echo test; clear -x`.

In konsole, this results in `test` being present in the scrollback, but in VS Code's terminal, "test" is being overwritten by the second `clear -x`.

To reproduce without using `clear -x`:
```sh
echo -ne '\e[H\e[2J test \e[H\e[2J'
```
