### ISSUE TITLE
Allow dropping tabs into an external editor

### ISSUE THREAD

**Issue by bricelam** [Microsoft/vscode#69242]
I just tried to drag and drop a tab into VS hoping it would open the file, but it didn't. 🙁

**Comment by bricelam** [comment]
Dragging and dropping an item from Explorer doesn't work either. 🙁

**Comment by isidorn** [comment]
Dragging from where to where exactly?
Can you reproduce with vscode insiders? https://code.visualstudio.com/insiders/
Has this ever worked?

**Comment by bricelam** [comment]
As far as I know, it has never worked. Here's a demo.

![demo](https://user-images.githubusercontent.com/1226749/53434709-0c001180-39ac-11e9-9ae6-e46f13f93ca1.gif)

**Comment by bricelam** [comment]
Out of scope? Lame. This should be as trivial as providing FileDrop data in addition to whatever else is already there. It would greatly improve interoperability.
