### ISSUE TITLE
Memory usage 100% in about 1-2 seconds debugging Python

### ISSUE THREAD

**Issue by rshaub** [Microsoft/vscode#69244]
Issue Type: <b>Bug</b>

I am debugging a single file and when I hover over an expression (msg_info) or if msg_info is in the watch window, python.exe eats all of my free ram within single-digit seconds.  After this my computer is completely unresponsive and I have to kill it with the power button.  Sometimes, I can kill python.exe from task manager if I'm lucky (and quick). This happens when I hit a breakpoint in an async method. The class this happens in is an overridden tornado TCPServer.  Enabling or disabling jedi made no difference.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q9500  @ 2.83GHz (4 x 2826)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.84GB free)|
|Process Argv|e:\Projects\PyLibBoonton55\PyLibBoonton.code-workspace|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
arepl|alm|1.0.10
vscode-python-docstring|aza|0.0.5
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.0
jupyter|don|1.1.5
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vscode-svn|eli|0.1.0
code-runner|for|0.9.7
shell-format|fox|4.0.4
language-cython|guy|0.0.5
beautify|Hoo|1.4.9
MeteorSnippets|jml|0.1.3
svn-scm|joh|1.47.1
electron-debug|kod|18.11.1
MagicPython|mag|1.1.0
meteor-package-intellisense|mat|1.1.0
dotenv|mik|1.0.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.2
Xel|noe|1.0.1
vscode-docker|Pet|0.5.2
meteorhelper|ram|0.1.5
vscode-icons|rob|8.2.0
viewmodel|Vie|2.1.3

vscodeintellicode|Vis|1.1.3
vscode-meteor|vuh|0.1.1
jinja|who|0.0.8

(1 theme extensions excluded)
</details>

Code below:
`
#!/usr/bin/env python3
import asyncio
try:
    import uvloop
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
except Exception:
    print("uvloop not available...")

from tornado.ioloop import IOLoop
from tornado.tcpserver import TCPServer
from bitarray import bitarray
from tornado.iostream import StreamClosedError  # , IOStream
import argparse
import struct

class HiSlipHeaderInfo(object):
    # Leave buf as None to initialize empty header
    def __init__(self, buf=None):
        self.msg_type = 0
        self.ctrl_code = 0
        self.msg_param = bitarray(32)
        for i in range(32):
            self.msg_param[i] = 0

        self.payload_len = 0
        self.err = 0
        self._buf = bytearray(16)
        if buf is not None:
            self.err = -1  # Error
            self._buf = buf
            if(len(self._buf) != 16):
                return
            if(self._buf[0] != b'H'[0] or self._buf[1] != b'S'[0]):
                return
            self.msg_type = int(self._buf[2])
            self.ctrl_code = int(self._buf[3])
            self.msg_param = bitarray(int.from_bytes(self._buf[4:8],
                                      byteorder='big', signed=False))
            self.payload_len = int.from_bytes(self._buf[8:16],
                                              byteorder='big', signed=False)
            self.err = 0  # Success

    def to_bytes(self):
        self._buf[0] = b'H'[0]
        self._buf[1] = b'S'[0]
        self._buf[2] = self.msg_type
        self._buf[3] = self.ctrl_code
        _param_int = struct.unpack(">I", self.msg_param)
        param_buf = _param_int.to_bytes(4, "big", signed=False)
        self._buf[4:4] = param_buf[0:4]
        payload_buf = self.payload_len.to_bytes(8, "big", signed=False)
        self._buf[8:16] = payload_buf[0:8]
        return self._buf

class HiSlipHandler(object):
    def __init__(self):
        #  Message handlers take a header and a payload.
        #  Then the handler takes whatever action is needed.
        #  If a return message is required, the handler method
        #  constructs the message and calls construct_msg to return
        #  a byte array. Otherwise, return None
        self._msg_handlers = {0: self.process_init,
                              2: self.process_fatal_err,
                              3: self.process_err,
                              4: self.process_async_lock,
                              6: self.process_data_msg,
                              7: self.process_data_end,
                              8: self.process_dev_clr_complete,
                              10: self.process_async_rem_cntl,
                              12: self.process_trigger,
                              15: self.process_async_max_size,
                              17: self.process_async_init,
                              19: self.process_async_dev_clr,
                              21: self.process_async_status_qry,
                              24: self.process_async_lock_info}
        self.max_msg_size = 256

    #  Use this method to create a message to send to the client
    def construct_msg(self, header_info, data_buf=None):
        #  Uncomment the line below to let intellisense know what's up
        #  hdr = HiSlipHeaderInfo()
        hdr = header_info
        if data_buf is None:
            hdr.payload_len = 0
            return hdr.to_bytes()
        else:
            hdr.payload_len = len(data_buf)
            msg_bytes = hdr.to_bytes() + data_buf
            return msg_bytes

    def get_msg_info(self, buf):
        retval = HiSlipHeaderInfo(buf)
        return retval

    def process_msg(self, header_info, payload=None):
        # TODO: Process messages keyed off of msg_type
        #  Uncomment the line below to let intellisense know what's up
        #  hdr = HiSlipHeaderInfo()
        hdr = header_info
        _meth_to_call = self._msg_handlers.get(hdr.msg_type)
        if _meth_to_call is None:
            return None
        else:
            retval = _meth_to_call(header_info, payload)
            return retval

    def process_async_max_size(self, header, payload):
        #  Handle HiSlip AsyncMaximumMessageSize msg
        #  Example case
        size = int.from_bytes(payload, byteorder='big', signed=False)
        self.max_msg_size = size
        hdr_info = HiSlipHeaderInfo()
        hdr_info.msg_type = 16  # AsyncMaximumMessageSizeResponse
        #  We can just reuse payload since it's the same value
        return self.construct_msg(hdr_info, payload)

    def process_init(self, header, payload):
        # TODO: Implement HiSlip Initialize msg
        pass

    def process_fatal_err(self, header, payload):
        # TODO: Handle HiSlip FatalError msg
        pass

    def process_err(self, header, payload):
        # TODO: Handle HiSlip Error msg
        pass

    def process_data_msg(self, header, payload):
        # TODO: Handle HiSlip Data msg
        pass

    def process_data_end(self, header, payload):
        # TODO: Handle HiSlip DataEND msg
        pass

    def process_async_lock(self, header, payload):
        # TODO: Handle HiSlip AsyncLock msg
        pass

    def process_async_lock_info(self, header, payload):
        # TODO: Handle HiSlip AsyncLockInfo msg
        pass

    def process_async_rem_cntl(self, header, payload):
        # TODO: Handle HiSlip AsyncRemoteLocalControl msg
        pass

    def process_async_dev_clr(self, header, payload):
        # TODO: Handle HiSlip AsyncDeviceClear msg
        pass

    def process_dev_clr_complete(self, header, payload):
        # TODO: Handle HiSlip DeviceClearComplete msg
        pass

    def process_trigger(self, header, payload):
        # TODO: Handle HiSlip Trigger msg
        pass

    def process_async_init(self, header, payload):
        # TODO: Handle HiSlip AsyncInitialize msg
        pass

    def process_async_status_qry(self, header, payload):
        # TODO: Handle HiSlip AsyncStatusQuery msg
        pass

class HiSlipServer(TCPServer):
    _debug = False
    _client_handlers = dict()

    async def handle_stream(self, stream, address):
        while True:
            try:
                # Uncomment below for intellisense help
                # mystream = IOStream(0)
                mystream = stream
                mystream.set_nodelay(True)
                header_len = 16
                # Read socket asynchronously
                header = await mystream.read_bytes(header_len,
                                                   partial=True)
                # Check if we have a handler for this client
                hndlr = HiSlipServer._client_handlers.get(address)
                if hndlr is None:
                    hndlr = HiSlipHandler()
                    HiSlipServer._client_handlers[address] = hndlr
                # Process the header
                msg_info = hndlr.get_msg_info(header)
                print(msg_info.msg_param)
                if msg_info.err == 0:
                    msg_len = msg_info.payload_len
                    payload = None
                    # If we have more to read, do it.
                    if msg_len > 0:
                        payload = await mystream.read_bytes(msg_len,
                                                            partial=True)
                    # Process the message with header and payload
                    data = hndlr.process_msg(msg_info, payload)
                    # If we have data, send it back
                    if data is not None:
                        await mystream.write(data)
            except StreamClosedError:
                # Not sure if this is the right action to take
                # probably a corner case if it isn't
                HiSlipServer._client_handlers[address] = None
                break

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--hshost", help="hislip host name")
    parser.add_argument("--hsport", help="hislip port number")
    parser.add_argument("--debug",
                        help="turn debug printing on.")
    args = parser.parse_args()
    hostname = args.hshost
    print("host: ", hostname)
    port = args.hsport
    print("port: ", port)
    if not(args.debug is None):
        HiSlipServer._debug = True
        print("debug printing on...")

    if port is None:
        port = 4880
    server = HiSlipServer()
    if hostname is None:
        # Bind to all interfaces
        server.listen(int(port))
    else:
        # Bind to specific host/ip address
        server.listen(int(port), address=hostname)
    IOLoop.instance().start()
`

**Comment by rshaub** [comment]
Which extension do you think it was caused by?

**Comment by weinand** [comment]
"python"
