### ISSUE TITLE
find previous in terminal does not work

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode#69249]
OS: Ubuntu 18.04
VSCode: 1.31.1

Using the find UI in the terminal will fail when you try to find previous (as in looking for the most recent errors or warnings in a compile log).

**Comment by Tyriar** [comment]
@zfields can you give some specific repro steps? I can't seem to reproduce the problem.

**Comment by zfields** [comment]
I have a make file that spews thousands of lines of compiler output. If I put a build flag (i.e. `-Werror`) in the `Ctrl+F` search box, and press the `<--` arrow, then it doesn't work (`-->` does work though). I just confirmed this behavior before responding, this is reproducible 100% of the time.

**Comment by Tyriar** [comment]
I suspect this is the same cause as https://github.com/Microsoft/vscode/issues/69248

**Comment by zfields** [comment]
Your suspicion is incorrect! Please reopen this. The terminal does not work and has not worked for a long time now.

I'm taking my time to help you improve your product, and this is a slap in the face.

**Comment by Tyriar** [comment]
Reopened the other issue

**Comment by zfields** [comment]
The issues are not duplicates, unless you can confirm they are. Since you don't seem to understand the other issue, then I cannot see how you could confirm them as duplicates.
Both issues involve the integrated terminal, but that is it. Please reopen.

**Comment by Tyriar** [comment]
@zfields if the lines are missing it completely makes sense that they would not show up in find previous.

**Comment by zfields** [comment]
Are you trolling me?

Have you attempted to reproduce this bug?
- [ ] Yes
- [ ] No

My guess would be, "No."

You are spending more effort trying to tell me it doesn't exist than reproducing it. Run a build that blows past your scroll back, then do a "find" that looks for `gcc` or something that will literally appear 10000 times. It will only find 2 or 3 max. I can see them - literally hundreds and hundreds - but the find back fails to find them.

My guess is that you are having an array indexing error. Why don't you try to reproduce it, instead telling me it couldn't possibly exist.

**Comment by Tyriar** [comment]
Find previous is broken for portions of lines that are wrapped: https://github.com/xtermjs/xterm.js/issues/1967
