### ISSUE TITLE
Cmd+C/Ctrl+C doesn't reach web view

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#6924]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Enterprise x64

Steps to Reproduce:

1. Use the command 'vscode.previewHtml' in our extension, like the sample code [vscode preview html sample](https://github.com/Microsoft/vscode-extension-samples/blob/master/previewhtml-sample/src/extension.ts).
2. In another panel will display the previewed html.

However, we can't copy the text from the previewed html in our test, even in the sample extension [Preview CSS Properties Sample](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-css-properties).

And I think we may have the requirements that, user wish to copy the text(maybe the previewed result is transformed output) in the preview panel.

**Comment by jrieken** [comment]
You can always ask for the context of a previewed document, using the underlying `TextDocument` and use a node module to copy this contents to the clipboard

**Comment by Huachao** [comment]
@jrieken, I still don't quite understand what is and how to get the context of a previewed document, could you please give me an example or more details? And I want to say it again that what I want is allow user to Ctrl+C of the previewed document. Thanks in advance

**Comment by jrieken** [comment]
You can always run [`openTextDocument`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3301) and copy the text of the returned document. 

The `previewHtml` command is producing a piece of UI and, as other UI pieces like the git or explorer viewlet, it not generally desirable to have a select all and copy gesture. Tho, I understand that there are cases in which it makes sense to have the contents selectable and copyable. I believe tho that only the extension can make that decision. 

The problem I see is that the `Cmd+C` doesn't travel to the web view container. Reopening to check if this is an issue with us or electron.

**Comment by jrieken** [comment]
@alexandrudima @bpasero It seems like something has changed here and that we now unconditionally eat up <kbd>Cmd+C</kbd>. Ideas?

**Comment by bpasero** [comment]
@jrieken I did not touch this recently, not sure about @alexandrudima. I know we do quite some dances in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L168 to know where to send the action to and we might not handle the webview case here.

Also there may be differences between Mac and Windows...

**Comment by bpasero** [comment]
I can reproduce already in our last release so it seems to be broken since we added the `webview` component. I can also reproduce on Windows and Mac so it does not seem Mac-Menu specific.

**Comment by bpasero** [comment]
@jrieken I think the issue is that we call `document.executeCommand("copy")` (or any of the other edit operations) and that just works in all cases even in `iframes`. Since the `webview` is out of process it just does not participate. 

I think the only way out is to install keybinding listeners within the `webview` and run `document.executeCommand()` within because I cannot even find out if a `webview` currently has focus (that is, `document.activeElement` does not return me a `webview` if focus is within).
