### ISSUE TITLE
Screen lock

### ISSUE THREAD

**Issue by cmguerra** [Microsoft/vscode#69243]
Issue Type: <b>Bug</b>

I've been working with SFDX and every time I split at least in two it block the second area and don't allow me to write in it

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tomcat|ada|0.11.1
apex-autocomplete|chu|0.2.13
apex-debug|chu|1.0.3
mavensmate|Dav|0.15.0
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-spring-boot|ecm|0.0.10
tslint|eg2|1.0.43
git-project-manager|fel|1.7.1
vscode-es6-string-html|hjb|1.1.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.4.0
vscode-manifest-yaml|Piv|1.4.0
vscode-spring-boot|Piv|1.4.0
material-icon-theme|PKi|3.6.3
java|red|0.39.0
vscode-java-checkstyle|ria|0.2.0
vscode-icons|rob|8.2.0
salesforcedx-vscode|sal|45.3.0
salesforcedx-vscode-apex|sal|45.3.0
salesforcedx-vscode-apex-debugger|sal|45.3.0
salesforcedx-vscode-apex-replay-debugger|sal|45.3.0
salesforcedx-vscode-core|sal|45.3.0
salesforcedx-vscode-lightning|sal|45.3.0
salesforcedx-vscode-lwc|sal|45.3.0
salesforcedx-vscode-visualforce|sal|45.3.0
vscode-checkstyle|she|1.0.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.4
quokka-vscode|Wal|1.0.189
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
