### ISSUE TITLE
Extreme slowness

### ISSUE THREAD

**Issue by ianstormtaylor** [microsoft/vscode#69256]
Issue Type: <b>Performance Issue</b>

I'm not sure exactly what causes this. But it seems like sometimes when I use multiple cursors (using `cmd-d`) afterwards it will cause VS Code to become super unresponsive. And it doesn't really ever recover. Even after hours.

I have a linter extension installed which runs often? And I also have Prettier running on every save? But I feel like I've had those for a while and this slowness has only happened over the past few months.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    82	   367	code main
    0	    33	   453	   gpu-process
    0	   557	   464	   window (home.js — contents)
    0	   229	   911	     extensionHost
    0	   508	   929	       electron_node tsserver.js 
    0	    66	   956	         electron_node typingsInstaller.js typesMap.js 
    0	    82	   936	       electron_node eslintServer.js 
    0	    33	  3915	       extensionHost
    0	    33	  4000	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=911
    0	    82	  5696	       extensionHost
    0	    82	  5697	       extensionHost
    0	    66	  8167	       extensionHost
    0	    33	 49458	       extensionHost
    0	    33	 61120	       extensionHost
    0	    33	 93219	       extensionHost
    0	    33	   915	     watcherService
    0	    66	   898	   shared-process
    0	    82	 19225	   window (Issue Reporter)
    0	     0	 19228	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (home.js — contents)
|    Folder (contents): 2634 files
|      File types: js(1429) yaml(1033) json(61) log(23) png(16) html(11)
|                  DS_Store(9) sketch(7) lock(6) env(5)
|      Conf files: package.json(56) webpack.config.js(2) settings.json(1);
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.0
EditorConfig|Edi|0.12.8
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
vscode-sql-template-literal|for|0.1.0
auto-rename-tag|for|0.0.15
graphql-for-vscode|kum|1.13.0
git-indicators|lam|2.1.1
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
debugger-for-chrome|msj|4.11.2
material-icon-theme|PKi|3.6.3
vscode-seedling-icon-theme|ras|0.2.0
sort-lines|Tyr|1.8.0
gitblame|wad|2.6.3
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|2.1.0
file-size|zh9|0.1.3

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@ianstormtaylor can you follow our wiki https://github.com/Microsoft/vscode/wiki/Performance-Issues to help troubleshoot?

**Comment by ianstormtaylor** [comment]
@rebornix oh wow, I followed the first step and didn't realize there were more! Sorry about that. I'll follow up with the extra information the next time I notice it happen, thanks!

**Comment by rebornix** [comment]
Sure, close it for now and we can reopen whenever we can.
