### ISSUE TITLE
Feature request: word wrapping config by document type

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#6925]
I always want markdown word-wrapped wrapped. I never want most other files wrapped. So I find myself switching back and forth all the time.

It seems like there is already some document-type specific configuration for html, e.g.

    // Maximum amount of characters per line (0 = disable).
    "html.format.wrapLineLength": 120,

The universal setting is named differently:

    "editor.wrappingColumn": 300,

It would be great if this convention were just standardized and applicable to any document type, and I could use `markdown.format.wrappingColumn` (or possibly any other known doc type, though I mostly just care about markdown) to control this per type.

**Comment by nchammas** [comment]
Hmm, I just tested out `html.format.wrapLineLength` and it didn't seem to do anything for me with an HTML file. I set the wrap line length to 70 characters but was able to type beyond that without any wrapping. Perhaps it doesn't do what we think it does.

**Comment by axefrog** [comment]
I've just spent the last 15 minutes looking for a solution to exactly the same problem as described in this issue. Both Atom and Sublime Text allow me to specify editor settings on a per-language basis.

**Comment by alexandrudima** [comment]
Let's track this in #2253
