### ISSUE TITLE
[Suggestion] SmartSelect: Select next/previous argument in function (to complement grow/shrink selection)

### ISSUE THREAD

**Issue by jotaf98** [microsoft/vscode#69252]
The grow/shrink selection shortcuts are great. However, with a (comparatively small) addition they could be used to go "anywhere" in the code, which would make them very powerful.

These two commands could be described intuitively as "next/previous selection", or "select next/previous argument".

An example, using square brackets to denote the selection. Initial selection (empty):
`my_function([]a, b*c, d)`
Expand selection:
`my_function([a], b*c, d)`
Next selection:
`my_function(a, [b*c], d)`

Growing/shrinking the selection can be seen as selecting the parent or child node in the AST (abstract syntax tree). Naturally, since some nodes in the AST have multiple children (e.g. a function with 3 arguments has 3 children, same with operators), if we could navigate between them we would be able to reach anywhere in the tree.

I think this hierarchical navigation could be very powerful. Thoughts?

**Comment by jrieken** [comment]
what version of vs code is that? what language is that?

**Comment by jotaf98** [comment]
Hi, I'm not sure it matters much since 1) it's a feature request so it doesn't exist in any version, 2) SmartSelect is a feature that exists across all supported languages.

In any case, I'm using VSCode 1.31.1 mostly for Python.

**Comment by jrieken** [comment]
It matter, because rewrote all of smart select in the last release. Also we have made API so that extensions can help the dump default implementation.

**Comment by jotaf98** [comment]
Thanks for clearing that up, it was naive of me to think the version didn't matter!

Reading about the SmartSelect rewrite (and the API for language-specific selections) is actually what prompted me to make this suggestion.

I noticed the inclusion of parent pointers in selections in #67872, thanks for following up on this! It seems that this structure will support lots of other powerful selection functions.
