### ISSUE TITLE
VSCode crashes with tcmalloc 4.2.6 on Ubuntu 16.04

### ISSUE THREAD

**Issue by mirsking** [Microsoft/vscode#69262]
- VSCode Version: code_1.31.1-1549938243_amd64.deb
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install vscode 1.30 and 1.31.1 on ubuntu 16.04 with tcmalloc 4.2.6 already installed.
2. Launch by command line `code`, it crashed with errror info: 
```
src/tcmalloc.cc:278] Attempt to free invalid pointer 0x16c4840b08d0 
/usr/bin/code: line 35:   182 Aborted                 (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
```
3. If I replace `/usr/lib/libtcmalloc.so.4.2.6` by `libtcmalloc.so.4.1.2`,  the crash can be worked around.

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
Does it crash when not launched through the command line? Also, could you see if it still reproduces using our exploration build which uses Electron 4? https://az764295.vo.msecnd.net/exploration/679127145ee0269021cdf123b1695b79e7792312/code-exploration_1.32.0-1551253863_amd64.deb
