### ISSUE TITLE
The cursor of integrated terminal has weird spacing when using powerline in wsl

### ISSUE THREAD

**Issue by M0gician** [Microsoft/vscode#69263]
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Choose the default terminal as "bash" (WSL)
2. As long as the powerline is enabled in the shell, the cursor will have extra spaces between the cursor and the text you typed in. After typing in few letters, the cursor goes back to its proper position, but it will go off at times if you keep typing more letters.

PS: I did choose the modified powerline font and the rendering looks very proper to me.
PS: In my screenshot I did use fish as the shell but the same symptom happens if you use the default bash shell.

![image](https://user-images.githubusercontent.com/13779937/53282337-e3e28b00-36eb-11e9-8a79-47a18ff3f267.png)
![image](https://user-images.githubusercontent.com/13779937/53282342-3b342b80-36eb-11e9-8bcb-72d3dcc09198.png)
![image](https://user-images.githubusercontent.com/13779937/53282345-438c6680-36eb-11e9-9c0b-d1610d39b628.png)
![image](https://user-images.githubusercontent.com/13779937/53282351-4edf9200-36eb-11e9-8602-a7d1af3f9457.png)

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
Tracked in https://github.com/xtermjs/xterm.js/issues/1709
