### ISSUE TITLE
Super strange terminal behavior

### ISSUE THREAD

**Issue by MVSICA-FICTA** [Microsoft/vscode#69266]
I've been using the Code Runner extension to run small snippets of code for sometime. In addition I'm using the esm package to patch node, so I can work with ES6 modules. This has all worked smoothly for sometime.

Today however is another story. Running snippets/files was working fine in the AM and then it started acting weird. Now running a code snippet that ran fine before results in a cursor that just sits there or else jumps down a number of lines, without showing any console.log results in the terminal.

I'm running the latest VSCode under Windows 10 Pro version 1809. 

I've tried dis/enabling Code Runner. This resulted in it working again but then it dies again. At this point I do not know what to do. Hopefully there is some solution to this complete frustration!

**Comment by MVSICA-FICTA** [comment]
Still have this issue. I've cleaned out the project so only a few files that I know run are left. I have even removed prefix numbers on the files I use for sorting files. Have also dis/enabled Code Runner over and over. Sometimes Code Runner works but usually it does not. The terminal cursor just freezes or else jumps down a number of lines. The only recent new thing I'm using is pnpm.

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by Tyriar** [comment]
This is probably an issue with code runner or this bug in Windows: https://github.com/Microsoft/vscode/issues/57803
