### ISSUE TITLE
Can't open files with doubleclick

### ISSUE THREAD

**Issue by Emexus** [Microsoft/vscode#69267]
Issue Type: <b>Bug</b>

When I'm double-clicking a file in the tree view (Explorer tab), it doesn't seem to be opening the file anymore. I can still open files by drag&dropping them into a group.
Pressing Return after clicking a file also doesn't open the file.
This issue is extremely annoying.

Setting the option "workbench.list.openMode" to "singleClick" allows me to open it via one click, but with "doubleClick" it just won't work

VS Code version: Code - Insiders 1.32.0-insider (11416de365a1e96302e171c9eebc2547872ac230, 2019-02-23T08:18:44.913Z)
OS version: Windows_NT x64 10.0.17763

**Comment by enricoreich** [comment]
Can confirm this.
Double click a file in explorer does not open this file...nothing happens. There is no message in devTools console. This issue persists even if I disable all extensions.

> Version: 1.32.0-insider (system setup)
> Commit: 11416de365a1e96302e171c9eebc2547872ac230
> Date: 2019-02-23T08:18:44.913Z
> Electron: 3.1.3
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
Fixed in latest
