### ISSUE TITLE
 Open folders in a predefined vs code environments

### ISSUE THREAD

**Issue by tharindusathis** [Microsoft/vscode#69260]
I already know there is a option called **work-space** , but this does not addressed my issue. 
This is the feature what I need,
Assume that I am using vs code for different purposes. As an example: I use vs code for,

> 
> 1. Web designing (HTML, CSS, JS) 
> 2. C++ Programming
> 
> When I'm working with HTML, CSS, JS I need to have some special extensions, tasks, launch properties etc. On the other hand when I'm working with C++ I need different extensions, tasks and launch properties. Assume I have two predefined environment for both separately. And these two environments will have only the extensions and other properties that are needed only for each environment. Now I need to open a folder to start a C++ project, so I open this folder with terminal command by adding a the environment name as argument. i.e. `code . -env MyCppEnvironment` or `code . -env WebDesigning`. 
> 
  
You may suggest that I could use workspaces option for this. But in my point of view I see workspace as follows,

> I open a workspace for C++. `code cppProject1.code-workspace`. Then I configure the needed properties of the workspace(extensions, tasks, launch properties etc.), then add folders of related project to workspace. And work with it. So then we have to make the workspace again and again for each project.

**Comment by sandy081** [comment]
Looks dup of https://github.com/Microsoft/vscode/issues/39272
