### ISSUE TITLE
Cannot create file/folder wrong path

### ISSUE THREAD

**Issue by wuchujiecode** [Microsoft/vscode#69261]
- VSCode Version: 1.31.1 (1.31.1)
- OS Version: maxOS Mojave 10.14.3

Steps to Reproduce:

1. when I want to create file/floder
2. new file/ new floder  in wrong path
3. U can check my pointer was in 'pages'    btw my vscode setting  'a' -create new file  'shift+a' create new floder
4. when I want to create a new file in '/pages' 
5. point jump in '/pages/admin'  but I just want to create new file in '/pages/'
6. btw I ready setting '"workbench.list.keyboardNavigation": "simple",'

Does this issue occur when all extensions are disabled?: Yes/No
![image](https://user-images.githubusercontent.com/12055501/53282006-c275b380-376c-11e9-97c1-82a50fa9fd62.png)
![image](https://user-images.githubusercontent.com/12055501/53282014-da4d3780-376c-11e9-8ec6-c92a35f52ae7.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68574
