### ISSUE TITLE
Lorem ru typo

### ISSUE THREAD

**Issue by Steam-Rabbit** [microsoft/vscode#69269]
Issue Type: <b>Bug</b>

Please replace "реторический" with "риторический".

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by lukaschal** [comment]
"реторический" not occurs in localizable resources. Please verify on latest VS code LP version and reopen with actual screenshots if still repro.
