### ISSUE TITLE
Support for building with node.js >= 9

### ISSUE THREAD

**Issue by korsaire** [Microsoft/vscode#69271]
When having node.js version > 9 on your machine you get the following error when trying to build:

```
*** Please use node >=8 and <9.

error Command failed with exit code 1.
```
Current node LTS is 10, is there a reason for using the outdated version? Allowing the latest node version would simplify the build process IMO, especially for new contributors.

**Comment by rebornix** [comment]
You can use 10.15+ now to build VSCode source code.
