### ISSUE TITLE
Regexp syntax highlighting improvement

### ISSUE THREAD

**Issue by Jojaba** [Microsoft/vscode#69276]
I take an example to showcase my feature request. The following code (in php file) is rightly highlighted (in red):
`/(<date_modification>).*?(<\/date_modification>)/`
But this one not:
`@(<date_modification>).*?(<\/date_modification>)@`
I don't know if this is the case for all languages, but for php you can choose any delimiter to embrace the regexp. The more often: /, #, ~, @...
It would be nice to have all the demlimiters have in account for the syntax highlighting ;)
Thanks in advance.

**Comment by roblourens** [comment]
I don't think this would be a good idea because it would just cause a lot of false positives in regex detection. But if you have a proposal you could file it upstream: https://github.com/atom/language-php/
