### ISSUE TITLE
Hide noisy breadcrumb entries like local variables

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [microsoft/vscode#69279]
Local variables in the breadcrumbs outline add too much noise. They make it hard to use breadcrumbs for overview or navigation.

![image](https://user-images.githubusercontent.com/302938/53289733-e22bcc80-37aa-11e9-8339-0656509217c3.png)

It would be nice to have an option to exclude them from breadcrumbs.
Or maybe have nodes that only contain local variables collapsed by default.

**Comment by Antonius-S** [comment]
The same wish for outline panel. Variables make it unusable

**Comment by richbully** [comment]
Makes it unusable for me. 

On top of hiding local variables another idea is to specify an auto collapse based on level (except if your in that level). In my case I have a namespace at level 1, classes at level 2, methods at level 3 and method variables are level 4 so I would setup to auto collapse level 4 items.

![image](https://user-images.githubusercontent.com/11023398/58660815-709b8580-837a-11e9-84cb-62749bf0b14b.png)

![image](https://user-images.githubusercontent.com/11023398/58661214-6a59d900-837b-11e9-939e-223708348b90.png)

**Comment by chesucr** [comment]
Yes, local variables in that menu does not make any sense in my view. As an alternative, meanwhile this feature is not implemented [this method](https://stackoverflow.com/a/42711938/4891717) to look for method works:

> Invoke Code's `Go to symbol` command:
> 
> - macOS: <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>o</kbd> (the letter `o`, not zero)
> 
> - Windows/Linux: <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>o</kbd>
> 
> Typing a colon (<kbd>:</kbd>) after invoking `Go to symbol` will group symbols by type (classes, interfaces, methods, properties, variables). Then just scroll to the `methods` section.

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/53034

**Comment by jrieken** [comment]
I am working on that feature (available on next 1.40 insiders). What I understand is that people want to filter entries in the breadcrumbs picker, what about breadcrumbs itself? My current implementation applies to both: picker and breadcrumbs. Is that what people want?

![Oct-10-2019 08-48-53](https://user-images.githubusercontent.com/1794099/66545382-d4a93400-eb3a-11e9-8763-515c981a8018.gif)

**Comment by Vlad-Shcherbina** [comment]
Can't speak for anybody else, but I think it makes sense to apply filtering to both. Otherwise it would look weird when you click on a variable breadcrumb and it's not in the picker.

**Comment by glacjay** [comment]
I remember that at some previous version of vscode, it will only show nodes at the same level of the selected node, and collapse all the levels under it. I think it's very convenient to use. But later, it became to expend all levels by default, which is very noisy :-(

**Comment by TonyRietwyk** [comment]
I agree with @richbully.  I would like to see the breadcrumb drop down collapsed **depending on which level was clicked on** - possibly overriding the global switches.  In a Typescript context, I currently see this:
![breadcrumb](https://user-images.githubusercontent.com/5600947/66573175-f8618e00-ebbd-11e9-8658-9278379cdf6a.png)
When I click on the namespace ScoreNS, I would like to see this: 
<img width="174" alt="breadcrumb ScoreNS" src="https://user-images.githubusercontent.com/5600947/66573217-0b745e00-ebbe-11e9-9e95-53d67538e2bb.png">
 Similarly, when I click on the class Voice, I would like to see this: 
<img width="171" alt="breadcrumb Voice" src="https://user-images.githubusercontent.com/5600947/66573284-234be200-ebbe-11e9-94db-de069ea4a87b.png">
When I click on the method mouseClick, then I would see: 
<img width="171" alt="breadcrumb mouseClick" src="https://user-images.githubusercontent.com/5600947/66573363-48405500-ebbe-11e9-965b-492058f560c1.png">
So the processing for the breadcrumb pop-up would be:
`CollapseAll`
`Expand the current node`
`Expand each parent to the file level`

**Comment by jrieken** [comment]
@TonyRietwyk This item is about filtering, not collapsing.

**Comment by zacksigmund** [comment]
@jrieken This issue is not specifically about filtering, it's about "hiding" and the original post explicitly mentions collapsing. @TonyRietwyk 's proposal is the exact behavior I would expect from the breadcrumb feature.

**Comment by jrieken** [comment]
This is now done, there are `breadcrumbs.filteredTypes.XYZ`-settings and by default all nodes will be collapsed.

**Comment by lmaran** [comment]
+1 for hide/remove local variables in breadcrumb dropdown

**Comment by jrieken** [comment]
verifier: 
1. ensure that there are `breadcrumbs.filtertTypes.XYZ` settings
2. ensure that breadcrumb symbol pickers come up collapsed (except for current symbol)

**Comment by alexr00** [comment]
If I set `"breadcrumbs.filteredTypes.boolean": false,`
And have this code
```typescript
	private async testContainer(): Promise<boolean> {
		let isGood: boolean = true;
		return isGood;
	}
```
I still see the boolean in the breadcrumbs:
![image](https://user-images.githubusercontent.com/38270282/67773847-ac876380-fa5c-11e9-9595-b696b4b347dc.png)

**Comment by jrieken** [comment]
Try Variable (https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions)

**Comment by jrieken** [comment]
Closing as it's the extension's job to name symbols - please followup with TS/JS to adjust symbols

**Comment by JacksonKearl** [comment]
`"breadcrumbs.filteredTypes.function": false`, but when I put cursor in an area not in any function, the `...` "items past this" dropdown shows functions.
![image](https://user-images.githubusercontent.com/8586769/67818340-047a9600-fa6e-11e9-8d38-05a541d68111.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/67883016-8e733f00-fb00-11e9-852f-609f33aacfb8.png)
In file with only functions, where functions are filtered from breadcrumbs, the dots still show and clicking them occasionally gives you this artifact

**Comment by jrieken** [comment]
Please don't reopen feature requests in the presence of a bug, let continue in https://github.com/microsoft/vscode/issues/69279#issuecomment-548025381

**Comment by jrieken** [comment]
❗️ the names of the settings have change to `breadcrumbs.showXYZ`, e.g `breadcrumbs.showFunctions`.

**Comment by eamodio** [comment]
@jrieken 
This may be intentional, but I found that if you hide a container type element (`function`, `class`, `module`, etc), you end up hiding the breadcrumbs for everything inside the container. For example if you set `"breadcrumbs.showClasses": false`, you won't see any breadcrumbs for anything inside.
```ts
    class Class {
        constructor() { }
        field: any;
        get property() { return "something"; }
        method() { }
    }
```

This was definitely unexpected for me -- I wouldn't think you'd lose all nesting like that.

Also if you are on a "hidden" symbol, you won't have access to the breadcrumbs dropdown. See below, where I have `"breadcrumbs.showFunctions": false` and you can see that the `...` goes away on the function.
![missing-ellipsis](https://user-images.githubusercontent.com/641685/68032218-9f07ee80-fc93-11e9-9ebb-2cb69d11b4c8.gif)

Also if you click the `...` breadcrumb, we auto-select the first entry in the box, which also highlights the symbol in the editor and scrolls to it. While this is working as it _should_, without any hiding the viewport is pretty unlikely to scroll since the first symbol will be close to the cursor, but with hiding, the next symbol could be much farther way, which can be a bit jarring. Maybe we should just avoid auto-selecting the first symbol in the list to avoid this all together?

Here is an example of that (I have set  `"breadcrumbs.showFunctions": false`):
![jumping](https://user-images.githubusercontent.com/641685/68032841-ddea7400-fc94-11e9-8f55-9e7b2b0f5926.gif)
