### ISSUE TITLE
Limit the number of breadcrumbs displayed by VS Code

### ISSUE THREAD

**Issue by danielvoicu** [microsoft/vscode#69274]
I am wondering if it's possible to limit the number of ancestors shown in the breadcrumbs bar. At this point, if you have a large file with a more complex structure, you will see all ancestors of the currently selected element. I don't know if the current setup has an impact on performance, but from a design point of view, it seems to be add more complexity than necessary.

![screenshot from 2019-02-23 15-21-56](https://user-images.githubusercontent.com/7198550/53287154-d7f4d880-3780-11e9-9d27-ea57e3607a8d.png)

As you already have the possibility to see all ancestors in a tree-like dropdown by clicking on a breadcrumb, I think the ability to limit the number of breadcrumbs might clean up the interface and help users find the things they need faster.

![screenshot from 2019-02-23 15-26-18-cropped](https://user-images.githubusercontent.com/7198550/53287155-db885f80-3780-11e9-9349-9dc591a01720.png)

I've added a couple of screenshots with an example structure for this issue. Please ignore the large amount of divs. :smile: 

Thanks!

**Comment by jrieken** [comment]
Well, it's the mirror view of your sources ;-) Not sure what you wanna do here? What items you want to hide? Cut off at the end? Remove some from the middle?

**Comment by danielvoicu** [comment]
> 
> 
> Well, it's the mirror view of your sources ;-) Not sure what you wanna do here? What items you want to hide? Cut off at the end? Remove some from the middle?

I understand that it's a mirror view of my sources. But I was wondering if the breadcrumb line could be limited to a certain amount of elements. Right now you can see both code and file ancestors of a given element. All of them until the first one. I don't know how this affects Code's performance, but from a visual standpoint, it adds clutter to the workspace.

So for a code item, would it be possible to limit the number of ancestors and children of this element in the breadcrumbs bar to something like 5 - random number here - elements before it and 5 after it?

Thanks.
