### ISSUE TITLE
Issues should have an expiration date

### ISSUE THREAD

**Issue by csicky** [Microsoft/vscode#69282]
I think all issues should have a dynamic label which starts green and changes color as time passes. A new issue would be green, a six months old would be blue or yellow, 1 year old issue would be orange, and a two years old one would be red. Colors don't matter that much, the aging itself is important.

After a year and still open, a bot should prompt it for consideration, do it, push it up in priority, or don't do it, close it and add a label like "won't do".
After two years it should be closed by the bot automatically.

Reason for this is, every day new issues are being added, old ones always are buried deeper every day. There are issues still open from 2015. I am watching some old issues from 2016, what are the chances any will be implemented? There is also the fact that the issue is still open but as the time has passed it became obsolete and it shouldn't even be done at all.

At least if they will be closed because of age people watching get an answer as why not and that's it. Obviously, there should be a comment with the reason before closing it.

**Comment by Tyriar** [comment]
We use :+1: votes on the issue to help with prioritization. If something is truly desired relative to others it will bubble to the top, especially as the issue becomes older.

In addition to this the team periodically cleans up all issues which may involve closing out issues that we aren't considering for the next 6 months. We intentionally leave old issues with votes open so they can continue to gather 👍 votes.
