### ISSUE TITLE
[json] Json Schema Server?

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/vscode#6928]
Would be possible to get a editor agnostic Json Schema npm package or something we can use as a service?  Something similar to OmniSharp but for Json Schema I suppose.  Ideally it would also be able to be hosted independent of VSCode, so editors like Sublime could call on the same functionality as well.

All the hard work is done to get Json Schema support into VSCode, and I'm looking to derive from it to enhance the Atom support for Json Schema (and Json in general).  Now that said that means two duplicate code bases, doing essentially the same thing.  It would be great if we had one shared code base, so fixes could be shared amoung many editors.

Having a set of API's that could API's for...
* completion
* hover
* symbols
* formatting
* contributions
  * list
  * add
  * [remove?]

**Comment by aeschli** [comment]
I've started to extract JSON functionality into node modules, starting with https://www.npmjs.com/package/jsonc-parser. I'll do the same with the formatter.
Then, we already have the JSON language support as a service using the [language server protocol](https://code.visualstudio.com/docs/extensions/example-language-server).
If you write a language client for atom then you could consume the service as is (and even other language services using the protocol: tslint, eslint, powershell, ...).
Right now the JSON language server isn't a separate node module, but of course that's easy to do.
FYI @dbaeumer

**Comment by david-driscoll** [comment]
That's an interesting alternative, I'll have to dig into it.

**Comment by aeschli** [comment]
The JSON language smarts are now in a separate git repo and node_package:
https://github.com/Microsoft/vscode-json-languageservice.
We use that package in both the [VSCode JSON language server](https://github.com/Microsoft/vscode/tree/master/extensions/json) and the [Monaco standalone editor](https://github.com/Microsoft/monaco-editor)
