### ISSUE TITLE
Can't pin tabs by double clicking explorer files

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#69284]
Issue Type: <b>Bug</b>

I used to be able to double click on a file to pin it open, while a single click only temporaly opens the tab

on this build it stop working 

VS Code version: Code - Insiders 1.32.0-insider (11416de365a1e96302e171c9eebc2547872ac230, 2019-02-23T08:16:36.706Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|3.0.24
vscode-icontheme-nomo-dark|be5|1.3.6
better-toml|bun|0.3.2
vscode-pull-request-github|Git|0.4.0
terraform|mau|1.3.7
markdown-shortcuts|mdi|0.11.0
prettify-json|moh|0.0.3
python|ms-|2019.1.0
vscode-docker|Pet|0.5.2
vscode-icons|rob|8.2.0
vscode-nginx|sha|0.6.0
sort-lines|Tyr|1.8.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@isidorn a recent change maybe? I can reproduce.

**Comment by isidorn** [comment]
@bpasero I can also reproduce. The issue is that the open event I am getting from the list service has pinned: false, even though it is a double click.
I will do some bisecting to find the fault.
fyi @joaomoreno @sandy081

**Comment by isidorn** [comment]
By bisection this was broken by https://github.com/Microsoft/vscode/commit/3946e3233baba153802680044654d605a03ce926
If I revert that commit everything works fine.
Forwarding to @joaomoreno 

![screenshot 2019-02-26 at 11 19 06](https://user-images.githubusercontent.com/1926584/53405542-58514e80-39b8-11e9-805a-f8ab607c774b.png)

**Comment by FernandoMiguel** [comment]
thanks for looking into this so quickly

**Comment by isidorn** [comment]
@FernandoMiguel thanks for using insiders and for reproting issues.
