### ISSUE TITLE
Terminal running PowerShell has dark blue background and black text 

### ISSUE THREAD

**Issue by fmorriso** [Microsoft/vscode#69288]
Issue Type: <b>Bug</b>

1. make sure PowerShell is the default for Visual Studio Code Terminal.
2. Start a new Terminal
3. enter any command, such as pwd.
4. Notice the blue background and black text - this makes the text unreadable.

Desired resolution: provide a way to set contrasting background/foreground colors in Terminal windows  so that I can make sense of what I'm typing.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (6.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
ng-template|Ang|0.1.11
azurenodeessentials|azu|0.2.6
azuretoolsforvscode|bra|2.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
vscode-solution-explorer|fer|0.3.1
code-runner|for|0.9.7
json2ts|Gre|0.0.6
angular-essentials|joh|0.5.1
Angular2|joh|7.0.1
azure-functions-tools|joh|0.3.3
efcore-snippets|jul|0.0.5
json-to-ts|Mar|1.5.5
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-azureextensionpack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1225
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.2
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.6.3
java|red|0.39.0
vscode-yaml|red|0.3.0
LiveServer|rit|5.5.1
sharecode|Rol|0.4.1
yo|sam|0.9.3
html5-boilerplate|sid|1.0.3
vscode-odata|sta|0.1.0
usql-vscode-ext|usq|0.2.14
vscodeintellicode|Vis|1.1.3
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.10.0
azure-iot-toolkit|vsc|2.3.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
wilderminds-aspnetcore-snippets|wil|0.2.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
The colors are determined by the theme, you can customize it in settings with `workbench.colorCustomizations`
