### ISSUE TITLE
 Gnu / Linux Sensitivity of the right click in windows (update 2019)

### ISSUE THREAD

**Issue by HorusBlack** [Microsoft/vscode#69280]
Issue Type: <b>Bug</b>

https://www.youtube.com/watch?v=dEBkO0ecKzY&feature=youtu.be

*ENGLISH (google translate)
* When loading the editor does not present problems. These appear when the extensions finish loading. When you right click with the mouse, the options open but the cursor automatically activates the option that you are currently dialing.
* You have to keep the right button pressed and move the cursor out of the options to avoid the error.

* We have tried to reproduce the same bug in other similar text editors and in some IDE, but without success, deducting that the error is in vscode.

* Comparing the behavior of vscode in windows 10,
the difference is that when using said S.O when doing the same procedure as in linux, the options have a small time lapse before appearing, while in seconds they appear immediately without the possibility of avoiding automatic activation.

ESPAÑOL

*Al cargar el editor no presenta problemas. Estos aparecen cuando terminan de cargarse las extensiones. Al hacer click derecho con el mouse se abren las opciones pero el cursor automáticamente activa la opción que este marcando en ese momento. 

*Se tiene que mantener presionado el botón derecho y mover el cursor fuera de las opciones para evitar el error.

*Se ha intentado reproducir el mismo bug en otros editores de texto semejantes y en algunos IDE, pero sin éxito, deduciendo que el error se encuentra en vscode. 

*Comparando el comportamiento de vscode en windows 10, la diferencia radica en que al usar dicho S.O al hacer el mismo procedimiento que en linux, las opciones tienen un pequeño lapso de tiempo antes de aparecer, mientras que en en segundo aparecen de manera inmediata sin posibilidad de evitar la activación automática.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.14.98-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1090T Processor (6 x 803)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.79GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-languagetool-es|ada|3.8.0
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|10.2.2
numbered-bookmarks|ale|6.1.0
vscode-color|ans|0.4.5
theme-verdandi|be5|1.9.0
vscode-intelephense-client|bme|1.0.2
githistory|don|0.4.6
jquerysnippets|don|0.0.1
gitlens|eam|9.5.1
vscode-great-icons|emm|2.1.46
vsc-material-theme|Equ|2.7.0
php-intellisense|fel|2.3.10
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
ftp-simple|hum|0.7.0
crane|Hvy|0.3.8
path-autocomplete|ion|1.13.1
vscode-pigments|jas|1.0.6
theme-karyfoundation-themes|kar|18.2.1
vscode-simple-icons|Lau|1.11.2
theme-monokai-pro-vscode|mon|1.1.10
vscode-language-pack-es|MS-|1.31.4
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
format-html-in-php|rif|1.5.1
LiveServer|rit|5.5.1
vscode-icons|rob|8.2.0
ayu|tea|0.18.0
highlight-matching-tag|vin|0.8.6
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(6 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
#65787
