### ISSUE TITLE
Antialiasing stopped working on Insiders

### ISSUE THREAD

**Issue by glockjt** [microsoft/vscode#69285]
- VSCode Version: 1.32.0-insider
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open up VS Code and the font is not antialiased.
2. Flip through the options in the settings and it never changes the aliasing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tc-diederik** [comment]
https://github.com/Microsoft/vscode/commit/1b908ce4ece05277191900bf567bcfb357d08064#diff-d3e0527fc1661d3ca1a624b2e58f62f2L44

The anti-aliasing classes are added to the same element as the `monaco-workbench` class and not nested underneath. I reckon the selectors should be along the lines of `.monaco-workbench.monaco-font-aliasing-###`.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by tc-diederik** [comment]
Tried the exploration build and the issue did not reproduce for me on macOS 10.14.6.

- Version: 1.37.0-exploration
- Commit: 960208fdf9aa06e6892aa14c9c84ddd607fbeb2f
- Date: 2019-07-31T06:56:38.567Z
- Electron: 6.0.0
- Chrome: 76.0.3809.88
- Node.js: 12.4.0
- V8: 7.6.303.27-electron.0
- OS: Darwin x64 18.7.0
