### ISSUE TITLE
Environment variables don't update after app restart

### ISSUE THREAD

**Issue by zebfross** [Microsoft/vscode#69289]
Issue Type: <b>Bug</b>

I updated my PATH environment variable, but it didn't update in VS Code command console even after restarting the app.  I had to restart my computer before it updated.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.14GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/zebfross/Documents/projects/discount-movies|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.1
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|0.15.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
PowerShell|ms-|1.11.0
heroku-command|pko|0.0.8

</details>

**Comment by joaomoreno** [comment]
This is a known Windows issue. Re logging in is usually the way to go.
