### ISSUE TITLE
VSCode keeps crashing when copying and pasting a file from Explorer

### ISSUE THREAD

**Issue by marcmm** [Microsoft/vscode#69291]
Issue Type: <b>Bug</b>

VSCode app crashes when doing Ctrl+C -> CtrlV on a file in the Explorer

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18339

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (3.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.6
vscode-csproj|luc|0.7.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0

</details>

**Comment by isidorn** [comment]
I can not reproduce this.
Can you repro with vscode insiders? https://code.visualstudio.com/insiders/
@bpasero can you fill in details on how to file crash reports please?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
