### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by sushil3107** [Microsoft/vscode#69294]
Issue Type: <b>Feature Request</b>

i can't use my terminal.I have tried many solution but none are working.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.2.9200

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169
