### ISSUE TITLE
Flaky behaviour in settings with large enum

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#69297]
Issue Type: <b>Bug</b>

I've written an extension and one of the settings selects from a large number of strings that name CSS stylesheets. When editing in settings the picker behaves erratically with a populous enum. Originally it had 90 items. Culling it to 30 improved things but it's stilly flaky. This has nothing to do with my extension code; it happens _before_ my code is loaded or activate is called.

![image](https://user-images.githubusercontent.com/5498936/53297234-f8975e00-3866-11e9-9046-9002533981bd.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
FYI @cleidigh

**Comment by cleidigh** [comment]
Hey @roblourens 

I can look at this tomorrow, it seems most likely it's  in selectBox.
If I can reproduce it I will report/fix-it.

**Comment by cleidigh** [comment]
@roblourens  
I did a quick and dirty test artificially adding 40,90,180 options to Auto File Save with selectbox.  This did not present any discernible problem ,  but probably does not match the issue closely enough.  I can do two things , make a hello world extension with a large enum setting or:  another slightly different test would be to artificially expand a built-in setting.  Both experiments might be necessary.  

@roblourens  any particularly easy setting to do this?

**Comment by roblourens** [comment]
I also have https://github.com/Microsoft/vscode/issues/69306 which I think is caused by changing the setting then immediately reopening the dropdown. I see some different behaviors, sometimes it shows up attached to the wrong setting. There is also an issue that sometimes the editor scrolls down a bit after changing a setting. These are on me and there may not be a new issue from having lots of items in a dropdown...

**Comment by cleidigh** [comment]
@roblourens 
yeah, I've seen some of the oddities.  I was going to post an issue regarding Alt-Down  which should open drop downs, but sometimes goes off elsewhere.  If that's a duplicate, I will post.

I just saw the following glitch which I will look into.  There may be multiple issues.  One thing I am looking at is layout changes either from zoom or having to open to the top.  I will keep looking at this book because I do think there is at least some issue with selectBox even if it does not relate to the number of items.  

Last note:  In the screenshot below you can see an erroneous description attached to the cursor style, is that something you have seen when you say "attached to a different setting" ?

![image](https://user-images.githubusercontent.com/25272315/53379144-5b0b5f80-3936-11e9-99b3-1cac65dcaeac.png)

**Comment by cleidigh** [comment]
@roblourens 
This glitch almost seems to have retained the height calculations from a longer list (viewed prior)  along with doing zooming.

![image](https://user-images.githubusercontent.com/25272315/53379497-c570cf80-3937-11e9-8010-ee20c3d715de.png)

**Comment by PeterWone** [comment]
Yes! That is exactly the behaviour I've been seeing. Is something stored in a wrong scope? Or at the right shared but not updated appropriately?

**Comment by cleidigh** [comment]
Hello Australia!

I think both @roblourens and myself believe this might be some combined issues.  Knowing the selectBox as I do and after some experiments, I do not believe the number of items is the direct cause.

Probably 30 items just fits under the drop-down IF the drop-down is nearer to the top of the screen.  If the drop-down needs to flip up, or a zoom is done, a relay out as necessary and somewhere in that is where I think there is at least one of the issues.

**Comment by cleidigh** [comment]
@PeterWone 
our post just crossed your observations do seem to line up with my comments above.

**Comment by PeterWone** [comment]
Yes I agree.

**Comment by PeterWone** [comment]
So where might that fit in the ten thousand things on your list? :)

**Comment by cleidigh** [comment]
@roblourens 
I am going to spin a configuration where the drop down will NOT allow flipping up to eliminate one layout scenario for experimentation.  Since we think there might be more than one thing going on here,  Do you want to post a branch which you can also use in your experiments?

**Comment by roblourens** [comment]
I don't think I've seen it go off to the side like that. Do you have good repro steps?

One thing that's different recently with the new list is that when it is rerendered, it's more likely to render a setting with a different template. So one of the bugs I know comes from editing a setting then immediately clicking a different dropdown. Then we refresh and the dropdown which is already being displayed can be overwritten by data from a different setting.

**Comment by cleidigh** [comment]
I only got the erroneous position to the side once.  I think I'm close to a reproducible scenario for my second image showing the gap in the drop down , but there's clearly multiple things going on at the same time.  I will work on solid set of steps to reproduce...

**Comment by cleidigh** [comment]
@roblourens 
I posted a link to my test branch (didn't think a PR was appropriate)  I added extra items for both Auto Save (first setting) and cursor style.

I have not found a totally consistent set of reproduction steps, the following repeated several times will usually trigger a layout problem within 4-5 view changes:

- open settings page
- tab to Cursor Style - open DD - Escape
- change zoom++
- reopen DD
- change zoom in and out ( sometimes DD re- renders other times it disappears, sometimes you get the gap )

Sometimes I have seen the focus change to the following DD but with the settings of Cursor Style

I will continue looking, but I thought you could use the experimental branch possibly.

https://github.com/cleidigh/vscode/tree/select-box-items-issue

**Comment by roblourens** [comment]
@cleidigh did you figure anything out? I am able to repro this without making code changes, just by editing a dropdown then expanding another one a few times.

**Comment by cleidigh** [comment]
@roblourens 
I was going to ask you the same thing.  I can reproduce it but it's not completely consistent.  I think your prior comment on crossing the list contents when switching between drop downs looks evident.  I can't really see well from my side how that is happening.  What can I do to help?

**Comment by roblourens** [comment]
I think I see the problem, we are not cleaning up completely when reusing a custom select box for multiple settings.

**Comment by alexr00** [comment]
Verified by filtering the settings to theme, then opening the color theme drop down followed by the icon them drop down. On stable, there is an odd gap in the icon theme drop down. On insiders, it is fixed :).
