### ISSUE TITLE
Markdown preview jumps (agian)

### ISSUE THREAD

**Issue by mhmorta** [Microsoft/vscode#69290]
Hi, markdown preview and the text editor jumps to the top or just scrolls when typing. I updated today, but it's having the same problem as was reported in the earlier version.
- VSCode Version: 1.31.1
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:
1. Have a markdown file **containing images** and text
2. Start editing the file with the preview enables.

Does this issue occur when all extensions are disabled?: Not sure.

Thank you.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mhmorta** [comment]
I just checked; **no** it doesn't have that issue. 
I guess I have messed up the configuration of my vscode; I have a lot of extensions that might have resulted in this problem. 
Do you have any suggestions on how to trace back this problem? I will try meanwhile.

**Comment by mjbvz** [comment]
Can you share a list of the extensions you have installed? Or try going through and disabling them until you find which one is causing this behavior

**Comment by mhmorta** [comment]
I have migrated again from to the latest stable version and it works perfectly. 
I guess I have some local configurations that were causing that and downgrading to version 1.23 and again upgrading fixed it. 
I tried the same when I had the problem by downgrading to 1.29 and 1.30, but it didn't help. 

I guess we can close the issue; I am not sure was causing that. 

Thank you.
