### ISSUE TITLE
vc slow

### ISSUE THREAD

**Issue by Erwinpt** [Microsoft/vscode#69292]
Issue Type: <b>Bug</b>

very slow

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E2-7110 APU with AMD Radeon R2 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.96GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.26
php-pack|fel|1.0.2
vetur|oct|0.16.2
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.6.3
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/wiki/Performance-Issues for reporting actionable perf issues.
