### ISSUE TITLE
window.showQuickPick is not closed when promise is rejected

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#693]
When `showQuickPick` is used with a promise, it shows a nice progress bar which is cool. But when the promise is rejected, it should close the quick pick in my opinion, which is not the case at the moment, the progress bar just keeps spinning.

```js
return window.showQuickPick(new Promise((resolve, reject) => {
	setTimeout(() => {
		reject();
	}, 2000);
}));
```

// @bpasero

**Comment by bpasero** [comment]
I fixed most of the issues: If there is an error in your promise, the picker will hide and you have a chance to handle the error from the returned promise from the pick() call.

@jrieken is our proxy from main to PH not handling errors? I have the following extension that shows a pick with error but in the console I still get an error about unhandled promise:

```typescript
export function activate(context: vscode.ExtensionContext) {

	var disposable = vscode.commands.registerCommand('extension.sayHello', () => {
		vscode.window.showQuickPick(new Promise((c, e) => {
			setTimeout(() => {
				e(new Error("does not work"));
			}, 2000);
		})).then(null, (e) => {
			vscode.window.showErrorMessage(e.toString());
		});
	});

	context.subscriptions.push(disposable);
}
```

![image](https://cloud.githubusercontent.com/assets/900690/11418595/91155dd2-9421-11e5-9ae7-d5295da015a2.png)

**Comment by SamVerschueren** [comment]
Thanks for the quick fix!

**Comment by jrieken** [comment]
@bpasero The reject works as expected but there is an known issue with unhandled promise rejection. Our handler sits here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/pluginHostProcess.ts#L33 but there is a well known issue with that. Since project rejection and handling can happen async (on different event loop ticks) a promise might be handled some time in the future. Since the node events seem to lack the actual promise causing this we can't have better logging.

**Comment by bpasero** [comment]
@jrieken in the example code I gave, we have a valid use of our API and the console ends up to report unknown errors:

![image](https://cloud.githubusercontent.com/assets/900690/11428784/ba32da52-946f-11e5-8917-9eec0261d925.png)

I would think this can happen from any promise that carries an error from the main side to the PH side. If we know this can happen and cannot fix it, we should filter these messages.

**Comment by jrieken** [comment]
It's not possible with the version of nodejs we are using today. Please read the comment and the links I have pointed to.

**Comment by jrieken** [comment]
And since this only happens when the event loop is released between rejection and handling of it I think its the better compromise to see some potential false positive here and there then not seeing any unhandled rejection.

**Comment by jrieken** [comment]
tracking the false positive in unhandled rejection here #963

**Comment by SamVerschueren** [comment]
:+1:
