### ISSUE TITLE
File Explorer overwrites file with non-existent one due to lack of refresh

### ISSUE THREAD

**Issue by oscarmarcelo** [Microsoft/vscode#69303]
Issue Type: <b>Bug</b>

1. Chose a folder with files in it and create new folder inside it;
2. Move a file into that folder (The file explorer does not refresh, not providing visual feedback);
3. Move that file again to that folder (The file was already in that folder, but the file explorer was still showing it in the old position);
4. Accept the warning of overwrite;
5. The "phantom" file will overwrite the real file, deleting everything in the process. 😠 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|-psn_0_617565392|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-language-babel|mgm|0.0.22
vscode-apache|mrm|1.2.0
vscode-puglint|mrm|2.3.0
vscode-icons|rob|8.2.0
sass-indented|rob|1.5.1
linter-xo|sam|2.3.2
vscode-csstree|sme|0.7.0
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68316

**Comment by mk-pmb** [comment]
I consider this side effect too dangerous to handle it as just a dupe as long as the "original" issue sounds like a mere UI inconvenience.
