### ISSUE TITLE
some questions about debug c with gdb

### ISSUE THREAD

**Issue by kenny39** [Microsoft/vscode#69300]
Issue Type: <b>Feature Request</b>

I am using vsc with gdb to debug my c program,and i want ask which console can display the output in my program ,and how can I input ?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by weinand** [comment]
VS Code has no built-in C debugging functionality. So you must be using an extension...
