### ISSUE TITLE
[json] vs code cannot analysis json schema location which includes chinese

### ISSUE THREAD

**Issue by DragonKnightOfBreeze** [microsoft/vscode#69308]
Issue Type: <b>Bug</b>

VSCode cannot analysis json schema location which includes chinese.
It once made me very confused.
See this:

```
"json.schemas": [
	{
		//when starts with / and not includes Chinese,its ok.
		"url": "/Idea/Information/Schema/ElemInfo.json"
	}, {
		//when incudes Chinese,vscode cannot analysis this location.
		"fileMatch": ["/Idea/信息/Element/测试.json"],
		//cannot analysis,too.
		"url": "/Idea/信息/Schema/ElemInfo.json"
	}, {
		//though vscode can work well like this,its still a serious issue.
		"fileMatch": ["/Idea/*/Element/*.json"],
		//cannot analysis
		"url": "/Idea/信息/Schema/ElemInfo.json"
	}
]
```

By the way,I dont know how to make vscode work well with sub-schema.  

```
//It will work well in jetbrains IDEA,but I dont know how to make it work well in vscode.  
"$ref":"/Idea/Information/Schema/ElemInfo.json#/definitions/Name"
//Is there any Issue else?
"$ref":"/Idea/Information/Schema/ElemInfo.json#/definitions/姓名"
```

By the way twice,it makes me very confused to define $schema property in common json files.

```
{
	//why it cannot be an relative location link?
	//show: connect ECONNREFUSED 127.0.1:80
	//no matter whether u define this location in json.schema/0/url or not.
	//(in settings.json) "json.schemas": [{"url": "/Idea/Information/Schema/ElemInfo.json"}
	//BUT: its the right way in jetbrains IDEA.
	//"$schema":"/Idea/Information/Schema/ElemInfo.json",
	
	//show: connect ECONNREFUSED 127.0.1:80,too.
	//"$schema":"Idea\\Information\\Action\\SpecialSkill\\Schema\\ElemInfo.json",

	//still have some problems.
	//show: Problems loading reference 'file:///Idea/Information/_Global/Schema/PropList.json#/definitions/Comment': ENOENT: no such file or directory, open 'd:\Idea\Information\_Global\Schema\PropList.json'
	//PropList.json is just another json schema file.
	//"$schema":"file:D:/My Documents/My Projects/Sample/Idea/Information/Action/Schema/ElemInfo.json",
	
	//its ok.
	"$schema": "http://json-schema.org/draft-06/schema",
	...
}
```

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (5.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
lua-debug|act|0.7.5
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
shaderlabvscodefree|aml|1.1.3
vscode-json|and|1.4.2
ng-template|Ang|0.1.11
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
vscode-database|baj|1.5.3
markdown-preview-github-styles|bie|0.1.4
path-intellisense|chr|1.4.2
regex|chr|0.2.0
gitignore|cod|0.6.0
python-snippets|cst|0.2.0
vscode-eslint|dba|1.8.0
vsc-invoke|dch|0.0.9
githistory|don|0.4.6
javadebugger|don|0.1.5
jquerysnippets|don|0.0.1
xml|Dot|2.4.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
javac-linter|fau|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
dotnet|for|0.0.4
dotnet-test-explorer|for|0.6.3
beautify|Hoo|1.4.9
latex-workshop|Jam|6.0.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.6
Lua|key|0.0.9
unity-code-snippets|kle|1.3.0
vscode-github|Kni|0.30.1
StarboundJson|Kyl|0.1.3
csharpfixformat|Leo|0.0.78
MagicPython|mag|1.1.0
regionfolder|map|1.0.0
Angular-BeastCode|Mik|7.2.4
HTMLHint|mka|0.5.0
vscode-language-pack-zh-hans|MS-|1.31.4
mssql|ms-|1.4.0
python|ms-|2019.1.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.2
python-docs|Muk|0.8.3
copy-json-path|nid|0.0.5
vscode-versionlens|pfl|0.22.0
vscode-jsp|pth|0.0.2
quicktype|qui|12.0.46
classynaming|ref|1.2.0
vscode-icons|rob|8.2.0
vscode-format|rya|0.0.6
code-settings-sync|Sha|3.2.5
markdown-preview-enhanced|shd|0.3.11
stylelint|shi|0.48.0
simontest|Sim|1.0.4
shader|sle|1.1.4
code-spell-checker|str|1.6.10
starbound-lua|sub|2.4.0
open-in-browser|tec|2.0.0
vscode-markdown-paste-image|tel|0.12.0
bootstrap4-vscode|the|6.0.3
unity-tools|Tob|1.1.0
vscode-markdown-todo|Tom|11.0.0
python-extended-snippets|tus|0.0.1
unity-debug|Uni|2.6.6
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.3
vscode-todo-highlight|way|1.0.4
vsc-jsonsnippets|wmo|0.1.4
markdown-all-in-one|yzh|2.1.0
vscode-open-in-github|ziy|1.3.6
explicit-folding|zok|0.2.1

(5 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
for $ref we only support full URL (`http://` `file://`).
For fileMatch and for $schema please try relative paths, like described here:
https://code.visualstudio.com/docs/languages/json#_mapping-to-a-schema-in-the-workspace

Note that these are URI paths, so it's always forward slash and you might have to encode characters.

**Comment by DragonKnightOfBreeze** [comment]
I tried relative location in $schema,and it shows 'connect ECONNREFUSED 127.0.1:80',
vscode seems to consider the relative location as a http url.

**Comment by DougBR** [comment]
I am having the same issue after installing Python extension on remote server.

**Comment by wmertens** [comment]
Triage: I think this issue can be closed, the problem was that the url used was not absolute?
