### ISSUE TITLE
Ignore Alt_R key

### ISSUE THREAD

**Issue by kev0960** [Microsoft/vscode#69304]
For the most of Korean keyboards, Alt_R key is mapped to the key that converts between Korean letters and alphabets. 

However it seems like for VSCode in Ubuntu, Alt_R key is interpreted as a Alt key which triggers very annoying behavior whenever I switch between Korean and English.

Could you please add an option to ignore Alt_R and only respond to Alt ?

**Comment by Basel-Issmail** [comment]
In older version of VSCode for Ubuntu, I didn't have this problem, it appeared in newer ones and it is very annoying.
If you could ignore Alt key or add an option for this. 
@kev0960 now I got used to press Alt key again after changing language to get back to normal state and get the cursor back to where I need it.

**Comment by Tyriar** [comment]
@kev0960 is the annoying behavior related to the title bar? If not what?

**Comment by kev0960** [comment]
@Tyriar For example, Whenever I switch from Korean letter to Alphabet, I immediately start typing english characters. That means, If I start type like 's' right after switching to English, it is actually interpreted as pressing Alt + s. This happens for all possible shortcuts that contains alt in it.

**Comment by sbatten** [comment]
@kev0960 this should be fixed when the custom titlebar is no longer default in Linux this coming milestone. https://code.visualstudio.com/docs/setup/linux#_using-the-custom-title-bar

**Comment by Tyriar** [comment]
@sbatten right alt switches english to hangul and doesn't focus the title bar on Windows 10, any idea why it doesn't on Ubuntu?
