### ISSUE TITLE
Terminal strange background color

### ISSUE THREAD

**Issue by farebord** [Microsoft/vscode#69309]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode.
2. Toggle view on the terminal.

Does this issue occur when all extensions are disabled?: Yes

How does it look?
![image](https://user-images.githubusercontent.com/602693/53301061-34adcd00-382d-11e9-854b-0405a6eac288.png)

I've tried using terminal.background under customization to see if that was the problem. It wasn't.

My current user config:
```
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "git.autofetch": true,
    "window.titleBarStyle": "custom",
    "window.zoomLevel": 1,
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "explorer.confirmDelete": false,
    "python.linting.enabled": false,
    "python.linting.flake8Enabled": true,
    "workbench.colorTheme": "Visual Studio Dark"
}
```

Edit: Apparently the terminal changes color and go even brighter after some usage.

**Comment by Tyriar** [comment]
I can't reproduce, what happens with different themes?

**Comment by farebord** [comment]
Nop. Its the same for all themes except Light version.

**Comment by Tyriar** [comment]
@farebord Have you customized the background color or other colors inside cmd.exe or powershell.exe? https://github.com/Microsoft/vscode/issues/68865#issuecomment-467309670

**Comment by farebord** [comment]
> @farebord Have you customized the background color or other colors inside cmd.exe or powershell.exe? [#68865 (comment)](https://github.com/Microsoft/vscode/issues/68865#issuecomment-467309670)

Nop. Btw I use cmd.exe without any changes on the background color.

**Comment by Tyriar** [comment]
Unfortunately we probably can't action this, however in the next version of Windows 10 (190*) we are moving over to a new backend which should fix most issues like this.

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by farebord** [comment]
@Tyriar this issue is fix when change `"terminal.integrated.rendererType": "canvas"` to `"terminal.integrated.rendererType": "dom"`.

Hope that helps you find the bug. I'm out.

**Comment by Tyriar** [comment]
@farebord it's interesting that's the fix. I'll keep a lookout for other reports, thanks.

**Comment by stephendeo** [comment]
@farebord this as driving me nuts! thanks for the fix

**Comment by dylanparry** [comment]
@Tyriar I get the same issue in Ubuntu. The solution above fixes it for me too.

**Comment by Tyriar** [comment]
If anyone can still reproduce this I need better steps and a setting.json file to try reproduce myself, please comment in https://github.com/Microsoft/vscode/issues/71568 to help out 🙂
