### ISSUE TITLE
What are .vscode/.browse.VC.db*?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6931]
These 2 files are being created, no idea what they are:

```
.vscode/.browse.VC.db
.vscode/.browse.VC.db-wal
```

Something to be concerned about or already fixed?

**Comment by alexandrudima** [comment]
@Tyriar Maybe you have installed the cpp extension?

**Comment by Tyriar** [comment]
@alexandrudima ah that must be it, do you remember what the cpptools issue repo was?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscppsamples#56
