### ISSUE TITLE
Disabling auto closing quotes does not have any effect on Python raw, binary, and f-strings.

### ISSUE THREAD

**Issue by huettenhain** [microsoft/vscode#69312]
### User Environment
- VSCode Version: 1.31.1 
- OS Version: Windows 10, Version 1803 (OS Build 17134.590)

The issue does occur when all extensions are disabled.

### Steps to Reproduce:
1. Disable auto closing quotes via the setting `"editor.autoClosingQuotes": "never"`
1. Create an empty `.py` file and type `test = r'`

### Expected Behavior:
The content of the file is `test = r'`.

### Observed Behavior:
A closing quote is inserted and the content of the file is `test = r''`.

### Illustration:
![auto-quotes](https://user-images.githubusercontent.com/11869704/53301966-49a05580-3859-11e9-8b9e-e1de45f76ba1.gif)

**Comment by alexandrudima** [comment]
python contributes some funny looking auto closing sets:

https://github.com/Microsoft/vscode/blob/9daddf91cbbeea15a3a72dc01c64d94d82410314/extensions/python/language-configuration.json#L11-L34

**Comment by huettenhain** [comment]
Well those generally look correct, `u''` is unicode strings. It's odd that they are configured the same way as _"normal"_ quotes, yet setting `editor.autoClosingQuotes` to `never` has no effect on them.

**Comment by alexandrudima** [comment]
This was also fixed by 37981d8fd5d4ba1619f69dc8a0f4670543d39650
