### ISSUE TITLE
Powershell terminal prints first line blank when opening

### ISSUE THREAD

**Issue by Rall3n** [Microsoft/vscode#69326]
- VSCode Version: 1.31.1 (user setup)
- OS Version: Windows 10 10.0.17763 Build 17763

Steps to Reproduce:

1. Launch VSCode
2. Open a terminal if not open
3. optional: Type into terminal to check if available

Does this issue occur when all extensions are disabled?: Yes

The terminal is printing its first line (the path to the current working directory) as a blank text when first opening the powershell in the integrated terminal. Typing shows the indent of the first line, and entering a command resets it.

<details>
<summary>VSCode Screenshot</summary>

![image](https://user-images.githubusercontent.com/15950630/53320342-b35e4500-38d5-11e9-8d5a-1706d4bb2b34.png)

</details>

<details>
<summary>VSCode Insider Screenshot</summary>

![image](https://user-images.githubusercontent.com/15950630/53320403-df79c600-38d5-11e9-9e05-61b691d477d0.png)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
