### ISSUE TITLE
Remove the output of storage contents when running with --verbose

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#69328]
start code with --verbose

This prints the storage content which is taking several pages (containing the persisted color and icon themes).
Maybe cut all values that are larger 100 chars? Or do not print the storage content?

![image](https://user-images.githubusercontent.com/6461412/53322212-07b7f380-38db-11e9-8d01-f996085ae9c5.png)

**Comment by bpasero** [comment]
Yeah I think I can possibly remove the output of the storage service from there by now. If anyone wants to take this via a small PR, be my guest.

**Comment by Ashniu123** [comment]
I'd like to take this up :+1:

**Comment by bpasero** [comment]
@Ashniu123 I would think this is across all OS.

Now that I realize, this might be less easy to fix as a "help wanted" because it actually just uses our log service. I think I will look into this.
