### ISSUE TITLE
PHP mysqli function auto-completion is missing .

### ISSUE THREAD

**Issue by saberhosneydev** [Microsoft/vscode#69325]
Issue Type: <b>Bug</b>

I found that there's no auto-completion for certian PHP built-in functions like mysqli and it's dependicies like mysqli_errno function as well. As far as I follow PHP 7 I know it's a built-in so seems VSCode has other functions supported  even with Intel on each .

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7600  @ 3.06GHz (2 x 3059)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (1.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sqltools|mtx|0.16.11

</details>

**Comment by tigerhawkvok** [comment]
IIRC it's because you're "supposed" to use the object syntax. You probably want to ping the PHP language server guys: https://github.com/felixfbecker/php-language-server

**Comment by roblourens** [comment]
vscode's builtin auto completion is simple and our definitions are a bit out of date. I recommend using an extension like the PHP Intellisense extension
