### ISSUE TITLE
UI Bug with window.zoomLevel -2 on MacOS with window.menuBarVisibility => Visible

### ISSUE THREAD

**Issue by Cow258** [Microsoft/vscode#69323]
Issue Type: <b>Bug</b>

<img width="474" alt="2019-02-25 11 27 48" src="https://user-images.githubusercontent.com/14261588/53312756-45277b80-38f1-11e9-835d-51d95a85e6c9.png">

Look at the left top corner to see the bug.
Thank you.

VS Code version: Code - Insiders 1.32.0-insider (4e68ba25fbc752e3d7da488b8d3db374029577d6, 2019-02-18T06:15:59.901Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|24.00GB (4.88GB free)|
|Process Argv|-psn_0_6641237|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
gltf-vscode|ces|2.2.3
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-mysql|for|0.3.0
minify|Hoo|0.3.0
code-beautifier|mic|2.1.0
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hant|MS-|1.32.2
mssql|ms-|1.4.0
vsliveshare|ms-|0.3.1225
material-icon-theme|PKi|3.6.3
ejs-language-support|Qas|0.0.1

</details>

**Comment by sbatten** [comment]
I am unable to reproduce this. Would you mind sharing your complete `settings.json` file?

**Comment by Cow258** [comment]
i just "cmd" + "-" x 2. 
btw, i will provide you the setting.json tomorrow when i back to office.

**Comment by sbatten** [comment]
@Cow258 I can repro. The cause is having `window.menuBarVisibility` in you settings.json on macOS. likely the settings file was shared from a Windows or Linux machine? In any case, I'm fixing this.

**Comment by Cow258** [comment]
yes, i am working with cross platforms, thx
