### ISSUE TITLE
Hover: toolbar should not be replicated when there are multiple errors 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#69327]
Create a setup where there are multiple errors with fixes.
Notices that the 'toolbar' is shown for each quick fix

![image](https://user-images.githubusercontent.com/172399/53321331-66c83900-38d8-11e9-9ba7-dbbd788c3dee.png)

Suggest to only show it for the last one, users will be able to step through all the other errors from the peek experience.

**Comment by sandy081** [comment]
There is no toolbar anymore and actions are shown as part of the error. For eg:

![image](https://user-images.githubusercontent.com/10746682/53324820-0807bd00-38e2-11e9-9d26-c55f41079e0d.png)

Now, they are part of the error message text and makes them belongs to the error. Let me know if you still want the actions only for last one?

**Comment by sandy081** [comment]
Changed to show status bar at the end.

![image](https://user-images.githubusercontent.com/10746682/53339401-87a78300-3906-11e9-8b50-26de1b66dda5.png)
