### ISSUE TITLE
Remove IFileService.readFolder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69330]
It looks like `IFileService.readFolder()` was added via https://github.com/Microsoft/vscode/commit/15177f207cc8cf8dc32951491845e4eb251f2f6b but `resolveFile` can be used for folders too. The file explorer is using that method to resolve folders.

**Comment by bpasero** [comment]
@chrmarti @alexr00 fyi please see https://github.com/Microsoft/vscode/commit/35068aeccd652f55359fb6d2691b5f95f261dd66 for the adoption in your code.

**Comment by chrmarti** [comment]
Thanks @bpasero !

**Comment by alexr00** [comment]
Yes, thanks!
