### ISSUE TITLE
ipc.electron: use Buffers

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69338]
Based on [this comment](https://github.com/Microsoft/vscode/blob/11416de365a1e96302e171c9eebc2547872ac230/src/vs/base/parts/ipc/node/ipc.electron.ts#L11):

>  This implementation doesn't perform well since it uses base64 encoding for buffers.
> Electron 3.0 should have suport for buffers in IPC: https://github.com/electron/electron/pull/13055

**Comment by joaomoreno** [comment]
@bpasero Their implementation isn't that great... they do exactly the same as we do: https://github.com/electron/electron/pull/13055/files#diff-afb53538fba027cfc7e028f785f2c57aR47 :man_facepalming:

**Comment by joaomoreno** [comment]
Still, removed our unnecessary base64 transformation.
