### ISSUE TITLE
wrong color in shell

### ISSUE THREAD

**Issue by YuanshengZhao** [Microsoft/vscode#69336]
- VSCode Version: 1.31.1
- OS Version: MacOC Mojave 10.14.3

Steps to Reproduce:
1. create a shell typed document. ex: `foo.sh`.
2. paste `./a.out test`.

The `test` is in highlight color, but here it is only an argument passed to `a.out`, and should not be highlighted.

![image](https://user-images.githubusercontent.com/37881856/53327484-3cec3200-392b-11e9-8246-69370a2d8f83.png)

**Comment by alexr00** [comment]
This issue was moved to atom/language-shellscript#137

**Comment by alexr00** [comment]
Moved to the repo where we get this grammar from.
