### ISSUE TITLE
Parts of serverReadyAction should be contributed by chrome debug

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#69339]
Refs #69313

It feels like parts of the `serverReadyAction` are tightly coupled with the chrome debug extension.
Due to that I feel like those attributes should be contributed from the chrome debug extension - since they do not really make sense if the chrome debug extension is not installed.
An example of such an attribute is `webRoot`.
Another is the `"action": "debugWithChrome"`

If we allow these attributes to be contributed by the chrome extension it should make it easier to integrate this for other browser debug extensions like firefox.

**Comment by weinand** [comment]
Yes, that the discussion we have here: https://github.com/Microsoft/debug-adapter-protocol/issues/23#issuecomment-465524246

**Comment by connor4312** [comment]
A while ago I added a "startDebugging" action which allows the user to name another launch configuration they want to invoke, which can be Firefox or any other debug configuration they would like to launch.

(technically it could make arbitrary chained launch configurations, they don't even have to be browsers...)
