### ISSUE TITLE
Contributed action is not visible when group is not provided

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#69340]
Testing #69196

```json
"menus": {
			"debug/toolbar": [
				{
					"command": "test.restartDebug",
					"when": "debugType == node2"
				}
			]
		}
```

Command is not there anywhere in the toolbar. There should be some assistance to say that group is mandatory or by default show it in the tool bar?

**Comment by sandy081** [comment]
When I provide the group, the contributed action is show at the beginning.

![image](https://user-images.githubusercontent.com/10746682/53410686-c3a11d80-39c4-11e9-9c94-ccb9dd6aa7b1.png)

**Comment by isidorn** [comment]
@sandy081 great catch, thanks!
