### ISSUE TITLE
serverReadyAction has a very short description

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69341]
Refs: #69313

Hover over `serverReadyAction` - you get "Server Ready options". I suggest to put a more elaborate description of what this attribute is actually used for.
Inside the `serverReadyAction` all the attributes have a nice description and those are great.

**Comment by weinand** [comment]
I'm now using this description:

"Open a URI externally when a server program sends output of the form 'listening on port 3000' or 'Now listening on: https://localhost:5001' to the debug console."

**Comment by isidorn** [comment]
Cool.
