### ISSUE TITLE
Consider renaming serverReadyAction -> onServerReady

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69342]
Refs: https://github.com/Microsoft/vscode/issues/69313

Just personal preference, but I prefer onServerReady since it sounds more like what it does -> that we actually do something when the server is ready.

**Comment by isidorn** [comment]
Also consider renaming `pattern` to `portPattern` since the pattern property only captures the port looking at the description.
Unless there are plans in the future to extend this property to more.

**Comment by isidorn** [comment]
Also consider to change `openExternally` to `openExternal` since that is the name that we use in our vscode.d.ts https://github.com/Microsoft/vscode/blob/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea/src/vs/vscode.d.ts#L5969

**Comment by weinand** [comment]
- pattern: No, the pattern covers ports or URIs.
- openExternally: end user features don't have to match grammatically incorrect developer API names.
