### ISSUE TITLE
Settings: remove notification that changes are saved

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#69349]
I am sure by now everyone got this:

![image](https://user-images.githubusercontent.com/900690/53330131-0643f680-38ee-11e9-8866-ef112e2512cd.png)

**Comment by roblourens** [comment]
I used to get issues about people not sure whether settings were saved, now I don't. You should only see it once in a new user data dir.

**Comment by bpasero** [comment]
I think given our latest move to reduce notifications we should revisit this.

//cc @isidorn

**Comment by isidorn** [comment]
Agree. @roblourens would you be open to remove this notification now?
This only happens in JSON settings? This one is advanced and maybe those users do not need help?

**Comment by bpasero** [comment]
This happens with our standard settings editor:

![image](https://user-images.githubusercontent.com/900690/116369756-03b0f480-a80a-11eb-8ce7-af3c233898d9.png)

**Comment by isidorn** [comment]
Oh I misunderstood, then I would definitely remove this notification. Most UI now days do not have an Apply button and none of the notify that you do not have to click apply for the setting to be applied.

@stevencl @devinvalenciano did we run some user studies where participants would get confused if their settings get saved? Could we maybe remove this notification and run a short study to gather some impressions.

Reopening this issue for discussion

**Comment by roblourens** [comment]
As I remember, this came directly from user studies. But that was 3 years ago and maybe we can just assume that people are used to it now? You will also only get it once.

**Comment by stevencl** [comment]
I don't remember the details from the user study but I think it would be fine to remove this and then also follow up with a short study.

**Comment by isidorn** [comment]
@stevencl cool.
@roblourens do you mind if we remove this in May debt week, so we have the whole May milestone to gather feedback and maybe do a short study?

**Comment by bpasero** [comment]
Since I noticed this again now in endgame week with fresh installs, decided to put up a PR with the notification removed in https://github.com/microsoft/vscode/pull/125083

**Comment by isidorn** [comment]
Awesome, thanks for doing that 👏
