### ISSUE TITLE
serverReadyAction.uriFormat not respected

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69344]
Refs: #69313

The uriFormat is not respected for me, whatever I enter there localhost is opened. Here are my steps

1. Clone our smoketest experess app https://github.com/Microsoft/vscode/wiki/Smoke-Test
2. Use the following launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "smartStep": true,
            "name": "Launch Program",
            "program": "${workspaceFolder}/bin/www",
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "Port: ([0-9]+)",
                "uriFormat": "http://WRONG:%s",
            }
        }
    ],
}
```
3. Notice how the localhost is opened, not my WRONG uri format 🐛

**Comment by weinand** [comment]
@isidorn The name of the property is in fact "urlFormat" (which is consistent because I'm talking about URIs).

**Comment by isidorn** [comment]
Cool that works now!
So the issue is that in the scheme you are recommending `uriFormat` it should recommend `urlFormat`

**Comment by weinand** [comment]
yep, that's the issue
