### ISSUE TITLE
Explorer simple navigation should navigate, not just highlight

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#69359]
Explorer simple navigation should immediately select the first file that's matching the entered pattern while typing. Currently, it doesn't.

The current behaviour is rather confusing:

![explorer doesn t select file](https://user-images.githubusercontent.com/9283914/53335083-ca635e00-38fa-11e9-8754-c47ba8560989.gif)
<hr/>

- VSCode/OS Version:

   ![VS Code version](https://user-images.githubusercontent.com/9283914/53335040-af90e980-38fa-11e9-9c00-cfcfc68fc5d7.png)

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders
