### ISSUE TITLE
Terminal bug

### ISSUE THREAD

**Issue by Gizmodo** [Microsoft/vscode#69351]
When i select Terminal tab i see blank window without any text. When i type something and hit enter - text comes back. I have to type something to see terminal text.
I attached an image. I entered "ef" and hit Enter. After that I saw "PS D:\Develop\mern_shopping_list>"

![error](https://user-images.githubusercontent.com/1078610/53330306-36e05c00-38ff-11e9-897c-924eccf8dc49.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
