### ISSUE TITLE
Unneeded picker when `Set Color Theme` for extension with only one theme

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#69356]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/69202

![image](https://user-images.githubusercontent.com/9205389/53334069-f6c9ab00-38f7-11e9-9a5f-f586e79a0bc9.png)

VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user pullrequest-demo|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github-insiders|Git|1.50.0

(2 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
Same with `Set File Icon Theme`. It would also make sense to hide these buttons if the only theme in the extension is already the current theme.

**Comment by sandy081** [comment]
Had these actions for consistency. Not showing any action without any information might be confusing. Do you think its better to show themes from other extensions too?

**Comment by chrmarti** [comment]
Maybe add an `Show all installed themes` pick?

**Comment by sandy081** [comment]
Showing other themes might also be confusing/inconsistent with other extensions. I think showing the existing theme is the better (not best) than other mentioned. I would not do anything unless I get a better suggestion that is worth. Closing it until.
