### ISSUE TITLE
Tree: Support for automatically expanding parent nodes of filter matches

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#69352]
Testing #69299

- enable filtering on type in the outline
- collapse all nodes using collapse all
- type a symbol that you know exists that but is collapsed
 
-> the parent node is not expanded

In this example the symbol `type` exists, but it is not expanded:

![image](https://user-images.githubusercontent.com/172399/53330746-97679d00-38ef-11e9-865f-de073f12d34f.png)

![image](https://user-images.githubusercontent.com/172399/53330794-b49c6b80-38ef-11e9-862c-f1111f52cbea.png)

**Comment by jrieken** [comment]
@joaomoreno is that something the filter controls? how do I achieve this? would I know when filtering happens/happened so that I can call expand all?

**Comment by jrieken** [comment]
I have pushed a change that restores the old behaviour when filtering but for "type to find" more is needed. Moving to March to the remainder...

**Comment by joaomoreno** [comment]
This is now fixed.
