### ISSUE TITLE
explorer.autoReveal sometimes not working

### ISSUE THREAD

**Issue by SM-durofusic** [Microsoft/vscode#69354]
- VSCode Version: 1.31.1 (1.31.1)
- OS Version: MacOS High Sierra

Steps to Reproduce:

1. Open a file and expect that it will be in focus in explorer
2. Sometimes works, sometimes doesn't

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68627
