### ISSUE TITLE
Searching for the exact extension id should yield in a better score

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#69350]
* paste `GitHub.vscode-pull-request-github-insiders` into the extension viewlet search box
* the extension with that ID isn't a good match at all...

<img width="1510" alt="screenshot 2019-02-25 at 11 13 49" src="https://user-images.githubusercontent.com/1794099/53330332-866a5c00-38ee-11e9-8846-838aa6ed18b3.png">

**Comment by sandy081** [comment]
To search by id, you should use `@id:extensionId` otherwise all strings are sent to marketplace for searching.

**Comment by sandy081** [comment]
@kesane-msft Is it possible to return the extension with the given id when searched by id. Eg: `GitHub.vscode-pull-request-github-insiders` returns Github Pull Requests nightly extension on the top?

**Comment by kesane-msft** [comment]
@sandy081 - Let me take a look at it and get back to you.

**Comment by sandy081** [comment]
Verify that searching by id returns only the extension with that id.
