### ISSUE TITLE
cmder no longer works on integrated terminal and spams external cmder instances

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6935]
Pretty sure ti was at one point, now it's opening a bunch of issues repeatedly as they exit with exit code 0.

**Comment by Tyriar** [comment]
Actually I'm not sure this every worked as cmder is a full blown UI app, the issue with the relaunching is fixed though so closing this.

**Comment by joaomoreno** [comment]
Any verification steps here?
