### ISSUE TITLE
Glob regex matches too much

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6936]
`glob.match("**/project.json",...) ` results in the regexp `(?:[/\\].*?|.+?[/\\]|)project\.json`

The or segment is strange `[/\\].*?`.
This results in `/rrproject.json` to be matched

**Comment by bpasero** [comment]
@aeschli I am not able to reproduce and pushed tests to proove it: https://github.com/Microsoft/vscode/commit/f7494b2057d801a3576c46128b196468813ab1c8

Please let me know what you saw.

**Comment by aeschli** [comment]
I was looking at glob.ts, parseRegExp. I added a breakpoint on line 210, `return regEx`.
There you see that e.g. `**/*.cs` is transformed into `(?:[/\\].*?|.+?[/\\]|)[^/\\]*?\.cs` which is not correst, as explained above.  But then in glob.ts, match line 303 it finds out that `parsedPattern.trivia === Trivia.T1` and doesn't use the pattern. Oh, lucky :-) But a lot of work to find out that this is just Trivia.T1.

But then there's pattern
`{**/package.json,**/project.json}`
resulting in
`(?:(?:[/\\].*?|.+?[/\\]|)package\.json|(?:[/\\].*?|.+?[/\\]|)package\.json|(?:[/\\].*?|.+?[/\\]|)project\.json)`
which is really used and fails:

```typescript
		p = '{**/package.json,**/project.json}';
		assert(glob.match(p, 'package.json'));
		assert(glob.match(p, '/package.json'));
		assert(!glob.match(p, 'xpackage.json'));
		assert(!glob.match(p, '/xpackage.json'));
```
Also note that there are two segments for 'package.json' and a non-capturung group around everything.

**Comment by aeschli** [comment]
Then there other cases that are still far too complicated and inefficient. It looks like #5438 is not really fixed.
{**/*.ts,**/*.tsx**/*.js,**/*.jsx,**/*.es6} ->
(?:(?:[/\\].*?|.+?[/\\]|)[^/\\]*?\.ts|(?:[/\\].*?|.+?[/\\]|)[^/\\]*?\.ts|(?:[/\\].*?|.+?[/\\]|)[^/\\]*?\.tsx[^/\\]*?[^/\\]*?[/\\][^/\\]*?\.js|(?:[/\\].*?|.+?[/\\]|)[^/\\]*?\.jsx|(?:[/\\].*?|.+?[/\\]|)[^/\\]*?\.es6)
It's correct, but `*.\.ts|*.\.tsx|*.\.js|*.\.tsx` would do it. The non-capturing groups also don't seem to be needed.

**Comment by bpasero** [comment]
@aeschli ah right, I was falling through my own optimisations in the test...

You seem to have an idea how to come up with efficient regexes for the glob patterns, so I will come to you next week so that you can show me your ideas :).

**Comment by aeschli** [comment]
The revert did not fix the problem. I extracted #9917.
