### ISSUE TITLE
Add horizontal line to problem hover

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#69360]
testing #69204:

I suggest to separate the hover's status bar with the `Peek Problem` and `Quick Fixes` actions from the "contents area" by another horizontal line:

![2019-02-25_12-47-25](https://user-images.githubusercontent.com/1898161/53335511-f03d3280-38fb-11e9-970a-5dbff257f3b6.png)

**Comment by weinand** [comment]
And please consider to use a smaller font for the hovwer's status bar (or better: the same size as the main status bar).

**Comment by sandy081** [comment]
@weinand This is how it looks if we use same style as status bar

![image](https://user-images.githubusercontent.com/10746682/53338076-08648000-3903-11e9-9f0a-f231d1c123be.png)

Does not it look odd with the rest of the hover?

**Comment by sandy081** [comment]
I think it looks good after adding a default status bar background

![image](https://user-images.githubusercontent.com/10746682/53339311-4d3de600-3906-11e9-980b-95d056f7b70c.png)

**Comment by bpasero** [comment]
@sandy081 I like it a lot. should "Quick Fix" appear first though?

**Comment by sandy081** [comment]
Done
