### ISSUE TITLE
Missing "Recent Workspaces" in task bar

### ISSUE THREAD

**Issue by HaaLeo** [Microsoft/vscode#69365]
# Question/Bug Report
I there any update on #63197? 
I experience the same issue.   

# Environment
Version: 1.32.0-insider (system setup)
Commit: ce073b0076ac2f69faf2c609af72f9b81506c791
Date: 2019-02-27T06:17:47.743Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

# Steps to reproduce
1. Download vscode insider system setup
1. Install it. An important note is that the user that executes the `.exe` has no admin priviledges. So before the installation the user is asked to insert admin credentials. During the installation I unchecked all combo boxes (about adding it to PATH and so on)
1. Open vscode insider
1. Pin it to the task bar
1. In vscode select _Open Folder_ on several git repositories
1. Close vscode
1. Right click on the vscode insider icon in task bar

# Expected Bevavior 
The previously opened folder are shown as _Recent Workspaces_ in the context menu

# Actual Behavior
no _Recent Workspaces_ are shown in the context menu

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by HaaLeo** [comment]
@bpasero I could reproduce the behaviour with the insiders build. I updated the description above.

**Comment by bpasero** [comment]
I cannot really reproduce this, just tried with a system installation of Insiders:

![image](https://user-images.githubusercontent.com/900690/53480393-69af5f00-3a7b-11e9-8677-4d9ba2c6fc47.png)

I wonder if there is any entry in your list that makes Windows stop adding entries. Can you do `File > Open Recent > Clear Recently Opened` and then go from there to see if that helps?

**Comment by HaaLeo** [comment]
After executing the command I still get only this.
![grafik](https://user-images.githubusercontent.com/23164374/53480820-3e793f80-3a7c-11e9-8f2a-8b862c2a9258.png)

**Comment by bpasero** [comment]
Ok too bad, I am not sure what this is then.

**Comment by bpasero** [comment]
@HaaLeo 

> 5\. In vscode select _Open Folder_ on several git repositories

Question: do you open one folder or multiple at once?

**Comment by HaaLeo** [comment]
@bpasero I select _Open Folder_ on a single folder, that contains a git repo, then I edit a file, save the file and then start over again.  
I edited the original post.

**Comment by bpasero** [comment]
If someone has ideas how to debug this on the Windows side, let me know.

**Comment by HaaLeo** [comment]
I found the error. It was a disabled windwos setting.  
To enable the "_Recent workspaces_" again on windows 10 do the following:
1. go to _Settings_ &rarr; _Personalization_ &rarr; _Start_ 
1. Turn on the option "_Show recently opened items in Jump Lists on Start or the taskbar_".  

It seems like some windows update may has disabled this behavior.
