### ISSUE TITLE
Wrong level of file creating using hotkey

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#69368]
Issue Type: <b>Bug</b>

Explorer asks to input file name for a new file on the wrong level after pressing <kbd>Escape</kbd> button. On the gif file below we have focus on `HOC` directory, but input field created on the root level of the project.

![bug](https://user-images.githubusercontent.com/46930/53245913-d9a69980-36b7-11e9-9fa1-6968cc59e9bb.gif)

@joaomoreno asks to create this issue. Related issue is https://github.com/Microsoft/vscode-atom-keybindings/issues/56

Keyboard navigation: simple.
Extension to switching keyboard context is installed.

VS Code version: Code - Insiders 1.32.0-insider (b64026839eed3dd03a6d6fe0ba3910255490c279, 2019-02-22T08:34:22.116Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 6, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
atom-keybindings|ms-|3.0.6
</details>

**Comment by controversial** [comment]
My understanding is that this is because `simple` keyboard navigation still attempts to select the nearest file beginning with `a` when you press `a`, and that the “create file” action is only triggered secondary to that, so the focus has already shifted when the file is created. Super annoying.
