### ISSUE TITLE
Explorer should (optionally) select file having focus

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#69361]
I often find myself editing a number of adjacent files.

To do so, while having opened a file in the editor, I hit <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>E</kbd> to give focus to the Explorer. I'd expect the corresponding file from the editor having focus before to be selected in Explorer then. I could then just hit <kbd>ARROW DOWN</kbd>, <kbd>RETURN</kbd> to be able to edit the next file.

Currently, only the "opened editors" panel is in sync with the currently opened file in an editor which is having focus.

I propose to have the _Explorer_ always be in sync with the currently opened file in the editor having focus, too.

**Comment by isidorn** [comment]
Fixed in latest insiders
