### ISSUE TITLE
workbench.colorCustomizations stopped working in insiders

### ISSUE THREAD

**Issue by jeffshaver** [Microsoft/vscode#69366]
- VSCode Version: 1.32.0-insider commit 393b48d4a5de85b6fa1d2ad0a59588d6715e12ea
- OS Version: CENTOS 7
- Electron: 3.1.3
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Linux x64 3.10.0-957.1.3.el7.x86_64

Steps to Reproduce:

1. Add color theme customizations to vscode workspace settins
2. Launch code-insiders

Does this issue occur when all extensions are disabled?: Yes

This currently works in normal VSCode on my OS. But it is broken on the insiders version

**Comment by aeschli** [comment]
I just tried with the latest insiders and it works for me.
Make sure your settings file doesn't have invalid syntax, or that you have not defined colorCustomizations in the workspace or workspace folder settings.

**Comment by jeffshaver** [comment]
@aeschli thanks for the reply. But the same settings work correctly on regular vscode. So that leads me to believe there aren't any issues with syntax errors. My settings file was fine. I updated insiders, and then it was broken.

**Comment by aeschli** [comment]
Tried again, all works for me. I need a reproducible case. Maybe you send me the workspace settings file?

**Comment by jeffshaver** [comment]
Here is my settings.json file for my workspace settings. 
```
{
  "workbench.colorCustomizations": {
    "titleBar.activeBackground": "#09f",
    "titleBar.inactiveBackground": "#09f",
    "titleBar.inactiveForeground": "#ffffff",
    "titleBar.activeForeground": "#ffffff"
  },
  "tslint.autoFixOnSave": false
}
```
This is code-insiders
![image](https://user-images.githubusercontent.com/5390616/53414791-89705580-399d-11e9-9b0c-61615cb7d922.png)

This is normal vscode
![image](https://user-images.githubusercontent.com/5390616/53414831-a7d65100-399d-11e9-9785-7314edd454f3.png)

**Comment by musicfuel** [comment]
@jeffshaver Do you have the `window.titleBarStyle` on insiders set to native by chance? Looking at your two images the title bar rendering with the menu is clearly different with the menu inside on the the normal vscode and the menu below in the code-insiders.

This looks very similar to issues noted by [Peacock](https://github.com/johnpapa/vscode-peacock#title-bar-coloring) when dealing with coloring the title bar.
