### ISSUE TITLE
Terminal Chars are ALWAYS UPPERCASE on MacOSX when 'keyboard Caps on'

### ISSUE THREAD

**Issue by lxx2013** [microsoft/vscode#69367]
Issue Type: <b>Bug</b>
![image](https://user-images.githubusercontent.com/20529542/53340736-a62c6f00-3944-11e9-8fb3-efc9a705c072.png)

Mac's default style of 'UpperCase or LowerCase' is widely-known as follows:
1. when 'Caps off && Shift off', It maybe 'Chinese IME'
2. when 'Caps on && Shift off', It is 'English LowerCase mode'
3. when 'Caps on && Shift on' , It is 'English UpperCase mode'

But the terminal in the vscode of version 1.31.1 didn't display correctly at scene 2.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 17.5.0, OSX 10.13.4

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.49GB free)|
|Process Argv|-psn_0_307275|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
doxdocgen|csc|0.4.1
app-migrator|deb|0.0.6
EditorConfig|Edi|0.13.0
lex-flex-yacc-bison|fau|0.0.3
vscode-flow-ide|gca|1.2.0
vscode-gutter-preview|kis|0.17.5
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.1.0
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.2
vetur|oct|0.16.2
minapp-vscode|qiu|1.12.1
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.5
fantastical-vuejs-code|sld|0.1.2
stylus-supremacy|thi|2.12.7
vscode-import-cost|wix|2.12.0
html2jade|wma|0.2.0
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Other terminals do this too.

**Comment by lxx2013** [comment]
Well, Mac's default Terminal.app and iTerm2 won't do this. Disappointed at your reply.

**Comment by Tyriar** [comment]
Ah I wasn't reproducing the right thing, this appears to be specific behavior of Chinese IMEs. Repro:

1. Enable PinYin IME
2. Type (Chinese auto completions appear)
3. Caps lock on
4. Type - This should be lowercase in the terminal but it's uppercase

**Comment by henpin** [comment]
i have same issue(Japanese IME
it appeared after updating latest MacOS

MacBook Pro (13-inch, 2017,
Mojave 10.14.3
code 1.31.1 (1.31.1)

**Comment by henpin** [comment]
My problem is fixed

1. Open keyboard settings -> input source
2. set "CapsLock behavior" as "input Alphabet when CapsLock is Off"

**Comment by Tyriar** [comment]
@lxx2013 did this comment help resolve the problem for you?

https://github.com/Microsoft/vscode/issues/68865#issuecomment-467309670

**Comment by lxx2013** [comment]
> @lxx2013 did this comment help resolve the problem for you?
> 
> [#68865 (comment)](https://github.com/Microsoft/vscode/issues/68865#issuecomment-467309670)

I tried to set `terminal.integrated.setLocaleVariables` to `true` or `false`. It doesn't work.

My OSX version is 10.13.4. My Chinese IME is [Baidu IME for Mac](http://srf.baidu.com/input/mac.html)

**Comment by yifanchen** [comment]
@henpin Brilliant

**Comment by yifanchen** [comment]
Regarding #68865, @henpin's solution works fine for macOS's default Chinese input source ,but not for Sougou input, a 3rd party input source which is the most popular Chinese input.

**Comment by Tyriar** [comment]
Tracking upstream https://github.com/xtermjs/xterm.js/issues/2457

**Comment by yjw0628** [comment]
![image](https://user-images.githubusercontent.com/15664734/69019961-e4475280-09ed-11ea-8c42-652b5ab2fd63.png)
