### ISSUE TITLE
Explorer "Auto Reveal" option should be considered when no editors are open

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#69362]
Currently, the `"explorer.autoReveal": false` option is not properly considered when no editors are open:

![explorer auto reveal option not working properly](https://user-images.githubusercontent.com/9283914/53337124-c76b6c00-3900-11e9-88b0-df0508df5b30.gif)
<br/>

This is very confusing given that there was no intention whatsoever to open the corresponding file in any editor.
<hr/>
<br/>

- VSCode/OS Version:

   ![grafik](https://user-images.githubusercontent.com/9283914/53337080-a60a8000-3900-11e9-8377-de4bece532b0.png)

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders
