### ISSUE TITLE
File Picker: arrow up/down should not change cursor in input field

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69378]
In the new file picker (on macOS) when I use the arrow keys to go up, the cursor in the input field jumps to the beginning of the line for some reason:

![before](https://user-images.githubusercontent.com/900690/53353640-8174cf00-3925-11e9-8c9d-82a7a2076aa6.gif)

**Comment by alexr00** [comment]
This is actually an existing issue with the quick pick. @chrmarti FYI.
