### ISSUE TITLE
File Picker: arrow up/down could change input to the path that is selected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69379]
When using the remote picker and arrow keys to go up and down, why not fill in the name of the selected item (selected so you can type over).

**Comment by alexr00** [comment]
To verify
1. Add this setting: `"workbench.dialogs.useSimplified": true`
2. File->Open. Then use the up and down arrows in the file picker. Verify that the input box shows the path that you have arrowed to.
