### ISSUE TITLE
cli.js Automatically Opening After VSC is closed.

### ISSUE THREAD

**Issue by getduckt** [Microsoft/vscode#69373]
Hello,

So I recently changed to vsc from Atom and I have this issue, Where when I close vsc after 5-10 minutes it AUTOMATICALLY opens and opens a file called "cli.js" this is the content: https://pastebin.com/fVFjpneb

If VSC is 100% closed even tho it automatically opens.

Tried:
1. Reinstalling vsc
2. Deleting the code in cli.js
3. Deleting the file cli.js
4. checking task manager for an hidden open program
5. Asking other developers for help
6. Searching for cli.js on microsoft official vsc page.

**Comment by Tyriar** [comment]
@getduckt are you on Windows?

**Comment by getduckt** [comment]
@Tyriar Yes, I am

**Comment by joaomoreno** [comment]
When it does open with that file, can you use Process Hacker (or another process explorer) to find all Code.exe processes and show me their full command line?

**Comment by getduckt** [comment]
@joaomoreno How?

**Comment by joaomoreno** [comment]
@getduckt Download [Process Hacker](https://processhacker.sourceforge.io/). When the time comes, run it, type Code.exe in the search bar and take a screenshot.
