### ISSUE TITLE
WorkspaceSymbolProvider is called with empty query string although API states otherwise

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#69372]
This got noticed on the LSP side (see https://github.com/Microsoft/vscode-languageserver-node/issues/458). 

I am pretty sure that we didn't do that for performance reasons in the past.

**Comment by jrieken** [comment]
not since three years: https://github.com/Microsoft/vscode/issues/11175

**Comment by dbaeumer** [comment]
Then we should update the API doc :-)

**Comment by jrieken** [comment]
done
