### ISSUE TITLE
File link size differs in hover and problems view

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69383]
#69204

The rest of the message is the same size:

![image](https://user-images.githubusercontent.com/2193314/53356132-929aed00-38df-11e9-9a5f-48cf015aa07c.png)

Version: 1.32.0-insider (user setup)
Commit: 393b48d4a5de85b6fa1d2ad0a59588d6715e12ea
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

**Comment by Tyriar** [comment]
The same applies to ts(...):

![image](https://user-images.githubusercontent.com/2193314/53356318-03420980-38e0-11e9-9870-03ff564fff9a.png)

**Comment by sandy081** [comment]
Fixed. To be consistent applied editor font for all.
