### ISSUE TITLE
Hover actions feedback

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69386]
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

While it looks alright here:

![image](https://user-images.githubusercontent.com/2193314/53356593-98dd9900-38e0-11e9-8964-a3bf49b2192a.png)

The actions look particularly ugly when there is a pointer to the file:

![image](https://user-images.githubusercontent.com/2193314/53356643-b3b00d80-38e0-11e9-987d-5d83259bdbd3.png)

Not sure if we can do anything to improve just that case.

Also the bottom padding should match the top padding if there is no "status bar" background color.

**Comment by sandy081** [comment]
There were some changes to the status bar background which makes it distinguishable from the message.

![image](https://user-images.githubusercontent.com/10746682/53368883-30c39d00-394a-11e9-849f-2c906b17d771.png)

**Comment by misolori** [comment]
@sandy081 we should make sure that the text link passes the color contrast ratio with that background color:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/35271042/53369392-f6351280-38ff-11e9-81ba-cf5dbb91a9d5.png">

**Comment by misolori** [comment]
Fixed this via 5f2ecc87c8b87a5f65dd4f470c1a0e1a67f2bd9f:

## Dark
<img width="443" alt="image" src="https://user-images.githubusercontent.com/35271042/53371061-28487380-3904-11e9-96fd-68a9faa07ba1.png">

<img src="https://user-images.githubusercontent.com/35271042/53371143-53cb5e00-3904-11e9-9f9b-292696a30863.png" width="50%">


## Light
<img width="358" alt="image" src="https://user-images.githubusercontent.com/35271042/53371070-2b436400-3904-11e9-82ef-e915c5774350.png">
<img src="https://user-images.githubusercontent.com/35271042/53371121-43b37e80-3904-11e9-9f68-4ec4c469f443.png" width="50%">
