### ISSUE TITLE
Bad wrapping on hover

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69387]
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

There appears to be room to the right for the text so it shouldn't have wrapped

![image](https://user-images.githubusercontent.com/2193314/53357831-9af52700-38e3-11e9-9dfa-be662d36ea7d.png)

**Comment by sandy081** [comment]
This wrapping is done by browser automatically and there is no special treatment. Would be great if there are any suggestions on doing it differently.

**Comment by Tyriar** [comment]
@sandy081 something wrong is going on, otherwise there wouldn't be all this empty space on the right? Is the hover programmatically sized based on the width of the text? If so maybe it's a few pixels off which is causing the wrap?

**Comment by sandy081** [comment]
Hover is not sized based on the width of the text. Instead the width is computed from the editor.

**Comment by Tyriar** [comment]
@sandy081 doesn't it have to be based on the width of the text otherwise this wouldn't fit so perfectly? 🤔

<img width="348" alt="screen shot 2019-03-01 at 11 28 19 am" src="https://user-images.githubusercontent.com/2193314/53661457-31dc1f00-3c15-11e9-90a5-c387fb1c30d6.png">

**Comment by sandy081** [comment]
We cannot compute the width from the text as the text can be any (Markdown). Other option is to remove the max width on hover so that there is no wrapping.
