### ISSUE TITLE
Recent Conflicted Commits breaks ability to paste multi-line to multi-location.

### ISSUE THREAD

**Issue by Acts7** [microsoft/vscode#69385]
- VSCode Version: Version 1.31.1 (1.31.1)
- OS Version: MacOSMojave 10.14.3 (18D109)

Steps to Reproduce:

1. Select several lines of code (lets say 7)
2. Copy.
3. Place cursor in multiple locations. (let's also do 7)
4. Paste.

If the number of lines copied equals the number of cursor locations, the copied code each only receives the next successive line.

Expected behavior :
Pasting selection should not rely on number of lines copied or pasted.

Additional info:
Two recent fixes were released which caused this conflict:
https://github.com/Microsoft/vscode/issues/30397
https://github.com/Microsoft/vscode/issues/46440

I really the root cause is due to this "fix": 
https://github.com/Microsoft/vscode/issues/46440

If one expects to copy multiple lines and have each successive line pasted into the next cursor location... then one should rely upon multi-cursor selection.

The user in this https://github.com/Microsoft/vscode/issues/46440 errors in expecting matched lines copied to equal one of each successive lines pasted. The user here should have made the selection, then split the cursor for each line. Then copied. This would have allowed copying multiple lines to equal successive pasted lined.  
(i.e. select 3 lines, hit alt+shift+I ... or opt+shift+I on mac) that breaks each line into its own selection. Copy that. Place cursor in 3 locations. Paste. That is how this should have been answered rather than patched. Resulting in breaking the ability to paste multiple lines to multiple locations.

As it stands now, if I copy seven lines and paste those 7 lines into 7 locations, I only get 1 of the seven lines at each location. This defeats the purpose of multi-line pasting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Acts7** [comment]
The bot referenced issues are dissimilar to my reported bug.

**Comment by alexandrudima** [comment]
Let's track in #80624
