### ISSUE TITLE
Only show keybindings when you hover the hover

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69384]
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

We don't show hotkeys anywhere except for in the title bar unless hovering, we should follow that here as well and use the `title` attribute:

![image](https://user-images.githubusercontent.com/2193314/53356213-bcecaa80-38df-11e9-86e7-d41a7dbae345.png)

It looks especially ugly when on Linux or Windows because modifiers don't have icons

**Comment by sandy081** [comment]
Yeah it does not look good.
