### ISSUE TITLE
Integrated terminal non-falsey shell exit codes should be reported to the UI, not just the console

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6938]
Steps to Reproduce:

1. Set terminal as "faketerm"
2. ctrl+`

**Comment by aeschli** [comment]
On Linux (ElementaryOS) I get an error dialog with message 'The terminal process terminated with exit code: 1'.
Setting as verified, although more details would be helpful.

**Comment by chrmarti** [comment]
@aeschli Indeed that verifies it. Thanks.
