### ISSUE TITLE
Follow cursor does not expand subtree

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69397]
Testing #69299.

- Have this following scss file:

```scss
.bar {
  .baz {

  }
}
```

- Have `.bar` collapsed.
- Move cursor between `.baz`
- Tree won't expand until you click it

This works in stable.

**Comment by joaomoreno** [comment]
@roblourens With this change, when you call reveal on a tree item which is in the model but not in the view, I take care of expanding its ancestor path, so you should be able to remove stuff like https://github.com/Microsoft/vscode/blob/877f19187d7c0a3f31367332067182a6d0a0d4f8/src/vs/workbench/contrib/preferences/electron-browser/settingsEditor2.ts#L697

@isidorn Still not there for the async trees, but getting close!

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/d810435e3b96da687865858f6b08f81c69d10e3e
