### ISSUE TITLE
Problem view next problem button has wrong color in HC theme

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69390]
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

![image](https://user-images.githubusercontent.com/2193314/53358405-12778600-38e5-11e9-8e1b-13b6d446aee1.png)

**Comment by sandy081** [comment]
@misolori Looks like the I missed this icon in hc. Can you please provide one?

**Comment by misolori** [comment]
This is now fixed 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/35271042/53370445-9429dc80-3902-11e9-945d-c56c4e55d422.png">
