### ISSUE TITLE
Debug toolbar contributed action not aligned when only title is provided

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#69395]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/69196

Only when the toolbar is floating:
![screen shot 2019-02-25 at 9 26 21 am](https://user-images.githubusercontent.com/3672607/53360652-f24ac580-38ea-11e9-9a0d-b74cee8ec4f1.png)

VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.2.0

</details>

**Comment by isidorn** [comment]
I do not really care about this since we do want the extension authors to contribute icons.

**Comment by isidorn** [comment]
Pine also hit it. Assigning to on-deck
