### ISSUE TITLE
Massive Save Dialog box

### ISSUE THREAD

**Issue by douglaswaugh** [microsoft/vscode#69392]
I feel quite silly asking this, but does anybody else see a massive Save dialog box?

Here's a comparison between VSCode and notepad Save dialogs on my machine:

![image](https://user-images.githubusercontent.com/1898630/53359257-4de87380-392a-11e9-9a1f-42878b951cbb.png)

I had assumed it was because I have different monitors on different scaled displays (my main display is scaled at 125%), but I set them all to 100% and I still have the problem.  Perhaps I should try restarting my machine.

If anybody has any ideas I would be very grateful.  It's really annoying me!

I'm on Windows 10 with version 1.31.1 of VSCode.

**Comment by douglaswaugh** [comment]
Okay, I restarted my machine with 100% scaling on all three monitors and it seems as though VSCode inherits the size of its Save dialog at start up.  Changing the scale after the system restarts does not change the size of the dialog box and neither does dragging the dialog box between screens.

Notepad's Save dialog does scale when I drag it between screens set to 100% scale and 125% scale.

I would have thought this was an operating system level component that VS Code and Notepad would have shared, but I must be wrong.

**Comment by PeterWone** [comment]
I'm seeing the opposite, but it's still a scaling issue -- an illegibly small file open dialog on my Surface Book 2 when not using any extra monitors. When I attach 1080P monitors that are scaled at 100% the dialogs are the right size on those monitors and rescaling occurs between monitors. I have tried changing the scaling setting to see whether this would cause a change in behaviour both while and not while VS Code was running. No success either way.

At the same time Firefox produces correctly scaled dialogs. Here they are on the same screen snap.

![image](https://user-images.githubusercontent.com/5498936/55662197-c0674000-5854-11e9-9496-eec62866bb39.png)

**Comment by Eliasar** [comment]
Definitely a Windows (10?) scaling issue. It is affected by the scaling of the main monitor on startup. I set my second monitor to the main monitor and the file dialog scaled with that monitor and not my 4k @ 250% scaling.

Affected monitor: 1440p @ 100% scaling
Main monitor: 3840 x 2160 (4k; UHD) @ 250% scaling
OS: Windows 10 Pro 64 bit
Display Adapters: Intel(R) HD Graphics 630; NVIDIA Quadro M1200
![vscode_oObgI8mmqx](https://user-images.githubusercontent.com/200301/61955601-fa359100-af80-11e9-922f-05413f0578db.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by benrhere** [comment]
I believe this has been fixed for a bit. I'm no longer seeing this on 1.38.1
