### ISSUE TITLE
Make file status / problems color theme-able for focused/selected tree items 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69399]
These two colors are used consistently in various trees (Outline, Explorer, Git). They should be theme-able.

Otherwise theme authors have no way to control certain fg/bg contrasts.

Here's `list.inactiveFocusBackground` against the green foreground.

![image](https://user-images.githubusercontent.com/4033249/53362921-1fe63d80-38f0-11e9-8243-0bbb803387b5.png)

**Comment by octref** [comment]
Would also want to be able to theme unused folder colors:

![image](https://user-images.githubusercontent.com/4033249/53368330-4c548680-38fd-11e9-9c77-f5d775adc9ed.png)

**Comment by usernamehw** [comment]
There's those 2 themables, only they do not have focus/selection foregrounds:

```
list.errorForeground
list.warningForeground
```

**Comment by octref** [comment]
Thanks, the ability to use other colors for foreground when in focus/selection would solve the problem.

**Comment by jrieken** [comment]
Those are `list.errorForeground` and `list.warningForeground`
