### ISSUE TITLE
Thenable does not have a catch method

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#694]
Why?

For instance, the `showQuickPick` method returns a `Thenable`, right? Why isn't it possible to use the normal promise flow? 

```js
vscode.window.showQuickPick(new Promise((c, e) => {
    setTimeout(() => {
        e(new Error("does not work"));
    }, 2000);
})).catch(e => {
    vscode.window.showErrorMessage(e.toString());
});
```

We always have to use the `then` method with 2 arguments which is, if I'm not mistaken, defined as a promise `anti-pattern`.

**Comment by jrieken** [comment]
That's because we use the `Thenable` as the common denominator of promise-wannabes. The VS Code api will accept anything that is like a promise to make it easy to integrate existing code. 

Promises that are _returned_ from the API are WinJS-promises (which btw don't support catch). We didn't declare that in the API since we will likely adopt native promises some time.

**Comment by SamVerschueren** [comment]
If you are going to adopt native promises, why are WinJS-promises used then? Native promises support catch which means the API will change when native promises are being adopted. Isn't it better to use a decent polyfill/ponyfill for now instead of the microsoft implementation?

Just wondering :).

**Comment by jrieken** [comment]
Our project started a little before the general availability of the native promises ;-) Also, the editor widget must still support environments without the native promise.

**Comment by SamVerschueren** [comment]
That's why a ponyfill comes in handy :). It uses the native promises if they are available, if not it will use the polyfill. 

Example: [pinkie-promise](https://github.com/floatdrop/pinkie-promise)

**Comment by jrieken** [comment]
Fully agree - everyone would like to have it but the adoption will be laborious esp that we build on `done` and `cancel` from WinJS...

**Comment by tamj0rd2** [comment]
so how do we catch errors from vscode thenables?

**Comment by SamVerschueren** [comment]
Add a error handler as second argument as explained in the opening post.
