### ISSUE TITLE
Selecting same text's highlights should look a bit different than current selection

### ISSUE THREAD

**Issue by madprops** [Microsoft/vscode#69407]
![code_2019-02-25_14-35-40](https://user-images.githubusercontent.com/206498/53367053-c63f3c80-390a-11e9-98df-8f9165643fd3.jpg)

Say we have something like that. Sometimes it's hard to know what is actually selected unless you check for the cursors, it has happened sometimes.

I suggest that when selecting something, the other text that gets highlighted should have a little less opacity/color, and when they get selected too they change to the regular highlighting color. 

This gives better indication of actual selection, like when using ctrl+d for instance or simply checking where the cursor is.

**Comment by usernamehw** [comment]
Can you repro the same behavior in all themes or only in this particular one? 

If it only reproduces in one theme => file the issue against theme repository.

**Comment by madprops** [comment]
@usernamehw You're right. Using the default dark theme the functionality works as I suggested. Closing this.
