### ISSUE TITLE
Debug server failed to initialized

### ISSUE THREAD

**Issue by YoHidden** [Microsoft/vscode#69405]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by YoHidden** [comment]
* VSCode Version: 1.31.1

* OS Version: MacOS Mojave 10.14.3

Hi there,

I am trying to setup the debug process for an ST NUCLEO board and a project downloaded from mbed. After trying several tools, I have finally come to use the _ST-UTIL_ as debug server for ST-Link V2 device.

If I run it from a terminal window, the _ST-Util_ finds my connected device and starts attending to port 4242. If I then run in another terminal window the _arm-none-eabi-gdb_, it connects immediately to the ST-Util and the debug process can start.

BUT, if I customize the launch.json file to use...

**"MIMode": "gdb",
"MIDebuggerPath": "arm-none-eabi-gdb",
"debugServerPath": "st-util"**

then, the launch process stops at the message...

**1: (248) codeSign-stderr: /Users/Jorge/bin/gcc-arm-none-eabi-8-2018-q4-major/bin/arm-none-eabi-gdb: code object is not signed at all
1: (255) Starting: "st-util" 
1: (5269) <-logout
ERROR: Unable to start debugging. Debug server process failed to initialize.**

and that's it. Debugging is aborted.
However, I've noticed that if I remove the line **"debugServerPath": "st-util"** and starts manually the _st-util_ tool in a terminal window, the launch process is successful and debugging can be done.

I really don't know what else can I do.

Regards.

**Comment by YoHidden** [comment]
Hi @weinand ... can you clarify which extension do you think to be the responsible for this behavior?

Thanks.

**Comment by weinand** [comment]
Since you did not include any useful information about the extensions you are using (e.g. by filing the issue via VS Code's "Report Issue" command), I can only speculate that you are using some "gdb" debugger which hints towards the C/C++ debugger (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools).

**Comment by YoHidden** [comment]
Ok, thanks. I did not know the right way to open an issue from VS Code. Sorry for that.
