### ISSUE TITLE
Clicking on label of list item to expand does not work in Outline

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69408]
Testing #69299:

In explorer, if you click `[Icon] Label`'s Label area, it expands. In Outline it doesn't.

**Comment by usernamehw** [comment]
Isn't it suppose to work this way and expand/collapse only by clicking on twistie?

**Comment by octref** [comment]
@usernamehw Not really, in explorer even if you use an icon set with twistie, clicking on label still expands.

I do think the intention is probably to allow quickly going through top-level symbols. For example, when the list is:

- A
  - 1
  - 2
  - 3...
- B

If A has 50 children then clicking on A to expand would be problematic, because user can't jump to B until he collapse A again.

But I'd argue selection using up/down should focus on the correct range in the editor, if "Outline: Follow Cursor" is turned on.

**Comment by jrieken** [comment]
It is the design of the outline. You need to be able to select a container node, like a class, with it toggling expansion state. The same is done for markers with children, e.g a marker with related locations
