### ISSUE TITLE
Lint showing error under variable name if an extra semicolon

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6940]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open the smoke test repo
2. Open routes/index.js
3. Run build task

![linterrorsemicolon](https://cloud.githubusercontent.com/assets/12900364/15589456/d7bb06e6-2347-11e6-9e15-f1f717d4efde.PNG)

If there is a semicolon error, it will show an error under the variable if it is next to one. If the extra semicolon is next to a bracket, it shows under the semicolon. Shouldn't it always show under the semicolon?

**Comment by dbaeumer** [comment]
We receive the errors from eslint (http://eslint.org/). There is little we can do about that. If you feel strong about it please open an issue in the eslint repository.
