### ISSUE TITLE
Add tree match background theme color

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#69400]
Testing #69299:

I quite like how this used to work:

![image](https://user-images.githubusercontent.com/4033249/53362092-4014fd00-38ee-11e9-856a-527a9be21e00.png)

It's also consistent with IntelliSense:

![image](https://user-images.githubusercontent.com/4033249/53363975-9e43df00-38f2-11e9-8ae1-8f68e086fcc6.png)

The new type to filter experience has some contrast problem, as the bg color of list item leaks into bg color of selection range because of transparency).

![image](https://user-images.githubusercontent.com/4033249/53364492-c1bb5980-38f3-11e9-922a-91bb16fedd2c.png)

@joaomoreno I don't know if we are committed to this visual representation of filtering, but I'd suggest something like this (full height, offer 2 them-able colors for filtering, filterSelection fg/bg). This would make it much easier to maintain contrast.

![image](https://user-images.githubusercontent.com/4033249/53364886-a9980a00-38f4-11e9-86db-d8e9f30bd281.png)

**Comment by joaomoreno** [comment]
@octref This is theme dependent. Type filter even exposes special theme keys for this. Which theme are you using?

**Comment by octref** [comment]
I'm using Nord. Which color key are you using for the match box background on the labels? I guess Nord has it set to a color with transparency.

**Comment by joaomoreno** [comment]
Hmm we're actually reusing `findMatchHighlightColor` for that.

**Comment by octref** [comment]
`"editor.findMatchBackground": "#88c0d066"` is what Nord is using. This is readable against text editor background, but it's not readable on top of tree focus/select bg.

![image](https://user-images.githubusercontent.com/4033249/53455316-e17b7c00-39de-11e9-832c-b81ed1721862.png)

![image](https://user-images.githubusercontent.com/4033249/53455327-ea6c4d80-39de-11e9-854c-2dd1e9a37165.png)

If a tree item is selected and tree is in focus, I can't see the type-to-filter box at all:

![image](https://user-images.githubusercontent.com/4033249/53455376-125bb100-39df-11e9-86dc-1039ff9229e5.png)

**Comment by joaomoreno** [comment]
Then we'll just create that theme color.

**Comment by octref** [comment]
@joaomoreno Thanks! Make sure you update vscode-docs as well.

**Comment by joaomoreno** [comment]
Good call! https://github.com/microsoft/vscode-docs/commit/e92eee50b76b3efb8c8b677b821b5ad0d2eed12f
