### ISSUE TITLE
Vscode Debugger takes time to kick in

### ISSUE THREAD

**Issue by cavalos0086** [Microsoft/vscode#69415]
- VSCode Version: 1.31.1
- OS Version: 10.14.3 (18D109)

Does this issue occur when all extensions are disabled?: YES

# Issue:
Breakpoints are taking a lot of time to start working.
Info: (My configuration uses `docker` with `typescript`. 

# Steps to Reproduce:
1. Setup breakpoint
2. Press F5 to run the debugger. 

# Expected: 
- When the code on the selected line gets execute, the breakpoint should work and stop execution. 

# Actual
Breakpoints don't get hit. To get it to work I have to do EITHER of these 2 things:
1. Wait about 65 seconds for the breakpoints to work.  (Seems like vscode is taking its time to get attached to the port than node exposes? my guess tough I am not familiar with the way it works). 
2. Open chrome browser, click on the icon 'node debugger in chrome', set a breakpoint on the same line I selected before and give the code another run. This will stop on both chrome browser and vscode. 

# Relative Info:
- Folder Structure
  - .vscode
  - package.json
  - src
    - routes
    - services
    ...

 - Launch.json:
```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
      "type": "node",
      "request": "launch",
      "name": "Launch in Docker",
      "preLaunchTask": "tsc-watch",
      "protocol": "auto",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "docker-debug" ],
      "port": 9229,
      "restart": true,
      "timeout": 60000,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/usr/src/app",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    },
	]
}
```

- Tasks.json:
```
{
 "version": "2.0.0",
 "tasks": [
   {
     "label": "tsc-watch",
     "command": "npm",
     "args": [ "run", "watch" ],
     "type": "shell",
     "isBackground": true,
     "group": "build",
     "problemMatcher": "$tsc-watch",
   }
 ]
}
```
- Package.json:
```
{
   "debug": "nodemon --watch ./dist --inspect=0.0.0.0:9229 --nolazy ./dist/bin.js",
    "docker-debug": "docker-compose up",
    "watch": "tsc -w",
    "start": "node dist/bin.js",
}
```
- DockerFile:
```
FROM node:10-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app
RUN npm install
```

- docker-compose.yml
```
version: '2'
...
services:
foo-service:
volumes:
      - ./public:/usr/src/app/public
      - ./dist:/usr/src/app/dist
    ports:
      - 80
      - "9229:9229"
environment:
      NODE_ENV: development
      HOST_PORT: 80
    command: npm run debug
    restart: always
```

**Comment by roblourens** [comment]
What OS are you on? Could you set `"trace": true` in your launch config, run it again, and upload the log from the path that it writes to the debug console? That should help me figure out why it's slow. A similar issue was reported in #69118 but I don't know why it's happening yet.

**Comment by cavalos0086** [comment]
Thanks for the reply @roblourens. Yes, that is exactly the same behaviour I am experiencing. 
My OS is: `MacOS Mojave 10.14.3 (18D109)` and here are the logs:

[debugadapter.txt](https://github.com/Microsoft/vscode/files/2906089/debugadapter.txt)
Let me know if there is anything I could help.

**Comment by roblourens** [comment]
Thanks! This is different than the other issue. Since you have a "launch" config, we run your runtimeExecutable then we wait for node to start and pause on start. We wait for "timeout" ms which in your case is 60s. The log shows that this is what the debugger is waiting for. However in your case the launch task just takes the container up. So I'm guessing at some point the container is already up and your node process is already running and so node will not "pause on start".

I think the best way to fix it is to use an "attach" task instead of a "launch" task. This will just try to attach to an already running node instance. But you could probably still get it to also start the container when it's not running by specifying a `preLaunchTask` and writing a task that takes the container up.

Alternately you could just decrease the "timeout" but then risk it timing out when the container is not actually running before you start debugging.

**Comment by cavalos0086** [comment]
@roblourens Ha! Nice. 
I like your idea of bringing the container up with a `preLaunchTask`, it makes the launch more robust. I also tried reducing the timeout to `1s` and it worked too. My server is very small and I only send the `dist` folder to the container so it doesn't need that much time but I will def try the preLaunchTask. Thanks. 

I will close the issue now.
