### ISSUE TITLE
Disabled kerning in type-to-filter causes tree label to shift

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#69410]
While testing #69299.

Notice the space between T and a:

![image](https://user-images.githubusercontent.com/4033249/53370025-73ad5280-3901-11e9-80ea-2c70b7714fd7.png)

When not using type-to-filter:

![image](https://user-images.githubusercontent.com/4033249/53370049-86278c00-3901-11e9-9462-67718a2ffd7f.png)

This causes the whole tree's labels to shift rightwards in variable amounts when typing, which isn't a pleasant experience.

**Comment by joaomoreno** [comment]
@octref What is your suggestion? To simply disable kerning on all tress?

**Comment by Tyriar** [comment]
The only thing I can think of to work around this is measuring the width of chars H, T, HTML and placing divs behind them, this is awfully complicated though. You could argue that disabling kerning is a good thing as it can make the character easier to read.

**Comment by joaomoreno** [comment]
Wikipedia argues exactly the opposite:

> In typography, kerning is the process of adjusting the spacing between characters in a proportional font, usually to achieve a visually pleasing result.

I really don't see a reasonable solution here besides disabling kerning on lists and trees, creating an inconsistent look or disabling kerning altogether, possibly annoying users the same way the lack of sub-pixel antialiasing does.

**Comment by Tyriar** [comment]
@joaomoreno I'm not arguing for disabling outright, but what's currently happening by separating the word using different spans. I'm pretty sure you could do what Pine is after by having a DOM structure like this:

```html
<li>
  <span>HTMLTag</span>
  <span class="selection" style="position: relative; left: **x**px; color: transparent">T</span>
</li>
```

Where `**x**` is the width of a span containing "HTML". That might be more complex than you're wanting to take this.

**Comment by octref** [comment]
Well, here's a way to measure text width:

```js
const context = document.createElement('canvas').getContext('2d')
// should be true
context.measureText('A').width + context.measureText('V').width > context.measureText('AV').width
```

Maybe you can test to see if you can run these calculations efficiently. I don't think it would be too slow because you are only updating 20-30 ish items shown in the tree's viewport.

**Comment by Tyriar** [comment]
@octref not quite that simple, context would need all font settings correct and in order to guarantee that it should probably be an invisible element inside the tree widget.
