### ISSUE TITLE
[API] Provide Virtual Document in window.visibleEditors or similar

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#6941]
- VSCode Version: 1.1.1-insiders
- OS Version: Win10

I know window.visibleEditors is supposed to contain actual text editors but it is not possible to tell at the moment if a VirtualDocument (ie a htmlContentProvider) is in view.

The scenario I would need this for is for detecting if a Virtual Document has focus when a command is triggered. If there is another work around for this please let me know.

Thanks :smile:

**Comment by jrieken** [comment]
@tht13 You mean the view that shows when running `previewHtml`, right?

**Comment by tht13** [comment]
@jrieken yup that's the one

**Comment by jrieken** [comment]
It's hard... Needs thinking.

**Comment by tht13** [comment]
It is also needed for extracting the markdown extension if full functionality is desired to be retained.
My extensions are very similar to the markdown one, but for previewing RST and HTML files.

An option could be to provide an array called visiblePanels (or similar) which is a superset of visibleEditors
