### ISSUE TITLE
Unable to style the "content" property in scss/less

### ISSUE THREAD

**Issue by benjaminfunk** [Microsoft/vscode#69412]
If i switch the language to scss or less the content property gets "entity.name.tag.css" and the styles from it. Impossible to style the properties and name.tag.

![scss](https://user-images.githubusercontent.com/856290/53370651-96b22380-394e-11e9-8897-531eb0a1e601.png)

**Comment by usernamehw** [comment]
/duplicate of https://github.com/atom/language-sass/issues/226
