### ISSUE TITLE
Indicate code actions with preferred fixes in the problems menu too

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#69418]
**Repo**
1. For the TS code:

```ts
const fooo = 1;
console.log(foo);
```
1. Open problems menu

**Bug**
Notice that the error in the editor uses the lightbulb with the little blue badge that indicates that preferred fixes are available: 

![screen shot 2019-02-25 at 2 28 54 pm](https://user-images.githubusercontent.com/12821956/53373234-b4a96500-3909-11e9-9d2c-646e4477813d.png)

However the one in the problems menu does not:

![screen shot 2019-02-25 at 2 29 16 pm](https://user-images.githubusercontent.com/12821956/53373249-c0952700-3909-11e9-9592-587ea9726714.png)

**Comment by alexr00** [comment]
I see the lightbulb in the editor, but I don't see the lightbulb in the problems panel. I do see the error in the problems panel. How can I make the light bulb show in the problems panel?

**Comment by alexr00** [comment]
Ah. Accidentally figured out that you need to click on it.

**Comment by sandy081** [comment]
It appears also on hover.
