### ISSUE TITLE
Add open a tab in new window

### ISSUE THREAD

**Issue by vdloc** [Microsoft/vscode#69427]
As normally, I've coded with two monitors, so VScode can a feature like right click on a tab and open this tab in a new window so I can move that window to another screen for more convenient working( compare code ...)

**Comment by yume-chan** [comment]
There is a command "File: Open Active File In New Window"

The default shortcut is <kbd>Ctrl</kbd> + <kbd>K</kbd>, <kbd>O</kbd>
