### ISSUE TITLE
Emojis are counted as two character in commit message line lengths 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#69421]
Testing #68894

**Repo**
1. Stage a commit
1. In the commit message, enter 26 emoji

**Bug**
We incorrectly mark the subject line as being too long (over 50 characters) because each emoji is counted as 2+ characters

**Comment by joaomoreno** [comment]
Uff. Are we sure we want to go there? https://mathiasbynens.be/notes/javascript-unicode
