### ISSUE TITLE
Go to definition opening a file from different location from different project.

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#69431]
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Go To Definition is opening a file which is from different project folder instead of current opened project.**

Steps to Reproduce:

1. Opened 2-3 laravel projects in vscode.
2. Deleted one project.
3. Tried to open the definition of a class.
4. Vscode is opening file from **Deleted Project** instead of current opened project.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by jrieken** [comment]
What language/extension is that?

**Comment by iyashpal** [comment]
It's PHP using Laravel Framework
