### ISSUE TITLE
Distribute portable application as npm module

### ISSUE THREAD

**Issue by roman-petrov** [Microsoft/vscode#69430]
I am a fan of one click project build & dev environment setup (hope many people like this too). Nowadays almost everything can be automated but users still have to download & install IDE to develop a project. 

So the idea is to provide portable `VSCode` package as official  `npm` module. In such scenario, when project already contains `package.json` and settings in `.vscode` folder new project contributors would be able to start develop GitHub project by just a couple console of commands like:

```bash
git clone <repo url>
yarn launch
```

which will install `npm` modules (including ` VSCode`) inside, install required `VSCode` extensions and launch VSCode. 

Hope this is not too hard to implement and might be helpful for many other people.

Thanks!

**Comment by joaomoreno** [comment]
Thanks for the idea, though I fear this may be out of scope of our goals. We believe the current distribution packages are more than enough to reach everyone.

**Comment by roman-petrov** [comment]
Thanks, I understand that installing applications via `npm` is not a common scenario...
