### ISSUE TITLE
[shellscript] Indent rule/behavor seems broken

### ISSUE THREAD

**Issue by suzetmk** [microsoft/vscode#69433]
- VSCode Version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
- OS Version: Linux x64 4.15.0 (ubuntu 16.04)

Steps to Reproduce:

Issue 1: if/while/for/case block has no indention rules

1. install new code 1.31.1 using deb package
2. open a shellscript file
3. type new "if" block like "if true; then" and hit return key
4. code doesn't indents (expected: automatically increase one indent)
5. same about while/for/case

Issue 2: auto-indent on move-line and/or paste not works

1. install new code 1.31.1 using deb package
2. open a shellscript file
3. move line across a indented block (such as function) never respects indents (see example below)
4. (same operation to a css/json file indents correctly)
5. (same operation to a c source has same issue)

example:

===
```bash
echo "moving this line into a function"

foo () {
    echo "this is a function block"
    return 0
}
```

===

```bash
foo () {
echo "moving this line into a function"
    echo "this is a function block"
    return 0
}
```

===

This is quite painful for me...

Does this issue occur when all extensions are disabled?: Yes

**Comment by suzetmk** [comment]
Thanks @rebornix for your assignment. Is there any progress?
If you need further information, please feel free to ask me.

**Comment by suzetmk** [comment]
Any progress?

**Comment by rebornix** [comment]
This can be done by a shell script language extension which contributes indentation rules or onEnter rules.
