### ISSUE TITLE
URLHandler channel is not used in renderer?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69438]
There is a 

```ts
electronMainClient.registerChannel('urlHandler', urlHandlerChannel);
```

in the renderer early (main.ts) but I do not see any service that is leveraging this channel? Can it be removed?

**Comment by joaomoreno** [comment]
The [`urlHandlerChannel`](https://github.com/Microsoft/vscode/blob/7d0c9e6fa0bedcf71bdae86c02611b65362795a3/src/vs/workbench/electron-browser/main.ts#L184) is the IPC counterpart to the [`urlService` defined above](https://github.com/Microsoft/vscode/blob/7d0c9e6fa0bedcf71bdae86c02611b65362795a3/src/vs/workbench/electron-browser/main.ts#L180). Services leverage the `urlService`, not the channel.
