### ISSUE TITLE
VS Code flickering even after completely uninstalling and new installation on TS/JS Language server initialization

### ISSUE THREAD

**Issue by rgnrw** [microsoft/vscode#69432]
-Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

Steps to Reproduce:
1. Uninstalled(Deleted from folder) all the extensions and installed latest version.

I deleted all the extensions also.

However does not create issue with disable --gpu.

**Comment by rgnrw** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Terminal is not split (#69273)](https://www.github.com/Microsoft/vscode/issues/69273)
> 
>     * [Go to definition opening a file from different location from different project. (#69431)](https://www.github.com/Microsoft/vscode/issues/69431)

Issue is not related to extensions.

**Comment by sandy081** [comment]
What do you mean by VS Code flickering? Can you please provide a screenshot or a small gif showing it?

**Comment by rgnrw** [comment]
![test-2](https://user-images.githubusercontent.com/11817631/53547385-ea8e5980-3b54-11e9-80d5-cbe58e8882a1.gif)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by rgnrw** [comment]
@bpasero I purged my earlier code and installed linux one provided by you.
It still flickers.
![flickering](https://user-images.githubusercontent.com/11817631/53736822-d6c65880-3eb0-11e9-88e1-f288372f888a.gif)

**Comment by bpasero** [comment]
@rgnrw I guess it does not flicker anymore when you run "code --disable-gpu"?

**Comment by rgnrw** [comment]
@bpasero Yes, it works fine with --disable-gpu.

**Comment by rgnrw** [comment]
Code-exploration updated through linux software updater.

Version: 1.33.0-exploration
Commit: 0c0bd7afe1491bf498db49dee9c411ae8d9bbbc1
Date: 2019-03-05T08:48:48.676Z
Electron: 4.0.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-46-generic

This version is working fine.

**Comment by rgnrw** [comment]
@bpasero  is there anything i can try? 
as both code and code-exploration as flickering with gpu on updated versions.

**Comment by pumpkinlink** [comment]
Having the same issue with Ubuntu 16.04 LTS on Intel HD Graphics 3000 (1st Gen i3), It flickers every time the TS/JS Language server is starting, when the spinning arrows animation plays on the status bar. And also then the text on the terminal changes. Running with --disable-gpu solves the issue.

**Comment by travisdowns** [comment]
I also suffer extensive flickering on Ubuntu 16.04 that goes away with `--disable-gpu`.

**Comment by rickhall** [comment]
Just wanted to say that I am now seeing this exact same flicker under Fedora 30. I'm not sure when it started, but perhaps over the last couple weeks. It didn't previously do this. It is very distracting and annoying. I will try with --disable-gpu and see how that goes.

**Comment by rickhall** [comment]
Just a followup, it does appear that --disable-gpu resolves the flickering.

**Comment by rickhall** [comment]
If this is a duplicate issue, would it be so hard to provide a link to the issue it is duplicating, rather than just closing it and telling us to search for it ourselves?

**Comment by travisdowns** [comment]
Came here to say the same thing. Is "We *figured* it's covering the same as another one we already have" the standard now for closing as a dupe? Is the dupe a secret?

**Comment by rickhall** [comment]
Definition of futility: trying to reason with a bot... ;-)

**Comment by bpasero** [comment]
Forgot to mention the issue: https://github.com/microsoft/vscode/issues/15211

**Comment by travisdowns** [comment]
@rickhall - maybe this is helpful for you:

`--disable-gpu` didn't solve the issue for me. Well the flickering went away, but I had another type of artifact: vertical artifacts appearing near the cursor and other places. I think it was about as annoying as the flickering.

What did seem to work was `code --enable-native-gpu-memory-buffers`.

You can check with `code --status` that it changes the `native_gpu_memory_buffers:     enabled` line from disabled to enabled. After that I have little to no flickering.

**Comment by rickhall** [comment]
Just an FYI, I've upgraded to Fedora 31 recently and am on VS Code 1.39.2 and it appears that I'm no longer experiencing the flicker issue even with no additional flags passed into the editor. So, maybe the issue has been resolved.
