### ISSUE TITLE
Extension viewlet suggests to upgrade extension right after install

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#69436]
This is when there is a newer version on the Marketplace that is not compatible with the current VS Code version:
![image](https://user-images.githubusercontent.com/9205389/53398589-3fda3780-39aa-11e9-98b8-f9f8bf33b603.png)

Reloading the window makes it disappear.

**Comment by sandy081** [comment]
Steps to verify:

- Open Extensions View
- Search for Azure Account extension
- Install it

Make sure it installs 0.8.0V and does not show the update button as above
