### ISSUE TITLE
Peek References: double click no longer takes me to reference

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69439]
Steps to Reproduce:

1. peek references
2. double click on an entry in the tree

=> :bug: you no longer navigate to that reference

Sounds a lot like https://github.com/Microsoft/vscode/issues/69284 which also shows broken double-click behaviour.

//cc @joaomoreno

**Comment by jrieken** [comment]
@joaomoreno It seems that the tree doesn't give me a selection change for the double click but that it does things on single click already
