### ISSUE TITLE
File Picker: cannot "Save As" an existing file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69445]
It looks like I cannot select an existing file to overwrite it when saving as.

**Comment by alexr00** [comment]
Correct, I haven't implemented this yet :)

**Comment by bpasero** [comment]
While this works now I find the UX on it very unexpected:

![image](https://user-images.githubusercontent.com/900690/55006850-b59fe600-4fde-11e9-9d8b-0476523dccaa.png)

Since this was once in the UX discussion I realize we are still on it I guess. @misolori fyi

I think what I would expect here is that I pick the same name after hitting enter and then get another picker that asks me specifically to overwrite and when I say no, it brings me back?

**Comment by misolori** [comment]
I agree that in this case we should show a confirmation picker and selecting `Cancel` would take you back to the file picker.

**Comment by alexr00** [comment]
Cool, I will implement that!
