### ISSUE TITLE
Offer to remove special characters from output from bash when opening

### ISSUE THREAD

**Issue by JerryGreen** [microsoft/vscode#69448]
I want to see terminal output in vscode sometimes, and I have a weird problem. Look at this example:

`man cut` terminal output (everything is ok):

![image](https://user-images.githubusercontent.com/13215662/53412350-f8c06680-39ea-11e9-8f4d-a3444574f9c4.png)

`man cut | code -` output (look, pretty much all the symbols are duplicated or messed up with `_` symbol)

![image](https://user-images.githubusercontent.com/13215662/53412483-489f2d80-39eb-11e9-8393-ad7a2458e376.png)

**Comment by bpasero** [comment]
I see the same when I pipe the output to a  file: `man cut > out.txt` so I think this is not an issue with VSCode.

**Comment by JerryGreen** [comment]
@bpasero yes, I agree that the guilty is not on vscode. Vscode works normally.

If you'll `cat out.txt` then - you'll see a normal output. So it's just a terminal thing - that's right.

And if you'll look into raw characters, for example, try `vi out.txt` (or `man cut | vi -`) - you'll see `^H` character there (which works like a "remove previous character" - not sure why they need it at first place)

So it turns out it's more like a feature request, not a bug request

It could be implemented like a message at bottom right corner, something like:

"Vscode found some unnecessary extra characters. Do you want to remove it?" Yes | No

And then it removes all characters by `.^H` pattern
