### ISSUE TITLE
VSCode API: InputBox.enabled doesn't work

### ISSUE THREAD

**Issue by s-KaiNet** [microsoft/vscode#69441]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create basic extension with `yo code`
2. Add code which shows inputbox and set `enabled=false`: 
```typescript
let input = vscode.window.createInputBox();
input.enabled = false;
input.show();
```
3. VSCode allows input despite `enabled` setting for the input.

**Comment by TylerLeonhardt** [comment]
Closing this with a newer one with more info https://github.com/microsoft/vscode/issues/159906
