### ISSUE TITLE
Bug: Can't escape input box in renaming context

### ISSUE THREAD

**Issue by mizchi** [Microsoft/vscode#69449]
- VSCode Version: 1.32.0-insider
- OS Version: MacOSX

Steps to Reproduce:

1. Double click identifier and enter rename context?

Sorry,  I can't explain 

This movie is all.

![](https://i.gyazo.com/417e3e0983b2354bffb0c25054bb341e.gif)

All input are taken by this input box and focus it. `ESC` does not work.

I will add repro step later if I could find.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Sorry, I do not understand. Please add repo steps
