### ISSUE TITLE
'html' snippet is annoying and easily inserts by accident when typing any html

### ISSUE THREAD

**Issue by coffeymatt** [Microsoft/vscode#69457]
- VSCode Version: 1.31.1
- OS Version: Windows 10 x64 10.0.17763

Steps to Reproduce:

1. Open an html file e.g. from an angular component so not a complete html page
2. in the middle of some html or a paragraph of text, press space so you get an intellisense suggestion.
3. It suggests a 'html' which puts a whole html document snippet in the middle of your code (easy to do by accident when your typing i.e. if you press enter for a new line you suddenly have a bunch of html

I could turn off html5 suggestions but then I'd lose suggestions for properties and values. Maybe this setting could separate out suggestions for tags? Or just not suggest this annoying snippet.

The place it's suggesting it doesn't even make sense:

![image](https://user-images.githubusercontent.com/32092194/53417850-5befd000-39ce-11e9-9a38-19363ed42200.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by coffeymatt** [comment]
Nope, not a duplicate of that thanks bot

**Comment by aeschli** [comment]
That's a general problem with snippets.
At some point we only shed them when at the beginning of the line or when at least some characters where matching.
I believe the only solution we currently have is for you to turn off snippets: `"editor.snippetSuggestions": "none",`

**Comment by aeschli** [comment]
I discussed with @jrieken. Another solution is for the HTML lamguag server to propose the default snippet through the language service. That way we can make sure it is not proposed inside an attribute.

I'll do that.

**Comment by coffeymatt** [comment]
Thanks for the suggestion @aeschli , I'll turn off snippets for now. That change sounds promising. Would it also prevent that snippet if you're typing some text in a <p> tag for example. (e.g. you're typing something and you press enter for a new line and get that snippet instead).

I can only see that snippet being useful in a totally blank html document, and even then, not that useful. Maybe having it is more hassle than it's worth?

**Comment by aeschli** [comment]
The html snippet now only appears at the beginning of the file
