### ISSUE TITLE
Integrated terminal should be able to bring up right click menu anywhere

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6945]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open integrated terminal
2. Right click in the terminal

The only place to bring up the paste option is on the text cursor. I think either right clicking inside terminal should paste (the same as Command Prompt) or be able to bring up that context menu anywhere inside the terminal.

**Comment by Tyriar** [comment]
Basically we defer to whatever xterm does here, there are a few issues in the repo related to this. Closing as designed.
