### ISSUE TITLE
watcherService using all my memory and CPU

### ISSUE THREAD

**Issue by MadeAccountJust4This** [Microsoft/vscode#69453]
- VSCode Version: 1.31.1
- OS Version: macOS Mojave version 10.14.3

Steps to Reproduce:
1. I don't know, I'm completely new to coding and to this program.

Does this issue occur when all extensions are disabled?: Yes, I disabled all extensions from the extensions menu.

I'm completely new to coding and thought I'd start trying to learn python. One of my friends recommended I use VSCode, so I downloaded it and went about trying to do my exercises/problems. However, I noticed that this program is making my computer run extremely slow, even with all the other applications closed. It's really annoying when I'm just trying to write simple code and I get the spinning rainbow wheel of death every 10 seconds for no apparent reason.

So, I looked at some other help pages on this site about similar issues. I didn't find anything that would directly solve the problem, but found out how I can identify the issue using the process explorer. When I opened it up the process called "watcherService" was using over 200% of my CPU (however that works) and almost a quarter of my computers memory (see screenshot attached). I found out how to disable any extensions I had, since most help pages seemed to suggest than an extension is the most likely cause of the program running slow, but nothing changed. Literally the only thing I have open is one .py file with 10 lines of code... Does anyone know what I can do to fix this?

![screen shot 2019-02-26 at 10 33 05 pm](https://user-images.githubusercontent.com/48018415/53413650-40111c00-3a18-11e9-8676-9116c11c4c5d.png)

**Comment by Tyriar** [comment]
@MadeAccountJust4This do you have a large folder open in the explorer? If you run `code --status` in a terminal it should print out some "workspace stats" at the bottom, these would help identify the problem.

**Comment by MadeAccountJust4This** [comment]
I'm not sure what you mean by that. When I type that into the terminal part all I get is "command not found". 
![screen shot 2019-03-02 at 7 25 39 pm](https://user-images.githubusercontent.com/48018415/53680034-12cab380-3d21-11e9-90d7-665275871ffa.png)

**Comment by Tyriar** [comment]
Oh on mac you will need to add `code` to the path using this command (F1) 

<img width="376" alt="screen shot 2019-03-02 at 8 53 25 am" src="https://user-images.githubusercontent.com/2193314/53684929-a91ebb00-3cc8-11e9-9152-42392c2ef988.png">
