### ISSUE TITLE
Stuck when dragging tabs in vscode

### ISSUE THREAD

**Issue by iulo** [Microsoft/vscode#69450]
- Version: 1.31.1 (user setup)
- Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
- Date: 2019-02-12T02:20:54.427Z
- Electron: 3.1.2
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. open vscode 
2. drag open tabs

Does this issue occur when all extensions are disabled?: Yes

demo：
![11](https://user-images.githubusercontent.com/6769037/53412467-6462fd80-3a04-11e9-9cd0-f6e81d3070c1.gif)

may help:
it also stuck when use vscode-insiders now. But a few days ago when I just install vscode-insiders, it work fine. I forget which version when i install.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by iulo** [comment]
@bpasero interesting... ，after I install **exploration** and restart my machine, my stable version of vscode 
working normally now... I will continue to pay attention and feedback to you. :beers:
