### ISSUE TITLE
New explorer: clicking on a file centers it vertically

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#69454]
Steps to Reproduce:

1. have enough elements in the explorer to have a scrollbar
2. click on a file
3. => :bug: the explorer scrolls so that the file is in center

I cannot reproduce in stable. I think this is quite serious, so setting "important".

![peek 2019-02-26 14-37](https://user-images.githubusercontent.com/900690/53416572-1209e880-39d4-11e9-994c-28c5c6ccd95a.gif)

**Comment by isidorn** [comment]
Fixed in latest
