### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Baawa** [Microsoft/vscode#69458]
Issue Type: <b>Bug</b>

When I create a file inside VSCode (e.g. "countries.ts") it doesn't always show up in the editor's file explorer.
I can still view it from terminal and referr to it in the code.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.46GB free)|
|Process Argv|-psn_0_2949840|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
Go|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.0.0
proto|pet|0.0.2
vscode-docker|Pet|0.5.2

</details>

**Comment by Baawa** [comment]
Update: Newly created folders are also hidden.

**Comment by mittalyashu** [comment]
Yes, I have to reload the instance of vscode to see the newly created files and folder.

Another problem is that after selecting the folder in which I want to create a new folder or file and then press `a` _(shortcut key to create new file)_, it shows the input _(to create new file)_ in some other directory.

**Comment by Baawa** [comment]
Yup, reloading manually works for me as well. Probably some issue with hot loading then?

**Comment by isidorn** [comment]
Fixed in latest insiders.
