### ISSUE TITLE
Terminal not displaying which branch is open

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#69465]
Issue Type: <b>Bug</b>

When I open the Terminal, "Windows Powershell Copyright (C) Microsoft Corporation. All rights reserved." is all that visually appears.  Furthermore, the cursor is several lines down from there.  When I type a Git command I can see the command typing and the result of the command.  Previous to this last update, everything worked fine and I could see what branch I am working with prior to running a command.

![vscodeinsider_terminal1](https://user-images.githubusercontent.com/6462859/53429265-e6760680-39b1-11e9-88b6-3ed778d57850.jpg)
![vscodeinsider_terminal2](https://user-images.githubusercontent.com/6462859/53429264-e6760680-39b1-11e9-808d-0d03679102a2.jpg)

VS Code version: Code - Insiders 1.32.0-insider (7d0c9e6fa0bedcf71bdae86c02611b65362795a3, 2019-02-26T06:19:00.351Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.73GB (6.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.9
classic-asp-html|jtj|0.1.0
vs-color-picker|lih|1.0.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-icons|rob|8.2.0
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
