### ISSUE TITLE
One Code.exe process taking a full CPU load

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#69461]
sometimes, I have a process code.exe which is taking one of my CPU completely.

when doing code --status: it si reporting 0% usage (tried several times):
```
code --status


Version:          Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)
Memory (System):  15.63GB (4.82GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       95    6832  code main
    0       69    6216     shared-process
    0      139    9388     window (Welcome - wsdl2rest - Visual Studio Code)
    0       12    6848       watcherService
    0        5   13448         console-window-host (Windows internal process)
    0       24   10644       extensionHost
    0       65   11944     gpu-process
Workspace Stats:
|  Window (Welcome - wsdl2rest - Visual Studio Code)
|    Folder (wsdl2rest): 1 files
|      File types: properties(1)
|      Conf files:
```

When using Process Explorer, we can notice that there are several Code.exe process. One of them is taking the CPU cycles:
![image](https://user-images.githubusercontent.com/1105127/53425525-76817380-39e5-11e9-8f15-14ca77bada31.png)

this one was launched this way:
"C:\Users\Aurelien Pupier\AppData\Local\Programs\Microsoft VS Code\Code.exe" --type=renderer --no-sandbox --enable-features=FixAltGraph --disable-features=ColorCorrectRendering --service-pipe-token=XXXXXXXXXXX--lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Users\Aurelien Pupier\AppData\Local\Programs\Microsoft VS Code\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#ffffff --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=XXXXXXXXXX--renderer-client-id=12 --mojo-platform-channel-handle=4540 /prefetch:1

- VSCode Version: 1.31.0
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/1105127/53425230-ecd1a600-39e4-11e9-8c40-06ec332dc43a.png)

Steps to Reproduce:

1. I don't know. I noticed several times that CPU was taken by code.exe
2.

Does this issue occur when all extensions are disabled?: Yes/No
I have not reproduced with --disable-extensions but as i don't know how to reproduce we can't be sure.

**Comment by apupier** [comment]
I killed my running VS Code instance and this Code.exe process is now running alone, still taking the CPU cycles.

**Comment by fbricon** [comment]
could it be a leftover process after running some ITs from CLI?

**Comment by rebornix** [comment]
@apupier can you follow our wiki 
https://github.com/Microsoft/vscode/wiki/Performance-Issues to help troubleshoot?

**Comment by apupier** [comment]
> could it be a leftover process after running some ITs from CLI?

No, I have not launched any Integration Tests from CLI since I rebooted my PC.

**Comment by apupier** [comment]
> @apupier can you follow our wiki
> https://github.com/Microsoft/vscode/wiki/Performance-Issues to help troubleshoot?

if I reproduce I will try to follow it more closely but at first sight I checked most of what is indicated inside already.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by apupier** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I'm currently not able to reproduce with the stable version. I have not found the steps to reproduce.

**Comment by nonubik** [comment]
I have the same issue, it is not related to untracked git files or vs code freeze. 
VS code is responsive, just that one process takes up an entire core (luckily I have 11 more).

"C:\Program Files\Microsoft VS Code\Code.exe" --type=renderer --no-sandbox --enable-features=FixAltGraph --service-pipe-token=8B3D088152907C3944144446237824CC --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Program Files\Microsoft VS Code\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#ffffff --device-scale-factor=1.25 --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=8B3D088152907C3944144446237824CC --renderer-client-id=4 --mojo-platform-channel-handle=2032 /prefetch:1
![vscode-process explorer 1](https://user-images.githubusercontent.com/49485422/55882686-3d701d80-5ba5-11e9-8a0e-2a544196af2d.png)
![vscode-process explorer 2](https://user-images.githubusercontent.com/49485422/55882776-5d074600-5ba5-11e9-878f-42546a148dc7.png)
