### ISSUE TITLE
Mouse pointer should not go away from editor when user perform action on error\info pop-up or debug action widget.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6946]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows

I am not certain if this is due to technical limitation or real issue but some time feel annoying.

With the current application behavior whenever user click on any dynamic control like error or info pp-up or "Debug action widget" then mouse pointer is not set back to original position on editor from where user left the control. 
If you compare the behavior with visual studio where after terminating the debug session mouse pointer set back to proper position (Line number).

Consider the scenario where user working in portrait mode to cover most of the screen portion with editor then it is annoying to find out the pointer location each time after clicking on the pop-up (error\info\debug)

![mousepointerissuenew](https://cloud.githubusercontent.com/assets/17735796/15592597/dd9cd550-2359-11e6-8a8f-9330e39eeef6.gif)

**Comment by isidorn** [comment]
There was an issue that clicking step / continue would not move focus to the editor - this commit fixes that.
Clicking on the stop aciton still does not bring focus to the editor - which I believe is fine for now. If more users ask for this we can improve on that.
