### ISSUE TITLE
Editor background ist too bright

### ISSUE THREAD

**Issue by scorp84** [Microsoft/vscode#69466]
Issue Type: <b>Bug</b>

The color of my editor area seems way too bright. If I compare it to the screenshots of the themes, it's a huge different. 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
open-in-sketch|dav|2.1.0
vscode-great-icons|emm|2.1.46
file-icons|fil|1.0.16
html-slim-scss-css-class-completion|gen|1.5.12
beautify|Hoo|1.4.9
ionic-preview|ion|0.0.18
easy-icons|jam|0.3.1
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|1.0.0
theme-monokai-pro-vscode|mon|1.1.10
vscode-language-pack-de|MS-|1.31.4
atom-keybindings|ms-|3.0.6
node-debug2|ms-|1.31.6
material-icon-theme|PKi|3.6.3
LiveServer|rit|5.5.1
vscode-icons|rob|8.2.0
ayu|tea|0.18.0
bootstrap4-vscode|the|6.0.3
vscode-todo-highlight|way|1.0.4
city-lights-icon-vsc|Yum|1.1.3

(16 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@scorp84 it can help if you share screenshots and the theme you are using to help troubleshoot.
