### ISSUE TITLE
Extremely slow hyperclick on a mixed JS/TS project

### ISSUE THREAD

**Issue by verydanny** [Microsoft/vscode#69469]
I like to jump around my project quickly with hyperclick, but it's extremely slow if using JS/TS and clicking on relative paths. My guess is that when `baseUrl` is configured in `tsconfig.json` that it really confuses/slows down tsserver and causes slowdowns. In general hyperclick seems to be extremely slow on a mixed project (we're in the process of migrating).

Example:

```js
import { App } from 'apps/small/App'
import fooBar from './fooBar'
import bazBar from './bazBar'
```

I have `"allowJs": false` and `"checkJs": false` so the `apps/small/App` path doesn't hyperclick like expected, but the relative paths `./fooBar` and `./bazBar` take FOREVER to navigate to. I see the pending bar animation forever before it finally gets there. Also my CPU usage skyrockets to 100-150%.

- VSCode Version: Version 1.32.0-insider
- OS Version: OS X Mojave

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share a small example project that demonstrates this issue

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this. The example in the comment does not provide enough context of the project structure or what the tsconfig/jsconfig contains
