### ISSUE TITLE
"Rename" contextual menu item in French is not capitalized

### ISSUE THREAD

**Issue by foucdeg** [microsoft/vscode#69463]
- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Open VSCode on a directory with existing files
2. Set interface language to French
3. In the file browser, right-click a file or directory.

Expected behaviour: the renaming option is called "Renommer"
Actual behaviour: the renaming option is called "renommer" (all other menu options are capitalized)

Does this issue occur when all extensions are disabled?: Yes

**Comment by lukaschal** [comment]
Corrected in a previous version of VS Code LP.
