### ISSUE TITLE
MD editor jumps up and down

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#69467]
* 7d0c9e6fa0bedcf71bdae86c02611b65362795a3
* open markdown file
* open preview with sync'd scrolling
* type at the bottom of the page
* :bug: the editor in which you type scrolls up and down

![feb-26-2019 17-39-33](https://user-images.githubusercontent.com/1794099/53429834-a46ab600-39ed-11e9-8d2b-b89d63dc13eb.gif)

**Comment by joemaller** [comment]
This was driving me crazy. As a workaround, you can set `"markdown.preview.scrollEditorWithPreview": false` or uncheck it in visual preferences.

![2019-03-21 at 3 20 PM](https://user-images.githubusercontent.com/8320/54779300-37fa6580-4bed-11e9-8771-c707a41a8004.png)

**Comment by moshebs** [comment]
+1

**Comment by flamanta** [comment]
> This was driving me crazy. As a workaround, you can set `"markdown.preview.scrollEditorWithPreview": false` or uncheck it in visual preferences.
> 
> ![2019-03-21 at 3 20 PM](https://user-images.githubusercontent.com/8320/54779300-37fa6580-4bed-11e9-8771-c707a41a8004.png)

Can confirm this workaround works.

It fixed my issue of the Markdown editor and the Preview window jumping up and down.

**Comment by mjbvz** [comment]
@jrieken Let me know if you still are seeing this. I tested it in our docs repo but don't see it happening
