### ISSUE TITLE
VSCode still asks for php executable even though I set it

### ISSUE THREAD

**Issue by koishy** [Microsoft/vscode#69479]
- VSCode Version: 1.31.1
- OS Version: Linux mint 19.1

Steps to Reproduce:

1. Download php intellisense extension 
2. Install php on your Linux machine
3. Add `"php.executablePath": "/usr/bin/php"` into `settings.json`

After this error still appears, does it mean that this plugin doesn't work with Linux?

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
Sounds like this is from the PHP Intellisense extension, please file the issue on their repo.
