### ISSUE TITLE
Resize/maximize does not work when running over X from Linux to Windows

### ISSUE THREAD

**Issue by shady-of-sweden** [Microsoft/vscode#69474]
Code 1.30.2 on Linux

I run MobaXTerm (10.9) on Windows 10 
Just start the $ code .

used to work like a charm ... but now i can NOT resize the Application window at all.
it can however be minimized.

**Comment by sbatten** [comment]
please see https://code.visualstudio.com/docs/setup/linux#_cannot-move-or-resize-the-window-while-x-forwarding-a-remote-window
