### ISSUE TITLE
Slack invite links expired

### ISSUE THREAD

**Issue by RussellSprouts** [Microsoft/vscode#69477]
- VSCode Version: N/A
- OS Version: N/A

The invite link for the vscode dev community on Slack has expired. (https://aka.ms/vscode-dev-community).

Steps to Reproduce:

1. Visit https://aka.ms/vscode-dev-community
2. See
> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by auchenberg** [comment]
Slack invitation link has been updated, https://aka.ms/vscode-dev-community
