### ISSUE TITLE
Powershell terminal breaks after remote desktop

### ISSUE THREAD

**Issue by iablaauw-MS** [microsoft/vscode#69475]
Issue Type: <b>Bug</b>

1. Have a VSCode window open with a powershell terminal visible.
2. On a different computer, remote desktop into the first computer
3. Everything looks fine
4. Quit the remote desktop, and go back to the original computer.
5. The powershell terminal is completely blank. Typing commands into it seems to work (the cursor moves around), but no text appears. The only thing that fixes it is restarting VSCode.

In case it matters, my original machine had 2 monitors, and the second machine had only 1.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18320

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|31.92GB (10.17GB free)|
|Process Argv|H:\os\src\onecoreuap\windows\dwm\dwmcore|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|1.1.190220004
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0

</details>

**Comment by buybackoff** [comment]
Having the same behavior and it's very annoying to work with a complex folder structure when I have multiple terminals `cd`ed into different subfolders. Have to close and reopen all of them on every reconnect.
