### ISSUE TITLE
Read only files are not properly marked in the editor

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#69476]
Issue Type: <b>Bug</b>

I've got a file set to Read only but am not seeing this properly marked in the editor like #53022. Did this change?

![image](https://user-images.githubusercontent.com/35271042/53437284-fbeb3080-39b1-11e9-9ee4-d9c6309af9c2.png)

![image](https://user-images.githubusercontent.com/35271042/53437296-00afe480-39b2-11e9-92ba-73b8555c32fc.png)

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:14:19.935Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.11.0
vscode-svgo|ajh|0.1.0
gitlens|eam|9.5.1
svgpreview|kis|0.2.0
python|ms-|2019.1.0

(6 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
The issue is probably that the file system provider does not mark the item as read only resulting in us not showing it as readonly in the explorer.

**Comment by gjsjohnmurray** [comment]
@isidorn - How does a file system provider mark an individual item as read only? I've been searching for this ability. I know that an extension implementing a FileSystemProvider can set ```isReadonly: true``` when it registers, thanks to #52330 (see also #51585). But what you wrote above implies it can decide on a per-file basis whether to make a file readonly or not.

**Comment by isidorn** [comment]
@gjsjohnmurray I was not correct in my comment from above. A FileSystemProvider can not mark a single item as readonly. It is a you say that it can only mark isReadonly when it registers.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/69651
