### ISSUE TITLE
Text buttons showing up in some places

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#69478]
- Building from source:

![image](https://user-images.githubusercontent.com/323878/53440143-b2eaaa80-39b8-11e9-91ac-9cb52af3a3fe.png)

**Comment by RMacfarlane** [comment]
Is that only for the debug toolbar? Looks like a dup of https://github.com/Microsoft/vscode/issues/69395

**Comment by roblourens** [comment]
"Find all references" is in the editor. Also I don't have anything that should be contributing those commands to the debug widget? Where would that come from?

**Comment by roblourens** [comment]
This went away after running yarn and restarting my watch task so something just got weird in my repo
