### ISSUE TITLE
what happened to the usersettings json format?

### ISSUE THREAD

**Issue by kiranjulapalli** [Microsoft/vscode#69471]
ctrl+shift+p userjson shows the user settins UI view.. 

Issue Type: <b>Bug</b>

User settings used to have an option to edit in json. Can't see this anymore and this is frustrating.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz (16 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (20.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.15.0
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.0
mssql|ms-|1.4.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.2
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-node-azure-pack|ms-|0.0.5
vsliveshare|ms-|0.3.1225
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.11.2
vscode-docker|Pet|0.5.2
vscode-icons|rob|8.2.0
azure-iot-toolkit|vsc|2.3.0

</details>

**Comment by roblourens** [comment]
It's still there for settings that can't be edited in the GUI. What setting are you missing it for?

**Comment by kiranjulapalli** [comment]
I wanted to change my default command from powershell to windows command as I have a configured environment. It used to be easy to find it in json. UI is bad.. In general why was the option to edit json removed?

**Comment by Gama11** [comment]
It wasn't, there is a button in the upper right to switch:

![](https://i.imgur.com/v3cj16U.png)

I just have this setting to permanently switch to the JSON editor:

```json
"workbench.settings.editor": "json"
```

**Comment by kiranjulapalli** [comment]
t only shows the modified settings. Previously, it used to show available settings on left and modified on right. That was much nicer to have a context on left.

**Comment by kiranjulapalli** [comment]
Here is where we show it in the docs.. https://vscode.readthedocs.io/en/latest/getstarted/settings/

![image](https://az754404.vo.msecnd.net/public/default-settings.gif)

**Comment by Gama11** [comment]
See https://github.com/Microsoft/vscode/issues/68119.

**Comment by kiranjulapalli** [comment]
Ah, thanks. This can be dup'ed to #68119
