### ISSUE TITLE
Unable to rename root level file in file explorer, stuck in bad state

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#69486]
Issue Type: <b>Bug</b>

Select a file in the file explorer that's at the root level of the explorer and choose `Rename` from the context menu or use the hotkey to rename. The input for rename is not shown, the tree appears disabled, and typing enters text into a red input at the top of the tree. Hitting enter or escape does not change the tree state, I was only able to get out of it by reloading:

![rename_root](https://user-images.githubusercontent.com/3672607/53454623-a2e4c200-39dc-11e9-8d6e-cd9cf3772837.gif)

VS Code version: Code - Insiders 1.32.0-insider (2e173fabe821d06a60f532b90d6e5d95c0e09a9c, 2019-02-26T20:21:55.610Z)
OS version: Darwin x64 18.2.0

**Comment by RMacfarlane** [comment]
Looks related to https://github.com/Microsoft/vscode/issues/69468

**Comment by joaomoreno** [comment]
Yup, definitely same as #69468
