### ISSUE TITLE
Breadcrumbs broken

### ISSUE THREAD

**Issue by ekkis** [Microsoft/vscode#69484]
- VSCode Version: 1.31.1
- OS Version: OSX 10.14.3

Problem:

I have made sure that Breadcrumbs is turned on and the path appears at the top of the tabs as it should, however, clicking on any part of it does not bring down a window (it works only for files) and I find no way of navigating it.  I have watched videos of others that show what is supposed to happen but for me, no window

Steps to Reproduce:

1. press cmd-opt-.

Does this issue occur when all extensions are disabled?: Yes/No

no idea how to launch VSCode from the command line

**Comment by jrieken** [comment]
Works for me and the provided information doesn't allow me to reproduce. How have you turned breadcrumbs on, what are you trying to click on in what file?

**Comment by ekkis** [comment]
View/Toggle Breadcrumbs has a checkmark next to it.  poor choice of UI, incidentally. 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/274980/53507812-6b722600-3a6d-11e9-8b4b-101c9f3ffe03.png">
from the image above you can see a path.  clicking on "gasPrice", "send", "unknown" or "self", or the little triangles between them does not display any kind of window.  if I click on "eth.js", which is a file I see:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/274980/53508366-737e9580-3a6e-11e9-93f4-f4b79e4c2e1e.png">

but as you can see, there should be right-pointing triangles (as per my understanding) next to the files so I can navigate their contents, but there arent'

**Comment by jrieken** [comment]
> there should be right-pointing triangles (as per my understanding) next to the files so I can navigate their contents, but there arent

Inside the picker? No, you just select the file and it's being opened. We don't show nested symbols in the picker. You must open the file first.

**Comment by ekkis** [comment]
I've seen videos of people demonstrating the navigation capabilities of breadcrumbs.  my app doesn't do that and as it is, it's pretty worthless

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
