### ISSUE TITLE
VS Code sometimes steals focus after I start debugging Chrome

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#69483]
- Run "Launch VS Code" launch config
- code-oss opens and is focused
- Wait a couple seconds
- The original vscode window becomes focused

I keep seeing this when debugging vscode. It doesn't happen every time. If I immediately start debugging again after seeing this then it never happens again right away. 

I don't know why it would happen, can you check whether you can repro @isidorn? Do you have any ideas? Can you point me to the code that causes vscode to take focus when it hits a breakpoint so I can see how that actually works and look for clues?

**Comment by isidorn** [comment]
I can not repro, I tried 5 times and the focus is always in the new window as it should.
Of course, here's a code pointer (it only happens on stop event) https://github.com/Microsoft/vscode/blob/760f44b96f889a86568d65116c2e5f43760c7021/src/vs/workbench/contrib/debug/electron-browser/debugSession.ts#L628

Let me know if you need more help.

**Comment by isidorn** [comment]
Closing since no more info is provided. @roblourens feel free to reopen if you hit this and get more info

**Comment by roblourens** [comment]
Yeah I've tried but haven't really been able to capture it happening
