### ISSUE TITLE
connect to server has been closed 

### ISSUE THREAD

**Issue by StarPrecursor** [Microsoft/vscode#69481]
We have written the needed data into your clipboard 
Issue Type: <b>Performance Issue</b>

Error: connect to the server has been closed

this error shows up recently whenever I open VSCode. Then I can't find the definition, reference and so on.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (1.22GB free)|
|Process Argv|C:\Users\yz622\DOCUME~1\MobaXterm\slash\RemoteFiles\330884_2_1\FindT0.cxx|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	 28832	code main
    0	    64	 23728	   window (Issue Reporter)
    0	   153	 26944	   window (FindT0.cxx - Visual Studio Code)
    0	    13	 18824	     electron-crash-reporter
    0	    72	 25896	     extensionHost
    1	   153	 29468	   gpu-process
    0	    64	 30460	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-add-brackets|ali|0.7.0
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.27
c-cpp-compile-run|dan|0.4.3
extlibraries|dan|0.0.3
code-runner|for|0.9.7
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-icons|rob|8.2.0

(1 theme extensions excluded)

</details>
because it was too large to send. Please paste.

**Comment by rebornix** [comment]
Can you try if you still see the problem when disabling all extensions?

**Comment by StarPrecursor** [comment]
Hi,

Thank you for your quick response!

If I disable all extensions, the problem disappears.
But when I enable C/C++ extension(which I use very often), it works fine at
the beginning but, after a few seconds, it's broken and shows:

[Error - 8:22:39 PM] Connection to server got closed. Server will not be
restarted.
[Error - 8:22:39 PM] Request textDocument/hover failed.
Error: Connection got disposed.
  at Object.dispose
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
  at Object.dispose
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:71:35)
  at LanguageClient.handleConnectionClosed
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2150:42)
  at LanguageClient.handleConnectionClosed
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\main.js:150:15)
  at closeHandler
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-languageclient\lib\client.js:2137:18)
  at CallbackList.invoke
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
  at Emitter.fire
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
  at closeHandler
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
  at CallbackList.invoke
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
  at Emitter.fire
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
  at StreamMessageReader.fireClose
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
  at Socket.listen.readable.on
(c:\Users\yz622\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
  at Socket.emit (events.js:187:15)
  at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)

Best,

**Comment by rebornix** [comment]
Thanks! Please file issue against the C# extension you are using.
