### ISSUE TITLE
Font is bold in VS compared to ATOM

### ISSUE THREAD

**Issue by timothymarois** [Microsoft/vscode#69485]
I really want to switch to VS but because of this font issue, I can't stand looking at the bold font. I have tried all the fonts available and I have had no luck. If I use the exact font and size in Atom Editor, the font is crisp and clean. 

Using: `Menlo, Consolas, DejaVu Sans Mono, monospace` on both, font-size 12 or 13.

**I have tried font-weight and it does nothing aside from bold or normal.** 

Both are using the One Dark Theme

VS Code:
![screenshot 2019-02-26 18 08 05](https://user-images.githubusercontent.com/2489333/53453398-f7466c80-39f1-11e9-88b4-02e30b1e8c80.png)

VS Code (PHP):
![screenshot 2019-02-26 18 17 41](https://user-images.githubusercontent.com/2489333/53453674-d0d50100-39f2-11e9-9b96-1cf5139e529f.png)

Atom Editor: (PHP)
![screenshot 2019-02-26 18 08 30](https://user-images.githubusercontent.com/2489333/53453403-fd3c4d80-39f1-11e9-88ff-95388581cbf3.png)

How can I replicate what I have running within Atom?

**Comment by karevn** [comment]
You should probably play with font antialiasing settings.

**Comment by timothymarois** [comment]
> You should probably play with font antialiasing settings.

Where would I find that setting? I know both VSC and Atom are using Electron, so I would assume engine-wise they are similar in rendering.

**Comment by karevn** [comment]
They say there's a search feature at the settings screen...

**Comment by timothymarois** [comment]
@karevn 

> They say there's a search feature at the settings screen...

Yeah that was the first thing I checked, It found no settings with anything relating to font antialiasing

**Comment by timothymarois** [comment]
So I found a somewhat workaround thanks to this [gist](https://gist.github.com/hanksudo/33ddf24f27f403c00b746b6f12bde746)

adding in css under the main `workbench.main.css`

```css
 .editor-container {
     -webkit-font-smoothing: antialiased;
 }
```
I don't really like to "rig" this feature in, so I am wondering if there is a better solution here, after doing this, VS gives me a notification, its more of just a warning. 

![screenshot 2019-02-27 14 46 54](https://user-images.githubusercontent.com/2489333/53518362-de47c500-3a9e-11e9-8fb5-4647ef8e8953.png)

The code is a lot thinner now, which is easier to read. Its just dimmed or more transparent. 

![screenshot 2019-02-27 14 50 11](https://user-images.githubusercontent.com/2489333/53518447-0d5e3680-3a9f-11e9-8047-b993febac03b.png)

I am also using **MacOS** to be clear since Apple has recently changed this setting due to retina screens.
