### ISSUE TITLE
Bulk file change event API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#69489]
**Problem**
I'm working with the TS team to optimize the TS Server's performance when many files are changed at the same time: https://github.com/Microsoft/TypeScript/issues/29598 An example of this is when a common string is replaced in multiple files or during a git branch switch.

As part of this work, the js/ts extension will need to construct an array of all file changes that occurred. As far as I can tell, this will require writing a custom throttler/delayer that uses `onDidChangeTextDocument` to group file change events into batches. 

**Question**
It seems to me that other extensions could also benefit from a VS Code api that exposes files changes in batches instead of individually, something like:

```ts
export const onDidChangeTextDocuments: Event<ReadonlyArray<TextDocumentChangeEvent>>;
```

This would be helpful for any extension where a file change can trigger an expensive operation, as is the case with TypeScript and our project-wide IntelliSense. Using the bulk change event, the extension or language server could easily ensure that the expensive operation is applied once per batch instead of once per file.

A bulk change api could also make it easier for an extension/language server to ensure its model of the workspace is in a valid state (for example, if a rename touches five files, TypeScript currently tries running code analysis after having only applied the first file change out of the total)

**Comment by jrieken** [comment]
Our answer to that has been that we should make the event utils available as standalone module instead of adding (bloating?) the API with these things. Apart from growth it's also hard to understand what the event represents, not many people understand that events are debounced/delayed

**Comment by alexandrudima** [comment]
Even if logically, renaming a variable across files or switching to a new git branch appears to an end user like an atomic operation, that is not the story at the level of the filesystem.

If such an operation touches 10 files, it is very likely that one by one the files will be changed on disk, with some delay in between the changes.

I think our API where we emit one event per file change is good, as it reflects how the underlying filesystem works in general. 

It is definitely a good idea to debounce those events for 10-20ms in hope of reaching a discrete state (i.e. when all 10 files are changed), but I think this should be done in the extension itself.

**Comment by mjbvz** [comment]
Good points. I guess the question is then: do we want to standardize the debouncing or leave it up to each extension? And would the language server or extension protocol benefit from batch change events instead of individual events?

For find/replace, since we don't touch the files on disk I believe we could surface it to extensions as an atomic operation. For git checkout or save all, you are correct that it is not atomic since it is dealing with the file system

**Comment by jrieken** [comment]
Closing as we don't plan API/code changes. It's still up to everyone to extract/copy `event.ts` to a node-module
