### ISSUE TITLE
Maximum call stack size exceeded is thrown when running Tasks: Configure Task

### ISSUE THREAD

**Issue by lcampos** [Microsoft/vscode#69497]
- VSCode Version: 1.32.0-insider 2e173fabe821d06a60f532b90d6e5d95c0e09a9c
- OS Version: macOS High Sierra (10.13.6) & Windows 10

Steps to Reproduce:

1. Clone https://github.com/forcedotcom/salesforcedx-vscode
2. Open it on vscode
3. Run `Tasks: Configure Task` from the command palette
4. No quick pick options get rendered. If you open Developer Tools you'll see `Maximum call stack size exceeded` error.

![screen shot 2019-02-26 at 7 26 55 pm](https://user-images.githubusercontent.com/1041842/53464319-a5581380-39fe-11e9-9eaa-76849ed33403.png)

Does this issue occur when all extensions are disabled?: Yes

I'm also running into this error when I try to use a launch configuration (`launch.json` in the same repo) that has a `preLaunchTask`.
I do not run into this issue when I use the same project on vscode 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60).

**Comment by alexr00** [comment]
Cannot reproduce in Ubuntu 18 or by copying the tasks.json. I'll test in Windows next.

**Comment by alexr00** [comment]
Do you have any additional repro steps? I tried with the insiders build on a Windows 10 VM and I couldn't reproduce it.

**Comment by lcampos** [comment]
@alexr00 let me see if I can isolate the issue a bit more. I did try just creating an empty project with the same `tasks.json` file but that wasn't enough.

**Comment by lcampos** [comment]
I think I understand why this is happening in our repo (linked in the description). We have a mono-repo in which several packages are related among each other. When we compile/build the mono-repo, we use lerna to compile and symlink local package dependencies. Somehow that is causing the vscode tasks code to eventually throwing a `Maximum call stack size exceeded` error.

I'm guessing something in the task parsing code changed since I can't replicate this behavior in the stable vscode version.

**Comment by alexr00** [comment]
Are there some simple steps for building the repo somewhere? Alternatively, if you make a smaller repo that also has this problem I can take a look at that.

**Comment by lcampos** [comment]
I was working on a simple repo for this but noticed that on version `1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0)` and above (currently `1.33.0-insider 9b849d9de7168eb4f685823bf9b9e27a0a8dae74`) this issue has been addressed. I'm going to close this now, I'm not sure what change fixed this but thanks for looking into it @alexr00
