### ISSUE TITLE
[json] whole file is marked as error

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#69493]
- Follow the steps in https://github.com/Microsoft/vscode/issues/69091#issuecomment-466217415
- Hover the error that appears at 0,0 in an open file
- The whole file is highlighted and the hover widget is far away, and I can't get to it with my cursor to interact with it. It hides when my cursor leaves the underline at 0,0. A problem with a 0-length diagnostic?

![image](https://user-images.githubusercontent.com/323878/53457563-ae89b600-39e7-11e9-99ba-91e1284ddbd9.png)

**Comment by sandy081** [comment]
Can repro it (also occurs on Stable)

**Comment by sandy081** [comment]
@alexandrudima Assigning to you as I think the editor controls where to show the hover.

**Comment by alexandrudima** [comment]
@aeschli This is another case where JSON returns the entire file as a hover range.

**Comment by aeschli** [comment]
@roblourens Can you provide the JSON content?

**Comment by alexandrudima** [comment]
Duplicate of #69238
