### ISSUE TITLE
Enhancement to File/Folder search in explorer

### ISSUE THREAD

**Issue by sandipchitale** [Microsoft/vscode#69494]
I would like to suggest an enhancement to the feature: https://github.com/Microsoft/vscode/issues/10026

When I type start of a file/folder name when an item in Explorer is selected it starts matching and scrolling to the first matching item. Well an good. However if there are more than one matching file/folder with same prefix I cannot go to it. One way to handle this could be, if the user types every next char fast enough then do the match. However if the user has typed some chars and then **slowly**  (say 1 second delay) types the same last char, do not append the char to match string but match the next match.

So for example with folder structure:

```
parent
  child 1
  child 2
  other
  another
  child 3
```

and with parent selected and I type

```c``` it matches **child 1**

1 sec delay and type ```c``` again, move the selection to **child 2**

and again

1 sec delay and type ```c``` again, move the selection to **child 3**

(I gues once the user enters this mode, do not even need 1 sec delay between types)

BTW WIndows explorer works like this I think.

**Comment by joaomoreno** [comment]
You might want to switch "workbench.list.keyboardNavigation" to "simple".

**Comment by sandipchitale** [comment]
Thanks. That works!
