### ISSUE TITLE
Command with no icon causes problem debug/toolbar menu contribution

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69491]
Found this while verifying #69340:

For such as contribution:

```json
{
  "contributes": {
    "commands": [
      {
        "command": "extension.helloWorld",
        "title": "Hello World"
      }
    ],
    "menus": {
      "debug/toolbar": [
        {
          "command": "extension.helloWorld",
          "when": "debugType == chrome"
        }
      ]
    }
  }
}
```

Here's the display:

![image](https://user-images.githubusercontent.com/4033249/53456636-f7d80680-39e3-11e9-8fa3-bb36f5680f89.png)

I suggest showing a warning notification and not display the broken icon in this case (similar to how you handle menu contribution with no corresponding command).

**Comment by isidorn** [comment]
Dup of #69395
