### ISSUE TITLE
Allow to change the font size individually

### ISSUE THREAD

**Issue by NDelt** [Microsoft/vscode#69499]
![twofonts](https://user-images.githubusercontent.com/46282492/53466037-97a09d80-3a93-11e9-8d8f-79faf38fd0bd.png)
I'm using main English font(Hack) and secondary CJK font(D2Coding) in VS Code. But CJK font is bigger than main font a little bit so I want to adjust the size of secondary font only.

Please allow to change font size separately.

**Comment by rebornix** [comment]
Duplicate of #519
