### ISSUE TITLE
File search function is abnormal

### ISSUE THREAD

**Issue by popring** [Microsoft/vscode#69496]
Issue Type: <b>Bug</b>

It seems that every search can only find open files, can't search all files in this project?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
githistory|don|0.4.6
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
beautify|Hoo|1.4.9
vscode-language-pack-zh-hans|MS-|1.31.4
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
view-in-browser|qin|0.0.5
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please see the wiki page for troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Search-Issues
