### ISSUE TITLE
Folder and file creation

### ISSUE THREAD

**Issue by ChristopherParo** [Microsoft/vscode#69490]
Issue Type: <b>Bug</b>

Currently when using the folder/file.js string to create both the file and the folder at the same time both the file and folder do not appear in the explorer until you restart VS code.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.43
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
graphql-for-vscode|kum|1.13.0
material-icon-theme|PKi|3.6.3
highlight-matching-tag|vin|0.8.6

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
> Currently when using the folder/file.js string to create both the file and the folder

@ChristopherParo how do you do this? I'm not familiar with the feature.

**Comment by ChristopherParo** [comment]
@Tyriar from the explorer window click on the new file icon. That will open the line to name your file.

Instead of just writing the name of the file you can write a string like this "folder/file.js" and it will create that folder as well as the file inside the folder.

I use it like crazy lol but now when I do it the folder and file will not appear in the explorer until I close vs code and reopen it.

This bug was introduced with the most recent update.

**Comment by Tyriar** [comment]
@ChristopherParo neat 😃

**Comment by isidorn** [comment]
Fixed in latest insiders.
