### ISSUE TITLE
Inline problem view layout

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#69495]
How is the width calculated? I can scroll very far to the right: 
![image](https://user-images.githubusercontent.com/323878/53459057-48079680-39ed-11e9-98d4-49a8cfdad852.png)

Also its width is not adjusted when the window size changes.

- Have the sidebar opened so the problem view has to scroll
- Hide the sidebar
- Problem view scrollbar only goes halfway

![image](https://user-images.githubusercontent.com/323878/53459289-1511d280-39ee-11e9-9ff4-abcbfed4fc42.png)

**Comment by sandy081** [comment]
Scroll width is computed from the content of the message and looks like it is not updated on layout change.
