### ISSUE TITLE
Clicking on the gutter closes peek definition window

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6950]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open the peek definition window on a variable
2. Set and remove breakpoints inside the peek window.

It doesn't do it always, but randomly will close the peek window when setting and removing breakpoints.

**Comment by isidorn** [comment]
It is not only clicking on the brekapoint but on the gutter closes the peek definition window.
I know Alex refatctored code in this area so forwading to him

**Comment by alexandrudima** [comment]
@vsccarl Are you double clicking?

**Comment by vsccarl** [comment]
@alexandrudima Yes, its double clicking anywhere on the peek window is closing it.

**Comment by jrieken** [comment]
close on double click is the design - that allows you jump to preview location quickly. there is an option `stablePeek` to turn that off
