### ISSUE TITLE
Whitelist circleci.com badges for extension READMEs

### ISSUE THREAD

**Issue by chdsbd** [Microsoft/vscode#69500]
- VSCode Version: Version 1.31.0-insider
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Search for [Margin Colours](https://github.com/chinchiheather/vscode-margin-colours) `chinchiheather.vscode-margin-colours` in the extensions panel
2. See that the circleci badge is not loading.

Does this issue occur when all extensions are disabled?: Yes

There is a previous issue for this, but it seems that the update was never made: https://github.com/Microsoft/vscode/issues/53804

circleci.com needs to be added to the whitelist for approved badge domains and documentation needs to be update: https://github.com/Microsoft/vscode-docs/blob/master/api/references/extension-manifest.md#approved-badges

Similar issue for travisci: https://github.com/Microsoft/vscode/issues/52239

<img width="390" alt="screenshot 2019-02-26 23 53 38" src="https://user-images.githubusercontent.com/1929960/53466966-09d89a00-3a22-11e9-8f07-2ef57a1fe173.png">

**Comment by chdsbd** [comment]
I guess this isn't super critical since I can use shields.io instead.

**Comment by sandy081** [comment]
@mjbvz Guess this is related to webview?
