### ISSUE TITLE
An option to manually set indent size in an editor

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [microsoft/vscode#69505]
As a motivating example, consider the following source file:
```python
import textwrap

def main():
    print(textwrap.dedent('''\
    <!DOCTYPE HTML>
    <html>
      <head>
        <title>hello world</title>
      </head>
      <body>
        Hello, world!
      </body>
    </html>'''))

if __name__ == '__main__':
    main()
```

On one hand, it's Python code, so I want indent 4. On another, it's HTML and I want indent 2. Generally, I want to manually change indent size depending on what I'm editing at the moment.

When I click on the indentation indicator in the status bar, the following actions are offered:
![image](https://user-images.githubusercontent.com/302938/53472211-18ea3700-3a78-11e9-974a-b7aecd69a9a1.png)

It would be nice to also have a "Set indent size to a specified number" action.

**Comment by ecgan** [comment]
@Vlad-Shcherbina , 

> It would be nice to also have a "Set indent size to a specified number" action.

Once you select the "Indent Using Spaces" action, you can select the number of space, like below: (for some reason, it says "tab size" even though I selected "space")

![image](https://user-images.githubusercontent.com/417342/59037107-2f880180-88a3-11e9-9026-05501d80730e.png)

This addresses your issue, right?

**Comment by Vlad-Shcherbina** [comment]
@ecgan, thank you! This works.

But this functionality is easy to miss. I didn't expect for another list to appear after selecting "Indent Using Spaces".

For menus, "..." after an item conventionally indicates that it opens a dialog box, and ">" or a triangle pointing to the right after an item means it's a submenu.

Perhaps it would be fitting to add ">" or a triangle pointing to the right here.

**Comment by ecgan** [comment]
@Vlad-Shcherbina , yea I remember I had similar experience / surprise when I first discovered this. Your idea is a good one. Hope the devs are able to work on your idea.
