### ISSUE TITLE
Debugging seems broken

### ISSUE THREAD

**Issue by gek0n** [Microsoft/vscode#69503]
I use gdb over ethernet. Early threads are not loaded together at the same time, it's really slow. I want to load only the thread that have breakpoint (the one I clicked on).
Popup messages with value of variable have wrong size, and some part of value is hiden and scroll bar is appeared. It's definetelly a bug

![image](https://user-images.githubusercontent.com/7239975/53473099-92832480-3a7a-11e9-908b-83c3adaacd53.png)

**Comment by weinand** [comment]
Please file against the debugger extension you are using.
