### ISSUE TITLE
Search Bug

### ISSUE THREAD

**Issue by AllanWang0507** [Microsoft/vscode#69502]
Issue Type: <b>Bug</b>

The search function on the left side only displays the current file content when the software is just opened. When the other files are not clicked, the search function can only search the current file content, and other file contents cannot be searched.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (16 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (11.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
xml|Dot|2.4.0
beautify|Hoo|1.4.9
vscode-language-pack-zh-hans|MS-|1.31.4
cpptools|ms-|0.21.0
vscode-icons|rob|8.2.0

(6 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It's not clear what your problem is. If you are missing search results, please check the wiki for troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Search-Issues
