### ISSUE TITLE
VS Code uses all my ram and CPU (searchService)

### ISSUE THREAD

**Issue by Mennims** [Microsoft/vscode#69511]
When I open certain project directories (normally large ones), VS code starts immediately eating all my memory (12GB). Closing VS Code before it freezes my computer immediately clears all the RAM. I have disabled all extensions and the problem still persists, however only when I do a ctrl + E to search for files. As soon as I do that, my memory starts climbing until it reaches max memory and starts going into the swap. I've had this problem over a year ago and it has come back, often resulting in an unexpected freeze and crash of my OS. I limited the amount of files it can watch to as low as 8 and the problem still persisted when I tried to search for files. It's becoming extremely frustrating that apparently no one can replicate this problem even though quite a few people have reported this issue over the last year. If I look at the process explorer, I can see the RAM usage of searchService skyrocket. I have also set the following config, which has made no effect.

"files.watcherExclude": {
      "**/.git/objects/**": true,
      "**/.git/subtree-cache/**": true,
      "**/node_modules/*/**": true
    }

If there's any way I can help diagnose or fix this problem, let me know. My project directory has 566 subfolders and 4373 files, if that helps. I've opened larger directories with no problem whatsoever, so I don't think it's just specific to the file count.

**Comment by roblourens** [comment]
Is it possible that you have symlinks leading outside of your workspace causing a search to include many other files? You can try disabling `search.followSymlinks`.

Also when this is happening do you see an `rg` process using lots of CPU or memory? It's surprising to me that searchService would be the one using lots of memory.

**Comment by Mennims** [comment]
Thanks for the quick response @roblourens! You are amazing. Disabling `
search.followSymlinks` did the trick. VS Code is working perfectly again.

Using a htop I do see an `rg` process consuming lots of CPU and memory..

Is this an issue and will it be fixed? If so, I can provide more information on my symlinks if needed

**Comment by roblourens** [comment]
It's probably not a bug, it's likely that you have symlinks that lead out of your workspace and cause vscode to search much more than is needed.
