### ISSUE TITLE
Not updating newly created files and folders

### ISSUE THREAD

**Issue by smp27** [Microsoft/vscode#69514]
Issue Type: <b>Bug</b>

I created new folders and files in vs code but its not showing it in the editor all though they are created they are just not showing. i have to restart the editor to see them

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.0.1

</details>

**Comment by alejandrofdiaz** [comment]
It happens to me when creating new file, and create a folder at the same time:
Create new file -> `insideFolder/myFile.ts`.
But i don't need to reload editor, just refresh explorer and it appears.

**Comment by isidorn** [comment]
This is fixed in latest. Try vscode insiders or wait for the stable release next week.
