### ISSUE TITLE
VS Code doesn't detect changes/references in files used by importing 'index.ts' in angular and don't recompiling project

### ISSUE THREAD

**Issue by zwiras** [Microsoft/vscode#69517]
- VSCode Version:  1.31.1
- OS Version: Windows_NT x64 10.0.17134

Does this issue occur when all extensions are disabled?: Yes

In AppComponent the IPerson1 interface is imported by index. Probably visual studio doesn't  detect references to the file and doesn't recompile the project when changing and saving the file. The interface "IPerson2" is imported directly and recompile works.

Steps to Reproduce:

1. Create Angular project
2. Add new folder "person"
3. Add file iperson1.ts to "person" folder 
```
export interface IPerson1 {
  name: string;
  age: number;
}
```
4. Add file IPerson2 to "person" folder 
```
export interface iperson2.ts {
  name: string;
  age: number;
}
```
5. Add ile index.ts to "person" folder
```
export * from './iperson';
export * from './iperson2';
```
6. Add this code to AppComponent:

```
import { IPerson1 } from './person';
import { IPerson2 } from './person/iperson2';
```

```
  person: IPerson1 = {
    age: 20,
    name: 'Karl'
  };

  person2: IPerson2 = {
    age: 21,
    name: 'Tomas'
  };
```
7. Start project: _npm start_
8. Change something in iperson1.ts and save. Project is not recompiled. 
9. Change something in iperson2.ts and save. Project is recompiled. 

![vscode2](https://user-images.githubusercontent.com/5776195/53482781-4fc44b00-3a80-11e9-9cc9-66f981f4f09c.gif)

**Comment by mjbvz** [comment]
This looks like an issue with the compiler you are running on the command line,  not with VS code. Please try filing this against either Angular or Typescript
