### ISSUE TITLE
VsCode Languag pack Russian - Hotkey problem

### ISSUE THREAD

**Issue by janbaltus** [Microsoft/vscode#69515]
Russian HK are not visible as expected. in 1.32.3 LP version.

&Файл is displayed instead of functional Hotkey

![obrazek](https://user-images.githubusercontent.com/18324209/53483622-29071400-3a82-11e9-83df-803be74cb6f0.png)

**Comment by dbaeumer** [comment]
Assigning to @bpasero & @sbatten since this is not releated to localization itself.

**Comment by dbaeumer** [comment]
We should try to fix this for 1.32 if possible since it is a regression.
