### ISSUE TITLE
can i customize the  default includepath in .vscode?

### ISSUE THREAD

**Issue by whr94621** [Microsoft/vscode#6951]
I am using ubuntu 16.04 and the default includePath of Linux is always '/usr/include'. 
I have always to add '/usr/include/c++/5.x' to the path manually.
Is there any way to modify the default includePath?
thx!

**Comment by Tyriar** [comment]
@whr94621 this issue should belong to the [cpptools extension](https://microsoft.gallery.vsassets.io/items?itemName=ms-vscode.cpptools) right?

**Comment by whr94621** [comment]
@Tyriar I am not so sure about where to put this issue...

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/vscppsamples#58
