### ISSUE TITLE
User and Workspace Settings can not be set to "false"

### ISSUE THREAD

**Issue by tjahn** [Microsoft/vscode#69512]
Hello,

I was using some plugin and tried to set some extension setting to "false" by unmarking the checkbox.  Instead, the parameter is removed from the settings. To explicitly set it false I have to manually do so in json-mode.

That said, it may be questionable, or even a bug, that this extension defaults to "true" if tslint.ignoreDefinitionFiles is unknown, what caused my problems in the first place. The extension is the typescript-tslint-plugin and the setting "tslint.ignoreDefinitionFiles".

Best, tjahn

**Comment by roblourens** [comment]
When a setting is set to its default, we remove it from the settings file. It looks like that setting doesn't have a default declared so we would assume it's `false`. If it's actually true, they should declare the setting with that default. Could you file an issue on that extension?
