### ISSUE TITLE
Focussed Extension description is almost unreadable in default light theme

### ISSUE THREAD

**Issue by LaRusCat** [Microsoft/vscode#69516]
Issue Type: <b>Bug</b>

Select default light theme
Select some Extension in extensions list
Try to read text on Extension item

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 3.13.0-166-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (3 x 3000)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.80GB (0.14GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
code-settings-sync|Sha|3.2.5
code-spell-checker|str|1.6.10
org-mode|too|0.5.0

</details>

**Comment by sandy081** [comment]
@LaRusCat Can you please provide a screenshot of what you are seeing?

**Comment by LaRusCat** [comment]
![vscode](https://user-images.githubusercontent.com/1818541/53700198-7ecc1b00-3df8-11e9-8eab-2a622a9f87eb.jpg)
Yes of course!

**Comment by LaRusCat** [comment]
![vscode](https://user-images.githubusercontent.com/1818541/53700198-7ecc1b00-3df8-11e9-8eab-2a622a9f87eb.jpg)
Yes of course!

**Comment by sandy081** [comment]
@LaRusCat Which theme are you using? And do you have any colour customisations in your settings? Also try to disable all extensions and check?

**Comment by LaRusCat** [comment]
@sandy081 I am using "Light+ (default light)" theme. 
And I don't have any color customization. 
 And this issue is reproducible after disabling all settings. 
I can try to reset all setting (remove all configs or something like this). Or try to reinstall it completely.

**Comment by LaRusCat** [comment]
@sandy081 looks like there is some problems in my configs(but I don't know how I broke this theme, because I didn't customize any themes, just switch between light and dark themes). I tested VSCode from an other user and theme works well. 
I think I can close this issue. 
Thanks!
