### ISSUE TITLE
Option to hide keyword suggestions in autocomplete

### ISSUE THREAD

**Issue by bali182** [Microsoft/vscode#69518]
While they might be very helpful while a new learning a language, most of the time they are very distracting. Let's say I'm interested in what methods are available on a subclass from the parent to overwrite or want to find local variables (this is not a big deal, but still distracting):

![vcode](https://user-images.githubusercontent.com/3879181/53485323-d88db780-3a7d-11e9-9475-2c2fc3dd9e76.gif)

I couldn't find any info about this (might have used the wrong keywords, no pun intended) so I'd propose an option to disable keyword suggestions in autocomplete.

**Comment by usernamehw** [comment]
Possible duplicate of #45039
