### ISSUE TITLE
Settings UI shifts when switching back to it

### ISSUE THREAD

**Issue by imba-tjd** [Microsoft/vscode#69523]
- VSCode Version: 1.13.1
- OS Version: Windows 10 1809 and Windows 7(VM)

Steps to Reproduce:

1. open settings ui and scroll down a little.
2. switch to another tab, for example <kbd>ctrl</kbd>+<kbd>N</kbd>.
3. switch to settings ui.

Then it would shift a little bit.

Maybe related to https://github.com/Microsoft/vscode/issues/68385

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Yeah it doesn't look exactly the same but it has the same cause as #68385
