### ISSUE TITLE
Git count badge's text will be cut when files over a thousand

### ISSUE THREAD

**Issue by anemology** [Microsoft/vscode#69521]
Issue Type: <b>Bug</b>

The chinese text is `2 千以上`, But it's too long so can't display all.

locale: left=`zh-tw`, right=`en-us`

<img width="254" src="https://user-images.githubusercontent.com/12845882/53484861-c2a0e680-3abf-11e9-885e-18e163646546.png"><img width="254" src="https://user-images.githubusercontent.com/12845882/53484874-ccc2e500-3abf-11e9-9b1f-e3664e1bcb84.png">

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
sql-formatter|cym|1.0.2
angular-schematics|cyr|1.18.0
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.8.0
angular-extension-pack|dog|7.1.0
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
auto-rename-tag|for|0.0.15
angular2-switcher|inf|0.2.0
docthis|joe|0.7.1
Angular2|joh|7.0.1
refactorix|kri|0.3.6
json-to-ts|Mar|1.5.5
rainbow-csv|mec|1.0.0
Angular-BeastCode|Mik|7.2.4
ecdc|mit|1.0.5
vscode-language-pack-zh-hant|MS-|1.31.4
python|ms-|2019.2.5416
typescript-javascript-grammar|ms-|0.0.49
vscode-typescript-tslint-plugin|ms-|1.0.0
quicktype|qui|12.0.46
move-ts|str|1.11.3
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by octref** [comment]
@joaomoreno You can use 2000+. "2千+" would read very weird.

**Comment by joaomoreno** [comment]
2000+ would also not fit. We might have to go with 999+.

**Comment by octref** [comment]
In that case I suggest using 2k+ for consistency.

**Comment by joaomoreno** [comment]
@sandy081 This does not localize well: https://github.com/Microsoft/vscode/commit/b71f2ad25d1b5c347f8b2b175dab73d562ffeb1a

**Comment by sandy081** [comment]
Localising it does not makes sense. Will show it as `nk+` for all languages.
