### ISSUE TITLE
close icon in "OPEN EDITORS" overflow when it active

### ISSUE THREAD

**Issue by GFwer** [microsoft/vscode#69522]
- VSCode Version:1.31.1
- OS Version:MacOS 10.14.3

Steps to Reproduce:
as the picture shows:
![image](https://user-images.githubusercontent.com/14303098/53486225-21b42a80-3ac3-11e9-9cdc-edb64709a483.png)

increase the element width may fix this problem

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Do you also see this with latest vscode insiders?
https://code.visualstudio.com/insiders/

**Comment by GFwer** [comment]
@isidorn Yes, maybe I didn’t express it clearly.it reproduces when the mouse clicks the icon button(with :active pseudo-class), then this situation will appear.
