### ISSUE TITLE
Tree: do not getChildren of elements that user collapsed

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69526]
The tree calls `getChildren` on elements that the user manually collapsed. This is different behavior as compared to the old tree (I verified using vscode 1.29).

Repro steps:
1. Explorer expand some top level folder, collapse it
2. Click refresh
3. Notice that the Tree will ask getChildren of the collapsed folder

**Comment by joaomoreno** [comment]
#67722

**Comment by isidorn** [comment]
Nice!
