### ISSUE TITLE
workbench.action.navigate : Can't switch between split terminal panes ? 

### ISSUE THREAD

**Issue by gomesalexandre** [Microsoft/vscode#69525]
Hi everyone,
This is the relevant snippet from my `keybindings.json`:
```javascript
	{
        "key": "ctrl+j",
        "command": "workbench.action.navigateLeft"
	},
	{
        "key": "ctrl+l",
        "command": "workbench.action.navigateUp"
        },
        {
        "key": "ctrl+k",
        "command": "workbench.action.navigateRight"
	},
	{
        "key": "ctrl+h",
        "command": "workbench.action.navigateDown"
        },
```
**Expected behaviour :** 
Ideally, I'd like to be able to navigate between panes, **including split terminals** using hjkl. 

**Actual behaviour**
Unfortunately, it seems that `workbench.action.navigate` sees the terminal as one pane. 
I think it would be better to make split terminals act as separate panes in this context, so such keybindings would work .

Or, if this doesn't make sense, maybe a way to achieve this with current `workbench.action` state is already possible ?

Thank you 😃

**Comment by usernamehw** [comment]
Have you tried those?:

![screenshot 78](https://user-images.githubusercontent.com/9638156/53533558-644e2500-3b0c-11e9-9ceb-40063f919a7a.png)

**Comment by gomesalexandre** [comment]
@usernamehw That wouldn't really work, or would it ? Because the behaviour should be 
*if terminal focused*
  `focus next terminal pane` on ctrl +k 
*else if pane focused*
  `focus next editor pane` on ctrl +k

My understanding is that if I use the actions you posted, it would overwrite the `focus next/previous editor pane`, except if there's a way to provide context to actions.

**Comment by usernamehw** [comment]
Welcome to contexts https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

```json
{
	"key": "ctrl+l",
	"command": "workbench.action.nextEditor",
},
{
	"key": "ctrl+l",
	"command": "workbench.action.terminal.focusNextPane",
	"when": "terminalFocus"
},
```

**Comment by Tyriar** [comment]
I don't think we should support split terminals as part of the navigate* commands as right now it navigates across the "top level" views: editor groups, the panel and the viewlet. Perhaps in the future we might want to add some sub-group navigation 🤔 ?
