### ISSUE TITLE
Simplified file picker says \c:\ instead of c:\

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69537]
![image](https://user-images.githubusercontent.com/2193314/53498002-4b853700-3a5a-11e9-82e4-e4d83a265a2f.png)

Maybe it should use caps as well for the drive?

**Comment by alexr00** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/07e498f887c32cbb621233c3d40aa69ed30aeeae
