### ISSUE TITLE
Error: "vscode.Uri.file" is not a constructor

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#69533]
My extension uses `vscode.Uri.file` to construct a resource with a file path:

`treeItem.resourceUri = new vscode.Uri.file( node.fsPath );`

https://code.visualstudio.com/api/references/vscode-api#Uri

This works correctly in the stable build, but in the insiders build (1.32.0-insider, 7d0c9e6fa0bedcf71bdae86c02611b65362795a3 ) I get the error:

`vscode.Uri.file is not a constructor`

Am I doing something wrong?

**Comment by jrieken** [comment]
> Am I doing something wrong?

Yes ;-) It's not a constructor function but a static function. Use `vscode.Uri.file(node.fsPath)`

**Comment by jrieken** [comment]
> This works correctly in the stable build, but in the insiders build (1.32.0-insider, [7d0c9e6](https://github.com/Microsoft/vscode/commit/7d0c9e6fa0bedcf71bdae86c02611b65362795a3) )

This is likely because we now compile to ES6, meaning the URI-class is now actually a class and not functions/prototypes anymore. The latter, functions, allow using `new` in more relaxed ways but it's likely not what you wanted. The ES6 world is more strict.
