### ISSUE TITLE
Uber-faded out explorer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#69538]
* open explorer
* type the name of a folder
* while the highlight shows, press `Enter`
* 🐛 everything is super grey now, you need to reload to get out of this

![feb-27-2019 15-40-35](https://user-images.githubusercontent.com/1794099/53498161-130b4a80-3aa6-11e9-9d26-45f84c698003.gif)

**Comment by usernamehw** [comment]
duplicate of #69468 ?

**Comment by isidorn** [comment]
Yeah, duplicate fixed in latest
