### ISSUE TITLE
Simplified file picker should finish auto complete when tab is pressed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69539]
Feels natural to press tab here to do the same as enter. Maybe tab should auto-complete if there is a selection in the textbox, otherwise move focus?

![image](https://user-images.githubusercontent.com/2193314/53498164-a4ed6600-3a5a-11e9-8331-3e4cb60132fb.png)

**Comment by alexr00** [comment]
I'm not so sure about this now that we have the OK button there. Having tab behave differently based on whether there is a selection is a bit confusing. I'm leaving this open for upvotes and opinions, but for now I'm going to leave tab to change focus.

**Comment by Tyriar** [comment]
Yeah with the new buttons I don't think we should do this.
