### ISSUE TITLE
Simplified file picker undo doesn't work as expected

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69536]
![image](https://user-images.githubusercontent.com/2193314/53497749-b97d2e80-3a59-11e9-8699-7eff81e186ad.png)

ctrl+backspace

![image](https://user-images.githubusercontent.com/2193314/53497771-c6018700-3a59-11e9-81d1-46ebe49cd814.png)

ctrl+backspace

![image](https://user-images.githubusercontent.com/2193314/53497788-d0bc1c00-3a59-11e9-90e3-83a065d57372.png)

ctrl+z

![image](https://user-images.githubusercontent.com/2193314/53497803-dc0f4780-3a59-11e9-8d5e-e079e6f2f4c5.png)

ctrl+z

![image](https://user-images.githubusercontent.com/2193314/53497828-ee898100-3a59-11e9-91a0-1dc85b891de9.png)

I see two ways we could fix:

1. Don't autocomplete when ctrl+z is pressed
2. Remove the selection before applying the undo (probably better)

Ideally redo would also function correctly as well, right now redo will leave the duplicated "REDMOND" part

**Comment by alexr00** [comment]
This is actually way more complicated that it seems. I tried out a change where I just don't do the autocomplete in this case, and I've tried removing the selection. Neither work because some how somewhere something is getting added to the undo buffer.
