### ISSUE TITLE
Deployment to Single device not working

### ISSUE THREAD

**Issue by Grewall** [Microsoft/vscode#69548]
Issue Type: <b>Bug</b>

Right Click Edge Device > Create Deployemnt for single device > 

Prompt to select device > Select Device

Nothing happens after that i.e. no popup to select file

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.7.0
azure-account|ms-|0.8.0
PowerShell|ms-|1.11.0
team|ms-|1.149.2
material-icon-theme|PKi|3.6.3
vscode-icons|rob|8.2.0
azure-iot-edge|vsc|1.10.0
azure-iot-toolkit|vsc|2.3.0
azure-iot-tools|vsc|0.0.2
vscode-iot-workbench|vsc|0.2.4

</details>

**Comment by rebornix** [comment]
Please file issue against the extension which support this features, thanks!
