### ISSUE TITLE
Generated `npm` tasks fail to launch

### ISSUE THREAD

**Issue by canadaduane** [Microsoft/vscode#69547]
I generated a new typescript extension on Mac OS X. When running the extension via the "Run Extension" launch configuration, it tries to kick off the `npm run watch` script via a [task](https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-ts/vscode/tasks.json). However, I get the following error:

```
The terminal process command '/bin/bash -c 'npm run watch'' failed to launch (exit code: 127)
```

No javascript is generated. However, when I run this script in my regular shell, it generates the compiled js file in the `out` directory as expected.

I suspect that the `npm` type task should be passing the `-l` flag to `/bin/bash` when calling `npm run watch`. The `-l` flag tells the shell to act as a "login shell." If it were to pass this flag, environment variables such as "PATH" and others from my `$HOME/.profile` shell config would be picked up. This flag is in fact the [default shell arg passed by vscode in OS X](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/electron-browser/terminal.contribution.ts#L99).

Is this a vscode-generator-code issue, or a bug in vscode? (or something else?)

* probably related: [this stackoverflow question](https://stackoverflow.com/questions/54194964/vscode-terminal-process-command-failed-to-launch).

**Comment by alexr00** [comment]
We deliberately don't use the login shell for tasks. However, this should definitely work. @canadaduane, can you run the `Run Task` command and run the npm compile task? What is the output in the terminal?
