### ISSUE TITLE
A tab opens when I switch to "Explorer" from "Search"

### ISSUE THREAD

**Issue by arturogh** [Microsoft/vscode#69556]
Issue Type: <b>Bug</b>

When I'm on Search, close all tabs, and switch to Explorer, one of the tabs I closed opens.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|-psn_0_11053706|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
htmltagwrap|bra|0.0.7
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.8.0
xcs-react-snippets|edu|0.1.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
vscode-flatland-icon-theme|geb|0.0.6
path-autocomplete|ion|1.13.1
vscode-styled-components|jpo|0.0.25
better-line-select|kai|1.0.1
vscode-simple-icons|Lau|1.11.2
vscode-azureappservice|ms-|0.12.0
atom-keybindings|ms-|3.0.6
azure-account|ms-|0.8.0
vsliveshare|ms-|0.3.1256
team|ms-|1.149.2
color-highlight|nau|2.3.0
vscode-jest|Ort|2.9.2
vscode-framerx-code-snippets|pix|0.0.61
material-icon-theme|PKi|3.6.3
esdoc-mdn|sam|0.8.0
markdown-preview-enhanced|shd|0.3.11
mdx|sil|0.1.0
vscode-fileutils|sle|2.13.5
ayu|tea|0.18.0
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|2.1.0

(10 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce with latest insiders?
https://code.visualstudio.com/insiders/

**Comment by arturogh** [comment]
Cannot! Was likely fixed then?

**Comment by isidorn** [comment]
Yeah it is fixed
