### ISSUE TITLE
Is it possible to have VS Code include .dart file associations during install?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#69551]
When installing VS Code, there's an option to have it associated itself with known file types (and I think also set icons). It's not clear where this is configured - is it possible to add .dart files to this?

**Comment by joaomoreno** [comment]
Since Dart is not a built-in language, I don't see how this would be possible at install time.

**Comment by DanTup** [comment]
Is there a reason it needs to be built-in in order to do this? When you open your first Dart file, you get the "marketplace has extensions for editing Dart files" prompt. I appreciate it may be a little strange to associate files not supported out-of-the-box, but I don't think it's completely crazy.

Otherwise, is it likely VS Code might ever get a feature/command to associate itself with known file extensions once their language extensions are installed?

**Comment by joaomoreno** [comment]
> Otherwise, is it likely VS Code might ever get a feature/command to associate itself with known file extensions once their language extensions are installed?

Feel free to create such an issue, it's a valid one for sure.

**Comment by DanTup** [comment]
Done! https://github.com/Microsoft/vscode/issues/69784
