### ISSUE TITLE
Extension api: WorkspaceSymbolProvider.resolveWorkspaceSymbol is never called without working around the type system

### ISSUE THREAD

**Issue by johnspurlock** [microsoft/vscode#69558]
Version: 1.32.0-insider
Commit: ce073b0076ac2f69faf2c609af72f9b81506c791
Date: 2019-02-27T06:15:35.767Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Docs for [WorkspaceSymbolProvider](https://code.visualstudio.com/api/references/vscode-api#WorkspaceSymbolProvider).provideWorkspaceSymbols state that:

> To improve performance implementors can implement resolveWorkspaceSymbol and then provide symbols with partial location-objects, without a range defined. The editor will then call resolveWorkspaceSymbol for selected symbols only.

Unfortunately, there is no type-safe way of creating Location objects with an undefined Range. 
 Using Range or Position in the only constructor`constructor(uri: Uri, rangeOrPosition: Range | Position);` results in `resolveWorkspaceSymbol` never being called.

If you hack around the type system, you can get around this constraint. e.g. `undefined as any` as the constructor arg, or `(location as any).range = undefined;` after construction.  Once you do this, `resolveWorkspaceSymbol` is called as expected. 

So the logic does work, it's just awkward to get there without battling the type system.

Thanks!

**Comment by jrieken** [comment]
@mjbvz Do you have a good idea? Technically we should allow to have `Location#range` be `Range | undefined`. That how it used to be but didn't spec it like that and doing so seems less pretty ;-) 

How about asking to resolve an item independent of having a range but whenever the provider has a resolve function? Optionally we can add a `isResolved` property so that we avoid asking too many times.

**Comment by mjbvz** [comment]
Interesting. From a type perspective, we would need to remove the `location` property from `SymbolInformation` and add it back with a different type. Something like this would work:

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

provideWorkspaceSymbols(query: string, token: CancellationToken): ProviderResult<
    Array<Omit<SymbolInformation, 'location'> & {
        location: Omit<Location, 'range'> & { range?: Range }
    } >
>;
```

This makes intellisense pretty ugly and you still would not be able to use the `Location` or `Range` constructors so I don't think this is a good solution.

Another option would be to create constants for unresolved ranges:

```ts
// In d.ts
export const UnresolvedRange: Range;

// Which behind the scenes could be defined as:
export const UnresolvedRange = new Range(-1, -1, -1, -1);
```

Or maybe just treat any invalid range (such as having a negative line number) as unresolved?

**Comment by jrieken** [comment]
Moving this out, the easiest is to use the `!` operator for now

**Comment by jrieken** [comment]
This is a valid issue but we have no simple fix for it. I believe doing special type gymnastics just for this case isn't worth the gain. Sorry, but closing without fix.

**Comment by jrieken** [comment]
The plan is as follows:

* When a provider implement "resolve" we will always call that function when an item is being opened. In real life that's once
* With that in mind in doesn't matter what range a provider returns, a good default would be (0,0,0,0)

**Comment by jrieken** [comment]
fyi @dbaeumer

**Comment by dbaeumer** [comment]
Added support to LSP.
