### ISSUE TITLE
Collapse + expand comments editor with text breaks its height

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#69553]
- Open PR comment thread
- Type a reply comment but don't submit
- Collapse comment thread
- Expand comment thread, see the text persisted but only the first line is visible
- See that the monaco instance is only 1 line tall. For example if I use the up/down arrow keys I can only see one line of text at a time

**Comment by rebornix** [comment]
I can no longer reproduce this issue in latest Insiders.
