### ISSUE TITLE
"Find With Selection" doesn't work on multi-line strings

### ISSUE THREAD

**Issue by elias6** [Microsoft/vscode#69568]
I have a file open in VS Code. I selected multiple lines, then pressed Cmd+E to search for this selection in the file. The search thing pops up in the top right corner, but instead of being populated with the text selected in the editor, it has what was in there before. If I press Cmd+G to go to the next match, nothing happens.

I can search for things on a single line with Cmd+E. And I can search for things on multiple lines by using the regex feature and typing `\n` in the search thing. But I can't search for things on multiple lines using Cmd+E.

**Note: I did not test this with any beta or insiders build. I don't know if I will have time to do that any time soon. But I searched existing issues and couldn't find anything that looks like this.**

- VSCode Version: Version 1.31.1
- OS Version: macOs High Sierra Version 10.13.6

Steps to Reproduce:
Create a file with this text:
```
foo
bar

foo
asdf

foo
bar
```
Select the first 2 lines (`foo` and `bar`). Press Cmd+E. Then press Cmd+G. Nothing happens, even though I would expect the selection to jump to the next occurrence of those 2 lines. Or sometimes (seemingly depending on what was searched for before), the selection goes to the next occurrence of `foo`, as if it is only looking at the first line of what is being searched for.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Currently, find can only do multiline queries using a regex. #15727
