### ISSUE TITLE
Open: Cmd + click opens in new window

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6956]
If I want to have a workspace in a new window of vscode I first have to open a new empty workspace window and then chose the workspace (thus doing 2 actions).
In my workflow it would be great if I could cmd + click on recent to open that workspace in a new instance of VSCode.

Any improvement on how to make this 2 step operation a 1 step operetion is great.

**Comment by bpasero** [comment]
@dbaeumer ping because you had a similar request, I decided to push this for June supporting Ctrl+click from the "Open Recent" picker. Will be in master once we open.

**Comment by isidorn** [comment]
Does not work for me on the mac, tried both ctrl and cmd. Feature -> moving to july

**Comment by bpasero** [comment]
Works for me.
