### ISSUE TITLE
Terminal lost all scrolling lines after sometime moving away and coming back

### ISSUE THREAD

**Issue by hiepkhuuMS** [Microsoft/vscode#69562]
Issue Type: <b>Bug</b>

- Open VSCode with OSG repo, and open Terminal with razzle setup. 
- Then, doing some build. 
- Then, moving away doing other things on Browser. 
- Coming back to VSCode and Terminal lost all lines, including razzle. Keep pressing any button does not bring back my razzle inside Terminal.

This is bad. The only way for me to get it back is by closing VSCode and re-open Terminal and run script to open razzle again.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18346

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (11.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-nmake-tools|Mic|1.1.190220004
cpptools|ms-|0.21.0
team|ms-|1.149.2

</details>

**Comment by Tyriar** [comment]
You're likely hitting https://github.com/Microsoft/vscode/issues/68721, should be fixed in insiders.
