### ISSUE TITLE
Running npm install from Terminal fails

### ISSUE THREAD

**Issue by ljhca** [Microsoft/vscode#69561]
Issue Type: <b>Bug</b>

I had an empty project, with a shell package.json file like this:

{
  "name": "company.application.web",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {},
  "dependencies": {}
}

I installed 'vue' and then attempted to install 'webpack' packages via npm. 

The webpack install failed due to the Terminal not having write access to a sub-folder within 'node_modules'.

I then ran the npm install webpack -D command again in Powershell and it succeeded without error.

The Terminal output:

S C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp> npm install vue -D
+ vue@2.6.7
added 1 package from 1 contributor and audited 1 package in 0.747s
found 0 vulnerabilities

PS C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp> npm install webpack -D
npm ERR! path C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json.742067490
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json.742067490' -> 'C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json'
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json.742067490' -> 'C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json.742067490' -> 'C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp\node_modules\source-map-url\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path:
npm ERR!       'C:\\_ljdev\\HCA.BookingSystem\\HCA.BookingSystem.WebApp\\node_modules\\source-map-url\\package.json.742067490',
npm ERR!      dest:
npm ERR!       'C:\\_ljdev\\HCA.BookingSystem\\HCA.BookingSystem.WebApp\\node_modules\\source-map-url\\package.json' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, rename \'C:\\_ljdev\\HCA.BookingSystem\\HCA.BookingSystem.WebApp\\node_modules\\source-map-url\\package.json.742067490\' -> \'C:\\_ljdev\\HCA.BookingSystem\\HCA.BookingSystem.WebApp\\node_modules\\source-map-url\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path:
npm ERR!    'C:\\_ljdev\\HCA.BookingSystem\\HCA.BookingSystem.WebApp\\node_modules\\source-map-url\\package.json.742067490',
npm ERR!   dest:
npm ERR!    'C:\\_ljdev\\HCA.BookingSystem\\HCA.BookingSystem.WebApp\\node_modules\\source-map-url\\package.json',
npm ERR!   parent: 'hca.bookingsystem.web' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user.name\AppData\Roaming\npm-cache\_logs\2019-02-27T22_45_38_299Z-debug.log
PS C:\_ljdev\HCA.BookingSystem\HCA.BookingSystem.WebApp> 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
xml|Dot|2.4.0
auto-close-tag|for|0.5.6
csharp|ms-|1.17.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vetur|oct|0.16.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
