### ISSUE TITLE
The terminal process terminated with exit code: 2

### ISSUE THREAD

**Issue by Eavendano1987** [microsoft/vscode#69564]
When I compile my code, it ends up saying that it has an error, as shown below and my code does not work on my board:
make: *** [C:\Users\Kyle\.particle\toolchains\buildscripts\1.2.0\Makefile:38: compile-user] Error 2
The terminal process terminated with exit code: 2

how can i fixed? 
Can somebody help me?
Thanks

**Comment by Tyriar** [comment]
How are you compiling your code? Some extension? Running the command in the terminal manually? A task? etc.

**Comment by rorypeck** [comment]
Hi, delete the folder "C:\Users\Name\AppData\Roaming\Code" can fix it, but user setting should be reset

**Comment by Thoralf-M** [comment]
With `Terminal -> New Terminal` instead of the shortcut it worked for me

**Comment by Eavendano1987** [comment]
Hello @Tyriar 
I compile my code manually, press the button shown in the image.

![vs](https://user-images.githubusercontent.com/45610476/53745386-2af31d80-3e5c-11e9-9f3d-fae5eeb4cd26.jpg)

**Comment by Eavendano1987** [comment]
Hello  @rorypeck  and @Thoralf-M 

Thanks for the information, I will try and let you know if it works.

**Comment by Eavendano1987** [comment]
Hello @rorypeck  and @Thoralf-M 

I make your recommendations but I still have the same error
![vs01](https://user-images.githubusercontent.com/45610476/53766315-bf2aa800-3e8f-11e9-9e7f-1eb510cb3ee5.jpg)

**Comment by krishnageethika** [comment]
> Hello @rorypeck and @Thoralf-M
> 
> I make your recommendations but I still have the same error
> ![vs01](https://user-images.githubusercontent.com/45610476/53766315-bf2aa800-3e8f-11e9-9e7f-1eb510cb3ee5.jpg)

Getting the same issue as well. How could you resolve that??

**Comment by Tyriar** [comment]
It really seems like whatever your extension is running is failing, I suggest reporting this against the extension itself. Also as I mentioned earlier, the error is improving in 1.34 so you should get a better error message when the command fails because the path doesn't exist.
