### ISSUE TITLE
when you type fi, it cannot render the character correctly

### ISSUE THREAD

**Issue by wood1986** [Microsoft/vscode#69576]
- VSCode Version: 1.31.1. It has been a while
- OS Version: Mac 10.14.3

Steps to Reproduce:

1. When you use the font Monaco" 
2. Type "f" and "i"
![image](https://user-images.githubusercontent.com/5212215/53538492-b0747780-3ac2-11e9-81e0-3b57c75be391.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by wood1986** [comment]
"f" and "l" have the same issue

**Comment by rebornix** [comment]
@wood1986 can you check if you have `editor.fontLigatures` turned on?

**Comment by wood1986** [comment]
yes. it was turned
