### ISSUE TITLE
Explorer: `Enter` doesn't collapse focused folder

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#69574]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.32.0-insider (69249882e8717cf111e04330390107282e337559, 2019-02-27T21:19:19.351Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
To verify make sure that
1. On windows and linux enter collapses / expands folders
2. On mac cmd + down collapses / expands folders
