### ISSUE TITLE
[Bug] Emoji cause the enabled extenstions to stop of working

### ISSUE THREAD

**Issue by gusbemacbe** [Microsoft/vscode#69579]
- VSCode Version: VSCode Insiders 1.32.0
- OS Version: Manajro 18.0.3 Illyria

Steps to Reproduce:

1. Create a HTML file and enable any extensions;
2. Insert `Made with ❤ and ☕ in 🇧🇷`;
3. These emoji cause the extensions to stop of working. If you restart extension host or reload the window, the same thing will happen. 

Does this issue occur when all extensions are disabled?
No, as all the extensions are disabled, these emoji did not cause anything. Only if the extensions are enabled.

**Comment by rebornix** [comment]
@gusbemacbe can you check if there is any error in Developer Tools ? (Open it by Help -> Toggle Developer Tools)

**Comment by gusbemacbe** [comment]
Hello @rebornix !

Here are two screenshots:

![imagem](https://user-images.githubusercontent.com/2257024/53593315-2508ee00-3b77-11e9-9477-be5403734620.png)

![imagem](https://user-images.githubusercontent.com/2257024/53593346-37832780-3b77-11e9-9af3-aa50f6f0675a.png)

**Comment by gusbemacbe** [comment]
More one scrrenshot:

![imagem](https://user-images.githubusercontent.com/2257024/53593715-1bcc5100-3b78-11e9-8a4e-defc64eb5559.png)

**Comment by alexandrudima** [comment]
I could not reproduce

![image](https://user-images.githubusercontent.com/5047891/55085337-c4ea6680-50a6-11e9-81fb-be2943ab2815.png)
