### ISSUE TITLE
Debugging with no launch config fails when tsc task detection is disabled

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#69572]
- Disable `typescript.tsc.autoDetect`
- Open a .ts file in a workspace with no launch.json
- Start debugging
- Get error `Could not find the task 'tsc: build - tsconfig.json'.`

**Comment by connor4312** [comment]
Does not happen with js-debug

**Comment by hediet** [comment]
I still get this error. (`"typescript.tsc.autoDetect": "off"`)

![image](https://user-images.githubusercontent.com/2931520/121256144-8a96c980-c8ac-11eb-8d72-a0b6f2a8fe05.png)

**Comment by hediet** [comment]
[repro.zip](https://github.com/microsoft/vscode/files/6622649/repro.zip)

**Comment by connor4312** [comment]
oh, the tsconfig did it. This is actually in js-debug, looks like logic I copypasta'd from the old debugger
