### ISSUE TITLE
Copy file to  a directory has a bug

### ISSUE THREAD

**Issue by gapsaras** [Microsoft/vscode#69571]
Issue Type: <b>Bug</b>

Step1: copy a file or directory
Step2: paste it to another directory in File Explorer
Result: nothing happens, but close the VS Code and restart,  it shows in the target directory

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (5.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.9
python|ms-|2019.2.5433
vetur|oct|0.16.2

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Fixed in latest insiders

**Comment by Daijobou** [comment]
Great! Thank you!
I have this bug too. 9 of 10 times the copied file was not pasted (in same directory)
But for me there was really nothing pasted. I take a look in windows explorer + F5 and there was no file like "file.1.ext"
