### ISSUE TITLE
Render checkmark in menu next to Text Wrapping

### ISSUE THREAD

**Issue by SoulAndris** [microsoft/vscode#69587]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1)  Check status text wrapping in "View".
2) Change status: click "text wrapping"  or "alt + z".
3) Text code is wrapping, but , a check mark does not appear near the item (in View).

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.13.0-26-generic

**Comment by alexdima** [comment]
Let's track in #62307
