### ISSUE TITLE
After typing Korean in the search box using "cmd + f", press esc to insert part of the "search word" into the body.

### ISSUE THREAD

**Issue by khaki4** [microsoft/vscode#69586]
- VSCode Version: 1.31.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. typing Korean in the search box using "cmd + f"
2. press esc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
I don't understand what the issue is, please provide more details.

**Comment by khaki4** [comment]
@roblourens 

<img width="652" alt="1" src="https://user-images.githubusercontent.com/8818375/53617541-ee8cab00-3c2a-11e9-8494-8fd55df94402.png">
**start with empty code.**

<img width="654" alt="2" src="https://user-images.githubusercontent.com/8818375/53617554-fe0bf400-3c2a-11e9-9a7a-c0a3d0dfa569.png">
**type "cmd + f"**

<img width="649" alt="3" src="https://user-images.githubusercontent.com/8818375/53617591-209e0d00-3c2b-11e9-9b18-843a4c765089.png">
**type "ㅇㅇ"(korean) in seach window**

<img width="654" alt="4" src="https://user-images.githubusercontent.com/8818375/53617605-2f84bf80-3c2b-11e9-93d5-b759cf88518f.png">
**inserted "ㅇ" in my code**

**Comment by khaki4** [comment]
@roblourens 
need to more infomation?

**Comment by rzhao271** [comment]
Not able to reproduce the issue in the latest stable. Adding verification-steps-needed

**Comment by rebornix** [comment]
Verifier: please follow https://github.com/microsoft/vscode/wiki/IME-Test#windows-korean to set up your IME and test.

**Comment by rzhao271** [comment]
Setting to verified for now, though I'm on Windows.
Couldn't reproduce the issue in v1.45 either.
We can just let users file a new issue if it shows up again in the future.
