### ISSUE TITLE
`--wait` has weird effects when used with ` -- ` end-of-arguments marker

### ISSUE THREAD

**Issue by tribut** [Microsoft/vscode#69588]
- VSCode Version: 1.32.0-163111aa6b
- OS Version: Ubuntu cosmic

Steps to Reproduce:
1. Start using `code --wait -- [filename]`
2. Notice two additional files are opened:

![screenshot from 2019-02-28 12-11-03](https://user-images.githubusercontent.com/719105/53562585-00e6e600-3b52-11e9-977e-5a9edc9d63c5.png)

Use case:
~~~
$ echo "this is a test" > --foo.txt
$ code --wait -- --foo.txt
~~~

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@tribut what is the use case of `--wait -- filename` exactly?

**Comment by tribut** [comment]
Gave an example above, not sure what you're asking? If the filename starts with a `-` (or might start with a `-`, for example when `code --wait` is called with a user-supplied argument) you need to use `code --wait -- "$filename"`. I stumbled across the bug while writing a script that at some points starts an editor window with such a filename I don't control.

**Comment by tribut** [comment]
It might be enough to use `argv.unshift` instead of [`argv.push` in cli.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cli.ts#L235)?

Note that a quick `git grep argv.push` shows this pattern is used a bunch of times, so it may be a good idea to fix those as well.
