### ISSUE TITLE
Add `Reset Zoom` action to menu

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#6958]
Before, zoom would never go under 100%... now it seems that it does, and I find it hard to reset it to 100%. Can we add such an action?

**Comment by bpasero** [comment]
<img width="659" alt="screen shot 2016-05-27 at 16 07 41" src="https://cloud.githubusercontent.com/assets/900690/15610368/2982e4de-2425-11e6-95f8-ffe3f0792afe.png">

**Comment by joaomoreno** [comment]
Sorry, I meant in the menu:

![image](https://cloud.githubusercontent.com/assets/22350/15610913/16bc8172-2428-11e6-88eb-b59693308d44.png)
