### ISSUE TITLE
Line selection doesn't work

### ISSUE THREAD

**Issue by gabiap96** [microsoft/vscode#69585]
Issue Type: <b>Bug</b>

Installed sublime text keys. ctrl + l did not selected the line that carat is at. Can't even find in keymap select line at carat.

**Comment by benjaminmillhouse** [comment]
Same as #70114

**Comment by wmertens** [comment]
Triage: Since this is duplicated by #70114 and there is a workaround and a wontfix state, I think this can be closed.
