### ISSUE TITLE
"sidebar" has inconsistent spelling in various keyindings conditions

### ISSUE THREAD

**Issue by matklad** [Microsoft/vscode#69589]
```
sidebarVisible | Side Bar is displayed.
sideBarFocus | Side Bar has focus.
```

from https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

I think we should make an alias, `sidebarFocus` for `sideBarFocus` and deprecate the latter

```
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.14.103
```

**Comment by isidorn** [comment]
Since we have Side Bar everywhere in the UX I decided to deprecate sidebarVisible and introduce sideBarVisible
sidebarVisible will still be supported in the march release, but in the next one we will remove it.
Marking this as feature-request as a reminder to put this into release notes.

**Comment by matklad** [comment]
@isidorn it might be a good idea to looks for other things whihc might use the wrong spelling. Ther's at least `workbench.action.toggleSidebarVisibility`

**Comment by isidorn** [comment]
You are right.
But that one I will not change. Converting command ids is a pain, and we have much wors command names than that.

**Comment by octref** [comment]
@isidorn Verified, but please update vscode-docs too.
