### ISSUE TITLE
Microsoft Python Language Server consumes ~100% of CPU

### ISSUE THREAD

**Issue by 73R3WY** [Microsoft/vscode#69581]
Microsoft.Python.Language.Server consumes around 100% of my CPU running VSCode on MacOS. I can already hear the sound of CPU fans running at full speed just like when I'm running Android Emulator. I only have three python files opened in one workspace. Before this happened, there was a status in the status bar telling that Python Language Server is being updated. Please tell me how can I provide more details to resolve this issue. Thanks.
Attached below is the screenshot of Activity Monitor.
![screen shot 2019-02-28 at 2 49 31 pm](https://user-images.githubusercontent.com/8436044/53547146-35b26780-3b69-11e9-8d46-afb463a82dde.png)

**Comment by mjbvz** [comment]
Please file this against the Python extension: https://github.com/Microsoft/vscode-python
