### ISSUE TITLE
Settings UX - Workbench Icon Theme fail to set additional value changes without blur

### ISSUE THREAD

**Issue by WORMSS** [Microsoft/vscode#69599]
Issue Type: <b>Bug</b>

Steps to Reproduce:
(Assuming your workbench icon theme is already set to vs-seti)
(Assuming you can easily see some files with icons in Explorer)
1. Select Workbench: Icon > Dropdown to `null`
2. Observe your icons in the Explorer window have now gone.
3. Without losing focus of the Workbench: Icon > Dropdown, select `vs-seti` (or any other theme you have)
4. Observe your icons in the Explorer window are still null, and the Workbench: Icon > Dropdown still has `null` selected.

--------------

Notes:
- If deselect the Workbench: Icon > Dropdown by clicking on the background of the Settings UI, and then repeat Step 3, you will observe that the icons change again.
- Something is requiring a blue of focus for setting to take effect for a second time.
- The blur is not required for the change to trigger in the first place.

Does this issue occur when all extensions are disabled?: Yes it still occurs.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (5.57GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by WORMSS** [comment]
They are not duplicates.

**Comment by WORMSS** [comment]
![image](https://user-images.githubusercontent.com/1384537/53578983-a446f380-3b70-11e9-896e-41f0216f9121.png)

Just adding for some context

**Comment by roblourens** [comment]
I think this is fixed in the latest Insiders. Please let me know if that's not the case.

**Comment by WORMSS** [comment]
@roblourens confirmed.
![image](https://user-images.githubusercontent.com/1384537/54910370-1bf40e00-4ee4-11e9-93cb-10f1ddf1970d.png)
