### ISSUE TITLE
[Explorer] Delete shortcut not working anymore

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#69590]
- VS Code Version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
- OS Version: macOS 10.14.3

Try to delete a file with `Alt+Cmd+Backspace`.
It doesn't work.

![image](https://user-images.githubusercontent.com/9491603/53563966-e9a9f780-3b55-11e9-8d40-4f107d54c840.png)

`files.enableTrash` is set to `false`. `Cmd+Backspace` moves to trash as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by levrik** [comment]
@isidorn Where's the duplicate?

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/68384

**Comment by levrik** [comment]
@isidorn Thanks! Will subscribe to it.
