### ISSUE TITLE
Multiple instances, same folder

### ISSUE THREAD

**Issue by parkerault** [Microsoft/vscode#69593]
PLEASE DON'T CLOSE: Every time someone creates a feature request for multiple _instances_ on a single _folder_ it gets closed and redirected to a feature request for multiple _windows_ on a single _instance_. I don't think these two features are equivalent. I have a large monitor and it takes me 10 minutes to set up my workspace with a particular editor grid containing certain types of files for my main project at work. Any time I need to do a screen share for a code review I have to close all of the editors and switch to a two editor vertical split (this would also be resolved if the extension API allowed saving and restoring sessions). I don't need detachable windows for this use case; it would be enough to have a separate full instance. Can we please track these feature requests separately?

**Comment by bpasero** [comment]
@parkerault why can you not use the command to duplicate the workspace into a new window:

![image](https://user-images.githubusercontent.com/900690/53639840-ac636980-3c2a-11e9-8303-be7a0bd9e228.png)

?

**Comment by parkerault** [comment]
What the... when did that become available?? I'm sure I combed every command looking for something like that!

**Comment by bpasero** [comment]
@parkerault 

> 
when did that become availabl

2016 or 2017 something
