### ISSUE TITLE
Switch Window command does not respect Snap windows

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#69597]
- VSCode Version: 1.31 Stable and 1.32 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a VSCode instance with any folder/workspace
2. Snap this window to right (`Win + Right`)
3. Open another VSCode instance with any other folder/workspace
4. Snap this window to left (`Win + Left`)
5. Now you have two VSCode instances side by side
6. In any of those windows, execute the `Switch Window` command and choose _the other_ window
7. The _other_ window looses its Snapped state, being restored to a normal state. It should not restore the window, but simply focus the other window, just like `Alt + Space` does

Does this issue occur when all extensions are disabled?: Yes

**Comment by alefragnani** [comment]
Different issue from the bot link, but possibly the same or a similar root cause.

**Comment by Tyriar** [comment]
@sbatten the switch window command unsnaps the window, might be something to do with the title bar?
