### ISSUE TITLE
"Open with Code" fails to open file with spaces

### ISSUE THREAD

**Issue by DanielSchmitt94** [microsoft/vscode#69591]
Issue Type: <b>Bug</b>

Reproduce:
- generate file with a space of type bat, for example "test file.bat"
- open context menu and click on edit
- vs code opens two tabs with "opened files" 'test' and 'file.bat'

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-angular2-files|ale|1.6.2
tslint|eg2|1.0.43
gitlab-workflow|fat|2.0.1
dotnet-test-explorer|for|0.6.3
vscode-firefox-debug|hbe|1.7.6
latex-workshop|Jam|6.0.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.6
Angular-BeastCode|Mik|7.2.5
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1256
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.5.2
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.5
vim|vsc|1.1.0
markdown-pdf|yza|1.2.0

</details>

**Comment by adamtajti** [comment]
Unable to reproduce. VS Code opens a single `test file.bat` tab for me.

```
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
OS: Windows_NT x64 10.0.17134
```
