### ISSUE TITLE
install-extension is case insensitive while unintsall-extension is case sensitive

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6959]
I would expect that both are case senstive, or both are case insensitive for consistency.

![screen shot 2016-05-27 at 11 46 32](https://cloud.githubusercontent.com/assets/1926584/15604442/aee8dfcc-2400-11e6-91c5-a94ff28ae19a.png)

**Comment by joaomoreno** [comment]
This is OK.

**Comment by isidorn** [comment]
Then your message is wrong in that case
![screen shot 2016-05-27 at 11 51 20](https://cloud.githubusercontent.com/assets/1926584/15604560/5df5421c-2401-11e6-921a-75117dbe9932.png)

**Comment by joaomoreno** [comment]
Still OK.

**Comment by isidorn** [comment]
We need to make `--install-extension` check that the ID has the right casing.

**Comment by joaomoreno** [comment]
Removed the disclaimer instead, since the marketplace is case insensitive after all...

**Comment by roslanr18** [comment]
Rnordin1000@gmail.cim
