### ISSUE TITLE
Ability to disable import completions in Java

### ISSUE THREAD

**Issue by goxr3plus** [Microsoft/vscode#69598]
I want auto completions for Java to show only Java methods and not import completions .... it's very messy : 

Messy **autocompletion** 

![untitled](https://user-images.githubusercontent.com/20374208/53572817-cb9fbf80-3b74-11e9-938b-89596cb9a82d.png)

Like for TypeScript https://github.com/Microsoft/vscode/issues/37711

**Comment by mjbvz** [comment]
Please file this against the Java extension
