### ISSUE TITLE
Quick open widget doesn't acknowledge tree.reveal(...) as a promise

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#696]
There are many calls to tree.reveal(), which all return promises, that are never `then`-ed:
- https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L346
- https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L546
- https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L555
- https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L562

**Comment by bpasero** [comment]
@joaomoreno I fixed those but I see many more in other places, including the tree itself:

![image](https://cloud.githubusercontent.com/assets/900690/11423584/f310c070-9445-11e5-84f4-4bb47b02e0d4.png)

**Comment by joaomoreno** [comment]
![omglob](http://vignette1.wikia.nocookie.net/totaldramaisland/images/a/a0/Oh_my_Glob.gif/revision/latest?cb=20130302230724)

**Comment by isidorn** [comment]
@joaomoreno I guess these are fine?

![screen shot 2015-12-16 at 12 28 19](https://cloud.githubusercontent.com/assets/1926584/11839745/86db636e-a3f0-11e5-97ec-5dc638e4d921.png)

**Comment by isidorn** [comment]
Oopsy ofc they are fine you added a .done
