### ISSUE TITLE
Environment variables not expanding when debugging tests in vscode

### ISSUE THREAD

**Issue by anant-barlota** [Microsoft/vscode#69601]
I am trying to debug tests in golang.
This is my launch.json
```   
 "configurations": [
        {
            "name": "Launch test package",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "envFile": "${workspaceFolder}/.vscode/debug.local.env",
            "program": "${workspaceFolder}/modules/helper",
            "showLog": true
        },
```

This is my debug.local.env
```
GOPATH=/home/user/go
PATH_TO_SAMPLE_KEY=${GOPATH}/sample_key.pub
PATH_TO_MY_REPO=${GOPATH}/myrepo
```

When I begin my debugging, `os.Getenv("PATH_TO_SAMPLE_KEY")` gives me `${GOPATH}/sample_key.pub` - the literal string and doesn't expand ${GOPATH}.

I want it to be `/home/user/go/sample_key.pub`

**Comment by weinand** [comment]
The format of .env files is not defined by VS Code but by this node module: https://www.npmjs.com/package/dotenv
It does not support "${...}" variables.
You might want to file a feature request against "dotenv".
