### ISSUE TITLE
Call stack: ensure thread status is displayed when label is long

### ISSUE THREAD

**Issue by marvingreenberg** [Microsoft/vscode#69606]
When debugging a java process, and presumably in other situations, the displayed thread label may overflow the current size of the stack frame window.  It isn't that obvious what the state of the running debug session is in that case.

![no_label](https://user-images.githubusercontent.com/216707/53584565-e0b72700-3b51-11e9-8022-2f83e3d198fe.png)

Expanding the call stack window way out shows the state.

![far_right](https://user-images.githubusercontent.com/216707/53584774-591de800-3b52-11e9-84a3-f3ba6a767c98.png)

It seems that a relatively minor CSS fix (if there is such a thing) like max-width:80%  on something would allow the thread state to always be displayed in the call-stack.

&lt;edit&gt; fixed to say "thread state"

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68276
