### ISSUE TITLE
StatusBar keeps displaying "Activating Extensions" after I downloaded and installed extensions with Setting-Sync.

### ISSUE THREAD

**Issue by ConAntares** [Microsoft/vscode#69607]
- VSCode Version: 1.31.1
- OS Version: Linux x64 4.15.0-29deepin-generic

If I download and  install my settings and extensions with the extension: Setting-Sync, the extensions can't work. StatusBar keeps displaying "Activating Extensions" if I try to launch any extension.
Although it works well in windows10, I can't use VScode in Linux-Deepin.

**Comment by sandy081** [comment]
Does it happen only when syncing extension using the Settings-Sync extension? Did you try installing the extensions manually (without using Sync extension)?

**Comment by ConAntares** [comment]
Yes, only after using Setting-Sync will my VScode break down. but, there are too many personalized settings in my configuration file. i have to use this kind of extensions.

**Comment by sandy081** [comment]
Can you please file an issue against Settings Sync extension, it could be the extension might be aware of this issue already.

**Comment by ConAntares** [comment]
It is found that once I install the older version(1.30), all extension work well. I can't upgrade it to 1.31.
I have done this experiment many times without the extension Setting-Sync.
So I think it may be not related to this extension.

**Comment by ConAntares** [comment]
OK, I have resolved this problem, thank you very much.

**Comment by sandy081** [comment]
@ConAntares May I know what was the issue and how it got resolved?

**Comment by ConAntares** [comment]
I found I was wrong about it. Just because I'm too impatient.
After a 40-minutes of waiting for the first time, the VSCode(1.32) can be used normally.
