### ISSUE TITLE
VS Ubuntu 18.04 install: missing libX11-xcbso.1

### ISSUE THREAD

**Issue by rufellouis** [Microsoft/vscode#69600]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rufellouis** [comment]
installing VS 1.31 onto Ubuntu 18.04 and cannot complete the install due to a missing library: libX11-xcbso.1
Attempted to fix this, find library, and reset PATHs, all to no avail.  Cannot successfully install VS onto my digitalocean VPS.

**Comment by Tyriar** [comment]
@rufellouis how did you install VS Code?
