### ISSUE TITLE
Scrolling not smooth after minimizing and maximizing window

### ISSUE THREAD

**Issue by BrandonShockley** [microsoft/vscode#69609]
Issue Type: <b>Bug</b>

1. Open VSCode
1.1 Scrolling is smooth
2. Minimize VSCode
3. Maximize VSCode
3.1 Scrolling is no longer smooth. Scrolls a set amount of lines each time.

Can be fixed by resizing the window.

Still occurs with extensions disabled.

I am using a laptop touchpad.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|1.0.0
python|ms-|2019.2.5433
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
veriloghdl|msh|1.0.1
java|red|0.39.0
shader|sle|1.1.4
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by BrandonShockley** [comment]
The Windows exploration build fixes the issue for me.

**Comment by BrandonShockley** [comment]
Do you know when the electron upgrade will find its way into the release build?

**Comment by PhyscoKillerMonkey** [comment]
I was also experiencing jumpy scrolling when un-minimising a maximised window. It was previously fixed by the `"window.smoothScrollingWorkaround": true` from issue #13612 but as the workaround was removed I've been experiencing it again.

Can confirm that that exploration version fixes the issue. Maximise - minimise - un-minimise and scrolling is still smooth.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
