### ISSUE TITLE
Add option to only show editor actions on hover

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#69605]
For those wanting a more minimal look, it would be great to have an option to hide the editor actions except when you hover over the tab area. Suggestion:

![gif](https://user-images.githubusercontent.com/35271042/53584408-5c0bdf00-3b38-11e9-9af5-dbdfe2575a33.gif)

**Comment by Astrantia** [comment]
Why wasn't this suggested before? Add to March milestone!
