### ISSUE TITLE
Rename file does now allow me to word part navigate

### ISSUE THREAD

**Issue by bj97301** [Microsoft/vscode#69617]
- VSCode Version:
Version 1.31.1 (1.31.1)
- OS Version:
osx: 10.14.3
Steps to Reproduce:

1. rename a file
2. try to ctrl+alt+arrow around the words

Expected: 
The text jumping shortcut keys should work in more than just the editor. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![nowordpartnavigation](https://user-images.githubusercontent.com/1450431/53658739-8203b300-3c0e-11e9-92b2-a8a0017e6bb4.gif)

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by bj97301** [comment]
Yep.  Added gif to illustrate.

**Comment by bj97301** [comment]
Just found this bug: https://github.com/Microsoft/vscode/issues/53498 will upvote and close this one.
