### ISSUE TITLE
Searching for text inside exact path does not work

### ISSUE THREAD

**Issue by edespong** [Microsoft/vscode#69611]
Issue Type: <b>Bug</b>

1. Opened vscode with folder c:\Code\vscode
2. Trying to search (Ctrl+Shift+F) for a string, 'text'.
3. Include pattern: c:/Code/vscode/src/vs/workbench/api/electron-browser/mainThreadSearch.ts

#### Expected result
At least a couple of hits

#### Actual result
Search fails with 'spawn c:\Users\erik\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT'

#### Additional information
The following two include patterns give the expected result
* c:/Code/vscode/src/vs/workbench/api/electron-browser/mainThreadSearch.t*
* src/vs/workbench/api/electron-browser/mainThreadSearch.ts

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by roblourens** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/48958
