### ISSUE TITLE
"Go to definition" on symbol with multiple definitions does not navigate to the first item, and the first item can't be opened

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#69613]
Forking this from https://github.com/Microsoft/vscode/issues/68469

- Put the cursor on `onDidChangeSelection` here: https://github.com/Microsoft/vscode/blob/0a4a3b98282175a82a819b70d2bbe46475e1ebd0/src/vs/platform/list/browser/listService.ts#L694
- Press F12
- Peek view opens with two definitions, one is already selected

In stable, at this point the editor navigates to that selected definition. In Insiders, it does not navigate.

- Press enter

In stable, the peek view closes. In Insiders, nothing happens. So there is no way to navigate to that selected item from the keyboard. If I double click on the row, then the editor navigates to it.

**Comment by roblourens** [comment]
Actually I don't think this is a tree thing, I think it's from changes here: https://github.com/Microsoft/vscode/blame/master/src/vs/editor/contrib/goToDefinition/goToDefinitionCommands.ts#L133

**Comment by jrieken** [comment]
That fact that it stays is https://github.com/Microsoft/vscode/pull/68023 and based on popular request, still it should go to the first location when pressing enter or when double clicking

**Comment by jrieken** [comment]
> So there is no way to navigate to that selected item from the keyboard. If I double click on the row, then the editor navigates to it.

@roblourens pressing Enter works for me. Do you recall on what symbol you tried this?

**Comment by jrieken** [comment]
Nevermind, I can repro with your steps

**Comment by jrieken** [comment]
So, the problem actually is the tree not sending another selection event. The item is already selected (via code) and when selected again via a user-gesture nothing happens. @joaomoreno that's very similar to the double click issue. I can see if I can workaround this but we might need a fix in the tree

**Comment by jrieken** [comment]
This needs a "real" fix

**Comment by joaomoreno** [comment]
@roblourens Uff that "selection event should not fire if selection doesn't change" already had quite some repercussions...

**Comment by joaomoreno** [comment]
Yup, definitely related to https://github.com/Microsoft/vscode/issues/69439. My fix https://github.com/Microsoft/vscode/commit/fae3d67f59b76c040d20341027cd3186382146ea was only half the story. We should have listened to the `open` event, not to double click. My bad!

**Comment by jrieken** [comment]
👏 thanks, didn't know we can already trust the `open`-thing

**Comment by joaomoreno** [comment]
We're slowly getting there!
