### ISSUE TITLE
Split terminal when using a compound debug configuration

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#69619]
When using a compound debug configuration, each task gets its own terminal. I can split these terminals manually, but I don't think there is a way to get these terminals side-by-side. And I don't think this is doable with an extension either. There is a split terminal API proposal in #45407 but applying that to both of the task terminals would just give me two extra empty terminals. I am looking for a way to get the two task terminals side-by-side in one integrated terminal pane so there is no need to switch between them. The way I'd like to see this done is an extra field in the debugger configuration which says whether the terminals should start standalone or split. I am not sure how this would deal with 3+ configurations, but that seems to be niche enough to not have to worry about it until an issue is raised.

**Comment by TomasHubelbauer** [comment]
@vscodebot you try but as usual you don't help.

- #62815 deal with two different panes, output and integrated terminal, I care about two terminals within the single integrated terminal pane
- #67704 is a completely unrelated integrated terminal error
- #45444 is interesting, nice tip, but still completely unrelated
- #45422 is kind of related as it also deals with splitting terminals by default, but in a different context (window open versus compound debugging started)
- #47265 is actually close, I am impressed - this seems to have been implemented, so maybe if the individual tasks of the compound configuration both defined a task group, they will open in a splt terminal? Who knows, I'll try that and see.

**Comment by TomasHubelbauer** [comment]
Okay so @vscodebot mentioned #47265 which according to my reading of it should make it so that setting a `group` field on both tasks, in this case prelaunch tasks, should make them open split side by side.

This has not been something that I was able to demonstrate, and also this field seems to not be free form, but a closed set of values instead.

My repro here: https://github.com/TomasHubelbauer/vscode-compound-debug-split-terminal

**Comment by TomasHubelbauer** [comment]
Actually I think I might have duplicated #68123 which I did not find when searching. @markfinlabs do you feel like your issues covers this use case as well? If yes, I'll be happy to close mine.

**Comment by markfinlabs** [comment]
Yes I believe so. My use case is multiple (in my case more than 2) launch configs in integrated terminals and I am keen to see them side-by-side in a split terminal following starting a compound launch configuration. Which I believe covers your use case as well.
