### ISSUE TITLE
Ajuste de Ventanas

### ISSUE THREAD

**Issue by erickmarcia** [Microsoft/vscode#69618]
Issue Type: <b>Feature Request</b>

Al momento de querer expandir las ventanas o secciones de la barra lateral, las cuales muestran los editores abiertos, como las estructuras de trabajo, etc, la primera no permite ajustarse al tamaño deseado, las demás secciones de la barra lateral si, adjunto una captura del comportamiento.

VS Code version: Code - Insiders 1.32.0-insider (0a4a3b98282175a82a819b70d2bbe46475e1ebd0, 2019-02-28T06:18:12.644Z)
OS version: Windows_NT x64 10.0.17134
[video vscode](https://github.com/erickmarcia/erickmarcia.github.io/blob/master/images/Blog/vscode/vscode.mp4)

**Comment by rebornix** [comment]
@erickmarcia can you post the question/issue in English and then I can better understand the issue you run into.
