### ISSUE TITLE
Error New golang 1.12 and vscode 1.31.1

### ISSUE THREAD

**Issue by ignusius** [Microsoft/vscode#69615]
/home/komar>Finished running tool: /home/komar/golang/go/bin/go build -i -o /tmp/vscode-gou3MimR/go-code-check .

/home/komar>Finished running tool: /home/komar/golang/go/bin/go vet ./...
/home/komar/golang/go/misc/cgo/testcarchive/src/libgo/libgo.go:13: cannot find package "p" in any of:
/home/komar/golang/go/misc/cgo/testplugin/altpath/src/plugin-mismatch/main.go:13: cannot find package "common" in any of:
/home/komar/golang/go/misc/cgo/testplugin/src/iface/main.go:8: cannot find package "iface_i" in any of:
/home/komar/golang/go/misc/cgo/testplugin/src/issue18676/main.go:20: cannot find package "issue18676/dynamodbstreamsevt" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/dep2/dep2.go:3: cannot find package "depBase" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/dep3/dep3.go:10: cannot find package "dep2" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/exe3/exe3.go:3: cannot find package "dep3" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/explicit/explicit.go:4: cannot find package "implicit" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/global/main.go:8: cannot find package "globallib" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/iface/main.go:7: cannot find package "iface_a" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/iface/main.go:8: cannot find package "iface_b" in any of:
/home/komar/golang/go/misc/cgo/testshared/src/implicitcmd/implicitcmd.go:4: cannot find package "explicit" in any of:
/home/komar/golang/go/test/fixedbugs/bug050.go:7: expected 'package', found 'func'
/home/komar/golang/go/test/intrinsic.dir/main.go:9: use of internal package runtime/internal/sys not allowed
/home/komar/golang/go/test/syntax/import.go:10: expected ';', found ','

**Comment by rebornix** [comment]
The issue seems not related to VS Code, please either file issue with the Go extension you are using or checking if the library you are using.
