### ISSUE TITLE
Opening a Existing Maven Folder with Open Workspace does not work

### ISSUE THREAD

**Issue by JimTyrrell** [Microsoft/vscode#69616]
Same issue with the 1.32.0-insider

- VSCode Version: 1.31.11
- OS Version: OS X 10.13.6

Steps to Reproduce:

1.  Have a valid Java Maven project in a folder
2.  Try to open it with the Open Workspace File menu
3.  See that you just keep opening folders and files w/o being able to open the Maven Workspace
4.  Against other Java editors this doesn't feel right

W/o some guidance how does a user know they shouldn't be doing this.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gorkem** [comment]
This is not caused by an extension. Users are simply confused by having two Open menus? One labeled `Open` and one labeled `Open Workspace`. I think you should just remove `Open Workspace` and make `Open` action recognize workspace files.

**Comment by fbricon** [comment]
@bpasero Open Workspace has a different meaning for someone coming from an Eclipse background, it's unclear it means you need to open a workspace *file*

**Comment by bpasero** [comment]
Oh ok, sorry I was not understanding this issue correctly then. VSCode is file/folder centric, we always allow you to open files/folders via the "File > Open" entry. We added the "Open Workspace" entry to allow to open VSCode workspaces.

**Comment by JimTyrrell** [comment]
@bpasero How would a new user know that Open Workspace would not work on a Maven centered Java project?  Guessing other projects like node, javascript and others should just work to ease a new users experience with this amazing tool!!!  Can't we just map Open Workspace to Open.  Or add the words Open VS Workspace or VS Workspace Open.

Can we please reopen this issue?

**Comment by bpasero** [comment]
I think we document this quite well: https://code.visualstudio.com/docs/editor/multi-root-workspaces
