### ISSUE TITLE
Desconfiguración de TERMINAL de VSCode en Ubuntu 18

### ISSUE THREAD

**Issue by irv-ro-j** [Microsoft/vscode#69621]
La terminal de Visual Studio no habilita la configuración utf-8 por lo que imprimir carácteres que no sean Unicode genera un error, la actualización anterior no tenía ese error

**Comment by Tyriar** [comment]
What's the error? Can you attach a screenshot and your settings.json file?

**Comment by t31060** [comment]
> La terminal de Visual Studio no habilita la configuración utf-8 por lo que imprimir carácteres que no sean Unicode genera un error, la actualización anterior no tenía ese error

Si tienes vscode en modo español, se presentan errores también con la interfaz, algunas letras con acento cambian por signos '??' y la terminal cambia de encoding, también desaparece la ayuda de default settings en modo json. Para regresar la terminal a UTF-8 puedes ir a 
ctlr+shift+p > Configurar Idioma de pantalla 
y cambiar el valor de locale por en-us o en-US, sin embargo eso cambia toda la interfaz a inglés.

**Comment by irv-ro-j** [comment]
> > La terminal de Visual Studio no habilita la configuración utf-8 para que pueda imprimir los caracteres que no son Unicode genera un error, la actualización anterior no tenía ese error
> 
> Si tienes vscode en modo español, se presentan errores con la interfaz, algunas letras con acento cambian por signos '??' y la terminal cambia de codificación, también desaparece la ayuda de la configuración predeterminada en modo json. Para regresar a la terminal a UTF-8 puede ir a 
> ctlr + shift + p> Configurar Idioma de pantalla 
> y cambiar el valor de locale por en-us o en-US, sin embargo eso cambia toda la interfaz a inglés.

Ya pude solucionarlo, era solo una configuración que no tuve que configurar al principio. En settings existe una opción  llamada "Integrated:Set Locale Variables", la casilla estaba marcada como habilitada en la actualización y en la anterior versión no lo estaba. Igualmente el no saberlo me quitó tiempo de programación, pero por lo menos que quede aquí por si a alguien más le pasa. Gracias

**Comment by irv-ro-j** [comment]
> What's the error? Can you attach a screenshot and your settings.json file?

Ya pude solucionarlo, era solo una configuración que nunca tuve que configurar y no sabía que existía. En "settings -> Preferences -> Terminal" existe una opción llamada "Integrated:Set Locale Variables", la casilla estaba marcada como habilitada en la última actualización y en las versiones anteriores no lo estaba. Provocaba que la terminal integrada de VSCode no tomara la configuración del terminal por defecto de Ubuntu y la terminal que estableció VSCode no tenia configuración utf-8, por lo que la impresión de todos los carácteres especiales causaba un error "unicode encode error"

**Comment by Tyriar** [comment]
@irv-ro-j @t31060 glad to hear it's fixed, what platform are you on for future reference?

**Comment by Tyriar** [comment]
Glad to hear you fixed it 👍
