### ISSUE TITLE
conpty terminal: `clear` doesn't always manage to clear the screen in a WSL terminal

### ISSUE THREAD

**Issue by 0xabu** [Microsoft/vscode#69625]
Issue Type: <b>Bug</b>

 * I'm using conpty on Windows 18342.19h1_release, and running a WSL shell inside it.
 * I have a fancy prompt that calls out to git while rendering the prompt. This takes a small but non-negligible time.
 * As a result, I can hold down the enter key, and repeat newlines faster than the shell/terminal can render new prompts. This results in some extra visual whitespace:
  ![image](https://user-images.githubusercontent.com/13037682/53605467-6cd64800-3b6c-11e9-8383-18b77977488c.png)
 * Often, when I run the shell command `clear` after some of this has happened, the terminal moves the cursor to the top of the window but doesn't actually clear the display:
  ![image](https://user-images.githubusercontent.com/13037682/53605637-fb4ac980-3b6c-11e9-9855-ea0af231d26e.png)
   (In the image above, I used `alias c=clear` to make the race that triggers this easier to hit -- essentially holding down enter for a while until enough newlines are buffered, then typing c, enter while the shell is still rendering the prompts from the previous newlines.)
 * In this state, the visible characters below the cursor copy and paste as empty newlines. i.e. the terminal's visual and textual representations appear to be inconsistent with each other.
 * Also in this state, clearing the window again has the same result -- the stale contents remain until the cursor legitimately moves down below the inconsistent area.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18342

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
@0xabu could you try this again on the latest Insiders build and also enable escape sequence logging and check the devtools console for what is send exactly when you run `clear`?

![image](https://user-images.githubusercontent.com/2193314/53606526-f9363a00-3b6f-11e9-9e99-400a1f30bfda.png)

**Comment by 0xabu** [comment]
I haven't been able to repro it on the insiders build -- I guess it's fixed, so apologies for the noise.

FTR, here's what `clear` produces:
```
 ~ > echo $TERM
xterm-256color
 ~ > clear | hd
00000000  1b 5b 33 4a 1b 5b 48 1b  5b 32 4a                 |.[3J.[H.[2J|
0000000b
```

And here's the console for 1.31.1:
![image](https://user-images.githubusercontent.com/13037682/53607696-b591ff00-3b74-11e9-9f7f-57756b8f9d1e.png)

That last input repeats for ages, and is followed by a load of "Unknown CSI code" errors. The console output on the insiders build is much shorter:
![image](https://user-images.githubusercontent.com/13037682/53607765-073a8980-3b75-11e9-9593-c57544ac8818.png)

**Comment by Tyriar** [comment]
Cool! My suspicion is that it's related to https://github.com/Microsoft/vscode/issues/68721
