### ISSUE TITLE
GDB C/C++ debugger won't start, giving error

### ISSUE THREAD

**Issue by GnedStark** [Microsoft/vscode#69626]
- VSCode Version: 1.31.1
- OS Version: Windows 10 v. 1809

Steps to Reproduce:

1. Attempt debug
2. Debug then fails

Here's my launch.json

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "%{workplaceFolder}/a.out",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\MinGw\\bin\\gdb.exe",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}

**Comment by weinand** [comment]
Please provide information how debugging fails.
And there is a '%' in the value for "program". That must be a '$'.
