### ISSUE TITLE
NullReferenceException during gdb launch on 1.31.1

### ISSUE THREAD

**Issue by GnedStark** [Microsoft/vscode#69627]
- VSCode Version: 1.31.1
- OS Version: Windows 10 v. 1809

Steps to Reproduce:

1. Attempt to debug
2. An error occurs on startup

Here's a screenshot with my launch.json open 
I've tried turning on/off externalConsole but It still crashes. I'm trying to debug a C++ file.
I'm sorry if I'm leaving out information, this is my first post on Github.
![image](https://user-images.githubusercontent.com/48109759/53609347-209b0000-3b8c-11e9-8bfa-cd60175d03b6.png)

**Comment by rebornix** [comment]
Please file issue to extensions which contribute gdb debugging feature.
