### ISSUE TITLE
Add option to set diff editor color for each use, not globally

### ISSUE THREAD

**Issue by kisantia** [microsoft/vscode#69629]
I'm creating an extension and need to set the colors when my extension opens the vs code diff editor.

I know that there the diffEditor.insertedTextBackground and diffEditor.removedTextBackground settings, but I only want the colors changed in my extension and have the default diff colors be used if the user was diffing a file.

**Comment by aeschli** [comment]
We currently have no plans to provide an API for editor specific colors...
