### ISSUE TITLE
Undo overwrites file after many undos

### ISSUE THREAD

**Issue by Fyreye** [microsoft/vscode#69630]
- VSCode Version: 1.25.1
- OS Version: Windows 10 pro v1803

discovered when working on html and js code: used undo to check a change made and when going back to present file stopped undoing and checking the browser cashed version via dev tools in chrome vs view source reveals version conflict
Steps to Reproduce:

1. work on code with many undo breakpoints
2. undo back to beginning of time
3. redo only returns so much time, file is changed to undone version of code

**Comment by rebornix** [comment]
We do have a limit for the undo/redo stack, which may be full when dealing with too many undo/redos.
