### ISSUE TITLE
[bug][file icon] Path intellisence shows the wrong icon

### ISSUE THREAD

**Issue by muzea** [microsoft/vscode#69637]
Version: 1.32.0-insider
Commit: 0a4a3b98282175a82a819b70d2bbe46475e1ebd0
Date: 2019-02-28T21:15:52.439Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-29deepin-generic

![image](https://user-images.githubusercontent.com/7843281/53620798-33b2dc00-3c2f-11e9-97b6-bd565ac40f25.png)

But in the Explorer is correct

![image](https://user-images.githubusercontent.com/7843281/53621077-44178680-3c30-11e9-9b9d-d6bc4580306a.png)

May be the file extension is ignored when calculating the file icon

https://github.com/Microsoft/vscode/blob/master/extensions/theme-seti/icons/vs-seti-icon-theme.json#L1428

Steps to Reproduce:

1. create a file called `Mix.tsx`
2. import `Mix.tsx` in another file

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
What icon does that file have in the file explorer?

**Comment by muzea** [comment]
@mjbvx The first picture is path intellisence showing the wrong icon, the second picture is the correct icon inside the Explorer.

**Comment by muzea** [comment]
ping @mjbvz

**Comment by mjbvz** [comment]
@muzea What if you just have a file called `Mix` (no suffix) in the file explorer?

**Comment by muzea** [comment]
@mjbvz 
![image](https://user-images.githubusercontent.com/7843281/53927303-62163880-40c1-11e9-8b38-57f3622e3ab8.png)

**Comment by mjbvz** [comment]
@jrieken How do you recommend that we handle this case? I think that we'd like to keep the completion label without the extension since that is what is inserted when you accept the completion

**Comment by jrieken** [comment]
Hm... we do use both, label and detail for this icon computation. See https://github.com/Microsoft/vscode/blob/ac5ef12529b233e2262574c7057e5724d91619da/src/vs/editor/contrib/suggest/suggestWidget.ts#L177-L178. So, you could try adding the full name as detail

**Comment by mjbvz** [comment]
I believe we do set `detail` to the full path with the extension, it seems that the classes from `label` just end up overriding them. Here's the complete set of classes we add currently:

```
["file-icon", "mix-name-file-icon", "ext-file-icon", "file-icon", "mix.ts-name-file-icon", "ts-ext-file-icon", "ext-file-icon", "typescript-lang-file-icon"]
```

**Comment by jrieken** [comment]
Hm... Not sure if changing the order would help, e.g. getting the icon classes from details first, then from the label. @aeschli, aka mr. icon, can you advise.

**Comment by aeschli** [comment]
d I'm not sure if there's any benefit by mixing the classes for label and details. One will win, but if both have the same number of classes, it's kind of random which one. It depends on the order we generate the css (which depends on the theme)
What about preferring details over label if label is a substring of details?

**Comment by jrieken** [comment]
> I'm not sure if there's any benefit by mixing the classes for label and details. [...] What about preferring details over label if label is a substring of details?

The mixing is such a strategy of not knowing where to read stuff from. @aeschli best would be if I would know that a label matched an icon style, e.g. didn't fall back to the default icon. Would that be possible?

**Comment by aeschli** [comment]
You can tell from the number of classes it returns. The more classes, the more specific the match was.
File < Extension < Language < File Name
But for this example, both label and details are quite specific: `Mix` happens to match a file name (as defined by the Seti theme) `Mix.tsx` matches a language.
