### ISSUE TITLE
+13.6MB extracted size, +3.7MB zip size in 1.2.0

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6963]
Comparing the latest alpha build with the latest insiders build

![image](https://cloud.githubusercontent.com/assets/5047891/15605574/1426ff9e-2407-11e6-8e2b-c042c6b6ad47.png)

![image](https://cloud.githubusercontent.com/assets/5047891/15605597/3560ed0a-2407-11e6-95c1-fb52be40163a.png)

Most of the extra size comes from `node_modules\pty.js` at 13MB.

Our build scripts contain some smartness where we've removed debug symbols from the C++ node modules we use. https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L206

Can we do the same for `pty.js`?

@joaomoreno @Tyriar

**Comment by joaomoreno** [comment]
Great catch.

**Comment by alexandrudima** [comment]
Nice!

**Comment by Tyriar** [comment]
@joaomoreno how much was saved from cleaning them?

**Comment by joaomoreno** [comment]
Well `pty.js` is now `~600KB` in Windows... so `~12.4MB`.

**Comment by Tyriar** [comment]
I approve :smile: :+1:
