### ISSUE TITLE
Save not auto formatting and causing error in developer tools.

### ISSUE THREAD

**Issue by goldingdamien** [Microsoft/vscode#69635]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
Saving.

Causes the warning/error below:
WARN Error: listener failed   log.ts:167
    at mainThreadSaveParticipant.ts:394
    at process._tickCallback (internal/process/next_tick.js:68)

Is this stopping the auto-formatting? Any idea on what causes it?

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Since this only happens when you have extensions enabled, try tracking down which one is causing this. Use the `Developer: Show Running Extensions` to see which extensions are active when the issue occurs

**Comment by eymerich** [comment]
Happens to me on 1.33 (previous versions too).
Extension used for auto-formatting is: junstyle.php-cs-fixer

    "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.rules": "@PSR2,no_trailing_whitespace,no_whitespace_in_blank_line,no_extra_consecutive_blank_lines,unary_operator_spaces,binary_operator_spaces",
    "[php]": {
        "editor.defaultFormatter": "junstyle.php-cs-fixer"
    },

I have noticed it happens when I save file frequently.
