### ISSUE TITLE
html format (golang template) 

### ISSUE THREAD

**Issue by xiaoyifan6** [Microsoft/vscode#69632]
Issue Type: <b>Bug</b>

1.  index.html
...
{{range .Socials}}
...
{{end}}
...

2. ctl+s
3. 
{{
        range.Categories
}}
...
{{
        end
}}

error: golang template, after format html file  {{range .Categories}} != {{range.Categories}}

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.3.2
flutter-snippets|ale|0.0.2
vscode-svgviewer|css|2.0.0
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
vue-format|feb|0.1.6
shell-format|fox|4.0.4
vue-snippets|hol|0.1.11
plantuml|jeb|2.10.5
solidity|Jua|0.0.49
dart-import|lua|0.1.2
vscode-filesize|mkx|2.1.2
language-gettext|mro|0.1.1
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.2.5433
cpptools|ms-|0.21.0
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
vetur|oct|0.16.2
java|red|0.40.0
startanyshell|rem|0.3.1
LiveServer|rit|5.5.1
vsc-nwjs|rua|1.0.17
html-preview-vscode|tht|0.2.5
shell-launcher|Tyr|0.3.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.14.2
markdown-all-in-one|yzh|2.1.0

</details>

**Comment by rebornix** [comment]
Please file issue against the Go extension you are using.
