### ISSUE TITLE
Causes 'Disable All Installed Extensions' to fail in VS Code (Regular and Insiders)

### ISSUE THREAD

**Issue by fourpastmidnight** [Microsoft/vscode#69643]
This extension prevents the option _Disable All Installed Extensions_ in Visual Studio Code because the other, newer extension, (hosted at https://github.com/Microsoft/vscode-node-debug2) "depends" on this extension, and apparently, this extension is attempted to be disabled first.

Actually, perhaps this is more of a bug for VS Code itself? IOW, VS Code should take into account extension dependencies when attempting to disable extensions and ensure that they are disabled in the correct order? (And perhaps even alert the user that "The 'xyz' extension will also be disabled because it depends on this 'abc' extension. Continue: Yes / No?")

**Comment by weinand** [comment]
@sandy081 I think this is a valid concern. This issue was initially filed against node-debug.

**Comment by fourpastmidnight** [comment]
It gets worse. I tried to disable another extension, a plugin to VS Code Test Explorer extension for Python tests. Nope, it depends on Python. Ok, I go to disable Python. Nope, an Azure extension depends on that. Ok, let's disable that, too. Nope, the Azure Extension Pack requires it. Yikes.

This really does seem more of an issue for VS Code rather than the extension itself. VS Code should also treat Extension Packs a bit differently, allowing constituent extensions to be individually disabled. (Barring any dependencies, of course, but that's more about the extension being disabled than about the entire extension pack. IOW, extension packs are just containers, nothing more?)

**Comment by sandy081** [comment]
@fourpastmidnight Node debug extensions are built in extensions are not disabled when you perform the action - Disable all Installed Extensions.

Did you have node-debug extension installed from Marketplace? Can you please open your extensions folder (use command `Open Extensions Folder`) and check if it contains node-debug extension.
