### ISSUE TITLE
User JSON Settings

### ISSUE THREAD

**Issue by kingeke** [Microsoft/vscode#69642]
Issue Type: <b>Feature Request</b>

Please please please, I would like the default JSON user setting to return the way it was, where we could see the default settings then decide on what we wanted to change and it'll copy them to our current settings, it was simpler that way, now i don't see that anymore, and it's harder to find a setting i want to change

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
/duplicate

https://github.com/Microsoft/vscode/issues/64932#issuecomment-462959522
