### ISSUE TITLE
Lost all User/ settings in VS Code (extensions, keybindings are gone)

### ISSUE THREAD

**Issue by lexishanson** [Microsoft/vscode#69641]
I was updating my `keybindings.json` file, and my VS Code program started to lag. I got a prompt to refresh my editor to make my settings take effect. After I clicked to refresh, my `keybindings.json` file was almost completely empty. I found it fell back to a version from over a year ago, that happened to be backed up from the Settings Sync extension. I never used that extension since its initial sync.

After further investigation, I realized that all of my User/ data is gone. My keybindings, extensions, and my `settings.json` config all reset back to what data was there over a year ago.

While this could be something to do with Settings Sync, my strong suspicion is that something went wrong in VS Code, and Settings Sync was able to at least provide the last information it had.

Has this been reported by anyone else, and more importantly is there a built-in way for me to recover my settings?
 

- VSCode Version: Version 1.31.1 (1.31.1)
- OS Version: High Sierra 10.13.6 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
VSCode itself will not touch your user data directory, so I am assuming this is due to the extension you mention.
