### ISSUE TITLE
Color icon is not shown when a color value selected in CSS

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#6964]
- VSCode Version: Alpha
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Open a CSS file
2. Under a rule set, type a rule say color: red;

**Expected:** To see the red icon before red label
**Actual:** Not seeing any color icon

**Additional Information:** Color icon is getting rendered if I reopen the file or tabbing to another file and tabbing to the css file.

**Comment by sandy081** [comment]
@aeschli I am wondering if it used to work before

**Comment by sandy081** [comment]
I checked and it is a regression. It is working as expected here - 5d2d6530905ed13c6d534c3c8a020f650d7ac015

**Comment by aeschli** [comment]
@alexandrudima Alex, can you have a look? 8913a2 introduces the problem.
The _contentChangedScheduler is no longer fired when typing.

**Comment by aeschli** [comment]
Adding
```typescript
						case editorCommon.EventType.ModelContentChanged2:
							this.emit(editorCommon.EventType.ModelContentChanged2, e);
							break;
```
in the comonCodeEditor.ts, line 860 seems to fix the issue.

**Comment by alexandrudima** [comment]
Yes, that is the problem. Great catch!

**Comment by sandy081** [comment]
Verified
