### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gianchub** [Microsoft/vscode#69659]
Issue Type: <b>Bug</b>

Hello,
I was searching for "json" in the extensions, and got a list of JSON related extensions. I then sorted by installs, and it seems I got the whole list of extensions again (as if the "json" search isn't done any more).
This is what I have in the search textbox: json @sort:installs

Kind regards,
Fabrizio

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
vsc-material-theme|Equ|2.7.0
gc-excelviewer|Gra|2.1.29
theme-monokai-pro-vscode|mon|1.1.10
python|ms-|2019.2.5433
csharp|ms-|1.17.1
vscode-docker|Pet|0.5.2
vscode-yaml|red|0.3.0
code-settings-sync|Sha|3.2.5
jinja|who|0.0.8

(9 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
It's because most of the top installed extensions are hits for `json` search and when you sort by installs you see them and it is pretty similar seeing all extensions sorted by installs. But if you observe keenly some top installed extensions like c# will be off the list for `json`.
