### ISSUE TITLE
Error installing vscode.d.ts: Error: Request returned status code: 500

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#69656]
build started to fail on Travis CI with 

```
Detected VS Code engine version: ^1.29.1
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error
```

it looks similar to a previously reported issue which was reported than fixed few minutes after: https://github.com/Microsoft/vscode/issues/36627

**Comment by jrieken** [comment]
Also happens locally for me

**Comment by joaomoreno** [comment]
Fixed now
