### ISSUE TITLE
Better shortcut for “Open Next Working Files”

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#6965]
The current shortcut for “Open Next Working Files” is `Cmd+K Down`, or `Cmd+K Up` for the reverse.

In other IDEs I am used to quickly switching between tabs aka working files with a single chord shortcut. Having a two chord shortcut for this slows me down quite a lot.

“Navigate Next in Quick Open” doesn't give me what I need here because the order is different from Working Files, and also it shows other recent files which are not currently in Working Files.

Would it be possible to improve this shortcut?

**Comment by bpasero** [comment]
For next milestone we plan to introduce stacks and tabs and I think this would cover your use case.

**Comment by OliverJAsh** [comment]
Hi, I'm using the Insiders release to trial the new “tabs” interface. I don't see a shortcut to go to the next file in an open editor?

**Comment by bpasero** [comment]
@OliverJAsh 
![image](https://cloud.githubusercontent.com/assets/900690/15890740/54048b72-2d71-11e6-862b-4bae1a64b85f.png)

**Comment by OliverJAsh** [comment]
Thanks!
