### ISSUE TITLE
Files served by readonly filesystem initially lack the '(read-only)' suffix on tab labels

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#69651]
- VSCode Version: 1.31.1 and 1.32.0-insider
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Obtain the MemFS sample (git clone https://github.com/Microsoft/vscode-extension-samples and then go to the fsprovider-sample subdir)
2. Edit package.json to require a newer version of vscode than the sample's default. I changed ```"vscode": "^1.23.0"``` to ```"vscode": "^1.31.0"```. This is necessary in order to get use of the isReadonly option on ```vscode.workspace.registerFileSystemProvider```
3. ```npm install``` in Terminal
4. Edit src/extension.ts to add that ```isReadonly: true``` to the options parameter.
5. F5
6. When Extension Development Host window opens, switch to it, press F1 and run 'MemFS: Setup Workspace', then F1 again and 'MemFS: Create Files'.
7. Switch to Explorer view.
8. Single-click on one of the files, e.g. file.js and observe that the tab caption lacks the '(read-only)' suffix.
![image](https://user-images.githubusercontent.com/6726799/53635715-e24a2300-3c15-11e9-9b1d-80fc8c0f0f76.png)

9. Try typing into the document and verify it is correctly read-only.
10. Doubleclick on the tab to persist it. The caption now gets the expected '(read-only)' suffix.
![image](https://user-images.githubusercontent.com/6726799/53636076-eb87bf80-3c16-11e9-9281-69fe2c2fa026.png)

Also notice the weird doubled-up '(read-only) (read-only)' on  the titlebar. Is this intentional?

**Comment by gjsjohnmurray** [comment]
@isidorn I had a go at fixing this issue. I think this is the line where the readOnly state is set on the editor:
https://github.com/microsoft/vscode/blob/22edad13ff5701fc1d5e07f0a7311881709c55bf/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L167

But until there's a repaint of the tab (a simple click on it is sufficient) it doesn't have the ' (read-only)' suffix.

I wasn't able to work out how to trigger this from code after the above line has updated the readOnly option of textEditor. If you can give me a pointer maybe I can submit a PR.

**Comment by isidorn** [comment]
@gjsjohnmurray do you still see this? If yes we should make a change [here](https://github.com/Microsoft/vscode/blob/d9a639a06b17eaecc76e5b82872c1667b30fb912/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L69)
What is missing it seems is the textFileService should have an event which fires when the model becomes readonly. fyi @bpasero

**Comment by gjsjohnmurray** [comment]
Actually, this just got worse in 1.39 - see #82964
