### ISSUE TITLE
Do not create a folder in start menu

### ISSUE THREAD

**Issue by brjsp** [microsoft/vscode#69650]
Issue Type: <b>Bug</b>

From the [Microsoft UI Fundamentals](https://docs.microsoft.com/en-us/previous-versions/ms954377\(v=msdn.10\)):

> Place your icon to launch your application directly under Start -> Programs. Avoid placing it in a folder under programs. In particular, do not create a folder in the Start menu in which you only put one item.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by adyavanapalli** [comment]
If I were to take this, any hints on how I would do this? Or maybe some resources that talk about folder structure?

**Comment by adyavanapalli** [comment]
@rebornix @bpasero @joaomoreno @brjsp 
Why was this issue closed? Has it been implemented already?

**Comment by Daniel-McCarthy** [comment]
@adyavanapalli This issue remains open. Another duplicate issue was closed and referenced to this one.

**Comment by adyavanapalli** [comment]
@Daniel-McCarthy
Understood. I have some interest in implementing this, but without guidance from the people referenced on this issue, I cannot start.

**Comment by joaomoreno** [comment]
Sorry but this won't happen any time soon, given the costly migration path.
