### ISSUE TITLE
Windows download page not found

### ISSUE THREAD

**Issue by Tony-HSU** [Microsoft/vscode#69653]
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. Go to website [https://code.visualstudio.com/Download](https://code.visualstudio.com/Download)
2. Download [https://update.code.visualstudio.com/latest/win32-user/stable](https://update.code.visualstudio.com/latest/win32-user/stable)

Does this issue occur when all extensions are disabled?: Yes

**Comment by zhaojingyits** [comment]
In Mainland China this problem occures too. Embarrassing.

**Comment by Sudamid** [comment]
Me too 👍 Hope MS can be faster to fix it!!!!

**Comment by Sudamid** [comment]
> Me too 👍 Hope MS can be faster to fix it!!!!

I am in China and using China Telecom.

**Comment by Sudamid** [comment]
What the hell with MS server???

**Comment by mrennix** [comment]
Also not working from Australia. None of the download links work. Just returns "Not Found".

**Comment by thatlittleboy** [comment]
Not working in Singapore as well.

**Comment by Sudamid** [comment]
VS Code for "Not Found"

**Comment by Sudamid** [comment]
Code editing.
Not Found.

**Comment by Zer0Lyfe** [comment]
this is also is happening to the other download pages like mac and linux (In Australia at least)

**Comment by papajames** [comment]
Also not found for Mac download page (in Taiwan)

**Comment by pravat85** [comment]
any idea when would the issue be fixed?

**Comment by AdsonCicilioti** [comment]
Also for me!! all versions

**Comment by Sudamid** [comment]
> any idea when would the issue be fixed?

Use Vim.

**Comment by makkes** [comment]
This is not only the case for the WIndows download but for Mac and Linux also:
```
mwerner:~ mwerner$ curl -I https://update.code.visualstudio.com/latest/darwin/stable
HTTP/1.1 404 Not Found
Content-Length: 9
Content-Type: text/plain; charset=utf-8
request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c
X-Powered-By: Express
Strict-Transport-Security: max-age=31536000
X-Source-Commit: ac58393a9add3e00938f89cac90d4c9e8fe80945
Set-Cookie: ARRAffinity=00d5bcecb71b87e9bf9bb28925f315a4d8828005fa777a17f8bcba07500e665d;Path=/;HttpOnly;Domain=update.code.visualstudio.com
Date: Fri, 01 Mar 2019 13:24:27 GMT
```

**Comment by Sudamid** [comment]
> This is not only the case for the WIndows download but for Mac and Linux also:
> 
> ```
> mwerner:~ mwerner$ curl -I https://update.code.visualstudio.com/latest/darwin/stable
> HTTP/1.1 404 Not Found
> Content-Length: 9
> Content-Type: text/plain; charset=utf-8
> request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c
> X-Powered-By: Express
> Strict-Transport-Security: max-age=31536000
> X-Source-Commit: ac58393a9add3e00938f89cac90d4c9e8fe80945
> Set-Cookie: ARRAffinity=00d5bcecb71b87e9bf9bb28925f315a4d8828005fa777a17f8bcba07500e665d;Path=/;HttpOnly;Domain=update.code.visualstudio.com
> Date: Fri, 01 Mar 2019 13:24:27 GMT
> ```

lol

**Comment by levrik** [comment]
@makkes Works fine for me from Germany.

**Comment by ekmoreau** [comment]
Works when using https://hide.me/en/proxy from the Netherlands for now.

**Comment by joaomoreno** [comment]
Our US web server failed badly and our traffic manager failed to reroute traffic accordingly.

Everything should be working now.
