### ISSUE TITLE
Unable to download Windows VS Code installer(s)

### ISSUE THREAD

**Issue by miniversal** [Microsoft/vscode#69658]
There seems to be a server issue. The latest stable and all of the previous builds show the same server error.
https://update.code.visualstudio.com/1.31.1/win32-x64-user/stable

The /latest/ subdirectory says "not found".
https://update.code.visualstudio.com/latest/win32-x64-user/stable

**Comment by jdestep93** [comment]
Same here with the darwin version

**Comment by DarthSpock** [comment]
Insiders is also affected. Also, I'm unable to update my Insiders to the latest (been almost a week since I updated).

**Comment by stuhj** [comment]
i meet this problem too, show not found when visit download page

**Comment by Sudamid** [comment]
I've waited for 3h and even longer....

**Comment by Sudamid** [comment]
Is there any MS developer?

**Comment by maxshaw** [comment]
darwin +1

**Comment by ekmoreau** [comment]
Anyone? Can anyone share a link to a past version? I just installed a new machine and literally cannot work right now. =/

**Comment by joaomoreno** [comment]
Yup, we're detecting anomalies in our update services. Looking into it.

**Comment by ekmoreau** [comment]
Works when using https://hide.me/en/proxy from the Netherlands for now.

**Comment by joaomoreno** [comment]
Our US web server failed badly and our traffic manager failed to reroute traffic accordingly.

Everything should be working now.
