### ISSUE TITLE
Code page stuck and not reflecting changes

### ISSUE THREAD

**Issue by MoAsmar** [Microsoft/vscode#69654]
Issue Type: <b>Bug</b>

I was copying and pasting some code in a big file with more than 1000 lines of code I am using react tsx, this started to happen when emulating and working on the file,  copy, past, the file doesn't show the changes but in the git source tree I can see those changes

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by MoAsmar** [comment]
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
Can you give me steps to reproduce your issue? Can you explain clearly what the issue is?

**Comment by MoAsmar** [comment]
I was opening 5 instances of VSCode, one of them is a big app, I was working on a thousand lines of code file, when I close it, the CPU goes down to 30%, when I reopen the same project, it becomes highly used to 99%, this caused the editor to stuck at writing any code, or you can write but it doesn't reflect what's being written, and some warning errors appears, sorry I didn't get a screenshot of this, I uninstalled the software, installed it again and it seems Ok.

**Comment by joaomoreno** [comment]
Alright. Make sure to give us more details if it comes back.
