### ISSUE TITLE
enable keychords of 3 or more steps

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/vscode#6966]
- VSCode Version: 1.1.1
- OS Version: Windows7, x64

Steps to Reproduce:
1. Create a key-chord of 3 steps: "ctrl+k ctrl+c d" and bind it to a command
2. Try the new key-chord
3. Observe no action

Expected: 3 steps key-chords should work.

**Comment by siegebell** [comment]
I'm writing an extension for a language that provides an alternative to the ubiquitous use of emacs. Some potential users are demanding that their crazy many-chorded keybindings be supported before moving to vscode...

**Comment by siegebell** [comment]
I can almost write an extension to provide this behavior...

Say I want to map `ctrl+c ctrl+a ctrl+b` to `some.command`. I can add these keybindings:
```json
{"key": "ctrl+c ctrl+a", "command": "chords.c.a" },
{"key": "ctrl+b", "command": "some.command", "when": "chord.c.a"}
```
Where command `chords.c.a` calls `vscode.commands.executeCommand("setContext","chord.c.a",true)`.

But I cannot think of a good way to exit the "chord.c.a" context when the next key is pressed. Something like `onDidExecuteCommand` (proposed in #1431) might work: if any command is run while in "chord.c.a" mode, then disable the mode.

Any suggestions?

**Comment by NightMachinary** [comment]
I very much like the Spacemacs.org model of things, and if multi key chords are supported, something similar could be achieved for VS code.

**Comment by truesilver92** [comment]
I bet it is possible to implement this using just a plugin that defines modes. As long as you use the plugin to actually do the command as well a normal command can be run while also clearing the key chord modes used to implement the key chords

**Comment by macintacos** [comment]
Just as a datapoint, but I find that with [the VSpaceCode extension](https://marketplace.visualstudio.com/items?itemName=VSpaceCode.vspacecode) I have found the Spacemacs chord emulation that I was looking for 🙂. While I still really believe that this should be addressed, the need has dramatically dropped for me as far as I'm concerned. If you really like Spacemacs chords, check out that extension!

**Comment by ZeanArts** [comment]
> Just as a datapoint, but I find that with [the VSpaceCode extension](https://marketplace.visualstudio.com/items?itemName=VSpaceCode.vspacecode) I have found the Spacemacs chord emulation that I was looking for 🙂. While I still really believe that this should be addressed, the need has dramatically dropped for me as far as I'm concerned. If you really like Spacemacs chords, check out that extension!

I too am using that extension and loving it. However this just makes a native implementation even more important to me, since it now showed me how good vscode can be with it.

Further reasons for a native implementation are many edge cases, where the plugin collection from vspacecode is not able to be activated. Or being able to search for a command and seeing the shortcut (chord) in the "ctrl+shift+p" menu.

So while it is indeed nice.. a native implementation would be nicer 😉 even for vspacecode

**Comment by truesilver92** [comment]
I am not seeing it on the description page, does vspacecode support mapping arbitrary length key chords?

**Comment by macintacos** [comment]
@truesilver92 you can map arbitrary key chord lengths by creating multiple menus. VSpaceCode's functionality for chords is actually implemented by the [vscode-which-key](https://marketplace.visualstudio.com/items?itemName=VSpaceCode.whichkey) extension (it's installed along with VSpaceCode; VSpaceCode is just a "default keychord map", if you will).

One limitation you should likely be away of is that I don't believe you can make multiple keychords that include modifiers, so something like `ctrl+a ctrl+b ctrl+c` is not possible, but you can make a chord that is `SPC a b c` (or any length, really). I recommend reading [their documentation](https://vspacecode.github.io/docs/whichkey/) about it.

I still think that having 3+ chords available to folks who don't want to install that extension is very handy, and should still be implemented for sure! Limiting chords to 2 always felt.... arbitrary 🙂

**Comment by thiagomajesk** [comment]
I'm also interested in this, I think it would be a great addition. What's the requirement for getting this approved/ voted, etc?

**Comment by spigelli** [comment]
This would need to check if the keyboard has n-key-rollover or limit at 6 keys right?

**Comment by truesilver92** [comment]
It shouldn't need that. It is called a "chord" but it is not intended for multiple segments to be pressed at the same time; at most all the modifiers and a single character.

**Comment by druskus20** [comment]
+1 This is the only thing I need to be able to port my Vim keymaps to vscode.

**Comment by AaronNGray** [comment]
The basic ChordKeybinding class has an Array of SimpleKeybinding's, 
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindings.ts#131

theres other bits of code though that do not support this though such as :-
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindings.ts#L36
https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/keybindingLabel/keybindingLabel.ts#L26
https://github.com/microsoft/vscode/blob/main/src/vs/monaco.d.ts#L422

And UI stuff :-
https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/keybindingLabel/keybindingLabel.ts

Keybindings seem to be represented as numbers in places that should hopefully be able to be replace by number Arrays
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindings.ts#L36

Then there is the keybinding parser :-
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindingParser.ts#L10

**Comment by AaronNGray** [comment]
Okay I see why this has not been done now, its complicated ! I am going to attempt it over the next week.

**Comment by amirdib** [comment]
Also interested. Please ask if you need help @AaronNGray

**Comment by AaronNGray** [comment]
@amirdib Sorry I printed out the relevant code it’s several pages that would probably need totally reworking then got distracted by other tasks. I will look the printouts out again and have a fresh look at them.

**Comment by wmstack** [comment]
> I bet it is possible to implement this using just a plugin that defines modes. As long as you use the plugin to actually do the command as well a normal command can be run while also clearing the key chord modes used to implement the key chords

I did make a plugin that enables you to have your own modes, at https://github.com/wmstack/contextually, though I still feel like three level chords are better implemented natively.

**Comment by mendeljacks** [comment]
What if you use a shortcut to a unicode character and do chording on the os/keyboard level

**Comment by Tyriar** [comment]
Very cool!

**Comment by LaurensUP** [comment]
Wow.. so happy I found this -- thank you!
I believe it's missing from the official documentation?

**Comment by LaurensUP** [comment]
@ulugbekna thank you!
It's working brilliantly and smoothly. Absolutely awesome feature!! 🙏

**Comment by ulugbekna** [comment]
This was actually developed by @ dyedgreen
All credits goes to him :-)
