### ISSUE TITLE
JSDoc @type is broken

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69664]
Repro:

- Clone https://github.com/Microsoft/vscode-extension-samples
- `cd webpack-sample && npm install`
- Open the `webpack-sample` folder in code (TS 3.3.1) and insiders (TS 3.3.3)

Insiders:

![image](https://user-images.githubusercontent.com/4033249/53659001-2f76c680-3c0f-11e9-9f61-2dbc1dd51fee.png)

Stable:

![image](https://user-images.githubusercontent.com/4033249/53659012-39002e80-3c0f-11e9-817c-1e9f6f17cf1e.png)

We are shipping the webpack bundling guide so this should be fixed. FYI @jrieken 
Also many people who haven't switched to TS rely on JSDocs types for IntelliSense.

**Comment by mjbvz** [comment]
Seems to be working fine for me:

<img width="657" alt="screen shot 2019-03-01 at 10 56 08 am" src="https://user-images.githubusercontent.com/12821956/53659540-aeb8ca00-3c10-11e9-9468-3a19039b3821.png">

What happens if you f12 on `webpack` in `import('webpack')`

**Comment by mjbvz** [comment]
This looks like an automatic types issue. I can repo if I clear the typings cache and then open the `webpack.config` file. However we then install the typings in the background. Once that completes any edits to the file refresh the diagnostics (we should probably auto refresh them here but this is not a regression)

**Comment by octref** [comment]
For some reason this doesn't repro after I reopen VS Code. Let me dig a bit to see what went wrong.

**Comment by octref** [comment]
I cannot find reliable repro. If I run into this again I'll reopen.
