### ISSUE TITLE
Different theme for the integrated terminal?

### ISSUE THREAD

**Issue by ItalyPaleAle** [Microsoft/vscode#69663]
I would like to be able to apply a different theme to the integrated terminal. My preferred theme for the editor is the light one, but this looks really ugly on the integrated terminal. In fact, I'm using ZSH, and the integrated terminal renders it poorly (uses the colors on a white background, and it doesn't load the Powerline fonts).

https://imgur.com/ovLKgyy

**Comment by Tyriar** [comment]
You can either find a theme which styles the terminal how you want it or customize it manually in settings using `workbench.colorCustomizations`: https://code.visualstudio.com/api/references/theme-color
