### ISSUE TITLE
Outline view: no symbols shown after collapse and expand

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#69667]
- VSCode Version: 1.32.0 804373ac4d5c84e96c8086cee5b9be132df88837
- OS Version: Windows

Steps to Reproduce:

1. Have a Markdown file open in the editor (repros for any file type JS, TS)
2. Expand Outline 

Outline view is empty.

3. Select another file in the editor.

Outline view is filled.

4. Collapse and expand Outline view.

Outline view is empty.

Also repros if you use View >Open View > Outline from the main menu

**Comment by gregvanl** [comment]
This is a recent regression and does not repro with the previous 1.32 Insiders build 
Commit: 52306b406d9231a0667c758e536bd177e5570180

**Comment by gregvanl** [comment]
Assigning to @jrieken. Bot didn't seem to run.

**Comment by jrieken** [comment]
A layout call seems to be missing

**Comment by jrieken** [comment]
Nope, layout is always being called when expanding. Everything recovers when resizing things and to make matter worst, it doesn't reproduce when having a breakpoint in [`layoutBody`](https://github.com/Microsoft/vscode/blob/c10ea17d96516e53a542b3982f556a1bca1c99cb/src/vs/workbench/contrib/outline/browser/outlinePanel.ts#L381). 

@joaomoreno is there some layout debouncing or does the tree ignore layout calls when the dimensions don't change?
