### ISSUE TITLE
"Trigger Expansion On Tab" option is working the opposite.

### ISSUE THREAD

**Issue by lovefields** [microsoft/vscode#69678]
- VSCode Version: January 2019 (version 1.31)
- OS Version: MAC OS 10.13.6

Steps to Reproduce:

1. "Trigger Expansion On Tab" is not checked, and not working the my key binding.
2. "Trigger Expansion On Tab" is checked, and is working the my key binding.

Does this issue occur when all extensions are disabled?: No

using extensions list is : korean language, ftp-simple

**Comment by octref** [comment]
When you don't have the setting checked, tab does not expand emmet abbreviation. This is as-designed.

**Comment by lovefields** [comment]
@octref 
I mean don't have the setting checked, but only expand emmet abbreviation "tab" key.
And i have the setting checked, is working "cmd+e"(my key binding) for expand emmet abbreviation.
My windows computer is not have the setting checked and is working  "cmd+e"(my key binding) for expand emmet abbreviation.

**Comment by octref** [comment]
Can you use https://getkap.co/ to record a gif? Also run "Toggle Screencast Mode".

**Comment by lovefields** [comment]
Here is video link  [https://www.youtube.com/watch?v=kr0yxWbLwg0](https://www.youtube.com/watch?v=kr0yxWbLwg0)

And now don't have the setting checked, not working expand emmet abbreviation....
setting checked, working "cmd+e" key.

**Comment by johnlindquist** [comment]
If I set `"editor.quickSuggestions": false,` (it defaults to true), then `Tab` no longer works for emmet. 

I prefer to use Emmet Tab expansion with the suggestions dropdown disabled. This was the behavior in previous builds. Something changed recently to "break" my this behavior.

**Comment by octref** [comment]
Does this still repro? I can't reproduce this with below setting:

```json
{
  "emmet.triggerExpansionOnTab": true,
  "editor.quickSuggestions": false
}
```

This is irrespective of whether I reset a shortcut for `Emmet: Expand Abbreviation`.

**Comment by lovefields** [comment]
- VScode version  : 1.39.2
- MAC version : Catalina10.15

Now is everything is ok.
Thanks you to answer my issue.
