### ISSUE TITLE
Quick open doesn't really work

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#69670]
> copied from https://github.com/Microsoft/vscode-cpptools/issues/3230
> @fr43nk

- OS and Version: Win7
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.22.0-insiders

I have a large code base located on a network drive (smb connection)
My workspace file has some folders set up like follows:
```
{
	"folders": [
		{
			"path": "y:\\base\\path1"
		},
		{
			"path": "y:\\base\\path2"
		},
		{
			"path": "y:\\base\\path3"
		},
		{
			"path": "y:\\base\\path4"
		}
	],
```

The problem is: If I hit Ctrl+P (quick open) and type in a file name, the dialog doesn't find anything.
Only after opening this file I can use the shortcut.
My expectation was, that some kind of tree walker iterates through the folders and builds a list of existing files.
Am I wrong?

**Comment by roblourens** [comment]
There should be a progress bar after you start typing, it's likely just slow to enumerate all files over your network connection. If you leave it for a minute do files show up?

**Comment by fr43nk** [comment]
Yes, there is a progressbar but it takes forever and doesn’t show anything. I thought the process starts immediately I open my workspace. Why is this so slow? It’s just a file listing, I guess.

**Comment by derekwallace** [comment]
this is a known issue when you have slow network drive.
in my case ripgrep takes about 5 minutes+ to complete its anlaysis of my workspace.
This only starts when you hit ctrl-p.
for a period after this completes the ctrl-p should work better. the reason is that the results are cached for ~ 1 hour. after that the cache is cleared and you are back where you started.

from my experience ctrl-p to find files is useless when you have a "slow" network drive.
other text editors implement a better caching scheme.

**Comment by fr43nk** [comment]
Why gets the cache cleared after one hour? It doesn’t make sense to me.

**Comment by fr43nk** [comment]
In the meantime I created an extension to solve this problem ([VSCode Quick Open](https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-quickopen))
It uses `dir` on windows and `find` on macos/linux to create a list of files of a open workspace.
This list gets stored in the workspace state so the index is up and running immediately when reopen the workspace.
Maybe this makes it a bit more clear what I expected from the quick open feature.

Best regards

**Comment by roblourens** [comment]
I'm going to merge this into https://github.com/Microsoft/vscode/issues/66884
