### ISSUE TITLE
Tsserver is consuming CPU

### ISSUE THREAD

**Issue by blurHY** [Microsoft/vscode#69679]
- VSCode Version: 1.32.0
- OS Version: Win10

Steps to Reproduce:

Open VSCode

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/33171396/53675187-f867ea00-3cce-11e9-9e3d-a6dedabe8d46.png)

**Comment by blurHY** [comment]
Uninstalling typescript extension solved this

**Comment by mjbvz** [comment]
You reported this same issue in #68895 and stated it was caused by an extension you installed. Is that not still the case?

**Comment by blurHY** [comment]
NOPE. It's a built-in extension

**Comment by mjbvz** [comment]
In addition, please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by blurHY** [comment]
The bug disappeared after some updates.

**Comment by blurHY** [comment]
14	183	13444	             electron_node tsserver.js 

It happens again

![image](https://user-images.githubusercontent.com/33171396/55874232-5a681900-5bc4-11e9-9032-66701f29e015.png)

**Comment by mjbvz** [comment]
Please start by following the perf reporting guide linked to share the relevant information, such as the output of `code-insiders --status`
