### ISSUE TITLE
Scripts show as <node_internals> while debugging with node 11

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#69675]
- Debug a .js file with no sourcemaps using Node 11
- Hit a breakpoint
- See that a new editor is opened with the script that says "read-only core module"

I will just revert https://github.com/Microsoft/vscode-chrome-debug-core/commit/b5a4d5436d3acd30369f167d48c59bcadebbcb12.

**Comment by octref** [comment]
Not sure the PR fixes the bug. Here's what I did:

- Build your branch
- `code.sh` to open VS Code
- Write a JS file like so and run `node --inspect-brk index.js`
- No breakpoints are hit. I ran it a few times and certain times the breakpoints are hit but the debugger did not pause (continued execution).

![image](https://user-images.githubusercontent.com/4033249/53710299-660c3700-3df1-11e9-898d-e1950c26ff37.png)

`node -v` is `v10.12.0`.
