### ISSUE TITLE
Incorrect code format

### ISSUE THREAD

**Issue by larini** [Microsoft/vscode#6968]
- VSCode Version:1.1.1
- OS Version: Windows 10

Steps to Reproduce:

Use this class:

	using System.Collections.Generic;
	namespace SqlExpress.ViewModels.Consulta
	{
		public class EditViewModel
		{
			public int? Peso {get;set;}
			public List<Exame> ExamesFisicos
			{
				get
				{
					var exames = new List<Exame>();
					if (Peso != null)
						exames.Add(new Exame(){Nome="Peso", Valor=Peso.ToString()});					
					return exames;
				}
			}
			
		}
	}

This line got incorrect indentation:

    exames.Add(new Exame() { Nome = "Peso", Valor=P = so.ToString()}) ;

It should be like this:

    exames.Add(new Exame() { Nome = "Peso", Valor = Peso.ToString()}) ;

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#383
