### ISSUE TITLE
In Workspace, rename of a file fails

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#69697]
Issue Type: <b>Bug</b>

I have a workspace, with a schematics project in it. I am modifying the cli schematics, each one I complete, I rename to "web-{folder-name}". But it fails to stick, sometimes, if I restart VS Code, it reflects the change, other times, which happens more often, it does not apply the rename.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (24.56GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (112)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|2.0.3
scss-scan|aar|0.1.67
html-snippets|abu|0.2.1
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
vscode-angular2-files|ale|1.6.2
angulardoc-vscode|Ang|6.1.3
vscode-color|ans|0.4.5
spellright|ban|3.0.24
scss-block-comments|cha|0.0.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-dictionary|Com|0.0.5
vscode-svgviewer|css|2.0.0
angular-schematics|cyr|1.20.0
angular2-snippets|dan|1.0.21
vscode-markdownlint|Dav|0.24.0
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.20
vscode-eslint|dba|1.8.0
angular-productivity-pack|dev|2.1.2
angular-extension-pack|dog|7.1.0
githistory|don|0.4.6
xml|Dot|2.4.0
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
vscode-todo-plus|fab|4.11.4
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
html-slim-scss-css-class-completion|gen|1.5.12
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.120
AngularMaterial|har|7.0.0
beautify|Hoo|1.4.9
githd|hui|2.1.0
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.2.0
path-autocomplete|ion|1.13.1
vscode-angular2-emmet|jak|2.0.3
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
angular-essentials|joh|0.5.1
Angular2|joh|7.0.1
vscode-codemetrics|kis|1.17.4
vscode-commitizen|Kni|0.8.2
refactorix|kri|0.3.6
node-module-intellisense|lei|1.5.0
angular-extension-pack|loi|0.7.0
Angular2Tests|Mar|0.7.3
json-to-ts|Mar|1.5.5
git-graph|mhu|1.4.0
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|7.2.5
vs-cron|mkl|3.0.0
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.12.0
azure-account|ms-|0.8.0
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.11.0
typescript-javascript-grammar|ms-|0.0.49
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1256
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
ng-fortytwo-vscode-extension|NG-|0.0.9
angular-console|nrw|7.3.1
createGUID|nwa|0.0.2
angular-component-extension|oni|0.0.14
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|3.6.3
tsimporter|pmn|1.2.14
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
project-snippets|reb|0.5.0
vscode-yaml|red|0.3.0
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
awesome-angular-pack|sal|1.12.2
comment-ts|sal|0.9.11
angular-follow-selector|san|1.2.0
MDTools|sea|1.0.1
git-merger|sha|0.4.1
stylelint|shi|0.48.0
vscode-scss-formatter|sib|1.4.0
vscode-fileutils|sle|2.13.5
vscode-smoothtype|spi|1.2.0
guides|spy|0.9.3
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
move-ts|str|1.11.3
lorem-ipsum|Tyr|1.2.0
Angular2|UVB|0.4.1
cmake-tools|vec|1.1.3
highlight-matching-tag|vin|0.8.6
vscode-angular-support|vis|0.1.4
gitblame|wad|2.6.3
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
dictionary-completion|yzh|0.8.0
markdown-all-in-one|yzh|2.1.0
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
