### ISSUE TITLE
VSC Node Package Manager / better local ts dev experience

### ISSUE THREAD

**Issue by jeremy-coleman** [Microsoft/vscode#69692]
A very simple solution exists to many of the problems facing node/web devs

1) Add a package manager to the IDE, prefer pnpm not rush. This solves the problem of billions of node_modules spread across projects. there is absolutely no need for that. It would also allow easier global shimming to essentially let users code in such a way as their web modules are core node modules. ie: import React from 'react' should just work, without a package.json as long as it's installed in the IDE. Managing dependencies in this way has countless benefits, including easier multi-monorepo management, a faster IDE, consistent types, increased productivity, immediate security patches, etc. The dev experience would be similar to using the node core modules. 

In addition to a package manager, the ts language server picking up the correct types often seems to be buggy , not update properly, mismatch types, resolve against multiple versions of the same package, etc. having a package manager would mostly alleviate that, but giving users more control over the language server and especially their own project would be beneficial. ie: over-riding globals like window shouldn't take a typescript beginner more than a few seconds. 

also please just add in sucrase-node by default or some other transpile-only execution script to handle .ts / es6 files from the command line. ts-node is garbage for any web development, because the cwd tsconfig.json will over-ride its settings. take for example, the majority of web developers in a CLI driven webapp (react/vue/angular) are going to be set up to use es modules. if they want to run a .ts file, ts-node isn't gonna work and ts-node maintainers do not think ts-node should run in node for some reason, providing a fix to that inside vsc makes the most sense and is an easy win

**Comment by mjbvz** [comment]
If I understand your request correctly, you are asking for integrating existing tools like a package manager into VS Code itself? I don't think this is within scope of core VS Code, especially because such as variety of tools and solutions are used by the community. An extension could provide more specialized support  for specific setups/environments

If you have specific examples of something not working, please open a bug report and I'll take a look
