### ISSUE TITLE
Is there a way to create an instance of `vscode.TextDocument`?

### ISSUE THREAD

**Issue by readless** [Microsoft/vscode#69695]
Is there a way to create an instance of `vscode.TextDocument`?

**Comment by usernamehw** [comment]
Do you mean a new Untitled file?

https://stackoverflow.com/questions/41068197/vscode-create-unsaved-file-and-add-content

**Comment by readless** [comment]
i have a TextDocument, and can i get the parent dir of the file? so i want to create a TextDocument

**Comment by usernamehw** [comment]
```javascript
const parentDirPath = path.join(document.uri.fsPath, '..');// where `document` is `vscode.TextDocument`
```

**Comment by readless** [comment]
i hava a file path of parent dir 。 and i want to get a TextDocument represent that file

**Comment by usernamehw** [comment]
`TextDocument` is  ... a text document. You can't make a text document out of a directory. 

Do you perhaps want to create a file **inside** that directory?

**Comment by jrieken** [comment]
You must use `openTextDocument` to open or create one (see docs). However, there is no API to ready/write arbitrary file objects.

**Comment by readless** [comment]
@jrieken thanks~
