### ISSUE TITLE
showing modified for files whose changes  are commited

### ISSUE THREAD

**Issue by Seenivasanseeni** [Microsoft/vscode#69699]
Look at this screenshot 
![screenshot from 2019-03-02 15-05-27](https://user-images.githubusercontent.com/20085943/53680149-06346400-3cfd-11e9-9a5f-09156330ea37.png)

I made some changes to the git repo and i commited those.
you can see that when i did `git diff`, there is nothing. 
But VScode keeps telling me that those are modified. 

Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-45-generic

I have no extensions installed.

**Comment by rebornix** [comment]
@Seenivasanseeni can you share what Git viewlet shows at this point?
