### ISSUE TITLE
Automatically open folders inside folder

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#6969]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.5

This is a feature request to automatically open folders inside a folder if only a single folder exists.

# Example

## Current
![before](https://cloud.githubusercontent.com/assets/3099626/15607889/c6ed9c60-2433-11e6-98b5-ce0e5e7f221d.png)

## Expected
![after](https://cloud.githubusercontent.com/assets/3099626/15607901/d3a47fbe-2433-11e6-9c2d-1710b5a6c7e6.png)

**Comment by bpasero** [comment]
@xeoneux this should actually work but maybe you have other files and folders within that tree that are excluded via settings? I think we only expand automatically when the folder really only has 1 child on disk.
