### ISSUE TITLE
PHP highlighter stops working if "<<<" used

### ISSUE THREAD

**Issue by Tommixoft** [Microsoft/vscode#6970]
- VSCode Version: 1.1.1
- OS Version: Win7 x64

Steps to Reproduce:

1. Use of <<<XML in variable value - stops highlighting rest of the code.

![untitled](https://cloud.githubusercontent.com/assets/1042441/15608363/29b5a99e-2422-11e6-8b28-948f82503a28.png)

**Comment by aeschli** [comment]
Can you please paste the code snippet that shows the issue?

**Comment by Tommixoft** [comment]
Attached photo shows code and problem very clearly

**Comment by aeschli** [comment]
This is how it looks in 1.1.1:
![image](https://cloud.githubusercontent.com/assets/6461412/15657021/6cd01bc8-26ad-11e6-80cc-eaf0f77dbf6a.png)
This is in the coming 1.2 where we updated the PHP syntax highlighting grammar:
![image](https://cloud.githubusercontent.com/assets/6461412/15657047/9c698144-26ad-11e6-8b3e-dc4cdc7d0131.png)


So this is looks like it's fixed.
I'd still like to try it with your code snippet, just in case you still have it.

**Comment by Tommixoft** [comment]
Yes in 1.1.1 it still have bug. No longer higlights php code but instead only variable value.

Here my snippet:

```
<?php

$globaltype = GLOBALTYPE;
$unitid = UNITID;
$userid = USERID;
$termtype = TERMTYPE;


class Queries
{
    public static function RegisterQuery($tel, $Firstname, $Lastname)
    {
        global $globaltype, $unitid, $userid, $termtype;
        
        $LoginQuery = <<<XML
        <?xml version="1.0" encoding="UTF-8"?>
        <Message Action="Login" Terminal_Type="$termtype" Global_Type="$globaltype" Unit_ID="$unitid" User_ID="$userid">
           <Is_Virtual_Card>True</Is_Virtual_Card>
           <Login Auto_Registry="True">%s</Login>
           <F_Name>%s</F_Name>
           <L_Name>%s</L_Name>
           <Full_Name>%s</Full_Name>
           <Auth_Code/>
        </Message>
XML;
        
        return sprintf($LoginQuery, $tel, $Firstname, $Lastname, $Firstname." ".$Lastname);
    }
    
    
    public static function ResetQuery($tel)
    {
        global $globaltype, $unitid, $userid, $termtype;
        
        $LoginQuery = <<<XML
        <?xml version="1.0" encoding="UTF-8"?>
        <Message Action="Login" Terminal_Type="$termtype" Global_Type="$globaltype" Unit_ID="$unitid" User_ID="$userid">
           <Is_Virtual_Card>True</Is_Virtual_Card>
           <Login Auto_Registry="True">%s</Login>
           <Auth_Code/>
        </Message>
XML;
        
        return sprintf($LoginQuery, $tel);
    }
    
}


?>
```

**Comment by Tommixoft** [comment]
it's like it doesn't react to ending tag - `XML;`

![untitled](https://cloud.githubusercontent.com/assets/1042441/15657704/058478ba-26bc-11e6-90c1-57517869a2ec.png)

**Comment by Tommixoft** [comment]
This is how it looks with other IDE  all good. colors are all ok, nothing broke.

![untitled2](https://cloud.githubusercontent.com/assets/1042441/15657755/a2598bda-26bc-11e6-9cda-329b33f6fa31.png)

**Comment by aeschli** [comment]
This is how it looks in 1.2:
![image](https://cloud.githubusercontent.com/assets/6461412/15657790/a3b53e6e-26b4-11e6-9a3d-3a1962ed7e89.png)

**Comment by aeschli** [comment]
With the Dark+ default theme:
![image](https://cloud.githubusercontent.com/assets/6461412/15657813/f0b6361e-26b4-11e6-91e6-70b404fbc93e.png)

**Comment by Tommixoft** [comment]
Look nice :) Thanks :) Love VS CODE... hope it will still last as a lightweight editor :) Would be awesome if FTP support would be integrated.
