### ISSUE TITLE
Maximize/zoom editor pane - menu or button on editor tab

### ISSUE THREAD

**Issue by l0k1verloren** [microsoft/vscode#69704]
I have looked at relevant related issues

![image](https://user-images.githubusercontent.com/20619963/53682452-244a9600-3cf6-11e9-93d2-08ab13cda3be.png)

and yes, related issues already exist. But none of them satisfy exactly nor have closed with this aspect properly addressed, so here goes:

My favourite linux terminal is Tilix, formerly known as Terminix, and it is similar to Terminator, but styled along Gtk+-3, but both terminals have multi-panel terminals with the ability to zoom one panel to fill the window's total content area.

There is one button on the header bar for the terminal panes that appears when not in maximised state, and when it is clicked, this panel becomes the sole panel in the group, with a button to minimise it.

I realise there is commands that do somewhat similar things, such as the view menu's 'Editor Layout -> Single', which joins all of the editor panes into one, merging their component tabs into a single view, but this can't be reversed, which means you can't 'maximize' and then reverse what you did. 

(yes, maybe if this editor view region state data had an undo log this would also satisfy the brief)

As to the implementation, the way I see it working is that it switches all other editor panes display attribute to 'none' and adds a node on the right of the panel's tab bar (in menu or a separate button) that reverses this and reverts to the previous state.

It doesn't have to hide the other tabs within the maximised pane, specifically one wants the total state of the editor panel region to retain its non-maximised state information, but make it inaccessible until you revert the maximization to the prior state.

I should note that a journal of the editor state would also satisfy this feature request, but that I believe such an addition is far more complex and would still have the problem of less accessibility of the feature, hiding in related but deep-embedded parts of the existing interface, when it would make more sense to implement it as I described - something like the maximize state used for windows in almost every window manager.

**Comment by isidorn** [comment]
fyi @sbatten

**Comment by daeh** [comment]
I also want this is a big way

**Comment by ezeugo-codaio** [comment]
I too would love this. The common use case is i have a hierarchy of files open that have parent child relationships in my react tree and I want all 4-5 of them open, with the ability to "zoom" into anyone of them and then back out while maintaining that list.
