### ISSUE TITLE
Incremental protocol for language server type extension does not seem to be implemented

### ISSUE THREAD

**Issue by bartosz-antosik** [Microsoft/vscode#69706]
When I am following the guide [Example - Language Server A Brief Overview of Language Server and Language Server Protocol](https://vscode-ppe.azurewebsites.net/docs/extensions/example-language-server) when I try to implement incremental protocol for language server I cannot get any of these events fired:

* onDidOpenTextDocument
* onDidChangeTextDocument
* onDidCloseTextDocument

It seems that I am doing everything as in the guide.

Is incremental protocol for language server type extension implemented?

**Comment by dbaeumer** [comment]
@bartosz-antosik two things are important:

- you need to have `textDocumentSync: TextDocumentSyncKind.Incremental` 
- you can't use a document manager. So the code `let documents: TextDocuments = new TextDocuments();` and all references to documents need to me removed.

Let me know if this helps?

**Comment by bartosz-antosik** [comment]
The first I had. Have not been aware of the second. I will try and come back with some update.

**Comment by bartosz-antosik** [comment]
Yes, id DOES work. IMHO should be bit better documented in the official documentation.
