### ISSUE TITLE
Latex workshop won't make a pdf viewer

### ISSUE THREAD

**Issue by khalilRhouma** [microsoft/vscode#69709]
Sorry  I didn't notice that thee information didn't add to the post issue. 
First, when i build latex file i get this output .

> [09:55:36] Initializing LaTeX Workshop.
> [09:55:36] Creating LaTeX Workshop http and websocket server.
> [09:55:36] LaTeX Workshop initialized.
> [09:55:36] Found root file from active editor: c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:55:38] Root file changed from: undefined. Find all dependencies.
> [09:55:38] Instatiating new file watcher for c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:55:38] Parsing c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:55:38] Cannot find .bib file references
> [09:55:38] Server created on 127.0.0.1:55389
> [09:55:38] Snippet data loaded.
> [09:55:38] LaTeX Workshop version: 6.0.0
> [09:56:02] BUILD command invoked.
> [09:56:02] Found root file from active editor: c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:56:02] Root file remains unchanged from: c:\Users\khalil\Downloads\modele_ensi_pcd.tex.
> [09:56:02] Building root file: c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:56:02] Build root file c:\Users\khalil\Downloads\modele_ensi_pcd.tex

and when I run the pdf preview on vscode tab or on the browser i get this output .

> [10:01:55] VIEW command invoked.

and nothing happen.

**Comment by rebornix** [comment]
> We have written the needed data into your clipboard because it was too large to send. Please paste.

@khalilRhouma please share the needed information to help troubleshoot.

**Comment by khalilRhouma** [comment]
Sorry  I didn't notice that thee information didn't add to the post issue. 
First, when i build latex file i get this output .

> [09:55:36] Initializing LaTeX Workshop.
> [09:55:36] Creating LaTeX Workshop http and websocket server.
> [09:55:36] LaTeX Workshop initialized.
> [09:55:36] Found root file from active editor: c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:55:38] Root file changed from: undefined. Find all dependencies.
> [09:55:38] Instatiating new file watcher for c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:55:38] Parsing c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:55:38] Cannot find .bib file references
> [09:55:38] Server created on 127.0.0.1:55389
> [09:55:38] Snippet data loaded.
> [09:55:38] LaTeX Workshop version: 6.0.0
> [09:56:02] BUILD command invoked.
> [09:56:02] Found root file from active editor: c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:56:02] Root file remains unchanged from: c:\Users\khalil\Downloads\modele_ensi_pcd.tex.
> [09:56:02] Building root file: c:\Users\khalil\Downloads\modele_ensi_pcd.tex
> [09:56:02] Build root file c:\Users\khalil\Downloads\modele_ensi_pcd.tex
and when I run the pdf preview on vscode tab or on the browser i get this output .

> [10:01:55] VIEW command invoked.

and nothing happen.

**Comment by khalilRhouma** [comment]
> 
> 
> > We have written the needed data into your clipboard because it was too large to send. Please paste.
> 
> @khalilRhouma please share the needed information to help troubleshoot.

Yes , Sorry I didn't notice that .

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
