### ISSUE TITLE
Ordinal Not Found / The window has crashed (languages not working)

### ISSUE THREAD

**Issue by JamTarty** [Microsoft/vscode#69713]
- VSCode Version: Latest (I can't check the exact build number as I can't open the software).
- OS Version: Windows 10 Version 1809

Steps to Reproduce:

1. Installed VSCode and I'm getting these issues

Does this issue occur when all extensions are disabled?: Yes/No
I have only the deafult extensions as its a fresh install. It hasn't happened in the past even with extensions.

When I first launch this is what I get:
![image](https://user-images.githubusercontent.com/36020040/53685412-34706e80-3d12-11e9-86f5-f7cf0e76db64.png)

If I can get past that which is rare I get this:
![code_2019-03-02_17-32-24](https://user-images.githubusercontent.com/36020040/53685424-6255b300-3d12-11e9-8994-1c886ab76dad.png)

Then none of my coding languages work for example html, css.

It seems an unusual issue I'm having as it was working perfectly last week I just hoped a reinstall would fix it. I removed all traces off previous installs as well before doing a clean install.

**Comment by joaomoreno** [comment]
Can you download and try running the ZIP release? https://code.visualstudio.com/docs/?dv=winzip
