### ISSUE TITLE
A bug about: command line "code" in macOS terminal!

### ISSUE THREAD

**Issue by Imputes** [Microsoft/vscode#69712]
I see the webpage says add the command line:
```bash
export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
```
to the .bash_profile, then the users can use the `code`  + optional_file_or_dir_name to launch the Visual Stuio Code.app, but I find it is no use.
I think the correct bash script is:
```bash
export PATH=/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin:$PATH
```
That webpage is [the page](https://code.visualstudio.com/docs/setup/mac)

**Comment by joaomoreno** [comment]
The webpage doesn't say you should add the line to bash profile. It says you should run all those commands together. That will add the correct line.
