### ISSUE TITLE
30% memory consumption when idle

### ISSUE THREAD

**Issue by LogX7** [Microsoft/vscode#69714]
- VSCode Version: 
1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64

- OS Version: Linux Mint 19.1 - x64 bit - (DE) Cinnamon 4.0
- RAM : 8GB 
- CPU : A8-5600k
- GPU : NVIDIA GT 740M - 2GB

Steps to Reproduce:
1. open vscode 
2. open a python project

Does this issue occur when all extensions are disabled?: NO

my problem is that opening vscode for a python project that has 2 .py files (each has around 100~150 lines of code) and letting it idle or using it for +30 minute gets the memory consumption from 50% up by 30% (i had around 52% mem usage before and it became 85% after)

here are the processes running
![screenshot from 2019-03-02 20-13-15](https://user-images.githubusercontent.com/9774613/53686581-2843db80-3d29-11e9-9c36-09c99f4d223b.png)

Thank you !

**Comment by rebornix** [comment]
@LogX7 can you open Developer Tools and take a snapshot of the Heap and share with us to help troubleshoot?

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/876920/53704513-05213680-3dd2-11e9-8497-33a77f87ddff.png">

**Comment by LogX7** [comment]
here is snapshot of my workspace
![image](https://user-images.githubusercontent.com/9774613/53704579-0e37f500-3e1e-11e9-961f-3000ac4690ed.png)


and here's a memory heap snapchot

[Heap-20190304T013626.heapsnapshot.tar.gz](https://github.com/Microsoft/vscode/files/2923908/Heap-20190304T013626.heapsnapshot.tar.gz)

**Comment by rebornix** [comment]
@LogX7 thanks, the heapsnapshot looks reasonable to me, did you record it when you have the high memory usage?

**Comment by LogX7** [comment]
@rebornix i launched vscode and opened some files, memory (i have 8 gb) went up  by about 30% just from that ...
