### ISSUE TITLE
node modules suggestions stop working when jsconfig's "target" field is set to es6+

### ISSUE THREAD

**Issue by kiyutink** [microsoft/vscode#69715]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a javascript project (create jsconfig.json)
2. Install any package with npm
3. If jsconfig.json has "es5" as "target" or if there's no "target" field, intellisense will suggest import from this package. If you set "target" to "es6" or anything newer (es2015, es7, esnext etc.), the suggestions won't appear.
![vscode](https://user-images.githubusercontent.com/16495771/53686715-b9bc4900-3d3b-11e9-92b6-843ee363c501.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, if you run go to definition on `React`, what file does it open?

**Comment by kiyutink** [comment]
It does reproduce in the Insiders build,
go to definition opens the definition file for react (@types/react/index.d.ts)

**Comment by mjbvz** [comment]
I'm having trouble reproducing this issue in [latest VS Code insiders build](https://code.visualstudio.com/insiders/) on windows. 

Can you share a small example project so I can make sure we are using the exact same version of `@types/react` and other packages?

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
