### ISSUE TITLE
Option to always disambiguate tab titles

### ISSUE THREAD

**Issue by raggi** [microsoft/vscode#69718]
There is a feature that already exists that is similar, where when there are two tabs with the same filename in a tab group, the tab is expanded and a disambiguating path is added.

When there are multiple tab groups however, one might have for example two files open called BUILD.gn in separate tab groups, but they have no disambiguation.

I would like an option to always render the path disambiguation if there are any open files with the same name anywhere in my workspace.

**Comment by raggi** [comment]
![screen shot 2019-03-02 at 1 02 23 pm](https://user-images.githubusercontent.com/348/53687608-72a66780-3ceb-11e9-884a-f35f2a9945c7.png)

^^^ this thing :)

**Comment by ndngo** [comment]
Hi, I would like to try implementing this issue.
