### ISSUE TITLE
Create files or directories directly in tree sometimes not shown up until restart of VSCode

### ISSUE THREAD

**Issue by TimoRuetten** [Microsoft/vscode#69717]
- VSCode Version: 1.31.1
- OS Version: macOS Mojave 10.14

Since a few weeks I have the problem that sometimes when I create a new file or directory directly in the tree the file and/or directory is not shown up there. I have to exit vscode and restart it so the created file/directory is shown in the tree. Don't know if this is a known bug but its very irritating.

I dont know how to reproduce this because it only happens sometimes. I would say in my case it happens about every hour on working.

**Comment by isidorn** [comment]
Fixed in latest vscode insiders
