### ISSUE TITLE
Customized environment variables not available for extensions when VS Code is not launched via terminal

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode#69728]
Steps to reproduce:
1. Add customized environment variables to shell configuration (e.g., add `export FOO=BAR` to `~/.zshrc`)
1. Open a new shell instance and launch VS Code via `code`
1. Open VS Code developer console
1. Enter `process.env.FOO` and see `"BAR"` in the output
1. Quit VS Code and relaunch VS Code via Spotlight or Launchpad
1. Repeat Step 3 and 4 but see `undefined` as result this time.

Related issue: https://github.com/Microsoft/vscode/issues/31800. The `"terminal.integrated.shellArgs"` config can resolve this issue for the integrated terminal, but the customized environment variables are still not available for extensions.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
gitlens|eam|9.5.1
vscode-pull-request-github|Git|0.4.0
latex-workshop|Jam|6.0.0
solidity|Jua|0.0.49
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.2.5433
azure-account|ms-|0.8.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
vscode-typescript-tslint-plugin|ms-|1.0.0
java|red|0.40.0
vscode-icons|rob|8.2.0
rust|rus|0.5.3
vscode-leetcode|she|0.11.0
code-spell-checker|str|1.6.10
vscode-lldb|vad|1.2.1
vscodeintellicode|Vis|1.1.3
azure-iot-edge|vsc|1.10.0
azure-iot-toolkit|vsc|2.3.0
vscode-java-debug|vsc|0.16.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
After step 5, what is the value of `process.env.SHELL`? Also, what does `getLazyEnv().then(r => console.log(r))` return?

**Comment by skyhiter** [comment]
When using extension `LeetCode`, I also encountered this problem. When sign in leetcode, it pops up "LeetCode extension needs Node.js installed in environment path".

if I start vscode from macOS's Dock, it will pop up this error. But if I start vscode from zsh shell, it works.

### p.s.
I have added `export PATH="/usr/local/opt/node@10/bin:$PATH"` to .zshrc file. So I am sure  the node is in environment path, but vscode extension can't find it.
