### ISSUE TITLE
CTRL+F2 Multiple Occurrence Edition fails at LineWrap-End

### ISSUE THREAD

**Issue by ksowada** [microsoft/vscode#69723]
Hi Thanks for the Great Software,
just reporting a serious issue when using CTRL+F2
when 1 Occurence is exactly wrapping at end of line, 
the used algorithm makes serious errors, 
editing at a one or more chars wrong position on the wrapped Occurence,
did supply a video, 
[VSCODE_F2_ERR.zip](https://github.com/Microsoft/vscode/files/2922705/VSCODE_F2_ERR.zip)

**Comment by alexdima** [comment]
Duplicate of #65815
