### ISSUE TITLE
Source Control - Diff View Cursor Position Resets to Top of Diff Section

### ISSUE THREAD

**Issue by nteymory** [microsoft/vscode#69729]
Issue Type: <b>Bug</b>

Steps:
- Start editing two different files in a source controlled project
- Add a large section to one of the files that spans more than one screen height
- Make any change to the other file so it will appear in the source control panel
- Open the source control panel and click the file with the large added section
- Scroll down partway through the large add section, take note of the cursor position
- Click on the other file in the source control panel
- Now click back on the file with the large added section again
- Observe that the cursor position will have jumped up towards the top of the add section, losing the previous cursor position

Expected result:
- Switching to an already open diff view for a file should not reset the cursor position
- If the diff view was never closed, the last cursor position should be maintained, like any other editor tab
- When a diff view is opened for the first time it should still jump to the first different section (as it already does)

Motivation:
Using the Source Control panel with "Toggle Side by Side View" off as a replacement for the Explorer panel as a workflow for focusing on currently modified files only. The cursor position being reset when switching back and forth between files diff views is disruptive to this workflow.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
githistory|don|0.4.6
autoconf|mae|0.0.7
prettify-json|moh|0.0.3
cpptools|ms-|0.21.0

</details>

**Comment by jmbockhorst** [comment]
I was not able to repro this. What I found was that when switching between diff editors, the cursor position was maintained (if both editors stayed open), but the cursor was not always in view. So the cursor would be at the end of the document, I would switch to another, then switch back, and the view had shifted up to the middle of the document, where the cursor was not in view.

@nt85 Maybe this is what you were trying to describe?

**Comment by nt85** [comment]
Yes, that might be right. The end result is switching back and forth between tabs causes you to lose your position
