### ISSUE TITLE
Parsing defect, parsing curly braces as syntax when within strings

### ISSUE THREAD

**Issue by prettydiff** [microsoft/vscode#69725]
- VSCode Version:
```
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```
- OS Version: Windows 10.0.17134

1. I am analyzing this code: https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js
1. I copy and pasted that code into VS Code as plain text without a language selection
1. I am adding white space between the functions to analyze the structure of the code against my parser/beautifier.  VS Code will highly the matching closing brace to a starting brace which is helpful to add whitespace between functions.
1. VS Code fails to match appropriate closing braces to appropriate starting braces if strings contain curly brace characters.  Search the code for this sequence `o+=t[n]+": {\n"` as an example of something that is tripping up the parsing.

**Comment by prettydiff** [comment]
I examined this issue against the bot's recommendations and this issue is a duplicate of those two suggestions though all these defects may result from a common cause.

**Comment by prettydiff** [comment]
Also, the parser I am working on at https://github.com/Unibeautify/sparser probably solves for all these structure problems, but its probably not fast enough for VS Code yet

**Comment by mjbvz** [comment]
Does this work properly if you set the language mode to javascript?

**Comment by prettydiff** [comment]
Yes and no.

For efficiency VS Code does not parse large blocks of code from a single line of code into a respective language with syntax coloring.  As a result, after selecting JavaScript as the language, the document remains mostly text until large code bodies are broken onto separate lines.  That means the problem persists because most of the document remains as plain text even after selecting a language.

If I manually inject line breaks periodically into the code, thereby forcing the plain text into the selected language, the problem is no longer present.
