### ISSUE TITLE
Support running tools in the custom shell / with the wrapper

### ISSUE THREAD

**Issue by MOZGIII** [microsoft/vscode#69727]
For the purposes of remote development, I need a way to run to run the tools (linters and other stuff) with a custom shell / wrapper.
The setup I want is for VS Code to run processes with my wrapper, that would ssh to a beefy server, that has my fs mounted over the network, and run the tools there (using it's cpu and memory).

This is closely related with #29194, but while that issue is tracking the "general" remote development, this one is created to address an issue with a much smaller scope: allowing running all the tools with a custom wrapper.

In other words, when VS Code needs to run `["/usr/local/bin/mybin", "myarg"]` I want it to run `["<my wrapper>", "/usr/local/bin/mybin", "myarg"]`.

Based on my understanding, this can be implemented with altering the `AbstractProcess.start` to start the processes in a wrapper.
See:
https://github.com/Microsoft/vscode/blob/f690d5e1ae8e0c9fef0e9858bcccd41554140029/src/vs/base/node/processes.ts#L171

This seems to be a rather small, quick and low effort code change, that can be properly hidden from the general availability, but the value is huge, as it allows various interesting experiments to be conducted.

What do you think?

PS: currently I'm estimating the possibility of implementing this code change myself, but I'm not sure how complicated the build process for VS Code is and if I'll be able to build it myself in the production-build-like configuration to test it in my everyday work.

**Comment by MOZGIII** [comment]
Other potential experiments with this change unlocks:
- runing tools with limied CPU/memory (cgroups/cpulimit/nice etc)
- runing tools in docker/lxc

**Comment by egamma** [comment]
These scenarios are now be covered by the VS Code Remote Extensions.
