### ISSUE TITLE
Searching in parent directory no longer works since 1.31

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#69739]
- Open the search tab
- Enter a search term
- In the "Include files", enter `..` for parent directory
- Hit Enter
- VSCode displays that no result was found, whatever the search term

Up to 1.30, it was allowed to search using a parent (or any other relative) directory. This now longer works in 1.31

This is quite a problem when you are developing a library using the following directories:

```
|- src
|- tests
     |- .vscode
```

When `tests` is opened, you would like to be able to search in `..` to search the whole library for a specific term.

**Comment by alexr00** [comment]
Verified, but you need to use `../` as your files to include, not `..`.

**Comment by roblourens** [comment]
Hm, let me see if I can fix that for this month
