### ISSUE TITLE
Html autocomplete not working in php file.

### ISSUE THREAD

**Issue by AndRoMarian** [Microsoft/vscode#69737]
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Need more details
