### ISSUE TITLE
Accessibility improvements for project-wide search

### ISSUE THREAD

**Issue by Neurrone** [Microsoft/vscode#69740]
Issue Type: <b>Bug</b>

CC: @isidorn

Hi,

Though this feature is technically useable with a screen reader, some UX improvements will go a long way towards making it much more productive.

1. The `ctrl+shift+f` keystroke brings you to an edit field to enter your query. After pressing enter to search, I use the tab key to move to the tree view of results. 

However, there are 4 tab stops between the edit field and the results list that I have to move past just to see the results:

* match whole case checkbox
* match whole word checkbox
* use regular expression checkbox
* toggle search details button

Is there a keystroke that immediately allows me to jump to the tree view? If not, it would be really helpful to add this feature. Having access to these controls is still important, but isn't needed most of the time.

2. When focusing on the results tree view for the first time, the first item in the list doesn't automatically gain focus. I use the down arrow key to move the focus to the first item in the list. This is relatively minor, but having this done automatically would be a nice touch.

3. When I am doing refactoring by e.g looking for occurances of something and changing it, this invalidates the current tree element I'm on. However, it is not attempting to remember my position at all, so I have to navigate all the way from the top of the tree again, which is painful when you have dozens of results and want to make changes to each.

I would expect it to try the following things when I return to the results tree:

* If the file has subsequent hits for the query after the one being invalidated by my edits, focus should move to the next one. For example, if my query matched on lines 10 20 and 30, I expect the results tree to move to the item corresponding to line 30 after I invalidate the match at line 20.
* If the file has no subsequent hits but there are preceeding matches that are still valid, move focus to the previous match in the same file. In this example, if I also edit line 30, move me to the item corresponding to line 10. I'm not sure if this is the best approach for this situation.
* If the file has no more matches but there are subsequent files with hits for the query, move me to the item to the node corresponding to the next matching file, so I can choose if I want to expand it or not.
* Otherwise, perform the current behaviour - set the focus to the first element of the tree. Presumably in this situation, you would have reached the end of the list.

4. This is relatively minor, but the ability to disable the arrow keys wrapping around back to the top of tree views (in general, not just in this results widget) would be useful.

VS Code version: Code - Insiders 1.32.0-insider (804373ac4d5c84e96c8086cee5b9be132df88837, 2019-03-01T18:22:35.336Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.86GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|36%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.25.0
vscode-eslint|dba|1.8.0
python|ms-|2019.2.5433
cpptools|ms-|0.21.0
Go|ms-|0.9.2
rust|rus|0.5.3
markdown-preview-enhanced|shd|0.3.11

</details>

**Comment by roblourens** [comment]
> Is there a keystroke that immediately allows me to jump to the tree view?

Yes, ctrl+down. This will also focus the first row in the tree, not the tree itself like you mentioned in 2.

> When I am doing refactoring by e.g looking for occurances of something and changing it, this invalidates the current tree element I'm on

Yes, this is a bug tracked in https://github.com/Microsoft/vscode/issues/20467. Thanks for the thoughtful comments. We recently changed the tree implementation for search and I hope that will make it easier to fix.

> This is relatively minor, but the ability to disable the arrow keys wrapping around back to the top of tree views (in general, not just in this results widget) would be useful.

Could you explain some more about why this would improve accessibility?

**Comment by Neurrone** [comment]
@roblourens so would the keystroke combination be ctrl+shift+f to move to the find widget, then ctrl+down to move to the tree?

About being able to turn off the wrapping back to the top of the tree, I feel this is unexpected behaviour since

* Doesn't match normal keyboard behaviour (we also have home and end to do this anyway)
* Also, the position of the item in a tree is typically read last after the element's label. E.g, "1 match in index.js. 1 of 30". So when moving down rapidly in the tree, its common for me to just let it read the label and interupt reading of the position by advancing. So I might wrap back to the beginning without intending to, if I'm not paying attention.

What was the original motivation for having this wrap by default?

**Comment by roblourens** [comment]
> so would the keystroke combination be ctrl+shift+f to move to the find widget, then ctrl+down to move to the tree?

Yes, there's also F4 to navigate to the next search result (with focus in the editor)

> What was the original motivation for having this wrap by default?

This is actually a recent change, @joaomoreno it sounds like a setting to disable wrapping when navigating a list/tree would be helpful for accessibility.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/69932

**Comment by roblourens** [comment]
Closing this since I think wrapping is the only unresolved issue.
