### ISSUE TITLE
Node.js debugging doesn't work

### ISSUE THREAD

**Issue by SirwanAfifi** [Microsoft/vscode#69748]
I am trying to debug a Node.js project, the project is a TypeScript project when I start the debugger it doesn't show the lines I have set the breakpoints for. so that I can't inspect values.

launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229
    }
  ]
}
```

script to run the debugger:
```json
"scripts": {
    "dev": "nodemon --inspect=0.0.0.0 --require ts-node/register server.ts",
```

**Node version**: v10.15.2
**TypeScript version**: 3.2.2
**VSCode version**: latest version
**OS**: macOS Movaje 10.14.3

**Comment by akoufatzis** [comment]
I do have a similar setup but the following **launch.json**: `{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "node",
          "request": "attach",
          "name": "Attach by Process ID",
          "processId": "${command:PickProcess}"
      },
      {
          "name": "Launch TypeScript",
          "type": "node",
          "request": "launch",
          "runtimeArgs": [
            "-r",
            "ts-node/register"
            ],
            "args": [
            "${workspaceFolder}/src/index.ts"
            ],
    
          "cwd": "${workspaceRoot}",
          "sourceMaps": true,
          "internalConsoleOptions": "openOnSessionStart",
          "env": {
            "TS_NODE_FILES":"true"
          }
      }
  ]
}`

The issue I am experiencing is that sometimes breakpoints are not hit or it seems that the debugger stopped at some breakpoint but it is inside an *async_hook.js* file at not at my code.

**Comment by weinand** [comment]
@akoufatzis please do not hijack unrelated issues like that.
Your issue is totally different:
- you are not using nodemon
- your setup works in principle but only sometimes breakpoints are not hit.

**Comment by weinand** [comment]
@roblourens I tried to reproduce the original issue with this project:
[bug69748.zip](https://github.com/Microsoft/vscode/files/2926154/bug69748.zip)

When setting a breakpoint in the TS source, I'm hitting the breakpoint in the generated (in-memory) JS (which is again called server.ts). SO we fail to correctly map the generated JS to the original TS file.

**Comment by roblourens** [comment]
This works in Insiders for me. You probably saw https://github.com/Microsoft/vscode/issues/69675. @SirwanAfifi could you try using the Insiders build? https://builds.code.visualstudio.com/insider

In the future, please include the actual vscode version instead of saying "latest version". It can help reduce confusion when you may be using the Insiders or Stable channels, or actually on an earlier version, or if we have to refer to this issue months in the future, etc

**Comment by SirwanAfifi** [comment]
@roblourens Thanks, sorry for not mentioning my VS Code Version, it's **1.31.1 (1.31.1)**
I also tested my code with VS Code Insiders and it worked thanks
