### ISSUE TITLE
OSX Rendering Flashes and Glitches on Mouse Move

### ISSUE THREAD

**Issue by HarpPDX** [microsoft/vscode#69744]
![screen shot 2019-03-03 at 10 03 06 am](https://user-images.githubusercontent.com/7102637/53699481-84e0de00-3d9d-11e9-9b9f-8faaa1485bde.png)
Issue Type: <b>Bug</b>

Status bar flashes with random rectangular glitches on mouse move.
File summary (not sure what it's called) area on right of code window flashes on/off on mouse move.
Full screen or maximized.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 5, 7|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.2.5433

</details>

**Comment by HarpPDX** [comment]
Same flashes/glitches occur with no mouse move, less frequent, approximately twice per second.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by HarpPDX** [comment]
Short test with Exploration Build looks promising.  One flashing icon on left side of status bar -- the 'close window' icon (round 'x') to the left of the error count.  The code summary is not flashing and I am not seeing random glitches in the status bar.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
