### ISSUE TITLE
Long file path showing on welcome screen

### ISSUE THREAD

**Issue by mittalyashu** [microsoft/vscode#69749]
Wasn't sure if this is an issue from Live Share or VS Code itself.

### About application
Version: 1.32.0-insider (user setup)
Commit: 804373ac4d5c84e96c8086cee5b9be132df88837
Date: 2019-03-01T18:22:35.336Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

### Steps to Reproduce:

1. Join a live share session with anyone (in VS Code Insider)
2. Exit the live share session
3. Open welcome screen

![image](https://user-images.githubusercontent.com/29014463/53701292-776d3780-3e21-11e9-9de9-4c3d4821fc5b.png)

**Comment by mittalyashu** [comment]
@Chuxel can you take a look at this issue, since I am not sure about the source of the problem, it is possible the can be from Live share too.

**Comment by Chuxel** [comment]
@mittalyashu @chrmarti Assuming this is the "guest" side, it looks like an artifact of how Live Share currently gets the join process to work.  The files are not on disk but a temporary workspace is used to flip VS Code into "Live Share mode".  There's an old issue about resolving it here: https://github.com/MicrosoftDocs/live-share/issues/78

**Comment by mittalyashu** [comment]
Great, thanks for clearing it out. @Chuxel 

I think this issue should kept open because vscode also need to improve the way they handle long path as it is shown in the issue description.
