### ISSUE TITLE
FileSystemProvider: watch() returned Disposable is never called

### ISSUE THREAD

**Issue by johnspurlock** [Microsoft/vscode#69753]
Version: 1.32.0-insider
Commit: 804373ac4d5c84e96c8086cee5b9be132df88837
Date: 2019-03-01T18:18:10.354Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Steps to Reproduce:

1. Create a custom [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider).
2. Open an editor against a file from the custom provider, the file should be outside the workspace, in case that matters.
3. Note `watch` is called as expected for the single file, with `options={"recursive":false,"excludes":[]`, return a `Disposable` to track cleanup.
4. Close the editor tab.
5. Note the `Disposable.dispose` callback is not called at this point. 🤔
6. Open the file again.
7. Note `watch` is called again with same args.  Now we have two watchers, `dispose` is never called on either of them.

Would have either expected the initial watch to be disposed when the editor tab was closed, or at least the second watch not to be sent.

Thanks!

**Comment by johnspurlock** [comment]
Verified watch dispose is now called when an editor becomes non-current, or closes.  Thanks!

Do you have suggestions on what to use as a proxy indicator for versions < 1.33 ?

Version: 1.33.0-insider
Commit: 9b849d9de7168eb4f685823bf9b9e27a0a8dae74
Date: 2019-03-08T06:57:39.083Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

**Comment by jrieken** [comment]
> Do you have suggestions on what to use as a proxy indicator for versions < 1.33 ?

No sure what you means? Would the `vscode.env.version` work or do you want to prevent your extension from running with older versions of vscode?

**Comment by johnspurlock** [comment]
The `dispose` call is a great indicator for cleaning up additional resources / polling started for the associated `watch`, but it's not reliable in 1.32.  I can at least de-duplicate `watch` calls when the same spec comes in, but It would be nice to have a similar cleanup signal somewhere in the api that works in current stable and earlier.

I suppose keeping track of [activeTextEditor](https://code.visualstudio.com/api/references/vscode-api#window.activeTextEditor) might be a good approximation, at least for watches initiated by editor focus.  Under what other scenarios is `watch` called on a custom fs provider?

**Comment by jrieken** [comment]
Yeah, active editor could work but it's hard without the correct dispose call...
