### ISSUE TITLE
Do not show single-thread in Call Stack during multi-session debugging

### ISSUE THREAD

**Issue by hoehrmann** [microsoft/vscode#69752]
Issue Type: <b>Bug</b>

When debugging with a single session and a single thread, the thread is omitted in the »call stack« hierarchy. However, if there are multiple sessions, even if they have only a single thread, the thread is included as a level in the call stack tree. In other words, is:

* Call stack
  * Process 1
    * Thread 1
      * function
  * Process 2
    * Thread 1
      * function

want:

* Call stack
  * Process 1
    * function
  * Process 2
    * function

Space is precious there if you have multiple processes.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.15.0-45-generic

**Comment by hoehrmann** [comment]
None of them is a duplicate.

**Comment by isidorn** [comment]
This is a fair feature request and I think it makes sense.
Assigning to on-deck so we look into this when we find some time.

**Comment by isidorn** [comment]
We fixed this in latest vscode that we are about to ship! Check it out and let us know what you think
