### ISSUE TITLE
Error: EPERM: operation not permitted, mkdir

### ISSUE THREAD

**Issue by nmodi** [Microsoft/vscode#69759]
Issue Type: <b>Bug</b>

**Current Behavior**
I get the following error when I run this npm script:    "build": "npm run clean && babel src --copy-files --out-dir dist"

```
{ Error: EPERM: operation not permitted, mkdir 'C:\Users\ME\codebase\myproject\myproject-project-rs\dist'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\mkdirp\index.js:71:13)
    at C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:203:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:74:103)
    at _next (C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:76:194)
    at C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:76:364
```

What's weird is that it runs correctly the first time after I start vscode, but fails every subsequent time after I stop the server with ctrl+c in the terminal. 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-styled-jsx|bla|1.0.0
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
githistory|don|0.4.6
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
output-colorizer|IBM|0.1.2
vscode-styled-components|jpo|0.0.25
wrapSelection|kon|0.6.8
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.11
color-highlight|nau|2.3.0
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
vscode-icons|rob|8.2.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.2.5
autoimport|ste|1.5.3
ayu|tea|0.18.0
sort-lines|Tyr|1.8.0
es-quotes|vil|0.2.6
vscode-todo-highlight|way|1.0.4

(9 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by nmodi** [comment]
Disabled winpty and the issue seems to be gone. Thanks!
