### ISSUE TITLE
recently history lost

### ISSUE THREAD

**Issue by PeterRock** [Microsoft/vscode#69754]
Issue Type: <b>Bug</b>

Right click on Vscode Icon at Docker, the menu can not show recently history. In detail, not lost all, only lost that you closed just now. Such as your current work folder is A, then you quit the vscode, then you cannot open A by rencently history(in OSX Dock)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|8.00GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
mithril-emmet|Fal|0.7.1
autotrim|Nat|1.0.6
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.0
react-redux-react-router-snippets|dis|0.4.29
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
beautify|Hoo|1.4.9
HTMLHint|mka|0.5.0
vscode-csscomb|mrm|5.2.2
vscode-language-pack-zh-hans|MS-|1.31.4
python|ms-|2019.2.5433
debugger-for-chrome|msj|4.11.3
vetur|oct|0.16.2
stylelint|shi|0.48.0
code-spell-checker|str|1.6.10
full-react-snippets|wal|1.2.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
code-template-tool|yua|0.5.1

</details>

**Comment by bpasero** [comment]
@PeterRock can you check that linked issue and see if you can reproduce at all?

//cc @aeschli @sandy081 ever since a while I get an increasing number of issues where people say that the right click menu on the dock (or taskbar on windows) is missing entries. If you can recall any changes on your end that could have an impact (string => URI conversion) please speak up.

**Comment by sandy081** [comment]
@bpasero Not aware of any changes that could impact this. I am sure that this case is covered during testing.

**Comment by PeterRock** [comment]
Thanks for proving the linked issue.
I fixed the issue by clean all recent history and it works right now.
