### ISSUE TITLE
Feature: Better color picker interface.

### ISSUE THREAD

**Issue by AndRo-Marian** [microsoft/vscode#69750]
A drop down to select what type of color i want to save in file. RGB, HEX or hsl, etc.
Number boxes for rgba values.

Maybe to appears the ColorPicker when clicks to preview color.

Only a idea.

**Comment by beastdestroyer** [comment]
Imo i would really like a "History" feature as I find myself experimenting with colours a lot in my designs, and also during testing. It would make life easier i think.

Definitely agree with OP here that we should have a choice of colour scheme. Whilst I stick with RGBA/HEX all the time, I think it would be an easy convert: ie not only can we type in values, but we can see equivalents in other schemes
