### ISSUE TITLE
JavaScript JSDoc not working

### ISSUE THREAD

**Issue by AndRoMarian** [Microsoft/vscode#69751]
Old: https://github.com/Microsoft/vscode/issues/514

I found the document.createElement() return the correct element name.
But why i can't use JSDoc in JS to override @type, @param, @returns to set the type for document.getElementById() or for Parameters. How supposed to be ?

I don't want to use TypeScript to create other files to compile to .js.

I like to see this to happen.

**Comment by mjbvz** [comment]
Please provide a code example of what you are trying to do

**Comment by AndRoMarian** [comment]
I don't know the reason but now i see to working to set the type of variable: For: getElementById and the return type, param type of the function.
