### ISSUE TITLE
MarkdownString support command arguments

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#69757]
Issue Type: <b>Feature Request</b>

https://github.com/Microsoft/vscode/blob/e96ab81392ec49effa0369f4f086be8c128e5e2f/src/vs/vscode.d.ts#L2336-L2347

`[Run it](command:myCommandId)`

This may require a new discussion to implement

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by jrieken** [comment]
It does support args, use the query-part of the uri.

**Comment by axetroy** [comment]
Thanks @jrieken

I tried the way of query.

but this can't get the parameters

the is the example

```markdown
[Install it](command:npmversion.install?query=123)
```

```ts
commands.registerCommand('npmversion.install', (a, b, c) => {
  console.log('params', a, b, c);
  // print `undefined, undefined, undefined`
});
```

I suspect that I am using it wrong or this is a bug.

I am very sorry to bother you again.

I can't find an example in the documentation and can't join slack.

can you write a simple example?

**Comment by jrieken** [comment]
It must be an json-stringified and url-encoded string, e.g. `encodeURIComponent(JSON.stringify({a: true}))`

**Comment by axetroy** [comment]
@jrieken thanks

Resolved and update the above example for others

```js
const mdStr = new MarkdownString();
const params = encodeURIComponent(JSON.stringify({ a: true }));
mdStr.value = `[Install it](command:npmversion.install?${params})`;

commands.registerCommand('npmversion.install', (params) => {
  console.log(params)  // { a: true }
});
```
