### ISSUE TITLE
How to delete to the indent?

### ISSUE THREAD

**Issue by bflatmajor** [microsoft/vscode#69758]
Like <kbd>⌘</kbd> <kbd>⇧</kbd> <kbd>⌫</kbd> in Sublime Text:

![delete-to-indent](https://user-images.githubusercontent.com/14685751/53708099-c7bdb700-3e6c-11e9-97c4-e80b82434f36.gif)

**Comment by Jta26** [comment]
Typically, at least on windows and linux, to unindent something its Shift + Tab

**Comment by gnirob** [comment]
@Jta26 Thank you, but I didn't mean that, you could check the screenshot again.

**Comment by usernamehw** [comment]
You can take any extension that runs multiple commands and execute those 2:
```json
"deleteAllLeft",
"tab"
```

**Comment by gjsjohnmurray** [comment]
I can already do it with a maximum of three keystrokes (Windows variant shown):

```End, Shift+Home, Delete```

or:

```Home, Shift+End, Del```

In both cases ⌫ can be used in place of Delete.

If you are already at the end of the line, only two keystrokes:

```Shift+Home, Delete```

Of course, that's still at least one more keystroke than you want.
