### ISSUE TITLE
KeyBindings: Inconsistent When Clause editing

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#69760]
Insiders: 3-3-19
Windows10

Issue Type: <b>Bug</b>

Editing the when clauses produces inconsistent results:
- Try editing first entry "Add Cursor Above"
- Try changing to "editorFocus" - remains original value
- Change to "editorTextFocus && !editorReadonly" - should stick
- Try editing to original  "editorTextFocus" - entry remains as above
- Reset binding - should be able to change again

- Also there does not seem to be a way to change an existing entry to blank "--" for a global entry

VS Code version: code-oss-dev 1.33.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (19.40GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.4.0

</details>

**Comment by alexandrudima** [comment]
@cleidigh Are you doing your edits in the "UI":

![image](https://user-images.githubusercontent.com/5047891/53740271-1f234d80-3e94-11e9-9f38-6f419a6cef29.png)

or in `keybindings.json`?

**Comment by cleidigh** [comment]
@alexandrudima 
The problem and reproduction steps were done within the UI.
Issue 1: Once you have edited a when clause once, a second edit does not work ( the clause remains the value after the first edit)
If you reset the binding then you can change it again once.
My first example changes editorTextFocus -> editorTextFocus && !editorReadonly (successful)
Now try to change to anything else original, drop the negation or delete everything (no change accepted)
Edits to the JSON file directly appear to behave correctly.

Issue 2:  I have no way within the UI to change a when clause to blank (no clause)
