### ISSUE TITLE
Ctr+F Find in file not working anymore.

### ISSUE THREAD

**Issue by kishanvasoya1** [Microsoft/vscode#69769]
Issue Type: <b>Bug</b>

search from file not working.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-autocomplete|chu|0.2.13
apex-pmd|chu|0.4.1
vsforce|cov|0.2.0
mavensmate|Dav|0.15.0
apex|Joh|0.0.2
notepadplusplus-keybindings|ms-|1.0.2
material-icon-theme|PKi|3.6.3
salesforcedx-vscode-apex|sal|45.3.0
salesforcedx-vscode-apex-debugger|sal|45.3.0
salesforcedx-vscode-apex-replay-debugger|sal|45.3.0
salesforcedx-vscode-core|sal|45.3.0
salesforcedx-vscode-lightning|sal|45.3.0

(7 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please provide more details

**Comment by ItzLevvie** [comment]
I believe it's related to https://github.com/Microsoft/vscode/issues/69819?
