### ISSUE TITLE
Debugger breaking in js read-only core module

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#69764]
Using the latest insiders and debugging a basic typescript app, when the debugger breaks on a break point, a javacript file opens instead. This does not repro in stable. I tried this in master as well and it also is broken.

![image](https://user-images.githubusercontent.com/6561887/53715130-df6e4e80-3e1e-11e9-8cd6-fe03b2778459.png)

**Comment by martimarkov** [comment]
@sbatten what is the duplicated issue?

**Comment by sbatten** [comment]
@martimarkov I don't recall where the duplicate is, but please open a separate issue as that one I know was resolved
