### ISSUE TITLE
PowerShell comment syntax highlight is not correct.

### ISSUE THREAD

**Issue by stefanita-mitran** [Microsoft/vscode#69771]
We have written the needed data into your clipboa
Issue Type: <b>Bug</b>

The highlight syntax for comments is wrong for PowerShell files.
EG.
```
.\procedure.ps1 `
   -arg1 $variableforarg1 ` #this syntax highlighting should not resemble a comment
   -arg2 $variableforarg2 ` <#this syntax highlight should not resemble a comment because it's invalid to add a comment here #>
   -arg3 $variableforarg3 <#this syntax higlight should be correct#>`
   -arg4 $variableforarg4
```

The example above shows that the "arg1" and "arg2" have incorrect comments and should not by syntax higlighted as comments.

For me saddly as a beginner powershell user this was an issue when trying to deploy :(. Just want to make that you have a visual cues when using this and not commit a faulty powershell script in production like me.
P.S. if you use the PowerShell ISE it will syntax highlight correctly. 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (15.24GB free)|
|Process Argv|C:\Users\stem\Documents\Repos\track-system\TrackServices\Database\schema\58_upgrade_from_v57_to_v58.sql|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
gc-excelviewer|Gra|2.1.29
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vetur|oct|0.16.2

</details>
rd because it was too large to send. Please paste.

**Comment by alexr00** [comment]
@stefanita-mitran I can reproduce this, but it also occurs in PowerShell ISE. I'll move this issue to the owners of the PowerShell grammar.

**Comment by alexr00** [comment]
This issue was moved to PowerShell/EditorSyntax#161
