### ISSUE TITLE
Uninstalling "debugger" extensions does not correctly un-merge their contributions

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#69772]
see the code around here https://github.com/Microsoft/vscode/blob/2469f39a58d457f6f206a4f5c0e7be28446f9af2/src/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.ts#L255

**Comment by isidorn** [comment]
I confirm this issue.
It might be more complex to fix this, since we need to write an unmerge function.
Moving this to on-deck.
Please let me know if you depend on this and I can put it back to March. Thanks
