### ISSUE TITLE
Multiple Files Highlighted in Explorer

### ISSUE THREAD

**Issue by developcodeza-matthew** [Microsoft/vscode#69774]
Issue Type: <b>Bug</b>

When alt-tabing between open files the explorer highlights both the current file, as well as the previous file I was just on. I can not recall seeing this untill around the December update. 

Is this expected behaviour? 

![screen shot 2019-03-04 at 12 15 17 pm](https://user-images.githubusercontent.com/26629247/53726800-6e0eba00-3e77-11e9-8850-ecbd7c7601cf.jpg)

I do have explorer.autoReveal: true set.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
vscode-eslint|dba|1.8.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
Angular2|joh|7.0.1
Kotlin|mat|1.7.0
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.6.3
code-spell-checker|str|1.6.10
html-css-class-completion|Zig|1.18.0

</details>

**Comment by isidorn** [comment]
This is fixed in latest insiders
