### ISSUE TITLE
Selecting a multi-line object and moving it down causes diagonal movement

### ISSUE THREAD

**Issue by davidpox** [microsoft/vscode#69777]
Issue Type: <b>Bug</b>

Selecting a multi-line object and moving it down over other lines using Alt + Down causes the select lines to indent every time. Moving them up once with Alt + Up resets the line to the normal indentation.

Steps to reproduce: 
1. Create a sample code file (I use JS & ES6)
2. Create an object anywhere above some lines of code such as 
```js
let test = {
    t: 1
};
```
3. Select lines either through mouse selection or Shift & arrow keys
4. Hold Alt and press the down arrow key several times and observe said behaviour. 

[GIF demonstation](https://i.imgur.com/xT0qPUb.gif)

Confirmed reproducing with all extensions disabled & window reload.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gltf-vscode|ces|2.2.3
vscode-eslint|dba|1.8.0
vsc-material-theme|Equ|2.7.0
beautify|Hoo|1.4.9
intellij-idea-keybindings|k--|0.2.31
debugger-for-chrome|msj|4.11.3
vscode-icons|rob|8.2.0
code-settings-sync|Sha|3.2.5
shader|sle|1.1.4
autoimport|ste|1.5.3
ayu|tea|0.18.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by iamanders** [comment]
I'm having the exact same error. Alson when moving single rows. And only when I move rows down. When moving rows up they get the correct indentation.

I get "diagonal movement" in HTML and CSS-files. Even on a blank/fresh vscode install without any extensions. But does not seems to affect all files, PHP files seems to indent correctly.

**Comment by RobinBlomberg** [comment]
This drives me crazy, as I('d like to) move around lines a lot.

It happens on both my machines, with .css, .html, .js and .tsx files (but not .json, .md, .yml). It has happened ever since I switched to VSCode (so at least two months). It only happens on Alt+Down (Alt+Up is fine).

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by tommulkins** [comment]
I only seem to experience this issue when moving multiple lines where the lines are already indented and moving them either up or down.

I agree it's really annoying but something I've found that helps a bit is to code fold your function, object, etc then highlight with your mouse.  Move using Alt or Opt + ⇅, then let prettier handle the rest on save.  Not ideal I know. 😕
