### ISSUE TITLE
代码缩进乱跳！！！！！！！

### ISSUE THREAD

**Issue by Half8Man** [Microsoft/vscode#69773]
代码缩进乱跳！！！！！！！代码缩进乱跳！！！！！！！代码缩进乱跳！！！！！！！

**Comment by DemonCloud** [comment]
@Half8Man  1没动态图，2不提供系统不系统详细信息，不要给支那人丢脸了，麻烦了。

**Comment by ddzy** [comment]
> 代码缩进乱跳！！！！！！！代码缩进乱跳！！！！！！！代码缩进乱跳！！！！！！！

???
