### ISSUE TITLE
Big performance issues

### ISSUE THREAD

**Issue by Vlad412** [Microsoft/vscode#69786]
Issue Type: <b>Performance Issue</b>

Hello, my vs code is extremely laggy and I reinstalled fresh vs code without extentions, I tried vs code insiders and it's pretty much the same. What can I do to improve it, it's like crazy that text editor is laggy if it was a game, I really love it so I just want to continue using it (I use it on my big computer with rtx 2070 and it's working well xD )
I'm currently on a thinkpad lenovo T480 with integrated gpu,
thanks and good day !

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.53GB free)|
|Process Argv|D:\Files\Documents\work\Sources\work\jhipster\project1|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	 10420	code main
    0	    64	  1928	   shared-process
    0	   165	  9584	   gpu-process
    0	    66	 10756	   window (Issue Reporter)
    0	   213	 11928	   window (password-strength-bar.tsx - project1 - Visual Studio Code)
    0	    11	  3788	     watcherService 
    0	    11	  4244	       console-window-host (Windows internal process)
    0	    13	 12012	     electron-crash-reporter
    0	    68	 16160	     extensionHost
    0	   141	  4180	       electron_node tsserver.js 
    0	    43	  4816	         electron_node typingsInstaller.js typesMap.js 
    0	    39	 10140	       "C:\Users\Vlad_\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Vlad_\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=16160
    0	    35	 16952	       "C:\Users\Vlad_\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Vlad_\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=16160
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (password-strength-bar.tsx - project1 - Visual Studio Code)
|    Folder (project1): 525 files
|      File types: java(95) class(87) json(87) tsx(45) ts(42) png(35) js(27)
|                  yml(23) html(15) css(12)
|      Conf files: settings.json(2) package.json(1) tsconfig.json(1)
|                  tslint.json(1);
```

</details>
Extensions: none

**Comment by joaomoreno** [comment]
Please go through https://github.com/Microsoft/vscode/wiki/Performance-Issues and let us know more information.
