### ISSUE TITLE
A task description/detail propery in tasks.json

### ISSUE THREAD

**Issue by jorisvanderpol** [microsoft/vscode#69785]
Hi,

A workspace with a large number of tasks could do with a task description property. When selecting a task to run from the command palette, show the description of the selected task below the task.

This is also nice for the onboarding of new team members.

**Comment by alexr00** [comment]
Once this is proposed we also need to change the tooltip in the npm explorer to behave better. (@egamma FYI)

**Comment by alexr00** [comment]
Current:
```typescript
	/**
	 * A structure that defines a task kind in the system.
	 * The value must be JSON-stringifyable.
	 */
	export interface TaskDefinition {
		/**
		 * The task definition describing the task provided by an extension.
		 * Usually a task provider defines more properties to identify
		 * a task. They need to be defined in the package.json of the
		 * extension under the 'taskDefinitions' extension point. The npm
		 * task definition for example looks like this
		 * ```typescript
		 * interface NpmTaskDefinition extends TaskDefinition {
		 *     script: string;
		 * }
		 * ```
		 *
		 * Note that type identifier starting with a '$' are reserved for internal
		 * usages and shouldn't be used by extensions.
		 */
		readonly type: string;

		/**
		 * Additional attributes of a concrete task definition.
		 */
		[name: string]: any;
	}
```
Proposal is to add:
```typescript
            		readonly description?: string;
````

**Comment by alexr00** [comment]
The description would be shown in the task quick pick with the task.

**Comment by jorisvanderpol** [comment]
How will the description be shown? For example under or next to each task in the task list or when hovering over a task in the task list using a tool tip (to save space)?

**Comment by alexr00** [comment]
It is shown in the quick pick detail spot:
![image](https://user-images.githubusercontent.com/38270282/67296473-cb2fac80-f4e8-11e9-84e6-1e54e387da35.png)
The quick pick description spot is taken already by tasks in a multiroot workspace. 

I ended up making the property `detail` and putting it on `Task` as it doesn't really belong in the definition.

**Comment by alexr00** [comment]
I also added a setting to turn this off: `"task.quickOpen.detail"`

**Comment by alexr00** [comment]
Reopening so that we don't forget to finalize this API.

**Comment by elahehrashedi** [comment]
@alexr00 The details are not shown all the time, for example, running the command "Tasks: Run build task" shows the details:
![image](https://user-images.githubusercontent.com/16143955/90464155-8dc48d00-e0c1-11ea-9cde-f54415637065.png)

But running "Tasks: Configure task" doesn't show the details:
![image](https://user-images.githubusercontent.com/16143955/90464290-d1b79200-e0c1-11ea-9e50-bc6f2dd876d6.png)

**Comment by alexr00** [comment]
Good find, I have opened a bug to fix this: https://github.com/microsoft/vscode/issues/104911

**Comment by elahehrashedi** [comment]
@alexr00 I am trying to modify the `detail `of a task when I resolve it in `TaskProvider::resolveTask`, but I can't see this modification to be effective.
As I understood, the tasks that are read from the tasks.json file will be resolved first. I want to be able to modify the `detail `of such a task while resolving it only for the purpose of differentiating between the _tasks that are detected_ and the _tasks that are read from the tasks.json file_ (Note: I am not intending to modify the Json file).
However, when I modify the detail, I can't see the modification. 

For example, the first 3 tasks are from tasks.json file and the next three are detected tasks (the current behavior is as below):
![image](https://user-images.githubusercontent.com/16143955/90555131-c0b36300-e14b-11ea-915a-afe114c0a631.png)

While resolving the tasks in `resolveTask`, I am modifying the `detail `, and I expect this modification to be effective (as below), but it is not.
![image](https://user-images.githubusercontent.com/16143955/90554812-41be2a80-e14b-11ea-87ce-b4a06b6be7e8.png)
![image](https://user-images.githubusercontent.com/16143955/90555033-9661a580-e14b-11ea-99a8-6ec1678826e1.png)

**Comment by alexr00** [comment]
To make the task quick pick (the list of tasks you show in your screen shots) as fast as possible, **no tasks** are resolved when the quick pick is shown. This means that only the stored data about a recently used task or the data from tasks.json is used.
