### ISSUE TITLE
Strongly recommend remove felixfbecker/* from PHP Pack vscode recommends, and replace to bmewburn/vscode-intelephense instead

### ISSUE THREAD

**Issue by xiaohuilam** [microsoft/vscode#69789]
As many PHPers' experience, felixfbecker's intellisense extension has many troubles that bmewburn/vscode-intelephense do not has:

- **Architectural defect**
  - **CPU bound**, because felixfbecker extension is using php-written language server, which have so many synchronize and blocking internal functions. what issue that can cause? for example: you are trying auto complete one class, and the same time you can't using other function if your cpu is only one thread.
  - **Memory pollution**, when one thread exceptions, you have highly possibility lost communication with the vscode extension before you restart extension host.
- **Function missing**
  - felixfbecker do not support `@property` annotation, `@mixin` annotation, and do not support intellisense other annotations' class.
  - felixfbecker is not including format code function.
  - felixfbecker is not including `$var` referenced or not checking function.
- **Out of maintained**. felixfbecker's last release is three months ago, and there are 203 issues(server + vscode-ext) remaining. but bmewburn is 59 issues instead(including long time ago `needs more info` labelled issues)

As the reasons upon, I'm here, highly recommending vscode maintainers to try these two extensions, and then considering am i right to complain upon words.

**Comment by egamma** [comment]
VS Code now also recommends `bmewburn/vscode-intelephense`.
