### ISSUE TITLE
Outline view title should 'Gliederung' (not 'Kontur') in German

### ISSUE THREAD

**Issue by snapmackz** [microsoft/vscode#69788]
Issue Type: <b>Bug</b>

Title 'Kontur' doesn't seem to be fitting - even the placeholder text if no editors are open mentions '...Gliederung...' instead of '...Kontur...'

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

**Comment by weinand** [comment]
@jrieken fyi, the Outline view is still "Kontur" in the latest...

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.
