### ISSUE TITLE
Feature request:  Allow zooming with ctrl+mousewheel combination

### ISSUE THREAD

**Issue by cookch10** [Microsoft/vscode#6978]
- VSCode Version:  1.1.1
- OS Version:  Windows 7 x64

It would be great if holding the `Ctrl` key + spinning the mouse wheel would increase / decrease the VS Code zoom value.

**Comment by bpasero** [comment]
I am not sure we want to zoom the entire UI when you use the mousewhell, I would expect only the editor font to increase. Thereby moving to @alexandrudima

**Comment by cookch10** [comment]
@bpasero, yes you are correct.

**Comment by pcgeek86** [comment]
Didn't this feature used to work, or am I just failing to remember correctly? I was just going to report this as a bug, but maybe it never actually worked. I jump between different computer setups fairly regularly, so maybe I am just not remembering. Anyway, I found this dupe, and didn't want to submit a new issue. Thanks for your efforts @bpasero.

By the way, I think I would expect this feature to work the same way that `CTRL + +` and `CTRL + -` work. VSCode's UI deviates from many other UIs in that it scales well, so I think I'd expect this to scale the entire UI consistently with the keyboard commands.

**Comment by seesharprun** [comment]
If this zooms only the editor, shouldn't it be seperate from ``Ctrl + +``?

**Comment by coreh** [comment]
I would expect `Ctrl +` and `Ctrl -` to zoom only the editor. That behaviour would be consistent with most (all?) other editors and apps. Scaling the entire interface is an accessibility feature IMO, so maybe it doesn't need to use such a commonly used shortcut by default?

Beyond Ctrl+Wheel, pinch to zoom should also zoom the editor.

**Comment by pierznj** [comment]
Can this be disabled? I'm constantly accidentally zooming my text to a tiny size when I ctrl-click and accidentally brush my fingers over the trackpad.

**Comment by alexandrudima** [comment]
@pierznj This is disabled by default, so you must have enabled it in the past -- `"editor.mouseWheelZoom": false`

**Comment by DarrenCook** [comment]
@alexandrudima Thanks - I came here to vote for this feature, and it turns out I just had to turn it on!

Shouldn't this issue be closed?

**Comment by alexandrudima** [comment]
:+1: Closing since this is implemented. The feature is disabled by default due to numerous issues reported by users using touchpads where we begin to unexpectedly zoom in/zoom out when e.g. using ballistic scrolling and pressing the ctrl/cmd modifier. The root problem is that we cannot differentiate `mousewheel` events coming in from a real mouse with a wheel from those coming in from touchpads / trackpads.
