### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by ShadyGaDa** [Microsoft/vscode#69781]
How long does it take to fold code?
Answer "If you're Microsoft an infinite amount of time"

**Comment by aeschli** [comment]
Can you give more details? Code folding is slow? Can you attach a sample code that shows that?

**Comment by ShadyGaDa** [comment]
What I mean is there is no "Toggle Code Fold" option.
In every other editor Sublime, Brackets, Notepad3, SynWrite....... There is.
Why?

**Comment by aeschli** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_folding

Note that code folding can be disabled by an option (`editor.folding`). Also, in screen reader mode, folding is disabled.

**Comment by ShadyGaDa** [comment]
I think you are avoiding the fact there are no easy menu choices for "Code folding"
Why would i want to know how to disable something i want to enhance?
Lets face it the most useful ability of an editor is to flexibly fold code.
I do not want to pop open and close 1000's of lines of code one by one.
Is there any one developing this editor that knows what i mean.

**Comment by gjsjohnmurray** [comment]
@ShadyGaDa - is your complaint that you didn't find code folding options on a menu off the menubar, or on a context menu? Did you follow the doc link @aeschli gave at https://github.com/Microsoft/vscode/issues/69781#issuecomment-469429070 to see the extensive set of key sequences to fold and unfold?

**Comment by ShadyGaDa** [comment]
So why can't you put it on the menu, like everyone else?

**Comment by gjsjohnmurray** [comment]
@ShadyGaDa you might like this small extension I just published.

[The Folding Stuff](https://marketplace.visualstudio.com/items?itemName=georgejamessoftware.thefoldingstuff)

It adds a few folding and unfolding options to the context menu.
