### ISSUE TITLE
Broken Save Dialog layout on Ubuntu 18.10 

### ISSUE THREAD

**Issue by x1unix** [Microsoft/vscode#69794]
- VSCode Version: 1.31.0
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Create a file in *VS Code* and press `Ctrl`+`S`
2. Save dialog will appear with broken appearance and layout

**Note**: This issue is not related to installed GTK theme (it appears on any used GTK theme, including default Advaita theme)

Also this issue appears on other Electron apps, not just VS Code

![2019-03-04 19-30-05](https://user-images.githubusercontent.com/9203548/53751140-47bb3f80-3eb4-11e9-94b8-26d72c343972.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Are you using the snap package?

**Comment by Sovgut** [comment]
I also have a non-native theme in ubuntu 18.10, but I don’t see such a problem
![image](https://i.imgur.com/N8AszA2.png)

**Comment by Sovgut** [comment]
Maybe the problem in gtk?

**Comment by x1unix** [comment]
@joaomoreno I'm using a snap package.

**Comment by x1unix** [comment]
@Sovgut I don't know. This issue occurs with Electron apps.

Also GTK library is not included in the snap package.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/57019
