### ISSUE TITLE
Support cell-by-cell navigation to allow links to be keyboard accessible and more fine grained keyboard selection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#69795]
Two potential solutions:

- Allow navigating the buffer cell by cell and maybe enter to activate a link
- ~~Enter a "link navigation mode" which allows navigating through just links~~ (this is handled by the open/detect link commands
- Shift to select text

**Comment by Tyriar** [comment]
The discussion in https://github.com/xtermjs/xterm.js/issues/583#issuecomment-545678744 affects how this would be implemented so it's blocked on that.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/87579 asks for selecting up page/cell, updated the title.

**Comment by meganrogge** [comment]
This is done with https://github.com/microsoft/vscode/pull/174400
