### ISSUE TITLE
VS Code replace file manager in super + e shortcut bug

### ISSUE THREAD

**Issue by filippfarias** [Microsoft/vscode#69790]
The VS code replace the default File Manager in super + e shortcut.

My solution for Deepin Linux:
Edit as admin the file mimeinfo.cache in /usr/share/applications

In the line ``` inode/directory= ```

might appear ``` dde-file-manager.desktop; ``` as second option. Just put it first and save.

**Comment by roblourens** [comment]
Sorry I don't really understand what you're saying, can you explain in more detail?

**Comment by filippfarias** [comment]
> Sorry I don't really understand what you're saying, can you explain in more detail?

In Linux Deepin, when you install the VS Code, it overwrites the default file manager, so the shortcut SUPER + e (WIN + e for Windows) used to open the file manager open the VS Code.
