### ISSUE TITLE
[Debug] Filter "Call Stack" panel based on thread state

### ISSUE THREAD

**Issue by rrmistry** [Microsoft/vscode#69793]
We are trying to debug a large application with hundreds of threads.

The breakpoint feature is nice to use, but our heavily threaded application triggers dozens of threads to break simultaneously with a single breakpoint.

Proper design discussions aside, it would be very helpful to have a filter feature that can, at the very least, limit call stack display by thread states:

- `Running`
- `Paused On Breakpoint`
- `Paused On Step`

With this feature, we would be better able to monitor overall application state.

Get affected thread count, etc.

Release threads in a controlled fashion for a better debugging experience.

The new tree view filter for the explorer pane, as of version 1.31.1, is quite nice to use and inconspicuous. A similar feature for the call stack filter would be very help (if not planned already).

Thank you!

**Comment by isidorn** [comment]
@rrmistry currently you can click in the callstack view and start typing. You can toggle it in the widget that appears to make it a filter.
This currently only filters based on thread name, but if you like this experience we could also add that it filters on thread state.
That way you would type "paused on breakpoint" and only those threads which have that state would be shown.
Let me know what you think

![filter](https://user-images.githubusercontent.com/1926584/53792331-b8ea0980-3f2b-11e9-8795-7fbe152597ba.gif)

**Comment by isidorn** [comment]
Makes sense.
It will be available in insiders end of week. And in our next next stable (in more than a month)

**Comment by andrei-pokrovsky** [comment]
Hi, is this feature available yet? I tried the latest insiders but can't seem to activate it.

**Comment by isidorn** [comment]
yes.
Just click on the call stack and start typing
