### ISSUE TITLE
Intellisense suggestions keep changing

### ISSUE THREAD

**Issue by josebalius** [microsoft/vscode#69798]
This report: https://github.com/Microsoft/vscode/issues/60753 is still happening for me, it is pretty bad at times, I keep having to "wait" until the update happens to have a stable list of suggestions I can select from, if I don't, I usually end up with the wrong selection being made (because the suggestions update randomly). #60753 is the only report I could find of this and the gif is exactly what happens to me, are there any updates on this?

- VSCode Version: 1.31.1
- OS Version: Mojave 10.14

Steps to Reproduce:

It's hard to say, at times it seems random, other times it happens almost every time.

**Comment by jrieken** [comment]
With what language is that?

**Comment by josebalius** [comment]
@jrieken It seems to happen with Go most of the times. Do you think this is related to the extention and not VSCode itself?

**Comment by jrieken** [comment]
This should be fixed - we have removed any re-filter delay/debounce with a recent fix. Please try this with latest insiders or next (june) stable release
