### ISSUE TITLE
Not able to run PowerShell scirpt

### ISSUE THREAD

**Issue by heyuyue** [Microsoft/vscode#69805]
I am not able to run any powershell script and it's not allow to enter command in Powershell Integrated console. 
For Example: Run 'Connect-AzureRmAccount' command and got "ConsoleFeature>: Unable to instantiate; language client undefined." error.
I tried to uninstall Visutal studio code and extension and installed it again. I am still getting same issue.
Here is detail log.
3/1/2019 12:33:54 PM [NORMAL] - Visual Studio Code v1.31.1 64-bit
3/1/2019 12:33:54 PM [NORMAL] - PowerShell Extension v1.11.0
3/1/2019 12:33:54 PM [NORMAL] - Operating System: Windows 64-bit
3/1/2019 12:33:54 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
3/1/2019 12:33:54 PM [NORMAL] - Language server starting --
3/1/2019 12:33:54 PM [NORMAL] -     exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
3/1/2019 12:33:54 PM [NORMAL] -     args: C:\Users\nha4996\.vscode\extensions\ms-vscode.powershell-1.11.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.11.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\nha4996\.vscode\extensions\ms-vscode.powershell-1.11.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\nha4996\.vscode\extensions\ms-vscode.powershell-1.11.0\logs\1551465234-c1a354f0-2ae2-4f8a-b6ee-48282eaed58e1551465209912\EditorServices.log' -SessionDetailsPath 'C:\Users\nha4996\.vscode\extensions\ms-vscode.powershell-1.11.0\sessions\PSES-VSCode-11740-936029' -FeatureFlags @()
3/1/2019 12:33:55 PM [NORMAL] - powershell.exe started, pid: 10480
3/1/2019 12:34:02 PM [NORMAL] - Language server started.
3/1/2019 12:34:02 PM [NORMAL] - {"languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_akzi2fn4.tau","debugServiceTransport":"NamedPipe","status":"started","debugServicePipeName":"\\\\.\\pipe\\PSES_zpkbqacj.dp1"}
3/1/2019 12:34:02 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_akzi2fn4.tau...
3/1/2019 12:36:54 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
3/4/2019 11:03:37 AM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
3/4/2019 2:53:54 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.

**Comment by joaomoreno** [comment]
https://github.com/PowerShell/vscode-powershell
