### ISSUE TITLE
Terminal empty w/ PS after opening vs code

### ISSUE THREAD

**Issue by edowney29** [Microsoft/vscode#69809]
- VSCode Version: 1.31.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open VS Code
2. Press ctrl + `
3. Start typing

![f9624617b4805b0307acc4246184b294](https://user-images.githubusercontent.com/14062239/53766298-77f8e300-3ea0-11e9-885b-7985eccdbb0d.png)
![f6d3bf7c5adcccd637cb75ae14645439](https://user-images.githubusercontent.com/14062239/53766301-792a1000-3ea0-11e9-9f20-0e3c2344a5f4.png)
![1ca849301cb37ba308c9e2b64b0217f8](https://user-images.githubusercontent.com/14062239/53766305-79c2a680-3ea0-11e9-8d18-76897dab009c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
