### ISSUE TITLE
Error when querying HDInsight

### ISSUE THREAD

**Issue by haveyoumetcp** [Microsoft/vscode#69802]
Issue Type: <b>Bug</b>

Get the following error when trying to query HDInsight with ADLS Gen 2 is the primary storage:
[Error] parse storage account error: "fs.defaultFS"

Extension version: 1.1.1
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.65GB (0.46GB free)|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
What makes you think this is an issue with VS Code?

**Comment by haveyoumetcp** [comment]
Because I get the error in VSCode and I don't get it ib Visual Studio or anywhere else.
________________________________

**Comment by joaomoreno** [comment]
What extension is this about?

**Comment by haveyoumetcp** [comment]
The HDInsight extension.  When I submitted the bug, I selected that extension, so not sure why it didn't carry over to this bug.

**Comment by joaomoreno** [comment]
https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight

> Found a Bug? - contact hditooling@microsoft.com
