### ISSUE TITLE
Can't browse to folder, VS Code just opens the first one I click on

### ISSUE THREAD

**Issue by Jvalal** [microsoft/vscode#69806]
See video. 2 weeks ago I could deep browse to various folders and then open, but now, it opens the first folder I click on instead of browsing deeper. 

 

[VSCode.mov.zip](https://github.com/Microsoft/vscode/files/2928196/VSCode.mov.zip)

**Comment by chrisdias** [comment]
I can't reproduce this.  Can you try disabling all extensions?

**Comment by Jvalal** [comment]
Still does it with all extensions disabled. 
[VSCode2.mov.zip](https://github.com/Microsoft/vscode/files/2928675/VSCode2.mov.zip)

**Comment by bpasero** [comment]
@Jvalal can I ask you how to bring up the dialog exactly?

**Comment by Jvalal** [comment]
Cmd-o

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Jvalal** [comment]
Sems to be happening there too.  
[VSCode.mov.zip](https://github.com/Microsoft/vscode/files/2932070/VSCode.mov.zip)

**Comment by bpasero** [comment]
@Jvalal really weird, I cannot explain that behaviour. It almost seems to me like on your Mac doubleclicking on a folder acts like picking it instead of expanding it. I do not think this is something VSCode can change, but if someone has more ideas, please feel free to state them.

**Comment by Jvalal** [comment]
Correct. But as you can see, it only happens in VSCode, not when I try and browse via, let's say GMail, attached. 

[VSCodePick.mov.zip](https://github.com/Microsoft/vscode/files/2932124/VSCodePick.mov.zip)

**Comment by bpasero** [comment]
Yeah, I am out of ideas, sorry. Is this a regression, was it working before?

**Comment by Jvalal** [comment]
thanks. Yes, I think it's a regression as it was working before.

**Comment by bpasero** [comment]
@Jvalal you are on 1.31 right? Can you try with 1.30? Download: https://az764295.vo.msecnd.net/stable/61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8/VSCode-darwin-stable.zip

**Comment by Jvalal** [comment]
Ok, I may have figured out something here. If you look, when I click on any other folder, that isn't my "Projects" folder, they open as expected, but when I try and open that Project folder it picks it vs. expanding?? Any thoughts?
[VSCode.mov.zip](https://github.com/Microsoft/vscode/files/2937771/VSCode.mov.zip)

**Comment by chrisdias** [comment]
Is the folder backed up with iCloud? i see a green dot and a cloud icon next to it in the explorer...maybe that's a clue.

**Comment by Jvalal** [comment]
It is, but this issue is new. It's always been a cloud folder and I didn't have this issue a few weeks ago.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by Jvalal** [comment]
hi - no dice. Notice it also does it on my adobe folder too.


[VSCodeExp.mov.zip](https://github.com/Microsoft/vscode/files/2942193/VSCodeExp.mov.zip)

**Comment by bpasero** [comment]
Thanks for trying, I am out of ideas.

**Comment by Jvalal** [comment]
ugh! So strange.

**Comment by Jvalal** [comment]
more weirdness. Even when I browse to the correct folder and try and "open" it opens to some other directory, looks like my home directory.  Though I was able to do it once. Makes no sense. And I can do it on other folders. 

[VSCode.mov.zip](https://github.com/Microsoft/vscode/files/2949166/VSCode.mov.zip)
[VSCode.mov 11.05.07 PM.zip](https://github.com/Microsoft/vscode/files/2949167/VSCode.mov.11.05.07.PM.zip)
