### ISSUE TITLE
Node.js debugging does not work

### ISSUE THREAD

**Issue by akoufatzis** [Microsoft/vscode#69808]
Hello dear vscode team. Thank you for the fantastic IDE. Unfortunately I have an issue with the latest version when I am trying to debug node.js apps written in typescript.

My **launch.json**: 

```ts
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "attach",
			"name": "Attach by Process ID",
			"processId": "${command:PickProcess}"
		},
		{
			"name": "Launch TypeScript",
			"type": "node",
			"request": "launch",
			"runtimeArgs": [
				"-r",
				"ts-node/register"
			],
			"args": [
				"${workspaceFolder}/src/index.ts"
			],
			"cwd": "${workspaceRoot}",
			"sourceMaps": true,
			"internalConsoleOptions": "openOnSessionStart",
			"env": {
				"TS_NODE_FILES": "true"
			}
		}
	]
}
```
The issue I am experiencing is that most of the times breakpoints are not hit or it seems that the debugger stops at some breakpoint but it is inside an **async_hook.js** file at not at my code.

- VSCode Version: 1.31.1
- OS Version: macOS

**Comment by sogehige** [comment]
Have similar issue when using babel with inline sourcemaps, I cannot set correct breakpoints, seems like inline sourcemaps are being ignored

**Comment by roblourens** [comment]
Please try updating to 1.32, which fixed an issue with ts-node
