### ISSUE TITLE
Searching for Wave: Select Default Code Search Provider does not work

### ISSUE THREAD

**Issue by lavinders** [Microsoft/vscode#69804]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Steps to try out the feature (ETA of entire setup: <2 min)
1.	Install VSCode & WAVE VSCode extension from steps here.
2.	Set your flighting ring to SelfHost by:
a.	In VSCode, ‘ctrl-shift-p’
b.	Type "Preferences: Open User Settings". And set: "nmake.selfhost-ring": "SelfHost" (its towards the bottom)
3.	Set default search provider to Azure DevOps rather than local file system
a.	In VSCode, ‘ctrl-shift-p’
b.	Type “WAVE: Select Default Search Provider” and choose “Azure DevOps (reSearch)” << THIS DOES NOT WORK, I did not see this setting in VS Code search results.
4.	Start searching! 
a.	You can use both the full list of operators available for Azure DevOps search as well as the VSCode search syntax
b.	By default, the search provider uses the closest official branch for which your repo is currently checked out to.
c.	The search itself does not hydrate any files. The file will only hydrate once you click on the search result to open the file.

Extension version: 1.1.190220004
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18845

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
This needs to be investigated by the team working on the WAVE extension, I've told them to take a look at this issue.
