### ISSUE TITLE
[Loc] Request to add Mongolian (mn) language to Transifex VS Code project

### ISSUE THREAD

**Issue by ulziibay** [microsoft/vscode#69801]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by danyeh** [comment]
We don't have plan to enable additional language in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
