### ISSUE TITLE
Release notes link is redirecting to blank page.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6980]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows10
-Default browser : Edge

I observed this issue with latest alpha build, when I click on Release notes button from pop-up or try to get release notes from Help->Release Notes , then it is redirect me to below page. https://github.com/Microsoft/vscode/wiki/Alpha-Release-Notes

![image](https://cloud.githubusercontent.com/assets/17735796/15616427/881d9106-23f8-11e6-9e7c-d387239ae0ec.png)

Expected:
I checked with other team member and they are getting correct URL for the same build.
https://github.com/Microsoft/vscode/wiki

**Comment by Tyriar** [comment]
Alpha is being deprecated so issue here, I did however find this for the insiders build from this https://github.com/Microsoft/vscode-distro/issues/44
