### ISSUE TITLE
New icon like Visual Studio 2019

### ISSUE THREAD

**Issue by JakubSteplowski** [Microsoft/vscode#69803]
Visual Studio will change icon (once again) with v16 (2019):

<img width="880" alt="new-vs-icons" src="https://user-images.githubusercontent.com/4522930/53759539-d766eb00-3ec0-11e9-9393-8cca9bda3e75.png">

I think Visual Studio Code should update it as well, here's my suggestion:

<img width="880" alt="new-vs-code-icons" src="https://user-images.githubusercontent.com/4522930/53760147-527cd100-3ec2-11e9-969a-50366f286a7e.png">

**Comment by Sovgut** [comment]
Great, I would like to see this logo in all versions of Visual Studio Code on all platforms!

**Comment by JakubSteplowski** [comment]
Before:
![before](https://user-images.githubusercontent.com/4522930/53828460-0a22e900-3f7e-11e9-8f52-222e0437d4ba.png)

After:
![after](https://user-images.githubusercontent.com/4522930/53828463-0d1dd980-3f7e-11e9-9577-3851c556cc94.png)

**Comment by jonbp** [comment]
Throwing my two cents in...
![vscode-2019](https://user-images.githubusercontent.com/3267483/55437627-40608200-5597-11e9-8b78-0866eea8ea31.png)

**Comment by chrisdias** [comment]
this is being tracked in https://github.com/Microsoft/vscode/issues/71827

**Comment by PogromistDev** [comment]
Visual Studio icon should stay as 
![visualstudioicon](https://user-images.githubusercontent.com/12221569/57069689-638d6700-6ce6-11e9-8898-59186ef0513e.PNG)
and vs code icon should be just blue vs icon
![visualstudiocodeicon](https://user-images.githubusercontent.com/12221569/57069793-a9e2c600-6ce6-11e9-96f1-4927bd5d48a4.png)
(not this tone, more bluish)

**Comment by PogromistDev** [comment]
Oh, hi there.
