### ISSUE TITLE
bash Terminal

### ISSUE THREAD

**Issue by dharrison2010** [Microsoft/vscode#69818]
Issue Type: <b>Bug</b>

Using CTRL + l is not clearing the terminal consistently...old text still displayed and prompt moves as if it was cleared... Tried with all extensions disabled, still happens.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
markdown-preview-github-styles|bie|0.1.4
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.25.0
vscode-eslint|dba|1.8.0
python-preview|don|0.0.4
es7-react-js-snippets|dsz|2.0.1
prettier-vscode|esb|1.8.1
code-runner|for|0.9.7
sepaswitch|Fut|1.0.2
sass-lint|gle|1.0.4
gc-excelviewer|Gra|2.1.29
vscode-test-explorer|hbe|2.6.0
vscode-python-test-adapter|lit|0.3.1
MagicPython|mag|1.1.0
rainbow-csv|mec|1.0.0
prettify-json|moh|0.0.3
python|ms-|2019.2.5433
cpptools|ms-|0.21.0
material-icon-theme|PKi|3.6.3
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1

(5 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
