### ISSUE TITLE
Zoomed in Selection Bug

### ISSUE THREAD

**Issue by emirazazi** [Microsoft/vscode#69817]
Issue Type: <b>Bug</b>

When zoomed in with strg + you get the bug that it automatically selects an item from the dropdown menu when you right click. Hapenned on 1080p linux

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.15.0-45-generic

**Comment by joaomoreno** [comment]
#65787
