### ISSUE TITLE
Wrap single line problems

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69813]
Just hit this problem which was harder to read because of the recent unwrapping:

<img width="1099" alt="screen shot 2019-03-04 at 3 54 44 pm" src="https://user-images.githubusercontent.com/2193314/53771088-2cd9d280-3e96-11e9-9c53-128990d3f0a5.png">

> Argument of type ‘(value: IQuickPickItem) => Promise<string | undefined> | null’ is not assignable to parameter of type ‘(value: IQuickPickItem) => string | PromiseLike<string | undefined> | undefined’.ts(TS2345)

Maybe we should wrap when the problem does not contain a `\n` character?

Another idea is to only not wrap when a problem has indentation and/or contains single line breaks, for example:

```
This looks like paragraph formatting.

Let's wrap this.
```

```
This looks like a stack trace
Let's not wrap this
```

**Comment by sandy081** [comment]
At present it is simple that to show a problem in multiple lines break into multiple lines. Do not want to introduce new concept and make it mix of wrapping and multiple lines. This is how it is from beginning.

**Comment by Tyriar** [comment]
@sandy081 this problem was way more difficult to work with, I couldn't see the full problem in the panel and needed to scroll left and right multiple times to spot the issues. Also I think in order to view the full problem with just the keyboard I needed to enable tab focus mode

**Comment by sandy081** [comment]
I see your point. But just wrapping the first line is not a solution and wrapping all lines can break those diagnostics which expect the character alignment. May be you can have a command that can focus the panel instead of enabling tab.
