### ISSUE TITLE
Pasting a line copied with ctrl+c should ignore the linebreak

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#69812]
When copying a line through having the cursor in the line and doing ctrl+c copies the linebreak too. This produces a new line when pasted, which is pretty much always undesired in my case, and I have to remove them. 

I suggest not copying the linebreaks when lines are copied through this method.

Video: https://dl.dropboxusercontent.com/s/gsigo9c1bdyh9ql/2019-03-04_17-48-02.mp4

**Comment by alexandrudima** [comment]
This is intentional. Perhaps we can add a setting to control the behaviour.

**Comment by madprops** [comment]
> This is intentional. Perhaps we can add a setting to control the behaviour.

Yes please, I would use that setting.

**Comment by alexandrudima** [comment]
Let's track in #61840
