### ISSUE TITLE
[Bug] Adding Folder To Workspace Expands All Folders

### ISSUE THREAD

**Issue by angelhdz** [Microsoft/vscode#69811]
### Environment Details
- VSCode Version: 1.31.1
- OS Version: Windows 10 Pro 64bit

### Steps to Reproduce:

1. Adding Folder To Workspace Expands All Folders

### Expected Result
- Adding Folder To Workspace Only Expands That Folder

### Does this issue occur when all extensions are disabled?: 
Yes

**Comment by isidorn** [comment]
I can not reproduce.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, what are the exact steps you add folders, and what fodlers exactly get expanded

**Comment by angelhdz** [comment]
![2019-03-05_14-04-21](https://user-images.githubusercontent.com/10191085/53826857-037d7d00-3f50-11e9-90e0-45edfac9dcb1.gif)

### Update
It also happens when a folder is removed from the workspace. If looks like the workspace refresh/update event messes up.

**Comment by isidorn** [comment]
Fixed in latest insiders
