### ISSUE TITLE
Make breakpoints section height adjustable

### ISSUE THREAD

**Issue by vsccarl** [microsoft/vscode#6982]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Open debug viewlet
2. Add 7 or more breakpoints

When you have many breakpoints set you have to scroll through them, but all other sections of debugging allow adjustable height sections. The breakpoints section should either be height adjustable or expand to be able to view all set breakpoints at once.

**Comment by sean-mcmanus** [comment]
+1.
