### ISSUE TITLE
parameter highlight

### ISSUE THREAD

**Issue by bichikim** [Microsoft/vscode#69824]
The image below is highlighting codes in Vscode now
![image](https://user-images.githubusercontent.com/13829322/53788668-cae89e00-3f65-11e9-98a8-5474d5f5bdc6.png)

I hope the parameters in the function are highlighted as shown below.

![image](https://user-images.githubusercontent.com/13829322/53788673-cfad5200-3f65-11e9-9997-02d33d1a40d4.png)

**Comment by alexr00** [comment]
This looks like it's caused by an extension. I cannot reproduce this.

**Comment by bichikim** [comment]
Hi
 
The second image is function code in Webstorm.

Webstorm can find the parameter name in the function. It would be nice if Vscode supports a theme color scope such as "variable.parameter ..." for the parameter values.

**Comment by alexr00** [comment]
I'm looking at the first image, and I'm not seeing the same syntax highlighting that is in your example. My example in VS Code:
![image](https://user-images.githubusercontent.com/38270282/54025452-dec91580-419a-11e9-8109-c99f1402ff5a.png)

**Comment by bichikim** [comment]
@alexr00 thank you for your time 

your image is the same image as mine.


Vscode does not know whether "value" or "parameter" is "const" or "parameter" so Vscode highlights "values" and "parameters" of the same color.

But Webstorm does know that so parameter and value are not the same color at my second image.

Highlighting two variables in a different color helps to determine which is the parameter.

**Comment by alexr00** [comment]
This is a change request for the TypeScript TextMate grammar we use then. In [this](https://github.com/Microsoft/vscode/issues/69824#issuecomment-470892654) example on lines 2 and 4, `parameter` and `value` are both `variable.other.readwrite.ts`. The change would be to categorize these differently.

````javascript
function myTest(parameter: any) {
	console.log(parameter);
	const value: string = 'value';
	console.log(value);
}
````

**Comment by alexr00** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#729

**Comment by alexr00** [comment]
Actually, I don't think this is possible with TextMate. Duplicate of https://github.com/Microsoft/vscode/issues/50140.

**Comment by B2o5T** [comment]
> @alexr00 thank you for your time
> 
> your image is the same image as mine if you add code below to settings.json
> 
> ```json
>             {
>                 "scope": [
>                     "variable.parameter",
>                 ],
>                 "settings": {
>                     "foreground": "#9AD100",
>                     "fontStyle": "",
>                 }
>             },
> ```
> 
> Vscode does not know whether "value" or "parameter" is "const" or "parameter" so Vscode highlights "values" and "parameters" of the same color.
> 
> But Webstorm does know that so parameter and value are not the same color at my second image.
> 
> Highlighting two variables in a different color helps to determine which is the parameter.
> 
> I ask the Vscode team to add this feature

that's the only reason I can't go over from WebStorm to VSCode, this is overkill ☝️

**Comment by bichikim** [comment]
> > @alexr00 thank you for your time
> > your image is the same image as mine if you add code below to settings.json
> > ```json
> >             {
> >                 "scope": [
> >                     "variable.parameter",
> >                 ],
> >                 "settings": {
> >                     "foreground": "#9AD100",
> >                     "fontStyle": "",
> >                 }
> >             },
> > ```
> > 
> > 
> > Vscode does not know whether "value" or "parameter" is "const" or "parameter" so Vscode highlights "values" and "parameters" of the same color.
> > But Webstorm does know that so parameter and value are not the same color at my second image.
> > Highlighting two variables in a different color helps to determine which is the parameter.
> > I ask the Vscode team to add this feature
> 
> that's the only reason I can't go over from WebStorm to VSCode, this is overkill ☝️

I think so.
