### ISSUE TITLE
Cannot find definition that webstorm can...

### ISSUE THREAD

**Issue by MrNewWorld** [Microsoft/vscode#69821]
![vscode](https://user-images.githubusercontent.com/18390127/53784469-5e16d900-3f50-11e9-860e-cc3e65678d53.gif)
![webstorm](https://user-images.githubusercontent.com/18390127/53784493-6ec74f00-3f50-11e9-92b5-37c6ae41a6b5.gif)

Also it's much slower when switching between tabs than webstorm...

**Comment by mjbvz** [comment]
Please share some example code or small example project

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
