### ISSUE TITLE
Files in \\wsl$ are not saved properly by VSCode Windows

### ISSUE THREAD

**Issue by khuongduybui** [Microsoft/vscode#69820]
- VSCode Version:
Version: 1.32.0-insider (user setup)
Commit: c23e8995f6e31b3540e0a2c3d4fdc58e6d7cba53
Date: 2019-03-04T17:23:10.903Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18845

- OS Version:
18845.1001

Steps to Reproduce:

1. In WSL, create a text file /tmp/test.txt with 4 lines (e.g. "a - b - c - d -")
2. Open \\wsl$\WLinux\tmp\test.txt in VSCode, remove 2 lines in the middle (e.g. "a - d -") and save
3. Back in WSL, cat /tmp/test.txt, got "a - d - c - d -" instead of "a - d -"

Does this issue occur when all extensions are disabled?: Yes (I use a pristine VSCode Insider to check)

Note 1: This erroneous behavior is NOT observed when editing the same file with other text editors such as Notepad.

Note 2: When the file size after changes is equal to or greater than before, everything works as expected. When the expected file size after changes is smaller than before, actual file size stays the same.

**Comment by dbaeumer** [comment]
@bpasero assigning to you since this is a save issue. Please note that the feature @khuongduybui is using is a insider feature. See https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/

**Comment by bpasero** [comment]
Open for grab if someone wants to investigate. The code that saves a file is here: https://github.com/Microsoft/vscode/blob/10cd21c637ecbe267a2c5cfa53d1ea008790388a/src/vs/workbench/services/files/node/fileService.ts#L553

Marking as upstream as this is very likely an issue with node.js.

**Comment by khuongduybui** [comment]
Is it possible that pfs.truncate isn't doing what is expected to do?

**Comment by bpasero** [comment]
@khuongduybui yeah certainly, if you want you could try to just use node.js and see if it reproduces and then file a bug against them.

**Comment by khuongduybui** [comment]
Problem fixed in latest version of VS Code (stable) and Windows build (18865).
Not sure who fixed it but it's fixed :)
