### ISSUE TITLE
toggleFindInSelection can only be triggered by keyboard, but not mouse click

### ISSUE THREAD

**Issue by slumder** [microsoft/vscode#69838]
Issue Type: <b>Bug</b>

1.Using shortcut Ctrl+F to open search bar.
2.Enter the string to search for.
3.There are 17 results I find.
4.After click toggleFindInSelection on search bar with mouse, there is only 1 result left.
5.Then, I try to click toggleFindInSelection again on seach bar with mouse, but there is still 1 result left, it should be 17 results.
6.Finally, I try to use shortcut Alt+L to trigger it, and it give me 17 results

I can turn on toggleFindInSelection by both mouse click and shortcut Alt+L, but can turn off toggleFindInSelection only by shortcut Alt+L.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.82GB free)|
|Process Argv|C:\Users\KEN\AppData\Local\Temp\scp06517\pmst113.php|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.0.0
xml|Dot|2.4.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
vscode-mysql|for|0.3.0
vscode-language-pack-zh-hant|MS-|1.31.4
snippet-creator|nik|0.0.5

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@slumder I can't reproduce this issue in latest Insiders anymore, can you help confirm it ?

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
