### ISSUE TITLE
Custom menus steal focus when using Alt for column selection in the editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#69830]
Issue Type: <b>Bug</b>

On Windows,
* Configure `"editor.multiCursorModifier": "ctrlCmd"`
* Use a mouse to make a selection by mousedown + dragging
* Press <kbd>Alt</kbd> to switch to doing a column selection
* At the end, the menubar steals the focus

VS Code version: Code - Insiders 1.32.0-insider (c42088be3b557e5607f7cde6b3b10c0dba6763dc, 2019-03-04T05:18:19.410Z)
OS version: Darwin x64 18.2.0

![column-selection](https://user-images.githubusercontent.com/5047891/53796153-d0c58b80-3f33-11e9-8860-eb4ced343976.gif)

**Comment by alexandrudima** [comment]
@sbatten We should decide if we want to do anything for this release, otherwise we might want to pull the entry from the release notes, since this cripples the feature on Windows.

**Comment by dbaeumer** [comment]
Closing. @alexandrudima  merged the PR.
