### ISSUE TITLE
Setting breakpoints adds them to breakpoint list nonsensically 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6983]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Add breakpoints from different files.
2. Observe the order they are added to the breakpoints list

![image](https://cloud.githubusercontent.com/assets/12900364/15620016/9b945206-240c-11e6-91dc-98d84a4cc6ff.png)

Shouldn't they be sorted alphabetically? When adding them it put breakpoints from app.js inbetween module.js and www.

**Comment by isidorn** [comment]
Assigning back to @vsccarl to verify the fix - should be in tomorrow's alpha
