### ISSUE TITLE
Incorrect terminal input behaviour when using ALT GR with Azerty keyboard on Windows

### ISSUE THREAD

**Issue by loganmzz** [Microsoft/vscode#69834]
* "Standard"
> Version: 1.31.1 (user setup)
>  Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
>  Date: 2019-02-12T02:20:54.427Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17134

* Insider
> Version: 1.32.0-insider
> Commit: c23e8995f6e31b3540e0a2c3d4fdc58e6d7cba53
> Date: 2019-03-04T17:23:10.903Z
> Electron: 3.1.3
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17134

Tested on Linux and there's no problem.

Steps to Reproduce:

1. Open a terminal (PowerShell, Command or Mingw)
2. Press Alt Gr + `é` / `è` (modifiers: `~` / ````` )
> Actual:  associated "default" (with no key modifier) character is send (e.g. `é` / `è` )
> Expected: nothing
3. Press any key (e.g. `n` / `u` )
> Apply modifer (e.g. `~`/ ````` )
> Actual output: `éñ` / `èù`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/68262
