### ISSUE TITLE
When using registerTextDocumentContentProvider, the view blocks Copy command

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#6984]
- VSCode Version: 1.1.1
- OS Version: OSX

I'm the author of a plugin (https://github.com/cfjedimaster/htmlescape-vscode) that takes code in the editor (or a selection), and creates a view of an escaped version of it. (This is so the code could be used in an HTML blog post.) Recently I noticed that while my extension works, selecting text in the view and trying to copy it to the clipboard no longer works.
Steps to Reproduce:

1. Install the extension (it is available in the market place).
2. Open any file, and execute the command ("Show Escaped HTML").
3. In the new view that opens up, select some of the escaped HTML, do Command-C, then paste in some other editor. Nothing will show up.

**Comment by jrieken** [comment]
do you use `previewHtml`?

**Comment by cfjedimaster** [comment]
No. From https://github.com/cfjedimaster/htmlescape-vscode/blob/master/src/extension.ts - I've implemented vscode.TextDocumentContentProvider. I'm using provideTextDocumentContent to get the text from the editor and create a new HTML document from it.

**Comment by jrieken** [comment]
well, you do [this](https://github.com/cfjedimaster/htmlescape-vscode/blob/master/src/extension.ts#L87) which is previewing the document as _html_. I wonder, if in your case and as a workaround, you could just `openTextDocument` and `showTextDocument` - then the editor will be used to display the _virtual_ document.

**Comment by cfjedimaster** [comment]
Are you saying it would take over the default editor pane? If so, that's not what I want.

**Comment by jrieken** [comment]
>  default editor pane

Well, like `previewHtml` it open where editors open but you can define the column in which it shows and also if it should take focus or not: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3018

**Comment by jrieken** [comment]
despite alternative implementation/workarounds to the problem, I believe this is #6924
