### ISSUE TITLE
vscode.workspace.findFiles() no longer honors the exclude pattern 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#69840]
1) use yo code to create an extension

2) Replace the extension.ts with the code below

4) Press F5 to run the workspace

5) Open a project for a node module that has a node_modules folder with many modules.

6) Execute the ´Hello World' command

--> the call workspace.findFiles returns file matches from the `node_modules` folder, but the node_modules folder is excluded.

Running the same extension in stable properly excludes matches in the `node_modules` folder.

Tagging as a candiate for February since the change of behavour impacts NPM script running and now proposes scripts from the node_modules.

The code for extension.ts

```
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
        const workspace = vscode.workspace.workspaceFolders![0];
        if (workspace) {
            vscode.workspace.findFiles(new vscode.RelativePattern(workspace, "**/package.json"), "**/node_modules/**").then(results => {
                console.log('results: ', results);
            });
        }
    });

    context.subscriptions.push(disposable);
}
```

**Comment by octref** [comment]
Would be fixed by 69864.
