### ISSUE TITLE
Unable to open integrated terminal in new update - exit code 2

### ISSUE THREAD

**Issue by Geor23** [Microsoft/vscode#69841]
- VSCode Version: 1.31.1
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

It was working on Thursday, 28th of Febr.
1. Try to open terminal via Terminal > New Terminal 
2. An error pops up with the following message: "The terminal process command 'C:\Windows\system32\cmd.exe' failed to launch (exit code: 2)", 
"The terminal process command 'C:\Program Files\Git\bin\bash.exe' failed to launch (exit code: 2)".

The paths are correct and was able to open them from the given path from the file explorer. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/69564

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/69564
