### ISSUE TITLE
id_rsa password (askpass?)

### ISSUE THREAD

**Issue by marchage** [Microsoft/vscode#69846]
Issue Type: <b>Feature Request</b>

I would suggest a provision for id_rsa password (askpass?), or a notification that something goes wrong. Indefinite spinner = anxiety levels go up = bad vibe when using VSCode, in the end. Perhaps I just need to switch. I have seen many requests for this before. Its probably too difficult/asking for a lot.

Thanks anyway.

PS I see that this is just a form for a GitHub issue... well, sorry for others watching these but, here you go!

VS Code version: Code 1.* (yeah, right))
OS version: (yeah, right)

**Comment by joaomoreno** [comment]
Please provide more information:

1. Steps you take to hit the issue
2. VS Code version
3. OS version
