### ISSUE TITLE
Search: when ignoring casing, search for kabob and snake case too

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#69855]
With this feature, snake_case and kabab-case will also be included in search results. For instance when I search for `clientId` I want to get results for 

* clientid
* client_id
* client-id
* CLIENT_ID

**Comment by roblourens** [comment]
I don't think this is likely to happen, but this issue is open for fuzzy text search: https://github.com/Microsoft/vscode/issues/60264
