### ISSUE TITLE
3-pane Merge View

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#69857]
Per requests in #5770 - separately requesting a 3-way merge view that has multiple panes in order to better facilitate using VS Code as a merge tool.  It is already very good with diff support, and would be wonderful to see better merge supports.

Example UI below...

![](https://user-images.githubusercontent.com/1470309/32250860-c677e4ce-bec0-11e7-82b5-0196d981cc28.png)

**Comment by ucavalcante** [comment]
This is a good way to go in VSCode

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/5770

**Comment by tracker1** [comment]
@joaomoreno if you read that thread #5770, the 3-way merge [it was requested to have a separate issue](https://github.com/Microsoft/vscode/issues/5770#issuecomment-466457745) added... it looks like there was already a similar request #37350 ... The dupe you mention is not the correct one.

**Comment by mkay581** [comment]
Yeah the proper thread this duplicates is #37350.
