### ISSUE TITLE
SCM Providers list resizing

### ISSUE THREAD

**Issue by smeesseman** [Microsoft/vscode#69850]
VSCode 1.31.1
WIndows 10

I am not sure if this happens in Git, but it does when using the SVN extension.  I am assuming the SCM API exposes an interface to the extension to add providers, from that assumption I am assuming the bug is in VSCode.

Reproduce:

1.  Add 6 or 7 or more separate projects which would register a new "source control provider" in SCM view.
2.  Switch from File Explorer view to SCM, to File Explorer, back to SCM.
3.  The "Source Control Providers" list box is resized to take up almost the entire height, and the list box below it (showing changes of selected provider) is resized to almost 0 height.  I have to click and drag it up to resize it every single time to show the content.
4.  Switch back to File Explorer view, and back to SCM, the bottom list box is once again almost 0 height.  Happens each time I leave the SCM view.

Note that less than 5 projects, the SCM view resizes perfectly and the height of the top list box is perfectly set to the accumulative height of the list items.

**Comment by joaomoreno** [comment]
Fixed by #49054
