### ISSUE TITLE
Breadcrumbs should not move the `tabsBorder`

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#69854]
- VSCode Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:

1. `View › Toggle Breadcrumbs`

![record_190305_182301](https://user-images.githubusercontent.com/9801624/53820184-eeb2e080-3f73-11e9-9cc5-8ede20f1aa17.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Hm, breadcrumbs are part of the tab control so it does make sense to me. Maybe it needs a breadcrumbs border style?

**Comment by bpasero** [comment]
@ihodev what would you expect, tabs, border and then breadcrumbs? And maybe an additional border for breadcrumbs?

**Comment by ihodev** [comment]
@bpasero Yes, that will be perfect

**Comment by ghosej** [comment]
Hi,
I am working on a class project where I need to make contributions to an open source project. I would like to work on this if that's fine.

**Comment by bpasero** [comment]
Tackled this as follows:
* `editorGroupHeader.border`: is a new color to show a border below breadcrumbs (this will also appear when tabs are disabled)
*  `editorGroupHeader.tabsBorder`: changed to only show below tabs but not breadcrumbs

Visually I feel like breadcrumbs belong to the editor and not tabs, so I like how this looks now:

![image](https://user-images.githubusercontent.com/900690/79107027-ee3e6900-7d73-11ea-80fd-02df87b8f76c.png)
