### ISSUE TITLE
copy shortcut doesn't work when browsing extensions

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#69869]
1. click on extensions
2. pick any extension
3. select some text in the "Details" section.
4. press CMD+C to copy
5. Paste somewhere.

Expected results:
Paste what is selected

Actual Results:
no copy has occurred.

If I go to edit->Copy in the menu it works properly. Many extensions have example code/settings for quick setup and copy will be helpful.

vscode version: Version 1.31.1 (1.31.1) on Mac

**Comment by mjbvz** [comment]
Duplicate of #69315
