### ISSUE TITLE
Preferences catagory listed twice for Open Workspace Settings

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#69867]
- VSCode Version: 1.32 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Bring up the Command Palette and filter on 'settings'

You'll see "Prefernces: Preferences: Open Workspace Settings". 

![image](https://user-images.githubusercontent.com/12818376/53832207-189be100-3f3b-11e9-855c-6ca7ec247a02.png)

The typo "Prefernces" has been fixed in src\vs\workbench\contrib\preferences\electron-browser\preferences.contribution.ts but the double category will still display as the category is also listed in the command name for Open Folder Settings and Open Workspace Settings.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/pull/69807

**Comment by gregvanl** [comment]
The typo was fixed by the other commit but the prefix "Preferences:" will still show up twice.

```typescript
MenuRegistry.appendMenuItem(MenuId.CommandPalette, {
	command: {
		id: OpenWorkspaceSettingsAction.ID,
		title: { value: `${category}: ${OpenWorkspaceSettingsAction.LABEL}`, original: 'Preferences: Open Workspace Settings' },
		category: nls.localize('preferencesCategory', "Preferences")
	},
	when: WorkbenchStateContext.notEqualsTo('empty')
});
```
