### ISSUE TITLE
Select is erratic in integrated terminal

### ISSUE THREAD

**Issue by trampster** [microsoft/vscode#69871]
Issue Type: <b>Bug</b>

1. Open integrated terminal.
2. Perform some commands
3. Try and select some text, so you can copy paste

The selection is erratic, it jumps around and it is sometime impossible to get it to select what you want.

In the follow example I have created a git branch and attempted to push and it tells me the command I need to use to set the upstream branch. However it's impossible to select it.

If I start from the left and drag to the right then the entire terminal to the bottom of the screen gets selected:

![vscodeselectbroken1](https://user-images.githubusercontent.com/2063633/53839996-cc65a500-3ffd-11e9-8ec5-b26ab3841a61.png)

If I start from the right then he entire terminal to the bottom of the screen gets selected excluding the bit of text I'm trying to select:

![vscodeselectbroken2](https://user-images.githubusercontent.com/2063633/53840076-0767d880-3ffe-11e9-9d23-8b265914f1a1.png)

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3447)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.58GB (3.69GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.4.1
EditorConfig|Edi|0.12.8
cpptools|ms-|0.21.0
csharp|ms-|1.17.1

</details>

**Comment by trampster** [comment]
Still happens on Version: 1.33.1

I have have created a new branch in git and comitted to it, I then try to push, and it tells me the command I should use, however I can't select it. I have screenshots below, which show this, it's s real issue.

![selectIssueFromLeft](https://user-images.githubusercontent.com/2063633/56780853-005a8b00-6835-11e9-9435-dd099af397a2.png)

![selectIssueFromRight](https://user-images.githubusercontent.com/2063633/56780861-08b2c600-6835-11e9-9103-4dfcc2f888dc.png)

**Comment by Tyriar** [comment]
Hmm I still can't repro and it's a little hard to understand the problem exactly. Are you sure you're not double clicking which enter "word select" mode. Could you do a screen recording to illustrate the problem? https://getkap.co/ works well for me.
