### ISSUE TITLE
Click on settings icon shows collapsed menu

### ISSUE THREAD

**Issue by drivinward** [Microsoft/vscode#69870]
Issue Type: <b>Bug</b>

- Open New Visual Studio Code - Insiders window
- Click on lower left gear icon

A collapsed menu list is shown.
This does not happen with normal version of Visual Studio Code.

VS Code version: Code - Insiders 1.32.0-insider (2380981c97a07816a3d1c10edf1fb678463dc215, 2019-03-05T10:33:47.691Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.41GB free)|
|Process Argv|-psn_0_9857382|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.4.9
python|ms-|2019.2.5433
LiveServer|rit|5.5.1

</details>

**Comment by joaomoreno** [comment]
What does that mean? Can you show us a screenshot?

**Comment by drivinward** [comment]
Here you go:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22613065/54526641-a7671f80-4977-11e9-8a22-8121dea155e8.png">

Sorry for not replying in time.
