### ISSUE TITLE
Intellisense has been really bad

### ISSUE THREAD

**Issue by aboktor** [Microsoft/vscode#69872]
Issue Type: <b>Bug</b>

Intellisense would just hang and I'd get the spinner at the top of the page forever. It never recorvers after that.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.90GB (33.48GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
code-spell-checker|str|1.6.10
gitblame|wad|2.6.3

</details>

**Comment by mjbvz** [comment]
Which language is this for?

**Comment by aboktor** [comment]
Typescript. Everyone around me is suffering from the same issue.

**Comment by mjbvz** [comment]
Please provide information about your project and what seems to trigger the problem

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
