### ISSUE TITLE
Unable to re-install powershell extension when working with multiple instance of  VSCode.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6987]
- VSCode Version: 1.2.0-alpha
- OS Version: Windows10

Steps to Reproduce:
Setup: I have powershell extension already installed with VSCode.

1. Launch two instances of VSCode and open different project folders with each instance.
2. Remove Powershell extension from one of the instance and wait for the restart popup.
3. If restart window didn't appear then execute reload window command from command palette.
4. Add new PS file in the project and go to extension recommendation from command palette.
5. Now try to install PS extension and verify app behavior.

Actual:
1. I didn't get reload option after uninstalling PS extension and when try to reinstall extension getting error message.
Getting error message from active VSCode instance "Please restart code before reinstalling PS". when try to install PS extension.
![image](https://cloud.githubusercontent.com/assets/17735796/15624681/9a03aec8-2443-11e6-8757-26a7d30889bf.png)

2. At the same time I am getting a pop-up to install extension on other VSCOde instance (where I opened TS proj). so one instance (my active instance) is showing up error message and other (where I opened TypeScript proj)  is showing proper message. 

![image](https://cloud.githubusercontent.com/assets/17735796/15624694/df2758f6-2443-11e6-96c5-76a5b5d5b64d.png)

Full Repro steps:
![psextissue](https://cloud.githubusercontent.com/assets/17735796/15624893/327b08da-244a-11e6-9005-4dca1b6713eb.gif)

**Comment by joaomoreno** [comment]
As designed.
