### ISSUE TITLE
Bugged folder rename

### ISSUE THREAD

**Issue by cloudrex** [Microsoft/vscode#69886]
Folder rename bugs when trying to rename a folder while another folder with the same name, but different casing exists in the same directory.

The editor always ends up bugged when I perform mass renaming on folders, but just change their casing (not the actual names).

- VSCode Version: 1.31.1
- OS Version: Linux (Ubuntu 18.04)

Steps to Reproduce:

1. Create 2 folders with the same name (different casings).
2. Attempt to rename any of the created folders.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders?
https://code.visualstudio.com/insiders/
