### ISSUE TITLE
Strange case on command usage when argument starts with 0

### ISSUE THREAD

**Issue by RGSS3** [Microsoft/vscode#69887]
Issue Type: <b>Bug</b>

When I tried this in cmd.exe to create a new folder, and open it.
```
F:\Work>md 0301
F:\Work>code 0301
```
Visual Code opens a newly created (unsaved) file named 301, what I expected to be is open the newly created folder as current workspace
![image](https://user-images.githubusercontent.com/4011940/53860608-85d37300-401c-11e9-9c96-27c7e3692761.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:21:36.727Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (0.87GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
semantic-ui-snippets|4tr|0.0.7
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
vsc-prolog|art|0.8.23
code-gnu-global|aus|0.2.2
vscode-django|bat|0.19.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
solargraph|cas|0.19.3
vscode-astyle|chi|0.9.0
scala|dal|0.0.5
jupyter|don|1.1.5
scala-lsp|dra|0.2.3
vscode-ghc-simple|dra|0.0.10
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.7.0
lex-flex-yacc-bison|fau|0.0.3
vscode-npm|fkn|3.3.0
reasonml|fre|1.0.38
vscode-atom-javascript-snippet|glu|0.2.1
ruby|gro|0.1.0
vue-snippets|hol|0.1.11
haskell-linter|hoo|0.0.6
vscode-ghc-mod|hoo|1.2.0
Ionide-fsharp|Ion|3.34.0
Scala|itr|0.1.7
mysql-syntax|jak|1.3.1
language-haskell|jus|2.5.0
wordcounter|kir|1.4.0
vscode-sbt-scala|lig|0.2.4
MagicPython|mag|1.1.0
rainbow-csv|mec|1.0.0
cpplint|min|0.1.3
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.1
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.1284
scala|nic|0.1.4
vetur|oct|0.16.2
vscode-code-outline|pat|0.1.1
open-html-in-browser|pea|1.0.4
word-counter|plu|0.0.1
tcl|ras|0.1.0
prolog|reb|0.0.4
ruby|reb|0.22.2
scheme|reb|0.0.2
java|red|0.40.0
vscode-yaml|red|0.3.0
tcl-outline|she|0.2.1
tcl|sle|0.2.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.15.0
vsopen1|vso|0.0.1
jinja|who|0.0.8
plsql-language|xyz|1.7.0

(5 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Looks like it only behaves like this when a folder has a leading 0. If someone wants to look into it, feel free.

**Comment by jmbockhorst** [comment]
This has to do with the minimist argument parser detecting the unknown path argument as a number, and thus returning a number. As you noted, this case only really happens if the argument has a leading 0. 

The only solution I could think of to avoid this behavior would be to check if any input arguments start with a 0, and then append a character to the end so that it isn't detected as a number, and then remove the character after it has been parsed. I feel like this could work since I think the only arguments that could start with zero would be folder and file names, so it wouldn't be breaking anything else. I may be missing something though, and I understand if this isn't the way you want to fix this. I'll open the pull request with my fix for you to look at.

**Comment by joaomoreno** [comment]
[This minimist line](https://github.com/substack/minimist/blob/master/index.js#L186) tells me we should define that `_` should be a string. Something like the following, over [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts#L33):

```
{ id: '_', type: 'string' }
```

@jmbockhorst Wanna try that?

**Comment by jmbockhorst** [comment]
@joaomoreno Yep, that worked. Thank you. I committed the new fix.
