### ISSUE TITLE
[themes] [syntax highlighting] allow theme to change font size, line height, negative indent

### ISSUE THREAD

**Issue by buckle2000** [microsoft/vscode#69884]
## What

Code should allow custom themes to
- specify `font-size`, `line-height`, `text-variant` and etc. for every line
- specify `font-size`, `font-stretch` and etc. for inline elements

## Why

When you write markdown in current's VS code, the h1-h6 lines are the same size as the body text. This is not very helpful in terms of writing.

This is editing Markdown in Code (for now):

![image](https://user-images.githubusercontent.com/10850402/53856207-a0630900-3f96-11e9-831f-c9cbcf688ce8.png)

note that the title is less prominent than the bold text.

In contrast, this is editing Markdown in Bear:

[![image](https://user-images.githubusercontent.com/10850402/53855544-b3c0a500-3f93-11e9-9457-6aaa094c026e.png)](https://bear.app/#features)

We also need to resolve #20652 for this to work.

**Comment by buckle2000** [comment]
No, @vscodebot, this is not about auto-indent.

**Comment by faldor20** [comment]
This may be closed but it would be very useful and not particularly hard to implement considering it's all just html and CSS rendering. 
The justification that it is out of vscode design spec is silly. Vscode is steadily evolving into a platform for many different extensions much like Emacs. It is already far beyond a text editor and arbitrarily saying some things are and are not within its scope is silly.

**Comment by faldor20** [comment]
So @alexdima considering my comment this random closed issue has managed to get 8 thumbs up, and i feel a reasonable argument has been made. 
Would you reconsider your decision about this being out out of scope?  
Additionally:
I attempted to implement this myself but hit a wall once i realised i would have to change the bit structure of the token metadata...  it would seem to require adding more bits to support size information.
Also #47113 asks for the same thing.

**Comment by lopugit** [comment]
It would be great to be able to make syntax such as `const, let, var` very small font, but have variable assignments a bit larger, doesn't really make sense for everything to be the same font size..
