### ISSUE TITLE
Ending in a curly brace in a CSS/Sass will indent as if it were code

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6988]
CSS (cursor on character 4)

![image](https://cloud.githubusercontent.com/assets/2193314/15625235/0fcabee8-2454-11e6-8d92-50fc85a07206.png)

Sass (cursor on character 4)

![image](https://cloud.githubusercontent.com/assets/2193314/15625244/299ccaaa-2454-11e6-8059-008540e9e255.png)

**Comment by aeschli** [comment]
@alexandrudima I assume our indent on enter is not comment aware?

**Comment by alexandrudima** [comment]
Yes, in all languages pressing Enter after the configured brackets will indent -- regardless of context.

**Comment by Tyriar** [comment]
@alexandrudima Sass supports brackets in the same way as CSS yet does not auto-insert brackets or auto-indent when inside a comment? The Sass experience is much better imo.

**Comment by alexandrudima** [comment]
@Tyriar CSS and SASS behave in the same way -- handling Enter does not use scopes/tokens in deciding what to do, it simply uses regular expressions around the text to figure out what to do. That was a conscious decision after analyzing the trade-offs.

![brackets](https://cloud.githubusercontent.com/assets/5047891/17616315/35afb102-6074-11e6-81fa-4525042c6151.gif)
