### ISSUE TITLE
JS auto imports display `import A = require(“moduleName”)` rather than `import A from "moduleName"`

### ISSUE THREAD

**Issue by Terry-Su** [Microsoft/vscode#69888]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. ![](https://i.stack.imgur.com/DebVC.png)
2. ![](https://i.stack.imgur.com/VjLVW.png)
3. jsconfig:
```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
    },
    "allowSyntheticDefaultImports": true,
    "checkJs": true,
  },
  "include": [
    "./src/**/*",
    "node_modules/lodash/**/*"
  ]
}
```

Does this issue occur when all extensions are disabled?
Yes

**Comment by mjbvz** [comment]
Thanks. This is already tracked upstream by https://github.com/Microsoft/TypeScript/issues/29038
