### ISSUE TITLE
Report tsconfig/jsconfig errors from TypeScript Server at correct location in file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#69880]
From https://github.com/Microsoft/TypeScript/issues/10384

**repo**
1. In a new project with a single ts file, create a `tsconfig.json`:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
    ],
    "files": []
}
```

2. Make sure the js/ts extension is active by opening the TS file.
3. Open the tsconfig.

**Bug**
There should be an error reported in the tsconfig about there being no input files. However this error is currently reported on the first line of the `tsconfig` instead of on the `files` entry

**Comment by alexr00** [comment]
I was able to reproduce in  stable, but in insiders I don't see the error reported anywhere. It is not in the problems panel and nothing is red-squiggled in the tsconfig.json. I made sure to open the .ts file, and I could see the status bar info about the typescript language features initializing.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/30623 for root cause of these not showing up in the first place. To test diagnostic location, please try making an edit to the config file and saving it
