### ISSUE TITLE
feature isssue

### ISSUE THREAD

**Issue by abhimlk7** [Microsoft/vscode#69883]
Issue Type: <b>Feature Request</b>

when I save the file , things get shadded up in my program . I dont need such feature how can i disable it

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.15.0-45-generic

**Comment by abhimlk7** [comment]
Its not working

**Comment by joaomoreno** [comment]
What does that mean? Can you elaborate? Can you show us a screenshot of what the problem is?
