### ISSUE TITLE
Opened files not restored after update

### ISSUE THREAD

**Issue by Hsn723** [microsoft/vscode#69889]
- VSCode Version: 1.31.1
- OS Version: Windows 10 1803 17134,590

Steps to Reproduce:

1. VSCode displays a toast prompting for update
2. Click on install update button
3. Update completes and VSCode restarts

Expected behavior:
All opened files are restored

Actual behavior:
None of the opened files are restored. Only the Welcome tab and the Release Notes tab are opened

This behavior is problematic as it adds a barrier to frequent updates. As a user, I am more reluctant to accept updates knowing that doing so might close all the files I'm currently working on or am keeping open for reasons. For instance, on a large projects with a complex directory structure, I keep files open to have them handy for an upcoming task.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Are you using the user setup?

Does this happen on every update?

Can you reproduce with our Insiders release?

**Comment by Hsn723** [comment]
Hi,
Yes, I am using the new user setup. This does seem to happen every update. As for the Insiders release, I'm not being reluctant to accept the next update since I also have a bunch of files that must remain open.

I usually juggle several tasks at once, so it keeps a burden off my mind to keep the files I need or will need open.

**Comment by joaomoreno** [comment]
If you shutdown Code and reopen it, do files get restored?

**Comment by Hsn723** [comment]
Yes, if I shutdown and close Code files get restored normally, both on regular and Insider versions.

**Comment by joaomoreno** [comment]
And this happens to you every time you got an update? How many times was that?

**Comment by Hsn723** [comment]
From memory, this seems to have been happening since the last 2-3 or so updates, though I cannot recall exactly which version numbers these may be.

**Comment by joaomoreno** [comment]
@bpasero Any clues why this happens? Remember that the win32 update service uses `lifecycleService.quit` to shut down.

**Comment by bpasero** [comment]
@joaomoreno no this should work properly. I remember we used to have issues with the old localStorage implementation where we had to tell Chrome explicitly to flush the contents to disk because they were lost otherwise. But with the new implementation this was not needed anymore, so I removed that code. As long as you go through the lifecycle service (which is long running to give services a chance to persist) it should be fine.

@Hsn723 can you see if you find something in the logs maybe?

**Comment by Hsn723** [comment]
Where can I find those logs? Do they persist long enough after an update?

**Comment by bpasero** [comment]
@Hsn723 they are accssible from the "Output" panel in VSCode from the dropdown. I am not sure we keep them long enough though...

**Comment by Hsn723** [comment]
Yeah...I only see output logs from VSCode launched, both in Log (Main) and Log (Shared).

**Comment by Hsn723** [comment]
Ah, I just remembered a perhaps important detail: I am using VSCode in Windows, but my source code is on a Linux VM (Hyper-V on the same machine) and mounted via SMB. When shutting down and reopening VSCode there are no issues however... Opened files are only not restored after a VSCode update.

**Comment by joaomoreno** [comment]
@Hsn723 Is this still an issue?

**Comment by Hsn723** [comment]
@joaomoreno Hi, I'm still having this issue. Since then I've been much more reluctant to close or update VSCode except when forced to (for instance to install Windows Updates). However, I've noticed that this seems to only happen when opening a SMB-mounted project directory in VSCode on Windows. Also, contrary to my previous observation in https://github.com/Microsoft/vscode/issues/69889#issuecomment-471162086, the issue sometimes happens when closing/reopening VSCode (for instance before/after Windows Update). Perhaps VSCode is not always cleanly shutting down?

In the time that passed since I opened the issue VSCode Remote was made available and any projects opened via an SSH session has all of its open files correctly restored when reconnecting so I've been slowly transitioning to using VSCode Remote though it would still be a concern if it happens with local files...

**Comment by joaomoreno** [comment]
This seems unrelated to VS Code update at all, and maybe more with Code not shutting down properly.

**Comment by bpasero** [comment]
@Hsn723 I wonder if this is just the editors not restoring but other view state remains, e.g. the size of the sidebar?

Could be that on startup we want to open all editors but then fail because of network issues and then start to close them all? That would explain why it only happens for SMB share, though it would not explain why you cannot reproduce with a normal restart...
