### ISSUE TITLE
Indent Using spaces

### ISSUE THREAD

**Issue by shubhwebkul** [Microsoft/vscode#69885]
When I select indent using spaces option to 4 it successfully updates the visuals but switching to another file and come back to the same file do not show the correct spaces which I have selected. It automatically converts the spaces to 2

**Comment by alexandrudima** [comment]
@shubhwebkul Please use the settings:

```
"editor.tabSize": 4,
"editor.insertSpaces": true,
"editor.detectIndentation": false
```
