### ISSUE TITLE
Add "discard" and "unstage" equivalents to git.stageChange

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Microsoft/vscode#69892]
Issue Type: <b>Feature Request</b>

At the moment, most of the git-index commands that can be bound have to do with entire files, or specific, selected ranges — for instance, `git.clean`, `git.stage` and `git.unstage`; or `git.stageSelectedRanges` and `git.unstageSelectedRanges`.

There's one useful exception, `git.stageChange`, which presumably is supposed to preform the behaviour I'm used to from Vim w/ GitGutter — staging the change *that my cursor is currently inside* (which is especially useful in a workflow that's heavy on mappings involving the `workbench.action.editor.nextChange` and `workbench.action.editor.previousChange` commands). I can't actually get this to work at the moment, but I think that's an unrelated issue on my end.

Unfortunately, `git.stageChange` seems to stand alone — there's no corresponding singular `git.cleanChange` or `git.unstageChange` for discarding or unstaging the change containing the current cursor. I'd love to see these added!

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/53866617-3f691e80-3ff2-11e9-820b-228486615b0a.png)

**Comment by ELLIOTTCABLE** [comment]
@joaomoreno no problem, because I totally understand what it's like to maintain a large repo — but I actually *specifically addressed* the `git.*SelectedRanges` commands in my OP! I'm talking — very specifically, and separately — about the `git.stageChange` command (notice the lack of `...SelectedRange` at the end of it), that operates without making a prior selection.

If it's helpful to understand my use-case, I'm a Vim user, and do most of my navigation from the keyboard: navigating to one of my changes, and then having to *select* a range that covers that change before I can operate on it, is just one extra step. `(=`

Please re-open!

**Comment by joaomoreno** [comment]
I see. Apart from `git.stageChange`, you also have its counterpart `git.revertChange`.  `git.unstageChange` can't really be implemented unless you open the indexed file and run it from there...
