### ISSUE TITLE
lose intellisense from parent class in typescript class without semicolon after property

### ISSUE THREAD

**Issue by coppyC** [Microsoft/vscode#69897]
when with a semicolon after property
![image](https://user-images.githubusercontent.com/25004510/53872024-49157500-4038-11e9-93db-c6541e400448.png)

when without a semicolon after property
![image](https://user-images.githubusercontent.com/25004510/53871982-3307b480-4038-11e9-9ed2-261b0e4bc557.png)

Component is React.Component

- VSCode Version: 1.31.1
- OS Version:  64bit Mac OS X 10.14.1 18B75

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by coppyC** [comment]
Component is React.Component

**Comment by mjbvz** [comment]
Thanks. Confirmed and opened https://github.com/Microsoft/TypeScript/issues/30536 to track this upstream
