### ISSUE TITLE
Command palette shouldn't auto close when switching window/focus

### ISSUE THREAD

**Issue by DeXtmL** [Microsoft/vscode#6989]
- VSCode Version:1.1.1
- OS Version:Win10 x64

everytime I search for extensions, it takes minutes to complete(slow network for oversea connection). VSCode doesn't allow me to switch to other apps while waiting, very frustrating.

Steps to Reproduce: You have to use VSCode with a slow network/4G network.

1. press Ctrl+P
2. type ext install xxx
3. observe the search results won't appear (until several minutes)
4. While waiting, switch to another window (use Alt+Tab or just press Start menu)
5. the command palette window automatically closes. You have to search again.

**Comment by bpasero** [comment]
I am closing this because in June we plan to move the extensions management UI out of quick open into a more stable experience. 

There are other feature requests filed to generally keep quick open open even on focus lost.
