### ISSUE TITLE
Network drive Unavailable Windows

### ISSUE THREAD

**Issue by Chris591** [Microsoft/vscode#69894]
Issue Type: <b>Bug</b>

I'm using a Windows 10 PC and opening files from Networkshares.
If I'm working from home via VPN the drives are marked in the explorer with a red x as they are not available after the login. But they are after the VPN connection is running.
if you now try to click on an open file it will show the error "Unable to open '<file>': File not found (file:///<drive>:/.../<file>) and close the file.
I need to click on the drive in the Explorer first so it will mark the drive as available first than I can click on the open file. 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (25.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
perl-toolbox|d97|1.3.0
gitlens|eam|9.5.1
gc-excelviewer|Gra|2.1.29
todo-tree|Gru|0.0.121
compareit|in4|0.0.2
cisco|jam|1.3.0
PowerShell|ms-|1.11.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by joaomoreno** [comment]
This seems to be a Windows issue, not a VS Code one.

**Comment by Chris591** [comment]
with any other app I can access the files without the need to use the explorer first.
I can't even reopen the file from recent files. If I do this it will be removed from the recent files.
So I think it's an issue with checking if the file/drive is available.
