### ISSUE TITLE
ES6 template strings issue with comments

### ISSUE THREAD

**Issue by elgervb** [Microsoft/vscode#699]
When using globs in ES6 template strings, VSCode's syntax highlighting thinks there is a unclosed comment. Example: `${settings.tests}**/*.js`

![capture](https://cloud.githubusercontent.com/assets/356204/11419620/f0e23332-9428-11e5-8f69-7c5d1bd67c1d.PNG)

Notice that after the /* all coloring is green, until the next start / end of a comment.

Issue found on https://github.com/elgervb/skeletonSPA
gulpfile.babel.js line 297, task scripts-tests

**Comment by aeschli** [comment]
duplicate of #133
