### ISSUE TITLE
Menu bar UI no longer matches theme

### ISSUE THREAD

**Issue by DarthSpock** [Microsoft/vscode#69908]
- VSCode Version: 1.32.0
- OS Version: Win 7 SP1

Steps to Reproduce:

1. Open and update Insiders
2. See immediately that the Menu bar UI no longer matches theme (or length).

![image](https://user-images.githubusercontent.com/33032910/53894328-d13f4e80-4027-11e9-82b8-52a874bd09b5.png)

Does this issue occur when all extensions are disabled?: Yes

I expect the UI to appear the same as it did before with the larger font and matching my dark theme.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_32.md#default-title-bar-style-on-linux

**Comment by DarthSpock** [comment]
Thanks. Must of missed that. Fixed by setting it back to custom. I think it should of kept the setting and let users choose to change to native though.
