### ISSUE TITLE
Ctrl +C No Longer Copies Blank Lines

### ISSUE THREAD

**Issue by dkelosky** [microsoft/vscode#69903]
- VSCode Version: 1.31.1
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1.  Ctrl + C with cursor on a non-blank line
2.  Ctrl + C on a blank line
3. Ctrl + V and the blank line is no longer pasted.

This is a break in previous behavior and dissimilar to Ctrl + X operation.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by dkelosky** [comment]
It is a similar issue, but the symptoms are a bit different.  Ctrl + X **does** work on a blank line.  Ctrl + C is the exception.

**Comment by alexandrudima** [comment]
@dkelosky Can you please check your settings around `"editor.emptySelectionClipboard"` and the keybindings around `"ctrl+c"`?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by dkelosky** [comment]
Here's an example of the problem.  Ctrl + C on a non blank line, then a Ctrl + V, paste the content.  On a black line, Ctrl + C used to copy the blank line, and then Ctrl + V insert blank lines.  It was a convenient behavior: 

![copy_paste_blank](https://user-images.githubusercontent.com/14940561/55283048-d7270780-5327-11e9-8c2f-28944935525d.gif)

**Comment by dkelosky** [comment]
I previously had `editor.emptySelectionClipboard` unset.  I tried setting to `true` and `false` which made no impact.  Here are settings around `ctrl + c`:
![image](https://user-images.githubusercontent.com/14940561/55283073-4997e780-5328-11e9-9823-6c9e4b454da1.png)

**Comment by dkelosky** [comment]
Thanks!

**Comment by alexandrudima** [comment]
The last version that I could find which copies blank linkes to the clipboard was 1.29.1

**Comment by irrationalRock** [comment]
I think this [PR](https://github.com/Microsoft/vscode/pull/59193) caused blank lines to be ignored. I don't think it takes in consideration the `editor.emptySelectionClipboard` setting.

**Comment by dkelosky** [comment]
Hi @irrationalRock and @alexandrudima - thank you both.   It looks like that is why I'm running into the issue.  I made some notes on the closed PR (I'm not sure if that's helpful).  My main objection with the PR is it has an inherent assumption that the copy of a blank line was unintentional, but I do it all the time (which is why I'm whining so much now that it has changed).

**Comment by dkelosky** [comment]
If I could help with a fix too - please let me know.  Perhaps making this configurable would help both camps :smile:

**Comment by alexandrudima** [comment]
@rebornix Giving to you, I was unaware of the PR and the intentional change in this area.

**Comment by dkelosky** [comment]
Some notes about the [PR](https://github.com/Microsoft/vscode/pull/59193):
* VS Code `Ctrl + C` on a blank line now differs in behavior from other editors ([Gitpod](https://www.gitpod.io/), firebase rules, [Atom](https://atom.io/), [Notepad++](https://notepad-plus-plus.org/) (using `Ctrl +Shift + X`), 
* `Ctrl + C` unlike other key shortcuts: `Ctrl + X`, `Ctrl + arrow`, etc... behaves differently based on the content of the line
* VS Code assumes `Ctrl + C` on a blank line was an error but could be perfectly valid

The PR author mentioned accidentally using `Ctrl + C` on a blank line as the reason for the PR.  Presumably the author wanted to avoid overlaying their clipboard, but a tool like [Ditto](https://sourceforge.net/projects/ditto-cp/) may be a better solution to protect clipboard.

Thanks again for the help

**Comment by dkelosky** [comment]
#65328 - fyi @clayms

**Comment by rebornix** [comment]
I think the real problem here is when `editor.emptySelectionClipboard` is set to `true`, should we allow copy empty line (no leading whitespace) or not. https://github.com/Microsoft/vscode/pull/59193 disallows it, while https://github.com/microsoft/vscode/pull/71750 attempts to roll it back.

**Comment by dkelosky** [comment]
I think after #59193 it's not possible to copy blank lines regardless of the value of
editor.emptySelectionClipboard.  Before #59193 you could copy blank lines.

The author of #59193 indicated copying a blank lines by Ctrl + c is a mistake (but not for all devs :smile:)

Current behavior with #59193 differs in behavior from other editors.

Do you agree?

**Comment by dkelosky** [comment]
@rebornix I misread before.  #71750 does not undo #59193.  I think it makes #59193 apply only when emptySelectionClipboard is set.

Sorry to complain so much;  I love VS Code.  I don't like the new behavior which assumes copying a blank line is a mistake.

**Comment by dkelosky** [comment]
Sorry to pester on a minor detail - is this but I hope to keep this alive.  Can the #71750 be merged?

**Comment by rebornix** [comment]
> #71750 does not undo #59193. I think it makes #59193 apply only when emptySelectionClipboard is set.

When `emptySelectionClipboard` is not set, it means you need to select some text to copy. However, for an empty line, there is nothing to select. That's why I say  #71750 undos #59193.

I'd love to have @usernamehw involved in this issue a bit.

**Comment by usernamehw** [comment]
... I just wanted to unlock an issue to advertise a glorious 3-line-long extension https://github.com/microsoft/vscode/issues/55243#issuecomment-423810344. 

Seems simple to me - it's unexpected and people don't like it - then revert #59193. I can republish extension that does exactly the same thing (prevents copying empty lines), but people will know what they're doing.

**Comment by rebornix** [comment]
Sounds fine to me. I'll do the revert instead of adding more `if`.

**Comment by rebornix** [comment]
Should ship with tomorrow's Insiders.

**Comment by dkelosky** [comment]
Thank you all

**Comment by usernamehw** [comment]
@rebornix, it's been 3 Insiders releases, but it seems to be not there.

**Comment by rebornix** [comment]
ops, nice catch. The commit is somehow lost in master. reverted commit https://github.com/microsoft/vscode/commit/fb810784a67c8b673fc6f28195df91ddddb31fc8 .
