### ISSUE TITLE
Terminal window placement setting

### ISSUE THREAD

**Issue by j-mes** [Microsoft/vscode#69901]
As mentioned in [v1.29 update](https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu) that the icon for moving the terminal window either bottom or right has been moved.

What would be nice if an option was in the user settings that could be set to always have the terminal window where the user would prefer to have it rather than configuring it every time a new project is added to VS Code.

In my use case, I prefer having the Terminal window on the right for every project I work on (current or future ones) and it's a bit annoying having to right click on the Terminal link then select 'right' when I could have a setting set in my settings that will automatically put it as right.

Other than that... what an awesome text editor, and I find new things to learn about it every day at work. Amazing stuff indeed.

**Comment by usernamehw** [comment]
```json
"workbench.panel.defaultLocation": "right",
```

**Comment by j-mes** [comment]
> ```json
> "workbench.panel.defaultLocation": "right",
> ```

Thank you for this. It is not really intuitive to know it's that area. Could this be better documented?

**Comment by Tyriar** [comment]
You can also right click on the panel, there used to be a button but we removed it to save space in the panel
