### ISSUE TITLE
Problems with PPA/deb

### ISSUE THREAD

**Issue by furai** [Microsoft/vscode#69907]
Hello,

It seems that someone borked something about updates. Apparently I'm stuck on version 1.33 that was (accidentally??) pushed on 4th of March? I can see 2 more builds that were done after that which have 1.32 version in it. Is everything correct? 

I think because of that APT does not pick up changes as it doesn't consider it a newer version but VSCode reports there is update to download.

I take my information from here:
https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/

Cheers,
Furai

**Comment by Tyriar** [comment]
We just released 1.32 so a new 1.33 release should come in the next few days and fix the issue.

**Comment by furai** [comment]
Ok, thank you for the information.
