### ISSUE TITLE
Improved Screencast mode

### ISSUE THREAD

**Issue by dyc3** [microsoft/vscode#69906]
While fixing #68849, we began discussing how we could further improve the screencast mode. Some of the things we want to add include:

- Displaying counters for repeat key presses
- Remove spaces between letters/numbers/symbols
- Have letters respect the case they were typed in
- More settings for screencast mode

I'd love to take this up, since I've already been working on screencast mode.

**Comment by joaomoreno** [comment]
Will close this as out of scope, thanks for the ideas any way.
