### ISSUE TITLE
Files not reopened after closing and open file from Windows Explorer

### ISSUE THREAD

**Issue by DoCode** [Microsoft/vscode#69919]
Issue Type: <b>Bug</b>

Steps to reproduce:

1) Open VS Code
2) Open a file
3) Close VS Code
4) Open VS Code
5) **SUCCESS:** Files are reopened
6) Close VS Code
7) GoTo Windows Explorer
8) Open a file with right click and open with VS Code
9) **FAILURE:** Only the file from Windows Explorer is reopened. NOT the files from the last session!

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

### This is not related to #66525!!!

**Comment by DoCode** [comment]
@bpasero can you please tell me why this issue is marked as duplicate?  
This is a unique issue and I can not found a similar one! It's simple to reproduce and not a duplicate one from the other.

**Comment by bpasero** [comment]
@DoCode https://github.com/Microsoft/vscode/issues/14675
