### ISSUE TITLE
broken code

### ISSUE THREAD

**Issue by DoggoB0y** [microsoft/vscode#69911]
Issue Type: <b>Performance Issue</b>

so i was just doing some code stuff that i do some times. so i opened my index.js file with the Terminal and i do cd.. , the command to get to the right folder. then i execute the command node index.js and then ''node' is not recognized as an internal or external command,
operable program or batch file.' randomly pops up. i tried multiple times and it was keep saying the same thing. now i cant finish my code and its annoying >:(

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by goxr3plus** [comment]
Oohhhh pure doggo :'(

**Comment by smbkr** [comment]
It sounds like `node` isn't in your `$PATH` from whatever context VS Code is running. Can you run `node` from another terminal emulator? Are you using the same shell in VS Code as you are in your default terminal?

Compare the output of `echo $PATH` in an external terminal and from the integrated terminal as a first troubleshooting step.
