### ISSUE TITLE
[folding] Optionally fold chained method calls

### ISSUE THREAD

**Issue by aaronhoffman** [Microsoft/vscode#6991]
For frameworks that expose a fluent API (ex: [d3.js](https://github.com/d3/d3)), it is common to chain method calls on separate lines. Example [here](https://bost.ocks.org/mike/bar/):

```
d3.select(".chart")
  .selectAll("div")
  .data(data)
  .enter()
  .append("div")
  .style("width", function(d) { return d * 10 + "px"; })
  .text(function(d) { return d; });
```

Currently, the vscode `editor.foldAll` command folds these chained method calls and hides everything except the first line `d3.select(".chart")...`. It would be nice to optionally enable/disable this functionality based on your use case. (In my case, I would disable it by default for all languages.)

Likely related to folding not being language aware: https://github.com/Microsoft/vscode/issues/3422

**Comment by aeschli** [comment]
Yes, this would need language awareness.
