### ISSUE TITLE
Any plan for a simple Tree View guide with JSON data as menu in the Activity bar

### ISSUE THREAD

**Issue by systemaker** [Microsoft/vscode#69917]
Hello,
I am looking for a **simple** tiny example (or tutorial) of a **simple** TreeView filled by a short JSON data for a very cute **simple** menu in the activity bar
Sorry but you know, **life** is too short to try to understand the other TreeProviders :D
Thanks for your help

**Comment by sandy081** [comment]
Here you go - https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample

**Comment by systemaker** [comment]
So when will we get in vscode production version ( not in vscode.proposed.d.ts ) the **TreeView2** class from TestView example ?
