### ISSUE TITLE
Organize Imports removes import used as flow type

### ISSUE THREAD

**Issue by byyo** [Microsoft/vscode#69914]
Issue Type: <b>Bug</b>

If an import is only used as a flow type, the Organize Imports command will remove it.

Here's a small test example:

```js
// @flow
import Moment from 'moment';

const test = (moment: Moment) => {
  console.log(moment);
};

export default test;
```

Running Organize Imports on this file removes `Moment`.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-postgres|cko|1.1.7
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|1.8.1
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
flow-for-vscode|flo|1.1.0
cql|Law|0.8.7
vscode-elixir|mjm|1.1.0
vscode-cosmosdb|ms-|0.10.0
python|ms-|2019.2.5433
azure-account|ms-|0.8.0
Go|ms-|0.9.2
stylelint|shi|0.48.0
language-stylus|sys|1.11.0

</details>

**Comment by mjbvz** [comment]
VS Code does not ship with built-in Flow support. To use Flow, install the [flow extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) and [follow these instructions](https://github.com/flowtype/flow-for-vscode#setup)

**Comment by byyo** [comment]
I am using the flow extension, but I realized that Organize Imports is doing the right thing here. Since I'm only using `Moment` as a type in this file, if i import it as

```js
import type Moment from 'moment';
```

then it will be sorted properly and not removed. Sorry for the erroneous bug report!
