### ISSUE TITLE
Fetching build tasks take a few seconds

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69912]
I remember in the past running build tasks will open terminal at once. However now there's a delay. StatusBar shows "Fetching build tasks" and it'll take a few seconds before anything is shown on terminal.

Why is the build tasks being "fetched" and why should it take this long?

**Comment by alexr00** [comment]
Gulp task enumeration is very slow. You can turn off gulp task detection with `"gulp.autoDetect": "off"
`, but if you have gulp tasks in your tasks.json then you'll get errors. If you don't intend to use the gulp tasks then you can leave gulp task detection disabled and ignore the errors.
