### ISSUE TITLE
Change Stop search button color

### ISSUE THREAD

**Issue by kvprasoon** [Microsoft/vscode#69928]
This is a suggestion. I just noticed the Stop search button in VSCode during _Find in files_ activity.

- VSCode Version: 1.31.1
- OS Version: Windows 10 (10.0.17134)

![image](https://user-images.githubusercontent.com/12897753/53931444-2b3d2400-40bb-11e9-99fd-7dd7849235d3.png)

My suggestion is to set the color of the stop button to Red. I use VSCode every minute every day, but never noticed this !

Related issue : #54727

**Comment by roblourens** [comment]
I think the red is too "in your face". As you can see in that issue you found, there was a bunch of back and forth on this already.
