### ISSUE TITLE
add new function

### ISSUE THREAD

**Issue by helax000** [Microsoft/vscode#69927]
Can search for selected text? , because the code is too much, and i dont want to search for the whole code , i only want to find in a piece of code.

**Comment by byyxx128** [comment]
When you ask for this feature, you should already realize that it should be a basic function.
So...
![image](https://user-images.githubusercontent.com/20079289/53932780-5b5bd700-4069-11e9-9d78-7b5094fbdfa8.png)

As shown above, click ![image](https://user-images.githubusercontent.com/20079289/53932808-847c6780-4069-11e9-8f95-8a47e6600467.png) or press Alt+L.

**Comment by Sovgut** [comment]
![Search](https://i.imgur.com/MvcwBRJ.jpg)

Such a function already exists, press ```CTRL + F``` select the text, press the button that I selected in the screenshot and start the search

**Comment by roblourens** [comment]
Yes also see `editor.find.autoFindInSelection`
