### ISSUE TITLE
Java Debugger Crashing after a few seconds.

### ISSUE THREAD

**Issue by LukeJelly** [Microsoft/vscode#69926]
OS Version Win 10 PRO 1809(OS BUILD17763.316)
Visual Studio Code 1.31.1(user setup)
Java Version 11.0.1 2018-10-16 LTS

Issue: 

Running a very simple java program and debugging the debugger seems to work fine for about 30 seconds then I get the following errors:
"[error] Error: Language client is not ready yet "
"[error] Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined"
"[error] Running the contributed command:'java.execute.workspaceCommand' failed.: Error: Running the contributed command:'java.execute.workspaceCommand' failed."

The debugger crashes I no longer have the option to step through and my variable values in the top left of my screen disappear.  Soon after that I will get the error "The language Support for Java server crashed 5 times in the last 3 minutes" I've uploaded a .zip file of the logs. 

I have tried launching as Administrator, Uninstalling and Reinstalling both VS Code and my JDK, restarting the computer, uninstalling and reinstalling all extensions, disabling my anti-virus, disconnecting from the internet and installing different versions of my JDK.

I attempted to recreate this issue on my Surface Book Laptop
OS Version Win 10 PRO 1803(OS BUILD 17134.590)
Visual Studio Code 1.31.1(user setup)
Java Version 11.0.1 2018-10-16 LTS

The debugger seemed to work fine on my laptop and I have no other computers to try and recreate this on. 

I'm pretty new to VS Code but from the research I've done it looks like this has been an issue with other people but those always seem to lead to a dead end. Either there fix doesn't work for me or they are no longer responding so the issue gets closed. 

I'm new here so sorry if this is in the wrong spot.  Does anyone have any ideas on how to fix this?

Thanks for your help in advance

My logs.
[20190306T193828.zip](https://github.com/Microsoft/vscode/files/2939403/20190306T193828.zip)
[20190306T191446.zip](https://github.com/Microsoft/vscode/files/2939390/20190306T191446.zip)

**Comment by weinand** [comment]
Please file this issue against the Java extension.
