### ISSUE TITLE
Restore focus to the last focused side in a diff editor

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#69922]
Issue Type: <b>Bug</b>

Similar to https://github.com/Microsoft/vscode/issues/22403

1. Open a diff view
2. Put cursor in left side editor
3. Open the command palette, and either run a command or close it

Instead of focus returning to the left side, it is shifted to the right. When the quick open hides, it's trying to focus back on the old editor
https://github.com/Microsoft/vscode/blob/d315d18deec4b9ece7f3cbb9d74a6916bb9718e8/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L281

but the diff editor always focuses the modified side:
https://github.com/Microsoft/vscode/blob/d315d18deec4b9ece7f3cbb9d74a6916bb9718e8/src/vs/editor/browser/widget/diffEditorWidget.ts#L758

I'm trying to write a command for starting a new comment thread, so I need to be able to get the focused editor. But the focus is always changed before the command runs, so there's no way to tell which editor to use

VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T11:10:01.691Z)
OS version: Darwin x64 18.2.0

**Comment by alexandrudima** [comment]
The diff editor is considered to be a single editor by our workbench and when `.focus()` is called, it focuses the right side. The same bug exists, for example, when invoking the quick open from the find widget... focus is not returned to the find widget... Another instance of the same issue is invoking it from an embedded editor like the one in peek definition.

I suggest the quick open checks where focus is before it is invoked and then restores focus when it is dismissed.

**Comment by bpasero** [comment]
I acknowledge the problem but would not want to change the default here simply because the left hand editor very often is not writable and this could cause frustration. 

Having an option for the `focus()` method to consider diff editors as opt-in could work though. Feel free to spin up a PR for that.

**Comment by alexandrudima** [comment]
@bpasero Please check my suggestion:

> I suggest the quick open checks where focus is before it is invoked and then restores focus when it is dismissed

i.e. record `document.activeElement` when quick open is shown and return focus there when it finishes.

**Comment by bpasero** [comment]
@alexandrudima in the end I call `diffEditorWidget.ts#focus()` so the fix has to go in there. This will be a change for every call to `IEditorService#focus()`.

![image](https://user-images.githubusercontent.com/900690/55136065-af6c4f80-512d-11e9-8064-2c8da377f7af.png)

**Comment by chrmarti** [comment]
This is a more general problem. We could track the focus for the entire workbench and when QuickOpen closes, we would just return to the previous active element.

The current solution appears to be to always return focus to the editor, which is not always correct, but has worked surprisingly well so far.

**Comment by alexandrudima** [comment]
@bpasero My recommendation is to read `document.activeElement` when quick open is shown and focus back to that value when quick open is hidden, unrelated to any diff editor. This would cover the case of the find widget or the embedded editor, etc.

**Comment by bpasero** [comment]
@alexandrudima we can do that, just worried that this is changing a pattern people might have gotten used to. Today we give the editor some extra treatment by always moving focus into it when any quick picker closes. We also have to make 100% sure that the command that executes from quick open does not require the editor to be focused. I remember in the past we had some issues with that where focus was not back in the editor but the command assumed that.

@chrmarti btw you are doing the same for `quickInput`: 

https://github.com/Microsoft/vscode/blob/3e2e048b9a3d65c8c47b309e01186bbf788ee6d8/src/vs/workbench/browser/parts/quickinput/quickInput.ts#L1386
