### ISSUE TITLE
Some output of task in integrated terminal is replaced with empty space.

### ISSUE THREAD

**Issue by angusgraham** [Microsoft/vscode#69929]
I've installed the Rust rls plug-in which adds a task which runs the command "cargo build":
https://github.com/rust-lang/rls-vscode/blob/548f3fe471f8e5feabe9f15fab6eedee058ba4b7/src/tasks.ts#L89-L96
My problem is that when I run the task, most of the task's output in the terminal is replaced with empty spaces.
However, if I run "cargo build" in a powershell window it displays fine.
If I run the task from within a VSCode integrated terminal, it works but it prepended by a bunch of empty lines which I imagine is connected.

Here is example output running in powershell:
```
PS C:\Users\agrah\projects\hello_cargo> cargo build
   Compiling hello_cargo v0.1.0 (C:\Users\agrah\projects\hello_cargo)
error[E0425]: cannot find value `error` in this scope
 --> src\main.rs:2:5
  |
2 |     error;
  |     ^^^^^ not found in this scope

error[E0425]: cannot find value `error2` in this scope
 --> src\main.rs:3:5
  |
3 |     error2;
  |     ^^^^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `hello_cargo`.

To learn more, run the command again with --verbose.
PS C:\Users\agrah\projects\hello_cargo>
```
Here is example output from the integrated terminal after running the task:
```
Compiling hello_cargo v0.1.0 (C:\Users\agrah\projects\hello_cargo)
    Building [                                                           ] 0/1: hello_cargo(bin)













For more information about this error, try `rustc --explain E0425`.
error: Could not compile `hello_cargo`.

To learn more, run the command again with --verbose.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
As you can see most of the output has been replaced with whitespace.
And here is a example where I created a new integrated terminal, and typed "cargo build" into it:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.












                                        cargo build
   Compiling hello_cargo v0.1.0 (C:\Users\agrah\projects\hello_cargo)
error[E0425]: cannot find value `error` in this scope
 --> src\main.rs:2:5
  |
2 |     error;
  |     ^^^^^ not found in this scope

error[E0425]: cannot find value `error2` in this scope
 --> src\main.rs:3:5
  |
3 |     error2;
  |     ^^^^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `hello_cargo`.

To learn more, run the command again with --verbose.
PS C:\Users\agrah\projects\hello_cargo>
```
All the output is there, but there's a bunch of whitespace inserted when the terminal is open; before I typed the command.
(RLS bug - closed since it seems to be a VSCode issue: https://github.com/rust-lang/rls/issues/1389)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
