### ISSUE TITLE
Feature request: Outline for the Markdown Preview

### ISSUE THREAD

**Issue by phuctv95** [Microsoft/vscode#69925]
`Ctrl+Shift+V` to open markdown preview is very useful to me for the reading.

In the markdown preview tab, I think it will be more useful if there's an outline (bookmark) which be on the left/right side.

**Comment by mjbvz** [comment]
There's already an outline for markdown files in the editor: https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view

An extension could potentially add an outline for the markdown preview as well for cases where you are not using a side-by-side view
