### ISSUE TITLE
edit file with 2 windows, current line becomes line from other window

### ISSUE THREAD

**Issue by plbowers** [Microsoft/vscode#69934]
Issue Type: <b>Bug</b>

I haven't been able to reliably reproduce this, but it happens pretty regularly for me and this is the situation when it happens:

(a) I use the vim emulator exclusively - I don't know if that's connected
(b) I have the same file open in 2 windows, looking at 2 different places (typically the call to a function and the definition of a function). One window is on the left and one on the right (it doesn't happen if the 2nd window is not visible).
(c) In one window I delete a line (dd) and suddenly my cursor in that window has jumped to the current line number from the *other* window. Sometimes the line I was deleting is deleted where I *was* and sometimes it is deleted in the *new* location

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.1
vim|vsc|1.1.0

</details>

**Comment by alexandrudima** [comment]
Please open an issue directly against the vim extension
