### ISSUE TITLE
improve the find/replace window

### ISSUE THREAD

**Issue by 632575987** [Microsoft/vscode#69933]
![20190307151748](https://user-images.githubusercontent.com/3284852/53938896-88050280-40ec-11e9-8a2b-94959594d911.png)
Request Improve the lookup or replacement function can be like notepad++. Thanks very much

**Comment by roblourens** [comment]
Please give more details about exactly what features you want.

**Comment by 632575987** [comment]
> Please give more details about exactly what features you want.

I would like the find and replace feature in the editor to **provide a text prompt** like notepad++ rather than the simple button, because the button has to hover over it to guess what it will do. And I'd like to **see all the lines I found displayed in a small window at the bottom**, as shown in the figure above，and we can **locate the corresponding line in the editor by double-clicking the row in the bottom window**.


*For example, if you open a file, hold down CTRL +F. Search for some text, and a small window appears below that shows all the matching lines. Double-click the line to locate the line in the original file.*

**Comment by roblourens** [comment]
Showing search results in a separate tab is covered by https://github.com/Microsoft/vscode/issues/23931 which is probably what you want.

Changing the buttons to text probably won't happen, it doesn't fit with the rest of the vscode ux.
