### ISSUE TITLE
Collapse all should cancel creating New file

### ISSUE THREAD

**Issue by jamOne-** [Microsoft/vscode#69946]
- VSCode Version: 1.31.1
- OS Version: MacOS Mojave 10.14.3 (18D109)

Steps to Reproduce:

1. Start creating new file in some directory 
2. Press Collapse All button in the Explorer
3. The project tree is now grayish until opening the directory with the New file name box.
It is even possible to have several New files in separate directories.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Fixed in latest vscode insiders
