### ISSUE TITLE
Word wrap icon not displaying

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#69947]
Open a file with a long line.
Observe
![image](https://user-images.githubusercontent.com/5047891/53952824-2afc5300-40d2-11e9-8fac-e9c677613c56.png)

**Comment by rebornix** [comment]
Verification steps:

* Create a file which has a line longer than 10k chars
* You should be able to see an icon for toggling word wrap for the file in the editor actions toolbar.
