### ISSUE TITLE
Where can I get the all tokenColorCustomizations scope strings?

### ISSUE THREAD

**Issue by Imputes** [Microsoft/vscode#69948]
🚨 The issue tracker is not for questions 🚨

Where can I get the all tokenColorCustomizations scope strings?

**Comment by usernamehw** [comment]
```
Developer: Generate Color Theme From Current Settings
```
```
Developer: Inspect TM Scopes
```

**Comment by Imputes** [comment]
> ```
> Developer: Generate Color Theme From Current Settings
> ```
> ```
> Developer: Inspect TM Scopes
> ```

Thank you

**Comment by Imputes** [comment]
> ```
> Developer: Generate Color Theme From Current Settings
> ```
> ```
> Developer: Inspect TM Scopes
> ```

But I saw there has the string "keyword.operator.sizeof.c", but I have not seen in the "Developer: Generate Color Theme From Current Settings" result file
