### ISSUE TITLE
TextEditor.selection is not respected in clipboard operations

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#6994]
- VSCode Version: ^1.1.0
- OS Version: Windows

Steps to Reproduce:

1. Update `TextEditor.selection`
2. Execute `editor.action.clipboardCopyAction` or `editor.action.clipboardCutAction` commands
3. Instead of copying to clipboard the _new selected word_, it copies the entire line (default Code  behavior when _nothing_ is selected)

The code is basically this one:

```typescript
  const cursorWordRange = doc.getWordRangeAtPosition(selection.active);
  var newSe = new vscode.Selection(cursorWordRange.start.line, cursorWordRange.start.character, cursorWordRange.end.line, cursorWordRange.end.character);
  editor.selection = newSe;
  vscode.commands.executeCommand("editor.action.clipboardCopyAction");
```
The issue already appeared in version 0.10.11 and was fixed in March release (https://github.com/Microsoft/vscode/issues/4393), but returned 1.1.0.

Thanks in advance

**Comment by jrieken** [comment]
@alefragnani  It's not really an API command - the behaviour isn't spec'd. For now I'd recommend to use a node_module to copy stuff to clipboard

**Comment by alefragnani** [comment]
@jrieken I understand that. I just reported the issue because in https://github.com/Microsoft/vscode/issues/4393  it was considered a bug, and was fixed by [this commit](https://github.com/Microsoft/vscode/commit/a5a166a519790ec1863493da8a67b1700f1ac32a).

I will move to https://github.com/xavi-/node-copy-paste, as you suggested in some other issues, like https://github.com/Microsoft/vscode/issues/4972 and https://github.com/Microsoft/vscode/issues/217.

Thanks

**Comment by jrieken** [comment]
@alexandrudima Can you comment?

**Comment by alexandrudima** [comment]
Sorry for not noticing this comment, I tried the following and it works for me:

```typescript
commands.registerCommand('test', () => {
		let editor = window.activeTextEditor;
		let doc = editor.document;
		let selection = editor.selection;

		const cursorWordRange = doc.getWordRangeAtPosition(selection.active);
		var newSe = new Selection(cursorWordRange.start.line, cursorWordRange.start.character, cursorWordRange.end.line, cursorWordRange.end.character);
		editor.selection = newSe;
		commands.executeCommand("editor.action.clipboardCutAction");
	});
```

**Comment by alefragnani** [comment]
No problem @alexandrudima 👍 

I followed @jrieken suggestion and since then, I'm using https://github.com/xavi-/node-copy-paste, instead of the clipboard `commands`.

Thanks
