### ISSUE TITLE
Opening an URL fails if URL scheme is uppercase

### ISSUE THREAD

**Issue by BillDietrich** [Microsoft/vscode#69941]
In my extension, following code works on URLs with lowercase scheme such as "http://example.com", but fails with "resource '' not available" or similar message on URLs with uppercase scheme such as "HTTP://example.com":

    let sTheURL = "HTTP://example.com";
    commands.executeCommand('vscode.open', Uri.parse(sTheURL));

I'm on Linux Mint 19.1.  Tried giving similar uppercase-scheme URL to KeepassXC to open, and it had no problem sending it to the browser.

Version: 1.33.0-exploration
Commit: 0c0bd7afe1491bf498db49dee9c411ae8d9bbbc1
Date: 2019-03-05T08:48:48.676Z
Electron: 4.0.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-46-generic

**Comment by alexr00** [comment]
Added this line to the hello-world sample:
````typescript
		vscode.commands.executeCommand('vscode.open', vscode.Uri.parse("http://bing.com"));
````
Works great in stable. Does not work at all in insiders.

**Comment by jrieken** [comment]
@alexr00 what you ran into is https://github.com/Microsoft/vscode/issues/71112

**Comment by jrieken** [comment]
this issue is only about `HTTP` vs `http`
