### ISSUE TITLE
Terminal PWD is always root

### ISSUE THREAD

**Issue by rgjamkhedkar** [Microsoft/vscode#69949]
Issue Type: <b>Bug</b>

Terminal: Integrated
Shell: Fish
Since the last update, whenever I open the terminal by pressing CTRL + \`, the working directory is always os root directory instead of project root. Not even the user home directory, but `/`. 
However, the path shown before the cursor correctly shows the project directory path. Git commands also execute in the project root. `pwd` command shows `\`. 
So I am not sure what is happening. I am also not sure if the problem is in fish or in VS code. But as this doesn't happen in other IDEs. I think it is a VS code issue. 

<img width="1060" alt="screenshot 2019-03-07 at 16 57 03" src="https://user-images.githubusercontent.com/3964412/53953740-2350a480-40fa-11e9-9b45-fbaf63f5f42b.png">

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (4.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
swift|Kas|0.0.3
better-comments|aar|2.0.3
project-manager|ale|10.3.2
react-pure-to-class-vscode|ang|1.1.8
vscode-color|ans|0.4.5
vscode-custom-css|be5|3.0.3
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.25.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.1
fileheadercomment|doi|0.0.3
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-author-generator|edw|0.0.8
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
css2react|got|0.0.6
search-node-modules|jas|1.3.0
sublime-babel-vscode|jos|0.2.10
vscode-styled-components|jpo|0.0.25
vscode-scss|mrm|0.6.2
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.6.3
code-settings-sync|Sha|3.2.7
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
local-history|xyz|1.7.0
sort-js-object-keys|zen|1.0.6
html-css-class-completion|Zig|1.18.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Update to fish 3.0.2 if you're using v3 https://fishshell.com/release_notes.html
