### ISSUE TITLE
NodeJs Debug, add some default settings

### ISSUE THREAD

**Issue by katlimruiz** [microsoft/vscode#69959]
When creating a launch.json with node, the following settings should be added by default: outputCapture and skipFiles.

```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\index.js",
            "outputCapture": "std",
            "skipFiles": [
                "<node_internals>/**"
            ],
        }
```

This way when stepping in and out you dont find trapped in the async hooks, and so on.

If not possible both, at least skipFiles.

**Comment by roblourens** [comment]
outputCapture just exists for some special scenarios, I wouldn't recommend it as a default.

It might be good to show off skipFiles by default. I think not enabled by default, but included in new generated configurations by default. What do you think @auchenberg or @weinand?

**Comment by auchenberg** [comment]
@roblourens I don't have strong opinions about `skipFiles` and `outputCapture`, but instead of providing more default options that get's written to all `launch.json`'s, wouldn't we update the internal defaults? I'd like to keep our debug configuration as minimal as possible.

**Comment by roblourens** [comment]
I can't decide whether adding that as an internal default is too "opinionated" or not. Debugging inside node internal modules is a legitimate thing to do, but ending up in them by accident, especially the async ones, is annoying. So adding it to the autogenerated launch configs could be a way to advertise it without making people have to google for how to turn it off. But yeah it is counter to the goal of making the launch config minimal. So anyway I probably won't do anything about this right now.

**Comment by DABH** [comment]
Hi @roblourens -- just wondering about `outputCapture` or `console` defaults in particular, based on e.g.
https://github.com/Microsoft/vscode/issues/19750#issuecomment-335127119
https://github.com/Microsoft/vscode/issues/34702#issuecomment-331237388
In a perfect world I'd like `winston` logging library users to have success in vsc out-of-the-box, and it's awesome vsc does have the necessary support.

Is there any downside to default `"console": "internalConsole"` or `"outputCapture": "std"`?  Changing the console sounds dramatic (maybe it's not though?), but making sure appropriate output is captured sounds like a strict positive?  (I'm naive here, haven't looked into exactly what that option is doing internally.)

**Comment by roblourens** [comment]
`"console": "internalConsole"` is the default. What issue are you having?

`"outputCapture": "std"` has the downside that you only get logs as text, not the live interactive objects that we get through the debug connection.

**Comment by DABH** [comment]
So I'm trying to `Debug` the following script:
```
const { createLogger, format, transports } = require('winston');
const { combine, timestamp, prettyPrint } = format;

const logger = createLogger({
  format: combine(
    timestamp(),
    prettyPrint()
  ),
  transports: [new transports.Console()]
})

logger.info('hey');
console.log('hi');
```
I'd expect to see both messages on the console, but since winston's console transport writes directly to stdout, only `hi` is printed in the vsc debug terminal.  Adding `"outputCapture": "std"` to my `launch.json` debug config makes both messages print in the Debug terminal.  But I sympathize with users who are confused when they try to debug their code but don't see log messages being printed -- not obvious this setting is needed without googling.

I think I understand your point about the downside of `"outputCapture": "std"`.  Seems a bit odd only one or the other behavior is possible -- wouldn't it be possible to capture the union of the std output and interactive objects, if that makes sense?

**Comment by roblourens** [comment]
Then in a normal case, logs will show up twice. It's not possible to dedupe them because they can be formatted differently.

**Comment by ccinelli** [comment]
1.  It took me a while to figure out what was going on here: with the [npm module `debug`](https://www.npmjs.com/package/debug), that is (or at least used to be) pretty popular,  a `debug("something")` does not show anything anywhere. Adding `"outputCapture": "std",` shows the output but without color and the module prefix. With `"console": "integratedTerminal",` shows, of course, what you normally would see in the terminal.
It seems the same behavior in #19750. Ideally `vscode` can display the typical terminal output in  "Debug Console". If it is not possible I think that `"outputCapture": "std",` or `"console": "integratedTerminal",` should be added as default. 

2.  I suggest to add: `"env": {},` too. It makes discover (or remember) how to add env parameters easier for the beginner (and who does not use env variable often).  

3. It looks like that `vscode`'s JSON config already support comments. It would be great to add some comments on what the options are and maybe adding some extra options commented out. The `// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387`  line is great but that link does not seems to have a reference to all the options.

**Comment by roblourens** [comment]
I think we should add the above `skipFiles` suggestion as a default for all config snippets and dynamically generated configs.

Need to modify here: https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L59

and the snippets here: https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L179

(@connor4312 note that this is in vscode-node-debug, not vscode-node-debug2)

**Comment by weinand** [comment]
@connor4312 please make sure that there is a test item and an entry in the October 2019 release notes for this.
