### ISSUE TITLE
winpty-agent constant high i/o

### ISSUE THREAD

**Issue by primaeval** [Microsoft/vscode#69953]
Issue Type: <b>Bug</b>

VSCode launches winpty-agent.exe processes with constant ~1MB/s I/O as shown by Process Hacker.
I have tried it on Python and Cordova projects so far. 
It doesn't matter if the terminal is PowerShell or just cmd.
Changing this setting makes no difference either.
"terminal.integrated.windowsEnableConpty": true

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.2.5558
cordova-tools|vsm|1.8.0

</details>

**Comment by Tyriar** [comment]
windowsEnableConpty will work in the next Windows 10 release (190*)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
