### ISSUE TITLE
QuickOpen: Rewrite using quick input widget

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#69955]
- [x] Quick Open https://github.com/Microsoft/vscode/issues/29096 not sure if @chrmarti or @bpasero 
- [x] Custom Views https://github.com/Microsoft/vscode/issues/63566 @sandy081 @alexr00 
- [x] Extensions Editor @sandy081 
- [x] Comments Panel @rebornix 
- [x] Delete old tree @joaomoreno

**Comment by bpasero** [comment]
@chrmarti fyi in order to use your `QuickInput` for quick open it would have to be accessible from `vs/editor` because we have some of the quick opens functional in the standalone editor.

**Comment by sandy081** [comment]
@joaomoreno `indent` option is not working here:

https://github.com/Microsoft/vscode/blob/a2e8a03d55cde707b6d56b1c3532f37b442a86b0/src/vs/workbench/contrib/extensions/browser/extensionsViewer.ts#L206

**Comment by joaomoreno** [comment]
@sandy081  What do you mean?

**Comment by sandy081** [comment]
I have different indentation for extension deps/pack tree. But the new tree is not respecting the indentation value I provide.

**Comment by joaomoreno** [comment]
Custom trees have adopted. :fireworks: 

We're getting closer

**Comment by rebornix** [comment]
Comments panel already adopted the new tree.

**Comment by joaomoreno** [comment]
@rebornix Fantastic!

**Comment by joaomoreno** [comment]
@chrmarti @bpasero Feel free to pass it back to me once quick open adopts the tree.

**Comment by bpasero** [comment]
This is something I would like to work on rather soon.

**Comment by chrmarti** [comment]
@bpasero Would you move to the new tree or QuickInput (which uses a list)?

**Comment by bpasero** [comment]
@chrmarti ideally quick open would use the quick input widget. My understanding is that all of the features quick open supports are surfaced on quick input too, but maybe I am wrong. I do not think we would want tree support for quick open, so the list seems fine to me.

One thing making this a bit harder is the fact that we need to support the standalone editor as well, so the quick input widget needs to be available from a lower layer than workbench.

**Comment by chrmarti** [comment]
Many features of the QuickOpen widget are available in QuickInput. Let me know when you need more, I'd be happy to get this issue done.

QuickInput only loosely depends on the workbench since it's only a widget. A few injections should make the code work on a lower layer. We should quickly discuss how we want to do this.

**Comment by bpasero** [comment]
I think as long as quick input widget lives in `vs/base/browser` we should be OK for the usage from both editor and workbench 👍

**Comment by joaomoreno** [comment]
@chrmarti @bpasero Let's get quick open moving to the list! We could delete a bunch of code once that's done. Also, you'll get a *big* perf improvement doing so.

**Comment by bpasero** [comment]
Yeah we discussed this and will start by bringing quick input down to base, then I can look into the rest in December.

**Comment by joaomoreno** [comment]
Yey!

Merging perf issue here: https://github.com/microsoft/vscode/issues/84945

**Comment by bpasero** [comment]
**Status:**
* quick open via quick input can be enabled via `"workbench.quickOpen.enableExperimentalNewVersion": true`
* will probably change the default sometime next week for more selfhosting coverage
* can then delete old code once we feel comfortable either end of milestone or in debt week
