### ISSUE TITLE
Top of window cut off on dual screen setup

### ISSUE THREAD

**Issue by DylanCottell** [Microsoft/vscode#69951]
Issue Type: <b>Bug</b>

I'm using a dual screen setup - my main screen is 16:10 and my secondary is 16:9. If I maximuze the window on the 16:10 monitor, the top of the window is missing - it's completely cut off and renders a glitched view based on whatever window was there before. On my 16:9 monitor it doesn't do this.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.11.3

</details>

**Comment by Tyriar** [comment]
Can you post a screenshot?

**Comment by DylanCottell** [comment]
Replicated again today - seems to be a windows bug/hardware bug rather than a bug with VS Code as I can replicate with multiple windows rather than just VS Code today. Apologies - closing ticket.
