### ISSUE TITLE
Right click menu from a file in the explorer gets closed and clicked immediately

### ISSUE THREAD

**Issue by rolurq** [Microsoft/vscode#69961]
![vscode_rc_menu](https://user-images.githubusercontent.com/13684824/53966354-00ee6500-40c1-11e9-877e-7cc8e88ad36d.gif)

The right click menu sometimes appears and is immediately clicked in the position the mouse is at the moment of showing up. As you can see, this doesn't happen always, but I think is because the second time the menu appears completely above the mouse. 

- VSCode Version: 1.31.0
- OS Version: Linux x64 4.18.0-2-amd64

Steps to Reproduce:

1. Right click a file in the explorer sidebar

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
#65787
