### ISSUE TITLE
Running multiple queries not possible

### ISSUE THREAD

**Issue by Edgarnp** [Microsoft/vscode#69965]
Issue Type: <b>Bug</b>

Why can't we run multiple simultaneous queries under interactive hive mode?

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.62GB (13.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
python-preview|don|0.0.4
azure-storage-explorer|for|0.1.2
azure-virtual-machine-explorer|for|0.0.2
vscode-remote-workspace|mkl|0.38.0
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.13.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.0
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.1.0
vscode-ai|ms-|0.4.2
azure-account|ms-|0.6.2
azurecli|ms-|0.4.3
vscode-node-azure-pack|ms-|0.0.5
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.5.0
azure-hdinsight|msh|1.1.1
vscode-docker|Pet|0.5.2
vscode-yaml|red|0.3.0
python|tht|0.2.3
usql-vscode-ext|usq|0.2.14
application-insights|Vis|0.4.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
What do you mean? What's _interactive hive mode_?
