### ISSUE TITLE
Support multiple sets of editor groups

### ISSUE THREAD

**Issue by cdmihai** [microsoft/vscode#69968]
Issue Type: <b>Feature Request</b>

Many times I need to work on different aspects of a repository. Each aspect would require a different set of editor groups. Ideally, I would open up each aspect in its own editor group and switch between editor groups when I switch between aspects. But today this is not possible.

By one editor group I understand all the horizontal / vertical splits on the screen. So a set of editor groups would be a collection of multiple vs "screen layouts" really.

Examples of aspects / editor groups:
- build code editor group. This is all the relevant files of the build engine
- real code editor group. All the sources
- test results editor group. After I run unit tests, some xml files get generated

For each aspect I have a different optimal editor group arrangement with its own vertical / horizontal splits.

Implementation ideas:
- support opening multiple vscode instances over the same directory, so I can have different editor groups in each one. Although this is not ideal, as the editor groups take time to setup and losing one instance would waste my setup effort
- introduce the concept of editor group sets, where I press a button / shortcut which then "zooms out" and shows me all the editor groups, maybe a preview box for each group, which I could also name, and then have all of them persisted between vscode instances.

Similar concept in other tools:
- [TMUX](https://en.wikipedia.org/wiki/Tmux), which persists multiple terminal tabs, where each terminal tab has multiple vertical / horizontal panes.
- [session buddy](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko?hl=en), a chrome extension, which allows one to save, name, and somewhat switch between multiple sets of tabs 

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by andyhasit** [comment]
I also think this would be incredibly useful. 

A simple workaround in the meantime is to create multiple workspaces for the same project. Just `Save Workspace As` to create a clone, you can then use `Open Workspace` (even better with keyboard shortcut like `ctrl+alt+p`) to switch between them. If you save your `.code-workspace` files in the same directory without too many other things in there it works quite well.

The only downside are:

1. The CPU might skyrocket whenever you switch workspaces.
2. If you make changes to the folder list or settings then you need to manually replicate those across `.code-workspace` files .

**Comment by Starwort** [comment]
I would also like this; Terminal group layers are already very useful and I'd make heavy use of an equivalent for editor groups
