### ISSUE TITLE
Visual studio Code not starting in Kali Linux

### ISSUE THREAD

**Issue by RisticMilos** [Microsoft/vscode#69966]
- VSCode Version:1.31.1
- OS Version:Kali Linux

Steps to Reproduce:

1.Open terminal
2.enter: code

Does this issue occur when all extensions are disabled?: Yes/No
Yes

I'm using Kali Linux from Microsoft Store, part of WSL and I installed code multiple times using .deb file using tar archive and using repository. Every time code installs fine but never start. When I run code it start processes for vscode but GUI never shows up. Tried reinstalling whole Linux distro but nothing helped.
I'm hoping you can help me with this I really need this to start working soon.

**Comment by DarthSpock** [comment]
I recommend you install for Windows but if you really want to install on WSL, I recommend using Wlinux, Debian, or Ubuntu. You can pen-test code in other distros installed in WSL if that was concern. Just nothing really IP related.

**Comment by Tyriar** [comment]
We don't support running the Linux binary of VS Code inside WSL as it wasn't designed to run GUI apps.
