### ISSUE TITLE
Please consider adding fold support for TypeScript 'type' definitions

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#69962]
Issue Type: <b>Feature Request</b>

Fold support already exists for TypeScript interface's but it does not exist for type definitions. 

VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T10:06:48.833Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Please provide a small code example (as text) that show what should be foldable.

**Comment by frankhale** [comment]
Given the following two code snippets. Visual Studio Code currently supports folding at the line that reads "interface PointInterface {" but does not have support to fold the type definition in the same manner.

```typescript
interface PointInterface {
  x: number;
  y: number;
}

type PointType = {
  x: number;
  y: number;
};
```

**Comment by mjbvz** [comment]
Thanks. I confirmed this and have opened https://github.com/Microsoft/TypeScript/issues/30466 to track this upstream
