### ISSUE TITLE
CPU over-usage once computer running VSCode is resumed after having been in sleep mode

### ISSUE THREAD

**Issue by SR-G** [Microsoft/vscode#69973]
- VSCode Version: 1.31.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Start vscode
2. Create some files (at this point everything is normal)
3. Put computer in sleep mode
4. Resume computer from sleep mode : vscode is then starting to over-consume CPU for no reason

This is quite new, it wasn't happening a couple of versions ago.
On my system it's always like this.

When the problem happens, it doesn't seem to be related to extensions as show with a `code.exe --status` when the problem is happening.

```
c:\Tools\VSCode\1.31.1>Code.exe --status

c:\Tools\VSCode\1.31.1>

Version:          Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS Version:       Windows_NT x64 10.0.17763
CPUs:             Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3503)
Memory (System):  15.97GB (6.06GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
   10       83    5832  code main
    0       73    2760     shared-process
    0      157   10660     gpu-process
   14      246   12244     window (2019-03.md - hugo-blog - Visual Studio Code)
    0       79    1268       extensionHost
    0        6    5872       winpty-process
    0       11    5188         console-window-host (Windows internal process)
    0        5    8240         C:\Windows\System32\wsl.exe
    0        5    8848           C:\Windows\System32\lxss\wslhost.exe {8ce83b0e-17b7-4867-ab35-bf9cd76a7e04} 464 472 476
    0       13   11848             console-window-host (Windows internal process)
    0       13    9372       electron-crash-reporter
    0       12   12108       watcherService
    0       11   12024         console-window-host (Windows internal process)

Workspace Stats:
|  Window (2019-03.md - hugo-blog - Visual Studio Code)
|    Folder (hugo-blog): 1833 files
|      File types: png(762) jpg(326) svn-base(157) md(116) html(70)
|                  markdown(61) js(59) css(37) svg(36) csv(22)
|      Conf files: launch.json(1) settings.json(1)
```

(it doesn't seem that much in the status, but it puts my computer on its kneels)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by serseb** [comment]
This happens to me as well. `code --disable-extensions`  didn't fix the issue. What I noticed is this only happens when I have network files open, therefore it could be related to the temporary files unavailability when resuming from sleep.

**Comment by SR-G** [comment]
Indeed, i forgot to add that information, i'm also encountering this problem whereas VSCode is running on a windows (client) PC wheras all my files are stored on a remote NAS (through a samba share).

Also, disabling extensions doesn't help in my situation.
