### ISSUE TITLE
When dismissing a search result, the total result count should decrement by 1, or indicate dismissed results count

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#69977]
I do not see a duplicate of my issue:

![image](https://user-images.githubusercontent.com/6444116/53983003-4708f000-40e4-11e9-872f-770005a4162a.png)

So I'm in the clear.

- VSCode Version: 1.32.0
- OS Version: Windows 10 1809 Stable

Steps to Reproduce:

1. In Visual Studio Code, click on the "Search" sidebar menu item to bring up the huge Search menu. 

![image](https://user-images.githubusercontent.com/6444116/53984028-7d476f00-40e6-11e9-9a4e-75c2c8e37037.png)

2. Search for a common word used quite a lot. Like "a", "let", "var", "i", and so forth.
3. When the Search displays the total results count, dismiss a few of them.
4. The total results count should **decrement by 1** per dismissal, or indicate both the **original total results count and the remaining non-dismissed total results count** side by side when dismissing the search results. For example:

![image](https://user-images.githubusercontent.com/6444116/53983993-6a349f00-40e6-11e9-94bc-b5fcfaed4839.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
For me, it does decrement. You don't see that? You are clicking the 'x' icon on a result row, right?

**Comment by tommai78101** [comment]
@roblourens It doesn't. 

![GIF](https://user-images.githubusercontent.com/6444116/54056400-ecdc5d80-41bd-11e9-89fa-1be9b30da470.gif)

**Comment by tommai78101** [comment]
Ok, so I was about to get it to decrement, but that's not done in real-time.

![GIF](https://user-images.githubusercontent.com/6444116/54056465-2a40eb00-41be-11e9-8583-84f1716c411d.gif)

**Comment by roblourens** [comment]
That's right, I thought you were talking about the total shown at the top ("x results in y files") in your original post.

**Comment by jeanp413** [comment]
This also happens when a new match is added or deleted in an existing file match.
![Peek 2019-04-08 08-32](https://user-images.githubusercontent.com/25115070/55728351-8a06fd80-59d9-11e9-9a6e-89fcc3346bb9.gif)
