### ISSUE TITLE
VSCode Feb 2019 update emptied all open, unsaved docs

### ISSUE THREAD

**Issue by penCsharpener** [Microsoft/vscode#69978]
- VSCode Version: 1.32.0
- OS Version: Win 10  18H2

Steps to Reproduce:

1. use VSCode 1.31.1 System installer
2. have 3 tabs open that have some text in them but aren't save
3. run built in upgrade to 1.32
4. 3 tabs are restored but are completely empty, no text inside :-(

Does this issue occur when all extensions are disabled?: Yes/No
* not tested

**Comment by MartinZubek** [comment]
Same thing for me... :(

**Comment by Eldaw** [comment]
Already reported here: https://github.com/Microsoft/vscode/issues/69972
