### ISSUE TITLE
VSCode Installer does not need a Start Menu Folder

### ISSUE THREAD

**Issue by AdamBraden** [Microsoft/vscode#69985]
Issue Type: <b>Bug</b>

Why does VSCode install a Start Menu folder on Windows?  The only thing in the folder is VSCode itself.  You only need to install the app, not the folder.  Keeping it this way is an ugly UX experience.

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.18349

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.1
vscode-adaptivecards|tom|1.1.3

</details>

**Comment by joaomoreno** [comment]
#69650
