### ISSUE TITLE
[Bug] Changing color theme in workbench causes vscode to crash

### ISSUE THREAD

**Issue by kalpaj12** [Microsoft/vscode#69984]
Type: **Bug**

Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:46:10.898Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

Steps to Reproduce:

1. Open vscode settings.
2. Try changing workbench colour theme to abyss and then switching back to the default.   

Sometimes, vscode crashes. Most of the time it goes unresponsive. 
Does this issue occur when all extensions are disabled?: Yes

**NOTE:** This issue is carried from 1.32.0
After updating to 1.32.1 vscode freezes and re-springs

**Comment by aeschli** [comment]
@kalpaj12 That's with the Settings UI?
Does the same happen when you use the menu (File > Preferences > Color Theme) or the keyboard (Ctrl+K & Ctrl+T)

**Comment by kalpaj12** [comment]
Yes, it crashes when changes are made from settings ui (Ctrl +,) but works fine when using the keybindings.

**Comment by roblourens** [comment]
I don't know what would cause this. I can't repro it. @sandy081? If you start through a terminal with `code --verbose` and try this, is there any error message?

**Comment by aeschli** [comment]
@kalpaj12 Can you attach your current user settings? Maybe that's related.

**Comment by kalpaj12** [comment]
[This](https://drive.google.com/open?id=1cZtBBztrhVF4Wlzu_LOaSFdN1e0vxoMX) is the screen recording describing the issue.

**Comment by kalpaj12** [comment]
Current user settings:
```
{
    "zenMode.hideLineNumbers": false,
    "global-config.folder": "/home/kalpaj_ag1/Desktop/CodeBuilders/.vscode",
    "editor.minimap.enabled": false,
    "css.lint.hexColorLength": "warning",
    "less.lint.argumentsInColorFunction": "ignore",
}
```

**Comment by roblourens** [comment]
I can repro that and it's fixed in Insiders. I wouldn't call that a hang or crash though.

It's not pretty but I wouldn't call it a candidate, do you agree @aeschli?

**Comment by kalpaj12** [comment]
This issue no longer persists in 1.32.3
