### ISSUE TITLE
Cmd Font doesn't start on the same line

### ISSUE THREAD

**Issue by tateelay2013** [Microsoft/vscode#69989]
Issue Type: <b>Bug</b>

When I typed in the command prompt for the terminal, the font begins on a separate line until I cleared the screen. 

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
notepadplusplus-keybindings|ms-|1.0.2

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
