### ISSUE TITLE
Add instructions for associating extensions with vscode-insiders on macOS

### ISSUE THREAD

**Issue by shreeve** [Microsoft/vscode#69991]
In the [Visual Studio Marketplace](https://marketplace.visualstudio.com), if you use a browser and click "install" on a vscode extension, it uses a special url "vscode:extension/{extension-name}" to automatically install the extension in vscode.

However, if you have vscode-insiders installed (and not the "normal" vscode), then the special url will fail.

What is needed is a simple way to associate these special urls with vscode-insiders.

In order to do this, the following is needed:

1) Edit the `Info.plist` to change the url scheme prefix from `vscode-insiders` to `vscode`
2) Invoke a command line program to re-register the updated url scheme handler

Here's how to do this:

1) Open an editor with the following file and change the following line to `vscode` (as shown) instead of `vscode-insiders` (what it originally was).

`nano /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Info.plist`

<img width="414" alt="info plist" src="https://user-images.githubusercontent.com/142875/53991118-21311a80-40e7-11e9-9e8f-873eef0c3e5a.png">

2) Run the following command line program to update the url scheme handler:

`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f /Applications/Visual\ Studio\ Code\ -\ Insiders.app`

Now, you should be able to click on any extension in the [Visual Studio Marketplace](https://marketplace.visualstudio.com) and it'll work!

**Comment by shreeve** [comment]
Can these instructions be added somewhere in the vscode-insiders documentation?

**Comment by joaomoreno** [comment]
The real fix is to get the Marketplace to show Insider links. They are already aware of this limitation.

cc @viradhamMS @pkuma-msft
