### ISSUE TITLE
 Focus Left/Right editor group should not wrap

### ISSUE THREAD

**Issue by anthonytranDev** [microsoft/vscode#69996]
Environment
---

>  **System:**
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Shell: 3.2.57 - /bin/bash

>  **Binaries:**
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v10.14.2/bin/npm

> **VSCode Version:** 1.32.0

Steps to Reproduce:
---
**Create a shortcut for  `Focus Left Editor Group`**
1. Install VSCode version 1.32.0
2. Go to Preferences: Open Keyboard Shortcuts 
Mac OSX - `shift` + `cmd` + `P`
Windows - `shift` + `ctrl` + `P`

3. Search `Focus Left Editor Group`
4. Create a shortcut for `Left Editor Group`
5. Repeat **Steps 2 - 4** for `Right Editor Group`

### Result
![Focus Editor Groups](https://media.giphy.com/media/1qfcxfIXQvHvrC6Smd/giphy.gif)

For more details on setting up shortcuts please see [vscode keybinding](https://code.visualstudio.com/docs/getstarted/keybindings)

Keybindings Used
---
**Keybind L** - `Left Editor Group` - `shift` + `alt` + `L`
**Keybind R** -`Right Editor Group` - `shift` + `alt` + `R`

Expected result
---
#### Scenario 1 - Left Editor Group
When only 2 editor groups are present
When focus is on right editor group
When I use **Keybind L**  it should go to the left editor group.
When I use **Keybind L** *again*, it should stay in the same editor group

#### Scenario 2 - Right Editor Group
When only 2 editor groups are present
When focus is on left editor group
When I use **Keybind R**  it should go to the right editor group.
When I use **Keybind R** *again*, it should stay in the same editor group

Actual result
---
#### Scenario 1 - Left Editor Group
When only 2 editor groups are present
When focus is on right editor group
When I use **Keybind L**  it goes to the left editor group.
When I use **Keybind L** *again*, it goes to right editor group - as if it has been toggled

#### Scenario 2 - Right Editor Group
When only 2 editor groups are present
When focus is on left editor group
When I use **Keybind R**  it goes to the right editor group.
When I use **Keybind R** *again*, it goes to left editor group - as if it has been toggled

**Does this issue occur when all extensions are disabled?: Yes/No**
No

**Comment by bpasero** [comment]
@anthonytranDev you say

> Focus Left/Right Editor Group doesn't work for 2 Editor Groups

But you actually just do not want that going left/right wraps over to the other side when the first/last is reached?

**Comment by anthonytranDev** [comment]
@bpasero I just think it would be best that whenever there are only 2 editor groups.

So that it does not wrap, but instead actually go to left as intended and right as intended.

The naming of the hotkeys is more of a *misnomer*, as the naming doesn't represent what it was suppose to do - in the case of 2 editor groups opened.


Solution
---
An potential approach (based on simple speculation of course). Would be to have

- Disable the wrap functionality of 2 editor groups
- Enable the wrap functionality of 3 or more editor groups - to scroll left and right of multiple editor groups.

I'm willing to have a go at the problem - especially the fact the amount of issues you guys have currently is 5000+  :astonished:

**Comment by bpasero** [comment]
This can be done once https://github.com/microsoft/vscode/issues/22755 lands. Marking as duplicate.
