### ISSUE TITLE
Requires update even when the IDE is the latest

### ISSUE THREAD

**Issue by spiralni** [Microsoft/vscode#6999]
- VSCode Version: 1.1,0
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open the IDE
2. The IDE shows and update to 1.1.0

**Comment by spiralni** [comment]
![vcupdate](https://cloud.githubusercontent.com/assets/339101/15629810/4a77ec14-24e0-11e6-8dff-7a36882749ec.png)

**Comment by Tyriar** [comment]
@joaomoreno I've actually seen this a lot on Linux alpha, I thought it was something to do with the alpha or assumed non-master builds were getting checked.

**Comment by ugurozturk** [comment]
Am i wrong ? Latest VS Code version is 1.1.1
- Win 10

**Comment by Tyriar** [comment]
@ugurozturk you are indeed, the latest is 1.1.1 (def9e32). I'm curious if @joaomoreno has comments on me seeing the update message on the Linux alpha build though.

**Comment by joaomoreno** [comment]
I am confused. The latest version is 1.1.1, Code is telling you to update to that. What is wrong with that?

@Tyriar What have you seen a lot in alpha? If you see an update notification and update, do you continue seeing it?

**Comment by Tyriar** [comment]
@joaomoreno I don't think the alpha notification on Linux tells you the version, just sends you to the list specified in the product.json.

**Comment by joaomoreno** [comment]
Which list?

**Comment by Tyriar** [comment]
link* https://github.com/Microsoft/vscode-distro/blob/master/quality/alpha/product.json#L15
