### ISSUE TITLE
[html][css] [custom data] Extension contributes settings don't take effect until vscode restarted now

### ISSUE THREAD

**Issue by bkelley13** [microsoft/vscode#70000]
- VSCode Version:1.32
- OS Version: mac/windows

Steps to Reproduce:

1.  Get an extension that has the html customData contributes setting for html tag lookups:
https://github.com/Microsoft/vscode/issues/68554
Download: https://github.com/Microsoft/vscode/files/2857364/svg-0.0.1.vsix.zip
2. Install in 1.32.
Notice the message says it installed fine.  In 1.31 it would say click "reload".
3. Open up an html file
4. Type <foreign  .  It should have offered you <foreignObject> but nothing happens.  The html editor's customData setting from the extension's contributes isn't working.  
5. Restart VSCode.
6. Repeat.  It works.

This is a regression in behavior from 1.31.  In 1.31, after installation of a vsix file, you would click on "Reload" button in message, and the settings would take effect.  Even doing a disable/enable on the extension doesn't work, you have to restart VSCode. 1.31 was much nicer, that you didn't have to do that.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
@octref We now install extensions without reload. New extensions can add new contribution points. You need to listen to `extensions.onDidChange`

**Comment by bkelley13** [comment]
Wouldn't this mean that the html extension would need to add onDidChange support to cope with this extension's installation modifying the contributes html.experimental.customData setting?

**Comment by aeschli** [comment]
This got fixed a few month back. No reload is necessary anymore for custom data to be picked up.
