### ISSUE TITLE
After Update to 1.32, I lost all unsaved content of file

### ISSUE THREAD

**Issue by jualy007** [Microsoft/vscode#70008]
Before Update to 1.32, vscode version is 1.31.1, and I have open 5 or mode files that unsaved, After update to 1.32, all unsaved content are missing.

I believe previous version will keep all unsaved content, even update to new version, it seems this version break this feature.

**Comment by pelonchasva** [comment]
Came here to post an update, since I was going to duplicate this issue.

This behavior has been happening from two previous updates, I recently lost 2 important files that I haven't saved over time (my fault tho), but still, it was nice that VS Code will remain your work even after an update.

**Comment by cylvoon** [comment]
It just happened to me, with version 1.32.1.
No need to mention I'm very upset right now, lost 8 files.
I've always used this feature in both notepad++ and VSCode, but despite being developed by only one guy, notepad++ never destroyed any of my content...
