### ISSUE TITLE
Window crashes when you refresh a git repo twice in the Source Control panel

### ISSUE THREAD

**Issue by jextrevor** [Microsoft/vscode#70003]
Issue Type: <b>Bug</b>

1. Open up a VS Code workspace with two or more git repos.
2. Navigate to the Source Control pane in the sidebar.
3. Click the refresh icon next to a repository twice in rapid succession.
4. Observe the window crash.

I've attached a screenshot of what the window crash looks like.
This issue doesn't happen for single repo windows, since the refresh icon seems to be disabled while the repo is still refreshing.
![capture](https://user-images.githubusercontent.com/4924999/53997284-db7d4d80-40f8-11e9-8476-d95fc9c2f405.PNG)

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
Does this happen to you for any two repos?

**Comment by jextrevor** [comment]
Yes, for any combination of repos. As long as it's a repo and it's in the
multiple repo view, clicking on the refresh button twice in a row causes VS
code to crash.

**Comment by joaomoreno** [comment]
Can you reproduce in the Insider release?

Can you reproduce with `code --disable-extensions`?

**Comment by jextrevor** [comment]
I have been able to reproduce it without extensions. I have not tried the
Insiders build yet—I will do that in the next few days.

**Comment by joaomoreno** [comment]
Let me know how it goes.

**Comment by jextrevor** [comment]
The Insiders build does not seem to have the same problem. 1.32.1 still has the problem though.

**Comment by jextrevor** [comment]
The problem seems to happen for any size repository that has a remote.

**Comment by joaomoreno** [comment]
How about that same version, but using a separate user data dir? `--user-data-dir`.

**Comment by jextrevor** [comment]
1.32.2 has the same problem, even with a separate user data dir.

**Comment by joaomoreno** [comment]
How big are your repositories?

**Comment by jextrevor** [comment]
This is happening with any size repository. I've tested with both big and
small repos.

>

**Comment by joaomoreno** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by jextrevor** [comment]
What the heck Microsoft? Are you expecting your users to do your debugging work? This issue is still not fixed, and I did the best I could with reporting information. The rest is up to you! Please don't close bugs just to close them!

**Comment by joaomoreno** [comment]
@jextrevor It's very hard to fix something which I can't reproduce on my side. If you want it fixed, please collaborate by going through the checklist. If you do so, we can maybe get to the bottom of this.

Also, considering that stable 1.33 is now out. Does it reproduce with that version?
