### ISSUE TITLE
When uploading blob .wasm files content type set to application/wasm rather then application/octet-stream

### ISSUE THREAD

**Issue by Lupusa87** [Microsoft/vscode#70001]
I do publish blazor apps on azure storage accounts from visual studio code using command - deploy to static website.

Uploaded .wasm file's content type is set to application/octet-stream.

Browser expects for .wasm files content type to be application/wasm, so we are forced to correct later content types using different ways, which is not convenient and requires extra time.

If it is possible please address this issue.

**Comment by joaomoreno** [comment]
What extension are you using to upload?

**Comment by Lupusa87** [comment]
This is azure storage.

![untitled3](https://user-images.githubusercontent.com/40779557/54044893-15ecf600-419e-11e9-8846-f31f028c8ed6.png)

It adds option - deploy to static website and uploads folder to selected storage account.

![untitled](https://user-images.githubusercontent.com/40779557/54044901-184f5000-419e-11e9-8e8a-1f705cadfc4c.png)

**Comment by joaomoreno** [comment]
/duplicate https://github.com/Microsoft/vscode-azurestorage/issues/325
