### ISSUE TITLE
Variable Substitution Relative Path

### ISSUE THREAD

**Issue by adstep** [Microsoft/vscode#7000]
The current set of Variable Substitution macros does not support the ability to access a relative path to the current opened file based off the cwd of the task. 

${workspaceRoot} the path of the folder opened in VS Code
${file} the current opened file
${fileBasename} the current opened file's basename
${fileDirname} the current opened file's dirname
${fileExtname} the current opened file's extension
${cwd} the task runner's current working directory on startup

**Comment by adstep** [comment]
I've played around with the code and think I can make a PR for this. Just wondering whether it would be better to surface:

${relDir}  path to the directory of the current opened file based off the cwd
or
${relFile} path to the current opened file based off the cwd

**Comment by adstep** [comment]
PR: https://github.com/Microsoft/vscode/pull/8982
Also added to the documentation here: https://github.com/Microsoft/vscode-docs/pull/464

**Comment by dbaeumer** [comment]
PR got merged a long time ago. Closing
