### ISSUE TITLE
Open Recent list is cleared after downgrading from 1.32

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70005]
After downgrading from 1.32 to 1.31.1 on macOS (I did that when verifying https://github.com/Microsoft/vscode/issues/69972), "Open Recent" shows an almost empty list. I'm sure I have opened more than 1 folders with it before:

![image](https://user-images.githubusercontent.com/4033249/54001018-af64cb00-40fe-11e9-9d16-0bc68baac69c.png)

**Comment by roblourens** [comment]
Note that this is downgrading from 1.32 to 1.31, and they aren't lost when opening 1.32 again, so probably not a big issue

**Comment by bpasero** [comment]
@aeschli possibly related to changes from you? Though I would expect that changes here are older than 1.32...

**Comment by aeschli** [comment]
We had a change in the storage format due to the workspace as URI change.
We only migrate forward, downgrading is not supported.
