### ISSUE TITLE
Ctrl + I does not work as "Select current line" after update to 1.32.1

### ISSUE THREAD

**Issue by Shsgear** [Microsoft/vscode#70012]
No response when i press Ctrl + I in coding panel.And I can't find "select current line" in keyboard shortcuts.json which describled in https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf.  Don't know where to set.Please can someone tell me?

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
avocode|avo|0.0.3
mapfile|chi|0.0.1
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.25.0
vscode-eslint|dba|1.8.1
es7-react-js-snippets|dsz|2.0.1
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
we-app-vscode|eme|0.8.0
json-tools|eri|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.7
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.9
vscode-power-mode|hoo|2.2.0
solidity-debugger|hos|0.2.1
rest-client|hum|0.21.2
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
solidity|Jua|0.0.49
react-native-snippet|jun|0.5.0
web3js-snippets|lem|0.2.1
vscode-filesize|mkx|2.1.2
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-language-pack-zh-hans|MS-|1.32.4
mssql|ms-|1.4.0
python|ms-|2019.2.5558
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
rxjs-snippets|pko|0.0.2
minapp-vscode|qiu|1.12.1
LiveServer|rit|5.5.1
vscode-icons|rob|8.2.0
code-settings-sync|Sha|3.2.7
code-bing|Sir|0.2.0
ejs-snippets|Tao|0.1.0
highlight-matching-tag|vin|0.8.6
vscode-react-native|vsm|0.8.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
markdown-all-in-one|yzh|2.1.1
vscode-ext-ontology|zam|1.5.3

(1 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_32

**Comment by tetchel** [comment]
it looks like they changed it to CTRL+L https://github.com/Microsoft/vscode/pull/67178/files

**Comment by Shsgear** [comment]
Thanks.I missed it.
