### ISSUE TITLE
Unexpected token E. Stopping the debug adapter

### ISSUE THREAD

**Issue by thomasgarai** [Microsoft/vscode#7001]
- VSCode Version: 1.1.1
  ====================>
  Commit def9e32467ad6e4f48787d38caf190acbfee5880
  Date 2016-05-13T13:38:00.094Z
  Shell 0.37.6
  Renderer 49.0.2623.75
  Node 5.10.0
- OS Version: Linux 3.16.0-72-generic [ubuntu 14.0.4 - trusty tahr]
  =============================>
# Steps to Reproduce:
1. prerequisites: 
   - install monocomplete
   - install vs code
   - run vs code in project folder [ example console app ]
   - modify launch.json file [ shown below ]
2. select mono as the active debug configuration
3. start debugging......
4. When a breakpoint is hit in code the following error is generated:
   Unexpected token E. Stopping the debug adapter
5. when vs code is exited the debug process still runs:

visual studio code debug console output:
===============================>
/usr/local/bin/mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55169 --debug ATF.exe

ps -ef yields the following:
====================>
ps -ef | grep mono
tg 14773 2250 0 10:02 ? 00:00:00 /usr/local/bin/mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55169 --debug ATF.exe

netstat -an shows socket still open
===========================>
$ netstat -an | grep 55169
tcp 0 0 127.0.0.1:55169 0.0.0.0:\* LISTEN
tcp 0 0 127.0.0.1:55169 127.0.0.1:44326 CLOSE_WAIT

The launch.json file:
{
"version": "0.2.0",
"configurations": [
{
"name": "mono",
"type": "mono",
"request":"launch",
"program": "${workspaceRoot}/bin/Debug/net40/ubuntu.14.04-x64/ATF.exe",
"runtimeExecutable": "/usr/local/bin/mono",
"runtimeArgs": ["--debug"]
},
{
"name": ".NET Core Launch (console)",
"type": "coreclr",
"request": "launch",
"preLaunchTask": "build",
"program": "${workspaceRoot}/bin/Debug/net40/ubuntu.14.04-x64/ATF.exe",
"args": [],
"cwd": "${workspaceRoot}",
"stopAtEntry": false
},
{
"name": ".NET Core Launch (web)",
"type": "coreclr",
"request": "launch",
"preLaunchTask": "build",
"program": "${workspaceRoot}/bin/Debug/net40/ubuntu.14.04-x64/ATF.exe",
"args": [],
"cwd": "${workspaceRoot}",
"stopAtEntry": false,
"launchBrowser": {
"enabled": false,
"args": "${auto-detect-url}",
"windows": {
"command": "cmd.exe",
"args": "/C start ${auto-detect-url}"
},
"osx": {
"command": "open"
},
"linux": {
"command": "xdg-open"
}
}
},
{
"name": ".NET Core Attach",
"type": "coreclr",
"request": "attach",
"processName": "ATF"
}
]
}

**Comment by ShadowIce** [comment]
I get the same error when I try to debug a C++ program on Windows using cppvsdbg, except that it's "Unexpected token C" and it's shortly after starting the program. I have a breakpoint set but it's not reached during that time. If I disable the breakpoint everything works.

**Comment by jacereda** [comment]
I deleted all breakpoints and still get the "Unexpected token C" error.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-mono-debug#25
