### ISSUE TITLE
Release Notes editor should handle file that starts with space then `#`

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#70011]
https://github.com/Microsoft/vscode/blob/release/1.32/src/vs/workbench/contrib/update/electron-browser/releaseNotesEditor.ts#L162

This line makes markdown like below invalid:

```

# February Release
```

Here's the fix I needed to do for release notes to show up: https://github.com/Microsoft/vscode-docs/commit/b0aa99b85d39a8510d472c7a14f693f590bcb3ac

The code should either trim beginning or change regex to handle whitespace in the beginning.

@rebornix FYI

**Comment by rebornix** [comment]
If we want to restrict the format of the content, we should have that in the CI of website/docs as well.
