### ISSUE TITLE
Close Button doesnot work

### ISSUE THREAD

**Issue by zmicx** [Microsoft/vscode#70018]
Issue Type: <b>Bug</b>

Click the Close button, the vscode doesnot close

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-project-generator|dan|1.1.1
gitlens|eam|9.5.1
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
unity-debug|Uni|2.7.2

</details>

**Comment by bpasero** [comment]
@zmicx can you be more specific? Maybe attach a screencast? Any errors in the log?

**Comment by zmicx** [comment]
@bpasero  There's no problem with updating vscode last Friday
