### ISSUE TITLE
some retracting problems

### ISSUE THREAD

**Issue by xxxxxxxyyyyyyy** [microsoft/vscode#70013]
Issue Type: <b>Bug</b>

hi there, first of all, sorry about my poor english , and your latest version has some retract issues.
seems like everytime i click "enter" to change the line and it will retract one more "tab" then before.
so i have to rollback to a older version to fix this problem.
btw , this feeling is awful.
hope you guys can fix this as fast as you can. 
thx.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (10.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
luaide|kan|0.7.5
vscode-quick-scope|ska|0.1.3
vim|vsc|1.1.0
vscode-proto3|zxh|0.2.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@xxxxxxxyyyyyyy sorry for coming back late. Could you please provide a reproduce step?
