### ISSUE TITLE
Smoke Test: implement a test that verifies hot exit restoration from stable to insiders

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70017]
With https://github.com/Microsoft/vscode/issues/69972 we have seen data loss because we are not testing hot-exit restoration from stable to insiders. We used to have a smoke test that would run against the data directory of a stable release to verify hot-exit is working properly (see https://github.com/Microsoft/vscode/blob/b263184/test/smoke/src/areas/workbench/data-migration.test.ts#L15) but this test was not ported over to our new smoke test architecture from @joaomoreno 

The test should be restored an:
* verify a dirty file that exists restores
* verify a dirty file that does not exist restores (untitled files)

**Comment by Tyriar** [comment]
I think the test was disabled originally in https://github.com/Microsoft/vscode/commit/c6cc8127bd0ef45fe756c23a703e1fd88f29effc as part of https://github.com/Microsoft/vscode/issues/58060. @joaomoreno @sandy081 any context here, it looks like we can no longer launch the stable version of the app from the tests now due to these refactors?

**Comment by sandy081** [comment]
This test was disabled [here](https://github.com/Microsoft/vscode/commit/3df5480a165eac0413921149f361ceda07c2f859#diff-ea36225e1b2b1aed77806e5528ec7d4b). This [commit](https://github.com/Microsoft/vscode/commit/c6cc8127bd0ef45fe756c23a703e1fd88f29effc) removed the test suite that does nothing.

**Comment by joaomoreno** [comment]
I commented this at the time with @bpasero. This test was running an insider after a stable, pointing to the same user data dir. It should rather be independent of stable vs insider. It should run on stable. And it should run on insider.

The test definition should be:

- Run a _previously released_ build, create a user data dir with it
- Run the build to be tested on the same user data dir

The test author and owner should better define what _previously released_ means. In stable, it makes sense: it's the previous minor version release. In insiders... I'm not so sure what it means.

**Comment by bpasero** [comment]
Well this test was never making any assumptions about stable vs insider. It was simply asking for 2 locations of full builds and then ran the one after the other.

**Comment by Tyriar** [comment]
We could also just hardcode some old stable version as well, that would probably be even better as we'll be certain it's using the correct paths.

**Comment by bpasero** [comment]
@Tyriar I think to get most out of this test is to test the actual update as it happens for most of our users, from version N-1 to N.

**Comment by bpasero** [comment]
I added the test back and it can be run as before via:

`yarn smoketest --build PATH_TO_BUILD --stable-build PATH_TO_STABLE_BUILD`

![before](https://user-images.githubusercontent.com/900690/54451739-cab18500-4753-11e9-995b-ead8f43669ff.gif)

**Comment by roblourens** [comment]
The test fails for `1.31 -> 1.32`, and passes for `1.31 -> 1.33` 🎉

**Comment by bpasero** [comment]
@roblourens thanks for verifying that 👍
