### ISSUE TITLE
Working directory status is missing

### ISSUE THREAD

**Issue by banguilin** [Microsoft/vscode#70016]
Issue Type: <b>Bug</b>

When using a network hard disk, vscode will not remember the working directory. After closing the directory, the settings about the directory will be lost, such as disabling the plugin settings, code breakpoints, code analysis cache, etc. are lost.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.26GB free)|
|Process Argv|Z:\web\magento2|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
vscode-intelephense-client|bme|1.0.8
ssh|chr|0.0.4
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|2.0.0
githistory|don|0.4.6
jquerysnippets|don|0.0.1
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.7.0
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.9
XMLLanguageSupport|IBM|0.0.1
Lua-Nginx-Snippets|jie|0.0.4
vscode-icon-theme|jtl|1.6.5
require-js|lic|0.1.23
rainbow-csv|mec|1.0.0
php-namespace-resolver|Meh|1.1.5
Angular-BeastCode|Mik|7.2.5
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
vscode-language-pack-zh-hans|MS-|1.31.4
debugger-for-chrome|msj|4.11.3
php-docblocker|nei|1.7.0
material-icon-theme|PKi|3.6.3
qub-xml-vscode|qub|1.2.8
background|sha|1.1.19
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.1.4
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
