### ISSUE TITLE
column select not working after recent update

### ISSUE THREAD

**Issue by psimek12** [Microsoft/vscode#70028]
- VSCode Version: 1.32.1 (system setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
Steps to Reproduce:

1. in any file try to reproduce column select as described in release notes
2. left mouse button click + mouse move -> normal selection
3. pressing Alt does nothing, no switch to column select

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@psimek12 did you configure `"editor.multiCursorModifier": "ctrlCmd"` ?
