### ISSUE TITLE
Duplicate symbol declaration 

### ISSUE THREAD

**Issue by elshobokshy** [Microsoft/vscode#70025]
- VSCode Version: 1.32.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

Say there's a code like the following : 

```
if(condition) {
    define('SOMETHING','value);
}
else {
    define('SOMETHING','value');
}
```

I get the error `Duplicate symbol declaration ` but they're not duplicates, as there's an if condition in between.

Does this issue occur when all extensions are disabled?: No

**Comment by bmewburn** [comment]
caused by extension https://github.com/bmewburn/vscode-intelephense/issues/320
