### ISSUE TITLE
More than one window open with duplicate tabs after auto-update

### ISSUE THREAD

**Issue by Simran-B** [Microsoft/vscode#70021]
- VSCode Version: 1.31.x
- OS Version: Windows 10

Steps to Reproduce:

- Unclear

See the full list of events: https://github.com/Microsoft/vscode/issues/69972#issuecomment-470824273

I observed multiple times that after an update on exit, when VS Code is started again by me, that it does not restore the last session properly. During the day, I had my "main" window with unsaved files/changes open all the time, and a second window with a workspace folder selected for short periods of time. The second window was long closed when I closed the main window. The automatic update started and I was interested in the changelog, so I restarted VS Code immediately.

What happened was that now two windows showed up, both with the changelog tabs, as well as the tabs from my previous session in both windows (although when this occurred yesterday, one window lacked one Untitled tab). This occurred only upon restart after an auto-update so far, but I remember that the changelog tab opened in multiple windows before, and sometimes again on the next restart.

Is there a way to fake auto-updates in order to attempt to reproduce this issue? It might not actually be related to the changelog tab, but something seems not right. If multiple windows are opened for some reason, with the same tabs in them with unsaved changes, it's unclear how to get of the situation without losing data (it seems like you can't close one of the windows without saving unsaved changes if you want to keep the changes, even though the remaining window will still have the dirty files, but not anymore on next restart).

**Comment by Simran-B** [comment]
The other issue does not mention the changelog tab, but I guess it can potentially open any tab twice?

**Comment by Tyriar** [comment]
@Simran-B pretty sure it's the same issue, the changelog will be there immediately after the update, but the underlying bug is that 2 windows are getting created incorrectly.
