### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by JSchiffmacher** [Microsoft/vscode#70023]
Issue Type: <b>Bug</b>

1/ Use special encoding such as CP437 
2/ Do a search

--> Red message : "Unknown encoding : cp437"

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (13.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
project-manager|ale|10.3.2
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
code-runner|for|0.9.7
FoxPro|Mat|0.0.1
vscode-perl|hen|1.17.0
vscode-git-add-and-commit|iva|2.0.4
git-indicators|lam|2.1.1
vscode-git-notify|mkl|0.4.2
vscode-language-pack-fr|MS-|1.32.4
indent-rainbow|ode|7.2.4
git-merger|sha|0.4.1
incremental-search|sie|0.2.1
selectline-statusbar|tom|0.0.2
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/68237
