### ISSUE TITLE
VSCode taskbar icon not present when run in WSL

### ISSUE THREAD

**Issue by amarchino** [Microsoft/vscode#70026]
- VSCode Version: 1.31.1
- OS Version: 1809 (OS Build 17763.348) - WSL: Ubuntu 18.04.2 LTS

Starting with the 1.31.1 (February recovery), when I start VSCode in WSL and switch around with other apps, it disappears from the Windows taskbar.
I know it is a non-standard use case, but it worked almost flawlessly up until version 1.31.0.

Steps to Reproduce:

1. Start VcXsrv in MultiWindow mode
2. Start dbus on WSL ( `sudo /etc/init.d/dbus start &> /dev/null` )
3. Enable X client ( `LIBGL_ALWAYS_INDIRECT=1`, `DISPLAY=0:0` )
4. Run `code` from wsl
5. Move around other windows (alas, I cannot be more specific, Sometimes it happens by itself when i iconize the application, other times when I switch to other apps, once or multiple times)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/50795
