### ISSUE TITLE
全屏上侧漏白条

### ISSUE THREAD

**Issue by wells-x** [Microsoft/vscode#70034]
Issue Type: <b>Bug</b>

全屏，退出全屏，再全屏

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sublime-importer|auc|1.0.1
xtemplate|bak|0.2.6
vscode-eslint|dba|1.8.1
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.9
comment-translate|int|1.0.0
vscode-language-pack-zh-hans|MS-|1.32.4
mssql|ms-|1.4.0
vetur|oct|0.16.2
templex|sle|0.1.1

</details>

**Comment by sbatten** [comment]
I can not reproduce with the above steps. Can you provide more information?

**Comment by wells-x** [comment]
最大化窗口的时候，每两次最大化时 会出现一次
问题描述： 窗口最大化时，最上方会出现白条以及50px左右空隙，
![问题截图](https://user-images.githubusercontent.com/23162260/54592929-5125d980-4a68-11e9-8456-f025687e26de.png)

**Comment by wells-x** [comment]
It is disappear after windows updated
