### ISSUE TITLE
Support CompletionItem textEdit that spans multiple lines

### ISSUE THREAD

**Issue by olafurpg** [Microsoft/vscode#70037]
The LSP specification on `CompletionItem.textEdit` mentions the following restriction: 

> *Note:* The range of the edit must be a single line range and it must contain the position at which completion has been requested.

Is there a fundamental reason for this restriction or could it be lifted?

I'm writing a language server I would like to implement a completion like this (observe the inserted `s` at the start of the string literal).

![2019-03-08 10 44 57](https://user-images.githubusercontent.com/1408093/54020915-4711fa00-418f-11e9-8886-563c535eacad.gif)

I already have it working for single-line string literals using a `textEdit` that spans the range of the string literal:

![2019-03-08 10 49 45](https://user-images.githubusercontent.com/1408093/54021219-ecc56900-418f-11e9-8c01-33d3f72fe634.gif)

However, completion items from the server are filtered out for multi-line string literals

![screenshot 2019-03-08 at 10 51 41](https://user-images.githubusercontent.com/1408093/54021331-2e561400-4190-11e9-8dfd-4c8798608ea5.png)

Here is the raw JSON for the completion item that is filtered out (observe that filter text contains `\n` and the text edit spans multiple lines):
```json
{
        "label": "name",
        "kind": 12,
        "detail": ": String",
        "filterText": "\"\"\"\n      |Hello $name",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 4,
              "character": 4
            },
            "end": {
              "line": 6,
              "character": 2
            }
          },
          "newText": "s\"\"\"\n      |Hello \\$name$0\n      |\"\"\""
        }
      }
```

(sidenote: the filter text needs to include the full prefix of the string literal for the single-line case to work, it doesn't work with an empty filter text or `"$name"`).

I tried using `additionalTextEdits` and got it working but it was not ideal because it requires multiple edits surrounding the completion position:
- escape existing `$` characters inside the string literal to `$$`
- wrap the completed name in curly braces: `"Hello nam<TAB>_" becomes `s"Hello ${name}_"

It is cleaner to provide a single `TextEdit` that transforms the entire string literal, it works great for a single-line strings.

**Comment by olafurpg** [comment]
Related discussion in https://github.com/Microsoft/language-server-protocol/issues/92

**Comment by jrieken** [comment]
We enforce this to keep the "main" edit smallish so that chance is reduced to have issues with multiple cursors, e.g. to support multiple cursors without extension authors thinking much about it. I am unsure if I understood your arguments for not using additional text edits

**Comment by olafurpg** [comment]
Thanks for the explanation! My main argument against additional edits was that it's trickier to implement and the "main edit must be on single line" restriction felt arbitrary. It makes sense that fine-grained additional edits lower the risk of potential conflicts and are a suitable workaround :)
