### ISSUE TITLE
Markdown: cs not being highlighted, csharp is

### ISSUE THREAD

**Issue by jamesqo** [Microsoft/vscode#7003]
- VSCode Version: 1.1.1
- OS Version: Windows 10.0.10586 x64

When editing a markdown (`.md`) file, this is not getting syntax highlighted:

\`\`\`cs
using System;

Console.WriteLine("Hello, world!");
\`\`\`

but this is:

\`\`\`csharp
using System;

Console.WriteLine("Hello, world!");
\`\`\`

Yet, they're both highlighted on GitHub:

```cs
using System;

Console.WriteLine("Hello, world!");
```

```csharp
using System;

Console.WriteLine("Hello, world!");
```

**Comment by mjbvz** [comment]
This looks like it has been fixed, perhaps by #7014

![screen shot 2016-09-14 at 6 22 24 pm](https://cloud.githubusercontent.com/assets/12821956/18535328/327f7d70-7aa8-11e6-8664-a003c4b66f52.png)

**Comment by jamesqo** [comment]
@mjbvz I meant while you were editing the markdown (in the `bla.md` tab), not in the preview view. I closed that PR btw.

**Comment by mjbvz** [comment]
@jamesqo Thanks for the clarification. In that case, it looks like neither `csharp` or `cs` is being properly highlighted. I'll look at adding a simple rule to the markdown grammar to match C# code blocks.
