### ISSUE TITLE
Can't report bug if not logged into Gitlab

### ISSUE THREAD

**Issue by jimbomorrison** [Microsoft/vscode#70030]
Issue Type: <b>Bug</b>

1. Go to gitlab.com and sign out.
2. Go to MSVSC and use the Issue Reporter tool.
3. Hit "Preview on GitHub"
4. Admire the GitHub 500 page.

NB - not sure if this is a malformed URL issue causing a problem with the login-redirect or a github.com issue.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
vscode-eslint|dba|1.8.1
vscode-html-css|ecm|0.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
mysql-syntax|jak|1.3.1
vue|liu|0.1.5
php-docblocker|nei|1.7.0
vetur|oct|0.16.2
php-formatter|Sop|0.2.4

</details>

**Comment by connorshea** [comment]
Is the extension you're reporting an issue with on GitHub or GitLab? Or is it supposed to be an issue for VSCode itself? What URL are you being sent to that gets you a 500? GitLab.com shouldn't be relevant to this at all.

If you mean logging out of Git**Hub**, that's probably expected behavior.

**Comment by jimbomorrison** [comment]
Git**Hub** - sorry.  gitlab was a musclememory-typo.

Returning to gather a link to provide you to demonstrate the problem it now appears to be working as expected so I can only assume this was a temporary GitHub issue.  

I did test some other scenarios at the time that would trigger the `login?return_to=` model and they were working fine... and posting from VSCode was failing consistently... but no more.  

For not I will close this issue as it's probably a waste of everyone's time.

Link, for reference:

```
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode%2Fissues%2Fnew%3Ftitle%3DTest%26body%3D%250AIssue%2520Type%253A%2520%253Cb%253EBug%253C%252Fb%253E%250A%250AThis%2520is%2520a%2520test%250A%250AVS%2520Code%2520version%253A%2520Code%25201.31.1%2520%281b8e8302e405050205e69b59abb3559592bb9e60%252C%25202019-02-12T02%253A16%253A38.656Z%29%250AOS%2520version%253A%2520Darwin%2520x64%252018.0.0%250A%250A%253Cdetails%253E%250A%253Csummary%253ESystem%2520Info%253C%252Fsummary%253E%250A%250A%257CItem%257CValue%257C%250A%257C---%257C---%257C%250A%257CCPUs%257CIntel%28R%29%2520Core%28TM%29%2520m5-6Y54%2520CPU%2520%2540%25201.10GHz%2520%284%2520x%25201200%29%257C%250A%257CGPU%2520Status%257C2d_canvas%253A%2520enabled%253Cbr%253Echecker_imaging%253A%2520disabled_off%253Cbr%253Eflash_3d%253A%2520enabled%253Cbr%253Eflash_stage3d%253A%2520enabled%253Cbr%253Eflash_stage3d_baseline%253A%2520enabled%253Cbr%253Egpu_compositing%253A%2520enabled%253Cbr%253Emultiple_raster_threads%253A%2520enabled_on%253Cbr%253Enative_gpu_memory_buffers%253A%2520enabled%253Cbr%253Erasterization%253A%2520unavailable_off%253Cbr%253Esurface_synchronization%253A%2520enabled_on%253Cbr%253Evideo_decode%253A%2520enabled%253Cbr%253Ewebgl%253A%2520enabled%253Cbr%253Ewebgl2%253A%2520enabled%257C%250A%257CLoad%2520%28avg%29%257C11%252C%252013%252C%25208%257C%250A%257CMemory%2520%28System%29%257C8.00GB%2520%280.14GB%2520free%29%257C%250A%257CProcess%2520Argv%257C%257C%250A%257CScreen%2520Reader%257Cno%257C%250A%257CVM%257C0%2525%257C%250A%250A%253C%252Fdetails%253E%253Cdetails%253E%253Csummary%253EExtensions%2520%285%29%253C%252Fsummary%253E%250A%250AExtension%257CAuthor%2520%28truncated%29%257CVersion%250A---%257C---%257C---%250Avscode-eslint%257Cdba%257C1.8.0%250Aphp-debug%257Cfel%257C1.12.6%250Aphp-intellisense%257Cfel%257C2.3.10%250Aphp-pack%257Cfel%257C1.0.2%250Aphp-formatter%257CSop%257C0.2.4%250A%250A%250A%253C%252Fdetails%253E%250A%253C%21--%2520generated%2520by%2520issue%2520reporter%2520--%253E
```
