### ISSUE TITLE
更新丢失了数据

### ISSUE THREAD

**Issue by RMzcq** [Microsoft/vscode#70031]
- VSCode Version: 版本 1.32.1 (1.32.1)
- OS Version: 版本 1.32.0 (1.32.0)

Steps to Reproduce:

1.有两个未保存的文件，更新后，然后restart，等了一会没启动，我就点了图标，然后两个文件是打开状态，但是没有内容了！！！你们怎么这样。
2.告诉我怎么找回或者解决问题！！！

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMzcq** [comment]
mac system

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/70006

**Comment by binaryer** [comment]
一样遇到了这个问题，重要笔记丢失无法找回
