### ISSUE TITLE
VS Code 1.32 no longer has nice custom titel bar, but goes back to ancient ugly system menu bar.

### ISSUE THREAD

**Issue by autarchprinceps** [Microsoft/vscode#70048]
- VSCode Version: 1.32.0
- OS Version: Linux (Amazon Linux 2)

Steps to Reproduce:

1. Update from 1.31
2. Start VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by autarchprinceps** [comment]
![code new](https://user-images.githubusercontent.com/239063/54028666-19847b00-41a6-11e9-91e0-0a0ae9a412a1.png)
![code old](https://user-images.githubusercontent.com/239063/54028667-19847b00-41a6-11e9-860b-f306ad081203.png)

**Comment by leopiccionia** [comment]
The default was changed in 1.32 release ([see notes](https://code.visualstudio.com/updates/v1_32#_default-title-bar-style-on-linux)).

To return to previous behavior, change `window.titleBarStyle` settings option to `custom`.

**Comment by autarchprinceps** [comment]
No idea why you would bring back that old stuff again, but if I can disable it, fine.
