### ISSUE TITLE
Network drive: High CPU usage after wake from hibernation

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#70046]
This is a repost of https://github.com/Microsoft/vscode/issues/68963, that was closed prematurely: 

Issue Type: <b>Bug</b>

When I hibernate my computer and then wake it up again, with code running, after the wake there is a high CPU usage in the code process cluster.

```
Version:          Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.87GB (5.71GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       96   15524  code main
    0       84    8460     gpu-process
   29      249   12776     window (ReportController.pm Z:\ReportController.pm - xxx - Visual Studio Code)
   10     1278   14664       extensionHost
    0       11   16984       watcherService
    0        9    3256         console-window-host (Windows internal process)
    0       72   15780     shared-process
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
vscode-django|bat|0.19.0
vscode-bad-code-highlighter|bha|0.1.6
unique-lines|bib|1.0.0
featurehighlight|Blo|1.7.0
bracket-pair-colorizer|Coe|1.0.61
jupyter|don|1.1.4
find-related|eam|0.8.0
sort-lines-by-selection|ear|0.0.3
php-intellisense|fel|2.3.10
gc-excelviewer|Gra|2.1.29
dupchecker|jia|0.0.9
vscode-random|jre|1.5.0
MagicPython|mag|1.1.0
id-generator|mat|1.0.0
xml-format|mik|1.0.1
vscode-duplicate|mrm|1.2.1
oracle-plsql|myc|1.0.3
indent-rainbow|ode|7.2.4
selectline-statusbar|tom|0.0.2
vscodeintellicode|Vis|1.1.3
gitblame|wad|2.6.3
twig|wha|1.0.2
jinja|who|0.0.8
cursor-align|yo1|1.0.4

</details>

**Comment by PunchyRascal** [comment]
Confirmed on this version, too:

Version: 1.32.1 (system setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@PunchyRascal can you isolate which process is spinning high?

**Comment by PunchyRascal** [comment]
I thought it was shown in the status output in the first comment. Or can I do something else?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by PunchyRascal** [comment]
I am having some trouble running the status on insiders code (` '.\Code - Insiders.exe' --status` throws error), but the constant CPU usage is still there.

**Comment by PunchyRascal** [comment]
```
code-insiders : The term 'code-insiders' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ code-insiders --status
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (code-insiders:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by bpasero** [comment]
@PunchyRascal did you install VSCode insiders with the installer? Maybe restart?

**Comment by PunchyRascal** [comment]
Well, somehow powershell when using autocomplete prepended it with `&` and it worked (` & '.\Code - Insiders.exe' --status`):

```

Version:          Code - Insiders 1.33.0-insider (c1d001a915fe85cac93492393ea69fdb0c49ec0d, 2019-03-13T06:18:20.237Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  15.87GB (6.26GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    7       78   13360  code-insiders main
    0       64    8040     shared-process
    0       95   13112     gpu-process
   16      217   17984     window (jobs.data - xxx- Visual Studio Code - Insiders)
    0       11   10244       watcherService
    0       10   10776         console-window-host (Windows internal process)
    0       61   16304       extensionHost

```

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by PunchyRascal** [comment]
I tried it before without extensions on a production code - without any change. 

However my insiders code has no extensions installed anyway.

**Comment by bpasero** [comment]
Ok, sorry I am out of ideas what this could be. The renderer process seems to spike for no apparent reason.

**Comment by richdelaney** [comment]
I am having the same issue. I've bound workbench.action.reloadWindow to ctrl+f5, and need to press this every time I come back form hibernate to make my system usable again. I hibernate frequently on my laptop.

**Comment by jtackaberry** [comment]
Out of curiosity, for those who have this problem, do you have open windows on CIFS shares?

I have this issue too and can reproduce it reliably.  Reloading the window is a quick workaround so I've not been too fussed about it.  But I noticed today Code wasn't burning CPU on wake, and the difference is that the active project I had open was referencing local files, whereas previously my active project was on CIFS.

This seems to be reproducible.

1. Close current workspace
2. Open a single file on CIFS
3. Sleep system
4. Wake system
5. After a moment, Code burns 100% of a core

If I swap step 2 for opening a local file rather than CIFS the problem doesn't occur.

Do the other folks suffering from this bug experience the same?

**Comment by richdelaney** [comment]
> Out of curiosity, for those who have this problem, do you have open editors on CIFS shares?

I wondered if file shares could be triggering the issue too. I almost always have tabs open in VSCode to files from a Win-SSHFS mount. Those shares become unavailable upon returning from hyphenate; so I later remount them. Even after remounting CPU utilization remains high (until I run workbench.action.reloadWindow).

A spot check reveals that CPU does not increase upon returning form hibernate when tabs are open to local files. However to check this, I did need to close all my tabs, each having: undo history, different file types (likely triggering different code paths in the extensions), sometimes not backed by files (e.g. Untitled), ect; so my restart of VSCode was also missing lots of other accumulated state, which may also be the trigger.

**Comment by jtackaberry** [comment]
> so my restart of VSCode was also missing lots of other accumulated state, which may also be the trigger.

I was able to reproduce it with a fresh window (no prior state) with a single file open on a CIFS share.  Could you try that case as well with the sshfs mount and see if the problem returns?

**Comment by PunchyRascal** [comment]
With only local files open I do not see any CPU usage at all. So it seems this is the problem. Most of the time I have a samba-share-mounted-as-a-drive folder open in code.

**Comment by richdelaney** [comment]
>I was able to reproduce it with a fresh window (no prior state) with a single file open on a CIFS share. Could you try that case as well with the sshfs mount and see if the problem returns?

Good idea. I tried what you suggested. Simply opening a file mounted on a Win-SSHFS share, then hibernating, and returning form hibernate triggered the increased CPU utilization.

I've noticed that recently VSCode will close tabs for files on the remote shares sometimes upon returning from hibernate, but not always; I'm not sure why this happens sometimes but not others. This time it closed the tab (while exhibiting the symptom of increased CPU utilization).

Leaving that tab closed, then hibernating, and returning form hibernate, did not re-trigger the issue.

**Comment by jtackaberry** [comment]
@bpasero I think we've converged on the root cause.  Do you feel this issue still needs more info?

**Comment by bpasero** [comment]
@jtackaberry is there an easy way for me to reproduce this scenario with the CIFS share? I am not even sure what that is.

Besides I feel like this issue is unrelated to code in VSCode but could rather be an upstream issue in node.js or electron which would mean we need a reproducible case for those projects and report the issue to them.

**Comment by PunchyRascal** [comment]
Like I said, same thing with a regular samba share mounted as a network
drive.

**Comment by bpasero** [comment]
Ok, I am unfortunately not having a lot of time to investigate this, but I am adding the help wanted label if someone wants to chime in and analyses further. I believe at this point the only option forward is to add a native profiler to the process to really understand where the CPU spike is originating from.

**Comment by richdelaney** [comment]
Please reopen. This is still occurring, and does not require more information.

**Comment by hickninja** [comment]
Yes, please reopen. This happens to me daily, and there are easy repro instructions on this thread. It does not need more information, and is still a bug.

**Comment by alienriver49** [comment]
This seems like the same issue as [#70566](https://github.com/Microsoft/vscode/issues/70566) which looks to have been fixed in the latest insider's build (which should be available in the stable build any day now, yay!).
