### ISSUE TITLE
[css/scss/less] require a space after : to trigger intellisense

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7004]
Steps to Reproduce:

1. Create a selector
2. Type `width:a`, notice no intellisense

![image](https://cloud.githubusercontent.com/assets/2193314/15630919/8c60276c-2504-11e6-8c5c-34fa849b0ab8.png)

**Comment by aeschli** [comment]
Proposals are filtered out again as the word rule includes the ':'
