### ISSUE TITLE
Can't execute new scripts

### ISSUE THREAD

**Issue by nitrocube** [Microsoft/vscode#70043]
- VSCode Version:1.32
- OS Version: Windows 10

When I open visual code, I can execute my program, but if I add something, the program will run, like if I hadn't changed anything. It's a big problem because I can't do anything.

(node.js)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Are you running your program via Debug, Tasks or Terminal?

**Comment by nitrocube** [comment]
> Are you running your program via Debug, Tasks or Terminal?

debug I think, with F5

**Comment by weinand** [comment]
Please provide steps that explain what you are trying to do.

**Comment by nitrocube** [comment]
I have my program in node js, I add something, like "  if (message.content === ... ){scripts}  "
the I press F5
the program (all, not the if) will work well, but like if the if and his script never existed

**Comment by weinand** [comment]
How does your launch config look like?
