### ISSUE TITLE
Node-Debug not auto attaching debugger to subprocesses on OSX.

### ISSUE THREAD

**Issue by sakiv** [Microsoft/vscode#70052]
- VSCode Version: 1.32.1
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Create sample node program to spawn multiple child processes.
2. Create launch config with autoAttachChildProcesses to true
3. Start to debug application

Does this issue occur when all extensions are disabled?: Yes/No
`code --disable-extensions`
Above command is not working. It opens VS Code with a new file named as "--disable-extensions".

Sample code using from https://github.com/Microsoft/vscode/issues/45320#issuecomment-371642189

Here is launch.json

`
{
  "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/test.js",
            "autoAttachChildProcesses": true
        }
    ]
}
`

**Comment by dmail** [comment]
Got same issue

**Comment by bunuelcubosoto** [comment]
Got the same issue after updating Code to 1.32.1
