### ISSUE TITLE
settings appears as a json file not GUI after update to version 1.32.1

### ISSUE THREAD

**Issue by engmagdy87** [Microsoft/vscode#70056]
settings appears as a json file not GUI after update to version 1.32.1
Version: 1.32.1 (system setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

![2019-03-08_15-31-03](https://user-images.githubusercontent.com/8473421/54031396-4ab97700-41b7-11e9-9dd1-488b0786a742.gif)

**Comment by shiftgeist** [comment]
The problem doesn't occur to me.

Could you output your setting of `workbench.settings.editor` for me?

**Comment by engmagdy87** [comment]
{
  "workbench.colorTheme": "Material Theme Ocean",
  "editor.formatOnSave": true,
  "window.zoomLevel": -1,
  "editor.fontSize": 16,
  "window.menuBarVisibility": "toggle",
  "workbench.startupEditor": "newUntitledFile",
  "eslint.alwaysShowStatus": true,
  "eslint.autoFixOnSave": true,
  "workbench.colorCustomizations": {
    "tab.hoverBackground": "#0f4b5f",
    "tab.activeBackground": "#045ad0"
  },
  "workbench.iconTheme": "material-icon-theme",
  // Command Prompt
  // "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
  // PowerShell
  // "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  // Git Bash
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "terminal.integrated.cwd": "C:\\Program Files\\Git\\etc\\ssh",
  "path-intellisense.mappings": {
    "/": "${workspaceRoot}",
    "src": "${workspaceRoot}/src"
  },
  "typescript.quickSuggestionsForPaths": true,
  "files.eol": "\n",
  "editor.find.autoFindInSelection": true,
  "editor.multiCursorModifier": "ctrlCmd",
  "sync.gist": "83d2cb117ac378b9c57551ce3d632476",
  "sync.lastUpload": "2018-04-20T21:49:39.964Z",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "",
  "sync.forceDownload": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "dart.flutterHotReloadOnSave": true,
  "files.autoSave": "off",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "materialTheme.fixIconsRunning": false,
  "terminal.integrated.rendererType": "dom",
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "javascript.implicitProjectConfig.checkJs": true,
  "breadcrumbs.enabled": false,
  "editor.formatOnPaste": true,
  "editor.formatOnType": false,
  "diffEditor.ignoreTrimWhitespace": false,
  "workbench.view.alwaysShowHeaderActions": true,
  "workbench.settings.editor": "json",
  "editor.wordWrap": "on",
  "editor.wrappingIndent": "indent",
  "editor.renderLineHighlight": "all",
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.cursorStyle": "line",
  "javascript.preferences.importModuleSpecifier": "non-relative",
  "typescript.preferences.importModuleSpecifier": "non-relative",
  "workbench.sideBar.location": "left",
  "workbench.statusBar.visible": true,
  "workbench.activityBar.visible": true,
  "editor.minimap.enabled": true,
  "editor.renderWhitespace": "none",
  "editor.renderControlCharacters": false,
  "editor.wordWrapColumn": 80,
  "[markdown]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": true
  },
  "window.titleBarStyle": "custom",
  "editor.tabCompletion": "on",
  "editor.largeFileOptimizations": true,
  "editor.cursorSmoothCaretAnimation": true,
  "editor.quickSuggestions": {
    "strings": true
  }
}

**Comment by shiftgeist** [comment]
You have `"workbench.settings.editor": "json"` in your settings -> Thats why it shows you the

Search for string `workbench.settings.editor` in the settings:
![settings-ui](https://user-images.githubusercontent.com/30648730/54073053-fbd91380-4282-11e9-823a-4456be69b5ca.gif)

**Comment by engmagdy87** [comment]
thx @shiftgeist solved
