### ISSUE TITLE
Breakpoints do not get hit work with while debugging react native app

### ISSUE THREAD

**Issue by MarcoLLeite** [Microsoft/vscode#70054]
The debugger seems to work and connect, but I never get a hit on any breakpoints.
This started to happen when I installed the version 1.31.1 more then a week ago. Installing the latest version 1.32.1 does not seem to fix this issue either.
I am not sure if this is directly related to any version as installing previous version does not seem to fix the issue.

Before that it used to work perfectly on both android emulators and android devices. Now it happens while debugging both android emulators and actual devices.

Any suggestions? Ideas?

**Comment by roblourens** [comment]
Please file this on the react native extension
