### ISSUE TITLE
On Progress SnackBar [on bottomright] is not visible & Flutter Auto Hot reload is not working after 1.32

### ISSUE THREAD

**Issue by rajeshjeshar** [Microsoft/vscode#70057]
Issue Type: <b>Bug</b>

Run a Flutter or Android Project,it should show "Building grade Files.." ,"Installing Application...","Syncing files to the device.."

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
bloc|Fel|0.1.3
kotlin|fwc|0.1.13
Kotlin|mat|1.7.0
java|red|0.40.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.15.0

(1 theme extensions excluded)

</details>

**Comment by kabyanil** [comment]
I am having the same problem. Hot reload(used to get triggered automatically on save) and Hot restart(ctrl+f5) is not working. It was working all fine till last night. This morning my vs code got auto updated and since then, running on this issue. Flutter development has been very painful with this!

**Comment by kabyanil** [comment]
If anyone else is having the same problem, a temporary workaround would be to use flutter run in combination with "r" for hot reload and "R" for hot restart, until vs code gets the issue fixed!

**Comment by weinand** [comment]
@isidorn was there a regression with keyboard shortcuts?

**Comment by isidorn** [comment]
@weinand no, as far as I know.
@rajeshjeshar please file this against your extension, they can investigate what is going on and then they can report back to us
fyi @DanTup to check if we broke something on the vscode side

**Comment by DanTup** [comment]
Yep, this is a dupe of #69534 / https://github.com/Dart-Code/Dart-Code/issues/1518 and is fixed in the Insiders build that was pushed just now 👍

**Comment by isidorn** [comment]
Great, we will also include this in the recovery stable build.

**Comment by DanTup** [comment]
(for those subscribed here, v1.32.2 of VS Code is live and contains the fix)
