### ISSUE TITLE
Terminal starts blank

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#70051]
Issue Type: <b>Bug</b>

When I open a terminal pane for the first time, it starts "blank" which it turns out is just scrolled down. When I scroll up, there's the prompt. But then, when I enter any character on the keyboard, it scrolls back down and the entered character appears in the middle of nowhere. When I scroll up yet again, it turns out the character I entered is now 3 lines down from the command prompt, but in the correct column.

This repeats for every entered character.

The workaround I've found so far, is to press Enter right after opening a terminal pane for the first time. This sort of "resets" the prompt, I guess, and allows normal input.

This problem occurs with all extensions disabled as well.
Issue #46078 appears to be similar, but its description suggests a different problem. I *can* enter commands, they just mess up the terminal visually.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (19.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.2.2
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.9
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.7
vscode-svg-previewer|vit|0.5.0

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by thany** [comment]
@Tyriar Websites tend to fix/workaround browser bugs, so application oughta workaround OS bugs.

Having said that, VScode is from Microsoft, and Windows is from Microsoft, so can you please work it out internally? Just walk over to the Windows dev team, I'm sure they are reasonable people ;)

**Comment by Tyriar** [comment]
@thany I tried to get the fix into Windows 10 1809 but it did not meet the severity bar. Also there is no workaround I can do on my side that wouldn't introduce instability elsewhere. I'm not particularly happy with how things turned out either or the fact that I'm getting daily issue reports on this for months.
