### ISSUE TITLE
Hot Restart not working with flutter

### ISSUE THREAD

**Issue by diver2** [Microsoft/vscode#70059]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.1)
[✓] Connected device (1 available)

Steps to Reproduce:

1. start debugging - F5 / CTRL-F5
2. hot reload = COMM SHIFT f5 = ok
3. hot restart = CTRL-F5 = NOTHING... 
This is critical... I did not update my vscode, it updated itself... I'm trying to get back to some previous version when it worked... annoying loss of time in a critical day for me...

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by diver2** [comment]
just to complement, I'm trying it in different code... and in the simplest code it doesn't work...
flutter ext = 2.24 / dart ext = 2.24

**Comment by diver2** [comment]
Another info - I went to settings, Dart: flutter debug restart behavior - there I can change the settings between hot reload/hot restart.
Now everytime I do a hot restart (I don't have hot reload anymore)...
and the COMM SHIFT F5 is hooked to hot restart (not hot reload)

**Comment by diver2** [comment]
for info as well - saving a file doesn't trigger hot reload/restart anymore

**Comment by diver2** [comment]
I just stopped using vscode - back to android studio. As simple as that.

**Comment by diver2** [comment]
@weinand I am a coder/entrepreneur. I am surprised by your reply.
I find it unbelievable that you could update vscode and not talk to the flutter team - to do a regression on their extension. At least on BASIC features (hot reload/restart is one of them). 
This shows me that vscode team (Microsoft) does not care about flutter. Ok. Message taken. Back to Android Studio with no regrets.

**Comment by weinand** [comment]
@diver2 I did not reply. That was a bot...

All your steps in your first comment are Flutter specific. VS Code has no concept of "Hot Restart". How should I investigate this? I'm not a Flutter expert. I do not even have Flutter installed (and learning to set up each and every extension out there is not a good use of my time).

Typically extension issues are filed against the extension first. If the extension author thinks it is a VS Code issue, he will let us know and we will investigate.

**Comment by diver2** [comment]
@weinand You missed my point... 
I find it bad that MS does not do a regression on major extensions, and coordinate with those before an udpdate
My definition of major extensions include flutter. Maybe yours (MS) doesn't. And that's when I recognized that I should go back to Google (who has 100% interest in flutter)
