### ISSUE TITLE
"Restart  to Update..." should not use an ellipsis

### ISSUE THREAD

**Issue by bersbersbers** [Microsoft/vscode#70058]
Issue Type: <b>Bug</b>

According to the Windows Dev Center:

> While menu commands are used for immediate actions, more information might be needed to perform the action. Indicate a command that **needs additional information (including a confirmation)** by adding an ellipsis at the end of the label.
https://docs.microsoft.com/en-us/windows/desktop/uxguide/cmd-menus#using-ellipses

As I have had to painfully learn, "Restart  to Update..." does not need additional information, and certainly no confirmation - not even when in the middle of a debugging process. Therefore, "Restart  to Update..." should become "Restart  to Update" to prevent the false indication of a confirmation.

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (32 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.86GB (160.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|6.1.0
svn-scm|joh|1.47.1
python|ms-|2019.2.5558
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.2.7

</details>

**Comment by alexr00** [comment]
It's still there: 
![image](https://user-images.githubusercontent.com/38270282/55091508-3d562500-50b1-11e9-8426-8d0f085fbd60.png)
