### ISSUE TITLE
Sass syntax highlighting is poor for incomplete rules

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7005]
CSS works much better currently.

Sass:

![image](https://cloud.githubusercontent.com/assets/2193314/15630920/b7ce7ee4-2504-11e6-93dd-f0a1abaadad3.png)

CSS:

![image](https://cloud.githubusercontent.com/assets/2193314/15630922/c5d1b6e6-2504-11e6-8957-efb155e9ac9f.png)

**Comment by aeschli** [comment]
Sass supports nested rules. width:aut can be the selector (with pseudo class). That's why it is highlighted orange(ish). Once you set the semicolon or add a space behind the colon, it is clear that it is a rule and will be colorised accordingly.
