### ISSUE TITLE
Settings UI focus jumps to next control

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#70063]
Version: 1.32.0-insider
Commit: 43228c493069ead7cfb7d57b2da1db20fc0acdaf
Date: 2019-03-06T01:22:34.867Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic\

- open settings UI, enter 'themes'
- open the combo box for color themes, select an entry
- open the combo box for color themes again, move the mouse a bit. Drop down switches to next control.

![settings](https://user-images.githubusercontent.com/6461412/54033680-412f0f80-41b5-11e9-9721-6954c6284f2f.gif)

**Comment by roblourens** [comment]
This should be fixed in the latest insiders, please update
