### ISSUE TITLE
auto import from index files appends 'index' to the filepath

### ISSUE THREAD

**Issue by zbeyens** [Microsoft/vscode#70061]
- VSCode Version: 1.32.1
- OS Version: Windows 10

Steps to Reproduce:

1. in `src/config/index.js`: `export const a = 1;`
2. auto import gives `import { a } from 'config/index';`

Does this issue occur when all extensions are disabled?: Yes

My `jsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ES6",
    "baseUrl": "./src"
  },
  "exclude": ["node_modules", "build"]
}
```

**Comment by feelextra** [comment]
Why is this an issue? the imported module's file name is `index.js`.
The only missing part in `config/index` is the extension name:  `config/index.js`

**Comment by mjbvz** [comment]
In your `jsconfig`, try setting: 

```json
        "module": "commonjs"
```
