### ISSUE TITLE
CSS snippets shouldn't display in rule value intellisense

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7006]
![image](https://cloud.githubusercontent.com/assets/2193314/15630949/d0647746-2505-11e6-86f1-a78d92e6d945.png)

**Comment by aeschli** [comment]
@Tyriar You can also write a snippet for rule values. Snippets have no limitations.

But yes, the snippet experience is an unhappy one, theres many possible ways of looking at it:
- need more context on snippets, so they only show when suited. Sounds easy, but difficult to implement as it needs language server smarts, or text mate scope dependecies which I'm sceptical that they will really help, especially in scenarios like the one above. Also, we will still have to support templates that have no context and we have to show everywhere.
- separate snippets out of code completions, hide them better, sort them differently (see #2343)...

**Comment by aeschli** [comment]
Closing. There are currently no restrictions on what snippets are for.
