### ISSUE TITLE
User keyboard shortcuts no longer available for editing

### ISSUE THREAD

**Issue by Gooseman** [Microsoft/vscode#70078]
- VSCode Version: 1.32.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code
2. Open keyboard shortcuts

Previously it was possible to edit user keyboard shortcuts directly in VSCode by opening the keyboard shortcuts and selecting to view all shortcuts, which opened the json files side by side.  That's been removed for some reason.

That's made doubly annoying by the fact that not all default shortcuts exist anymore.  Ctrl+I used to expand the selection by a line.  Now it does nothing and I'm left to dig up the keyboard shortcuts file to change it so I can get back  a useful shortcut that was removed for no reason.

**Comment by sandy081** [comment]
@Gooseman It seems you are looking to open Keyboard shortcuts json file and also the defaults. There is a button on the top of the Keyboard shortcuts editor to open the file. To open the default keyboard shortcuts, use the command `Preferences: Open Default Keyboard Shortcuts (JSON)` in the command pallette.

<img width="1200" alt="Screenshot 2019-03-11 at 10 05 16" src="https://user-images.githubusercontent.com/10746682/54111917-4e324580-43e5-11e9-8886-237983f833b8.png">

Above changes are mentioned in the release notes - https://code.visualstudio.com/updates/v1_32#_keyboard-shortcuts-editor
