### ISSUE TITLE
CSS intellisense should intelligently display shorthand syntax

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7007]
It would be awesome if CSS rules would show hints like this:

![image](https://cloud.githubusercontent.com/assets/2193314/15630935/45fcb2c6-2505-11e6-82fe-75e970228004.png)

Currently there is a long description that explains it in very verbose language when you expand it (not very discoverable <kbd>ctrl</kbd>+<kbd>space</kbd>):

![image](https://cloud.githubusercontent.com/assets/2193314/15630938/6a940b34-2505-11e6-9e00-085a755f5b52.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15630940/794d9a64-2505-11e6-9c73-bde812e1b892.png)

Moving into the rule shows auto complete based on possible types (in addition to snippets #7006):

![image](https://cloud.githubusercontent.com/assets/2193314/15630944/958820fa-2505-11e6-8fb4-fc01ae0c0612.png)

Ideally above the cursor it should show something like:

```
padding: all;
padding: vertical horizontal;
padding: top horizontal bottom;
padding: top right bottom left;
```

This would be a pretty big win as many developers have difficulty remembering the shorthands. I want to live in that world :sparkles: 

![image](https://cloud.githubusercontent.com/assets/2193314/15631014/8f49a66c-2507-11e6-9e1a-40d1352f6b91.png)

**Comment by aeschli** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
