### ISSUE TITLE
vscode:// URI scheme not opening folders/files properly

### ISSUE THREAD

**Issue by rawbytz** [Microsoft/vscode#70085]
- VSCode Version: 1.32.1 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Attempt to open myFolder using:  `vscode://file/path/to/myFolder/`
2. A new instance opens indicating **"myFolder (vscode)"** but it is not the specified folder, and no files are present.

Does this issue occur when all extensions are disabled?: YES

**Comment by joaomoreno** [comment]
#69998
