### ISSUE TITLE
cursor position incorrect after moving window across screens

### ISSUE THREAD

**Issue by elzorrofxt** [microsoft/vscode#70089]
Issue Type: <b>Bug</b>

- Open VS Code
- Open and begin to edit a file of any type (tested python, txt, and go).
- Type some characters or a sentence, and leave the text cursor indicator at the end.
- Use the mouse and move the window in any direction.
- observe cursor position has moved, sometimes over the top of a character (instead of between characters) and typed characters appear in a different location

Expected result - 
- after moving the window the cursor stays in the same position and typing occures at the cursor location

Note - this is slightly different than BUG #45539, the cursor is not always off by 1 character

System note - working with a Surface 2017 (2736x1824 ~15" screen) and a Samsung (2560x1440 ~ 32" widescreen), may be related to the drastically different aspect ratio and pixel sizes

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:57:55.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexandrudima** [comment]
@bpasero Do you know if there is electron API that could tell us when the window changes screens or when the screen DPI is modified? (I would like to invalidate my font measurement cache in such cases)

**Comment by bpasero** [comment]
@alexandrudima yeah all possible, but currently afaik not being forwarded to the renderer just yet. But see https://github.com/Microsoft/vscode/blob/13583577d9687171e4812c21acf27ac755a71009/src/vs/code/electron-main/window.ts#L393 for reference on the main side.

**Comment by alexdima** [comment]
Let's track in #61641
