### ISSUE TITLE
'Console' is being auto imported (when it shouldn't be) when using 'TS React' file type

### ISSUE THREAD

**Issue by ben-denzer** [Microsoft/vscode#70087]
- VSCode Version: 1.32.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create new file - select 'TypeScript React' for the language mode
2. Type 'console' then press the '.'

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ben-denzer** [comment]
I opened an editor to a different project and I get different behavior - seems to be something in the configuration for my project. Closing.

**Comment by fr3fou** [comment]
Mind sharing what the configuration for your project was? My friend is also experiencing the same issue. @ben-denzer

**Comment by ben-denzer** [comment]
It comes from @types/node if I remember correctly, but if you do a search (INCLUDING NODE MODULES) for `declare module "console` - then you delete that whole block, you will be back to normal. You will have to do this after every `npm install`
