### ISSUE TITLE
Unsaved content disappears when renaming the file on 1.32.1

### ISSUE THREAD

**Issue by jjo148** [Microsoft/vscode#70088]
Issue Type: <b>Bug</b>

Unsaved file content disappears when renaming the file before saving its content. 

- Create a new file
- Enter some text
- Rename the file and the file is suddenly empty

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 5.0.0-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1428)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.42GB (1.84GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
project-manager|ale|10.3.2
vscode-sqlite|ale|0.5.3
better-toml|bun|0.3.2
cmake-format|che|0.4.2
gitignore|cod|0.6.0
doxdocgen|csc|0.4.1
bazel-code|Dev|0.1.9
githistory|don|0.4.6
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
font-switcher|eva|3.0.0
gitlab-workflow|fat|2.0.1
code-runner|for|0.9.7
vscode-yarn|gam|1.6.0
macros|ged|1.2.1
jenkinsfile-support|ivo|0.4.3
latex-workshop|Jam|6.1.0
plantuml|jeb|2.10.6
lua-plus|jep|1.1.1
react-native-snippet|jun|0.5.0
Lua|key|0.0.9
cmake-tools-helper|mad|0.2.1
markdown-shortcuts|mdi|0.11.0
vscode-exec-node|mir|0.5.1
sxhkdrc-syntax|mos|0.0.1
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.0.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.3
trusty-rusty-snippets|pol|0.0.5
vscode-icons|rob|8.2.0
rust|rus|0.5.3
crates|ser|0.3.7
code-settings-sync|Sha|3.2.7
gitconfig|sid|2.0.0
code-spell-checker|str|1.6.10
jest-typescript-toolbox|sve|1.3.2
type-doc-vscode|Tre|0.0.35
cmake|twx|0.0.17
vscode-lldb|vad|1.2.1
cmake-tools|vec|1.1.3
vscode-react-native|vsm|0.8.0

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@jjo148 I cannot reproduce this, what name did you start with and what did you rename to?
