### ISSUE TITLE
[html] should show information on attributes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#7008]
![image](https://cloud.githubusercontent.com/assets/2193314/15631065/71c40dc4-2509-11e6-9358-067dab2a247d.png)

Related: https://github.com/Microsoft/vscode/issues/2037

**Comment by aeschli** [comment]
The challenge is to gather all the description. Maybe it can be accessed online.
It someone is interested to contribute a PR, changes would go here: https://github.com/Microsoft/vscode-html-languageservice/blob/master/src/parser/htmlTags.ts

**Comment by Tyriar** [comment]
It could be fairly trivially pulled in at runtime from MDN, I don't this we should do this though for security reasons.

**Comment by octref** [comment]
Seems possible to make a crawler that directly pulls the info from MDN beforehand and put it into a JSON.

**Comment by jaqra** [comment]
@Tyriar sir, is that ok now?

![htmlattributeinformation](https://user-images.githubusercontent.com/48099350/55750728-98dac800-5a4c-11e9-954e-21aefb53b43f.png)

**Comment by octref** [comment]
@jaqra What you see is a WIP — I'll work on using Markdown for the description https://github.com/Microsoft/vscode-html-languageservice/issues/57.

**Comment by octref** [comment]
Fixed as part of https://github.com/microsoft/vscode-html-languageservice/issues/47.
