### ISSUE TITLE
Breakpoint set in disabled state by default when clicked on a line

### ISSUE THREAD

**Issue by sri-mabelsoftware** [Microsoft/vscode#70080]
Issue Type: <b>Bug</b>

Start debugging any node process in windows. 
Click at the appropriate location of a source line to select it for setting a break point.
It is selected for break point but the break point is disabled.
An additional click (in the break point list) is needed to enable it.

Sorry if it is already reported or by design - but I could not find in a quick search

VS Code version: Code - Insiders 1.33.0-insider (9b849d9de7168eb4f685823bf9b9e27a0a8dae74, 2019-03-08T06:59:35.464Z)
OS version: Windows_NT x64 10.0.17763

**Comment by payonel** [comment]
please forgive my ignorance, is there a "happening for me too!" emoji I should use?
(note: happening for me too!)

**Comment by lumaxis** [comment]
@payonel I believe using the "👍" emoji, like you did, is the common practice. 🙂

**Comment by isidorn** [comment]
Fixed, will be covered once the new insiders is released (will be out today).
Sorry for this!
As a workaround, you have to enable breakpoint, either via breakpoints view or via right click on breakpoint -> enable
