### ISSUE TITLE
Terminal, git status, can't copy file path, pastes random source code.

### ISSUE THREAD

**Issue by wondersloth** [Microsoft/vscode#70086]
Issue Type: <b>Bug</b>

When copying a path in the termainal from a git status, I can't copy and paste the file path.

It will show a list of modified files, and I can't cxopy the path in the terminal and paste it below.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
dustjs|Azk|0.1.1
vscode-toggle-quotes|Bri|0.3.2
prettier-vscode|esb|1.8.1
vscode-language-todo|fir|1.2.3
prettify-json|moh|0.0.3
python|ms-|2019.2.5558
gradle-language|nac|0.2.3
vscode-jsp|pth|0.0.2
java|red|0.40.0
vscode-checkstyle|she|1.0.2
markdown-all-in-one|yzh|2.1.1

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Are you using cmd+c to copy from the terminal? Seems to work for me.

**Comment by wondersloth** [comment]
Note: The underline for the link is not correct. (Though not the problem)

It seems when I click and drag to copy and paste, it will trigger the command click from the terminal then open the window, which then puts my focus else where, then when I hit copy it copies the first line of that file.

**Comment by Tyriar** [comment]
@wondersloth did you mean to attach a screenshot?

It will only activate the link if you're holding ctrl/cmd when you release the mouse button (this will be fixed soon though (https://github.com/xtermjs/xterm.js/pull/1958).

**Comment by wondersloth** [comment]
Sorry, yes I had intended to attach a screenshot. Will upload that manually.

![terminal_copy_paste_problem](https://user-images.githubusercontent.com/129781/54149986-aae92c80-43f4-11e9-9e74-056ef18f4463.gif)
 

Note: The underline for the link is not correct. (Though not the problem)

It seems when I click and drag to copy and paste, it will trigger the command click from the terminal then open the window, which then puts my focus else where, then when I hit copy it copies the first line of that file.

**Comment by Tyriar** [comment]
Ok I think you're seeing 2 different issues, both of which should be fixed in the next release:

- Links are offset when line starts with \t https://github.com/Microsoft/vscode/issues/66632
- Don't activate a link if there was a selection change: https://github.com/xtermjs/xterm.js/pull/1958
