### ISSUE TITLE
VS Code 1.31.1 does not respect "update.channel": "none"

### ISSUE THREAD

**Issue by rpires** [Microsoft/vscode#70084]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Pro Build: 17134.590

Steps to Reproduce:

1. Install VS Code 1.31.1
2. Set settings of Update Channel to None
"update.channel": "none"
3. Restart VS Code
4. Verify that the update 1.32.1 was installed

Does this issue occur when all extensions are disabled?: Yes

Interestingly with extensions disabled, the usual welcome to version 1.32.1 is not displayed. The update is applied anyway.

I see that in 1.32.1 the setting is called _update.mode_, and _update.channel_ gives a deprecated warning, but on 1.31.1 the only setting available that i can see is _update.channel_

**Comment by joaomoreno** [comment]
We moved from `update.channel` to `update.mode`. If you have `update.channel` set in your user settings, then it will still be respected. If you have both settings set, only `update.mode` is respected. Each should be set in user settings, not workspace settings.

Where do you have your setting defined? Did you have both set?

**Comment by rpires** [comment]
Yes I understand that update.channel is being deprecated.

I tried combinations, with just update.channel, and both channel and mode, and yet the update still happens in any of the cases.
 
I have a feeling this should be a very hard to reproduce bug, since others seem to be totally unaffected.

The main motivation for me to stay in 1.31.1 was related to #69534 , which seems to be solved in insider, so I will probably move to that one.

just for debugging help here go the contents of my **%APPDATA%\Code\User\settings.json**

```
{
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.historyExplorer.enabled": true,
    "git.enableSmartCommit": true,
    "git.autofetch": true,

    "emulator.emulatorPath": "%ANDROID_HOME%\\emulator\\emulator.exe",
    "window.zoomLevel": 0,
    // "emulator.emulatorPath": "C:\\Users\\Rui\\AppData\\Local\\Android\\Sdk\\emulator\\emulator.exe"

    "files.associations": {
        "*.js.liquid": "javascript",
        "*.scss.liquid": "scss",
    },
    "dart.flutterSdkPath": "C:\\Users\\Rui\\Projects\\framework_tests\\flutter",
    "files.autoSave": "afterDelay",
    "editor.fontFamily": "Fira Code, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "workbench.iconTheme": "material-icon-theme",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "prettier.singleQuote": true,
    "todohighlight.isEnable": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "update.mode": "none",
    "update.channel": "none",
}
```

Thanks,
Rui Pires

**Comment by joaomoreno** [comment]
Did you restart Code when changing that value?

**Comment by rpires** [comment]
Yes, both with extensions on, and disabling extensions.

In fact when changing the setting from default to none, VS Code requests a restart, which I honor.

Also tried restarting with just the update.channel setting, just the update.mode setting, and both.

All in all I must have reinstalled version 1.31.1 about 20 times this past two days.

In version 1.31.1 when checking the raw JSON settings file, update.mode appears underlined in green, with the tooltip saying unknown setting (as expected this one I suppose)

Thanks

**Comment by joaomoreno** [comment]
This is very strange, as I can't reproduce.

If you want to stay in 1.31 for the time being I suggest using the ZIP release which won't auto update itself.

**Comment by rpires** [comment]
Yeah, I figured this would be a very hard to reproduce one. 

I think its best to move on, keeping this as a reference should anyone search for a similar bug.

Thanks for your time.
