### ISSUE TITLE
Files in the file tree aren't greyed out when using a different .gitignore pattern

### ISSUE THREAD

**Issue by nathfreder** [Microsoft/vscode#70099]
Issue Type: <b>Bug</b>

1. Create a Git repository and open VSCode
2. Create a empty file named `test.txt`
3. Create a `.gitignore` with the following contents
```txt
/test.txt
```
4. Notice that the file isn't greyed out in the file tree
5. Change the content of `.gitignore` to the following:
```txt
text.txt
```
6. Notice that the file **is** greyed out

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|-psn_0_536707|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
In your issue you mention both `test.txt` and `text.txt`. Make sure you can reproduce this without that typo.

**Comment by nathfreder** [comment]
@joaomoreno Sorry, looks like it was just a typo. 👍

**Comment by nathfreder** [comment]
@joaomoreno I just re-read my message, the problem still occurs but it was just a typo in the issue description.

**Comment by joaomoreno** [comment]
I still can't reproduce, even without the typo. Can you show me a screen recording?

**Comment by nathfreder** [comment]
Here's a screenshot:
<img width="1024" alt="Screen Shot 2019-03-11 at 12 42 12 PM" src="https://user-images.githubusercontent.com/40307305/54136808-31087180-43fb-11e9-9dbd-4e7814cb08c6.png">
As you can see `GitKraken Glo Boards-ee337add1627.json` is in the `.gitignore` but isn't greyed out. If I change the pattern from `/GitKraken Glo Boards-ee337add1627.json` to `GitKraken Glo Boards-ee337add1627.json` it becomes greyed out.
<img width="1024" alt="Screen Shot 2019-03-11 at 12 44 45 PM" src="https://user-images.githubusercontent.com/40307305/54136964-847abf80-43fb-11e9-85f0-629966692865.png">

**Comment by joaomoreno** [comment]
I still can't reproduce. Is that `GitKraken Glo Boards-ee337add1627.json` file checked into the repo?

**Comment by nathfreder** [comment]
Oddly enough the issues isn't happening anymore. 🤔
