### ISSUE TITLE
Integrated terminal is printing ^C instead of canceling the command

### ISSUE THREAD

**Issue by mikehogan** [Microsoft/vscode#70096]
Issue Type: <b>Bug</b>

Open integrated terminal
type a command
press ctrl-c

actual results: prints ^C after the command and doesn't cancel the command

expected: cancel the command go to a new blank command prompt

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.3
vscode-eslint|dba|1.8.2
vscode-faker|dee|1.3.0
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-solution-explorer|fer|0.3.1
code-runner|for|0.9.7
reg|ion|0.0.2
latex-workshop|Jam|6.1.0
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
ruby|reb|0.22.3
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by mikehogan** [comment]
Bug still occurs in latest insiders, clean install

VS Code version: Code - Insiders 1.33.0-insider (9b849d9de7168eb4f685823bf9b9e27a0a8dae74, 2019-03-08T06:59:35.464Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by krokofant** [comment]
Still have it in latest insider even with windowsEnableConpty set to false.

**Comment by krokofant** [comment]
@Tyriar Why is this issue along with #45693 closed if the solution is a feature that comes *with a future version of windows*?

**Comment by Tyriar** [comment]
@krokofant because the work on our side to support conpty is done, and as of last week it's enabled by default in vscode insiders (if Windows is >= build 18309). That's how we manage issues in this project.

**Comment by krokofant** [comment]
@Tyriar I do appreciate the work and it seems like it will be great with this support. However, what confuses me a bit is that this issue arose for me just some days ago so I don't understand how the fix is conpty with a newer Windows. Ctrl+C worked for a long time in VSCode Insiders terminal and now it doesn't. 🤔

**Comment by Tyriar** [comment]
@krokofant ctrl+c has always only _sometimes_ worked under the old backend [winpty](https://github.com/rprichard/winpty), you were likely just lucky and didn't see it not work much. Conpty is the future and it's maintained by the [Console team](https://github.com/Microsoft/console) at Microsoft so they'll actually be able to support future issues like these.
