### ISSUE TITLE
Emmet not working with Django plugin

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Microsoft/vscode#70092]
Emmet would not work when I was working with an index.html file. I disabled all of my extensions and re enabled them one by one until I found I found the culprit.

#### - OS Version: Arch Linux w/ Con Kolivas kernel 4.20.14-1

**Comment by octref** [comment]
Did you follow the usage?

![image](https://user-images.githubusercontent.com/4033249/54055697-b218fc00-41a2-11e9-8770-7da4448c0c90.png)
