### ISSUE TITLE
Terminal Linkify doesn't work with some "valid" characters

### ISSUE THREAD

**Issue by Goodwine** [Microsoft/vscode#70098]
Version: 1.31.1
OS: Linux x64

Steps to Reproduce:

1. `echo http://example.com/+/test`

**Expected:** linkify `http://example.com/+/test`
**What happened?:** linkified only `http://example.com/`

It seems like `+` causes linkify to "break", it works as expected on my terminal outside vscode.
The use case for this is that gerrit uses this for code reviews 

Does this issue occur when all extensions are disabled?:
Yes

**Comment by jchang10** [comment]
Linkify just broke for windows backslash '\' delimiters, too. Broke about 2 weeks ago in the Developer's edition, I noticed.

**Comment by jchang10** [comment]
@Tyriar Awesome! Confirmed, working on the latest developer's build!!!
