### ISSUE TITLE
MSSQL Intellisense not showing suggestions but does identify invalid objects

### ISSUE THREAD

**Issue by cryocaustik** [Microsoft/vscode#70094]
While using MSSQL and connected to a SQL Server, Intellisense will identify and highlight invalid object names (db, schema, table, and columns), but will NOT provide any suggestions/autocomplete options.

- VSCode Version: 1.32.1 (user setup)
- OS Version: Win10 Enterprise
- MSSQL Version: 1.4.0

Steps to Reproduce:

1. Open .sql file
2. Connect to SQL Server using MSSQL extension
3. While writing query, attempt to browse Intellisense suggestions/autocomplete (using the auto-popup or ctrl+space)
4. Complete writing query with invalid db, shcema, or table name

Example of Intellisense identifying invalid object:
![image](https://user-images.githubusercontent.com/15346996/54054834-2605d500-41a0-11e9-87d1-1b4e20df3287.png)

Example of Intellisense NOT providing any suggestions/autocomplete options:
![image](https://user-images.githubusercontent.com/15346996/54054864-3d44c280-41a0-11e9-8bf7-0405ee4a688c.png)

I have also verified that downgrading VS Code to v1.31.1 **will resolve** the issue.

**Comment by sandy081** [comment]
@cryocaustik 

![image](https://user-images.githubusercontent.com/15346996/54054834-2605d500-41a0-11e9-87d1-1b4e20df3287.png)

This is not an intellisense. This is error peek widget. You can also see this in the second example. You can open this from the hover or using the command `Go to Next Problem (Error/Warning/Info)`

If you are not intending this, please explain it clearly what are you expecting to see.

**Comment by cryocaustik** [comment]
@sandy081 I am using the error peek widget to show that the application does recognize that the table is an invalid object; this means that there is a valid connection and the query is comparing the user query to the objects in the database.

The issue is that it does not provide those as autocomplete suggestions (intelisense).

**Expected Result**
![image](https://user-images.githubusercontent.com/15346996/54138303-6d78a500-43dc-11e9-8197-26671d3c8436.png)


**Actual Result**
![image](https://user-images.githubusercontent.com/15346996/54138116-196dc080-43dc-11e9-94b0-245106b29323.png)

**Comment by RyanRogers5911** [comment]
Upgrading to the latest Insider Version of VS Code does not resolve the error either.

**Comment by DrDanRyan** [comment]
I am having the same issue on Windows 10, Build 1.32.1 as well.

**Comment by sandy081** [comment]
Looks to me an issue with the extension. Please file an issue against it - https://github.com/Microsoft/vscode-mssql
