### ISSUE TITLE
filter disappeared on outline view

### ISSUE THREAD

**Issue by martinrosas84** [Microsoft/vscode#70095]
Issue Type: <b>Bug</b>

Outline view doesn´t show the filter input

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.97GB (1.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.2.5558

</details>

**Comment by joaomoreno** [comment]
@martinrosas84 You can now simply start typing when focused in the outline. It will start filtering.

**Comment by Bbommel** [comment]
But you have to click into the outline view to focus it and by clicking there, the editor jumps to method you (randomly) clicked on. Without a filter symbol there is no chance to simply focus the outline view without any further action. 

Please re-open this issue and solve that bug (or feature request).

**Comment by gracece** [comment]
With  the Vim plugin installed, it is more **inconvenient**. 
After clicked randomly to focus to outline view, I have to  type `/` to switch into search mode.

**Comment by martinrosas84** [comment]
I´m agree with Bbommel!! the new feature is very uncomfortable!! I don´t understand why the search box dissapear
