### ISSUE TITLE
[ERROR:OmniSharp.Dnx.DnxProjectSystem] TODO: unknown keyword platform

### ISSUE THREAD

**Issue by z2xlong** [Microsoft/vscode#7009]
- VSCode Version:1.1.1
- OS Version:Mac OSX El Capitan 10.11.5

The formatting code & intelligent functions does not work.

Steps to Reproduce:

1. Create new ASPNET project via yeoman, the contents of project.json as follows:
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "protobuf-net": "2.1.0-alpha-1",
    "System.Collections": "4.0.10"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },

  "tooling": {
    "defaultNamespace": "Demo"
  }
}

2. The Omnisharp log like this:
[INFO] Starting OmniSharp at '/Users/zzx/Projects/DesignSmell/Demo'...
[INFO] Started OmniSharp from '/Users/zzx/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 9572...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/zzx/Projects/DesignSmell/Demo' on host 9561.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/zzx/.k/runtimes/kre-mono.1.0.0-beta3'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/zzx/Projects/DesignSmell/Demo' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/zzx/Projects/DesignSmell/Demo/project.json'.
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Listening on port 58705
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running DesignTimeHost on port 58705, with PID 9579
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:58705
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:58705
[ERROR:OmniSharp.Dnx.DnxProjectSystem] TODO: unknown keyword platform
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/zzx/Projects/DesignSmell/Demo'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/zzx/Projects/DesignSmell/Demo'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading

**Comment by jrieken** [comment]
please file against the omnisharp reop
