### ISSUE TITLE
Add outputCapture launch config option to documentation.

### ISSUE THREAD

**Issue by martinog2** [Microsoft/vscode#70093]
An 'outputCapture' option was added in vscode update Septemper 2017, version 1.17.
Info about that option was not added to docs for 'Launch configuration attributes' here:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by roblourens** [comment]
Yeah it's only needed for some specific situations, probably not of general interest. But I can add it to the docs.

**Comment by martinog2** [comment]
> Yeah it's only needed for some specific situations, probably not of general interest. But I can add it to the docs.

Thanks.

Why is it uncommon to need it? I have a nodejs application that uses winston logger to log to stdout (using winston.transports.Console). If I don't add "outputCapture": "std" to launch.json then I don't see any logging as I debug. Wondering if there's a more standard approach I should be taking. Thanks again.

**Comment by roblourens** [comment]
You're correct, that's a scenario where it's needed. That's because it writes directly to the stdout stream bypassing `console.log`.
