### ISSUE TITLE
Automatic commit message stage and commit unexpectedly stages all untracked files in tree

### ISSUE THREAD

**Issue by wesinator** [microsoft/vscode#70091]
- VSCode Version: 1.32.1
- OS Version: mac 10.14.3

Steps to Reproduce:
1. Git repo project with unstaged files in directory
2. Modify a file already tracked in commits.
3. Before staging, enter a commit message and send with command+return
4. Select 'Yes' on the 'no staged changes' dialog
<img width="431" alt="image" src="https://user-images.githubusercontent.com/5124946/54053578-ab47b480-41b5-11e9-8f4c-d685bf732d78.png">

All files in the project directory, including ones that were unstaged and not tracked, were staged and committed.

This is astonishing behaviour.

**Expected:** only stage and commit already tracked, modified files.
If no tracked files are modified, cancel the commit and don't stage anything.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
I suggest a setting which defines that only tracked files can be auto staged when committing.

**Comment by joaomoreno** [comment]
Added `git.smartCommitChanges` which allows you to control whether all files are staged or just tracked ones, when smart commit runs.
