### ISSUE TITLE
"ZoomTo" action?

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#701]
The zooming in/out on the UI works great, but for me the "perfect" zoom level would be somewhere between the 1st and 2nd zoom. I wondered if a ```ZoomTo``` action (or some other public api) with input parameter could be added, so that extensions such as [vscode-zoom](https://github.com/Microsoft/vscode-zoom) could set a more precise zoom level.

**Comment by jrieken** [comment]
@bpasero will know but I believe the zoom states are given by electron/chromium and that there is no 1.5 level

**Comment by bpasero** [comment]
@stkb yeah the zoom action is only going up and down by an increment of 1. fair request.

**Comment by bpasero** [comment]
This will be possible with the newly introduced and persisted `window.zoomLevel` setting.

**Comment by stkb** [comment]
:thumbsup: Thanks!
