### ISSUE TITLE
"Auto-Attach" DebugSession name change after launch

### ISSUE THREAD

**Issue by hoehrmann** [microsoft/vscode#70104]
I am currently implementing something akin to an »auto-attach« feature for `vscode-perl-debug`. When I call `vscode.debug.startDebugging` I do not have a good name for the debug session yet, but once a connection to the debugger is established, I can come up with a better one.

Unfortunately the `DebugSession.name` property is `read-only` and there does not seem to be an alternative to set it post-launch. https://github.com/Microsoft/vscode-node-debug/blob/d490a306164fd086e7e792dec858b1d36a879871/src/node/extension/autoAttach.ts#L62 also uses an awkward name like `Auto attached (123)` it seems.

I do have control over the thread name, but in case of Perl, there is only ever one thread, and I'd rather not have session name and also thread name in the user interface, https://github.com/Microsoft/vscode/issues/69752.

(Some way to make vscode use the thread name of the single thread in place of the poorly auto-generated session name would work for me.)

**Comment by weinand** [comment]
Valid feature request, but since you are the first to ask for this, it will not addressed anytime soon...

**Comment by hoehrmann** [comment]
Related to https://github.com/Microsoft/vscode/issues/62972

**Comment by weinand** [comment]
@hoehrmann `DebugSession.name` has been made writable some time ago and changes are now properly reflected in the UI.
