### ISSUE TITLE
Not saving, not returning

### ISSUE THREAD

**Issue by maxpauwels** [Microsoft/vscode#70101]
Issue Type: <b>Bug</b>

Hi there, 

I am experiencing an issue with VSC, it keeps on deleting code when saving, go to the bottom of the page when pressing "command z" or save.

I explained it here: 

https://www.useloom.com/share/1ef508026ab74981a7ffa223a29a984e

I hope this can be fixed as I am supposed to finish this project in the next 3 days.

Bes,t

Max

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (17.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tidyhtml|anw|1.10.0
path-intellisense|chr|1.4.2
vscode-faker|dee|1.3.0
vsc-material-theme|Equ|2.6.3
beautify|Hoo|1.4.9
icon-fonts|idl|2.1.5
path-autocomplete|ion|1.13.1
LiveServer|rit|5.5.1
html5-boilerplate|sid|1.0.3

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is almost certainly one of your extensions, vscode-tinyhtml and beautify sounds like they might be it
