### ISSUE TITLE
i want have a new possible

### ISSUE THREAD

**Issue by RubyKiss** [Microsoft/vscode#70108]
Code navigation hopes to enter each code block, for example, **the current cursor is in the for loop and then you can go to the for loop header at the navigation point**. Of course, when you have a lot of code, it is very troublesome to find the head and tail. I think so.

代码导航希望输入每个代码块，例如，当前光标位于for循环中，然后您可以转到导航点的for循环标题。
当然，当你有很多代码时，找到头部和尾部是非常麻烦的。 我觉得可以。

**Comment by alexandrudima** [comment]
Can you explain in greater detail your issue? I am afraid I don't understand.

**Comment by RubyKiss** [comment]
it look like this

**Comment by RubyKiss** [comment]
it loo like 
I hope that the code navigation can be made: the inside of the if statement where the cursor is currently located or the inside of the for, you can choose to switch to the head and tail of the current code space, for example: if { at 100 lines, } on line 200, hope Can switch the head and tail of if in the navigation bar

**Comment by alexandrudima** [comment]
@RubyKiss What action/command are you running?

**Comment by RubyKiss** [comment]
i don't know use what a quicky key achieve this function

**Comment by alexandrudima** [comment]
@RubyKiss You can invoke the command "Expand Selection".

**Comment by RubyKiss** [comment]
well,thank you

**Comment by jrieken** [comment]
We have no real API for this and extensions are encouraged to implement this functionality.
