### ISSUE TITLE
Terminal VIsual Bugs, and more

### ISSUE THREAD

**Issue by bagasprima** [Microsoft/vscode#70109]
Issue Type: <b>Bug</b>

On my current version, I did these:
1. Open terminal window (Ctrl+Shift+`).

From here, there are 2 different behavior shown, but more or less the same problem.
Powershell:
2. Terminal is then showing blank screen, (supposed to show version and current directory).
3. If you see on the scroll bar, it is like I've scrolled down many lines. and when I scroll to top, the version text is sitting there.
4. But still, cant seem to find any <current directory text>.
5. When I start typing, my command line becomes indented as if  the <current directory text> is there.

CMD:
2. Terminal show the default screen (showing version and current directory).
3. Type something on it, and the previous texts stops appearing, leaving my command line indented, as if the <current directory text> is there.
4. From here, I can close the terminal, and open it again, and will then the <current version text> and <current directory> is shown. But, after I typed any character, they will disappear again.
5. If I do 'cls', the current directory text will then be shown again. then the behavior will be normal for the rest of the experience.

Additional Bugs:
AND, if I take a look at the terminal dropdown, after I switch between terminal (using Ctrl+Shift+P and Choose default terminal) it duplicates to two or three (I can see 3 choices, but all of them is powershell, or cmd, depends on what I am using right now), and thus I cannot switch to the other terminal using that dropdown.. It stays the same even after I restart VS Code (the duplicates disappear though, but I still cannot choose other terminal) 

Idk what happened to this visual studio code, but seems to be normal in my other laptop (I just bought this one and fresh install).

Please fix this because I really find this annoying thanks. And lemme know how to fix it once its done

Best Regards,

Bagas

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.95GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by pavelloz** [comment]
Last couple releases made vscode almost unusable... at least on macOS. I have to restart my editor 10 times a day because of visual bugs and freezes (completely unresponsive).

**Comment by Tyriar** [comment]
@pavelloz you might want to look at https://github.com/Microsoft/vscode/wiki/Performance-Issues to hopefully create a performance report that we can action. This specific issue is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
