### ISSUE TITLE
Zen-mode for current working window

### ISSUE THREAD

**Issue by ghominejad** [Microsoft/vscode#70115]
Consider you have an ultra wide LCD and you've opened and working with many files simultaneously.
Most of the time you need to be focused on one file .

I think it's useful having Zen Mode shortcut key only for current working window.

**Comment by isidorn** [comment]
Well zen mode is applied only to the current active window. Not for all windows.
Ctrl + K, Ctrl + Z

What are you exactly missing here? On what OS are you?

**Comment by ghominejad** [comment]
Before zen mode :
![image](https://user-images.githubusercontent.com/1716698/54136663-72b40f00-4431-11e9-8dd0-389eafd41b95.png)

After zen mode :
![image](https://user-images.githubusercontent.com/1716698/54136669-76479600-4431-11e9-911c-0b8b1edc7dd4.png)

When i have splitted windows, all of them are shown in zen mode

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.76GB (2.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.8
handlebars-preview|cha|1.1.0
es7-react-js-snippets|dsz|2.1.1
gitlens|eam|9.5.1
vsc-material-theme|Equ|2.7.0
php-debug|fel|1.13.0
beautify|Hoo|1.4.9
peachpie-vscode|iol|0.9.36
csharpextensions|jch|1.3.0
nodejs-repl|los|0.5.11
Kotlin|mat|1.7.0
vs-deploy|mkl|14.0.0
theme-monokai-pro-vscode|mon|1.1.12
csharp|ms-|1.17.1
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.6.3
quicktype|qui|12.0.46
LiveServer|rit|5.5.1
ayu|tea|0.18.0

(9 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Yeah, as designed.
We will not change that.

**Comment by ghominejad** [comment]
But i didn't want to change it. of course it is useful. As i mentioned it's useful having a new Zen Mode shortcut key "only for current working window".

Thank you
