### ISSUE TITLE
Terminal can not display normal when the terminal tab height is not enough

### ISSUE THREAD

**Issue by roboooots** [Microsoft/vscode#70110]
- VSCode Version:  Version 1.32.1(user setup)
- OS Version: Windows 10 1809 11763.348

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/45580554/54065761-31203a00-4260-11e9-9ac8-4bfea30b9727.png)
open terminal did't show anything 

2.
![image](https://user-images.githubusercontent.com/45580554/54065783-5d3bbb00-4260-11e9-86f3-1fa5fe6b21ca.png)
type any  word, show command line,  can use normal , but , produced a certain height of blank
![image](https://user-images.githubusercontent.com/45580554/54065802-81979780-4260-11e9-80c2-f9731d4ab590.png)

3.
Pull up the terminal tab, and delete this terminal, reopen a new terminal
![image](https://user-images.githubusercontent.com/45580554/54065829-ec48d300-4260-11e9-9c59-71f32640fe42.png)
can be displayed normally

Does this issue occur when all extensions are disabled?: Yes

**Comment by roboooots** [comment]
#70109

**Comment by roboooots** [comment]
#70109

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
