### ISSUE TITLE
Adding option to turn off warning message off and on

### ISSUE THREAD

**Issue by moreal** [Microsoft/vscode#70119]
When I use promise for web request, I saw 'rejected promise not handled within 1 second' warning for many times  
But there will be people dislike to see that message, so I suggest adding options to turn that warning message off and on.

**Comment by kasparsbergs** [comment]
#16432 [TS/JS: rejected promise not handled within 1 second ](https://github.com/Microsoft/vscode/issues/16432)

**Comment by jrieken** [comment]
> When I use promise for web request, I saw 'rejected promise not handled within 1 second' warning for many times

That means you are missing an error and just ignore that isn't what we like to do.

**Comment by moreal** [comment]
> > When I use promise for web request, I saw 'rejected promise not handled within 1 second' warning for many times
> 
> That means you are missing an error and that isn't what we like to do. If you wanna ignore your error, than you can use `catch(() => {/*i don't handle errors*/})`

Wow.. I didn't know that, Thank you!!
