### ISSUE TITLE
code formatting support of some template languages

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#7011]
- VSCode Version: 111
- OS Version: OSX current

Hello,
are there any reliable way to use auto format code on templates such as handlebars or ejs ?

I see that there is in user settings an indent setting support for handlebars, but this is not accessible in handlebars mode, only in html mode. This is inconsistent.

Also if I try a template language like EJS (for which there is an extension), in ejs mode there is no auto format, and in html mode every <% is considered as opening html tag which produce catastrophic auto format code. And we have no intellisense for js code in ejs templates (html or ejs mode).

All in all, unless I miss something, I find it hard to work with templates in vscode and I suggest an improvement on this.

**Comment by jrieken** [comment]
@aeschli fyi

**Comment by v3ss0n** [comment]
bumbing this , formatting handlebars is totally broken as of now.

**Comment by Alonski** [comment]
Just wanted to give my 2 cents on this.
Using this config: https://medium.com/@alonbukai/how-to-format-handlebars-in-vscode-26144e9feec8
I am able to correctly format handlebars.
One problem that I found though is that formatting for {{unless}} doesn't work as expected.
Example:
```
<div class="site-settings-header-text">
    {{#unless site.is_template}}
        {{t 'site-data-description'}}
        {{else}}
            {{t 'template-data-description'}}
    {{/unless}}
</div>
```

Expected formatting:
```
<div class="site-settings-header-text">
    {{#unless site.is_template}}
        {{t 'site-data-description'}}
    {{else}}
        {{t 'template-data-description'}}
    {{/unless}}
</div>
```

If you think I should open a separate issue please tell me.

**Comment by v3ss0n** [comment]
Thanks a lot , that is much better , only a few edge cases are unless / span  /small

**Comment by Alonski** [comment]
I found another problem.
In an `{{each}}` loop an `{{else}}` isn't formatted correctly:
Input:
```hbs
{{#each list as |item|}}
  {{item}}
    {{else}}
  No Items
{{/each}}
```

Expected:
```hbs
{{#each list as |item|}}
  {{item}}
{{else}}
  No Items
{{/each}}
```

Actual:
```hbs
{{#each list as |item|}}
  {{item}}
  {{else}}
    No Items
{{/each}}
```
