### ISSUE TITLE
Webpack error in vscode terminal

### ISSUE THREAD

**Issue by Ahnteve** [Microsoft/vscode#70112]
### In vscode terminal
![222](https://user-images.githubusercontent.com/33370010/54066602-00e39600-4276-11e9-88fd-1a7e29ceabcb.JPG)
Unexpected token error

### In console
![333](https://user-images.githubusercontent.com/33370010/54066617-4acc7c00-4276-11e9-98cc-0434d0c261ca.JPG)
Success..
Why..????

### webpack.config.js
```
const path = require("path");

const MODE = process.env.WEBPACK_ENV;
const ENTRY_FILE = path.join(__dirname, "src", "assets", "js", "main.js");
const OUTPUT_DIR = path.join(__dirname, "src", "static");

module.exports = {
	entry: {
		main: ENTRY_FILE
	},
	mode: "development",
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: {
					loader: "babel-loader"
				}
			}
		]
	},
	output: {
		filename: "main.js",
		path: OUTPUT_DIR
	}
};
```
I want to run webpack in vscode but I am so sad that I can't 😢

**Comment by ShatterPlayer** [comment]
Do you use cmd or PowerShell in VS Code? If PowerShell, try change terminal to cmd in settings - set terminal.integrated.shell.windows to C:\\Windows\\System32\\cmd.exe

**Comment by Ahnteve** [comment]
Oh, my God. The problem's solved..!! Thank you 😂😂😂😂😂😂😂
