### ISSUE TITLE
unknown css property horizontal-align

### ISSUE THREAD

**Issue by jokro** [Microsoft/vscode#70116]
Issue Type: <b>Bug</b>

In ccs file unknown property warning error  for horizontal-align:center.  If changed into vertical-align:center this works fine.

 file.css:
.textField {
    horizontal-align:center;
}

I use lates VS Code with enabled from MarketPlace: Debugger for chrome and Nativescript.

I tried Installing CSSLINT;this makes no difference. Deinstalling it doesnt solve the problem either.

The code is compiled ok and works fine. The warning message is disturbing however.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.11.3
nativescript|Tel|0.9.0

</details>

**Comment by shiftgeist** [comment]
This is not an issue with vscode. CSS has no property that is called `horizontal-align`.

Maybe this helps you: [CSS Layout - Horizontal & Vertical Align](https://www.w3schools.com/css/css_align.asp)

**Comment by jokro** [comment]
I am sorry, but your answer is mistaken: vertical-align is a CSS property. It is even shown in the link you sent, scroll down and see:

```
 /* If the text has multiple lines, add the following: */
.center p {
  line-height: 1.5;
  display: inline-block;
  vertical-align: middle;
}
```
I am not using CSSLint, and therefore I wonder which component is triggering the error. Please help to find a solution.

**Comment by shiftgeist** [comment]
@jokro you are absolutely right: `vertical-align` is a CSS property, `horizontal-align` is not.

**Comment by jokro** [comment]
You are perfectly right, my excuse for the disturbance. It was caused by the fact that Nativescript 
both supports vertical-align and horizontal-align. I now understand why VS does not suport this, because it is not standard. Thx
