### ISSUE TITLE
A problem with install Go 0.9.2

### ISSUE THREAD

**Issue by ajuse** [Microsoft/vscode#70120]
Issue Type: <b>Bug</b>

when I wanna to install Go extension, I got this problem:
Cannot read property 'local' of undefined and Failed to install 'ms-vscode.go'.
Any suggestions are useful, tks.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
@ajuse I cannot repro it. Can you provide the logs so that we can know what's happening. You can find the logs in the output panel. Please share `Shared Process` and `Renderer` logs.

**Comment by ajuse** [comment]
@sandy081 Thanks a lot, but there is no logs in the output panel. My operate is simple, open VScode > click the Extensions button > get a Go extension > click the install button, and I got an interface like this:
<img width="1026" alt="VScode-go" src="https://user-images.githubusercontent.com/46194850/54135827-81acb880-4455-11e9-84d7-8426ffd44e51.png">

Is there a problem with my operation?

**Comment by sandy081** [comment]
@ajuse Do following

- Set log level to trace using command `Set Log Level`
- Open the shared log view using command `Open View` -> `Log (Shared)`
- Open the Developer tools console using command `Toggle Developer Tools`
- Retry the operation

See if there are any interesting info in the log view or console

**Comment by ajuse** [comment]
@sandy081 Thanks a lot, I found the reason of this problem when I got the message in OUTPUT，VScode Permission denied to creat dirctory in .vscode/extensions/. So I type a command "sudo chown -R luoyunfu:staff .vscode", The problem is solved.

![image](https://user-images.githubusercontent.com/46194850/54819572-47ee7400-4cd7-11e9-9311-8cdd2ec3eedf.png)
