### ISSUE TITLE
syntax highlight for .vimrc files

### ISSUE THREAD

**Issue by zachvalenta** [Microsoft/vscode#70121]
I searched open and closed issues but couldn't find anything related to syntax highlighting for `.vimrc` files. 

Also looked around extension store and didn't see anything else there, either.

**Comment by shiftgeist** [comment]
Visual Studio Code has no build in support for `.vimrc` syntax highlighting, but you can install this extention: [vscode-viml-syntax](https://marketplace.visualstudio.com/items?itemName=dunstontc.viml). It supports `.vim`, `.vimrc`, `.gvim` and `.ideavim` syntax highlighting.

**Comment by zachvalenta** [comment]
Cheers! Works like a charm.

I searched for `vimrc` but didn't get this extension in the search results. Seems like search inside the extensions portion of the sidebar searches over the description text of the extension, which is why I didn't come across it. Will open a PR on the extension's Github so that other people find!
