### ISSUE TITLE
Me aparece una ANOMALY: meaningless REX error en el terminal con el git bash de visual studio code vscode

### ISSUE THREAD

**Issue by jpeguerocastro** [Microsoft/vscode#70122]
![errorvscode](https://user-images.githubusercontent.com/12587688/54072502-e5669400-4251-11e9-96c2-17bc3bb9109e.jpg)

Issue Type: <b>Bug</b>

cuando abro la terminal de vscode, en este caso estoy utilizando git-bash me aparece el siguiente error **[0x7FFFC239EA00] ANOMALY: meaningless REX prefix used**, multiples veces cada vez que ejecuto algun comando, no se a que se debe.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (7.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
gc-excelviewer|Gra|2.1.29
php-cs-fixer|jun|0.1.96
php-namespace-resolver|Meh|1.1.5
dotenv|mik|1.0.1
vscode-language-pack-es|MS-|1.31.4
python|ms-|2019.2.5558
sublime-keybindings|ms-|4.0.0
vetur|oct|0.16.2
laravel-blade|one|1.18.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|3.6.3
code-spell-checker|str|1.6.10
code-spell-checker-spanish|str|1.0.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
