### ISSUE TITLE
vscode.debug.activeDebugSession is updated asynchronously

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#70125]
- VSCode Version: 1.32.1, 1.33.0-insider from 2019-03-08T06:57:33.004Z
- OS Version: Arch Linux, Windows 10, MacOS

In 2 of my extensions, I start a debug session and then try to read `vscode.debug.activeDebugSession`, like this:
```
await vscode.debug.startDebugging(workspaceFolder, debugConfig);
const session = vscode.debug.activeDebugSession;
```

Starting with version 1.32.1, the session I get is `undefined`. However, I found a very simple workaround:

```
await vscode.debug.startDebugging(workspaceFolder, debugConfig);
await new Promise(resolve => setImmediate(resolve));
const session = vscode.debug.activeDebugSession;
```

So it seems that `vscode.debug.activeDebugSession` is updated asynchronously immediately after the promise from `vscode.debug.startDebugging()` is resolved.

I think that this is probably related to #69534, maybe the fix for that issue will also solve this one. I will check this as soon as there is an Insiders build containing that fix.

**Comment by hbenl** [comment]
I just checked with the Insiders version from 2019-03-11T08:42:16.804Z and the bug is still there.

**Comment by weinand** [comment]
This issue and #69534 are probably originating from the same change: some internal method has become asynchronous. This was breaking the `vscode.debug.onDidStartDebugSession` and we had to fix it.

But `vscode.debug.activeDebugSession` is not broken by this: you cannot assume that `vscode.debug.activeDebugSession` is updated immediately after you are calling `startDebugging`. Previously you might have been able to observe this, but there is no guarantee for this.

A better approach would be to register a `vscode.debug.onDidChangeActiveDebugSession` handler.
But be aware: the debug session that you receive via `onDidChangeActiveDebugSession` is not necessarily the one you've started with `startDebugging`.

**Comment by hbenl** [comment]
I am not assuming that `vscode.debug.activeDebugSession` is updated _immediately_ after calling `startDebugging`. But since `startDebugging` returns a `Promise` one would assume that it is resolved _after_ the asynchronous operation is finished, not before.
The way it is now, I find the API to be misleading. What's the point of returning a `Promise` if it doesn't signify anything useful? I think the `Promise` should either be removed or made to work as one would expect.
I know how to work around this, so it's not a big issue, but I'm sure others will be confuses by this as well.

**Comment by weinand** [comment]
`startDebugging` returns a promise that resolves to true when debugging could be successfully started.

The `activeDebugSession` is driven by the UI (and the users). It is asynchronous by nature and unrelated to `startDebugging`.
