### ISSUE TITLE
keyboard accelerators don't work

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#7012]
- VSCode Version: 1.1.1
- OS Version: Windows 7, x64

Steps to Reproduce:

1. ~~Open the editor, make sure it has focus (cursor is blinking).~~
2. Press and hold the `Alt` key
3. Observe the accelerator letters highlighted in the main menu on the top. Particularly the `File` menu got an underscore at `F`
4. While keeping to hold `Alt` press the `F` key

Expected: the "File" in the main menu to open
Actual: no action

**Comment by alexandrudima** [comment]
Works for me in Win10 in vscode 1.4.0
