### ISSUE TITLE
Collapsible Comment Block

### ISSUE THREAD

**Issue by TLKG** [Microsoft/vscode#70134]
[Python ](https://github.com/Microsoft/vscode/issues/31966)and [Go ](https://github.com/Microsoft/vscode-go/issues/2364)have collapsible comment block, can we have it for Javascript / Node?

**Comment by TLKG** [comment]
Note, I'm talking about comment not code block.
I've tried white space and tab, neither give me the folding/unfolding sign to click on.

![image](https://user-images.githubusercontent.com/22269729/54076749-a0e3f400-4263-11e9-8f87-8c2d22b52f6f.png)

**Comment by TLKG** [comment]
![image](https://user-images.githubusercontent.com/22269729/54076777-020bc780-4264-11e9-8826-2cfce703a170.png)

**Comment by Sovgut** [comment]
Are you talking about it?
![Comment block](https://i.imgur.com/XWJNxVV.png)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/22732

**Comment by TLKG** [comment]
Just tested again in a .js file, as soon as `/**` is typed in, it recognizes and prompts as "JSDoc comment", but still not folding
![image](https://user-images.githubusercontent.com/22269729/54870142-dc041e00-4d5f-11e9-978d-08e84e87dea5.png)

**Comment by TLKG** [comment]
it does not do it for .ts either. 
VSC version and setting

![image](https://user-images.githubusercontent.com/22269729/54870181-44eb9600-4d60-11e9-8b3c-2f752094473b.png)

![image](https://user-images.githubusercontent.com/22269729/54870226-e1159d00-4d60-11e9-966d-1aecccc0a82c.png)
