### ISSUE TITLE
terminal window does not shows the directory when opens for the first time

### ISSUE THREAD

**Issue by bennymeg** [Microsoft/vscode#70130]
Issue Type: <b>Bug</b>

The terminal window does not shows the directory when opens for the first time.
Once opend, the terminal window is either empty or shows the power shell copyrights. it does not shows the current working directory mark (i.e. c:/code>).

How to reproduce:
Simply open the terminal. my system configuration atteched below. 

Thanks in advance.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
json-tools|eri|1.0.2
gc-excelviewer|Gra|2.1.29
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.3
debugger-for-edge|msj|1.0.6
code-spell-checker|str|1.6.10
cython|tcw|0.1.0
vscode-arduino|vsc|0.2.25

</details>

**Comment by FishOrBear** [comment]
me too

![image](https://user-images.githubusercontent.com/19372111/54126438-81ef8880-4442-11e9-9783-8b5785d9c987.png)

![image](https://user-images.githubusercontent.com/19372111/54126457-8d42b400-4442-11e9-8004-c20a8d260e39.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
