### ISSUE TITLE
Quick open does not recognize "~" for home directory anymore

### ISSUE THREAD

**Issue by madig** [Microsoft/vscode#70132]
(Reopening of https://github.com/Microsoft/vscode/issues/32736 -- Regression?)

In Python tracebacks, file paths can be shown like this:

> ~/.virtualenvs/cantarell/lib/python3.7/site-packages/fontMath/mathGlyph.py

Copying and pasting this path into the "quick open" field (Ctrl+P) does not find the file. I have to manually expand the tilde to my home directory to open the file with the enter key.

**Comment by bpasero** [comment]
/confirmed

I can reproduce. Maybe a candidate?

**Comment by roblourens** [comment]
I'm pretty sure that this has been broken for several months at least. I can't reproduce in any recent build.
