### ISSUE TITLE
从win10开始菜单运行code命令，有黑色窗口残留

### ISSUE THREAD

**Issue by yunxu1019** [Microsoft/vscode#70139]
- VSCode Version: 1.32.1 (system setup)
- OS Version:Windows 10

    ![image](https://user-images.githubusercontent.com/15274374/54079957-5163fd80-4321-11e9-8ae8-7a65afd8ca74.png)

Steps to Reproduce:

1.打开开始菜单输入code
    ![image](https://user-images.githubusercontent.com/15274374/54079938-1f529b80-4321-11e9-9256-2165e194507b.png)

2.回车打开vscode
    ![image](https://user-images.githubusercontent.com/15274374/54079918-c3881280-4320-11e9-9552-a6cf2e6611f0.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
我已经不想翻译了……而且你的这些问题我一个也没遇到……
***
**A brief in English. I don't have this issue.**
> Use `code` to launch VS Code from the Start menu. There will be a residual window of cmd after VS Code starts.

**Comment by guobing1993** [comment]
😃
![Snipaste_2019-03-10_12-00-04](https://user-images.githubusercontent.com/22333388/54080492-1ddaa080-432c-11e9-94ae-34b078de7bb1.jpg)

**Comment by byyxx128** [comment]
@guobing1993
他用里面的“命令”启动的。但是我测试了很多遍没有这个问题。
Note the author used command "code" to launch VS Code rather than the shortcut.

**Comment by g-plane** [comment]
I don't think this is a bug, because you have launched VS Code from command line, not via Windows shortcut.

**Comment by joaomoreno** [comment]
If you reinstall VS Code, does the application (not the launcher) show up in the start menu?

**Comment by yunxu1019** [comment]
我用windows管理员用户安装，然后用windows普通用户使用，出现这种情况

**Comment by yunxu1019** [comment]
从开始菜单运行`code.cmd`，我更希望没有多出一个黑色窗口

**Comment by joaomoreno** [comment]
Can you install VS Code with your user, instead of with Administrator?
