### ISSUE TITLE
add typescript-language-features extension api typing

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#70133]
Issue Type: <b>Feature Request</b>

add typescript-language-features extension API typing for other extensions

```typescript
  const extension = extensions.getExtension("vscode.typescript-language-features");

  if (!extension.exports || !extension.exports.getAPI) {
    return;
  }

  const api = extension.exports.getAPI(0);
  if (!api) {
    return;
  }
```

https://github.com/Microsoft/vscode/blob/6cc7eea6ed353d6dc433252d1cbd00edb7e7d68c/extensions/typescript-language-features/src/api.ts#L1-L36

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

**Comment by mjbvz** [comment]
No plans to do this in the next six months as the api is very specialized and there are no plans to expand it further

**Comment by rubengmurray** [comment]
Is there any way to get the TypeScript version being used by VS Code via this extension's APIs? It appears that none of that is exposed?

**Comment by mjbvz** [comment]
@rubengmurray Please don't post on issues that have been closed for 3 years
