### ISSUE TITLE
VS Code persists across multiple desktops on macOS

### ISSUE THREAD

**Issue by KMFSousa** [microsoft/vscode#70131]
- VSCode Version: Version 1.31.1 (1.31.1)
- OS Version: Mojave 10.14.2

Multiple Desktops exist to partition your tasks and help with organization. Keeping VS Code appearing on all Desktops defeats this point.

Steps to Reproduce:
1. Open VS Code
2. Open multiple desktops 
3. Open multiple instances of VS Code with different Workspaces (possibly not needed)
4. 4 finger swipe to the other desktops
5. Observe VS Code is still there on other desktops

Does this issue occur when all extensions are disabled?: Yes

Possibly related to Issue #58978 and the closed Issue #56845. Needs testing with insider builds (Help needed here).

**Comment by tinchodipalma** [comment]
This worked for me: https://github.com/Microsoft/vscode/issues/56845#issuecomment-416243880

**Comment by kevin-chau** [comment]
@tinchodipalma's worked for me (definitely just a user error, and not a vscode bug).

@KMFSousa Let's close this one?

**Comment by KMFSousa** [comment]
It’s possible the default setting here is what needs to change. If not then yes let’s close it.
