### ISSUE TITLE
cannot close the peek problem display

### ISSUE THREAD

**Issue by GoodMexicanSir** [Microsoft/vscode#70138]
Issue Type: <b>Bug</b>

1. Generate a problem
2. Hover the cursor to the problem and select the Peek Problem button
3. Close the Peek Problem display
4. If we try step 2 for the same problem it won't open
5. It can be opened again using step 2 with another problem or Alt+F8 however it won't show the navigation buttons.

![imagen](https://user-images.githubusercontent.com/26801459/54078181-8e7cb100-4289-11e9-8f0c-71a1104c7f15.png)
![imagen](https://user-images.githubusercontent.com/26801459/54078182-93416500-4289-11e9-8e52-d89918809523.png)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
Fixed.
