### ISSUE TITLE
Ctrl+C does not kill processes in EXTERNAL terminal

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/vscode#70146]
Version: 1.32.1 (system setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open vscode
2. Launch *external* terminal using hotkey (Ctrl+Shift+C)
3. Launch any process in the terminal
4. Ctrl+C in the terminal window does not kill the process

This is dup of #25195 which is still happening for me in the latest version

**Comment by Tyriar** [comment]
Are you using the 64-bit version of VS Code and what's in your settings.json file?

**Comment by oliverjanik** [comment]
Yes 64 bit (based on Win Task manager)

My user settings.json

```
// Place your settings in this file to overwrite the default settings
{
    "files.trimTrailingWhitespace": true,
    "window.zoomLevel": 0,
    "editor.formatOnSave": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.settings.editor": "json"
}
```

**Comment by oliverjanik** [comment]
Came back and can't reproduce, go figure. I'll reopen if it happens again.

For posterity VS is 64 bit. My settings.json:
```
// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 0,
    "workbench.iconTheme": "vs-seti",
    "dart.debugSdkLibraries": false,
    "dart.debugExternalLibraries": false,
    "editor.lightbulb.enabled": false,
    "editor.formatOnSave": true,
    "explorer.confirmDelete": false,
    "rust-client.channel": "stable",
    "terminal.external.windowsExec": "",
    "workbench.settings.editor": "json",
    "workbench.settings.useSplitJSON": true
}
```
