### ISSUE TITLE
Package for Solus Linux

### ISSUE THREAD

**Issue by tecosaur** [Microsoft/vscode#70149]
It would be good if VSCode could be packaged for Solus. Currently, the OSS version is used, but that introduces a few quirks that would be nicer to not have to deal with.

Solus is currently #&#8203;8 on distrowatch so while it may no be the biggest out there, it is definately popular.

**Comment by joaomoreno** [comment]
Unfortunately we can't tackle them all. This is why we make a ZIP download available.
