### ISSUE TITLE
vscode.workspace.openTextDocument not work

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#70152]
Issue Type: <b>Bug</b>

``vscode.workspace.openTextDocument`` not work

```typescript
    vscode.workspace
      .openTextDocument({
        language: "markdown",
        content: "# hello world"
      })
      .then(() => {
        console.log("open...");
      });
```

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.2.2
vscode-auto-schema|axe|0.1.0
vscode-comment-autocomplete|axe|0.4.1
vscode-gpm|axe|2.1.2
vscode-npm-import-package-version|axe|0.4.2
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
markdown-yaml-preamble|bie|0.0.2
EnglishChineseDictionary|Cod|0.0.11
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
flow-for-vscode|flo|1.1.0
terminal|for|0.0.10
todo-tree|Gru|0.0.124
vscode-nginx-conf-hint|han|0.1.0
svgeditor|hen|2.9.0
npm-dependency-links|her|1.0.1
comment-translate|int|1.0.0
statusbarerror|Joe|0.3.0
docthis|joe|0.7.1
intellij-idea-keybindings|k--|0.2.31
vscode-colorize|kam|0.8.8
nim|kos|0.6.3
graphql-for-vscode|kum|1.13.0
git-indicators|lam|2.1.1
git-graph|mhu|1.4.2
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.32.4
cpptools|ms-|0.21.0
Go|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-gn|npc|1.0.0
vetur|oct|0.16.2
indent-rainbow|ode|7.3.0
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.3
nginx-formatter|ray|0.0.4
vscode-sort-json|ric|1.13.0
extension-update-reporter|ryu|1.0.2
px-to-rem|sai|1.2.7
bash-beautify|sha|0.1.1
vscode-nginx|sha|0.6.0
trailing-spaces|sha|0.2.11
gitconfig|sid|2.0.0
node-dependencies-view|sql|0.0.2
code-spell-checker|str|1.6.10
tabnine-vscode|Tab|1.1.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.4
vscode-todo-highlight|way|1.0.4

</details>

**Comment by usernamehw** [comment]
```typescript
vscode.workspace
    .openTextDocument({
        language: "markdown",
        content: "# hello world",
    })
    .then(document => {
        console.log("open...");
        vscode.window.showTextDocument(document);
    });
```

**Comment by axetroy** [comment]
@usernamehw 
I am sorry. I forget it.
