### ISSUE TITLE
Visual Studio issue with Network Drive in VPN

### ISSUE THREAD

**Issue by ingcarlosperez** [Microsoft/vscode#70159]
Issue Type: <b>Bug</b>

I have a project in a network drive and I connect with VPN.
In vscode 1.30 I work with any problems. After the last upgrade vSCode 1.32.1 take a long time to open the project and files.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10

</details>

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/70143
