### ISSUE TITLE
JSDoc doesn't support methods that are inside of a context

### ISSUE THREAD

**Issue by thoughtsunificator** [Microsoft/vscode#70162]
Issue Type: <b>Bug</b>

1. Initialize an object
2. Give the object a method with at least one parameter
3. Type "/**" above the method and press enter

Actual:
The comment block is not pre-filled with our parameter

![Animated GIF](https://i.imgur.com/QFKolTL.gif)

Expected:
The comment block should be pre-filled with our parameter

![Animated GIF](https://i.imgur.com/nP67RxX.gif)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|2.15.1
vscode-gist|ken|3.0.3
vetur|oct|0.16.2
nunjucks|ron|0.2.3

</details>

**Comment by mjbvz** [comment]
If you are adding a comment before `obj`, I don't think it is expected that params for `myMethod` should be added; the jsdoc should be on the direct element you are trying to comment 

https://github.com/Microsoft/TypeScript/issues/27638 tracks why commenting before `obj.x = ` also does not work

**Comment by thoughtsunificator** [comment]
I'm not making up anything that's how things worked in the other code editor I used.

**Comment by thoughtsunificator** [comment]
Sorry my gifs missed the point...

![https://i.imgur.com/5zEDRsJ.gif](https://i.imgur.com/5zEDRsJ.gif)
(sublime)

This is not working in vscode.
