### ISSUE TITLE
Stopping debugging while on a breakpoint crashes vscode

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7016]
- VSCode Version: Version 1.2.0-alpha, Commit 2833eb9d664db9c5a77bdf5fb19d7d7fefd4653c
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Debug an extension
2. Put a breakpoint
3. Hit the breakpoint
4. Press stop debugging button

**Comment by jrieken** [comment]
@weinand candidate?

**Comment by weinand** [comment]
@Tyriar when I press the stop debugging button, the VS Code [extension development window] closes but VS Code stays open. This is the expected behaviour.
Are you seeing something different?

**Comment by Tyriar** [comment]
This happened twice in a row while I was doing general extension development, I was hoping the steps would be more reliable. It definitely happened though, the window grayed out after a short period and then crashed.

**Comment by weinand** [comment]
@Tyriar so you mean: all VS Code windows (as opposed to just the extension host window) closed after pressing the stop button?

**Comment by weinand** [comment]
@isidorn any idea why pressing stop could crash VS Code?

**Comment by Tyriar** [comment]
I had code alpha running full screen in the foreground and the extension host in the background. I hit the stop button and all windows closed after about 5-10 seconds. I'm not sure if the extension host closed first or not as it was in the background.

**Comment by Tyriar** [comment]
I just tried 2 more times, no more repro. Maybe I hit some narrow edge case?

**Comment by isidorn** [comment]
@weinand stop for debugging extension host development does nothing special on my side. We send the 'disconnect' request to node adapter. I believe then that the node adapter notifies the workbench to close the extension host window. It might be that in some edge case the workbench closes the wrong window - I know Ben has some funky logic of figuring out which window to close and there might be a flaw for some use cases.

**Comment by weinand** [comment]
@bpasero may be the 'funky logic' has an issue with fullscreen mode?

**Comment by isidorn** [comment]
@weinand as far as I know ben uses workspace resource uris to identify each vscode window. Fullscreen mode has no influence here.
Ben can correct me if I am wrong

**Comment by weinand** [comment]
I could not reproduce the issue in Elementary OS and Ubuntu 15.10.
Currently I'm installing Ubuntu 16.04...

**Comment by bpasero** [comment]
Are we really sure this is a native crash and not another edge case where I just close the window? @Tyriar do you get a core dump?

**Comment by Tyriar** [comment]
@bpasero no I didn't

**Comment by bpasero** [comment]
Ok so it might be not a native crash. Actually one way to find out is to have a dirty file in the debugger to see if you get a prompt on shutdown. 

Anyway, steps to reproduce are needed to debug this.
