### ISSUE TITLE
workflow to support introductory CS courses...

### ISSUE THREAD

**Issue by zdodds** [Microsoft/vscode#70163]
Hello! I'm Zach Dodds; I teach introductory CS at the Claremont Colleges (Harvey Mudd specifically; we serve all 5 sibling colleges.)

VSCode brilliantly fills the space created by Sublime (which, institutionally, is tricky to use). 

One feature that would make VSCode more attractive for us (and, one suspects, all introductory instructors) is a workflow that allows an instructor (me!) to customize how VSCode works when their students download and install it. The key is a configurability that does not require building -- at least not yet -- a sophisticated conceptual model of all the wonderful features of VSCode. Right now, every student at Mudd and -- well, we're converging to every student at the other colleges -- downloads and uses VSCode. If there were a conceptually-zero-measure workflow for default-setting, that would be wonderful. The current defaults involve many too many helpful annotations, e.g. full pop-up docs with signature, docstrings, and annotations every time a student hovers over the print command in Python. This is helpful to some users, but is outright counterproductive for the goal of introductory computing. (It's worth noting that, in 2019, that goal is absolutely _not_ to increase the number of software engineers.)

We have created a json file of personal settings that offers the kind of streamlined experience we would like our introductory (first-day) students to have. (And, to be honest, it more effectively counters many stereotypes about the essential nature of computing.) If there were a  "apply the settings from this url" or "from this external file" menu option: Yay! Done! Or something with the same cognitive load, i.e., none. (Telling are the contortions cs50 takes to insulate (Harvard!) students from in-situ software tools.)

Many thanks -- and thanks to SIGCSE's Microsoft representatives who suggested I post this idea here... .

**Comment by joaomoreno** [comment]
You can configure a [portable Code](https://code.visualstudio.com/docs/editor/portable) and distribute it. Portable mode is our answer for use cases such as these.
