### ISSUE TITLE
breakpoints stopped working after update to (1.32.1)

### ISSUE THREAD

**Issue by mgrybyk** [Microsoft/vscode#70160]
- VSCode Version: Version 1.32.1 (1.32.1)
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. have project that spawns child processes
2. add breakpoint to any place, main or child process.

Does this issue occur when all extensions are disabled?: Yes

NOTE:
- downgrading to 1.31.1 resolves the problem 
- tried on different systems

**Comment by Eli-Goldberg** [comment]
Probably duplicate of #70080

**Comment by mgrybyk** [comment]
Most likely

**Comment by Hufe921** [comment]
I have the same question

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/70080
