### ISSUE TITLE
Rename terminal command doesn't persist after running a command in the terminal

### ISSUE THREAD

**Issue by lanzkron** [Microsoft/vscode#70164]
Issue Type: <b>Bug</b>

* Rename an integrated terminal 
   * CRL-Shift-P Terminal: Rename (to anything e.g. `Plonk`)
* (Terminal is renamed correctly)
* Run a command in the terminal (e.g. `ls`)
* (Terminal's name has reverted to "bash")

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.67GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
plantuml|jeb|2.10.6
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.5.2
code-spell-checker|str|1.6.10

</details>

**Comment by jeanp413** [comment]
Same as #68287 . It will be fixed for the march release.
