### ISSUE TITLE
Strange hover in theme picker

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#70166]
Issue Type: <b>Bug</b>

1. Open extension details
1. Select some text?
1. Open theme picker
1. 🐛 There's 1 focused element and 1 hover, but the mouse is outside of picker

![demo](https://user-images.githubusercontent.com/9638156/54087931-2f8e6900-4369-11e9-878e-0f809313e6e3.gif)

VS Code version: Code - Insiders 1.33.0-insider (9b849d9de7168eb4f685823bf9b9e27a0a8dae74, 2019-03-08T06:59:35.464Z)
OS version: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
Seems to be related to webviews and mouse events.

**Comment by bpasero** [comment]
@usernamehw does this only reproduce with release notes text selected or also with normal editors?

**Comment by bpasero** [comment]
This looks a lot like https://github.com/Microsoft/vscode/issues/64955

**Comment by kanlukasz** [comment]
This blue hover is not nice. I see this sometimes too

**Comment by usernamehw** [comment]
Only in #64955, the mouse is **INSIDE** the picker. This one only repros with webviews and much more unexpected.

**Comment by bpasero** [comment]
This is likely an upstream issue.
