### ISSUE TITLE
Release Notes 1.32.1 list.toggleKeyboardNavigation is hard to understand

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#70171]
The description for **Automatic Keyboard Navigation setting** is hard to understand without the right context or previous knowledge. Being a non-native english speaker, the use of certain scientific terms make it even harder to understand and further deepens the confusion. Visual clues such as screenshots or gifs of the feature would help a lot.

> ### Automatic Keyboard Navigation setting
> A new setting **List: Automatic Keyboard Navigation** controls whether lists and trees capture lexicographic keypresses in order to navigate and filter elements. If disabled, keyboard navigation becomes modal and the `list.toggleKeyboardNavigation` command will toggle its state. You can assign a specific keyboard shortcut to that command. For example, you could set it to be `/` and only after pressing `/`, will subsequent keypresses filter items in lists/trees. This setting defaults to enabled.

The keybinding, when added to my `keybindings.json` seemingly does not work, which makes it even harder to understand by "reverse engineering" it, ie. discover the feature by trying to simulate the behavior.

---

While gathering information for this suggestion, I ultimately discovered what the **Automatic Keyboard Navigation** is about and that I have actually used it since some previous release, but it was nonetheless frustrating to be not able to understand and visualise the introduced changes.

**Comment by joaomoreno** [comment]
This is an advanced setting which under 0.01% of our users should even be aware of. It is only interesting for users who have simple keyboard shortcuts in trees (eg <kbd>A</kbd> to create a file in the explorer) yet see those shortcuts collide with the new automatic filtering feature. The setting allows to disable the filtering feature so you can still have those shortcuts.

**Comment by ackvf** [comment]
Thank you for explanation and while I agree with what you say, it shouldn't mean that it is mentioned in the changelog just btw. VSCode team has set a high standard for explaining things in the changelog, which is great, but this one feature didn't meet the standard. I always read the changelog thoroughly to discover new features and options to better customize my workplace and I was really frustrated to not be able to better understand it.
