### ISSUE TITLE
@types/vscode for extension usage

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70175]
Ref: https://github.com/Microsoft/vscode-extension-vscode/issues/147

DefinitelyTyped, question for publishing old versions of types: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33738

Tracking here for testing later.

Current Problem:

- `vscode.d.ts` is fetched by running a script, `node_modules/vscode/install`
- The script depends on update server, so when it's down dependency install for extension fails
- yarn and npm can't fully cache the `vscode` module

Proposed solution:

- For each release of VS Code, we publish `@types/vscode` corresponding to the VS Code version. For example VS Code 1.32.0 => `@types/vscode@1.32.0`
- We seldom have breaking API changes, so most people can roll with `"@types/vscode": "^1.32.0"` and always get latest API.

VS Code related changes:

Extension authors can use `engines.vscode` to specify which versions of VS Code their extensions support. With this change, `engines.vscode` is no long used for fetching corresponding dts files.

I think this is a good change. I want to develop always with latest `vscode.d.ts` but if I don't use any new API, I can still support older versions. If I want to lock to specific versions of `vscode.d.ts` I can always use exact version such as `"@types/vscode": "1.32.0"`.

**Comment by octref** [comment]
We might be able to include proposed dts in `@types/vscode` too. @jrieken should we do this?

**Comment by jrieken** [comment]
> @jrieken should we do this?

Not sure, not the biggest fan because proposed api changes a lot and proposed api doesn't work with vscode-stable, only insiders. having it out and published might send the wrong mesage

**Comment by octref** [comment]
@jrieken And I assume we don't publish types for recovery build, such as 1.32.1, correct?

**Comment by jrieken** [comment]
Yeah, we shouldn't as the API does change

**Comment by octref** [comment]
We'll publish 1.14 to 1.32 `@types/vscode`. This has to be done one PR per version.

- Published: None
- To publish: 1.14+

Other tracking: 

- [ ] Update samples https://github.com/Microsoft/vscode-extension-samples
- [ ] Update beginner guide https://code.visualstudio.com/api

**Comment by octref** [comment]
@jrieken I plan to update the extension generator, so the template uses latest `engine.vscode` and `@types/vscode`.

Do you feel there's a need for vsce to check that the downloaded `vscode.d.ts` corresponds to `engine.vscode`? I can think of cases where author want to specify "fetched dts" and "supported VS Code version" differently, but during today's discussion there are concerns that users would use API only available in newer versions but forget to update `engines.vscode`.

**Comment by jrieken** [comment]
> Code version" differently, but during today's discussion there are concerns that users would use API only available in newer versions but forget to update engines.vscode.

Yeah, that's something something you get for free today and something we loose with the decoupling work. Yeah, I think adding a check to vsce and also some package.json validation makes sense.

**Comment by octref** [comment]
This [GitHub Action Event](https://developer.github.com/v3/activity/events/types/#createevent) seems the right fit for us to automate `@types` publishing. Creating `tag/<VERSION>` in `microsoft/vscode` could send a PR to `DefinitelyTyped`.

**Comment by octref** [comment]
`@types/vscode` 1.14 - 1.32 are published. More work is captured in https://github.com/Microsoft/vscode/issues/71048. I'll still focus on Vetur contribution in April and get back to this in May.

**Comment by octref** [comment]
No testplan item for this one because we aren't mentioning it publicly. When #71408 is shipped I'll create testplan item for it.

Verifier: Create a new extension, drop `postinstall` hook and `vscode` dependency and just use `@types/vscode`. Verify that  IntelliSense and error-checking works. Alternatively, create a JS extension and do **not** install `node_modules`. Verify that Automatic Type Acquisition works.
