### ISSUE TITLE
Intellisense and JavaScript

### ISSUE THREAD

**Issue by thewinterwolf220** [Microsoft/vscode#70178]
Issue Type: <b>Bug</b>

Try to import a core module, like fs. There won't be any autocompletion on the imported module. It worked till now.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.18.0-16-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 3028)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|7.73GB (2.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-standardjs|che|1.2.3
jshint|dba|0.10.20
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
node-module-intellisense|lei|1.5.0
LiveServer|rit|5.5.1
javascript-typescript|sou|0.0.7
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please provide more information about your project and what you are trying to do. How are you trying to trigger imports for example

Also, oes this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by thewinterwolf220** [comment]
It doesn't concern a particular project, but I've noticed that it still works on my old projects initialised with **create-react-app**
Packages are imported using the require function. I've also tried disabling all extensions, and using the last version of VS Code but it still doesn't work.

![intellisensejavascript](https://user-images.githubusercontent.com/41757349/54460462-eaec3e80-4769-11e9-83aa-4174ccdc3471.png)

**Comment by mjbvz** [comment]
I suspect that typing acquisition is not downloading that data for node. Can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `ti-xxx.log` file in it

 If you can share the log, I can take a look to see if anything stands out

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
