### ISSUE TITLE
vscode with urls: vscode://file return error "Unable to open file : resource is not available"

### ISSUE THREAD

**Issue by MagTun** [Microsoft/vscode#70177]
Issue Type: <b>Bug</b>

I use a local html file that I keep open in my browser  (chrome) which lists several links in this format: 
<a href="vscode://file/C:/Users/user/Desktop/script.py">python</a> 

All my links worked fine until a couple of days (weeks?) ago. 

It may follow a vscode update or a Windows Update. 

How can I troubleshoot this? 

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (4.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
transformer|dak|1.6.0
jupyter|don|1.1.5
xml|Dot|2.4.0
auto-close-tag|for|0.5.6
macros|ged|1.2.1
gc-excelviewer|Gra|2.1.29
beautify|Hoo|1.4.9
vscode-favorites|how|1.4.0
vscode-opn|lfu|1.1.2
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.3
vscode-fileutils|sle|2.13.5
vscode-autohotkey|sle|0.2.2
vscode-arduino|vsc|0.2.25
local-history|xyz|1.7.0

</details>

**Comment by adrianbj** [comment]
I just discovered this as well. If I downgrade to v1.31.1 they work as expected, so it's something in 1.32.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/69998
