### ISSUE TITLE
project-searching [^\s] (negated whitespace) doesn't match

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#70173]
Issue Type: <b>Bug</b>

I boiled down the issue to this: project-searching for negated whitespace char class doesn't match anything in closed files.

```
[^\s]
```

There regex doesn't need to be as simple as the above, of course, but if the above pattern is used anywhere within, it fails to match anything.

Cannot reproduce on ripgrep `0.8.1` and up.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.31.1 (system setup)
OS: Windows_NT x64 6.1.7601

Version: 1.33.0-insider (user setup)
OS: Windows_NT x64 6.1.7601

**Comment by roblourens** [comment]
This works fine for me. How about similar searches like `\S` or `\s`?

**Comment by dwelle** [comment]
I can still repro in latest insiders. To be sure, I'll re-state the steps:

1. create a file with contents `foo bar`
2. close the file
3. do a project search for either of the these two patterns:
    1. `[^\s]`
    2. `[\s]`

As from above, turns out the non-negated `[\s]` has the same problem --- matches nothing. It seems it needs to be a character class (`[]`), and it doesn't matter whether that character class includes other characters --- as long as it contains `\s`, it won't match anything.

Matching `\s` outside of character class works ok (e.g. `/\s/`).

`\S` (i.e. `[\S]`) works fine, as does `[ ]` (space) or `[\t]`, as well as their negations (`[^\S]`, ...).

**Comment by dwelle** [comment]
Hmm, ok this is significant --- can repro only when PCRE2 is enabled.

**Comment by roblourens** [comment]
Ok, I think I know what the issue is. I rewrite `\s` to prevent it from matching `\r` in CRLF files and it's not correct when inside a character class.

**Comment by roblourens** [comment]
I need to enable the `--crlf` flag on ripgrep and delete my hacks that worked around it.
