### ISSUE TITLE
Add approved badge for Azure DevOps

### ISSUE THREAD

**Issue by BernieWhite** [Microsoft/vscode#70187]
Can we please add badges for Azure DevOps to the list of approved badges.

Currently I have a URI like this: `https://<org>.visualstudio.com/<project>/_apis/build/status/<pipeline>?branchName=master`

**Comment by joaomoreno** [comment]
Have you tried using the up-to-date `dev.azure.com` domain?

**Comment by BernieWhite** [comment]
The list of approved badge domains is [here](https://code.visualstudio.com/api/references/extension-manifest#approved-badges) and neither is in the list.

**Comment by joaomoreno** [comment]
It's pretty fresh: https://github.com/Microsoft/vscode/issues/69874, but should work on the latest Insiders
