### ISSUE TITLE
Typing Errors on the "new Square(10, 3).width page

### ISSUE THREAD

**Issue by ManfordDSR** [Microsoft/vscode#70186]
Issue Type: <b>Bug</b>

In the readme file of the release notes for update 1.32.1, there are two typos in the spelling of "width -> 
widht" is what you have on the dialog box. It is on the "newSquare(10, 3) in the dialog box that is shown on the page.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.92GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by gregvanl** [comment]
Hi @ManfordDSR The mispelling is intentional in the screenshot to show that of the two possible fixes (correct the spelling or add a new property "widht"), the spelling fix is the "preferred" code action and listed first.
