### ISSUE TITLE
After save the cursor/focus is not on the document anymore

### ISSUE THREAD

**Issue by kenw232** [Microsoft/vscode#70183]
Issue Type: <b>Bug</b>

In Windows whenver I ALT-F -> Save to save my current file the document is not put into focus again afterwards.   I then have to reach for the mouse and click the document window again to get the cursor to start flashing again to resume editing.  Could not be more annoying.  Does this happen for everyone?

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3517UE CPU @ 1.70GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.42GB (11.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.2.2
multiline-find-and-replace|axl|0.0.1
php-autocomplete|bsc|0.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
php-snippets|heb|0.0.3
beautify|Hoo|1.4.9
favorites|kdc|2.4.5
indent-rainbow|ode|7.3.0
vscode-css-peek|pra|2.2.0
java|red|0.40.0
code-spell-checker|str|1.6.10
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.14.1
vscode-maven|vsc|0.15.0
JavaScriptSnippets|xab|1.7.2

(4 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
https://github.com/Microsoft/vscode/issues/70022#event-2191658354
