### ISSUE TITLE
NewFile NewFolder CopyFile PastFile does't work

### ISSUE THREAD

**Issue by zmicx** [Microsoft/vscode#70185]
Issue Type: <b>Bug</b>

Some cmd does't work as Title desc
the pic attached as follows

![image](https://user-images.githubusercontent.com/26269444/54097774-94d76e00-43ec-11e9-9964-5cc29d8a59c7.png)
![image](https://user-images.githubusercontent.com/26269444/54097790-a6b91100-43ec-11e9-8c99-84e25e36f371.png)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-project-generator|dan|1.1.1
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
unity-debug|Uni|2.7.2

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes please provide reproducable steps so we can also repro this on our machine. Also explain better what is the actuall issue here.
