### ISSUE TITLE
Cliakable links in terminal should ignore last `)`

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#70190]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/227713/54100634-68c2e980-43fa-11e9-9282-0cedd3e9424e.png)

then `CMD+Click` will open `http://localhost:8080/)`, the last `)` is unexpected

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gpm|axe|2.1.2
vscode-npm-source|dku|1.0.0
gitlens|eam|9.5.1
code-runner|for|0.9.7
search-node-modules|jas|1.3.0
vsliveshare|ms-|0.3.1284
node-modules-resolve|nau|1.0.2
text-power-tools|qcz|1.10.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/21125
