### ISSUE TITLE
Create user configuration to set a timeout for debugger connection.

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode#70192]
This is a feature request from the Python VS Code extension team, in response to customer feedback.

Due to startup times on various customer setups, the debugger startup time can become too long, and the debugger fails with a popup window like this:

![image](https://user-images.githubusercontent.com/11466735/54102860-4f348a00-4387-11e9-90bb-9f0781201e6a.png)

The issue is caused by a combination of:
- A customer's terminal can take a large amount of time to startup (Group policy settings, antivirus).
- A Python environment can take a little extra time to start up.

See related issues: #60633, Microsoft/vscode-python#2752

## Reproduce this issue
*VS Code: 1.31.1*
*Python extension: 2019.2.x*

On Windows:

1. Install the Python extension
2. Create a workspace, add a single file `repro.py`, with the following content:
```python
def my_method():
    print(123)
    return 123

if __name__ == "__main__":
    my_method() # place breakpoint on this line.
```
3. Set your shell to Powershell (Open the command palette, type `Terminal: Select Default Shell`).
4. Open the terminal window (should be Powershell).
5. Open or create the file described by the `$PROFILE` environment variable.
6. Add the following code to the Profile file:
```ps
Start-Sleep -Seconds 20
```
7. Place a breakpoint on the call to `my_method()` (line 6).
8. Ensure all terminal windows are closed by clicking on the `Kill Terminal` icon until they are all gone.
9. Press `F5` to start the debugger.
   - If the timeout has not triggered, change the `Start-Sleep -Seconds x` to a higher value of x.

**Comment by weinand** [comment]
There is no "Timeout waiting for debugger connection" message anyway in VS Code. Are you sure that this Alert is originating from VS Code and not from the Python extension?
