### ISSUE TITLE
I cant bind ctrl+alt+d in keybinds

### ISSUE THREAD

**Issue by diedekerkhof** [Microsoft/vscode#70199]
Issue Type: <b>Bug</b>

I cant bind ctrl+alt+d in keybinds. When i try to set that combination it resets the field to only a D when i type the D

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vs-jokes|cam|0.0.2
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
vscodefy|iag|0.0.11
vscode-icons|rob|8.2.0
quokka-vscode|Wal|1.0.193
vscode-js-console-utils|wht|0.7.0

</details>

**Comment by roblourens** [comment]
Please see this page for troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexandrudima** [comment]
@diedekerkhof What is shown when you try to press the desired keys? e.g.

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by diedekerkhof** [comment]
Hello sir/madam,

First of all thanks for reaching out to me.
When i press ctrl+alt+d windows places this sign 'ð' and that brakes the
input field, when i press these keys in the input box it resets my input so
that the box is empty or just shows the letter d.
I am running on windows 10

thanks in advance,
Diede Kerkhof

Op wo 27 mrt. 2019 om 16:53 schreef Alexandru Dima <notifications@github.com

**Comment by alexandrudima** [comment]
Thanks for replying. This indicates that `ctrl+alt+d` does not reach VS Code? Have you been able to use this keybinding successfully in other operating systems? Are you also trying with the left `ctrl`, left `alt`, and then `d` ?

**Comment by diedekerkhof** [comment]
I have not used it on other operating systems but i do use both left ctrl
and left alt

Op wo 27 mrt. 2019 om 20:54 schreef Alexandru Dima <notifications@github.com

**Comment by alexandrudima** [comment]
@diedekerkhof Sorry I had a typo. Did you manage to use ctrl+alt+d in any other applications on the same OS?
