### ISSUE TITLE
QuickPickOptions.onDidSelectItem hides the PickList when another document is loaded in the view

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#7019]
- VSCode Version: 1.1.1
- OS Version: Windows

Steps to Reproduce:

1. Defines a `onDidSelectItem` function that will open and show a text document, like this:
```typescript
  let options = <vscode.QuickPickOptions>{  
    placeHolder: 'Type a line number or a piece of code to navigate to',
    matchOnDescription: true,
    onDidSelectItem: item => {
      if (item.detail.toString().toLowerCase() == vscode.window.activeTextEditor.document.uri.fsPath.toLowerCase()) {
        revealLine(parseInt(item.label) - 1);
      } else { // here is the problem
        let uriDocument: vscode.Uri = vscode.Uri.file(item.detail.toString());
        vscode.workspace.openTextDocument(uriDocument).then(doc => {
          vscode.window.showTextDocument(doc).then(editor => {
             // any code can be added here
             //revealLine(parseInt(item.label) - 1);
          });
        });
      }
    }
  };
```
2. Shows a `vscode.window.showQuickPick`, with that `vscode.QuickPickOptions`, like this:
```typescript
  vscode.window.showQuickPick(items, options).then(selection => {
    // do anything
  });
```
Whenever the `else` code block in `onDidSelectItem` function is reached (wich will load another document) the PickList disappears. (no matter the code added inside `showTextDocument`, even nothing).

I don't know if this is the expected behavior or not, but it would good that the PickList remains visible. With that, I could have a _preview_ of other documents.

Thanks in advance

**Comment by jrieken** [comment]
Today, quick pick closes on focus lost. We should add an option to prevent that.

**Comment by jrieken** [comment]
@bpasero @weinand This might also be useful for the process picker work

**Comment by bpasero** [comment]
@jrieken @weinand this is already an option for the picker, see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L389

**Comment by weinand** [comment]
@jrieken Then this only needs to be surfaced in vscode.d.ts.

**Comment by jrieken** [comment]
@alefragnani Can you try this with the `preserveFocus` when calling `showTextDocument`? It should not move focus away from the quick pick widget so that it stays open.

**Comment by alefragnani** [comment]
@jrieken It works perfectly, thanks :+1: 

By the way, Is there an API to show items in the pick list, just like the _Go to Symbol_, where you have some kind of _groups of items_ (that appears when you type '@:' in the pick list)? 

![vscode-pick-list-like-go-to-symbol](https://cloud.githubusercontent.com/assets/3781424/15649770/653e93ac-264a-11e6-8dda-4c0af353f65c.png)

Currently, I'm using the `QuickPickItem.detail` property to show the file name of the item in the pick list, but the _Go to Symbol grouping_ approach is much better, because it does not _repeat_ that info for every item in the pick list.

Thanks in advance

**Comment by bpasero** [comment]
This is something we do support from within code but not exposed as API. The related option for a picker entry is in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/quickopen/common/quickOpenService.ts#L18

We use it e.g. if you click on the whitespace picker in the status bar.

**Comment by alefragnani** [comment]
@bpasero, That´s exactly what I mean. Any chances in exposing this API?

**Comment by jrieken** [comment]
Unsure - I don't like that fact the separator/group must be repeated on each item. Tho I also don't like the idea of a complex data structure. For now, I would opt to keep this simple

**Comment by bpasero** [comment]
The way it works currently with string array as pick items is easy and would probably not allow for more complex things like groups and separators. For sure I would not just copy the internal API we have and make it public.

**Comment by alefragnani** [comment]
I didn't mean to expose _that_ API, but only use the `separator` attribute idea. Sorry about the misundertandig. 

I didn't look at the source to see how that API is related to the _published_ API, so I don't know hard would be to publish a `separator/grouping` attribute and use it as in @bpasero example (whiltespace picker). But since the same idea appears in other pickers too, like _Go to Symbol_, _Open Recent_, it's something that I was expecting to be able to use. Specially because it keeps the UI cleaner.

@jrieken I totally agree about _keep this simple_ :+1:

**Comment by jrieken** [comment]
Sorry, but fell off the plan for June

**Comment by alefragnani** [comment]
I noted that it also lost the **Backlog** tag/milestone. Is that right?

**Comment by jrieken** [comment]
Backlog or No milestone is the same to me

**Comment by alefragnani** [comment]
Ah, ok.. Thanks :+1:

**Comment by jrieken** [comment]
We did add [`ignoreFocusOut`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1368) flags for quick pick and input

**Comment by bpasero** [comment]
Marking as verification-found due to https://github.com/Microsoft/vscode/issues/11442

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/18203960/7097f8ea-711a-11e6-9077-ba493108e0e4.gif)

@alefragnani if you `preserveFocus` when opening an editor you can get this to work already today without the new `ignoreFocusOut` option

**Comment by alefragnani** [comment]
@bpasero yes, I'm already using it as @jrieken [suggested in May](https://github.com/Microsoft/vscode/issues/7019#issuecomment-222448065) :+1: 

I think the issue remained open not based in the original post (about _preserve focus_) but because of [expose grouping API](https://github.com/Microsoft/vscode/issues/7019#issuecomment-222484365). It lost the **June** tag/milestone and only last week new comments were added. 

Would be valid to re-open (add a new issue) for that _grouping feature_ in Pick List?

**Comment by jrieken** [comment]
Let's track the grouping in a new item.
