### ISSUE TITLE
How to clean opened png file's infomation in Status bar

### ISSUE THREAD

**Issue by yzw** [Microsoft/vscode#70194]
Issue Type: <b>Bug</b>

In status bar, If i opened png file, status bar shows file size and dimensions. Then i opened an other text file. The image size and dimensions always show the status bar. Thanks a lot

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.2.0
githistory|don|0.4.6
Go|ms-|0.9.2
vscode-docker|Pet|0.5.2
markdown-all-in-one|yzh|2.1.1

</details>

**Comment by mittalyashu** [comment]
I am using insider build and I don't see is this bug anywhere.

**Comment by yume-chan** [comment]
I can reproduce this, after opened a png file, now my status bar looks like this.

![image](https://user-images.githubusercontent.com/1330321/54111186-37f4ab80-441e-11e9-9540-7da7f45cf6c1.png)

Version: 1.33.0-insider
Commit: 9b849d9de7168eb4f685823bf9b9e27a0a8dae74
Date: 2019-03-08T06:59:35.464Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
@mjbvz another strict null related regression. I see `onMetadataChange` being called with `metadata = undefined` but later the state is not updated due to another `typeof` check...

**Comment by bpasero** [comment]
Since this reproduces in stable, setting candidate.

**Comment by cedric05** [comment]
can i work on it?
