### ISSUE TITLE
New explorer: creating 2 folder in a row results in hidden input box

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70198]
Steps to Reproduce:

1. open a folder with some files
2. click on a root file
3. click on the "New Folder" action in the view
4. type some name
5. click it again to create a second folder

=> 🐛 
![image](https://user-images.githubusercontent.com/900690/54115895-d4528a00-43ed-11e9-9885-35c382a41b6f.png)

//cc @joaomoreno

**Comment by isidorn** [comment]
I can repro. Good catch. This is due to the blur timeout witchcraft which we do [here](https://github.com/Microsoft/vscode/blob/84a6d429bba083b6a8648933315729f963731d3e/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L218)

**Comment by isidorn** [comment]
Fixed it with the same witch craft it is built upon, increased timeout for ignore blur events from 0 to 100 ms.
