### ISSUE TITLE
When I click on a link in VSCode, browser opens with a URL which seems to be the link, but run through decodeURIComponent

### ISSUE THREAD

**Issue by Maples7** [Microsoft/vscode#70197]
- VSCode Version: 1.32.1
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. write URL in editor or inner terminal：

> https://openapi.alipaydev.com/gateway.do?method=alipay.trade.page.pay&app_id=2016092500596274&charset=utf-8&version=1.0&sign_type=RSA2&timestamp=2019-03-11%2016%3A37%3A35&notify_url=http%3A%2F%2Fhansel-dev.seniverse.com%2Fapi%2Fv1%2Ftransactions%2Falipay%2Fnotify&return_url=http%3A%2F%2Fhansel-dev.seniverse.com%2Falipay%2Fresult&sign=BjeSSFwNnIjTRqJGLWCsU4azsfkQhU4mpO2EXuutIKTDCZU5UXYTkJDKFf6yGiCb%2FhH9OFEsfgQdc2pbk17gSUOopeuptDnBjXVl5s5thFXn%2BytWK1JeKfZsRjH4Ta%2FGP2prlaZelIElcmFUPGpghgSvXZVnVqHG3QL7xDhWZ%2F%2Bx9rqq4lr5xVegDsOtdkcWDi8YjuPIjjtigU5MpXvcjjnlA5kwJ%2BI9tV6FpMAo7sPAjTRh4s1iC3B%2BWEpkHAuGDZVg0qX6UMZDg%2BLql%2FytKuQwnrEf4CLYOeTKJVjl4hwcSI%2BqIOPoCrAn43f8%2FTLqzwhnfwbcGF1P0KzQaJYO5Q%3D%3D&alipay_sdk=alipay-sdk-nodejs-3.0.4&biz_content=%7B%22out_trade_no%22%3A%22201900123Test%22%2C%22product_code%22%3A%22FAST_INSTANT_TRADE_PAY%22%2C%22total_amount%22%3A%220.01%22%2C%22subject%22%3A%22%E5%BF%83%E7%9F%A5%E5%A4%A9%E6%B0%94%E6%9C%8D%E5%8A%A1%E8%B4%B9%22%2C%22body%22%3A%22%E5%BF%83%E7%9F%A5%E5%A4%A9%E6%B0%94%E4%B8%BA%E4%BD%A0%E6%8F%90%E4%BE%9B%E5%87%86%E7%A1%AE%E3%80%81%E7%A8%B3%E5%AE%9A%E3%80%81%E5%85%A8%E9%9D%A2%E7%9A%84%E5%A4%A9%E6%B0%94%E6%95%B0%E6%8D%AE%E6%9C%8D%E5%8A%A1%E3%80%82%22%7D

2. cmd + click to open it in browser, the url which seems to be decoded becomes: 

> https://openapi.alipaydev.com/gateway.do?method=alipay.trade.page.pay&app_id=2016092500596274&charset=utf-8&version=1.0&sign_type=RSA2&timestamp=2019-03-11%2016:37:35&notify_url=http://hansel-dev.seniverse.com/api/v1/transactions/alipay/notify&return_url=http://hansel-dev.seniverse.com/alipay/result&sign=BjeSSFwNnIjTRqJGLWCsU4azsfkQhU4mpO2EXuutIKTDCZU5UXYTkJDKFf6yGiCb/hH9OFEsfgQdc2pbk17gSUOopeuptDnBjXVl5s5thFXn+ytWK1JeKfZsRjH4Ta/GP2prlaZelIElcmFUPGpghgSvXZVnVqHG3QL7xDhWZ/+x9rqq4lr5xVegDsOtdkcWDi8YjuPIjjtigU5MpXvcjjnlA5kwJ+I9tV6FpMAo7sPAjTRh4s1iC3B+WEpkHAuGDZVg0qX6UMZDg+Lql/ytKuQwnrEf4CLYOeTKJVjl4hwcSI+qIOPoCrAn43f8/TLqzwhnfwbcGF1P0KzQaJYO5Q==&alipay_sdk=alipay-sdk-nodejs-3.0.4&biz_content=%7B%22out_trade_no%22:%22201900123Test%22,%22product_code%22:%22FAST_INSTANT_TRADE_PAY%22,%22total_amount%22:%220.01%22,%22subject%22:%22心知天气服务费%22,%22body%22:%22心知天气为你提供准确、稳定、全面的天气数据服务%E3%80%82%22%7D

with that, I got the wrong parameter `sign`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/25852
