### ISSUE TITLE
The window is no longer responding

### ISSUE THREAD

**Issue by us-concrete-sdiwan** [Microsoft/vscode#70207]
Issue Type: <b>Bug</b>

The window is no longer responding

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 4, 4|
|Memory (System)|8.00GB (0.69GB free)|
|Process Argv|-psn_0_598162|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
tslint|eg2|1.0.43
local-history|gay|0.0.3
compareit|in4|0.0.2

</details>

**Comment by roblourens** [comment]
Please give as much info as possible
