### ISSUE TITLE
monaco.d.ts generation flaky and unstable

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#70205]
Since the `monaco.d.ts`-generation has been changed (a few months ago) it has been flaky and unstable. Almost every change to `modes.ts` results in a broken build, like https://dev.azure.com/vscode/VSCode/_build/results?buildId=16050. This used to be a no-brainer and no problem at all and has significantly regressed.

**Comment by alexandrudima** [comment]
:+1: I think the usage of node's `fs.watch` is the culprit.
