### ISSUE TITLE
The pieces of code do not remain minimized when I give the save command.

### ISSUE THREAD

**Issue by RomuloDurante** [Microsoft/vscode#70202]
Issue Type: <b>Bug</b>

The VSCode is amazing, but recently, I started to have the following problem: I program in GO, and every time I give the command save the codes that are minimized (pieces of code) expand and I have to minimize them again. I'm not talking about minimizing windows, but rather parts of the same code I'm typing. TKS

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
html-slim-scss-css-class-completion|gen|1.5.12
beautify|Hoo|1.4.9
vscode-autoprefixer|mrm|2.2.0
Go|ms-|0.9.2
vscode-icons|rob|8.2.0
pdf|tom|0.5.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
I suspect you have `Format on Save` enabled. 

I'm not able to reproduce: Bare VSCode with Go and beautify extensions disabled.


Closed folding regions stay closed on save (I also tested with format on save)
![format-go](https://user-images.githubusercontent.com/6461412/54276420-9b511b80-458d-11e9-9d6d-74996de112bb.gif)
