### ISSUE TITLE
Shorten file paths that are displayed in the UI

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#7020]
- VSCode Version: 1.1.1- insider
- OS Version: win7

https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/14379813-usability-paths-in-work-list

Instead of full paths:
![2016-05-30_08h30_29](https://cloud.githubusercontent.com/assets/3082812/15640464/ef175546-2640-11e6-9f95-0e8a4e7e72f3.png)
Propose to do so, it's just more convenient:
![2016-05-30_08h34_17](https://cloud.githubusercontent.com/assets/3082812/15640493/508e3664-2641-11e6-964f-fbee8b8f7048.png)
Or do as in "Brackets"to show only differing part of the way
![2016-05-30_08h36_15](https://cloud.githubusercontent.com/assets/3082812/15640512/9648589c-2641-11e6-9fda-0d2193ef41de.png)

PS: Usability forever!

**Comment by bpasero** [comment]
This would probably apply throughout the UI.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
