### ISSUE TITLE
Open editors: new files are coming in a strange way

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70204]
Steps to Reproduce:

1. enable editor preview
2. double click some editors to open them pinned
3. open another editor

=> 🐛 the editor appears somewhere strange at first and is then sorted down?

 
![before](https://user-images.githubusercontent.com/900690/54119387-7b86ef80-43f5-11e9-968f-cd543815a006.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/67041
