### ISSUE TITLE
Detect currently installed version of dependency and range of versions available to be installed when hovering over a dependency in a node.js project's package.json

### ISSUE THREAD

**Issue by c4ss** [Microsoft/vscode#70203]
Currently when you hover over a dependency you get a box that looks like this

![image](https://user-images.githubusercontent.com/40792152/54118726-9fddce80-43eb-11e9-8f27-af653e634496.png)

Could there be more information in this box?

- Currently installed version from `package-lock.json` or `yarn.lock`
- Version that will be installed if you run `npm install` or `yarn`
- Version that will be installed from a fresh install (or `yarn --force`)

This would be helpful to avoid delving into `package-lock.json`/`yarn.lock` to discover versions and would help users improve their understanding of [npm's semantic versioning syntax](https://github.com/npm/node-semver)

**Comment by roblourens** [comment]
There are extensions that give more info, I think this would be best handled by an extension
