### ISSUE TITLE
VSCode doesn't launch at all on Windows

### ISSUE THREAD

**Issue by rjnfrazao** [Microsoft/vscode#70208]
When launching VSCode, the screen seems frozen with a black window. The screen was active as I was able to close by clicking on the top right of the window. 

Finally, I found this issue, not the same but somehow similar : "VSCode freezes when switching from Chrome to it #28709", so the fix for the time being opening using cmd : code --disable-gpu

But, my case wasn't related to switch from Chrome and also not freezing, just the screen opened was totally black, but still active.

The only application as far as I remember installed recently in my laptop was "Duet", an application to use the iPad as a second monitor.

![image](https://user-images.githubusercontent.com/40456619/54124564-1ad3d300-4446-11e9-9c38-0d79064be9a4.png)

I hope this helps other with similar problem. 

- VSCode Version: 1.32 (but happened in all previous version)
- OS Version: Windows 10 v1803

Steps to Reproduce:

1. Just trying to open the VSCode, either via icon or cmd.
2. Opens with a black screen. Nothing else.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Could you try to fill out the same checklist from the other issue to give us some more info?

Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`
