### ISSUE TITLE
Find panel in the guide (basic principles of use)

### ISSUE THREAD

**Issue by atiris** [microsoft/vscode#70210]
Issue Type: <b>Feature Request</b> (possible a bug?)

Missing description / documentation of Find panel in the VSCode manual (user guide).  
So I can't judge whether a particular behavior is OK or a bug. This request is a requirement to create these rules of Find panel behavior in the guide.

_In some cases VSCode shows nothing found, or that all the occurrences of the word was replaced with others but that is not true and that seems to me to be_ **a serious problem since VSCode is an editor.** _Regardless, I cannot say whether it is really a bug or not because there is no description how exactly Find panel should work._

I expected something like this:

### Find panel intialization phase

- If there is no selection, active word (with cursor) is copied into Find input after CTRL+F, Search in selection is disabled (since there is no selection evidently). (1a)
- After one word (or something smaller than 2 lines) is selected, CTRL+F open Find panel with selected string in input field and Search in selection is disabled. (1b)
- If more than 1 line is selected, after CTRL+F, nothing is copied into find input (if anything has previously been searched, it will remain preserved but marked for overwriting), Search in selection is active. (1c)

Currently not working: **1b, 1c**

### Find panel actions

Any of next steps must retain the original selection until the searched value is confirmed / selected or find panel is closed.

- If user type anything, find panel search for the first occurrence (from cursor, or in selection from beginning) and select it. Find panel has focus. (2a)
- If user press ENTER, find panel search the next occurrence and select it. Find panel has focus. (2b)
- If user press SHIFT + ENTER, find panel search for the previous occurrence and select it. Find panel has focus. (2c)
- If user press CTRL + ENTER (confirmation), active search selection is "transferred to the document", document get focus, active occurence is selected and find panel is closed (I do not know if it's possible, but I miss it now). (2d)
- If user press ALT + ENTER (confirmation) all occurences are selected, cursor is multiplied, document has focus, Find panel is closed. (2e)
- If user press ESC (cancellation), find panel will be closed, original selection is restored, so searching is canceled. (2f)
- If user navigate in occurences, enable or disable Find in selection or enable or disable any search feature like Match case, Match whole word or Regexp, original selection can not be changed. (2g)

Currently not working: **2d, 2f, 2g**  
Reproduce steps 2g: select line "ab aa ac aa ad ae aa af aa" press CTRL + F, type aa, Enable and disable Find in selection (result is 1 of 1, new selection is first "aa")

Is the required behavior of Find panel different? Where are the Find panel behavior rules described?

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:53:01.021Z)
OS version: Linux x64 4.20.14-200.fc29.x86_64

### This is probably a bug (example for case 1b and 2g)

But I'm not sure if it's the bug, as there is no description of how it works.

Changes in "Find panel" change (remove) my selection.  
I write it as a feature request because the Find panel behavior is not intuitive.

- Open code without extensions
- Type something. Example:

aaa aaa aaa aaa
bbb aaa aaa bbb
aaa aaa ccc ddd

- Press CTRL+F
- Select second line
- Type aaa into find text input field
- Click Find in selection

=> Only first aaa is selected, result is 1 of 1.

Expected behavior is to not break selection with any settings in find panel. 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|30.83GB (18.59GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
In the future, please file one issue per bug/request, it makes things easier to follow. I get what I expect with 1b and 1c, please expand on "not working".

2d - I think you just want 'esc'

I don't think I understand 2g

**Comment by atiris** [comment]
Hi, I understand 1 bug/request per file principle, sorry, main part of this request is missing description of how exactly the Find panel should work (I can't find it in the guide).  
Until it is in the manual, I can't tell if any behavior is wrong or not, so I didn't want to report it as a bug, just report a request to add documentation and point out the peculiarities of using this panel.

Some examples in video - please turn on EN subtitles: https://youtu.be/1Nmew84CXgs

**Comment by atiris** [comment]
obsolete
