### ISSUE TITLE
Copy Paste, pasted text gets changed (re-formatted)

### ISSUE THREAD

**Issue by bhtw** [Microsoft/vscode#70215]
Issue Type: <b>Bug</b>

Hi

I don't know if this is a bug in VS Code or an extention, but pasted text gets changed.
Example, copying this text:

$payload = array("Result"=>"OK","Data"=>self::$headColumnNames);

Paste result differs, depending on where it is pasted.
Inside same function gives this result:
$payload = 
array("Result"=>"OK","D at a"=>  self:: $headColumnNames);

Inside another function gives this result:
$payload = 
array("Result"=>"OK ", "Data "=> se lf::$headColumnNames);

Note the way spaces are added in weird places.

Take note, that pressing cmd+z after paste, fixes the added spaces (!) --- maybe even more weird ... (?)

For now I have only seen this issue in a PHP project... 
I am not sure if it is valid for other script languages as well...

Is this issue triggered due to simular extentions "fighting" each other?

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (1.12GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
php-project|Fro|2.2.0
minify|Hoo|0.3.0
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.2.2
project-manager|ale|10.3.2
rtf|ale|2.0.0
angular1-code-snippets|ale|0.0.3
markdown-mermaid|bie|1.1.2
vscode-intelephense-client|bme|1.0.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
apacheconf-snippets|eim|1.2.0
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.1.29
beautify|Hoo|1.4.9
php-cs-fixer|jun|0.1.96
php-symbols|lin|2.1.0
vscode-apache|mrm|1.2.0
vscode-attrs-sorter|mrm|2.1.0
python|ms-|2019.2.5558
sublime-keybindings|ms-|4.0.0
vuejs-extension-pack|mub|1.1.3
php-docblocker|nei|1.7.0
vetur|oct|0.16.2
vuehelper|oys|0.1.0
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.3.0
flowmaker|spe|1.2.0
language-stylus|sys|1.11.0
bootstrap4-vscode|the|6.0.3
vscode-status-bar-format-toggle|tom|1.4.0
quokka-vscode|Wal|1.0.193
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0
editorzoom|zol|1.0.3

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It sounds like you have a formatter installed and probably `editor.formatOnPaste` enabled? I see you have several PHP-related extensions
