### ISSUE TITLE
Avoid using fsPath on a non-file URI

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#70217]
Using fsPath on a non-file URI is not very nice and kind of unspecified.

https://github.com/Microsoft/vscode/blob/c7ffcb9d0dc81252879cd82741067aa8379dfa5c/src/vs/platform/windows/electron-main/windowsService.ts#L423

**Comment by joaomoreno** [comment]
@aeschli As you've seen, this is the feature that allows users to open files based on product URLs, which have their scheme locked to `vscode` or `vscode-insiders`. Eg:

```
vscode://file/Users/joao/Desktop/file.txt
```

What is the recommendation here, if `fsPath` isn't allowed?

**Comment by aeschli** [comment]
Code got refactored in the meantime.
