### ISSUE TITLE
VSC/VSCI is calling silent az764295.vo.msecnd.net without using proxy settings

### ISSUE THREAD

**Issue by michtoen** [Microsoft/vscode#70227]
Behind an enterprise proxy, the VSC and the VSCI will try to call 2 times az764295.vo.msecnd.net:

Using Fiddler, you get:

CONNECT az764295.vo.msecnd.net:443 HTTP/1.1
Host: az764295.vo.msecnd.net:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.31.1 Chrome/66.0.3359.181 Electron/3.1.2 Safari/537.36
Proxy-Authorization: Basic Og==

- this happens on different mashines on win7 and win10 
- it ignores the HTTP_PROXY/HTTPS_PROXY settings with auth ( like http://user:pass@proxy:8080 )
- it will ignore the proxy settings from VSC itself

We tested that with a tricky setup, using an auth based proxy in the windows env settings but a different one inside the settings file, which did not need any auth. Both will fail because VSC is direct callign the 443 port, as the fiddler output shows.

The szenario is easily to test on a non proxy system by using fiddler and running it with a blind proxy.
After starting the VSC (and the insider), it will show after 2-3 seconds 2 calls to the host above on 443.

We already tried to disable it in the settings, but it seems not be invoked by something configurable.
Which also not fix the main problem, that this calls are either not documented but also did not respect any proxy and auth settings.

Naturally, this behaviour will rise some question to any company security.

**Comment by joaomoreno** [comment]
Did you give this document a read? https://code.visualstudio.com/docs/setup/network

**Comment by michtoen** [comment]
I did some tests and found, that when i add the cmd line to the VSC call, it works in terms VSC use the right proxy settings.

"--proxy-server=http://USER:PASS@DOMAIN:8080"

I used the same proxy string as set in the windows env as HTTP/S_PROXY and also as set in the settings.json without success. Only as cmd line part it works.

As we have an enterprise proxy system, my proxy string looks like "http://username%40company.com:PASS@PROXY_IP:PORT", with a percent encoded @.
But I did, as noted, also a test with a non auth proxy in the settings.json, which was ignored.

I tried this funny and wild collection but it did not stop the 2 calls home:

{
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "update.enableWindowsBackgroundUpdates": false,
    "workbench.settings.enableNaturalLanguageSearch": false,
    "update.channel": "none",
    "workbench.enableExperiments": false,
    "extensions.autoCheckUpdates": false,
    "extensions.autoUpdate": false,
    "extensions.showRecommendationsOnlyOnDemand": true,
    "update.showReleaseNotes": false,
    "git.autorefresh": false,
    "http.proxy": "...."
 }
I really like to point out that our all interest must be not to make the proxy working but to have a working solution to make only outgoing connections when the settings explicit allows it.

Its also a question of security and good behaviour. In my company are higher security levels set and this kind of calls are monitored. This forced calls will move VSC on the blacklist at some point if there is no native solution to really stop it. And because my company works also for official authorities which depend on them, this could escalate in some bad way.

**Comment by joaomoreno** [comment]
As the document mentioned, neither the setting nor the HTTP_* variables work for the core product. The core product reads the system settings, just like Google Chrome does. How do you configure Google Chrome in your company's machines?

**Comment by michtoen** [comment]
Chrome reads and respects the enviroment  _PROXY settings as every major browser. It asks in the default settings to confirm the auth but can store it.

But the point now we have is not how to setup the proxy, i have to stress it.

The question is why and what is doing that calls and how we can tell VSC not do to it.

If there is non way, then we have the issue of an automated ping, to a host.
Do we have this issue?

**Comment by joaomoreno** [comment]
> But the point now we have is not how to setup the proxy, i have to stress it.
>
> The question is why and what is doing that calls and how we can tell VSC not do to it.

The calls are done for the auto update feature, which you can easily disable using the `update.mode` setting.

Read more about it here: https://code.visualstudio.com/docs/supporting/faq#_managing-online-services

If this issue isn't about the proxy but about how to disable VS Code from reaching out to the update server, then I'll close it. Thanks.

**Comment by michtoen** [comment]
Thank you for your time but sadly the information the link provides seems to be outdated and did not help nor "update.mode" seems to be a known option anymore.

I assume the "update.channel" option should be used instead on the current build?
I run the current stable: V. 1.31.1. and had, as shown above, already set to "none".

Anyway, i forced both options to the settings.json - it had no effect.

We still have 2 foced calls to az764295.vo.msecnd.net on port 443.

**Comment by michtoen** [comment]
The call is done from the marketplace controlUrl. 
Removing that url setting from the product.json will stop the calls.

As far i can see in the settings, there is no option to disable this behaviour, related settings like 
extensions.showRecommendationsOnlyOnDemand
extensions.ignoreRecommendations

do not stop it.

**Comment by joaomoreno** [comment]
> The call is done from the marketplace controlUrl.

Oh thanks for this. This is pretty important actually and we don't offer a way to block it. There have been situation in the past in which extensions have contained malicious code. We use the marketplace controlUrl to protect users against this and have Code uninstall malicious extensions automatically.
