### ISSUE TITLE
Html autocomplete not working in php file.

### ISSUE THREAD

**Issue by AndRoMarian** [Microsoft/vscode#70220]
For what more you need more info. Just not working + CSS.
I don't know what you need. Say.
https://github.com/Microsoft/vscode/issues/69737

![Untitled](https://user-images.githubusercontent.com/48178307/54133549-f31d4480-441e-11e9-96f5-3cf8dbbf60e0.png)

**Comment by roblourens** [comment]
Hey @octref I can use emmet in PHP with `div` but not `<div`, which used to work, can you take a look?

**Comment by octref** [comment]
HTML only has `<div` completion too. Emmet only expands `div` not `<div`.

You might want to use https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client which has good support for HTML in PHP.

**Comment by AndRoMarian** [comment]
Still not working.

**Comment by octref** [comment]
@AndRoMarian It's working for me though. Can you make sure Intelephense is the only extension you install, and disable all other PHP extensions?
![image](https://user-images.githubusercontent.com/4033249/54226317-cc145080-44ba-11e9-89e3-074ad218ef0e.png)
