### ISSUE TITLE
JS code recognition off after regex

### ISSUE THREAD

**Issue by wasinwill** [Microsoft/vscode#70225]
Issue Type: <b>Bug</b>

VS Code Insiders doesn't to recognize when a regex expression ends (when JS code is compressed) since the last update

VS Code version: Code - Insiders 1.33.0-insider (d77d8d561143cc021a82664efc056755c075d070, 2019-03-11T08:47:23.627Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (12.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
vscode-apache|mrm|1.2.0
highlight-matching-tag|vin|0.8.6

</details>

**Comment by wasinwill** [comment]
![Capture](https://user-images.githubusercontent.com/44789688/54136099-7cb61d80-43f1-11e9-844b-0f2040fc3a18.PNG)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, please share the text of the code along with screenshots

**Comment by wasinwill** [comment]
It does reproduce when all extensions are disabled. I attached a screenshot (see above)

**Comment by wasinwill** [comment]
Text where code recognition fails:

function validateEmail(e){return/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(e)}

Note that the same code is recognized just fine when not compressed. The text below causes no issue:

function validateEmail(input) {var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(input);}

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/732 to track upstream
