### ISSUE TITLE
Folders Do Not Expand

### ISSUE THREAD

**Issue by blongacre22** [Microsoft/vscode#70226]
Issue Type: <b>Bug</b>

Since the latest update, folders do not expand.  I have the entire "D:" drive available to view, but when I try to open a folder to view the files, it just spins.  I need to close VS Code from Task Manager to get it to stop.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (21.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0

</details>

**Comment by roblourens** [comment]
Is this in the Explorer view? Did you open the D drive through Open Folder?

**Comment by blongacre22** [comment]
Yes, this is the Explorer view.  The "D:" drive is my default folder that I
just keep open and browse in the Explorer.

Currently no files open, and I can't close the application.

**Comment by isidorn** [comment]
I can not preorduce this.
Can you reproduce using vscode insiders? https://code.visualstudio.com/insiders/
If yes, can you attach a gif showing this issue?

**Comment by blongacre22** [comment]
Sorry, but I cannot help with troubleshooting this.

Version 1.32.1 cannot be used, so I have uninstalled and re-installed
1.31.0.

I'll watch for future updates and hope things get fixed.

**Comment by isidorn** [comment]
Sure.
