### ISSUE TITLE
Naming/Renaming box closes when window loses focus

### ISSUE THREAD

**Issue by KennethSweezy** [Microsoft/vscode#70238]
- VSCode Version: `1.32.1`
- OS Version: `Windows 10.0.17134 Build 17134`

Steps to Reproduce:
1. Click new file button OR Right-click and select "Rename"
2. Click away (another window, desktop, etc) from VSCode
3. See that the naming/renaming box gets closed when VSCode loses focus

Does this issue occur when all extensions are disabled?: **Yes**

Video:
![name error](https://user-images.githubusercontent.com/33377824/54145217-f525da00-4403-11e9-92b2-c57b3f317cfc.gif)

**Comment by isidorn** [comment]
As designed, the explorer has behaved like this since always. We will not change this.
