### ISSUE TITLE
Shows invalid signs/Language not supported

### ISSUE THREAD

**Issue by BelarminoVicenzo** [Microsoft/vscode#70236]
Issue Type: <b>Feature Request</b>

I have this SQL query:
insert into Fun��o values(@fun��o)

Instead of showing the right text, it shows "??", so it's written like this:
insert into Fun??o values(@fun??o)

The correct one should be: 
insert into Funçãoo values(@função)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763
![image](https://user-images.githubusercontent.com/20697084/54144955-2b2b8400-442d-11e9-9d2f-adeffe754ada.png)

Line 21 on the screenshot

Notepa++ shows it correctly

**Comment by yume-chan** [comment]
As the screenshot of notepad++ shows, your .sql file is in ISO 8859-9 encoding.

Which can not be detected reliably, thus Code decodes it with UTF-8 encoding incorrectly. 

Try to click the `UTF-8` on the status bar, choose `Reopen with Encoding`, `Turkish (ISO 8859-9)` to override the encoding.

**Comment by BelarminoVicenzo** [comment]
Thanks. It worked. :)
