### ISSUE TITLE
tasks.runTask is missing from Keyboard Shortcuts GUI Keyboard 

### ISSUE THREAD

**Issue by jfoshee** [Microsoft/vscode#70230]
Issue Type: <b>Bug</b>

1. Install Visual Studio Code
2. Open Keyboard Shortcuts GUI
3. In search box type: `tasks.runtask`
4. Observe that only `workbench.action.tasks.reRunTask` is listed, however `workbench.action.tasks.runTask` is missing.

If the user manually adds a shortcut via the JSON editor, then `runTask` will be listed in the GUI.

VS Code versions:  
Code - Insiders 1.33.0-insider (d77d8d561143cc021a82664efc056755c075d070, 2019-03-11T08:47:23.627Z)  
Code 1.32.1 (05f146c)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|28.00GB (24.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jfoshee** [comment]
I want to mention that as a consultant I coach other developers.  When I introduce them to Visual Studio Code, assigning a keyboard shortcut to runTask is literally one of the first things we do.  This was pretty jarring when I experienced this bug with a client, and makes for a poor first impression.

**Comment by alexr00** [comment]
I can reproduce this.

**Comment by sandy081** [comment]
@alexr00 This is because Keybindings editor does not support showing commands with arguments. Looks like run task command takes a string argument.

**Comment by sandy081** [comment]
Keyboard Shortcuts Editor should show all commands those appear in Command Pallette irrespective of having args or not. Because those commands gets executed without args when triggered from Command Pallette.
