### ISSUE TITLE
Incorrect code highlight std::swap

### ISSUE THREAD

**Issue by GauthamBanasandra** [Microsoft/vscode#70233]
I'm getting an error highlight for std::swap as shown in this image - https://photos.app.goo.gl/JWpLGewodLgZDcRn6

Here's the program - https://gist.github.com/GauthamBanasandra/c69bad2dcbb96d82834b1fb26f00fcee
The error highlight is seen on this line - https://gist.github.com/GauthamBanasandra/c69bad2dcbb96d82834b1fb26f00fcee#file-test-the-rods-cpp-L129

Please note that the program compiles and runs fine with Visual C++ compiler.

- VSCode Version: 1.31.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Just open the program https://gist.github.com/GauthamBanasandra/c69bad2dcbb96d82834b1fb26f00fcee in Visual Studio Code.

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
It sounds like you are using the C++ extension, please file this on the C++ extension repo

**Comment by GauthamBanasandra** [comment]
Sure @roblourens . In case anybody wants to follow - https://github.com/Microsoft/vscode-cpptools/issues/3280
