### ISSUE TITLE
glob: duplicate entries in parsed pattern

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7023]
Have a pattern like this: `{**/foo.json}` and run it through glob. The resulting pattern will end up having foo.json twice.

**Comment by bpasero** [comment]
@aeschli I extracted the one issue you found in https://github.com/Microsoft/vscode/issues/6936 where the same file pattern would show up twice into here and pushed a fix for June.

**Comment by aeschli** [comment]
I verified that | is used and works.
Not clear why you commented out the tests, they work. The problem is with the pattern I extracted to #9917.
