### ISSUE TITLE
vscode should send `textDocument/signatureHelp` after autocomplete result

### ISSUE THREAD

**Issue by vicapow** [Microsoft/vscode#70239]
When attempting to implement [function parameter auto complete](https://github.com/facebook/flow/pull/7518) in Flow, I wanted to support the same behavior as with TypeScript for function parameter autocompletion. It seems vscode + tsserver provides both the completion parameter helper and the signature helper as below:

![signature-helper](https://user-images.githubusercontent.com/583385/54145868-0bc03700-43ec-11e9-88fd-fe064b229eaf.gif)

However, when using communicating over LSP, vscode doesn't send the `textDocument/signatureHelp` request after the `textDocument/completion` response. Without this ability, it doesn't seem possible to match the same behavior in any LSP server implementation and provide the signatureHelp dialog.

**Comment by jrieken** [comment]
You can use signature help trigger characters (like `(` or `,`) and commands the get triggered after accepting a proposal, se https://github.com/Microsoft/vscode/blob/59dca36c224d885ba70741a2d47ebb46fe7f3bd2/src/vs/vscode.d.ts#L3406

**Comment by vicapow** [comment]
@jrieken best on my experimentation, those triggers don’t get called from characters coming from completion.

Also, as far as I can tell, commands don’t work in this situation either because the client would need to have custom logic to respond to the `workspace/executeCommand`. In otherwords, the client doesn’t execute the raw commands, it wraps them in the executeCommand request and response.

**Comment by jrieken** [comment]
You use the UI command, e.g the one that you invoke via the keybinding. That everything goes its ways

**Comment by vicapow** [comment]
@jrieken I don’t see these commands mentioned as part of the LSP specification. Under this assumption, this solution isn’t editor agnostic.

**Comment by jrieken** [comment]
> Under this assumption, this solution isn’t editor agnostic.

If you want something editor agnostic that you shouldn't post issues in the vscode repository, but in LSP land

**Comment by vicapow** [comment]
@jrieken i believe there is a solution that is editor agnostic that the LSP spec already supports that doesn’t require vscode specific protocols. So I don’t see this as a requiring any LSP spec changes.

To better align with the LSP spec in an editor agnostic way so that LSP servers don’t have to have any vscode specific code, the request here is for vscode to confirm to the LSP spec in an editor agnostic way. Specifically, sending the signatureHelp request after the completion would solve this issue in an editor agnostic way.

**Comment by vicapow** [comment]
@jrieken is there no interest from the vscode team to implement this feature using only editor agnostic LSP commands?
