### ISSUE TITLE
"View: Quick Open View" auto-selects the first item via keyboard

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#70235]
Issue Type: <b>Bug</b>

![gif](https://user-images.githubusercontent.com/35271042/54140629-483a6580-43e1-11e9-8ce8-ed6699b91a67.gif)

This does not repro while using the mouse, only on mouse-enter. I've tested this on other quick pick menus that require a secondary input and they do not reproduce. This also reproduces in stable (1.32.1).

Repro steps:

1. Open quick pick
2. With your keyboard, select "View: Quick Open View"
3. 🐛 The first item in the next screen is auto-selected

VS Code version: Code - Insiders 1.33.0-insider (d77d8d561143cc021a82664efc056755c075d070, 2019-03-11T08:44:16.124Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.90GB free)|
|Process Argv|-psn_0_2871997|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
azure-virtual-machine-explorer|for|0.0.2
vscode-pull-request-github-insiders|Git|1.64.0
vscode-azureappservice|ms-|0.12.0
azure-account|ms-|0.8.0
azurecli|ms-|0.4.3
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
code-settings-sync|Sha|3.2.6
mdx|sil|0.1.0
mdx-inline|vad|0.1.0
markdown-all-in-one|yzh|2.1.0

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@misolori I think this is expected, the quick open commands that hide the input field select the first entry automatically to allow for fast keyboard access, they are not meant to be used with the mouse. Not sure what the issue is here?
