### ISSUE TITLE
Revisit explorer reopening last used file when getting active

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7024]
Steps to Reproduce:
1. open some non explorer viewlet - e.g debug
2. have only one editor open - preview of a markdown file 
3. open explorer viewlet
4. the markdown preview gets closed and the markdown source is shown

I would expect that swtiching viewlets keeps my markdown preview open.
I guess the problem is that on explorer reveal you want to open the selected file but in this case you fail to recognize that the preview of that file is already open

**Comment by chrisdias** [comment]
It really feels like there needs to be a harder link between markdown and the preview.  i see from interviews people expect that the preview is closed when closing the markdown file (for example).  i don't know what the answer is but maybe there is a formalization of an editor to a preview.

**Comment by isidorn** [comment]
No longer happens
