### ISSUE TITLE
pasting makes code disappear

### ISSUE THREAD

**Issue by rcrooks** [Microsoft/vscode#70240]
Issue Type: <b>Bug</b>

I think this must have something to do with the smart selection improvements, but I can't figure out what is happening. What I'm seeing is that when I place the cursor in the middle or at the end of a line and paste some code there, other code following that, sometimes on multiple lines, disappears. for example, I had this
          if (video.loc.indexOf('?') > -1) {
            video.loc += '&' + url_param + '=';
          } else {
            video.loc += '?' + url_param;
          }

I copied the '=' from line 2, placed the cursor before the ; on line 4 and pasted. both the ';' and the '}' on the following line disappeared.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-add-brackets|ali|0.8.0
swagger-viewer|Arj|2.2.0
htmltagwrap|bra|0.0.7
bracket-select|chu|2.0.1
bracket-pair-colorizer|Coe|1.0.61
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.20
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
unibeautify-vscode|Gla|0.7.0
vs-docblock|jer|0.5.3
openapi-lint|mer|1.0.1
swagger-doc-viewer|mim|1.0.4
syncing|non|2.1.4
material-icon-theme|PKi|3.6.3
htmlescape-vscode-extension|ray|0.0.6
vscode-yaml|red|0.3.0
highlight-words|rsb|0.1.1
csspreview|san|1.0.2
indenticator|Sir|0.6.0
json2yaml|tux|0.2.0

(13 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Is it a formatting issue? Do you have `editor.formatOnPaste` set?

**Comment by rcrooks** [comment]
I do have that on. Will turn it off and see if that makes a difference (though I suppose it would be a bug in the format on paste in that case).

**Comment by rcrooks** [comment]
so far, not seeing it since turning off format on paste. Will report back if that changes.

**Comment by roblourens** [comment]
Maybe from `unibeautify-vscode`?

**Comment by rcrooks** [comment]
That's possible, though I haven't actually seen it happen when I run the formatter, and I only run it manually. but if it recurs, I'll try disabling that.
