### ISSUE TITLE
Release Notes: 1.32.1 Right-Click inoperative

### ISSUE THREAD

**Issue by regolas** [microsoft/vscode#70253]
Issue Type: <b>Bug</b>

If I right click on "Update 1.32.1: The update address these issues.", the context menu does not appear, even though hovering will display the github link and clicking on it will open the browser to github. I feel the right-click of the hyperlinked word "issues", should allow the context menu to appear.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Similar to #65310

**Comment by mjbvz** [comment]
Closing in favor of #65310
