### ISSUE TITLE
VSCode should suggest cleaning up unused workspaces

### ISSUE THREAD

**Issue by kevindiclemente** [Microsoft/vscode#70257]
See the attached image for size context: (the workspace .vscode folders are gone for these workspaces)
![image](https://user-images.githubusercontent.com/43895272/54157933-a3328380-4406-11e9-8ee1-a5ec15ee9cfc.png)

VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T10:06:48.833Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
I'm not sure how we can tell when you'll be done with the workspace entirely. What's using all that space, is it in workspaceStorage? You must have an extension caching huge amounts of data?

**Comment by kevindiclemente** [comment]
Hey @rob, I’m happy to dump more data - it’s likely the cpp extension intelligence database. What info should I capture for you? Sample scenario here would be you have a mapping from the workspace storage to a workspace folder and the workspace folder gets deleted, I think that would be good grounds for concidering storage deletion, or prompting the user if storage is low (my disk was full). Simple edge case is someone moves or renamed a folder (but that’s not a intractable)

**Comment by bpasero** [comment]
@kevindiclemente it would help if you can drill into the folder to see which one (with parents) is the large one
