### ISSUE TITLE
Update to add the latest Atom features

### ISSUE THREAD

**Issue by NtReleaseEpinephrine** [Microsoft/vscode#70259]
There's an issue with VS Code which should have been fixed for a long-time now: syntax highlighting in C and C++.

User-defined types are not included in the syntax highlighting.

When is this going to be solved?

**Comment by roblourens** [comment]
Please include some more details and an example code snippet

**Comment by NtReleaseEpinephrine** [comment]
When you define a data-type with the typedef keyword in C or C++, the defined type will be ignored by syntax highlighting - this will be regardless of whether you're using the C/C++ extension or not.

An example would be the following snippet.

`    
    #include <stdio.h>
    #include <windows.h>
    #include <winternl.h>

        ...


    NTSTATUS
    SnippetDemo(
        PVOID DemoBuffer
    )
    {
        NTSTATUS status;

        status = NtGiveMeEpinephrine(DemoBuffer);

        if(NT_SUCCESS(status))
        {
             ...
        }

        return status;
    }


    ...

`

On the latest official release for VS Code - with the latest C/C++ extension installed too - the user-defined PVOID (void*) and NTSTATUS (LONG) data-types from Windows header files are not highlighted. Furthermore, the NT_SUCCESS definition from the winternl.h header file is neither highlighted.

However, if I were to use a data-type which isn't user-defined, such as int or long, then it will be highlighted in blue. Even boolean will not be highlighted.

Please get this solved, finally.

**Comment by roblourens** [comment]
I see, we call this feature "Semantic highlighting" and it's on our roadmap. https://github.com/Microsoft/vscode/issues/585
