### ISSUE TITLE
Git init icon is missing?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#70258]
- VSCode Version: latest insiders
- OS Version: ubuntu 18.10

Steps to Reproduce:

1. create new folder, open and file inside
2. goto source control tab
3. says "no source control providers registered"? ok? sure but git works
4. press git init button (it is gone) it used to be in the source contol tab at top beside title

git still works and git init still works from command list just icon is gone?

![Screenshot from 2019-03-11 16-59-59](https://user-images.githubusercontent.com/962340/54157957-d6354100-441f-11e9-965c-e76a44603821.png)

it used to look like this:
https://code.visualstudio.com/Docs/editor/versioncontrol

![git-initialize](https://user-images.githubusercontent.com/962340/54158151-4217a980-4420-11e9-9f88-958eb7cfe0e9.png)

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur when all settings are reset?: Yes

Thanks.

**Comment by joaomoreno** [comment]
Thanks, great catch!
