### ISSUE TITLE
Support interactive variables in launch configurations

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#7026]
This is a feature required for https://github.com/Microsoft/vscode/issues/6569.

For details please see my prototype in the andre/pickervariables branch:

https://github.com/Microsoft/vscode/blob/andre/pickervariables/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L564

**Comment by isidorn** [comment]
@weinand I checked out the branch and the code looks good. Though I have some things which I would change, would your prefer:

-  I incorparate all that feedback and rewrite parts of your code on master
- You create a PR and I add comments on your PR

Both work equally fine for me 😊

**Comment by weinand** [comment]
@isidorn my code is not meant as a PR, it was just code that I wrote to unblock me. Since you are the owner of the launch config variable substitution you should implement this feature.

**Comment by isidorn** [comment]
Pushed a first version of this to master, check it out and let me know what you think.
Seems to work fine for the mock debug example - note that the variable name is case sensitive and in `package.json` of mock debug you contribute 'PickProcess'

**Comment by weinand** [comment]
@isidorn looks great! I've released "Attach to Process" support for node-debug to master.
One issue I saw: dismissing the process picker with ESC does not abort the launching of the debug session.

**Comment by isidorn** [comment]
I pushed the change that dimissing hte process picker silently aborts the debug session - let me know if we should show an info message in that case.

Also feedback on following wording is welcome. When extension writer hovers over `variables` in `package.json` we say 'Mapping from interactive variables (e.g ${action.pickProcess}) in `launch.json` to a command.'

When there is an interactive variable which is not contributed we say: 'Adapter {0} does not contribute variable {1} that is specified in launch configuration.'

**Comment by weinand** [comment]
@isidorn if an action variable is used multiple times in a launch config, the associated command should only be run once.

The reason behind this is as follows:
For a user the mental model of action variables should be that a variable has a value and that VS Code ensures that this value is initialised once, and not that every use of an action variable is a function call with a potentially different result.

**Comment by isidorn** [comment]
@weinand pushed a fix that should take care of this issue - so an action will get triggered only once even if it occurs multiple times in launch.json
