### ISSUE TITLE
Order open files in the order of use

### ISSUE THREAD

**Issue by DekInc** [Microsoft/vscode#70262]
Order open files in the order of use,
so is easy to find the last file opened.

Version: 1.32.1 (system setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Please include more details about what you want
