### ISSUE TITLE
Welcome page hotkeys are drawn over the panel in Insiders

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#70264]
Stable seems fine, this happens in Insiders/out of sources though:

![image](https://user-images.githubusercontent.com/2193314/54160827-c7459300-440d-11e9-8073-3987338e749b.png)

**Comment by bpasero** [comment]
Up for grab if someone can investigate what caused this 👍

**Comment by jeanp413** [comment]
I'll take this.

**Comment by jeanp413** [comment]
@bpasero while fixing this I found another minor issue about the shortcuts positioning that also happens in stable. The `max-height-478px` class is not added on startup https://github.com/Microsoft/vscode/blob/c1d001a915fe85cac93492393ea69fdb0c49ec0d/src/vs/workbench/contrib/watermark/browser/watermark.ts#L179 I fixed it by changing this https://github.com/Microsoft/vscode/blob/c1d001a915fe85cac93492393ea69fdb0c49ec0d/src/vs/workbench/browser/workbench.ts#L203 to this `lifecycleService.when(LifecyclePhase.Restored).then(() => this.layout());` not sure if this is fine. Should I create a separate issue and PR?
After startup or windows reload:
![1](https://user-images.githubusercontent.com/25115070/54253256-2b567d00-451c-11e9-981d-bf023a954cfb.png)
After panel resize:
![2](https://user-images.githubusercontent.com/25115070/54253273-41643d80-451c-11e9-8c82-dba72176453e.png)
