### ISSUE TITLE
Revisit instances where createSnapshot can null

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#70260]
From https://github.com/Microsoft/vscode/pull/69921

During the strict null migrations, we had to add a number of conditional guards and null suppressions around `ITextFileEditorModel.createSnapshot`. For cases where we know that `createSnapshot` will not return null (when the model is resolved) we should use the `IResolvedTextFileEditorModel` interface instead of `ITextFileEditorModel`. This should let us get rid of many of the conditionals / supressions

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73123
