### ISSUE TITLE
Add settings documentation rule to VS Code and VS Code extensions build pipeline

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#70268]
In preferences, there is a new setting, `editor.codeInsets`. That's a new expression that's nowhere explained. Googling doesn't explain what it does, too.

Please make it a habit to always add thorough documentation for new settings before publishing them. I also suggest to add Hyperlinks to each setting, pointing to the corresponding chapter in the online documentation. Screenshots would be quite helpful in the documentation to further shed light on the visual effect of a setting.

I suggest the VS Code build pipeline to add a linter step that's checking for a minimum length of explanatory IntelliSense information and for the presence (and validity) of documentation hyperlinks.

**Comment by jrieken** [comment]
That's a prototype and too early for being documented.

**Comment by SetTrend** [comment]
@jrieken : I see, but what's the purpose of making it public if it's of no use to anyone not being involved in VS Code development?

**Comment by jrieken** [comment]
fair point, I have removed the setting from the public listing

**Comment by SetTrend** [comment]
Thanks, Johannes.
