### ISSUE TITLE
Markdown preview don't display image when image path have blank space.

### ISSUE THREAD

**Issue by fha520** [Microsoft/vscode#70279]
Issue Type: <b>Bug</b>

Both "Design Pattern/image001.png" and "DesignPattern/image001.png" path have image file.
![img](Design Pattern/image001.png), wont display image. 
![img](DesignPattern/image001.png), display image correctly. 

Both Windows and macOS have this issue.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by fha520** [comment]
![img](DesignPattern/image001.png), display image correctly.

**Comment by fha520** [comment]
"![img](DesignPattern/image001.png)", display image correctly.

**Comment by fha520** [comment]
![img](Design (no blank space)Pattern/image001.png), display image correctly.

**Comment by mjbvz** [comment]
The markdown specification (common mark) does not allow spaces in urls; you need to percent encode them: `%20`
