### ISSUE TITLE
打开程序会打开两个。。。

### ISSUE THREAD

**Issue by lyjas** [Microsoft/vscode#70271]
之前版本可以存储临时文件，自动保存。现在换成了win8.1企业版安装之后，双击程序快捷方式会打开两个visual studio code程序，点击关闭会提醒我是否保存临时文件（之前版本可以一直临时存储，直到我想真正的存储到一个文件上）

**Comment by roblourens** [comment]
I think this is https://github.com/Microsoft/vscode/issues/70006
