### ISSUE TITLE
启动程序会打开两个窗口

### ISSUE THREAD

**Issue by pengxiaozuo** [Microsoft/vscode#70270]
Issue Type: <b>Bug</b>

如果关闭程序时，有未保存的文件，打开程序会启动2个窗口

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.25.0
Kotlin|mat|1.7.0
vscode-language-pack-zh-hans|MS-|1.32.4
java|red|0.40.0
markdown-preview-enhanced|shd|0.3.12
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.0
vscode-maven|vsc|0.15.0
markdown-all-in-one|yzh|2.1.1

</details>

**Comment by roblourens** [comment]
I think https://github.com/Microsoft/vscode/issues/70006
