### ISSUE TITLE
High CPU usage on Mac OS X after latest upgrade, constant errors

### ISSUE THREAD

**Issue by andreixk** [Microsoft/vscode#70275]
Issue Type: <b>Bug</b>

After last upgrade, the CPU usage shot up to 100% for no reason (all same files/folders open), Process Explorer shows extensionHost is using 104%.
Also, this error constantly popping up in Output window:

[Error - 10:39:56 PM] Request textDocument/signatureHelp failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.Server.SignatureHelp(TextDocumentPositionParams params, CancellationToken token)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.SignatureHelp(JToken token, CancellationToken cancellationToken)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.89GB free)|
|Process Argv|-psn_0_2634371|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.0.4
insertnumbers|Asu|0.9.1
vscode-django|bat|0.19.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.8.2
jupyter|don|1.1.5
python-extension-pack|don|1.4.0
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
diff-tool|jin|0.0.1
MagicPython|mag|1.1.0
python|ms-|2019.2.5558
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.16.2
vscode-docker|Pet|0.5.2
vscode-icons|rob|8.2.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.2.7
vscode-fileutils|sle|2.13.5
vscode-status-bar-format-toggle|tom|1.4.0
vscodeintellicode|Vis|1.1.4
vuetify-vscode|vue|0.2.0
jinja|who|0.0.8
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It looks like the Python extension must be doing something weird. Please file this on the Python extension repo so they can investigate

**Comment by andreixk** [comment]
Do you know the name of the repo by any chance?

**Comment by huangxg** [comment]
I uninstalled the Python extension and disabled all other extensions, still have this problem when opening some JavaScript files.

**Comment by roblourens** [comment]
@huangxg please open your own issue and see this steps to provide as many details as possible: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu
