### ISSUE TITLE
API to get the scopes applied to the current position in the document

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7027]
I couldn't find anything like this which would have removed the need for parsing some text in my extension.

https://atom.io/docs/api/v1.1.0/ScopeDescriptor

**Comment by warpdesign** [comment]
What's the status on this ? I see it has been closed but doesn't seem to be mentionned anywhere else.

**Comment by alexandrudima** [comment]
@warpdesign 

#7590 is a duplicate of this issue, so given this issue was created before #7590 I closed #7590 in favor of this one.

**Comment by indiejames** [comment]
This would be very useful for my extension as well. I need to be able to get the brackets/parens containing the position while ignoring any brackets/parens inside strings or comments.

**Comment by chrmarti** [comment]
👍 This would allow for features that need language specific knowledge, but can do without a full AST with bindings.

**Comment by hoovercj** [comment]
This appears to be a duplicate of #580

**Comment by alexandrudima** [comment]
Let's track in #580
