### ISSUE TITLE
Show Exploer with CTRL+SHIRT+E Fail went a file is open

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#70277]
Issue Type: <b>Bug</b>

Showing the Explorer using CTRL+SHIFT+E only works when no files are open in the editor. I am able to toggle between Show Explorer, Show Debug, Hide Sidebar.

When I have a file open and I press CTRL+SHIFT+E, I see the character 'E' typed into the edit window and the Explorer is not shown.

VS Code version: Code - Insiders 1.33.0-insider (d77d8d561143cc021a82664efc056755c075d070, 2019-03-11T08:42:16.804Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.66GB (3.88GB free)|
|Process Argv|/home/yadav/dev/docs/guides|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.2
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
java-debug|DSn|0.0.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
markdown-preview-bitbucket|hbr|1.0.0
Scala|itr|0.1.7
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.2.5
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
java|red|0.40.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.0
vscode-maven|vsc|0.15.0
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by rajinder-yadav** [comment]
This is not the same bug  #70285, KDE does not use IBUS. 

I even checked and it is not install:

```
yadav@source$ ibus

Command 'ibus' not found, but can be installed with:
sudo apt install ibus

yadav@source$ which ibus
yadav@source$ 
```

Also as I stated, this key combo works when there is no file open in the editor window, so clearly this key combination is getting delivered to vscode. It is only when there is a file open in the editor does this issues show up and the letter "E" is typed out.

**Comment by usernamehw** [comment]
@chrmarti

**Comment by benjaminwood** [comment]
Same issue here, ibus is installed but I confirmed the daemon is not running. The shortcut works when no file is open in the editor window as @rajinder-yadav mentioned.

Interestingly, other VScode keyboard shortcuts stop working after using `CTRL+SHIFT+E`, until I click/focus something on screen (click text, change tabs, whatever).

I believe this problem appeared after upgrading to the most recent release (a day or two ago).

**Comment by rajinder-yadav** [comment]
This issue has existed for much longer, I say weeks. Last time it also was closed off prematurely as a dup and I didn't bother contesting.

**Comment by lesha1201** [comment]
This is not vscode issue. This shortcut uses input methods (e.g. ibus), and when you press it, it opens Emoji (ctrl+shift+u - Unicode). Try to change input method to `xim`

**Comment by benjaminwood** [comment]
@lesha1201 see the above comment from @rajinder-yadav: https://github.com/Microsoft/vscode/issues/70277#issuecomment-472259922

> This is not the same bug #70285, KDE does not use IBUS.
> 
> I am using Linux Kubuntu, it uses Qt, not IBUS or GTK.
> 
> I even checked and ibus is not installed:
> 
> ```
> yadav@source$ ibus
> 
> Command 'ibus' not found, but can be installed with:
> sudo apt install ibus
> 
> yadav@source$ which ibus
> yadav@source$ 
> ```
> Also as I stated, this key combo works when there is no file open in the editor window, so clearly this key combination is getting delivered to vscode. It is only when there is a file open in the editor does this issue show up and the letter "E" is typed out.

**Comment by lesha1201** [comment]
@benjaminwood Try to press this combination in any other text field (browser for example) and you will see this is not VSCode issue. I didn't write to change `ibus` to something, I suggest to change current input method to `xim`, because this helped me on two distros (Ubuntu 18.10 (just open language settings and choose xim) and Deepin 15.4 (needed to change config files))

**Comment by benjaminwood** [comment]
@lesha1201 thanks for trying to help. I can confirm that pressing the key combination outside of VScode (browser for example) does nothing at all. Did you read the following?

> Also as I stated, this key combo works when there is no file open in the editor window, so clearly this key combination is getting delivered to vscode. It is only when there is a file open in the editor does this issue show up and the letter "E" is typed out.

The key combination **works** inside of VScode if there is no open file in the editor window. Clearly this is a different issue that what you experienced (and was documented in #70285 & #48480).

**Comment by rajinder-yadav** [comment]
To reiterate CTRL+SHIFT+E works inside VSCode when there is no editor open, once a file is open for editing this shortcut stops working.

**Comment by alexandrudima** [comment]
@rajinder-yadav 
Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by alexandrudima** [comment]
Could this be helpful? --- https://stackoverflow.com/questions/52032340/ctrlshifte-inerts-special-characters-into-file-instead-of-showing-explore-pane

**Comment by benjaminwood** [comment]
@alexandrudima the "View: Show Explorer" command is bound for me:

![image](https://user-images.githubusercontent.com/1232531/57237239-6b9e1d00-6fec-11e9-8ca4-6980182865eb.png)

The shortcut worked for me until recently when I upgraded VS-Code. My GTK version has not changed. I'd upgrade GTK to confirm, but I believe it'd be a can of warms unless I upgrade my distro beyond the latest LTS.

**Comment by rajinder-yadav** [comment]
![show-explorer](https://user-images.githubusercontent.com/439226/57267806-5c9c8680-704f-11e9-8af7-183f81a58e9a.png)

**Comment by hardikdangar** [comment]
To anyone who is experiencing this in Linux,

This is because ctrl + shift + E is assigned to emoji input.

TO disable that go to terminal & type 

$ ibus-setup

window will open third tab will be emojis tab. change the shortcut key ctrl + shift + e to anything you like. then explorer shortcut key will perfectly.

**Comment by rajinder-yadav** [comment]
@hardikdangar this is not related to that bug, see my 2nd reply, but thanks for sharing.

**Comment by Qussayyon** [comment]
![Peek 2019-06-28 12-29](https://user-images.githubusercontent.com/13088819/60333100-dfcbc000-99a0-11e9-8483-8aa63eea77ca.gif)
I'm using KDE neon and KDE doesn't use ibus and as U see in gif, code is being run while disabling all extensions.

**Comment by alexandrudima** [comment]
Does `Ctrl+Shift+E` reach VS Code?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by benjaminwood** [comment]
Thanks for the tip. For me it appears not to be reaching VS code.

I haven't figured out how to resolve the problem, but I'm suspicious my conflict is with i3 (window manager). Anyone else having this problem using i3?

If it is helpful to anyone else, you may be able to track down what is intercepting the key using `XF86LogGrabInfo`.

First tail the system journal to see the result: `journalctl -f`. Then in another terminal window/tab:

```
xdotool keydown "ctrl+shift+e"; xdotool key "XF86LogGrabInfo"; xdotool keyup "ctrl"; sleep 1; xdotool keyup "shift"; xdotool keyup "e";
```

FYI, I'm on Ubuntu, the above may be different on other distros.

**Comment by Qussayyon** [comment]
> Thanks for the tip. For me it appears not to be reaching VS code.
> 
> I haven't figured out how to resolve the problem, but I'm suspicious my conflict is with i3 (window manager). Anyone else having this problem using i3?
> 
> If it is helpful to anyone else, you may be able to track down what is intercepting the key using `XF86LogGrabInfo`.
> 
> First tail the system journal to see the result: `journalctl -f`. Then in another terminal window/tab:
> 
> ```
> xdotool keydown "ctrl+shift+e"; xdotool key "XF86LogGrabInfo"; xdotool keyup "ctrl"; sleep 1; xdotool keyup "shift"; xdotool keyup "e";
> ```
> 
> FYI, I'm on Ubuntu, the above may be different on other distros.

What is the correct output and wrong output?

**Comment by benjaminwood** [comment]
@Qussayyon 

> What is the correct output and wrong output?

Not sure that there is right/wrong output, it just shows you what applications are intercepting keystrokes. In my case, I only saw i3 mentioned in the output. So, I assume that i3 is grabbing the key command (but I'm not 100% sure). Like I said, "*I'm suspicious my conflict is with i3*".

**Comment by alexandrudima** [comment]
There isn't anything we can do on our side if we don't receive the keybinding... My recommendation is to rebind the action to another keybinding, which is trivial using the keybindings editor (ctrl+k ctrl+s)

**Comment by benjaminwood** [comment]
Thanks @alexandrudima, I agree (for my situation, anyways!).

**Comment by grooveygr** [comment]
@benjaminwood, I use a similiar Ubuntu + i3 setup.
I can confirm this issue has been driving me crazy as well.

A recent workaround I found is simply turning on the `ibus-daemon` (and turning off the global emoji selector shortcut). I've done absolutely no digging into how or why this works, especially seeing as other editors have no problem capturing the ctrl+shift+e combination without ibus, but a workaround is a workaround. 

Hope this helps! :pray:

**Comment by benjaminwood** [comment]
Thanks for the tip @grooveygr, I can confirm your workaround, uhh, works for me too. :-)

Perhaps it'll work for others, too.
