### ISSUE TITLE
When file size open in editor exceed size of a buffer, VS Code crashed

### ISSUE THREAD

**Issue by Kri-Ol** [microsoft/vscode#70274]
- VSCode Version: 1.32.1
- OS Version: Windows 10 1809, x64

Steps to Reproduce:

1. Have open file from disk with trivial name, file is large but buffer size is not exceeded
2. File is overwritten by external process, generating data
3. File is now large than the buffer size
4. VS Code crashed
5. On attempt to open file again, VS Code goes to setting mode and asks to increase
    file max buffer size to 4096M, then file is opened successfully

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kri-Ol** [comment]
File size is a bit larger than 2Gb

**Comment by rebornix** [comment]
You may want to increase the limit a bit more, like `code --max-memory 8096`
