### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by ishworpanta10** [Microsoft/vscode#70284]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.flutter hot reload is not working after update
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ShashankSirmour** [comment]
same here.

**Comment by roblourens** [comment]
Please include more details

**Comment by weslly99** [comment]
Flutter hot reload not working, and no throws exception on console of the vs.

**Comment by ShashankSirmour** [comment]
I have currently version 1.32.1 and before the update when I save flutter program it auto takes to reload and shows changes but after the update, every time I have to click restart button to see changes means nothing happens after the program saved.

**Comment by roblourens** [comment]
Are you using an extension for Flutter? This doesn't sound like a vscode issue.

**Comment by ShashankSirmour** [comment]
> Are you using an extension for Flutter? This doesn't sound like a vscode issue.

yes, I am using an extension for Flutter everything just change after the update only.

**Comment by ShashankSirmour** [comment]
> Are you using an extension for Flutter? This doesn't sound like a vscode issue.

now after updating it to 1.32.2, it's all works fine  thank you
