### ISSUE TITLE
Custom typings file only used while open

### ISSUE THREAD

**Issue by rasenplanscher** [Microsoft/vscode#70286]
Issue Type: <b>Bug</b>

0. `git clone git@github.com:rasenplanscher/vscode-typings-test.git` and open in `vscode`
1. open `index.ts`
    + you will see the ts error `Cannot find module './import.vue'.`
2. open `vue.d.ts` persistently
3. go back to `index.ts`
    + you will not see that error
4. close `vue.d.ts`
5. go back to `index.ts`
    + you will see the error again

+ does not happen in `import` without `from` – that does not seem to be checked 🤷‍♂️

VS Code version: Code - Insiders 1.33.0-insider (d77d8d561143cc021a82664efc056755c075d070, 2019-03-11T08:47:23.627Z)
OS version: Windows_NT x64 10.0.17763

Extensions: none

**Comment by rasenplanscher** [comment]
Funny: the same thing happens in `Visual Studio 2017` 🤔

**Comment by Cerlancism** [comment]
I visited your repo.

I think you just got to remove `"include": ["tsconfig.ts"]` from the tsconfig and the typing works, that line doesnt make sense there.

**Comment by rasenplanscher** [comment]
Thank you for the quick response!
I'm really sorry for having wasted your time with this 😢 

That line was actually there to solve another issue in the original repo.
After removing that line again, both errors are gone...
I really don't know what's going on...
