### ISSUE TITLE
Cant open interactive terminal

### ISSUE THREAD

**Issue by AndyWDev** [Microsoft/vscode#70281]
Issue Type: <b>Bug</b>

I am trying to open the interactive terminal. When I select powershell from the option, there 'appears' to be nothing on the screen under the 'terminal' menu.

For example, one would expect a flashing cursor to highlight where the input focus is currently, also one would expect the terminal input area to be highlighted (as a normal editor window is).

In my case, I just have a large white box which does nothing and the menu items 'Problems', 'Output', 'Debug Console', 'Terminal' at the top.

With terminal selected, typing text below it does nothing - there is no input cursor and no highlighting of the edit area (so I know where to type).

After some investigation, I have found that the start of the edit field is indented almost under the terminal menu, but on the next line down, appears to be correctly left justified to the edge of the screen.  

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IsaacLf** [comment]
I suppose it's the same problem as this one: #57803, right?, i've just got the same problem after installing the latest version Win10 (1809), and it appears not to be solved yet, hope it is soon.

**Comment by SirBETE** [comment]
Got the same issue
![image](https://user-images.githubusercontent.com/34303738/54186869-a718e100-44ac-11e9-9f23-05ec7aefefc2.png)

**Comment by kathrynherod** [comment]
Same issue here, except mine won't allow me to click inside of it and crashes.

**Comment by AndyWDev** [comment]
Just an update with my original post.  

If one left mouse clicks on the terminal window top left corner and drags the mouse to the lower right, it highlights the terminal area in a different color.

For Powershell, I found that if one then single left clicks in the highlighted area (around the middle of the screen)  and hits return a couple of times, the Powershell prompt will appear.

The indentation issue I was encountering, was because the powershell prompt itself takes up a few inches on the left side of the screen, so clicking there and trying to type will do nothing.

Once I was able to get the PS prompt to appear. the same technique allowed other prompts to appear (there is a short delay between selecting view..command pallet.terminal type and when one can hit return to get the prompt to appear).

**Comment by fsackur** [comment]
Have you tried changing the renderer?

`Terminal > Integrated: Renderer Type`

DOM is probably the safest - use Canvas if it works.

**Comment by AndyWDev** [comment]
yes, but it didnt make any differences.

For those not familiar with VS Code,  the above post is referring to edit.preferences.user settings.terminal.Renderer Type.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
