### ISSUE TITLE
Command Palette closes when navigating away from window

### ISSUE THREAD

**Issue by Immortalin** [Microsoft/vscode#7028]
- VSCode Version: 1.1.1
- OS Version: Xubuntu 16.04

Steps to Reproduce:

1. Open VS code, bring up command palette with ctrl-shift-p. Start a command e.g. bring up the install extensions list.
2. Navigate away from window e.g. alt-tabbing. The command palette closes when you come back.

AFAIK, this pretty much happens on all editors with command palettes but it would be nice if it could be made to be more permanent.

**Comment by bpasero** [comment]
We plan to replace extensions with a more stable UI this release, closing.

**Comment by ice-blaze** [comment]
Is there any information on this release ?

**Comment by bpasero** [comment]
@ice-blaze try `"workbench.quickOpen.closeOnFocusLost": false`

**Comment by ice-blaze** [comment]
Thanks! You made my day.
