### ISSUE TITLE
browsing python code doesn't work

### ISSUE THREAD

**Issue by omganesh** [Microsoft/vscode#70287]
Issue Type: <b>Bug</b>

hi , 

i am unable to browse b/w code using vscode.
even basic def / func lookup doesn't work.

swithing back to intelliJ 

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
java-decompiler|dgi|0.0.2
xml|Dot|2.4.0
shell-format|fox|4.0.4
simple-vim|jpo|0.0.5
restructuredtext|lex|105.0.0
remotefs|lix|0.0.13
MagicPython|mag|1.1.0
python|ms-|2019.1.0
gradle-language|nac|0.2.3
java|red|0.40.0
autoimport|ste|1.5.3
python|tht|0.2.3
shell-launcher|Tyr|0.3.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.0
vscode-maven|vsc|0.15.0
vscode-ansible|vsc|0.5.2
jinja|who|0.0.8

</details>

**Comment by roblourens** [comment]
Please include more details and file this on the python extension please
