### ISSUE TITLE
Switch to Explorer using shortcut have bug

### ISSUE THREAD

**Issue by rudilee** [Microsoft/vscode#70285]
Issue Type: <b>Bug</b>

Steps to reproduce:
* Press `Ctrl + Shift + E`

Expected results:
* Explorer should displayed/switched to

Actual results:
* Explorer not shown
* `e` character inputed into editor
* When press escape repeatedly `` characters inputed for each press until it all disappear after pressed 8 times
* If typing other characters it inputed normally, but when press backspace, all the inputed chars disappear

Temporary workaround:
* Switch to others panel first like Debug or Extensions using shortcut
* Then switch to Exproler using shortcut

Notes:
I use i3wm with XFCE desktop, and the bug actually occurred way back around 1.2X version if i remembered correctly

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:53:01.021Z)
OS version: Linux x64 4.20.8-100.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2321)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (0.96GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-coffeescript-preview|dre|1.0.1
language-gettext|mro|0.1.1
python|ms-|2019.2.5558
vscode-docker|Pet|0.5.2
vscode-fileutils|sle|2.13.5
vscodeintellicode|Vis|1.1.4

(1 theme extensions excluded)

</details>

**Comment by amitbisht511** [comment]
Same Issue With Me
I am using ubuntu and i have disabled all extensions.

**Comment by amitbisht511** [comment]
Oops I think i found out the issue 

You can look at this  [https://github.com/Microsoft/vscode/issues/48480#issuecomment-413473595](comment)

I guess my ubuntu does not use ibus by default i have to set up a environment value ` GTK_IM_MODULE=ibus`

**Comment by rudilee** [comment]
> Oops I think i found out the issue
> 
> You can look at this [comment](https://github.com/Microsoft/vscode/issues/48480#issuecomment-413473595)
> 
> I guess my ubuntu does not use ibus by default so i have to set up a environment value ` GTK_IM_MODULE=ibus`

Yup, that's fixed the problem for me, thanks
