### ISSUE TITLE
VS Code refuses to authenticate with Azure Repos using AAD and refuses to persist authentication even with alternate credentials

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vscode#70293]
Issue Type: <b>Bug</b>

I try to push to my Azure Repos git repository.

VS Code pops up the AAD authentication prompt.  I enter my credentials.

Expected result: authentication succeeds and authenticated session persisted, so I do not have to enter credentials again for some weeks (at minimum).

Actual result: VS Code gives no feedback and pops up the textbox asking for username (non-AAD authentication). Entering alternate credentials here succeeds but the session is not persisted. I have to re-do this dance every time!

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.98GB free)|
|Process Argv|--folder-uri file:///c%3A/Source/CmsTinkering.Configuration|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.10.6
PowerShell|ms-|1.11.0

</details>

**Comment by roblourens** [comment]
Can you check whether going through auth with this extension: https://marketplace.visualstudio.com/items?itemName=ms-vsts.team or using a git credential helper: https://code.visualstudio.com/Docs/editor/versioncontrol#_how-can-i-sign-into-git-with-my-azure-devops-organization-which-requires-multifactor-authentication solves your problem?

**Comment by sandersaares** [comment]
I tried Azure Repos extension - no difference. The Azure Repos "sign in" action also does not persist, requiring me to re-login every session to see the new statusbar information it adds.

I already have Git Credential Manager installed (it is the same one that comes with the Git for Windows installer, right? I installed that).

**Comment by roblourens** [comment]
>  The Azure Repos "sign in" action also does not persist

That seems wrong. Not sure if you have a better answer @joaomoreno or if this goes to another team

**Comment by joaomoreno** [comment]
> VS Code pops up the AAD authentication prompt

Can you show me a screenshot of that auth prompt?

**Comment by sandersaares** [comment]
This is what I refer to as the AAD auth prompt:

![git-credential-manager_JBZm6eBqGU](https://user-images.githubusercontent.com/9914262/54352858-907db000-468d-11e9-85f7-928c4bda626c.png)

I took a problem steps recording of the whole process - if you like I can email it to you (not sure if the URLs and details are safe for public posting).

Interestingly, I can pull just fine from the repo in question - only pushing causes the re-authentication every time.

**Comment by joaomoreno** [comment]
That auth dialog doesn't come from VS Code. What credential manager did you install?

**Comment by sandersaares** [comment]
I have installed VS2017 and Git for Windows 2.21.0 (with the credential manager that comes with that installer).

![](https://i.imgur.com/LigP2RL.png)

**Comment by joaomoreno** [comment]
Does the dialog open when you run `git fetch` from a terminal?

**Comment by sandersaares** [comment]
No but it does open when I run `git push` from a terminal!

So not VS Code related, clearly - I will close this and report it elsewhere. In fact, given that I am unable to actually repro this on a clean new repository, I am just going to ignore it and chalk it up to computer hissy fits and hope I never see it again.
