### ISSUE TITLE
.tesbak

### ISSUE THREAD

**Issue by xiaohu1991** [Microsoft/vscode#70296]
[Issue](url) Type: <b>Bug</b>

It will be building a file which like xx.lua.tesbak when i press Ctrl+s every time.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
luaide|kan|0.7.5
vscode-language-pack-zh-hans|MS-|1.31.4

</details>

**Comment by roblourens** [comment]
I don't understand. Maybe the lua extension is doing this?
