### ISSUE TITLE
Restart Extension Host

### ISSUE THREAD

**Issue by iqapps** [Microsoft/vscode#70295]
Issue Type: <b>Bug</b>

I get "Restart Extension Host" very often when developing Arduino, when disconnecting Arduino with active Serial connextion.

Can't we have the Extension Host not break down, or restart itself at least. 

Even though some extension goes berserk, the extension host should be rock solidt, right.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
svn-scm|joh|1.47.1
cpptools|ms-|0.21.0
vscode-arduino|vsc|0.2.25

</details>

**Comment by roblourens** [comment]
Could you file this issue on the Arduino extension? It sounds like they are crashing the node process so maybe they can investigate a bit.
