### ISSUE TITLE
Improved column selection not quite working

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#70299]
Issue Type: <b>Bug</b>

In the release notes:
https://code.visualstudio.com/updates/v1_32#_improved-column-selection

I've set the `editor.multiCursorModifier` setting to Alt. Now when I hold Alt and drag to select, it selects normally. I have to hold Alt+Shift for column selection, which is neither specified in the setting, nor in the instructions.

This also happens with all extensions disabled.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (18.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.2.2
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.9
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.5.2
vscode-versionlens|pfl|0.22.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.7
vscode-svg-previewer|vit|0.5.0

</details>

**Comment by alexandrudima** [comment]
The call out from the release note only works when configuring `"editor.multiCursorModifier": "ctrlCmd"`. The Shift+Alt+ variant used to work before the latest release.

**Comment by thany** [comment]
So youre saying it block-selects with Alt if it's set to `ctrlCmd` and block-selects with Ctrl if it's set to `alt`?

Shouldn't it block-select with Alt if it's set to `alt`? And if no, why?

**Comment by alexandrudima** [comment]
`editor.multiCursorModifier` controls the modifier to add multiple cursors. Multiple cursors is a distinct feature from block selection or "column selection", even though they appear very similar.

Multiple cursors can be added independent of a rectangular shape by alt+clicking or ctrl+clicking (depending on the configuration) at any location in the source code. Mulitple cursors can also be added with Ctrl+D or Ctrl+Shift+L (by selecting words).

So when the multi-cursor feature is configured to be `ctrlCmd`, then `alt` is "available" and can be used for column selection

**Comment by thany** [comment]
I see.

This is confusing to people who don't actually use multiple cursors that commonly, but are used to block selection. They will not be able to figure out what determines the modifier for that.

Why is it not possible to use one modifier for both? I mean, multiple cursor is clicking while holding either alt or ctrl, while column selecting is dragging.

**Comment by alexandrudima** [comment]
Similar how there are many people used to block selection, there are also a lot of people used to multi-cursor which is a generalization of block selection. There is not one concept that is easier or more commonly used. Each person has come in contact with one concept or another first and feels more familiar with one or another, but both concepts are mainstream.

All of this is documented on our website. Example of multi cursors documentation https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

It is not possible for Alt+Click to do both multi-cursor and block selection at the same time because they are different gestures and they behave differently. One is creating a block of multiple cursors, while the other can be used to add a cursor at any location.

**Comment by thany** [comment]
I mean, block selection is dragging, and multiple cursors is clicking. So with that as the primary difference in gesture, why does vscode still demand different modifier keys?

Analogy: It would be like if Ctrl+S wasn't possible because the Ctrl modifer is already used for Ctrl+F.

**Comment by alexandrudima** [comment]
> I mean, block selection is dragging, and multiple cursors is clicking

That is not true. It is possible to drag to create multiple cursors with a specific selection e.g.
![Kapture 2019-04-04 at 10 18 10](https://user-images.githubusercontent.com/5047891/55540294-fd033200-56c2-11e9-9e46-6b70506cfa4a.gif)

**Comment by thany** [comment]
Shiiiit, I didn't know that 😵

Okay, it makes sense now. But still, the settings that control this are still confusing.
