### ISSUE TITLE
Terminal view problem

### ISSUE THREAD

**Issue by masoudr** [Microsoft/vscode#70294]
- VSCode Version:1.32.1
- OS Version: Windows 10 17763

Steps to Reproduce:

My problem is a little weird but it annoys me. I'm using VSCode with Python. But when I try to use `Run python file in terminal` the output is printed in terminal but it automatically scrolls my terminal to the last line and hides the output. Another problem with this terminal is when I launch a new terminal window and typing something inside it, it hides the first part of the terminal. I put some gifs for clarification. I'm having this problem on two separate PCs running the same OS.
![hides_1](https://user-images.githubusercontent.com/6974428/54185453-4c888080-44be-11e9-959d-d3b1b227343b.gif)
![hides_2](https://user-images.githubusercontent.com/6974428/54185459-514d3480-44be-11e9-884b-b4f182ab9c47.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by masoudr** [comment]
So what should I do to fix it?

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
