### ISSUE TITLE
Find in selection doesn't work for selection in single line in some cases

### ISSUE THREAD

**Issue by sliwinski-milosz** [microsoft/vscode#70298]
- VSCode Version: 1.32.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:
1. Select one line and toggle `Find in selection` (till this point it works fine and searches in the selected line)
2. Reselect another one line in the document and try to use `Find` in that selected line

Expected Result:
Editor should start to search in the newly selected line.

Actual Result:
Editor keeps searching in the previously selected line

Comments:
It works as expected if instead of selecting one line I will select at least two lines.

**Comment by sidrmhu** [comment]
I see this problem too with Replace All in Selection with VSCode 1.34 on Windows.

**Comment by rebornix** [comment]
Same as https://github.com/microsoft/vscode/issues/95356
