### ISSUE TITLE
VS Code Insiders crashing after last update

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/vscode#70301]
After last update I'm getting the following error when trying to open VS Code Insiders build:
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...es.asar.unpacked\node-pty\build\Release\winpty.dll
File: d:\a\1\s\node_modules\node-pty\deps\winpty\...\winpty.cc
Line: 924

Expression: ASSERT_CONDITION("wp != nullptr && cols > 0 && rows > 0")

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

If I select "Abort", the following message is shown:
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
The window has crashed

[Content]
We are sorry for the inconvenience! You can reopen the window to continue where you left off.

[Reopen] [Close]

**Comment by AndriusAndrulevicius** [comment]
I don't have to press anything - just opening VS Code crashes the application

**Comment by Ali1Ammar** [comment]
me too

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
