### ISSUE TITLE
Suggest to use Webpack for extension building is bug I think.

### ISSUE THREAD

**Issue by peni4142** [Microsoft/vscode#70308]
- VSCode Version: newest
- OS Version: 

Steps to Reproduce:

1. Create a complex project
2. Try to use webpack

The explanation https://code.visualstudio.com/api/working-with-extensions/bundling-extension will work for a Hello World project, but I think not for:
https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample

when I call in my extension the equivalent of :
`client.start();` (https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/client/src/extension.ts line 57). I get an error. "Had trouble to start the theServer server."
With a deeper dive, I was getting the error 1;

The params for this part are correct:
```
client = new LanguageClient(
		'languageServerExample',
		'Language Server Example',
		serverOptions,
		clientOptions
	);

```
I had to proof by `console.log()`, that the params are correct because the source-map doesn't work too.

So I think you should make an example for a bit more complex project, like the lsp-sample, to show that it works fine and how to use it and not an example for a "Hello World" extension. You even don't document which vscode-modules (vscode-debugadapter, vscode-debugprotocol, vscode-jsonrpc, vscode-languageclient, vscode-languageserver, vscode-languageserver-protocol, vscode-languageserver-types, vscode-uri) I have to execlude.

I tried some different webpack configs. My last was:

```
//@ts-check

'use strict';

const path = require('path');
const nodeExternals = require('webpack-node-externals');

/**@type {import('webpack').Configuration}*/
const config = {
  target: 'node', // vscode extensions run in a Node.js-context 📖 -> https://webpack.js.org/configuration/node/

  entry: './src/client/extension.ts', // the entry point of this extension, 📖 -> https://webpack.js.org/configuration/entry-context/
  output: {
    // the bundle is stored in the 'dist' folder (check package.json), 📖 -> https://webpack.js.org/configuration/output/
    path: path.resolve(__dirname,'..', 'out', 'client'),
    filename: 'extension.js',
    libraryTarget: 'commonjs2',
    devtoolModuleFilenameTemplate: '../[resource-path]'
  },
  // devtool: 'source-map',
  // externals: {
  //   vscode: 'commonjs vscode', // the vscode-module is created on-the-fly and must be excluded. Add other modules that cannot be webpack'ed, 📖 -> https://webpack.js.org/configuration/externals/
  //   ws:'ws',
  //   "node-sp-auth-config":"node-sp-auth-config",
  //   "vscode-languageclient":"vscode-languageclient"
  // },
  externals: [nodeExternals()],
  resolve: {
    // support reading TypeScript and JavaScript files, 📖 -> https://github.com/TypeStrong/ts-loader
    extensions: ['.ts', '.js']
  },
  node:{
    __dirname:false,
    __filename:false
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'ts-loader'
          }
        ]
      }
    ]
  }
};
module.exports = config;
```
I think that will execlude all node_module, but even that didn't work.
I also did just transpile the client and transpiled the servers in the old way.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
Shouldn't be a problem when using LSP servers, a good sample is vscode-eslint: https://github.com/Microsoft/vscode-eslint. In essence you define a bundle for the client and for the extension part. Let us know if you have a concrete questions

**Comment by peni4142** [comment]
It seems  if I exclude a module with vscode-languageserver it suddenly need the entry point itself and looking at the wrong place. I also tried to explain that here:
https://stackoverflow.com/questions/55421167/webpack-output-requires-the-typescript-entrypoint-on-the-wrong-place
