### ISSUE TITLE
List of color scope in documentation

### ISSUE THREAD

**Issue by kanlukasz** [Microsoft/vscode#70305]
Hi

I think it will be good move if you will made a instruction for color scheme scopes

I talk about something like this in ST3 doc
(https://www.sublimetext.com/docs/3/scope_naming.html#color_schemes)

I know about https://macromates.com/manual/en/language_grammars but I think that it should be in your documentation along with a advice about **good practices**. I can't find any good practices about it

**Comment by roblourens** [comment]
Our color theme docs are here - https://code.visualstudio.com/api/extension-guides/color-theme, that's all we have currently.

And there isn't really a complete list of scopes since each theme can look for whatever it wants.
