### ISSUE TITLE
Weird scrollbar when hovering in debugger

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#70300]
v. 1.32.1 (Ubuntu)

When I hover over a variable in the debugger, vertical and sometimes horizontal scrollbars appear then fade out.

This is probably fine when the popup can be scrolled, but it's pointless if it can't.

This is particularly annoying when the variable you're inspecting has a single digit value as it completely obscures it.  :grin:

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/67643
