### ISSUE TITLE
Regression: WSL Shell Task command containing spaces fails

### ISSUE THREAD

**Issue by davidwin** [Microsoft/vscode#70307]
- VSCode Version: 1.32.1
- OS Version: Windows 10 16299.1004

Steps to Reproduce:

1. Create a shell task in `tasks.json` supposed to run under WSL:
```json
{
    "label": "My Task",
    "options": {
      "shell": {
        "executable": "${env:windir}\\system32\\wsl.exe",
      }
    },
    "type": "shell",
    "command": "ls / && echo OK # comment",
    "problemMatcher": []
}
```
2. Run "My Task". It will fail with the following error: 
```
> Executing task: ls / && echo OK # comment <

/bin/bash: ls / && echo OK # comment: No such file or directory
The terminal process terminated with exit code: 127
```
Does this issue occur when all extensions are disabled?: Yes

This behavior is new for 1.32 (present in Insider 1.33). By tracing the process invocation, I can see that the `command` property is enclosed within double quotes, causing WSL to interpret the whole script as a command file. The `args` property doesn't work properly either, causing all arguments to be enclosed within double quotes.

A possible, but unpleasant, workaround is to put the whole command into the `args` property of the `shell` options:

```json
{
    "label": "My Task",
    "options": {
      "shell": {
        "executable": "${env:windir}\\system32\\wsl.exe",
        "args": [ "ls", "/", "&&", "echo", "OK", "#", "comment" ]
      }
    },
    "type": "shell",
    "command": "",
    "problemMatcher": []
}
```

**Comment by davidwin** [comment]
After looking into this, I am beginning to suspect that 83c89be050e6692a9c1080fbb73b7fad198ce146 is the commit that caused the regression. The intention was to prevent `-e` from being added to old wsl (#67855), but the fix causes wsl.exe to be treated as Git Bash, which has other escaping rules and also requires the `-c` flag (which wsl.exe doesn't).

I propose that the code:
https://github.com/Microsoft/vscode/blob/83c89be050e6692a9c1080fbb73b7fad198ce146/src/vs/workbench/contrib/tasks/electron-browser/terminalTaskSystem.ts#L750-L758

is changed to:
```typescript
} else if ((basename === 'bash.exe') || (basename === 'zsh.exe')) {
	windowsShellArgs = false;
	if (!shellSpecified) {
		toAdd.push('-c');
	}
} else if (basename === 'wsl.exe') {
	if (!shellSpecified && (this.getWindowsBuildNumber() >= 17763)) {
		toAdd.push('-e');
	}
}
```
What do you think, @alexr00?

**Comment by alexr00** [comment]
@davidwin that looks like a reasonable fix. Will you be able to test it on your version of Windows if I merge it?

**Comment by davidwin** [comment]
Thanks for looking into this so quickly! I'm not sure about building (corporate environment), but I can definitely run the Insider build, if that helps. (And if push comes to shove, I can probably build Code here as well.)

For what it's worth, I found another workaround: By specifying the shell in tasks.json as `ubuntu1804.exe` (assuming that's your WSL distro of choice), Code will not try to enclose your command in extra quotes, but you need to add a `-c` flag manually:
```json
"options": {
      "shell": {
        "executable": "ubuntu1804.exe",
        "args": [ "-c" ]
      }
}
```

**Comment by alexr00** [comment]
I will push the fix then if you can try it in the next insider build then that would be great!

**Comment by alexr00** [comment]
Fix is pushed. @davidwin, let me know if it works ok in the next insiders build!

**Comment by davidwin** [comment]
Sure, I'll keep an eye out!

**Comment by davidwin** [comment]
I just tested this on Insider 7258b995f6, Windows 10 x64 16299, and your commit works great. I specified wsl.exe as the shell both in the tasks.json file and in User settings, both with and without arguments to the command.

Thanks again!

**Comment by alexr00** [comment]
Thanks so much for verifying this!
