### ISSUE TITLE
Random Message On The Terminal When Stopping The Debug Process

### ISSUE THREAD

**Issue by infixint943** [Microsoft/vscode#70304]
There is some sort of message that appears on the terminal after stopping the debug process of C++. This is what it looks like - 
![GtE4G](https://user-images.githubusercontent.com/45997896/54197092-098fd280-44e9-11e9-9e93-17c5c0751066.png)

1.Linux, 64 bit, Deepin 15.9
2.VS Code 1.31.1
3.G++ - 8, GDB 7.12
4.Extension used : C/C++ IntelliSense, debugging, and code browsing by Microsoft

Steps to Reproduce:
1. Change debug terminal to inbuilt
2. Start the debug process(GDB)
3. stop it by pressing on the red button

<h2>My .json files</h2>
c_cpp_properties.json
<pre>{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++-8",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}</pre>

launch.json
<pre>{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "setupCommands": [
                {
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}</pre>

tasks.json
<pre>{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "_runner": "terminal",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "g++-8",
            "args": [
                "-g",
                "${file}"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}</pre>

**Comment by weinand** [comment]
Please file this against the C++ debugger.

**Comment by infixint943** [comment]
I don't think it's a debugger problem since the words Microsoft appear in the message and the gdb is on linux

**Comment by weinand** [comment]
The C++ debugger is a Microsoft extension, and the error message is exactly pointing to that.
