### ISSUE TITLE
Cannot make CodeCompletionProvider for 'javascript'

### ISSUE THREAD

**Issue by Arilas** [Microsoft/vscode#7031]
- VSCode Version: 1.1
- OS Version: Linux | OS X

Quick example:
```js
vscode.languages.registerCompletionItemProvider('javascript', {
  provideCompletionItems() {
    console.log("I'm here")
    return []
  }
}, '.')
```
For new languages and for plain text it's works, but for 'javascript' you will see not see this console.log. In some strange actions (like many times pressing on Backspace inside some string) you will see this console.log, but if you will provide CompletionList or CompletionItem it's also will be ignored.

I know about score, but I'm not sure how to increase it, selectors like `{ language: 'javascript', scheme: 'file' }` doesn't works.

I'm working on next Flow extension https://github.com/Kr0na/flow-for-vscode but for now the only way to implement code completion is to make 'Flow' language that doesn't provide a power of IntelliSense and user should manually select it to use Flow completion

**Comment by Arilas** [comment]
I've also investigate to source code of VSCode and found this:
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/languageSelector.ts
So when I just put 'javascript' the score is 10, when `{ language: 'javascript', scheme: 'file' }` it will be 20

After this I look at the typescript extension and found registration of Code Completion for javascript:
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L134
So score for javascript in this case only 10

20 > 10 So `{ language: 'javascript', scheme: 'file' }` should be called before wildcard 'javascript'

**Comment by jrieken** [comment]
Good feedback. The behaviour when multiple provider contribute to a language feature is described in the `registerXYZProvider`-methods. For suggestion it is [this](https://github.com/Microsoft/vscode/blob/joh/paths/src/vs/vscode.d.ts#L3446): 

> Multiple providers can be registered for a language. In that case providers are sorted
> by their [score](#languages.match) and groups of equal score are sequentially asked for
> completion items. The process stops when one or many providers of a group return a
> result. A failing provider (rejected promise or exception) will not fail the whole
> operation.

This is a little special and different to the commonly used strategy of just merging all results. We made that decision to always have a _reasonable_ small list of completions. I can see how that bites you now and we should revise. 

Having  said that, the selector `{ language: 'javascript', scheme: 'file' }` should be equal to the one VS Code uses, therefore be in the same group, and consulted when completions are requested

**Comment by jrieken** [comment]
I think we should change the scoring wrt document filters. It should not be the sum but the max of each attribute whereas each value must be greater than zero.

**Comment by jrieken** [comment]
The effect of this change will introduce a small semantic change. Take two document selector

1. `{ language: 'javascript', scheme: 'file' }`
2. `{ language: 'javascript' }`

and a javascript file on disk which matches for both selectors. Today the scoring will favour the former selector cos it matches on `language` and `scheme`. The conclusion is that this doesn't make much sense and only the opposite should be true (the former should not match on an untitled buffer). 

This affects only completion provider cos other providers use a merging strategy. @egamma pls speak up if you think this is _semantic api breakage_.

**Comment by Arilas** [comment]
@jrieken I'm not sure that this fix is finally correct. Because seems that if I use this selector in code:
```{ language: 'javascript', scheme: 'file' }```
It will have score 10 even if:
1. All Documents that have scheme `'file'` (this includes css files, bin files, etc)
2. All Documents with language `'javascipt'` (for both file and in-memory)
So this commit change LanguageSelector from "and"(use as much as possible) to "or"(any of condition is true).

**Comment by Arilas** [comment]
Ok. Thanks

**Comment by wrygiel** [comment]
It there perhaps a way to *decrease* a score? In order for the extension to indicate that it wants its suggestions to be displayed after all the other providers? ([use case here](https://github.com/pmneo/ts-importer/issues/5))

**Comment by jrieken** [comment]
>  displayed after all the other 

You mean *sorting* or *only iff no other extensions as suggestions*?

**Comment by wrygiel** [comment]
I mean the ability for extension developers to express the fact that "my suggestions are usually less important than suggestions provided by other providers with the same document selector and there for I'd like vscode to display them on the bottom of the autosuggestions popup".

**Comment by jrieken** [comment]
Ok - for that you can use the [`sortText`](https://github.com/Microsoft/vscode/blob/joh/fmtprio/src/vs/vscode.d.ts#L2303) property

**Comment by wrygiel** [comment]
Thank you very much!

BTW, the link above seems to be to a private repository, [here](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2303)'s a public one.

**Comment by jrieken** [comment]
ops - I am working on a PR that I have pushed yet
