### ISSUE TITLE
Visual studio latest Update Showing error

### ISSUE THREAD

**Issue by neeleshthakur333** [Microsoft/vscode#70318]
when ever i try to update visual studio it pop up this message

There was an error while marking a file for deletion:
Failed to mark file for deletion:
Access is denied
Please verify these are no VS code processes still executing

then i always click cancel, then again another message poped up
Failed to install  VS code update
Updates may fail due to anti-virus software and/or runway processes
Please try restart your pc

**Comment by interglobalmedia** [comment]
Hi Jeffrey, I would like to attend the Entrepreneurship Council on March
27. Thanks!
Maria D. Campbell
Full Stack Developer
*I just love what I do. Let's work together!*
*Telephone: 212-532-2552*
*Cell: 646-369-6437*
Github Profile
<https://mailtrack.io/trace/link/16082f2ec211141e37f0cf02ecdd557ce3d3fa6b?url=https%3A%2F%2Fgithub.com%2Finterglobalmedia&userId=221357&signature=852f6f4ed6ed20c7>
Portfolio Site
<https://mailtrack.io/trace/link/df0bb3011c05fa86c037e453abbb5cc3e1f7d7b1?url=https%3A%2F%2Finterglobalmedia.github.io%2Fportfolio%2F%23%2F&userId=221357&signature=4c52fabb9c638e05>
http://mariadcampbell.com
<https://mailtrack.io/trace/link/9370994009aa0ed3b17c34b23bcc4e515a473dd3?url=http%3A%2F%2Fmariadcampbell.com%2F&userId=221357&signature=8f3579823064b9da>
https://twitter.com/letsbsocial1
<https://mailtrack.io/trace/link/76921ac444971afb27695d1b6eb1d8590cefc432?url=https%3A%2F%2Ftwitter.com%2Fletsbsocial1&userId=221357&signature=d9af69859accf030>
https://twitter.com/MariaDCampbell
<https://mailtrack.io/trace/link/df7fc97e1a6f8119788008fbc4544ce0819baf9d?url=https%3A%2F%2Ftwitter.com%2FMariaDCampbell&userId=221357&signature=e304c11a8cfe3f3d>
www.linkedin.com/in/mariacampbell/
<https://mailtrack.io/trace/link/318c7ebe6e07db6f1e0601fa78f1a04685afc45c?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fmariacampbell%2F&userId=221357&signature=96e6acc43855f369>

**Comment by neeleshthakur333** [comment]
what i actually going on here ?, i'm looking for solution. now who is jeffrey?

**Comment by joaomoreno** [comment]
@neeleshthakur333 The error message should've pointed you to a log file, can you send me that log file?

**Comment by prudhvirv** [comment]
Facing a similar issue. Attaching log file. Hope this will help.

[vscode-inno-updater-1554097373.log](https://github.com/Microsoft/vscode/files/3027917/vscode-inno-updater-1554097373.log)
