### ISSUE TITLE
Split up workbench/api into a node and browser part

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70319]
For https://github.com/Microsoft/vscode/issues/68302

We will eventually have to move our `vs/workbench/api/electron-browser/mainThread.*` files into `browser` or `common` to support running extensions without node integration. 

When I look at an example (`mainThreadLanguages.ts`) a common pattern seems to be a dependency to `node/extHost.protocol` which seems to contain both types for the renderer side as well as the extension host side.

As a first step I would think `node/extHost.protocol` needs to split up into 2 parts, where the one is clearly the types accessed within the extension host and the other from the renderer side (which then can live in `common` or `browser`).

Thoughts?

**Comment by jrieken** [comment]
> As a first step I would think node/extHost.protocol needs to split up into 2 parts, where the one is clearly the types accessed within the extension host and

I believe that `extHost.protocol` is pretty independent of node-api and it it can be moved to common, at least I would aim for that.

**Comment by bpasero** [comment]
@jrieken when I look at `extHostProtocol` it seems to reach into `extHostTypes` which eventually requires `vscode`. Otherwise, there are indeed not many dependencies to node/electron-browser it seems.

**Comment by jrieken** [comment]
The `vscode` module is always there

**Comment by bpasero** [comment]
@jrieken does it make sense to require `vscode` from the renderer though ever? Imho that should only be depended on from the extension host.

**Comment by jrieken** [comment]
Yes and No, in extHostTypes and other places that implement the API it does make sense, esp. with interfaces that we don't want to duplicate everywhere.

**Comment by jrieken** [comment]
* [ ] @joaomoreno for `mainThreadEditors`, [`resource.scheme === product.urlProtocol`](https://github.com/Microsoft/vscode/blob/02381f00b9c097e80407a3b78cc82614e72a7556/src/vs/workbench/api/electron-browser/mainThreadEditors.ts#L287-L289)
* [ ] @RMacfarlane for `mainThreadComments`
* [ ] @bpasero for `mainThreadConsole`
* [ ] @isidorn, @weinand  for `mainThreadDebug`
* [ ] @alexandrudima for `mainThreadExtensionService`
* [ ] @jrieken @alexandrudima for `mainThreadLanguageFeatures`
* [ ] @alexr00 for `mainThreadTask`
* [ ] @joaomoreno for `mainThreadUrls`
* [ ] @mjbvz for `mainThreadWebviews`

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/70319#issuecomment-472366964 - I have changed my mind, we shouldn't leak the `vscode`-module into our "normal" sources, e.g. outside the extension host. I have copied a couple of interfaces into `extHost.protocol.ts` and when moving things to `browser` you might have to do the same.

**Comment by bpasero** [comment]
The list is down to:

* [ ] @RMacfarlane for `mainThreadComments`
* [ ] @alexr00 for `mainThreadTask`
* [ ] @mjbvz for `mainThreadWebviews`

**Comment by alexr00** [comment]
Thanks @bpasero for moving mainThreadtTask.ts!
