### ISSUE TITLE
Azure Schema Store cannot be reached behind proxy

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#70310]
While almost all parts of Visual Studio Code seem to be able to reach the Internet, `https://schemastore.azurewebsites.net/schemas/json/tsconfig.json` cannot be reached:

```
Authentication Required
You must be authenticated to access this URL.
urlprotocol = "https";
statuscode=407;
URL:  break_line("https://schemastore.azurewebsites.net");
```

`HTTP_PROXY` and `HTTPS_PROXY` environment variables have both been set, like `HTTPS_PROXY=http://user:pwd@proxy.domain.loc:8080/`.

### VSCode/OS Version:

![image](https://user-images.githubusercontent.com/9283914/54204278-31c10680-44d4-11e9-97b1-f8d4fa2b8401.png)

### Does this issue occur when all extensions are disabled?
- [x] Yes
- [ ] No

![image](https://user-images.githubusercontent.com/9283914/54204260-24a41780-44d4-11e9-9f56-b0f77fec11eb.png)

All existing issues here are locked and seem unsolved. That's why I'm creating this new issue. I suspect the cause for this bug is a regression.

PS: It would be great if the fix for the corresponding portion in Code would use WinINET by default (on Windows machines) when `HTTP(S)_PROXY` environment variables are not set, so the system configured proxy would be used by default.

**Comment by joaomoreno** [comment]
#12588
