### ISSUE TITLE
Terminal Window closes with error on terminate a DocFx process in the terminal

### ISSUE THREAD

**Issue by EifelMono** [Microsoft/vscode#70315]
Issue Type: <b>Bug</b>

Terminal Window closes with error on terminate a DocFx process in the terminal
See video
https://github.com/EifelMono/ReportedBugs/blob/master/VisualStudioCodeWindows/VsCodeDocFxCrash.mp4

Visual Studio Code 1.32.1 DocFx 2.40.12.0

Create a folder
Open VSCode
Open Terminal
Run:  docfx init -q
Run:  docfx .\docfx_project\docfx.json --serve -p 4711 
Terminate process with CTRL C 
Wait: terminal closes with Error

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.60GB (48.96GB free)|
|Process Argv|C:\Temp\DocFxTest|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.5.3
azuretoolsforvscode|bra|2.0.2
cake-vscode|cak|0.11.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vs-code-xml-format|fab|0.1.5
chocolatey-vscode|gep|0.7.0
vscode-pull-request-github|Git|0.5.0
plantuml|jeb|2.10.6
vscode-azureappservice|ms-|0.13.0
vscode-azurefunctions|ms-|0.15.0
vscode-azurestorage|ms-|0.7.0
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
azurerm-vscode-tools|msa|0.5.0
debugger-for-chrome|msj|4.11.3
editorconfiggenerator|nep|0.2.1
quicktype|qui|12.0.46
vscode-icons|rob|8.2.0
vscode-open|san|0.1.0
vscode-zipexplorer|sle|0.3.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.4
omnipascal|Wos|0.17.1
markdown-all-in-one|yzh|2.1.1

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
