### ISSUE TITLE
changed files don't show up in 'source control' side bar

### ISSUE THREAD

**Issue by gozzoo** [Microsoft/vscode#70312]
- VSCode Version: 132.1
- OS Version: Windows 10 32 bit

Steps to Reproduce:

1. Chnage some file
2. Open 'Source control' panel

![image](https://user-images.githubusercontent.com/296970/54209628-c7fe2800-44e6-11e9-9f2d-6a70359a0a6e.png)

```
C:\work\project>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   server/connection.ts

no changes added to commit (use "git add" and/or "git commit -a")
```
If I restart VSCode it shows the changed files correctly.

**Comment by gozzoo** [comment]
I just remembered that I had added git path to `settings.json`

`  "git.path": "C:\\Program Files\\Git\\mingw32\\bin\\git.exe"`

I had to do it because 'Git History' plugin was complaining that it coudn't find git executable.

After I removed `git.path` from settings the problem disappeared.

**Comment by roblourens** [comment]
So this can be closed?

**Comment by gozzoo** [comment]
I think that this is a valid problem. Adding the correct path of the git executable shouldn't break the source control functionality in VSCode.

**Comment by roblourens** [comment]
VS Code needs windows git, not mingw git. https://git-scm.com/download/win

**Comment by gozzoo** [comment]
@roblourens Thanks for pointig this out. I actually do have windows git installed, but I checked and apparently the installation folder contains 2 git.exe files, one of them part of the mingw distribution. 

However:

1. Both of them are the same versoin and they should behave the same.
2. Even if the wrong one is specified VSCode should display an error message or a warning, instead of most source code functionality to disappear misteriously.

**Comment by joaomoreno** [comment]
If you run `Git: Show Git Output`, what's the outcome?

**Comment by gozzoo** [comment]
> If you run Git: Show Git Output, what's the output?

```
Looking for git in: C:\Program Files\Git\mingw32\bin\git.exe
Using git 2.11.1.windows.1 from C:\Program Files\Git\mingw32\bin\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\work\tansys
> git fetch
> git rev-parse --show-toplevel
> git status -z -u
fatal: Not a git repository (or any of the parent directories): .git
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git show :src/app/lib/connection.ts
> git check-ignore -z --stdin
> git show :server/connection.ts
> git pull --tags origin master
> git show :server/connection.ts
```
> If you create a file in the Windows Explorer, does it show up in VS Code?

![image](https://user-images.githubusercontent.com/296970/54361027-d0816a80-466e-11e9-9aa3-9c9d8238968f.png)

> Did you open the repository root as a folder in VS Code, or did you just open a file?

the repository root

**Comment by joaomoreno** [comment]
Can you fully uninstall all Git versions and reinstall it from https://git-scm.com/?

**Comment by gozzoo** [comment]
@joaomoreno I have only one git version and it is exactly that one. For some reason git for windows comes with multiple git.exe files.

```
C:\Program Files\Git>dir git.exe /s
 Volume in drive C has no label.
 Volume Serial Number is 11111-2222

 Directory of C:\Program Files\Git\bin

02/03/2017  08:39 AM           157,016 git.exe
               1 File(s)        157,016 bytes

 Directory of C:\Program Files\Git\cmd

02/03/2017  08:39 AM           157,016 git.exe
               1 File(s)        157,016 bytes

 Directory of C:\Program Files\Git\libexec\git-core

03/08/2015  02:21 PM         1,503,744 git.exe
               1 File(s)      1,503,744 bytes

 Directory of C:\Program Files\Git\mingw32\bin

02/03/2017  08:39 AM         2,291,048 git.exe
               1 File(s)      2,291,048 bytes

 Directory of C:\Program Files\Git\mingw32\libexec\git-core

02/03/2017  08:39 AM         2,291,048 git.exe
               1 File(s)      2,291,048 bytes
```

**Comment by joaomoreno** [comment]
It's pretty weird that Code picks up `C:\Program Files\Git\mingw32\bin\git.exe`, it should pick `C:\Program Files\Git\bin\git.exe`. When using that value in the setting, does it work?

**Comment by gozzoo** [comment]
> t's pretty weird that Code picks up C:\Program Files\Git\mingw32\bin\git.exe,

@joaomoreno I think it does because I put this in `settings.json`

`"git.path": "C:\\Program Files\\Git\\mingw32\\bin\\git.exe"`

I did it because the 'Git History' plugin couldn't figure out on its own the path to git.exe and I din't know that there were mutltiple git executables, so this is the first one I found.

**Comment by joaomoreno** [comment]
When using `C:\Program Files\Git\bin\git.exe` in the setting, does Code pick up the changes?

**Comment by gozzoo** [comment]
Weird. I just tested, the problem doesn't happen any more. Everything is working fine with mingw version of git.exe. It works fine even if I set wrong or not existing file name.

I have upgradet to 1.32.3, probably there are some git related fixes in this release.

**Comment by joaomoreno** [comment]
Alright, closing for now

**Comment by gozzoo** [comment]
I'm still not sure that this is correct behaivour because ignores the `git.path` settings gets ignored if it's not correct. I think users shoud be made aware if they put a wrong setting.
