### ISSUE TITLE
Shortcut for code formatting doesn't work

### ISSUE THREAD

**Issue by Dharmoslap** [Microsoft/vscode#7032]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. hit ⇧⌥F to format code
2. watch how " ̰" character appears instead of formatting code

**Comment by jrieken** [comment]
does work for me...

**Comment by Dharmoslap** [comment]
![vs code](https://cloud.githubusercontent.com/assets/3543614/15677624/5d6a1834-274b-11e6-8ee9-7ecfb88f86dc.gif)

**Comment by jrieken** [comment]
@Dharmoslap what is your expected behaviour? The TypeScript formatter doesn't remove empty lines, try with something like this: `console.log(    4)   ;`

**Comment by alexandrudima** [comment]
@Dharmoslap It looks like ⇧⌥F brings us in composition mode on your machine. What keyboard layout have you configured? What does ⇧⌥F do in other programs? You can always rebind the shortcut via `Preferences > Keyboard Shortcuts`. Here is how the default is defined:

```
{ "key": "shift+alt+f", "command": "editor.action.format",  "when": "editorTextFocus" }
```
