### ISSUE TITLE
tasks.json "dependsOn" property does not resolve variables/commands

### ISSUE THREAD

**Issue by SurfaceMcu99** [microsoft/vscode#70327]
Issue Type: <b>Bug</b>

Using the C/C++ extension.  The ${command:cpptools.activeConfigName}" works fine when it is used within a "command".   However, the request is to be able to use this value in a compound task to select the specific task to run.

When used as follows:

{
            "label": "Build Active Configuration",
            "dependsOn": "Build ${command:cpptools.activeConfigName}",
            "problemMatcher": []
        }

this error is generated:

Couldn't resolve dependent task 'Build ${command:cpptools.activeConfigName}' in workspace folder 'Source'

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
We do not resolve variables in dependsOn right now.

**Comment by Frotty** [comment]
@alexr00 you mentioned here https://github.com/Microsoft/vscode/issues/11396#issuecomment-449032341 that "You can now have commands", which is very unspecific.
It seems only commands that return a string can even be used because they then get replaced.
I have a command that requires a file input, and doesn't return string.
I tried 
```
	"tasks": [
    {
      "label": "test",
      "command": "${input:wbuild}",
    }
  ],
  "inputs": [
      {
          "id": "wbuild",
          "type": "command",
          "command": "wurst.buildmap",
      }
  ]
```
to no avail, since it always complains that it can't "substitute input variable".
Kind of strange that a more complex case works, but a basic dependency on a plugin's command doesn't...

**Comment by alexr00** [comment]
@Frotty, you still have to put something that can run in the "command" property:
```
		{
			"type": "shell",
			"command": "echo ${input:wbuild}",
			"problemMatcher": [],
			"label": "Example"
		}
```

**Comment by rohitkotak** [comment]
@alexr00 as said by @SurfaceMcu99, we want to run specific task from the task "Build Active Configuration" ("label": "Build Active Configuration"). And the name of the task which should be ran depends on the run time environment which is "Active configuration" (stored in command:cpptools.activeConfigName variable).

So in short we want to run the task whose name is stored in "command:cpptools.activeConfigName" variable. But as you said, dependsOn can not resolve the variable. So how to achieve this?

The issue which we are facing is, we are able to run command for the specific task but the problemMatcher of all the tasks(all the configurations) are different. So we are not able to use problemMatcher of that specific task(configuration) from task "Build Active Configuration".

**Comment by alexr00** [comment]
I don't see a way to accomplish that right now using only tasks.json. We do have a proposed API [here](https://github.com/microsoft/vscode/issues/66818) which might help you, but that API surface will be changing quite a lot.
