### ISSUE TITLE
Emmet - Several languages (php -> css + html)

### ISSUE THREAD

**Issue by Highter87** [Microsoft/vscode#70324]
In *.php file,  I want to use Emmett with the syntax option html + css.

Html use to create tags (div>ul>li*5)
Css is used in the built-in attribute (style="mt20")

I tried to do this in the settings, but don't work:

```
"emmet.includeLanguages": {
    "php": ["html", "css"]
}
```

How can this be combined?

**Comment by octref** [comment]
You can only use HTML emmet in PHP, sorry.
