### ISSUE TITLE
maintain cursor position when copying lines using ctrl+c, ctrl+v

### ISSUE THREAD

**Issue by hansifer** [microsoft/vscode#70333]
Copy Line Down (Shift + Alt + DownArrow) maintains cursor position. That's great.

However, copying a line using ctrl+c and ctrl+v (when there is no selection) places the cursor at the beginning of the copied line.

The cursor placement behavior should be consistent between the two methods of copying a line. The cursor position should be maintained in both cases.

**Comment by alexandrudima** [comment]
Let's track in #40695
