### ISSUE TITLE
[Question/Feature request] Show the list of errors using visual studio code editor

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/vscode#7033]
I can`t find a way to show the list of typescript build errors in an error list, like it works in visual studio 2015.

My motivation is that I do not want to click in each file to see the build/intellisense errors...

I would like to have a list of those errors in an integration window.

**Comment by Tyriar** [comment]
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd> is the shortcut for showing errors and warnings in all files. You can also click the icons with the numbers at the bottom of the screen

![image](https://cloud.githubusercontent.com/assets/2193314/15661931/153c79c6-26a1-11e6-95c5-510c1e33e27f.png)

**Comment by bastienJS** [comment]
Is there any chance of making the error "dialog" pin-able to the bottom/top? Maybe its already in the 1.2.0 release?

**Comment by Tyriar** [comment]
@bastienJS I don't think it's possible right now, you can file an issue specifically for that "Show errors/warnings in 'pinnable' panel" (or something) and it will get routed to the right person :smiley:

**Comment by bastienJS** [comment]
@Tyriar Hey hey quick answer ;-) Ok I will do that, thanks!

**Comment by Tyriar** [comment]
@bastienJS I'm most awake around this time :wink:

**Comment by bastienJS** [comment]
@Tyriar Man I can`t wait for the 1.2.0 release with the integrated CMD :-)

=> https://github.com/Microsoft/vscode/issues/7074

**Comment by Tyriar** [comment]
@bastienJS you can try it out now on the Insiders build, pretty eager for feedback to come in! http://code.visualstudio.com/insiders

**Comment by bastienJS** [comment]
@Tyriar Just installed it. So I get the latest visual code artifact from each day? Thats cool man. So I can give quick feedback if I see change in the behavior good/ bad ;-)

**Comment by Tyriar** [comment]
@bastienJS I think the daily change is going live next week with the stable build

**Comment by bastienJS** [comment]
@Tyriar I already experienced the not available scrollbar due to term.js, I am surprised that this is a javascript implementation, never thought of that. Is there a special reason for it? Just curious...

**Comment by Tyriar** [comment]
@bastienJS the root cause of that is because only the current viewport is represented in the DOM, it's probably the right way to go to save creating so many elements but a scroll bar would definitely be handy.

**Comment by bastienJS** [comment]
@Tyriar handy? hehe that was said mildly ;-) Without scrollbar, but more than ONE build error, its not usable at least in that context. Just think the integrated termin has a height of appr. 100px. When I run no "ng build" with more than an error I can see only the last error, the rest is cut.

**Comment by Tyriar** [comment]
@bastienJS it's still possible to scroll though with the mouse wheel and <kbd>ctrl</kbd>+<kbd>shift</kbd>+arrow or <kbd>ctrl</kbd>+<kbd>alt</kbd>+page up/down (on Linux/bash anyway). If you weren't aware of this I'd be interested in the platform you're on and which shell you're using.

**Comment by timhyson** [comment]
Hi @Tyriar, is there an equivalent to this for zsh?

**Comment by Tyriar** [comment]
@timhyson page up/down should work, I opened https://github.com/sourcelair/xterm.js/issues/181 to look into why the arrows don't.

**Comment by timhyson** [comment]
Ah ok, cool - I'm on a macbook pro, so fn + shift + ↑/↓ gets me there...  Many thanks.

**Comment by kevinjreece** [comment]
@waderyan: Hey Wade. I see how to show errors and warnings for files that are currently open (ctrl+shift+m). But is there are way to show errors and warnings for all files, even closed ones?

**Comment by echo-sean** [comment]
@kevinjreece I have the done the same thing and had to look at the terminal to find the errors. I think it would be useful to show something (a red circle?) next to each icon in the file explorer to indicate an error. I wonder if this is something the icon theme extensions would need to support though?

**Comment by guillaume86** [comment]
I'm also highly interested in project wide typescript error checking.
Should I open a new issue dedicated to this? (is it the right place?)

**Comment by waderyan** [comment]
@kevinjreece not today as far as I know but this is a good feature request. Can you open a new issue? Definitely something I would like to see as well.

**Comment by kevinjreece** [comment]
@echo-sean: Showing a red icon next to the file in the file explorer would be useful for small projects. But in my current project, we have hundreds of files nested many layers deep in multiple sub-directories. So red icons wouldn't fully solve the problem for me. What I need is a list of the errors by file so that I can see them in one place and quickly click through them, just like the "Problems" section they currently have

**Comment by kevinjreece** [comment]
I just created an issue to formalize this discussion: https://github.com/Microsoft/vscode/issues/13953

**Comment by echo-sean** [comment]
@kevinjreece Sorry, I wasn't very clear. I meant as an addition to the problems section of course.

**Comment by jiayihu** [comment]
Is there any setting to automatically open the warnings/errors on save if there are any of them?
