### ISSUE TITLE
Strict null check vs/workbench/contrib/preferences

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#70332]
The following files under `vs/workbench/contrib/preferences` need to be strict null checked:

- [x] `"./vs/workbench/contrib/preferences/browser/keybindingsEditor.ts"` 
- [x] `"./vs/workbench/contrib/preferences/browser/keybindingsEditorContribution.ts"`
- [x] `"./vs/workbench/contrib/preferences/browser/keybindingWidgets.ts"` 
- [x] `"./vs/workbench/contrib/preferences/browser/preferencesEditor.ts"` 
- [x] `"./vs/workbench/contrib/preferences/browser/preferencesRenderers.ts"`
- [x] `"./vs/workbench/contrib/preferences/electron-browser/preferences.contribution.ts"` 
- [x] `"./vs/workbench/contrib/preferences/test/browser/keybindingsEditorContribution.test.ts"`

Together, these files contain around 15% of the remaining strict null errors in our code

Note that these files may still be blocked from being added to the strict null list by their dependencies. Please just fix issues within these files themselves

**Comment by roblourens** [comment]
I am working on the preferences files but I attempted keybindingsEditor and got a bit lost, so maybe you can take those @sandy081
