### ISSUE TITLE
Strict null check src/vs/workbench/contrib/files

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#70338]
Tracks strict null checking files under `src/vs/workbench/contrib/files`

Some of these files have dependencies that are not strict null check enabled. You only need to worry about the errors under `src/vs/workbench/contrib/files`

**Comment by isidorn** [comment]
Assiging to march, if I do not find time I will push to next milestone.

**Comment by isidorn** [comment]
Done via ad107b8a92
