### ISSUE TITLE
vsc lost almost all open windows

### ISSUE THREAD

**Issue by baslr** [Microsoft/vscode#70348]
- VSCode Version: 1.32.1
- OS Version: macOS 10.12

just recognized that vsc restored only 3 of 10+ previously open windows.

Is there a chance that the saved state for the windows are still around?

Where are the logs to investigate what happened?
I copied the `Code` directory in `Application Support`

**Comment by roblourens** [comment]
- Did they have unsaved content?
- If you open one of the missing folders, is its state restored?

**Comment by Yzrsah** [comment]
This has happened to me 3 times in total. It's an uncommon occurrence, but it can happen. Somehow, there is no provision to make it impossible for this to happen. When it happened, the files in `~/Library/Application Support/Code/Backups` were simply gone.

**Comment by Yzrsah** [comment]
This has happened to me 3 times in total. It's an uncommon occurrence, but it can happen. Somehow, there is no provision to make it impossible for this to happen. When it happened, the files in `~/.config/Code/Backups` or `~/Library/Application Support/Code/Backups` were simply gone.

**Comment by baslr** [comment]
yes, the windows have unsaved content

hm, is this a bug or a feature? I just opened an existing window with cmd + shift + n then selected on under recent. It opened with the unsaved content.

When I close vsc and reopen it, it just opens the last one.

<img width="381" alt="Bildschirmfoto 2019-03-13 um 02 24 23" src="https://user-images.githubusercontent.com/1494154/54246941-2ce16e80-4537-11e9-8030-7a99c46c1a7e.png">

ok, its a new feature. Should be communicated better that the default is one now :S

**Comment by cedric05** [comment]
i prefer not opening last opened project. even after setting it to none. its opening last opened workspace.
`   "window.restoreWindows": "none",`
@roblourens

**Comment by Tyriar** [comment]
`window.restoreWindows` and `files.hotExit` drive the window restore behavior, read about them on settings and let us know if they're not working.
