### ISSUE TITLE
Python no name 'X' in module 'Y'

### ISSUE THREAD

**Issue by jnwarp** [Microsoft/vscode#70342]
Issue Type: <b>Bug</b>

Create the following directory structure:
```
- example/
  - test/
    - __init__.py
    - Test.py
  - __init__.py
- test.py
```

Use the following code:
```python
from example.test import Test
```

Expected behavior:
VS Code will correctly import the local module.

Actual behavior:
The code is marked as having the error "No name test in module example".
  

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.31GB free)|
|Process Argv|D:\Drive\Projects\PolySEED\Python-Doc\change.py|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
python|ms-|2019.2.5558

</details>

**Comment by roblourens** [comment]
Please file this on the python extension repo
