### ISSUE TITLE
Opened the file incomplete when is a big file

### ISSUE THREAD

**Issue by rodrigo36999** [Microsoft/vscode#70341]
- VSCode Version: 1.31.1 and Insiders version
- OS Version: Mojave 10.14.2

Steps to Reproduce:

1. Open VScode or Inside version
2. Install Remote Workspace plugin
3. Open a remote big file linked for Remote Workspace plugin
4. The file open incomplete
5. if you save the file this is saved incomplete this behavior is not only a visual error.

Does this issue occur when all extensions are disabled?: Yes/No
When I open same file in local machine this is displayed complete.

**Comment by roblourens** [comment]
This sounds like an issue with that extension, please file an issue on their repo
