### ISSUE TITLE
Explorer keeps spinning when accessing over VPN

### ISSUE THREAD

**Issue by m33ts4k0z** [Microsoft/vscode#70347]
- VSCode Version: Insiders 1.33
- OS Version: Windows 10 Pro x64
Does this issue occur when all extensions are disabled?: Yes

Using all the Insider and regular VSCode I could find and having all extensions disabled.

I'm trying to access a mapped drive using its local IP address over a VPN connection. 
I simply go to Windows Explorer and right click the folder choosing to open it with VSCode. It will open all the contents almost directly but when I will click to expand a subfolder, it will keep spinning for about 5 minutes. Then it looks like that navigating through the subfolders is really fast. 

The folder is big (About 1GB) but the files Im trying to access are only PHP code files. The server upload is 250Mbps and the client download is 100Mbps. Testing my internet over the VPN tunnel shows 100Mbps or more so no speed problem there.

I see an horizontal blue line at the very top of the project explorer and it seems like its loading. When that finishes it seems like everything opens really fast. Is it some caching that VSC does or...?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70045
