### ISSUE TITLE
Run selected text in integrated terminal

### ISSUE THREAD

**Issue by bernardocaldas** [Microsoft/vscode#7034]
We should be able to select some lines and have them sent to the terminal, either via a keyboard shortcut or by a right click action.

**Comment by DonJayamanne** [comment]
Can i suggest we expose this same functionality via a command as well - for extension developers.
This way extension developers can launch the integrated terminal window and run some commands to set up the environment or launch a program for CLI debugging.

**Comment by Tyriar** [comment]
@DonJayamanne a regular command (not extension API) would suffice for this?

**Comment by DonJayamanne** [comment]
Yes, that would.

**Comment by Tyriar** [comment]
@DonJayamanne you can try this out in Insiders tomorrow via the command palette, there is no keybinding though as everything seems to be taken (modifiers+enter, ctrl+shift+r)

**Comment by DonJayamanne** [comment]
@Tyriar, does this change also allow an extension developer to send some text to the terminal window?
What I would like to do is, use the terminal to for debugging python code.

**Comment by Tyriar** [comment]
It sends the selected text in the editor only, it's a command so it doesn't take arguments. I think https://github.com/Microsoft/vscode/issues/547 is what you're after.

**Comment by DonJayamanne** [comment]
@Tyriar, thanks, will check that out.
