### ISSUE TITLE
Disk loss when disk is full

### ISSUE THREAD

**Issue by Ektasahusahu** [Microsoft/vscode#70340]
Issue Type: <b>Bug</b>

please help me i lossed my data when disk is full is there us any way to get back my code

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
prettier-vscode|esb|1.8.1
react-native-snippet|jun|0.5.0
color-highlight|nau|2.3.0

</details>

**Comment by roblourens** [comment]
Sorry you lost some data. This sounds like https://github.com/Microsoft/vscode/issues/34915, please take a look at that issue.
