### ISSUE TITLE
last empty line not numbered

### ISSUE THREAD

**Issue by patleb** [Microsoft/vscode#70344]
The last empty line isn't numbered, why would anyone want this behavior, I don't get it.

was asked before here https://github.com/Microsoft/vscode/issues/69129

**Comment by glen-84** [comment]
Duplicate of #70126.

**Comment by patleb** [comment]
Well, this is debatable, I've asked a question which wasn't answered by the other opened issues. The UX part isn't addressed, which makes absolutely no sense.

**Comment by glen-84** [comment]
> The UX part isn't addressed ...

Issue #1027 explains the reason for this change. The way that it was released (as a breaking change without notifying users), is a bit unfortunate though.

**Comment by patleb** [comment]
I saw this discussion, but don't get why the change has been approved: the UX part hasn't been addressed (there was some mentions, but they have all been ignored). The arguments were about how a newline is represented OS-wise and in comparison to other editors but with the same argument about what a newline is, which has nothing to do with how you expect to see it in a editor. When I enter a newline, I expect to see a newline regardless of if there is content after or not and the number shows its presence, otherwise you need to put the cursor there to see it.

**Comment by glen-84** [comment]
What do you think about some kind of character/symbol to indicate that the last line ends with a `\n`?

Something like this:

![image](https://user-images.githubusercontent.com/261509/54355660-534ff880-4662-11e9-9a71-eee5fba170fd.png)

I mentioned this [here](https://github.com/atom/atom/issues/7787#issuecomment-332930211) as well (with some alternatives).

In that way, you know that the line is terminated, and where to place your cursor, without erroneously numbering that as a line.

**Comment by patleb** [comment]
I think that's a pretty good idea. I actually really didn't care about the number, but more about the fact that there is no indication that the last newline exists.

**Comment by rightaway** [comment]
@glen-84 That's a great idea. Otherwise we can't tell the difference if a file ends with a new line or if it doesn't. We want all files to end with a newline so if it doesn't then that difference should be apparent.

**Comment by Sshirsha** [comment]
Its to show that the code ends over there and if that have been numbered that would also have been compiled. All the lines which are number are compiled.

**Comment by patleb** [comment]
@Sshirsha, having expectation about how the editor behave and how your code (or compiler) behave are two different things. Regardless, it doesn't show anything: that's the issue.

**Comment by HRK44** [comment]
Was about to create an issue but this one popped, it's very annoying to open the file and we don't know if there is an empty line or no at the end. I have to manually click to see it...very confusing.

![Screenshot from 2019-03-22 16-53-12](https://user-images.githubusercontent.com/7391040/54835906-6480b100-4cc3-11e9-94c7-09b8c4fc3340.png)

**Comment by patleb** [comment]
Closing this issue, the current release has the new setting:

```json
"editor.renderFinalNewline": false,
```

which could be activated by changing the value to `true`.
