### ISSUE TITLE
No textDocument/signatureHelp message is sent to our C/C++ extension after an edit/selection change if our response takes too long

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#70354]
- VSCode Version: 1.32.1
- OS Version: Windows

Steps to Reproduce:

1. Use our C/C++ extension.
2. Type something like
```
std::string s;
s.append(""); 
```
in a C/C++ file to generate signatureHelp, followed by edits. It needs to be in a file that takes long enough for us to send the response back. Adding a 5 second sleep to our code gives a 100% repro.

Bug: We never get a textDocument/signatureHelp message after the didChange and textEditorSelectionChange.

textDocument/signatureHelp
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
// no signatureHelp message

This causes the signatureHelp UI to get stuck.

I don't believe this is a bug with our extension code. It only repros if our signatureHelp response takes "too long".

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
@joaomoreno I do believe this is due the request throttling using the delayer but I might be wrong.

**Comment by joaomoreno** [comment]
@sean-mcmanus Can you reproduce this in a small extension sample?

@jrieken Any other pointers? Where do you use the delayer? What did you observe?

**Comment by jrieken** [comment]
> Where do you use the delayer?

I do not use the delayer ;-) Pretty sure that its your or @mjbvz codes

**Comment by joaomoreno** [comment]
@jrieken Could you reproduce this?

**Comment by sean-mcmanus** [comment]
Yeah, I found an easy repro using the open source sqlite3.c file (I used version 3.13.9, but any should work). Spme of the slowness and failure to respond to cancelRequest has been fixed with our pending 0.22.0, but this bug still repros with that.

See this screenshot -- I just use Ctrl+Shift+Space after the ( to trigger signature help (you should see the signatureHelp message appear in the C/C++ panel (after setting C_Cpp.loggingLevel to "Debug") and then type a space, and then use Fn+Right arrow to move the cursor to the right of the ;
![image](https://user-images.githubusercontent.com/19859882/54310868-9e014000-4590-11e9-97df-5128eb3a9936.png)

**Comment by mjbvz** [comment]
Signature help requests are throttled and file change will cause the requests to be deferred. To make sure I understand the bug, for the file:

```c++
std::string s;
s.append(""); 
```

- Manually trigger sig help after the `(`. This takes a long time to resolve
- Before it resolves, make an edit
- This should cancel the existing requests and trigger a new request. But this does not happen?

**Comment by sean-mcmanus** [comment]
That is sort of correct, but after further investigation I discovered the repro is a little tricker.
1. With a single edit, we DO receive a cancel request, and we DO receive a 2nd signatureHelp (i.e. the bug won't repro), but if the selection changes after that 1st signatureHelp and/or if a 2nd edit occurs, then it causes the signatureHelp request to not be sent.

e.g.

textDocument/signatureHelp: 149
$/cancelRequest: 149
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/signatureHelp: 150 // correct

but then...
textDocument/didChange
and/or
textDocument/textEditorSelectionChange

and we get back no signatureHelp.

If I add a sleep to our signatureHelp handler, I'm able to repro the bug with a simple file with just
```
int main() {
main(  ); // signature help, edit, selection change here
return 0;
}
```

**Comment by mjbvz** [comment]
Thanks. Steps to repo with js/ts:

1. On this line (https://github.com/Microsoft/vscode/blob/d3443fd68d625c980325e1571066850e943dfbef/extensions/typescript-language-features/src/features/signatureHelp.ts#L27), add:

```ts
		await new Promise(resolve => setTimeout(resolve, 3000));
```

1. Running VS Code oss from source
2. Open a ts file
1. start with:

```ts
console.log
```

1. type out `(a);`. The line should end up as `console.log(a);` with the cursor at the end

**Bug**

1. See signature help triggered after a short delay.

**Comment by mjbvz** [comment]
@sean-mcmanus Please test out the next VS Code insiders build. Based on my observations the problem should be fixed but I wasn't able to test against the C++ extension

**Comment by sean-mcmanus** [comment]
@mjbvz Sure, I'll let you know. Thanks.

**Comment by sean-mcmanus** [comment]
@mjbvz It isn't fixed with Insiders with date 03-13T06:18. Is that the build with the fix or the next one?

**Comment by joaomoreno** [comment]
Thanks for the great info @sean-mcmanus and for the investigation and fix @mjbvz.

**Comment by sean-mcmanus** [comment]
@mjbvz It's fixed with the latest Insiders. 03-14. Thanks a lot for the fast turn around.
