### ISSUE TITLE
Enable noImplictAny in codebase

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#70352]
We should look into enabling TypeScript's `noImplicitAny` in the codebase as it can help catch issues where errors were unexpectedly suppressed by `any`

**Comment by bpasero** [comment]
Yes please 👍

**Comment by bpasero** [comment]
Draft PR: https://github.com/Microsoft/vscode/pull/70797

**Comment by mjbvz** [comment]
To fix these errors:

1. In `./src/tsconfig.base.json`, change the line `"noImplicitAny": false` to:

    ```json
		"noImplicitAny": true,
		"suppressImplicitAnyIndexErrors": true,
    ```

1. Start a compile

**List of errors**
- [ ] Outline / breadcrumbs @jrieken 

```
vs/workbench/contrib/outline/browser/outlinePanel.ts(371,85): Parameter 'editor' implicitly has an 'any' type.
vs/workbench/contrib/outline/browser/outlinePanel.ts(371,93): Parameter 'event' implicitly has an 'any' type.
vs/workbench/browser/parts/editor/breadcrumbsModel.ts(208,8): 'parent' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

- [ ] debug @isidorn 
vs/workbench/contrib/debug/browser/callStackView.ts(112,13): Parameter 'element' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/callStackView.ts(124,34): Parameter 'e' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/watchExpressionsView.ts(66,32): Parameter 'element' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/watchExpressionsView.ts(67,68): Parameter 'e' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/baseDebugView.ts(129,2): 'enableInputBox', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/debug/browser/breakpointsView.ts(79,68): Parameter 'e' implicitly has an 'any' type.
vs/workbench/contrib/debug/node/terminals.ts(74,109): Parameter 'config' implicitly has an 'any' type.
vs/workbench/contrib/debug/electron-browser/rawDebugSession.ts(500,29): Parameter 'response' implicitly has an 'any' type.
vs/workbench/contrib/debug/electron-browser/debug.contribution.ts(527,60): Parameter 'order' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/variablesView.ts(79,32): Parameter 'element' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/variablesView.ts(80,68): Parameter 'e' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/repl.ts(376,32): Parameter 'element' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/repl.ts(378,68): Parameter 'e' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/loadedScriptsView.ts(427,13): Parameter 'element' implicitly has an 'any' type.
vs/workbench/contrib/debug/browser/loadedScriptsView.ts(430,34): Parameter 'element' implicitly has an 'any' type.
vs/workbench/contrib/debug/common/debugUtils.ts(202,37): Parameter 'arg' implicitly has an 'any' type.
vs/workbench/contrib/debug/common/debug.ts(171,2): 'logToRepl', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/debug/common/debug.ts(474,2): 'onRequest', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/debug/common/debug.ts(475,2): 'onEvent', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/api/node/extHostDebugService.ts(999,2): 'start', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/api/node/extHostDebugService.ts(1000,2): 'send', which lacks return-type annotation, implicitly has an 'any' return type.
```

- [ ] themes @aeschli 

```
vs/workbench/contrib/themes/browser/themes.contribution.ts(79,24): Parameter 'theme' implicitly has an 'any' type.
vs/workbench/contrib/themes/browser/themes.contribution.ts(80,21): Parameter 'theme' implicitly has an 'any' type.
vs/workbench/contrib/themes/browser/themes.contribution.ts(116,25): Parameter 'theme' implicitly has an 'any' type.
vs/workbench/contrib/themes/browser/themes.contribution.ts(139,24): Parameter 'theme' implicitly has an 'any' type.
vs/workbench/contrib/themes/browser/themes.contribution.ts(140,21): Parameter 'theme' implicitly has an 'any' type.
vs/workbench/contrib/themes/browser/themes.contribution.ts(174,18): Parameter 'theme' implicitly has an 'any' type.
vs/workbench/services/themes/common/workbenchThemeService.ts(59,2): 'restoreColorTheme', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/services/themes/browser/workbenchThemeService.ts(261,124): Parameter 'devThemes' implicitly has an 'any' type.
vs/platform/theme/common/colorRegistry.ts(64,2): 'deregisterColor', which lacks return-type annotation, implicitly has an 'any' return type.

```

- [ ] Preferences @roblourens @sandy081 

```
vs/workbench/contrib/preferences/browser/settingsTree.ts(442,20): Parameter 'value' implicitly has an 'any' type.
vs/workbench/contrib/preferences/browser/settingsTree.ts(701,22): Parameter 'obj' implicitly has an 'any' type.
vs/workbench/contrib/preferences/browser/settingsTree.ts(904,7): Parameter 'v' implicitly has an 'any' type.
vs/workbench/contrib/preferences/browser/settingsWidgets.ts(406,20): Parameter 'edited' implicitly has an 'any' type.
vs/workbench/contrib/preferences/electron-browser/preferencesSearch.ts(290,10): Parameter 'r' implicitly has an 'any' type.
vs/workbench/contrib/preferences/electron-browser/preferencesSearch.ts(450,95): Parameter 'searchDescription' implicitly has an 'any' type.
```

- [ ] SCM

```
vs/workbench/contrib/scm/browser/scmViewlet.ts(237,37): Parameter 'r' implicitly has an 'any' type.
```

- [ ] Explorer @bpasero 
vs/workbench/contrib/files/browser/views/explorerView.ts(288,13): Parameter 'stat' implicitly has an 'any' type.
vs/workbench/contrib/files/browser/views/explorerView.ts(291,34): Parameter 'stat' implicitly has an 'any' type.
```

- [ ] Terminal @Tyriar 

```
vs/workbench/contrib/terminal/common/terminal.ts(649,2): 'addDisposable', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/terminal/common/terminal.ts(650,2): 'dispose', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/terminal/common/terminal.ts(651,2): 'createProcess', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/externalTerminal/electron-browser/externalTerminalService.ts(74,24): Parameter 'spawner' implicitly has an 'any' type.
vs/workbench/contrib/externalTerminal/electron-browser/externalTerminalService.ts(195,24): Parameter 'spawner' implicitly has an 'any' type.
vs/workbench/contrib/externalTerminal/electron-browser/externalTerminalService.ts(279,24): Parameter 'spawner' implicitly has an 'any' type.
```


- [ ] Extensions @sandy081 

```
vs/workbench/services/extensions/node/proxyResolver.ts(518,19): Parameter 'blob' implicitly has an 'any' type.
vs/workbench/services/extensions/electron-browser/extensionHostProcessManager.ts(323,34): Parameter 'totalLength' implicitly has an 'any' type.
vs/workbench/contrib/extensions/electron-browser/extensionsViewlet.ts(340,13): Parameter 'item' implicitly has an 'any' type.
vs/workbench/contrib/extensions/electron-browser/extensionsViewlet.ts(346,21): Parameter 'query' implicitly has an 'any' type.
vs/workbench/contrib/extensions/electron-browser/extensionTipsService.ts(1011,48): Parameter 'id' implicitly has an 'any' type.
```

- [ ] Others

```
vs/workbench/services/files/node/remoteFileService.ts(410,26): Parameter '_' implicitly has an 'any' type.
vs/workbench/contrib/comments/electron-browser/commentService.ts(68,2): 'setActiveCommentThread', which lacks return-type annotation, implicitly has an 'any' return type.
vs/workbench/contrib/comments/electron-browser/commentService.ts(69,2): 'setInput', which lacks return-type annotation, implicitly has an 'any' return type.
vs/base/parts/ipc/node/ipc.net.ts(255,10): Member '_totalLength' implicitly has an 'any' type.
vs/platform/update/electron-main/updateService.win32.ts(195,34): Parameter 'one' implicitly has an 'any' type.
vs/platform/storage/node/storageMainService.ts(262,32): Parameter 'row' implicitly has an 'any' type.
vs/platform/configuration/common/configurationModels.ts(491,20): Parameter 'keys' implicitly has an 'any' type.
vs/platform/actions/browser/menuItemActionItem.ts(92,154): Parameter 'getAlternativeActions' implicitly has an 'any' type.
vs/workbench/api/node/extHostSearch.ts(110,21): Parameter 'ev' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(622,64): Parameter 'scheme' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(622,72): Parameter 'provider' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(629,64): Parameter 'scheme' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(629,72): Parameter 'provider' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(644,53): Parameter 'listener' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(644,63): Parameter 'thisArg' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(644,73): Parameter 'disposables' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(647,54): Parameter 'listener' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(647,64): Parameter 'thisArg' implicitly has an 'any' type.
vs/workbench/api/node/extHost.api.impl.ts(647,74): Parameter 'disposables' implicitly has an 'any' type.
vs/editor/contrib/rename/renameInputField.ts(119,33): Parameter 'focusEditor' implicitly has an 'any' type.
vs/editor/contrib/hover/modesContentHover.ts(405,48): Argument of type 'TextEdit[] | { identifier: null; range: Range; text: string; forceMoveMarkers: boolean; }[]' is not assignable to parameter of type 'IIdentifiedSingleEditOperation[]'.
  Type 'TextEdit[]' is not assignable to type 'IIdentifiedSingleEditOperation[]'.
    Type 'TextEdit' is not assignable to type 'IIdentifiedSingleEditOperation'.
      Types of property 'range' are incompatible.
        Type 'IRange' is missing the following properties from type 'Range': isEmpty, containsPosition, containsRange, plusRange, and 7 more.
vs/editor/contrib/hover/modesContentHover.ts(409,49): Argument of type 'TextEdit[]' is not assignable to parameter of type 'IIdentifiedSingleEditOperation[]'.
vs/editor/contrib/folding/indentRangeProvider.ts(21,11): Member 'decorations' implicitly has an 'any' type.
vs/workbench/browser/workbench.ts(85,13): Parameter 'err' implicitly has an 'any' type.
vs/workbench/browser/editor.ts(179,52): Parameter 'descriptor' implicitly has an 'any' type.
vs/code/electron-main/main.ts(215,77): Parameter 'error' implicitly has an 'any' type.
vs/base/node/storage.ts(697,34): Parameter 'error' implicitly has an 'any' type.
vs/base/browser/event.ts(16,13): Parameter 'e' implicitly has an 'any' type.
vs/base/browser/event.ts(30,2): 'preventDefault', which lacks return-type annotation, implicitly has an 'any' return type.
vs/base/browser/event.ts(31,2): 'stopPropagation', which lacks return-type annotation, implicitly has an 'any' return type.
```

**Comment by bpasero** [comment]
I did quite a few that were easy enough, down to ~30 🥇

**Comment by isidorn** [comment]
Done mine via a94502f9df and b56df1120b

**Comment by Tyriar** [comment]
Only 4 left!

Extensions:

```
[07:52:20] Error: /Users/daimms/dev/Microsoft/vscode/src/vs/workbench/services/extensions/node/proxyResolver.ts(518,19): Parameter 'blob' implicitly has an 'any' type.
[07:52:20] Error: /Users/daimms/dev/Microsoft/vscode/src/vs/workbench/contrib/extensions/electron-browser/extensionTipsService.ts(1011,48): Parameter 'id' implicitly has an 'any' type.
```

contrib/hover:

```
[07:52:20] Error: /Users/daimms/dev/Microsoft/vscode/src/vs/editor/contrib/hover/modesContentHover.ts(405,48): Argument of type 'TextEdit[] | { identifier: null; range: Range; text: string; forceMoveMarkers: boolean; }[]' is not assignable to parameter of type 'IIdentifiedSingleEditOperation[]'.
  Type 'TextEdit[]' is not assignable to type 'IIdentifiedSingleEditOperation[]'.
    Type 'TextEdit' is not assignable to type 'IIdentifiedSingleEditOperation'.
      Types of property 'range' are incompatible.
        Type 'IRange' is missing the following properties from type 'Range': isEmpty, containsPosition, containsRange, plusRange, and 7 more.
[07:52:20] Error: /Users/daimms/dev/Microsoft/vscode/src/vs/editor/contrib/hover/modesContentHover.ts(409,49): Argument of type 'TextEdit[]' is not assignable to parameter of type 'IIdentifiedSingleEditOperation[]'.
```
