### ISSUE TITLE
Support for fold/expand shortcuts in explorer

### ISSUE THREAD

**Issue by harryi3t** [microsoft/vscode#70357]
We already have this awesome feature of folding/expanding multiple levels in the editor 👍 
![image](https://user-images.githubusercontent.com/5207331/54252925-c9753200-4572-11e9-94fb-1bfa880eaecb.png)

This feature request is about extending the same feature for the explorer. 
I tried searching for this issue but couldn't find one. Feel free to close this if it's is a duplicate request.

**Comment by isidorn** [comment]
This feature request should be for all trees forwarding to @joaomoreno

**Comment by potatoqualitee** [comment]
can it please be an icon on the side thing? instead of just Collapse All, I would like Expand All as its opposite. 

![image](https://user-images.githubusercontent.com/8278033/57473879-2a7a6700-7291-11e9-9fd8-4ba2883600cf.png)

**Comment by giammi56** [comment]
Is to expand all feature implemented now?

**Comment by lukamo1996** [comment]
When is this functionality coming?
