### ISSUE TITLE
Several "& &" on the menu when language is Brazilian Portuguese

### ISSUE THREAD

**Issue by Wellvergton** [Microsoft/vscode#70364]
- VSCode Version: Commit 1.32.1
- OS Version: Ubuntu 16.04.6

Steps to Reproduce:

1. Open the editor
2. Navigate through the options in the menu

Does this issue occur when all extensions are disabled?: Yes

**Comment by whizzo** [comment]
Same with Spanish Language Pack.
And, the menus are white even though I have a dark theme.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/70245
