### ISSUE TITLE
shortcut to collapse all in outline view

### ISSUE THREAD

**Issue by glacjay** [microsoft/vscode#70369]

**Comment by sandy081** [comment]
@jrieken Outline view is not a custom view and is contributing collapse all action by itself.

**Comment by jrieken** [comment]
True, my mind was on the references view...

**Comment by bolariin** [comment]
I would like to try to resolve this.

**Comment by jrieken** [comment]
sure: this is where things are wired up: https://github.com/Microsoft/vscode/blob/5f48c695deb5ad61e9de084d15adf47a2482308f/src/vs/workbench/contrib/outline/browser/outlinePanel.ts#L387

**Comment by jrieken** [comment]
cc @isidorn

**Comment by isidorn** [comment]
Should there be just one shorcut for all trees so the experience is the same across the product?
fyi @joaomoreno

**Comment by jrieken** [comment]
Yes, one shortcut for them all

**Comment by bolariin** [comment]
@jrieken thanks for the direction. I have looked through `outlinePanel.ts`, I have also been looking into adding keyboard shortcuts. I noticed the use of `KeybindingsRegistry.registerCommandAndKeybindingRule` to add keyboard shortcuts. I wanted to verify if using this to create a shortcut would be the right approach.
