### ISSUE TITLE
为什么没有等宽字体 中英文不能对齐~~~~

### ISSUE THREAD

**Issue by hyl24lee** [Microsoft/vscode#70368]
为什么没有等宽字体 中英文不能对齐~~~~

**Comment by roblourens** [comment]
I don't understand the problem. Please describe in more detail

**Comment by yume-chan** [comment]
Literally it says:

> Without a mono-space font family, why can not Chinese and English characters be aligned?

But I can not understand what it means.

**Comment by zhanghuimeng** [comment]
I don't know if it is an issue with VScode itself, but you can install a font named Sarasa-Gothic to solve this problem for Chinese. See [在VSCode中使用（汉字）等宽字体](https://zhanghuimeng.github.io/post/using-chinese-monospace-in-vscode/).
