### ISSUE TITLE
Set Next Statement support please.

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#70366]
It's been more than 12 months, can we re-open https://github.com/Microsoft/vscode/issues/12514 please?

**Comment by HoppeMateusz** [comment]
That feature is very useful, all other GUI IDEs have that.
Do you consider adding that?

I would really like to have ability to move next instruction pointer in C++ debugger.

**Comment by isidorn** [comment]
This is supported now. We call it Jump To Cursor.
Not all debuggers support it yet. C# should work.
If your extension does not support it please file this feature request against that extension. Thanks
