### ISSUE TITLE
Workspace auto execute script

### ISSUE THREAD

**Issue by nasiruddin-saiyed** [Microsoft/vscode#70370]
As i'm using vscode since a year now, i have all of the projects configured in each work space, i was searching through docs and not able to get anything about execution of some script on opening workspace.  Please have a look at what i am going to apply for a new feature request, please forgive me this is first time of mine. 

In settings.json 

- We could have an option for auto-execution script default it should be `npm start` from ```package.json```  It will save time for everytime to open terminal and execute script for every running MEAN app / Node.js Server. 

- On opening vscode prompt user to execute script.
- Accepting prompt should execute script while opening terminal.
- It should be able to configure multiple folder in a single workspace i.e if i have an Angular Client with a Node server in different dir. 

Happy Coding!!

**Comment by nasiruddin-saiyed** [comment]
@Tyriar Do you have any solution to this ?

**Comment by Tyriar** [comment]
You can use tasks to run things when you open a folder. Other than that you could always write an extension.

https://code.visualstudio.com/docs/editor/tasks#_run-behavior
