### ISSUE TITLE
Feature Request - Drag from Project Explorer to import file path

### ISSUE THREAD

**Issue by syedsimanta03** [Microsoft/vscode#70373]
For example on Dragging an image to an HTML file, it would create a <img src="..."> with the relative path of the image already filled out. The same for CSS and JS files.

Also when Dragging a PHP file to a PHP file it would create a requirement of that script

Also, is it possible to open multiple windows for same project on different monitor screens?

**Comment by roblourens** [comment]
> Also, is it possible to open multiple windows for same project on different monitor screens?

Not quite due to technical limitations but you can open multiple workspaces with the same folder (Open empty window, "Add folder to workspace")
