### ISSUE TITLE
File changes not reflected

### ISSUE THREAD

**Issue by arunstar** [Microsoft/vscode#70379]
Issue Type: <b>Bug</b>

When files are added to VS Code project from other resources its not reflecting in VS Code editor. I have tried increasing the watches as per the microsoft documentation. still getting error like unbale to watch for file changes.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-06T08:51:24.856Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 1769)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.67GB (1.67GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
vscode-icons|rob|8.2.0

</details>

**Comment by roblourens** [comment]
Please describe the issue with exact steps. Also please try updating to 1.32.
