### ISSUE TITLE
emmet tab completion is slow

### ISSUE THREAD

**Issue by hassanbinsafdar** [microsoft/vscode#70371]
vs code Version : 1.32.1
Mac Os : 10.14.3
Hello I got a problem after to update my vscode . before it was working perfectly. Even i disabled all my extensions. But still its giving me issues and my workflow is disturbing.

I am going to attach a gif so you can check Thanks .

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13061479/54262238-8a090e80-458f-11e9-9b35-0de5e1c46f66.gif)

**Comment by roblourens** [comment]
Is your CPU busy? You could open Activity Monitor to check.

**Comment by hassanbinsafdar** [comment]
@roblourens I am going to attach cpu load  no cpu is not busy Thanks
<img width="808" alt="Screen Shot 2019-03-14 at 11 53 52 AM" src="https://user-images.githubusercontent.com/13061479/54337238-1b3fba00-4650-11e9-950e-9d1c268c5c10.png">

**Comment by hassanbinsafdar** [comment]
@roblourens  I created new html file and i found that this issue only occurs when html file is lengthy
but on fresh file its not happening .

**Comment by hassanbinsafdar** [comment]
@roblourens I made new gif you will get complete idea whats happening it will be helpful to identify issue. Thanks
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13061479/54341833-ae7eec80-465c-11e9-9b20-0f820dfdcf47.gif)

**Comment by octref** [comment]
I can repro this by putting everything in view-source:https://microsoft.github.io/language-server-protocol/specification in a single html file and typing in it.

**Comment by hassanbinsafdar** [comment]
@octref why this is not resolved yet when it will be resolved still not resolved in insiders as well

**Comment by octref** [comment]
Verifier: Test that emmet works as expected in various embedded languages in HTML, such as css/js (suggestion in css, no suggestion in js).

Test in large documents, such as the source of https://microsoft.github.io/language-server-protocol/specification, emmet completion is reasonably fast (compare with stable).

**Comment by hassanbinsafdar** [comment]
@octref Yes in css its working completely fine but in html large file not working same issue as i showed you if you want i can make gif , vs code version and will show you issue. Thanks

**Comment by hassanbinsafdar** [comment]
Here is my gif vs code version 1.36.1 My html file has 4992 lines of code. 
![vscode](https://user-images.githubusercontent.com/13061479/62108465-8b7b6f00-b2c3-11e9-9325-cca68e398640.gif)

**Comment by octref** [comment]
The change is not in Insiders yet, wait a bit.

**Comment by octref** [comment]
Fixed by https://github.com/microsoft/vscode/pull/78207.
