### ISSUE TITLE
I have issue when running my project angular

### ISSUE THREAD

**Issue by khanhndevizi** [Microsoft/vscode#70378]
When i run my project, cpu max 100%, i can't more action :(

![Screenshot 2019-03-13 16 01 59](https://user-images.githubusercontent.com/48306525/54267896-ab2c2800-45ac-11e9-8148-25efbe6a2967.png)
![Screenshot 2019-03-13 16 05 37](https://user-images.githubusercontent.com/48306525/54267897-ab2c2800-45ac-11e9-9e88-9e059f98be52.png)

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by roblourens** [comment]
Please see the steps in this wiki page to provide more info for us: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu
