### ISSUE TITLE
No localization "ru-RU" to "Toggle Integrated Terminal"

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#7038]
- VSCode Version: 1.2.0-insider
- OS Version: win7

No localization "ru-RU" to "Toggle Integrated Terminal"
![2016-05-31_09h48_47](https://cloud.githubusercontent.com/assets/3082812/15665781/a79f6ffc-2715-11e6-879a-4bb2717e7c64.png)

**Comment by jrieken** [comment]
Translation team was a little late this time and we were eager to push insiders... Will be proper with the stable release

**Comment by dbaeumer** [comment]
Closing since this will be fixed in next stable release.
