### ISSUE TITLE
Selected tree icons hardly visible in light+ theme

### ISSUE THREAD

**Issue by ralfstx** [Microsoft/vscode#70380]
With the (default) Light+ color theme, icons in selected tree items in the Git view are black on dark blue. They should probably be inverted.

![image](https://user-images.githubusercontent.com/255637/54268974-aea7bb00-457c-11e9-8618-de894aaaa91a.png)

- VSCode Version: 1.32.1
- OS: Linux x64 4.15.0-46-generic

**Comment by usernamehw** [comment]
Duplicate of #55857
