### ISSUE TITLE
git status issue

### ISSUE THREAD

**Issue by mlushpenko** [Microsoft/vscode#70381]
Issue Type: <b>Bug</b>

Since the last 1-2 releases, I started seeing issues with file explorer and source control. I edit some file, save it, and then file exporer together with source control window don't show any changes while git status from command line does.

It doesn't happen always, maybe it's more related to workspaces with mutiple projects, not sure.

Screenshot of file explorer
![image](https://user-images.githubusercontent.com/2006610/54271744-6be8e180-4582-11e9-9b00-3f49558bb2ef.png)

Screenshot of source control
![image](https://user-images.githubusercontent.com/2006610/54271820-8de26400-4582-11e9-8982-99ff5982ba2b.png)

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|-psn_0_73746|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
scala|dal|0.0.5
gitlens|eam|9.5.1
json-tools|eri|1.0.2
hadolint|exi|0.3.0
gitlab-workflow|fat|2.0.1
jsonnet|hep|0.1.0
terraform|mau|1.3.8
python|ms-|2019.2.5558
Go|ms-|0.9.2
python-docs|Muk|0.8.3
vscode-docker|Pet|0.5.2
jinjahtml|sam|0.8.0
bash-beautify|sha|0.1.1
shellcheck|tim|0.6.0
jsonnet-formatter|xrc|0.2.2

</details>

**Comment by mlushpenko** [comment]
Some more info, when I update file and click refresh, nothing happens
![image](https://user-images.githubusercontent.com/2006610/54292052-d06d6600-45ad-11e9-84f4-2d19664b6817.png)

But, when I go to source code view and click refresh, then both source code and file explorer windows refresh and show changes
![image](https://user-images.githubusercontent.com/2006610/54292116-e844ea00-45ad-11e9-9478-4d8995777f63.png)

**Comment by joaomoreno** [comment]
Are the workspace folders roots of git repositories? Or are they sub folders of the git repository?

**Comment by mlushpenko** [comment]
@joaomoreno yes, each folder is git root folder

**Comment by joaomoreno** [comment]
Does it work if you open each folder individually in Code?

Does it always reproduce if you open that workspace?

**Comment by mlushpenko** [comment]
Sorry @joaomoreno it doesn't always reproduce, it happened several times, but I don't know how to reproduce the bug every time. Perhaps just keep the issue open and see if some other people report this as well, or maybe it was fixed with recent upgrade.

**Comment by joaomoreno** [comment]
Does it reproduce if you open each folder individually in Code?

**Comment by mlushpenko** [comment]
I can't reproduce it now, maybe it was fixed
