### ISSUE TITLE
Wrong highligting in a string contatenation in PHP

### ISSUE THREAD

**Issue by chimit** [Microsoft/vscode#70382]
Issue Type: <b>Bug</b>

There is a bug in code highlighting in PHP string concatenation.

![image](https://user-images.githubusercontent.com/839349/54271749-18e05000-45bd-11e9-8a22-d8aca9187a26.png)

Apparently, `env('DB_PREFIX')` should be highlighted.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|2.7.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
file-icons|fil|1.0.16
beautify|Hoo|1.4.9
phpcs|ika|1.0.5
dotenv|mik|1.0.1
vscode-language-pack-ru|MS-|1.32.4
php-docblocker|nei|1.7.0
vetur|oct|0.16.2
subtle-brackets|raf|3.0.0
code-settings-sync|Sha|3.2.7
vscode-wakatime|Wak|1.2.13

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Tracking this in https://github.com/atom/language-php/issues/348
