### ISSUE TITLE
Runaway Process?

### ISSUE THREAD

**Issue by b4l8ter** [Microsoft/vscode#70383]
Issue Type: <b>Bug</b>

The VS Code editor owns a process thread at 20% CPU and ~200Mb+ memory on my quadcore system. I have removed all extensions and the problem persists. I have only noticed the problem when I leave the editor open for lengthy periods (like overnight).

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:21:36.727Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (26.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Please see the tips here to provide more info: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu which process is it?

**Comment by b4l8ter** [comment]
UPDATE: I switched to the latest stable 64-bit version and no longe experience this issue.
