### ISSUE TITLE
Convert null to undefined in workbench

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#70384]
* `| null` should not be used
* `withUndefinedAsNull` and `withNullAsUndefined` should not be needed

Related: #70020

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/70020

**Comment by bpasero** [comment]
@mjbvz how do you plan to tackle this? There are still usages of `null` in hundreds of files in our code. Rather than doing an all or nothing approach, I typically just gradually convert to `undefined` while I refactor a piece of code.

**Comment by mjbvz** [comment]
Yeah I don't think we want to make a big push to convert every `null` to `undefined`. Gradual conversion seems like the right approach to me too

Closing this issue

**Comment by bpasero** [comment]
@mjbvz also close https://github.com/microsoft/vscode/issues/70020 ?
