### ISSUE TITLE
Cannot read property 'searchAndReplaceWidget' of null

### ISSUE THREAD

**Issue by martinschayna** [Microsoft/vscode#70385]
Version: 1.33.0-insider
Commit: c1d001a915fe85cac93492393ea69fdb0c49ec0d
Date: 2019-03-13T06:13:28.579Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

Steps to Reproduce:

1. Search widget location set in the bottom panel (`"search.location": "panel"`)
2. Press `Ctrl+Shift+F` or choose `View` -> `Search from menu`
3. Search widget has not been activated, error popup appeared:

```
Cannot read property 'searchAndReplaceWidget' of null
```
Does this issue occur when all extensions are disabled?: Yes

This issue occurs only when location of Search widget is set to panel.

**Comment by bengry** [comment]
Also happens on macOS (10.14.3) with VS Code insiders:
```
Version 1.33.0-insider (1.33.0-insider)
c1d001a915fe85cac93492393ea69fdb0c49ec0d
2019-03-13T06:06:57.428Z
```

**Comment by NKjoep** [comment]
in case you are stuck with this bug, open the json preferences and disable the `"search.location": "panel"` then refresh the window.

**Comment by sandy081** [comment]
Sorry for this. This is fixed and will be available in latest insiders.
