### ISSUE TITLE
New window takes too long to open

### ISSUE THREAD

**Issue by hyperfekt** [Microsoft/vscode#70386]
Issue Type: <b>Performance Issue</b>

Using `code --wait --new-window` as the `$EDITOR` is a bad experience, because the process of opening a new window reliably takes almost two seconds. This is the case even with extensions disabled.
Note that this refers to the time to open a new window only, with an instance already running in the background and thus does not refer to the usual startup time.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.20.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2952)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.31GB (16.30GB free)|
|Process Argv|--skip-getting-started --extensions-dir /nix/store/dkz0f461qxdipm7p38ds08p7khpbd09y-vscode-extensions-1.31.1/share/vscode/extensions|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
Please see the tips here to provide more info: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by hyperfekt** [comment]
None of these seem able to provide data on the time between triggering a new window to be opened and it being fully rendered (except `code --status`, which I cannot use due to #7390), which is, as noted in the issue, distinct from startup performance (what you linked me to).

**Comment by roblourens** [comment]
Oh I see that `--prof-startup` won't work in this scenario. So this is much slower than just opening a new window through the menu?

**Comment by hyperfekt** [comment]
I would say it is a little less than one second slower than opening a new window through the menu.
The 'performance marks' of the startup performance tab however look pretty close between these two ways of opening a new window, so there is a significant delay not captured by that.

**Comment by roblourens** [comment]
Is there any way to get startup perf info for this scenario @jrieken?

**Comment by bpasero** [comment]
@hyperfekt instead of comparing to "File > New Window" can you run code <some folder> from the command line and see how long that takes compared to the other one? That comes closest to what code --wait does.

**Comment by hyperfekt** [comment]
Timing without `--wait`is hard of course, but I estimate it takes just as long as calling code with `--wait`.
This means just `code` takes roughly the same amount of time as `code --wait --new-window <file>`, while `code [--wait] <file>` and File > New Window are about twice as fast (which puts them into the range of acceptable latency).
The overhead really seems to come from opening a new window from the command line.
