### ISSUE TITLE
After the latest update multiple instances running chewing up system memory

### ISSUE THREAD

**Issue by curiousalok** [Microsoft/vscode#70391]
- VSCode Version: Version: 1.32.1 (user setup)
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS Version: Windows 10

Steps to Reproduce:

1.Open one instance of VSCode.
2.After some time open Task Manager.
3.Multiple instances of VSCode shown to be running but i had opened only one instance.
![VSCode](https://user-images.githubusercontent.com/27468808/54276727-10374c00-45b4-11e9-81fb-83d7fca65af4.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please see the tips here to provide as many details as possible https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by Half8Man** [comment]
![image](https://user-images.githubusercontent.com/32817089/54337522-1f78d100-466a-11e9-8d9b-ceb2aa8da174.png)

I just open a vscode windows

**Comment by roblourens** [comment]
One VS Code window always has several processes associated with it. The screenshot doesn't show any issue. You can use the process explorer or `code --status` to figure out which process is using the most memory. Likely one of your extensions is involved.
