### ISSUE TITLE
cant close the find reference dialog 

### ISSUE THREAD

**Issue by ebra100** [Microsoft/vscode#70399]
![Screenshot (82)](https://user-images.githubusercontent.com/33094584/54281341-33590000-45a2-11e9-8301-e5c420908020.png)

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
