### ISSUE TITLE
Message "Git not found. Install it or configure it using the 'git.path' setting" received after update to OSX Mojave

### ISSUE THREAD

**Issue by upugo-dev** [microsoft/vscode#70398]
The git installation is actually there, but probably VScode is having trouble recognising git, because XCode CLI tools needs updating for ti to work properly. Unsure of details. See https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-mojave-update-xcrun-error-invalid-active-devel

Perhaps VSCode could offer a slightly more sophisticated check and more verbose error message to point users in the right direction (updating XCode CLI tools, nothing wrong with git)

**Comment by upugo-dev** [comment]
I’ve provided a better explanation in #68172

**Comment by joaomoreno** [comment]
We do have a few checks, done a *long* time ago: https://github.com/Microsoft/vscode/blob/7e4bac31d8b6c46ad6989e9f4db0c7004668746b/extensions/git/src/git.ts#L87

It sucks that we have to keep up with whatever weird Apple thing happens which each OS update.

**Comment by prasadgujar** [comment]
@joaomoreno can I work I this issue?

**Comment by upugo-dev** [comment]
> We do have a few checks, done a _long_ time ago:
> 
> [vscode/extensions/git/src/git.ts](https://github.com/Microsoft/vscode/blob/7e4bac31d8b6c46ad6989e9f4db0c7004668746b/extensions/git/src/git.ts#L87)
> 
> Line 87 in [7e4bac3](/Microsoft/vscode/commit/7e4bac31d8b6c46ad6989e9f4db0c7004668746b)
> 
>  // must check if XCode is installed 
> It sucks that we have to keep up with whatever weird Apple thing happens which each OS update.

Thanks for the reply @joaomoreno. I guess this is a non-issue in Microsoft land. At least confused users will hopefully stumble accross this thread in their googling efforts!

**Comment by nathanpitman** [comment]
This was fixed for me by installing the latest Xcode update and just opening Xcode, then closing VSC and reopening it.

**Comment by joaomoreno** [comment]
#81287
