### ISSUE TITLE
Extension updated indicator

### ISSUE THREAD

**Issue by elitistsnob** [Microsoft/vscode#70394]
Extensions that have updated but do not require reload are not indicated. When parsing my list of extensions I cannot identify ones that have just recently updated. A good solution might be something Apple does to call out iOS apps with fresh updates, using a small blue dot next to the app name.

**Comment by usernamehw** [comment]
Probably would be solved by https://github.com/Microsoft/vscode/issues/68527#issuecomment-470389100
