### ISSUE TITLE
In-File-Searchbar hides search result

### ISSUE THREAD

**Issue by m4w** [Microsoft/vscode#7039]
- VSCode Version: 1.1.1
- OS Version: OS X 10.11.4 

Steps to Reproduce:
1. Create a file with at least one line of dummy code (the contend should fill the line completely)
2. Search for a string which is on the rightern side of the viewport (where the searchbar would appear)

You will notice that the searchbar hides the searchresult.

**Comment by m4w** [comment]
any updates here? I believe can be very important, since you are not able to see all search results and you might wonder were the match is.

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/5525 and solve it in May.
