### ISSUE TITLE
Terminal name resets to bash once typing starts

### ISSUE THREAD

**Issue by SamStonehouse** [Microsoft/vscode#70397]
Window
- VSCode Version: 1.32.1
- OS Version: Windows 10

Steps to Reproduce:

1. Rename terminal to anything via the 'Rename terminal' command
2. Start to type in the terminal, the terminal name resets to bash

Does this issue occur when all extensions are disabled?: Yes

This is a fairly new issue, happened in 1.31.1 and the current version but it never used to happen

**Comment by SamStonehouse** [comment]
Looks like it's a duplication I didn't find in my own search, but previous issues are closed.

**Comment by martinog2** [comment]
Still broken in 1.32.3

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/68287

Fix coming in 1.33
