### ISSUE TITLE
TypeScript wrong highlighting when using `if` within `for`

### ISSUE THREAD

**Issue by igabesz** [Microsoft/vscode#704]
TypeScript highlighter interprets `if` calls within a `for` loop as function definitions if the `if` has middle parameter and brackets. The interpretation starts failing in the `for` loop for the last parameter. 

Not the consequence of installed extensions.
Highlighting fails for other color themes as well, not only Monokai. 

```typescript
// OK
for (var i=0;; i++) {
	if (i===0) {}
}
// Partially wrong, see for loop 3rd parameter
for (let i=0; i<5; i++)
	if (i===0) {}
// Wrong
for (var i=0; i<5; i++) {
	if (i===0) {}
}
// Wrong
for (let i=0; i<5; i++) {
	if (i===0) {}
}
// Wrong
for (; i<5;) {
	if (i===0) {}
}
```

![vs-highlight-error](https://cloud.githubusercontent.com/assets/3373181/11421925/2235eca8-9438-11e5-8231-57733459fb4e.png)

**Comment by igabesz** [comment]
This can get really ugly for more complex cases. (Logic mostly omitted.)
![vs-highlight-error2](https://cloud.githubusercontent.com/assets/3373181/11422134/e370a0e2-9439-11e5-8d0c-c64350df5918.png)

**Comment by igabesz** [comment]
OK, messing with this a little more I came across that highlighting breaks if there is a `variableName<` text in the middle parameter of `for`. I think it's something with the parsing of templates. 

* Not happens if there is whitespace, e.g. `variableName <`
* Not happens for `funcCall(variable)<`

![vs-highlight-error3](https://cloud.githubusercontent.com/assets/3373181/11422480/9959a47e-943c-11e5-809a-c7a322ef188b.png)

**Comment by egamma** [comment]
The TypeScript Sublime plugin renders this correctly. 
Should we update the textmate bundle with the one from Microsoft/TypeScript-TmLanguage.

**Comment by aeschli** [comment]
I verified that we are using the latest version from https://github.com/Microsoft/TypeScript-TmLanguage.
Installing that latest also in Sublime shows there is the same bug:

VS Code on the left - Sublime 3 on the right:
![image](https://cloud.githubusercontent.com/assets/6461412/11445329/8e780c40-952b-11e5-9231-6eab8a5b668f.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#17
