### ISSUE TITLE
Source Control / more actions not working after commit

### ISSUE THREAD

**Issue by rogermartensson** [microsoft/vscode#70400]
- VSCode Version: 1.32.1 
- OS Version: Windows 10

Steps to Reproduce:

1. Change a file in GIT, save
2. Change to Source Control
3. Stage the updated file
4. Add a message.
4. Move the mouse to the commit icon (V) and clieck.
5. Move mouse to the right over to More Actions menu (...) without clicking anywhere else
6. Clicking menu (...) does not show the menu

Does this issue occur when all extensions are disabled?: Yes

If I click anywhere else (like in the editor) the (...)-menu is shown. This has been visible the last couple of versions. Before it stopped working I noticed a small amount of time before I was able to click and view the menu.

**Comment by sbatten** [comment]
I am unable to reproduce this, can you provide a gif or more details?

**Comment by joaomoreno** [comment]
Also can't repro. @rogermartensson Can you send us a screen recording of the issue?

**Comment by rogermartensson** [comment]
Sure.. here is a simple gif.
Any ideas where I can look for clues or what to try? I have tried to run with extensions disabled and had the same problem.

![cantclick](https://user-images.githubusercontent.com/12293031/54349643-006b4680-464c-11e9-9342-881f93ecf9eb.gif)

**Comment by joaomoreno** [comment]
@sbatten That input box warning uses the context view service.

**Comment by Eitz** [comment]
To me this is only happening if I have a commit message larger than 50 chars (eg. the yellow warnings is highlighting the field)
