### ISSUE TITLE
Open Editors highlighting lags behind

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7040]
Have a setup with three panes:

![image](https://cloud.githubusercontent.com/assets/22350/15666970/f03f54d6-2713-11e6-8b8e-873ff11614b4.png)

Repeat the following *ad infinitum*:

1. Click inside the left-most editor
2. Click inside the center editor
3. Click inside the right-most editor

Notice how, as you click around:

- The explorer always highlights the file which is opened in the currently focused
- The Open Editors pane does the same, but it always lags behind the explorer... is there a `setTimeout` in there?

**Comment by isidorn** [comment]
Yes there is a 250ms timeout which we introduced due to #6749

**Comment by joaomoreno** [comment]
Yep, that has to go.

**Comment by bpasero** [comment]
@isidorn this goes into a similar direction of not doing a full tree refresh when there is just the active group changing I believe. In the end, selection should update as fast as for the explorer.

**Comment by isidorn** [comment]
@bpasero yeah I think it is time to introduce some smartness on updating the tree. So we could refresh with a delay when new elements added, but updating selection and other minor stuff we could do immediatly - will look into that

**Comment by joaomoreno** [comment]
I'd assume that the delay is going to go away and work on that. Remember that you only introduced it to fix the double clicking. It was a bad fix, needs to happen some other way.

**Comment by bpasero** [comment]
@isidorn I would not expect a tree refresh on non-structural changes, this is outlined in https://github.com/Microsoft/vscode/issues/6670
