### ISSUE TITLE
implement default search provider for custom FileSystemProvider

### ISSUE THREAD

**Issue by suntobright** [microsoft/vscode#70409]
When a extension implement a filesystem provider, the quick open and search viewlet don't work unless implement the file/text search provider either.

If some extension register a custom filesystem provider. It has provided the basic functionality to search file in quick open and search text in search viewlet.

VS code should implement a default text/file search provider.

The extension could implement their own text/file search provider, if they think the default one is not good enough.

**Comment by roblourens** [comment]
When the search provider API is stable, developers will be able to do this themselves. But I don't plan to provide a FileSystemProvider-based search out of the box.
