### ISSUE TITLE
Save work-space variables out to file

### ISSUE THREAD

**Issue by bhuffman-usgs** [Microsoft/vscode#70407]
When debugging, I believe it would be beneficial to be able to save variables out to a file, maybe by right clicking the variable and having an option to "save to file".  This helps in testing, especially with python, as there is a limit to using the debug console.  For example, say a piece of code produces a large vector and I'm having issues later on down the line in the code.  I want to run some tests on this vector but as stated, there's only so much you can do in the debug console on the fly.  By saving out the current vector (variable) to a file, I can copy the variable data from that file and write another python script to run the aforementioned tests on it.

**Comment by roblourens** [comment]
Please include more details

**Comment by bhuffman-usgs** [comment]
Details now included.

Brad

**Comment by roblourens** [comment]
Maybe copying it to the clipboard is enough?

**Comment by bhuffman-usgs** [comment]
That only works when the variable has only a few elements, otherwise you get something like this
![vs_code_clipboard](https://user-images.githubusercontent.com/40209416/54304411-75327800-459b-11e9-8f79-5adcae65a578.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70377
Plus the python extension should do it

**Comment by bhuffman-usgs** [comment]
How is this related to 70377 at all?  Also before you claim the python
extension should do it, have you tried it.  Because I have and I'm not sure
where you're indicating that this is possible.
