### ISSUE TITLE
expose registerLinkMatcher api in terminal render

### ISSUE THREAD

**Issue by suntobright** [Microsoft/vscode#70411]
I've noticed that vscode is moving terminal render api to stable.

And I think it would be great if vscode could expose the registerLinkMatcher api for terminal render, since vscode use xterm as the underlying terminal.

By this, extension could be able to more powerful, like `ctrl` + `shift` + `click` to download a sftp file in a custom ssh terminal.

**Comment by Tyriar** [comment]
The terminal renderer API will be changing soon, see https://github.com/Microsoft/vscode/pull/67923#issuecomment-471635837

The current thinking to get links working is being able to specify what home is and what the OS is, that way links would even work in Live Share https://github.com/Microsoft/vscode/pull/67923#issuecomment-472937493

As for custom links like you're proposing I don't think we'd want to expose something like registerLinkMatcher as I'm pretty keen on improving that API in https://github.com/xtermjs/xterm.js/issues/583
