### ISSUE TITLE
Strict null check extHostDebugService.ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#70417]
Great work strict null checking debug! One more debug related file to handle: `vs/workbench/api/node/extHostDebugService.ts` with 42 errors

**Comment by weinand** [comment]
@mjbvz I've fixed strict-null issues in extHostDebugService.ts and variableResolver.ts.
But if I enable `vs/workbench/api/node/extHostDebugService.ts` in `tsconfig.strictNullChecks.ts` I get lots of errors in `proxyResolver.ts` and `extHostTreeView.ts`.

So I leave it up to you to enable the `vs/workbench/api/node/extHostDebugService.ts` eventually.
