### ISSUE TITLE
Files code erased after starting VS Code

### ISSUE THREAD

**Issue by ricardofilipehenriquesfaria** [Microsoft/vscode#70419]
Issue Type: <b>Bug</b>

We usually work with the VS Code to create custom JavaScript solutions for Sharepoint sites. Everything is saved on two servers: a Dev Server where we develop solutions, and a Prod server that is used by us to save our solutions and make them available to our clients.
We started using VS Code auto-save in order to save everything automatically.
Since then, what happened was that, after starting VS Code, all the code was erased from the files. The files still there, on the server, but without any code.
There were not any problems with other JavaScript files saved inside the server, just the ones that were opened in VS Code.
After that, we disabled the auto-save and everything go back to normal, and we could open other files without any problem.

We just wanted to know if there are any problems with the auto-save since we have lost precious code from our servers.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
Sorry that you lost code. First, you should update vscode, version 1.26 is very old. Second, can you explain your scenario a bit more? How did you open the code on the server, like through a mapped network drive or something else?

**Comment by ricardofilipehenriquesfaria** [comment]
We use the UNC path to open the folders in the VS Code. 
I have checked, and the autoSaveDelay was set to 1000 milliseconds (1 second), by pre-definition. Maybe this should be the problem, and the autoSaveDelay pre-definition should be changed. 
When we opened the VS Code it seems that it was trying to open the files and saving at the same time.

**Comment by bpasero** [comment]
@ricardofilipehenriquesfaria that should not happen but I fear without a reliable way to reproduce this, it will be hard to track down the issue. Can you reproduce this reliably?

**Comment by ricardofilipehenriquesfaria** [comment]
@bpasero I have created a test file, and set the Auto Save on VS Code, but sadly, I was not able to reproduce the problem.

**Comment by bpasero** [comment]
@ricardofilipehenriquesfaria we do first truncate the file to 0 bytes on Windows ([here](https://github.com/Microsoft/vscode/blob/2275bfe42848f3ddea9f907e5bb63e39d74390fb/src/vs/workbench/services/files/node/fileService.ts#L599)) and then write to it, so this may explain why a file shows up empty if the connection goes down before being able to write the contents fully.
