### ISSUE TITLE
Debug console doesn't properly handle succeeding color escape sequences

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#70416]
Version: 1.33.0-insider (user setup)
Commit: c1d001a915fe85cac93492393ea69fdb0c49ec0d
Date: 2019-03-13T06:18:20.237Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

When coloring debug console output with ANSI escape codes, VSCode will not always properly handle new colors. Instead, it seems to apply a hierarchy of colors where, for example, white will override any other succeeding colors.

For example, printing the following string:
```
\u001b[31m Red \u001b[32m Green \u001b[34m Blue \u001b[37m White \u001b[32m Green \u001b[31m Red \u001b[0m
```
Results in this output in VSCode:
![image](https://user-images.githubusercontent.com/2294248/54300787-f84fd000-4593-11e9-8cfc-418ccfcfd387.png)
Powershell, on the other hand, handles this properly:
![image](https://user-images.githubusercontent.com/2294248/54300904-38af4e00-4594-11e9-9d7a-a6cbd46e9fd7.png)

**Comment by isidorn** [comment]
Dup of some of these https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+debug+console+ansi+colors

**Comment by iansan5653** [comment]
@isidorn I don't see which one it would be a duplicate of. #67217 is about a different format, #42388 is related to theming and colors, #38834 and #571 relate to other locations in the program (not the Debug Console).

**Comment by isidorn** [comment]
How about this one https://github.com/Microsoft/vscode/issues/67217
And here's a broader list
https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+debug+console+color

**Comment by iansan5653** [comment]
@isidorn #67217 is about support for a different format for color codes. This specific bug notes that the colors I am trying to use are supported and rendered, but not handled properly when multiple colors are used in succession. 

I don't see it in that list either.

**Comment by isidorn** [comment]
Ok, let's reopen this one.

**Comment by isidorn** [comment]
We accept PR's that fix this.
Code pointer https://github.com/Microsoft/vscode/blob/a93905ebf8233c9f755e389b348cdc9b91c8f5f7/src/vs/workbench/contrib/debug/browser/debugANSIHandling.ts#L21

**Comment by iansan5653** [comment]
I'll work on it, thanks!

**Comment by isidorn** [comment]
Make sure to add tests here https://github.com/Microsoft/vscode/blob/b4d347d9f634283eb122dc58ae518594726a2b9e/src/vs/workbench/contrib/debug/test/browser/debugANSIHandling.test.ts#L1
