### ISSUE TITLE
Inconsistent JavaScript Highlighting

### ISSUE THREAD

**Issue by JoshSchreuder** [Microsoft/vscode#7041]
- VSCode Version: 1.1.1
- OS Version: Windows 8.1

I'm just trying out VSCode for the first time (coming from ST3) and noticed something with the JS highlighting. Not sure if it's is intentional - it occurs in all default themes - so apologies if it is / has been raised already.

Take the following code and check out the difference:
```js
export class Test {
    var foo = {};
    foo.bar = qux;
}

function a () {
    var foo = {};
    foo.bar = qux;
}
```

The export code highlights the `.bar` portion of `foo.bar` whereas the standard function doesn't.

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/681706/15667125/ddccdec4-2757-11e6-9704-f810eaaa9296.png)

**Comment by aeschli** [comment]
@JoshSchreuder The problem is that the first part is not valid JavaScript syntax. Inside a class you can't define a var. You need to surround this with a method or constructor.
That's why the syntax highlighting gets confused.

**Comment by JoshSchreuder** [comment]
Thanks @aeschli. I was just messing around, so not surprising when I mess up syntax :smile: 

Are there any plans to revise the highlighting to include properties? Or would I have to write a custom highlighter to do something like that?

For instance, here's what my current ST3 theme looks like:
![image](https://cloud.githubusercontent.com/assets/681706/15673312/3c25dd24-2779-11e6-8254-238b73c61ce8.png)

And here's VS Code:
![image](https://cloud.githubusercontent.com/assets/681706/15673308/34995b4e-2779-11e6-95cb-3e19fb886db2.png)

Obviously it's a highly personal thing what you like highlighted, but personally I find having additional highlighting as per my ST3 theme to be beneficial (especially looking at a line like `root.Backbone = factory(root, {}, root._, (root.jQuery || root.Zepto || root.ender || root.$));`)

Thoughts?
