### ISSUE TITLE
February update: code is unusable seems to be hanging in infite loop

### ISSUE THREAD

**Issue by derekwallace** [Microsoft/vscode#70410]
1.32.1
windows 10

1.31.1 was fine.
I also tried insiders a few weeks ago and it exhibited similar behavour to what i see now in prodcution release.
See https://github.com/Microsoft/vscode/issues/68280

no plugins loaded
workspace explorer not showing an files.
cannot save files
UI cannot close File - Exit doesnt work...

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by derekwallace** [comment]
it seems to have resolved itself. 
i left the window open and after 1hr + things seems to have returned to normal.
the  extensions are available.
opening and saving files is ok.

i now closed the program and re-open.
The behaviour is the same
- workspace explorer is not displaying
- open file from ctrl-p does not display
- opening settings and htting the {} button to see in json format does not work

There is something happening on  startup 
the GUI is responsive and interactive.
but nothing is  functional...

process explorer does not show any high load
![image](https://user-images.githubusercontent.com/5574230/54336025-c174cb00-4622-11e9-9344-4364052803df.png)

i have insiders and will try. i have not been able to use this for 1+month due to the same issue .

**Comment by bpasero** [comment]
@derekwallace are you opening a workspace file or a folder? is the path you open on a network drive or local folder?

**Comment by derekwallace** [comment]
i can confirm that insiders 1.33 has the same issue.
there is some startup behaviout that is new (intrdocued in insiders 1.32 , that i s now in production) that has a huge negative impact.
I am sure its related to
1. i am using a windows network drive to a linux NAS
2. the connection is relatively slow vs a local c: on machine
3. the worksapce is large 10000 files (maybe)

i notice that in explorer or in the file editor window that there are horizontal scrolling lines at the top , indicating its doing somethign....

In the 1.32 production release, the app  becomes usable after about 15-20 minutes.
All the scrolling lines on top of windows are now gone.

These are the plugins i have installed.
The Python and the language server may be a factor... (im writing Python code)
It is very very slow at analyzaing the project and generating the symols.
![image](https://user-images.githubusercontent.com/5574230/54337488-f97e0d00-4626-11e9-8eb1-1acac441bb33.png)

**Comment by bpasero** [comment]
@derekwallace thanks, I think this is https://github.com/Microsoft/vscode/issues/70045 so I suggest we continue the investigation there.

**Comment by derekwallace** [comment]
yes i agree this sounds like the same issue i am experencing.
