### ISSUE TITLE
Custom shortcut to bring VScode to the front of all windows

### ISSUE THREAD

**Issue by flowen** [Microsoft/vscode#70412]
A configurable shortcut that brings VScode window to the front of all Applications.

Similar to [Numi](numi.io) if you look at `preferences -> Hotkey`

**Comment by roblourens** [comment]
I think this has to be handled by something in the OS outside of vscode itself. I don't think vscode should manage global shortcuts on the OS.

**Comment by flowen** [comment]
The mentioned app Numi does it, they simply add a shortcut option. I don't believe this is an OS specific thing.
