### ISSUE TITLE
Syntax coloring error using preprocessor in C/C++

### ISSUE THREAD

**Issue by braincodec** [Microsoft/vscode#70424]
// There is a syntax coloring error when we are using a "Simple quote" in #error ... "doesn't"

![VisualStudioCodeSyntaxColoringError](https://user-images.githubusercontent.com/15169898/54310097-e12fd300-45d1-11e9-8853-b59896339350.png)

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)

**Comment by alexr00** [comment]
This is fixed in the Insiders build, and the fix should be in the next Stable release.
