### ISSUE TITLE
Incorrect shortcut watermark position after startup or window reload

### ISSUE THREAD

**Issue by jeanp413** [Microsoft/vscode#70425]
After startup or window reload:
![1](https://user-images.githubusercontent.com/25115070/54311160-00af0780-45a2-11e9-9c85-7379fc1135f4.png)
Expected:
![2](https://user-images.githubusercontent.com/25115070/54311167-04db2500-45a2-11e9-8114-d4cea6dc62b1.png)

**Comment by bpasero** [comment]
I can reproduce even in stable.
