### ISSUE TITLE
Text completion only shows on every other trigger event when extension is enabled

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#70428]
Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:46:10.898Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64

The built in vscode text completion seems to only happen on every second trigger event when the intelephense extension is activated. When the extension is disabled the vscode text completion happens every time. In the screenshot below intelephense returns an empty `CompletionList`.

![string_completion](https://user-images.githubusercontent.com/5885195/54315454-40bdcb00-4632-11e9-999d-4a4f857f0c22.gif)

Does this issue occur when all extensions are disabled?: **No**

**Comment by jrieken** [comment]
>  In the screenshot below intelephense returns an empty CompletionList

Empty but with or without the `isIncomplete` flag set? Also, what are the trigger characters that you are using? Last, please compose a sample extension that shows this behaviour. Thanks
