### ISSUE TITLE
Add menu option to open recent files/folders/projects in new window

### ISSUE THREAD

**Issue by avdept** [Microsoft/vscode#70421]
My idea is to have boolean option(similar to Auto Save) to open recent files/folders in new window rather than in current(and close currently working project).

Currently I have semi working feature which, however, needs to be discussed if accepted by core team. Example below

<img width="534" alt="Screen Shot 2019-03-13 at 8 11 40 PM" src="https://user-images.githubusercontent.com/1757017/54303719-4ed90080-45cc-11e9-8df8-19b9e1551bc4.png">

**Comment by roblourens** [comment]
Find the setting `window.openFoldersInNewWindow`. I don't think this belongs in the menu however.
