### ISSUE TITLE
Sometime not properly loading

### ISSUE THREAD

**Issue by nirmohiofficials** [Microsoft/vscode#70422]
Issue Type: <b>Bug</b>

i am facing an issue sometime while loading collapse feature is not loading . live server extension is also causing infinite load time some times

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.0.15
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
color-highlight|nau|2.3.0
seti-icons|qin|0.1.3
prettier-now|rem|1.4.9
LiveServer|rit|5.5.1
indenticator|Sir|0.6.0
code-spell-checker|str|1.6.10
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by roblourens** [comment]
> sometime while loading collapse feature is not loading

I don't understand what you mean. Please include more details and exact steps for how to reproduce this issue.
