### ISSUE TITLE
AGAIN: "Unable to create 'launch.json' file inside the '.vscode' folder ({0})."

### ISSUE THREAD

**Issue by ebewley** [Microsoft/vscode#70429]
Once again this issue returns in version 1.32.1 of Visual Studio Code and prevents people from following the instructions provided on visualstudio.com for setting up debugging.  For example, the instructions at https://code.visualstudio.com/Docs/editor/debugging , "Launch configurations" section, specifically instruct users to open their project folder and click on the gear icon.  VSCode does not automatically detect my configuration, which I find strange, being that it is a fresh install of VSCode on a fresh install of Debian 9 on a fresh VM in VM Workstation Pro 15, with nothing else installed except the Angular CLI, Node.js and the Chrome debugger.  Whether I select the "Chrome" option or the "Node.js" options in the dropdown, the result is the same:  "Unable to create 'launch.json' file inside the '.vscode' folder ({0})."

From the Help/About dialog of VSCode:
Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:46:10.898Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64

**Comment by ebewley** [comment]
**New findings:**

**CAUSE:**  VSCode does not verify that the .vscode folder exists, and does not create it in the workspace prior to attempting to create the launch.json file.  The error message is typically incomplete and marginally helpful.  Instead of saying "Unable to create 'launch.json' file inside the '.vscode' folder.", which may lead one to believe that it is never allowed, the reason for the error, "Folder ".vscode" does not exist." should be appended.  This reason, or one like it, was probably reported by the exception generated by the system when the attempt was made to create the launch.json file.

**WORKAROUND:**
1. Create the .vscode folder manually within the workspace.
2. Change ownership or ensure that the user account you are developing with, has sufficient permissions to add and delete files within the folder.
3. Return to following the instructions for setting up debugging in VSCode.

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders
https://code.visualstudio.com/insiders/

If yes please provide step by step reproducable concise steps. Not a story. Thanks!

**Comment by jramsay** [comment]
@isidorn, @weinand: I have a repro for this in VS Live Share.

**Repros on:**

Version: **1.32.3** (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Prerequisite:** Install the latest VS LiveShare extension (0.3.1326)

Repro steps:
1. VS Code **(Host**): open a C# console App and make sure there is **no launch.config**. Also make sure the Program.cs file is open. Start a VS Live Share Collaboration session and when it connects select 'Make read-only' in the notification:

![image](https://user-images.githubusercontent.com/8161247/54714100-6bfe5980-4b0d-11e9-8df2-cfd783e9abc4.png)


2. VS Code **(guest**): join the collaboration session and make sure Program.cs is open.  Now try to do a guest initiated debug session with: Debug -> Start Debugging

Select .NetCore from the dropdown when it pops up:

![image](https://user-images.githubusercontent.com/8161247/54714305-d44d3b00-4b0d-11e9-96fc-65367a53a0e6.png)

Notice the error that pops up:

![image](https://user-images.githubusercontent.com/8161247/54714330-e4fdb100-4b0d-11e9-922a-6f9ae6c354e9.png)

I believe we started seeing this happen as of VS Code version 1.32.1.  It makes sense as this is a readonly session so the guest doesn't have access to write to this location.  I was getting this same errror in a Node.js project and was able to work around the issue by intercepting in our joinDebugManager's (implements DebugConfigurationProvider) resolveDebugConfiguration.  When I get a launch debug request and this is a readonly session I throw our own custom error "This operation is not allowed in read-only collaboration session" before you guys throw:

Unable to create 'launch.json' file inside the '.vscode' folder ({0})." 

In the scenario above though the error is being thrown before I have a chance to intercept it - resolveDebugConfiguration is never called.

**Comment by isidorn** [comment]
Yeah if the folder is readonly it makes sense to me that the file service throws and that it can not create a `launch.json`.
I do not understand why you would like to interecept the error?
I think the proper fix would be that the file service just throws a more preicse error: Unable to create... because the workspace is readonly.

**Comment by isidorn** [comment]
@jramsay ping

**Comment by isidorn** [comment]
@jramsay this works just fine for me with the latest vscode insiders.

Here are my steps:
1. Have a readonly `FileSystemProvider`
2. Open a workspace which does not have a `launch.json`
3. F1 > Open launch.json > answer questions
4. `launch.json` gets populated nicely

fyi @bpasero since he changed the `fileService` this milestone

@jramsay as for your questions from the email regarding the error message I thought that we fix it on the vscode side, that we just throw a more precise error message. No action needed on your end

Please try with latest insiders https://code.visualstudio.com/insiders/
If this does not work please let me know what you are doing differently than me.

![readonly](https://user-images.githubusercontent.com/1926584/55093632-08e46800-50b5-11e9-977f-85e0deb6d4b5.gif)

**Comment by jramsay** [comment]
@isidorn:  I'm still able to repro in the latest Insiders:

Version: 1.33.0-insider (user setup)
Commit: 627c7f730a776ef6efb8762e9379b8c7e71e417b
Date: 2019-03-27T20:51:24.171Z

Perhaps the difference is I'm using '.NET Core' debugging? Also, I'm seeing another error, in addition to the one we're discussing, now in VS Code Insiders:

![image](https://user-images.githubusercontent.com/8161247/55113900-c5323400-509d-11e9-9778-6588adb4ce69.png)

**Comment by bpasero** [comment]
@isidorn I do not see the file getting populated with a readonly file system provider and would not expect that this works given the provider is marked readonly. Here are my steps:
* clone https://github.com/Microsoft/vscode-extension-samples/blob/efbfb30884a4bf4aec72335b67ad51b71aa652ff/fsprovider-sample
* set `isReadonly: true` in the extension when it registers itself
* run the extension
* mem: create workspace
* mem: create files
* try to create launch config via command palette

Outcome:
![image](https://user-images.githubusercontent.com/900690/55137918-83070200-5132-11e9-8dfc-dea1bd28a060.png)

**Comment by isidorn** [comment]
I was setting the readonly file system incorrectly. @bpasero you are right.

I have looked into the issue and I have improved the error message to properly surface the error from the FS provider.

Here's the current error:
@jramsay please let me know if you would like us to further tune the wording (please note that this is a general read only case and that we should not mention live share). Thanks!

![Screenshot 2019-03-28 at 12 15 59](https://user-images.githubusercontent.com/1926584/55153694-5e6f5200-5153-11e9-9237-e92df36e5e31.png)

**Comment by robindegen** [comment]
I'm having the same error which braught me to this issue in the first place. I'm using the C++ extension. I click add configuration and it pops up with this random message. Why isn't this just working out of the box? It's very user unfriendly this way
