### ISSUE TITLE
onDidCloseTextDocument not working correctly

### ISSUE THREAD

**Issue by shsuman** [Microsoft/vscode#70439]
Issue Type: <b>Bug</b>

We are trying to implement a scenario where when the user closes a file with some specific fle names, we capture the data from the file and return it. However,  while trying to use the onDidCloseDocument for this, I see that it's quite inconsistent, some times it fires twice, some times it doesn't fire at all. I am first using vscode.window.showTextDocument() to open a temporary file and then using the onDidCloseTextDocument function to to the processing and return

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
VSCode decides when to really close documents, this is based on ref counting, memory pressure, and timing. You cannot rely on a document being closed only when the editor closes, however you can rely on the fact that it will be eventually closed.
