### ISSUE TITLE
Autosave stucking

### ISSUE THREAD

**Issue by darkodavidovic** [Microsoft/vscode#70431]
After last update of my VS code, autosave is waiting too long to autosave my work, delay is 1s by default... i hear my hard drive working too hard when i make some changes in my code. Instead of 1s, i waiting more then 7s to autosave. Settings are ok, 1s unchanged... System config on my computer- unchanged, No viruses, No conflict with other software, just VS code struggling...

**Comment by roblourens** [comment]
Probably there is some extension working too hard when a save happens. Can you try starting with `--disable-extensions` to verify?

**Comment by darkodavidovic** [comment]
I tried to disable extensions, same results... But, my .SCSS file has 1200 lines of code. I tried to edit small file and VS code working normally. To confirm my computer problems, i tried on my friends computer (i7, 8GB RAM, SSD) to edit that large file and problem has happend again.

**Comment by roblourens** [comment]
Hm, 1200 lines is not really that long. Is any process using high CPU while this is going on? 
Does anything in here help to provide more info? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by nhducit** [comment]
I got the same issue. 
this is log from developer tools console
```
 WARN Aborted codeActionsOnSave after 750ms
```

Disable `Setting Sync` extension fixed it issue for me.
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by roblourens** [comment]
Please open your own issue @nhducit and see the questions I asked above to provide more details

**Comment by darkodavidovic** [comment]
You can close this topic. Problem persisted no mether what i do. Only files with 1000+ lines in combination with autosave. When i disable autosave, only emmet has delay of around 5-7 seconds to suggest me the code. Brackets, Sublime, Atom works ok whit that file... Something like VS code do some calculation or scanning in my code.
