### ISSUE TITLE
Integrated terminal (PowerShell) cannot launch with cwd containing square brackets

### ISSUE THREAD

**Issue by yzhang-gh** [Microsoft/vscode#70432]
Issue Type: <b>Bug</b>

1. Create a directory `D:\folderNameHas[SquareBrackets]`
2. Open the above folder with VSCode
3. Toggle integrated terminal
4. See `cwd` is `C:\Windows\System32\WindowsPowerShell\v1.0>` rather than `D:\...`

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.28
vscode-custom-css|be5|3.0.3
log-wrapper-for-vscode|chr|1.0.2
vsc-material-theme|Equ|2.7.0
vsc-material-theme-icons|equ|0.9.8
vscode-commands|fab|1.2.5
vscode-github-notifications-bell|fab|2.1.5
vscode-highlight|fab|1.3.4
vscode-open-in-application|fab|1.0.5
latex-workshop|Jam|6.2.1
rainbow-csv|mec|1.0.0
git-graph|mhu|1.4.2
python|ms-|2019.2.5558
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.7
dictionary-completion|yzh|0.8.0
find-word-at-cursor|yzh|0.1.1
markdown-all-in-one|yzh|2.1.1
vscode-jupyter|yzh|1.2.3

</details>

**Comment by jmbockhorst** [comment]
I believe that this is a problem with node-pty.

**Comment by the-ress** [comment]
This is a PowerShell bug. See PowerShell/PowerShell#5752 and [UserVoice post](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11629491-bug-current-working-directory-is-reset-to-pshome).

**Comment by Tyriar** [comment]
Thanks @the-ress, I verified this works with pwsh 6.
