### ISSUE TITLE
unexpected EOF while parsing error in Python Interactive

### ISSUE THREAD

**Issue by mugofjoe** [Microsoft/vscode#70436]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mugofjoe** [comment]
when I hit shift+enter over a multi-line python statement, the Python Interactive screen would show "SyntaxError: unexpected EOF while parsing". This happens even if I use a "\" at the end of a line.

**Comment by roblourens** [comment]
Please file this on the Python extension repo
