### ISSUE TITLE
Visual Studio hangs with "Initializing JS/TS language features" when opening a .ts file

### ISSUE THREAD

**Issue by miguellira** [Microsoft/vscode#70435]
Issue Type: <b>Bug</b>

After a recent upgrade, when opening a typescript file, Visual Studio Code hangs and CPU utilization maxes out for several minutes with the **Initializing JS/TS language features** status indicator.

The closest related _open_ issue I could find is: https://github.com/Microsoft/vscode/issues/68142, however, its title implies its a Mac issue.

After setting TypeScript Server trace to verbose:

`"typescript.tsserver.trace": "verbose"`

I was able to note a significant lag between the following two events upon opening a `.ts` file:

```
[Trace  - 6:44:35 PM] Event received: typingsInstallerPid (0).
Data: {
    "pid": 27112
}
[Trace  - 6:45:44 PM] Event received: projectLoadingStart (0).
```
Visual Studio Code Insiders cuts this down to ~1 minute but it still hangs and maxes out the CPU.

VS Code version: Code - Insiders 1.33.0-insider (c1d001a915fe85cac93492393ea69fdb0c49ec0d, 2019-03-13T06:18:20.237Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
Can you please try collecting the TS Server log to see why it may be hanging:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

If you can share the log, I can take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by miguellira** [comment]
@mjbvz Took at hammer to it and uninstall/reinstalled. The JS/TS language features still takes a long time when starting and my CPU maxes out but its not as bad as before - or maybe I'm just getting use to it. 😧 In any event, I have attached the log. Thanks!

[tsserver.log](https://github.com/Microsoft/vscode/files/2972342/tsserver.log)

**Comment by miguellira** [comment]
After upgrading to Visual Studio Code `1.32.3` the performance hit initializing JS/TS is now in line with prior builds.
