### ISSUE TITLE
PHP autoclosing pairs do not work outside of <?php ?>

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#70437]
I'd like to add an autoclosing pair for the short form of the PHP syntax `<?php echo ... ?>`, that is  `<?= ?>`, in a `language-configuration.json`.

```json
{
"autoClosingPairs": [
		{ "open": "{", "close": "}", "notIn": ["string"] },
		{ "open": "[", "close": "]", "notIn": ["string"] },
		{ "open": "(", "close": ")", "notIn": ["string"] },
		{ "open": "'", "close": "'", "notIn": ["string", "comment"] },
		{ "open": "\"", "close": "\"", "notIn": ["string", "comment"] },
                { "open": "/**", "close": " */", "notIn": ["string"] },
                { "open": "<?=", "close": " ?>" }
	]
}
```
However, it only works inside of `<?php ?>` which makes is not useful as it is only valid syntax outside of `<?php ?>`. Is there a way to achieve this?

![autoclosing](https://user-images.githubusercontent.com/5885195/54321124-cbf38c80-4643-11e9-83b1-f42423a2f166.gif)

**Comment by roblourens** [comment]
I think you would have to add them as autoclosing pairs for html?

**Comment by bmewburn** [comment]
Thanks @roblourens , looks like the autoclosing pairs work outside of `<?php ?>` only if the pair is declared in language configurations for both PHP _and_ HTML. If it's just in the PHP config then it only autocloses within `<?php ?>`. If it's just in the HTML config then it only autocloses in HTML language mode.
