### ISSUE TITLE
debug configuration file launcg.json not opening

### ISSUE THREAD

**Issue by asr117** [Microsoft/vscode#70446]
sometimes when i open a folder that contains my angular project ..and when i click on debug button->open or add configuration there is no effect on clicking on open configuration or add configuration no file is opened ...and then i have to restart the vs code....

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, please provide exact reproducable steps so I can investigate this more

**Comment by isidorn** [comment]
Closing since more information is not provided
