### ISSUE TITLE
Find in files indexing for autocomplete / instant search 

### ISSUE THREAD

**Issue by pthiben** [Microsoft/vscode#70441]
One thing I love about Visual studio is the entrian source search plugin (http://entrian.com/source-search/ ). It performs autocomplete while in the search box (because I sometimes remember only the prefix of a given function), and does 'instant' (<500ms) search on our 10M+ loc solution for whole word search, file VSCode take ~5-10s on the same machine.

I understand there'd be a disk cost associated for storing this indexed data, but I for one would live happily with it if it could give me these 2 features.

Thanks

**Comment by roblourens** [comment]
We have investigated this in the past but rejected it because it's just at odds with vscode being a simple and lightweight text editor.
