### ISSUE TITLE
Environment Variables set with an extension are not propagated

### ISSUE THREAD

**Issue by ysndr** [Microsoft/vscode#70445]
- VSCode Version: 1.32.2
- OS Version: MacOS 10.14.3

Steps to Reproduce:
1. create an extension that sets `process.env['FOO'] = 'bar';` for example
2. install and make sure extension is run
3. open developer tool and observe that  `process.env['FOO'] === undefined`

Is it even possible to set process.env keys from an extension that may be read by other extensions or tasks, etc? The existence of `vscode-direnv` indicates that it should have been possible at least in an earlier version of vscode though...

**Comment by roblourens** [comment]
Other extensions should see the same environment, I believe. Tasks are spawned by a different process so they will not.

**Comment by ysndr** [comment]
First, thanks for the quick response :)
I'll look into what other extension see tomorrow, though from what I have observed by now, it seems not to work that well there either.

I'm trying to get direnv working with vscode. Based on some existing work from 3 years ago I try to rewrite that not-so-well-working extension in hope to fix theese issues.

What it basically does is assigning the environment `direnv` produces to `process.env` which _should_ make set variables, foremost `PATH`, visible to vscode.

Quite a bummer if that won't work with tasks as you said, but I could circumvent that, as long as at least other extensions work in this scenario.

**Comment by egorse** [comment]
With 1.32 vscode-python unable to expand any variables from .env - like if environment would be empty.
Even old versions of plugin has same issue.
Wonder if this is linked.

**Comment by roblourens** [comment]
Not sure what you're talking about, please file an issue on the python extension repo @egorse

**Comment by egorse** [comment]
@roblourens I am not sure that belongs to vscode-python. but between 1.31 and 1.32 something got changed - so same old versions of vscode-python (i.e. 2018.7.1) expands values from .env to empty.
once this one is closed - is there PR for fix?

**Comment by roblourens** [comment]
Honestly I don't really know which issue you're talking about, please file this issue on the python extension with full steps to reproduce the issue.
