### ISSUE TITLE
Startup / loading time noticeably longer or just hangs.

### ISSUE THREAD

**Issue by roguesleipnir** [Microsoft/vscode#70448]
Since the update yesterday, loading my project workspace (Unity) has taken very long or just hangs when switching between files. The selected file will not display and just has the progress indicator animating. Other UI elements aren't functional too, even when trying to close the app.

Reverting to an earlier version like 1.31.1 fixes all of these.

- VSCode Version: 1.32.2
- OS Version: Windows 10 x64 17134.472

**Comment by roblourens** [comment]
Please see this wiki page for tips to provide as many details as possible: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by roblourens** [comment]
Also, please try 1.32.3 since this sounds like https://github.com/Microsoft/vscode/issues/70045
