### ISSUE TITLE
UX: "Code for 64-bit Windows is now available"

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#70447]
This always comes back, no matter how many times I dismiss it:

![image](https://user-images.githubusercontent.com/298883/54333095-db3b0000-466c-11e9-8e9f-7540a971ead5.png)

I click to learn more, as it requests:

![image](https://user-images.githubusercontent.com/298883/54333148-1806f700-466d-11e9-85ef-5af31cd2e2f7.png)

Ok, uninstalling one thing and then installing another is kind of only a loose interpretation of "upgrading", but maybe I'm nitpicking. Crossing my fingers that uninstalling won't remove my settings...

![image](https://user-images.githubusercontent.com/298883/54333249-7b912480-466d-11e9-85a4-0b02be519e55.png)

Ok, now I'm feeling really uncertain. Windows says related info will be removed. Aren't my settings "related info"? If your page says my settings will be preserved, why does Windows claim otherwise?

At this point I'm bailing because I'm too busy to mess around with possibility of losing my settings. My suggestion is that the wording could be improved, and/or the installer could be improved so as to automate the process of uninstalling one and installing the other. The fact that one is 32 bit and the other is 64 bit... should this matter if one process is simply launching another process when it is done?

**Comment by beastdestroyer** [comment]
It should keep your settings. 
If you aren't sure yourself, you can always open settings.json  select all and copy into a notepad or smth, then uninstall, then reopen settings.json and paste it in

Regardless of which version, 32 bit or 64 bit, your extensions will keep since they both use the `.vscode` folder in your user directory.

**Comment by yume-chan** [comment]
Classic Desktop Apps like Code manage their data by themselves, they can put anything anywhere, so what is deleted when uninstalling is decided by the app itself.

But Universal Windows Apps have their data managed by Windows, so uninstalling will delete all data as well.

Most new Windows settings are designed mainly for Universal Windows Apps, they just are "compatible" with Classic Desktop Apps.

So maybe you can report this inaccuracy wording in the Feedback Hub app and let Windows team fix it.

**Comment by roblourens** [comment]
Yes, it should keep your settings. Thanks @beastdestroyer and @yume-chan for the details
