### ISSUE TITLE
Show smaller search/replace preview

### ISSUE THREAD

**Issue by ChrisJefferson** [Microsoft/vscode#70458]
I often do search/replace where I change a small term, but add context so it matches correctly. For example, replace `_bound` with `Bound`.

In the preview I see `_bound` crossed out in red and `Bound` inserted in green. I would prefer it if the strings added/removed were squashed at the left and right where identical, so instead I'd just see `_b` removed and `B` added. This would both give a more compact view, and give me confidence I'm doing the right thing (as the first time I did this I accidentally replaced with `Bonud`, but didn't notice).

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/19310
