### ISSUE TITLE
When the cursor is inside the function, how can I get  the function name

### ISSUE THREAD

**Issue by bengbengdaxishi** [Microsoft/vscode#70451]
When the cursor is inside the function, how can I get  the function name，What kind of API is available？Please give advice or comments，thanks！

**Comment by jrieken** [comment]
No API is available for this, you can try using document symbols (https://code.visualstudio.com/api/references/commands#commands, `executeDocumentSymbolProvider`) but note that all of our API are driven by UI demands, not representing syntax trees.
