### ISSUE TITLE
Cannot trigger IME on Integrated terminal

### ISSUE THREAD

**Issue by realmx** [Microsoft/vscode#7045]
- VSCode Version: 1.2.0-insider
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:
- by default settings
![1](https://cloud.githubusercontent.com/assets/6071313/15667677/232b121e-274a-11e6-9629-286ffa0d3704.png)

**Comment by kirill-kruchkov** [comment]
Cannot type cyrillic as well

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/124

**Comment by Tyriar** [comment]
This is one of the things issues I want to focus on for v1.4
