### ISSUE TITLE
extensions are not showing also not able to install new one in vscode

### ISSUE THREAD

**Issue by kiranyad** [Microsoft/vscode#70455]
- VSCode Version: version 1.32
- OS Version: Ubuntu 18.04
i have installed my vscode 3 to 4 months back till now it working fine and able to install extensions and remove them but around 1 week problem started. i am not able to see any of installed extensions neither recommend nor disabled.

Steps to Reproduce:
![Screenshot from 2019-03-14 12-52-11](https://user-images.githubusercontent.com/48545867/54338476-0535f780-4658-11e9-83a0-9d7f105c3def.png)

1. just start vs code 
2. and click on extensions button. it is continuously showing processing but is not showing anything. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@kiranyad Are you behind any proxies?

**Comment by kiranyad** [comment]
No it is not.

**Comment by sandy081** [comment]
Please do following and provide us the info

- Enable log level to trace using the command `Set Log Level`
- Open the Shared process logs view using the command `View: Open View` -> `Log (Shared)
- Open the developer tools console using the command `Toggle Developer Tools`

Check if there is any information in the logs/console that can be helpful to understand the issue.

**Comment by kiranyad** [comment]
I had followed the instructions that you have mentioned above and i got this,

![Screenshot from 2019-03-26 17-40-55](https://user-images.githubusercontent.com/48545867/54996139-7f6a6280-4fee-11e9-9e00-434b7031bda6.png)
![Screenshot from 2019-03-26 17-41-23](https://user-images.githubusercontent.com/48545867/54996150-84c7ad00-4fee-11e9-8d16-30805faaee7b.png)

hope it will help to find the problem.

**Comment by sandy081** [comment]
Looks like there are some issues with your shared process. Did you try the following

- Open the Shared process logs view using the command View: Open View -> `Log (Shared)`

Also try following

- `F1 -> Toggle Shared Process` and see if there are any errors in console
- `F1 -> Show Running Extensions` and let us know what extensions are running
