### ISSUE TITLE
No splitter control anymore in Source Control view

### ISSUE THREAD

**Issue by zplan** [Microsoft/vscode#70454]
- VSCode Version: 1.33.0-insider
- OS Version:Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Make a workspace which contains more than 10 git repos
2. Navigate to Source Control 
3. Under "Source Control Providers" 10 repos are directly visible, for the others you have to scroll down
4. In previous version there was a splitter control to drag down the splitter to see more than 10 repos instead of scrolling
5. Hover with the mouse under the last visible entry and no splitter is available

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by joaomoreno** [comment]
This now works like `Open Editors`. There is an additional setting `scm.providers.visible` which when set to `0`, lets you manually resize the view.
