### ISSUE TITLE
Cannot search files (Cannot read property 'on' of undefined)

### ISSUE THREAD

**Issue by Atoms** [Microsoft/vscode#70452]
- VSCode Version: 1.31.1, 1.32.1, 1.32.2
- OS Version: Linux

Steps to Reproduce:

1. Open Folder in workspace
2. Try searching files

Does this issue occur when all extensions are disabled?: Yes/No
Yes

---
When trying to search in files error message appears in search box.
Tried to remove all code files and do a clean setup, and without extensions it also happened.
College on macos does not have such issue.

![image](https://user-images.githubusercontent.com/9615/54337516-d14ada00-4637-11e9-936a-eafd91a7fcaa.png)

**Comment by roblourens** [comment]
Can you open the developer tools (Help > Developer tools) and check whether there's a full error stack trace in the console?

**Comment by Atoms** [comment]
```
console.ts:134 [IPC Library: Search] Error: spawn /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by roblourens** [comment]
Not sure why you got an EACCESS can you check the permissions on `/opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg`?

**Comment by Atoms** [comment]
```
# ls -la /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg                                                                                           130 ↵
-rw-r--r-- 1 root root 5057144 Mar 14 08:55 /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg
```
i use gentoo linux, and use own ebuild to install package https://github.com/Atoms/rukruk/blob/master/app-editors/visual-studio-code/visual-studio-code-1.32.2.ebuild
so, if permissions should be changed on that file, i can add in ebuild permission fix.

**Comment by Atoms** [comment]
```
# ls -la /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg                                                                                           130 ↵
-rw-r--r-- 1 root root 5057144 Mar 14 08:55 /opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg
```
i use gentoo linux, and use own ebuild to install package https://github.com/Atoms/rukruk/blob/master/app-editors/visual-studio-code/visual-studio-code-1.32.2.ebuild
so, if permissions should be changed on that file, i can add in ebuild permission fix.

**Comment by roblourens** [comment]
It should be executable. I guess that needs to be fixed in ebuild, thanks.

**Comment by Atoms** [comment]
thanks, fixed in ebuild so it's executable now all working 
https://github.com/Atoms/rukruk/blob/master/app-editors/visual-studio-code/visual-studio-code-1.32.3.ebuild#L53
