### ISSUE TITLE
Error squiggly in wrong location

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#70465]
while working on #68657 I was (again) seeing the following confusing squiggly:

Here is the code and the squiggly:
![2019-03-14_10-33-37](https://user-images.githubusercontent.com/1898161/54346156-e5490880-4644-11e9-9aba-4f3625ededf1.png)

And here the error message:
![2019-03-14_10-34-07](https://user-images.githubusercontent.com/1898161/54346172-eda14380-4644-11e9-9de0-c8d03f94f29c.png)
 
The error message does not make any sense because "tracker" cannot be undefined after the "if" guard.

However, the problem is that the squiggly is shown in the wrong location.

The method property "onError" is optional and as such can surely can be undefined. 
So the correct location of the squiggly would be on the "onError" property.

**Comment by mjbvz** [comment]
This is because we don't have am end line / end column from the tsc problem matcher. The tsc output does not include this so I'll see what we can do

**Comment by mjbvz** [comment]
Closing this for now since we have not seen other reports of this causing problems

The upstream TS issue (microsoft/TypeScript#30433) tracks a discussion of ways to address this
