### ISSUE TITLE
How to close unmodifed file when going back from `jump to def`

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#70466]
If you jump to definition from a modified file, it would open the file as new tab. When you `Go back` from that file:

![2019-03-14 at 10 41](https://user-images.githubusercontent.com/6391776/54346674-c39c5100-4645-11e9-83a9-b3510009e598.png)

It would switch to the file you jumped from but leave the file hanging even though it was unmodified.

Is there a setting in VS Code to close the unmodified files when `Going back`?

**Comment by nikitavoloboev** [comment]
I see I have already opened this issue a year ago and it wasn't addressed still. 😞

Should I close this one?

**Comment by roblourens** [comment]
I'll close it as a duplicate but the idea currently is that the unmodified file is opened as a "preview" (with italic text in the tab title) and only one preview tab will be open at a time, so the next opened file will replace that one.

You can probably ask in the other issue whether a PR would be accepted.

**Comment by nikitavoloboev** [comment]
> only one preview tab will be open at a time

That makes a huge difference for me. Thank you. I didn't realize this and knowing this, the issue is resolved for my use case.
