### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by dinesh0178** [Microsoft/vscode#70463]
Issue Type: <b>Bug</b>

i have created a total of 5 to 6  files but all of a sudden i cant find them anymore .once i colsed  vscode it all went missing . i need those files back urgent.please give me some solutions.

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2196)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|6.94GB (1.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.7
python|ms-|2019.2.5558

</details>

**Comment by Tyriar** [comment]
This could have been related to the [hot exit feature](https://code.visualstudio.com/docs/editor/codebasics#_hot-exit) though I don't think we have any issues reported for v1.31. The backed up files are stored under the `Backups` folder in the user data folder https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations (it's a sibling of the `User` folder).
