### ISSUE TITLE
outline view (markdown) does not work if yaml frontmatter ends in "..."

### ISSUE THREAD

**Issue by agusmba** [microsoft/vscode#70464]
Issue Type: <b>Bug</b>

The outline view showing markdown chapters and subchapters does not show anything if the document yaml frontmatter ends in "...".

This works:

    ---
    title: My title
    ---
    
    # My chapter

But this doesn't (the outline does not show anything):

    ---
    title: My title
    ...
    
    # My chapter

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.1.1
vscode-markdownlint|Dav|0.25.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.5.1
language-haskell|jus|2.5.0
rainbow-csv|mec|1.0.0
Go|ms-|0.9.2
vscode-docker|Pet|0.6.0
material-icon-theme|PKi|3.6.3
qub-xml|qub|1.2.1
markdown-preview-enhanced|shd|0.3.12
vscode-table-formatter|shu|1.2.1
vscode-mermaid-preview|vst|0.11.1

</details>

**Comment by crystalfp** [comment]
I just want to add that the preview is not generated too. I opened a bug report against an [extension](https://github.com/yzhang-gh/vscode-markdown/issues/398#issue-421836077), but seems it uses the vscode services.

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
To help with this, please look into fixing this upstream: https://github.com/craigdmckenna/markdown-it-front-matter/issues/4

**Comment by TroyTae** [comment]
@mjbvz 
For fixing this issue, I need to implement this [spec](https://yaml.org/spec/1.2/spec.html#marker/document%20end/) in [markdown-it-front-matter](https://github.com/craigdmckenna/markdown-it-front-matter).
And update dependency in here, correct?

**Comment by crystalfp** [comment]
And updating example on [README.md](https://github.com/craigdmckenna/markdown-it-front-matter)

**Comment by mjbvz** [comment]
@TroyTae Yes, that is correct

**Comment by TroyTae** [comment]
@crystalfp @mjbvz 
Ummm it seems [markdown-it-front-matter](https://github.com/craigdmckenna/markdown-it-front-matter) isn't maintained anymore...
(https://github.com/craigdmckenna/markdown-it-front-matter/pull/7#issuecomment-559633000)
When faced like this situation, how can we do?

**Comment by mjbvz** [comment]
Let's give it a few more days and see if they respond. Otherwise, we can fork the repo and take your PR into the fork
