### ISSUE TITLE
Emmet need to move cursor to `class` for `div.` expansion

### ISSUE THREAD

**Issue by Almo7aya** [microsoft/vscode#70469]
- VSCode Version: 1.32.1
- OS Version: Windows 10

Steps to Reproduce:

In an HTML file when typing ```div.``` and press `tab`
it creates a new ```<div class=""></div>``` and moves the cursor inside the ```<div class="">|</div>```, I think it should move it inside the class name `class="|"`, It's so helpful when using classname auto completion extension.

Does this issue occur when all extensions are disabled?: NO

**Comment by rzhao271** [comment]
\closedWith dc5a3da
