### ISSUE TITLE
A command to install extension

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#70468]
A command `workbench.extensions.installExtension` to install an extension from Marketplace or a VSIX

Usage:

`vscode.commands.executeCommand('workbench.extensions.installExtension', 'extensionId');`

`vscode.commands.executeCommand('workbench.extensions.installExtension', vscode.Uri.file('path-to-vsix');`

**Comment by octref** [comment]
After running the command, extension is installed and activated, but the list of installed extension is not refreshed.

![image](https://user-images.githubusercontent.com/4033249/55039388-34961e00-4fe1-11e9-89e9-19f0a95a3339.png)

**Comment by octref** [comment]
Otherwise this works great. Thanks!

**Comment by sandy081** [comment]
Thanks. Extensions view will not be updated automatically (known issue).

**Comment by shivapoudel** [comment]
@sandy081 Can you please guide me how can I run this command? I stuck at the real beginning :)

I might have 20-30 extensions collection for vscode and wanted all of them in `settings.json`, is that possible now through this feature :)

**Comment by sandy081** [comment]
@shivapoudel You can run this command from an extension using the code mentioned in the description.
