### ISSUE TITLE
If you have open editors disabled the Close All action should be part of the editor header

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#7046]
- VSCode Version: alpha

It is now in the overflow menu which makes sense if you have tabs or open editors enabled. If both are disabled would be cool to have it in the header as a primary action.

**Comment by bpasero** [comment]
The action is now available in the context menu anywhere if you right click in the title area:

<img width="701" alt="screen shot 2016-06-17 at 17 50 44" src="https://cloud.githubusercontent.com/assets/900690/16156330/09e45cb2-34b4-11e6-85a9-8e0d2bcaf741.png">

I am still not sure if we should expose it as primary action though given the close button is already there.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/9888

**Comment by bpasero** [comment]
Idea from Steven+Ben+Joao: Have a setting to control the close behaviour:

```
//This setting controls how the close button works when tabs are disabled
    "workbench.editor.groupCloseButton" : { "closeAllWhenTabsDisabled", "closeTopMostEditor" }
```

**Comment by bpasero** [comment]
I published an extension which adds a "Close All" button to the editor: https://marketplace.visualstudio.com/items?itemName=benjpas.close-all

**Comment by bpasero** [comment]
Closing in favour of my extension.
