### ISSUE TITLE
Tab Size gets set to 2 whenever i open a new file

### ISSUE THREAD

**Issue by Juggern4ut** [microsoft/vscode#70460]
Issue Type: <b>Bug</b>

Whenever I open a new file, the Tab Size will get set to "2" even though "4" is the configured tab size. This happend since the last update, I believe. 

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
coldfusion|ili|1.0.1
compareit|in4|0.0.2
python|ms-|2019.2.5558
sublime-keybindings|ms-|4.0.0
vetur|oct|0.16.2
taskrunnercode|San|0.3.0
stylelint|shi|0.48.0

</details>

**Comment by rebornix** [comment]
You may want to turn off `editor.detectIndentation`
