### ISSUE TITLE
'Go to Definition' instead does 'Peek Definition' on Styled Components

### ISSUE THREAD

**Issue by leotm** [Microsoft/vscode#70473]
- VSCode Version: February 2019 (version 1.32)
- OS Version: macOS Mojave 10.14.3 (18D109), also Windows 10 64-bit version 1809

Steps to Reproduce:

1. Open up at .tsx file
2. On a Styled Component, hit F12 or right-click then _Go to Definition_

Result: _Peek Definition_ is opened instead

I first noticed this happening roughly a week ago.

Current workaround: From the _Peek Definition_ window, double-click the constant.

NB: This issue does not occur with React Components.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by leotm** [comment]
Just spotted https://github.com/Microsoft/vscode/issues/70032, checking if related

**Comment by roblourens** [comment]
Thanks, this sounds like #70032
