### ISSUE TITLE
support old for-loop syntax

### ISSUE THREAD

**Issue by vammex** [Microsoft/vscode#70474]
Issue Type: <b>Feature Request</b>

currently a shortcut for for-loop looks like

```
for (let index = 0; index < array.length; index++) {
        const element = array[index];
    }
```

can i choose to stay with VAR anywhere instead of let and const? like:
```
for (var index = 0; index < array.length; index++) {
        var element = array[index];
    }

```
at some locations (inside java servers etc) these new js features like const should not work for me, so i have to refactor all these syntax values every time i use the shortcut

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Our basic built-in snippets target es6. You can write a [custom snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets) or install a snippet extension if you need to target older versions of JavaScript
