### ISSUE TITLE
Incorrect placement (vertical aligment) of error/warning icons in status bar

### ISSUE THREAD

**Issue by waldyrious** [Microsoft/vscode#70478]
The icons for the Errors and Warnings in the status bar seem to be misaligned with the numbers next to them. They should be vertically centered with the text, but they appear to be shifted down. This is not the case with the icons for other entries in the status bar.

Screenshot:
<img width="415" alt="Screenshot 2019-03-14 at 11 41 59 (2)" src="https://user-images.githubusercontent.com/478237/54355184-52ae6680-4650-11e9-9f46-de7f8c90b351.png">

- VSCode Version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T01:56:08.693Z)
- OS Version: Darwin x64 18.2.0

Does this issue occur when all extensions are disabled?: Yes

Running `code --disable-extensions .` I see this:

<img width="199" alt="Screenshot 2019-03-14 at 11 58 24" src="https://user-images.githubusercontent.com/478237/54355294-9b661f80-4650-11e9-8058-a9c99e146340.png">

**Comment by waldyrious** [comment]
Note: I searched for similar issues but only found #58777 which is about horizontal alignment of icons within the problems tab.

**Comment by sandy081** [comment]
@waldyrious I am not able to reproduce this. I see following 

![image](https://user-images.githubusercontent.com/10746682/54604402-f0d27000-4a46-11e9-8dc2-cf4fbe248c95.png)

Can you please try with a different user data directory and extensions directory. You can do it by running code from command line as following

`code --user-data-dir <folder-path> --extensions-dir <extensions-folder-path>`

**Comment by waldyrious** [comment]
Hmm, it seems like it may be related to the zoom level.

With `code --user-data-dir /tmp --extensions-dir /tmp .`

- Zoom reset:
  <img width="168" alt="Screenshot 2019-03-19 at 14 21 06" src="https://user-images.githubusercontent.com/478237/54613440-9c34f200-4a52-11e9-91a8-a20f98d6d02e.png">

- Zoomed out:
  <img width="116" alt="Screenshot 2019-03-19 at 14 20 42" src="https://user-images.githubusercontent.com/478237/54613438-9c34f200-4a52-11e9-8bde-21f0f790cc23.png">

With `code --disable-extensions .`

- Zoom reset:
  <img width="110" alt="Screenshot 2019-03-19 at 14 23 09" src="https://user-images.githubusercontent.com/478237/54613442-9c34f200-4a52-11e9-88e9-976c05e8674e.png">

- Zoomed out:
  <img width="103" alt="Screenshot 2019-03-19 at 14 23 27" src="https://user-images.githubusercontent.com/478237/54613444-9d661f00-4a52-11e9-82cc-d50ec1fc1cd4.png">

**Comment by sandy081** [comment]
@waldyrious Sorry cant repro. Can you try our latest insiders and see if you see the same?

https://code.visualstudio.com/insiders/
