### ISSUE TITLE
Cannot close opened folder

### ISSUE THREAD

**Issue by wzkid** [Microsoft/vscode#70472]
Issue Type: <b>Bug</b>

Once I open a folder (folder is a Office365 SharePoint Online site) I'm unable to close it and the VSC app will not close. I need to force it closed from the task manager.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:01:00.888Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.9
minify|Hoo|0.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
html-css-class-completion|Zig|1.18.0

</details>

**Comment by roblourens** [comment]
Can you explain exactly what you open and happens when you try to close it? Is this a folder on a network drive?

**Comment by roblourens** [comment]
Is this covered by one of the issues mentioned here? https://github.com/Microsoft/vscode/issues/70265#issuecomment-472732246

**Comment by roblourens** [comment]
This could also be https://github.com/Microsoft/vscode/issues/70045
