### ISSUE TITLE
Harddisk always run 100% when startup VS Code

### ISSUE THREAD

**Issue by MahoneWei** [Microsoft/vscode#70475]
Issue Type: <b>Performance Issue</b>

When I startup VS Code, my harddisk would run at 100%.

VS Code version: Code - Insiders 1.33.0-insider (c1d001a915fe85cac93492393ea69fdb0c49ec0d, 2019-03-13T06:18:20.237Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (12.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    91	 15664	code-insiders main
    0	   224	  1408	   window (Join.vue - 无标题 (工作区) - Visual Studio Code - Insiders)
    0	    40	  6732	     watcherService
    0	    12	  8052	     electron-crash-reporter
   12	   173	 16188	     extensionHost
    0	    99	  3520	       electron_node vueServerMain.js 
    0	    33	 23444	     searchService
    0	    68	 10556	   window (问题报告程序)
    0	    83	 13052	   gpu-process
    0	    67	 19596	   shared-process
    0	     7	 21436	   C:\Users\wwh\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-7258b995f63827ff1b179f47722e500296d64c35.exe /verysilent /update="C:\Users\wwh\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-7258b995f63827ff1b179f47722e500296d64c35.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    29	 18756	     "C:\Users\wwh\AppData\Local\Temp\is-HRPOG.tmp\CodeSetup-insider-7258b995f63827ff1b179f47722e500296d64c35.tmp" /SL5="$30894,49357440,159744,C:\Users\wwh\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-7258b995f63827ff1b179f47722e500296d64c35.exe" /verysilent /update="C:\Users\wwh\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-7258b995f63827ff1b179f47722e500296d64c35.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Join.vue - 无标题 (工作区) - Visual Studio Code - Insiders)
|    Folder (vonic): 113 files
|      File types: js(35) vue(25) map(21) png(7) css(4) html(3) svg(2) json(2)
|                  eot(2) ttf(2)
|      Conf files: package.json(1)
|    Folder (vonic_formal): 148 files
|      File types: js(53) map(39) vue(25) png(7) css(4) html(3) woff(2) eot(2)
|                  json(2) ttf(2)
|      Conf files: package.json(1)
|    Folder (xinyin): 49 files
|      File types: js(17) svg(14) vue(7) json(2) png(2) html(1) gitignore(1)
|                  browserslistrc(1) md(1) css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.7.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.9
vscode-language-pack-zh-hans|MS-|1.32.4
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
sass-indented|rob|1.5.1
language-stylus|sys|1.11.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by roblourens** [comment]
Is there any process using high CPU when this happens? If you start with `--disable-extensions`, does that still happen?

**Comment by roblourens** [comment]
This could also be https://github.com/Microsoft/vscode/issues/70045, please try the latest
