### ISSUE TITLE
Keybinding conflict (scrollPageDown, scrollPageUp)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7047]
@alexandrudima how attached are you to these keybindings? I chose Ctrl+PageUp and Ctrl+PageDown as keybindings to navigate across tabs. This seems established standard (https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts Tab Management).

```
Conflict detected, command `scrollPageDown` cannot be triggered by ctrl+pagedown due to workbench.action.nextEditor
Conflict detected, command `scrollPageUp` cannot be triggered by ctrl+pageup due to workbench.action.previousEditor
```

**Comment by alexandrudima** [comment]
@bpasero Why not use `ctrl+tab` and `ctrl+shift+tab`. Everybody knows those and they are the same over all OSes?

![image](https://cloud.githubusercontent.com/assets/5047891/15818635/d11f4a00-2bde-11e6-856e-d3ca9f5a0d83.png)

**Comment by bpasero** [comment]
@alexandrudima this is for navigating across multiple tab groups. within one group we already have Ctrl+Tab.

In Sublime this maps to "Goto Next File" and "Goto Previous File":
<img width="622" alt="screen shot 2016-06-06 at 10 54 59" src="https://cloud.githubusercontent.com/assets/900690/15820379/6364bd0a-2be9-11e6-91ca-6c5185af33fb.png">

**Comment by bpasero** [comment]
@alexandrudima ping
