### ISSUE TITLE
Visual Studio Code Stop to Working

### ISSUE THREAD

**Issue by pnmorais** [Microsoft/vscode#70476]
Issue Type: <b>Bug</b>

Since your last update the Visual Studio stop to working. I already remove and install from scratch the Visual Studio but the problem continues. I can opened files and change tab for another files. Appear to be stock in some loop hole.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (11.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
systemverilog|eir|0.6.0
python|ms-|2019.2.5558
json-template|sto|0.3.1
elfcode|vst|0.0.3

</details>

**Comment by gmacgregor1** [comment]
Having the same issue. Just updated and its stuck loading my workspace.

**Comment by kieferrm** [comment]
- Can you attach a screencast/gif that allows us to see what you see?
- Any errors in the console of DevTools? (Command palette > Developer: Toggle Developer Tools)
- What's the output when you start VS Code from the command line with the `--verbose` option?

**Comment by pnmorais** [comment]
I already removed the visual studio and install the previous version which I don't have any problem. But for what I saw after in the thread a lot of people have the same problem. The only thing I could had diferent from some people is that I had opened several workspaces with a lot of files each one. These  workspaces are in my network not on my local PC. The visual studio block completed, at the time I try to report the issue as performance issue but was impossible.


---- Kai Maetzel escreveu ----


  *   Can you attach a screencast/gif that allows us to see what you see?
  *   Any errors in the console of DevTools? (Command palette > Developer: Toggle Developer Tools)
  *   What's the output when you start VS Code from the command line with the --verbose option?

**Comment by roblourens** [comment]
Please try 1.32.3, this sounds like https://github.com/Microsoft/vscode/issues/70045
