### ISSUE TITLE
Crashing when opening another instance

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#70470]
Issue Type: <b>Bug</b>

I started to notice periodic crashing when I have code-insider open and I open another instance. The running instance will crash and close down and nothing starts up. 

I then have to open another instance of code-insider, when I do I am told there are background instance running and if I want to close them.

VS Code version: Code - Insiders 1.33.0-insider (c1d001a915fe85cac93492393ea69fdb0c49ec0d, 2019-03-13T06:13:28.579Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.66GB (1.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.2.2
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
java-debug|DSn|0.0.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
Scala|itr|0.1.7
solidity|Jua|0.0.49
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.2.5
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
java|red|0.40.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.0
vscode-maven|vsc|0.15.0
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by rajinder-yadav** [comment]
This still continues to happen on a regular basis but not easily reproducible. Also leaves behind background processes.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by rajinder-yadav** [comment]
Sure I will give it a go, thanks!
Give me a few days to get back to you.

**Comment by rajinder-yadav** [comment]
I've switched to using Code Exploration, will open future issues against this release thanks!

**Comment by rajinder-yadav** [comment]
Where can I get daily builds of Code Exploration?

**Comment by rajinder-yadav** [comment]
So far Code Exploration has been pretty stable, no crashing.
