### ISSUE TITLE
Explorer panel + open file extremely slow

### ISSUE THREAD

**Issue by micc91** [Microsoft/vscode#70488]
Since last update, browsing directories in explorer tree panel and opening a simple source file became extremely slow : several minutes !
Occurs right after startup

**Comment by micc91** [comment]
CPUs | Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3096)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 31.85GB (19.51GB free)
Process Argv |  
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
    2	    83	 19236	code main
    1	   163	  4256	   gpu-process
    0	    75	 16900	   shared-process
    3	   167	 17272	   window (Welcome - vsiqa (Workspace) - Visual Studio Code)
    0	     7	  4016	     winpty-process
    0	    11	 17496	       console-window-host (Windows internal process)
    0	    10	 21492	       cmd.exe /k C:\SocieteQualif\cmder\vendor\init.bat
    0	    70	 10424	     extensionHost
    0	    44	 23964	     watcherService
    0	    70	 27828	   window (Issue Reporter)

|  Window (Welcome - vsiqa (Workspace) - Visual Studio Code)
|    Folder (jenkins_tools): 487 files
|      File types: i(246) sh(59) ps1(41) iss(23) bat(15) rb(15) py(11) jmx(8)
|                  ksh(8) txt(8)
|      Conf files:
|    Folder (automation_dc_data): more than 21600 files
|      File types: i(17495) feature(3730) xml(166) ext(53) empty(42) d(24)
|                  unipkg(21) jar(9) txt(8) bat(3)
|      Conf files: tasks.json(1)
|    Folder (automation_dc): 5951 files
|      File types: i(3898) png(1511) rb(112) d(93) css(52) jar(46) js(44)
|                  java(32) gif(19) har(18)
|      Conf files:
			

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 10.2.2
cucumberautocomplete | ale | 2.13.1
gherkin-indent | Ara | 2.0.0
cucumber-mapper-ruby | cuc | 0.0.1
ini-for-vscode | Dav | 0.0.4
vscode-terminals | fab | 1.12.4
code-runner | for | 0.9.7
rest-client | hum | 0.21.2
bash-ide-vscode | mad | 1.3.3
hg | mrc | 1.3.0
python | ms- | 2019.2.5558
cpptools | ms- | 0.21.0
PowerShell | ms- | 1.11.0
vscode-code-outline | pat | 0.2.1
ruby | reb | 0.22.3
text-marker | ryu | 1.10.0
shellcheck | tim | 0.6.0
shell-launcher | Tyr | 0.3.0

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70045
