### ISSUE TITLE
Ctrl+` doesn't work on Japanese layout

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#70482]
Issue Type: <b>Bug</b>

When the keyboard is set to English UK language&locale with Japanese layout, the `` Ctrl+` `` shortcut to show or hide the terminal, no longer works. It just simply doesn't do anything. This bug also occurs when on the Microsoft Japanese IME, but also when using the "regular" Japanese layout without IME.

Switching back to English UK language&locale, and US-international layout, the `` Ctrl+` `` shortcut works again.

Should it matter, my physical keyboard is the US-layout version of a Dell XPS 9570.

This problem also happens with all extensions disabled.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (14.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.2.2
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.9
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.6.0
vscode-versionlens|pfl|0.22.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.7
vscode-svg-previewer|vit|0.5.0

</details>

**Comment by thany** [comment]
To re-emphasize: this issue also occurs *without* the Japanese IME. Having a Japanese keyboard layout on an otherwise English UK language, also triggers the bug. So I believe this is not a true dupe of #67839.

**Comment by alexandrudima** [comment]
The Backtick key (left of <kbd>`</kbd>) appears to be a special IME key:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66313129-2327ba00-e912-11e9-90cf-99d41c76897e.gif)

If you look carefully at the last frame, you will see the `keyCode` we receive has a value of `229`. The value `229` is defined to be the value for unknown when using IME: http://lists.w3.org/Archives/Public/www-dom/2010JulSep/att-0182/keyCode-spec.html

![image](https://user-images.githubusercontent.com/5047891/66313296-70a42700-e912-11e9-984b-d09419f2b21b.png)

Therefore, unfortunately, the Backtick key is unusable in VS Code when using Japanese IME, sorry about that!

**Comment by thany** [comment]
This may be too simplistic on my end, but is it not possible to listen for keyCode 229 then?

**Comment by alexandrudima** [comment]
I'm sorry, but that is not possible, because keyCode 229 is a catch-all value... Pressing <kbd>.</kbd> also produces 229, etc. Unfortunately, that is how this keyboard layout works and I think this is not a limitation specific to VS Code...

**Comment by thany** [comment]
Then maybe it's possible to assign a different hotkey (by default at least) when a Japanese IME is detected? I dont think it's right the default to certain keys that aren't usable because of a keyboard layout.

We also don't default anything to the Ğ key, because it only exists on a Turkish F-keyboard. This is an extreme example of course, but the point is that default hotkeys, IMO at least, should "just work" regardless of keyboard layout, even if it means some exceptions for some hotkeys.

This seems pretty hard to accomplish, so I understand if this would get a slightly reduced priority.

**Comment by alexandrudima** [comment]
@thany :+1: It is possible to change absolutely any keybinding on your side. You can remove everything we ship with and add your own from scratch or just tweak the defaults here and there... Just open the keybindings editor and reassign or edit directly in `keybindings.json`. See https://code.visualstudio.com/docs/getstarted/keybindings

By default, we ship with good default keybindings for the US keyboard layout. All other keyboard layouts are not optimized and it is a best-attempt situation. You can upvote this in https://github.com/microsoft/vscode/issues/1240
