### ISSUE TITLE
Auto detect ANSI encoding

### ISSUE THREAD

**Issue by swaner** [Microsoft/vscode#7048]
- VSCode Version:
  1.1.1
- OS Version:
  Win 10

Steps to Reproduce:
1. Create a new file in notepad, save it as ANSI (on my machine Ansi = Windows-1252)
2. Open the file in vs code

Result: VSCode assumes UTF-8 and the file is corrupted. Sublime-text has no problem recognizing Windows-1252.

**Comment by bpasero** [comment]
@swaner we do not have encoding detection so you need to either configure the encoding globally or per workspace or switch it from the status bar picker.

**Comment by MantvydasD** [comment]
I support this issue. I just had a deployment using a script which had ® character inside it and I then edited with Code. And ooh, how the script failed and brought down the system. Simple editors handle ANSI files simply, and Code doesn't. That's a shame.

I attach a sample file to test. When I open this file with Code I see � instead of ®, it should leave ® alone. And I tried to change encoding to ANSI, and I couldn't find it in Code.

[Character ®.txt](https://github.com/Microsoft/vscode/files/360293/Character.txt)

**Comment by JoV5** [comment]
+1

**Comment by Georgeouz** [comment]
Less powerful alternatives for handling this issue in the short run:

* use the problems or errors counter to signal the presence of � or any unrecognised characters;
* upon opening a file containing unrecognised characters, issue a question dialog suggesting `Reopen with encoding` or `Continue`. At least this will help prevent accidental overwriting;

Of course encoding detection would much more powerful.

**Comment by buzzzzer** [comment]
It is better to add onOpenFile setEnconding to api extentions...

**Comment by regs01** [comment]
I have UTF8 files and I have Windows 1251 files. I can't change it globally to Windows 1251. So every time i open them i have to reopen them. Why, at least, not to save desired encoding per file? If once i opened it in Win1251, open it in Win1251 any time else, unless i reopen or resave it manually as other encoding?

**Comment by llucassantoss** [comment]
Hi,
For ANSI files, use Western (Windows 1252).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5388

**Comment by mauriciovirtual** [comment]
Hi, a friend of mine found a workaround for this "ansi autodetect" problem:

- Under "preferences / user settings" we find "files.encoding"
- after that we choose "edit" to send it to right 
- manually we past the line 3 times, like below:
    "files.encoding": "utf8bom",
    "files.encoding": "utf8",
    "files.encoding":"windows1252"
- ignore alerts, close vsCode, open again and voila, now I can open UTF8 or ANSI encoded files with no problem and no need to "reload with encode".
We dont know why it works, but it just works fine on vsCode 1.8.1

**Comment by Hyperdingo** [comment]
This setting has been added: **files.autoGuessEncoding**

Will hopefully be true as default soon; https://github.com/Microsoft/vscode/issues/23417

**Comment by QtRoS** [comment]
Why only CP1252? I want this for CP1251 too... Someone else will want this for another encoding and so on. I think that you should pick local encoding of this machine. What do you think of it?
