### ISSUE TITLE
Can't select text on Linux when using Ibus Pinyin input method

### ISSUE THREAD

**Issue by touuki** [microsoft/vscode#70483]
- VSCode Version: 1.32.2
- OS Version:  Linux x64 4.16.0-kali2-amd64

Steps to Reproduce:
I can't select text in editor via holding the mouse click and dragging when I run VSCode as root, but it works fine running as a normal user.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zsc347** [comment]
This issue also occur when I run vscode as normal user.
But it's gone after I switch to a new user or run as root.
Try uninstall along with remove .vscode in user home dir and then reinstall won't fix the bug. So I guess some config in other place cause this issue.

**Comment by zsc347** [comment]
Since it's related with Ibus Pinyin input method. When I switch input method to `en`. This prblem has gone.

**Comment by zsc347** [comment]
For users meet same problem in Ubuntu 18.04 using ibus pinyin， try turn it off and user fcitx-google-pinyin instead. It fix my prolem.

If only there is a team like vscode mataining a Chinese input method for linux!

**Comment by TangHHH** [comment]
> Seems it's related with Ibus Pinyin input method. When I switch input method to `en`. This prblem has gone.

@zsc347 Oh, thx. It really solved my problem : )

**Comment by jypjypjypjyp** [comment]
@zsc347 same with you.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by touuki** [comment]
@bpasero I just tried it, but it still doesn't work.
