### ISSUE TITLE
Debug console merges newlines

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#70489]
Issue Type: <b>Bug</b>

```typescript
console.log('1\n\n2');
```
Expected:
```
1

2
```
Actual:
```
1
2
```
VS Code version: Code - Insiders 1.33.0-insider (7258b995f63827ff1b179f47722e500296d64c35, 2019-03-14T06:19:44.881Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/69535
