### ISSUE TITLE
cost too much memory & cpu

### ISSUE THREAD

**Issue by xgqfrms** [Microsoft/vscode#70480]
when run vscode , the code helper will cost most of cpus & memory

I don't know why ?

> VS Code version

![image](https://user-images.githubusercontent.com/7291672/54411843-988c2d00-472b-11e9-8a5c-d2cc7a2b7642.png)

> MacOS version

![image](https://user-images.githubusercontent.com/7291672/54411868-b48fce80-472b-11e9-9a50-da52ffd634e1.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/54356595-f7ec2d80-4696-11e9-868f-84046b72ddb6.png)

**Comment by xgqfrms** [comment]
https://github.com/Microsoft/TypeScript/issues/30034

**Comment by kieferrm** [comment]
@xgqfrms when it happens please run `code --status` from the command line to confirm that it is the tsserver.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

If it does, please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by xgqfrms** [comment]
```sh
$ code --status

$ code-insiders --status

```

**Comment by xgqfrms** [comment]
@kieferrm , @mjbvz 

> Thanks a lot.

OK, I will try that!

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
