### ISSUE TITLE
How would you call this?

### ISSUE THREAD

**Issue by bogmarko** [microsoft/vscode#70484]
Issue Type: <b>Bug</b>

Hello Microsoft
http://prntscr.com/mxt7my

I just installed VScode, and after looking for features and other stuff I have come up to this..

When i click or ( and scrolling)
Font,
Formatting,
Diff Editor,
minimap,
Suggestions,
Files etc down bellow it gets worse and worse..
Zen mode is the last affected thing.
On mouse hover => problem disappears.

Versions info http://prntscr.com/mxtdj1

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 6.1.7601

**Comment by roblourens** [comment]
What did you do to get into that state? Just open the settings editor and start scrolling?

**Comment by bogmarko** [comment]
Exactly. 
After the program was restarted, it did not appear anymore.

**Comment by roblourens** [comment]
I can't repro this but I will look out for it, please let me know if you see it again.
