### ISSUE TITLE
textResourcePropertiesService wrongly declares getEOL(resource: URI | null | undefined, language?: string): string;

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#70490]
The implementation does not handle `null | undefined` and imho should also not handle it actually.

Somewhat depends on https://github.com/Microsoft/vscode/issues/70491

//cc @mjbvz @isidorn

**Comment by isidorn** [comment]
If you do not handle null | undeinfed I still need a centralised way to ask for the EOL character if I dont have a resource.
Should every piece of code that needs this information to write it's own `isWindows ? '\r\n' : '\n'` logic?

**Comment by bpasero** [comment]
@isidorn not sure I can follow, in what situation do you need the EOL character without resource? I think this service purpose is actually only to ask for the EOL of a specific resource, not in general. Because this knowledge may be provided from the remote file system.

**Comment by isidorn** [comment]
@bpasero I am copying the whole call stack to the clipboard, I need the EOL charracted to append between lines. There I do not have a resource - but on second thought I am wrong and I can use the resource of the focused stack frame...

**Comment by bpasero** [comment]
@isidorn yeah something along those lines

**Comment by bpasero** [comment]
@isidorn yeah not sure, in that case you probably always want the EOL of the operating system the user is on that copies the thing. Not sure if @sandy081 could just beef up this service to allow for no resource to be provided but then I would add a new property for that case (and not a method).

**Comment by isidorn** [comment]
If you beef up the service let me know. This works for me decently for now as seen [here](https://github.com/Microsoft/vscode/blob/daccb87f92e4351de3beca7a6396797a7f5de185/src/vs/workbench/contrib/debug/browser/debugActions.ts#L892)

**Comment by sandy081** [comment]
It does not look correct to me having a method that does not take resource in `ITextResourcePropertiesService`. Only callee who does not pass `resource` is 
https://github.com/Microsoft/vscode/blob/bc9a93e67ba274ed3cf4d0c951cca5d93eaf7060/src/vs/editor/common/services/modelServiceImpl.ts#L197

It looks like @alexandrudima added this `null | undefined` to `resource` parameter for the above case.

@alexandrudima Any insights on why you need this?

**Comment by sandy081** [comment]
Moving this to @alexandrudima as he introduced above.
