### ISSUE TITLE
Wrong column selected when using 'go to line'

### ISSUE THREAD

**Issue by goulashsoup** [microsoft/vscode#70497]
Issue Type: <b>Bug</b>

1. Open a file with a very long line e.g. js.min-file.
2. Open the line selection command (`Ctrl + P > go to line`, `Ctrl + G`)
3. Select a line and a column with a big column number e.g. `:65,91334`
4. A wrong column gets selected.

![issue](https://user-images.githubusercontent.com/33103832/54371635-05df8580-467a-11e9-8a0a-a989a150a36e.gif)

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-todo-plus|fab|4.11.4
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-language-babel|mgm|0.0.22
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by rebornix** [comment]
The `line, column` status doesn't represent the view column information, instead it displays the character information in JS string, which is the one we use to store the text buffer. To fix this issue we need proper unicode text segmentation.
