### ISSUE TITLE
SCM: Add repo actions in panel header

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#70494]
Issue Type: <b>Bug</b>

~~In the SCM sidebar the behavior of repo multi-select has seem to change in the recent insiders. Previously in 1.32.2, the order of the repo multi-select would determine the order of the repos shown. Now the order seems to always be the same (almost alphabetic but not) which feels like a step backward. If the desire it to be more consistent and deterministic, I would suggest using the same order they are in the "master" view as that is the order of the workspace folders (which is controllable by the user).~~

~~I do like that is now remembers the multi-selection when reloading a workspace now though.~~

I just wish each repo view had the branch/status info in its title. It would also be great if there was a way to have an auto-collapse/expand mode on each repo -- like a 3rd state (not expanded or collapsed) which would stay collapsed while there were no changes in the repo but would auto-expand when there were.

VS Code version: Code - Insiders 1.33.0-insider (7258b995f63827ff1b179f47722e500296d64c35, 2019-03-14T06:19:44.881Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (19.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
After doing more playing around with this -- I see now that the order of the "details" can be rearranged just like any other view (and preserved). This is great! So now given the new remembering of which repos should be shown and their order (position), I can almost get rid of the "Source Control Providers" view altogether.

I just wish each repo view had the branch/status info in its title. It would also be great if there was a way to have an auto-collapse/expand mode on each repo -- like a 3rd state (not expanded or collapsed) which would stay collapsed while there were no changes in the repo but would auto-expand when there were.

**Comment by joaomoreno** [comment]
@eamodio The SCM views now behave like all other views, they can easily be resorted and that will be preserved. Is the multi select order really critical for you?

**Comment by eamodio** [comment]
I think this is basically addressed with the recent SCM changes
