### ISSUE TITLE
Expanding a folder is a long running process?

### ISSUE THREAD

**Issue by psgivens** [Microsoft/vscode#70499]
Issue Type: <b>Bug</b>

When I try to open a project folder, it gives me a progress indicator and takes a while. I expect expanding a folder to be instantanious. What the heck is it doing? 

![image](https://user-images.githubusercontent.com/195981/54374230-eaee2080-463b-11e9-9810-5eaa1b578482.png)

This is a workspace with a few projects in it, but it happens in subfolders too. This started happening recently, may in the last week. 

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-markdownlint|Dav|0.25.0
json-tools|eri|1.0.2
php-debug|fel|1.13.0
plantuml|jeb|2.10.7
python|ms-|2019.2.5558
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
team|ms-|1.149.2
vscode-docker|Pet|0.6.0
serverless-ide-vscode|Thr|0.2.3

</details>

**Comment by beard7** [comment]
I'm experiencing the same issue, but with a single project... no workspace involved. This has started within the last few days.

Same thing happens when opening a file. VS Code then won't close and has to be killed from Task Manager.

I'm on the verge of doing a full system restore, but if the problems remains, that's a massive waste of time.

**Comment by beard7** [comment]
Reverting to version 1.30.2 fixes the problem (now I just have to disable auto updates).
