### ISSUE TITLE
add merge to local branchs

### ISSUE THREAD

**Issue by herbertpimentel** [Microsoft/vscode#705]
code is just awesome and simple for "git fresh users" and we just miss the ability to merge our local branch just like github for windows does (but does not work well with non github repos)

* visually show branchs and can alternate between them without command
* allow drang a branch on top of other to perform a merge

**Comment by joaomoreno** [comment]
I'm gonna *merge* this into #68.

**Comment by thedamon** [comment]
I don't think this is really the same as #68. I'm trying to find how to use VSCode to do a merge, but that's not the same as history.

**Comment by joaomoreno** [comment]
It's not, but its definitely related. Once we have a history, merging is but a contextual action.
