### ISSUE TITLE
A default export can only be used in an ECMAScript-style module.

### ISSUE THREAD

**Issue by marianatuma** [Microsoft/vscode#70504]
Apologies if this isn't the right place for this, but I have already opened a StackOverflow question about it [here](https://stackoverflow.com/questions/55162493/how-to-debug-a-react-add-in).

I'm trying to debug an Excel add-in, but am running into various problems. The add-in was generated using `yo office` from the `generator-office` tool. Options chosen were Excel and React. I then followed this [tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react). I was able to sideload and use it with no problems. I then added a `console.log(props)` to the constructor of `Content.tsx` just to have a look, but couldn't see the output on Powershell or on Edge. 

Some googling later, I tried to attach a VS debugger. I describe the problems I had with this [here](https://stackoverflow.com/questions/55146089/difficulties-debugging-add-in). Anyway, I gave up on that and moved on to VSCode. At first, starting the debugger gave me a "No program to debug" error. After some more googling, I arrived at the following `launch.json` and `tsconfig.json`:

`launch.json`:

    {
    "version": "0.2.0",

    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/src/index.tsx",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outfiles": [
                "${workspaceFolder}/out/**/*.js"
            ]
        }
    ]
    }

`tsconfig.json`:

     {
      "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "jsx": "react",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "outDir": "out",
        "allowUnusedLabels": false,
        "noImplicitReturns": true,
        "noUnusedParameters": true,
        "noUnusedLocals": true,
        "lib": [
          "es7",
          "dom"
        ],
        "pretty": true,
        "typeRoots": [
         "node_modules/@types"
        ]
      },
      "exclude": [
        "node_modules"
      ],
      "compileOnSave": false,
      "buildOnSave": false
     }

Unfortunately, this still isn't working. This is the output in VSCode's terminal:

    > Executing task: c:\{path}\node_modules\.bin\tsc.cmd -p c:\{path}\tsconfig.json

    node_modules/@microsoft/office-js-helpers/dist/office.helpers.d.ts:628:10 - error TS1319: A default 
    export can only be used in an ECMAScript-style module.

    628   export default function stringify(value: any): string;

(That first line does say `tsconfig.jso` CORRECTION: It seems the n was simply being cut out).

**Comment by usernamehw** [comment]
It looks like an issue with `office-js-helpers` https://github.com/OfficeDev/office-js-helpers/issues/82

**Comment by roblourens** [comment]
Agreed, it looks like your problem is with running the add-in at all, not debugging it in vscode.

**Comment by roblourens** [comment]
`outFiles` has a capital F which will fix one of your warnings, but won't fix this issue.
