### ISSUE TITLE
JSDoc includes initial * for code snippet

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70506]
Version: 1.33.0-insider
Commit: 7258b995f63827ff1b179f47722e500296d64c35
Date: 2019-03-14T06:14:28.810Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 17.7.

For the below interface:

```ts
export interface MyInterface {
	/**
	 * Absolute path to the test suite folder. Must include an `index.js` that
	 * exports a test runner, such as:
	 *
	 * ```ts
	 * import * as testRunner from 'vscode/lib/testrunner';
	 * module.exports = testRunner;
	 * ```
	 */
	testRunnerPath: string;
}
```

When using the parameter, TS shows such hover:

![image](https://user-images.githubusercontent.com/4033249/54376926-54246280-4641-11e9-831a-92be3c0f9a45.png)

I understand this comes form TS, but @mjbvz I remember you were doing some special handling of the leading `*`, so maybe TS could do the same thing.

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/23517

I've marked it as a priority to be fixed
