### ISSUE TITLE
Make tasks run commands with parenthesis in them when PowerShell is the shell

### ISSUE THREAD

**Issue by Dangerous-Mind** [Microsoft/vscode#70509]
Not Fixed on Insider.

- VSCode Version: 1.32.2
- OS Version: Windows 10.0.17763

Steps to Reproduce:

1. In a SPFx project when I try make the following entry (or similar) on the terminal:
`C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd package-solution --ship`

2. 
```
CompanyName: The term 'CompanyName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:21
+ C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd package-sol ...
+                     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CompanyName:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Does this issue occur when all extensions are disabled?: Yes

Recently there was a bug on this command line also. It didn't support special chars on the command line (like ã, õ,ç... ). After the fix on the previous version this problem appeared.

**Comment by roblourens** [comment]
Are you typing that in the terminal manually or is this from a task or something?

**Comment by Dangerous-Mind** [comment]
The command it's part of a plugin that creates tasks.
It creates a package to deploy to SharePoint.

But the same happens in the terminal command line if I include the full path.

I don't insert the full path if I create a package manualy but things could get weired if vscode thinks that a path with brackets are cmdlets.

**Comment by roblourens** [comment]
This is the windows command prompt, not vscode. The path should be quoted or escaped, please file this on the extension that writes it to the terminal

**Comment by Dangerous-Mind** [comment]
Hi @roblourens ,

The path is quoted by the extension and the command works fine on command prompt.
Can you please reopen the case?

Ex:
```
Executing task: "C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship <

CompanyName: The term 'CompanyName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:21
+ C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd package-sol ...
+                     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Aenergy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
The terminal process terminated with exit code: 1
```

**Comment by roblourens** [comment]
So this is a task?

**Comment by Dangerous-Mind** [comment]
Yup.
> The command it's part of a plugin that creates tasks.

Same entry on Command prompt:

```
C:\_Projects\SPFx\All\smallWebparts>"C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship
Build target: SHIP
[15:05:55] Using gulpfile C:\_Projects\SPFx\All\smallWebparts\gulpfile.js
[15:05:55] Starting gulp
[15:05:55] Starting 'package-solution'...
[15:05:55] Starting subtask 'configure-sp-build-rig'...
[15:05:55] Finished subtask 'configure-sp-build-rig' after 6.21 ms
[15:05:55] Starting subtask 'package-solution'...
```

**Comment by alexr00** [comment]
In https://github.com/Microsoft/vscode/issues/70509#issuecomment-473329541
Are you running from cmd.exe or PowerShell?
If you are running from cmd.exe can you try running from PowerShell?

**Comment by Dangerous-Mind** [comment]
Thanks for your reply Alex,

This issue started two versions ago.

In PowerShell I get:

With Quotes:
```
PS C:\_Projects\SPFx\All\smallWebparts> "C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship
At line:1 char:61
+ ... MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship
+                                                   ~~~~~~~~~~~~~~~~
Unexpected token 'package-solution' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

Without Quotes:
```
PS C:\_Projects\SPFx\All\smallWebparts> C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd package-solution --ship
CompanyName: The term 'CompanyName' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:21
+ C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd package-sol ...
+                     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CompanyName:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by alexr00** [comment]
@Dangerous-Mind if you can find a way to run the .cmd file with a path with parenthesis in PowerShell, let me know and I will try to fix tasks so it works the same way. I went back to version 1.30.1 and it doesn't work there either.

**Comment by Dangerous-Mind** [comment]
To run it on a PowerShell command with quotes we can use the &:

`& "C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship`

**Comment by alexr00** [comment]
I don't think that will work for tasks. We need a way to run the file that looks like this:
`powershell.exe -Command <your cmd file>`
For your case it might just be best to add this to your task so that it doesn't run in powershell:
````
"options": {
	"shell": {
		"executable": "cmd.exe",
		"args": ["/c"]
	}
},
````

**Comment by Dangerous-Mind** [comment]
This works:
powershell.exe -Command "C:\Users\MyName`(CompanyName`)\AppData\Roaming\npm\gulp.cmd" package-solution --ship

Add a ` char before the ( and ).

I really don't know who could or should add a patch for this. I just pointed to vscode because it started seconds after a vscode update on several machines.
On the other hand its very dangerous for you to insert ` chars inside code inserted by the client.

Can you please check?

The command is inserted by a vscode plugin. I cant/shouldn't change its code. 
But I can contact them to check for this issue.

**Comment by alexr00** [comment]
We already do some character escaping for commands run through tasks, so if there's a good way to escape it then I can add it if there is a need for it. It looks like the ` character properly escapes the parentheses so I can make the change to escape them when I have time. Thank you!

**Comment by alexr00** [comment]
After thinking about it some more, I think that the best solution here is for you to just set your integrated terminal to use cmd.exe instead of powershell.exe. Tasks does do some character escaping, but if we start escaping ( and ) then we might escape them when they shouldn't be escaped. The extension could possibly do the escaping, since they know that they have a path and that the path is safe to escape. However, your user path has  ( ) in it, which means you might have this issue with other tasks too. 

You can set this in settings `	"terminal.integrated.shell.windows": "cmd.exe"`
Or you can modify the task in tasks.json to use cmd.exe on Windows https://code.visualstudio.com/Docs/editor/tasks#_customizing-autodetected-tasks

**Comment by Dangerous-Mind** [comment]
Yeah it's better that way, it would could have a tremendous impact to change it on your side.
I'll try to talk to the owner of the  plugin to see if he can fix it from there side.

Thanks for your support @alexr00
