### ISSUE TITLE
Step over not working in attached node (electron)

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#7051]
- VSCode Version: alpha
- OS Version: Windows 10

Steps to Reproduce:
1. clone vscode-elint, cd eslint && npm install && cs ../eslint-server && npm install
2. open code on eslint and eslint-server folder. In both instances start build (Ctrl+Shift+B)
3. in eslint press F5
4. open a workspace that has JS files and eslint installed
5. go to vscode that has eslint-server open
6. attach
7. open server.ts
8. set a breakpoint at line 175
9. go to the launched VS Code instance
10. type into the js file. Observe: breakpoint is hit
11. click step over

Observe: debugger continues

**Comment by weinand** [comment]
@dbaeumer most likely you are running into this node bug: https://github.com/nodejs/node/issues/7219
