### ISSUE TITLE
command 'git.clone' not found

### ISSUE THREAD

**Issue by fsmith03** [Microsoft/vscode#70513]
Issue Type: <b>Bug</b>

I cannot use github clone. The command returns the error "command 'git.clone' not found"
This is a fresh install of VSCode and Github.
How do I fix this?

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (27.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
lambda-snippets|log|1.0.0

</details>

**Comment by joaomoreno** [comment]
If you open the Extensions view, click the `...` menu and choose `Show Built-in Extensions`, does Git show up?
