### ISSUE TITLE
Terminal does not display prompt text

### ISSUE THREAD

**Issue by DeborahK** [Microsoft/vscode#70517]
Searched "terminal", did not find any similar issues.

Version: 1.32.2 (user setup)
Commit: e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951
Date: 2019-03-13T02:00:46.035Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open the terminal
2.

Does this issue occur when all extensions are disabled?: Yes/No
I don't currently have any extensions.

When I open the terminal, the terminal text does not appear. This began to happen in January and I assumed it would be fixed in a later release. Several updates later, the problem persists.

Notice in the attached screen shot that there is no prompt text. I type: npm start and it appears where it should, but there is no text to the left.

![image](https://user-images.githubusercontent.com/7987365/54392486-0d486400-4665-11e9-9fbf-ee1d8483a69d.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by DeborahK** [comment]
I can't comment on the duplicate post, so I'm adding my question here:

I will be recording several videos and I can't record with no text appearing. Is there any work-around? Some way to get the text to display? (Or at least a new expected date?)

(I understand it was supposed to be last November, but the last post in February says it's been delayed.)

**Comment by Tyriar** [comment]
@DeborahK unfortunately the only workarounds are:

- Press enter twice to get the prompt to show up
- Use Linux/macOS (probably not an option)
- Use Windows 1803
- Use Windows Insiders and set `"terminal.integrated.windowsEnableConpty": true`
