### ISSUE TITLE
Unexpected task runtime error when running tasks

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#70511]
Issue Type: <b>Bug</b>

Since the introduction of PR https://github.com/Microsoft/vscode/pull/66819, anytime I try to run any task in my workspace it fails with `Unexpected task runtime`. I've tracked it down to having a task defined that uses the `dependsOn` property -- even when that isn't the task being run. Just the existence of a task with `dependsOn` in the `tasks.json` will cause all tasks to fail.

Here is the code that throws the error:
https://github.com/Microsoft/vscode/pull/66819/files/8f21e46353a558c141367e4ddd92c8c8e688ad20#diff-24a99c59e6990af6624d30ba8e8e438eR610

/cc @Tyriar @alexr00 

VS Code version: Code - Insiders 1.33.0-insider (7258b995f63827ff1b179f47722e500296d64c35, 2019-03-14T06:19:44.881Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexr00** [comment]
@eamodio, do you have any additional repro steps? I cannot reproduce the error with this tasks.json:
````json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "task 1",
            "type": "shell",
            "command": "echo 1",
            "problemMatcher": [],
            "dependsOn": "task 2"
        },
        {
            "label": "task 2",
            "type": "shell",
            "command": "echo 2",
            "problemMatcher": []
        }
    ]
}
````

**Comment by eamodio** [comment]
@alexr00 I'm trying to reproduce this in a sample I can easily share, but now also I'm running into a related issue.

In GitLens I have the following tasks:
https://github.com/eamodio/vscode-gitlens/blob/b0941c2acc4a2c0980e58541c6dfc234cfd5235e/.vscode/tasks.json#L18-L40
```json
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "group": "build",
            "problemMatcher": ["$ts-webpack", "$tslint-webpack"]
        },
        {
            "type": "npm",
            "script": "lint",
            "group": "build",
            "problemMatcher": ["$tslint5"]
        },
        {
            "type": "npm",
            "script": "watch",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "isBackground": true,
            "problemMatcher": ["$ts-webpack-watch", "$tslint-webpack-watch"]
        }
    ]
```

But anytime I try to start either the `build` or the `lint` task I get:
```
Failed to create terminal for task npm: lint
ERR Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
    at x.createTerminal (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3081:26)
    at e.configurationProperties.isBackground.Promise (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3074:495)
    at new Promise (<anonymous>)
    at x.executeInTerminal (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3074:459)
    at resolveVariablesFromSet.then.i (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3071:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
log.ts:173   ERR Failed to create terminal for task npm: lint: Error: Failed to create terminal for task npm: lint
    at x.executeInTerminal (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3076:877)
    at resolveVariablesFromSet.then.i (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3071:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The error is coming from the line below, because `this.terminals[idleTerminalId]` is undefined

https://github.com/Microsoft/vscode/blob/63642b538a699478baca9e389908b9ba5be0bb3e/src/vs/workbench/contrib/tasks/electron-browser/terminalTaskSystem.ts#L928

**Comment by eamodio** [comment]
@alexr00 I also figured out the cause of the `Unexpected task runtime error` issue. I was wrong, it wasn't just related to `dependsOn` it only seems to happen, when you have no command/script/etc (only a `dependsOn`) and also have a `presentation.group`, see below.

```
        {
            "type": "npm",
            "script": "watch",
            "group": "build",
            "isBackground": true,
            "problemMatcher": [],
            "presentation": {
                "group": "vscode"
            }
        },
        {
            "label": "watch",
            "dependsOn": ["npm: watch"],
            "group": "build",
            "isBackground": true,
            "problemMatcher": [],
            "presentation": {
                "group": "vscode"
            }
        }
```

If you try to run the `watch` task it will fail with `Unexpected task runtime error`

**Comment by alexr00** [comment]
I just got that too, and then it stopped happening (without me doing anything other than looking away from it for a few minutes). I'll make a fix for that one.

re the original issue: Thanks for the new tasks, I'll try again.

**Comment by eamodio** [comment]
Yeah, my vscode just updated and the issue went away too.

**Comment by alexr00** [comment]
Reproduced and fixed. Thanks for reporting it!
