### ISSUE TITLE
Project snippets

### ISSUE THREAD

**Issue by hafofu** [Microsoft/vscode#70516]
I create alot of React projects and the steps to setup a project are usually the same.
Setup Webpack/Parcel, setup ESLint, setup prettier etc.
It would be cool to have something like code snippets, but on a folder/file level.
So you can have a snippet for example for react projects, which will create the folders and files etc.

**Comment by jrieken** [comment]
You have that: simply put a `*.code-snippets` file in the `.vscode` folder, like this: https://github.com/Microsoft/vscode/blob/9fb1a067b683a51e568126c83787a49ceaac04f6/.vscode/shared.code-snippets
