### ISSUE TITLE
characters are automatically indented

### ISSUE THREAD

**Issue by git710** [Microsoft/vscode#70528]
Issue Type: <b>Bug</b>

When copying and pasting code from other documents, two characters are automatically indented.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
mithril-emmet|Fal|0.7.1
vscode-language-pack-zh-hans|MS-|1.32.4
sublime-keybindings|ms-|4.0.0
open-in-browser|tec|2.0.0

</details>

**Comment by rebornix** [comment]
You can turn off this feature by setting `editor.autoIndent` to false.
