### ISSUE TITLE
Editor status bar entries don't go away

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#70520]
- Open a file
- Close the file so that no editors are open
- See that the status bar is still reporting the line/column/language mode, etc

![image](https://user-images.githubusercontent.com/323878/54395173-4cc67e80-466c-11e9-8887-de7d447aa3e3.png)

Reproes in 1.32 but not a few versions ago at least

**Comment by mjbvz** [comment]
Duplicate of #70321
