### ISSUE TITLE
February 2019 Recovery 3 Endgame 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70525]
- [x] Create a milestone `<Month> Recovery <year>` @octref
- [x] Bump the version number @octref
- [ ] ~~Include an issue 'update translations' @octref~~
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch @octref
- [x] Make rpm signing request **@Tyriar**
- [x] Issues are verified on `stable` build and the `verified` label is added @octref
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch @octref
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits
  - [x] Windows - @roblourens 
  - [x] OS X - @mjbvz
  - [x] Linux - @RMacfarlane 
- [x] Sanity check installable stable bits that have not been smoke tested
  - [x] Windows
    - [x] signed installer 32-bit @octref
    - [x] signed installer 64-bit @octref
    - [x] zip 32-bit @octref
    - [x] zip 64-bit @octref
  - [x] OS X - @octref
  - [x] Linux
    - [x] deb package 32-bit @RMacfarlane 
    - [x] deb package 64-bit @rebornix 
    - [x] rpm package 64-bit @RMacfarlane 
    - [x] rpm package 32-bit @rebornix 
    - [x] archives @rebornix @RMacfarlane 
- [x] Publish website **@gregvanl**
- [x] Publish stable build @octref
- [ ] Publish rpm to repository manually **@Tyriar**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z`

**Comment by kevine-voicera** [comment]
What does `Recovery` mean in release name?

**Comment by roblourens** [comment]
The x.1, x.2, x.3 etc releases are called "Recovery" releases

**Comment by kevine-voicera** [comment]
@roblourens Does this loosely translate to "bug fix" releases? Trying to understand the key purpose.

**Comment by roblourens** [comment]
Yes: https://github.com/Microsoft/vscode/wiki/Running-the-Endgame#recovery-build you may also be interested in https://github.com/Microsoft/vscode/wiki/Development-Process

**Comment by kevine-voicera** [comment]
Thank you very much, @roblourens !
