### ISSUE TITLE
Casing shown in file explorer is different from that on disk.

### ISSUE THREAD

**Issue by terry-au** [microsoft/vscode#70522]
Issue Type: <b>Bug</b>

I renamed a directory from "Components" to "components" with VSCode and have since rebooted, yet VSCode reports that the directory is named "components" whereas Finder displays it as "Components". Additionally, TypeScript is unable to resolve files as the name of disk varies from that is referenced in my code.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T01:56:08.693Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.25.0
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.47
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
code-runner|for|0.9.7
shell-format|fox|4.0.4
beautify|Hoo|1.4.9
gitignore|mic|1.0.1
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.0
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.6.3
java|red|0.40.0
vscode-yaml|red|0.3.0
LiveServer|rit|5.5.1
sonarlint-vscode|Son|1.6.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.0
vscode-maven|vsc|0.15.0
vscode-icons|vsc|8.3.0
vscode-react-native|vsm|0.8.0
tslint-snippets|zuo|1.1.0

(2 theme extensions excluded)

</details>

Screenshot of the issue I'm describing:
![image](https://user-images.githubusercontent.com/22073694/54397220-d5dfc300-4709-11e9-8068-c995d5042c3a.png)

**Comment by isidorn** [comment]
I can not reproduce this.
Yes, when you rename a file from  "Components" to "components" vscode will not immediatly pick it up but when I click on the "refresh" in the explorer or when I do F1 > Reload, explorer picks up the proper casing.
If you do that can you still reproduce?
Also can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by SetTrend** [comment]
Same here.

![image](https://user-images.githubusercontent.com/9283914/55010630-d408e000-4fe4-11e9-829d-de78cb647340.png)

This happens when one team member renames the casing of a file and other team members checkout that change. VS Code doesn't recognize the change in casing and believes that the file still has the original casing. So when hitting "Go To Definition", VS Code always opens a second editor, titled with the old name plus "file deleted" appended to the file name in the title.

**Comment by isidorn** [comment]
Closing as can not reproduce. And no exact steps provided (also their might be similar issues that are open)
