### ISSUE TITLE
Default file extension for new files when saving without one

### ISSUE THREAD

**Issue by flow2k** [Microsoft/vscode#70523]
For new, plain text files, it is sometimes convenient to not have to type ".txt" as the filename extension when saving. Many editors, such as Atom and Sublime, already support having a default extension when none is supplied at save-time.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/54413203-27ca1e00-46f5-11e9-962c-6262b9d702ae.png)

**Comment by flow2k** [comment]
Unfortunately, setting `"files.defaultLanguage": "txt"` did not save my new file with `.txt` extension.
