### ISSUE TITLE
打开终端路径问题

### ISSUE THREAD

**Issue by coxoll** [Microsoft/vscode#70534]
Issue Type: <b>Bug</b>

打开终端不显示路径，回车一次才显示。（之前没有这种问题重装完系统出现的）

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
copy-relative-path|ale|0.0.2
color-info|bie|0.5.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
jquerysnippets|don|0.0.1
translation|dus|0.0.4
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.8.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.9
HTMLHint|mka|0.5.0
vscode-filesize|mkx|2.1.2
easy-less|mrc|1.4.5
vscode-language-pack-zh-hans|MS-|1.32.4
vetur|oct|0.16.2
vscode-css-peek|pra|2.2.0
LiveServer|rit|5.5.1
partial-diff|ryu|1.4.0
vscode-toggleproxy|sat|0.4.6
code-settings-sync|Sha|3.2.7
html5-boilerplate|sid|1.0.3
win-opacity|ska|1.0.8
open-in-browser|tec|2.0.0
vscode-icons|vsc|8.3.0
quokka-vscode|Wal|1.0.195
vscode-preview-server|yui|1.2.1
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by sxyugao** [comment]
曾经有段时间也有这个问题，但是后来莫名其妙好了。。

**Comment by yzhang-gh** [comment]
Windows 系统版本的问题（见 #57803）

**Comment by roblourens** [comment]
Sorry, Google Translate is not doing a good job here, so I don't understand the issue. Please file issues in English.
