### ISSUE TITLE
serverReadyAction doesn't work

### ISSUE THREAD

**Issue by btmorex** [Microsoft/vscode#70537]
Issue Type: <b>Bug</b>

1. Configure serverReadyAction as follows:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Web Server",
      "program": "${workspaceFolder}/build/out/development/src/backend/web/server.js",
      "preLaunchTask": "Build",
      "serverReadyAction": {
        "pattern": "server started",
        "uriFormat": "http://localhost/",
        "action": "openExternally"
      }
    }
  ]
}
```

2. Expected to see browser launch when I start debugging. Instead server starts (printing "server started" to debug console) and nothing happens.

VS Code version: Code - Insiders 1.33.0-insider (7258b995f63827ff1b179f47722e500296d64c35, 2019-03-14T06:12:59.861Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 2407)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.27GB (23.05GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by weinand** [comment]
The "preview" version of the feature assumed that "pattern" has a capture group and "uriFormat" uses a substitution placeholder '%s'.
Both assumptions do not hold in your case.

I've relaxed the assumptions and added some error messages.
