### ISSUE TITLE
Display messy code on v1.32.3

### ISSUE THREAD

**Issue by joket1999** [microsoft/vscode#70538]
- VSCode Version: 1.32.3
- OS Version: Mac OS 10.14.3

Steps to Reproduce:

1. update from 1.32.2 and restart vscode
2. open  my file and display messy code like this

![5CF235CF-FFA0-4FB4-AB47-6CDD75D87E0A](https://user-images.githubusercontent.com/6611880/54413271-089cb200-4730-11e9-9697-a0ea83ab6b17.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
- Can you try launching with `--disable-gpu`?
- Have you set `editor.fontFamily`? Can you try changing that setting to see if it makes an impact?

**Comment by tanzhihang** [comment]
@roblourens I uninstall it. Download and install the old version(1.31.1), still not work. But the vs code update to the v1.32.3 automatically and it's ok.

**Comment by rebornix** [comment]
As noted above, it no longer reproduces after update.
