### ISSUE TITLE
optimize activity bar

### ISSUE THREAD

**Issue by ersuman** [Microsoft/vscode#70533]
It would be better if activity bar is optimized to use less space.
I would like to suggest to **add** an option to **view activity bar icons in horizontal tabs above the left panel.** 
See the image below (sorry for the rough sketch)
![image](https://user-images.githubusercontent.com/23517648/54407381-b0e95100-4705-11e9-92ee-2bf4b70febb4.png)

Also, I am not suggesting to remove the current layout of activity bar. Just add options to customize it.
So, the options can be:

- Left dock with larger icon (current style)
- Left dock with smaller icon
- Tabs

Thanks.

**Comment by roblourens** [comment]
Sorry, this is likely not going to happen. We just don't support layouts that are that flexible.
