### ISSUE TITLE
Enhance the plugin manager to reduce performance overhead

### ISSUE THREAD

**Issue by MingHuiLiu** [Microsoft/vscode#70543]
I want to enhance the functionality of the Plugin Manager. Users can customize the mode (Multiple enabled plugin lists). The mode only contains enabled plugins. It can be switched between multiple custom modes. The workspace remembers the current The use of modes.
Sorry, my English is not good.

**Comment by MingHuiLiu** [comment]
The pattern is equal to the list of plug-ins launched. Users can customize multiple patterns, and only one mode can be used in a workspace

**Comment by MingHuiLiu** [comment]
@kaiwood @AArnott @threeve @doudou

**Comment by lifetin** [comment]
和我的遇到问题相同
扩展太多了，开发环境都不同。导致运行变化，或是出现错误的提示。
https://github.com/Microsoft/vscode/issues/69742

**Comment by roblourens** [comment]
Yes this looks the same as #69742

**Comment by lifetin** [comment]
> 是的，这与[＃69742](https://github.com/Microsoft/vscode/issues/69742)相同[](https://github.com/Microsoft/vscode/issues/69742)

这个问题你们是忽略，还是保留呢？
---------------------------------
Are you ignoring or reserving this issue?
