### ISSUE TITLE
Cannot debug cpp or c. MIEngine Internal Error.

### ISSUE THREAD

**Issue by paulzhn** [Microsoft/vscode#70542]
Issue Type: <b>Bug</b>

When I try to debug a cpp file, it occurs to be "Exception of type 'System.ArgumentNullException' was thrown." ![批注 2019-03-15 150029](https://user-images.githubusercontent.com/8180364/54414312-ad6cbe80-4733-11e9-81cd-bb201673ddbf.jpg)

P.S. I have found a similar issue report on Github(https://github.com/Microsoft/vscode/issues/55368), however it was closed and was told to be an extension bug. But the only extension I have in common with that user is cpptools. So I have no idea what's the matter.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (6.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|ms-|2019.2.5558
cpptools|ms-|0.21.0

</details>

**Comment by roblourens** [comment]
This looks like an issue with the cpptools extension, so please file it on their repo.
