### ISSUE TITLE
refresh the tree view repeatedly in an extension

### ISSUE THREAD

**Issue by cranechu** [Microsoft/vscode#70549]
I am working on an extension which monitors external devices. I hope to update the status repeatedly in the tree view, like every 1 or even 0.1 second. It looks like the pic below: 

Now, I have the refresh button working, so I can do it by clicking it repeatedly. Can we trigger the refresh (or corresponding command, keybinding) by a timer? 

![refresh](https://user-images.githubusercontent.com/15793455/54421675-e57dfc80-4747-11e9-9f17-1d6e5308cefe.png)

Thanks!

**Comment by sandy081** [comment]
@cranechu You can call the following API in an interval of you like

https://github.com/Microsoft/vscode/blob/bc9a93e67ba274ed3cf4d0c951cca5d93eaf7060/src/vs/vscode.d.ts#L6741
