### ISSUE TITLE
Missing git decorations in scrollbar when workspace has wrong casing

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7054]
- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. have some git changes
2. sometimes decorations are not shown in the scrollbar

Lately I am getting this quite often.

The right scroll bar has no decorations in this example:
![screen shot 2016-05-31 at 12 27 29](https://cloud.githubusercontent.com/assets/1926584/15671427/13bc0226-272b-11e6-8d23-b814e92d94d8.png)

**Comment by joaomoreno** [comment]
I never got it. Any console error messages?

**Comment by isidorn** [comment]
No error messages, I will try to get repro steps...

**Comment by isidorn** [comment]
I think it was because of wrong casing of my opened workspace on mac.

Ben previously had an issue that file events would get missing for wrong casing workspace on mac. I think he fixed that, but maybe there is something related for these decorations.

**Comment by bpasero** [comment]
You have case issues :|

**Comment by joaomoreno** [comment]
If it is casing, it must be very reproducible when you open it with the wrong case. Did you give it a try?

**Comment by isidorn** [comment]
Yes - it reproduces every time I have wrong casing

**Comment by joaomoreno** [comment]
Closing as there's a workaround.
