### ISSUE TITLE
Problem with creating new classes is still reproducing

### ISSUE THREAD

**Issue by pyrejkee** [Microsoft/vscode#70547]
Issue Type: <b>Bug</b>

Hello,

In last updates of Visual Studio Code was a fix for problem when it was impossible to create new C# class in subfolders.
The problem sometimes occurs. Reloading Visual Studio code helps with it.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (5.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
cucumberautocomplete|ale|2.13.1
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
angular2-switcher|inf|0.2.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|7.0.1
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.3
vetur|oct|0.16.2
material-icon-theme|PKi|3.6.3
bootstrap4-vscode|the|6.1.0

</details>

**Comment by roblourens** [comment]
Please open this issue on the C# extension repo
