### ISSUE TITLE
VSCode remove whitespaces on debugging time

### ISSUE THREAD

**Issue by GregorBiswanger** [Microsoft/vscode#7055]
- VSCode Version: 1.1.1
- OS Version: Windows 8.1

Hi,
VSCode show only one whitespace character from variables on debugging time.
On mouse over and on the debug console.

`let whitespace = "";
        
whitespace += " ";
console.log("A" + whitespace + "B");
whitespace += " ";
console.log("A" + whitespace + "B");
whitespace += " ";
console.log("A" + whitespace + "B");
whitespace += " ";
console.log("A" + whitespace + "B");
`

**Comment by isidorn** [comment]
Works with latest vscode that will be released the following week
![screen shot 2016-06-01 at 11 34 36](https://cloud.githubusercontent.com/assets/1926584/15704884/df244b8c-27ec-11e6-9f5b-7caaa1f79128.png)
