### ISSUE TITLE
Pressing Enter when creating a new directory in the Explorer pane with a name that conflicts with a file name collapses the parent directory

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#70552]
Go to Explorer pane, find a directory you like, e.g. `src`, right-click it and select New Folder, then type a name of an existing file in `src` and observe VS Code showing an error due to the name conflict, press Enter to commit anyway and observe `src` going from expanded to collapsed state for no reason. Nothing gets created. This also happens in Insiders.

- VSCode Version: 1.32.3 and Insiders
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@TomasHubelbauer good catch, thanks for reporting.
Try it out in next weeks vscode insiders and let us know if the issue is fixed for you.
