### ISSUE TITLE
Extensions icon shows one update available when no updates

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#70558]
Issue Type: <b>Bug</b>

After reloading a window (or I think starting VS Code) the extensions icon shows one update available. In the "@outdated" list there's nothing showing. See screenshot:
![image](https://user-images.githubusercontent.com/17859340/54428025-13e1e480-4714-11e9-9e47-ef528dca319f.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (22.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|3.0.2
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.5.1
matlab|Gim|0.9.0
triggertaskonsave|Gru|0.2.7
vscode-dimmer|hoo|2.1.0
string-manipulation|mar|0.3.1
select-part-of-word|mle|1.0.1
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
vsliveshare|ms-|0.3.1326
indent-rainbow|ode|7.3.0
vscode-clearcase|Ope|2.1.0
vscode-icons|rob|8.2.0
vscode-header-source|ryz|1.3.0
code-settings-sync|Sha|3.2.7
indenticator|Sir|0.6.0
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
sensitive-replace|vil|0.1.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(3 theme extensions excluded)

</details>

**Comment by paidhi** [comment]
Noticed the same issue here. I was going through my list of extensions and noticed that an update for the vscode-icons extension was available. I updated the vscode-icons extension and did not have that display issue again. Maybe it is related to the setting `"vsicons.dontShowNewVersionMessage": true`.

**Comment by sandy081** [comment]
@BillDenton Do you have auto update available? If so, it could be that time interval where extension would have auto updated and the badge is taking a moment to sync?

**Comment by BillDenton** [comment]
Auto update is disabled:
![image](https://user-images.githubusercontent.com/17859340/54611289-8fae9a80-4a4e-11e9-96d7-9ea502b80a12.png)

**Comment by Roemer** [comment]
I have the same issue. But as soon as I go to the Extensions Marketplace, the notification goes away until I restart vscode, then it comes back.

**Comment by Roemer** [comment]
I think I found the issue. For some reason, it did not show an update when viewing my installed extensions. But when browsing the marketplace, it shows the installed `vscode-icons` with the buttons `Update to 8.3.0` and `Reload Required`. After pressing the update button, the problem went away.
![image](https://user-images.githubusercontent.com/393641/54667309-4f055e80-4aec-11e9-8019-eb7f9ffd986d.png)

**Comment by rsola** [comment]
Hello, I was facing the same issue. It was a bit annoying. Thanks for the hint with respect to the vscode-icons extension. However, Visual Studio Code (version 1.32.3 on Windows, extracted from ZIP, autoupdate disabled for extensions) wasn't offering me the update from version 8.2.0 to 8.3.0. I uninstalled the vscode-icons extension and I installed it again, then the "update of Schrödinger" issue went away. Now, the version number of the installed extension is the right one (8.3.0).

I think it could be related to a publisher name change. There is a report on this subject in its own repository: vscode-icons/vscode-icons#1908.

**Comment by sandy081** [comment]
Is it with vscode-icons extensions that everybody is seeing?

**Comment by jens1o** [comment]
I also see this, and I also use vscode-icons.

**Comment by sandy081** [comment]
Very strange that this happens only with specific extension, I would suggest to file the issue against vscode-icons extension and probably get investigated first from extension perspective.

**Comment by enricoreich** [comment]
> 
> 
> Is it with vscode-icons extensions that everybody is seeing?

Yes! I had vscode-icons 8.2.0 installed and got this annoying "outdated note" too but version 8.4.0 was already out (did not know that). VSCode did not show the update button for this extension. So, I uninstalled vscode-icons and reinstalled version 8.4.0 and now the problem is gone.

**Comment by sandy081** [comment]
I see vscode-icons got renamed after 8.2.0. Will try to investigate and see why updates are not shown.

**Comment by sandy081** [comment]
I tried it and I could see the update and could update the extension.

**Comment by BillDenton** [comment]
No out of date extensions showing, so I searched for "vscode-icons". This shows that it was out of date, and needed reloading to complete the installation. I reloaded, but this didn't make any difference. I then updated. It now says "The icons manifest will be regenerated. Select 'Restart' for changes to take effect.". After restarting the "one update available" has gone away. It's now on 8.4.0.

**Comment by BillDenton** [comment]
From https://github.com/vscode-icons/vscode-icons/blob/master/CHANGELOG.md:
8.3.0 (March 14, 2019)
Fix: Changed publisher name. @robertohuertasm in #1909)
Fix: Fixed changelog typo. @jakobpack in #1884)

Could the "Changed publisher name" be the problem?

**Comment by Duracell1989** [comment]
Came here because I also had 1 update which didn't show in the "@outdated" list. Searching manual showed me the vscode-icons update. After updating and reloading - the update badge is gone.

**Comment by erihanse** [comment]
I have the same issue, but when I open the extensions panel, it goes away.

**Comment by enricoreich** [comment]
I can confirm that, this issue occurs again.

```
Version: 1.36.0-insider (system setup)
Commit: c3fe2d8acde04e579880413ae4622a1f551efdcc
Date: 2019-06-20T05:20:10.276Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by fxn** [comment]
I have the same issue, and don't have `vscode-icons` installed. This happened months ago too.

**Comment by rsola** [comment]
I didn't have any issue with `vscode-icons` updates since I applied the uninstall/reinstall workaround three months ago.

I think another extension may have been renamed in the last few days. Cannot repro this time. @erihanse, @enricoreich and @fxn, you should figure out what installed extensions you might have in common and check their last update date, release notes and change log. One of these extensions might be the culprit.

**Comment by enricoreich** [comment]
Thanks @rsola for your advice. I've done this before (116 extensions  :scream: ) but found nothing.
Anyway, the issue is gone in:

```
Version: 1.36.0-insider (system setup)
Commit: 41691474e5fa22a279d49fc4b58af66bc11ce41b
Date: 2019-06-26T05:20:29.762Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Also vscode-icons was updated yesterday from version 8.7.0 to 8.8.0 but I don't think this was the issue.
Maybe some internal VSCode extension? I don't know.

**Comment by fxn** [comment]
How is extension rename related to this? Is it a known bug?

**Comment by sandy081** [comment]
There is an UI issue that is not syncing the renamed extension with the extension that is running. Hence this issue appears.

**Comment by sandy081** [comment]
To Verify:

1. Install any extension
2. Go to Extensions folder and open its `package.json` and update publisher id to different value and version to old version. 
3. Make sure `.obsolete` file in the extensions folder does not has the entry to which you updated
4. Open VS Code and you should see an update badge on extensions viewlet
5. Above extension in extension viewlet should show an update action

Verify steps 4 and 5 by reloading the window when in extensions view and when not in extensions view.
