### ISSUE TITLE
Editor format modifies markojs handles

### ISSUE THREAD

**Issue by rtalwar26** [Microsoft/vscode#70550]
Issue Type: <b>Bug</b>

<${input.renderBody}/> gets formated to <$ {input.renderBody}/> when formatting is switched on for markojs templates. https://markojs.com/docs/body-content/

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|10.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
vscode-color|ans|0.4.5
swagger-viewer|Arj|2.2.0
path-intellisense|chr|1.4.2
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
gitlens|eam|9.5.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.9
emoji-code|idl|0.7.4
graphql-for-vscode|kum|1.13.0
sonic-pi|mac|0.0.1
web-browser|mas|0.0.1
azure-account|ms-|0.8.0
cpptools|ms-|0.21.0
Go|ms-|0.9.2
vsliveshare|ms-|0.3.1326
debugger-for-chrome|msj|4.11.3
marko|pca|0.4.0
vscode-docker|Pet|0.6.0
erlang|pgo|0.5.2
tsimporter|pmn|1.2.14
vscode-css-peek|pra|2.2.0
typescript-hero|rbb|3.0.0
ruby|reb|0.22.3
sass-indented|rob|1.5.1
rust|rus|0.5.4
crates|ser|0.3.7
cmake|twx|0.0.17
vscode-lldb|vad|1.2.1
cmake-tools|vec|1.1.3
vscode-ansible|vsc|0.5.2
linecount|yyc|0.1.7
markdown-all-in-one|yzh|2.1.1
html-css-class-completion|Zig|1.18.0

</details>

**Comment by roblourens** [comment]
Sounds like an extension is formatting these documents. Please file this issue on the extension repo
