### ISSUE TITLE
Search input field: do not hardcode border in light theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70555]
It looks like https://github.com/Microsoft/vscode/commit/fe70dbfdbedaa1483fb99156af502249085e38b1 added a border to input fields in light themes. This is not how we use colors given we have theming support.

Please convert this color into a real color that can be themed. Btw I also think we should not have the border by default, we never had it for a long time and I prefer our style where we try to stay away from borders as much as possible. 

![image](https://user-images.githubusercontent.com/900690/54425347-653ea380-4715-11e9-9156-bfaee3c2f684.png)

//cc @misolori

**Comment by bpasero** [comment]
Btw there already is a themable color `input.border`. Why can we not use that?

**Comment by roblourens** [comment]
Did you see the original issue? We need a border for the input in the panel, and not the sidebar. I don't want to add it to every input box, so I don't use theming. 

It's not supposed to show up in the sidebar but I see that it is in Insiders, @sandy081 is this from your change? It has the `panel` class in the sidebar.

**Comment by misolori** [comment]
We already show borders in the panel w/ the problems filter, and setting `input.border` will override it properly. But I do find it odd that this is hard coded.

It also looks like the Settings input fields [have the same treatment,](https://github.com/Microsoft/vscode/blob/5a88160c7dc5db820a564e3872e0de087ff3563d/src/vs/workbench/contrib/preferences/electron-browser/media/settingsEditor2.css#L30) which in this case breaks theming via `workbench.colorCustomizations`:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/35271042/54442860-ae362e00-46fc-11e9-9409-56b0fb875654.png">

**Comment by misolori** [comment]
Actually, why doesn't the search input fields (in the panel) follow the same styling as the problems input field? That seems to handle the styling correctly.

**Comment by roblourens** [comment]
They do follow the problems input, I probably copied it from there.

**Comment by roblourens** [comment]
Settings inputs have their own theme tokens because they are in a different context

**Comment by bpasero** [comment]
I observe the following:
* we need an input border for search when search is in panel
* this border should not show up when search is in the sidebar
* we never ever hardcode a color in CSS so this must be extracted to a color

I hope that makes sense 👍

**Comment by roblourens** [comment]
Yeah, thinking about it more, we should just have a token for all inputs in the panel and apply it to problems as well.

`panel.inputBorder`?

**Comment by bpasero** [comment]
That probably makes sense. //cc @aeschli for input on this color theme related addition.

**Comment by aeschli** [comment]
`panelInput.border`

**Comment by sandy081** [comment]
@roblourens Yes this was caused by my refactorings. SearchView now extends PanelView whose base class is `panel`. Let me fix it so that it looks like before.
