### ISSUE TITLE
Text Wrap Button is invisible

### ISSUE THREAD

**Issue by IT-Delinquent** [Microsoft/vscode#70554]
Issue Type: <b>Bug</b>

Whenever I open VS Code, even after updating and rebooting, the text wrap button is invisible. I still get the tooltip and the invisble button still works but there is no icon. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
python|ms-|2019.2.5558
PowerShell|ms-|1.11.0
vscode-xml-complete|rog|0.1.5
html5-boilerplate|sid|1.0.3
vscode-icons|vsc|8.3.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Sorry which button are you talking about? Can you show a screenshot?

**Comment by IT-Delinquent** [comment]
![image](https://user-images.githubusercontent.com/48588045/54518829-2864ed80-495d-11e9-9bfe-ed305df4f4ed.png)

Sorry, should have included this

**Comment by roblourens** [comment]
I think that whatever button you are missing comes from an extension, because there isn't a builtin text wrap button as far as I know. If you can figure out which extension it is, please file an issue on them.
