### ISSUE TITLE
Double click to select words cancels inline file name editing

### ISSUE THREAD

**Issue by richardtreier** [Microsoft/vscode#70560]
**How it used to be:**
When using F2 to edit a file's name in the explorer, you could use double click to select a word or even select multiple words. This is used when refactoring / renaming files that use kebap case, for example in Angular Projects.

**Now:** 
when you double click a word in the file name, after you release the mouse button, the inline file name editing will be closed.

This makes copy-pasting and refactoring files very tedious, as one has to use arrow keys and Ctrl + Shift + Arrow Keys to select words, or even worse, the mouse to perfectly aim at the single characters. Mice in big corporations don't even have the accuracy to do this properly, this slows down refactoring speed.

**This behaviour wasn't there a month ago. **

**Comment by isidorn** [comment]
Fixed in insiders
