### ISSUE TITLE
Revisit diagnostics service resolving workspace metadata

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#70563]
We have seen in https://github.com/Microsoft/vscode/pull/70518/files that resolving the workspace metadata can be expensive for large workspaces. I have moved the code into the only placed where it was used (via https://github.com/Microsoft/vscode/commit/a1b5e8dc8a34ba26889274fc9d4f453f7bd11800 to diagnostics service).

The code can still be triggered and we should write it in a way that this expensive crawling does not happen again.

**Comment by bpasero** [comment]
@roblourens actually since you did the change, can you maybe comment if the performance issue can still be hit or is the offending code really gone for good?

**Comment by roblourens** [comment]
The same code runs to collect workspace stats when you open the issue reporter, but it was like that before.

I just took the part of your branch that runs at startup. I assume we still want to collect those stats somehow and we can probably do it in a more perf sensitive way. Depth limit, time limit, defer until awhile after startup, etc?

**Comment by bpasero** [comment]
Ok so then we should revisit this code as it seems to still run in the same bad way when using issue reporter.

**Comment by bpasero** [comment]
I pushed a change that comments out the resolving of launch configurations and left a TODO to revisit this. We would still flood the file system with lots of requests if:
* a user runs `code --status`
* a user files a performance issue

**Comment by RMacfarlane** [comment]
The resolving of launch configurations has been like this for over a year.
Introduction of collecting workspace stats: https://github.com/Microsoft/vscode/commit/df6a4213fbbe172432cdeb4086ac2a44dd6cc768#diff-426e0fe443b2ca7a33c2d8bf95224b64
Reading launch configs:
https://github.com/Microsoft/vscode/commit/ec0250d25435552d89ee6a7d111d658807053621#diff-426e0fe443b2ca7a33c2d8bf95224b64

Originally, `readFileSync` was being used for this, which was causing even more problems, the issue reporter UI was getting blocked when requesting the data: https://github.com/Microsoft/vscode/issues/45163. I rewrote it to be async.

There's a limit of 20000 files that are walked right now, reducing this or limiting the depth of the walk could help.

**Comment by bpasero** [comment]
@RMacfarlane so the only change was to add this to the workspace stats telemetry but otherwise the logic was the same?

**Comment by RMacfarlane** [comment]
Right

**Comment by bpasero** [comment]
@RMacfarlane ok I did not know that. Yeah I feel we can bring this change back once we add a simple limit which should probably be lower than 20000 at least for the launch config lookup 👍

**Comment by RMacfarlane** [comment]
Closing as this doesn't seem relevant anymore, it looks like the `launchConfig` data has been commented back in for some time without issue
