### ISSUE TITLE
Act on multiple file extensions `file.md.hbs`

### ISSUE THREAD

**Issue by FedPete** [Microsoft/vscode#70564]
As a Front-end developer I see and use files with multiple file extensions (it starts to be common usage ... ?). Like `homepage.html.twig` or `mynotes.md.hbs`. Whereby the VCode extensions  processes the content of the file, looking for the last file extension (or getting confused).

Like `mynotes.md.hbs` which content is first interpreted as a Handlebar template. And then as Markdown content processed by site generators. While the document contains mainly text content in Markdown notation, it will not be viewed as such in VCode (ctrl+shift+v).

I can understand that combining multiple VCode extensions, reacting on multiple file extensions, can be difficult. 
It would be nice to say at least, this file with two, three or more extensions, should be handled as if it was a file with a single extension.

Example file `mynotes.md.hbs`;
- Handle it as a Markdown file (.md) (setting it somehow by default?). Maybe `.md.hbs` == `.md`
- Or handle it as a Handlebar template file (.hbs).
- Or (would be nice) apply VCode extensions, first as Handlebar then Markdown (etc., right to left).

**Comment by mjbvz** [comment]
You can use the `files.associations` setting to specify the language mode of files with a given extension (or set of extensions)

Treating a document  as being part of multiple languages is out of scope for core VS Code. We recommend that extension be developed specifically for such mixed mode files, as regular markdown / handlebars extensions may not properly support a combined markdown+handlebars files
