### ISSUE TITLE
Update removes text from unsaved files

### ISSUE THREAD

**Issue by builder7777** [Microsoft/vscode#70562]
Issue Type: <b>Bug</b>

I saw duplicate issue #69972 closed. However it's most definitely not resolved. After upgrading to 1.32.1 and 1.32.2 all unsaved files are empty.
I routinely make notes in VS Code without saving them, it's been working fine up until now.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T01:56:08.693Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv|-psn_0_8308716|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.0.4
insertnumbers|Asu|0.9.1
vscode-django|bat|0.19.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.8.2
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
diff-tool|jin|0.0.1
MagicPython|mag|1.1.0
python|ms-|2019.2.5558
vuejs-extension-pack|mub|1.1.3
autodocstring|njp|0.2.3
vetur|oct|0.16.2
vscode-docker|Pet|0.6.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.2.7
vscode-fileutils|sle|2.13.5
vscode-status-bar-format-toggle|tom|1.5.0
vscodeintellicode|Vis|1.1.4
vscode-icons|vsc|8.3.0
vuetify-vscode|vue|0.2.0
jinja|who|0.0.8
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
So you upgraded from 1.32.1 to 1.32.2 and saw exactly the same issue? Can you try installing the 1.32.3 update to see if it happens again?
