### ISSUE TITLE
vscode does not support http.proxy url with hash symbol

### ISSUE THREAD

**Issue by billboardBR** [Microsoft/vscode#7056]
- VSCode Version: 1.1.1
- OS Version: Windows 7

Steps to Reproduce:

1. Configure your settings for http.proxy, using the following url pattern:
"http.proxy": "http://username:password@hostname:port" with a password containing hash symbol ("#")
2. Try to download an extension (ctrl + p), such as cpp: "ext install cpptools"
3. The following error will be shown: "getaddrinfo ENOTFOUND username username:80"

**Comment by joaomoreno** [comment]
You must url encode your password, since it is a URL. Replace the `#` with `%23`.
