### ISSUE TITLE
cluster.fork() fails since version 1.32.1

### ISSUE THREAD

**Issue by ManfredSteiner** [Microsoft/vscode#70569]
Issue Type: <b>Bug</b>

Launching program which is using  `cluster.fork()` works as desired when started from shell (outside vscode). Launching the same program inside vscode results in starting the main process, but not starting the child processes.

On recent versions of vscode everything works fine (child processes were started and attached).

This is the launch.json configuration:
```
    {  
        "type": "node",
        "request": "launch",
        "name": "Test",
        "program": "${workspaceRoot}/server/src/main.ts",
        "outFiles": [ "${workspaceRoot}/server/dist/*.js" ],
        "autoAttachChildProcesses": true
    }
```

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.15.0-46-generic
Node.js: v8.15.1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2601)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.43GB (2.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
tslint|eg2|1.0.43
vscode-great-icons|emm|2.1.47
vscode-remote-workspace|mkl|0.42.0
cpptools|ms-|0.21.0
markdown-pdf|yza|1.2.0

</details>

**Comment by weinand** [comment]
Please try VS Code >= 1.32.2.

/duplicate #70243
