### ISSUE TITLE
Text typed in one file inserted in another

### ISSUE THREAD

**Issue by ridago** [microsoft/vscode#70576]
Issue Type: <b>Bug</b>

When working with multiple files open I will sometimes notice files I haven't edited show as changed in my git repo. When looking at the changes it seems text I type in one files sometimes get randomly inserted in another open file. One example is I just changed a True to a False in one file and immediatly saw False in the middle of a word in anther file: "current_step_ruFalsenning". Sometimes the same word is inserted multiple places using multiple cursors. When pressing ctrl+z my curser is now at all the places the text was inserted. I disabled extensions using code --disable-extensions, to see if it was an extensions problem, but that didn't make a difference. I am unable to figure out how to reproduce this. It seems to just randomly happen every now and then.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (24.29GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by rebornix** [comment]
@ridago I'm wondering if you have auto save turned on or anything similar ? Do you see the issue in all languages?

**Comment by ridago** [comment]
This had been a while, haven't used VSCode on that OS recently, but I don't
think I had autosave on and I think I was only using Python at the time.
