### ISSUE TITLE
process#findExecutable() should not use sync fs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#70577]
Looks like [`win32.findExecutable`](https://github.com/Microsoft/vscode/blob/8f16a02e663da99642bed8f274308f382983d446/src/vs/base/node/processes.ts#L407) is being used from the renderer and has 3 occurrences of `fs.existsSync()` that should use the async variant instead. It should be possible to just return a promise from this method.

Feel free to move forward if you are not the owner of this method, I just went by git history.

**Comment by bpasero** [comment]
@dbaeumer looks like I filed this in 2017 already (https://github.com/Microsoft/vscode/issues/34425). Is there a technical problem resolving this?

**Comment by dbaeumer** [comment]
No technincal problem. I even think that this has no super high priority right now since the whole code needs to move out of the renderer anyways. This is independent of whether it is sync or async.

**Comment by bpasero** [comment]
@dbaeumer oh ok, if it moves out of the renderer into the extension host than its less critical. Though I still think sync API should not be used if possible (I know we are not very good in other processes besides the renderer).
