### ISSUE TITLE
ts(TS1234)

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#70572]
I see ts twice in the error codes, did the ts server start sending them in a different format?

![image](https://user-images.githubusercontent.com/323878/54440913-d754bf80-46f8-11e9-9e25-dc9d2bbd8d89.png)

**Comment by mjbvz** [comment]
The second set look like they come from the strict null check task. Will investgate if anything change

**Comment by mjbvz** [comment]
Not a regression but we now display errors differently so this is more noticeable. Will fix

**Comment by roblourens** [comment]
Oh you're right that it's from the strict null task.
