### ISSUE TITLE
PHP ternary and static members breaks syntax highlight

### ISSUE THREAD

**Issue by Ralle** [microsoft/vscode#70571]
- VSCode Version: 1.32.1
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Put in this PHP code: `$extraData['removeRequested'] = in_array('remove', $splitStat) ? \XF::$time : 0;`

The colons are highlighted wrong:
![Screen Shot 2019-03-15 at 15 49 49](https://user-images.githubusercontent.com/467309/54439893-faec2a00-4739-11e9-9f61-5edd13e1a73a.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
https://github.com/atom/language-php/issues/356

**Comment by Ralle** [comment]
Oh man, I thought I was a good boy doing my searching thoroughly before reporting and then it turns out that I would have to search on Atom too, oh well :).

**Comment by rzhao271** [comment]
Closing this for housekeeping. @Ralle feel free to reply if this issue still occurs for you after upgrading to the latest VS Code.
