### ISSUE TITLE
Can irrelevant extensions be automatically disabled?

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#70573]
是否能自动禁用不相关的扩展？
假如我的工作环境是java  可以自动禁用php,python,javascript等不相关的扩展？
我的工作环境是php，就自动禁用掉python,java,javascript等不相关的扩展？
在启动vscode的时候就自动禁用，防止多余的cpu和内存被占用
-------------------------------------------------------------------------------------------
Can irrelevant extensions be automatically disabled?

What if my working environment is that Java can automatically disable unrelated extensions like php, python, javascript, etc?

My working environment is php, which automatically disables irrelevant extensions like python, java, javascript, etc.

Disabled automatically when vscode is started to prevent unnecessary CPU and memory from being occupied

**Comment by lifetin** [comment]
这个问题被关闭了，因为我的问题得不到解决， 我觉得这是个很重要的功能。
-----------------------------------------------------------------------------------
The problem was closed because my problem could not be solved. I think it is a very important function.

https://github.com/Microsoft/vscode/issues/69742

**Comment by roblourens** [comment]
Extensions are responsible for activating themselves when certain conditions are met. If an extension is activating itself and doing work at the wrong time, you can file an issue on that extension. You can also deactivate the extension per workspace.
