### ISSUE TITLE
ssh to Vagrant VM on integrated terminal crashes windows

### ISSUE THREAD

**Issue by codigo47** [Microsoft/vscode#70574]
- VSCode Version: 1.32.3
- OS Version: Windows 10 Pro 1803

Steps to Reproduce:

1. Create a Vagrant VM
2. On the VS Code terminal open Bash WLS 
* $ bash
3. SSH to the Vagrant VM 
* $ shh [VM IP]
4. Windows crash

**Comment by roblourens** [comment]
Can you explain more about what you see when the "windows crash" happens?

**Comment by codigo47** [comment]
A blue screen, saying "you must restart your PC" (not the exact words), everything frezed, sound crashed, no other exit than restarting

**Comment by codigo47** [comment]
Nevermind @roblourens , It's happening on all my terminals! :(
