### ISSUE TITLE
'user' is declared but its value is never read.ts(6133)

### ISSUE THREAD

**Issue by marcosa20** [Microsoft/vscode#70582]
Issue Type: <b>Bug</b>

```
function name ( ) {
     let user = 0
     
     for ( i in arguments ) {
        user += arguments[i]
    }
}
```

Language = JavaScript

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:01:00.888Z)
OS version: Windows_NT ia32 6.3.9600

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.7
vscode-heroku|iva|1.2.6
debugger-for-chrome|msj|4.11.3
heroku-command|pko|0.0.8

</details>

**Comment by mjbvz** [comment]
The error is correct: you are not doing anything with `user`, just incrementing the value. Its value is never used (read) and this is often a programming mistake
