### ISSUE TITLE
Mac Code Helper hight CPU - Insiders version

### ISSUE THREAD

**Issue by asnow003** [Microsoft/vscode#70587]
Issue Type: <b>Performance Issue</b>

Open VS Code
Use it for a little bit.
Code complete stops working and starts killing my computer CPU.

Issue occurs after briefly using the editor...then the code help stops working and my CPU is pegged and my computer fans start running on high.

VS Code version: Code - Insiders 1.33.0-insider (5a88160c7dc5db820a564e3872e0de087ff3563d, 2019-03-15T15:48:56.158Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|32.00GB (12.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   131	 59043	code-insiders main
    6	    66	 59044	   gpu-process
    0	    98	 59217	   shared-process
    4	   295	 59318	   window (authenticationService.ts — Teamspace-Web)
    0	   131	 59319	     extensionHost
    0	    33	 59338	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=59319
  236	  1442	 59445	       electron_node tsserver.js 
    0	    66	 59446	         electron_node typingsInstaller.js typesMap.js 
    0	    66	 59320	     watcherService
    0	    66	 59455	   window (Issue Reporter)
    0	     0	 59458	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (authenticationService.ts — Teamspace-Web)
|    Folder (Teamspace-Web): more than 29314 files
|      File types: ts(9790) js(5224) html(4437) map(4392) json(984) png(903)
|                  svg(628) scss(585) dll(468) cs(203)
|      Conf files: package.json(49) tsconfig.json(15) csproj(7) sln(6)
|                  gulp.js(4) webpack.config.js(3) tslint.json(3)
|                  launch.json(2) grunt.js(2) tasks.json(1)
|                  settings.json(1)
|      Launch Configs: node(14) chrome;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0

</details>

**Comment by asnow003** [comment]
Added this one also so you have the debug information for both versions of VS Code...feel free to close this one as a dup.

**Comment by roblourens** [comment]
tsserver @mjbvz

**Comment by mjbvz** [comment]
When this issue occurs, Can you please share the output of running `code-insiders --status` from the command line. It includes additional system / project info that may be helpful

**Comment by ghs** [comment]
Same happens here since the lates release, but using the normal version.

In my case, if I quit vscode, the process of code helper is never ended and starting vscode again will create another process and after some time the new one will also touch the sky.

**Comment by mjbvz** [comment]
@ghs Please open a new issue for your problem

**Comment by philiiiiiipp** [comment]
Are you by any chance doing some transpiling in the background? I am seing a similar thing when building my code. I am wondering if there is a way to tell vscode to ignore certain paths ?

I tried using the jsconfig.json

```
{
  "exclude": ["src/*/.serverless"], <-  Ignore all .serverless folders
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["src/*"]
    }
  }
}
```
But it seems to still go wild while doing transpilation in the background.

**Comment by mjbvz** [comment]
Closing as more info needed from original poster
