### ISSUE TITLE
Variable substitution from settings to tasks results in variable name, not value

### ISSUE THREAD

**Issue by willanderson1** [Microsoft/vscode#70581]
- VSCode Version: 1.33.0
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Create a task that is dependent on a config variable
2. Have that config variable point to an input selector
3. Value passed to task is the input selector variable name, not the value selected from the picker. 

Example:
In local settings.json:
`  "DefaultDeployTarget": "${input:targetSelector}",`
In Tasks:
```
        {
            "label": "Deploy: to target machine",
            "type": "shell",
            "command": "xcopy",
            "args": [
                "${workspaceFolder}",
                "\\\\${config:DefaultDeployTarget}\\D$\\your\\path\\here",
                "/S",
                "/Y",
                "/I",
                "/D",
                "/EXCLUDE:.vscode\\exclusions.txt"
            ],
            "presentation": {
                "panel": "shared",
                "focus": true,
                "echo": true,
                "reveal": "always"
            },
            "problemMatcher": [],
            "options": {
                "shell": {
                    "executable": "cmd.exe",
                    "args": [
                        "/d",
                        "/c"
                    ]
                }
            }
        }
    ],
    "inputs": [
        {
            "id": "targetSelector",
            "description": "Select Target name",
            "type": "pickString",
            "options": [
                "target1",
                "target2",,
            ]
        },
```
The behavior works as intended, the selection is prompted. After choosing the target, the task fires, but the string contains "${input:targetSelector}" instead of "target1". 

You can fake it into working with order of operations by first having the task run with the input selector directly, then add the user config to settings, then update the reference to that config setting in the tasks, and it will work as intended. 

Restarting vscode breaks it. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
input variable types are only supported in launch.json and tasks.json.

**Comment by willanderson1** [comment]
We wanted to provide a generic task and allow users to swap in which input list was appropriate for their environment based on their local settings. We got the intended behavior that we wanted, with the config parameter triggering the appropriate input selector and actually passing it through to the task, but only if we'd first run the task with the input selector first before updating the task to point at the config parameter.

That seems to suggest it could be made to work that way reliably. That being said, do you have a recommendation for how we should pursue the above use case?

**Comment by alexr00** [comment]
I think you're hitting the limits of what tasks can do. If you need to have decision logic based on a setting, you're better off writing a VS Code extension.
