### ISSUE TITLE
Linux repo hash sum mismatch (Mar 2019)

### ISSUE THREAD

**Issue by cossio** [microsoft/vscode#70584]
It seems this issue keeps coming up. There are several issues with a similar title but they are closed and I can't comment. Hence I'm creating a new one.

I am located in Havana, Cuba.

@RMacfarlane @TheTeraByte

To reproduce, run `sudo apt update` in the terminal. I get:

```
Get:23 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [103 kB]                        
Err:23 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages        
  Hash Sum mismatch
```

I am using Linux Mint 18.
vscode version Version: 1.32.1

Similar (older) issues:

https://github.com/Microsoft/vscode/issues/66339
https://github.com/Microsoft/vscode/issues/66238
...
There are more.

**Comment by RMacfarlane** [comment]
Thanks @cossio, I've contacted the linux repo admin team

**Comment by cossio** [comment]
It looks like this has been fixed because I was able to update today. But it seems like this is a recurrent issue. Hopefully the underlying problem is identified and solved once for all. :)

**Comment by jean** [comment]
I'm currently getting 

> Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2 Hash Sum mismatch
> Some index files failed to download. They have been ignored, or old ones used instead.
