### ISSUE TITLE
EPERM: operation not permitted, open: every time when restarting building project with webpack

### ISSUE THREAD

**Issue by budarin** [Microsoft/vscode#70585]
- VSCode Version: 1.32.3
- OS Version: Windows Server 2008 R2

Steps to Reproduce:

1. Start build any project with webpack which has rimraf at start
2. Stop the process 
3. Try to start it again ->  fail with the error

Does this issue occur when all extensions are disabled?: Yes

Appreared some updates ago

**Comment by roblourens** [comment]
Are you using tasks for this? Not clear exactly what you are stopping/starting.

**Comment by budarin** [comment]
What do you mean by tasks? npm script commands?
I use to nsp script commands to start build process and stop it Ctrl+C in terminal window

**Comment by roblourens** [comment]
I mean the vscode feature. But it sounds like you are just running a command in the terminal. In that case this doesn't sound like a vscode issue, there is just some issue with your build. Maybe it's trying to delete a file that's open somewhere.

**Comment by budarin** [comment]
I run commands from npm scripts panel

**Comment by roblourens** [comment]
Does it work if you just use the terminal?

**Comment by budarin** [comment]
the result is the same

![изображение](https://user-images.githubusercontent.com/8055157/54491737-cad78f00-48d1-11e9-9410-b22e1a7cf123.png)

"clean-dist": "rimraf ./dist"

**Comment by roblourens** [comment]
It sounds like this is just an issue with your build script. If you can come up with clear steps that show that there is a vscode issue, we can investigate.

**Comment by budarin** [comment]
it's not only my problem with my script - a lot people on VSCode suffer from this error
Have a look at a list of issues with the eeror!

**Comment by alexr00** [comment]
This isn't an issue with tasks, but it does appear to be an issue on Windows where VS Code is hanging onto a file that the script is trying to unlink. 

@isidorn and @joaomoreno for explorer and tree. 
This is reproducible with an npm install, a git clean -xfd, and then an other npm install ***while the folder is open in VS Code***. You'll notice that afer the git clean the node-modules folder is still there. Somthing in VS Code is keeping a file around. This only happens on Windows.

**Comment by budarin** [comment]
also have to notice that the same webpack script never fails on MacOS in VSCode

**Comment by alexr00** [comment]
Something in VS Code on Windows is hanging onto the `node_modules\@types folder`.

**Comment by isidorn** [comment]
Nope. Explorer does not do things like that
@budarin can you reproduce if you close the sidebar and never open the explorer?

**Comment by alexr00** [comment]
It's typescript. This is the process hanging onto the directory:
"C:\Users\alros\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\alros\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\alros\AppData\Local\Temp\vscode-typescript\tscancellation-2ae8985cc153ff8002a1.tmp* --globalPlugins typescript-tslint-plugin --pluginProbeLocations C:\Users\alros\.vscode-insiders\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0 --locale en --noGetErrOnBackgroundUpdat

**Comment by isidorn** [comment]
@alexr00 thanks for looking into it!

**Comment by mjbvz** [comment]
Thank you for the investigation. I believe this is already being tracked upstream by https://github.com/Microsoft/TypeScript/issues/29407

I've marked this issue as a priority to be fixed upstream
