### ISSUE TITLE
Better file navigation / history

### ISSUE THREAD

**Issue by lateshift** [microsoft/vscode#70588]
Something like 🤫 Webstorm/Idea/Android Studio:

Pressing and **holding** CMD+e (afaik it's CTRL-e on Win) opens a "Fileswitcher" (it has more features but imho File editing history/navigation is to cumbersome in vscode) overlay (window center):

<img width="447" alt="Screenshot 2019-03-15 at 19 54 12" src="https://user-images.githubusercontent.com/179465/54455558-6d6e0180-475c-11e9-900d-9682c7271025.png">

Just Pressing CMD+e  (afaik it's CTRL-e on Win) **once** switches back to the last opened file (+ cursor position).

I guess it's not really possible (yet) to display overlay "dialogs"? An implementation shouldn't be to complicated 😌

Cheers,
Jens

**Comment by roblourens** [comment]
How is this different from cmd+p? Please say more about exactly what you want from this menu.

**Comment by lateshift** [comment]
Sorry for the late reply but work got in the way 

Basically it behaves like the windows task switcher for files (file editing history),  holding shift + cursor up/down allow for re-opening multiple files. It's hard to explain but imho it's a really fast way to switch multiple files. I often have to switch between multiple related files for small editing/lookup tasks and it feels much faster then anything vscode currently have to offer.

cmd+p behaves more like pressing the "shift"-keys 2 times repeatedly in the Jetbrains IDE's:

![image](https://user-images.githubusercontent.com/179465/54671497-5893c400-4af6-11e9-8f94-4179ca3d7a9e.png)

For more details I guess it's the best to just download a 30-Day trial from:

https://www.jetbrains.com/webstorm/download/#section=mac 

(There is no signup etc.)

<SNiP>

Is there a currently a way (api) to display window centered overlays? 

Thanks & best regards
Jens
