### ISSUE TITLE
Overflow action is not a good indicator for a stack

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7059]
After talking to @alexandrudima we came to the conclusion that the single overflow dropdown action is a weak indicator for the stacks model. It blends too easily into the other editor actions and so you think it actually is an action that does something on the opened editor. 

We had some ideas to improve this:
* put this control into a designated area (different background color) to make clear it operates on the entire stack
* draw stronger affordance that you have multiple documents stacked on top of each other

For example in the image below we are representing a stack but we are not doing this with tabs but with a different piece of UI. Maybe we can do the same when you have tabs disabled and integrate the overflow affordance into there as well?

![image](https://cloud.githubusercontent.com/assets/900690/15675811/f343fc92-2743-11e6-99b7-073fa1940a1a.png)

//cc @alexandrudima

**Comment by bpasero** [comment]
Now that I see the image I pasted I actually think this is a much better icon to use if we keep an icon!

**Comment by stevencl** [comment]
We discussed at the UX meeting today and agreed that we would refine the button layout like so:

![image](https://cloud.githubusercontent.com/assets/1704059/15719955/30eed364-282a-11e6-8cfd-1384b3ce40ad.png)

Note the different overflow icon. Brad will work with the icon team in Redmond to get a new icon similar to this.

Assigning to Brad so that he can get the icon.

**Comment by bgashler1** [comment]
See the refinement here
https://github.com/Microsoft/vscode/issues/7058#issuecomment-223175779

**Comment by bgashler1** [comment]
@bpasero here are the icons (I modified existing icons to fit our current icon style and this particular need).
[stackView icons.zip](https://github.com/Microsoft/vscode/files/294711/stackView.icons.zip)

**Comment by bpasero** [comment]
Thanks.
