### ISSUE TITLE
Go to Files (ctrl+p) does not show files in the .gitignore though I would like it to

### ISSUE THREAD

**Issue by EmbeddedBacon** [Microsoft/vscode#70595]
Currently, as stated by the documentation for the Find in Files:

`Also note the Use Exclude Settings and Ignore Files toggle button in the files to exclude box. The toggle determines whether to exclude files that are ignored by your .gitignore files and/or matched by your files.exclude and search.exclude settings.`

There is a button to disable this setting during Find in Files task.  Though, in the Go to Files box , displayed when pressing CTRL+P, will exclude files that are found in the .gitignore file.  For configuring which files goes into the repository these settings are appropriate, but there are many times I would like to search for .map and .lst file (to name a couple), but I can't since they are part of the .gitignore.   As a work around, I need to manually edit the .gitignore file during development and try to remember to re-enable them prior to configuring the files to to the repository.

I would request a way for Go to Files to ignore these settings just like Find in Files is able to do.

**Comment by roblourens** [comment]
There is an issue for a similar toggle button for quickopen: https://github.com/Microsoft/vscode/issues/59982
