### ISSUE TITLE
New Directory/File Is In Incorrect Root After Cancel New Directory/File

### ISSUE THREAD

**Issue by ecnepsnai** [Microsoft/vscode#70598]
Apologies for the confusing title, it's hard to describe this. Easier to just watch the GIF.

- VSCode Version: 1.32.3
- OS Version: macOS 10.14.3, Windows 10 Pro 1809. Does not appear to be OS specific.

Steps to Reproduce:

![Mar-15-2019 18-10-04](https://user-images.githubusercontent.com/1607109/54468858-3e509380-474e-11e9-9d90-64d9045a3d6a.gif)

Assuming you have a project directory like:

```
my-project/
- subdir/
```

1. Open the `my-project` in code
2. Select `subdir` and click on *either* New Directory or New File in the sidebar menu
3. Oops, you clicked the wrong one, press escape to cancel out what you were doing and try again
4. The Directory/File is now being created in the root `my-project`, even though you still have `subdir` selected

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70069
