### ISSUE TITLE
VSCode should do like any decent editor, and provide a drop-down from all search text boxes

### ISSUE THREAD

**Issue by TheJCAB** [Microsoft/vscode#70591]
Issue Type: <b>Feature Request</b>

Decent editors provide a drop-down list of older search phrases in their search (and replace!) text entry UI elements.

But VSCode doesn't seem to do this, for some reason.

It's only polite to remember such things for the comfy user, you know :)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.18348

**Comment by roblourens** [comment]
#23099
