### ISSUE TITLE
Provide better error: specify modified extension

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#70592]
Issue Type: <b>Feature Request</b>

This error is popping up too often: 
> Extensions have been modified on disk. Please reload the window.

But I have ~100 extensions and want to know which one is modified to find out the cause.

VS Code version: Code - Insiders 1.33.0-insider (5a88160c7dc5db820a564e3872e0de087ff3563d, 2019-03-15T15:54:09.237Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment]
@usernamehw do you have reproducible steps? This should not happen. It means something is changing the contents of `package.json` on disk and the cache we build is invalidated because of these changes.

**Comment by usernamehw** [comment]
I do not have the steps because there's no indication which extension is doing it.

Can't even reproduce it now.
