### ISSUE TITLE
Support PHP debug

### ISSUE THREAD

**Issue by su-xiaolin** [Microsoft/vscode#706]

**Comment by ducke** [comment]
https://visualstudio.uservoice.com/forums/293070-visual-studio-code

**Comment by herbertpimentel** [comment]
+1

**Comment by jrieken** [comment]
Everyone is invited to write an extension for that.

**Comment by egamma** [comment]
Here is the documentation for how to do integrate a debugger into VS Code: 
- https://code.visualstudio.com/docs/extensions/example-debuggers
- https://code.visualstudio.com/docs/extensionAPI/api-debugging

XDebug would be one option: http://xdebug.org/

**Comment by herbertpimentel** [comment]
a lot of people want it see https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752606-php-intellisense

**Comment by bubifengyun** [comment]
good idea！

**Comment by felixfbecker** [comment]
I _would_ write one, but the documentation isn't really helpful as it basically says "download the example project". A step-by-step tutorial would be helpful.

**Comment by felixfbecker** [comment]
Found https://github.com/cmpaul/vscode-php-debug

**Comment by weinand** [comment]
@felixfbecker https://code.visualstudio.com/docs/extensions/example-debuggers is meant to be a "a step-by-step tutorial". Please let me what you are missing from the tutorial or what is difficult to understand. I'd be glad to help.

**Comment by felixfbecker** [comment]
@weinand There is a good documentation about the VS Code debugger protocol and a tutorial about how to get the mock debugger up and running. But the mock debugger itself (the classes in the common folder) are, besides inline comments, not documented at all. There's just all these methods that somehow get called and it's not clear to me when and what parameters are important.

I'm (and I think many others are) interested in Java and PHP debugging support. Thank you for your offer to help, maybe we can talk on the VS Code Gitter? https://gitter.im/Microsoft/vscode

**Comment by weinand** [comment]
@felixfbecker thanks for the feedback. I'll try to improve the class documentation next week. The classes in common are actually not that important because they are just an implementation detail of the server side framework. Debug adapter implementers are just expected to implement the 'xxxxRequest' methods of their subclass of DebugSession. I think it will help if I copy the high level documentation from https://code.visualstudio.com/docs/extensionAPI/api-debugging into the individual methods of the mock debugger and the DebugSession class.

**Comment by felixfbecker** [comment]
I have an extension that is 80% finished: https://www.github.com/felixfbecker/vscode-php-debug

**Comment by felixfbecker** [comment]
Here it is: https://marketplace.visualstudio.com/items/felixfbecker.php-debug :)

**Comment by weinand** [comment]
@felixfbecker Awesome - php-debug looks great!

**Comment by bubifengyun** [comment]
work  not well. maybe I need test it in yii2

**Comment by felixfbecker** [comment]
@bubifengyun If the debug adapter is not working please open an issue at my repository.

**Comment by bubifengyun** [comment]
@felixfbecker OK, thanks for your great work. I will debug yii2 using vscode-phpdebug

**Comment by felixfbecker** [comment]
I feel that my extension is actually a pretty solid solution and as it is probably not planned to move this feature into core, maybe this issue should be closed?

**Comment by egamma** [comment]
Agreed with @felixfbecker this is well covered by the extension - closing
