### ISSUE TITLE
Keep editor actions and stack related actions separate

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7060]
After talking to @alexandrudima we think we cannot mix editor targeting actions and stack related actions (e.g. overflow dropdown) at the same location because they target different things.

If you look at typical editors that show tabs, all actions that target the editor are in the context menu of the tab. And all actions that target the entire stack are outside of the tabs to the far right. We should look at a similar model to be consistent and move the overflow action outside of the editor actions and outside of any tab.

However, putting all editor actions into the context menu is also odd because some are very useful. Interestingly Eclipse is one example where they decided to just draw a toolbar within the editor:

![image](https://cloud.githubusercontent.com/assets/900690/15675947/98112100-2744-11e6-8686-180c8d7fac99.png)

This takes away a lot of space, so we thought about something different:

* tabs enabled: move editor actions to the right of the tab. show them only on mouse over and take away space from the label. this ensures we are not growing the tabs too much. we can still have a "..." in there to bring up the context menu
* tabs disabled: in this case we only have 1 tab that just spans the entire title area so the model would work here as well. one difference could be that we show the actions always and not just on hover. still, with nice separation the user would understand that some actions only target the editor and the other (e.g. overflow) targets the stack

//cc @alexandrudima

**Comment by stevencl** [comment]
We discussed at the UX meeting today and agreed that we would refine the button layout like so:

![image](https://cloud.githubusercontent.com/assets/1704059/15719955/30eed364-282a-11e6-8cfd-1384b3ce40ad.png)

Brad will tidy up the mockups I created and copy them up to the deck with our visual designs.

**Comment by bgashler1** [comment]
See the refinement here
https://github.com/Microsoft/vscode/issues/7058#issuecomment-223175779
