### ISSUE TITLE
VS Code never sends our C/C++ extension a cancelRequest for textDocument/definition

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#70602]
- VSCode Version:1.32.3 (also repros with the latest Insiders)
- OS Version:Windows

Steps to Reproduce:

1. Use our C/C++ extension Go to Definition feature with some file that takes a long time to complete, such as the big sqlite3.c file.
2. Do some action that you would expect to cause a cancelRequest to be sent for the previous definition request, such as a 2nd Go to Def.

Bug: cancelRequest is never sent for the textDocument/definition message. I see some cancelRequests sent for different IDs -- in particular, I see a cancelRequest with an ID that is 1 greater than the definition request ID at around the same time I would expect the "definition" cancel request, so maybe this is just an off by one error (or the ID is some event we don't currently recognize). I assume no other extensions have reported this bug yet because they're all too fast returning a definition.

None of our shipping C/C++ extensions try to react to the cancelRequest yet (i.e. only my internal branch does), see https://github.com/Microsoft/vscode-cpptools/issues/1174 .

UPDATE: 0.22.0 that we plan to ship March 19th has the ability to react to a Go to Definition cancel request if we ever receive one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
The operation is now cancelled when the document, document content, or selection/position changes
