### ISSUE TITLE
VS Code caches and suggests Bootstrap classes when i have Semantic UI in the workspace and no Bootstrap file

### ISSUE THREAD

**Issue by yourAverageDeveloper** [Microsoft/vscode#70603]
- VSCode Version: 1.32.3
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Click on the thunderbolt icon in the bottom left and let VS Code cache all the CSS classes that are in the workspace
2. Once cached, try writing some markup and give an HTML element some classes. Only Bootstrap classes would be suggested even when there's no Bootstrap file in my workspace and i have Semantic UI files in my workspace

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It sounds like this is coming from an extension because I'm not sure what thunderbolt icon you're talking about. Please file this issue on the extension that provides this feature.
