### ISSUE TITLE
Test new comment api

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#70601]
Refs: #68020

- [x] any @joaomoreno  
- [x] any @sbatten 

Authors: @rebornix, @RMacfarlane 

Complexity: 4

GH PR extension has been using the proposed commenting api for more than half a year. Based on the lessons we learnt from dog fooding in GH PR, we refactored the api to be more SCM like and it's pretty close to what we imagine a generic but powerful enough commenting api should look like. If you are interested in the problems we ran into and our design decisions, please read https://github.com/Microsoft/vscode/issues/68020.

Right now the new commenting api and the legacy one are both in `vscode.propsed.d.ts` as we don't want to break any other extension using the legacy api immediately. So to get familiar with the API

1. Read [Microsoft/vscode-extension-samples/blob/rebornix/.../vscode.proposed.d.ts](https://github.com/Microsoft/vscode-extension-samples/blob/rebornix/commentcontroller/comment-sample/src/typings/vscode.proposed.d.ts). The api names should be self explanatory and jsdocs can help also.
2. Play with sample https://github.com/Microsoft/vscode-extension-samples/tree/rebornix/commentcontroller/comment-sample

You don't need to create a comment controller as complex as GH PR but please at least test

* Comment thread creation/disposal
* Comments update
* Customize actions on Comment Widget by `Comment.acceptInputCommand` and `Comment.additionalCommands`

Please provide feedback on the api, sample and docs/comments.

**Comment by sbatten** [comment]
I wanted to add a `Delete Thread` button, but the only way I could do that was by adding it to additional commands which requires the user to hit `Reply...` first. I think that's a little weird.
