### ISSUE TITLE
Filter box in Outline has dissapeared in Release 1.32.3

### ISSUE THREAD

**Issue by fmartelg** [Microsoft/vscode#70605]
The filter box in the Outline Pane in the Side Bar has disappeared in the latest release.

Disabled all extensions.  Still no filter box.

Windows 10 Home

**Comment by MikeMcl** [comment]
See also #70095 and #70646.

Please restore the filter box and improve the folding in the outline view. For example, by providing an option not to show every symbol in the file, but just the functions.
