### ISSUE TITLE
Integrated Terminal error display!

### ISSUE THREAD

**Issue by leitwolf** [Microsoft/vscode#70606]
VS Code version: Code 1.32.3  (zip type)
OS version: Windows_NT x64 10.0.17763
![TIM图片20190316151353](https://user-images.githubusercontent.com/1720546/54472296-1ff7a000-4801-11e9-9b5c-ea3942feca80.png)
![TIM图片20190316151421](https://user-images.githubusercontent.com/1720546/54472297-24bc5400-4801-11e9-9022-30c6b299aafb.png)

**Comment by leitwolf** [comment]
"terminal.integrated.windowsEnableConpty": false or true
does not work!

**Comment by usernamehw** [comment]
> ConPTY support got pushed back to 18309+ as opt in with v1.31 due to stability concerns.

**Comment by usernamehw** [comment]
`17763` < `18309`
