### ISSUE TITLE
Goto symbol does not work when invoked early on file

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#70607]
This issue returned #58089.

**Comment by bpasero** [comment]
I just tried this: open vscode.d.ts and quickly type to go to symbol but that works.

**Comment by usernamehw** [comment]
@bpasero can you try to reload the editor first?

**Comment by bpasero** [comment]
@usernamehw I reload VSCode on having vscode.d.ts opened and type "open", then wait. It reveals something for me. Anything else you do?

**Comment by usernamehw** [comment]
Nope.

![demo](https://user-images.githubusercontent.com/9638156/54487631-4cff8d80-48a9-11e9-8242-bbe0d9314798.gif)

**Comment by bpasero** [comment]
Since I have not changed anything in the picker for a while, I assume a recent change in the language service. Moving to @mjbvz

**Comment by mjbvz** [comment]
I suspect this is not a regression and is not typescript specific.  In this example, the go to symbol view is opened before we've registered any document symbol provider.

The fix would be to retrigger symbol search when the document symbol provider registry changes. @jrieken Do you own `go to symbol`? I'm not very familiar with the code

**Comment by jrieken** [comment]
@bpasero Your code isn't listening on `DocumentSymbolProviderRegistry.onDidChange`. That event is emitted when an extension registers a provider and then search must restart (or abort).

**Comment by bpasero** [comment]
Yeah, quick open never had support for updating results after the results are in. You have to restart the typing or close/open.

@jrieken is there any promise I can join on to make this work? Similar to the commands palette that waits a bit for the extension host to startup.

I would assume that "Open Symbol in Workspace" possibly suffers from the same issue.

**Comment by jrieken** [comment]
> @jrieken is there any promise I can join on to make this work? Similar to the commands palette that waits a bit for the extension host to startup.

No promise, but the event because we don't know when providers will be registered. Internally, simply retriever when the event happens. E.g this is how IntelliSense does it: https://github.com/Microsoft/vscode/blob/97cc9b15ba557b226f237483b7ebff67ae5b74c9/src/vs/editor/contrib/suggest/suggestModel.ts#L133-L136

**Comment by bpasero** [comment]
This is actually more:
* if you bring up goto symbol right on startup, the editor does not even have a model and we fail to run
* if you bring up goto symbol on the editor before the mode is set, we miss out on the language registering a provider

I do not have an immediate fix, the workaround is to continue typing and the results kick in. I will revisit this when quick open moved to the picker infrastructure which I think supports changing results after the fact.

**Comment by bpasero** [comment]
The new quick access for symbols will now wait for the registry to be loaded and then populate the results. This is not yet enabled for quick open but I plan to do so until we release.
