### ISSUE TITLE
Changelog for .deb releases

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/vscode#70608]
Please add [your changelog](https://code.visualstudio.com/updates/) as [deb-changelog](https://manpages.debian.org/testing/dpkg-dev/deb-changelog.5.en.html).

Currently the Changelog is empty, even though you keep a changelog on your website.
Especially with patch releases and because I'm on a mobile network, it would be very nice to see the changelog so I can decide if I need the fixes before downloading vscode.

![vscode changelog on linux mint](https://user-images.githubusercontent.com/43763/54472967-b2804b00-47d1-11e9-9238-90b50afeac6e.png)
_Screenshot from linux mint update manager._

**Comment by Tyriar** [comment]
We have no plans to add this, the source of truth for the changelog is the website.
