### ISSUE TITLE
Missing option to hide git sync button in the status bar

### ISSUE THREAD

**Issue by joshleeb** [microsoft/vscode#70604]
There doesn't appear to be an option to hide the git sync icon that appears in the status bar. 

It's not really a big deal but it would be nice to hide the git sync icon. Personally, coming from Vim I prefer working with the VCS outside of the editor, yet I would still like to see the current branch that is being worked on. This is why I'd like to hide just the sync button and not hide both git status bar items or disable the git extension entirely.

**Comment by misolori** [comment]
I believe this is resolved via #3874

**Comment by bpasero** [comment]
No, hard to revert that change.
