### ISSUE TITLE
Open links of vscode marketplace inside vscode

### ISSUE THREAD

**Issue by Millon15** [Microsoft/vscode#70617]
Imagine how it would be nice, if hit to the link of provided format:
https://marketplace.visualstudio.com/items?itemName=espresso3389.vcterminal
redirects us directly to the page of the extension in our favorite code editor.

**Comment by roblourens** [comment]
That's interesting, but I don't think vscode should take over all marketplace links. A few reasons

- The marketplace has extensions for VS and Azure, not just vscode
- The marketplace web ui has some extra features
- Some people will be very annoyed
