### ISSUE TITLE
--vscode-editor-font-family css var in webview is incorrect

### ISSUE THREAD

**Issue by Almenon** [Microsoft/vscode#70619]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. open a webview extension. For example, [AREPL](https://github.com/Almenon/AREPL-vscode) or run command "Markdown: open preview to side"
2. Open webview dev tools
3. look at css vars
4. --vscode-editor-font-family is incorrect. It should match editor.fontfamily value (set to `Consolas, 'Courier New', monospace` by default on windows) but instead it is `"Segoe WPC", "Segoe UI", sans-serif;`

Does this issue occur when all extensions are disabled?: N/A

Impact: Minor. Text does not line up properly in AREPL. User is unable to change font in webview to their desired font.

**Comment by Almenon** [comment]
--vscode-editor-font-size and --vscode-editor-font-weight are also different than their defaults (14 and normal). There may be other bad css values.

**Comment by PEZ** [comment]
I'm having this problem on MacOS as well.
