### ISSUE TITLE
comment not working 

### ISSUE THREAD

**Issue by nikki9024** [Microsoft/vscode#70610]
Issue Type: <b>Bug</b>

when i save a file using .php extension then it does not support commenting option in the editor as 
like 

single line comment {//}
and multi line comment {/*----*/}

regards

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|1.90GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.7.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
crane|Hvy|0.3.8
python|ms-|2019.2.5558
LiveServer|rit|5.5.1
code-spell-checker|str|1.6.10
python|tht|0.2.3
vscode-icons|vsc|8.3.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This should work with `ctrl+/`, how are you trying to do it?
