### ISSUE TITLE
AltGr not working in integrated terminal (french keyboard)

### ISSUE THREAD

**Issue by andresiraola** [Microsoft/vscode#7061]
- VSCode Version: 1.2.0-insider (https://github.com/Microsoft/vscode/commit/7ccb21d7)
- OS Version: Windows 10 14342

When I try to write the backward slash ("\") in the integrated terminal using a french keyboard (AltGr-8), I get "8" instead of "\". However, Ctrl-Alt-8 works.

This also happens for all AltGr combinations.

**Comment by Tyriar** [comment]
I believe this will be solved with the same fix as https://github.com/Microsoft/vscode/issues/7045

**Comment by andresiraola** [comment]
Yes, it works!

**Comment by Tyriar** [comment]
@andresiraola good to hear, I haven't actually done the fix yet. I was testing this last night and could not reproduce even on older versions so I'm not sure what is going on. AltGr seemed to function just fine :confused:

**Comment by Tyriar** [comment]
I was testing on Ubuntu so I was thinking maybe it's Windows only, now I'm kinda confused.

**Comment by andresiraola** [comment]
It's been fixed in the insider build for some time now.  I only tested it on Windows. 

When the may release came out, it wasn't working and I opened this issue. A week later (or so), I switched to the insider build and I noticed it had been fixed so I thought that somebody had taken care of it. 

So .. perhaps somebody fixed another issue that was somehow related to this. :)

**Comment by Tyriar** [comment]
Great, one less thing to worry about :smiley:
