### ISSUE TITLE
Can not connect to extensions market place

### ISSUE THREAD

**Issue by Predatorie** [Microsoft/vscode#70613]
Issue Type: <b>Bug</b>

VS Code for Mac - connecting to extension market place was working but has now suddenly stopped. I have an active internet connection, market place on web  is live.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

Uninstalled and installed insiders build, same issue can not connect to market place. I am dead in the water so I have had to switch to another editor for the time being. Any help is appreciated.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (16.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
beautify|Hoo|1.4.9
pubspec-assist|jer|0.3.4
material-icon-theme|PKi|3.6.3
vscode-yaml|red|0.3.0

</details>

**Comment by Predatorie** [comment]
I found the issue. I have a VPN installed and for whatever reason disconnecting from the VPN re-enabled the market place connection. Is this by design? Can we not use a VPN?

**Comment by joaomoreno** [comment]
You should be able to use a VPN. If VS Code can't connect through the VPN, please file an issue to the VPN provider.
