### ISSUE TITLE
Dispaly goes wrong when running with NVIDIA processor

### ISSUE THREAD

**Issue by DXie123** [Microsoft/vscode#70612]
VS Code Version: 1.32.3 (system setup)
OS: Windows_NT x64 10.0.18351

There are green underline and green board line when running with NVIDIA processor, and the fonts also seem twisted.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by roblourens** [comment]
Can you try starting with `--disable-gpu` to see if that makes a difference? What do you mean "NVIDIA processor", do you mean GPU?
