### ISSUE TITLE
Completion not working for attribute value in JSX

### ISSUE THREAD

**Issue by pucelle** [Microsoft/vscode#70616]
- VSCode Version: 1.32.3
- OS Version: Win10 1803

Steps to Reproduce:

I created an extension [CSS Navigation](https://marketplace.visualstudio.com/items?itemName=pucelle.vscode-css-navigation) these days. When I trying to support class name completion in JSX file (it works well in HTML file), I found it can't work in some places:
`<div c[CURSOR] />` - Here, the completion work.
`<div className="c[CURSOR]" />` - Here, the completion failed, No request send to language service.

So I want to know if this is an issue, or I have missed some thing in providing completion?

Thanks very much.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Please share some example code that demonstrates this in an extension

**Comment by pucelle** [comment]
Hi, hmbvz, Thanks for your reply. My extension is here: [CSS Navigation](https://marketplace.visualstudio.com/items?itemName=pucelle.vscode-css-navigation)

And here are some codes for E2E testing (it's only code pieces):
https://github.com/pucelle/vscode-css-navigation/blob/master/client/test/fixture/index.jsx#L1-L13

You may clone the code of this extension and debug it, or just install the extension, and save the test file into one workspace directory, then try completion, and debug the communication message between client and language server.

I'm not sure if this is enough for you, if you need more resources, just comment here.

**Comment by mjbvz** [comment]
Do you see the completions requests being made if you manually trigger intellisense inside the string using ctrl+space? We don't automatically trigger completions inside strings by default. Alternatively, add this to your settings:

```json
	"editor.quickSuggestions": {
		"other": true,
		"comments": false,
		"strings": true
	}
```

**Comment by pucelle** [comment]
Yes, it works, Thanks very much!!!

Otherwise I have some suggestions: I searched about this in Google but I didn't get any helpful answer.
Now I found VSCode document [intellisense](https://code.visualstudio.com/docs/editor/intellisense) has some descriptions about quickSuggestions, but mot much. Can it give more details about?

Thanks again.
