### ISSUE TITLE
Windows Shell Task trims spaces from command

### ISSUE THREAD

**Issue by bjosa** [Microsoft/vscode#70621]
- VSCode Version: 1.32.3
- OS Version: Windows 10 Pro 1809

Steps to Reproduce:

Create a Task that has two or more spaces in the command. like this one.
Notice that there are two spaces between the words _two_ and _spaces_.

```jsonc
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "test",
            "type": "shell",
            "command": "echo",
            "args": ["two  spaces"],
            "problemMatcher": []
        }
    ]
}
```

This prints an output with only one space between the words on the terminal:

```
> Executing task: echo 'two  spaces' <

two spaces

Terminal will be reused by tasks, press any key to close it.
```

Expected is that the spaces included in the command are preserved in the terminal like this.

```
> Executing task: echo 'two  spaces' <

two  spaces

Terminal will be reused by tasks, press any key to close it.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This is just how PowerShell works:
````
D:\repos\Microsoft\vscode>powershell -Command echo 'two  spaces'
two spaces
````
If you want to preserve spaces don't use PowerShell:
````
In your task
			"options": {
				"shell": {
					"executable": "cmd.exe",
					"args": ["/c"]
				}
			},
````
````
Or in your settings
	"terminal.integrated.shell.windows": "cmd.exe"
````

**Comment by bjosa** [comment]
Thanks for pointing this out. I'll use cmd instead.

It's confusing that typing this directly in PowerShell it will work as expected:

```
PS C:\Users\user> echo "two  spaces"
two  spaces
```
