### ISSUE TITLE
Git SCM shows scroll bars in branch/sync panel

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#70623]
### As of version 1.32.3, the Git SCM branch/sync panel shows interfering scroll bars:

![Git Scrollbar](https://user-images.githubusercontent.com/9283914/54479836-ade38300-4821-11e9-9bd3-57d8d640d32d.png)

- VSCode/OS Version:
Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Datum: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17134

Steps to Reproduce:
1. Open a project using git
1. Open git panel
2. Move the mouse pointer to branch name.

Does this issue occur when all extensions are disabled?:
- [x] Yes
- [ ] No

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/6906d7e3b26e807eedc566944de344e0e53a39bc
