### ISSUE TITLE
Alternating editor background colors for major blocks

### ISSUE THREAD

**Issue by internally-combusted** [microsoft/vscode#70625]
The actual implementation would probably have to be in individual extensions like syntax highlighters, but it'd be useful for me for Code to provide a way to have the editor visually separate functions/structs by alternating the background color, like so:

![alternating](https://user-images.githubusercontent.com/48036274/54481030-e4eb7180-47ec-11e9-97be-f827a181fd3f.png)

It'd be especially nice in the minimap, I think.

**Comment by aeschli** [comment]
That would be an editor feature, maybe based on the outline information.

**Comment by alexandrudima** [comment]
This can be done from an extension...
