### ISSUE TITLE
Snap to maximize/minimize for editor group not persisting when going to Zen mode

### ISSUE THREAD

**Issue by Taugeshtu** [Microsoft/vscode#70626]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:
1. Maximize editor group
2. Go to Zen mode AND fullscreen, which is triggered by "Zen Mode: Full Screen" setting being set to `true`
3. Observe the editor groups retaining their proportions, but completely breaking "maximized" flag or something in them - when switching to another editor group it doesn't get maximized.

Really frustrating. This is what I need from my VSCode:
![VScode_flow](https://user-images.githubusercontent.com/6285293/54481160-ceb7d280-4839-11e9-8a10-7131f2d338d9.gif)
without any fiddling :/

**Comment by isidorn** [comment]
This has nothing to do with zen mode but with layout and sanpping.
Forwarding to @joaomoreno and @sbatten

**Comment by sbatten** [comment]
@bpasero editor maximization is handled a layer below the workbench i assume
