### ISSUE TITLE
Display profile images or avatar of people having access to workspaces in Live Share.

### ISSUE THREAD

**Issue by helios1101** [Microsoft/vscode#70628]
People use LIve-share Extension to collaborate in a particular project.
Whenever multiple people comes we get people list in the sidebar but if their profile pic or avatar from login can be used to display at top-right in the circular form it would look more interactive.
Adding to this whatever edits are shown by defaults in left sidebar, can be displayed when this avatar is clicked.
So my suggestion/feature request would be adding an additional function that make it more interactive to work on.

**Comment by roblourens** [comment]
Please file this on the repo for the Live Share extension
