### ISSUE TITLE
Wrong command name for `Open Workspace Settings`

### ISSUE THREAD

**Issue by alexreg** [Microsoft/vscode#70637]
The command `Prefernces: Preferences: Open Workspace Settings` should be `Preferences: Open Workspace Settings`.

I also see the commands:
* `Preferences: Open Settings (JSON)`
* `Preferences: Open Settings (UI)`
* `Preferences: Open User Settings`

It therefore maybe makes sense to get rid of `Preferences: Open User Settings` (or rather rename the previous two commands to `... Open User Settings ...` and have `(JSON)` and `(UI)` variants for the above `Preferences: Open Workspace Settings` as well.

**Comment by alexreg** [comment]
@usernamehw Almost. The other naming suggestions haven't been mentioned elsewhere.

**Comment by usernamehw** [comment]
@alexreg Do you really need those commands? Are you opening GUI and JSON workspace settings in rotation?

**Comment by alexreg** [comment]
@usernamehw No, but does it hurt? It's useful to have them all (just 4!) for consistency as well. There's no obvious way to access user settings anyway, apart from by the file browser.

**Comment by usernamehw** [comment]
> There's no obvious way to access user settings anyway, apart from by the file browser.

@alexreg What do you mean? Which setting you cannot access?

![Screenshot (107)](https://user-images.githubusercontent.com/9638156/54520144-109b6280-4979-11e9-9b16-6e058c870c52.png)

**Comment by usernamehw** [comment]
@roblourens

**Comment by alexreg** [comment]
Ignore me, I was getting confused... it would still be nice to have consistency though. :-)
