### ISSUE TITLE
Does not compiles

### ISSUE THREAD

**Issue by architjaiswal** [Microsoft/vscode#70636]
Issue Type: <b>Bug</b>

When ever I give compile and run commands, it redirects me to codeBlocks and their I have to compile my code.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.88GB (7.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0

</details>

**Comment by Sshirsha** [comment]
Update it to the latest version of vscode. I had the same problem but by updating I got the code complied and ran.

**Comment by architjaiswal** [comment]
> Update it to the latest version of vscode. I had the same problem but by updating I got the code complied and ran.

It is having the issue on latest version of vscode, I cannot update it any further.

**Comment by roblourens** [comment]
We need more details
