### ISSUE TITLE
htmlPreview is not pinned

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#7063]
* open something via `previewHtml`
* the part is shown as preview editor

<img width="515" alt="screen shot 2016-05-31 at 17 03 15" src="https://cloud.githubusercontent.com/assets/1794099/15679296/94d4dd62-2751-11e6-86e3-7dac10220399.png">

**Comment by jrieken** [comment]
@bpasero ideas?

**Comment by bpasero** [comment]
@jrieken that is true for any editor until some condition that makes it pinned. currently we have:
* double click from the explorer
* double click from "opened editors" list
* double click on title of editor
* the global action to pin an editor

The fact that an editor is preview or not is not bound to the editor being a file or not. Are you suggesting we should change this assumption?

**Comment by jrieken** [comment]
The html preview isn't an editor - it renders html and happens to be implemented as an editor. I think it should be pinned by default
