### ISSUE TITLE
Escaping a "create file/folder" shortcut changes the file explorer focus to a different path.

### ISSUE THREAD

**Issue by IgorGee** [Microsoft/vscode#70631]
Steps to Reproduce:

1. Focus file explorer from a file nested in a directory
1. Enter shortcut to create file/folder
a. This prompts a file/folder name to be entered in the correct path (the nested folder)
1. Press Escape
1. Enter shortcut to create file/folder
a. This prompts a file/folder name to be entered in an incorrect path (not the nested folder)

Does this issue occur when all extensions are disabled?:

Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70069
