### ISSUE TITLE
占用cpu100%

### ISSUE THREAD

**Issue by zhangpurple** [Microsoft/vscode#70638]
Issue Type: <b>Bug</b>

code安装有损坏，占用cpu100%

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.75GB (2.07GB free)|
|Process Argv|D:\msz\VSCode-vuewin32-x64-1.24.0\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
npm-intellisense|chr|1.3.0
angular2-snippets|dan|1.0.21
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.9
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
Angular-BeastCode|Mik|7.2.5
vscode-language-pack-zh-hans|MS-|1.24.3
angular2-inline|nat|0.0.17
vetur|oct|0.12.6
material-icon-theme|PKi|3.6.3
vue-vscode-snippets|sdr|1.3.0
ionic2|Tha|3.0.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance issues
