### ISSUE TITLE
Highlighted line lost in search results of files after edit content of file

### ISSUE THREAD

**Issue by Daijobou** [Microsoft/vscode#70645]
Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Datum: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Search in your project a string and you get many files in results found in files
2. Select a line from founded file in results, its now highlighted in list
3. Edit content of this file in editor before line of results. Now the highlight is gone

Its annoying to find the correct file and line for next edit, becuase the highlight is gone.
And I would like a better highlight for the active file in list, not only the selected line of results. ;-)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/20467
