### ISSUE TITLE
Cannot load PyLint on start even it's installed

### ISSUE THREAD

**Issue by AnClark** [Microsoft/vscode#70643]
Issue Type: <b>Bug</b>

I installed PyLint via `pip3 install pylint`, however sometimes when I start VS Code, it will report an error:

```
Starting Jedi Python language engine.
Linting with pylint failed.
Error: Module 'pylint' not installed.
```

But soon PyLint can work properly.

Would you love to fix this bug?

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 5.0.1-akura-enhance_test

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 1639)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.74GB (0.06GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.25.0
vscode-todo-plus|fab|4.13.0
gc-excelviewer|Gra|2.1.29
vscode-language-pack-ja|MS-|1.32.4
vscode-language-pack-zh-hans|MS-|1.32.4
python|ms-|2019.2.5558
markdown-preview-enhanced|shd|0.3.12
vscode-todo-highlight|way|1.0.4

</details>

**Comment by roblourens** [comment]
Please file this on the python extension repo
