### ISSUE TITLE
Files lost due to update?

### ISSUE THREAD

**Issue by Fnoh** [Microsoft/vscode#70649]
Issue Type: <b>Bug</b>

Hello,

could it be that Updates for VS Code delete everything that was stored in its installation folder?
I stored my Projects in a self created Folder "G:\Microsoft VS Code\Projects\". But now after the Update (i think the February update just happened) the Projects-folder is gone.

I could recover the files with 'recuva', but it would be nice to know what happened. I don't think I deleted them.

Am i right with my assumption?

Kind regards,
Christopher

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-language-pack-de|MS-|1.32.4
python|ms-|2019.2.5558
angular2-inline|nat|0.0.17
autoimport|ste|1.5.3
vscode-icons|vsc|8.3.0

</details>

**Comment by roblourens** [comment]
We did have a bug that changes in unsaved files could be lost when upgrading from 1.31 to 1.32. That is fixed now. I'm not aware of any bug that would have deleted an entire folder.

You could download 1.31 and try upgrading again to see if this happens again. https://az764295.vo.msecnd.net/stable/1b8e8302e405050205e69b59abb3559592bb9e60/VSCode-win32-x64-1.31.1.zip But I think it's more likely that there is some other external issue...

**Comment by weinand** [comment]
no reply -> closing
