### ISSUE TITLE
Copy line / duplicate line not working (Windows 10)

### ISSUE THREAD

**Issue by KhaaliTurbo** [Microsoft/vscode#70644]
Issue Type: <b>Bug</b>

On any line in a .ps1 script, Shift+Alt+Up or Down doesn't duplicate the current line. Ctrl+C + Ctrl+V (when nothing is selected) on front of the line does work, but is not what I want. This is supposed to work isn't it? I see the keyboard shortcut in my keyboard shortcuts keybindings (and no other ones which could interfere).

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.11.0

</details>

**Comment by roblourens** [comment]
Possible troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexandrudima** [comment]
@KhaaliTurbo Can you please check the keybinding bound to "shift+alt+up"

Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by KhaaliTurbo** [comment]
@alexandrudima only the "Copy Line Up" is bound to "Shift + Alt + UpArrow". And for Copy Line Down it's "Shift + Alt + DownArrow".

![image](https://user-images.githubusercontent.com/32901068/55150769-1d743f00-514d-11e9-86e5-74e202d46c86.png)

![image](https://user-images.githubusercontent.com/32901068/55150743-10575000-514d-11e9-98ad-5da70cdfe125.png)

**Comment by alexandrudima** [comment]
Thanks for following through. Now that we know that keybinding would trigger the action, let's check if VSCode receives the keybinding form the OS:

e.g.
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by KhaaliTurbo** [comment]
Thanks. I don't know why or how, but after I did that, it started working. I will close this issue.
