### ISSUE TITLE
安装后显示不支持

### ISSUE THREAD

**Issue by JianGuoHt** [Microsoft/vscode#70642]
Issue Type: <b>Feature Request</b>

可以将后面的不受支持取消吗  难受

Extension version: 1.1.19
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Fierralin** [comment]
Translation: 
After installed, it keeps on showing "unsupported".
Could you pls cancel it? I feel ill (OCD haha)

**Comment by roblourens** [comment]
I don't understand, we need more details
