### ISSUE TITLE
Obvious memory leaks

### ISSUE THREAD

**Issue by wildlywasp** [Microsoft/vscode#70641]
Issue Type: <b>Bug</b>

Obvious memory leaks when writing python scripts with vscode.
env: anaconda 5.3.1 (python 3.7)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (5.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|55%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clang|mit|0.2.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
Go|ms-|0.9.2
vscode-yaml|red|0.3.0
cmake-tools|vec|1.1.3

</details>

**Comment by roblourens** [comment]
Please file this on the python extension repo
