### ISSUE TITLE
Settings UI dropdowns jumping around

### ISSUE THREAD

**Issue by AndreasBackx** [Microsoft/vscode#70652]
Issue Type: <b>Bug</b>

I have just recorded what happened as it almost sounds too silly to describe. I recommend to view it full-screen to see what happens. When I hover over the dropdown of one setting in VS Code, change it, then hover over another to try and change it, it opens the previous dropdown. Perhaps there is a more accurate explanation, but it's strange nonetheless.

[Video of what is happening.](https://gfycat.com/OddballAncientGrison)

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T14:40:37.095Z)
OS version: Linux x64 5.0.1-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 2692)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.68GB (5.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.4.0
better-toml|bun|0.3.2
gitlens|eam|9.5.1
graphviz-preview|EFa|1.3.0
tslint|eg2|1.0.43
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
godot-tools|gee|0.3.7
graphql-for-vscode|kum|1.13.0
Kotlin|mat|1.7.0
rainbow-csv|mec|1.0.0
vscode-clang|mit|0.2.3
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
Go|ms-|0.9.2
vsliveshare|ms-|0.3.1326
autodocstring|njp|0.2.3
vetur|oct|0.16.2
vscode-docker|Pet|0.6.0
tslint-vue|pro|1.5.6
jinjahtml|sam|0.8.0
code-settings-sync|Sha|3.2.7
vscode-nginx|sha|0.6.0
dot|Ste|0.0.1
vscode-icons|vsc|8.3.0
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by AndreasBackx** [comment]
I've just updated to version 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4) and the bug persists.

**Comment by roblourens** [comment]
Thanks for the video, this is already fixed in Insiders for the next version.
