### ISSUE TITLE
Internationalize markdown extension

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#7065]
For #6106:

Support the core vscode UI languages.

**Comment by jrieken** [comment]
@dbaeumer can help. There is a story that we have used for the TypeScript extension and others

**Comment by dbaeumer** [comment]
Yes, we do have full support to externalize strings in extensions. All extensions in the vscode repository should be externalized so what we for example do in TS or JSON can be copied.

If markdown moves to its own repository and out of vscode then the story is more or less the same. You can use vscode-nls to do the string marking as in the normal extension code. To do the actual string extraction during build time there is another npm module that can be used called vscode-nls-dev.

Although not an extension vscode-node-debug uses both npm modules to do their internationalization work.

@kieferrm please ping me if you need any additional information.

**Comment by kieferrm** [comment]
Only requires the `package.json` files to use keys that are resolved in the `package.nls.json` file. Everything afterwards is handled automatically. Nothing else todo.
