### ISSUE TITLE
Can't find Sign-in option

### ISSUE THREAD

**Issue by Anuadh** [Microsoft/vscode#70653]
Issue Type: <b>Feature Request</b>

Hello Sir,
I have using visual studio code . And I unable to find sign in option so I can  login using my microsoft accout to use benifits. Please solve it.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.4.0-21-generic

**Comment by roblourens** [comment]
There is no "sign in" option. vscode is free 😁
