### ISSUE TITLE
Rename Folder

### ISSUE THREAD

**Issue by Leandermen** [Microsoft/vscode#70655]
Issue Type: <b>Bug</b>

In Explorer. I copy-paste a folder into the workspace (ej: copy foder "foo" and it renamed to "foo.1"), after that i wanted to rename to another name and it didn't allow me to rename it

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
prettier-vscode|esb|1.8.1
git-project-manager|fel|1.7.1
beautify|Hoo|1.4.9
python|ms-|2019.2.5558
github-issues-prs|ms-|0.9.1
debugger-for-chrome|msj|4.11.3
LiveServer|rit|5.5.1
vscode-icons|vsc|8.3.0

</details>

**Comment by roblourens** [comment]
Please explain the issue some more. How did you try to rename it, and what happened instead? Can you get it to happen a second time?
