### ISSUE TITLE
Preview of markdown is not working

### ISSUE THREAD

**Issue by hanpari** [Microsoft/vscode#70657]
This seems to be duplicate of https://github.com/Microsoft/vscode/issues/68912

I tried to disable all extension, restart VSCode and markdown seems to work. But as soon as I enabled one extension (no matter which) it seems to stop working again.

In developer console I found this error

    [Embedded Page] Uncaught TypeError: Cannot read property 'body' of null

It appears everytime I try to open preview.

Issue Type: <b>Bug</b>

After upgrading to  1.32.3 I tried Ctrl+K V to see preview of my markdown file but the preview window stays clear with no text whatsoever.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2020M @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.88GB (3.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.28
vscode-importmagic|bra|0.1.3
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.2.0
python|ms-|2019.2.5558
django-intellisense|sha|0.0.2
vscode-djaneiro|the|1.4.2

</details>

![obrazek](https://user-images.githubusercontent.com/7354817/54495712-a803a580-48e6-11e9-8ef8-0c508fa4aff9.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by hanpari** [comment]
> 
> 
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

No, I didn't test it. Nevertheless, on my second computer (same system, the latest version of VsCode) I was not able to reproduce it either. This one works as expected with my extensions enabled.

**Comment by mjbvz** [comment]
Please test on the latest insiders build

**Comment by hanpari** [comment]
OK I will try. Meanwhile I should inform you I have completely uninstalled the not-functional VS Code  and installed new downloaded one for system installation. Now it is working again.

**Comment by hanpari** [comment]
OK, so insider build downloaded and extracted from zip with no installed extension doesn't work!

![report](https://user-images.githubusercontent.com/7354817/54542890-e196e800-499c-11e9-9431-81703c221e8f.gif)

**Comment by mjbvz** [comment]
Does it work for any markdown files?

**Comment by hanpari** [comment]
Sometimes yes, sometimes no. I saw even problem with md files from extension description.

**Comment by mjbvz** [comment]
Based on the error, this sounds like the same issue as #70790

It seems there's something goofy going on with webviews and window's firewall or security settings. Will keep tracking this issue in #70790
