### ISSUE TITLE
Regular quotes over smart quotes

### ISSUE THREAD

**Issue by rhewy** [Microsoft/vscode#70658]
Turn off smart quotes (Text editor option or language based option)

I really desire regular quotes over smart quotes. I am working in python so I am not sure if this a generic text editor thing or a language based thing. Cross language and platform I find that regular quotes are more stable.

**Comment by roblourens** [comment]
I don't understand what you are asking for

**Comment by rhewy** [comment]
Here is an example
https://images.newrepublic.com/2a6f0041ce8493add4a44cfeb7a598787402bfc9.png?w=1000&q=65&dpi=2.625&h=332

**Comment by rhewy** [comment]
Do you want a screenshot of what I see in VSCode?

**Comment by roblourens** [comment]
vscode doesn't add smart quotes, this is probably coming from an extension, or from your keyboard. Can you check whether it still happens if you start vscode with `--disable-extensions`?
