### ISSUE TITLE
search bar for filter search

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/vscode#70664]
I am a heavy mouse user and primary work on a project with thousands of files. Each time I search on the left, I have to place my cursor there then type. Generally, this means that I open up some random file that I clicked on. 

Please add a dedicate space for me to place my cursor and search, as proposed in yellow below.

![image](https://user-images.githubusercontent.com/8278033/54498785-984a8800-490b-11e9-81fd-f9b2296df002.png)

**Comment by roblourens** [comment]
@sandy081 @isidorn is it possible to focus a tree with the mouse, without selecting a row?

**Comment by isidorn** [comment]
Yeah you can click on the activity bar.
In the tree you can not click. Leaving open as a feature request
fyi @joaomoreno

**Comment by joaomoreno** [comment]
Clicking the scrollbar works.

**Comment by potatoqualitee** [comment]
it does work, but then im spending a lot of time focusing on clicking on a scroll bar and/or backspacing my previous search term. Both Visual Studio and PowerShell Studio have a dedicated search boxes; it would be very useful to have it in VS Code as well.
