### ISSUE TITLE
Add Copy Name context menu option for Variables view in Debug pane

### ISSUE THREAD

**Issue by hoehrmann** [Microsoft/vscode#70666]
Suppose you store long strings as names in an object e.g. because you mean to deduplicate them or cache data about them like

```js
seen[string] = true
```

There currently seems to be no way to get to the full `string` from the Variables view other than the tooltip when you hover over the name, which might not be sufficient if the string is very long, and you cannot get it onto the clipboard even when it might fit a tooltip.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70377 as we want this to come from extensions
In the meantime use the Copy as Expression as a workaround
