### ISSUE TITLE
Variable watch entry should be removed when pressing DEL key

### ISSUE THREAD

**Issue by hoehrmann** [Microsoft/vscode#70668]
Pressing `del` on a breakpoint in the debugging sidebar removes the breakpoint.

Doing the same on a watch expression does not remove the watch expression.

**Comment by hoehrmann** [comment]
That issue is not a duplicate, it's about adding a button, this is about binding a key to an action.

**Comment by ersteller** [comment]
Should be fixed by #68687

**Comment by jjasoncool** [comment]
#68687 I uploaded a demo video, this issue may not be fixed.

**Comment by isidorn** [comment]
This is fixed in latest insiders and will be in stable in about 10 days

**Comment by jjasoncool** [comment]
Thanks a lot!
