### ISSUE TITLE
Add way to determine if terminal modification is "allow" or "disallow"

### ISSUE THREAD

**Issue by ssilverman** [Microsoft/vscode#70663]
There's this new mysterious "Do you allow this workspace to modify your terminal shell?" message that happens whenever any action is done in VSCode (I'm using PlatformIO).
(See #68032 for more questions about this, but it doesn't answer the questions posed here.)

When clicking "allow" or "disallow", some state is changed somewhere for the current project. There's no way to determine what the state is after one of the choices is made. Note that a choice can also be made using the Command Palette.

To summarize:
1. How to determine the current state?

Related:
1. How to change the state so that the dialog asks again after a choice is made? Completely recreating the project doesn't change the state. It somehow remembers what was chosen last and never asks again.
2. What is the effect of "allow" vs. the effect of "disallow"? Does it change some terminal setting somewhere outside of VSCode, or does it affect something within only VSCode?
3. Is it possible to document this more fully? For example, inside one of the settings.json areas.

VSCode version: 1.32.3
OSX version: 10.14.3

**Comment by Tyriar** [comment]
> How to determine the current state?

There are 3 states: allowed, disallowed or not answered. There is no easy way to query the state.

> How to change the state so that the dialog asks again after a choice is made?

You cannot unless you change the workspace folder's path. There are these actions though:

![image](https://user-images.githubusercontent.com/2193314/54869410-0a303080-4d55-11e9-81ec-32ca378fb5cf.png)

> What is the effect of "allow" vs. the effect of "disallow"?

allow will allow the use of the `terminal.integrated.*.env|shell|shellArgs` settings, disallow will prevent it (the default).

> Is it possible to document this more fully? For example, inside one of the settings.json areas.

It's intentionally not a setting as we don't want to pollute your user settings with a bunch of workspace folders that you allowed. It's meant to be lightweight and answer once and forget about it sort of option. If you have suggestions on improvements to the dialog or something I'm all ears 😃
