### ISSUE TITLE
File Menu - Settings & Extensions Complete Backup Natively in Code

### ISSUE THREAD

**Issue by SirTwsted** [Microsoft/vscode#70670]
I would like to go to FILE Menu,
and select "Backup Studio Code".  Where it then goes through the entire process of completely
backing up the entire Studio Code into a compressed file.  It will save everything,
so a user can either keep a backup on their Google Drive or Thumb-Drive.
and take that backup anywhere they want.
And they decide to install Studio Code into a new computer or laptop,
they can then use that backup file they created and saved to have / restore Studio Code exactly how they left it when they did the backup.

I tried many extensions that says they do this feature in some kind of way,
But I would like something that is actually part of Studio Code itself and not rely on an extension to do this.
in case a person doesnt have access to internet for what ever reason or another.
I just want something solid that I can depend on right within and part of Studio Code itself.

**Comment by roblourens** [comment]
I think this is not likely. We do have an issue for providing settings sync support: https://github.com/Microsoft/vscode/issues/2743

But it would be simple to write a script or an extensino which essentially does what you ask.

**Comment by SirTwsted** [comment]
ok, so I guess I will have to go to %appdata% and save all the folders in that directory, 
Then go to MyDocuments folder and Save all folders in that directory,
And then look any where else on my Windows OS for anything that has to do with Visual Studio Code, and also save those folder.
And then group all those folder together into 1 folder and name it back up.
Then save on thumb drive and also Google Drive.
Since microsoft doesnt want to create a Backup feature natively in Studio Code .....
:(

**Comment by roblourens** [comment]
User data (settings and workspace state) is stored here: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

Extensions are stored in `~/.vscode/extensions`.

That's it

**Comment by SirTwsted** [comment]
Thank you, will definitely do that.
Such a shame microsoft company doesnt want to do this natively within their application.
as millions of people would love to have this feature.
anyways, on I go to save a bunch of files.
