### ISSUE TITLE
VSCode LuaIde extension memory usage maybe very high

### ISSUE THREAD

**Issue by liyu34** [Microsoft/vscode#70675]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

The same extension, LuaIde, use different memories.
After upgrade VSCode to Version 1.32+, the LuaIde will eat more than 1G memories when it is inited with some editor open, and if during it`s initialization close all editors, it will cost no more than 300M memories. Here is one gif to show how it appeared.

![VSCode内存问题](https://user-images.githubusercontent.com/12342277/54504895-9ff04800-4970-11e9-8226-81105519258c.gif)

**Comment by roblourens** [comment]
Please file this on the lua extension repo
