### ISSUE TITLE
Vertical Editor Side-by-Side with Vertical Terminal

### ISSUE THREAD

**Issue by HJLBX** [Microsoft/vscode#70673]
There is no way to configure VSCode editor and terminal to be side-by-side vertical ?

**Comment by HJLBX** [comment]
I am not sure what the purpose of the vscodebot is as it points to something that has nothing to do with my original question.

What I am asking is if there is a way to configure VSCode editor-terminal layout so that the editor and terminal are both simultaneously aligned vertically (side-by-side) ?

**Comment by knyhle** [comment]
You mean the panel postion? 
```> View: Toggle Panel Position```

**Comment by HJLBX** [comment]
There is no View: Toggle Panel Position on the latest VSCode version.

**Comment by knyhle** [comment]
Oh, it's in the command pallete.

![sidebysideterminal](https://user-images.githubusercontent.com/10459400/54506561-f7f46380-490a-11e9-8cb6-bcc1a1fb002b.PNG)

**Comment by HJLBX** [comment]
Thank you.
