### ISSUE TITLE
Vscode cross-directory watch files change

### ISSUE THREAD

**Issue by veaba** [Microsoft/vscode#70679]
- VSCode Version: 1.32.3
- OS Version:Windows_NT x64 6.1.7601

Steps to Reproduce:

>sometime will has
- A folder with files
![image](https://user-images.githubusercontent.com/8652596/54511819-17cc6b80-498d-11e9-8f86-6dcb9e04e0e9.png)

Even the folder is empty,Source control has a loading icon

- with command use `code folder`
>Open this folder again,it is fix~。

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Those are not reproducable steps.
Please file with nice repro steps so I actually know what you are trying to say and that I can repro on my machine. Thanks a lot!

**Comment by veaba** [comment]
Maybe it was my mistake. I found that vscode always checks the parent's. git file and lists all its subfiles, including subfolders.

The first problem I mentioned was that I accidentally init the F disk, causing it to check all its subfiles recursively every time.

(:=  sorry~

**Comment by isidorn** [comment]
No problem. Closing this issue, glad it works now :)
