### ISSUE TITLE
The terminal will be blank when the string is entered

### ISSUE THREAD

**Issue by CaijiOrz** [Microsoft/vscode#70678]
- VSCode Version: 1.32.3
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Ctrl + ` open terminal
2. enter any string

Does this issue occur when all extensions are disabled?:  Yes

My system terminal language is chinese, maybe this is the reason?

![Honeycam 2019-03-18 14-44-23](https://user-images.githubusercontent.com/18412368/54511719-c7eda480-498c-11e9-9b44-d5f4fc82fd06.gif)

**Comment by beastdestroyer** [comment]
No this has been a problem for a long time. It's due to the way the terminal is rendered and whatnot. The VSCode team are working on Conpty terminal and will be available with the 19H1 release of windows, to which VSCode will be updated to support CONPTY. 
@Tyriar since you're the terminal guy

**Comment by CaijiOrz** [comment]
> No this has been a problem for a long time. It's due to the way the terminal is rendered and whatnot. The VSCode team are working on Conpty terminal and will be available with the 19H1 release of windows, to which VSCode will be updated to support CONPTY.
> @Tyriar since you're the terminal guy

I understand. thank you very much.
look forward to it.
