### ISSUE TITLE
when Typing "if"

### ISSUE THREAD

**Issue by japhib** [Microsoft/vscode#70672]
When using VSCode (with Unity 2018.3 if that matters), typing "if" and then a space often autocompletes to "iPhoneSettings". Can Intellisense be tuned not to offer autocomplete suggestions for super common language keywords?

Edit: On further investigation, it looks like the `iPhoneSettings` suggestion only registers with the `i` and not the `f`, which makes it seem like a case of typing `if` quickly enough, it misses the `f` completely. 
![image](https://user-images.githubusercontent.com/11890284/54502235-26644580-48ef-11e9-951f-9fd813669478.png)

Edit #2: the bot labelled this with javascript when it applies to C#.

**Comment by mjbvz** [comment]
Please file this issue against the c# or unity extensions (probably start with C#)

**Comment by w0nche0l** [comment]
This is also happening for me and is really annoying... @japhib any luck with this?

**Comment by japhib** [comment]
@w0nche0l Not yet. Here's the issue on the c# extension repo though: https://github.com/OmniSharp/omnisharp-vscode/issues/2472
