### ISSUE TITLE
Decorate filename for merge conflict not working on Mac

### ISSUE THREAD

**Issue by alanyinjs** [Microsoft/vscode#70671]
- VSCode Version: 1.32.3
- OS Version: macOS High Sierra 10.12.6

Steps to Reproduce:

1. Produce a merge conflict in a repo
2. open the repo in vscode
3. Observe whether the filename for the file that contains the merge conflict would change colour

Does this issue occur when all extensions are disabled?: **YES**

Expected behaviour on Windows (files that contain merge conflicts are coloured in purple):
![conflict](https://user-images.githubusercontent.com/25688258/54500702-b21fb580-4973-11e9-9779-6a8f64ab03f7.PNG)

**Comment by jrieken** [comment]
Please share the repro and repro steps with us

**Comment by alanyinjs** [comment]
@jrieken Thanks Johannes. Please find the following steps:

1. Open the same repo in vscode (1.32.3) on mac (10.12.6)
2. Observe there is no colour change in filenames for files that contain merge conflicts
<img width="327" alt="Screen Shot 2019-03-18 at 7 45 25 pm" src="https://user-images.githubusercontent.com/25688258/54517823-de105a80-49b6-11e9-92f4-af63f8cbd9cc.png">

**Comment by jrieken** [comment]
What does the git log show (F1 > Show Git Output)? Do modified/untracked markers work?

**Comment by alanyinjs** [comment]
@jrieken Here is the git output: 
```
Looking for git in: /usr/local/bin/git
Using git 2.16.2 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/alanyin/EMR
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse c2cnew-3814-UI-observations-hip
> git rev-parse --symbolic-full-name c2cnew-3814-UI-observations-hip@{u}
> git rev-list --left-right c2cnew-3814-UI-observations-hip...refs/remotes/origin/c2cnew-3814-UI-observations-hip
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git check-ignore -z --stdin
> git check-ignore -z --stdin
```

Here is what I did with the merge:
```
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/types/dynamicAssessment.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/shared/constants/observation.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/reducers/dynamicAssessment/patientObservationsReducer.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/reducers/dynamicAssessment/patientObservationReferenceDataReducer.js
CONFLICT (content): Merge conflict in Sources/Web/Siberia.Web/static/js/react-src/reducers/dynamicAssessment/patientObservationReferenceDataReducer.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/i18n/en.json
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/constants.js
CONFLICT (content): Merge conflict in Sources/Web/Siberia.Web/static/js/react-src/constants.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/components/pages/DynamicAssessment/Observations/observationsMock.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/components/pages/DynamicAssessment/Observations/index.js
CONFLICT (content): Merge conflict in Sources/Web/Siberia.Web/static/js/react-src/components/pages/DynamicAssessment/Observations/index.js
Auto-merging Sources/Web/Siberia.Web/static/js/react-src/actions/dynamicAssessment/patientObservationsActions.js
CONFLICT (content): Merge conflict in Sources/Web/Siberia.Web/static/js/react-src/actions/dynamicAssessment/patientObservationsActions.js
Automatic merge failed; fix conflicts and then commit the result.
```

When you look at the "merge changes" tab, it clearly shows all the files with merge conflict (marked with purple C). However it is not happening with the file names in the 'EXPLORER' as shown in my previous posts.
<img width="349" alt="Screen Shot 2019-03-19 at 8 26 07 pm" src="https://user-images.githubusercontent.com/25688258/54594703-52193400-4a85-11e9-9498-e948158f2799.png">

**Comment by jrieken** [comment]
So, what folder are you opening? In the first comment it seems you have opened `react-src` in the second it seems you have opened `~`? Also, what is the value the `git.decorations.enabled` setting and what are the values of the `explorer.decorations` settings?

**Comment by alanyinjs** [comment]
@jrieken Thanks a lot for the prompt reply! I was opening 'react-src' in both cases (the screenshot I showed you above is the source control tab on the left hand side -> 
<img width="390" alt="Screen Shot 2019-03-19 at 9 48 02 pm" src="https://user-images.githubusercontent.com/25688258/54600363-b5f52a00-4a90-11e9-86bb-d6855fb2df2c.png">
). 

the value of `git.decorations.enabled` is `true` and all the `explorer.decorations` settings were set as `true`: 
<img width="995" alt="Screen Shot 2019-03-19 at 9 49 16 pm" src="https://user-images.githubusercontent.com/25688258/54600460-f5237b00-4a90-11e9-94b5-ab6cdafc7788.png">
<img width="1047" alt="Screen Shot 2019-03-19 at 9 49 45 pm" src="https://user-images.githubusercontent.com/25688258/54600466-f94f9880-4a90-11e9-95cc-909dc8e15522.png">

I have checked all of the above and ensured that I had the latest version. I also disabled all extensions. Are you using Windows/Linux? I'm asking because this can only be reproduced on Mac.

**Comment by jrieken** [comment]
> (the screenshot I showed you above is the source control tab on the left hand side (that's where the ~ came from)

So, is the `.git` folder in `~` then?

**Comment by alanyinjs** [comment]
@jrieken Yes. The `.git` folder is in `~` and I opened a subdirectory (i.e. `react-src`) which doesn't contain `.git` in both cases. 

The only difference between this:
![conflict](https://user-images.githubusercontent.com/25688258/54500702-b21fb580-4973-11e9-9779-6a8f64ab03f7.PNG)
and this:
<img width="327" alt="Screen Shot 2019-03-18 at 7 45 25 pm" src="https://user-images.githubusercontent.com/25688258/54517823-de105a80-49b6-11e9-92f4-af63f8cbd9cc.png">
is that the one with purple decoration is on Windows and the one without decoration (for files containing merge conflicts) is on Mac.

Other decorations (e.g. linter errors etc.) for filename still work in both cases. Just the merge conflict decoration that is not working on the Mac version.

**Comment by alanyinjs** [comment]
@jrieken I just realised it's working now (Not sure exactly why as I tried restarting it before and it didn't work...). I will close this issue. Thanks so much for your time!
