### ISSUE TITLE
Explorer: Command list.open should toggle folder expansion

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#70681]
From https://github.com/VSCodeVim/Vim/issues/3466

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/e0e8a3348d77ae496c872982c37121147e750529/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L342

**Comment by isidorn** [comment]
Works great, adding verified label
