### ISSUE TITLE
Cannot update - "There was an error when marking a file for deletion"

### ISSUE THREAD

**Issue by theLoFix** [Microsoft/vscode#70680]
- VSCode Version: 1.31.1
- OS Version: Windows 7 64-bit

Steps to Reproduce:

1. Check update
2. Instal Update

Does this issue occur when all extensions are disabled?: No

During update error occurs:
![2019-03-18_08h07_10](https://user-images.githubusercontent.com/25254833/54512681-46c6eb00-4955-11e9-88bf-9dcb1e477b93.png)
![2019-03-18_08h07_23](https://user-images.githubusercontent.com/25254833/54512679-46c6eb00-4955-11e9-9927-11c6f1519ccc.png)

[vscode-inno-updater-1552892787.log](https://github.com/Microsoft/vscode/files/2976732/vscode-inno-updater-1552892787.log)

**Comment by joaomoreno** [comment]
Please install Code in a user-owned folder, if you're using the [user install](https://code.visualstudio.com/docs/?dv=win64user).

If you'd like to install in Program Files, please use the [system install](https://code.visualstudio.com/docs/?dv=win64).
