### ISSUE TITLE
Failing RPM builds

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#70688]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=44615

```
cp: cannot stat 'usr/share/pixmaps/code-insiders.png': No such file or directory
```

Could it be from https://github.com/Microsoft/vscode/pull/62650?

**Comment by Tyriar** [comment]
Needed to create my own branch to do CI builds and didn't bring https://github.com/Microsoft/vscode/pull/70699/commits/f425411ab36b7aed382e35e6a33c30b7f2de0b7c to the PR branch, will do a build now to verify

**Comment by Tyriar** [comment]
Passed
