### ISSUE TITLE
Add support for sub-sessions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#70695]
This item is for exploring the UI side of #62972.

for details see https://github.com/Microsoft/vscode/issues/62972#issuecomment-438723929

**Comment by isidorn** [comment]
@weinand yes, this makes sense.

Bottom line:
1. Child sessions will be shown as children of a parent session in the CALLSTACK view
2. Child sessions are shown like all other session in the debug drop down
3. Stopping a parent session stops all child sessions as well
4. The only way for the debug extension to create child sessions is via `startDebugging` call

I can implement this once we add this feature to the API. Just ping me once it is added. Thanks.

**Comment by weinand** [comment]
@isidorn the API is there and startDebugging has already an additional parameter "parentSession". The new "serverReady" feature already uses the new API.

1. OK
2. OK
3. I'm not yet sure about this one. Don't change anything for this right now.
4. yes, correct

**Comment by isidorn** [comment]
@weinand ok cool, thanks. I will look into this tomorrow..

**Comment by isidorn** [comment]
We now support sub-sessions in VSCode.
Even added some unit tests!

![Screenshot 2019-03-20 at 11 29 22](https://user-images.githubusercontent.com/1926584/54677625-8f240b80-4b03-11e9-9b5a-22f0bc817d60.png)
