### ISSUE TITLE
Restore smartSelect steps for XML documents

### ISSUE THREAD

**Issue by reubster** [Microsoft/vscode#70691]
Feature used to work whereby editor.action.smartselect.grow would expand a selection within an Xml element to select all content between angle brackets. 

Currently, the selection is expanded from the current word directly to the entire line, which makes it much less powerful.

**Comment by jrieken** [comment]
We are finalising the API for this during this milestone and that it is up to extensions to implement this correctly. The old approach was unreliable, error prone, and a cause for UX freezes.
