### ISSUE TITLE
search ignore white spaces

### ISSUE THREAD

**Issue by Louis7777** [Microsoft/vscode#70697]
I think it would be really convenient to have a search toggle that allows us to search while ignoring any whitespace.

For example, if the code contains the word `Github` but you search for `Github   ` , you won't get any results because of the space.

This is a feature that I liked in Dreamweaver (enabled by default for all searches) and that is missing from VS Code.

![search-ignore-white-spaces](https://user-images.githubusercontent.com/7398634/54530765-544b9780-498c-11e9-80b6-eaaf940c57d0.png)

VS Code has most of the options seen above, such as **Match Case**, **Match Whole Word** and **Use Regular Expressions**, but it doesn't have **Ignore White Spaces**.

![Untitled](https://user-images.githubusercontent.com/7398634/54531131-37fc2a80-498d-11e9-8a04-557c7f245ea1.png)

**Comment by roblourens** [comment]
It seems like the easiest thing to do is to not add whitespace to your query. I don't really see the benefit of this.

**Comment by Louis7777** [comment]
> 
> 
> It seems like the easiest thing to do is to not add whitespace to your query. I don't really see the benefit of this.

The fact that I have not given the best of examples - in favor of simplicity - doesn't mean that there aren't benefits.

So here's another example. There are many code tutorials, snippets and fixes on the Web which require you to search and add or replace code.

Try searching for this:
```
if(...)
{

var hello;
}
```

When in reality it is like this:
```
if (...) {
    var hello;
}
```

Yeah, no luck.

There have been many occasions where I couldn't locate the suggested code (and eventually I had to be much more specific in my queries) because of whitespace differences! You name it - tabs, trailing spaces, new lines etc.

And in any case, does it matter whether I can express the benefit of it? Adobe has it in their product enabled by default. There have to be benefits, one would think, right? Plus, it is the only option missing from VS Code's search. It'd be a good thing to have it.

**Comment by roblourens** [comment]
This would require us to either rewrite the query into a regex that can match different things or to build an index of the codebase that we can fuzzy search. We investigated the second and rejected it as being too complicated for a "simple/lightweight" code editor.

**Comment by Louis7777** [comment]
Well, maybe someone can come up with a good implementation if we don't dismiss the idea. After all, these days VS Code is an all-in-one editor rather than a "simple" editor like Dreamweaver - yet the latter has had this neat feature for a long time.
