### ISSUE TITLE
Indentation detection on ruby files is incorrect

### ISSUE THREAD

**Issue by jrz** [Microsoft/vscode#70694]
Issue Type: <b>Bug</b>

Indent-detection doesn't work properly for ruby files with spaces:2.. It will detect tabs/4.. probably because it doesn't detect any indentation, and defaults to tabs/4

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

I have the extension: ruby|reb|0.22.3 , which afaik doesn't change anything

**Comment by aeschli** [comment]
Is that with the empty file or can you give a code sample?

Did you define any language specific settings for ruby?
```json
			"[ruby]": {
				"editor.insertSpaces": true,
				"editor.tabSize": 2
			}
```

**Comment by jrz** [comment]
That helps thanks

I think it happens when creating a new file and then pasting some empty class. 

There’s no UI for language overrides, correct?

**Comment by aeschli** [comment]
@jrz That's right, the settings UI doesn't allow you to do that yet.

**Comment by aeschli** [comment]
Closing issue.
