### ISSUE TITLE
Telemetry: We should log startup times

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#707]
We had a severe performance regression in startup time (#335). For the future it would be cool to log the startup time via telemetry and then to see trends between versions to see if we are getting slower or better over time.

@SofianHn this would need to be done from the main side I guess because you dont want to log it for each window open. We already have the starting time stored here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/bootstrap.js#L9

@egamma @alexandrudima fyi we talked about it

**Comment by alexandrudima** [comment]
@bpasero 
But the regression in start-up time was in the renderer side, (on each window open), so I don't think logging from the main process would have helped discover it sooner. Logging the startup time of the main process would also be useful.

**Comment by bpasero** [comment]
@alexandrudima sorry I was not clear: yes, we must log all the time it takes until the first workbench window is up and running. what I meant is that this logging code should live on the main side and not renderer side because only main side knows when the first window is opening!

**Comment by bpasero** [comment]
@SofianHn I added event name `startupTime` and value `{ ellapsed: number }`. We should hook this up to our dashboard after releasing.

**Comment by SofianHn** [comment]
@bpasero thanks! I will add that to the dashboard.
