### ISSUE TITLE
Scrolling in TreeView jumps to current selection

### ISSUE THREAD

**Issue by jhuels** [microsoft/vscode#70707]
- VSCode Version: 1.31.1
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1.  Active the window pane the TreeView exists in
2.  Select a node
3.  Send an event to update the node
4.  Scroll jumps back to current selection

Does this issue occur when all extensions are disabled?: N/A

If the text/code window is active instead of the pane with the TreeView, the scroll does not jump and events update the display on each node correctly.

This issue is specifically evident in the test explorer extension:
https://github.com/hbenl/vscode-test-explorer/issues/46
![image](https://user-images.githubusercontent.com/40254454/54559688-d3859f00-497d-11e9-905e-097ca8f5cdd9.png)

**Comment by sandy081** [comment]
@jhuels May I know which node you are updating? is it a node with or without children?

**Comment by jhuels** [comment]
Typically it is a node without children (a leaf).  I don't have an easy way to test with children without making some customization.  Even if the parent node is collapsed, the jumping still occurs.

**Comment by hbenl** [comment]
To reproduce:
* install Mocha Test Adapter
* create a project with a file `test/test.js` with the following contents:
```
describe('Suite', function() {
    for (let i = 0; i < 100; i++) {
        it(`Test #${i}`, async function() {
            await new Promise(resolve => setTimeout(resolve, 100));
        });
    }
});
```
* in the Test Explorer click on the suite so that the tests are shown
* scroll down in the list of tests
* start a test run

Sometimes the Test Explorer now jumps to the top of the list of tests (so that the suite is shown). Interestingly, this doesn't happen for me on every test run, it seems to happen on every second test run. Maybe it depends on what part of the UI had focus before the test run was started(?)

**Comment by connorshea** [comment]
This also effects my test explorer, it seems like it might jump based on the currently focused (e.g. when you collapse/expand a group of tests, that group is focused) group? https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-ruby-test-adapter

**Comment by eamodio** [comment]
I think #72617 is basically the same as (or very similar to) this issue.

**Comment by sandy081** [comment]
Yeah both seems related

**Comment by sandy081** [comment]
@joaomoreno Is it possible to avoid revealing the selected element on refresh/update?
--

**Comment by joaomoreno** [comment]
> @joaomoreno Is it possible to avoid revealing the selected element on refresh/update?

The tree doesn't do that by default. Put a breakpoint on the reveal call and check who's doing that call.

**Comment by eamodio** [comment]
Thank you!!!

**Comment by misolori** [comment]
Verified

<img width="80%" src="https://user-images.githubusercontent.com/35271042/62252247-28630880-b3a7-11e9-8d41-96e5c8616f0e.gif" />
