### ISSUE TITLE
[sass] Warning for 'display: inline-block' as if it is 'display: inline'

### ISSUE THREAD

**Issue by ipassynk** [Microsoft/vscode#7070]
- VSCode Version:0.10.8
- OS Version: windows

Steps to Reproduce:

1. SASS file:
  .state-actions {
    display: inline-block;
    float: right;
    margin-right: 20px;
  }
2. Warning is displayed:
"Property is ignored due to the display. E.g. with 'display: inline', the width, height, margin-top, margin-bottom, and float properties have no effect
Specifies how a box should be floated. It may be set for any element, but only applies to elements that generate boxes that are not absolutely positioned."

**Comment by StfBauer** [comment]
Should be fixed please. ;)
Still exists in Version 1.3.1.

**Comment by aeschli** [comment]
According to http://csslint.net/about.html, display: inline-block should not use float.
I will improve the hover message
