### ISSUE TITLE
Lost href and create another path by itself

### ISSUE THREAD

**Issue by felhur** [Microsoft/vscode#70709]
since last update,  I have loss my href paths, for example I got this line, and if I Clikc with the control KEY it have to open the link, but it does not.

"<a href="pages/contact.html""

a dropdown box appears to say "Unable to open 'contact.html': File not found (file:///d:/Pipe/Documents/Programación/Workspace/nettec/pages/pages/contact.html). It seams to look and create another "pages" subdirectory inside of the original directory that all the "htmls" belong to. Why? If my Original path was (file:///d:/Pipe/Documents/Programación/Workspace/nettec/pages/contact.html)

**Comment by aeschli** [comment]
@octref Did we change with resolving refs?

**Comment by octref** [comment]
We didn't change resolving refs. @felhur Where's the file that contains the href located?

- If it's like `.../nettec/pages/something.html`, then `pages/contact.html` resolves to `.../nettec/pages/pages/contact.html`

**Comment by felhur** [comment]
HI,
Where's the file that contains the href located? the file it's containned and allways have been containned at .../nettec/pages/something.html, but now it's trying to resolve to another /pages subdirectory inside of /.../nettec/pages. Sorry but It has not to working like that, becouse, before updates allways works with the original path (.../nettec/pages/something.html) and NOT (.../nettec/pages/pages/something.html).

**Comment by octref** [comment]
If you want to resolve to `.../nettec/pages/contact.html` in `.../nettec/pages/something.html`, then use `./something.html`. `pages/contact.html` resolves correctly to `.../nettec/pages/pages/something.html`.
