### ISSUE TITLE
problem in opened folder section

### ISSUE THREAD

**Issue by pitkusharma** [Microsoft/vscode#70706]
Issue Type: <b>Bug</b>

usually i opens a folder and starts my work . but when i open a file it should be open in a new window but its opening in the same window.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.8
php-intellisense|fel|2.3.10
vscode-icons|vsc|8.3.0

(1 theme extensions excluded)

</details>

**Comment by jasperpilgrim** [comment]
Single-clicking a file via the Explorer causes it to open in preview mode, and tabs in preview mode are reused. Editing or double-clicking the file (either via the Explorer or the tab title) will dedicate a tab for that file.

Alternatively, you can enable/disable this behavior by looking for the following in your settings:

* `workbench.editor.enablePreview` to globally enable or disable preview editors.
* `workbench.editor.enablePreviewFromQuickOpen` to enable or disable preview editors when opened from quick box/quick open.

**Comment by ashisalokhe** [comment]
Here is a workarround, the file that you are currently working on make some unsaved changes like space and then open new file.
:)
