### ISSUE TITLE
disable tooltips, plz, disable them ALL

### ISSUE THREAD

**Issue by Asitis** [Microsoft/vscode#70708]
I'm on the verge of going back to SublimeText because VSCode seems the need to throw tooltips in my face everywhere I look, constantly.
I've collected ALL the possible markups for the configuration file, including the "unofficial" `"editor.hover": false`. Nothing works, it still feels the urge to tell me what a css property is and what "background-color" means. I'm getting seriously fed up with it. 
The sheer amount of popups are getting in the way of my productivity. Some popups includes links to external sources, and more then once I try to click anywhere in my code and get sent to some page I don't give a crap about. 

It is starting to feel like an adware program in this behavior.
So. I ask again, as thousands of others before, and I know there are hundreds more of these similar posts all across the web. Maybe, do something about it?

I would LOVE. No, I NEED a way to disable ALL tooltips. I don't care if it breaks "functionality". Functionality requiring tooltips has no reason to exist in a code editor as far as I'm concerned.
Anyone has a "2019-workaround"? Thaaanks!

**Comment by usernamehw** [comment]
Hover setting name is `editor.hover.enabled`, not `editor.hover`

Also, there's `editor.hover.delay`.
