### ISSUE TITLE
TerminalOptions.shellArgs should accept `string` on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#70716]
In order to align it with how tasks and the `terminal.integrated.shellArgs.windows` setting work.

**Comment by jrieken** [comment]
@dbaeumer Is this something that would also apply to [`ShellExecution#shellArgs`](https://github.com/Microsoft/vscode/blob/199461e1ec6b0d2cdce78af3f6c91b7b73ef67ba/src/vs/vscode.d.ts#L5050). Is this a different thing despite the same name?

**Comment by dbaeumer** [comment]
@jrieken I would say we are OK here. The shellArgs are on `ShellExecutionOptions` to define args for the shell itself. The actual ShellExecution has a `command: string` or `args: string[]` to support a single command line. In the terminal this is one setting and therefore supports a string.
