### ISSUE TITLE
Nested submodules break git GUI

### ISSUE THREAD

**Issue by dmcilvaney** [Microsoft/vscode#70712]
Issue Type: <b>Bug</b>

Adding a submodule, which itself contains additional submodules, causes the git GUI to fail reporting "No source control providers registered". The git CLI continues to function as expected. Looks to be independent of issue #37947.

Expected result: Git GUI shows  at least the root repository and first layer of submodules (nested submodules would be nice to have, but preserving existing functionality would be sufficient)

Repro using the OpenSSL repo (it is not unique to OSSL however). Tested using WSL/bash.
```bash
#Create folder and open it in VSCode
mkdir submodule_issue_repro; cd submodule_issue_repro; code .
#Create git repo and add 1st layer submodule
git init
mkdir external; pushd external; git submodule add https://github.com/openssl/openssl.git; popd
git status

#VSCode git GUI is available and agrees with git CLI, shows the first layer submodule
```
```bash
#Initialize the second layer of submodules
pushd external/openssl; git submodule init; git submodule update; popd
git status

#VSCode git GUI will now show "No source control providers registered".
```

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.18859

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (19.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
line-endings|ste|1.0.3

</details>

**Comment by joaomoreno** [comment]
Can you test this using Git for Windows, which is the only one we support?

**Comment by dmcilvaney** [comment]
Worked with Git for Windows with some caveats (on the Git side).

We usually run with bash as our default terminal, and a repo modified via the bash terminal in VSCode does not work since there seems to be an incompatibility between git on bash, and git for Windows.

It apears that if the submodules are added from Git for Windows both bash and Windows can get status successfully, but if the submodules are added from bash, git status fails in Windows (hence breaking VSCode).
