### ISSUE TITLE
Visual Studio Code freezes

### ISSUE THREAD

**Issue by kofifus** [Microsoft/vscode#70718]
I am opening this issue becasue https://github.com/Microsoft/vscode/issues/60467 was closed for no reason.

Visual Studio Code occasionally freezes for 10-30 seconds or more
This happens on my machine about once every 1-3 days.
Once this happens it will usually then reoccur very frequently (every few minutes) until I reboot my machine.
I get no visual feedback during the freeze
Once it unfreezes any keyed I pressed while frozen are played

I get this on both the official version and on the latest insiders
I only use one extension - overtype (https://marketplace.visualstudio.com/items?itemName=adammaras.overtype)

CPU and memory load while this happens is low
restarting chrome does not help
closing all other programs does not help
--disable-gpu does not help
setting git.enabled: false does not help
setting git.autorefresh: false does not help

This is an ongoing issue for myself and others and there are many reports (see closed issue above)

What can be done ?
Is there any way for me to debug this ? as the freezes are relatively long is there anyplace I can look to see what VS Code is doing that may be freezing it ?

**Comment by bpasero** [comment]
@kofifus is that always on the same workspace with the same folder? Does it reproduce when you disable all extensions?

**Comment by kofifus** [comment]
I only use one extension - overtype (https://marketplace.visualstudio.com/items?itemName=adammaras.overtype)


I usually work on a single javascript workspace so it's hard to tell about different workspaces.

**Comment by bpasero** [comment]
Yeah it is also hard for me to understand how this is triggered. Can you try help?

**Comment by kofifus** [comment]
One thing I noticed which may or may not be relevant is that if I run Sysinternals ProcessMonitor I see that VS code is conterminously accessing many files in my workspace even when they are not opened in the editor (the workspace is very big but I usually only have 4-5 files opened.

This 'scanning' goes on also while the editor freezes.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by kofifus** [comment]
Here is a screenshot of `"Code - Insiders.exe" --status` while the editor is hanging.

Today it's the worst yet, VScode is pretty much unusable ATM and causing me a lot of grief :(

![image](https://user-images.githubusercontent.com/3926071/55199771-43faae80-520f-11e9-9942-539f2e4e866e.png)

**Comment by kofifus** [comment]
And is a screenshots from the profiler while hanging:

![image](https://user-images.githubusercontent.com/3926071/55200808-12381680-5214-11e9-85bf-a2681a5e60e5.png)

Seems like the culprit is OnigScanner.findNextMatchsync ??

**Comment by alexandrudima** [comment]
@kofifus This indicates that the slow-down is in tokenization. This means that there is something specific about a file that you open which triggers this slow-down. Can you please share with us the file that you open and which causes the slow-down?

**Comment by kofifus** [comment]
These are just plain ES6 javascript files nothing fancy .. I will ask for permission to share them but there is nothing special there (It would be easier to PM them)

**Comment by alexandrudima** [comment]
Thank you.
