### ISSUE TITLE
Debugging: Key binding for »run to cursor« (+ ignoring breakpoints)

### ISSUE THREAD

**Issue by hoehrmann** [Microsoft/vscode#70715]
In Visual Studio you can (or used to be able to) use `CTRL+F10` to do what vscode calls »run to cursor« for which there is currently no key binding in vscode. That should be added, and it would be very nice if there was the option, through context menu and a different key combination, to »run to cursor« **while ignoring other breakpoints**.

**Comment by isidorn** [comment]
Just add a keybinding to it
Preferences > keyboard shortcuts
![Screenshot 2019-03-19 at 14 45 34](https://user-images.githubusercontent.com/1926584/54610621-adcbc900-4a55-11e9-841f-1fdbd056c07e.png)
