### ISSUE TITLE
Renaming not opt-out or missing setting

### ISSUE THREAD

**Issue by theklr** [Microsoft/vscode#70714]
![Screen Shot 2019-03-18 at 3 04 48 PM](https://user-images.githubusercontent.com/6653320/54566870-52cf9e80-498f-11e9-9881-c8dffb9736d8.png)
![Screen Shot 2019-03-18 at 3 04 41 PM](https://user-images.githubusercontent.com/6653320/54566871-52cf9e80-498f-11e9-8168-720231af2424.png)

Issue Type: <b>Bug</b>

In previous versions I have been able to rename properties  in my files and it would replace the name. In recent updates it creates an alias that I cannot opt out of in the settings. Is there any way I can force disable this feature

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.76GB free)|
|Process Argv|-psn_0_3724173|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
ejs-language-support|Qas|0.0.1
sharecode|Rol|0.4.1
indenticator|Sir|0.6.0
Bookmarks|ale|10.3.0
jenkins-status|ale|3.1.1
project-manager|ale|10.4.0
vscode-css-modules|and|1.1.1
react-pure-to-class-vscode|ang|1.1.8
cform|aws|0.0.15
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
vscode-yarn-script|car|0.0.1
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.3
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
language-postcss|cpy|1.0.5
vscode-eslint|dba|1.8.2
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.3
prettier-vscode|esb|1.8.1
vscode-todo-plus|fab|4.13.0
shell-format|fox|4.0.4
webpack-4-snippets|fwg|0.0.3
vscode-yarn|gam|1.6.0
css2react|got|0.0.6
gc-excelviewer|Gra|2.1.29
react-jest-vscode-snippets|jal|0.0.3
jenkins-declarative-support|jmM|0.1.0
svg|joc|0.1.4
sublime-babel-vscode|jos|0.2.10
vscode-styled-components|jpo|0.0.25
contextualduplicate|laf|0.2.0
vscode-smart-column-indenter|lmc|0.0.13
lambda-snippets|log|1.0.0
aws-cli-configure|mar|0.3.0
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.12
vscode-autoprefixer|mrm|2.2.0
vscode-postcss-sorting|mrm|3.0.1
vscode-azureterraform|ms-|0.2.2
azure-account|ms-|0.8.0
vsliveshare|ms-|0.3.1326
debugger-for-chrome|msj|4.11.3
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.6.0
vscode-versionlens|pfl|0.22.0
vscode-gitignore-generator|pio|1.0.1
cf-templates|pra|0.1.1
seti-icons|qin|0.1.3
diff|raf|0.0.1
vscode-yaml|red|0.3.0
postcss|ric|2.0.0
vscode-sort-json|ric|1.13.0
partial-diff|ryu|1.4.0
jenkinsfile-support|sec|0.1.0
vscode-sql-beautify|sen|0.0.4
stylelint|shi|0.48.0
css-auto-prefix|spo|0.1.7
guides|spy|0.9.3
vscodeintellicode|Vis|1.1.4
vscode-icons|vsc|8.3.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
local-history|xyz|1.7.0
markdown-all-in-one|yzh|2.1.1
vscode-open-in-github|ziy|1.3.6

(4 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Try setting `"javascript.preferences.renameShorthandProperties": false` and `"typescript.preferences.renameShorthandProperties": false`

**Comment by mjbvz** [comment]
Also, this requires VS Code 1.33 (the current [VS Code insiders build](https://code.visualstudio.com/insiders/) build)
