### ISSUE TITLE
Crash in webview render process when webview creates a web worker.

### ISSUE THREAD

**Issue by jacdavis** [microsoft/vscode#70711]
I have created a minimal webview project repro which is enclosed. The problem occurs when a webview creates a webworker. This is a regression from a few months ago. 

1) Open the enclosed webview project in vscode
2) npm install
3) Hit f5
4) Open webview in second instance
[repro.zip](https://github.com/Microsoft/vscode/files/2980419/repro.zip)
 (it's the coding cat example project)

EXPECTED: coding cat shows numbers
ACTUAL: webview turns black and does nothing

Note that the webview creates an iframe to allow for the web-worker script to load in the vscode-resource context.

**Comment by mjbvz** [comment]
This is most likely a problem with electron/chromium, not with VS Code itself

We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). Could you please try one of these builds? Downloads:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by mjbvz** [comment]
Closing this as an upstream issue. This could be https://github.com/electron/electron/issues/19150.  

It'd help if you could create a minimal electron repo of this issue and file that against electron
