### ISSUE TITLE
Changing the flow of selecting a block

### ISSUE THREAD

**Issue by kaba2** [Microsoft/vscode#70720]
The current flow for block selection in VSCode is as follows:
1. Move the mouse over the first corner of a block selection. 
2. Click left mouse button.
3. Hold a key (Ctrl+Shift).
4. Push down left mouse button.
5. Move the mouse over the second corner of a block selection.
6. Release the mouse button.

The flow for block selection in Sublime Text is as follows:
1. Hold a key (Shift).
2. Move the mouse over the first corner of a block selection.
3. Push down right mouse button.
4. Move the mouse over the second corner of a block selection.
5. Release the right mouse button.

I find the flow in VSCode hard to use compared to Sublime Text. The core of the problem is that it requires two clicks instead of one, and the two clicks must differ on whether the key is pressed or not. 

Feature request: either replace the flow with that of Sublime Text, or add an option to choose between these two flows. (What keys are used, or which mouse button is used is not of interest in this feature request.)

Note that the VSCode flow above is inconsistent with the Alt block selection introduced in the February 2019 update of VSCode, which works like the Sublime Text flow above.

**Comment by alexandrudima** [comment]
Have you seen https://code.visualstudio.com/updates/v1_32#_improved-column-selection ? That makes it possible to select normally and just press Alt to toggle between a block selection and a regular selection.

**Comment by kaba2** [comment]
@alexandrudima I addressed Alt block selection above: "Note that the VSCode flow above is inconsistent with the Alt block selection introduced in the February 2019 update of VSCode, which works like the Sublime Text flow above.". That is, there are currently two ways to perform the block selection, and I'm proposing to make the Ctrl block selection to work the same as the Alt block selection.
