### ISSUE TITLE
Not able to run the TEST from terminal after today's update.

### ISSUE THREAD

**Issue by kritulrathod** [Microsoft/vscode#70723]
**- VSCode Version:** 1.32.3
**- OS Version:** Windows 10 Home

Steps to Reproduce:

1. was using the vstest.console.exe to run the selected tests from the command line. this was 

**"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "D:\ProjectName\ProjectNameTest\bin\Debug\ProjectNameTest.dll" /TestCaseFilter:TestCategory=CategoryB /Logger:trx**

This command was working before I updated the VS Code version and restarted the VS Code.

Shows below error message.

**This app can't run on your PC 
To find a version for your PC, check with the software publisher. 
Close** 

**Does this issue occur when all extensions are disabled?:** Yes

**Also, the VS Code stops responding after a couple of attempts of running this command.**

**Comment by kritulrathod** [comment]
On further digging, I found that  vstest.console.exe for VS 14.0 works but the VS 2017 doesn't work.
See below commands.

## THIS ONE DID NOT WORK
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "D:\ProjectName\ProjectNameTest\bin\Debug\ProjectNameTest.dll" /TestCaseFilter:TestCategory=CategoryB /Logger:trx

## THIS ONE WORKS
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "D:\ProjectName\ProjectNameTest\bin\Debug\ProjectNameTest.dll" /TestCaseFilter:TestCategory=CategoryB /Logger:trx

**Comment by isidorn** [comment]
This repo is for filling issues against vscode. Not for visual studio issues

**Comment by kritulrathod** [comment]
@isidorn I am using the vstest.console.exe from VSCode. this is for running the tests within the MSBuild project for CI builds.
