### ISSUE TITLE
When typing Chinese in Visual Studio Code, the IME overlaps the pinyin I'm typing

### ISSUE THREAD

**Issue by Trannosaur** [microsoft/vscode#70728]
Issue Type: <b>Bug</b>

It only happens in the main editor; for example in this bug report dialogue it doesn't occur. It also does'nt happen every time. It occurs maybe 2/3 times for me.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
node-debug2|ms-|1.31.2
vscode-react-native|vsm|0.8.0

</details>

**Comment by shinjisr** [comment]
Having the same issue here, but it occurs all the time.

VS Code version: Code 1.33.1 (1.33.1) (51b0b28 2019-04-11T08:14:39.158Z)
OS version: macOS Mojave Version 10.14.4 
System info: 
MacBook Pro (Retina, 13-inch, Early 2015) 2.7 GHz Intel Core i5

**Comment by shinjisr** [comment]
Issue figure:
![Screen Shot 2019-04-22 at 22 11 16](https://user-images.githubusercontent.com/21114376/56511731-e92f4b00-655f-11e9-93bd-11c4159a2f0c.jpg)
![2chinese_typing_issue](https://user-images.githubusercontent.com/21114376/56511749-f2201c80-655f-11e9-9433-93b8862b81d4.gif)

**Comment by AshleyKwan** [comment]
Having the same issue here, It occurs all the time also.

VS Code version: Code 1.43.2 (1.43.2)
OS version: Windows Server 2019 (10.0.17763.379)

**Comment by stevencch99** [comment]
> Issue figure:
> ![Screen Shot 2019-04-22 at 22 11 16](https://user-images.githubusercontent.com/21114376/56511731-e92f4b00-655f-11e9-93bd-11c4159a2f0c.jpg)
> ![2chinese_typing_issue](https://user-images.githubusercontent.com/21114376/56511749-f2201c80-655f-11e9-9433-93b8862b81d4.gif)



> Having the same issue here, It occurs all the time also.
> 
> VS Code version: Code 1.43.2 (1.43.2)
> OS version: Windows Server 2019 (10.0.17763.379)

I have fixed this issue by using monospace fonts in my VS Code, hope this will help.

**Comment by Trannosaur** [comment]
That... feels like a lie: https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Abug+IME

There are no other open bugs on this.

**Comment by Trannosaur** [comment]
Having looked around it looks like VS triage has shut down every bug in this realm...  every thread has a "here are some potential dupes" (all also closed)

Here it is today, MacOS 10.15.7, 1.50.1 (and I tried it again on 1.51.0 too)

<img width="240" alt="Screen Shot 2020-11-07 at 2 17 58 PM" src="https://user-images.githubusercontent.com/291144/98434620-0ad13280-2104-11eb-8f3a-b090012b17ce.png">

I get it, non-latin is often not prioritised by devs, but this just feels like trying to hide the issue. Just accept a bug and set it low pri!

**Comment by Trannosaur** [comment]
https://github.com/microsoft/vscode/issues/85680 this one is the same issue but was closed

If it helps it is /less likely/ to occur at the top left so to repro it just type, and keep doing linebreaks

I get it 100% repro if I just type:

"hey" enter
hey enter
hey (100% repro here)
