### ISSUE TITLE
Parse ":line " in Quick Open

### ISSUE THREAD

**Issue by axdiamond** [Microsoft/vscode#70726]
Currently, typing a file name with colon and a line number into Quick Open will take you to that line in the file. This is great! 
However, ASP Core currently logs exceptions like this 

     System.Exception: Oopsie
     at Controllers.ContactController.Get(Guid id) in .\Controllers\ContactController.cs:line 44

And the Quick Open menu is unable to parse ":line 44" as a line number, so when I copy/paste the file name, the open file command is hidden. 

I would like if the Quick Open menu was able to parse this as a line number, and take me to the expected location.

**Comment by axdiamond** [comment]
I've done some digging, and it seems that currently, the regex that drives this functionality 

https://github.com/Microsoft/vscode/blob/02423d3f15f9f26b22d5784406d8c5fb283b95a3/src/vs/workbench/contrib/search/browser/openAnythingHandler.ts#L35

supports any of these test cases:

    asd.cs:231
    asd.cs:123:231
    asd.cs:123,231
    asd.cs:123#231
    asd.cs(231:231)
    asd.cs:(123#231)
    asd.cs:123#231

I was able to add in line pretty simply, so I did it and open a PR 

https://github.com/Microsoft/vscode/pull/70727

**Comment by roblourens** [comment]
Thanks for the PR! Apparently we handle this pattern in the terminal too. @Tyriar can you show me where the link detection for the terminal is because I think it would make sense to sync the cases that it supports with quickopen.

**Comment by roblourens** [comment]
Thanks for the PR! On one hand I don't want to add a ton of patterns that are sort of specific to one library or runtime but I think this makes sense and apparently we already handle this pattern in the terminal too. @Tyriar can you show me where the link detection for the terminal is because I think it would make sense to sync the cases that it supports with quickopen.

**Comment by Tyriar** [comment]
@roblourens I'd recommend against copying all the patterns the terminal supports as it's super complicated, [I want remove regexes from the system](https://github.com/xtermjs/xterm.js/issues/583) and it supports formats which should only work in the terminal imo such as `"(file path)", line 45`

https://github.com/Microsoft/vscode/blob/d25ea61e0cdfef641b31deca1858af997ed8d5d4/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L36-L44

**Comment by roblourens** [comment]
Ok. Thinking about it some more, I don't really think we should have that kind of fuzziness in quick open. We will start adding more patterns it will end up very complicated.

However, an extension could show an input and handle whatever patterns they want!
