### ISSUE TITLE
Set color theme issue

### ISSUE THREAD

**Issue by athulrs** [Microsoft/vscode#70730]
Issue Type: <b>Bug</b>

Apply theme doesn't work anymore, after last update.
The features "set color theme" in the extension menu is crashing it seems, sending out a error message in vs screen notification panel as "Cannot read property 'id' of undefined".

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.13.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.66GB (1.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
indenticator|Sir|0.6.0
gitlens|eam|9.5.1
vscode-autoprefixer|mrm|2.2.0
python|ms-|2019.2.5558
atom-keybindings|ms-|3.0.6
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Can you ioen the dev tools (`Help > Toggle Dev Tools`) and copy the full stack trace and paste it here?
What is the name of the extension you use `Set Color Theme` on?

**Comment by athulrs** [comment]
"settings.json" was overwritten by a fellow teammate and pushed along, caused this error to occur while triggering my theme from the extensions.
Sorry, for the trouble caused.
