### ISSUE TITLE
The interface problem

### ISSUE THREAD

**Issue by baobz** [Microsoft/vscode#70732]
Please look at pictures:
https://upload-images.jianshu.io/upload_images/4221632-4b8bde271cb2550d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

Long page stay appear interface confusion. Occasionally appear problem, specific how to operate to appear this kind of phenomenon, I am not clear. This is the second time this has happened to me

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Please file with nice reproducable steps and include a picture in the issue. The current one I can not access.
These are horrible steps you provided.
Thanks

**Comment by baobz** [comment]
> Please file with nice reproducable steps and include a picture in the issue. The current one I can not access.
> These are horrible steps you provided.
> Thanks

I'm sorry, I can't provide more information. It has a chance, maybe can according to the bug that where the problem is, maybe the plugin is the problem. Restart vscode and the problem is gone. See if anyone else has the same problem.

**Comment by isidorn** [comment]
Thanks. Closing for now then.
