### ISSUE TITLE
[Feature Request] - Save extension and themes as a Favorite

### ISSUE THREAD

**Issue by SirTwsted** [microsoft/vscode#70738]
I would like to be able to set both extensions and Themes into a favorites list.
and then be able to view that entire list 
A. Favorite Extensions List
B. Favorite Themes List

This way people can their favorites , specially when it comes to themes,
so people don't have the scroll through an entire list of themes but instead 
scroll through their favorites themes list and select the one they want that week or day to use  :D

**Comment by sandy081** [comment]
Related to https://github.com/Microsoft/vscode/issues/68527

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/103391
