### ISSUE TITLE
Support inserting touchbar icons between existing debug buttons

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#70737]
If you try to insert a touchbar button between the debug buttons like this:

```js
{
	"command": "flutter.hotReload",
	"when": "dart-code:flutterProjectLoaded && inDebugMode && debugType == dart",
	"group": "9_debug@4"
},
```

The dividing line vanishes:

<img width="1085" alt="Touch Bar Shot 2019-03-19 at 8 36 09 am 1" src="https://user-images.githubusercontent.com/1078012/54591469-33ce1c80-4a22-11e9-85a6-e5a8db96caa2.png">

The existing buttons numbers are 4, 5, 6, etc. - whereas for the debug toolbar they're 40, 50, 60. I don't know if adding zeros would fix this (since I wouldn't use the exact same number). I did try 49 anyway, but it appeared in the wrong place.

Since it's possible to fit buttons between them in the debug toolbar, it'd be nice if the same thing could be replicated here to avoid buttons in different orders.

I know it looks awful as text, but the plan is to replace it with an icon (see #70735) to match the toolbar.

**Comment by DanTup** [comment]
Actually, the above works correctly if I use an icon (png) and make it exactly 60x60. If it's bigger than that the button ends up wide (even though the proportions are the same) and if it's text, the separator does not appear.

So, possibly this is fine - however I think it'd be better if the numbers were extended to make it more obvious where the buttons will go. I'm using `9_debug@4` but it's not obvious whether it'll come before or after the built-in `9_debug@4`.

**Comment by isidorn** [comment]
Glad that it works.
I will not change the order since it might break other extensions and I do not want to get into that
