### ISSUE TITLE
Icons not working on touchbar

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#70735]
According to https://github.com/Microsoft/vscode/issues/35641, icons should appear in the Touch Bar (that issue is about allowing them to be overridden from the command). However, in my testing this doesn't work... I have a command that has icons:

```js
{
	"command": "flutter.hotReload",
	"title": "Hot Reload",
	"category": "Flutter",
	"icon": {
		"dark": "media/commands/hot-reload.svg",
		"light": "media/commands/hot-reload.svg"
	}
},
```

And it shows up fine on the debug toolbar:

![Screenshot 2019-03-19 at 8 06 41 am](https://user-images.githubusercontent.com/1078012/54590017-13509300-4a1f-11e9-822a-1dbfef5a6a3c.png)

However it just shows up as text in the Touch Bar:

<img width="1085" alt="Touch Bar Shot 2019-03-19 at 8 16 13 am" src="https://user-images.githubusercontent.com/1078012/54590187-6296c380-4a1f-11e9-821b-7d458cb0d4d4.png">

I can't find any solid information on whether this is intended to work or not, only that other issue which shows a screenshot of it working.

**Comment by isidorn** [comment]
@bpasero I was not aware that we have made the touch bar menu contributable.
Might you know why the icons do not apear for Dan? I know that you had to change these icons a while back, do they require some special format?

**Comment by bpasero** [comment]
Only PNGs work!

**Comment by DanTup** [comment]
@bpasero Aha, I'll give that a go! Is that documented anywhere (I did look, but [couldn't find much](https://github.com/Microsoft/vscode-docs/issues/2424) on the Touch Bar).
