### ISSUE TITLE
explorer menu indenttation

### ISSUE THREAD

**Issue by Sharma121** [Microsoft/vscode#70733]
Issue Type: <b>Feature Request</b>

please provide little more indentation on explorere file just like sublime or netbeans sometime i have been lost if project is big . otherwise i love it

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

**Comment by isidorn** [comment]
Please use this setting to configure indendation to whatever you like
`workbench.tree.indent`
