### ISSUE TITLE
Code action to implement unimplemented members

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7073]
I don't think we do this yet, I want the editor to go and implement the missing members of abstract classes/interfaces at the press of a button.

![image](https://cloud.githubusercontent.com/assets/2193314/15685016/adacefb0-271e-11e6-8338-a03d44b81abf.png)

**Comment by mjbvz** [comment]
The implement interface code action, plus many others, is now in TypeScript 2.2. You can start testing this today by installing `typescript@next` and pointing your `"typescript.tsdk"` setting to it:

![jan-04-2017 17-05-56](https://cloud.githubusercontent.com/assets/12821956/21665206/16476424-d2a0-11e6-91c6-5e33e7692519.gif)

We will be picking up the final release of TS 2.2 in VSCode 1.10+

Note that #18135 is needed to properly format some of these quick fixes as shown above. I plan on taking that PR into VSCode 1.9

**Comment by maxcan** [comment]
Is this available in 1.9.x?  I can't seem to trigger it with TS 2.2.1 and `"typescript.tsdk": "./node_modules/typescript/lib"
`

Looking forward to this, will love it.

Great work as always guys!

**Comment by nbransby** [comment]
What about anonymous implementations via an object literal?
