### ISSUE TITLE
explorer show/hide button function functionality

### ISSUE THREAD

**Issue by Sharma121** [Microsoft/vscode#70734]
Issue Type: <b>Feature Request</b>

it would be great if vs code have buttton function just like atom have just click it and all your files are displayed

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

**Comment by isidorn** [comment]
Just click on the activity bar on the left on the explorer and all the files will be hidden / shown
