### ISSUE TITLE
Freezes system on Win + Shift + Left/Right Arrow

### ISSUE THREAD

**Issue by chatny** [Microsoft/vscode#70739]
1. Settings: see attached file
2. VS code is in fullscreen mode
3. Push the fullscreen to a different monitor by pressing Win + Shift + Left/Right Arrow key
4. The system freezes, the only way I could get out of it was a hard system reset

Sending the bug report from my working machine, but also reproduced it on my personal one. While I was writing this report I tested out if the issue happens and I am writing my report again.
The mouse remains responsive that the cursor changes, but the whole system is stuck. Can't open anything, do anything, except a hard reset, which of course solves the issue. 

I haven't been using this shortcut a long time, but since 1.32.1 -> till the newest I have issues.

Attached the current settings I am running.
[settings.txt](https://github.com/Microsoft/vscode/files/2982380/settings.txt)

CPUs | Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 31.92GB (21.54GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
vscode-firefox-debug | hbe | 1.7.7
vscode-typescript-tslint-plugin | ms- | 1.0.0
debugger-for-chrome | msj | 4.11.3
sort-lines | Tyr | 1.8.0

Thanks.
Have a nice day.

**Comment by chatny** [comment]
Update:
1. When VS Code is running and you are able to push the editor to another monitor, it doesn't occur.
2. When you start up VS Code and don't wait until you can see the content of opened files, and push it to other monitors, the system freezes. (it may happen on the second try)
3. Logging off the user solves the freeze issue. (I managed not to hard reset the system, the power button is set to sleep in windows power options, after that the system was unfrozen)

**Comment by chatny** [comment]
With opened task manager:
Even the task manager is frozen during the freeze. No CPU or Memory spike noticed. The only thing that peaked was the Power usage of VS Code.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by chatny** [comment]
Reproduced on the exploration build. Opened folder, fullscreen VS Code, pushed with Win + Shift + Left/Right Arrow Key -> the system froze, after 3-4 switches between monitors.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by chatny** [comment]
[Code__PID__17492__Date__03_19_2019__Time_02_45_54PM__40__Log.txt](https://github.com/Microsoft/vscode/files/2983637/Code__PID__17492__Date__03_19_2019__Time_02_45_54PM__40__Log.txt)

**Comment by bpasero** [comment]
@chatny a few more questions:
* what does this mean: "When VS Code is running and you are able to push the editor to another monitor, it doesn't occur". what does it mean to be able to push the editor?
* does it reproduce if you configure `window.titleBarStyle: native`?

**Comment by chatny** [comment]
**what does this mean: "When VS Code is running and you are able to push the editor to another monitor, it doesn't occur". what does it mean to be able to push the editor?**
Bad choice of words, I thought the issue occurs, when I move the editor to another screen before I allow the content being visible, but that's not the case. (there is an interval of 1-2 seconds, when VS code is just loading) Push is also not the best word -> move the editor to another screen
Just to clarify: when VS Code is not in fullscreen, I can move the window without freezing

**does it reproduce if you configure window.titleBarStyle: native?**
Yes, It froze. At least I am able to unfreeze by sleeping the machine.

**Comment by bpasero** [comment]
@sbatten do you have a multi-monitor windows setup where you could maybe try to reproduce?
