### ISSUE TITLE
Editor Format On Save messing up paragraph

### ISSUE THREAD

**Issue by bebotette** [Microsoft/vscode#70746]
Issue Type: <b>Bug</b>

I have a very simple startup html boilerplate document. Considering I only add <p>sample 3 or 4 lines of paragraph </p>, when I hit save, those lines of paragraph go crazy with some random lines breaking up. The change is also undoable. So I know something is doing it, like an extra step.

I also tried disabled 'beautify' extension. Restarted VScode. Still the same issue.
Also with Whiteviz. Did same thing. Still same issue.
Disabled both. Restarted. Still same issue.

yes, I have ticked the checkbox on 'Editor: Format on Save' because that's a required step for me to maximize the said extensions. So if I untick this option, I don't have this issue, but I can't maximize the extensions mentioned.

I think that 'Editor: Format on Save' is the real bug.

See the problem in action:
http://recordit.co/DIfsVIRTIq

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
beautify|Hoo|1.4.9
vscode-autoprefixer|mrm|2.2.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.6.3
vscode-css-peek|pra|2.2.0
LiveServer|rit|5.5.1
whiteviz|spy|0.6.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> So if I untick this option, I don't have this issue, but I can't maximize the extensions mentioned.

Please file this issue against the extension. VS Code is more or less applying what it returns
