### ISSUE TITLE
On ubuntu, Closes previous workspace on new window

### ISSUE THREAD

**Issue by ashisalokhe** [Microsoft/vscode#70741]
Issue Type: <b>Bug</b>

Steps to reproduce,
On ubuntu go to File -> New Window

In new Window Got File -> Open Folder
and then open a folder, the new folder is opened in old visaul studio and new window stays as it is.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1584)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 1|
|Memory (System)|7.71GB (0.24GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
It sounds like you're trying to open the same folder in multiple windows which is why the first window is opened again? We only let you open the same folder in multiple windows if the window is converted to a workspace, see https://code.visualstudio.com/docs/editor/multi-root-workspaces
