### ISSUE TITLE
[Feature request] Show errors/warnings in 'pinnable' panel

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/vscode#7074]
Due to this issue: https://github.com/Microsoft/vscode/issues/7033

I would like to have a pinnable error/warnings dialog on the bottom/top/whatever side.

Thank you for not moving this feature request to 2017 :-)

**Comment by jrieken** [comment]
work has already started

**Comment by sandy081** [comment]
duplicates #6679 

Please refer or follow #6679 for more updates
