### ISSUE TITLE
extension config should consider  different operating systems

### ISSUE THREAD

**Issue by Southhill** [Microsoft/vscode#70743]
VS code version: 1.32.2
OS version: windows 10
---
feature description：
**Because:**
I use sync-setting extension, but sync config have a little problem.
for example, the **markdown-pdf** extension require chrome runtime. chrome file path setting to `markdown-pdf:executablePath` key, but different systems have different file path, so sync-setting extension synced the value of `markdown-pdf:executablePath` key is invalid. there are many similar config key of plugins：`gitProjectManager.baseProjectsFolders` path，`prolog.executablePath` path,
`terminal.integrated.shell.windows` path, and so on.
**So:**
I think the question have two solution.
one, extension author coding related config path, add multiple path configuration items，take markdown-pdf extension as an example, the config relate path：
```json
{
   "win32ExecutablePath": "C:\\application\\chrome.exe",
   "linuxExecutablePath": "/usr/bin/chrome",
   "osxExecutablePath": "/usr/bin/chrome"
}
```
two. vscode provide built-in support, detail: extension author declare the config item:`runTimePath` to FilePath type. vscode mapping to filePath Object for the value `runTimePath` config item that user input to setting UI interface.
filePath Object example:
```json
{
   // os type: Specific path
   "win32": "C:\\application\\xx.exe"
}
```
Everything for the sync-setting. 
End

**Comment by Southhill** [comment]
label should add to sync-setting.

**Comment by sandy081** [comment]
Please file issue against https://github.com/shanalikhan/code-settings-sync/issues
