### ISSUE TITLE
integrated terminal: cursor blinking dosen't work with render type dom

### ISSUE THREAD

**Issue by yukulele** [microsoft/vscode#70749]
- VSCode Version: 1.32.3
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. use that in settings
```json
{
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.rendererType": "dom"
}
```
2. open integrated terminal

→ cursor is not blinking

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1977

**Comment by roottool** [comment]
I'm trying to resolve this issue.
My recognition is that this issue resolves by updating `vscode-xterm` using xtermjs/xterm.js#1979 and xtermjs/xterm.js#2039.

I created Microsoft/xterm.js#1 which is PR to update `vscode-xterm`.
@Tyriar, please check it when you have time.
