### ISSUE TITLE
When not in a folder File-N/Ctrl-N creates a new file but Command palette-new file displays "Open a folder first to create files or folders within."

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [Microsoft/vscode#7075]
- VSCode Version:1.1.1
- OS Version: Windows 7 Enterprise

I always keep a VS Code window open for creating random one off snippets of code that I never save. If i have something larger in one file I like to create a new temporary file and use it. I have always used the command palette to do this but since updating VSCode it no longer works. Instead I get an info-bar that says `Open a folder first to create files or folders within.`

Was this functionality intentionally restricted? If so, why? It seemed to work perfectly fine before.

**Comment by bpasero** [comment]
@ZombieProtectionAgency please use `New Untitled File` from the command palette. The other action really needs an opened folder.
