### ISSUE TITLE
Automatically modified my files and all content was deleted

### ISSUE THREAD

**Issue by vinay1702** [Microsoft/vscode#70750]
- VSCode Version: 1.32.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. I was repeatedly writing code in another file and its in auto save. Suddenly I got error in nodejs that file is not found and there is file but when I open its all cleared.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@vinay1702 sorry to hear that, can you reproduce this issue somehow?

**Comment by jyakaranda** [comment]
encountered same problem, my source code was also deleted while I was trying to save, really sad
