### ISSUE TITLE
Source Control panes are resized unexpectedly

### ISSUE THREAD

**Issue by Maximus5** [Microsoft/vscode#70757]
Issue Type: <b>Bug</b>

When I switch to "Source Control" (Ctrl+Shift+G) the height of pane with changes becomes low unexpectedly.

To repro
1. Ctrl+Shift+G, resize panes equally or make lower pane longer than upper one
2. Ctrl+Shift+E
3. Ctrl+Shift+G, observe the bug, height of upper pane (Source control providers) becomes much larger.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 3189)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.55GB (0.88GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.3.0
xml|Dot|2.4.0
json-tools|eri|1.0.2
vscode-highlight|fab|1.3.4
todo-tree|Gru|0.0.125
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
vscode-docker|Pet|0.6.1
incremental-search|sie|0.2.1

</details>

**Comment by joaomoreno** [comment]
This has been fixed in the latest [insider release](https://code.visualstudio.com/insiders).
