### ISSUE TITLE
Kubuntu, unable to increase max inotify watchers

### ISSUE THREAD

**Issue by mcarpenterjr** [Microsoft/vscode#70754]
Version: 1.33.0-insider
Commit: 73ccd28be6b94b8965b65e6f187689dca7c30805
Date: 2019-03-18T06:13:57.622Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32

OS: Kubuntu 18.04
KDE Plasma Version: 5.12.7
KDE Frameworks Version: 5.44.0
Qt Version: 5.9.5
Kernel Version: Linux x64 4.15.0-46-generic
OS Type: 64-bit

Steps to Reproduce:

1. Open an instance of VS Code Insiders
2. VSC Insiders Alerts to unable to watch files.
3. Implement the fix listed here; [Visual Studio Code is unable to watch for file changes in this large workspace](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)
4. Do `sudo sysctl -p` as instructed from above, and get `sysctl: cannot stat /proc/sys/fs/notify/max_user_watches: No such file or directory`

I know this is more of an OS issue than a VSC issue.

**Comment by Tyriar** [comment]
Not sure we can help with this, it works for us and it look like a problem with either Kubuntu or your specific setup.

**Comment by mcarpenterjr** [comment]
That's what I figured, just wanted to verify. I've upgraded Kubu from 18.04 to 18.10 and it seems to have fixed whatever was misconfigured.

18.04 was using `notify`, 18.10 uses `inotify` astonishingly it all panned out.
