### ISSUE TITLE
Reopening VS Code from Windows Explorer via right-click results in lost previous session

### ISSUE THREAD

**Issue by DoCode** [Microsoft/vscode#70755]
Issue Type: <b>Bug</b>

## Steps to reproduce

1. Open VS Code
2. Open one existing document
3. **_Optional:_** Open a new tab or new window with a new tab and type anything and do NOT save this new file
4. Close VS Code
5. Re-Open VS Code
6. **Now all tabs are correctly restored!**
8. Close VS Code
7. Open a File from Windows Explorer with right-click and open in VS Code

## Expected behavior

All tabs should re-opened (Tabs/files from Step 2., 3. and 7.)

## Actual behavior

Only the unsaved file from step 3. and the one from the Windows Explorer, step 7. are opened.
And the last session (in this example, file from step 1. is lost!

Is this wanted or can this be configured?

**_Notes:_** Relates also to #70006

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3499)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.93GB (55.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
pascal|ale|8.0.1
pascal-formatter|ale|2.2.0
markdown-checkbox|bie|0.1.1
markdown-mermaid|bie|1.1.2
markdown-preview-github-styles|bie|0.1.4
better-toml|bun|0.3.2
vscode-eslint|dba|1.8.2
vscode-new-file|dku|4.0.2
docs-markdown|doc|0.2.2
xml|Dot|2.4.0
gitlens|eam|9.5.1
LogFileHighlighter|emi|2.4.3
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
graphviz-markdown-preview|gee|0.0.7
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.4.9
rest-client|hum|0.21.2
innosetup|idl|1.2.0
reg|ion|0.0.2
vscode-fix-checksums|leh|1.1.0
select-highlight-minimap|mde|0.0.8
python|ms-|2019.2.5558
csharp|ms-|1.17.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vetur|oct|0.16.2
vscode-auto-scroll|pej|1.0.2
vscode-docker|Pet|0.6.1
markdown-checkbox|PKi|1.5.0
vscode-sort-json|ric|1.13.0
ActiveFileInStatusBar|Ros|1.0.3
trailing-spaces|sha|0.2.11
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
vscode-smoothtype|spi|1.2.0
vscode-icons|vsc|8.3.0
markdown-all-in-one|yzh|2.1.1

</details>

**Comment by SylwesterZarebski** [comment]
Confirm bug with 1.32.2 and 1.32.3. Saved files are not opened only unsaved ones.

**Comment by aeschli** [comment]
From what I have tested, there hasn't been any changes. I tested with 1.26 (just picked an older version).
When starting code with files or folders as argument we don't restore previous windows or files, just unsaved files.

@bpasero What's the intended behaviour?

**Comment by DoCode** [comment]
@aeschli thanks for the info.
It's very annoying when we always lost our last session on this issue/feature!
When this is really the expected behavior, then please add an option to configure `Force restore all sessions on startup`!

**Comment by SylwesterZarebski** [comment]
True, how to restore session, when sometimes it do not restore? It is lost then?

**Comment by SylwesterZarebski** [comment]
Ah, old issue, thanks.
