### ISSUE TITLE
Built-in programming language extensions

### ISSUE THREAD

**Issue by Zenderking** [Microsoft/vscode#70753]
Issue Type: <b>Feature Request</b>

VSCode is the BEST text editor I ever used. It is fast, free, and easy to use. The only problem I have with it is that it doesn't support a lot of files without (hacking) the program. For example, if you want to run C++ files, you have to install 3 plugins to auto compile the file or you have to do a lot of JSON coding to allow VSCode to compile and run the files. I wish VSCode has a built-in plugin that allows the user to enter commands and run them when you run the file (Like Notepad++'s NppExec). I hope this feature is in the next update for VSCode so I can enjoy the cool-looking text editor again. PS: Please contact me using email if the problem is fixed becuase I'm pretty busy (Almost Always).

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
We deliberately keep language specific actions in extensions to keep VS Code lightweight and useful for everyone. If you don't want to install extensions you can set up your own tasks to build projects: https://code.visualstudio.com/Docs/editor/tasks
