### ISSUE TITLE
Code completion/lookup extremely slow

### ISSUE THREAD

**Issue by raijinsetsu** [Microsoft/vscode#70751]
Issue Type: <b>Bug</b>

We have a moderately sized project. After a recent VSCode update, all TypeScript code completions/lookups slowed to a crawl. Hovering over a variable, using ctrl-space to see completions, or using ctrl-click to see the definition of an identifier all take upwards of 30 seconds to display. This is prohibitive to development.

This is happening for multiple users on different machines, all Windows.

CPU and Memory do not appear to be factors as my machine is idling around 25% CPU and I have ~8GB of free memory.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.68GB (6.96GB free)|
|Process Argv|C:\Users\lcharron\development\server.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
javascript-ejs-support|Dig|0.4.4
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vscode-guid|hea|1.4.2
vscode-kubernetes-tools|ms-|0.1.18
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.6.3
typescript-mono-repo-import-helper|q|0.0.6
ejs-language-support|Qas|0.0.1
vscode-yaml|red|0.3.0
markdown-preview-enhanced|shd|0.3.13
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by raijinsetsu** [comment]
Disabling all extensions appears to correct the issue. We will review the
extensions we're enabling and then update then reach out to the extension's
developer to report the issue.

Thanks!

**Comment by hegelstad** [comment]
@raijinsetsu do you mind sharing which extension was causing the deterioration of the performance?
