### ISSUE TITLE
Add files opened within Code to the list of recently opened files

### ISSUE THREAD

**Issue by cbmeeks** [Microsoft/vscode#70762]
Issue Type: <b>Bug</b>

When I used Sublime Text, I was always annoyed that the most recent documents were never in my list.

Then I switched over to VS Code only to discover the same bug is there!  So I waited a very long time to see if this would be fixed.  As of the newest version, it has not.

I literally created a small TXT file, saved it, then went to Open Recent to discover it is not there.  I even went to "More..." and typed the filename given and it still was not there.  I had to manually open it by locating it myself.

What's worse is that my most recent documents are documents that I opened MONTHS ago and only opened once!  Even though I have opened dozens and dozens of more recent files, my most recent documents does not properly get updated.  

Why can't "Open Recent" actually show the RECENT documents that I opened or created?  Why do I constantly have to navigate to "More..." to find the document I literally opened 10 minutes ago?  But documents that I opened last YEAR are in my list?

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.65GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.1
pascal-formatter|ale|2.2.0
xml|Dot|2.4.0
retroassembler|Eng|1.0.4
spin|Ent|0.4.0
mssql|ms-|1.4.0
python|ms-|2019.2.5558
cpptools|ms-|0.21.0
PowerShell|ms-|1.11.0
veriloghdl|msh|1.0.1
forth|ric|0.0.1
vscode-arduino|vsc|0.2.25

</details>

**Comment by bpasero** [comment]
@cbmeeks that is not how that list works, that list is only populated from opening files outside of VSCode into VSCode. If each file that you open ends up in that list it would become very large.

What is your use case exactly with this list? Can you not use the local history (Ctrl+P) instead?

**Comment by cbmeeks** [comment]
@bpasero I wouldn't expect the list to contain every file I've ever opened.  Just the most recent 5-10 or so.  So it appears I have to manually open the file from my OS explorer in order to be in that list.  Which is annoying because I routinely open a blank VS Code instance, create a text file and then save it.  The next day I want to open that text file.  So why wouldn't it appear in that list?  Notepad++ (and many other apps) have this behavior.  Which seems natural to me.

**Comment by cbmeeks** [comment]
Ctrl+P seems to be working.  But, earlier, it didn't find a text file that I just created.  So it may not be consistent.

Feel free to close this issue.
