### ISSUE TITLE
Debug play button is invisible in Insiders

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#70766]
Repro:

1. Start debugging (I was using attach to extension host target)
2. Press pause

![image](https://user-images.githubusercontent.com/2193314/54625474-9a583800-4a2c-11e9-9f1f-fb876c4a5859.png)

---

Version: 1.33.0-insider (user setup)
Commit: 1d191e8909535aaee3389f89b96422a774188ed2
Date: 2019-03-19T06:18:48.768Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18855

**Comment by isidorn** [comment]
@Tyriar this should be fixed with latest. Can you please try reproducing this when running out of source?
 Thanks you

**Comment by isidorn** [comment]
Fixed via 966050a653
fyi @dbaeumer
