### ISSUE TITLE
Debug Continue button Greyed Out but functional

### ISSUE THREAD

**Issue by Jay-Beeckman** [Microsoft/vscode#70760]
Issue Type: <b>Bug</b>

Enter debugging mode and stop on a breakpoint.  The Play button (Continue) is greyed out, you can't even see it, but it functions properly if you hit the empty space where the icon should be.

VS Code version: Code - Insiders 1.33.0-insider (1d191e8909535aaee3389f89b96422a774188ed2, 2019-03-19T06:18:48.768Z)
OS version: Windows_NT x64 10.0.18358

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (4.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
jshint|dba|0.10.20
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
quickOpenSelection|fin|1.0.2
auto-rename-tag|for|0.0.15
salesforce-commerce-cloud-productivity-pack|gkk|1.0.0
vscode-mocha-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.7.0
beautify|Hoo|1.4.9
vscode-scss|mrm|0.6.2
js-patterns-snippets|nik|0.0.5
subtle-brackets|raf|3.0.0
sass-indented|rob|1.5.1
trailing-spaces|sha|0.2.11
prophet|Sqr|1.1.2

</details>

**Comment by isidorn** [comment]
This should be fixed via 37b76b0889
Please try out wednesday vscode insiders nad if you still see it please let us know (with more details, on what repo you still see this and so on)

**Comment by martinschayna** [comment]
This problem persists in the Wednesday insiders version too.

Version: 1.33.0-insider
Commit: 1efaca21afeb983a8efdae6a6b142bd00276c563
Date: 2019-03-20T08:20:09.900Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

Steps to reproduce
- place breakpoint somewhere to code
- start debugging
- whenever debugger stops on breakpoint the first icon **Continue (F5)** isn't visible, but it's clickable and fully functional.

Technically, according to DevTools panel, it's icon `continue-inverse.svg`. Other icons such as `pause-inverse.svg` etc. are still visible, even in disabled state.

**Comment by isidorn** [comment]
Sorry I just pushed a fix. Will be fixed in tomorrow's vscode insiders!
