### ISSUE TITLE
setting to turn off tooltips in explorer pane

### ISSUE THREAD

**Issue by hansifer** [microsoft/vscode#70768]
Tooltips on filenames in the explorer pane are annoyingly obtrusive, obscuring the file below the hovered one and often code as well. Additionally, they are of low value. I rarely need to know a file's full path when I'm working in a known repo.

PLEASE provide a setting to turn these tooltips off.

**Comment by sefaYavuz** [comment]
This is so annoying. It blocks the view of other files as well.

**Comment by cleverlemming** [comment]
I agree with [hansifer](https://github.com/hansifer). Please turn this feature off if you don't want to fix it. Users know where their repository is without this distracting redundancy.

**Comment by ariens-shopify** [comment]
I agree with this frustration.  I'm usually a vim user, but the project that I'm contributing to atm requires vs code.  This has been driving me nuts, especially being unfamiliar with the repo directory structure _and_ the IDE.  I'm constantly having to focus on another element to be able to dismiss the hover.

**Comment by isidorn** [comment]
Ok, let's reopen and we might add this in the future. Also there was a duplicate issue.

**Comment by dehmer** [comment]
I'm very glad this issue was reopened.
I'd really like to have an option to disable hovers in explorer completely.

Just out of interest: What benefit do users get from the information provided in said hovers? It seems pretty redundant to me too. Is there any pointer to the initial requirement or why this would be useful?

**Comment by Rusty-Shackleford** [comment]
Is there a way to change the format of it?  The weird thing is I don't ever recall noticing this before, but now it's all I can see.  I'm thinking something may have changed the look of it, but I've removed all preferences for workspace and user and it still looks the same.

![image](https://user-images.githubusercontent.com/19804292/89091419-35765700-d36f-11ea-829b-b9f6eee39141.png)

**Comment by eieioxyz** [comment]
As a developer, I have zero use for these.

But as a tutorial creator, they are downright annoying. I find myself editing around these, trying to cut them out, re-recording portions, etc.

**Comment by alanschneider** [comment]
I wish they would just fix this issue. It has been reported in the past by another user: #82775. It's incredibly annoying, and sometimes the tooltip wraps over multiple lines (See #115653).

**Comment by samheuck** [comment]
Agreed. Breadcrumbs already does a great job of showing me where I am in the file tree. I find the file path tooltip pop-ups to be really visually distracting.

**Comment by iskrisis** [comment]
This is really hard when doing file traversing in tutorials/screencasts. I don't think anyone uses this it just makes stuff complicated to edit afterwards.

**Comment by samheuck** [comment]
@isidorn Any chance you could take a second look at this? Several people have expressed that this hover tool-tip is not useful in day-to-day programming work. If you could help us understand some of the challenges that are making this issue out-of-scope, perhaps we could put our heads together and come up with some solutions to overcome them?

**Comment by samheuck** [comment]
Would something like this work?

```
diff --git a/src/vs/workbench/contrib/files/browser/views/explorerView.ts b/src/vs/workbench/contrib/files/browser/views/explorerView.ts
index 8aae18473ee..f7e7b2ff6f5 100644
--- a/src/vs/workbench/contrib/files/browser/views/explorerView.ts
+++ b/src/vs/workbench/contrib/files/browser/views/explorerView.ts
@@ -264,7 +264,7 @@ export class ExplorerView extends ViewPane implements IExplorerView {
 		const setHeader = () => {
 			const workspace = this.contextService.getWorkspace();
 			const title = workspace.folders.map(folder => folder.name).join();
-			titleElement.textContent = this.name;
+			titleElement.textContent = '';
 			titleElement.title = title;
 			titleElement.setAttribute('aria-label', nls.localize('explorerSection', "Explorer Section: {0}", this.name));
 		};
````

**Comment by grantsimongrant** [comment]
I have applied this functional request again, I hope everyone can vote for this request, link:#173236

**Comment by grantsimongrant** [comment]
I have applied this functional request again, I hope everyone can vote for this request, link:#173236

**Comment by grantsimongrant** [comment]
> Tooltips on filenames in the explorer pane are annoyingly obtrusive, obscuring the file below the hovered one and often code as well. Additionally, they are of low value. I rarely need to know a file's full path when I'm working in a known repo.
> 
> PLEASE provide a setting to turn these tooltips off.

I have applied this feature-request again, I hope everyone can vote for it, link:#173236

**Comment by grantsimongrant** [comment]
> This is so annoying. It blocks the view of other files as well.

I have applied this feature-request again, I hope everyone can vote for it, link:#173236

**Comment by grantsimongrant** [comment]
> I agree with [hansifer](https://github.com/hansifer). Please turn this feature off if you don't want to fix it. Users know where their repository is without this distracting redundancy.
I have applied this feature-request again, I hope everyone can vote for it, link:#173236

**Comment by grantsimongrant** [comment]
> I agree with this frustration. I'm usually a vim user, but the project that I'm contributing to atm requires vs code. This has been driving me nuts, especially being unfamiliar with the repo directory structure _and_ the IDE. I'm constantly having to focus on another element to be able to dismiss the hover.

I have applied this feature-request again, I hope everyone can vote for it, link:#173236

**Comment by grantsimongrant** [comment]
> Ok, let's reopen and we might add this in the future. Also there was a duplicate issue.

I have applied this feature-request again, I hope everyone can vote for it, link:#173236

**Comment by grantsimongrant** [comment]
> I'm very glad this issue was reopened. I'd really like to have an option to disable hovers in explorer completely.
> 
> Just out of interest: What benefit do users get from the information provided in said hovers? It seems pretty redundant to me too. Is there any pointer to the initial requirement or why this would be useful?
I have applied this feature-request again, I hope everyone can vote for it, link:#173236

**Comment by monk-afk** [comment]
Here's a workaround that worked for me; a broken setting to the workbench.hover.delay in User/settings.json:

```json
    "editor.hover.enabled": false,
    "workbench.hover.delay": null,
```

**Comment by samheuck** [comment]
> Here's a workaround that worked for me; a broken setting to the workbench.hover.delay in User/settings.json:
> 
> ```json
>     "editor.hover.enabled": false,
>     "workbench.hover.delay": null,
> ```

This didn't work for me in VS Code v1.91.1 build: f1e16e1e6214d7c44d078b1f0607b2388f29d729

**Comment by samheuck** [comment]
Somebody has more pull than the rest of us.

**Comment by zemariolacBG** [comment]
> Here's a workaround that worked for me; a broken setting to the workbench.hover.delay in User/settings.json:
> 
> ```json
>     "editor.hover.enabled": false,
>     "workbench.hover.delay": null,
> ```

THANKS!!

**Comment by ekinertac** [comment]
> Here's a workaround that worked for me; a broken setting to the workbench.hover.delay in User/settings.json:
> 
> ```json
>     "editor.hover.enabled": false,
>     "workbench.hover.delay": null,
> ```

This method is effective, but it also disables the popup on the code itself.

**Comment by MariuzM** [comment]
```
 "workbench.hover.delay": null,
```

use this to disable tooltip in explorer and other stuff but not editor / code

**Comment by 0x8fv** [comment]
@ekinertac Only use this to keep the popup in the code editor.
`"workbench.hover.delay": null,`

**Comment by taftster** [comment]
Setting the delay to "null" causes a validation warning (which probably doesn't hurt anything). But technically it's expecting a number of milliseconds for the delay.

That being said, I just set mine to some large value with the same effect. `"workbench.hover.delay": 60000` for a one minute delay.

Concur with the general annoyance here. This should just be disabled. It takes up unnecessary visual space. Like why exactly do I need to know the Full Path to the file exactly, when I can right-click and "Reveal in File Explorer" when necessary.
