### ISSUE TITLE
Multi cursor jumping screens in macOS version of VS Code

### ISSUE THREAD

**Issue by AplUSAndmINUS** [Microsoft/vscode#70765]
Issue Type: <b>Bug</b>

1- Click the mouse to position first cursor.
2- Select ALT+click to select mutliple cursors.
3- After a few selections, the window will jump to a different position than what was selected, throwing off the multi-cursor. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
beautify|Hoo|1.4.9
angular2-switcher|inf|0.2.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
LiveServer|rit|5.5.1
vim|vsc|1.2.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by alexandrudima** [comment]
@AplUSAndmINUS What exactly do you mean by "After a few selections, the window will jump to a different position than what was selected". I cannot reproduce this.
