### ISSUE TITLE
Terminal key combinations not working properly

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#7077]
- VSCode Version: 1.2.0-insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Open terminal using sysnative Powershell as default
2. Press key combinations like the following and it inputs the key mapping instead:
   - <kbd>ctrl</kbd> + <kbd>c</kbd> produces ^C
   - <kbd>ctrl</kbd> + <kbd>left</kbd> produces 5D
   - <kbd>ctrl</kbd> + <kbd>right</kbd> produces 5C
3. Using Shift combinations does not highlight text
   - <kbd>shift</kbd> + <kbd>end</kbd> Skips to end without highlight
   - <kbd>shift</kbd> + <kbd>home</kbd>  Skips to beginning without highlight
   - <kbd>shift</kbd> + <kbd>left</kbd>  moves left without highlight
   - <kbd>shift</kbd> + <kbd>right</kbd>  moves right without highlight

**Comment by Tyriar** [comment]
So the regular Powershell terminal supports selection using those keybindings? Interesting that <kbd>ctrl</kbd>+arrow doesn't skip the word, that works fine on bash.

**Comment by gerane** [comment]
Yeah it works in regular powershell terminal, and it also works if you launch powershell from a cmd.exe prompt.

![](https://raw.githubusercontent.com/gerane/PowerShell/master/Images/ConsoleKeys.gif)

**Comment by gerane** [comment]
Here is an example of what it looks like inside of Code.

![](https://raw.githubusercontent.com/gerane/PowerShell/master/Images/VSCodeKeys.gif)

**Comment by Tyriar** [comment]
These keys may be a limitation of winpty, or at least the quite old version that is being used.

Copying and pasting hasn't been looked at yet, the experience is terrible on all platforms. See https://github.com/Microsoft/vscode/issues/6451 https://github.com/Microsoft/vscode/issues/6945

**Comment by rajeevkumarsharma** [comment]
ctrl + c , here copy selected area (missing in vscode terminal), insted it produces ^C

it's my elementary os terminal with this feature
![screenshot from 2016-06-02 13 00 46](https://cloud.githubusercontent.com/assets/8169482/15737322/130bfe82-28c3-11e6-983a-6125108b6c8d.png)

ctrl + v, here paste whatever is in clipboard (missing in vscode terminal), insted it produces ^V

![screenshot from 2016-06-02 13 01 06](https://cloud.githubusercontent.com/assets/8169482/15737346/324fc90e-28c3-11e6-9b8e-1063b3b1e49b.png)

**Comment by AAurelianus** [comment]
ctrl + backspace in powershell is also not working. It only removes one character, while in native powershell and powershell launched through native cmd it removes the whole previous word.

**Comment by AAurelianus** [comment]
In the latest insider's release ctrl + left/right no longer produce '5D/5C', but only move one character at a time rather than whole words. ctrl + c produces nothing rather than '^c'.

**Comment by Tyriar** [comment]
Thanks @AAurelianus, it looks like the adoption of xterm.js has improved the powershell situation :fireworks:

Here is the open issue for <kbd>ctrl</kbd>+arrow https://github.com/sourcelair/xterm.js/issues/65 (it happens on Linux/bash too).

**Comment by AAurelianus** [comment]
@Tyriar actually my previous comment on <kbd>ctrl</kbd> + <kbd>backspace</kbd> does apply. In native powershell the sequence deletes whole words, in powershell in the integrated terminal it only deletes single characters, the same as unmodified <kbd>backspace</kbd>.

**Comment by michaeltlombardi** [comment]
@gerane, I think the functionality for those keys is driven by [PSReadline](https://github.com/lzybkr/PSReadLine), not the terminal itself.

The terminal does seem to load PSReadline *okay* (the color highlighting works, no errors get thrown) but some of the functionality is lost. This might be due to the implementation of PSReadline?

**Comment by codymullins** [comment]
is this already being worked on or is it something I could create a PR for?

**Comment by Tyriar** [comment]
@codymullins not being worked on right now, I'm guessing its a problem within the https://github.com/sourcelair/xterm.js code base though (or the oldish https://github.com/rprichard/winpty version it uses when hooked up with pty.js).

**Comment by Thaina** [comment]
Using vscode with windows native command line also the same problem with ctrl key

**Comment by Tyriar** [comment]
@Thaina ctrl+left/right in cmd.exe should work fine in the current insiders https://code.visualstudio.com/insiders

**Comment by idoo** [comment]
Is it possible to build `CMD+K` to clear current render in terminal?

**Comment by Tyriar** [comment]
@idoo a command to clear its being added in v1.6,the key binding will come a little later though https://github.com/Microsoft/vscode/issues/12585

**Comment by Tyriar** [comment]
Closing this off in favor of https://github.com/Microsoft/vscode/issues/11314 (blocking upstream issue: https://github.com/sourcelair/xterm.js/issues/487)
