### ISSUE TITLE
keybindings.json: show default values column again

### ISSUE THREAD

**Issue by 3v1n0** [Microsoft/vscode#70779]
In vscode 1.32 (could be also in earlier versions) the keybindings.json doesn't open anymore in a multi-view with two columns with the original keybindings.

This was quite handy to be able to read the values and process them quickly.

Can it be restored?

Otherwise is there a way to open the original keybindings.json file manually?

**Comment by 3v1n0** [comment]
RTFM!

`workbench.settings.openDefaultKeybindings: true`

**Comment by shepelevstas** [comment]
> RTFM!
> 
> `workbench.settings.openDefaultKeybindings: true`

THANK YOU SO MUCH!!! I was going nuts trying to find them again...
