### ISSUE TITLE
Please let people to vote

### ISSUE THREAD

**Issue by morozovsk** [Microsoft/vscode#70770]
You "locked and limited conversation" in this issue: https://github.com/Microsoft/vscode/issues/41309 but you also limited people to vote for this issue.
Please let people to vote.

**Comment by isidorn** [comment]
Thanks but for the reason specified here https://github.com/Microsoft/vscode/issues/41309#issuecomment-405842785
We will never do that feature

**Comment by isidorn** [comment]
On second thought I have unlocked the issue. So you can vote. Thanks

**Comment by ronnyek** [comment]
I appreciate this btw... No telling if the vscode users will agree with my opinions about toolbar support, but at least there is some way for them to voice their opinions without having issues immediately closed. At least there is some semblance of caring what users want.

Thanks again

**Comment by jjssoftware** [comment]
Whilst the proposal is a much needed fabulous idea of a feature, it has stagnated for too long and the comments here make it stink even more of: microsoft not going to happen. I'm amazed that they've stooped low enough to grudgingly reopen it for comment.

**Comment by ronnyek** [comment]
I see reopening as a positive thing. It's possible no amount of votes are significant enough to change minds... Which has me a bit skeptical... 

Whether it's to save face... To lead us on... Genuine desire to deliver what users ask for... I think the issue is open for comments and votes for now which is (within reason) how open source projects should work. (Keep governance... Accept features you want... Consider overwhelming demand for specific changes or features)

**Comment by jjssoftware** [comment]
imo this recent comment is the most positive thing that I've seen in this debacle: 

https://github.com/Microsoft/vscode/issues/41309#issuecomment-479530956

I imagine that if someone were to come up with a vscode extension based on this pattern that enabled people to configure custom links to their favourite vscode commands and those links then appear as clickable links in a treeview pane to the left, this would cover 95% of the features of a toolbar that people are after. 

I'm nowhere near a vscode js extension dev expert but this idea is nagging and prodding me to have a go at creating this extension.

**Comment by usernamehw** [comment]
@jjssoftware Well, extension of that form kind of exists:

https://marketplace.visualstudio.com/items?itemName=usernamehw.run-commands-view

**Comment by ronnyek** [comment]
I mean ultimately I'd want it visible regardless of which item was shown at left. Also... There are things that allow this in the status bar... But that's already limited in real estate

**Comment by jjssoftware** [comment]
Thank you @usernamehw that is really useful for me, great work. It's a compromise of "toolbar" functionality but very useful in the absence of anything else.
