### ISSUE TITLE
Codeception output using git bash

### ISSUE THREAD

**Issue by buttflattery** [Microsoft/vscode#70775]
when I run 

`./vendor/bin/codeception run`

it gives me the output like below

![image](https://user-images.githubusercontent.com/1536454/54637772-493b5900-4aab-11e9-925e-38807a658845.png)

Any ideas why it shows the garbled output?

Info
```
OS: Windows 10 64bit
vscode : 1.32.3
```

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
