### ISSUE TITLE
Error when closing the last terminal of a composite task

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#70774]
Issue Type: <b>Bug</b>

When I close the last terminal associated with a composite task I see the following error message:
`Command name should never be undefined here`

It is coming from this code:
https://github.com/Microsoft/vscode/blob/b1ceace24d52332bf6ddb673a6e00dfed44cbb7b/src/vs/workbench/contrib/tasks/electron-browser/terminalTaskSystem.ts#L1113-L1115

Which was added as part of this commit: https://github.com/Microsoft/vscode/commit/5adc152eca5fadf4f61740434ba17f1729d6818c

Although that commit is far older than I've seen this issue -- which has been for the last few insider builds

/cc @alexr00 - it might be related to some of the changes to fix the other recent issues around composite tasks

VS Code version: Code - Insiders 1.33.0-insider (1d191e8909535aaee3389f89b96422a774188ed2, 2019-03-19T06:18:48.768Z)
OS version: Windows_NT x64 10.0.18358

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexr00** [comment]
Can you give an example of what kind of composite tasks cause this? I've tried several combinations, and I can't reproduce it.

**Comment by eamodio** [comment]
@alexr00 Here are my tasks, it is the `watch` task below that causes the error
```
		{
			"type": "npm",
			"script": "watch",
			"group": "build",
			"isBackground": true,
			"problemMatcher": [],
			"presentation": {
				"group": "vscode"
			}
		},
		{
			"type": "npm",
			"script": "agent:watch",
			"group": "build",
			"isBackground": true,
			"problemMatcher": [],
			"presentation": {
				"group": "vscode"
			}
		},
		{
			"label": "watch",
			"dependsOn": ["npm: watch", "npm: agent:watch"],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"isBackground": true,
			"problemMatcher": [],
			"presentation": {
				"group": "vscode"
			}
		}
```

**Comment by alexr00** [comment]
Good stuff, I can reproduce it.

**Comment by alexr00** [comment]
It's because you have a `presentation` the composite task. It doesn't actually do anything there other than cause this bug. Tasks should either not allow presentation without a command, or hand this better.

**Comment by roblourens** [comment]
I think I verified it but I see a different error https://github.com/Microsoft/vscode/issues/71311
