### ISSUE TITLE
UI: source control commit message input different border sizes

### ISSUE THREAD

**Issue by mtxr** [Microsoft/vscode#70777]
VS Code version: Code - Insiders 1.33.0-insider (1d191e8909535aaee3389f89b96422a774188ed2, 2019-03-19T06:14:21.651Z)
OS version: Linux x64 4.18.16-300.fc29.x86_64

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/707561/54638593-2dfc2980-4a6a-11e9-8cf1-4a254c167305.png)

**Comment by joaomoreno** [comment]
This is a purposeful design decision.

**Comment by mtxr** [comment]
Thanks! I thought it was a bug
