### ISSUE TITLE
Inappropriate default keybindings on macOS (they break text entry)

### ISSUE THREAD

**Issue by deanishe** [Microsoft/vscode#70776]
- VSCode Version: 1.32.3
- OS Version: 10.13.6 / High Sierra

Multiple default keybindings use ALT+letter or ALT+SHIFT+letter, which interferes with text entry on macOS.

Using ALT(+SHIFT)+letter is a core part of input on macOS, used to enter characters that aren't on your current keyboard. ALT+z = Ω, for example, and is impossible to type in VS Code (without editing keybindings) because it's mapped to `toggleWordWrap` instead.

ALT(+SHIFT)+alphanumeric keys should not be used for keybindings on macOS in any application that allows text entry. If ALT+alphanumeric is used, it should be combined with CMD or CTRL in order not to break text entry.

**Comment by alexandrudima** [comment]
AFAICT `alt+z` is the only built-in keybinding on the mac that is in the form `alt+[letter]`. I am not convinced this is a big enough problem to now change the default for toggle word wrap. The workaround is to configure keybindings and remove the offending one e.g.

```
{ "key": "alt+z", "command": "-editor.action.toggleWordWrap" },
```

**Comment by deanishe** [comment]
> since it might be now used by thousands...

Yes, it's probably too late to fix now. Something to bear in mind when adding new keybindings, I suppose.
