### ISSUE TITLE
Uninstalled extensions not deleted, keep reloading

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#70784]
Insiders, Mac

![image](https://user-images.githubusercontent.com/1487073/54648446-7fed8100-4a63-11e9-8956-82e6c4b0949f.png)

I've got a few extensions installed that I have previously uninstalled, but at some point they are being loaded again.  

For example, in this picture you can see the kubernetes and hue extensions, which I've previously uninstalled (a number of times). 

![image](https://user-images.githubusercontent.com/1487073/54648417-66e4d000-4a63-11e9-9d32-00aa1dd886bf.png)

I went and uninstalled the kubernetes, hue, and shades of purple extension again. But when we look at the `.vscode-insiders\extensions` folder, you can see the folders still there, plus a number of others that I've uninstalled in the past (marked with red arrow):

![image](https://user-images.githubusercontent.com/1487073/54649044-d8258280-4a65-11e9-9811-acb765927af2.png)

Also, as you can see above, i'm getting a number of versions of the extensions being left on the disk as well.

And eventually, i can't figure out when, these extensions on disk that i previously uninstalled will be loaded again (see the first picture).

Any ideas on what i can look for?

**Comment by sandy081** [comment]
@chrisdias we do not remove the uninstalled or outdated extensions immediately. Clean up is done after you restart VS Code. Please restart VS Code and all of them will be gone. 

Regarding showing uninstalled extension, do you have steps to repro? When you install an extension, we do not remove it immediately. Instead we tag it in an internal file and we do not show/load those tagged extensions. You should not see the uninstalled extensions after you reload. Please try and let me know if you see otherwise.

**Comment by sandy081** [comment]
@chrisdias Regarding clean up, there was a bug in insiders that clean up was not getting called at start up. Fixed it. But this should not impact the issue you reported showing uninstalled extensions in the UI. I would still need some help (steps) from you to repro.

**Comment by sandy081** [comment]
@chrisdias Can you please check the contents of `.obsolete` file in your extensions folder?

**Comment by chrisdias** [comment]
I upgraded my Insiders build yesterday and did not see the "old" extensions activated again.  So that was goodness.  There is no `.obsolete` file in the `.vscode-insiders/extensions` folder and all of the duplicate/uninstalled extensions have been deleted from there, so that's goodness too. 

![image](https://user-images.githubusercontent.com/1487073/54839444-1c906880-4c88-11e9-961b-2c71832cd861.png)

So, it looks like things have been cleaned up.  I'll close for now and reopen if it starts happening again.
