### ISSUE TITLE
Evaluating expressions in Debug Console scrolls to top

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70781]
Version: 1.33.0-insider
Commit: 1d191e8909535aaee3389f89b96422a774188ed2
Date: 2019-03-19T06:14:14.538Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

![scroll](https://user-images.githubusercontent.com/4033249/54645228-97733c80-4a58-11e9-88c0-4114b80773d9.gif)

Happens to me whichever thing I'm debugging on.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70331
