### ISSUE TITLE
Revisit PSCustomObject Accelerator Intellisense Formatting

### ISSUE THREAD

**Issue by mpearon** [Microsoft/vscode#70786]
## REFERENCE: https://github.com/PowerShell/vscode-powershell/issues/1595 #62744

# Details Output

### VSCode extensions:
```Powershell
WakaTime.vscode-wakatime
aaron-bond.better-comments
alexcvzz.vscode-sqlite
Compulim.vscode-clock
DotJoshJohnson.xml
eamodio.gitlens
fabiospampinato.vscode-github-notifications-bell
formulahendry.vscode-mysql
GrapeCity.gc-excelviewer
hoovercj.vscode-power-mode
idleberg.applescript
johnstoncode.svn-scm
Kelvin.vscode-sshfs
le0zh.vscode-regexp-preivew
mkloubert.vscode-remote-workspace
ms-mssql.mssql
ms-vscode.PowerShell
ms-vscode.PowerShell-Preview
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
nonoroazoro.syncing
rafaelmaiolla.remote-vscode
shyykoserhiy.git-autoconfig
softwaredotcom.swdc-vscode
yzhang.markdown-all-in-one
```

### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Th...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

When using the [PSCustomObject] Accelerator, the initial [ is not removed.

### Expected Behavior

I think that the if an initial [ is detected, it should be removed.

### Actual Behavior

The [ is duplicated when using Tab and when selecting the autocomplete option.
I've seen that if I type PSCustomObject, then hit tab or select the option, the bracket is not added - but I naturally begin typing the actual expression. Maybe I'm being a bit too picky.

### Attached Files
![](https://user-images.githubusercontent.com/7157790/47732868-11836000-dc35-11e8-9ddc-f24176d589e2.gif)

**Comment by TylerLeonhardt** [comment]
Hi 👋 this probably shouldn't have been closed. Can some one help with this?

**Comment by TylerLeonhardt** [comment]
@sbatten or @Tyriar this might not be your area... But could one of you help point us to the right folks?

**Comment by Tyriar** [comment]
I think it's a snippet issue?

**Comment by jrieken** [comment]
This is actually not an issue with snippets because the snippet-*prefix* defines what portion get detected and hence replaced. As shown in https://github.com/PowerShell/vscode-powershell/issues/1595#issuecomment-475329943 that is `PSCustomObject` and not `[PSCustomObject`

**Comment by TylerLeonhardt** [comment]
@jrieken there are 2 problems here still...

It's set to `PSCustomObject` because that's the name of the snippet. If I set it to `[PSCustomObject` then `[PSCustomObject` is what shows in the dialog:

![image](https://user-images.githubusercontent.com/2644648/55418090-c55f8300-5526-11e9-91a9-b8a34827cf02.png)

Instead of showing the actual name of the snippet.

Also, if I type `[`, vscode naturally adds the `]` to the other end, but then when I use my snippet, the `]` still is there:

![image](https://user-images.githubusercontent.com/2644648/55418183-fa6bd580-5526-11e9-808b-b22d80f40b21.png)

This is a tougher problem... I know, but I want to call it out as an experience that customers will likely hit.

**Comment by mpearon** [comment]
Where did this responsibility land?

**Comment by TylerLeonhardt** [comment]
Ping @jrieken.

**Comment by TylerLeonhardt** [comment]
Another gentle ping, @jrieken

**Comment by sba923** [comment]
I'd really like this behavior to be improved... who owns this?

**Comment by jrieken** [comment]
@TylerLeonhardt I actually stopped reading after this

> @jrieken there are 2 problems here still...

The rule is 1 problem, 1 issue

**Comment by TylerLeonhardt** [comment]
Sounds good @jrieken that is a respectable policy. Would you prefer I open two new issues?

For context:

Issue one using _Python_ as the example language snippet:

```json
{
    "listcompPy": {
        "prefix":"x for x in",
        "body":[
            "[x for x in range(1,20) if x%2==0 ]"
        ]
    }
}
```
typing `[x` results in extra brackets:
```python
[[x for x in range(1,20) if x%2==0 ]]
```

Issue two using your suggestion of adding `[` to the `prefix`:
```json
{
    "listcompPy": {
        "prefix":"[x for x in",
        "body":[
            "[x for x in range(1,20) if x%2==0 ]"
        ]
    }
}
```
typing `[x` results in a single extra bracket at the end:
```python
[x for x in range(1,20) if x%2==0 ]]
```

**Comment by jrieken** [comment]
> Would you prefer I open two new issues?

Well, one exits https://github.com/microsoft/vscode/issues/26012 and other is the acknowledgement of the limitations of static snippets. Details:

> Issue two using your suggestion of adding [ to the prefix:

I wasn't suggesting that your snippet-prefix is `[x` but I was explaining that the prefix is what's being overwritten. That's all snippets can do, for dynamic stuff a completion provider should be used. 

Suggestion: knowing that vscode auto closes brackets by default you could adjust your snippet to not  insert brackets as well...

**Comment by TylerLeonhardt** [comment]
> Suggestion: knowing that vscode auto closes brackets by default you could adjust your snippet to not insert brackets as well...

This is a reasonable suggestion if the brackets come at the start and end of the snippet, but that's not always the case.

For example the snippet that this issue was originally opened for is:

```pwsh
[PSCustomObject]@{
      
}
```

> for dynamic stuff a completion provider should be used.

I'll investigate this as a workaround but that said, #26012 would certainly fix this issue. Snippets and auto-closing pairs playing nicer together is ideal.

@mpearon #26012 is the language agnostic issue that we should put examples into and use for further tracking.
