### ISSUE TITLE
VSCode overlays everything even when minimized on Ubuntu

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#7078]
- VSCode Version: 1.0.0 and 1.1.1
- OS Version: Ubuntu 16.04 x64 running in a VirtualBox on Windows 10 Pro x64 (3D acceleration enabled)

Steps to Reproduce:

Open VS Code and Minimize it or simply try to drag another window over it
While the window handle dissappears, the UI of Code will overlay everything else.

![image](https://cloud.githubusercontent.com/assets/10532611/15688503/ad7ee9e2-277a-11e6-8bf3-8f3557b0db06.png)

Even on the lockscreen:

![unbenannt](https://cloud.githubusercontent.com/assets/10532611/15688837/5d4da542-277c-11e6-99fa-f9d86888efd4.PNG)

This does not happen with 3D acceleration disabled, but disabling that also makes Ubuntu lag incredibly :/

**Comment by Tyriar** [comment]
Did you get a consistent repro? I've found lots of issues with any Chromium-based app on VirtualBox so this is probably an upstream issue.

**Comment by bpasero** [comment]
@felixfbecker maybe try `code --disable-gpu`

**Comment by herbfickes** [comment]
I have the same problem using VSCode 1.2.1 on Ubuntu 16.04 LTS running in a VirtualBox 5.20 guest on top of a Windows 7 host.

With 3D acceleration on, VSCode does not redraw its screen.  With 3D acceleration off, Ubuntu/Unity is too slow to use.

**Comment by bpasero** [comment]
@felixfbecker @herbfickes could you give our insider release a try to see if this issue is fixed? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by felixfbecker** [comment]
@bpasero Sorry, I don't have a Ubuntu VM on my PC atm, storage got low 😄

**Comment by herbfickes** [comment]
@bpasero, the preview version worked great on both my 32 and 64 bit Ubuntu images.  I'm going to try it on our Windows dev image as well, though we haven't seen that problem on it.

Thank you and btw, VSCode is fantastic.  We've even gotten our 'anything-but-MS' developers here to use it.

**Comment by bpasero** [comment]
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.
