### ISSUE TITLE
Allow Github HTML tags in Hover markdown

### ISSUE THREAD

**Issue by Linskeyd** [Microsoft/vscode#70785]
Previous issue that was closed as out of scope: https://github.com/Microsoft/vscode/issues/40607

Reference PR which was merged in Atom's auto-complete: https://github.com/atom/autocomplete-plus/pull/1003

Right now (as far as I can tell), HTML elements are not supported in VSCode Markdown Hovers.  I'd like to re-open the discussion from the previous issue; I am willing to create a PR to resolve this.  Either of these would work for me:
* Enabling Github HTML tags in Hover markdown.
* Whitelisting a subset of HTML elements to be usable in VSCode Markdown Hovers.

An example use-case I have is breaking lines within Markdown tables.  The version of markdown being used in VSCode has the plugin for markdown tables enabled, but doesn't support `<br>`, so markdown table cells can only ever be single line.

**Comment by jrieken** [comment]
@Linskeyd #40607 isn't locked so please comment there instead of creating new issues. Thanks

**Comment by Linskeyd** [comment]
@jrieken ok I'll move the comment over there.  Apologies if process wasn't followed here, I was trying to re-open that previous issue for discussion but I could only make a new issue.
