### ISSUE TITLE
can not debug node.js program without any error info

### ISSUE THREAD

**Issue by mccoysc** [Microsoft/vscode#70799]
C:\Program Files\nodejs\node.exe --inspect-brk=47618 she.js 
Debugger listening on ws://127.0.0.1:47618/099459ec-9a27-4360-9b27-9d2773c7879b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...

output showing as the above.
after showing this,the vscode debug controle panel disappeared
especially,i click the 'debug' button at the file "test.js",but as the above showing:"C:\Program Files\nodejs\node.exe --inspect-brk=47618 she.js",vscode try to debug "she.js".
why?
node --version
v11.9.0

**Comment by weinand** [comment]
How does your launch configuration (launch.json) look like?

**Comment by mccoysc** [comment]
and ah...i know
vscode denug the file in package.json's field "main" if exist
