### ISSUE TITLE
Find from files in project function(CMD + shift + F) by Japanese character doesn' work

### ISSUE THREAD

**Issue by minolasoft** [Microsoft/vscode#70793]
Issue Type: <b>Bug</b>

Find from files in project function(CMD + shift + F) by Japanese character doesn' work. When enter Japanese character in find target, results is not enough and some of file names are lack.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
codestream|Cod|0.35.0
ftp-sync|luk|0.3.9
vscode-language-pack-ja|MS-|1.32.4
debugger-for-chrome|msj|4.11.3
printcode|nob|3.0.0
es6-css-minify|olb|2.2.0

</details>

**Comment by roblourens** [comment]
Are the missing files in a different encoding? You need to set `"files.encoding"` and can only search one encoding at at ime.

**Comment by minolasoft** [comment]
Thanks for your help. Actually some of files are encoded as utf-8 but almost my files are encoded as Shift-JIS. Windows OS needs shift-jis to run bat script but almost other sources are written by utf-8. Japanese need treat both shift-jis and utf-8 so ability searching with different encoded files is very helpful for me.

**Comment by roblourens** [comment]
Ok. It's unlikely that searching multiple file encodings or encoding detection will be supported. We would need support from ripgrep which will not add it https://github.com/BurntSushi/ripgrep/issues/746
