### ISSUE TITLE
A keyboard shorcut for rearrange the splited tabs

### ISSUE THREAD

**Issue by vdloc** [Microsoft/vscode#70795]
I usually split tabs to the vertical dimension tabs and resize them to get more space to view codes so I really want to have a keyboard shortcut that makes the split tabs have equal width(or height)
For example, if we have two split tabs which resized, each tab should be 50 percent of the screen width after the action.
(I'm sorry for my poor English)

**Comment by usernamehw** [comment]
`View: Reset Editor Group Sizes`
