### ISSUE TITLE
reporting error of "Matches multiple schemas when only one must validate." when build go program

### ISSUE THREAD

**Issue by yuan78** [Microsoft/vscode#70792]
Hi,
It reporting error of "Matches multiple schemas when only one must validate." when build go program.

The task.json is as follows:

{
    "version": "2.0.0",
    "tasks": [
    {
    "label": "build",
    "command": "go build",
    "args": ["-x -v", "-o", "Hello.exe", "Hello.go",],
    "problemMatcher": {
    "owner": "cpp",
    "fileLocation": ["relative", "${workspaceFolder}\\src"],
       }
    }
 ]
}
    

I don't think the task.json has any issue but it still pop out the error.

Pls help doublecheck it 

THX!

**Comment by alexr00** [comment]
This is already fixed in the latest Insiders build!
