### ISSUE TITLE
webview display blank page in Azure VM 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode#70790]
- VSCode Version: 1.32.3
- OS Version: Azure VM windows10 pro ,version 1809 

Steps to Reproduce:

1. create new Azure VM with windows10 pro,vision1809 , and login VM
![image](https://user-images.githubusercontent.com/35018765/54654707-06ed3880-4afa-11e9-8844-ba37412ce8f9.png)

2.install VS Code v1.32.3
3.install Azure IoT Edge v1.10.0 extension
4. run command "Azure IoT Edge: show sample gallery"
here Windows Security Alert will pop up
![image](https://user-images.githubusercontent.com/35018765/54654869-a6aac680-4afa-11e9-9782-22049a6a539b.png)
5.check private networks and public networks, and click Allow access
6.sample gallery page  is display blank page
![image](https://user-images.githubusercontent.com/35018765/54655018-38b2cf00-4afb-11e9-8609-59ddf6d7e2da.png)

**Comment by czgtest** [comment]
this issue also repro on Azure IoT Device workbench extension in vscode

![image](https://user-images.githubusercontent.com/35018765/54655104-97784880-4afb-11e9-8558-5110be40b505.png)

**Comment by mjbvz** [comment]
Thanks for the details steps. 

Looks like this is the same issue as #70809. Will keep this open since it has good repo steps

**Comment by mjbvz** [comment]
I can't repo this following these steps with VS Code 1.33 on azure with a windows user level account. I never see any windows defender pop up

@czgtest Does your company a proxy or other security thing setup for these machines?

**Comment by onlineservices283418** [comment]
@mjbvz 
#71033 is still present in VS Code 1.33, Windows 1809. Windows Defender is turned off via group policies. Visual Studio Code app is allowed to pass through Windows firewall, no other firewalls are installed on my machine. VS Code developer tools show that the app receives extension description but fails to display it. Looks like some kind of race condition or async programming error because some requests are displayed correctly, some aren't.

![bug1](https://user-images.githubusercontent.com/29972256/55666581-c01d7380-5859-11e9-958a-cc9b5dad76c9.png)
![bug2](https://user-images.githubusercontent.com/29972256/55666582-c01d7380-5859-11e9-88e4-2e10891e1283.png)
![bug3](https://user-images.githubusercontent.com/29972256/55666583-c0b60a00-5859-11e9-8eb4-a2cafab5298f.png)
![bug4](https://user-images.githubusercontent.com/29972256/55666579-c01d7380-5859-11e9-84b0-517a5a37f81c.png)

**Comment by onlineservices283418** [comment]
#70809 can be reproduced under the following conditions:
- Size: Standard D2 v3 (2 vcpus, 8 GB memory)
- Operating system: Windows 10 Pro, Version 1809

I can reproduce #71033 on my testing machine (barebone hardware, no virtualization) which also has 2 core cpu and 8 GB ram.

Hope it helps.

**Comment by Anmol-Singh-Jaggi** [comment]
I am also facing this issue, and based on a survey of co-workers, it happens on systems with 2 logical processors.
Also, this issue does not happen on VSCode 1.30.2

**Comment by mjbvz** [comment]
For someone that can repo this:

1. Run the `Developer Open Webview Developer Tools` command
1. Open the console of the dev tools
1. Is there any more information about the error in the developer console?

**Comment by onlineservices283418** [comment]
@mjbvz 

for #71033

![bug5](https://user-images.githubusercontent.com/29972256/55780272-416e4380-5ab0-11e9-92a0-7135be7e542e.png)

**Comment by mjbvz** [comment]
@onlineservices283418 Thanks. If you click on the link, can you please share which file and line number it opens up to. The printed line number (9) does not make sense

**Comment by onlineservices283418** [comment]
@mjbvz

![bug6](https://user-images.githubusercontent.com/29972256/55859428-b7d77800-5b7a-11e9-840d-c147ad3ac916.png)

**Comment by mjbvz** [comment]
@onlineservices283418 Are you still seeing this issue in the latest insiders build? I added some conditional guards with fbf201b that should prevent the exception but I'm not sure if they actually fix the issue

**Comment by onlineservices283418** [comment]
@mjbvz I don't use insider builds.

**Comment by mjbvz** [comment]
Someone that was seeing this issue, please test on the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by onlineservices283418** [comment]
VS Code 1.34.0, the bug is still here.

**Comment by mjbvz** [comment]
Someone from the community will need to investigate this since we've never been able to repo this issue. Here's a guide to getting started building VS Code from source: https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by onlineservices283418** [comment]
Nice policy, guys... to close issues you don't want to fix.

**Comment by onlineservices283418** [comment]
Ver. 1.36.0, the issue seems to be fixed.
