### ISSUE TITLE
Editor shows error on a valid TypeScript dynamic import statement 

### ISSUE THREAD

**Issue by gozzoo** [Microsoft/vscode#70806]
- VSCode Version: 1.32.3
- OS Version: Win 10 32bit

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/296970/54666629-eb326400-4af2-11e9-95e3-3ec74710163e.png)

Here is the actuall error message:

`Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.ts(1323)`

This is the relevant `tsconfig.json` (in the same directory with the source file)

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc",
    "module": "commonjs",
  }
}
```

What is strange is that there are no errors when I'm comiling the file with `tsc`.

```
C:\work\project>npm run tsc:server

> project@0.10.0 tsc:server C:\work\project
> tsc -p server/tsconfig.server.json
```

**Comment by mjbvz** [comment]
Can you check if that ts file is part of the correct project: 

1. Open the file
1. Run the `TypeScript go to project configuration` command

Does this open the correct `tsconfig.json`?

**Comment by gozzoo** [comment]
>Does this open the correct tsconfig.json?

No, it opens the one in the root folder of my project. I have second one in the folder with my source files, which extneds the one in the root folder, but for some reason Code ignores it.

**Comment by mjbvz** [comment]
Can you please share the tsconfigs along with their names?

**Comment by gozzoo** [comment]
If `/` is the root of my project

`/tsconfig.json`

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": ["es2015", "dom"]
  }
}
```

`/server/tsconfig.server.json`

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc",
    "module": "commonjs",
  }
}
```

The file I'm getting error on is in `/server` directory

**Comment by mjbvz** [comment]
We'll always try to use files called `tsconfig.json` as the project definition, not other variants of that file name like `tsconfig.server.json`

You should either rename `tsconfig.server.json` to `tsconfig.json` (also renaming the old `tsconfig.json` to `tsconfig.base.json`), or change the default `module` value in the existing `tsconfig.json` and create a new derived tsconfig for whoever needs to use `"module": "es2015"`

**Comment by gozzoo** [comment]
That helped, thanks!

I just renamed tsconfig.server.json to tsconfig.json and the error dissapeared.

Some people might not be able to fix similar issue that easily. There is a pattern in Angular apps to call config files like this:

```
tsconfig.app.json
tsconfig.e2e.json
tsconfig.spec.json
```

They all extend `tsconfig.json` in the root directory. These files get generated by angular-cli when creating new apps and are part of the predefined schema of each Angular app. People might get quite puzzled (as I was) when they start getting errors in VSCode for valid Typescript code.
