### ISSUE TITLE
Open Recent shows duplicates

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70800]
![image](https://user-images.githubusercontent.com/4033249/54664552-c8c42a80-4aa1-11e9-8f2d-38852eb3451b.png)

Version: 1.33.0-insider
Commit: 1d191e8909535aaee3389f89b96422a774188ed2
Date: 2019-03-19T06:14:14.538Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 17.7.0

I'm not 100% sure what's the repro steps. I remember that I did a few git checkout on CLI which has reverted/applied changes to the file.

Both entry resolve to the same file on disk, but I can open them side by side, including on tabs and Open Editors.

**Comment by bpasero** [comment]
Very likely: https://github.com/Microsoft/vscode/issues/12448
