### ISSUE TITLE
"Compared selected" feature disregards which file to edit upon mouse click

### ISSUE THREAD

**Issue by smeeklai** [Microsoft/vscode#70808]
**VS Code Info:**
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-16-generic

**Steps to Reproduce:**
1. Ctrl+left click on an origin file
2. Ctrl+left click on a file you want to compare
3. Right click on a file you want to edit

Please copy the link below and paste it in a new tab. For some reasons, directly clicking on it doesn't show you the original gif as it supposes to do
https://media.giphy.com/media/YWymvatZvnqmdQKKTw/source.gif

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by smeeklai** [comment]
More context: it was working as it should previously, but that is like a while ago. I don't remember exactly when I started getting this bug

**Comment by isidorn** [comment]
This works as expected for me. Please let me know what you are doing differently than me and what is the unexpected result.
Also we fixed something in this area so please try reproducing with vscode insiders https://code.visualstudio.com/insiders/

![compare](https://user-images.githubusercontent.com/1926584/54674988-d5766c00-4afd-11e9-8f1a-d20a018e0e05.gif)

**Comment by smeeklai** [comment]
@isidorn Hi

What I found in my case was that the lower file in the file explorer (`hey.py` in your case) is always selected to be the editable file (file on the right panel). I'll also get the same expected result if I follow exactly what you did. However, if I select the lower file (`hey.py`) first, then select the upper file (`hey.js`), then right click on the upper file (`hey.js`) and select `compare selected`, I'll get `hey.py` to be the editable file, which in fact I expected that `hey.js` should be the editable file (it worked like this previously)

Can you please confirm that if you follow the above steps, do you get `hey.js` to be the editable file?

**Comment by isidorn** [comment]
@smeeklai Yes I confirm. Dup of https://github.com/Microsoft/vscode/issues/68772
