### ISSUE TITLE
Insiders newest version update infinite loop

### ISSUE THREAD

**Issue by C0deRubbish** [Microsoft/vscode#70802]
Issue Type: <b>Bug</b>

MacOS Mojave version 10.14.3
VS Insiders 1.33.0
when I update once time, it will be always update, no matter how I restart it, it will check update and donwload newest insider file and will restart it

**Comment by bpasero** [comment]
@joaomoreno I can reproduce

**Comment by joaomoreno** [comment]
Thanks @C0deRubbish! Unpublished the latest insider, pushed fix https://github.com/Microsoft/vscode/commit/1efaca21afeb983a8efdae6a6b142bd00276c563 and we're triggering new builds, they'll be out in 30 mins.

**Comment by joaomoreno** [comment]
`1efaca21afeb983a8efdae6a6b142bd00276c563` is rolling out right now

**Comment by sanket-bhalerao** [comment]
This fixed the issue, thanks
