### ISSUE TITLE
Avoid "import 'vscode'" outside extension host

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70807]
Looks like webview and search are offenders:

![image](https://user-images.githubusercontent.com/900690/54666988-93dcc580-4aeb-11e9-8e18-a0b3a79c2a05.png)

//cc @jrieken

**Comment by jrieken** [comment]
related to https://github.com/Microsoft/vscode/issues/70319

**Comment by roblourens** [comment]
All of this is in the extension host for types only. If we duplicate the vscode.d.ts types somewhere else, what guarantees that they will match vscode.d.ts?

**Comment by jrieken** [comment]
>  If we duplicate the vscode.d.ts types somewhere else, what guarantees that they will match vscode.d.ts?

The compiler will guarantee that. Everything is linked together in `extHost.api.impl.ts`
