### ISSUE TITLE
vscode is crashing on startup

### ISSUE THREAD

**Issue by mkantz84** [Microsoft/vscode#70818]
- VSCode Version: 1.32.3
- OS Version: windows 10

Steps to Reproduce:

1. open vscode

Does this issue occur when all extensions are disabled?: Yes

Some log text that maybe can help:
[Code__PID__5212__Date__03_20_2019__Time_11_18_46AM__395__Log.txt](https://github.com/Microsoft/vscode/files/2987363/Code__PID__5212__Date__03_20_2019__Time_11_18_46AM__395__Log.txt)
[Code__PID__8464__Date__03_20_2019__Time_11_18_41AM__340__Log.txt](https://github.com/Microsoft/vscode/files/2987364/Code__PID__8464__Date__03_20_2019__Time_11_18_41AM__340__Log.txt)
[Code__PID__7648__Date__03_20_2019__Time_11_18_50AM__388__Log.txt](https://github.com/Microsoft/vscode/files/2987365/Code__PID__7648__Date__03_20_2019__Time_11_18_50AM__388__Log.txt)
[Code__PID__11208__Date__03_20_2019__Time_11_18_47AM__380__Log.txt](https://github.com/Microsoft/vscode/files/2987366/Code__PID__11208__Date__03_20_2019__Time_11_18_47AM__380__Log.txt)

Some more information: 
I had some problems debugging node.js with docker, and ufter some reserch i've killed port 5858. didnt work.
After that i restarted my computer and than the issue started..

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mkantz84** [comment]
It looks like the issue had fixed from itself after i installed the vs insider (dont really know if its related..)
