### ISSUE TITLE
allThreadsStopped stops the client completely

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#70816]
From Al-Shanha Jamal:

"It seems that allThreadsStopped:true/false just stops the client completely (as in the client sends a disconnect request) if this option is included at all whether true or false.
 
However, if I send a separate “stopped” event for each thread without the allThreadsStopped optional parameter, things work as expected.
 
I think that there is a further issue that is not noticeable when the number of threads is low. And that is that the client sends a Threads request continually it seems, and I’m not sure why…
And so when the list of threads is large (i.e. 1000) the UI is slow because its processing this long list, and on pause is having to read stopped events for each thread sequentially (because allThreadsStopped doesn’t seem to be working).
 
Anyways just some of my observations, let me know if you’ve encountered any of these please.
 
The reason I am interested in displaying such a large number of threads is because the language we have developed is performant based on a large number of threads. So this test of mine was to see how VSCode scales with the number of threads.
"

**Comment by isidorn** [comment]
Al-Shanha we have fixed some issue with allThreadsStopped more details here: https://github.com/Microsoft/vscode/issues/70107

Due to that can you reproduce the issue you are seeing with latest vscode insiders?
https://code.visualstudio.com/insiders/

**Comment by g2-aj** [comment]
Hi,

The version of VSCode I am using is: 

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I will try the insider build now and see if the issue with allThreadsStopped still occurs there.

**Comment by isidorn** [comment]
Great, thanks!

**Comment by g2-aj** [comment]
I tested this on VSCode Insiders and the same thing happened.

After configurationDone, I send events for each thread, and then a stopped event with "allThreadsStopped":true.


After this the client sends a threads request (to which I respond as shown in the attached log) and then the client disconnects.

Am I using it incorrectly?
[debug_logger.txt](https://github.com/Microsoft/vscode/files/2989156/debug_logger.txt)

**Comment by isidorn** [comment]
So the client is sending an unexpected `disconnect`?
If yes, F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/e16115a0c38caa521f9267c1cfc0cf7d3cea8ba5/src/vs/workbench/contrib/debug/electron-browser/debugSession.ts#L230)
And try to figure out why the client is sending a `disconnect` request which the user did not initiate.

**Comment by g2-aj** [comment]
Yes it is sending an unexpected disconnect request.

Re: "If yes, F1 > developer tools > put a breakpoint here" - do I do this in the extension development host? I don't see how to do this...more instructions would be great. Thanks.

**Comment by g2-aj** [comment]
Attached in this log is stopped events without "allThreadsStopped". 

A couple of things:

- The continue button disappears (but when I click in the area I can still "continue") (this happens on VSCode Insider only for me)
- You will notice the client sending a bunch of thread requests and I'm not sure why since at this point the debugger is just paused. I believe this is part of the issue with scaling the number of threads in the UI which I mentioned in my original post. Do you know why the client issues Thread requests continually like this?
[debug_logger.txt](https://github.com/Microsoft/vscode/files/2989247/debug_logger.txt)

**Comment by isidorn** [comment]
1. Continue button disappering is in unrelared issue that got fixed, so you should no longer see it
2. I do not know. Do you have a reproducable steps so I can try on my os x?
3. Here's how to add a breakpoint. After that you will see the stack trace and you can investigate why somebody called disconnect
4. Same way you can put a breakpoin in the threads request to try to figure out why are we always calling it

![breakpoint](https://user-images.githubusercontent.com/1926584/54749219-2a84b180-4bd4-11e9-82d2-9b351da2837c.gif)
