### ISSUE TITLE
libdbus-1.so.3: no version information available 

### ISSUE THREAD

**Issue by zhyhang1** [Microsoft/vscode#70814]
- VSCode Version: Stable 1.32.3

- OS Version: Fedora 22

- OS Type: 64-bit

Steps:

1. dnf install code
2. code 
I got this error :[ /usr/share/code/bin/../code: /usr/lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code) ], vscode can't open

**Comment by Tyriar** [comment]
We only support fedora 23+ https://code.visualstudio.com/docs/supporting/requirements
