### ISSUE TITLE
Improve Create Branch usability

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#70812]
Users are used to just creating a branch from HEAD. They are getting confused about choosing a ref as a target after choosing the new branch name.

Let's create separate `Create Branch` and `Create Branch from...` commands. Also, split those two actions in the `Checkout...` quick input.

**Comment by bpasero** [comment]
@joaomoreno I think both commands should have a "..." in the end as both ask for more input right?

![image](https://user-images.githubusercontent.com/900690/55073167-49c88680-508d-11e9-91b5-4ff52a805b87.png)
