### ISSUE TITLE
Clicking An Element

### ISSUE THREAD

**Issue by MisterJ936** [Microsoft/vscode#70810]
Issue Type: <b>Feature Request</b>

VS Code can be a little bit of confusing, and it has a lot of good staff in the vs code but,, the most important fix that most of us wants is element highlights.

example:
![Untitled](https://user-images.githubusercontent.com/31676163/54669951-8c3e1080-4b2d-11e9-897e-c7818a261309.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
@MisterJ936 this actually exists already for HTML. In the bottom right corner of VS Code there is a Language Mode option. Yours is set for PHP. If you set it for HTML you will get the highlighting behavior you want. 

@roblourens possible PHP feature request?

**Comment by MisterJ936** [comment]
@alexr00 I also did that but still highlights every element, see image bellow
![Untitled](https://user-images.githubusercontent.com/31676163/54690596-b3f89d00-4b5c-11e9-888e-27068f3fe2db.png)

![Untitled](https://user-images.githubusercontent.com/31676163/54690630-c70b6d00-4b5c-11e9-8a47-d48ebc7b6d78.png)

**Comment by bmewburn** [comment]
@MisterJ936 you might find this extension useful https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

![highlight](https://user-images.githubusercontent.com/5885195/55524669-d4d2fd80-56d9-11e9-9408-fcfca22bc293.gif)

**Comment by MisterJ936** [comment]
thanks!
