### ISSUE TITLE
runtimeVersion using nvm-windows when it should use WSL

### ISSUE THREAD

**Issue by petermorlion** [Microsoft/vscode#70815]
- VSCode Version: 1.32.3
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

0. Have nvm installed on WSL, nvm-windows installed on Windows
1. Configure VS Code to run/debug applications on the WSL
2. Add a launch configuration for a NodeJS project
3. Add a `runtimeVersion` to the launch configuration with a version that you have not installed on nvm-windows/Windows, but have installed on nvm/WSL.
4. Run the application --> you get the error "Node.JS version 'x.x.x' not installed for 'nvm-windows'.
5. Install that version on nvm-windows/Windows.
6. Run the application --> the application is started in VS Code's debug console, on the WSL

So it seems the runtimeVersion is checked in Windows _before_ running the app in the WSL. It also works if you just remove the runtimeVersion setting.

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur in the Insiders build?: Yes, as of 20/03/2019

**Comment by petermorlion** [comment]
I took a deeper look and believe it's related to the [vscode-node-debug](https://github.com/Microsoft/vscode-node-debug) repo. If you want, I can resubmit it there. If I read the code correctly, it [checks the current platform](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L199). And of course, I'm running VS Code on Windows, but my application on WSL/Linux.

**Comment by petermorlion** [comment]
Apparently, the Debug Console is still running on Windows, instead of the WSL. In light of that, the error message makes sense of course. Yet I thought it was possible to have your application run/debug on WSL, while still using VS Code in Windows?
I have `terminal.integrated.shell.windows` and `terminal.external.windowsExec` set to bash.exe. If anyone can point me to some documentation on how to run VS Code in Windows, but have the Debug Console use bash, that would be great.

**Comment by weinand** [comment]
If you set "useWSL" to true in your launch config, the debug target will be launched in WSL and the Debug Console will be connected to that debug target properly.

The Debug Console is not "running anywhere" because it is not a terminal. The debug console just shows the output of the process being debugged. If the process being debugged runs remotely, the Debug Console will show the output from the remote process but it does not "run remotely".

**Comment by petermorlion** [comment]
Ok, makes sense. So I've now managed to get it working again, and my initial report still stands. Here you can see it's connected to bash, but it still complains about nvm-windows:

![Capture](https://user-images.githubusercontent.com/3483719/54748115-07a4ce00-4bd1-11e9-87bb-c2eace8229bb.PNG)

The output in the debug console is from a previous run, using runtimeVersion 8.10.0, which is installed with nvm-windows. Changing that to a version that isn't installed, will produce the error in the message box.

**Comment by weinand** [comment]
Currently node.js version managers like "nvm" are not supported for "useWSL".
But we are working on this...

**Comment by petermorlion** [comment]
Ok, thanks for answering.
