### ISSUE TITLE
With window.restore.windows: none, still restore the sidebar state as before

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#70822]
Hi,

I've set `window.restoreWindows` to `none`, because I don't want to keep open files on next VSCode run.

It works, but the side effect is that when you start VSCode again, the sidebar is collapse

I would like to have the sidebar ( explorer ) always open by default

It is possible?

**Comment by isidorn** [comment]
Sidebar explorer is laways opened by default for me.
Can you reproduce this issue with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you post a short gif showing this issue. Thank you

**Comment by kanlukasz** [comment]
```
Version: 1.33.0-insider
Commit: 1efaca21afeb983a8efdae6a6b142bd00276c563
Date: 2019-03-20T08:25:15.878Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
```

**GIF:**
![vs2](https://user-images.githubusercontent.com/30685349/54684156-c6021d80-4b13-11e9-865c-187a01003354.gif)

**My settings JSON:**
```
	"editor.fontFamily": "Consolas",
	"editor.fontSize": 15,
	"editor.insertSpaces": false,
	"editor.lineHeight": 22,
	"editor.links": false,
	"editor.minimap.showSlider": "always",
	"editor.multiCursorModifier": "ctrlCmd",
	"editor.occurrencesHighlight": false,
	"editor.renderLineHighlight": "all",
	"editor.rulers": [100],
	"editor.showFoldingControls": "always",
	"editor.tabCompletion": "on",
	"explorer.sortOrder": "type",
	"files.hotExit": "off",
	"files.trimFinalNewlines": true,
	"files.trimTrailingWhitespace": true,
	"search.showLineNumbers": true,
	"window.restoreWindows": "none",
	"window.titleBarStyle": "native",
	"workbench.editor.highlightModifiedTabs": true,
	"workbench.editor.restoreViewState": false,
	"workbench.list.openMode": "doubleClick",
	"workbench.startupEditor": "none",
	"workbench.statusBar.feedback.visible": false
```

**Comment by bpasero** [comment]
@kanlukasz that is in a window without folder/workspace opened right?

**Comment by kanlukasz** [comment]
@bpasero - Yes, but I also tried with an open folder a moment ago and problem is the same

Gif below:
![vsanother_new](https://user-images.githubusercontent.com/30685349/54736295-bb469780-4baa-11e9-85d8-5cf08670dd14.gif)

**Comment by bpasero** [comment]
Oh I see, I will update the summary.
