### ISSUE TITLE
User settings are not overriding on mac

### ISSUE THREAD

**Issue by nitinbansal1989** [Microsoft/vscode#7082]
- VSCode Version: 1.1.1
- OS Version: Mac OS X

Steps to Reproduce:
1. Added following setting for indent with 2 spaces
   "editor.insertSpaces": true,
   "editor.tabSize": 2
2. Editor still formatting with 4 spaces.

**Comment by bpasero** [comment]
Might be our auto detection?

**Comment by alexandrudima** [comment]
@nitinbansal1989 These two settings get overwritten when opening a file with existing indentation and `editor.detectIndentation` is true. I will improve the description on these two settings to make that clear:

![image](https://cloud.githubusercontent.com/assets/5047891/15818286/ddf87208-2bdc-11e6-808c-ee986e38a212.png)

**Comment by nitinbansal1989** [comment]
Thanks.
