### ISSUE TITLE
VSCode documentation: codebasics needs to describe how to specify multiple patterns

### ISSUE THREAD

**Issue by marvingreenberg** [Microsoft/vscode#70828]
The advanced search windows supports specifying "files" to include or exclude.  (This is actually files/directories to include or exclude.)  But it is not documented how to separate the patterns if multiple are specified.  See:

https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

Using a space separator between patterns (which might be considered best) does not work.  Apparently separating with a comma (and no other whitespace) does.

**Comment by roblourens** [comment]
Good point, fixed
