### ISSUE TITLE
Advanced search does not allow filtering when directory paths include ","

### ISSUE THREAD

**Issue by marvingreenberg** [Microsoft/vscode#70830]
In a project where conventions name certain directories with commas in the path, VScode fails when trying to search within a folder:

Right-click Find in Folder yields a "Files to include" setting like
   
    ./TENA,RepositoryServer,trunk-3.2.2,Library,source,all/src

But this results in an error when executing the search "No folder in workspace named TENA"

Although undocumented (ref #70828 ) it seems that "," is a special character to delimit multiple patterns. There is no documentation describing how this pattern might be escaped, and attempts using '', ', and \ do not work.   Simply changing this delimiter to a space and documenting that would address this issue.  Alternatively, keeping commas as the delimiter, defining an approach to escape commas, and automatically escaping paths with commas when Right-Click Find in folder is executed would be sufficient.

**Comment by marvingreenberg** [comment]
Although not ideal, this apparently works:

    ./TENA[,]RepositoryServer[,]trunk-3.2.2[,]Library[,]source[,]all/src

**Comment by roblourens** [comment]
Good workaround, I didn't even realize that would work. This is covered by #16834, other special characters have the same problem
