### ISSUE TITLE
Tabs displayed incorrectly.

### ISSUE THREAD

**Issue by kmac720** [microsoft/vscode#70832]
Issue Type: <b>Bug</b>

All of the files in our project are 4 space tabs. Recently VSCode will display some of these files at having 2 space tabs. If I open them in another editor or notepad++ they show as having 4 tab spaces.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.96GB (17.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.8.1
coldfusion|ili|1.0.1
indent-rainbow|ode|7.4.0
vscode-react-native|vsm|0.9.0

</details>

**Comment by kmac720** [comment]
I turned off "Detect Indentation" and it appears to fix the issue, but odd that it's detecting two space tabs when no files are setup in this manor.

**Comment by alexandrudima** [comment]
@kmac720 Is it possible to share the files which have their indentation detected incorrectly?

**Comment by kmac720** [comment]
Not possible.

**Comment by alexandrudima** [comment]
@kmac720 Can you then do the following please:

* open a file where indentation is not detected correctly, e.g.
![image](https://user-images.githubusercontent.com/5047891/55107966-d3e70e00-50d2-11e9-8ad1-e20f2928a192.png)

* replace in file `^(\s*).+` in regex mode with `$1x`. e.g.
![image](https://user-images.githubusercontent.com/5047891/55108079-1577b900-50d3-11e9-9c33-e24fcbff3d7b.png)

This would leave intact the indentation in the file, while removing all relevant source code.

**Comment by kmac720** [comment]
And github doesn't support .cfm files... 

I converted to a .txt file and uploaded that. Honestly just turning off "Detect Indentation" has solved it for me. I had to turn that setting back on to re-create it. 

[test_file.txt](https://github.com/Microsoft/vscode/files/3015177/test_file.txt)

**Comment by johneriksson** [comment]
I am also experiencing the same issue with my project. Since about a month ago **some files** open with 2 space tabs instead of 4. I tried turning off "Editor: Detect Indentation" and it seems to have solved it for me too.
MacOS Mojave 10.14.3
VS Code 1.33.0
