### ISSUE TITLE
Color change for only specific variable similar to Atom

### ISSUE THREAD

**Issue by MariuzM** [Microsoft/vscode#70836]
Is it possible to change color similar to the way Atom does? 

https://imgur.com/wd33nrh

The above window in this picture will be VSC and bottom Atom. When i try to change the color of variable "test" or "test2" it also changes the color of the "document" so currently you can see both of them are in RED in vscode. But Atom works the way i would like the vscode to work.

When i do CMD + SHIFT + P and chose "Developer Inspect TM Scopes". For "test" and "test2" i get "variable" same goes for the "document", hence why they change both, could a feature be added to separate them?

**Comment by aeschli** [comment]
Both `document` and `test` are variables, so IMO the grammar is correct here to give it the same scope.
We use the https://github.com/Microsoft/TypeScript-TmLanguage as grammar, I think Atom uses it's own tree sitter based. Maybe it considers document a library variable, but that's IMO not really correct (`document` is only a built in variable in the browser environment). But feel free to request changes to the grammar at https://github.com/Microsoft/TypeScript-TmLanguage.

To colorize specific parts we have the editor decorations API. You could use that from an extension.
