### ISSUE TITLE
Option to auto-pin all

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7083]
I would like to have an option to auto-pin every editor.
An alternative naming is to disable preview tab.

My workflow is that I am used to having all the editors I navigate between in my history. I believe some of our users use it in the same way and with the june changes we might break their mental model.
Due to that we should introduce this setting such that we behave as before - nothing is preview, everything is pinned.

**Comment by bpasero** [comment]
+1, this is https://github.com/Microsoft/vscode/issues/2754
