### ISSUE TITLE
Bug: Disabling all extensions leads to whole computer crash

### ISSUE THREAD

**Issue by iamclaytonray** [Microsoft/vscode#70838]
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:
1. Disable all extensions

Basically, I just disabled all of my extensions and it not only crashed VSCode but also forced my laptop off. Unfortunately, I don't really have more information because I had to boot my computer back on. Let me know if there is anything else I can do to provide more info to help fix this issue.

My mid-2014 MacBook Pro specs are:

Processor: 2.5 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel Iris Pro 1536 MB
Storage: 500GB SSD

**Comment by sandy081** [comment]
@iamclaytonray Do you reproduce it consistently? If so, can you please try disabling extensions one by one and see which extension is causing it?

**Comment by iamclaytonray** [comment]
I'll have to do this at the start of next week. (Sunday or Monday.) Sorry!

**Comment by sandy081** [comment]
Ok

**Comment by iamclaytonray** [comment]
@sandy081 - not one single extension caused it to happen. I am able to get it to happen here and there when disabling every extension at once. I should also note that it's more prone when I have a lot of CPU-intensive stuff open. (iOS Simulator / Xcode, etc)

**Comment by sandy081** [comment]
Is it possible to get any crash reports to know why it is crashing?

**Comment by iamclaytonray** [comment]
Sure. How would I do that exactly? 😅

**Comment by sandy081** [comment]
@bpasero Can you help in how to get the crash reports?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
