### ISSUE TITLE
Test Manager crashes

### ISSUE THREAD

**Issue by MartinFeineis** [Microsoft/vscode#70834]
Issue Type: <b>Bug</b>

Our test engineers Visual Studio Test Manager crashes randomly. We got the following error message out of PS but are not sure how to proceed troubleshooting. Can you give some advice? 

PS C:\> Get-EventLog -LogName Application -Source "Microsoft Test Manager"

   Index Time          EntryType   Source                 InstanceID Message
   ----- ----          ---------   ------                 ---------- -------
   33022 Feb 26 09:44  Error       Microsoft Test Ma...            0 The description for Event ID '0' in Source 'Mic...
   32777 Feb 25 15:52  Error       Microsoft Test Ma...            0 The description for Event ID '0' in Source 'Mic...
   16369 Feb 07 11:48  Error       Microsoft Test Ma...            0 The description for Event ID '0' in Source 'Mic...

PS C:\> (Get-EventLog -LogName Application -Source "Microsoft Test Manager").Message
The description for Event ID '0' in Source 'Microsoft Test Manager' cannot be found.  The local computer may not have the necessary registry information or message DLL files to display the message, or you may not have permission to access them.  The following information is part of the event:'Exception was thrown from the UITest module.Stack Trace ==>   at Microsoft.VisualStudio.TestTools.UITest.Recorder.EventCaptureBase.HandleStoredException()
   at Microsoft.VisualStudio.TestTools.UITest.Recorder.LowLevelHookEventCapture.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by MartinFeineis** [comment]
Also some advice on how to get this issue to the right board will be appreciated. I don't have Visual Studio installed and can't use their feedback system.

**Comment by weinand** [comment]
Please file this issue against the extension you are using.
