### ISSUE TITLE
Fix broadcast service debt

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#70831]
While working on https://github.com/Microsoft/vscode/issues/70319 I have moved the `IBroadcastService`-service definition to common. However, there is only an implementation for electron-node (not electron-node-less). 

Looking at the service and it's usages it seems like a kitchen-sink service that should be avoidedby using "topic"-services, like a service that manages debug output or one that's about windows and themes.

**Comment by isidorn** [comment]
I am fine with dismantling it into smaller services and introducing one only for the debug use case

fyi @bpasero

**Comment by bpasero** [comment]
Yeah a good idea 👍

**Comment by weinand** [comment]
I've created https://github.com/Microsoft/vscode/issues/70835 for the debug case.

**Comment by bpasero** [comment]
Leaving `vscode:changeColorTheme` for @aeschli

**Comment by isidorn** [comment]
I have moved the debug stuff as covered by this item #70835
@aeschli if you like my changes from there I can do the same for your `vscode:changeColorTheme` and we fully get rid of the `broadcastService`.
