### ISSUE TITLE
vscode typescript debuging - hover tooltips do nor always work

### ISSUE THREAD

**Issue by PMoransais** [Microsoft/vscode#70848]
In VS Code latest version (1.32.3) debugging a Typescript file 

The line                        
       `this.item = res.value;` 
above the break-point (and thus processed) provides a correct tooltip description of the object in the variable res.value but yields an undefined value when hovering above this.item

![image](https://user-images.githubusercontent.com/19433579/54708358-9ce48b80-4b19-11e9-87a4-2857d3fc1707.png)

**this.item** = res.value;
![image](https://user-images.githubusercontent.com/19433579/54708659-4166cd80-4b1a-11e9-91ec-f5a785419a8b.png)

These types of problems were reported in 2017 #19750, 30286 and 24277.

Whatever the reason for the behavior it is clearly diminishing the value of the product and appears senseless: you assign a value that is known and shown in the tool tip and the variable receiving the assignment is shown as undefined. 

The assignment does take place correctly it is just the hover that is misreporting. Please note that this is a very frequent problem.

The chrome debugger  works without these problems.

Thanks for your help on this

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/24520
