### ISSUE TITLE
Cannot see logpoint or console output from Main Process

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#70849]
When debugging VS Code Main Process, no log point or console output is shown in the debug console.

**Comment by roblourens** [comment]
Most likely we are intercepting console.log somewhere and doing weird stuff but I will have to investigate later.

**Comment by roblourens** [comment]
I am seeing `console.log` output now.

**Comment by sbatten** [comment]
@roblourens since this was not working before, but you say is now working, i think we should place it in the milestone for verification
