### ISSUE TITLE
Add support for JSDoc's @inheritDoc for TypeScript

### ISSUE THREAD

**Issue by kohzihan** [Microsoft/vscode#7084]
- VSCode Version: 1.2.0-insider
- OS Version: Win 10

For TypeScript, for instance when a class implements an interface, it would be good if the IntelliSense would recognize JSDoc's `@inheritDoc` and display the JSDoc declared at the parent/interface level instead.

http://usejsdoc.org/tags-inheritdoc.html

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#8912
