### ISSUE TITLE
Can't save file after using git - fdatasync is now disabled for this session because it failed

### ISSUE THREAD

**Issue by X-Tender** [microsoft/vscode#70841]
- VSCode Version: 1.32.3 (1.32.3)
- OS Version: macOS High SIerra - 10.13.6

We have a problem with the following situation:
* We work on iMacs.
* Out develeopment server (where the files are placed and we work on) is a Ubuntu server with netatalk 2 Protocol.
* When I stage a file to git via CLI or via GUI (GitKraken) I cant save the File anymore.
* When I unstage it the error still exists.
* Other files can be saved, only the previously staged file is not saveable
* When I close and Open the file, still cant save
* When I open it in an another Error I can save the FIle
* When I restart VSCode the file can be saved again

In the vscode Devtools console the following error gets displayed:
```
extfs.ts:449 [node.js fs] fdatasync is now disabled for this session because it failed:  Error: EBADF: bad file descriptor, fdatasync
i.fdatasync.e @ extfs.ts:449
```
Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@bpasero Any fallback for `doWriteFileStreamAndFlush`?

**Comment by bpasero** [comment]
@joaomoreno that warning really does not mean a lot, we just print it. there is no behavioural change other than `fs.dataSync` did not succeed.

**Comment by X-Tender** [comment]
But the problem didn't happen when using an other Editor.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by X-Tender** [comment]
Here's a dump of the relevant part:
https://pastebin.com/X3NjE1Kj
In line 43 the fdatasync error appears after I pressed save.

**Comment by bpasero** [comment]
@X-Tender would you be willing and able to try to run VSCode out of sources to do some debugging? Steps are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run

**Comment by X-Tender** [comment]
Sure, I try it.

**Comment by X-Tender** [comment]
OK 've tested it now with a build from the repo and the issue didn't happened there. I've tried it about 50 times:

- make a change
- save
- stage file
- save
- unstage file
- save
etc.

It always worked, then I switched back to my installed VSCode and it took me just a few attempts to get the problem.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by X-Tender** [comment]
Sadly the issue happened there at the first shot.
I tried it again with the forked build and then it happend too ☹️

But the bad news also have a good news, I noticed (and that could be the reason why it didn't happend in the first place with the forked build) that the issue just happen when I open a Directory in vscode.
When I only drag a file in it the issue didn't happen (also on my installed version) But when I open a folder and pick a file form there the issue appear again.

**Comment by bpasero** [comment]
@X-Tender ok even when you run out of sources?

**Comment by X-Tender** [comment]
Yes. When I jsut drag a file in it the issue didnt appear. Only when I open a folder and select an file out of it. Must test if it also happen when i use a file which is not inside the choosen folder.

**Comment by X-Tender** [comment]
Yes it looks like when the open file is inside the selected folders structure the issue apperas. If I drag a file which is not inside the structure it don't happen.

**Comment by bpasero** [comment]
@X-Tender ok great, can you maybe open the debugger and select to break on error and make a change to see where it throws?

**Comment by X-Tender** [comment]
Will do it tomorrow. I'm now out of office.

**Comment by X-Tender** [comment]
Don't know if this helps. 
<img width="1146" alt="img1" src="https://user-images.githubusercontent.com/1413979/54809139-b523ea00-4c82-11e9-9784-63af077bf821.png">

<img width="1151" alt="img2" src="https://user-images.githubusercontent.com/1413979/54809140-b523ea00-4c82-11e9-8ce1-3296f40a69bc.png">

But couldn't I change the line where it sets canFlush = false; in the source and test what happen when he run it in and didn't disable the flush?
You just have to point me which file I have to look at :)

>// In some exotic setups it is well possible that node fails to sync

Would be also interesting what the "exotic setup" this cause the error. ist here maybe a way to get some more error feedback?

**Comment by bpasero** [comment]
@X-Tender cool stuff, can you comment out the flushing and simply do as if it was not enabled in the first place and see if that makes the file save? You probably end up with a different error elsewhere.

Anyhow, this error seems to originate from a place that is not under control of VSCode...

**Comment by X-Tender** [comment]
Hmm nope it didn't changed anything. :/
Looks like it's so exotic that it's not fixable.

**Comment by X-Tender** [comment]
Is it maybe possible to break into the function when in press "Save" so I can step through it and see where he quits?

**Comment by bpasero** [comment]
@X-Tender if you add a breakpoint into that method and maybe break on error too, and then save does that not bring you there?

**Comment by X-Tender** [comment]
Sorry no, as you can see the Callstack is pretty short. It also didn't break on error, I had to set a breakpoint.

**Comment by bpasero** [comment]
@X-Tender oh yeah, simply add the breakpoint into `doWriteFileStreamAndFlush`, that is where it all begins from.

**Comment by X-Tender** [comment]
I've stepped bit through the process and noticed that in the variable `writer` which is created by the `fs.createWriteStream` the `path` was the path to the file. After the error the `path` contains something like hat.

`"/Users/paul/Library/Application Support/code-oss-dev/Backups/aeed58d7ee276bd964519f125f1318a3/file/1f0b1f2af4b2d8597801e10ce2f6cf22"`

here's the whole content of `writer``
Before the error:
```
autoClose:false
bytesWritten:0
closed:false
fd:36
flags:"w"
mode:438
path:"/Volumes/clients/company/project/framework/cfg/webpack.settings.js"
pos:undefined
start:undefined
writable:true
_events:{error: ƒ, finish: ƒ, close: ƒ}
_eventsCount:3
_maxListeners:undefined
_writableState:WritableState {objectMode: false, highWaterMark: 16384, finalCalled: false, needDrain: false, ending: false, …}
destroyed:(...)
writableBuffer:(...)
writableHighWaterMark:(...)
writableLength:(...)
__proto__:WriteStream
```

After the error:
```
autoClose:false
bytesWritten:0
closed:false
fd:null
flags:"w"
mode:438
path:"/Users/paul/Library/Application Support/code-oss-dev/Backups/aeed58d7ee276bd964519f125f1318a3/file/1f0b1f2af4b2d8597801e10ce2f6cf22"
pos:undefined
start:undefined
writable:true
_events:{}
_eventsCount:0
_maxListeners:undefined
_writableState:WritableState {objectMode: false, highWaterMark: 16384, finalCalled: false, needDrain: false, ending: false, …}
destroyed:(...)
writableBuffer:(...)
writableHighWaterMark:(...)
writableLength:(...)
__proto__:WriteStream
```

**Comment by bpasero** [comment]
@X-Tender this Backups path is our way of backing up changes you make to the file in frequent intervals (each second) to support closing the editor without having to save. That should not cause issues though and is stored always on the same disk as where VSCode is installed itself.

**Comment by X-Tender** [comment]
Ok, thanks for the explanation. I'm just looking for everything "suspicious" :)

**Comment by X-Tender** [comment]
I don't know if that could be helpfull but I noticed that when I "Save" and the error occures that the file gets saved in the first place. VS code just didn't mark it as saved and the next save attempts are failing.

**Comment by X-Tender** [comment]
FYI. Since some VSCode Update the Error didn't appear anymore. So can be closed.
