### ISSUE TITLE
Nothing happens while extension installation

### ISSUE THREAD

**Issue by apotrebin** [Microsoft/vscode#70843]
- VSCode Version:
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
 
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. I had one of the older version on pc (don't know exactly)
2. Uninstall older version 
3. Install version 1.32.3
4. Open Vue project of mine 
5. There was a suggestion to install extension Vetur
6. Click Install
*result:* Looks like VS Code in process of installing extension but nothing happens for a long time.  
Also in **Developer: Toggle Shared Process** I see vs code tries to find not existing variable - 
![33449723c1](https://user-images.githubusercontent.com/7914938/54706220-8b76a000-4b68-11e9-8f16-dba7f0044138.png)

P.S. I tried to install previous versions but got the same behavior. 
(Also, I don't use a proxy)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
What is your TEMP folder setting? It looks like you have wrong TEMP folder path setting

**Comment by apotrebin** [comment]
@sandy081 Do you mean this? - 
![temp](https://user-images.githubusercontent.com/7914938/54845439-81d56f80-4d03-11e9-8493-0d9a5cc47f08.png)

**Comment by sandy081** [comment]
Yes
