### ISSUE TITLE
wrong avatar in git history

### ISSUE THREAD

**Issue by vintg** [Microsoft/vscode#70846]
Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. open git history
2. someone else's github avatar is displayed if they have a similar name (substr of mine?)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by usernamehw** [comment]
Is there git history in vscode?

**Comment by mjbvz** [comment]
This sounds like it is coming from an extension, likely gitlens or perhaps the github pull requests extension. Please determine which one provides the git history you are using and file this issue against them
