### ISSUE TITLE
Debug: Continue icon doesn't show

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70842]
Version: 1.33.0-insider
Commit: 1efaca21afeb983a8efdae6a6b142bd00276c563
Date: 2019-03-20T08:19:32.830Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

![image](https://user-images.githubusercontent.com/4033249/54703222-90e6d280-4af5-11e9-9082-3d2bc7c81534.png)

**Comment by isidorn** [comment]
Fixed in latest, sorry about that
