### ISSUE TITLE
Peek problem should have Quick Fix... button

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#70853]
Since we are trying to make the problem peek view more discoverable, I think it would make sense for it to also have the "Quick Fix..." button

![image](https://user-images.githubusercontent.com/323878/54711528-643bb680-4b07-11e9-847e-164008b7d504.png)

**Comment by sandy081** [comment]
@roblourens Quick fix light bulb is shown as you see in the picture. Might not be good if we show it again, is not it?

**Comment by roblourens** [comment]
I guess that when the peek view is shown, the cursor always is set on that problem initially so the lightbulb will appear. That's not true for the hover. So yeah that's probably fine.
