### ISSUE TITLE
VSCode shifts errors underlining when Perttier's multiline import formatting applies

### ISSUE THREAD

**Issue by DmitryKoterov** [Microsoft/vscode#70854]
Not quite clear, is it a bug in VSCode or in Prettier, but I bet 90% it's in VSCode, because it's VSCode who highlights errors in the text.

There is a bug somewhere when builtin VSCode's source.organizeImports feature is used together with Prettier (and probably with any other extension which rewrites the text). People sometimes prefer to use VSCode's built-in source.organizeImports feature ON SAVE which, among other things, places all imports on the same line. And this conflicts with Prettier when it formats imports at multiple lines: **if there is an error in the code, the underlining of this error shifts towards beginning of the file.**

I recorded a video which shows the effect, pretty easy to reproduce:
https://www.dropbox.com/s/apj5znzlqy8pub6/vscode-prettier.mp4?dl=0

- VSCode Version: 1.32.3
- OS Version: MacOS Mojave 10.14.3

Steps to Reproduce:

1. Install Prettier, turn on  `"editor.codeActionsOnSave": { "source.organizeImports": true  }` in settings.json.
2. Open a file with a big number of imports and an error in the file and reproduce what's shown on the video. When you hit Save, and there is an error, its underlining shifts left on every save and messes everything up.

Does this issue occur when all extensions are disabled? No

Corresponding issue at Prettier: https://github.com/prettier/prettier/issues/5995

**Comment by jrieken** [comment]
> built-in source.organizeImports feature ON SAVE which, among other things, places all imports on the same line.

Putting things on one line isn't what we do. I bet that this is an extension issue but I leave it to @mjbvz who works on code-actions-on-save

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by DmitryKoterov** [comment]
> Putting things on one line isn't what we do

I meant not everything on one line, but each individual import statement (i.e. all symbols related to one import) on the same line. Different import statements are still on different lines while using organizeImports. 

But it all doesn’t quite matter, this bug report is about error underlining shifting, not about organizeImports nor prettier. I mentioned organizeImports and prettier only to show how to reproduce the bug. 

I will try the latest vscode insiders build.

**Comment by jrieken** [comment]
> this bug report is about error underlining shifting, 

Where do those errors come from? After the error message we show something like `ts(1182)` or `tslint(7)`. Please check with those, stale, errors

**Comment by mjbvz** [comment]
@DmitryKoterov Did you have a chance to try on the latest builds?

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this issue
