### ISSUE TITLE
Transform case - add sentence / Pascal casing

### ISSUE THREAD

**Issue by StephenKoller** [microsoft/vscode#70858]
### Description
Would like to see 'Transform to Capitalized / Sentence Case / Pascal Case' as a basic editor option.

While `editor.action.transformToUppercase` and `editor.action.transformToLowercase` exist, `editor.action.transformToCapitalize` does not.

![image](https://user-images.githubusercontent.com/1561673/54717919-ae389280-4b2f-11e9-90b6-02320217662a.png)

### Examples
| Pre-transform        | Post-transform  |
|  ------------- | ------------- |
| lowercase to capital | Lowercase To Capital |
| UPPERCASE TO CAPITAL | Uppercase To Capital |
| snake-case-to-capital | SnakeCaseToCapital |

### Similar issues:
[Enable regular expression case changing](https://github.com/Microsoft/vscode/issues/12185)
More complex, possibly a better candidate for an extension.

[Text transform to `Capitalize`.](https://github.com/Microsoft/vscode/issues/58867)
This seems like a very similar request, but it was closed with the mod suggesting to implement in an extension. IMO it's not worth installing a whole extension just for this, and if upper / lower casing is already supported, it should be fairly trivial to add capital casing.

For the record, I would be interested in taking this on myself.

**Comment by rebornix** [comment]
@StephenKoller PRs are always welcome ;)
