### ISSUE TITLE
Is there any way to convert the Explorer window into tabs instead of stacked accordion?

### ISSUE THREAD

**Issue by gdeverlant** [Microsoft/vscode#70852]
Right now this is how the Explorer section if VSCode looks like:

https://github.com/BowlerHatLLC/vscode-as3mxml/issues/339#issuecomment-474973500

I would like to know if it is possible to make a button on the far right which will convert the OpenEditors/Multiverses/Outline/etc... into tabs instead?

![image](https://user-images.githubusercontent.com/26530975/54711429-30ce4b80-4b4a-11e9-9e6e-8913a43ece02.png)

The accordion is not practical and takes to much space.

**Comment by isidorn** [comment]
If it is taking too much space you can hide some views by right click -> hide

**Comment by gdeverlant** [comment]
No we need this change to reflect another IDE that we are porting to VSCode. We try to make the UI as seamless as possible for the old users of the other IDE.

**Comment by gdeverlant** [comment]
If anyone has a clue where to look for it please let us know.

**Comment by bgbruno** [comment]
> de some views by right click -> hide

also because I want see for eg "#outline" on full width 😀 - not just partial or switch with hiding other #panels 🙈
