### ISSUE TITLE
extension testing doesn't work on Linux

### ISSUE THREAD

**Issue by matepek** [Microsoft/vscode#70857]
With vscode version 1.1.32 it doesn't work. [see](https://travis-ci.org/matepek/vscode-catch2-test-adapter/builds/508980498)
```bash
$ npm test --silent
### VS Code Extension Test Run ###
Current working directory: /home/travis/build/matepek/vscode-catch2-test-adapter
Downloading VS Code into "/home/travis/build/matepek/vscode-catch2-test-adapter/.vscode-test/stable
Downloading VS Code 1.32.3
Downloaded VS Code 1.32.3
Running extension tests: /home/travis/build/matepek/vscode-catch2-test-adapter/.vscode-test/vscode-1.32.3/VSCode-linux-x64/code /home/travis/build/matepek/vscode-catch2-test-adapter/out/test --extensionDevelopmentPath=/home/travis/build/matepek/vscode-catch2-test-adapter --extensionTestsPath=/home/travis/build/matepek/vscode-catch2-test-adapter/out/test --locale=en
Failed to execute tests: Error: spawn /home/travis/build/matepek/vscode-catch2-test-adapter/.vscode-test/vscode-1.32.3/VSCode-linux-x64/code ENOENT
```

I changed the version to 1.1.30. IT works again. [see](https://travis-ci.org/matepek/vscode-catch2-test-adapter/builds/509133123)

[diff](https://github.com/matepek/vscode-catch2-test-adapter/compare/f250889246bc...37fcc85280a1)

**Comment by dgolovin** [comment]
I have the same problem, and 1.1.31 works forks for me.

**Comment by bpasero** [comment]
@octref can you follow up?

**Comment by glennsarti** [comment]
I think I'm experiencing the same thing.

My testing on Travis CI has stopped working for Linux builds but is still fine for MacOS.  My Windows Appveyor builds are fine also.

```
Running extension tests: /home/travis/build/lingua-pupuli/puppet-vscode/.vscode-test/vscode-1.32.3/VSCode-linux-x64/code /home/travis/build/lingua-pupuli/puppet-vscode/out/test --extensionDevelopmentPath=/home/travis/build/lingua-pupuli/puppet-vscode --extensionTestsPath=/home/travis/build/lingua-pupuli/puppet-vscode/out/test --locale=en
Failed to execute tests: Error: spawn /home/travis/build/lingua-pupuli/puppet-vscode/.vscode-test/vscode-1.32.3/VSCode-linux-x64/code ENOENT
Tests exited with code: -2
The command "npm test --silent" exited with 1.
```

https://travis-ci.com/lingua-pupuli/puppet-vscode/jobs/186261001

Travis CI doesn't mention any recent major changes in it's builder changelog at https://docs.travis-ci.com/user/build-environment-updates/

**Comment by glennsarti** [comment]
Initially I though it was because Travis is using an older version on Nodejs

> Now using node v8.11.3 (npm v5.6.0)

However both the MacOS and Linux builds are the same.

**Comment by glennsarti** [comment]
Oh I have a suspicion of what it is.... Just testing it out now.  I think there's an extra directory in the downloaded path ...

**Comment by glennsarti** [comment]
Hrmm... well that's weird.  I added some `ls` commands to see what was on disk in the Travis builder and apparently `.vscode-test` is empty.

```
### VS Code Extension Test Run ###
Current working directory: /home/travis/build/lingua-pupuli/puppet-vscode
Downloading VS Code into "/home/travis/build/lingua-pupuli/puppet-vscode/.vscode-test/stable
Downloading VS Code 1.32.3
Downloaded VS Code 1.32.3
Running extension tests: /home/travis/build/lingua-pupuli/puppet-vscode/.vscode-test/vscode-1.32.3/VSCode-linux-x64/code /home/travis/build/lingua-pupuli/puppet-vscode/out/test --extensionDevelopmentPath=/home/travis/build/lingua-pupuli/puppet-vscode --extensionTestsPath=/home/travis/build/lingua-pupuli/puppet-vscode/out/test --locale=en
Failed to execute tests: Error: spawn /home/travis/build/lingua-pupuli/puppet-vscode/.vscode-test/vscode-1.32.3/VSCode-linux-x64/code ENOENT
Tests exited with code: -2
The command "npm test --silent" exited with 1.
0.00s$ ls -al .vscode-test
total 8
drwxrwxr-x  2 travis travis 4096 Mar 21 07:49 .
drwxrwxr-x 15 travis travis 4096 Mar 21 07:49 ..
The command "ls -al .vscode-test" exited with 0.
0.00s$ ls -al .vscode-test/vscode-1.32.3/VSCode-linux-x64
ls: cannot access .vscode-test/vscode-1.32.3/VSCode-linux-x64: No such file or directory
The command "ls -al .vscode-test/vscode-1.32.3/VSCode-linux-x64" exited with 2.
```

**Comment by glennsarti** [comment]
Okay...so some initial digging.

1. The `https://github.com/Microsoft/vscode-extension-vscode` repo which holds that npm module has changed it's tagging system from `1.1.30` to `v.1.1.32` which may be coincidental.

The release dates for [vscode on npmjs](https://www.npmjs.com/package/vscode) shows that 1.1.31 and 1.1.32 shortly thereafter were only a day ago so that explains why things have suddenly gone bad.  1.1.30 was a month ago.

A quick look at the diff between the two....
https://github.com/Microsoft/vscode-extension-vscode/compare/1.1.30...v1.1.32

Shows some major work on the `bin/test` file shows that the functionality seems to have moved to a `vscode-test` module (https://www.npmjs.com/package/vscode-test) which is VERY new (7 days ago)

Interestingly is this line: https://github.com/Microsoft/vscode-extension-vscode/compare/1.1.30...v1.1.32#diff-f900621cc6a1719b5473baf0191f297bR12

It says that the testing should be in the `stable` folder which clearly doesn't exist in my example above.  It did exist on my Ubuntu 18.04 desktop though

Given the following log from a job
```
Downloading VS Code into "/home/travis/build/lingua-pupuli/puppet-vscode/.vscode-test/stable
Downloading VS Code 1.32.3
Downloaded VS Code 1.32.3
```

My hunch is that `unzipVSCode` (https://github.com/Microsoft/vscode-test/blob/master/lib/download.ts#L127) is failing silently.

**Comment by octref** [comment]
My bad, I just realized, `fs.mkdirSync` is not available in Node < 10.
So this line was failing: https://github.com/Microsoft/vscode-test/blob/master/lib/download.ts#L40

**Comment by matepek** [comment]
One more note. I tried to use the CODE_VERSION environment variable feature and noticed that if I change the version and I did run it with a different version before it won’t download the new version, it will just use the already downloaded one. I didn’t expect this behaviour.

**Comment by octref** [comment]
@matepek That'll be handled with https://github.com/Microsoft/vscode-extension-vscode/pull/155.

I'll try to keep existing env variables working, but they are implicit and I think it's better to move to https://github.com/microsoft/vscode-test in the long term.

**Comment by matepek** [comment]
@octref oh i see, it is new..

**Comment by octref** [comment]
This should be working again in vscode@1.33:
- https://travis-ci.org/octref/hellotest/builds/509629532
- https://github.com/octref/hellotest

Also I restored support for `CODE_VERSION` in 1.33.
