### ISSUE TITLE
Latest Code-insiders tar.gz fails to install, "LICENSE.txt: no such file or directory" 

### ISSUE THREAD

**Issue by tgilland95** [Microsoft/vscode#70860]
- VSCode Version: 1.33.0-insider 1efaca21afeb983a8efdae6a6b142bd00276c563
x64 
- OS Version: Manjaro linux 4.20 kernel

Steps to Reproduce:

1. aurman -S visual-studio-code-insiders (same with yay and aur directly)
2. Install will fail with the following output: 
```bash
==> Making package: visual-studio-code-insiders 1549487462-1 (Wed 20 Mar 2019 03:08:30 PM MDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading code_x64_1549487462.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    763      0 --:--:-- --:--:-- --:--:--   763
100   132  100   132    0     0    271      0 --:--:-- --:--:-- --:--:--   271
100 64.7M  100 64.7M    0     0  12.5M      0  0:00:05  0:00:05 --:--:-- 14.0M
  -> Found visual-studio-code-insiders.desktop
  -> Found visual-studio-code-insiders-url-handler.desktop
==> Validating source_x86_64 files with sha256sums...
    code_x64_1549487462.tar.gz ... Skipped
    visual-studio-code-insiders.desktop ... Passed
    visual-studio-code-insiders-url-handler.desktop ... Passed
==> Extracting sources...
  -> Extracting code_x64_1549487462.tar.gz with bsdtar
==> Starting pkgver()...
==> Updated version: visual-studio-code-insiders 1553070255-1
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat '/home/ty/.cache/aurman/visual-studio-code-insiders/src/VSCode-linux-x64/resources/app/LICENSE.txt': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
2019-03-20 15:08:38,937 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/ty/.cache/aurman/visual-studio-code-insiders


```

Does this issue occur when all extensions are disabled?: Yes

It looks like make expects a file names LICENCE.txt, but the tar.gz has LICENSE.rtf. Changing the filename manually allows the build to pass.

Please let me know of more info is needed :)

**Comment by KamranMackey** [comment]
I don't think this is up to the VS Code team to fix. I think you should leave a comment on the official AUR package letting them know the filename changed.

**Comment by tgilland95** [comment]
@KamranMackey oh that could be. However, the tar.gz provided by microsoft's official link to install the insiders edition also has the problem. 

If I:
- go to https://code.visualstudio.com/
- click on the insiders link (https://code.visualstudio.com/insiders)
- extract the tar.gz and look through the files
I meet the same error. Again, you can change the name of the file from 'LICENSE.rtf' to 'LICENSE.txt' trying to install again succeeds.

Do you think there's a better place for this issue? Thanks for the feedback

**Comment by tgilland95** [comment]
I found [this commit](9017c54660951e1529ab61f8d00852aa9dc787cc) changing .txt to .rtf from two days ago, It looks related but I'm not sure how to fix it.

**Comment by tgilland95** [comment]
It's just the package build on the AUR that needs updated. You were right haha sorry for the brain fart haha, thanks @KamranMackey
