### ISSUE TITLE
Group and abbreviate tabs with same filename base and different extensions

### ISSUE THREAD

**Issue by atomlin** [microsoft/vscode#70866]
Tab space is valuable and files with same base name and different extension have full file name. An option to group them together automatically and just have extension shown would be useful.

eg with sausage.abc selected
| Sausage.abc | .cde |

with sausage.cde selected
| ...cde | sausage.cde |

I saw a different issue #53687 that was closed as specific to C++ extension but this feature request would work on all files.

**Comment by isidorn** [comment]
Search for issue with label file-explorer and feature-request and you will find a duplicate

**Comment by atomlin** [comment]
I just went through all the issues with those labels and did not see any feature request that looked the same. This request is regarding the editor tabs. Can you provide pointer to the duplicate please.

**Comment by isidorn** [comment]
Aha you mean the editor tabs. Reopening and forwarding to @bpasero 
There might be a setting

**Comment by atomlin** [comment]
Should I be concerned that no one is assigned?
