### ISSUE TITLE
Can not edit in new tab

### ISSUE THREAD

**Issue by tonmoyhbk** [Microsoft/vscode#70863]
Hi

Just an annoying issue and tried to reproduce on other machine but looks unique. When I open a new tab using Ctrl+N, the tab is created but it's not editable.  So I can not copy paste anything for testing or intend. Anything I want to type can't be done unless I save the new tab as a file. 
Is there any setting I am missing?

**Comment by isidorn** [comment]
No. I can not reproduce this.
Can you reproduce using vscode insiders https://code.visualstudio.com/insiders/

**Comment by tonmoyhbk** [comment]
It is working on Insite. Also after the windows update, it was fixed. Thanks for the vs code inside as didn't have any idea about it
