### ISSUE TITLE
VS Code Sometimes Holds Onto File Handles For a Long Time

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/vscode#70865]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:
Unfortunately I don't have consistent repro step. The symptoms I see is that sometimes when I run a script/gulp task/etc. that needs to access some folders, it fails due to access denied errors:
![image](https://user-images.githubusercontent.com/21112697/54725486-7ed45680-4b2c-11e9-82d4-b638f91811a9.png)

In Process Explorer I can see that the proces holding onto file handles is a VS Code process:
![image](https://user-images.githubusercontent.com/21112697/54725330-ec33b780-4b2b-11e9-8a9f-6119176a64d2.png)
![image](https://user-images.githubusercontent.com/21112697/54725374-0ff6fd80-4b2c-11e9-8b65-f68a4e72f1d1.png)

So far the only way I have found to release the file handle is to close VS Code or kill the offending process via PowerShell.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/29407
