### ISSUE TITLE
paths.normalize(): perf regression

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7086]
Running the following test with profiling enabled shows that recent changes to paths.ts cause a major performance regression:
* open the monaco folder
* expand some folders
* click refresh 10 times

Before:
![image](https://cloud.githubusercontent.com/assets/900690/15700429/1f71c674-27d4-11e6-83b6-89732fc2e508.png)

After:
![image](https://cloud.githubusercontent.com/assets/900690/15700443/2ba6d3bc-27d4-11e6-90a4-31194c1419f2.png)

[profiles.zip](https://github.com/Microsoft/vscode/files/292775/profiles.zip)

**Comment by jrieken** [comment]
impossible ;-)

**Comment by jrieken** [comment]
Seems like it gets into the deopt-state cos it was optimised to many times...

**Comment by bpasero** [comment]
Sorry I have to reopen this because I notice that the UI is freezing when I do a `gulp watch` from the command line while having Code open. I profiled the explorer refresh again as well as starting a profile before running `gulp watch` and measuring after this is done (vscode sourcecode workspace):

**Explorer refresh new**
![image](https://cloud.githubusercontent.com/assets/900690/15734620/e712d5de-2891-11e6-9026-e12db2390f65.png)

**Explorer refresh old**
![image](https://cloud.githubusercontent.com/assets/900690/15734628/06cc9fc2-2892-11e6-9d8c-8570883129f4.png)

**Compile all new**
![image](https://cloud.githubusercontent.com/assets/900690/15734633/0fa09d10-2892-11e6-8b74-f48791c76646.png)

**Compile all old**
![image](https://cloud.githubusercontent.com/assets/900690/15734644/1c99f052-2892-11e6-9c2c-21cd464d95b9.png)

[profiles.zip](https://github.com/Microsoft/vscode/files/294849/profiles.zip)

**Comment by jrieken** [comment]
@bpasero I don't understand how that is related to `gulp watch`?

**Comment by jrieken** [comment]
might be an optimisation I removed to do nothing in case of an already normal string...

**Comment by bpasero** [comment]
@jrieken the gulp watch causes file events to be triggered in relatively short time frame that probably spam our listeners in the window that all do normalization.

I think spamming file events is a sensitive topic for the workbench because many listeners are in the UI thread and most of them do path/uri magic. We could try to pull out more of that to the file watcher process but nevertheless it is a good test case for measuring performance in path/uri land.

**Comment by jrieken** [comment]
@bpasero Please check this again if you don't mind. I took to shortcut to figure out first if a path is normal  - which in case of `gulp watch` all paths are. The [implementation](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paths.ts#L167) doesn't use a regex anymore, is more correct than before, esp wrt double slashes. The sad part is that using `charCodeAt` isn't much faster than a regex...

**Comment by jrieken** [comment]
Ok - hold on. RegEx for the win! Using `/\/\.\.?\/|\/\.\.?$|^\.\.?\/|\/\/+|\\/` for checking posix paths is magnitudes after (23ms vs 120ms)

**Comment by bpasero** [comment]
@jrieken yeap, back to good, thanks!
