### ISSUE TITLE
After opening the javascript file, the computer CPU soared

### ISSUE THREAD

**Issue by feelingsky** [Microsoft/vscode#70877]
When you open up a javascript file, it's going to get really stuck and it's going to take up a lot of CPU

**Comment by sanket-bhalerao** [comment]
facing similar issue for typescript.
intellisense popout takes too long or it never appears just shows loading and the cpu consumption is around 30% for vscode insiders.
memory consumption for vscode is around 3000mb.

vscode build details
Version: 1.33.0-insider (user setup)
Commit: edd2c737f9b6f08cd0e30050b441cd262eb7f0d8
Date: 2019-03-21T06:19:48.689Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as more information needed
