### ISSUE TITLE
In Terminal, while typing first command of terminal, the terminal info and directory path get cleared

### ISSUE THREAD

**Issue by eSachin** [Microsoft/vscode#70878]
Issue Type: <b>Bug</b>

Open terminal. You will see the terminal information and path of current directory like,

Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. All rights reserved.

e:\Dev-Visual-Code\web> 

while typing first command of terminal, above all the information get cleared and user inputs only comman
![terminal](https://user-images.githubusercontent.com/11748261/54736469-3622a900-4bd1-11e9-990f-8e29fb8e31e9.png)
![terminal](https://user-images.githubusercontent.com/11748261/54736486-3f137a80-4bd1-11e9-9135-d5d06f581f59.png)

d

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (9.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.17.0

</details>

**Comment by beastdestroyer** [comment]
This has been a long time issue due to terminal rendering and many more issues. You're not alone. Hopefully ConPTY will fix it (available in Windows 10 19H1, and then VSCode)
