### ISSUE TITLE
vs lost  tmp file

### ISSUE THREAD

**Issue by peizhelun** [Microsoft/vscode#70872]
sometimes , when I open the vs  by click ,I found out my tmp files lost . should I must save my tmp files everytime?  By the way ,when openning a file  use vs,tmp files also may lost.

**Comment by peizhelun** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [vscode fills /tmp with sock files (#20490)](https://www.github.com/Microsoft/vscode/issues/20490)
Not resolved yet.

**Comment by isidorn** [comment]
These are not valid reproducable steps.
File an issue with reproducable steps so we can actually try to do something to fix this.
