### ISSUE TITLE
color decorators control

### ISSUE THREAD

**Issue by RRM1000** [Microsoft/vscode#70870]
Can you sort out the colour palette control? It hasn't worked for ages, and now it's inserting random colour squares in the middle of the .jsx code (after getting the latest VS Code version)!

e.g.
<div cla[]sName="App-home-subheading">

Colour Square: []

<img width="163" alt="Untitled" src="https://user-images.githubusercontent.com/18437575/54729497-dc18e800-4bbe-11e9-9950-3697fdb28b98.png">

**Comment by aeschli** [comment]
@RRM1000 Can you paste the example code that shows that?
Is it just temporary while editing?

**Comment by aeschli** [comment]
BTW, you can turn off the color decorators with `editor.colorDecorators: false`.
But I still like to know how you got your screenshot. I don't see any colors defined there.
