### ISSUE TITLE
Feedback on task and command documentation.

### ISSUE THREAD

**Issue by bolinfest** [Microsoft/vscode#70876]
I've just spent several hours trying to figure out whether the following is possible using only public documentation and it has been...challenging. Part of this is asking about what is possible whereas the other part is identifying shortcomings in existing docs.

**Here is what I am trying to do**

I want to build an extension that lets the user type `bb //foo:bar` in the Command Palette and have it open a new terminal that runs `buck build //foo:bar`. Note this should be able to take a variable number of arguments, so `bb @mode/opt //foo:bar` and `bb //foo:bar //foo:baz` should also be possible.

Taking a step back, this is intended to be a workaround for the fact that it is not possible for an extension to draw its own toolbar GUI into the VS Code window. Ideally, we would also have autocomplete support to help the user fill in the argument after `bb `, but that is lower priority. (Some sort of fixed-size quick pick is not an appropriate option here because it is not practical to enumerate all of the Buck build targets up front, particularly when operating in a large repository.)

**My Research**

At first glance, assuming this was possible, I suspected the building blocks would be one or both of [commands](https://code.visualstudio.com/api/extension-guides/command) or [tasks](https://code.visualstudio.com/docs/editor/tasks).

**Commands Documentation**

I started looking at commands first, partially because I thought this would be more likely to do what I wanted and partially because the docs for commands were far simpler than those for tasks. This certainly seemed promising, as the command docs mention things like:

> Some commands take arguments that control their behavior.

and the primary code sample showed a command handler taking an argument:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  const command = 'myExtension.sayHello';

  const commandHandler = (name?: string = 'world') => {
    console.log(`Hello ${name}!!!`);
  };

  context.subscriptions.push(vscode.commands.registerCommand(command, commandHandler));
}
```

I tried running that example. (By the way, that code sample does not appear to be valid. TypeScript tells me **"Parameter cannot have question mark and initializer."**, so it has to be `name` rather than `name?`.)

After adding the appropriate snippet to my `package.json`:

```
  "contributes": {
    "commands": [
      {
        "command": "myExtension.sayHello",
        "title": "bb"
      }
    ]
  },
```

If I enter `>bb` in the command palette and run it, it works fine, but if I enter `>bb //foo:bar`, the palette tells me **No commands matching** and doesn't let me run anything. At this point, commands no longer seemed like a fruitful path to pursue.

**Searching GitHub Issues**

Before diving into the tasks documentation, I tried searching a combination of existing GitHub issues and StackOverflow posts to see if I could find an answer that way first. For example, these two links seemed promising:

https://github.com/Microsoft/vscode/issues/1574
https://stackoverflow.com/questions/45582698/is-it-possible-to-pass-arguments-to-a-task-in-visual-studio-code

And this ultimately took me to:

https://github.com/Microsoft/vscode/issues/64214

With some difficulty, I got the `Echo input` example to run. Once again, the code sample did not run verbatim: `label` had to be changed to `id` and each `type` also had to be updated: `pickString` instead of `pick` and `promptString` instead of `prompt`. (Note that [#64214](https://github.com/Microsoft/vscode/issues/64214) is locked, so I could not suggest changes there.)

The flow to test this out feels a bit convoluted (though I get it):

* Choose **Tasks: Run Task** from the Command Palette.
* Choose **Echo input** from the quick pick.
* Type in the free-form input box for `echoPrompt`.
* Pick a value from the dropdown for `echoPick`.
* Pick a value from the dropdown for the node process. (Incidentally, I ran `rg pickNodeProcess` over the `vscode` repo and did not get any matches, so I have no idea where support for this comes from.)

Note that if you want to change a previous value, you have to fill out the form all over again and remember what you already entered. I used a combination of this example and the docs to make progress.

**Tasks Documentation**

*Before I get into this section, I feel that it is important to note that the [Tasks documentation](https://code.visualstudio.com/docs/editor/tasks)* **never explains what a "task" is!** *Even more confusing for me, at least given my primary objective, was figuring out that the tasks I define in the `.vscode/tasks.json` in my extension project serve the purpose of developing my extension. They are not, as I was trying to use them, there for the purpose of making tasks available to those who* **installed** *my extension*.

In trying to streamline the experience of launching the "Echo input" task, I discovered the [Binding keyboard shortcuts to tasks](https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks) docs and added the following to my `keybindings.json`:

```
  {
    "key": "ctrl+h",
    "command": "workbench.action.tasks.runTask",
    "args": "Echo input"
  },
```

Now if I hit `ctrl+h`, I would go straight to the third bullet in the list of five bullets above. Definitely an improvement!

I did not have a chance to play with all of the other options for a task yet (like `presentation`, `args`, or `problemMatcher`). Again, I was still trying to have a cleaner association with the Command Palette. For example, it is fairly common to alternate between running `buck build` and `buck test`, so assuming the last two commands I ran were `bb //foo/...` and `bt //foo/...`, I could hit `cmd+shift+p` to quickly pop open the Command Palette and choose the appropriate one. In practice, this would give me quick keyboard access to command I am running frequently without formally configuring something via `keybindings.json`.

Playing around some more, I discovered that I could enter `task echo input` (or `task bb`, in my case) to trigger my task from the Command Palette, but I still could not do something like `task echo input //foo:bar` to specify the value of `echoPrompt` in the same line.

If I had things working the way I wanted, the one keyboard shortcut I *would* want to setup would be to map `ctrl+b` to something that opens the Command Palette with `bb ` pre-populated so that you could type your Buck build target straight away (ideally defaulting to the last thing you built).

**Task Provider Documentation**

Again, I was pretty confused that when I ran my extension, the tasks defined in the `.vscode/tasks.json` file were not recognized in the window that opened when I hit F5. Somewhere around this time, I suspected that a *task provider* might be the thing that I needed.

Similar to my frustration with the Tasks documentation, the [Tasks Provider](https://code.visualstudio.com/api/extension-guides/task-provider) docs don't really explain what one is or why you would use it. It jumps into information about auto-detection, but I'm not sure what that is or why I should care about it. All I want to do is define a task in my extension for others to use.

This is another instance where the code samples appear to be out of date (unless this is because I'm using Insiders?). For example, there's this:

```ts
let task = new vscode.Task(
  { type: 'rake', task: 'compile' },
  'compile',
  'rake',
  new vscode.ShellExecution('rake compile')
);
```

I'm not sure where that comes from, but the thing I got to compile is this (as you can see, the types are quite different):

```ts
  let task = new vscode.Task(
    {
      type: 'buck',
      command: 'build',
      arg: '//xplat/nuclide/fb-JavaLib/...',
    },
    vscode.TaskScope.Global,
    /* name */ 'buck build',
    /* source */ 'buck',
  );
```

Also, in the code sample from the docs, it feels like the arguments to `new vscode.Task` duplicate information, so I really have no idea what is going on.

Unable to compose any sort of mental model for what a task provider is, this is about where I gave up. 

**Next Steps**

Looking at the source for VS Code itself, it seems that the internal `registerQuickOpenHandler()` API is basically what I want. Is this something the team would be willing to explore as a proposed API?

**Comment by alexr00** [comment]
@bolinfest thanks for the feedback on the tasks documentation in particular. I will add some more intro stuff to the beginning of the documentation. It certainly does assume a base level of knowledge that is not necessarily safe to assume in documentation like that.

Your goal is to make running various `buck` actions easy, and to maintain some kind of history of recently run action + parameter sets? Unless you add a command for every set of parameters, there is no way supported way for you to just type everything into the command palette in one go.

To get the history of recently run with Tasks, you'd need to make a task provider that provides a task for every single combination of parameter. Quite reasonably, that doesn't seem like what you're looking for. 

You could use commands to do this in an ok way: 
- Have a `bb` command
- When the command is executed, show a quick pick with the recent parameter sets the user has used (your extension would need to maintain the list of recent parameter sets). One of the options could be to "start over" and have no parameters.
- When the user selects one of the recent parameter sets, you then show an input box prefilled with the recent parameter set the picked.

**Comment by bolinfest** [comment]
@alexr00 Thanks for the detailed response and suggested workaround! I think I'll focus on #70889 since if we can make that work, that seems like a more elegant solution (and hopefully useful to others, as well).

You can feel free to close this unless you want to leave it open as an action item for yourself to address the various documentation issues?

**Comment by alexr00** [comment]
I'm going to leave it open as an action item to improve the tasks documentation 😊. We don't have a timeline for when (or if) we will do #70889. Because of that, you might want to consider looking into other ways to accomplish what you want!

**Comment by alexr00** [comment]
Closing since this is a March issue. I'll be adding additional tasks documentation this week.
