### ISSUE TITLE
Flaky test: showQuickPick, accept first

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#70887]
Have seen this test failing more often recently (https://dev.azure.com/vscode/VSCode/_build/results?buildId=16591). Disabled it for now.

[`test('showQuickPick, accept first', async function () {`](https://github.com/Microsoft/vscode/blob/18c7f9148426a0fbfc87dc5da48b656cfd0c1d7e/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts#L384)

**Comment by bpasero** [comment]
@chrmarti I also had to disable `test('showQuickPick, keep selection (Microsoft/vscode-azure-account#67)'` due to https://dev.azure.com/vscode/VSCode/_build/results?buildId=16838

**Comment by bpasero** [comment]
@chrmarti looks like showWorkspaceFolderPick is also failing (see https://dev.azure.com/monacotools/Monaco/_build/results?buildId=46259)

**Comment by joaomoreno** [comment]
@chrmarti  Let's fix this or close it if already fixed.
