### ISSUE TITLE
Splitview: support scrolling when all views are at a minimum

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#70888]
The absence of a vertical scrollbar on the side bar impedes discoverability of some of the sections when operating with limited overall window height. For example in Debug view:
![junk](https://user-images.githubusercontent.com/6726799/54743806-1ed9c080-4bbd-11e9-8437-6b8c9240169b.gif)

If you don't want to add a vertical scrollbar, how about a visual cue at the bottom of the sidebar to hint that there's more below? User could then resize the window or collapse visible panels to discover what else is available.

- VSCode Version: 1.32.3
- OS Version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
This is true for all split views, forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
#64188
