### ISSUE TITLE
Stuck 

### ISSUE THREAD

**Issue by YangZhongLou** [Microsoft/vscode#70881]
Issue Type: <b>Bug</b>

Stuck with loading files from disk. 

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T02:00:46.035Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (10.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.7.8
flutter-snippets|ale|0.0.2
dart-code|Dar|2.24.0
flutter|Dar|2.24.0
python|ms-|2019.2.5558
cpptools|ms-|0.22.0
Go|ms-|0.9.2
awesome-flutter-snippets|Nas|2.0.0
java|red|0.41.0
rust|rus|0.5.4
vscode-lua|tri|0.12.4
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.1

</details>

**Comment by isidorn** [comment]
Please follow these steps and file a useful issue https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by YangZhongLou** [comment]
Must be one of the installed extensions. I closed all the extensions and I can't reproduce this issue.
