### ISSUE TITLE
Explorer: adopt resolveMetadata property

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#70880]
`IFileService.resolveFile(s)` has a new option `resolveMetadata` that controls if `mtime`, `size` and `etag` should be resolved or not. This can be an expensive operation for remote file systems and thus should only be enabled when the explorer is sorted in a way that these properties are needed. 

For now I hardcoded `{ resolveMetadata: true /* TODO@isidor only do this when needed */ }` in 3 locations of the explorer, but this should be driven by the sort setting.

//cc @jrieken

**Comment by isidorn** [comment]
Makes sense, I can look into this.
