### ISSUE TITLE
VSCode unable to find any tasks when you use a certain regex as problemMatcher pattern.

### ISSUE THREAD

**Issue by SeWiSy** [Microsoft/vscode#70882]
- VSCode Version: 1.33.0-insider / commit ...7f0d8
- VSCode Version: 1.32.3 / commit ...eaae4
- OS Version: Windows 10 Pro Build 17134

VSCode shows no tasks to run when you use certain regular expressions as `regexp` in `pattern` in `problemMatcher`. It fails to recognize any tasks (even other tasks.)
`Terminal > Run Task > No task to run found`

Steps to Reproduce:

1. Create tasks.json
2. Create this task: 

> {
            "label": "Angular Linting",
            "type": "shell",
            "command": "ng lint",
            "problemMatcher": {
                "pattern":[
                    {
                        `"regexp": "^(ERROR).*?([^\\s]*)[(\\d+).*?(\\d+)(.*)$"`,
                        "severity": 1,
                        "file": 2,
                        "line": 3,
                        "column": 4,
                        "message": 5,
                    }
                ]
            },
        }

Does this issue occur when all extensions are disabled?: Yes (Insider)

Background: I wanted to write a problem matcher for the Angular CLI "ng lint" command, with example output:
`ERROR: c:/Code/Project/Test/e2e/app.po.ts[4, 5]: expected call-signature: 'navigateTo' to have a typedef`

By the way, the [Regexp playground](https://regex101.com/) recommended in [the problem matcher guide](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) seems to use a different syntax than VSCode.

**Comment by alexr00** [comment]
That's not a valid regular expression. However, tasks shouldn't fail to enumerate because of it.
