### ISSUE TITLE
Check failed: (isolate->snapshot_blob()) == nullptr Unable to launch VS Code on Windows

### ISSUE THREAD

**Issue by mnjit20** [Microsoft/vscode#70895]
- VSCode Version: 1.32.3
- OS Name: Microsoft Windows 10 Enterprise
- OS Version: 10.0.16299 N/A Build 16299

Steps to Reproduce:

1. It was working I just restarted my computer and at the time of restarting I was not knowing that some visual code update is going on or have started which seems to be got distrubed due to restart and then after restart of laptop its stopped working.
2. while trying using CLI it's giving  this error

#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 00000053D4DCF160

Does this issue occur when all extensions are disabled?: Yes/No: 
Yes the same issue is occuring

#
# Fatal error in , line 0
# Check failed: (isolate->snapshot_blob()) == nullptr.
#
#
#
#FailureMessage Object: 000000E959B8F010

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by mnjit20** [comment]
![visual-code](https://user-images.githubusercontent.com/6074872/54826038-38f3cb80-4caf-11e9-8674-d3e8e5e1f196.png)
Hi, @joaomoreno please find attached screenshot, and when I open it from the desktop then nothing is happening.

**Comment by annokr** [comment]
Have the same issue, VS Code doesn't launch:

![image](https://user-images.githubusercontent.com/16205499/54908687-c40bd600-4ee8-11e9-811d-a4ae8951d7da.png)

**Comment by joaomoreno** [comment]
Does it start with a new user data dir `code --verbose --user-data-dir FOLDER_NAME`?

**Comment by mnjit20** [comment]
@joaomoreno No still the same, I have tried with the command you have shared.

**Comment by mnjit20** [comment]
@joaomoreno : please let me know if any further details required because I am going to get it re-installed. thanks. any other system log details required then let me know.

**Comment by joaomoreno** [comment]
No, not really. Please reinstall and let me know if that fixed it.

**Comment by mnjit20** [comment]
@joaomoreno  no other solution at this moment right, without re-installing?

**Comment by joaomoreno** [comment]
It shouldn't be too much of a hassle to reinstall VS Code, please give it a try.

**Comment by mnjit20** [comment]
just reinstalled the latest version and its solved.
