### ISSUE TITLE
Settings incorrectly escaping '(' and ')' in Windows paths.

### ISSUE THREAD

**Issue by loudambiance** [Microsoft/vscode#70898]
Issue Type: <b>Bug</b>

Try to update a path in User Settings using the UI with a path that contains an '(' or an ')', for example: C:\Program Files (x86)

You will receive a message stating that:
Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

If you "Open Settings", you will see that the '(' and the ')' has been escaped. You can remove the preceding '\', which allows the settings file to be saved. 

Any edits to the path in the UI causes the path to complain about being invalid again.

For specificity, I was updating the "Path to Makensis" on the NSIS extension when this occurred.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
project-manager|ale|10.4.0
vscode-sqlite|ale|0.6.0
gitignore|cod|0.6.0
flask-snippets|cst|0.1.0
autoit|Dam|0.2.2
mumps|dgi|0.1.2
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.5.1
rest-client|hum|0.21.2
nsis|idl|3.16.1
plantuml|jeb|2.10.7
gitignore|mic|1.0.1
mssql|ms-|1.4.0
python|ms-|2019.2.5558
PowerShell|ms-|1.11.0
autodocstring|njp|0.2.3
vscode-gitignore-generator|pio|1.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
hl7tools|Rob|1.9.7
git-add-remote|sam|0.0.2
jinjahtml|sam|0.8.0
trailing-spaces|sha|0.2.11
sort-lines|Tyr|1.8.0
vscode-icons|vsc|8.3.0
vscode-todo-highlight|way|1.0.4
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@roblourens Forwarding to you for settings editor case

**Comment by roblourens** [comment]
I can't repro this. We just set the setting with that string as-is, I don't know why it would be escaped. Can you show exactly what you set and what the escaped result is?
