### ISSUE TITLE
ALT + SHIFT vertically scrolls all open windows simultaneously

### ISSUE THREAD

**Issue by emveeoh** [microsoft/vscode#70899]
Often, I am comparing two GIT versions of a long file and editing a third file. It would be wonderful if we could scroll all open files simultaneously, rather than have to manually scroll each pane independently. 

![Capture](https://user-images.githubusercontent.com/16849690/54757611-f358d500-4bc0-11e9-8308-9aeea65562f1.PNG)

Please add the ability to scroll all open code editor windows simultaneously when the user holds the ALT + SHIFT and then scrolls the page using the mouse, the mouse scroll wheel, arrow keys or page-up/page-down keys.

Thank you!

**Comment by Luifr** [comment]
I`d like to take this one
