### ISSUE TITLE
Terminal: pressing Escape closes the terminal panel

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#7089]
- VSCode Version: 1.2.0 Insider
- OS Version: Windows 10

Steps to Reproduce:

1. open the terminal panel
2. type some text
3. press Escape

What happens: the text is removed (that's expected), and the terminal panel is immediately closed (unexpected).

**Comment by Tyriar** [comment]
Duplicate of #6455, will be coming in 1.3.0
