### ISSUE TITLE
Menus Scroll up automatically, submenu text not drawn

### ISSUE THREAD

**Issue by dirtandgrass** [microsoft/vscode#70896]
Issue Type: <b>Bug</b>

Have vscode menus _not_ fit on the screen (set a low resolution/height)

Open a menu (i believe file is the longest)
Scroll to the bottom, 
- it automatically scrolls up
Try to access a submenu, (must not be visible before scroll)
eg: File->Preferences
- submenu items are rendered a few pixels tall with no text

![image](https://user-images.githubusercontent.com/2494598/54752064-2ac08500-4bb3-11e9-88b1-6a8627e83e30.png)

This is an issue because I teach and use VSCode extensively on a projector, with scaling turned up, (to increase visibility throughout windows) for students. (not only in vscode)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (11.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.8
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.8.1

</details>

**Comment by sbatten** [comment]
this issue should be resolved by now.
