### ISSUE TITLE
Using eval() returns a not created variable

### ISSUE THREAD

**Issue by elshobokshy** [Microsoft/vscode#70890]
I've got this code that is telling me : `Undefined variable '$tab.`

```
$cacheManager = new \Cache\Manager(\Cache\Driver\StorageInterface::MEMORY_STORAGE);
eval($cacheManager->getCache());
self::$products[$id_thematique] = $tab;
```

Thing is, the varibale IS defined in the result of the `eval()` function, is this a bug? Or it's normal that it can't detect the result of the `$cacheManager`?

**Comment by weinand** [comment]
What language is this?
How is this related to VS Code?

**Comment by elshobokshy** [comment]
@weinand it's PHP. It's related in the sense that the undefined variable issue is in VS Code :-)

**Comment by weinand** [comment]
It is a php issue. Please file the issue against the php extension you are using.
