### ISSUE TITLE
intelisense problem

### ISSUE THREAD

**Issue by MasoodRezazadeh** [Microsoft/vscode#709]
there is no code suggestions for OVERRIDE ... last night it tooks till 6 AM for me to figure out that in DbContext i should  override OnConfiguring with DbContextOptionsBuilder parameter not DbContextOptions ...

**Comment by jrieken** [comment]
Please provide details steps include a code sample so that we can understand and reproduce

**Comment by MasoodRezazadeh** [comment]
```
public class AvaContext: DbContext
	{
		public DbSet<Place> Places { get; set; }
		public DbSet<Location> Locations { get; set; }
		
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
			
		}
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			var appEnv = CallContextServiceLocator.Locator.ServiceProvider
                            .GetRequiredService<IApplicationEnvironment>();
			optionsBuilder.UseSqlite($@"Data Source={appEnv.ApplicationBasePath}/../apiava/avaDB.db");
		}
    }
```

using EntityFramework 7 i created this context , for adding db connection query string ```OnConfiguring``` method should be overriden and in vscode intelisense not seggesting that or ```OnModelCreating```

**Comment by jrieken** [comment]
@MasoodRezazadeh Do I understand correctly that this is a feature request for IntelliSense helping you to implement a method?  Like so 

```
public class AvaContext: DbContext
    {
        public DbSet<Place> Places { get; set; }
        public DbSet<Location> Locations { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

        }
        OnCon<IntelliSense> -> Propose to override?
    }
```

**Comment by MasoodRezazadeh** [comment]
@jrieken Yes i Thought this feature should be available for newbies like me

**Comment by jrieken** [comment]
ok. understood. moving to OmniSharp cos they drive the C# features

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#346
