### ISSUE TITLE
need some visual feedback when the task is done (add post action to tasks)

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/vscode#7090]
Currently there is no way to tell if a script is running other than a spinning bar in the bottom which is hard to see. If the task doesn't spit any output than there is no way to know if it's still running or finished other than by looking at that bar. Would be nice to get something more visible and explicit.

**Comment by dbaeumer** [comment]
This should be addressed using some postAction property on a task.

**Comment by alexr00** [comment]
This postAction could also do some processing on the last line of the output so that a success of fail could be reported.

**Comment by grimpunch** [comment]
as mentioned in #12466 closed against this task, if post actions could trigger sound playback (for an alert) that would be useful, I arrived at this bug while searching for this functionality in the editor.

**Comment by NicksenDK** [comment]
Also very interested in seeing a feature that would allow me to enable a sound playback on code completion/failure.

**Comment by alexr00** [comment]
We now show task status in terminal tabs.
