### ISSUE TITLE
Update imports takes too long to show on large projects

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#70905]
This is a duplicate of https://github.com/Microsoft/vscode/issues/65112, which was supposedly fixed/closed, however this still appears to be an issue for the large project I'm currently working on.

(Since that issue is now locked, I am forced to open a new issue here.)

VS Code 1.32.3
TypeScript 3.3.3333

/cc @samijaber

**Comment by mjbvz** [comment]
I see this in the VS Code codebase too. Perf seems to have regressed at some point.

Opened https://github.com/Microsoft/TypeScript/issues/30535 to track this upstream
