### ISSUE TITLE
Open or close a folder without reloading?

### ISSUE THREAD

**Issue by kanlukasz** [Microsoft/vscode#70901]
It is possible to open or close folder in VSCode **without reload**?
It a little strange that program must have reload if we just open folder....

In addition, this is a problem if you have previously opened other tabs without any folder

I have some habits from Sublime, where it wasn't a big problem ( _comparing is not my goal_ ). I just opened the folder and it was added - nothing simpler.

GIF for better understanding:
![](https://i.stack.imgur.com/o7dTO.gif)

**Comment by bpasero** [comment]
Currently not possible, but we have an issue logged to look into it. I am sure you can find it.

**Comment by kanlukasz** [comment]
Sorry for duplicate. To be honest, I couldn't find it.

Anyway, if someone knows ID of this issue, I will be grateful for posting a link (thanks to this I will be able to follow the development of the case)

P.S. thanks for all quick answers and for this great program :heart:

**Comment by usernamehw** [comment]
Maybe this one #35109.
