### ISSUE TITLE
Allow right click on breakpoints in gutter to edit condition

### ISSUE THREAD

**Issue by drayfar** [Microsoft/vscode#70900]
Right-clicking on the red dot of a breakpoint in the gutter doesn't bring up a context menu. It took me forever to figure out conditional breakpoints were even supported. It's hard to figure out which one of these breakpoints is the one I want to edit:
![image](https://user-images.githubusercontent.com/1672546/54757974-85a0af00-4ba8-11e9-9f32-fb07d6da9409.png)

It would be way easier to just right click them here, like other debuggers support: 
![image](https://user-images.githubusercontent.com/1672546/54758000-94876180-4ba8-11e9-901a-c8468a289cb1.png)

**Comment by isidorn** [comment]
Yeah we do support that

![editBreakpoint](https://user-images.githubusercontent.com/1926584/54760348-354d3f80-4bf0-11e9-91d3-02cef49d29b2.gif)

**Comment by drayfar** [comment]
@isidorn guess it's a bug then? It's not working on my build:
Version: 1.33.0-insider (user setup)
Commit: 1efaca21afeb983a8efdae6a6b142bd00276c563
Date: 2019-03-20T08:25:15.878Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18351

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70388
