### ISSUE TITLE
Broken underlines for git status output

### ISSUE THREAD

**Issue by svillar** [Microsoft/vscode#70907]
Issue Type: <b>Bug</b>

The underlines bellow paths in the `git status` command, when executed in the terminal, are shifted to the right as it can be seen in the attached screenshot. This didn't happen months ago, but started 2-3 months ago IIRC.

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T14:40:37.095Z)
OS version: Linux x64 4.17.0-3-amd64

![code-bug](https://user-images.githubusercontent.com/1826122/54761946-6713d580-4bf3-11e9-8d24-0a28dda77aeb.png)

**Comment by pamnanaimanish169** [comment]
Does this reproduce in the latest [VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? 

Also, can you provide more information on your environment details by Going to **Help > About** and Copy the information from over there.

**Comment by svillar** [comment]
> Does this reproduce in the latest [VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
> 

It works fine in VS Code insiders

> Also, can you provide more information on your environment details by Going to **Help > About** and Copy the information from over there.

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.17.0-3-amd64
