### ISSUE TITLE
vsCode - glaring debuging flaw

### ISSUE THREAD

**Issue by PMoransais** [Microsoft/vscode#70903]
In reference to #70848 and #24520

Both issues were closed because of a technical reason that makes it impossible for vs code to show the value of some variables while hovering over them during debug.

For the last 2 years Microsoft has accepted a situation where very often hovering the line of code

const A = B; 

shows A as **undefined** but properly shows the value of B.

Please take you head outside the purely technical reasons for this and read the above statement a few times! This is not an issue that should be closed. It is an issue that should have priority because with a the statement such as  if (A.something) {}  it matters during debugging and runtime whether A is in fact undefined or not.

As of now the debugger does not say 'I don't know anything about this', it says 'this is not defined'

In fact, if it proves impossible to fix this, the best solution is to eliminate the display of values on hover or replace 'undefined' with 'no clue'!

I opened a new issue because I did not find a way to comment on the old one.

Thank you

**Comment by isidorn** [comment]
Reproducable steps please.
Create a repo on github which I can simply clone and see this issue on my machine
Thanks
