### ISSUE TITLE
Minor typo in command palette

### ISSUE THREAD

**Issue by codezapper** [Microsoft/vscode#70908]
- VSCode Version: 1.32.3
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Open command palette
2. Type 'Prefer'
3. The 'Open Workspace Settings' and 'Open Folder Settings' will be listed as 'Prefernces: Preferences: Open Workspace Settings' and 'Prefernces: Preferences: Open Folder Settings'

Note both the missing "e" and the double "Preferences"

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
#69867
