### ISSUE TITLE
Output displays 'Request textDocument/definition failed' on selection + CTRL

### ISSUE THREAD

**Issue by BillyCoda** [Microsoft/vscode#70914]
Issue Type: <b>Bug</b>

If any word is selected and "Ctrl" is pressed the "OUTPUT" window will pop up and display an error "[Error - 12:52:02 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'text' of undefined
  Code: -32603".
This is exceptionally annoying when trying to copy/paste anything from the editor. I tried changing the keyboard shortcut for "peek definition" since that seems like what it's trying to do but the same behavior persists.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (4.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.8.1
json-pretty-printer|eus|1.1.0
beautify|Hoo|1.4.11
ternjs|hsi|0.0.4
vs-docblock|jer|0.5.4
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-docker|Pet|0.6.1
insert-special-symbol|swi|1.3.0
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@BillyCoda this is very likely caused by an extension. To verify could you start VS Code with `--disable-extensions` if the problem is gone. If so I can only ask to disable extensions selectively to see which one is causing this and then report the error there.

**Comment by BillyCoda** [comment]
Thank you!
It was the Ternjs extension. Not sure how it got installed, but it's gone now.
