### ISSUE TITLE
Git output window shows fatal error during stage/unstage of files

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#70911]
- VSCode Version: 1.31.3
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open a workspace with one or more files
2. Make a change to a single file
3. Stage the file

I see this error:
```
> git rev-parse --symbolic-full-name user/hillr/tweak-client-readme@{u}
fatal: ambiguous argument 'user/hillr/tweak-client-readme@{u}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What's the name of the current branch you are on?

**Comment by rkeithhill** [comment]
The name is `user/hillr/tweak-client-readme`.

**Comment by joaomoreno** [comment]
And if you run `git rev-parse --symbolic-full-name user/hillr/tweak-client-readme@{u}` from the command line, it fails as well?

**Comment by rkeithhill** [comment]
Yes, that command fails:
```
C:\Users\hillr\Git\FOO-Samples> git rev-parse --symbolic-full-name user/hillr/tweak-client-readme@{u}
fatal: no such branch: 'user/hillr/tweak-client-readme'
```
Git version is:
```
git version 2.20.1.windows.1
```

**Comment by joaomoreno** [comment]
How about `git branch -vv | grep user/hillr/tweak-client-readme`?

**Comment by joaomoreno** [comment]
How about `git for-each-ref --format='%(upstream:short)' refs/heads/user/hillr/tweak-client-readme`?

**Comment by joaomoreno** [comment]
Also... does the stage actually work? Does any feature fail to work? The error message just means your branch doesn't have an upstream configured, it's not a problem.

**Comment by rkeithhill** [comment]
I get nothing from that command.  However, if I run git status I see this:
```
Your branch is based on 'origin/user/hillr/tweak-client-readme', but the upstream is gone.
```
Not sure if this was the case when I filed this issue but yeah, the branch was merged and deleted on origin.  In which case, I guess you're right - not a problem.
