### ISSUE TITLE
Source control panels don't remember their positions

### ISSUE THREAD

**Issue by tangtony** [Microsoft/vscode#70919]
Issue Type: <b>Bug</b>

Possibly a regression of https://github.com/Microsoft/vscode/issues/48566, but when more than 5 projects are available in the source control providers, a scroll bar appears and the lower source control panel can be adjusted to a custom position.

Unfortunately, when one navigates to a different menu and then returns to the source control menu, the position of the lower source control panel is always reset to a position at the bottom.

This is extremely annoying since I have to adjust the position every single time I want to check diffs and adjust my commits.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

## Before
![6-projects-custom-position](https://user-images.githubusercontent.com/5085394/54783466-d55a9700-4bf7-11e9-8fa3-d69743ccc509.PNG)

## After
![6-projects-reset-position](https://user-images.githubusercontent.com/5085394/54783467-d55a9700-4bf7-11e9-9ba1-e71aa0bf665e.PNG)

**Comment by joaomoreno** [comment]
This was addressed this milestone by https://github.com/Microsoft/vscode/issues/49054
