### ISSUE TITLE
Windows + GIT Bash: display issue

### ISSUE THREAD

**Issue by ArThoX** [Microsoft/vscode#70916]
**Steps to Reproduce:**

1. Open VSCode
2. Run a cmd (with integrated GIT Bash, here `yarn run xstart`)
3. The result in the integrated terminal should be identical to external terminal.

**Does this issue occur when all extensions are disabled?:**

 Yes

**Please find attached two screenshots:**

In the first one you can see a big white square of missing text:
![image](https://user-images.githubusercontent.com/551029/54771953-a4359300-4c06-11e9-9486-cf89a36bc22b.png)

In the second one you can see that the missing text is here (external terminal):
![image](https://user-images.githubusercontent.com/551029/54771989-bb748080-4c06-11e9-9702-fc4642b55937.png)

**Question**

Could you please advise on why some text is missing on integrated terminal ?

**Comment by jamiewinder** [comment]
I'm seeing the same. Another effect of this that I've found is that running any command causes the terminal to scroll right to the bottom the first time it outputs a line (actually past the line it outputs). Might be a clue.

Other shells don't appear to be affected.

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by ArThoX** [comment]
#57803 was closed and `"terminal.integrated.windowsEnableConpty": false` did not change anything.

**Comment by Tyriar** [comment]
I've decided to update the #57803 comment as well as the saved reply I use, see below for more details on what I closed this.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423)

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by ArThoX** [comment]
FLY I am getting the same issue with either

> "terminal.integrated.windowsEnableConpty": true,

or

> "terminal.integrated.windowsEnableConpty": false,

**Comment by Tyriar** [comment]
@ArThoX what version of Windows are you on?

**Comment by ArThoX** [comment]
@Tyriar Windows 10 Pro 64-bits (build 17763), vscode 1.33.

**Comment by Tyriar** [comment]
conpty doesn't work on that build on Windows, see https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423
