### ISSUE TITLE
Running slow

### ISSUE THREAD

**Issue by fercr31** [Microsoft/vscode#70918]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
Issue Type: <b>Performance Issue</b>

VSCode running to slow after using for a couple of days. It started today, its been like this for a few hours now. It occurs while writing my code. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|14.96GB (6.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    75	  3100	code main
    0	    65	  2624	   window (Issue Reporter)
    0	   237	  9484	   window (● app.ts - Fer - Visual Studio Code)
    0	    36	  4692	     searchService
    0	    12	 11936	     electron-crash-reporter
    0	   440	 15868	     extensionHost
    0	    70	  5084	       "C:\Users\Fer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Fer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=15868
    0	    38	 17516	       "C:\Users\Fer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Fer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=15868
    4	   337	 20532	       electron_node server.js 
   23	   521	 20948	       electron_node tsserver.js 
    0	    54	  2360	         electron_node typingsInstaller.js typesMap.js 
    0	     6	 16044	     winpty-process
    0	     8	  8944	       console-window-host (Windows internal process)
    0	    62	 11092	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    15	 21144	     watcherService 
    0	     5	  7748	       console-window-host (Windows internal process)
    0	    62	 11812	   shared-process
    1	    63	 19556	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● app.ts - Fer - Visual Studio Code)
|    Folder (Fer): more than 29795 files
|      File types: png(4125) JPG(4121) code(1618) file(1302) mp3(953) jpg(758)
|                  tmp(674) svg(624) ithmb(619) jar(565)
|      Conf files: sln(55) package.json(55) csproj(30) tsconfig.json(13)
|                  settings.json(8) tslint.json(7) launch.json(5)
|                  tasks.json(4) webpack.config.js(3) gulp.js(1)
|                  grunt.js(1);
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
jshint|dba|0.10.20
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.8.1
terminal|for|0.0.10
vscode-angular2-emmet|jak|2.0.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|7.2.5
auto-npm-install|mos|1.0.17
vscode-typescript-tslint-plugin|ms-|1.0.0
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.6.3
tsimporter|pmn|2.0.0
typescript-hero|rbb|3.0.0
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by isidorn** [comment]
Just disable your extensions one by one. It is one of the extensions you have installed
