### ISSUE TITLE
The left and top background are in blue

### ISSUE THREAD

**Issue by dmarzan** [Microsoft/vscode#70913]
Issue Type: <b>Bug</b>

Recent visual studio code comes with top and side blue backbround with no way to change it.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (15.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|9.5.1
gc-excelviewer|Gra|2.1.29
githd|hui|2.1.0
rainbow-csv|mec|1.0.0
mssql|ms-|1.4.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.6.1

</details>

**Comment by isidorn** [comment]
Can you attach a picture please? 
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by weinand** [comment]
no reply -> closing.
