### ISSUE TITLE
Path Variables uses the platform slashes instead of always forward slashes

### ISSUE THREAD

**Issue by pbricout** [Microsoft/vscode#70926]
Issue Type: <b>Bug</b>

On Windows path variables like ${relativeFile} or ${workspaceFolder} are return in the platform format. I.E. using backslashes instead of forward slashes, this seems to be recent regression from this issue:
https://github.com/Microsoft/vscode/issues/40256
According to this issue forward slashes should be used on all OSes.
Doing this on windows, when the shell is bash is failing:

```
        "tasks": [{
            "label": "echo",
            "type": "shell",
            "command": "echo ${workspaceFolder}",
            "problemMatcher": []
        }]
```

Will show abc instead of a/b/c.
My bash scripts are not working any more.
Is there a setting to control the behaviour? I could not find one.

Doing this work as the path is in the platform format:
```
    "tasks": [
        {
            "label": "echo",
            "type": "process",
            "command": "cmd.exe",
            "args": [
                "/C",
                "echo",
                "${workspaceFolder}"
            ],
            "problemMatcher": []
        },
```

Trying to find if there is a solution, the following discussion suggest that there should be a command to specify whether to replace slashes or not, but I could not find such a thing:
https://github.com/Microsoft/vscode/issues/37438

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Genuine Intel(R) CPU 0 @ 2.30GHz (4 x 2307)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.97GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.3.0
githistory|don|0.4.6
code-runner|for|0.9.7
vscode-auto-open-markdown-preview|hnw|0.0.4
launcher|ili|0.0.4
autoconf|mae|0.0.7
python|ms-|2019.2.5558
cpptools|ms-|0.22.0
partial-diff|ryu|1.4.0
vscode-hexdump|sle|1.7.2
m68k|ste|0.0.1
code-spell-checker|str|1.6.10
acmecrossassembler|Ton|0.0.18

</details>

**Comment by isidorn** [comment]
As designed, more details here https://github.com/Microsoft/vscode/issues/70050#issuecomment-472052839

**Comment by pbricout** [comment]
This solution can't work in my case, see my comments in the other issue:
https://github.com/Microsoft/vscode/issues/70050#issuecomment-475878210

**Comment by pbricout** [comment]
Found a clean solution to my problem, see my comment here:
https://github.com/Microsoft/vscode/issues/70050#issuecomment-475964508
