### ISSUE TITLE
Wrong git avatar

### ISSUE THREAD

**Issue by msbadar** [Microsoft/vscode#70923]
- VSCode Version: 1.31.1
- OS Version: Windows_NT x64

Steps to Reproduce:

1. Open Git History ( Git Log ) and click any commit item from the list. A panel will display below with user image and commit details for your clicked item.
2. If your "Name" is unique in GitHub you will get correct image for your commit, Otherwise, Your name is used by any other person,  you will be seeing his/her avatar instead of your's for your commit. 

I think its checking "Name" instead of username or email.

**Comment by msbadar** [comment]
This issue starts from git config itself. If User A kept his config.user name as User B, just name  not "username",  is this okay to show the User B avatar for User A's commit. In My case this is the case. 

I don't think it's correct way to handle this, 
Setting in git.config is fine. but when fetching details from GitHub it should against login id instead of any search.

**Comment by joaomoreno** [comment]
Are you maybe using Gitlens?

**Comment by msbadar** [comment]
Yes

**Comment by joaomoreno** [comment]
Please file an issue for that extension: https://github.com/eamodio/vscode-gitlens/issues
