### ISSUE TITLE
API request: Set relative zoom level of webview

### ISSUE THREAD

**Issue by mrmeku** [Microsoft/vscode#70921]
Currently, all webviews use the same zoom level as all VSCode views. Sometimes this is not ideal, it can make the content in the webview look comically large. This API request would hopefully make things look less comical.

The ask is an API to let webviews set a relative scaling factor. If VScode is zoomed to 125%, I want an API that would let me specify that my content should only be at 100% zoom. This would be a scaling factor of 0.8

100 / 0.8 = 1.25 = 125%

**Comment by mrmeku** [comment]
One might argue that you can accomplish something similar using the CSS scale transform. However using a transform negatively impacts font rendering. The only way to scale content without affecting font rendering is to use electron's native zoom API

**Comment by mjbvz** [comment]
Zoom is currently designed to zoom the entire editor. I don't think allowing webviews to override this is a good idea as some users may need webview content to be displayed at a larger size
