### ISSUE TITLE
PHP Flexible heredoc and nowdoc

### ISSUE THREAD

**Issue by AdnanBabakan** [Microsoft/vscode#70929]
- VSCode Version: 1.32.3
- OS Version: Windows 10 Pro 1809

PHP 7.3 has a new syntax for heredoc and nowdoc features that heredocs and nowdocs can now be indented.
https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

I would ask to implement this PHP syntax in VSCode as a core syntax.

**Comment by roblourens** [comment]
Tracked upstream in https://github.com/atom/language-php/issues/346
