### ISSUE TITLE
Random output messages on typing error 

### ISSUE THREAD

**Issue by axe-z** [Microsoft/vscode#70928]
I keep having output messages, 
on js files that are not supposed to be watched : 

	"files.watcherExclude": {
	"**/1-Notes/**": true,
	},
 
![Capture d’écran, le 2019-03-21 à 19 38 19](https://user-images.githubusercontent.com/27289270/54791579-e2d04b00-4c10-11e9-8821-b50bd6e6026b.png)

- VSCode Version: latest 1.32.3
- OS Version: latest 10.14.3

**Comment by axe-z** [comment]
there is not much more I can say. If we could not display the output, I would not care, 
but that the thing , even if I remove OUTPUT from terminal, to only show the terminal, it comes back. 
it's a fresh create react app dev. nothing is running , editing a simple .js file.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

It sounds like this is caused by the styled-jsx extension

**Comment by axe-z** [comment]
I uninstalled it an hour ago..

**Comment by mjbvz** [comment]
And you're still seeing logs from it?

**Comment by axe-z** [comment]
I ll try tomorrow , I had enough for the day ;) tks !
