### ISSUE TITLE
[ Feature Request ] - Show name of theme currently used on File Menu Grab-Bar

### ISSUE THREAD

**Issue by SirTwsted** [microsoft/vscode#70927]
Sometimes people need to immediately know the current name of theme they are using.
So people would have the name of the theme to be immediately shown in the
upper right side of the VSC application within the File Menu Grab Bar. (next to the minimize button).

Also when someone goes to CNTRL + P and then type "Theme"
It should show you the last 5 themes recently used with the most recent one used at the top.

![Screenshot_1](https://user-images.githubusercontent.com/15247713/54790176-9df5e580-4c0b-11e9-862a-cc2c893b8473.png)

**Comment by sbatten** [comment]
@SirTwsted the shortcut Ctrl+K, Ctrl+T will open the theme selector and show you the current theme selected

**Comment by SirTwsted** [comment]
thank you for showing me the short cut @sbatten ,
Though,....... 
I wish VS Code has a button switch that would let me toggle, when I want to show it up on the 
menu bar constantly. I use a Extension that is called "Theme by Language" by (Julien Saulou)
so it would be nice to be able to just have the option to flip a button switch in the settings to always show JUST the name of the theme in the menu bar next to the minimize button of VS Code.

thx :)
