### ISSUE TITLE
when pasting a file path in quick open it should show the result immediately

### ISSUE THREAD

**Issue by hferreiro** [Microsoft/vscode#70924]
Apparently Quick Open only works with file names. Regardless of that, when pasting a full or relative path to an existing file, it should first check if the path exists, and show it in the result list if that's the case. The current behaviour is that vscode finds the file but after searching, which can take a long time in huge repos.

**Comment by roblourens** [comment]
This does work with absolute paths. It used to be implemented for relative paths, but we decided that it was not a very useful or well-known feature, and just gets complicated with multiroot workspaces, etc.

**Comment by hferreiro** [comment]
My use case is with relative paths where I copied it from the compiler output on errors. Would you consider supporting that?

**Comment by roblourens** [comment]
Ideally search is fast enough that this would be covered by search. If search is extremely slow, you might consider trying to exclude large folders with `search.exclude`, disabling `search.followSymlinks`, etc depending on your workspace. Also if the build is in the integrated terminal, you should be able to just click it to open that file.
