### ISSUE TITLE
Debug widget is in "paused" state while initializing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#70931]
![Mar-21-2019 17-23-39](https://user-images.githubusercontent.com/323878/54793103-240b2f80-4bfe-11e9-8caa-8da52a2628b8.gif)

- Start debug session
- Debug widget appears with "continue" immediately visible
- When the session is initialized, it switches to "pause"

**Comment by isidorn** [comment]
@roblourens great catch! Thanks a lot!
