### ISSUE TITLE
Unable to resize the GIT list between source control providers and the changes list

### ISSUE THREAD

**Issue by brwilkinson** [Microsoft/vscode#70933]
Issue Type: <b>Bug</b>

Click on source control
Expand out the Source Control Providers list
Click on a specific repo
Expand out the Changes list

Hover over the area where you would resize the divider between the two sections, the arrow doesn't change from the selector icon to the arrow resize icon. There is no way to resize to see the full list of repo's.

You have to use the scroll bar on the side to scroll to see the hidden repos.

VS Code version: Code - Insiders 1.33.0-insider (5a88160c7dc5db820a564e3872e0de087ff3563d, 2019-03-15T15:54:09.237Z)
OS version: Windows_NT x64 10.0.18860

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 3506)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (17.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|0.1.120190228
vscode-markdownlint|Dav|0.25.0
gitlens|eam|9.5.1
vscode-azureappservice|ms-|0.13.0
vscode-azurefunctions|ms-|0.15.0
vscode-azurestorage|ms-|0.7.0
vscode-azureterraform|ms-|0.2.2
vscode-cosmosdb|ms-|0.10.0
vscode-kubernetes-tools|ms-|0.1.18
mssql|ms-|1.4.0
python|ms-|2019.2.5558
vscode-ai|ms-|0.4.5
azure-account|ms-|0.8.0
azurecli|ms-|0.4.4
PowerShell-Preview|ms-|2.0.0
typescript-javascript-grammar|ms-|0.0.49
vscode-azureextensionpack|ms-|0.0.9
vsliveshare|ms-|0.3.1326
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.5.0
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.6.3
vscode-yaml|red|0.3.0
code-settings-sync|Sha|3.2.7
usql-vscode-ext|usq|0.2.14
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.10.0
azure-iot-toolkit|vsc|2.4.0

</details>

**Comment by joaomoreno** [comment]
There is now a setting: `scm.providers.visible`, set it to 0 to allow for manual resizing.

**Comment by brwilkinson** [comment]
Nice one, thanks @joaomoreno 

I ended up setting it to a high number [30], so that by default it auto sizes and I can see them all.

I think a high number would be a good default (since it's a breaking change?!), instead of 10.
