### ISSUE TITLE
Keyboard binding for step into (F11) no longer working

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#70932]
Issue Type: <b>Bug</b>

This is a regression from stable. In Insiders, F11 while debugging is doing a show fullscreen.  It's supposed to step into when debugging

![image](https://user-images.githubusercontent.com/6913354/54793682-c62c1700-4c00-11e9-944c-1caaf27d5a03.png)

This is the binding in stable:
![image](https://user-images.githubusercontent.com/6913354/54793696-df34c800-4c00-11e9-9ed3-9b6bbd90fb90.png)

VS Code version: Code - Insiders 1.33.0-insider (edd2c737f9b6f08cd0e30050b441cd262eb7f0d8, 2019-03-21T06:19:48.689Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (16.07GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
capturesyntaxtokens|Mic|0.0.1
vscode-antlr4|mik|2.1.1
vscode-cosmosdb|ms-|0.10.0
extension-manifest-editor|ms-|0.1.5
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
azurerm-vscode-tools|msa|0.5.0
vscode-docker|Pet|0.6.1
vscode-yaml|red|0.3.0
vscode-sort-json|ric|1.13.0
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
sort-lines|Tyr|1.8.0
win-ca|uko|2.4.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by isidorn** [comment]
@StephenWeatherford Good catch, thanks for using insiders and for filling quality issues.

**Comment by isidorn** [comment]
Pushed a fix, please try vscode insiders on Monday and let us know if it is good for you now.

**Comment by andre-rosa** [comment]
It works, but if you keep F11 pressed while debugging it'll still trigger full screen sometimes in between debug actions.

**Comment by StephenWeatherford** [comment]
Works for me, thanks!

**Comment by isidorn** [comment]
@StephenWeatherford thanks, adding verified label
