### ISSUE TITLE
Allow to restrict "ctrl + shift + F" and "ctrl + P" to only desired folder when workspace has multiple projects.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#70934]
Issue Type: <b>Feature Request</b>

usecase:
- there are multiple folder added to the workspace.
- you have opened a folder with two instance of similar code base in same VSCode instance

press ctrl + p, and search for file (lets assume package.json present in both code base).

since the file exists in both folder/project 2 suggestions/results will be visible in ctrl + P viewlet.

expected:
- there should be a way to ignore the folder that is just for reference from the results of ctrl + P and ctrl + shift + F.
- a context menu (mouse right click) option  will be very welcomed.

VS Code version: Code - Insiders 1.33.0-insider (edd2c737f9b6f08cd0e30050b441cd262eb7f0d8, 2019-03-21T06:19:48.689Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
Is this a duplicate of https://github.com/microsoft/vscode/issues/71989? Please explain some more

**Comment by sanket-bhalerao** [comment]
@roblourens it is kind of duplicate..
