### ISSUE TITLE
[ FEATURE REQUEST ]  - Ability to save theme colors settings files individually for each theme installed

### ISSUE THREAD

**Issue by SirTwsted** [Microsoft/vscode#70930]
Im trying to find a simpler title for this feature, but cant at the current time - Anyways.....,
This is a bit long winded, because im trying to explain over text which is a bit difficult,
and im a bit frustrated because ive been googling all day finding everything else but what I am asking for.  Anyways,

 - Ability to save theme colors settings files individually for each theme installed.

Ill give a brief explanation as I have been trying to do this for days now and yet havent got a result to what I want to do.
So,
I have several themes installed. so for example lets take the theme I downloaded called 
"Darwin" by (Chris K. Seidel).
I like the colors but would like to tweak it a bit.

I tried the ((**Developer: Generate Color Theme from Current Settings**))
Here I thought, 
hey It will generate a file that I can tweak and then save it within the Darwin Theme folder so then, VS Code would know that when it pulls up this Darwin theme, it would
grab the info settings file from the settings file I tweaked for the theme.
Well no, it doesnt.  it just makes a generic file and if a theme is changed that file is screwed.
A bit frustrating.  It doesnt save the tweaked/modified file in the themes folder,
like it should.

I would like to be able to do this ((**Developer: Generate Color Theme from Current Settings**))
or something similar that would allow me to tweak all the settings from a specific theme I have installed and be able to save it as an independent theme settings file under the same name of the theme I am tweaking.
So when I change themes and recall a theme back,.
VS Code would know to read that specific tweaked / modified file to get the colors I have implemented.

Currently you cant do this.
Sometimes people really love a specific theme and its colors, but would like to tweak / modify a few things here and there to their liking.
And would like to be able to save a version of those tweaks / modifications of that file within that specific themes folder, so they will always have it and can also back that file up, in case something drastic happens with a persons computer.

I have been trying to do this for days now, and been googling this for days,
and I get everything else in the sink except for what I specifically want to do.
"Unless im typing something wrong"

So now i am posting this as  a feature so it will be easier for users to do.

Sorry for the long winded post,
Thanks for reading.....

**Comment by usernamehw** [comment]
In `settings.json`:
```json
"workbench.colorCustomizations": {
    "[Monokai]": {
        "editor.background": "#ff0000"
    },
},
"editor.tokenColorCustomizations": {
    "[Monokai]": {
        "textMateRules": [
            {
                "scope": "keyword",
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    }
}
```
Replace `Monokai` with your color theme name.

**Comment by SirTwsted** [comment]
But wouldnt that also delete all the colors in the theme for Darwin Theme  ?
and only implement the colors thats in that code ?
Darwin theme has a bunch of colors to the theme depending on the code and the different parts of the code.

**Comment by usernamehw** [comment]
> But wouldnt that also delete all the colors in the theme for Darwin Theme ?
and only implement the colors thats in that code ?

No

**Comment by aeschli** [comment]
Thanks @usernamehw for the showing the syntax to customise specific themes.

**Comment by SirTwsted** [comment]
Thank you @usernamehw ,  I will for sure give this a try.
and
@aeschli , i wasnt being rude,  I fell asleep as its extremely late here.  Just saying :)
