### ISSUE TITLE
Extension details: Tooltip "Install count" should be "Downloads count"

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#70945]
Issue Type: <b>Bug</b>

![Screenshot (114)](https://user-images.githubusercontent.com/9638156/54811295-6a619c80-4c99-11e9-8222-5490b65e6d9a.png)

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
Its not download count, its an install count.

**Comment by usernamehw** [comment]
@sandy081 it doesn't match marketplace for me:

![Screenshot (112)](https://user-images.githubusercontent.com/9638156/54810474-469d5700-4c97-11e9-9ea7-f32185ee9226.png)

**Comment by sandy081** [comment]
@gaurav42 May I know when I query Marketplace and sort by install count, do you sort by install count or download count?

**Comment by ZainChen** [comment]
> @gaurav42 May I know when I query Marketplace and sort by install count, do you sort by install count or download count?

Hi, hello, by comparison, the VS code extension is sorted by number of installs, not including updates.
![image](https://user-images.githubusercontent.com/15615524/56809936-9a3b2b80-6867-11e9-8298-0a0fda6b39ea.png)

**Comment by sandy081** [comment]
This will be fixed by https://github.com/microsoft/vscode/issues/80551
