### ISSUE TITLE
Terminal in blank

### ISSUE THREAD

**Issue by crm86** [Microsoft/vscode#70947]
Issue Type: <b>Bug</b>

Terminal prompt starts in blank on windows 10 until you write something. I am using windows powershell console. After the first command it works fine. I think this is only a visual glitch

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (8.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
angular-schematics|cyr|1.23.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
docthis|joe|0.7.1
angular-essentials|joh|0.5.1
Angular2|joh|7.0.1
svn-scm|joh|1.47.5
Angular-BeastCode|Mik|7.2.5
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.6.3
vscode-uppercase|rui|1.0.1
bootstrap4-vscode|the|6.1.0
local-history|xyz|1.7.0
markdown-all-in-one|yzh|2.1.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
