### ISSUE TITLE
[ Feature Request ] - Allow us to modify or make boiler plates for each language.

### ISSUE THREAD

**Issue by SirTwsted** [Microsoft/vscode#70943]
Allow us to modify or make boilerplates for each language Natively within VS Code..
Ive tried several boilerplates extensions, but for some reason those devs hide the boilerplate from being edited/modified.
Would be nice to be able to save the boiler plate in the install directory of VS Code,
and have it Natively in VS Code, so people can modify each language boilerplate to their liking.
When a person makes a boilerplate, it would be nice that a FOLDER Natively gets created by VS Code called "Boilerplates" and be located in the install directory for ease of access by users..

**Comment by alexr00** [comment]
This looks like a feature request to allow contributed snippets to be editable and savable locally.
