### ISSUE TITLE
Doanload Counts are incorrect

### ISSUE THREAD

**Issue by chandanhasija** [Microsoft/vscode#70942]
Issue Type: <b>Bug</b>

I was watching a video on Youtube for React and in this video when he was downloading an extension called Prettier by Esben Petersen. Their were 2,749,536 downloads already and when i was downloading the same extension it was showing 1,871,321. How comes downloads are decreasing in future. This is a bug in your system. Please check and solve.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
csharp|ms-|1.15.2

</details>

**Comment by usernamehw** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/9638156/54810474-469d5700-4c97-11e9-9ea7-f32185ee9226.png)

**Comment by chandanhasija** [comment]
That was my mistake i actually wanted to say install count.

![image](https://user-images.githubusercontent.com/32809497/54813609-e963ce80-4cb3-11e9-984d-17fe2d6f5a0f.png)

**Comment by sandy081** [comment]
I see same in Code and Marketplace. Which version of VS Code are you using?

**Comment by chandanhasija** [comment]
@sandy081 Thanks it worked. But i don't what could have been causing this thing.
