### ISSUE TITLE
git plugin regressions?

### ISSUE THREAD

**Issue by ryenus** [Microsoft/vscode#70941]
I've been using selective staging quite often, namely stage only the selected changes, but today I noticed VSCode is not behaving correctly as it used to be.

This is happening with one of my local repositories checked out from github, but with some changes on a file that had already been committed before.

There're two chunks of code changes, first having only one line, the 2nd about 10 lines.

- VSCode Version: 1.32.3
- OS Version: 10.14.3

Steps to Reproduce:

1. click the first chunk, namely the chunk with only one line changed code
2. perform the action "stage selected change", it worked, actually it would work regardless the whole line was selected or not, this is fine.
3. select the 2nd chunk, do stage selected change, this is where it's broken, nothing got actually staged. I tried to do this in the normal file editor, or Working Tree view, or the Index view, neither worked.

Does this issue occur when all extensions are disabled?: Yes
I disabled all extensions for the current workspace, though.

<b>BTW, may I ask how to restore the workspace to its previous state in terms of the enabled/disabled extensions? the only action I see are enable all extensions or disable all extensions, but none says restore extensions status.</b>

**Comment by joaomoreno** [comment]
Does this happen with that specific change? If so, can you send me the exact file and let me know exactly which lines you select and attempt to stage? Without that, I can't reproduce the issue.

**Comment by ryenus** [comment]
I created a demo repository, with only the affected file. Unfortunately I couldn't reproduce the problem with the new repository, even though it's still happening in my original repository.

However, the repository isn't one I can share here. I wonder if there's some flag to to turn on debug log for the related code so maybe I can compare the debug log to see what could be different?
@joaomoreno is that possible? if yes, then how?

**Comment by joaomoreno** [comment]
There isn't really a log output which would help us.

Instead of trying to replicate the bug in a new repo... try removing things from the existing repo until it stops reproducing.
