### ISSUE TITLE
Snippets with default minimise feature

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#70949]
When inserting snippets, the snippets of functions are by default maximised, Like the below image:
![DeepinScreenshot_select-area_20190322163201](https://user-images.githubusercontent.com/45997896/54818782-10c09880-4cc0-11e9-9d78-85dcbf1ee87d.png)

However, there should be an option while making the snippet to insert it in minimised/maximised mode, like the image below:
![DeepinScreenshot_select-area_20190322163338](https://user-images.githubusercontent.com/45997896/54818865-46fe1800-4cc0-11e9-9717-673054e1b9f3.png)

**Comment by jrieken** [comment]
Do you meaning folding or what does minimise mean?

**Comment by infixint943** [comment]
@jrieken updated my question for better understanding

**Comment by jrieken** [comment]
Thanks for clarifying. Tho, I argue the usefulness of that. A snippet is meant to speed up typing and having something in which you type collapsed isn't that useful imo.

**Comment by infixint943** [comment]
Most of the time a snippet can be large and could be a function that we might not require to edit. So instead of having it expanded, it could be collapsed to save screen-space and make the code more readable.
