### ISSUE TITLE
Snippet with multiple variable refs is not completing properly, leaving multiple cursors in editor.

### ISSUE THREAD

**Issue by bill-mybiz** [Microsoft/vscode#7094]
- VSCode Version: 1.2.0-insider
- OS Version: Windows 10

Steps to Reproduce:
1. Create a snippet, but do not enter a `$0` to explicitly tell the snippet where to put the cursor after the completion of the snippet.

```
    "log error": {
        "prefix": "logerror",
        "body": [
            "logger.error({ logContext: lc, errorContext: `${1:err}`, error: $1 });"
        ],
        "description": "Log error message."
    }
```
1. Invoke the snippet. Enter a default value (Issue #7093 has been created for the default value not already being prepopulated in the second variable reference). Notice that there are multiple cursors when entering this value, which is as it should be.
2. Press enter to complete the snippet.

What should happen: The snippet should exit and there should only be one cursor in the editor.
What actually happens: The snippet leaves two active cursors in the editor.

You can press `esc` and the snippet will complete properly. You can also enter a `$0` in the snippet such as:

```
    "log error": {
        "prefix": "logerror",
        "body": [
            "logger.error({ logContext: lc, errorContext: `${1:err}`, error: $1 });$0"
        ],
        "description": "Log error message."
    }
```

And the snippet will complete properly. But if you do not explicitly state this `$0` marker, it does not act as the TextMate documentation states: 

> If you do not explicitly set $0, the caret will be at the end of the snippet.

**Comment by bill-mybiz** [comment]
Actually, it looks like it doesn't complete properly with a single variable reference either. If you just do the same snippet without the mirror, pressing enter should place the cursor after the snippet. What it actually does is just keep the variable highlighted.

**Comment by jrieken** [comment]
There is now an implicit `$0` at the end of a snippet -unless already specified- make this a lot better. Jumping to the end happens on <kbd>Enter</kbd>, <kbd>Tab</kbd> still cycles. 

![nov-15-2016 17-35-39](https://cloud.githubusercontent.com/assets/1794099/20314305/136403a6-ab5a-11e6-937e-677b850ff320.gif)
