### ISSUE TITLE
private_xxx and public_xxx C lang highlight render issue 

### ISSUE THREAD

**Issue by JiapengLi** [Microsoft/vscode#70951]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Steps to Reproduce: 
save below code to .h file and open in vscode
```
int uECC_shared_secret(const uint8_t *public_key,
                       const uint8_t *private_key,
                       uint8_t *secret,
                       uECC_Curve curve);


```
![image](https://user-images.githubusercontent.com/3773923/54816667-cf37e980-4ccf-11e9-9ed9-54e5331d6238.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Already fixed in insiders as part of adopting a different grammar.
