### ISSUE TITLE
Performance completely killed with update

### ISSUE THREAD

**Issue by Johnogram** [microsoft/vscode#70955]
Issue Type: <b>Performance Issue</b>

Updating Code from ~1.29 to 1.3* has completely killed it's performance. It never becomes unresponsive, but is completely unresponsive, scrolling the slightest bit in a file takes seconds to register.

If I downgrade back to ~1.29, it works completely fine.

I have managed to get it working just about fine by running code using the following flags `code --use-gl=osmesa --disable-gl-drawing-for-tests`

I notice when running `code --status` I get the following error:
```
[7102:0322/114433.979383:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
```
Possibly something GPU related?

(I have had to redact some project names for security purposes)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|11.69GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   120	  6032	code main
    0	    36	  6035	   zygote
    0	   263	  6114	     window (Payruns.js - *removed* (Workspace) - Visual Studio Code)
    0	   132	  6139	       extensionHost
    0	   347	  6188	         electron_node tsserver.js 
    0	   108	  6331	           electron_node typingsInstaller.js typesMap.js 
    0	   108	  6202	         electron_node eslintServer.js 
    0	   263	  6279	         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/johnminns/.vscode/extensions/sonarsource.sonarlint-vscode-1.6.0/server/sonarlint-ls.jar 45501 file:///home/johnminns/.vscode/extensions/sonarsource.sonarlint-vscode-1.6.0/analyzers/sonarjs.jar file:///home/johnminns/.vscode/extensions/sonarsource.sonarlint-vscode-1.6.0/analyzers/sonarphp.jar file:///home/johnminns/.vscode/extensions/sonarsource.sonarlint-vscode-1.6.0/analyzers/sonarpython.jar file:///home/johnminns/.vscode/extensions/sonarsource.sonarlint-vscode-1.6.0/analyzers/sonarts.jar file:///home/johnminns/.vscode/extensions/sonarsource.sonarlint-vscode-1.6.0/analyzers/sonarhtml.jar
    0	    84	  6460	           node --max-old-space-size=2048 /home/johnminns/.sonarlint/work/.sonartmp_3804671756200196163/1727752109807396556/sonarts-bundle/node_modules/tslint-sonarts/bin/sonarts-server 33127
    0	    48	  6491	           node /home/johnminns/.sonarlint/work/.sonartmp_3804671756200196163/eslint-bridge-bundle/node_modules/eslint-bridge/bin/server 45715
    0	    24	  6374	         PHP Language Server
    0	     0	  6382	           sh -c '/usr/bin/php7.2' '-n' '-c' '/tmp/C3n2eV' '/home/johnminns/.vscode/extensions/felixfbecker.php-intellisense-2.3.10/vendor/felixfbecker/language-server/bin/php-language-server.php' '--tcp=127.0.0.1:42583' '--memory-limit=4095M'
    0	   275	  6383	             PHP Language Server
    0	    72	  6157	       watcherService
    0	    48	  6190	       searchService
    0	   108	  6362	     shared-process
    2	    96	  7283	     window (Issue Reporter)
    1	    96	  6096	   gpu-process
    0	     0	  7313	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7314	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Payruns.js - *removed* (Workspace) - Visual Studio Code)
|    Folder (*removed*): 231 files
|      File types: js(95) scss(35) eot(24) woff(24) woff2(24) json(6) map(5)
|                  css(4) html(2) png(2)
|      Conf files: package.json(1)
|    Folder (*removed*): 614 files
|      File types: js(241) css(157) scss(125) woff2(24) woff(24) eot(24)
|                  json(6) map(5) html(2) env(1)
|      Conf files: package.json(1)
|    Folder (*removed*): 467 files
|      File types: js(320) scss(110) md(23) json(4) gitignore(2) html(2)
|                  npmrc(1) arcconfig(1) editorconfig(1) babelrc(1)
|      Conf files: package.json(1)
|    Folder (wowanalyzer): 2578 files
|      File types: js(2007) png(178) jpg(174) scss(39) json(27) css(24) md(17)
|                  snap(17) gif(17) xml(15)
|      Conf files: jsconfig.json(2) package.json(2)
|    Folder (*removed*): 6671 files
|      File types: php(3804) png(521) js(308) inc(293) bcmap(168) xml(164)
|                  gif(161) fixed(141) css(121) properties(105)
|      Conf files: makefile(3) grunt.js(2) package.json(2) settings.json(1)
|    Folder (*removed*): 9302 files
|      File types: php(6520) html(320) inc(299) phpt(273) xml(272) json(226)
|                  md(188) txt(159) fixed(141) css(79)
|      Conf files: makefile(5) package.json(1) launch.json(1) settings.json(1)
|      Launch Configs: php(2)
|    Folder (*removed*): 8074 files
|      File types: php(4556) png(483) js(449) inc(315) xml(268) phpt(200)
|                  md(195) fixed(193) bcmap(168) css(160)
|      Conf files: package.json(3) makefile(2) grunt.js(1) csproj(1) sln(1);
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-eslint|dba|1.8.2
EditorConfig|Edi|0.13.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
phpcs|ika|1.0.5
sublime-babel-vscode|jos|0.2.10
string-manipulation|mar|0.3.1
php-docblocker|nei|1.8.0
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.6.3
partial-diff|ryu|1.4.0
sonarlint-vscode|Son|1.6.0
vscode-apielements|vnc|0.6.7
gitblame|wad|2.6.3
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by DanielFabian** [comment]
I'm not perfectly sure, they are related, but I'm using the same build (and hash) and windows 10 and every few seconds my editor becomes unresponsive for minutes at time. Here's a profile:

![image](https://user-images.githubusercontent.com/1929340/54832511-3b0c5900-4cb4-11e9-98d0-d52330ba0eca.png)

**Comment by Johnogram** [comment]
@bpasero just as bad I'm afraid :(

Let me know if you need any other information.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by DanielFabian** [comment]
Here's a profile from the exploration version, and it seems reproducible with all extensions disabled: 

![image](https://user-images.githubusercontent.com/1929340/54834455-20d47a00-4cb8-11e9-90bb-faa87cec28e7.png)

**Comment by Johnogram** [comment]
## System Info

* Code - Exploration: 1.32.0-exploration (14236f9f44cc7c94055bb8e65ebda29a4a91ddc7)
* OS: linux(4.15.0-46-generic)
* CPUs: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz(4 x 3899)
* Memory(System): 11.69 GB(0.14GB free)
* Memory(Process): 290.21 MB working set(212.76MB private, 1.26MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                    | Duration | Process          | Info                                       |
| ------------------------------------------------------- | -------- | ---------------- | ------------------------------------------ |
| start => app.isReady                                    | 118      | [main]           | initial startup: true                      |
| nls:start => nls:end                                    | 1        | [main]           | initial startup: true                      |
| require(main.bundle.js)                                 | 66       | [main]           | initial startup: true                      |
| app.isReady => window.loadUrl()                         | 237      | [main]           | initial startup: true                      |
| require & init global storage                           | 24       | [main]           | initial startup: true                      |
| window.loadUrl() => begin to require(workbench.main.js) | 299      | [main->renderer] | NewWindow                                  |
| require(workbench.main.js)                              | 310      | [renderer]       | cached data: YES                           |
| require & init workspace storage                        | 15       | [renderer]       | -                                          |
| init workspace service                                  | 14       | [renderer]       | -                                          |
| register extensions & spawn extension host              | 501      | [renderer]       | -                                          |
| restore viewlet                                         | 25       | [renderer]       | workbench.view.explorer                    |
| restore panel                                           | 0        | [renderer]       | -                                          |
| restore editors                                         | 537      | [renderer]       | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                  | 644      | [renderer]       | -                                          |
| workbench ready                                         | 2406     | [main->renderer] | -                                          |
| extensions registered                                   | 2596     | [renderer]       | -                                          |

## Extension Activation Stats

| Extension                         | Eager | Load Code | Call Activate | Finish Activate | Event               |
| --------------------------------- | ----- | --------- | ------------- | --------------- | ------------------- |
| vscode.debug-auto-launch          | true  | 14        | 0             | 6               | *                   |
| vscode.emmet                      | true  | 13        | 2             | 4               | *                   |
| vscode.git                        | true  | 30        | 2             | 37              | *                   |
| vscode.merge-conflict             | true  | 10        | 2             | 10              | *                   |
| vscode.extension-editing          | false | 38        | 0             | 3               | onLanguage:markdown |
| vscode.markdown-language-features | false | 57        | 2             | 0               | onLanguage:markdown |
| vscode.php-language-features      | false | 27        | 2             | 6               | onLanguage:php      |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1553269758561	0	0
main:appReady	1553269758679	118	118
nlsGeneration:start	1553269758682	3	121
nlsGeneration:end	1553269758683	1	122
willLoadMainBundle	1553269758683	0	122
didLoadMainBundle	1553269758749	66	188
main:willInitGlobalStorage	1553269758769	20	208
main:didInitGlobalStorage	1553269758793	24	232
main:loadWindow	1553269758916	123	355
renderer/started	1553269759194	278	633
willShowPartsSplash	1553269759197	3	636
didShowPartsSplash	1553269759200	3	639
willLoadWorkbenchMain	1553269759215	15	654
didLoadWorkbenchMain	1553269759525	310	964
main/startup	1553269760297	772	1736
willInitWorkspaceService	1553269760306	9	1745
willInitWorkspaceStorage	1553269760308	2	1747
didInitWorkspaceService	1553269760320	12	1759
didInitWorkspaceStorage	1553269760323	3	1762
willStartWorkbench	1553269760323	0	1762
LifecyclePhase/Ready	1553269760325	2	1764
willRestoreEditors	1553269760430	105	1869
willRestoreViewlet	1553269760430	0	1869
willResolveExplorer	1553269760447	17	1886
didRestoreViewlet	1553269760455	8	1894
willLoadExtensions	1553269760656	201	2095
didResolveExplorer	1553269760826	170	2265
didRestoreEditors	1553269760967	141	2406
LifecyclePhase/Restored	1553269760967	0	2406
didStartWorkbench	1553269760967	0	2406
extensionHostReady	1553269761145	178	2584
didLoadExtensions	1553269761157	12	2596
LifecyclePhase/Eventually	1553269763486	2329	4925
```

[prof-291f.extHost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2997252/prof-291f.extHost.cpuprofile.txt)
[prof-291f.renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2997253/prof-291f.renderer.cpuprofile.txt)
[prof-291f.main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2997254/prof-291f.main.cpuprofile.txt)

**Comment by Johnogram** [comment]
p.s. I notice there is not much free memory. I closed a lot, freed up the RAM to `* Memory(System): 11.69 GB(2.59GB free)` but there is no noticeable improvement in performance.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/70955#issuecomment-475667789 has a lot of IPC traffic. Adding @joaomoreno to get more people on this, not sure this is any regression yet, but needs more investigation.

**Comment by joaomoreno** [comment]
@Johnogram Can you reproduce using a brand new user data dir? `code --user-data-dir FOLDER`.

**Comment by Johnogram** [comment]
@joaomoreno Still basically unusable :(
[prof-06e5.extHost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/3002988/prof-06e5.extHost.cpuprofile.txt)
[prof-06e5.renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/3002989/prof-06e5.renderer.cpuprofile.txt)
[prof-06e5.main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/3002990/prof-06e5.main.cpuprofile.txt)

**Comment by Johnogram** [comment]
@joaomoreno Still basically unusable :(
[Uploading prof-06e5.extHost.cpuprofile.txt…]()
[Uploading prof-06e5.renderer.cpuprofile.txt…]()

**Comment by joaomoreno** [comment]
I see nothing wrong in the attached CPU profiles...

@bpasero Given that this doesn't repro with the flags `code --use-gl=osmesa --disable-gl-drawing-for-tests`, I'm not sure there's much I can help here. I don't think that's our IPC.

**Comment by bpasero** [comment]
@Johnogram @DanielFabian does it also reproduce when you disable GPU via "`code --disable-gpu`" from the command line?

**Comment by Johnogram** [comment]
Code Exploration works fine for me using `code --disable-gpu`

**Comment by DanielFabian** [comment]
@bpasero It does seem much better with `--disable-gpu`. Also, I think I must have measured it somehow incorrectly before, because I couldn't repro without any extensions today on the exploration build. However, I've managed to narrow it down to a single extension. The `--disable-gpu` flag helps also when then extension is active.

Name: TypeScript Importer
Id: pmneo.tsimporter
Description: Automatically searches for TypeScript definitions in workspace files and provides all known symbols as completion item to allow code completion.
Version: 2.0.0
Publisher: pmneo
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter
