### ISSUE TITLE
Changes not appearing in Source Control

### ISSUE THREAD

**Issue by thomasbalmer** [Microsoft/vscode#70953]
Issue Type: <b>Bug</b>

When I've made a code change the change is not listed in the Changes section of the Source Control.

If I click on the + icon under changes it finds changes that I've made and adds them to the Stage Changes Section.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|5.98GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
vscode-markdownlint|Dav|0.25.0
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
rest-client|hum|0.21.2
MagicPython|mag|1.1.0
python|ms-|2019.2.5558
autodocstring|njp|0.2.3
vscode-docker|Pet|0.6.1

</details>

**Comment by joaomoreno** [comment]
Did you open the root of the repository as a folder in VS Code? Or did you open a sub folder of that repository?

**Comment by thomasbalmer** [comment]
I beleive I would have opened the root of the repository in VSCode
