### ISSUE TITLE
Emmet Not Working Ubuntu

### ISSUE THREAD

**Issue by mepowerleo10** [Microsoft/vscode#70957]
Issue Type: <b>Bug</b>

On opening a html file, typing a letter.. say "d" and pressing "tab". Emmet autocomplete options do not pop up

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 1580)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|7.50GB (0.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
lit-html|bie|1.11.0
vscode-intelephense-client|bme|1.0.8
gotemplate|cas|0.3.0
path-intellisense|chr|1.4.2
compulim-vscode-closetag|Com|1.2.0
phptools-vscode|DEV|1.0.3241
vsc-material-theme|Equ|2.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
golang-tdd|joa|0.0.9
intellij-idea-keybindings|k--|0.2.31
python|ms-|2019.2.5558
cpptools|ms-|0.22.1
csharp|ms-|1.17.1
Go|ms-|0.9.2
live-server-preview|neg|0.1.4
erlang|pgo|0.5.2
material-icon-theme|PKi|3.6.3
live-preview|pro|0.0.3
java|red|0.40.0
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
vscode-postfix-go|yok|0.0.12
erlang-otp|yuc|0.2.4
html-css-class-completion|Zig|1.18.0

(10 theme extensions excluded)

</details>

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/54894842-f3cfc500-4e79-11e9-8d00-78d3f34ac969.png)

Try `code --disable-extensions`. I guess one of your html extension is messing with emmet, not that emmet is broken.

**Comment by octref** [comment]
Feel free to reopen if that's not the case.
