### ISSUE TITLE
debugToolbar -> debugToolBar

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#70954]
We are deprecting depricating menu contribution point `debug/toolbar` in favor of `debug/toolBar`. That name is more in line with names of other menus.

We will announce this in the release notes and for the following milestone support both.
However in april we will drop support for `debug/toolbar`

fyi @DanTup @weinand

**Comment by DanTup** [comment]
@isidorn Just to be clear:

- v1.32 supports only `toolbar`
- v1.33 supports both
- v1.34 support only `toolBar`

So I should make the change in a version that increases the VS Code requirement to v1.33?

**Comment by isidorn** [comment]
@dantup correct!
