### ISSUE TITLE
Error before running tasks: "test is not defined"

### ISSUE THREAD

**Issue by YangHanlin** [Microsoft/vscode#70958]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open a file that ends with `.cpp` or `.c` (**not `.h`, `.ipp`, etc.**);
2. Press `F1` or `Ctrl + Shift + P` and type `Tasks: Run Task`;
3. Select the option `Tasks: Run Task`;
4. A message will pop up that read:
> There are task errors. See the output for details.
5. Click the button "Show output" and you will see an error message in the output window:
> Error: test is not defined
6. Open Developer Tools > Console, and you will see 3 warnings, like the warnings saved in [this log file (-1553261460757.log)](https://github.com/Microsoft/vscode/files/2996691/-1553261460757.log) (saved with the Developer Tools).

Note:

- I have tried to disable all extensions and the error still appears;
- The error occurs before I choose which task to run, so I think it has nothing to do with my task configuration;
- The error only occurs when you try to reproduce with a `.cpp` or `.c` file opened. **It has nothing to do with the content of the file**: even if an empty file is opened, the error occurs; but when a file with C/C++ code not with suffix `.c` or `.cpp` is opened, the error does not appear;
- The error also appears when tasks are run in other ways, such as select `Terminal > Run Build Task`.
- The error does not affect the build task itself or debugging process. The only effect is that there is an error message.

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.18358

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.25.0
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
carbon-now-sh|eri|1.2.0
code-runner|for|0.9.7
gc-excelviewer|Gra|2.1.29
cpptools|ms-|0.22.1
vscode-icons|vsc|8.3.0
vscode-wakatime|Wak|1.2.13
debug|web|0.23.0

(2 theme extensions excluded)

</details>

**Comment by YangHanlin** [comment]
@alexr00 Could you tell me what info is further needed? I'd like to provide it. Thanks.

**Comment by alexr00** [comment]
@YangHanlin what is in your tasks.json? This is likely a problem there.

**Comment by YangHanlin** [comment]
@alexr00 I think it has nothing to do with my tasks.json as the error appears before I select which task to run.

If you would like to see it, I will do some work to make it cleaner (now there may be some mess in it), confirm there is still the error, and comment.

**Comment by alexr00** [comment]
We enumerate all tasks when you execute the Run Task command. That includes the tasks in your tasks.json.

**Comment by YangHanlin** [comment]
@alexr00 I cleaned my tasks.json and the error still occurs and now it looks like this: (sorry I cannot upload the file as JSON format is not supported by GitHub)

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "command": "g++",
            "args": [
                "-DDBGGING",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-g",
                "-Wall",
                "-static-libgcc",
                "-std=c++17"
            ],
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true
            },
            "problemMatcher":"$gcc"
        }
    ]
}
```

**Comment by shepdelacreme** [comment]
I'm having this same issue. It started when I upgraded to the March 2019 1.33 Insiders release. Although my version bumped a couple of times when I did the upgrade today so it may have been an earlier release.

Like the OP I'm seeing this when trying to run tasks in my C/C++ projects.

**Comment by alexr00** [comment]
Thank you for reporting this!
