### ISSUE TITLE
Invalid path causing updates to fail and shortcut to get corrupted

### ISSUE THREAD

**Issue by atkulp** [microsoft/vscode#70968]
Issue Type: <b>Bug</b>

I have VS Code installed on the D drive (where user profiles are).  It was completely failing the update each time due to "ERRO Bad arguments: Code path doesn't seem to exist."  The path it provides is indicative of the underlying error though:

D:\Users\FIRST.LAST\AppData\Local\Programs\Microsoft VS Code\%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe

Checking Registry, this is the path it reflects in HKEY_USERS\ID\Environment\Path,  HKEY_USERS\ID\SOFTWARE\Classes\Applications\code.exe\DefaultIcon, and most other path instances and also what it updates the shortcut to on every update attempt.

It's even worse in VSCodeSourceFile\shell\open\command:

""D:\Users\FIRST.LAST\AppData\Local\Programs\Microsoft VS Code\%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe" "%1"%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe" "%1"

Looking into the actual folder, I see that it somehow created a folder based on the environment variable.  Didn't realize that was even possible!

D:\Users\FIRST.LAST\AppData\Local\Programs\Microsoft VS Code\%LOCALAPPDATA%\Programs\Microsoft VS Code
(yes, "%LOCALAPPDATA%" is actually a subfolder there)

Step to reproduce is simply to click "Update Now" when prompted.  It just shows the fail dialog and breaks the shortcut.

After deleting the %APPLOCALAPPDATA% folder and fixing every single VS Code path in registry it now works.  Hopefully this helps track down how it happens.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (10.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
typescript-javascript-grammar|ms-|0.0.50
vscode-icons|vsc|8.3.0

</details>

**Comment by joaomoreno** [comment]
@atkulp Any clue how a literal `%LOCALAPPDATA%` could have gotten there? If you fully reinstall, can you reproduce?

**Comment by atkulp** [comment]
I can't imagine.  I can try uninstall/reinstall today to test it.  It might have been installed global first then uninstalled and reinstalled per-user, but I'm not 100% sure that was this machine since I've needed to switch machines recently.  I'll update with results later today.
