### ISSUE TITLE
Tree does not highlight item under context menu if tree does not have focus

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#70966]
Issue Type: <b>Bug</b>

1. Try to invoke context menu on Explorer item
2. The item in Explorer is not highlighted

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.17763

**Comment by usernamehw** [comment]
In **Stable** it doesn't work for Custom Trees.

**Comment by isidorn** [comment]
You first have to click on the tree to give it focus (first clicks in my gif show how the tree first does not have focus).
This works for me. Are you doing something different

![highlight](https://user-images.githubusercontent.com/1926584/54835909-65b1de00-4cc3-11e9-913c-f411cb5802ed.gif)

**Comment by usernamehw** [comment]
So ... more breaking changes? And to the worse... Making 2 clicks instead of 1... just ... why?

If you are using <kbd>Shift</kbd>+<kbd>F10</kbd> it doesn't highlight too.

**Comment by usernamehw** [comment]
Also clicking is opening the file(or executing action in Custom Views) which I don't want to.

**Comment by isidorn** [comment]
Updating title. Forwarding to @joaomoreno  this is a tree issue

**Comment by joaomoreno** [comment]
@isidorn This is a consequence from https://github.com/Microsoft/vscode/issues/68697.

The item is highlighted, the "focus" trait is indeed there. But since the tree isn't DOM focused, the row doesn't have any background color. Just right click an element and then click in the editor... the element will be highlighted then.

@misolori This is why we go back and forward on this all the time.

**Comment by misolori** [comment]
Maybe I'm missing something, but I'm able to get a highlight on a tree item when invoking the context menu?

![gif](https://user-images.githubusercontent.com/35271042/54935031-bea88e80-4edc-11e9-98eb-2f5bc1335066.gif)

**Comment by isidorn** [comment]
@misolori first get the focus out of the viewlet.

**Comment by misolori** [comment]
So it appears this happens when there is no focus on the entire application (in the background) and you attempt to right-click.

@joaomoreno is there any way to apply this highlight when the application window is inactive and not when you're in the app? In that case it makes sense to show a highlight but I also wouldn't want this when I'm in a different part of the editor.

**Comment by joaomoreno** [comment]
@misolori This also happens in custom menus, regardless of window focus.

**Comment by jsunsawyer** [comment]
Not sure why my issue was closed as a duplicate, but I hope that this issue can resolve it. See #72013

**Comment by misolori** [comment]
@isidorn @joaomoreno since #72013 was closed, are we planning on updating this issue to cover the overall focus of the app when it's in the background? Here's a GIF of that issue:

![gif](https://user-images.githubusercontent.com/35271042/55898564-b6f11700-5b77-11e9-8193-e9cd2129aa32.gif)

**Comment by joaomoreno** [comment]
That's more of a question for @bpasero

**Comment by bpasero** [comment]
We have a setting `window.clickThroughInactive` for macOS that controls that. By default we allow to click through.

**Comment by Multiply** [comment]
> We have a setting `window.clickThroughInactive` for macOS that controls that. By default we allow to click through.

I'm pretty confident that is enabled for me, and when I rightclick (while vscode is not focused) on a folder to create a new file, it doesn't allow me to type anything, as the window didn't get focus.

**Comment by jsunsawyer** [comment]
Maybe it's more that actions in the right click menu that trigger actions that require focus to interact with should trigger a focus on the app.

**Comment by florianrusch** [comment]
The description of `window.clickThroughInactive` says, that the window will be activated and then the element under the mouse will be triggered. But that's not how it work...

![image](https://user-images.githubusercontent.com/1724759/62042263-f82c3600-b1fd-11e9-83fc-f873b9dc0892.png)

If I do a right click, like @misolori showed in his gif, the window will not be activated.

Belongs this bug to this issue? Or should I create a new one?

**Comment by misolori** [comment]
Given that this issue seems to flop [based on this](https://github.com/microsoft/vscode/issues/70966#issuecomment-476140126), I'm going to close as `wont-fix`.
