### ISSUE TITLE
Console.WriteLine() does not result in an empty line anymore.

### ISSUE THREAD

**Issue by StasD** [Microsoft/vscode#70962]
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.3
- .NET Core SDK Version: 2.2.105

Steps to Reproduce:

1. use Console.WriteLine() without arguments or with empty string argument in c# code
(put a call to Console.WriteLine() without arguments between Console.WriteLine() with arguments, so that the behavior is obvious)
2. see what it outputs in the debug console (Currently it has no effect, while it should be an empty line)

Does this issue occur when all extensions are disabled?: N/A (c# extension has to be enabled anyway)

It used to work with previous versions of VS Code and .NET SDK (resulted in proper empty line in the console).

**Comment by weinand** [comment]
@isidorn a regression?

**Comment by isidorn** [comment]
Should be fixed in latest
@StasD can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

Similar issue https://github.com/Microsoft/vscode/issues/69535

**Comment by StasD** [comment]
Hi,
No, it did not work with the insider version, either.
But, when I downloaded the previous version (1.31.1), it worked properly, as before.

On a side note, the insider version did not pick up any of my settings (despite that I renamed the .app file / folder to match the normal one before moving it to 'Applications'), which is annoying...

**Comment by isidorn** [comment]
I can not reproduce this with node. So I would ask you to please file this against C#
![emptyLine](https://user-images.githubusercontent.com/1926584/54833867-34cfaa00-4cbf-11e9-9e2c-a5ca8ba28139.gif)

Please file against C# and they can investigate more from their side if they are doign something special. Thank you
https://github.com/OmniSharp/omnisharp-vscode

**Comment by isidorn** [comment]
My mistake. I can reproduce when there is no source linked with the output. Reopening and investigating....

**Comment by isidorn** [comment]
The issue here is that we started using dynamic heights for the tree in the debug console.
So the tree gives an empty element a dynamic height of 0 which makes it invisible.
As a fix all elements that do not have content I set to not have dynamic height.

fyi @joaomoreno

**Comment by StasD** [comment]
OK, hope it will work properly in the next version!

Also, why did you investigate it using console.log()? It's JavaScript code, right? While I was talking about C#'s Console.WriteLine().

I.e. you create a folder somewhere (called e.g. 'console1'), then cd to it in the Terminal, then run 'dotnet new console', then open the resulting project in VS code, change
Console.WriteLine("Hello World!");
into
Console.WriteLine("Hello");
Console.WriteLine();
Console.WriteLine("World!");
then go to Debug tab and just click the green triangle there to run it. :)

**Comment by isidorn** [comment]
Javascript is easier for my personal setup.
Yes the next release will have the fix. In the meantime you can use vscode insiders which will have the fix starting on Monday https://code.visualstudio.com/insiders/

**Comment by StasD** [comment]
Cool. Thanks!
But for now it is perhaps easier for me to just change to Console.WriteLine(" "); which works OK. :)

**Comment by octref** [comment]
@isidorn How to setup for "no source linked with the output"?

**Comment by isidorn** [comment]
@octref use some debugger that is not node, for exampe python, go, c#
An alternative is to verify out of source and set this sourceData to undefined [here](https://github.com/Microsoft/vscode/blob/c09aac5dffa0d55a5cbfb9ec2a81bc97ddbb9c6f/src/vs/workbench/contrib/debug/common/debugModel.ts#L32)

**Comment by octref** [comment]
Verified in Python debugger.
