### ISSUE TITLE
Add Better integration between PowerShell Extention Terminal Session and New Integrated Terminal.

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#7096]
- VSCode Version: 1.2.0-Insiders
- OS Version: Windows 10

These should be able to share the same session, but first #7095 likely needs to be addresses since the PowerShell Extension uses a 64 bit session.

The Latest Version of the PowerShell Extension added a new Profile `Microsoft.VSCode_profile.ps1` for use in the PowerShell Extension session, it would be beneficial if the Code Terminal could also use this profile. Right now the editor is using the default console profile `Microsoft.PowerShell_profile.ps1`

There are a lot of great new features in the PowerShell Extension for interacting with the editor environment, and it would be beneficial to be able to take advantage of these in the integrated terminal.

**Comment by daviwil** [comment]
I think this one can be closed, it's coming to the PowerShell extension in a few days.
