### ISSUE TITLE
Image resolution in status bar does not disappear when non-images are previewed

### ISSUE THREAD

**Issue by hxlnt** [Microsoft/vscode#70977]
Issue: 
When an image is previewed in VSCode, the image's resolution and file size appear in the status bar as expected. However, this content is not removed from the status bar when a different file is selected. It looks like the relevant code is in `vscode/src/vs/workbench/browser/parts/editor/editorStatus.ts`.

Environment:
- VSCode Version: 1.32.1
- OS Version: Windows 10

Steps to Reproduce:
1. Click on a .PNG file in file browser. Image resolution and size appears in status bar.
2. Click on any other file in file browser. Previous image resolution and size still appear in status bar.

Does this issue occur when all extensions are disabled?: Yes

![screenshot2](https://user-images.githubusercontent.com/9647195/54843929-9550ee00-4ca3-11e9-8c9a-c403840ca36b.png)

**Comment by usernamehw** [comment]
I think it was fixed in **1.32.2** OR **1.32.3**. Can you try to update?

**Comment by hxlnt** [comment]
Fixed in 1.32.3--thanks! Closing.
