### ISSUE TITLE
Support external links for go to definition

### ISSUE THREAD

**Issue by Linskeyd** [Microsoft/vscode#70973]
Currently, go to definition for external links does not seem to be supported in VSCode.  

This would be a useful feature, as it would allow easy navigation out of editor to endpoints of interest (without having to support the more heavy-weight [document links LSP method](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentLink)).

While developing a Language Server extension for VSCode, I registered the capability for [go to definition](https://microsoft.github.io/language-server-protocol/specification#textDocument_definition) and attempted to return a response where the [location link response](https://microsoft.github.io/language-server-protocol/specification#locationlink) had a 'https://' prefixed targetUri.  However, an error is thrown saying vscode cannot parse the resulting link (when attempting to hover over a term and hold down cmd on a mac).  I'd want the link to show up as clickable once I hold down cmd, and then navigate once I click while holding command.  The example link I used was 'https://www.google.com'.  I've included a screenshot of the error thrown.

<img width="1319" alt="Screen Shot 2019-03-22 at 10 51 27 AM" src="https://user-images.githubusercontent.com/5875538/54843062-be1bb800-4c90-11e9-83ed-dc262c37a6c5.png">

Is this a design decision to not allow external links as a part of go to definition? It seems like the 'DocumentLink' response type could just be allowed as type for the go to definition response, which would enable the external link to be followed (by type checking, and then navigated or resolving depending on whether the link needs to be resolved by the language server).

**Comment by jrieken** [comment]
The design is that go-to-definition opens an editor showing a text document. If you want to use a custom scheme you can register a `FileSystemProvider` or a `TextDocumentContentProvider`, however common schemes like `http` or `https` are reserved.
