### ISSUE TITLE
VS Code insiders- uri links do not work when clicked from VS Code insiders 

### ISSUE THREAD

**Issue by setaskin** [Microsoft/vscode#70983]
We discover the issue from VS Live Share extension welcome page. The links in the page opens up from VS code stable, but the same links doesn't work on VS Code insiders. The issue is confirmed by creating a new helloWorld extension. Links works on stable when they clicked but doesn't work on insiders. Example link used : "https://aka.ms/vsls-docs/vscode#co-debugging"

**Comment by weinand** [comment]
Please see Kai's duplicate #71088. He did already lots of investigation...

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/71112
