### ISSUE TITLE
Regression: vscode closes (crashes?) after running tests

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#70984]
Issue Type: <b>Bug</b>

This just started happening yesterday, so I assume it's a regression with the latest version.

1) Get any extension project
  option a) yo code -> New Extension (TypeScript) -> give it a name, use all other defaults
  option b) git clone https://github.com/Microsoft/vscode-azurearmtools.git -> npm I
2) Load folder into vscode
3) launch tests from vscode
!) After the tests run, both the extension host instance and the main instance of vscode close

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (17.63GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/test|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
capturesyntaxtokens|Mic|0.0.1
vscode-antlr4|mik|2.1.1
vscode-cosmosdb|ms-|0.10.0
extension-manifest-editor|ms-|0.1.5
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|1.0.0
azurerm-vscode-tools|msa|0.5.0
vscode-docker|Pet|0.6.1
vscode-yaml|red|0.3.0
vscode-sort-json|ric|1.13.0
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
sort-lines|Tyr|1.8.0
win-ca|uko|2.4.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by octref** [comment]
Did you run this when VS Code stable is still open, and got the following error?

```
Running extension tests: /Users/pine/Code/vscode-ts/.vscode-test/vscode-1.32.3/Visual Studio Code.app/Contents/MacOS/Electron /Users/pine/Code/vscode-ts/out/test --extensionDevelopmentPath=/Users/pine/Code/vscode-ts --extensionTestsPath=/Users/pine/Code/vscode-ts/out/test --locale=en
[main 2019-03-25T04:03:09.998Z] Running extension tests from the command line is currently only supported if no other instance of Code is running.

[main 2019-03-25T04:03:10.000Z] Error: Running extension tests from the command line is currently only supported if no other instance of Code is running.
    at EADDRINUSE.l.code.u.connect.then.t (/Users/pine/Code/vscode-ts/.vscode-test/vscode-1.32.3/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:480:647)
    at process._tickCallback (internal/process/next_tick.js:68:7)

internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/Users/pine/Code/vscode-ts/.vscode-test/vscode-1.32.3/Visual Studio Code.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as dialog] (/Users/pine/Code/vscode-ts/.vscode-test/vscode-1.32.3/Visual Studio Code.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/Users/pine/Code/vscode-ts/.vscode-test/vscode-1.32.3/Visual Studio Code.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:451:27)

Tests exited with code: 7
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If so that's expected. You can't run the extension test when another instance of VS Code is running. For that reason I suggest using vscode insiders for development and run `npm run test` in terminal, or just close VS Code stable completely and run test from a regular terminal.

**Comment by StephenWeatherford** [comment]
No, I didn't.  This happens on my Win and Mac boxes without other instances open.  Regression from a few days ago.

**Comment by StephenWeatherford** [comment]
And as I said, vscode crashes/closes.

**Comment by octref** [comment]
- `yo code`, choose TS extension
- Run `npm run test` in the extension folder in a terminal, without VS Code open
- What happens? What's the output on terminal?

**Comment by octref** [comment]
Looking into this, happening to me now too.

I can repro this on `vscode` 1.29 as well, so that's before my changes went in. @bpasero fyi.

**Comment by octref** [comment]
Here's the repro: https://github.com/octref/vscode-70984

Steps I did:

- `yo code`, TS extension, manually `yarn add vscode@1.1.29` to ensure it's not related to new changes in `vscode` module
- Run The `Extension Tests` debug target

Stable:

![image](https://user-images.githubusercontent.com/4033249/54955276-127d9c80-4f0a-11e9-90d5-7e4ddbbc4efb.png)

Insiders:

![exthost-crash](https://user-images.githubusercontent.com/4033249/54955448-8cae2100-4f0a-11e9-90be-96f9de99f00c.gif)

@alexandrudima Did something in extension host change?

**Comment by bpasero** [comment]
A regression from https://github.com/Microsoft/vscode/commit/499686ca03e0995a286b24964de1ee8ec7b3adf1 where we now seem to send `ipc.send('vscode:exit', code)` when the extension host goes down which in turn will kill VSCode entirely.

**Comment by octref** [comment]
@StephenWeatherford This should be fixed in latest insiders.

**Comment by StephenWeatherford** [comment]
Works, thanks!

**Comment by ycjcl868** [comment]
me too

**Comment by octref** [comment]
@ycjcl868 The fix is only in Insider channel, not in Stable release yet.

**Comment by ycjcl868** [comment]
VSCode (1.33.0-insider) not working.

**Comment by ycjcl868** [comment]
@octref  ok, thanks
