### ISSUE TITLE
Custom user snippets fail within Emmet defined snippets

### ISSUE THREAD

**Issue by mindpixel-labs** [Microsoft/vscode#70982]
- VSCode Version: 1.32.3
- OS Version: Mac OSX 10.13.6 High Sierra

It seems that when you are within a cursor of another snippet, specifically an HTML Emmet snippet, you cannot trigger any of your custom snippets unless you explicitly exit out of the cursor and go back in and hit tab. Otherwise, it will just go to the second cursor option as defined within the Emmet snippet.

**Steps to Reproduce:**

1. Create any custom user-defined snippet
2. Create an HTML5 anchor tag with Emmet auto-completion and then try to execute your custom snippet within the double quotes within the anchor tag href attribute.

Does this issue occur when all extensions are disabled?: **Yes**

**Example**
![](https://media.giphy.com/media/xBoTgoo4DxovPpIzye/source.gif)

**Expected Behavior**
As soon as you start to type a prefix of one of your custom snippets it should bring up a search of options that relate to your custom snippet, and when you hit tab it should insert it.

**Comment by octref** [comment]
@jrieken Is is an ad-designed, existing limitation?

**Comment by jrieken** [comment]
This setting `editor.suggest.snippetsPreventQuickSuggestions`
