### ISSUE TITLE
Improve checkout branch visibility

### ISSUE THREAD

**Issue by stevemoser** [Microsoft/vscode#70985]
Searching around the git tab and and the command palette I couldn't easily find how to switch branches. I propose two changes to increase the visibility of checking out branches. 

1) Add something about checking out or switching branches in the 3 dots dropdown on the git tab. Or even an option to show all branches in the git tab.
2) In the command palette change 'Git: Checkout to...' to 'Git: Checkout to branch' so that this command will appear when the user searches for 'branch' in the command palette.

I'm just comparing this to GitHub Desktop where searching for 'branch' under the Help menu shows 'Show Branches List' which then lets you checkout a branch.

**Comment by joaomoreno** [comment]
Added the command to the `...` menu. Can't add `branch` to the command name since tags are also possible targets for checkout.
