### ISSUE TITLE
editor.wordHighlightBackground not having effect

### ISSUE THREAD

**Issue by dl2n** [Microsoft/vscode#70987]
Issue Type: <b>Bug</b>

I'm using default Dark+ and trying to specify a different word highlight, the style which I believe applies when the cursor is in a word, and we try to highlight the other instances of that word nearby (a variable name, for instance). If it matters, this is in C++ w/ the MS C++ extension live.

This is Code 1.32.3 on a Windows 19H1 Insider flight. I believe this is current/up to date.

I've tried several variations, and cut it down to this. I believe this should give me a medium red transparent highlight, but I'm still getting the default dark gray. This is my entire settings.json:

```
{
    "files.trimTrailingWhitespace": true,
    "editor.fontSize": 11,
    "nmake.hide-large-folder-notification": true,
    "window.zoomLevel": 0,
    "editor.renderWhitespace": "none",
    "editor.renderControlCharacters": false,
    "breadcrumbs.enabled": false,
    "files.trimFinalNewlines": true,
    "workbench.colorCustomizations": {
        "editor.wordHighlightBackground": "#ff000044"
    }
}
```

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.18359

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2950X 16-Core Processor  (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (6.44GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|1.1.190227006
cpptools|ms-|0.22.1
PowerShell|ms-|1.11.0

</details>

**Comment by alexandrudima** [comment]
This works for me, e.g. read access in TS uses the color:

```
"workbench.colorCustomizations": {
	"editor.wordHighlightBackground": "#ff0000"
}
```

![image](https://user-images.githubusercontent.com/5047891/55098888-05ee7500-50bf-11e9-9cb8-c7d0126a7b3a.png)
