### ISSUE TITLE
Add ARIA info to dialogs

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#70981]

**Comment by isidorn** [comment]
This sounds like low hanging fruit.
@sbatten can you provide a code pointer so we add a help-wanted label?

**Comment by sbatten** [comment]
https://github.com/Microsoft/vscode/blob/3074fd588d1a01ae552243a1c4359b4cf0d5227d/src/vs/base/browser/ui/dialog/dialog.ts

**Comment by isidorn** [comment]
Removing help-wanted since I provided a PR for this
