### ISSUE TITLE
Formatting or Other Features Provided by Extensions Do Not Work on New Unsaved Files

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#70988]
Although the issue seems caused by extensions, however, multiple extensions have the same issue, so cannot exclude if it's the limitation by VS Code.

If I open an existed C or Java file, everything is OK.
If I **create a new file and select specific language mode**, formatting doesn't work.
If I save the new file, everything is OK again.
https://github.com/Microsoft/vscode-cpptools/issues/3343
https://github.com/redhat-developer/vscode-java/issues/856
So the issue only occurred on **new unsaved files**.

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.22.1
java|red|0.41.0

**Comment by octref** [comment]
@jrieken FYI

**Comment by octref** [comment]
@byyxx128 Linking #70314 fyi. Probably related to changes there.

**Comment by byyxx128** [comment]
Maybe related, not sure. https://github.com/Microsoft/vscode-cpptools/issues/3343 has realized the issue, but no idea how to fix. https://github.com/redhat-developer/vscode-java/issues/856 has abandoned because they thought it was complicated to achieve. In this situation, I can't help suspecting if it's VS Code's problem. I think your team needs to cooperate with other extension teams and help them easily to develop extensions.

**Comment by byyxx128** [comment]
Maybe related, not sure. https://github.com/Microsoft/vscode-cpptools/issues/3343 has realized the issue, but no idea how to fix. https://github.com/redhat-developer/vscode-java/issues/856 has abandoned because they thought it was too complicated to achieve. In this situation, I can't help suspecting if it's VS Code's problem. I think your team needs to cooperate with other extension teams and help them easily to develop extensions.
