### ISSUE TITLE
vscode.window.createOutputChannel caused 10 second hang in extension

### ISSUE THREAD

**Issue by jkeech** [Microsoft/vscode#70998]
- VSCode Version: `1.32.3`
- OS Version:`Windows_NT x64 10.0.17763`

Steps to Reproduce:

1. Extension calls vscode.window.createOutputChannel() to create an output channel
2. Call took a long time to return due to a 10 second `fs.stat` call when creating the underlying rotating logger (see screenshot from profile below)
3. VS Code blamed the extension for causing a CPU hang

![image](https://user-images.githubusercontent.com/746020/54861198-a9681000-4ce2-11e9-842a-3fe2552b8770.png)

Does this issue occur when all extensions are disabled?: Not sure, but the issue occurred when called from an extension. See MicrosoftDocs/IntelliCode#77 for more details.

A couple questions:
1) Can anything be done to make output window creation not dependent on file system calls?
2) Is there a better way to create the output window in an async way (with async fs calls underneath) that won't block the extension host?
2) Can the VS Code extension blaming logic be updated to remove time spent in VS Code APIs? As an extension author who seems to be calling the APIs in a supported way, a high CPU report that blames my extension seems unactionable to me in this case and also might give the wrong impression about the extension performance to users.

**Comment by sandy081** [comment]
This is because the folder under which the output channel file is created does not exist and there is a sync call to create it. Will change it to async.

**Comment by sandy081** [comment]
To verify make sure output channels (e.g., git, typescript) show the data properly

**Comment by octref** [comment]
Need more steps, show what data properly?

I do see that a folder like `output_1_20190327T162056` is created upon start, but the `extensions.log` and `tasks.log` inside it are both empty.

**Comment by sandy081** [comment]
`extensions.log` and `tasks.log` channels are created inside core. Please use channels created from extensions for example `git`. 

@joaomoreno Can you please verify that the git channel is showing the data as expected. Also please try out the output channel actions available in the panel, like `clear`.

**Comment by joaomoreno** [comment]
All looks like it's working. 👍
