### ISSUE TITLE
Grammar for golang produces incorrect syntax highlighting

### ISSUE THREAD

**Issue by vladbarosan** [Microsoft/vscode#70993]
- VSCode Version: `1.32.3`
- OS Version: `Windows_NT x64 10.0.17763`

Steps to Reproduce:

See  https://github.com/Microsoft/vscode-go/issues/2367

**Comment by alexr00** [comment]
This is an issue with the grammar, since the grammar is functioning as written and categorizing the second `string` as `variable.other.assignement.go`. Moving to the repository that owns the grammar.

**Comment by alexr00** [comment]
New issue: https://github.com/atom/language-go/issues/170
