### ISSUE TITLE
extensions are not installed

### ISSUE THREAD

**Issue by g-struchin** [Microsoft/vscode#70991]
I cannot install extensions through the manager in visual studio.
When I click on the install button it changes to Installing
I waited 2 hours.
The extension is not installed.
I tried to install different extensions.
Installation via "install from vsix" gave positive results.

I have already reinstalled vs code.
Opened on behalf of the administrator.
nothing helps

Version: 1.32.3 (user setup)
OS: Windows_NT x64 10.0.17134

**Comment by mamonraab** [comment]
ubuntu 18.04  can not install any extions , i tried to install vsode from offical  ubuntu repo and not work , also from download the latest version from your website and not work , also install vscode from anaconda navigator and not work  all not install extensions and tell me this message
Cannot read property 'local' of undefined

**Comment by g-struchin** [comment]
@mamonraab 
Did you find a solution to the problem?
Old versions of vs code also have this problem?
Or is this a problem in marketplace.visualstudio.com?

**Comment by g-struchin** [comment]
Extensions do not work in update November 2018 (version 1.30).
Updates below 1.30 install pointless. Required extensions require updates above 1.30.

**Comment by mamonraab** [comment]
@g-struchin   , i fix the problem i see it my fault i did not check the permission of extensions in .vscode  dir  but as far i remmber when i was work on ubuntu 16.04  here was no such problem

**Comment by sandy081** [comment]
Can you please open the logs (F1 -> Open View -> Log (Shared) ) and check if there are any errors?
