### ISSUE TITLE
Allow debug target configuration switching per file

### ISSUE THREAD

**Issue by sepehr-laal** [Microsoft/vscode#70999]
It would be nice to switch debug target configurations based on a file or directory I am working on. In bigger projects, there can be a dozen different debug targets and not all of them work on all files. Here is an example:

File in directory: `<repo>/tests/sample.js`

```JS
/* vscode-debug-target: mocha-tests */

const chai = require('chai');

describe('tests', () => {
  // ... tests
})
```

File in directory: `<repo>/src/app.js`

```JS
/* vscode-debug-target: server-app */

const Server = require('./Server');
const port = 2525;
const instance = new Server(port);
server.startListening();
```

Here if I have the `app.js` file open and active in the editor and I hit F5, it automatically launches with the `server-app` debug target indicated by a comment at the top of the file.

I am unsure if this is doable by writing an extension.

**Comment by weinand** [comment]
Yes, that is easily doable with and extension.
