### ISSUE TITLE
Markdown Syntax Highlighting - Opening Literal

### ISSUE THREAD

**Issue by cbreeden** [Microsoft/vscode#7099]
- VSCode Version: 1.1.1
- OS Version: Linux Mint LMDE 2

Steps to Reproduce:
1. Create new markdown file.  Type in: 
```
The TeX command `\TeX` is fun! So is `\LaTeX`!
```

Problem:
In markdown `` `\ `` doesn't appear to be registered as an opening code literal for syntax highlighting.
Code will highlight this as shown:

![markdownhilight](https://cloud.githubusercontent.com/assets/12069845/15714738/5fb205fc-27e1-11e6-941f-1321f3035f75.png)

I was looking into possibly fixing this, but I found this statement
> some of VS Code's built-in colorizers (e.g. Markdown) are integrated differently and cannot be overridden.

here <https://code.visualstudio.com/Docs/customization/colorizer>.  So I didn't know where to look really.

**Comment by mjbvz** [comment]
Looks like this is fixed, at least for the example provided:

<img width="853" alt="screen shot 2016-09-19 at 1 57 33 pm" src="https://cloud.githubusercontent.com/assets/12821956/18648799/1548325c-7e71-11e6-965c-0781b213e423.png">

Could you please try a more recent build and let me know if you can still repo the problem? Thanks.

**Comment by cbreeden** [comment]
Works like a charm in version 1.4.0.  Thank you :)
