### ISSUE TITLE
A right-located sidebar grows larger on cycling Zen mode

### ISSUE THREAD

**Issue by arbitar** [Microsoft/vscode#70996]
Issue Type: <b>Bug</b>

(User Interface)

Repeatedly entering/exiting Zen mode causes the panel to grow larger and larger over time, causing an annoying requirement to stop and shrink it back down over time. This doesn't seem to occur while "workbench.sideBar.location" is set to "left".

To reproduce:
  1. Set editor setting "workbench.sideBar.location" to "right"
  2. Expand your file Explorer
  3. Take note of the location of the left edge of your Explorer
  4. Use your assigned "View: Toggle Zen Mode" hotkey to enter Zen mode
  5. Press your Zen hotkey again to exit Zen mode.
  6. Note the new location of the left edge of your Explorer. It should be somewhat more to the left than before.

NOTE:
  * My Zen mode configuration is unchanged from default.
  * My hotkey for Zen mode has been changed to Ctrl+F11
  * My fullscreen hotkey has been retained as its default F11.
  * This seems to occur with any sidebar panel - not just the Explorer.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by isidorn** [comment]
I cannot reproduce this issue following your exact steps
Can you repro with latest vscode insiders https://code.visualstudio.com/insiders/
