### ISSUE TITLE
[xml] provide a formatter

### ISSUE THREAD

**Issue by zwernberg** [Microsoft/vscode#71]
before the update I could use alt+shift+f to code format an xml file. After the update this no longer works (using windows version 0.10.1)

**Comment by Thoorium** [comment]
This issue is not limited to XML. All code format seems to be gone or the command is broken.

**Comment by zwernberg** [comment]
@Thoorium thanks I've updated the title to highlight that.

**Comment by briankuhncelera** [comment]
I am experiencing the same issue with XML files.  Prior to the 0.10.1 update, XML files could be formatted using Alt-Shift-F or the context menu.  Since pulling the update, I cannot format XML files.

I can, however, format .js files.

**Comment by mkebrian** [comment]
I am experiencing the same issue with XML files. Prior to the 0.10.1 update, XML files could be formatted using Alt-Shift-F or the context menu. Since pulling the update, I cannot format XML files.

I can, however, format .js files.

**Comment by aeschli** [comment]
XML formatting has been removed as it was based on the HTML formatter and had lot of bugs.
We hope that an extension can provide a high quality XML formatter.

**Comment by FabianLauer** [comment]
Started to work on one tonight. I'm not at all happy with it yet, but maybe it's a start. https://github.com/FabianLauer/vs-code-xml-format

**Comment by aeschli** [comment]
Great!

**Comment by aeschli** [comment]
There's now even a second extension:
https://marketplace.visualstudio.com/items/DotJoshJohnson.xml

**Comment by bgashler1** [comment]
Related #2117

**Comment by bgashler1** [comment]
Related #1735 Handlebars Formatting

**Comment by hansvonn** [comment]
A workaround to format XML: 
- change language mode to HTML
- format the document
- restore language mode.

Based on @aeschli's note about the formatter being related to the HTML formatter.
