### ISSUE TITLE
Allow extensions to add additional views

### ISSUE THREAD

**Issue by mattiascibien** [Microsoft/vscode#710]
One great feature that could be added to VsCode is the possibility to add more "tabs" in the letf area like the Git and the Debug one. 

This way one developer can add other things like Sql server browser, github issues and more
![vscode](https://cloud.githubusercontent.com/assets/1300681/11424016/cb99b700-9449-11e5-9997-a2929316e825.PNG)

If somebody already has an idea to where to add these extension pointe I will be glad to help.

**Comment by daviwil** [comment]
That would be really cool, but it sort of implies that extensions need to be able to provide custom UI :)

**Comment by mattiascibien** [comment]
@daviwil I guess that providing UI is not possibile at the moment?

**Comment by daviwil** [comment]
As far as I know it isn't possible yet

**Comment by egamma** [comment]
Yes, not possible at the moment. Please see this doc https://code.visualstudio.com/docs/extensions/our-approach it describes our extensibility approach.

**Comment by mgrenier** [comment]
That would be really useful to add custom panel. I'd like to port my [Atom's Remote-FTP](https://github.com/mgrenier/remote-ftp) to vscode.

**Comment by cwtuan** [comment]
2 years pass, still not possible?

**Comment by ccorcos** [comment]
@daviwil I want to build a custom File Explorer pane that uses metadata from the TypesScript compiler. Would be awesome if I could build it straight into VSCode rather than a separate prototype.

**Comment by daviwil** [comment]
@ccorcos have you seen the explorer tree APIs?  They would allow you to do this.  https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample

**Comment by ccorcos** [comment]
Interesting. Thanks for the link -- I never saw that. It looks like you can't change the basic tree structure though, right? Basically I want to make a graph explorer where children are the file's imports and parents are file that import a file. Then I want to make tags that reference a set of files used for a specific feature. It sounds like this API only allows you to provide a tree...

**Comment by mjbvz** [comment]
Fixed by #43645
