### ISSUE TITLE
Allow "View: Show Search" command to be a Toggle command

### ISSUE THREAD

**Issue by jsunsawyer** [Microsoft/vscode#71001]
I have my search set up in the bottom panel.

Output, Debug Console, and Terminal all use Toggle commands, meaning that I can use the same hotkey to toggle that pane open or close.

This should work the same for all other tabs that display here.

I am often quickly jumping between my search view and my files (with my search view covering most of my screen). This would be a huge quality of life improvement.

**Comment by roblourens** [comment]
You can set up your own keybinding to do this. Example:

```
    {
        "key": "shift+cmd+f",
        "command": "workbench.view.search",
        "when": "!searchViewletVisible"
    },
    {
        "key": "shift+cmd+f",
        "command": "workbench.action.closePanel",
        "when": "searchViewletVisible"
    }
```
