### ISSUE TITLE
Why doesn't work emmet media query? Specifically @m and @media?

### ISSUE THREAD

**Issue by baxebu** [microsoft/vscode#71002]
Why doesn't work emmet media query? Specifically **@m** and **@media**?

- VSCode version: 1.32.3
- Windows 8.1x64:

Steps to Reproduce:

1. I want to using emmet 
2. When i press tab `@media` or `@m` i was expecting [this](https://github.com/emmetio/snippets/blob/master/css.json#L6).

_Look here please:_
![media emmet vscode](https://i.imgur.com/cTS5Wfs.gif)
Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Hi @baxebu, I realize you opened this issue over a year ago, but I noticed on 1.49.3 that there's a `@media screen` abbreviation that is now suggested if you type `@m` inside of a `style` tag within an HTML file. Does this work for your purposes?

**Comment by rzhao271** [comment]
Nvm, labelling this as a bug because `@m` and `@media` both expand properly on other editors.

**Comment by rzhao271** [comment]
Closing in favour of the more general issue #74505
