### ISSUE TITLE
env variables failed to load in debug for nodejs app

### ISSUE THREAD

**Issue by emclab** [microsoft/vscode#71000]
The env variables failed to load in debug with 2 popular modules - `dotenv` and `config`. The app has no problem loading the env variables file in normal development with `nodemon index.js`. But none of the variable is loaded with `Launch index.js` in debug. Initially I thought it was problem with `config`. But after the same problem happens with `dotenv`, I am wondering if this is a bug with VS code.

Here is the VS code info:

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by weinand** [comment]
What do you mean by "env variables failed to load"?
Please provide reproducible steps.
