### ISSUE TITLE
Redirect old extensions to new extension

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/vscode#71006]
We have 3 existing extensions and are planning to merge these 3 into 1 new extension.
After release the new extension, we want to redirect all these three old extensions to this new one, includes in VS Code and the marketplace website:

- In VS Code, all these 3 old extensions would get upgraded to the new extension if installed any of them.
- In VS Code, search the name of any of these 3 old extensions would return the new extension.
- In the VS Code marketplace, search the name of any of these 3 old extensions would return the new extension.

I think this feature is very important for extension developer to manage the lifecycle of their extensions and keep improving the experience of their extensions.

**Comment by Yzrsah** [comment]
You can do this by structuring each of the 3 extensions as an extension pack which includes the other 2 extensions. Extension packs are extensions and can have other contributions. For an example, see [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)

**Comment by SirTwsted** [comment]
just as a consumers input, (persay)  hehehe,  friendly constructive criticism. 
Wouldn't it be better to just delete the old ones when uploading the new one.
so as to not clog up the marketplace with old extensions.
right now there are hundreds of really old and out of date/ obsolete/legacy  extensions.
Last thing we need right now is to keep more old extensions that is not going to be used in the market place.
Thats hoarding the marketplace, wouldn't you think ?

Just a friendly and kind feedback  :D

**Comment by ArthurMa1978** [comment]
> just as a consumers input, (persay)  hehehe,  friendly constructive criticism.
> Wouldn't it be better to just delete the old ones when uploading the new one.??
> so as to not clog up the marketplace with old extensions.
> right now there are hundreds of really old and out of date/ obsolete/legacy  extensions.
> Last thing we need right now is to keep more old extensions that is not going to be used in the market place.
> Thats hoarding the marketplace, wouldn't you think ?
> Just a friendly and kind feedback  :D

That's why I want to have this kind of redirect feature which can help developer to delete old extensions but not lose customers

**Comment by sandy081** [comment]
@ArthurMa1978 We support renaming an extension but not deprecating and redirecting to new. If possible try to see if renaming works out for you, if so, you have to contact Marketplace team for renaming.

Otherwise I dont think we will support for this feature atleast in the near future.
