### ISSUE TITLE
Disable automatic search for system headers 

### ISSUE THREAD

**Issue by martin-zarzycki** [Microsoft/vscode#71005]
This a feature request for vscode-cpptools regarding the handling of system headers
.
Currently when a folder is opened, the extension attempts to locate your system headers based on your operating system. However for development projects on embedded platforms which use a cross compiler (ARM, etc.) this is not helpful. The "incluePath" parameter in c_cpp_properties.json file should take preference over any automatic search results. It would be great to include an option (flag) which allows to bypass or disable the automatic system headers search.

**Comment by roblourens** [comment]
Please file this on the vscode-cpptools repo: https://github.com/Microsoft/vscode-cpptools/issues
