### ISSUE TITLE
Create a setting to define the extensions path

### ISSUE THREAD

**Issue by pauloofmeta** [Microsoft/vscode#71013]
Hi, because of a security rule in my company, i needed to change the installation path of extensions, today i am doing this through the parameter `--extensions-dir`, but this parameter i can only use as an argument when starting vscode, i would suggest the creation of a configuration to inform the path of the extensions, so it would be much better to open the vscode through of the console `code.`

**Comment by sandy081** [comment]
Duplicate of #17691
