### ISSUE TITLE
VS Code does not handle a high amount of code completions well

### ISSUE THREAD

**Issue by natanfudge** [Microsoft/vscode#71015]
Issue Type: <b>Performance Issue</b>

When there is a very high amount of code completions available, vscode will take a long time to show them to the user. Although, this is redundant because the user will likely only scroll through a low percentage of them.

Steps to reproduce:
- Create a new extension with `yo code`.
- In package.json, add the `"*"` activation event. 
- Replace the contents of `extension.ts` with this:
 
```
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	let completionProvider = vscode.languages.registerCompletionItemProvider({ language: "plaintext" }, {
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
			const amount = 10000;
			let completionsArr = new Array<vscode.CompletionItem>(amount);
			let start = Date.now();
			for (let i = 0; i < amount; i++) completionsArr[i] = new vscode.CompletionItem(i.toString());
			let end = Date.now() - start;
			console.log("Time taken by the extension to process completions: " + end);
			return new vscode.CompletionList(completionsArr);
		}
	})


	context.subscriptions.push(completionProvider);
}

export function deactivate() { }
```
- Run the extension and create a new `.txt` file.
- Ask for completions (`ctrl+space`) and notice how there is a delay before the completions are provided, but the actual providing of completions take an insignificant amount of time. 
- Try multiplying the amount of iterations by 10 in case you are not noticing it on your system. 

Note: this might seem like an insignificant problem that never happens, but this amount of completions can be easily reached when for example an extension adds in all of the available namespaces of a project. Secondly, the delays are actually quite annoying and there is no way to deal with them on the extension's side. 

One way to optimize it might be to only show the top 100 or so completions, and update that list whenever the user types (in case there are completions that have not been filtered other than the top 100 being shown currently).  If the user wishes to scroll pass these 100 then the next 100 will be loaded as well (this happens a very low percentage of the time though). 

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:18:30.063Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (11.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    96	  4288	code-insiders main
    0	   138	   416	   gpu-process
    0	    64	  4668	   shared-process
    0	   214	  9412	   window (extension.ts - completions-test - Visual Studio Code - Insiders)
    0	    11	   220	     watcherService 
    0	     9	  1156	       console-window-host (Windows internal process)
    0	    83	 10944	     extensionHost
    0	   108	  2032	       electron_node tsserver.js 
    0	    57	  1028	         electron_node typingsInstaller.js typesMap.js 
    0	    34	 10724	       "C:\Users\natan\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\natan\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=10944
    2	    66	  9956	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (extension.ts - completions-test - Visual Studio Code - Insiders)
|    Folder (completions-test): 15 files
|      File types: json(8) md(3) ts(3) vscodeignore(1)
|      Conf files: package.json(1) tslint.json(1) tsconfig.json(1)
|                  settings.json(1) launch.json(1) tasks.json(1);
```

</details>
Extensions: none

**Comment by jrieken** [comment]
Our testing/benchmarking is for around 20000 suggestion. With that my 2015 MBP shows ~400ms total time (from request to result), most time is spend in deserialising data, e.g. `JSON.parse`. We can optimise the data transfer types but ultimately the problem is remains. 

> One way to optimize it might be to only show the top 100 or so completions, and update that list whenever the user types

For IntelliSense we actually support that, however it's the extension that can best pick the top 100 items. When computing your suggestions, mark the result as [incomplete](https://github.com/Microsoft/vscode/blob/fd77ea1e6df6ec35d63f5a9e16a06205720be3b0/src/vs/vscode.d.ts#L3430) and VS Code will check back with every additional character that's being typed (for instance this is how we query npm).
