### ISSUE TITLE
Setting to Disable Split Editor on Drag and Drop

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode#71016]
I use drag and drop a lot to move files among different columns, but never to split the editor into more columns or rows. When moving quickly, I accidentally split the editor a lot, and it slows me down and takes me out of flow. I posit that there are other users that are like this as well.

I would like a setting that disables the behavior of splitting of the panes completely. The behavior I'd like to disable is illustrated in this gif from [the docs](https://code.visualstudio.com/docs/getstarted/userinterface#_grid-editor-layout):

![grid-dnd](https://user-images.githubusercontent.com/1935696/54869262-3b7d2080-4d96-11e9-98e3-c50b44b2bcbd.gif)

Keywords for search:

panes, panels, tabs, grid

Similar issues: #52063

**Comment by JacobDB** [comment]
I'd really like this too, this is extremely annoying to me.

**Comment by Bwin4L** [comment]
Agreed, would definitely love an option that disables this behavior.
It happens to me a lot when dragging and dropping files from the Windows Explorer into VSCode.

**Comment by difosfor** [comment]
Using a Wacom tablet also results in these annoying accidental splits. Sometimes when I click on a tab it accidentally becomes a tiny drag movement resulting in VS Code immediately splitting the editor and me being startled and having to drag the tab all the way back in with the others in the right place.

**Comment by SaschaWillems** [comment]
I second this. Most of the time I'm splitting editor windows even though I don't want to. Instead of just quickly dropping files into the IDE, you now have to carefully drop them in the center to not split the editor. An option to disable this would be great.

**Comment by Slaaaap** [comment]
Hey, try this if your workspace seems to be too large, it worked for me :

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

I had this problem because my workspace had too many files and VSCode couldn't watch all of them.

**Comment by alexey4453** [comment]
They just must implement it.

**Comment by difosfor** [comment]
So.. What is this "community" and "upvote" the bot is talking about?

**Comment by alexey4453** [comment]
VSCODE team needs 20 likes to put the request in process. If 12 members of github upvote it in 60 days, we'll see the option one day in Visual Code.

**Comment by difosfor** [comment]
Still not entirely clear to me who is liking what and where/how exactly. Can I like it as a Github user? Or only members of the VSCODE team?

**Comment by karlhorky** [comment]
I am assuming by "community" they mean the public (users on GitHub). The "upvotes" I'm assuming to be 👍 emojis on the issue description (8 of them right now).

I'm assuming these two things based on previous feature request voting behaviors I've seen in other projects.

**Comment by tringuyen-yw** [comment]
I wonder how to categorize this "drag-drop to split screen": is it a design feature or a bug? Personally I find this very annoying, I would consider this as a bug. Would like to add my vote to either remove this unfortunate feature or give a setting to disable it.

**Comment by q2apro** [comment]
When is this setting coming? The implementation seems pretty basic. 

And I think, btw, it should be disabled by default. Most of the developers I worked with do not use split screens when they work.

**Comment by ithinkandicode** [comment]
I happened across this thread trying to find a fix. Glad to see it's in the backlog, it's been an unintuitive feature for ages. I've used it intentionally maybe once, but accidentally dozens of times.

**Comment by q2apro** [comment]
This "feature" is completely annoying, I am not a sniper to pin point my drag and drop. I just drop onto the window and expect the file opening.

Please add an option to disable this. Thanks a lot. 😀

**Comment by bpasero** [comment]
Added a new setting `workbench.editor.splitOnDragAndDrop` to control this. I also added a way to toggle this conditionally during the drag and drop operation when you press and hold `Shift` key (macOS) or `Alt` key (Windows, Linux).

**Comment by karlhorky** [comment]
Thanks @bpasero, cool! And nice touch with the modifier key too :)

**Comment by q2apro** [comment]
I hope it is deployed with the next VSCode update. 👍 Thanks a lot. Now VSCode feels just perfect.

**Comment by bpasero** [comment]
Yes it should be out in tomorrows insider and then I am happy for feedback how it goes.

**Comment by tringuyen-yw** [comment]
@bpasero thanks very much for the fix. Is the `workbench.editor.splitOnDragAndDrop` setting set to `false` by default? If not can you make it so to help the newcomers to VSCode, avoiding the confusion cause by this sscren split bug?

**Comment by q2apro** [comment]
Even with the latest VSCode 1.51.1 (2020-11-17) `workbench.editor.splitOnDragAndDrop` is not included.

**Comment by bpasero** [comment]
@q2apro you are using the wrong version of VSCode, the correct one to use from now on and never worry again is VSCode Insiders: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
**Verification:** see feature works as outlined in https://github.com/microsoft/vscode/issues/71016#issuecomment-723923012

**Comment by q2apro** [comment]
Finally it is rolled out in the official release (v1.52.1):

![image](https://user-images.githubusercontent.com/6764548/102710435-f794b380-42ba-11eb-8838-ea82c565b36a.png)

One usability issue less!

And yes, now VSCode is (officially) the best editor that I have ever used up to this date. Awesome work guys!

🚀 Happy coding ❤
