### ISSUE TITLE
Whole lines are not copied when there is a text selection

### ISSUE THREAD

**Issue by lukas-tr** [microsoft/vscode#71011]
- Version: 1.33.0-insider (user setup)
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

![vscode copy not working](https://user-images.githubusercontent.com/36337818/54867463-ba675e80-4d80-11e9-8239-ba0e9828fb74.gif)

In this example, both `aaaaaaaaaaaaaa` and `bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb` should have been copied instead of only `aaaaaaaaaaaaaa`.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@lukas-tr have you customized `"editor.emptySelectionClipboard"`. Can you try setting that to `true` (the default) ?

**Comment by lukas-tr** [comment]
> @lukas-tr have you customized `"editor.emptySelectionClipboard"`. Can you try setting that to `true` (the default) ?

I didn't change `"editor.emptySelectionClipboard"`.

**Comment by alexandrudima** [comment]
Have you installed any extension which tries to take over Ctrl+C ?

Can you search keybindings for "Ctrl+C"?
![image](https://user-images.githubusercontent.com/5047891/55109244-a354a380-50d5-11e9-99c7-e9606cead0a5.png)

**Comment by lukas-tr** [comment]
![image](https://user-images.githubusercontent.com/36337818/55232086-b6c25480-5224-11e9-8c7e-97b92c33e39c.png)

**Comment by alexandrudima** [comment]
@lukas-tr Now that I look again at your gif, are you pressing `Alt+Ctrl+C` and expecting that to copy the entire line, even when you have a selection?

**Comment by lukas-tr** [comment]
I am pressing `Ctrl+C` and expect that to copy both the text of the selection and the whole second line.

![image](https://user-images.githubusercontent.com/36337818/55391260-4e7fb580-5539-11e9-9196-4e58539bcec4.png)

Pressing `Ctrl+C` here would copy `aaa\nbbb\nccc`.

![image](https://user-images.githubusercontent.com/36337818/55391464-b46c3d00-5539-11e9-84b1-edcd8ddcef3b.png)

Pressing `Ctrl+C` here would copy `aaaaaaaaaaaaaaaaaaaaa\nccccccccccccccccccccc`.

So having both a selection and a cursor without selection should copy both the selected text and the entire line the second cursor is in.

**Comment by alexandrudima** [comment]
Oh wow, now I understand your gif. So steps would be:
- have 2 cursors
- have cursor 1 with a selection containing text
- have cursor 2 contain no text (collapsed selection)
- press Ctrl+C
![image](https://user-images.githubusercontent.com/5047891/55410225-c531a880-5563-11e9-96c5-44a1e0788fd3.png)

* the clipboard should contain `1\nline2`
* today, the clipboard only contains `1`.
