### ISSUE TITLE
Markdown italic indicator interpreted incorrectly in URL

### ISSUE THREAD

**Issue by crystalfp** [Microsoft/vscode#71017]
Issue Type: <b>Bug</b>

Create a markdown file containing:
```
blog: [sethgodin.typepad.com/seths_blog/2014/09/the-shameful-fraud-of-sorting-for-youth-meritocracy.html](http://sethgodin.typepad.com/seths_blog/2014/09/the-shameful-fraud-of-sorting-for-youth-meritocracy.html)
```
and open it in VSC. You will see the text between the two underscores (in seths_blog) rendered in bold. This makes a long page containing URLs with '_' totally unreadable.

The underscore should make the text _italic_ like here. Instead inside a word (one_two_three) it makes the 'two' text bold (this does not happen here, but happens in VSC). Also in my opinion markdown inside a URL should not be rendered.

Note that in the rest of the file I always use '*' as italic indicator, never '_'.

Thanks for considering!
mario

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (4.71GB free)|
|Process Argv|--file-uri file:///d%3A/Montessori/Libro%20-%20Corriere/Tecnologia%20in%20famiglia.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.3.0
spellright|ban|3.0.28
github-markdown-preview|bie|0.0.2
markdown-yaml-preamble|bie|0.0.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
vscode-pandoc|Dou|0.0.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|9.5.1
vscode-great-icons|emm|2.1.47
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.4
todo-tree|Gru|0.0.125
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
prettify-json|moh|0.0.3
notepadplusplus-keybindings|ms-|1.0.2
leaper|Onl|0.5.3
vscode-jscpd|pau|0.3.4
bib|phr|0.3.0
vscode-javascript-booster|sbu|0.10.2
trailing-spaces|sha|0.2.11
unique-window-colors|stu|1.0.23
highlight-matching-tag|vin|0.8.6
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.1.1

</details>

**Comment by mjbvz** [comment]
Doesn't repo for me:

<img width="1072" alt="Screen Shot 2019-03-27 at 9 04 16 PM" src="https://user-images.githubusercontent.com/12821956/55126860-e746a900-50d3-11e9-8ba6-8b8984937bcf.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by crystalfp** [comment]
It is an extension problem. Sorry for the noise
