### ISSUE TITLE
No Steps Given for JSDoc Comments in Interactive Playground 

### ISSUE THREAD

**Issue by johnyradio** [microsoft/vscode#71023]
Issue Type: <b>Documentation Request</b>

Interactive Playground says:

JSDoc Tip: ..."using JSDoc comments... try this out by invoking the Book function"....

I have no idea what this means, or how to try it out. 

The Interactive Playground doesn't not give steps, as it does for other features. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by johnyradio** [comment]
Another Playground issue:

"See syntax errors with squiggles. Press F8 to navigate across them"

There are no squiggles in the sample code. Pressing F8 jumps to next editor tab.

**Comment by mjbvz** [comment]
@johnyradio Please open a separate issue for the second problem

**Comment by kbajno** [comment]
I would like to address this documentation issue
