### ISSUE TITLE
Tab Fails for Emmet Expansion in the playground

### ISSUE THREAD

**Issue by johnyradio** [microsoft/vscode#71024]
Has been reported before, but not working for me in Playground, in Win 10, brand new VS Code install. 

VS Code version: Code 1.32.3 (a3db5be, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by johnyradio** [comment]
Partially resolved:
- Edit menu should NOT display "Tab" next to Emmet expansion unless it's actually ENABLED. 
- Playground says to enable using: "emmet.triggerExpansionOnTab". But the easier way is to click the "Emmet: Trigger Expansion On Tab" checkbox in settings. Playground should give this easier method.

**Comment by octref** [comment]
> Edit menu should NOT display "Tab" next to Emmet expansion unless it's actually ENABLED.

Not sure what that means. Can you show a screenshot?

> Playground says to enable using: "emmet.triggerExpansionOnTab". But the easier way is to click the "Emmet: Trigger Expansion On Tab" checkbox in settings.

@roblourens Do you mind updating that link in playground so it opens the new settings editor? I think for beginners the Settings UI is easier.

**Comment by roblourens** [comment]
It opens whichever settings editor you have configured as the default

**Comment by johnyradio** [comment]
Not just about link. Playground instructions text should mention settings
screen.

Please look at Edit menu. It says:
Emmet: Expand Abbreviation    Tab

**Comment by octref** [comment]
Yeah emmet on playground seems broken

![image](https://user-images.githubusercontent.com/4033249/54941547-5a8cc700-4eea-11e9-8f23-f7a344850bd4.png)

**Comment by chrmarti** [comment]
You need enable `"emmet.triggerExpansionOnTab"` for this to work.
