### ISSUE TITLE
Implementing Git Sync for Settings Sync

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#71022]
Hi, 

Settings Sync is looking forward to all one feature in future version on its extensions to implement similar `git` sync like `gist` sync.

Issue details are available at https://github.com/shanalikhan/code-settings-sync/issues/413
Issue bounty is about 200$ at the moment , which will be transferred once PR is accepted.

Just wanted to post here so you can tag this issue as `extension-candidate` or `feature-request` so any of the contributors who are willing to solve can go ahead to implement in my repo.

Thanks!

**Comment by shanalikhan** [comment]
@isidorn we can keep this open for some time.
What do you suggest?

**Comment by isidorn** [comment]
up to @joaomoreno he owns the git world. I would close it as we usually don't do advertise extensions like this.
