### ISSUE TITLE
Feature Request: Events on debug session status (stopped, running, etc.)

### ISSUE THREAD

**Issue by haneefdm** [Microsoft/vscode#71020]
I am trying to create an extension or enhance the existing vscode-cpptools extension to add register and memory views. Lots of requests for these features in the cpptools area. While I think I can create such views, I have an issue with refreshing them and knowing when to refresh them

We already have events for start/terminate/changed (vscode.debug.onDidXXXXDebugSession) but no events for when the debugger session status has changed -- stopped/running.

If such event emitters exist, then I can keep track of the current status but it would be nice to also know what the current status is. Current Status is not a must-have.

If you like I can make a proposal and see if I can implement it and submit for approval? 

Maybe there is already a way but I looked in the code/exported *.d.ts files and searched issues I saw nothing.

**Comment by haneefdm** [comment]
Just to show you I am serious, I managed to create a view in the debug viewlet/pane and show the register section. About 200 lines of code, not production ready. I am able to debug a native program on my mac (x64, lldb) and a board (ARM, gdb) attached to my mac. It is just that I have to manually trigger a refresh. In my code, I also have to guess the type of CPU I am dealing with on a session by session basis.

Please see the attached images. One with dark theme is native on my Mac. Light theme is program running on a ARM board attached to the same Mac via USB

<img width="831" alt="vscode" src="https://user-images.githubusercontent.com/41269583/54888879-6b8ff680-4e5e-11e9-9df2-b894a58e9da5.png">
<img width="379" alt="vscode-arm" src="https://user-images.githubusercontent.com/41269583/54888911-a5f99380-4e5e-11e9-80a2-583a6b302849.png">

**Comment by haneefdm** [comment]
Please visit https://github.com/haneefdm/adv-cppdbg to see my extension.

**Comment by haneefdm** [comment]
Hi guys, I have an update. I got a workaround suggested by https://github.com/gregg-miskelly

Greggs idea was to use `registerDebugAdapterTrackerFactory` API to snoop on all the traffic between the Debug Adapter and VSCode.

Pretty invasive (and ugly) but it works for what I need. Bit of a performance hit, I am sure. Anything going wrong in the snooper can make the debug session to go nuts/stop.

It seems like you can have only one tracker per adapter? What if some other extension wants to track as well?

Waiting for your thoughts. My latest (ugly) code is https://github.com/haneefdm/adv-cppdbg and I also have a vsix file on there

**Comment by weinand** [comment]
> "Anything going wrong in the snooper can make the debug session to go nuts/stop."
No, you cannot change anything from the tracker and exceptions are ignored.
You can register multiple trackers per DA.

**Comment by haneefdm** [comment]
Thanks, @weinand, I had a couple of instances where an exception in my code basically halted the debug session. Can't say what went wrong, pretty late into the night. I will watch out for it from now on and report.

Thanks for all your other clarifications.
