### ISSUE TITLE
Mouse pointer does not show as expand when area is small

### ISSUE THREAD

**Issue by sirmspencer** [Microsoft/vscode#71026]
- VSCode Version: 1.32.3
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Shrink terminal window or explorer to a very small state (about 5 lines or less for the terminal)
2. Move mouse the the line to expand
3. Pointer shows as normal instead of the expand/shrink arrow pointer.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/62320
