### ISSUE TITLE
Editor Action Format hotkey not working on some jsx markup

### ISSUE THREAD

**Issue by CrazyRyDmi** [Microsoft/vscode#7102]
- VSCode Version:1.1.1
- OS Version:Windows 8.1

Steps to Reproduce:

1. Create .tsx file with simple jsx template (one div element).
2. Add a text with double quotes and put inside it a some substitution (with braces).
3. Press shift+alt+f to perform a format action.

After that formatting will not work on any file of project until vsc restarted.

My example.tsx:
![image](https://cloud.githubusercontent.com/assets/8034149/15717614/d62dbcec-2838-11e6-8b07-81779741b6a0.png)

**Comment by dbaeumer** [comment]
Tracing this shows that the format request fails in the tsserver. Formatting a tsx file results in:

```
Sending request: format (4). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/ts/test.tsx",
    "line": 1,
    "offset": 1,
    "endLine": 3,
    "endOffset": 2
}

Response received: format (4). Request took 86 ms. Success: false . Message: Error processing request. Debug Failure. False expression: 
```

Formatting any other file afterwards results in 

```
Sending request: format (8). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/ts/m.ts",
    "line": 1,
    "offset": 1,
    "endLine": 3,
    "endOffset": 16
}

Response received: format (8). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure. False expression: 
```

as well. Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8933
