### ISSUE TITLE
python程序无法加载相对路径下的数据文件

### ISSUE THREAD

**Issue by suiahaw** [Microsoft/vscode#71030]
Issue Type: <b>Bug</b>

-   通过以下步骤运行的python将会出现bug

    `打开文件夹`-->`点击打开文件`-->`调试/在不调试的情况下启动` 

    如下

   
    ![image](https://user-images.githubusercontent.com/45323123/54876044-42fb0300-4e44-11e9-98ac-175c0ed18532.png)

    1.  红色圈出的为需要加载的数据文件

    ![image](https://user-images.githubusercontent.com/45323123/54876054-59a15a00-4e44-11e9-96eb-522da6f7ce87.png)

    2.  python程序中引用此数据文件的相对路径代码

    ![image](https://user-images.githubusercontent.com/45323123/54876063-69b93980-4e44-11e9-951b-f3b381638c56.png)

    3.  此为错误信息

    ![image](https://user-images.githubusercontent.com/45323123/54876066-7a69af80-4e44-11e9-90c1-9b9720370fe7.png)

-   然而直接打开python文件则可正常运行

    ![image](https://user-images.githubusercontent.com/45323123/54876077-9705e780-4e44-11e9-8645-e65d87f46c69.png)

-   猜测原因:

    可能是由于在"文件夹"打开文件时,文件会被临时存储在系统临时目录中. 导致无法通过相对路径来加载文件. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (2.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-faker|dee|1.3.0
gitlens|eam|9.5.1
vscode-language-pack-zh-hans|MS-|1.32.4
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.2.5558
vscode-yaml|red|0.3.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by suiahaw** [comment]
Unable to load data files in relative path when compiling and running python program

（PS. My English is very bad, please forgive me for using Chinese in question.）

**Comment by Tyriar** [comment]
This looks like either a problem with the python extension https://github.com/Microsoft/vscode-python or a programming error on your side?

**Comment by suiahaw** [comment]
Thanks！But, I found this to be a design issue for vscode. In vscode, the relative path starts from the directory where ".vscode" is located, and Python starts from the directory where the current ".py" file is located. Then I solved this problem caused by the operating habit by modifying the "launch.json" file.

**Comment by Tyriar** [comment]
I think the python extension drives what the links do

**Comment by suiahaw** [comment]
I think this is a problem caused by the different habits of the relative path. However, the python plugin does not handle this problem well. So I don't know which section should continue to submit this feedback.

**Comment by Tyriar** [comment]
-> https://github.com/Microsoft/vscode-python
