### ISSUE TITLE
wrong auto import when exist tow options.

### ISSUE THREAD

**Issue by yantrab** [Microsoft/vscode#71031]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create export class in root folder.
2. Create another export that export previews one, in some nested project.
3. Start hit the name of the class, and auto import it.
4. Instead of import from nested  folder, it import from the root.

In[ my Project,](https://github.com/yantrab/nest-angular) , for example,  in `client\src\app\app1\poly\poly.component.ts` if i trying to import `FilterGroup`, instead of import from 'shared', it import from  `'../../../../../shared';`

Does this issue occur when all extensions are disabled?:Only TSLINT.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
