### ISSUE TITLE
[ Crash ] - Extension Host Terminated Unexpectedly - extensionService terminated.

### ISSUE THREAD

**Issue by SirTwsted** [Microsoft/vscode#71036]
[ Crash ] - Extension Host Terminated Unexpectedly - extensionService terminated.

VS Code crashed 4 times so far.

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Switch language from python to Java to Javascript 
2. it spontaneously happens, i dont know how exactly how , it just happens doing different things.

.
![Screenshot_18](https://user-images.githubusercontent.com/15247713/54879280-969e2a00-4e0d-11e9-9367-d220cbac9fc5.png)

**Comment by SirTwsted** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/15247713/54880349-1fbb5e00-4e1a-11e9-9333-ced455fb1b12.png)

**Comment by SirTwsted** [comment]
Ok, this is starting to be very very annoying now.
This problem started happening last night when I updated VS Code from v1.32.2 to v1.32.3
My memory is getting chewed up and my CPU is going nuts pinging at 90
And constant crash with this error popup.  I think You guys broke something.
.
![Screenshot_23](https://user-images.githubusercontent.com/15247713/54882523-4769f080-4e31-11e9-87e5-fbdab2897495.png)

**Comment by SirTwsted** [comment]
VS Code v1.32.3

I just got this just now - complete black out screen crash.  You guys definitely broke something....lol
.
![Screenshot_24](https://user-images.githubusercontent.com/15247713/54882569-bc3d2a80-4e31-11e9-8614-d5efb2936dfc.png)

**Comment by alexandrudima** [comment]
@SirTwsted Does this reproduce when disabling all extensions?
