### ISSUE TITLE
Add ctrl+` / cmd+` keyboard shortcut for cycling to next tab

### ISSUE THREAD

**Issue by grantalewis** [Microsoft/vscode#71035]
Please add ctrl+` (PC) / cmd+` (Mac) keyboard shortcut for cycling to next tab.

**Comment by onlineservices283418** [comment]
Ctrl+Tab does the job.

**Comment by grantalewis** [comment]
The key sequence I was trying to type was altered. What I intended to suggest:

```
CTRL + ` 
CMD +`
```

You're right that CTRL+TAB or CMD+TAB work -- thank you for mentioning that. It would be nice, however, if Visual Studio Code were consistent with other Microsoft applications on Mac and used the  keys I suggest.

**Comment by bpasero** [comment]
Keybindings are configurable.
