### ISSUE TITLE
Typescript file keeps on showing as changed

### ISSUE THREAD

**Issue by dylanvdmerwe** [Microsoft/vscode#71032]
Issue Type: <b>Bug</b>

I have enabled save on focus change as well as format on save, but the file is always showing that there are changes whenever the window's focus changes. Even though there are no changes, the file always shows that it needs to be saved on focus change. 

This is specifically for .ts files. Html and .scss files do not show this behaviour. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-npm-script|eg2|0.3.5
auto-rename-tag|for|0.0.15
vscode-peacock|joh|1.3.1
code-spell-checker|str|1.6.10
vscodeintellicode|Vis|1.1.4

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by dylanvdmerwe** [comment]
See below which helps illustrate the problem. TypeScript files have a problem saving. 

Nothing has changed in the .ts file, but it keeps saying something has changed. I think it has to do with the format on save.

![ts save problem](https://user-images.githubusercontent.com/2852839/55292121-15373080-53e7-11e9-9227-87b0a8b5ff0d.gif)

My settings:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.formatOnSave": true,
    "files.autoSave": "onWindowChange",
    "git.confirmSync": false,
    "typescript.implementationsCodeLens.enabled": true,
    "typescript.referencesCodeLens.enabled": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.suggestSelection": "first",
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "extensions.ignoreRecommendations": true,
    "cSpell.userWords": [
        "choropleth"
    ],
    "peacock.favoriteColors": [
        {
            "name": "Angular Red",
            "value": "#b52e31"
        },
        {
            "name": "Auth0 Orange",
            "value": "#eb5424"
        },
        {
            "name": "Azure Blue",
            "value": "#007fff"
        },
        {
            "name": "Gatsby Purple",
            "value": "#639"
        },
        {
            "name": "JavaScript Yellow",
            "value": "#f9e64f"
        },
        {
            "name": "Mandalorian Blue",
            "value": "#1857a4"
        },
        {
            "name": "Node Green",
            "value": "#215732"
        },
        {
            "name": "React Blue",
            "value": "#00b3e6"
        },
        {
            "name": "Something Different",
            "value": "#832561"
        },
        {
            "name": "Vue Green",
            "value": "#42b883"
        }
    ]
}
```

Have not tried with insiders build as yet.

**Comment by mjbvz** [comment]
Try in insiders with extensions disabled

**Comment by dylanvdmerwe** [comment]
Looks much better in the latest version (1.33.0).

**Comment by dylanvdmerwe** [comment]
This still occurs in the latest version of VS Code (1.33.0). Closing and opening the editor keeps things happy for a little while, but then it goes right back to thinking TS files are changed when they are not .

**Comment by mjbvz** [comment]
Have you tried with all extensions disabled to see if one of them is causing this?
