### ISSUE TITLE
Edited but unsaved content appears in the "Search in Folders" result

### ISSUE THREAD

**Issue by GFwer** [microsoft/vscode#71037]
- VSCode Version:1.32.3
- OS Version: MacOS 10.14.3

This problem also exists in the insiders version.

Steps to Reproduce:

folder like this:

```
- FolderA
 - body.js
- FolderB
```

body1.js like this:
```
content
```

1. Right-click FolderB and select "Search in Folders"
2. Delete 'content' in body.js and don't save the file(now body.js is empty but not save)
3. Right-click FolderA and select "Search in Folders" and search "content",the result like this picture

![image](https://user-images.githubusercontent.com/14303098/54881153-f5a08500-4e87-11e9-96a1-f0c9631e9392.png)

Remarks: After this result, I just try to type in the body.js file and the result will disappear

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I don't understand the issue. Does search.js have a result or not?

**Comment by GFwer** [comment]
@roblourens no, search.js is empty now, It should not appear in search results,but it shows “1 file 0 result” in result list

**Comment by roblourens** [comment]
Now I see, thanks.

The problem is here, this line needs to look at the include pattern/file relative to the folder being searched: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/common/search.ts#L362

**Comment by skprabhanjan** [comment]
@roblourens , Can i work on this ?
If yes then some info on how to do this also please :)

**Comment by roblourens** [comment]
I don't think it will be straightforward, thanks though @skprabhanjan
