### ISSUE TITLE
Huge CPU consumption when using vscode

### ISSUE THREAD

**Issue by dodgers** [Microsoft/vscode#71045]
Issue Type: <b>Performance Issue</b>

One process (Microsoft.python.LanguageServer)  consumes more than 100% cpu utilization permanently
I have no file open , only many folders in my workspace. 

I tried to remove  some plugins but the issue still persist

Regards

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|11.19GB (2.95GB free)|
|Process Argv|--open-url|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   137	 29343	code main
    0	    34	 29347	   zygote
    0	   321	 29393	     window (workspace - Visual Studio Code)
    0	     0	 29536	       /bin/bash
    0	   378	 29585	       extensionHost
    0	    92	 29687	         /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=29585
    0	    57	 29688	         electron_node dbaeumer.js server.js 
    0	    69	 31290	         electron_node server.js 
    0	    57	 31311	         electron_node server.js 
    0	   756	 29650	       watcherService
    0	    57	 29668	       searchService
    0	   137	 29998	     shared-process
    0	   103	 32404	     window (Issue Reporter)
    0	   115	 29379	   gpu-process
    0	     0	 32430	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 32431	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (workspace - Visual Studio Code)
|    Folder (workspace): more than 31145 files
|      File types: go(7433) py(4261) yaml(2986) md(1886) txt(1566) yml(983)
|                  xml(790) jar(739) html(598) sh(585)
|      Conf files: makefile(123) package.json(20) settings.json(13)
|                  grunt.js(5) launch.json(4)
|      Launch Configs: python(13) go;
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
toml|be5|0.0.3
solargraph|cas|0.19.3
vscode-eslint|dba|1.8.2
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.4.11
kubernetes-snippets|ipe|0.1.9
ldif|jta|0.1.1
vscode-azureterraform|ms-|0.2.3
vscode-kubernetes-tools|ms-|0.1.18
python|ms-|2019.2.5558
azure-account|ms-|0.8.0
cpptools|ms-|0.22.1
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.6.1
ruby|reb|0.22.3
java|red|0.41.0
vscode-yaml|red|0.3.0
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
jinja|who|0.0.8

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
