### ISSUE TITLE
Test webview port mapping api

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#71049]
Test for #70851

- [x] Mac @bpasero
- [x] Linux @RMacfarlane
- [x] Windows @alexr00

Complexity: 4

**Summary**
The new webview port mapping api allows an extension to remap ports from localhost inside a webview. See #70851 and the proposed api documentation for api details

**Testing**
Using the [webview api sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample), test that port mappings you define as an extension are observed properly in the webview extension. For example:

1. Define a port mapping from 3000 to 4000 in the cat coding extension
1. Modify the cat coding html to load an image or other resource from localhost 3000
1. On your machine, start a server running port 4000 that serves up the image
1. Start the cat coding extension and verify that its webview transparently redirects content from localhost:3000 to the server running at localhost:4000

**Comment by bpasero** [comment]
I verified this by embedding a `<img src="https://localhost:80/foo.png"/>` into the content of the webview, configuring the option `portMapping: [{ port: 80, resolvedPort: 4000 }]` and checking the webview developer tools for making a request to `https://localhost:4000/foo.png`

**Comment by alexr00** [comment]
Verified by embedding a `<img src="http://localhost:3000/cat.gif">` into the content of the webview and configuring the port mapping: `portMapping: [{port:3000, resolvedPort:4000}]`. Confirmed in the webview developer tools (didn't know that was a thing) that the port resolved correctly.

**Comment by RMacfarlane** [comment]
Port mapping worked well, did run into https://github.com/Microsoft/vscode/issues/71107 while using the webview sample
