### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by investigator1092** [Microsoft/vscode#71040]
Issue Type: <b>Bug</b>

my PC got more than 15GB of memory using and smoked, sparked, vibrated, warped, disappeared

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (11.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vandelay-py|edb|1.2.0
MagicPython|mag|1.1.0
vscode-language-pack-ja|MS-|1.32.4
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.2.5558
open-html-in-browser|pea|1.0.4
vscode-yaml|red|0.3.0
vscodeintellicode|Vis|1.1.4

</details>

**Comment by isidorn** [comment]
Follow this steps to file a good issue please 
https://github.com/Microsoft/vscode/wiki/Performance-Issues
Thanks

**Comment by weinand** [comment]
no actionable information -> closing.
