### ISSUE TITLE
Starting on black screen.

### ISSUE THREAD

**Issue by KingWaffleIII** [microsoft/vscode#71044]
This is similar to other black screen problems however none of them fix my problem. Here's what I get:
![image](https://user-images.githubusercontent.com/43790097/54885025-73a46200-4e6f-11e9-94e1-5aa798acd578.png)
I've tried running it with "code --disable-gpu" but that doesn't work. Please help, I can't code without it. Sublime doesn't do it for me.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by KingWaffleIII** [comment]
Is there a way to still use the normal VSCode? (I've tried reinstalling it but it comes to no avail).

**Comment by bpasero** [comment]
Did you try https://github.com/Microsoft/vscode/issues/71044#issuecomment-476136915 ?

**Comment by KingWaffleIII** [comment]
Yeah it works fine but I'm not too sure with using a pre-alpha build of VSCode.

**Comment by grandao** [comment]
I have the same problem after updating vscode. Tried the --disable-gpu but id did not work. I also tried  the app.disableHardwareAcceleration(); hack but to no avail.
$ code --version
1.35.0
553cfb2c2205db5f15f3ee8395bbd5cf066d357d
x64
$ uname -a
Linux fields 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abeburnett** [comment]
The black screen issue just appeared for me. I don't _start_ with the black screen, but it just suddenly happened as I was working happily. Help!

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
