### ISSUE TITLE
Foldable <details> section in Markdown

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#71043]
I'd like to be able to fold `<details>` sections in Markdown, for example

```md
<details><summary>Log output</summary>

Some long content here...

</details>
```

A similar request was #57505 which was resolved by commit https://github.com/Microsoft/vscode/commit/a118676a3b73c8972d76e5e854496fc4901dcd75 ("Allow folding of html blocks in markdown files") but I don't see this behavior in 1.33.0:

<img width="375" alt="Screenshot 2019-03-24 at 19 36 24" src="https://user-images.githubusercontent.com/101152/54884025-2a9ede80-4e6c-11e9-8fd5-1fb6f5489eca.png">

(Note how the fenced code block is foldable but not the entire `<details>` element.)

**Comment by mjbvz** [comment]
Not easy to fix with current markdown engine (markdown-it). It gives us a flat list of tokens, but as far as I know it does not check if an html block is open or closed. This makes matching the opening `<details>` to the closing `</details>` difficult to do correctly 

Here's the folding code if anything wants to try taking a look: https://github.com/microsoft/vscode/blob/0ec326531e30fb27fb6fdc735b6cc5938399940b/extensions/markdown-language-features/src/features/foldingProvider.ts#L14

**Comment by PEZ** [comment]
Another use case for this would be to support presenting data structures, like I ask for in this issue: https://github.com/microsoft/vscode/issues/81313

**Comment by intellekta** [comment]
I think it is very important for a software documentation in Markdown, which is structured with "details" for an HTML export.

After my test, the folding works without a blank line after details.
~~~
| 1 | V | <details><summary>foldme</ summary>
| 2 |   | - something
| 3 |   | </ details>
~~~
But that does not work with an HTML export.
The necessary blank line after details breaks folding in VSCODE
~~~
| 4 |   |
| 5 |   | <details><summray>foldme</ summary>
| 6 |   |
| 7 |   | - something
| 8 |   | </ details> 
~~~
