### ISSUE TITLE
March 2019 Endgame

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#71059]
This is the endgame schedule for [March 2019 Iteration](https://github.com/Microsoft/vscode/issues/70102).

## Schedule

- End game master: @weinand / Zurich
- End game buddy: @octref / Redmond
- 03/25 Code freeze for the endgame
- 03/29 [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- 04/04 Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday 03/25
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/README.md) **@weinand**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at **5pm PT**
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain test meta data by **5pm PT** and sufficiently comprehensive test descriptions by 8am CET
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday 03/26
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

##### Wednesday 03/27
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22March+2019%22+)

##### Thursday 03/28
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22March+2019%22+)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/README.md) and pass list of changed OSS usage (https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/license/third_party_1.nn.0_diff.txt) to @isidorn for verification **@weinand**

##### Friday 03/29
- [x] Pause scheduled `insider` builds **@weinand**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
- [x] All issues [verified](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22March+2019%22+)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - @dbaeumer 
  - [x] OS X - @alexandrudima 
  - [x] Linux - @aeschli 
- [ ] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). ⚠️We are now doing release notes via **Git LFS**. Please read what this means here: https://github.com/Microsoft/vscode-docs/blob/vnext/README.md#git-lfs-setup⚠️
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [ ] @rebornix
  - [x] @rmacfarlane
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **@weinand**
  - [x] vscode-node-debug **@weinand**
  - [ ] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [ ] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [ ] vscode-recipes **@auchenberg**
  - [x] localization **@shawndon**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **@weinand**
- [x] Acknowledge issue trackers from the community **@chrmarti**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@weinand**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **@weinand**
- [x] Bump up the version in package.json - **@weinand**
- [x] Announce master is open for business **@weinand**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@weinand**
- [x] Build `Insider` from `release/<x.y>` **@weinand**
- [x] Manually release `Insider` **@weinand**
- [x] Build stable for all platforms as new candidate issues come in **@weinand**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [ ] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [ ] @rebornix
  - [x] @rmacfarlane
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @sbatten
  - [ ] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [x] Build stable for all platforms **@weinand**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@RMacfarlane**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit @roblourens  
    - [x] signed installer 64-bit @octref 
    - [x] signed user installer 32-bit @roblourens  
    - [x] signed user installer 64-bit @octref 
    - [x] zip 32-bit @roblourens  
    - [x] zip 64-bit @octref 
  - [x] OS X - @octref 
  - [x] Linux
    - [x] deb package 32-bit @RMacfarlane 
    - [x] deb package 64-bit @sbatten
    - [x] rpm package 64-bit @RMacfarlane 
    - [x] rpm package 32-bit @RMacfarlane 
    - [x] archive 32-bit @RMacfarlane 
	- [x] archive 64-bit @RMacfarlane
- [x] Publish website **@gregvanl**
- [x] Publish Localization language pack **@shawndon**
- [x] Publish to stable **@weinand**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **@weinand**
- [x] Publish `@types/vscode@<x.y>` @octref 
- [x] Publish rpm to repository manually **@RMacfarlane**
- [x] Enable scheduled `insider` builds **@weinand**
- [x] Twitter announcement **@auchenberg**

**Comment by dzienisz** [comment]
What is happening with the last two releases, both are delayed?

**Comment by weinand** [comment]
@dzienisz no, we are always shipping the release in the week after the endgame. 
You can always find the expected release date in the first comment of the endgame (above).

> 04/04 Expected release date (this may change)

**Comment by weinand** [comment]
March released shipped!

**Comment by dzienisz** [comment]
@weinand thanks for the answer!
