### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by doribd** [Microsoft/vscode#71056]
Issue Type: <b>Bug</b>

keyboard stopped working in the editor. 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
xml|Dot|2.4.0
prettier-vscode|esb|1.8.1
code-runner|for|0.9.7
terminal|for|0.0.10
rest-client|hum|0.21.2
vscode-github|Kni|0.30.1
prettify-json|moh|0.0.3
python|ms-|2019.2.5558
Go|ms-|0.9.2
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.6.1
vscode-spring-boot|Piv|1.4.0
java|red|0.41.0
vscode-yaml|red|0.3.0
bash-debug|rog|0.3.4
vscode-java-debug|vsc|0.17.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
vscode-spring-initializr|vsc|0.4.5
vim|vsc|1.2.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by isidorn** [comment]
Works for me.
Can you repro with vscode insiders https://code.visualstudio.com/insiders/

**Comment by weinand** [comment]
on reply -> closing.

**Comment by doribd** [comment]
unable to reproduce
