### ISSUE TITLE
Install extension ranking is bad

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7105]
It's sorting the partial matches by install count, regardless of relevance.

![image](https://cloud.githubusercontent.com/assets/2193314/15721640/ba846ecc-27ee-11e6-997f-264a4b74d1a4.png)

**Comment by Tyriar** [comment]
This is also harmful imo as lesser known niche extensions will never get installed unless they're found via browsing the web interface.

**Comment by rebornix** [comment]
+1, the only way to get more audience for now is more downloads, which makes extensions less detectable.

Speaking of relevance, do we need to implement some special alogrithm to define `relevance`? For instance, when people search for php extensions, a debugger+intellisense extensions is more relevant than a theming extension, regardless of the name.

**Comment by joaomoreno** [comment]
The marketplace has implemented a relevance sort order. We can jump onto it. Here are some query results, for reference:

![screen shot 2016-06-02 at 09 53 02](https://cloud.githubusercontent.com/assets/22350/15737727/ec469462-28a7-11e6-9519-efe982668337.png)

![screen shot 2016-06-02 at 09 53 11](https://cloud.githubusercontent.com/assets/22350/15737729/ec48176a-28a7-11e6-8cdb-f2523978469b.png)

![screen shot 2016-06-02 at 09 53 21](https://cloud.githubusercontent.com/assets/22350/15737728/ec47d85e-28a7-11e6-9761-22f4a490ab89.png)

You can get the same results by [running a search](https://marketplace.visualstudio.com/search?term=c&target=VSCode&sortBy=Relevance) in the marketplace page.

**Comment by alefragnani** [comment]
What about _expanding_ the `Install Extension` command, creating commands for each _Category_? 

This way, the user could search specifically for `Themes`, `Languages`, `Debuggers`, etc, and its category could be applied as the first filter, regardles the relevance criteria that already exists.

**Comment by Tyriar** [comment]
I think this should be dealt with sooner rather than later, right now the installation advice given on the marketplace is wrong because of this. Consider https://marketplace.visualstudio.com/items?itemName=AdamCaviness.theme-monokai-dark-soda

![image](https://cloud.githubusercontent.com/assets/2193314/15854362/41815188-2c5e-11e6-9a60-8406e0822ac7.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15854373/54d8a0b0-2c5e-11e6-8826-e148b0f19a6e.png)

**Comment by joaomoreno** [comment]
Oh that's a much worse problem!

**Comment by joaomoreno** [comment]
Verification: search for extensions, they should not be sorted by download count.
