### ISSUE TITLE
Ignoring .gitignore

### ISSUE THREAD

**Issue by ekkis** [Microsoft/vscode#71054]
Issue Type: <b>Bug</b>

I have a file called `.url` which I have included in my `.gitignore`.  however, any time this file changes, it appears in the source control listing with an M (modified) and expects to be committed.  the file should be ignored and should not appear in the list

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.3.0
vscode-wasm|dts|1.2.1
githd|hui|2.1.0
composer-support-client|Hyp|0.19.12
vscode-github|Kni|0.30.1
cpptools|ms-|0.22.1
vsliveshare|ms-|0.3.1326
debugger-for-chrome|msj|4.11.3
typescript-hero|rbb|3.0.0
cmake|twx|0.0.17
sort-lines|Tyr|1.8.0
cmake-tools|vec|1.1.3

</details>

**Comment by joaomoreno** [comment]
https://stackoverflow.com/a/9750651/261019

**Comment by ekkis** [comment]
I see.  so this isn't a VSCode problem at all.  thanks for pointing me in the right direction!
