### ISSUE TITLE
EOL focus changed to `LF` after Extensions change content

### ISSUE THREAD

**Issue by zheung** [Microsoft/vscode#71057]
- VSCode Version: 1.33.0-insider
- OS Version: Windows 10 1809
- Commit: 5688d00dd592a165530a82945c4ade4dad6b01e7
- Date: 2019-03-25T06:19:55.474Z
- OS: Windows_NT x64 10.0.17763

Problem:
My current EOL is `CRLF`.
After use any Extension to change content, EOL focus changed to `LF`.

Steps to Reproduce:
Use any extension to change content, like this:
- with Extension `Beautify css/sass/scss/less`
![BS](https://user-images.githubusercontent.com/894004/54908656-634dbf00-4f23-11e9-85f4-1c0ea0a90e07.gif)
- with Extension `Insert Date String`
![IDS](https://user-images.githubusercontent.com/894004/54908679-69dc3680-4f23-11e9-8649-a9e650514ef6.gif)
- with Exension ` NumberMonger`
![NM](https://user-images.githubusercontent.com/894004/54908683-6ba5fa00-4f23-11e9-8f66-86a527245eac.gif)

Does this issue occur when all extensions are disabled?: Yes/No
No, but occur any extensions with change content

**Comment by alexandrudima** [comment]
@zheung One of your extensions is editing the text document and changing the EOL. I don't know which one it is, you have not shared the list of installed extensions. You would need to try to reproduce with extensions disabled.

**Comment by zheung** [comment]
@alexandrudima 
I mean, **ALL** extensions will change the EOL, if they edit something.

Look at this gif↓
I reset Code and just installed 3 extensions:
- `Beautify css/sass/scss/less` format css AND **change the EOL**
- `Insert Date String` insert a date AND **change the EOL**
- `code-eol` to show the EOL

![DM](https://user-images.githubusercontent.com/894004/55146191-0f3f1680-517f-11e9-97f2-0f8f1ab4996d.gif)

**Comment by alexandrudima** [comment]
@zheung have you tried to uninstall/disable `code-eol`? I cannot reproduce with `Insert Date String`

**Comment by alexandrudima** [comment]
Introduced via cfd4cb8c8111b04e7831f2214fd41be8d0532555

The bug is on this line https://github.com/Microsoft/vscode/blob/292e59f3678ef0b9a6c7d920cd00abf9c26c8ccc/src/vs/workbench/api/node/extHostTextEditor.ts#L610

**Comment by jrieken** [comment]
Well, exposed via cfd4cb8 the weird thing is that an enum type can be assigned with "outside" values, e.g. like this. `EndOfLine` can be `1` or `2` but not `0` or any other number. However, for TypeScript that doesn't seem to be an issue.

<img width="846" alt="Screenshot 2019-03-28 at 12 41 53" src="https://user-images.githubusercontent.com/1794099/55155323-55807f80-5157-11e9-8bfa-4206351efe70.png">
