### ISSUE TITLE
Unicode symbols not work

### ISSUE THREAD

**Issue by SupinePandora43** [Microsoft/vscode#71053]
- VSCode Version: 1.32.3 (user setup)
- OS Version: Windows 7 x32

i see missing symbol icon instead red cross when java test failed. also in code time: instead bomb i see missing symbol

**Comment by SupinePandora43** [comment]
@isidorn it caused not by extension

**Comment by isidorn** [comment]
I think it is. Becuase we do not have red crosses and we do not support java tests in vscode. That is contributed by extensions

**Comment by SupinePandora43** [comment]
yes, but. i can't see icon font/unicode in vscode window

**Comment by SupinePandora43** [comment]
@isidorn  this issue can be duplicate of #31366 , but i have issue on windows, and in editor window (not in editor)

**Comment by isidorn** [comment]
Aha, so you have a font rendering problem. Sorry I misunderstood, reopening and forwarding.

**Comment by alexandrudima** [comment]
AFAIK Windows 7 does not have fonts with all the new fancy icons, so I don't see how we're going to fix this... Did you try installing some newer system fonts?

**Comment by SupinePandora43** [comment]
@alexandrudima thank you!
![Thanks](https://user-images.githubusercontent.com/36124472/55144077-dfcde100-5161-11e9-91cb-9613cab8e772.PNG)
fix: https://support.microsoft.com/ru-ru/help/2729094/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-ser    or    https://support.microsoft.com/en-us/help/2729094/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-ser
