### ISSUE TITLE
System hang up on dual screen with T480

### ISSUE THREAD

**Issue by ajay127** [Microsoft/vscode#71051]
Issue Type: <b>Bug</b>

When run vcode for about 2 hours, it will hangup the system on my notebook.

It is the same without runing with extension.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.61GB (3.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.3.0
ctags-support|jay|1.0.19
python|ms-|2019.2.5558
cpptools|ms-|0.22.1
devicetree|plo|0.1.1

</details>

**Comment by Tyriar** [comment]
What do you mean by hangup?
