### ISSUE TITLE
[Insider Build] "Folder Symbolic Links" appear as "Files" and cannot be opened

### ISSUE THREAD

**Issue by thaoula** [Microsoft/vscode#71055]
- VSCode Version: Latest Insider Version
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Create a folder and open in VScode
2. Create a symbolic link to another "Folder" inside folder created in step 1. 
3. VS code will display the link as File rather than a folder. 

In the insider build you will get the following error - 

![image](https://user-images.githubusercontent.com/349133/54901096-0d1f5280-4f08-11e9-953e-c6fd9ef9b446.png)

![image](https://user-images.githubusercontent.com/349133/54900977-bdd92200-4f07-11e9-9dfa-8b04c3d00d68.png)

This appears to have been broken recently. Possibly in the last 2-3 insider builders. Opening the same folder using non insider build will display the symbolic link as folder and you can browse inside it like a normal folder.

![image](https://user-images.githubusercontent.com/349133/54901188-48218600-4f08-11e9-9a7e-2f8991d3eadd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Sounds like a change in the file service, forwarding to @bpasero

**Comment by maanlamp** [comment]
To add to this: I am also unable to open my symbolic link project folder as a workspace since updating to the last version of insiders (1.33.0).

It seems every way of loading/using symbolic links is broken.

**Comment by bpasero** [comment]
@jrieken the idea of FileType is that I can have `FileType.SymbolicLink | FileType.Directory` so that I can signal both types right?

**Comment by bpasero** [comment]
fixed via https://github.com/Microsoft/vscode/commit/480d54b54698d9f7600bcd1176db87063b2a841d

**Comment by jrieken** [comment]
Yeah, `FileType` is a bitmash

**Comment by thaoula** [comment]
Thanks for the fast fix @bpasero .. Got the latest nightly and it works 👍
