### ISSUE TITLE
Symlinked directory not traversable in explorer

### ISSUE THREAD

**Issue by leemhenson** [Microsoft/vscode#71064]
- VSCode Version: Version 1.33.0-insider
- OS Version: MacOS 10.14.3

Steps to Reproduce:

1. `cd /tmp/`
2. `mkdir symlink-test`
3. `mkdir symlink-test-2`
4. `echo "foo" > ./symlink-test-2/foo.md`
5. `cd symlink-test`
6. `ln -s ../symlink-test-2 ./symlink-test-2`
7. `code -n .`

The entry in the explorer for `symlink-test-2` is not usable. In the non-insiders build it can be expanded to view the `foo.md` file inside.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of 71055
