### ISSUE TITLE
Test: hierarchical debug sessions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#71063]
Refs: https://github.com/Microsoft/vscode/issues/70695

- [x] windows @jrieken
- [ ] macOS @misolori

Complexity: 3

Authors: @weinand, @isidorn 

In this milestone we have added support to optionally display debug sessions as a tree in the debugger UI. Previously debug session were displayed as flat lists.

This functionality is only available through the extension API as an additional "parent" parameter to the `vscode.debug.startDebugging()` API. 

Currently this feature is only used in two places:
- In node.js cluster debugging all subprocesses of the cluster are registered under the main debug session.
- in the "server-ready feature" an automatically launched Chrome browser session is registered as a child of the server debug session.

If you do not want to create an extension that makes use of the new API, you can test this feature more easily either by using a cluster sample (see https://github.com/Microsoft/vscode/issues/40123#issue-281453170) or the "server-ready feature" (https://github.com/Microsoft/vscode/issues/69313#issue-413841502).

Start debugging and verify:
* sub-sessions are shown in the call stack view as children of their parent session.
* the parent should expand automatically if a child is added. 
* in the dropdown menu in the debug toolbar sub-sessions appear indented under its parent but the parent cannot be collapsed or expanded.
* a terminated sub-session disappears under its parent.
* context menu actions related to debug sessions should behave like before (as there was no change in behavior in the actions).

Please note: the launch config attribute to enable automatic child processes is "autoAttachChildProcesses".

**Comment by jrieken** [comment]
@weinand Like the other debugging issue, nothing happens when pressing F5, showing progress forever. Using this sample: https://github.com/Microsoft/vscode/issues/40123#issue-281453170 on a windows vm

**Comment by isidorn** [comment]
Running the sample on a win vm works for me.
Here's my `launch.json`

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Cluster",
            "program": "${workspaceFolder}/test.js",
            "autoAttachChildProcesses": true
        },
    ]
}
```

And here's my test.js

```javascript
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length;

if (cluster.isMaster) {
	console.log(`Master ${process.pid} is running`);

	// Fork workers.
	for (let i = 0; i < numCPUs; i++) {
		cluster.fork();
	}

	cluster.on('exit', (worker, code, signal) => {
		console.log(`worker ${worker.process.pid} died`);
	});
} else {
	// Workers can share any TCP connection
	// In this case it is an HTTP server
	http.createServer((req, res) => {
		res.writeHead(200);
		res.end('hello world\n');
	}).listen(8000);

	console.log(`Worker ${process.pid} started`);
}
```

@jrieken running just a simple node javascript sample works fine?

![Screenshot 2019-03-26 at 15 23 02](https://user-images.githubusercontent.com/1926584/55004819-3230c580-4fdb-11e9-861e-a55b1b142700.png)

**Comment by jrieken** [comment]
It's flaky (like often unfortunately) and while after a couple of restarts it now starts the debuggee, breakpoints aren't hit. Using your config from above (and not the "node.js >= v8" one from https://github.com/Microsoft/vscode/issues/40123#issue-281453170) makes this work, at least most breakpoints are verified and hit.

**Comment by misolori** [comment]
FWIW, I was able to get this work on macOS with the same sample as @isidorn 

<img width="771" alt="image" src="https://user-images.githubusercontent.com/35271042/55036708-aae25280-4fd8-11e9-93e4-59ac2c5701ee.png">

**Comment by misolori** [comment]
Ran into all of the same issues as @jrieken. I think the only way for this to be usable is if #71206 and #71183 are fixed.

**Comment by isidorn** [comment]
Thanks a lot for testing and for providing feedback. I have fixed most of the issues on the vscode side.
There is still one which Joh filled which could contain some deeper problems, for that we would also need to investigate on the backend side https://github.com/Microsoft/vscode/issues/71201
