### ISSUE TITLE
Duplicate lines in terminal

### ISSUE THREAD

**Issue by Yogeeshvh** [Microsoft/vscode#71069]
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

Getting duplicate log lines  (for pm2 ) in terminal, few minutes after it gets loaded. Problem appears after resizing terminal window for few times. Over the time number of duplicate lines increases, sometime reaches 6-8.

![image](https://user-images.githubusercontent.com/12169410/54917898-d73b9780-4f22-11e9-9dea-224599bbe4af.png)

Steps to Reproduce:

1. Load terminal with above configurations
2. Run an application which produces logs
3. Resize terminal window for few times

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Please update vscode

**Comment by Yogeeshvh** [comment]
Updated it, Issue still exist on new version

**Comment by Tyriar** [comment]
Can you do a screen recording showing the good state, then the resize into the bad state? I can't reproduce here.
