### ISSUE TITLE
Marketplace is bad at detecting licenses

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7106]
Prime examples:

- https://marketplace.visualstudio.com/items/donjayamanne.python/license
- https://marketplace.visualstudio.com/items/donjayamanne.javadebugger/license

It seems to do with non-SPDX identifiers in the license field of package.json, however when a valid SPDX identifier exists [it just dumps](https://marketplace.visualstudio.com/items/Tyriar.sort-lines/license) the [contents of `LICENSE`](https://github.com/Tyriar/vscode-sort-lines/blob/master/LICENSE) on the webpage. Why not just always do that...?

**Comment by joaomoreno** [comment]
This was fixed in Microsoft/vscode-vsce#66. Extension developers need to update to the latest vsce.

**Comment by joaomoreno** [comment]
Created DonJayamanne/pythonVSCode#145

**Comment by joaomoreno** [comment]
Created DonJayamanne/javaVSCode#5
