### ISSUE TITLE
About "ipch"

### ISSUE THREAD

**Issue by GuanyunLu** [Microsoft/vscode#71061]
Issue Type: <b>Bug</b>

I use VSCode for practicing algorithm contest, but nowadays when I compile .cpp files, there' ll be a ipch folder costing much disk space. I wish you could fix that problem.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.90GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|0.5.0
cpptools|ms-|0.22.1
vscode-icons|vsc|8.4.0

(1 theme extensions excluded)

</details>

**Comment by tehKaiN** [comment]
related to https://github.com/Microsoft/vscode-cpptools/issues/3347
