### ISSUE TITLE
Integrated terminal needs to be closed in memory not just visually.

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/vscode#7107]
- VSCode Version: 1.2.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open the integrated terminal
2. Run "ng serve" which starts a process
3. Close the terminal by clicking on the right-top X
4. Open terminal again 
5. Everything is like before, I can **NOT** enter anything in the terminal.
6. How am I assumed to cancel the current process to enter something new like ng build, ng test, or any other tool?
6.5 At the moment I have always to restart vscode :/
7. WebStorm has a red square button for that feature :-)

**Comment by Tyriar** [comment]
Do you mean you want to run multiple processes at once? #6458 will probably solve this.

**Comment by bastienJS** [comment]
@Tyriar I thought about this issue again. Actually its enough for me, if I could enter text into the terminal when there is a process runnung. Its just I can not type anything when "ng serve" is done.

**Comment by Tyriar** [comment]
@bastienJS `ng serve` continues to run though, so the terminal is not supposed to have control until the process is terminated??

**Comment by bastienJS** [comment]
@Tyriar Well I just would like to have it like it worked in WebStorm. There a integrated terminal has an exit button terminating the process within the terminal :-)

**Comment by Tyriar** [comment]
Ah ok, yeah I think I'll close this in favor of #6458. That will include a UI where you can kill terminal instances.
