### ISSUE TITLE
Duplicate 'A' access key in Brazilian Portuguese

### ISSUE THREAD

**Issue by awvalenti** [Microsoft/vscode#71075]
- VSCode Version: Versão: Commit de 1.32.3 (user setup): a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4 Data: 2019-03-14T23:43:35.476Z elétron: 3.1.6 Chrome: 66.0.3359.181 node. js: 10.2.0 V8: 6.6.346.32 OS: Windows_NT x64 10.0.17134
- OS Version: Windows 10 Pro (probably happens on all OSs)

Steps to Reproduce:

1. Press Alt + A
2. Submenu Ajuda (Help) is open; can't open submenu Arquivo (File).

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/834921/54923249-9cb50900-4ee8-11e9-85a8-90f534f96290.png)

Should change &Ajuda to Aj&uda (underlining 'u' instead of 'A'). Arquivo should be kept the same. This is the usual behavior, like Notepad below:
![image](https://user-images.githubusercontent.com/834921/54923406-f0275700-4ee8-11e9-8188-16c948fb2bd4.png)

**Comment by sbatten** [comment]
@janbaltus can the language pack be updated

**Comment by janbaltus** [comment]
Implemented the change.

**Comment by janbaltus** [comment]
Fix is present now in 1.33.1 LP. for insiders builds.
