### ISSUE TITLE
1.33.0-insider no longer calling readFile method of my FileSystemProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#71073]
I am developing an extension that implements FileSystemProvider. It is working correctly on the current VSCode release (1.32.3) but at the moment it's not loading file content when running on 1.33.0-insider.

I can also replicate the issue using the Remote FS extension (liximomo.remotefs) extension whose source is published at https://github.com/liximomo/vscode-remote-fs.

The MemFS sample is still working on my Insiders, so FileSystemProvider isn't completely broken.

But for my extension and for Remote FS I'm not seeing the readFile method ever getting called. In contrast, the readDirectory method continues to get called.

The effect is that I can browse directories on the remote system, but when I open any file it behaves as though it is a 0-byte file. No errors are reported, but all the content is missing.

I first noticed this after returning from vacation, so can't be sure exactly when it broke. But there seems to have been some recent work related to strict null checking which I guess could be relevant:

8f3cda12e475c810f77c737b590b67b1c7546f1b

To reproduce the problem:
1) Install Remote FS extension
2) Connect to a remote system (I used FTP)
3) Directories list OK
4) Opening a file reports no errors, but gives no content

Repeat the test on 1.32.3 to see correct behaviour.

Version: 1.33.0-insider (user setup)
Commit: 5688d00dd592a165530a82945c4ade4dad6b01e7
Date: 2019-03-25T06:19:55.474Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
@gjsjohnmurray thanks, good catch. I pushed a fix and would be happy if you can validate that your extension works properly with the next insiders update. I did some heavy refactorings in the file service

**Comment by gjsjohnmurray** [comment]
@bpasero I confirm this is now fixed in the latest Insiders:
Version: 1.33.0-insider (user setup)
Commit: 1876bd1d3805d632a9aa78fad47b2c3c555f6eec
Date: 2019-03-25T14:53:36.371Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

Thanks for the fast turnaround.
