### ISSUE TITLE
Test "server ready" feature in integrated terminal

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#71074]
Test for #69898:

- [x] macOS @auchenberg
- [x] linux @joaomoreno
- [x] windows @jrieken

Complexity: 3

For a description of the feature, please see https://github.com/Microsoft/vscode/issues/69311#issue-413837459.

In this milestone we've added support for detecting the trigger message in the integrated terminal (in addition to the debug console supported last milestone).
And we improved the error message if  the "Debugger for Chrome" is not installed if a user configures the "server ready" feature to start a browser debug session.

Verify that....
- it works out of the box for a node.js "express" application both for `openExternally` and `debugWithChrome` actions (see https://code.visualstudio.com/docs/nodejs/nodejs-tutorial#_an-express-application for how to create an express app)
- create a simple server application in another language (e.g. C# or Python, etc.) and configure the "pattern" and "uriFormat" properties to match the trigger message.
- use intellisense to configure the "server ready" feature to start a browser debug session. Verify that an error dialog is shown if the "Debugger for Chrome" is not installed.

**Comment by jrieken** [comment]
Unable to test this with express-app-sample...

**Comment by joaomoreno** [comment]
Was able to test this with a regular server:

```js
const http = require('http');

const port = 3001;
const app = http.createServer((req, res) => {
  res.write('Hello world!');
  res.end();
});

app.listen(port);
console.log(`server listening at port ${port}`);
```

Even cooler, after installing the Debugger for Chrome, I tested this one, which opens Chrome on start and breaks on that client side breakpoint.

```js
const http = require('http');

const port = 3001;
const app = http.createServer((req, res) => {
  res.write(`<script>debugger;</script>`);
  res.end();
});

app.listen(port);
console.log(`server listening at port ${port}`);
```

**Comment by weinand** [comment]
The default app generated by the express generator has changed and does not spit out the `Listening on port 3000` message any more.

This can be easily fixed:
- open "bin/win"
- add `console.log('Listening on port ' + bind)` at the end of the `onListening()`function:
```js
function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
  console.log('Listening on port ' + bind);
}
```

**Comment by jrieken** [comment]
I understand `console.log` I think what blocks me is that in 9 out of 10 cases debugging just doesn't work for me. Spinning forever not signs of launching

**Comment by weinand** [comment]
I'm already looking into this issue on Windows....

**Comment by weinand** [comment]
I'm not able to reproduce node.js debugging issues on Windows.
I tried with node.js 10.2 and 10.15

**Comment by jrieken** [comment]
let debug on my machine then

**Comment by jrieken** [comment]
This seems very flaky (and silent to me). I need a couple of restarts of my VM for debugging to work reliably. Opening firefox only worked after the 5th try, it was likely installing an update, but I had no clue what's going on

**Comment by auchenberg** [comment]
Validated all steps using my https://github.com/auchenberg/nodejs-shopping-cart on MacOS with no problems.

I agree with https://github.com/Microsoft/vscode/issues/69311 and https://github.com/Microsoft/vscode/issues/71177, it would be great to have a some logging that also outputs if the `pattern` doesn't match anything.

**Comment by weinand** [comment]
It will be difficult to log if the pattern doesn't match anything.
The program output that gets scraped appears at any time while the program runs.
When do we know that the pattern will not match anything?

**Comment by auchenberg** [comment]
It's more in the configuration phase, where you don't know whether your regex is working or not, but you could argue that's a generel regex problem ;)
