### ISSUE TITLE
Tasks always terminate with exit code 2 on Samba directory on Windows

### ISSUE THREAD

**Issue by 91khr** [microsoft/vscode#71072]
Issue Type: <b>Bug</b>

1. Create a tasks.json:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "test",
            "type": "shell",
            "command": "dir",
        },
    ]
}
```
2. Run the task, it outputs:
```
The terminal process terminated with exit code: 2
```

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-wordcount-cjk|hol|1.3.0
background|sha|1.1.19
vim|vsc|1.2.0

</details>

**Comment by alexr00** [comment]
If you `cd` to the Samba directory from the VS Code integrated terminal and run `dir` from there does it work?

**Comment by 91khr** [comment]
> 
> 
> If you `cd` to the Samba directory from the VS Code integrated terminal and run `dir` from there does it work?

Yes, and other commands also work.

**Comment by 91khr** [comment]
Only commands defined in `tasks.json` do not work.

**Comment by alexr00** [comment]
If you scroll up in terminal that the task runs in (up before the `The terminal process terminated with exit code: 2`) is there any other information?

**Comment by 91khr** [comment]
> 
> 
> If you scroll up in terminal that the task runs in (up before the `The terminal process terminated with exit code: 2`) is there any other information?
There is no except `Executing task`

**Comment by alexr00** [comment]
What happens if you set a cwd on the task? https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks

**Comment by 91khr** [comment]
Seems that it's because Windows's cmd isn't compatible with remote directory. After upgrading both Windows and vscode I get `The terminal shell CWD "\\\wsl$\Arch\tmp" does not exist` as command output.

I don't know if it's because cmd changes its way to output error message, or vscode's terminal changed its way to get program output. I don't know if this issue(error message of `cmd` doesn't appear on terminal output) still exists on old versions of Windows either.

System info:
```
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Thanks, and sorry for wasting your time.

**Comment by alexr00** [comment]
Thanks for checking again. Sounds like it's safe to close!
