### ISSUE TITLE
optional task input param

### ISSUE THREAD

**Issue by fatfatson** [Microsoft/vscode#71071]
currently we can have input param for task,
but it will always prompt to input,
sometimes I hope there's a default input( maybe the last input), 
so none prompt appear if I trigger the task regularly,
it will only appear when I hold a special key(Shift or Option) at the same time.

BTW:
could the `pickString` input get its options dynamically(such as from a shell cmd ouput)?

**Comment by alexr00** [comment]
Checkout the `Rerun Last Task` command. You can also set keybindings for specific tasks, so you could create a separate task that does what you want and add a keybinding for it. 
Otherwise, you can just create a new task that does what you want.
