### ISSUE TITLE
VsCode spawning too many git for windows processes

### ISSUE THREAD

**Issue by HenriqueSabino** [Microsoft/vscode#71085]
So, I while ago when I tried to open VsCode my computer went really slow after some time using it, so slow that I couldn't shut it down normaly because it was super unresponsive. I tried to find many issues here but couldnt find any that really solved my problem. The issue is: when I open VsCode it spawns too many git processes and the CPU usage just goes to 100% and my PC become unusable. Here's a screenshot:

![Screenshot (49)](https://user-images.githubusercontent.com/22148178/54928916-7b0d4f00-4ef3-11e9-8eb6-f3064f7d2206.png)

I really want to fix this issue because I don't want to change to another IDE. I love VsCode and it is perfect for me. If you guys need some more info, just say what you need and I'll send as soon as possible!

**Comment by HenriqueSabino** [comment]
Ok, I got a hint of how to avoid the problem on stackoverflow. If I add `"git.enabled" = false` to the settings.json file It does spawn github processes weirdly like that.

**Comment by joaomoreno** [comment]
In order to figure out what those processes are doing, can you take a screenshot of the Task Manager showing the full command line of those `Git for Windows` processes? You can find that in the `Details` tab.

**Comment by HenriqueSabino** [comment]
Here you go

![Screenshot (53)](https://user-images.githubusercontent.com/22148178/55010204-91cea700-4fc2-11e9-8136-0718833ad8b7.png)
![Screenshot (54)](https://user-images.githubusercontent.com/22148178/55010206-92673d80-4fc2-11e9-8903-9ffca75354a4.png)

**Comment by joaomoreno** [comment]
If you right click on that view's columns, you can add more columns. Can you add the `Command Line` column, expand it and show it?

**Comment by HenriqueSabino** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/22148178/55102715-cc5d4000-50a5-11e9-9ed8-15af3bc8c469.png)

**Comment by joaomoreno** [comment]
In a Command Line, what does `git --version` return?

**Comment by HenriqueSabino** [comment]
The same thing happens, it spawns a bunch of `git for windows` processes, but when I close the cmd it stops all of then

**Comment by joaomoreno** [comment]
Can you please fully reinstall Git from https://git-scm.com/?

**Comment by HenriqueSabino** [comment]
Ok! Looks like I just needed to update my Git, lol. Thanks a lot for helping me solving this problem!
