### ISSUE TITLE
Cmd clicking any URL in an editor is broken

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#71088]
Issue Type: <b>Bug</b>

1) Open any file (I tried .ts and .md) that contains a URL
-> URL is correctly detected
2) Cmd+click the url
-> nothing happens

VS Code version: Code - Insiders 1.33.0-insider (5688d00dd592a165530a82945c4ade4dad6b01e7, 2019-03-25T06:15:09.139Z)
OS version: Darwin x64 18.0.0

**Comment by weinand** [comment]
@kieferrm when I hover over such a link I see that the correct modified key for opening the link is "opt"  and not "cmd". And an "opt"-click actually opens the link fine. 

Do you see the same?

**Comment by kieferrm** [comment]
I don't. Whether it's Option or Cmd is based on your settings. But no matter which setting I use, no links opens for me.

**Comment by kieferrm** [comment]
Same on windows.

**Comment by kieferrm** [comment]
Works out of source.

**Comment by weinand** [comment]
It works for me with the same Insiders version on bot Windows and macOS.
Can you reproduce with extensions disabled?

**Comment by kieferrm** [comment]
Same with disabled extensions. Nothing happens. Nothing in the logs or devtools.

**Comment by kieferrm** [comment]
Here is a reproducible case:
1) create a new untiled file
2) use the following content
```
https://github.com/eamodio/vscode-gitlens
```
-> link can not be opened
3) change link to
```
https://www.github.com/eamodio/vscode-gitlens
```
-> links opens

This happens in all editors including web views.

**Comment by kieferrm** [comment]
See also #70983.

**Comment by joaomoreno** [comment]
Merging with https://github.com/Microsoft/vscode/issues/71112
