### ISSUE TITLE
Test new IntelliSense settings

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71084]
Refs: https://github.com/Microsoft/vscode/issues/45039, https://github.com/Microsoft/vscode/issues/68557

- [x] any @sbatten
- [x] macOS @misolori

Complexity: 2

Test the following new IntelliSense settings. Make sure the settings name makes sense, its documentation is good, that its values make sense, and that they can be configured per language.

* `editor.suggest.showIcons`
* `editor.suggest.maxVisibleSuggestions`
* `editor.suggest.filteredTypes`

**Comment by sbatten** [comment]
@jrieken why is the max value 12 for `editor.suggest.maxVisibleSuggestions`?

**Comment by jrieken** [comment]
That's what it used to be and we never go requests to show more only less
