### ISSUE TITLE
 Cannot read property 'identifier' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#71099]
Issue Id: <b>26f4eef0-9ac5-74da-dfc0-841f069c95f2</b><br /><br />*Versions* <br />- 1.32.3<br />*Stack* <br />TypeError: Cannot read property 'identifier' of undefined<br />[/vs/workbench/contrib/extensions/electron-browser/extensionsList.ts#184:49 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/contrib/extensions/electron-browser/extensionsList.ts#L184:49 (call))<br />[/vs/base/common/event.ts#586:18 (fire)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L586:18 (fire))<br />[/vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts#61:64](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts#L61:64)<br />    at Array.forEach (<anonymous>)<br />[/vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts#61:29 (onFocusChange)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts#L61:29 (onFocusChange))<br />[/vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts#119:51 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts#L119:51 (call))<br />[/vs/base/common/event.ts#586:18 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L586:18 (call))<br />[/vs/base/common/event.ts#56:83 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L56:83 (call))<br />[/vs/base/common/event.ts#584:15 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L584:15 (call))<br />[/vs/base/common/event.ts#56:83 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L56:83 (call))<br />[/vs/base/common/event.ts#750:14 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L750:14 (call))<br />[/vs/base/common/event.ts#584:15 (fire)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L584:15 (fire))<br />[/vs/base/browser/ui/list/listWidget.ts#163:17 (set)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/browser/ui/list/listWidget.ts#L163:17 (set))<br />[/vs/base/browser/ui/list/listWidget.ts#1364:13 (setFocus)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/browser/ui/list/listWidget.ts#L1364:13 (setFocus))<br />[/vs/base/browser/ui/list/listWidget.ts#1374:8](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/browser/ui/list/listWidget.ts#L1374:8)<br />    at V.focusNext (out/vs/workbench/workb<br />

**Comment by sandy081** [comment]
@joaomoreno I see `List.onFocusChange` event is returning null/undefined elements. I do not think my list model  has such. How is it possible?

**Comment by joaomoreno** [comment]
@sandy081 Not really sure, gotta try to repro... :thinking:

**Comment by sandy081** [comment]
Unfortunately no repro.. Guessing it could be coming from the model as the model is delayed paged model.
