### ISSUE TITLE
Parent sessions should be auto expanded in call stack view

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#71092]
testing #71063:

- Use Cluster sample.
- set breakpoint in line 20: "res.writeHead(200);"
- F5

Observe:
Child sessions are not visible:

![2019-03-26_12-20-38](https://user-images.githubusercontent.com/1898161/54993204-98105380-4fc1-11e9-8328-38f7ce40fd91.png)

I think we should automatically expand the parent if the first child is added. If the user then decides to collapse the parent, we should not expand it automatically later.

- now open browser on "localhost:8000"

Observe:
The debugger hits a breakpoint but no changes in the stack view, the stack is not revealed and the parent session still says "running":

![2019-03-26_12-23-57](https://user-images.githubusercontent.com/1898161/54993433-0bb26080-4fc2-11e9-8f04-a0e0520992e6.png)

Stopping should always reveal the stack (and expand all parent nodes as needed).

**Comment by misolori** [comment]
Also ran into this. It appears that the dropdown menu selects the child process but not in the tree view. I expected it to select it in both.

**Comment by weinand** [comment]
The session is now expanded properly when a breakpoint is hit.

But when starting the Cluster sample without a breakpoint set, the child sessions will be hidden behind the collapsed top level node. This is a loss of functionality compared to the non-hierarchical solution where all child sessions were visible.
So the fix does not address the original problem from above.

**Comment by weinand** [comment]
works fine

**Comment by isidorn** [comment]
Great, thanks for verifying.
