### ISSUE TITLE
Review call hierarchy api proposal

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71098]
Refs: https://github.com/Microsoft/vscode/issues/70231

- [x] any @aeschli 

Complexity: 2

Review the call hierarchy API proposal: https://github.com/Microsoft/vscode/blob/61c990fb6f1a7cdd7ff599156f2002b36b7b079f/src/vs/vscode.proposed.d.ts#L21-L68

**Comment by aeschli** [comment]
@jrieken in the returned [CallHierarchyItem, Location[]][], wouldn't the locations always be inside the CallHierarchyItem? Does it have to be a Location then, or is Range[] enough?

**Comment by jrieken** [comment]
Yeah, they are always inside "a" call hierarchy item, e.g the item making the call so either items from the returned tuples or when the arguments. I have no strong feelings, there are more arguments in the LSP item: https://github.com/Microsoft/vscode-languageserver-node/pull/420#discussion_r264675674

**Comment by aeschli** [comment]
Discussed with @jrieken. We wrote down a new proposal in https://github.com/Microsoft/vscode/issues/70231#issuecomment-477042744
