### ISSUE TITLE
Keyboard shortcut for switching between diff/editor views

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#7109]
There is a button in the top right of the editor which says either "Switch to Editor View" or "Switch to Changes View". Maybe I'm missing it but I can't find a keyboard shortcut for this functionality.

**Comment by bpasero** [comment]
Here are the command ids: `workbench.action.git.globalOpenChange` and `workbench.action.git.globalOpenFile`

**Comment by pdavies** [comment]
I've mapped (different) shortcuts to these, but it's still not possible to map a key combination to toggle between the two modes which is how I interpreted the issue title. (Attaching the same keyboard shortcut to both commands doesn't work.) Having a single toggle shortcut would be much nicer!
