### ISSUE TITLE
IFileService.watchFileChanges is not watching files not existing

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#71090]
IFileService.watchFileChanges is not watching files not existing. It should trigger an event when file is added just like when the file is modified or removed.

I am moving away from node based listener for user configuration file to file service based. This is needed for this.

**Comment by bpasero** [comment]
Not convinced that should be done by the watcher automagically. I find it better to ask clients to explicitly watch on the parent folder, but I can see how what you ask is more convenient for you, but it will not happen until we revisit the file watcher implementation.

**Comment by sandy081** [comment]
If it is only for this case, I can also live by creating the settings file if not exists and then start watching.

**Comment by bpasero** [comment]
@sandy081 is this for global settings or workspace settings?

**Comment by sandy081** [comment]
Global settings
