### ISSUE TITLE
Test handling of multiple formatters

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71093]
Refs: https://github.com/Microsoft/vscode/issues/41882

- [x] any @octref
- [x] any @isidorn

Complexity: 3

We have improved the behaviour when having multiple formatters for a document. Install 'conflicting' formatter extensions like beautify and/or prettier and test that

* there are new actions 'Format Document With...' and 'Format Selection With...' which show quick pick allowing you to select an extension that's used to format
* clicking the gear icon in the formatter pick opens the extensions viewlet for that extension - allows to configure/disable/uninstall it
* there is also 'Format Document' and 'Format Selection' which in case of multiple extensions just pick one and then print on the status bar which it picked
* format on save and format on paste also print to status bar which formatter was selected, also only when multiple formatters exists

*Note that format selection only shows when an extension contributes such a provider.

**Comment by octref** [comment]
Great work 👍
