### ISSUE TITLE
 Cannot read property 'moveEditor' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#71094]
Issue Id: <b>8602f492-e93b-6f89-fe04-d2d45dc4fa3d</b><br /><br />*Versions* <br />- 1.32.3<br />*Stack* <br />TypeError: Cannot read property 'moveEditor' of undefined<br />[/vs/workbench/contrib/webview/electron-browser/webviewEditorService.ts#123:53 (revealWebview)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/contrib/webview/electron-browser/webviewEditorService.ts#L123:53 (revealWebview))<br />[/vs/workbench/api/electron-browser/mainThreadWebview.ts#188:23 (apply)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/api/electron-browser/mainThreadWebview.ts#L188:23 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#390:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L390:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#375:31 (_invokeHandler)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L375:31 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#295:18 (_receiveRequest)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L295:18 (_receiveRequest))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#225:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L225:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#100:41 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L100:41 (call))<br />[/vs/base/common/event.ts#584:15 (fire)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L584:15 (fire))<br />[/vs/base/parts/ipc/node/ipc.net.ts#295:11 (deliverMessages)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/parts/ipc/node/ipc.net.ts#L295:11 (deliverMessages))<br />[/vs/base/parts/ipc/node/ipc.net.ts#302:2 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/parts/ipc/node/ipc.net.ts#L302:2 (call))<br />[/vs/base/common/event.ts#584:15 (fire)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L584:15 (fire))<br />[/vs/base/parts/ipc/node/ipc.net.ts#103:22 (acceptChunk)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/parts/ipc/node/ipc.net.ts#L103:22 (acceptChunk))<br />[/vs/base/parts/ipc/node/ipc.net.ts#132:3](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/parts/ipc/node/ipc.net.ts#L132:3)<br />    at Socket.emit (events.js:182:13)<br />    at addChunk (_stream_readable.js:279:12)<br />    at readableAddChunk (<br />

**Comment by mjbvz** [comment]
This was fixed at some point by adding a conditional guard
