### ISSUE TITLE
Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#711]
_From @Ristaaf on November 20, 2015 13:8_

I get this error every time when opening a comparison of a ts file in the GIT panel of VS Code. Happen in all projects I have tried, including a test one with just one simple ts file.

_Copied from original issue: Microsoft/vscode-tslint#5_

**Comment by egamma** [comment]
_From @serkanyersen on November 23, 2015 22:23_

Same here.

**Comment by egamma** [comment]
This is unrelated to vscode-tslint. Moving to vscode.

**Comment by egamma** [comment]
closing, this is indeed a tslint issue, reopening the original issue filed against vscode-tslint and closing this one.

**Comment by kumarharsh** [comment]
@egamma I'm getting the same error when I view a javascript file in the Git diff view after updating to 1.6-insider. The only change in settings I've done is setting the `nodePath` for eslint. @dbaeumer could it be related to that?

Although I must say that nothing is breaking (visibly) due to this error yet, just pressing escape dismisses it and I can keep working, and this error is *not* being shown when I open a golang file.

**Comment by dbaeumer** [comment]
No, the nodePath variable is only interpreted by the ESLint server.

**Comment by egamma** [comment]
@kumarharsh can you file a new bug with as much information about your setup and steps to reproduce please.

**Comment by kumarharsh** [comment]
@egamma: I want to, but I don't have any extra info as of now. Is there a way to trace where an error is being thrown from? The stack trace of the error is not very helpful I'm afraid...

**Comment by egamma** [comment]
@kumarharsh I doubt that you see the same problem that was reported here and that was fixed some time ago. Therefore, please file a new issue with the error you are seeing. 

Can you still reproduce the issue when you run without extensions `--disable-extensions`.  Do you see anything in the developer tools console `Help>Toggle Developer Tools`.

**Comment by kumarharsh** [comment]
Yes, restarting vscode with your recommendations does indeed fix this error. It might be due to the eslint server... I've opened the new issue here: https://github.com/Microsoft/vscode/issues/12229
