### ISSUE TITLE
C# Resolve for usings

### ISSUE THREAD

**Issue by Bungalow12** [Microsoft/vscode#7110]
- VSCode Version: 1.1.1
- OS Version: OSX 10.11.4

Steps to Reproduce: 

1. Type in a class that exists somewhere in a referenced library. 
2. Right click the class
3. Go to Resolve -> then Add using statement or replace with full namespace

This is a feature I love in Visual Studio and MonoDevelop. However I'm really enjoying vscode and would like this to be my main editor. This is a feature I adored.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#572

**Comment by Bungalow12** [comment]
This is supposedly provided via /fixusings command in Omni-sharp but does not seem to be surfaced by vscode
