### ISSUE TITLE
 Cannot read property 'getId' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#71100]
Issue Id: <b>7f6e808c-11ed-a4a9-f860-b63d568b6056</b><br /><br />*Versions* <br />- 1.32.3<br />*Stack* <br />TypeError: Cannot read property 'getId' of null<br />[/vs/workbench/browser/parts/sidebar/sidebarPart.ts#109:31](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L109:31)<br />    at Generator.next (<anonymous>)<br />[/vs/base/common/errors.ts#184:9](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/errors.ts#L184:9)<br />    at new Promise (<anonymous>)<br />[/vs/base/common/errors.ts#184:9 (__awaiter)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/errors.ts#L184:9 (__awaiter))<br />[/vs/workbench/browser/parts/sidebar/sidebarPart.ts#108:94 (call)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L108:94 (call))<br />[/vs/base/common/event.ts#584:15 (fire)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/base/common/event.ts#L584:15 (fire))<br />[/vs/workbench/browser/composite.ts#258:24 (deregisterComposite)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/browser/composite.ts#L258:24 (deregisterComposite))<br />[/vs/workbench/browser/viewlet.ts#95:8 (deregisterViewlet)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/browser/viewlet.ts#L95:8 (deregisterViewlet))<br />[/vs/workbench/api/browser/viewsExtensionPoint.ts#336:59 (deregisterCustomViewContainer)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L336:59 (deregisterCustomViewContainer))<br />[/vs/workbench/api/browser/viewsExtensionPoint.ts#209:9 (removeCustomViewContainers)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L209:9 (removeCustomViewContainers))<br />[/vs/workbench/api/browser/viewsExtensionPoint.ts#174:9 (_handler)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/api/browser/viewsExtensionPoint.ts#L174:9 (_handler))<br />[/vs/workbench/services/extensions/common/extensionsRegistry.ts#140:8 (_handle)](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/common/extensionsRegistry.ts#L140:8 (_handle))<br />[/vs/workbench/services/extensions/common/extensionsRegistry.ts#131:7](https://github.com/microsoft/vscode/blob/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/src/vs/workbench/services/extensions/common/extensionsRegistry.ts#L131:7)<br />    at Function._handleExtensionPoint (out/vs/workbench/workbe<br />

**Comment by bpasero** [comment]
Not sure this can still happen after our strict null work.

**Comment by isidorn** [comment]
Looking at the code it looks covered by the stict null work. Closing.
