### ISSUE TITLE
Test: Certificates loaded from OS

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#71108]
#52880

- [x] macOS @kieferrm
- [x] linux @sandy081
- [x] windows @roblourens

Complexity: 3

Run the [https-server.zip](https://github.com/Microsoft/vscode/files/3005094/https-server.zip) in a terminal.

Run this code in an extension:
```js
https.get('https://localhost:3000', res => console.log(res.statusCode))
	.on('error', console.error);
```

- Verify that the request fails because the certificate is self-signed.
- Add the certificate (attached) to the root certificates of your OS. (See, e.g., https://www.bounca.org/tutorials/install_root_certificate.html)
- Verify that the request succeeds.
- Turn the `http.systemCertificates` setting off.
- Verify that the request fails again.
- Remove the certificate from the root certificates of your OS to clean up.

**Comment by sandy081** [comment]
Verified as per the steps mentioned.

**Comment by roblourens** [comment]
Which one is the crt I added, is it the one called localhost?

![image](https://user-images.githubusercontent.com/323878/55022294-8164ff00-4fb7-11e9-9142-63d4c60b1996.png)

**Comment by kieferrm** [comment]
FYI, on macOS, adding the key to the keychain did not suffice. I had to reboot my machine to

**Comment by chrmarti** [comment]
@roblourens Yep, it's the 3/7/2020 one.
