### ISSUE TITLE
Test: GitHub PR Extension - new commenting API

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#71103]
- [x] macOS @meaghanlewis
- [x] linux @bpasero
- [x] windows @jrieken

Complexity: 3

Authors: @rebornix, @RMacfarlane 

This iteration, we created a new proposed commenting API (https://github.com/Microsoft/vscode/issues/68020) and adopted it in the GitHub PR extension. This is to test that all commenting functionality behaves as before. Test that

- Within an editor, you can create new comment threads, and reply to previously existing ones
- You are able to edit and delete comments
- You can start, finish, and delete a review from within the editor
- When a comment is part of an unfinished review, it should have the label "Pending"
- If you enter text in a comment without adding it and switch editors, the text is preserved when you return to the editor

Please test against the nightly version of the extension, which should have the most recent changes:
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders

And file issues in this repo: https://github.com/Microsoft/vscode-pull-request-github

You can use https://github.com/auchenberg/pullrequest-demo for testing

**Comment by octref** [comment]
Hey @meaghanlewis, I cannot seem to assign you to this test item. Would you mind testing this item, and post issues that you found while referencing this issue? Thanks!

**Comment by meaghanlewis** [comment]
👋@octref I can't assign myself either for some reason. I'll test today and update this issue once I'm done.

**Comment by meaghanlewis** [comment]
I'm all done testing on Mac but can't ✔️off my item in the issue description.
