### ISSUE TITLE
Background color is not applied to whole background

### ISSUE THREAD

**Issue by Cubox-** [microsoft/vscode#71117]
- VSCode Version: 1.32.3
- OS Version: Windows 10 1809

Steps to Reproduce:

1. ??
2.

Does this issue occur when all extensions are disabled?: Yes

Hi,

I am having a weird glitch where the background colour is not applied all the way when using a dark theme (even default dark theme).
This looks like the issue #12473 but I'm on Windows 10 1809.
I do have a calibrated screen profile.

See attached screenshot.
![image](https://user-images.githubusercontent.com/479129/54957709-d96a1a00-4f53-11e9-8ed6-51df71d6ed1a.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by Cubox-** [comment]
The issue does not occur with the exploration build

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by Cubox-** [comment]
Thanks for the update!
