### ISSUE TITLE
Test actions installing missing dependencies

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#71119]
Ref - https://github.com/Microsoft/vscode/issues/70546

- [x] AnyOS @chrisdias
- [x] AnyOS @kieferrm

Complexity: 2

1. Install any extension that has dependencies for example `ms-azuretools.vscode-cosmosdb`
2. Open extensions folder and delete the extension it depends on `ms-vscode.azure-account`
3. Reload the window and open Azure Explorer in the side bar
4. Make sure that an error with an action `Install and Reload` pops up with missing dependency message. Clicking on `Install and Reload` action should install the missing dependency and reloads the window.
5. There is also a command `Extensions: Install Missing Dependencies`, you can run to install all missing dependencies. Test running this command after step 3 and make sure missing dependencies are installed.

**Comment by kieferrm** [comment]
Tested on macOS and Windows.

**Comment by chrisdias** [comment]
Tested on Linux, overall looks good.
