### ISSUE TITLE
Links don't work without a subdomain

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#71112]
Many links in VS Code do not open in extension pages and in the terminal. The behavior I see is that links without a subdomain `e.g. https://github.com` will not work, while links with a subdomain `e.g. https://www.google.com` will. 

To repro: 
1. Open terminal
2. `echo https://google.com`
3. Ctrl/Alt+Click the link

🐛 => Nothing happens.

@bpasero or @jrieken ?

**Comment by Tyriar** [comment]
We debugged this and little and the main findings were this line never gets hit (the await doesn't return) for "http://google.com" but it does with "http://www.google.com"

https://github.com/Microsoft/vscode/blob/7c0068d6edb23bc6c5aad3199b34f67fc255a404/src/vs/editor/browser/services/openerService.ts#L44 (

**Comment by dig22** [comment]
I tried to re-produce the steps, I can confirm the links don't work for me
but if I ` Ctrl + Left-Click ` it works

> Many links in VS Code do not open in extension pages and in the terminal. The behavior I see is that links without a subdomain `e.g. https://github.com` will not work, while links with a subdomain `e.g. https://www.google.com` will.
> 
> To repro:
> 
> 1. Open terminal
> 2. `echo https://google.com`
> 3. Ctrl/Alt+Click the link
> 
> 🐛 => Nothing happens.
> 
> @bpasero or @jrieken ?

**Comment by bpasero** [comment]
Seems to be going through some relay URL service on the main side, @joaomoreno ?

**Comment by joaomoreno** [comment]
@jrieken Ufff. Gotta see which of my handlers never returns.
