### ISSUE TITLE
Cuda an actual language

### ISSUE THREAD

**Issue by MMMziemniaki** [Microsoft/vscode#71111]
As far as I am concerned cuda support is an extension. However, making it an actual language would much simplify developing other extensions. Exibit A: https://reviews.llvm.org/D59759

In the example, onLanguage handler can't be called in case of Cuda, because it is not a vscode language. The case requires opening c++ file to start clang and that feels just wrong.

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
