### ISSUE TITLE
Code inline highlighting not functional inside bold or italics text

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#7111]
- VSCode Version: Any (up to 1.1
- OS Version: Any (tried OSX and Win10)

seems that code inside bold or italics text is not rendered (as it is here on github even):

``` md
**te`code`st**
_te`code`st_
`code`
```

**te`code`st**
_te`code`st_
`code`

Same for **_bold italics_**

![image](https://cloud.githubusercontent.com/assets/5379325/15730101/48a48e14-289c-11e6-9516-67d9cb64b237.png)

**Comment by mjbvz** [comment]
I believe this was fix in VSCode 1.7

<img width="245" alt="screen shot 2016-12-01 at 2 38 05 pm" src="https://cloud.githubusercontent.com/assets/12821956/20815705/d31275fe-b7d3-11e6-8812-2579441f721a.png">

Let us know if you still see any issues
