### ISSUE TITLE
Background appears different from text background

### ISSUE THREAD

**Issue by josefaidt** [microsoft/vscode#71123]
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.3

I recently received an issue regarding my theme and a slight discoloration on the background where blocks for text are rendered and the background color I have set. [Here is the issue](https://github.com/josefaidt/rouge-theme/issues/13) for a reference screenshot.

I've been digging through the dev tools trying to see if there was a transparent layer causing the discoloration or an off color on my part, but the only thing that stood out to me was my background color being converted to rgb format and being passed down to child elements as inline styles. Though, most look correct.

Using the macOS digital color meter I've been able to determine a slight variance in the color I've set:

|  | Shown in DevTools | Converted color |
|---|---|---|
| Actual | `#172030` | `rgb(25, 32, 47)` |
| The 'off' color |`rgb(25, 33, 47)` | `#19212f` |

This may be related to #70782 

Steps to Reproduce:

1. install `josef/rouge-theme`
2. discoloration will be noticeable in the sidebar with a folder open, and a short file. Discoloration is generated in blocks upon hitting a certain line number below the existing text block

Does this issue occur when all extensions are disabled?: Yes

**Comment by josefaidt** [comment]
Bottom right of this image:

![image](https://user-images.githubusercontent.com/5033303/54963887-68693900-4f38-11e9-9606-083c48e8155d.png)

**Comment by aeschli** [comment]
@josefaidt Not sure what I should see bottom right. Can you add some arrows to the screenshots?

**Comment by usernamehw** [comment]
![54963887-68693900-4f38-11e9-9606-083c48e8155d](https://user-images.githubusercontent.com/9638156/54986226-4d8fd680-4fc3-11e9-88cd-76b4309b2d27.png)

**Comment by josefaidt** [comment]
Thanks @usernamehw for the additional screenshot. The discoloration is most noticeable with "night mode" turned on.

**Comment by aeschli** [comment]
![DeepinScreenshot_select-area_20190402092716](https://user-images.githubusercontent.com/6461412/55384024-e1b0ef00-5529-11e9-9601-a55f37a8c04a.png)

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/55384386-e4f8aa80-552a-11e9-8d8c-8a6cd0f23286.png)

**Comment by aeschli** [comment]
The difference comes from the use of canvas for the minimap.
Chromium adopts the monitors colorspace for the DOM area, but not for the canvas. 
https://webkit.org/blog/6682/improving-color-on-the-web/ discusses the API to be added.

Alternatively we can use a transparent background for the canvas.

**Comment by josefaidt** [comment]
@aeschli I've changed the name after rereading this issue. I think my issue has been misunderstood. I think you're still on the right track, but I have minimap disabled. The issue does seem to be related to the use of canvas, but this is affecting the editor background, not just the minimap.

**Comment by UXDart** [comment]
on electron to fix that, the solution is to add a parameter `app.commandLine.appendSwitch('force-color-profile', 'srgb');`

the problem is that the canvas is using other color profile, maybe try to add that parameter... and it will do the same (?)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by josefaidt** [comment]
Thanks @bpasero I will test the new build this evening!

**Comment by bpasero** [comment]
OK

**Comment by josefaidt** [comment]
Looks good to me 👍
