### ISSUE TITLE
Opening new file shouldn't replace current one

### ISSUE THREAD

**Issue by frostbyte3** [Microsoft/vscode#71121]
Issue Type: <b>Bug</b>

When I open a new file from the file explorer it closes the one I currently have open and replaces it with the new one to open. This seems like it was an intentional feature, but It. Is. So. Annoying. Usually when I'm programming I need to open other files to reference and see what methods I need, exact names etc. 80% of the time when I open a new file, I still need the old one. And the other 20% of the time I wouldn't care either way. Please just keep it stupid simple and open new files in new tabs. Thank you.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100H CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.56GB (0.22GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.8.1
php-debug|fel|1.13.0
vscode-prettydiff|Hex|0.6.5
mssql|ms-|1.5.0
python|ms-|2019.2.5558
vscode-docker|Pet|0.6.1
java|red|0.41.0
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2

</details>

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
