### ISSUE TITLE
FileSearchProvider results are not displayed correctly

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/vscode#71120]
- VSCode Version: 1.33.0-insider 
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Register a FileSearchProvider and return a set of results in a URI array
Expected: the path is displayed after each filename in the results dropdown
Actual: the path is displayed only for files that are currently open in the guest's editor. For all others, the displayed path is just a backslash.

Does this issue occur when all extensions are disabled?: n/a

![capture5](https://user-images.githubusercontent.com/16658549/54960807-7066b000-4f1b-11e9-838d-e85f2ce2db4f.PNG)

**Comment by roblourens** [comment]
Also fixed by https://github.com/Microsoft/vscode-cached-file-search-provider/commit/14d4ec1676429da1c54195031790dd20ebe44c95

**Comment by gjsjohnmurray** [comment]
@roblourens When is FileSearchProvider expected to get promoted from a proposed API to a final one? A search for the api-finalization tag didn't show anything for this.

**Comment by roblourens** [comment]
It's not a high priority right now. Is there something you want to use it for?

**Comment by gjsjohnmurray** [comment]
I'm building an extension that implements ```IFileSystemProvider``` to access code on a remote server. As I understand it, ```IFileSearchProvider``` would allow me to make QuickOpen (Ctrl+P) more useful.

**Comment by RMacfarlane** [comment]
@roblourens Is drive letter casing expected to matter here?

If I do

```ts
        vscode.workspace.registerFileSearchProvider('file', {
            provideFileSearchResults(query, options, token) {
                return Promise.resolve([vscode.Uri.parse('file:///e:/dev/new-test-extension/src/extension.ts')]);
            }
        });
```

everything works as expected, but if the drive letter is capitalized, the drive letter is appended twice:
![Screen Shot 2019-03-28 at 11 06 33 AM](https://user-images.githubusercontent.com/3672607/55182112-4810c880-514a-11e9-8843-d44380bdd96e.png)

**Comment by roblourens** [comment]
Is that a correctly formed windows file URI? Do you get the same from `Uri.file(e:/dev...)`?

**Comment by RMacfarlane** [comment]
Using `vscode.Uri.file('E:\dev\new-test-extension\src\extension.ts')` and `vscode.Uri.file('e:\dev\new-test-extension\src\extension.ts')` both work. So I think I'm just misusing parse

**Comment by roblourens** [comment]
I can't remember, it might be that `e:` needs to be uri-encoded. You can check by creating one and toStringing it.
