### ISSUE TITLE
[Custom Dialog] Different font-size

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#71132]
#71116 Issue Type: <b>Bug</b> 

![Screenshot (116)](https://user-images.githubusercontent.com/9638156/54977210-ad7b8280-4fad-11e9-93a4-b27006b82ed8.png)

![Screenshot (117)](https://user-images.githubusercontent.com/9638156/54977222-b409fa00-4fad-11e9-9d61-7429e95dd420.png)

VS Code version: Code - Insiders 1.33.0-insider (966b87dd4013be1a9c06e2b8334522ec61905cc2, 2019-03-26T01:05:50.235Z)
OS version: Windows_NT x64 10.0.17763

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/55119200-2f52d500-50ae-11e9-9957-74fb9cbbc37a.png)

![image](https://user-images.githubusercontent.com/876920/55119213-3bd72d80-50ae-11e9-955d-76487aa5933b.png)

The font size is inconsistent in above cases.

**Comment by sbatten** [comment]
@rebornix This is the same as native.

**Comment by rebornix** [comment]
Turns out that the messages in first image are separated by `\n\n`.
