### ISSUE TITLE
底部菜单栏自动刷新

### ISSUE THREAD

**Issue by bapuqln** [Microsoft/vscode#71137]
Issue Type: <b>Bug</b>

选中一个比较长的C++函数，底部的菜单栏就会疯狂的刷新

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|29, 12, 7|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
git-project-manager|fel|1.7.1
vscode-simple-icons|Lau|1.11.2
vscode-fileheader|mik|0.0.2
vscode-clang|mit|0.2.3
theme-monokai-pro-vscode|mon|1.1.12
vscode-language-pack-zh-hans|MS-|1.32.4
python|ms-|2019.2.5558
cpptools|ms-|0.22.1
vscode-ios-common-files|Ort|1.0.5
material-icon-theme|PKi|3.7.0
java|red|0.41.0
merge|ron|0.0.1
xcodebuild-tools|ste|0.0.7
python|tht|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
vscode-icons|vsc|8.4.0
debug|web|0.23.0
clang-format|xav|1.9.0

(10 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please file issues in English. Thanks!
