### ISSUE TITLE
Dropdown UI issue in Settings

### ISSUE THREAD

**Issue by induratized** [Microsoft/vscode#71133]
Issue Type: <b>Bug</b>

- Go to Setting > User Setting > Workbench > Appearance > Icon Themes.
- Click to open the Icon Themes dropdown.

Expected:
- The dropdown UI should be as expected of dropdown element

Actual:
- the dropdown top item has a top margin with background transparent

![Image Pasted at 2019-3-26 12-24](https://user-images.githubusercontent.com/6311837/54977425-4ec10380-4fc3-11e9-8b95-5e2604dce210.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
dart-code|Dar|2.24.0
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
tslint|eg2|1.0.43
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.7.0
polacode|pnp|0.2.2
java|red|0.41.0
code-settings-sync|Sha|3.2.7
vscodeintellicode|Vis|1.1.4
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-icons|vsc|8.4.0

(12 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This should already be fixed in Insiders
