### ISSUE TITLE
One or more snippets from the extension 'php' very likely confuse snippet-variables and snippet-placeholders

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#71138]
Seeing this when running insiders:

![image](https://user-images.githubusercontent.com/900690/54984813-f0d6f080-4faf-11e9-888d-e0521ec7bd86.png)

**Comment by roblourens** [comment]
I don't see this. Steps?

**Comment by bpasero** [comment]
Uff, not sure anymore, sorry. I think I just opened insiders, but feel free to close if you cannot repro.

**Comment by roblourens** [comment]
I looked into that warning and don't see any problematic snippets 🤷‍♂️

**Comment by roblourens** [comment]
Oh wait it only shows up in extension development mode, now I see it
