### ISSUE TITLE
eslint can't not find the module "babel-eslint" when I have installed the module babel-eslint?

### ISSUE THREAD

**Issue by fantasyKing** [Microsoft/vscode#7113]
- VSCode Version:latest
- OS Version:mac os x

Steps to Reproduce:

1. I install the extension eslint for vsc,and write parser : "babel-eslint" after I have installed babel-eslint locally,but the eslint extension reminds me that can't find the module babel-eslint?

**Comment by dbaeumer** [comment]
You need to have both eslint and babel eslint installed either globally or locally. Mixing it will not work. See https://github.com/Microsoft/vscode-eslint/issues/2.

If this is not the case for you can you please share your workspace. I tried it locally and I can run eslint with babel-eslint installed.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#82

**Comment by AbhayShiro** [comment]
I was facing this issue. I was working on ES6 MERN stack project. 

> ERROR: babel-eslint is not found 
This error was bugging me a lot.

It turns out that I had to **disable the eslint extension** of VS Code. Once this was done i reloaded the VS Code and the error stopped coming.

**Comment by AbhayShiro** [comment]
Most of the times whenever I faced such issues, I always check installed extension in VS Code. These extensions create conflicts and hence cause errors.

**Comment by AnalyzePlatypus** [comment]
@AbhayShiro 
Thanks!
