### ISSUE TITLE
Can't use numeric keyboard for search on macOS

### ISSUE THREAD

**Issue by tomintaiga** [microsoft/vscode#71134]
Issue Type: <b>Bug</b>

When I start typing file name in file explorer **iec104** and type **104** on addition keyboard (right from arrows) **VSC** didn't catch that input.

If I type **104** on main keyboard (numbers on top of qwerty keys) **VSC** catch that input and find my file.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3617)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.65GB (0.36GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.4.1
snort|inf|1.1.4
autoconf|mae|0.0.7
cpptools|ms-|0.22.1
bash-beautify|sha|0.1.1
markdown-all-in-one|yzh|2.2.0

</details>

**Comment by kostyabushuev** [comment]
Hello
@joaomoreno can i help to fix this bug?
**[PR](https://github.com/Microsoft/vscode/pull/71500)**

**Comment by sanket-bhalerao** [comment]
is this issue fixed?
i am able to see this issue in current vscode insiders.
Version: 1.35.0-insider (user setup)
Commit: 16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9
Date: 2019-05-27T05:19:20.616Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

**Comment by joaomoreno** [comment]
Reopening due to https://github.com/microsoft/vscode/pull/71500#issuecomment-512696781

**Comment by R4PH4** [comment]
Hello, do you have news for this bug to be fixed ?

**Comment by jrieken** [comment]
Still repros for me. Looks like the save was inside printable character but I believe the tree isn't using that...

**Comment by joaomoreno** [comment]
cc @alexdima

**Comment by alexdima** [comment]
@jrieken This works for me. I press number keys on the numpad on Windows and I see them filtering in various trees:

![image](https://user-images.githubusercontent.com/5047891/73473195-9d31f200-438c-11ea-81dc-6ff7e5835ca3.png)

**Comment by jrieken** [comment]
🤷‍♂ I used the num pad on my external mac keyboard and while it worked in the editor it didn't work in the tree

**Comment by alexdima** [comment]
This does not work on macOS. It works on Windows/Linux.
