### ISSUE TITLE
Debug: no longer able to debug a single file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#71135]
I just opened an empty workspace with one js file and hit F5:

![image](https://user-images.githubusercontent.com/900690/54981215-13650b80-4fa8-11e9-8b1a-31f68c07f57b.png)

**Comment by isidorn** [comment]
I can reproduce this but only for purple vscode (no folder). Both with out of source and insiders.
The error is coming from the node extension when trying to determine what program to run.
Thus leaving to @weinand feel free to assign back to me so I investigate more

**Comment by weinand** [comment]
@bpasero you saw the issue in a non-folder workspace, right?

**Comment by bpasero** [comment]
@weinand yeah

**Comment by weinand** [comment]
This is not a new problem.
It was already broken in previous stable builds.
