### ISSUE TITLE
Marketplace markdown links do not work

### ISSUE THREAD

**Issue by HaaLeo** [Microsoft/vscode#71136]
- VSCode Version: 1.32.3
- OS Version: windows 10 1803
- Type: Bug

# Description
When plubshing an extension with the vsce tool to the vscode marketplace with a readme containing: 
```markdown
# My Extension

See [Examples](#my-examples)

[...]

# My Examples
```
clicking the link _Examples_ I expect the section _My Examples_ to be revealed.

This works as expected on 
* GitHub
* VS Code's Markdown Preview
* VS Code's Extension Explorer

Previously this also worked for the vscode marketplace website. However currently the expected section is not revealed. I guess this behavior changed due to a server side update? How can I change my readme links to work properly on all platforms again?

# Example
An example extension where the described behavior can be observed is the [Time Converter (timing)](https://marketplace.visualstudio.com/items?itemName=HaaLeo.timing) extension, where links like https://marketplace.visualstudio.com/items?itemName=HaaLeo.timing#simple-conversion do not work any more.

**Comment by sandy081** [comment]
@HaaLeo Do you mean, it does not work in Marketplace web site?

**Comment by HaaLeo** [comment]
@sandy081 yes exactly. Also because a time ago it was used to work there, too.

**Comment by sandy081** [comment]
@gaurav42 Not sure where to report this issue in Marketplace. Please help the user in reporting.
