### ISSUE TITLE
[Custom Dialog] Spacebar doesn't press button

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#71131]
#71116  Issue Type: <b>Bug</b>

Using native dialog it's possible to use <kbd>Spacebar</kbd> to press the buttons.

VS Code version: Code - Insiders 1.33.0-insider (966b87dd4013be1a9c06e2b8334522ec61905cc2, 2019-03-26T01:05:50.235Z)
OS version: Windows_NT x64 10.0.17763

**Comment by chrisdias** [comment]
Same on MacOS

**Comment by auchenberg** [comment]
+1 on Windows

**Comment by bpasero** [comment]
@sbatten may I ask why a fix is needed in `dialog.ts`? A `Button` already listens to the Space key, so shouldn't it just work?

https://github.com/Microsoft/vscode/blob/fcb773d1cad9d3e09688b9b1b5a6bec098c2dff3/src/vs/base/browser/ui/button/button.ts#L82

**Comment by sbatten** [comment]
@bpasero dialog was blocking the button from listening to the spacebar. the fix was to let it through.
