### ISSUE TITLE
[Custom Dialog] Shift+Tab doesn't work

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#71130]
#71116 Issue Type: <b>Bug</b> 

1. Press <kbd>Shift</kbd>+<kbd>Tab</kbd>
1. Focus is on the same button

VS Code version: Code - Insiders 1.33.0-insider (966b87dd4013be1a9c06e2b8334522ec61905cc2, 2019-03-26T01:05:50.235Z)
OS version: Windows_NT x64 10.0.17763

**Comment by weinand** [comment]
Please provide reproducible steps and make clear what you expect and what is actually happening.

**Comment by usernamehw** [comment]
Expected: Focus moves to the previous button

**Comment by chrisdias** [comment]
Same on Mac

**Comment by auchenberg** [comment]
+1 on WIndows
