### ISSUE TITLE
symlink in projects make the explorer empty

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#71148]
- VSCode Version: Version 1.33.0-insider (1.33.0-insider
- OS Version: MacOs 10.14.3

In the latest versions of the Insiders i have an empty explorer on some folder. I pint pointed it to  folders having symlinks. If i remove the symlink the explorer gets fills correctly.
Add them again and the explorer gets cleared.

It also not happen with the current Exploration build

**Comment by farfromrefug** [comment]
sorry did not want to hit enter :s

**Comment by isidorn** [comment]
Fixed in latest insiders which should be out soon.
Dup of some issue

**Comment by farfromrefug** [comment]
@isidorn thanks!
