### ISSUE TITLE
Debug: No error for missing Debugger for Chrome extension, when missing pattern

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#71146]
Testing #71074

When the `pattern` is missing from the `serverReadyAction` and there is no Debugger for Chrome extension installed, there is no error when starting to debug:

![image](https://user-images.githubusercontent.com/22350/54987936-c2f4aa80-4fb5-11e9-9ca1-27445fba8bb9.png)

**Comment by weinand** [comment]
There is a default pattern that does not trigger the action in this case.

**Comment by weinand** [comment]
This has already been fixed.
The following alert is shown in this case:
<img width="523" alt="2019-10-15_12-11-44" src="https://user-images.githubusercontent.com/1898161/66822701-0eb47480-ef45-11e9-8fbc-473330dd16a3.png">
