### ISSUE TITLE
Call Hierarchy: do not show twistie when node has no children

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#71141]
Refs: #71083 

Currently, a node that has no children still shows a twistie. I would expect that the twistie does not show so that one understands there are no further calls below.

**Comment by jrieken** [comment]
> show so that one understands there are no further calls below

For once there is technical challenge, when being (synchronously) being asked for children we don't know yet but then isn't this just like the explorer. That also shows twisties for empty folders

**Comment by bpasero** [comment]
@jrieken yeah I would argue in the explorer it somewhat makes sense because the twistie is a good indicator for the thing being a folder or not. 

I would only say a twistie should not be shown if you can have that knowledge when the node becomes visible. Otherwise it is probably not worth it.

**Comment by jrieken** [comment]
Closing as I don't have the information about children until I run the (expensive) call to resolve them. This might change with some API updates but it likely stays like that I would refer to the folder-model here...

**Comment by roblourens** [comment]
It might also look nicer if there is a dummy label like `(No children)` when I expand an empty child. The first time I saw it I thought I was waiting for data to load.
