### ISSUE TITLE
OS X Terminal cannot open

### ISSUE THREAD

**Issue by willin** [Microsoft/vscode#7114]
- VSCode Version: 1.1.1
- OS Version: os x 10.11.5

Steps to Reproduce:

1. Add User Key Binding
```json
  { 
    "key": "ctrl+shift+t", 
    "command": "workbench.action.terminal.toggleTerminal" 
  }
```
2. Trigger

```
No handler found for the command: 'workbench.action.terminal.toggleTerminal'. An extension might be missing an activation event.
```

**Comment by Tyriar** [comment]
The terminal is currently only available in the Insiders build, you can download it here code.visualstudio.com/insiders
