### ISSUE TITLE
Comments API review

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#71157]
Testing #70601

For all these points, I've run and played around with https://github.com/Microsoft/vscode-extension-samples/tree/rebornix/commentcontroller/comment-sample

1. Why is `CommentController.commentingRangeProvider` optional? When I remove that, nothing seems to work, there are no gutter actions.
2. What good is a `commentingRangeProvider` without a `emptyCommentThreadFactory`? If I comment out the example `emptyCommentThreadFactory`, the action appears in the UI yet nothing happens. Do we ever want that?
3. Shouldn't ids always be `readonly`? Eg `threadId`, `commentId`. I suggest reviewing all properties of classes and interfaces and mark those which we do not support to change once instantiated as `readonly`.
4. Related to the previous point, when creating new `CommentThread` with `createCommentThread` you also have to pass along `comments: Comment[]`. Is this necessary? If it's just util, should it be optional instead?

**Comment by rebornix** [comment]
@joaomoreno thanks for all the feedback!

> Why is CommentController.commentingRangeProvider optional? When I remove that, nothing seems to work, there are no gutter actions.

In the sample, it requires a commenting range provider as there is no existing comment. But for extensions which need to support readonly mode (displaying comments but not allowing reaction to them), an optional `commentingRangeProvider` is better than registering a provider which returns nil.

> What good is a commentingRangeProvider without a emptyCommentThreadFactory

If there is no `emptyCommentThreadFactory`, we should not show `+` sign. It probably makes more sense that `CommentingRangeProvider` and `EmptyCommentThreadFactory` are merged together.

> Shouldn't ids always be readonly?

For GH PR case, we should be able to update `CommentThread.id` as there is actually no thread id on GH.com side, we use the id of the first comment as the thread id, which can be changed. `Comment` properties can be all `readonly` as we don't monitor their changes.

> Related to the previous point, when creating new CommentThread with createCommentThread you also have to pass along comments: Comment[]

We put every non-optional properties in ctor and put `comments` in there also by purpose. When `createCommentThread` is invoked, we will create comment widget if the corresponding document is already opened. If the `comments` are set later, users get the chance to see an empty comment thread first and then a refresh (and we do allow empty comment thread for the comment thread creation case) if the communication between extension host and renderer is slow.

**Comment by joaomoreno** [comment]
> If the comments are set later, users get the chance to see an empty comment thread first and then a refresh (and we do allow empty comment thread for the comment thread creation case) if the communication between extension host and renderer is slow.

What we usually do in situations like this is to batch changes before sending them over to the renderer, which solves this issue. That way, creating the thread and then setting the comments in the same stack frame would be a single message sent to the renderer.

**Comment by rebornix** [comment]
Already out dated.
