### ISSUE TITLE
File system shouldn't support move from readonly file system provider

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71159]
Setup

- have a readonly file system provider
- select a file and move it to a writable file system provider

Observe: you get a very generic error message

![capture](https://user-images.githubusercontent.com/1931590/54993257-b37b5e80-4fc1-11e9-859c-f43067a62ed6.png)

We shouldn't allow move at all in that setup.

**Comment by bpasero** [comment]
@isidorn I would think the explorer needs to adjust for a readonly file. E.g. things like "New Folder" / "New File" should also not appear in the context menu. Do you already have an issue for that?

**Comment by isidorn** [comment]
@bpasero new file and new folder shuold be disabled for readonly resources as seen by this [context](https://github.com/Microsoft/vscode/blob/bb35a1d223c04425c73bfa7bd4ef865018f8fe4c/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L380)

I have disabled dnd when it is a move for readonly resources

**Comment by bpasero** [comment]
@isidorn ah ok good 👍
