### ISSUE TITLE
Comments: Pressing `Escape` in comment box doesn't close the comment view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#71155]
Testing #70601

1. Run https://github.com/Microsoft/vscode-extension-samples/tree/rebornix/commentcontroller/comment-sample
2. Click the `+` action in the gutter
3. Press <kbd>Escape</kbd>

The comment view doesn't close.

![image](https://user-images.githubusercontent.com/22350/54992699-369bb500-4fc0-11e9-97e3-b318be64deee.png)

**Comment by rebornix** [comment]
it seems the keybinding is only active when adding a new comment through the old api https://github.com/Microsoft/vscode/blob/fcb773d1cad9d3e09688b9b1b5a6bec098c2dff3/src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts#L461 cc @RMacfarlane
