### ISSUE TITLE
[xml] does not work with characters other than the Latin 

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#7115]
- VSCode Version: 1.1.1
- OS Version: Windows 10
Steps to Reproduce:
1. Open attached sample_utf.xml

![image](https://cloud.githubusercontent.com/assets/1981785/15735044/053b6d94-289e-11e6-9504-35bc8d9d0744.png)

[sample_utf.zip](https://github.com/Microsoft/vscode/files/294882/sample_utf.zip)

Regards, Serge

**Comment by Tyriar** [comment]
Seems relevant:

> Names and Tokens

> [4]   	NameStartChar	   ::=   	":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
> [4a]   	NameChar	   ::=   	NameStartChar | "-" | "." | [0-9] | #xB7 | [#x0300-#x036F] | [#x203F-#x2040]
> [5]   	Name	   ::=   	NameStartChar (NameChar)*
> [6]   	Names	   ::=   	Name (#x20 Name)*
> [7]   	Nmtoken	   ::=   	(NameChar)+
> [8]   	Nmtokens	   ::=   	Nmtoken (#x20 Nmtoken)*

https://www.w3.org/TR/REC-xml/#sec-common-syn

**Comment by jrieken** [comment]
![screen shot 2016-07-04 at 14 03 31](https://cloud.githubusercontent.com/assets/1794099/16559868/20e8eaa6-41f0-11e6-8de3-b0e07c6d744b.png)

Still seeing this with

```
<äddddd>
</ädddd>

<däddddd>
	
</dädddd>

```

**Comment by aeschli** [comment]
Works for me with XML
![image](https://cloud.githubusercontent.com/assets/6461412/16596427/32f1c984-42f4-11e6-8fd3-905fb8c31556.png)

Maybe you tried HTML?
![image](https://cloud.githubusercontent.com/assets/6461412/16596447/42f24016-42f4-11e6-888b-d0af70283877.png)
