### ISSUE TITLE
File system broken with unexisting sym link

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71152]
Steps:

- create a normal workspace
- create folder shared
- create folder folder
- create text files inside both folders
- create a symlink from folder/shared -> shared
- delete shared
- open the workspace

Observe: the folder is empty. It is not showing any files contained inside.

![capture](https://user-images.githubusercontent.com/1931590/54991296-ecfd9b00-4fbc-11e9-8bc1-e2f276011cd7.png)

**Comment by bpasero** [comment]
I pushed a fix that preserves our stable behaviour where we simply do not show a file/folder entry in the explorer if we cannot stat it. We could in theory show the link even though it is broken, but I feel like that is a bit too late for endgame.
