### ISSUE TITLE
Revisit symlink handling when moving across providers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#71158]
Microsoft/vscode-internalbacklog#492

Issue Type: <b>Bug</b>

- In a local folder:
```
mkdir sub
mkdir test
cd test
touch foo.txt
ln -s foo.txt bar.txt
```
- DnD `test` folder to `sub` folder.
- Observe that `bar.txt` is now a file and not a symlink anymore.

Similarly when a symlink points to a folder and the symlink is DnDed to another filesystem (tested local to remote).

VS Code version: Code - Insiders 1.33.0-insider (b9bcca2b9830df592892d63201704026c18dcbe5, 2019-03-26T08:08:11.421Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
nodefs-provider-sample|foo|0.0.1

</details>

**Comment by bpasero** [comment]
@chrmarti can you please check if this is just a missing decoration in the explorer or is the link really gone? e.g. reload the window to assert that.

**Comment by chrmarti** [comment]
I no longer see this when moving within a local folder. It only reproduces when moving the `test` folder from a local to a "remote" filesystem. 🤔

**Comment by bpasero** [comment]
First of all, this depends on https://github.com/Microsoft/vscode/issues/71204 so that we can detect and restore symlinks.

Second, I do not think it makes sense to restore symlinks that point to paths outside the data that is moved because in the target file system that might just not exist. In that case I think copying the raw data is correct.
