### ISSUE TITLE
Can't move folder to parent folder

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71153]
OS: Windows

Steps:

- workspace
- create folder `folder`
- create folder `folder\folder1`
- create file `folder\folder1\file1.txt`
- try to move folder1 to the workspace root using D&D

You get

![capture](https://user-images.githubusercontent.com/1931590/54991967-60ec7300-4fbe-11e9-954b-6410e4054c4d.png)

**Comment by dbaeumer** [comment]
Same happens when trying to move to another folder.

**Comment by dbaeumer** [comment]
Might be a problem of having a command prompt open. Couldn't reproduce anymore after closing the command prompt.

**Comment by dbaeumer** [comment]
Reopeing. I can reproduce this when moving a folder into a sym linked folder.

![capture](https://user-images.githubusercontent.com/1931590/55000580-17f2e980-4fd3-11e9-8f00-7e5ff66afbf6.png)

**Comment by dbaeumer** [comment]
shared points to folder\folder2

**Comment by bpasero** [comment]
@dbaeumer I cannot reproduce this on macOS at least. What are the full exact steps here? How did you create the links from the command line?

We possibly have an issue with not being able to detect endless recursive moves if the paths overlap due to symlink. Maybe you can see if you can reproduce this also in stable.

**Comment by dbaeumer** [comment]
![capture](https://user-images.githubusercontent.com/1931590/55029929-94092380-500b-11e9-8033-00dc36c3667f.png)

- folder3/shared points to folder/folder2.
- I created the link using mklink from an elevated cmd.exe
- move folder2 into shared.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/71160 as this behaviour is same for stable.
