### ISSUE TITLE
Running tasks with space in username fails

### ISSUE THREAD

**Issue by kjpluck** [microsoft/vscode#71154]
Issue Type: <b>Bug</b>

Updated to version 1.32.3
Previously configured tasks in tasks.json are now failing with the following error:

```
> Executing task: "C:\Users\Kevin Pluck\AppData\Roaming\npm\gulp.cmd" clean <

C:\Users\Kevin : The term 'C:\Users\Kevin' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
```

As you can see I have a space in my windows user name (I wasn't responsible for that! _Glances sideways at Dave_)  which means the task is attempting to execute Kevin, I am uncomfortable with that possibility.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.60GB (5.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
scratchpad|awe|0.1.0
graphviz-preview|EFa|1.3.1
plantuml|jeb|2.10.9
classic-asp-html|jtj|0.1.0
csharp|ms-|1.17.1

</details>

**Comment by alexr00** [comment]
I can reproduce this, but I'm not sure we changed anything here. I went back to version 1.29 (4 months old) and the issue still exists there. It is possible that the behavior of PowerShell has changed. @kjpluck can you go to your Windows Settings app -> Update & Security -> Windows Update -> View update history and see if any Feature Updates have installed recently? 

This should still work if you set `"terminal.integrated.shell.windows": "cmd.exe"` in VS Code settings or if you set
```
                   "options": {
				"shell": {
					"executable": "cmd.exe",
					"args": ["/c"]
				}
			}
```
in your task.

**Comment by alexr00** [comment]
Also @kjpluck, how recently do you recall this working?

**Comment by kjpluck** [comment]
Thank you for this.

It definitely worked the day before, I'm not sure now if it worked just before I updated VSCode though.

At home at the moment but will try your suggestion and check for PS changes UK work hours.

**Comment by jan-di** [comment]
Same Problem here, also with Gulp:
I could reproduce it with Windows Powershell v5.1/PowerShell Core v6.1 and vscode 1.33.1. Before the Update to v1.31, it certainly worked with PowerShell Core v6.1. 
When i'm manually executing the command, which is showed on the task output, with the &-Operator, it also works.

I remember that the auto detection for gulp tasks was changed in v1.31 (see #68413). So I think maybe the bug exists for longer time, but is first noticed in v1.32 due to the use of the global gulp installation since this version.
 
The workaround with cmd.exe works for me.

```json
{
  "type": "gulp",
  "task": "watch",
  "group": {
    "kind": "build",
    "isDefault": true
  },
  "problemMatcher": []
}
```

```powershell
> Executing task: "C:\Users\Jan Dittrich\AppData\Roaming\npm\gulp.cmd" watch <

C:\Users\Jan : The term 'C:\Users\Jan' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Users\Jan Dittrich\AppData\Roaming\npm\gulp.cmd watch
+ ~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\Jan:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by alexr00** [comment]
@jan-di nice catch with the global gulp change. That is why people started noticing this. The cause of the issue is that there is additional escaping of spaces needed for powershell.
