### ISSUE TITLE
Errors in large numbers of files (for ex. 5k) results in significant editor hangs

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#71165]
I don't know what the expectations are here, but I had some reports of VS Code hanging (not the extension host, but the whole editor locking up). For the one I was able to look into, it seemed to be caused by large numbers of files with errors. I'm able to repro with this extension code, which reports errors in 5,000 files (at 1ms intervals - aiming to somewhat simulate the initial analysis when opening a project):

```ts
import * as vs from 'vscode';

export function activate(context: vs.ExtensionContext) {
	const diagnostics = vs.languages.createDiagnosticCollection("foo");
	context.subscriptions.push(diagnostics);

	// Simulate finding errors in 5000 files during initial analysis.
	// Spread them out to 1-per-ms after an initial 100ms.
	for (var i = 0; i < 5000; i++) {
		let j = i;
		setTimeout(() => sendDiagnostics(diagnostics, j), 10000 + i);
	}
}

async function sendDiagnostics(diagnostics: vs.DiagnosticCollection, i: number): Promise<void> {
	const errors = Array.from({ length: 1 }, () =>
		new vs.Diagnostic(
			new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)),
			`Error ${i}`,
			vs.DiagnosticSeverity.Error,
		)
	);
	diagnostics.set(vs.Uri.file(`/tmp/test/file/${i}.foo`), errors);
}

export function deactivate() { }
```

A CPU profile suggests that `updateBadge` is being called a lot and is taking ~300ms per call because of some sorting (which is probably unnecessary since it only uses the count?):

![Screenshot 2019-03-26 at 11 40 29 am](https://user-images.githubusercontent.com/1078012/54994924-64332f00-4fbd-11e9-8a69-c060cea38c02.png)

![Screenshot 2019-03-26 at 11 48 25 am](https://user-images.githubusercontent.com/1078012/54994964-8331c100-4fbd-11e9-836d-1f45844484dc.png)

I don't know if 5,000 files with errors is something you think is reasonable, but if you're looking for places you might be able to optimise, this might be one :-)

**Comment by jrieken** [comment]
@sandy081 looks like [`get resourceMarkers`](https://github.com/Microsoft/vscode/blob/46fa864299966f6c1284b4902dd5e115baaf907c/src/vs/workbench/contrib/markers/browser/markersModel.ts#L128-L130) always sorts even though the count is only needed. Also, you should consider looking into using [`IMarkerService#getStatistics`](https://github.com/Microsoft/vscode/blob/46fa864299966f6c1284b4902dd5e115baaf907c/src/vs/platform/markers/common/markers.ts#L15) which is incrementally updated

**Comment by sandy081** [comment]
Good catch @DanTup

**Comment by DanTup** [comment]
Great, thanks for the quick turnaround! I'll do some testing with insiders tomorrow and see if I can get the original users to verify it too.

**Comment by DanTup** [comment]
We did some testing in Insiders, and Code remains completely responsive (both in my repro and for the original issue reported to me). It's made a huge difference - thanks!

**Comment by jrieken** [comment]
🐎

**Comment by DanTup** [comment]
That racing horse looks much faster on GitHub than it did in Gmail! 😄

![Screenshot 2019-03-27 at 11 49 32 am](https://user-images.githubusercontent.com/1078012/55073763-762cd480-5086-11e9-8395-e5e236012843.png)

**Comment by jrieken** [comment]
haha

**Comment by DanTup** [comment]
I'm not sure if it's related, or how I got here - but I just noticed this in Insiders:

<img width="1317" alt="Screenshot 2019-03-27 at 3 14 21 pm" src="https://user-images.githubusercontent.com/1078012/55088134-1bee3c80-50a3-11e9-8fe2-b079842e8c04.png">

Badge says 18, but there aren't any errors (and as far as I can tell, no filters).

**Comment by sandy081** [comment]
Yeah it is related to the fix I did. I should not consider unknown markers.
