### ISSUE TITLE
Better ux clarification on setting files hierarchy

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#71161]
From @isidorn 

I suggest we use some UX to help the user figure the settings hierarchy

- Consider adding some affordance between tabs like > to indicate the hierarchy. 

Be creative in some other way to help make this easier for the user. We have the whole settings ux

**Comment by roblourens** [comment]
Is this really necessary? I don't think any user has ever complained about this.

**Comment by isidorn** [comment]
Because now we have 2. In the future there might be more.

**Comment by sandy081** [comment]
To remind, It's not just two, we also have folder settings.
