### ISSUE TITLE
Intellisense types resolve in Typescript files not working

### ISSUE THREAD

**Issue by deathcomes84** [Microsoft/vscode#71166]
- VSCode Version: 1.32
- OS Version: Windows 10

Steps to Reproduce:

1. Create a .ts file with this code
![image](https://user-images.githubusercontent.com/28006214/54996538-40c6af00-4fd2-11e9-898e-fe0022bcd8f8.png)
2. Now add some documentation
![image](https://user-images.githubusercontent.com/28006214/54996622-78cdf200-4fd2-11e9-93ef-a993a7ad101a.png)
3. Now try to hover the mouse over "MyFunction" and it shows this inside the tooltip
![image](https://user-images.githubusercontent.com/28006214/54996708-ad41ae00-4fd2-11e9-80fb-6e5f84f5ec7f.png)
4. Intellisense does not recognizes the {string} type of neither the `@param` parameter nor the `@returns`

Does this issue occur when all extensions are disabled?: Yes

Am i doing something wrong?

Edit: Sorry for the bad English
Edit2: Here is the text of my code
`export interface MyInterface`
`{`
`/**`
`* @param {string} parameter`
`* @returns {Promise<string>}`
`* @memberof MyInterface`
`*/`
`MyFunction(parameter: string): Promise<string>;`
`}`

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by deathcomes84** [comment]
Is it not replicable like this? I tested it with this exact steps of code.

**Comment by mjbvz** [comment]
Share text. I'm not typing this out

**Comment by deathcomes84** [comment]
Ok here it is

`export interface MyInterface`
`{`
`/**`
`* @param {string} parameter`
`* @returns {Promise<string>}`
`* @memberof MyInterface`
`*/`
`MyFunction(parameter: string): Promise<string>;`
`}`

**Comment by mjbvz** [comment]
Thanks. 

The correct types from the source code are being shown in the top section of the hover. In general you should not use jsdoc types in TypeScript files as they are redundant and TS ignores them
