### ISSUE TITLE
Improve error messages presented to the user for native node.js errors

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#71160]
Microsoft/vscode-internalbacklog#492

Issue Type: <b>Bug</b>

The target folder is a symlink to a subfolder of the moved folder (because you asked for it!):
```
mkdir -p foo1/bar1
ln -s foo1/bar1 bar2
```

Then DnD `foo1` into `bar2`. 💥 

VS Code version: Code - Insiders 1.33.0-insider (b9bcca2b9830df592892d63201704026c18dcbe5, 2019-03-26T08:08:11.421Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
nodefs-provider-sample|foo|0.0.1

</details>

**Comment by chrmarti** [comment]
Somewhat similarly: Copying in the above steps instead of moving will fail with `ENAMETOOLONG`.

**Comment by bpasero** [comment]
I can reproduce this already in stable and think this is not bad behaviour, just the raw error from node.js that is presented is not nice for the user (but I never heard complaints so far).

**Comment by chrmarti** [comment]
Fine with me.

**Comment by bpasero** [comment]
We can leave this open as debt item, we could still try to not show raw node.js errors to the user.

**Comment by bpasero** [comment]
I decided to do this, e.g. an error now shows as this:

![image](https://user-images.githubusercontent.com/900690/55066102-56dd7980-507d-11e9-89b6-329568066daf.png)

I still think the original node.js error is useful.
