### ISSUE TITLE
能不能新增配置的导入导出功能？

### ISSUE THREAD

**Issue by pengjianxun** [Microsoft/vscode#71167]
我想很多人可能会像我一样，在不同的电脑上都需要使用vs code，但是目前好像没有很好的方式能让我在重新安装vscode的时候同步之前的配置和设置，所以我很希望后面的版本中能支持这个功能，毕竟所有的开发者都不想把同样的活干两遍

**Comment by jrieken** [comment]
Please file issues in English. Thanks!
