### ISSUE TITLE
Folder not refreshing correctly when dropping file into linked folders

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#71174]
Steps to reproduce:

- dropped a file onto the shared folder which is a symlink to folder2
- appreaded under folder2 but not under shared

![capture](https://user-images.githubusercontent.com/1931590/55002376-c9dfe500-4fd6-11e9-9839-b004e98df811.png)

**Comment by dbaeumer** [comment]
This was only reproducibale when moving a file from another file provider. Didn't happen when moving files inside the same provider.

**Comment by dbaeumer** [comment]
Refreshing made the file appear.

**Comment by dbaeumer** [comment]
Actually it does reproduce on a local file system as well when having multiple workspace folders. Even deleting the file doesn't refresh it in both places.

![capture](https://user-images.githubusercontent.com/1931590/55002741-699d7300-4fd7-11e9-8496-be880a0283fc.png)

**Comment by bpasero** [comment]
This could be an explorer issue @isidorn

**Comment by isidorn** [comment]
Yeah might be. What are the exact steps for the local file sistem.
Are there any errors in the console? If not (then it is possible a missing file event)

**Comment by dbaeumer** [comment]
I had to locel workspace folders. Move from one to the other. On the target I droped the file into a folder that was symlinked to another folder. Shared in the above screen shot points to folder2

**Comment by bpasero** [comment]
@dbaeumer I cannot reproduce this easily. I have a simple workspace like this:
* `folder/folder2`
* `folder3/shared` pointing to `folder/folder2`
* then I drop a file from root into shared and it shows up correctly in both folders (also delete works)

![grid-tw](https://user-images.githubusercontent.com/900690/55066916-0cf59300-507f-11e9-90a0-bcbb89d92d92.gif)

What are you doing differently? 

PS: I would appreciate steps that involve setting up the workspace to reproduce, thanks.

**Comment by bpasero** [comment]
@dbaeumer oh I can reproduce if I move the file out from the original folder, not the shared one. Is that maybe what you did? If so I suspect simply issues with the file watcher not reporting this through symlinks.

**Comment by dbaeumer** [comment]
@bpasero I actually move the file from a second workspace folder which was also local.

**Comment by bpasero** [comment]
Yeah that still does not reproduce for me unless I drop into the real folder and not the symlinked one. I think this is a file watcher issue and no regression I introduced (besides, all I changed was the copy operation not the file watcher - and that one seems to succeed).
