### ISSUE TITLE
Format actions overkill in context menu

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#71170]
Refs: #71093

1. Have prettier, beautify installed.
2. Open typescript file
3. Select something -> context menu

Notice there are 4 commands regarding formating. Even though I understand the differences I think this is overkill. Instead of that I suggest to just show 2 commands in the context menu, and still show all 4 in the command palette.
If you really want to force the user to disable some formatter then I suggest to only show the "Format With..." commands.

![Screenshot 2019-03-26 at 14 40 09](https://user-images.githubusercontent.com/1926584/55001567-2b9f4f80-4fd5-11e9-96f4-f40a6ffdcf0f.png)

**Comment by jrieken** [comment]
> If you really want to force the user to disable some formatter then I suggest to only show the "Format With..." commands.

We are not going in circles here. That's exactly what we had three days ago and people didn't like it. I think having a selection, multiple formatters, and the context menu open happens seldom and when it happens then it represents that state of your installation.

**Comment by octref** [comment]
> If you really want to force the user to disable some formatter

Once you have only one formatter left, the context menu, the command palette and the status bar all get cleaner. That's a well designed incentive for users to only enable 1 formatter for a filetype 👍
