### ISSUE TITLE
Comment: Sample contributed commands fail

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#71172]
Testing #70601

1. Run https://github.com/Microsoft/vscode-extension-samples/tree/rebornix/commentcontroller/comment-sample
2. Run any of the two contributed commands from the command palette

None of them work

![screenshot yHY7cP](https://user-images.githubusercontent.com/22350/55002043-2b538400-4fd6-11e9-8f9b-eb4e67037d9b.png)

**Comment by joaomoreno** [comment]
Maybe we should just hide them from the command palette?

**Comment by rebornix** [comment]
They should be hidden from the command palette, like other commands we register for tree items, scm, etc.

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode-extension-samples/pull/160/commits/b81c1c9d4ee012cca88a3023891b9182d3f63732
