### ISSUE TITLE
Custom Task: reuse massge offset incorrect

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71178]
Tests: https://github.com/Microsoft/vscode/issues/71089

Custom task that writes to the terminal renderer without new line. The Resue message looks like this:

![capture](https://user-images.githubusercontent.com/1931590/55004097-e03b7000-4fd9-11e9-841b-6d7b7769e488.png)

**Comment by alexr00** [comment]
Not dependent on newline. I added a newline char to the end of `"Hello from a custom task"` and it still gets that offset.

**Comment by alexr00** [comment]
@Tyriar I debug to here and the string being sent to xterm is `\n\x1b[1mTerminal will be reused by tasks, press any key to close it.\x1b[0m` https://github.com/Microsoft/vscode/blob/5688d00dd592a165530a82945c4ade4dad6b01e7/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L957

**Comment by Tyriar** [comment]
Reported and fixed this before I saw this one 😄 https://github.com/Microsoft/vscode/issues/71230

`\n` moves the cursor down 1 line, `\r` moves it to the start of the line.
