### ISSUE TITLE
debugWithChrome is weird

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71176]
re https://github.com/Microsoft/vscode/issues/71074

I find it rather weird that vscode as a product suggests to configure something that requires an extension. Isn't the logical separation of concerns that the chrome-debug-extension contributes that configuration value?

<img width="814" alt="Screenshot 2019-03-26 at 15 09 04" src="https://user-images.githubusercontent.com/1794099/55003707-2cd27b80-4fd9-11e9-8bb6-c512884a2e91.png">

**Comment by weinand** [comment]
yes, fully agree.
/duplicate #69339
