### ISSUE TITLE
Link decoration remembered when replaced with actual file

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#71175]
Microsoft/vscode-internalbacklog#492

Issue Type: <b>Bug</b>

In some folder:
```
touch test1.txt
ln -s test1.txt test2.txt
rm test2.txt
touch test2.txt
```

`test2.txt` will now again show a symlink decoration. 🐛 

VS Code version: Code - Insiders 1.33.0-insider (b9bcca2b9830df592892d63201704026c18dcbe5, 2019-03-26T08:08:11.421Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
nodefs-provider-sample|foo|0.0.1

</details>

**Comment by bpasero** [comment]
This could be decoration service too @isidorn

**Comment by isidorn** [comment]
Here is a good places to put a breakpoint
https://github.com/Microsoft/vscode/blob/a3198370c891507b4fdbf4e113c18e0db49883ce/src/vs/workbench/contrib/files/browser/views/explorerDecorationsProvider.ts#L29
Explorer service should theoreticaly send out an event (as a reaction to the file service event) that the item changed and the decoration needs to be provided again.

**Comment by bpasero** [comment]
I can reproduce and think this is an issue with the explorer because after a window reload this decoration is gone.

**Comment by isidorn** [comment]
Yes, the issue here is that the decorationProvider does not refresh properly on file events.
