### ISSUE TITLE
Comments: Strange new comment thread behavior

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#71171]
Testing #70601

1. Run https://github.com/Microsoft/vscode-extension-samples/tree/rebornix/commentcontroller/comment-sample
2. Open a file
3. Click the gutter to start a comment
4. Close the comment view

There's a couple of things that are weird. I'm not sure how much of this is related to the API vs. the actual sample.

- The gutter marker is still there, as if the thread wasn't disposed once I closed it, since I didn't input anything. Does the extension API informs the API user that the comment view was closed, giving it a chance to dispose the thread?
- When I switch to another file and back, the comment pops up.

![Peek 2019-03-26 14-34](https://user-images.githubusercontent.com/22350/55001146-3f968180-4fd4-11e9-9d6e-1522195f22ec.gif)

**Comment by rebornix** [comment]
We introduced `deleteCommand` for a comment thread, which will be called when users click Close button on the Comment Widget when it's a temporary one.

We should use chevron icons for Comment Thread expansion/collapse and use the Close button for deleting Comment Thread.

**Comment by rebornix** [comment]
Already outdated.
