### ISSUE TITLE
Custom tasks can't be customized

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71179]
Tests https://github.com/Microsoft/vscode/issues/71089

- contribute a custom task as described in the test plan item
- Execute Terminal > Customize Task
- select the contributed task

Observe: the tasks.json opens but the task is not inserted. You get

```ts
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558 
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"problemMatcher": []
		}
	]
}
```

**Comment by alexr00** [comment]
You can manually customize them, but it looks like the Customize Task command doesn't work for them. Good find.
