### ISSUE TITLE
Call graph: only show source location paths for external callers/callees

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#71188]
testing #71083:

In your sample all callers and callees are located in a single source file. In this case it is very noisy to duplicate the same source path for each node in the call graph:

![2019-03-26_16-49-10](https://user-images.githubusercontent.com/1898161/55012670-0ff17480-4fe8-11e9-9bee-730cdf92abe6.png)

I suggest to only show paths for nodes that are outside of the current source file. So in the sample no path would show up.

In a more realistic scenario I could easily see with this approach what part of the call hierarchy is local in the source file and what is external.

**Comment by jrieken** [comment]
The path is actually just a fallback. The api defines `CallHierarchyItem#detail` and when that's missing it falls back to the filename. The idea is that detail is something like the signature of fully qualified name. 

I would just nuke that fallback, showing the symbol name without the filename then.
