### ISSUE TITLE
vscode version is not working on RHEL 6.7

### ISSUE THREAD

**Issue by Uma19** [Microsoft/vscode#71186]
- VSCode Version: Latest feb 2019 version
- OS Version: Linux RHEL 6.7

While installing using rpm command, it gives following error

- libstdc++.so.6(GLIBCXX_3.4.14)(64bit) is needed by code-1.20.1-1518536126.el7.x86_64
- libstdc++.so.6(GLIBCXX_3.4.15)(64bit) is needed by code-1.20.1-1518536126.el7.x86_64
- libsecret-1.so.0()(64bit) is needed by code-1.20.1-1518536126.el7.x86_64

Reason : what I can see is linux 6.7 version contains below things
- GLIBCXX version 3.4.13
- GLIBC version 2.12

And as per basic requirement mentioned by vscode is on Linux 7 version it needs
- GLIBCXX version 3.4.15 or later
- GLIBC version 2.15 or later

**so then which version of vscode is suitable to get it installed successfully on RHEL 6.7 platform, as its difficult to get latest RHEL version to get installed**

**Comment by Tyriar** [comment]
Sorry, we don't support RHEL < 7 https://code.visualstudio.com/docs/supporting/requirements

**Comment by Uma19** [comment]
Thanks for your quick response Tyriar
