### ISSUE TITLE
Explorer doesn't open folder when it contains a broken symlink

### ISSUE THREAD

**Issue by juristr** [Microsoft/vscode#71180]
- VSCode Version: Version 1.33.0-insider (1.33.0-insider)
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Create a folder `mkdir ~/test`
2. Inside a VSCode workspace, create a folder `src` and create some empty files just to have some content in there. 
3. Inside the `src` folder create a symlink (via the shell) to the `test` folder (i.e. `ln -s ~/testdir testdir`)
4. Refresh the VSCode Explorer window and the symlinked folder inside `src` should be properly shown.
5. Now delete the`~/test` folder where the symlink points to, i.e. we have a broken symlink in `src/`.

The result is that in VSCode you're no more able to open `src` and view its contents.

Does this issue occur when all extensions are disabled?: Yes

**Comment by juristr** [comment]
Just recognized it could be a dup of #71148. Will test that once the new version of insiders gets released and in case I'll close this issue

**Comment by isidorn** [comment]
Closing as duplicate for now, please let us know if this still happens with newer insiders and we can reopen
