### ISSUE TITLE
Specify snippet TM scope

### ISSUE THREAD

**Issue by tecosaur** [Microsoft/vscode#71187]
I spend a lot of time writing LaTeX documents in VS Code. As a result, I have quite a few snippets to improve my workflow.

One frequent annoyance is that I can't specify short snippets for math that come up in text as well without significant irritation / false positives.

It would be very handy if I could specify the TM scope `support.class.math.latex`. I am aware this is possible for an extension, but I would like to be able to do this from `keybindings.json` where user snippets _should_ reside.

**Comment by jrieken** [comment]
> I am aware this is possible for an extension, but I would like to be able to do this from keybindings.json where user snippets should reside.

A scope like `support.class.math.latex` cannot be defined statically anywhere, VS Code doesn't have this information, e.g. the tokeniser information isn't sufficient for this. This can only be achieved with an extension and that's the design of things

**Comment by Gama11** [comment]
I believe @tecosaur was talking about using TM scopes that already exist to make a user-snippet only appear in a specific context, not declaring new scopes.

**Comment by jrieken** [comment]
Let's let him clarify but `support.class.math.latex` isn't a language identifier that I know and that's the only scopes vscode supports

**Comment by Gama11** [comment]
[It's a TmLanguage scope](https://i.imgur.com/EBNBgWN.png). Not sure I follow, shouldn't it be easy for VSCode to check if the completion position has a specific TmLanguage scope, considering it does syntax highlighting based on them as well?

**Comment by jrieken** [comment]
> Not sure I follow, shouldn't it be easy for VSCode to check if the completion position has a specific TmLanguage scope,

No we don't have that information. That's what I tried to say here: https://github.com/Microsoft/vscode/issues/71187#issuecomment-476750027

**Comment by tecosaur** [comment]
@jrieken to clarify as requested, this issue is regarding using TM scopes that already exist to make a user-snippet only appear in a specific context, not declaring new scopes.
The identifier `support.class.math.latex` is provided by the LaTeX-Workshop extension.

This may be as designed, however in latex documents, you get large math environments, in which you may want completely different behaviour to the rest of the document.

E.g. you may want `cr`(for cube root) to expand to `\sqrt[3]{}`, but obviously this would be annoying in a non-math context.

I find not having enough flexibility with snippets has a significant effect on the speed at which I can write LaTeX (this is only a part of that greater issue), and is one of the few deficiencies I have felt in VS Code.

**Comment by jrieken** [comment]
Yeah, VS Code doesn't support TM scope names because that information doesn't survive.
