### ISSUE TITLE
Deleteing .vscode folder prints exceptions to log

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#71181]
Not sure what actually caused it but the developer tools poped up after I deleted tyhe .vscode folder

![capture](https://user-images.githubusercontent.com/1931590/55004692-f5fd6500-4fda-11e9-9e92-16ba90f07d46.png)

**Comment by dbaeumer** [comment]
Needed to refresh to get out of this.

**Comment by bpasero** [comment]
An electron upstream issue that we need to wait for a new Electron version for. Probably not for this milestone though.

**Comment by bpasero** [comment]
Actually I want to see how easily this reproduces.

**Comment by bpasero** [comment]
I cannot reproduce this, @dbaeumer can you?

Anyway this is fixed upstream with https://github.com/electron/node/pull/97
