### ISSUE TITLE
Explorer color decoration sometimes doesn't consider .gitignore file

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#71189]
## Synopsis

Many times, Explorer in Visual Studio Code doesn't dim files/folders mentioned in .gitignore file.

This issue occurs randomly. Sometimes after opening a solution/folder, the corresponding items correctly appear dimmed in Explorer, sometimes the exactly same files don't.

## VSCode/OS Version

![image](https://user-images.githubusercontent.com/9283914/55012949-7ececd80-4fe8-11e9-9dea-ab4960936104.png)

## Screenshot

![image](https://user-images.githubusercontent.com/9283914/55012916-72e30b80-4fe8-11e9-8949-b878596ae697.png)

Does this issue occur when all extensions are disabled?
- [x] Yes
- [ ] No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/70963
