### ISSUE TITLE
extensionDependencies Not Installing, Blocking Extension Activation

### ISSUE THREAD

**Issue by coltonoscopy** [Microsoft/vscode#71194]
- VSCode Version: 1.32.3
- OS Version: macOS 10.14

Goal with this extension is to have the CPP and Python extensions, as dependencies, install before the extension itself is activated/installed. The docs seem to suggest this would work just by defining `extensionDependencies` in the `project.json`, which doesn't seem to be the case (per https://code.visualstudio.com/api/references/extension-manifest).

Steps to Reproduce:

1. Create any simple extension, boilerplate is fine.
2. Define `extensionDependencies` in the extension's `project.json`; for me, I defined:

```
"extensionDependencies": [
		"ms-vccode.cpptools",
		"ms-python.python"
	]
```

3. The following output is returned:

```
Cannot activate extension 'my-extension' because it depends on extension 'ms-vccode.cpptools', which is not installed or disabled. Please install or enable 'ms-vccode.cpptools' and reload the window.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@coltonoscopy When did you do step 2? Are you testing your extension by running the `Launch Extension`?

**Comment by coltonoscopy** [comment]
@sandy081 using `F5` to test running the extension; is this equivalent?

**Comment by sandy081** [comment]
Yes. We do not auto install when you are testing your extension. Extension dependencies are installed automatically when the user is installing your extension. When you are testing your extension, you have to install the dependencies manually.

**Comment by coltonoscopy** [comment]
@sandy081 what's the recommended way to test this then? e.g., we want to download the C/C++ extension and ideally disable any popups that it generates when it installs (if this is even possible).

**Comment by sandy081** [comment]
You have to install the dependencies manually for now. In the new release (that comes out next week) there is a command available to install all missing dependencies.

**Comment by coltonoscopy** [comment]
@sandy081 is this command accessible via an API so it can be triggered on extension install?

**Comment by sandy081** [comment]
@coltonoscopy There is no need for it when an extension is installed because VS Code makes sure dependencies are also installed. But in your case, you are testing the extension by launching it (not installing it) and hence deps are not installed.
