### ISSUE TITLE
Wrong pause icon shown on window's first debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#71198]
- Reload the window
- Start a debug session
- Don't hit a breakpoint
- See dimmed pause button:

![image](https://user-images.githubusercontent.com/323878/55019034-57a8d980-4fb1-11e9-981f-1bc8a5edee5a.png)

- Hit a breakpoint, resume
- Now it's correct and will be for the rest of the window's lifespan: 

![image](https://user-images.githubusercontent.com/323878/55019071-67c0b900-4fb1-11e9-98a3-fcb14f31b9bf.png)

**Comment by isidorn** [comment]
Great catch.
This also revelaed that pause action was not really working
