### ISSUE TITLE
Disabling Typescript validation also misses Javascript validation

### ISSUE THREAD

**Issue by holden-caulfield** [Microsoft/vscode#71199]
- VSCode Version: 1.32.3 (1.32.3)
- OS Version: MacOS 10.14.3 

Steps to Reproduce:

I have a project on which I'm using flow. When I write type definitions on my files I get the `'type aliases' can only be used in a .ts file. (ts8008)` validation.

I would expect that validation goes away if I uncheck `typescript.validate.enabled` on the settings, however it only goes away if I uncheck `javascript.validate.enabled`, which in turn makes me lose some very useful validations, for example declaration of variables that are never used, etc.

Expected behavior would be to either: 
- make ts8008 enable/disable based on `typescript.validate.enabled` OR
- have a specific setting to enable/disable ts8008 (so I could uncheck that but still have `javascript.validate.enabled`)

**Comment by mjbvz** [comment]
VS Code does not ship with built-in Flow support. To get proper flow support, install the [flow extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) and [follow these instructions](https://github.com/flowtype/flow-for-vscode#setup)

**Comment by holden-caulfield** [comment]
@mjbvz my problem is not with flow support, I installed the plugins and that is working fine. My problem is I need to disable the Typescript validation (because it would complain about the flow syntax) but I'd like to keep the validation on unused variables and other validations that coming from the javascript validation, which are very useful.

In other words, my request is why ts8008 depends on the `javascript.enabled` setting when IMHO it clearly should depend on the `typescript.enabled` setting. Even the prefix of the rule is `ts` :P. 

I think there are clear use cases (like mine, or every other person using flow instead of typescript, but may be others not necessarily using flow and needing the same thing) on which you want to disable ts8008 together with the other typescript validations but you DO want to keep all the actual javascript (not typescript related) validations. It just seems ts8008 is on the wrong bucket here.

**Comment by blanchma** [comment]
Happening to me too. Please, fix this.
