### ISSUE TITLE
Port the excellent Notebook support from Azure Data Studio

### ISSUE THREAD

**Issue by chojrak11** [microsoft/vscode#71192]
Last version of Azure Data Studio added excellent integrated support for notebooks - they handle Python, Spark, PySpark and SQL notebooks. There's "File->New Notebook" command and everything works fantastic.

I'd like this to be ported to VSCode. Hope that in the future we can have also PowerShell, C#, bash and other notebooks. This is indispensable tool for education, presentations and demos, among others.

**Comment by gramster** [comment]
Note that we do have a data science/notebook-y experience in the Python extension.

**Comment by chojrak11** [comment]
Yes, thank you. I've tried it, but it pales in comparison to this support in ADS. Here you have to import the notebook, then work with it then export it. It has the following major drawbacks:
- it does not preserve data and images, which is one of the best features of notebooks; you needn't have access to the data that the notebook uses, yet the charts and tables that were previously rendered are still there, so you can show them or send the notebook to interested party,
- it causes general nuisance when additional actions are required when working, i.e. import then export,
- it does not support anything but Python. In case of ADS I was stunned when I saw SQL notebook support. It'll draw my presentations to the next level - and here also the data is remembered in notebook, so you don't need to be connected to data source to tell the story and show the queries and the data.

I think it's worth porting and developing further. Being able to mix Markdown, media and live code is a tremendous value.

**Comment by chojrak11** [comment]
I would like to expand this proposal further. After working with notebooks for a while I'd suggest ability to have different languages in one notebook. For example:
* one cell to execute Python code
* then markdown cell
* then another cell with PowerShell command
* then markdown cell with comments/description
* then another one with SQL code
* then markdown cell with comments/description
* then another one with Node.js code
* and so on...

I think that would need extending ipynb format, and would potentially consume a lot of memory during runtime (due to different kernels running at the same time), but still I'd say such a tool would be invaluable for a lot of use cases, including automation. It's a multi-language shell on steroids.

This kind of extended notebook format could be fully backward-compatible, with defined behaviour on what to do when it contains unsupported cells: ignore them or don't execute anything at all.

**Comment by a8775** [comment]
It would be great to support https://notebooks.azure.com (https://github.com/microsoft/AzureNotebooks) in a way remote extension works.
