### ISSUE TITLE
call hierarchy: double clicking inside Peek has no effect

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#71193]
testing #71083:

double clicking on text in the Peek has no effect: it does not bring me anywhere.

**Comment by jrieken** [comment]
works for me...

![Mar-26-2019 18-10-04](https://user-images.githubusercontent.com/1794099/55018087-66fc4700-4ff2-11e9-83af-f625c4667740.gif)

**Comment by weinand** [comment]
arggh. Reloading VS Code fixed the issue for me.
