### ISSUE TITLE
"editor.gotoLocation.many": "reveal"`: reveals second entry

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#71195]
Testing #71087

Version: 1.33.0-insider
Commit: b9bcca2b9830df592892d63201704026c18dcbe5
Date: 2019-03-26T08:08:33.302Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

The description of  `"editor.gotoLocation.many": "reveal"` says that this would reveal the first entry. It looks like it is the second.

- set `"editor.gotoLocation.many": "peek"`
- in the vscode repo, open `workbenchThemeService.ts`, set cursor at line 95, `IExtensionService`.
- Use `Goto Definition` from context menu
`export const IExtensionService = createDecorator<IExtensionService>('extensionService');` is first entry

- set `"editor.gotoLocation.many": "reveal"`
- Use `Goto Definition` from context menu
- reveals `export interface IExtensionService`

**Comment by jrieken** [comment]
Well, `export const IExtensionService = createDecorator<IExtensionService>('extensionService');` is the first entry but not the selected one... The logic is that the 'nearest' definition is selected and that's what we pick when `reveal` is used. 

However, the nearest-logic seems flawed when changing files and there were also discussions about not doing this when having definitions that we should just use the provider sorting...

**Comment by aeschli** [comment]
Behaviour is fine for me. Just fix the description to e.g.  'Reveal the primary result and ignore others
