### ISSUE TITLE
Provide a way for an extension to open a README file after it gets installed

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#712]
I'd like to be able to show the user a README.md file with some helpful documentation when they install the PowerShell extension.  Could we add a field to package.json like "postInstallDocumentation" (or a better name) which will be loaded after the extension is installed and the window is reloaded?  This would be helpful for guiding users to settings they may be interested in or a feature walkthrough to help them get started.

**Comment by daviwil** [comment]
Bonus points if the Markdown previewer is invoked automatically if the README has a .md extension :)

**Comment by joaomoreno** [comment]
Merging with #637.
