### ISSUE TITLE
File Provider: open() should indicate if it is for reading or writing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#71200]
Currently there is no way for a file based implementation to know if the `open()` call is to read a file or writing to it. I think it would be best to add related options to it. In node.js jargon this is called [`flags`](https://nodejs.org/docs/v10.2.0/api/fs.html#fs_file_system_flags). 

Currently I just use `w` if create: true and `r` otherwise.

I guess this has an impact on (proposed) API too.

**Comment by jrieken** [comment]
merging this into #41985
