### ISSUE TITLE
Selecting child select parent

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71205]
re #71063 

* use sample from https://github.com/Microsoft/vscode/issues/71063#issuecomment-476669886
* start, child process 3 is selected
* open drop down select child process 2
* :bug: cluster is selected

![Mar-26-2019 18-56-02](https://user-images.githubusercontent.com/1794099/55021322-d5440800-4ff8-11e9-8fd2-9c1dcb9abb45.gif)

**Comment by gjsjohnmurray** [comment]
Seems similar to what @weinand noted in https://github.com/Microsoft/vscode/issues/71183#issuecomment-476674224
