### ISSUE TITLE
Expand more values for editor.suggest.filteredTypes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#71208]
Testing https://github.com/Microsoft/vscode/issues/71084

<img width="245" alt="image" src="https://user-images.githubusercontent.com/35271042/55022008-f1bf5080-4fb6-11e9-9b8d-ba3d89f6bfa0.png">

When expanding `editor.suggest.filteredTypes` only `keyword` is expanded. We should expand more values (more common ones) to reduce the amount of typing required (it's easier to delete than to type). We do this with `editor.quickSuggestions`:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/35271042/55021969-e66c2500-4fb6-11e9-9ff4-5a07d8246fa6.png">

**Comment by jrieken** [comment]
I wouldn't know more than adding `snippet` (for which we have already a different, older, setting). For quick suggestions things are easy because only three values exists, for suggestions many exist
