### ISSUE TITLE
AnalyticGear

### ISSUE THREAD

**Issue by maristhek** [Microsoft/vscode#71209]
Issue Type: <b>Bug</b>

I created a simple node-express-pug web page.  Using the Azure App Service it was published to Azure.  All steps in the process were successfully completed and I received a confirmation in the output pane.
Entering the published site url in the browser a splash page pops up with a message stating that my app is up and running with two buttons :
Deployment Center for ready code and Quickstart to create the app. 
Clicking Deployment Center redirects to a page showing a 403 error stating that the app has stopped.  However, on the Azure Portal dashboard page it shows that the app is running.

Please advise.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (22.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-wasm|dts|1.2.1
vsc-material-theme|Equ|2.8.2
vscode-azureappservice|ms-|0.13.0
azure-account|ms-|0.8.0
cpptools|ms-|0.22.1
csharp|ms-|1.18.0

(6 theme extensions excluded)

</details>
.

**Comment by weinand** [comment]
I do not see that this is related to VS Code.

**Comment by maristhek** [comment]
Thanks for your help.
