### ISSUE TITLE
Debugging error : path not found

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#71202]
@MagixInTheAir commented on [Tue Mar 26 2019](https://github.com/Microsoft/vscode-python/issues/4917)

Here is the full console output when trying to debug a simple python program:

generated command : D:\Chris\Documents\MEGA\IPSA\Aéro 3\Quadrature & EDO\MP>`cd "d:\Chris\Documents\MEGA\IPSA\Aéro 3\Quadrature & EDO\MP" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && "C:\Users\Chris de Claverie\AppData\Local\Programs\Python\Python37\python.exe" "c:\Users\Chris de Claverie\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py" --default --client --host localhost --port 63937 "d:\Chris\Documents\MEGA\IPSA\Aéro 3\Quadrature & EDO\MP\ex7.py" "`

Output : `Le chemin d’accès spécifié est introuvable.`

Translated from french, the error at the bottom says the specified path cannot be accessed. I presume this comes from the path having both special characters (`é` and `&`) and spaces.

**Comment by DonJayamanne** [comment]
Not an extension issue, as the commands are sent to VSC via the debugger protocol, and VSC builds the commands and sends them to the terminal.

**Comment by weinand** [comment]
@DonJayamanne How does your launch config look like?

**Comment by connor4312** [comment]
Potentially related: https://github.com/microsoft/vscode/issues/71917

**Comment by DonJayamanne** [comment]
Sorry, no idea.
This was reported by a user & thats over a year ago. Not sure if it still replicates.
Sorry not much help here.

**Comment by connor4312** [comment]
I tried to repro the linked issue and wasn't able to --  nor this one.

![](https://memes.peet.io/img/20-11-b462743e-b867-4920-9828-d2de302f46c7.png) (ignore all the environment variable junk that js-debug needs to set)

Both are from April-March last year, so I will close this as a tentative dupe. @pwnorbitals please comment on #71917 if you still run into this in recent versions of VS Code.
