### ISSUE TITLE
Intellisense comments tooltip does not support Chinese character display

### ISSUE THREAD

**Issue by lishali12345** [Microsoft/vscode#7120]
- VSCode Version:Version 1.1.1 (1.1.1)
- OS Version: OSX EI Capitan Version 10.11.5

Steps to Reproduce:

1. 
![Chinese character display correctly in editor](https://cloud.githubusercontent.com/assets/170981/15736555/235527fe-28d3-11e6-8497-e9bb255c509c.png)

2. 
![Chinese character display not correctly in tooltip](https://cloud.githubusercontent.com/assets/170981/15736618/7c870216-28d3-11e6-8589-b3a4ce694667.jpg)

The Chinese character in the second screen shot display like "??????". Please let me know If I can do any config to make this right, thanks a lot.

**Comment by joaomoreno** [comment]
@jrieken This is hover. And clearly the div in the hover is able to render chinese characters. Shouldn't this be forwarded to the csharp guys?

**Comment by jrieken** [comment]
I see. Thanks

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#573
