### ISSUE TITLE
Indicate range for editor.suggest.maxVisibleSuggestions

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#71203]
Testing https://github.com/Microsoft/vscode/issues/71084

<img width="491" alt="image" src="https://user-images.githubusercontent.com/35271042/55020989-377b1980-4fb5-11e9-82ea-63d85cd159ec.png">

It would be helpful to know the range of `editor.suggest.maxVisibleSuggestions`. For example, it would be nice to know that there is a max of 12 items.

**Comment by jrieken** [comment]
@aeschli What's the recommended approach here. The bounds are defined in the scheme, should I copy them into the label or should this be part of the "type-label"?

**Comment by jrieken** [comment]
Added the max to the message and bumped that to 15
