### ISSUE TITLE
Debugging of hierarchical sessions is flaky

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#71201]
re https://github.com/Microsoft/vscode/issues/71063

Sorry, needs two gifs because I can only record 30s in one go. Message is that every is flaky and I have no clue what's going on. 

* using cluster sample from https://github.com/Microsoft/vscode/issues/71063#issuecomment-476669886
* press F5
* something happens (that's the best I can describe it)
* stop and restart debugging
* something else happens

waiting forever for the sub processes to appear, thing seems to be in debug mode?
![p1](https://user-images.githubusercontent.com/1794099/55020908-1c7dc900-4ff8-11e9-8c09-41d817456673.gif)

still waiting (continuation from above). re-trying and it does something else
![Mar-26-2019 18-47-48](https://user-images.githubusercontent.com/1794099/55020906-1c7dc900-4ff8-11e9-84b9-0f8d8b4cfb47.gif)

**Comment by isidorn** [comment]
From @jrieken 


I have created this longish video: https://1drv.ms/v/s!AmNrgp2f2IPiz1P380bXQfWbSXKt showing so many issues that I am afraid I will miss some

at 34" debugging seems to have started but there are no child processes #71201
at 38" I stop debugging which makes the viewlet show progress (why not)
at 44" debugging stops after pressing the action again
at 48" I seems to be more successful, debugging shows child processes
at 1'01" a new interpretation of a hierarchy-layout is rendered
at 1'06" debugging stops by itself (why?), the toolbar doesn't update
at 1'12" I press stop, the toolbar partially disappears but continues to show the "hierarchy", focusing the editor cleans that up

**Comment by isidorn** [comment]
I have pushed fixes to the vscode regarding multiple sub sessions filed in other issues.

However this sounds like there is something wrong with cluster debugging. For that I am also assinging to @weinand to investigate. When investigating please use latest out of source
I will look into the wrong states here (showing initialisation when I should not for example and so on)

**Comment by weinand** [comment]
The only issue I see is on Windows:
once in a while detecting child processes is slow/delayed and VS Code creates new debug sessions late.

I'm not seeing this on the other platforms.

**Comment by weinand** [comment]
My last comment is not correct.
Here is what I found out so far:
- child process detection is not slow on Windows
- the node extension detects new child processes  quickly and immediately calls "startDebugging"
- but the "Debugger attached." response from node.js comes 22 seconds too late.

Here is screencast showing the sequence of events in realtime:

![2019-03-27_15-54-49 (1)](https://user-images.githubusercontent.com/1898161/55086947-915d0b80-50a9-11e9-87ce-c2389c314047.gif)

/cc @isidorn @roblourens

**Comment by weinand** [comment]
Next finding:

no slowness with "node-debug (legacy)":

![2019-03-27_16-24-11 (1)](https://user-images.githubusercontent.com/1898161/55088995-ff570200-50ac-11e9-87a2-19ee769f0090.gif)

**Comment by weinand** [comment]
With node-debug2 I was using node.js 10.15.0, but using 8.9.3 did not make a difference...

**Comment by weinand** [comment]
Another finding:
The attach slowness only occurs if I set "numCPUs" of the Cluster sample to 4 or more ("numCPUs" controls the maximum number of child processes). With values < 4 I could not observe any slowness.

**Comment by weinand** [comment]
For launching debug sessions for the child processes I create launch configs in memory.
I've added a `"trace": true` to the launch config and here is the result:

[debugadapter.txt.zip](https://github.com/Microsoft/vscode/files/3014061/debugadapter.txt.zip)

**Comment by isidorn** [comment]
@weinand Great findings.
The issue seems to be on the node side, thus unassigning myself. Feel free to assign back if I can help.

**Comment by roblourens** [comment]
The log doesn't show any slowness. The DA sends "initialized" less than 100ms after it's created. The "Debugger attached" message just comes from node the instant a debugger is attached. But it doesn't sound like the delay is on vscode's side, so I don't know what's going on, I'll try it.

**Comment by roblourens** [comment]
It seems like the delay is during startDebugging. Here is the window log. I start the parent session at :33, we start handling the other sessions at :37, but the other sessions don't actually start until :43.

I've seen it much slower than that too, during that time, I see the new node processes but I don't see any debug adapter processes.

```
[2019-03-27 23:36:33.515] [renderer1] [trace] telemetry/debugSessionStart {"type":"node2","breakpointCount":0,"exceptionBreakpoints":[{"enabled":false,"id":"03514f29-534b-418c-9fe4-c8bb59aec74d","filter":"all","label":"All Exceptions"},{"enabled":false,"id":"8c4467e1-9117-4c78-81fd-166fb75ff66f","filter":"uncaught","label":"Uncaught Exceptions"}],"watchExpressionsCount":0,"extensionName":"ms-vscode.node-debug2","isBuiltin":true,"launchJsonExists":true}
[2019-03-27 23:36:33.516] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"workbench.action.debug.start","from":"sideBar"}
[2019-03-27 23:36:36.207] [renderer1] [trace] CommandService#executeCommand setContext
[2019-03-27 23:36:37.625] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve
[2019-03-27 23:36:37.626] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve:node
[2019-03-27 23:36:37.626] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve
[2019-03-27 23:36:37.627] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve:node
[2019-03-27 23:36:37.628] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve
[2019-03-27 23:36:37.628] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve:node
[2019-03-27 23:36:37.629] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve
[2019-03-27 23:36:37.630] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve:node
[2019-03-27 23:36:37.630] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve
[2019-03-27 23:36:37.631] [renderer1] [trace] onWillActivateByEvent:  onDebugResolve:node
[2019-03-27 23:36:43.145] [renderer1] [trace] telemetry/debugSessionStart {"type":"node2","breakpointCount":0,
```

**Comment by roblourens** [comment]
Is it the configuration resolver? Maybe detecting the protocol version is slow on several processes simultaneously.

**Comment by roblourens** [comment]
Oh that might also explain why node is faster than node2

**Comment by isidorn** [comment]
If I understand the comments correctly it looks like the protocol version detection might be slow. This is done in the node extension [here](https://github.com/Microsoft/vscode-node-debug/blob/56dc3892885b3122385b785322b00a92d33fdded/src/node/extension/configurationProvider.ts#L47). Thus assigning to @weinand 
VSCode side does not detect protocols and it is also not windows dependent.

I can also help, but please let me know where exactly you would like me to investigate. Thanks!

**Comment by weinand** [comment]
No, I've verified already yesterday that protocol detection is not the issue.

The slowness was between calling "startDebugging" and seeing the corresponding debug adapter coming to life. This lead us to believe that it is a VS Code issue.

But good news: in the latest Insiders I'm no longer seeing the issue. 

I'm investigating...

**Comment by weinand** [comment]
I have no idea why the latest Insiders does not show the flakiness any more.
I can only speculate that changes in VS Code are the reason since there were no changes in the node-debug extensions.
I'm not planning to change anything for the March milestone, so I'm moving this to "onDeck".

**Comment by connor4312** [comment]
This should be more reliable with js-debug's approach to dealing with child processes. Let me know if you still run into this anywhere.
