### ISSUE TITLE
editor.gotoLocation.many setting help text

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#71212]
Testing #71087 

VS Code version: Code - Insiders 1.33.0-insider (b9bcca2b9830df592892d63201704026c18dcbe5, 2019-03-26T08:08:11.421Z)
OS version: Darwin x64 17.7.0

A couple of nits with this text:

![image](https://user-images.githubusercontent.com/1487073/55022499-e7ea1d00-4fb7-11e9-8254-c5d3f4ffbdc2.png)

I don't think we by default use the UK version of `behavior` so drop the `u`, drop the `-` from `-commands`, and capitalize the `Go To`s to match what is in the UI:

_Controls the behavior of the "Go To" commands such as Go To Definition, when multiple targets exist._

**Comment by jrieken** [comment]
Thanks @chrisdias
