### ISSUE TITLE
Keyboard Shortcuts Change When Expression Not Working

### ISSUE THREAD

**Issue by xiata** [Microsoft/vscode#71219]
Issue Type: <b>Bug</b>

Was making a slight tweak to the alt+arrows default bindings since by default there are no bindings to get back to get back and forth between my 1: bash and 2: npm terminals (webpack watch). Saw that there were commands for it, but then noticed the Keyboard Shortcuts visual editor seems to not save changing the When expression. I see it flag the tab with a * for a second, so it definitely noticed the keybinding assignment change but doesn't take effect. Minor issue, but unexpected behavior nevertheless.

1. Go to Keyboard Shortcuts
2. Remove binding for workbench.action.terminal.focusNextPane
3. Add binding for workbench.action.terminal.focusNext (alt+UpArrow)
4. Right-click on When column for added binding, hit Change When Binding
5. Type and hit enter: terminalFocus

## Expected
When binding for workbench.action.terminal.focusNext to be: terminalFocus

## Actual
When binding for workbench.action.terminal.focusNext not set

## Work around
Add the missing when property to the binding in keybindings.json manually.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (8.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-firefox-debug|hbe|1.7.8
mssql|ms-|1.5.0
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.3
sort-lines|Tyr|1.8.0
vscode-icons|vsc|8.4.0

</details>

**Comment by sandy081** [comment]
Its fixed in insiders and will be available in next release.
