### ISSUE TITLE
moving editor.suggest.filteredTypes to language-specific fails

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#71213]
Testing https://github.com/Microsoft/vscode/issues/71084

Repro:
1. Open vscode repo
2. Open a js file and ts file
3. Configure `editor.suggest.filteredTypes` to hide methods
4. Verify both ts and js file hide methods in suggestions
5. Move the setting into a `[javascript]` block

🐛 => ts file will continue to hide methods in suggestions

**Comment by jrieken** [comment]
> => ts file will continue to hide methods in suggestions

ts? really? when configuring for `[javascript]` then that would be expected....

**Comment by sbatten** [comment]
@jrieken none of the other settings worked that way. configuring for `[javascript]` to hide icons only affected the js file. why should they differ?

**Comment by sbatten** [comment]
For clarity:
```json
"[javascript]": {
	"editor.suggest.showIcons": false,
	"editor.suggest.maxVisibleSuggestions": 12,
	"editor.suggest.filteredTypes": {
		"keyword": false,
		"method": false,
		"function": false,
		"class": false,
		"module": false,
		"property": false,
		"value": false,
		"enum": false,
		"reference": false,
		"color": false,
		"unit": false,
		"snippet": false
	}
}
```

The above should only affect the js file. The top 2 do, and the bottom one affects both js and ts

**Comment by jrieken** [comment]
Oh, now I understand. So this happens when stuff gets moved around. Does it recover after a reload?

**Comment by sbatten** [comment]
Yes, reload makes it work as expected

**Comment by rebornix** [comment]
* Filter `method`
* Methods are gone from suggestion list
* Comment out the setting
* Methods are still filtered out 🐛

It seems turning off the filtering doesn't bring out the suggestions.

**Comment by weinand** [comment]
@sbatten please verify this today
