### ISSUE TITLE
Hierarchical debug sessions are not ready for prime time

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71210]
re #71063

This is maybe the same as https://github.com/Microsoft/vscode/issues/71201, surely a bit of a rant, and I do what we shouldn't do: file multiple issues in one. 

I have created this longish video: https://1drv.ms/v/s!AmNrgp2f2IPiz1P380bXQfWbSXKt showing so many issues that I am afraid I will miss some

* at 34" debugging seems to have started but there are no child processes https://github.com/Microsoft/vscode/issues/71201
* at 38" I stop debugging which makes the viewlet show progress (why not)
* at 44" debugging stops after pressing the action again
* at 48" I seems to be more successful, debugging shows child processes
* at 1'01" a new interpretation of a hierarchy-layout is rendered
* at 1'06" debugging stops by itself (why?), the toolbar doesn't update
* at 1'12" I press stop, the toolbar partially disappears but continues to show the "hierarchy", focusing the editor cleans that up

**Comment by isidorn** [comment]
Thanks @jrieken 
But sounds very similar to that one. So let's keep that as one issue and I am copying over this data
