### ISSUE TITLE
No method suggestions in yarn workspaces

### ISSUE THREAD

**Issue by akaRem** [Microsoft/vscode#71225]
I have a project which uses yarn workspaces.
It's a kind of client-server thing that shares devTools.

If I run `ts-node-dev --respawn --transpileOnly ./src/index.ts` from `packages/server` everything works.

But if I open VSCode from project's root and navigate to `packages/server/src/index.ts`, I do not have any autocompletion or method suggestions.

like..
```
const express = require("express"); // jump-to-definition does not work
const app = express();
app.   // -> have no Idea about methods
```

I searched through https://code.visualstudio.com — there are no docs regarding this setup.

Does VSCode support yarn workspaces at all?
Where can I find any documentation regarding setup?
What extra info do you need from my side?

**Comment by mjbvz** [comment]
Can you please share a small example project so that we can investigate this

Also, what VS Code version are you using and what extensions do you have installed?

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate
