### ISSUE TITLE
VS Code holds onto file handle which prevents other git client from working

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/vscode#71221]
Issue Type: <b>Bug</b>

I have a github project https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure/storage/blob folder opened in VS Code.

When I tried to rebase my branch from outside VS Code it failed with:

```
  1 git.exe … "rebase" "upstream/master"
First, rewinding head to replay your work on top of it...
error: cannot stat 'packages/@azure/storage/blob/lib': Permission denied
error: cannot stat 'packages/@azure/storage/blob/lib': Permission denied
... [cut]
error: cannot stat 'packages/@azure/storage/blob/tests': Permission denied
error: cannot stat 'packages/@azure/storage/blob/tests': Permission denied
error: cannot stat 'packages/@azure/storage/blob/tests': Permission denied
could not detach HEAD
```

VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T10:06:48.833Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|31.76GB (15.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-generate-getter-setter|DSK|0.5.0
prettier-vscode|esb|1.8.1
docthis|joe|0.7.1
debugger-for-chrome|msj|4.11.3
java|red|0.41.0
trailing-spaces|sha|0.2.11

</details>

**Comment by joaomoreno** [comment]
What are the permissions of `packages/@azure/storage/blob/lib`? Does the file/folder exist? Can you run `rebase` from a command line instead, does that work?

**Comment by jeremymeng** [comment]
From what I can tell using `procexp`, VS Code is holding the file handles open.  After I closed VS Code, the same rebase operation succeeded.

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions`?

**Comment by jlowcs** [comment]
I have the same issue, even with `--disable-extensions`

**Comment by joaomoreno** [comment]
Can you reproduce if you disable VS Code's git altogether? `git.enabled = false`

**Comment by joaomoreno** [comment]
cc @mjbvz Does TS lock directories?

**Comment by mjbvz** [comment]
Only for `@types` that I know of, see Microsoft/TypeScript#29407

**Comment by devlinb** [comment]
I'm seeing similar issues where vscode is not letting the /build/ folder of my Firebase Functions project be deleted. A handle to the folder is being kept open. 

I can confirm that this happens even with all extensions disabled.

The behavior is very strange, the folder is being kept in some sort of strange state, after running my build scripts, which first delete the folder, I can see the folder on the command line, but I am unable to cd into the folder. If after attempting to delete the folder using my build scripts, I then try to navigate to it in VSCode, it will sometimes crash VSCode!

I also suspect it is some sort of indexer, since this does not happen right away after loading VSCode, but it takes 30 or so seconds before the folder has a handle taken out on it.

I believe this is a regression, as earlier versions of VSCode did not exhibit this behavior, unfortunately I don't recall when it first started happening.

**Comment by joaomoreno** [comment]
@roblourens Have you seen this before?

**Comment by roblourens** [comment]
Is there a search running when you see this? If you open the process explorer (under Help menu) do you see a searchService running?

I haven't seen this before and wouldn't expect rg to prevent you from deleting a file.

**Comment by devlinb** [comment]
> 
> 
> Is there a search running when you see this? If you open the process explorer (under Help menu) do you see a searchService running?
> 
> I haven't seen this before and wouldn't expect rg to prevent you from deleting a file.

@roblourens 

searchService is indeed running.

I checked using Process Explorer and without the search.exclude, Code.exe has a handle open to the \build folder

If I add 

````
"search.exclude": {
    "**/build": true
},
````

reload, code.exe does not grab a handle to the \build folder and the folder can be deleted.

code.exe does not appear to grab a handle to any of the files within the folder, but it only grabs a handle to the folder itself. 

Occasionally to get a repro I have to modify a file somewhere in the project. (not in the build folder obviously!)

Interestingly if I look a Process Monitor, w/o the search.exclude this is happening non-stop:

![image](https://user-images.githubusercontent.com/11895351/55434147-c0f99100-554b-11e9-9716-34ca9cf947e7.png)

With search.exclude all of that is gone.

**Comment by roblourens** [comment]
Can you get the command line args of the `rg` process under the search service?

**Comment by roblourens** [comment]
Also you are on kind of an old Insiders build, it would be good to update to a newer version.

**Comment by devlinb** [comment]
Unfortunately I'm not sure where to find the rg process, the process explorer within VSCode shows

![image](https://user-images.githubusercontent.com/11895351/55443902-4fc8d680-5569-11e9-9d46-62ef78f5617e.png)

Using SysInternals process explorer, here is info on the 2 (!) processes that have a handle to that folder:

![image](https://user-images.githubusercontent.com/11895351/55444585-e8605600-556b-11e9-8f8a-ebc4074f6eb7.png)

![image](https://user-images.githubusercontent.com/11895351/55444628-28bfd400-556c-11e9-978c-50e91a78e3ad.png)


As I've played around more, I have some more detail: 

1. This is a project workspace that has 4 different JS projects in it. Only 1 of the folders exhibits this behavior.

2. All the projects have the same 1st step in their build, which is where the failure is at for the project with the issue: `rimraf build/ `

(As mentioned before, deleting the folder through DOS or Windows Explorer brings up various permission denied errors)

3. The root of the project has a jsconfig.json

4. The folder that has this problem also has a jsconfig.json

If I remove jsconfig.json from the sub-project folder, the problem also goes away.

##Contents of the main jsconfig.json:

````
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs"
    }
}
````

##Contents of the sub-project's jsconfig.json:

````
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs"
    },
    "include": [
        "src/**/*",
        "index.js"
    ]
}
````

For deleting / adding the sub-projects jsconfig.json to have an impact, vscode has to be reloaded.

So far, 2 ways around this. :)

**Comment by roblourens** [comment]
Oh ok this is related to the TS server not search itself. @mjbvz is there an issue with TS holding onto files?

**Comment by mjbvz** [comment]
Probably Microsoft/TypeScript#29407 then. I thought it was `@types` specific but it may just be for any d.ts file under `node_modules`
