### ISSUE TITLE
Running a file forces terminal window to pop up

### ISSUE THREAD

**Issue by Jure34** [Microsoft/vscode#71223]
Every time I debug a file it switches from the debug console to the terminal window in VSC. In videos, I don't see this happening to other users, also the debug toolbar (titled "C" in the link) disappears after running.

https://code.visualstudio.com/Docs/editor/debugging

My only extension is ms.python-python

_Edit_: link wasn't working

**Comment by weinand** [comment]
And you are debugging python?

**Comment by Jure34** [comment]
Yes, I'm debugging python
