### ISSUE TITLE
inputs section of launch.json specification is not right for 'args' field, type 'input'

### ISSUE THREAD

**Issue by haneefdm** [Microsoft/vscode#71222]
Issue Type: <b>Bug</b>

Create an input specification in launch.json like below and you will notice that
** You cannot create an array, only an object for the args field
** If you do try to make an array, you will get errors parsing launch.json

Here is an example launch.json I was trying to create

```json
{
    "version":"0.2.0",
    "configurations": [],
    "inputs": [
        {
            "id": "myVar",
            "type": "command",
            "command": "echo",
            "args": [
            ]
        }
    ]
}
```

According to the docs, the "args" field is supposed to be an array of strings that form the arguments to the command to be executed. Intellisense and parser thinks it should be an object.

See https://code.visualstudio.com/docs/editor/variables-reference

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--disable-extension|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.6.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.25.1
vscode-eslint|dba|1.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
csharpextensions|jch|1.3.0
vscode-csharp-snippets|jor|0.3.1
csharpfixformat|Leo|0.0.80
cortex-debug|mar|0.2.3
python|ms-|2019.2.5558
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
mono-debug|ms-|0.15.8
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
tcl|sle|0.2.0
python|tht|0.2.3
vscode-icons|vsc|8.4.0

</details>

**Comment by haneefdm** [comment]
The same problem also exists for tasks.json which also allows an 'inputs' section.

Aside question: I am not sure of the relationship between the inputs section in launch.json and tasks.json. I am assuming they are separate (not shared) and if I want the same input variable in both, I have to duplicate it in both files? Is there a better/centralized place where I can create my own variables so I don't have to duplicate code and have one version of the truth?

Sure, I can always use env. variables but depending on the OS, it may require a logout/login which is not nice.

**Comment by weinand** [comment]
I cannot find a single place in the doc where we say that "args" is an array.
All I can find is:
> args: Optional option bag passed to the command's implementation.

**Comment by haneefdm** [comment]
Yes, I am so very sorry. It is supposed to be a bag for a vscode command.

Can't even begin to explain, how I interpreted that documentation that way. I thought it was an external shell command (confused between task and input sections).  I am going to go hide somewhere now.

**Comment by weinand** [comment]
@haneefdm no problem
