### ISSUE TITLE
Some 'font-family' properties in the workbench CSS not work as expected due to lack of quotation marks

### ISSUE THREAD

**Issue by wangcheng678** [Microsoft/vscode#7122]
- VSCode Version: 1.1 stable
- OS Version: OS X 10.11.4

I tried to add `'.SFNSDisplay-Light'` value into the `font-family` property since `'SFUIText-Light'` value does not work on latest OS X.
**During the building process, quotation marks / apostrophes wrapping font names are removed.** `'.SFNSDisplay-Light'` without quotation marks does not resolve to the font as expected, so Helvetica is used instead. After I add quotation marks back, it works.

**Comment by joaomoreno** [comment]
What do you mean with *during the building process*? Where did you add that value?

**Comment by bpasero** [comment]
@joaomoreno maybe this is due to our CSS optimizer that we run during the build? It might remove quotes from font families to minimize the CSS content.

**Comment by wangcheng678** [comment]
@bpasero got my idea. There are quotation marks in CSS source cod, but nothing in workbench.main.css.

**Comment by joaomoreno** [comment]
I see what you mean. The minifier does remove the quotes... but that is OK, the browser still parses it:

![image](https://cloud.githubusercontent.com/assets/22350/15751465/7c19efd4-28ea-11e6-8ebc-21768da7d8d2.png)

**Comment by wangcheng678** [comment]
Names start with punctuation characters or digits (like ".SFNSDisplay")
must be wrapped with quotes to get parsed. According tow this article.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family (look at
"valid family names" section）
2016年6月2日 23:51，"João Moreno" <notifications@github.com>写道：

I see what you mean. The minifier does remove the quotes... but that is OK,
the browser still parses it:

[image: image]
<https://cloud.githubusercontent.com/assets/22350/15751465/7c19efd4-28ea-11e6-8ebc-21768da7d8d2.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/7122#issuecomment-223334761>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABnEvG4G-THq8B1dedXsJzPzQetMU2FTks5qHvvwgaJpZM4IsTAX>
.

**Comment by joaomoreno** [comment]
> punctuation characters and digits at the start of each token must be escaped in unquoted font family names

The dot `.` is escaped with a backslash in the minified version, that's why it works.

**Comment by wangcheng678** [comment]
@joaomoreno OK. I've learned that. Thanks.
