### ISSUE TITLE
program will crash in libpng when debugging via vscode. it will not crash if run or debugged from terminal.

### ISSUE THREAD

**Issue by arnoldemu** [Microsoft/vscode#71224]
Hello, 
I am seeing a crash when debugging my program within vscode. The crash doesn't happen if debugging outside of vscode or run from the terminal directly.

I am running the 'snap' vscode under Ubuntu 18.10 with default "unity" look window manager.

To reproduce this you will need the "cmake-tools-helper" extension installed because the build uses cmake. I have cmake 3.12.1 installed.  I don't believe the issue I am seeing is with the extensions I am using because I can build the program executable with vscode using these extensions and then run that same program outside of vscode without a problem.

You will need to install wxwidgets development libraries because the program uses wxwidgets. Note that wxwidgets libraries are also linked against libpng. 

Pre-requisites: 

Install wxwidgets and cmake from terminal:

sudo apt-get install g++
sudo apt-get install cmake
sudo apt-get install libwxgtk3.0-dev

Steps to reproduce:
1. Run vscode from terminal. I am running as a normal user which can be elevated with "sudo" to install packages.
2. Inside vscode use "open folder" and choose the folder where the CMakeLists.txt file is located for the program. See attached "minexp.zip"
3. Click on the cmake triangle icon on the bar on the left to access the cmake tools.
4. Click on the configure button/cmake smaller triangle at the top of the cmake tool window. Use gcc 6.5.0 if prompted. I tried clang with the same results. You need a compiler that can build programs. The cmake tools will fail to configure if you don't have one of those.
Check configuration is successful in the output window.
5. Click on the hammer button at the top of the cmake tool window. The code will build.
6. Check build is successful.
7. Check "export" program executable has been built inside the build folder which is located within the source directory.
8. "Start Debugging" in vscode to debug the executable. I see gdb outputting logging. If it breaks at the start of the program "go" to make it run. You will see a dialog appear with a title and a menu. This is the program running.
9. Click on the window and attempt to use the file menu.
You will get see a crash in memcpy-sse3. In the callstack libpng is mentioned. It is not possible to skip this and continue. 
10. In a terminal go to the executable's location and run it and do the same as before. NOTE: It will not crash.
11. In a terminal go to the executable's location run it via gdb and do the same as before. (gdb export, run). NOTE: it will not crash.

My expectation is that I can use the debugger in vscode and that it is consistent with running from the terminal or via gdb in the terminal in that the operation is the same, currently vscode is inconsistent with the other methods to run it.

I checked that the paths that the gdb launched from the terminal and the gdb launched by vscode were using for the shared libraries that were loaded. I saw they were the same. However, what I did see is that the gdb vscode is using  is loading more libraries than the gdb run from the terminal. This may be part of the problem. 

Thank you for your help.

Kevin

vscode information:

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-16-generic

CPUs | Intel(R) Xeon(R) CPU X5472 @ 3.00GHz (4 x 2556)
-- | --
GPU Status | 2d_canvas: disabled_softwarechecker_imaging: disabled_offflash_3d: disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline: disabled_softwaregpu_compositing: disabled_softwaremultiple_raster_threads: disabled_offnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwaresurface_synchronization: disabled_offvideo_decode: disabled_softwarewebgl: disabled_offwebgl2: disabled_off
Load (avg) | 3, 2, 1
Memory (System) | 3.85GB (1.50GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
code-gnu-global | aus | 0.2.2
configure-c-compiling | ivo | 0.2.1
cmake-tools-helper | mad | 0.2.1
cpptools | ms- | 0.22.1
vscode-make | tec | 1.0.2
cmake | twx | 0.0.17
cmake-tools | vec | 1.1.3

[minexp.zip](https://github.com/Microsoft/vscode/files/3010141/minexp.zip)

**Comment by weinand** [comment]
Please file this issue against cpptools.
