### ISSUE TITLE
Deleting a file via hotkey in the file explorer causes focus to move to the entire tree

### ISSUE THREAD

**Issue by jsunsawyer** [Microsoft/vscode#71236]
- VSCode Version: 1.32.3 
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Focus file explorer
2. Navigate to a folder and add a file
3. Delete that file with cmd+delete

Focus is now outside of the entire file explorer tree, requiring the user to navigate back to the folder to continue adjusting files.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70069 and https://github.com/Microsoft/vscode/issues/63673
Since the bottomline issue is the same, when there is no more focused item the focus should be left in the tree
