### ISSUE TITLE
Cannot find a program to debug

### ISSUE THREAD

**Issue by chuckleslove** [Microsoft/vscode#71235]
Issue Type: <b>Bug</b>

This is a script I have debugged many times in the past for testing and working on it.  All of the suddent in the latest version it is unable to find a program to debug.  Literally no changes have been made on my code as I haven't worked on it for about a month, I was just going to insert a few break points to refresh myself on code but I can't even run the script in debug mode.  If I run the exact file in a node terminal using either node script.js or pm2 start script.js it works just fine.

Something is broken on the VS Code side of things.

This is a pretty basic node.js script which is supposed to be supported natively, just a relatively basic Discord bot.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

**Comment by weinand** [comment]
Please provide reproducible steps.
How does your launch config looks like?

**Comment by chuckleslove** [comment]
I've never used a launch.json config.

Even if I create a new js file with the example from here: https://code.visualstudio.com/docs/introvideos/debugging

var i = 0;

setInterval(() => {
        console.log('iteration' + i);
        i++;
}, 1000)

That won't run in the debugger either with the same error.

I'm not sure what the problem is unless I missed something in an update to VS Code that requires me to add some new settings but right now not a single node script will run in debug mode.  They will run fine from the terminal as expected.

**Comment by weinand** [comment]
You are running into issue #71135 that got introduced some releases ago and was reported and fixed today. 
You can wait for the fix to appear in tomorrows Insider build or you can use a launch config as a workaround, e.g. the following which debugs the file in the active editor: 
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}"
		}
	]
}
```
A more robust approach is to use a launch config that debugs a fixed file "test.js":
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/test.js"
		}
	]
}
```
