### ISSUE TITLE
Deleting a file in working tree freezes vscode 

### ISSUE THREAD

**Issue by umutozdemir97** [Microsoft/vscode#71233]
- VSCode Version: 1.32.3
- OS Version: Kubuntu and Windows 10 (Both experience the same problem)

Steps to Reproduce:

1. Open a folder as a working space
2. Delete any file (even empty ones)

After a long freeze, it will actually delete the file. OS (Windows and Kubuntu) reports that it is not responding. I click on 'wait' to avoid termination. 

Does this issue occur when all extensions are disabled?: Yes
I tested --disable-extensions on only Kubuntu and everything was exactly same. I will add Windows situation.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by umutozdemir97** [comment]
Now I tested this situation with the latest insider version: 

```
Version: 1.33.0-insider
Commit: 3bd60b2ba753e7fe39b42f99184bc6c5881d3551
Date: 2019-03-27T06:14:45.709Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic
```
Seems like this problem does not exist now.

**Comment by bpasero** [comment]
Ok good, we will release that next week.
