### ISSUE TITLE
Allow to drop a folder into the explorer to copy it in

### ISSUE THREAD

**Issue by b-hayes** [microsoft/vscode#71239]
I have looked at other similar issues but not exactly the same as this.

The problem I have is I can not drag a folder into vs code's explorer tool to copy it.

Draging a folder in it shows the plus icon indicating it will copy the files, and it even expands folders in the tree giving me the impression it's letting me pick where Im going to copy them but instead of copying the files.....

vs code opens a workspace instead 🤷‍♀️👿 and shows a seperate section int he explorer with files that ares not inside the project folder and in this case are tracked by an some other git repository.

Then I had to spend an hour figuring out how to stop showing files outside of my current project folder that im working on.

I always open vscode via command line 'code /some/project/folder'

I tried closing vs code and reopening with cli 'code /path/to/folder' again and now two copies of vscode will open. One with the workspace it just created and another copy with with the folder i just ran with cli.

Eventually found I can close workspace. Close vs code and then open with my cli again to get back to normal. But I shouldn't have to do this because I tried to copy a file.

But this seems pretty un-intuitive and diverges from all windows application behaviours I am used to.

At least make it so that dragging files doesn't make you think it's going to copy them if it isn't going to.

I also tried right clicking file to copy form windows explorer and right click in vs code always has paste greyed out.

Seems the only way is do the file copy in a separate application. 😒

Yes it is simple enough to right click and open the folder with window explorer and then drag my files there instead.

But why should I have to make a point to remember how to stop vs code making a work-space and forcing me to recover from expecting normal behaviour as indicated by the UI itself.

I do not want to use work-spaces that start referencing files that are not in the project folder/git repository im working in.

Seems like madness to me.

**Comment by isidorn** [comment]
Fixed via a3baa1e2ee
