### ISSUE TITLE
Emmet support for abbreviation expansion

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#71237]
Currently there is no support for abbreviation expansion like `select+` of `table+` for Emmet:

![gif](https://user-images.githubusercontent.com/35271042/55038489-3f9b7f00-4fde-11e9-8a05-621a6bee8a16.gif)

And here is how it works in Emmet:
![gif](https://user-images.githubusercontent.com/35271042/55038441-1844b200-4fde-11e9-94b2-85263f75cf54.gif)

**Comment by devanshj** [comment]
I guess this can be closed because as [Sergey said "Abbreviations with + at the end are deprecated"](https://github.com/emmetio/expand-abbreviation/issues/19#issuecomment-374131586).
/cc @octref

**Comment by octref** [comment]
As @devanshj said, can't help here 😢
