### ISSUE TITLE
console.trace from EH not handled correctly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#71245]
- In an extension, parse a URI without a scheme like `console.log(vscode.Uri.parse('/foo/bar'));`
- Or, just call it directly `console.trace('hi')`
- When debugging the extension, the debug console shows `[object Object]` and a stack trace. The message is missing. This is a bad experience for the `Uri.parse` change from #66802 because the stack trace has no message or explanation.

cc @jrieken 

![image](https://user-images.githubusercontent.com/323878/55042621-8d6cb300-4fef-11e9-88a7-0b120224e2b1.png)

**Comment by isidorn** [comment]
This works just fine for me.
Here's my code snippet, and here's the output
```
       console.trace('hi');
       console.log(vscode.Uri.parse('/foo/bar'))
```
Let me know what you are doing differently.
I tried both out of source and insiders on os x

![Screenshot 2019-03-27 at 10 40 15](https://user-images.githubusercontent.com/1926584/55065790-c30bad80-507c-11e9-8a28-84de85843cd7.png)

**Comment by roblourens** [comment]
I can still repro. I'll try to debug it.

**Comment by roblourens** [comment]
This is very weird, I traced it into node console.js. It essentially does

```
  const err = {
    name: 'Trace',
    message: this[kFormatForStderr](args)
  };
  Error.captureStackTrace(err, trace);
  this.error(err.stack);
```

`message` is `"foo"`. `Error.captureStackTrace` is native but it creates a `stack` property with `[object Object]` and I don't know why.

I'm curious about this so I'll debug more but there's probably nothing we can do and it will probably disappear at some point so I'll just close this.
