### ISSUE TITLE
"Pick a remote to publish the branch to" should have a "new branch" option

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#71242]
To address the original issue in https://github.com/Microsoft/vscode/issues/21189 more directly, it would be great if this worked:

- Create a new branch
- Run the "Publish branch" command
- See the "Pick a remote..." prompt
- Select a "Add New Remote" option
- The remote is added and the branch is pushed to that remote

Is that what you originally had in mind @Tyriar?

**Comment by jmbockhorst** [comment]
I would like to take this.

**Comment by Tyriar** [comment]
@roblourens yep that was it.

@jmbockhorst 👍
