### ISSUE TITLE
"Select All Occurrences of Find Match" doesn't work if Find panel is open

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#71249]
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Hit `cmd-F` to show the editor find panel.
2. Focus the editor.
3. Select a word.
4. Hit `cmd-shift-L` ("Select All Occurrences of Find Match").
5. It will select all occurrences of _whatever is in the find panel_.

If you do this without having the find panel open, it will match all instances of the selected word correctly. It's a bug because "Select All Occurrences of Find Match" should have consistent behaviour; it shouldn't matter if you have the find panel open or not. It seems that if you don't have the find panel open, it will copy the current selection into it in step 4. If you already have the find panel open, it won't.

Workaround: Use `cmd-D` ("Add Selection to Next Find Match") first:

1. Hit `cmd-F` to show the editor find panel.
2. Focus the editor.
3. Select a word.
4. Hit `cmd-D`. This causes the selected word to be copied into the find panel.
5. You can now use `cmd-shift-L` to get the right behaviour.

Does this issue occur when all extensions are disabled?: Yes

**Comment by atombender** [comment]
Not a dupe of those.

**Comment by rebornix** [comment]
@atombender I can't reproduce this issue anymore, can you help confirm ?

![select-all](https://user-images.githubusercontent.com/876920/61917644-10047100-af03-11e9-81bf-e3dfb5c5b711.gif)

**Comment by atombender** [comment]
Looks like it!
