### ISSUE TITLE
Open Editors: Reveal in File Tree as Menu-Option/Shortcut

### ISSUE THREAD

**Issue by m4w** [Microsoft/vscode#7124]
- VSCode Version: 1.1.0

It would be a great feature to have a right click menu option on a "Working File"-file to reveal a file in the file tree, as well as a shortcut for the same.
This is essential, if you deactivate the `explorer.autoReveal` feature. 

I do not want to always (aka. automaticly) reveal a file in the filetree. But sometimes, currently I can not do so.

**Comment by Tyriar** [comment]
I have `explorer.autoReveal` as false and use a keybinding on `workbench.files.action.showActiveFileInExplorer` to accomplish this. You can also get to it from the command palette.

![image](https://cloud.githubusercontent.com/assets/2193314/15741021/802d545e-286c-11e6-9140-1763fa038cc7.png)

**Comment by m4w** [comment]
Thanks, that helps a lot. I must have overlooked it. Nevertheless the right click menu would be useful.

**Comment by MLefebvreICO** [comment]
+1 for the right click menu

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

Also there is a workaround
