### ISSUE TITLE
Custom Dialogs clipped by VS Code window

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#71246]
Testing #71116 
Mac, Insiders
`b9bcca2b9830df592892d63201704026c18dcbe5`

The native dialog extends beyond the VS Code window frame when resizing which the custom dialog is clipped by VS Code.

![image](https://user-images.githubusercontent.com/1487073/55042716-0f5cdc00-4ff0-11e9-8724-310a5e085267.png)

Here's with the custom dialog (all of the warning dialog is clipped so you can't see it):

![image](https://user-images.githubusercontent.com/1487073/55042785-6662b100-4ff0-11e9-895d-3b69821a749b.png)

I don't think this needs to be addressed, but logging anyway.

**Comment by sbatten** [comment]
thanks for logging but this is just a known limitation so not likely to have a fix anytime soon
