### ISSUE TITLE
'Undo Last commit' does not work if there is no commit message

### ISSUE THREAD

**Issue by shubhra-agrawal** [microsoft/vscode#71258]
Issue Type: <b>Bug</b>

- Made some changes to my branch, staged them, added a commit message and clicked on the commit button
- The app was slow so I clicked on the commit button again
- Got a prompt along the lines of "Can't fetch head.." but I dismissed it accidentally. The status bar at the bottom showed that the commit was sucessful so I pushed to remote
- Checked the commit on remote. Somehow there was no commit message
- Tried to 'Undo last commit' in VS code but it fails with a 'Bad commit' error

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 799)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.66GB (1.63GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
vscode-pull-request-github|Git|0.5.1
cpptools|ms-|0.22.1

</details>

**Comment by engrravijain** [comment]
@joaomoreno is this issue resolved? if not i would like to work on this.

**Comment by ngrygiel** [comment]
I have the same question, would like to work on this if it still isn't resolved. @joaomoreno

**Comment by marmikc** [comment]
I all, I've also been looking into this issue. While I have not been able to recreate the error as stated what I have noticed is that VS Code cannot undo commits where the commit is only whitespace. For example, if a commit is made by pressing space in the commit message box, and then pressing Ctrl + Enter, the commit does through fine, however, when undoing, the same error described in the original post occurs.

I have not localized the error to a specific file yet, I just wanted to let people know what I've found out.

**Comment by marmikc** [comment]
Hi again everyone, I've noticed that in this bug there are essentially two parts to it. If VS Code tries to undo a commit where there was an empty commit message, or a commit message with only whitespace, the "Bad Commit" error occurs.

Furthermore, there is a way to make a commit with just whitespace through VS Code. As I described it in the last comment, if you press the tick by Source Control: Git, enter some whitespace, and then press enter, the commit goes through with the message being whitespace. If you try to undo this, the same error will occur.

- [ ] Cannot undo git commits with only whitespace
- [ ] Can make commits with only whitespace

**Comment by ngrygiel** [comment]
I think I've located where the error with whitespace commits is happening.

In commands.ts, the function undoCommit() calls getCommit() on 'HEAD' and leads to the getCommit() function in git.ts, which is where the 'bad commit format' error originates.

getCommit() in git.ts returns the 'bad commit' error if the function parseGitCommit() (which takes an inputted string) returns null. parseGitCommit() runs a regex check on the inputted string after calling trim() on it and returns null if it doesn't find any matches.

It appears to me that the error eventually corresponds to that regex match/calling trim() on the inputted string, as that should be causing any pure whitespace commit message passed in to become an empty string. I'm hesitant to simply remove the trim() function call, however, as I believe that could cause a lot of new issues.

**Comment by marmikc** [comment]
I have found a potential fix for this error, I will submit a pull request for it soon.

**Comment by marmikc** [comment]
> I think I've located where the error with whitespace commits is happening.
> 
> In commands.ts, the function undoCommit() calls getCommit() on 'HEAD' and leads to the getCommit() function in git.ts, which is where the 'bad commit format' error originates.
> 
> getCommit() in git.ts returns the 'bad commit' error if the function parseGitCommit() (which takes an inputted string) returns null. parseGitCommit() runs a regex check on the inputted string after calling trim() on it and returns null if it doesn't find any matches.
> 
> It appears to me that the error eventually corresponds to that regex match/calling trim() on the inputted string, as that should be causing any pure whitespace commit message passed in to become an empty string. I'm hesitant to simply remove the trim() function call, however, as I believe that could cause a lot of new issues.

I have found this error to be in the same location as well. By testing with different commits it seems the regex matching expression is at fault, not the trimming function call.

The string that goes into the regex match is as follows:
```python
[hash of previous git commit]
emailaddress@domain.com
[hash of this git commit]
[name of this commit]
```

The last part, the name of this commit, is optional, and is not present when there is an empty git commit, but the regex expression looks for it, and hence sees the expression as invalid.

**Comment by marmikc** [comment]
The build on my pull requests is failing and I am unsure why. I would appreciate help if someone could provide it for me. It seems an integration test for macOS is failing.
