### ISSUE TITLE
custom dialog: button order is reversed

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#71251]
Testing #71116 
Mac, Insiders
`b9bcca2b9830df592892d63201704026c18dcbe5`

here's the code from my extension to get a modal dialog:

``` javascript
vscode.window.showWarningMessage('warning', { modal: true }, 'button1', 'button2', 'button3', 'button4', 'button5');
```

Native:
![image](https://user-images.githubusercontent.com/1487073/55042962-4089dc00-4ff1-11e9-8128-e8f1f1666d43.png)

Custom:
![image](https://user-images.githubusercontent.com/1487073/55043021-80e95a00-4ff1-11e9-851d-2b297c53c887.png)

I actually like the fact that the `Cancel` button is always rightmost in the custom dialog, not sure why it is like it is in the native one.

**Comment by sbatten** [comment]
@chrisdias I believe the layout is platform dependent. I don't think we need to adopt this behavior.

@bpasero thoughts?

**Comment by bpasero** [comment]
@sbatten I think we should try to stay close to platform expectations so that people on their OS feel familiar.
