### ISSUE TITLE
vscode crashs when sync button of source control providers clicked

### ISSUE THREAD

**Issue by energygreek** [Microsoft/vscode#71256]
Issue Type: <b>Bug</b>

we use git modules. when sync the git module branch, vscode will soon crash every time. but git branch not.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.90GB (6.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-fileheader|mik|0.0.2
cpptools|ms-|0.22.1
vetur|oct|0.17.1
cmake|twx|0.0.17
clang-format|xav|1.9.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by joaomoreno** [comment]
What does the crash look like? Can you share a screen recording? Can you run `Git: Show Git Output` before you record? Does it happen with any workspace?
