### ISSUE TITLE
terminal  current project path does not display

### ISSUE THREAD

**Issue by Yinyiran** [Microsoft/vscode#71252]
Issue Type: <b>Bug</b>

**ctrl+` open terminal  , current project path does not display** 

![捕获](https://user-images.githubusercontent.com/22965503/55043626-0f052500-5072-11e9-8c5e-68770093b0ef.PNG)
![捕获 PNG2](https://user-images.githubusercontent.com/22965503/55043632-1298ac00-5072-11e9-8a1c-f38906458d35.PNG)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (4.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
vusion-peek|lin|0.1.2
vscode-language-pack-zh-hans|MS-|1.32.4
vetur|oct|0.17.1
LiveServer|rit|5.5.1
code-settings-sync|Sha|3.2.7
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.4.0
local-history|xyz|1.7.0

(1 theme extensions excluded)

</details>

**Comment by TheAndroidGuy** [comment]
I have the same issue. I noticed that the path is not empty but there are a lot of newline characters and because your window height it appears to be empty but its up in the window (check scrollbar).

![image](https://user-images.githubusercontent.com/17319245/55047852-760ce480-5046-11e9-8589-b9fbae81911b.png)
