### ISSUE TITLE
[Custom Dialog] Dialogs are not centered when zoomed

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#71250]
#71116 Issue Type: Bug

1. Zoom workbench
2. Trigger modal.

**Expected:**
Modal to be centered per zoom level

![Screen Shot 2019-03-26 at 6 02 40 PM](https://user-images.githubusercontent.com/173559/55043037-8cd51c00-4ff1-11e9-970c-706b38eb6951.png)

**Actual:**
Modal is off center.

**Comment by sbatten** [comment]
@auchenberg isn't that centered with respect to the entire window?

**Comment by auchenberg** [comment]
@auchenberg Yes, I would expect modals/dialogs to be centered to the entire window, so in this case about 1/2 height up

**Comment by sbatten** [comment]
Ah vertically oops
