### ISSUE TITLE
Cannot set environment variable for WSL

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#71267]
```
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

#### Steps to Reproduce:

1. Open settings, add an entry
    ```json
    "terminal.integrated.env.windows": {
        "TEST_ENV_KEY": "a non-empty string"
    },
    ```
2. Set default integrated terminal to WSL
3. Open the terminal, run `echo $TEST_ENV_KEY`, the value is empty. Not as expected.

#### More info
During extension development I also find that, the API `vscode.window.createTerminal` cannot set the env for WSL either.

In my experiment I set custom envs in a powershell, and then launches wsl from the powershell, it turns out wsl.exe doesn't respect envs from its parent process. 

Does this issue occur when all extensions are disabled?: Yes (nothing to do with extensions)

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development

**Comment by aeschli** [comment]
The terminal opened in the WSL Remote Window is now a proper terminal. So to set an env variable, you use 
```
"terminal.integrated.env.linux": {
    "TEST_ENV_KEY": "a non-empty string"
},
```

I verified this works.
