### ISSUE TITLE
can't save file

### ISSUE THREAD

**Issue by hzbxt** [Microsoft/vscode#71268]
- VSCode Version:1.32.3 (user setup)
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
- OS Version:win 10

Steps to Reproduce:

1.after edit ,press ctrl+s ,can not save file .but menu:file->save can save.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
What exactly do you mean by "cannot save file"?
The file contents isn't saved to disk?
Is there an error showing?
Does this reproduce if you disable all extensions?

**Comment by weinand** [comment]
no reply -> closing.

**Comment by 40345839668** [comment]
It is recommended that you use the same browser on the first setup,which is also happening in the same browser,which will most likely register after 1 hour try again and continuously.
