### ISSUE TITLE
`organizeImports` can't reliably be used with `codeActionsOnSave`

### ISSUE THREAD

**Issue by rolandleth** [Microsoft/vscode#71265]
- VSCode Version: 1.32.3
- OS Version: 10.14.3

Steps to Reproduce:

1. Activate `source.organizeImports` inside `editor.codeActionsOnSave`.
2. Open any `js(x)` or `ts(x)` file.
3. Write an `import` statement.
4. Save the file before the `imported` item was used.
5. The `import` statement gets deleted, since `source.organizeImports` clears unused `imports`.

Since there's no setting for `source.organizeImports`, there's no way for these two features to be reliably used together, unless extra care is taken when using ⌘S. Extra care _can_ be taken, but I think features like this should reduce cognitive load, not increase it.

Does this issue occur when all extensions are disabled?: Yes

Sorry for opening a second issue, but the first one was wrongly created as "feature request".

A great day to everyone dropping by!

**Comment by mjbvz** [comment]
This is the designed behavior. Organize imports sorts and removes unused imports
