### ISSUE TITLE
Status bar reserve colsed picture's information

### ISSUE THREAD

**Issue by LiQuidFly** [Microsoft/vscode#71266]
Issue Type: <b>Bug</b>

step:
1.open a text file
2.open a picture
3.split editor
(now there are two file opened in left zone and one picture in right)
4.switch to text file of left zone
5.switch to picture of right zone
(now status bar shows picture's information)
6.close picture,meanwhile right zone also closed,now text file is active

result: status bar remain picture's information
expect: status bar only show text file's information

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
vscode-npm-script|eg2|0.3.5
beautify|Hoo|1.4.11
vscode-language-pack-zh-hans|MS-|1.32.4
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
rust|rus|0.5.4
crates|ser|0.4.0
open-in-browser|tec|2.0.0
vim|vsc|1.2.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by LiQuidFly** [comment]
It seems to be fixed in preview release.
