### ISSUE TITLE
Indent not working properly for Typescript files

### ISSUE THREAD

**Issue by JacopoSciampi** [Microsoft/vscode#71272]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. the json config looks like this

```
    "git.ignoreMissingGitWarning": true,
    "window.zoomLevel": 1,
    "explorer.confirmDelete": false,
    "workbench.colorTheme": "One Dark Pro",
    "workbench.iconTheme": "material-icon-theme",
    "breadcrumbs.enabled": true,
    "editor.fontLigatures": true,
    "editor.fontFamily": "Consolas, 'Trebuchet MS', monospace",
    "editor.fontWeight": "100",
    "explorer.confirmDragAndDrop": false,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.formatOnSave": true,
    "editor.tabSize": 4,
    "sonarlint.ls.javaHome": "C:\\Program Files (x86)\\Java\\jre1.8.0_201"
```
but when I saved the code is spaced to 2, and in the bottom bar I can see "Spaces: 2". After the save the json config isn't changed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Set `"editor.detectIndentation": false` and then set the spacing you wish for the file

**Comment by JacopoSciampi** [comment]
I've tried putting this configuration but it's not working either. How to set a custom configuration for spaceing by the file ext? SO quesiton: https://stackoverflow.com/questions/55357901/autoformat-on-save-with-4-tab-space
