### ISSUE TITLE
VS Code window crash

### ISSUE THREAD

**Issue by kookyle** [Microsoft/vscode#71270]
Issue Type: <b>Bug</b>

I opened a folder in VS Code, and the files in it would change with time, because I was doing some calculation involved with Python and others automatically. The time it crashed, I reopened the window ( There was a dialog box and I just clicked "reopen"). And after over 24 hours, it crashed again. And it has been crashed three times until today after approximate same time period.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (6 x 2660)|
|Memory (System)|11.98GB (4.93GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Version
---|---
python|2019.3.6139
csharp|1.18.0

</details>

**Comment by weinand** [comment]
Please provide a screenshot of VS Code and the dialog box when it is about to crash.
Is it only crashing when you are running your Python calculation?

**Comment by kookyle** [comment]
@weinand Thanks for your respond.
The following is the screenshot of VS Code, and the dialog box:

![image](https://user-images.githubusercontent.com/12111332/55074885-7485ff80-50cc-11e9-9a6c-9cbb998dbe50.png)

![image](https://user-images.githubusercontent.com/12111332/55076573-c16bd500-50d0-11e9-8d23-d064d786faf4.png)

And the dialog box appears after it crashed.
It should be noted that Python calculation is outside of the VS Code, it does not use Python extension of the VS Code. I run this calculation in the cmd, and I just keep VS Code open all the time.

**Comment by weinand** [comment]
It would be great if you provide more information about the crash by following this information:
https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kookyle** [comment]
@weinand Yeah, Debug Diagnostic Tools is running now. And all I could do now is to wait to next crash.

**Comment by kookyle** [comment]
@bpasero Well, I think the insider builds, get the latest release each day, is a little more frequent for me. And I am running a diagnostic tool as @weinand told me. I will provide more information about the crash until next crash.

**Comment by bpasero** [comment]
OK

**Comment by kookyle** [comment]
It crashed again. The following is the crash log file.
[Code__PID__25432__Date__03_28_2019__Time_09_28_25AM__848__Log.txt](https://github.com/Microsoft/vscode/files/3020641/Code__PID__25432__Date__03_28_2019__Time_09_28_25AM__848__Log.txt)

**Comment by kookyle** [comment]
@bpasero Recently, I try to reproduce this problem with nightly insider build. While doing my calculation, I keep VS Code - Insiders open continued for a about a week, and it works properly.
VS Code version: Code - Insiders 1.34.0-insider (05fc61ffb1aee9fd19173c32113daed079f9b7bd, 2019-04-17T05:20:44.358Z)
