### ISSUE TITLE
[scss] validate @imports as errors for not existing local files

### ISSUE THREAD

**Issue by znar** [Microsoft/vscode#71275]
Hello, when i import a none existing local scss file via @import no error is shown.

![image](https://user-images.githubusercontent.com/16944577/55066613-73c67c80-507e-11e9-8155-c6a52670a5e0.png)

But InteliSense works, availble local files are listed.

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

**Comment by aeschli** [comment]
It's very unlikely we will add this feature for two reasons:
- Performance: it requires the css/scss language server to observe file changes. 
- false errors: if we don't fully and correctly re-implement the scss import lookup there will be errors on imports that are actually valid. There are also plugins that allow additional import syntaxes (https://stackoverflow.com/questions/6502313/when-using-sass-how-can-i-import-a-file-from-a-different-directory)

While we provide some linting in the scss language server, we want to stay lightweight. You rather want to run your actual build script in watch mode, e.g. as a task, to get the errors.
