### ISSUE TITLE
Improve wording on workspace with no errors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7127]
![screen shot 2016-06-02 at 12 45 03](https://cloud.githubusercontent.com/assets/1926584/15742549/e75d624c-28bf-11e6-947b-34701a522a29.png)

'Clear' for me does not mean without errors. We need a better term here. Maybe something like
'No errors have been detected in the workspace so far'

You are also missing a dot at the end,

**Comment by sandy081** [comment]
Message "No errors have been detected in the workspace so far." looks good to me.. Updated it.
