### ISSUE TITLE
VS code appears to log to stdout/err while running

### ISSUE THREAD

**Issue by NeilMacMullen** [Microsoft/vscode#71289]
Start up a Powershell console
Run VsCode as a background process...

`& "C:\Users\NeilM\AppData\Local\Programs\Microsoft VS Code\Code.exe"  somefile.txt`

After a while you will see output similar to 

> [main 2019-03-27T12:10:23.447Z] update#setState idle
> [main 2019-03-27T13:10:23.262Z] update#setState checking for updates
> [main 2019-03-27T13:10:23.492Z] update#setState idle

in the Powershell window.

**Comment by martea** [comment]
second.... suddenly got the issue also on vscode in powershell...

**Comment by martea** [comment]
Now i discovered that is was related to if the terminal was "run as adminsitrator" or not..

**Comment by joaomoreno** [comment]
Inside VS Code's installation folder there's a `bin` folder. Inside, there's a `code` executable. That's the one that should be on the PATH to be running.

**Comment by NeilMacMullen** [comment]
@joaomoreno  Not sure if you're replying to me or @martea?  I'm simply using the path from the taskbar/shortcut for VSCode.  Are you suggesting there is another version of code.exe installed alongside that I should be using?

**Comment by joaomoreno** [comment]
To both, actually. When Code is installed, it adds the `bin` folder to the PATH. Can you show me your PATH variable?

**Comment by NeilMacMullen** [comment]
The path is "C:\Users\neilm\AppData\Local\Programs\Microsoft VS Code\bin"

I think what you actually meant is to run the code.CMD *batch* script, rather than the code.EXE *executable*  in the folder above it?  Running it this way does avoid the spurious output.

**Comment by joaomoreno** [comment]
Good suggestion, I'll keep it in mind. Glad to know you're unblocked now, closing this.

**Comment by NeilMacMullen** [comment]
Thanks for your help! :-)

**Comment by martea** [comment]
@joaomoreno for me the issue was that i was running powershell as normal user, and code was set to run as administrator, dont know if thats a known issue or not.
