### ISSUE TITLE
Do not hide last debug session if there ever were more than one

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#71288]
I'm running the latest VS Code out of source.

- start cluster sample
- terminate all child sessions but not the main session

Observe:
after killing the last child, the cluster debug session disappears and the Call Stack view becomes empty. This is confusing since the debug session continues.

The reason for this behavior is probably the optimization to hide session nodes when there is only one session. We should disable this optimization whenever there were more than one session.
And after the session count has fallen to 0, the optimization can be enabled again.

**Comment by isidorn** [comment]
Good idea.

**Comment by weinand** [comment]
works fine!
