### ISSUE TITLE
Add the ability to add fileds to the source control sidebar

### ISSUE THREAD

**Issue by sketchbuch** [Microsoft/vscode#71287]
The company I work at uses commitlint where you have to specify a type from a fixed list and an optional scope plus the normal commit message.

I would like to have a select here for commitlint types and an extra text field for the scope. Currently you can't edit GUI elements like this with an extension. Will this be changed in the future? I would write an extension myself to do this if it was possible.

**Comment by joaomoreno** [comment]
The git extension exposes access to the commit input box: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/api/git.d.ts#L125

Your extension can [reach out to the git extension](https://github.com/Microsoft/vscode-pull-request-github/blob/ca8204b9084b5786df351b6a1102eca8719733a9/src/git/model.ts#L11) and populate the input box at will.
