### ISSUE TITLE
Explorer: moving with Alt-key no longer copies but moves

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#71280]
Steps to Reproduce:

1. drag a folder or file around with Alt+key pressed (you should see a plus icon)
2. drop somewhere
3. => 🐛 the file/folder is moved but not copied

**Comment by isidorn** [comment]
I can not repro.
It copies nicely. Just the plus is missing (I see this also on stable).
On what platform are you? I tried os x.

![heyBen](https://user-images.githubusercontent.com/1926584/55072941-bf802280-508c-11e9-83b2-e8803bbbc5b9.gif)

**Comment by bpasero** [comment]
@isidorn I see this on macOS and Linux running out of sources.

**Comment by bpasero** [comment]
@isidorn it actually works for me if I first press Ctrl+key and then start to drag but does not work if I first start to drag and then press Ctrl.

**Comment by bpasero** [comment]
I cannot reproduce that in stable though.

**Comment by bpasero** [comment]
It is probably this change: https://github.com/Microsoft/vscode/commit/a3198370c891507b4fdbf4e113c18e0db49883ce#diff-18552b0ae82758a2b0227eb483bdc8d8

**Comment by isidorn** [comment]
Yes I acknowledge that issue. And yes it is that change. Will fix
