### ISSUE TITLE
Clicking outside error list focuses the tree and produces an ugly blue outline

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7128]
Clicks outside the error list should simply be ignored.
Currently the error list tree gets focused which as a result has an ugly blue line

![screen shot 2016-06-02 at 12 53 32](https://cloud.githubusercontent.com/assets/1926584/15742737/09cf98a8-28c1-11e6-9651-eb1343a5b3e2.png)

**Comment by sandy081** [comment]
@isidorn This is the default behavior from our tree library. I think this is true at all places where tree is being used. 

I agree that this is not looking nice. Will look into this. Thanks.

**Comment by isidorn** [comment]
It is more promiment for your use case because the tree does not take the full area which you have.
I think you can look into having a tree controller which could ovewrite onClick methods to not focus the tree - check that out.
