### ISSUE TITLE
Pointless annoying flash on Source Control icon

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [Microsoft/vscode#71297]
Issue Type: <b>Feature Request</b>

Please stop the pointless annoying time indicator over the source control icon.

To repo, open vscode on a git project with no changed files. The source control icon on the left flashes a little clock icon every few seconds. My peripheral vision picks this up without  telling me what it is, breaking my concentration. 

Please get rid of this ASAP. If the house is on fire it's fine to make something flash, but indicating normal operation with a flashing visual is just awful.

![image](https://user-images.githubusercontent.com/10535302/55087954-2212f780-5068-11e9-9e12-341dbc273d42.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
The setting is `"git.showProgress": true`
