### ISSUE TITLE
New Command task input types

### ISSUE THREAD

**Issue by augustocdias** [Microsoft/vscode#71296]
I have a suggestion for 2 input types for tasks configuration.
1. Input file. It would list files from a specified directory (recursively or not)
2. Shell command. I think it would be useful to have a custom input for tasks that could be the output of a shell command. My use case for example:
I want to pick a file from my project to use as input from a task, so I thought I could run the command `find cypress/integration -type f` and have each line result as a possible input for my task. I know the 1st suggestion solves my use case, but I think it might be useful anyway to have this possibility.

**Comment by alexr00** [comment]
If you need to run code as part of your "task" setup, then a command is probably a better fit! Tasks is intended to be for putting together existing building blocks or, in the case of the new CustomExecution task type (documentation will be added to the tasks VS Code docs soon), running a typescript callback. If the actual setup for your task requires that you pipe the outpu from one thing into another thing, then commands are the existing way to do that!

**Comment by augustocdias** [comment]
@alexr00 I didn't get it... As far as I understood the command type in the tasks is intended for vscode commands and not shell commands. I want to be able to choose a file from my project to use as input for a task... I was reading [this  page](https://code.visualstudio.com/api/references/commands) and I could not find any command that would fit my use case for example (I want to run a specific [cypress](http://cypress.io/) test which I would choose from a list of files from a particular directory). 
Did I understand it wrong?

**Comment by alexr00** [comment]
I was suggesting that you write your own command.

**Comment by augustocdias** [comment]
Is it doable without creating a whole extension for it?
I could not find any doc... Could you give me an example?

**Comment by alexr00** [comment]
https://code.visualstudio.com/api/extension-guides/command

**Comment by augustocdias** [comment]
Well... Writing an extension would totally solve the problem, but I do believe that it is overkill for what I'm trying to do...

**Comment by augustocdias** [comment]
@alexr00 I'm doing as you suggested and creating a vscode command and I have one question which I could not find the answer yet
Let's say I have this config for my tasks for example:

```
"inputs": [
    {
      "id": "inputTest",
      "type": "command",
      "command": "shellCommand.execute",
      "args": {
        "command": "ls",
        "cwd": "${cwd}/.vscode"
      }
    }
  ]
```


In my command code, how can I resolve the `${cwd}`? 

   ```
const cwd = args['cwd'] || vscode.env.appRoot;
```

When I execute this, the `cwd` variable is not resolving the `${cwd}` placeholder.
