### ISSUE TITLE
Jupyter Notebook suddenly required to run python script??

### ISSUE THREAD

**Issue by ronnies007** [Microsoft/vscode#71299]
Issue Type: <b>Bug</b>

Yesterday everything worked fine. Today I cant start a single script. tried it on two seperate computers. it didnt work.
thants the error message: 'Executing code failed : Error: Running cells requires Jupyter notebooks to be installed.'

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|14.93GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
py-paste-indent|hye|0.1.1
python|ms-|2019.3.6139
jinja|who|0.0.8

</details>

**Comment by ronnies007** [comment]
I fixed it by right clicking on the python extension and selecting 'install another version'
then I chose the version right below the active one.

**Comment by gramster** [comment]
Issue moved to [Microsoft/vscode-python #4962](https://github.com/Microsoft/vscode-python/issues/4962) via [**ZenHub**](https://www.zenhub.com/)
