### ISSUE TITLE
Horizontal scroll breaks rendering in tree

### ISSUE THREAD

**Issue by rodriguescelio** [microsoft/vscode#71291]
Issue Type: <b>Bug</b>

When I am going to rename a file that has a name bigger than the width of explorer the vertical scrollbar loses its position and goes to the middle of window.

Bug still happening with all extensions disabled.

Steps to reproduce:
- Create new file with large name
- Try to rename

Example:
![Example](http://i68.tinypic.com/ngwz6f.jpg)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100T CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.8
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.8.2
php-debug|fel|1.13.0
svn-scm|joh|1.47.9
hex-fmt|ker|1.0.0
code-fragments|mar|1.2.0
rainbow-csv|mec|1.0.0
vs-deploy|mkl|14.0.0
hg|mrc|1.3.0
vscode-language-pack-pt-BR|MS-|1.32.5
Go|ms-|0.9.2
live-server-preview|neg|0.1.4
vetur|oct|0.17.1
material-icon-theme|PKi|3.7.0
phpdoc-comment-vscode-plugin|rex|1.1.0
ayu|tea|0.18.0
vscode-icons|vsc|8.4.0
vscode-wakatime|Wak|1.2.13

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I can not reproduce.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by rodriguescelio** [comment]
In vscode insiders the error doesn't occur, I noticed that in the insiders build the file explorer doesn't have a horizontal bar, all files are abbreviated with '...', this probably solves the problem.

**Comment by isidorn** [comment]
Then it should be fixed in latest. Thus closing
I also tried reproducing with tunring on horizontal scroll in explorer and could not.

p.s also try to disable horizontal scroll, "workbench.list.horizontalScrolling": false

**Comment by rodriguescelio** [comment]
@isidorn, if I set "workbench.list.horizontalScrolling" to false everything works fine!

But I run a test on insiders build setting "workbench.list.horizontalScrolling" to true and the bug appears, you can see the result bellow:

"workbench.list.horizontalScrolling": false
!["workbench.list.horizontalScrolling": false](https://media.giphy.com/media/52EP35OCKQXApI5BwO/giphy.gif)

"workbench.list.horizontalScrolling": true
!["workbench.list.horizontalScrolling": true](https://media.giphy.com/media/1zKvMakq45zPjHPNb5/giphy.gif)

I used this folder to run the test https://mega.nz/#!458SUSqY!cWEXvdO37jcgzLEUuD1-H3XKEvquS0ELm5_hM7v4n4g

**Comment by isidorn** [comment]
Ok, reopening and assigning to @joaomoreno 
I can not reproduce

**Comment by joaomoreno** [comment]
Very much reproducible. Not great!

**Comment by jeanp413** [comment]
While looking into this I found #72626

**Comment by jeanp413** [comment]
This also happens in the debug viewlet
![bug-horizontal-scrolling](https://user-images.githubusercontent.com/25115070/57979362-3fb66a80-79e2-11e9-8c4b-8916213f7f5d.gif)

**Comment by isidorn** [comment]
Yes, every tree in vscode is affected by this.

**Comment by jeanp413** [comment]
@joaomoreno I can still repro this in the explorer too while renaming a file with a very long filename

**Comment by joaomoreno** [comment]
Yeah I am able to repro, after all.
