### ISSUE TITLE
Showing only errors message superfluous

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7129]
I believe that the 'showing only errors' message is unnecessery - we should have a nice toggle icon which would make it clear what is being shown.
We also do not have this pattern (to write what is being filtered) anywhere else (search / find widget) 

![screen shot 2016-06-02 at 12 54 42](https://cloud.githubusercontent.com/assets/1926584/15742776/4088c716-28c1-11e6-873e-c629da826c98.png)

**Comment by sandy081** [comment]
@isidorn I agree that we need a nice toggle icon here.. I already asked Steven for this.

**Comment by sandy081** [comment]
Removed the error toggle icon completely and one can use filter textbox to filter errors/warnings/infos
