### ISSUE TITLE
Call Hierarchy: Same ids being used for separate tree items

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#71298]
Refs: #71083

From this screenshot, I have a feeling we might be giving the same ID to different tree items, in Call Hierarchy?

![Screenshot from 2019-03-27 16-16-22](https://user-images.githubusercontent.com/22350/55088264-bb173200-50ab-11e9-9c8b-be517abf8538.png)

**Comment by jrieken** [comment]
good guess: https://github.com/Microsoft/vscode/blob/e4e0eb0637feabd0a180be031ab9eaba2490dbf3/src/vs/workbench/contrib/callHierarchy/browser/callHierarchyTree.ts#L54-L56
