### ISSUE TITLE
Staged changes tool icons hides if filename is too long

### ISSUE THREAD

**Issue by ppizarror** [Microsoft/vscode#71294]
Issue Type: <b>Bug</b>

The scrollbar pushes the icons of staged changes (toolbar) away. Also i'm unable to see git information about each file. Maybe related to #71291

![image](https://user-images.githubusercontent.com/12925256/55083806-dc175d00-5082-11e9-9aa2-30fa5e7109ad.png)
![image](https://user-images.githubusercontent.com/12925256/55083848-f05b5a00-5082-11e9-87a6-b5f7146f0915.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.90GB (4.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
vscode-glsllint|CAD|0.0.5
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-ipaddress|Com|1.0.0
excel-to-markdown-table|csh|1.1.0
vscode-markdownlint|Dav|0.25.1
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
jquerysnippets|don|0.0.1
gitlens|eam|9.5.1
toggle-excluded-files|eam|1.6.0
matlab-runner|eam|0.3.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
windows-explorer-context-menu|ele|2.0.0
vsc-material-theme|Equ|2.8.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
code-runner|for|0.9.7
vscode-opencl|gal|0.5.2
matlab|Gim|0.9.0
gc-excelviewer|Gra|2.1.29
beautify|Hoo|1.4.11
JSDocTagComplete|Hoo|0.0.2
minify|Hoo|0.4.2
latex-workshop|Jam|6.2.2
vscode-language-opensees|jam|0.1.2
mark-as-excluded|jcm|0.2.6
vscode-cudacpp|kri|0.1.1
pasteurl|kuk|0.4.3
markdown-shortcuts|mdi|0.11.0
vscode-filesize|mkx|2.1.2
python|ms-|2019.3.6139
cpptools|ms-|0.22.1
vscode-paste-image|mus|1.0.4
hide-gitignored|npx|1.0.1
material-icon-theme|PKi|3.7.0
tcl|ras|0.1.0
java|red|0.41.0
closure-compiler|rua|1.2.12
explorer-excluded-files|sad|1.0.0
code-settings-sync|Sha|3.2.7
stylelint|shi|0.48.0
matlab-snippets|sky|1.11.0
shader|sle|1.1.4
addDocComments|ste|0.0.8
vscode-markdown-paste-image|tel|0.12.0
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.3.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
vscode-wakatime|Wak|1.2.13
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.2.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
#68027
