### ISSUE TITLE
Debug console switcher doesn't do anything

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#71306]
- Debug two things
- Open the debug console dropdown, select a different session
- Nothing happens

**Comment by octref** [comment]
Same thing for me, although I'm using the compound debug target here: 

https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/.vscode/launch.json#L38-L43

- Switch to "Launch Client"
- Click "Terminal"
- Click "Debug Console"
- 🐛 Target is back to "Attach to Server"

**Comment by isidorn** [comment]
Thanks for reporting and for self-hosting!
