### ISSUE TITLE
Oddity in navbar dragging

### ISSUE THREAD

**Issue by buffet-time** [Microsoft/vscode#71307]
- VSCode Version: 1.30.1
- OS Version: Windows 10 x64 (1803)

Steps to Reproduce:

1. Open VSC
2. Move mouse to the right of the "help" button on the top navigation bar
3. click and hold and attempt to drag
4. the windows is not draggable from this point when logically it should.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
This is fixed in more recent builds of VSC.

/duplicate
