### ISSUE TITLE
Custom dialog service fonts too large

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#71305]
Running with the custom dialog service.
All dialogs are large, way too large. It uses fonts that are at least twice as large as the second largest font.

![image](https://user-images.githubusercontent.com/4674940/55098620-547a2000-507b-11e9-9ccc-fedf220af1a4.png)

**Comment by sbatten** [comment]
To mimic the behavior of native, I've now made it so if only a message is provided, the normal (smaller) font is used. If both a message and details are provided, the details will use the smaller font. The above dialog uses only message, but probably should separate the two into message + details.
