### ISSUE TITLE
Add branch name to branch hover tooltip

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#71304]
## Proposal
When hovering over large branch names, the branch name should be shown in the tooltip instead of static text <kbd>check out ...</kbd>.

## Current Situation
![Git branch](https://user-images.githubusercontent.com/9283914/55095846-24517200-50b9-11e9-81ee-1106eaf3c3c8.png)

## Desired Situation
![Git branch2](https://user-images.githubusercontent.com/9283914/55095854-29162600-50b9-11e9-9d41-c752689b100f.png)

**Comment by abhinavdc** [comment]
Hi, I would like to try fixing this bug. Could anyone point out to me where I should start looking ?

**Comment by marmikc** [comment]
Hi! If this issue is not being worked on, I would like to try tackle it. May I do so?

**Comment by rthaneda** [comment]
@abhinavdc @marmikc have either of you progressed on this issue? if not I would be interested as well

**Comment by Daniel-McCarthy** [comment]
I have looked into this issue and found the relevant area of the code base, `/vscode/extensions/git/src/statusbar.ts`. I have taken a swing at solving this and will submit a pull request soon.

**Comment by marmikc** [comment]
I did not realize someone had created a PR for the issue, I thought I was free to work on it, I apologize for any confusion. I've looked at both and they are functionally the same fix.
