### ISSUE TITLE
Extensions smoke test fails

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#71319]
On macOS:

```
yarn smoketest --build /Applications/Visual\ Studio\ Code\ -\ Insiders.app/
```

```
    Extensions
** Timeout!
Did not pass accept function
      1) install and activate vscode-smoketest-check extension
```

Pauses here:

<img width="1030" alt="Screen Shot 2019-03-27 at 2 59 47 PM" src="https://user-images.githubusercontent.com/2193314/55115216-36bfb180-50a1-11e9-88cf-91706a89e47f.png">

---

VS Code version: Code - Insiders 1.33.0-insider (1afeb46cc4f2856ed6d0759fff85b13647c7ab83, 2019-03-27T16:02:22.809Z)
OS version: Darwin x64 18.2.0

**Comment by sandy081** [comment]
Caused by this [commit]( https://github.com/Microsoft/vscode/commit/fa1c88a4e1beb7a24c82d5c42e62a0b3973af12c#diff-24be943a039f2e8a3badc3d5186d4d02) that disabled extensions in smoke test. 

@roblourens Why was this done?

**Comment by Tyriar** [comment]
@sandy081 it was needed because smoke tests run in a remote context will pick up existing remote extensions, I think we need a remote extensions dir option if we need this?

**Comment by sandy081** [comment]
May I know what happens if the remote extensions are picked up? 

I think it makes sense to create a separate issue and discuss about it there.
