### ISSUE TITLE
Intellisense read more close button has 1px wide left side that makes the cursor freak out

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#71317]
![hover](https://user-images.githubusercontent.com/2193314/55113587-e9d9dc00-509c-11e9-9144-4918406291ce.gif)

Version: 1.33.0-insider (user setup)
Commit: 1afeb46cc4f2856ed6d0759fff85b13647c7ab83
Date: 2019-03-27T16:09:48.043Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18860

**Comment by kostyabushuev** [comment]
hello
i would like to help to fix this bug
**[PR](https://github.com/Microsoft/vscode/pull/71488)**

**Comment by joaomoreno** [comment]
Can't repro, but removed CSS `float`. @Tyriar let me know if that helps.
