### ISSUE TITLE
TS error 

### ISSUE THREAD

**Issue by axe-z** [Microsoft/vscode#71314]
![Capture d’écran, le 2019-03-27 à 16 40 43](https://user-images.githubusercontent.com/27289270/55110739-13036800-50af-11e9-8f75-e62f1b18226e.png)
test the latest, and without extensions 

- VSCode Version: 1.32.3
- OS Version: 10.14.3

Steps to Reproduce:

1. open a ts filfe 
2. enter a fn 

 let a: number = 4

function isPair(nombre: number):boolean  {
		return nombre % 2 === 0
}
console.log(isPair(a)) 

![Capture d’écran, le 2019-03-27 à 16 40 18](https://user-images.githubusercontent.com/27289270/55110714-02eb8880-50af-11e9-9954-253126309a46.png)

**Comment by mjbvz** [comment]
What other files are in your workspace? What does running `go to definition` on `isPair` show?
