### ISSUE TITLE
Clicking on the error does not pass focus to editor if editor already open

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7131]
- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. have some errors, open error list
2. click on the error - notice how the focus nicely moves to the editor
3. click on the same error again - editor looses focus

I would expect that the behavior is the same if I click first, second or third time...
The issue is that the focus is not passed to editor if that editor is already opened

**Comment by sandy081** [comment]
@isidorn This is a nice catch.. I am sure it is working before I merged to master. Need to check if something changed

**Comment by sandy081** [comment]
#7146 is similar and has more information. Hence marking this as duplicates #7146
