### ISSUE TITLE
Failed to create terminal for task 

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#71311]
- Paste the tasks from #70774 into the vscode repo's tasks.json file
- Start the watch task
- Kill the terminal before the build is totally done
- Get an error popup `Failed to create terminal for task `

**Comment by alexr00** [comment]
A bad merge deleted the fix for the original issue 😓

**Comment by alexr00** [comment]
duplicate of #70557

**Comment by alexr00** [comment]
Actually not a bad merge. Fixing again.
