### ISSUE TITLE
Compound debugging: Output from client is hidden

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71325]
Version: 1.33.0-insider
Commit: 627c7f730a776ef6efb8762e9379b8c7e71e417b
Date: 2019-03-27T20:46:19.398Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

- Clone the lsp-sample, and add a `console.log` in `extension.ts`'s activate function: https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/client/src/extension.ts#L18
- Compile, launch "Client + Server" debug config
- Switch to "Launch Client", nothing shows 🐛 
- Detach from server config
- Now "Launch Client" shows `console.log` output

![gif](https://user-images.githubusercontent.com/4033249/55116941-4e4d6900-50a6-11e9-8165-cfd651229196.gif)

**Comment by isidorn** [comment]
Dup of #71306
