### ISSUE TITLE
Error list: screen cheese with filter

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7132]
Click on the filter icon twice, notice blue outline is not fully outlined - screen cheese

![screen shot 2016-06-02 at 15 00 08](https://cloud.githubusercontent.com/assets/1926584/15745580/cacb8830-28d2-11e6-9ddf-635ee8be019b.png)

**Comment by sandy081** [comment]
This looks like an issue in panel title/toolbar. Since, it is also true in other panels

**Comment by sandy081** [comment]
This is no longer the case. Hence closing this.
