### ISSUE TITLE
Disabling editor.suggest.filterGraceful does not work as intended.

### ISSUE THREAD

**Issue by jsunsawyer** [Microsoft/vscode#71327]
Option had been added here: https://github.com/Microsoft/vscode/issues/52789

My expectation is that unchecking this setting should force my autocomplete to not use fuzzy search when displaying suggestions.

Nothing seems to be different whether this is toggled on or off.

**Comment by jrieken** [comment]
This explained what it does: https://code.visualstudio.com/updates/v1_19#_smarter-intellisense and works as promised. It seems you want something completely different, please file a separate feature request for that.

**Comment by jsunsawyer** [comment]
@jrieken I don't see any reference to `editor.suggest.filterGraceful` in that link. I thought that the issues leading up to the addition of this option had already requested the functionality that I want this setting to do, and what the setting label describes that it does.

When I disable this setting:
![Screen Shot 2019-03-28 at 9 02 00 AM](https://user-images.githubusercontent.com/1007191/55173165-75547b00-5138-11e9-87c4-306146ffc3a2.png)

Then type `true` in a json file, I get:
![Screen Shot 2019-03-28 at 9 02 22 AM](https://user-images.githubusercontent.com/1007191/55173207-84d3c400-5138-11e9-85d9-3633bdaa6980.png)

I'm just trying to eliminate some of the autosuggest spam. Is this not the proper option to use to achieve that?

**Comment by jsunsawyer** [comment]
@jrieken Sorry, it seems that you have already shot down the functionality that I want. https://github.com/Microsoft/vscode/issues/64367

Please reconsider and reopen #64367

**Comment by jsunsawyer** [comment]
@jrieken Still having trouble figuring out a way to customize the editor to my liking and this is especially driving me crazy.

Are you sure that this feature is working as intended?

See: https://github.com/Microsoft/vscode/issues/52789#issuecomment-401729341
