### ISSUE TITLE
在小窗口启动VUE项目时候，会有BUG 端口显示错误 

### ISSUE THREAD

**Issue by xl-youcanknow** [Microsoft/vscode#71331]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by xl-youcanknow** [comment]
![image](https://user-images.githubusercontent.com/38066533/55122426-ef393400-5139-11e9-8748-dab23bc8cbd1.png)

**Comment by xl-youcanknow** [comment]
端口错误，但是如果8080端口未占用的情况下 输入http://192.168.20.254:8080 仍能打开项目

**Comment by weinand** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
