### ISSUE TITLE
vscode设置的字体大小在vue文件无效

### ISSUE THREAD

**Issue by suwei0708** [Microsoft/vscode#71336]
如题，.html文件就是设置的大小，但是.vue文件就是默认的大小，怎么设置都无效

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7600

**Comment by weinand** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
