### ISSUE TITLE
Click on error icons in status bar should toggle error list

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7133]
Click on the error icons in the status bar - notice error list poping up.
Click on the error icons again - I would expect the error list hides, thus the error icons in status bar behave as a toggle - similar to how the debug console icon behaves in the debug viewlet.

Just my expectation.
@stevencl feedback welcome

**Comment by sandy081** [comment]
@isidorn I do not know what is desired behavior here... but I expect to see problems view showing errors and warnings when I click on the errors icons in the status bar. 

This was the same behavior before with the command pallette. I know that command pallette is not togglable where as panels are.
