### ISSUE TITLE
Can not expand the variables in the watch list

### ISSUE THREAD

**Issue by Tragicalone** [Microsoft/vscode#71332]
Issue Type: <b>Bug</b>

Hi,

I  can see all the properties of variables in the watch list before. However, I found I can not expand the variables in the watch list since yesterday. There were no signal "+" on the left side of the variable. I used two different computers and found the same problem. I would think this should be the bug of the new verson of Visual Studio Code. Does anyone get the same proplem?

Frank Chen

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8400  @ 2.26GHz (2 x 2261)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.00GB (0.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.32.4
python|ms-|2019.3.6139
notepadplusplus-keybindings|ms-|1.0.2
team|ms-|1.149.2

</details>

**Comment by isidorn** [comment]
Can you reproduce using vscode insiders
https://code.visualstudio.com/insiders/

**Comment by Tragicalone** [comment]
OK. I tried vscode insiders. And the situation continues.
There is no arrow on the left side of watch list.
![image](https://user-images.githubusercontent.com/42540343/55200338-aac09d80-51f8-11e9-9e8a-1f1875421415.png)

**Comment by isidorn** [comment]
Wait how do you have a minus on the side of the watch expression?
Anyways please file  this against python extension
