### ISSUE TITLE
开多个窗口cpu占用率太高原因是工作区中有多个项目,每个项目有大量文件

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#71342]
- VSCode Version:
- OS Version:
版本: 1.32.3 (user setup)
提交: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
日期: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

-----------------------------------------------------------------------------------
我开了三个窗口,每个窗口都是独立的工作区,每个工作区中又有多个文件夹.
当文件夹都含有大量文件时,会导致CPU马上升到100%
我觉得你们的工作区环增设计的很不合理.特别是工作区是VUE的项目,每个的文件夹下有多个node_modules,这样大量的文件,会导致启动慢,而且CPU占用率很高. 
----------------------------------------------------------------------------------------
I opened three windows, each of which was a separate workspace with multiple folders in each workspace.
When folders contain a large number of files, it will cause the CPU to rise to 100% immediately.
I think your workspace ring design is very unreasonable. Especially the workspace is a VUE project. There are many node_modules under each folder. Such a large number of files will lead to slow startup and high CPU usage.
----------------------------------------------------------------------------------------

![22](https://user-images.githubusercontent.com/10474968/55132682-2ae5f500-515e-11e9-87ba-57cbdc0d4f75.png)
![44](https://user-images.githubusercontent.com/10474968/55132683-2b7e8b80-515e-11e9-9ade-bebdcd2ad272.png)
![55](https://user-images.githubusercontent.com/10474968/55132685-2b7e8b80-515e-11e9-9ef3-fa923de6b434.png)

----------------------------------------------------------------------------------------
我是没有办法才要用工作区,非常不好. 具体看这个反馈的内容
https://github.com/Microsoft/vscode/issues/69742

因为当我用Ctrl+p来定位一个文件时,整个工作区中的同名文件都出来了,我当然只要我当前文件夹中的这一个.这导致VS要搜索工作区中所有文件.
以前我是用文件夹方式,一个窗口开一个文件夹,这样CPU和内存占用率就低一些.

I have no way to use the workspace. It's very bad. Look at the feedback.
Https://github.com/Microsoft/vscode/issues/69742
Because when I use Ctrl + P to locate a file, the same name files in the whole workspace come out. Of course, I only need this one in my current folder. This causes VS to search all files in the workspace.
----------------------------------------------------------------------------------------
In the past, I used to use folder mode, a window opens a folder, so that CPU and memory occupancy is lower.

![88](https://user-images.githubusercontent.com/10474968/55132842-b65f8600-515e-11e9-88d4-209c64402b57.png)

总的来说就是因为我安装的扩展太多了,而VS code是只能根据工作区来禁用扩展.
当我用多个工作区后,文件多了引响搜索或是定位文件有多余不需要的出现.
----------------------------------------------------------------------------------------
Generally speaking, because I installed too many extensions, VS code can only disable extensions based on workspace.
When I use multiple workspaces, there are more files that trigger searches or locate files that don't need to appear.

**Comment by lifetin** [comment]
![10](https://user-images.githubusercontent.com/10474968/55133512-e9a31480-5160-11e9-8f2f-e906d8876fcf.png)
![99](https://user-images.githubusercontent.com/10474968/55133514-e9a31480-5160-11e9-9070-dd79a3b5af98.png)

我只修改了VUE工作具中的一个文件,导致CPU又到了100%
---------------------------------------------------------------------
I only modified one file in the VUE workbench, resulting in CPU reaching 100%.

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. 

When Code is consuming lots of CPU, please run "`code --status`" from the command line (or "`code-insiders --status`" if you are using VS Code Insiders edition). 

Please attach the output of this command to this issue. Thanks!
