### ISSUE TITLE
Error list: filter needs more UX love

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7134]
Open the error list filter and notice:
* input box has a black outline - seems out of style compared to our other input boxes
* input box pushes the tree lower - leaving the space above the tree empty. I find this strange and not elegant
* 'Type to Filter' seems like a strange message, in the find widget we just say 'Find' not 'Type to Find'

![screen shot 2016-06-02 at 15 06 54](https://cloud.githubusercontent.com/assets/1926584/15745733/b311a8fe-28d3-11e6-9683-3c70fa38ec8f.png)

ping @stevencl @bgashler1

**Comment by Tyriar** [comment]
The collapse all icon is a little weird as well, similar but inconsistent with the close all button in open editors and also easily mistaken for it. Plus the `-` is blue:

![image](https://cloud.githubusercontent.com/assets/2193314/15765667/3b9f0e06-28ec-11e6-92f1-7721ca32901d.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15765673/41234734-28ec-11e6-883f-6d48073201d4.png)

**Comment by sandy081** [comment]
@Tyriar This is the same button that is also used in Search view and Explorer view.

**Comment by sandy081** [comment]
Moved filter box to the title bar which fixed the mentioned issues in the description.
