### ISSUE TITLE
White screen at the start

### ISSUE THREAD

**Issue by klys** [Microsoft/vscode#71347]
Issue Type: <b>Bug</b>

Im using a dark theme, in all, browser, system, to be able to work at night and because white or lighter colors in the screen burn my eyes.

But when i start this app, it first appear a big white window of nothing and then the app appear. 

Very annonying. Good reason for not opening it.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by aeschli** [comment]
If you switch to a dark theme in VSCode, exit VSCode and restart, do you still see this?

We remember the last used theme when closing a window and apply it right away when starting up. So maybe the last time you exited VSCode there was a light theme active?
