### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by Tengxuerong** [Microsoft/vscode#71346]
My vs code can't appear icon of collapse expand code block.I make it unload and download it again.But it still not appear icon of collapse expand code block.And my operating system is ubuntu.I hope you can give me some help.
![2019-03-27 15-43-11屏幕截图](https://user-images.githubusercontent.com/48267152/55134593-2ae8f380-5164-11e9-9bfc-69095e434f10.png)

**Comment by aeschli** [comment]
Do you have the accessibility support enabled?
![image](https://user-images.githubusercontent.com/6461412/55226923-765bda00-5216-11e9-9e49-401952a979ad.png)

Folding is disabled in accessibility mode.

**Comment by Tengxuerong** [comment]
![图片](https://user-images.githubusercontent.com/48267152/55228040-12580680-5254-11e9-8f24-307739d9af09.png)
It's success.Thank you very much for your help.
