### ISSUE TITLE
In rare cases TAB key doesn't insert tab/spaces in source code

### ISSUE THREAD

**Issue by fandecheng** [Microsoft/vscode#71345]
Issue Type: <b>Bug</b>

In rare cases TAB key doesn't insert tab/spaces in source code. Instead, it jumps between UI elements. I don't know how to reproduce it yet, but I've seen it once in this version.

FYI. I'm editing scala code. Opening a new VSCode window and closing the old one can work around the issue.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.68GB (16.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
scala|dal|0.0.5
xml|Dot|2.4.0
json-escaper|jos|1.1.0
csharp|ms-|1.18.0
PowerShell|ms-|1.11.0
vscode-json-editor|nic|0.2.3

</details>

**Comment by alexandrudima** [comment]
@fandecheng We have a an accessibility related action called "Toggle Tab Key Moves Focus". Once executed, <kbd>Tab</kbd> will no longer insert a tab character/space, but will jump focus to the next focusable element.

This state is indicated in the status bar with the following new status bar entry:
![image](https://user-images.githubusercontent.com/5047891/55317732-67bd2f00-5471-11e9-8fbf-bad390878f16.png)

If you click the status bar entry or if you execute the command again, then this mode is left and <kbd>Tab</kbd> will return to the default of inserting tabs/spaces in an editor.
