### ISSUE TITLE
Typo mistake in Intellisense configuration

### ISSUE THREAD

**Issue by RicaBenhossi** [Microsoft/vscode#71356]
Issue Type: <b>Bug</b>

There is an option in Vsintellicode > Modify > Editor: Suggest Selection that has a typo mistake: it's written AutomaticallyOverrOde instead of AutomaticallyOverrIde.
![image](https://user-images.githubusercontent.com/15204313/55144324-5695ba80-511f-11e9-9238-391d7cd634df.png)

VS Code version: Code - Insiders 1.33.0-insider (2e6db8d955046349a941ab814183cf480b0e274b, 2019-03-28T06:14:42.995Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1715)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.68GB (0.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.0
project-manager|ale|10.4.0
gitkraken-glo|axo|1.1.0
vscode-django|bat|0.19.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
git-extension-pack|don|0.1.3
githistory|don|0.4.6
jupyter|don|1.1.5
python-extension-pack|don|1.4.0
gitlens|eam|9.5.1
vscode-mysql|for|0.3.0
todo-tree|Gru|0.0.125
MagicPython|mag|1.1.0
python|ms-|2019.3.6139
embrace|myc|1.0.0
code-settings-sync|Sha|3.2.7
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.4.0
vscode-wakatime|Wak|1.2.13
jinja|who|0.0.8
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
file this issue against the VsIntellicode extension

**Comment by RicaBenhossi** [comment]
Done... #78

Thank you @weinand
