### ISSUE TITLE
Window crash after rapid opening and hiding integrated terminal

### ISSUE THREAD

**Issue by szepeu** [Microsoft/vscode#71352]
Couldn't find it in #45693, so I'm creating a new one.

- VSCode Version: 1.32.3
- OS Version: Windows_NT x64 6.1.7601
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:
1. Open a window without any terminal launched - ```Ctrl + ` ``` should open a new one,
2. Press ```Ctrl + ` ``` twice,
3. The window will crash with the error message below:

![image](https://user-images.githubusercontent.com/24934271/55138497-eb0a1800-5133-11e9-95fb-7b5322c50e4d.png)

It looks like it might be connected with #70003.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
