### ISSUE TITLE
Selection / Search is limited to 999 items

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#7135]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Pro (1511; 10586.318)

Hello,

there seems to be some 999 entries / items / whatever limit for selections, searches and so on:
![animation](https://cloud.githubusercontent.com/assets/7961978/15747869/f2e7f830-28dc-11e6-8312-83767da1a87e.gif)

Can this be addressed?
Some option to change the limit?

**Comment by yisibl** [comment]
https://github.com/Microsoft/vscode/issues/5887

**Comment by Ngranger** [comment]
I've run into this problem while trying to xml and json files with an average of 5-10 lines per root array's objects/items and it is extremely frustrating, particularly if I'm trying to find out how many entries there are of a given term (forcing me to turn to the much slower Dreamweaver program for such things).
