### ISSUE TITLE
Option and CMD key have switched almost all functions?

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/vscode#71350]
- VSCode Version: **1.32.3**   a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4   x64
- OS Version: **10.12.6**

For weeks now, I haven't been able to use ⌘+click to go directly **to an element's definition**. And between ⌘ and ⌥, it's all been weird. But I can't recall what change prompted it, but I've tried without any extension and works the same.

Right before I was about to reinstall everything and start from scratch with all my configs, extensions, keyboard preferences, etc., I tried using ⌥, et voilà! Not for all things though. Very weird.

Well, I've made a short video to help you better see what's going on. Check it out:
https://youtu.be/swY1mnyvK8Q

You'll see either ⌘ or ⌥ flashing, and the mouse clicks visible and audible. I hope it helps

And here's the gist with both JSONS, keyboard's and settings':
https://gist.github.com/nmaxcom/05fdb091991674decbc4003abff9b6fa

**Comment by jrieken** [comment]
This setting: https://gist.github.com/nmaxcom/05fdb091991674decbc4003abff9b6fa#file-settings-json-L174. When you configure cmd as the multi cursor character than alt is used for links as indicated here: 

<img width="758" alt="Screenshot 2019-03-28 at 11 27 49" src="https://user-images.githubusercontent.com/1794099/55150503-86a78280-514c-11e9-8535-d69b81acb45b.png">
