### ISSUE TITLE
Centered layout should be stored globally not per workspace

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode#71361]
I tend to switch a lot between workspaces (*File: Open Recent*). I also tend to switch a lot between monitors: the small laptop screen, and a separate ultrawide one. In the ultrawide monitor it feels much more comfortable to work in centered layout, while in the laptop monitor it's the contrary.

If I toggle the centered layout (*View: Toggle Centered Layout*) in a workspace, then that setting becomes attached to the workspace, meaning that:

- Switching to another workspace may have that setting disabled.
- Switching back to this workspace will have it enabled, no matter if I switched it otherwise in another workspace.

I cannot be all the time thinking about this setting when I switch the workspace, so I end up not using the feature at all, which is a shame because the neck ends up hurting in the ultrawide monitor.

IMHO this situation doesn't make sense. :roll_eyes:  The centered layout is a view setting, which one can change depending on the physical environment. It's like the theme: in the day, I use the light theme; in the night I use the dark one; but it doesn't make sense to have a different theme per workspace!

So, what I'm asking for is that the setting persists until I toggle it back again.

Thanks!

**Comment by isidorn** [comment]
Bascially you want it to be stored globally.
However some people want that it is stored per workspace as it is now. Their resoning being one workspace they open at work on a large montior, and other workspaces they open at home on small montiros.

I understand both view points, however I will not change this now and am keeping this open as a feature request so we see if more people agree with you.

**Comment by caseykulm** [comment]
I definitely prefer centered layout regardless of the monitor size I am on. If I have centered on both large/small monitor I'm always looking at the middle of my screen so it's consistent. I don't quite understand wanting it stored per workspace since centered layout on small screens seems desirable. That said I would be happy if global was simply something I could opt into.

**Comment by Yajo** [comment]
> However some people want that it is stored per workspace as it is now. Their resoning being one workspace they open at work on a large montior, and other workspaces they open at home on small montiros.

For these people, the only problem would be to hit a key combination when getting home or getting work. It's something that belongs to the workflow of switching monitor: leave laptop here, close it, plug cable, hit keys.

For people like me who work in the same projects across different monitors, it means hitting the key combination once per project/monitor change combination. I work with 2 monitors across more than 100 projects. You can imagine how annoying this becomes. I just want it centered always, or not centered always. I know that in programming a good rule of thumb is to be explicit instead of implicit, and thus it's usually a good practice to specify your project's dependencies explicitly; however, it seems like all of my projects end up relying relies on a healthy neck and a monitor, but these are decoupled dependencies, so having to hardcode them on every project seems like too much.

I think that a good solution would be to change the implementation of what "centered layout" means. Right now, it means: "there should be X% of margin between the end of the file tree and the start of the code view, and the same X% of margin between the end of the code view and the end of the window". This approach is wrong. Look at this effect, when I want to have 2 vscode one next to the other:
![Peek 13-05-2019 15-28](https://user-images.githubusercontent.com/973709/57629572-eab6c680-7593-11e9-893e-bfa0fff84826.gif)

So, yes, both of the editors have a centered layout, as stated in its project, but it's an illogical thing.

The right approach would be: "if the code view area is bigger than X pixels, the code view should be X pixels wide, centered in the window".

This way, if the window gets smaller (no matter if you switched monitor, or you just resized the window), that's no problem: it will just use the 100% of its size.

The fact that it's not properly centered in the window (the side of the left tree view moves the viewport slightly) is another problem regarding

**Comment by isidorn** [comment]
Thanks for the feedback. However currently we are not planning to change the centered editor layout.
There might be a bigger rewrite of the workbench layout coming in the future.

**Comment by Yajo** [comment]
Don't worry, I found a workaround! This is how it looks now in my wide screen:

![Captura de pantalla de 2019-05-15 09-42-30](https://user-images.githubusercontent.com/973709/57761668-e0acd900-76f5-11e9-90d0-b8c5b1a80d6e.png)

:tada: Centered layout persistent across projects for free! :smile_cat:

**Comment by Yajo** [comment]
Hi dear @vscodebot, I understand why you are doing this.

Yes, I consider this a crucial issue. As you saw in my last comment, I found a workaround to save my neck. However, that doesn't mean the situation is good.

The centered layout feature is awesome, and with this bug it is mostly useless. In fact, my workaround is _not_ using it.

Given the scope of the issue affects users' health, I think it is important. But OK, it's up to you. After 5 months using the workaround I'm used to it and it's already in my routine: change monitor, resize sidebar, keep working, repeat. :robot:

**Comment by isidorn** [comment]
The bot was just following my commands, so I am to blame, not the bot.
Since you seem to be passionate about this issue, I can reopen this one. Even though we do not have immediate plans to tackle this. Thanks

**Comment by akbyrd** [comment]
Please make this a setting in the user's json file rather than hidden session state. If it's a setting then it can be either global or per-workspace based on the users preference. This solves the concerns I've seen in this thread.
