### ISSUE TITLE
Default formater should be preselected by quick pick 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#71368]
#71173

Have multiple formatters. Choose one as default.
"Format with..." command -> notice that the default formmater has it specified in parenthesis. However I would also expect that it is preselected by quick pick

![Screenshot 2019-03-28 at 12 31 03](https://user-images.githubusercontent.com/1926584/55154544-64663280-5155-11e9-9464-6ce7a7174768.png)

**Comment by jrieken** [comment]
I am always confused when quick pick opens and when the first item isn't the selected one. So, would likely reorder formatters, e.g sort the top pick atop but I am not sure about that...

**Comment by isidorn** [comment]
Changing the order might make sense as that is how quick pick usually behaves.
fyi for opinions @bpasero @chrmarti

**Comment by chrmarti** [comment]
The theme selector keeps the order and selects the current theme. I'd go with consistency.
![image](https://user-images.githubusercontent.com/9205389/55161878-d004cb80-5166-11e9-9ba4-ad95583c8d5b.png)
