### ISSUE TITLE
several issue with "file: delete" 

### ISSUE THREAD

**Issue by WiliTest** [Microsoft/vscode#71363]
Issue Type: <b>Bug</b>

 1/ File:delete takes a while before doing something.  I can run it on several tabs without having any feedback. 

2/ It would be more intuitive (notepad++ do that) to remove immediately the tab of the file that has been deleted. Instead, it keeps the tab and (after a while) it happens on the tab name a "deleted from disk" (which I often missed).

3/ Even more confusing, when I run again the "file:delete" on this tab/file (which should have been removed) it asks if I want to save it...

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.87GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.1
transformer|dak|1.6.0
vscode-eslint|dba|1.8.2
beautify|Hoo|1.4.11
vscode-favorites|how|1.4.0
reg|ion|0.0.2
vscode-opn|lfu|1.1.2
python|ms-|2019.3.6139
cpptools|ms-|0.22.1
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.3
vscode-fileutils|sle|2.13.5
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
vscode-arduino|vsc|0.2.25
local-history|xyz|1.7.0

</details>

**Comment by bpasero** [comment]
Closing, please adhere to https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by WiliTest** [comment]
Before closing it, could you please tell me what is wrong with my report? If it's a duplicate, from where? If it's not clear, where?
