### ISSUE TITLE
check for updates feature not working

### ISSUE THREAD

**Issue by daviliano2** [Microsoft/vscode#71365]
When trying to update VS Code, the system will always say that no updates are available.

Steps to reproduce:
  1. Click on "Code" or the setting button at the bottom.
  2. Click on "Check for Updates".
  3. Popup appears and with the following message:
      "There are currently no updates available."

I tried with and without VPN.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Mac OS

and below my user settings:

{
    "terminal.integrated.shell.osx": "zsh",
    "prettier.singleQuote": true,
    "prettier.trailingComma": "all",
    "prettier.semi": false,
    "prettier.eslintIntegration": true,
    "terminal.integrated.scrollback": 2500,
    "emmet.triggerExpansionOnTab": true,
    "emmet.showSuggestionsAsSnippets": true,
    "editor.snippetSuggestions": "top",
    "editor.formatOnSave": true,
    "eslint.autoFixOnSave": true,
    "editor.tabSize": 2,
    "emmet.includeLanguages": {
      "javascript": "javascriptreact"
    },
    "window.zoomLevel": 0,
    "window.title": "${activeEditorLong}${separator}${rootName}"
}

**Comment by joaomoreno** [comment]
Not really sure what is wrong, but I'd recommend downloading a fresh new VS Code version from the website: https://code.visualstudio.com/Download

Let me know if you still don't get an update notification with the next update (in a couple weeks.
