### ISSUE TITLE
Creation of output panel slower

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71367]
* maybe related to https://github.com/Microsoft/vscode/issues/71366
* check https://msit.powerbi.com/groups/2bb9c256-c8ed-47a3-b1be-ebf0c050fb85/reports/2f5bed71-2607-4e0c-8a83-d0f9de023342/ReportSection1f5ac8ab4f061b4a1f8d
* output channels are restored slower

<img width="298" alt="Screenshot 2019-03-28 at 11 59 44" src="https://user-images.githubusercontent.com/1794099/55152590-fcade880-5150-11e9-92e8-73bd85bf0e6a.png">

**Comment by isidorn** [comment]
Output does not use the tree so it should not be the same cause.
Assigning to @sandy081

**Comment by sandy081** [comment]
Yes, Symptoms and timelines look similar. Thanks @isidorn for digging it out.
