### ISSUE TITLE
Toggle Word Wrap does not render a checkmark

### ISSUE THREAD

**Issue by loofou** [microsoft/vscode#71364]
Issue Type: <b>Bug</b>

As the title says: 
1. Load text file with long lines. 
2. Toggle line/word wrapping. 
3. Restart VS and load the same file again
4. Line Wrapping is disabled again.

This happens on every restart of VS Code and there is also no checkmark next to the menu entry when it's turned on.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (16.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
gc-excelviewer|Gra|2.1.29
code-groovy|mar|0.1.2
python|ms-|2019.3.6139
vscode-json-editor|nic|0.2.3
jenkinsfile-support|sec|0.1.0
perforce|sle|3.1.0
shader|sle|1.1.4
vscode-wakatime|Wak|1.2.13
markdown-all-in-one|yzh|2.2.0

</details>

**Comment by alexandrudima** [comment]
You can configure `"editor.largeFileOptimizations": false`. This will prohibit the automatic wrapping of files with long lines.

**Comment by loofou** [comment]
I'm sorry but this flag does not change anything about the behavior I described. It doesn't matter if "editor.largeFileOptimizations" is true or false, Line Wrapping is still deactivated on every launch of VS Code and the checkmark next to the menu point is also still not there, regardless of if the wrapping is currently toggled.

Please re-open this issue, it is definitely not closed.

**Comment by alexandrudima** [comment]
@loofou I am sorry I misread your issue. I thought you are running into the case where you open a file with very long lines where the editor forces word wrapping.

- The menu item never renders a checkmark. That is not a bug, it is just not implemented like that.
- The action in the menu is temporary and is not persisted between restarts. That is not a bug, it is just not implemented to be persistent.
- You can use the setting `"editor.wordWrap": "on"` to have wrapping enabled for all your editors or you can use the language selector syntax e.g. `"[typescript]": { "editor.wordWrap": "on" }` to enable word wrapping for a subset of file types.

**Comment by loofou** [comment]
Hm alright. It seems a bit off that the Word Wrap toggle is the only one in that menu group that does not have a checkmark. I would at least consider this an item to polish, as it is quite confusing if this one option behaves differently to the rest of the toggles.

The setting worked, though, thank you. I think I was confused by the wording of the setting and the additional options (I assumed it was only to turn on column width wrapping instead of viewport size wrapping).

And with that the case is closed, thanks for the help!

**Comment by alexandrudima** [comment]
Yes, you're right. All the other actions have checkmarks, but that is news to me :). When I implemented those actions none of them had checkmarks. Let's keep this issue open for adding a checkmark next to Toggle Word Wrap.

**Comment by alexandrudima** [comment]
Let's track in #62307
