### ISSUE TITLE
Format on paste should have same experience as format on save for conflict resolution

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#71373]
#71173

For me mentally format on paste and format on save are similar user interections and thus should have a very similar UX.
Due to that I suggest that the conflict resolution of format on paste is same as format on save. Pick first formatter automatically + silent notification.

Currently when I format on paste I get a notification (not silent) and I have to choose before it formats.

**Comment by jrieken** [comment]
I agree, it used to be like that and will change it back
