### ISSUE TITLE
After update to latest insiders terminal unusable

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#71378]
Version: 1.33.0-insider (user setup)
Commit: b5f5db349f211f5045e7dad6fd1672010d2d00de
Date: 2019-03-28T10:50:20.288Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.2.9200

Steps to Reproduce:

1. Start `VS Code Insiders`
2. Notice that something is executed as the terminal keeps on scrolling the current path

![image](https://user-images.githubusercontent.com/10828570/55161134-207b2980-5165-11e9-90c7-0dba478250dc.png)

When I close all scripts in the editor pane then the second terminal `2: PowerShell ingerated` is not loaded and there's no problem. Also, when `VS Code insiders` starts with no files open, all is good and only `1: PowerShell` is loaded. When I then open a file it opens the second terminal and keeps on scrolling. This only happens when opening `PowerShell` scripts.not when opening a txt file for example.

This just happened after updating from the previous insiders to the latest. 

No issue when nothing is open:
![image](https://user-images.githubusercontent.com/10828570/55161497-f4ac7380-5165-11e9-96d0-81ce609960cc.png)

**Comment by Tyriar** [comment]
Looks like a problem with https://github.com/PowerShell/vscode-powershell
