### ISSUE TITLE
Escape characters shown in editor.defaultFormatter hover message

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#71370]
refs: #71173

![Screenshot 2019-03-28 at 12 36 32](https://user-images.githubusercontent.com/1926584/55154875-32090500-5156-11e9-8b2c-c908182a0563.png)

Notice the escape characters in the hover message in the name of the extension.
`esbenp\.prettier\-vscode:` should be `esbenp.prettier-vscode:` 

I have been in double escape hell before when doing this for debug because json is somehow overly smart about it...

**Comment by jrieken** [comment]
That's an JSON issue I believe

**Comment by octref** [comment]
Here's the hover result:

```
[Trace - 10:25:42 AM] Received response 'textDocument/hover - (45)' in 3ms.
Result: {
    "contents": [
        "Defines a default formatter which takes precedence over all other formatter settings\\. Must be the identifier of an extension contributing a formatter\\.\n\n`esbenp\\.prettier\\-vscode`: VS Code plugin for prettier/prettier"
    ],
    "range": {
        "start": {
            "line": 79,
            "character": 31
        },
        "end": {
            "line": 79,
            "character": 55
        }
    }
}
```
