### ISSUE TITLE
vscode opens on linux desktop directory icons that were associated with nemo previously

### ISSUE THREAD

**Issue by davidthewatson** [Microsoft/vscode#71372]
Issue Type: <b>Bug</b>

0. install visual studio code on Manjaro Linux Cinnamon
0. Double click desktop icon associated with Home Directory
0. Visual Studio Code opens, expected to see nemo (file explorer) as usual
0. This does not occur for the Computer icon, only the home icon

File associations should be source files or the like, not directories. I know how to do `code .`.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.19.30-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2829)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.39GB (11.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.3.6139

</details>

**Comment by joaomoreno** [comment]
This is rather a question about Manjaro Linux and how you can change the default application for certain file types.
