### ISSUE TITLE
Formatter not availble in status bar

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#71371]
#71173

If a formatter is not available I get a message in status bar
For formatting we already use silent notifications so I am not sure what is the reasoning to use the status bar in this case.
I would prefer a silent warning notification. Makes it more consistent with other format notifications and we keep the format UX not all over the place

![Screenshot 2019-03-28 at 12 42 46](https://user-images.githubusercontent.com/1926584/55155205-0e928a00-5157-11e9-863b-b7c2a1607c97.png)

**Comment by jrieken** [comment]
This is done a status bar message because you must not always take action when this happens. E.g. or formatter only supports the `file` protocol and the file in question is `untitled`. Then it doesn't make sense to configure a different formatter but we will still wanna let you know...

**Comment by isidorn** [comment]
Ok it makes sense that this does not need user action and that it is different in that regard. However I think silent notifications can also serve that role. Or have we envisioned notifications to always require actions, I think not.
My only issue with the crrent approach is: formatter ux all over the place, and I guess that status bar can get clogged easily

fyi @bpasero

**Comment by jrieken** [comment]
> My only issue with the crrent approach is: formatter ux all over the place, and I guess that status bar can get clogged easily

To put this into perspective: my expectation is that you very rarely encounter this in real life

**Comment by jrieken** [comment]
closing as no other feedback as reached us
