### ISSUE TITLE
Double click bracket to select content

### ISSUE THREAD

**Issue by martinandersen3d** [Microsoft/vscode#71376]
Move mouse to bracket, and Double Click to select content.
![doubleclick bracket to select content](https://user-images.githubusercontent.com/19984581/55157517-dc842680-515c-11e9-878d-62c5841ff175.gif)

Should work for bracests/parentheses/curly bracests/single quote/double quote  

This feature is inspired  by Eclipse. But I love VSCode mutch better.

**Comment by weinand** [comment]
see https://stackoverflow.com/questions/51884000/double-click-inside-brackets

**Comment by Tj3n** [comment]
Really hoping to get this one, all existing suggest is still very much annoying to use and not cover other kind of language. A lot IDE is having this though
