### ISSUE TITLE
"Find in Files" move focus to first result with arrow down key

### ISSUE THREAD

**Issue by hstandaert** [Microsoft/vscode#71388]
I'd like to be able to move directly to the search results after searching through my files. Right now, I can move focus by pressing the `TAB` key 5 times but it would be nice to be able to do this in one keystroke.

**Desired behavior**
* Press `ENTER` to perform a search
* Focus is still on the input field
* When pressing the down arrow: move focus directly to the first result.

**Comment by roblourens** [comment]
Press cmd+down 😁
