### ISSUE TITLE
DEBUG CONSOLE shows :undefined doesn't allow object expansion

### ISSUE THREAD

**Issue by cash007** [Microsoft/vscode#71384]
Issue Type: <b>Bug</b>

Hi, 

All of a sudden by DEBUG CONSOLE started showing :undefined. Also I can not expand objects in the WATCH and DEBUG CONSOLE. I can expand object in the VARIABLE panel. How can I fix this issue ? 

 WARNING: Do not use the development server in a production environment.
:undefined
   Use a production WSGI server instead.
:undefined

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|-psn_0_266305|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.3.6139

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders?
https://code.visualstudio.com/insiders/

If yes please provide exact reproducable steps

**Comment by montegeorgeiii** [comment]
Having similar issues.  File with simple print('test','testing') will generate ':undefined' and put the input on separate lines in the Debug console.

**Comment by isidorn** [comment]
Are you all using python?
If yes please file this issue against the python extnesion

fyi @DonJayamanne
