### ISSUE TITLE
TypeScript - perf hooligan

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#71389]
Similar as https://github.com/Microsoft/vscode/issues/71381 and https://github.com/Microsoft/vscode/issues/71290, the TypeScript extension is pretty high up in the list of extensions freezing the extension host. We don't encourage users to file bugs 🤦‍♂️  when it's a built-in extension but we should drill into this...

**Comment by jrieken** [comment]
E.g. TypeScript caused 12359 freezes over 5 seconds with 1.32.3. That totals to a lot of time...

**Comment by octref** [comment]
#68896 is possibly related.

**Comment by rebornix** [comment]
One side effect I saw is cmd+hover stop working very often. I thought it was mouse event related bug and turns out to be that language service doesn't come back.

**Comment by mjbvz** [comment]
@jrieken Where do we get this data from? I'd like to drill into how many sessions/machines this happens for

**Comment by jrieken** [comment]
The telemetry event is `exthostunresponsive`

**Comment by mjbvz** [comment]
Seems likely this is the same issue with `spawn` as in #71290

**Comment by mjbvz** [comment]
Although this could be #69822

In that case, calls to `_convertCompletionItem` are taking around 250ms

**Comment by mjbvz** [comment]
Moving this out since I need a perf log and #69822 doesn't have a response yet

**Comment by mjbvz** [comment]
Closing as not actionable without a perf profile or repo. I haven't see any user reports of perf problems specific to the TS extension (not the server) but will keep an eye out
