### ISSUE TITLE
All "settings.json" files have comma autocomplete

### ISSUE THREAD

**Issue by MaxBazik** [Microsoft/vscode#71392]
- VSCode Version: 1.32.3
- OS Version: Fedora 28
 
Steps to Reproduce:
1. Make a file in your project called: settings.json
2. Write invalid JSON such that a one or more commas are missing.
3. Save the JSON.
4. Notice the missing commas have been added automatically by vscode.

To my knowledge, there is no way to stop vscode from adding in these missing commas. This can be annoying when paired with the editor.autoSave feature as commas will magically appear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is tricky because an extension doesn't have a bulletproof way to tell whether a file is a vscode settings file, so we take over all files named `settings.json`.

However, now that we have the settings GUI and consider editing json files to be mainly for "power users", I wonder whether we should just delete the settings.json autofixing. What do you think @sandy081?

**Comment by sandy081** [comment]
@roblourens I think we associate JSON schema for our settings file specifically. May be you can use the same logic. @aeschli might know it.

Otherwise I am ok to remove that behaviour.

**Comment by aeschli** [comment]
@mattbierner added the feature and it's done in https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/src/extension.ts#L58

It should only do it if in the `.vscode` folder.

**Comment by roblourens** [comment]
Pretty sure I added this feature. Also it needs to work on user settings too which could be anywhere

**Comment by roblourens** [comment]
Why did you close this @MaxBazik?

**Comment by MaxBazik** [comment]
My mistake, I misread the @aeschli's comment.

**Comment by aeschli** [comment]
Oh sorry, @roblourens.
For the user settings, you can assume it is outside the workspace folders and in a folder called `/User/`
We make the same assumption in the JSON extension when associating the settings schema.

**Comment by roblourens** [comment]
I am just going to delete the feature. It doesn't seem that necessary now that the GUI exists.
