### ISSUE TITLE
[GIT SPLIT VIEW] The window does not save height

### ISSUE THREAD

**Issue by wayheming** [Microsoft/vscode#71391]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

Hello, if there are more than 6 repositories in the project, the change window starts behaving strangely. When setting the height of the window after turning on the editor tabs, the height returns to a terrible position and some of the files are not visible. The decision is very necessary as it is not very convenient to work. The main question is how to fix the height of the window permanently?

![d9d28b71c3e1d38cd163168fc17edba3](https://user-images.githubusercontent.com/31981892/55168661-dfdada80-517b-11e9-952c-d7c0c2453a27.gif)

1. Add more than 6 repo to project
2. Set changes window height 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/issues/49054

**Comment by wayheming** [comment]
@joaomoreno Hello, thank you!
