### ISSUE TITLE
Children of the cut folder don't look like cut folders/files

### ISSUE THREAD

**Issue by sh7dm** [microsoft/vscode#71395]
- VSCode Version: 1.32.3
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Select any directory
2. `Ctrl` + `X`
![изображение](https://user-images.githubusercontent.com/19504461/55172666-71057d80-518b-11e9-82cd-724baf87bd39.png)

Seems like a `good first issue`

Does this issue occur when all extensions are disabled?: Yes, not related to them

**Comment by isidorn** [comment]
Might not be super simple.
But here's a code pointer https://github.com/Microsoft/vscode/blob/292e59f3678ef0b9a6c7d920cd00abf9c26c8ccc/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L526
