### ISSUE TITLE
Live share fails to start

### ISSUE THREAD

**Issue by srfrnk** [Microsoft/vscode#71394]
```
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic
```
Steps to Reproduce:

1. Click on `live share` - Browser opens
2. Login using Github (previously authorized)
3. Close browser

Keeps waiting for session to start forever.

Does this issue occur when all extensions are disabled?: No - Can't use live share when the extension isn't loaded.

See video in ZIP:
[bug live share.zip](https://github.com/Microsoft/vscode/files/3018907/bug.live.share.zip)

**Comment by weinand** [comment]
Please file issue against LiveShare extension.
