### ISSUE TITLE
Remove single line / group from debug console

### ISSUE THREAD

**Issue by ellman121** [microsoft/vscode#71396]
Hi all,

It would be very handy if I could take a line of debug console output and delete it.

For example, if you have lots of `log` / `printf` statements throughout an application to track how an object is manipulated from point to point (e.g. tracking changes in a Redux store or something similar), it would be very nice to be able to delete log lines pertaining to certain actions, or to remove them until you have a clear picture of what's going on.

Maybe it can be buried in a right click action on the line in question?

Other thoughts?

**Comment by weinand** [comment]
@isidorn request makes a lot of sense to me (and seems to be low-hanging fruit).

**Comment by isidorn** [comment]
Yes, this is low hanging fruit. However I would only added it if more people ask for it. Thus leaving it open as a feature request.

**Comment by weinand** [comment]
@isidorn please count me in as another user asking for it ;-)

**Comment by isidorn** [comment]
Hehe fair enough :-)
