### ISSUE TITLE
Java code formatter inconsistency

### ISSUE THREAD

**Issue by srfrnk** [Microsoft/vscode#71393]
```
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic
```

Steps to Reproduce:

1. Open file from https://github.com/srfrnk/beam-playground/blob/master/src/main/java/org/apache/beam/examples/ReadCassandra.java
2. `Format document` - Code is changed to V1
3. `Format document` again - Code is changed to V2
4. This will iterate over and over.

Does this issue occur when all extensions are disabled?: No. "There is no document formatter for 'java'-files installed."

See video in this ZIP:
[bug formatter.zip](https://github.com/Microsoft/vscode/files/3018867/bug.formatter.zip)

**Comment by weinand** [comment]
Please file this issue against the Java extension because - as you have noticed yourself - there is no Java formatter built into VS Code.
