### ISSUE TITLE
PowerShell module path missing

### ISSUE THREAD

**Issue by MakwaWes** [Microsoft/vscode#714]
Hi,

# Problem
Some PowerShell modules aren't automatically loaded by 'Microsoft.PowerShell.EditorServices.Host.exe'.
The following path isn't included : '**C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\**'
although it actually reads the x64 counterpart ('C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules').

Thanks !

**Comment by daviwil** [comment]
Hi @MakwaWes, could you file this issue here:

https://github.com/PowerShell/PowerShellEditorServices/issues

If you have other bugs to file against the PowerShell extension for VS Code, you can file them here:

https://github.com/PowerShell/vscode-powershell/issues

Thanks!

**Comment by alexandrudima** [comment]
Moved to PowerShell/vscode-powershell#36
