### ISSUE TITLE
VSCode Doesn't Automatically Use System Proxy

### ISSUE THREAD

**Issue by opticyclic** [Microsoft/vscode#7140]
- VSCode Version: 1.1.1
- OS Version: Windows 7

Steps to Reproduce:
1. Install VSCode behind a firewall configured via a pac file
2. Try to install a C# extension
3. Fail
4. Uninstall and use something else

The system admin has disabled the settings in IE via Group Policy so I can't work out what the pac is and as such can't work out the proxy to put in the config.

VSCode should just use the system proxy settings by default and ask for a username/password if necessary.
There should still be manual options for proxies in the config, however, it would also be useful for someone to have the option to specify a pac file too if for some reason the auto detection doesn't work.

**Comment by rebornix** [comment]
AFAIK, pac file will only proxy requests whose domain is on the list and I suspect our marketplace is not listed, in this case our requests are not going through your proxy. Can you help make sure 

If those two urls are accessible and we do not detect system proxy, then it's a valid request.

**Comment by KeithBallard** [comment]
I am just chiming in on this to suggest that if PAC files are supported, it would be useful to support WPAD files as well for automatic proxy detection.  I don't know if this is so much a bug as a feature suggestion (but that is up to you guys).

**Comment by stanleyxu2005** [comment]
I have the same issue as the @opticyclic. All these urls are accessible in MSIE, but don't work for VSCode. Because VSCode does not use system default network settings (via the WinInet.dll so something), it just connect the Internet directly. This is the issue.

**Comment by joaomoreno** [comment]
Finally someone that knows how the sausage gets made. Thanks for the info @stanleyxu2005.

**Comment by fibric** [comment]
I have the same issue since few days and only in Code - Insiders.

All 3 URL's are accessible in Chrome browser.
```
"extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
}
```

191.238.172.191 forwards to https://markedplace.visualstudio.com while 191.238.172.191:443 cause a timeout. I informed our network team, and they told that neither our proxy nor our firewall blocks any network request to 191.238.172.191:443

When I try 191.238.172.191:443 on my iPhone it tells me that `Certificate Error - The identity of https://191.238.172.191/ can't be verified` and only on pressing the continue button in Safari I get forwarded to https://marketplace.visualstudio.com

**Comment by jankap** [comment]
Got the same problem here in our company network with version 1.9.1
Is the IP address hardcoded in VSC or the domain? I did not have troubles browsing to the domain directly, but extensions cannot be loaded because of "connect ECONNREFUSED 191.238.172.191:443"

**Comment by gritts1** [comment]
Same issue as posted earlier using version 1.9.1... "ECONNREFUSED 191.238.172.191:443". If I test the URL's posted previously I get the following:

```
https://marketplace.visualstudio.com/_apis/public/gallery - Results in a 404 error
https://vscode.blob.core.windows.net/gallery/index - appears to work fine
https://marketplace.visualstudio.com/items - Results in a 404 error.
```

To verify this is not something related to my work network, I attempted to connect to the same URLs through my cell phone. The same results appeared.

**Comment by jankap** [comment]
For your information: Using the key ""http.proxy":"http://username@ip:port" in user settings does work for me without entering a password (got authenticated before by Windows). 

So all works as expected for me now, thanks

**Comment by AbhishekTripathi** [comment]
I am still facing this issue. The URL 191.238.172.191:443 doesn't resolve

**Comment by crewshin** [comment]
Same issue on OSX

**Comment by joaomoreno** [comment]
Actually, Code now uses the system proxy settings. Which doesn't mean that proxy issues are fixed for every one. More in #22214
