### ISSUE TITLE
Breakpoints not showing in the editor

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#71402]
@karthiknadig commented on [Wed Mar 27 2019](https://github.com/Microsoft/vscode-python/issues/4975)

@luabud commented on [Wed Mar 27 2019](https://github.com/Microsoft/ptvsd/issues/1269)

## Environment data

- PTVSD version: 0.2.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1 (global)
- Using VS Code or Visual Studio: VS Code Insiders

## Actual behavior

I added breakpoints by clicking on the margin of the editor and they show up in the Breakpoints window, but not in the editor
![image](https://user-images.githubusercontent.com/45497113/55113933-d7ac6d80-509d-11e9-9525-c3d50c866fa1.png)

## Steps to reproduce:
It happened three times but I don't know how to reproduce it. Twice when I reloaded the window with the interactive window open, but it doesn't happen all the time

---

@karthiknadig commented on [Wed Mar 27 2019](https://github.com/Microsoft/ptvsd/issues/1269#issuecomment-477363783)

@luabud Can you enable logs? one way is to set the environment variable 'PTVSD_LOG_DIR' to some directory.

---

@karthiknadig commented on [Wed Mar 27 2019](https://github.com/Microsoft/ptvsd/issues/1269#issuecomment-477364270)

Also, were you already debugging or was this before running?

---

@luabud commented on [Wed Mar 27 2019](https://github.com/Microsoft/ptvsd/issues/1269#issuecomment-477373827)

Yes, I was already debugging. Now I can reproduce it. Have the debugger to stop on a breakpoint and open the interactive window, and then reload VS Code. 
[ptvsd-19488.log](https://github.com/Microsoft/ptvsd/files/3015502/ptvsd-19488.log)

---

@karthiknadig commented on [Wed Mar 27 2019](https://github.com/Microsoft/ptvsd/issues/1269#issuecomment-477375339)

Looks like the debugger is already disconnected (looking at the end of the code).  On reload the debugger is shutdown, and wont be started unless it is launched again. Extension should look into what is going on here.

**Comment by DonJayamanne** [comment]
Not an extension issue as we're just adding breakpoints via the editor.

**Comment by isidorn** [comment]
Please try to find some reproducable steps or some other clues which might help. For instance are the breakpoints still respected by the debug adapter? Does the debug adapter recieve / send some unexpected breakpoint requests? How come that only python users are seeing this? Can people reproduce for simple node debugging? And so on...

I currently can not reproduce.

**Comment by fourpastmidnight** [comment]
I've seen this in PowerShell, too. And the breakpoints are still honored. The workaround for me was to remove and then re-set the breakpoint. I also do not have specific steps to reproduce, as it appeared to happen "randomly" without any noticeable sequence of actions resulting in this behavior.

**Comment by isidorn** [comment]
@fourpastmidnight repro steps if possible please. Also please make sure to file this against the powershell extension.

**Comment by zeyangl** [comment]
I am having exactly the same issue with C#. Breakpoints work normally but just won't show in the editor.

**Comment by zeyangl** [comment]
I found this issue that solved my problem. Not sure if it helps.
https://github.com/Microsoft/vscode/issues/14989

**Comment by isidorn** [comment]
No repro steps provided closing

**Comment by luabud** [comment]
Repro steps were on a comment:

With the Python extension isntalled, run the debugger on a Python file and get it to stop on a breakpoint. Then open the Python interactive window and reload VS Code. Even though this repro steps are for the Python extension, this has been seeing with C# and PowerShell, so I believe it could be a bug in VS Code

**Comment by isidorn** [comment]
Ok, reopening
