### ISSUE TITLE
Do not automaticall populate search box with selected text

### ISSUE THREAD

**Issue by fredlcore** [microsoft/vscode#71404]
When searching for text in an open editor, the search box is automatically populated with any currently selected text. While this is fine when first starting a search, it is a pain when I search for a given text, then make some changes and then want to search for the next occurrence. In that case, the word next to the cursor is automatically selected and overwrites the previous search term.

I know I can jump back to the previous search term with Alt+arrow up (on Mac), but it's an additional and annoying step which I would like to avoid.

**Comment by roblourens** [comment]
I recommend using the F3 or F4 keys to navigate to the next search. I don't think it's worth adding a whole setting to disable this.

**Comment by fredlcore** [comment]
I'm not sure if we are talking about the same issue. F3 (on Mac) jumps to the next occurrence of the search string. F4 has no effect (on Mac).

What I mean is something different: 
I search for a string with CMD+F (on Mac) and go through the hits (for example with F3). When I have found the hit that I want to edit and make some changes and then want to search for the next hit with CMD+F, the old search string is replaced with the word next to the cursor.
And yes, as I mentioned above, I can use ALT+Arrow Up (on Mac) to go back by one in the search string "history", but this is a pain in the back if you want to make changes on various locations using the same search string.

So maybe you could reconsider closing this issue?

Thanks,

F.

**Comment by roblourens** [comment]
> and then want to search for the next hit with CMD+F

I'm saying, you can use F3 to go to the hit instead of cmd+F then enter, but maybe I'm still misunderstanding

**Comment by fredlcore** [comment]
No, that is true, I didn't know about this, thanks a lot, I just have to re-wire my mind a bit to switch between CMD+F and F3 because most other editors do not have the behaviour and keep the original search string, but I agree that adding a config option is then probably too much of an effort, so you can close this issue then.

**Comment by roblourens** [comment]
Actually I think this issue is the right dupe: https://github.com/microsoft/vscode/issues/20768

Also there is apparently already a setting to disable this entirely: `editor.find.seedSearchStringFromSelection`

**Comment by fredlcore** [comment]
Yes, that is the correct dupe, and also a perfectly fine solution to my issue, thanks!
