### ISSUE TITLE
Very High CPU Usage on Windows 10

### ISSUE THREAD

**Issue by felixchr** [Microsoft/vscode#71401]
Issue Type: <b>Performance Issue</b>

I'm getting very high CPU usage whenever I'm using it or not. It keeps very high CPU usage all the time. It is making the computer lag very evidently. The performance issue disappears when I close all VSCode windows.

![vscode_high_cpu_usage](https://user-images.githubusercontent.com/5973884/55178843-6f17cc00-5143-11e9-93c7-4624e6891962.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   30	    86	 16036	code main
    0	   159	  5484	   gpu-process
    0	    55	 16016	   shared-process
   17	   178	 17252	   window (config.yaml.example - ansible-playbook - Visual Studio Code)
    0	    32	 12908	     extensionHost
    0	     9	 21124	     watcherService 
    0	     5	 20836	       console-window-host (Windows internal process)
   17	   179	 21384	   window (views.py - flask - Visual Studio Code)
    0	    18	 19852	     extensionHost
    0	    19	 23532	       C:\Users\g707455\.vscode\extensions\ms-python.python-2019.2.5558\languageServer.0.1.80\Microsoft.Python.LanguageServer.exe
    0	     3	 14256	         console-window-host (Windows internal process)
    0	     8	 23372	     watcherService 
    0	     3	 21896	       console-window-host (Windows internal process)
    0	    68	 30024	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (views.py - flask - Visual Studio Code)
|  Window (config.yaml.example - ansible-playbook - Visual Studio Code)
|    Folder (ansible-playbook): 284 files
|      File types: yaml(171) py(33) j2(25) retry(12) sh(7) example(4) yml(3)
|                  gitignore(3) git(2) gitmodules(1)
|      Conf files: settings.json(1)
|    Folder (flask): 18882 files
|      File types: py(6177) pyc(6159) js(1106) png(977) dat(712) pdf(445)
|                  svg(442) txt(170) html(169) h(133)
|      Conf files: settings.json(3) makefile(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ftp-sync|luk|0.3.9
python|ms-|2019.3.6139
Go|ms-|0.9.2
codemap|ole|1.6.0
jinja|who|0.0.8

</details>

**Comment by weinand** [comment]
Do you see this behaviour even when disabling all extensions?

**Comment by weinand** [comment]
no reply -> closing.
