### ISSUE TITLE
Bash terminal doesn't show text again after cancelling entering a passphrase

### ISSUE THREAD

**Issue by amoreauCoveo** [Microsoft/vscode#71408]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. In the bash terminal of VS Code, try to pull from a git repository that requires you to enter a passphrase.
2. When prompted for a passphrase, `ctrl`+ `c` to cancel entering the passphrase.
3. Try entering a new command - the text will stay hidden as when entering a passphrase.

Closing the VS Code window and reopening it resets it, and shows the commands again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
