### ISSUE TITLE
Text in custom dialogs should select/copyable

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#71407]
This is very useful for filing issues with error messages. I can copy text from notifications too.

**Comment by sbatten** [comment]
note this is not a feature of native

**Comment by bpasero** [comment]
What?

![image](https://user-images.githubusercontent.com/900690/63573853-b7b6a280-c586-11e9-9ef8-51ac6cde2621.png)

**Comment by sbatten** [comment]
ah works differently on windows, you can't select the text but if a dialog is focused, ctrl+c copies all its contents in a formatted way
```
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Do you want to save the changes you made to Untitled-1?

[Content]
Your changes will be lost if you don't save them.

[Save] [Don't Save] [Cancel]
```

I personally don't like when UI lets you select text as it looks unpolished to me, but I can see how it might be of use to select a portion of the dialog. Preference between selection and a single copy action?

**Comment by bpasero** [comment]
Interesting, I did not know that Windows allows you to copy. I find that very hard to discover to be honest. We allow to select and copy in notifications as well so I would go for that.
