### ISSUE TITLE
VScode background turns ligter when window is moved to secondary display

### ISSUE THREAD

**Issue by Luxray5474** [microsoft/vscode#71419]
- VSCode Version: 1.32.3
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Drag VScode window to secondary display https://youtu.be/yLCiGSOncQM

Does this issue occur when all extensions are disabled?: Yes

Even though I said it is a "weird issue" I have personally no problem with it, just a bit concerned/thrown off since I have not seen or expected this behavior. In fact, it helps a bit because my second display is a little darker and has a stronger red channel. I think it might be a bug though.

P.S. excuse the crap video quality. Taken using a Powershot A700 from centuries ago.

EDIT: If it is a bug please make it a feature :) I strongly believe there are other people who also have problematic displays and imo I think that would help us all out.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by Luxray5474** [comment]
~~excuse the very late reply, i thought my e-mail reply sent but apparently no~~ 

Thank you and yes I have tried it. It does not exhibit the same behavior.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
