### ISSUE TITLE
F12 opens file in preview even if preview is disabled

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/vscode#71418]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:
1. Install Python Extension
2. Install Python 3.7
3. Enable language server by setting `python.jediEnabled` to false.
4. Restart VSC.
5. Open/create Python file, type `import logging`
6. Right click on `logging`, choose `Goto Definition`
7. `__init__.py` opens, but there are no tooltips and I cannot navigate to imports inside the file (i.e. drill deeper).

- Python LS does not receive `didOpen` on the `__init__.py`
- `"workbench.editor.enablePreview": false`

Expected: F12 to allow me to go deeper than one file.

![image](https://user-images.githubusercontent.com/12820357/55196136-b4e88a80-516b-11e9-8a60-4d74f4120445.png)

**Comment by jakebailey** [comment]
This is also goofy when you restart the editor after doing the above; the first time the file is essentially "fake" open, but after restarting it's actually open and everything loads (e.g. the outline).

**Comment by jakebailey** [comment]
We are on the Python team; this isn't an extension issue to our knowledge. Our bug for this: Microsoft/python-language-server#840

![gotodef](https://user-images.githubusercontent.com/5341706/55199607-d485b000-5177-11e9-9976-5ca148f3879d.gif)

**Comment by MikhailArkhipov** [comment]
Specifically we do not get `didOpen` on the file opened as response to F12.

**Comment by weinand** [comment]
If you clearly state that you are the extension author and that you think that VS Code is the culprit, we will certainly not ask you to file it against the extension ;-)

**Comment by MikhailArkhipov** [comment]
Will do :-) Thanks!

**Comment by jakebailey** [comment]
This may or may not be the same thing, but if we open another Python file that isn't in the workspace (via Open File), then the same behavior occurs. No outline shows up, the language server is never notified that the file is opened, and the right click menu is limited.

**Comment by jakebailey** [comment]
Another quirk:

1. Open a folder with a python file; get the right click items and completion as normal in a Python file.
2. Try to open a file outside the project; get no right click options or completion.
3. Restart the editor; things work again _and_ opening more files outside the workspace works normally as though there were no issue.

**Comment by jrieken** [comment]
> Controls whether opened editors show as preview. Preview editors are reused until they are pinned (e.g. via double click or editing) and show up with an italic font style.

🔝 that's what `openPreview` does. It has nothing to do with F12, for that a new setting is coming with next stable and current insider: `editor.gotoLocation.multiple`

**Comment by jakebailey** [comment]
After bisecting a few repos, this turned out to be extension related after all; multi-root workspace support was added in a way that files outside the workspace aren't being handled by the extension (so no features are available). Microsoft/vscode-python#5132
