### ISSUE TITLE
Emmet doesn't set cursor properly within nested element in custom grammar

### ISSUE THREAD

**Issue by mindpixel-labs** [microsoft/vscode#71411]
**Version & OS:**
- VSCode Version: 1.32.3
- OS Version: Mac OS High Sierra 10.13.6

**Steps to Reproduce:**
I have a custom grammar that includes `text.html.basic`. However, when my grammar is activated certain Emmet features seem to be not working correctly anymore.

1. When I set the Language mode to my custom defined [extension's](https://marketplace.visualstudio.com/items?itemName=mindpixel-labs.vsc-expressionengine) provided grammar, typing `div` and hitting tab to autocomplete creates the snippet provided from Emmet.
2. If you then hit enter to create a nested element within the div, it places the cursor right before the closing tag instead of within the center of the parent div.

**Result**
![result](https://user-images.githubusercontent.com/32364162/55185655-3855ac00-516b-11e9-95ff-99047fb2e3bc.gif)

**Expected Result** (Within Default VSCode HTML Language Mode)
![expected](https://user-images.githubusercontent.com/32364162/55185608-18be8380-516b-11e9-8c7f-628299640a59.gif)

Does this issue occur when all extensions are disabled?: Not Applicable

**Comment by octref** [comment]
You need to configure Indentation Rules for your language. This has nothing to do with emmet.
https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules

Here's [HTML](https://github.com/microsoft/vscode/blob/7006ca07723ba3ea2b73f9fa0db5b1c122ffbf2b/extensions/html-language-features/client/src/htmlMain.ts#L113-L116)'s indentation rule shipped in VS Code.
