### ISSUE TITLE
Autocomplete on <input> doesn't support autofill values

### ISSUE THREAD

**Issue by codepo8** [Microsoft/vscode#7142]
- VSCode Version: 1.1.1
- OS Version: OSX

Steps to Reproduce:

1.  type <input autocomplete=" in an HTML file
2. see only "on" and "off"

There are many more: https://html.spec.whatwg.org/multipage/forms.html#inappropriate-for-the-control 

I'm happy to take this on :)

**Comment by aeschli** [comment]
fixed by #7152
