### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by strangerDemon** [Microsoft/vscode#71427]
often crash after update the last version 。
最新版本的vscode易崩溃，特别是在拖拽tab页的时候

**Comment by weinand** [comment]
Please provide more information so that we can investigate.
See https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues for details.
You do not even tell us the platform/OS where this happens...

**Comment by strangerDemon** [comment]
![1](https://user-images.githubusercontent.com/12962168/55692570-f256de80-59db-11e9-828f-50729b1099c1.gif)
like this
