### ISSUE TITLE
"{{" can't trigger html snippet

### ISSUE THREAD

**Issue by leozhao0709** [Microsoft/vscode#71420]
VSCode Version: 1.32.3
OS Version: mac osX
Steps to Reproduce:

Add this snippet
{
"doubleBracket": {
    "prefix": "{{",
    "body": "{{ $1 }}$0",
    "description": "angular double bracket"
  },
}
Try to trigger it via "{{" **within** a html element tag,
It does not work.

In a html file, **within** an element tag, I want to trigger the double curly bracket. But the personal defined snippet now working. I remember it's working before. If I change to other "prefix" like "--", then it can work.

**Comment by jrieken** [comment]
When typing `{{` you automatically get `}}` and by that your cursor isn't at a word end anymore. Intellisense as-you-type only works on word ends. You need to press Ctrl+Space to get IntelliSense

**Comment by leozhao0709** [comment]
@jrieken  what I see is if tap `{{` within an html tag in the same line, let's say if I tap `{{` **within** a 
```
<div>{{</div>
```
, then `}}` can't automatically get. That's why I want to create this snippet.

The automatically trigger only works if the div in different line like this
```
<div>
  {{}}
</div>
````
