### ISSUE TITLE
Create new folder in simplified file dialog

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#71425]
Maybe you've already thought about this but it would be useful to be able to create a new folder in the simplified file dialog. This could be a button in the title bar or a confirmation step when a folder that doesn't exist was typed.

Creating a folder and opening it, and creating a folder and saving a file in it, are common workflows so it would be useful to be able to do those in one step.

**Comment by mhanuszh** [comment]
For the meantime: https://marketplace.visualstudio.com/items?itemName=igordvlpr.new-folder

**Comment by igorskyflyer** [comment]
Hey @mhanuszh, thanks for the mention! 🙌

This was a feature I personally needed for quite some time - we all basically do those steps mentioned by @roblourens on a daily basis so I decided to code an extension for it. Even though the extension already works great, I am actually working on it right now and adding a new feature which will allow it to create new folders using the Simple file dialogs - regardless of user setting, see #127201.

If anyone's interested, I think I'll manage to finish it by tomorrow. 😄

**Comment by igorskyflyer** [comment]
I've been busy with work and other projects but after a long wait, I worked really hard and managed to finish my [FolderPicker](https://github.com/igorskyflyer/npm-vscode-folderpicker) npm module for Visual Studio Code that implements the aforementioned behavior and shows a custom QuickPick that allows browsing and creating folders from the Command Palette, even nested/recursive folders. The extension that implements this package is available at [New Folder](https://github.com/igorskyflyer/vscode-new-folder) repo.

Not perfect (yet) but it works. 😁

**Comment by xgdgsc** [comment]
Also create new file in Open File dialog would be useful.

**Comment by rzhao271** [comment]
Saving is good. Opening hasn't been implemented -- should there be a new issue for that?
