### ISSUE TITLE
Bash/Terminal isn't running latest Python version

### ISSUE THREAD

**Issue by dbrucknr** [Microsoft/vscode#71422]
Issue Type: <b>Bug</b>

I can't seem to get my bash/terminal in Microsoft Visual Studio Code to run any other version of python except version 2.7.10 (The default Python on MacOs). 
I've switched interpreters between version 3.7.3 and Anaconda's virtual environment, but the bash consistently runs version 2.7.10

I've attempted to switch paths in the VS Code settings, and in the JSON settings as well.

Any recommendations would be greatly appreciated. I just purchased this laptop, so I may be missing settings from my old system.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (6.23GB free)|
|Process Argv|-psn_0_372827|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.3.6215

</details>

**Comment by Tyriar** [comment]
The version of python available is based on your $PATH. I suspect you're experiencing issues described in https://github.com/Microsoft/vscode/issues/70248
