### ISSUE TITLE
Source Control Providers: horizontal scroll bar is blocking click repo item

### ISSUE THREAD

**Issue by bammoo** [Microsoft/vscode#71436]
- VSCode Version: 1.32.3
- OS Version: Mac Mojave

Steps to Reproduce:

1. Open SOURCE CONTROL
2. When there are many submodule repos and the repo name is very long, the horizontal scroll bar is blocking click the bottom of repo item in the list.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
#68027
