### ISSUE TITLE
searcher all file not work

### ISSUE THREAD

**Issue by nicetu** [Microsoft/vscode#71438]
Issue Type: <b>Feature Request</b>

There is a sub-repository under the git repository. Searching for files with the same name is not searched.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0

**Comment by joaomoreno** [comment]
Can you elaborate the bug, with steps for me to reproduce?
