### ISSUE TITLE
<Explorer :volumes > to empty

### ISSUE THREAD

**Issue by kewaldeshpande** [Microsoft/vscode#71433]
I have mapped the volumes wrongly into visual studio code. 
When I try to delete the volumes it asks for a delete. Is there any way to just remove it from explorer :volumes than deleting it completely. 

This would be a good feature, I tried many ways, but it only asks for deleting and also prompts for a permanent delete which I do not want to proceed with.

**Comment by isidorn** [comment]
I suggest you start using multi root workspaces and choose what folders you work on. More details can be found here https://code.visualstudio.com/docs/editor/multi-root-workspaces
