### ISSUE TITLE
“Unable to find project.json or *.csproj” while creating a new Interface or class in VS Code(1.32.3)

### ISSUE THREAD

**Issue by H-AbdulMateen** [Microsoft/vscode#71439]
I am getting this issue "Unable to find project.json or *.csproj" while creating a new class or interface in my Angular project in vs code. It was working fine, but accidentally I am getting this issue. Due to this issue, I am unable to create new files in my project. I can't find any solution from previous ones, so don't do it duplicate. please help me.

**Comment by H-AbdulMateen** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Error Unable to find project.json or *.csproj (#68356)](https://www.github.com/Microsoft/vscode/issues/68356)



> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Error Unable to find project.json or *.csproj (#68356)](https://www.github.com/Microsoft/vscode/issues/68356)

nope, the previous one also did not resolve.

**Comment by weinand** [comment]
Please file the issue against the C# extension. Thanks!
