### ISSUE TITLE
Maximizing the editor in a snap setup causes the interface to not update

### ISSUE THREAD

**Issue by tardigradedigital** [Microsoft/vscode#7143]
- VSCode Version: 1.1.1
- OS Version: Windows 10, Build 14352

Steps to Reproduce:

1. Snap a program to the right (I used Groove at minimum width)
2. Snap VS Code to top left
3. Enlarge the window down until Windows snaps it to the top of the taskbar
4. Clicking in the window appears to do nothing until you unsnap the app
5. This does not affect snapping to left, only corner snapping

**Comment by bpasero** [comment]
This is a known (Windows 10) issue.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5415
