### ISSUE TITLE
Can we add ReactXP template in VSCode?

### ISSUE THREAD

**Issue by hmheng** [Microsoft/vscode#71431]
Can we add ReactXP template in VSCode since it is developed Microsoft In-house by Skype team? 
This will encourage more new react-native developers to kick start with it and improve the framework.

**Comment by weinand** [comment]
What do you mean by ReactXP "template"?

VS Code out of the box has no builtin React functionality. 
So even without understanding what you mean by ReactXP template I suggest that you ask the owners of the React extensions for this.
