### ISSUE TITLE
Terminal display exception

### ISSUE THREAD

**Issue by MissAX** [Microsoft/vscode#71447]
Issue Type: <b>Feature Request</b>

in windows .if first open terminal ,the terminal  not show current worke space file path.mine windows version is windows 10 chinese family.I'm very sorry,because mine english is very poor.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
