### ISSUE TITLE
Please add the ability to reference system environment variables‎ ||希望增加引用系统环境变量的功能

### ISSUE THREAD

**Issue by sky5454** [Microsoft/vscode#71444]
A lot of time, to change _The System Environment_ is easy than change the VSCode's config , so I wonder if you could add the ability for VSCode to reference _The System Environment_ . 
[And I'm so sorry about my poor English]
And that would be high efficiency. 
like this.

The System Environment  :
[NPCAP_INCLU] C:\npcap\include

And I'd to ask you to make it in VSCode :
Replace "C:\npcap\include"  with  ${$NPCAP_INCLU} 

很多时候，直接引用系统环境变量的配置要比在单个软件里配置来得更舒服高效。所以希望增加引用系统环境变量的功能，而非只能用VSCode内部的变量。

如
系统环境变量：
[NPCAP_INCLU] C:\npcap\include

而我个人希望在VSCode能直接使用
${$NPCAP_INCLU} 来代替"C:\\npcap\\include"

**Comment by weinand** [comment]
Where in VS Code do you want to use environment variables?

**Comment by sky5454** [comment]
Sorry,  I didn't know that VS Code originally supports the environment variales.
Actually we can use it like VS:
The System Environment :
[NPCAP_INCLU] C:\npcap\include

in file [c_cpp_properties.json]
${NPCAP_INCLU}


It is more convenient that I don't need to edit the config file when I need to change my dir location or to send code to my friend.

**Comment by weinand** [comment]
@sky5454 "c_cpp_properties.json" is not a file that VS Code knows. It was probably introduced by the C++ extension.
Please file the feature request against the C++ extension.
