### ISSUE TITLE
Usability issue for 'Outline' (left panel)

### ISSUE THREAD

**Issue by ClickSapiens** [Microsoft/vscode#71443]
- VSCode Version: 1.32.3
- OS Version: Windows 7

This is a **usability issue** and an easy one to fix.

I'm using 'Outline' feature a lot, since it helps me jump to different parts of my multi-thousand lines code.
For that purpose, I have enabled "Follow cursor" (to know where I am), "Filter on type" and "Sort by position" in order to match the structure displayed with the actual code layout and help me orientate.

**BUT,  it keeps opening each function displayed when I click on a variable in the code, showing the local vars** which is useless (if you are inside a function you see the vars anyway), and keeps them opened and **that ruins the whole structure displayed** which becomes unusable and I have to click on "Collapse All" button a thousand times every day!

**So please, correct this, make it show only the functions -not the local vars and the global ones also interfere against usability as they push the whole structure down,  or make that optional on the settings!  The vars are not important, the structure is!**

**Comment by halhenke** [comment]
I had a similar issue in that the function nodes are always expanded by default in the Output panel, which in combination with displaying all variables as described above really cripples the ability to see and navigate between functions/classes in a given file at a glance. I guess the option to hide variables would do away with both issues but IMHO function nodes should probably be folded by default at the topmost level (Classes should probably show methods). Anyway options to customize would be great.
