### ISSUE TITLE
smoke test failure with vscode-smoketest-check 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#71445]
Version: 1.33.0-insider
Commit: 4039ea871879ef8f654f27df5c32d209104b3a44
Date: 2019-03-29T10:48:26.004Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic

running smoke test against https://az764295.vo.msecnd.net/stable/a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4/code-stable-1552606946.tar.gz

has the following failure: (both on LInux and Mac, didn't try WIndows)

1) Running Code
       Extensions
         install and activate vscode-smoketest-check extension:
     Error: Timeout: get text content 'div.monaco-quick-open-widget .quick-open-tree .monaco-tree-row.focused .monaco-highlighted-label' after 20 seconds.
      at /home/aeschli/workspaces/vscode/test/smoke/out/vscode/code.js:148:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

**Comment by alexandrudima** [comment]
Also happens on mac

**Comment by weinand** [comment]
@aeschli confirmed that this is a problem of the smoketest; testing the underlying VS Code functionality manually doesn't show a problem.

**Comment by dbaeumer** [comment]
Didn't fail for me under Windows.

**Comment by sandy081** [comment]
It worked for me on Mac. Please accept all changes in VS Code and compile smoke test code before running smoke tests.
```
cd test/smoke
yarn watch
```

**Comment by aeschli** [comment]
I didn't know that, just followed the steps from https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md
Can we add it to the wiki, or add a `yarn compile` to the `yarn smoke` script?

**Comment by sandy081** [comment]
Done
