### ISSUE TITLE
VS Code complain about high cpu loading caused by React Native Tools extension

### ISSUE THREAD

**Issue by SounD120** [Microsoft/vscode#71449]
Hello, I am a maintainer of [React Native Tools](https://github.com/Microsoft/vscode-react-native).
Recently we got a high cpu load report https://github.com/Microsoft/vscode-react-native/issues/957 and, also, user attached [CPU profiling file](https://github.com/Microsoft/vscode-react-native/files/3014752/vsmobile.vscode-react-native-unresponsive.cpuprofile.txt). We analyzed it and found out that possible cause of perfomance degradation might be extension activation event, but looking at the profiler report we are not sure if it is extension issue or VS Code ones. Could you please take a look at the report and give us any clues or point us to the right direction? Also, here are the steps that have led user to the issue:
1) Install [React Native Tools](https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native) extension
2) Install [Flutter](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) extension
3) Start debugging of Flutter app with Flutter extension led to VS Code performance issue with React Native Tools.

**Comment by jrieken** [comment]
See https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading. @SounD120 Profiles looking like that are strong indicator of slow code loading, e.g we get to your extensions but it takes 5sec+ to load all code and all node modules it depends on. We strongly recommend to use a bundler (like parcel or web pack), you can follow this https://code.visualstudio.com/api/working-with-extensions/bundling-extension. That reduces the number of files drastically, improving install and load times.
