### ISSUE TITLE
Auto save disabled but project gets rebuild and loads application again

### ISSUE THREAD

**Issue by shripadgodse** [Microsoft/vscode#71450]
Issue Type: <b>Bug</b>

I have disabled Auto Save from file > prefernces > setting from both workspaces though project gets rebuild when i switch from one tab to another

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|9.5.1
auto-rename-tag|for|0.0.15
Angular2|joh|7.0.1
vscode-css-peek|pra|2.2.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by shripadgodse** [comment]
I have uninstalled all the extensions and run application through external command prompt still getting the same issue

**Comment by bpasero** [comment]
@shripadgodse what does this mean exactly?

>  project gets rebuild when i switch from one tab to another

**Comment by shripadgodse** [comment]
When i switch from one file to another file by pressing ctrl+p/ctrl+tab then code gets rebuild and application gets reloaded

**Comment by bpasero** [comment]
@shripadgodse to clarify, you have an external program you are developing on that is restarted whenever you switch tabs?

**Comment by shripadgodse** [comment]
yes

**Comment by bpasero** [comment]
@shripadgodse well we do read the contents of the file when you switch tabs and this is likely changing the accesstime of the file which maybe the watcher is treating as a file change event?

Hard to say, but I do not think this is something VSCode is doing wrong, we do not write to the file upon switching but read it to detect file changes.
