### ISSUE TITLE
API to trigger a refresh of the OUTLINE (DocumentSymbols)

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vscode#71454]
Currently `provideDocumentSymbols` is called whenever a documents content changes.  

There are occasions when the "known" list of symbols for a document may get updated independently to the document getting changed (like during a background compile, or a user initiated "check syntax").

It would be nice if we could trigger an event which would force a given document to request the latest list of known symbols from the DocumentSymbolProvider.

(its quite common for compilers to provide the outline quickly via a simplistic AST, but then "fill in the gaps" as part of a full compile).

**Comment by stefan-toubia** [comment]
+1 
With Clojure, the file has to be evaluated in the REPL before the symbols can be inspected, so this happens after the file is saved and the REPL is done loading.
