### ISSUE TITLE
Tasks.json contents not updated until VS Code is reloaded on Ubuntu 18.04

### ISSUE THREAD

**Issue by alexiip** [Microsoft/vscode#71459]
I am using Ubuntu 18.04. I use Tasks to build, configure and debug my C++ CMake projects inside of Docker. I pass in my args to the app using tasks. However, every time I update the arguments, that is, modify the tasks.json file, the changes are not seen by VS Code until it is re-loaded. By not seen, I mean, if I execute the task before reloading the window the new arguments are not passed down to the command.  I should not have to re-load VS Code every time I update a task. Seems like this has been fixed on other platforms but not on Ubuntu 18.04. [Related issue](https://github.com/Microsoft/vscode/issues/42226) for other platforms

**Comment by alexr00** [comment]
Tried on Ubuntu 18.04 and I can't reproduce. Do you have any other repro steps?

**Comment by alexiip** [comment]
I just pulled the latest update and it fixed the issue. Thank you for taking the time to check it out. VSCODE is an amazing IDE on Linux.
