### ISSUE TITLE
Go to definition not working in php

### ISSUE THREAD

**Issue by haunted2** [Microsoft/vscode#71452]
- VSCode Version: 1.32.3
- OS Version: Windows 7

Steps to Reproduce:

1. Install PHP Intellisense extension
2. Open a folder with a php project in VS Code
3. Double click on a method/function reference, then right click on it and select "Go to definition"

Nothing happens.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please file this on the repo for the extension you are using
