### ISSUE TITLE
Pressing the "debug settings" gear icon opens .code-workspace instead of launch.json

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#71456]
Version: 1.33.0-insider (user setup)
Commit: 4039ea871879ef8f654f27df5c32d209104b3a44
Date: 2019-03-29T10:53:36.965Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

Clicking the gear icon (pictured below) to the right of the debug configurations dropdown menu opens `{workspace}.code-workspace` instead of `launch.json`, even if debug configurations already exist in a `launch.json` file.

The title text for the button is "Open launch.json" in one workspace and "Configure or Fix launch.json" in another (not sure why). Neither imply that opening the code-workspace config file is the intended behavior.

![image](https://user-images.githubusercontent.com/2294248/55247247-73b0b300-521d-11e9-814f-3b34a6c19d35.png)

**Comment by isidorn** [comment]
I can not reproduce this.
Can you always reproduce this? Even if you run the Gulp Build launch configuration?
If you can always repro can you create a minimalistic repository on GitHub so I clone it and see this behavior on my machine?

**Comment by iansan5653** [comment]
I'm not able to reproduce this on my personal computer. I'll have to try at work again.

**Comment by isidorn** [comment]
Once you get the repro let me know
