### ISSUE TITLE
Restore opened editors broken when the path or directory name changed

### ISSUE THREAD

**Issue by sgon00** [Microsoft/vscode#71451]
Restore opened editors broken when the path or directory name changed.

I have asked this question in many places for more than a year. (in gitter, stackoverflow etc..). But so far, no workaround yet. 

I have no ideas why vscode can't save opened editors session inside the project directory, something like `<path>/projectDir/.session`. I constantly re-structure/move/rename my project directory name. The default restore opened editors behavior just don't work at all. 

Thank you very much for your help if you can provide a workaround. I even searched extensions, but no luck so far. 

I am sorry that if this is not really a bug report. I really did try to fix this by myself for more than a year before asking here.

**Comment by bpasero** [comment]
@sgon00 you can use a workspace file for that purpose. Doing so will associate the state with that file regardless of the directories within: https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by sgon00** [comment]
@bpasero thanks a lot for your reply. But I still don't figure out how to do it. I have read the link you provided and actually I use workspace for some years now. I have no ideas how to use workspace file to achieve this purpose. I have asked this question for more than a year and no one can answer it online. Can you please teach me what the proper steps are? For example, I tried the following steps which don't work:

* Launch vscode with `code myProjectDir\`
* Open some files in vscode (opened editors)
* In vscode, **File** -> **Save Workspace As...** -> save the file as `myProjectDir\myproject.code-workspace`
* Quit vscode
* Change the directory name `mv myProjectDir\ myProjectDirNew\`
* Start a new vscode
* In vscode, **File** -> **Open Workspace...** -> choose the workspace file `myProjectDirNew\myproject.code-workspace`
* All my previous opened editors session is lost now. Because the directory name is changed and the workspace file actually has no information regarding opened editors.
