### ISSUE TITLE
Search: allow to match on entire word in combination with regex option

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#71455]
Currently we do not seem to respect the "match entire word" option when enabling regex search. The editor find widget does respect it.

**Comment by roblourens** [comment]
Seems to work for me. But it will be imperfect because "entire word" is sort of a hack. And behavior differences in some cases could come from https://github.com/microsoft/vscode/issues/27280

**Comment by roblourens** [comment]
And this kind of thing https://github.com/microsoft/vscode/issues/66411
