### ISSUE TITLE
Configure Excludes is too aggressive, will not allow my project

### ISSUE THREAD

**Issue by Yzrsah** [Microsoft/vscode#71468]
**The Curse of the Dreaded Configure Excludes**

After a random delay... Maybe 2 hours... Suddenly I get:

![Configure Excludes](https://i.imgur.com/xhiI7DN.png)

I have configured all possible excludes.
I have excluded all possible module directories.
I have excluded all possible build directories.
I've added numerous specific path to exclude even more things.

in jsconfig.json
```
    "exclude": [
        "node_modules",
        "**/node_modules",
        "**/build",
        "more_excludes",
        "**/even_more_excludes",
```

Please allow the project to continue without the curse of the dreaded configure excludes.

**Comment by mjbvz** [comment]
Please provide more info about your project structure or check the tsserver logs to see which files are being included incorrectly:


1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look at the end of the logs for long lists of files that are included in your project. Do these files match your expectation?

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this

**Comment by Yzrsah** [comment]
@mjbvz Sorry I didn't respond yet. Can you please re-open the issue?

**Comment by Yzrsah** [comment]
@mjbvz Sorry I didn't respond yet. Can you please re-open the issue? 

This is a very serious problem, it is the #1 problem in VSCode

I didn't respond because the situation "improved" for a few days with an Insiders build and I was trying to find out if it was working

**Comment by mjbvz** [comment]
So does it work on insiders? If not please take a look at the logs as I suggested and share the results

**Comment by Yzrsah** [comment]
@mjbvz On it right now

**Comment by Yzrsah** [comment]
@mjbvz `tsserver.log` shows the list of source files match my expectations.

But there's also 10,000 `.d.ts` files.

The indexed `.d.ts` files do not utilize the jsconfig.json excludes, so the log shows every possible `**/node_modules/**/*.d.ts`

Is that normal?

On a side note, `TypeScript: Open TS Server log` command is not existing anymore

**Comment by Yzrsah** [comment]
My response may have been wrong, I'm trying to figure it out. The log has more stuff, I need to sort out the caches

**Comment by Yzrsah** [comment]
@mjbvz As far as I can tell, you smart Microsofters made this problem disappear on the most recent Insiders build.

Suddenly I am unable to even reproduce the issue.

I just opened 50 files across different yarn workspaces and I can't even get the Excludes warnings to pop up. Maybe the problem will return after VSCode runs for a number of hours. I can report back.
