### ISSUE TITLE
Problems: there are some behaviour things in trees to consider

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7146]
Our trees typically behave like this:
* clicking with the mouse keeps focus in the tree (see below for explanation)
* double click moves focus to the editor
* Cmd/Ctrl+click opens the editor to the side

You can see this in action e.g. in search: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L892

When I use the mouse to click on an entry in the problems list, I would expect focus to remain in the list. It seems you open an editor without specifying the `preserveFocus` option which would keep the focus in the tree.

Of course only use that option when the mouse is used, not on enter. I would also think that doubleclick should move focus into the editor too.

**Comment by sandy081** [comment]
@bpasero I was following the same behavior as search.. Previously in search,
- mouse click switched focus to the editor

I think with stacks changes behavior got changed. I will update with new behavior in error-list also.
Thanks

**Comment by sandy081** [comment]
@bpasero I am confused about the new behavior in Search view. 

If the file is in open editors list, then
- Single click and Double click opens the file at the position and focus remains in tree
- Enter opens the file at the position and focus is in file
- Cmd/Ctrl+click opens the editor to the side and focus remains in tree

Else
- Single click, Double click and Enter opens the file at the position and focus remains in tree
- Cmd/Ctrl+click opens the editor to the side and focus remains in tree

Let me know if this is expected. IMO, this is not a better user experience when iterating search results either by mouse or keyboard.

**Comment by sandy081** [comment]
Also, it is not very intuitive to know at which position in the file, the currently selected result is shown, if there are more results visible in the page.. See the attached screenshot

![One of the search results shown in the file](https://cloud.githubusercontent.com/assets/10746682/15759800/b070be36-2910-11e6-8315-d752cc41ffd2.png)

**Comment by bpasero** [comment]
@sandy081 wow, I totally broke double click with the stacks work, good catch! it should definitely focus the editor on double click :). 

As for the broken behaviour in search where it would loose focus on single click, that was a bug from stacks I fixed.

**Comment by bpasero** [comment]
@sandy081 the currently selected search match causes a stronger decoration in the editor, but this is very slight. @bgashler1 didn't you want to talk about this in our UX meeting?

**Comment by sandy081** [comment]
@bpasero I think on ENTER is also broken just similar to double click, hope you gonna fix this too. I would wait until your fix. Thanks.

**Comment by bpasero** [comment]
@sandy081 yeah all fixed on master!

**Comment by sandy081** [comment]
@bpasero Thanks for fixing. 

I have changes now with the expected behavior. But as an impact, highlighting has to be supported in problems view, otherwise it is very hard to see the selected problem in the file on single click. 

I am thinking it will add more mess to the editor, in the sense, when in Search view and problems panel is opened, editor will have many highlights specific to search and error.

**Comment by bpasero** [comment]
True, search adds a stronger decoration over the currently selected search result.

**Comment by bpasero** [comment]
Actually there is another bug that the editor does not show the current active line if it does not have focus. I think once that bug is fixed, maybe we do not need to do anything special?

**Comment by sandy081** [comment]
Right, that will give better experience

**Comment by sandy081** [comment]
Since the mentioned behavior in the description is not user friendly due to issues like
- Hard to see the selected problem in the file on single click 
- Editor would be clumsy with too many selectors when both search and problems views are opened

I am not in favor of implementing this until we get UX input.

@bpasero @bgashler1 Consider this during UX discussion.

Thanks

**Comment by bpasero** [comment]
@sandy081 can you please clarify where exactly you see issues?

**Comment by sandy081** [comment]
@bpasero Mainly for following reason

- When I am navigating the results/problems using single click, It is not clear in the file at what line the currently selected result/problem is in

**Comment by bpasero** [comment]
@sandy081 so you would argue that due to this you move focus into the editor?

**Comment by sandy081** [comment]
@bpasero No, what I am saying is implementing this behavior with above issue is not giving good user experience. Hence suggesting to get a solution for that before implementing.

**Comment by bpasero** [comment]
@sandy081 but loosing focus after clicking is super bad UX behaviour. So it is good you fixed that. Now you can focus on decorating the currently selected problem :)
