### ISSUE TITLE
Debug Adapter: all debug bar buttons dimmed after breakpoint hit

### ISSUE THREAD

**Issue by willportnoy** [Microsoft/vscode#71462]
Issue Type: <b>Bug</b>

In my custom debug adapter, I find that the Debug bar buttons and Debug menu options for continue/step/etc are all dimmed even though the thread is marked as "PAUSED ON BREAKPOINT".  Is that combination of states even possible?  The debugger adapter is still connected, and I can explore the stack frames and variables just fine.

It seems like the UI state is out of sync - is there some mitigation where I can restore that state?

![image](https://user-images.githubusercontent.com/17912714/55255288-7d371c80-5217-11e9-95fd-d432aee117cd.png)

![image](https://user-images.githubusercontent.com/17912714/55255334-9fc93580-5217-11e9-84b0-7ea112c8b224.png)

![image](https://user-images.githubusercontent.com/17912714/55255370-ba031380-5217-11e9-925b-5759e9260677.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.70GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
dialog-debugger|Mic|0.0.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.34.0
Ionide-Paket|Ion|1.12.0
json-to-ts|Mar|1.5.5
azurecli|ms-|0.4.4
csharp|ms-|1.18.0
powershell|ms-|1.12.0
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.5.0
debugger-for-chrome|msj|4.11.3

</details>

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders https://code.visualstudio.com/insiders/
We have changed how these actions are contributed and this should be fixed with latest

**Comment by willportnoy** [comment]
I just installed VS Code Insider and there are different problems:

1. the pause button lights up, but the only thread is already paused at a breakpoint
2. the casing of the file system drive path now seems to be different (possibly a different issue - c: is cased differently)

![image](https://user-images.githubusercontent.com/17912714/55430837-eb475080-5543-11e9-8278-415f6d1a68b6.png)

Here is a log of the messages sent back and forth with output events removed (I rarely see configuration done, by the way):

READ: {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"dialog","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
SEND: {"body":{"supportsConfigurationDoneRequest":true},"request_seq":1,"success":true,"command":"initialize","message":null,"seq":1,"type":"response"}
SEND: {"body":{},"event":"initialized","seq":2,"type":"event"}
READ: {"command":"setBreakpoints","arguments":{"source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"lines":[1],"breakpoints":[{"line":1}],"sourceModified":false},"type":"request","seq":2}
SEND: {"body":{"breakpoints":[{"verified":false,"message":null,"source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"line":1,"column":null,"endLine":null,"endColumn":null,"id":1}]},"request_seq":2,"success":true,"command":"setBreakpoints","message":null,"seq":4,"type":"response"}
READ: {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":3}
SEND: {"body":{},"request_seq":3,"success":true,"command":"setExceptionBreakpoints","message":null,"seq":5,"type":"response"}
READ: {"command":"threads","type":"request","seq":4}
SEND: {"body":{"threads":[]},"request_seq":4,"success":true,"command":"threads","message":null,"seq":6,"type":"response"}
SEND: {"body":{"threadId":1,"reason":"started"},"event":"thread","seq":8,"type":"event"}
SEND: {"body":{"reason":"changed","breakpoint":{"verified":true,"message":null,"source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"line":1,"column":null,"endLine":null,"endColumn":null,"id":1}},"event":"breakpoint","seq":11,"type":"event"}
READ: {"command":"threads","type":"request","seq":5}
SEND: {"body":{"threads":[{"id":1,"name":"threadOne"}]},"request_seq":5,"success":true,"command":"threads","message":null,"seq":14,"type":"response"}
SEND: {"body":{"reason":"breakpoint","description":"'threadOne' is Breakpoint","threadId":1,"text":"'threadOne' is Breakpoint","preserveFocusHint":false,"allThreadsStopped":true},"event":"stopped","seq":13,"type":"event"}
READ: {"command":"threads","type":"request","seq":6}
SEND: {"body":{"threads":[{"id":1,"name":"threadOne"}]},"request_seq":6,"success":true,"command":"threads","message":null,"seq":15,"type":"response"}
READ: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":7}
SEND: {"body":{"stackFrames":[{"name":"FRAMENAMEREMOVED","source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"line":1,"column":1,"endLine":83,"endColumn":1,"id":1},{"name":"planning[]","source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"line":1,"column":1,"endLine":83,"endColumn":1,"id":2}]},"request_seq":7,"success":true,"command":"stackTrace","message":null,"seq":16,"type":"response"}
READ: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":8}
SEND: {"body":{"stackFrames":[{"name":"FRAMENAMEREMOVED","source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"line":1,"column":1,"endLine":83,"endColumn":1,"id":3},{"name":"planning[]","source":{"name":"FILENAMEREMOVED","path":"FULLPATHREMOVED"},"line":1,"column":1,"endLine":83,"endColumn":1,"id":4}]},"request_seq":8,"success":true,"command":"stackTrace","message":null,"seq":17,"type":"response"}
READ: {"command":"scopes","arguments":{"frameId":1},"type":"request","seq":9}
SEND: {"body":{"scopes":[{"expensive":false,"name":"FRAMENAMEREMOVED","variablesReference":1}]},"request_seq":9,"success":true,"command":"scopes","message":null,"seq":18,"type":"response"}
READ: {"command":"variables","arguments":{"variablesReference":1},"type":"request","seq":10}
SEND: {"body":{"variables":[{"name":"user","value":"Count = 0","variablesReference":2},{"name":"conversation","value":"Count = 0","variablesReference":3},{"name":"dialog","value":"Count = 0","variablesReference":4},{"name":"turn","value":"Count = 0","variablesReference":5},{"name":"entities","value":"Count = 0","variablesReference":6},{"name":"tags","value":"Count = 0","variablesReference":7}]},"request_seq":10,"success":true,"command":"variables","message":null,"seq":19,"type":"response"}

**Comment by willportnoy** [comment]
@isidorn do you need more information than the above comment?

**Comment by isidorn** [comment]
Please change the mock debug adapter and create a repo on github with reproducable steps https://github.com/Microsoft/vscode-mock-debug
Otherwise I will unforunetly not be able to help since I can not reproduce this.

**Comment by willportnoy** [comment]
@isidorn do you know why in the above trace configurationDone is never sent after my response to setExceptionBreakpoints?  It might help me narrow down the difference between the mock debug adapter and my custom adapter.

**Comment by weinand** [comment]
@willportnoy you have to "opt into" the "configurationDone" mechanism by returning a value of `true` for the `supportsConfigurationDoneRequest` capability.

**Comment by willportnoy** [comment]
@weinand I believe supportsConfigurationDoneRequest is already (hopefully correctly?) included in the response body for initialize in the trace above.

**Comment by isidorn** [comment]
VSCode > F1 > Developer Tools > sources > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/26cebd0ce79f7632a1d9a82b2b4821007d732701/src/vs/workbench/contrib/debug/electron-browser/debugSession.ts#L611) and investigate why the sendConfigurationDone is not called.
Also make sure you send out an `initialized` event from your debug adapter. Put a breakpoint [here](https://github.com/Microsoft/vscode/blob/26cebd0ce79f7632a1d9a82b2b4821007d732701/src/vs/workbench/contrib/debug/electron-browser/rawDebugSession.ts#L117) on the vscode side to verify all is good.

**Comment by willportnoy** [comment]
@isidorn @weinand thank you for the help - it turned out that I had some errors encoding the protocol json into the TCP stream, causing some response messages to be apparently skipped.
