### ISSUE TITLE
Description view fails to open when diff editor is visible

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#71463]
Issue Type: <b>Bug</b>

* Open a PR
* Open description view
* Open a diff editor from file changes
* Click Description node again, nothing happens.

Extension version: 1.88.1
VS Code version: Code - Insiders 1.33.0-insider (4039ea871879ef8f654f27df5c32d209104b3a44, 2019-03-29T10:48:35.896Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_5281033|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by weinand** [comment]
@RMacfarlane if PR #71464 fixes this issue and is already merged, please close this issue.
