### ISSUE TITLE
Not finding extensions

### ISSUE THREAD

**Issue by PawanRoy1997** [Microsoft/vscode#71477]
Issue Type: <b>Bug</b>

I am trying to search a plugin but vscode is not searching it, not only this but is not searching any extension

VS Code version: Code - Insiders 1.33.0-insider (4039ea871879ef8f654f27df5c32d209104b3a44, 2019-03-29T10:48:26.004Z)
OS version: Linux x64 4.18.0-16-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|11.60GB (6.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
vscode-todo-plus|fab|4.13.0
php-intellisense|fel|2.3.10
rest-client|hum|0.21.2
python|ms-|2019.3.6215
laravel-blade|one|1.18.0
vscode-icons|vsc|8.4.0
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please provide more detailed steps.
How do you search for extension?
What is the result?

**Comment by PawanRoy1997** [comment]
I pressed ctrl+shift+p  
then I typed install extensions, then a tab opened at the left end. There is a search bar at the top, I just typed Python, before searching there were some extensions but when I started typing they all just disappeared, and I waited for about 3 mins there were no options just a progress bar was going from left to right... My internet connection was fast and when I removed everything from search bar all Initial options became visible... I installed some of them but it was not that must satisfactory experience, compared to sublime and atom

**Comment by sandy081** [comment]
@PawanRoy1997 Are you behind any proxies? Can you please open network tab and check if there are any errors in the requests to Marketplace. You can open network tab by
using the command `F1 > Toggle Developer Tools > Network`
