### ISSUE TITLE
Disable/Enable Emmet Command

### ISSUE THREAD

**Issue by smhmd** [microsoft/vscode#71472]
I have Emmet enabled for more than html files and it gets in the way more often than not. It is always the top suggestion (as it should, I like that) in order to write custom tags. To only enable it when I am going to write html/pug/jsx.. code and maybe toggle it with a keyboard shortcut would be great.

```
"emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "vue": "jade"
  },

**Comment by rzhao271** [comment]
@smhmd is your goal to add an Emmet command to disable expansion suggestions?

**Comment by smhmd** [comment]
@rzhao271 When I used pug inside vue files, Emmet suggestions popped up everywhere. I haven't used pug in well over a year, and I don't think the solution I proposed here would have solves the issue right at its root.

**Comment by rzhao271** [comment]
Reminds me a bit of https://github.com/microsoft/vscode/issues/51537
Thanks for the feedback
