### ISSUE TITLE
When two extensions activate on same event, second activation does not complete before event runs

### ISSUE THREAD

**Issue by itowlson** [Microsoft/vscode#71471]
Issue Type: <b>Bug</b>

Consider an extension E1 that declares a command `foo` and activates on `onCommand:foo`, and another extension E2 that depends on E1 and also activates on `onCommand:foo`.  An example is if `foo` displays a list of options that can be extended through E1's API object, and E2 adds an entry to that list.

Suppose now that a user has both E1 and E2 installed (but neither has activated yet), and invokes `foo` via the command palette.  What I'm seeing is that E1 activates and starts running the handler for `foo`, and _then_ E2 activates (presumably at some point where the command handler yields the main thread or something like that?).  For example, `foo` displays the entries set up by E1, but not those added by E2.

This only happens the first time I run `foo` - by the second time, E2 has had its chance to activate and it all works fine.  Similarly, if E1 has already activated for some other reason, then E2's activation _does_ happen before the command runs, and everything works fine even the first time.

I have found that introducing a delay before the command runs does _not_ reliably fix the problem, but running a dummy command (via `vscode.commands.execute`) and awaiting that _does_ seem to give E2 the chance to stick its oar in.

I have also seen this with views, where if two extensions activate on the same view, and the second wants to participate in view (TreeDataProvider) initialisation via an API object, I need to force VS Code to perform a refresh of the view not just via a call on the TreeDataProvider but via a _command_ that triggers the refresh - otherwise the second extension's contributions are not included in the initial display.

If it's relevant, the E2 activate methods are `async` - this is necessary because getting the E1 API object is inherently async.

Is it possible to fix VS Code so that _all_ extensions that activate on an event are allowed to complete their initialisation (including any async continuations) before the event is 'executed' please?  Alternatively, is there a recommended workaround, ideally one that can be implemented entirely within E1 (so that authors of extensions that consume E1's API don't need to worry about it)?

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (3.96GB free)|
|Process Argv|--folder-uri file:///c%3A/GitHub/vscode-kubernetes-tools-api-samples/kind-cluster-provider|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.5.1
tslint|eg2|1.0.43
vscode-pull-request-github|Git|0.5.1
duffle-vscode|ms-|0.0.5
vscode-kubernetes-tools|ms-|0.1.18
python|ms-|2019.3.6215
azure-account|ms-|0.8.0
csharp|ms-|1.18.0
Go|ms-|0.9.2
azurerm-vscode-tools|msa|0.5.0
vscode-yaml|red|0.4.0
rust|rus|0.5.4

</details>

**Comment by alexandrudima** [comment]
@jrieken This seems like a good use-case. This race came in via https://github.com/Microsoft/vscode/commit/5c6694ca2811dfc37740a924597c2e2587cf2f6a

Perhaps we should only race against `*` and not against `onCommand:X` ?

To repro:

* `71471.a/package.json`
```js
{
    "publisher": "71471",
    "name": "a",
    "engines": {
        "vscode": "^1.0.0"
    },
    "version": "0.0.0",
    "activationEvents": [
        "onCommand:myCommand"
    ],
    "main": "./index.js",
    "contributes": {
        "commands": [
            {
                "command": "myCommand",
                "title": "My Command"
            }
        ]
    }
}
```
* `71471.a/index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {

    console.log(`71471.a: activate called!`);

    vscode.commands.registerCommand('myCommand', function () {
        console.log(`71471.a: command is executing`);
    })

    console.log(`71471.a: returning from activate function!`);

    return {
        register: function () {
            console.log(`71471.a: somebody called register`);
        }
    }
};
```

* `71471.b/package.json`:
```js
{
    "publisher": "71471",
    "name": "b",
    "engines": {
        "vscode": "^1.0.0"
    },
    "version": "0.0.0",
    "activationEvents": [
        "onCommand:myCommand"
    ],
    "main": "./index.js",
    "extensionDependencies": [
        "71471.a"
    ]
}
```

* `71471.b/index.js`:
```js
const vscode = require('vscode');

function timeout(time) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, time);
    })
}

exports.activate = function () {
    console.log(`71471.b: activate called!`);

    return timeout(1000).then(() => {
        console.log(`71471.b: 1s elapsed!`);

        const ext = vscode.extensions.getExtension(`71471.a`);
        ext.exports.register();


        console.log(`71471.b: returning from activate!`);
    });
};
```

**Comment by jrieken** [comment]
> @jrieken This seems like a good use-case. This race came in via 5c6694c

I believe this only came in because we indefinitely wait for extension activation. If we take that as root cause and if we find a fix for it then this issue might become obsolete?

> Perhaps we should only race against * and not against onCommand:X around here?

Not sure that I understand. We race the command registration against all activation - * and onCommand.
