### ISSUE TITLE
Problems: embed the search box into the header

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7147]
Instead of showing an action to enable the "type to filter", why do we not just embed an input field in the header that you can just start typing?

It is possible to contribute actions to the header that heave their own UI. E.g. the dropdown in the debug viewlet or output channel is done like that:

<img width="333" alt="screen shot 2016-06-02 at 19 25 05" src="https://cloud.githubusercontent.com/assets/900690/15754259/ba029d3e-28f7-11e6-97f3-d85220301ac5.png">

**Comment by sandy081** [comment]
@bpasero That's a good idea.. this would also fix some usability issues. Thanks.
