### ISSUE TITLE
USB cannot exit from your computer

### ISSUE THREAD

**Issue by dragonmenorka** [Microsoft/vscode#71478]
Issue Type: <b>Bug</b>

<u>Steps to reproduce:</u>
<ul>
<li>Connect an USB</li>
<li>Program 1 file of it or more</li>
<li>When you finish, then close VS Code</li>
<li>Try to take the USB</li>
</ul>
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|3.3.11

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
What do you mean by "USB"?

**Comment by weinand** [comment]
no reply -> closing
