### ISSUE TITLE
"Shell Script" cannot identify multi-line command substitution.

### ISSUE THREAD

**Issue by Magicloud** [Microsoft/vscode#71479]
Issue Type: <b>Bug</b>

Sample code
```
someVar="$(someCmd | while read -r aVar; do
  someProc "${aVar}"
done)"
anotherLine
```
VSCode cannot identify the "end" of the quote for someVar. So anotherLine is colored as inside the string.

VS Code version: Code - OSS 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-21T22:49:07.188Z)
OS version: Linux x64 5.0.5-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2537M CPU @ 1.40GHz (4 x 1058)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vimStyle|74t|0.5.7
vscode-hie-server|ala|0.0.25
vscode-ghc-simple|dra|0.1.7
haskutil|Edk|0.4.2
haskell-linter|hoo|0.0.6
hoogle-vscode|jca|0.0.7
language-haskell|jus|2.5.0
hlint|lun|0.5.1
haskero|Van|1.3.1

</details>

**Comment by alexr00** [comment]
@Magicloud, can you give an example of what the syntax highlighting looks like and what it should look like?

**Comment by Magicloud** [comment]
Wrong:
![1554278759](https://user-images.githubusercontent.com/1886157/55463278-3daf6c80-562b-11e9-8226-7280ebf85407.png)
Correct:
![1554278923](https://user-images.githubusercontent.com/1886157/55463277-3daf6c80-562b-11e9-867f-3a2719cdd3d1.png)

Before I commented out the selection part, code following was rendered in "string" color. After I commented the problem part, following code was rendered correctly.

**Comment by alexr00** [comment]
Moved to the correct repo
