### ISSUE TITLE
Breakpoint on provided document: "Cannot read property 'isVisible' of undefined"

### ISSUE THREAD

**Issue by prb28** [Microsoft/vscode#71480]
Issue Type: <b>Bug</b>

Very similar to https://github.com/Microsoft/vscode/issues/56639. Same exception source line : https://github.com/Microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/editor/common/viewModel/splitLinesCollection.ts#L744:49

Debuging using extension : https://github.com/prb28/vscode-amiga-assembly/tree/copper_debug.

A breakpoint is set on a provided (TextDocumentContentProvider) document containing disassembled code. Sometimes this error apears and the document can't be opened (1 over 5 to 10 calls).
Debugging shows that the content is provided as expected, the error occurs during the document display function.

stack:
notificationsAlerts.ts:40 Unable to open 'copper_$5850__500.dbgasm': Cannot read property 'isVisible' of undefined.
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:584
notify @ notifications.ts:113
notify @ notificationService.ts:52
doHandleOpenEditorError @ editorGroupView.ts:827
t.editorControl.openEditor.then.t @ editorGroupView.ts:803
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
doShowEditor @ editorGroupView.ts:792
doOpenEditor @ editorGroupView.ts:784
openEditor @ editorGroupView.ts:743
doOpenEditor @ editorService.ts:245
openEditor @ editorService.ts:238
openInEditor @ debugSource.ts:87
openInEditor @ debugModel.ts:385
focusStackFrame @ debugService.ts:785
t @ callStackView.ts:162
disposables.push.n.onDidOpenResource.e @ callStackView.ts:170
fire @ event.ts:584
open @ listService.ts:733
onSelection @ listService.ts:728
_register.tree.onDidOpen.e @ listService.ts:696
fire @ event.ts:584
e @ event.ts:56
fire @ event.ts:584
e @ event.ts:56
fire @ event.ts:584
open @ listWidget.ts:1572
onPointer @ listWidget.ts:614
onPointer @ abstractTree.ts:885
fire @ event.ts:586
e @ event.ts:56
fire @ event.ts:584
s @ event.ts:16

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
@prb28 I am quite interested to try to figure this one out, but I could not reproduce. 

I have tried the extension and the example at https://github.com/prb28/vscode-amiga-wks-example/releases

I am not getting that exception... I am opening `gencop.s` and placing a few breakpoints and hitting F5... Do you have any more steps?

**Comment by prb28** [comment]
To reproduce it, you'll need my 'dev' version of fs-uae and extension. Can you tell me which os you use and I will prepare a workspace ?
I think this happens when the breakpoints are on a provided content file bigger than the window (scroll bars are visible). 
On a smaller text or with a dummy text returned without using a promise it seems to work <- I'm not sure this test was done correctly.

**Comment by alexandrudima** [comment]
Thanks for the quick response. Can you prepare it for Linux? Thank you!

**Comment by prb28** [comment]
First, thank you for trying to reproduce this issue.

Here is the workspace: [wks-issue-71480.zip](https://github.com/Microsoft/vscode/files/3035878/wks-issue-71480.zip)
And the extension: [amiga-assembly-0.14.0.vsix.zip](https://github.com/Microsoft/vscode/files/3035880/amiga-assembly-0.14.0.vsix.zip)
To reproduce:
- Open the linux workspace file
- add a breakpoint in gencop line 130
- Run the linux debug launch configuration ... wait for the breakpoint hit
- Click on the copper thread and add two breakpoints in 3e08 and 3e18 adress
- Click on continue (or F5), until the bug appears.

I'm sorry these binaries are 'beta' so some crashes may occur. On the linux version you may have to restart the debugger on a crash at debugger start.
I hope you'll reproduce it !

**Comment by alexandrudima** [comment]
Thank you for the detailed steps, I am able to reproduce. The root cause is that someone, somewhere sets the editor selection a fractional line number:

![image](https://user-images.githubusercontent.com/5047891/55490235-b9adb280-5633-11e9-8e33-fe5bb35b1331.png)

This ends up trying to access an array with a fractional index:

![image](https://user-images.githubusercontent.com/5047891/55490281-d1853680-5633-11e9-8b4b-3e6d4dcad998.png)

FYI @weinand @isidorn -- it looks like fractional line numbers make it through from the debug adapter. I will work on adding protection on my side, but just FYI, you might have other problems due to fractional line numbers:

```
convertModelPositionToViewPosition (splitLinesCollection.js:540)
convertModelPositionToViewPosition (splitLinesCollection.js:38)
convertModelPositionToViewPosition (cursorCommon.js:222)
_setState (oneCursor.js:71)
setState (oneCursor.js:49)
setStates (cursorCollection.js:90)
setStates (cursor.js:134)
setSelections (cursor.js:241)
_setSelectionImpl (codeEditorWidget.js:403)
setSelection (codeEditorWidget.js:395)
applyViewState (editor.js:414)
apply (editor.js:395)
input.resolve.then (textResourceEditor.js:53)
_tickCallback (internal/process/next_tick.js:68)
Promise.then (async)
setInput.then (textResourceEditor.js:36)
_tickCallback (internal/process/next_tick.js:68)
Promise.then (async)
setInput (textResourceEditor.js:35)
doSetInput (editorControl.js:126)
openEditor (editorControl.js:47)
doShowEditor (editorGroupView.js:603)
doOpenEditor (editorGroupView.js:597)
openEditor (editorGroupView.js:563)
doOpenEditor (editorService.js:163)
openEditor (editorService.js:158)
openInEditor (debugSource.js:71)
openInEditor (debugModel.js:301)
focusStackFrame (debugService.js:643)
focus (debugSession.js:535)
_tickCallback (internal/process/next_tick.js:68)
Promise.then (async)
fetchThreads.then (debugSession.js:544)
_tickCallback (internal/process/next_tick.js:68)
Promise.then (async)
rawListeners.push.raw.onDidStop.event (debugSession.js:527)
fire (event.js:477)
RawDebugSession.debugAdapter.onEvent.event (rawDebugSession.js:65)
acceptMessage (abstractDebugAdapter.js:90)
$acceptDAMessage (mainThreadDebugService.js:221)
_doInvokeHandler (rpcProtocol.js:331)
_invokeHandler (rpcProtocol.js:316)
_receiveRequest (rpcProtocol.js:248)
_receiveOneMessage (rpcProtocol.js:171)
RPCProtocol._protocol.onMessage (rpcProtocol.js:61)
fire (event.js:477)
deliverMessages (ipc.net.js:328)
source (ipc.net.js:334)
fire (event.js:477)
_receiveMessage (ipc.net.js:552)
PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (ipc.net.js:436)
fire (event.js:477)
acceptChunk (ipc.net.js:182)
ProtocolReader._register._socket.onData.data (ipc.net.js:151)
listener (ipc.net.js:16)
emit (events.js:182)
addChunk (_stream_readable.js:279)
readableAddChunk (_stream_readable.js:264)
Readable.push (_stream_readable.js:219)
onread (net.js:636)
```

**Comment by weinand** [comment]
@alexandrudima Oh, interesting.
Thanks for letting us know...

**Comment by prb28** [comment]
@alexandrudima Thanks a lot, sorry you spent some time on this, I should have figured it out myself, and qualified better this issue. I have a good idea where the bug on my code is.
