### ISSUE TITLE
F13 as a keyboard shortcut

### ISSUE THREAD

**Issue by alivefromupstairs** [microsoft/vscode#71481]
- VSCode Version: 1.32.3
- OS Version: Windows 10.0.17763 Build 17763

Steps to Reproduce:

1. remap Capslock to F13 through autohotkey or registry 
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
"Scancode Map"=hex:00,00,00,00,00,00,00,00,02,00,00,00,64,00,3a,00,00,00,00,00
```
2. try to use it to as a keyboard shortcut and it won't work.

**Comment by alexandrudima** [comment]
I am a bit weary of doing the registry change, but I have a keyboard which has a physical F13 key. Pressing F13 on this keyboard is recognized correctly by VS Code.

**Comment by alivefromupstairs** [comment]
the register way still not working. the ahk wasn't working because it relied on the register change I made. closing because ahk on its own works.
