### ISSUE TITLE
Mixed indentation (tab in code, spaces in multiline string) does not work well in TypeScript

### ISSUE THREAD

**Issue by asfernandes** [microsoft/vscode#71484]
- VSCode Version: 1.32.3
- OS Version: Ubuntu 18.04

Situation: you code is indented with tabs but you open a multiline string that is indented with spaces.

Something like:

```ts
			await attachment.execute(transaction, `
				insert into table (field1, field2)
				  values (
				    ?,
				    ?)
				`);
```

When you are finishing this string lines and pressing enter, instead of respect the indentation of the previous line (starting with tab, then spaces), VSCode changes the new line to use only tabs.

**Comment by alexandrudima** [comment]
`"editor.useTabStops": false`
