### ISSUE TITLE
LinkageError while compiling Java

### ISSUE THREAD

**Issue by benebsiny** [Microsoft/vscode#71483]
I installed "Java Extension Pack" and ready to compile Java, but it shows: 

> Error: LinkageError occurred while loading main class HelloWorld
> 	java.lang.UnsupportedClassVersionError: Preview features are not enabled for HelloWorld (class file version 55.65535). Try running with '--enable-preview'

in DEBUG CONSOLE , how could I do? (I used Java 11)

**Comment by robertschaap** [comment]
@benebsiny see https://github.com/Microsoft/vscode-java-debug/issues/553 as well. For me it worked fine for about a week and then it broke. Following the steps in that issue works for me.

**Comment by niudiewei** [comment]
thank you
