### ISSUE TITLE
'compare with saved' tab does not update on saving the file

### ISSUE THREAD

**Issue by LabhanshAgrawal** [microsoft/vscode#71485]
Issue Type: <b>Bug</b>

Open any file and make some changes, but don't save them yet.
Right click on the file from the file list and click 'compare with saved'
In the comparison tab that opens, you can see the difference between the file on disk and the current state of the file
Now save the file
The comparison tab should show that both the files are same, but it does not update and the earlier diff is still being shown

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.4.0
bracket-pair-colorizer-2|Coe|0.0.28
gc-excelviewer|Gra|2.1.29
beautify|Hoo|1.4.11
hive-sql|jos|0.0.4
python|ms-|2019.3.6215
cpptools|ms-|0.22.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1403
color-highlight|nau|2.3.0
printcode|nob|3.0.0
vscode-sql-beautify|sen|0.0.4
vscode-icons|vsc|8.4.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
It seems to work for the first save at least but then no more. Help wanted if someone wants to grab this and investigate.

**Comment by AdamT213** [comment]
I'll take a crack at it

**Comment by bpasero** [comment]
thanks I went ahead and found the culprit

**Comment by AdamT213** [comment]
Thanks @bpasero. Don't think I would have figured that out anytime soon haha. If I want to find some ways to get more familiar with the codebase, and possibly find some smaller bugs to fix, do you have any advice on how I might do that?

**Comment by bpasero** [comment]
@AdamT213 we have a label "good first issue" that you should maybe check: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by AdamT213** [comment]
Wow. Didn't realize there were so many issues with that tag. I'll take a closer look. Thanks!

**Comment by LabhanshAgrawal** [comment]
Thanks a lot for fixing this.

**Comment by bpasero** [comment]
@alexr00 great catch

**Comment by sandy081** [comment]
This fix is not included in current insiders build. Needs new insiders build to verify.
