### ISSUE TITLE
Search/Replace in files creates no backups and overwrites files with 0 bytes if Code was unresponsive and user clicked "Reload"

### ISSUE THREAD

**Issue by randre70** [Microsoft/vscode#71489]
- VSCode Version: 1.32.3
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Search in files with complex regex over large project which matches several files (e.g. "import(\s|\r?\n)*\{([^;]|\s|\r?\n)*LoggerService([^;]|\s|\r?\n)*\}(\s|\r?\n)*from([^;]|\s|\r?\n)*'@myscope/logger';")
2. Make sure your regex matches a fair amount of files, let's say 100 files.
3. Repeat this search with replace in all files (e.g. "import$1{$2LoggingLevel, ILoggingFactory, CreateLoggingInstance$3}$4from$5'@myscope/logging';")
4. After some time - Code is unresponsive - a dialog appears and offers to "Wait" or "Reload" or "Quit", press "Wait"
5. Again after some time, when Code offers to "Wait", "Reload" or "Quit", press "Reload"
6. Several matched files have been overwritten and have 0 bytes size. There are no backups of those files (%APPDATA%/Code/backups) to recover your work.

Does this issue occur when all extensions are disabled?: No idea

**Comment by roblourens** [comment]
I can't reproduce this, even with 10000 results in 1000+ files, the window never stops responding.

Do you have a slow machine? Especially large files?

**Comment by roblourens** [comment]
This sounds similar to https://github.com/Microsoft/vscode/issues/34915, although the disk may not be full, it shows how interrupting a Save could have bad effects.

**Comment by randre70** [comment]
Machine used is i4960X, drive is NVMe with 3.5gb/s read and 2.4gb/s write

**Comment by roblourens** [comment]
Can you reproduce this consistently if you try again?
