### ISSUE TITLE
Probable mistype in copyFilePath shortcut command...

### ISSUE THREAD

**Issue by mikamiel** [Microsoft/vscode#71482]
Default VSCode(Windows) keybinding for `copyFilePath` command is set to:
```js
{
   "key": "shift+alt+c",
   "command": "copyFilePath",
   "when": "!editorFocus"
},
```
I suppose `"when": "!editorFocus"` condition is mistyped and should be `"when": "editorFocus"`, because usually we want to copy to clipboard a path of the currently edited/active file.
___
Version: 1.32.3 (system setup)  (32bit version)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T22:49:40.955Z
OS: Windows_NT ia32 6.1.7601

**Comment by isidorn** [comment]
No, it is not mistyped. That keybinding is taken by the find widget when the editor has focus. Thus we do this only when the focus is not in the editor.
You can of coure customise this to your own fitting, thus closing this as designed
