### ISSUE TITLE
Keyboard shortcut format removes newline at end of file, against convention

### ISSUE THREAD

**Issue by davelogear** [Microsoft/vscode#71487]
- VSCode Version: 1.32.3
- OS Version: Windows 7/10

Steps to Reproduce:

1. Code anything (syntactically-proper) in any language of its appropriate file type (like .html), except in an improperly-spaced/indented way (so that it would still run).
2. At the end of the file, hit Enter or Return to put a newline at the end of the file.
3. Hit your keyboard shortcut for auto-formatting the code (Ctrl-Shift-F for me).

Notice that the newline at the end of the file is removed; the problem with this is that:

A: Certain VCS programs/editors like git or SourceTree will warn you that no newline is at the end of the file.
B: Committing code without a newline then adding a new line of code will not only show the addition of the new line in a VCS as a changed line, but also the previous line - even though none of the text on that line was changed, making a false positive.

This has caused a few red herrings or unnecessary merge conflicts (when two people add a new line of code to the end of the same file) over my years working with multiple developers and code reviews, even to the point of people getting upset or in trouble, before closer inspection, thinking code was changed when it actually wasn't.

Removing the newline also goes against convention and good practice, which VS Code should have a good implementation for by now:

https://stackoverflow.com/a/34184247/9905557
https://unix.stackexchange.com/a/18789
https://coderwall.com/p/icxxna/don-t-forget-that-extra-line
https://www.quora.com/Why-is-it-good-practice-to-add-a-newline-to-the-end-of-a-file

I'm not seeing how to disable this auto-format quirk... but if possible, it will go on the list of things to configure when ramping up a new developer or setting up a new workstation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@davelogear in my understanding the "files.insertFinalNewline" setting addresses this issue, right?
