### ISSUE TITLE
TypeScript Intellisense shows incorrect function signature

### ISSUE THREAD

**Issue by govindrai** [Microsoft/vscode#71492]
Issue Type: <b>Bug</b>

```javascript
function add(num1: number, num2: number): number {
  return num1 + num2;
}
```

after writing the function above and then trying to call it, intellsense shows

`add(num1: any, num2: any): any` as its first suggestion

You have to go to the second suggestion to see the correct suggestion: add(num1: number, num2: number): number. 

It should only display the latter suggestion

Here's a visual
<img width="1680" alt="Screen Shot 2019-03-30 at 2 11 42 PM" src="https://user-images.githubusercontent.com/13859249/55281726-13da0b00-52f6-11e9-82b1-b0adca1e7b7d.png">

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|-psn_0_893146|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.8.1
vscode-pull-request-github|Git|0.5.1
chat|kar|0.12.0
python|ms-|2019.3.6215
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.1403
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.10
vscode-docker|Pet|0.6.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by govindrai** [comment]
Closing and reopening the file made the error go away, but definitely something going on there

**Comment by mjbvz** [comment]
You have opened both the js and ts version of the file. Since these files do not have any imports or exports, everything declared in them is considered global. Therefore it will see both the ts declaration of `add` plus the compiled js version of `add`

Try creating a simple [tsconfig](https://code.visualstudio.com/docs/typescript/typescript-tutorial#_tsconfigjson) to ensure that the ts file is treated as part of its own project
