### ISSUE TITLE
Automatically show changes side-by-side if there's only one group, otherwise show changes inline

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#71497]
Please add an option to automatically show Git diff changes side-by-side, if there's only one group, and inline, if there's two or more groups. Since the side-by-side changes is too narrow if there are two or more groups, so I always manually change it anyway. But it would be very useful to have this automated.

**Comment by mkolm** [comment]
Hi, I would like to attempt to fix this issue. @joaomoreno how do I know which files I should edit?
