### ISSUE TITLE
TensorFlow Recomendation Freeze

### ISSUE THREAD

**Issue by Akifhan** [Microsoft/vscode#71490]
Issue Type: <b>Performance Issue</b>

For python files whenever I try to see TensorFlow library recomendations vscode freezes the computer completely. No keyboard input or mouse action is possible. First I try to import the library with command;
import tensorflow as tf
After that using the naming alias I want to see the "tf.***" recomendations using keyboard shortcuts ctrl+space. This is the point where things get out of control, vscode tries to find all possible recomendations and list them however the search consumes a lot of resources and blocks everything going on in the computer.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2286)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 5, 4|
|Memory (System)|7.67GB (4.99GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    79	 12711	code main
    0	     0	 12715	   zygote
    0	   212	 12760	     window (● ageestimator.py - Code - Visual Studio Code)
    0	     0	 12852	       /bin/bash
    0	    24	 12855	       watcherService
    0	    94	 12862	       extensionHost
    0	   259	 12988	         /home/akifhan/anaconda3/bin/python completion.py
    0	   165	 12992	           /home/akifhan/anaconda3/bin/python lib/python/jedi/evaluate/compiled/subprocess/__main__.py lib/python
    0	    63	 13092	         /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=12862
    0	    39	 12826	     shared-process
    2	    86	 15189	     window (Issue Reporter)
    1	   126	 12744	   gpu-process
    0	     0	 15212	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 15213	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● ageestimator.py - Code - Visual Studio Code)
|    Folder (Code): 8882 files
|      File types: jpg(8874) py(4) gz(4)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|ms-|2019.3.6215
cpptools|ms-|0.22.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
