### ISSUE TITLE
python autocomplete not working for wxPython module

### ISSUE THREAD

**Issue by ejamshidiasl** [Microsoft/vscode#71502]
hi
i installed wxpython but vscode cannot load autocomplete for it. for other modules like tkinter , pyttsx3 and etc. autocomplete works completely.

i tested something and found it:
i wrote wx. and then write one other character like B (wx.B) and pressed ctrl+space after 10 seconds autocomplete page comes up.
i tested on visual studio 2019 RC4 and there is same problem with wxpython.

my pc: windows 10 latest update - cpu: core i7 - ram: 16gb DDR4
vscode: latest version
python: 3.7.2
wxpython: latest release from pip

**Comment by ejamshidiasl** [comment]
i just installed "ms-python.python" extension
no other extension !!!!

**Comment by Caterpillar3211** [comment]
I was having problems with auto-completion for wxpython too, now I'm using Wing IDE Pro. I find it better than vscode, only disadvantage of Wing is its appearance. But still, I would be happy if you'd shared with me how you solved the issue, if you did of course.
