### ISSUE TITLE
Assign keybinding to multiple languages and get rid of "langId" for snippet-keybinding reference

### ISSUE THREAD

**Issue by mrinalini-m** [Microsoft/vscode#71501]
[According to the docs](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets), you use the `langId` to reference an existing snippet for the key binding. But the `name` map works without specifying the `langId`.
And adding it to the args removes the language scoping of the keybinding as seen here: 

![ezgif-1-1b2c108e45ad](https://user-images.githubusercontent.com/3789040/55283303-fd8f7780-5314-11e9-838b-55ad482c657d.gif)

To remedy this, I had to add in `editorLangId` to the when clause. But this is redundant since the snippet was scoped to the language. 
 
I think this is a bug but I also have some suggestions on what would would be better:

1. Get rid of `langId` entirely. There's an `editorLangId` in the `when` clause and it's easy to confuse those two.  

2. It would eliminate the question - What would be the `langId` of a snippet defined in the global snippets file? It would also let the keybindings work on multiple languages if there were multiple `scope` languages. 

3. Regarding keybindings, [defining keybindings for multiple languages is an issue as brought up by this SO question](https://stackoverflow.com/questions/39122450/key-binding-when-condition-for-multiple-languages/55429071#55429071). I think it would make sense to eject `editorLangId` as a property and allow users to specify multiple languages like `scope` in snippet definitions. Right now, the only way to do it is to rewrite the key assignment for each language.   

So instead of:

```
{
  "key": "shift+cmd+l",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus && editorLangId == javascript",
  "args": {
    "snippet": "console.log(${1:}$SELECTION)${0};"
  }
},
{
  "key": "shift+cmd+l",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus && editorLangId == typescript",
  "args": {
    "snippet": "console.log(${1:}$SELECTION)${0};"
  }
},
```

it would be:

```
{
  "key": "shift+cmd+l",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "editorLangId": "javascript,typescript",
  "args": {
    "snippet": "console.log(${1:}$SELECTION)${0};"
  }
},
```

1. You could exclude languages with '!' infront.
2. If the snippet is scope specific, you wouldn't have to specify `editorLangId`. 
3. It wouldn't work if a language outside the snippets scope is specified.
4. But snippets would work in files with more than one language. E.g., it would work inside the script tag in an html file unless `editorLangId` has `!html`. 

- VSCode Version: 1.32.3 (I tried in the insiders app too. v 1.33.0)
- OS Version: macOS Mojave 10.14.3

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Not a real answer but you can make the current version shorter with regexes:
https://code.visualstudio.com/docs/getstarted/keybindings#_keyvalue-when-clause-operator

```json
{
  "key": "shift+cmd+l",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus && editorLangId =~ /javascript|typescript/",
  "args": {
    "snippet": "console.log(${1:}$SELECTION)${0};"
  }
},
```

**Comment by jrieken** [comment]
> But the name map works without specifying the langId.

When the lang id isn't specified it defaults to the document language but that's not always what you want. That's what there is support for langId
