### ISSUE TITLE
Lua highlighting bug in Light/Light+/Dark/Dark+

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#71504]
Issue Type: <b>Bug</b>

This isn't a huge deal, but this always throws me off when i need to edit Lua using default theme. Basically in Lua syntax highlight keywords "and", "or" and "not" are not highlighted like they are in other themes. This reproduces in Light/Light+/Dark/Dark+.

The issue might be related to the fact that in `lua.tmLanguage.json` those keywords are listed under `keyword.operator.lua` section while other Lua keywords are listed under `keyword.control.lua` (and they are properly highlighted).

Here is comparison of various themes:

![image](https://user-images.githubusercontent.com/993454/55286859-1e55dc80-53aa-11e9-9e83-9ca6471e0ad9.png)

Note that "and", "or" and "not" are highlighted in Solarized Light and Monokai, but not in Light+ and Dark+.

I suspect other languages might also be affected somehow, but i didn't check.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.4.0-142-generic

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.3.0
cpptools|ms-|0.19.0
shader|sle|1.1.4
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by alekseyt** [comment]
For Light theme, this seems to be deliberate decision:

```json
                {
			"scope": "keyword.operator",
			"settings": {
				"foreground": "#000000"
			}
		},
```

But for Light+ i'm not so sure, it may be that `keyword.operator` just wasn't covered with a particular style for some reason. Widening scope of this block from `keyword.control` to `keyword` highlights "and", "or" and "not", like this:

```json
		{
			"name": "Control flow keywords",
			"scope": "keyword",
			"settings": {
				"foreground": "#AF00DB"
			}
		},
```

**Comment by alekseyt** [comment]
> Widening scope of this block from keyword.control to keyword highlights "and", "or" and "not"

Or maybe not, i'm not really expert in themes. Light+ seems to include Light or something. This seems to do it:

```json
		{
			"name": "Operator keywords (or whatever)",
			"scope": "keyword.operator",
			"settings": {
				"foreground": "#AF00DB"
			}
		},
```

**Comment by alekseyt** [comment]
I just wanted to check how Github highlights this example:

```lua
if x and y or not z then
end
```

Although i think Github's highlighting is probably less sophisticated, but i think this could be used as a reference.

**Comment by alexr00** [comment]
@alekseyt, it looks like this is a deliberate decision in the theme since the lua grammar is correctly categorizing the operators. In the other themes (not Light/Light+/Dark/Dark+), the operators are just getting the keyword color. If you want to modify this for yourself you can do so in settings.json:
````json
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
			"textMateRules": [
                {
                    "scope": "keyword.operator",
                    "settings": {
                        "foreground": "#e63333"
                    }
                },
            ]
        }
    }
````
 @aeschli for themes since this isn't a grammar issue.

**Comment by alekseyt** [comment]
I appreciate the workaround, it works as expected, however i don't think it resolves the issue. Actually i've done blame on Light theme and found same issue was fixed in #24664 (df3c4151a89).

Will you accept a pull request with a patch(es) like this?

```diff
diff --git a/extensions/theme-defaults/themes/light_vs.json b/extensions/theme-defaults/themes/light_vs.json
index 97787c38bd..52c315a388 100644
--- a/extensions/theme-defaults/themes/light_vs.json
+++ b/extensions/theme-defaults/themes/light_vs.json
@@ -316,7 +316,8 @@
                                "keyword.operator.cast",
                                "keyword.operator.sizeof",
                                "keyword.operator.instanceof",
-                               "keyword.operator.logical.python"
+                               "keyword.operator.logical.python",
+                               "keyword.operator.lua"
                        ],
                        "settings": {
                                "foreground": "#0000ff"
@@ -368,4 +369,4 @@
                        }
                }
        ]
-}
\ No newline at end of file
+}
```

**Comment by alekseyt** [comment]
By the way this is what i see in Python (Light+):

![image](https://user-images.githubusercontent.com/993454/55475375-78f66f00-561c-11e9-981a-b92db7ed97a3.png)

The problem here is that keywords `for` and `if` are highlighted using `keyword.operator` style from Light+ (purple) while `in`, `and`, `or` and `not` keywords style was inherited from Light (blue).

TBH i couldn't care less, but just to let you know that proper fix for #24664 potentially was lost somewhere in between df3c415 and current master.

**Comment by alexr00** [comment]
Actually, it could be argued that the logical operators should be categorized as keyword.operator.logical, instead of just keyword.operator which makes this a grammar issue.

**Comment by alexr00** [comment]
Thanks for the investigation @alekseyt. I opened an issue in the repository that we get the grammar from.
@aeschli, you might want to update the themes still, since currently the keyword.operator.logical theming exists for python, and only for light, light+, dark, and dark+.

**Comment by aeschli** [comment]
The lua grammar also uses `keyword.operator.lua` for operators like `=` , `==`, `+`,  `*` which is what the default grammars what to keep on the default color.

So it would be good if the grammar uses a different scope for `and`, `or`and `not`, as done by other grammars

**Comment by aeschli** [comment]
Closing, should be fixed in the lua grammar. https://github.com/textmate/lua.tmbundle/issues/12 is the issue.
