### ISSUE TITLE
Pls add: Scientific View - Variable Explorer & Data Frame Viewer

### ISSUE THREAD

**Issue by Wishman** [Microsoft/vscode#71507]
You have partnered with anaconda, your Python interactive is great, but for proper data science, please add a variable explorer and a data (frame) viewer. Both PyCharm and even Spyder have it (see attachments) - Cheers, a true VS Code fan (especially for JS)

![Screenshot 2019-03-31 at 14 37 02](https://user-images.githubusercontent.com/6534784/55289190-6d5c3b80-53c3-11e9-8d1e-2327031c1a71.png)
![Screenshot 2019-03-31 at 14 18 11](https://user-images.githubusercontent.com/6534784/55289192-70572c00-53c3-11e9-8b8b-62552d6918a9.png)

**Comment by weinand** [comment]
Debugger extensions can easily support Variable Explorer & Data Frame Viewer. There is no need to have this functionality in VS Code.

**Comment by Wishman** [comment]
to my knowledge the Python Interactive window is not a "in debugging" mode. So no breakpoints, etc. In Data Science you generally don't run the program, but Shift-Enter individual statements to the interactive REPL and work your way through it. Please do not compare this to regular programming, it's a totally different approach. This lack keeps me and some fellow data scientists from using vs code for our data science projects in python

**Comment by Wishman** [comment]
ps. your python interactive window is useless without the above mentioned feature - at least from a data scientist's point of view

**Comment by weinand** [comment]
If the "Python Interactive window" is not used in debugging mode, then this feature is even more a feature of the Python extension and not VS Code.

**Comment by Wishman** [comment]
ok, is there a separate feature request page for the extension where I can drop this?

**Comment by Wishman** [comment]
found it - thanks for your help and your comittment to vs code - cheers & happy Sunday!

**Comment by weinand** [comment]
Sure!

When you file an issue from VS Code's "Report Issue" action in the Help menu, the dialog allows you to directly file the issue against the extension.

Alternatively you can open VS Code's extension view and search for the Python extension and click on the "Repository" tab:

<img width="1069" alt="2019-03-31_17-33-32" src="https://user-images.githubusercontent.com/1898161/55291107-43167800-53db-11e9-9dfc-e3d25e4ede2b.png">


Or just follow this link:
https://github.com/Microsoft/vscode-python/issues

**Comment by weinand** [comment]
Thank you for using VS Code and providing feedback.
Happy coding!
