### ISSUE TITLE
Workspace Add Folder Fail

### ISSUE THREAD

**Issue by hsmyers** [Microsoft/vscode#71514]
Issue Type: <b>Bug</b>

1. find keybindings.json file in tree
2. attempt to add folder to workspace
    folder: c:\Users\hsmyers\AppData\Roaming\Code - Insiders\User
3. the error message reads: The name <folder as shown in #2> is not a valid file or folder name. Please choose a different name.
4. same error using quotes
5. same error using short form: c:\Users\hsmyers\AppData\Roaming\CODE-I~1\User
6. %vsuserPath% silently fails as it does not expand

VS Code version: Code - Insiders 1.33.0-insider (4039ea871879ef8f654f27df5c32d209104b3a44, 2019-03-29T10:53:36.965Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor            (8 x 3512)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (20.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
numbered-bookmarks|ale|6.2.0
markdown-imsize|amo|0.0.2
html-class-suggestions|And|1.0.7
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
coffeescript-jsdoc|bam|0.2.2
vscode-custom-css|be5|3.0.3
markdown-emoji|bie|0.0.7
markdown-mermaid|bie|1.1.2
turbo-console-log|Cha|1.2.17
path-intellisense|chr|1.4.2
jsrefactor|cms|2.18.1
bracket-pair-colorizer-2|Coe|0.0.28
dakara-foldplus|dak|1.3.2
vscode-coffeescript-snippets|din|0.0.2
macros|ged|1.2.1
mdmath|goe|2.3.9
todo-tree|Gru|0.0.126
vscode-journal-view|Gru|0.0.25
path-autocomplete|ion|1.13.2
latex-workshop|Jam|6.2.2
reason-vscode|jar|1.5.2
markdown-extended|jeb|1.0.7
markdown-extension-pack|jeb|0.0.2
asciidoctor-vscode|joa|2.4.0
vscode-peacock|joh|2.0.0
vscode-insertdatestring|jsy|2.2.3
language-haskell|jus|2.5.0
perltidy-more|Kak|0.5.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Lisp|mat|0.1.8
vscode-clang|mit|0.2.3
vscode-html-format|moh|0.0.3
vscode-cosmosdb|ms-|0.10.0
azure-account|ms-|0.8.0
cpptools|ms-|0.22.1
printcode|nob|3.0.0
indent-rainbow|ode|7.4.0
vscode-journal|paj|0.9.1
coffeescript-formatter|prp|1.0.1
funclist|qrt|7.6.2
subtle-brackets|raf|3.0.0
perlcritic|sfo|1.0.2
perltidy|sfo|1.3.1
markdown-preview-enhanced|shd|0.3.13
html5-boilerplate|sid|1.0.3
indenticator|Sir|0.6.0
numbermonger|sof|0.4.0
code-spell-checker|str|1.6.10
vscode-markdown-paste-image|tel|0.12.0
vscode-input-sequence|tom|0.2.0
vscode-icons|vsc|8.4.0
change-case|wma|1.0.0
clang-format|xav|1.9.0
coffeescript-support|yor|0.2.0
markdown-all-in-one|yzh|2.2.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@hsmyers How are you adding the folder?

**Comment by hsmyers** [comment]
By clicking on the new folder icon in the workspace section of Explorer.

**Comment by sandy081** [comment]
@hsmyers Do you mean following button

![image](https://user-images.githubusercontent.com/10746682/55587089-e1337680-572a-11e9-87df-87f6edff7c27.png)

**Comment by hsmyers** [comment]
[image: Annotation 2019-04-04 183456.png]
This is the one that gave the error message. It is the normal EXPLORER
display in so far as I know The one associated with the File>Add Folder to
Workspace…works fine, it is what I used to solve my problem. I've not seen
the example you clipped.

**Comment by sandy081** [comment]
@hsmyers I do not see any screenshot from you.

**Comment by hsmyers** [comment]
Yes! all I see on this end is: [image: Annotation 2019-04-04 183456.png]! Let me see if drag and drop will work…
![Annotation 2019-04-04 183456](https://user-images.githubusercontent.com/937918/55740923-56cc6a80-59e9-11e9-8c4d-46c48ca20446.png)

**Comment by hsmyers** [comment]
Didn't mean to close the issue—sorry!

**Comment by hsmyers** [comment]
At this point I can see the image…

**Comment by isidorn** [comment]
I can not reproduce this issue.
@hsmyers please file with exact reproducable steps, what folder are you trying to create
Can you reproduce if you disable all extensions?

**Comment by hsmyers** [comment]
The folder is "c:\Users\hsmyers\AppData\Roaming\Code - Insiders\User"

First step: select the folder icon, second icon from the left on the
explorer line labeled <title> (WORKSPACE)
Second step: Click it. This opens an empty text box.
Third step: paste desired folder with or without quote marks (it makes no
difference) into the text box.
Immediate display of error message.

Regards extensions turning them off does not affect the error.
Note that I am not trying to create a folder, I am simply trying to add a
folder to my workspace. Likewise, note that this folder is not directly
contiguous to the workspace in question. Same directory tree but neither a
parent nor a child of the workspace itself.

**Comment by hsmyers** [comment]
I know that works since that is what I used to add the folder. I'd suggest
perhaps a more meaningful error message in that case? Claiming a directory
created by Visual Code is an illegal name seems kind of misleading?
