### ISSUE TITLE
PowerShell window not ready until you type something

### ISSUE THREAD

**Issue by TLKG** [Microsoft/vscode#71518]
it shows this
![image](https://user-images.githubusercontent.com/22269729/55295294-3f292c80-53c0-11e9-88ea-0d0119d97cf7.png)

until you type something 
![image](https://user-images.githubusercontent.com/22269729/55295334-c676a000-53c0-11e9-8721-1f60d04ef106.png)

- VSCode Version: 1.32.3 
- OS Version: win10 x64

Steps to Reproduce:

1. open a MEAN project
2. tab+`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
