### ISSUE TITLE
Problems: automatically expand file nodes similar to search results

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7151]
In search we have this logic to automatically expand a file node when it has less than 10 results within. Maybe we apply the same logic to problems?

**Comment by sandy081** [comment]
@bpasero I am doing same in error-lists as in search. It auto expands when a file has less than 10 markers.. on top of it added some smartness to not to open a file it is collapsed.. I see there are some cases which this is not as expected while applying filters.. I will check and make it more user friendly. 
Thanks
