### ISSUE TITLE
Theme changes made will not apply when VS code start again even if user settings was saved

### ISSUE THREAD

**Issue by abdulbadii** [Microsoft/vscode#71521]
I did change theme to night blue but applied only then. Later on once vs code start again it will not apply, instead it'd be back to black high contrast even if user settings was saved

![Snipaste_2019-04-01_05-33-34](https://user-images.githubusercontent.com/25836673/55296238-c918da00-5440-11e9-8f65-fdee6be820c1.png)

It's been up to a week I tried whatever I can to solve it to no avail..
Sincere useful help will be sincerely appreciated

**Comment by aeschli** [comment]
Is your OS in high contrast mode? If set we will always switch to a HC theme.
If that's not wanted, there's a setting `window.autoDetectHighContrast` to disable this behaviour.

**Comment by abdulbadii** [comment]
Exactly, Windows High contrast mode.. sorry just new in VS code, what should be done ?!

**Comment by aeschli** [comment]
Open the settings (Ctrl + comma), search for autoDetectHighContrast, disable the setting.

**Comment by abdulbadii** [comment]
Works like a charm !
Thanks much.
