### ISSUE TITLE
Circle badges in trees look off-centered vertically

### ISSUE THREAD

**Issue by c5inco** [Microsoft/vscode#71528]
Issue Type: <b>Bug</b>

The vertical centering of the circles look off when inline with text in the trees.  This is more notable in certain themes, such as Universe and Night Owl (extensions), and Visual Studio Dark.

![image](https://user-images.githubusercontent.com/1253402/55308244-f6e52b00-540e-11e9-886c-9aa8b893dd83.png)
![image](https://user-images.githubusercontent.com/1253402/55308273-10867280-540f-11e9-8f97-67292d2a8a0d.png)
![image](https://user-images.githubusercontent.com/1253402/55308252-fea4cf80-540e-11e9-8f14-110bc538c13e.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.25.0
flutter|Dar|2.25.0
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
Kotlin|mat|1.7.0
node-debug2|ms-|1.33.0
debugger-for-chrome|msj|4.11.3
polacode|pnp|0.2.2
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0

(13 theme extensions excluded)

</details>

**Comment by c5inco** [comment]
😅 @misolori @joaomoreno @bpasero

**Comment by joaomoreno** [comment]
![gif](https://media.giphy.com/media/MUeQeEQaDCjE4/giphy.gif)

**Comment by misolori** [comment]
The height of the rows were being bumped up by 1px, which caused them to look a bit stretched. Circle badges in the scm tree should now look the same as the rest of our badges.

![image](https://user-images.githubusercontent.com/35271042/55342562-ef00a780-545d-11e9-821b-226f205a7ce8.png)

**Comment by misolori** [comment]
Yea, only in that multi-root view with the split pane. We do also have weird alignment (~1px) in all of our badges due to their percentage/em sizing in a 22px row:

https://github.com/Microsoft/vscode/blob/5260a601f95bb5b2f87cd46daebd25aea00fee08/src/vs/base/browser/ui/countBadge/countBadge.css#L6-L9

**Comment by misolori** [comment]
@c5inco as I'm re-reading this, I'm wondering if you meant that the badges were off-center inside of the row or inside of the badge? Or both? 😄

**Comment by c5inco** [comment]
Both really - it sorta looked like an egg with the yolk gravitating towards the bottom. 😄

**Comment by misolori** [comment]
😄 This should fix that then

**Comment by alexr00** [comment]
I'm verifying and I see that the number inside the badge looks more centered, but the badge itself still looks to be a bit closer to the bottom of the row.

**Comment by misolori** [comment]
@alexr00 thanks for verifying, and yes this is just for the badge shape itself and not the position of it.
