### ISSUE TITLE
Gray out emojis when commented

### ISSUE THREAD

**Issue by mjarkk** [microsoft/vscode#71529]
I noticed that emojis are not grayed out when commented.  
This is a bit annoying when big parts of code are commented out and there are a view emojis in there that are colorized.  
Example:  
![Screenshot from 2019-04-01 09-12-16](https://user-images.githubusercontent.com/15320763/55309563-80701980-545e-11e9-9856-97573aacdb7d.png)

**Comment by pkostas1** [comment]
I would like to work on this.  Any pointers on where to start would be appreciated.

**Comment by mjarkk** [comment]
Whatever not an important feature. i'll close the issue
