### ISSUE TITLE
Hotkey: doesn't respond to any key combination with `(the grave accent)

### ISSUE THREAD

**Issue by RoadToDream** [Microsoft/vscode#71526]
- VSCode Version: 1.32.3
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Set "toggle terminal" to Ctrl+'
2. Does not respond to this combination

Keyboard Layout:
 - Standard US layout

Installed Extension
1. C/C++
2. LaTeX Workshop

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
Please see [this guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) for how to file a proper issue.

Include: 
* VS Code version
* OS version
* Installed extensions
* Steps to reproduce
* keyboard layout

Is the `(the grave accent) key a "dead key" on your keyboard (= requires another key before a character is entered)?

**Comment by RoadToDream** [comment]
@weinand Excuse me for an improper bug report, weird it doesn't include relative info as i have put them all in this report.

**Comment by weinand** [comment]
If you create bugs from within VS Code with the "Report Issue" command from the help menu, all information should be automatically there.

**Comment by RoadToDream** [comment]
macOS's weird strategy conflicts with VS code, cancelled all customization in settings and then it works well, and surprisingly find that VS code can react towards different input methods.
