### ISSUE TITLE
add symbol to refer to the file have been edit and wait to be saved

### ISSUE THREAD

**Issue by mohamed0123** [Microsoft/vscode#71539]
add symbol to recognize opened files that have been edited and still not saved

let assume that Launcher.js have been content edited and still not saved

image before
![Capture](https://user-images.githubusercontent.com/17961077/55323632-e28d4680-547f-11e9-9f44-5eefdb4a18df.PNG)

image after suggestion

![Capture](https://user-images.githubusercontent.com/17961077/55323760-46177400-5480-11e9-9402-381bc96c1c92.PNG)

**Comment by weinand** [comment]
The big dot indicates that a file is dirty (hasn't been saved):

![2019-04-01_14-51-11](https://user-images.githubusercontent.com/1898161/55328894-b37dd180-548d-11e9-85bb-24385ce967d4.png)
