### ISSUE TITLE
GitLens conflicts with the merge conflict code lens

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#71532]
Originally reported here: https://github.com/eamodio/vscode-gitlens/issues/319

Basically the issue as reported is that when GitLens adds its git code lens, and there are merge conflicts, that the merge conflicts code lens doesn't show up. This issue has been reported numerous times on the GitLens repo, and it seems to be only affecting vscode on linux.

I have only seen this once (ever), but I'm also not using linux. But in theory, GitLens shouldn't be able to conflict with any other code lens provider.

Any ideas?

**Comment by joaomoreno** [comment]
@alexandrudima Any thoughts on editor view zones overriding others?

**Comment by alexandrudima** [comment]
The editor allows for multiple view zones after the same line number and they will "accumulate".

@jrieken What do we do in case of multiple code lens providers for a file?

**Comment by jrieken** [comment]
> @jrieken What do we do in case of multiple code lens providers for a file?

They are merged and concatenated, e.g `Lens 1 | Lens 2`.

**Comment by jrieken** [comment]
> Basically the issue as reported is that when GitLens adds its git code lens, and there are merge conflicts, that the merge conflicts code lens doesn't show up

In a sense of they get removed when gitlens kicks in?

**Comment by jrieken** [comment]
I can reproduce with this snippet

```ts
    vscode.languages.registerCodeLensProvider('*', {
        provideCodeLenses(document) {
            if (document.lineAt(0).text === 'Lens') {
                return [new vscode.CodeLens(
                    document.lineAt(0).range,
                    { command: 'extension.sayHello', title: 'This is a long lens from another provider ' }
                )];
            }
            return undefined;
        }
    })

    vscode.languages.registerCodeLensProvider('*', {
        provideCodeLenses(document) {
            if (document.lineAt(0).text === 'Lens') {
                return [new vscode.CodeLens(
                    document.lineAt(0).range,
                    // { command: 'extension.sayHello', title: 'This is a long lens from another provider ' }
                )];
            }
            return undefined;
        },
        resolveCodeLens() {
            throw new Error('lens fail');
        }
    })
```
