### ISSUE TITLE
Cannot write code on new line

### ISSUE THREAD

**Issue by nansol** [Microsoft/vscode#71530]
- VSCode Version:1.32.3
- OS Version: Win 7

Steps to Reproduce:

1.When I hit enter, the cursor move to new line, but right away returns back on previous line, 
It is impossible to start write a code on new line

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
Does this happen if you disable all extensions?

**Comment by nansol** [comment]
no :-), I have to find out which extension is doing that :-), thank you for help
