### ISSUE TITLE
Failed to delete folders in the WIN7 system.

### ISSUE THREAD

**Issue by forijk** [Microsoft/vscode#71537]
- VSCode Version: 1.32.3
- OS Version: win7 x64

Steps to Reproduce:

When deleting the folder in the project, it succeeded, but when vscode was refreshed, the folder came out again, and the files in it were still there. Git also has no record of these file changes.

**Comment by bpasero** [comment]
@forijk how did you delete?

**Comment by forijk** [comment]
@bpasero After selecting the folder, right-click to delete it, but there is no such problem in the MAC system. What's the matter? ...

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
