### ISSUE TITLE
Typescript 3.1.1 (from workspace) fails but 3.4.0-rc works

### ISSUE THREAD

**Issue by philjones88** [Microsoft/vscode#71536]
- VSCode Version: Version 1.33.0-insider (1.33.0-insider) 4039ea871879ef8f654f27df5c32d209104b3a44
- OS Version: MacOS 10.14.4

Steps to Reproduce:

1. Open typescript file
2. Set to workspace ts version which is 3.1.1

See this stuck constantly spinning:
![image](https://user-images.githubusercontent.com/677167/55318797-84eeff00-546b-11e9-89a8-4e1117821462.png)

```
[Info  - 10:38:22 AM] Using tsserver from: /work/vq/cypress-testing/node_modules/typescript/lib
[Info  - 10:38:22 AM] Forking TSServer
[Info  - 10:38:22 AM] Started TSServer
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Better 3.1.1 and 3.4 fixes a number of bugs were fixed in TypeScript that could be causing this. Please consider using a newer TS version in your workspace
