### ISSUE TITLE
Opening a terminal is blank

### ISSUE THREAD

**Issue by dylanvdmerwe** [Microsoft/vscode#71542]
Issue Type: <b>Bug</b>

When opening a terminal through VS Code initially the terminal is completely blank. It does work however, but first render looks incorrect.

On first opening the terminal:
![image](https://user-images.githubusercontent.com/2852839/55324753-4ebd7980-5483-11e9-9122-7402b0318e9e.png)

Pressing enter a few times:
![image](https://user-images.githubusercontent.com/2852839/55324776-5ed55900-5483-11e9-99ed-b95049993496.png)

VS Code version: Code - Insiders 1.33.0-insider (4039ea871879ef8f654f27df5c32d209104b3a44, 2019-03-29T10:53:36.965Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (5.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
