### ISSUE TITLE
Settings for editor panes extending

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#71546]
Currently, {minimized panes} extending goes in all directions even if affected panes are not maximized .
![piZsugZ1ZvisualStudioCode](https://user-images.githubusercontent.com/13949704/55333491-1d06db80-54a0-11e9-977a-4dbbed623d39.PNG)
("2" in the picture should not be minimized but currently are)

its inconvenient and should have a setting or/and be disabled by default.

Also, is there a way to disable the extending at all?

**Comment by joaomoreno** [comment]
@bpasero The current grid minimizes all views in order to make space for the newly maximized view. I guess the user only wants to minimize views which are in the same splitview as the newly maximized view (in the previous example that would only be the editor view on the right).

**Comment by Ilias48rus** [comment]
@bpasero i was meaning that it should minimize only previously maximized this way windows, but thanks to pointing me at the description issue

**Comment by irvnriir** [comment]
![](https://lh3.googleusercontent.com/hRpeojUsfnJqXUSmsnFJ1504roynakc7fQUak7UAZQUPluGiOQrNUUbERXQr2dqWzNxBptU5gnb4KjemmNZHIP1xhI0gQI5nxj5Swag3whgZu3-hLLRhYH-iwaJExWrUMb9upYkk_zvm64TAsEwG6S2r_NO-u1aMmAuH0uE6pL35zlJ2Xtdq8RQMIlPWmot8jApL833kbz28eU6gTbiheXI6VXFh3ECZwU9b8Dtv-ShVV4vF2bKS_mUVw8u001r9OuKva3Y9kWzme-G_Ys_XnRcJGRUg862Q9LRvov6GrMUfMyKlfa-QlVWnjulSh9z8qhX97MAWoUUkWYadOHIgSaDWa_xvIKt1YnAnH9ofxEvajGpdeGnojKzdQzHOeKNRBJjvQ7GQpl_7k3HOb1KQREuaFaOgCEC8RAFpmVYVZes9JzrrxQWBDeoTj9xP-L9b0kwr49yIu1xsV2__Ou0yPhwMHIm6Aqm5heLS8akblU685Kmg9ZbcDoS5Bf3ybaZqCNgcRczGh8CedQko--2E-9oOOdti7OM-XTl4QhIhpK6BPCmA1DAsbV8h8e0PXanq2sWCAPllRYFtiRYdsrIFQLiRfVXU0k8lDoTUlwqnwJixLVPBZyfBmrgSnEp_Er95eEzP1XNu8Ag7HCmKyTXLCacxZzqcpKoJZBvIEK77LXqBXvy3-a5vaw=w1126-h608-no)

please reopen it .
