### ISSUE TITLE
Modifying and saving this file did not pin it

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7154]
Version 1.2.0-alpha
Commit 81ab7e3332cca6610078063dc830f71ba3986d4b
Date 2016-05-31T18:40:39.797Z
Ubuntu 16.04

Not sure what I did in particular but it is not in this state:

![image](https://cloud.githubusercontent.com/assets/2193314/15758270/a7c26b74-28be-11e6-82a0-2733c128cc35.png)

**Comment by bpasero** [comment]
@Tyriar really need some steps to reproduce here to find out. What is odd is that the file is dirty and even that is not showing in the editor. 

I am moving this back to you to try out more things: Did you maybe have the same file open in multiple groups and stuff like that?

**Comment by Tyriar** [comment]
@bpasero if I manage to reproduce I'll ping this.

**Comment by bpasero** [comment]
@Tyriar I just ran into this too, super weird. Gotta find steps to reproduce...

**Comment by bpasero** [comment]
Ok I got it, needs some serious fixing.

**Comment by bpasero** [comment]
This reproduced for me quite easily like this: open file, close file, use quick open to pick the file again from history and start typing: no pinning or dirty indication at all.
