### ISSUE TITLE
the console dispaly is weird

### ISSUE THREAD

**Issue by zkangHUST** [Microsoft/vscode#71540]
Issue Type: <b>Bug</b>

The console interface does not display properly in big screen
![TIM截图20190401191142](https://user-images.githubusercontent.com/16082281/55324229-010d3500-54b4-11e9-9909-94607da680c1.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (12.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.32.4

</details>

**Comment by zkangHUST** [comment]
After press enter a few times , the terminal turns  back to normal. 
![TIM截图20190401194408](https://user-images.githubusercontent.com/16082281/55325062-8abe0200-54b6-11e9-8b7d-9e7b07573d07.png)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by zkangHUST** [comment]
Thanks a lot! I update Windows 10 today , and it turns back to normal.
I really love vscode,  thank you for your hard work !
