### ISSUE TITLE
Support more than just quick fixes (for ex. "Open docs for error_code") in Problems view context menu

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#71541]
Right-clicking in the Problems view shows a filtered list of QuickFix code actions. I'd really like to add an entry in there to open the help docs for more information on the error - however it doesn't seem right to mark it as a QuickFix:

![Screenshot 2019-04-01 at 12 37 10 pm](https://user-images.githubusercontent.com/1078012/55324742-e79bc700-547a-11e9-9a80-a182641c2889.png)
![Screenshot 2019-04-01 at 12 37 16 pm](https://user-images.githubusercontent.com/1078012/55324743-e79bc700-547a-11e9-9402-03e609589473.png)

It would be great if there was some way to either supply a URL for more help about an error, or at least another CodeAction kind that can be shown in the problems view.

**Comment by sandy081** [comment]
@mjbvz How can I get other code actions which are relevant to the given diagnostic? Right now I only get quick fixes.

**Comment by mjbvz** [comment]
@sandy081 When calling `getCodeActions` [here](https://github.com/microsoft/vscode/blob/b71932d4b725b4a55124f3fc0bc85487b8a9c8ba/src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts#L564), remove the `filter`. However keep in mind that the returned result may also include refactorings and other actions that probably should not show up in the problems context menu

@DanTup For those documentation code actions, could mark them with a code action kind of `CodeActionKind.QuickFix.append('documentation')` or similar? The action is related to quick fixes so abusing the code action kind this way may not be too terrible. Once you add that kind, the actions should should show up in the problems menu

**Comment by DanTup** [comment]
I certainly could, but it feels a bit weird. For ex. if you had a keybind to show the menu filtered to "all quick fixes" (I think you can do that?) it'd be weird for this to show up there. Maybe a `CodeAction.Help` or something would be appropriate?

**Comment by mjbvz** [comment]
Or, even better, put the help text in the error message itself. @sandy081 Is that something we support?

**Comment by DanTup** [comment]
We do have extra help text in the errors (in the screenshot at the top you can see some errors have a second line with more descriptive text), but we wanted to be able to link to online docs that are more detailed than we'd want to cram into the problems list.

**Comment by sandy081** [comment]
There are discussions to add help link to diagnostics - https://github.com/Microsoft/vscode/issues/11847

So options here are to change the code action kind to quick fix or follow up on other item.

**Comment by DanTup** [comment]
Making a help URL a first-class citizen sounds good to me - it opens the door to other nice functionality (for ex. a keybind that opens help for the current error). I still think being able to show non-fix items in this context menu is worthwhile, but I don't have a specific need for it if diagnostics could have URLs.

That said, it's not clear what's going on in that issue - using RelatedInformation sounds wonky to me, and I don't think supporting formatted content in errors solves the problem (I don't want to clutter the error list even more with visible links, the context menu is an idea place for it).

**Comment by sandy081** [comment]
@DanTup Thanks for your feedback. Closing this in favor of #11847
