### ISSUE TITLE
Handle source map/original file content diffs

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#71548]
Often, when debugging js apps written in ts, I want to change the (ts) source code while debugging. This can be as subtle as adding single line comments, formatting the entire file or even changing statements or whole function bodies.

Then however, the js to ts source map is not valid anymore.
This is especially problematic when adding a single empty line at the top of the file - you have to restart the debugee so that nodejs catches up the new sourcemap.

It would be great if VSCode could create a new source map from the old ts source file (if the old content is embedded in the source map) to the new content (= the current editors content) and combine it with the existing source map. Code that could not be matched could be grayed out (e.g. changed statements and so on). Matching could be done on AST level.

Some remapping is actually done by vs code when adding lines before currently executed line. This remapping is however not persistent:
![demo](https://user-images.githubusercontent.com/2931520/55335768-03fc2b80-549c-11e9-831e-84f5e47fa0c8.gif)

**Comment by weinand** [comment]
VS Code does not want to know anything about source maps.

But what you are asking for can be easily achieved by running TS in watch mode (which creates new source maps as a side effect) and using "nodemon" to restart the program whenever the generated JS changes.

**Comment by hediet** [comment]
In my scenario I don't want the program to restart to adopt the new source maps but rather want the editor to respect source changes after the source map has been created.

Right now, a source map might store the path to the source file (lets call it `sm.sourceFilePath?: string`) and also might store its content at compile time (lets call it `sm.sourceFileContent?: string`).

If `sm.sourceFilePath` is provided, VSCode just ignores `sm.sourceFileContent` (or rather `vscode-node-debug`, but I assume that VSCode just does not send a `SourceRequest` to the debug adapter to obtain the source (as it was when being compiled) if the `Source` object has a `path` set).
Instead, VSCode assumes that `sm.sourceFileContent === undefined || getEditorBufferOrFileContent(sm.sourceFilePath) === sm.sourceFileContent` with `getEditorBufferOrFileContent(path)` being the text content of the editor if `path` is opened or the file content.

I find this suboptimal in otherwise quite optimal debugging environment.

It would be great if VSCode diffs `sm.sourceFileContent` with `getEditorBufferOrFileContent(sm.sourceFilePath)` and uses that diff to compute the actual position of the active line. All new lines could be highlighted to signal the user that he is debugging against newer source.
Then VSCode still does not know anything about source maps.

This would even be applicable to other languages like rust, where recompiling is often a very time consuming task.

**Comment by weinand** [comment]
What exactly is the purpose of the mapping in your case?
If node.js is not restarted, it will not pickup JS changes and will continue to execute old JS. Mapping old JS to new TS will be confusing because the TS source might already be deleted and you will step through non-existing code. How is this helpful?

**Comment by hediet** [comment]
> Mapping old JS to new TS will be confusing because the TS source might already be deleted and you will step through non-existing code.

This is more helpful than just pretending the file has not changed. Stepping through nothing, i.e. having no active line marked, (if statements were deleted) seems to be way less confusing to me than stepping through completely different code (as seen in the gif above - it will step through white lines).

It also wouldn't step through new existing code as it does now - it will only step through the code that existed when the sourcemaps (and the js files) were created.
If the entire source file was deleted (`sm.sourceFilePath`), VS Code already uses `sm.sourceFileContent` for debugging as expected.

Another very useful case that is covered with a solution for this problem is, when you want to debug minified js code without access to the unminified source. If you format the minified code in VS Code while debugging, you have to save the changes and restart the debugee (if you have write access to the minified code, if you haven't, you are out of luck). In this case, a sourcemap is not even involved.
