### ISSUE TITLE
how to block one file("go to definition")

### ISSUE THREAD

**Issue by bowenee** [Microsoft/vscode#71544]
Issue Type: <b>Feature Request</b>

when click "go to definition", vs code shows a popup(two options for choice), two files(c source file) have one same function name, how to exclude one of them?

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0
<img width="803" alt="image" src="https://user-images.githubusercontent.com/5562854/55327574-f0ad8800-54bc-11e9-8d38-0d91a2b28009.png">

**Comment by weinand** [comment]
Please ask this the authors of the C extension you are using.
