### ISSUE TITLE
Please don't file duplicate issues on extension repos

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#71545]
I get spammed with issue reports coming from the VS Code issue reporter.
When filing an issue on GitHub, GitHub will show an issue template and suggest potential duplicate issues as you type the title.
The VS Code issue reporter circumvents these mechanisms.

![image](https://user-images.githubusercontent.com/10532611/55328139-f8a10400-548b-11e9-8586-0f14f909ecc4.png)

It is a known issue that this extension uses a lot of CPU to do its first index of the project. After that indexing is done, the CPU usage stops. 
As a maintainer I have no way to intercept the issue filing process (as I do on GitHub) and the user has no way to know that it is a known issue.
Everyone is welcome to open a PR to optimize the indexing, filing more and more issues doesn't change anything, it is just really dreading to the maintainer and makes me want to completely unsubscribe the repo, which surely is not in the interest of the user nor the intention of this feature.

**Comment by RMacfarlane** [comment]
Hey @felixfbecker, sorry for the issue spam. The issue reporter should query for similar issues against what's listed for `bugs.url` or `repository.url` if that's not present
![Screen Shot 2019-04-01 at 10 57 43 AM](https://user-images.githubusercontent.com/3672607/55348989-5b36d780-546d-11e9-8f0f-0ca96e8e3ba9.png)

@jrieken These issues look to be coming from the `ReportExtensionIssueAction` - perhaps we could either add a warning dialog when clicking the report button if there are similar issues, or include some additional warning text in the issue preview?
