### ISSUE TITLE
stutters

### ISSUE THREAD

**Issue by happypd** [Microsoft/vscode#71549]
Issue Type: <b>Performance Issue</b>

when boot and open a file , very very stutters .

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|2.92GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    44	 15532	code main
    0	    28	  3648	   shared-process
    0	    32	  6648	   gpu-process
    0	   111	  9604	   window (● README.md - 无标题 (工作区) - Visual Studio Code [管理员])
    0	    75	  8760	     extensionHost
    0	    43	 16968	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=8760
    0	     5	 11964	     electron-crash-reporter
    0	    13	 12360	     watcherService
    1	    54	 17684	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● README.md - 无标题 (工作区) - Visual Studio Code [管理员])
|    Folder (audioWebApp): 2 files
|      File types: html(1) md(1)
|      Conf files:
|    Folder (test): 4 files
|      File types: json(2) js(1)
|      Conf files: package.json(1)
|    Folder (ctextAPI): 57 files
|      File types: json(13) js(12) wxss(12) wxml(10) png(8) md(2)
|      Conf files: package.json(1)
|    Folder (blog): 265 files
|      File types: ejs(58) styl(30) yml(28) js(28) md(19) png(16) html(14)
|                  css(14) gif(12) json(10)
|      Conf files: package.json(4) grunt.js(2) launch.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
prettier-vscode|esb|1.8.1
tortoise-svn|fan|0.1.1
beautify|Hoo|1.4.11
svn-scm|joh|1.47.12
vscode-language-pack-zh-hans|MS-|1.30.2
rust|rus|0.5.4
markdown-all-in-one|yzh|2.0.1

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
