### ISSUE TITLE
prepare-commit-msg hook code is populated in SCM commit message input

### ISSUE THREAD

**Issue by mliq** [microsoft/vscode#71550]
- Still happens in Insiders Build: ✅ 

- VSCode Version: 1.32.3
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Have a custom `prepare-commit-msg` git hook located either in your project at `./.git/hooks` OR in your global git hooks directory - **_Example provided below_**
2. Open any vscode project folder
3. Select menu View -> SCM
4. Observe that the full code (minus comments) of the `prepare-commit-msg` is inserted in the git commit entry input area. 
5. Observe that this code will be repopulated after any commit or when VSCode is closed and opened again, or when a new project is opened.

Does this issue occur when all extensions are disabled?: Yes

### Additional Info:

* I have used this hook for several months and it worked correctly until the most recent VSCode update (1.32.3). By "correctly" I mean that the VSCode commit message window was empty and functioned just as if I had no git hook, but the resulting commit message did reflect the results of the hook. 

* Here is the `prepare-commit-msg` hook I use, which simply adds `<current-branch-name> - ` to the front of each commit where `<current-branch-name>` is the actual name of the current branch.

```sh
#!/bin/bash

# You can copy this to a repo as `.git/hooks/prepare-commit-msg`, or
# Add to global .gitconfig and global hooks folder with git config --global core.hooksPath ./hooks
# also had to make executable `chmod u+x ./hooks/prepare-commit-msg`

# This way you can customize which branches should be skipped when
# prepending commit message.
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop test)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e "1s/^/$BRANCH_NAME - /" $1
fi
```

Screenshot:
<img width="469" alt="Screen Shot 2019-04-01 at 10 19 40 AM" src="https://user-images.githubusercontent.com/7573605/55339134-b49c0800-5467-11e9-8a4d-05a76410148f.png">

**Comment by mliq** [comment]
There is a new bug where `CMD+A` no longer selects all text in the commit window, making the workaround to this bug much more egregious 😞

**Comment by joaomoreno** [comment]
@mliq That might happen due to a keybinding you have defined... can you double check?

**Comment by mliq** [comment]
@joaomoreno I did check that, can't see what the issue is but maybe you can? (Same keybindings I've had for about a year and the problem only started now)
<img width="1274" alt="Screen Shot 2019-06-05 at 9 47 58 PM" src="https://user-images.githubusercontent.com/7573605/59003470-ba9dc480-87db-11e9-81be-3de160e0c5d0.png">

**Comment by joaomoreno** [comment]
Maybe let's try to repro in a new user data dir:

```
code --user-data-dir

**Comment by mliq** [comment]
Solved: I had a `~/.stCommitMsg` file referenced in my global git config as:

```
[commit]
	template = /Users/mliq/.stCommitMsg
```

I suspect that SourceTree created this file by taking the code from my `prepare-commit-msg` hook and inserting it as a text template in my git config 😠
