### ISSUE TITLE
Linux "desktop entries" (.desktop) aren't colored very well by ini language

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7155]
Notice:

- Sections not emphasized `[Desktop Entry]`
- `;` start comments in ini files, not in desktop entries

![image](https://cloud.githubusercontent.com/assets/2193314/15758555/fc3df24e-28bf-11e6-92ea-c7619ec5a15d.png)

**Comment by aeschli** [comment]
Do you suggest to remove .desktop from the file extensions for ini?

**Comment by Tyriar** [comment]
It's probably preferable to lose the property highlighting over incorrectly indicating comments yeah.

What's the protocol on adding niche language grammars like this? No one will bother download an extension for .desktop files but it would be handy to have valid highlighting.

**Comment by aeschli** [comment]
It has to be an extension, I don't see us author and maintain support for such rarely used file types.
We should make it easy though to find and install such an extension. E.g when opening a .desktop file we should propose to install support for it.
