### ISSUE TITLE
tsserver.js hogging my CPU

### ISSUE THREAD

**Issue by Risto-Mcintosh** [Microsoft/vscode#71552]
Im having the same issues posted here [#71286 ](https://github.com/Microsoft/vscode/issues/71286)

electron_node tsserver.js has a high CPU usage

I've already tried the following :
- followed the Performance issue guide
- open up the project in the Insiders build (with no extensions)

**Comment by mjbvz** [comment]
A few initial questions:

- When this happens, does intellisense still work in javascript/typescript files?
- Does something specific trigger it?
- Does this happen for all projects or only one in particular?

**Comment by Risto-Mcintosh** [comment]
It starts as soon as I open the project. intellisense does not work

The process starts to rise as soon as I open VScode, so I can't tell what exactly is trigging it.

It raises a bit in my other projects, but not enough to stop intellisense

**Comment by Risto-Mcintosh** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/22851415/55418720-d4e7c780-5538-11e9-8254-93f5653f05e9.png)

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

 If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Risto-Mcintosh** [comment]
[tsserver.log](https://github.com/Microsoft/vscode/files/3036770/tsserver.log)

**Comment by Risto-Mcintosh** [comment]
Like that or should I copy and paste the contents?

**Comment by mjbvz** [comment]
Thanks. From the logs it looks like you are not on the latest insiders build (or are using an older TS version in your workspace) Please test on insiders using TS 3.4.1.

Also test with extensions disabled to see if one of them is causing. I see that tslint and intellicode are being loaded

**Comment by Risto-Mcintosh** [comment]
I've already done those things (see first post). I've never used TS before how do I check/update the version Vscode is using?

**Comment by mjbvz** [comment]
With a js file open, run `select Typescript version` from the command palette 

Share the logs from insiders with extensions disabled.

**Comment by Risto-Mcintosh** [comment]
[tsserver.log](https://github.com/Microsoft/vscode/files/3040965/tsserver.log)

**Comment by Risto-Mcintosh** [comment]
CPU %	Memory (MB)	pid	Name
0	80	31752	code-insiders main
0	192	22592	     gpu-process
0	199	23452	     window (App.js - flashcards - Visual Studio Code - Insiders)
0	68	11640	         extensionHost
0	892	15588	             electron_node tsserver.js 
0	55	4164	                 electron_node typingsInstaller.js typesMap.js 
0	35	25972	             "C:\Users\risto\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\risto\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=11640
0	10	17244	         watcherService 
0	9	5360	             console-window-host (Windows internal process)
0	6	21416	         winpty-process
0	9	15068	             console-window-host (Windows internal process)
0	62	31008	             C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
0	12	32528	         electron-crash-reporter
0	63	26816	     shared-process
0	64	33468	     window (Process Explorer)

**Comment by mjbvz** [comment]
Thanks. Nothing obvious in the logs. Your process explorer output shows 0 cpu usage which seems odd. Can you share the output from windows process explorer instead for the code-insiders process

**Comment by Risto-Mcintosh** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/22851415/55518133-773aa480-5638-11e9-881d-954fab3f6185.png)

**Comment by Risto-Mcintosh** [comment]
is that what you mean?

**Comment by mjbvz** [comment]
Yes, but those are also 0%. How did you determine it is hogging your cpu?

**Comment by Risto-Mcintosh** [comment]
LOL! This whole time I meant memory 😆 that's embarrassing..

**Comment by Risto-Mcintosh** [comment]
CPU %	Memory (MB)	pid	Name
0	78	14652	code-insiders main
0	190	1908	     window (● Navigation.js - flashcards - Visual Studio Code - Insiders)
0	11	8960	         watcherService 
0	9	6412	             console-window-host (Windows internal process)
0	61	13344	         extensionHost
**26	286	12372	             electron_node tsserver.js** 
0	44	7324	                 electron_node typingsInstaller.js typesMap.js 
0	6	14840	         winpty-process
0	5	3192	             "C:\Program Files\Git\bin\bash.exe"
0	9	11580	                 "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
0	8	13688	             console-window-host (Windows internal process)
0	169	12076	     gpu-process
0	64	13580	     shared-process
0	61	13884	     window (Process Explorer)
0	8	14772	     C:\Users\risto\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-5fb8764a0b2cfd1cedd522f3b33eda7195da3e36.exe /verysilent /update="C:\Users\risto\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-5fb8764a0b2cfd1cedd522f3b33eda7195da3e36.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
0	31	15148	         "C:\Users\risto\AppData\Local\Temp\is-S44GU.tmp\CodeSetup-insider-5fb8764a0b2cfd1cedd522f3b33eda7195da3e36.tmp" /SL5="$50402,49407040,159744,C:\Users\risto\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-5fb8764a0b2cfd1cedd522f3b33eda7195da3e36.exe" /verysilent /update="C:\Users\risto\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-5fb8764a0b2cfd1cedd522f3b33eda7195da3e36.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon

**Comment by Risto-Mcintosh** [comment]
nows it definitely using too much CPU.  

Intellsense not even working now
