### ISSUE TITLE
Ability to change sql dialect from MSSQL -> (anything else) really

### ISSUE THREAD

**Issue by mikepc** [Microsoft/vscode#71554]
https://marketplace.visualstudio.com/items?itemName=jakebathman.mysql-syntax#review-details

I would like to be able to change from the default MSSQL intellisense to MySQL syntax highlighting, as they have different syntax.

Even though this should be on a file by file basis, it would at least be a step forward to change the rendering to use a different database language at the project level

**Comment by weinand** [comment]
Are you using an sql extension?
