### ISSUE TITLE
Config issues: Tab space size not applying when Workspace setting uses default value

### ISSUE THREAD

**Issue by PabloNeirotti** [Microsoft/vscode#71555]
Issue Type: <b>Bug</b>

The default value of Tab space is 4.

Now, I like to use 3 typically, so my User setting is 3.

I am working on a project where we are using 4 and we rely on spaces instead of tabs, so I've set the Workspace settings to 4 spaces so the indentation remains the same.

When creating a new file on this workspace, the file will use my User setting (3 spaces), probably due to the fact my Worskpace setting is set to the default. If I set my Workspace setting to 5, for instance, THEN a new file will use the Workspace setting instead of my User setting.

It'd seem to be something related with the Workspace setting being at default value so it doesn't overwrite the User setting.

Cheers!

VS Code version: Code 1.32.0 (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T18:52:50.880Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.19.3
compulim-vscode-closetag|Com|1.2.0
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
godot-tools|gee|0.3.7
twig-language|mbl|0.7.1
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vsliveshare|ms-|0.3.1403
ruby|reb|0.22.3

</details>

**Comment by mjbvz** [comment]
Which language is this for?
