### ISSUE TITLE
`vscode.languages.getDiagnostics` do not return `tags` for faded out errors

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71556]
Version: 1.33.0-insider
Commit: 0ac111466ec925fd5ca180ab9893f51531e419b2
Date: 2019-04-01T15:47:22.304Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Related: https://github.com/Microsoft/vscode/issues/51104

Repro:

- Clone this repo (`unused-bug` branch) https://github.com/octref/hello-code/tree/unused-bug
- `yarn install && yarn watch`
- F5 to debug
- Open a JS file with following content:

  ```js
  const foo = 5
  
  export const bar = 10
  ```
- Run command `Hello World`
- Returned diagnostics do not include `tags`. Heres' the output

```json
[
  {
    "severity": "Warning",
    "message": "'foo' is declared but its value is never read.",
    "range": [
      {
        "line": 0,
        "character": 6
      },
      {
        "line": 0,
        "character": 9
      }
    ],
    "source": "ts",
    "code": 6133
  }
]
```

This makes it impossible for me to write end-to-end test for unused variables: https://travis-ci.org/vuejs/vetur/jobs/514281703#L572-L575.

Also I'm curious — why in the inspector I get `serverity: 1` but in the `JSON.stringify` conversion it becomes `Warning`?

![image](https://user-images.githubusercontent.com/4033249/55350522-2af13800-5471-11e9-9744-f75160d6519e.png)

fyi @jrieken @dbaeumer

**Comment by jrieken** [comment]
> Returned diagnostics do not include tags. Heres' the output

That only means it's not part of being json-stringified. We have never made promises about that. Why aren't you using the object as defined by its API?
