### ISSUE TITLE
Extended VSCode use enables dead keys

### ISSUE THREAD

**Issue by cjfloresalonso** [Microsoft/vscode#71560]
Issue Type: <b>Bug</b>

I'm not entirely sure how to reproduce... 

I find that after I use VSCode for a while, occasionally, dead keys permanently turns on (by permenant, I mean no need to use AltGr; they're just on). That is, the keys `` [`'"^~] `` wait for a second key to be pressed to do their thing. If, for example, and a is pressed, it does an à. This behaviour is not restricted to VSCode, but system wide.

Expected behaviour: Seperate characters in all cases, no waiting for next key press.

Actual behaviour: `` [`'"^~] `` then vowels (possibly other keys) combines into a single character, and key presses of `` [`'"^~] `` wait for another key to do anything.

Changing keyboard settings in Windows 10 settings does not fix this. Only system language is English (Australia), only keyboard layout is US International. System reboots do not revert actual behaviour to expected.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.91GB (5.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
chat|kar|0.12.0
python|ms-|2019.3.6215
vsliveshare|ms-|0.3.1403
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.10

</details>

**Comment by cjfloresalonso** [comment]
Please, let me know how I can help you get more information for the bug report.

**Comment by cjfloresalonso** [comment]
Not going to lie, I actually don't know exactly when this bug kicks in, nor how to fix it and revert to expected behaviour. Any help would be appreciated.

**Comment by alexandrudima** [comment]
@cjfloresalonso Are you running Windows inside a VM or on bare metal ?

**Comment by cjfloresalonso** [comment]
Bare metal.

**Comment by alexandrudima** [comment]
@cjfloresalonso 

> Expected behaviour: Seperate characters in all cases, no waiting for next key press.
> Only system language is English (Australia), only keyboard layout is US International.

This is how US International works. For example, when pressing `` ` ``, on the US international there will be "hidden state" and the keyboard subsystem of Windows will wait for your next keypress. This is tremendously useful in countries in Europe where there are lots of accents...

I believe you actually don't want to use US International. You can add another keyboard layout US QWERTY (Standard) and that will work in the way you desire. You can then remove US International since you obviously don't want to use that.

**Comment by cjfloresalonso** [comment]
It happened again... yet the keyboard is US (QWERTY).
