### ISSUE TITLE
Theme color is not solid and changes depending on the text and cursor location

### ISSUE THREAD

**Issue by NatalieGates** [Microsoft/vscode#71566]
I notice while using any color theme, even default, I will get slightly faded rectangles of different colors (same shade just slightly different). This changes frequently based upon where my text is located and where the cursor is located and is a bit distracting. I've tested on several machines and I'm sure any user of VSCode can easily replicate. Just open a new file and start typing...

I hope this can be easily fixed as I really enjoy VSC.

Here is a screenshot

![ThemeDiscrepancy](https://user-images.githubusercontent.com/47909481/55361382-15960100-54a5-11e9-9885-dc14fac6a641.png)

**Comment by mjbvz** [comment]
Which VS Code version and operating system are you using?

/needsMoreInfo

**Comment by NatalieGates** [comment]
> Which VS Code version and operating system are you using?

Reproducible on any operating system (mac, windows, linux)
VSC Version: 1.32.3

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by NatalieGates** [comment]
Oh my, this fixed it! I tried on macOS and Linux and they both have clean and solid background colors. My issue is resolved in the exploration version.

When will the stable release receive this newer version of the UI framework? I can be patient, this will be an amazing update once released - at least for me.
