### ISSUE TITLE
Integrated Terminal has different colour after reinstall/settings reset

### ISSUE THREAD

**Issue by Monbrey** [microsoft/vscode#71568]
Issue Type: <b>Bug</b>

![vsc terminal](https://user-images.githubusercontent.com/5294381/55361987-76185300-5524-11e9-831b-d0543600b119.PNG)

As shown in the screenshot, after uninstalling VSC and deleting settings folders, upon reinstall the Integrated Terminal appears to have this transparent overlay applied to it. This effect is seen on all default themes, and regardless of which Terminal is being used (cmd/powershell/git bash).

I was unable to find a `workbench.colorCustomizations` setting which would control this.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (8.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
prettier-vscode|esb|1.8.1
angular-essentials|joh|0.6.0
Angular2|joh|7.0.1
vscode-typescript-tslint-plugin|ms-|1.0.0
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.7.0

</details>

**Comment by Monbrey** [comment]
Using the Developer Tools I was able to identify which elements are causing this overlay effect

![image](https://user-images.githubusercontent.com/5294381/55698758-c868e080-5a0a-11e9-9ca4-90ed3d283382.png)

xterm-selection-layer and xterm-cursor-layer both add a semi-transparent overlay to the terminal, despite neither of these having a CSS background defined if I look at the element.

**Comment by Tyriar** [comment]
@Monbrey can you share your settings.json file?

**Comment by Tyriar** [comment]
I suspect there's something weird going on with this line https://github.com/xtermjs/xterm.js/blob/7aaa1ad0bbb7c7b5dea775f1a432c1b042c44a45/src/renderer/BaseRenderLayer.ts#L198

**Comment by Tyriar** [comment]
Having trouble reproducing, if anyone can repro please provide:

- Your settings.json file
- Your Windows 10 build number (or if you're not on Windows 10)
- Any other info that you think might help

**Comment by Monbrey** [comment]
[settings.zip](https://github.com/Microsoft/vscode/files/3133717/settings.zip)

Settings attached (zipped for Github comment support)
I'm on Windows 10 Pro 1803, build 17134.706

After attached the settings file, I've made the change references in #69309 :
`"terminal.integrated.rendererType": "dom"`

This also fixes the issue for me too

**Comment by mrmckeb** [comment]
I've also started to see this on MacOS and I'm not sure why.

But I tried changing themes which didn't help, then killed VSCode and reopened and it seems OK now.

I am not sure if it was a combination of the above that fixed it, or something else, but it appeared around the time of the last update.

**Comment by Tyriar** [comment]
This is actually a bug in Electron

/duplicate https://github.com/microsoft/vscode/issues/76656
