### ISSUE TITLE
Error when restoring a markdown preview for a file that has been deleted

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#71570]
Issue Type: <b>Bug</b>

**repo**
1. Create a file `x.md`.
1. Open markdown preview for the file
1. Now close  the `x.md` editor and rename the file to `y.md` (without opening it again in the editor)
1. Reload window and go to the restored markdown preview

**Bug**
Non-specific error shown in the editor

VS Code version: Code - Insiders 1.33.0-insider (0ac111466ec925fd5ca180ab9893f51531e419b2, 2019-04-01T15:47:22.304Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|-psn_0_15584988|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by skprabhanjan** [comment]
@mjbvz , Can I take a look at this ?
Any code pointers to start will be helpful :)

**Comment by mjbvz** [comment]
Sure: 

* Here's where we start restoring the markdown preview: https://github.com/microsoft/vscode/blob/9fb1a067b683a51e568126c83787a49ceaac04f6/extensions/markdown-language-features/src/features/preview.ts#L80

* Here's where we try loading the text document for a preview: https://github.com/microsoft/vscode/blob/9fb1a067b683a51e568126c83787a49ceaac04f6/extensions/markdown-language-features/src/features/preview.ts#L384

You probably want to add a `try/catch` around around when the preview fails to open. If the open fails, we should update the preview to show some basic html that explains what went wrong and what document failed to load

Here's another related case we should handle for this bug:

* Open markdown file
* Open preview
* Delete markdown file
* Go back to preview

We should probably show an error message for this case too

**Comment by prithvihv** [comment]
hey @mjbvz ! im new here . I went through the file mentioned above . Could you help with a good example of error handling in the repo ?
Thank you

**Comment by mjbvz** [comment]
Just wrap the call to `openTextDocument` in a `try/catch`

**Comment by skprabhanjan** [comment]
Hey @prithvihv  , Sorry there was already a fix ready for this :) 
You can the follow the PR for getting more info, in case you wanted to learn about the changes :)
