### ISSUE TITLE
vscode-tscancellation- files being created without limit.

### ISSUE THREAD

**Issue by DrPizza** [microsoft/vscode#71577]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. Use VS Code with TypeScript for any amount of time
2. There is no step 2.

Does this issue occur when all extensions are disabled?: Yes/No
Seems to be caused by core TypeScript support.

OK so this has been reported before. #54671, #53423, #61935, #28970, probably more. I got bored of checking. Technically this report is a duplicate, but since the issue keeps getting ignored, here we all are.

Each time the report is closed, and we're told it's by design.

Well I'm telling you it's a terrible design. I mean, quite aside from the issue of using a file to signal that a request has been cancelled (surely there's some better IPC mechanism that could be used for that? A named pipe, an event, a signal, a socket, a domain socket, anything), there's the minor issue of VSCode never actually deleting the files.

@mjbvz seems to be of the [opinion](https://github.com/Microsoft/vscode/issues/53423#issuecomment-401842492) that the files will be cleaned up by the operating system. And that might be true on a Linux machine with files created under /tmp, because /tmp should get clobbered each time you reboot. It might even be true of macOS, I don't know.

What I do know is that it's not true of Windows. %temp% does not get clobbered automatically. A file that's created in %temp% is going to stay there until it's manually removed. It's true that the Disk Cleanup utility can remove some files from %temp% and can be scheduled, but typically nothing is ever removed from %temp% by the operating system. Applications are meant to tidy up after themselves. VSCode is failing to do so.

If VSCode were using raw win32 then the obvious answer would be to open the files with delete-on-close, so they'd get tidied up automatically. But I don't know if Electron apps have the ability to do that.

**Comment by DrPizza** [comment]
OK so... both the TS Server side and the VS Code client side talk as if there were a named pipe being created, using the pipe's existence as the cancellation token... but instead of creating a named pipe they just use a file on the file system. The mere act of creating the file is the signal to cancel.

A named pipe would be nicer, sending the request ID over the pipe to indicate cancellation, but files are what we have so I suppose files are what we should use.

The obvious thing would be for the TS Server side to delete the files once it's seen them, but that doesn't help older TS versions, and I imagine it's possible for the TS Server to never notice the files at all.

It looks as if neither Node nor libuv support opening files with `FILE_FLAG_DELETE_ON_CLOSE`, so any automatic deletion by the operating system is not an option.

So the deletion must happen from VS Code's side. Only it looks to me that there's no particularly reliable way of doing that. We don't know when the server has seen the file, if ever. I think if a new request comes in we can safely delete the file for the old request, and if the server object gets torn down we can remove old files then. Presuming the `Dispose()` method gets reliably called, that'd be the natural place to clear up any old files.

None of these help if VS Code crashes or is terminated. It would be tempting to also remove old files on startup, but then we run into a problem if two instances are running simultaneously.

**Comment by mjbvz** [comment]
[More info about TypeScript cancellation](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#cancellation). This approach cannot be changed easily and is used by TS for a few reasons:

* Simple
* Cross platform
* TS server is single threaded. Using the presence of files lets us check cancellation synchronously

Leaving these empty files around is not a designed behavior, but the bug has such a minimal real world impact that I haven't found it worth prioritizing. I've marked it as help wanted if someone wants to take a look. Here's what I think could be done:

* For normal cases, when the TS extension is de-activated, delete its temp dir. The temp dir is defined [here](https://github.com/microsoft/vscode/blob/9fb1a067b683a51e568126c83787a49ceaac04f6/extensions/typescript-language-features/src/utils/electron.ts#L12). Just delete it in the `deactivate` method of the typescript extension

* To handle cases where VS Code crashes or shuts down unexpectedly, implement something like [logs data cleaner](https://github.com/microsoft/vscode/blob/3d9b0a4b691d2830b4d9d0a4b6fa8762caf1a05e/src/vs/code/electron-browser/sharedProcess/contrib/logsDataCleaner.ts#L12) to clean up old dirs

Let me know if there are any questions about implementing this

**Comment by DrPizza** [comment]
@mjbvz I continue to find it strange that both the code and that documentation consistently call these things "named pipes" when they ain't. If they were named pipes then the issue would disappear, because named pipes don't persist across reboots, and (by default) get torn down when the last handle is closed. There's clearly a divergence between the variable names and documentation, on the one hand, and the actual code on the other.

Beyond that, something along the lines of what you propose sounds reasonable enough, though to confirm: when exiting VS Code, does it promise to perform an orderly shutdown, deactivating extensions and so letting them tidy up (as opposed to syncing buffers to disk and then terminating immediately)?

**Comment by cedric05** [comment]
@DrPizza does windows support named pipes? i don't think it would

**Comment by DrPizza** [comment]
> @DrPizza does windows support named pipes? i don't think it would

It does, yes.
