### ISSUE TITLE
git rebase not works ,even close the vscode-insiders

### ISSUE THREAD

**Issue by manglobe** [Microsoft/vscode#71576]
Yestorday I trigger #52855 again. So I install vscode-insiders again.
Then when I use git rebase , it throw an error:
```bash
hint: Waiting for your editor to close the file... "C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe" --wait: C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe: No such file or directory
error: There was a problem with the editor '"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe" --wait'.
```
Even I close vscode , it still there.

**Comment by joaomoreno** [comment]
Does `C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe` exist in disk?

**Comment by manglobe** [comment]
> Does `C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe` exist in disk?

No it's real path is `C:\Program Files\Microsoft VS Code Insiders\_\Code - Insiders.exe`.

**Comment by joaomoreno** [comment]
I see... You have to fully reinstall, unfortunately. Between uninstalling and installing, make sure the `C:\Program Files\Microsoft VS Code Insiders` folder does not exist.

BTW, have you tried the user setup? https://code.visualstudio.com/docs/?dv=win64user
