### ISSUE TITLE
Lags when closing out of nodemon

### ISSUE THREAD

**Issue by ZumbaIdol** [Microsoft/vscode#71571]
Issue Type: <b>Bug</b>

I pressed Ctrl + c to close nodemon and nothing happened for over a minute.  I tried pressing some other keys and at first nothing happened, then after several seconds the text that I typed appeared  at the prompt.  

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.1.0
python|ms-|2019.3.6215
csharp|ms-|1.18.0
team|ms-|1.149.2
python|tht|0.2.3
jinja|who|0.0.8

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by ZumbaIdol** [comment]
Thank you for your response. I'm not experiencing the issue anymore. It's
been a little while since I posted this issue and think the software had
been updated.

D. Foote
