### ISSUE TITLE
Extensions sidebar isn't loading

### ISSUE THREAD

**Issue by Mason-Chou** [Microsoft/vscode#71574]
- VSCode Version: 1.32.3
- OS Version: Linux x64 4.15.0-46 generic

Steps to Reproduce:

1. Open VSCode and then click on extensions tab.
2. Nothing will showup.

Seems to be the same issue as the following: https://github.com/Microsoft/vscode/issues/30902
Resolution seems to be a bug in the code; maybe got accidentally re-introduced in linux.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@Mason-Chou What do you mean by Nothing will showup? Can you please provide a screenshot?

**Comment by Mason-Chou** [comment]
![image](https://user-images.githubusercontent.com/11034427/55473990-e5de1a80-55c4-11e9-8b90-3fbcfa2ac60f.png)

Extensions will keep trying to load. Nothing I do will showcase either my installed extensions or the marketplace.

![image](https://user-images.githubusercontent.com/11034427/55474125-4705ee00-55c5-11e9-8136-fa69980a3d59.png)
Similarly like the linked issue. The submit the bug link doesn't work as well. Clicking on it will provide no feedback.

**Comment by sandy081** [comment]
Can you please let us know if you see anything in logs and console

Logs: F1 -> Open View -> Log (Shared Process)
Console: F1 -> Toggle Developer Tools -> Console

**Comment by Mason-Chou** [comment]
Just updated to the march release VSCode and now my extensions sidebar is working!

I checked the logs before the update and it may be tied to this error message:
![image](https://user-images.githubusercontent.com/11034427/55599909-bc310a80-570e-11e9-893b-7a46940f7eee.png)

Seems like the **sharedprocess.log** wasn't getting made when I was starting the app. 

I'm going to leave the issue open if you want to put any more feedback. The problem been solved for me by updating.

**Comment by sandy081** [comment]
Thanks for the update.
