### ISSUE TITLE
SCM: Opening a folder with many repos can push views out of the viewport

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#71578]
Issue Type: <b>Bug</b>

If I open a folder that contains many repos, switching to the SCM sidebar will now select them all by default (so that a view per repo is visible), but since they all have a minimum size they end up pushing views outside the viewport and without collapsing the views there is no way to get to the views pushed out (because you can't scroll the panel) -- nor is there any indicator that views are out of the viewport.

While this isn't new in 1.33, it is far more apparent, since it happens by default. When I noticed this, I actually thought for a minute that GitLens had failed to startup or something, because none of its views were shown (since they had gotten pushed out of view).

/cc @joaomoreno 

VS Code version: Code - Insiders 1.33.0-insider (0ac111466ec925fd5ca180ab9893f51531e419b2, 2019-04-01T15:51:40.913Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
This is https://github.com/Microsoft/vscode/issues/70888

This is fine for now, as long as the Source Control Providers view is at the top. Once the user selects one repo, all others will hide, cleaning everything up.

We could also cap the number of repositories we automatically show.

**Comment by joaomoreno** [comment]
#64188
