### ISSUE TITLE
Showing the fixes menu (lightbulb) ends up saves the document

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#71580]
Issue Type: <b>Bug</b>

I don't believe this is new, but I think I have finally figured out an issue I've been having for a while now. The behavior I've been seeing is that using quick fixes to say add imports would sometimes completely screw up and insert imports in the middle of words, etc. I had always assumed that this was do to some timing conflict with applying the fix and my webpack watcher (which does linting fixes, including reordering imports), but until now I hadn't tracked down exactly how it happened.

Today, I noticed that just showing the lightbulb quick fix menu (via shortcut key or using the mouse) causes the document to be saved -- this is because it is apparently considered to be a focus change as I have `"files.autoSave": "onFocusChange"` set. IMO this should not be considered a focus change.

So because of this, changing focus to the menu, saves the document, which kicks off the watcher, while I then execute one of the fixes, which ends up applying a change to the document which might be a moving target because the webpack watcher is also mucking with it.

Can we change the quick fix menu to not be considered a focus change of the document?

VS Code version: Code - Insiders 1.33.0-insider (0ac111466ec925fd5ca180ab9893f51531e419b2, 2019-04-01T15:51:40.913Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
@eamodio Do you use custom or native menus?

**Comment by eamodio** [comment]
Custom menus

**Comment by jrieken** [comment]
@stevencl Custom menus aren't "rooted" inside the editor, right? Causing a full focus-loss? @bpasero Is this something that you are aware of?

**Comment by bpasero** [comment]
No, not so far. Opening a context menu inside the editor should not save the document if it is configured to "save on focus lost", but this could be challenging with custom menus.

**Comment by jrieken** [comment]
We might be forced to ask the context menu service if its currently showing a menu and not save in that case

**Comment by bpasero** [comment]
@jrieken @alexandrudima I am subscribing to ICodeEditor.onDidBlurEditorWidget and would think this one should maybe not fire if the custom context menu shows? I find that makes more sense than having to check in each consumer for a context menu being visible or not?

**Comment by jrieken** [comment]
@mjbvz I have pushed a change to make sure `getCodeActions` gets canceled when the model changes during the request

**Comment by alexandrudima** [comment]
@bpasero I don't think `ICodeEditor.onDidBlurEditorWidget` can be aware of custom context menus because they are implemented at a conceptional layer above the editor. Would the editor then need to be aware of the command palette and the custom menubars as well?

**Comment by bpasero** [comment]
@sbatten any clue how to detect that focus is in the context menu or even the main menu? ideally I could even pass you in a HTMLElement so that we only prevent saving if the context menu was opened within the editor, though this could also be optional.

**Comment by bpasero** [comment]
@sbatten ping

**Comment by sbatten** [comment]
@bpasero I don't really have a great solution for this. There a few perspectives here:

1) Focus loss due to context menu inside the editor.
-> Right now, the context menu is rooted in the context view. It could be positioned absolutely within the editor to ensure focus remains in the editor. I think this might be what you were referring to by passing an HTMLElement. I am not certain of the implications of this. @joaomoreno might have some additional insight.
-> We might also be able to do something with contextKeys to manage if a context menu is open, but I don't know if that's any better or cleaner than just having a check on the context menu service to see if it is open.
-> Just checking to see if the context menu is open with some contextmenuservice api could be the simplest solution if there aren't a lot of places where this kind of accuracy is important. I don't think this api would be functional in the native case however. (Though its not relevant for this issue, it still feels wrong)
2) Focus loss due to application menu
-> This is much harder since the menubar is part of the dom under the title bar. It can't just be moved into the editor.

Also, clicking the lightbulb regardless of native/custom menus still causes a focus loss.

**Comment by bpasero** [comment]
Having a method on the context menu service to ask if focus is inside any of the menu (context or top level menu) is something to explore. If I had such a method I can see if it is any useful. 

One potential issue I see is that even if I ask using that method, if the user then clicks somewhere else outside the editor, we should track that as a focus lost event and save the editor but would probably not unless we get an event from the menu service that now focus is lost from the menu.

**Comment by bpasero** [comment]
This has to be fixed on the editor level first, as you can see below just clicking the light bulb seems to send the focus change event:

![before](https://user-images.githubusercontent.com/900690/56674541-89998280-66ba-11e9-92ce-40020bc88381.gif)

Even if we detect the menu, the document would have already been saved by then. Since I do not see the editor saving when moving focus into the find widget, I suspect this is specific to the lightbulb.

**Comment by bpasero** [comment]
@alexandrudima after this change I can no longer click the lightbulb on Linux at least. Looks like this broke the widget interaction. Besides, we should reopen this issue as the editor will still save when interacting with the menu.

//cc @jrieken @mjbvz

**Comment by jrieken** [comment]
<img width="1345" alt="Screenshot 2019-05-28 at 09 42 03" src="https://user-images.githubusercontent.com/1794099/58459992-f4603280-812c-11e9-954b-e5f89e3cec50.png">

Looks like preventing default on the mouse down event doesn't work on linux and that therefore the widget hides again (triggered by the context service). You can verify that by right clicking the light bulb. Everything works nicely when using native menus

**Comment by eamodio** [comment]
I am seeing the same thing as @bpasero but on Windows

**Comment by jrieken** [comment]
@eamodio Using custom menus?

**Comment by eamodio** [comment]
Yeah

**Comment by bpasero** [comment]
@sbatten if a fix is too complicated for endgame, we can always return to the previous behaviour and work on a real fix in June.

**Comment by jrieken** [comment]
Yes - this commit can be reverted easily

**Comment by sbatten** [comment]
@jrieken @alexandrudima I changed this to include stop propagation. Is there any reason why this wasn't already the case?

**Comment by jrieken** [comment]
>  Is there any reason why this wasn't already the case?

We usually only prevent defaults and don't stop events from propagating. We consider that the better style as we don't wanna steal events from others. Maybe global'ish listeners, like the context view, should check if default has been prevented

**Comment by sbatten** [comment]
> Maybe global'ish listeners, like the context view, should check if default has been prevented

That makes sense. It should be a safe change, but do you want to wait til after the release to do this if the current fix will suffice?

**Comment by jrieken** [comment]
Yeah, let's wait ill after the release. For now we are good, right? Eg custom menu users do see a quick fix menu, right?

**Comment by sbatten** [comment]
yeah

**Comment by sbatten** [comment]
last commit is to fix the previously mentioned prevent default issue

**Comment by eamodio** [comment]
Can this be bumped up? I still hit this pretty often.

**Comment by sbatten** [comment]
this should have been resolved with the shadow dom in editor. @eamodio to verify.
