### ISSUE TITLE
.tsx commenting issue with latest TS/JS grammar extension

### ISSUE THREAD

**Issue by uloco** [Microsoft/vscode#71586]
When the "Latest TypeScript and Javascript Grammar" Extension is installed, line comments stop working correctly in `.tsx` files.

After disabling this plugin, the commenting works again in vscode. Even tried in vscode insiders, there is no problem in vscode with commenting jsx or tsx on the lastest insider and normal version without this plugin installed. Just try out yourself, install insiders without any extensions, install this extension and tsx commenting stops working correctly.
![vscode-bug-tsx-commenting](https://user-images.githubusercontent.com/8818340/54593560-1d7a8d80-4a2f-11e9-8916-d6896cbeb91c.gif)

**Comment by uloco** [comment]
I already did, they pointed me here.
Look here: https://github.com/Microsoft/TypeScript-TmLanguage/issues/618

**Comment by mjbvz** [comment]
The extension that contributes the grammar is responsible for specifying what type of comment to use. We have logic for our built-in js/ts grammar to select the right commenting style. External grammars need to add their own mapping for this

**Comment by uloco** [comment]
I thought, this extension provides the bleeding edge version of the next JS/TS grammar for vscode, since its repository owner is Microsoft also. I will file an issue there again. Thanks for your time.
