### ISSUE TITLE
FileService.watch fails if given resource does not exists

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#71589]
Assume that a resource is being watched at multiple locations in code.

- Resource does not exist
- Location 1: Watch on the resource.
- Location 2: watch on the resource.

- Location 1: Stop watching. Create the resource. Start watching
- Open resource and change the content.

🐛 No change events are triggered

**Comment by bpasero** [comment]
I am closing this as designed, as discussed the contract on the caller is that the file/folder must exist.
