### ISSUE TITLE
Support Git Stash unstaged changes

### ISSUE THREAD

**Issue by julian-poidevin** [Microsoft/vscode#71597]
It would be great to have "Git: Stash unstaged changes" command shortcut in command pannel 
This would avoid typing manually `git stash save -k`.

The "Stash All changes" button in the right pannel has the same function in `STAGED CHANGES` and in `CHANGES` parts. Maybe it could be implemented an other way on the `CHANGES` part to only stash changes not staged.

![image](https://user-images.githubusercontent.com/8756421/55413200-26a84600-5569-11e9-8b2b-0977a7de6c5a.png)

**Comment by julian-poidevin** [comment]
This issue is not a duplicate of the suggested ones.

**Comment by joaomoreno** [comment]
@julian-poidevin The `Stash All Changes` action comes from the GitLens extension. It would make sense to file this feature request over there as well?

**Comment by julian-poidevin** [comment]
@joaomoreno Oh snap ! You're right, opening the issue in GitLens as well. I'll let you close this one if you consider it useless.

**Comment by joaomoreno** [comment]
Definitely not useless! :wink:
