### ISSUE TITLE
Why not support all encodings that are supported by iconv-lite?

### ISSUE THREAD

**Issue by yossizahn** [microsoft/vscode#71591]
- VSCode Version: 1.32.3
- OS Version: all

Hi,
I have searched through previous issues and it seems that you have been adding various legacy encodings on a case-by-case basis. Is there a valid reason for this? I am currently trying to read through source code containing text in cp862 (DOS/IBM Hebrew) which is currently supported in iconv-lite but unsupported in VSCode. It would make me happy if support could be added. However, I don't see any reason not to add all available codepages.

Previous issues/pull requests:
https://github.com/Microsoft/vscode/issues/9468
https://github.com/Microsoft/vscode/pull/47123
https://github.com/Microsoft/vscode/issues/23646

**Comment by Somnium7** [comment]
We are also interested in this. In particular in "maccenteuro" encoding. It is supported in iconv-lite (as mentioned [here](https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings)). We can use it now by manually writing in settings it, however some things don't work correctly with that. One most important is that git diff is incorrect, as it shows lines with diacrytics as changed.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/68237
