### ISSUE TITLE
Git features [in explorer and source control panes] do not work when folder opened via symlink

### ISSUE THREAD

**Issue by webmasterMeyers** [Microsoft/vscode#71594]
Issue Type: <b>Bug</b>

On a Linux (this is Ubuntu) OS.

Steps to reproduce:

1. Clone or start a new git repo in `/var/www/html/my-awesome-website`
2. create a symbolic link in your home folder `sudo ln -s /var/www/html/ ~/Sites/`
3. in VS Code, open folder via `~/Sites/my-awesome-website`

Expected behaviour, the file explorer would highlight and mark files as they are changed.  The Source Control panel would update it's "dirty" count etc.
Actual behaviour, nope, none of that.

Of note, the output of Git will say 

> fatal: not a git repository (or any of the parent directories): .git

Now open a folder via `/var/www/html/my-awesome-website` and everything works as expected!

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.18.0-16-generic (Ubuntu 18.10)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4034)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.32GB (15.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.8
php-debug|fel|1.13.0
twig-language|mbl|0.7.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0

</details>

**Comment by webmasterMeyers** [comment]
I should add that when open via the symlink `~/Sites/my-awesome-website` the "refresh" button in the Source Control pane would work.  When clicked the changed files would be found.  Staging and committing them via the Source Control pane also works.  Just none of the automagical refreshing or highlighting that I have grown oh so fond of.

**Comment by joaomoreno** [comment]
#5970
