### ISSUE TITLE
[git tool bug] Use command change git branch, but vsCode default git branch not changed

### ISSUE THREAD

**Issue by Richard-Choooou** [Microsoft/vscode#71592]
- VSCode Version: 1.26.1
- OS Version: mac os 10.13.6

Steps to Reproduce:

1. Use command change git branch
2. vsCode default git tool's git branch has not changed 

must click the refresh button to reload git branch

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by joaomoreno** [comment]
Did you open the repository's root folder as a folder in VS Code?

**Comment by Richard-Choooou** [comment]
No, I didn't, I open a child folder in VS Code and changed git branch.

**Comment by joaomoreno** [comment]
Known limitation: https://github.com/Microsoft/vscode/issues/41085
