### ISSUE TITLE
Git diff view does not show untracked nested repositories, but will commit them

### ISSUE THREAD

**Issue by kryops** [Microsoft/vscode#71593]
Issue Type: <b>Bug</b>

VS Code does not show untracked nested Git repositories it in the "Source Control" panel's diff view, but will add them to a commit using the "Commit" button, or stage them using the "Stage All Changes" button.

In my case I wanted to add an external repository into my yarn workspace for development, but added it to my `.gitignore` incorrectly, which made me accidentally commit it because it did not show up in VS Code's diff view.

Steps to reproduce:

- Clone a Git repository and open it in VS Code
- Optional: Make changes to a file
- Clone a nested repository into a subfolder

Expected result:
- The "Source Control" view shows both the edited file and the untracked nested repository 

Actual result:
1) Only the changes to the edited file are displayed in the "Source Control" view

![image](https://user-images.githubusercontent.com/1042594/55401539-5ea38f00-5551-11e9-8cfc-1368dc8d7927.png)

2) When committing all changes by pressing the "Commit" button at the top of the "Source Control" view, the nested repository is committed as well

```
> git diff HEAD^1

...

diff --git a/packages/test b/packages/test
new file mode 160000
index 000000000..edcb146c9
--- /dev/null
+++ b/packages/test
@@ -0,0 +1 @@
+Subproject commit edcb146c9d9904038f83a7020a802cd6b8212d3b
```

3) Only after the nested repository is committed, The "Source Control" view starts displaying changes made to it

![image](https://user-images.githubusercontent.com/1042594/55401968-8a734480-5552-11e9-8ee1-cda68c72f636.png)

Side Notes:

- The nested repository is displayed in the "Staged Changes" diff view when the "Stage All Changes" button is clicked or it is added via `git add` through the shell. This bug only seems to affect nested repositories that are untracked.
- The Git command line warns about adding nested repositories that are not proper submodules. Maybe VS Code should add a warning in these cases as well?

```
> git add packages/test

warning: adding embedded git repository: packages/test
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint:   git submodule add <url> packages/test
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint:   git rm --cached packages/test
hint: 
hint: See "git help submodule" for more information.
```

Related: https://github.com/Microsoft/vscode/issues/37947

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.18GB free)|
|Process Argv|-psn_0_77843|
|Screen Reader|no|
|VM|0%|

</details>

- [x] Tried with extensions disabled

**Comment by kryops** [comment]
(not a duplicate as this issue is not about showing the nested repository as a SCM provider, but rather the diff it causes to the parent repository)

**Comment by joaomoreno** [comment]
#37947
