### ISSUE TITLE
Feature Request: Open file with an extension scheme

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#7159]
It would be nice to be able to open files from the Explorer with a TextDocumentContentProvider scheme from an extension, 

![image](https://cloud.githubusercontent.com/assets/7251102/15763190/349bfebc-28f0-11e6-9965-e6b99b84dd13.png)

It would then only be a matter of calling openTextDocument() with a different schema than file:
```javascript
var fileUri = vscode.Uri.file(filePath);
var hexUri = vscode.Uri.parse(fileUri.toString().replace('file:', 'hexdump:'));
vscode.workspace.openTextDocument(hexUri).then(function (doc) {
    vscode.window.showTextDocument(doc);
}
````

It would be useful for opening binary files with extension like [vscode-hexdump](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump)

**Comment by ZCShou** [comment]
I feel the same way！

**Comment by jrieken** [comment]
#3192
