### ISSUE TITLE
Opening Command Palette is removing the current line' indicator

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#7160]
- VSCode Version: 1.2.0-insider
- OS Version: Windows

Steps to Reproduce:

1. Put the cursor in any line, Code indicates the _current line_ with a full line border
2. Opens `Command Palette` (`Ctrl + P`)
3. The _current line indication_ disappears, until you closes the `Command Palette` or any `QuickPick` that you open.

Here is an animated GIF:

![code-insiders-current-line-indicator-disappears](https://cloud.githubusercontent.com/assets/3781424/15765513/fa653512-290b-11e6-879b-03c7c09acd0c.gif)

I noted this issue in the previous insider version (May 31 I guess). And in the current (June 2nd) also presents the issue.

Thanks in advance

**Comment by Tyriar** [comment]
I think this is intended behavior as the editor is not being focused.

**Comment by alefragnani** [comment]
It is visible in the current _stable_ release, and I'm pretty sure that at least since 0.10.7 (_stable_ and _insiders_) it was also visible.

I just noted because of my Bookmarks extension, which contains a `List` command that allows the user to navigate between the bookmarked lines and _preview_ the cursor. The code is something like:

```typescript
function revealLine(line: number) {
        var newSe = new vscode.Selection(line, 0, line, 0);
        vscode.window.activeTextEditor.selection = newSe;
        vscode.window.activeTextEditor.revealRange(newSe, vscode.TextEditorRevealType.InCenter);
}
```

Thanks

**Comment by Tyriar** [comment]
@alefragnani good point, this is a regression. It no longer highlights when focus is not in the editor.

**Comment by alefragnani** [comment]
@Tyriar thanks for you help 👍
