### ISSUE TITLE
Passing ${workspaceFolder} to extension development host has no effect

### ISSUE THREAD

**Issue by realmhamdy** [microsoft/vscode#71609]
Version: 1.33.0-insider (user setup)
Commit: 0ac111466ec925fd5ca180ab9893f51531e419b2
Date: 2019-04-01T15:51:40.913Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a new extension `yo code`
2. Change `launch.json` and include `"${workspaceFolder}"` as the first item in each `args` list.

**Expected behavior**: The workspace opened in the original instance to be also opened in the extension development host instance.

**Actual behavior**: The EDH opens without an active workspace.

I'm building an extension that, during tests, I need an active workspace. Not to repeat myself, here's my [SO question](https://stackoverflow.com/questions/55456193/testing-a-vscode-extension-that-involves-opening-a-folder-workspace/55469250#55469250).
Does this issue occur when all extensions are disabled?: Yes

Example project that exhibits the issue: 
[hello-world.zip](https://github.com/Microsoft/vscode/files/3035203/hello-world.zip)

**Comment by weinand** [comment]
VS Code prevents to open a folder multiple times.
