### ISSUE TITLE
allow navigating to a type

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#71604]
problem: 
currently you can navigate to a file (Ctrl + P), to a local symbol (Ctrl + Shift + O), but there is no way to navigate to a type that can be imported

workaround:
declare a variable
```
const x: 
        ↑ - you are here
            1. start writing type name
            2. auto complete
            3. auto import
            4. navigate to type: F12
            5. come back and delete what was written
```

solution:
i wish there was a type picker just like there is for symbols and files

crossposted: https://github.com/Microsoft/TypeScript/issues/30710

**Comment by mjbvz** [comment]
Try using [Go to symbol in workspace](https://code.visualstudio.com/Docs/editor/editingevolved#_open-symbol-by-name) for this

**Comment by aleksey-bykov** [comment]
sweet baby jesus, thank you!
