### ISSUE TITLE
HTML Format

### ISSUE THREAD

**Issue by bobcat2085** [Microsoft/vscode#71606]
Issue Type: <b>Bug</b>

The following HTML string is not formatting properly.

```
<div><div><label id="myLabel">Hello, World</label></div><div><input id="myInput"></div></div>
```

It is formatting to the following:
```
<div>
	<div><label id="myLabel">Hello, World</label></div>
	<div><input id="myInput"></div>
</div>
```

But I would expect it to format the Label and Input on their own lines; ideally with the content of the element on its own line also:
```
<div>
	<div>
		<label id="myLabel">
			Hello, World!
		</label>
	</div>
	<div>
		<input id="myInput">
	</div>
</div>
```
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.87GB (4.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. You can file the request directly against https://github.com/beautify-web/js-beautify ?
