### ISSUE TITLE
microsoft scuplt mousewheel often stops working until application restarted

### ISSUE THREAD

**Issue by negspect** [microsoft/vscode#71607]
Issue Type: <b>Bug</b>

the mousewheel on the microsoft scuplt comfort bluetooth mouse will often stop working in visual studio code until visual studio code is restarted.  this does not happen in other applications, ie, mousewheel is still working in firefox when it stops working in code.  

sometimes cycling the power on the mouse will restore mousewheel functionality, but often code needs to be restarted.    this breaks flow of getting stuff done.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1512)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.18.0
mono-debug|ms-|0.15.8
unity-debug|Uni|2.7.2

</details>

**Comment by alexandrudima** [comment]
@negspect Is the mouse wheel working consistently for you in Chrome?

**Comment by negspect** [comment]
Hi Alexandru!

I don't use chrome, but it works fine in firefox, notepad++, etc.  Even when it stops working in visual studio code, I tab over to firefox and it's still working fine there.

Thanks,
Jeremy

________________________________

**Comment by alexandrudima** [comment]
The reason I asked about Chrome is that Chrome is built with Chromium and VS Code is built with Electron, which is also built with Chromium. So a mouse wheel often stopping in both Chrome and VS Code would indicate the issue with Chromium.

**Comment by negspect** [comment]
Still don't use chrome over here, sorry.  However, I discovered something about this issue.

When the mousewheel stops working, dragging the scrollbar on the right with the mouse and appears to get the mousewheel working again without having to cycle power on the mouse.  This is somewhat less aggravating.  But also indicates that scrollbar code is resetting whatever state is borked in mousewheelland.

Thanks,
Jeremy

________________________________

**Comment by alexandrudima** [comment]
I use a mouse with a wheel every day and I cannot reproduce this... The mouse wheel never "blocks"... Does this happen for you with other mice ?
