### ISSUE TITLE
Allow preLaunchTask to run task from another project in workspace

### ISSUE THREAD

**Issue by deppe** [Microsoft/vscode#71603]
Suppose I have two projects in a workspace: an application and a dependent library. In order for the application to "run", the library needs to be built. To accomplish this, I would like to add a preLaunchTask in the application's launch.json which would run the "build" task from the library's tasks.json. AFAIK, this is not currently possible as the preLaunchTask can only run tasks from its own project's tasks.json.

**Comment by weinand** [comment]
@alexr00 is there already a syntax to refer to a task in a different workspace folder?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/36966 and https://github.com/Microsoft/vscode/issues/58818
