### ISSUE TITLE
[themes] Debounce color theme selection

### ISSUE THREAD

**Issue by Gaboik** [microsoft/vscode#71616]
# Background

Like a lot of developers, I find myself developing in multiple languages and environments and and I have adopted different color themes that I prefer for different languages. So I, for instance, like to use the _Monokai_ theme when I write JavaScript code but prefer to use something like Material Theme Dark when I write C# code. The point here is because I like to use different themes for different languages, I find myself switching color themes often (pretty much as often as I change workspace).

However, the process of changing color theme can be tedious when there are a lot of color themes installed, (by a lot here I mean like 14, including the default ones) because it is sometimes necessary to scroll trough the entire list of color themes to access the desired one. This becomes tedious because when using the keyboard arrows, which I do because I open the 'color theme selector' by pressing `Ctrl + K T` so it's convenient to not use the mouse, the editor previews the highlighted color theme every time an arrow key is pressed which takes some time and makes it somewhat long to select a desired color theme.

# Current behavior

As of now, the 'color theme selector' previews the selected  color theme every time a new one is selected using the keyboard arrow keys.

## Somewhat of a workaround

One possible way to partly counter this is to keep pressing an arrow key until the cursor scrolls to the desired color theme and try to 'snipe' it but this is no easy task and in my opinion, not adequate.

# Proposal

I would like to suggest that the 'color theme selector' be '[debounced](https://www.quora.com/What-is-debouncing)'. I use the term 'debouncing' for lack of a better term but what I mean by 'debouncing' is that the 'color theme selector' should not immediately attempt to preview the selected color theme when the selection changes and instead wait a given interval (say 300ms) before previewing the selected color theme, allowing someone to rapidly scroll trough the list of color themes without having to wait for the editor to have previewed each one.

Any thoughts?

**Comment by aeschli** [comment]
To verify:
- open the color or file icon theme selection dialog (`Ctrl + K Ctrl +T`)
- quickly cursor down will not reveal the theme, only after typing stops.

**Comment by Tyriar** [comment]
@Gaboik the debouncing is a nice addition but FYI you might be better off typing to search for the theme, also you can disable built-in themes that you never plan to use to shorten the list:

![image](https://user-images.githubusercontent.com/2193314/67803652-b86a2a00-fa4a-11e9-9f49-072ab078ea54.png)
