### ISSUE TITLE
[FeatReq] Support nbdime for diff-ing notebooks

### ISSUE THREAD

**Issue by cipri-tom** [microsoft/vscode#71611]
Searched existing issues, but the closest one is #17973 .

However, since Jupyter notebooks are now a first-class citizen in VSCode, they should also be better integrated for git diffs and merge. There is a solution for that: [nbdime](https://github.com/jupyter/nbdime)

So, if it it not possible to integrate it directly in VSCode, then at least it should offer to diff the files in the browser.

**Comment by roblourens** [comment]
Sorry for the slow response. Our Jupyter notebook support comes from extensions and this should come from an extension too.
