### ISSUE TITLE
Javascript: "Go To implementation" does not work

### ISSUE THREAD

**Issue by chipbite** [Microsoft/vscode#71618]
Issue Type: <b>Bug</b>

All similar issues seem closed. But it the issue is not fixed, _it does not work_.
Shouldnt there be atleast one open item so that it can be tracked?

Repro: Create project with two javascript files, one exporting a fucntion foo to the other, using module.exports.
Use foo in the code and try to navigate to it using Go To Implementation. Error pops up, "Cannot find implementation".

Expected: It navigates to implementation of foo...

BR! /mawi

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.0
vscode-eslint|dba|1.8.2
plantuml|jeb|2.10.9
restructuredtext|lex|105.0.0
cpptools|ms-|0.22.1
gitblame|wad|2.7.0

</details>

**Comment by mjbvz** [comment]
Please share some example code
