### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by rolurq** [microsoft/vscode#71610]
Issue Type: <b>Bug</b>

I tried to install the prettier extension [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and it fails. When I try to install it manually from the vsix, this error pops up
```
Corrupt ZIP: end of central directory record signature not found
```
The same error shows up with the angular language extension.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.18.0-2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G (4 x 1170)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|11.27GB (0.49GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
dart-code|Dar|2.25.0
flutter|Dar|2.25.0
gitlens|eam|9.5.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
Angular2|joh|7.0.1
vscode-peacock|joh|2.0.0
python|ms-|2019.3.6215
Go|ms-|0.9.2
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.1284
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.7.0
polacode|pnp|0.2.2
vscode-workspace-switcher|sad|1.13.1
vscode-wakatime|Wak|1.2.13

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
What about other extensions? Can you install any extension?

**Comment by rolurq** [comment]
Yes, I can install and update some of the other extensions. I recently noticed that updatating the Python extension throws the same error. I don't know what is the complete list of extensions that causes this but there are not all of them.

**Comment by sandy081** [comment]
Are you seeing the same error when you download it and install it?

**Comment by rolurq** [comment]
@sandy081 yes, I tried it with the Prettier extension and the angular one, both when installed manually still throw the error.

**Comment by rolurq** [comment]
@sandy081 yes, I tried it with the Prettier extension and the angular one, both when installed manually still throw the error.

**Comment by seanmcfeely** [comment]
I was getting this exact message installing an extension on a remote system because I needed to specify the proxy to use for that system. Perhaps whatever system you are trying to install this extension on uses a proxy as well?

In vscpde:
File --> Preferences --> Settings --> click the "Remote [SSH: remote.system]" tab --> search for "proxy" --> enter your proxy  info in the box: http://user:pass@proxyaddress:proxyport

**Comment by sandy081** [comment]
@seanmcfeely Your issue is related to this https://github.com/microsoft/vscode-remote-release/issues/231 and has been handled.

@rolurq Sorry for not getting back on this. 

> yes, I tried it with the Prettier extension and the angular one, both when installed manually still throw the error.

It means that the extension you are downloading is not complete. Looks like Marketplace is not returning complete vsix.

**Comment by rolurq** [comment]
@sandy081 I have keep vscode updated, I think this is fixed, I am not really sure, at least I could install the extensions that where causing the errors, but I haven't installed any new ones.
I'm going to close this because the problem hasn't happened again.
