### ISSUE TITLE
Find in Files: Add hint on which path separator to use

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#71621]
I'm working on a Windows machine, and I've spent some time figuring out that Find in Files doesn't accept backslash characters as path separators when choosing a folder to search within:

![Find in Files - Backslash](https://user-images.githubusercontent.com/9283914/55439413-d0f18f00-55a4-11e9-8dd1-7d09283d5070.png)

![Find in Files - Slash](https://user-images.githubusercontent.com/9283914/55439426-db138d80-55a4-11e9-8167-c85157716648.png)

Please either add a hint to the Find in Files panel explaining that backslashes are not accepted as path separators or accept backslashes as path separators.

**Comment by roblourens** [comment]
Spent some time deciding whether to allow this by rewriting \ to /, because our internal glob implementation doesn't support \, but I decided just to stay consistent with the `files.exclude` and `search.exclude` settings which don't support \. I did add a comment about this in the docs.
