### ISSUE TITLE
Link in the editor with the `vscode:` URI scheme is parsed as `file://vscode:...`

### ISSUE THREAD

**Issue by phaseOne** [microsoft/vscode#71622]
Issue Type: <b>Bug</b>

Cmd-clicking a link in the editor with the `vscode:extension/...` URI scheme + path doesn't launch the extension page, and results in an error. It seems that the URL opener service is not recognizing the `vscode:` URI scheme, and instead is assuming the link is a `file://` URI.

Might be related to #69998. Discovered while fixing #71414.

## Steps to reproduce
Create a Markdown file that contains a link with the `vscode:` URI scheme:
```
[Link to Python extension for vscode](vscode:extension/ms-python.python)
```
Cmd-click link in editor. Receive error:
> Unable to open 'ms-python.python': File not found (file:///vscode:extension/ms-python.python).

Expected behavior is to launch the extension page for `extension/ms-python.python`.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.0.1
solargraph|cas|0.19.3
vscode-modelines|chr|2.0.2
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.5
vscode-diff|fab|1.4.0
vscode-git-history|fab|2.0.5
beautify|Hoo|1.4.11
vscode-duplicate|mrm|1.2.1
python|ms-|2019.3.6139
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
mono-debug|ms-|0.15.8
incrementor|nms|0.1.0
printcode|nob|3.0.0
openhab|ope|0.4.1
vscode-docker|Pet|0.6.1
platformio-ide|pla|1.6.0
diff|raf|0.0.1
ruby|reb|0.22.3
java|red|0.41.0
LiveServer|rit|5.5.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.7
code-spell-checker|str|1.6.10
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.1.5
vscode-arduino|vsc|0.2.25
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
markdown-all-in-one|yzh|2.2.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Partially fixed by #71416 but links are still not working.

Adding @joaomoreno since this still doesn't work end to end however. One issue I ran into while testing this that `vscode:` links will not work for users on insiders (and `vscode-insiders` links will not work for regular VS Code users)

**Comment by phaseOne** [comment]
@mjbvz Perhaps the handler should fall back to the installed version of VS Code if the other is not available? e.g. Only have VS Code, but clicking `vscode-insiders` links will open VS Code anyway

**Comment by joaomoreno** [comment]
There's a check for the actual protocol to be exactly the one specified in `product.json`:

https://github.com/Microsoft/vscode/blob/a62b16e130b259127ff23ac41c0ddf1a7c88183b/src/vs/platform/url/electron-browser/urlService.ts#L31

We maybe have to rethink that and just handle any `vscode*` or `code*` uris?
