### ISSUE TITLE
Links with `vscode:` URI scheme are inert in Markdown preview window

### ISSUE THREAD

**Issue by phaseOne** [microsoft/vscode#71624]
Issue Type: <b>Bug</b>

Clicking a link in the Markdown preview with the `vscode:extension/...` URI scheme + path doesn't launch the extension page. vscode does not display an error

Might be related to #69998, and #71622. Discovered while fixing #71414.

## Steps to reproduce
Create a Markdown file that contains a link with the `vscode:` URI scheme:
```
[Link to Python extension for vscode](vscode:extension/ms-python.python)
```
Click link in preview window. Nothing happens.

Expected behavior is to launch the extension page for `extension/ms-python.python`.

VS Code version: Code 1.34.0 (df4988d54438247ebd8046f573e38e62176531db)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.0.1
solargraph|cas|0.19.3
vscode-modelines|chr|2.0.2
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.5
vscode-diff|fab|1.4.0
vscode-git-history|fab|2.0.5
beautify|Hoo|1.4.11
vscode-duplicate|mrm|1.2.1
python|ms-|2019.3.6139
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
mono-debug|ms-|0.15.8
incrementor|nms|0.1.0
printcode|nob|3.0.0
openhab|ope|0.4.1
vscode-docker|Pet|0.6.1
platformio-ide|pla|1.6.0
diff|raf|0.0.1
ruby|reb|0.22.3
java|red|0.41.0
LiveServer|rit|5.5.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.7
code-spell-checker|str|1.6.10
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.1.5
vscode-arduino|vsc|0.2.25
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.15.2
markdown-all-in-one|yzh|2.2.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@mjbvz In the latest Insiders, the link seems to be rewritten to:

![image](https://user-images.githubusercontent.com/22350/55709255-36e87700-59e8-11e9-8d4b-26de59e120f8.png)

**Comment by mjbvz** [comment]
I pushed a fix for that. Here's what I see on 0ab39f4148f242e7b0802330385fc99b4845aa31

![Screen Shot 2019-04-08 at 3 04 11 PM](https://user-images.githubusercontent.com/12821956/55759955-9d34c000-5a0f-11e9-8625-a2337321de6a.png)

**Comment by joaomoreno** [comment]
Yup that fixes it. Pushing another related fix.

**Comment by mjbvz** [comment]
On insiders, you need to use the `vscode-inssiders` scheme instead:

```
[Link to Python extension for vscode](vscode-insiders:extension/ms-python.python)
```

I just tested this again and those links seem to work in the preview and in the editor

We discuss this limitation #71622 but for now you need to use the scheme specific to the product being used
