### ISSUE TITLE
How to set different tabSize for special files?

### ISSUE THREAD

**Issue by fenbox** [Microsoft/vscode#7163]
- VSCode Version: 1.1.1
- OS Version: osx 10.11.5

How to set different tabSize for special files? Such as:

- `*.sass` file indent tabSize is 2
- `*.rst` file indent tabSize is 3

**Comment by jrieken** [comment]
there is the editorconfig extension that should do that: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
