### ISSUE TITLE
Color coding breaks in php if last character in string isnt space

### ISSUE THREAD

**Issue by SchadowofMorning** [Microsoft/vscode#71637]
Issue Type: <b>Bug</b>

If I write: 
`$id_result = $this->connection->prepare("SELECT @id AS ID");`
the following characters in the document( (, ), ?, <, >, {, }, although not [, ] ) are color coded like a string, but writing:
`$id_result = $this->connection->prepare("SELECT @id AS ID ");`
fixes the color coding.
Testet this with the Color Themes Monokai and Cobalt2.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-9590 Eight-Core Processor            (8 x 4716)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-summarizer|ala|1.0.0
Handlebars|and|0.4.1
ng-template|Ang|0.1.11
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.0.10
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
angular-schematics|cyr|1.23.0
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.8.2
angular-extension-pack|dog|7.2.0
githistory|don|0.4.6
vscode-generate-getter-setter|DSK|0.5.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.0.15
vscode-mysql|for|0.4.0
rust-test-lens|hde|0.1.2
beautify|Hoo|1.4.11
output-colorizer|IBM|0.1.2
phpcs|ika|1.0.5
angular2-switcher|inf|0.2.0
mysql-syntax|jak|1.3.1
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
Angular2|joh|7.0.1
language-haskell|jus|2.5.0
docomment|k--|0.1.6
vscode-rust|kal|0.4.2
refactorix|kri|0.3.6
node-module-intellisense|lei|1.5.0
regionfolder|map|1.0.4
json-to-ts|Mar|1.5.5
Angular-BeastCode|Mik|7.2.6
vscode-exec-node|mir|0.5.1
vscode-language-pack-de|MS-|1.32.4
azure-account|ms-|0.8.0
csharp|ms-|1.18.0
powershell|ms-|1.12.0
typescript-javascript-grammar|ms-|0.0.50
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
heroku-command|pko|0.0.8
tsimporter|pmn|2.0.0
quicktype|qui|12.0.46
bash-debug|rog|0.3.4
rust|rus|0.6.0
RustyCode|sav|0.19.1
shader|sle|1.1.4
move-ts|str|1.11.3
bootstrap4-vscode|the|6.1.0
unity-tools|Tob|1.1.0
unity-debug|Uni|2.7.2
vscode-lldb|vad|1.2.2
vscode-icons|vsc|8.4.0
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
unity-snippets|Ycl|0.1.2
linecount|yyc|0.1.7

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Looks fine to me? What do you see exactly?

![image](https://user-images.githubusercontent.com/323878/55502205-e7c5cf00-5600-11e9-917d-4d0f813ecd10.png)

**Comment by SchadowofMorning** [comment]
this is what i meant:
![withoutspaceattheend](https://user-images.githubusercontent.com/4491333/55534516-f372cd80-56b4-11e9-943f-d151d934a928.PNG)
![withspaceattheend](https://user-images.githubusercontent.com/4491333/55534517-f372cd80-56b4-11e9-9e8c-66fdb06f4bfb.PNG)

**Comment by roblourens** [comment]
I still can't reproduce. What theme is this? Can you share the full file as text?

**Comment by SchadowofMorning** [comment]
I cannot really share the full text file these screenshots where already a bit too much actually. In the original post I already stated I tested it with the Cobalt2 and Monokai, but I checked some other color themes at random from the theme-gallery, issue persists independent of the Color Theme. 
This is the minimal code I needed to reproduce the bug:
```
<?php
$sql = "SELECT id AS "
?>
```
![thisshouldntbegreen](https://user-images.githubusercontent.com/4491333/55618889-e67ada80-5797-11e9-9799-c8bc37812edd.PNG)

**Comment by SchadowofMorning** [comment]
I got some free time now I checked these things:
- Removed all php related extensions. Issue persists.
- Checked all the default themes, still happens.
- Installed new VSCode on seperate drive, still wrong color coding.
-Checked VSCode on my laptop, and, you guessed it, wrong colors.

**Comment by roblourens** [comment]
Can you try updating to 1.33 which was released yesterday? I still can't reproduce it so it may have been fixed.

![image](https://user-images.githubusercontent.com/323878/55638741-c2f66680-577c-11e9-8861-12540c6fbe24.png)

**Comment by SchadowofMorning** [comment]
already did that by reinstalling visual studio code.

**Comment by roblourens** [comment]
And it still happens? Does it happen if you start with `--disable-extensions`? Not sure if you have some alternate php grammar installed?

**Comment by SchadowofMorning** [comment]
Without changing anything about my setup it somehow disappeared today if I can recreate it again I will make a new issue but it seems I cannot reproduce the bug myself anymore.
