### ISSUE TITLE
Link to extended config file in tsconfig

### ISSUE THREAD

**Issue by hilleer** [Microsoft/vscode#71639]
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Install a typescript project with typescript version `>= 3.2.0` (earlier version don't support this way to extend node_module package.
2. Create a tsconfig file.
3. Make tsconfig file extend from a node module, e.g. `{ "extends": "@my-team/team-tsconfig" }`.
4. Cmd + click (on mac) to follow the link to the file, but returns an error `unable to open "team-tsconfig.json" file not found` - it expects the path to be `<project path>/@my-team/team-tsconfig.json`  

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Here's where the link is created: https://github.com/microsoft/vscode/blob/a3385c07216f510d9821731edd5fa8c67f797f05/extensions/typescript-language-features/src/features/tsconfig.ts#L35


Here's the check ts does to determine if we have a real path vs one to a module: https://github.com/Microsoft/TypeScript/pull/27348/files#diff-057bf8560e435e388ba45f7810c3d08dR2194

**Comment by vitaliymaz** [comment]
I'd like to work on the fix if nobody minds.

**Comment by mjbvz** [comment]
Fixed by #71944
