### ISSUE TITLE
Git stage changes does not update diff view

### ISSUE THREAD

**Issue by Nabav** [Microsoft/vscode#71634]
Exactly like #34209 and  #26642 (closed)

Version: 1.32.3
OS: Linux x64 4.9.0-8-amd64

Steps to Reproduce:
1. Stage some lines or whole file
2. Wait for diff view to update by excluding staged changes

Diff view does _not_ change after staging changes.

Same result without extensions.
@joaomoreno, please check, thanks.

**Comment by Nabav** [comment]
Inspired by #53652 and #3025, I have created a new local repository and step-be-step staging works great.
The bug shows up when I have a repository as a submodule in a higher level repository.
I think it is a duplicate of #3025 then.

**Comment by Nabav** [comment]
One more thing, when I edit the file outside vscode, the change is immediately shown inside vscode.

**Comment by joaomoreno** [comment]
> duplicate of #3025

:+1:
