### ISSUE TITLE
Implement showFirstIndentGuideLines

### ISSUE THREAD

**Issue by Sekkei** [microsoft/vscode#71631]
Adding showFirstIndentGuideLines to tweak UI experience (Current problem: if the following characters are a space, the Guide line continues until the next line with a character )

boolean: first indent guide lines

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please post a screenshot showing an example of what you mean, and perhaps a second image doctored to show what you would like to see,

**Comment by Sekkei** [comment]
Of course:

How it look:
![a](https://user-images.githubusercontent.com/28356741/55521056-5cd7e980-567f-11e9-91c4-84bdc5a4e0b0.png)

How it should look:
![b](https://user-images.githubusercontent.com/28356741/55521066-6e20f600-567f-11e9-83d1-d3124c8c2527.png)

What I want it to look like:
![c](https://user-images.githubusercontent.com/28356741/55521076-7842f480-567f-11e9-90ff-9e55cc57b6d9.png)
