### ISSUE TITLE
HTML autocomplete clears redo stack

### ISSUE THREAD

**Issue by NoOorZ24** [Microsoft/vscode#71636]
Issue Type: <b>Bug</b>

1) Wrap something with any tag
    `<span>Sample TEXT</span>`
2) Remove tag (with DELETE not UNDO)
    `Sample TEXT`
3) Edit something
    `New TEXT`
4) Undo until in step 1 (HTML autocomplete kicks in)
    `<span></span>Sample TEXT`
5) CTRL + Y  [SPAN is autocompleted and I can not redo anymore]
    `<span></span>Sample TEXT`

This is just a small example but this can discard some bigger chunks of code by trying to see how your code looked in past by using UNDO and hoping to do REDO

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.84GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by aeschli** [comment]
Yes, that's a known issue with the auto-close code. We have https://github.com/Microsoft/vscode/issues/52777 for the problem.
