### ISSUE TITLE
Cost of IContextKeyService#onDidChangeContext 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#71642]
Context keys have become popular, they drive keybindings, menus, and views. The latter two depend on events because they are stateful and need to update when context keys change. Simple instrumentation shows that during startup the event fires ~233 times and costs around 90ms (on my early 2015 MBP). Observations

* [ ] each `ViewDescriptorCollection` (explorer, search, scm, etc. etc) [listens](https://github.com/Microsoft/vscode/blob/04336627c2e675fc1464fe6fc5caf80cb0e374fa/src/vs/workbench/browser/parts/views/views.ts#L117) to the event no matter if it's visible or not cc @sandy081 
* [x] there is no way to emit a batch event, e.g producers call `myKey.set(value)`. For instance, [`EditorModeContext#_update`](https://github.com/Microsoft/vscode/blob/04336627c2e675fc1464fe6fc5caf80cb0e374fa/src/vs/editor/browser/widget/codeEditorWidget.ts#L1736-L1754) might trigger 19 events, instead of one
* [ ] most events are emitted during lifecycle phases `Starting` and `Ready`, so often before the UI shows much. Should the service buffer events till `Restored`?
* [ ] half of the events are triggered by context key creation and setting their default value. Should we not emit an event then?

**Comment by jrieken** [comment]
I have pushed and adopted `IContextKeyService#bufferChangeEvents` and I also fixed an interesting issue that would trigger events from child/scoped context services on its parent. With those changes, the event still fires 233 times but less listeners are reached and only ~30ms is spent processing them. 

I will push some more tweaks to the event itself but not do the event-pausing on lifecycle events.

**Comment by jrieken** [comment]
@sandy081 I leave the `ViewDescriptorCollection` to you

**Comment by sandy081** [comment]
@jrieken I looked into this a bit deeply to see if I can start listening to context only when viewlet is visible. But there is a usecase in activity bar to hide viewlet icon if it has no active views. So this needs me to build the model by reading and listening to context keys.

**Comment by sandy081** [comment]
Since no action can be taken un-assigning myself.

**Comment by jrieken** [comment]
no action then
