### ISSUE TITLE
[Feature request] Sync explorer with terminal

### ISSUE THREAD

**Issue by FreHu** [Microsoft/vscode#71641]
Add an optional setting so that navigating in the terminal in the currently opened folder would sync with the explorer view.

Example: doing cd app
![image](https://user-images.githubusercontent.com/5097067/55462188-797c0f00-55f6-11e9-84fe-ae00ec7e6709.png)
would expand the folder app
![image](https://user-images.githubusercontent.com/5097067/55462227-8dc00c00-55f6-11e9-88f2-631fc852d1ce.png)

**Comment by rthaneda** [comment]
Hello! University student intending on taking a stab at implementing this in the next week as an open source contribution for a class with my partner @tejdnagaraja — we will post updates here

**Comment by FreHu** [comment]
Hi @rthaneda! Since it is in my best interest, I will happily be your model user to provide feedback and testing if you require one. It would be nice to have someone from the vscode team comment that this is worth pursuing first though.

**Comment by Tyriar** [comment]
We don't have plans to add something like this to the core and I don't think it's possible to accomplish using the extension API currently (I don't think you can manipulate the explorer like this?).
