### ISSUE TITLE
switch desktop will type letter 'E' auto

### ISSUE THREAD

**Issue by CFhM-Lolipop** [Microsoft/vscode#7165]
- VSCode Version:1.2.0 insider
- OS Version:windows 10 insider preview 14352

bug report：
if you open vscode writing c++ code, then press ctrl+win+left to switch desktop(multi-desktop mode),and when you switch back, the editor will type an 'E' automactically without any other operation.

**Comment by rebornix** [comment]
can not repro this with vscode 1.2.0-insider and Windows 10 Enterprise. Not sure if it's a Windows issue.

**Comment by CFhM-Lolipop** [comment]
ok thanks,I'll check it.
And here's another problem, maybe my method is wrong, anyway,here it is:
when I'm writing a cpp program, if I choose "open a folder" such as the Desktop folder and edit the existing file and type an ';',which usually don't need to automatically delay a quick suggestion, but as the following picture shows,it does, and it's really awful when I just wanna type an CR, it type the top suggestion of the list so that I have to delete it.
Please tell me how to fix it, thank you very much.
PS:forgive my English since it's not good :0, I hope you understand what I'm saying.
![image](https://cloud.githubusercontent.com/assets/9619115/15797990/03e1779e-2a5c-11e6-8c5e-3df76f1b8575.png)

**Comment by alexandrudima** [comment]
@jrieken added an option to disable word completion (coming in 1.2.0, `editor.wordBasedSuggestions`). You can also disable auto suggestion via `editor.quickSuggestions`.

I also cannot reproduce the initial report of `E` being inserted automatically. Does this happen with other software on your machine (e.g. Chrome?).
