### ISSUE TITLE
Extension which uses proposed API yet is not allowed to, can still contribute global commands

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#71650]
1. Have an extension which has a global command and uses proposed API and declares it in `package.json` using `"enableProposedApi": true`
2. Load that without allowing it to use proposed API

The global command still shows up in the command palette.

cc @aeschli

**Comment by jrieken** [comment]
Sure - the implementation checks only against use of proposed api not against the use of any API or static contribution. E.g. you can declare the use of proposed API but not use any and that's OK. @joaomoreno I don't understand the issue here?
