### ISSUE TITLE
Git stash 3 dot menu doesn't work

### ISSUE THREAD

**Issue by Kontik** [Microsoft/vscode#71657]
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. Try to stash any changes via 3 dot menu on Source Control layer
2. Error occured (see screenshots)

![Screenshot_147](https://user-images.githubusercontent.com/1705730/55479549-ff17b300-5626-11e9-9ec2-be4e24c7dc82.png)
![Screenshot_145](https://user-images.githubusercontent.com/1705730/55479447-c8da3380-5626-11e9-80cb-554802ba7aa7.png)
![Screenshot_146](https://user-images.githubusercontent.com/1705730/55479452-cd9ee780-5626-11e9-899b-0818bbf14bd1.png)

**Comment by jaqra** [comment]
@Kontik what is your git version?
`git stash push` command introduced in 2.13.x version.

I will send a PR to fix that

**Comment by jaqra** [comment]
@joaomoreno can i send a PR that change `git stash push` command to `git stash save`.

There is just one rule that stash message can not be start with minus (-).

Its working well otherwise.

It is ready to send if you accept.

**Comment by joaomoreno** [comment]
Please update to the latest git version.
