### ISSUE TITLE
The selected item formatter for the vue file is not currently installed

### ISSUE THREAD

**Issue by mikepxq** [Microsoft/vscode#71656]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by octref** [comment]
Check your user settings for something like:

```
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  }
```

And make sure the formatter extension is installed and enabled.
