### ISSUE TITLE
'Analyzing in background' freezes with 100% CPU usage

### ISSUE THREAD

**Issue by qrx** [Microsoft/vscode#71659]
Issue Type: <b>Bug</b>

As soon as I open VSC the analysis starts, then it stays on 'Analyzing in background, 1523 items left...'. The number of items left does not decrease and the CPU is locked to 100%

If I wait hours later the CPU is still pegged at maximum usage.

This happens even when the most basic code is open (helloworld.py).
I'm using python 3.7.2 64-bit

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.3.6352

</details>

**Comment by mjbvz** [comment]
Please file this against the python extension

**Comment by xialeizhou** [comment]
+1
