### ISSUE TITLE
Add new display language

### ISSUE THREAD

**Issue by pashmak73** [microsoft/vscode#71668]
Hi,
I would like to see Visual Studio Code in Persian language.

I want to translate it to Persian language.
Any idea how can I do this?

Thanks.

**Comment by dbaeumer** [comment]
Besides the translation there is the fact that Persian is a RTL writing system.

**Comment by pashmak73** [comment]
I know, and I think it should add an option for RTL languages like Persian.

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. 
New request to enable language in MLCP should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)

**Comment by danyeh** [comment]
Close this issue as the reasons stated above.
