### ISSUE TITLE
Snippet choice incorrectly selected

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#71661]
In [vscode-xml](https://github.com/angelozerr/lsp4xml/pull/334#issuecomment-477763373), we have a completion item that returns an attribute and its values as a list of choices. The 1st choice (UTF-8) is displayed as default value, as expected. However, the choices are ordered differently and the 1st item (ISO-8859-1), which is selected is no longer the displayed default value. Since ISO-8859-1 is the selected choice, it eventually gets inserted when you hit tab. So to recap:
- server returns textedit with `"newText": "encoding=\"${1|UTF-8,ISO-8859-1,Windows-1251,Windows-1252,Shift JIS,GB2312,EUC-KR|}\"$0"`
- UTF-8 is pre-inserted
- UI displays reordered list as ISO-8859-1,UTF-8,Windows-1251,Windows-1252,Shift JIS,GB2312,EUC-KR, selecting ISO-8859-1

```
[Trace - 9:56:06 AM] Received response 'textDocument/completion - (318)' in 4ms.
Result: {
    "isIncomplete": false,
    "items": [
        {
            "label": "encoding",
            "kind": 11,
            "documentation": {
                "kind": "markdown"
            },
            "filterText": "encoding",
            "insertTextFormat": 2,
            "textEdit": {
                "range": {
                    "start": {
                        "line": 0,
                        "character": 20
                    },
                    "end": {
                        "line": 0,
                        "character": 25
                    }
                },
                "newText": "encoding=\"${1|UTF-8,ISO-8859-1,Windows-1251,Windows-1252,Shift JIS,GB2312,EUC-KR|}\"$0"
            }
        }
    ]
}
```
![snippet-choice](https://user-images.githubusercontent.com/148698/55485690-ee504880-55f8-11e9-8790-08290b7bd2d9.gif)

So I would expect the UI to keep the initial choice order.

Does this issue occur when all extensions are disabled?: Maybe

**Comment by MrTango** [comment]
I just hit the same problem:

![vs-code-snippets-choice-bug](https://user-images.githubusercontent.com/1113628/55962703-18011380-5c7a-11e9-8859-d54cc13ebaa0.gif)

The first value in the list is True and the second is False, but when using the snippet it's showing them in wrong order and only by tab-ing thru the options on eswitches every choice to False.
