### ISSUE TITLE
Suggestion: Add text to help get started debugging

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#71664]
Most of the built in viewlets have some sort of information that tells you what to do with it.  If no folder is open in the Workbench, the Explorer has a big button to open a folder.  The Search viewlet has a Search input box.  Extensions shows a list of extensions.

The Debug viewlet is empty. We could have a simple prompt to help people get started by pressing `F5` or configuring `launch.json`.

![image](https://user-images.githubusercontent.com/1487073/55496575-45075380-55f4-11e9-8822-949be95ec0eb.png)

**Comment by misolori** [comment]
Yea, I agree we need a better empty state to help users get started. I already created https://github.com/Microsoft/vscode/issues/56391 to track this, so I'll add your screenshot as a suggestion.
