### ISSUE TITLE
registerCompletionItemProvider not trigger `@` char in less.

### ISSUE THREAD

**Issue by ycjcl868** [Microsoft/vscode#71662]
![image](https://user-images.githubusercontent.com/13595509/55491415-04492200-5668-11e9-90a4-ed1929b22aef.png)

-------------

![image](https://user-images.githubusercontent.com/13595509/55491503-293d9500-5668-11e9-89c1-875767f94ad1.png)

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/55519106-59b30e00-562b-11e9-91d1-81b2847f62de.png)

```ts
import * as vscode from 'vscode'

export function activate(context: vscode.ExtensionContext) {
  vscode.languages.registerCompletionItemProvider({
    scheme: 'file',
    language: 'less',
  }, {
    provideCompletionItems() {
      return [{
        label: '@test'
      }];
    }
  }, '@')
}
```

If you try to return `label: 'test'`, nothing will show up. Your completion item needs to include the trigger character.
