### ISSUE TITLE
Intelli-Sense for MicroPython

### ISSUE THREAD

**Issue by koldomon** [Microsoft/vscode#71667]
Issue Type: <b>Feature Request</b>

I want to use Visual Studio Code to develop MicroPython on a ESP8266. But I'm really new to Python. I installed VSCode on Linux Mint19.1 (working fine), installed the Extenions "MicroPython IDE" and "Pymakr" (both are working fine), but when I'm writing Code, there is no code-completion for some modules and "machine" is always marked with "unresolved import". Then I cloned the github repo from micropython and "linked" it in my settings.json ("python.autoComplete.extraPaths": ["/home/me/src/micropython/ports/esp8266", "/home/me/src/micropython/drivers"]). With that extrapath i get most module with code-completion and all the nice intellisense features, but not for "machine" or "network". And I'm stuck at this point. I already tried to get some help in the micropython forum but had no success.

what i want to do: build some nice IOT devices with micropython
what i am actually doing: trying to get the environment working

I'm a developer for VB.NET for years and I know to ask "the right" people if you have a problem. So PLEASE can some of you amazing people spend a few hours to support micropython in visual studio code. PLEASE PLEASE PLEASE

greetings Markus

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

**Comment by mjbvz** [comment]
Please start by filing an issue against the python extension

**Comment by koldomon** [comment]
the python extension is part of vs code (
vscode/extensions/python). 

so where should i fill an issue?

**Comment by mjbvz** [comment]
https://github.com/Microsoft/vscode-python/issues

**Comment by koldomon** [comment]
thank you :-)
