### ISSUE TITLE
node.js intellisense not working

### ISSUE THREAD

**Issue by melozzo** [Microsoft/vscode#71665]
Issue Type: <b>Bug</b>

4 line server.js file doesnt have intellisense for node 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Please share some example code + steps to reproduce the issue

/needsMoreInfo

**Comment by byronmejia** [comment]
Sounds more linked to #71658 

Our whole office has now witnessed intellisense hanging in a regular typescript project.
Would I be correct in assuming you mean intellisense is trying, but never completing?

**Comment by mjbvz** [comment]
Closing as more info is needed from original poster
