### ISSUE TITLE
Offer theme colors for text foreground in diff editor

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71663]
Abyss:

![image](https://user-images.githubusercontent.com/4033249/55495765-78e17980-55f2-11e9-9da5-ba83ea8e7303.png)

Monokai:

![image](https://user-images.githubusercontent.com/4033249/55495837-9f071980-55f2-11e9-9b95-ef9f9fade285.png)

The low color contrast makes the text hardly readable. Also an issue for Nord.

https://github.com/arcticicestudio/nord-visual-studio-code/issues/14#issuecomment-479325318

It would be great if theme authors could say, in the diff added/removed region, use a different foreground than the normal foreground to avoid contrast issues.

**Comment by aeschli** [comment]
But then you would lose syntax highlighting for the diff regions. 

IMO it's up the themes to find good diff background colors that go well with the token colors. It's the same for all other background colors in the editor (selection, ...)

**Comment by aeschli** [comment]
In order to replace all tokens with a foreground color the diff view has to create an annotation with that color. It would only do that when the color is defined.

I'd rather not go there, but expect themes to pick good colors (it's all under their control)

**Comment by octref** [comment]
I meant being able to say, for added/removed regions, use different colors for certain syntaxes. For example,

```
    {
      "name": "Comment",
      "scope": "comment",
      "settings": {
        "foreground": "#616E88",
        "git.added.foreground": "<Color good for the green>",
        "git.removed.foreground": "<Color good for the red>",
      }
```

**Comment by octref** [comment]
@aeschli Can we reopen this as a feature request?

**Comment by aeschli** [comment]
We can open it to collect votes, but given the complexity of the implementation (a layering issue, token colors are computed in vscode-textmate, the git decoration comes from an extension), I don't see a way this can become reality.
I'd rather have theme pick good colors.

**Comment by octref** [comment]
@aeschli @alexandrudima Is it possible to do this?

- Currently we have rules for `.mtk<n>` classes for different syntax tokens
- When the code is in diff region, add `.git-added` or `.git-removed` to the container
- The `.git-added .mtk<n>` and `.git-removed .mtk<n>` CSS rules would apply the colors

**Comment by arcticicestudio** [comment]
@aeschli I'm not familiar with the parsing/coloring architecture of VS Code so I can't make any statements how to solve this or how this would impact the performance. I know that I've spend many hours trying to find a color mix that keeps the balance between the theme ambience and the readability and it looks like it is almost impossible. There are many other themes with the same problem and all authors are helpless and limited regarding the design possibilities, e.g. see the discussion in https://github.com/arcticicestudio/nord-visual-studio-code/pull/105 (there are more closed issues).
Choosing a good color for the diff means on the other side it will completely change the ambience of the theme for all other views, e.g. using a darker and more saturated color for comment would help in the case of the Nord theme to make comment readable in diff-addition views, but would make them almost invisible in other views (dark foreground on dark background).

It would be really nice if this would be evaluated again to see if e.g. the solution from @octref can be used to solve this without impact on the performance. The changes only need to apply to the view/tab that gets opened when using the Git diff feature.

If this is also to much effort/performance impact I'd suggest to check if there is a way to invert all foreground colors when they are within the Git diff addition/remove scope. This would reflect the design of other editors like Vim (see [Nord Vim diff background feature](https://github.com/arcticicestudio/nord-vim/#uniform-diff-background) as example). Of course this should be made a opt-in with a setting key to allow users to only enable it when it fits their needs.

![](https://raw.githubusercontent.com/arcticicestudio/nord-vim/develop/assets/scrot-config-uniform-diff-default.png)
