### ISSUE TITLE
Completion sortText and preselect is ignored when typed identifier is an exact match with completion label

### ISSUE THREAD

**Issue by olafurpg** [Microsoft/vscode#71660]
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.2 (18C54)

Steps to Reproduce:

- run completion in the following Scala code  using the [Metals](https://marketplace.visualstudio.com/items?itemName=scalameta.metals) language server extension
```scala
  locally {
    val concurrentString = ""
    concurrent<COMPLETE>
  }
```
- language server returns the following (simplified) completion items

```json
[
    {
      "label": "concurrentString: String",
      "preselect": true,
      "sortText": "00000"
    },
    {
      "label": "concurrent",
      "sortText": "00001"
    }
  ]
```
- I expected the `concurrentString` item to be pre-selected and appear at the top of the completion results
- VS Code pre-selects the `concurrent` result even if it has a lower `sortText` 
<img width="329" alt="Screenshot 2019-04-03 at 15 49 40" src="https://user-images.githubusercontent.com/1408093/55484385-af39eb80-5628-11e9-992e-7766490bd91a.png">

Even if `concurrent` is an exact match with the typed identifier, I think it's undesirable to move it to the top because
- the language server has semantic understanding about the program and knows that the local variable `concurrentString` is more likely to be selected
- since I have already typed `concurrent` in the code, I don't save keystrokes by selecting `concurrent`. 

Does this issue occur when all extensions are disabled?: No, you need the Metals language server extension.

**Comment by olafurpg** [comment]
I'm experiencing a similar issue where `sortText` is ignored even when the typed identifier is not an exact match with the label/filterText

<img width="830" alt="Screenshot 2019-04-03 at 20 47 10" src="https://user-images.githubusercontent.com/1408093/55504802-e670c280-5651-11e9-92dc-3a08f8459cbb.png">

I expected the order to be [`intNumber`, `toInt`, `instance`] because in the returned completion list because `toInt` has a lower sortText than `instance`

```json
[
  {
    "label": "intNumber: Int",
    "preselect": true,
    "sortText": "00000",
    "filterText": "intNumber"
  },
  {
    "label": "toInt: Int",
    "sortText": "00001",
    "filterText": "toInt"
  },
  {
    "label": "instance: Int",
    "sortText": "00002",
    "filterText": "instance"
  },
  {
    "label": "asInstanceOf[T0]: T0",
    "sortText": "00003",
    "filterText": "asInstanceOf"
  },
  {
    "label": "isInstanceOf[T0]: Boolean",
    "sortText": "00004",
    "filterText": "isInstanceOf"
  }
]
```

**Comment by jrieken** [comment]
Yes, that's the design and honestly unlikely to change. The match-score with the current prefix (which the user typed) is stronger than the preselect property that the language brain computed. Only with equal scores, preselect comes to play.  The reasoning is that user-input is worth more and I still think that's a good idea.

**Comment by jrieken** [comment]
Commenting on the other question here: the same is true for sort text, that's used for the initial (prefix-less) sorting and to resolve score-conflicts but not to overrule user-input.

**Comment by olafurpg** [comment]
Thank you for the explanation. I agree the current behavior is a good default.

Would it be possible to introduce an option similar to `editor.suggestSelection` to disable the match-score based on the current prefix? For example `editor.completionSort = "prefix-match-score" | "sort-text"`. In our extension, we can overwrite that setting for the Scala language while keeping the default for other languages.

In the examples above, I hadn't typed additional characters after triggering the completion so the language server sees the same user-input as VS Code.

Either way, I'm fine closing this ticket with "working as intended". This is not a critical issue, the completion experience in VS Code is already one of the best I have experienced 👏

**Comment by olafurpg** [comment]
Closing since this is unlikely to change, thank you for the explanation!

**Comment by jrieken** [comment]
Alright, there is an issue which is about disabling fuzzy scoring and using something more 'traditional' like prefix match. I didn't find it right away but that then might be interesting for you
