### ISSUE TITLE
Category for Extensions

### ISSUE THREAD

**Issue by kaanoo2904** [Microsoft/vscode#7166]
It would be really greate if you guys can add some categorys, filters , or if better - something like "extension store" page right inside VS Code. It's better when themes, snippets, and language supports ... get their own place.

something like editor Atom.
![Extension Store](http://www.noupe.com/wp-content/uploads/2015/01/die-einstellungen-von-atom.jpg)

Btw, really good job done guys :+1:

**Comment by joaomoreno** [comment]
#637
