### ISSUE TITLE
Not responding if opening big js.map files

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/vscode#7167]
I noticed big lag and crashes if opening big files like js.map.
![not-responding](https://cloud.githubusercontent.com/assets/3028012/15770911/91b2ed0c-296f-11e6-8e71-ddedcce3132d.png).

- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open any big js.map file, for example angular.min.js.map
2. vscode will start doing some big work and stop working.

**Comment by alexandrudima** [comment]
@Anjmao I cannot reproduce in 1.2.0. I have pushed a couple of fixes to target long lines in 1.2.0. Would you mind trying out [the insiders build](https://code.visualstudio.com/insiders) and checking if it reproduces there?

**Comment by alexandrudima** [comment]
Just tried again and it works for me.

Verification steps:
npm install angular
open angular.min.js
