### ISSUE TITLE
Некорректное отображение значка Seti в коде

### ISSUE THREAD

**Issue by bossonojka** [Microsoft/vscode#71679]
Issue Type: <b>Bug</b>

При изменении размера шрифта в параметрах Visual Studio Code, следующий значок в коде отображается некорректно (его размер слишком большой):

![image](https://user-images.githubusercontent.com/36764653/55511301-ed56ff80-5668-11e9-8f72-45b7a3a9ae03.png)
![image](https://user-images.githubusercontent.com/36764653/55511384-23947f00-5669-11e9-97bc-d28b6cf40657.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
> When you change the font size in the Visual Studio Code settings, the following icon in the code appears incorrectly (its size is too large)

**Comment by jrieken** [comment]
Please file issues in English. Thanks!
