### ISSUE TITLE
Debug adapter exits at startup or is unable to start but debug session is not terminated.

### ISSUE THREAD

**Issue by ivanhernandez13** [Microsoft/vscode#71671]
- VSCode Version: 1.32.3 
- OS Version: macOS 10.14.3 

Steps to Reproduce:

1. clone [vscode-mock-debug](https://github.com/Microsoft/vscode-mock-debug) 
2. Open vscode-mock-debug in vscode
3. Modify contributes.debuggers.program in package.json to something invalid such as "./invalid/file.js".
4. Install node modules and compile.
5. Launch the extension with debugging
6. Select "Add Configuration..." in the Debug view and select "Mock Debug" to create the default launch.json.
7. Start a debug session with the "Ask for file name" configuration.
8. Give it any file name and observe as the debug adapter fails to start.
9. Try to start a debug session again with the "Ask for file name" configuration. 

This fails with the error 'There is already a debug configuration "Ask for file name" running.'
I would expect the session with that configuration to have been terminated when the debug adapter failed to launch. I also couldn't find a way to manually terminate the session since the debugging toolbar disappears after the debug adapter fails to start.

I am using a c++ program as my debug adapter and the same thing occurs even when the program file does exist but the process terminates at startup for whatever reason.

**Comment by isidorn** [comment]
Thanks a lot of nice steps.
However I fixed an issue similar to this one and can you please first try to reproduce with vscode insiders https://code.visualstudio.com/insiders/
Or wait a couple of days so we release a new stable?

If you still see it please let me know and I will follow your exact steps. Thanks!

**Comment by ivanhernandez13** [comment]
Thanks for your response. I was able to reproduce this issue with Code - Insiders.

**Comment by aeschli** [comment]
Verified that 'There is already a debug configuration "Ask for file name" running.' no longer shows. That means the previous, invalid debug adapter terminated
