### ISSUE TITLE
Task output does not show in VSCode (but is working in insiders)

### ISSUE THREAD

**Issue by jasonwilliams** [Microsoft/vscode#71670]
- VSCode Version:
- OS Version: 1.32.3

Steps to Reproduce:

1. Checkout https://github.com/jasonwilliams/boa
2. Install the Rust-RLS plugin
3. hit ctrl+b to build

**Does this issue occur when all extensions are disabled?:**  Yes
code-insiders still shows output with extensions disabled

Expected behaviour (insiders - 1.33.0-insider)
This is me hitting ctrl+b
![insiders](https://user-images.githubusercontent.com/936006/55501963-7ce9b780-5643-11e9-85b5-05222243deba.gif)

Actual Behaviour (Stable 1.32.3)
![code](https://user-images.githubusercontent.com/936006/55502066-a73b7500-5643-11e9-9e65-81c9953523af.gif)

**Comment by alexr00** [comment]
Another instance of #45693. If you scroll up most of your task output will be there.

**Comment by jasonwilliams** [comment]
@alexr00 why did you close the issue? I scrolled up there's nothing there.
And the issue you linked was closed last year

**Comment by jasonwilliams** [comment]
@alexr00 on stable when my terminal is high enough, the output is printed out, but only once its a certain size. Is this part of the same issue?

**Comment by alexr00** [comment]
The issue I linked to is closed because it is fixed if you have a new enough version of Windows. If you have a version of Windows that is older, then you will still see the issue. That issue is the cause of almost all terminal weirdness on Windows.
