### ISSUE TITLE
Re-use existing editor tab from unfocused editor group when hitting a breakpoint

### ISSUE THREAD

**Issue by jarrodldavis** [Microsoft/vscode#71672]
Issue Type: <b>Feature Request</b>

Currently, when a breakpoint is hit in a file open in an unfocused tab from an unfocused editor group, VS Code creates a new tab for that file in the currently focused editor group. Instead, it should re-use the existing tab and move focus to it.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

Here is a screen recording illustrating the issue:

https://jmp.sh/gbienyu

**Comment by isidorn** [comment]
This makes sense imho, however the `editorService.openEditor` needs to support that option.
Currently it has SIDE_GROUP and ACTIVE_GROUP. It seems it should also have GROUP_THAT_CONTAINS_EDITOR or something like that.
@bpasero or is there already something like that?

**Comment by bpasero** [comment]
@isidorn [`IEditorOptions.revealIfVisible`](https://github.com/Microsoft/vscode/blob/e1cf956/src/vs/platform/editor/common/editor.ts#L87) | [`IEditorOptions.revealIfOpened`](https://github.com/Microsoft/vscode/blob/e1cf956/src/vs/platform/editor/common/editor.ts#L94)
