### ISSUE TITLE
package.json crashes VS Code

### ISSUE THREAD

**Issue by eduardoRoth** [Microsoft/vscode#71674]
Issue Type: <b>Bug</b>

1. Create a new Nx Workspace
2. Open it
3. VS Code will keep refreshing itself

Remove `package.json` (or just change it's extension) and issue will disappear.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|sensa-control/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
dart-code|Dar|2.25.0
githistory|don|0.4.6
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.5.1
Angular2|joh|7.0.1
theme-karyfoundation-themes|kar|18.2.1
vscode-azureappservice|ms-|0.13.0
azure-account|ms-|0.8.1
csharp|ms-|1.18.0
vsliveshare|ms-|1.0.18
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
sass-indented|rob|1.5.1
vsfire|tob|1.4.1
vscode-icons|vsc|8.4.0
propertylist|zho|0.0.2

(4 theme extensions excluded)

</details>

**Comment by eduardoRoth** [comment]
## **package.json**
```
{
  "name": "project-name",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "affected": "./node_modules/.bin/nx affected",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help"
  },
  "private": true,
  "dependencies": {
    "@nestjs/common": "5.5.0",
    "@nestjs/core": "5.5.0",
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "ts-jest": "24.0.0",
    "@nestjs/schematics": "5.11.2",
    "@nestjs/testing": "5.5.0",
    "jest-preset-angular": "7.0.0",
    "@nrwl/builders": "7.7.2",
    "jest": "24.1.0",
    "@types/jest": "24.0.9",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "^7.0.0",
    "@angular-devkit/build-angular": "~0.13.0",
    "codelyzer": "~4.5.0",
    "cypress": "3.1.0",
    "@types/jquery": "3.3.6",
    "@angular/cli": "7.3.1",
    "@nrwl/schematics": "7.7.2",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.2.2",
    "prettier": "1.15.2"
  }
}

```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by eduardoRoth** [comment]
@mjbvz No, it doesn't happen.

I'm clean installing VS Code again to see if the issue is still present.

**Comment by eduardoRoth** [comment]
The problem is with `vscode-icons-team.vscode-icons` package, it reloads to show icons but something is happening that it keeps reloading VS Code.

**Comment by mjbvz** [comment]
Thanks for tracking that down. Please file an issue against that extension instead
