### ISSUE TITLE
Toggle Screencast Mode show wrong title on Traditional Chinese version

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vscode#71673]
- VSCode Version: `1.32.3`
- OS Version: `Windows_NT x64 10.0.17763`

Steps to Reproduce:

1. Open VSCode
2. Hit `F1`
3. Search `toggle`, then you will see **Developer: Toggle Mouse Clicks*** on the list.

![image](https://user-images.githubusercontent.com/88981/55505896-b5f74b80-5686-11e9-9fa0-4d94f08ab385.png)

The function is correct.  The translation is correct. ( translation to  **Developer: Toggle Screencast Mode** ).  But the **English** part of this item is **wrong**.  The right text should be **Developer: Toggle Screencast Mode**.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by anemology** [comment]
Also found the key typo in i18n.json. But I don't know how to fix it, anyone can help? Thanks.

https://github.com/Microsoft/vscode/blob/2937cb0baa742db4094f810e4a59cbaf7ad02db7/src/vs/workbench/electron-browser/actions/developerActions.ts#L115

https://github.com/Microsoft/vscode-loc/blob/94a7bfabcf0239d89aa9879fb7964670b483b953/i18n/vscode-language-pack-zh-hant/translations/main.i18n.json#L1913

**Comment by johnliu2016** [comment]
Hi @dbaeumer, can you take a look please? The ask seems about updating the key, translation is correct as is.

**Comment by dbaeumer** [comment]
@joaomoreno if I remember correctly you introduced that action. Right?

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/82a03daef25d3a33bd8007d8c8bd5f6f917f44e2
