### ISSUE TITLE
Can't open methods after debugging

### ISSUE THREAD

**Issue by Sparksss** [Microsoft/vscode#71677]
Hello. 
I have a problem with my _VS Code_ every time after i debbuging **node.js**, stop debug and close it, i see invoke methods and after click on method can't move to current method. I see infinity loading in upper.

1. Open a project
2. Open debuging
3. Set a breakpoint
4. Start debug
5. end debug, end stop it
6. click left button mouse to any place where method is invoked
7. See the results

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders?
https://code.visualstudio.com/insiders/

If yes please provide exact reproducable steps with a repository which you can put on github

**Comment by Sparksss** [comment]
Thanks for the link, while is the same problem not repeated with a new version, if a problem will be repeated I write a message. thanks.

**Comment by isidorn** [comment]
Ok. So you can not reproduce with insiders. Thus closing this issue
If you see it with insiders let us know and we will reopen
