### ISSUE TITLE
Source control Keyboard shortcut on Mac

### ISSUE THREAD

**Issue by arturogh** [Microsoft/vscode#71687]
Issue Type: <b>Bug</b>

On a Mac, left nav items should have the same base (CMD + shift) for example. The shortcut for switching to Source control uses control instead of cmd (unlike Explorer) in the left nav.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|72, 41, 37|
|Memory (System)|16.00GB (1.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
htmltagwrap|bra|0.0.7
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.8.2
xcs-react-snippets|edu|0.1.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
vscode-flatland-icon-theme|geb|0.0.6
path-autocomplete|ion|1.13.2
vscode-styled-components|jpo|0.0.26
better-line-select|kai|1.0.1
vscode-simple-icons|Lau|1.11.2
vscode-azureappservice|ms-|0.13.0
atom-keybindings|ms-|3.0.6
azure-account|ms-|0.8.0
vsliveshare|ms-|1.0.18
team|ms-|1.149.2
color-highlight|nau|2.3.0
vscode-jest|Ort|2.9.2
vscode-framerx-code-snippets|pix|0.0.61
material-icon-theme|PKi|3.7.0
esdoc-mdn|sam|0.8.0
markdown-preview-enhanced|shd|0.3.13
mdx|sil|0.1.0
vscode-fileutils|sle|2.13.5
ayu|tea|0.18.0
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|2.2.0

(12 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
This is why we have customized keyboard shortcuts, feel free to change it to whatever you please.

**Comment by misolori** [comment]
@joaomoreno I think this a valid question, why is the SCM shortcut different than the rest? I would expect all of them to be consistent.

![image](https://user-images.githubusercontent.com/35271042/55773025-b192b000-5a43-11e9-81d5-6521ed541330.png)

**Comment by joaomoreno** [comment]
Just follow the rabbit trail, but be careful... it's a never-ending road: https://github.com/Microsoft/vscode/blob/568844820882d987c74f2bfcd0b9e705b75771aa/src/vs/editor/contrib/find/findController.ts#L542 :see_no_evil:
