### ISSUE TITLE
add option to open folder in VSCode from the explorer

### ISSUE THREAD

**Issue by aster94** [Microsoft/vscode#71681]
I looked for duplicates but i didn't find any

I think that an option to open a folder or file directly in VSCode from the explorer would be usefull

during installation the user could be asked if he wants to add it to the right click menu

now to open a folder in vscode you should:
1. open vscode
2. from file > open folder
3. choose the folder you wish to open

doing directly from the explorer would be very useful, like it is possible with other programs, example for Visul Studio:
![img](https://user-images.githubusercontent.com/21184718/55514289-f72c3300-5667-11e9-970b-de204a019cec.png)

**Comment by joaomoreno** [comment]
> during installation the user could be asked if he wants to add it to the right click menu

This already exists in the current Installer.

**Comment by aster94** [comment]
okkk maybe i installed vscode before the option was there
