### ISSUE TITLE
workbench.action.debug.selectandrun

### ISSUE THREAD

**Issue by jamesstidard** [microsoft/vscode#71682]
I prefer to run my configurations using the 'workbench.action.debug.selectandstart' command - which I've assigned to a keyboard shortcut. 

I also want to be able to bind the complimentary one which I can use to run my code not in debug i.e. a 'workbench.action.debug.selectandrun'.

Would appreciate someone taking the time to add this or pointing me in the direction where I could add it myself.

Thanks.

**Comment by isidorn** [comment]
Leaving this open as a feature request.
We will not add it just yet, let's try to get more feedback on this one.
