### ISSUE TITLE
Cursor is zoomed when using recording/meeting software like Zoom and ScreenFlow

### ISSUE THREAD

**Issue by kentcdodds** [microsoft/vscode#71684]
- VSCode Version: latest
- OS Version: macOS latest

Steps to Reproduce:

1. Record your screen with ScreenFlow or Zoom
2. Notice the recording has the cursor huge

This happens to everyone I've seen who has tried it.

It even happens in CodeSandbox.io with the VSCode editor experience enabled.

See the gifs here: https://twitter.com/kentcdodds/status/1113160739114455040

**Comment by rebornix** [comment]
I can reproduce with

* rMBP's retina screen, vscode on the left and focused, browser on the right

I can't reproduce with

* rMBP's retina screen, monaco editor playground https://microsoft.github.io/monaco-editor/index.html
* External monitor (non-4k), any setup

Is it possible (IMO very likely) that this is a feature of Screenflow or Zoom, where it enlarges the cursor when necessary?

**Comment by kentcdodds** [comment]
Highly unlikely I think. I don't see why it would only apply it to vscode based editors...

**Comment by auchenberg** [comment]
Notes from debugging:
VS Code codebase specific
Not electron specific
	Repros in CodeSandbox
High DPI related issue
	Don't see it on regular DPI monitors
Not Monaco specific
	Not in playground
Chromium + webkit repo
	No gecko

**Comment by rebornix** [comment]
Debugged together with @auchenberg and nailed it down to `-webkit-image-set`.
