### ISSUE TITLE
Unpersisted webviews being kept around when editor restarts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#71688]
Issue Type: <b>Bug</b>

**Steps**
1. Run `Show release notes`
1. Reload window

**Bug**
Empty release notes tab still around after start

VS Code version: Code - Insiders 1.33.0-insider (4d1cb56a5b88248b1e0f38b9980f4a1bc8a6fb1a, 2019-04-03T08:11:05.447Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|-psn_0_19132990|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by mjbvz** [comment]
Fixed by 06dd68b4e1b4b3a2135095c4ad65de76cc742e35 in master

**Comment by rebornix** [comment]
Another way to verify:

* Open a description view for a pull request from GH PR extension
* Reload the window

**Comment by mjbvz** [comment]
Fixed in 1.33 branch with #71689
