### ISSUE TITLE
Detect VMs and show notification with tip to improve performance

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#71685]
Based on learnings from customer interviews it's clear that we have a segment of VS Code users who experience perf rendering issues when running inside VM's. The size of this segment is hard to quantify through telemetry, as we only seem to detect the used OS and version.

The perf issues seem to be caused by a lack of GPU acceleration, which is a known Chromium/Electron issue per https://github.com/electron/electron/issues/5755.

To educate our users about this I'm proposing the following:

**Proposal:**
1. Detect VS Code is running in a VM (Could `--status` be used?) 
2. If a VM host is detected, we show a notification with the wording `We detected that you are running VS Code inside a VM. This might affect the performance of VS Code.` with an action to `Read more`.
3. Read more would open our documentation in an external browser and point to a new doc, that will have a section about `--disable-gpu` and how it might improve perf for in particular Virtual Box users.

**Related links:**
- https://unix.stackexchange.com/questions/89714/easy-way-to-determine-virtualization-technology
- https://serverfault.com/questions/109154/how-do-i-know-if-im-working-on-a-virtual-machine-or-not

**Comment by bpasero** [comment]
Possibly blocked by: https://github.com/Microsoft/vscode/issues/15211

**Comment by jrieken** [comment]
> The size of this segment is hard to quantify through telemetry, as we only seem to detect the used OS and version

@auchenberg We do send a VM hint which is meant to be used for this. That is based off MAC dresses ranges used by VM vendors and should be a pretty good hint.

**Comment by auchenberg** [comment]
@jrieken Didn't know that. Looks promising, https://github.com/Microsoft/vscode/blob/65e55416c416a41a3522ebf8aaaa60bd81c1b52a/src/vs/platform/diagnostics/electron-main/diagnosticsService.ts#L69
