### ISSUE TITLE
Quick selection flash to wrong position

### ISSUE THREAD

**Issue by chenzhijie** [Microsoft/vscode#71696]
- VSCode Version: Version 1.32.3 (1.32.3) (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4)
- OS Version: macOs High Sierra Version 10.13.3

Steps to Reproduce:

1. Define a struct with some fields. Those fields have same prefix.
2. Access to one field with `.` expression of this struct
3. Access to next field by typing the prefix, then use shortcut (CMD+N) to choose 
4. Quick press `Enter` button to choose, the focus will flash to a wrong position, usually
the first one.

Here is a GIF image shows the issue:
![test2](https://user-images.githubusercontent.com/8435489/55523968-e0b0c680-56bd-11e9-96fa-a7780fc57a97.gif)
If the GIF image is not clear, here is the movie:
[test2.zip](https://github.com/Microsoft/vscode/files/3041361/test2.zip)

Does this issue occur when all extensions are disabled?: No (Only install Go and VIM extensions)

**Comment by mjbvz** [comment]
Please start by filing this issue against the Go extension: https://github.com/microsoft/vscode-go
