### ISSUE TITLE
File browse setting type and supporting UI

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#71691]
I searched for "settings file browse" and didn't get any likely hits, which greatly surprised me.
If this _is_ a duplicate this will at least serve as a cross reference for people framing the idea in these terms.

Currently settings can be of the following types: `{ array | Boolean | integer | null | number | object | string }`

I propose another type `filepath` which would display as a string with an ellipsis button that invokes a file open dialog.

The supporting properties for this can be cribbed from the WinForms FileOpen widget. In particular one needs to define a file mask list with friendly names, and an initial path.

Personally I would also support a qualifier that defines a root path outside which users are not allowed to browse but that's something requiring debate.

**Comment by roblourens** [comment]
Thanks for searching, I do have an issue for this here: https://github.com/Microsoft/vscode/issues/56834
