### ISSUE TITLE
扩展宿主出现问题，老是要重启

### ISSUE THREAD

**Issue by linzigangV** [Microsoft/vscode#71697]
Issue Type: <b>Bug</b>

luaide的扩展经常会出现重现

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (1.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
luaide|kan|0.7.5
vscode-language-pack-zh-hans|MS-|1.32.4
korofileheader|OBK|3.6.0

</details>

**Comment by mjbvz** [comment]
> There is a problem with the extended host and you always have to restart 

> luaide的扩展经常会出现重现

**Comment by linzigangV** [comment]
我觉得是新版vs code 与luaide不兼容的原因，因为我重新安装了上个版本的vscode并不会出现这个问题，一更新就会出现
