### ISSUE TITLE
TreeDataProvider shows error "Element with id is already registered"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode#71698]
Issue Type: <b>Bug</b>

We've noticed errors similar to the following when leveraging the `TreeDataProvider` in our extensions:
<img width="283" alt="Screen Shot 2019-04-03 at 7 29 51 PM" src="https://user-images.githubusercontent.com/11282622/55525831-7cebb680-5647-11e9-9238-6c65b4611b46.png">

I believe it's a race condition when refreshing and I've created a simple extension that you can clone in order to repro. Specifically, the 'ej/tree' branch:
https://github.com/EricJizbaMSFT/helloworldext/tree/ej/tree

In order to repro, right click on the "1" node and select "Hello world":
<img width="375" alt="Screen Shot 2019-04-03 at 7 29 12 PM" src="https://user-images.githubusercontent.com/11282622/55525893-bb817100-5647-11e9-9800-8d9aaec11cac.png">

This repros for me on both insiders and non-insiders.

VS Code version: Code - Insiders 1.33.0-insider (0ac111466ec925fd5ca180ab9893f51531e419b2, 2019-04-01T15:47:22.304Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.34GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|3.35.0
vscode-azurefunctions|ms-|0.16.0
python|ms-|2019.3.6352
azure-account|ms-|0.8.1
csharp|ms-|1.18.0
java|red|0.42.1
vscode-java-debug|vsc|0.17.0

</details>

**Comment by eamodio** [comment]
I see this a lot in GitLens too, but I haven't been able to pinpoint a scenario that always repro's it.

**Comment by eamodio** [comment]
I was really hoping that when the custom views adopted the new tree implementation this issue would go away -- but I still see it 😢

**Comment by sandy081** [comment]
@eamodio Can you please provide steps to repro it?

**Comment by EricJizbaMSFT** [comment]
@sandy081 I've confirmed it still repros with my original steps provided in the first comment above

<img width="306" alt="Screen Shot 2019-07-12 at 10 25 05 AM" src="https://user-images.githubusercontent.com/11282622/61139676-68615a80-a48f-11e9-8b72-306a2c972f45.png">

Version: 1.37.0-insider
Commit: 8fa811108f0f0524c473020ef57b6620f6c201e1
Date: 2019-07-12T09:17:10.495Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by mikepsinn** [comment]
I can reproduce with this project on:
OS: Windows 10
Node Version: v8.11.2
Xcode version: Not installed

- Clone [https://github.com/QuantiModo/quantimodo-android-chrome-ios-web-app](https://github.com/QuantiModo/quantimodo-android-chrome-ios-web-app)
- `yarn install`
- Install Gulp VSCode extension
- Click refresh button that appears here
![Screenshot_2](https://user-images.githubusercontent.com/2808553/61174151-0d4c6800-a562-11e9-8560-0e43652a368a.png)

Then I get 
`Element with id gulpfile.js:current git branch: develop is already registered`
and it doesn't show the gulp tasks. 

```
notificationsAlerts.ts:38 Error: Element with id gulpfile.js:current git branch: develop is already registered
	at p.createAndRegisterTreeNode (k:\Users\m_000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:488:50)
	at define.fetchChildrenNodes.a.asPromise.then.Promise.all.u.coalesce.map.a.asPromise.then.n (k:\Users\m_000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:486:763)
```
![Screenshot_3](https://user-images.githubusercontent.com/2808553/61174212-e9d5ed00-a562-11e9-926c-831dd3e3dcb2.png)

Any suggestions?

**Comment by nbransby** [comment]
Im getting this a lot too. Could I confirm if this error message was intended for the extension developer due to incorrect use of the vscode API or an internal assertion?

**Comment by alexr00** [comment]
I can repro with the original example from @EricJizbaMSFT (thank you for the concise example!). I'm looking into it.

**Comment by alexr00** [comment]
The example nicely shows that we don't do anything to prevent multiple tree refreshes from occurring at the same time. I've added refresh queuing. If you seen any odd tree behavior in the near future, it could be that this queuing broke some other timing.
