### ISSUE TITLE
Add Option to Show Border Around Window When Active

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#71690]
Haven't seen an option for this yet, but I generally use Visual Studio and VS Code together. I use the same color scheme and at times it can be difficult to differentiate the two when the windows overlap (generally I have one maximized in the background with one free floating in front of it). Visual Studio does have a border around the window that matches the status bars when it is active. I was wondering if an option could be added to VS Code to do something similar.

For comparison, the differences between active and inactive currently:

![frame](https://user-images.githubusercontent.com/42397654/55518418-f41e4c00-5641-11e9-91b9-e3592817e46e.png)

**Comment by Pomax** [comment]
This feels more like an application setting, similar to "where to dock the sidebar", not something that should be set per theme. Not having a border around the application in windows 10 in a definitely productivity detractor, as it becomes impossible to tell where what is VS Code and what is another application in a black-on-black or white-on-white situation.

**Comment by krisbox-git** [comment]
I experience same problem when working with android studio or Unreal and anything that the dark mode of windows 10 have enabled. I really miss VS Code with window borders when focused like any other apps have!

**Comment by bpasero** [comment]
@eamodio similar

**Comment by eamodio** [comment]
Closed in https://github.com/microsoft/vscode/pull/82781
