### ISSUE TITLE
Right click on line numbers selectes all line numbers

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#717]
- right click on a line number
- notice that all line numbers are now selected

![screen shot 2015-11-26 at 19 52 11](https://cloud.githubusercontent.com/assets/1926584/11429371/59cdceda-9477-11e5-9e0c-2a1b01b3d52f.png)

**Comment by alexandrudima** [comment]
@isidorn I cannot reproduce on windows

**Comment by isidorn** [comment]
Yes I see it on the mac all the time. I am in the office from Monday so I can show you

**Comment by pcgeek86** [comment]
I can reproduce on Mac OS X.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alexandrudima** [comment]
I can not reproduce this on the mac mini in the office

**Comment by isidorn** [comment]
I also can no longer repro this
