### ISSUE TITLE
Comment box issue

### ISSUE THREAD

**Issue by devrajjha91** [Microsoft/vscode#71703]
Issue Type: <b>Bug</b>

**After writing comment there are left character going to negative.**

- 
![bug](https://user-images.githubusercontent.com/47135426/55530315-3dfb4680-56c3-11e9-895d-2f12ca617f37.PNG)

**Comment by mflan48** [comment]
Hi, @bpasero, I would like to help with this issue. Do you have any recommendations as to where to start?

**Comment by bpasero** [comment]
@devrajjha91 hey any steps how you got there to reproduce?

**Comment by mflan48** [comment]
Hi, @bpasero, I was able to replicate it on my own copy of vscode. First, click on the smiley face in the status bar to open the feedback box. Then, select the "frowny face option". With this option selected, the character limit is 270. Write some message that meets the 270 character limit. Then, select the "smiley face option". This will cause the "-13 characters left" to appear.

**Comment by bpasero** [comment]
Thanks, I am willing to accept a reasonably small PR to fix this 👍

**Comment by ramank775** [comment]
Hi @bpasero , i have fixed this issue and created a pull request 
https://github.com/Microsoft/vscode/pull/71880.

This is my first contribution to open source, if i have miss anything please let me know.
