### ISSUE TITLE
Cursor jumps up a line after pressing enter with formatOnType=true

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vscode#71706]
X-post of https://github.com/PowerShell/vscode-powershell/issues/1786 since vscode-powershell did not seem to consider it theirs.

------

I am at the end of a comment line and wish to press enter and starting a new line of code.

I press enter. For a fraction of a second, everything is as it should be - the cursor is on the right place on the next line.

Then suddenly it is back on the previous line, and not even at the end of the line (2 characters offset, apparently).

If I start typing fast enough, it stays where it should. Otherwise, not.

If I press enter multiple times fast enough, it will still bump me back up to the original line.

The behavior does not reproduce with `formatOnType=false`.

Screen capture of issue happening: https://i.imgur.com/VNyj87I.gifv

My settings file:

```json
{
	"files.autoSave": "afterDelay",
	"editor.wordWrap": "on",
	"editor.tabSize": 4,
	"editor.wrappingIndent": "none",
	"editor.minimap.enabled": false,
	"editor.find.seedSearchStringFromSelection": false,
	"editor.find.autoFindInSelection": true,
	"editor.formatOnType": true,
	"editor.formatOnPaste": true,
	"files.trimTrailingWhitespace": true,
	"powershell.integratedConsole.showOnStartup": false,
    "eslint.enable": true,
    "git.confirmSync": false,
    "workbench.colorTheme": "Visual Studio Light",
	"plantuml.exportSubFolder": false,
	"plantuml.exportFormat": "png",
	"git.enableSmartCommit": true,
	"extensions.ignoreRecommendations": false,
	"window.zoomLevel": 0,
	"git.autofetch": true,
	"explorer.confirmDragAndDrop": false,
	"plantuml.jarArgs": [
		"-SfixCircleLabelOverlapping=true"
	],
	"workbench.startupEditor": "newUntitledFile",
	"team.showWelcomeMessage": false
}
```

Extension version: 1.11.0
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.88GB free)|
|Process Argv|--folder-uri file:///c%3A/Source/CmsTinkering.Configuration|
|Screen Reader|no|
|VM|0%|

</details>

----

Latest build tested on:

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
Please share the code snippet and the exact steps with us. Thanks

**Comment by sandersaares** [comment]
File attached. Press enter when cursor is at end of line 331.

Deleting random sections from the file seems to hide the problematic behavior. I was unable to determine any pattern.

[xx.zip](https://github.com/Microsoft/vscode/files/3072030/xx.zip)

**Comment by jrieken** [comment]
Tried with that file and PowerShell 1.12.0 and cannot reproduce. Please provide *minimal* steps that allow me to reproduce this, also make sure this isn't caused by something else in your installation

**Comment by sandersaares** [comment]
The only extension I have enabled is PowerShell (I also have PlantUML which is disabled). This occurs on multiple PCs. Windows 10. Not sure what else to try - there is some dependency on file contents, so attempting to minimize the file makes it magically work.

I have no useful additional input to provide at the moment. It reliably reproduces with that file for me. Do you have any specific ideas that I should try?

**Comment by jrieken** [comment]
> I have no useful additional input to provide at the moment. It reliably reproduces with that file for me. Do you have any specific ideas that I should try?

Can you try with latest insiders: https://code.visualstudio.com/insiders/ - we have fixed an issue with format on type recently...

If this still reproduces can you share the file with us?

**Comment by sandersaares** [comment]
I confirm issue does not reproduce on latest insiders build!
