### ISSUE TITLE
Listen for command events in the extensions API: onCommand/onCommandDidExecute

### ISSUE THREAD

**Issue by hedgerh** [Microsoft/vscode#71700]
I'm interested in creating an extension for macro recording, which has been a requested feature in VSCode since 2016. (https://github.com/Microsoft/vscode/issues/4490)

If the extension API exposed some way to listen for commands to be executed, I think I'd be able to do it.  Something along the lines of `onCommandDidExecute('*', (command) => {})` to subscribe to all commands being executed would be great.

 The onCommand event listener feature was requested back in 2017, but it seems that it was not a priority at the time. https://github.com/Microsoft/vscode/issues/1431

Any chance this could be revisited?

**Comment by hedgerh** [comment]
It looks like there's actually an `onWillExecuteCommand` event emitter in the commands service already.  Would it be possible to expose this?

https://github.com/Microsoft/vscode/blob/5fb0f1ead7c411dd678bcd96df70f452ba73c31b/src/vs/platform/commands/common/commands.ts#L21

**Comment by jrieken** [comment]
I have unlocked #1431 and I am closing this a duplicate
