### ISSUE TITLE
at the teminal tab, it should be added a button for rerun last task

### ISSUE THREAD

**Issue by amoxuk** [Microsoft/vscode#71704]
![捕获](https://user-images.githubusercontent.com/26641021/55531353-81ae7a00-56dc-11e9-9699-eee4cc128f27.PNG)

when i run a task, i want there is a butoon for rerun last task.
my task is a shell with some select param, so when i want to rerun last task , i need to select some words and use `ctrl+h` to select the task. but unfortunately, the popups gui is too slow.
if there is a button, the work will be enjoyed.

**Comment by alexr00** [comment]
Right now those buttons are only for terminal specific actions, not tasks. I think it would be confusing to have a bunch of terminal specific buttons and then have a single task specific button. The best way for you to easy use the rerun task command would be to make a keyboard shortcut for it.
