### ISSUE TITLE
Add touch mode

### ISSUE THREAD

**Issue by jolleekin** [microsoft/vscode#71702]
Issue Type: <b>Feature Request</b>

I use touch a lot an no external mouse, so it would be great if VS Code has a touch mode that optimizes the UI for touch (more spacing between items in the Welcome page, for example). One way to achieve this is to add a mouse/touch mode toggle similar to the one in MS Office apps.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

**Comment by misolori** [comment]
Thanks for the feedback. I think we'll be able to make things more touch-friendly, but having a dedicated "touch mode" with increased padding seems unlikely to happen in the short term. Closing this as `out-of-scope` and if we ever re-visit this in the future we'll re-open.
