### ISSUE TITLE
TypeScript syntax highlighting breaks for class methods returning a type ending in a digit

### ISSUE THREAD

**Issue by lostfictions** [Microsoft/vscode#7170]
This is a bit of a strange one. In the screenshot below, a class with two methods is declared. The first returns a `number` and has correct syntax highlighting. The second has an almost identical body but returns an `endsWithDigit1` (a type alias for `number`), which breaks highlighting for the method body.

(On a more practical level, I discovered this while trying write a method that returned a `Matrix4x4`, so it's definitely something that might happen in day-to-day use!)

![bug](https://cloud.githubusercontent.com/assets/567041/15771924/052546c4-293c-11e6-87cd-2afc663a68e0.png)

- VSCode Version: 1.1.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

The repro code in the screenshot above is as follows:

```typescript
type endsWithDigit1 = number

class Repro {
  normalMember() : number {

    const someDeclaration : (name : string) => string = (name) => 'hello there ' + name
    const myString = someDeclaration('human')
    let coolNumber = myString.length + 20
    var anotherCoolThing = {
      pigs: 6,
      rabbits: 29,
      horseName: 'Johnny'
    }
    
    console.log('this is how the syntax highlighting should look!')
    
    return 1
  }
  
  badHighlightingMember() : endsWithDigit1 {
    
    const someDeclaration : (name : string) => string = (name) => 'hello there ' + name
    const myString = someDeclaration('human')
    let coolNumber = myString.length + 20
    var anotherCoolThing = {
      pigs: 6,
      rabbits: 29,
      horseName: 'Johnny'
    }
    
    console.log('this has some highlighting but the colors are wrong')
    
    return 1
  }
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#188
