### ISSUE TITLE
Intellisense C++ parser got stuck at random files

### ISSUE THREAD

**Issue by whoozle** [Microsoft/vscode#71716]
Issue Type: <b>Bug</b>

c++ parser constantly freezes at some random points eating 100% cpu (could be in this state for days), and the only way to kill it is kill -9 (just kill, signal 15 is not working)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 5.0.3-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (32 x 3664)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|62.83GB (15.02GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
QML|bbe|1.0.0
vscode-markdownlint|Dav|0.25.1
vscode-clang|mit|0.2.3
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.10
cmake|twx|0.0.17
vscode-icons|vsc|8.4.0
swig-tpl|zha|0.0.6

</details>

**Comment by mjbvz** [comment]
Please file this against the c++ extension

**Comment by whoozle** [comment]
I have no idea where it is, sorry

**Comment by Tyriar** [comment]
@whoozle https://github.com/Microsoft/vscode-cpptools/issues
