### ISSUE TITLE
Feedback box description box character count

### ISSUE THREAD

**Issue by AthulNair** [Microsoft/vscode#71719]
Issue Type: <b>Bug</b>

The character count mismatch for happy and disappointed mode. for happy mode its showing 257 as max count where as for disappointed mode its showing 270. This is bug is blocking me from submitting feedback. Please resolve this ASAP.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
Positive feedback includes a hashtag
