### ISSUE TITLE
SIGWINCH caught when running a docker container in integrated terminal and sidebar is toggled

### ISSUE THREAD

**Issue by unlock21** [Microsoft/vscode#71728]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1.  Terminal Type: Powershell
2.  Start a docker container "docker run -i -t php:7.2-apache"
3. Focus on vs code editor window
4. Press CTRL+B to expand/hide sidebar or click on active icon to toggle state

Sidebar toggles as expected but container is picking up a SIGWINCH

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (5.68GB free)|
|Process Argv|--folder-uri file:///c%3A/VMSHARE/DOCKER/WebUtility|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|10.4.1
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|1.8.1
code-runner|for|0.9.7
powershell|ms-|1.12.0
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
vscode-yaml|red|0.4.0

</details>

**Comment by Tyriar** [comment]
You resized the panel which made the terminal resize smaller, that's where the SIGWINCH came from
