### ISSUE TITLE
Search should strip trailing space

### ISSUE THREAD

**Issue by chrisdmc** [Microsoft/vscode#71723]
- VSCode Version: 1.32.3
- OS Version: Windows 10 Pro 17763

I appreciate that this is probably intentional behaviour, but I would contend that rarely, if ever, are searches conducted where the user wants it to limit the results to only those with a trailing space (I'm referring specifically to the space character 0x20). Whitespace within the search term? Of course. But a trailing space character, seriously? Bear in mind that many, many searches are conducted on terms that have been copy/pasted, it's very easy to mistakenly include a trailing space, and not realize the results are incomplete. This is misleading.

Steps to Reproduce:

1. In the search box, enter a term with a trailing space.
2. Results are restricted to that term, including the space.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I disagree, it's absolutely a valid thing to search for. We should search for whatever the user types, not try to outsmart them.
