### ISSUE TITLE
creating user snippets

### ISSUE THREAD

**Issue by vammex** [Microsoft/vscode#71721]
Issue Type: <b>Feature Request</b>

recently i have asked about this, and the link https://code.visualstudio.com/docs/editor/userdefinedsnippets  is exactly what I wanted to learn. Unfortunately though, there is no explanation on the page about how-to make a snippet with regular formatting (indentation etc), despite the printscreens on the page show formatted snippets. But my snippets all are not formatted.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
> But my snippets all are not formatted.

Sorry, but I don't understand what you mean

**Comment by vammex** [comment]
> > But my snippets all are not formatted.
> 
> Sorry, but I don't understand what you mean

please look at screens, the indentation
![111](https://user-images.githubusercontent.com/19187347/55571231-cb638880-570d-11e9-901f-d93848831717.PNG)
![2222](https://user-images.githubusercontent.com/19187347/55571236-ce5e7900-570d-11e9-98d3-1a13d9e22e1b.PNG)

**Comment by jrieken** [comment]
I still don't understand? How about sharing the snippet? How about describing what it does and what it should do?

**Comment by vammex** [comment]
> I still don't understand? How about sharing the snippet? How about describing what it does and what it should do?

i cannot understand what is that not clear in my explanation. could you see that the first screen i sent includes not formatted for-loop code? "var element" should be indented with one tab, just like on the second screen. 
i can share a code if it may help:
"loop": {
    "prefix": "for",
    "body": [
      "for (var ${1:i} = 0; ${1:i} < ${2:array}.length; ${1:i}++) {",
        "var ${3:element} = ${2:array}[${1:i}];",
      "}"
    ],
    "description": "for loop"
  }

i don't see how i force my code lines to be intented though

**Comment by jrieken** [comment]
> i don't see how i force my code lines to be intented though

Did you try spaces or `\t`?

**Comment by vammex** [comment]
> > i don't see how i force my code lines to be intented though
> 
> Did you try spaces or `\t`?

wonderful, that what makes sense
"\tvar ${3:element} = ${2:array}[${1:i}];",

thanks a lot
