### ISSUE TITLE
Git checkout sometimes names the created directory "repository"

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#71722]
Issue Type: <b>Bug</b>

I apologize if this has been reported already - but searching for "git repository" is not very helpful.

I'm not sure how to reproduce this, as it happens very infrequently. But sometimes when cloning a git repo, VSCode fails to correctly name the resulting directory. Instead it falls back to "repository", "repository-1" and so on.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
toggle-excluded-files|eam|1.6.0
EditorConfig|Edi|0.13.0
RunOnSave|eme|0.0.18
vscode-test-explorer|hbe|2.9.1
vscode-language-pack-de|MS-|1.32.4
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.6.1
project-snippets|reb|0.5.0
java|red|0.42.1
vscode-coverage-gutters|rya|2.3.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by joaomoreno** [comment]
Here's where that happens:

https://github.com/Microsoft/vscode/blob/a62b16e130b259127ff23ac41c0ddf1a7c88183b/extensions/git/src/git.ts#L339

Code does its best to figure out a good name for the folder, given the repository's URL. If it can't do so, it calls it `repository`.

In order to fix this you have to provide the URL of the cloned repository which causes the issue.

**Comment by AlCalzone** [comment]
@joaomoreno It has happened with https://github.com/AlCalzone/node-zwave-js, but also other github repos. The weird thing is that it is not reproducible - it usually works, but fails sometimes. Maybe a timing issue?

**Comment by joaomoreno** [comment]
It can't really be a timing issue... Next time it happens, send me the full git log which shows in `Git: Show Git Output`.

**Comment by AlCalzone** [comment]
I haven't reproduced it yet, but I'll keep you posted.

**Comment by joaomoreno** [comment]
Let me know :+1:

**Comment by AlCalzone** [comment]
@joaomoreno It just happened again:
Repo URL: https://github.com/ioBroker/testing/
Notice the trailing slash, I think that causes the problem

The git output doesn't seem very helpful:
Suchen nach Git in: C:\Program Files\Git\cmd\git.exe
Verwenden von Git 2.21.0.windows.1 von C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: d:\repository-1
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

**Comment by AlCalzone** [comment]
Also happened on my 2nd try with another repo, also with a trailing slash in the URL -> it's reproducible.

**Comment by AlCalzone** [comment]
@joaomoreno I would provide a PR, but I'm not sure about the requirements, tests and so on. This should be fixable with a simple change:
```diff
- let baseFolderName = decodeURI(url).replace(/^.*\//, '').replace(/\.git$/, '') || 'repository';
+ let baseFolderName = decodeURI(url).replace(/\/$/, '').replace(/^.*\//, '').replace(/\.git$/, '') || 'repository';
```

Basically, removing the trailing slash before doing any more replacements.

**Comment by joaomoreno** [comment]
@AlCalzone Feel free to submit PR.

**Comment by AlCalzone** [comment]
@joaomoreno Is it enough if I just do the above change? Or does this need an additional test somewhere?

**Comment by joaomoreno** [comment]
It's enough! :+1:

**Comment by AlCalzone** [comment]
PR is up

**Comment by joaomoreno** [comment]
This has already been fixed.
