### ISSUE TITLE
Extension tests run test from other git branch

### ISSUE THREAD

**Issue by brianignacio5** [Microsoft/vscode#71720]
- VSCode Version: 1.32.3
- OS Version: MacOS Mojave 10.14.3

Steps to Reproduce:

1. Create an extension project using project generator `yo code` and create a typescript extension with git repository.
2. Save initial files in a initial commit in master.
3. Create a new branch with `git checkout -b branch-name`
4. Create a new test file in `branch-name` and commit it.
5. Go back to master branch
6. Run Extension tests. The tests from this new test file are shown in the master branch.

Shouldn't these tests being disabled in master ? (For example: if there are npm required in one branch tests, this would break test functionality in master) Is there any setting I should add to the test runner ? 

Couldn't find an issue related to this or information of how to configure vscode mocha test runner. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
When you do `git checkout master`, it doesn't clean your `out` folder so it contains the built test from `branch-name`. TS rebuild doesn't clean that folder either.
