### ISSUE TITLE
Fine grained PATH specification

### ISSUE THREAD

**Issue by bence42** [microsoft/vscode#71725]
Issue Type: <b>Feature Request</b>

Hi,

Currently the PATH can be specified for terminal.integrated.env, but this is used by all tasks and it is not used by the launch configurations. Launch configs use the PATH from system settings.

As a result, it is not possible to have have multiple compilers each in a different task. Also it is not possible to leave the Windows path unchanged and still be able to launch the executables or debug them, let alone launch it in various environment or debug them with different debugger versions. Currently these can only be done by setting up various batch scripts that do modify the PATH and do the rest, however debugging does not work this way.

So my request is that each process started by VS Code (tasks, launch config) shall have its own PATH config and launch the process using that PATH and only use the current system setting as a fallback.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
The current state of the world is that you define env separated for tasks, debug and terminal. Tasks can inherit the terminal environment but if you don't want that you can use `terminal.integrated.automationShell`. Please update vscode and try the latest version as many changes have come in during the last 7 months.
