### ISSUE TITLE
Ability to suppress dialogs that occur within vscode.debug.startDebugging

### ISSUE THREAD

**Issue by awschristou** [microsoft/vscode#71726]
We call `vscode.debug.startDebugging` with a dynamically generated DebugConfiguration object. When `vscode.debug.startDebugging` is called, the method can encounter scenarios that produce a modal dialog box. We'd like to have a mode that prevents any dialogs from showing up.

Motivation
* The dialog contains two buttons: "Cancel" and "Open launch.json".
  * "Open launch.json" is not relevant when calling code is providing a custom DebugConfiguration object. Users are unable to take action on this, which can be confusing as a user.
  * "Cancel" sends a message to users that nothing further will happen with their intent to debug. The calling code may wish to perform actions (for example, making the call again, or prompting the user for a next action), and encountering this dialog within a more extended flow could result in a jarring experience.

Possible approach:
* a option that, when passed into `startDebugging` would throw errors rather than show dialogs. The errors would use a common StartDebugError class to convey error codes & messages to the calling code. Calling code would have the flexibility to handle or surface the errors

**Comment by weinand** [comment]
@isidorn this request makes a lot of sense.
With the new "DebugSessionOptions" argument for "vscode.debug.startDebugging" this is in reach...
