### ISSUE TITLE
Can't Ctrl+Click in Python stack trace if path contains spaces

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#71730]
@haimat commented on [Thu Apr 04 2019](https://github.com/Microsoft/vscode-python/issues/5111)

## Environment data

- VS Code version: 1.32.3
- Extension version (available under the Extensions sidebar): 2019.3.6352
- OS and version: Ubuntu 18.04.2 LTS 
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a 
- Relevant/affected Python packages and their versions: n/a

## Expected behaviour

CTRL+Clicking on a file name in the stack trace within the built-in console should open that file and jump to the respective line number.

## Actual behaviour

This does only work if the file path does not contain a whitespace (blank). If thre is a blank, then holding CTRL does not underline the file name and clicking on it does nothing.

## Steps to reproduce:
1. Create a folder that has a blank character in it
2. Create a Python source file in that new folder
3. Add some code to that Python file that would lead to an exception
4. Run the new Python file from within VS Code
5. Check the stack trace in the console, try to CTRL+Click on a file name of the new Python script

**Comment by DonJayamanne** [comment]
Confirmed this is not a python extension issue.
User is running code in a terminal (i.e. nothing to do with the extension).

**Comment by pkostas1** [comment]
Hi I am a new contributor and would like to work on this if @weinand allows.  I am able to repro.

**Comment by isidorn** [comment]
PRs that fix this are welcome if they are not overly complicated.
Code pointer https://github.com/Microsoft/vscode/blob/26cebd0ce79f7632a1d9a82b2b4821007d732701/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L14

**Comment by haimat** [comment]
This is noit a severe bug, but still, it is quite annoying to encounter when running on Linux.
Why did you close it - don't see a need to fix?

**Comment by OM26SKBLT** [comment]
still doesn't work?
