### ISSUE TITLE
cannot create user data directory

### ISSUE THREAD

**Issue by gurubert** [Microsoft/vscode#71738]
- VSCode Version: code-insiders 4d1cb56a (109)
- OS Version: Ubuntu 18.04.2

Steps to Reproduce:

1. sudo snap install code-insiders --classic
2. 
    gurubert@kendrew:~/snap/code-insiders$ ls -l
    insgesamt 8
    drwxr-xr-x 2 gurubert gurubert 4096 Apr  4 22:01 109/
    drwxr-xr-x 2 gurubert gurubert 4096 Apr  4 22:01 common/
    lrwxrwxrwx 1 gurubert gurubert    3 Apr  4 22:01 current -> 109/

3. 
    gurubert@kendrew:~/snap/code-insiders$ code-insiders
    cannot create user data directory: /home/home/gurubert/snap/code-insiders/109: Permission denied`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kedstar99** [comment]
Just to confirm, are you certain you are trying to create a user directory as /home/home/gurubert?

**Comment by gurubert** [comment]
Yes, $HOME is /home/home/gurubert

The directory has been created fine but then it complains.

**Comment by Kedstar99** [comment]
Would you mind running some commands to verify if the issue is occurring with vscode?

If you run the following in a terminal what happens?
snap run --shell code-insiders
cd $SNAP_USER_DATA
pwd
touch foo
mkdir foo2
cd ..
mkdir foo3

Do all the commands work? I can perform them all without much issues on Kubuntu 18.10?

Also why are you adding directories there? They are mainly designed for config for various snaps. The classic flag in this case allows you to have directories wherever. If you want to hide it from other snaps, it would make more sense to add them as a hidden directory ie (.foo). These will be hidden to snaps too.

**Comment by gurubert** [comment]
To be clear: I have not added ~/.snap/code-insiders manually, this was created on first run.

$SNAP_USER_DATA is not set:

gurubert@kendrew:~$ echo $SNAP_USER_DATA

gurubert@kendrew:~$

Therefore your command examples do not make sense.

gurubert@kendrew:~$ snap run --shell code-insiders
cannot create user data directory: /home/home/gurubert/snap/code-insiders/112: Permission denied

I have now removed ~/snap and reran the commands:

gurubert@kendrew:~$ ls snap
ls: cannot access 'snap': No such file or directory
gurubert@kendrew:~$ snap run --shell code-insiders
cannot create user data directory: /home/home/gurubert/snap/code-insiders/112: Permission denied
gurubert@kendrew:~$ ls snap/
code-insiders/
gurubert@kendrew:~$ ls snap/code-insiders/
112/  common/  current@
gurubert@kendrew:~$ ls  -l snap/code-insiders/
total 8
drwxr-xr-x 2 gurubert gurubert 4096 Apr  6 19:38 112/
drwxr-xr-x 2 gurubert gurubert 4096 Apr  6 19:38 common/
lrwxrwxrwx 1 gurubert gurubert    3 Apr  6 19:38 current -> 112/

**Comment by Kedstar99** [comment]
I don't think this is a problem with anything vscode specifically.

It seems to me that something is seriously bugged with your snap installation.

My guess is that the /home/home is screwing something either apparmour or the SquashFS. 
It isn't anything to do with VSCode though as neither the yaml or electron-launcher changes those file permissions.

That and I am certainly not seeing the same behaviour on kubuntu 18.10/18.04.

Maybe post this on the snapcraft forums but it shouldn't be here.

**Comment by joaomoreno** [comment]
@Kedstar99 is right. I would post this around the Snapcraft forums. Let us know how it goes!
