### ISSUE TITLE
put marker filter into panel header

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#7174]
Instead of having a toggle button that reveal the filter widget we should just move into the panel header. That would make it not take extra space and still be easily discoverable.

<img width="1027" alt="screen shot 2016-06-03 at 10 13 52" src="https://cloud.githubusercontent.com/assets/1794099/15772900/33712628-2974-11e6-8034-91abb8a56197.png">

**Comment by jrieken** [comment]
@stevencl fyi

**Comment by sandy081** [comment]
duplicates #7147
