### ISSUE TITLE
flatpak release

### ISSUE THREAD

**Issue by mikelpr** [Microsoft/vscode#71747]
now that we've got a snap for vscode and is properly containerized (I suppose that'd be the reason to use it over the deb), it'd be good to have a flatpak for the rest of the systems which are not ubuntu. (while snap can be installed in other distros, it doesn't make much sense and no one else is adopting it while flatpak is already on the other distros and isn't centralized on canonical's server, has better sandboxing, etc, etc)

there are already two recipes for vscode on flathub:
https://github.com/flathub/com.visualstudio.code.oss (compiles from source, no microsoft proprietary bits)
https://github.com/flathub/com.visualstudio.code (pulls deb from microsoft servers, extracts the contents to /app/extra and runs it from there)

while the .oss one contains the important bits as the other one just pulls binaries, there are some interesting flatpak manifest thing going on the other one (like pulling the deb to /app/extra on install and not while building)

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/7112

We don't plan on offering another official Linux distribution method available, we already have 4. You can always install snapcraft on other systems to use the snap. The unofficial option is also always available.

**Comment by mikelpr** [comment]
that issue is closed for comments. and it's a wasted effort making a snap when ubuntu already has a deb and only ubuntu users are going to go for it. if you don't plan on adding it, at least think about replacing the snap with a flatpak.

**Comment by Tyriar** [comment]
@mikelpr last year is not this year. See https://docs.snapcraft.io/installing-snapd/6735 for supported distros.

I know some people have their favorites and may have philosophical issues with others, but you can always fall back on the deb, rpm, the tarball or even the community packages already available, like that on flathub or AUR, which are derived from the official packages.
