### ISSUE TITLE
Code lens can sometimes overlap with code

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#71745]
Issue Type: <b>Bug</b>

I have only seen this with today's insiders (1.34), but sometimes the code lens overlaps with the editor content. See below:
![image](https://user-images.githubusercontent.com/641685/55593906-9a825400-570b-11e9-9df5-2efa00539b72.png)

VS Code version: Code - Insiders 1.34.0-insider (e88a32ff2cb11e750b57b7c844a4b17665f0f04a, 2019-04-04T19:48:00.957Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
😱 what... @eamodio when you see this can you use the `Element` dev tool to inspect the html structure?  Look for `codelens-decoration` and `monaco-visible-content-widget` classes

**Comment by eamodio** [comment]
The DOM of both good and bad code lens look identical -- and it looks like they are positioned appropriately, but the issue is that for some reason there is a missing view zone -- notice that there is no `2` view zone

![image](https://user-images.githubusercontent.com/641685/55664842-18755680-5803-11e9-80ca-a93051202a6a.png)

Bad code lens:
![image](https://user-images.githubusercontent.com/641685/55664809-689fe900-5802-11e9-835a-b54d6ea4bbfd.png)

Good code lens:
![image](https://user-images.githubusercontent.com/641685/55664812-77869b80-5802-11e9-87f5-47739c839865.png)

I think that this issue might be in some way related to https://github.com/Microsoft/vscode/issues/71707 since it feels like it only happens after a on-save format. Also switching to a different tab and back fixes it.

**Comment by jrieken** [comment]
This just happened to me with Insiders (without fix for #71707) and it seems that one view zone is missing. Below screen shot shows how 13 isn't there...

<img width="934" alt="Screenshot 2019-04-09 at 19 58 06" src="https://user-images.githubusercontent.com/1794099/55823396-e6653c80-5b01-11e9-9881-f5734f32419f.png">

**Comment by eamodio** [comment]
I don't know what changed, but I'm seeing this issue happen A LOT more frequently. And I get tripped up, because sometimes it overlaps with a blank line, and it makes me think I'm missing a blank line in that space, causing me to add a new line and only then realize that there was one, it was just this issue.

**Comment by jrieken** [comment]
Nobody here having repro steps, right? Looking at code lens source this should only happens with an error somewhere - the calls to add and remove the viewzone/content widget pair always come together. One failing could prevent that other but should surface as error...

**Comment by eamodio** [comment]
I don't have any steps that for sure make it happen, but I use both the typescript references code lens and GitLens' code lens (with a custom scope to make them appear on all blocks too): 
```
"gitlens.codeLens.scopes": [
    "document",
    "containers",
    "blocks"
  ],
```

With that I see the issue very often... though as I'm trying to reproduce it with today's insiders I can't seem to get it to happen. 🤷‍♂

**Comment by jrieken** [comment]
@eamodio Errors on the console?

**Comment by eamodio** [comment]
@jrieken I can't be sure these lines were exactly related to this issue, but when I saw this issue, these were the last things in the console

```
workbench.main.js:239 [Extension Host] Registering disposable on object that has already been disposed. (at add (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:41:27))
t.log @ workbench.main.js:239
workbench.main.js:1406   ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at Y.getDataNode (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:964:433)
    at Y.updateWidth (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:962:270)
    at e.s.instantiationService.createInstance.e [as updateWidth] (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5250:648)
    at i.elementDisposable.i.label.onDidRender (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5235:155)
    at d.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:78:67)
    at D.render (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4364:212)
    at D.notifyFileDecorationsChanges (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4361:301)
    at _widgets.forEach.t (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4358:644)
    at Array.forEach (<anonymous>)
    at _register.decorationsService.onDidChangeDecorations.e (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4358:631)
    at e (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:74:506)
    at d.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:78:67)
    at setTimeout (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:74:789)
```

**Comment by jrieken** [comment]
Unfortunately not, those errors come form the tree not being able to find nodes by id...

**Comment by DanTup** [comment]
I've been seeing this a lot lately, though can't see any obvious reason.

<img width="541" alt="Screenshot 2019-07-24 at 5 26 40 pm" src="https://user-images.githubusercontent.com/1078012/61811059-8b4d2080-ae38-11e9-91b5-970283217c67.png">

I have errors in the console, but I don't think they're related.

<img width="1137" alt="Screenshot 2019-07-24 at 5 27 56 pm" src="https://user-images.githubusercontent.com/1078012/61811005-6fe21580-ae38-11e9-8bbe-d8897dcf672a.png">

Could it be related to the caching of code lens that was added to reduce them jumping around?

That said, in the screenshot here the file was never modified, so I wouldn't expect the cache to have ever had only one of the two (line 10 and line 19 are the locations.. line 10 is hard to see as it overlaps `void main`).

**Comment by alexandrudima** [comment]
fyi @rebornix -- this is caused by the find widget which removes a view zone id created with the previous view from the new view. Steps:

1. Open fileA which has code lenses
2. Open fileB which does not have code lenses
3. Cmd+F to open the find widget (this will introduce view zone 1)
4. Open fileA again -- the find widget will remove view zone 1 incorrectly from the new view

![Kapture 2019-08-14 at 17 34 35](https://user-images.githubusercontent.com/5047891/63034568-d9929400-beb9-11e9-9dd5-2a0758007a17.gif)

**Comment by rebornix** [comment]
@alexandrudima thanks for the quick turn around
