### ISSUE TITLE
/src folder emptied randomly

### ISSUE THREAD

**Issue by lukesnc** [Microsoft/vscode#71744]
Issue Type: <b>Bug</b>

I closed Visual Studio after saving my project multiple times and reopened the workspace to an empty project. The files on the disk are gone, not in the recycle bin, and are nowhere on the disk. This is unacceptable.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (9.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
chat|kar|0.10.0
cpptools|ms-|0.21.0
vsliveshare|ms-|0.3.1151
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.5
java|red|0.38.0
vscode-java-debug|vsc|0.16.0
vscode-java-dependency|vsc|0.3.0
vscode-wpilib|wpi|2019.2.1

</details>

**Comment by mjbvz** [comment]
Sorry to hear this. Looks like you are on an old vscode version with a few extensions installed that could have caused this.  Can you please make sure you update the latest vs code (1.33) and try disabling all extensions to see if this hapens again

**Comment by aeschli** [comment]
Closing, please reopen if you see this again.
