### ISSUE TITLE
VSCode intellisense wrong for CDN ARM Templates

### ISSUE THREAD

**Issue by ShirleyJ27** [Microsoft/vscode#71749]
We (the CDN team) want to do a tech blog/a Build session on how to deploy a CDN service using ARM templates. However, when I was trying to write the ARM template and update the apiVersion to the most recent one, VSCode gives me a green line saying that the apiVersion is wrong. And it recommends two different versions. I'm not sure where I got that value from. 

![image](https://user-images.githubusercontent.com/8152925/55597156-fd222280-5700-11e9-99e7-07453889a764.png)

![image](https://user-images.githubusercontent.com/8152925/55597170-0b703e80-5701-11e9-89e3-c73b7e717978.png)

So I went to Github for samples on other products and see that it also gives errors for other products when it shouldn't.

For example,

https://github.com/ShirleyJ27/azure-quickstart-templates/blob/master/101-AAD-DomainServices/azuredeploy.json 

![image](https://user-images.githubusercontent.com/8152925/55597127-e7acf880-5700-11e9-9a9c-8619b0c059af.png)

Can you let me know where the error is coming from and how to fix it? We don't want our customers to see intellisense errors for something valid.

**Comment by mjbvz** [comment]
Please file an issue against whatever azure extension is providing support for these templates

**Comment by ShirleyJ27** [comment]
I've disabled all of my extensions and it's still like that...

**Comment by mjbvz** [comment]
This is not a vscode issue. Not caused by extension as I first thought but by the schema hardcoded in that json file:  `"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json"`

I don't know who owns that schema but please file an issue against them. If you think VS Code is incorrectly interpreting the schema, let us know
