### ISSUE TITLE
Markdown preview text turned black in version 1.33.0

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#71741]
Today, VS Code 1.33.0 installed to my machine.

After that, Markdown preview text turned black, so it isn't readable anymore with the default Visual Studio Code color scheme:

![Visual Studio Code](https://user-images.githubusercontent.com/9283914/55587524-d3cabc00-572b-11e9-9e36-7bb88745a87f.png)

### VSCode/OS Version:

Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Datum: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17134

### Steps to Reproduce:

1. Open some markdown file and hit "Show Markdown Preview" button.

### Does this issue occur when all extensions are disabled?
- [x] Yes
- [ ] No

<hr/>
EDIT: This situation is only true when Markdown preview is opened. As soon as the Markdown text is changed or when the color theme is changed, the Markdown preview updates correctly. Still, when opening Markdown preview, the text is rendered black on dark gray.

**Comment by mjbvz** [comment]
@SetTrend Do you see this consistently? I can only repo on windows and only sometimes (possibly related to cpu load)

**Comment by mjbvz** [comment]
I've found the possible cause of the issue and pushed a fix to master. @SetTrend can you please test the next [VS Code insiders build](https://code.visualstudio.com/insiders/) to see if you still hit tthis (it should come out in about 12 hours or so)

We can consider porting this fix to 1.33 as well if many people are running into it. It would be most common on windows + on machines that are under heavy load or not too fast to begin with

**Comment by SetTrend** [comment]
Thanks, @mjbvz, for your fast response and efforts!

Yes, your observation is right: For my private development I'm running an older virtual machine that occured to become rather slow recently.

I guess won't be able to attend my machine until next week. But I will download the Insiders Build next week ASAP.

**Comment by aeschli** [comment]
@mjbvz Any suggestions how to verify?

**Comment by mjbvz** [comment]
Just load the preview a bunch of times on a slow windows machine. This bug would only rarely show up in the first place and there is no reliable way to trigger it
