### ISSUE TITLE
Task detection error for workspaces without tasks

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/vscode#71742]
- VSCode Version: 1.33.0-insider
- OS Version: Mojave 10.14.3

I'm writing an extension to auto-detect tasks in the user workspace.
The extension basically scans the current workspace folder for tasks, and registers a task provider in that manner:

```ts
  vscode.tasks.registerTaskProvider(taskProviderType, {
        provideTasks: () => {
          return this.searchForTasks();
        },
        resolveTask:  () => undefined,
      }),
```

Now if the user has only one workspace folder (with tasks inside), the task list will be populated with the tasks correctly. But if the user opens a workspace folder with no active tasks to run, my provider will return an empty array (as it should?). This makes vscode pop up a warning:

`Error: The ABC task detection didn't contribute a task for the following configuration:`

What is the recommended way to hide that warning? the provider should be allowed to provide an empty list of tasks for a given workspace if there are no tasks to run.

cc @dbaeumer

**Comment by alexr00** [comment]
@OmarTawfik I created a task provider that returns an empty array and opened a folder without a tasks.json file. I didn't get any error about task detection. Do you have a repo I can reproduce this with?

**Comment by OmarTawfik** [comment]
It is not public yet unfortunately :(
I'm trying to pinpoint and isolate now. Is there a specific place/setting I can look into when debugging to root-cause it? the task runner guidelines don't say anything about this error.

**Comment by alexr00** [comment]
It is an expected error that happens when the user has tasks in their tasks.json file that are supposed to be provided by a task provider. You can just debug your extension and confirm that it provides tasks that match the ones of your task type in the tasks.json.

**Comment by OmarTawfik** [comment]
@alexr00 hence why I filed the bug. Suppose I have this in my `package.json`:

```json
    "taskDefinitions": [
      {
        "type" : "my-custom-type",
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the task"
          }
        }
      }
    ]
```

If the user opens a folder that I didn't detect tasks for, I'll return an empty list. This will still be the case until the user opens another workspace with some tasks.
Why does vscode expect to **always** get tasks from task providers?
