### ISSUE TITLE
Click + Open result open two new tabs

### ISSUE THREAD

**Issue by Haytam95** [Microsoft/vscode#71757]
- VSCode Version: 1.33.0 (stable)
- OS Version: Windows 7 Ultimate x64

Steps to Reproduce:

1. Open a project
2. search something
3. CTRL + click on a result
4. Two windows will appear, instead of one :bug: 

![98ba59cd-47e9-47db-8c84-d16dd1cec9ea](https://user-images.githubusercontent.com/7773130/55598977-e1804180-572b-11e9-8e93-472fccf3121b.gif)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Haytam95** [comment]
Thank you bot, but it's not the same issue!

**Comment by roblourens** [comment]
I can repro, probably similar to https://github.com/Microsoft/vscode/issues/68176
