### ISSUE TITLE
Flickering and various visual issues when in fullscreen

### ISSUE THREAD

**Issue by raiguard** [microsoft/vscode#71753]
Issue Type: <b>Bug</b>

1. Open vscode
2. Open a workspace or folder and open a file
3. Enter fullscreen (F11)
4. When you try to use vscode, everything will start glitching out and flickering

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (8.46GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

----------

**Details:** This is a very strange issue, as I can only get it to occur if I'm NOT recording my screen. If I'm using OBS at all, the issue goes away entirely. The moment I close OBS, the flickering starts again.

Therefore, I had to record a cell phone video. Please disregard my family blabbing in the background - I asked them to be quiet but they quickly stopped being quiet... Anyway, [here is the video](https://drive.google.com/file/d/1zEj45Iw3hL4z6D2Q0IfN4EeB4BmUemmV/view?usp=sharing) (you won't be able to view it until it's done processing).

At first, I blamed my GeForce overlay, so I disabled that. I went through and disabled the Discord and Steam overlays as well, just in case. But this did not help.

I will try to provide as much info as I can, because I feel like this might be a system-specific issue, since nobody else has reported it yet and it's very VERY easy to reproduce.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by raiguard** [comment]
Sorry for the late response, I've been super busy recently. I downloaded and installed the exploration build and the flickering still occurs. Let me know if you need more information and I will do my best to accommodate.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.

**Comment by raiguard** [comment]
That workaround does indeed fix the issue! I went and it turns out there was a graphics driver update, so I installed that and restarted vscode, but the flickering still occurs without setting the `--disable-gpu` flag.

GeForce Game Ready Driver v425.31
EVGA GeForce GTX 970
1x 3840x2160p monitor (primary)
2x 2160x1440p monitors (secondary)

**Comment by raiguard** [comment]
So I reimaged my PC earlier today (it was a long time coming, Windows was getting really unstable and I wanted to upgrade my SSD), and when I reinstalled vscode after reimaging, I tested and the flickering no longer occurs. I have no idea why this would have fixed it, but I will try to see if I can get the issue to reappear so we can get to the actual root of this problem.
