### ISSUE TITLE
Terminal bug on first command, the location has disappear 

### ISSUE THREAD

**Issue by rboopathyAST** [Microsoft/vscode#71759]
Issue Type: <b>Bug</b>

open new terminal
type any command
then the location part (eg. xxxx/xxxx/xxx>) will dissappear 
see the picture : 
![image](https://user-images.githubusercontent.com/38854570/55603272-6fd5e100-5787-11e9-8c3a-12cbf425f0ae.png)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
Polymer2Snippets|jus|1.1.0
team|ms-|1.149.2
polymer-ide|pol|0.6.0
inline-html|pus|0.2.5
vscode-bolt-language|smk|0.0.4
firebase-bolt|tha|0.1.3
gitflow|vec|1.2.1

(1 theme extensions excluded)

</details>

**Comment by pkeuter** [comment]
Isn't this the same issue as https://github.com/Microsoft/vscode/issues/57803 ? If it is, it's an issue with Windows, and should be fixed in the next feature update.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
