### ISSUE TITLE
Code format shortcut is not working 

### ISSUE THREAD

**Issue by githubhero** [Microsoft/vscode#7175]
- VSCode Version: 1.1.1
- OS Version: OSX El Capitan 10.11.5

Steps to Reproduce:

1. Focus the text editor
2. Modify some code, so that code is not properly formatted;
3. Try the shortcut shift+alt+F;

Code is not formatted.

Other shortcuts are working (I don't know if any of them, but ctrl+F works)

**Comment by alexandrudima** [comment]
@githubhero Does `Format` appear as an action when you right click in the file? What file type are you using? Not all the languages have formatting support out of the box (you might need to install an extension that adds it).

**Comment by githubhero** [comment]
@alexandrudima 

No, I have only the following menu items:

- Change all occurrences;
- Cut;
- Copy;
- Paste;

The file is a PHP file. Same issue with CSS files. No issue with JS.

But why this common feature needs an extension?

**Comment by alexandrudima** [comment]
I think it is a matter of time -- we did not implement formatting for php, but there seems to be an extension that does that in the marketplace. https://marketplace.visualstudio.com/search?term=format&target=VSCode&sortBy=Relevance

Weird, I see @aeschli created a separate extension to do css formatting. @aeschli why not css formatting out of the box and only through an extension?

**Comment by mrdulin** [comment]
same issue! MacOs, `shift` + `option` + `f` not working. Give me this : `Ï` char. Mouse right click does not show the `format` option.
