### ISSUE TITLE
Multiple window restore.

### ISSUE THREAD

**Issue by cheako** [Microsoft/vscode#71756]
I'm working on migrating code to another project and it helps to have both projects open.  However when I exit only one window is restored when relaunching.

Please add better support for working with multiple projects at the same time.

**Comment by msftrncs** [comment]
@cheako, sounds like you need to check out the setting window.restoreWindows, setting to All.

**Comment by cheako** [comment]
It's not enough, even if it is the vscode method, to have a configuration option.

On Exit(I.E. File->Exit) there should be a check for more than one window open and a confirmation dialog with a checkbox(or radio for the case of never show again) to restore all windows.
