### ISSUE TITLE
不调试启动无反应

### ISSUE THREAD

**Issue by Brother-Lee** [Microsoft/vscode#71763]
Issue Type: <b>Bug</b>

简单的两行代码
import numpy as np
print(1)
有时会不调试启动无反应，而调试启动就正常
删掉import numpy则在两种启动状态下都可以正常运行
这不是一个能稳定复现的bug，不过有时候这样很影响工作效率

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.8.2
gc-excelviewer|Gra|2.1.30
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6352
vscode-icons|vsc|8.4.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
> Simple two-line code
Import NumPy as NP
Print (1)
Sometimes no debugging starts without a reaction, and debugging starts is normal
Deleting import numpy works correctly in both startup states
This is not a bug that can be consistently replicated, but sometimes it affects productivity

**Comment by mjbvz** [comment]
Please file this against the python extension
