### ISSUE TITLE
Links in Terminal not clickable

### ISSUE THREAD

**Issue by realhoffi** [Microsoft/vscode#71768]
It is no longer possible to open german file Links with CRTL+Click from the terminal.

- VSCode Version:
Newest Version
- OS Version:
windows 10
Steps to Reproduce:

What works: 
1. echo http://www.google.de
2. Link is clickable

::ERROR::
1. echo "C:/Projects/xxxx/ItemSelectBox.tsx"
2. link is not highlighted an not clickable!

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
