### ISSUE TITLE
Save search/replace patterns in a search/replace library (preferences)

### ISSUE THREAD

**Issue by TobiasWantzen** [Microsoft/vscode#71764]
I’d like to name and save search/replace pairs (with regex) to a search/replace library (JSON?), which reside in the user references.

This would be a great help in refining texts and code, because I use a lot of search/replace pairs regularly on different files.

(I’d like to refer back to issue #10791, which is NOT a duplicate of #5865, as it hadn’t asked for a search/replace history, but for search/replace pairs to be savable!)

**Comment by roblourens** [comment]
We are actually working on making it possible for extensions to build something like this in https://github.com/Microsoft/vscode/pull/71626
