### ISSUE TITLE
how to show only specified files in explorer

### ISSUE THREAD

**Issue by Nishit-Zinzuvadiya** [Microsoft/vscode#71766]
this is not working in settings json
is there is an alternate to do this.
```
"files.exclude": {
      "**/*.*":true,
      "**/*.php":false,
    }
```

My purpose is to hide all files first and show the only PHP files.

**Comment by roblourens** [comment]
`files.exclude` only lets you exclude certain file patterns, it doesn't work the way you are trying to use it. It's not likely that we will support only showing files that match a pattern.
