### ISSUE TITLE
Performance issue when open huge file

### ISSUE THREAD

**Issue by devhyunjae** [Microsoft/vscode#71767]
- VSCode Version: Version 1.34.0-insider (1.34.0-insider), also can be reproduce in stable latest
- OS Version: macOS Mojave Version 10.14.4. MacBook Pro (Retina, 15-inch, Mid 2015

Steps to Reproduce:

![32](https://user-images.githubusercontent.com/12890257/55610391-c65e1200-57bd-11e9-82d1-fb8daecea73d.gif)

1. open a small avascript file. everything is fast and cmd+click works fine.
2. open a large react javascript file. imported bunch of files and 1500+ lines of code in 1 file.
3. you can see that cpu usage boosts up to 100%+. overall performance gets super slow. cmd+click is loading forever
4. after opening the large file. cpu 100% usage never gets down. and even no.1 small file doesn't work with cmd+click

this worked fine. before i update my macbook to 10.14.4

Does this issue occur when all extensions are disabled?: Yes

**Comment by devhyunjae** [comment]
downloaded to 1.32.3 and works fine

**Comment by ScreamZ** [comment]
I was thinking that auto-completion was broken, it seems I have the same issue as you… Using auto-complete write `loading…` and nothing complete

Version 1.33.0 (1.33.0)

**Comment by roblourens** [comment]
Which process is that? Please run `code --status` while this is happening and share the output.

And does this still happen when you start with `--disable-extensions`?

My first guess is that this will involve the TS server, so if so is this a project that is on github or that you can share?

**Comment by roblourens** [comment]
Looks like there is a TS perf issue: https://github.com/Microsoft/TypeScript/issues/30663

https://github.com/Microsoft/vscode/issues/71746

It looks like you can change the TS version away from 3.4.1 (in the status bar) to work around this
