### ISSUE TITLE
Issues with running chained bash commands in Tasks via Powershell+Docker

### ISSUE THREAD

**Issue by paradajz** [Microsoft/vscode#71765]
Version: 1.33.0 (user setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to reproduce:

1. Try to pass chained bash commands in tasks using Powershell which runs docker image
2. Error occurs due to the `&&` operator

I am using Docker container as my build enviroment on Windows. In VSCode, I have several tasks which run some make targets in that container. Here's an example:

            "label": "[Make][Debug]",
            "type": "shell",
            "problemMatcher": [
                "$gcc"
            ],
            "windows": {
                "command": "docker run -it -v ${PWD}:/project build_env /bin/bash -c \"make -j8 DEBUG=1\"",
            },
            "linux": {
                "command": "make -j8 DEBUG=1",
            }

This works fine. It launches my Docker image and executes make inside container. The problem occurs when my bash command is actually a chain of more commands, ie.:

            "label": "[Make] [GTest] FW update",
            "type": "shell",
            "problemMatcher": [
                "$gcc"
            ],
            "windows": {
                "command": "docker run -it -v ${PWD}:/project build_env /bin/bash -c \"cd tests && make TESTS=fw\"",
            },
            "linux": {
                "command": "cd tests && make TESTS=fw",
            }

In VSCode terminal I am getting the following error:

    Executing task: docker run -it -v ${PWD}:/project build_env /bin/bash -c "cd tests && make TESTS=fw" <

    At line:1 char:72
    + ... it -v ${PWD}:/project build_env /bin/bash -c cd tests && make TE ...
    +                                                                ~~
    The token '&&' is not a valid statement separator in this version.
        + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : InvalidEndOfLine

Now, I realize Powershell doesn't support `&&` operator but:

1) I am not chanining multiple Powershell commands - the `&&` part is argument for bash command
2) The command works fine when I run it in Powershell window directly, which is strange.

Here's the output:

    PS C:\dev\EsProject> docker run -it -v ${PWD}:/project build_env /bin/bash -c "cd tests && make TESTS=fw"
    Building test_FwUpdater.cpp
    Building aes/aes128.cpp
    Building aes/aes256.cpp
    Linking.
    Created executable: build/fw.out
    PS C:\dev\EsProject>

**Comment by alexr00** [comment]
We run tasks in PowerShell like this:
````
> powershell.exe -Command "echo hello"
````
I suspect you'll need some additional escaping for the `&&` in this case. 
What happens when you start cmd and run: 
````
powershell.exe -Command "docker run -it -v ${PWD}:/project build_env /bin/bash -c \"cd tests && make TESTS=fw\""
````

**Comment by paradajz** [comment]
This:

    The string is missing the terminator: ".
        + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**Comment by paradajz** [comment]
I am working around this by using cmd as default terminal which seems to work fine.

**Comment by alexr00** [comment]
You can set cmd just for this one task if you want:
````
      "options": {
        "shell": {
          "executable": "cmd.exe"
        }
      }
````
