### ISSUE TITLE
path disappear when we start entering command in integrated terminal

### ISSUE THREAD

**Issue by torabshaikh** [Microsoft/vscode#71761]
Issue Type: <b>Bug</b>

After upgrading to the latest Windows 10, Whenever I open an integrated terminal, The path where the terminal points to appear but soon as I start typing a command it disappears.

Also, I have turned on the dark theme which came in the latest Windows update but the problem won't go away even with the light theme.

I am attaching screenshots.

 [Before typing command](https://drive.google.com/file/d/1I9S3PWad3YXRuOlq9Mq5ROhMku7saXzX/view?usp=sharing)
[After typing command](https://drive.google.com/file/d/1CnZuAj-iun-MMSZtOktqrzb77EPGtlLc/view?usp=sharing)
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
python|ms-|2019.3.6352

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
