### ISSUE TITLE
VS Code crashes when trying to open 1,8GB file

### ISSUE THREAD

**Issue by morriekken** [microsoft/vscode#71770]
Issue Type: <b>Bug</b>

1. I try to open 1,8GB txt file 
2. Appliction asks me to set up more memory (up to 8192MB) I choose to "Restart with 8192"
3. Application restarts and crashes

When I check what is current memory limit, it is already 8192MB but then when I try to open file again I got asked to "Restart with 8192MB" again.. and it goes on like this...

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.62GB (8.13GB free)|
|Process Argv|C:\Temp\!\msmdsrv.log|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
graphviz-preview|EFa|1.3.1
mssql|ms-|1.5.0

</details>

**Comment by morriekken** [comment]
@rebornix This is tricky bit. I know how important this is for you to test, but it's customer's log file from Microsoft SSAS (msmdsrv.log) and this is actually my last day on site. Nevertheless I'll try check with them if it's OK that I take a log outside organisation.

**Comment by rebornix** [comment]
Close it for now and we can reopen once we have more data to troubleshoot.
