### ISSUE TITLE
Option to completely hide titlebar and menubar in Windows

### ISSUE THREAD

**Issue by mpekurin** [microsoft/vscode#71777]
Since all menu commands are available from command palette it would be nice to add an option to hide titlebar and menubar completely. This suggestion is like https://github.com/Microsoft/vscode/issues/43154 and https://github.com/Microsoft/vscode/issues/12377, but for Windows. It might look something like this:
![vscode](https://user-images.githubusercontent.com/22733346/55616056-a4eb2f00-5799-11e9-8aec-fc62f7c5b128.png)

**Comment by kamenminkov** [comment]
What would happen if you open a terminal to the right?

**Comment by mpekurin** [comment]
@kamenminkov there might be 2 ways to handle this. Without redusing tabs row width:
![vscode 1](https://user-images.githubusercontent.com/22733346/55617239-54290580-579c-11e9-81ff-342535d96af2.png)
And with redusing width (like implemented in VS Code now):
![vscode 2](https://user-images.githubusercontent.com/22733346/55617300-7589f180-579c-11e9-8b43-7154dcceaa70.png)
