### ISSUE TITLE
Expose bracket matching functionality to extensions

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#7177]
I'm developing a Vim extension for Visual Studio Code and I could really use your guys' bracket matching  logic. 

Either exposing a function like `getTextDecorations()` or, better yet, a function like `getMatchingBracket(position: Position)` would be awesome.

Thanks!

**Comment by jrieken** [comment]
fyi @alexandrudima

**Comment by jrieken** [comment]
Sorry, but that won't happen in July

**Comment by johnfn** [comment]
How about December? 😉

**Comment by jrieken** [comment]
How about a PR?

**Comment by johnfn** [comment]
Alright, but if I make a PR on vscode you have to make a PR on vscodevim. It's only fair! 😉

**Comment by CoenraadS** [comment]
@johnfn I would also be interested in something like `getMatchingBracket(position: Position) : BracketPair` if you are working on it.

**Comment by CoenraadS** [comment]
@johnfn Is this being worked on? Else I might try it myself if its not too hard.

@jrieken Should API be discussed here or in PR?

**Comment by jrieken** [comment]
> @jrieken Should API be discussed here or in PR?

here

**Comment by johnfn** [comment]
No, I haven't worked on this. 

Sorry I missed your question almost a month ago. `getSurroundingBrackets` would be ideal.

**Comment by CoenraadS** [comment]
```
getMatchingBracketPosition(position: Position) : Position?
getSurroundingBracketPositions(position: Position, type?: CharacterPair) : Position[]?
getBracketTypes() : CharacterPair[]
```

I would also like to expose getting the bracket types for a document, and then being able to search surround brackets based on the bracket type.

**Comment by jrieken** [comment]
cc @alexandrudima who knows more about this. 
@CoenraadS today we have no token information in the extension host and for performance reasons have no plans yet to change that

**Comment by jrieken** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
