### ISSUE TITLE
Rendering bug on app start in zen mode

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [Microsoft/vscode#71772]
- VSCode Version: 1.32-1.33
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Set app to restore to zen mode if it was exited in zen mode
1. Open file explore and/or terminal
1. Reload vscode
1. Observe previously opened file explore and/or terminal are not rendered but empty panels are shown instead.
![vs](https://user-images.githubusercontent.com/6418145/55612130-35247680-5790-11e9-81a9-e754e5f016eb.png)

Does this issue occur when all extensions are disabled?: Yes
<img width="1426" alt="Screenshot 2019-04-05 10 49 07" src="https://user-images.githubusercontent.com/6418145/55612246-79177b80-5790-11e9-9d55-ded0e45ca56b.png">

Does this issue occur in latest insiders build?: Yes
<img width="1434" alt="Screenshot 2019-04-05 11 00 11" src="https://user-images.githubusercontent.com/6418145/55612905-09a28b80-5792-11e9-8b11-8708f22f9416.png">

**Comment by isidorn** [comment]
@ivanvoznyakovsky great find and nice steps.
I first thought this is a candidate issue, however the previous stable we already shipped with this and nodoby noticed. So it seems like zenmode.restore is not such a popular option.

I have pushed a fix, so if you are reallying on this behavior please start using insiders. Thanks!

**Comment by ivanvoznyakovsky** [comment]
great. thnx for a quick fix 👍

**Comment by sandy081** [comment]
@isidorn On reload/restart file explorer is not retrieved? Is it expected?

![Kapture 2019-05-07 at 14 06 59](https://user-images.githubusercontent.com/10746682/57298032-7b436180-70d1-11e9-8821-97f7d66473a3.gif)

**Comment by isidorn** [comment]
No, that is an issue. I filled it here -> https://github.com/microsoft/vscode/issues/73408
