### ISSUE TITLE
“No result" when "peek reference" or "find all reference" in Python file

### ISSUE THREAD

**Issue by futurehome** [Microsoft/vscode#71773]
Issue Type: <b>Bug</b>

No specific operation, just launch code, and open an Python file, when I try to use "peek reference" or "find all reference", it shows "no results". These feature can be used before, maybe 2 months ago. I've disabled all the extensions, it still doesn't work.

![image](https://user-images.githubusercontent.com/6230304/55613580-a4648f80-57bd-11e9-85ec-b29cf716025f.png)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (9.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-sshfs|Kel|1.14.6
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6352
veriloghdl|msh|1.0.2
tcl|ras|0.1.0
vscode-yaml|red|0.4.0
vscodeintellicode|Vis|1.1.5
vim|vsc|1.3.0

</details>

**Comment by futurehome** [comment]
But I have disabled all the extensions, but it still doesn't work.

**Comment by jrieken** [comment]
>  I have disabled all the extensions, but it still doesn't work.

That cannot be. Peek only enables itself when there is at least one extension claiming that it supports peek.

**Comment by futurehome** [comment]
You're right, I disable all but Python. So you mean it's Python's issue?

**Comment by beastdestroyer** [comment]
Yes, it most likely is. File the issue in their repo and see if you get a response

**Comment by futurehome** [comment]
Ok, I'll try it. Thanks for the support.
