### ISSUE TITLE
Closing integrated terminal causes window to crash with C++ assertion error

### ISSUE THREAD

**Issue by kaleidawave** [microsoft/vscode#71789]
- VSCode Version: 1.33.0
- OS Version: Win10

Steps to Reproduce:

1. Closing the integrated terminal

Does this issue occur when all extensions are disabled?: "Shouldn't be affected by extensions"

Before window crashes this Microsoft Visual C++ Runtime Library error comes up.

![image](https://user-images.githubusercontent.com/26967284/55623830-044a3e80-579c-11e9-81f7-98bd87a93df4.png)

**Comment by kaleidawave** [comment]
Can confirm it has symptoms of #68513 which has been closed.

**Comment by Tyriar** [comment]
Does this crash for you reliably? I haven't been able to reproduce at all personally.

**Comment by kaleidawave** [comment]
Can confirm this is now quite frequent. It may be associated with using the keybind to close the integrated terminal. I think it has happens when you go to close it after it has first launched up with the terminal already open.

**Comment by Tyriar** [comment]
What's the build number of Windows 10? Is your repro just open and close the terminal?

**Comment by kaleidawave** [comment]
Windows 10 Home: 17134.706
So yeah it seems to crash if you close the terminal from when it first launched up. 
```
{
    "window.zoomLevel": 0,
    "git.ignoreMissingGitWarning": true,
    "breadcrumbs.enabled": true,
    "workbench.sideBar.location": "right",
    "html.format.wrapLineLength": 0,
    "window.restoreWindows": "all",
    "workbench.startupEditor": "none",
    "editor.minimap.enabled": false,
    "search.usePCRE2": true,
    "csharp.referencesCodeLens.enabled": false,
    "explorer.confirmDragAndDrop": false,
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\cmd.exe",
    "git.confirmSync": false,
    "terminal.integrated.rendererType": "dom",
    "javascript.suggest.completeFunctionCalls": true,
    "editor.autoClosingBrackets": "beforeWhitespace",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "git.autorefresh": false,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.windowsEnableConpty": false,
    "workbench.iconTheme": "material-icon-theme"
}
```
The line `terminal.integrated.windowsEnableConpty": false,` was added after the crashes appeared from a thread on a similar issue but has not affected the random crashes. This has only happened recently (~last 3 weeks)

**Comment by lvanvugt** [comment]
Having the same issue, but only when my VScode workspace contains .ps1 sources. It is annoying, cause as long as the sources are part of the workspace the error is thrown when starting up VSCode. After removong the sources form the workspace VSCode can startup normally.

Once VSCode opened normally the sources can be placed again in the workspace.

VSCode version 1.33.1

**Comment by JulianTillmann** [comment]
I have the same issue as @lvanvugt 

I see that him and me are both NAV (Dynamics 365 Business Central) Partners, so I'm guessing he's using the same extensions as me

- https://github.com/Microsoft/AL
- https://github.com/PowerShell/vscode-powershell

the PowerShell guys already sent me here

**Comment by JulianTillmann** [comment]
By the way, the insiders version has the same issue 
![image](https://user-images.githubusercontent.com/35929603/58533958-38653d00-81ea-11e9-8b7d-40e758ecd1cd.png)

**Comment by lvanvugt** [comment]
Now on VSCode 1.34.0 it's not bothering me anymore, even though the issue occured once.

**Comment by JulianTillmann** [comment]
I'm also on VCode 1.30.0, but I've had the Problem 5 times today.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
