### ISSUE TITLE
Terminal misalignment

### ISSUE THREAD

**Issue by jayaprakashmani92** [Microsoft/vscode#71781]
Please see below attachement

![issue](https://user-images.githubusercontent.com/44426702/55618278-be997000-57b3-11e9-86e3-e1a765f8c7bf.png)

**Comment by bluemonkmn** [comment]
I think I'm seeing the same issue which has been bugging me since I re-installed 1.32 on a new system.

![TerminalBug](https://user-images.githubusercontent.com/1648185/55627883-d998bf80-5774-11e9-85fc-353966ddc12c.gif)

**Comment by WormChickenWizard** [comment]
I am also experiencing this issue in a similar manner bluemonkmn is
![image](https://user-images.githubusercontent.com/39471591/55662582-501bd880-57da-11e9-85f5-1a87ca0fc3cf.png)

**Comment by rocifier** [comment]
Mine is even more serious when using angular-cli: I can't see anything but some weird square brackets, even when I scroll up!

![image](https://user-images.githubusercontent.com/1772304/55693819-390cfe80-5a05-11e9-8e2e-3f164cf9a29a.png)

**Comment by gbbarroso** [comment]
Adding a "me too" here.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
