### ISSUE TITLE
Pipe stdout from command line into 'code -' does not work on Windows

### ISSUE THREAD

**Issue by ivanhernandez** [Microsoft/vscode#71788]
When trying to pipe the output of a command from Windows shell into an instance of Visual Studio Code, stdout content is lost.

### Setup

- VSCode Version: 1.32.3  (but detected issue in previous versions)
- OS Version: Windows 7 (x64)

### Steps to Reproduce

Write from Windows terminal

```
dir | code -
```

**Expected**

a VSC instance with a temp file open showing `dir` command output, as indicated by https://code.visualstudio.com/updates/v1_19

**Shows**
 
a VSC instance with an empty file named `-` open.

### Alternative tests

* Whem you omit `-`, no new file is open, but stdout from `dir` is lost (VSC instance does not show it)
* Does this issue occur when all extensions are disabled?: **Yes**

**Comment by bpasero** [comment]
I cannot reproduce. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by whitlaaa** [comment]
FWIW, I see this same issue (on both stable and insider builds), but only when invoking `code -` from WSL. When run via cmd/Powershell, it works as expected.

* VS Code Stable  - 1.33.0
* VS Code Insiders - 1.34.0-insider
* Windows 10 - Version 1709

**Comment by bpasero** [comment]
I do not believe we currently support piping from a WSL session into Code. 

@ivanhernandez is that your setup too?

**Comment by whitlaaa** [comment]
@bpasero Ah, you're correct. I had completely overlooked the fact that #44945 was specifically about RS4 hosts, which our org hasn't pushed out, yet.

**Comment by ivanhernandez** [comment]
It is not.

I am launching a regular cmd in Windows 7, so no case for WSL.

Instead, I forgot to mention it is configured as portable.(data folder
within vscode folder.)

**Comment by joaomoreno** [comment]
@ivanhernandez If it is portable, how is `code` on the PATH?
