### ISSUE TITLE
#include <> underlined with green line. Cannot open source file ".h"

### ISSUE THREAD

**Issue by GeorgeFlorian** [Microsoft/vscode#71784]
- VSCode Version: version 1.33
- OS Version: Linux Mint 19.1

Steps to Reproduce:

1. Install the new 1.33 version.

## Issue:

I've never configured includePath or IntelliSense, and never had issues with `#include <>`
I've just upgraded to the newest version of the VS Code (1.33) and I went to compile a random project.

I noticed that it compiles without any problems, but all my `#include <>` are underlined with a green wobbly line. Hovering over the first `#include <>` says: 

```#include errors detected. Please update your includePath. IntelliSense features for this translation unit (/home/george/Documents/PlatformIO/Projects/LoginPage_try5/src/main.cpp) will be provided by the Tag Parser.
```

Hovering over the next few `#include <>` and they all say: `cannot open source file "libraryname.h"` where `libraryname` corresponds to their library names, respectively.

What do you think the issues is and how can I fix it ?

Thank you !

**Comment by mjbvz** [comment]
Please file this against your cpp extension

**Comment by GeorgeFlorian** [comment]
> Please file this against your cpp extension

Do what now ?
