### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by nolvia80** [Microsoft/vscode#71782]
Issue Type: <b>Bug</b>

The workspace is composed with 11 Angular 4 projects. When I try to access to external methods or resources the VS Code is very slow (and the most of time no file is opened or I'm faster at opening the file by hand), and in some cases the workspace crash. 
In the windows task manager there are multiple open process and the CPU run up to 90%... So I can't work and makes me think to leave the tool for a better one 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-generate-getter-setter|DSK|0.5.0
Angular2|joh|7.0.1
vscode-typescript-tslint-plugin|ms-|1.0.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled? If not, please file an issue against your angular extension

**Comment by no-more** [comment]
Hello,

I have the same kind of troubles. With a quite big workspace (over 3k ts files) vscode is often completely lost. In some cases intelisence, go to definitions, code validation ... takes several minutes to achieve.

I have tried with disabling all extensions and it seems a bit faster but still very slow.

I'm on a windows 10 laptop computer with a very good processor and lots of ram (32Go). Vscode take around 3-4Go.

I don't know if it's related but quite often import suggestions don't even work in some files.

I think this is related to the size of the project which is a monorepos of hundreds of project components.

**Comment by mjbvz** [comment]
Closing as more information is needed from original poster

**Comment by nolvia80** [comment]
mjbvz the extensions not work so I disabled them all.
