### ISSUE TITLE
Terminal jumps using US International Keyboard and custom lineHeight

### ISSUE THREAD

**Issue by vinicio** [microsoft/vscode#71798]
- VSCode Version: 1.33.0
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Change your system keyboard layout to US - International
2. Sets any value to `terminal.integrated.lineHeight` (different of 1)
    Eg.: `"terminal.integrated.lineHeight": 1.1`
3. Open integrated terminal and try to input quotes or any accents. You will see this:
![Apr-04-2019 17-18-23](https://user-images.githubusercontent.com/874123/55633271-5c7c4300-5792-11e9-82db-48cb5040e15c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/2012

**Comment by Tyriar** [comment]
This seems to be fixed in latest 
![image](https://user-images.githubusercontent.com/2193314/66347086-5e24f000-e908-11e9-98cd-af22eea53106.png)

**Comment by Tyriar** [comment]
Actually it works with 2, but not 1.1 or 1.2?

**Comment by Tyriar** [comment]
Let's track this in https://github.com/xtermjs/xterm.js/issues/2012

**Comment by roblourens** [comment]
I see this:

![Oct-30-2019 10-43-27](https://user-images.githubusercontent.com/323878/67883915-258cc680-fb02-11e9-8f83-a1398d04fb8c.gif)

But only when I am typing near the bottom of the terminal. Works ok at the top.

**Comment by Tyriar** [comment]
Upstream issue is closed
