### ISSUE TITLE
Opened Folder changes don't show in explorer

### ISSUE THREAD

**Issue by AN1BRA** [Microsoft/vscode#71796]
1-> opened node project
2-> run npm install
3-> explorer doesn't update with node_modules folder until I reload the vscode window
( same thing happened when I cloned a repo )

**Comment by AN1BRA** [comment]
1-> opened node project
2-> run npm install
3-> explorer doesn't update with node_modules folder until I reload the vscode window
( same thing happened when I cloned a repo )

**Comment by isidorn** [comment]
I fixed this morning. Please wait for monday and try to reproduce with vscode insidershttps://code.visualstudio.com/insiders/
In case you still see it then let me know and I will reopen this issue. Thanks!
