### ISSUE TITLE
Regression in Explorer: alt-click does no collapse/expand subtree

### ISSUE THREAD

**Issue by jmrossy** [Microsoft/vscode#71792]
Alt-click does no collapse/expand subtree
I can confirm this used to work but stopped working a few versions ago.

- VSCode Version: 1.33
- OS Version: MacOS Mojave (10.14.3)

Steps to Reproduce:

1. Alt + Click a folder in the explorer view. It should recursively collapse/expand the children folders.

Does this issue occur when all extensions are disabled?: Yes

Related issues:  #9456, #18109, #68943

**Comment by isidorn** [comment]
Works for me.
Can you reproduce with vscode insiders.
If yes, please give exact reproducable steps, for what folder structure do you expact what?

**Comment by jmrossy** [comment]
@isidorn have you tested on MacOS?

**Comment by isidorn** [comment]
Yes
