### ISSUE TITLE
Extensions output logs are saved incorrectly on Windows if there are forbidden symbols in output channel name

### ISSUE THREAD

**Issue by SounD120** [Microsoft/vscode#71797]
- VSCode Version:1.33.0
- OS Version:Windows 10

Steps to Reproduce:

1. Clone test VS Code extension with `git clone https://github.com/SounD120/proxysupporttest.git` command
2. `cd proxysupporttest`
3. `npm i`
4. `code .`
5. Open debug tab and run `Run extension`
6. In Extension Developement Host call command pallete and run `Proxy Support Test: Send message to the Extension: Logs channel`
7. Proceed to `C:\Users\<username>\AppData\Roaming\Code\logs` folder, or folder which you choosed for saving VS Code temporary data.
8. Find the corresponding `exthost<number>` (in my case it was `exthost3`) which contains logs from the Extension Developement Host. 

You will see file `Extension` without extension `.log` which was truncated by `:` symbol instead of `Extension: Logs.log`, file will be empty. Example:
![image](https://user-images.githubusercontent.com/32372875/55629704-864a5f80-57bc-11e9-952f-8dc8d7902a24.png)

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
Yeah but it is an implementation detail and it can subject to change so it cannot be promised to have same name as it can change. I would suggest to write into your own file in such a case.
