### ISSUE TITLE
toggle problems shortcut

### ISSUE THREAD

**Issue by JerryGreen** [microsoft/vscode#71790]
It's not toggling back (not closing the "problems" view)

Versions
===
- VSCode Version: 1.32.3
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:
===

1. `cmd + shift + m` to toggle the view (it works)
2. `cmd + shift + m` to toggle it back / to close (it won't work)

Does this issue occur when all extensions are disabled?
===
Yes

**Comment by JerryGreen** [comment]
However, if I use a separate tab, "output" (`cmd + shift + u`) – it toggles back and fourth

But `cmd + shift + m` is one-side toggle :(

**Comment by jwikman** [comment]
This has annoyed me as well.

Actually I think it's related to the behavior of the Problems panel. If there are no problems, the "problems" panel isn't focused on `ctrl+shift+m`. As soon as I got a problem this works as intended. You can see the focusing of the panel (or lack of it) by observing the border of that panel.

The panel is only hidden if it is focused as seen in src\vs\workbench\browser\panel.ts:
```
		if (this.isPanelFocused()) {
			this.layoutService.setPanelHidden(true);
		} else {
			this.panelService.openPanel(this.panelId, true);
		}
```
So I think the the solution would be to focus on the "problems" panel even if there are no problems.

**Comment by sandy081** [comment]
@JerryGreen Can you please check in your keybindings editor to which command `ctrl+shift+m` keybinding is associated to?

**Comment by jwikman** [comment]
@sandy081 I've got the default binding, with a similar experience as @JerryGreen 
But I only experience this if the problems list is empty, don't know if @JerryGreen has this issue also when there are problems...

Keybinding:
```
{
  "key": "ctrl+shift+m",
  "command": "workbench.actions.view.problems"
}

```

**Comment by sandy081** [comment]
@jwikman I see following as default

![image](https://user-images.githubusercontent.com/10746682/55718451-014d8900-59fc-11e9-90ea-5a39d3af721e.png)


Can you disable all extensions and check again?

**Comment by JerryGreen** [comment]
@sandy081 ofc:

![image](https://user-images.githubusercontent.com/13215662/55725348-f3f9c400-5a26-11e9-8712-90a9c5739537.png)

Also, agree with @jwikman:

> But I only experience this if the problems list is empty

**Comment by jwikman** [comment]
> @jwikman I see following as default
> 
> ![image](https://user-images.githubusercontent.com/10746682/55718451-014d8900-59fc-11e9-90ea-5a39d3af721e.png)
> 
> Can you disable all extensions and check again?

@sandy081 if you right click and select copy you get the same result as me... I.e. I haven't changed any keybinding, I'm using the default ones. If you search for "workbench.actions.view.problems" in the code, you'll see that's the default command for that ctrl+shift+M.

So no surprises here: it's the same with all extensions disabled...

**Comment by chrisjones-brack3t** [comment]
Also running into this issue and it's driving me a little mad.

**Comment by akshaal** [comment]
Quite annoying. Is there a workaround at the moment? It could have been possible to just call workbench.action.togglePanel when the problems panel is already visible, but it looks like there is no way to find out whether the problems panel is visible or not....
