### ISSUE TITLE
Ctrl+C does not work in new ConPTY integrated terminal

### ISSUE THREAD

**Issue by sschocke** [Microsoft/vscode#71793]
Issue Type: <b>Bug</b>

I am using Powershell as my Integrated Terminal. After updating to the latest release, ConPTY support was automatically enabled. When running a node based application, `Ctrl+C` no longer terminates the running application.
### Actual: ###
1) Open Integrated Terminal
2) run `node index.js`
3) press `Ctrl+C`
4) Nothing happens
### Expected: ###
1) Open Integrated Terminal
2) run `node index.js`
3) press `Ctrl+C`
4) node process is terminated

### Note ###
I have disabled ConPTY support with the setting `"terminal.integrated.windowsEnableConpty": false` and then it works as expected, so it definitely seems to be ConPTY related.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (17.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
markdown-preview-github-styles|bie|0.1.4
better-toml|bun|0.3.2
turbo-console-log|Cha|1.2.17
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.11
chat|kar|0.12.0
git-tree-compare|let|1.6.1
VS-code-vagrantfile|mar|0.0.7
rainbow-csv|mec|1.0.0
mssql|ms-|1.5.0
python|ms-|2019.3.6352
azure-account|ms-|0.8.1
csharp|ms-|1.18.0
powershell|ms-|1.12.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.18
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.10
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
rust|rus|0.6.1
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Tyriar** [comment]
Please report over at https://github.com/Microsoft/console
