### ISSUE TITLE
Fast autocomple typing selects the previous autocomplete suggestion

### ISSUE THREAD

**Issue by cra0zy** [microsoft/vscode#71795]
Fast autocomple typing selects the previous autocomplete suggestion

- VSCode Version: 1.32.3
- OS Version: Ubuntu 18.04

Steps to Reproduce:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6773302/55625812-1df28280-57aa-11e9-9251-93929db2b7e2.gif)

**Comment by cra0zy** [comment]
@jrieken If you don't mind, could you link me to an existing issue as I've been unable to find it?

**Comment by jrieken** [comment]
This is the one meant: https://github.com/Microsoft/vscode/issues/70974 but this might actually be a different issue... We re-filter with a 25ms delay and you might be accepting completions during that delay, we should either stop delaying or accepting should join on the delay...

**Comment by jrieken** [comment]
Long stretch for April...

**Comment by claytongulick** [comment]
I'm running into this a lot, my specific case is when typing "this" quickly. My expectation is that if I do 'thi' then '.' I should autocomplete "this" and then trigger the new autocomplete list for everything relevant to this.

What I'm seeing instead is "this.ATTRIBUTE_NODE." come up. I keep having to stop what I'm doing and go back to delete this and redo it, it's slowing me down quite a bit.

Thanks!!

**Comment by jrieken** [comment]
@claytongulick what you are seeing is #70974

**Comment by jrieken** [comment]
I have minimised the re-filter delay to 0ms. That is a fair workaround but not yet the real fix (which requires a little more work)

**Comment by jrieken** [comment]
Showing the problem from the gif

<img width="588" alt="Screenshot 2019-05-17 at 16 56 45" src="https://user-images.githubusercontent.com/1794099/57961574-c2e19e80-78c4-11e9-9d0b-bdfbd0010d13.png">

**Comment by cra0zy** [comment]
Welp, this bug is back with the newest version :/

@jrieken can you re-open this issue?

**Comment by cra0zy** [comment]
The problem now seems present only if "Accept Suggestion on Commit Character" is enabled strangely enough.
