### ISSUE TITLE
CSS vendor prefixes at the top

### ISSUE THREAD

**Issue by svipas** [Microsoft/vscode#71791]
Right now CSS vendor prefixes are at the top, but before they were at the bottom.

VS Code: 1.33.0

<img width="934" alt="Screenshot 2019-04-05 at 14 26 53" src="https://user-images.githubusercontent.com/10441177/55624514-df12fb80-57ae-11e9-8a9e-4354a437be31.png">

**Comment by aeschli** [comment]
I think they were hidden due to our filtering...

**Comment by octref** [comment]
@aeschli What do you think about using `sortText` to make sure `-` properties always come after normal ones? I suggest:

```
0block
0flex
0grid
1-moz-...
1-webkit-...
```

**Comment by aeschli** [comment]
@octref  Yes, sounds good!

**Comment by octref** [comment]
@aeschli It seems you are already using `sortText` so I just added `x` to the ones with `-`. Normal attributes are prefixed with `d`.

For verifier: Verify in CSS completions, `-` items always come after ones without `-`.
