### ISSUE TITLE
Explorer activity icon unsaved count decoration stays around

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7180]
1. Create a new Untitled file <kbd>Cmd N</kbd>
2. Type something
3. Close the file, don't save

![image](https://cloud.githubusercontent.com/assets/22350/15774429/7fa2d912-297c-11e6-9743-1c8a87c18fa8.png)

**Comment by bpasero** [comment]
Might be me given that the explorer is also showing the dirty counter.
