### ISSUE TITLE
VS Code no longer rememberers opened windows upon quit and launched again since v1.32

### ISSUE THREAD

**Issue by neoswallow** [Microsoft/vscode#71806]
- VSCode Version: 1.32 and 1.33
- OS Version: MacOS 10.14.4

Steps to Reproduce:

1. Open multiple windows each pointing to different repo
2. Quit and launch VS Code again

Does this issue occur when all extensions are disabled?: Cannot disable all extensions

**Comment by bpasero** [comment]
Set this in settings: `"window.restoreWindows": "all"`
