### ISSUE TITLE
Explorer Tree View No Longer Opens to Show Active File

### ISSUE THREAD

**Issue by 51ngul4r1ty** [Microsoft/vscode#71811]
Issue Type: <b>Bug</b>

We have a workspace file that has the following layout:

- Root Folder
- Client Folder
- Server Folder

Although the Client and Server folders are underneath the Root folder we've specifically excluded client & server folders because we want developers to open up VS Code with the provided workspace file.

A recent VS Code update seems to be confused by this workspace layout: if you view a file using Cmd+P it won't expand the "client" folder, but attempts to expand "root" instead - under "root" it can't show the file because we exclude the "client" and "server" folders (to force developers to use the workspace file).

Although this may be viewed as a "hack" to get developers to use the workspace file, I still feel this is a valid bug and it is a change in the original behavior of VS Code to it needs to be fixed.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (17.94GB free)|
|Process Argv|main.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
touch-bar-display|bla|1.2.1
vscode-svgviewer|css|2.0.0
gitlens|eam|9.5.1
toggle-excluded-files|eam|1.6.0
EditorConfig|Edi|0.13.0
vscode-sort|hen|0.2.5
path-autocomplete|ion|1.13.2
plantuml|jeb|2.10.9
awesometypescriptproblemmatcher|Jua|0.3.0
xml-format|mik|1.0.2
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-versionlens|pfl|0.22.0
node-tdd|pra|0.2.4
text-power-tools|qcz|1.10.0
quicktype|qui|12.0.46
vscode-coverage-gutters|rya|2.3.1
jenkinsfile-support|sec|0.1.0
vscode-icons|vsc|8.4.0
vscode-import-cost|wix|2.12.0
markdown-pdf|yza|1.2.0

</details>

**Comment by isidorn** [comment]
What recent vscode update are you referring to? On what version was this previosly working?
Can you reproduce this issue with vscode inisiders https://code.visualstudio.com/insiders/
If yes, can you please write nice reproducable steps so I try to get this on my machine
