### ISSUE TITLE
Mouse middle click pasting doesn't work within the integrated terminal on VSCode Mac

### ISSUE THREAD

**Issue by manojvazirani** [Microsoft/vscode#71817]
In a Mac terminal window, mouse middle click should paste the selected block of text into the current cursor position. This is not happening in the VS Code integrated terminal:

VSCode Version: Version 1.33.0 (1.33.0)
OS Version: Mac Mojave 10.14.4 (18E226)

Steps to Reproduce:

1. Launch Integrated Terminal
2. Drag your mouse to select a block of text from the terminal
3. Try to use the mouse middle click to paste the selected text
4. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

Or add option to Integrated terminal **Middle Click Behavior** similar to Right Click Behavior

**Comment by Tyriar** [comment]
This is not a mac feature, some terminals support it but it's not an OS-wide feature like on Linux so it only works within that application/terminal and also doesn't use a selection keyboard. Closing as designed for now.

Note that you can use the default for copy/paste on Windows by tweaking settings https://code.visualstudio.com/docs/editor/integrated-terminal#_right-click-behavior

**Comment by manojvazirani** [comment]
I would think, the integrated terminal to work as the default terminal in mac. The default Terminal Version 2.9.4 (421.1.1) supports middle click by default. Also adding an option for the user would be ideal, for any user who works on the Mac terminal can work on the integrated terminal with no transition. If not then, is there a way to integrate the mac default terminal properties to VSCode Integrated terminal?

**Comment by Tyriar** [comment]
@manojvazirani when https://github.com/Microsoft/vscode/issues/3130 is done you should be able to configure this yourself.
