### ISSUE TITLE
Find in files operation extremely slow after upgrade to 1.33.0

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/vscode#71819]
Issue Type: <b>Performance Issue</b>

It seems that the upgrade to 1.33.0 might have introduced some performance problems when searching for something in multiple files. Searching in a repository of about 600 files typically took 10-15 seconds and now takes up to 5 minutes. Unfortunetely the problem does not seem to be consistent but it happens in 50-75% of find operations. While running the build in "Process explorer shows "30 559 14508  window (module.ts - periscope - Visual Studio Code [Administrator]) and the cpu utilization in the task manager of Windows stays on 100%.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	 10820	code main
    1	    71	 11068	   gpu-process
    0	    44	 13104	   shared-process
    8	   557	 14508	   window (index.ts - periscope - Visual Studio Code [Administrator])
    0	     1	  8168	     electron-crash-reporter
    0	    33	  8996	     searchService
    2	     8	 17060	       "c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --hidden --ignore-case -g **/src/modules/** -g **/src/modules -g !**/configs/** -g !**/configs -g !**/scripts/** -g !**/scripts --max-filesize 17179869184 --no-ignore --follow --pcre2 --regexp buttonEmailForward --no-config --no-ignore-global --json -- .
    0	     7	 12588	     watcherService 
    0	    90	 16372	     extensionHost
    0	    71	  5740	       "C:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=16372
    0	    10	  9596	       "C:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=16372
    0	   451	 16484	       electron_node tsserver.js 
    0	     4	 16964	         electron_node typingsInstaller.js typesMap.js 
    0	    37	 16676	       electron_node server.js 
    0	   391	 16876	       electron_node eslintServer.js 
    0	    59	 16980	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.ts - periscope - Visual Studio Code [Administrator])
|    Folder (periscope): 1746 files
|      File types: ts(597) gif(357) png(232) html(202) css(91) styl(81)
|                  psd(47) js(39) tsx(23) less(13)
|      Conf files: package.json(2) tsconfig.json(1) webpack.config.js(1)
|                  settings.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
svn-scm|joh|1.47.12
python|ms-|2019.3.6352
printcode|nob|3.0.0
vscode-docker|Pet|0.6.1
code-settings-sync|Sha|3.2.8
stylelint|shi|0.48.0
language-stylus|sys|1.11.0
vscode-icons|vsc|8.4.0
stylint|vtf|0.0.2
plsql-language|xyz|1.8.0

</details>

**Comment by roblourens** [comment]
Nothing changed on our end. Does the process MsMpEng.exe show up in task manager? If not what is using high CPU:

**Comment by doberkofler** [comment]
>Does the process MsMpEng.exe show up in task manager?
Yes!
![image](https://user-images.githubusercontent.com/1009585/55651512-24ecb580-57e9-11e9-9311-bb8bb55dd25b.png)

>What do you mean by...
forget it. i just copied one line from the vscode process explorer

**Comment by roblourens** [comment]
Ok. That's windows defender scanning all the files being searched. Unfortunately there's nothing we can do about that. This sometimes happens after new releases. I'm guessing that the new code gets whitelisted by Defender after it has been out for a bit.

**Comment by doberkofler** [comment]
What files would I need to exclude in vscode files? Thank you!

**Comment by MrAcalf** [comment]
Same problem here, mine is on infinite load loop and the intellisense is stuck forever.

**Comment by roblourens** [comment]
> What files would I need to exclude in vscode files? Thank you!

Not sure what you mean, if you have a large folder like node_modules that isn't already excluded from search, you can add that to `search.exclude`.

**Comment by doberkofler** [comment]
I wanted to understand what files might be responsible for the dramatic slowdown. The node_modules folder, all temp folders a d distribution directories are always excluded from searching.

**Comment by roblourens** [comment]
Unfortunately Windows Defender thinks that it needs to scan all files as they are searched, and apps  don't have any control over that.

**Comment by doberkofler** [comment]
... even if I exclude them from the search?

**Comment by roblourens** [comment]
It's scanning the files that are searched

**Comment by doberkofler** [comment]
... then I really don’t understand why it slowed down so much after the update. Maybe something else changed and I will have to dig deeper.

**Comment by hd4ng** [comment]
@doberkofler I think #71751 will solve your problem.
