### ISSUE TITLE
Links opened from terminal have extra characters

### ISSUE THREAD

**Issue by zkarim-ib** [Microsoft/vscode#71816]
Issue Type: <b>Bug</b>

From Terminal:
> cat README.md
README contains a git markup readme. Contains hyperlinks ie:
[helm](https://helm.sh/docs/using_helm/)

cmd + click option opens the following link in web browser:
https://helm.sh/docs/using_helm/)

The link is pulling in the tailing ")"

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
Go|ms-|0.9.2
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
java|red|0.42.1
vscodeintellicode|Vis|1.1.5
vscode-arduino|vsc|0.2.25
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.16.0
vscode-icons|vsc|8.4.0

(1 theme extensions excluded)

</details>

**Comment by onecentlin** [comment]
I encounter the same issue

e.g.
`server started: <http://127.0.0.1:8000>`

the link with string: `http://127.0.0.1:8000>`

**Comment by konradw86** [comment]
pt., 5 kwi 2019, 19:31 użytkownik zkarim-ib <notifications@github.com>
napisał:
