### ISSUE TITLE
Powershell produces UTF16LE when echoing.

### ISSUE THREAD

**Issue by arlCode** [Microsoft/vscode#71812]
- VSCode Version: 1.33.0
- OS Version: Windows 10

Steps to Reproduce:

1. Use Powershell as your terminal tool
2. CTRL+`
3. type: echo "whatever" >> .gitignore

Does this issue occur when all extensions are disabled?: Yes/No
Yes

The file interpreter produces a UTF16LE file, which nullifies .gitignore functionality entirely, I have to manually convert the file to UTF8 then get rid of the gibberish characters.

**Comment by Tyriar** [comment]
@TylerLeonhardt this something on powershell's end?

**Comment by TylerLeonhardt** [comment]
@arlCode can you repro this outside of vscode?

**Comment by arlCode** [comment]
Oh, I just tried it outside the scope of VSCode, I think you are right @Tyriar, it seems like a PowerShell thing. https://stackoverflow.com/questions/6947749/how-to-check-if-a-txt-file-is-in-ascii-or-utf-8-format-in-windows-environment. This is something related to that topic, nevermind.
