### ISSUE TITLE
Powershell  in Visual code 1.33

### ISSUE THREAD

**Issue by MarkSix** [Microsoft/vscode#71825]
Issue Type: <b>Bug</b>

Powershell doesn't work with VC 1.33

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (27.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-django|bat|0.19.0
lit-html|bie|1.11.0
flask-snippets|cst|0.1.0
vscode-eslint|dba|1.8.2
code-runner|for|0.9.7
vscode-firefox-debug|hbe|1.7.9
python|ms-|2019.3.6352
html5-boilerplate|sid|1.0.3
vscodeintellicode|Vis|1.1.5
jinja|who|0.0.8
html-css-class-completion|Zig|1.18.0

</details>

**Comment by mjbvz** [comment]
Are you using Powershell in the editor or from the terminal?

**Comment by MarkSix** [comment]
I'm using it in the editor.

**Comment by mjbvz** [comment]
From the extension list, it doesn't look like you have powershell installed: https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell

Did you install it previously?

Also, what exactly doesn't work?

**Comment by MarkSix** [comment]
I got it working, don't know what happened :(    Sry
