### ISSUE TITLE
Toggle Commit keyboard shortcut(CMD + /) stopped working after the update

### ISSUE THREAD

**Issue by adityaarakeri** [microsoft/vscode#71820]
- VSCode Version: 1.33.0
- OS Version: Mac OS 10.13.6

Steps to Reproduce:
1. Update VScode to Version 1.33.0 (1.33.0)
2. go to your code and try to comment a line of code pressing the short cut (⌘+/)

Does this issue occur when all extensions are disabled?: Yes

Note: I tried to change the shortcut to (CTRL + / ) it works and when i change it back to (CMD + /), it does not

**Comment by golee** [comment]
Same symptoms here.
- Ctrl + / (toggle comment line)  
- Ctrl + ` (toggle terminal)  
Not always work on editor focused.

It is temporary restored after press CTRL key few times quickly 

------------------------
1.33 / Windows 10

- extensions
bertolinimarco.theme-newton
bhughes339.replacerules
bmewburn.vscode-intelephense-client
brittanychiang.halcyon-vscode
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cssho.vscode-svgviewer
daltonjorge.scala
dariofuzinato.vue-peek
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
dragos.scala-lsp
eamodio.gitlens
eg2.vscode-npm-script
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.code-runner
gerane.Theme-Peacock
gerane.Theme-peacocks-in-space
henoc.svgeditor
hsnazar.hyper-term-theme
ikappas.composer
James-Yu.latex-workshop
junstyle.php-cs-fixer
lextudio.restructuredtext
mikestead.dotenv
mrmlnc.vscode-apache
mrmlnc.vscode-scss
MS-CEINTL.vscode-language-pack-ko
ms-python.python
msjsdiag.debugger-for-chrome
mubaidr.vuejs-extension-pack
nobuhito.printcode
octref.vetur
plievone.vscode-template-literal-editor
redhat.java
ryu1kn.partial-diff
Shan.code-settings-sync
small.php-ci
tinkertrain.theme-panda
tombonnike.vscode-status-bar-format-toggle
vincaslt.highlight-matching-tag
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
WallabyJs.quokka-vscode
xabikos.JavaScriptSnippets
yzhang.markdown-all-in-one
zhuangtongfa.Material-theme
Zignd.html-css-class-completion
------------------------------

**Comment by alexandrudima** [comment]
@adityaarakeri Does VS Code receive the `cmd+/` keybinding?
@golee Does VS Code receive the `ctrl+/` keybinding?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by golee** [comment]
@alexandrudima 

![keystrokeinput](https://user-images.githubusercontent.com/1129665/55854626-3b579000-5ba0-11e9-8b72-ca11fc5df735.gif)
*Does not receive it.*


![aletter](https://user-images.githubusercontent.com/1129665/55854663-54f8d780-5ba0-11e9-8b84-9de2039f0a01.gif)
*It just type one letter at editor. Curiously it dosen't type more than one letter*


![after restored](https://user-images.githubusercontent.com/1129665/55854666-562a0480-5ba0-11e9-8386-a9d3615f4df1.gif)
*After pressing Ctrl + Alt + Shift few times quickly. it restored*

**Comment by chadcodes** [comment]
Same issue, 
Mac OS 10.13.6

After the latest update version 1.33.1, CMD+/ does not comment code anymore.  I've deleted and replaced the key binding with the same value but it does nothing.

**Comment by adityaarakeri** [comment]
@alexandrudima

The ctrl + / binding is not received on the mac.

**Comment by alexandrudima** [comment]
@golee What keyboard layout do you use?

**Comment by golee** [comment]
@alexandrudima It is 101 key qwerty.
Vendor and model is durgod k310.

**Comment by alexandrudima** [comment]
@golee I believe you have installed some keyboard layout in Windows that make `` ctrl+/ `` and `` ctrl+` `` produce weird characters / key codes. I suggest that you edit the keybinding and bind it to some key combination which works on your keyboard, or, alternatively, remove the offending keyboard layout.
