### ISSUE TITLE
100% CPU used after upgrading to Mojave

### ISSUE THREAD

**Issue by laila-vinson** [Microsoft/vscode#71829]
Issue Type: <b>Performance Issue</b>

After upgrading Mac OS to Mojave, VSCode is now taking several minutes or more to respond to any code changes on one of my projects.

This is a Typescript/React project nested inside of a parent project. Neither the main project or the subproject are working. Other separate repos still work with VSCode.

I've uninstalled/reinstalled VSCode and removed all of my extensions. Both the main project and the subproject have node_modules in the "exclude" argument of their respective .tsconfig. The parent project also has the subproject excluded.

Here is a sample output of TS Server logs (path name slightly changed for privacy) and a screenshot of the Process Explorer. I can email the full TS Server logs if needed.

Thanks!

`Info 91   [16:13:0.424] Running: *ensureProjectForOpenFiles*
Info 92   [16:13:0.424] Structure before ensureProjectForOpenFiles:
Info 93   [16:13:0.424] Project '/Users/lailavinson/<root>/<subproject root>/tsconfig.json' (Configured) 0
Info 93   [16:13:0.424] 	Files (446)
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2016.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.esnext.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.iterable.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.core.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.promise.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.object.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.string.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.intl.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.intl.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.promise.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.regexp.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.array.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.string.d.ts
/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.symbol.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.esnext.intl.d.ts
	/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.esnext.bigint.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/react/global.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/csstype/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/prop-types/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/react/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/react-dom/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/redux/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/hoist-non-react-statics/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/react-redux/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/indefinite-observable/dist/types.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/indefinite-observable/dist/IndefiniteObservable.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/indefinite-observable/dist/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/jss/css.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@types/jss/index.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/styles/createGenerateClassName.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/styles/createBreakpoints.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/styles/spacing.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/colors/amber.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/colors/blue.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/colors/blueGrey.d.ts
	/Users/lailavinson/<root>/<subproject root>/node_modules/@material-ui/core/colors/brown.d.ts
` .. etc (this goes on for more node modules)

<img width="801" alt="Screen Shot 2019-04-05 at 4 18 56 PM" src="https://user-images.githubusercontent.com/46457901/55661406-92382080-57c0-11e9-8196-23b80129a73a.png">

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   115	 30603	code main
    0	    82	 30604	   gpu-process
    0	   311	 30605	   window (Untitled-1 —<my project>)
    0	    82	 30608	     extensionHost
  101	   311	 30610	       electron_node tsserver.js 
    0	    49	 30624	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 30638	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=30608
    0	    49	 30609	     watcherService
    0	    49	 30640	     searchService
    0	    82	 30637	   shared-process
    0	    82	 30701	   window (Issue Reporter)
    0	     0	 30702	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-1 — <my project>)
|    Folder (<my project>): 11408 files
|      File types: cache(6630) rb(1964) slim(573) coffee(511) png(497) gz(183)
|                  svg(150) scss(144) js(136) yml(101)
|      Conf files: package.json(2) tsconfig.json(2) tslint.json(2)
|                  settings.json(1);
```

</details>
Extensions: none

**Comment by mjbvz** [comment]
Sounds like a duplicate of #71751

See https://github.com/Microsoft/vscode/issues/71751#issuecomment-480126916 for workarounds

Let me know if these solve the issue for you

**Comment by laila-vinson** [comment]
Thanks for the quick response! Downgrading TypeScript to 3.3 worked. The other workarounds (deleting cache and changing @types/styled-components version) did not seem to do anything.
