### ISSUE TITLE
Installed label disappears if you overscroll extensions list

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#71822]
Issue Type: <b>Bug</b>

After vscode launches it updates installed extensions, some of which do not need reloading. But it's hard to know which were actually updated. Each `installed` label disappears from extensions list if you overscroll it. Here is how `installed label looks like:

![image](https://user-images.githubusercontent.com/7345761/55652874-7ef37800-57f5-11e9-9e85-bff391b906cf.png)

STR:
1. Launch vscode, with at about 20 extensions installed and one of extensions got updated
2. Scroll to the bottom and top
3. If you have no clue which was updated

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (11.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
Installed label is just a temporary state to show user the extension is completely installed after you install/update the action. It disappears when you update the view.
