### ISSUE TITLE
Search results navigation in Tree using keyboard is not consistent as using mouse 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#7183]
Navigation in search results is as follows:

Using Mouse
* clicking with the mouse keeps focus in the tree
* double click moves focus to the editor
* Cmd/Ctrl+click opens the editor to the side

Using Keyboard
* There is no way to do what mouse single click is doing
* There is no way to do what Cmd/Ctrl+click is doing

**Comment by bpasero** [comment]
@sandy081 I added support in search to Ctrl+click to open to the side. Cmd+click is taken by the OS to show the context menu so we cannot use it on Mac, but on Windows it should be fine.

I have not heard complains to have a keybinding to keep focus in the tree, so I did not add it.

**Comment by bpasero** [comment]
Also you are free to do anything you want if you implement a TreeController. If you feel for problems you need a keybinding to keep focus, it is up to you to do so.
