### ISSUE TITLE
Some Git status icons are missing

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#71839]
Issue Type: <b>Bug</b>

It seems that deleted, renamed, and added status icons are missing in the SCM sidebar:
![image](https://user-images.githubusercontent.com/641685/55665318-41014e80-580b-11e9-9ac8-d9fb0bcc3dd4.png)

VS Code version: Code - Insiders 1.34.0-insider (d234937aedcbc265d2272ba5861125293239f9c7, 2019-04-05T05:18:43.251Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.09GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
@jrieken Anything changed lately wrt resource decorations?

**Comment by jrieken** [comment]
Nope, didn't change anything. @eamodio Are then icons also missing from the explorer? @joaomoreno Those letters/colors in the SCM viewlet should just travel as part of the `SCMRawResourceSplices`, the decoration service may add extra information, like compile info, later

**Comment by eamodio** [comment]
I can't reproduce this with the latest insiders.
