### ISSUE TITLE
error when i open integrated terminal in liunx

### ISSUE THREAD

**Issue by ruanshanshan** [Microsoft/vscode#71833]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by ruanshanshan** [comment]
The terminal process command '/usr/bin/bash' failed to launch (exit code: 1)

**Comment by Tyriar** [comment]
That means bash exited with code 1, you sure you're pointing at the right path?
