### ISSUE TITLE
Don't show setting count when not searching

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#71832]
![image](https://user-images.githubusercontent.com/323878/55662782-ae8d8a80-57cb-11e9-9e68-b3cdfbc0b0f3.png)

**Comment by bpasero** [comment]
I am now stuck with this counter, even if I reload:

![image](https://user-images.githubusercontent.com/900690/57303095-de86c100-70dc-11e9-8dfa-da714d4dc799.png)

I did not see the counter initially, but then typed, selected all text and cut it. The counter stays.

**Comment by DavidMunozMartinez** [comment]
I could try and make a PR for this one, seems like in renderResultCountMessages fn  we are setting the "settings-count-widget" to display none but then immediately afterwards we are setting it back to display block

**Comment by roblourens** [comment]
Yeah that code got a bit weird so I will handle this one
