### ISSUE TITLE
No longer possible to start empty instance with new untitled file

### ISSUE THREAD

**Issue by TheCGDF** [microsoft/vscode#71837]
Issue Type: <b>Bug</b>

{
    "workbench.startupEditor": "newUntitledFile",
    "window.restoreWindows": "none",
    "files.hotExit": "off",
    "update.showReleaseNotes": false
}

it doesn't work in newest version.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (11.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.3.6352

</details>

**Comment by bpasero** [comment]
This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by alexr00** [comment]
I copied the settings from the original issue into my settings, then closed VS Code. 

When I have a single folder open before closing: ✔

When I have an unsaved workspace open before closing: it restores my untitled workspace and doesn't do the new untitled file.

**Comment by bpasero** [comment]
Thanks for verifying, yeah this was the behaviour from before, we always give preference to restoring untitled workspaces or untitled files.
