### ISSUE TITLE
Git is not updating after file change

### ISSUE THREAD

**Issue by alexdevero** [Microsoft/vscode#71838]
Issue Type: <b>Bug</b>

1) Git is not detecting changes in files. Changes in code are highlighted but source control tab is empty. Manual refresh is necessary.

2) Git is also not updating after committing changes. After change is committed, source control tab still shows files that were committed. Manual refresh is necessary. Also, code changes are still highlighted in opened files after committing.

VS Code version: Code - Insiders 1.34.0-insider (d234937aedcbc265d2272ba5861125293239f9c7, 2019-04-05T05:18:43.251Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
color-info|bie|0.5.0
bracket-pair-colorizer-2|Coe|0.0.28
EditorConfig|Edi|0.13.0
auto-close-tag|for|0.5.6
svg|joc|0.1.4
vscode-styled-components|jpo|0.0.26
wordcounter|kir|1.5.0
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.22
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.2
vscode-duplicate|mrm|1.2.1
react-proptypes-intellisense|OfH|1.0.3
material-icon-theme|PKi|3.7.0
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.2.8
stylelint|shi|0.48.0
code-spell-checker|str|1.6.10
code-spell-checker-czech|str|0.1.0
vscode-icons|vsc|8.4.0
dictionary-completion|yzh|0.8.1

(1 theme extensions excluded)

</details>

**Comment by ghiscoding** [comment]
I also have the same problem with few latest versions of insiders, most of the time I have to click on the Git Refresh icon. However in couple of occasions the refresh made it worst and it showed commit differences that were already commited and pushed to origin, after restarting VSCode, it came back to correct diff...

**Comment by alexdevero** [comment]
The issue seems to be fixed now.

Version: 1.34.0-insider
Commit: 0ab39f4148f242e7b0802330385fc99b4845aa31
Date: 2019-04-08T05:19:58.162Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
