### ISSUE TITLE
exclude folder in context menu

### ISSUE THREAD

**Issue by WittHickmanYoung** [microsoft/vscode#71836]
I work on a project with 30 thousand files. In order to speed up he performance and reduce memory usage ,  I add "files.exclude" in "settings.json" to stop IntelliSense.

Is there any way to add exclude feature in context menu?

Thanks!

**Comment by rthaneda** [comment]
Hello! Me and my partner @TejDNagaraja would like to work on this issue — forking to do so

**Comment by rthaneda** [comment]
https://github.com/Microsoft/vscode/pull/72731
