### ISSUE TITLE
Git / Stage Selected Ranges doesn't work with UTF-16LE files

### ISSUE THREAD

**Issue by rysavyjan** [Microsoft/vscode#71847]
- VSCode Version: 1.33 and 1.34.0-insider
- OS Version: Latest Windows 10 x64
- Git: latest version 2.21.0

Steps to Reproduce:

1. Unpack attached repository
2. Switch to Source Control View
3. Choose utf16le.rh file
4. Try to select change on the first line and choose Stage Selected Ranges command

You will receive following error: "Git: Could not hash object."
> git hash-object --stdin -w --path utf16le.rh

Same operation for UTF-8 encoded file utf8.h works fine.
Command line `git add -p` works for both utf16le.rh and utf8.h files.

Does this issue occur when all extensions are disabled?: Yes

[git_utf16le_problem.zip](https://github.com/Microsoft/vscode/files/3050324/git_utf16le_problem.zip)

**Comment by petrsol** [comment]
Moreover when I select second change (line "define 20") in utf16le.rh file (when viewing changes) and click Stage Selected Ranges command from right-click context menu, it seems to stage selected line, but the result is corrupted utf16le.rh file in stage area. I have to unstage utf16le.rh file to continue working.

It seems to me that change in utf16le.rh file is staged without automatic conversion from UTF-16LE to UTF-8. This conversion is set in .gitattributes on this line:
*.rh         text working-tree-encoding=UTF-16LE-BOM

When I tried to stage that line with command line version of git, it works well:
git add -i
p
1
<empty-line = just press Enter>
n
y
q

```
X:\DOWNLOAD\git_utf16le_problem\git_utf16le_problem>git add -i
           staged     unstaged path
  1:    unchanged        +2/-2 utf16le.rh
  2:    unchanged        +2/-2 utf8.h

*** Commands ***
  1: status       2: update       3: revert       4: add untracked
  5: patch        6: diff         7: quit         8: help
What now> p
           staged     unstaged path
  1:    unchanged        +2/-2 utf16le.rh
  2:    unchanged        +2/-2 utf8.h
Patch update>> 1
           staged     unstaged path
* 1:    unchanged        +2/-2 utf16le.rh
  2:    unchanged        +2/-2 utf8.h
Patch update>>
diff --git a/utf16le.rh b/utf16le.rh
index 5195bcf..c0d61a7 100644
--- a/utf16le.rh
+++ b/utf16le.rh
@@ -1,4 +1,4 @@
-#define 1
+//#define 1
 #define 2
 #define 3
 #define 4
Stage this hunk [y,n,q,a,d,j,J,g,/,e,?]? n
@@ -17,4 +17,4 @@
 #define 17
 #define 18
 #define 19
-#define 20
\ No newline at end of file
+//#define 20
\ No newline at end of file
Stage this hunk [y,n,q,a,d,K,g,/,e,?]? y

*** Commands ***
  1: status       2: update       3: revert       4: add untracked
  5: patch        6: diff         7: quit         8: help
What now> q
Bye.
```

**Comment by joaomoreno** [comment]
#36219
