### ISSUE TITLE
Sort Hover Event

### ISSUE THREAD

**Issue by JCofman** [Microsoft/vscode#71848]
Hi 👋 folks,

I am currently trying to create an extensions which provides some additional hover results. The results show up but I wasn't able to find any solution to order the results. 

This is what happens: 
<img width="525" alt="hover results" src="https://user-images.githubusercontent.com/2118956/55668104-1fcd4c00-5865-11e9-9c29-080c1f244bf9.png">

I want to place the additional changelog results below the already available package info results.

The documentation says that the registered `HoverProviders` get merged somehow but I couldn't find any way to order the results. 

Could we add a way to provide an order in which the hover results get shown.

**Comment by jrieken** [comment]
Providers get sorted by their [score](https://github.com/Microsoft/vscode/blob/c052919d985b47569e84ae17cf3dc97104440054/src/vs/vscode.d.ts#L7831) and in case of equal scores by registration time, later is better.

**Comment by JCofman** [comment]
Hi @jrieken thanks a lot for your advice. :)
