### ISSUE TITLE
CLI Flag "--user-data-dir" Has No Effect

### ISSUE THREAD

**Issue by McPrescott** [Microsoft/vscode#71849]
Issue Type: <b>Bug</b>

Using the command line flag `user-data-dir` with many different configurations has no effect on the instance of VsCode.

I attempted to use empty directories as the user-data directory, copying the `data` directory from the installation directory and using custom directories with only some of the relevant files, such as `settings.json` and `keybindings.json`.

With the `data` directory copied from the vscode installation, I've attempted to use the `data/user-data` directory, the root `data` directory, as well as `data/user-data/User` directory, thinking that perhaps I misunderstood the meaning of "user-data-dir". For each of these I also attempted using absolute and relative paths, but to no avail.

@izznogooood mentions in #41429 that he had success using `--user-data-dir=/some/directory`, however this also had effect.

When the vscode instance is created, any modifications to user-data, such as to `settings.json`, or `keybindings.json` are reflected within the installation directory. In all of the mentioned attempts there were never any modifications to the directory specified, nor were the files from that directory ever used.

I've found that the `--extensions-dir` command line option works perfectly fine. The extensions are taken from and installed into the specified directory.

Thank you in advance for the help, it is much appreciated! 

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1622)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 1|
|Memory (System)|7.67GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by McPrescott** [comment]
As a follow up, I've installed the vscode insiders edition in which the `--user-data-dir` option functions without any issue.

**Comment by joaomoreno** [comment]
> One other difference between the two installations is that the stable installation is using portable mode.

> Is portable mode intended to prevent the modification of the user data directory?

Yes it is! `--user-data-dir` is *not* compatible with Portable mode, since it defeats the whole purpose of Portable.
