### ISSUE TITLE
editor.insertSpaces and editor.tabSize changes don't apply for JSON files

### ISSUE THREAD

**Issue by dnear** [Microsoft/vscode#7184]
- VSCode Version: 1.1.1
- OS Version: Windows 7 Enterprise 64 bit 

User settings editor.insertSpaces and editor.tabSize don't seem to change the behaviour for .json files.

Steps to Reproduce:
1. Generate or create a package.json file
2. Open Visual Studio
3. Go to File > Preferences > User Settings
4. Add "editor.insertSpaces": false to the JSON file and "editor.tabSize": 4
5. Go to the package.json file and use tab

**Comment by alexandrudima** [comment]
@dnear `editor.insertSpaces` and `editor.tabSize` are overwritten based on the file contents if a third option `editor.detectIndentation` is set to `true` (it is `true` by default):

So if you create a new json file (where there is no indentation to detect, it will use what you have put in `editor.insertSpaces` and in `editor.tabSize`). If you open an existing json file (that contains indentation), its indentation will be used.

I agree that this is pretty nasty, as there is a third setting that overrides the other two. Do you think this would be better if I improve the comments on `editor.tabSize` and `editor.insertSpaces` to explicitly mention `editor.detectIndentation`?

![image](https://cloud.githubusercontent.com/assets/5047891/15815769/684f6ca8-2bcf-11e6-808a-b63b707c04d4.png)

**Comment by timfish** [comment]
I just spent ages trying to work out why a couple of my typescript files were ignoring my specified tab size. Turns out `editor.detectIndentation` defaults to true and for some reason a couple were being detected with 4 rather than 2!

**Comment by alexandrudima** [comment]
@timfish There might be issues also in the detection algorithm. Can you please share the files which were detected with 4 rather than 2, so we can look if the detection algorithm is broken?

**Comment by timfish** [comment]
Looking into it, I think the detection algorithm was working fine, I just didn't realise a it was being detected and enforced in the background. 

I tried to manually correct a file to 2 spaces and closing the last bracket was re-aligning it to 4 spaces again. Is the detection meant to be re-applied?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response
