### ISSUE TITLE
Extension state in `when` condition

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#71843]
Contributions define `when` clauses dynamically governing visibility of keycodes, menu items and other things. There is already elaborate support for symbols and operators but there is no way to make use of arbitrary state maintained by an extension.

The obvious solution to this problem is to allow a `when` clause to refer to an extension defined function returning true or false. However this introduces the questions of exception handling and failure to return in a timely manner.

A more robust solution is to extend contribution to support the declaration of properties exported by an extension and allow them to be used in when clause expressions. 

The intrepid would then no doubt declare a property for which the value was a function or an object with a property whose value was a function. This can be trivially sanitised by JSON stringify and parse.

**Comment by Gama11** [comment]
Extensions can set context variables fro `when` clauses via the `setContext` command: https://github.com/Microsoft/vscode/issues/10471

**Comment by PeterWone** [comment]
In that case I'll save myself the embarrassment of having this closed as a duplicated by closing it myself. It does, however, highlight the need to surface this fact in documentation likely to be found by someone who doesn't know he's looking for it. I propose https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts
