### ISSUE TITLE
Terminal Path not displaying

### ISSUE THREAD

**Issue by mayura33** [Microsoft/vscode#71840]
Sometimes while opening the terminal window it does not display the current path of the project. I don't know why it's happening in my pc.
____________________________: myCommand
It looks like this so its create confusion that where I am currently in terminal

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
