### ISSUE TITLE
breakpoint hit first debug but not on subsequent

### ISSUE THREAD

**Issue by tonyhallett** [Microsoft/vscode#71857]
- VSCode Version:
- OS Version:
![image](https://user-images.githubusercontent.com/11292998/55671488-7a2bd400-5888-11e9-9c9d-4675106d15b2.png)

Steps to Reproduce:

I have [minimal repo](https://github.com/tonyhallett/badBreakpointsGulp).  
I am debugging gulp task written in typescript which is being transpiled by ts-node.  The task is in its own module and imported/exported by index.ts within the gulpfile.ts folder ( nothing out of the ordinary here ).  When the breakpoint is not hit you can see that the code has been executed from the console.log statement.  I have checked ts-node and each time it is successfully transpiling with typescript and returning with inlined source.

1. add a breakpoint inside the function simpleTask in simple.ts
2. debug ( using launch config for gulp provided by vscode ) - breakpoint hit
2. debug again - breakpoint not hit
3. close vscode - debug again - breakpoint not hit

Does this issue occur when all extensions are disabled?: Yes/No
Still occurs with clean vscode insiders

By adding breakpoints in to the gulp javascript source it will hit my breakpoint.
![image](https://user-images.githubusercontent.com/11292998/55671446-fc67c880-5887-11e9-87df-bc100079e52d.png)

The debugadapter.txt has been added to my repo.

**Comment by roblourens** [comment]
When debugging with ts-node and similar tools, it's impossible for vscode to preload the sourcemaps, so it's impossible to guarantee that a breakpoint will be hit soon after a script is loaded. I recommend adding a `debugger` statement at the top of the file or near your breakpoint.

**Comment by tonyhallett** [comment]
Ok. Thanks. It doesn't seem to happen with ts-jest or ts-node outside of gulp though. Different mechanisms/timing then.

**Comment by roblourens** [comment]
It can still happen, it's just all about timing.
