### ISSUE TITLE
I cannot view variable values in hover when debugging,

### ISSUE THREAD

**Issue by albaizzz** [Microsoft/vscode#71853]
Issue Type: <b>Bug</b>

I cannot view variable values in hover when debugging, I used lubuntu 18.04

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.18.0-16-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2605)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (3.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
xml|Dot|2.4.0
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
golang-tdd|joa|0.0.9
mssql|ms-|1.5.0
python|ms-|2019.3.6352
csharp|ms-|1.18.0
Go|ms-|0.9.2
vscode-docker|Pet|0.6.1
ruby|reb|0.22.3
vscode-yaml|red|0.4.0
gotimeformat|v4r|1.0.1
vscode-react-native|vsm|0.9.1
JavaScriptSnippets|xab|1.7.2
vscode-proto3|zxh|0.2.2

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
What language are you debugging?

**Comment by albaizzz** [comment]
golang, Already installed golang debugger
