### ISSUE TITLE
Weird Terminal background color

### ISSUE THREAD

**Issue by yooceii** [Microsoft/vscode#71856]
![image](https://user-images.githubusercontent.com/19211761/55671177-1e972180-585b-11e9-8500-e58010bfc210.png)

![image](https://user-images.githubusercontent.com/19211761/55671186-35d60f00-585b-11e9-87fb-233b55c1eede.png)

![image](https://user-images.githubusercontent.com/19211761/55671315-f9a3ae00-585c-11e9-8d30-da1de950cce8.png)

- VSCode Version: 1.33.0
- OS Version:  Windows 10 10.0.17763.404
Actually this issue has been occured for more than half a year.

Steps to Reproduce:

1. Open any other shell in integrated terminal except cmd.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
