### ISSUE TITLE
Unable to do rename symbol

### ISSUE THREAD

**Issue by haani104** [Microsoft/vscode#71858]
Issue Type: <b>Bug</b>

![Screenshot 2019-04-06 at 9 00 01 PM](https://user-images.githubusercontent.com/6011865/55671602-592aa980-58af-11e9-8420-6e1f3d27f47a.png)

Not sure if these are correct steps, but this has what happened to me.

1. In a file, inside a function, when I try to click `Rename Symbol`, it basically displays a error in a pop over which is not fully visible but seems to be coming from some of the node modules.
2. This is my project https://github.com/haani104/js-refactoring, and it was happening in `createStatementData.js` file. On whatever variable or function name I was trying to do rename symbol, it always gave the above pop over

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|-psn_0_1831359|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
prettier-vscode|esb|1.8.1
dotenv|mik|1.0.1
vscode-import-cost|wix|2.12.0

</details>

**Comment by mjbvz** [comment]
I can't repo this.

Can you please share the full error by:

1. In VS Code, run the `Developer: Toggle developer tools` command
1. Open the developer tools console in the dev tools
1. Reproduce the problem

There should be a new error printed. Please share the text of this error

**Comment by mjbvz** [comment]
Closing as not reproducible
