### ISSUE TITLE
Ability to search in "problems output 'debug console' terminal" tabs/windows

### ISSUE THREAD

**Issue by haneefdm** [Microsoft/vscode#71860]
I've searched and could not find a similar request. Or, perhaps I am using the GUI wrong. Find seems to be limited to the document window or across all files in my workspace.

These windows at the bottom right where most of my debugging really happens. It would be super nice to be able to search within these windows. You know, its own search bar. Sometimes, I have a LOT of text in there and I have to copy the text to another file/text-editor and search there. Many extra steps and I have to constantly re-copy as new output appears.

**Comment by roblourens** [comment]
This is supported in problems, output, and terminal but not debug console: https://github.com/Microsoft/vscode/issues/4338
