### ISSUE TITLE
Intellisense doesn't work with snippets.

### ISSUE THREAD

**Issue by dsznajder** [Microsoft/vscode#71863]
- VSCode Version: 1.33.0
- OS Version: macOS Mojave 10.14.4 (18E226)

Steps to Reproduce:
1. Use snippet extension which will involve import path
2. Intellisense is not triggered to search `node_modules` or module paths, also it ignores named exports inside package / module.

Issue in package: dsznajder/vscode-es7-javascript-react-snippets#61
Example: https://youtube.com/watch?v=QOi44GXGJy0

P.S. I'm not sure if this ever worked, so maybe it's more like a feature request.

**Comment by polishedwp** [comment]
FYI. I reverted back to VSCode 1.32.3 (February 2019) version and everything works fine. It appears the March release broke Intellisense with snippets.

**Comment by jrieken** [comment]
Suggestions as you type are disabled inside snippets and can be enabled via `editor.suggest.snippetsPreventQuickSuggestions`

**Comment by polishedwp** [comment]
I would suggest this is not a fix. This problem started with the new version. I did add `"editor.suggest.snippetsPreventQuickSuggestions": false` to the `json` with no effect. I did not have this setting in my `json` before and `vscode-es7-javascript-react-snippets` worked perfectly. 

As you can see, it still presents the loading:
![Screen Shot 2019-04-09 at 5 45 54 AM](https://user-images.githubusercontent.com/13651291/55791839-630a0380-5a8d-11e9-9b88-b6ae38bf3f17.png)

The template eventually works, after a VERY long delay (at least a minute), inserting the snippet but autocomplete is unusable.
![Screen Shot 2019-04-09 at 5 50 53 AM](https://user-images.githubusercontent.com/13651291/55791880-7321e300-5a8d-11e9-8b66-3e7951660bab.png)
