### ISSUE TITLE
Typescript will include interfaces from files even when not imported.

### ISSUE THREAD

**Issue by Olian04** [Microsoft/vscode#71869]
- VSCode Version: 1.33.0 & 1.34.0-insider
- OS Version: Windows 10 & Ubuntu 18.04 (haven't tested as much in Ubuntu as in Windows)

Steps to Reproduce:

1. Create these 3 files:

```ts
// file1.ts
interface Console {
  ONE: String  
}
console.ONE = 'file one';
```
```ts
// file2.ts
interface Console {
  TWO: String  
}
console.TWO = 'file two';
```
```ts
// index.ts
import './file1';

console.log(console.ONE); // (1)
console.log(console.TWO); // (2)
console.log(console.THREE); // (3)
```

2. Reload window without extensions

3. In `index.ts`:
* `(1)` will work both in vscode and when passed to tsc.
* `(2)` will fail both in vscode and when passed to tsc.
* `(3)` will fail both in vscode and when passed to tsc.

4. Open `file2.ts`

5. In `index.ts`:
* `(1)` will work both in vscode and when passed to tsc.
* `(2)` **will work (even though it shouldn't) in vscode and will fail (as expected) when passed to tsc.**
* `(3)` will fail both in vscode and when passed to tsc.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
If your file does not have any imports or exports, it is put in the global scope. That's why case two works in VSCode
