### ISSUE TITLE
Incorrect SHA-256 Hash for 1.33.0 Mac .zip Download...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#71865]
hey there :wave:

i think the download website shows the wrong SHA-256 Hash for the macOS download file here:

https://code.visualstudio.com/download (click the "See SHA-256 Hashes” button / link)

the sha displayed there is:

`bda029d95e0dfad274a23017a266310075a753187e972f65da44376c3b6b3d60`

but checking the downloaded `.zip` file here locally on my mac with:

`openssl sha -sha256 -binary ~/Downloads/VSCode-darwin-stable.zip | xxd -p -c 256`

returns:

`d90a9c19f68aa9be5ebeab025fe2bb05389f1ed697df945af9024a4f9b9f30b9`

- VSCode Version: `v1.33.0`
- OS Version: `macOS@10.13.6`

Steps to Reproduce:

1. download the mac distribution from https://code.visualstudio.com/download
2. generate a sha256 hash of the downloaded file using `openssl` (see above for full command)
3. compare generated hash with the one listed on the vscode download website

**Comment by octref** [comment]
@joaomoreno I got the same `bda029d95e0dfad274a23017a266310075a753187e972f65da44376c3b6b3d60` sha256 hash from update service.

**Comment by joaomoreno** [comment]
Argh!

This was fixed yesterday by chance, by https://github.com/Microsoft/vscode/commit/3bd3d74a2c7cd564c374d7010a169babea5a6f31.

I've updated the hashes to the correct ones. :+1:
