### ISSUE TITLE
Weird window title left padding on windows 10

### ISSUE THREAD

**Issue by mmis1000** [microsoft/vscode#71861]
- VSCode Version: 1.33.0
- OS Version: windows 10 18362

Steps to Reproduce:

1. open vscode
2. click on update check when there is no update exist
3. windows popup
4. you saw the window title with weird no left padding

weird title with no left padding
There is almost no space left between the V and window border
![圖片](https://user-images.githubusercontent.com/2993977/55672327-568a7d00-58cc-11e9-8697-f009348a37c6.png)

other normal window in windows10 (take dialog popup by firefox for example)
It has left padding that almost equal to top padding
![圖片](https://user-images.githubusercontent.com/2993977/55672332-6d30d400-58cc-11e9-9023-fe5de12f2335.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@bpasero This seems like Electron's fault. We could add 2 spaces before the product name when we do this but I don't know how big a deal this is.

**Comment by bpasero** [comment]
I would not change this on our end but ask Electron to address this.
