### ISSUE TITLE
Blurry/glitchy font in custom title bar (minor issue)

### ISSUE THREAD

**Issue by faelv** [Microsoft/vscode#71862]
Issue Type: <b>Bug</b>

![Screenshot from 2019-04-06 13-31-43](https://user-images.githubusercontent.com/33964313/55672623-835e7600-5873-11e9-887d-5de48393a850.png)

**Steps to reproduce**
- Enable the custom title bar (I know it's now disabled by default)
- Open some files in VS Code
- Switch file tabs a couple times

**Actual result**
Custom title bar font gets blurry

**Expected result**
No changes to the font

**Extra info**
- Don't happens in 1.32 or older
- OS: Linux Mint 18.3 Cinnamon x64 (based on Ubuntu 16.04)
- Seems to be caused by a _transform_ CSS property (?)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 881)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (3.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
gitlens|eam|9.5.1
good-taste-theme|fae|2.0.1
php-debug|fel|1.13.0
vscode-yarn|gam|1.6.0
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
php-docblocker|nei|1.8.0
material-icon-theme|PKi|3.7.0

</details>

**Comment by ecgan** [comment]
FYI I'm seeing this issue too. With custom title bar.

![image](https://user-images.githubusercontent.com/417342/55747113-1cf17780-5a6e-11e9-9428-ccd1356a14fc.png)

Below info are copied from VS Code Help > About window:

Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic
