### ISSUE TITLE
Partial tree refresh breaks tree structure

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7187]
Steps to Reproduce:

1.  Comment out following line https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L173
2. Build from source, have two editors open side by side, and drag editors in the open editors view
3. Notice tree gets broken, children of an open editor become it's siblings

I verified that the getId and getChildren calls on the open editors side look good
I believe this is happening because I am doing a partial tree refresh. If I do a full tree refresh all is good - thus the workaround

**Comment by joaomoreno** [comment]
Can't reproduce. This is better if you show me at your desk...

**Comment by isidorn** [comment]
@joaomoreno I can still reproduce this - when you feel like it just drop by my desk
