### ISSUE TITLE
File watching seems to be broken in 1.34

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#71873]
Issue Type: <b>Bug</b>

I am seeing issues with the built-in Git extension and GitLens not updating/refreshing when files change. With GitLens I'm not seeing my file watchers (`workspace.createFileSystemWatcher`) fire anymore.

/cc @bpasero 

VS Code version: Code - Insiders 1.34.0-insider (d234937aedcbc265d2272ba5861125293239f9c7, 2019-04-05T05:18:43.251Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.16GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
@eamodio exact steps to reproduce would make the process of addressing this issue faster. This includes folder you opened (1 or multiple) and the watcher pattern you setup.

**Comment by bpasero** [comment]
I cannot reproduce with the following sample extension on macOS:

```
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "test-ts" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		// The code you place here will be executed every time your command is executed


		const watcher = vscode.workspace.createFileSystemWatcher('**');
		watcher.onDidChange(console.log);
		watcher.onDidCreate(console.log);
		watcher.onDidDelete(console.log);

		// Display a message box to the user
		vscode.window.showInformationMessage('Hello World!');
	});

	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() { }

```

**Comment by eladcandroid** [comment]
Happens for me too with the new version  .. Saving a simple index.html file (that under git repository of course..) and  not get any git change info... 

VS code version: 1.33
MacOS Mojave 10.14.2

Demo:
https://github.com/eladcandroid/todo-list-app/raw/master/Screen%20Recording%202019-04-07%20at%2010.04.20.mov

**Comment by eamodio** [comment]
@bpasero I'm opening a single folder, and any changes to files don't show up in the SCM sidebar until I hit the refresh button. Opening the same folder in 1.33 doesn't have any issue. I see the behavior with the SCM sidebar even with all extensions disabled.

In GitLens here are the 2 places I call `createFileSystemWatcher`:
https://github.com/eamodio/vscode-gitlens/blob/3c4bb8c900b8cb1ead7f5e740fab106450a74502/src/git/models/repository.ts#L123-L147

https://github.com/eamodio/vscode-gitlens/blob/3c4bb8c900b8cb1ead7f5e740fab106450a74502/src/git/models/repository.ts#L420-L429

**Comment by eamodio** [comment]
@bpasero Using your sample, it seems to only be reproducible using a folder, if I open a workspace (that has more then 1 folder) it seems to work.

**Comment by YangHanlin** [comment]
Having the same issue now. This bug does appear on my VSCode and I am using a folder (not a workspace). I also find that now current branch shown on the status bar does not automatically change if current branch is changed using `git branch` from the command line.

**Comment by bpasero** [comment]
Got it, a regression where the Windows watcher was not included anymore in the build. This has nothing to do with issues seen in our stable release (where this change is not yet in) and also does not surface on any os other than Windows.
