### ISSUE TITLE
Unable to install any extension

### ISSUE THREAD

**Issue by Soomrojb** [Microsoft/vscode#71879]
Issue Type: <b>Bug</b>

I am struggling with extension(s) installation, they just stuck forever saying "Installing". The extension folder is empty, I have tried installing multiple extension over couple of days however nothing is working. Today I have uninstalled visual code, downloaded the latest version and installed it again however the issue is still there.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.96GB (0.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
Please try following
- Set the log level to trace using command `F1 > Set Log Level`
- Open Shared process logs folder using command `F1 > Open View.. > Log (Shared)`
- Try installing the extension again

Provide us the logs to understand the issue

**Comment by Soomrojb** [comment]
I had to reinstall Windows and it's working fine in new installation now.

**Comment by sandy081** [comment]
Ok closing this. Please reopen this issue with requested info if you see it again.
