### ISSUE TITLE
Save opened editors session to a file (inside the project dir) for migration

### ISSUE THREAD

**Issue by sgon00** [microsoft/vscode#71876]
[Feature Request]

Hi, I constantly change my project directory name and move the project dir around different paths and move it to other computers. But once the directory name is changed or moved to other computers, I lost my opened editors session (unable to restore opened editors on startup `code projectDir`). This problem drives me crazy. 

I would like to save the opened editors session to a file with relative paths stored in it to overcome this issue. (It has to be relative path to the project directory, otherwise it won't work once the path is changed). 

Thank you very much for your support.

**Comment by TejDNagaraja** [comment]
Hi @sgon00 ! I'm looking to take this issue with my colleague @rthaneda as an open source contribution for class. I will post any relevant updates here.

**Comment by sgon00** [comment]
@TejDNagaraja thank you very much for your help. :)

**Comment by kanlukasz** [comment]
I hope it will only be optional. Many people do not like it when the application automatically creates a file in the directory

**Comment by sgon00** [comment]
@bpasero Dear sir, I kinda disagree on the final decision on this feature request. If this is not supported, what can I do to restore opened editors when I move the project directory location on file system? Thanks a lot.

**Comment by sgon00** [comment]
@kanlukasz I think the "many people" are using Windows OS. Creating files is a common technique in Linux/MacOS/Unix operating systems. For instance, Finder.app in MacOS will create `.DS_Store` on each folder it opened. The current vscode behavior makes users so hard to move their projects or work on different computers at home and office. Btw, vscode is not designed for Windows only.
