### ISSUE TITLE
SOCKS5 proxy worked but the regex verification only accept "https"

### ISSUE THREAD

**Issue by rzhb** [microsoft/vscode#71877]
- VSCode Version: 1.33.0
- OS Version: Win10

Steps to Reproduce:

1. Go to `Settings` `User Settings` `Application` `Proxy` `proxy`
2. Input a `SOCKS5` proxy like `socks5://127.0.0.1:8080`
3. The SOCKS5 proxy actually worked.
4. The problem is the regex verification only accept `https`

Related Issues: #58080 #27838 #9971
These Issues are locked and I can't make a  comment. This is really inconvenience.
@joaomoreno

**Comment by chrmarti** [comment]
The ProxyResolver and vscode-proxy-agent will need to add support for SOCKS5. https://www.npmjs.com/package/socks5-client might help.
