### ISSUE TITLE
the new c++ highlight is bad. some variables turn blue and some not

### ISSUE THREAD

**Issue by tkj666** [Microsoft/vscode#71875]
Issue Type: <b>Feature Request</b>

'operator' lost its colour, too

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

**Comment by vsamy** [comment]
Same here, lot of hightlight has changed.

VS Code version: Code 1.33.0
OS Version: Windows 10 Pro for Workstation 10.0.17134

**Comment by alexr00** [comment]
Duplicate of #71821
