### ISSUE TITLE
Integrated terminal starts completely blank until after pressing enter

### ISSUE THREAD

**Issue by JamesMowery** [Microsoft/vscode#71870]
Issue Type: <b>Bug</b>

When using the integrated Terminal, the text area is blank until after pressing enter. Seems like it is exactly related to this issue: https://github.com/Microsoft/vscode/issues/57803

I attempted to disable ConPTY as mentioned in that issue, and the issue still remains.

I am on a fresh install of Windows 10 and a fresh installation of Visual Studio Code with no extensions.

![Issue1](https://user-images.githubusercontent.com/868178/55677959-6727fc80-58a6-11e9-900b-1a356bdff606.png)

![Issue2](https://user-images.githubusercontent.com/868178/55677960-6abb8380-58a6-11e9-98bc-14b71070c789.png)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

**Comment by callmeblessed** [comment]
on my workspace, I can see 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved. 

but cannot see the prompt (C:\Project\Names\xxxx\)

but I can type the command line and it work.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
