### ISSUE TITLE
could not create file

### ISSUE THREAD

**Issue by Lwenli1224** [Microsoft/vscode#71871]
Issue Type: <b>Bug</b>

Unable to create new files

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T16:15:50.230Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (3.45GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
ejs-language-support|Qas|0.0.1
vsc-material-theme-italicize|Ser|0.0.14
ejs-snippets|Tao|0.1.0
terminal-tabs|Tyr|0.2.0
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.3
vscode-javascript-snippet-pack|aka|0.1.5
vscode-color|ans|0.4.5
eggjs|ati|0.3.1
mpvue-snippets|ban|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-wxml|cod|0.1.9
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.25.1
vscode-eslint|dba|1.8.2
app-migrator|deb|0.0.6
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.2.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.5.1
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
we-app-vscode|eme|0.8.0
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
markdown-table-formatter|fcr|1.4.1
file-icons|fil|1.0.16
flow-for-vscode|flo|1.1.1
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.8
terminal|for|0.0.10
vscode-yarn|gam|1.6.0
vscode-flow-ide|gca|1.2.0
vscode-nginx-conf-hint|han|0.1.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
vscode-favorites|how|1.4.0
path-autocomplete|ion|1.13.2
search-node-modules|jas|1.3.0
webpack|jer|2.1.3
azure-functions-tools|joh|0.3.3
intellij-idea-keybindings|k--|0.2.31
auto-comment-blocks|kev|1.0.1
vscode-codemetrics|kis|1.18.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
sftp|lix|1.12.2
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.6.0
prettify-json|moh|0.0.3
vscode-autoprefixer|mrm|2.2.0
vscode-azurefunctions|ms-|0.16.0
vscode-language-pack-zh-hans|MS-|1.33.2
azure-account|ms-|0.8.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.18
vsliveshare-audio|ms-|0.1.48
debugger-for-chrome|msj|4.11.3
vscode-paste-image|mus|1.0.4
vscode-for-node-js-development-pack|nod|2.0.1
prettier-standard-vscode|num|0.5.0
vetur|oct|0.18.1
code-rhythm|onv|1.0.6
vuehelper|oys|0.1.0
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
minapp-vscode|qiu|1.13.0
LiveServer|rit|5.5.1
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.8
vscode-nginx|sha|0.6.0
markdown-preview-enhanced|shd|0.3.13
vscode-leetcode|she|0.13.3
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
language-stylus|sys|1.11.0
react-beautify|tai|0.3.0
vscode-markdown-paste-image|tel|0.12.0
stylus-supremacy|thi|2.12.7
vscode-npm-scripts|tra|0.2.1
vscode-icons|vsc|8.4.0
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
html-css-class-completion|Zig|1.18.0

(15 theme extensions excluded)

</details>

**Comment by Lwenli1224** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

Clicking on the new file did not respond

**Comment by aeschli** [comment]
You mean `File > New File`. It didn't open an new empty editor?

**Comment by aeschli** [comment]
Closing due to lack of information
