### ISSUE TITLE
Terminal crashes when pasting text

### ISSUE THREAD

**Issue by FancyBanana** [Microsoft/vscode#71883]
Version: 1.33.0
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:08:57.775Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.5-1-MANJARO

Steps to Reproduce:

1. Copy text from anywhere
2. Paste it into terminal ( either `ctrl-shift-v` or `right-click -> paste`)
3. Terminal crashes

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by FancyBanana** [comment]
Update: After some research I found out that my ZSH was crashing. Therefore the issue is not about the terminal crash per se, but about absence of any error message.

**Comment by Tyriar** [comment]
The terminal will exit using the code that the shell exits with, so it sounds like this is purely a zsh issue.
