### ISSUE TITLE
Many VS Code running in Task manager

### ISSUE THREAD

**Issue by Viipiin** [Microsoft/vscode#71882]
Hi,
Many VS code instances are running in the background that is impacting performance.
also, VS Code crashing much time when I work in recent version 1.33.
Please help.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	 15472	code main
    0	   138	  9160	   window (ReactAppsPractice - Visual Studio Code [Administrator])
    0	    35	  4264	     searchService
    0	   134	  6764	     extensionHost
    0	     6	 12124	     winpty-process
    0	    11	 18124	       console-window-host (Windows internal process)
    0	    72	 18264	       "C:\Program Files\Powershell\6\pwsh.exe"
    0	     4	 13268	         C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    33	 12040	           "C:\Program Files\nodejs\\node.exe"  "C:\Users\Viipiin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" start
    0	     4	 18324	             C:\WINDOWS\system32\cmd.exe /d /s /c react-scripts start
    0	    23	  9896	               node   "E:\SPFx\ReactAppsPractice\reactjs-essentialtraining\node_modules\.bin\\..\react-scripts\bin\react-scripts.js" start
    0	   128	  1540	                 node E:\SPFx\ReactAppsPractice\reactjs-essentialtraining\node_modules\react-scripts\scripts\start.js
    0	    12	 13908	     electron-crash-reporter
    0	    10	 18320	     watcherService 
    0	    10	 15128	       console-window-host (Windows internal process)
    0	    66	  9848	   window (Issue Reporter)
    0	   168	 11468	   gpu-process
    0	    70	 14808	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ReactAppsPractice - Visual Studio Code [Administrator])
|    Folder (ReactAppsPractice): 45 files
|      File types: js(12) json(10) css(5) html(3) ico(3) gitignore(3) md(3)
|                  svg(3) log(1) sqlite(1)
|      Conf files: package.json(3);
```

</details>
<details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.4.0
code-gnu-global|aus|0.2.2
vscode-standardjs|che|1.2.3
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.1.4
gitlens|eam|9.5.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
spfx-snippets|eli|1.7.1
vscode-great-icons|emm|2.1.47
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
code-runner|for|0.9.7
beautify|Hoo|1.4.11
rest-client|hum|0.21.2
csharpextensions|jch|1.3.0
Angular2|joh|7.0.1
cmake-tools-helper|mad|0.2.1
ajax-snippets|Mem|1.9.0
Angular-BeastCode|Mik|7.2.6
sp-tools|Mik|0.3.0
HTMLHint|mka|0.6.0
vs-rest-api|mkl|3.0.1
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
mono-debug|ms-|0.15.8
node-debug2|ms-|1.32.1
powershell|ms-|1.12.0
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vetur|oct|0.18.1
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
typescript-hero|rbb|3.0.0
vscode-spfx-deploy-package|Ren|1.1.0
code-settings-sync|Sha|3.2.8
move-ts|str|1.11.3
jstool|sun|1.1903.0
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
shell-launcher|Tyr|0.3.0
cmake-tools|vec|1.1.3
vscode-icons|vsc|8.4.0
vscode-react-native|vsm|0.9.1
quokka-vscode|Wal|1.0.205
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by Viipiin** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
