### ISSUE TITLE
Run multiple launch.json test configurations in sequence

### ISSUE THREAD

**Issue by ericbiewener** [microsoft/vscode#71885]
A `compounds` option currently exists for launching configurations at the same time, but this doesn't work for the test suites I'm trying to run (see the configurations starting [here](https://github.com/ericbiewener/vscode-vandelay/blob/master/.vscode/launch.json#L70)). The first configuration runs fine but the second one doesn't appear to correctly launch. Even if it did, I don't think this would be preferable to running tests in sequence since it creates a potentially less accurate integration test environment.

Running configurations in sequence would be an ideal solution. The test output would need to be preserved in the debug console between each suite.

**Comment by isidorn** [comment]
This is a fair feature request. Though it is not on our immediate plane. Thus assignign to backlog.

**Comment by 1RedOne** [comment]
This would be very useful to me.  I have three dotnet core microservices I run which all have a shared dependency and I frequently get errors of 

> Performance is degraded.  This can occur when the same project is built more than once in parallel

I use launch.json with a compound to launch my three webservices and often times one of them will fail and I'll need to launch it manually afterwards.  If I could configure the sequence of the items, perhaps with a configurable time delay, i'd be set.

**Comment by IAmIlliest** [comment]
Putting in a bump here to re-open this one. Whilst I know you can hack around this using tasks.json and preLaunchTask to fire a sleep via the shell or some sort of polling script, I feel like this sort of orchestration these days should be built into the launch.json capabilities directly?
