### ISSUE TITLE
Asked twice for Github credentials after wrong password entered

### ISSUE THREAD

**Issue by omer-g** [Microsoft/vscode#71887]
- VSCode Version: 
Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
- OS Version:
Windows 7

Steps to Reproduce:

1. Push to Github
2. Enter wrong password
3. Enter correct credentials on the external Github window that opens.

After this, I am asked to reenter the credentials in VSCode once more. It would be nice to not have to enter the credentials twice.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, but slightly different. After disabling the extensions, I got the external Github prompt right away, and was still asked to reenter the credentials in VSCode afterwards.
Once I reactivated the extensions, the latter behavior persisted, at least for now.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the dialog which asks for credentials?

**Comment by omer-g** [comment]
Yes, here is the screenshot:
![Screenshot 2019-04-09 10 43 42](https://user-images.githubusercontent.com/26910173/55782397-dbd08600-5ab4-11e9-977f-a5e1b0c468c3.png)

**Comment by joaomoreno** [comment]
This is the Github credential manager, probably from Github Desktop. I suggest you reach their support instead.
