### ISSUE TITLE
Organize Imports marks a file as dirty even if it doesn't change anything

### ISSUE THREAD

**Issue by NiloCK** [Microsoft/vscode#71889]
- VSCode Version: 1.33
- OS Version: Windows 10

Steps to Reproduce:

1. Open a typescript file with disorganized imports.
2. Run `Organize Imports` command.
3. Save the file.
4. Run `Organize Imports` again.
5. Note that the file is marked as dirty despite not having changed.

By comparison, running `Format Document` marks the file dirty only if there are changes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/22912

**Comment by NiloCK** [comment]
Thanks! I did in fact do a search, but no beans.
