### ISSUE TITLE
Multi-line output breaks debug console auto-scroll

### ISSUE THREAD

**Issue by guusw** [Microsoft/vscode#71884]
Issue Type: <b>Bug</b>

Outputting a message to the debug console that has newlines seems to break automatic scrolling. 
After unlocking the auto-scroll an trying to reenable it vscode seems to randomly scroll towards the middle or start of the output upon receiving new output.

This is especially obvious when using the go extension since it puts anything received in stdout in the debug console.
I used the following simple program to test this issue.

```go
package main

import (
	"time"
	"fmt"
)
func main() {
	for {
		fmt.Printf("a\nb\nc\nd")
		time.Sleep(time.Second/2)
	}
}
```

![](https://d.tdrz.nl/9G5Sho1Q.gif)

I could also reproduce this on the insider build with only the go extension installed. (1.34.0 d234937)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (24.43GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/vscode-go|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
spellright|ban|3.0.38
vscode-markdownlint|Dav|0.25.1
lua-debug|dev|1.1.1
xml|Dot|2.4.0
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.3
vscode-great-icons|emm|2.1.47
vscode-todo-plus|fab|4.13.0
fxd|guu|0.0.1
vscode-nginx-conf-hint|han|0.1.0
asciidecorator|hel|0.2.0
rest-client|hum|0.21.2
latex-workshop|Jam|6.3.0
svn-scm|joh|1.47.12
theme-dark-plus-contrast|k3a|0.1.101
theme-karyfoundation-themes|kar|18.2.1
velocity|luq|0.7.1
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
Go|ms-|0.9.2
mono-debug|ms-|0.15.8
powershell|ms-|1.12.0
lsp-inspector-webview|oct|0.0.2
indent-rainbow|ode|7.4.0
project-snippets|reb|0.5.0
java|red|0.42.1
code-settings-sync|Sha|3.2.7
vscode-nginx|sha|0.6.0
indenticator|Sir|0.6.0
shader|sle|1.1.4
vscode-autohotkey|sle|0.2.2
shader-toy|ste|0.7.10
selectline-statusbar|tom|0.0.2
unity-debug|Uni|2.7.2
vscode-lldb|vad|1.2.2
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.15.1
vscode-maven|vsc|0.16.0
swig|zhu|0.0.5

(33 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/71737
