### ISSUE TITLE
Highlighting of fenced code in markdown for known but non-default languages

### ISSUE THREAD

**Issue by zhaouv** [Microsoft/vscode#71888]
For example, I installed [the language support of Julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia). But I have to change those files manually, then the fenced code in markdown \`\`\`julia\n [content] ``` could be highlighted

+ `%USERPROFILE%\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-basics\package.json`  
```diff
					"meta.embedded.block.csharp": "csharp",
-					"meta.embedded.block.fsharp": "fsharp"
+					"meta.embedded.block.fsharp": "fsharp",
+					"meta.embedded.block.julia": "julia"
				}
			}
		],
```

+ `%USERPROFILE%\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-basics\syntaxes\markdown.tmLanguage.json`  
```diff
		},
+		"fenced_code_block_julia": {
+			"begin": "(^|\\G)(\\s*)(`{3,}|~{3,})\\s*(?i:(julia|jl)(\\s+[^`~]*)?$)",
+			"name": "markup.fenced_code.block.markdown",
+			"end": "(^|\\G)(\\2|\\s{0,3})(\\3)\\s*$",
+			"beginCaptures": {
+				"3": {
+					"name": "punctuation.definition.markdown"
+				},
+				"5": {
+					"name": "fenced_code.block.language"
+				},
+				"6": {
+					"name": "fenced_code.block.language.attributes"
+				}
+			},
+			"endCaptures": {
+				"3": {
+					"name": "punctuation.definition.markdown"
+				}
+			},
+			"patterns": [
+				{
+					"begin": "(^|\\G)(\\s*)(.*)",
+					"while": "(^|\\G)(?!\\s*([`~]{3,})\\s*$)",
+					"contentName": "meta.embedded.block.julia",
+					"patterns": [
+						{
+							"include": "source.julia"
+						}
+					]
+				}
+			]
+		},
		"fenced_code_block_dart": {
```
```diff
				{
					"include": "#fenced_code_block_fsharp"
				},
+				{
+					"include": "#fenced_code_block_julia"
+				},
				{
					"include": "#fenced_code_block_dart"
				},
```

Could it achieved that the fenced code automatically highlight known languages?

**Comment by faelv** [comment]
This may help you: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example

**Comment by zhaouv** [comment]
Thanks!  
Follow this clue I find another repository.
updating a dict like 
```js
const languages = [
    { name: 'css', language: 'css', identifiers: ['css', 'css.erb'], source: 'source.css' },
    { name: 'basic', language: 'html', identifiers: ['html', 'htm', 'shtml', 'xhtml', 'inc', 'tmpl', 'tpl'], source: 'text.html.basic' },
    { name: 'ini', language: 'ini', identifiers: ['ini', 'conf'], source: 'source.ini' },
    { name: 'java', language: 'java', identifiers: ['java', 'bsh'], source: 'source.java' },
    { name: 'lua', language: 'lua', identifiers: ['lua'], source: 'source.lua' },
```
in https://github.com/mjbvz/vscode-comment-tagged-templates/blob/master/build/languages.js 
people can build their own injections.

and the question is also that everyone have to build their own extensions.

is there any `meta-operation`? One extension scans the vscode and get the dict. And generates `.tmLanguage.json` dynamically.

**Comment by faelv** [comment]
To add a new grammar and thus add syntax highlight for it you need an extension. Take a look at the extension development documentation, you are probably interested in this: https://code.visualstudio.com/api/references/contribution-points#contributes.grammars

**Comment by zhaouv** [comment]
If a new language (named as NL) is created.

An extension `NL-language-support` is created to describe the syntax.

And there should be an extension `markdown-NL` to support it.

But the markdown is not the only language using fenced code. 

For every extension which works similarly to markdown and uses injecting grammars, 
there should be a new extension `xxx-NL`.

It is strange. Why not the `NL-language-support` provide a `{ name: 'NL', language: 'NL', identifiers: ['NL',’NLAlias’], source: 'source.NL' }` to the VSCode, And the markdown-like extensions fetch the list from the VSCode and generate injections.

And there will be only one new extension `NL-language-support` needed.

**Comment by mjbvz** [comment]
Extensions can contribute support for their language in markdown codeblocks by following these instructions: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example

Generalizing this is out of scope
