### ISSUE TITLE
startup with newUntitledFile doesn't work

### ISSUE THREAD

**Issue by hfcheng66** [Microsoft/vscode#71890]
- VSCode Version: 1.33.0
- OS Version: Mac Mojave 10.14.4

Steps to Reproduce:
1. in settings, set "workbench: startup editor" to "newUntitledFile"
2. close all tabs and quit vs code.
3. start vs code, it starts without editor open up. it stays the blank page with 4 command shortcut in the middle.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by konradw86** [comment]
niedz., 7 kwi 2019, 22:22 użytkownik hfcheng66 <notifications@github.com>
napisał:

**Comment by konradw86** [comment]
Tak

pon., 8 kwi 2019, 12:54 użytkownik Benjamin Pasero <notifications@github.com>
napisał:
