### ISSUE TITLE
Highlighting in Suggest Widget

### ISSUE THREAD

**Issue by mrGibi** [microsoft/vscode#71892]
- VSCode Version: all VSCode versions including Insider
- OS Version: macOs 10.14.4 but I suppose its the same on every platform

Steps to Reproduce:
Ok, lets start with first screen shot. **Notice where I have left my mouse cursor**:
<img width="521" alt="Zrzut ekranu 2019-04-07 23 34 30" src="https://user-images.githubusercontent.com/29686195/55690290-bac24500-598f-11e9-8cfc-516a04552036.png">

Lets start typing:
<img width="519" alt="Zrzut ekranu 2019-04-07 23 34 50" src="https://user-images.githubusercontent.com/29686195/55690292-cb72bb00-598f-11e9-97d6-a6c2e46b1113.png">
Notice **what** is being highlighted and **where**. 
There are two hightlighted lines. 
- First one (with `confirm`) is what will be used if I press `tab` for autocompletion. Also it will be a starting point for keyboard `up` and `down` arrow buttons to navigate manually through the list.
- Second highlighted line (with `constructor`) is where I have left my mouse cursor earlier, before I started typing. 

Additionally (and this is pretty important and annoying) ONLY mouse cursor have ability to use `list.focusForeground` theme setting in Suggest Widget (thats why `contructor` or more precisly `nstructor` is white). We end up in situation where item that is NOT going to be used for autocomplete has higher VISUAL priority. 
(We only have `editorSuggestWidget.selectedBackground` to visually mark an Suggest Item that will be used for autocompletion. There is no `editorSuggestWidget.selectedForeground` to make it pop more.)

How (in my opinion) it should work:
1. Mouse cursor should NOT hightlight Suggest Widget items only becouse it was left in that spot. It should highlight an item only if we move the mouse cursor.
2. If mouse cursor is moved it should take the visual priority, **unhightlight** first line (with `confirm` in screenshots above), and highlight only the item under the cursor, although this might lead to some confusion, for example: what if we hover Suggest Item with mouse and press `tab`... So this is something to consider.
3. This is very important: along with `editorSuggestWidget.selectedBackground` there should be `editorSuggestWidget.selectedForeground` setting to achieve higher visual priority for keyboard-related actions (like pressing `tab` button to autocomplete, or `up`/`down` arrow buttons to pick other suggestion) on selected Suggest Item

Does this issue occur when all extensions are disabled?: Yes

**Comment by faelv** [comment]
It has bothered me for a while too.

**Comment by usernamehw** [comment]
Related #64955

**Comment by misolori** [comment]
@joaomoreno we should not highlight any items in the suggest widget until a mouse event is triggered.

**Comment by joaomoreno** [comment]
Delegating that to @octref.

**Comment by octref** [comment]
#64955 was closed as out-of-scope. I'll close this one as well.

@mrGibi Your theme has an issue: It doesn't tell between `active` and `hover` items. See below for both `Nord` and `Dark+` theme when this behavior happens:

![image](https://user-images.githubusercontent.com/4033249/67035288-3f73e580-f0ce-11e9-91b4-bf5433b4397e.png)

![image](https://user-images.githubusercontent.com/4033249/67035295-46025d00-f0ce-11e9-9824-1577e93a6bd7.png)

I think this behavior itself is fine. After all, clicking your mouse right now would select the hover-highlighted item in the list.

**Comment by octref** [comment]
You can read more about theme colors in: https://code.visualstudio.com/api/references/theme-color#lists-and-trees
