### ISSUE TITLE
Autocompletion can be very annoying

### ISSUE THREAD

**Issue by madprops** [Microsoft/vscode#71896]
Video: https://dl.dropboxusercontent.com/s/8bzxke3xtyctjba/2019-04-07_17-52-46.mp4

In the video I'm simply trying to type "Tetris.something" but it autocompletes something else.
Actually I've been having to get used to hit Escape constantly very often to avoid undesired autocompletion. I'm not sure if this can be fixed, but the problem exists.

**Comment by mjbvz** [comment]
Set `"editor.acceptSuggestionOnCommitCharacter": false` if you don't want `.` to accept the current completion
