### ISSUE TITLE
Add hability to include/exclude the files to parse

### ISSUE THREAD

**Issue by svillar** [Microsoft/vscode#71893]
Issue Type: <b>Feature Request</b>

VS code currently offers the possibility of excluding/ignoring files/dirs from being shown on the UI or from search results. However all the files found in a project are unconditionally parsed. That might be a problem in large projects, like Chromium or WebKit for example.

In those code bases there are a huge amount of files/directories that should not be parsed from the Web engine developer POV, for example most of the HTML/JS tests, most third party libraries or even large portions of the engine which are barely inspected and/or touched by the engine developer.

The parsing happens relatively fast even for those projects (order of seconds not minutes), however it'd be nice to have the possibility to restrict it to a selected group of directories. That initial parsing would be faster but also the intellisense engine would work much more faster and would provide much better results. 

Does it make sense?

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.19.0-4-amd64

**Comment by mjbvz** [comment]
This is up to each extension / language provider. Please file issues against whatever extension are causing problems
