### ISSUE TITLE
Wrong console.log autocomplete

### ISSUE THREAD

**Issue by madprops** [Microsoft/vscode#71897]
Video: https://dl.dropboxusercontent.com/s/ahhczdjg77drbiy/2019-04-07_17-56-47.mp4

In this video you can see how not only "clog" doesn't trigger console.log in some cases (this actually never happens to me except on this demo) but actually it won't autocomplete/suggest things inside (this happens very often to me, pretty much all the time).

**Comment by nieldev** [comment]
Added a code snippit for thi limilar to th log(funtions)

**Comment by svipas** [comment]
@madprops Could you share:

1. Your extensions list.
2. Your user snippets.
3. Your settings.
4. VS Code version.

Also, try to reproduce same behavior in the Insiders build.

**Comment by madprops** [comment]
I just ran code-insiders --disable-extensions.

Video: https://dl.dropboxusercontent.com/s/ia40alkpx4wofvx/2019-04-08_15-33-55.mp4

clog turns into console.log as it should, but "game_started" is not being suggested.

**Comment by mjbvz** [comment]
What extensions do you have installed?

**Comment by madprops** [comment]
@mjbvz In normal vscode:

```
λ code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension amos402.scope-bar
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension gazugafan.vscode-indent-on-paste
code --install-extension jkchao.hy-theme
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension madprops.console-log-checker
code --install-extension madprops.fortune
code --install-extension madprops.nordico
code --install-extension madprops.occurrence-count
code --install-extension madprops.when-did-i-start-working
code --install-extension ms-python.python
code --install-extension peterfh.linesinfostatusbar
code --install-extension sdras.night-owl
code --install-extension sldobri.nord-5-stars
code --install-extension sleistner.vscode-fileutils
code --install-extension sveggiani.vscode-field-lights
code --install-extension zhuangtongfa.Material-theme
```

**Comment by madprops** [comment]
And snippets for JS:

```
{
/*
	// Place your snippets for JavaScript here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
*/
	"Print to console": {
		"prefix": "console.log",
		"body": [
			"console.log($1)"
		],
		"description": "Log output to console"
	}
}
```

**Comment by mjbvz** [comment]
I believe the behavior that the latest video shows is by-design. Set `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions in snippets (or manually trigger intellisense with ctrl+space)
