### ISSUE TITLE
can not perform global  search in current opening folder

### ISSUE THREAD

**Issue by 2qif49lt** [Microsoft/vscode#71901]
Issue Type: <b>Bug</b>

1.  win10 ,run VSCode with administrator privileges.
2. open a folder which contarin a Typescript node server project.
3. press CTRL+SHIFT+F, input  a short word, press ENTER.
4. results items are just from those opened files in the editer, no result from other files.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (23.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.4.11
vscode-language-pack-zh-hans|MS-|1.33.2
cpptools|ms-|0.22.1
Go|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-icons|vsc|8.5.0

</details>

**Comment by roblourens** [comment]
Do you see any error messages? 
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)
