### ISSUE TITLE
Include the extension that provides the formatter when choosing a formatter

### ISSUE THREAD

**Issue by connorshea** [Microsoft/vscode#71904]
When picking a Formatter to run for a file type, it'd be nice to see what extension is providing each formatter. This can make it easier to choose which formatter I want to use, or to open an issue to request that the extension use a more obvious name for their formatter :) (in this case, the Ruby extension accidentally provides the legacy formatter as well as the "current" formatter at the same time).

When in a situation like this, I'm not sure which to choose:

<img width="621" alt="Screen Shot 2019-04-07 at 6 20 49 PM" src="https://user-images.githubusercontent.com/2977353/55694905-8c367100-5973-11e9-9082-4aec7a0f273a.png">

Maybe have the extension name de-emphasized like the "Configured Tab Size" text in the indentation dropdown?:

<img width="615" alt="Screen Shot 2019-04-07 at 8 29 28 PM" src="https://user-images.githubusercontent.com/2977353/55695012-e0415580-5973-11e9-920e-fedec5aea5c3.png">

**Comment by jrieken** [comment]
We use the 'displayName' or 'name' (when not having the former) but it seems that there are multiple extensions with the same name... We should be more precise in that case.
