### ISSUE TITLE
feature-request: pause extension like chrome plugin manager

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#7190]
- VSCode Version: 1.1.1
- OS Version: oxs 10.11.4

In china, install extension is very slowly, sometime i want to pause one extension at some project

**Comment by jrieken** [comment]
>  sometime i want to pause one extension at some project

what do you mean by pausing? pausing the download/install?

**Comment by builden** [comment]
@jrieken I mean inactive extension, like this in chrome plugin manager
![image](https://cloud.githubusercontent.com/assets/9499016/15799234/13ecdbf2-2a88-11e6-9373-ec362f8ebfe6.png)

**Comment by rebornix** [comment]
From the snapshot, I suppose what @builden wants is enabling/disabling installed extensions.

**Comment by joaomoreno** [comment]
Duplicate of #2882
