### ISSUE TITLE
How to customize syntax colors, like how we cutomize fonts? 

### ISSUE THREAD

**Issue by ChangyuYan** [Microsoft/vscode#71905]
For example, I would like my python comments to be light blue. Is there a way to achieve that specifically without changing my current theme and other fonts?

**Comment by Socratides** [comment]
In settings.json, you can add: 
```json
"editor.tokenColorCustomizations": {
    "comments": "#0000ff"
}
```

Source: https://code.visualstudio.com/api/extension-guides/color-theme#syntax-colors
