### ISSUE TITLE
Fonts for Languages and panes

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#71909]
How can I set only specific languages to have a specific font and the rest of the panes in VSCode (terminal etc) have another font within `settings.json` ?

**Comment by svipas** [comment]
Currently it's impossible, you can use extension which overrides css or do it by yourself.

Duplicate of https://github.com/Microsoft/vscode/issues/26128 (I suggest to add 👍 to this issue)

**Comment by SheepDomination** [comment]
I know extensions which override CSS, what do you mean; *do it by yourself* ?

**Comment by svipas** [comment]
@SheepDomination you can override css by yourself without extension if you want

**Comment by SheepDomination** [comment]
@svipas How ?

**Comment by svipas** [comment]
You can find all info in this issue: https://github.com/Microsoft/vscode/issues/26128

**Comment by Tyriar** [comment]
You can set the terminal and debug console fonts currently.

/duplicate #26128
