### ISSUE TITLE
调试控制台输出多余空行.

### ISSUE THREAD

**Issue by AlecShang** [Microsoft/vscode#71907]
Issue Type: <b>Bug</b>

1. python输出语句,
print('AAA')
print('BBB')
2.在调试控制台输出的时候输出的是(with debug console print)
AAA
空行(a line)
BBB
3.在终端输出的时候是(with terminal priint)
AAA
BBB

如果将调试控制台的空行去掉.如何配置.在别的vscode环境中,2和3的输出结果是一致的,都是3.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T16:15:50.230Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-language-pack-zh-hans|MS-|1.33.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6352
vscode-yaml|red|0.4.0
bash-debug|rog|0.3.4
code-settings-sync|Sha|3.2.8
vscode-icons|vsc|8.5.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please start by filing this issue agains the python extension
