### ISSUE TITLE
Watch not working

### ISSUE THREAD

**Issue by silenthunter206** [Microsoft/vscode#71902]
Issue Type: <b>Bug</b>

I tried running XDEBUG. All this while it was working. But now after the vs code update, i cannot seem to run debug as usual. I cant add watch when debugging is running and afterwards. I cannot edit, add or delete my watch variables

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-php-cs-fixer|fte|0.1.0
open-php-html-js-in-browser|Pri|1.8.0
format-html-in-php|rif|1.5.3
bootstrap4-vscode|the|6.1.0
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by weinand** [comment]
Please file issue against php-debug
