### ISSUE TITLE
syntax highlight not work  sometimes

### ISSUE THREAD

**Issue by dxkite** [microsoft/vscode#71916]
Issue Type: <b>Bug</b>

the syntax highlight  somtimes the code file syntax highlight only 
half  rendered, then type a backspace  the  highlight  rendered return to normal.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.93GB (11.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
xml|Dot|2.4.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
githd|hui|2.1.0
php-cs-fixer|jun|0.1.118
vscode-regexp-preivew|le0|0.0.3
php-namespace-resolver|Meh|1.1.7
code-beautifier|mic|2.2.1
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6352
php-docblocker|nei|1.8.0
vscode-php-getters-setters|php|1.2.3
sass-indented|rob|1.5.1
vscode-hexdump|sle|1.7.2

</details>

![screenshot](https://user-images.githubusercontent.com/7450707/55710492-4e8e2280-5a1d-11e9-86ee-7f02c411cd0f.png)

**Comment by Malintha** [comment]
This is the worst a code can get. Yet no warnings or anything. 
![Selection_004](https://user-images.githubusercontent.com/3253761/60376352-2fbb7e80-99c3-11e9-98c1-8a847b762eff.png)
