### ISSUE TITLE
VS code using more than 1gb ram

### ISSUE THREAD

**Issue by RagedPanda** [Microsoft/vscode#71911]
Issue Type: <b>Performance Issue</b>

Before it was all working fine now it's slow down my pc as per instruction i disabled all my extension still ram cosumption is more than 1gb.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2675QM CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	    98	  1031	code main
    0	     8	  1032	   gpu-process
    0	    41	  1447	   shared-process
    0	   115	 29180	   window (job-request.service.js — services)
    0	    33	 29181	     extensionHost
    0	    41	 29183	       electron_node tsserver.js 
    0	    25	 29196	         electron_node typingsInstaller.js typesMap.js 
    0	    25	 29182	     watcherService
    3	    74	 29214	   window (Issue Reporter)
    2	     0	 29215	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (job-request.service.js — services)
|    Folder (services): 1034 files
|      File types: js(640) json(152) ics(76) html(50) snap(34) Dockerfile(25)
|                  DS_Store(10) md(6) eslintignore(6) gitignore(5)
|      Conf files: package.json(13) launch.json(1) settings.json(1)
|                  webpack.config.js(1)
|      Launch Configs: node(10);
```

</details>
Extensions: none

**Comment by svipas** [comment]
If you can provide as much info as possible. Repository where this issue occurs, how to reproduce it, etc. Because looking at `Process Info` shows that memory usage isn't even > 500 MB. Also, as I can see your project isn't small since it contains 1034 files, maybe try to exclude some directories with `searchExclude` and `watcherExclude`. Also, try to close VS Code and to remove TS cache which is here: `/Users/(your username)/Library/Caches/typescript`. If that doesn't help and issue still occurs I suggest to try Insiders build.

**Comment by Tyriar** [comment]
Also most of these reports are related to extensions such as typescript (electron_node tsserver.js and the one under it in your process info), I'm pretty sure I've seen it spike above 1gb at least when working on the VS Code codebase. Please report again if your process info is actually above 1gb and we can have a look, it's expected for large codebases for the typescript server (tsserver) to use quite a bit as it's indexing your project and getting ready to respond to things like rename/go to definition instantly.
