### ISSUE TITLE
Opening multiple files via Windows Explorer does not work as expected

### ISSUE THREAD

**Issue by codefox42** [Microsoft/vscode#71913]
Issue Type: <b>Usability</b>

Steps to reproduce:

1. Select two files in Windows Explorer

2. From the context menu choose *Open with Code (Insiders)*

Expected behavior:

* One VS Code instance with the two selected files loaded

Current behavior:

* It seems that two instances of VS Code are launched, but only the first wins and opens one of the two files. The second instance shows an error message.

    ![image](https://user-images.githubusercontent.com/4426497/55705477-2a135580-59df-11e9-81a2-02793950a2a4.png)

VS Code version: Code - Insiders 1.34.0-insider (d234937aedcbc265d2272ba5861125293239f9c7, 2019-04-05T05:18:43.251Z)
OS version: Windows_NT x64 10.0.17134

**Comment by codefox42** [comment]
Update: It seems that VS Code supports the described scenario most of the times. At the moment the steps above show the expected behavior. I will have to investigate this further...

**Comment by bpasero** [comment]
OK

**Comment by codefox42** [comment]
Though trying hard to reproduce the error, it did not appear any more in the past days.
