### ISSUE TITLE
Format on Save for Go files results in cursor going to the end of file 

### ISSUE THREAD

**Issue by iashbringer** [Microsoft/vscode#71912]
版本: 1.33.0 (user setup)
提交: 0dd516dd412d42323fc3464531b1c715d51c4c1a
日期: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

This bug appeared last year：https://github.com/Microsoft/vscode/issues/47382.
And appeared again after updating to the last version.

**Comment by aleclarson** [comment]
This is also happening with `prettier-vscode` in VSCode v1.33.0 on macOS v10.14.3.
