### ISSUE TITLE
.LOG

### ISSUE THREAD

**Issue by tamerxu** [Microsoft/vscode#71915]
Issue Type: <b>Bug</b>

line 1：.LOG
line 2: [ press F5 ]

VS code display not changed,
but open with notepad, line 2 inserted time and date

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:49:40.955Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (6.58GB free)|
|Process Argv|C:\Users\a54288445\Desktop\123.TXT|
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
git-project-manager|fel|1.7.1
changeEncode|lan|0.0.8
vscode-language-pack-zh-hans|MS-|1.32.4
cpptools|ms-|0.22.1

</details>

**Comment by mjbvz** [comment]
I don't understand the problem. Please explain in more detail

/needMoreInfo

**Comment by tamerxu** [comment]
add content to file.txt with vs code:
.LOG
//press F5 here,nothing display,but something inserted,can be displayed with notepad.exe

the notepad.exe display:
.LOG

10:07 2019-04-09

I think it is a function of notepad.exe.but I think its strange in vs code
