### ISSUE TITLE
注释乱码

### ISSUE THREAD

**Issue by KentRainbow** [Microsoft/vscode#71920]
Issue Type: <b>Bug</b>

调整注释的内容无法解决中文正常编码的现象

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.87GB (7.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
GBKtoUTF8|buk|0.0.2
code-runner|for|0.9.8
run-in-terminal|kor|0.0.1
vscode-language-pack-zh-hans|MS-|1.32.4
cpptools|ms-|0.22.1

</details>

**Comment by mjbvz** [comment]
> Adjusting the contents of comments does not solve the phenomenon of normal Chinese encoding

I do not understand the problem. Please explain step-by-step what you are trying to do and what is going wrong

/needsMoreInfo

**Comment by Garfield550** [comment]
@KentRainbow 
Could you upload a screenshot?
What is the Encoding type of your file? UTF-8 or GBK or GB2312
