### ISSUE TITLE
F12 go to definition not working

### ISSUE THREAD

**Issue by arhtudormorar** [Microsoft/vscode#71924]
Issue Type: <b>Bug</b>

Go to definition not working.
Example:

1. Make a new project with create-react-app
npx create-react-app my-app

2. in App.js
const myDeclaration = 1;
const somewehereBelow = myDeclaration + 1;

3. Ctrl+Click on myDeclaration on line 2 does not go to line 1

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.71GB (5.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
flow-for-vscode|flo|1.1.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? I see you have the flow installed for example

**Comment by arhtudormorar** [comment]
Hi!
  yes. still not working with all extensions disabled. Ctrl+Click does not work.   Also navigating to something like 
import Component from './../../../folder/Component'; // <- F12 here
  does not work
   On Monday, 8 April 2019, 21:44:21 EEST, Matt Bierner <notifications@github.com> wrote: 
 
 
Does this reproduce in the latest VS Code insiders build with all extensions disabled? I see you have the flow installed for example

**Comment by mjbvz** [comment]
Do other javascript features such as intellisense still work in that file? And did you have a chance to test using the insiders build, VS Code 1.34?

**Comment by arhtudormorar** [comment]
I confirm VS Code Insiders 1.34 is working as expected. Thanks!
    On Wednesday, 10 April 2019, 00:54:44 EEST, Matt Bierner <notifications@github.com> wrote:  
 
 
Do other javascript features such as intellisense still work in that file? And did you have a chance to test using the insiders build, VS Code 1.34?
