### ISSUE TITLE
Search - Files to include - Set path on settings.json

### ISSUE THREAD

**Issue by Nowhk** [Microsoft/vscode#71938]
Would be nice to add the path(s) to be included in search dialog in the `settings.json`.

So, instead of write (for example) `../../` in the Search Dialog, I simply could add it on settings.json as `"files.include":`, or even better `"search.include".`

This way I can set custom included path per project/folder.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/20530
