### ISSUE TITLE
Extensions not instlling

### ISSUE THREAD

**Issue by scarint** [Microsoft/vscode#7193]
- VSCode Version: 1.1.1
- OS Version: Win 10 Pro 10.0.10586

Steps to Reproduce:
1. Launch VS Code
2. Install extension (C/C++, Csharp, Python) using 'ext install ...'

The extensions never get installed; the busy icon in the bottom left shimmers indefinitely.

I've uninstalled, re-installed, installed and ran as Administrator. I've deleted the .vscode\extensions directory.

My other Win 10 Pro computer, same network, runs VSCode fine and installs extensions fine. Same user, same domain, same build of Win10. Copying the contents of the extensions directory to the non-working system seems to work.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by scarint** [comment]
No proxy, both computers have the same network configuration, with the exception of different IP addresses; on is DHCP and the other is static, both have the same DNS information.

Nothing displays in the console.

No significant change in network traffic in/out of the computer.

**Comment by joaomoreno** [comment]
Running as an Administrator might've caused the issue. Can you try deleting the `.vscode\extensions` directory once again and running without Administrator privileges?

**Comment by scarint** [comment]
Nothing. Even uninstalled, deleted the folder out of Program Files (x86), and deleted the entire .vscode directory; re-installed as my user (which is a domain admin), and it's behaving exactly as before. Developer console is showing nothing. .vscode/extensions directory is empty.

The extensions icon continues shimmering indefinitely.

**Comment by joaomoreno** [comment]
This is strange. Until we figure it out here's a workaround: install the extensions on the other machine and copy them over to the broken one.

**Comment by scarint** [comment]
That's what I've done; it seems to work fine that way. I'm running sfc /scannow, then will run Dism /Online /Cleanup-Image /CheckHealth and Dism /Online /Cleanup-Image /RepairHealth if necessary. 

I've got an issue in VisualStudio 2015 Community with Windows 10 SDK, but I don't think it is related (though I've seen weirder conflicts).

For the sake of more information, the error I receive is when I open a .xaml file in Designer view: 

System.InvalidOperationException
The Windows Software Development Kit (SDK) required by the XAML Designer was not correctly installed. Consider repairing your installation of either Visual Studio or the Windows SDK.

I've repaired the installation, uninstalled and re-installed, uninstalled Win10SDK and deleted directory, installed the stand-alone SDK package...I'm begining to think there's a gremlin in my system somewhere that is effecting both programs (VS and Code).

**Comment by joaomoreno** [comment]
Not related, but worth a try. 👍

**Comment by scarint** [comment]
We've identified the following error concerning my VS 2015 install:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/d40b7ac1-8829-4933-9ba5-cff403f14f8c/vs-2015-unhandled-exception-in-design-view
"[4044:2CF8][2016-06-11T16:32:17]e000: Error 0x800b0003: Failed authenticode verification of payload: K:\packages\sqllocaldb_amd64\sqllocaldb.msi
[4044:2CF8][2016-06-11T16:32:17]e000: Error 0x800b0003: Failed to verify signature of payload: sqllocaldb_amd64
[4044:2CF8][2016-06-11T16:32:17]e310: Failed to verify payload: sqllocaldb_amd64 at path: K:\packages\sqllocaldb_amd64\sqllocaldb.msi, error: 0x800b0003, delete: No.

Error 0x800b0003: it appears to be a Windows Update error: http://answers.microsoft.com/en-us/protect/forum/mse-protect_start/failed-installation-error-code-0x800b0003/a17946b5-786f-4e7b-b865-b066a9967a95

No other error messages in the setup log, so maybe we would think about the windows itself."

Not sure if it's related or not.

**Comment by joaomoreno** [comment]
Visual Studio Code does not relate at all with Visual Studio 2015.

**Comment by scarint** [comment]
Right, I'm saying it might not be a problem with VS Code, it might be a problem with my system.

**Comment by scarint** [comment]
Did a format and re-install of Win10 from the feedback from the Visual Studio crowd and other searching on that error above. It appears to be an issue with my system, as everything is working fine now.

**Comment by joaomoreno** [comment]
Thanks for the info!
