### ISSUE TITLE
Git panel doesn't refresh automatically 

### ISSUE THREAD

**Issue by halws** [Microsoft/vscode#71930]
Issue Type: <b>Bug</b>

When there are some changes: file modifiing or new files 

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
prettier-vscode|esb|1.8.1
vscode-atom-sass-snippet|glu|0.0.3
vue-snippets|hol|0.1.11
sftp|lix|1.12.2
HTMLHint|mka|0.6.0
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.6
vetur|oct|0.18.1
laravel-blade|one|1.18.0
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.8
code-spell-checker|str|1.6.10
vscode-icons|vsc|8.5.0

(11 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Did you open the repository root as a folder in VS Code?

**Comment by halws** [comment]
> Did you open the repository root as a folder in VS Code?

Yes, i do;

There is a record how it act now:
![ww](https://user-images.githubusercontent.com/16323637/55784768-85ae1380-5ab1-11e9-8893-86707f49202c.gif)
But i should notice that before update everything was OK.

**Comment by joaomoreno** [comment]
Can you show me the full contents of `Git: Show Git Output`?

**Comment by halws** [comment]
Ok, there is no need anymore. 

I've found that there was a disabled option `git Autorefresh`;
I don't know why this disable it, but I turned it on, and now it's working. 

Thank for the reply)
