### ISSUE TITLE
hit breakpoint on start.

### ISSUE THREAD

**Issue by yantrab** [microsoft/vscode#71933]
Version: 1.33.0 (user setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1.hit f5 to debug
2.vscode pause on start for each child prosses

config:
```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeArgs": [
                "-r",
                "ts-node/register"
            ],
            "args": [
                "${workspaceFolder}/app.ts"
            ], 
            "autoAttachChildProcesses": true
        },
```
![image](https://user-images.githubusercontent.com/12247800/55723434-c8b8aa00-5a11-11e9-83dd-0c11e860e9c1.png)
 
![image](https://user-images.githubusercontent.com/12247800/55723578-159c8080-5a12-11e9-8e5f-fc765d18c502.png)

**Comment by connor4312** [comment]
This should be fixed in out [new debugger](https://github.com/microsoft/vscode-js-debug/). Let us know if you're still running into issues.
