### ISSUE TITLE
VS Code crashes if I press any arrow key in the commit message input field

### ISSUE THREAD

**Issue by timduck-js** [Microsoft/vscode#71932]
Issue Type: <b>Bug</b>

1. Switch to Source Control panel
2. Click to the commit message input field
3. Press the Left key on the keyboard

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (1.92GB free)|
|Process Argv|d:\Projects\VM\vm.code-workspace|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
What does the crash look like? Does it hang? Does the Window disappear? Can you record this?

**Comment by timduck-js** [comment]
The problem disappeared after the system rebooted. I can't exactly reproduce the message, but there was a message in the dialog box that said something like this: "The window crashed. The contents of the window will be restored after restarting the window." After closing the message, VS Code reopened with the current content. It seems to me that the problem appeared right after updating the VS Code to the new version and disappeared immediately after rebooting the system.

**Comment by joaomoreno** [comment]
Alright, let us know if it comes back.
