### ISSUE TITLE
Alias paths from tsconfig cannot be found

### ISSUE THREAD

**Issue by danwellman** [Microsoft/vscode#71946]
- VSCode Version: 1.34.0-insider | 1.33.0
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. Add a path alias to tsconfig
2. Import something from the aliased path

Does this issue occur when all extensions are disabled?: Yes

I've been working in the same Angular project for about a year, with many aliased paths in the tsconfig. When I updated to the latest OSX (*not* VSCode itself), suddenly this issue started to occur.

Since the issue began I have tried disabling all extensions in VSCode (I had only 1 extension - editorconfig), and I have tried using the latest insider build. These things have not helped.

I have tried restarting the Mac, and VSCode, and these have not helped.

This is hugely frustrating because the app itself works - if there was some real issue with aliases, or some other config issue, I would expect the app to no longer build (especially with `--prod`). But the app itself is fine, just VSCode has an issue. Now I cannot right-click and "peek" or "go to" an aliased import, which is super annoying.

**Comment by mjbvz** [comment]
Check that the file is part of the correct tsconfig project by opening it and running the `TypeScript: go to project configuration` command from VS Code

Also, please share some example code or description of your project structure

**Comment by danwellman** [comment]
> running the TypeScript: go to project configuration command from VS Code

How? What are the steps to do that?

**Comment by mjbvz** [comment]
In VS Code, open the command palette and run the `TypeScript: go to project configuration` command

**Comment by danwellman** [comment]
It says "no commands matching". There are no TypeScript* commands listed

**Comment by mjbvz** [comment]
Make sure you are in a javascript or typescript file when running the command

**Comment by danwellman** [comment]
Ah-ha, it gave error that file was not part of a TS project, so I checked `includes` part of tsconfig and found the path wasn't including all files...

Weird that compilation/builds still worked, and that problem only became apparent after updating MacOS. Thanks for your help
