### ISSUE TITLE
Settings UI does not support "undefined" for missing values

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#71941]
If I set the type for a configuration settings to `"number"` when the settings UI populates it with a 0 by default (which is strange, given the API returns it as undefined):

![Screenshot 2019-04-08 at 11 05 50 am](https://user-images.githubusercontent.com/1078012/55730630-88a4f780-5a10-11e9-9545-f0b153982648.png)

However if I change the type to `["number", "undefined"]` then the UI no longer allows it to be set:

![Screenshot 2019-04-08 at 11 07 55 am](https://user-images.githubusercontent.com/1078012/55730667-9ce8f480-5a10-11e9-8ad5-58a60b1e5574.png)

I've checked the docs, but it's not entirely clear how this should work. Using `null` seems to work, but it seems a bit strange to use `null` for the case where the value is not defined in settings.

**Comment by roblourens** [comment]
> which is strange, given the API returns it as undefined

Not sure what you are seeing. I have an extension that contributes

```
"extension.testSetting": {
    "type": "number",
    "description": "test setting"
}
```

and I get the value like

`console.log(vscode.workspace.getConfiguration().get('extension.testSetting')`

and it prints `0`.

**Comment by DanTup** [comment]
Ugh, my testing of that was a bit flawed:

```
if (config.analyzerDiagnosticsPort)
```

Of course, 0 is falsey.

So, testing again - it seems like it does match up, and `["number", "null"]` defaults to `0` (which seems confusing, but if you swap them around it becomes `null`, so I guess it's using the first type for the default when it's not specified).

It still seems slightly strange that it doesn't support `undefined`, though I guess conveniently, that also distinguishes if you ask for a setting that doesn't exist.

**Comment by DanTup** [comment]
Actually, you can still get undefined:

```
"dart.sdkPath": {
	"type": "string",
	"scope": "window"
},
```

Reading this gives `undefined`. If it's valid to return `undefined` for a setting with no default if it's a `string`, why is it different for a `number`? It seems strange for one to implicitly allow undefined and the other not.

**Comment by roblourens** [comment]
That last comment is the only thing that feels wrong to me. It's probably too late to change it but I wonder if it's by design? 

@sandy081 do you know why a string setting with no default specified will be read as undefined, but a number setting with no default will give 0/

**Comment by sandy081** [comment]
Default value for string type should be empty string - https://github.com/Microsoft/vscode/blob/efa670f7b9965141fca80af1cdf73980900e75a7/src/vs/platform/configuration/common/configurationRegistry.ts#L420

**Comment by DanTup** [comment]
Hmmm, I can't repro this now - using the same `sdkPath` value, I'm seeing an empty string.

I must've done something wrong, so seems like this is working as expected - apologies! :)
