### ISSUE TITLE
Run silently from command line

### ISSUE THREAD

**Issue by jakewatkins** [Microsoft/vscode#71949]
I use Code (Insiders edition) from the commandline most of the time.  I'd like to be able to tell it to not send any output to the console so it doesnt mess up my console window.  Something like:
c:\>code --silent
would be perfect.
right now when I run code (again- insiders edition) I see this:
c:\>code somefile.txt
[main 2019-04-08T16:57:10.087Z] update#setState idle
[main 2019-04-08T16:57:40.088Z] update#setState checking for updates
[main 2019-04-08T16:57:40.148Z] update#setState idle
I don't want to see that

**Comment by bpasero** [comment]
@jakewatkins it will be silent if you do not execute code.exe directly but our command line script which you will get when you install Code through the installer with the choice to put it to path.
