### ISSUE TITLE
Make Extensions Easier to Find

### ISSUE THREAD

**Issue by alivefromupstairs** [Microsoft/vscode#71955]
![image](https://user-images.githubusercontent.com/46059092/55751066-b2741380-5a3c-11e9-8a14-16d24df10eb7.png)

It's hard to find extensions. If you can name extension folders starting with the actual name that would save a lot of time. Or better yet, add a link in the extension page if installed.

![image](https://user-images.githubusercontent.com/46059092/55750901-47c2d800-5a3c-11e9-8f83-ec88207fa464.png)

**Comment by sandy081** [comment]
But why do you want to go into the extensions folder, it is an implementation detail.

**Comment by alivefromupstairs** [comment]
@sandy081 to modify the code to my specific needs; fix issues or bugs, at least locally; experiment with theme colors; add "$0" to snippet extensions. Instead of building my own I just take a good one and build on it.
Just this morning, I had to remove this from an extension called colonize `vscode.commands.executeCommand('acceptSelectedSuggestion').then(() => {ext code}`
 it was triggering intellisense when I didn't want it to.

**Comment by sandy081** [comment]
@alivefromupstairs I see. But I think what you are trying to do might be risky but it is up to you. 

Anyway we do not have plans to implement such a requirement for this purpose. Sorry for that. Hence closing it as out of scope.
