### ISSUE TITLE
Folder type seems to accept URIComponent which may not have `fsPath`

### ISSUE THREAD

**Issue by veeramarni** [Microsoft/vscode#71958]
Was it a mistake to use `fsPath` (instead of `path`) which possibly not needed to define in the input as a UriComponents type and `URI.revive` is done at the post step. 

https://github.com/Microsoft/vscode/blob/ef74aa9628746e6a4fd85f1183a10c73383b8fc1/src/vs/workbench/services/search/node/searchService.ts#L468

**Comment by roblourens** [comment]
I don't really understand your issue, what problem are you seeing? I think this code is correct.

**Comment by veeramarni** [comment]
As per my understanding, [folderQueries](https://github.com/Microsoft/vscode/blob/ef74aa9628746e6a4fd85f1183a10c73383b8fc1/src/vs/workbench/services/search/common/search.ts#L70) can be just `URIComponents` without`fsPath`, right?

For example, if I pass `folderQueries` from parsing a JSON object shown below, then this [Line 468](https://github.com/Microsoft/vscode/blob/ef74aa9628746e6a4fd85f1183a10c73383b8fc1/src/vs/workbench/services/search/node/searchService.ts#L468) wouldn't able to run since `fsPath` doesn't exist (and neither it would be an instance of URI to have `fsPath`).
```
{
scheme: 'file',
path: '/tmp'
}
```

The jsonObject will be converted to URI instance later for example here https://github.com/Microsoft/vscode/blob/ef74aa9628746e6a4fd85f1183a10c73383b8fc1/src/vs/workbench/services/search/node/rawSearchService.ts#L38

So, would this [Line 468](https://github.com/Microsoft/vscode/blob/ef74aa9628746e6a4fd85f1183a10c73383b8fc1/src/vs/workbench/services/search/node/searchService.ts#L468) need to corrected as `pfs.exists(q.folder.path)` instead?

**Comment by roblourens** [comment]
The code is correct. `q` is a `IFolderQuery<uri>` so `q.folder` will be a URI.
