### ISSUE TITLE
Call stack tree should show label in narrow space

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71959]
Version: 1.34.0-insider
Commit: efa47d77cfd55cbad68bef54a2d765b73d7beb13
Date: 2019-04-03T20:23:50.493Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Good:

![image](https://user-images.githubusercontent.com/4033249/55757194-3eb81380-5a08-11e9-8026-0ea1ad08f1d5.png)

Bad:

![image](https://user-images.githubusercontent.com/4033249/55757215-4972a880-5a08-11e9-8d0d-8943d47da238.png)

I'd expect "Running" to be shown all times.

**Comment by isidorn** [comment]
This is fixed in latest insiders
Dup of https://github.com/Microsoft/vscode/issues/68276

![Screenshot 2019-04-09 at 10 50 51](https://user-images.githubusercontent.com/1926584/55786873-5e594580-5ab5-11e9-8b60-8d0bb507b3d8.png)
