### ISSUE TITLE
Displaying extra dark area in most themes

### ISSUE THREAD

**Issue by YusifKhalilov** [Microsoft/vscode#71950]
In themes appeared dark area. I tried in the VSCode insider too. I changed the theme without installing any extension. I got same displaying issue In the Solarized Dark theme. Dark area going deeper if the code is shorter. It seems dark area follows the code length.

- VSCode Version: 1.33.0
- OS Version: 10.14.4

Steps to Reproduce:

1. Download any theme
2. Change into the new theme

Does this issue occur when all extensions are disabled?: Yes

<img width="1440" alt="Screen Shot 2019-04-08 at 11 01 29 AM" src="https://user-images.githubusercontent.com/16528284/55746149-dbb98300-59ed-11e9-9e80-30416c08a081.png">

<img width="1440" alt="Screen Shot 2019-04-08 at 10 32 42 AM" src="https://user-images.githubusercontent.com/16528284/55745129-5fbe3b80-59eb-11e9-8817-01c57981a933.png">

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by YusifKhalilov** [comment]
> We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
> * Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

Thank you for your reply. I checked the exploration macOS version. It looks ok. 👍
