### ISSUE TITLE
Seems I can't delete contents fully of a file

### ISSUE THREAD

**Issue by jonolo6** [microsoft/vscode#71957]
Issue Type: <b>Bug</b>

I do 'select all' (cmd-a) and then delete it has an empty file. If I then save (cmd-s) the file reverts back its content.

Same if I delete file by file and save between. The final line deletion always reverts back when saving so I end up with one line in the file.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.18.2
gitignore|cod|0.6.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.6.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
vscode-open-in-node-modules|fab|1.1.1
vscode-jest-runner|fir|0.3.4
auto-rename-tag|for|0.0.15
todo-tree|Gru|0.0.126
docthis|joe|0.7.1
sublime-babel-vscode|jos|0.2.10
intellij-idea-keybindings|k--|0.2.31
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
node-debug2|ms-|1.33.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
linesinfostatusbar|pet|0.0.3
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
qub-xml|qub|1.2.1
typescript-hero|rbb|3.0.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.8
move-ts|str|1.11.3
jest-typescript-toolbox|sve|1.3.2
ayu|tea|0.18.0
vscode-icons|vsc|8.5.0
vscode-react-native|vsm|0.9.1
babelrc|wad|1.0.0
ReactSnippets|xab|2.3.0
markdown-all-in-one|yzh|2.2.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by alexandrudima** [comment]
@jonolo6 Are you using the setting `"files.insertFinalNewline"` ?

**Comment by jonolo6** [comment]
Yes I believe so @alexandrudima - when searching for files.insertFinalNewline in settings I get 'Files: Insert Final Newline' ticked.

**Comment by alexandrudima** [comment]
I can no longer reproduce in the meantime. With the latest VS Code Insiders, I can delete all content inside a file and when I save it, it gets saved with an empty content.

**Comment by jonolo6** [comment]
Sorry for the late reply. Fine to close this. I believe it actually was a plugin issue. 

FyI. My issue was I had a file with contents that I wanted removing completely via ctrl-a and delete. And then when command s (saving), the file would revert back it's full contents. It should save an empty file and possibly adhere  to newline setting (the latter I'm less sure about).
