### ISSUE TITLE
Feature Request: add option to disable suggestions in comments

### ISSUE THREAD

**Issue by bradcavanagh** [Microsoft/vscode#7195]
- VSCode Version: 1.1.1 commit def9e3
- OS Version: Windows 10

I would like to suggest an option to be able to disable suggestions from showing up while typing in a comment. I find it distracting and very seldom useful. Perhaps an "editor.quickSuggestionsInComments" setting?

**Comment by jrieken** [comment]
there is a way to disable word based suggestions
