### ISSUE TITLE
Improve ordering of "Go to symbol in workspace" results

### ISSUE THREAD

**Issue by olafurpg** [microsoft/vscode#71951]
Currently, `workspace/symbol` results are sometimes sorted in alphabetical order making it difficult to navigate to certain symbols

<img width="456" alt="Screenshot 2019-04-08 at 20 03 16" src="https://user-images.githubusercontent.com/1408093/55746870-2ca39880-5a3b-11e9-83ab-aeb70b60cc9f.png">

I expected "CompletionSuite", which is at the bottom in the screenshot, to appear at the top because

- it's the shortest result
- it has a shared prefix "Compl" with the query "ComplSuite"

In this particular case, the language server (Metals, https://marketplace.visualstudio.com/itemdetails?itemName=scalameta.metals) returns "CompletionSuite" at the top of the results.

It would be nice if Visual Studio Code could either

- improve the default ordering of items, or
- introduce some option like `"editor.workspaceSymbolOrdering": "default" | "language-server"` to preserve the ordering from the language server

**Comment by olafurpg** [comment]
Another example where the default ordering could be improved

<img width="446" alt="Screenshot 2019-04-25 at 08 43 34" src="https://user-images.githubusercontent.com/1408093/56714845-51378a00-6736-11e9-8bc5-0a861d2c6c4f.png">

I expected `WorkspaceSymbolProvider` to appear above `TestingWorkspaceSymbolProvider`. Also, I expected the uppercase `S` and `P` to be highlighted instead of lowercase `sp`.

**Comment by jrieken** [comment]
This actually already happened

<img width="553" alt="Screenshot 2019-10-23 at 10 46 25" src="https://user-images.githubusercontent.com/1794099/67375062-5e68f080-f582-11e9-91a2-08c7a0165ed0.png">

**Comment by olafurpg** [comment]
A recent release of VS Code seems to have regressed in the ordering of workspace/symbol results

<img width="590" alt="Screenshot 2019-12-05 at 11 00 15" src="https://user-images.githubusercontent.com/1408093/70229637-82f1e400-174e-11ea-865f-9c6c21b9f081.png">

I expected the `Add ; to search library dependencies` to appear at the bottom of the list, which is how the ordering used to be in a previous release. The language server returned the following results

```
[Trace - 11:00:11 AM] Sending response 'workspace/symbol - (14004)'. Processing request took 2ms
Result: [
  {
    "name": "MetalsLanguageServer",
    "kind": 5,
    "location": {
      "uri": "file:///Users/lgeirsson/dev/metals/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala",
      "range": {
        "start": {
          "line": 53,
          "character": 6
        },
        "end": {
          "line": 53,
          "character": 26
        }
      }
    },
    "containerName": "scala.meta.internal.metals."
  },
  {
    "name": "Add \u0027;\u0027 to search library dependencies",
    "kind": 24,
    "location": {
      "uri": "file:///Users/lgeirsson/dev/metals/.metals/workspace-symbol.md",
      "range": {
        "start": {
          "line": 0,
          "character": 0
        },
        "end": {
          "line": 0,
          "character": 0
        }
      }
    }
  }
]
```
Could it be that the `uri` is used for sorting in this situation? I would expect that it weighs more that the "LangSer" matches more closely "MetalsLanguageServer".


PS. I admit the `Add ; to search library dependencies` result is a hack 😅 It's a workaround to try and support a similar feature in IntelliJ. 

![2019-12-05 11 06 27](https://user-images.githubusercontent.com/1408093/70230086-7f129180-174f-11ea-9952-d3f98f6916c1.gif)
