### ISSUE TITLE
Simple file picker glitch on /

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#71962]
![image](https://user-images.githubusercontent.com/323878/55760732-d0784e80-5a11-11e9-9b2d-8163236fe8af.png)

This is on a Mac, somehow `/.HFS+ Private Directory Data?` has a newline in its name?

![image](https://user-images.githubusercontent.com/323878/55760767-eb4ac300-5a11-11e9-9de4-11ec07c652e4.png)

**Comment by alexr00** [comment]
Does Mac allow you to put newline characters in the name? I'm trying to understand if somehow I'm adding a newline character or if the filename has one. I can't figure out a way to make this same issue happen.

**Comment by alexr00** [comment]
Alright. It's possible and I can make it happen: https://unix.stackexchange.com/questions/212688/add-a-newline-into-a-filename-with-mv

**Comment by alexr00** [comment]
This is actually very tricky to solve. We normalize the slashes, so we'd have to specifically ignore \n. The input box doesn't provide a way to show new lines. The quick pick doesn't have a good way to do this either.

The best option here is to hide items with a new line character.

**Comment by roblourens** [comment]
I think you could just strip newline characters from the file names when displaying them, and just say that you can't type a newline into the input box to search for it.

**Comment by alexr00** [comment]
I'm implemented this, and it adds a lot of additional computation every time the value in the input box is changed. If it's too slow I'll remove it.
