### ISSUE TITLE
File Type column in the File Explorer on Windows shows "Visual Studio Code" rather than the actual file type

### ISSUE THREAD

**Issue by CGreenburg** [Microsoft/vscode#7196]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Try to open a file (any extension: xml, html, js, cpp, etc.). Windows prompts for default way to open the file. Choose Visual Studio Code
2. The file explorer now shows the file type being Visual Studio Code in the Type column.

The problem with this is that it's impossible to know what file is what since the extension of the file is hidden. The only way to know is to open the file or run ls in the terminal.

![unknown_file_types](https://cloud.githubusercontent.com/assets/13036301/15787035/7b491ca6-2985-11e6-9827-f6be40b7f79f.PNG)

![vscode_file_list](https://cloud.githubusercontent.com/assets/13036301/15787043/8f1adf80-2985-11e6-9819-a90f4c9c135f.PNG)

When registering the files to use Sublime Text by default, the file types are shown in the Types column in the file explorer as shown in the following picture.

![sublime_file_types](https://cloud.githubusercontent.com/assets/13036301/15787100/fc1bdecc-2985-11e6-86a6-86d0c3454540.PNG)

**Comment by joaomoreno** [comment]
This is terrible! And I finally got what the fuss was all about, thanks @CGreenburg!

**Comment by joaomoreno** [comment]
#3419
