### ISSUE TITLE
Ability to disable or configure Git change peek button next to line number

### ISSUE THREAD

**Issue by zero41120** [microsoft/vscode#71967]
## Current Behavior
It is related to [this issue](https://github.com/Microsoft/vscode/issues/36642).

Although it is no longer **_overlapping_**, 
but it is really difficult to click especially it animates to a wider size. 
![image](https://i.stack.imgur.com/yNg0R.png)

The red indicates the area where the fold button is responsive:
![image](https://user-images.githubusercontent.com/10471270/55762229-1257c380-5a17-11e9-89ac-f40096a38f97.png)
![image](https://user-images.githubusercontent.com/10471270/55762329-6367b780-5a17-11e9-948d-a1c4d2104f63.png)

## Problem:

1. As an end-user perspective who uses code folding frequently, I should be able to click near by the fold button to fold code consistently. 
2. I do not want to accidentally click on other function. (Especially the peek because it messes with the layout expectation and creates frustration).
3. When the git changes bar appears, I'm unable to click the fold consistently.
    - About 33% of the fold button's original responsive area is taken by git changes bar
    - The animation naturally makes a user clicks on it since it responds to location point on fold button.
    - User may never use git change peek. I personally will open Working-tree instead of peek when I need to examine the git changes. 
4. There is no way to configure the git changes bar nor fold button. The only way to turn off git changes bar is to disable git. 
![image](https://i.stack.imgur.com/cfHH3.png)

## Feature request
1. User should be able to turn on and off of the git changes bar
2. User should be able to disable the git changes bar's animation
3. The interface should have a consistent margin between fold button and git changes bar when the bar animates
4. User should be able to relocation change bar to other place, such as the break point area indicated in red:
![image](https://user-images.githubusercontent.com/10471270/55763141-a1b2a600-5a1a-11e9-8aac-a06480dabc9b.png)
5. User should be able change action on click line number, currently, click on it selects the line.
    - I personally like to do triple click on the line to select line, it is easier and intuitive, enable user action on line number click can make user work more effectively.

**Comment by joaomoreno** [comment]
This is now better thanks to the new `scm.diffDecorationsGutterAction` setting. No more action is planned.
