### ISSUE TITLE
Extra newlines in Debug Console

### ISSUE THREAD

**Issue by akrymskiy** [Microsoft/vscode#71964]
Issue Type: <b>Bug</b>

After updating to 1.33, output from my Python scripts (individual print() calls) gets an extra newline when output to Debug Console, running in Terminal and externally produces expected results
![console_problem](https://user-images.githubusercontent.com/9452607/55761061-117d5c80-5a2c-11e9-8b0b-a0427c40e5fe.png)
![terminal_ok](https://user-images.githubusercontent.com/9452607/55761073-18a46a80-5a2c-11e9-9d91-b4951a67028d.png)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.0
python|ms-|2019.3.6352
notepadplusplus-keybindings|ms-|1.0.2
powershell|ms-|1.12.0
material-icon-theme|PKi|3.7.0
java|red|0.42.1
ayu|tea|0.18.0
vscode-asl-validator|Tre|0.1.5
vscode-icons|vsc|8.5.0

</details>

**Comment by isidorn** [comment]
I can not reproduce with latest vscode insiders and javascript with the following sample

```javascript
console.log('1\n');
console.log('2');
console.log('3\n4');
console.log('5');
```

However I cn reproduce with pyhton. The issue here is that the python extension sends extra newline output events. Due to that I have created this issue https://github.com/Microsoft/vscode-python/issues/5173
