### ISSUE TITLE
Terminal prompt does not show on first load

### ISSUE THREAD

**Issue by AldrinSalazar** [Microsoft/vscode#71975]
Issue Type: <b>Bug</b>

- Open a new VSCode window
- Open a new terminal window
- The terminal prompt does not show at first load of the terminal section

Expected:

- The terminal prompt should show

Example:
![GIF](https://user-images.githubusercontent.com/12591112/55771266-51a50500-5a55-11e9-8e7e-ba268cdcb2c4.gif)

Im using the default windows command line, cmd.exe

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.0
elm|sbr|0.25.0

</details>

**Comment by davemvp** [comment]
I been seeing the same issue on Windows 10 1809. On a Windows 10 1803 machine the same version of VS Code works just fine.

**Comment by wyckster** [comment]
As per https://github.com/Microsoft/vscode/issues/57803, you're on Windows 10 [version 1809](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1809_(October_2018_Update)) and I believe you'll need to update to Windows 10 [version 1903](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)) to get the fix for this.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
