### ISSUE TITLE
After updated to 1.33.0, loading 'markdown.styles' setting is getting failed

### ISSUE THREAD

**Issue by rykoma** [Microsoft/vscode#71971]
Issue Type: <b>Bug</b>

1. Create workspace setting like below.

```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"markdown.styles": ["md-preview.css"]
	}
}
```

2. Create md-preview.css and save it to the same path as the workspace setting file.

3. Update to 1.33.0.

4. Show the preview of markdown file.

Expected behavior:
The preview of markdown file is styled with css file.

Actual behavior:
A toast will be displayed and it says "Could not load 'markdown.styles': md-preview.css".

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.24GB free)|
|Process Argv|C:\Users\rykoma\OneDrive - Microsoft\SR\SR.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.18.0

</details>

**Comment by mjbvz** [comment]
Duplicate of #71802

**Comment by sakronos** [comment]
> Duplicate of #71802

The bug still exists in version 1.33.1

**Comment by sahelsasani** [comment]
بانکداری یک نهاد بسیار منظم است هم از نظر سرمایه و هم از نظر بودجه و نقدینگی. در این مورد، مدیریت بانک باید بتواند ریسک ها و کارایی را کنترل کند تا عملکرد خود را بهبود بخشد. این مطالعه اثر ریسک و کارایی بر عملکرد بانکداری اسلامی را بررسی می کند. ریسک عبارت است از ریسک تامین اعتبار که توسط تامین اعتبار غیرقابل بازگشت (NPF) اندازه گیری می شود، ریسک سرمایه که توسط نسبت بسندگی سرمایه (CAR) و ریسک نقدینگی که توسط نسبت تامین اعتبار به سپرده (FDR) و پیش نیاز حداقل ذخیره اندازه گیری (RR) می شوند. کارایی نیز توسط نسبت هزینه های عملیاتی به درآمد عملیاتی (OEOI) اندازه گیری می شود. در حالی که عملکرد بانکداری اسلامی توسط بازده دارایی (ROA) و حاشیه سود خالص (NPM) اندازه گیری می شود. این مطالعه شامل 8 بانک اسلامی در اندونزی به همراه داده های فصلی است که با استفاده از تحلیل رگرسیون چندگانه پردازش می شود. نتایج نشان دهنده اثر معنی دار FDR، CAR، OEOI و اندازه عملکرد بانکداری اسلامی هستند برخلاف RR و NPF که اثر معنی داری بر عملکرد بانکداری اسلامی نداشتند.
