### ISSUE TITLE
Proposal: Ability to search only through specific directories

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#7197]
Just throwing the idea out there (it might already be something upcoming), but it'd be a great feature to be able to search only specific folders (like most editors / atom etc can).

Sometimes when looking for a specific file, let's say `index.ts`, it can look through so many directories. 

Let's say you know you're looking for something `import { Whatever }` and you know it's in `/modules/things` someplace, at the moment there is no way to achieve this, without looking through absolutely everything.

**Comment by bpasero** [comment]
@MarkPieszak you can right click on a folder in the explorer and pick to search in that folder. That will automatically fill in the advanced options under search.

**Comment by MarkPieszak** [comment]
Oh my god thank you, tried everything but that! Maybe a helpful hint could be put in the "Search" to let people know of that feature? Seems like it'd be something very common! Thank you Ben 👍
