### ISSUE TITLE
The new version caused the computer to freeze

### ISSUE THREAD

**Issue by xiaodoubaoldl** [Microsoft/vscode#71972]
- VSCode Version:1.33.0
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please add more imformation...

**Comment by ricsam** [comment]
related to https://github.com/Microsoft/vscode/issues/71886?

**Comment by xiaodoubaoldl** [comment]
change the code helper render type to dom  @aeschli solve the problem
