### ISSUE TITLE
Source control perform hard delete on un-tracked files

### ISSUE THREAD

**Issue by kedar9444** [Microsoft/vscode#71978]
- VSCode Version: 1.33.0
- OS Version: Windows_NT x64 10.0

Steps to Reproduce:

1. Try to add a new file in any project. [becaomes untracked file]
2. Delete the untracked file. 

Current behavior: 
The built-in plug-in performs hard delete operation.

Expectation: 
VS code should perform soft delete, and file should be present in recycle bin.

**Comment by joaomoreno** [comment]
> The built-in plug-in performs hard delete operation

The action is `Discard Changes`, it runs a git command to discard changes. There is a confirmation dialog coming up.

If you'd like a file to go to the trash, delete it from the file explorer.
