### ISSUE TITLE
Can't resize source control lower pane

### ISSUE THREAD

**Issue by anthonytietjen** [Microsoft/vscode#71976]
- VSCode Version: 1.33.0
- OS Version: MacOs Mojave

Steps to Reproduce:

1. Open a workspace with multiple folders that have github repos
2. In VS Code, click the Source Control icon on the left
3. Click one of the repos
4. In the pane at the bottom half, try to resize the pane's height
5. We used to be able to resize it, but we can not resize it anymore

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The SCM Repositories panel now automatically resizes itself, just like the Open Editors panel. If you'd like to manually resize it, set `scm.providers.visible` to `0`.

**Comment by anthonytietjen** [comment]
I know of 3 people (including myself) that this affected. I wonder how many devs across the world are pulling their hair out due to this change.

**Comment by nmajin** [comment]
> I know of 3 people (including myself) that this affected. I wonder how many devs across the world are pulling their hair out due to this change.

Make that 4
