### ISSUE TITLE
Formatter Settings UI shows strange default

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#71987]
- open settings UI, enter `Formatter` to the search test
- it appears that theres a default formatter

![image](https://user-images.githubusercontent.com/6461412/55790134-0a9e2a80-5abc-11e9-9481-133da8c4cfb7.png)

-> Should show 'None'

Setting a global formatter is rarely useful. Maybe the description should also say: `To define a formatter for a language, use the "[languageId]": { } syntax.`

**Comment by jrieken** [comment]
I can push a workaround, e.g have a special enum value that signals undefined (`enumDescriptions: ['None', ...], enums: [ undefined, ...]`) but given the default value is already declared as `undefined` it could also be the settings UI.

**Comment by jrieken** [comment]
Not sure that I can get to a pretty fix, when using `undefined/None` the drop down shows this...

<img width="455" alt="Screenshot 2019-04-09 at 12 17 02" src="https://user-images.githubusercontent.com/1794099/55792665-66b77d80-5ac1-11e9-9808-a7e08ed16e03.png">

**Comment by jrieken** [comment]
related/dupe issue https://github.com/Microsoft/vscode/issues/71941

**Comment by konradw86** [comment]
wt., 9 kwi 2019, 11:55 użytkownik Johannes Rieken <notifications@github.com>
napisał:

**Comment by jrieken** [comment]
Nothing because nothing is configured

**Comment by jrieken** [comment]
*Nothing should mean some nice UX saying 'no value' or alike

**Comment by roblourens** [comment]
The GUI tries to reflect the JSON whenever possible, so if you have a value set to undefined or null, it will show undefined or null.

This setting needs the type to be correct, as it is you get a warning in JSON if you set it to null. Then it also needs null/undefined listed as a value in the enum.

I assume this is what you did to get your screenshot, and that's what I would recommend, I can send a PR if you want or you can take what you have.

**Comment by weinand** [comment]
@jrieken this can be closed, right?

**Comment by jrieken** [comment]
yeah.

**Comment by reporter123** [comment]
This now shows a default of null
![image](https://user-images.githubusercontent.com/684470/56071746-da86ae00-5d7f-11e9-9e83-81c9d524ef8b.png)

**Comment by roblourens** [comment]
That's correct, that's the default value.
