### ISSUE TITLE
Unable to select first formatter in picker

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#71988]
- install [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- open a json document
- open the context menu, `Format Document With...` and pick the first entry in the list.
Nothing happens.

**Comment by jrieken** [comment]
🤦‍♂️ this is 0 being falsy...

**Comment by burtek** [comment]
JFR: setting first formatter as default and running "Format Document" works as a workaround.

**Comment by jrieken** [comment]
fix for next insiders and for 1.33.1

**Comment by konradw86** [comment]
wt., 9 kwi 2019, 17:57 użytkownik Johannes Rieken <notifications@github.com>
napisał:

**Comment by aeschli** [comment]
verified in Version: 1.34.0-insider
Commit: 7a07992127a6ff176f0ed073d0698d81d09fc4bb
