### ISSUE TITLE
URI.revive is not well typed

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#71992]
Today it is:

```
	static revive(data: UriComponents | any): URI {
        ...
    }
```

It should be something like:

```
    static revive(data: UriComponents): URI;
    static revive(data: UriComponents | undefined): URI | undefined;
    static revive(data: UriComponents | null): URI | null;
    static revive(data: UriComponents | null | undefined): URI | null | undefined;
    static revive(data: UriComponents | null | undefined): URI | null | undefined {
        ...
    }
```

cc @weinand

**Comment by weinand** [comment]
I was running into this issue when I changed some type from being a URL to URL[] and the "revive" would happily accept it...

**Comment by jrieken** [comment]
Fixed. 

@aeschli This is the only thing that now looks fishy: https://github.com/Microsoft/vscode/blob/261fa9f93910ec25a9836fcfe68d7f3cb4a6a06b/src/vs/workbench/electron-browser/window.ts#L529

**Comment by Tyriar** [comment]
Verified via review. @jrieken FYI you can avoid these casts:

https://github.com/microsoft/vscode/blob/8ef8aa6b3cb5b96870660fdd3bb8d0755e62fe51/src/vs/workbench/api/browser/mainThreadSearch.ts#L157-L168

Like this:

```ts
		dataOrUri.forEach(result => {
			if ('resource' in result) {
				searchOp.addMatch({
					resource: URI.revive(result.resource),
					results: result.results
				});
			} else {
				searchOp.addMatch({
					resource: URI.revive(result)
				});
			}
		});
```
