### ISSUE TITLE
Feature request: Option to not toggle open/close folder when clicking on folder name

### ISSUE THREAD

**Issue by batanun** [microsoft/vscode#71994]
This is a feature suggestion.

I often get a bit taken back with how Visual Studio Code behaves when I click on a folder name in the explorer, since it toggles between open/close. In my mind, that is what the small arrow icon to the left of the folder name is for (ie clicking on it to open/close the folder). When I click on the folder name I expect that folder to be selected (ie get the focus), but nothing else.

Would it maybe be possible to make this behavior configurable? If so, I would suggest the following configuration options:
1. Toggle open/close when clicking folder name [Current behavior] [Default]
2. Open closed folder when clicking folder name, but don't close an open folder
3. Don't toggle open/close when clicking folder name

P.S. I already know about issue 26400 being closed because this functionality is by design. But I'm asking for a simple configuration option for all us that prefer a different functionality.

**Comment by isidorn** [comment]
This would be a feature request against the tree, since all trees should behave consistently across the workbench.

fyi @joaomoreno

**Comment by joaomoreno** [comment]
Yeah we should have this configurable at the workbench level.

**Comment by sportshead** [comment]
If nobody's working on this, I'll try to implement this. You can find my progress here: https://github.com/sportshead/vscode/tree/issue-71994-file-tree-expansion

**Comment by joaomoreno** [comment]
Setting name is: `workbench.tree.expandOnFolderClick`.

**Comment by ArturoDent** [comment]
It doesn't appear this has been merged yet.  It isn't in the Insiders' Build as of

Version: 1.51.0-insider (user setup)
Commit: a5dfd9dcf83620a3b50dd56dc0117f83415c2ca8
Date: 2020-11-03T19:58:29.881Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20246
