### ISSUE TITLE
Tasks: Unhandled SASS 'error' event ends task

### ISSUE THREAD

**Issue by oncalldev** [Microsoft/vscode#7199]
- VSCode Version: 1.1.1
- OS Version: Windows 8.1
# Error Generated:

[15:11:26] Using gulpfile c:\Angular2\angular2-quickstart\gulpfile.js
[15:11:26] Starting 'sass'...
[15:11:26] Finished 'sass' after 14 ms
[15:11:26] Starting 'default'...
[15:11:26] Finished 'default' after 14 ms
[15:11:30] Starting 'sass'...
[15:11:30] Finished 'sass' after 4.66 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: bog.scss
Error: Invalid CSS after "h1": expected "{", was ""
        on line 1 of bog.scss

> > h1
> >    ^
> >     at options.error (c:\Angular2\angular2-quickstart\node_modules\node-sass\lib\index.js:271:32)

Watching build tasks has finished.
Steps to Reproduce:

Please note the tasks.txt file is really tasks.json and gulpfile.txt is gulpfile.js
[tasks.txt](https://github.com/Microsoft/vscode/files/298345/tasks.txt)
[gulpfile.txt](https://github.com/Microsoft/vscode/files/298347/gulpfile.txt)
1. Ctrl-Shift-B started task
2. Created empty file called bog.sass
3. Entered h1 - error immediately came up.  In fact the second I enter any text into an empty .sass file the error displays and the task terminates.

If this is any help, this used to work.  The other day I was running into an angular-cli problem so in the course of trying to figure that one out I upgraded my version of node from 4.2.4 to 4.4.5 and that indeed fixed THAT problem.  I may now have caused this problem.  Not sure.  I'm a bit confused about the version of node that Visual Studio code uses (5.10.0) and what I see when I run node-v on the command line which shows 4.4.5.

I'm in an experimental phase in CSS precompilers with VS Code so in the short term I've moved to LESS and that seems to work fine.

**Comment by dbaeumer** [comment]
Actual there is little VS Code can do about this. If gulp exits (e.g the node process) VS Code assumes that the task has finish. It doesn't do any inspection of why the process has exited.
