### ISSUE TITLE
Ctrl + F can't find some kind of text like "("

### ISSUE THREAD

**Issue by 785172550** [Microsoft/vscode#71991]
- VSCode Version:  1.25.1
- OS Version: window 7

Steps to Reproduce:

1.  If I use "Ctrl +F“ to find text "ENC(hAoghX4g52KUc==)" in a file which contains the text.
2.  It can not find the searching text.

After some test, I find that in "Ctrl +F" search I need to use "\\(" to make vscode match "(" char, but in "Ctrl + Shift +F" search is not needed. I'm confused about this non-consistent search function.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Gama11** [comment]
Sounds like you might have the "regex search" option active without noticing? `(` needs to be escaped there.

![](https://i.imgur.com/EebTvF6.png)

**Comment by 785172550** [comment]
great！thanks for your information.
