### ISSUE TITLE
Add pgrep support to debug launch configuration (for automatic attaching)

### ISSUE THREAD

**Issue by daravi** [Microsoft/vscode#72004]
As it currently stands, you either have to choose between all running processes or specify the process ID (not known before runtime). Therefore if you want to run a program and attach to it, you have to do so manually. 

A solution would be to add an option to pgrep the process-id from program name. For example it could look like the following:
```
{
"version": "0.2.0",
"configurations": [
	{
		"name": "debug (attach)",
		"type": "cppdbg",
		"request": "attach",
		"preLaunchTask": "build active file",
		"cwd": "${workspaceFolder}",
		"processId":"${command:pgrep}${fileBasenameNoExtension}",
		...
	},
	...
]
}
```

**Comment by daravi** [comment]
What extension?

**Comment by weinand** [comment]
The C++ extension. Here is the link: https://github.com/Microsoft/vscode-cpptools/issues
