### ISSUE TITLE
seems The vscode use about 10 times memory against sublime

### ISSUE THREAD

**Issue by qcq** [Microsoft/vscode#72007]
opened with the **same project** in VSCODE and SUBLIME TEXT3, I can see that vscode used more memory, may be it is not a issue. But I think that is a good improve point for vscode.
because it loved by so many people.

1. VSCODE version: 
![vscode_version](https://user-images.githubusercontent.com/8703631/55815537-1a9d2500-5b23-11e9-9b32-afddcdf0eac3.PNG)

2. sublime version:
![sublime_version](https://user-images.githubusercontent.com/8703631/55815566-25f05080-5b23-11e9-8568-8730744ae022.PNG)

3. with screenshot attached.
![Capture](https://user-images.githubusercontent.com/8703631/55815242-98146580-5b22-11e9-893c-fb7d7f70ce85.PNG)

4. system OS info also attached.
![windows](https://user-images.githubusercontent.com/8703631/55815244-98acfc00-5b22-11e9-885f-4d626d82eae5.PNG)

**Comment by bobber205** [comment]
VSCode is an electron project, Sublime isn't. That's the reason for the difference and I don't think VSCode will ever approach Sublime's memory usage territory.

**Comment by qcq** [comment]
firstly, I said that may be not a issue, but a point which can improve the vscode.
secondly, The reason I drop **Atom** away  is because **It takes too much disk space than sublime**.
the Atom also an electron project, but vs code can make it more smaller than Atom, why can not us make the memory usage less?
The most import things is-----if we know there exist one goal, why not to catch it and leave it behind us!

**Comment by tulevaisuus** [comment]
I think this is really a problem that needs to be improved. My computer runs memory 8G, and the vscode workspace has several folders. When opening a file page, vscode will take up 50% of my computer's memory. At the highest, it takes up 90% more memory

**Comment by aeschli** [comment]
When you run `code --status` while code is up you can see more where the memory is used. Mostly it is used by language servers e.g. for TypeScript , providing rich editing capabilities. You can decide to uninstall these extensions.

**Comment by qcq** [comment]
are you sure, I type the command, and get list below:

![resource](https://user-images.githubusercontent.com/8703631/55956807-6a9cf880-5c97-11e9-9b80-d58b6f147a66.PNG)


The 158M is my workspace of project
the 167M seems with the 88M item are seems microsoft plugins

which part is TypeScript?

**Comment by aeschli** [comment]
No TypeScript in your screenshot but the c++ language server and the JSON language server (that's based on the files you have opened since you opened the Window).

**Comment by qcq** [comment]
but the memory usage do high, compare to 40M of sublime total. 10 times, which is a big number.
