### ISSUE TITLE
Bug with replacing repetitive code inside of folding text

### ISSUE THREAD

**Issue by viztastic** [Microsoft/vscode#7200]
- VSCode Version: 1.1.1
- OS Version: Mac OS X El Capitan

Steps to Reproduce:

1. Fold code that contains repeating text (E.g. "repeating.text") inside of "[{a:_.function(repeating.text) { } }]
2. Now use the ctrl+shift+l shortcut to replace all instances of repeating.text
3. You will notice that the changes within a few of the folded regions are applied in a very strange way, often breaking the code.

(I searched for 'replace all inside of folded code' before posting this and couldn't find anything).

**Comment by aeschli** [comment]
`ctrl+shift+l` is mark occurrences. What is the action you execute?

**Comment by aeschli** [comment]
Closing as more information is needed to proceed.
