### ISSUE TITLE
Search and Replace replaces wrong line

### ISSUE THREAD

**Issue by jacobweber** [Microsoft/vscode#72009]
Issue Type: <b>Bug</b>

When I do a multi-file search and replace, sometimes it replaces text from the line above the match, rather than the match itself.

I'm not using regular expressions, match-case, or match-whole-word.

Happens without any custom extensions.

I have a reproducible case, but it involves code that I can't post publicly. Is there a secure place I can put it?

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
swagger-viewer|Arj|2.2.1
vscode-intelephense-client|bme|1.0.13
npm-intellisense|chr|1.3.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.6.0
vscode-npm-script|eg2|0.3.5
vscode-powertools|ego|0.39.0
php-debug|fel|1.13.0
vscode-pull-request-github|Git|0.6.0
vscode-favorites|how|1.4.0
svn-scm|joh|1.47.13
vscode-apache|mrm|1.2.0
python|ms-|2019.3.6558
debugger-for-chrome|msj|4.11.3
java|red|0.42.1
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.0
sync-rsync|vsc|0.34.7
jinja|who|0.0.8

</details>

**Comment by jacobweber** [comment]
It seems like this is caused by inconsistent line endings (CR/LF vs just CR) in the original file. It looks like VSCode attempts to fix the line endings, but in the process, the replace gets messed up.

If this is not considered a bug, you can close.

**Comment by roblourens** [comment]
If you have some line endings that are only CR, these are not really supported and can cause this issue. Is that what you mean? https://github.com/Microsoft/vscode/issues/48063

**Comment by jacobweber** [comment]
@roblourens Yeah. Here's a simple example:
```
mkdir foo
printf "one\r\ntwo\r\nthree\rfour\r\n" > foo/bar.txt
code foo
```
Then search and replace "four" with something else. It will end up changing the "three" line instead:

![image](https://user-images.githubusercontent.com/542988/55973511-963dc580-5c3a-11e9-9639-60e2f1433c1e.png)
