### ISSUE TITLE
Implementation of top level function is not shown in hover

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#72017]
Issue Type: <b>Bug</b>

* GitHub Pull Request extension repo https://github.com/Microsoft/vscode-pull-request-github/blob/master/src/view/reviewDocumentCommentProvider.ts#L128
* Hover on `workspaceLocalCommentsToCommentThreads`
* Press CMD key

![image](https://user-images.githubusercontent.com/876920/55827333-cbbda400-5abe-11e9-97be-45a840e08e05.png)

Ideally we should be able to implementation of `workspaceLocalCommentsToCommentThreads` at the top and definition at the bottom, but :(

VS Code version: Code - Insiders 1.34.0-insider (56f1b4795fed05677eb82a21dac4fc1ab62d747b, 2019-04-09T05:14:40.620Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_12430298|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.5.2
markdown-emoji|bie|0.0.7
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.0
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
flow-for-vscode|flo|1.1.1
vscode-pull-request-github-insiders|Git|1.98.0
ocaml|hac|0.6.43
beautify|Hoo|1.4.11
references-plusplus|jri|0.0.5
graphql-for-vscode|kum|1.13.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.12
vscode-azurefunctions|ms-|0.16.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
azure-account|ms-|0.8.1
cpptools|ms-|0.22.1
Go|ms-|0.9.2
powershell|ms-|1.12.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.18
debugger-for-chrome|msj|4.11.3
debugger-for-ios-web|msj|0.1.2
vetur|oct|0.18.1
subtitles-editor|pep|1.0.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
ruby|reb|0.22.3
smartpaste|reb|0.0.3
toggle|reb|0.0.1
vscode-fuzzsymbols|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.6.1
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.2
vscode-intelli-nav|vsi|0.0.6

(12 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
adding @jrieken since I believe the implementation peak when holding CMD is determined by VS Code

**Comment by jrieken** [comment]
Yeah, today we count matching bracket (up to a low maximum of lines) to compute the preview. @mjbvz not sure if TypeScript provides [`LocationLink#targetRange`](https://github.com/Microsoft/vscode/blob/8789ee62ba52f2619b782bf3397d88bfff610d60/src/vs/vscode.d.ts#L4186) but that would certainly help here

**Comment by mjbvz** [comment]
Ok, we do set the `targetRange` but it is just the range of the identifier (`workspaceLocalCommentsToCommentThreads`).

 I've opened https://github.com/Microsoft/TypeScript/issues/30849 to track having this information returned from TypeScript

**Comment by mjbvz** [comment]
Planning to do work to support API proposed by https://github.com/microsoft/TypeScript/pull/31587  in June. We would not actually ship this until TS 3.6 hover

**Comment by mjbvz** [comment]
To verify, please make sure you are using TS 3.6 in your workspace and follow @rebornix's original instructions in the github PR extension's codebase
