### ISSUE TITLE
Malfunctioning of some emojis.

### ISSUE THREAD

**Issue by BaseMax** [microsoft/vscode#72019]
**- VSCode Version:** 1.32.3
**- OS Version:** Linux Base 5.0.5-arch1-1-ARCH (Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux)

Steps to Reproduce:

1. Create a new file.
2. Copy the "⏰  
⏱".

> Emoticons are displayed well in Mozilla firefox.
![Screenshot from 2019-04-10 00-05-10](https://user-images.githubusercontent.com/2658040/55829847-e75b9580-5b24-11e9-868e-08f4ccd40766.png)

![Screenshot from 2019-04-09 23-59-24](https://user-images.githubusercontent.com/2658040/55829418-da8a7200-5b23-11e9-94f1-9c6ef572ab8e.png)
![Screenshot from 2019-04-10 00-01-12](https://user-images.githubusercontent.com/2658040/55829460-f2fa8c80-5b23-11e9-9cda-e7d32736d3b6.png)

**Comment by alexandrudima** [comment]
@BaseMax Do these emojis display correctly in Chromium?

**Comment by BaseMax** [comment]
Hey,

Sorry for my late reply.
We were busy with programming...

### Firefox
66.0.5 (64-bit)

![1](https://user-images.githubusercontent.com/2658040/58413950-40f53080-808f-11e9-989f-55efaebfa608.png)

### Chromium
Version 74.0.3729.157 (Official Build) Arch Linux (64-bit)

![2](https://user-images.githubusercontent.com/2658040/58413955-43578a80-808f-11e9-8dd6-8f02888962cc.png)
### Sublime Text
Version 3.1.1, Build 3176

![3](https://user-images.githubusercontent.com/2658040/58413963-4488b780-808f-11e9-8297-d2ac601b0077.png)

### VSCode (Code - OSS)
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-12T08:59:47.459Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 5.1.2-arch1-1-ARCH

![4](https://user-images.githubusercontent.com/2658040/58413965-46527b00-808f-11e9-9a91-4dba53b0c435.png)

Regards,
Max

**Comment by BaseMax** [comment]
Hey,

I have been submitting the problem (or bug) in the [chromium](https://bugs.chromium.org/) bug tracking system.

https://bugs.chromium.org/p/chromium/issues/detail_ezt?id=967357

Regards,
Max

**Comment by BaseMax** [comment]
> @BaseMax Do these emojis display correctly in Chromium?

Hey,

No,
I have been submitting the problem (or bug) in the chromium bug tracking system.

https://bugs.chromium.org/p/chromium/issues/detail_ezt?id=967357

Regards,
Max
