### ISSUE TITLE
Typescript features not working since latest update

### ISSUE THREAD

**Issue by jmeyers91** [Microsoft/vscode#72016]
- VSCode Version: 1.33.0 and 1.34.0-insider
- OS Version: OSX 10.14.3

Steps to Reproduce:

I'm not able to make a reproducible example. I tried by following these steps:

1. Copy affected project
2. Delete components, tests, pages, utils, types, etc. until the issue went away

Seemingly at random the typescript features started working while I was removing some JSX from a component. Then I hit CMD-Z a few times to undo the change, and the features continued to work.

Other things I've tried:

- Deleted typescript cache from `~/Library/Caches`
- Deleted VS Code and reinstalled
- Installed insider version (same issue)
- Update typescript (both globally and locally to `3.4.2`)

Here is my `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "es2018",
    "lib": [
      "es2018",
      "dom"
    ],
    "jsx": "react",
    "moduleResolution": "node",
    "allowJs": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noImplicitReturns": true,
    "outDir": "../dist/src",
    "typeRoots": [
      "./types",
      "../node_modules/@types"
    ]
  }
}
```

Does this issue occur when all extensions are disabled?: Yes

And here's a screenshot of what I see when I hover over a variable in a `.tsx` file:

![Screen Shot 2019-04-09 at 12 00 59 PM](https://user-images.githubusercontent.com/24255174/55827532-44bcfb80-5abf-11e9-9ba0-568302852ddd.png)

The code in that screenshot should be covered in red squiggles because there's a bunch of type errors in it, but nothing is being picked up by VS Code. The "loading..." tooltip never goes away regardless of how long I leave the cursor.

And the VS Code output tab for TS doesn't show any issues:

```
[Info  - 12:00:47 PM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 12:00:47 PM] Forking TSServer
[Info  - 12:00:47 PM] Started TSServer
```

**Comment by ricsam** [comment]
Probably related to https://github.com/Microsoft/vscode/issues/71886

**Comment by mjbvz** [comment]
A few questions to help us investigate :

1. Do you see this with all projects or just this one?
1. Have you installed any `@types` packages in your project? We've pushed a few fixes to the styled components typings but you could still be working with older versions of them
1. Does downgrading your workspace to use TypeScript 3.3 fix the issue?

/cc @RyanCavanaugh

**Comment by jmeyers91** [comment]
@mjbvz Updating `@types/styled-components` to `4.1.14` seems to have fixed the issue. I think @ricsam is right: this is related to #71886.
