### ISSUE TITLE
Application should get focus when right click is used

### ISSUE THREAD

**Issue by jsunsawyer** [Microsoft/vscode#72013]
- VSCode Version: 1.33.0
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. Have a browser and VSCode opened (side by side)
2. Focus your browser
3. Right click a folder in the VSCode file explorer
4. Click either Find in Folder or Rename
5. Begin typing (notice how nothing's happening)
6. Press tab and notice that your focus is the browser

**Comment by Multiply** [comment]
This also happens when right-clicking to create a file in a specific folder.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70966
