### ISSUE TITLE
larger HTML with mixed JS mode forces all after to be JS

### ISSUE THREAD

**Issue by tomByrer** [Microsoft/vscode#72010]
Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.  Open larger HTML file that includes `<script></script>` tags
2.  Use `Inspect TM selectors`
3.  Inspect HTML code after a `</script>`, & the reported (& visually highlighted) code is `JavaScript`, but should be HTML.

Does this issue occur when all extensions are disabled?: **Yes**

Thanks for all your hard work! :)

**Comment by aeschli** [comment]
Is this a dup of https://github.com/Microsoft/vscode/issues/70614

Please add the source sample..

**Comment by tomByrer** [comment]
Not sure if related.

Any `Save As...` YouTube HTML page will work it seems.   Can't test too much with these files, since VSCode lags out sometimes.  (Perhaps related or another bug?)

If you /really/ want me to attach / link a file, I can.

**Comment by aeschli** [comment]
Thanks for the tip, I can reproduce with the youtube html page.

Yes, the embedded JavaScript code isn't correctly understood by the grammar and prevents the rest 
of the page to be correctly highlighted: Dup of https://github.com/Microsoft/vscode/issues/20488
