### ISSUE TITLE
CTRL+W should not close vscode

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#72018]
It takes me completely by surprise every time I close a few windows with CTRL+W and then decide to just close them all by keeping it held down and then discovering that vscode closes as well.  This is just plain wrong - no app that I know of, other than browser, which are just a collection of tabs, does this.  

Yes, I know you can unbind it (but that's not actually obvious since it seems like it would be the same action that's happening, so I think most people would not look for this).

**Comment by jaqra** [comment]
You can do it by delete this shortcut
![cw](https://user-images.githubusercontent.com/48099350/55833173-d0ff0b00-5b1f-11e9-9889-e67dcb05b0a7.png)

**Comment by StephenWeatherford** [comment]
Yes, but read my comments.  This really should not be the default.
