### ISSUE TITLE
Auto import/Import doesn't work properly

### ISSUE THREAD

**Issue by vasilev-alex** [Microsoft/vscode#72023]
Issue Type: <b>Bug</b>

Auto import doesn't work for functions/classes/React components on accepting the suggestion or using quick fix (import suggestion doesn't appear in the quick fix popup)

However I noticed that if you open the file you want to import from  and go back to the file from which you're importing quick fix import suggestion and auto import start working as expected (only for the items exported from the visited file)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.38GB free)|
|Process Argv|-psn_0_12868677|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
vscode-html-css|ecm|0.2.0
clipboard-manager|Edg|1.1.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.0.15
macros|ged|1.2.1
rest-client|hum|0.21.2
smarty|imp|0.3.0
hungry-delete|jas|1.5.0
intellij-idea-keybindings|k--|0.2.31
vscode-mocha-sidebar|mat|0.20.24
mssql|ms-|1.5.0
azure-account|ms-|0.8.1
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
gitconfig|sid|2.0.0
vscode-icons|vsc|8.5.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Try creating a [jsconfig.json](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) file in your workspace. This tells VS Code to treat all js files in your workspace as part of the same project

**Comment by vasilev-alex** [comment]
Tried to add `jsconfig.json` with the following content to `./src` and to the root folder

```
{
  "compilerOptions": {
    "target": "ES6"
  },
  "exclude": ["node_modules", "**/node_modules/*"]
}
```

It doesn't change the before mentioned behavior

**Comment by mjbvz** [comment]
Please share more info about your project or example code
