### ISSUE TITLE
Terminal window can be resized through dropdowns

### ISSUE THREAD

**Issue by PassTheMayo** [Microsoft/vscode#72022]
Issue Type: <b>Bug</b>

![03-40-46 PM](https://user-images.githubusercontent.com/16949253/55833736-db001a00-5add-11e9-9c2a-821d493733f0.gif)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-html2pug|dba|0.1.0
eslint-disable-snippets|drK|1.2.0
gitlens|eam|9.6.0
vscode-npm-script|eg2|0.3.5
carbon-now-sh|eri|1.2.0
auto-rename-tag|for|0.0.15
discord-vscode|icr|3.3.11
dotenv|mik|1.0.1
vetur|oct|0.18.1
material-icon-theme|PKi|3.7.0
code-settings-sync|Sha|3.2.8
swdc-vscode|sof|0.14.3
sort-lines|Tyr|1.8.0
better-align|wwm|1.1.6
vscode-surround|yat|1.0.2

</details>

**Comment by isidorn** [comment]
@sbatten you are looking in the new workbench layout as far as I know.
If you would like me to look into this issue just assign it back. Thanks

**Comment by sbatten** [comment]
Looks like hovers use `z-index: 50`, suggests use `z-index: 40` and sashes use `z-index: 90`

@isidorn @joaomoreno @bpasero There don't seem to be any `z-index` values between 40 and 90 besides the participants listed above so I've moved sashes down to 35. Please review and revert if you feel this change is unsafe.

**Comment by isidorn** [comment]
If we break something people will complain in insiders. But great that you chekced the other z-index values.
