### ISSUE TITLE
cursorHomeSelect and cursorEndSelect are not properly working

### ISSUE THREAD

**Issue by oscarmlage** [microsoft/vscode#72028]
The `cursorHomeSelect` and `cursorEndSelect` shortcuts are not working. The default keybinding information:
```json
{
  "key": "shift+cmd+left",
  "command": "cursorHomeSelect",
  "when": "textInputFocus"
},
```
They works with `cmd+Home` and with `cmd+End` but they does not work with `shift+cmd+left` and `shift+cmd+right`.

- VSCode Version: `Versión 1.33.0 (1.33.0)`
- OS Version: `MacOS High Sierra 10.13.2`

Does this issue occur when all extensions are disabled?: Yes

I've noticed that this binding will work temporarily when first loading up VS Code, and this is the first binding I attempt. But once I do some other action, it stops working properly.

I've disabled all of the extensions, emptied out the `keybindings.json`, and the same behavior still persists.

I've no other keybindings with that shortcut, only that ones. Any hint?

**Comment by alexandrudima** [comment]
What does VS Code detect when you press the desired key combination? 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by oscarmlage** [comment]
Code is not able to detect the arrow hit, it detects `cmd` + `shift` but when I press the arrow (no matter if `right` or `left` one) it's not able to detect it, so in the end I guess the complete shortcut is not being triggered and that's why it's not working. But why is it not able to capture the arrow keys?

**Comment by alexandrudima** [comment]
@oscarmlage I don't really know. My best guess is that there is something on your machine that is eating up those key combinations. Perhaps you have defined a keybinding in the OS? Or perhaps you have other software that eats that key combination before it reaches us?

In any case, there is no possible code change I can do in VS Code if the keybinding does not reach us.
