### ISSUE TITLE
Evironment variables not expanding in tasks

### ISSUE THREAD

**Issue by 2012rcampion** [Microsoft/vscode#72029]
Environment variables (of the form `${env:name}`) are not expanding, or are expanding to the empty string, when occurring in `tasks.json`.  This was working as of about a week ago, but didn't work today.

- Version: 1.33.0 (user setup)
- Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
- Date: 2019-04-04T15:14:28.026Z
- OS: Windows_NT x64 10.0.17763

Also tested in the Insiders build:

- Version: 1.34.0-insider (user setup)
- Commit: 56f1b4795fed05677eb82a21dac4fc1ab62d747b
- Date: 2019-04-09T05:19:45.294Z

Steps to Reproduce:

1. Create a new empty folder; add `.\.vscode\tasks.json` with the following contents:
    ```
    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "echo path",
                "type": "shell",
                "command": "Write-Host ${env:PATH}",
            }
        ]
    }
    ```
2. Run this task (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, `Tasks: Run Task`, `echo path`); the output is:
    ```
    > Executing task: Write-Host  <
    
    Terminal will be reused by tasks, press any key to close it.
    ```
    i.e. the environment variable expands to the empty string.
3. Run the same command in the terminal (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>\`</kbd>, run `Write-Host ${env:PATH}`); the system path is printed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
I can repro, thank you for providing clear repro steps/examples.

**Comment by weinand** [comment]
On Windows the path env variable is "Path" and not "PATH", right?

**Comment by alexr00** [comment]
Neither Path or PATH work now in tasks. Both used to work.

**Comment by weinand** [comment]
Both "Path" or "PATH" work fine in a launch config on Windows:
```
{
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "args": ["-e", "console.log(process.argv[1]);", "${env:PATH}"]
        }
    ]
}
```

**Comment by alexr00** [comment]
Caused by https://github.com/Microsoft/vscode/commit/900d58bfe522e812acedf8720076590d853787b3

**Comment by the-nw1-group** [comment]
I'm also seeing this in user settings:
```
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.env.windows": {
        "TEST": "${env:PROCESSOR_REVISION}",
    },
}
```
open a terminal, and run:
```
$ env | grep -e TEST -e PROCESSOR_REVISION
TEST=
PROCESSOR_REVISION=3f02
```

**Comment by weinand** [comment]
@alexr00 please close if it's fixed.
