### ISSUE TITLE
search text in function

### ISSUE THREAD

**Issue by spolat** [Microsoft/vscode#72020]
Hi, I think it will be so nice if we can search a text in a specific function not whole file :) 
Sometimes I encounter very large files and when trying to search a variable (which is used by many places) I need to cut the function to another file then can search for variable. Is there anyone thinking like me :)

**Comment by roblourens** [comment]
You can click the button with the lines to enable "find in selection". Select your function then you can just search there. Hope that helps

![image](https://user-images.githubusercontent.com/323878/55972496-73121680-5c38-11e9-9065-4b1c93c721c5.png)
