### ISSUE TITLE
All double quotes removed from command in tasks.json in powershell

### ISSUE THREAD

**Issue by xisui-MSFT** [Microsoft/vscode#72039]
Issue Type: <b>Bug</b>

In tasks.json, write a command like 
```
"command": "C:\\Windows\\System32\\cmd.exe /k \"`\"C:\\Program Files (x86)\\Microsoft Azure Sphere SDK\\\\InitializeCommandPrompt.cmd`\" & azsphere dev sl deploy -p build/CMakeSample.imagepackage\""
```
The result would be
```
At line:1 char:113
+ ... 6)\Microsoft Azure Sphere SDK\\InitializeCommandPrompt.cmd` & azspher ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

Seems like all the double quotes are removed when running in powershell.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|32.00GB (18.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexr00** [comment]
@xisui-MSFT, can you provide an minimal/simple example that has the same issue?

**Comment by xisui-MSFT** [comment]
@alexr00 You can write line
```
"preLaunchTask": "deploy",
```
in launch.json, and in task.json, write something like:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "deploy",
            "type": "shell",
            "windows": {
                "command": "Copy-Item \"My test file.txt\" -Destination \"Another test file.txt\""
            }
        }
    ]
}
```
(No need for 'My test file.txt' to actually exist somewhere.)

Expected output:
```
Copy-Item : Cannot find path 'F:\Bugs\AZSphere\azure-sphere-samples\Samples\CMakeSample\My test file.txt' because it does not exist.
At line:1 char:1
+ Copy-Item "My test file.txt" -Destination "Another test file.txt"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F:\Bugs\AZSpher...y test file.txt:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

Actual output:
```
> Executing task: Copy-Item "My test file.txt" -Destination "Another test file.txt" <

Copy-Item : A positional parameter cannot be found that accepts argument 'test'.
At line:1 char:1
+ Copy-Item My test file.txt -Destination Another test file.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

As you can see, although it says the task executed is ' Copy-Item "My test file.txt" -Destination "Another test file.txt" ', the actual command executed doesn't contain double quotes.

**Comment by alexr00** [comment]
Thank you for the example!
This is what ends up getting run: 
`C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command Copy-Item "My test file.txt" -Destination "Another test file.txt"`

It looks like there is some additional escaping that needs to be done.

**Comment by alexr00** [comment]
Some places to start https://stackoverflow.com/questions/18454653/run-powershell-command-from-command-prompt-no-ps1-script
and https://stackoverflow.com/questions/18116186/escaping-quotes-and-double-quotes

**Comment by alexr00** [comment]
Everything is getting escaped as expected based on the input. Since we can't realistically detect that you're trying to run a commandlet, any other escaping will need to be done in the tasks.json.

**Comment by xisui-MSFT** [comment]
@alexr00 Thanks for the answer! I thought the task could just run it as a powershell or cmd command.
