### ISSUE TITLE
集成终端打开新的窗口

### ISSUE THREAD

**Issue by liushui123567** [Microsoft/vscode#72038]
Issue Type: Bug

工作区设置 
"settings": {
		"powershell.powerShellExePath": "C:/Program Files/PowerShell/6/pwsh.exe"

但是当我我打开新的pwsh，不是打开集成终端，而是一个新的窗口，关闭该窗口时，我收到以下消息：终端进程以退出代码终止：3221225786。

版本: 1.33.0 (user setup)
提交: 0dd516dd412d42323fc3464531b1c715d51c4c1a
日期: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

我能知道，这个原因肯定是因为，我升级windows1903的原因，但是我不能解决它

**Comment by Berrysoft** [comment]
Translation:
Issue Type: Bug

Workspace settings
"settings": {
"powershell.powerShellExePath": "C:/Program Files/PowerShell/6/pwsh.exe"

But when I start a new pwsh, it opens a new window instead of opening the integrated terminal. After closing the window, I receive the following message: The terminal process exits with code: 3221225786.

Version: 1.33.0 (user setup)
Commit: [`0dd516d`](https://github.com/Microsoft/vscode/commit/0dd516dd412d42323fc3464531b1c715d51c4c1a)
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

I'm sure it is due to my upgrade to Windows 1903, but I can't solve it.

**Comment by Berrysoft** [comment]
我这里是insider版本，Windows 1903，工作区设置：
My environment is Windows 1903 and insider edition of VS Code, the workspace settings is:
``` json
{
    "powershell.powerShellExePath": "C:/Program Files/PowerShell/6/pwsh.exe"
}
```
插件运行正常，无法复现。
The extension runs well, I can't repro the bug.

@liushui123567 工作区设置没有`"settings":`吧？

**Comment by liushui123567** [comment]
> 我这里是insider版本，Windows 1903，工作区设置：
> My environment is Windows 1903 and insider edition of VS Code, the workspace settings is:
> 
> ```json
> {
>     "powershell.powerShellExePath": "C:/Program Files/PowerShell/6/pwsh.exe"
> }
> ```
> 
> 插件运行正常，无法复现。
> The extension runs well, I can't repro the bug.
> 
> @liushui123567 工作区设置没有`"settings":`吧？

有的，windows1809就没有任何问题，windows1903就不行了

**Comment by Berrysoft** [comment]
> 有的，windows1809就没有任何问题，windows1903就不行了

那就删了这个试试吧，应该是没有的。另外这个描述很迷啊，PowerShell插件应该是默认启动终端的，不需要手动启动吧。你是怎么“打开新的pwsh”？

**Comment by aeschli** [comment]
How do you open a new powershell?

**Comment by liushui123567** [comment]
> How do you open a new powershell?

This description is not accurate. When vscode is opened, the inheritance terminal will not appear, but a window of PWSH will appear

"powershell.powerShellExePath": "C:/Program Files/PowerShell/6/pwsh.exe",

**Comment by KexyBiscuit** [comment]
Could you paste the full `settings.json` file?

**Comment by liushui123567** [comment]
> Could you paste the full `settings.json` file?

workspace.json
{
	"folders": [
		{
			"path": "D:\\VSCode"
		},
		{
			"path": "D:\\python"
		}
	],
	"settings": {
		"powershell.powerShellExePath": "C:/Program Files/PowerShell/6/pwsh.exe",
		"python.linting.pylintEnabled": false
	}	
}
settings.json
{
    "editor.wordWrap": "wordWrapColumn",
    "editor.mouseWheelZoom": true,
    "editor.wordWrapColumn": 180
}

**Comment by liushui123567** [comment]
当我卸载1.33.0 重新安装1.31后此问题消失

版本: 1.31.0 (user setup)
提交: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
日期: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
@TylerLeonhardt any idea what's happening here? Seen reports like this in the powershell ext?

Update to 1903 is mentioned as a cause and later downgrading to 1.31 fixes it? Could be pwsh under conpty?

**Comment by TylerLeonhardt** [comment]
It's possible... I've never seen this behavior before. The setting `powershell.powerShellExePath"` is for sure the PowerShell extension... but I'm curious if it's reproing in the regular integrated terminal and not the PowerShell extension's integrated console.

**Comment by KromaLee** [comment]
![image](https://user-images.githubusercontent.com/26086447/58720176-07605480-8404-11e9-8e9c-905ea860102f.png)

**Comment by xingjiapeng** [comment]
我也有这个问题啊……
i have this problem,too

setting.json
{
    "c-cpp-compile-run.cpp-compiler": "C:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\bin",
    "C_Cpp.updateChannel": "Insiders",
    "files.defaultLanguage": "cpp",
    "code-runner.defaultLanguage": "cpp",
    "editor.fontSize": 21,
    "code-runner.executorMap": {
        "javascript": "node",
        "php": "C:\\php\\php.exe",
        "python": "python",
        "perl": "perl",
        "ruby": "C:\\Ruby23-x64\\bin\\ruby.exe",
        "go": "go run",
        "html": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc \"$fileName\" -o \"$fileNameWithoutExt\" && \"$dir$fileNameWithoutExt\"",
        "cpp" : "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && \"d:\\编程\\VS Code\\$fileNameWithoutExt\"",
    },
    "code-runner.runInTerminal": true,
}

**Comment by xingjiapeng** [comment]
我也有这个问题啊……
i have this problem,too

setting.json
{
    "c-cpp-compile-run.cpp-compiler": "C:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\bin",
    "C_Cpp.updateChannel": "Insiders",
    "files.defaultLanguage": "cpp",
    "code-runner.defaultLanguage": "cpp",
    "editor.fontSize": 21,
    "code-runner.executorMap": {
        "javascript": "node",
        "php": "C:\\php\\php.exe",
        "python": "python",
        "perl": "perl",
        "ruby": "C:\\Ruby23-x64\\bin\\ruby.exe",
        "go": "go run",
        "html": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc \"$fileName\" -o \"$fileNameWithoutExt\" && \"$dir$fileNameWithoutExt\"",
        "cpp" : "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && \"d:\\编程\\VS Code\\$fileNameWithoutExt\"",
    },
    "code-runner.runInTerminal": true,
}

**Comment by xingjiapeng** [comment]
我也有这个问题啊……
i have this problem,too

setting.json
{
    "c-cpp-compile-run.cpp-compiler": "C:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\bin",
    "C_Cpp.updateChannel": "Insiders",
    "files.defaultLanguage": "cpp",
    "code-runner.defaultLanguage": "cpp",
    "editor.fontSize": 21,
    "code-runner.executorMap": {
        "javascript": "node",
        "php": "C:\\php\\php.exe",
        "python": "python",
        "perl": "perl",
        "ruby": "C:\\Ruby23-x64\\bin\\ruby.exe",
        "go": "go run",
        "html": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc \"$fileName\" -o \"$fileNameWithoutExt\" && \"$dir$fileNameWithoutExt\"",
        "cpp" : "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && \"d:\\编程\\VS Code\\$fileNameWithoutExt\"",
    },
    "code-runner.runInTerminal": true,
}

**Comment by xingjiapeng** [comment]
我也有这个问题啊……
i have this problem,too

setting.json
{
    "c-cpp-compile-run.cpp-compiler": "C:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\bin",
    "C_Cpp.updateChannel": "Insiders",
    "files.defaultLanguage": "cpp",
    "code-runner.defaultLanguage": "cpp",
    "editor.fontSize": 21,
    "code-runner.executorMap": {
        "javascript": "node",
        "php": "C:\\php\\php.exe",
        "python": "python",
        "perl": "perl",
        "ruby": "C:\\Ruby23-x64\\bin\\ruby.exe",
        "go": "go run",
        "html": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc \"$fileName\" -o \"$fileNameWithoutExt\" && \"$dir$fileNameWithoutExt\"",
        "cpp" : "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && \"d:\\编程\\VS Code\\$fileNameWithoutExt\"",
    },
    "code-runner.runInTerminal": true,
}

**Comment by xingjiapeng** [comment]
我的版本是1.36.1

**Comment by yukiChow** [comment]
same with me, and even if I change to use gitBash as external terminal, still pop up powershell window
