### ISSUE TITLE
Integrated terminal opens as new window

### ISSUE THREAD

**Issue by juandematei** [microsoft/vscode#72033]
Issue Type: <b>Bug</b>

My settings.json has this line `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`,

However, bash terminal opens as new window instead of integrated. When closing that window I get this message: **The terminal process terminated with exit code: 3221225786**.

Any idea?

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.61
beautify|Hoo|1.4.11
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
vscode-icons|vsc|8.5.0

</details>

**Comment by liushui123567** [comment]
I had this problem after I upgraded Windows 1903

**Comment by liushui123567** [comment]
终端进程已终止，退出代码: 3221225786,我使用的是pwsh,也出现同样的问题

**Comment by Tyriar** [comment]
When this happens it normally means you're launching a terminal rather than the shell, but that is indeed the path we recommend for git bash on https://code.visualstudio.com/docs/editor/integrated-terminal#_windows. I can't reproduce here.

Did you recently update git? Also how are you launching the terminal?

**Comment by juandematei** [comment]
Hi @Tyriar, I'm running Git-2.21.0-64-bit which is the latest version. I have exact same configuration on different PC with other Windows 10 version and I don't have this issue. I normally launch terminal using Ctrl + ' command.

**Comment by Tyriar** [comment]
Works fine for me on git 2.12.0.windows.1, upgraded to your version and it works there too 😕.

If you switch to powershell/cmd does it work? You can use the Select Default Shell command to switch the setting over.

**Comment by liushui123567** [comment]
> Issue Type: Bug
> 
> My settings.json has this line `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`,
> 
> However, bash terminal opens as new window instead of integrated. When closing that window I get this message: **The terminal process terminated with exit code: 3221225786**.
> 
> Any idea?
> 
> VS Code version: Code 1.33.0 ([0dd516d](https://github.com/Microsoft/vscode/commit/0dd516dd412d42323fc3464531b1c715d51c4c1a), 2019-04-04T15:14:28.026Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info
> Extensions (6)

I have downgraded to version 1.31. The problem has been solved. You can try it

版本: 1.31.0 (user setup)
提交: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
日期: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by juandematei** [comment]
I tried changing default terminal to cmd and powershell and I have same problem.
Also tried using Git 32bit instead of 64bit, with no luck as well.

**Downgrading to 1.31 solved the problem.**

**Comment by BasilaryGroup** [comment]
I also saw the same problem.

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I had uninstalled Node.js and reinstalled (version 10.15.3) before I noticed that the Code integrated terminal terminated with error code 2. I tested bash and Powershell with the same error code 2 terminations. Code integrated terminal was working before the Node.js uninstall/purge/install. I have no how a Node.js uninstall would affect Code. It was the only change I made to my development system today.

Both bash and Powershell worked as expected outside of VS Code.

I upgraded to git 2.21.0.windows.1 from git 2.18.0. Code continued with the integrated terminal termination problem.

**My successful work around!**
1. uninstall Code 1.33.1 (64 bit) 
2. reinstall Code 1.33.1 (64 bit)

Now the integrated terminal (bash and Powershell) work.
```
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
```
and
```
//"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
```

I was running an older version of VS Code (32 bit), sorry I don't remember the version, before I installed Code 1.33.1 (64 bit).

**Comment by averagejoe77** [comment]
I am on 1.34, installed yesterday and I have the same issue, oddly I did not have any issue with 1.33, am I also running Windows 10 Pro version 1903 build 18362.116 which just came out yesterday. 

I also just tried the 1.35.0 insiders build and got the same behavior.

**Comment by GollyJer** [comment]
Answer... for now. 😀
https://stackoverflow.com/questions/56154957/how-do-i-get-visual-studio-code-to-use-the-integrated-terminal
