### ISSUE TITLE
终端面板移到右侧,缩放致最小后,关闭面板,终止终端按钮不显示.

### ISSUE THREAD

**Issue by mopkq** [Microsoft/vscode#72034]
Issue Type: <b>Bug</b>

终端面板移到右侧,缩放致最小后,关闭面板,终止终端按钮不显示.

比较一下 , 这样是正常情况吗?
![image](https://user-images.githubusercontent.com/8299029/55844777-827a5c80-5b71-11e9-9e2e-1820c98bf4c7.png)

![image](https://user-images.githubusercontent.com/8299029/55844791-9920b380-5b71-11e9-9c16-b67d9da31877.png)

![image](https://user-images.githubusercontent.com/8299029/55844821-cb321580-5b71-11e9-93d6-f6c727bfee76.png)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.99GB free)|
|Process Argv|E:\TJPro\tsee|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-language-pack-zh-hans|MS-|1.33.2
vetur|oct|0.18.1
vscode-icons|vsc|8.5.0

</details>

**Comment by NateLing** [comment]
@mopkq 
我都看不懂你描述的重现步骤，你让别人如何理解你表达的意思呢？
I can't understand your issue description even i am  Chinese .  so how could other people understand this?

**Comment by mopkq** [comment]
> @mopkq
> 我都看不懂你描述的重现步骤，你让别人如何理解你表达的意思呢？
> I can't understand your issue description even i am Chinese . so how could other people understand this?
https://user-images.githubusercontent.com/8299029/55844777-827a5c80-5b71-11e9-9e2e-1820c98bf4c7.png

https://user-images.githubusercontent.com/8299029/55844791-9920b380-5b71-11e9-9c16-b67d9da31877.png

https://user-images.githubusercontent.com/8299029/55844821-cb321580-5b71-11e9-93d6-f6c727bfee76.png

这样是正常情况吗?
