### ISSUE TITLE
SCM: Clicking 'Open File' leaves Preview Tab in background

### ISSUE THREAD

**Issue by ProLoser** [Microsoft/vscode#72032]
# Background

1. Edit an SCM managed file
2. Go to Source Control panel
3. Select changed file in SCM panel (opens preview)
4. Press 'Open File' button in SCM panel (opens file in new tab)

# Result
Preview tab is left in the background (VSCode should never be able to have a preview tab in the background, it fundamentally defeats the purpose of the preview tab). A copy of the same file is opened in another tab. This leaves tab clutter.

# Expected
I am no longer concerned with the diff, I want to work on the file. The preview tab should disappear and the editor tab (which is active) should replace it.

See screenshot for illustration of the Preview Tab left in the background and adding clutter
![image](https://user-images.githubusercontent.com/67395/55842980-b0688e00-5aea-11e9-8768-24ae9b8fa750.png)

**Comment by joaomoreno** [comment]
> VSCode should never be able to have a preview tab in the background, it fundamentally defeats the purpose of the preview tab

This is incorrect. Instead, the constant is: there should always only be one preview tab at any point in time. That preview tab can easily be next to a pinned tab. Just try it in the explorer: double click file A in the explorer, click file B in the explorer, then click A's tab above the editor. Preview tab of B will still be up there.

The current behavior is correct, as it was reviewed by other users:

- Selecting a row in the SCM list is a preview action, as you're likely to select other rows.
- Clicking the "Open File" action on a row element is not a preview action, as it's an explicit action execution, so we pin that editor on purpose.
