### ISSUE TITLE
VScode integrated terminal dies if its in split mode

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#72035]
![image](https://user-images.githubusercontent.com/1018196/55843413-00485480-5aed-11e9-98f1-5dfc1a2a3190.png)

Happens almost every day after a couple of hours of use. There is no way to revive it back.

Funny thing is kill terminal kills both terminals. There is no way to create a new terminal anymore. All terminals are dead terminals without scrollbar. Weird.

I basically have to restart my vscode to get back to a good state.

```
MacOSX: Sierra
VSCode: 1.33.0
0dd516dd412d42323fc3464531b1c715d51c4c1a

2019-04-04T15:01:38.042Z
```

**Comment by Tyriar** [comment]
Hoping this is fixed in today's build. Please let me know if not 🙂 

/duplicate #69603
