### ISSUE TITLE
Vscode runs too high memory

### ISSUE THREAD

**Issue by tulevaisuus** [Microsoft/vscode#72040]
Issue Type: <b>Performance Issue</b>

When vscode starts, it will take up more than 80% of the running memory of the computer. After a while, it will recover about 40% of the memory. When you open a file in the workspace, it will take up 80% of the memory.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    58	 13144	code main
    0	   131	  7048	   window (blog-with-sidebar.html - 无标题 (工作区) - Visual Studio Code)
    0	    85	  3544	     extensionHost
    0	   366	  1280	       electron_node server.js 
    0	   359	  2468	       electron_node server.js 
    0	   387	  4236	       electron_node server.js 
    0	     6	  4756	       electron_node server.js 
    0	   261	  5684	       electron_node server.js 
    0	     8	  8820	       "C:\Users\15530\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\15530\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=3544
    0	     6	  9644	       electron_node server.js 
    0	     5	 10640	       "C:\Users\15530\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\15530\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=3544
    0	   309	 10896	       electron_node server.js 
    0	   335	 11076	       electron_node server.js 
    0	   406	 11992	       electron_node server.js 
    0	   429	 13448	       electron_node server.js 
    0	   365	 13940	       electron_node server.js 
    0	     4	 10912	     watcherService
    0	     8	 13076	     searchService
    1	    67	  8396	   window (问题报告程序)
    2	   124	 12516	   gpu-process
    0	    23	 14108	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (blog-with-sidebar.html - 无标题 (工作区) - Visual Studio Code)
|    Folder (fenye): 0 files
|      File types:
|      Conf files:
|    Folder (zhongjianjian): 24 files
|      File types: js(6) ejs(4) png(3) PNG(3) json(2) css(1) txt(1) jpg(1)
|                  pdf(1)
|      Conf files: package.json(1)
|    Folder (boostrap实战): 299 files
|      File types: jpg(182) png(74) js(14) css(12) html(6) eot(2) woff(2)
|                  ttf(2) woff2(2) ini(1)
|      Conf files:
|    Folder (模板网站): 132 files
|      File types: jpg(54) png(33) html(24) js(11) css(8) woff(1) woff2(1)
|      Conf files:
|    Folder (临时文件): 73 files
|      File types: js(19) mp4(16) vue(7) json(7) ts(6) png(4) jpg(2)
|                  gitignore(2) md(2) html(2)
|      Conf files: package.json(2) tsconfig.json(1) tslint.json(1)
|    Folder (个人网站项目): 153 files
|      File types: png(56) jpg(45) js(15) html(12) css(11) vue(6) json(2)
|                  pdf(1) editorconfig(1) gitignore(1)
|      Conf files: package.json(1)
|    Folder (portal): 39 files
|      File types: js(21) css(5) html(3) png(3) gif(3) eot(1) svg(1) ttf(1)
|                  woff(1)
|      Conf files:
|    Folder (优林科技): 122 files
|      File types: jpg(54) png(29) vue(15) js(14) css(2) json(2) gitignore(1)
|                  gitkeep(1) md(1) html(1)
|      Conf files: package.json(1)
|    Folder (项目实战): 765 files
|      File types: jpg(342) png(273) js(63) vue(30) css(14) html(10) json(9)
|                  map(4) babelrc(3) gitignore(3)
|      Conf files: package.json(4) settings.json(1)
|    Folder (道同): 1576 files
|      File types: php(1256) png(59) dat(40) md(39) json(30) txt(18) html(16)
|                  yml(10) gitignore(10) xml(8)
|      Conf files: makefile(2)
|    Folder (Files): 2378 files
|      File types: html(737) js(428) gif(419) png(418) css(115) java(36)
|                  ejs(29) jpg(22) swf(17) cs(16)
|      Conf files: package.json(2) sln(2)
|    Folder (WebSite): 3340 files
|      File types: png(687) html(501) gif(460) js(430) jpg(295) asp(191)
|                  css(136) json(108) mp4(64) wxss(41)
|      Conf files: package.json(21) tslint.json(4) settings.json(2)
|                  tsconfig.json(2) launch.json(1) sln(1);
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
EnglishChineseDictionary|Cod|0.0.11
bracket-pair-colorizer|Coe|1.0.61
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.2.1
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.8
vue-snippets|hol|0.1.11
node-module-intellisense|lei|1.5.0
sftp|lix|1.12.2
ftp-sync|luk|0.3.9
font-awesome-codes-html|med|0.0.7
Angular-BeastCode|Mik|8.0.1
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hans|MS-|1.33.2
debugger-for-chrome|msj|4.11.3
vetur|oct|0.18.1
vuehelper|oys|0.1.0
vscode-css-peek|pra|2.2.0
sass-indented|rob|1.5.1
element-ui-snippets|SS|0.3.5
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|8.5.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by soorajvnair** [comment]
I can also confirm this. Insiders build runs fine.

**Comment by aeschli** [comment]
The process view shows that `electron_node server.js ` has been called multiple times and taking all the time. This is from an installed extension.
Can you find out which extension this is? 
https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions has the instructions

**Comment by tulevaisuus** [comment]
> 进程视图显示`electron_node server.js `已多次调用并且一直在调用。这是来自已安装的扩展程序。
> 你能找到这个扩展名吗？
> https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions有说明

Thanks, I have found this extension and the current usage has returned to normal.
