### ISSUE TITLE
Copy Paste - Window Crash

### ISSUE THREAD

**Issue by man18786** [Microsoft/vscode#72043]
Issue Type: <b>Bug</b>

![Annotation 2019-04-10 111322](https://user-images.githubusercontent.com/33743316/55854257-c2494000-5b81-11e9-8282-53b444f04641.jpg)

Open VS Code
Open a File Explorer on left navigation by opening a workspace
Copy a file
Paste on folder
VS Code crashes with "Window Crash" error

VS Code version: Code - Insiders 1.34.0-insider (56f1b4795fed05677eb82a21dac4fc1ab62d747b, 2019-04-09T05:19:45.294Z)
OS version: Windows_NT x64 10.0.18845

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment]
Can not reproduce.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, please can you give exact repro steps, or a gif of the issue happening
