### ISSUE TITLE
Finding in problems does not expand nodes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7204]
When I search for problems we do not expand collapsed nodes automatically but we should.

**Comment by sandy081** [comment]
@bpasero what is expected if a file has many markers (say more than 10) after applying find text? In general, files are collapsed if they have many markers just like in Search view

**Comment by bpasero** [comment]
Well in this case the node just had 1. I am fine still keeping nodes with > 10 elements collapsed.

**Comment by bpasero** [comment]
I can still reproduce, see video:

![sd](https://cloud.githubusercontent.com/assets/900690/16522924/e42e2906-3fa0-11e6-8b11-27731ae82978.gif)

**Comment by sandy081** [comment]
@bpasero All are expanded by default. But when user collapse any, then I am not expanding them even during filtering. I think if user collapses it specifically then it is good to retain it.

**Comment by bpasero** [comment]
@sandy081 I am not sure about that, the user might have clicked on the "Collapse All" action to get an overview and then wants to drill in. What use is it to keep something collapsed that has valid search results? I am still fine to not expand if count > 10.
