### ISSUE TITLE
symbols with a prefix in common with a C++ reserved word are rendered incorrectly

### ISSUE THREAD

**Issue by purplegerbil** [Microsoft/vscode#72046]
![vs code bug](https://user-images.githubusercontent.com/44987214/55857512-32c07480-5b22-11e9-897c-f343af285a3a.png)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. create a function with this (or similar) name in the editor, using C++ highlighting: ListNode* delete_duplicate_nodes_sorted(ListNode* head)
2. observe the rendering: "delete" is highlighted as though we're dealing with a keyword, but it's no longer a keyword after the subsequent characters.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
What version of VS Code are you using? I can't reproduce this in Insiders or in 1.33.1

**Comment by purplegerbil** [comment]
I don't see it repro on 1.33.1 either; maybe I was on the previous version and I just got automatically updated.  Thanks.
