### ISSUE TITLE
Tab key adds random number of spaces instead of specified

### ISSUE THREAD

**Issue by vishnumaiea** [Microsoft/vscode#72044]
Issue Type: <b>Bug</b>

There are options to control whether Tab characters are replaced by 'n' number of spaces or not, and also to convert between existing tabs and spaces. Following is my setting (on both User and Workspace configs),

Editor: Detect Indentation - False
Editor: Tab Size - 2
Editor: Insert Spaces - True
Editor: Use Tab Stops - False (changing this has no effect)

Yet, whenever I press the Tab key, I get **RANDOM** number of spaces than what I have set. For example, Tab will be replaced with 2 spaces at some places and 1 space at some other place.

Why is this weird behavior ? My requirement is just to replace Tabs (when I press Tab key) with specified number of spaces **ALWAYS** instead of random number of spaces. That is the way I was working on Atom.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vsc-material-theme|Equ|2.8.2
tag-inserter|l7s|1.4.0
vscode-auto-timestamp|lpu|0.0.1
cpptools|ms-|0.22.1
code-spell-checker|str|1.6.10
rainbow-tags|vol|0.0.3
vscode-arduino|vsc|0.2.25
vscode-icons|vsc|8.5.0
TabSpacer|yui|1.0.2

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Are you expecting that regardless of whether your cursor is in an odd-numbered column or an even-numbered column, pressing TAB will always insert 2 spaces because of those settings?

AFAIK that's not how VSCode behaves. In response to you pressing TAB it inserts enough spaces (at least 1) to move you to the column position of the next tabstop.

For example, when set to Spaces: 8 and I type 1,TAB,|,ENTER,1,2,TAB,|,ENTER,1,2,3,TAB,|,ENTER etc
```
1       |
12      |
123     |
1234    |
12345   |
123456  |
1234567 |
12345678       |
```

**Comment by vishnumaiea** [comment]
@gjsjohnmurray Thanks for the explanation. I tried out your example on Atom with the same setting you said, and found to be working the same way. So I was wrong with my statement on Atom.

I now understand how Tab works (I always thought it would simply place Tab character or equivalent number of spaces, but I was wrong), and how it is used to "align" text.

But since we [developers] are more concerned with indentations rather than alignment, wouldn't it be logical if Tab key produced same number of spaces everywhere ? For example, if the indentation I prefer is 2 spaces, both auto indentation and Tab key should produce 2 spaces everywhere. What do you think ?

**Comment by gjsjohnmurray** [comment]
I disagree. I'm happy with the current behaviour.

**Comment by vishnumaiea** [comment]
@gjsjohnmurray Thank you :)
