### ISSUE TITLE
Copy file name will trigger update imports 

### ISSUE THREAD

**Issue by taven-liu** [microsoft/vscode#72057]
- VSCode Version:  1.33.0 
- OS Version: MacOS 10.14.4

Steps to Reproduce:

1.  Open VSCode 
2. Open a React project
3. Select a file in VSCode explorer panel
4. Tap `enter` to edit file name
5. Tap `command` +` c` to copy file name
6. Click elsewhere and then will automatic popup a dialog to `update imports for move file: [selected file name]`

Does this issue occur when all extensions are disabled?: Yes

**Comment by WangXiaoxi** [comment]
I had the same problem

**Comment by itamark** [comment]
Trying to reproduce. What version of vscode is this happening in? Are you sure all extensions are off?

![cannot_reproooo](https://user-images.githubusercontent.com/1757393/62361764-a7f8f080-b4e9-11e9-81c9-cc0c88c8e39d.gif)

**Comment by mjbvz** [comment]
I also can't repo this using a simple project from create-react-app. @taven-liu Please provide a step by step guide (preferably with a small example project also) that explains how to reproduce the problem
