### ISSUE TITLE
Opening the terminal window doesn't show the path

### ISSUE THREAD

**Issue by Humadroid** [Microsoft/vscode#72051]
Issue Type: <b>Bug</b>

1. Opening the terminal window doesn't show the path, on the first time.
2. Start typing any commands it will run, but the path is not visible.
3. Stop the running commands by pressing Ctrl+C and press enter, now the path is visible and you can run the commands again.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
vscode-pull-request-github|Git|0.6.0
beautify|Hoo|1.4.11
Angular2|joh|7.0.1
vscode-kubernetes-tools|ms-|0.1.18
mssql|ms-|1.5.0
python|ms-|2019.3.6558
notepadplusplus-keybindings|ms-|1.0.2
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.45
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.11
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-manifest-yaml|Piv|1.5.0
vscode-spring-boot|Piv|1.5.0
java|red|0.42.1
vscode-yaml|red|0.4.0
live-sass|rit|3.0.0
LiveServer|rit|5.5.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5
vscode-react-native|vsm|0.9.1

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
