### ISSUE TITLE
British Keyboard Layout: System keymaps overridden

### ISSUE THREAD

**Issue by jamesRaybould** [microsoft/vscode#72052]
The system keymaps appear to have been overridden in the latest release. In all other applications using cmd + ` scrolls through all the open windows in that application. Currently it does nothing when using the British PC keyboard layout

VSCode Version: 1.32/1.33
OS Version: OSX 10.13.6
Steps to Reproduce:

- Open VSCode
- Open another VSCode window
- Attempt to scroll through the VSCode windows using cmd + \`
- Nothing happens
- If I open up the inspector window I can cmd + \` to the VSCode window, but then I can't use cmd + \` to go back to the inspector window

I've had a similar issue in the past reported in #24044

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@jamesRaybould What kind of physical keyboard are you using?

ISO or ANSI?
![image](https://user-images.githubusercontent.com/5047891/57219992-1537db00-6ffa-11e9-9825-bca269c87e87.png)

**Comment by jamesRaybould** [comment]
Hi @alexandrudima it's an ISO layout

**Comment by alexandrudima** [comment]
I can reproduce, using an ISO keyboard and the British - PC keyboard layout, `` cmd+` `` (left of <kbd>1</kbd>) does not switch between VS Code windows, while it is possible to switch between windows of other applications.

**Comment by mogwai** [comment]
The key is read as a | in vscode.

**Comment by mogwai** [comment]
I've tried looking into it but I can't find out where the ` is being translate to a | in the code base. 

This makes working on multiple projects much harder and is pretty important. Has been an issue since March #69745

**Comment by alexandrudima** [comment]
@mogwai What do you want to do? You can change what any key produces in VS Code by doing:

e.g.
```
{ "key": "[IntlBackslash]", "command": "type", "args": { "text": "`" }, "when": "isMac && editorTextFocus" },
```

**Comment by danielthepope** [comment]
As a workaround for this I have set the following in my keybindings.json:
```json
[
    {
        "key": "cmd+`",
        "command": "workbench.action.quickSwitchWindow",
        "when": ""
    }
]
```
That file can be accessed by clicking Code > Preferences > Keyboard Shortcuts.

That function behaves similarly to what you would expect cmd+` to do, except it brings up a new dialog that you need to use your arrow keys to navigate (instead of mashing the backtick key). See if that works for you.

Also, not sure if it's relevant to working out what the problem is, but that keybinding shows this extra bit of dialog for me (British PC keyboard layout, OSX 10.12):

![image](https://user-images.githubusercontent.com/5173183/62793958-c8691200-baca-11e9-8ca4-3438dd09d4b1.png)

**Comment by mogwai** [comment]
@danielthepope Your a star. This has fixed the issue

**Comment by danielthepope** [comment]
I'd say _mitigated_, not _fixed_. It's still not ideal but I'm glad that it's helped you :+1:

**Comment by alexandrudima** [comment]
The looping of `` cmd + ` `` through Windows is done by the OS or Electron/Chromium, not by any piece of code we have written. I am sorry, but there is no possible code change I can do in VS Code to alleviate this.

**Comment by danielthepope** [comment]
OK, thanks for the update @alexandrudima. I thought it was a VSCode specific problem since I could cmd + ` with Chrome. I hadn't tried any other Electron apps until just now, when I have the exact same problem with the Hyper terminal app.
Thank you for looking into this anyway.
