### ISSUE TITLE
Editor zooming (editor.mouseWheelZoom) is too sensitive

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#72050]
On a MacBook Pro, when I have `editor.mouseWheelZoom` enabled, the pinch-zooming is way too sensitive – I only move my fingers like 2-3 mm and the zoom ratio goes all the way up or down.

For scrolling, there's a setting `editor.mouseWheelScrollSensitivity` but I don't think anything similar exists for editor zooming; the default value is way too eager.

Tried on these versions:

- Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
- Code - Insiders 1.34.0-insider (07d9e44f910223e7ab6d3e8bc02439f39213cd90, 2019-04-10T05:14:23.598Z)
- OS version: Darwin x64 18.5.0

Does this issue occur when all extensions are disabled?: Yes

**Comment by rikkit** [comment]
I have the same problem on my Surface Pro 4.

**Comment by nicoandmee** [comment]
I too experience this issue on a M1 MBP. Maybe I'm just OCD, but it drives me crazy when I do Cmd+Mouse/Track Wheel and the editor zoom goes to almost max.

**Comment by carvalhopatrick** [comment]
I also experience this in a Windows laptop with Preicison touchpad. Both pinch to zoom and zooming with Ctrl + scroll gesture

**Comment by bhavyaus** [comment]
Tried this on my surface laptop and the editor still appears to be too sensitive to my pinching on the mouse pad. Is there a settig I should enable for the sensitivity? And the scrolling appears to "bounce back" into place when using the mouse pad. Is this expected?
