### ISSUE TITLE
最末尾行会置于窗口最上方的问题

### ISSUE THREAD

**Issue by JonasAi** [Microsoft/vscode#72055]
当很大力向下滑动鼠标的时候文件最末行会跑到窗口的最上方,希望能优化,让最末行始终处于窗口的2/3之后的位置,谢谢

**Comment by JonasAi** [comment]
![image](https://user-images.githubusercontent.com/18554399/55866645-58498e80-5bb3-11e9-890b-44d25b5946a9.png)

**Comment by aeschli** [comment]
Translation:
When the mouse is swiped down a lot, the last line of the file will run to the top of the window. I hope to optimize it so that the last line is always after the 2/3 of the window. Thank you.

**Comment by rebornix** [comment]
You can turn this off by setting `editor.scrollBeyondLastLine` to false.
