### ISSUE TITLE
v1.33 crashes IntelliSense in React/NextJS

### ISSUE THREAD

**Issue by spacecakes** [Microsoft/vscode#72059]
- VSCode Version: 1.33
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Open any React JavaScript file and start typing and TypeScript produces a log like this (verbose setting turned on): `[Trace  - 11:59:39] TypeScript Server: trying to cancel ongoing request with sequence number 16`
 
2. This does not happen in `v1.32` which I just reinstalled. It does not happen in plain JS files either. It has something to do with my project but I cant figure out what. 

[Full log here](https://pastebin.com/aamwGBL5)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tpdewolf** [comment]
I have the same problem

**Comment by mikedloss** [comment]
Can confirm intellisense doesn't seem to be working correctly on my side too. Both JS and TS files inside of React projects. Another person on my team is also having the same issues.

**Comment by markunmind** [comment]
This seems to be occurring specifically in React Native for me, but works in React. I can see the following error in tsserver.log: `[16:48:39.955] Failed to load module 'typescript-tslint-plugin': Error: Could not resolve JS module 'typescript-tslint-plugin'`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by markunmind** [comment]
@mjbvz latest VS Code insiders build **doesn't** reproduce issue with extensions disabled OR enabled.

**Comment by nguyenkhois** [comment]
IntelliSense works fast and stable in version 1.32.3 (even with installed extensions and snippets). 
I'm very happy with that when I can code faster.

I agree with @markunmind at it's a small bit of lag in version 1.34.0 insider although it's much better than version 1.33.0. It affects my experience. Many thanks!

**Comment by changLiuUNSW** [comment]
Can confirm intellisense also not working for my React native typescript project. Have to downgrade to 1.32

**Comment by mjbvz** [comment]
@spacecakes have you tested the latest insiders build? Also, do you have `@types/styled-components` under your `node_modules`?
