### ISSUE TITLE
[loc][Query][VSCODE] Localizability of string: The action 'debugWithChrome' requires the '{0}' (1)

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#72065]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
The action 'debugWithChrome' requires the '{0}' (1)
Extension id or VSIX resource uri (2)

Query:
Could you please clarify the context, in which the given string (1) appears? It seems that the string is part of the following segment (2), but we are not entirely sure. Please clarify and check

**Comment by weinand** [comment]
The message warns the user if she has configured a "serverReadyAction" of a launch.config to open the Chrome debugger but doesn't have the 'Debugger for Chrome' extension installed.

I've changed the message to include the word "extension" and I've converted the string literal 'debugWithChrome' into a parameter to prevent it from translation:
```
"The action '{0}' requires the '{1}' extension.", 'debugWithChrome', 'Debugger for Chrome'
```
