### ISSUE TITLE
[loc][Query][VSCODE] Localizability of string: When set to `false` IntelliSense never shows `customcolor` suggestions.

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode#72068]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
When set to `false` IntelliSense never shows `customcolor` suggestions.

Query:
Is "**customcolor**" supposed to be localized? Left in English for the time being. Please confirm. Please note that this also refers to other strings, such as

When set to `false` IntelliSense never shows `constructor` suggestions.

**Comment by jrieken** [comment]
No translation needed
