### ISSUE TITLE
creating new ALProject gives error "Cannot resolve workspace folder"

### ISSUE THREAD

**Issue by yuvrajsharma** [Microsoft/vscode#72061]
With this new version
**VSCodeUserSetup-x64-1.33.0**
I get error while creating new AL Project. It produces yellow marked folder and doesn't recognise it as ALProject.

But when I try same thing in older version **VSCodeUserSetup-x64-1.32.3**, it works fine.

- VSCode Version:1.33.0 (user setup)
- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Creating new ALProject by AL!Go (Ctrl+shift+P)
2. It gives a yellow marked folder with errir "Cannot resolve workspace folder"

Does this issue occur when all extensions are disabled?: Not Applicable
I am working it with AL Extension

Name: AL Language
Id: microsoft.al
Description: Extension development support for Dynamics NAV
Version: 0.13.82793
Publisher: Microsoft

**Comment by aeschli** [comment]
Please file issue again https://github.com/Microsoft/AL
