### ISSUE TITLE
The output of terminal doesn't show properly

### ISSUE THREAD

**Issue by StevenCSU** [Microsoft/vscode#72063]
- VSCode Version:1.33.0
- OS Version:macOS Mojave version10.14.4

Steps to Reproduce:

1.When I open the terminal inside the vscode and input some command, it doesn't show properly.
2.It always output the command I just input and the right output after that.

```
(base) ➜  flasky git:(master) ✗ source /Users/zhangyin/anaconda3/bin/activate
source%    
(base) ➜  flasky git:(master) ✗ conda activate web
conda% 
(web) ➜  flasky git:(master) ✗ ls
lsREADME.md   __pycache__ hello.py
```

As you can see, it always repeat the command I just input.
And it shows a '%' if it shouldn't output anything. Like `source%` and `conda%`.
If the command has an output, it will also output the command. Like `ls`.

However, my iTerm and Atom terminal works well. These two terminals output properly.
I have tried some ways, reinstall vscode, reset the settings to default. They don't help. 
How can I fix it? Thank you!

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What's in your settings.json file? This is likely some issue with your environment otherwise there would be heaps of reports like this (and I would be seeing it).

**Comment by Tyriar** [comment]
Also are you using the Python extension? How are you launching the terminal?

**Comment by StevenCSU** [comment]
It works well now. And I don't know why...
