### ISSUE TITLE
workbench.startupEditor Behavior

### ISSUE THREAD

**Issue by rgb86** [Microsoft/vscode#72064]
Issue Type: <b>Bug</b>

As of version 1.33.0, VS Code is no longer respecting the setting:
"workbench.startupEditor": "newUntitledFile"

Upon startup, a new blank file is no longer opened.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.66GB (26.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.8
gc-excelviewer|Gra|2.1.32
reg|ion|0.0.2
nbpreviewer|jit|1.2.2
classic-asp-html|jtj|0.1.1
rainbow-csv|mec|1.0.0
Angular-BeastCode|Mik|8.0.1
prettify-json|moh|0.0.3
python|ms-|2019.3.6558
powershell|ms-|1.12.0
vscode-autohotkey|sle|0.2.2
vba|spe|1.2.0
plsql-language|xyz|1.8.1

</details>

**Comment by bpasero** [comment]
This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/
