### ISSUE TITLE
[loc][Query][VSCODE] Localizability of string: file path of the workspace

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#72069]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
`${rootPath}`: file path of the workspace (e.g. /Users/Development/myWorkspace).

Query:
Is file path supposed to be localized or left in English?

**Comment by roblourens** [comment]
It should be localized
