### ISSUE TITLE
Window changes height everytime it is minimized and restored.

### ISSUE THREAD

**Issue by me-egits** [microsoft/vscode#72060]
Issue Type: <b>Bug</b>

1. Set windows scaling above 100%. (Mine is set to 125%)
2. Open VS Code.
3. Put it into not maximized window mode.
4. Minimize the window.
5. Restore the window.
6. Notice that the height of the window is increased by a few pixels every time it is restored.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (4.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity|Jua|0.0.50
t4-support|zbe|0.4.2

</details>

**Comment by Tyriar** [comment]
Related to https://github.com/Microsoft/vscode/issues/38574?

**Comment by sbatten** [comment]
@me-egits I can't actually reproduce this on my machine with any scaling, but its likely an electron issue since we don't have any code around this behavior.
