### ISSUE TITLE
VS 19 Professional : Cannot navigate to the symbol under the caret

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [Microsoft/vscode#72076]
I have just installed VS 19 Professional but Navigation is not working.
I have a Web Based Project.The project always compiles successfully but Navigation is not working with my project,
Please Advice!

![VS19Error](https://user-images.githubusercontent.com/36439393/55884582-9ab99e00-5ba8-11e9-8c81-5d5f0d8dad0e.PNG)

**Comment by KexyBiscuit** [comment]
Please report Visual Studio problems to [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by mybhavsar9** [comment]
This is happening to projects that are using v1.0.0 of Microsoft.Net.Compilers. To work around this problem you need to update to the latest stable version which is 3.0.0. To do that you can follow the these steps:

1) Right click on "References" in the Solution Explorer
2) Select "Manage NuGet Packages"
3) Under the "Installed" tab search fro "Microsoft.Net.Compilers"
4) Select "Microsoft.Net.Compilers"
5) On the side window of "Microsoft.Net.Compilers" click the update button

That should allow you navigate to definitions
