### ISSUE TITLE
Customizable data tip 

### ISSUE THREAD

**Issue by AdowTatep** [Microsoft/vscode#72073]
- VSCode Version: 1.33.0
- OS Version: Windows_NT x64 10.0.17763

Could we get an option to customize the hover over data tip/tooltip css values?

Currently sometimes the size is just too small and not so good to look through and horrible to expand:
![image](https://user-images.githubusercontent.com/12276174/55884027-b78cac00-5b7d-11e9-8c48-c02c78a2ec88.png)

Visual Studio 2015/2017 does it right and since VSCode is inspired by it, its data tip should be the same but it is not.

I'd like to change its width/height a bit, and also give it a padding. If so, anyone should be able to change the css as desired to fit everyone's needs.

Therefore, I ask you to implement this feature, which I had in my mind for so long.

Steps to Reproduce:

1. Debug something
2. Hover over a defined variable

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/67620
Making customizable css is out of scope
