### ISSUE TITLE
Settings: commonly used not interactable by VoiceOver

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#72078]
From @PeterSaathoff-Harshfield

On the left side of the settings screen is a section called "commonly used." This section can't be read or interacted with by VoiceOver. It is reported as, "empty table."

**Comment by roblourens** [comment]
This is just a tree like other trees. Are there other issues or has this been fixed @isidorn?

**Comment by isidorn** [comment]
This works fine now. Just make sure to have Voice Over set to medium verobosity at least.
