### ISSUE TITLE
make emmet work in JSON files (or everywhere)

### ISSUE THREAD

**Issue by pitommasi** [Microsoft/vscode#72072]
I sometimes need to add html in json files and EMMET would be useful (I come from Atom).

I cannot, however wrap my head around the "emmet.includeLanguages" settings, as every source I've been looking at simply copy/pastes what it is written in the official documentation, some examples and nothing more.
It would be useful to have in the documentation what is the syntax of that preference, I mean, what goes as key and what as value? Let's say I want to enable it for
JSON files, how it should be?

So far, I've tried 
`"json":"html"`
`"json":"javascriptreact"`
both lowercase and uppercase

I've also tried adding
`"emmet.showExpandedAbbreviation": "always"`
to no avail

Also, wiuld it be possible to make Emmet work anywhere, even in "untitled" files, like it is for other editors, such as Atom?

**Comment by octref** [comment]
Why would emmet be useful in JSON files?

**Comment by pitommasi** [comment]
As already stated in my request:
> I sometimes need to add **html in json files** and EMMET would be useful (I come from Atom)

Anyway, I will reverse the question: 
why is VSCode limiting Emmet to the context? 
What's wrong with the approach that the other editors have to let Emmet work anywhere?
In Atom or even in Notepad++ I can use Emmet anywhere...

At least, let ME have the choice to let it work anywhere or just as per `emmet.includeLanguages` settings

**Comment by ramya-rao-a** [comment]
Adding the below to my settings allows me to use emmet in json files
```
"emmet.includeLanguages": {
    "json": "html"
  }
```

Check if the file you are working on is `json` or `jsonc` (JSON with comments) and use the right one as the key

**Comment by pitommasi** [comment]
Thanks but, if you read my original post, I've already tried that to no avail...

That said, the file where I am testing emmet is a json file (matter of fact, I am testing in the very same settings.json where I am trying to enable Emmet).

Again, what is the reasoning behind limiting Emmet only for certain files, for certains languages?
I have also seen people complaining that you cannot set it so it works for two separate languages in the same file type (e.g.: javascript and html in a PHP file - which is far from uncommon)...
What's the point? Why not having the option to enable Emmet just everywhere?

**Comment by pitommasi** [comment]
OK, I've found the problem and it is even more annoying than I thought...
In order to make in work, I've had to MANUALLY set 

`    "files.associations": {
        "*.json": "json"
    }`

Really?

**Comment by pitommasi** [comment]
I'm wondering why you keep ignoring my other question: why restricting the context where Emmet cam be used?

**Comment by octref** [comment]
Because people can get annoyed by irrelevant emmet suggestions, especially in files that has nothing to do with emmet like python or java?

**Comment by pitommasi** [comment]
Given that one might also need it in java or python, why not leaving to the user the choice, whether to enabling it everywhere or by filetype?

**Comment by octref** [comment]
You can write your own extension using this library: https://github.com/Microsoft/vscode-emmet-helper. I wouldn't support it.

**Comment by ramya-rao-a** [comment]
@pitommasi If you had to set `"files.associations": { "*.json": "json" }` specifically then that is a different issue altogether. Most likely you have an extension that is mapping your json files to some other type.

Emmet is a language specific feature and therefore enabled in languages where it makes the most sense. Number of users wanting to use emmet in other languages are much lesser than those who never want to use emmet or even heard of emmet for that matter. Therefore, it is an opt-in feature for the former group of people rather than opt-out for the latter i.e majority of users.

Coming to your point of enabling it everywhere, one can imagine the `emmet.includeLanguages` setting to accept `*` as the key. I will leave it up to @octref and the team if they will consider a PR for this. If they do, then you are most welcome to submit a PR to that affect.

**Comment by pitommasi** [comment]
Thanks @ramya-rao-a, that is exactly what I was talking about: 
I understand the choice of the default being what it is - and I wasn't discussing that - but it would be nice to have either the 

> `emmet.includeLanguages` setting to accept `*` as the key

as you said, or an

`emmet.expandAnywhere` setting that overrides the default behaviour when set to `true`...

I've seen other people opening issues here with requests that, although not identical, are similar to mine, 
a couple of examples:

[More than on language in PHP](https://github.com/Microsoft/vscode/issues/70324)
or
[One to many mapping](https://github.com/Microsoft/vscode/issues/62910)
