### ISSUE TITLE
No possibility to remote debug on folders mounted through WinSSHFS

### ISSUE THREAD

**Issue by filipski** [Microsoft/vscode#72070]
Issue Type: <b>Bug</b>

Up until today morning, remote debugging on Python with ptvsd was working fine. Then I got 1.33 update and none of my breakpoints can be found anymore, I get warnings like:

`pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/<my username>/projects/<my project folder>/v:/projects/<my project folder>/<python file to debug>.py (will have no effect)`

I have my remote Linux home folder mounted on Windows with WinSSHFS as a V: drive. 
I made no other changes to the environment nor the project, just allowed installation of 1.33 VSCode update. Please fix asap as it's prevening me from remote debugging efficiently.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (24.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
restructuredtext|lex|106.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
vscode-yaml|red|0.4.0

</details>

**Comment by filipski** [comment]
Thanks a lot for quick reply!
Which of those 4 extensions caused the problem? 
Why did it start after updating just the VSCode? I haven't updated any of the extensions, at least not manually.

**Comment by weinand** [comment]
The Python extension. 
Even if VSCode has introduced an issue in the latest release that affects the Python extension, then the Python team should investigate first and then file an issue against VS Code.
We are not aware of a general problem in that area.
