### ISSUE TITLE
Automatically open blank document.

### ISSUE THREAD

**Issue by garretwilson** [Microsoft/vscode#72082]
I'm on Windows 10 using VS Code 1.33.0.

Sometimes I want to just have a blank scratch document to work with, so I have configured a Windows shortcut to open up a new VS Code in a new window. There's nothing complicated about the shortcut:

    "C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe" --new-window

But in the latest versions the new window is still blank, and I still have to hit `Ctrl+N` to actually get a document to type on.

How can I get VS Code to open a new document automatically when opened in a new windows? (I could have sworn that this was how it worked already, but it's not working now.)

**Comment by bpasero** [comment]
This issue has already been fixed in our insiders version but not yet released to the stable version. To benefit from the fix, you can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by garretwilson** [comment]
If this is a duplicate, could someone provide a link to the duplicated issue?
