### ISSUE TITLE
Blank terminal - Git Bash

### ISSUE THREAD

**Issue by opiyonico** [Microsoft/vscode#72081]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I have a node.js server running and I'm using Git bash on Windows 10 Pro 64-bit. My terminal doesn't show text after some time when my node server is running. I can copy the text and read it on a txt file but the terminal stays blank. I can only see the cursor position.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|0.5.0
vsc-material-theme|Equ|2.8.2
font-switcher|eva|3.0.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
python|ms-|2019.3.6558
java|red|0.42.1
format-html-in-php|rif|1.5.3
LiveServer|rit|5.5.1
rewrap|stk|1.9.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1
vscode-icons|vsc|8.5.0
pyqt-integration|zho|0.2.0

</details>

**Comment by Tyriar** [comment]
Do you mean the terminal blank in the beginning? If it was blank some time later, did you sleep/resume your OS at some point?

**Comment by opiyonico** [comment]
No, it wasn't blank from the beginning. I cannot remember if my computer went to sleep but I was working on it all along. I don't think it went to sleep. I have tried sleeping OS but that doesn't seem to affect the terminal.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
