### ISSUE TITLE
VSCode doesn't support leading slash imports

### ISSUE THREAD

**Issue by matthew-dean** [Microsoft/vscode#72093]
Issue Type: <b>Bug</b>

This commit added support for leading-slash module resolution. 
 https://github.com/Microsoft/TypeScript/pull/27980

However, even though TypeScript / tsc will handle it fine, VSCode will mark leading slash imports with the error "cannot find module". In addition, typing a `/` slash will show Intellisense / autocomplete for the system root instead of the tsconfig mapped root.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
gitlens|eam|9.5.1
vsc-material-theme|Equ|2.8.2
vscode-sort|hen|0.2.5
JSDocTagComplete|Hoo|0.0.2
nearley|kar|1.0.3
vscode-lebab|mrm|2.6.0
cpptools|ms-|0.22.1
vetur|oct|0.18.0
material-icon-theme|PKi|3.7.0
final-newline|sam|0.3.2
code-settings-sync|Sha|3.2.7
trailing-spaces|sha|0.2.11
cmake-tools|vec|1.1.3

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please share your tsconfig

**Comment by matthew-dean** [comment]
@mjbvz 

```
  "compilerOptions": {
    "baseUrl": "app",
    "jsx": "react",
    "esModuleInterop": true,
    "paths": {
      "config/*": ["../build/config/*"],
      "~/*": ["react/*"],
      "/*": ["../*"]
    },
```

**Comment by mjbvz** [comment]
In the effected file, run the `TypeScript: go to project configuration` command. Does this open the correct tsconfig?

**Comment by mjbvz** [comment]
Closing as needs more info

**Comment by matthew-dean** [comment]
@mjbvz Good call! The tests folders were excluded from TS builds (in `tsconfig.json`), so apparently that excludes them from VSCode linting (?), which I didn't realize.
