### ISSUE TITLE
Go to next unused 

### ISSUE THREAD

**Issue by cristian3d** [Microsoft/vscode#72099]
Similar to "Go to Next Problem" (f8, alt/f8) but for unused vars, fields, imports, functions, etc.

It'd help cleaning up the code while still being able to check what each of them are.

**Comment by mjbvz** [comment]
You should have your language or linter mark unused code as an error/warning. That ways they show in the problems panel and f8 works

For js/ts, just set `noUnusedLocals` in your `jsconfig` or `tsconfig`
