### ISSUE TITLE
vscode doesn't resolve gradle import dependencies macOS

### ISSUE THREAD

**Issue by mentaloaf** [Microsoft/vscode#72091]
I am using Java 11 and gradle 5.3.1 (via macports) on macOS.  When I am viewing Java source for a gradle project, many of the Java language extension features don't function properly.  It complains about unresolved symbols even though my build works properly.  I also get this error message in the problems:

Could not create an instance of Tooling API implementation using the specified Gradle installation '/opt/local/share/java/gradle'.
Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64.

The Gradle installation directory it reports does not exist.  I have tried setting GRADLE_HOME and running Electron from the command line with no luck.  FYI - the only instance of the file libnative-platform.dylib on my mac is in ~/.gradle/native/25/osx-amd64/ which does appear to be in use by IntelliJ if I fuser the file.

Vscode was working so well with Maven projects - all the Java language features worked beautifully so I am hoping this issue can be resolved soon/easily as I have moved on to Gradle and Java 11.

- VSCode Version: 1.34.0-Insider (and latest stable Mac OS version)
- OS Version: Mojave 10.14.4

Steps to Reproduce:

1. Add gradle project folder to workspace
2. You will see the error message regarding libnative-platform.dylib
3. Open a Java file and witness most/all Java language dynamic features don't work

The issue doesn't happen with extensions disabled but that's not surprising since my issue is with the extensions functioning properly.

**Comment by aeschli** [comment]
Please file the issue against the extension that you use for Java.
https://github.com/redhat-developer/vscode-java ?
