### ISSUE TITLE
when debug cpp, variable value read from ifstream is wrong

### ISSUE THREAD

**Issue by shaozi** [Microsoft/vscode#72095]
Issue Type: <b>Bug</b>

If a variable is read from an ifstream, its values does not update in debug VARIABLES window.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|-psn_0_180268|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
Angular2|UVB|0.4.1
angular1-code-snippets|ale|0.0.3
vscode-intelephense-client|bme|1.0.13
systemd-unit-file|coo|1.0.3
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
python|don|0.7.0
xml|Dot|2.4.0
auto-close-tag|for|0.5.6
vscode-emacs|hir|0.1.1
rails-snippets|Hri|1.0.8
mysql-syntax|jak|1.3.1
Angular2|joh|7.0.1
graphql-for-vscode|kum|1.13.0
eml|lei|0.3.2
restructuredtext|lex|106.0.0
vue|liu|0.1.5
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
mssql|ms-|1.5.0
python|ms-|2019.3.6558
cpptools|ms-|0.22.2-insiders
Go|ms-|0.9.2
vsliveshare|ms-|1.0.45
debugger-for-chrome|msj|4.11.3
ReactSnippetsWithoutSemicolons|not|1.3.1
vetur|oct|0.18.1
vscode-docker|Pet|0.6.1
diff|raf|0.0.1
tcl|ras|0.1.0
ruby|reb|0.22.3
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.0
language-stylus|sys|1.11.0
ReactSnippets|xab|2.3.0
licenser|ymo|1.3.1
markdown-pdf|yza|1.2.0

</details>

**Comment by shaozi** [comment]
sample code:

```cpp
#include <fstream>
#include <iostream>

using namespace std;

int main()
{
  long long l;
  ifstream input;
  input.open("data.txt");
  input >> l;
  cout << l << endl;
  return 0;
}
```

When run lldb, variable `l` does not update to the read value.

**Comment by weinand** [comment]
please file against C++ debugger
