### ISSUE TITLE
On maximizing the panel I would expect to have the focus on the prompt.

### ISSUE THREAD

**Issue by deniercounter** [microsoft/vscode#72090]
More often than not i maximize the panel where I have my npm commands and corresponding outputs and write a command ... only to learn that I wrote the command at my cursor in the hidden editor above. In this moment I even can't see any code and where the cursor actually stays in the document.

I would expect to have the focus at the command prompt when I maximize the panel taken the fact that I already clicked in this window (respectively panel) by maximizing it.

(Feature request)

**Comment by isidorn** [comment]
This is a fair feature request. Leaving it open for now to collect more feedback.
fyi @sbatten

**Comment by jbaileyashe** [comment]
Since the August release I've been using the "Toggle Editor Area" command to quickly bring up a full-window maximized terminal. I've also noticed that the input focus does not get placed in the terminal window.
