### ISSUE TITLE
syntax highlighting fails on valid code

### ISSUE THREAD

**Issue by 3DdeepAI** [Microsoft/vscode#72096]
Issue Type: <b>Bug</b>

```
// .h file with C++ syntax highlighting
#ifdef USE_IN_HLSL
cbuffer  testCB
#else
struct testCB
#endif   // <= this #endif is highlighted white although its valid
{
  float Brightness;
  // ...
};
// the .h file with this struct definition can be used in HLSL and in C++ code 
// this way
```

![endif_syntax_highlighting](https://user-images.githubusercontent.com/28405357/55911714-762de800-5be1-11e9-9074-d20088bfc020.jpg)

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.1.0
python|ms-|2019.3.6558
python|tht|0.2.3

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Moved to C++ grammar: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/88
