### ISSUE TITLE
IntelliSense Not Working

### ISSUE THREAD

**Issue by jamiljaar** [Microsoft/vscode#72092]
Issue Type: <b>Bug</b>

My IntelliSense has completely stopped working since about 2 or 3 days ago. I am not sure if it had anything to do with installing LiveShare because it was around the same time that it stopped working. Though, now that I had uninstalled LiveShare, it is still not working. No import auto-complete, no attribute suggestions, and no predeclared variable or function suggestions of any kind. I checked my settings and they all are properly set to work as it should, but it doesn't.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (18.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.1.32
vscode-styled-components|jpo|0.0.26
vs-color-picker|lih|1.0.0
vscode-language-babel|mgm|0.0.22
atom-keybindings|ms-|3.0.6
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.7.0
vscodeintellicode|Vis|1.1.5
vscode-react-native|vsm|0.9.1

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
It seem you have vscodeintellicode, maybe try disable that too?

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by jrieken** [comment]
no actionable information provided
