### ISSUE TITLE
CSS color previews stopped working

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7209]
Version 1.2.0-alpha
Commit dacf99d41fbf3929b00af685b5a985d6f2d9542d
Date 2016-06-02T20:55:38.297Z
Ubuntu 16.04

I was fiddling with rgba colors and it stopped working.

![image](https://cloud.githubusercontent.com/assets/2193314/15799116/030a3180-2a07-11e6-97a7-cbc464d8339f.png)

Console:
![image](https://cloud.githubusercontent.com/assets/2193314/15799121/1bab8e00-2a07-11e6-9ca9-c38671ab7d83.png)

Closing the file and opening it again didn't fix the issue, typing `rgba()` in from of one of the colors however did fix it:

![image](https://cloud.githubusercontent.com/assets/2193314/15799132/5d01ce8c-2a07-11e6-90da-5bf1c441b5d2.png)

**Comment by 1EyeTy** [comment]
I just install the new version a few days ago. I just noticed that in one particularly long css file that the color preview just stops after a certain point so that anything after that point does not show the preview but if I move code above that point it works. Really odd.

**Comment by aeschli** [comment]
For performance reasons, there's a maximum of 500 color decorator we render

**Comment by 1EyeTy** [comment]
Great to know. Thanks aeschli

**Comment by aeschli** [comment]
Not sure how to reproduce... The console error 'setDecoration on invisible editor' looks suspicious.
The implementation is now very different after moving css to an extension.
I close this and I suggest you reopen if you see it again.
