### ISSUE TITLE
Hover, quick info, tooltip when debugging is unusably small sometimes

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#72094]
- VSCode Version: VS Code
- OS Version: Windows

Steps to Reproduce:

1. Hover while debugging (I used the C++ extension). See the screenshot -- this makes VS Code hard to use. I tried to find the duplicate for this bug but I couldn't find it.

![image](https://user-images.githubusercontent.com/19859882/55907806-9d0dff00-5b8c-11e9-8a85-243bc7c2ff35.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce.
Please provide exact reproducable steps to get the hover in a bad state. 
Thank you

**Comment by sean-mcmanus** [comment]
It happens when C++ debugging on a laptop with 150 scaling and when the value is 1 root element of a tree and it's worse if you did a hover and scrolled the previous hover to the bottom, i.e. it looks like the relative scroll position is saved between hovers.

When the previous hover scroll was at the bottom:
![image](https://user-images.githubusercontent.com/19859882/55981624-fc7f1400-5c4b-11e9-9f80-601ca98c3878.png)

When the previous hover scroll is at the top:

![image](https://user-images.githubusercontent.com/19859882/55982070-ecb3ff80-5c4c-11e9-9efa-3bb2d199324d.png)

The problem is that it's hard to expand the tree elements.

**Comment by isidorn** [comment]
Try it out in monday's vscode insiders and let us know if this behaves better now.
Thanks!
