### ISSUE TITLE
dead keys can't be handled via key bindings

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode#721]
Context: Vim extension for VSC.

We try to handle all keys via key bindings so that we can process them. It seems that this suppresses dead keys.

For example, we handle `a` in a key binding. As a consequence, `´a` does not produce `á` as expected, but simply `a`.

**Comment by alexandrudima** [comment]
@guillermooo Please see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation extension for VS Code - it shows how to capture typed characters (not through keybinding rules).
