### ISSUE TITLE
/bin/sh: 1: adb: not found

### ISSUE THREAD

**Issue by rajeshbhagat** [Microsoft/vscode#7210]
- VSCode Version:1.1.1
- OS Version:Linux

Steps to Reproduce:

1. /bin/sh: 1: adb: not found
2. [vscode-react-native] [Error : 0101] Cannot debug application: Error while executing command 'adb devices': Command failed: /bin/sh -c adb devices
/bin/sh: 1: adb: not found

**Comment by bpasero** [comment]
Looks like debugging? @rajeshbhagat can you explain what you do?

**Comment by weinand** [comment]
@rajeshbhagat This looks like a vscode-react-native problem. Please file this issue here https://github.com/Microsoft/vscode-react-native/issues

**Comment by xpcode** [comment]
@rajeshbhagat can you tell me how to solve? thank you

**Comment by brunobraga95** [comment]
anybody solved it?

**Comment by weinand** [comment]
@brunobraga95 we don't know because this issue does not seem to be a VS Code issue but a vscode-react-native problem. Please file the issue in the vscode-react-native repository: https://github.com/Microsoft/vscode-react-native/issues
