### ISSUE TITLE
The terminal failed to load powershell, there is an error loading cmd

### ISSUE THREAD

**Issue by ygwoo** [Microsoft/vscode#72105]
- VSCode Version: 1.33.0
- OS Version: Windows_NT x64 10.0.17763

extra information：
- 版本: 1.33.0 (user setup)
- 提交: 0dd516dd412d42323fc3464531b1c715d51c4c1a
- 日期: 2019-04-04T15:14:28.026Z
- Electron: 3.1.6
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open terminal.
2. Powershell does not work properly in vscode.
3. Switch to cmd, the text format in the terminal is incorrect when the script is first input.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you elaborate on what "Powershell does not work properly in vscode" means and also "the text format in the terminal is incorrect"? Screenshots might help.

**Comment by ygwoo** [comment]
1. cmd text format problem：
When opening the terminal, the following picture:
![TIM截图20190415161155](https://user-images.githubusercontent.com/10443704/56116943-9bcc4000-5f99-11e9-8f85-c772cf569cb9.png)
entering a line command:
![TIM截图20190415161224](https://user-images.githubusercontent.com/10443704/56117030-d2a25600-5f99-11e9-97eb-7c5a2a9313a3.png)
The focus position is incorrect and the current path is not displayed.

 2. Powershell cannot be started in the vscode terminal. 
![TIM截图20190415162136](https://user-images.githubusercontent.com/10443704/56117403-8f94b280-5f9a-11e9-9e03-679297437a29.png)
Will always be in this state...

**Comment by ygwoo** [comment]
English is not good, please forgive me

**Comment by shihaonan369** [comment]
@ygwoo 显示问题，滚轮上滑可以看到powershell已经启动了，功能也不受影响

**Comment by shihaonan369** [comment]
@Tyriar That's a render problem, scroll up will see powershell is already run, but a lot of blank has rendered.

**Comment by ygwoo** [comment]
> @ygwoo 显示问题，滚轮上滑可以看到powershell已经启动了，功能也不受影响

哦 发现了，谢谢，那现在只存在显示格式问题了。

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
