### ISSUE TITLE
closeFindWidget keybindings don't work properly

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#72103]
Issue Type: <b>Bug</b>

The `where` clause for `closeFindWidget` does not appear to evaluate correctly when changed edited manually. I'm attempting to extend the clause to avoid closing the find widget when I have text selection in the editor (I want the clear my selection before the widget closes, not the other way around).

I replaced the existing keybinding to add `!editorHasSelection` to the `where` clause like so:

```
  {
    "key": "escape",
    "command": "closeFindWidget",
    "when": "editorFocus && findWidgetVisible && !editorHasSelection"
  },
  {
    "key": "escape",
    "command": "-closeFindWidget",
    "when": "editorFocus && findWidgetVisible"
  },
```

When doing this, pressing escape while the widget has focus immediately closes the widget.  This should happen because the `where` clause specifies `editorFocus` which isn't true when escape is pressed.

When investigating this, I noticed it seems to be a side effect of a deeper problem. If I replace the keybinding with _the exact same thing_ it no longer works correctly. It shows the behavior above where escape immediately closes the widget when it has focus.

```
  {
   "key": "escape",
   "command": "-closeFindWidget",
   "when": "editorFocus && findWidgetVisible"
  },
  {
   "key": "escape",
   "command": "closeFindWidget",
   "when": "editorFocus && findWidgetVisible"
  },
```

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (20.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.2
graphviz-preview|EFa|1.3.1
vscode-npm-script|eg2|0.3.5
vsc-space-block-jumper|jmf|1.2.2
Lua|key|0.0.9
theme-monokai-pro-vscode|mon|1.1.12
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
Go|ms-|0.9.2
powershell|ms-|1.12.0
material-icon-theme|PKi|3.7.0
code-settings-sync|Sha|3.2.8
shader|sle|1.1.4
dot|Ste|0.0.1
Align|ste|0.2.0
unity-debug|Uni|2.7.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
There are two kind of keys for editor focus:
* `editorTextFocus` - focus is in the editor's text (cursor is blinking in the editor)
* `editorFocus` - focus is in the editor's text or in an integrated editor widget like the find widget, the find all references widget, the F8 list, the rename input box, etc.

**Comment by akbyrd** [comment]
Thanks, I'm able to setup the keybindings I want now. However, that bit about replacing the default keybinding with the exact same thing causing different behavior still looks to be a bug.

**Comment by alexandrudima** [comment]
Keybindings work with a sorted rule-based engine. Any entry in your `keybindings.json` results in an operation applied to the rules. So the following content:
```
  {
   "key": "escape",
   "command": "-closeFindWidget",
   "when": "editorFocus && findWidgetVisible"
  },
  {
   "key": "escape",
   "command": "closeFindWidget",
   "when": "editorFocus && findWidgetVisible"
  },
```

means:
- remove any entries that binds `escape` to `closeFindWidget`
- append to the bottom of the rules the binding of `escape` to `closeFindWidget`.

So the above snippet in `keybindings.json` effectively means that you have moved a rule to the end of the sorted rules. The sort order is important because keybindings are evaluated from bottom to top. More details here -- https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules
