### ISSUE TITLE
Shift+Delete default shortcut keeps working after being removed

### ISSUE THREAD

**Issue by wodim** [microsoft/vscode#72117]
Issue Type: <b>Bug</b>

I removed the Shift+Delete (default action: Cut) shortcut using the editor and it keeps working. In other words, after deleting the shortcut, pressing it cuts text instead of doing nothing, which is the behaviour I expect. This is what my `keybindings.json` files says:

```javascript
// Place your key bindings in this file to override the defaults
[
    {
        "key": "shift+delete",
        "command": "-editor.action.clipboardCutAction",
        "when": "textInputFocus && !editorReadonly"
    }
]
```

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
language-gettext|mro|0.1.1
python|ms-|2019.3.6558
Go|ms-|0.9.2

</details>

**Comment by alexandrudima** [comment]
@wodim

Perhaps `shift+delete` is mapped to cut by Windows itself... Even without us binding it to cut...

Can you please try:
```
// Place your key bindings in this file to override the defaults
[
    {
        "key": "shift+delete",
        "when": "textInputFocus && !editorReadonly"
    }
]
```

This will mean `shift+delete` is bound to a no-op command. The other form means to remove the built-in keybinding, which would let `shift+delete` fall through and be interpreted by the OS itself...

**Comment by wodim** [comment]
That doesn't work. Anyway it looks like I've found a workaround. It deletes as if the shift key was not pressed but it doesn't work properly (keeps cutting) when there is no text selected. 

```
// Place your key bindings in this file to override the defaults
[
    {
        "key": "shift+delete",
        "when": "textInputFocus && !editorReadonly && editorHasSelection",
        "command": "deleteAllLeft",
    }
]
```
