### ISSUE TITLE
Search Function ENOENT

### ISSUE THREAD

**Issue by jimbo8098** [Microsoft/vscode#72118]
Issue Type: <b>Bug</b>

1. Open a workspace. Click the search icon on the left navigation bar.
2. Type in a search term. I used 
```message: "```
3. Type a file to include.
4. Press enter to search.

Searching without the file to include option works perfectly. 

VS Code version: Code - Insiders 1.34.0-insider (7a07992127a6ff176f0ed073d0698d81d09fc4bb, 2019-04-11T05:20:32.584Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
What are you typing in "files to include"?

**Comment by jimbo8098** [comment]
A full file path. Which could actually be where the issue lies. Maybe I
need to use relative reference for the file?

**Comment by jimbo8098** [comment]
I was using:
```
C:\Users\JimSpeir\Documents\Git Repos\ProjectName\dist3\bundle.js
```
where "ProjectName" is the redacted folder name. It's just upper and lower case letters, nothing out of the ordinary there. No spaces even.

**Comment by roblourens** [comment]
Unfortunately it only supports providing folders or glob patterns, not absolute paths to files
