### ISSUE TITLE
Allow to remove individual items from open file palette

### ISSUE THREAD

**Issue by lonix1** [Microsoft/vscode#72116]
The command palette has a nice feature for clearing recent files: `File: Clear Recently Opened`.

But that removes all recent files. Sometimes there is one pesky file that keeps showing up, and I inadvertently open it, instead of one that is similarly named, or has a different extension, etc.

It would be nice to be able to highlight it, then press <kbd>delete</kbd>, to remove it from the recent list. The rest of the recent files would not be affected.

**Comment by bpasero** [comment]
@lonix1 as a workaround this is possible:

![image](https://user-images.githubusercontent.com/900690/55968519-716a4200-5c7c-11e9-9b75-9cfe8244b2f5.png)

**Comment by lonix1** [comment]
Nice! Didn't know about that... :+1: 
I guess I should close?
