### ISSUE TITLE
Command 'code' not found

### ISSUE THREAD

**Issue by IHaveBeenAHero** [Microsoft/vscode#72111]
Issue Type: <b>Bug</b>

I installed vscode in my ubuntu 18.04 computer and it worked well. However, 1 day later, when i started vscode via command 'code .', the window said: 'Command "code" not found'. But I can still start vscode via the icon in software store.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.18.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2027)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.40GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.22.1
markdown-all-in-one|yzh|2.2.0

</details>

**Comment by taoliujun** [comment]
yep. the extension `relative path` worked well before, but it was broken and show `command "relative" not found` now.

**Comment by Tyriar** [comment]
How did you install vscode?
