### ISSUE TITLE
CompletionProvider Intellisense in extension working only for specific symbol ':' not for dot symbol '.'.

### ISSUE THREAD

**Issue by nuruddinfaizee** [Microsoft/vscode#72120]
Working on extension to provide Intellisense with the help of CompletionProvider API. 
I have added registerCompletionItemProvider with the triggerCharacters  as ':' it works but when i change the  triggerCharacters to dot '.' the Intellisense stops showing.
Do i have to make some extra setting change or register my trigger characters somewhere to get the Intellisense in my json document.

Another issue related to CompletionProvider what i'm facing is I'm not getting any intellisense inside a string marked in quotes "", I have checked few other people having the same issue, they are able to resolve it by adding  "editor.quickSuggestions": {"strings": true} in setting.json. 
I tried the same but no luck !! Can somebody help me what I'm missing here.

**Comment by jrieken** [comment]
> works but when i change the triggerCharacters to dot '.' the Intellisense stops showing

What does that mean? You aren't called? You are called but your results don't show? IntelliSense shows loading? IntelliSense shows suggestions from another extension?

Please provide a full sample that allows to reproduce this.

**Comment by nuruddinfaizee** [comment]
I am trying to have implement CompletionProvider in JSON document. I have a registerCompletionItemProvider with a trigger element as '.' I can see the trigger element working fine as my method is hit where I'm returning CompletionList object but I cant see any Intellisense menu in my editor.

**Comment by jrieken** [comment]
Ok - make sure to set `CompletionItem#range` and `#filterText` correctly. When unset the current word range (and label) is used and the former isn't always what you expect.
