### ISSUE TITLE
Debugger start failing. Not recognizing launch.json file.

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#7212]
- VSCode Version: 1.2.0-insider
- OS Version: Windows, OS X, Linux

Steps to Reproduce:

1. Create a new app or open an existing one.
2. Hit F5 to start debugger.

When no `launch.json` file exists VSCode creates it but then refuses to recognize it and start the debugger.

This buggy behavior is noticeable when at start you press F5 from anywhere but the Debugger. If you navigate to the Debugger and hit F5 it works and then VSCode remembers it.

Note: VSCode 1.1.1 works.

**Comment by jabaz** [comment]
I'm having same issue in VSCode 1.2.0.

**Comment by JoBrad** [comment]
Is it possible that this has something to do with NPM 2 vs 3? I also had this issue, today. A new project with no dependencies debugs fine, though.

**Comment by JoBrad** [comment]
This comment resolved this issue for me. Hopefully it helps you, too. https://github.com/Microsoft/vscode/issues/7291#issuecomment-224216216

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/7291#issuecomment-224291320

**Comment by JimiC** [comment]
:-1: @weinand Thanks for marking the original bug report as `duplicate`. I'm speechless.

**Comment by jabaz** [comment]
Thanks for help!
