### ISSUE TITLE
Allow clickable links in completion pop-up inside snippet description

### ISSUE THREAD

**Issue by beyon** [Microsoft/vscode#72127]
It would be nice if links (for example to documentation or other references) inside the description field of a snippet was click-able when presented to the user via the completions pop-up.

"Ctrl + click to follow link" as with links in text/source files would be fine.

**Comment by matbrady** [comment]
It would be helpful to cross reference the duplicate issue when closing. The only related issues I was able to track down were:
- https://github.com/Microsoft/vscode/issues/56238
- https://github.com/Microsoft/vscode/issues/10561

None of which seem to reference the way this is implemented in Atom. Atom allows for a `descriptionMoreURL` key/value that can be linked to documentation related to the snippet.

Example snippet structure:
```cson
'fs-min-height':
  'prefix': 'fs-min-height'
  'body': """@include fs-min-height(${1:$width}) {
    $2
  }"""
  'description': 'Min-height media query helper'
  'descriptionMoreURL': 'http://threespot.github.io/frontline-sass/documentation/#main-mixin-fs-min-height'
  'rightLabelHTML': '@mixin'
```

Example UX:
<img width="298" alt="Screenshot 2019-04-19 08 55 04" src="https://user-images.githubusercontent.com/1770862/56425328-c2cc8f80-6281-11e9-91b0-ef7d7c96822a.png">
