### ISSUE TITLE
Branch change doesn't always work

### ISSUE THREAD

**Issue by fredi1993** [Microsoft/vscode#72121]
Issue Type: <b>Bug</b>

I use the graphical tool to switch beetwen my branches. Most of the times it works perfectly but sometimes it just gets stuck, you click on it and nothing happens.
If you restart visual code then it works again.
I think I've seen this issue only after the last update.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2111)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 2, 1|
|Memory (System)|11.84GB (1.86GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
rtf|ale|2.0.1
vscode-eslint|dba|1.8.2
FreeMarker|dco|0.0.9
githistory|don|0.4.6
gitlens|eam|9.6.0
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.126
beautify|Hoo|1.4.11
rainbow-csv|mec|1.0.0
code-beautifier|mic|2.2.1
mssql|ms-|1.5.0
debugger-for-chrome|msj|4.11.3
laravel-blade|one|1.18.0
vscode-docker|Pet|0.6.1
vscode-jsp|pth|0.0.2
highlight-matching-tag|vin|0.9.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by joaomoreno** [comment]
Can you reproduce with `--disable-extensions`?
