### ISSUE TITLE
New Folder creation

### ISSUE THREAD

**Issue by p-racoon** [Microsoft/vscode#72126]
Issue Type: <b>Bug</b>

So once you have created a New folder, when you continue to create another folder, It does not happen, what happens is that, the menu turns dark, and the new folder name starts coming in Red. Please check into it

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.2.1
vscode-html-css|ecm|0.2.0
sublime-babel-vscode|jos|0.2.10
python|ms-|2019.3.6558
cpptools|ms-|0.22.1

</details>

**Comment by isidorn** [comment]
Dup of #72139
