### ISSUE TITLE
Explorer screen too small during RDP session from 4K monitor

### ISSUE THREAD

**Issue by aditya-giri** [microsoft/vscode#72129]
I have a laptop with a **4K (3840x2160)** display, and I often **RDP** into a workstation that has a **1920x1080** display. When I open a folder after launching VSCode, the resulting Windows File Explorer screen is not scaled and the text and icons are extremely small, making them unreadable.

I've attached a screenshot.
![vs](https://user-images.githubusercontent.com/30208735/55956282-39b1c900-5c81-11e9-90cf-5573a6697d5b.PNG)

**Comment by aeschli** [comment]
How is this related to VSCode? Looks to me that it's rather a problem if the RDP window?

**Comment by aditya-giri** [comment]
I don't think so. During the same RDP session, if I open the same Explorer view via another text editor like Notepad++, it scales it up before displaying. Opening File Explorer by itself also scales correctly. I'm seeing this only with VSCode.

**Comment by aeschli** [comment]
Is it the `Reveal in Explorer` command that you are using?

**Comment by aditya-giri** [comment]
*Reveal in Explorer *seems to work fine, but *Open Folder* does not

**Comment by aditya-giri** [comment]
`Reveal in Explorer` seems to work fine but `Open Folder` does not.
