### ISSUE TITLE
Terminal "cls" not working expected

### ISSUE THREAD

**Issue by lyh-ADT** [microsoft/vscode#72130]
Issue Type: <b>Bug</b>

on Windows 10 Home Insider version 18362.53
After using "cls", previous output still show in the terminal(powershell)

VS Code version: Code - Insiders 1.34.0-insider (7a07992127a6ff176f0ed073d0698d81d09fc4bb, 2019-04-11T05:20:32.584Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
latex-preview|ajs|0.5.1
vscode-django|bat|0.19.0
jupyter|don|1.1.5
python-extension-pack|don|1.4.0
code-runner|for|0.9.8
latex-workshop|Jam|6.3.0
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.2-insiders
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.1.5
jinja|who|0.0.8

</details>

**Comment by DHowett-MSFT** [comment]
For what it's worth, we cannot reproduce this on the Terminal team. Neither VSCode nor another ConPTY consumer we use for testing recapitulates this behavior.

**Comment by Tyriar** [comment]
@DHowett-MSFT this one's already fixed, it was caused because ECH wasn't flagging lines to be re-rendered. Has been a bug for years going back to [term.js](https://github.com/chjj/term.js/) but only conpty emits it enough to make the bug obvious https://github.com/microsoft/vscode/issues/72708

**Comment by DHowett-MSFT** [comment]
Thanks for the heads up!
