### ISSUE TITLE
"Change All Occurrences" could be limited to the variable's scope

### ISSUE THREAD

**Issue by jamespacileo** [Microsoft/vscode#7213]
- VSCode Version: 1.2.0 Insider

This may just be an opinion, but would appreciate if you could consider this feature.

The "Change All Occurrences" currently works as a simple find and replace, 
it would help workflow if a similar option existed for only changing variables with same name and scope.

Thanks for the great software. 👍

**Comment by Spown** [comment]
this would be a highly language specific feature... Don't think it will be ever fully possible.

**Comment by jrieken** [comment]
There is the `rename` feature which does what you are asking for. Today there is rename for quite a few languages like TypeScript, JavaScript, Go, C# etc. Best is to file a request against the language extension you are using

**Comment by jamespacileo** [comment]
thanks @jrieken 👍
