### ISSUE TITLE
Upgrade of Windows 10 Seems to break VS Code & Git integration

### ISSUE THREAD

**Issue by robinsparky** [Microsoft/vscode#72137]
Issue Type: <b>Bug</b>

fatal: Not a git repository (or any of the parent directories): .git
Update to latest Windows 10.
Open VS Code. 
Open recent folder. 
Notice that Git integration is not working. i.e. doe VS Code does not recognize repo and does not display file changes.

VS Code version: Code - Insiders 1.34.0-insider (d234937aedcbc265d2272ba5861125293239f9c7, 2019-04-05T05:18:43.251Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-apache|mrm|1.2.0
language-gettext|mro|0.1.1
mssql|ms-|1.5.0
python|ms-|2019.3.6558
powershell|ms-|1.12.0

</details>

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show?

**Comment by robinsparky** [comment]
Hi,

GIT output said there was no such repository as ".git". However there was
another windows update 2 days ago and it fixed the problem.

VS Code interface with GIT seems to be working now.

Robin
