### ISSUE TITLE
Word based navigation behaves unpredictable

### ISSUE THREAD

**Issue by Therealskythe** [Microsoft/vscode#72131]
Issue Type: <b>Feature Request</b>

Why does the cursor jump **into** the next block of text instead of **before the start of it** when I hit Ctrl + Right? It lands at a completely arbitrary position and makes me waste time navigating to the beginning or end of the block **every time**. `<div class="">` does _not_ start after "div"!

Why does VSC never paste lines of code the way i copy them, keeping the indentation intact? The auto-indentation of VSC is completely broken - I dont think it has **ever** correctly indented a single line to the surrounding code so please **just paste code and indentation the way i copied it**!

Feel free to ignore. We're wasting so much time on these issues now, I needed to vent.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
Auto indentation can be disabled in the settings

**Comment by aeschli** [comment]
Can you add a small code snippet to illustrate the word based navigation issue? Please also describe what would be the expected behaviour.
