### ISSUE TITLE
Environment variables expand to empty strings in tasks.json

### ISSUE THREAD

**Issue by doxxx** [Microsoft/vscode#72135]
Issue Type: <b>Bug</b>

1. Define a task that uses `${env:FOO}` syntax to reference an existing environment variable.
2. Execute that task.
3. Observe that the expansion for that variable is an empty string.

The integrated terminal shows the expected env variable, so it's just the tasks.json that's affected (maybe other parts of VS Code too).

Does this issue occur when all extensions are disabled?: Yes (I checked this by creating a new Explorer shortcut to VS Code, with the disable option added to the commandline)

<details>
<summary>Example tasks.json</summary>

```json
{
    "label": "loader: clean build",
    "type": "shell",
    "command": "./build.sh",
    "options": {
        "cwd": "${workspaceRoot}/projects/loader"
    },
    "windows": {
        "command": "${env:CYGWIN}/bin/bash.exe",
        "args": [
            "-c",
            "source /etc/profile; source $HOME/.profile; ./build.sh"
        ],
        "options": {
            "env": {
                "CHERE_INVOKING": "1"
            }
        }
    },
    "problemMatcher": [
        "$gcc"
    ]
}
```

</details>

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (24.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
scratchpad|awe|0.1.0
spellright|ban|3.0.38
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
systemd-unit-file|coo|1.0.3
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.0
vscode-npm-script|eg2|0.3.5
vscode-pull-request-github|Git|0.6.0
nsis|idl|3.16.1
vscode-react-typescript|inf|1.1.0
intellij-idea-keybindings|k--|0.2.31
vscode-azureappservice|ms-|0.13.0
vscode-cosmosdb|ms-|0.10.1
python|ms-|2019.3.6558
azure-account|ms-|0.8.1
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
Go|ms-|0.9.2
powershell-preview|ms-|2.0.1
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
typescript-hero|rbb|3.0.0
java|red|0.42.1
windbg-debug|rez|0.3.4
rust|rus|0.6.1
vscode-zipexplorer|sle|0.3.1
rewrap|stk|1.9.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-icons|vsc|8.5.0
debug|web|0.23.1
jinja|who|0.0.8

</details>

**Comment by doxxx** [comment]
After some further investigation, I realize the problem is a little more fundamental than I initially thought, hence the major edit above.

**Comment by doxxx** [comment]
This was working some weeks ago, so I think it's a regression.

**Comment by David-Else** [comment]
Fixed I think https://github.com/Microsoft/vscode/issues/72029

**Comment by doxxx** [comment]
Ah, dang it. I searched but I didn't find that one. Thanks!
