### ISSUE TITLE
Format-on-save sometimes moves cursor/selection to end of file

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#72138]
It seems like this has come up a few times before but was supposed to be fixed (see https://github.com/Microsoft/vscode/issues/47382#issuecomment-379818652).

The issue is formatting Dart. We return a single large edit when formatting the document, and VS Code computes minimal edits so that it can preserve the cursor location (see https://github.com/Microsoft/vscode/issues/10133).

However, in this instance we're seeing the cursor jump to the end of the file when formatting *on save*, but not when just formatting the document. I'm testing with a large document, because some changes to it seem to stop this happening - though I haven't tracked down a specific change.

Here is a video that shows me making a change (adding an extra newline that will be removed), then invoking Format Document, and it works fine. I then re-add the same extra newline, then Save, and the cursor jumps to the end of the file.

The Dart formatter returns a `TextEdit` as a format provider, it does not apply any workspace changes itself.

![format](https://user-images.githubusercontent.com/1078012/55964508-bedeb300-5c6c-11e9-97e1-a9b6f1eda6b1.gif)

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by DanTup** [comment]
This appears to be fixed in the patch release.
