### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'showMessage' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#72147]
Issue Id: <b>31cb9ba0-a857-b8c8-da42-353d73f31544</b><br /><br />*Versions* <br />- 1.33.0<br />-  4d1cb56a5b88248b1e0f38b9980f4a1bc8a6fb1a<br />-  4039ea871879ef8f654f27df5c32d209104b3a44<br />-  de81ccf04849309f843db21130c806a5783678f7<br />-  f5044f0910e4aa7e7e06cb509781f3d56e729959<br />-  0ac111466ec925fd5ca180ab9893f51531e419b2<br />-  627c7f730a776ef6efb8762e9379b8c7e71e417b<br />-  2e6db8d955046349a941ab814183cf480b0e274b<br />*Stack* <br />TypeError: Cannot read property 'showMessage' of undefined<br />[/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#95:24](https://github.com/microsoft/vscode/blob/0dd516dd412d42323fc3464531b1c715d51c4c1a/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L95:24)<br />    at MouseZone.tooltipCallback (/node_modules.asar/vscode-xterm/lib/Linkifier.js:188:25)<br />    at MouseZoneManager._onTooltip (/node_modules.asar/vscode-xterm/lib/ui/MouseZoneManager.js:117:18)<br />    at /node_modules.asar/vscode-xterm/lib/ui/MouseZoneManager.js:111:70<br />

**Comment by Tyriar** [comment]
Fixed in 67cd0b1969ab6426ab257d12a255f8ea2a42eea2
