### ISSUE TITLE
Title Case Command

### ISSUE THREAD

**Issue by fingerskier** [Microsoft/vscode#72143]
I would like a 'Title Case' command that capitalizes the first letter of each word in a selected string.

e.g.:  the quick, sleek ninny-muggins.

Title Case command would alter to this:

The Quick, Sleek Ninny-Muggins.

Leaving punctuation and spaces as-is.

**Comment by alexwhitman** [comment]
The `change-case` extension will do just that. https://github.com/wmaurer/vscode-change-case

**Comment by jmbockhorst** [comment]
This feature has been added already (#70990) and should come in the April update. Also related to #70858.

**Comment by aeschli** [comment]
duplicate of #70990
