### ISSUE TITLE
Integrated terminal with gitbash no output with yarn run

### ISSUE THREAD

**Issue by Murbal** [Microsoft/vscode#72145]
- VSCode Version: Latest
- OS Version: Windows 10 64bit

Steps to Reproduce:
Install git version 2.21.0
Install yarn 1.13.0
Set default integrated terminal to git bash
Run a yarn script with yarn run <script>
See no output only some blank lines

Tried insiders build too, still doesn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
