### ISSUE TITLE
Add icons to top level view/title for custom activitybar view

### ISSUE THREAD

**Issue by ewanharris** [Microsoft/vscode#72141]
My extension contributes an activity pane which (currently) has a single view. So all the contributions in `view/title` go to the top level of the view (see first image)

![First image with single view](https://i.imgur.com/1HEc6LD.jpg)

I'm currently adding a second view to my pane, and it seems I can't place the initial icons in the same location as when I only contribute one view?

![Second images with two views](https://i.imgur.com/TVc3chv.jpg)

I tried to search stackoverflow and existing issues but couldn't find any references as to how to achieve this, and any existing packages I know that contribute an activity pane with multiple views do not seem to use the design I wish to achieve. Apologies if this is a dupe! 🙂

**Comment by sandy081** [comment]
@ewanharris Icons you contribute are for views and hence they are shown in the title bar of the views. And you contribute views to view containers. May I know your use case to show icons in view container title?
