### ISSUE TITLE
Hover pop-up sidebar option in zen mode, plus centre content properly with sidebar open in zen mode

### ISSUE THREAD

**Issue by lewislepton** [Microsoft/vscode#72142]
I searched for something like this. but would think it would be nice features to have.

but in zen mode. it would be great that if you hit a certain threshold on where the sidebar is located, then it can fade in & out whether or not you are in that threshold.
allowing you to have a nice work flow without the sidebar still at the side all the time.
so once you have opened the file you need & come away from the sidebar, it fades away. hiding it

also as well. in zen mode. when you do access the sidebar, could the content [the code/markdown] stay in the center. once the sidebar is open, it shifts the code a little bit. making it not centre.

<img width="1680" alt="Screenshot 2019-04-11 at 15 48 20" src="https://user-images.githubusercontent.com/11299322/55967221-cd7b9900-5c71-11e9-92d5-7059c9eb4e01.png">
<img width="1680" alt="Screenshot 2019-04-11 at 15 48 27" src="https://user-images.githubusercontent.com/11299322/55967227-d0768980-5c71-11e9-9d9d-6a3250bfe182.png">

**Comment by isidorn** [comment]
The last part of your comment is dup of https://github.com/Microsoft/vscode/issues/60900
The first part of your comment to auto hide side when it passes the trashhold we already have. Not sure what you are missing there. Maybe you want the auto hide of sidebar which also has a feature request for it.
Bottom line -> duplicate
