### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'replaceCells' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#72148]
Issue Id: <b>4b69b724-b37f-bb2f-e560-074018d6c3e3</b><br /><br />*Versions* <br />- 1.34.0-insider (4/8/2019 5:18:29 AM)<br />-  0dd516dd412d42323fc3464531b1c715d51c4c1a<br />-  4d1cb56a5b88248b1e0f38b9980f4a1bc8a6fb1a<br />-  0ac111466ec925fd5ca180ab9893f51531e419b2<br />-  2e6db8d955046349a941ab814183cf480b0e274b<br />-  4039ea871879ef8f654f27df5c32d209104b3a44<br />-  1876bd1d3805d632a9aa78fad47b2c3c555f6eec<br />-  3bd60b2ba753e7fe39b42f99184bc6c5881d3551<br />-  56f1b4795fed05677eb82a21dac4fc1ab62d747b<br />-  5688d00dd592a165530a82945c4ade4dad6b01e7<br />-  b9bcca2b9830df592892d63201704026c18dcbe5<br />-  627c7f730a776ef6efb8762e9379b8c7e71e417b<br />-  b5f5db349f211f5045e7dad6fd1672010d2d00de<br />-  de81ccf04849309f843db21130c806a5783678f7<br />-  d234937aedcbc265d2272ba5861125293239f9c7<br />-  f5044f0910e4aa7e7e06cb509781f3d56e729959<br />-  1afeb46cc4f2856ed6d0759fff85b13647c7ab83<br />*Stack* <br />TypeError: Cannot read property 'replaceCells' of undefined<br />    at InputHandler._eraseInBufferLine (/node_modules.asar/vscode-xterm/lib/InputHandler.js:435:14)<br />    at InputHandler.eraseInLine (/node_modules.asar/vscode-xterm/lib/InputHandler.js:489:22)<br />    at Array.<anonymous> (/node_modules.asar/vscode-xterm/lib/InputHandler.js:96:84)<br />    at EscapeSequenceParser.parse (/node_modules.asar/vscode-xterm/lib/EscapeSequenceParser.js:402:40)<br />    at InputHandler.parse (/node_modules.asar/vscode-xterm/lib/InputHandler.js:191:22)<br />    at Terminal._innerWrite (/node_modules.asar/vscode-xterm/lib/Terminal.js:893:32)<br />    at /node_modules.asar/vscode-xterm/lib/Terminal.js:873:23<br />

**Comment by Tyriar** [comment]
Should be fixed in https://github.com/Microsoft/vscode/issues/69603
