### ISSUE TITLE
Launching from the command line fails when the file path has a space in it

### ISSUE THREAD

**Issue by TexAgg** [Microsoft/vscode#7214]
- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:

1. In the windows command line, in a folder with a space somewhere in its file path
(like `C:\Users\me\My Website`), 
try to open VSCode using the batch command `code %cd%`.
2. A new instance of VSCode will open up with two new documents, one called "My" and one called "Website", or however many spaces were in the filepath.

**Comment by Spown** [comment]
did you try ``code "%cd%"``?

**Comment by TexAgg** [comment]
oh yeah nevermind that worked
