### ISSUE TITLE
horizontal scrollbar shows up very often in debug hovers

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#72144]
From @eamodio 

The horizontal scrollbar shows up very often in debug hovers for me, so this isn't a rarity.

Also, not sure if this is 100% related, but if not, let me know and I can open another issue. But sometimes the debug hovers open slightly too small for the content so you get unneeded scrollbars... and then often it ends scrolled to the end, rather than the start:

![image](https://user-images.githubusercontent.com/641685/55690487-72d7f980-5960-11e9-97df-809f2b380f43.png)

In that image, I didn't touch/scroll the hover, it opened that way (seemingly scrolled to the end, rather than the start). But in this case there is no need for a vertical a scrollbar there at all.

My guess is that this only happens on machines with visible scrollbars by default (Windows, macOS if you turn off the autohide scrollbars) and the content is just slightly too big for the hover.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/67620
