### ISSUE TITLE
Complete freeze after terminal close, Windows

### ISSUE THREAD

**Issue by JakubBlaha** [Microsoft/vscode#72140]
The app completely freezes after closing the integrated terminal. I am using VS Code to only develop python scripts, so I can't really say whether it's because the python extension or not. I wanna point out that I use the terminal only to run a python script, so maybe it's related to the python extension. This behavior occurs rarely, however I then have to kill the app through the Task Manager.

- VSCode Version: 1.33.0
- OS Version: Windows 10, build 18362.53

**Steps to Reproduce:**

*Note that this is hard, if not impossible, to reproduce since it seems to happen almost randomly. That's also the reason why I can't answer whether the issue persists after disabling the extensions.*

1. Open the terminal
2. Run a python script
3. Try to close the terminal (using the *bin* button)

**Comment by Tyriar** [comment]
Can you []follow these steps to capture the native crash](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#windows) and create a new issue? Unfortunately without logs we can't diagnose this.
