### ISSUE TITLE
"window.openFoldersInNewWindow" - feature request for another option/behavior

### ISSUE THREAD

**Issue by drewda** [microsoft/vscode#72150]
I'd like to have an option for `window.openFoldersInNewWindow` that produces the following behavior:

- when in a window with no open tabs, an open action will replace the existing window (the "default"/"off" behavior)
- when in a window with one or more open tabs (for example, an open editor tab), an open action (for example, `File > Open Recent > [another workspace]`) will open a new window (the "on" behavior)

I've experimented with settings and do not see a way to get this combination currently. I've also searched issues and have not found a similar feature request. Of course, I may have missed something -- would appreciate pointers to how this can be done or to other existing issues!

**Comment by gnowland** [comment]
I would also like to see a "hybrid" option like this added, where if there are already folders or files open in the workspace the `File > Open` behavior opens the folder in a new window, and if it is an empty workspace (e.g. only "Welcome" tab is shown, no files or folders in the explorer) the `File > Open` behavior replaces the current (empty) workspace.

I've also been experimenting with settings and do not see a way to get this combination, and have searched issues and this feature request seemed to be the closest "in spirit", but I may have just as easily missed something and would appreciate pointers to how this can be done or to other existing issues or if this is fundamentally different and should open a new issue... Thanks!
