### ISSUE TITLE
renaming symbol not working

### ISSUE THREAD

**Issue by BBI-DiWang** [Microsoft/vscode#72154]
Issue Type: <b>Bug</b>

F2 and  "find all references" stopped working.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.68GB (24.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.3.6558
mel|sat|0.1.2

</details>

**Comment by aeschli** [comment]
@BBI-DiWang For what language? Can you add a small code sample?

**Comment by BBI-DiWang** [comment]
python. renaming symbols does not work either. I have posted the problem [here](https://github.com/Microsoft/vscode-python/issues/52#issuecomment-482328577) as well:

[Imgur](https://i.imgur.com/h1oTj1O.gifv)

I bypass this issue by adding:
"python.jediEnabled": true
in the setting.json

**Comment by aeschli** [comment]
Please file this issue against the python extension: https://github.com/Microsoft/vscode-python
