### ISSUE TITLE
GitHub PR extension make reference window focus in the inner editor

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#72158]
Version: 1.34.0-insider
Commit: efa47d77cfd55cbad68bef54a2d765b73d7beb13
Date: 2019-04-03T20:23:50.493Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

---

When disabling GitHub PR extension and is in a PR branch, find references:

![ref1](https://user-images.githubusercontent.com/4033249/55981401-719e1980-5c4b-11e9-96a7-fb1ec43875e4.gif)

When enabling GitHub PR extension and is in a PR branch, find references don't focus in the references section but the inner editor section.

![ref2](https://user-images.githubusercontent.com/4033249/55981615-f4bf6f80-5c4b-11e9-8dce-a91952db2778.gif)

**Comment by octref** [comment]
Not sure if this is specific to GH PR extension or any comment providers, so opening issues here.

**Comment by rebornix** [comment]
I'll take a look, it breaks keyboard navigation.

**Comment by rebornix** [comment]
@octref can you still reproduce this issue in latest Insiders? I can no longer reproduce this issue anymore.

**Comment by octref** [comment]
Version: 1.34.0-insider
Commit: b7c5e104a44b65e937408a10cbb8b49d6dfd19bf
Date: 2019-04-12T11:12:09.412Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

I can still repro it.
