### ISSUE TITLE
performance regression: loading -> hint -> loading -> hint infinite loop

### ISSUE THREAD

**Issue by matt-erhart** [Microsoft/vscode#72153]
- VSCode Version: newest non-insiders
- OS Version: windows 10

Steps to Reproduce:

1. hover anything with a hint
2. nearly all typscript features are slower in editor

Also note that loading... is taking longer now.

Does this issue occur when all extensions are disabled?: Yes

![kk2qsYQ5pp](https://user-images.githubusercontent.com/3199847/55976536-6ba33b00-5c41-11e9-8b63-f49d09c7e84d.gif)

In the gif I show ~3 vscode loops, not just the gif looping. 

I've used vscode for a few years now and this is the biggest and most wide spread perf regression I've seen, so I'm sure you're all on it. Hopefully this might give some clues as to what's going on.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Closing as not enough information to investigate this
