### ISSUE TITLE
Terminal as tab

### ISSUE THREAD

**Issue by zhakhalov** [Microsoft/vscode#7215]
Hi
It would be great to have ability to open terminal as code editing tab. Or to be able to open several terminals (actually only one open terminal it is rare case ;) )

**Comment by Tyriar** [comment]
Multiple terminals is planned for the June release https://github.com/Microsoft/vscode/issues/6458

I don't see terminals being made as actual tabs due to the way that vscode is, full screening or making panels more convenient to expand is definitely an option in the future though.
