### ISSUE TITLE
Finalize Webview port mapping api

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#72152]
Tracks finalizing the webview port mapping API proposed in #70851

**Comment by jrieken** [comment]
How about names: `webviewPort` and `extensionHostPort`? That would name them according to the places at which the ports are being listened on

**Comment by Chuxel** [comment]
@jrieken @mjbvz I like the proposal, but I'd rather not change the names if we can help it given uptake by extension authors to date.  Could we support both sets for backwards compatibility?

**Comment by mjbvz** [comment]
We're going to change  the names to what @jrieken suggests but keep compatibility with the existing names for an iteration
