### ISSUE TITLE
Aba igual a do Google Chrome

### ISSUE THREAD

**Issue by soaresrodrigo** [Microsoft/vscode#72151]
Poderia criar uma transição de abas, estilo o do Google chrome, é muito mais prático, desde já grato, parabéns aos desenvolvedores.

**Comment by aeschli** [comment]
Automated translation:

Could create a tab transition, Google chrome style, is much more practical, grateful already, congratulations to the developers.

**Comment by bpasero** [comment]
@soaresrodrigo can you explain in english?
