### ISSUE TITLE
Inconsistent behavior with NVDA screen reader in WebViews

### ISSUE THREAD

**Issue by RussellSprouts** [microsoft/vscode#72156]
- VSCode Version: 1.33.0 and 1.34.0-insiders (7a0799212)
- OS Version: Windows 10.0.17763 Build 17763

Steps to Reproduce:

1. Launch VSCode with the NVDA screen reader active
2. Move mouse around to elements in a webview, like the release notes page. Sometimes the reader will read text when hovered over it, and then it will stop. Sometimes the first few paragraphs of a screen will work but the rest will not.

Our [VSCode extension](https://marketplace.visualstudio.com/itemdetails?itemName=ms-databasemigration.data-access-migration-toolkit) creates a report in a WebView. We are working with our accessibility team to test that it works with a screen reader. They aren't able to confirm because the screen reader is working inconsistently.

Our WebView is a simple document. The only interactivity is a simple expander that toggles the max-height on some elements.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RussellSprouts** [comment]
Any update on this? Our accessibility certification is blocked by this issue.

Thanks

**Comment by RussellSprouts** [comment]
Browsing other issues, the symptoms seem similar to https://github.com/Microsoft/vscode/issues/67374

**Comment by rbenson** [comment]
Screen readers use the cursor to navigate/read. NVDA has some functionality to read text under the mouse pointer. I work in accessibility professionally, and would never require a test like you describe, and would not base my decision if something is accessible on that alone. 

I would test it with using the keyboard hotkeys. If it stopped reading that way, then that might be a bug. Before filing a bug, I would recreate the thing I am testing in HTML, and see what happens. If it reads correctly in a browser, then I'd know it  was a bug in Code or maybe electron.

**Comment by Neurrone** [comment]
If you can provide steps to repro, I can try to see if I experience it. 

But as said earlier, this functionality is very infrequently used by screen reader users, so it is possible that there is a bug in NVDA.

**Comment by RussellSprouts** [comment]
Thanks,

I will work with our accessibility team to clarify the issues we're seeing, and determine if it's an issue with our code, or VSCode.

**Comment by isidorn** [comment]
@RussellSprouts Please try to use vscode insiders https://code.visualstudio.com/insiders/ which uses latest electron and let us know if you still experience the issue. if yes please provide steps
