### ISSUE TITLE
Баг во время обновления

### ISSUE THREAD

**Issue by ISM1491** [Microsoft/vscode#72163]
Issue Type: <b>Bug</b>

VS Code не актуальной версии
Появляется окошко с инфой что есть доступное обновление
Нажимаем установить
Просит перезапустить VS Code чтобы применить обновление
Нажимаем позже
Происходит перезагрузка машины
VS Code пропал, ярлыки никуда не ведут
По всей видимости старый редактор удаляется но остается в памяти до того момента пока его не закрыть, после закрытия из папки с обновленным редактором извлекается все в корень, и ярлыки указывают куда надо

После перезагрузки машины нашел обновленный редактор в  ..\Microsoft VS Code\_

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
gitlens|eam|9.6.0
prettier-vscode|esb|1.8.1
vscode-language-pack-ru|MS-|1.33.2
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by aeschli** [comment]
Automated Translation:

VS Code is not the current version
A window appears with the info that there is an available update.
Click install
Requests to restart VS Code to apply the update.
Push later
Machine restart occurs
VS Code is gone, shortcuts do not lead anywhere
Apparently, the old editor is deleted but remains in memory until it is closed, after closing everything is removed from the folder with the updated editor, and the shortcuts indicate where

After rebooting the machine, I found the updated editor in .. \ Microsoft VS Code_

**Comment by joaomoreno** [comment]
Please fully reinstall VS Code.
