### ISSUE TITLE
Source Control tab horizontal divider (changes panel) no longer adjustable

### ISSUE THREAD

**Issue by leakyshoe** [Microsoft/vscode#72161]
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: macOS 10.14.4

Source Control tab horizontal divider (changes panel) no longer adjustable as it was in February

Steps to Reproduce:

1. Open a git repository with lots of git submodules
2. Open the Source Control tab and select the parent repository
3. Notice that the horizontal divider is fixed and cannot be adjusted vertically in order to display more of the submodules in the upper area

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The SCM Repositories panel now automatically resizes itself, just like the Open Editors panel. If you'd like to manually resize it, set `scm.providers.visible` to `0`.

**Comment by leakyshoe** [comment]
Thanks. In that case the auto resize does not work as well as it could because when there are several submodules in the upper area and no changes in the lower area many of the submodules are obscured and scrolling is necessary.
