### ISSUE TITLE
python syntax highlighting with typing

### ISSUE THREAD

**Issue by michaelcapizzi** [Microsoft/vscode#72165]
- VSCode Version: 1.33.0
- OS Version: Windows 10

This is an issue with syntax highlighting that occurs when trying to use a return type in my `python` method.

```
def create_odbc_connection(
        database: str,
        user: str,
        password: str
    ) -> pyodc.Cursor:
    """
    Creates ODBC connection.

    NOTE: may require driver installation: 
            https://www.microsoft.com/en-us/download/details.aspx?id=56567
            https://www.microsoft.com/en-us/download/details.aspx?id=48742
    
    Args:
        database (str): Name of the customer database to query
        user (str): ActiveDirectory email
        password (str): ActiveDirectory password
    
    Returns:
        pyodbc.Cursor: <Cursor> instance that can now execute a query
    """
    # set variables
    driver = "{ODBC Driver 17 for SQL Server}"
```

The presence of `-> pyodc.Cursor` before the `:` seems to throw off the highlighter, and my docstring is not highlighted correctly as well as the actual code.

Two notes:

1. if I do *not* include the return type (*i.e.* exclude `-> pyodc.Cursor`), the highlighting is correct.
2. if I do *not* include a docstring at all, the highlighting is correct.

**Comment by alexr00** [comment]
@michaelcapizzi thanks for the copy/pastable example. Can you provide some screen shots of what you're seeing? 
This is what I see:
![image](https://user-images.githubusercontent.com/38270282/56024300-036f5a80-5d10-11e9-8704-62ba6a5c58ef.png)
It looks ok to me. The docstring is tokenized as a `string.quoted.docstring.multi.python` which also looks correct.

**Comment by msftrncs** [comment]
@michaelcapizzi, are you referring to the 'DATA:' in the docstring being highlighted as a  'codetag.notation'?   Or the fact that 'pyodc.Cursor' does not receive any specific scope?

**Comment by michaelcapizzi** [comment]
Thanks @alexr00  and @msftrncs for such quick replies.

It turns out that I had competing `python` extensions that were causing problems.  When I removed the non-microsoft-supported extension, everything worked great!

I'm closing this issue.
