### ISSUE TITLE
Memory Leak - Python Language Server

### ISSUE THREAD

**Issue by warvolin** [Microsoft/vscode#72166]
Issue Type: <b>Performance Issue</b>

I have 1 python file open with around 140 lines of code, and 2 .yaml files open. I walked away for lunch and the Python Language Server was using 11+ GB of ram when I returned. After shutting it down completely, and reopening the one file and VS Code, the usage of Microsoft.Python.LanguageServer has risen from 40MB to 200MB in a matter of minutes of doing absolutely nothing. There is definitely a memory leak happening somewhere.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (4.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	    98	 84918	code main
    1	    82	 84919	   gpu-process
    0	   262	 84920	   window (~/git/python-dev/cli_python/geojson-merge.py)
    0	   360	 84994	     extensionHost
    0	    49	 84999	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=84994
    0	    49	 85001	       electron_node server.js 
    0	    33	 85037	       electron_node server.js 
   58	   229	 85223	       /Users/bcoates/.vscode/extensions/ms-python.python-2019.3.6558/languageServer.0.2.47/Microsoft.Python.LanguageServer
    0	    98	 84995	   shared-process
    1	    82	 85372	   window (Issue Reporter)
    0	     0	 85412	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
project-manager|ale|10.5.1
vscode-database|baj|2.1.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.6.0
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
json-tools|eri|1.0.2
prettier-vscode|esb|1.8.1
font-switcher|eva|3.0.0
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.126
beautify|Hoo|1.4.11
compareit|in4|0.0.2
diff-tool|jin|0.0.1
hive-sql|jos|0.0.4
vscode-map-preview|jum|0.4.8
MagicPython|mag|1.1.0
rainbow-csv|mec|1.0.0
mssql|ms-|1.5.0
python|ms-|2019.3.6558
sublime-keybindings|ms-|4.0.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
vscode-css-peek|pra|2.2.0
vscode-fileutils|sle|2.13.5
guides|spy|0.9.3
autoimport|ste|1.5.3
python|tht|0.2.3
highlight-matching-tag|vin|0.9.1
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.5.0
vscode-react-native|vsm|0.9.1
jinja|who|0.0.8
markdown-all-in-one|yzh|2.2.0

(12 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Please file this against the python extension: https://github.com/Microsoft/vscode-python/issues
