### ISSUE TITLE
Extension Host Terminated

### ISSUE THREAD

**Issue by JulioSarmiento** [Microsoft/vscode#72167]
Issue Type: <b>Bug</b>

I recently started receiving the Extension Host Terminated error (_onExtensionHostCrashed @ extensionService.ts:450). I removed all the extensions and still received the error. I uninstalled and deleted all related folders and reinstalled VSCode and still get this error.

Now I do not know what to do.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (10.00GB free)|
|Process Argv|--open-url -- vscode://vscode.git/clone?url=https://ryder-vsts.visualstudio.com/SFDC/_git/sfdc|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aeschli** [comment]
Can you see if there's information in any of the logs (View > Output > ...) and run with `--verbose`.

**Comment by JulioSarmiento** [comment]
I do not see any logs. Should I be looking in a particular place?

**Comment by aeschli** [comment]
From the global menu, invoke `View > Output`, then in the output view check the output logs
![image](https://user-images.githubusercontent.com/6461412/56124197-619d7700-5f76-11e9-990c-6096892330c9.png)

**Comment by jrieken** [comment]
closing because this issue is without actionable information
