### ISSUE TITLE
Color emoji support

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#7216]
It seems, at least on Windows, VS code does not show emoji characters in color even with fonts like "Segoe UI Emoji".
Is this just a mis-configuration? Or, if not supported, do you have any plan to support color emoji?

I'm on:
1.2.0-insider
7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f

**Comment by alexandrudima** [comment]
We delegate all text rendering to Chromium, so Chromium ultimately decides how to render the text. Can you please share what characters you use, how you configure the font, and what you'd expect to see vs what you end up seeing? Do other text editors display these characters in color?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.

**Comment by DBaker2** [comment]
c

**Comment by espresso3389** [comment]
We can just type 🍺 on the web. Why not on the text editor?

The problem is; even with the following font configuration, VSCode does not assign the correct font to emoji characters:

```json
"editor.fontFamily": "Consolas, Segoe UI Emoji,Meiryo"
```

It does not seem to be an issue on Chromium but just an issue on VSCode structure.

**Comment by alexandrudima** [comment]
@espresso3389 This actually seems to work as you'd wish to in our insiders version (where we have adopted Chromium 53). I'm thinking you've tested on a version of Chromium >= 53.

### Stable (Chromium 52)
![stable-beer](https://cloud.githubusercontent.com/assets/5047891/20759517/69e34cae-b71d-11e6-9da8-ba9d2273a38b.gif)

### Insiders (Chromium 53)
![insider-beer](https://cloud.githubusercontent.com/assets/5047891/20759572/8b8adf5c-b71d-11e6-906b-4ac30f709e52.gif)

**Comment by espresso3389** [comment]
Yes, I've already noticed the change.
Thanks!
