### ISSUE TITLE
Separate workspaces from directories in Open Recent menu

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#72164]
From a UX and user workflow point of view, it seems to me that it would make sense to list workspaces separately from stand-alone folders in the File→Open Recent menu, similar to how folders & workspaces are currently separated from files.

**Comment by bpasero** [comment]
I am closing this as wontfix because the list of recently opened workspaces/folders is something I very often use to switch to the previous workspace/folder I had opened. If now these 2 are split apart, I loose that functionality.

**Comment by mgabeler-lee-6rs** [comment]
Two comments:
1. Closing an issue because _you personally_ don't find it useful is a strange choice to make for an open source project with such a large user base
2. I don't see how putting a divider in the menu to clearly separate workspaces from files removes functionality for you.  I was not suggest removing either one from the menu, only that it would be more useful to _group_ each set together, since the case of "I want to go to a different workspace" is a rather different use case from "I want to go back to this file"
