### ISSUE TITLE
activeTextEditor or document.fileName loses its context

### ISSUE THREAD

**Issue by KyleEggleston63** [Microsoft/vscode#72162]
Issue Type: <b>Bug</b>

My extension is not working after 1.33 update.  I wrote the Language iRite extension.  The issue is with this code: 
<code>let textEditor = vscode.window.activeTextEditor;</code>
<code>iRiteChannel.appendLine("Building: " + textEditor.document.fileName);</code>

The first time through the channel displays the correct path to the active file trying to compile i.e. C:\AACode\program1\src\myProgram.src.  Every time after that it displays extension-output-#2 with no path.  

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.84GB free)|
|Process Argv|--folder-uri file:///c%3A/AACode/vscode_irite/src|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
Bookmarks|ale|10.4.3
lit-html|bie|1.11.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.18.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.28
vue-peek|dar|1.0.2
jshint|dba|0.10.20
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.8.1
vue-inline-template|fai|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
todo-tree|Gru|0.0.126
vscode-mocha-test-adapter|hbe|1.8.1
vscode-test-explorer|hbe|2.9.2
canvas-snippets|hol|0.3.2
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
easy-icons|jam|0.3.1
vscode-codemetrics|kis|1.18.0
node-module-intellisense|lei|1.5.0
quickstart|lol|0.1.0
vscode-language-babel|mgm|0.0.22
code-beautifier|mic|2.2.1
easy-less|mrc|1.4.5
cpptools|ms-|0.22.1
vsliveshare|ms-|1.0.45
debugger-for-chrome|msj|4.11.3
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.18.1
irite|RLW|2.5.1
vscode-javascript-booster|sbu|0.10.2
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.6.0
indenticator|Sir|0.6.0
es6-mocha-snippets|spo|0.2.2
vscode-status-bar-format-toggle|tom|1.5.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
bootstrap-v4-snippets|Zac|0.2.1

(19 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
The output channel itself is also an editor and what you are seeing is the "path" of that

**Comment by KyleEggleston63** [comment]
Ok but my extension no longer works and it did all the way up until 1.33.  So something changed, which is fine, but can you please tell me how to fix it then?

**Comment by jrieken** [comment]
> So something changed, which is fine, but can you please tell me how to fix it then

Pretty sure that behaviour didn't change, it's like that since the first release. Not sure what your problem is and what path you expect

**Comment by KyleEggleston63** [comment]
The problem is this: 
let textEditor = vscode.window.activeTextEditor;
textEditor.document.fileName would return C:\AACode\program1\src\myProgram.src.  I would then pass that to the compile command.  vscode.window.activeTextEditor.document.fileName always returned C:\AACode\program1\src\myProgram.src.  Now it does not.  Now it will return C:\AACode\program1\src\myProgram.src one time and then it returns the extension-output-#2 or whatever.  This extension has existed in some form for a few years and this has always worked.  Anyway, how do I select the open .src file as the active file and then get the path to that active file since this no longer works?

**Comment by KyleEggleston63** [comment]
Here is the rest of the method up to that point: 
vscode.commands.registerCommand("irite.build", () => {
    iRiteChannel.clear();
    vscode.workspace.saveAll().then(
      success => {
        if (success) {
          iRiteChannel.appendLine("All Files Saved");
          vscode.workspace.findFiles("*.src", "system.src", 100).then(
            result => {
              var openTextDoc;
              if (result.length > 0) {
                {
                  if(result.length > 1){
                    openTextDoc = new Promise(function (resolve, reject) {
                      resolve(vscode.window.activeTextEditor.document);
                    });

                  } else {
                    openTextDoc = vscode.workspace.openTextDocument(result[0]);
                  }

                  openTextDoc.then(srcFile => {
                    iRiteChannel.show();
                    vscode.window.showTextDocument(srcFile).then(srcEditor => {
                      checkEngineDefined().then(engineType => {
                        checkEnginePathDefined(engineType.toString()).then(engineParameters => {
                          //got engine path and compiler from config, now init active window and push to iRiteProcessor
                          //iRiteProcessor takes argument of desired .src file path
                          let enginePath: string = vscode.workspace
                            .getConfiguration("irite")
                            .get("build.enginePath", "");
                          let compilerPath: string = vscode.workspace
                            .getConfiguration("irite")
                            .get("build.compilerPath", "");
                          let textEditor = vscode.window.activeTextEditor;
                          iRiteChannel.appendLine("Building: " + textEditor.document.fileName);

**Comment by jrieken** [comment]
> Anyway, how do I select the open .src file as the active file and then get the path to that active file since this no longer works?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else

**Comment by KyleEggleston63** [comment]
Really?  I am aware of what an if statement is.  Never mind I'll figure it out myself.  There was no need to be rude and insulting which is all you have been here.  I had an extension.  It worked.  1.33 comes out.  It doesn't work.  Seems pretty straight forward and I just wanted some help figuring this out.  But easy to be rude and disrespectful hiding behind a keyboard.  @aeschli @jrieken
