### ISSUE TITLE
VSCode deletes itself!

### ISSUE THREAD

**Issue by chrisbennet** [Microsoft/vscode#72168]
Issue Type: <b>Bug</b>

Version 1.33.0 and possibly 1.32.2 will sponteneously delete themselves.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.52GB (23.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.22.1

</details>

**Comment by joaomoreno** [comment]
Please fully reinstall VS Code.

**Comment by chrisbennet** [comment]
Yes, I do that every time it decides to delete itself. NOT CLOSED

-Chris
