### ISSUE TITLE
Settings TOC is not expanded the first time it opens with predefined query

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#72175]
Issue Type: <b>Bug</b>

Found this issue while playing with https://github.com/Microsoft/vscode/pull/72157 and it seems that we run the search before rendering the settings editor.

VS Code version: Code - Insiders 1.34.0-insider (7a07992127a6ff176f0ed073d0698d81d09fc4bb, 2019-04-11T05:15:17.190Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_2048500|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.5.2
markdown-emoji|bie|0.0.7
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.0
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
flow-for-vscode|flo|1.1.1
vscode-pull-request-github-insiders|Git|1.101.0
ocaml|hac|0.6.43
beautify|Hoo|1.4.11
references-plusplus|jri|0.0.5
graphql-for-vscode|kum|1.13.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.12
vscode-azurefunctions|ms-|0.16.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
azure-account|ms-|0.8.1
cpptools|ms-|0.22.1
Go|ms-|0.9.2
powershell|ms-|1.12.0
vscode-typescript-tslint-plugin|ms-|1.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.45
debugger-for-chrome|msj|4.11.3
debugger-for-ios-web|msj|0.1.2
vetur|oct|0.18.1
subtitles-editor|pep|1.0.2
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
ruby|reb|0.22.3
smartpaste|reb|0.0.3
toggle|reb|0.0.1
vscode-fuzzsymbols|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.6.1
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.2
vscode-intelli-nav|vsi|0.0.6

(12 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I can't repro this anymore, based on how I remember it. Let me know if you can.
