### ISSUE TITLE
VS Code keeps losing the ability to see files in some of my folders

### ISSUE THREAD

**Issue by rfernand2** [microsoft/vscode#72174]
Issue Type: <b>Bug</b>

Just running latest version - I can see the files at my windows command line, but VS Code shows the folder as empty (I click to expand it, it opens with no entries).  I tried restarting VS Code, turning off workspace (just opening the folder).  No joy.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (22.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
printcode|nob|3.0.0
remote-vscode|raf|1.1.0
cython|tcw|0.1.0

</details>

**Comment by aeschli** [comment]
What kind of files are that folder? Can you show a screenshot? Anything special with the files or folders?

**Comment by rfernand2** [comment]
I noticed it happening on 2 of my folders.  The first folder contains just *.py files and a *.txt file.  The second folder contains *.py and a .toml file, but previously contained a VS Code workspace file.  When I found that, I deleted it and restarted VS Code but the problem remained.  As for a screenshot, the problem is not happening now, but it would just show the folder view of VS Code, with a folder icon for “open folder” with no children (for the problem folder).

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes please file exact reproducable steps.

**Comment by rfernand2** [comment]
I currently do not have a reliable way to reproduce the problem; if I find one, I’ll try it with insiders.

- Roland

**Comment by isidorn** [comment]
Thanks Roland, Let me know how it goes.

**Comment by MilesDuke-Keysight** [comment]
Something similar happens to me in VSCode 1.33.1, and has happened in the version before.

I don't have a tried-and-true set of steps to make the problem happen, but I generally keep at least 3 VScode projects open in separate windows.

When I encountered the problem:

- I can still expand most folders in my project
- The one folder I could not expand was marked with the "brown mauve" dot, and the hover-over message said "Contains emphasized items"
- The emphasized items were files modified under Git
- No other folders in my project are emphasized atm
- When restarting VScode, the folder would actually be expanded, so I am able to work normally until the problem recurs

**Comment by JoshuaSjoding** [comment]
I can reliably reproduce this in a [Go](https://github.com/microsoft/vscode-go/tree/0.10.2) project by performing `Go to Definition` (`F12`) on a symbol that exists in a different package. It opens the file preview in a new tab as expected, but it doesn't correctly expand the folder. Once this happens I can no longer expand the folder manually, even if I close the previewed file. If the folder was already expanded, the files within that folder suddenly disappear.

If I restart VS Code I can expand and collapse the folder again. Performing `Go to Definition` on a symbol defined in that folder causes it to fail again until the next program restart. Only the folder containing the definition is affected. This happens regardless of whether I have uncommitted changes in a folder.

I've encountered `folder-that-cannot-be-expanded` issues intermittently over the last several releases of VS Code while working on `Go` projects on Windows 10. This is the first time that I've reliably reproduced it. I'm running VS Code release `1.35.1` on `Windows 10 1903` with git `2.20.1.windows.1`. I have TortoiseGit `2.8.0.0` installed.

**Comment by isidorn** [comment]
A collegue of mine just showed this to me @lszomoru
I am still looking for nice reproducable steps and would really appreciate them. Thanks all!

**Comment by sergei3000** [comment]
I don't know how to reproduce this. It just happens sometimes. Have to close VS Code and reopen it to see some of my files again in the Explorer window.

**Comment by michelerota** [comment]
I solved moving the project folder to another folder and than move back to the original folder.

**Comment by ginoarpesella** [comment]
> I solved moving the project folder to another folder and than move back to the original folder.

This worked for me. Thanks

**Comment by AnassL** [comment]
This worked for me too. Thanks

**Comment by JoeEarly** [comment]
![Screenshot 2020-02-22 at 13 45 41](https://user-images.githubusercontent.com/5208459/75093437-a1ab8e00-5579-11ea-84df-2d63f0ffed80.png)

Moving folder has not fixed it for me

**Comment by ginoarpesella** [comment]
> ![Screenshot 2020-02-22 at 13 45 41](https://user-images.githubusercontent.com/5208459/75093437-a1ab8e00-5579-11ea-84df-2d63f0ffed80.png)
> 
> Moving folder has not fixed it for me

Not sure if this will help but for me, I did not move my folder back to its original spot. I know this is a workaround but it's all we have until they find and resolve the main issue.

**Comment by JoeEarly** [comment]
I moved it into `SystemStatus` then back again into its original spot, and it loaded as expected again

**Comment by motanol** [comment]
Had similar issue opening folder, deleting file inside with strange name worked for me.

**Comment by isidorn** [comment]
Nobody complained for quite some time. I would guess this got fixed.
If you still see this please let me know
