### ISSUE TITLE
Underscore renders as an empty space within integrated terminal linux mint 19.1

### ISSUE THREAD

**Issue by tberghuis** [Microsoft/vscode#72179]
Issue Type: <b>Bug</b>

steps:
open integrated terminal
type the '_' key
blank space shows

also tested running simple script with `echo _`, just output blank space

vscode running under linux mint 19.1

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3249)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.61GB (6.31GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
very-smart-select|clo|0.3.0
bracket-pair-colorizer-2|Coe|0.0.28
prettier-vscode|esb|1.8.1
python|ms-|2019.3.6558
LiveServer|rit|5.5.1

</details>

**Comment by zztalker** [comment]
If you change fontFamily or fontSize it appeared again.  
`"terminal.integrated.fontSize": 12,` is enough. 
I use this: 

    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'",
    "terminal.integrated.fontSize": 16,

**Comment by tberghuis** [comment]
Thanks that works. 
I believe it should still be fixed for the default settings
