### ISSUE TITLE
Integrated Terminal shows a weird text highliting effect

### ISSUE THREAD

**Issue by MalikBagwala** [Microsoft/vscode#72183]
![Code - 12-04-2019-228](https://user-images.githubusercontent.com/23068029/56010616-fea3aa00-5d01-11e9-9c4e-7ba92ccfcc97.png)
![Code - 12-04-2019-330](https://user-images.githubusercontent.com/23068029/56010617-fea3aa00-5d01-11e9-8529-13f377e499f5.png)

Issue Type: <b>Bug</b>

The integrated terminal shows a weird text highliting effect. I have tried re-installing vscode and changing the default shell but the problem persists

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.90GB (2.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
python|ms-|2019.3.6558
material-icon-theme|PKi|3.7.0
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1
ayu|tea|0.18.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
