### ISSUE TITLE
conda activate base bug in VsCode after update 1.33.1 

### ISSUE THREAD

**Issue by Focke-Wulf** [Microsoft/vscode#72188]
- VSCode Version:
- OS Version: MacOS 10.14.4

Steps to Reproduce:

1.  python intercepter using Anaconda 3.6.8
2. when create a new terminal 

[base env here already exist]
(base) Etar:Khanid eel$ source /Users/eel/anaconda3/bin/activate
(base) Etar:Khanid eel$ conda activate base
(base) Etar:Khanid eel$ 

However it shows below which is not conda python env

Python 2.7.10 (default, Feb 22 2019, 21:17:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

i tried in my own system terminal , it works fine.
hopefully this problem can be fixed

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
> However it shows below which is not conda python env

Can you explain what you mean for someone unfamiliar with conda?

**Comment by Focke-Wulf** [comment]
> > However it shows below which is not conda python env
> 
> Can you explain what you mean for someone unfamiliar with conda?

HI, Anaconda provide visual environment for users to switch different versions of python.
in vscode terminal it works fine with previous version.

when you set python path in vscode. vscode terminal should be expected to switch the same python version. however. the terminal doesn't make it work properly

**Comment by Focke-Wulf** [comment]
<img width="566" alt="屏幕快照 2019-04-14 上午11 30 40" src="https://user-images.githubusercontent.com/26343300/56087994-a0b1c680-5ea9-11e9-9c37-3a5a4cf85938.png">
this is how it's happend

**Comment by Tyriar** [comment]
Looks like this is related to the Python extension and could be related to https://github.com/Microsoft/vscode/issues/70248

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
