### ISSUE TITLE
Replace all sometimes doesn't replace everything

### ISSUE THREAD

**Issue by c19** [Microsoft/vscode#72184]
- VSCode Version: March 2019 (version 1.33) Update 1.33.1
- OS Version: OSX High Serria 10.13.6 (17G4015)

Steps to Reproduce:

1. alt-shift-f to find and replace
2. replace all
3. sometime it doesn't work for some lines

Does this issue occur when all extensions are disabled?: Yes

Something like this happened back in 2015
https://github.com/Microsoft/vscode/issues/331

**Comment by roblourens** [comment]
Can you give some more specific details? Can you reproduce it consistently?
