### ISSUE TITLE
Unexpected problems

### ISSUE THREAD

**Issue by YangBai8023** [Microsoft/vscode#72182]
Issue Type: <b>Bug</b>

Here is my code:
```
#include <stdio.h>
#include <stdlib.h>
void main()
{
   int i = 0;

   for (int idx = 0; idx < 100; idx++)
   {
      i = i + idx;
   }
   printf("%d\n", i);
   system("pause");
}
```
There are 2 problems detected:
1,expected an expression[7,9]
2,identifier "idx" is undefined[7,22]

I don't know why,  maybe it is a bug.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vscode-c-syntax|dun|0.0.11
HdsCppSnippets|hua|0.0.1
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
vscode-icons|vsc|8.5.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The problems reporting comes from the ms-cpptools extension. Please file the issue there.
