### ISSUE TITLE
Backspace does not handle certain emoji correctly

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#7218]
Version: 1.2.0-insider
Commit: 7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f

Steps to Reproduce:
1. Type an emoji such as "💩".
2. Delete an emoji character using [Backspace] key.
3. You can see only a half of the character is deleted.

Interestingly, cursor move, [Delete] key work correctly with the character.

![remove-poo](https://cloud.githubusercontent.com/assets/1311400/15802553/e0a846a0-2af0-11e6-89cd-8ec36b5f42b8.gif)

**Comment by espresso3389** [comment]
Oops, I mis-understood the issue. The code sequence does not have any EVS.
But the emoji character was just treated as two character sequences.
Anyway, this seems a bug of vscode.

**Comment by jeremywiebe** [comment]
I suspect this is related, but when I add certain emoji from the *Characters* view in macOS, I sometimes see an alternate emoji and a second black-and-white symbol. My guess is this is related to mutli-byte unicode characters or combining marks (as #22486).

For example: if I select the man signaling "no" (🙅‍♂️), I get this:

![image](https://user-images.githubusercontent.com/77138/29731994-884232ea-899b-11e7-8bf8-d7c1787ff012.png)

What's interesting is that Chrome doesn't handle this properly either... so might be unfixable until electron/chrome does.

**Comment by alexandrudima** [comment]
@jeremywiebe You are correct, our version of Chromium (58) does not yet render 🙅‍♂️ correctly. GitHub appears to use some sort of library to overcome this issue (and render it correctly in the comment):
```
<g-emoji alias="no_good_man" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f645-2642.png" ios-version="10.0">🙅&zwj;♂️</g-emoji>
```

This will work correctly for us once Chromium renders it correctly. Given also Chromium 60 does not render this emoji correctly, perhaps you could create an issue with them at https://bugs.chromium.org/p/chromium/issues/list

---

In the meantime, it appears we have fixed the original issue (with backspacing)
