### ISSUE TITLE
Python enviroments gone after last vscode update

### ISSUE THREAD

**Issue by jheffez** [Microsoft/vscode#72197]
Upon launch of updated vscode 1.33.1 all python environments are gone from bottom left bar. Trying to python:select interpreter return error: command 'python.setInterpreter' not found. Reinstall python extension did not help..

**Comment by aeschli** [comment]
Please file this issue against the python extension: https://github.com/Microsoft/vscode-python/issues

**Comment by jheffez** [comment]
@aeschli, the problem started after vscode update, not the extension..

**Comment by aeschli** [comment]
Please still file to the python extension, so they can investigate why the extension no longer works.

**Comment by jheffez** [comment]
I did. 
I suggest both groups looking into this.
