### ISSUE TITLE
customize name of workspace '.vscode' directory 

### ISSUE THREAD

**Issue by samodadela** [microsoft/vscode#72196]
Use case: I'm sharing the same source directory (via volume mount) on two machines (one on mac, one on linux). I'm usually developing on mac and then testing the same code in a VM on linux. This is a cmake/c++ project so the build artifacts are already separated by specifying different build directories (outside the source tree). The only issue I have is with the workspace .vscode directory - I'd like the linux box to use a different directory than .vscode - for example .vscode-linux. This way I can keep separate workspace settings, launch, intellisense, etc. The name of the .vscode directory should be saved in the users settings.json (so it's global for this user) - once configured vscode should always try to open workspace .vscode-linux on that machine. 

The source tree would than look like this:
mySrc/.vscode/*
mySrc/.vscode-linux/*
mySrc/src/
mySrc/test/

Hopefully the workspace name '.vscode' is not hardcoded in a million places and is always obtained via a function call ;) 

The workaround I have is using symlinks:
myLinkedSrc/.vscode/
myLinkedSrc/src@ -> ../mySrc/src
myLinkedSrc/test@ -> ../mySrc/test
myLinkedSrc/CMakeLists.txt@ -> ../mySrc/CMakeList.txt

But that would not work on windows. 

Sorry if this is a duplicate of some other request - I did my best, but searching for "vscode", ".vscode", "workspace vscode" is a bit challenging :)

**Comment by aeschli** [comment]
There's currently no way of changing the `'.vscode'` folder name. In theory what's in there should work on all platforms. I think it's ok to share these across platforms, but maybe what you are looking for are more platform specific settings and launches. The launches have already the capability for platform specific exec paths and arguments.
Not sure what you mean by `intellisense`

**Comment by samodadela** [comment]
Example of stuff that does not work on different platforms (if sharing the source folder):
- .vscode/c_cpp_properties.json: contains compiler paths (I use clang on mac, gcc on linux)
- .vscode/settings.json: the setting from mac should not apply on linux (for example on linux vscode added "C_Cpp.intelliSenseEngineFallback": "Disabled", I don't want that on the other system)

AFAIK any extension can put its settings in workspace .vscode - those settings might also be machine specific and won't work between systems.

The point here is to be able to share the code (same source tree), but not the settings.

**Comment by aeschli** [comment]
What's in `.vscode` are the settings applying to that workspace and are typically also put into SCM (Git,...) and shared amongst all developers of the project. So the settings are expected to work for all machines and users.

User specific settings should go in the user settings. Maybe that would make sense for you to do for `"C_Cpp.intelliSenseEngineFallback": "Disabled",`

`.vscode/c_cpp_properties.json` should also be designed the way that it is platform neutral. If not, it should contain platform specific settings. Please file this as a request against the cpp extension.

**Comment by samodadela** [comment]
Yes, c_cpp_properties.json has sections with names of the platform (name: Linux, Mac).. this does help a bit, but what if I have two "Linux" boxes - one using clang, the other gcc? :) How will vscode select the right one? 

It seems that not all extension developers know that settings are "expected to work for all machines and users"... so an option to workaround such extensions would be welcome. By being able to specify a different instead of .vscode there would be no problems.

I never check-in .vscode into source control - the extensions I use always recreate the files they need. The only file I usually have to edit is launch.json - since the path of the binary is different depending on the system I work on.

As said... If there are too many places where the name '.vscode' is hardcoded and if extensions also hardcode that name - forget about it. There was a similar request for JetBrains products for the .idea folder and this was the reason why it couldn't be done.

**Comment by GitMensch** [comment]
I'd recommend to _not_ do this, but @samodadela with the .workspace file that now exist and can include all definitions that are otherwise found in the .vscode folder you could move all entries there and have two files, don't you think?

So maybe that issue is up for closing?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/29918
