### ISSUE TITLE
Opening Terminal will crash VS Code 32-bit client on 64-bit Windows

### ISSUE THREAD

**Issue by spixy** [Microsoft/vscode#72190]
Issue Type: <b>Bug</b>

Everytime I click on Terminal, VScode crashes.
https://drive.google.com/file/d/13aI7kZScZ75wMGVm9OQlfPgaou201K7L/preview
It doesn'´t matter if I have open file, folder or nothing.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.18362

Also happened in version 1.33.0.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (6.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.26.0
auto-rename-tag|for|0.0.15
vscode-nuget-package-manager|jmr|1.1.6
Angular2|pav|0.0.1
material-icon-theme|PKi|3.7.0
typescript-hero|rbb|3.0.0
java|red|0.42.1
vscode-hexdump|sle|1.7.2
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.18.0

</details>

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by spixy** [comment]
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 16,
    "explorer.openEditors.visible": 0,
    "todohighlight.keywords": [
        "TODO",
        "HACK",
        "NOTE"
    ],
    "workbench.startupEditor": "newUntitledFile",
    "typescript.check.npmIsInstalled": false,
    "zenMode.hideTabs": false,
    "git.ignoreMissingGitWarning": true,
    "explorer.confirmDelete": false,
    "workbench.iconTheme": "material-icon-theme",
    "window.zoomLevel": 0,
    "explorer.confirmDragAndDrop": false,
    "workbench.colorTheme": "Visual Studio Dark",
    "editor.minimap.maxColumn": 80
}
```

**Comment by billwert** [comment]
I'm also getting a crash when I try to open a terminal.
```cmd
Version:          Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS Version:       Windows_NT ia32 10.0.18877
CPUs:             Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)
Memory (System):  63.79GB (48.21GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       71   16616  code main
    0      119    5876     window (Visual Studio Code)
    0       70   19188       extensionHost
    0       35    4012         electron_node server.js
    0       78   16696     gpu-process
    0       63   20944     shared-process
```

I just upgraded. Opening code again doesn't help. Doesn't seem to matter if I have files open or not.

Looking at the help output I took a guess and ran with `--verbose --log debug`. I see this when it crashes:
```cmd
[4244:0417/103537.844:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[4244:0417/103537.845:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[4244:0417/103537.847:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[4244:0417/103537.986:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-04-17T17:35:38.131Z] [VS Code]: render process crashed!
[main 2019-04-17T17:35:38.131Z] telemetry/windowerror { type: 2 }
```

Happy to collect whatever other data you might need @tyriar.

**Comment by Tyriar** [comment]
It looks like this could be related to ConPTY under 32-bit Windows, does adding this setting help?

```
"terminal.integrated.windowsEnableConpty": false
```

**Comment by billwert** [comment]
That fixed it!

**Comment by spixy** [comment]
That fixed it for me as well.

**Comment by Tyriar** [comment]
Thanks for verifying, I've moved this upstream to ConPTY https://github.com/Microsoft/console/issues/412

**Comment by Tyriar** [comment]
https://github.com/Microsoft/node-pty/issues/277

**Comment by spixy** [comment]
btw. we both have 64-bit Windows (I assume billwert doesn´t use 32-bit OS with 64GB ram)

**Comment by Tyriar** [comment]
@spixy @billwert your machines say:

> Windows_NT ia32 10.0.18362

Are you using the 32-bit version of VS Code maybe? Perhaps conpty doesn't work via WoW64

**Comment by oising** [comment]
I just installed the 64 bit insiders version of Code and it doesn't crash -- is ConPTY enabled by default for latest Code?

**Comment by Tyriar** [comment]
@oising ok it sounds like that's it then.

ConPTY is enabled from VS Code stable 1.33, provided you're on Windows 10 > build 18309
