### ISSUE TITLE
No implicit any check fails for this file in electron-main

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#72193]
Check the following code:

https://github.com/Microsoft/vscode/blob/39012b24631928b528c0e1fb83d28a06d9e6e491/src/vs/platform/history/electron-main/historyMainService.ts#L285

You can hover and see the type is found to be "any", but no error is reported. 

It looks like the type can only ever be `string`, but then the hover should show that too?

![image](https://user-images.githubusercontent.com/900690/56020738-1ed66780-5d08-11e9-801a-32b44a4309b7.png)

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/30899 to track this upstream
