### ISSUE TITLE
Fix your files bugs checker on Linux version

### ISSUE THREAD

**Issue by loptova** [Microsoft/vscode#72206]
Issue Type: <b>Bug</b>

Fix your files bugs checker on Linux version

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.18.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 1514)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.41GB (16.80GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
postgresql|JPT|0.0.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
vetur|oct|0.18.1
vscode-icons|vsc|8.5.0

(2 theme extensions excluded)

</details>

**Comment by rcjsuen** [comment]
@loptova Could you describe in more detail what you experienced? What did you see that looked buggy?

**Comment by jrieken** [comment]
closing because this issue is without actionable information
