### ISSUE TITLE
Reveal in explorer opens explorer twice

### ISSUE THREAD

**Issue by janhaertel** [microsoft/vscode#72207]
When I **right-click** a file in the sidebar explorer and click **"reveal in explorer"**, the file's folder is **opened** in the **windows explorer**. Sometimes after several seconds, the **explorer opens** the **folder again**.
This doesn't always happen but every once in a while. Is there maybe a way to log what vscode is doing here ?

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes
F1 > developer tools > sources > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/e6215b9fc9a14a379157fa5cbe1f8317595dd854/src/vs/workbench/contrib/files/browser/fileCommands.ts#L404)
And figure out what is going on since I can not reproduce

**Comment by janhaertel** [comment]
Ok I installed vscode insiders and am sometimes able to reproduce the error. I noticed now that when it happens, the context menu freezes after I right-click and select "reveal in explorer". The second time the explorer opens is after the frozen contextmenu disappears, after some seconds.

I'm still trying to go to the sources but when I do F1 > developer tools I don't get a third option "sources".

**Comment by isidorn** [comment]
Sources is a tab under the developer tools window

![Screenshot 2019-04-16 at 09 37 28](https://user-images.githubusercontent.com/1926584/56190792-4cceeb00-602b-11e9-82a5-67ccaab42936.png)

**Comment by janhaertel** [comment]
Ah ok thank you.

**Comment by alexandre-trottier** [comment]
I don't have qttabbar and I get the exact same problem: when I click reveal in explorer, the explorer window opens immediately and VS Code freeze for 30 seconds and then the explorer window open again.
