### ISSUE TITLE
Unless I'm wrong, I founda bug in CSS coding assis it *tries* to provide me...

### ISSUE THREAD

**Issue by DumbJoe** [Microsoft/vscode#72202]
Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Copy this code:
`:not(article) > header h2 { text-transform: lowercase; text-shadow: 1px 1px #FFFFPF;}`
2. Paste into a new file and it reveals your "error"...

Does this issue occur when all extensions are disabled?: Yes

Screenshots:

![semi-colon expected](https://i.imgur.com/I5Ntqkm.png)
![at-rule or selector expected](https://i.imgur.com/d3M22iC.png)

**Comment by usernamehw** [comment]
Is this a valid HEX color `#FFFFPF`?

**Comment by koishy** [comment]
#FFFFPF is an invalid hex code

**Comment by DumbJoe** [comment]
> #FFFFPF is an invalid hex code

If it's invalid how come it's official in an educational institute that I attend:

![image](https://i.imgur.com/fY5jMDI.png)

And if it's truly invalid, how come it works:
![works](https://i.imgur.com/dS9yn4u.png)

?

Getting the "invalid" hex code out(which would revert to default or whatever code it inherits from):
![out](https://i.imgur.com/3CjvuJK.png)

Explain....

**Comment by octref** [comment]
> how come it works:

Browser falls back to using `#FFFFFF` doesn't mean your input is valid CSS.

> If it's invalid how come it's official in an educational institute

I wonder why too, you should ask your educational institute.

**Comment by DumbJoe** [comment]
> Browser falls back to using #FFFFFF doesn't mean your input is valid CSS.

Oh I see...

> I wonder why too, you should ask your educational institute.

Yes I will ask, thanks!
