### ISSUE TITLE
--help formatting is bad after localization

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7220]
cc @joaomoreno 

Standard sized (80 width) terminal:

![image](https://cloud.githubusercontent.com/assets/2193314/15802830/7a6c70d0-2a75-11e6-8971-342eff7895e4.png)

This is what is was like before:

![image](https://cloud.githubusercontent.com/assets/2193314/15802833/8b6528c8-2a75-11e6-8cd8-de0894cd53a3.png)

**Comment by Tyriar** [comment]
@joaomoreno do you have any reason against using a community lib for this if I get the deps approved?

**Comment by joaomoreno** [comment]
Not at all... I just think that the hard 80 column wrap is an unnecessary remnant of the past, given the resizing capabilities of terminal emulators of today.

**Comment by Tyriar** [comment]
@joaomoreno yeah, I believe the community libs like yargs size the column dynamically but keep formatting similar to what it was like before.
