### ISSUE TITLE
Git: Filename capitalization change diff 

### ISSUE THREAD

**Issue by AhsanE** [Microsoft/vscode#72205]
- VSCode Version: 1.33.1
- OS Version: Win 10

Steps to Reproduce:

1. Set up git through the VS Code Source Control UI
2. Make a file with all with a name `procfile`
3. Make changes and publish the branch
4. Rename the file to `Procfile` (notice the "P" with capitals)

It is expected that VS Code will diff the file names upper CASE and allow to update the filenames to match the right CASE. 
On Heroku the right capitalization is required for `Procfile`.

**Comment by joaomoreno** [comment]
What does `git status` return when you rename the file? https://stackoverflow.com/questions/8904327/case-sensitivity-in-git

**Comment by AhsanE** [comment]
This:

```
On branch master
Your branch is up to date with 'heroku/master'.

nothing to commit, working tree clean
```

**Comment by joaomoreno** [comment]
VS Code just reflects what Git says. `git status` reports no status, so VS Code does the same.

More info: https://stackoverflow.com/questions/8904327/case-sensitivity-in-git
