### ISSUE TITLE
Stop button on serach doesn't stop search

### ISSUE THREAD

**Issue by ryan-jonesford** [microsoft/vscode#72208]
Issue Type: <b>Bug</b>

When doing a search through all files in the workspace directory, the search cannot be stopped by clicking the stop button. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
clipboard-history|Anj|1.0.7
dakara-foldplus|dak|1.3.2
matlab|Gim|1.0.0
AWK|lug|0.0.2
rainbow-csv|mec|1.0.0
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
powershell|ms-|1.12.0
text-marker|ryu|1.10.0

</details>

**Comment by roblourens** [comment]
I can't reproduce this, please give some more details about exactly what you are seeing.

**Comment by ryan-jonesford** [comment]
Before clicking the stop button:
 ![image](https://user-images.githubusercontent.com/1300041/56224270-55c8b800-603d-11e9-869b-e971cc5102d3.png)
After clicking the stop button: 
![image](https://user-images.githubusercontent.com/1300041/56224320-7264f000-603d-11e9-947c-f2a9b9c20df4.png)
Note that it is still searching as indicated by the stop button still there and the line on top.

It seems that it is happening when it is able to first find the search term, but then as it is traversing the filesystem it cannot be stopped. If the term isn't found yet, it'll stop okay.

This doesn't happen on my linux VM, the search happens MUCH faster and I don't even have time to hit the stop button before it finishes. It might be a windows specific problem.

**Comment by roblourens** [comment]
I can reproduce this on windows as well.
