### ISSUE TITLE
Code create index.html files when its opened

### ISSUE THREAD

**Issue by DLuensch** [Microsoft/vscode#72212]
Code always create a index.html file with a google start page when its opened. If the file already exists a new file named index.html.1, index.html.2 etc. is created. I tested it with a completely fresh installed system (Kubuntu 18.04) and fresh installed vscode 1.33.1 without any addons. After I had the issue there I installed gnome-desktop and the same issue is still there.

I attached the files as an .txt because the upload of .html files is not allowed: [index.txt](https://github.com/Microsoft/vscode/files/3073571/index.txt)

- VSCode Version: 1.31
- OS Version: Ubuntu 18.04 and Kubuntu 18.04

Steps to Reproduce:

1. Launching code or opening a file directly
2. The file occurs in Home (~) or in the current folder where you opened the file

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This must be an extension that is causing that. Please disable all extension as see if this still happens.
