### ISSUE TITLE
Java Extension Pack: rejected promise not handled within 1 second: SyntaxError: 

### ISSUE THREAD

**Issue by bugada** [Microsoft/vscode#72216]
VSCode Version: 1.33.1
- OS Version: Windows 7 Pro

Steps to Reproduce:

1. Open a java project
2. After upgrading to latest release, java errors are not hightlighted, nor update project works. The console says:

[Extension Host]
stack trace: SyntaxError: "c:/Users/andrea/git/orderfe/src/main/java/it/andrea/controller/MyController.java" is not a valid JSON Schema
	at C:\Users\andrea\.vscode\extensions\arjun.swagger-viewer-2.2.1\node_modules\json-schema-ref-parser\lib\index.js:114:19
	at o (C:\Users\andrea\.vscode\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69130)
	at C:\Users\andrea\.vscode\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69474
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
log.ts:173   ERR "c:/Users/andrea/git/orderfe/src/main/java/it/andrea/controller/MyController.java" is not a valid JSON Schema: SyntaxError: "c:/Users/andrea/git/orderfe/src/main/java/it/andrea/controller/MyController.java" is not a valid JSON Schema
	at C:\Users\andrea\.vscode\extensions\arjun.swagger-viewer-2.2.1\node_modules\json-schema-ref-parser\lib\index.js:114:19
	at o (C:\Users\andrea\.vscode\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69130)
	at C:\Users\andrea\.vscode\extensions\vscjava.vscode-java-pack-0.6.0\out\extension.js:1:69474

Does this issue occur when all extensions are disabled?: N/A (requires Java Pack Extension)

**Comment by aeschli** [comment]
Please file this against https://github.com/Microsoft/vscode-java-pack
