### ISSUE TITLE
find is not restricted to project scope

### ISSUE THREAD

**Issue by elbkind** [Microsoft/vscode#72213]
- VSCode Version: 1.33.0
- OS Version: OSX Mojave

Steps to Reproduce:

1. lookup a project
2. In parent dir of project create a file "test.ts" with aaa=bbb as content
3. start code and open project
4. Open find ( cmd shift f)
5. search text: aaa
4. file to include: /**/*.ts

Expected: should only search in project scope and should not find the file
Result: finds file in parent dir

It seems that "/" maps to the user home dir and not the root of the current project.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
> It seems that "/" maps to the user home dir and not the root of the current project.

That's correct, you can simply use `*.ts`

**Comment by elbkind** [comment]
why is this closed? 
If i mistype my whole user dir is searched. This really is a feature?
Eventually i get a dialog that vscode requires permissions to read my contacts and calendar data.

**Comment by roblourens** [comment]
It's interpreted as an absolute path, so `/**/*.ts` searches your whole disk. This is by design so you can search arbitrary folders.
