### ISSUE TITLE
Ctrl+click to go to the imported .vue file.

### ISSUE THREAD

**Issue by yangcore** [Microsoft/vscode#72219]
Issue Type: <b>Feature Request</b>

Ctrl+click to go to the imported .vue file.  But now it is not possible to jump
![image](https://user-images.githubusercontent.com/20217483/56075033-6c2d0480-5dee-11e9-9fce-ea2e746e3c93.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gabrc52** [comment]
Can you translate your request to English?

**Comment by byyxx128** [comment]
@gabrc52 No need to translate his sentence... Because I cannot understand what he wanted to say.

**Comment by byyxx128** [comment]
No need to translate his sentence... Because I cannot understand what he wanted to say.

**Comment by yangcore** [comment]
Ctrl+click to go to the imported .vue file  
![image](https://user-images.githubusercontent.com/20217483/56075033-6c2d0480-5dee-11e9-9fce-ea2e746e3c93.png)

**Comment by yangcore** [comment]
> Can you translate your request to English?

Ctrl+click to go to the imported .vue file  
![image](https://user-images.githubusercontent.com/20217483/56075033-6c2d0480-5dee-11e9-9fce-ea2e746e3c93.png)

**Comment by yangcore** [comment]
> No need to translate his sentence... Because I cannot understand what he wanted to say.

Ctrl+click to go to the imported .vue file.  But now it is not possible to jump
![image](https://user-images.githubusercontent.com/20217483/56075033-6c2d0480-5dee-11e9-9fce-ea2e746e3c93.png)

**Comment by SummerYY16** [comment]
I also encountered this problem.
