### ISSUE TITLE
Relese Notes Lag

### ISSUE THREAD

**Issue by imBalji** [microsoft/vscode#72217]
After Update > the Release Notes take alot of time to display content

**Comment by joaomoreno** [comment]
What about when you run the `Show Release Notes` action in the command palette? Does that take long too?

**Comment by baljiBalu** [comment]
Yes., i did try that. It takes about 45-50 seconds for the content to show up.
![image](https://user-images.githubusercontent.com/35697331/56226464-e54b8680-6090-11e9-8216-1988baa076e5.png)

**Comment by joaomoreno** [comment]
If you open the Developer Tools, and run a CPU profile, does anything interesting come up?
