### ISSUE TITLE
Editor renders itself incorrectly while composing Korean character

### ISSUE THREAD

**Issue by joonhwan** [Microsoft/vscode#7221]
- VSCode Version:1.1.1
- OS Version:OSX 10.11.5(El Capitan)

Steps to Reproduce:

1. Open a html file and add normal html5 boilerplate
2. open comment block and begin typing korean more than 3 characters

**Comment by alexandrudima** [comment]
@joonhwan Please try out the [insiders build 1.2.0](https://code.visualstudio.com/insiders), where we have merged in PR #5615 that improves this behaviour. The stable release should come out any day now. Does the issue occur on the 1.2.0 build?

**Comment by joonhwan** [comment]
With the 1.2.0 version, this issue has been resolved. Yeah. Great.
