### ISSUE TITLE
Large image file

### ISSUE THREAD

**Issue by faruk6276** [Microsoft/vscode#72220]
Issue Type: <b>Feature Request</b>

Please add learge image file showing option in vs code.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
After testing, I've increased the size limit to 10mb with 1e5ca39d8426d23a0f98dc4332b1451ed3f191b9
