### ISSUE TITLE
VS code never opens again after crashing on opening large files

### ISSUE THREAD

**Issue by senjacob** [Microsoft/vscode#7222]
- VSCode Version: 1.1.1
- OS Version: Windows 8.1 x64

Steps to Reproduce:

1. Open a large minified javascript file (1MB+).
2. Search for some function name which is located nearly the bottom of the file
3. Now VS code stops responding (may be trying to colorize the code/syntax, but takes too much time).
4. From task manager, force close code with end process tree (Process with command line: code.exe -n)
5. If not reproducible, repeat steps 1-4 a couple of times more.

VS code does not opens ever again. Clearing temp files or re installing the VS code will not work. No error logs in temp or windows event viewer.

Additional info:
- H/W config: Core2 Duo 2.1GHz, 3GB RAM (To check performance)
- Installed extensions:

benjaminromano.typings-installer-0.1.1
dzannotti.vscode-babel-coloring-0.0.4
eg2.tslint-0.5.23
HookyQR.minify-0.2.0
johnpapa.Angular2-0.4.4
ms-vscode.csharp-0.3.7
samverschueren.yo-0.8.4
vsmobile.cordova-tools-1.1.1
warren-buckley.iis-express-0.0.3

Is atom editor compatible with VS Code projects?

**Comment by bpasero** [comment]
@senjacob can you try our insider build (http://code.visualstudio.com/Download#insiders) from the command line with the following arguments: `code-insiders --verbose`

And attach the output here?

**Comment by buzinas** [comment]
If I open any minified javascript file (34kb for example), VSCode crashes here.

And I have a powerful machine, Win10 i7 6th gen 8mb cache, 16gb ram 2133mhz, ssd etc.

**Comment by bpasero** [comment]
@buzinas please report that as separate issue with the file in question attached if possible. Thanks.

**Comment by buzinas** [comment]
@bpasero Done #7254

**Comment by senjacob** [comment]
@bpasero I could not reproduce the problem with VS Code insiders. Hopefully the issue is already fixed in the nightly build. I'll update if I get the issue again.

**Comment by bpasero** [comment]
Ok, closing then.
