### ISSUE TITLE
can not jump to error in Msbuild task for c++

### ISSUE THREAD

**Issue by xspeed1989** [Microsoft/vscode#72229]
- VSCode Version:1.25.1
- OS Version:win10

Steps to Reproduce:

1. create a vc project，and write some invalid code in main.cpp
2.turn off use full paths in C/C++ property page 
3.tasks run in vscode

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by xspeed1989** [comment]
create a file  *.props

`<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <UseFullPaths>true</UseFullPaths>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
`

then add 
 "/p:ForceImportBeforeCppTargets=${workspaceFolder}\\Fullpath.props", to tasks.json like this

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Release",
            "type": "process",
            "command": "cmd",
            "args": [
                // Ask msbuild to generate full paths for file names.
                "/c",
                "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/vcvarsall.bat",
                "amd64",
                "&&",
                "msbuild",
                "/t:build",
                "/p:Configuration=Release",
                "/p:ForceImportBeforeCppTargets=${workspaceFolder}\\*.props"
            ],
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
            },
            // Use the standard MS compiler pattern to detect errors, warnings and infos
            "problemMatcher": "$msCompile",
            "options": {
                "cwd": "${workspaceFolder}"
            }
        }
    ]    
}`

**Comment by alexr00** [comment]
This is by design. The `msCompile` problem matcher only handles absolute paths.
