### ISSUE TITLE
Opening File of Same Name But Different Extension Replaces the Previous One

### ISSUE THREAD

**Issue by HarieshJay** [Microsoft/vscode#72221]
- VSCode Version: 1.33.1
- OS Version: Ubunutu 16.04

It is hard to tell if this is a feature or a bug, sorry if this was intended. 

Steps to Reproduce:

1. Create a folder with 2 files that have the same name but a different extension in the same folder. For example, GameState.cpp and GameState.h. Make sure both files are empty
2. Open the folder into vs code and one of the files. 
3. When you try to open the other file, it replaces the current one instead of opening a new tab.

Both files have to be blank.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jasperswallen** [comment]
Hmm, I can't replicate this. Are you sure you are saving the file in place? By default, if you don't make a change to a file, it is kept only temporarily, and opening a new file replaces it, so this seems to be intentional.

**Comment by HarieshJay** [comment]
That's probably what it is.

Thanks for your help and sorry about that!
