### ISSUE TITLE
Duplicate 'E' access key in Brazilian Portuguese

### ISSUE THREAD

**Issue by awvalenti** [microsoft/vscode#72238]
- VSCode Version: Versão: Commit de 1.33.1 (user setup): 51b0b28134d51361cf996d2f0a1c698247aeabd8 Data: 2019-04-11T08:27:14.102Z elétron: 3.1.6 Chrome: 66.0.3359.181 node. js: 10.2.0 V8: 6.6.346.32 OS: Windows_NT x64 10.0.17134
- OS Version: Windows 10 Pro and Linux Mint 19 Cinnamon

Steps to Reproduce:

1. Press Alt + E
2. Submenu Exibir (View) is open; can't open submenu Editar (Edit).

#71075 was almost exactly the same, but regarding Arquivo/Ajuda. Didn't realize the same was going on for Editar/Exibir.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/834921/56072065-a1dbda00-5d69-11e9-8136-130d7bbc97f2.png)

Should change &Exibir to E&xibir (underlining 'x' instead of 'E'). Editar should be kept the same. This is the usual behavior, like Notepad below:
![image](https://user-images.githubusercontent.com/834921/54923406-f0275700-4ee8-11e9-8188-16c948fb2bd4.png)

**Comment by lukaschal** [comment]
Fixed.

new tgt: E&amp;&amp;xibir
