### ISSUE TITLE
Missing tab title for settings.json 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#72239]
VS Code version: Code - Insiders 1.34.0-insider (b7c5e104a44b65e937408a10cbb8b49d6dfd19bf, 2019-04-12T11:12:09.412Z)
OS version: Darwin x64 18.2.0

**repo**
1. Open settings editor.
1. Click on `{}` to open the `settings.json` file

**Bug**
Notice that the opened json file has no title in the tab bar:

![Screen Shot 2019-04-12 at 5 27 30 PM](https://user-images.githubusercontent.com/12821956/56072102-6846a700-5d48-11e9-8254-5d34cdfa0176.png)

**Comment by roblourens** [comment]
Is this user settings? I don't see that

**Comment by roblourens** [comment]
I see it in the split editor
