### ISSUE TITLE
Error in Integrate Terminal

### ISSUE THREAD

**Issue by GustavoFSoares** [Microsoft/vscode#72231]
Issue Type: <b>Bug</b>

When I start my vscode, my integrate terminal don't start.
I can press Enter for "show" the first line with the path of the workspace

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (4.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|1.8.1
vue-snippets|hol|0.1.11
atom-keybindings|ms-|3.0.6
PowerShell|ms-|1.11.0
vetur|oct|0.18.1
material-icon-theme|PKi|3.7.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.6.0
vscode-status-bar-format-toggle|tom|1.5.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by GustavoFSoares** [comment]
Ok. Thanks

Em seg, 15 de abr de 2019 5:59 PM, Daniel Imms <notifications@github.com>
escreveu:
