### ISSUE TITLE
VSCODE cannot get right process.env

### ISSUE THREAD

**Issue by ShenChen-Amazon** [microsoft/vscode#72235]
Here might be a related one: https://github.com/Microsoft/vscode/issues/70248

- VSCode Version: 1.33.1
- OS Version: mac 10.13.6

Steps to Reproduce:

1. Inside our plugin extension, we use node module shelljs to detect whether a file exists by using the 'which' fucntion. This function will traverse process.env.path and see if there's a match.
2. It works well for most of time, excepet a few machines. When we launch vscode from terminal, everything looks good. But when we launch the vscode through dock, it will report that file doesn't exist. So I guess vscode may have problem to access process.env when it was launched by dock.

Code in extension.ts

```ts
export async function activate(context: vscode.ExtensionContext) {
    if (!await wasCliInstalled()) {
        return;
    }
   ...........
}

async function wasCliInstalled() {
    if (!shell.which('nameOfTheFile')) {
        const action = ....
        return false;
    }
    return true;
}
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
lazy env issue?

**Comment by jrieken** [comment]
> lazy env issue?

Maybe but very unlikely, it would mean that we start the extension host before having resolved the environment... 

@joaomoreno Do you know how @ShenChen-Amazon can measure how long it takes to resolve the env...

**Comment by ShenChen-Amazon** [comment]
Hey guys @bpasero @jrieken ,

Thanks for responding, may I know what thing I can do on my side to provide more info you need?

Thanks,
Shen

**Comment by joaomoreno** [comment]
@ShenChen-Amazon If you open the Developer Tools and run `getLazyEnv().then(console.log)`, do you get the expected environment?

**Comment by panw** [comment]
@ShenChen-Amazon  @joaomoreno  This is what I get as my output
 
```
Apple_PubSub_Socket_Render
:
"/private/tmp/com.apple.launchd.wm54InyDZd/Render"
COMMAND_MODE
:
"unix2003"
HOME
:
"/Users/panwangp"
LOGNAME
:
"panwangp"
PATH
:
"/usr/bin:/bin:/usr/sbin:/sbin"
SHELL
:
"/bin/false"
SSH_AUTH_SOCK
:
"/private/tmp/com.apple.launchd.7nV4nwQt1A/Listeners"
TMPDIR
:
"/var/folders/fq/3z17qknd553grhy5fr3tpfr5twgw4y/T/"
USER
:
"panwangp"
VSCODE_IPC_HOOK
:
"/Users/panwangp/Library/Application Support/Code/1.35.0-main.sock"
VSCODE_LOGS
:
"/Users/panwangp/Library/Application Support/Code/logs/20190607T165827"
VSCODE_NLS_CONFIG
:
"{"locale":"en-us","availableLanguages":{},"_languagePackSupport":true}"
VSCODE_NODE_CACHED_DATA_DIR
:
"/Users/panwangp/Library/Application Support/Code/CachedData/553cfb2c2205db5f15f3ee8395bbd5cf066d357d"
VSCODE_PID
:
"51699"
XPC_FLAGS
:
"0x0"
XPC_SERVICE_NAME
:
"com.apple.xpc.launchd.oneshot.0x10000049.Electron"
__CF_USER_TEXT_ENCODING
: "0x75C7F09E:0x0:0x0"
```

**Comment by sattpat** [comment]
I ran into the same issue yesterday. Could this ticket be reopened?
