### ISSUE TITLE
Find not working

### ISSUE THREAD

**Issue by kishanvasoya1** [Microsoft/vscode#72246]
Issue Type: <b>Bug</b>

Ctrl+F find did't work, it is't correctly highlighted and "1 of 1" those number not working

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-autocomplete|chu|0.2.13
apex-pmd|chu|0.4.1
vsforce|cov|0.2.0
mavensmate|Dav|0.16.3
vscode-eslint|dba|1.8.2
apex|Joh|1.0.4
notepadplusplus-keybindings|ms-|1.0.2
material-icon-theme|PKi|3.7.0
salesforcedx-vscode|sal|45.10.0
salesforcedx-vscode-apex|sal|45.10.0
salesforcedx-vscode-apex-debugger|sal|45.10.0
salesforcedx-vscode-apex-replay-debugger|sal|45.10.0
salesforcedx-vscode-core|sal|45.10.0
salesforcedx-vscode-lightning|sal|45.10.0
salesforcedx-vscode-lwc|sal|45.10.0
salesforcedx-vscode-visualforce|sal|45.10.0

(8 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@kishanvasoya1 can you provide more information about the content and query you are using ?
