### ISSUE TITLE
Navigation buttons are disappeared.

### ISSUE THREAD

**Issue by Wahib1** [microsoft/vscode#72248]
Issue Type: <b>Bug</b>

After the latest march 2019 update. Navigation buttons(minimize, maximize and close button) are disappeared. Then I have to restart VS code again to make it appear.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (4.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|1.8.1
sublime-keybindings|ms-|4.0.0
LiveServer|rit|5.5.1
indenticator|Sir|0.6.0

</details>

**Comment by kudchikarsk** [comment]
> Issue Type: Bug
> 
> After the latest march 2019 update. Navigation buttons(minimize, maximize and close button) are disappeared. Then I have to restart VS code again to make it appear.
> 
> VS Code version: Code 1.33.1 ([51b0b28](https://github.com/Microsoft/vscode/commit/51b0b28134d51361cf996d2f0a1c698247aeabd8), 2019-04-11T08:27:14.102Z)
> OS version: Windows_NT x64 10.0.16299
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)
> GPU Status	2d_canvas: enabled
> checker_imaging: disabled_off
> flash_3d: enabled
> flash_stage3d: enabled
> flash_stage3d_baseline: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> native_gpu_memory_buffers: disabled_software
> rasterization: enabled
> surface_synchronization: enabled_on
> video_decode: enabled
> webgl: enabled
> webgl2: enabled
> Memory (System)	7.92GB (4.27GB free)
> Process Argv	
> Screen Reader	no
> VM	0%
> Extensions (5)
> Extension	Author (truncated)	Version
> bracket-pair-colorizer	Coe	1.0.61
> prettier-vscode	esb	1.8.1
> sublime-keybindings	ms-	4.0.0
> LiveServer	rit	5.5.1
> indenticator	Sir	0.6.0

Does this buttons disappeared at start of the application or does any series of task/activity make it disappear?

**Comment by Wahib1** [comment]
Only after first boot up when i launch VS code it disappeared. When close
it and launch it again then it is appeared as normal.

**Comment by sbatten** [comment]
@Wahib1 Is this something you can reproduce every time you reboot your machine?

**Comment by Wahib1** [comment]
Yes

**Comment by sbatten** [comment]
@wahib1 can you open dev tools and check to see if the controls are present in the DOM? Also, would you mind posting a screenshot of them missing just so I am sure I understand the problem correctly?

**Comment by Wahib1** [comment]
Yes, sure
