### ISSUE TITLE
Don't remove uncommitted git message when closing application

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#72247]
If you type something into the git commit message box and then close vscode and reopen it, whatever you entered is gone. It should be saved there allowing you to continue editing it later.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/26952

**Comment by rightaway** [comment]
That issue is about commit history, what does it have to do with this?

Should I create this issue again or can you actually explain how the linked one relates at all to this? It might be a good idea to do this in general if you want to close an issue with a link to another where the relation isn't clear.
