### ISSUE TITLE
设置无法更改-Mac

### ISSUE THREAD

**Issue by Nancy626** [Microsoft/vscode#72240]
Issue Type: <b>Bug</b>

苹果电脑
1.Code-首选项-设置-工作区设置-文本编辑器-Auto Closing Brackets
  无法设置为never
2.Code-首选项-设置-工作区设置-文本编辑器-Auto Closing Quotes
  无法设置为never

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vue-snippets|hol|0.1.11
jquery-snippets|Hri|1.0.0
quickstart|lol|0.1.0
vscode-language-pack-zh-hans|MS-|1.32.4
vetur|oct|0.18.1
open-html-in-browser|pea|1.0.4
vue-vscode-snippets|sdr|1.6.0
highlight-matching-tag|vin|0.9.1

</details>

**Comment by rebornix** [comment]
@Nancy626 can you elaborate more what happened when you try to set `Auto Closing Brackets ` to `never`?
