### ISSUE TITLE
debug console input

### ISSUE THREAD

**Issue by car520120** [Microsoft/vscode#72242]
程序正常运行时 调试控制台下方的为终端输入模式
当触发断点是转为调试命令模式
如果更友好一点可以加上文字描述一下.

![image](https://user-images.githubusercontent.com/36702004/56073685-d471eb00-5dda-11e9-8a57-a68971057bec.png)

主要是使用外部终端每一次程序结束都是需要手动去关闭
使用内置的，需要来来回回切换调试控制台和终端太麻烦调试结束后也是需要手动去关闭

**Comment by weinand** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

**Comment by car520120** [comment]
The terminal input mode is below the debugging console when the program is running normally.
When the trigger breakpoint is changed to debug command mode            
If it's friendlier, you can add words to describe it. 

Mainly using external terminals, each program termination needs to be manually shut down. 
Use built-in, need to switch back and forth debugging console and terminal too much trouble after debugging also need to manually close 

Use built-in, need to switch back and forth debugging console and terminal debugging after the end of the need to manually close! Not easy to use! 

Maybe it's my personal habit.
