### ISSUE TITLE
在window 下，vs code运行会出现占用cup很高的问题

### ISSUE THREAD

**Issue by ChenKaiKe** [Microsoft/vscode#72241]
我的电脑是window系统的，更新了vs code之后，老是出现占用cup很高，导致电脑卡死的。
![image](https://user-images.githubusercontent.com/24711778/56073593-8f998480-5dd9-11e9-9bf6-afed390570d7.png)
vs code 版本：
![image](https://user-images.githubusercontent.com/24711778/56073600-a7710880-5dd9-11e9-9299-6a25692d05ba.png)
希望可以不用占用这么高cup.

**Comment by byyxx128** [comment]
**This person is reporting a performance issue.**
***
1. 请用英文反馈。
2. cup 是什么鬼……
3. 性能问题请走专门的途径来反馈。
![image](https://user-images.githubusercontent.com/20079289/56074659-79150e00-5d84-11e9-9bfb-2e35901d7695.png)

**Comment by ddzy** [comment]
我之前也有遇到这个问题([issue#67150](https://github.com/Microsoft/vscode/issues/67150)), 用的是`VS Code -user`版本, 间隔两分钟左右会出现`CPU`飙到100%.

后来用了[VS Code -exploration](https://code.visualstudio.com/)版本的, 就没有出现这个问题了, 你可以试一下.

**Comment by aeschli** [comment]
Can you run `code --status` when that happens?

**Comment by jrieken** [comment]
Please file issues in English. Thanks!

**Comment by ChenKaiKe** [comment]
> Can you run `code --status` when that happens?
I can run the code, but the computer will be stuck, causing some of the functions in vs code to fail.
