### ISSUE TITLE
Can't set key binding to ctrl shift l

### ISSUE THREAD

**Issue by ChildishGiant** [microsoft/vscode#72259]
In previous versions I've used ctrl+shift+l to transform to lowercase and not had any issues. I just tried using on the bind on 1.33.1 and nothing happened. So I tried to rebind it but it won't let me type ctrl+shift+l. Shift+l and ctrl+l on their own work.

**Versions I've reproduced this on:**
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Version: 1.34.0-insider
Commit: b7c5e104a44b65e937408a10cbb8b49d6dfd19bf
Date: 2019-04-12T11:20:43.178Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Steps to Reproduce:**
1. Open keyboard shortcuts
2. Attempt to bind CTRL+SHIFT+L to any command.

Does this issue occur when all extensions are disabled?: Yes

Here's me trying to bind it and failing.
https://gfycat.com/officialselfreliantfruitbat
![](https://thumbs.gfycat.com/OfficialSelfreliantFruitbat-size_restricted.gif)

**Comment by ChildishGiant** [comment]
I've since reinstalled my drivers and this seems to be resolved. I was trying to replicate this on linux and ctrl+shift+l would work but ctrl+shift+u wouldn't. I think it's fair to say that something was/is wrong with my keyboard but I think it's still worth someone else trying to replicate this.

https://gfycat.com/RegalReadyAfricangroundhornbill
![](https://thumbs.gfycat.com/RegalReadyAfricangroundhornbill-size_restricted.gif)

**Comment by alexandrudima** [comment]
I have tried to reproduce, but was unable to do so, therefore closing this issue for now.
