### ISSUE TITLE
Format document dont work cerfully

### ISSUE THREAD

**Issue by kindslayer** [Microsoft/vscode#72258]
Issue Type: <b>Feature Request</b>

Please check phpstorm format document .. work in html, vuejs,rectjs, sass, less, css, laravel blades and ... 
but whats this! if vscode format document is not complate i prefer remove it from context menu !

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

**Comment by 282159468** [comment]
same issue

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
