### ISSUE TITLE
microsoft.python.language server Memory leak

### ISSUE THREAD

**Issue by liguifa** [Microsoft/vscode#72256]
Issue Type: <b>Bug</b>

system: macOS 10.14.4

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx-languageserver|And|1.0.1
vscode-styled-jsx|bla|1.0.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.2
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.2.1
ts-tslint|eg2|0.0.7
tslint|eg2|1.0.43
vscode-todo-plus|fab|4.13.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vue-snippets|hol|0.1.11
vscode-remote-workspace|mkl|0.37.0
mssql|ms-|1.5.0
cpptools|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|0.0.6
debugger-for-chrome|msj|4.11.3
tslint-vue-tsx|nob|1.0.0
vetur|oct|0.17.1
indent-rainbow|ode|7.4.0
tslint-vue|pro|1.5.6
remote-vscode|raf|1.1.0
java|red|0.40.0
code-settings-sync|Sha|3.2.4
indenticator|Sir|0.6.0
js-jsx-snippets|sky|0.3.0
vscodeintellicode|Vis|1.0.6
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1
gitblame|wad|2.6.3
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
tslint-snippets|zuo|1.1.0

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Please file this against the Python extension: https://github.com/Microsoft/vscode-python/issues

**Comment by ashwin-phadke** [comment]
I am facing the same issue , here is the snip of the screen, it dramatically increases for upto 3+GBs at a certain moment.
Also slows reopening of the vs-code window while maximizing. 
![langserver](https://user-images.githubusercontent.com/23502062/56501291-d4d15b00-652b-11e9-95f9-21e8f26b43b7.jpg)

**Comment by aeschli** [comment]
@DonJayamanne FYI
