### ISSUE TITLE
images

### ISSUE THREAD

**Issue by NesrinaBeqiraj** [Microsoft/vscode#72257]
images are not loading on my website,how can I fix this probl??

**Comment by aeschli** [comment]
What web site?
How is it related to VSCode?

**Comment by NesrinaBeqiraj** [comment]
I'm designing an web by html/CSS using VS code, but I can't insert pic on
web(there on web showing up just contures of my pic,(no pic))?!

**Comment by plibither8** [comment]
This is probably not VSCode bug, but it'll help if you could attach supporting screenshots and code examples where you're facing the problem.

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.

**Comment by NesrinaBeqiraj** [comment]
It's not about any mistakes on code ,even if I write on ,just simple example
<body>
<Img src="...."
</Body>
( If I only insert pic)
Pic doesn't show up on web, it's showing just contures of pic or just name
of pic(alt) aslo colors ( if I want to change ,background-color,or text-
color) there dont change colour on web!
