### ISSUE TITLE
use it made my computer slow

### ISSUE THREAD

**Issue by RubyKiss** [Microsoft/vscode#72250]
use it made my computer slow, the computer  random access memory  very big

**Comment by aeschli** [comment]
Please provide more details. You can run `code --status` when this happens to get more information.

**Comment by RubyKiss** [comment]
that use time is long and open file too more will appear!  i open the file is more and close that,and now the memory storage is very big, up to 80% ,i close all file but it is alway a 80% ,slow slow slow..

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.

**Comment by RubyKiss** [comment]
code --status ,i dont know how to exec....,wt...

**Comment by jrieken** [comment]
open a terminal and type `code --status`
