### ISSUE TITLE
Unable to create package - gulp Task never defined

### ISSUE THREAD

**Issue by floatas** [Microsoft/vscode#72252]
I'm having hard time figuring out how to build package.

Yarn build succeed and I can run VScode with scripts\code.bat

I'm unable to run any of packaging gulp tasks, all of them are not found. Was build\packaging process changed ?

https://github.com/Microsoft/vscode/wiki/How-to-Contribute#packaging

> Packaging
> Code can be packaged for the following platforms: **win32-ia32** | win32-x64 | darwin | linux-ia32 | linux-x64 | linux-arm
> 
> These gulp tasks are available:
> 
> **vscode-[platform]**: Builds a packaged version for [platform].
> vscode-[platform]-min: Builds a packaged and minified version for [platform].
> See also: Cross-Compiling for Debian-based Linux

**Error:**

> yarn run v1.15.2ource\repos\vscode>yarn run gulp **vscode-win32-ia32**
> $ gulp --max_old_space_size=4095 vscode-win32-ia32
> [11:48:01] Node flags detected: --max_old_space_size=4095
> [11:48:01] Respawned to PID: 13940
> [11:48:06] Using gulpfile ~\source\repos\vscode\gulpfile.js
> [11:48:06] Task never defined: vscode-win32-ia32
> [11:48:06] To list available tasks, try running: gulp --tasks
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by alexr00** [comment]
In the last couple months we upgraded to a newer version of gulp. Have you run yarn recently to update?

**Comment by floatas** [comment]
yarn --version
1.15.2

yarn gulp --version
yarn run v1.15.2
$ gulp --max_old_space_size=4095 --version
[06:05:57] Node flags detected: --max_old_space_size=4095
[06:05:57] Respawned to PID: 22076
[06:05:58] CLI version 2.0.1
[06:05:58] Local version 4.0.0

I can build and run project successfully. However, I can't find or run packaging gulp task that are mentioned in documentation.

**Comment by joaomoreno** [comment]
Did you run `yarn` before? Make sure that runs successfully and builds our build scripts.
