### ISSUE TITLE
A lot errors trying to update

### ISSUE THREAD

**Issue by arrbrk1** [Microsoft/vscode#72264]
[vscode-inno-updater-1555171704.log](https://github.com/Microsoft/vscode/files/3076439/vscode-inno-updater-1555171704.log)
Issue Type: <b>Bug</b>

It shown a lot of errors when trying to update (in different times)...

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (3.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.2.1
react-native-react-redux|EQu|2.0.3
auto-close-tag|for|0.5.6
vscode-language-babel|mgm|0.0.22
python|ms-|2019.3.6558
csharp|ms-|1.18.0
advanced-new-file|pat|1.2.0
java|red|0.42.1
LiveServer|rit|5.5.1
vscode-java-debug|vsc|0.17.0
vscode-icons|vsc|8.5.0
vscode-react-native|vsm|0.9.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you reinstall, this time using the System Setup? https://code.visualstudio.com/docs/?dv=win64
