### ISSUE TITLE
Cannot use VSC on Mac Mini, 2011, High Sierra 10.13.6

### ISSUE THREAD

**Issue by EwellBMyne** [microsoft/vscode#72266]
This is an update to the case I pened almost a year ago as EwellBMyne, but newer MacOS and newer VSC.

I have removed VSC multiple times and cleaned the disk. I still get the same problems. I have noticed that though I installed them the same way (emptying the ZIP file into /Applications) the files look much different on my Mojave machine than on my High Sierra machine.

I am using the current Insiders and Stable builds downloaded moments ago. Trying to start yields the below. Clearly, something is wonky with Electron.:

Process:               Electron [67451]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.33.1 (1.33.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [67451]
User ID:               501

Date/Time:             2019-04-13 13:00:26.864 -0400
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        280DF019-3F9E-24D0-BB06-0462870F79C5

Time Awake Since Boot: 1200000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1041ca000 -        0x1041caff3 +com.microsoft.VSCode (1.33.1 - 1.33.1) <B0F33200-8657-3C2B-B027-3BB824CB528A> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x1110a8000 -        0x1110f2acf  dyld (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> /usr/lib/dyld

Model: Macmini5,1, BootROM 131.0.0.0.0, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 1.76f0
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f12, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone 5, Ethernet, en9
Network Service: iPad, Ethernet, en4
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk Ultra II 500GB, 500.11 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: iPad
USB Device: IR Receiver
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: iPhone
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: Mac mini, Apple Inc., 22.2

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by EwellBMyne** [comment]
I did try the Exploration build and the same thing happened. I'm starting to think it is something with my installation because the same versions of Code run great on my other 3 Macs.

Here's the report it popped up:
Process:               Electron [34029]
Path:                  /Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCodeExploration
Version:               1.32.0-exploration (1.32.0-exploration)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [34029]
User ID:               501

Date/Time:             2019-04-16 14:23:19.335 -0400
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        280DF019-3F9E-24D0-BB06-0462870F79C5


Time Awake Since Boot: 1400000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
/Applications/Visual Studio Code - Exploration.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Applications/Visual Studio Code - Exploration.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1081b7000 -        0x1081b7ffb +com.microsoft.VSCodeExploration (1.32.0-exploration - 1.32.0-exploration) <6E272AEB-51ED-363B-B2D0-1E8B0C094EDF> /Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
       0x10f9e2000 -        0x10fa2cacf  dyld (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> /usr/lib/dyld
    0x7fff28400000 -     0x7fff28400fff  com.apple.Cocoa (6.11 - 22) <8C1B3F7A-889A-3D71-A58C-C672665F9E78> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff2ad3a000 -     0x7fff2b100ff3  com.apple.Foundation (6.9 - 1454.95) <0A759716-AD1C-3409-A8FD-D6C615FADB7F> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff2b417000 -     0x7fff2b4b2fff  com.apple.framework.IOKit (2.0.2 - 1445.71.5) <59191D07-0C8E-3823-A124-CE46F1A35935> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff34a44000 -     0x7fff34d6ffff  com.apple.security (7.0 - 58286.70.13) <2AE4C057-B8D1-3DD0-A634-5C50C5146B49> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff351d7000 -     0x7fff35247ff3  com.apple.SystemConfiguration (1.17 - 1.17) <CD4A4C66-7886-3323-A3B9-0C8952500856> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration


________________________________

**Comment by bpasero** [comment]
Yeah possibly something with your machine is wrong, but I am not sure what that could be.

**Comment by EwellBMyne** [comment]
Thanks for the feedback. Its not your job to debug my machine. 🙂 I find it very odd that the same installation package yields different results on both machines.

I love the work all of you are doing on VS Code!
David
________________________________

**Comment by EwellBMyne** [comment]
I just installed the Exploration version on my Macbook Pro that has VS Code Insier running just fine, and it will not run VS Code - Exploration (Insider is till just fine.) Perhaps it doesn't like older Macs? Anyway, FYI...

Process:               Electron [14896]
Path:                  /Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCodeExploration
Version:               1.32.0-exploration (1.32.0-exploration)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [14896]
User ID:               501

Date/Time:             2019-04-17 08:04:05.375 -0400
OS Version:            Mac OS X 10.14.5 (18F108f)
Report Version:        12
Anonymous UUID:        3135F462-6C8A-917A-614A-63B9AC44DC72


Time Awake Since Boot: 580000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
/Applications/Visual Studio Code - Exploration.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Applications/Visual Studio Code - Exploration.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1018b3000 -        0x1018b3ffb +com.microsoft.VSCodeExploration (1.32.0-exploration - 1.32.0-exploration) <6E272AEB-51ED-363B-B2D0-1E8B0C094EDF> /Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
       0x110d5b000 -        0x110dc56ef  dyld (655.1.1) <520FF998-4F89-382C-8440-12700A524F7E> /usr/lib/dyld
    0x7fff3b544000 -     0x7fff3b544fff  com.apple.Cocoa (6.11 - 23) <6BA5D861-9F09-36AA-8A17-76B779416F22> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3e0a2000 -     0x7fff3e44ffff  com.apple.Foundation (6.9 - 1575.12) <AD258ED7-64AE-367C-AE5F-48D45089D9F2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3e757000 -     0x7fff3e7e6fff  com.apple.framework.IOKit (2.0.2 - 1483.260.3) <2EF4EE2F-AA38-3052-977D-C2D84F8AD390> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff47779000 -     0x7fff47a78ff7  com.apple.security (7.0 - 58286.260.16) <2E5C3ECB-2224-3B2E-BA33-5ED3403EC028> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff47ed3000 -     0x7fff47f40fff  com.apple.SystemConfiguration (1.17 - 1.17) <1D0FACF6-1EBD-36B5-998D-97676463FA0B> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration

Model: MacBookPro9,1, BootROM 224.0.0.0.0, 4 processors, Intel Core i7, 2.6 GHz, 16 GB, SMC 2.1f170
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGT650MItem, NVIDIA GeForce GT 650M, spdisplays_pcie_device, 1 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1325.2)
Bluetooth: Version 6.0.12d16, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Crucial_CT525MX300SSD1, 525.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

________________________________

**Comment by EwellBMyne** [comment]
Please ignore the who issue- I found the error on my systems. It was indeed pilot error.

Thanks... (embarrassed grin)
________________________________

**Comment by skywinder** [comment]
@EwellBMyne how did you fix it?
