### ISSUE TITLE
Intellisence (JS) "String" replaced "string"

### ISSUE THREAD

**Issue by MacKentoch** [Microsoft/vscode#72278]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4

Steps to Reproduce:
1. in js file (*with flow types or not?*), declare a `string` (*s lowercase*) type
2. intellisence will always suggest and replace with `String` (*s uppercase*) interface

Did not occur last month and before.

<img width="985" alt="Capture d’écran 2019-04-14 à 07 22 35" src="https://user-images.githubusercontent.com/11223428/56088721-eb6e1700-5e86-11e9-8284-cbb0630c1552.png">

**Comment by mjbvz** [comment]
Have you disabled certain types of suggestions by setting `"editor.suggest.filteredTypes"`?

**Comment by MacKentoch** [comment]
Hi @mjbvz 

I tried:
- disabled / enabled [.vscodeintellicode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)
- ensure flow plugin is installed ([flow-for-vscode](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode))
- played with `"editor.suggest.filteredTypes"` as you suggested (thank you by the way 🙂):
```json
"editor.suggest.filteredTypes": {
        "class": true,
        "color": true,
        "constant": true,
        "enum": true,
        "event": true,
        "enumMember": true,
        "field": true,
        "file": true,
        "folder": true,
        "variable": true,
        "function": true,
        "interface": false,
        "method": true,
        "customcolor": true,
        "keyword": true,
        "module": true,
        "operator": true,
        "property": true,
        "reference": true,
        "snippet": true,
        "struct": true,
        "text": true,
        "typeParameter": true,
        "unit": true,
        "value": true
    },
```

I guess intellisence won't present flow types suggestions (*not that much a problem*) but introduces JS class (String for string etc...).

**Comment by MacKentoch** [comment]
Seems like intellisense tries to be too much helpful (a JS file, ok let's show JS).

How could I try to create some kind key word database for flow type syntax?

**Comment by mjbvz** [comment]
Since you are using flow, have you disabled the built-in js/ts extension as they suggest in their docs? At that point, Flow should be providing intellisense so you should file any issues against that extension

**Comment by MacKentoch** [comment]
Yes already did it since a while. 

I guess `flow-for-vscode` must evolve to help intellisense.

Alright I close this issue (*no need for pollution*) since I will try to see if `flow-for-vscode` had some clue about that.

Thank you @mjbvz 🤝
