### ISSUE TITLE
Problem with output window encoding

### ISSUE THREAD

**Issue by nim** [Microsoft/vscode#72270]
I have problem with encoding in output window. 
![Image](https://i.imgur.com/QRsIZ6e.png)
I apologize if the problem is already known. I was looking for a solution. But I found that it was already fixed a year ago. Maybe something broke again.

- VSCode Version:1.33.1
- OS Version: Win10

locale.json
`
{
    "locale": "en"
}
`

Steps to Reproduce:
Install in a system where there are several languages.

**Comment by isidorn** [comment]
Please file against the C# extension

**Comment by nim** [comment]
Your formal replies look like a mockery. Apparently for this he is still crap. How many years have you been developing it. All problems you have one answer.
