### ISSUE TITLE
[question] windows installer

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#7227]
I am sorry to ask this here as it is not really a VSCode issue, but i think it can be useful to the whole Electron community.
My question is how did you manage to have such a small windows installer? 30Mo is really low.
And your executable is only 56Mo. 
In my project my executable is already 80Mo and the installer (squirrel) is 62Mo.
And i already clean most of the node_modules files.

I have looked at the code and couldn't find the win installer build script so i thought i should ask.

Thanks

**Comment by joaomoreno** [comment]
We use [Inno Setup](http://www.jrsoftware.org/isinfo.php) as a setup framework, which seem to be pretty awesome at compressing. 👍

**Comment by develar** [comment]
@farfromrefug Because Squirrel.Windows uses old ZIP instead of lzma. In the electron-builder we will get rid of Squirrel.Windows soon.

**Comment by develar** [comment]
@joaomoreno If possible, could you please explain why you decided to use Inno instead of NSIS?

**Comment by joaomoreno** [comment]
Just caught our attention first and worked.

**Comment by farfromrefug** [comment]
@joaomoreno you don't apply any transformation to the electron.exe (which becomes vscode.exe) to reduce its size?

**Comment by joaomoreno** [comment]
None.
