### ISSUE TITLE
1.33.1 crashing after running npm start

### ISSUE THREAD

**Issue by emko** [microsoft/vscode#72279]
Issue Type: <b>Bug</b>

when i start up a electron project with npm start after a while vsc will close, i also tested by running nmp start in cmd prompt in this case my electron app keeps running but vscode closes, this does not happen on 1.32

i also tested code --disable-extensions, same thing happens
Thanks

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.96GB (25.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.43
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
Angular2|joh|7.0.1
Angular-BeastCode|Mik|8.0.1
python|ms-|2019.3.6558
csharp|ms-|1.18.0
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
vscodeintellicode|Vis|1.1.5

(1 theme extensions excluded)

</details>

**Comment by emko** [comment]
somehow having games.ts file open when i run npm start, my electron app and vscode crash, when i say crash it just closes to desktop. When i run npm start in cmd prompt my app stays open but VSC crashes.

if i don't have games.ts file open when i do start npm start in VSC everything works fine, ts file just contains a few electron ipcMain event listeners nothing different then any other of files i have written.

i deleted every line in games.ts then saved and still it causes crashes.

i then open copied and moved this emtpy games.ts and then in terminal cd into my projects dir and npm start vsc and my app crash, i rename this file to 2.ts and its not crashing second i rename it back to games.ts it crashes.... :confused: i am lost, i made sure to remove the call to this file in my code so thats not the issue anyways for now i just named it something different and VSC is running smooth.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by emko** [comment]
just tested it, same thing it does seem to crash even faster, just changing this filename to something else and no crashes. 

if i have the VS code developer tools open only VS code will crash and my app will function, in task manager you can see VS code using 30% CPU on one of its process in the background.

https://i.gyazo.com/33259856a611d7c8347a4926fccc86cc.png

**Comment by bpasero** [comment]
@emko can you find out which process that is? we have a process dialog from the help menu

**Comment by emko** [comment]
@bpasero i can't since vs code is gone like i said that process is just running in the background i have no way to get to vs code window.

another interesting thing is when i have the process dialog open i don't get any more crashes, when i close the process dialog i get this in vscode developer tools console, not sure if its related

```
ERR Object has been destroyed: Error: Object has been destroyed
    at WebContents.send (C:\Users\emkoe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\electron.asar\browser\api\web-contents.js:101:15)
    at v.<anonymous> (C:\Users\emkoe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:392:66)
    at Generator.next (<anonymous>)
    at s (C:\Users\emkoe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:11:431)
```

**Comment by bpasero** [comment]
@emko you could use a tool like Process Explorer or Process Monitor to find out the command line arguments of that process.

**Comment by emko** [comment]
@bpasero here is a screen shot of Process Explorer showing vscode process

https://i.gyazo.com/4e73caf703ae91766fa9a5db81305268.png


`"C:\Users\emkoe\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --type=renderer --no-sandbox --enable-features=FixAltGraph --service-pipe-token=8B6CDB73611FFDA02E652A4DEA23866F --lang=en-US --app-user-model-id=Microsoft.VisualStudioCodeInsiders --app-path="C:\Users\emkoe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=8B6CDB73611FFDA02E652A4DEA23866F --renderer-client-id=4 --mojo-platform-channel-handle=2104 /prefetch:1`

**Comment by bpasero** [comment]
@emko does it reproduce if you configure this in settings (you can open the settings file as JSON file):

```json
"files.watcherExclude": {
    "**": true,
}
```

**Comment by emko** [comment]
@bpasero with that its not crashing anymore

**Comment by bpasero** [comment]
@emko can you see if there is possibly a single large folder (maybe some out folder?) that gets created with lots of files? That would be a good candidate to exclude from watching.

**Comment by emko** [comment]
@bpasero  sorry, late here i forgot to have the games.ts file open before testing, it still crashes

**Comment by emko** [comment]
another thing, if i start vscode and make sure the games.ts file is not open and then start up npm start the electron app opens and functions correctly at this point if i open games.ts it does not crash, i don't know if this info helps, if i close my app and rerun npm start with games.ts open it crashes.

i am trying to recreate the problem so i can make a example code i can share to reproduce it, but it seems to be very specific issue causing this.

**Comment by bpasero** [comment]
@emko you mean even with that setting turned on (after a restart)?

**Comment by emko** [comment]
@bpasero yea sorry, last night i opened the file game.ts and when i went to settings it closes the open files and i assumed it was open when i was testing.

my app does not change any or make any new files other then a sqlite3 db file but its only reading since i can't get to anywhere in my app to cause a write.
