### ISSUE TITLE
[Feature] Config option to hide sidebar title

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#72277]
I've searched for similar issues, and extensions.

*Problem:*
Title at the top of the sidebar takes too much space. For example, "EXPLORER", "SEARCH", "SOURCE CONTROL: GIT", "DEBUG", "EXTENSIONS", etc. On some monitors, or when stacking multiple vscode windows, those titles take too much space and add no value.

*Solution:*
 Would be nice to be able to hide it, via a config option. Some titles (e.g. for debug) include some buttons as well, so those should not be hidden.

**Comment by drekevist** [comment]
For a while now trying to find a way to disable the side title bar (including the buttons) as with keybinds it's completely wasted real estate. A command like workbench.action.toggleSidebarControls would be ideal..
