### ISSUE TITLE
After upgrade to 1.33 the vscode icon has disappeared from system menu and/or DE panel on Ubuntu 18.04

### ISSUE THREAD

**Issue by arobenko** [Microsoft/vscode#72272]
Clean reinstall of 1.33.1 didn't help either. It looks like the icon has been moved from /usr/share/pixmaps/code.png to /usr/share/pixmaps/com.visualstudio.code.png, but some place in the system still expects it to find in the old location. 

Copying the icon to the old location made the icon in the system menu and panel to re-appear.

**Comment by ozkanaltuner** [comment]
Can confirm this on Ubuntu 19.04 with version 1.33.1 of VS Code. Copying the icon with name code.png fixed it.
