### ISSUE TITLE
插件首页里文本可以选择但不能复制，不便于复制翻译查询学习，请问有什么解决办法么？

### ISSUE THREAD

**Issue by zhliner** [Microsoft/vscode#72276]
插件首页里基本都是英文，很多时候想了解学习，复制翻译一下是常用的做法。请问为什么不允许复制文本呢？选取是高亮的，说明已经选取。

是出于一种安全原因吗？

我觉得允许复制才是尊重用户学习的权利，不是所有的人都精通英文。这也是对非英语文化的一种尊重，非常感谢！

注：编辑器发行说明里的文本是可以正常复制的。

编辑器：vscode v1.33，vscode insider v1.34
操作系统：MacOS Mojave 10.14.4

Automated translation:

The extensions homepage is basically in English. Many times I want to learn about it. Copying and translating is a common practice. Why is it not allowed to copy text? The selection is highlighted, indicating that it has been selected.

Is it for a security reason?

I think that allowing copying is the right to respect the user's learning. Not everyone is proficient in English. This is also a respect for non-English culture, thank you very much!

Note: The text in the editor's release notes can be copied normally.

**Comment by byyxx128** [comment]
### **The author is asking a question. This issue can be closed directly if necessary.**
***
1. 首先 Github 不是用来问问题的。问问题有专门的平台，
`The issue tracker is not for questions. Please ask questions on https://stackoverflow.com/questions/tagged/visual-studio-code.`
当然这也是纯英文平台，想必你也没兴趣……
2. 为了保证这里所有的人都能够交流，只能使用英文。这和尊不尊重毛关系没有，语言就是个工具。
3. 我试过了可以复制。Command+C、Command+V 没有问题。没有右键菜单倒是真的。如果你确认不能复制，请截图说明。
4. 出于安全原因……你想得太多了点……VS Code 是开源软件，源代码都开放了，还有什么见不得人的……

**Comment by byyxx128** [comment]
### **The author is asking a question. This issue can be closed directly if necessary.**
***
1. 首先 Github 不是用来问问题的。问问题有专门的平台，
`The issue tracker is not for questions. Please ask questions on https://stackoverflow.com/questions/tagged/visual-studio-code.`
当然这也是纯英文平台，想必你也没兴趣……
2. 为了保证这里所有的人都能够交流，只能使用英文。这和尊不尊重毛关系没有，语言就是个工具。
（至少你可以用翻译软件看懂英文，别人用翻译软件也看不懂中文的，所以没办法……除非能让所有的人一夜之间全掌握中文……）
3. 我试过了可以复制。Command+C、Command+V 没有问题。没有右键菜单倒是真的。如果你确认不能复制，请截图说明。
4. 出于安全原因……你想得太多了点……VS Code 是开源软件，源代码都开放了，还有什么见不得人的……

**Comment by Garfield550** [comment]
You can use Menu > Edit > Copy to copy Extension page content.

![image](https://user-images.githubusercontent.com/3471836/56106835-a70d7480-5f75-11e9-88bc-e9e5a501b4a1.png)

`When you rename one HTML/XML tag, automatically rename the paired HTML/XML tag`

**Comment by alxdhuang** [comment]
> 插件首页里基本都是英文，很多时候想了解学习，复制翻译一下是常用的做法。请问为什么不允许复制文本呢？选取是高亮的，说明已经选取。
> 
> 是出于一种安全原因吗？
> 
> 我觉得允许复制才是尊重用户学习的权利，不是所有的人都精通英文。这也是对非英语文化的一种尊重，非常感谢！
> 
> 注：编辑器发行说明里的文本是可以正常复制的。
> 
> 编辑器：vscode v1.33，vscode insider v1.34
> 操作系统：MacOS Mojave 10.14.4

这跟尊不尊重非英语文化没关吧？英语作为世界通用语言，是每一个程序员都应该掌握的，是我们互相交流的基础。

**Comment by rebornix** [comment]
For short, copy doesn't work in extension description page. I think it's a weview issue.

**Comment by zhliner** [comment]
@alxdhuang @Garfield550

so sorry,, I'm wrong  :(

thank you !

一时冲动，惭愧……

学习了 ^o^

**Comment by TTtuntuntutu** [comment]
那去vscode官网搜这个插件呗
