### ISSUE TITLE
[Feature request] Toggle collapse/expand widget

### ISSUE THREAD

**Issue by phmngocnghia** [Microsoft/vscode#72284]
![image](https://user-images.githubusercontent.com/36730355/56090928-9526c580-5ed2-11e9-9418-735ade146850.png)

I already try command list.expand and list.collapse but it's doesn't work

Please implement command hotkey to toggle foldable section: variables, watches,callstack. Its would be convienient to have them. 

Also its would be nice to have command that toggle index. eg
Toggle foldable section index 0 which is variables, index 2 which is calltack

And a command to collapse all of them

**Comment by isidorn** [comment]
This is regarding the split view, thus forwarding to @sandy081 
I think out of scope

**Comment by sandy081** [comment]
This can be done generic to all views but i see it is not a request that is often asked for. Hence closing it out of scope.

**Comment by phmngocnghia** [comment]
Hi @sandy081 , Could you help me by providing further technical informations, so I could implement on my own fork (E.g. which part of code should I take a look/update/analyze to get this implement). Would be nice if I could sumbit a PR to contribute for the project, or at least implement it for my self use.
