### ISSUE TITLE
Sidebar on right side doesn't align with Close button of the window on Windows

### ISSUE THREAD

**Issue by Garfield550** [Microsoft/vscode#72285]
- VSCode Version: 1.33.1
- OS Version: Microsoft Windows 10.0.17763

Steps to Reproduce:

1. `"workbench.sideBar.location": "right",`

2. ![Annotation 2019-04-14 175722](https://user-images.githubusercontent.com/3471836/56091278-99a5ab00-5edf-11e9-81ed-84984a3d67fc.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Garfield550** [comment]
👻

**Comment by sbatten** [comment]
This is by design. Widening the window controls to match the sidebar is only effective on this side (right sidebar) and would make them look less native.
