### ISSUE TITLE
Vscode directory Autocreation due to C/C++ Extension

### ISSUE THREAD

**Issue by manishtanwar** [Microsoft/vscode#72283]
Issue Type: <b>Bug</b>

In ubuntu 18.10, on installing C/C++ Extension or C++ Intellisense, every time a folder is added in workspace, it creates .vscode directory with 200MB per opened cpp file.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.18.0-17-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2356)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 1|
|Memory (System)|7.70GB (1.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-diff|fab|1.4.0
code-runner|for|0.9.8
material-icon-theme|PKi|3.7.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Please file the issue against the C++ extension.
