### ISSUE TITLE
Please optimazie search function

### ISSUE THREAD

**Issue by DOGSHITD** [Microsoft/vscode#72286]
Issue Type: <b>Feature Request</b>

Hi,

Could you please add support for these demands?
   1. searching key word for multi specific file type;
   2. UEFI file type: *.hfr,*.inf, *.vfr;

thanks!

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
I don't understand what you are asking for. Please include more specific details
