### ISSUE TITLE
vs code keeps crashing continuously after update 1.33 

### ISSUE THREAD

**Issue by cedverd** [Microsoft/vscode#72289]
Vs code Keeps crashing after 1.33 update. 
it keeps saying

> the window has crashed.

> We are sorry for inconvience ! You can reopen the window to continue where you left off. 

if I click reopen it again crashes.

![ see here](https://user-images.githubusercontent.com/28141633/56092608-cc4da480-5edb-11e9-91ce-aea082d24afb.png)

Does this issoue occur when all extensions are disabled?: its not even opening properly

**Comment by cedverd** [comment]
I reinstalled the vs code but the problem remains same

**Comment by jmbockhorst** [comment]
I am getting this same problem. For me, it happens when I switch back to the terminal after a certain amount of time.

**Comment by aeschli** [comment]
Can you run `code --status` when this happens?
What files did you work on?

**Comment by cedverd** [comment]
I was Working on Angular. Due to some issues I had to reset my os but now it's working fine

**Comment by PiotrPolewczak** [comment]
same issue after update to 1.33

Version:          Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS Version:       Windows_NT ia32 10.0.18362
CPUs:             Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)
Memory (System):  15.88GB (1.28GB free)
VM:               21%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       63   18904  code main
    0       61   23152     shared-process
    0       43   24760     gpu-process

Workspace Stats:
|  Window (main.cpp - esp8266_milight_hub - Visual Studio Code)
|    Folder (esp8266_milight_hub): 1377 files
|      File types: o(700) a(141) h(111) hpp(80) ino(75) cpp(73) md(26)
|                  json(18) txt(12) bin(12)
|      Conf files: makefile(4) launch.json(1) settings.json(1) gulp.js(1)
|                  package.json(1)

**Comment by mkhamat** [comment]
Same, I got crashes when I use WSL terminal I guess

**Comment by jrcasso** [comment]
Same here.
