### ISSUE TITLE
VSCode mp4 support or youtube video support

### ISSUE THREAD

**Issue by Edris89** [Microsoft/vscode#72280]
I know that vscode doesn't support mp4 or youtube videos
But is this feature ever gonna be implement?

Because a lot of the time I am watching a youtube tutorial and I am constantly switching from vscode to youtube..
Is there a way to?

**Comment by johndpope** [comment]
maybe just better support to open file - if i'm ssh'd - show a download button.
if it's local - show a open button / smack bang in middle of screen.

such an abrupt end to great ux. got to go into recovery mode - right mouse clicking / downloading....

<img width="1217" alt="Screen Shot 2021-08-21 at 03 05 22" src="https://user-images.githubusercontent.com/289994/130268950-94b6cd2c-f81a-49b9-a033-4873f4cfbc25.png">

**Comment by developomp** [comment]
vscode does support image preview, so I'm not sure why audio & video playback suggestions are labeled out of scope

**Comment by austinmw** [comment]
Any plans to reconsider this? Jupyter notebook tutorials often embed YouTube videos. This makes JupyterLab a better environment to run tutorial notebooks than VS Code.

**Comment by reinux** [comment]
I have scripts that render video which need to be further manipulated. Video support would be very useful.

**Comment by bouachalazhar** [comment]
> Would like to +1 this request, I work in computer vision and frequently need to quickly preview video files in VSCode, but must instead download the file from the remote server I'm working on, manually find it on my local filesystem, and view it from there. It would save me a lot of time if I could preview video files without leaving VSCode.

Hi ! Can you read .mp4 file on vs code or not ?

**Comment by JeffRockatansky** [comment]
In my VSCode installation (version 1.75.1) I could open an `.mp4` file, a new tab appears wih player controls, but the video doesn't start. Might be an encoding issue, but there is no info about which encodings are supported by VSCode.

**Comment by bouachalazhar** [comment]
> In my VSCode installation (version 1.75.1, `.deb`) I could open an `.mp4` file, a new tab appears wih player controls, but the video doesn't start. Might be an encoding issue, but there is no info about which encodings are supported by VSCode.

Check your codecs audio and video and look this link : [Supported Media](https://code.visualstudio.com/api/extension-guides/webview#supported-media-formats)
