### ISSUE TITLE
conda or pip packages installation starts late by about 2 to 3 minutes

### ISSUE THREAD

**Issue by sosam29** [Microsoft/vscode#72287]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sosam29** [comment]
Issue Type: <b>Performance Issue</b>

I am trying to install conda install -c ryanvolz libusb and it took almost 2 to 2 3min even to start resolving environment and start downloading and installing that library.

Just to be clear on that point , this happenes to all the conda and or pip installations I try at TERMINAL window.

May be my settings or System issue. I checked and AV was not doing scanning.

Any help would be great.

Thanks
~Sam

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.93GB (1.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    83	  7984	code main
    1	    65	 10136	   window (Issue Reporter)
    0	    65	 12828	   shared-process
    0	   159	 12964	   gpu-process
    2	   198	 13100	   window (playlistcomibine.py - captcha_breaker - Visual Studio Code [Administrator])
    0	    11	   664	     watcherService 
    0	     6	 11152	       console-window-host (Windows internal process)
    0	     6	  7664	     winpty-process
    0	     4	  8244	       C:\WINDOWS\System32\cmd.exe
    0	     9	  9324	       console-window-host (Windows internal process)
    0	     6	 11488	     winpty-process
    0	     8	 12892	       console-window-host (Windows internal process)
    0	     3	 13212	       C:\WINDOWS\System32\cmd.exe
    0	    32	 11736	     searchService
    0	    13	 12240	     electron-crash-reporter
    0	   142	 12768	     extensionHost
    0	    34	  6984	       C:\Users\Sam\.vscode\extensions\ms-vscode.csharp-1.18.0\.razor\rzls.exe -lsp --logLevel None
    0	     5	  7320	         console-window-host (Windows internal process)
    0	    32	  7420	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=12768
    0	    32	  9328	       electron_node tslintServer.js 
    0	    29	 11808	       C:\ProgramData\Anaconda3\python.exe completion.py
    0	     6	  2280	         console-window-host (Windows internal process)
    0	    19	 12368	         C:\ProgramData\Anaconda3\python.exe lib\python\jedi\evaluate\compiled\subprocess\__main__.py lib\python
    0	     6	  9228	           console-window-host (Windows internal process)
    0	     6	 13064	     winpty-process
    0	     8	  7684	       console-window-host (Windows internal process)
    0	     4	 11680	       C:\WINDOWS\System32\cmd.exe
    0	     2	  8912	         "C:\ProgramData\Anaconda3\Scripts\conda.exe"  install -c ryanvolz libusb
   24	   626	 12652	           C:\ProgramData\Anaconda3\python.exe "C:\ProgramData\Anaconda3\Scripts\conda-script.py" "install" "-c" "ryanvolz" "libusb"
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (playlistcomibine.py - captcha_breaker - Visual Studio Code [Administrator])
|    Folder (captcha_breaker): 8 files
|      File types: py(7) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
tslint|eg2|1.0.43
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
csharp|ms-|1.18.0
vscode-yaml|red|0.4.0


</details>

**Comment by aeschli** [comment]
How is it related to VSCode? Only happens when done in an integrated terminal?

**Comment by sosam29** [comment]
I have to test with anaconda prompt.  It used to get updated in vs code before 2 or 3 releases.  


Let me check and get back to you.  

Thanks
Sam

**Comment by aeschli** [comment]
Sorry, I don't know what the anaconda prompt is. Please add more information, also screenshots can help.
If it is functionality provided by an extension, you might want to file the issue against that extension.

**Comment by jrieken** [comment]
closing because this issue is without actionable information
