### ISSUE TITLE
VSCode showing wrong file icon in windows explorer

### ISSUE THREAD

**Issue by Summon528** [microsoft/vscode#72290]
- VSCode Version: 1.33.1
- OS Version: Windows 10.0.17763.379 & 10.0.18362.53

Steps to Reproduce:

1. Double click a file while before any app was registered to open it.
2. "How do you want to open this file" pops, select VS code.
The file is now showing the general file icon.
3. Right click file ->properties -> open with -> change -> VS code
The file is now showing a totally wrong icon

expected result: showing this [icon](https://raw.githubusercontent.com/Microsoft/vscode/master/resources/win32/markdown.ico)

Repro video in VM: https://gfycat.com/qualifiedglasshornshark

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I do not see a way for us to fix this.
