### ISSUE TITLE
getColumnAtBeginningOfLine cursorHome keybinding behavior

### ISSUE THREAD

**Issue by joenoon** [microsoft/vscode#7229]
`getColumnAtBeginningOfLine` feels very strange to me:
https://github.com/Microsoft/vscode/blob/875e28c7ce42aec6922f45676cc5b7f9a20e5f91/src/vs/editor/common/controller/cursorMoveHelper.ts#L196

The experience is when using keybindings that call `cursorHome` (which calls `getColumnAtBeginningOfLine`), I expect to go to the beginning of the line, but what happens is I end up at the first non-whitespace position OR the beginning, depending on where I last was (it alternates).

To me, this makes certain things more difficult.  For example clean multi-line selection/cut/paste using the keyboard becomes tedious when the selection accidentally starts indented rather than at col 1.
- Is there a simple fix I can just make in my keybindings? **(Preferred, but I couldn't figure out a way)**
- If not, should there be a new "cursorCol1" command or similar?
- Or should the getColumnAtBeginningOfLine just be avoided and always return 1?
- Or is there wisdom behind the way it works that I'm missing?

**Comment by alexandrudima** [comment]
IMHO this behaviour is useful by default, but I agree, we should add a new command that always goes to column 1, such that it can be easily replaced via keybindings.

Some editors distinguish and call this a **soft** start of line vs a **hard** start of line.
