### ISSUE TITLE
Three Dots in Source Control is not working properly

### ISSUE THREAD

**Issue by kameshkotwani** [Microsoft/vscode#72297]
Issue Type: <b>Bug</b>

When clicking on the three dots in source control menu the drop down list in not freezing, rather it is automatically choosing the first item even with a single click. i.e pull request. This is happening in my Desktop too.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (4.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.28
es7-react-js-snippets|dsz|2.2.1
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
bootstrap-4-cdn-snippet|eve|1.1.8
macros|ged|1.2.1
bing-search|kam|0.0.1
google-search|kam|0.0.1
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
vsliveshare|ms-|1.0.45
material-icon-theme|PKi|3.7.0
java|red|0.42.1
LiveServer|rit|5.5.1
shell-launcher|Tyr|0.3.0
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you share a screen recording of that?

**Comment by kameshkotwani** [comment]
![2019-04-16_22-01-48](https://user-images.githubusercontent.com/36355951/56227519-4c6a3a80-6093-11e9-8c3b-090be1c87de1.gif)

**Comment by joaomoreno** [comment]
#65787
