### ISSUE TITLE
VSCode should be aware it might have been called via electron binary

### ISSUE THREAD

**Issue by FFY00** [microsoft/vscode#72298]
Related to #56686

When we start the app using the electron binary, vscode isn't able to properly spawn other instances of itself. This happens because it just uses the binary file to spawn the new session, not taking into account that it might have been started using the electron binary. Vscode just needs to take that into account, it should only add a few lines to the code at most.

**Comment by bpasero** [comment]
//cc @joaomoreno

**Comment by FFY00** [comment]
Any news?

**Comment by FFY00** [comment]
BUMP

This really shouldn't be a hard fix, I would send a PR myself but I am not very acquainted with the electron codebase.

**Comment by Tyriar** [comment]
If you can find the lines that need to be changed we will consider it provided it doesn't harm our development flow, but this is basically the same issue as https://github.com/microsoft/vscode/issues/56686 which was closed as out of scope.
