### ISSUE TITLE
intellisense stops working

### ISSUE THREAD

**Issue by WDever** [Microsoft/vscode#72294]
- VSCode Version: 1.33.1
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. open a react component that is using styled-components.
2. try to use intellisense or autoComplete with 'Tab' Key.

Does this issue occur when all extensions are disabled?: Yes

I'm using styled-components with tsx. when I open a tsx file that us using styled-components, intellisense or autoComplete doesn't work. But when I open a tsx file that is not using styled-components, it work really good.

**Comment by rolandleth** [comment]
I have issues with `jsx` files too. Latest version is unusable for me, I have to keep falling back on `1.32`.

**Comment by WDever** [comment]
> I have issues with `jsx` files too. Latest version is unusable for me, I have to keep falling back on `1.32`.

I think it can resolve. if your styled-components's version is lower than 4.2.0, you have to upgrade it.

In my case, I upgrade styled-components and it was fixed.

But, my intellisense is slowed down.

**Comment by rolandleth** [comment]
That's not it, I have `4.2.0` 😞.

**Comment by WDever** [comment]
> That's not it, I have `4.2.0` 😞.

I'm sorry to hear that 😢.

I don't have idea with this problem

**Comment by mjbvz** [comment]
What version of `@types/styled-components` do you have installed?

**Comment by WDever** [comment]
> What version of `@types/styled-components` do you have installed?

when I found the problem, it's version is 4.1.12.

But now it is 4.1.14.

**Comment by mjbvz** [comment]
Sounds like https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391

Are still seeing this issue with the latest typings?

**Comment by rolandleth** [comment]
I updated `typescript` to `3.5.0-dev.20190413` and now it appears to be working correctly.

**Comment by WDever** [comment]
> Sounds like [DefinitelyTyped/DefinitelyTyped#34391](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391)
> 
> Are still seeing this issue with the latest typings?

No. After I upgrade @types/styled-components, intellisense started to work.

But, It is slower than 1.32.3. It takes long time.

**Comment by WDever** [comment]
> I updated `typescript` to `3.5.0-dev.20190413` and now it appears to be working correctly.
> 
> Edit: It is better indeed, but still substantially slower than on `1.32.3` 😞.

I'm using typescipt 3.4.3.. But you have a problem like me.

**Comment by WDever** [comment]
I heard that this issue is typescript's issue.

when I'm using typescript 3.3.3333, it solves. THX
