### ISSUE TITLE
vscode can not format "pug" files

### ISSUE THREAD

**Issue by johnsky007** [Microsoft/vscode#72295]
I use latest vscode version 1.33.1 in ubuntu 18.10, I want to be able format the "pug" template file in the editor, editor hints "There is no formatter for 'jade'-files installed" and when I try to install "sujs" for formatting pug file, editor repeat above hint again, I tried "Pug beautify" extension but can not resolve the problem and actually does not work! It seems that there are no extension available to formatting of pug files

**Comment by aeschli** [comment]
Sorry, we have no plans to add a pug formatter as a built-in extension to VSCode.

Maybe file a file a issue against "Pug beautify" to provide their beautifier a proper formatter, so it can be used with the regular `Format Document` commands?
