### ISSUE TITLE
Python: <class 'RuntimeError'>: generator raised StopIteration

### ISSUE THREAD

**Issue by IamManchanda** [Microsoft/vscode#72291]
- VSCode Version: 1.33.1
- OS Version: MacOS Mojave 10.14.4
- pylint Version: 2.3.1
- astroid Version: 2.2.5
- Python Version: 3.7.3

Steps to Reproduce:

<img width="688" alt="Screenshot 2019-04-14 at 7 09 54 PM" src="https://user-images.githubusercontent.com/4970624/56093656-0f624480-5ee9-11e9-8df3-12a6fe28a219.png">
<img width="853" alt="Screenshot 2019-04-14 at 7 10 03 PM" src="https://user-images.githubusercontent.com/4970624/56093657-0ffadb00-5ee9-11e9-8fd5-54f21761848a.png">

**Comment by aeschli** [comment]
Please file this against the Python extension.
