### ISSUE TITLE
Extend existing extension with both configuration and grammar

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [Microsoft/vscode#72300]
In our case we'd like to extend HTML syntax with [Django](https://www.djangoproject.com) tags (like `{% url 'hello' %}` stuff), snippets and so on.

However, [docs](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#developing-a-new-grammar-extension) remind us that 

> _if you are contributing a grammar to a language that VS Code already knows about, be sure to delete the languages contribution point in the generated package.json_

So an extension like [vscode-django](https://github.com/vscode-django/vscode-django) ends up overriding the internal HTML extension and [HTML IntelliSense no longer works](https://github.com/vscode-django/vscode-django/issues/16).

So how can we extend an existing grammar with language configuration? Do we have to start from a fork of the HTML extension?

**Comment by aeschli** [comment]
While at a glance it looks like Django files are like HTML, the Django syntax is not pure/strict HTML.

So the correct way is for Django to define it's own language id, and also to implement it's own language server for features like intellisense, hovers etc.

While cleraly that is not trivial, it ill lead to a better end result. We provide libraries for setting up an LSP server (https://github.com/Microsoft/vscode-languageserver-node) as well as a library that lets you reuse all the HTML smartness (https://github.com/Microsoft/vscode-hml-languageservice).

**Comment by aeschli** [comment]
But we are aware that it would be nice to have a simpler solution for templating languages:
https://github.com/Microsoft/vscode/issues/49210
