### ISSUE TITLE
format on save causes build dir EPERM issue when running npm run build

### ISSUE THREAD

**Issue by Suhail** [Microsoft/vscode#72305]
- VSCode Version: 1.33.1
- OS Version: Windows 10 x64 (Server 2019)
Node.js: 10.2.0

Steps to Reproduce:

1. Use formatOnSave
2. Open a project dir where you might see a build folder in it too
3. Run npm run build

You'll get this error: `gyp ERR! stack Error: EPERM: operation not permitted, mkdir 'C:\Users\Administrator\endec\build'`

Does this issue occur when all extensions are disabled?: yes

**Comment by Suhail** [comment]
Temporary solution was to add this and ignore the build dir entirely
```
"files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/build/**": true
  },
```

**Comment by Suhail** [comment]
Seems like an issue with the prettier extension

**Comment by aeschli** [comment]
If it's prettier, please file the issue against the prettier extension.
