### ISSUE TITLE
Menu bar goes black

### ISSUE THREAD

**Issue by biswajit-paul** [microsoft/vscode#72302]
Issue Type: <b>Bug</b>

VSCode works abnormally when I continue running more than 6+ hours. Sometimes formatting not work, sometime menu bar goes black.

Screenshot: https://snag.gy/wOa17b.jpg

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.18.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3388)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.63GB (5.31GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
githd|hui|2.1.0
path-autocomplete|ion|1.13.2
sftp|lix|1.12.2
ecdc|mit|1.0.5
vscode-apache|mrm|1.2.0
php-docblocker|nei|1.8.0
highlight-matching-tag|vin|0.9.1
twig|wha|1.0.2
better-align|wwm|1.1.6

</details>

**Comment by aeschli** [comment]
When that happens, can you run `code --status` from time to time to observe the memory usage or process time?

**Comment by jmcclin2** [comment]
I have a similar issue when running v1.33.1 in Virtual Box, Mint Linux 64-bit v19.1.  I only have the C++ extension installed.  Once I run the debugger and exit, all the menu bar remains correctly rendered, but all of the drop down menus are black as shown in the picture biswajit-paul posted.  I can click where the commands would be and they execute (in the drop down menus) but I have not been able to get the menus to render again without restarting VS Code.  Only happen for me once the debugger is executed.

**Comment by jrieken** [comment]
I don't think that this is a perf issue but I think its a menu issue

**Comment by sbatten** [comment]
likely an electron issue. especially in the VM case.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by biswajit-paul** [comment]
@bpasero I installed Windows version. I see no difference without the blue app icon. Looks like an insider preview. I do not have intention to continue with 2 separate installations with same extensions. It takes much space bro.

**Comment by sbatten** [comment]
@biswajit-paul Did the exploration version fix the issue you reported or you are still seeing the issue?
