### ISSUE TITLE
Cannot open file/folder

### ISSUE THREAD

**Issue by MinecraftPlaye** [microsoft/vscode#72303]
- VSCode Version: 1.33.1
- OS Version: Linux x64 5.0.6-arch1-1-ARCH

`xdg-mime query default inode/directory` -> `pcmanfm.desktop`
`cat usr/share/applications/mimeinfo.cache | grep inode/directory` -> `inode/directory=pcmanfm.desktop;ranger.desktop;`

System:
> 5.0.6-arch1-1-ARCH
> GDB 8.2.1
> gcc 8.2.1 20181127
> pcmanfm 1.3.1-1
> ranger 1.9.2-1
> i3-gaps 4.16.1-1

Visual Studio Code:
> VSCode Version: 1.33.1
> Date: 2019-04-12T08:59:47.459Z
> Electron: 4.1.4
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.30-electron.0

Steps to Reproduce:

1. Click on File.
2. Then click on `Open File`, `Open Folder` or `Open Workspace`.
3. See the white window.
![photo_2019-04-14_21-10-18](https://user-images.githubusercontent.com/9168045/56097839-bfd84480-5ef9-11e9-8703-64c370d28461.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by MinecraftPlaye** [comment]
> 
> 
> We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
>     * macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
> 
>     * Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
> 
>     * Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

Isn't .deb for Debian based Linux systems as I'm using Arch Linux.

**Comment by MinecraftPlaye** [comment]
Ok, I downloaded code-git-1.16.0.r25594.ga31dcc38f2-1 from AUR today and the problem still persists.

**Comment by bpasero** [comment]
@MinecraftPlaye here is a ZIP: https://az764295.vo.msecnd.net/exploration/d3efc180606a1eaa4e8d51e5a9099013ce31518f/code-exploration-1555986884.tar.gz

**Comment by MinecraftPlaye** [comment]
> @MinecraftPlaye here is a ZIP: https://az764295.vo.msecnd.net/exploration/d3efc180606a1eaa4e8d51e5a9099013ce31518f/code-exploration-1555986884.tar.gz

Sadly this did not fix it for me. Thought I noticed that this problem also exists in Firefox.

> locate filechooser
> /usr/include/gtk-2.0/gtk/gtkfilechooser.h
> /usr/include/gtk-2.0/gtk/gtkfilechooserbutton.h
> /usr/include/gtk-2.0/gtk/gtkfilechooserdialog.h
> /usr/include/gtk-2.0/gtk/gtkfilechooserwidget.h
> /usr/include/gtk-3.0/gtk/gtkfilechooser.h
> /usr/include/gtk-3.0/gtk/gtkfilechooserbutton.h
> /usr/include/gtk-3.0/gtk/gtkfilechooserdialog.h
> /usr/include/gtk-3.0/gtk/gtkfilechoosernative.h
> /usr/include/gtk-3.0/gtk/gtkfilechooserwidget.h
> /usr/share/gtk-doc/html/gtk3/filechooser.png

**Comment by MinecraftPlaye** [comment]
Ok, I figured out that the problem is caused by scaling my desktop (as I'm using an HiDPI display).

This problem also affected only GTK and thus applications like Firefox. Qt application were not affected and worked fine with scaling.
