### ISSUE TITLE
it doesn't prettify react native code all the time

### ISSUE THREAD

**Issue by hridoy43** [Microsoft/vscode#72306]
Issue Type: <b>Bug</b>

sometimes when I press ctrl+s, then react-native's code get breaks. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
smali|cra|1.0.1
vscode-eslint|dba|1.8.2
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.8.1
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.8
beautify|Hoo|1.4.11
fontawesome-autocomplete|Jan|0.1.7
LiveServer|rit|5.5.1
indenticator|Sir|0.6.0
ayu|tea|0.18.0
vscode-react-native|vsm|0.9.1
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
In what type of file is that?

Which formatter is used? If it is _prettier_, please file the issue against the extension.

**Comment by jrieken** [comment]
closing because this issue is without actionable information
