### ISSUE TITLE
Commit length warning hides changed files

### ISSUE THREAD

**Issue by kaykayehnn** [Microsoft/vscode#72304]
Issue Type: <b>Bug</b>

When writing a commit message in the source control view, the commit length warning is positioned over the list of changed files. In case of a very narrow commit tab, the warning spans two lines and hides the first entry in the list of changes. This can be somewhat confusing if there is only one file changed in the commit.

Here are some screenshots which help illustrate the problem

![image](https://user-images.githubusercontent.com/19822240/56097663-25c7ca80-5f00-11e9-9afb-a785a4861e45.png)
![image](https://user-images.githubusercontent.com/19822240/56097674-4d1e9780-5f00-11e9-89a8-c8281af2df0e.png)

Steps to Reproduce:

1. Change a file in a source controlled directory
2. Type a long commit message

VS Code version: Code - Insiders 1.34.0-insider (b7c5e104a44b65e937408a10cbb8b49d6dfd19bf, 2019-04-12T11:12:09.412Z)
OS version: Darwin x64 18.5.0

Does this issue occur when all extensions are disabled?: Yes

**Comment by kaykayehnn** [comment]
The same issue occurs in the search tab when there are more than 10000 results and the input field is focused.

![image](https://user-images.githubusercontent.com/19822240/56148820-cb884180-5fb3-11e9-9627-e0851cbb38d4.png)
![image](https://user-images.githubusercontent.com/19822240/56148494-1190d580-5fb3-11e9-816f-f95548f19b4a.png)

**Comment by joaomoreno** [comment]
Closing as designed. This box is ephemeral and goes away as soon as you focus out of the input.
