### ISSUE TITLE
Debug console window formatting : missing leading spaces

### ISSUE THREAD

**Issue by koutsenko** [Microsoft/vscode#7230]
- VSCode Version: 1.1.1
- OS Version: Win10 x64

Steps to Reproduce:

1. Write NodeJS server that uses console.log to logging purposes
2. Format output, I use `JSON.stringify(packet, null, 2)`
3. Start debugging, output will go to "debug console" (in ru_RU translation it is 'консоль отладки')

Problem is that all leading spaces (between line start and formatted text) are missing.
So if I want to see readable JSON structs, I must run server in OS native shell...

**Comment by isidorn** [comment]
This should be fixed in vscode version 1.2 - please download the latest version and let us know if the problem still persits
