### ISSUE TITLE
debug with nodemon,when close vscode,nodemon still running

### ISSUE THREAD

**Issue by lerit** [microsoft/vscode#72312]
- VSCode Version:1.32.3
- OS Version:ubuntu 18.04

Steps to Reproduce:

1.set launch.json to debug nodejs with nodemon
launch.json:
```
    {
      "name": "Node Debug",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
      "args": [
        "--config",
        "${workspaceRoot}/nodemon.json",
        "dist/server/index.js"
      ],
      "sourceMaps": true,
      "restart": true,
      "console": "integratedTerminal", 
      "timeout": 15000,
      "internalConsoleOptions": "neverOpen",
      "skipFiles": ["<node_internals>/**", "node_modules/**"],
      "smartStep": true
    }
```
nodemon.json
```
{
  "verbose": true,
  "execMap": {
    "js": "node --harmony --trace-warnings"
  },
  "env": {
    "NODE_ENV": "development"
  },
  "watch": ["dist/server/index.js", "config"],
  "script": "dist/server/index.js"
}
```
2.press f5 to start debug
3.close vscode
4.when vscode close,i am sure that nodemon still running and start a new nodejs instance(by use command:top ,a new process named node start with high cpu 100%),i can only close this node process withcommand: pkill node

Does this issue occur when all extensions are disabled?: Yes

can vscode kill runtimeExecutable when it close,or can i use other methods to kill nodemon?

**Comment by lerit** [comment]
still a problem,i think because runtimeExecutable can not be kill when close vscode or stop debug
@weinand 
is this any method to stop runtimeExecutable program?

**Comment by lerit** [comment]
i think same issue #87321

**Comment by faabiopontes** [comment]
It just happened to me.. I can't believe VS Code doesn't close it's terminal after closing the program

**Comment by connor4312** [comment]
Should be fixed with https://github.com/microsoft/vscode/issues/108289

/duplicate
