### ISSUE TITLE
Multiple formatters from the same extension cause choices for default formatter to be not helpful

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#72315]
The `vscode-go` extension gives language server support for the user to opt-in to.
Using settings, we allow user to pick and choose the features they would want to use language server for. 

For example, a user can choose to use the language server, but choose not to use its formatting features.

The way we accomplish this is by having the extension register a formatting provider and use [middleware to ignore formatting results from language server.
](https://github.com/Microsoft/vscode-go/blob/0.9.2/src/goMain.ts#L125-L130)
This results in 2 formatters for the extension. VS Code prompts the user to select the default formatter which results in the below:

<img width="818" alt="Screen Shot 2019-04-14 at 11 05 18 PM" src="https://user-images.githubusercontent.com/16890566/56110546-c8d11200-5f09-11e9-8d03-3c798b408c2c.png">

It confuses users to see both options with the same name.
If they choose the one that is meant for language server, then they won't get any formatting edits.

_Proposed solution:_
If one of the registered providers returns empty results, do not consider it as one of the multiple formatters and thus avoid the prompt to select the default provider.

**Comment by jrieken** [comment]
> extension register a formatting provider and use middleware to ignore formatting results from language server.

That's the problem, you should not register two providers and ignore one because that's not how the integration works. Calling register does something, like updating the UI et al, and that's nothing to be toyed with. Your proposed solution doesn't work because the picker comes *before* calling a formatter. 

You extension should have default values and honour that, e.g register formatter A only, on setting change unregister A, register B etc

**Comment by ramya-rao-a** [comment]
Thanks @jrieken 

To unregister a registered provider, do we just call `dispose` on what is returned by the `vscode.languages.register....Provider()` ?

**Comment by jrieken** [comment]
yes, `dispose` is all you need

**Comment by ramya-rao-a** [comment]
And is there a way to unregister the provider from the language server?

**Comment by jrieken** [comment]
sure, see this: https://github.com/Microsoft/vscode/issues/70314#issuecomment-472336416
