### ISSUE TITLE
[json] JSON Schema fail to validate 'multipleOf' for some values

### ISSUE THREAD

**Issue by john5f35** [microsoft/vscode#72314]
Report Issue to prefill these.
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. save the following as test `schema.json`:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "num": {
            "type": "number",
            "multipleOf": 0.1
        }
    }
}
```

2. define a `test.json`:
```json
{
   "num": 0.7
}
```

3. set settings to let VSCode load schema for `test.json`:
```json
{
    "json.schemas": [
        {
            "fileMatch": [
                "/test.json"
            ],
            "url": "file:///path/to/schema.json"
        },
    ]
}
```

Then you will see green squiggles under `0.7`, and output problems shows `Value is not devisible by 0.1`. Integer values like `3` also fails. 

However some other values like `0.8` is fine.

**Comment by KapitanOczywisty** [comment]
We could improve this, but I don't think this could be fixed completely. Floats are rather non-precise by nature.

Take: https://github.com/microsoft/vscode-json-languageservice/blob/2bf9ebf5b7752389ff9c7a0da199a5694a53b063/src/parser/jsonParser.ts#L561-L562
Replace with:
```js
		if (isNumber(schema.multipleOf)) {
			const remainder = Number.isInteger(val)
				? val % schema.multipleOf
				: Math.round(val / schema.multipleOf * 1000) % 1000
			if (remainder !== 0) {
```

This will help in most cases, but in some will still fail, e.g. `val`: 1.99999 , `multipleOf`: 0.1. Constant `1000` changes how precise we could go before it fails. I'm not sure if this is sufficient solution to implement. @aeschli ?

**Comment by aeschli** [comment]
Maybe we turn `0.1` into a non-fractional integer first. We need to count the digits behind the dot to find the multiplicand that does that (10 in this case).

Then use the multiplicand also on the value to test.

**Comment by KapitanOczywisty** [comment]
@aeschli I've made something like that and It seems to be working, but I'm pretty sure there will be some edge cases. Provided test code:

```ts
const isMultipleOf = function (val: number, multipleOf: number) {
  let remainder: number = 0;
  if (Number.isInteger(multipleOf)) {
    remainder = val % multipleOf;
  } else {
    const parts = /^\d+(?:\.(\d+))?(?:e-(\d+))?$/.exec(multipleOf.toString());
    if (parts) {
      const multiplier =
        10 ** ((parts[1]?.length || 0) + (parseInt(parts[2]) || 1));
      // console.log(parts, multiplier);
      remainder = (val * multiplier) % (multipleOf * multiplier);
    } else {
      console.error("Invlaid number", multipleOf, multipleOf.toString());
    }
  }
  console.log(multipleOf, val, remainder === 0, remainder);
};

console.clear();
isMultipleOf(0.01, 0.1);
isMultipleOf(0.1, 0.1);
isMultipleOf(2.1, 0.1);
isMultipleOf(0.0000001, 0.01);
isMultipleOf(0.01, 0.0000001);
isMultipleOf(0.064, 0.00000032);
isMultipleOf(0.034, 0.00000033);
isMultipleOf(0.099, 0.0000000000099);
```

[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlhAsgVwDZTgB1QUwPIBmMAvDAcmMBuDABQBuAhqgFwxjIC2ARjgE4AaGJzQZs+Amw49+AShgBvAFAwYuWHxydGcMABN+Urrz4kYABgDcK+EVoA5Y-wB0CAJJgoOAOb9aI9CxcQll5ZVVVTW1dA1NSJlQYAFJhUSCJa1UAXxgcVAgcRRtVUEhYTEY+KAgzAHoAPQAdPQBqWgB+FkbnWmaW0PaOlhwAWl7WgYASWuccAA8cYH808UJnKBAAZSg+XW9aUMyIuDsKqogw4ojS6FTA7Dh+EiuImABGcxgAKi+6WjPqgBtN4AXXazlwYG8UAAFjAAD7wizyFp0M4FDxQf6VIEAJhB8kR70OLxgtVqMBuIFwEJA+wBECEATEqEefFkR1eUR0+iepAYzG+dxZbPkKWW92CRF+zKCos5MByeQKRVeJXAEGpOFmfD4ID4tAARB56KgdHp2E4+IamSspbbJRJ1lsdnsDhyrlkbF71ZAtbT9rLVgQhAkhNyYnziKRzOGtDzYh6stYlFSacBcJUDtYEChHYRaOZnOY3kIi28Pbm7RJC85SxY65WkNWC7i62XGznm-mCLXzP2B-WiyWm3mWTXh0PiwP+xWu2P0gXhwA2AAsHZn-YAzLjRy3e8Ot+uG5vzFut3ue32AJzXjenme3j1AA)
