### ISSUE TITLE
Relative Paths do not work

### ISSUE THREAD

**Issue by Ted-Lalakas** [Microsoft/vscode#72311]
Issue Type: <b>Bug</b>

When working on a project in Linux. CTRL+Click a file will always result in an error the file cannot be found because the path to the file is always incorrect.

Using a path for my SCSS file such as this: 

@import "../../../../../themes/contrib/sass/theme/_mixins/form",
        "../../../../../themes/contrib/sass/theme/_mixins/leaders",
        "../../../../../themes/contrib/sass/theme/_mixins/teaser-image";

These paths do not work. The error message says that for form:
Unable to open 'form': File not found
(file:///home/[user]/Projects/[sitename]/[the rest of the file structure is correct]

the home/user/ path is a problem and I can't find anywhere to removed this.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2310)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.50GB (0.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
drupal-8-snippets|dss|0.0.2
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.7.0
ayu|tea|0.18.0
drupal-8-javascript-snippets|tse|0.0.2
drupal-8-twig-snippets|tse|1.0.2

</details>

**Comment by octref** [comment]
You might want to file an issue against https://github.com/mrmlnc/vscode-scss.
