### ISSUE TITLE
[question] Does editor have API to expose markers?

### ISSUE THREAD

**Issue by Bigbrd** [Microsoft/vscode#7232]
I want to programmatically populate a list of errors from the editor. These markers are present as they are highlighted in the editor, but is there an API that I can call to get all the markers and access these errors/warnings programmatically?

Thanks in advance!

**Comment by jrieken** [comment]
You can create markers using a [`DiagnosticsCollection`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3471) which also allows for reading.

**Comment by ptyork** [comment]
@jrieken, is there a way to access the editor's "master" `DiagnosticCollection`? In other words, all `Diagnostic` objects created by all providers? Note that this would be for the browser-hosted monaco-editor, not VSCode. Just a read-only, forEach iteration is all I would need, ideally perhaps with an onDidChange notification.

Thanks.

**Comment by jrieken** [comment]
No that not possible in neither API tho there are ideas about adding it to VS Code. Note that the editor api different from the VS Code api. If we add that for VS Code extensions it doesn't mean the editor has it. Under the hood both use a `IMarkerService` which encapsulated the functionality. When creating the editor you can pass your own implementation of that.

**Comment by ptyork** [comment]
Thanks for the reply. So you're saying I could create my own class that implements `IMarkerService` (presumably wrapping the default one) and pass that in to `create()` using a configuration object like `{ markerService: myMarkerService }`? Definitely doable, but I worry about tightly coupling with internal code.

Can I request an enhancement that adds this capability (enumerating markers or diagnostics) to the public editor API? Or I guess specifically that it ALSO be added to the standalone editor if that is being worked on?

**Comment by jrieken** [comment]
The request is fair, tho this isn't the right repo for it ;-) Pls log it here: https://github.com/Microsoft/monaco-editor. For the editor side we are looking very much forward to receive pull request ;-) So, analog to [setModelMarkers](https://github.com/Microsoft/vscode/blob/master/src/vs/monaco.d.ts#L780) you could do a PR for something like `getModelMarkers`. It's more or less partially exposing [this](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/markers.ts#L25)

**Comment by ptyork** [comment]
Haha, actually I already have an issue in that repo (https://github.com/Microsoft/monaco-editor/issues/30), but it has gone unanswered. Saw in the readme that monaco-editor-core was here, found this issue and posted here figuring my original issue was in the wrong place. I'm obviously very confused, but what's new. :)

I'll look into doing a PR. Thanks again.

**Comment by jrieken** [comment]
>  I'm obviously very confused,

Ask me about it - there so many MSFT repos on GH
