### ISSUE TITLE
wrong licence mentioned on snapcraft.io

### ISSUE THREAD

**Issue by lhpitn** [Microsoft/vscode#72328]
Hi,

on the snap repository ( https://snapcraft.io/code ) the vscode licence is mentioned as Proprietary, but isnt it the MIT FOSS licence?

greetings

**Comment by khoitd1997** [comment]
Hi, I think that while the source code is open source, the final packaging will have Microsoft proprietary license, check out [this issue](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005) for more info on this.
