### ISSUE TITLE
Selection moves incorrectly during a format operation

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#72321]
Here's a formatter that simply removes duplicate newlines:

```ts
{
	async provideDocumentFormattingEdits(document: TextDocument, options, token): Promise<TextEdit[]> {
		const origText = document.getText();
		return [
			new TextEdit(
				new Range(new Position(0, 0), document.positionAt(origText.length)),
				origText.replace(/\n{2,}/g, '\n'),
			),
		];
	},
}
```

When running the formatter, the selection is not preserved as you would expect.

Before format:

![Screenshot 2019-04-15 at 8 46 51 am](https://user-images.githubusercontent.com/1078012/56115316-07db8380-5f5b-11e9-9980-7f5f5bee5e4e.png)

After format:

![Screenshot 2019-04-15 at 8 47 08 am](https://user-images.githubusercontent.com/1078012/56115338-12961880-5f5b-11e9-9ac1-3c3942ddec59.png)

My understanding is that VS Code constructs a minimal edit for the format (since I just gave it a full replace) so there should be no loss of cursor position for an edit like this.

I've published a repo of a VS code extension containing an extension with the code above, as well as a folder (`folder_to_open`) with the same file in it here:

https://github.com/DanTup/vscode-repro-format-selection

To repro:

- Clone that repo
- Open the root of that repo in VS Code and run the extension by pressing F5
- In the Dev host, open the `folder to open` folder from the cloned repo
- Open the `file.foo` file
- Put the cursor somewhere, for example select the word `DragStartBehavior` on line 17
- Invoke Format Document (format-on-save works too)
- Note that the selection is not the same

Repros in both stable and Insiders 3d67364fbfcf676d93be64f949e9b33e7f1b969e (2019-04-15T05:07:01.672Z). The only extensions I have installed (none of which supply formatters for `foo` files) are:

- Dart
- Debugger for Chrome
- Flutter
- TSLint

No errors/warnings appear in the dev tools when this happens.

I cannot find any duplicate open issues in the tracker.

**Comment by jrieken** [comment]
> My understanding is that VS Code constructs a minimal edit for the format (since I just gave it a full replace) so there should be no loss of cursor position for an edit like this.

That's the wrong understanding. The API expects an array of text edits. A single-element-array fulfils that contract but still misses the point and "good" formatters return fine grained edits. 

However, we have acknowledged that extensions return single-element-arrays and we try to make up for it by producing more minimal edits. That approach sometimes works well and sometimes doesn't work well. There is will we can/will do here. Internally the editor keeps markers for things like selection start/end, squiggles, highlight decorations etc. With "crazy" edits these markers can collapse, collide, or intersect in non-expected ways and that will yield in unexpected selections etc. You are invited to improve how markers work but I would suggest you spend time in making the formatter better, e.g. make the formatter return "good" edits. 

cc @alexandrudima

**Comment by DanTup** [comment]
> That's the wrong understanding. The API expects an array of text edits. A single-element-array fulfils that contract but still misses the point and "good" formatters return fine grained edits.

Sorry - that was my understanding I just didn't explain it very well.

> With "crazy" edits these markers can collapse, collide, or intersect in non-expected ways and that will yield in unexpected selections etc

There are definitely no "crazy edits" here. The formatter is removing some newlines, nothing more. VS Code was specifically updated up to handle this type of edit in https://github.com/Microsoft/vscode/issues/10133 which describes the same issue. The differences between the before/after are some very trivial whitespace changes, and yet the selection is left at the same offset that it was before and not moved at all.

> I would suggest you spend time in making the formatter better, e.g. make the formatter return "good" edits.

I'd love like to improve the Dart formatting edits but that's a bigger task (the formatting is not done by the VS Code extension but requires work in the SDK). Given VS Code goes out of its way to handle this, it seems weird that it doesn't work for the most basic of edits though.

**Comment by jrieken** [comment]
> There are definitely no "crazy edits" here. The formatter is removing some newlines, nothing more

Sorry, that's not true. The formatter replaces all of the text which makes us run the edit through a diff algorithm trying to produce more minimal edits. The outcome is what I call crazy edits. If you fix your formatter to do this (below) than everything works as expected. 

```ts
async provideDocumentFormattingEdits(document: vscode.TextDocument, options, token): Promise<vscode.TextEdit[]> {
            // const origText = document.getText();
            // return [
            //     new vscode.TextEdit(
            //         new Range(new Position(0, 0), document.positionAt(origText.length)),
            //         origText.replace(/\n{2,}/g, '\n'),
            //     ),
            // ];
            const result: vscode.TextEdit[] = [];
            const origText = document.getText();
            let index: number = 0;
            while ((index = origText.indexOf('\n\n', index)) !== -1) {
                result.push(vscode.TextEdit.delete(new vscode.Range(document.positionAt(index), document.positionAt(index + 2))));
                index += 2;
            }
            return result;
        }
```

#10133 is a workaround that we added and you are invited to improve the diff'ing or the marker logic but this is a case of unexpected/bad API usage and we don't have a perfect way to handle this. You will always find a way in which this goes south and I recommend you spend your energy on the formatter instead.

**Comment by DanTup** [comment]
@jrieken I understand replacing the text is sub-optimal, but it's all we have today (and from what I've seen in the issue tracker, Dart is not the only language with this limitation). I agree we should improve it.

But, I don't understand why it isn't handling this simple case - I don't know how it works, but the changes being made seem like they should be easy to compute the edits from. They're not only whitespace, but only blank lines being removed.

If you can point me in the direction of the code that does this and its tests, I don't mind doing some digging to see if I can understand why it's falling down.

**Comment by jrieken** [comment]
This is the place in which edits are made more minimal: https://github.com/Microsoft/vscode/blob/23fd99b493979a5b3778dc239d7eea46bf249f16/src/vs/editor/common/services/editorSimpleWorker.ts#L404. The code runs inside a web worker in is invoked from [here](https://github.com/Microsoft/vscode/blob/23fd99b493979a5b3778dc239d7eea46bf249f16/src/vs/editor/contrib/format/format.ts#L246)

**Comment by DanTup** [comment]
@jrieken I tracked this down to `BaseEditorSimpleWorker._diffLimit`. There's currently a hard-coded limit of 10,000 characters for either string which results in the diff being skipped. The comment suggests this is done for performance reasons. My test file was 13k.

Would you consider increasing this a little? 10k is not that huge for a source file and in my testing, the code took only 16ms for the 13k file. This is still very fast, and I believe any increase in time will only be hit by people who have edits this large (and I'm sure the people that hit this limit would absolutely rather wait a few more milliseconds than have selections/breakpoints/etc. move to the wrong location).

**Comment by jrieken** [comment]
Thanks for the investigation! You seems to have a very fast computer. On my 2015 MBP (running on battery) it takes 250ms to diff 16k... I guess that explains why the limit is 10k 🤣 Note that the limit is measured per edit, which for the 1-edit-case is the file length, but there might be more edits of such length (admittedly rarely)

I am fine with up'ing the limit but I wonder how this isn't arbitrary... E.g a cool solution would be to assign a time budget of X and than minimise edits as long as we are within budget, e.g after 500ms we terminate the for-loop and accept the remaining edits as-is. Likes?

**Comment by DanTup** [comment]
> You seems to have a very fast computer. On my 2015 MBP (running on battery) it takes 250ms to diff 16k...

Oh, wow - that's some difference (mine is a 2018 MBP running on mains). Our of interest, how long does it take you to format a 16k file that doesn't go through this code (for ex typescript)?

> I am fine with up'ing the limit but I wonder how this isn't arbitrary... E.g a cool solution would be to assign a time budget of X and than minimise edits as long as we are within budget, e.g after 500ms we terminate the for-loop and accept the remaining edits as-is

I had the same thought - but that would result in different behaviour across machines which a) might make people with slower machines see this issue much more and b) make it tricker to debug if someone sees it (for ex. if they're trying to figure out why a colleagues machine is has this weird bug they do not).

It's definitely arbitrary, but I can't think of a great solution. Even if we pushed this into the formatter, there's a chance the formatter would just be doing the same thing and therefore eat the same time. If there's a concern about formatter time, wouldn't it be better to measure the full format time rather than just this portion? For ex:

- After 500ms write a console warning that the formatter is slow
- After 1.5s (or something else arbitrary) tell the user their formatter is slow and was aborted

(having telemetry on that might be good too, you could open issues with formatters that you think are particularly slow).

**Comment by DanTup** [comment]
> Oh, wow - that's some difference (mine is a 2018 MBP running on mains)

Actually, it was my Windows PC I was using when I measured that (I didn't have yarn etc. set on up on MBP) and the CPU is super old, so now I'm wondering if I measured it properly (I was using one of your exist tests, just changed the content and used `window.performance.now`). I'll have another look at that later to confirm .

**Comment by DanTup** [comment]
Ok, I re-measured (using the sample file from my repro above). `console.log` didn't seem to work, so I got the timing like this:

```ts
// lines is the array of lines from the sample file
const model = worker.addModel(lines, '\n');
const newContent = lines.join('\n').replace(/\n{2,}/g, '\n');

const now = window.performance.now();
const edits = await worker.computeMoreMinimalEdits(model.uri.toString(), [{ text: newContent, range: new Range(1, 1, lines.length, lines[lines.length - 1].length) }])
const now2 = window.performance.now();

throw new Error(`took ${now2 - now}ms to run over ${newContent.length} characters`);
```

>  took 18.099999986588955ms to run over 13274 characters

My CPU is a Core i5-4430 (3Ghz).

**Comment by jrieken** [comment]
Yeah, I measured with the limit set to 100k. That should explain the big difference. Then we might just accept 250ms and says that's OK. 

That might still be better than the time budget because in most cases we split 1 edit into N. If making that one edit more minimal takes minutes we are lost and the time check won't help as it's too late...

**Comment by DanTup** [comment]
My limit was also set to 100k, but my input text was only 13k characters.

> Then we might just accept 250ms and says that's OK.
> 
> That might still be better than the time budget because in most cases we split 1 edit into N

I'm not sure which options you're comparing here. Do you mean having an overall timer and cancelling, rather than your earlier idea of bailing out after the time (which doesn't help if a single diff is too slow)? That sounds fine by me - though it'd be good if the timer did elapse it gets logged somewhere, so if anyone sees issues we can easily identify them from the console.

In the case where it goes over, would you cancel the edit, or just apply the single edit? I can see arguments for both - cancelling means things like breakpoints won't get messed with, but also in some cases the users might prefer to have the formatting (esp. if they have no breakpoints/etc.). Seems overkill to have an option/prompt though!

**Comment by jrieken** [comment]
I have pushed a change to up the limit to 100k. A trace log message keeps tracks how long this takes and I suggest to go with this for a while. 

No cancellation yet because you cannot cancel from within the worker (once it is stuck) and while you can stop waiting from the UI thread you cannot unblock the worker. That's why some kind of iff limit should always be used.

**Comment by DanTup** [comment]
Great, thanks very much! I'll give it a quick test in insiders tomorrow (and ofc, I will try to progress things with improving our formatter where I can).

> A trace log message keeps tracks how long this takes and I suggest to go with this for a while.

It may be worth logging when it's skipped due to hitting the limit too, otherwise the picture may be incomplete (there are logs for slow 90,000 edits, but nothing for skipped 100k edits). Though if the logging is only client side, it probably doesn't matter too much - but if you want to collect data on it, it might.

For the timeout issue, I wonder if the diff code could support a cancellation token or something (it could periodically check and bail out)? I think you might be using an external package atm though, so maybe more effort than it's worth.
