### ISSUE TITLE
I add snippets for markdown, but it doesn't work

### ISSUE THREAD

**Issue by haizhuling** [Microsoft/vscode#72320]
just like title, i create new extension for vs code, so need add snippets for markdown, but it doesn't work. when i use javascript or html, it can work , just markdown doesn't workdown. so what i can do to add snippet for markdown?
this is html 
![Snipaste_2019-04-13_17-06-48](https://user-images.githubusercontent.com/23161247/56077426-b7efa600-5e0e-11e9-9e40-63cbf830b7bc.png)
this is markdown
![批注 2019-04-13 170540](https://user-images.githubusercontent.com/23161247/56077428-b9b96980-5e0e-11e9-9856-7729d453f4ea.png)

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by ShengdongYan** [comment]
I have the problem as well, please answer the question, how to deal with that?

**Comment by ToSeven** [comment]
me too

**Comment by jrieken** [comment]
Everyone: please provide reproducible steps

**Comment by haizhuling** [comment]
i find the question, just like this, we need open the suggestion or press _ctrl + space_
![Snipaste_2019-04-13_17-06-48](https://user-images.githubusercontent.com/23161247/56716163-32ec8100-676c-11e9-8b44-930855b53978.png)
