### ISSUE TITLE
The problem window repeatedly shows two identical questions.

### ISSUE THREAD

**Issue by Czlun** [Microsoft/vscode#72325]
- VSCode Version:1.33.1
- OS Version:Windows_NT x64 10.0.117763

Steps to Reproduce:

1. Open Gitbash
2. Enter work path. example: `cd /f/Work/C++/3.data structure/tree`
3. Open VSCode. example `code .`
4. Start Debug

The problem window repeatedly shows two identical questions.
Clicking on the first error will locate the code,but Clicking on the second error will prompt "File not found".
`Unable to open 'binaryLink_tree.c': File not found (file:///f:/Work/C++/3.data structure/tree/f:/Work/C++/3.data structure/tree/binaryLink_tree.c).`

It uses the wrong path:
`file:///f:/Work/C++/3.data structure/tree/f:/Work/C++/3.data structure/tree/binaryLink_tree.c
`

The correct path is: 
`file:///f:/Work/C++/3.data structure/tree/binaryLink_tree.c`

![图片](https://user-images.githubusercontent.com/22112076/56122219-742ea500-5fa4-11e9-8541-8bd42303ba99.png)
![图片](https://user-images.githubusercontent.com/22112076/56122256-945e6400-5fa4-11e9-8574-97f1857b0ee8.png)
![图片](https://user-images.githubusercontent.com/22112076/56122332-c8398980-5fa4-11e9-8f31-f5fca93f69a8.png)

Does this issue occur when all extensions are disabled?: Disabling the plugin causes the debug to fail.

**Comment by aeschli** [comment]
Please file this against the cpp extension.
