### ISSUE TITLE
high light feature for point word.

### ISSUE THREAD

**Issue by lchch** [Microsoft/vscode#72335]
If there be a feature that when i press some shortcut key, then the word that the cursor point to now(all this word in the dir)  turn high light.

**Comment by madarsbiss** [comment]
just use Text Marker (Highlighter) and register it to your keyboard shortcut settings, for example: { "key": "ctrl+h", "command": "textmarker.toggleHighlight", "when": "editorTextFocus" }

**Comment by lchch** [comment]
Thank you. I have try it.
