### ISSUE TITLE
Scrolling by touchpad lags behind

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#72333]
Issue Type: <b>Bug</b>

Scrolling by touch severely lags behind, to the point of making me nausious. Also happens with all extensions disabled.

Scrolling by a mousewheel is instant (smooth scroll is disabled, otherwise that will make me nausious instead). Doesn't feel laggy at all. My scrollwheel is a traditional "ticking" one.

If I scroll by touchpad in a browser (I tried Firefox, Edge, Chrome) it is virtually instant.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (15.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.4.3
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.11
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.22.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.8
vscode-svg-previewer|vit|0.5.0

</details>

**Comment by deepak1556** [comment]
@thany can you try the latest insiders and see if the issue is any better https://code.visualstudio.com/insiders/ ? Also can you run with the extensions disabled and verify if the issue still repros. Incase the issue happens, can you attach the profile trace following the guidelines mentioned under https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process . Thanks!

**Comment by alexandrudima** [comment]
Thank you for attaching the CPU profile. From looking at it, I don't see that any large amounts of time is spent in JS (in our code)... Most frames take just a few ms to render:
![image](https://user-images.githubusercontent.com/5047891/66461391-3c974600-ea79-11e9-82e3-134efddd5c91.png)

So I think this might be an issue with the received events. I suggest we continue tracking in  https://github.com/microsoft/vscode/issues/76594
