### ISSUE TITLE
Goto Definition for language Java

### ISSUE THREAD

**Issue by fabiodamas** [Microsoft/vscode#72339]
Issue Type: <b>Bug</b>

1. File > Open folder (project java)
2. Try use the "Goto Definition". Isnt' working for me.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 x 2999)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
pgformatter|bra|1.6.5
vscode-postgres|cko|1.1.10
gc-excelviewer|Gra|2.1.32
edge|luo|0.3.1
dotenv|mik|1.0.1
vscode-language-pack-pt-BR|MS-|1.33.2
mssql|ms-|1.5.0
java|red|0.42.1
vscode-sql-beautify|sen|0.0.4
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1
vscode-spring-initializr|vsc|0.4.5

</details>

**Comment by aeschli** [comment]
Please file this against the Java extension: https://github.com/redhat-developer/vscode-java
Also, if you can add a small code sample, that would be great.
