### ISSUE TITLE
Make prefix sorting in quick open aware of used language

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#7233]
バージョン 1.2.0-insider
コミット 7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f

This is purely a usability issue on Japanese localized environment but I think "Install Extension" should be shown first place if we type "install ext" or something.

The problem is that "Show Installed Extensions" is translated as "インストール済みの拡張機能を表示" but "Install Extension" as "拡張機能のインストール" and the order is changed during the translation process...

![image](https://cloud.githubusercontent.com/assets/1311400/15813374/6ab81e20-2bf9-11e6-980e-b981c6677389.png)

**Comment by bpasero** [comment]
Our prefix sorting in quick open widget is not aware of the command alias we introduced.

**Comment by espresso3389** [comment]
@bpasero
> Our prefix sorting in quick open widget is not aware of the command alias we introduced.

Do you mean Localized texts by "command alias"?

If so, my intention is different. I think the commands should be sorted using the original command names like en-US:

![image](https://cloud.githubusercontent.com/assets/1311400/15842574/2ccaf26c-2c95-11e6-9837-bf05d73fc4d3.png)

**Comment by bpasero** [comment]
Yes, that would be the idea, but this is not easily possible without a bit of work currently.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
