### ISSUE TITLE
Not opening multiple files in tabs

### ISSUE THREAD

**Issue by SyedZeeshanHussain** [Microsoft/vscode#72331]
Issue Type: <b>Feature Request</b>

my vs code is not opening multiple files at a time. when I click other file, it replaces old one.

VS Code version: Code - Insiders 1.32.0-insider (11416de365a1e96302e171c9eebc2547872ac230, 2019-02-23T08:18:00.091Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by gjsjohnmurray** [comment]
This is what's called Preview Mode. See https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode on how it works, and how you can turn it off if you prefer.

Perhaps worth reading the rest of the Getting Started page as well...

**Comment by madarsbiss** [comment]
@gjsjohnmurray exactly! ;)

**Comment by SyedZeeshanHussain** [comment]
Now solved, thank you so much.
