### ISSUE TITLE
Failure to save file after renaming occurred

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#72343]
This issue was initially reported as https://github.com/redhat-developer/vscode-java/issues/871

> 
> 
> 
> 
> - Operating System: Windows 10, macOS 10.14.3
> - JDK version: jdk1.8.0_181
> - Visual Studio Code version: 1.33.1
> - Java extension version: 0.42.1
> 
> Steps to Reproduce:
> 
> When renaming a class (F2) the class symbol and the file itself are renamed properly. However, when I try to save the file the following error is displayed:
> 
> _Failed to save 'NewName.java': The content on disk is newer. Please compare your version with the one on disk._
> 
> When I now click on the compare button (part of the error popup) and accept the change then the renamed class is eventually saved.
> 
> ##### Steps To Reproduce
> 1. create new file _MyClass.java_
> 2. inside _MyClass.java_ expand the template"class" which gives you a skeleton for _MyClass_
> 3. position the cursor inside the symbol _MyClass_
> 4. press F2 (rename)
> 5. enter _NewName_
> 6. the mentioned error popup is displayed
> 7. press _Compare_
> 8. accept new version
> 9. _NewName.java_ is saved
> 
> ##### Current Result
> Extra step to save/ accept the renamed class.
> 
> ##### Expected Result
> After changing the name of the class via F2, the class symbol as well as the file name are changed and saved.
> 
> ##### Additional Informations
> When autosave is turned on the error occurs instantly, with autosave turned off the error popup is displayed when saving manually.
> 
> ![vs-code-rename-error](https://user-images.githubusercontent.com/1508184/55782290-3addcd00-5aac-11e9-8b11-1fa9d185917b.png)
 
 Does this issue occur when all extensions are disabled?: Maybe

I checked the problem doesn't occur with VS Code 1.32.3, so the regression was introduced in 1.33

**Comment by jrieken** [comment]
@bpasero for changes in the file service

**Comment by bpasero** [comment]
I think I am seeing this with typescript too.

**Comment by bpasero** [comment]
@fbricon can I ask you to please try to reproduce this from our latest insider version: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

If it reproduces: is that class you are renaming used anywhere outside? Could you give me a minimal repository to reproduce that I can clone?

**Comment by fbricon** [comment]
I can reproduce with Insiders 1.34 (6d5feae57959287fb116467f4eb6c7079571b466 2019-04-17T09:11:24.577Z).
To reproduce: 
- unzip
[rename-me.zip](https://github.com/Microsoft/vscode/files/3089905/rename-me.zip), 
- open the rename-me folder in vscode
- open foo/bar/RenameMe.java, 
- wait for the thumb up icon on the lower right to show up, indicating the Java language server is started, 
- rename the RenameMe class to whatever you want, once done, save the file

**Comment by bpasero** [comment]
@fbricon thanks, I see it.

**Comment by bpasero** [comment]
@fbricon pushed a fix, it would be great if you could verify it from an insiders build starting today or later.

**Comment by fbricon** [comment]
I confirm the problem is fixed in the Insiders build

**Comment by bpasero** [comment]
@fbricon thank you
