### ISSUE TITLE
Code formatting not working with organizeImports turned on

### ISSUE THREAD

**Issue by rolandleth** [microsoft/vscode#72346]
- VSCode Version: 1.33 and 1.33.1
- OS Version: 10.14.4

Steps to Reproduce:

1. Turn on
```json
"editor.codeActionsOnSave": {
	"source.organizeImports": true
},
```
2. Go to any `tsx` or `jsx` file.
3. Write some code that is poorly formatted.
4. Press save.
5. First save, oddly enough, works. From the second save onwards, it either doesn't format anything **except** the imports, or it does it after a delay (Press save, wait a second, press save again, now it formats).

Turning `source.organizeImports` off properly formats the file on save. `1.32.3` works properly.

`electron.tsserver` is at 100% and Code is at 100–140% when this happens.

Tried other solutions like clear TS caches or update `styled-components`, but nothing worked.

Does this issue occur when all extensions are disabled?: Yes

https://d.pr/free/i/vid7ty — too big to upload here.

Between 0:10 and 0:20 I pressed ⌘S multiple times and nothing happening until it finally kicked in at 0:22. After disabling `organizeImports` it can be seen that the format happens instantly.

Another example at 00:57, the format happened instantly, but after enabling `organizeImports` again, the first save at 1:04 happened almost instantly, but the future ones happen after multiple saves, 1:08–1:13 and 1:15–1:20 (the save didn't happen until I actually moved the cursor on another line).

It can be observed when the imports are getting organized (semicolons are added and/or unused imports are being removed).

Sorry for not having key presses displayed, I didn't know how to do it.

**Comment by rolandleth** [comment]
I updated `typescript` to `3.5.0-dev.20190413` and now it appears to be working correctly. Will have to test a bit more to properly confirm, though.

**Comment by mjbvz** [comment]
@rolandleth Can you share your project so we can investigate?

**Comment by rolandleth** [comment]
You can try https://github.com/rolandleth/rolandleth.com. It doesn't use TypeScript, but it has the same issues as the ones that do (even the `electron_node.tsserver.js` and Code CPU usage). If this one proves to be of no help, I can invite you to a private repo that uses TS.

**Comment by codepunkt** [comment]
I'm having the same issue.

**Comment by mjbvz** [comment]
@rolandleth I suspect these actions on save are timing out. Try increasing the timeouts  by setting:

```
"editor.codeActionsOnSaveTimeout": 2000
"editor.formatOnSaveTimeout": 2000
```

Not sure what causes these actions to take so long. I can repo this maybe every few saves. Will keep investigating

**Comment by rolandleth** [comment]
Had them at `750` (which is still high-ish), bumped to `2000`. Thanks for investigating!

**Comment by rolandleth** [comment]
@mjbvz Any chance this might get tackled in the next version? Any way I could help?

**Comment by mjbvz** [comment]
Are you still seeing this regularly in VS Code insiders (1.35)?

**Comment by rolandleth** [comment]
@mjbvz I can confirm that it appears to be working properly on 1.34 and 1.35, both projects with TypeScript and without, all making use of styled-components (not sure if this is the culprit here, but I've read a few issues where it was).

The only exception is React Native + TypeScript (`3.5.0-latest-dev`) + styled-components (doesn't matter what version). This one still has the previous behaviour.

**Comment by mjbvz** [comment]
Closing since it sounds like you aren't hitting the original issue anymore?

https://github.com/microsoft/vscode/issues/75792 proposed a setting that would make on save failures more obvious

**Comment by rolandleth** [comment]
Yes, it feels _much_ better. It still hiccups from time to time, but it's so rare, it goes unfelt.

Have a great day, Matt!
