### ISSUE TITLE
emoji can't display normally on terminal 

### ISSUE THREAD

**Issue by zzxqd** [Microsoft/vscode#72342]
- VSCode Version:1.33.1(user setup)
- OS Version:Windows_nt x64 10.0.17763

Steps to Reproduce:

1.open vscode terminal
2.input emoji or paste an emoji into terminal

Does this issue occur when all extensions are disabled?: Yes
![图片](https://user-images.githubusercontent.com/23022401/56137779-22981180-5fc8-11e9-9838-578ab0df9135.png)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
