### ISSUE TITLE
VS Code on MAC: to use the java command line tool you need to install jdk

### ISSUE THREAD

**Issue by AdhamAlHarazi** [Microsoft/vscode#72341]
Since I installed VSCode on MAC three months ago, I got the attached message every time I open VSCode or when I open the terminal. I had no problem with the terminal before installing VSCode. The editor is functioning perfectly, but the message is annoying.

My current version is Version 1.33.1 (1.33.1), but it was not the same when I first installed it.
 
<img width="428" alt="Screen Shot 2019-04-15 at 4 34 55 PM" src="https://user-images.githubusercontent.com/20932136/56136994-902e4880-5f9c-11e9-98d6-bea372e9dcce.png">

**Comment by Tyriar** [comment]
You must have some extension that uses java and is triggering it.

**Comment by AdhamAlHarazi** [comment]
@Tyriar I only use C#, Python, and Debugger for unity extensions. I disabled them and the issue persists.
