### ISSUE TITLE
path.join fails on './'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#7234]
- Set a breakpoint in TMSyntax.ts, line 106, make it conditional: `syntax.language ===  "css"`
- restart VS code, 

extensionFolderPath is: `/home/aeschli/workspaces/vscode/extensions/css`
syntax path is: `./syntaxes/css.plist`

result of join is: `/home/aeschli/workspaces/vscode/extensions/css`

**Comment by jrieken** [comment]
got fixed by #7202
