### ISSUE TITLE
Mac OS - Update download failed.

### ISSUE THREAD

**Issue by lgArlequin** [Microsoft/vscode#72344]
- VSCode Version: Version 1.33.0 (1.33.0)
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Check for updates
2. Get the error: Update download failed. The server sent an invalid response. Try again later.

Extra:
When try to download manually, the url fails:
https://az764295.vo.msecnd.net/stable/51b0b28134d51361cf996d2f0a1c698247aeabd8/VSCode-darwin-stable.zip

**Comment by aeschli** [comment]
I'm able to access the URL.

**Comment by lgArlequin** [comment]
I do not, also try from a windows PC and I could not access.

**Comment by lgArlequin** [comment]
Now it works, thanks.
