### ISSUE TITLE
Underscore Character in Terminal

### ISSUE THREAD

**Issue by nrfaikar** [Microsoft/vscode#72340]
Issue Type: <b>Bug</b>

Underscore character "_" in built-in terminal not visible.

I'm using bash or zsh in Linux.

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:12:57.707Z)
OS version: Linux x64 5.0.7-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1895)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.63GB (4.02GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
gitlens|eam|9.6.0
php-intellisense|fel|2.3.10
graphviz-markdown-preview|gee|0.0.7
vue-snippets|hol|0.1.11
vscode-git-tags|how|1.3.1
r|Iku|1.0.7
r-pack|Iku|0.0.2
git-indicators|lam|2.1.1
git-graph|mhu|1.4.5
r|Mik|0.0.6
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
vetur|oct|0.18.1
r-lsp|REd|0.1.0
dot|Ste|0.0.1
gitblame|wad|2.7.0

(1 theme extensions excluded)

</details>

**Comment by TheTrainor** [comment]
I ran into this today as well. It's a font rendering problem. As a temporary fix, you can either change your font size or the font family of the integrated terminal. I now run the following and underscores show properly.

```
"terminal.integrated.fontFamily": "Monospace",
"terminal.integrated.fontSize": 14
```
