### ISSUE TITLE
Reveal In Side Bar does not work

### ISSUE THREAD

**Issue by adam-morgan** [Microsoft/vscode#72353]
- VSCode Version: 1.33.1
- OS Version: macOS Mojave (10.14.4), Windows 10

Since upgrading to 1.33, switching between open file tabs or right clicking a tab and clicking "Reveal in Side Bar" does not highlight and scroll to the file.  Reverted to 1.32.3, both of these actions highlights and scrolls to the file in the side bar.  Tested on both macOS Mojave and Windows 10, same behavior in both.

Steps to Reproduce:

1. Click on an open file tab, side bar does nothing.
2. Right click a tab and choose "Reveal in Side Bar", side bar shows a blue border but otherwise does nothing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by adam-morgan** [comment]
I am using a multi-folder workspace.  My workspace file looks something like this:

```
{
    "folders": [
        {
            "path": "."
        },
        {
            "path": "code"
        }
    ],
    "settings": {
        "files.exclude": {
            "code": true,
            "tools": true,
            "packages": true
        }
    }
}
```

In this workspace, the "code" folder is explicitly called out in the "folders" section so that it appears in the side bar at the top level alongside the root folder, and it's then excluded in the "files.exclude" section so that it doesn't appear again inside the root folder.  I suspect that this inclusion and exclusion of "code" is causing the issue?

If I remove "code" from "folders" and from "files.excludes", the reveal functionality works as expected.

Using this same workspace with 1.32.3 gives me the expected behaviour.

There are no errors in the development console.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/72299
