### ISSUE TITLE
Provide a way for extensions to open the settings editor with a query

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#72352]
Issue Type: <b>Feature Request</b>

I'd love to be able to open settings with a query from an extension. This would allow opening it to show the user all of the extension's settings or some particular setting.

**Comment by RMacfarlane** [comment]
Oh, nevermind, this is already possible using `vscode.commands.executeCommand('workbench.action.openSettings', 'query text');`. I had been looking at `workbench.action.openSettings2`

**Comment by Vigilans** [comment]
Now that `workbench.action.openSettings` accepts a query as args(@rebornix 's [e5c1c22](https://github.com/Microsoft/vscode/commit/e5c1c2258e421db353c2a2ee1a04da31837a7e77#diff-dfd9031c00a144c2364595f331243744)), personally I think the same should goes for `workbench.action.openKeyBindings`.

However... `workbench.action.openKeyBindings` and `workbench.action.openSettings2` are both implemented using `Action` class, and the args are discarded in [triggerAndDisposeAction](https://github.com/Microsoft/vscode/blob/91eaf035024ef04350278167a890f40df46d3293/src/vs/workbench/common/actions.ts#L96) class:

https://github.com/Microsoft/vscode/blob/91eaf035024ef04350278167a890f40df46d3293/src/vs/workbench/common/actions.ts#L113

(`args` is not passed to `actionInstance.run` in code above)

Similar with @RMacfarlane, this would allow an extension to provide the users with some hint to configure custom key bindings.

**Comment by roblourens** [comment]
Out of curiosity, what would you want to use that for in an extension? Have a keybinding that opens the setting editor pre-filtered to some query?

**Comment by Vigilans** [comment]
I'm a collaborator of [vscode-leetcode](https://github.com/jdneo/vscode-leetcode) extension, and frequently there are rookies asking how to bind 'test' or 'submit' command to a specific key binding. like [this issue](https://github.com/jdneo/vscode-leetcode/issues/262).

If we can show a message to tell them how to do it, and an option to guide them to a pre-filtered keybinding editor like this:
![](https://user-images.githubusercontent.com/20227484/55670915-77e36d00-58bc-11e9-93b7-4dba00ff8348.png)

The the issues about this should be reduced.

The same goes for settings editor, where our webview [uses built-in markdown preview settings](https://github.com/jdneo/vscode-leetcode/issues/246) to control its appearance. If we can open the settings editor with pre-filtered query 'markdown.preview', then users would find it  easy to modify the settings.

**Comment by roblourens** [comment]
That's a good idea. If you open a new issue for that, we could do it.

**Comment by Vigilans** [comment]
Thanks, I'll open a issue for it.
