### ISSUE TITLE
Intellisense: PromiseRejectionEvent suggested over Promise

### ISSUE THREAD

**Issue by jbsulli** [Microsoft/vscode#72357]
Issue Type: <b>Bug</b>

I'm in the middle of a large refactor where I am converting jQuery.Deferred() to Native Promises. For some reason, PromiseRejectionEvent is suggested by IntelliSense before Promise or Promise isn't suggested at all. This is making it very difficult to work. For example, I'll type "new Promise(" and by typing the "(" it turns my perfectly valid JS into "new PromiseRejectionEvent(". Then I have to hit undo twice and type the parenthesis again. 

Do I need to configure VSCode differently or is a bug? `recentlyUsedByPrefix` has helped some but only when I have already used "Promise" in the file.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
pgformatter|bra|1.6.5
vscode-postgres|cko|1.1.10
scala|dal|0.0.5
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.0
vscode-pull-request-github|Git|0.6.0
python|ms-|2019.3.6558
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by mjbvz** [comment]
Closing as not reproducable in my testing
