### ISSUE TITLE
Bug: dialog boxes broken on Ubuntu using snap package

### ISSUE THREAD

**Issue by sdc395** [Microsoft/vscode#72356]
- VSCode Version: 1.33.1
- OS Version: Ubuntu 16.04.6 4.15.0-47-generic x86_64

Steps to Reproduce:

1. Install the `code` snap on Ubuntu 16.04
2. Launch `code`
3. Open the 'About' (or any other) dialog box.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/11042556/56154490-8b738f80-5fb0-11e9-8250-2d295bc5e55a.png)
![image](https://user-images.githubusercontent.com/11042556/56154576-bfe74b80-5fb0-11e9-8e60-c26423fc8234.png)

**Comment by sdc395** [comment]
It also seems to affect the context menus.  They appear flat and there's no highlighting of the item under the mouse.

**Comment by Tyriar** [comment]
FYI @flexiondotorg

**Comment by Tyriar** [comment]
This is either an issue with snaps, electron or Ubuntu itself, therefore closing off as out of scope.
