### ISSUE TITLE
Allow changing colorCustomizations without writing them to settings file

### ISSUE THREAD

**Issue by oreporan** [Microsoft/vscode#72350]
I have an extension which colors the activeTab (or status bar) based on a regex. 
The extension works fine however because I'm changing the `settings.json` -> `colorCustomization` at runtime, it creates an extra flicker (an extra paint of the editor) when its set.

I'd like to see an option of changing colorCustomizations at runtime without having to save them to the settings.

Something that exists only in memory perhaps, using the API

**Comment by aeschli** [comment]
we have a memory configyration tareg, but I think it's not available in the extension API.
While I see that this would help you, it's unclear to me how users would understand what's going on. We probably also need UI for the memory settings.

**Comment by sandy081** [comment]
@oreporan What is that extra flickering and why is it caused only when you are writing in to the settings file?

**Comment by oreporan** [comment]
I'm not sure what causes the flickering. I'm guessing its because the file renders, and then I change the colorCustomization so it re-renders, but instead of just the tab color changing, the whole file flickers

**Comment by sandy081** [comment]
@aeschli Can you please explain about the flickering?
