### ISSUE TITLE
Active file not highlighted in explorer

### ISSUE THREAD

**Issue by ktoto** [Microsoft/vscode#72351]
- VSCode Version: 1.33.0, 1.33.1
- OS Version: MacOS 10.14.4

Steps to Reproduce:

1. I have workspace with some folders inside it:
```
{
	"folders": [
		{
			"path": "online"
		},
		{
			"path": "online/packages/mobile"
		},
		{
			"path": "online/packages/desktop"
		},
		{
			"path": "online/packages/core"
		},
		{
			"path": "online/packages/common"
		}
	]
}
```
2. In root folder I have settings for ignore all "packages/*" files.
```
{
    "files.exclude": {
        "**/node_modules": true,
        "packages": true
    }
}
```
3. When open files from `packages` folder file explorer not highlight them. 

In version 1.32 all be fine and highligh in file explorer is working.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/72299
