### ISSUE TITLE
Update failure

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#72355]
@Chanfeechen commented on [Thu Apr 11 2019](https://github.com/Microsoft/vscode-python/issues/5221)

[vscode-inno-updater-1555038148.log](https://github.com/Microsoft/vscode-python/files/3071372/vscode-inno-updater-1555038148.log)

## Environment data

- VS Code version: VSCodeUserSetup-x64-1.33.0
- Extension version (available under the Extensions sidebar): XXX
- OS and version: Windows 10 1803
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): anaconda
- Relevant/affected Python packages and their versions: none

## Expected behaviour

autoupdate

## Actual behaviour

fail and uninstall automatically

## Steps to reproduce:
1. close vs code after use

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Not applicable
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
Not applicable
```

**Comment by DonJayamanne** [comment]
Note, this is not specific to the `Python extension`

**Comment by sandy081** [comment]
@Chanfeechen Not sure if I understood the issue. Are you having issues auto updating an extension or VS Code?
