### ISSUE TITLE
Workspace Settings TAB missing ??

### ISSUE THREAD

**Issue by Cyper77** [Microsoft/vscode#72365]
![image](https://user-images.githubusercontent.com/26312870/56161539-70197c00-5fd2-11e9-881e-6778f0a18ede.png)

**Comment by mittalyashu** [comment]
Which **Workspace Settings TAB** are you referring about?

**Comment by usernamehw** [comment]
`NO FOLDER OPENED`

**Comment by Cyper77** [comment]
hmm. ok i seen "no folder opened" section then i select my folder, finally workspace settings appears to us :) thanks folks.
