### ISSUE TITLE
Support git difftool --dir-diff

### ISSUE THREAD

**Issue by lutzroeder** [Microsoft/vscode#72364]
When configuring Visual Studio Code as a Git diff tool a new IDE instance will be opened for each file. Git supports `--dir-diff` to diff a set of files simultaneously, for example `git difftool --dir-diff HEAD~3 HEAD`. Some diff tools also support a partial mode to collect all `git difftool` calls to get the full list of files. 

In Visual Studio Code `--dir-diff` currently shows as two empty folders. lnstead the file list could be shown in `Source Control` with all other activities disabled which would be a much better user experience.

![screen](https://user-images.githubusercontent.com/438516/56160605-74b34580-5f7c-11e9-82fc-b1901bdd0a02.png)

**Comment by ChopSu3y** [comment]
I also would like to have this feature! This is the exact same thing I want and am currently seeing.

**Comment by joaomoreno** [comment]
#63548
