### ISSUE TITLE
Clicking create new folder button before extensions have finished loading can prevent creating folders altogether

### ISSUE THREAD

**Issue by PassTheMayo** [Microsoft/vscode#72368]
Issue Type: <b>Bug</b>

Upon loading vscode, clicking the `Create Folder` button at the top of the workspace before extensions are done loading can prevent the button from being used any further beyond that. This only occurs when extensions are enabled that add or modify buttons in the sidebar, such as GitLens. I can't tell if this is just GitLens or vscode, since I don't know of any other extensions that modify the sidebar beyond that. Once the button is clicked, and extensions are finished loading, the input for the folder name goes away, and the button no longer works after at all.

![03-54-44 PM](https://user-images.githubusercontent.com/16949253/56164707-e13b3e00-5f96-11e9-8e48-01e5bae1de62.gif)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vscode-html2pug|dba|0.1.0
vscode-npm-script|eg2|0.3.5
auto-rename-tag|for|0.0.15
discord-vscode|icr|3.4.0
material-icon-theme|PKi|3.7.0
code-settings-sync|Sha|3.2.8
swdc-vscode|sof|0.14.7
vscode-surround|yat|1.0.2

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/72139
