### ISSUE TITLE
Sass variables incorrectly hyperlinked as functions

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#72367]
Issue Type: <b>Bug</b>

1. Create a sass variable of a data url string (e.g. a base64-encoded svg) such as `$marker`

2. use the vaeiable as a background-image property:
`background-image: url($marker);`

3. The variable inside the parens in hyperlinked, but clicking it yields the error 

```
Unable to open '$marker': File not found (file:///Users/st016lo/github/ng-designsystem/client/src/sass/documentation/pages/$marker).
```
or 
```
Unable to open '$marker`: t.dispose is not a function.
```

<img width="790" alt="Screen Shot 2019-04-15 at 4 45 38 PM" src="https://user-images.githubusercontent.com/835148/56164352-8574b300-5f9e-11e9-8bde-134447a762b0.png">

VS Code version: Code - Insiders 1.34.0-insider (4f212683c16977661ad51f8d13957de9d3280b30, 2019-04-15T14:12:07.955Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|-psn_0_184233896|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
project-manager|ale|10.5.1
turbo-console-log|Cha|1.2.17
bracket-pair-colorizer|Coe|1.0.61
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.8.2
vsc-material-theme-icons|equ|0.12.0
prettier-vscode|esb|1.8.1
path-autocomplete|ion|1.13.2
svg|joc|0.1.4
ecdc|mit|1.0.5
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.12
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.22.0
polacode|pnp|0.2.2
quicktype|qui|12.0.46
LiveServer|rit|5.5.1
code-settings-sync|Sha|3.2.8
stylelint|shi|0.48.0
rewrap|stk|1.9.1
ayu|tea|0.18.0
vscode-npm-scripts|tra|0.2.1
sort-lines|Tyr|1.8.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.2.0

(4 theme extensions excluded)

</details>

**Comment by octref** [comment]
Probably caused by vscode-scss.
