### ISSUE TITLE
Label frames in stack are not copied correctly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#72361]
- Pause in some async code
- Right click on stack -> "Copy call stack"
- Paste the result somewhere
- See that the promise label frame says `[ Promise.then ] (Unknown Source:undefined)`

**Comment by isidorn** [comment]
What would you expect in that case.
Just `[ Promise.then ]` or
`[ Promise.then ] (Unknown Source)`

**Comment by roblourens** [comment]
Yeah just `[ Promise.then ]` I think

**Comment by isidorn** [comment]
Makes sense. Pushed it. Let me know if it fixes the issue for you.
