### ISSUE TITLE
debug console not showing the latest line 

### ISSUE THREAD

**Issue by sajafleming** [Microsoft/vscode#72377]
- VSCode Version: 1.330
- OS Version: Mojave v10.14.3

Steps to Reproduce:

1. Install Visual Studio Code Ruby Extension
2. Debug and view the Debug Console -> the window does not scroll to the latest line 
3. Type an expression in the debug console -> you will not be able to see what you typed and have to manually scroll

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Fixed in latest insiders. You can use insiders as a workaround or wait for the next stable which will have this fix
https://code.visualstudio.com/insiders/

**Comment by sajafleming** [comment]
I got the latest insiders and it does work as expected. Thank you!

**Comment by isidorn** [comment]
Great. Welcome
