### ISSUE TITLE
Support serverReadyAction in tasks.json

### ISSUE THREAD

**Issue by dantman** [microsoft/vscode#72374]
`launch.json` added `serverReadyAction` which [automatically opens a browser tab based on a text match in the debug console or integrated terminal](https://code.visualstudio.com/updates/v1_33#_automatically-open-a-uri).

It would be great if we could use this same config in `tasks.json` tasks so when we say run a `npm: start` task for an express/angular/etc server a tab for it automatically opens.

**Comment by personball** [comment]
In my scenario:

- Press F5 to start debugging grpc service: `start rpc server, port:  10170`;
- Manually open a shell to run: `grpcui -plaintext localhost:10170`;
- grpcui open a web ui;

It would be great if we could config serverReadyAction to call a shell task.
