### ISSUE TITLE
Improve usability of minimized/maximized editors

### ISSUE THREAD

**Issue by stefcameron** [microsoft/vscode#72371]
I tried as best I could to look for duplicates, but couldn't find any. For the longest time, when using cmd+X to set focus to a different editor group, only the focus (i.e. I-bar) would change to the last active editor in that group. Now, that still happens, but the editor group also gets maximized, and all my other groups minimized -- _mega annoying_ for me! I don't want my editor layout to change; I still need to able to read stuff in other groups, and with all other groups minimized, that's not possible. I also don't want to spend my time resizing all my groups with the mouse (I haven't found any key sequence to revert back to non-maximized layout, not that it would solve my issue anyway).

How do I now set focus to another editor group with the keyboard __without__ my workbench layout being altered? I've searched settings for things like "maximize", "minimize", "resize", nothing seems applicable except `"workbench.editor.centeredLayoutAutoResize"` but only kind of, and setting this to `false` (from default `true`) didn't fix the issue.

- VSCode Version: 1.33.0 (1.33.0)
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Press cmd+1 or cmd+2 or cmd+3 with a 3x2 grid.

Interestingly, the issue only occurs with cmd+2 and on. cmd+1 just sets the focus. Yet all sequences of cmd+N are tied to the same behavior: "set focus to editor group N"

Does this issue occur when all extensions are disabled?: __Yes__

**Comment by sbatten** [comment]
@stefcameron can you try running the command _Reset Editor Group Sizes_ and see if the issue still reproduces?

**Comment by stefcameron** [comment]
> @stefcameron can you try running the command _Reset Editor Group Sizes_ and see if the issue still reproduces?

@sbatten Certainly! But I'm not sure at what point I should run this command, and what I should expect. Do I just run this once and then expect the problem to go away? Or do I run this after I've focused to an editor and all other editors have been minimized (and so I'd have to run this command every time I focus to an editor group with `cmd+N`...)? Or once I've set focus to an editor group with `cmd+N`, then run this command, and after that, `cmd+N` should no longer minimize other editors? Please clarify.

**Comment by sbatten** [comment]
If you run the command once, I expect that clicking into editor groups will no longer maximize them. If this not the case, please let me know and I will continue to investigate the issue.

**Comment by stefcameron** [comment]
@sbatten Thanks for clarifying. I gave it a try, and yes, it fixed the issue! I played around a bit more to see if I could get the issue to resurface, and I discovered that all is well _until_ I click and drag an editor to resize it such that it causes another editor to get minimized (i.e. that editor's height gets to its minimum height). At that point, `cmd+N` will continue to work (i.e. _not_ cause that editor to get maximized and all others to be minimized) _until_ I set focus to the minimized editor. Then that editor will get maximized and all others will be minimized. From this point on, since all other editors got minimized, as I continue with the `cmd+N` sequence, they each get maximized and all others minimized. This until I issue the _Reset Editor Group Sizes_ and editors come back to their original heights and the maximizing/minimizing on `cmd+N` finally stops.

So the trigger is causing an editor to be minimized just by resizing it to be (in my case, _without the intent to minimize it_, just to make it small).

I think here, because I had no visual cue that I had now minimized an editor, I'd expect that editor's height to _maybe_ get increased just a bit on focus if it's so small focus can't be set, but suddenly causing it to get maximized and all others minimized was completely unexpected.

**Comment by sbatten** [comment]
@stefcameron thanks for diving in.
@joaomoreno @bpasero

**Comment by stefcameron** [comment]
My pleasure!

**Comment by bpasero** [comment]
@stefcameron if you make an editor group small enough it snaps into minimized mode (we had this behaviour for a long time). In that mode moving focus around will cause this state to be preserved. Maybe what you want is a way to disable this behaviour? Can you state what you expect here?

**Comment by axefrog** [comment]
Not sure if this is related or the same thing, but I also work with multiple editor group columns and rows, and I've discovered that the automatic expand/collapse behaviour of minimised groups in one orientation also affects groups in other rows or columns. For example, if I have two primary columns, and then in the second column I have multiple rows that I keep in a minimised state (except for the one in focus), then, when I switch to another row, thus triggering the expand/collapse behaviour, the other _column_ also collapses, and the current column _expands_. Automatic expand/collapse behaviour should be limited to the current row or column. The feature is currently unusable if using more than a single primary row or column of editor groups.

**Comment by axefrog** [comment]
@bpasero I know you guys are probably swamped, but I figure pinging you can't hurt ... :-)
