### ISSUE TITLE
Output should not scroll beyond the last line

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7237]
There is no reason for having the Output scroll beyond the last line in the buffer, unlike the common editors.

@alexandrudima There is a setting for this, right?

![image](https://cloud.githubusercontent.com/assets/22350/15815045/94d0b44e-2bca-11e6-9ade-5fb4f95b25ea.png)

**Comment by alexandrudima** [comment]
Yes, `scrollBeyondLastLine`.

**Comment by joaomoreno** [comment]
Excellent, thanks!
