### ISSUE TITLE
VSCode drains memory and locks Ubuntu Virtualbox VM under Windows 10

### ISSUE THREAD

**Issue by markatarmlsg** [Microsoft/vscode#72379]
Issue Type: <b>Bug</b>

After running for a while VSCode causes system memory to be first gradually, then rapidly, consumed. It then goes on to consume memory filling up the swap file and locks the virtual machine.

It can happen at any time, but seems to be related to "Go to Definition", especially when I search into the gSoap source code.

It is generally stable if I don't use "Go to Definition". If I restrict searches to my code or the standard library it is mostly stable, but will still happen on occasion. If I search into gSoap it will happen withing 10 seconds.

I have tried the insider edition, and diabling all extensions. Neither helped. I have also tried running with --disable-gpu.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.18.0-17-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (4 x 3695)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|5.82GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
bracket-pair-colorizer-2|Coe|0.0.28
algorithm-mnemonics-vscode|dav|1.0.3
xml|Dot|2.4.0
CppSnippets|har|0.0.13
c-cpp-flylint|jbe|1.2.4
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
bash-debug|rog|0.3.4
bash-beautify|sha|0.1.1
cmake-tools|vec|1.1.3

</details>

**Comment by octref** [comment]
Report to cpptools, thanks.
