### ISSUE TITLE
"vscode:uninstall" script is run after extension update...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode#72375]
hi there :wave:

i'm seeing some odd behavior w/ the `vscode:uninstall` script / handler. it appears that script is called not only when someone _uninstalls_ your extension but ALSO when they update it. 

- VSCode Version: `v1.33.1`
- OS Version: windows 10

Steps to Reproduce:

1. in the extensions tab, select "check for extension updates" within the `...` (three dot) menu
2. after your extension is updated, reload if prompted
3. close and reopen VSCode

Expected:

`vscode:uninstall` script is NOT executed.

Actual:

`vscode:uninstall` script is run, files which should be kept are deleted.

**Comment by busticated** [comment]
from the docs:

> This script gets executed when the extension is completely uninstalled from VS Code which is when VS Code is restarted (shutdown and start) after the extension is uninstalled.

[source](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook)

**Comment by busticated** [comment]
@sandy081 any thoughts on this one?

**Comment by sandy081** [comment]
This looks to me a bug.

**Comment by sandy081** [comment]
To verify:

- Publish an extension with post uninstall script - https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook
- install the extension
- publish a newer version of the extension
- update the extension
- Make sure post uninstall script is not executed. You can confirm it from shared process logs
