### ISSUE TITLE
tsserver eating 120%+ of CPU 

### ISSUE THREAD

**Issue by InfinityMarketing** [Microsoft/vscode#72382]
Issue Type: <b>Performance Issue</b>

Working on a gatsby.js project with styled components - was running into the issue of 100% CPU when using styled components but I used the fix of clearing my typescript cache so it's running the latest version. It worked for a few days but now it's much worse and effects any .js file.

All of my gatsby projects pushes my CPU to 120%+

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    98	  5420	code main
    0	    98	  5422	   gpu-process
    0	    98	  5460	   shared-process
    0	   426	  6609	   window (mouse.js — Development)
    0	     0	  6610	     /bin/bash -l
    0	   262	  9088	       node /usr/local/bin/gatsby develop
    0	    33	  9094	         /usr/local/Cellar/node/11.8.0/bin/node /Users/leecampbell/Projects/Portfolio/Development/node_modules/jest-worker/build/child.js
    0	    33	  9095	         /usr/local/Cellar/node/11.8.0/bin/node /Users/leecampbell/Projects/Portfolio/Development/node_modules/jest-worker/build/child.js
    0	    33	  9096	         /usr/local/Cellar/node/11.8.0/bin/node /Users/leecampbell/Projects/Portfolio/Development/node_modules/jest-worker/build/child.js
    0	    33	  9097	         /usr/local/Cellar/node/11.8.0/bin/node /Users/leecampbell/Projects/Portfolio/Development/node_modules/jest-worker/build/child.js
    0	    33	  9098	         /usr/local/Cellar/node/11.8.0/bin/node /Users/leecampbell/Projects/Portfolio/Development/node_modules/jest-worker/build/child.js
    0	    33	  9099	         /usr/local/Cellar/node/11.8.0/bin/node /Users/leecampbell/Projects/Portfolio/Development/node_modules/jest-worker/build/child.js
    0	   131	  6613	     extensionHost
    0	   360	  6615	       electron_node tsserver.js 
    0	    66	  6634	         electron_node typingsInstaller.js typesMap.js 
    0	    66	  6618	       electron_node eslintServer.js 
    0	    33	  9193	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=6613
    0	    98	  9978	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=6613
    0	    66	  6614	     watcherService
    0	    33	 12918	     searchService
    3	    98	 12942	   window (Process Explorer)
    0	    66	 13240	   window (Issue Reporter)
    0	     0	 13271	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (mouse.js — Development)
|    Folder (Development): 437 files
|      File types: json(138) jpg(127) js(102) png(22) webp(18) md(8) css(3)
|                  eot(3) woff(3) DS_Store(2)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|10.5.1
vscode-browser-preview|auc|0.5.2
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-yarn|gam|1.6.0
diff-tool|jin|0.0.1
vscode-styled-sort|joh|0.0.7
vscode-styled-components|jpo|0.0.26
auto-comment-blocks|kev|1.0.1
vscode-titlebar-less-macos|leh|1.9.1
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.11.3
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|3.7.0
vscode-icons|vsc|8.5.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you have `@types/styled-components` npm installed in your workspace?

**Comment by InfinityMarketing** [comment]
I have "styled-components": "^4.1.3", I do not have @types/styled-components.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, your shared process info shows 0% cpu usage for tsserver. Can you please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information when the issue happens. Share the output of `code-insiders --status`

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
