### ISSUE TITLE
Trouble in installing Salesforce or other extensions as well.

### ISSUE THREAD

**Issue by vivekponugoti** [Microsoft/vscode#72389]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
I am trying to install Salesforce  extensions but giving the same error for all the extensions, below is the error message.

"Couldn't find a compatible version of Salesforce Extension Pack with this version of Code."
---

Steps to Reproduce:

1.
2.

**Comment by gjsjohnmurray** [comment]
VSCode 1.9.1 is ancient (see its 2017-02-09 date). I suggest you update it.

**Comment by octref** [comment]
Please install a more recent version, or download old versions of that extension.
