### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7238]
From @ra9r:

> So this is same issues occurs to me running on Mac OS X 10.11.5.  I'm running VSC 1.1.1.  Initially I get an error "**Extension host terminated unexpectedly.  Please reload the window to recover.**"  Clicking "Reload Window" results in the error being generated again.  When I leave it sitting for a few seconds, a second message appears that says "**Error from the extension host: channel closed**".

**Comment by joaomoreno** [comment]
Can I ask you to give me the following details?

- Inside Code, open the Developer Tools (<kbd>Cmd Shift P</kbd>, type `Developer`). Are there any errors in there? Also, type `process.env` and paste that in here.
- In a Terminal, outside Code, paste in here what you get from `env`.

Thanks!

**Comment by CannibalVox** [comment]
I'm having this same issue as described above.  However, I cannot use Cmd Shift P, because vs-code never begins functioning on startup.  I can interact with menu options but clicking them does nothing, I can open files from the left drawer but they're all plain white text, and no keyboard shortcuts ever work.  Additionally, I receive this error even if I open vscode without a folder.

Here is my output from `env`:

```
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/false
TERM=xterm-256color
TMPDIR=/var/folders/j8/x1_3f4p113z0ss1n3qk2ldt053m58d/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Gaq2AJDytY/Render
TERM_PROGRAM_VERSION=361.1
OLDPWD=/Users/XXX
TERM_SESSION_ID=C1F70A8B-6294-42A1-B7A5-AF5533115E08
USER=XXX
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ymKWKcmbFm/Listeners
__CF_USER_TEXT_ENCODING=0xA3A150D:0x0:0x0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/go/bin
PWD=/Users/XXX/code
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/XXX
GOROOT=/usr/local/go
LOGNAME=XXX
GOPATH=/Users/XXX/code
SECURITYSESSIONID=186bc
_=/usr/bin/env
```

**Comment by joaomoreno** [comment]
@CannibalVox maybe try <kbd>Cmd Alt I</kbd>... maybe that'll open the dev tools?

**Comment by ra9r** [comment]
Neither `Cmd Alt I` not `Cmd Shift P` work for me.  Here is the output from `env`

```
Hayaku:~ rodney$ env
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/nj/ndmd_2p519vgqdm9f4f_r1s00000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.t9xAURoMvN/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=AD0270EE-060E-42FB-9566-BEE13972CCA6
USER=rodney
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.yOkU5Rw7bX/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/rodney
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/rodney
LOGNAME=rodney
_=/usr/bin/env
```

**Comment by joaomoreno** [comment]
Can you give the Insiders release a try? It has a few fixes which can fix this issue.

https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders

**Comment by ra9r** [comment]
Yes, that did seem to make a difference.  I’ll let you know if the problem pops up again. FYI I updated to 1.2 instead of the nightly build.
On June 13, 2016 at 2:30:32 AM, João Moreno (notifications@github.com) wrote:

Can you give the Insiders release a try? It has a few fixes which can fix this issue.

https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders

**Comment by joaomoreno** [comment]
Excellent, thanks. We will push an update to the stable release this week with these fixes.

**Comment by varunkumar** [comment]
I am still seeing this issue. Its pretty annoying. Just not able to use. :/

**Comment by varunkumar** [comment]
Insider build is working fine though

**Comment by inspiratoadam** [comment]
I was seeing these same symptoms after installing the C# extension while VS Code was running on OSX 10.11.6.  I quit and reopened VS Code and it prompted me to install a debugger extension and now it works correctly.

**Comment by jwbenson** [comment]
Encountered this same issue on 1.3.1.  After closing all instances of VSCode and restarting the problem did not resurface.

**Comment by EricJammin** [comment]
This issue has popped up for me running version 1.11.2 on macOS 10.11.6 over the last several days.

I get the error message every couple of minutes and am asked to reload window. I have disabled all extensions, and this issue is still present.
