### ISSUE TITLE
F2 rename folder , all import package path will append the rename folder name in this TS file

### ISSUE THREAD

**Issue by kingemma** [Microsoft/vscode#72388]
Step 1: Select one foler in Source Explore
Step 2: Click "F2" and then press Enter key (don't change folder name )
The ts file will be changed like below.
**New (It is error code)** , absolute path "**@app/page/packageComponent/document-posting/node_modules/**" will be appended into import package path. 
import * as Enumerable from '@app/page/packageComponent/document-posting/node_modules/linq/linq';
import * as moment from '@app/page/packageComponent/document-posting/node_modules/moment';
**Original**, 
import * as Enumerable from 'linq/linq';
import * as moment from 'moment';

Thanks

**Comment by mjbvz** [comment]
Please include your vscode version and if this repos with extensions disabled

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate this
