### ISSUE TITLE
when i use setModel by a created model, it crashed

### ISSUE THREAD

**Issue by netweng** [Microsoft/vscode#72383]
here is the thing.
i want to implement multiple tabs, so i will use monaco.editor.createModel every time i create a new tab, and save the old model and editorviewstate in the store
`
{
 editor_model: editor.getModel(),
 editor_view_state:editor.saveViewState()
}
`
when i swich to the old tab, i will get the created model and the old view state from the store by the current tab index, and set them as the current tab context
`
editor.setModel(editor_model)
editor.restoreViewState(editor_view_state)
`
but the application crashed when i use setModel, and i found the project was suspend by an infinite loop
vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js: line 238

`    PieceTreeBase.prototype.getOffsetAt = function (lineNumber, column) {
        var leftLen = 0; // inorder
        var x = this.root;
        while (x !== SENTINEL) {
            if (x.left !== SENTINEL && x.lf_left + 1 >= lineNumber) {
                x = x.left;
            }
            else if (x.lf_left + x.piece.lineFeedCnt + 1 >= lineNumber) {
                leftLen += x.size_left;
                // lineNumber >= 2
                var accumualtedValInCurrentIndex = this.getAccumulatedValue(x, lineNumber - x.lf_left - 2);
                return leftLen += accumualtedValInCurrentIndex + column - 1;
            }
            else {
                lineNumber -= x.lf_left + x.piece.lineFeedCnt;
                leftLen += x.size_left + x.piece.length;
                x = x.right;
            }
        }
        return leftLen;
    };`
the x will never equal to SENTINEL, and this loop will never end. i don't know whether i miss something or else?
if i change the judge condition to 
`while(!isEqual(x, SENTINEL))`
it works perfect.
so and i miss something, or maybe this is a bug?

**Comment by netweng** [comment]
ok, i think i find the reason.
when i set a model in redux store, it just like cloneDeep the original model as a new object, and re-bind it's 'this', so when i use setModel, it failed, so, any api can be provided to re-attach by a model object to re-bind 'this' to the current editor

**Comment by netweng** [comment]
ok, i find the solution, maybe this issue can be closed.
i find there is a api `monaco.editor.getModels`, it record all the craeted models, so i dont save the textmodel in the store, i save the textmodel's id, and i will use this id to get the model by call the api `monaco.editor.getModels`

maybe this can help others, who have the same problem as mine.

**Comment by rebornix** [comment]
@netweng thanks for your investigation into this. It's good to know it's `cloneDeep` who leads to crash.
