### ISSUE TITLE
OS X: extension contributed protocol handler not invoked when no window is open

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#72391]
On OS X
- close all Windows but keep the vscode application running
- in chrome navigate to this URL `vscode://vscode.git/clone?url=https://github.com/Microsoft/vscode.git`
-> an empty window opens, but the protocol handler is not invoked.

Executing the same steps with a window open works and triggers the protocol handler.

**Comment by joaomoreno** [comment]
This has been fixed since
