### ISSUE TITLE
show error tips for arrow function in class

### ISSUE THREAD

**Issue by codingEcho** [Microsoft/vscode#7239]
- VSCode Version:1.1.1
- OS Version:10.11.5

Steps to Reproduce:
1. define class extends React.Component
2. input code like

``` javascript
 doLogin = (event) => {
        // ....
    }
```

show error wave line with `doLogin`

**Comment by dbaeumer** [comment]
@codingEcho can you please provide a more complete example. Best would be a workspace including your tsconfig.json that shows the problem.

**Comment by basarat** [comment]
> show error wave line with doLogin

You probably have a `.js` file. That syntax (property initializers) is not in JS standard yet (but on track). Ofcourse it is supported by TS : https://github.com/basarat/typescript-book/blob/master/docs/classes.md#property-initializer :rose:

**Comment by dbaeumer** [comment]
Closing the issue since no additional information has been provided.
