### ISSUE TITLE
"Edit in settings.json" link doesn't work and there is no any response 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode#72394]
Issue Type: <b>Bug</b>

"Edit in settings.json" link doesn't work and there is no any response 

VS Code version: Code - Insiders 1.34.0-insider (8b5ebbb1b8f6b2127bbbd551ac10cc080482d5b4, 2019-04-16T05:23:07.866Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.16.1-alpha
python|ms-|2019.3.6558
azure-account|ms-|0.8.2
csharp|ms-|1.18.0
vscode-docker|Pet|0.6.2-alpha

</details>

**Comment by roblourens** [comment]
I believe this has been fixed, do you still see it with the latest Insiders?

**Comment by v-dantch** [comment]
Yes, it works well on the latest Insiders. Thanks for your work.
