### ISSUE TITLE
massive cpu usage

### ISSUE THREAD

**Issue by unel** [Microsoft/vscode#72397]
Issue Type: <b>Performance Issue</b>

385% cpu usage in system monitor

VS Code version: Code - Insiders 1.34.0-insider (4f212683c16977661ad51f8d13957de9d3280b30, 2019-04-15T14:12:07.955Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	    98	  5264	code-insiders main
    0	    82	  5265	   gpu-process
    0	   262	  5266	   window (index.js — git)
    0	   115	  5272	     extensionHost
    0	    49	  5446	       electron_node eslintServer.js 
    0	   131	  5450	       electron_node tsserver.js 
    0	    33	  5457	         electron_node typingsInstaller.js typesMap.js 
    0	    33	  6936	       extensionHost
    0	    33	  6937	       extensionHost
    0	    33	  6939	       extensionHost
  399	  2114	 11076	       electron_node server.js 
    0	    33	  5273	     watcherService
    0	    49	  5443	     searchService
    0	    66	  5378	   shared-process
    0	    82	 11070	   window (Issue Reporter)
    0	     0	 11081	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js — git)
|    Folder (git): 10596 files
|      File types: png(4831) css(2369) js(2059) map(567) svg(178) ts(89)
|                  woff(70) woff2(70) ttf(70) tsx(52)
|      Conf files: package.json(8) webpack.config.js(5) tsconfig.json(1)
|                  makefile(1);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.0
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|2.2.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0

</details>

**Comment by octref** [comment]
https://github.com/wix/import-cost/issues
Report to them.
