### ISSUE TITLE
jsconfig baseUrl not working with multi root workspace

### ISSUE THREAD

**Issue by shengbeiniao** [microsoft/vscode#72395]
- VSCode Version: 1.33.1
- OS Version: MAC OS

Steps to Reproduce:

1. My workspace config
![image](https://user-images.githubusercontent.com/3301995/56192953-224c5480-6062-11e9-830b-be3c6761bda8.png)

2. My jsconfig.json
![image](https://user-images.githubusercontent.com/3301995/56192982-34c68e00-6062-11e9-9832-f3eeadd21f50.png)

```
# When I use cmd+left click this code,then should goto definition,but It's not working!
import { Card, Select, TableSelect } from 'components/Form'
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
I can't repo this with a simple workspace test:

![Screen Shot 2019-06-21 at 3 43 36 PM](https://user-images.githubusercontent.com/12821956/59954760-5a458e80-943b-11e9-8f9e-a5df24cd9468.png)

Please share an example project that demonstrates this
