### ISSUE TITLE
Long files crash vscode

### ISSUE THREAD

**Issue by bzuillsmith** [Microsoft/vscode#724]
I have a file that I am writing code to parse. It is ~3.8 million lines long. Most of the times I try to open it, vscode crashes. I don't need vscode to parse it in any way, I just want to open it in code for the line numbers so I can debug my code.

**Comment by bpasero** [comment]
@bzuillsmith how large is the file on disk?

**Comment by bzuillsmith** [comment]
~31 MB

**Comment by bpasero** [comment]
@bzuillsmith Can you upload it as zip somewhere and send the link?

**Comment by bzuillsmith** [comment]
@bpasero Sent it to you a private email because the file is not owned by me.

**Comment by bpasero** [comment]
@bzuillsmith thanks! @alexandrudima assigning to you, I cannot reproduce on Windows though. I see the file opens fine after some delay and my mem usage goes up to 600 MB.

**Comment by alexandrudima** [comment]
@bzuillsmith @bpasero Also tried the file on master and it opens fine. The work I did for #177 seems to make opening this file reliable as well.

**Comment by bpasero** [comment]
Cool :+1:
