### ISSUE TITLE
One big workspace uses over 20GB RAM (on 16GB computer)

### ISSUE THREAD

**Issue by AlexisTM** [Microsoft/vscode#72407]
Issue Type: <b>Bug</b>

Hi,

When I am opening a huge workspace, the Visual code "bootstrap-fork" uses over 60GB (increasing) in htop, while I am on a 16GB RAM Machine, using 100% of all 8 cores. 

On huge Python repos, the Python Execution Server extension was using over 20GB RAM. 

I first had the langage server using a lot of RAM:

![Screenshot from 2019-04-16 13-07-09](https://user-images.githubusercontent.com/6976744/56410608-f1486b80-627d-11e9-9a0c-a7aacce2cfb6.png)

I rebooted the computer and got the following:

![image](https://user-images.githubusercontent.com/6976744/56205541-5b78ca80-604a-11e9-928a-68984b90930d.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3099)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|15.10GB (0.15GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
msg|ajs|0.1.1
ros|ajs|0.3.0
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
jquerysnippets|don|0.0.1
xml|Dot|2.4.0
gitlens|eam|9.6.0
vscode-html-css|ecm|0.2.0
git-project-manager|fel|1.7.1
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
vue|jcb|0.1.5
restructuredtext|lex|106.0.0
vscode-clang|mit|0.2.3
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
Go|ms-|0.9.2
vetur|oct|0.18.1
vscode-docker|Pet|0.6.1
ros-snippets|pij|0.2.2
platformio-ide|pla|1.6.0
java|red|0.42.1
vscode-yaml|red|0.4.0
ispy|Ric|0.0.4
vscode-hexdump|sle|1.7.2
bootstrap4-vscode|the|6.1.0
python|tht|0.2.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1
debug|web|0.23.1

</details>

**Comment by roblourens** [comment]
That's strange, I can't reproduce this. No idea why the searchService would end up using so much memory. Which linux distribution is this/

**Comment by AlexisTM** [comment]
It is Ubuntu 16.04 x64.

It is also recent for me, I never had the issue.

**Comment by roblourens** [comment]
If you press ctrl+p to open the file picker, does the same thing happen?
