### ISSUE TITLE
mismatch on first line of cmd terminal

### ISSUE THREAD

**Issue by GreyElec** [Microsoft/vscode#72408]
![issue](https://user-images.githubusercontent.com/33427038/56207877-6cddc900-6082-11e9-8312-9cc3b99c253a.PNG)
Issue Type: <b>Bug</b>

i found my cmd terminal mismatch on the first line, please help

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (24.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
skill|her|0.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
powershell|ms-|1.12.1
vscode-yaml|red|0.4.0
perforce|sle|3.1.0

(4 theme extensions excluded)

</details>

**Comment by GreyElec** [comment]
suddenly, it works back fine, for no reason, it's werid

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
