### ISSUE TITLE
The value of watch display problem on Linux

### ISSUE THREAD

**Issue by sallyur** [microsoft/vscode#72405]
### Environment:
- VSCode Version: 1.33.1
- OS Version: Linux
- Debugger for java version: 0.18.0

### Steps to Reproduce:

1. Add a watch in vs code 

### Result: 
The row height is not suitable:
![image](https://user-images.githubusercontent.com/28860891/56201772-2d0fe500-6074-11e9-9473-47c343810481.png)

**Comment by isidorn** [comment]
Do you also see this in the explorer (when you try to create a new file), or only in the watch expressions view?

**Comment by ZhengJun003** [comment]
I also see this in the variables view, not appear in the explorer.
Variables view:
![image](https://user-images.githubusercontent.com/41051257/56488200-4bf8f600-6510-11e9-9980-27cf38fd5451.png)

Create a new file:
![image](https://user-images.githubusercontent.com/41051257/56488304-9d08ea00-6510-11e9-938e-c89baf1c50a3.png)

**Comment by isidorn** [comment]
I can not reproduce this on my ubuntu machine with the latest vscode insiders

![Screenshot 2019-05-28 at 16 20 27](https://user-images.githubusercontent.com/1926584/58485545-8e8f9d00-8164-11e9-9f57-512d6637da7e.png)

**Comment by ZhengJun003** [comment]
I can reproduce it before, but can not reproduce this on my Ubuntu machine with 1.33.1 vscode now.

![image](https://user-images.githubusercontent.com/41051257/58525528-9d2a9280-81fe-11e9-91bc-7d238a14eccb.png)
![image](https://user-images.githubusercontent.com/41051257/58525599-ec70c300-81fe-11e9-9837-d293b8ffe203.png)

**Comment by isidorn** [comment]
Great, let's close this then
