### ISSUE TITLE
Terminal crash on `Cmd+b` on mac

### ISSUE THREAD

**Issue by MatanYed** [Microsoft/vscode#72401]
Issue Type: <b>Bug</b>

1. Open side menu
2. Open terminal
3. Click `Cmd+b`

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.54GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
gc-excelviewer|Gra|2.1.32
php-namespace-resolver|Meh|1.1.7
vsliveshare|ms-|1.0.45
vetur|oct|0.18.1

</details>

**Comment by upupming** [comment]
I have tested on mac, but won't get crash

**Comment by MatanYed** [comment]
It usually happens after search (`Cmd+Shift+f`), I didn't find it consistent, but it happened lots of times for me.
The terminal becomes completely black, and if I will try to close the terminal, VSCode will get stuck for some seconds and then a dialog pops up with "the window is no longer responding" message

**Comment by upupming** [comment]
still not reproducible

**Comment by upupming** [comment]
you can test on vscode insiders and report it here again.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
