### ISSUE TITLE
Add hover transparency

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#72400]
Issue Type: <b>Bug(-ish)</b>

Tooltips inside the code editor are really useful, but... Also go away!

When I hover my mouse over something slowly enough in order to find that one spot I need to start typing, a tooltip may show up. I need to be somewhere along the lines I'm looking at. Now a tooltip is obscuring the code I was looking at.

Still not a huge problem.

Now I need to be one or two lines above the word where the tooltip showed up for. How do I make the tooltip go away? I click frantically, but in the process I just select the text in the tooltip? Why would I even want that? Go away! Shoo!

By now, I forgot what I needed to do.

Turns out, I need to move my mouse well away from where I need to be, in order to make the tooltip disappear. By then, my eyes are focused nowhere near where I needed to be in my code. I have to re-find that spot, carefully avoiding that tooltip that ripped my out of my flow earlier.

This is not happening on a single instance. This happens many times a day.

In conclusion:
It must be easier to do away with the tooltip.
I *don't* want it to bother me.
I *do* want it to be useful to me.

In retrospect:
The story above, of course, happens nothing as slowly as I make it out to be. It happens in a second or so. But that second, every time, takes me out of my concentration. I think we all know how that feels.

Proposed solutions:
* Click the tooltip to make it dissappear.
* Have it be "click-through" where clicks on it are actually clicks behind it.
* Have it display away from the mouse cursor's trajectory. Display it above the cursor if moving downward, display below the cursor if moving upward.
* Don't display the helptext as a tooltip at all, but in a fixed position somewhere.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (18.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.4.3
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.11
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.22.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.8
vscode-svg-previewer|vit|0.5.0

</details>

**Comment by alexandrudima** [comment]
Have you tried `"editor.hover.sticky": false` ?

**Comment by thany** [comment]
Better.

But something inbetween would be better. I may sometimes want to select text from it... See proposed solutions. Let's add one more:

* Have it be transparent during mouseover, so it's possible to at least see what's behind it.

Or of course, a combination of my proposed solutions.

**Comment by octref** [comment]
Related: #22439

**Comment by octref** [comment]
You can set this yourself:

```json
"workbench.colorCustomizations": {
  "editorHoverWidget.background": "#ff000015"
}
```

Just change the last 2 digit to any value between 00 and ff.
We won't do this in the core.

**Comment by thany** [comment]
Is that really the best solution?

**Comment by octref** [comment]
I don't think transparency is the solution. If that's what you are after you can use that config. If you have better solution I'd love to learn.

**Comment by thany** [comment]
See my other suggestions. Place the popup according to pointer trajectory.

I'm sure this is possible. I'm not quite sure how difficult it would be, especially for users of pen/touch screen as the only pointing device. In any case it could be optional for those who don't like it.
