### ISSUE TITLE
Theme specific settings

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#72403]
There is no doubt every theme comes with a certain set of functionality and settings, from icon size to menubar background color.

It is helpful for adding custom settings inside `settings.json` file, but for a developer who loves to change theme often doesn't want to use the same theme setting for some other theme.

That's why adding theme specific settings will be helpful.

```json
{
  "pkief.material-icon-theme": { // unique id for each theme (a.k.a extension)
    "workbench.colorCustomizations": {
      "activityBar.border": "#ff000000"
    }
  }
}
```

**Comment by aeschli** [comment]
That already exists, see https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
```json
"workbench.colorCustomizations": {
    "[Monokai]": {
        "sideBar.background": "#347890"
    }
}
```

**Comment by mittalyashu** [comment]
Thanks 😅
