### ISSUE TITLE
After saving any type of files VS messing up formatting (and not only format)

### ISSUE THREAD

**Issue by julia-dizhak** [Microsoft/vscode#72402]
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: mac

Steps to Reproduce:

1. change files
2. try to save (same with auto save )

Does this issue occur when all extensions are disabled?: Yes
I switched off all extensions and it still occurs.

**Comment by octref** [comment]
What do you mean by "VS messing up formatting (and not only format)"? Can you give a file and its messed up format?

**Comment by julia-dizhak** [comment]
Basically, you open any type of file, for example, js. Change smth and all code will move on 2 spaces (or tabs depends on settings) left (after the line of code with last change). It's happening after saving or auto-saving.
Next chage - next 2 spaces move left and so on for js. 
For scss/css files the behavior was weirder, with formatting, moving the cursor to the end of the file and adding some rules.

**Comment by octref** [comment]
Turn off format on save.

**Comment by julia-dizhak** [comment]
@octref hm, but then how I will save files automatically? The problem exists, I can send you my screen recording

**Comment by octref** [comment]
Feel free to post the screen recording here.

> then how I will save files automatically?

Those are two different things.

1. You can turn on `"files.autoSave": "afterDelay"` for auto saving
2. Save triggers "format on save". If the formatting is wrong, can you check what's the formatting setting on the lowerright for the file?

![image](https://user-images.githubusercontent.com/4033249/56677334-276a5e80-6675-11e9-8ddc-1e505c79f3fc.png)
