### ISSUE TITLE
Notification service should help with 'Don't show again'

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#72417]
If you search for 'Don't Show Again' you find roughly 20 matches that are all about showing notifications and not showing them again. All usages do the same, persisting a value in workspace or global storage so that a notification doesn't show again. 

This seems like a good candidate for code-reuse and a unified solution for the "Don't Show Again" problem

<img width="1066" alt="Screenshot 2019-04-16 at 16 39 44" src="https://user-images.githubusercontent.com/1794099/56219250-b7514c80-6066-11e9-8941-32958d606cbf.png">

**Comment by bpasero** [comment]
PR welcome, maybe starting with one example to see the usage before going wild and adopting this everywhere 👍

**Comment by skprabhanjan** [comment]
I can take a look at this.

**Comment by YisraelV** [comment]
@skprabhanjan still working on this or can I take a look?

**Comment by skprabhanjan** [comment]
Hey sorry , didn’t get time to take a look at this !
So anyways , You can work on this :)

**Comment by bpasero** [comment]
The API just got merged (https://github.com/microsoft/vscode/pull/73968), now we need to adopt it. This is still up for grab.

**Comment by YisraelV** [comment]
If anyone wants to take this I'll be happy to get them up to start. 
This shoudn't be hard except testing your changes might be difficult as you have to set up all the scenarios.
