### ISSUE TITLE
"Cannot read property 'line' of null" in node-debug2/chromeDebugAdapter

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#72412]
I'm not sure if this is the right place to raise this, but it looks very similar to #42162. It's not clear if it's the Chrome Debugger extension, or node-debug2, though as far as I know, nothing should be using the Chrome Debugger extension (I'm running a TypeScript VS Code extension).

I see it often in my debug console when I'm debugging the Dart VS code extension (it appears in the main VS Code instance, after I've been running the extension in the dev host).

```
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
    at NodeDebugAdapter.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:792:62)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:7:58)
```

#42162 was resolved as fixed over a year ago, so I don't know if it's the same issue or not.

@roblourens how did track down the issue last time? You can try running the Dart extension from source but it doesn't always seem to happen, so I can do some more digging if you can give me some pointers.

**Comment by roblourens** [comment]
That means something is weird with sourcemaps. Can you share a log? Set `"trace": true` in your node launch config, and it will write the log path in the debug console.

**Comment by DanTup** [comment]
Here's the full log: [vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/3088248/vscode-node-debug2.txt)

It does contain some paths similar to the issue linked above, but not sure if they're the issue (wasn't really sure what to search for).

```
[06:48:57.189 UTC] Could not map start position for: ../node_modules/diagnostic-channel-publishers/dist/src sync ^.*/lib/Connection$
[06:48:57.189 UTC] Could not map start position for: ../node_modules/diagnostic-channel-publishers/dist/src sync ^.*/lib/Pool$
[06:48:57.189 UTC] Could not map start position for: ../node_modules/diagnostic-channel-publishers/dist/src sync ^.*/lib/Connection$
[06:48:57.189 UTC] Could not map start position for: ../node_modules/diagnostic-channel-publishers/dist/src sync ^.*/lib/Connection$
```

**Comment by roblourens** [comment]
Why do people do things like this, haha. Does this break debugging for you or is it just a random error that shows up?

**Comment by DanTup** [comment]
I don't know where the paths are coming from, so I'm not sure they're doing. Does look weird though. The lines I gave look like an MS package: https://github.com/Microsoft/node-diagnostic-channel

I haven't *noticed* anything broken during debugging, but I couldn't be certain. Though I don't expect I'll need to debug through that package above!

**Comment by developermj** [comment]
I have the same issue. My project is using electron-forge with webpack. The issue only shows up if I add "node_modules/**/*.js" to the skipFiles property of the launch config in vscode. I'm at a loss of where to go to try and help provide any additional information to try and help with this issue.

**Comment by roblourens** [comment]
There is a `null` entry in the sourcesContent array of a sourcemap we ship. FYI @digeff you might want to check that case too.

**Comment by roblourens** [comment]
Verification steps

- Open an extension to debug
- Add a skipFiles expression to the launch config like:
```
"skipFiles": [
            "<node_internals>/**"
],
```
- Start debugging the extension
- Open a JSON file
- Check that the error does not show up in the debug console
