### ISSUE TITLE
Closed files linger in problems view

### ISSUE THREAD

**Issue by yllekz** [Microsoft/vscode#72414]
- VSCode Version: 1.33.1
- OS Version: 17763.379

I'm encountering a really frustrating problem. Problems view does not always expunge files that are closed, rather they remain in the view. This happens in particular with large .ps1 and .psm1 files but I've occasionally seen it crop up with smaller files as well.

Continuation of #61241 which was closed with no resolution. Is there a roadmap for fixing this?

Steps to Reproduce:

1. Launch VSCode with the PowerShell extension at a minimum. Open a particularly large .psm1 or .ps1 file of 5000 lines or greater.
2. Close the file, work with other files. Problems view will often not expunge the problems on the file that was closed. Restarting VS Code is the only way to get it to go away.

Does this issue occur when all extensions are disabled?: Yes/No
No. Problem occurs when the PowerShell extension is enabled at a minimum. Unsure if this occurs with other languages.

**Comment by jlave-dev** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
No. Problem occurs when the PowerShell extension is enabled at a minimum.

This issue should be opened in the PowerShell extension repo, then.
