### ISSUE TITLE
Avoid opening a new macOS space when starting VS Code

### ISSUE THREAD

**Issue by loilo** [microsoft/vscode#72411]
> Disclaimer: I am aware that this case may be rather niche, so please take this with a grain of salt.

I'm running VS Code on macOS with a dual monitor setup (large main screen to the left, small secondary screen aka MacBook to the right) where I'm using VS Code on the main screen and a full screen terminal on the secondary screen.

![Visualization of the described setup: A large monitor with a VS Code icon to the left, a smaller laptop with a Terminal icon to the right](https://user-images.githubusercontent.com/1922624/56211303-df857f00-6057-11e9-8213-4726fe919f44.png)

What bugs me a lot is the following behavior of VS Code:

Whenever I open a new VS Code window from the terminal (via the `code` command), that window will open on the secondary monitor in a new space, pushing the fullscreen terminal aside — even if other VS Code windows are already open on the main screen.

I think this behavior can be improved. When VS Code is opened from a fullscreen terminal and another screen is available, VS Code should not be supposed to push the terminal aside but rather open on the screen where no full screen app is running. Maybe this behavior should be configurable, I'm not sure if there are users who'd want to go with the current option.

> For what it's worth: Sublime Text handles this like you'd expect – it opens new windows initiated by the command line on the same screen where existing windows are.

**UPDATE:** Apparently, the described behavior *only* occurs when VS Code is already running. Starting the first VS Code window via `code` will open the app in the place it had been running in previously.

**Comment by bpasero** [comment]
@Loilo we have a setting to disable native fullscreen (`window.nativeFullScreen`) that can be set to false to at least prevent creating spaces for a fullscreen window. But I guess that would not help in this case.

**Comment by Loilo** [comment]
I had read that in another issue and tested it, but it still opens a new space, yes.

**Comment by Loilo** [comment]
FWIW I just discovered a funny workaround by accident:

If my secondary screen *already has* an existing space to the left of the terminal and that space is occupied by another fullscreen app (e.g. another terminal), running `code` on the right space terminal will not create an additional third space but instead open the VS Code window on the main screen. 😁
