### ISSUE TITLE
Inconsistency with debug configuration between Extension Development Host and installed package.

### ISSUE THREAD

**Issue by miniwolf** [Microsoft/vscode#72410]
- VSCode Version: 1.34.0-insider 
- OS Version: Windows 10

Steps to Reproduce:

It seems that my debugger's activationEvent are not getting triggered. 
When I am debugging this through VSCode's Extension Development Host everything works as expected.
However when I install my package, and try to replicate, it does not work. 

The problem that I see is that when I try to add a debugger configuration, it does not show my specific label. However, when doing this in the Extension Development Host everything works.

How can I debug and get more information about why this happens?

**Comment by weinand** [comment]
What exactly do you mean by "when I try to add a debugger configuration, it does not show my specific label"?

**Comment by miniwolf** [comment]
When you want to debug, and get a list of configurations to choose from, my label is not displayed.
You get this list by clicking the cogwheel under the debug view.

**Comment by miniwolf** [comment]
![image](https://user-images.githubusercontent.com/710238/56214181-b2d46600-605d-11e9-93e2-06709a60b697.png)
This cogwheel, gives you a list of configurations that you can generate your launch.json from. And my label is not added to the list. Only in Extension Development Host mode.

**Comment by isidorn** [comment]
Please fork the vscode mock debug extension https://github.com/Microsoft/vscode-mock-debug
Create a reproducable case, give me the steps and I can investigate more.
Thanks

**Comment by miniwolf** [comment]
I actually was yes. If I go to package.json and delete the `initialConfigurations` and `confiugrationSnippets` from the `contributes.debuggers` then I get the same behaviour. 
I will double check, but it seems to be correct.

**Comment by miniwolf** [comment]
My activation events are "*" event though it is not recommended, but I tried modifying it to different triggers, without any results.
Regardless of if I have a file open or not it does not produce my label in the list of the debugger configuration.

**Comment by isidorn** [comment]
Thanks. 
Please create reproducable steps using the vscode mock debug.

An alternative is F1 > devleoper tools > open source tab > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/ff6ef95b2ba4ebaca9dd85a7dd58199ac781e8b4/src/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.ts#L428)

Figoure out why your debug adapter is not in the list.

**Comment by miniwolf** [comment]
So the steps to reproduce are first to apply this diff:
```
diff --git a/package.json b/package.json
index fd05bc5..0bed53a 100644
--- a/package.json
+++ b/package.json
@@ -93,28 +93,6 @@
                                                }
                                        }
                                },
-                               "initialConfigurations": [
-                                       {
-                                               "type": "mock",
-                                               "request": "launch",
-                                               "name": "Ask for file name",
-                                               "program": "${workspaceFolder}/${command:AskForProgramName}",
-                                               "stopOnEntry": true
-                                       }
-                               ],
-                               "configurationSnippets": [
-                                       {
-                                               "label": "Mock Debug: Launch",
-                                               "description": "A new configuration for 'debugging' a user selected markdown file.",
-                                               "body": {
-                                                       "type": "mock",
-                                                       "request": "launch",
-                                                       "name": "Ask for file name",
-                                                       "program": "^\"\\${workspaceFolder}/\\${command:AskForProgramName}\"",
-                                                       "stopOnEntry": true
-                                               }
-                                       }
-                               ],
```
2. You open the project in VSCode and press F5 to get into Extension Development Host mode.
3. Now you try to debug any project, and see that Mock Debug is in the list of debug configurations.
4. You make a vsix file by using the "`vsce package`" command.
5. Install this extension and try step 3. again. Now you will not see Mock Debug in the list. (This is the problem)

**Comment by miniwolf** [comment]
Thank you for the debug idea, I will try to do that and see if I can come up with something.

**Comment by miniwolf** [comment]
No the repro steps, are not valid. I will try again.

**Comment by miniwolf** [comment]
Alright so the steps above are the same apart from the diff: 
```
diff --git a/package.json b/package.json
index fd05bc5..0bed53a 100644
--- a/package.json
+++ b/package.json
@@ -93,28 +93,6 @@
                                                }
                                        }
                                },
-                               "initialConfigurations": [
-                                       {
-                                               "type": "mock",
-                                               "request": "launch",
-                                               "name": "Ask for file name",
-                                               "program": "${workspaceFolder}/${command:AskForProgramName}",
-                                               "stopOnEntry": true
-                                       }
-                               ],
-                               "configurationSnippets": [
-                                       {
-                                               "label": "Mock Debug: Launch",
-                                               "description": "A new configuration for 'debugging' a user selected markdown file.",
-                                               "body": {
-                                                       "type": "mock",
-                                                       "request": "launch",
-                                                       "name": "Ask for file name",
-                                                       "program": "^\"\\${workspaceFolder}/\\${command:AskForProgramName}\"",
-                                                       "stopOnEntry": true
-                                               }
-                                       }
-                               ],
                                "variables": {
                                        "AskForProgramName": "extension.mock-debug.getProgramName"
                                }
diff --git a/src/extension.ts b/src/extension.ts
index 1fb5561..80e1e91 100644
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -43,6 +43,18 @@ export function deactivate() {

 class MockConfigurationProvider implements vscode.DebugConfigurationProvider {

+       provideDebugConfigurations(folder: WorkspaceFolder | undefined, token?: CancellationToken): ProviderResult<DebugConfiguration[]> {
+               const config = [
+                       {
+                               "type": "mock",
+                               "request": "launch",
+                               "name": "Ask for file name",
+                               "program": "${workspaceFolder}/${command:AskForProgramName}",
+                               "stopOnEntry": true
+                       }
+               ];
+               return config;
+       }
        /**
         * Massage a debug configuration just before a debug session is being launched,
         * e.g. add all missing attributes to the debug configuration.
```

**Comment by isidorn** [comment]
Please apply those difs on your fork of mock debug. I do not want to copy paste patches like it is 1985

**Comment by miniwolf** [comment]
Here is the diff on our fork: https://github.com/Unity-Technologies/vscode-mock-debug/commit/bbb7314bf24deaab0f3f59f1008f19edf14b38b2

**Comment by isidorn** [comment]
Works for me using your version of node debug
The issue for you is that your probably have some file open, and when you click on the configure, VSCode does not pick your adapter since it is not regsitered as an adapter for that language.
Here's how node is doing it as an example 
https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L162

![Screenshot 2019-04-17 at 16 13 28](https://user-images.githubusercontent.com/1926584/56294681-c221e500-612b-11e9-943c-39cc351a3fae.png)
