### ISSUE TITLE
Letterpress background image in editor area should be SVG

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7242]
Noticed it is still using PNG which does not scale nicely when you zoom in:

<img width="622" alt="screen shot 2016-06-06 at 10 54 59" src="https://cloud.githubusercontent.com/assets/900690/15816819/2201858c-2bd5-11e6-8f92-3f899ca78661.png">

**Comment by joaomoreno** [comment]
Probably not worth doing due to the drop shadow, but an `@2x` png would work.

**Comment by bpasero** [comment]
@joaomoreno we do have a @2x version afaik, at least there are multiple PNGs.

**Comment by joaomoreno** [comment]
If you inspect the DOM, aren't we using it, then?

**Comment by bpasero** [comment]
@joaomoreno we do, it just seems bad when you zoom in. I was not aware of the issue with the shadow, so if we cannot get this with the SVG, then we can close this.

**Comment by joaomoreno** [comment]
Oh I see what you mean! It might be [possible](http://stackoverflow.com/a/6094674/261019), so let's just let @bgashler1 decide.

**Comment by joaomoreno** [comment]
@bgashler1 @bpasero 

The letterpress is now worse, imo: it is simply the VS logo with an outline. It used to be an inset VS logo, which is the whole style of a letterpress.
