### ISSUE TITLE
i can't run as root though i specify an alternate user data directory with the --user-data-dir argument

### ISSUE THREAD

**Issue by fregie** [Microsoft/vscode#7243]
- VSCode Version:1.1.1
- OS Version:ubuntu 14.04

Steps to Reproduce:

1. sudo code --user-data-dir /home/fregie/.config/Code/
2. It is recommended to start vscode as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument.

**Comment by darryldalton** [comment]
I had the same issue. I was able to finally get it to work by running ...
`sudo code . --user-data-dir='.'`

**Comment by Tyriar** [comment]
`sudo code --user-data-dir /home/fregie/.config/Code/` doesn't work because it needs to be a new user data directory, one whose permissions are not as restrictive as `.config`. This should work:

```
sudo code --user-data-dir /home/fregie/.code-root-user-data
```

Note that once we reshuffle the configuration directories this will no longer be necessary to explicitly indicate the root user data dir. See #5570 and #2741

**Comment by lovettchris** [comment]
I had the same problem, but after reading this thread very closely I found the magic trick.  The command line requires and equals sign (=) between the --user-data-dir and the actual directory, which is NOT indicated by the --help.  

usage:   --user-data-dir=path

would be nice to fix the help or remove the '=' (which would be more consistent with most other unix tools)...

**Comment by razvan-panda** [comment]
As a root user inside a VM I used: `code --user-data-dir=~/.config/Code/` and also added the same to the command line inside KDE menu.

Not sure how to set it though so that it always uses that path when launching it from Konsole as that would be very useful.
