### ISSUE TITLE
Download broken?

### ISSUE THREAD

**Issue by rclai** [Microsoft/vscode#72438]
https://code.visualstudio.com/docs/?dv=osx

**Comment by rulas** [comment]
Also, getting "Not Found" when tried to download it for Windows https://update.code.visualstudio.com/latest/win32-x64-user/stable

**Comment by dalecosp** [comment]
Concur.

**Comment by dalecosp** [comment]
https://update.code.visualstudio.com/1.33.1/win32-x64-user/stable

"Internal Server Error".

**Comment by opiyonico** [comment]
Also same issue, Not Found!

**Comment by volare2016** [comment]
can't download...

**Comment by mapsdev** [comment]
Same here:
https://update.code.visualstudio.com/latest/linux-deb-x64/stable

**Comment by flametrav** [comment]
same issue even tried switching an os

**Comment by av8rgeek** [comment]
Same issue, but with the MacOS release.  Tried other platforms and got the same "Not Found!" error.

**Comment by gabriel-lima-dev** [comment]
Yep, same thing. Can't download.

**Comment by ArsBarsj** [comment]
For linux you can try `snap remove vscode` and `snap install code --classic`

**Comment by StevenSeifried** [comment]
Same here

**Comment by creativeguy2013** [comment]
The vscode team is aware of the situation. It does not help when you comment "same thing". Unless you have constructive help on the issue, please do not comment. Github has reaction buttons which you can use to show the team that you are experiencing the issue.

**Comment by johndroid202** [comment]
I noticed that releases from March 2018 and earlier were on vscode-update.azurewebsites.net
so I copied and edited the link to this and it worked for me
https://vscode-update.azurewebsites.net/1.33.1/win32-x64/stable

**Comment by rakeshvanga** [comment]
seeing this error as well when installing dependencies for a vscode extension.
`npm install`
`Detected VS Code engine version: ^1.34.0
 Error installing vscode.d.ts: Error: Request returned status code: 500 
Details: Internal Server Error`

**Comment by tblong** [comment]
Download works again now for me.

**Comment by octref** [comment]
Downloads should be working again. Sorry for the interruption. Looking into why this is happening now.

**Comment by octref** [comment]
Here's what happened:

- Around 2pm PDT, we are notified about download failing
- Around 3:30pm, we identified the failing node and took it off traffic balancer, so public API stop failing
- Around 5pm, we fixed the failing node and brought it back to the traffic balancer
