### ISSUE TITLE
Word Wrap shortcut doesn't work

### ISSUE THREAD

**Issue by HeyLookItsBrandon** [microsoft/vscode#72435]
Issue Type: <b>Bug</b>

On Mac, when I press option-Z to toggle word wrap, nothing happens. Selecting it from the menu works as expected.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|-psn_0_151589|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.22.1
java|red|0.42.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1

</details>

**Comment by alexandrudima** [comment]
@HeyLookItsBrandon 

Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by HeyLookItsBrandon** [comment]
Hi @alexandrudima. Thanks for the followup and sorry for the delay getting back to you. I have never changed the key mappings, so Option-Z should have been assigned to word wrap. That's the only mapping I'm seeing for that key combination now. However, I'm using VS Code 1.34.0 now and the issue seems to be resolved.
