### ISSUE TITLE
Watched Array Item is Empty - but only under WATCH

### ISSUE THREAD

**Issue by cawoodm** [Microsoft/vscode#72433]
- VSCode Version: 1.33.1 user
- OS Version: Windows 10
Debugging PowerShell: an array value is shown as an empty string on the left but it's plainly not empty on hover or under locals:

![image](https://user-images.githubusercontent.com/498834/56234327-571dd300-6085-11e9-9cde-68599d12099f.png)

**Comment by cawoodm** [comment]
No, I disabled all extensions except the PowerShell extension required for debugging, restarted, and the problem still occurs.

![image](https://user-images.githubusercontent.com/498834/56263368-fa510580-60e2-11e9-8c37-a10eee7c2258.png)

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.
