### ISSUE TITLE
Trying to download older version of vscode gives "Internal server error"

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#72445]
For instance, https://update.code.visualstudio.com/1.26.1/darwin/stable, but repros for any version and any platform.

**Comment by miparnisari** [comment]
Related: the "Mac" link in https://code.visualstudio.com/Download is broken

**Comment by rakeshvanga** [comment]
seeing this error as well when installing dependencies for a vscode extension
`Detected VS Code engine version: ^1.34.0
Error installing vscode.d.ts: Error: Request returned status code: 500
Details: Internal Server Error`

**Comment by StephenWeatherford** [comment]
Working now.
