### ISSUE TITLE
Don't want any updates from untrustworthy Microsoft

### ISSUE THREAD

**Issue by FuckYouMicrosoft** [Microsoft/vscode#72449]
Despite me not wanting to change versions i.e. update, it seems that I am being forced to do so anyway. This is a bug. It is ignoring the user's i.e. me (a human) needs. I don't want an updated version... I've seen what updates from Microsoft do to perfectly working products. It f.ucks them, that's what it does. Yesterday I spent hours of my work time simply trying to get my (previously perfectly working and fitting my purpose) f.u.cking network working again to show all my networked folders - but was never able to succeed. This was following Microsoft's instructions on how to share folders!!! I in the end had to move hundreds of gigabytes of my data instead to the public folder - because for some reason that works perfectly... but anything that involves me once again having a secure system again seems to have been thrown out of the window when you idiots decided to remove the HomeGroup stuff. I got recommend to use OneDrive instead!!!! Why the f.uck would I want to spend all my time copying my fuc.king files to OneDrive so that I can share them on my local network PRIVATELY!!!! You know what... f.uck you ... I'm fucking over this! I'd hope somebody drops a fucking nuclear weapon on Redmond, but I actually want you fuckers to suffer... so instead I'll wish for a lone gunman with lots of ammunition. It couldn't happen to a more deserving bunch of fuckwits! Even your company's founder despises the direction you are forcing us to go.. that should tell you something... but you've been so deaf to your customers for so many years that you've probaly forgotten how to listen to people who actually know what they are talking about. Anyway... rat-a-tat-a-tat ... listen out for that sound... it's your karma coming to get you. I can't wait to see some dead bodies being pulled from a Redmond building on the news soon... I will laugh and laugh and laugh and laugh... because finally somebody managed to get through to you fuckers in a way you are forced to listen to. Fuck with people, and eventually they'll fuck with you. You can't expect to continue stealing our future without some reprisals... I won't be doing them... but I'll be there in spirit encouraging anybody with a good semi-automatic, a crazy look and a short ride to Redmond, to give you some feedback that you actually can't ignore for a change.

**Comment by octref** [comment]
You can use setting `"update.mode": "none"`.
