### ISSUE TITLE
"runOn": "folderOpen" does not work

### ISSUE THREAD

**Issue by jaens** [Microsoft/vscode#72448]
Issue Type: <b>Bug</b>

I added the following task to an existing project (to tasks.json):
```
    {
      "type": "shell",
      "label": "NPM watch",
      "command": "npm run watch",
      "isBackground": true,
      "problemMatcher": ["$tsc-watch"],
      "runOptions": { "runOn": "folderOpen" }
    },
```

I can run the task manually, but when I open the folder, it does not auto-start. I understand there is supposed to be a notification that asks you to confirm it, but that does not show up either.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.8.1
code-beautifier|mic|2.2.1
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
vscode-lua|tri|0.12.4
vscode-icons|vsc|8.5.0

</details>

**Comment by alexr00** [comment]
We don't show the notification to enable automatic tasks until after you have run a task. We didn't want to spam users with a notification that pops up when you open the window. So if you run any task, the notification will show up when the task is complete. You can also run the command`Tasks: Allow Automatic Tasks in Folder` from the command palette to enable the automatic tasks.

**Comment by jaens** [comment]
I see... the task in question never terminates (it's a watch task), so the notification never pops up.
