### ISSUE TITLE
Right Click Menu Closing Without User Input

### ISSUE THREAD

**Issue by RossBrunton** [Microsoft/vscode#72447]
* Be on Linux Mint Cinnamon (I've tested it with a live CD running in a VM with a fresh VSCode install, and it still occurs).
* Right click in the editor buffer.
* Leave the mouse alone and wait.
* Eventually, the right click menu will close on its own without user input. This seems to happen after a random amount of time. Sometimes while I'm moving my mouse to select an option.

VS Code version: Code - OSS 1.34.0 (0b81f3553ea26cc3f8ea015371841a68d74b7a35, 2019-04-10T19:47:30.122Z)
OS version: Linux x64 4.15.0-47-generic

**Comment by sbatten** [comment]
@RossBrunton do you have any extensions installed that could be contributing codelens? If so, do you notice the codelens popping up at the same time as the dismissal?

**Comment by RossBrunton** [comment]
I've tested it with only the default extensions installed, and it still happens then. I've also tried it on that "background" screen with the VSCode logo you get when you close all the tabs, and the "tab selector" toolbar thing on the left side. The issue still occurs on both those.

**Comment by sbatten** [comment]
@bpasero just discovered that [this](https://github.com/electron/electron/issues/17341#issuecomment-476457183) is likely the cause of the issue for us. Seems just like the app menu bar issue we saw before. See dumb fix which I think works.

**Comment by bpasero** [comment]
@sbatten very good find, this is quite crazy. I often saw the context menu closing at random on macOS too btw.
