### ISSUE TITLE
Errors in Untitled files stay around

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7244]
1. Create a new Untitled file
2. Type `const hello;` in it
3. Change its mode to JavaScript
4. Close the file, don't save

There is an error laying around in the Problems view

**Comment by dbaeumer** [comment]
Will investigate. Very likely the tsserver not cleaning up correctly.

**Comment by dbaeumer** [comment]
This is ESLint.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#84
