### ISSUE TITLE
[Feature] An option to move the activity bar to the top 

### ISSUE THREAD

**Issue by filtration** [microsoft/vscode#72443]
Currently you have the activity bar on the left side, would an option to have it at the top be good?

For example VS for mac has a menu bar like so:

<img src="https://i.imgur.com/42laKxz.png">

Vscode top menu bar would look similar (better than this screenshot)

<img src="https://i.imgur.com/nNvXPaS.png">

**Comment by hujianxin** [comment]
It's good to have some options to tune activity bar itself
