### ISSUE TITLE
Enable or expose ripgrep’s --auto-hybrid-regex flag to use PCRE2 only if necessary

### ISSUE THREAD

**Issue by roryokane** [microsoft/vscode#72459]
Motivated by VS Code issue #64606, ripgrep [has gained](https://github.com/Microsoft/vscode/issues/64606#issuecomment-483060850) the `--auto-hybrid-regex` flag, which “will automatically fall back to PCRE2 if Rust's regex engine fails to compile the regex”. The flag was added to ripgrep [in version 11.0.0](https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md#1100-2019-04-15).

VS Code currently has a boolean setting `search.usePCRE2` that is the equivalent of the `-P`/`--pcre2` flag for ripgrep. It forces PCRE2 to be enabled all the time, but [as @roblourens observed in #64606](https://github.com/Microsoft/vscode/issues/64606#issuecomment-452400155), this can cause searches that don’t use PCRE2-only features to be slower than necessary.

I can think of two possible ways to improve VS Code given the availability of ripgrep’s hybrid regex engine feature:

- VS Code could **change `search.usePCRE2` to a three-state setting** where the options are “never” (no flag), “always” (`--pcre2`), or “only if necessary” (`--auto-hybrid-regex`).
- VS Code could **remove the `search.usePCRE2` setting** completely and always use `--auto-hybrid-regex`.

That second option would “just work” in most cases and would lessen the amount of configuration the user has to manage, but ripgrep’s documentation for `--auto-hybrid-regex` notes one possible downside:

> The primary downside of using this flag is that it may not always be obvious which regex engine ripgrep uses, and thus, the match semantics or performance profile of ripgrep may subtly and unexpectedly change. However, in many cases, all regex engines will agree on what constitutes a match and it can be nice to transparently support more advanced regex features like look-around and backreferences without explicitly needing to enable them.

So I am not really sure which is the better option. I do think most users will at least want `--auto-hybrid-regex` to be set by default, even if they have to override it after experiencing unexpected match semantics or unexpected performance problems.

**Comment by roblourens** [comment]
Yes, I would prefer to remove `search.usePCRE2`, at least in the long term. I would probably take the conservative approach and keep a setting to opt in/out at first.

**Comment by roblourens** [comment]
Verification: Without `search.usePCRE2` set, you should be able to search using lookahead. The setting will remain with a deprecated message and can still force the `--pcre2` flag if we need it for testing.
