### ISSUE TITLE
Text being overwritten

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [Microsoft/vscode#72456]
Issue Type: <b>Bug</b>

When using autocomplete to fill in a variable or parameter name,  if there's text next to it, it seems to switch into insert mode for a second and part of the following text is overwritten. So it'll go from  ["|" indicates caret]
`myFunc(samplePa|:);`
to
`myFunc(sampleParam|:` <- notice no closing parenthesis or semicolon. 
this doesn't happen all the time, but it happens enough. May have something to do with the Flutter or Dart plugin

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0 (MacOS Mojave (10.14)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-monokai-seti|adi|0.0.5
flutter-snippets|ale|1.1.0
dart-code|Dar|2.25.0
flutter|Dar|2.25.0
bloc|Fel|0.5.0
code-runner|for|0.9.8
output-colorizer|IBM|0.1.2
intellij-idea-keybindings|k--|0.2.31
chat|kar|0.13.0
vscode-gist|ken|3.0.3
vsliveshare|ms-|1.0.45
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.12
java|red|0.42.1
git-merger|sha|0.4.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1

(1 theme extensions excluded)

</details>

[Edit] Got it on [video](https://streamable.com/nhmp1)

**Comment by ThinkDigitalRepair** [comment]
@jrieken edited issue with a video link

**Comment by jrieken** [comment]
What language is this? What is your code sample?

**Comment by ThinkDigitalRepair** [comment]
This is Dart. I have no code sample because it's not doing it in response to the code, just autocomplete, so any thing could cause it and that same thing could not cause it, as shown in the video. If you have a chance to watch it, it's linked at the bottom of the post.

**Comment by ThinkDigitalRepair** [comment]
I haven't been able to recreate it reliably

**Comment by jrieken** [comment]
Ok, saw the video. This must be caused by the dart extension you are using. by default we don't replace text to the right (we only have a default for the prefix) and it must be dart giving us the wrong range to replace

**Comment by ThinkDigitalRepair** [comment]
Makes sense to me, thank you!
