### ISSUE TITLE
Upgraded to Mojave 10.14.4 and now can't launch vscode

### ISSUE THREAD

**Issue by bobwiller** [Microsoft/vscode#72455]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bobwiller** [comment]
VS Code version 1.33.0
OS Version: macOS 10.14.4 (18E226)

Updated MacOS tonight, and now I can't launch visual studio code w/o running it as sudo which is not...optimal.

When launching via code --verbose, here is the output:

[main 2019-04-17T02:02:20.242Z] Error: connect EACCES /Users/admin/Library/Application Support/Code/1.33.0-main.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
[main 2019-04-17T02:02:20.243Z] Lifecycle#kill()

I assume the update has changed some file/folder permissions...

**Comment by bpasero** [comment]
This signals a configuration problem and nothing VSCode fault. Make sure the directory is writeable for your logged in user and VSCode.
