### ISSUE TITLE
Syntax highlighting broken for PHP

### ISSUE THREAD

**Issue by hworld** [Microsoft/vscode#7245]
- OS Version: Fedora 24

Version 1.2.0-insider
Commit 7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f
Date 2016-05-30T13:06:09.365Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

For some reason PHP syntax highlighting is broken for me on latest insiders build. I tried switching to different color themes but that didn't change anything. It looks like only PHP is broken. It's correctly detecting it as PHP (it shows in the lower right). All other file types are working fine. I installed any extensions having to do with PHP and nothing worked. Reverting back to the previous Insiders build works. I've attached a view of what I see.

![screenshot from 2016-06-06 11-46-51](https://cloud.githubusercontent.com/assets/1024321/15818294/ec0baebe-2bdc-11e6-9b68-3885e0652605.png)

**Comment by aeschli** [comment]
Hmm, strange. All seems to work for me with a fresh install on 1.2-insiders:
![image](https://cloud.githubusercontent.com/assets/6461412/15850280/73351f6e-2c97-11e6-8ed3-cb709f305129.png)

That's the Dark+ theme. What platform are you? Can you try to run vscode without any extensions?
`code-insiders --disable-extensions`

**Comment by hworld** [comment]
Hey, that helped a ton! I didn't realize there was a way to launch without extensions. It worked, so then I was able to move out my extensions one by one until I found the culprit. It was a random syntax ext. I had made months ago to fix the fact that vscode wasn't highlighting angular2 templates correctly (because of the weird [] * and () syntax in the attributes). Not related to PHP, but I'm sure the config of it broke it somehow. 

Either way, it's not needed anymore since vscode supports angular2 syntax by default.

Thanks!

**Comment by myfonj** [comment]
For me the offending extension that disabled PHP syntax coloring was [sodatea.velocity](https://marketplace.visualstudio.com/items?itemName=sodatea.velocity) namely presence of the [HTML.tmLanguage](https://github.com/sodatea/vscode-velocity/blob/master/syntaxes/HTML.tmLanguage) file. (Apparently.)
