### ISSUE TITLE
watcherexclude don't work

### ISSUE THREAD

**Issue by JWleo** [microsoft/vscode#72458]
vscode :1.33.1
Osystem: fedora 28     64-bit

i have written /build/  into the watcher-exclude like this.
![Screenshot from 2019-04-17 10-44-49](https://user-images.githubusercontent.com/32316654/56257418-b23fdc00-60fe-11e9-9682-0493e4d6d5a4.png)

But when i cmake or make the project, it always assert me like this picture.
![Screenshot from 2019-04-17 10-44-20](https://user-images.githubusercontent.com/32316654/56257507-0b0f7480-60ff-11e9-9e40-165cc98f1df0.png)

**Comment by bpasero** [comment]
@JWleo could it be that you are in a multi-root workspace or is this a single folder workspace?

**Comment by JWleo** [comment]
> @JWleo could it be that you are in a multi-root workspace or is this a single folder workspace?

a single folder workspace like this.
<img width="227" alt="Screenshot from 2019-04-17 13-49-12" src="https://user-images.githubusercontent.com/32316654/56264225-613ce180-6118-11e9-9da4-57bfb4eb1729.png">

**Comment by bpasero** [comment]
@JWleo could it still be that there are other large folders being watched, can you check?

**Comment by JWleo** [comment]
@bpasero NO.The assert just show up in the process of building.
                When i build it in this project,all the new-produced files just put into the build file.

**Comment by husseinraoouf** [comment]
happens with me on code-insider 1.37, also search.exclude isn't working
it gets search result form node_modules

**Comment by husseinraoouf** [comment]
I have downgraded to the stable version for now and it works
