### ISSUE TITLE
Ubuntu release does not show errors or warnings

### ISSUE THREAD

**Issue by flametrav** [Microsoft/vscode#72450]
Hi! I am new to Ubuntu and still having issues, one of them is that visual studio code does not recognize any syntax errors or warning (missing variables, etc) at all (even after debugger fails)  using Js, Python, and HTML.

Thanks in advance for any help!

- VSCode Version: 1.33.1 (installed from the snap store)
- OS Version: Ubuntu 18.10 cosmic

**Comment by octref** [comment]
For JS you need to open a project, see https://code.visualstudio.com/docs/nodejs/working-with-javascript
For Python you need to install Python extension, see https://code.visualstudio.com/docs/python/python-tutorial.

**Comment by flametrav** [comment]
Hey @octref I did use an extension for Python and JS, sorry if it wasn't clear
