### ISSUE TITLE
Fall back to built-in formatter if one specified in settings is unavailable

### ISSUE THREAD

**Issue by ecraig12345** [Microsoft/vscode#72462]
Issue Type: <b>Feature Request</b>

Sort of a follow-up to #71400: If the formatter specified under `editor.defaultFormatter` for a language is unavailable, and a built-in formatter for that language exists, I think VS Code should fall back to the default formatter (maybe with a warning?) rather than refusing to format the file.

(Some other possible approaches would be to make `editor.defaultFormatter` accept an array specifying the order of precedence for formatters, or add yet another setting specifying whether falling back to the default formatter is allowed.)

#### Scenario

The main project I work on uses Prettier for formatting. I have the extension installed, but I disable it globally and *only* enable it in workspaces with a Prettier config (because I find some of Prettier's behavior obnoxious and don't always want to use it). 

Previously, formatting on save or on demand seemed to use Prettier if it was enabled, then fall back to the default formatter. After a recent update, I got a prompt to choose a default formatter, and I chose Prettier since that's what I use most often. But now when I try to format a file in a workspace where the Prettier extension is disabled, I get a message (added in #71531 apparently):
> Extension 'esbenp.prettier-vscode' is configured as formatter but not available. Select a different default formatter to continue.

This means I'm **entirely unable to format files** without tweaking more settings. There are workarounds, but none are great:
- Changing the formatter in user settings when I go to a different project: obviously annoying 
- Setting the formatter to prettier in the main projects: Not a great option because many people work on these projects, and the setting would cause anyone who doesn't happen to have Prettier installed to get a cryptic error message and be unable to format files.
- Setting the formatter to built-in in each secondary project: Also not a great option because these projects are usually either quick one-off things (where I may not have workspace settings), or it's in some repo where I can't permanently modify/add workspace settings

---

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

**Comment by jrieken** [comment]
> Setting the formatter to prettier in the main projects: Not a great option because many people work on these projects, and the setting would cause anyone who doesn't happen to have Prettier installed to get a cryptic error message and be unable to format files.

That's the idea. A team working together on a project shall agree on a formatter and use the default formatter as a shared setting (as manifestation of the agreement). In consequence everyone will have prettier installed. 

With your selective enable/disablement of prettier you seem to have found a workable solution already.

**Comment by ecraig12345** [comment]
No, I haven't found a workable solution. That's the whole point of filing this issue...

**Comment by svipas** [comment]
I totally agree with @ecraig12345 now I should specify every formatter individually:

```
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
// ... JS, etc...
```

Because if I format `Go` file I get `Extension 'Prettier - Code formatter' cannot format 'src/main.go'`

<img width="1136" alt="Screenshot 2019-05-07 at 08 07 30" src="https://user-images.githubusercontent.com/10441177/57273102-2f77c480-709f-11e9-9bbd-495d04177b86.png">

@jrieken, In my opinion, it should fallback to the formatter which is not specified in `editor.defaultFormatter`.

Or I should use this solution:

```
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[go]": {
    "editor.insertSpaces": false,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.defaultFormatter": "ms-vscode.Go"
  },
```

But this also leads to the same problem mentioned above because now I should include every other language I do not want to use Prettier as formatter.

**Comment by svipas** [comment]
@ecraig12345 As I workaround I found that `"editor.formatOnSave": true` uses Prettier and I don't need to use `editor.defaultFormatter`, but now you will format your file on every save.
