### ISSUE TITLE
Icon for pug is different for language mode and file type.

### ISSUE THREAD

**Issue by adamdune** [Microsoft/vscode#72464]
The icon for pug file type is different than the one for language mode (Jade icon).

![Screenshot_30](https://user-images.githubusercontent.com/39018755/56263204-9ba47f80-6114-11e9-87ae-b7fcb613486a.png)

Maybe this was intentional, so people who didn't hear about Jade's name change can find the language mode. In that case, sorry for opening the issue pointlessly.

- VSCode Version: 1.33.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create file with .pug extension.
2. Select language mode.
3. Search for 'pug'

Does this issue occur when all extensions are disabled?: No

**Comment by yume-chan** [comment]
Can reproduce with the built-in "Seti (Visual Studio Code)" icon theme.

Looks like the "pug" file extension and "jade" language ID are using different icons.

("pug" file extension)
https://github.com/Microsoft/vscode/blob/fe31e7bfb96b242094332bd324b88f4000b42b27/extensions/theme-seti/icons/vs-seti-icon-theme.json#L1329
https://github.com/Microsoft/vscode/blob/fe31e7bfb96b242094332bd324b88f4000b42b27/extensions/theme-seti/icons/vs-seti-icon-theme.json#L885-L886

("jade" language ID)
https://github.com/Microsoft/vscode/blob/fe31e7bfb96b242094332bd324b88f4000b42b27/extensions/theme-seti/icons/vs-seti-icon-theme.json#L1501
https://github.com/Microsoft/vscode/blob/fe31e7bfb96b242094332bd324b88f4000b42b27/extensions/theme-seti/icons/vs-seti-icon-theme.json#L573-L574

**Comment by yume-chan** [comment]
As the comments in "vscode/extensions/theme-seti/icons/vs-seti-icon-theme.json" say:

https://github.com/Microsoft/vscode/blob/fe31e7bfb96b242094332bd324b88f4000b42b27/extensions/theme-seti/icons/vs-seti-icon-theme.json#L2-L9

You may open an issue to [jesseweed/seti-ui](https://github.com/jesseweed/seti-ui) for it.

**Comment by adamdune** [comment]
@yume-chan Oh I see, I was unaware the issue needed to be opened there since Seti Icon Theme is bundled with VSCode by default.

Thank you very much, sir.
