### ISSUE TITLE
git 崩溃，扩展崩溃

### ISSUE THREAD

**Issue by Baogh** [microsoft/vscode#72468]
Issue Type: <b>Bug</b>

在进行git分支切换或者merge时偶尔会出现扩展崩溃的情况

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|1.0.0
iview-snippets|bos|0.2.1
htmltagwrap|bra|0.0.7
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.6.0
EditorConfig|Edi|0.13.0
carbon-now-sh|eri|1.2.0
php-debug|fel|1.13.0
beautify|Hoo|1.4.11
vscode-language-pack-zh-hans|MS-|1.33.2
debugger-for-chrome|msj|4.11.3
vsc-netease-music|non|0.0.14
vetur|oct|0.18.1
minapp-vscode|qiu|1.13.0
LiveServer|rit|5.5.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.8
easysass|spo|0.0.6
vscode-icons|vsc|8.5.0

(1 theme extensions excluded)

</details>

**Comment by KexyBiscuit** [comment]
Please disable extensions and try again, if the issue occurs only with specific extension enabled, it's recommended to report this to the maintainer of that extension.
请禁用所有扩展再试，如果问题只出现于特定扩展启用时，建议向扩展维护者报告。

**Comment by octref** [comment]
When it happens, please provide all error log from Help -> Developer Tools.

**Comment by vsTianhao** [comment]
Change to English
