### ISSUE TITLE
Can't start extension tests from within Code anymore?

### ISSUE THREAD

**Issue by spmeesseman** [Microsoft/vscode#72460]
I can no longer run my extension tests from an npm task from within VSCode.  Is this intended?  I have always ran my tests from an npm task, i.e.:

`npm run test`

Where 'test' is defined in my package.json scripts section:

`"test": "node ./node_modules/vscode/bin/test"`

Pretty sure it worked in 1.33.0, definitely worked prior to 1.33.  Works fine from the command line if VSCode is not running, as the error clearly states it will.

- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Run "node ./node_modules/vscode/bin/test" in an extension project from within VSCode terminal or from a VSCode task.
2.  An error is displayed that tests cannot be ran from the command line when there is already an instance of VSCode running.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
This is how it has been working. You can only run extension test from stable when no other instances are running. So either quit Code and run it from terminal, or develop and run it from https://code.visualstudio.com/insiders/.
