### ISSUE TITLE
Search indicator

### ISSUE THREAD

**Issue by przemokon** [microsoft/vscode#72466]
Issue Type: <b>Bug</b>

When i go back to file when i searched for a passphrase, indicator shows me that my selected occurence is first(1), after going forward in search indicator shows actual value.

How to reproduce:
1. Open a file and search for repeated phrase
2. Go to second or third occurence of phrase
3. Go to next opened file in VS Code
4. Go back to file where search was
5. Look at indicator, it shows 1 and not your last search position (i.e. 2 or 3)
6. Search next phrase (indicator go back to correct value)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (11.16GB free)|
|Process Argv|C:\Users\pokoniewski\Desktop\butor-mirjan24.hu-error_log|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
vscode-faker|dee|1.3.0
vs-code-xml-format|fab|0.1.5
code-runner|for|0.9.8
beautify|Hoo|1.4.11
smarty|imp|0.3.0
vscode-placeholder-images|Jak|0.1.0
css-grid-snippets|oha|0.0.5
material-icon-theme|PKi|3.7.0
LiveServer|rit|5.5.1
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Sorry I'm not sure what you mean by "indicator", can you explain some more?

**Comment by przemokon** [comment]
Well, by indicator i mean number which shows position of actual searched word i.e. 1 of 5.
It's next to regular expression option in Find.

**Comment by rebornix** [comment]
/duplicate

we don't support it at this moment.
