### ISSUE TITLE
Drag and drop into the integrated terminal with Git Bash as the shell produces strange output

### ISSUE THREAD

**Issue by tlm-2501** [microsoft/vscode#72478]
Issue Type: <b>Bug</b>

Trying to drag a file from the explorer pane into the integrated terminal with PowerShell produces the path to the file in the terminal. This is expected and normal behaviour. However, when I switched the terminal to use Git Bash instead of PoSH, drag and drop now produces the following bizarre output:
```
$ Windows\ Subsystem\ for\ Linux\ has\ no\ installed\ distributions.
bash: Windows Subsystem for Linux has no installed distributions.: command not found
$ Distributions\ can\ be\ installed\ by\ visiting\ the\ Microsoft\ Store:
bash: Distributions can be installed by visiting the Microsoft Store:: command not found
$ https://aka.ms/wslstore
bash: https://aka.ms/wslstore: No such file or directory
```
To clarify once again: this doesn't, and shouldn't, have anything to do with WSL. This is Git's distribution of Bash, packaged as part of Git for Windows.

Expected behaviour is that it would just paste the filepath normally. Ideally it would also use bash-compatible forward slashes instead of the Windows path separator.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
vscode-standardjs|che|1.2.3
gitlens|eam|9.6.1
php-debug|fel|1.13.0
mysql-syntax|jak|1.3.1

</details>

**Comment by Tyriar** [comment]
Verification:

- Set default shell to git bash
- Create terminal
- Drag a file into the terminal from the explorer

The should not cause the above weird error and also should not print a WSL-style `/mnt/c/...` path.
