### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by imnotashrimp** [Microsoft/vscode#72476]
Issue Type: <b>Bug</b>

1. Start Visual Studio Code.
2. Watch the error be thrown.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
markdown-yaml-preamble|bie|0.0.2
mermaid-markdown-syntax-highlighting|bpr|1.0.1
language-hugo-vscode|bud|0.11.0
better-toml|bun|0.3.2
githistory|don|0.4.6
vscode-html-css|ecm|0.2.0
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1
todo-tree|Gru|0.0.128
minify|Hoo|0.4.3
rest-client|hum|0.21.2
readabilitycheck|jem|1.3.0
vscode-github|Kni|0.30.2
vscode-regexp-preivew|le0|0.0.3
slugify-vscode|max|1.0.2
markdown-shortcuts|mdi|0.11.0
swagger-doc-viewer|mim|1.0.4
python|ms-|2019.3.6558
Go|ms-|0.9.2
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.11.3
language-liquid|nei|0.1.1
emoji|Per|0.0.3
webstorm-icons|pms|1.0.0
vscode-css-peek|pra|2.2.0
swaggitor|qns|0.1.1
vscode-yaml|red|0.4.0
LiveServer|rit|5.6.0
partial-diff|ryu|1.4.0
trailing-spaces|sha|0.3.1
ayu|tea|0.18.0
write-good-linter|tra|0.1.1
json2yaml|tux|0.2.0
highlight-matching-tag|vin|0.9.1
vscode-mermaid-preview|vst|0.11.2

</details>

**Comment by imnotashrimp** [comment]
Digging some more, I found the issue is with an extension, not VSC. Closing this issue.
https://github.com/ritwickdey/vscode-live-server/issues/285

**Comment by ritwickdey** [comment]
New version is published. Please try to install from store. It should work. If not, please let me know
