### ISSUE TITLE
Using find and replace feature but adds line breaks

### ISSUE THREAD

**Issue by gnanadeeptu** [Microsoft/vscode#72475]
I am using find and replace feature, to replace three lines and do not wanted to add a line breaks. Tried with regEx search and replace does not seems to work.
- VSCode Version: version 1.33
- OS Version:10.13.6 

Steps to Reproduce:
1.Click on Search option on the left side. Enter following string in the search
```
    <ns0:layoutAssignments>
        <ns0:layout>abc__c-abc Layout</ns0:layout>
    </ns0:layoutAssignments>
```
2. Enter blank on replace section. Click on replace all.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This works for me. Not really clear what the issue is, what happens when you click replace?

**Comment by yume-chan** [comment]
I doubt the problem is that, when I have

```plain
aaa
bbb
ccc
ddd
```

in an editor, then I put

```plain
bbb
ccc
```
in search, and nothing in replace, then hit Replace All, the result is

```plain
aaa

ddd
```

, leaving an empty line.

However I believe it works as intended, the search field is missing the last line break.

**Comment by gnanadeeptu** [comment]
Hi @yume-chan I was looking for following results (taking your own example)
Actual Result: 
aaa

ddd

Expected Result: 
aaa
ddd

**Comment by roblourens** [comment]
Then you can add an extra newline to the search query (shift+enter) so it will be replaced
