### ISSUE TITLE
一开始打开软件很卡，内存飙高

### ISSUE THREAD

**Issue by wing-king** [Microsoft/vscode#72477]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by KexyBiscuit** [comment]
Translation: The app is slow and consumes much RAM just after starting it.

(The issue description is "We have written the needed data into your clipboard because it was too large to send. Please paste.", seems like it was directly copied from the issue reporter.)

**Comment by octref** [comment]
Please provide performance logs, otherwise we can't debug.
