### ISSUE TITLE
Problem view should show source information

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#7247]
- VSCode Version: alpha
- OS Version: all

Markers carry a source attribute (e.g eslint, ts,js, ...). If present it should be rendered in the problems view.

**Comment by sandy081** [comment]
@dbaeumer See the attached screenshot. Wondering if this would be clear for the user to determine the source of error/warning.

![source-info](https://cloud.githubusercontent.com/assets/10746682/15829980/70562986-2c16-11e6-880d-10e94a041c5f.PNG)

**Comment by sandy081** [comment]
After thinking again, I think its not a good idea to put owner information as part of the entry as not everybody is interested in this info. Another idea is to put it as part of the filters so that interested users can filter markers based on who generate them

**Comment by dbaeumer** [comment]
@sandy081 sorry, I was not clear in my description. Corrected it. I was talking about the source attribute on a marker. And be aware that different markers on a file can have different source attibutes. So we can't make it part of the file name. Either we need a column or we integrate it into the message as we do in hovers (e.g [ts]. [js], ...)
