### ISSUE TITLE
VS CODE running super slow today

### ISSUE THREAD

**Issue by jrodbshaw** [Microsoft/vscode#72472]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jrodbshaw** [comment]
Issue Type: <b>Performance Issue</b>

Everything just takes ages to load, even removing extensions it still lags, not as bad but it does. 
My activity tracker has three sometimes four code Helper's at 97-99% CPU 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 11, 14|
|Memory (System)|8.00GB (0.27GB free)|
|Process Argv|/private/var/folders/gk/dqxc1_3n6hj5xpbbrtg1ssy80000gn/T/AppTranslocation/20322C96-05C5-4D9C-AAE0-3BD32E1C6777/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	   123	  6061	code main
    0	    49	  6063	   gpu-process
    0	   123	  6307	   shared-process
    0	   238	  6901	   window (RegisterForm.js — client)
    0	   115	  6905	     extensionHost
    0	    66	  6909	       electron_node eslintServer.js 
    0	   246	  6910	       electron_node tsserver.js 
    0	    57	  6938	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    57	  6912	       electron_node server.js 
    0	    49	  7609	       /private/var/folders/gk/dqxc1_3n6hj5xpbbrtg1ssy80000gn/T/AppTranslocation/20322C96-05C5-4D9C-AAE0-3BD32E1C6777/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /private/var/folders/gk/dqxc1_3n6hj5xpbbrtg1ssy80000gn/T/AppTranslocation/20322C96-05C5-4D9C-AAE0-3BD32E1C6777/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=6905
    0	    41	  6906	     watcherService
    0	    49	  6914	     searchService
    0	     0	  6944	     /bin/zsh -l
    0	    90	  7752	   window (Issue Reporter)
    0	     0	  7754	   (ps)
    0	     0	  7755	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (RegisterForm.js — client)
|    Folder (client): 20 files
|      File types: js(9) DS_Store(3) json(3) gitignore(1) md(1) lock(1) ico(1)
|                  html(1)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
jest-snippets|and|1.7.0
vscode-color|ans|0.4.5
snapshot-tools|asv|0.3.0
vscode-toggle-quotes|Bri|0.3.2
vscode-yarn-script|car|0.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.6.0
vscode-faker|dee|1.3.0
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.2.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|2.6.2
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-yarn|gam|1.6.0
vscode-pull-request-github|Git|0.1.7
react-jest-vscode-snippets|jal|0.0.3
vscode-styled-components|jpo|0.0.26
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|1.0.0
google-fonts|lio|0.0.1
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
cpptools|ms-|0.21.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
prettier-vscode-with-tabs|pas|1.1.0
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
LiveServer|rit|5.5.1
js-jsx-snippets|sky|0.3.0
code-spell-checker|str|1.6.10
ejs-snippets|Tao|0.1.0
ReactSnippetsStandard|Tim|1.1.0
vscode-react-native|vsm|0.9.1
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2


</details>

**Comment by octref** [comment]
Does this happen if you disable all extensions?

You an run "Process Explorer" command to see which extension is causing CPU spikes.

**Comment by justinobney** [comment]
![image](https://user-images.githubusercontent.com/1054188/56464081-4f24a280-63a7-11e9-8479-d3608543b553.png)

**Comment by mjbvz** [comment]
@jrodbshaw Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

Also, make sure you are on the latest VS Code version (1.33.1)

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate.

One possible cause is https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391, so make sure you do not have one of the broken versions of `@types/styled-components` installed under your `node_modules`
