### ISSUE TITLE
搜索功能跑到终端栏是怎么回事？

### ISSUE THREAD

**Issue by EricWong1992** [Microsoft/vscode#72470]
Issue Type: <b>Feature Request</b>

搜索功能跑到终端栏是怎么回事？

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by EricWong1992** [comment]
Why the 'Search' function stays with Terminal? It's very inconvenient!

**Comment by KexyBiscuit** [comment]
这是 `search.location` 设置控制的，建议检查是否意外修改了此设置。
This is controlled by `search.location`, please check if configured this accidentally.

**Comment by EricWong1992** [comment]
> 这是 `search.location` 设置控制的，建议检查是否意外修改了此设置。
> This is controlled by `search.location`, please check if configured this accidentally.

多谢，不知道什么时候Location那里变成panel了，改为sidebar就好了。
