### ISSUE TITLE
Using numeric name in settings properties does not format in Settings UI

### ISSUE THREAD

**Issue by chunkypixel** [microsoft/vscode#72483]
- VSCode Version: 1.33.1
- OS Version: Windows_NT x64 10.0.17763, Ubuntu 18.04.02, Gnome 3.28.2

**Steps to Reproduce:**
See attached pic. When using leading numeric values in the properties id the field is not properly formatted.
![settingsEditor-issuewithnumericnames](https://user-images.githubusercontent.com/20292815/56276147-59476680-6145-11e9-8c15-5f8dbbff91f4.png)

**From my package.json:**
"atari-dev-studio.compiler.7800basic.args": {
    "type": "string",
    "default": "",
    "description": "Specify (optional) command line arguments.",
    "scope": "resource"
}

**Comment by DavidMunozMartinez** [comment]
Hello! I would very much like to start participating in open source projects and what better than the text editor i use every day, i believe i could take on this issue

**Comment by roblourens** [comment]
@chunkypixel can you clarify what the expected format would be? This PR would fix it to show `Compiler > 7800basic` which is great but should we also always split `[0-9][a-z]` or capitalize a letter after a number, like `7800 Basic`?

**Comment by chunkypixel** [comment]
@roblourens 
Thanks for taking a look.  Having a look at what appears to be the standard??? a capitalisation would appear to break words. So:
7800basic = 7800basic but 7800Basic = 7800 Basic

FYI - doing some further testing around leading chars (may help with determination):
![vsc-settings1](https://user-images.githubusercontent.com/20292815/57819880-a878c980-77cd-11e9-8d2b-3102b5a7490c.png)
![vsc-settings2](https://user-images.githubusercontent.com/20292815/57819885-ac0c5080-77cd-11e9-9cc7-81d752d260df.png)

Hope that helps to clarify?

**Comment by DavidMunozMartinez** [comment]
So are we supposed to support the leading upper case character after the dot ?
and also support camel case for strings containing numbers? sounds very tricky, I'm still confused on what the correct behavior should be, but i guess we need to clarify the expected behavior

**Comment by roblourens** [comment]
I think that this would be a good start:

> 7800basic = 7800basic but 7800Basic = 7800 Basic

And regarding `.a` vs `.A`, in theory we should probably handle them the same, but I'm inclined not to change that unless somebody complains. I think .camelCase (`.a`) is the more typical format so I would optimize for that.

It's impossible to get every setting right just with heuristics. Some day there will be a way for an extension to just specify exactly how the setting should look in the UI...

**Comment by chunkypixel** [comment]
> Some day there will be a way for an extension to just specify exactly how the setting should look in the UI...

Would certainly be great to eventually be able to provide your own (optionally) eventually but it works pretty well for just about every situation otherwise.

**Comment by DavidMunozMartinez** [comment]
I will make a PR to handle it like so:  
7800basic = 7800basic
7800Basic = 7800 Basic

I will ignore the `.A` case for now

**Comment by chunkypixel** [comment]
Thanks guys for the fix!
