### ISSUE TITLE
Block comment when  already one is included in the selection

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#72484]
I use modify/add block comment on a portion of code where I have already a block commented. It doesn't work..
![image](https://user-images.githubusercontent.com/624802/56276863-9b4fb880-6103-11e9-9058-e58cc7175c16.png)
Issue Type: <b>Bug</b>

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|5.98GB (2.51GB free)|
|Process Argv|--folder-uri file:///d%3A/electron/GestionSiteRestau|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.4.3
project-manager|ale|10.5.1
vscode-custom-css|be5|3.0.3
css-compressor|bes|0.0.2
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.13.0
vscode-mysql|for|0.4.0
beautify|Hoo|1.4.11
ftp-simple|hum|0.7.0
typings-autoinstaller|jvi|1.2.0
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.33.2
debugger-for-chrome|msj|4.11.3
live-server-preview|neg|0.1.4
flowmaker|spe|1.2.0
html-css-class-completion|Zig|1.18.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Block comments cannot be nested in javascript. The fix would be to remove existing block comments when using block comment command, but that would be unexpected in many cases and is out of scope
