### ISSUE TITLE
Add an option for sync compounds execution

### ISSUE THREAD

**Issue by ihodev** [Microsoft/vscode#72486]
Add an option for sync compounds execution. Sometimes building requires a common component that both of configurations wants to compile.

```js
    {
      "name": "Default",
      // "async" is default now
      "run": "sync",
      "configurations": [
        "Data Api",
        "Gateway Api",
        "Workplace"
      ]
    },
```

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
