### ISSUE TITLE
I just copy foder name,bug it auto update import path in js

### ISSUE THREAD

**Issue by hongyin163** [microsoft/vscode#72487]
Issue Type: <b>Bug</b>

I just copy foder name,bug it auto update import path in js,so i close auto import to avoid that

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.71GB (3.29GB free)|
|Process Argv|--folder-uri file:///d%3A/Workfolder/ats|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.1
vsnotes|pat|0.7.0
LiveServer|rit|5.6.0
vscode-leetcode|she|0.13.3
stylelint|shi|0.48.0

</details>

**Comment by mjbvz** [comment]
Please add steps to reproduce this and a more detailed explanation of the problem

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing this as more information is needed to investigate this, such as steps to reproduce or a small sample project
