### ISSUE TITLE
Settings UI display order

### ISSUE THREAD

**Issue by chunkypixel** [microsoft/vscode#72485]
When building VS Code extensions, developers would benefit from being able to set a display order of settings within a section and/or sub items.

The current (apparent) order of alphabetical is generally OK but once you begin adding a larger number of settings they may be more coheriant and logical to be displayed in another order.

**Suggestions**
- Display in order of entry in package.json;
- or provide an index, priority (or similar);
- or provide a setting within the configuration to choose: ie Alphabetic, Entry order, other?

**Comment by roblourens** [comment]
I think this is covered by https://github.com/microsoft/vscode/issues/51778
