### ISSUE TITLE
QuickInput: Missing ThemeIcon support

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#72489]
Have an extension, use the following code:

```
const quickPick = vscode.window.createQuickPick<T>();
quickPick.title = 'My Title;
quickPick.placeholder = placeholder;
quickPick.items = items;

quickPick.buttons = [{
		iconPath: vscode.ThemeIcon.File,
		tooltip: 'Learn More'
}];

quickPick.show();
```

Notice the quick pick appears broken showing a custom button

fyi @chrmarti

**Comment by alexr00** [comment]
This was also broken in 1.33.1

**Comment by alexr00** [comment]
@chrmarti the quick pick doesn't actually support using a ThemeIcon: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostQuickOpen.ts#L446

**Comment by alexr00** [comment]
I fixed a misleading `!` and made it so the whole quick input doesn't get messed up if a ThemeIcon is provided. Actual support for using ThemeIcons as in the API would still need to be added.

**Comment by chrmarti** [comment]
@alexr00 That shouldn't affect the visibility of the 'custom' button. @isidorn Saw the custom button when using the API which shouldn't be possible.

Maybe the custom button was shown in the previous QuickPick and then not properly hidden when this one opened?

**Comment by alexr00** [comment]
It showed everything when I reproed and debuged it. I was not specific to the custom button, and reproed in stable.
![image](https://user-images.githubusercontent.com/38270282/56719125-63b6c100-6740-11e9-96fa-73352bd3be8a.png)

**Comment by jrieken** [comment]
fyi - this might help you: quickpick.buttons = [
			vscode.QuickInputButtons.Back,
			{ iconPath: vscode.ThemeIcon.File },
			{ iconPath: vscode.ThemeIcon.Folder },
			{ iconPath: new vscode.ThemeIcon('zap') }
		];
