### ISSUE TITLE
codeActionsOnSave shows file changes as unsaved

### ISSUE THREAD

**Issue by manospasj** [Microsoft/vscode#72496]
Issue Type: <b>Bug</b>

Since the update to VS Code 1.33 the editor.codeActionsOnSave setting does not work as expected. When saving a file the defined actions run but then the file is unsaved. Sometimes the file gets saved but not always. This worked fine in VS Code 1.32.

My VS Code settings are:

```json
{
  "workbench.startupEditor": "newUntitledFile",
  "editor.formatOnSave": true,
  "[handlebars]": {
    "editor.formatOnSave": false
  },
  "files.exclude": {
    "node_modules/": true
  },
  "git.autofetch": true,
  "git.enableSmartCommit": true,
  "prettier.tslintIntegration": true,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.fixAll": true
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

If I change the source.organizeImports and source.fixAll settings to false the issue everything works fine.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.73GB (5.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.15
gitlens|eam|9.6.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.8.1
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.11.3
vscode-yaml|red|0.4.0

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by manospasj** [comment]
I just tried the nightly insider build without any extensions and it does the same thing. I also played a bit with the settings and it seems that the only setting causing this is the source.organizeImports, as setting it to false fixes the issue.

**Comment by bpasero** [comment]
@manospasj can you give me an exact repro how you get there?

**Comment by bpasero** [comment]
@manospasj ping

**Comment by manospasj** [comment]
@bpasero I tried to create a repro but I can't reproduce it with a hello world app. It only seems to be happening with the project I'm working on. I'll do some more investigation and see if I can find something more helpful.

**Comment by manospasj** [comment]
@bpasero Sorry for my late response but I was not in the office for a couple of days. This is not a duplicate of #72343. I tried the latest insiders build as suggested in #72343 but this is not fixed.

I know I'm not giving you enough info to reproduce it,  but I'm not sure what's causing it and thus I can't create a repro to demonstrate it. I can only reproduce it in a work project which is not open source and I can't share. Maybe I can show you using TeamViewer?

**Comment by bpasero** [comment]
@manospasj this is with a typescript project right?

**Comment by manospasj** [comment]
Yes this is a react with typescript project. Here is my full package.json, if that helps. I have also noticed that it happens more often when I'm running the project.

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/google-map-react": "^0.23.10",
    "@types/history": "^4.7.2",
    "@types/jest": "23.3.9",
    "@types/lodash": "^4.14.119",
    "@types/node": "10.12.10",
    "@types/react": "16.7.7",
    "@types/react-dom": "16.0.10",
    "@types/react-router-dom": "^4.3.1",
    "@types/styled-components": "^4.1.1",
    "cross-env": "^5.2.0",
    "google-map-react": "^1.1.2",
    "history": "^4.9.0",
    "i18next": "^15.0.6",
    "lodash": "^4.17.11",
    "node-sass": "^4.10.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-grid-layout": "^0.16.6",
    "react-i18next": "^10.4.2",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.8",
    "react-testing-library": "^5.4.4",
    "rxjs": "^6.3.3",
    "styled-components": "^4.1.1",
    "tslint": "^5.11.0",
    "tslint-react": "^3.6.0",
    "typescript": "3.1.6",
    "yargs": "^12.0.5"
  },
  "scripts": {
    "start": "node scripts/environment --config development react-scripts start",
    "start:local": "node scripts/environment --config local react-scripts start",
    "build": "node scripts/environment --config development react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "tslint 'src/**/*.tsx' 'src/**/*.ts'",
    "gen": "plop --plopfile ./src/utils/generators/index.js && prettier --loglevel error --write \"./src/**/*.tsx\""
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@types/react-grid-layout": "^0.16.7",
    "inquirer-directory": "^2.1.0",
    "plop": "^2.1.0",
    "prettier": "^1.14.3"
  }
}
```

**Comment by mjbvz** [comment]
@manospasj When this happens, can you please run the `Developer: Toggle developer tools` command in VS Code to open the developer tools. In the developer tools console, do you see any messages about `codeActionOnSave` timeout or other errors?

**Comment by manospasj** [comment]
@mjbvz yes there is a warning `WARN Aborted codeActionsOnSave after 750ms` at workbench.main.js:1401

**Comment by mjbvz** [comment]
Are other language features, such as intellisense, responsive in this workspace or are they slow/sluggish? 

Can you also please make sure you have the latest version of `@types/styled-components` installed. See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391 for details

**Comment by manospasj** [comment]
Upgrading to the latest version of `@types/styled-components` did the trick. Thanks @mjbvz
