### ISSUE TITLE
feat(global symbols): make config to disable export global symbols

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/vscode#72497]
I saw [this comment][1] from @mjbvz that it's normal behavior when I create any `*.ts` or `*.js` file without `export` symbols and I can see all declared symbols in global namespace.

I would like to have a config to avoid such behavior.

[1]: https://github.com/Microsoft/vscode/issues/39598#issuecomment-349382351

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/14279

Please upvote if you are interested in this
