### ISSUE TITLE
Rename variable after rename file

### ISSUE THREAD

**Issue by Hongarc** [microsoft/vscode#72505]
About:
- Version: 1.33.1 (user setup)
- Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
- Date: 2019-04-11T08:27:14.102Z
- Electron: 3.1.6
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. I change the name of my file: `Browser.ts` to `browser.ts` (Use F2 key to change)
2. I tried to change the name of one variable in `browser.ts` but VS code open new tab named: `Browser.ts` and change the name of my variable in `Browser.ts`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Same root cause as #55655
