### ISSUE TITLE
`command 'emmet.expandAbbreviation' not found

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#72507]
I am having issues with auto completion as well. It first noticed it sometime last week.

Expected: Pressing tab either tabs 4 spaces or auto completes inputed text.

Results: Tab key does not function at all. No spaces added. No auto complete. Instead I receive error:  
`command 'emmet.expandAbbreviation' not found`

One note, if I set `emmet.expandAbbreviation: false`,  my tab key works again (adding spaces). I don't receive any errors but obviously there is no auto complete functionality in that case.

Also I am not seeing performance issues experienced in #71751.

These are my emmet settings:

{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Atom One Dark",
    "files.associations": {
        "*.js": "javascript",
    },
    "emmet.showSuggestionsAsSnippets": true,
    "eslint.autoFixOnSave": true,
    "eslint.alwaysShowStatus": true,
    "eslint.run": "onSave",
    "diffEditor.ignoreTrimWhitespace": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.enablePreview": false,
    "gitlens.hovers.enabled": false,
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "emmet.triggerExpansionOnTab": true,
    "emmet.expandAbbreviation": true,
    "breadcrumbs.enabled": true,
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 100,
    "edge.format.enable": true,
}

_Originally posted by @osogrizz in https://github.com/Microsoft/vscode/issues/71805#issuecomment-483784117_

**Comment by mjbvz** [comment]
@osogrizz Please share your vscode version and installed extensions.

/needsMoreInfo

**Comment by osogrizz** [comment]
The issue apparently was fixed with the last update. 

`"emmet.expandAbbreviation":`   seems to have been deprecated. 

Flagging `"emmet.triggerExpansionOnTab":`  back to true functions now. My tab key functions normally as well at all times.

**Comment by lacivert** [comment]
I am having this issue as well. I am using 1.33.1 (up to date), it does not put a normal tab (two spaces indentation) on a .js file, just nothing happens on the code and this error shows at right bottom:

`command 'emmet.expandAbbreviation' not found`

setting.json is;

```
{
    "git.autofetch": true,
    "emmet.triggerExpansionOnTab": true,
    "files.autoSave": "afterDelay",
    "workbench.colorTheme": "Visual Studio Light",
    "colorInfo.languages": [
        {
            "selector": "css",
            "colors": "css"
        },
        {
            "selector": "sass",
            "colors": "css"
        },
        {
            "selector": "scss",
            "colors": "css"
        },
        {
            "selector": "less",
            "colors": "css"
        },
        {
            "selector": "javascript",
            "colors": "css"
        }
    ],
    "files.autoSaveDelay": 5000,
    "java.home": "/path/to/openjdk64-11.0.1",
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}
```
![image](https://user-images.githubusercontent.com/945612/57383994-71485e00-71b8-11e9-85e5-c9ea23b46da4.png)

**Comment by plaporte** [comment]
Same issue happening to me.

**Comment by ramya-rao-a** [comment]
@lacivert and @plaporte Can you share the keyboard settings that you may have customized?
