### ISSUE TITLE
Terminal does not auto scroll after clearing output

### ISSUE THREAD

**Issue by fdk17** [microsoft/vscode#72503]
Issue Type: <b>Bug</b>

Create a build task where "presentation" "clear" is set to "true" . 

Normally this works fine and the terminal is cleared and the terminal auto scrolls with the build output.

But when scrolling to the top of the output and then rerunning the task the output does not scroll.  Only the few first lines of output is shown, you need to manually scroll to the bottom.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.4.0-144-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.68GB (1.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
Bookmarks|ale|10.4.3
beautify|Hoo|1.4.11
shortcut-menu-bar|jer|0.1.5
cpptools|ms-|0.22.1
code-settings-sync|Sha|3.2.8
code-eol|soh|0.3.3
code-spell-checker|str|1.6.10
linkerscript|Zix|1.0.0

</details>

**Comment by Tyriar** [comment]
@alexr00 this is by design on the terminal side.

**Comment by alexr00** [comment]
To verify, open the hello world sample and add this task:
```
        {
            "type": "npm",
            "script": "compile",
            "group": "build",
            "problemMatcher": [],
            "presentation": {
                "clear": true
            }
        }
```
Create a lot of errors in the extension code.
Run the task.
Scroll to the top of the task terminal when the task is done.
Run the same task again, and verify that the terminal scrolls with the task output.
