### ISSUE TITLE
Shrink/Expand destructuring list

### ISSUE THREAD

**Issue by ahmetcetin** [Microsoft/vscode#72502]
I believe I'm not alone, I write quite frequently code like follows:

```
    const {
      loading,
      groups,
      types,
      selectedType,
      selectedFolder,
      currentPage,
      pageSize,
      selected,
      approved,
      rejected,
      premium,
      filter,
    } = this.state;
```

To save space, I want to shrink that code, but it's not possible it looks atm.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/30996 to track upstream
