### ISSUE TITLE
Debugger - Typescript - "this" scoped variables always display as undefined in debugger

### ISSUE THREAD

**Issue by grizzlysol** [microsoft/vscode#72510]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by grizzlysol** [comment]
Issue Type: <b>Bug</b>

When debugging typescript files in an angular project, variables being accessed with "this" scope always display as 'undefined' even when they are not. 
Data is actually assigned and passed using these variables but the data is invisable to the developer.
Using the debugger in chrome reveals that the variables are working correctly. This indicates that the issues are in the VSCode debugger.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.1
csharp|ms-|1.17.1
powershell|ms-|1.12.1
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3


</details>

**Comment by roblourens** [comment]
Sorry for the slow response. Do you have a reproducible code example?
