### ISSUE TITLE
VSC-I icon not showing up in Dock

### ISSUE THREAD

**Issue by jpinnix** [Microsoft/vscode#72513]
Issue Type: <b>Bug</b>

It just appears as a dot.

<img width="419" alt="Screen Shot 2019-04-17 at 2 13 27 PM" src="https://user-images.githubusercontent.com/4436/56315223-cb578580-611c-11e9-80ad-6e8ba8484a3d.png">

VS Code version: Code - Insiders 1.34.0-insider (6d5feae57959287fb116467f4eb6c7079571b466, 2019-04-17T09:19:05.456Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|22, 10, 6|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-elixir|mjm|1.1.0
cpptools|ms-|0.22.1
erlang|pgo|0.5.2
sass-indented|rob|1.5.1
stylelint|shi|0.48.0
fish-vscode|sky|0.2.1

(2 theme extensions excluded)

</details>

**Comment by krupenja** [comment]
Looks similar to https://github.com/Microsoft/vscode/issues/63068
