### ISSUE TITLE
Shift+tab removes spaces from the start of the line

### ISSUE THREAD

**Issue by MolusMS** [Microsoft/vscode#72515]
Issue Type: <b>Bug</b>

1.- Open a c++ work space.
2.- Open a file that is indented using spaces.
3.- Go to a line of text that is indented and has a comment in line:
    int a;      // A variable
4.- Place cursor before the first /
5.- Press Shift+tab

Expected behavior:
    int a;// A variable

Actual behavior:
int a;      // A variable

VS Code version: Code - Insiders 1.34.0-insider (8b5ebbb1b8f6b2127bbbd551ac10cc080482d5b4, 2019-04-16T05:23:07.866Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.79GB (12.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|2.0.190410007
cpptools|ms-|0.22.2-insiders

</details>

**Comment by yume-chan** [comment]
I think the "outdent" command (bind to <kbd>Shift</kbd> + <kbd>Tab</kbd> by default) is designed to remove indent for the whole line.

Can you list some other editors that do what you said?

**Comment by MolusMS** [comment]
Microsoft Visual Studio Enterprise 2017
