### ISSUE TITLE
bash shell syntax highlighting fail on `here-document`

### ISSUE THREAD

**Issue by GloobyBoolga** [Microsoft/vscode#72512]
Issue Type: <b>Bug</b>

```
cat <<"some delim" > some_file
some
file
content
some delim
false 
```

The highlighting fails on the space between the 1st `some` and `delim`.
`delim` is not seen as part of the _word_. 
`man bash` says:

>  If any characters in word are quoted, the delimiter is the result of quote removal on word,[...]

Workaround: Remove the space in the `word`.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|9.6.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.2-insiders
vscode-docker|Pet|0.6.1
code-spell-checker|str|1.6.10
vscode-capnp|xmo|1.0.0

</details>

**Comment by alexr00** [comment]
Opened in the owning repo.
