### ISSUE TITLE
VS Code crashes when trying to open Terminal

### ISSUE THREAD

**Issue by x1unix** [Microsoft/vscode#72511]
Issue Type: <b>Bug</b>

VS Code crashes when I'm trying to open the terminal

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.18875

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (7.38GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-database|baj|2.1.5
vscode-icontheme-nomo-dark|be5|1.3.6
better-toml|bun|0.3.2
cmake-format|che|0.4.2
vscode-wasm|dts|1.2.1
tslint|eg2|1.0.43
dotnet|for|0.0.4
vscode-mysql|for|0.4.0
vscode-todo-renewed|Hac|0.8.5
beautify|Hoo|1.4.11
docthis|joe|0.7.1
vscode-icon-theme|jtl|1.6.5
intellij-idea-keybindings|k--|0.2.31
vscode-rust|kal|0.4.2
svgpreview|kis|0.2.0
vscode-mesh-viewer|mic|0.0.10
vscode-language-pack-ru|MS-|1.33.2
cpptools|ms-|0.22.1
Go|ms-|0.9.2
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
sass-indented|rob|1.5.1
rust|rus|0.6.1
RustyCode|sav|0.19.1
code-settings-sync|Sha|3.2.8
shader|sle|1.1.4
webassembly|trf|0.2.0
cmake|twx|0.0.17
wast|uky|0.2.6
vscode-arduino|vsc|0.2.25
vscode-icons|vsc|8.5.0
vscode-todo-highlight|way|1.0.4

(4 theme extensions excluded)

</details>

**Comment by baltuonis** [comment]
Happens after the latest update. Linux Mint 18.3

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/72190

You should upgrade to the 64-bit VS Code client.
