### ISSUE TITLE
JSON: no warning shown when typing setting with invalid casing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7252]
A user was setting `files.autosave` instead of `files.autoSave` but there was no warning generated for doing so.

**Comment by aeschli** [comment]
If we wanted a warning we would have forbid any setting that is not any of the schemas.
This is done by setting 'additionalProperties' to false.
But this likely will hurt users that have settings of extensions that the currently haven't installed or internal/hidden settings for which we don't define a schema.

**Comment by bpasero** [comment]
I thought we would show warnings when using settings that are not defined anywhere.

**Comment by aeschli** [comment]
Closing. I looked into it but it turns out to be a bigger change. Also it would cause a lot of ripples.
