### ISSUE TITLE
[Portable-Win7] VSCode doesn't remember last session if opened via pinned link on taskbar

### ISSUE THREAD

**Issue by mk-in** [Microsoft/vscode#72526]
Setup
```
Windows 7x64
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
```
Mode
```
Mode : Fully portable
Settings - /data/user-data
Extensions - /data/extensions

Other : Issue always occurs on a particular path ( P:/dev/Vscode)
```

Steps to Reproduce:

1. Open Vscode via code.exe in installed folder
2. Open folder + Files
3. Close[X] or Exit
4. Reopen via code.exe ---> No Issue
5. Close[X] or Exit
6. Pin Code.exe to taskbar
7. Reopen via pinned link. ---> Last session not open
8. Close[X] or Exit
9. Last session cannot be restored .. either via code.exe or pinned shortcut  start

Does this issue occur when all extensions are disabled?: Yes

To test, I cloned VSCode to VScode_clone in same drive ... The issue could not be reproduced in new folder

Comparison of both folders/files

--- Verbose start
![image](https://user-images.githubusercontent.com/7939779/56335828-b7169580-61bb-11e9-9e50-8927a3f5324a.png)
![image](https://user-images.githubusercontent.com/7939779/56335841-c72e7500-61bb-11e9-89b8-0d970ffbcfa4.png)

--- User-data backup/workspace.json 
--- While the VSCODE_CLONE has a populated folderURIWorkspace, the regular place has this as empty
![image](https://user-images.githubusercontent.com/7939779/56335870-d9101800-61bb-11e9-94f8-4c2875430866.png)

--- User-data/storage.json 
--- Has folder key-value missing after starting via pinned shortcut
![image](https://user-images.githubusercontent.com/7939779/56335953-22606780-61bc-11e9-9dd0-5ffb8710ae6f.png)

**Comment by mk-in** [comment]
Issue replicated on VSCode insider build. 
Steps
- Extract insider build into p:\dev\vscode
- Renamed code-insider (.exe and manifest ) to code (.exe and manifest)
- Open code.exe 
- Open a folder and file
- Close[X] or exit
- Reopen code.exe
- Opens last session
- Close[X} or Exit
- Pin to taskbar
- Open pinned shortcut
- Does not open last session

If I do not rename (.exe and manifest) code-insider to code, the above situation cannot be replicated

Somehow pinning the application at windows taskbar is having a conflict with a particular path. Any idea what does Vscode looks for when started from pinned shortcut ?

**Comment by c3er** [comment]
I don't know whether I encountered exactly the same issue but the behavior matches this issue description. The issue seems to be introduced with version 1.33.0. I downgraded now to 1.32.3 and this version is able to restore the last session with all open files when a start Code via the pinned taskbar entry.

My setup of the last working version:

```
Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600
```

**Comment by mk-in** [comment]
Seems my lucky day as I found the cause of the issue. It seems pinning of vscode actually used command line switch '-n'.  This was forcing creation of a new session.

I right clicked on pinned shortcut , then again right clicked on vscode icon .. and there I found the executable path with '-n' switch. Fixed it and it worked ok.

Keeping this open for a while, if someone has some inputs.
