### ISSUE TITLE
Terminal canvas renderer can be slow sometimes

### ISSUE THREAD

**Issue by dzg** [microsoft/vscode#72538]
Issue Type: <b>Performance Issue</b>

Since a few days ago VS Code is EXTREMELY sluggish, to the point of not being useable.
I tried disabling ALL extensions (except builtin) but did not help.
I also deleted all support files/folders in ~/Library. Did not help.

This is even with just 1 single editor open.

Help!!!
**UPDATE** After some testing, it seems to happen when I open a terminal panel in VS Code. If I close the terminal panel, it returns to normal speed.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (14.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    98	  2545	code main
    0	    66	  2546	   gpu-process
    0	   492	  2547	   window (fox-server2.js — portal (Workspace))
    0	     0	  2573	     /bin/bash -l
    0	    98	  2601	     extensionHost
    0	   131	  2608	       electron_node tsserver.js 
    0	    66	  2621	         electron_node typingsInstaller.js typesMap.js 
    0	    66	  2665	       /Users/dang/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/dang/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=2601
    0	    33	  2602	     watcherService
    0	    33	  2692	     /Users/dang/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/dang/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork ms-vscode.node2 {"common.vscodemachineid":"18c4dcf0f0ffbc117ed7b3bcba62025922b56fc996bd3556cbaacb019f69358e","common.vscodesessionid":"7689dc4a-a274-4861-b55f-447b3bedd3e21555577571247"} AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    66	  2618	   shared-process
    0	    98	  2802	   window (Issue Reporter)
    0	     0	  2806	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (fox-server2.js — portal (Workspace))
|    Folder (portal): 3033 files
|      File types: js(2382) html(401) css(94) png(52) json(51) DS_Store(24)
|                  jsx(9) vue(6) txt(4) gitignore(2)
|      Conf files: package.json(3) launch.json(1);
```

</details>
Extensions: none

**Comment by Antisunny** [comment]
Have you compare the loading speed of native Terminal.app and VScode Terminal panel?

**Comment by dzg** [comment]
> Have you compare the loading speed of native Terminal.app and VScode Terminal panel?

Yes, normal Terminal is "normal" speed. If I close the terminal panel, VSC returns to normal speed.

Note that it's not just the terminal panel in VSC that is slow ... it's the entire app, including any editor panels.

I noticed same behavior on 3 separate machines.

**Comment by koenpunt** [comment]
I see extreme slowness without having a terminal panel open. For now I downgraded to 1.32.3, and disabled auto update to make VSCode usable again.

**Comment by Tyriar** [comment]
@dzg does this setting fix the problem?

```
"terminal.integrated.rendererType": "dom"
```

See https://github.com/Microsoft/vscode/wiki/Performance-Issues for diagnosing performance issues.

**Comment by dzg** [comment]
> @dzg does this setting fix the problem?
> 
> ```
> "terminal.integrated.rendererType": "dom"
> ```

Yes, seems that it does! Thanks!

**Comment by Tyriar** [comment]
You're probably hitting one of the issues that the canvas renderer just can't handle very well, such as:

- GPU doesn't like rendering Chromium's canvas
- Chromium disables GPU acceleration
- The terminal renders lots of colors, particularly in background
- The terminal renders lots of non-ascii characters

The workaround for this is to use the DOM renderer, which typically will degrade performance in some focuses cases, but it should have better overall performance:

```
"terminal.integrated.rendererType": "dom"
```

The end fix here is to bring xterm.js' WebGL renderer into VS Code https://github.com/xtermjs/xterm.js/issues/2033

**Comment by clankill3r** [comment]
If when I set it to `dom` it is still unbearable slow. (this is with colors etc.).
I estimate around 10fps.

This is what scrolling in 1987 looked like:
https://www.youtube.com/watch?v=L41oIvre9K0

**Comment by Tyriar** [comment]
@clankill3r the DOM being too slow for a huge highly dynamic buffer is exactly why I pursued the canvas implementation, but there are issues with a 2d rendering context that we simply cannot overcome without going lower level which is why I put together the WebGL renderer.

Since your hardware seems to have issues with both, you can try it out if you want and let me know if it solves the perf issue. To try it out clone the xterm.js repo, launch the demo and hit the Enable WebGL Renderer button down the bottom: https://github.com/xtermjs/xterm.js/wiki/Contributing#linux-or-macos

**Comment by Tyriar** [comment]
This isn't actionable outside of electron updates improving GPU support, new hardware or https://github.com/xtermjs/xterm.js/issues/2033
