### ISSUE TITLE
Since updating to 1809, terminal doesn't show my first prompt

### ISSUE THREAD

**Issue by biltongza** [Microsoft/vscode#72537]
Issue Type: <b>Bug</b>

As title says. I updated to Windows 10 1809 yesterday and since then, when I open a terminal it doesn't show my first prompt, so it looks like it isn't ready and is completely blank. I can scroll up to see the usual Windows version and if I press enter it looks like a lot of space is left blank by the terminal.

![terminal issue](https://user-images.githubusercontent.com/2845704/56348811-8b011180-61c7-11e9-8814-a0077243ded9.gif)

Yesterday before 1809 my terminal worked just fine and showed me my first prompt as expected.

I first experienced this issue on my PC at home which updated to 1809 a while ago, but I didn't know 1809 was the cause, I just noticed now since my work laptop updated to 1809 that it is experiencing the same issue since the update.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (7.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1.11
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
node-modules-navigation|geg|0.0.2
angular-cli-task-provider|Gen|1.3.2
angular2-switcher|inf|0.2.0
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
Angular-BeastCode|Mik|8.0.1
vscode-scss|mrm|0.6.2
azure-account|ms-|0.8.2
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.67
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
stylelint|shi|0.48.0
vscode-icons|vsc|8.5.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.18.0

</details>

**Comment by reduckted** [comment]
I'm experiencing exactly the same thing. It started happening recently, but I don't remember exactly when, so it either started after installing Windows 10 1809, or after installing VS Code 1.33.

Starting VS Code in safe-mode made no difference.

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Extension|Version
---------|--------
aeschli.vscode-css-formatter|1.0.1
Angular.ng-template|0.1.11
asvetliakov.snapshot-tools|0.3.0
dbaeumer.vscode-eslint|1.8.2
dbalage.vscode-stylesheet-formatter|0.2.0
EditorConfig.EditorConfig|0.13.0
esbenp.prettier-vscode|1.8.1
jock.svg|0.1.4
kisstkondoros.svgpreview|0.2.0
ktriek.ng-bootstrap-snippets|1.0.0
Mikael.Angular-BeastCode|8.0.1
ms-vscode.powershell|1.12.1
ms-vscode.vscode-typescript-tslint-plugin|1.0.0
msjsdiag.debugger-for-chrome|4.11.3
ow.vscode-subword-navigation|1.2.0
QassimFarid.ejs-language-support|0.0.1
qinjia.seti-icons|0.1.3
reduckted.vscode-gitweblinks|1.3.0
shinnn.stylelint|0.48.0
tintoy.msbuild-project-tools|0.2.54
xaver.clang-format|1.9.0

![image](https://user-images.githubusercontent.com/10321525/56350715-c410a480-620e-11e9-8f5a-9e855c7ee850.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
