### ISSUE TITLE
Git Diff is not exist

### ISSUE THREAD

**Issue by hcakkuzu** [Microsoft/vscode#72534]
Issue Type: <b>Bug</b>

The diff tab(left one) is not exist, its gone after update.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2285)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.49GB (1.49GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
vue-peek|dar|1.0.2
todo-tree|Gru|0.0.129
vue-snippets|hol|0.1.11
vue-beautify2|ker|0.0.3
vetur|oct|0.18.1
sass-indented|rob|1.5.1
bootstrap4-vscode|the|6.1.0

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
Please provide screenshot and include repro steps
