### ISSUE TITLE
vscode auto imports behave weirdly after automatic package update

### ISSUE THREAD

**Issue by Dar0n** [Microsoft/vscode#72539]
Hello there!

I am relatively new to Linux. Couple of days ago I have run some automatic update of all the packages with apt-get.

After that VSCode behaves somewhat weird. In particular, it suddenly forgot all installed extensions (had to install them again). But the most bothering  issue is with auto import(ctrl + .): instead of themed colorful suggestion list with automatic selection of the most probable option, I get a "default" white list with no selection, that occasionally disappears while I navigate through it.

I tried to install older version of VSCode from couple of months ago, but that didn't change anything.
I also tried to delete ~/.vscode folder, but that also didn't do anything.
I failed to find similar issue and not sure where even to start to dig.

Environment:
Kubuntu 18.04, VSCode 1.29.1, Typescript 3.1.4

![myimage](https://user-images.githubusercontent.com/5588039/56349253-73765880-61c8-11e9-96e2-d59e4cd81435.gif)

**Comment by Dar0n** [comment]
Interestingly, auto-suggestions while typing work fine. Just the forced import (ctrl + .) looks atypical.

![myimage](https://user-images.githubusercontent.com/5588039/56359929-39668000-61e3-11e9-8eea-277556591bfb.gif)

**Comment by jrieken** [comment]
Code action use the default operating system context menu (not a custom menu). However, on Linux you can configure to use custom rendered menus if you want.

**Comment by Dar0n** [comment]
Hi @jrieken ! Thanks for finding time to answer my question.
Could you be more specific how I could configure custom rendered menus? Before the mentioned accidental update, the nice custom VSCode menu would appear every time I pressed "ctrl + ." . And I definitely did not configure anything before that, it came out of the box.

**Comment by jrieken** [comment]
Sorry, didn't find the name of setting, @sbatten will be able to help

**Comment by sbatten** [comment]
@Dar0n sorry for not getting this here sooner. The setting for modifying the titlebar and menus is `window.titleBarStyle`.

**Comment by Dar0n** [comment]
@sbatten Oh my God, you made my day! The native menu was so ridiculously annoying! Last week was a nightmare! :)
Thank you so much!
