### ISSUE TITLE
VSCode graphical glitching

### ISSUE THREAD

**Issue by henrycates** [Microsoft/vscode#72548]
Issue Type: <b>Bug</b>

1. Have vscode running with project/code
2. Put computer to sleep
3. Wake up computer
4. Unlock
5. VSCode now looks like crap

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic snap

Similar issue: [(CLOSED) Graphical glitch, garbled interface #29637](https://github.com/Microsoft/vscode/issues/29637)

I used these guidelines [Contributing to VS Code](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) and searched before posting.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.68GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Any file open will cause this, but here is the code in the image (incomplete prj):
`#include <stdio.h>
#include <stdlib.h>
#include <syscall.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <fcntl.h>
#include <dirent.h>
#include <time.h>
#include <grp.h>
#include <pwd.h>
#include <math.h>
#define MAX_SIZE 1000

int main(int argc, char **argv)
{
    int i, n;
    long int new_pos;
    char c[MAX_SIZE];

    FILE *fd;
    // int fd = open(argv[2], O_RDONLY);
    fd = fopen(argv[2], "r");
    n = abs(atoi(argv[1]));

}`
![image](https://user-images.githubusercontent.com/47864782/56360304-3f903880-61b2-11e9-849d-146f4b252cf6.png)

Picture without any extensions:
![image](https://user-images.githubusercontent.com/47864782/56361700-08238b00-61b6-11e9-9b8f-fdd310f583a1.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by henrycates** [comment]
I will add more info after finals next week.

**Comment by bpasero** [comment]
OK
