### ISSUE TITLE
Plz add auto-wraps

### ISSUE THREAD

**Issue by AyumuzawaYui** [Microsoft/vscode#72542]
Issue Type: <b>Feature Request</b>

I means, not Alt + Z to switch. Instead of add a permanent button into setting to give those people who don’t want to switch every time when VSC is open.

Appreciate.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
Did you try the editor.wordWrap setting?

**Comment by AyumuzawaYui** [comment]
> Did you try the editor.wordWrap setting?

Ah.. I feel that I am a blind man now.

Very thankful! XD
