### ISSUE TITLE
Paste should use ITextFileService instead of IFileService

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#72543]
From Ben:
can you try to come up with a test case that reproduces this issue? I have many tests for move() already here. Should be easy enough to add one with Promise.join().

Yes, you should use ITextFileService.move() because that is the only one that takes care of dirty models (e.g. it ensures to preserve dirty state and contents).

**Comment by bpasero** [comment]
@isidorn pushed a change to use `ITextFileService#move()`. However you might still want to revisit the usage of [`sequence`](https://github.com/Microsoft/vscode/blob/5c3b542/src/vs/workbench/contrib/files/browser/fileActions.ts#L1069) which would explain why the paste is slow for many files.

**Comment by isidorn** [comment]
@bpasero this works fantastic now. Changed it do it in parallel.
Adding bug so we verify this in endgame.

Verifier: paste 20+ files in the explorer and make sure they all get paster properly
