### ISSUE TITLE
Tab close button gets hidden when resizing

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#72541]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. open a markdown file
2. resize vscode so that the tab's name is small enough

What happens?
==
The close button disappears behind the preview icon.

What should happen?
==
The close button should be visible.

Video: https://youtu.be/r1J-R7nbDXs

This seems to be related to this issue #49954 which has been closed without any fix.

Note that here it's an edge case, but can happen even with large vscode window size if the tab's title is large enough.

**Comment by bpasero** [comment]
You can fix this by configuring: `"workbench.editor.tabSizing": "shrink"`
