### ISSUE TITLE
Search In Files returns partial lines when there is a slash

### ISSUE THREAD

**Issue by mat-m** [Microsoft/vscode#72549]
- VSCode Version: 1.33.1 (system setup)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Open a file containing the following block 
    xcopy /Y /F /I /E %_PROFILES% %_PROFILES%_PREMIG
2. Trigger Search Panel and search `PREMIG` without option
3. The result line starts after the last slash
![image](https://user-images.githubusercontent.com/1039753/56362794-f9a39680-61ea-11e9-9ca2-73c13f376f0f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is by design because we are looking for a good place to crop the result and we don't consider `/` to be a word character. But we want to show more info where there is room, you can see more info here: https://github.com/Microsoft/vscode/issues/59310
