### ISSUE TITLE
VSCode crashes when opening any minified Javascript file

### ISSUE THREAD

**Issue by buzinas** [Microsoft/vscode#7254]
I have a powerful machine with the configurations below:
Intel Core i7-4770K 3.5GHz 8MB L3 cache
16 GB RAM 2133Mhz
SSD 256 GB
MS Win 10 64-bit

If I try to open any minified Javascript file (34kb, for example), VSCode stops responding, and after ~20s it shows a dialog with the options: "Reopen", "Keep waiting" or "Close".

If I click "Keep waiting", sometimes after 40s or more it finally displays, but usually it doesn't.
If I click "Reopen", it never reopens and after more time, it shows the dialog again.
If I click "Close", VSCode is closed and I need to reopen it manually (as expected).

- VSCode Version: Last version (1.1.1)
- OS Version: Microsoft Windows 10 Home Single Language

Steps to Reproduce:

1. Download the attached [minified file](https://github.com/Microsoft/vscode/files/300771/min.txt).
2. Rename it to `min.js`
3. Open VSCode
4. Open `min.js`

**Comment by bondz** [comment]
Can't repro.
Followed your steps.
Running Win 10 Pro 1511 though.

**Comment by buzinas** [comment]
Btw, didn't inform, and not sure if it can be the cause of this, but I'm using the Dark-Dracula theme.

**Comment by bondz** [comment]
Yup, same one I'm running.

**Comment by buzinas** [comment]
Created an animated GIF showing what happens:

![Crash reprodution](https://cloud.githubusercontent.com/assets/7298695/15829481/6252aee4-2bea-11e6-8b1b-a95a39ff172e.gif)

**Comment by bondz** [comment]
Might be an installed extension, try updating your extensions.

**Comment by buzinas** [comment]
Updated to v1.2.0 and the problem is gone.
