### ISSUE TITLE
PHP syntax highlighting when using shorthand php tags inside html tags

### ISSUE THREAD

**Issue by jenstornell** [microsoft/vscode#72547]
- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:

```php
<li<?= ' class="hello"'; ?>></li>
```

It get all red like I'm breaking something, but it's perfectly valid code.

![image](https://user-images.githubusercontent.com/927011/56361448-a845d800-61e7-11e9-9465-06cf2c2f1da2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
@alexr00 not sure whether you own all of these or whether I own the PHP grammar still?

---

Our html grammar is different from atom's and it requires a space or `>` after the tag name: https://github.com/Microsoft/vscode/blob/master/extensions/html/syntaxes/html.tmLanguage.json#L2127

But I don't know how to fix this to keep the same highlighting for unrecognized tag names.

**Comment by alexr00** [comment]
@roblourens I just own grammar caretaking scripts and the first triage of issues. PHP grammar is all yours :)

**Comment by roblourens** [comment]
Fun! I will keep this open but I don't know how to fix it without infecting the upstream html grammer with php knowledge. Maybe it's ok to accept a `\s|(?=\b)` after the tag name instead of just `\s`.

**Comment by roblourens** [comment]
Since the upstream project has been archived, merging this into the general issue for a new SSH grammar. https://github.com/microsoft/vscode/issues/162707
