### ISSUE TITLE
Improve Default Light+Theme contrast

### ISSUE THREAD

**Issue by ericoloewe** [microsoft/vscode#72550]
Today is very difficult to stay more than 1 hour with the Default Light Theme because there is no "basic" contrast on it.

Contrast is important to stay more time front a screen. And the light theme is important to does not force our eyes 😄.

For more info, you can read this article: [Dark or Light UI? The UX Influence.](https://uxdesign.cc/dark-or-light-ui-the-ux-influence-ca6df6aff390)

![image](https://user-images.githubusercontent.com/8793862/56362316-e9c28d00-61bf-11e9-802a-fb0381674a66.png)

![image](https://user-images.githubusercontent.com/8793862/56362321-ec24e700-61bf-11e9-84ef-485a436c7a81.png)

- VSCode Version: 1.33.1
- OS Version: Window_NT x64 10.0.18362

Steps to Reproduce:

1. Open VSCode
2. File > Preferences > Color Theme
3. Choose `Light + (default light)

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
Thanks for the feedback. While our default themes may not meet your expectations for contrast, there are several other themes available in the marketplace that you can choose from as well. With that being said, I'll be closing this issue as `as-deigned`.
