### ISSUE TITLE
Markdown ignores User settings for wordWrap

### ISSUE THREAD

**Issue by amithm7** [Microsoft/vscode#72559]
- VSCode Version: 1.33.1
- OS Version: Linux x64 4.9.0-8-amd64

Steps to Reproduce:

1. Enable wordWrap, i did so like this:
```
"editor.wordWrapColumn": 120,
"editor.wordWrap": "bounded",
```
2. Open a markdown file with long enough lines to observe word-wrapping

From #45653, i have understood that, markdown has it's own wordWrap settings; even if i turn off word-wrapping, i see that there is word-wrapping in a markdown file. So, it basically ignores  general User settings
Currently i am only able to disable the default behavior by redefining the wordWrap setting again specifically for markdown files as so:
```
"[markdown]": {
    "editor.wordWrap": "bounded",
}
```
But this shouldn't be necessary, can't understand why there are hidden rules just for markdown. This behavior is counter-intuitive and uncalled-for in my opinion.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
What you describe is the designed behavior. There is a default markdown language specific setting for word wrap as word wrap is often desired in these files even if not enabled in others

**Comment by amithm7** [comment]
Okay, can this be made more evident in the settings that word wrap is set to 'on' by default for markdown?

![wordwrap](https://user-images.githubusercontent.com/7036770/56381073-7ce7db00-6231-11e9-8075-2b4836f9cac7.png)

**Comment by alexilyaev** [comment]
@sandy081 @mjbvz I've just spent 30 minutes not understanding why my wordWrap settings does not take effect in Markdown files. So I totally agree with @amithm7 that it should be noted in the settings when searching for "word wrap".

But I also think perhaps user settings should have higher priority than default language specific settings, but I don't see the big picture here, I just know it didn't make sense to set a custom user setting and not have it work in one of the languages.

**Comment by sandy081** [comment]
This was discussed here - https://github.com/microsoft/vscode/issues/45653

**Comment by alexilyaev** [comment]
@sandy081 Yes I know, and specifically noted by @yume-chan...

> Actually you made me thinking about is it not intuitive that a default value overriding a user value. Maybe the priority should be user [languageId] block -> user settings -> default [languageId] block -> default settings (If an extension really want the current behavior, it should add its [languageId] blocks to user settings).

The fact is more people in the future will go to change the word wrap settings and wonder why it doesn't apply to their Markdown files.

If you don't want to change the precedence, at least let's make it clear in the settings that some languages have a default which overrides it.
But I think it will back fire in the future, if more languages will have default settings (language specific) then a user might end up needing to write a lot of settings override if they want it to apply to all of the languages, which is really not a good user experience.

**Comment by sandy081** [comment]
@alexilyaev Filed a feature request for it - https://github.com/microsoft/vscode/issues/74195
