### ISSUE TITLE
"Manage Extension" is broken from notification

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#72557]
Steps to Reproduce:

1. install "Notification Tester" extension
2. bring up a notification
3. click on gear to "Manage Extension"

=> 🐛 nothing happens

**Comment by sandy081** [comment]
This is because notification tester extension has different gallery id `svipas.notification-tester` when compared to its id in the package.json `svipben.notification-tester`. Could be because the extension changed the publisher id without updating it in Marketplace.
