### ISSUE TITLE
Copy code in vscode, then paste into Evernote or Word, the indents will disappeared

### ISSUE THREAD

**Issue by sunwin123** [microsoft/vscode#72556]
- VSCode Version: newest version.
- OS Version: Windows 10.

Steps to Reproduce:

1.When {Editor:Detect indentation} is set Off, then you type codes in vscode editor with tab indent, then select & copy the codes, then paste it in other applications such as Word/Evernote, the indentations disappear!
2. However, When {Editor:Detect indentation} is set On, then you type codes in vscode editor with tab indent, then select & copy the codes, then paste it in other applications such as Word/Evernote, the indentations are there!
3. So, it is certainly an issue of VSCode! Not of other applications.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sunwin123** [comment]
I find another thing:
When paste into Plain text editors, indents will not disappear.
When paste into Rich text editors, indents disappear!

So, I think it shouldn't be an issue of those other rich text editors. It is of VSCode.

**Comment by sunwin123** [comment]
It is really a big problem for many programmers, they usually use copy/paste code into their blogs or notes.

**Comment by vsxen** [comment]
Yes, when you use Space indentation in your code, the idents will lost in OneNote, but use Tab indentation is normal.
So you'd better convert indents to Tabs in VSCode before copy：

Click ctrl + shift + p
Find command Convert Indentation to Tabs
Execute it and then copy your code to OneNote

https://github.com/microsoft/vscode/issues/35954#issuecomment-508985390
