### ISSUE TITLE
Fix "Test soft idle start/stop events" test

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7256]
@joaomoreno your change in https://github.com/Microsoft/vscode/commit/483c63bc0cbabe28f18e9a91b9637d582c75aead causes many test errors. One issue I could fix easily in https://github.com/Microsoft/vscode/commit/4ede18f76f8ed3cfe1374591a814ca42996c8049.

There is another test that seems to mock the eventing and I commented it out for now, but it should be fixable: https://github.com/Microsoft/vscode/commit/ad737c8de5a028589218fa19d2182e57814a1bba

@jrieken fyi as potential owner of that test

**Comment by joaomoreno** [comment]
@bpasero Thanks!
