### ISSUE TITLE
How to indent the code outline of the workspace

### ISSUE THREAD

**Issue by Rain120** [microsoft/vscode#72568]
OS Version: Windows 10 1809
Vscode version: 
![image](https://user-images.githubusercontent.com/20939839/56375310-b7547680-6237-11e9-821e-71404a33c3f4.png)

Current situation：
![image](https://user-images.githubusercontent.com/20939839/56375121-47de8700-6237-11e9-9ef2-14b70acb4575.png)

Expect:
![image](https://user-images.githubusercontent.com/20939839/56375319-c0454800-6237-11e9-9187-07781ee73581.png)

**Comment by gjsjohnmurray** [comment]
What File Icon Theme are you using?

**Comment by Rain120** [comment]
@gjsjohnmurray 
Thx you for replying to my question first.

I used which extension named vscode-icons,  and the theme named VSCode Icons.

![image](https://user-images.githubusercontent.com/20939839/56400587-43da5580-6287-11e9-9552-bb47c83780e1.png)

**Comment by gjsjohnmurray** [comment]
Maybe this issue belongs at https://github.com/vscode-icons/vscode-icons

**Comment by aeschli** [comment]
@Rain120 How did you get the 'expected' image?

Did you define any vscode-icon settings, e.g. about folders?

**Comment by Rain120** [comment]
@gjsjohnmurray 
Thx for your reply.
Maybe, I will new issue at the vscode-icon repo for help, and I will inform you as soon as possible of the results of the investigation.

**Comment by Rain120** [comment]
@aeschli 
Thx for your reply.
I found this extension in the VSCode extension store, the screenshot in its readme.

![image](https://user-images.githubusercontent.com/20939839/56573401-930be780-65f3-11e9-84de-a002fffc6649.png)

**Comment by JimiC** [comment]
Hi. `vscode-icons` maintainer here. There is nothing wrong. The user is asking how to achieve the intended folders visualization we show in the screenshot. What the user missed is that the indented folders are children of the `src` folder and thus `vscode` shows them indented to visualize the relationship when the parent folder gets expanded. In the users project the `src` folder is empty and thus even expanding it doesn't indent the folders beneath it simply because those are at the same level as the `src` folder. 

Mystery solved.

**Comment by Rain120** [comment]
@JimiC 

Why are the same projects different in different PC systems, such as windows and Mac?

The Current situation pic is windows

**Comment by JimiC** [comment]
There should be no difference. Can you post new screenies this time from your `Windows` and `MacOS` of the same project?

**Comment by Rain120** [comment]
@JimiC
Yes，Here it is.

Mac：

[Mac](https://user-images.githubusercontent.com/20939839/56573639-234a2c80-65f4-11e9-815c-99039602ae0e.png）

Windows:

**Comment by JimiC** [comment]
First, you are showing us different projects.
Second, your `src` folder in the `Windows` screenshot is empty. Move any file/folder in it and observe that they are shown indented as you expect.

**Comment by Rain120** [comment]
@JimiC

The first and second is the same project, and the third is another project.

There is the other project in my windows.

![image](https://user-images.githubusercontent.com/20939839/56583288-cfe3d880-660b-11e9-9b78-958e6532b6bd.png)

![image](https://user-images.githubusercontent.com/20939839/56582865-d3c32b00-660a-11e9-8775-d9c26b6dc3f7.png)

**Comment by JimiC** [comment]
OK, I see it now. I suspect that another extension is causing this misalignment. Disable all extensions and then enable them one by one until you find the one that is causing this.

**Comment by JimiC** [comment]
The one that adds that folder icon in the sidebar looks suspicious to me.

**Comment by Rain120** [comment]
First I disable all extensions, and then just enable vscode-icons.

![image](https://user-images.githubusercontent.com/20939839/56584962-7382b800-660f-11e9-925b-8758a11900b8.png)

![image](https://user-images.githubusercontent.com/20939839/56585039-a036cf80-660f-11e9-9ebb-7f4f5cb83fa6.png)

The result is still the same.

![image](https://user-images.githubusercontent.com/20939839/56585282-1affea80-6610-11e9-9c76-7e1eb9a87a3f.png)

**Comment by JimiC** [comment]
What color theme are you using?

**Comment by Rain120** [comment]
![image](https://user-images.githubusercontent.com/20939839/56587788-b85d1d80-6614-11e9-8fc4-2aa7ee373f90.png)

**Comment by JimiC** [comment]
The color theme, not the icon theme.

**Comment by Rain120** [comment]
srr, my fault

![image](https://user-images.githubusercontent.com/20939839/56588515-163e3500-6616-11e9-8c64-41dcb2222c82.png)

**Comment by JimiC** [comment]
![Untitled](https://user-images.githubusercontent.com/1716442/56591767-ff85e700-65f1-11e9-8537-5f31aec34a94.png)

This is how `vscode` looks on my `Windows` with `Monokai` and `vscode-icons`.

**Comment by Rain120** [comment]
![image](https://user-images.githubusercontent.com/20939839/56595370-15f76700-6621-11e9-9008-7ff5e10016e6.png)

I don't know why we are different.

**Comment by aeschli** [comment]
@Rain120 When you switch to the built-in `Minimal (Visual Studio Code) theme, do you see the same?

**Comment by Rain120** [comment]
I also found this problem by switching the theme to MiniMal according to your suggestion.
Should I uninstall and reinstall?

![image](https://user-images.githubusercontent.com/20939839/56659750-7f827e80-66d0-11e9-9d34-b8d0f4fda5c5.png)

**Comment by aeschli** [comment]
Looks like something is strange with positioning in the tree. @joaomoreno @isidorn

**Comment by joaomoreno** [comment]
@Rain120 Can you take a screenshot of the *full* VS Code window? I want to see the full status bar as well.

**Comment by Rain120** [comment]
@joaomoreno 
Thx for your reply.
Do you want this screenshot?

![image](https://user-images.githubusercontent.com/20939839/57232249-c5373380-704e-11e9-8b03-dacefa9d2a6f.png)

**Comment by joaomoreno** [comment]
The `workbench.tree.indent` setting controls the tree indentation. Did you change that setting?

**Comment by Rain120** [comment]
1. I should not set the **workbench.tree.indent** property. I need to go home and check it out. When I get home from work, I will paste my vscode user configuration information screenshot.
2. I'm not sure if there are plugins that affect the VSCode CSS style, but I tried to close all the plugins and only open **vscode-icons**, but it doesn't work.

**Comment by joaomoreno** [comment]
> I'm not sure if there are plugins that affect the VSCode CSS style, but I tried to close all the plugins and only open vscode-icons, but it doesn't work.

If a plugin messed around with Code's core CSS, it doesn't matter if you disable it... since they won't revert those changes. You should try a brand new installation, without any plugins.

**Comment by Rain120** [comment]
ok, I will try to uninstall all extensions and reset the user settings in vscode, then install vscode-icon  first, see the effect,  one by one  to find the extensions which affect the VSCode CSS style at last

**Comment by Rain120** [comment]
I just reset my user settings, then uninstalled all the plugins, and then installed one by one, I found that this problem has been solved, thank you so hard to help me solve the problem.
