### ISSUE TITLE
Offer "Manage Extension" from viewlet and view context menus

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#72562]
We have a pattern for status bar entries and notifications to "Manage Extension" and quickly see which extension contributed to the UI piece. I think it would be good to have the same when:
* right click on a viewlet icon in the activity bar
* right click on a view header in a viewlet

**Comment by sandy081** [comment]
If we want to make it consistent then all contributed pieces should have this like commands, menu actions etc., ?

**Comment by bpasero** [comment]
@sandy081 yeah totally, I can see this also working for right clicking on a contributed command 👍

**Comment by jrieken** [comment]
Not a fan of manage extension tbh. It allows me to disable/uninstall but I am usually only annoyed by that piece of UI, not the extension itself. GitLens is a good sample for that. What I think is missing is more user control, eg. allow users to hide status bar entries, allow users to configure menus. What we have today in the activity switcher works well for me and want it in more places.

**Comment by bpasero** [comment]
Yeah this is really just a workaround for not being able to do that, so that at least you get an idea where a UI contribution is coming from.
