### ISSUE TITLE
Share "inputs" variables across tasks.json and launch.json. 

### ISSUE THREAD

**Issue by jonenz** [Microsoft/vscode#72579]
- VSCode Version: 1.33.1
- OS Version: Linux x64 4.15 Juno

I am creating a debugging configuration that attaches to a remote session of GDB. The user needs to be prompted for the IP address of their target device. This IP is needed in both tasks.json and launch.json. It would be great if this variable was shared so the user did not have to enter it twice.

**launch.json**
```json
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Target GDB",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "Start GDBServer",
            "program": "/usr/bin/${workspaceFolderBasename}",
            "miDebuggerServerAddress": "${input:targetIP}:12345",
            "serverLaunchTimeout": "2000",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
        }
    ],
    "inputs": [
        {
          "type": "promptString",
          "id": "targetIP",
          "description": "What is the IP address of the target?",
          "default": "192.168.1.7"
        }
    ]
```

**tasks.json**
```json
    "version": "2.0.0",
    "tasks": [
        {
          "label": "Start GDBServer",
          "type": "shell",
          "command":"ssh root@${input:targetIP} 'gdbserver localhost:12345 --attach `pidof /usr/bin/${workspaceFolderBasename}` > /dev/null 2>&1 &'"
        }
    ]
```

**Comment by philipwasserman** [comment]
We run into the same remote debugging scenario where we have to type the hostname of the debugging target 3 times (once for preLaunchTask, once for launch configuration, and once for postLaunchTask). This is both error-prone and annoying to the developer.

Is there a reason this was marked "out-of-scope"?

**Comment by Xaz16** [comment]
I'm agree with that one, due to face the same issue: I'm duplicating input variables for tasks and launch jsons due to I have similar args to run my tasks/debug configurations

**Comment by bryceschober** [comment]
Me too.

**Comment by ConnorJBishop** [comment]
This would be a very welcomed feature

**Comment by pauloasherring** [comment]
+1

**Comment by carlossanlop** [comment]
@weinand can this issue please be considered again?

**Comment by weinand** [comment]
Have you tried to use VS Code's "Remote Development" extensions?
With that approach you connect to your remote site once and then run debuggers and tasks locally inside the remote host. So there is no need to ask for IP addresses any more.

**Comment by roboteacher1** [comment]
We are running code on devices and machines that don't support a development environment. We cross compile locally and deploy, run, and debug code elsewhere. Remote Development assumes the target is running the full Dev environment (minus the gui).

**Comment by deepakpchp** [comment]
+1

**Comment by cekuran** [comment]
+1

**Comment by alexandre-perrin** [comment]
+1

**Comment by Sour-Codes** [comment]
+1

**Comment by leo-costa** [comment]
+1

**Comment by framarbon** [comment]
+1

**Comment by russelltg** [comment]
+1

**Comment by ggladilo** [comment]
+1

**Comment by Sour-Codes** [comment]
Would love to see support for this.  Still an annoying issue I deal with today.  Notepad, copy, paste is not fun.

**Comment by paulokow** [comment]
+1

**Comment by Andrei-Basarab** [comment]
+1

besides this, it also would be cool to declare/define your own variables in `.vscode/*.json` files and use them directly there, for example like this:
```
"variables": [
    {
        "name": "myVariable",
        "value": "myValue",
    }
],
"cwd": "${workspaceFolder}/${var:myVariable}"
```

**Comment by shalauko** [comment]
+1

At least it would be very useful it such feature could be provided for `.code-workspace` files. It contains _launch_ and _tasks_ sections, and each of them should have it's own _inputs_ sections. In my case they are fully identically. The problem could be solved by commonise _inputs_  section.

**Comment by harkairt** [comment]
+1

would be great

**Comment by dernorberto** [comment]
+1
it would be amazing to pass the outcome from `tasks` into `launch` when e.g. processing a task and feeding the output to the launch

**Comment by mkiessling-ifx** [comment]
+1 obsoletely needed!!

**Comment by are-scenic** [comment]
> +1
> 
> besides this, it also would be cool to declare/define your own variables in `.vscode/*.json` files and use them directly there, for example like this:
> 
> ```
> "variables": [
>     {
>         "name": "myVariable",
>         "value": "myValue",
>     }
> ],
> "cwd": "${workspaceFolder}/${var:myVariable}"
> ```

@Andrei-Basarab  You already can do it. It's just that VSCode documentation is vary vague. In settings you can define any value you want, like this:

```json
"settings": {
               "my_variable": "my_value",

```

After that you can use it across settings, launch configurations and tasks like this:

```json
"tasks": {
		"version": "2.0.0",
		"tasks": [
			  {
				"label": "MakeDir",
				"type": "shell",
				"command": "mkdir",
				"args": [
				  "-p",
				  "${workspaceFolder}/${config:my_variable}/"
				],

```

**Comment by are-scenic** [comment]
+1

**Comment by afsay** [comment]
+1
I have the same issue, I have to duplicate my inputs in tasks.json and launch.json file:
 ```
"inputs": [
        {
          "type": "pickString",
          "id": "targetHW",
          "description": "Select HW",
          "options": [
            "STM32F0",
            "STM32F1",            
          ],
          "default": "STM32F0"
        },
        {
            "type": "pickString",
            "id": "buildType",
            "description": "Select Build Type",
            "options": [                
              "Debug",
              "Release",            
            ],
            "default": "Debug"
          },
]
```

**Comment by Tea2Jay** [comment]
+1

**Comment by romeoxbm** [comment]
+1

**Comment by alexisbg** [comment]
+1

**Comment by dimateos** [comment]
This issue was deemed out of scope in 2019. Nowadays task usage is much more widespread so maybe it's time to reconsider @weinand ?

I find myself copy pasting inputs from tasks to launch quite frequently... for example a `pickString` input with a set of paths I want to use for launching tests tasks but also in some cases for debugging a specific case etc.

Best regards

**Comment by inxksp** [comment]
+1 
This needs to be implemented

**Comment by inxksp** [comment]
The best option is to add the "include file" to task.json and launch.json.

**Comment by inxksp** [comment]
A good example is СmakePresets. And VS Сode supports it

**Comment by dimateos** [comment]
So https://github.com/microsoft/vscode/issues/214956 was not marked out of scope, but did not gain +20 votes, maybe this one could be reopened then?

Notice that the linked one also mentions the issue about **global** inputs not shared across local inputs either!

Today I had to copy paste inputs from my global tasks.json to my local launch.json, such a bummer to maintain 3+ copies:
* local tasks.json
* local launch.json
* global tasks.json
* +even rarely used global launch configs stored in global settings.json (yes that is possible)

Maybe the implementation could be related to https://github.com/microsoft/vscode/issues/53557
