### ISSUE TITLE
Using VS Code as git commit editor results in empty commit message when file is closed quickly after editing

### ISSUE THREAD

**Issue by lukewlms** [microsoft/vscode#72573]
- VSCode Version: 1.33.1
- OS Version: 10.14.4

When editing and closing a git commit message file very quickly, the contents are not provided to git.  Currently I manually save before closing any git commit file but it seems clear this should work properly - autosave should happen, _then_ Code should inform Git that the commit file is ready.  Currently it appears the two events are happening in reverse order, causing a bug.

Steps to Reproduce:

1. Add VS Code as `git commit` editor (`code --wait`)
2. Perform a git commit
3. Edit the commit message in Code
4. Quickly close the commit message in Code, before autosave occurs

**Result:** git complains about an empty commit message

**Expected:** Autosave should happen _before_ Code releases control back to git, resulting in a properly saved commit message

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Good catch. Extra points for using auto save in VSCode :+1:

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73682
