### ISSUE TITLE
Improve snap metadata

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#72571]
Issues:

- No mention of "vscode" and their search does exact text matching so that won't show the app
- Use of markdown ** looks bad

<img width="734" alt="Screen Shot 2019-04-18 at 10 41 10 AM" src="https://user-images.githubusercontent.com/2193314/56380239-84be6580-61c6-11e9-823a-700da40b8d46.png">

**Comment by joaomoreno** [comment]
The website does show Markdown: https://snapcraft.io/code

The editing page even says it is supported:

![image](https://user-images.githubusercontent.com/22350/57212732-eebb7500-6fe4-11e9-8531-f014d7131ad8.png)

I guess they didn't implement that on the Software Center. I'll remove it.
