### ISSUE TITLE
User Settings support for TypeScript plugin configuration

### ISSUE THREAD

**Issue by cpboyd** [Microsoft/vscode#72578]
This was originally described in #63648, but was only resolved for extensions (#63181) via https://github.com/Microsoft/vscode/commit/575e1630d556bd6272724d4d20662c8f6ff745e8.

`typescript.tsserver.pluginPaths` currently only seems to take an array of strings, with no ability to specify any options.

Would it be possible to allow it to accept an array of strings (to keep from breaking a user's existing settings) **or** objects as used in `tsconfig.json`, e.g.:
```json
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "customMatcher": "\\.m\\.css$",
          "camelCase": "dashes"
        }
      }
```

Sure, it'd be possible to create an extension for configuring the CSS Module TypeScript support, but that seems like overkill when all I want to do is specify `"camelCase": "dashesOnly"`

Edit: My current workaround is just to use the workspace version of TypeScript and `tsconfig.json`.

**Comment by mjbvz** [comment]
In almost all cases you should configure these in the tsconfig itself or use a VS Code extension that allows configuring the plugin through setting. `typescript.tsserver.pluginPaths` was added only to support a specific use case and is not well supported in general

Closing as out of scope. Adds too much complexity for very limited user value

**Comment by mrmckeb** [comment]
Hi @cpboyd, thanks for raising this - I'm the author of that plugin and was hoping to update the docs if there had been any changes.

Thanks for the response @mjbvz. I understand that you're suggesting that a VSCode plugin be created, or that the user uses their workspace version of TypeScript. Is my understanding correct?

Is there a reason VSCode doesn't read plugins from `tsconfig.json`?

**Comment by mjbvz** [comment]
Yes, executing code automatically from the workspace when you open it would be unsafe. We only load plugins from the workspace if you are using a workspace version of TypeScript

**Comment by mrmckeb** [comment]
Thanks @mjbvz. Let's hope the TypeScript team can improve the way plugins work in future to make this easier for users.
