### ISSUE TITLE
Provide setting to disable focusing editor when selecting a file in the explorer

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7257]
Steps to Reproduce:

1. Click a file in explorer, notice focus is sent to the editor

This is particularly bothersome when navigating the explorer with the keyboard. See https://github.com/Microsoft/vscode/issues/1025

**Comment by bpasero** [comment]
Not for me:

![editors](https://cloud.githubusercontent.com/assets/900690/15846593/0c847e94-2c7f-11e6-9472-52ea10dc06c6.gif)
