### ISSUE TITLE
Formatting on save is actually formatting after save

### ISSUE THREAD

**Issue by LMulvey** [Microsoft/vscode#72577]
- VSCode Version: 1.33.1
- OS Version: Mac OS 10.13.6 High Sierra

Steps to Reproduce:

1. Open a JavaScript file with `vscode-prettier` running
2. Ensure formatOnSave is enabled
3. Make a change that does not adhere to the Prettier settings (priming it to format on save)
4. Save the file.

The file will save, and then format, causing unsaved changes to occur.

![example gif](https://user-images.githubusercontent.com/16218249/56390060-55205500-61e8-11e9-9a2e-efa75cf004e0.gif)

Does this issue occur when all extensions are disabled?: Yes/**No**

**Comment by johnletey** [comment]
@LMulvey I've also noticed this too ... really annoying (especially when formatting then committing immediately after)

**Comment by jrieken** [comment]
> The file will save, and then format, causing unsaved changes to occur.

No, that's not how its implemented. There are two event, `willSave` and `didSave`, all our formatting logic is implemented during the `willSave` phase. This can only be an issue with the formatter extension not integrating well (as a formatter but as a bunch of commands)
