### ISSUE TITLE
Git: Support aborting the current rebase

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/vscode#72576]
It's very common to have to resolve merge conflicts during a pull with rebase. You might decide that you want to *stop* and try something else. There's no way, that I found, through the source control UI or command palette to properly abort a rebase.

You can get into a jam trying to abort, though. Like clicking the branch button in the status bar. You can choose your local branch and have the local branch's contents restored, but Code leaves you in a rebase (and that's no good).

You're stuck running `git rebase --abort` on the command line.

(I'll upload some pics later when I can contrive some examples... sorry, I didn't capture them while I was causing trouble earlier.)

**Comment by vitaliymaz** [comment]
I'd like to work on the implementation. But there are 2 options when a repository is being rebased: continue and abort. I can add two menu items right under "Pull (Rebase)": "Rebase Continue" and "Rebase Abort". Will it work from the UX perspective?

**Comment by joaomoreno** [comment]
Rebase continue is already implemented: if you try to commit during a rebase, it will run rebase continue instead. All we're missing is the abort action.

**Comment by vitaliymaz** [comment]
So, adding "Rebase Continue" option under the "Pull (Rebase)" will be ok. Am I right?

**Comment by AnthonyMastrean** [comment]
@joaomoreno This is good to know and takes some exploring to figure out. Are there any good patterns to explain this like during your 1st use of the feature? Or in the docs somewhere? This is a problem any time you combine git commands (like Sync).

**Comment by joaomoreno** [comment]
We could maybe add that to the docs. :+1: Wanna submit a PR on https://github.com/Microsoft/vscode-docs ?

**Comment by AnthonyMastrean** [comment]
@joaomoreno Hey, to this point (https://github.com/microsoft/vscode/issues/72576#issuecomment-489652354), I don't recall anywhere except maybe the Output | Git log that you can tell that the rebase has continued. There's no *obvious* status that commits are being replayed or that you may need to wait a few seconds for the next merge conflict to render in the source control explorer (if there are more conflicts) or even if the rebase is "done".

You end up needing to check the Git status on the command line anyway.

**Comment by jmbockhorst** [comment]
I did some exploration on supporting rebase features, which is related to this. https://github.com/microsoft/vscode/issues/31153#issuecomment-478274005

**Comment by vitaliymaz** [comment]
@jmbockhorst, looks like your implementation covers git abort and my PR is not required anymore. Closing it.
