### ISSUE TITLE
accessibility of vs code on Mac with line breaks reading correctly

### ISSUE THREAD

**Issue by tayarndt** [microsoft/vscode#72570]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. turn on voiceover on a Mac by pressing cmd f5
2. open a file in vs code with some blank lines

Does this issue occur when all extensions are disabled?: Yes/No
yes it does 
Hardware/ software
I am running vs code on a Mac book pro 2017 with 16 gigs of ram. My software is the latest version, and I am also using voiceover on the Mac. 
Issue
The issue is when using VS code with voiceover, which is apples built in screen reader, Line-breaks are not read. The current behavior is when using the arrow keys to navigate the lines of the file, voiceover doesn’t say anything when a blank line is encountered.  As a result, when using the arrow keys to navigate a file with voiceover, it is difficult to know where the blank lines are.Another thing is when there were a blank line, visual studio code would read that block of text twice. It would go something like this new new line than the code statement. Then the next line has the code statement only. Hope this makes sense. I can.produce an audio clip if that would be helpful. I am also using the accessibility mode with vs code.

**Comment by alexandrudima** [comment]
Let's continue tracking in #70033 , where the OP has reached out directly to Chromium.

**Comment by alexandrudima** [comment]
May I also kindly encourage that you subscribe and comment at https://bugs.chromium.org/p/chromium/issues/detail?id=951777
