### ISSUE TITLE
Debug Console hyperlinks

### ISSUE THREAD

**Issue by zhulika** [Microsoft/vscode#72572]
If I write a message to the Debug Output Window in the Visual Studio IDE that starts with the filename and line number in a particular format, e.g.:

```
c:\myapp\main.cc(12): Help!
```

then double-clicking on this line will make the IDE open the file at the appropriate line. I find this to be extremely helpful.

Although VSCode is able to do the equivalent in the Integrated Terminal, by (ctrl-clicking the message), the Debug Console window doesn't support this.

Can you extend it so that it does the same thing as the Integrated Terminal Window, please?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/27713
