### ISSUE TITLE
Cannot open Terminal - crashes the window immediately

### ISSUE THREAD

**Issue by oising** [Microsoft/vscode#72580]
Issue Type: <b>Bug</b>

It's as simple as the title. Attempting to switch to the terminal popups up a dialog saying the window has crashed, and offers the option to reopen.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
azurenodeessentials|azu|0.2.6
azuretoolsforvscode|bra|2.0.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
javadebugger|don|0.1.5
xml|Dot|2.4.0
gitlens|eam|9.6.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.11
terraform|mau|1.3.9
vscode-azureappservice|ms-|0.13.0
vscode-azurefunctions|ms-|0.16.0
vscode-azurestorage|ms-|0.7.0
vscode-azureterraform|ms-|0.2.3
mssql|ms-|1.5.0
python|ms-|2019.3.6558
azure-account|ms-|0.8.2
azurecli|ms-|0.4.4
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
powershell|ms-|1.12.1
azurerm-vscode-tools|msa|0.5.0
debugger-for-chrome|msj|4.11.3
gradle-language|nac|0.2.3
vscode-docker|Pet|0.6.1
java|red|0.43.0
yo|sam|0.9.3
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1
vscode-icons|vsc|8.5.0
vscode-wakatime|Wak|1.3.0
iis-express|war|1.1.2
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by oising** [comment]
running with --disable-extensions has no effect. It still crashes immediately.

**Comment by Tyriar** [comment]
Adding the setting `"terminal.integrated.windowsEnableConpty": false` should fix it

/duplicate https://github.com/Microsoft/vscode/issues/72190
