### ISSUE TITLE
Pressing right arrow on an open folder in the explorer should send focus to the directories first child

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7258]
Steps to Reproduce:

1. Focus explorer
2. Move focus to a closed directory
3. Press <kbd>&rarr;</kbd> to open the dir
4. Press <kbd>&rarr;</kbd>, notice nothing happens

I expect the first child of the directory to be focused.

**Comment by bpasero** [comment]
that should happen on the level of the tree

**Comment by joaomoreno** [comment]
Is this platform dependant? Finder, in OS X, does not behave that way.

**Comment by Tyriar** [comment]
I believe this is how Windows Explorer works and it's how I generally expect tree views to work. Atom works the same as I'm describing https://github.com/atom/tree-view/issues/561 (I actually did the PR before joining :stuck_out_tongue:)

**Comment by elemongw** [comment]
What's the stance on platform conventions conformity? Currently vscode also expands a tree if you click on it, which doesn't conform with OS X conventions. I was ready to open a pr to change that, should I go ahead or is the project policy not to follow them so closely?

**Comment by joaomoreno** [comment]
@elemongw How would the user expand a directory, then?

**Comment by elemongw** [comment]
Yeah sorry I should be more specific. Currently wherever you click in the line, the tree expands. The standard behaviour is to expand only when the little arrow that is before the folder name is clicked.

**Comment by joaomoreno** [comment]
cc @bpasero what do you think?

**Comment by Tyriar** [comment]
I strive for a consistent experience across platforms personally (tweaking keybindings/settings where necessary). I seldom use OS X though and Linux/Windows are fairly similar.

**Comment by joaomoreno** [comment]
I think this wouldn't fly so late in the game. Besides, we're trying to achieve OS consistency in keybindings, but product consistency in UI, so we'd probably not take just clicking the twisty for expanding/collapsing.
