### ISSUE TITLE
No vertical scrollbar appears the 1st time completion resolve occurs

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#72587]
- VSCode Version: 1.33.1
- OS Version: Windows

Steps to Reproduce:

1. Install the C/C++ extension. It's not a C/C++ extension bug,
but it doesn't repro with TypeScript.
2. Use the code below in a .cpp file, and use Ctrl+Space to invoke completion after "test1".
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
// lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text 
int test1;
test1

![image](https://user-images.githubusercontent.com/19859882/56397500-d7187a00-61f8-11e9-9d55-d5ecfb7ae3c9.png)

Bug: No vertical scroll bar appears so the text isn't viewable.
The vertical scrollbar re-appears the 2nd time completion occurs,
but the bug starts reproing again after a Reload Window.

This is the expected result:
![image](https://user-images.githubusercontent.com/19859882/56397537-0dee9000-61f9-11e9-8cb2-92ef1a92fe1e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by arussellk** [comment]
I was able to reproduce this in a `.ts` file by changing the comment style to `/**`.

I'd like to try fixing this bug and would appreciate any tips of where to look in the codebase.

VSCode version: 1.33.1
OS version: macOS Mojave 10.14.4
Extensions: none

```
/** lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 * lots of text lots of text lots of text lots of text lots of text lots of text lots of text lots of text
 */
let test1;
test1
```

Note: the scrollbar does appear for me (unlike the original bug report) but the content appears to be truncated the first time I press `Ctrl+Space`.

![image](https://user-images.githubusercontent.com/6454257/57572250-ebedc500-73d4-11e9-8359-fa1f6fd6169d.png)
