### ISSUE TITLE
Wrong tooltip on extension page uninstall button after installing extension

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#72585]
Issue Type: <b>Bug</b>

**Repo**
1. Install a theme extension in the editor
1. After the install, hover over the `uninstall` button on the extensions page

**Bug**
The tooltip reads `Installing`:

![Screen Shot 2019-04-18 at 4 26 16 PM](https://user-images.githubusercontent.com/12821956/56397064-df6fb580-61f6-11e9-9c51-2ebe1fd66d60.png)

VS Code version: Code - Insiders 1.34.0-insider (f89390fcec44a24ce74dfc4efbc1438f35b7357a, 2019-04-18T13:31:41.962Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|

**Comment by georgejiang97** [comment]
Hi,

Could I try to take this? Any pointers would be appreciated :)

**Comment by sandy081** [comment]
@georgejiang97 You can start from here - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/extensions/electron-browser/extensionsActions.ts#L496
