### ISSUE TITLE
`insertBestCompletion` doesn't work on snippet-placeholders

### ISSUE THREAD

**Issue by AviralGarg1993** [Microsoft/vscode#72582]
**Short:**
auto-completion/insertBestCompletion/text-expansion doesn't work when you are replacing a snippet placeholder.

**Detailed:**
Let's take a case: 
Keystrokes: `i` `f` [tab] would results in:
```
if($1{condition}){
$2
}
```
after that my cursor goes on selecting the first placeholder ($1{condition}) where I would replace `condition` with the actual condition I would like to use in the if statement. BUT, I cannot use the auto-complete/insertBestCompletion feature ([ctrl]+[space] or [tab] or click on the option from the context menu that automatically appears <-- intellisense? that doesn't even show up when I am in that placeholder-replacement-step).

I would like to be able to auto-complete even while I am replacing a placeholder.
I think I was quite redundant but this is my first ever feature request. Let me know how I can improve this request.

Thanks

**Comment by jrieken** [comment]
>  cannot use the auto-complete/insertBestCompletion feature ([ctrl]+[space] or [tab] or click on the option from the context menu that automatically appears

Can you clarify? What do you expect in the context menu? `Tab` not working is kind of expected because when inserting snippets `tab` moves to the next placeholder. Pressing `ctrl+space` should always work, unless no suggestion can be computed

**Comment by AviralGarg1993** [comment]
As you can see in the gif file below, suggestions show up as we type `sysout` when not inside any snippet placeholder, otherwise, they don't show up.

![snippetNotWorking](https://user-images.githubusercontent.com/12901566/56702038-df6c2b80-66b6-11e9-962c-d52e088ead5d.gif)



You are right about:

- `ctrl+space` works inside snippet-placeholder.

- `tab` shouldn't be used for auto-completion in this case.

**Comment by AviralGarg1993** [comment]
Please let me know if and when I should change the title and description of this issue to remove the parts that weren't really an issue.

**Comment by jrieken** [comment]
Quick suggestions and snippet placeholder often collide and by default quick suggestions are disabled when snippet mode is active. This setting controls that behaviour: `editor.suggest.snippetsPreventQuickSuggestions`
