### ISSUE TITLE
Initializing JS/TS languages features just ALWAYS there

### ISSUE THREAD

**Issue by Kindok** [Microsoft/vscode#72596]
Issue Type: <b>Bug</b>

It just run, never stop

VS Code version: Code - Insiders 1.34.0-insider (7d39e805fb66a6eac22f19af8bb90f48da863fd5, 2019-04-19T05:14:36.383Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
wechat-snippet|Cha|0.4.10
wxml-vscode|cny|0.1.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
beautify|Hoo|1.4.11
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-icons|vsc|8.5.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by Inveth** [comment]
Same here for windows 10 - unusable editor really.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Also, does javascript/typescript intellisense and other editor features work when this happens?

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this issue
