### ISSUE TITLE
vacode无法使用mac的三指取词功能

### ISSUE THREAD

**Issue by litao1993** [microsoft/vscode#72591]
- VSCode Version: 1.33.1
- OS Version:macOS 10.14.4

复现步骤:

1. 光标移动到单词上方，使用三指轻触，无法弹出mac的翻译弹窗

**Comment by litao1993** [comment]
这个功能对我很重要！！！

**Comment by vsTianhao** [comment]
Change to English

**Comment by litao1993** [comment]
@vsTianhao 切换到英文也不行

**Comment by litao1993** [comment]
@rebornix

**Comment by rebornix** [comment]
It's an known issue, thanks for reporting.

**Comment by litao1993** [comment]
> It's an known issue, thanks for reporting.

好的，谢谢

**Comment by litao1993** [comment]
@rebornix 想问一下近期有修复计划吗

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/31047 and let's track it there.
