### ISSUE TITLE
Relative path instead of absolute

### ISSUE THREAD

**Issue by alienvspredator** [Microsoft/vscode#72590]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Create blank c++ project.
2. Open problems tab.
3. Click on any message and go to the problem.
4. But VSCode will not find path, because problem message contains absolute path, and VSCode will try to open it like relative path.
5. You can see VSCode notification:
Unable to open 'main.cpp': File not found (file:///absolute/path/main.cpp).
6. Click "Create File" and update file tree. You can see "./absolute/path/main.cpp" inside your project folder.

**Comment by sandy081** [comment]
Please file it against c++ extension as it generates these problems with these URIs.
