### ISSUE TITLE
Javascript Error Highlighting not working

### ISSUE THREAD

**Issue by cannahum** [Microsoft/vscode#72595]
Issue Type: <b>Bug</b>

I have  a .js file (jest test spec to be more specific)
I have a bunch of re-declared const statements, e.g.
```
it('should work', () => {
  const result1 = testMe('foo');
  const result1 = testMe('bar');
});
```
I should be getting error highlighting but I don't.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|/Users/cnahum/Projects/wallet-v2/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
flow-for-vscode|flo|1.1.1
latex-workshop|Jam|6.4.0
plantuml|jeb|2.10.9
graphql-for-vscode|kum|1.13.1
code-beautifier|mic|2.2.1
vscode-scss|mrm|0.6.2
vsliveshare|ms-|1.0.67

</details>

**Comment by mjbvz** [comment]
More advanced error reporting (semantic errors) are enabled by the checkJs setting: https://code.visualstudio.com/Docs/languages/javascript#_type-checking

Basic js error reporting only cover syntax errors
