### ISSUE TITLE
Add Backup Feature

### ISSUE THREAD

**Issue by OmPipi** [Microsoft/vscode#72599]
Issue Type: <b>Feature Request</b>

Please add preference/setting backup feature (included preference and installed extension), so when I install VScode in another PC, I no need to setup from zero, just import backup file then VScode will append it. I hope VScode team will realize it. Thanks

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by johnletey** [comment]
@OmPipi You can already do this by using [settings-sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) ... and it doesn't just sync your settings, but also keybindings and extensions

**Comment by johnletey** [comment]
However, it would be nice to have this built in

**Comment by OmPipi** [comment]
Thank you for reply, but my problem is when my friends want to use VScode
with same setting, extension, etc. I don't want to sign in for sync, so I
want just give them backup file without sign in.

**Comment by johnletey** [comment]
> so I want just give them backup file without sign in.

Understand ... let's see what the team say, because this will definitely be a handy feature

**Comment by OmPipi** [comment]
> 
> 
> > so I want just give them backup file without sign in.
> 
> Understand ... let's see what the team say, because this will definitely be a handy feature

by the way, I can't find sync feature in settings, just Git sync.

**Comment by johnletey** [comment]
> I can't find sync feature in settings, just Git sync.

You've installed the plugin right?

**Comment by OmPipi** [comment]
Oh sorry, I read from email directly, so I don't know you give plugin link.
Thanks

**Comment by johnletey** [comment]
No problem

**Comment by roblourens** [comment]
We are tracking this request in https://github.com/Microsoft/vscode/issues/2743
