### ISSUE TITLE
Copy/Paste buffer is permanently tainted with error messages

### ISSUE THREAD

**Issue by NoSuchProcess** [Microsoft/vscode#72597]
I have:
Version: 1.33.1
Фиксация: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Дата: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
ОС: Linux x64 4.4.0-116-generic (Ubuntu 14.04 x64)

Steps to Reproduce:

1. Open some file (I use C source code)
2. Copy some text with Ctrl+C or with popup menu
3. Open new file, paste buffer contents with Ctrl+V or with popup menu
4. Behold some strange json with error messages:
[garbage.txt](https://github.com/Microsoft/vscode/files/3097239/garbage.txt)

Does this issue occur when all extensions are disabled?: No

**Comment by octref** [comment]
Please report to the C extension you are using.
