### ISSUE TITLE
workbench.files.action.focusFilesExplorer can focus open editors

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7259]
This is a regression with the inclusion of stacks. I had `workbench.files.action.focusFilesExplorer` bound to <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>e</kbd> so that it would consistently focus the file explorer and stay away from working files. Now it just focuses whatever was focused last in the explorer pane (ie. same as the default keybinding `workbench.view.explorer`). 

Steps to Reproduce:

1. Open a folder
2. Open a file
3. Click the opened file in open editors
4. Trigger `workbench.files.action.focusFilesExplorer`, the file explorer should be focused, not open editors

**Comment by bpasero** [comment]
Not for me:

![editors](https://cloud.githubusercontent.com/assets/900690/15846676/cbe375ce-2c7f-11e6-8b6d-fa2eac314336.gif)

**Comment by Tyriar** [comment]
My bad, I tried again and it worked. I think this was either a missing comma in my keybindings or I only reloaded the window, didn't restart vscode.
