### ISSUE TITLE
Emmet: Support css.color.short setting

### ISSUE THREAD

**Issue by agragregra** [microsoft/vscode#72594]
"emmet.preferences": {
	"css.color.short": true
}
Why not working?

**Comment by ramya-rao-a** [comment]
@sergeche Does the new modular emmet support this feature?

**Comment by sergeche** [comment]
@ramya-rao-a yes, it should be passed as `shortHex` option: https://github.com/emmetio/stylesheet-formatters/blob/master/format/css.js#L7

**Comment by ramya-rao-a** [comment]
Looks like it is enabled by default. Since VS Code doesnt change that particular property, we will need to debug why this doesnt work.

**Comment by Friksel** [comment]
I'm having the same problem, using the latest VS Code version: 1.35.0. 
After adding the setting `"css.color.short": true` as mentioned above, Emmet in VS Code still expands `#1` to `#111111` instead of `#111`.

Hope this could get some love, because small color values are just way more sexy!

**Comment by rzhao271** [comment]
@agragregra @Friksel I updated the Emmet dependency, and now css.color.short is enabled by default in the latest Insiders.

I still have to add the setting to VS Code if one wants to disable it for whatever reason, so I'll leave this issue open.
