### ISSUE TITLE
Powershell Terminal Fails to Fully Load

### ISSUE THREAD

**Issue by mcollier** [Microsoft/vscode#72592]
Issue Type: <b>Bug</b>

My default terminal in VS Code is PowerShell.  I've noticed that after starting VS Code and switching to the Terminal tab (at the bottom of VS Code), the terminal doesn't fully load.  I have to touch into the terminal window, and often press the Enter key a few times.  Doing so will get the terminal to load to a point where I can use it.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.26.0
docs-article-templates|doc|0.2.2
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.4
docs-preview|doc|0.3.17
docs-yaml|doc|0.2.1
gitlens|eam|9.6.2
code-runner|for|0.9.8
docker-explorer|for|0.1.6
dotnet-test-explorer|for|0.6.6
vscode-pull-request-github|Git|0.6.0
rest-client|hum|0.21.2
azure-pipelines|ms-|1.147.2
vscode-azureappservice|ms-|0.13.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|0.16.0
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.1
vscode-logicapps|ms-|0.1.17
mssql|ms-|1.5.0
python|ms-|2019.3.6558
azure-account|ms-|0.8.2
azurecli|ms-|0.4.4
csharp|ms-|1.19.0
powershell|ms-|1.12.1
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.5.0
vscode-docker|Pet|0.6.1
quicktype|qui|12.0.46
vscode-yaml|red|0.4.0
bash-debug|rog|0.3.4
arm-snippets|sam|1.4.13
code-settings-sync|Sha|3.2.9
code-spell-checker|str|1.6.10
vscode-icons|vsc|8.5.0

(1 theme extensions excluded)

</details>

**Comment by rahmatafridi** [comment]
Same Issue with vscode latest version and with windows 10 x64

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
