### ISSUE TITLE
Automatically prefix the dependent reference with the ./node_modules prefix

### ISSUE THREAD

**Issue by cs840610862** [Microsoft/vscode#72600]
Issue Type: <b>Bug</b>

jsx文件在文件切换的时候，会自动给依赖引用加上./node_modules前缀，导致引用依赖错误，希望尽快纠正，不要无形中把代码修改错误

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.8.1
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
vscode-language-pack-zh-hans|MS-|1.33.2
vetur|oct|0.18.1
view-in-browser|qin|0.0.5

</details>

**Comment by mjbvz** [comment]
> JSX file when the file is switched, the dependency reference is automatically added to the./node_modules prefix, resulting in a reference dependency error, which you want to correct as soon as possible, and do not invisibly modify the code incorrectly

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate
