### ISSUE TITLE
PHP syntax is half highlighted

### ISSUE THREAD

**Issue by githubhero** [Microsoft/vscode#7260]
- VSCode Version: 1.1.1
- OS Version: OS X El Capitan 10.11.5

Here I see an image with PHP syntax highlighted: https://code.visualstudio.com/Docs/languages/php
but I can't see it highlighted in my editor... about any PHP is white, "header", "fopen", "file_get_contents", etc. In a random file, the only things I see hightlighted are: true, if, exit, isset and echo...

Steps to Reproduce: just look at the syntax

**Comment by aeschli** [comment]
@githubhero What theme are you using? What you describe sounds like the Dark (Visual Studio) theme. If you like variable and function declaration highlighted, use the Dark+ theme.

If that's not the problem, please add a code snippet that shows the issue.

**Comment by githubhero** [comment]
@aeschli I'm using Monokai. 

In the following snippet, I want to highlight:

- <?php and ?>
- file_get_contents
- json_decode
- trim
- strtolower
- file_exists
- fopen
- fwrite
- fclose
- in_array
- header
- unset

<?php

$content = file_get_contents('php://input');
$update = json_decode($content, true);

$text = trim($text);
$text = strtolower($text);

$filePath = 'jvm/jsm.json';

switch ($text) {
	case '/start':
	
	if (file_exists($filePath)) {
		// found
		$string = file_get_contents($filePath);
		$obj = json_decode($string, true);
		$ids = $obj['ids'];
		
    if (in_array($chatId, $ids)) {
			header('Content-Type: application/json');
			$parameters = array('chat_id' => $chatId, 'text' => 'running');
			$parameters['method'] = 'sendMessage';
			echo json_encode($parameters);
		}
		else {
			$ids[] = $chatId;
			$a = array('ids' => $ids);
			$fp = fopen($filePath, 'w');
			fwrite($fp, json_encode($a));
			fclose($fp);
			
			header('Content-Type: application/json');
			$parameters = array('chat_id' => $chatId, 'text' => 'Avviato');
			$parameters['method'] = 'sendMessage';
			echo json_encode($parameters);
		}
	}
	else {
		// not found
				   $a = array('ids' => array($chatId));
		$fp = fopen($filePath, 'w');
		fwrite($fp, json_encode($a));
		fclose($fp);
		
		header('Content-Type: application/json');
		$parameters = array('chat_id' => $chatId, 'text' => 'ok');
		$parameters['method'] = 'sendMessage';
		echo json_encode($parameters);
	}
	;
	break;
	case '/stop':
		   if (file_exists('jvm/jvm.json')) {
		
		$string = file_get_contents($filePath);
		$obj = json_decode($string, true);
		$ids = $obj['ids'];
		if (in_array($chatId, $ids)) {
			
			unset($ids[array_search($chatId, $ids)]);
			$a = array('ids' => $ids);
			$fp = fopen($filePath, 'w');
			fwrite($fp, json_encode($a));
			fclose($fp);
			
		}
		else{

			// cut...
			
		}
		
	}
	// cut...
}

?>

```

**Comment by githubhero** [comment]
@aeschli Martin, I updated to 1.2.0 right now and, aside from <?php and ?>, it looks like it is working now

**Comment by aeschli** [comment]
I don't know why Monokai doesn't highlight <?php and ?>. We are not the author of the Monokai theme. From the dark+ theme I see that these elements are highlighted, so it looks like special tokens are returned and could be colored.
Please file separate bugs for JavaScript and C#. If possible add screenshots and snippet.
Note that for C# you need the OmniSharp extension and issues can directly be filed against https://github.com/OmniSharp/omnisharp-vscode.

**Comment by githubhero** [comment]
Done, thanks.
