### ISSUE TITLE
文件选择

### ISSUE THREAD

**Issue by bufanrush** [Microsoft/vscode#72603]
Issue Type: <b>Bug</b>

 当我选择我的文件时 ，总是自动打开我的文件目录，那么有很多文件时，就很繁琐，需要频繁的手动关闭我的文件目录，而其实我只是需要查看我的文件而已！

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G4600 @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.33.2
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details>

**Comment by octref** [comment]
Please report issue in English.
