### ISSUE TITLE
Python : Pretty print pandas dataframe in debugger

### ISSUE THREAD

**Issue by NiIkLaAs** [Microsoft/vscode#72604]
Issue Type: **Feature Request**

Could be possible to add in vscode or in the python extension, the possibility to have pretty print of pandas dataframe when debugging, as it exists in Pycharm, in a matrix format ?
Pandas is one of the most used library in Python, so it makes sense to me to have specific development for it.
I asked the question here : https://stackoverflow.com/questions/52225216/pretty-print-a-pandas-dataframe-in-vs-code
But had no satisfactory answer.

**Comment by weinand** [comment]
VS Code does not have a built-in Python debugger. Please file this feature request against the Python extension you are using. You can use VS Code's built-in "Issue reporter" for this:

<img width="700" alt="2019-04-19_14-14-57" src="https://user-images.githubusercontent.com/1898161/56423687-9e86a800-62ad-11e9-80aa-7069fd3c9248.png">
