### ISSUE TITLE
The validation of shell paths does not work properly for empty strings

### ISSUE THREAD

**Issue by roottool** [microsoft/vscode#72601]
## Environment

- VSCode Version: 1.34.0
- OS Version: Windows_NT x64 10.0.17763

## Description

I found this issue when I was trying to fix #72425.
`_validateShellPaths` function in `src\vs\workbench\contrib\terminal\common\terminalService.ts` does not work properly when an array include an empty string at the beginning is sent to `_validateShellPaths` function.

## Steps to Reproduce

1. Add the below to `expectedLocations` in `src\vs\workbench\contrib\terminal\electron-browser\terminalService.ts`.

```ts
test: ['', `${system32Path}\\cmd.exe`],
````

2. Run `npm(or yarn) run watch`
3. Choose the Launch VS Code launch configuration from the launch dropdown in the Debug viewlet and press F5.
4. Press `Ctrl+Shift+P`.
5. Select `Terminal: Select Default Shell`.

## Expect behavior

Choose `${system32Path}\\cmd.exe`

## Actual behavior

Choose an empty string

## Screenshot

![ValidationDoesNotWorkProperlyForEmptyStrings](https://user-images.githubusercontent.com/11808736/56414285-14e2d480-62c5-11e9-9b7f-50f429475f6f.jpg)

## Note

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I guess we can just special case `''` and not do the file check to catch accidental errors?

**Comment by roottool** [comment]
I have an idea.
It is to add this code between the below into `_validateShellPaths()`.

```ts
if (current! === '') {
    return this._validateShellPaths(label, potentialPaths);
}
```

https://github.com/Microsoft/vscode/blob/3a12b7ac2efd2f1f01a646ef5272313ad50bf618/src/vs/workbench/contrib/terminal/common/terminalService.ts#L428-L429

**Comment by skprabhanjan** [comment]
@roottool , you want to send a PR for this or can I handle this ?

**Comment by roottool** [comment]
PR for this issue is created by @NizamLZ.
I think that I entrust him.

**Comment by skprabhanjan** [comment]
@roottool , @NizamLZ sent the PR after the comment and while I was waiting for your confirmation and maybe @Tyriar to suggest the best approach.

**Comment by roottool** [comment]
@skprabhanjan, I wrote it here because I was afraid that my suggestion is wrong.
My answer to your question is "Of course! You can handle this.".

**Comment by NizamLZ** [comment]
@skprabhanjan, I just found the first 'good first issue' and submitted a PR. As it was too small, I won't mind even it gets rejected or be replaced by your PR. 

Cheers.

**Comment by skprabhanjan** [comment]
@NizamLZ , There is nothing wrong in that but it is good to let others know that you are working on the issue. 
I will leave this PR to you and close my PR :)
@roottool , i guess your approach is good but i will leave @Tyriar  to take the final decision :)
