### ISSUE TITLE
Can't rename variables

### ISSUE THREAD

**Issue by Gabriel641942** [Microsoft/vscode#72606]
Issue Type: <b>Bug</b>

When I try to rename a variable, a function or something in python, it just doesn't. No errors, no popups, nothing. Just nothing. I searched a lot for something like this and could not find this problem anywhere else.
I don't know if it's an issue with the Microsoft Python extension or if there is some conflict with another extension or a config. Please help me.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.91GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
lua-debug|act|0.9.4
project-manager|ale|10.5.1
shaderlabvscodefree|aml|1.1.3
uas|aml|1.0.6
code-gnu-global|aus|0.2.2
vscode-django|bat|0.19.0
vscode-icontheme-nomo-dark|be5|1.3.6
love|bsc|0.3.6
glsl-canvas|cir|0.2.6
supersharp|cra|0.1.4
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
python-preview|don|0.0.4
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
darkpixel-theme|erg|4.5.0
vscode-nupkg|eri|0.0.8
comment-anchors|Exo|1.6.1
git-project-manager|fel|1.7.1
vscode-solution-explorer|fer|0.3.1
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.1.32
live-html-previewer|hdg|0.3.0
csharpextensions|jch|1.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
vscodeilviewer|jos|0.0.1
docomment|k--|0.1.6
theme-karyfoundation-themes|kar|18.2.1
hex-fmt|ker|1.0.0
Lua|key|0.0.9
unity-code-snippets|kle|1.3.0
node-module-intellisense|lei|1.5.0
csharpfixformat|Leo|0.0.81
MagicPython|mag|1.1.0
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
code-beautifier|mic|2.2.1
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
mssql|ms-|1.5.0
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.11.3
vscode-json-editor|nic|0.2.3
pixelbyte-love2d|pix|0.1.19
love2dsnippets|pix|2.0.0
material-icon-theme|PKi|3.7.0
vscode-sort-json|ric|1.13.0
LiveServer|rit|5.6.1
aspnet-helper|sch|0.6.4
code-settings-sync|Sha|3.2.9
markdown-preview-enhanced|shd|0.3.13
shader|sle|1.1.4
vscode-3dviewer|sle|0.1.0
vscode-csstree|sme|0.7.0
ayu|tea|0.18.0
python|tht|0.2.3
unity-tools|Tob|1.1.0
vscode-lua|tri|0.12.4
vscode-w3cvalidation|Umo|2.3.2
unity-debug|Uni|2.7.2
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.5.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.2.0
html-css-class-completion|Zig|1.18.0

(9 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please start by filing this against the python extension
