### ISSUE TITLE
Admin mode

### ISSUE THREAD

**Issue by kvart714** [Microsoft/vscode#72610]
Please add a marker indicating that VS Code is running in administrator mode as in Visual Studio
![image](https://user-images.githubusercontent.com/17424528/56429631-4ca14a80-62cc-11e9-84bb-ed354679f148.png)

**Comment by WSLUser** [comment]
![image](https://user-images.githubusercontent.com/33032910/56434429-1a8bea80-62c4-11e9-8aa5-95db792270b0.png)

**Comment by kvart714** [comment]
Yes thank you
I was deceived by the fact that if you have already opened an instance of VS Code  from a non-administrator, then the following instances will also be in user mode (even if you try to open them as the admin)
