### ISSUE TITLE
Integrated Terminal: Blue highlight on everything

### ISSUE THREAD

**Issue by harshavamsi** [Microsoft/vscode#72612]
Issue Type: <b>Bug</b>

Hello,

I'm currently using Windows Subsystem for linux on a windows machine and have ZSH and Oh-My-Zsh installed. I have bashrc pointing to zsh. This setup on the hyper terminal works fine and I have no issues with the colors, but in VScode there seems to be an issue. 

Running other terminals like gitbash on VScode seems to work fine, the only issue is when I run WSL. Any help would be appreciated.

On Hyper - 
![1](https://user-images.githubusercontent.com/10369642/56431492-7f0c7100-62e7-11e9-8975-79c720275318.JPG)

On VScode -
![2](https://user-images.githubusercontent.com/10369642/56431491-7f0c7100-62e7-11e9-9482-aa37e7b315c6.JPG)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.15
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.6.2
prettier-vscode|esb|1.8.1
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
python|ms-|2019.3.6558
Go|ms-|0.9.2
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.7.0
vscode-yaml|red|0.4.0
quokka-vscode|Wal|1.0.209
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
