### ISSUE TITLE
Stop (custom?) tree views from changing the scroll position on updates

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#72617]
Issue Type: <b>Bug</b>

Currently whenever a tree view (maybe only a custom views) are updated they scroll to the selected row. While this is certainly reasonable, it drives me nuts with longer views (e.g. GitLens with many repositories). For example, if I am focused in the GitLens Repositories view with many repositories, and I kick off a fetch/pull/switch branches (i.e. something that will cause an update), and then continue scrolling to the next repo, once the update happens, the view will jump back to where the last selected item was. This makes it difficult to use the view to run multiple operations at once, because it will keep jumping around.

I really wish there was a way (by default or a setting) to stop the view from scrolling to the selected item and instead try to maintain the current scroll position.

/cc @sandy081 

VS Code version: Code - Insiders 1.34.0-insider (7d39e805fb66a6eac22f19af8bb90f48da863fd5, 2019-04-19T05:19:16.037Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
@joaomoreno Is it possible to avoid revealing the selected element on refresh/update?
