### ISSUE TITLE
Some GIT commands do not show password prompt

### ISSUE THREAD

**Issue by oxirt** [microsoft/vscode#72613]
### Preconditions

* I'm working with a _password protected Git repo_ in VS Code
* I open _command pallet_ (F1) and execute a Git command

Now most commands like `pull`, `push`, etc. _correctly asks for a password_ by showing a UI password prompt.

### Issue

However, certain commands like `fetch`, etc. **do not ask for a password** by showing a UI password prompt and fails with error `Git: Missing or invalid credentials.`

**Comment by oxirt** [comment]
I see [File:extensions/git/src/askpass-main.ts Line:31](https://github.com/Microsoft/vscode/blob/7d39e805fb66a6eac22f19af8bb90f48da863fd5/extensions/git/src/askpass-main.ts#L31) _explicitly skips_ the `fetch` command. Any particular reason for this?

**Comment by joaomoreno** [comment]
We skip fetch since it's done automatically behind the scenes, most of the time. We should probably change the check to make sure it is only skipped if the fetch is automatic (vs manually).

**Comment by periscuelo** [comment]
I had the same problem. Cannot type my prompt password anymore. Have any workaround without set a credentials? Thanks.
