### ISSUE TITLE
Can not connect to extensions market place

### ISSUE THREAD

**Issue by samFredLumley** [Microsoft/vscode#72618]
Cannot access the market place via web https://marketplace.visualstudio.com/VSCode or via VSCode. May be a duplicate of previous issues, but they're all closed. 

- VSCode Version: 1.33.1
- OS Version: on both Mac and Linux

**Comment by iSimar** [comment]
Same, website not working either: https://marketplace.visualstudio.com/

**Comment by samFredLumley** [comment]
Back online again for me
