### ISSUE TITLE
Import proxy setting from Chromium

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode#72619]
My customer is in the company which has network policies. He has to set up proxy setting in VS Code to list Azure resources. Quote from customer:
I guess it uses Chromium settings for proxy but my basic wish as a user is following:
If I am able to login to Azure via my browser then VS Code should be able to use the system settings and be able to login, too. That’s a pain for many tools out there and it is always a problem when working on big companies with many network policies.

So probably we can import proxy settings from Chromium.

**Comment by chrmarti** [comment]
We have been working on using the same OS settings as Chromium does: https://github.com/Microsoft/vscode/issues/60773

What particular proxy setup do they have?
