### ISSUE TITLE
Ctrl + C doesn't end running command, Kill Terminal "trashcan" crashes VSCode with some PowerShell commands

### ISSUE THREAD

**Issue by Inthedriversseat** [microsoft/vscode#72629]
Issue Type: <b>Bug</b>

Ctrl + C not working:
`Ping COMPUTERNAME -n 15`
Before command completes, press Ctrl + C
-nothing happens

Kill Terminal "Trashcan" button crashing VSCode:
Run below script or another script that takes a while to run:
```
$Users = Get-ADUser -Filter *

for ($i = 0; $i -lt $Users.Count; $i++) {
    Write-Host $Users[$i].name
}
```
Press Kill Terminal button
VSCode freezes then brings up window asking to reload.
![image](https://user-images.githubusercontent.com/42391316/56448026-da773880-62c0-11e9-8f20-60809206c210.png)

VS Code version: Code - Insiders 1.34.0-insider (6d5feae57959287fb116467f4eb6c7079571b466, 2019-04-17T09:25:49.535Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vsc-material-theme|Equ|2.8.2
gc-excelviewer|Gra|2.1.32
powershell|ms-|1.12.1
code-settings-sync|Sha|3.2.9

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/Microsoft/node-pty/issues/286

**Comment by Tyriar** [comment]
Fix incoming in May release, props to @DHowett-MSFT for helping with the fix
