### ISSUE TITLE
Create a cross-platform terminal emulator

### ISSUE THREAD

**Issue by chriskuech** [Microsoft/vscode#72623]
There are a variety of open-source projects for creating cross-platform terminal emulators but they all have various pitfalls.  The VS Code terminal is already more feature-rich than the native terminals on macOS and Windows, and in your past release notes, it seems that the VS Code team already works with the Windows Console team to make improvements between the two systems.  It would be great if we could just use the VS Code terminal as a standalone Terminal emulator across all platforms that VS Code supports.

**Comment by Tyriar** [comment]
❤️ be sure to 👍 https://github.com/Microsoft/vscode/issues/34442
