### ISSUE TITLE
Unwanted Line Breaks When Copy-Pasting

### ISSUE THREAD

**Issue by mwdavids** [Microsoft/vscode#72620]
Issue Type: <b>Bug</b>

VS Code inserts line breaks at random places when I paste code from anywhere else, even another file open in vs code. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0
r|Mik|0.0.6
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
azurecli|ms-|0.4.4
sublime-keybindings|ms-|4.0.0
team|ms-|1.149.2
vscode-docker|Pet|0.6.1
vscode-yaml|red|0.4.0
elastic|ria|0.13.3

</details>

**Comment by octref** [comment]
Please give a repro case.
