### ISSUE TITLE
User-defined Markdown code segment invalidation

### ISSUE THREAD

**Issue by ShengdongYan** [Microsoft/vscode#72625]
Issue Type: <b>Bug</b>

我在用户自定义选项中，给markdown的json文件添加了相关代码段，但是无法再 .md文件中使用， 为了防止意外，我又在java的JSON文件中复制了一份，发现Java文件里的可以起作用，可是md文件的就是识别不到代码段提示，重新安装了一遍也没用。

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
html-class-suggestions|And|1.0.7
vscode-standard-format|che|0.0.12
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
php-intellisense|fel|2.3.10
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
debugger-for-chrome|msj|4.11.3
view-in-browser|qin|0.0.5
java|red|0.43.0
markdown-preview-enhanced|shd|0.3.13
html-css-class-completion|Zig|1.18.0

</details>

**Comment by mjbvz** [comment]
> In the User customization option, I added the relevant code snippet to the markdown's JSON file, but I could no longer use it in the. md file, and to prevent accidents, I copied a copy of the Java file and found that the Java file could work, But the MD file is not recognized in the code snippet prompt, reinstalled again is useless.

**Comment by mjbvz** [comment]
How are you trying to trigger the snippets? Can you also please share the snippet file itself

**Comment by ShengdongYan** [comment]
Yes ,you get me, I am talking about the snippets, I can use the snippets through F1, but they don't appear when I type them.
<img width="509" alt="屏幕快照 2019-04-20 下午4 23 03" src="https://user-images.githubusercontent.com/45132673/56459234-a5361d80-6388-11e9-80f5-572d0efc05f3.png">
It's the markdown.json  file, I tried to add the same thing in java.json， it can work in java file, so it must no the content syntax fault， can you tell me how to deal with it?

**Comment by mjbvz** [comment]
Markdown disables suggestions as you type by default. Can you trigger snippets manually using ctrl+space?

Also, set 

```json
  "[markdown]": {
    "editor.quickSuggestions": true
  }
```

to enable quick suggestions in markdown

**Comment by mjbvz** [comment]
Closing as likely fixed by setting `editor.quickSuggestions`
