### ISSUE TITLE
Dangling input elements after renaming top level file element in explorer view in single folder workspace

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#72626]
Steps to Reproduce:

1. Invoke rename on a top level file element in explorer view in single folder workspace
2. Check in developer tools that the div `monaco-tl-contents` for that file row contains multiple invisible children elements which are input element containers

![Peek 2019-04-19 16-32](https://user-images.githubusercontent.com/25115070/56445509-3c38a200-62c3-11e9-93fe-974fdd5e478d.gif)

**Comment by isidorn** [comment]
I can not reproduce this issue on my machine.
How do you end the rename, with Esc, Enter or some other way?
Are you doing anything else that is special?

**Comment by jeanp413** [comment]
@isidorn I just press `f2` `esc` continuously. I can reproduce this easily on linux(ubuntu) and windows. The setup it's just a folder with a single file and I drag and drop the folder on vscode.

**Comment by isidorn** [comment]
Yes I can reproduce now.

**Comment by isidorn** [comment]
This might happen again on tomorrow's vscode insiders. Thus unlocking converstaion so we can open this issue if needed.

**Comment by jeanp413** [comment]
You are right I can repro this again.
