### ISSUE TITLE
Heavy CPU and memory usage

### ISSUE THREAD

**Issue by rtippabhotla** [Microsoft/vscode#72624]
Recently upgraded to v1.33.1 and after the app for few mins, entire machine is becoming very slow to a point I am not able to use anymore without closing the process. VSCode process taking 2GB+ memory and 50%+ CPU. Here is process explorer snapshot. Please let me know if there is a workaround for this issue or if I should uninstall this and install a previous version.

![image](https://user-images.githubusercontent.com/1743655/56444159-721e5c00-62ac-11e9-9727-6738086f994f.png)

**Comment by rtippabhotla** [comment]
As a workaround I tried reverting back to 1.32.3 and it looks good now.

**Comment by mjbvz** [comment]
Are you using a workspace that has `@types/styled-components` installed in it. If so, make sure it on the latest version

**Comment by rtippabhotla** [comment]
no I don't have  styled-components installed.

**Comment by mjbvz** [comment]
Can you share your project?

You can also try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
