### ISSUE TITLE
F5 debug no longer launches Debug window

### ISSUE THREAD

**Issue by psmocko** [Microsoft/vscode#72622]
Issue Type: <b>Bug</b>

When hitting F5 inside of VS code. The browser is no longer launching for the debug session and therefore cannot debug my angular app. I have noticed this since last update (I believe it was last or earlier this week).

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (3.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vscode-solution-explorer|fer|0.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
Angular-BeastCode|Mik|8.0.2
csharp|ms-|1.19.0
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vscode-icons|vsc|8.5.0
gitblame|wad|2.7.0

</details>

**Comment by weinand** [comment]
How does your launch configuration look like?

**Comment by psmocko** [comment]
Below is the configuration that worked before latest update.

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "ng serve",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080/",
            "webRoot": "${workspaceFolder}"
          },
          {
            "name": "ng test",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:9876/debug.html",
            "webRoot": "${workspaceFolder}"
          },
          {
            "name": "ng e2e",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/protractor/bin/protractor",
            "protocol": "inspector",
            "args": ["${workspaceFolder}/e2e/protractor.conf.js"]
          }        
    ]
}

**Comment by roblourens** [comment]
Which one isn't working? Can you explain exactly what you see?

**Comment by psmocko** [comment]
Sorry, after it is working now after a restart of my computer. I guess VSCode was confused.
