### ISSUE TITLE
Rename File - File Name Not Updating After Being Changed

### ISSUE THREAD

**Issue by REPNOT** [Microsoft/vscode#72637]
Issue Type: <b>Bug</b>

Steps to Reproduce - Option 1:

Right click on the file that you want to change in the file explorer blade menu, select the rename option from the mouse display menu and modify the name.  Once the name has been updated, press enter.

Pressing enter typically updates the name automatically.

Steps to Reproduce - Option 2:

Make sure the desired file is selected in the file explorer blade menu, then press F2 and modify the name.  Once the name has been updated, press enter.

Pressing enter typically updates the name automatically.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.82GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0
docs-article-templates|doc|0.2.2
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.4
docs-preview|doc|0.3.17
docs-yaml|doc|0.2.1
vscode-html-css|ecm|0.2.0
code-runner|for|0.9.8
azure-pipelines|ms-|1.147.2
vscode-azureappservice|ms-|0.13.1
vscode-azurefunctions|ms-|0.16.0
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.1
mssql|ms-|1.5.0
vscode-postgresql|ms-|0.2.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
vscode-ai|ms-|0.4.5
azure-account|ms-|0.8.2
azurecli|ms-|0.4.4
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
Go|ms-|0.9.2
js-atom-grammar|ms-|0.1.14
powershell|ms-|1.12.1
typescript-javascript-grammar|ms-|0.0.50
vscode-node-azure-pack|ms-|0.0.6
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.5.1
azure-hdinsight|msh|1.1.1
vscode-docker|Pet|0.6.1
vscode-yaml|red|0.4.0
rust|rus|0.6.1
salesforcedx-vscode-apex|sal|45.10.0
salesforcedx-vscode-core|sal|45.10.0
code-spell-checker|str|1.7.0
usql-vscode-ext|usq|0.2.15
azure-iot-edge|vsc|1.11.1
azure-iot-toolkit|vsc|2.5.1
vscode-arduino|vsc|0.2.25
vscode-maven|vsc|0.16.1

(16 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce this with the latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by REPNOT** [comment]
Isidor,

Thank you for taking the time to contact me.  I download the insiders version of VS Code and everything is running much better now.

I think we're all set right.  Thanks again for getting back to me.

Best Regards,



Derek Evans
(231) 563-3413
deevans01@hotmail.com
________________________________

**Comment by isidorn** [comment]
Thanks. Clsoing this then
