### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by freebird96** [Microsoft/vscode#72635]
Issue Type: <b>Bug</b>

The intellisense which made coding in vs code easier doesnt seems to be working all of sudden in my laptop. Please address this issue as soon as possible.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (7.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.2.1
LiveServer|rit|5.6.1

</details>

**Comment by scottmeschke** [comment]
Downgrading to 1.30.1 fixed it for me just an FYI while it get's sorted out.

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate
