### ISSUE TITLE
Opening image file from source control is broken

### ISSUE THREAD

**Issue by rasmusgo** [microsoft/vscode#72640]
Issue Type: <b>Bug</b>

### Steps to reproduce

1. Create a png file in a folder with git source control.
2. Click the "Open file" icon next to the file name in source control view.

### Actual results
A dialog appears "Git: cannot open ... Detail: File seems to be binary and cannot be opened as text"

### Expected results
The file is opened as if it was opened from the explorer view.

VS Code version: Code - Insiders 1.34.0-insider (750680d2f7ae563529501f8ec419d83ccf8ec325, 2019-04-19T19:59:19.092Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_770236|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ALDamico** [comment]
Is anyone working on this? I'd like to contribute to this bugfix.

**Comment by darshkpatel** [comment]
@rasmusgo Seems to work for me for formats like jpg, jpeg. It gave the error message for .tiff format although.
