### ISSUE TITLE
Expand javascript.format options in settings

### ISSUE THREAD

**Issue by nwayve** [Microsoft/vscode#7264]
- VSCode Version: 1.2
- OS Version: Windows 10.0.10586

The immediate issue is spacing around anonymous generator functions but there may be other formatting options to consider with later version of ecmascript standards.

Steps to Reproduce:

Say I have:
```javascript
var foo = function () { };
var bar = function* () {};
```
and I want them both to be:
```javascript
var foo = function() { };
var bar = function*() {};
```
I would want to add this setting to my user and/or workspace settings:
```json
"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false
```
With this set, if I trigger vscode autoformatting, it only results in:
```javascript
var foo = function() { };
var bar = function* () {};
```
*Note: The anonymous function formatted correctly but the anonymous generator function remains untouched.

I'm not sure what the desired solution here is.
Should anonymous generator functions be treated as regular anonymous functions? (my gut says no).
Should another `javascript.format` option be added? (preferred)
```json
"javascript.format.insertSpaceAfterFunctionKeywordAndStarForAnonymousGeneratorFunctions": false,
"javascript.format.insertSpaceAfterGeneratorFunctionStarForAnonymousGeneratorFunctions": false
```
```javascript
//  true,  true: function * ()
//  true, false: function *()
// false,  true: function* ()
// false, false: function*()
```

Another thing to consider is that in vscode v1.2 release, there is now the option to "auto-fix" eslint errors.  Could we maybe add to the auto-formatting the option to also trigger linting fixes?
```json
"javascript.format.eslint": false, true, "beforeAutoFormat", "afterAutoFormat"
```
In which case it would autoFormat, lint, lint then autoFormat, or autoFormat then lint.

**Comment by dbaeumer** [comment]
Moving to TS team since the formatter comes through the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9001
