### ISSUE TITLE
CTRL+p stopped working

### ISSUE THREAD

**Issue by jgwill** [Microsoft/vscode#72647]
Issue Type: <b>Bug</b>

Since last VSCode upgrade, CTRL+p stops working out of nowhere.
It says: CTRL+p,CTRL+p is not ...

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.18.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2269)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|7.65GB (1.44GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
google-translate-ext|ben|1.3.1
vscode-store|cg-|0.0.1
handlebars-preview|cha|1.1.0
regex|chr|0.2.0
vscode-svgviewer|css|2.0.0
angular-schematics|cyr|1.23.0
angular2-snippets|dan|1.0.21
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-protractor-snippets|dee|1.0.5
xml|Dot|2.4.0
gitlens|eam|9.6.2
vscode-mysql|for|0.4.0
shell-format|fox|4.0.5
vscode-google-translate|fun|1.1.5
code-sync|gol|2.5.3
vscode-back-forward-button|gri|0.1.2
gix-vscode-xstore|gui|0.0.5
gixdeko-comments|gui|1.0.94
angular2-switcher|inf|0.2.0
svg|joc|0.1.4
Angular2|joh|7.0.1
firebase-explorer|jsa|0.3.3
vscode-circleci|jva|0.5.0
vscode-gist|ken|3.0.3
protractor-test-runner|luc|1.1.0
Angular-BeastCode|Mik|8.0.2
debugger-for-chrome|msj|4.11.3
ngx-translate-quickcreate|nex|1.0.1
snippet-creator|nik|0.0.5
promise-snippets|pro|0.2.3
quicktype|qui|12.0.46
karma-problem-matcher|rct|1.0.1
vscode-yaml|red|0.4.0
comment-ts|sal|0.9.11
taskrunnercode|San|0.3.0
angular-follow-selector|san|1.2.0
vscode-scss-formatter|sib|1.4.1
open-in-browser|tec|2.0.0
vsfire|tob|1.4.1
jasmine-ng-test-snippets|tre|0.0.3
lorem-ipsum|Tyr|1.2.0
JasmineSnippets|xab|1.0.1
vscode-surround|yat|1.0.2

</details>

**Comment by octref** [comment]
Try to disable all extension. Does it work?

**Comment by roblourens** [comment]
> It says: CTRL+p,CTRL+p is not ...

What do you mean, can you explain more?

**Comment by jgwill** [comment]
Is it possible that one extension is modifying the way shortcut are
interpreted? (Ex. It became a combination of 2 sequences like in
traditional VS (ex. Ctrl+k,ctrl+d to format))

 In my next session, I will try to disable all extensionS (as suggested in
another reply)

**Comment by gforceg** [comment]
@jgwill I found a plugin that was doing this just now "Handlebars Preview with helper functions support"
