### ISSUE TITLE
Annoying "Not enough space to split terminal" message

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#72649]
- VSCode Version: 1.32.3
- OS Version: macos 10.14

Steps to Reproduce:

1. Make VSC's window narrow enough
2. Try to split a terminal
3. The "not enough space to split terminal" message pops up and the terminal doesn't get split.

IMHO this is a useless annoyance, since I can increase the window's width temporarily just for splitting the terminal and when resizing it back it just works. So I don't understand what the purpose of this message is, let me decide if there's enough space or not.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It's there for stability reasons; to try and prevent issues that could arise out of terminals being too narrow since we don't have a proper overflow solution for split terminals.
