### ISSUE TITLE
Show the specific html tag where the cursor on

### ISSUE THREAD

**Issue by laughinggg** [Microsoft/vscode#72648]
Currently, I am working with front-end development where I am a newbie. I found out that VSC does not have any extension show which the tag on the cursor, unlike the IntelliJ IDE. 
The image below is example from Phpstorm.

![example](https://user-images.githubusercontent.com/31165945/56459366-8cdff600-63bc-11e9-8dc3-09a308ad8b48.PNG)

**Comment by aeschli** [comment]
e have something similar: You need to turn on the breadcrumbs: 
breadcrumbs.enabled: true
![breadcumbs](https://user-images.githubusercontent.com/6461412/56571458-49080f00-65bd-11e9-984a-f4e78683c863.png)
