### ISSUE TITLE
Don't remove uncommitted git message when closing application

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#72654]
If you type something into the git commit message box and then close vscode and reopen it, whatever you entered is gone. It should be saved there allowing you to continue editing it later.

_This issue was previously closed with no explanation other than a link to an issue that is unrelated. That person either didn't understand this issue or didn't give the actual reason it was closed._

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/41232
