### ISSUE TITLE
Shell paths should be validated before launched to prevent ambiguous errors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#72650]
We should validate the shell path exists and cache the result per window. Need to make sure it also works with symlinks.

![image](https://user-images.githubusercontent.com/2193314/56459856-9af72d80-634e-11e9-88f3-448d66f7b00d.png)

There is this code that is meant to do this sort of thing right now but I think it's Windows only and also still just says "exit code 2":

https://github.com/Microsoft/vscode/blob/50c9a782ad2cf3b1b662966455187f8a9ec41bac/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L71-L77

**Comment by skprabhanjan** [comment]
@Tyriar , Can i try this ?
If yes then can you please give me a bit more information on implementation side ?

**Comment by Tyriar** [comment]
@skprabhanjan sure! We will need to check the FS to make sure the path exists, this likely has to happen in this file: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/node/terminalProcess.ts

The easiest approach might be to use a negative exit code and then handle that specially here:

https://github.com/Microsoft/vscode/blob/3081cf911172aeeb83c6246470c0abe3beae4542/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L975-L977

It might get a little tricky doing this in `TerminalProcess.ctor` as everything is sync right now but a FS check would be async.

**Comment by Tyriar** [comment]
I had to undo this because paths like "cmd.exe" don't work now, we need to check against $PATH.

**Comment by skprabhanjan** [comment]
@Tyriar , Okay I will fix this issue.
I checked for any methods to check if executable is on $PATH but could not find any standard approach in node.
Can you please help with the your suggestion on how to go ahead with this ?
Thanks :)

**Comment by calshius** [comment]
https://www.npmjs.com/package/hasbin

Here's a node package that detects for binaries on your path:

```
var hasbin = require('hasbin');
 
// Check if a binary exists
hasbin('node', function (result) {
    // result === true
});
```

**Comment by skprabhanjan** [comment]
Hey @calshius , Thanks for that and even I came across the same thing [here](https://stackoverflow.com/questions/26090995/detect-if-executable-exists-on-system-path-with-node)
But it is a module that is not used else where in the codeline , So just wanted to check with @Tyriar the preferred approach. ( Because I assume they must be doing this already somewhere else in the code)

**Comment by Tyriar** [comment]
We'd prefer not to use a module like this. We have this function to do this on Windows at least, not sure if we have one for non-Windows:

https://github.com/microsoft/vscode/blob/42c957d973dc9993673a883590bbde7a034d5269/src/vs/base/node/processes.ts#L406-L407

**Comment by Tyriar** [comment]
Verifier make sure the follow scenarios work:

- Using an existing absolute path for shell (eg. "/bin/bash")
- Using a non-existing absolute path for shell (eg. "/idonotexist")
- Using an absolute directory for shell (should get a special directory only error) (eg. "/bin")
- Using a non-existing path for shell (eg. "idonotexist")
- Using a symlink off the path for shell (eg. "somesymlink")
- Using a file off the path (eg. "bash")
