### ISSUE TITLE
this app is very hanging my computer

### ISSUE THREAD

**Issue by develliars67** [Microsoft/vscode#72659]
Issue Type: <b>Bug</b>

it hands upto 1min then it responses when i open this app.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.26.0
sublime-keybindings|ms-|4.0.0
indenticator|Sir|0.6.0

</details>

**Comment by octref** [comment]
You might want to disable bracket-pair-colorizer which has many perf issue reports: https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues

Otherwise follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to report a new issue.
