### ISSUE TITLE
vscode doesn't respect terminal selection related to "The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 1)"

### ISSUE THREAD

**Issue by raegnar** [Microsoft/vscode#72655]
Issue Type: <b>Bug</b>

Trying to run a cmake project with "CMake: Execute the current target without a debugger" and I get the "The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 1)" error. 
I've tried reinstalling vscode, nuking but the settings, and extensions. 
I've tried changing "terminal.external.windowsExec" and "terminal.integrated.shell.windows" to all the options.  The integrated shell will change but the execution value is absolutely ignored for execution, the error message is always reported 'C:\WINDOWS\System32\cmd.exe' instead of the configured terminal.

"CMake: debug target" works fine.  I've checked out the other related bug reports, which don't seem to solve my issue, but also seem to indicate they are able to change the execution terminal.

https://github.com/Microsoft/vscode/issues/45693
https://github.com/Microsoft/vscode/issues/64449
https://github.com/Microsoft/vscode/issues/20100
https://github.com/Microsoft/vscode/issues/20858
https://github.com/Microsoft/vscode/issues/66867

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.81GB (18.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.22.1
cmake-tools|vec|1.1.3

</details>

**Comment by Tyriar** [comment]
You might want to report against `cmake-tools`, whatever it's running in the terminal is exiting with an exit code of 1. You can find out what it's launching which might be useful to them by enabling debug logging move (F1, "log level", "debug") then launching a terminal and viewing the devtools console (Help > Toggle Developer Tools, console). You should see something like this:

![image](https://user-images.githubusercontent.com/2193314/57046524-b05d3900-6c25-11e9-80be-ee655e82dca7.png)
