### ISSUE TITLE
Screen flickering on Ubuntu 16.04

### ISSUE THREAD

**Issue by Louis-Ian** [Microsoft/vscode#72653]
Issue Type: <b>Bug</b>

I noticed that screen flickering when I move the mouse around even if I have just powered up the system and I also noticed that the flickering intensifies when I move the mouse between the sidebar and the editing area. I've attached a ~gif~ a zip with a screen recording.
[screen-flickering vscode-2019-04-20_14.22.48.mkv.zip](https://github.com/Microsoft/vscode/files/3100446/screen-flickering.vscode-2019-04-20_14.22.48.mkv.zip)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1999)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|3.64GB (0.10GB free)|
|Process Argv|--unity-launch|

|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by octref** [comment]
Does `--disable-gpu` help?

**Comment by Louis-Ian** [comment]
Yes, it does. Do I only have to run $code --disable-gpu once and the change is permanent?

**Comment by Louis-Ian** [comment]
I searched it on the internet and found the file that I have to edit to make it permanent so I'm closing the issue, thank you.
