### ISSUE TITLE
Right npm version not picked up by the integrated terminal

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#72651]
Issue Type: <b>Bug</b>

- I am using `nvm` to manage different node versions on my Mac.
- Recently changed the default node version to be 10.15.3
- Since the old version of `npm` (5.5.1) was not compatible with this version of node, I installed the latest version of npm using `nvm install-latest-npm`
- Now, my external terminal is using the latest node and npm versions
- The integrated terminal in VS Code is using the latest node, but not the latest npm version

External terminal:

<img width="383" alt="Screen Shot 2019-04-20 at 9 34 23 AM" src="https://user-images.githubusercontent.com/16890566/56459915-89faec00-634f-11e9-93b7-5b1c5211d1ab.png">

Integrated terminal:
<img width="727" alt="Screen Shot 2019-04-20 at 9 34 39 AM" src="https://user-images.githubusercontent.com/16890566/56459917-8e270980-634f-11e9-87e8-13388182db0f.png">

VS Code version: Code - Insiders 1.34.0-insider (6d5feae57959287fb116467f4eb6c7079571b466, 2019-04-17T09:19:05.456Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (5.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.3.2
Go|ms-|0.9.3-beta.8
vsliveshare|ms-|1.0.45
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.1
vscode-versionlens|pfl|0.22.0
show-offset|ram|0.0.4

</details>

**Comment by Tyriar** [comment]
This is probably because your launch scripts are running multiple times, see https://github.com/Microsoft/vscode/issues/70248

You might also want to purge a previously installed version of node/npm if you're using nvm now, see https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched

To help figure out what's going on run:

```
echo $PATH
which node
which npm
```

Let me know if you're still having problems 🙂
