### ISSUE TITLE
Unable to add watch variable on VSCode

### ISSUE THREAD

**Issue by jdfa14** [Microsoft/vscode#72658]
Issue Type: <b>Bug</b>

1.- Reopened VSCode with DART & Flutter application loaded
2.- Debuging an operation where I added two variables to watch. One of them is a Date with the format "yyyy-MM-dd hh:mm:ss.nnnnnnn"  and the another one is a DateTime.parse(*dateString*), the parsing did well on the watch section but on continuing an exception of Invalid Format of DateTime.parse throws
3.- Second time I start the debugging (inmediatly) on the same section I was no longer able to modify, delete nor add a new variable on the watch window

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.80GB (11.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.25.1
flutter|Dar|2.25.1

</details>

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please share the repository for which you see this and the exact steps to reproduce this?
