### ISSUE TITLE
Can't open large files

### ISSUE THREAD

**Issue by mfaheemakhtar** [microsoft/vscode#72666]
Issue Type: <b>Bug</b>

I've a 3.7 GB JSON file. When I open the file using VS Code, I see a prompt to start VS Code with more memory. I do, but it keeps prompting me instead of opening the file.

I tried the Insiders build, it does starts loading the file but later, almost at the end of the file. The RAM drops and I gets an option to Keep waiting or reopen. 

It is super annoying that I can't open a file now. I've opened some files of the same size before using VS Code. But they don't work sometimes if I save changes.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2868)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.44GB (3.39GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.8.1

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Does it work when you run `code-insiders --max-memory 8000` or any large number from the command line ?

**Comment by mfaheemakhtar** [comment]
@rebornix, This is a very old issue.

I had tried the `max-memory` but it did not work. I've just tried opening a 3.2 GB JSON file and it worked in the production/stable build. I don't have the insider build at the moment.
