### ISSUE TITLE
Unable to update on Windows: "file is being used", corrupts install

### ISSUE THREAD

**Issue by xobs** [Microsoft/vscode#72665]
Visual Studio Code keeps prompting me to update.  When I accept the update, it sits for a very long time before telling me that it can't access Code.exe.

According to Process Explorer, Code.exe is opened by `System` with PID 4.  Windows Defender is running with normal configuration, except the Firewall is disabled.

As per a suggestion here, I set `update.enableWindowsBackgroundUpdates` to `false`.  When it prompted me to update, I accepted.  Midway through, it said that it couldn't access Code.exe, and offered to ignore, retry, or abort.  I selected Abort.

Now when I try to open Visual Studio Code, it gives me an error:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'C:\Users\smcro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\main'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Users\smcro\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Object.<anonymous> (C:\Users\smcro\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\browser\init.js:189:8)
    at Object.<anonymous> (C:\Users\smcro\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\browser\init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

[OK]
```

Similar issues:

https://github.com/Microsoft/vscode/issues/47841

- VSCode Version: Unknown
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Set `"update.enableWindowsBackgroundUpdates": false` as described in https://github.com/Microsoft/vscode/issues/47841#issuecomment-433968487
2. Allow the update to run
3. When setup reports that code.exe is being used, click "Abort"

This issue is happening on two of my machines.  Both are Windows 10 1803, neither is joined to a domain, neither has any sort of security software installed except Windows Defender.

**Comment by xobs** [comment]
This occurs even on a fresh reboot.  I'm reluctant to disable WindowsBackgroundUpdates because the last time I did that it corrupted the install.

An alert is telling me to upload this file:
[vscode-inno-updater-1556632522.log](https://github.com/Microsoft/vscode/files/3131549/vscode-inno-updater-1556632522.log)

Is it possible to disable the "An update is available!" box?  It's popping up a lot now, and it's getting distracting.

**Comment by xobs** [comment]
@joaomoreno is it possible to at least disable the update notification? since it happens every time, updates are broken, and there hasn't been any progress towards a fix in six months.

**Comment by joaomoreno** [comment]
Have you tried keeping `update.enableWindowsBackgroundUpdates` to `false` and manually reinstalling VS Code?

**Comment by xobs** [comment]
Visual Studio Code is completely broken.  I tried updating it like you said, and ran into the same issue.  I clicked "Abort", and now when I try to run code I get this error:

```
nternal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'C:\Users\sean\AppData\Local\Programs\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
```

I've uninstalled it, and now when I reinstall it I get the following Windows error:

```
---------------------------
Error
---------------------------
C:\Users\sean\AppData\Local\Programs\Microsoft VS Code\Code.exe



An error occurred while trying to replace the existing file:

DeleteFile failed; code 32.

The process cannot access the file because it is being used by another process.



Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
---------------------------
Abort   Retry   Ignore   
---------------------------
```

I remembered that there is a separate "System" installer, and found "https://code.visualstudio.com/docs/?dv=win64".  This installer appears to actually work, and is what I've installed on both of my systems.

It seems like the "User" version is very broken, and shouldn't be used.  Furthermore, the error messages are very opaque.  It says that the file is in use, but the best I can figure out is that it's in use by "System (PID 4)", and I don't know why, or how to kill it.
