### ISSUE TITLE
Terminal not showing prompts

### ISSUE THREAD

**Issue by thedigitaldesign** [Microsoft/vscode#72664]
Issue
- Terminal prompt not displaying when docked to bottom
- Terminal window is scrolled down to the bottom when opened and docked to bottom

Versions and OS
- VSCode Version: 1.33.1 and Insider 1.34.0
- OS Version: Windows 10 v1809

Steps to Reproduce:
01. Open new terminal
02. [No prompt and window scrolled to bottom](https://imgur.com/DDIoNHc)
03. [Scroll up, no prompt](https://imgur.com/b9kOmsP)
04. Kill Terminal 
05. Open new terminal
06. Right click on the Terminal tab and select, Move Panel Right
07. Kill Terminal
08. Open new terminal
09. [Prompt working correctly](https://imgur.com/kysq8kR)
10. Right click on the Terminal tab and select, Move Panel to Bottom
11. Kill Terminal
12. Open new terminal, problem still persists

Does this issue occur when all extensions are disabled?: Yes

I tried uninstalling and re-installing VS Code. The problem still persisted.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
