### ISSUE TITLE
integrated terminal npm Error: This socket is closed

### ISSUE THREAD

**Issue by davidgabrichidze** [Microsoft/vscode#7267]
- VSCode Version: 1.2.0
- OS Version: Windows 10 Insider Preview, Build 14352

![image](https://cloud.githubusercontent.com/assets/12189125/15836978/5884b610-2c48-11e6-84e0-fa49acb37ee5.png)

Steps to Reproduce:

1. Ctrl + `
2. npm -v

**Comment by Codesleuth** [comment]
I'm experiencing the same issue.

* VSCode Version: 1.2.0
* OS Version: Windows 10 Insider Preview 14352
* NPM Version: 3.8.6

However, `npm ls` is able to print some results:

![image](https://cloud.githubusercontent.com/assets/5011956/15840338/14c7c0c2-2c41-11e6-8073-84e30bcdc384.png)

**Comment by Codesleuth** [comment]
Seems this is a duplicate of #7194, recommend close.

**Comment by davidgabrichidze** [comment]
dup of #7194
