### ISSUE TITLE
Block comments in TSDoc `@example` sections not (practically) usable

### ISSUE THREAD

**Issue by BendingBender** [Microsoft/vscode#72674]
Issue Type: <b>Feature Request</b>

Currently it's not (practically) possible to use block comments in `@example` sections in TSDoc comment blocks.

To use a block comment in an example section one has to escape the closing `*/` with a backslash. The problem is that this backslash is still rendered in the tooltip showing the example which is very ugly:

<img width="271" alt="docblock1" src="https://user-images.githubusercontent.com/4807083/56468717-b0885800-641f-11e9-8013-a29f8c5ffa99.png">
<img width="294" alt="docblock2" src="https://user-images.githubusercontent.com/4807083/56468768-58058a80-6420-11e9-8926-384c94568efd.png">

Ideally, I'd expect the backslash escape character not to appear in the rendered tooltip, neither in a plain example section nor if it's wrapped with ```` ``` ````.

Current workaround: I use line comments in example sections but this makes larger example outputs harder to read.

VS Code version: Code - Insiders 1.34.0-insider (750680d2f7ae563529501f8ec419d83ccf8ec325, 2019-04-19T19:59:19.092Z)
OS version: Darwin x64 18.5.0

**Comment by mjbvz** [comment]
This is not supported by syntax highlighters or by the jsdoc tool itself either:

![Screen Shot 2019-04-24 at 10 23 26 AM](https://user-images.githubusercontent.com/12821956/56679973-1886aa80-667b-11e9-842d-9f27d4e6a526.png)

**Comment by sindresorhus** [comment]
That's not a great argument. You can do better than jsdoc. Also, this limitation just discourages code examples in doc comments, which I guess is the opposite of what you want with VS Code.

**Comment by trusktr** [comment]
@sindresorhus @mjbvz Does VS Code use TSDoc? Seems that all tooling around TS should standardize on one thing, if it hasn't already.
