### ISSUE TITLE
vscode使用tab补全需要等待5秒左右才补全

### ISSUE THREAD

**Issue by suwei0708** [Microsoft/vscode#72678]
Issue Type: <b>Performance Issue</b>

html文件398.39kb，tab补全emmet结构提示正在加载，需要等待5秒左右才会出来，用sublime就很快，希望能够提高速度

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

**Comment by octref** [comment]
Duplicate of #71996.
