### ISSUE TITLE
Language features are unprecedentedly slow

### ISSUE THREAD

**Issue by jessepinho** [Microsoft/vscode#72686]
Issue Type: <b>Performance Issue</b>

1. Open a .tsx (TypeScript JSX) file.
2. Place the mouse over any variable in the file — including one defined higher up in the same file.
Expected behavior: it very quickly shows a tooltip with the typing of the variable.
Actual behavior: it shows the tooltip after 30-40 seconds.

I tested this with extensions disabled. It's not reliably reproducible, unfortunately. It's hard to say whether it happens immediately after startup or later – it seems to go back and forth. (Sorry, I know that's not super helpful.)

I turned on verbose TSServer logging and was watching the logs and noticed that it seemed that there was a long delay between when I typed, moused over, etc. something in vscode, and when the logs would output more — almost as though the communication between vscode and the TS Server is slow. Let me know if I can provide more information, and I'm happy to provide logs privately.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|16.00GB (4.71GB free)|
|Process Argv|--disable-extensions --usr-data-dir ./foo|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   115	 85023	code main
    0	    66	 85027	   gpu-process
    0	   311	 85029	   window (tsconfig.json — vusik-natural-thing)
    0	    82	 85032	     extensionHost
    0	   492	 85037	       electron_node tsserver.js 
    0	    49	 85050	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 85063	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=85032
    0	    49	 85033	     watcherService
    0	    49	 85167	     searchService
    0	    98	 85035	   shared-process
    0	    82	 85267	   window (Issue Reporter)
    0	     0	 85272	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (tsconfig.json — vusik-natural-thing)
|    Folder (vusik-natural-thing): 154 files
|      File types: js(84) json(18) png(16) ts(13) tsx(10) mp3(2) lock(1) md(1)
|                  gitignore(1) babelrc(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  webpack.config.js(1) settings.json(1);
```

</details>
Extensions disabled

**Comment by ChuckyHelse** [comment]
I confirm that I am experiencing this as well with the Microsoft C/C++ add-on. This may thus be independent from the language server itself and be more related to the related Visual Studio Code framework itself.

**Comment by mjbvz** [comment]
@ChuckyHelse File an issue against the C++ extension

@jessepinho Do you have `@types/styled-components` installed in your workspace under `node_modules`?

**Comment by jessepinho** [comment]
Yes, I do! Could that be at fault? (I also have the styled components
vscode extension installed, but I disabled it and still experience this
issue.)

**Comment by mjbvz** [comment]
Yes, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391

Please try upgrading the latest version of `@types/styled-components` and restarting VS Code to see if that fixes the performance issue

**Comment by jessepinho** [comment]
I believe this fixed it! Thanks, @mjbvz ! Ahhh wow, that was such a pain.

will close this for now and reopen if I experience the issue further.
