### ISSUE TITLE
Debug session: Need to stop twice

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#72685]
Version: 1.34.0-insider
Commit: 750680d2f7ae563529501f8ec419d83ccf8ec325
Date: 2019-04-19T19:59:19.092Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

![twice](https://user-images.githubusercontent.com/4033249/56473634-dcf1a380-6422-11e9-9a67-e32edf4eb42b.gif)

**Comment by octref** [comment]
This seems to happen only for sessions started from Viewlet, doesn't repro for auto attach.

**Comment by isidorn** [comment]
This is up to the debug adapter. First stop sends out a "disconnect" and it seems like the debug adapter does not shut down on disconnect.
Second stops manually shuts it down thus it works.
Thus forwarding to Andre and Rob

**Comment by weinand** [comment]
@octref first stop sends a SIGINT signal to the process being debugged. If this signal is not intercepted, it should terminate the process.

**Comment by octref** [comment]
I can no longer repro it. Not sure what happened.
