### ISSUE TITLE
Integrated Terminal does not support font ligatures

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#7268]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

First of all, having lots of fun with the integrated terminal, great addition!

I'm currently using FiraCode for my editor, with font ligatures enabled. I was able to configure the terminal to use the same font, but there's currently no option to enable ligatures for it.

Ideally we'd have `"terminal.integrated.fontLigatures"` just like we have `"editor.fontLigatures"`. Also would be nice if the terminal simply inherited the editor fonts by default (though having the option of specifying a custom font for it is nice).

Thanks in advance.

**Comment by Tyriar** [comment]
Closing in favor of #7541.
