### ISSUE TITLE
[electron_node tsserver.js] process go instant 100% CPU as soon as I make any change to any js file!

### ISSUE THREAD

**Issue by plat123456789** [microsoft/vscode#72687]
Issue Type: <b>Performance Issue</b>

[electron_node tsserver.js] process go instant 100% CPU as soon as I make any change to any js file!

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (6.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	   131	  2289	code main
    0	    82	  2290	   gpu-process
    0	   311	  2291	   window (utility.js — sync-chrono24)
    0	    98	  2297	     extensionHost
  100	   197	  2299	       electron_node tsserver.js 
    0	    66	  2313	         electron_node typingsInstaller.js typesMap.js 
    0	   147	  3120	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=2297
    0	    49	  2298	     watcherService
    0	    82	  2315	   shared-process
    1	    82	  2316	   window (Process Explorer)
    0	    66	  3251	   window (Issue Reporter)
    0	     0	  3255	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (utility.js — sync-chrono24)
|    Folder (sync-chrono24): 17 files
|      File types: js(6) json(4) html(4) DS_Store(2) sql(1)
|      Conf files: package.json(1);
```

</details>
Extensions: none

**Comment by plat123456789** [comment]
I already add follow to setting.json base on other issue, but it didn't help:
```json 
"files.useExperimentalFileWatcher": true,
  "files.exclude": {
    "**/.git**": true,
    "/.DS_Store": true,
  },
  "search.exclude": {
    "/node_modules": true
  },
  "files.watcherExclude": {
    "/.git**": true,
    "**/.git/objects/**": true,
    "/.DS_Store": true,
    "/node_modules": true,
    "**/node_modules/**": true,
    "**/tmp/**": true,
    "/.history": true,
    "**/.history/**": true,
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
```

**Comment by plat123456789** [comment]
I also upload my log file
Log file ID: 3972866624

**Comment by plat123456789** [comment]
my typescript version: Version 3.5.0-dev.20190420

**Comment by plat123456789** [comment]
this does reproduce in the latest VS Code insiders build with all extensions disabled

**Comment by plat123456789** [comment]
I also downgrade to 1..32.2 as a workaround

**Comment by plat123456789** [comment]
I still experience this issue on 1..32.2, I tried  ` "javascript.validate.enable": false` , and use eslint, and the problem finally solved

**Comment by mjbvz** [comment]
Can you please try collecting the TS Server log (which is also used for javascript):

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it (or open the tsserver log file itself if you are on insiders)

 If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by plat123456789** [comment]
@mjbvz I uploaded the log already?

**Comment by johmike** [comment]
Also running into the same issue suddenly, almost the same steps

**Comment by mjbvz** [comment]
Thanks. The logs do not show any long running requests, which is what we'd generally expect for high cpu usage.

When this happens, does intellisense still work? Does the cpu usage spike for a moment and then return to normal or does it stay high?

**Comment by mjbvz** [comment]
@plat123456789 Can you please test in the latest VS Code insiders build. If you still see this issue, I suspect that due to the high cpu usage plus lack of long running requests that you could be hitting https://github.com/microsoft/TypeScript/issues/31452,

Also, it would help if you could share a small example project so that we can try to reproduce this issue on our side

**Comment by plat123456789** [comment]
@mjbvz Thanks for the reply, I noticed that CPU usage reduced to average 10-50% after [build-in typescript extension](https://github.com/microsoft/vscode/tree/master/extensions/typescript-language-features) the update [Pick up ts 3.4.5](https://github.com/microsoft/vscode/commit/24ff03f6274169b6613026d43a3e831d29342cd8#diff-a5a2289f01a84ef64ce81f0e8e468c96)
But I'm not sure the reason.
I will test on the latest VS code insiders build about 12 hours later, also share the test project later

**Comment by plat123456789** [comment]
@mjbvz I test on latest VS Code insiders build. CPU usage average 10 - 50%. I think I will not upload the project but share the package.json, thank you.
```
{
  "name": "uploader",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@koa/cors": "^2.2.3",
    "csv-parse": "^4.4.1",
    "koa": "^2.7.0",
    "koa-body": "^4.1.0",
    "koa-router": "^7.4.0",
    "koa-views": "^6.2.0",
    "lowdb": "^1.0.0",
    "mysql2": "^1.6.5",
    "nodemailer": "^6.1.1",
    "puppeteer": "^1.14.0",
    "request": "^2.88.0",
    "simple-node-logger": "^18.12.22"
  },
  "devDependencies": {
    "eslint": "^5.16.0"
  }
}
```

**Comment by mjbvz** [comment]
How long do the spikes last? Momentary spikes are expected when you are actively changing code or navigating. If they spikes last longer, please share the output of running [`code-insiders --status`](https://github.com/Microsoft/vscode/wiki/Performance-Issues) from the command line when one of them happens

**Comment by plat123456789** [comment]
@mjbvz the spikes appear only when I editing the js file (typing in the file), after I stop editing, CPU usage go back 0-10% quickly.

**Comment by mjbvz** [comment]
A spike in cpu usage is expected while typing as we are re-computing errors and computing other language features, such as intellisense
