### ISSUE TITLE
net::ERR_CONNECTION_RESET on windows 7

### ISSUE THREAD

**Issue by shenweiyan** [Microsoft/vscode#72692]
On my windows 7 x64, I got `net::ERR_CONNECTION_RESET` error when I want to update vscode.

- VSCode Version: 1.32.3
- OS Version: windows 7 x64

So I want to known which resources vscode is needed when it update ?

**Comment by joaomoreno** [comment]
These are the resources: https://code.visualstudio.com/docs/setup/network#_common-hostnames
