### ISSUE TITLE
Failed : Reveal in sidebar on workspace

### ISSUE THREAD

**Issue by AlanWalk** [Microsoft/vscode#72698]
Issue Type: <b>Bug</b>

Hello, I have a workspace containing many folders. When I used 'Reveal in sidebar', vscode could not locate this file.But when I open the folder directly, using 'Reveal in sidebar', vscode can locate the file.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (5.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
proto-snippets-for-lua-client2|Ala|0.2.0
proto-snippets-for-lua-d2c_rep|Ala|0.2.0
proto-snippets-for-lua-dungeon_common|Ala|0.2.0
quick-open-file|Ala|0.1.3
ue4-lua-snippets|Ala|1.0.0
vscode-opennewinstance|chr|0.0.6
vstortoise|flo|1.2.2
rainbow-csv|mec|1.0.0
luacheck|rog|1.0.0
vscode-proto3|zxh|0.2.2

(1 theme extensions excluded)

</details>

**Comment by devaradhanm** [comment]
I was facing similar issue.  my config looked something like below:
 "folders": [
        {
            "name": "root",
            "path": "../",
        },
        {
            "name": "project1",
            "path": "../packages/project1"
        },
        ....
   }
],
 "settings": {
           "files.exclude": {
            "**/packages/": true,
        },
  }

So, whenever i try to open any file under packages folder, reveal in sidebar doesnt work. But, if i remove the files.exclude line, then it reveals under the root folder instead of project1 folder.


As a workaround, I had to move the root folder config below the project1 folder config & restart vscode.

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by AlanWalk** [comment]
It's not valid.

**Comment by isidorn** [comment]
Then closing as fixed in latest insiders
