### ISSUE TITLE
Cannot find node if path in envFile

### ISSUE THREAD

**Issue by sheeldotme** [microsoft/vscode#72695]
Issue Type: <b>Bug</b>

1. Create a file .envrc that appends to $PATH
2. Set envFile in a debug configuration.
3. Debug the application

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.78GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by weinand** [comment]
What debug extension are you using?

**Comment by sheeldotme** [comment]
I'm using nix which does an eval to get the env variables so I tried it manually with the following which still didn't work for me:

.env:
`PATH=/nix/store/cn7z089w546p8qvxddg0am6m43p88ak5-nodejs-11.13.0/bin:$PATH`

launch.json

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "ABC",
            "protocol": "inspector",
            "sourceMaps": true,
            "outFiles": [
                "${workspaceFolder}/bundles/core/downloader/result/**/*.js"
            ],
            "restart": true,
            "smartStep": true,
            "cwd": "${workspaceFolder}/bundles/core/downloader",
            "envFile": "${workspaceFolder}/bundles/core/downloader/.env"
        }
    ]
}`

`Sheels-MacBook-Pro:downloader sheelpatel$ ls /nix/store/cn7z089w546p8qvxddg0am6m43p88ak5-nodejs-11.13.0/bin
node  npm  npx
`

**Comment by sheeldotme** [comment]
@weinand, is there anymore information I can provide to help move this forward?

**Comment by weinand** [comment]
.env files are not shell files, so
`export PATH=/nix/store/cn7z089w546p8qvxddg0am6m43p88ak5-nodejs-11.13.0/bin:$PATH`does does not work.

The syntax of .env file is:
- each line in an env file to be in VAR=VAL format.
- Lines beginning with # are processed as comments and ignored.
- Blank lines are ignored.
- There is no special handling of quotation marks. This means that they are part of the VAL.
