### ISSUE TITLE
Intellisense not working for required libraries

### ISSUE THREAD

**Issue by meindra** [Microsoft/vscode#72704]
- VSCode Version: 1.33.1
- OS Version: Windows 10 Pro 1809
- Node Version: 11.14.0

Steps to Reproduce:

1. require a library (lodash, express, http, etc) and assign it to a variable (ex: lodash)
2.  type 'lodash.' then the suggestion box will pop up, but no suggestions from the library

Does this issue occur when all extensions are disabled?: Yes

This happened when I used the typescript version 3.4.3 (used by default by vscode 1.33.1). I tried it with version 3.4.1 and 3.4.2 but the issue still persists. I managed to fixed it by changing it to typescript version 3.3.3. 

Still not sure what caused it. Maybe the automatic type acquisition not working properly? Hope this will get fixed in the upcoming releases.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by meindra** [comment]
<img width="698" alt="Screenshot_212" src="https://user-images.githubusercontent.com/6771960/56728864-03df0b00-677e-11e9-9986-14e100460c79.png">

VSCode 1.34.0-insider (TS v3.4.5, node v11.14.0)
Intellisense still not showing up.

**Comment by meindra** [comment]
<img width="572" alt="Screenshot_213" src="https://user-images.githubusercontent.com/6771960/56729362-4ce38f00-677f-11e9-8e05-1032ca05d9df.png">

It worked on VSCode 1.33.1 with TS v.3.3.3

**Comment by mjbvz** [comment]
I suspect that [type acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) is failing. You can test this theory by npm installing `@types/lodash` and seeing if that fixes the issue

Also can you please try collecting the log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This will open a `tsserver.log` file. 

In the same folder as the `tssserver.log` file, there is `ti-xxx.log` file that contains info about automatic typing acquisition. If you can share that log file, I can take a look to see if it is working as expected

**Comment by meindra** [comment]
this is the ti-xxx.log file 
[ti-1988.log](https://github.com/Microsoft/vscode/files/3124510/ti-1988.log)

it worked with @types/lodash
<img width="647" alt="Screenshot_214" src="https://user-images.githubusercontent.com/6771960/56857144-1b8fdc80-6994-11e9-9a81-d48abfbdb80c.png">

**Comment by meindra** [comment]
ah, it's working again after I installed npm globally and reinstall lodash, I guess that's the problem

**Comment by mjbvz** [comment]
Yes, you need a global install npm for automatic type acquisition to work properly. From the logs, it looks like we can't find npm:

```
[8:56:17.697] Exec: npm install --ignore-scripts types-registry@latest
[8:56:17.888]     Failed. stdout:
    
    stderr:
    internal/modules/cjs/loader.js:670
        throw err;
    ^

Error: Cannot find module 'C:\Users\meindra\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

If you have npm installed but this automatic type acquisition still isn't working, try setting [`typescript.npm`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_fixing-npm-not-installed-warning-for-automatic-type-acquisition) to point to the npm install
