### ISSUE TITLE
Terminal: Create New Integrated Terminal crash on Windows 10 on Arm (running win32 binary)

### ISSUE THREAD

**Issue by vielmetti** [Microsoft/vscode#72709]
Issue Type: <b>Bug</b>

To reproduce:

Ctrl-Shift-P "Terminal: Create New Integrated Terminal". 

Immediate "The Window Has Crashed" message, though I'm able to restore the window I had been working on and carry on with no loss of data.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon (TM) 850 @ 2.96 GHz (8 x 1613)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.64GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0

</details>

**Comment by Tyriar** [comment]
You should upgrade to the 64-bit client

/duplicate https://github.com/Microsoft/vscode/issues/72190

**Comment by vielmetti** [comment]
"terminal.integrated.windowsEnableConpty": false

in settings worked, per #72190 .

Just so I'm clear, I'm running Windows 10 on Arm - is there an arm64 client? (I didn't think that it was ready....)

**Comment by Tyriar** [comment]
@vielmetti I don't think we have a arm64 client, I wouldn't have thought VS Code would work at all there? 😕 Are you using the 32-bit client?

**Comment by vielmetti** [comment]
I'm using the 32-bit client and it's been fine (admittedly in light use so far) running in emulation. The terminal crash has been the only misfeature so far, and that setting fixed it.

I'm aware of various efforts to get a native 64-bit Electron build (see the work @headmelted is up to) but I'm not running that - though I would love to be.
