### ISSUE TITLE
Auto-complete is not working correctly

### ISSUE THREAD

**Issue by tamvcspk** [Microsoft/vscode#72700]
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Press "this." 
2.Got "thisis."

![ezgif com-optimize](https://user-images.githubusercontent.com/7186798/56482545-f19b6d80-64ee-11e9-982d-0cb4020ece8b.gif)

Does this issue occur when all extensions are disabled?: Yes
This bug is really annoying. It happened so frequently. Please fix it.

**Comment by octref** [comment]
@jrieken Not sure if same cause as https://github.com/Microsoft/vscode/issues/70974

**Comment by tamvcspk** [comment]
I workaround by setting: 
`"editor.acceptSuggestionOnCommitCharacter": false`
and It haven't happened again
