### ISSUE TITLE
Sorting in Outline

### ISSUE THREAD

**Issue by clive-ccc** [Microsoft/vscode#72703]
Issue Type: <b>Bug</b>

I have set outline sort by position in settings.But when I open file ,outline is sort by type. If I want use outline sort by position, I must change outline sort by manual .Then,I re-open that file ,outline wil sort by position.I think this is a bug, and I do not want changing sort in manual everytime. I hope that when I open file ,outline is sort by which I set in settings.Thanks!

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.00GB free)|
|Process Argv|.\|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
beautify|Hoo|1.4.11
cpptools|ms-|0.22.1
korofileheader|OBK|3.6.0
vscode-icons|vsc|8.4.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by andyfcx** [comment]
I am using python, outline worked sometime, and sometimes the outline just broken and said "No symbols found in the document", weird.

**Comment by jrieken** [comment]
> I have set outline sort by position in settings.

A setting as in settings.json? Today we only persist the UX state (using a memento) so are you actually changing some setting?

**Comment by clive-ccc** [comment]
About outline ,I just change Symbol Sort Order to positon in settings.

**Comment by jrieken** [comment]
@clive-ccc And then? Does it work? What is the expected and actual behaviour? For me sorting by position/name/type works and is persisted when changing files

**Comment by clive-ccc** [comment]
,I just change Symbol Sort Order to positon in settings. But when I open file at first time,it is sorted by type not position.If I want use sort by position mode ,I must change out line in explorer.It means  it was no use by set in settings.

**Comment by jrieken** [comment]
> It means it was no use by set in settings.

What setting are you using? Can you provide the name here?

**Comment by rakkarage** [comment]
there is a breadcrumbs: symbol sort order setting
it does not work for outline

**Comment by jrieken** [comment]
no actionable information provided
