### ISSUE TITLE
Cleanup the Plugins Section UI

### ISSUE THREAD

**Issue by pratyushtewari** [Microsoft/vscode#72716]
I am always overwhelmed by the amount of information and details on the plugin section. I was thinking to improve this design by moving a few details together so the there is more white-space in the UI without removing any existing details.

Check out the proposed difference.

![Improvement on Plugin UI](https://user-images.githubusercontent.com/251768/56510818-eea57a80-64f8-11e9-98fe-30d3849ce1bf.png)

1. `Bookmark recommended indicator` is moved down here to cleanup the icon making the left side cleaner
2. `version, number of downloads abd rating `are moved down here to cleanup the header making the right side cleaner

The changes are not much.

Please let me know if this is good and I can send a PR.

**Comment by sandy081** [comment]
Please add your thoughts here - https://github.com/Microsoft/vscode/issues/68527
