### ISSUE TITLE
Switching git branches doesn't refresh the TOC 

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode#72717]
Issue Type: <b>Bug</b>

I'm switching branches quickly, making changes, commiting and pushing, then switching again. Either the TOC isn't refreshing fast enough (without doing anything) or I have to close and open a parent node in the TOC. Not sure which one is the case. 

If git is still returning status to VSCode so that the TOC is out of date, can't you give a visual indication of that so I don't try to get to files that VSCode doesn't know about yet? 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
vscode-markdownlint|Dav|0.26.0
docs-article-templates|doc|0.2.2
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.4
docs-preview|doc|0.3.17
docs-yaml|doc|0.2.1
python|ms-|2019.3.6558
powershell|ms-|1.12.1
vscode-yaml|red|0.4.0
code-spell-checker|str|1.7.1

</details>

**Comment by joaomoreno** [comment]
What is the TOC?

**Comment by diberry** [comment]
Table of contents showing files and folders.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that TOC?

**Comment by diberry** [comment]
It is the github.com/MicrosoftDocs/azure-docs-pr repo with the cognitive-services/LUIS folder open. I'll try to repro and git the screenshot.

**Comment by xianxingg** [comment]
Kinda irrelevant, but it's a good idea to record `current branch open files`, and when switching branches, open files should be updated! I need this option. That is: different branch, different feature, different context, different work files.

**Comment by joaomoreno** [comment]
@diberry If you get a screenshot, let me know.
