### ISSUE TITLE
Support opening files from a file system provider through URL handling

### ISSUE THREAD

**Issue by mathieudutour** [Microsoft/vscode#72712]
## Context
- In #4883, support for opening files through URL handling was added so you can open files in vscode by opening a URL like `vscode://file/path/to/file`.
- The File System provider was added a bit later so extensions can register url schemes.

## Feature Request
Right now, if you have an extension registering the `memfs` file system scheme, opening `vscode://file/memfs://path/to/file` doesn't work. I'd be nice to make it work.

_I'm happy to work on this if this is something the team considers adding to vscode._

**Comment by jrieken** [comment]
This already working using a `UriHandler`, see https://github.com/Microsoft/vscode/blob/ef4a8062233114d6913ffff7265f15e921f59e6d/src/vs/vscode.d.ts#L6668-L6689

**Comment by mathieudutour** [comment]
Ah that can work, thanks!
