### ISSUE TITLE
Install/Update failures: Code.exe being used by another process

### ISSUE THREAD

**Issue by purplekrayons** [Microsoft/vscode#72714]
- VSCode Version: 1.32.3
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. Attempt to update, or re-install VS Code

Does this issue occur when all extensions are disabled?: Yes/No
Yes, it occurs regardless of extensions

Upon attempting to update VS Code to 1.33.1,  get warnings indicating that Code.exe is being used by another application, and as such, the update fails. Similarly, uninstalling VS Code, and attempting to re-install, also fails with a similar warning.

In fact, upon attempting to re-install the application, and choosing to "Abort", it breaks the entire installation during it's rollback.

> Uncaught Exception:
Error: Cannot find module 'C:\Users\BATMAN\AppData\Local\Programs\Microsoft VS Code\resources\app\out\main` at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)

When attempting to update, I receive a warning that Code.exe is already in use:

> C:\Users\BATMAN\AppData\Local\Programs\Microsoft VS Code\Code.exe
The process cannot access the file because it is being used by another process.

After having closed Visual Studio code, I noticed there were still several processes running via task manager. I manually terminated those, and tried to install --- same thing; Code.exe is being used by another process.

I'll note that, per another issue submitted (and has since been locked), I've tried disabling the background updates --- this did not resolve the issue. It still throws a warning that Code.exe is locked up.

I was however, able to resolve the issue by doing one notable thing: closing Slack. I feel as though this may be of particular importance considering that Slack is also built on-top of Electron. Something for the team to consider.

**Comment by stt888** [comment]
I have had the same problem since I use VScode.

**Comment by chriswiley** [comment]
I ended up booting into Safe Mode in Windows 10 and doing the update there. I couldn't get it to update any other way.
