### ISSUE TITLE
Integrated Terminal doesn't display path

### ISSUE THREAD

**Issue by ZsgsDesign** [Microsoft/vscode#72711]
Similar to #57803, I noticed that the problem has already been solved by the new API, but mine still exists.

- VSCode Version: 1.33.1 (system setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Click the new terminal button
2. the new terminal starts but with nothing displayed
3. Enter anything, like clear
4. The path displays again

![1](https://user-images.githubusercontent.com/19504567/56505460-55a14e80-654e-11e9-92d2-19df555ba014.PNG)
![2](https://user-images.githubusercontent.com/19504567/56505700-ebd57480-654e-11e9-8d22-e68ad104d835.PNG)
![3](https://user-images.githubusercontent.com/19504567/56505702-ec6e0b00-654e-11e9-9e01-5ab216e4b7f2.PNG)

Does this issue occur when all extensions are disabled? Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
