### ISSUE TITLE
Use keyboard to open method information

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#7271]
- VSCode Version: 1.2.0-Insider
- OS Version: Windows 10 Build 14332

How do I use the keyboard to open detailed method information?

![image](https://cloud.githubusercontent.com/assets/466713/15839301/d93d2876-2bff-11e6-9c0a-46422aaa0494.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by Tyriar** [comment]
Hitting <kbd>ctrl</kbd>+<kbd>space</kbd> toggles the information
