### ISSUE TITLE
Disable auto update for some extensions

### ISSUE THREAD

**Issue by vnen** [Microsoft/vscode#72715]
I would want to disable the update of a single extension, since an update broke it. But I still want all other extensions to keep updating.

There's a mention that installing a different version manually disables the auto-update (https://github.com/Microsoft/vscode/issues/30579#issuecomment-456028574) but this is not true: installing an older version triggers the update immediately (I would comment on the issue but it's locked).

While #37162 could solve my case, I'm asking for something much simpler, since I don't really care if the other extensions update to a new major version, as long as it's not broken. I just want to keep the one extension in an older version for now.

**Comment by sandy081** [comment]
There was a bug that continues to auto update those extensions which were installed with specific version and got fixed in this milestone.
