### ISSUE TITLE
STATUS PROCESSING appears

### ISSUE THREAD

**Issue by halmsx** [Microsoft/vscode#72724]
Issue Type: <b>Bug</b>

edit php file with multiple functions. update codes. STATUS PROCESSING appears in outline and didnt disappear.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
php-intellisense|fel|2.3.10
beautify|Hoo|1.4.11
vscode-insertdatestring|jsy|2.2.3
php-cs-fixer|jun|0.1.118
VS-code-drupal|mar|0.0.12
python|ms-|2019.3.6558

</details>

**Comment by jrieken** [comment]
what is 'STATUS PROCESSING'?

**Comment by halmsx** [comment]
> what is 'STATUS PROCESSING'?

after clean reinstall, the text disappeared. but when i make changes to methods, the outline list does not update or change. when i clicked on an item in outline list, it doesnt jump to it like it supposed to. i had to restart vscode for that work every time i update the files. this mostly happens when i opened more than 1 editor window.

**Comment by jrieken** [comment]
Ok, please producible steps, like the extension(s) you are using, the file you are working in etc, etc

**Comment by jrieken** [comment]
no actionable information
