### ISSUE TITLE
Git: Opening file from another project add it to source control provider

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#72722]
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:22:55.268Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

- Have two git folders, `/a` and `/b`
- Open `/a` with VS Code
- Cmd+O and open a single file from `b` such as `/b/README.md`
- You end up with 2 source control providers and Viewlet count will always be messed up

How can I disable this behavior?

![image](https://user-images.githubusercontent.com/4033249/56515475-d6c7f980-64ec-11e9-920c-0f8df97ae54d.png)

**Comment by rebornix** [comment]
Can you bump the importance of this issue a bit as VS Code can be the default editor for Git. It means, anytime when you run a git command which requires an editor, the editor will run into the state where there is zombie git repository in the SCM Viewlet

![image](https://user-images.githubusercontent.com/876920/56914063-fc627f00-6a67-11e9-82e4-e7bf3fae2032.png)

**Comment by octref** [comment]
> Can we bump the importance of this issue a bit

That's what important label is for!

This should also be a regression because I haven't seen this happening until like a month ago.

It's also annoying when you are debugging into dependencies linked locally (which I do every day).

**Comment by joaomoreno** [comment]
`"git.autoRepositoryDetection": "subFolders"`
