### ISSUE TITLE
Option for unified Search / Replace Bar

### ISSUE THREAD

**Issue by assumptionsoup** [microsoft/vscode#72725]
I like the way that sublime text has a unified search / replace bar for all open tabs. The search is executed on the tab with focus. Usually when I'm searching, I'm searching for the same text across multiple files. In VS Code, this happens:

-> Search in one tab
-> Switch to another, open search
-> Realize I need the search term from the other tab
-> Mouse over to the other tab. Select the search term, copy.
-> Go back to my original tab.
-> Paste and search again

This is tedious and interrupts my workflow. A "Sync Search" or "Unified Search" option would be very helpful.  That is to say, either a single search widget across all tabs to the replace the per-tab search widgets, or the ability to keep all search widgets in sync.

**Comment by roblourens** [comment]
The history should at least be shared across tabs, if that helps. It will not be shared between editor groups though.

**Comment by assumptionsoup** [comment]
@roblourens Oh, I think I described the issue poorly. Not sharing widgets / history across editor groups is the problem. You're right, the widget is the same across tabs.
