### ISSUE TITLE
Feature request: start to debug C++/python directly from command line.

### ISSUE THREAD

**Issue by 9527KGG** [Microsoft/vscode#72726]
This a feature request. Currently, for C++ to debug the exe or attach a process, for python, to debug a py script, I've to setup launch.json, which is very tedious if you just want to do some quick very verification.

Request: start to debug directly from command line, eg

For cpp,
code -e cpp -d ./a.out arg1 arg2, argN: to debug a.out with arg1 and arg2.... argN
code -e cpp -p 12345: attach process 12345.

"-e cpp" means "pass the following parameters to vscode-cpptools extension."

For python:
code -e vspy -d ./a.py arg1 arg2, argN: to debug a.py with arg1 and arg2.... argN
"-e vspy" means "pass the following parameters to vscode-python extension."

As a comparison:

In visual studio, you can devenv.exe /debugexe a.exe

Eclipse has a plugin: https://github.com/eclipse-cdt/cdt/blob/master/debug/org.eclipse.cdt.debug.application/scripts/cdtdebug.sh, which allow you to start debug from command line.

Emacs (which is close to VScode since both VScode and emacs are editors while VS/Eclipse are IDE, you can pass some parameters https://stackoverflow.com/questions/5997309/start-emacs-gdb-from-command-line to start debugging directly.

**Comment by 9527KGG** [comment]
There is a related one, https://github.com/Microsoft/vscode/issues/10979. However, it's about typescript. So I am not sure if mine is dup or that one.

**Comment by 9527KGG** [comment]
#3502 and Microsoft/vscode-python#5396 are the related extension request.
I think it needs work from vscode and extension.

**Comment by weinand** [comment]
yes, this very similar to  #10979.

In general this feature can be implemented as an extension (and at least one extension already exists). It is not on our roadmap.

**Comment by 9527KGG** [comment]
cpptool guys from https://github.com/Microsoft/vscode-cpptools/issues/3502, said “This would be a feature for VS Code itself. There is no commandline option to pass to the extension at the moment. Please submit an issue at https://github.com/Microsoft/vscode/issues”
Just FYI

**Comment by weinand** [comment]
The extension https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-debug-launcher proves that this feature can be implemented without directly VS Code support.

**Comment by 9527KGG** [comment]
Hi @weinand , cpptools folks said "For this feature, this would require implementing VS Code's UriHandler which should call startDebugging with the given parameters.". Please see it here https://github.com/Microsoft/vscode-cpptools/issues/3502#issuecomment-486371241
