### ISSUE TITLE
JavaScript identation and autocomplete stop working at some point

### ISSUE THREAD

**Issue by maramal** [Microsoft/vscode#72737]
Issue Type: <b>Bug</b>

I have to close VS code at some point (randomly) when coding because line identation and autocomplete don't work anymore. The error has been "shown" in two different workstations with Windows 10 both.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (5.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
vscode-django|bat|0.19.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vue-snippets|hol|0.1.11
angular-essentials|joh|0.6.0
Angular2|joh|7.0.1
vscode-peacock|joh|2.1.0
graphql-for-vscode|kum|1.13.1
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.7.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.6.0
vscode-react-native|vsm|0.9.2
jinja|who|0.0.8
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
