### ISSUE TITLE
Issue with moves focus

### ISSUE THREAD

**Issue by wbobillet** [microsoft/vscode#72741]
Issue Type: <b>Bug</b>

Focus moves disabled, but my Tab button still continue to change focus. no Tab/space  in the editor is/are added

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3530)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|31.32GB (10.06GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
msg|ajs|0.1.1
ros|ajs|0.3.0
cpptools|ms-|0.22.1
vs-keybindings|ms-|0.2.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3

</details>

**Comment by rebornix** [comment]
@wbobillet do you still see the issue after you reload the window?

**Comment by wbobillet** [comment]
Yes nothing s changed. My tab button no longer insert a tab or spaces

**Comment by rebornix** [comment]
Could you help confirm if you can reproduce once you set `editor.accessibilitySupport` to `off`?
