### ISSUE TITLE
typescript format options for the second params' indent level

### ISSUE THREAD

**Issue by Wyntau** [Microsoft/vscode#72746]
my code is 
```ts
function bizError(err: ErrorData) {
  return window.Owl && Owl.addError({
    name: 'Biz_Error',
    msg: 'Error Content：' + JSON.stringify(err, null, '  ')
  }, {
    category: Owl.errorModel.CATEGORY.AJAX
  });
}
```

when vscode auto format, it will become
```ts
function bizError(err: ErrorData) {
  return window.Owl && Owl.addError({
    name: 'Biz_Error',
    msg: 'Error Content：' + JSON.stringify(err, null, '  ')
  }, {
      category: Owl.errorModel.CATEGORY.AJAX
    });
//↑ indent level changed
}
```

How can I preserve the indent level in this condition. the second params is a multi line object, and I want it's properties to indent only 1 level.

I changed all `typescript.format.*` options, but have no effect.
If I disabled typescript formatter, it will not change my indent level again.

So my question is How I can preserve the indent level?

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/14589
