### ISSUE TITLE
Chinese characters are not exactly equal to the width of two English letters

### ISSUE THREAD

**Issue by yoqo** [microsoft/vscode#72743]
![img](https://i.niupic.com/images/2019/04/23/6g5s.png)

![img](https://zhanghuimeng.github.io/post/using-chinese-monospace-in-vscode/after-formatting.png)

I expect the width of a Chinese character to be exactly equal to two English characters.

**Comment by alexandrudima** [comment]
This is determined by the font. If you would like for a wide character to have the width of a latin character, then please switch to a font which defines this, like e.g. Inconsolata or others...
