### ISSUE TITLE
Allow repositioning of the debug control panel

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#7274]
On smaller screens (15" in this case), the debug control panel is hiding anything below it's top-center position. It would be great if users could drag the debug control panel across the horizontal axis (or wherever) to reveal anything hidden.

In this example I have two panes and the split editor button in the first pane is covered:

![screen shot 2016-06-06 at 6 54 49 pm](https://cloud.githubusercontent.com/assets/15803541/15840597/e42b3700-2c18-11e6-80e8-5ba834fc7287.png)

In this example I have a three panes and the name of the file in the center pane and the button to close the left pane are covered:

![screen shot 2016-06-06 at 7 00 36 pm](https://cloud.githubusercontent.com/assets/15803541/15840613/fabf427c-2c18-11e6-9f2f-a3b2873f5729.png)

**Comment by isidorn** [comment]
Dup of #4580
We will look into fixing this issue in June
