### ISSUE TITLE
Emmet: Add support for 'css.color.short' Emmet preference

### ISSUE THREAD

**Issue by agragregra** [microsoft/vscode#72748]
By default:
color: #666666

Is required:
color: #666

Where this option?

**Comment by aeschli** [comment]
Can you give more details? Is this about the colors the color picker writes?

**Comment by agragregra** [comment]
in files .css & sass CODE!

**Comment by agragregra** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10989424/56589961-69ad8480-6610-11e9-9726-749df81c6ce8.png)

**Comment by aeschli** [comment]
Thanks @agragregra. Please explain how this got there and what you expect VSCode to do,

**Comment by agragregra** [comment]
По-умолчанию Emmet распаковывает HEX цвета при написании стилей в вашем редакторше в длинный код, например, #666666, а нужно, чтобы было #666. Что тут не понятного?
Переведете короче.

**Comment by iansan5653** [comment]
Sounds like you would like Emmet to prefer short hex colors instead of long ones on autocomplete. This is Emmet's default behavior but it appears that VSCode has overridden it and doesn't support the setting that would allow for adjusting this:

```
"emmet.preferences": {
  "css.color.short": true
}
```

This has no effect though so support needs to be added.

**Comment by iansan5653** [comment]
@agragregra Why don't you change the title to "Add support for 'css.color.short' Emmet preference"? Then the feature request will be much clearer and more likely to be addressed.

**Comment by rzhao271** [comment]
Closing in favour of #72594. 
@iansan5653 the original title is understandable; the VSCode Emmet extension hasn't been looked at for a while.
