### ISSUE TITLE
Search within search inside file

### ISSUE THREAD

**Issue by Lelelo1** [Microsoft/vscode#72756]
When searching inside a large file I would like to be able to search between the results of my first search. So that I can `firstSearch && searchInBetween` in the search textfield.

I can press enter with `firstSearch` like it is know with existing functionality. If there are 4 instances of `firstSearch` - move to instance 3 with enter - and by appending with `... && newSearch` to search between 3 - 4 instances of `firstSearch.` with a new phrase: `newSearch`

It would make the search more like a query. And the times you want to search for instances of `&&` in the code it would be a problem. But something like this would help moving through a lot of code quickly.

**Comment by roblourens** [comment]
I don't want to support special syntax in the search field, when people need to be able to just search using that syntax. It would be confusing
