### ISSUE TITLE
Arrow function parameter syntax highlighting does not work

### ISSUE THREAD

**Issue by bcmarinacci** [Microsoft/vscode#7275]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

Regular function parameters are highlighted properly but arrow function parameters are not.

![screen shot 2016-06-06 at 4 16 41 pm](https://cloud.githubusercontent.com/assets/14657580/15841018/d1772760-2c02-11e6-80dd-b7342eb7b950.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#187
