### ISSUE TITLE
Some Directory of .Net MVC Project not Showing in Explorer Tree.

### ISSUE THREAD

**Issue by dhunmoon** [Microsoft/vscode#72755]
I have a .Net MVC project when I open the same project in VSCode some of the folder is not visible.
![image](https://user-images.githubusercontent.com/7768142/56568205-29c8ac00-65d4-11e9-8b1a-4266f1f9f5ff.png)

If you see the Image which is the comparison of Directory structure of Visual Studio 2019 and VSCode there are many Folders are not visible. 

The folders which should be visible are `Add_Data`, `App_Start`, `Areas`, `Controller`,`View`,  etc.

any Ideas why is this happening.

**Comment by bpasero** [comment]
@jrieken explorer issues are going to Isi

**Comment by markheath** [comment]
I've got a similar (maybe related) issue with an ASP.NET Core MVC project where the contents of my wwwroot folder stop showing when I expand the tree node in the explorer.

![image](https://user-images.githubusercontent.com/147668/56720074-da03f500-6739-11e9-84b3-f23a5cc9e0de.png)

If I reload VS Code, I can see the folder contents again:

![image](https://user-images.githubusercontent.com/147668/56720105-f6a02d00-6739-11e9-92e1-d207a0846350.png)

Don't know what triggers it getting into this state, but its happened several times over the last few days

**Comment by isidorn** [comment]
I can not reproduce this.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, please try to get better reproducable steps and create a repository on GitHub for which you see this so we can clone it and investigate more on our machines.
