### ISSUE TITLE
Dump filesystem watchers to output window

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#72758]
### Problem
I often run out of filesystem watchers (inotify instances) on linux. Each time I increase the limit, but after a while I run into the problem again.

I often have multiple vscode windows open, and other apps which consume inotify instances. I exclude things like `node_modules`, but there is always something that eats all my inotify instances... even though I've set it to 50k!

And then I get the dreaded `System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached.` (aspnet core).

### Feature Request
Please add a feature to the command palette called `Dump inotify instances`, or `Show filesystem watchers` or something similar.

When run, it would dump all watched directories and files to the output window.

### Value of this feature
It would be very EASY and very QUICK to find out which paths should be excluded.

This problem comes up again and again in the issues. This feature would make it easy for developers to diagnose the problem.

### Environment
Ubuntu 18.10
VSCode 1.33.1

**Comment by Tyriar** [comment]
[This](https://stackoverflow.com/a/17200850/1156119) should help:

```
inotifywait -m --timefmt '%H:%M' --format '%T %w %e %f' ~/some/filter/*
```
