### ISSUE TITLE
Show offending file path, when "Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`."

### ISSUE THREAD

**Issue by samodadela** [microsoft/vscode#72752]
I'm getting this notification since a week or so:
Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`.

Would it be possible for the notification to show the path of the offending file? 

VsCode Mac (latest Mojave), Version 1.33.1 (1.33.1)
Project: C++/CMake

**Comment by anilshatharashi** [comment]
Is this similar to https://github.com/Microsoft/vscode/issues/55212?

**Comment by samodadela** [comment]
I don't think so... I'm just interested in the name of the offending file when I get the "Tokenization is skipped for performance reasons" message.

**Comment by alexandrudima** [comment]
@samodadela It's the current opened file.
