### ISSUE TITLE
Graphics settings break VS Code

### ISSUE THREAD

**Issue by GirtsKru** [microsoft/vscode#72751]
Issue Type: <b>Performance Issue</b>

On my workstation I have Nvidia graphics card. In the NVIDIA control panel, if I change the Image settings with preview value from "Performance" or "Balanced" to Quality the VS Code interface breaks. There are green lines everywhere, text is blurry and have a green shadow. Changing back to "Performance" or "Balanced" fixes the issue, but I would like to run the best setting for graphics quality.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (19.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	 20732	code main
    0	   211	   948	   window (loadDocumentsSaga.js - Frontend - Visual Studio Code)
    0	    14	  3200	     watcherService 
    0	    11	 21212	       console-window-host (Windows internal process)
    0	     7	 12392	     winpty-process
    0	    70	 19944	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	 20964	       console-window-host (Windows internal process)
    0	    13	 18300	     electron-crash-reporter
    0	    75	 21376	     extensionHost
    0	   118	 19804	       electron_node eslintServer.js 
   18	   183	 21476	       electron_node tsserver.js 
    0	    68	 20928	         electron_node typingsInstaller.js typesMap.js 
    0	    75	 10776	   shared-process
    0	   119	 20452	   gpu-process
    0	    66	 20568	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (loadDocumentsSaga.js - Frontend - Visual Studio Code)
|    Folder (Frontend): 334 files
|      File types: js(271) map(12) scss(11) json(9) xml(7) png(6) html(3)
|                  dll(2) xlsx(1) babelrc(1)
|      Conf files: package.json(1) webpack.config.js(1) settings.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
powershell|ms-|1.12.1

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by GirtsKru** [comment]
Downloaded the Windows version, and that seem to be working excellent. Also now that I'm connected to external monitor, noticed that this issue is only present on the built in laptop screen, not on external monitors. Attached a screenshot comparing VS Code and the VS Code- Eploration
![VSCode_VSCodeExploration](https://user-images.githubusercontent.com/49897803/56636006-25ea6780-6670-11e9-8087-a78fb142fd3e.png)

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
