### ISSUE TITLE
terminal tiny bugs with new console

### ISSUE THREAD

**Issue by pbpf** [Microsoft/vscode#72761]
Issue Type: <b>Bug</b>

When using new console, terminal can not input in first line, you must type a [enter] firstly.
when using old console, everything just fine.
But sometime you need new console, for example : wsl.

This is a tiny bug, but makes me feel very sad, I need change between new console and old console again and again and again ...

Please fix it.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.85GB free)|
|Process Argv|E:\projects\manuscripts\AIAA\bak\再入动力学近似.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
scad|efb|1.0.1
code-runner|for|0.9.8
matlab|Gim|1.1.0
latex-workshop|Jam|6.4.0
language-julia|jul|0.11.5
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
Go|ms-|0.9.2
vscode-3dviewer|sle|0.1.0
octave|toa|0.0.3
markdown-all-in-one|yzh|2.2.0

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
