### ISSUE TITLE
Does vscode-node-debug support Sourcemap section?

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/vscode#7276]
Does vscode-node-debug support Sourcemap section?

**Comment by weinand** [comment]
@frogcjn what do you mean by 'Sourcemap section'?

VS Code supports source maps, including inlined source maps and inlined source.

VS Code does **not** support 'index maps' (see https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?hl=en_US)

**Comment by frogcjn** [comment]
@weinand
ReactNative generate source map v3, with a sections property, then vscode cannot match with this kind of source map. Vscode only can debug with source code without sections. chrome supports debug with source map sections.

**Comment by frogcjn** [comment]
let developer debug react native in vscode has two approaches:
(1) let node-debug support sorcemap sections or 
(2) let vscode-react-native transfer sections source map to normal source map.

I have make some progress on the second approach:

<img width="1164" alt="2016-06-07 16 43 04" src="https://cloud.githubusercontent.com/assets/1777562/15851399/1e76875a-2ccf-11e6-8512-f43b10cff401.png">
