### ISSUE TITLE
A new issue label *english-please to auto-close issues in foreign languages

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#72766]
When I'm tracking inbox I see a lot of issues in foreign languages that doesn't have any reproducible details. The cause might be a combination of the issue opener now knowing English well and thus not reading https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues at all.

We should have a *english-please label. When bot sees it it'll close the issue with a message and suggest user to rewrite a new issue using Bing translate.

Extra: We can include a translated version of issue reporting guideline. I can do the Chinese version.

**Comment by chrmarti** [comment]
You could open a PR for https://github.com/Microsoft/vscode/blob/master/.github/commands.yml if you like.

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/pull/72767
