### ISSUE TITLE
Python interpreters/cmds processes are not closed

### ISSUE THREAD

**Issue by schperplata** [Microsoft/vscode#72769]
Issue Type: <b>Bug</b>
Note: [I've already reported this issue to Python extension](https://github.com/Microsoft/vscode-python/issues/5376), but apparently this is not their issue - Python extension does not spawn any processes. 

I am running some python script and after a while (for example, a few days of computer usage), I can see tens of leftower python interpretters and console window hosts in task manager. Seems like something does not do the cleanup properly.

All of those Python processes were spawned with this data:
```
cmd = psutil.Process(3680).cmdline():

0:'W:\\ISYSTEM_APPS\\Python36-64bit\\python.exe'
1:'-c'
2:'from multiprocessing.spawn import spawn_main; spawn_main(parent_pid=12004, pipe_handle=600)'
3:'--multiprocessing-fork'

cmd = psutil.Process(14072).cmdline():
0:'W:\\ISYSTEM_APPS\\Python36-64bit\\python.exe'
1:'-c'
2:'from multiprocessing.spawn import spawn_main; spawn_main(parent_pid=972, pipe_handle=660)'
3:'--multiprocessing-fork'
```

At the same time, there is approximately the same number of Console windows:
```
cmd = psutil.Process(14364).cmdline():
['\\??\\C:\\WINDOWS\\...nhost.exe', '0x4']
0:'\\??\\C:\\WINDOWS\\system32\\conhost.exe'
1:'0x4'
__len__:2

cmd = psutil.Process(840).cmdline():
['\\??\\C:\\WINDOWS\\...nhost.exe', '0x4']
0:'\\??\\C:\\WINDOWS\\system32\\conhost.exe'
1:'0x4'
```

My co-worker does not use VS Code for the same project, and he does not have any remaining python interpretters/cmds after days of work.

![image](https://user-images.githubusercontent.com/8736111/56415968-afc0bc00-628f-11e9-912e-4775bb49e21b.png)

![image](https://user-images.githubusercontent.com/8736111/56415976-b9e2ba80-628f-11e9-8282-9482739b91bb.png)

Extension version: 2019.3.6558
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (2.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
arm|dan|0.3.0
cortex-debug|mar|0.2.3
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
markdown-all-in-one|yzh|2.2.0

</details>

**Comment by Tyriar** [comment]
Do you use the terminal? Do you launch these Python processes or are they being launched by some other tool?

> 0:'W:\\ISYSTEM_APPS\\Python36-64bit\\python.exe'
> 1:'-c'
> 2:'from multiprocessing.spawn import spawn_main; spawn_main(parent_pid=12004, pipe_handle=600)'
> 3:'--multiprocessing-fork'

**Comment by schperplata** [comment]
I have no idea what could create this processes, but I am sure they are spawned by VS Code.

I use the terminal from time to time for quick on the fly testing, but I have no configurations/tasks that would use any kind of multiprocessing - at least not that I would explicitly specify (as in this command).

**Comment by Tyriar** [comment]
It sounds like one of your other extensions is calling them, VS Code itself and the bundled extensions don't touch Python in any way, only its extensions do. If vscode-python isn't the culprit I'd look into your other extensions or maybe some other program (not vscode) that could launch them.
