### ISSUE TITLE
Different typing fonts for Semitic languages

### ISSUE THREAD

**Issue by dzdeveloper** [microsoft/vscode#72772]
Hello, my feature request revolves around specifying fonts for Semitic languages like Arabic in order to look more clear and suitable
 thank you

**Comment by jrieken** [comment]
Can you clarify where and how?

**Comment by dzdeveloper** [comment]
> Can you clarify where and how?

Currently i'm using the Inconsolata font , and it looks good and clear for HTML tags and Latin content but not so much for the Arabic one, so i was wondering if it can be an option for multiple fonts 

![Capture1](https://user-images.githubusercontent.com/4678731/56701366-aeabe680-66f6-11e9-81a6-65b3e7c78f81.PNG)

**Comment by dzdeveloper** [comment]
> Can you clarify where and how?

Currently i'm using the 'Inconsolata' font , and it looks good for HTML tags and Latin content but not so much for the Arabic one, so i was wondering if it can be an option for multiple fonts

![Capture1](https://user-images.githubusercontent.com/4678731/56701433-06e2e880-66f7-11e9-9c51-a795a595c9b7.PNG)

**Comment by alexandrudima** [comment]
@dzdeveloper It is possible to name multiple fonts. e.g.

`"editor.fontFamily": "Inconsolata, Arial"`

This will make it that the glyphs not contained in Inconsolata will be looked up in Arial.

**Comment by dzdeveloper** [comment]
@alexandrudima 

 works like a charm, thank you.
