### ISSUE TITLE
Allow case sensitive paths on Windows/macOS

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#72776]
- VSCode Version: 1.34.0-insider
- OS Version: Windows 10.0.17763

Steps to Reproduce:

1. In a terminal `fsutil.exe file setCaseSensitiveInfo %somepath%`
2. create two files with the same name, but different cases `foo.txt` and `FOO.txt`
3. browse to that `%somepath%` in vscode

![image](https://user-images.githubusercontent.com/49660427/56615232-86759800-65cf-11e9-9baa-90917b1182e3.png)

Observations:
Seems to be limited to the folder tree widget, since find in files correctly lists the case sensitive filenames

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
File service related?

**Comment by bpasero** [comment]
VSCode today does not support file path case sensitivity on neither Windows nor macOS. Related: https://github.com/Microsoft/vscode/issues/48258

//cc @isidorn
