### ISSUE TITLE
Incorrect column count using ASCII text

### ISSUE THREAD

**Issue by tsujp** [microsoft/vscode#72770]
- VSCode Version: Version 1.33.1 (1.33.1), 51b0b28134d51361cf996d2f0a1c698247aeabd8
- OS Version: macOS Mojave 0.14.4 (18E226)

Steps to Reproduce:

1. Paste the following text into VSCode.
2. Observe that immediately before each `(` on each line the column count is 30 despite them not lining up correctly. The line with `Vagrantfile` shows 30 characters before `(` but is shown to be 1 space to the left (see picture).

```
+-- _vagrant/                (dev [prod if cpu-supported])
|   +-- Vagrantfile          (provision VM, uses provision.sh)
+-- README.md                (this file)
```

**The picture and GIF have extensions enabled but I have tested this without extensions and it's exactly the same. I just didn't record it with extensions disabled is all.**

Picture: https://i.imgur.com/cppsCDm.png

GIF (easier to understand): https://i.imgur.com/cm5IpTi.gif
_I used some website to convert the mov screen recording into a GIF, so sorry for the terrible quality. It also seems to have messed with the playback speed._

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by hito** [comment]
I think I know what this is now. It appears to be the ligature "fi". Perhaps an option to render ligatures over 2 columns (seems to defeat the point though) or to have a floating space at the end of the line so that in this case things line up.

**Comment by alexandrudima** [comment]
Yeah, some fonts implement ligatures in such a way that they maintain their monospace properties... So my recommendation is to either disable ligatures or switch to such a font...
