### ISSUE TITLE
cmd in Integrated Terminal automatically deletes the first few lines on startup

### ISSUE THREAD

**Issue by onecalled3bkr** [Microsoft/vscode#72774]
Issue Type: <b>Bug</b>

Starting up a new terminal, typing anything should appear after the prompt.

Actual Results: The prompt is deleted and a clear terminal is shown instead, the input is shifted a certain amount of whitespaces

Expected Results: The prompt isn't deleted and the input is shown directly after it

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (12.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sync|jac|1.0.4
python|ms-|2019.3.6558
cpptools|ms-|0.22.1
subtitles-editor|pep|1.0.2

(2 theme extensions excluded)

</details>

**Comment by onecalled3bkr** [comment]
More to describe the behaviour

![Screenshot_1](https://user-images.githubusercontent.com/44498156/56607465-df155700-6608-11e9-8806-139d7ca0ecaa.png)
![Screenshot_2](https://user-images.githubusercontent.com/44498156/56607467-df155700-6608-11e9-9328-0894d70197d7.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
