### ISSUE TITLE
Find in files doesn't work

### ISSUE THREAD

**Issue by sandorvasas** [Microsoft/vscode#72781]
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

Steps to Reproduce:
Happens sometimes.
1. Select a folder to search in, type a keyword that surely must be found, search
2. No results.

Please fix this asap, it's a horrible issue. I need to grep stuff in terminal

**Comment by roblourens** [comment]
I need more details. How often does it happen? Do you see any results or are you just missing some?

**Comment by sandorvasas** [comment]
Whoops, I think I just figured it out:

Happens when Files to exclude is empty (not even touched that), and the 'Use Exclude Settings and Ignore Files' is enabled (neither touched that, was selected by default).

It might not be a bug, but it's quite counter-intuitive.

**Comment by roblourens** [comment]
So you're looking for results in files that are excluded by settings or a .gitignore file?

**Comment by sandorvasas** [comment]
I don't understand the relation to .gitignore.

'Files to exclude' is an input field in VS Code

 'Use Exclude Settings and Ignore Files' is toggle-button next to 'Files to exclude' in VSCode

**Comment by roblourens** [comment]
The 'Use Exclude Settings and Ignore Files' button enables exclude settings and filtering based on the .gitignore file. If you are missing results when this is enabled then that's why. If that's not what's going on, please be more specific.
