### ISSUE TITLE
Latest Code editor Code Suggestion ALWAYS FAILS!!!

### ISSUE THREAD

**Issue by aisakeniudun** [Microsoft/vscode#72787]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.upldate to 1.33 or the latest one
2.code suggestion fails frequently,Actually the IDE works no better than a text editor !!!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
no actionable information provided
