### ISSUE TITLE
jump to define not work

### ISSUE THREAD

**Issue by ZeddShi** [Microsoft/vscode#72789]
Issue Type: <b>Feature Request</b>

`jump to define` not work suddenly, I'v tried reload app, reinstall app and restart computer are all failed.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
