### ISSUE TITLE
Python Run file on terminal do not work

### ISSUE THREAD

**Issue by camilojm27** [Microsoft/vscode#72780]
Issue Type: <b>Bug</b>

I click to run a python file on terminal and nothing happens

The python interpreter do not work any more too, if i use the command python select interpreter says "python.setInterpreter" not found

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.14.111-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G (2 x 3593)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|6.83GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
python|ms-|2019.4.11881
cpptools|ms-|0.22.2-insiders
material-icon-theme|PKi|3.7.0
code-settings-sync|Sha|3.2.9
clang-format|xav|1.9.0

(4 theme extensions excluded)

</details>

**Comment by iimlearning** [comment]
me,too

**Comment by OnePieceJoker** [comment]
I also had this problem just now

**Comment by takayuki-ishiguro-tkmes** [comment]
me too...

**Comment by cszhangbo** [comment]
Today, my computer and my friends computs do not work, the same problem

**Comment by MLeapFish** [comment]
same problem (win10 and ubuntu18.04, vscode1.33.1)

**Comment by RJAtouT** [comment]
me too

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/issues/5440, https://github.com/Microsoft/vscode-python/issues/5439
