### ISSUE TITLE
Refresh button is shown two times in the References pane

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#72797]
- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:

1. `npx create-react-app . --typescript` (or any other TypeScript codebase)
2. Go to `index.ts` and right-click on `App`, select Find All References
3. Observe how only a single disable refresh button is shown during search
4. Observe how two Refresh buttons are shown when the search finishes
5. Observe that the right one doesn't seem to initiate refresh (no loading indicator)

![image](https://user-images.githubusercontent.com/6831144/56646530-0b1fef00-6680-11e9-9a69-2204a614cfb7.png)

I don't know if this happens without extensions disabled, nor do I know if this is TypeScript specific, nor do I know if it happens in Insiders, haven't had time to check.

**Comment by jrieken** [comment]
I have never seen something like that... @TomasHubelbauer what are those other icons? Where does this magnifier icon come from? Is that another viewlet/extensions?

cc @sandy081

**Comment by TomasHubelbauer** [comment]
Oh shoot, these are from one of my own extensions! I am sorry, not sure how that didn't connect before I posted this 🙄 How did they find their way into this viewlet though? Should it be possible to contribute buttons here programatically?
