### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms

### ISSUE THREAD

**Issue by 951565664** [Microsoft/vscode#72792]
![image](https://user-images.githubusercontent.com/22285404/56640896-aa57dd00-66a6-11e9-8b25-21ade13dd657.png)

Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:7446).

```js
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "test",
                "Image"
            ],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        },
    ]
```

I can get the results in the terminal, but I can't debug. Execution does not pause at the breakpoint. I promise to enter my breakpoint under normal circumstances.

![image](https://user-images.githubusercontent.com/22285404/56641556-2f8fc180-66a8-11e9-9a1a-4127ce61de5a.png)

The terminal printed 1111
![Uploading image.png…]()

**Comment by weinand** [comment]
With your launch configuration the VS Code node debugger will just add a "--inspect-brk=1234" to the arguments passed to npm:
```
  npm run test Image --inspect-brk=1234
```
This does not work since npm passes "--inspect-brk=1234" to "test" script and not to node.js.

The correct way to do this is documented here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools

**Comment by 951565664** [comment]
I added  `--inspect-brk=9229`, but I still get this error.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "test",
                "--inspect-brk=9229"
            ],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "port": 9229
        },
    ]
}
```

**Comment by 951565664** [comment]
In the terminal 
```bash
cd /Users/gp/code/image ; /usr/local/bin/npm run-script test --inspect-brk=9229 
```

**Comment by weinand** [comment]
The "--inspect-brk=9229" argument is still in the wrong place (it doesn't matter whether VS Code adds that argument implicitly or you add it explicitly).

I suggest this:
In your package.json add a new "debugtest" script:
´´´js
"scripts": {
    "debugtest": "node --nolazy --inspect-brk=9229 myProgram.js"
  },
´´´

And the use this launch config:
```js
{
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debugtest",
            ],
            "cwd": "${workspaceRoot}",
            "console": "integratedTerminal",
            "port": 9229
},
```

BTW, here is an old duplicate: #43093
