### ISSUE TITLE
'code' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Chawki726** [Microsoft/vscode#72796]
"code" commend doesn't work in my cmd. O/S windows.
![Capture](https://user-images.githubusercontent.com/42825498/56645492-690e0000-669b-11e9-8fe6-635a101903c1.PNG)

**Comment by polishedwp** [comment]
According to the [documentation](https://code.visualstudio.com/docs/editor/command-line), this setting is different for each OS. 
> Note: Users on macOS must first run a command (Shell Command: Install 'code' command in PATH) to add VS Code executable to the PATH environment variable. Read the macOS setup guide for help. Windows and Linux installations should add the VS Code binaries location to your system path. If this isn't the case, you can manually add the location to the Path environment variable ($PATH on Linux). For example, on Windows, VS Code is installed under `AppData\Local\Programs\Microsoft VS Code\bin`.

**Comment by Chawki726** [comment]
I fixed the issue:
setting the environment variable path to `C:\Users\chawki\AppData\Local\Programs\Microsoft VS Code\bin` fixed the issue, now I can open the vs code through cmd using the code commend
