### ISSUE TITLE
command 'python.setInterpreter' not found

### ISSUE THREAD

**Issue by EncoderPtd** [Microsoft/vscode#72790]
Issue Type: <b>Bug</b>

command 'python.setInterpreter' not found

After i updated VSCode it's self.
Type: `Python: SelectInterpreter`
And this was shown:
`command 'python.setInterpreter' not found`

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3220 @ 3.00GHz (2 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|9.92GB (4.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
restructuredtext|lex|106.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.4.11881
vscode-docker|Pet|0.6.1
vscode-yaml|red|0.4.0

</details>

**Comment by EncoderPtd** [comment]
At first i thought of my python env was broken, because i didn't find anywhere to select Anaconda env.
So, i have re-installed ALL MY PYTHON ENVIRONMENTS...^&^
And after i read the VSCode document, i tried the `Python: Select Interpreter`.

**Comment by EncoderPtd** [comment]
The problem was found in 

> VSCodeUserSetup-x64-1.33.1
And i rolled back to 
> VSCodeUserSetup-x64-1.32.3
the problem disappeared.

**Comment by EncoderPtd** [comment]
But the thing is... It automatically upgraded its self to 1.33.1 again. 
And the problem didn't appear! W

**Comment by netsesame2** [comment]
I got the same question today. All worked fine before I click to update.
So downgrade to 1.32.3, it works correctly.

**Comment by enify** [comment]
I got this problem too. Version 1.33.1

**Comment by xlla** [comment]
same issue here. 
and how to downgrade to 1.32.3?

**Comment by SwingWillwow** [comment]
same issue appears after upgrade, and fixed after downgrade.

**Comment by lvtao** [comment]
just get the extension of Python(ms-python.python) downgrade to 2019.3.6558
the problem disappeared.

**Comment by SwingWillwow** [comment]
> same issue here.
> and how to downgrade to 1.32.3?

just download the old version from here [](https://code.visualstudio.com/updates/v1_32) and install it.

**Comment by archtaurus** [comment]
Yeah, downgrade Python extension to ver.2019.3.6558 sovled this. And I disabled the extension auto upgrading for now.
It's not vscode's wrong, good!

**Comment by yanhuacuo** [comment]
> Yeah, downgrade Python extension to ver.2019.3.6558 sovled this. And I disabled the extension auto upgrading for now.
> It's not vscode's wrong, good!

thank you，this is  『Python extension's bug 』

**Comment by Tyriar** [comment]
Microsoft/vscode-python#5440, Microsoft/vscode-python#5439
