### ISSUE TITLE
VS Code DEBUG CONSOLE put the new line own way

### ISSUE THREAD

**Issue by rura6502** [Microsoft/vscode#72793]
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. run this my JAVA code
```java
public class StreamTest {
  public static void main(String[] args) {
    List<Integer> list =  Arrays.asList(1,2,3,4,5,6,7,8,9,10);
    for (int i : list) 
      System.out.print(i + ", ");
  }
}
```
2. DEBUG CONSOLE randomly put the new line own way like under. but when i tried to this in eclipse, there was no problem.
```
// example case 1
1, 2, 3,
4, 5, 6, 7, 8, 9, 10
// example case 2
1, 2, 3, 4, 5, 6, 7, 8, 9,
10,
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
This should be fxied in the latest vscode insiders https://code.visualstudio.com/insiders/

If you can still reproduce with latest vscode insiders let us know and we will reopen this issue
