### ISSUE TITLE
Add SVG language mode

### ISSUE THREAD

**Issue by karl20888** [Microsoft/vscode#728]

**Comment by Tyriar** [comment]
This has been mentioned in https://github.com/Microsoft/vscode/issues/375, would be great to see it happen in .svg and .html files.

**Comment by Tyriar** [comment]
Looking at the code, the first step towards this is probably to factor out XML-only logic from the HTML code to XML (closing tags, tokenizing, etc.) and have HTML extend that. SVG can then extend XML in the same way HTML does.

**Comment by iDev0urer** [comment]
Would be nice to also add svg support to html

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=jock.svg

It contributes a new svg language mode and basic completion support for svg files
