### ISSUE TITLE
Folding-Scrollbar (feature request)

### ISSUE THREAD

**Issue by top-master** [microsoft/vscode#72807]
## What?
I would like to request a feature (or extension, at least) for `VS Code`,
it should provide an additional scrollbar (from now on referred to as `folding-scroll`), which should be on the left side of the full-document scrollbar, I mean, the default scrollbar (we do not want to replace the original and default scroll-bar).

## Why?
Okay, consider a project where we have documents with thousand lines of code, and we just can't use the full-document scrollbar, basically, because unlike its name `scrollbar`, it just does jump around and we may get a headache, I mean, it is pretty useless, it should be called `jump-bar` (o_O)

## How?
The folding-scrollbar should be (and is) limited to only cover the area which is between the nearest (collapsible) folding, to be more precise:
   - when we are using it, we should only be able to scroll upwards until the previous `{` (the code-block start, optionally, even few lines above that until the brace is in the center would be nice; so that we see the `if` statement or function-name too).
   - and we should only be able to scroll downwards until the next `}` (the code-block end, optionally some lines after that as well).
   - and also, the folding-scroll should update the range that it covers once the user changes the text-cursor location in the document.
   - at last, the folding-scroll should also have down on its bottom a `lock-button` which gets red when locked, so that once it is locked, the user can place the text-cursor anywhere they want but the scrollbar does not update the range that it covers

### Preview:
Below is a small preview of how it should look, where you can see that I do not use the full-document scroll-bar, basically because it does NOT scroll, it would just jump away !!! (click on recording for more quality)

![recording2](https://user-images.githubusercontent.com/31405473/56658619-518d4200-66b0-11e9-8397-c6d76026aaf0.gif)

>**Note:** I did previously develop something like above for another IDE (namely `Qt-Creator`, where above recording comes from), and I would like to see something similar to above in the editor that I currently spend most of my time every day (namely `VS Code`)

**Comment by top-master** [comment]
I think it is different, because:
   - the `outline` is like a tree-view of links, that can navigate us to the first line of something (method, class and etc) which we need to already know by name; but once the method is found, there is no way to get a quick overview, except scrolling around, but like mentioned above that can be near impossible in some documents.
   - the `folding-scroll` is to move around easily inside of the large foldings (which could belong to anything), but not the outside structure (we got already `outline` for that)
   - when the user makes use of both `outline` and `folding-scroll` they may never get lost, even when their document has thousands of lines of code.
   - I do not think that the folding-scrollbar is hard to develop since the IDE has already folding support and keeps track of all code-blocks, and `folding-scroll` does not care what the folding is for (it needs not any extra logic or parser), it just allows scrolling inside already existing foldings

**Comment by aeschli** [comment]
Thanks for the suggestion but there are currently no plans for such a feature. I leave it open so other users can comment or vote.
