### ISSUE TITLE
GIt: Remote Changes Shelf

### ISSUE THREAD

**Issue by spmeesseman** [Microsoft/vscode#72808]
For all the GREAT stuff in VSCode, I can't believe there isn't a "Remote Changes" shelf in the SCM view for Git repos (i.e. together with the "Changes" and "Staged Changes" shelves).  The 3rd party SVN extension has this feature, even the old dinosaur Eclipse has it.

I was even more confused when I didn't find a duplicate in the issues.  Am I missing something?  If I am, could someone please let me know what do Git users do in VSCode (admittedly I am coming from CVS/SVN and am new to Git) to see remote changes? (without using the 3rd party plugin GitLens which is not easy to navigate with all the clutter).  I assume people just don't 'sync' or 'pull' blindly without knowing what changes are coming in?

![remote_changes_req](https://user-images.githubusercontent.com/48744816/56658667-35b27d80-6669-11e9-90fb-87a5c806eb69.png)

**Comment by joaomoreno** [comment]
"Remote changes" simply isn't a useful concept in most Git workflows. People usually fetch to see the remote changes and then merge/rebase on demand. Most people simply sync/pull.

I recommend checking out GitLens: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

**Comment by spmeesseman** [comment]
GitLens is nice but it does not compare to the convenience of having it in the SCM view, but my point being you are already doing a fetch with the "autofetch" feature, it displays how many commits are on the remote side, it would be extremely useful to be able to see the results of that fetch, and see the diffs, "in the SCM View".  Am I missing something?  Would you accept a pull request if I did this myself?
