### ISSUE TITLE
SCM panels flip order

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#72802]
Issue Type: <b>Bug</b>

since yesterday update, the SCM panels flip order, moving the repo one jump to the bottom and the code changes one jump to the top.

I have scm.providers.visible enabled
#70065

VS Code version: Code - Insiders 1.34.0-insider (63c1ff218ecf3c2b3df8df1eab8e963d3c1f1a50, 2019-04-24T06:06:38.011Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_3773337|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|3.0.38
vscode-icontheme-nomo-dark|be5|1.3.6
better-toml|bun|0.3.2
terraform|mau|1.3.9
markdown-shortcuts|mdi|0.11.0
prettify-json|moh|0.0.3
python|ms-|2019.4.11881
powershell|ms-|1.12.1
vscode-docker|Pet|0.6.1
errorlens|Phi|1.1.3
code-settings-sync|Sha|3.2.9
vscode-nginx|sha|0.6.0
sort-lines|Tyr|1.8.0
vscode-icons|vsc|8.6.0

</details>

**Comment by joaomoreno** [comment]
You can move them around using drag and drop and they will remember their location.

**Comment by FernandoMiguel** [comment]
I have one hundred scm modules on this project alone, more in on other directories
I would have to go into each of them every time I open a new project (I don't save workspaces) 

This is a breaking change and feels like a big ux change (can't find anything in the release notes about the reasoning. 

Can we either revert this or have a toggle option to keep it at top or bottom?
