### ISSUE TITLE
ESC closes terminal.

### ISSUE THREAD

**Issue by thepont** [Microsoft/vscode#7280]
- VSCode Version: 1.2.0
- OS Version: Linux 4.4.0-22-generic #40-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

Escape is bound to close the new terminal window feature, this is frustrating since some terminal applications use escape as a key to do certain things ( such as escape the application ).

I am now stranded in vim, with no way of getting out within my embedded terminal.

Steps to Reproduce:
1.  Open a terminal.
2. Press ESC.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6455, coming in the next release :)

**Comment by thepont** [comment]
Cheers!
