### ISSUE TITLE
不能挑选python的运行环境

### ISSUE THREAD

**Issue by lwhluvdemo** [Microsoft/vscode#72806]
Issue Type: <b>Bug</b>

在VS code最下面的信息栏中，我找不到选择python环境的选项，或者说它隐藏起来了，但是我找不到，以至于我需要从终端启用我的虚拟环境，这很繁琐。
而且当我打开一个项目时，它的底栏都是空的，不显示任何信息。
卸载重装也没有解决问题。

同时，当我启动Azure Machine Learning拓展时，它通知我command 'vscodeai.view.azureml.refresh' not found错误，我不知道该怎么解决它。

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0
vsc-material-theme|Equ|2.8.2
vscode-npm|fkn|3.3.0
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|6.4.0
vscode-language-pack-zh-hans|MS-|1.33.2
mssql|ms-|1.6.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.4.11881
vscode-ai|ms-|0.4.5
azure-account|ms-|0.8.2
azurecli|ms-|0.4.5
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vscode-yaml|red|0.4.0

</details>

**Comment by wk-mike** [comment]
我也用同样的问题，刚刚3台电脑都出现了同样的问题。
环境是anaconda3 5.3.1 ，win10
vscode按ctrl+F5没办法运行。

**Comment by jrieken** [comment]
Please file issues in English. Thanks!

**Comment by wk-mike** [comment]
I think i fix this problem.
delet last commoa in this file.   C:\Users[username].vscode\extensions\ms-python.python-2019.4.11881\package.nls.[language].json." 

引用github大神提供的方法:去掉 "C:\Users[username].vscode\extensions\ms-python.python-2019.4.11881\package.nls.[language].json."文件中最后一个逗号可以解决
或者在扩展右下角齿轮选下载之前的版本
