### ISSUE TITLE
Color appears wrong without --disable-gpu (slightly different from hex values)

### ISSUE THREAD

**Issue by Servail** [microsoft/vscode#72809]
Issue Type: <b>Bug</b>

Somehow, colors which I set in editor.tokenColorCustomizations displays wrong (probably not only these), it's noticeable on #0000ff (it must be blue, but appears purple-ish). To test it, I've done following steps.

Steps to reproduce:
1. Set color for any element (e.g. example "variables":"0000ff")
![изображение](https://user-images.githubusercontent.com/45024837/56657783-93fb5280-66a1-11e9-806f-6e40cd563124.png)
2. Make screenshot with that element (I've used PrintScreen).
![изображение](https://user-images.githubusercontent.com/45024837/56657883-cefd8600-66a1-11e9-9f76-dccf30b28fb3.png)
3. Open in graphic editor (I've used MS Paint and pasted to it).
4. Pick that element's color with Color Picker tool and check it - it's different color (not blue as expected to be)! 
![изображение](https://user-images.githubusercontent.com/45024837/56657941-f94f4380-66a1-11e9-9a34-653a38dcde7a.png). 
But when I launch VSCode with --disable-gpu, issue is fixed somehow. 
<details>
Even grayscale colors are broken (e.g. midrange #808080 hex is 107,107,107 rgb). Seems like weird gamma issue, but I've tweaked graphics card (AMD Radeon HD 5700) gamma and relaunched VSCode - same result (but more noticeable at higher gamma), same numbers. (Maybe it's windows color profile issue?)
</details>

Does this issue occur when all extensions are disabled?: Yes
Reproducible in Insider build?: Yes

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6500 APU with Radeon(tm) HD Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.91GB (1.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.1
vscode-great-icons|emm|2.1.44
eppz-code|epp|1.2.41
vscode-fold|fel|1.4.3
godot-tools|gee|0.3.7
unity-code-snippets|kle|1.3.0
csharp|ms-|1.19.0
vscode-yaml|red|0.3.0
shader|sle|1.1.4

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by Servail** [comment]
> I wonder if this issue reproduces with one of these builds
No, it's fixed in these. Color works as expected.

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
