### ISSUE TITLE
Intergrated Terminal LetterSpace Of Chinese Words

### ISSUE THREAD

**Issue by zjruan** [Microsoft/vscode#7281]
- VSCode Version:1.2
- OS Version: Windows10 Chinese Language

Steps to Reproduce:

1.  `` Ctrl + ` `` to open Intergrated Terminal
2.  ` ipconfig ` show ipaddress  
![TestImg](http://zjruan.com/sources/TestImg.png)

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7062
