### ISSUE TITLE
Automatically moves cursor location

### ISSUE THREAD

**Issue by gohar94** [Microsoft/vscode#72819]
Issue Type: <b>Bug</b>

After I am done typing sometimes I experience my cursor having moved to a different location automatically. I am using the vim extension (have been using it for a long time) - it might be related to that but this issue is fairly recent.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (10.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
todo-tree|Gru|0.0.129
vscode-nmake-tools|Mic|2.0.190403001
theme-monokai-pro-vscode|mon|1.1.12
cpptools|ms-|0.22.1
powershell|ms-|1.12.1
code-settings-sync|Sha|3.2.9
vim|vsc|1.4.0

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This issue is without actionable information. Please update after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
