### ISSUE TITLE
Notifications Toolip - Heading Text cut in half

### ISSUE THREAD

**Issue by LikaBAU5za** [Microsoft/vscode#72817]
Issue Type: <b>Bug</b>

1. Install vs code.
2. Install GIT.
3. Click on notifications' icon (bottom right, blue bar).
4. Clear notifications.
5. Click on notifications' icon again.

The heading text is being cut off horizontally what seems to be too much padding-top.

![image](https://user-images.githubusercontent.com/22576295/56678239-7d192800-66c2-11e9-89c2-6d39118ec63f.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.27GB free)|
|Process Argv|C:\Users\USER\source\repos\NgApp1\NgApp1|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
@LikaBAU5za I assume this does not reproduce easily or does it?

**Comment by LikaBAU5za** [comment]
Hi bpasero,

No I don't think it does reproduce easily, decided to report it with as much information as I have available.  If there's anything else you need, I'll gladly help.

**Comment by bpasero** [comment]
Ok closing until we have reliable steps how to reproduce.
