### ISSUE TITLE
Weird scolling going on in latest version of the debug console

### ISSUE THREAD

**Issue by richtera** [Microsoft/vscode#72818]
Issue Type: <b>Bug</b>

It has some improvements now I can copy sections and so on, but it's now no longer automatically scrolling to the bottom. In fact when I do scroll it to the bottom it flickers up to some random location when output is added to the console and then I have to scroll it down again. Something is messed up there.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-jq|dan|1.0.0
vscode-jq-playground|dav|2.0.1
gitlens|eam|9.6.3
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.8.1
code-runner|for|0.9.8
gc-excelviewer|Gra|2.1.32
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
python|ms-|2019.4.11881
Go|ms-|0.10.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
sass-indented|rob|1.5.1
gitconfig|sid|2.0.0
mdx|sil|0.1.0
quokka-vscode|Wal|1.0.209

(8 theme extensions excluded)

</details>

**Comment by adnanberberovic** [comment]
I have this problem too. I don't know if it's relevant but I've only been programming with Python in VSC, so maybe it's specific to the Python debug console? I see that @richtera is also using Python (perhaps something else too). 

@Tyriar @isidorn: Is there any information I can provide for easier troubleshooting?

**Comment by isidorn** [comment]
Fixed in latest vscode insiders

**Comment by adnanberberovic** [comment]
Works perfectly in insiders. Thanks @isidorn

**Comment by isidorn** [comment]
Great, thanks!
