### ISSUE TITLE
unsigned test RPM contaminating yum repo

### ISSUE THREAD

**Issue by discard-this** [Microsoft/vscode#72827]
There's an unsigned RPM in your yum repo dated from March, 2019:

test_1.0.x86_64.rpm                                13-Mar-2019 23:40               87802

Name        : hello
Version     : 2.8
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 225689
License     : GPLv3+
Signature   : (none)
Source RPM  : hello-2.8-1.src.rpm
Build Date  : Fri 19 Feb 2016 11:07:07 AM PST
Build Host  : chuanliu1.corp.microsoft.com
Relocations : (not relocatable)
Summary     : The "Hello World" program from GNU
Description :
The "Hello World" program, done with all bells and whistles of a proper FOSS
project, including configuration, build, internationalization, help files, etc.
* Fri Feb 19 2016 AzLinux <azlinux@microsoft.com> 2.8-1
- Initial version of the package
ORG-LIST-END-MARKER

If this badly-named RPM is really supposed to be there please rename it to reflect what it really is and GPG sign it. If it isn't supposed to be there please remove it so yum will stop complaining about it.

thanks,
nomad

**Comment by Tyriar** [comment]
Thanks, I let the repo admins know.
