### ISSUE TITLE
Can we have editor.acceptSuggestion as list of keys?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#7282]
Instead of editor.acceptSuggestionOnEnter. I would like to have something like this

```JSON
{
    "editor.acceptSuggestion" : ["Enter" , "Tab" , "Space" ]
}
```
or maybe

```JSON
{
    "editor.acceptSuggestion" : { "Enter" : true, "Tab" : false }
}
```
This can be used to inherit from default

**Comment by jrieken** [comment]
You can bind any key/keys to the `acceptSelectedSuggestion` command using the keyboard configuration story. For details see: https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts

**Comment by Thaina** [comment]
@jrieken Yes we can bind key by ourself. So `acceptSuggestionOnEnter` is duplicated

So I would like to have it only one for all key. And I think `acceptSuggestionOn` is far more easier to edit. So I think we should have just `acceptSuggestion` instead

**Comment by jrieken** [comment]
Yes - it is duplicated but for a reason. That is until recently is was hard to 'undo' a keybinding. We recently added that: #612. The setting is only left to not break existing configurations.
