### ISSUE TITLE
Allow DocumentLinks to provide hover message

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#72824]
## Problem
The markdown document link provider creates document links that use command URIs. Currently these have a generic hover message in the editor:

![Screen Shot 2019-04-24 at 11 07 16 AM](https://user-images.githubusercontent.com/12821956/56682821-3951fe80-6681-11e9-9a5b-7d099a373575.png)

It'd be nicer if a message describing what the link does where shown, something like: `Open file. cmd+click to execute`

## Api
Two ideas on this

#### Allow DocumentLink to take a `Command` instead of URI

```ts
	export class DocumentLink {

		/**
		 * The range this link applies to.
		 */
		range: Range;

		/**
		 * The uri this link points to or a command executed when the document link is clicked.
		 */
		target?: Uri | Command;

		/**
		 * Creates a new document link.
		 *
		 * @param range The range the document link applies to. Must not be empty.
		 * @param target The uri the document link points to or a command executed when the document link is clicked.
		 */
		constructor(range: Range, target?: Uri | Command);
	}
```

This would let extensions to set a title or tooltip in the document link. 

```ts
new vscode.DocumentLink(new vscode.Range(0, 0, 0, 0), {
    title: 'Does thing when clicked',
    command: 'ext.doThing'
})
```

#### Add a title property on `DocumentLink`

```ts
	export class DocumentLink {
		/**
		 * Label for the document link shown in the UI on hover
		 */
               tooltip?: string;

		/**
		 * The range this link applies to.
		 */
		range: Range;

		/**
		 * The uri this link points to.
		 */
		target?: Uri;

		/**
		 * Creates a new document link.
		 *
		 * @param range The range the document link applies to. Must not be empty.
		 * @param target The uri the document link points to.
		 */
		constructor(range: Range, target?: Uri);
	}
```

**Comment by mjbvz** [comment]
Due to the two phase resolution we use for links (`provide` and then `resolve`) I think adding a title property makes the most sense here

**Comment by mjbvz** [comment]
For UX here, I believe we still want to show the shortcut used to click the link. A few ideas on this

### Option 1: put custom message above existing message

<img width="646" alt="Screen Shot 2019-05-23 at 2 23 22 PM" src="https://user-images.githubusercontent.com/12821956/58287706-94514100-7d66-11e9-99c8-d3e41a4bfdfa.png">

This makes it clear that you are executing a comment

### Option 2: put custom message inline

<img width="600" alt="Screen Shot 2019-05-23 at 2 26 17 PM" src="https://user-images.githubusercontent.com/12821956/58287790-c367b280-7d66-11e9-8dd9-4ce672f2b265.png">

(I'm not sure if this approach can be properly localized or not)


/cc @misolori

**Comment by misolori** [comment]
Definitely prefer Option 2 as it reads more naturally. Option 1 has an odd placement and you have to re-read it a few types to understand what it means.

**Comment by mjbvz** [comment]
Any concerns about localization? This string would have to be something like:

```
Cmd + click to {0}
```

Other languages could change the ordering but I'm just not sure if this will result in odd reading sentences

**Comment by misolori** [comment]
Hmm...do we do anything for localization in other parts of the product? If we know certain languages phrase words differently I could see us being smart enough to change that but I wonder how we handle these cases elsewhere.

**Comment by mjbvz** [comment]
I've pushed an api proposal that uses the second UX. One note, I renamed the property from `title` to `tooltip` since that is consistent with the term we for other hovers

**Comment by mjbvz** [comment]
Closing this since proposed api has been added. Created #74336 to track finalziation
