### ISSUE TITLE
Syntax highlighting for null conditional operator in JS ES7 showing error

### ISSUE THREAD

**Issue by ASteinheiser** [Microsoft/vscode#72820]
I am working on a React Native project using Babel ES7. They now support using the null conditional operator (ie. `object?.key`), however when I write this code, VSCode tells me that it will cause an error. When I run the code, it works as expected with no errors. This issue is purely with the syntax highlighting.

<img width="684" alt="Screen Shot 2019-04-24 at 10 40 25 AM" src="https://user-images.githubusercontent.com/9949512/56681229-bb402880-667d-11e9-94b9-0fc2c01b4755.png">

- VSCode Version: 1.33.1
- OS Version: MacOS 10.14.4

Steps to Reproduce:
1. Open VSCode
2. Create new react app (`create-react-app sample-app`)
3. Try the null conditional syntax, noting the error text highlighting
4. Run the app and see that the new syntax actually works

Does this issue occur when all extensions are disabled?: **Yes**

I have also tried using some Babel ES7 plugins for syntax highlighting to see if that would help. Here's what I've tried:
- https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring
- https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/16
