### ISSUE TITLE
For some reason, VSC will not show diff between these two files

### ISSUE THREAD

**Issue by sonatypeJimB** [microsoft/vscode#72823]
Issue Type: <b>Bug</b>

On **macOS**, download the following two files:

http://code.jquery.com/jquery-1.8.3.js
http://code.jquery.com/jquery.js

Then attempt to diff them, either thru the GUI ("Select to compare") or via CLI (code --diff jquery-1.8.3.js jquery.js).

Note that VSCode does not highlight any deltas.  The files open fine, but it doesn't show you any colorized changes.

This problem does not occur on another box I have that is running Linux, so it may be macOS specific.  I also have not had this issue with any other pairs of files, so there must be something about these files which is triggering some kind of issue?

Please note, the issue also occurs with all installed extensions disabled (--disable-extensions).

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.4.3
project-manager|ale|10.5.1
transformer|dak|1.6.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.6.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
code-runner|for|0.9.8
macros|ged|1.2.1
vscode-pull-request-github|Git|0.6.0
todo-tree|Gru|0.0.129
beautify|Hoo|1.4.11
vscode-pigments|jas|1.0.6
markdown-shortcuts|mdi|0.11.0
vscode-language-babel|mgm|0.0.22
vscode-postgresql|ms-|0.2.0
python|ms-|2019.4.11987
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
Go|ms-|0.10.0
powershell|ms-|1.12.1
java|red|0.43.0
vscode-yaml|red|0.4.0
autocomplate-shell|tru|0.1.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.2
vscode-icons|vsc|8.6.0
markdown-all-in-one|yzh|2.2.0

(1 theme extensions excluded)

</details>

**Comment by sonatypeJimB** [comment]
Added files in question in case upstream changes.
[jquery-diff-issue.zip](https://github.com/Microsoft/vscode/files/3113688/jquery-diff-issue.zip)

**Comment by bpasero** [comment]
Possibly too many diffs so we decide to not diff?

**Comment by sonatypeJimB** [comment]
Thanks for following up.  I wondered that, however a few other _subjectively_ large file comparisons didn't have issues.  And also there's the fact that it doesn't happen on my Linux system, just the macOS one.

If I can be pointed at a debug method or something that will deliver some kind of output or logging that would include any kind of "too large, abort" decision-making I'd be happy to give that a run.

**Comment by bpasero** [comment]
Actually for me on Windows I can compare the two files:

![image](https://user-images.githubusercontent.com/900690/56736554-bad08c00-6768-11e9-82d3-3664aaf797fc.png)

**Comment by sonatypeJimB** [comment]
Thanks for that.  What would be your advice for troubleshooting the issue on my system?

**Comment by alexr00** [comment]
I could actually compare both files with stable, but I verified that the experience is better with a progress bar.

**Comment by sonatypeJimB** [comment]
> I could actually compare both files with stable, but I verified that the experience is better with a progress animation.

While I had seen that the earlier change for skipping char diffs on 'huge chunks' was committed, after seeing your comment I tested again with the same files and sure enough, the diffing works as expected nowadays (1.39.2).

Thanks to everyone who contributed to this.
