### ISSUE TITLE
A highlighting bug

### ISSUE THREAD

**Issue by sweettyler** [Microsoft/vscode#72825]
Issue Type: <b>Bug</b>

1) start vscode by typing "code";
2) type the following lines:
int aGrid;
int mGrid;
3) save the file as "aaa.cc" and due to the bug the word "mGrid" is highlighted, which is not expected.

it seems this bug is related with the default color theme.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|187.41GB (32.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sweettyler** [comment]
don't know it was labeled as "integrated-terminal". it has nothing to do with that, so closed it.

**Comment by Tyriar** [comment]
This seems to be fixed in Insiders

**Comment by sweettyler** [comment]
@Tyriar : thanks and will try insider.
