### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by omnekkanti** [Microsoft/vscode#72833]
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: macosmojave 10.14.4

Steps to Reproduce:

1. install azure machine learning extension
2. run script using local target

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
This issue does not contain actionable information. Please update after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
