### ISSUE TITLE
Git revert changes not working (for ipynb files)

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#72837]
Issue Type: <b>Bug</b>

This seems to be a recent issue, I've not noticed it before but since updating to the latest vscode I'm seeing it regularly. 

On the SOURCE CONTROL: GIT sidebar, it's showing files are changed which I don't want to commit, so I right click "Revert Changes". The blue bar moves, and I can see in the Git output log that is done a `git checkout -q -- /home/david/dev/project/notebooks/examples.ipynb`

However the file still shows in the SOURCE CONTROL: GIT sidebar despite it having no changes (I'm don't believe it was ever changed, I've started seeing vscode report changes to for multiple ipynb files which I've not deliberately touched).

I have a feeling this is only happening with *.ipynb files (jupyter notebooks), these are text (json) files containing code and output. The difftool doesn't work for these files, so I wonder if that's the problem.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 1201)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.76GB (53.83GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.10
jedi|cya|0.1.0
vscode-markdownlint|Dav|0.26.0
githistory|don|0.4.6
gitlens|eam|9.6.3
git-project-manager|fel|1.7.1
flatbuffers|gab|0.1.0
vscode-test-explorer|hbe|2.9.3
rest-client|hum|0.21.2
latex-workshop|Jam|6.5.0
nbpreviewer|jit|1.2.2
rainbow-csv|mec|1.0.0
python|ms-|2019.3.6558
cpptools|ms-|0.23.0-insiders
csharp|ms-|1.19.0
vscode-docker|Pet|0.6.1
vscode-lldb|vad|1.2.2
vscode-icons|vsc|8.6.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|2.2.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by joaomoreno** [comment]
Is this maybe a line ending issue? https://help.github.com/en/articles/dealing-with-line-endings

**Comment by david-waterworth** [comment]
@joaomoreno thanks, potentially that's the problem. I'm generally the only user of the repo but I bounce between two linux machines - I'll check they're both configured the same.

**Comment by joaomoreno** [comment]
Let me know how it goes.

**Comment by david-waterworth** [comment]
@joaomoreno that did seem to work thanks.
