### ISSUE TITLE
Explorer auto scrolls to top

### ISSUE THREAD

**Issue by dilpazirahmad** [Microsoft/vscode#72839]
when you are at the bottom of explorer and open file then close it; the explorer will auto scroll to top;
then I again need to scroll to bottom to open another file in the same directory

**Comment by isidorn** [comment]
I can not reproduce, please try reproducing with latest vscode insiders https://code.visualstudio.com/insiders/
And if you can reproduce please let me know what are the exact reproducable steps so I get this on my machine. Thank you
