### ISSUE TITLE
"Illegal state: service accessor is only valid during the invocation of its target method" after attempting folder deletion

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#72830]
Issue Type: <b>Bug</b>

I just attempted to delete a folder from the file explorer and received this error message. FWIW the folder lives on an SMB share.

![Screen Shot 2019-04-24 at 4 57 46 PM](https://user-images.githubusercontent.com/226872/56701135-91552900-66b2-11e9-8a10-3f4afec76f06.png)

VS Code version: Code - Insiders 1.34.0-insider (63c1ff218ecf3c2b3df8df1eab8e963d3c1f1a50, 2019-04-24T06:06:38.011Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|-psn_0_12573693|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
dafny-vscode|cor|0.17.0
prettier-vscode|esb|1.8.1
reasonml|fre|1.0.38
vscode-pull-request-github|Git|0.6.0
Ionide-fsharp|Ion|3.35.0
python|ms-|2019.4.11987
csharp|ms-|1.19.0
Go|ms-|0.10.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.91
vscode-docker|Pet|0.6.1
vscode-graphql|Pri|0.1.7
rust|rus|0.6.1
crates|ser|0.4.2
vscode-scheme|sjh|0.4.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by isidorn** [comment]
Try it out in the next vscode insiders and let us know if this is fixed for you
