### ISSUE TITLE
JavaScript: Undefined block scope values after 5th call to "debugger" statement 

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/vscode#72834]
Issue Type: <b>Bug</b>

I'm on the Microsoft Bot Framework Team and we've added a debugBreak() command to our SDK that helps simplify debugging a bot using VS Code.  When a developer enables debugging for their bot we'll call the debugBreak() method below at key points within the framework to let the developer inspect the current state of memory within their bot.

The code below works great the first 5 times its called but from the 6th time on it shows "undefined" for all of the variables above the "debugger" statement.  If I set an actual breakpoint on that line everything works fine. I can tell devs to set a breakpoint there as a work around but it would be great if we could get this fixed in a future build.

```
    public debugBreak(event: string, target?: any): void {
        if (this.shouldBreak(event)) {
            const _dialog = this.getCurrentDialog();
            const _dialogPath = this.getDialogPath();
            const _event = event;
            const _memory = this.state.toJSON();
            const _sequence = this.getSequence();
            const _target = target;
            debugger;
        }
    }
```

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (18.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.8
code-spell-checker|str|1.7.4

</details>

**Comment by Stevenic** [comment]
It seems like this issue could be related to #72510

**Comment by isidorn** [comment]
Please create a repository on github which we can clone and reproduce this on our machines.
With the current description you provided we can not get this on our machine.

**Comment by weinand** [comment]
@isidorn I can easily reproduce the problem "with the current description":

```ts
function debugBreak(event: string, target?: any): void {
    if (true) {
        const _dialog = "abc"; // this.getCurrentDialog();
        const _dialogPath = "bar"; // this.getDialogPath();
        const _event = event;
        //const _memory = this.state.toJSON();
        //const _sequence = this.getSequence();
        //const _target = target;
        debugger;
    }
}

debugBreak("foo");
debugBreak("foo");
debugBreak("foo");
debugBreak("foo");
debugBreak("foo");
```

On 5th step I see this:

![2019-04-25_17-03-09](https://user-images.githubusercontent.com/1898161/56746358-57e8f000-677c-11e9-8ee9-5044859cdeef.png)

**Comment by weinand** [comment]
Further investigation showed that this problem does not occur for the node-legacy debugger. So most likely it is not a front-end problem.

**Comment by isidorn** [comment]
Thanks for the nice steps.
Yes I can reproduce this. The variables are coming from the debug adapter thus forwarding to @roblourens 

![Screenshot 2019-04-25 at 17 13 41](https://user-images.githubusercontent.com/1926584/56747125-b19dea00-677d-11e9-9493-271d3fae844b.png)

**Comment by roblourens** [comment]
Since those variables aren't referenced in the scope, v8 will sometimes dispose them. I see the same debugging with chrome devtools, so there's nothing we can do on our end. 

You can log the variables, or add some other reference to them, or move the breakpoint to work around it.

**Comment by Stevenic** [comment]
Thanks for looking into this. I was wondering if it was related to the fact I wasn't referencing them. I'll rework things so that I log them...
