### ISSUE TITLE
Develop kits` wrong

### ISSUE THREAD

**Issue by zeewane** [Microsoft/vscode#7283]
- VSCode Version:1.2.0
- OS Version:win10pro  10586.318

Steps to Reproduce:

1. 切换开发人员工具
2. 点击移动视图
3. 关闭开发人员工具
4. 提示遇到异常需要关闭

**Comment by alexandrudima** [comment]
@zeewane I've used Google Translate and here is what it translates to:
Switching Developer Tools
Click Mobile view
Close Developer Tools
Tip exception is encountered and needs to close

However, I do not understand the steps...

**Comment by dbaeumer** [comment]
No response received from issue creator. Closing after 14 days
