### ISSUE TITLE
Build tasks hangs 3 out of 4 times

### ISSUE THREAD

**Issue by skadefro** [Microsoft/vscode#72847]
Issue Type: <b>Bug</b>

After installing "Feature update to Windows 10, version 1809 amd64 19-‎04-‎2019" i need to kill and restart build tasks several times. 
Also tested on a latest insider build

I suspect its related to either of these issues, since I'm at the same time started experiencing issues with my consoles being full of blanks ( including the build window)
#59899 #57803 #43169 and
https://github.com/rprichard/winpty/issues/152
https://github.com/cbucher/console/issues/501
https://github.com/cbucher/console/issues/511

![image](https://user-images.githubusercontent.com/4155937/56718697-898f9600-673f-11e9-82f1-da2b33f77b01.png)
![image](https://user-images.githubusercontent.com/4155937/56718746-acba4580-673f-11e9-98c9-00141f0f40ec.png)

VS Code version: Code - Insiders 1.34.0-insider (0fde6619172c9f04c41f2e816479e432cc974b8b, 2019-04-25T05:24:52.804Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
