### ISSUE TITLE
vs code IntelliSense have a problem 

### ISSUE THREAD

**Issue by eizo2200** [microsoft/vscode#72840]
How to close this prompt，Intelligent Tips for JS Files doesn't work
![image](https://user-images.githubusercontent.com/29911043/56711423-50feb500-675d-11e9-82b7-31146a41b4ac.png)
Folding code is no longer available

![319936A9-23AC-4b10-8CFB-E6B66ED9C554](https://user-images.githubusercontent.com/29911043/56713732-316b8a80-6765-11e9-8dd1-a15256f7bd59.png)

**Comment by eizo2200** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

How to close this prompt，Intelligent Tips for JS Files doesn't work
image
Folding code is no longer available

319936A9-23AC-4b10-8CFB-E6B66ED9C554

**Comment by mjbvz** [comment]
Please follow the [issue reporting](https://aka.ms/vscodeissuereporting) guidelines to provide steps to reproduce the issue and basic information about the project you are opening

**Comment by mjbvz** [comment]
Closing as more information is needed about the what the issue issue is and how to reproduce it
