### ISSUE TITLE
Markdown Preview not handling a specific kind of line break

### ISSUE THREAD

**Issue by skprabhanjan** [Microsoft/vscode#72846]
@mjbvz , While i was creating a test file for checking #72671, I found that line breaks are not added in the preview for the kind of file I created. 
Just for your info , this is how I created using terminal
```
for ((i=1;i<=10;i++));                                                                                                                                             
do
   echo "Hello World $i" >> testSmallMdfile.md
done
```
Please confirm if we have to take care of this ? ( I can fix this if you can guide me :) )

Attaching screenshot for further reference.

<img width="1440" alt="Screen Shot 2019-04-25 at 12 57 00 PM" src="https://user-images.githubusercontent.com/17094832/56717394-35de7600-675a-11e9-89c2-1dd2dc9bfe7a.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is how markdown handles line breaks. To separate lines, you either need a double line break or end the line with two spaces
