### ISSUE TITLE
Unable to run code normally

### ISSUE THREAD

**Issue by solidsickle** [Microsoft/vscode#72843]
Issue Type: <b>Bug</b>

Hello ,  i am unable to run my code properly when i press Fn + F5 and theres breakpoint thing that keeps appearing whenever i run my program

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (9.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
htmltagwrap|bra|0.0.7
code-runner|for|0.9.8
live-html-previewer|hdg|0.3.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details>

![image](https://user-images.githubusercontent.com/29114103/56715377-151e1c80-676a-11e9-9686-0858535378d7.png)

**Comment by isidorn** [comment]
File > open folder. Then everythign should work as the info message in the corner says
