### ISSUE TITLE
Search files with type - string, symbol, integer, variable, ...

### ISSUE THREAD

**Issue by lopun** [Microsoft/vscode#72848]
I want to search files with specific type(language dependent).
```typescript
// For Example
const someFunc123 = 'searching some stuff'  // 1st line
console.log('someFunc123')  // 2nd line
console.log('someFunc', 123)  // 3rd line
```
Search results by search param and type
- param: 123, type: integer => 3rd line
- param: someFunc, type: string => 2nd line, 3rd line
- param: someFunc, type: variable => 1st line

**Comment by roblourens** [comment]
Our search is a basic text search and it's not really practical for us to add any language-specific filtering or parsing.
