### ISSUE TITLE
Interface zooming delta is way too big

### ISSUE THREAD

**Issue by gubikmic** [microsoft/vscode#72841]
When zooming the interface via `⌘+`/`⌘-` (or `^+`,`^-` respectively) the increments/decrements are very big. This is unfortunate. Repeating the same keypress a few times in a row is very low effort vs. the inability to more finely select the right font size quickly is a big penalty.

I propose to decrease the zoom delta.

**Comment by usernamehw** [comment]
Achievable with extensions that can manipulate Settings, like [Run Commands View](https://marketplace.visualstudio.com/items?itemName=usernamehw.run-commands-view)

```json
{
	"key": "ctrl+=",
	"command": "-workbench.action.zoomIn"
},
{
	"key": "ctrl+-",
	"command": "-workbench.action.zoomOut"
},
{
	"key": "ctrl+=",
	"command": "run-commands-view.incrementSetting",
	"args": {
		"setting": "window.zoomLevel",
		"value": 0.5
	}
},
{
	"key": "ctrl+-",
	"command": "run-commands-view.decrementSetting",
	"args": {
		"setting": "window.zoomLevel",
		"value": 0.5
	}
},
```
