### ISSUE TITLE
Possible to force indentation size when auto detected is wrong?

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#72851]
Issue Type: <b>Bug</b>

I've already configured java files to use `tabSize: 4`, as in my user settings.json:

```json
  "[java]": {
    "editor.insertSpaces": false,
    "editor.tabSize": 4
  }
```
But for one of the java files, it's always displayed as if tabSize is `8`, I think this is because "Detect Indentation from Content" isn't working as expected.

### Expectation
I believe the algorithm can be improved, but I think the bigger problem here is, there needs to be an option for me to force the indentation size when the algorithm isn't right.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
vsc-rustfmt|Con|0.1.0
vscode-eslint|dba|1.8.2
vscode-instant-markdown|dba|1.4.3
xml|Dot|2.4.0
gitlens|eam|9.6.3
prettier-vscode|esb|1.8.1
vscode-reveal|evi|3.4.0
shell-format|fox|4.0.5
gc-excelviewer|Gra|2.1.32
contextualduplicate|laf|0.2.0
Kotlin|mat|1.7.0
rainbow-csv|mec|1.0.0
prettify-json|moh|0.0.3
python|ms-|2019.4.11987
cpptools|ms-|0.22.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.91
vsliveshare-audio|ms-|0.1.50
vscode-boot-dev-pack|Piv|0.0.8
vscode-manifest-yaml|Piv|1.6.0
vscode-spring-boot|Piv|1.6.0
material-icon-theme|PKi|3.7.0
ruby|reb|0.22.3
java|red|0.43.0
vscode-yaml|red|0.4.0
rust|rus|0.6.1
vscode-cds|SAP|1.1.1
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.2.9
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5

(1 theme extensions excluded)

</details>

**Comment by ryenus** [comment]
OK, I found the option `"editor.detectIndentation": false`, which make this a lower-priority request, but I think that should be the last resort rather than the solution.

**Comment by KillyMXI** [comment]
I think something was broken in indentation detection recently.
I've seen multiple complains about Python code and I got issues with F# code myself.
Even if the file has indentation of 4 spaces, VSCode autodetection thinks it is 8.

I think detection has to be fixed first.

**Comment by ablakey** [comment]
Yeah I'm getting issues where tabSize is seemingly ignored.  Right now typescript is getting 4 spaces despite these settings:

```
{
  "[typescript]": {
    "editor.tabSize": 2,
  },
  "editor.tabSize": 4,
  "editor.detectIndentation": false,
}
```

**Comment by alexandrudima** [comment]
@ryenus @KillyMXI @ablakey

The indentation detection uses a heuristic where it counts spaces and tries to guess what the intent was. If you find that the detection code guesses wrong, then please create an issue with the file that is guessed wrong, or a similar file where you have replaced the code with `x`, in fact only the first letter of each line is relevant (to figure out how many leading spaces are on each line), otherwise I cannot improve the guessing logic...
