### ISSUE TITLE
Remove folder from the current one-folder workspace

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#72858]
How do I remove the current folder from a one-folder workspace?

Multiple times I've needed to check how an extension behaves when there are no folders in the current workspace, and I haven't yet found a good way to get in that kind of environment.

**Comment by bpasero** [comment]
@fabiospampinato you cannot without a window reload, e.g. File > Close Folder.

**Comment by fabiospampinato** [comment]
`File  -> Close Folder` is exactly what I was looking for, thanks 👍
