### ISSUE TITLE
ExtensionHost themselves consumes 1,8 GB

### ISSUE THREAD

**Issue by Floyddotnet** [Microsoft/vscode#72856]
Issue Type: <b>Performance Issue</b>

I don't know how to repduce this but this error repeats after each restart of visual studio code.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3502)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.70GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   115	 15736	code main
    0	   235	  5432	   window (OnlineAntrag.ts - PublicWebApi - Visual Studio Code)
    0	     5	   204	     winpty-process
    0	     3	  7584	       C:\Windows\system32\cmd.exe
    0	     6	  9896	       console-window-host (Windows internal process)
    0	    15	 14916	     watcherService 
    0	     4	  3596	       console-window-host (Windows internal process)
    0	  1868	 16076	     extensionHost
    0	    28	  8852	       electron_node Server.js 
    0	    34	 15508	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=16076
    0	    45	 16248	       electron_node eslintServer.js 
    0	   246	 17312	       electron_node tsserver.js 
    0	    42	 16396	         electron_node typingsInstaller.js typesMap.js 
    0	    19	  6424	   utility
    1	    71	 14740	   window (Process Explorer)
    0	    77	 14828	   shared-process
    0	   203	 15276	   window (● debug_helper.http - RESTClient - Visual Studio Code)
    0	    11	    32	     electron-crash-reporter
    0	   130	  2452	     extensionHost
    0	    27	  6804	       electron_node Server.js 
    0	    29	 14488	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=2452
    0	    12	  3808	     watcherService 
    0	     4	 11224	       console-window-host (Windows internal process)
    0	    63	 16748	   window (Issue Reporter)
    0	    81	 16896	   gpu-process
    0	    55	 17584	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● debug_helper.http - RESTClient - Visual Studio Code)
|  Window (OnlineAntrag.ts - PublicWebApi - Visual Studio Code)
|    Folder (RESTClient): 6 files
|      File types: http(6)
|      Conf files:
|    Folder (PublicWebApi): 3576 files
|      File types: dll(1477) bin(1195) pdb(169) cs(134) json(118) cache(115)
|                  sst(92) dat(47) txt(45) xml(24)
|      Conf files: csproj(11) package.json(1) sln(1) tsconfig.json(1)
|                  settings.json(1);
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.18.2
gitignore|cod|0.6.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.8
rest-client|hum|0.21.2
output-colorizer|IBM|0.1.2
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
TypeScriptImport|kev|1.17.0
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.2.1
prettier-now|rem|1.4.9
sass-indented|rob|1.5.1
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by jrieken** [comment]
no actionable information provided
