### ISSUE TITLE
Colour theme is being displaying too light

### ISSUE THREAD

**Issue by nomad-software** [microsoft/vscode#72859]
Issue Type: <b>Bug</b>

I'm using a custom colour theme that I wrote myself to customise the editor's colours and when loaded the background colour (and perhaps others) is incorrectly displayed. It seems too light.

Here is my colour theme:

https://github.com/nomad-software/vscode/tree/master/freya-theme

In that colour theme the background colour is defined as:
```
"editor.background": "#2A2A2A",
```
But when screenshotted and measured in GIMP it's `#2E2E2E`.

In other editors such as Vim it displays correctly.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.4.0-146-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4087)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.36GB (26.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
php-intellisense|fel|2.3.10
file-icons|fil|1.0.17
Go|ms-|0.10.1
sort-lines|Tyr|1.8.0
vim|vsc|1.4.0

(1 theme extensions excluded)

</details>

**Comment by nomad-software** [comment]
This still occurs on VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)

**Comment by aeschli** [comment]
We set the RGB to the DOM or styleheet and that's how the Chromium engine(part of Electron) renders it.

**Comment by nomad-software** [comment]
> We set the RGB to the DOM or styleheet and that's how the Chromium engine(part of Electron) renders it.

Well, something's going wrong somewhere because it's not correctly displaying the color.

**Comment by aeschli** [comment]
Color rendering is a complex topic. The Chromium engine renders the colors based on your monitor's color profile monitor. I don't know what VIM does.
To make sure this is not caused by VSCode, I opened the following html-page in Chrome and verified that there are no color rendering differences. I did it on Ubuntu 18.04.3 LTS.

```
<html>
    <body style="background-color: #2A2A2A"></body>
</html>
```
If you are convinced that it's wrong what Chrome does, please file an issue against Chromium.

**Comment by nomad-software** [comment]
Chromium isn't the issue as that renders fine as you have demonstrated.

Change your vscode background to:
```
"editor.background": "#2A2A2A",
```
then screenshot it, then measure it.

vscode (and only vscode) doesn't display as `#2A2A2A`. Every other application or editor displays it fine.

**Comment by nomad-software** [comment]
I've just tested it again and screenshotted a load of applications, including the webpage you posted above. All display properly as `#2A2A2A` apart from vscode.

**Comment by nomad-software** [comment]
Ok, I've just update to the latest version of vscode and it's fixed! It looks like something has been changed in the newer version. Nevermind, alls good now.
