### ISSUE TITLE
Code Folding for Dart doesn't include closing brace

### ISSUE THREAD

**Issue by madqueendany** [microsoft/vscode#72855]
Issue Type: <b>Bug</b>

1. Open a Flutter application
2. Fold code with `CMD+K` & `CMD+1`

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|2.25.1
flutter|Dar|2.25.1
gitlens|eam|9.6.3
pubspec-assist|jer|0.3.4
awesome-flutter-snippets|Nas|2.0.2
material-icon-theme|PKi|3.7.0
vscode-spotify|shy|3.1.0
vscode-icons|vsc|8.6.0
vim|vsc|1.4.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by DanTup** [comment]
The Dart extension does its own folding ranges, so I think this should be raised at https://github.com/Dart-Code/Dart-Code.

**Comment by DanTup** [comment]
Thoguh FWIW, the behaviour in Dart seems to match TypeScript... That also doesn't seem to include the closing brace in the collapsed range (though I think VS Code also only supports line-level ranges for the collapse, not characters?)

**Comment by aeschli** [comment]
Yes, needs to be filed against https://github.com/Dart-Code/Dart-Code..
Yes, the editor only supports folding at the line level (the API is ready for more).
