### ISSUE TITLE
Path Autocomplete abnormity

### ISSUE THREAD

**Issue by PLQin** [microsoft/vscode#72854]
Issue Type: <b>Bug</b>

I don't think it's a question of expansion ,  vscode will automatically complete the path for me , But it's bad : 

It completes the wrong path , 
I have a GIF, see it at the end

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (4.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
markdown-table-formatter|fcr|1.4.1
todo-tree|Gru|0.0.129
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
code-beautifier|mic|2.2.1
vscode-language-pack-zh-hans|MS-|1.33.2
LiveServer|rit|5.6.1

</details>

**Comment by PLQin** [comment]
![2](https://user-images.githubusercontent.com/24371471/56731365-e2d1e680-678c-11e9-88a3-27c942ef30ef.gif)

**Comment by PLQin** [comment]
ooo,  为了避免引起误会, 我删除了 packages 目录下的 node_modules 目录,  并且禁用了大部分的插件
To avoid confusion, I removed the `node_modules` directory under the `packages` directory and disabled most plug-ins ;

I also restarted vscode ;

![3](https://user-images.githubusercontent.com/24371471/56731833-08132480-678e-11e9-9d71-9e2a57fdc0ed.gif)

**Comment by PLQin** [comment]
I like its features(Path Autocomplete) and hope it can do better.  hope this problem can be solved as soon as possible ;

**Comment by mjbvz** [comment]
Can you share an example project that shows this problem?

**Comment by plqin-xiaohao** [comment]
Can't it be reproduced? Let me look at some examples

**Comment by mjbvz** [comment]
Closing as we need a small example project or at least more information about the project structure from the original poster to investigate this
