### ISSUE TITLE
Please provide a terminal shortcut button in the bottom bar

### ISSUE THREAD

**Issue by muyu66** [Microsoft/vscode#72852]
Although the shortcut is very convenient, if you provide a terminal shortcut button in the bottom bar, I think it should be more perfect.

![image](https://user-images.githubusercontent.com/20837526/56728438-5cfe6d00-6785-11e9-91cb-6ce55b01c271.png)

**Comment by Tyriar** [comment]
We've explored this in the past but decided against it for now, in the meantime you can easily make an extension to give you a toggle terminal button in the status bar.
