### ISSUE TITLE
Git bash shell was opened in a standalone window instead of integrated on Windows

### ISSUE THREAD

**Issue by steven-qi** [Microsoft/vscode#7286]
- VSCode Version: 1.2.0
- OS Version: Microsoft Windows [Version 10.0.10240]

Steps to Reproduce:

1. Add the following to settings.json
```json
    // The path of the shell that the terminal uses on Windows.
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\git-bash.exe"
```
2. Close and re-open VSCode (so that the new settings.json would take effect).
3. Choose ```View``` -> ```Toggle Integrated Terminal``` from menu.

In this case, the "TERMINAL" panel shows up but remains in blank, and the git bash shell was opened as a standalone window instead of integrated. Checkout the snapshot below:

![integrated shell](https://cloud.githubusercontent.com/assets/6123222/15844934/fae4fa3e-2ca0-11e6-804b-f080b7b9d14b.PNG)

**Comment by mappy7771** [comment]
Hi.
Try it.
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`

**Comment by steven-qi** [comment]
@mappy7771 It works perfectly. Thanks much. :+1:

**Comment by steven-qi** [comment]
I guess the difference is that: ```git-bash.exe``` is a Windows application (with ```WinMain``` as entry), but ```bash.exe``` is a console application (with ```main``` as entry). To be used as integrated shell, the executable must be a console application, so that ```stdin```/```stdout```/```stderr``` can be redirected.

As this is a pretty  common scenario, should we somehow make this documented, at least for ```git-bash.exe```?

**Comment by Tyriar** [comment]
@steven-qi this should definitely be added to the docs when a topic is written on the terminal, I've created https://github.com/Microsoft/vscode-docs/issues/343 to follow it up in the eventual documentation. Thanks! :smiley:

**Comment by steven-qi** [comment]
@Tyriar Thanks. 😄

**Comment by carlo-salinari** [comment]
@mappy7771  bash.exe doesn't seem to load the same profile of git-bash.exe (you lose aliases, colorization etc.)

This workaround forces the profile (you get the whole "git-bash experience"...)
```
// settings.json
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "--init-file",
        "C:\\Program Files\\Git\\etc\\profile"
    ]
}
```

**Comment by jamesxv7** [comment]
@steven-qi you should try @mappy7771 recommendation, it works flawlessly.

**Comment by steven-qi** [comment]
@jamesxv7 yes, I have been using it for quite a while, and it works well. Thank you for your suggestion.

**Comment by zaenk** [comment]
If you have custom `.bashrc` and `.bash_profile` under your `%USERPROFILE%`, you might also want to add `--login` to `shellArgs` in order to load them (for example: when you want to alias WLS `bash.exe` inside `System32` like [this](https://gist.github.com/zaenk/20178e637299404dcdcc1ff4667f24d7#file-bashrc)):

```
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.shellArgs.windows": [
    "--login",
    "--init-file",
    "C:\\Program Files\\Git\\etc\\profile"
],
```

> If you only create the `%USERPROFILE%/.bashrc`, Git Bash will create a `%USERPROFILE%/.bash_profile` which will load that for you (see it in: `C:\Program Files\Git\etc\profile.d\bash_profile.sh`)

**Comment by c3y** [comment]
bash.exe doesn't print with colors. For example, ls command returns all the results same color. but git-bash.exe makes the directories blue. you know a way to make bash.exe colorful as in original bash?
