### ISSUE TITLE
JavaScript class private fields with '#'

### ISSUE THREAD

**Issue by M-Nayeem** [Microsoft/vscode#72867]
See #56566.

The proposal is now stage 3 (like many features that _have_ already been implemented in VS Code) and is even implemented in Google Chrome 74 - stable as of earlier this week. I think it should be revisited and this should probably be kept open until it is implemented or actually cancelled.

**Comment by M-Nayeem** [comment]
Although, I guess it's the case that this feature is harder to implement than those other features and should be held off for longer. Nevertheless.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/9950

**Comment by M-Nayeem** [comment]
Just to be clear, I'm talking about syntax highlighting for JavaScript. Does that feed from TypeScript's language specification somehow?

**Comment by mjbvz** [comment]
Yes, TypeScript powers our JavaScript intellisense
