### ISSUE TITLE
Extreeme CPU usage

### ISSUE THREAD

**Issue by RadoslavMarinov** [Microsoft/vscode#72864]
Extreeme CPU usage after half an hour work with all extensions disabled. 46% of my cpu: Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
