### ISSUE TITLE
User defined snippet tab stops ignored

### ISSUE THREAD

**Issue by LennDG** [Microsoft/vscode#72862]
- VSCode Version: 1.33.1
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Create a new user snippet file for the project. The one I encounter the issue with is:
```json
{   
    "System": {
        "scope": "lua",
        "prefix": "system",
        "body": [
            "local ${1:SystemName} = System.create(\"$1\")",
            "",
            "function $1:requires( )",
            "\treturn {\"${2:Required Components}\"}",
            "end",
            "",
            "function $1:update( dt )",
            "",
            "\tfor _, entity in pairs(self.targets) do",
            "\t\t${3:--update logic}",
            "\tend",
            "",
            "end",
            "",
            "return $1"
        ],
        "description": "Create a new system"
    }
}
```
2. Use the snippet and attempt to press TAB after writing the first variable
3. The cursor does not move to the next stop, instead a tab character is added

The desired behavior would be for the cursor to move to the next tab stop.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Seems to work just fine for me... Any special keybinding or setting?

![Apr-25-2019 15-52-55](https://user-images.githubusercontent.com/1794099/56740956-3be05100-6772-11e9-8e56-a9ae1cd26dfc.gif)

**Comment by LennDG** [comment]
The action you took is not the problem I encounter and does indeed work the same way for me. 
Could you try to edit "SystemName", the first tab stop, then press TAB to go to "Required Components"? 

vsCode just inserts a tab character after whatever I wrote instead of going to the next tab stop.

**Comment by jrieken** [comment]
Ok, thanks for clarifying. For some reason snippet mode stops when making that edit... Not sure why

**Comment by ackvf** [comment]
I have encountered similar issue, however, I could add a single blank space in the snippet which "fixed" the tab navigation. See https://github.com/Microsoft/vscode/issues/72963

**Comment by jrieken** [comment]
This is a regression from https://github.com/Microsoft/vscode/commit/556bfbeee6ec5126e4a7d84581ef4f14afb043b0. I will revert that change and re-open the corresponding issue (which is much more rare than these issues)

**Comment by LennDG** [comment]
Thank you for fixing this, looking forward to the next release.
