### ISSUE TITLE
Not able to Refactor

### ISSUE THREAD

**Issue by mihirp1730** [microsoft/vscode#72860]
Issue Type: <b>Bug</b>

I'm trying to refactor my snippet but it cant allow me to refactor,
![refactor_notWork](https://user-images.githubusercontent.com/24892060/56736386-a6e75300-6785-11e9-818a-b2624ebf1cfa.PNG)
![Refactor_works](https://user-images.githubusercontent.com/24892060/56736387-a6e75300-6785-11e9-86b9-d61f0d6547b4.PNG)

When I'm using **Ctrl+Shift+R** it won't me allow showing any option like
- Extract to the method in class 'any text'
Please refer pictures attached with BUG. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
prettier-vscode|esb|1.8.1
beautify|Hoo|1.4.11
material-icon-theme|PKi|3.7.0

</details>

**Comment by mjbvz** [comment]
Can you please share the source code of that class

**Comment by mihirp1730** [comment]
Yeah sure,
You can go through the link [https://bitbucket.org/snippets/mihirp1312/qe5pb6]

**Comment by mjbvz** [comment]
In the current vscsode insiders builds, I see the menu showing up on ctrl+shift+r and the refactoring works as expected:

![Screen Shot 2019-04-26 at 10 26 03 AM](https://user-images.githubusercontent.com/12821956/56825370-c7f38680-680d-11e9-9c5d-2772b3ded414.png)

Does this happen if you open an empty folder with just that one jsx file?

**Comment by mjbvz** [comment]
Closing as more information is needed about how to reproduce this
