### ISSUE TITLE
Revert default JSON settings editor

### ISSUE THREAD

**Issue by janosh** [Microsoft/vscode#72863]
I'd like to question the changes suggested and then immediately implemented by #62964 without awaiting user feedback. I can understand that VS Code chose to make the settings UI the default even though I much prefer the JSON interface. But it makes absolutely no sense to me to remove the split-screen view which offered
- default settings in JSON format on the right and
- a search bar at the top

in favor of only the current user settings in a simple editor when `"workbench.settings.editor"` is changed from `"ui"` to `"json"`. In other words, I'm suggesting to make `"workbench.settings.useSplitJSON": true,` the default (rather than `false`) which would result in this settings interface

![split-settings](https://user-images.githubusercontent.com/30958850/56738265-26642a80-6764-11e9-8752-4393a5577c5a.png)

rather than this one

![simple-settings](https://user-images.githubusercontent.com/30958850/56738371-5e6b6d80-6764-11e9-87bd-e1a3a1a523ed.png)

once `"workbench.settings.editor": "json"` is set.

**Comment by roblourens** [comment]
Discussed in https://github.com/Microsoft/vscode/issues/68386
