### ISSUE TITLE
Provide a way for extensions to open the keybindngs editor with a query

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode#72878]
Issue Type: **Feature Request**

I'm a collaborator of [vscode-leetcode](https://github.com/jdneo/vscode-leetcode) extension, and frequently there are rookies asking how to bind 'test' or 'submit' command to a specific key binding, like [this issue](https://github.com/jdneo/vscode-leetcode/issues/262).

If we can show a message to tell them how to do it, and an option to guide them to a pre-filtered keybinding editor like this:
![](https://user-images.githubusercontent.com/20227484/55670915-77e36d00-58bc-11e9-93b7-4dba00ff8348.png)

Then the issues about it should be reduced.

The same goes for settings editor(solved in @rebornix 's [e5c1c22](https://github.com/Microsoft/vscode/commit/e5c1c2258e421db353c2a2ee1a04da31837a7e77#diff-dfd9031c00a144c2364595f331243744)), where our webview [uses built-in markdown preview settings](https://github.com/jdneo/vscode-leetcode/issues/246) to control its appearance. If we can open the settings editor with pre-filtered query 'markdown.preview', then users would find it  easy to modify the settings as they want.

Some early investigations are covered in https://github.com/Microsoft/vscode/issues/72352#issuecomment-486619632, which might be of some help.

**Comment by Vigilans** [comment]
@roblourens

**Comment by sandy081** [comment]
You can call `workbench.action.openGlobalKeybindings` command by passing query string as arg.

**Comment by sandy081** [comment]
To verify:

Write a simple extension that calls following command

`vscode.commands.executeCommand('workbench.action.openGlobalKeybindings', 'some query')`

This shall open keybindings editor with provided query arg.
