### ISSUE TITLE
No source rpms in the repos

### ISSUE THREAD

**Issue by dstathis** [Microsoft/vscode#72879]
vscode makes rpm repos available at https://packages.microsoft.com/yumrepos/vscode. This repo does not have any of the source rpms. They should be there so that people can use the os provided way of downloading source code (dnf download --source code).

**Comment by Tyriar** [comment]
There is a difference between the OSS version of code that you can build yourself and the official VS Code package, see https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005
