### ISSUE TITLE
status bar

### ISSUE THREAD

**Issue by liaohui5** [Microsoft/vscode#72872]
Issue Type: <b>Feature Request</b>

I think the status bar is too small when using vscode

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-29deepin-generic

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
