### ISSUE TITLE
Same file opened twice after search result

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#72876]
When you search for file using Search option, if the search folder is not correctly cased, then the file opened will have a slightly different path.

For example, here i spelled `Projects` as `projects`:

![image](https://user-images.githubusercontent.com/1022912/56753001-e44ddf80-6789-11e9-9e24-2f59a0deb93b.png)

This lead to having two times time same file opened, one with the path from search results and one with the path coming from language server (or workspace)

![image](https://user-images.githubusercontent.com/1022912/56753075-0e9f9d00-678a-11e9-998f-e4c7753922df.png)

**Comment by roblourens** [comment]
Yes, this is a long standing issue with file path casing: https://github.com/Microsoft/vscode/issues/12448
