### ISSUE TITLE
Keyboard freezes for several seconds when editing MD files

### ISSUE THREAD

**Issue by zodiacon** [Microsoft/vscode#72881]
Issue Type: <b>Performance Issue</b>

When editing markdown files, especially as they get larger (~ 50KB+) keystrokes are not accepted for several seconds (sometimes up to 15 or so) and then the stored keystrokes suddently are invoked.
The rest of the UI is fully responsive.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (13.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 58032	code main
    0	    68	 21872	   window (Issue Reporter)
    0	   180	 33884	   gpu-process
    0	   242	 38588	   window (● chapter6.md - manuscript - Visual Studio Code)
    0	    13	 16392	     watcherService 
    0	     5	 49432	       console-window-host (Windows internal process)
    0	   277	 39008	     extensionHost
    0	    10	 69168	     electron-crash-reporter
    0	    84	 41820	   window (undefined)
    0	    66	 47684	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● chapter6.md - manuscript - Visual Studio Code)
|    Folder (manuscript): 59 files
|      File types: png(27) PNG(18) md(7) txt(3) json(2) sqlite(1) suo(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.26.0
vscode-dash|dee|2.1.0
xml|Dot|2.4.0
vscode-rust-syntax|dun|0.0.32
vsc-material-theme|Equ|2.8.2
vscode-rust|kal|0.4.2
vscode-clang|mit|0.2.3
python|ms-|2019.4.11987
cpptools|ms-|0.23.0-insiders
csharp|ms-|1.19.0
cargo|pan|0.2.0
vscode-docker|Pet|0.6.1
rust|rus|0.6.1
RustyCode|sav|0.19.1
crates|ser|0.4.2
rust-pack|Swe|0.2.15
spellchecker|swy|1.2.13
ayu|tea|0.18.0
vscode-lldb|vad|1.2.2
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.6.0
markdown-all-in-one|yzh|2.2.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does with all extensions disabled?

**Comment by zodiacon** [comment]
no. I'm using the markdown all in one and markdown lint

**Comment by mjbvz** [comment]
Ok, it sounds like one of those extensions is causing this issue. Please track down which one by selectively enabling them, and then file an issue against the extension that is causing this
