### ISSUE TITLE
tab.activeBorder also colors unfocused tab

### ISSUE THREAD

**Issue by oreporan** [Microsoft/vscode#72887]
- VSCode Version: `1.30.2`
- OS Version: Mac Mojave

Steps to Reproduce:

1. set workbench.ColorCustomizations -> tab.activeBorder to green
2. open another file using a split editor

I know there is the option of coloring `tab.unfocusedActiveBorder ` which will override. But in my case I don't want any color on `tab.unfocusedActiveBorder `

The unfocused tab will also be colored green

**Comment by bpasero** [comment]
This works as designed, there can be multiple active tabs across multiple groups. Active tab simply means, active in a group.

**Comment by usernamehw** [comment]
Transparency FTW:

```json
"tab.unfocusedActiveBorder": "#fff0",
```

**Comment by oreporan** [comment]
@bpasero In that case do I have a way of getting that file?

` const currentlyOpenTabfilePath = e.document.fileName;`

gives me the active tab, how about the active not focused one?

**Comment by bpasero** [comment]
@oreporan there is currently no extension API to iterate over the opened tabs in VSCode, only to iterate over opened documents.
