### ISSUE TITLE
About vscode intelligence

### ISSUE THREAD

**Issue by nonstuff** [Microsoft/vscode#72886]
intelligence issues coming every time its not working after opening vs code

**Comment by ttbug** [comment]
version 1.32.3 works well, but version 1.33 is not working

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
