### ISSUE TITLE
Toggle Word Wrap [alt+z] in read-only editor

### ISSUE THREAD

**Issue by veganaize** [microsoft/vscode#72880]
Issue Type: <b>Feature Request</b>

Word-wrap should be able to work in a read-only editor, as well.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.3.9600

**Comment by alexandrudima** [comment]
@veganaize AFAIK word wrap does work in a read-only editor. What are the exact steps that you do?

**Comment by veganaize** [comment]
1. [ctrl+shift+p] Prefereneces: Open Default Settings (JSON)
2. Attempt to Toggle Word Wrap [alt+z]
3. Observe that it has no effect
