### ISSUE TITLE
Cannot open VS Code when offline

### ISSUE THREAD

**Issue by wuzzdingbatch** [Microsoft/vscode#72889]
Issue Type: <b>Bug</b>

0. My laptop is offline.
1. Click my main.go file. It suppose to open with VSC. Does nothing.
2. Right click my main.go file, select open with, select Visual Studio Code, click open. Does nothing.
3. From start menu, type Code, click Visual Studio Code. Does nothing. Shows nothing on Task Manager.
4. I connect to Wifi, connected.
5. From start menu, type Code, click Visual Studio Code. And running.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
xml|Dot|2.4.0
json-tools|eri|1.0.2
latex-workshop|Jam|5.20.1
Go|ms-|0.10.1

</details>

**Comment by bpasero** [comment]
@wuzzdingbatch can you update to latest VSCode and try again?

**Comment by wuzzdingbatch** [comment]
I just managed to update it. It works normally now.

Probably because I didn't update after few windows updates.
