### ISSUE TITLE
vsda is not buildin into RPM for linux x86_64

### ISSUE THREAD

**Issue by linqing2004** [Microsoft/vscode#72885]
- VSCode Version: 1.32.3
- Oracle Linux 7:       4.1.12-61.1.18.el7uek.x86_64

Steps to Reproduce:
1. I build the package by doing:
    1.2   yarn --verbose
    1.3 gulp.js vscode-linux-x64 --max_old_space_size=8192
    1.4 gulp.js vscode-linux-x64-prepare-rpm  --max_old_space_size=8192

It can be launched by running "code" 

But I have compared with the standard version of your RPM, and find out the vsda.node is not buildin.  I couldn't find this module anywhere. It looks used for debugging sessions' handshake.

Could you let me know if it is important and where to get or build this module?

Thanks,

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
vsda is only provided in the packaged version of VS Code, not in the OSS version.
