### ISSUE TITLE
vscode super slow

### ISSUE THREAD

**Issue by andremartinswork** [Microsoft/vscode#72888]
Issue Type: <b>Performance Issue</b>

I don't know why, but my vscode it's too slow.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   115	 10806	code main
    1	   115	 10807	   gpu-process
    0	   131	 10838	   shared-process
    0	   279	 10870	   window (itemProjects.js — zaply_backoffice)
    0	    98	 10872	     extensionHost
    0	    82	 10907	       electron_node eslintServer.js 
    0	   311	 10917	       electron_node tsserver.js 
    0	    82	 10918	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 10943	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=10872
    0	    49	 10873	     watcherService
    0	     0	 10955	     /bin/bash -l
    0	    49	 10965	     searchService
    3	    66	 10964	   window (Issue Reporter)
    0	     0	 10968	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
auto-close-tag|for|0.5.6
vscode-styled-components|jpo|0.0.26
material-icon-theme|PKi|3.7.0
autoimport|ste|1.5.3

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
