### ISSUE TITLE
Allowing unmodified keys to trigger commands 

### ISSUE THREAD

**Issue by vincentwhales** [Microsoft/vscode#72899]
First of all, I am trying to bind `\+t` to start quickOpen. 

I have the following key shortcuts: 

```
    {
        "key": "\\ t",
        "command": "workbench.action.quickOpen"
    },
```

Now when I press `\`, I see: 

`(\) was pressed. Waiting for second key of chord...`

This prevents me from actually typing `\` in my code 

I have posted a [question](https://stackoverflow.com/questions/55821142/i-cant-type-in-visual-studio-code) on stackoverflow, and learned that it is basically not possible to achieve what I want in VSCode. 

Is it possible to consider using unmodified keys to trigger commands in future releases?

**Comment by jrieken** [comment]
> Is it possible to consider using unmodified keys to trigger commands in future releases?

I am afraid it's not possible unless you use a context key to enable that keybinding only outside of editors.
