### ISSUE TITLE
feature merge conflict & button tab not working 

### ISSUE THREAD

**Issue by Myusuf060696** [microsoft/vscode#72890]
Issue Type: <b>Bug</b>

feature merge conflict, not show conflict style for fix conflict 
button tab sometime not working

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
rails-routes|aki|0.0.1
html-class-suggestions|And|1.0.7
All-Autocomplete|Ati|0.0.18
laravel-blade-spacer|aus|1.0.2
vscode-intelephense-client|bme|1.0.13
rails|bun|0.13.0
vscode-gemfile|bun|0.0.2
solargraph|cas|0.19.6
laravel-goto-view|cod|1.2.3
erb|Cra|0.0.1
rails-test-runner|dav|0.0.4
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
ruby-around-the-block|ell|0.1.2
LogFileHighlighter|emi|2.4.3
vsc-material-theme|Equ|2.8.2
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.11
ruby-linter|hoo|1.0.0
rails-snippets|Hri|1.0.8
path-autocomplete|ion|1.13.2
rails-fast-nav|jem|1.3.0
endwise|kai|1.4.2
auto-comment-blocks|kev|1.0.1
edge|luo|0.3.1
vscode-rufo|mbe|0.1.1
rainbow-csv|mec|1.0.0
php-namespace-resolver|Meh|1.1.7
code-copy-ruby-ref|mic|0.2.2
ruby-symbols|mig|0.1.7
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|1.0.91
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.2.12
php-docblocker|nei|1.8.0
snippet-creator|nik|0.0.5
prettier-standard-vscode|num|0.5.0
laravel-blade|one|1.18.0
phpstorm-snippets|phi|1.1.1
material-icon-theme|PKi|3.7.0
subtle-brackets|raf|3.0.0
ruby|reb|0.22.3
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.2.9
slim|sia|0.1.2
highlight-matching-tag|vin|0.9.1
simple-ruby-erb|vor|0.2.1
vscode-icons|vsc|8.6.0
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
markdown-all-in-one|yzh|2.2.0

(3 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
Sorry, I don't understand:
- Where would you expect a different style? Could you attach a screenshot?
- Which button does not work?
