### ISSUE TITLE
Mark same variable when document splitted

### ISSUE THREAD

**Issue by itdevbpi** [Microsoft/vscode#72898]
Issue Type: <b>Feature Request</b>

is it possible to mark a variable for a variable that selected , when document mode is in split view

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by itdevbpi** [comment]
[](url)

> 
> 
> Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
