### ISSUE TITLE
Make CJK characters use precisely two spaces width to align with western characters

### ISSUE THREAD

**Issue by kidlj** [Microsoft/vscode#72907]
As the screenshots show, Terminal app always display Chinese characters with two spaces width, and they are aligned with western characters. Can we offer an option for VSCODE to achieve this kind of display?

<img width="777" alt="terminal" src="https://user-images.githubusercontent.com/300616/56793794-5cc2a800-683f-11e9-9c2c-981aad374736.png">
<img width="816" alt="vscode" src="https://user-images.githubusercontent.com/300616/56793797-5cc2a800-683f-11e9-9124-ab7e007538c3.png">

**Comment by gjsjohnmurray** [comment]
See also #72743

**Comment by alexdima** [comment]
Here is the content in a copy-paste friendly format:
```
| item                 | description                                           |  |
|----------------------|-------------------------------------------------------|--|
| item1 item1 item1    | this is a line with only western characters           |  |
| item2 中文条目2 item2 | line with Chinese characters and western characters   |  |
| item3 item3 item3    | yet another line                                      |  |
```
