### ISSUE TITLE
Detect invisible junk characters

### ISSUE THREAD

**Issue by biswajit-paul** [Microsoft/vscode#72901]
Once I copied some PHP code from pdf to VSCode, I was getting some error which I could not rectify it for 2+ hours. Then I paste the code in PHPMyAdmin SQL editor and found that there are some red dots over there which gave me the headache. I cleared the red dots and after that code run smoothly. Is there any settings or something else which I can detect those hidden characters?

Raw code here: https://kopy.io/l1k3H

Screenshot in VSCode:
![Screenshot from 2019-04-26 11-43-49](https://user-images.githubusercontent.com/14993725/56787834-5d494780-681b-11e9-8511-8b06415ae061.png)

Screenshot in PHPMyAdmin:
![Screenshot from 2019-04-26 11-45-18](https://user-images.githubusercontent.com/14993725/56787849-65a18280-681b-11e9-888f-0014e21e081c.png)

**Comment by Delapouite** [comment]
Did you try the following setting: `"editor.renderWhitespace": "all"`?

**Comment by biswajit-paul** [comment]
It works. After applying setting, it is visible only in light theme. I could not find it first because I have dark monokai theme activated.
