### ISSUE TITLE
VSCode cross-origin request inside WebView

### ISSUE THREAD

**Issue by rusnasonov** [Microsoft/vscode#72900]
I ask question on StackOverflow but activity is very low.

Summary:

I want to make HTTP request inside WebView but I got error

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

Server does't support Access-Control-Allow-Origin for "null" or "localhost" Origin.

Is the way to create HTTP request from WebView to server ignoring missing Access-Control-Allow-Origin header? Maybe I can setup some policy for WebView panel? Or create localhost proxy inside extension and make request over proxy?

https://stackoverflow.com/questions/55841688/vscode-cross-origin-request-inside-webview

**Comment by mjbvz** [comment]
There is no vscode support for changing this. You should think of the webview more as an html view (one that does not have any server or origin) rather than a webpage

Posters on stackoverflow may have suggestions for workarounds
