### ISSUE TITLE
Startup: createSpdLogService() is slow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#72906]
I am looking at startup profiles on Windows and `createSpdLogService` shows up very early with around 30ms both in main, renderer and extension host process:

**Renderer**
![image](https://user-images.githubusercontent.com/900690/56793129-8bbf2680-680b-11e9-95d5-17bf6f4ce85e.png)

**Main**
![image](https://user-images.githubusercontent.com/900690/56793165-9da0c980-680b-11e9-843d-ea845ba3c1aa.png)

**Extension Host**
![image](https://user-images.githubusercontent.com/900690/56793760-00df2b80-680d-11e9-875b-af6125409763.png)

On the main side this blocks the window from opening and on the renderer it blocks the overall startup.

One idea I had was: can we simply have a buffered log service initially and then later fill in the real implementation + push the logged messages to disk when loading is done?

**Profiles:**
[profiles-windows.zip](https://github.com/Microsoft/vscode/files/3120390/profiles-windows.zip)

//cc @jrieken

**Comment by jrieken** [comment]
Yeah, also the extension host pays for this, e.g something like git or TS is delayed 3*30ms because of this...

**Comment by bpasero** [comment]
I added also the extension host log.

**Comment by sandy081** [comment]
Yeah, creating a spdlog logger is sync and sometimes it takes long time. This was investigated [here](https://github.com/Microsoft/vscode/issues/70998). There, I made creating spdlog logger and async and adopted in ext host output channels. I would adopt the same everywhere.

**Comment by bpasero** [comment]
Cool :rocket:

**Comment by sandy081** [comment]
@bpasero Changed creation of spdlog logger from sync to async. Can you please run the perf profile and let me know if you see the difference. You can also let me know how to run.

**Comment by jrieken** [comment]
> You can also let me know how to run.

@sandy081 This is with `--prof-startup`, either `scripts/code-cli.sh` or (better) using a real build

**Comment by bpasero** [comment]
Let's make sure we verify this, either way.

**Comment by sandy081** [comment]
Well the fix I did fixes creating the spdlog logger by making it async. But loading spdlog module is still sync.

```
const _spdlog: typeof spdlog = require.__$__nodeRequire('spdlog');
``` 

@alexandrudima Is there a way to load this module async?

**Comment by bpasero** [comment]
@sandy081 then I think we need to move the loading of the module out to a place where we have already opened the window. E.g. the flow would be:
* always have a buffered logger
* open first window
* then start loading the real logger and flush the buffer into it

**Comment by sandy081** [comment]
It means we miss logs if there is a crash in between. Is there a way to load the module async?

**Comment by bpasero** [comment]
@sandy081 I am not sure how valuable the logs are for a crash on startup, I cannot recall from my issues that I could track the cause through logs for native crashes at least.

I think the only way to load the module truly async is by providing a function from speedy log to initialize it and implement that in a worker thread of node.js. This likely requires changes to the native implementation if it currently is sync.

**Comment by bpasero** [comment]
Talked to Sandy, the proper way to async require is "`await import('spdylog')`"

**Comment by jrieken** [comment]
are you two sure about that? ultimately it'ss a node module and they are always loaded sync and in one chunk. To my knowledge, one reducing the module size helps

**Comment by sandy081** [comment]
I do not know how different the module is getting loaded with this [change](https://github.com/microsoft/vscode/issues/72906#issuecomment-496135037) but see think there is a difference in times.

Before:

![image](https://user-images.githubusercontent.com/10746682/58412183-35e1d680-8076-11e9-81ea-3f4cce4ce792.png)


After:

![image](https://user-images.githubusercontent.com/10746682/58412128-19de3500-8076-11e9-91a0-36486583414b.png)

**Comment by bpasero** [comment]
Yeah I take it back, it will still cause a sync require later. If `spdylog` has any sync code (fs access) in the module loading phase, we will still see this slowdown.

**Comment by sandy081** [comment]
I measured the times after moving loading & creation of spdlog to the eventual lifecycle phase so that it will not interfere with the start up. On an average there is an improvement of ~<10ms which I felt is not worth to the changes and debt this will introduce. 

@bpasero Can you please verify with the improvements those were done already (async spdlog creation) and revisit this if it is still a bottle neck.

**Comment by bpasero** [comment]
I can confirm a nice speedup with the current solution (on my old Thinkpad, Windows 10, no power plug), good job.

Stable (renderer): `36ms`

![image](https://user-images.githubusercontent.com/900690/58468710-5aa18100-813e-11e9-8473-11afb0f1a97b.png)

Master (renderer): `3.51ms`

![image](https://user-images.githubusercontent.com/900690/58468753-6e4ce780-813e-11e9-9070-b2ff24a8e088.png)

**Comment by jrieken** [comment]
To bust a myth: `3.51ms` to create a promise that (eventually) loads the code. Writing `await import('foo')` desugars to 

```ts
new Promise(resolve => {
  const module = require('foo');
  resolve(module);
})
```

Those `3.51ms` are lines 1 and 2 in the sample, not lines 3 and 4

**Comment by bpasero** [comment]
This is still a lot faster compared to before: `RotatingLogger` ctor: `7ms` to `1ms` (not being sync anymore)

The actual require now happens at a later point, hard to find in the timeline without perf marks.

Attached profiles: 
[profiles.zip](https://github.com/microsoft/vscode/files/3227054/profiles.zip)
