### ISSUE TITLE
Build task is not ended when exiting VSCode

### ISSUE THREAD

**Issue by rogierschouten** [Microsoft/vscode#72908]
Issue Type: <b>Bug</b>

Load any project.

Use Terminal - Run Build Task...  to run a watch task (in our case a Node script defined in package.json)

Exit VSCode by clicking the top-right cross button

In the background, the build task is still running.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (16.75GB free)|
|Process Argv|C:\Source\modules\exlent-session-ui|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
unique-lines|bib|1.0.0
code-sql|cod|0.0.3
vscode-markdownlint|Dav|0.26.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.8.1
sass-lint|gle|1.0.5
vscode-guid|hea|1.4.7
vscode-styled-components|jpo|0.0.26
vscode-insertdatestring|jsy|2.2.3
vscode-typescript-to-json-schema|mar|0.0.11
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|0.1.18
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-docker|Pet|0.6.1
modified-typescript-hero|rbb|0.0.0-development
vscode-yaml|red|0.4.0
vscode-sort-json|ric|1.13.0
sass-indented|rob|1.5.1
vscode-sql-beautify|sen|0.0.4
vscode-hexdump|sle|1.7.2
sort-lines|Tyr|1.8.0
alphabetical-sorter|ue|2.0.1

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
@rogierschouten, do you have any additional repro steps? I can't reproduce this with the VS Code build task [here](https://github.com/Microsoft/vscode/blob/alexr00/catchInputErrors/.vscode/tasks.json#L7)

**Comment by alexr00** [comment]
I also tried with a npm script that runs a node script.

**Comment by rogierschouten** [comment]
I'm unable to narrow it down. Let's close this issue until I can give a better reproduction.
