### ISSUE TITLE
Please set up the launch configuration file for your application

### ISSUE THREAD

**Issue by wsg36236** [Microsoft/vscode#7291]
- VSCode Version:1.2.0
- OS Version:Windows 10

Steps to Reproduce:

1. I updated VSCode to 1.2.0
2. When i debug a nodejs app and set config, but VSCode still tell me to set up config

![image](https://cloud.githubusercontent.com/assets/18693746/15845357/e784a134-2ca4-11e6-91d5-cfb46c330927.png)

**Comment by englercj** [comment]
I just updated today and am getting the same thing.

**Comment by wsg36236** [comment]
I install back to 1.1.1, everything is ok.

**Comment by pangtengfei** [comment]
updated 1.2, same thing

**Comment by weinand** [comment]
Just open the launch.json or select a launch config from the drop down menu and problem disappears.

**Comment by ghurlman** [comment]
@weinand Which dropdown menu? having the launch.json file open in the editor or not doesn't seem to have any effect.

**Comment by weinand** [comment]
@ghurlman the launch config dropdown:
![2016-06-07 15-32-36](https://cloud.githubusercontent.com/assets/1898161/15859349/1e327ec0-2cc5-11e6-8df8-375f583bc14d.png)

**Comment by ghurlman** [comment]
@weinand Thanks! I'd only ever launched via F5, so I totally missed that.

**Comment by JoBrad** [comment]
Re-choosing "Launch" for my NodeJS app (Launch was already specified in the dropdown) addressed this issue for me. It's like the default option for the dropdown isn't getting set in the debugger or something.

**Comment by weinand** [comment]
@JoBrad yes, your analysis is correct. Sorry for the inconvenience.

**Comment by JoBrad** [comment]
Thanks for the fix! Was really bugging me :)

**Comment by pangtengfei** [comment]
@weinand Thanks

**Comment by isidorn** [comment]
For the recovery vscode build we have decided on a simple solution - open the debug viewlet when the launch.json is generated for the first time. I understand this changes how the UI behaves, but making the vielwet more discoverable on first setting up debug is not that bad IMHO.

Later in June we will look to address this feature without changing the UI
