### ISSUE TITLE
Get installation log of the extension

### ISSUE THREAD

**Issue by Vyshakh18** [Microsoft/vscode#72917]
- VSCode Version: 1.31
- OS Version: Windows 10

Steps to Reproduce:
I have created an extension for VS Code. During the installation of the extension, i want to see the installation log during the installation of the dependencies that are mentioned in package.json - is a there a way to see these logs.

**Comment by Vyshakh18** [comment]
One of the dependency for my extension is the ibm_db module - which is infact a native module and requires electron rebuild. There is already code inside the install script for ibm_db module to handle this.
But however it does not seem to work when this installation happens via vscode. 
So i want to see the console.log that the ibm_db prints, during its installation.

**Comment by Vyshakh18** [comment]
okay, so i kinda figured out thing. I was a missing a basic information, my bad - that the installation of the extension actually happens on the machine where we are publishing the extension - and its this snaphshot which actually goes to marketplace, and then later, to user's system - am i right?

**Comment by gjsjohnmurray** [comment]
This issue has some info that may be useful to you:

https://github.com/Microsoft/vscode/issues/658

**Comment by Vyshakh18** [comment]
@gjsjohnmurray thank you very much for the pointer...
the reason i was looking for the installation log is understand about the installation errors...but when i digged further about the cause of the error, i kinda figured out that what i shud be looking for is , a solution to [this](https://github.com/Microsoft/vscode/issues/23251)
