### ISSUE TITLE
Changes in tasks.json aren't reflected when building the program

### ISSUE THREAD

**Issue by Managor** [Microsoft/vscode#72914]
- VSCode Version: 1.33.1
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Press Ctrl+Shift+B to open the build options
2. Click on the gear icon to edit the task file
3. Add for example `"-lpthread",` as an argument 
![image](https://user-images.githubusercontent.com/42655600/56800666-46f3b980-6824-11e9-9787-7029772a1dbc.png)
4. The change isn't reflected by the terminal input reported when selecting the same task nor is there and additional option for the modified task 
![image](https://user-images.githubusercontent.com/42655600/56800852-b5d11280-6824-11e9-8d91-0ca1f55b95db.png)

There is however and additional option when using Ctrl+Shift+P, typing in "tasks" and selecting "Tasks: Configure task" 
![image](https://user-images.githubusercontent.com/42655600/56800959-fd579e80-6824-11e9-812d-39968f243a25.png)

Does this issue occur when all extensions are disabled?: The problem is kinda fixed when run with --disable-extentions. This forces VSCode to display an error message that no build tasks found, asks if you want to create one and ***after*** that gives you an option to use the user generated one.

**Comment by alexr00** [comment]
Only tasks with `"group": "build"` show in the build task picker.

**Comment by Managor** [comment]
Then why isn't `"group": "build"` in the autogenerated file? If I choose the cog to edit a task, I expect the edits to be reflected without additional modification.

**Comment by alexr00** [comment]
By changing the arguments for the existing task you have actually created a new task. The original task is still marked as a build task, which is why it shows up. If you had added a property to the task in tasks.json that didn't cause the task to become a new task (such as the presentation properties), then it would still be the same task and still be a build task.
