### ISSUE TITLE
option for searching the Hard coded string in the code.

### ISSUE THREAD

**Issue by pandyamarut** [microsoft/vscode#72912]
It's difficult to search for hard coded  strings when you're working on big projects. 
There should be some search option to search for the hard coded strings in the whole project as well as in the file. 
it will be great help for the people who want to write translation files for their project. 
Thanks!

**Comment by gjsjohnmurray** [comment]
Perhaps an extension?

https://marketplace.visualstudio.com/search?term=translat&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by pandyamarut** [comment]
@gjsjohnmurray Not exactly this. 
There should be something to find the hard coded strings in the whole project.

**Comment by roblourens** [comment]
Not exactly clear what you are asking for. You want to match search terms only if they are in strings? It's not practical for us to search based on language syntax.
