### ISSUE TITLE
Indentation of file-explorer-icons Not Correct

### ISSUE THREAD

**Issue by riatec** [Microsoft/vscode#72918]
Issue Type: <b>Bug</b>

Just consider the folder structure as following:

/src
/src/app
/src/index.html

Though the last 2 items are at the same level inside /src, the icon of the folder(arrow) is indented more to right. Because of this index.html seems to be in the root level with /src. So when there are many files in an expanded /app folder, in order to avoid clutter to the eye, we try collapsing the /src folder which then hides the index.html file inside it. 

Happened many times. Please do the needful
![suggest-icons](https://user-images.githubusercontent.com/6203259/56805515-ede94d00-6846-11e9-8bb0-cf73725a3482.png)

Thank you
Riatec

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.84GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-rust-syntax|dun|0.0.32
vscode-ionic-snippets|fiv|0.24.0
rust|rus|0.6.1

</details>

**Comment by gjsjohnmurray** [comment]
@riatec - Is this similar to #72568 ? What File Icon Theme are you using? Do you have the same problem if you select "Minimal" or "Seti"? Also, please post your version info from the About dialog. Use the Copy button to put it onto the clipboard rather than pasting a screenshot of the dialog.

**Comment by isidorn** [comment]
Dup of #72568
@gjsjohnmurray thanks!

**Comment by riatec** [comment]
Super, thank you!

regards,
