### ISSUE TITLE
cursor goes down automatically in vscode

### ISSUE THREAD

**Issue by kunal812eee** [Microsoft/vscode#72910]
Every time i am writing something and as i stop writing something for some fraction of seconds the cursor automatically goes to the next line.
![Capture1](https://user-images.githubusercontent.com/36692515/56797793-1f581d80-6833-11e9-812c-45db23f2cf77.PNG)

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by kunal812eee** [comment]
how to update issue means delete
