### ISSUE TITLE
Reveal in Explorer

### ISSUE THREAD

**Issue by ivanfsa** [microsoft/vscode#72923]
Issue Type: <b>Bug</b>

After updating the "Reveal in explorer" option does not work.
Two Pops Up with "system call failed"

Thanks.

Windows 10 Pro build 1803
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.70GB (2.91GB free)|
|Process Argv|--folder-uri file:///e%3A/Relatorio/iestoque|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.19.0
team|ms-|1.149.2

</details>

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode inisders 
https://code.visualstudio.com/insiders/
