### ISSUE TITLE
Find all references in CSS cuts off before hyphen in property name

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#7292]
- VSCode Version:
Version 1.2.0 (1.2.0)

- OS Version:
OS X 10.lostCount

Steps to Reproduce:

1. Right click on a CSS property value
2. Find all occurrences 

Expected:

See all of the property name as even the longest CSS properties are not that long

Actual:

It seems in most cases it trims before the last hyphen, but sometimes it keeps a little more. 

This is probably a design decision (to keep the values aligned?) but I thought I'd file a bug as the property  a value is defined on is often relevant, and many different properties end with the same last word (background-color, color, boder-left-color; background-image, border-image, etc.), and with CSS properties not being super long, there is often room to fit the full property. In the screenshot it even includes the comment.

![screen shot 2016-06-06 at 9 24 16 pm](https://cloud.githubusercontent.com/assets/465069/15846068/4ab0f270-2c2e-11e6-98ff-c638b53c36cd.png)

**Comment by jrieken** [comment]
Yeah, we [cut](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesModel.ts#L84) the left part of a preview to roughly eight characters and prefer word boundaries, such as `.`, `-`, whitespace etc. I see how this isn't right for css. Maybe we shouldn't use `/\b/` but a custom set of splitters

**Comment by jrieken** [comment]
![screen shot 2016-06-07 at 12 08 27](https://cloud.githubusercontent.com/assets/1794099/15854171/b45feada-2ca8-11e6-889e-6e1421559155.png)

I am now using the word definition knowledge each language provides. That results in better cuts.
