### ISSUE TITLE
Dirty save Compare option not quite working right for FileSystemProvider-sourced documents

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#72924]
Testing on 1.34 Insiders. Using my `FileSystemProvider` extension I open a remote document and modify it in VSCode. Then I modify it directly on its host server. When I try and save the changes in VSCode I correctly get this:
![image](https://user-images.githubusercontent.com/6726799/56814510-444e8f80-6837-11e9-9215-365fa6fb8881.png)

👍  Looking good (though it probably should avoid talking about "on disk" at this point).

So I click the button:
![image](https://user-images.githubusercontent.com/6726799/56814659-90013900-6837-11e9-9467-002e4d1dbe0e.png)

👎 The comparison seems to try loading the remote document as if it's stored locally. In this case the URI of the remote document is `serenji://tin.hs181/USER/test4.int`

It's possible my extension is doing something wrong when the document loaded originally. Or maybe there's still a bit of rewiring to do inside VSCode. If the latter, I really hope it can make the April milestone.

@bpasero ?

**Comment by bpasero** [comment]
@gjsjohnmurray thanks, another good catch 👍

**Comment by bpasero** [comment]
Pushed a fix via https://github.com/Microsoft/vscode/pull/72954

@gjsjohnmurray would be great if you could verify from tomorrows insider release

**Comment by gjsjohnmurray** [comment]
Verified 👍
