### ISSUE TITLE
phpDoc highlight variables

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#72928]
It seems as if phpDoc block syntax highlighting is built into code (I disabled all extensions to make sure), so I would like to request that variables get highlighted just like they do in the javascript/typescript files.

As you can see from the images the variables are not highlighted, and look like they are part of the comment (`$db`, `$response`, `$request`, etc.):

![@var](https://user-images.githubusercontent.com/1571806/56820401-6d5c2980-6811-11e9-8864-2bcc98d61ea8.PNG)
![@property](https://user-images.githubusercontent.com/1571806/56820400-6d5c2980-6811-11e9-9d37-2f765bbcad88.PNG)
![@param](https://user-images.githubusercontent.com/1571806/56820402-6d5c2980-6811-11e9-9217-9cf1dd43fbcb.PNG)

---

This is how I would like it to look (From a `.js` file), as you can see the variable is highlighted in red:

![@param-js](https://user-images.githubusercontent.com/1571806/56820829-84e7e200-6812-11e9-9f82-3e6debbdcedd.PNG)

**Comment by roblourens** [comment]
https://github.com/atom/language-php/issues/354
