### ISSUE TITLE
Multiline Function Generics Break Highlighting and Formatting

### ISSUE THREAD

**Issue by ac566** [Microsoft/vscode#72930]
- VSCode Version:  1.33.1
- OS Version: Win 10

When defining or calling a function with long generics it helps to split it out into separate lines.

When you do this it breaks the color highlighting for the rest of the page.

This seems related to https://github.com/Microsoft/vscode/issues/26485

It seems to happen when calling a function that takes generic type arguments, and when declaring such a function inside of a class. Functions declared outside of a class (i.e. with `function`) don't show this behavior.

Steps to Reproduce:
1. Create a class function with a couple of generic type arguments
2. Have each type argument be on its own line 
3. Call that function from any valid scope and specify the type arguments on separate lines

```typescript
class Baz {
    static get< // get is highlighted like an accessor
        U, V
    >(x: U, y: V): boolean {
        return (x && y) != null;
    }

   foo(): void { 
       if (Baz.get<number, number>(1, 2){ // notice that get is highlighted here but not in the other calls
            console.log(3)
       }
   }
}

const t = Baz.get<
    string, number // Types show up the wrong color
>('hello', 4);

// The problem seems to be compound when calling within a class
class Buzz {
    y = {
        a: Baz.get<
            string,
            {
                a: 5;
            }
        >('hello', { a: 5 }),

        b: Baz.get<string, number>('hello', 6), // Bazz.get shows up in a Type color
    };
}
```

Does this issue occur when all extensions are disabled?: *Yes*

**Comment by mjbvz** [comment]
Thanks for the example code. The colorization problem is a known limitation with the TypeScript grammar. See https://github.com/Microsoft/TypeScript-TmLanguage/issues/745 for more information
