### ISSUE TITLE
Debug not starting

### ISSUE THREAD

**Issue by maunderingpowershell** [microsoft/vscode#72933]
Issue Type: <b>Bug</b>

When trying to debug using the integrated powershell terminal debug fails to start after a few times. The only way I'm able to get it working again is to relaunch VSCode but then the issue recurres after a few more debug sessions.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.95GB (5.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.3
gc-excelviewer|Gra|2.1.32
powershell|ms-|1.12.1
vsliveshare|ms-|1.0.91

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes please create a repository on github for which you can always reproduce so we can clone it and investigate more on our machines
