### ISSUE TITLE
tsconfig.json paths auto-imported incorrectly

### ISSUE THREAD

**Issue by ac566** [Microsoft/vscode#72931]
- VSCode Version: 1.33.1
- OS Version: Win7

This may have been a hack to begin with but..

Steps to Reproduce:
1. Add a section to the project level tsconfig.json
```json
{
  "compilerOptions": {

    ...
    "baseUrl": ".",
    "paths": {
       "mylib/*": [
         "./lib/*/index.ts"
       ]
     }
   }
}
```
2. Create `./lib/types/index.ts` like this 
```typescript
export type MyLibType = 'hello';
```

3. Create another file and try to auto import MyLibType (not using the relative path)
4. You get an import from `'mylib/types/index'` which is not correct, it should be `'mylib/types'`

**Comment by mjbvz** [comment]
Do you have `module` or `moduleResolution` set in your tsconfig?

Also if you use `mylib/types` for the import, does tsc or the editor show an error?

**Comment by ac566** [comment]
> Do you have `module` or `moduleResolution` set in your tsconfig?
module is es2015
moduleResolution is node

> Also if you use `mylib/types` for the import, does tsc or the editor show an error?
neither shows an error

**Comment by mjbvz** [comment]
I can't repo this:

![Apr-26-2019 14-18-53](https://user-images.githubusercontent.com/12821956/56914411-e5705c80-6a68-11e9-8194-7de76ea3e2ef.gif)

Are you sure the files are part of the tsconfig project? Open the ts file and run the `TypeScript: go to project configuration` command to check. It should open the correct tsconfig.

**Comment by ac566** [comment]
Yes they are in the right project. I double-checked what I was doing and I think the name of the index file might make a difference. When I rename it to `_index` like in my real project, the import option shows up how I explained in the OP

Here's a screenshot:
![screenie](https://user-images.githubusercontent.com/33584700/56933311-d7442f80-6aac-11e9-921a-ea5f6c62f77c.png)
My tsconfig:
![screenie](https://user-images.githubusercontent.com/33584700/56933422-63eeed80-6aad-11e9-8538-816b57a4d624.png)

**Comment by mjbvz** [comment]
Can you share that example project so that we are testing the exact same project

**Comment by ac566** [comment]
I made a mistake on my last comment. 

here is a repo where its happening: https://github.com/ac566/typescript-auto-import-issue

**Comment by mjbvz** [comment]
Thanks. I've confirmed this issue and opened https://github.com/Microsoft/TypeScript/issues/31173 upstream to track it
