### ISSUE TITLE
Exiting Zen Mode exits Fullscreen

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#72936]
```json
"zenMode.restore": true
```

1. Go Fullscreen
1. Enter Zen Mode
1. Reload Window
1. Exit Zen Mode

**Actual**: Exits Fullscreen
**Expected**: Stays Fullscreen

VS Code version: Code - Exploration 1.34.0-exploration (bb1b2e1f9a658bfb88e0639b4b9c4a0b70766db5, 2019-04-26T06:57:29.582Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
I acknowledge this behavior.
Code pointer for potential fix https://github.com/Microsoft/vscode/blob/28c7d9976fa6abe7f080259cf6dd19da3b78b761/src/vs/workbench/browser/layout.ts#L556
