### ISSUE TITLE
Implement Interface produces awkward code

### ISSUE THREAD

**Issue by jitcoder** [Microsoft/vscode#72937]
- VSCode Version: 1.33.1
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. Create interface
2. Create empty class that implements interface
3. Press `ctrl+.` or lightblub icon
4. Select implement interface

![image](https://user-images.githubusercontent.com/4588694/56836070-e7e57300-682a-11e9-8e06-6a7222980311.png)

result:

![image](https://user-images.githubusercontent.com/4588694/56836094-fa5fac80-682a-11e9-8d4a-a28c36958ed6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/28165
