### ISSUE TITLE
Extension Host is using too much RAM

### ISSUE THREAD

**Issue by AdrianCarreno** [Microsoft/vscode#72934]
Issue Type: <b>Bug</b>

Just by launching VS Code, it 
uses about 2.2GB of RAM, and just 1 of it's subprocesses is taking 1.7GB.

![Captura](https://user-images.githubusercontent.com/14844417/56830279-f3896780-6833-11e9-9471-63c9de6e28f7.PNG)

Killing said process triggers a notification "Extension host terminated unexpectedly".

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

<details>
<summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.13
xml|Dot|2.4.0
gitlens|eam|9.6.3
vscode-html-css|ecm|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2019.4.11987
vetur|oct|0.19.2
laravel5-snippets|one|1.5.0

</details>

<details>
<summary>Processes list of "code --status"</summary>

CPU %|Mem MB|PID|Process
---|---|---|---
0|84|5628|code main
0|66|496|shared-process
0|167|7052|window (tos.blade.php - SinDeudaTag - Visual Studio Code)
0|14|2384|watcherService
0|9|13900|console-window-host (Windows internal process)
0|6|9380|winpty-process
0|9|1120|console-window-host (Windows internal process)
0|64|17148|C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
0|4|8916|C:\Windows\system32\cmd.exe /c ""C:\Users\Adri´┐¢n Carre´┐¢o\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --status"
0|33|16252|electron_node cli.js
0|54|18948|"C:\Users\Adri´┐¢n Carre´┐¢o\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
0|1538|9564|extensionHost
0|72|8992|"C:\Users\Adri´┐¢n Carre´┐¢o\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Adri´┐¢n Carre´┐¢o\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=9564
0|134|21164|electron_node intelephense.js
0|33|16664|searchService
0|12|17392|electron-crash-reporter
0|174|7200|gpu-process

</details>

**Comment by Tyriar** [comment]
The extension host is consuming a lot of RAM because that's how much your extensions are using. You can disable them but they may need this much RAM normally to operate as many extensions need to index/cache a lot of data in order to provide fast language services.
