### ISSUE TITLE
It's not possible to give an args array on inputs.

### ISSUE THREAD

**Issue by paeolo** [microsoft/vscode#72935]
I am trying to use an input in tasks.json

`    "inputs":
    [{
        "id": "terminate",
        "type": "command",
        "command": "workbench.action.tasks.terminate",
        "args": ["terminateAll"]
    }]`

However it doesn't work since somehow "args" seems to accept only an object. Now, I know "args" is also meant to be an array in other parts of vscode, for instance:

`{
		"key": "ctrl+shift+alt+t",
		"command": "workbench.action.tasks.terminate",
		"args": ["terminateAll"]
	}
`
After reading vscode's code, I couldn't figure out how to solve this issue.

The task I want to terminate is the "preLaunchTask" for debug, and I want to terminate it in the "postDebug" task.

I use the "preLaunchTask" to launch a game boy advance emulator that runs a gdb server. All I want is to terminate the task "preLaunchTask" without any prompt when the debugging is done.
Thank you!
Paul.

**Comment by alexr00** [comment]
Documentation: https://code.visualstudio.com/docs/editor/variables-reference#_input-variables
Command inputs take a property bag as their args.

This looks like a bug since everywhere else I see does expect an array for command args.

**Comment by alexr00** [comment]
@weinand for FYI.

**Comment by alexr00** [comment]
Added documentation: https://github.com/microsoft/vscode-docs/commit/fd9130256b8a3195171252e06c9dd777e5decb00
