### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by giamuhammad** [Microsoft/vscode#72949]
Issue Type: <b>Bug</b>

When i do alt-tab and back to visual studio code, then scrolling my opened file, the position always jump to end of file then i should search scrolling back to last position

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor (16 x 1828)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.41GB (21.09GB free)|
|Process Argv|/tmp/fz3temp-2/User.php|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.4.11987
vscode-yaml|red|0.4.0

</details>

**Comment by jrieken** [comment]
Does this happen with all file types? Do you use format on type? Does this reproduce with latest insiders?

**Comment by jrieken** [comment]
no actionable information provided

**Comment by donhall** [comment]
bug closed, but problem not resolved?

**Comment by alexandrudima** [comment]
Let's track in #28795
