### ISSUE TITLE
XDebug dissapear after click on Step Over (F10) button after updating to Version 1.2.0

### ISSUE THREAD

**Issue by slaveofcode** [Microsoft/vscode#7294]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Start debugging F5 (xdebug)
2. Go to browser and refresh url related to the breakpoint 
3. Debug catched on breakpoint
4. Click on Step Over F10
5. Step Over button disabled, looks like not active / not available
6. List Variables on the left side was gone, but Call Stack values still exist

**Comment by weinand** [comment]
@slaveofcode xdebug is php?

**Comment by weinand** [comment]
This issue was moved to felixfbecker/vscode-php-debug#40
