### ISSUE TITLE
Delete files with WinSSHFS

### ISSUE THREAD

**Issue by manuelcanepa** [Microsoft/vscode#72948]
Issue Type: <b>Bug</b>

Step to reproduce error:

1. Install WinSSHFS 
2. Connect WinSSHFS to remote unix server (CentOS in my case)
3. Open dir from that remote device with Visual Code
4. Try to delete one file
5. Error message: "Illegal state: service accessor is only valid during the invocation of its target method"

Spec:

5. The file is deleted

Note: This just happen in some specific version, i have this setup (Running VSCode from windows and project on remote) for a while.

VS Code version: Code - Insiders 1.34.0-insider (a31dcc38f2b09a623fc9239d9004e74b6f0765f6, 2019-04-22T05:20:31.160Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (3.57GB free)|
|Process Argv|--folder-uri file:///i%3A/sparta2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.0.13
laravel-blade|cjh|1.1.2
githistory|don|0.4.6
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
apacheconf-snippets|eim|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
csharpfixformat|Leo|0.0.81
angular-localization-helper|man|0.2.1
rainbow-csv|mec|1.0.0
vscode-remote-workspace|mkl|0.42.0
vscode-apache|mrm|1.2.0
vscode-language-pack-es|MS-|1.33.2
python|ms-|2019.4.11987
csharp|ms-|1.19.0
vsliveshare|ms-|1.0.91
laravel-blade|one|1.18.0
laravel-extension-pack|one|0.4.0
laravel5-snippets|one|1.5.0
sass-indented|rob|1.5.1
laravel-artisan|rya|0.0.25
vscode-scss-formatter|sib|1.4.1
php-formatter|Sop|0.2.4
markdown-all-in-one|yzh|2.2.0

</details>

**Comment by bpasero** [comment]
@isidorn I think you just fixed this right?

**Comment by manuelcanepa** [comment]
My bad. #72830

**Comment by isidorn** [comment]
@bpasero yup
