### ISSUE TITLE
preLaunchTask don't start unless multiple click on Start/Restart button

### ISSUE THREAD

**Issue by mic4126** [Microsoft/vscode#72950]
Issue Type: <b>Bug</b>

Step 1: start debug (Sometime this will prompt error say cannot trace the specific task)
Step 2: Single click Restart button (almost everytime will prompt the error above)
Step 3: Click Restart button until terminal start webpack

Attached launch,json and tasks.json 
[launch.txt](https://github.com/Microsoft/vscode/files/3123590/launch.txt)
[tasks.txt](https://github.com/Microsoft/vscode/files/3123591/tasks.txt)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (16.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.33.2
debugger-for-chrome|msj|4.11.3
vscodeintellicode|Vis|1.1.5

</details>

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If yes can you please create a repository on github for which you can always reproduce this so we investigate more on our machines. Thanks

**Comment by mic4126** [comment]
preLaunchTask seem fine in insider build.

**Comment by isidorn** [comment]
Then closing as it is fixed.
 You can use insiders, or wait for the next stable release in a couple of weeks. Thanks
