### ISSUE TITLE
Terminal Disappears on Esc key while using Vim

### ISSUE THREAD

**Issue by UthaiahBollera** [Microsoft/vscode#7295]
- VSCode Version:1.2
- OS Version:OSX EI Captain 10.11.1

Steps to Reproduce:

1. Open integrated Terminal (Cntrl+~)
2. Open any file using Vim
3. Change the file and press Esc key , the terminal disappears.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6455, fix coming in v1.3
