### ISSUE TITLE
Snippet tab stop not working under certain circumstance

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#72963]
Steps to Reproduce:

1. set up snippets in `typescriptreact.json`
```
  "react fc": {
    "prefix": "reactFC",
    "body": [
      "import React from 'react'",
      "",
      "const $1: React.FC = () => (",
      "  $2",
      ")",
      "",
      "export default $1"
    ]
  },
  "react fc2": {
    "prefix": "reactFC",
    "body": [
      "import React from 'react'",
      "",
      "const $1: React.FC = () => (",
      "  $2",
      ")",
      "",
      "export default $1 " // <- this space here is the only difference
    ]
  },
```
2. Try invoking the snippets in a `tsx` file, and move to tabstop $1 and $2
`reactFc<tab>Test<tab>`
result is:  
`reactFC` - tab is inserted after first tabstop $1
![image](https://user-images.githubusercontent.com/2313018/56852343-99170680-691a-11e9-9592-d1240333d450.png)
`reactFC2` - tabstop $2 is correctly reached
![image](https://user-images.githubusercontent.com/2313018/56852348-ae8c3080-691a-11e9-8646-23383666f8de.png)
_After saving, the extra space is auto-trimmed. Thankfully._

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>
Extensions are all disabled

**Comment by jrieken** [comment]
this is likely the same as https://github.com/Microsoft/vscode/issues/72862

**Comment by ackvf** [comment]
Yes, I guess this is a duplicate. I hope that the little detail in my report helps a bit at least.
