### ISSUE TITLE
Markdown syntax highlighing confused by backslashes and quotes

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#7296]
- VSCode Version: 1.1.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Open the attached file [markdown.txt](https://github.com/Microsoft/vscode/files/301913/markdown.txt) in VSCode.

2.  Enable word wrap to be able to view the entire paragraph.

3.  Rename the file to have the '.md' extension identifying it as Markdown

4.   Observe syntax coloring of the markdown text.   The entire sentence starting with the phrase "One set of encoded values" is inappropriately colored blue because the syntax highlighting code in VSCode is confused by the example.   

Note: results from processing this markdown using grunt-markdown results in HTML producing the desired effect, the flaw seems to be in the markdown highlighting logic.

**Comment by cbreeden** [comment]
Looks like a duplicate of #7099

**Comment by BurtHarris** [comment]
I'll go ahead and close this one if you think it's a dupe
