### ISSUE TITLE
Add action for toggling editor group maximize

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#72968]
We have actions to maximize an editor group and to reset editor groups sizes: `workbench.action.minimizeOtherEditors` and `workbench.action.evenEditorWidths` but there's no way to bind these is such a way that the same keybinding can toggle between maximized and not maximized.

I'd like to request an action such as `workbench.action.toggleEditorGroupMaximize`.

This is related to https://github.com/Microsoft/vscode/issues/24163 but I think is a better solution.

**Comment by bpasero** [comment]
I pushed a new action "Toggle Editor Group Sizes" with command ID `workbench.action.toggleEditorWidths` that will:
* maximize the active editor group unless maximized already
* even out the editor widths otherwise
