### ISSUE TITLE
Preserve maximized editor groups after window size changes

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#72969]
**Short Version**
When using `workbench.action.minimizeOtherEditors` which group is currently maximized stops updating with editor focus changes if the window size changes.

**Long Version**
After using `workbench.action.minimizeOtherEditors` the editor group that is maximized will automatically change based on which editor group currently has focus. Assume I have 2 groups, left and right. If I have an editor in the right group focused and I maximize it then the right group becomes larger and the left group becomes smaller. If I then move focus to the left group the left group becomes larger and the right group becomes smaller.

If I resize the window to be smaller, this continues to work as expected.

However, if I resize the window to be larger, this behavior breaks. Moving focus between groups will no longer update which group is currently maximized.

It appears to me that when the window becomes larger vscode 'forgets' that the editors are in a maximized state and thinks the groups have been resized manually. I have to use `workbench.action.evenEditorWidths` to reset the group widths then use `workbench.action.minimizeOtherEditors` again to get back to a state where things are working correctly.

I can easily trigger this bug by either toggling fullscreen mode or simply grabbing the corner of the window to resize it slightly smaller.

**Steps to Reproduce**

Two ways.

First
1. Open two editor groups side by side
2. Exit fullscreen mode
3. Use `workbench.action.minimizeOtherEditors` to maximize one of the groups
4. Move focus to the other group
5. Notice that the newly focused group becomes maximized
6. Enter fullscreen mode
7. Move focus to the other group
8. Notice that the newly focused group _does not_ become maximized

Second
1. Open two editor groups side by side
2. Exit fullscreen mode
3. Use `workbench.action.minimizeOtherEditors` to maximize one of the groups
4. Move focus to the other group
5. Notice that the newly focused group becomes maximized
6. Grab the window corner and resize the window to be slightly larger
7. Move focus to the other group
8. Notice that the newly focused group _does not_ become maximized

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
OS: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
@joaomoreno bug in the grid? I see how this breaks when making the window larger, but not the other way around...

**Comment by joaomoreno** [comment]
I have resumed this into https://github.com/microsoft/vscode/issues/73453, will close this one. Thanks!
