### ISSUE TITLE
Completion selections don't change the sorting

### ISSUE THREAD

**Issue by yzhang-gh** [Microsoft/vscode#72966]
#22839 said the recent selection will be pre-selected. However, the [Dictionary Completion](https://marketplace.visualstudio.com/items?itemName=yzhang.dictionary-completion) extension seems not to benefit from this. Is there anything we should do on the extension side?

![sort](https://user-images.githubusercontent.com/7588612/56853357-6bcc5780-691e-11e9-8b35-40f4d77a18f1.gif)

**Comment by jrieken** [comment]
Do have the setting `editor.suggestSelection` configured? What is its value?

**Comment by yzhang-gh** [comment]
I didn't change it. It is the default value `recentlyUsed`.

![setting](https://user-images.githubusercontent.com/7588612/56888389-bf988700-6a6b-11e9-8b12-bfd7092308ae.png)

**Comment by jrieken** [comment]
Ok, you should use `recentlyUsedByPrefix` then, `recentlyUsed` stores selection only when typing, e.g `a` in your sample, hasn't selected a suggestion

**Comment by yzhang-gh** [comment]
Thank you! `recentlyUsedByPrefix` does the trick.

However, it (`recentlyUsed`) is a bit confusing. Could you point me to the issue where this feature was introduced, if there is one?
