### ISSUE TITLE
Setting to reuse diff tab in source control instead of opening new one

### ISSUE THREAD

**Issue by HorstBaerbel** [Microsoft/vscode#72961]
I love VSCode and the source control support (thanks a bunch), but one thing that really bugs me is that when clicking on a modified file in source control a new tab is opened every diff. I'd love to have an option to always reuse the existing tab for every diff. That would save me a lot of clicks...
I use VSCode 1.33.1 on Ubuntu 18.04. I searched the docs, but found nothing.

**Comment by gjsjohnmurray** [comment]
Sounds like you have set `"workbench.editor.enablePreview": false` to disable [preview mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode).

**Comment by gjsjohnmurray** [comment]
When preview mode is enabled (the default), clicking on a modified file on the Source Control view will open the diff in a preview tab (italic caption). Clicking another modified file shows its diff in the same preview tab.

**Comment by HorstBaerbel** [comment]
I found out this it due to the "Tab cycle" / mpontus.tab-cycle extension. If I turn it off it works as expected. Sorry for not testing that.

**Comment by HorstBaerbel** [comment]
I filed an issue in the [tab-cycle repo](https://github.com/mpontus/tab-cycle/issues/1).
