### ISSUE TITLE
Zoom in/out

### ISSUE THREAD

**Issue by nOob1que** [Microsoft/vscode#72962]
Issue Type: <b>Bug</b>

Zoom in/out enlarges UI elements with text, not only text;

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (6.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
@nOob1que can you please file individual issues as individual issues and not one? I think you mean to file 2 issues.

**Comment by nOob1que** [comment]
> @nOob1que can you please file individual issues as individual issues and not one? I think you mean to file 2 issues.

Done.

**Comment by bpasero** [comment]
@nOob1que to rephrase this issue, you want to change the font size of the workbench, would that be accurate?

**Comment by nOob1que** [comment]
Yes, font size, without UI elements.
