### ISSUE TITLE
less variable undefined

### ISSUE THREAD

**Issue by Pfeifakopf** [Microsoft/vscode#72960]
- VSCode Version:
Version: 1.33.1 (user setup)
Node.js: 10.2.0
- OS Version:
Betriebssystem: Windows_NT x64 10.0.17763

Steps to Reproduce:

1.  create main.less
2.  create variables.less
2.  create downloads.less
3.  import variables.less to main.less
4.  edit downloads.less with variables
5.  error variable is undefined
![image](https://user-images.githubusercontent.com/3351449/56851317-e80a6f00-690d-11e9-91de-3425190dec73.png)
6. less intellisense finds the variable
![image](https://user-images.githubusercontent.com/3351449/56851277-7b8f7000-690d-11e9-9083-71fe78efc9ca.png)

Steps with no effect:
- uninstall all extensions
- deactivate css.validate & less.validate
- change from utf8 to utf8 with bom

Someone can help? Thanks!

**Comment by octref** [comment]
Likely caused by your less extension. Please report to its GitHub repo instead of VS Code.
