### ISSUE TITLE
How to get logs in vscode debug console

### ISSUE THREAD

**Issue by 10142904** [Microsoft/vscode#72979]
🚨 The issue tracker is not for questions 🚨
I want to make vscode's extension which can get log in debug console and make suggestions for errors, but i dont know how to get the log, So my question is if have some documentation to manipulate debug console messages or how i can work with debug console messages in my vscode extension.

**Comment by isidorn** [comment]
Checkout the debug adapter protocol https://microsoft.github.io/debug-adapter-protocol/
You could add a debug adapter tracker to listen on all the debug protocol messages https://github.com/Microsoft/vscode/blob/28c7d9976fa6abe7f080259cf6dd19da3b78b761/src/vs/vscode.d.ts#L8854
