### ISSUE TITLE
Invisible terminal text

### ISSUE THREAD

**Issue by Ahmed-Nematallah** [Microsoft/vscode#72974]
Issue Type: <b>Bug</b>

Open any terminal window
The initial view has no text (though scrolling up shows some stuff)
I'm currently using powershell

Pressing enter goes to the next line and the text is visible there.

![image](https://user-images.githubusercontent.com/19266669/56856025-7274c200-6952-11e9-8976-a388198c0ca5.png)

When I use CMD, the first line is visible, but typing jumps to a weird location (and scrolls away from the current line) This also seems to indicate that there is a problem with the default cursor location?

![image](https://user-images.githubusercontent.com/19266669/56856090-b1efde00-6953-11e9-9832-640c6d59c5cd.png)

I've tried different renders, but that didn't help.

I've tried disabling all extensions, and reloading VS code, and also didn't help.

After pressing enter, everything works well though.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.81GB (7.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
macos-modern-theme|dav|1.1.3
file-icons|fil|1.0.17
theme-macos-classic|hua|1.1.1
latex-workshop|Jam|6.5.0
python|ms-|2019.4.11987
cpptools|ms-|0.22.1
veriloghdl|msh|1.0.3
material-icon-theme|PKi|3.7.0
platformio-ide|pla|1.7.1
vscode-icons|vsc|8.6.0

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
