### ISSUE TITLE
JSON-formatted cli extension info (details + enabled/disabled)

### ISSUE THREAD

**Issue by jsejcksn** [Microsoft/vscode#72970]
See #19083, #37620, #69090

Currently, I know of two ways to get extension information:

One way, in a shell:

```bash
code --list-extensions [--show-versions]
```

which produces the an extension `id` (and, optionally, version) followed by a newline character for each installed extension:

```
dbaeumer.vscode-eslint[@1.8.2]
ms-vsliveshare.vsliveshare[@1.0.91]
...
```

And the other way, in VS Code:

1. Toggling the Extensions panel
2. Right-clicking on an extension
3. Selecting "Copy Extension Information"

<img width="488" alt="vscode-copy-extension-information" src="https://user-images.githubusercontent.com/868251/56854649-c73b1d00-68ff-11e9-9741-b35d7f099769.png">

which produces this output in the clipboard:

```
Name: ESLint
Id: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 1.8.2
Publisher: Dirk Baeumer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
```

I would like the ability to output extension information in JSON format when using the cli argument `--list-extensions`. This option could be implemented with an additional argument such as `--json` and used like the `--show-versions` argument:

```bash
code --list-extensions --json
```

I propose that the output would be a JSON-formatted array of objects representing each installed extension containing the information provided via the "Copy Extension Information" command, and additionally providing a boolean attribute for whether the extension is enabled. It would look like this:

```json
[
  {
    "name": "ESLint",
    "id": "dbaeumer.vscode-eslint",
    "description": "Integrates ESLint JavaScript into VS Code.",
    "version": "1.8.2",
    "publisher": "Dirk Baeumer",
    "link": "https://marketplace.visualstudio.com/items?itemname=dbaeumer.vscode-eslint",
    "enabled": true
  },
  {
    "name": "Live Share",
    "id": "ms-vsliveshare.vsliveshare",
    "description": "Real-time collaborative development from the comfort of your favorite tools.",
    "version": "1.0.91",
    "publisher": "Microsoft",
    "link": "https://marketplace.visualstudio.com/items?itemname=MS-vsliveshare.vsliveshare",
    "enabled": false
  }
]
```

This would allow programmatic retrieval of extension information and status.

**Comment by sandy081** [comment]
@jsejcksn What is the usecase and why you need this?

**Comment by jsejcksn** [comment]
Hi @sandy081: I am not aware of another way to get a list of all installed extensions with information about which ones are enabled and which ones are disabled. This export would be a first step in being able to store the information so that the current extension state can be replicated in another instance of VS Code.

**Comment by sandy081** [comment]
So you are trying to sync extensions? There is an extension already in market place that does it already - https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

Have you tried this?

**Comment by jsejcksn** [comment]
Yes, I have tried that extension previously, but it introduces dependencies which don't need to be present for this functionality:

  - installation of that extension
  - a GitHub account
    - giving that extension OAuth access to a GitHub account

Using that extension also makes the user's settings public by syncing them to a GitHub gist. GitHub gists cannot be made private, only "secret" (security through obscurity).

**Comment by sandy081** [comment]
I do not think we have plans/cycles to implement this request unless it is highly requested. So I would close this as out of scope and revisit this if more users request for the same.

On the other hand, We have a feature request to support synchronisation of settings across machines. Synchronising extensions will also be supported while implementing that. https://github.com/Microsoft/vscode/issues/2743

**Comment by jsejcksn** [comment]
@sandy081 How can I get a list of enabled extensions vs disabled extensions in VS Code?

**Comment by sandy081** [comment]
@jsejcksn You cannot right now, but there is a request already asking for it - #14444
