### ISSUE TITLE
Highlight currently open file in Source Control tab - just like in Explorer's "Open Editors"

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#72973]
Please highlight the current file in Source Control tab. Here's a visualization:

![image](https://user-images.githubusercontent.com/611746/56855615-b09cc200-690f-11e9-9157-f4622ec8a76a.png)

It's extremely useful to know which file is currently being edited - for the purpose of clicking the `+` button on it when merge conflict has been resolved.

Workaround: execute `Git: Stage Changes` command.

Related feature request for Explorer: https://github.com/Microsoft/vscode/issues/64210

**Comment by joaomoreno** [comment]
Pushed. Also introduced a `scm.autoReveal` setting to disable this behavior.

**Comment by jrieken** [comment]
This only works when using tree-mode, not in list-mode
