### ISSUE TITLE
Find in files tree view frequently breaks

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#72971]
When using Find in Files I quite frequently get into a state where it starts spitting out `Tree element not found: [object Object]`

I tend to see it after I have opened a search result (moving focus away from the search panel) and then trying to do some operation with the search tree view. For example, using `search.action.focusNextSearchResult` or `list.collapse`

Steps to Reproduce:
There are lots of ways to cause this to happen. Here's a few I can easily repro:

Case 1
1. Do a search
2. Open a search result (focus will move to the editor)
3. Close the editor
4. Return focus to the search panel (`search.action.focusSearchList`)
5. Try to open the search result
6. Notice the error `Tree element not found`

Case 2
1. Do a search
2. Open a search result (focus will move to the editor)
3. Close the editor
4. Use `search.action.focusNextSearchResult`
5. Notice the error `Tree element not found`

Case 3
1. Do a search
2. Open a search result (focus will move to the editor)
3. Close the editor
4. Return focus to the search panel (`search.action.focusSearchList`)
5. Use `list.collapse`
6. Notice the error `Tree element not found`

I think it has something to do with the fact that I have `search.action.focusSearchList` bound so that I can return to the search panel without resetting focus back to the search box (which is another issue in it's own right).

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
OS: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Thanks for the detailed steps, I think this has been fixed in the latest Insiders, could you try your scenario there?

https://code.visualstudio.com/insiders

**Comment by akbyrd** [comment]
I don't have insiders installed and I'd have to fuss with settings and keybindings to repro it properly. I'll just wait for the next non-insiders release.
