### ISSUE TITLE
Ctrl + c or v or x is not working

### ISSUE THREAD

**Issue by sanky72** [Microsoft/vscode#72982]
Issue Type: <b>Bug</b>

the ctrl +c or v or x is not working. It was working before but now it's not.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|0.5.0
vscode-emacs|har|0.1.7
cpptools|ms-|0.22.1

</details>

**Comment by LWChris** [comment]
Could this be related to the emacs extension? The keybindings are working on my system.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by CAspeling** [comment]
Mine wasn't working either. Had to fully close, restart machine and open project again. It's since the last update that sometimes after having VSCode open for a while that it does that. Very annoying.

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by jrieken** [comment]
no actionable information provided
