### ISSUE TITLE
Chinese characters displayed overlapped.

### ISSUE THREAD

**Issue by MonsterSupreme** [Microsoft/vscode#7298]
- VSCode Version: 1.2.0
- OS Version: Windows 10, Traditional Chinese

Steps to Reproduce:

1. Ctrl+`
2. There will be Chinese characters overlapped in the Terminal.
![2016-06-07_140308](https://cloud.githubusercontent.com/assets/1573411/15847791/4c45db54-2cbb-11e6-8211-b81aaf34410b.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7062
