### ISSUE TITLE
Integrated Terminal opening as External Terminal

### ISSUE THREAD

**Issue by DeJayDev** [Microsoft/vscode#72983]
- VSCode Version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
- OS Version: Windows_NT x64 10.0.18362

Also Reproducible on:
- VSCode *Insiders* Version: Code 1.34.0-insider (c1abf7978d59415dcfcf8cfcb15e0ee30c5e45a5, 2019-04-26T13:39:29.623Z)

Steps to Reproduce:
1. Run the `Open New Terminal` keybind (`Ctrl` + `Shift` + `C`)
2. Observe. 
2b. Or, see gif! 
    * After I write "hi :)" I run the keybind.
![This should be a gif.](https://u.dejay.dev/2125e.gif)

Does this issue occur when all extensions are disabled?: 
Yes (Above gif recorded with extensions disabled.)

**Comment by DeJayDev** [comment]
Fixed:

Use the right command 🤦‍♂ 

`Terminal: Create New Integrated Terminal` (`Ctrl` + `Shift` + `` ` ``)

Hopefully this prevents someone else from having the same issue.

**Comment by Tyriar** [comment]
Also ctrl+` toggles the panel (which will create a terminal if it didn't exist yet). 🙂

**Comment by VivianKeith** [comment]
Hello, I'm a novice at VS code. May I ask a question sounds simple? What does the option ***" Explorer Kind, Customizes what kind of terminal to launch. integrated or external "*** do??? It seems like I can create a new integrated terminal panel by ```Ctrl```+```shift```+``` ` ```  or ```Ctrl``` + ``` ` ``` rather than an external one, although I choose ***integrated***. I can't find a satisfactory answer in any way. Could you help me??
@DeJayDev 

> * VSCode Version: Code 1.33.1 ([51b0b28](https://github.com/microsoft/vscode/commit/51b0b28134d51361cf996d2f0a1c698247aeabd8), 2019-04-11T08:27:14.102Z)
> * OS Version: Windows_NT x64 10.0.18362
> 
> Also Reproducible on:
> 
> * VSCode _Insiders_ Version: Code 1.34.0-insider ([c1abf79](https://github.com/microsoft/vscode/commit/c1abf7978d59415dcfcf8cfcb15e0ee30c5e45a5), 2019-04-26T13:39:29.623Z)
> 
> Steps to Reproduce:
> 
> 1. Run the `Open New Terminal` keybind (`Ctrl` + `Shift` + `C`)
> 2. Observe.
>    2b. Or, see gif!
>    
>    * After I write "hi :)" I run the keybind.
>      ![This should be a gif.](https://camo.githubusercontent.com/3984d062b7b52a56a075ab29748bab496aa86a2b/68747470733a2f2f752e64656a61792e6465762f32313235652e676966)
> 
> Does this issue occur when all extensions are disabled?:
> Yes (Above gif recorded with extensions disabled.)

**Comment by Tyriar** [comment]
@VivianKeith it's which terminal to open when you use the context menu in the explorer:

<img width="302" alt="Screen Shot 2019-05-21 at 9 23 23 PM" src="https://user-images.githubusercontent.com/2193314/58147296-b637b000-7c0e-11e9-8bb8-fffc6304c2b0.png">
