### ISSUE TITLE
Tabs are missing every time after I installed the updates

### ISSUE THREAD

**Issue by yipu0v0** [Microsoft/vscode#72984]
- VSCode Version: lastest
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:
I have already found one similar existing issues, but my situation was different. I have already encountered this for 2 times without changing any config. It's this a bug or built-in action? which in my mind is totally not reasonable.

Does this issue occur when all extensions are disabled?:  Don't know

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jrieken** [comment]
no actionable information provided
