### ISSUE TITLE
Compare not working with File Encoded with UTF16 LE

### ISSUE THREAD

**Issue by datauduong** [Microsoft/vscode#72985]
Visual Studio Source Control, can't compare file encoded with UTF16 LE, it is showing grabbage on the Original file and properly show the file that is change.

Step to Reproduce
1. create a file with UTF-16 LE
2. commit to GitHub.
3. make a change to the same file.
4. going to source control on the left-hand side of Visual Studio Click on the changed file to see what has changed.

<img width="857" alt="compare_not_working" src="https://user-images.githubusercontent.com/2460101/56857939-5acf2500-69b6-11e9-9b22-aff50957f059.png">

**Comment by bpasero** [comment]
@datauduong does the file have a BOM (byte order mark) or not?

**Comment by datauduong** [comment]
@bpasero, yes the file contains BOM mark.
<img width="475" alt="open_with_encoding_windows1252" src="https://user-images.githubusercontent.com/2460101/56867435-8559c600-6a28-11e9-9cdf-9c593c246879.png">

**Comment by bpasero** [comment]
Ok, I thought the Git extension had a bit of encoding detection to support this case. At least UTF-16 BOMs are very easy to detect.

**Comment by datauduong** [comment]
I hope this could be included in the next fix.

**Comment by datauduong** [comment]
Found the fix for my issue:
https://github.com/Microsoft/vscode/issues/21146

joaomoreno commented on Mar 27, 2018
Fixed by having git attempt to detect encoding when files.autoGuessEncoding is enabled. Some encodings are still improperly detected: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding+label%3Aupstream
