### ISSUE TITLE
Colour preview swatches not shown in some JSON files

### ISSUE THREAD

**Issue by krupenja** [Microsoft/vscode#72996]
- VSCode Version: 1.34.0-insider c1abf7978d59415dcfcf8cfcb15e0ee30c5e45a5
- OS Version: 10.14.4 (18E226)

Steps to Reproduce:

1. Launch VSCode with an empty profile and all extensions disabled.
2. Create a new file, set Language Mode to JSON (or JSON with comments).
3. Paste in the following code:

```json
{
    "name": "Flat White Theme",
    "tokenColors": [
        {
            "settings": {
                "background": "#F5F5F5",
                "foreground": "#333333"
            }
        }
    ],
    "colors": {
        "focusBorder": "#A6B39B",
        "pickerGroup.foreground": "#A6B39B"
    }
}
```

4. Save the file.

Colour preview boxes are not shown:
![image](https://user-images.githubusercontent.com/26354715/56864489-9d4f2c80-69cb-11e9-8d2b-2a0cf3b1738c.png)
Also reproducible in 1.33.1 stable. Reproducible with all the default themes I have tried.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
For the color swatches to show in JSON, the JSON file needs to be [associated with a JSON schema](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings) and the schema needs to define `"format": "color-hex"` on the property.

In your example, you could rename you file to *-color-theme.json* so it gets associated with the color theme schema.

**Comment by krupenja** [comment]
Thank you so much for the explanation! That solved the problem.
