### ISSUE TITLE
Could extension show his setting as exclude setting?

### ISSUE THREAD

**Issue by sumneko** [Microsoft/vscode#72991]
Issue Type: <b>Feature Request</b>

![TIM图片20190428173543](https://user-images.githubusercontent.com/5213431/56862299-22dad880-69dc-11e9-8ddb-ef257e9de8cd.png)
![TIM图片20190428173603](https://user-images.githubusercontent.com/5213431/56862304-2b331380-69dc-11e9-8069-1d4584dddfa2.png)
![TIM图片20190428173949](https://user-images.githubusercontent.com/5213431/56862368-a98fb580-69dc-11e9-9769-6faa21e0ef24.png)

Setting of "files.exclude" shows a beautiful and convenient interface, however extensions can only show "edit in setting.json" even if they use the same properties, because who can use "ExcludeSetting" is hard coded.
So please let us use the "ExcludeSetting", thank you.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/62440
