### ISSUE TITLE
[folding] make max folding region limit configurable

### ISSUE THREAD

**Issue by Lovecircle** [microsoft/vscode#72994]
- VSCode Version: 1.32.1
- OS Version: Win7 x64

Steps to Reproduce:

1. Set in editor settings:
`"editor.folding": true,
"editor.foldingStrategy": "indentation"`

2. Open the attached file and go to line 43914 where folding stopped working.

[test_ident.zip](https://github.com/Microsoft/vscode/files/3124928/test_ident.zip)

3. Delete couple of blocks of code - folding starts working again.

Developer of folding extension "Explicit Folding" pointed out to me that there is a hard limit of 5000 foldings per file. If it is so than I guess this is not a bug report but a feature request for editor setting in order to increase this limit.  In my case, folding stopped working in file with about 35000 lines - which is not that many.

Does this issue occur when all extensions are disabled?: Yes

**Comment by robcowart** [comment]
Is there any plan to address this? It is quickly becoming a show-stopper us.

**Comment by gse4me** [comment]
Any news on this feature ?

**Comment by zahanm** [comment]
I looked through, and these look like the relevant spots where this limit is currently hardcoded

https://github.com/microsoft/vscode/blob/9dd4f31a21d63deea5e1fc322cfc802413b31d95/extensions/markdown-language-features/src/features/foldingProvider.ts#L11
https://github.com/microsoft/vscode/blob/9dd4f31a21d63deea5e1fc322cfc802413b31d95/src/vs/editor/contrib/folding/syntaxRangeProvider.ts#L14
https://github.com/microsoft/vscode/blob/9dd4f31a21d63deea5e1fc322cfc802413b31d95/src/vs/editor/contrib/folding/indentRangeProvider.ts#L14
https://github.com/microsoft/vscode/blob/9dd4f31a21d63deea5e1fc322cfc802413b31d95/src/vs/workbench/contrib/notebook/browser/contrib/fold/foldingModel.ts#L203
https://github.com/microsoft/vscode/blob/9dd4f31a21d63deea5e1fc322cfc802413b31d95/src/vs/editor/contrib/folding/folding.ts#L58

Making it configurable, similar to `editor.largeFileOptimizations` seems preferable. Though it is of course a "shoot yourself in the foot" situation.
