### ISSUE TITLE
[CSS] Add specificity to hover

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#7299]
Currently when one hovers over a selector in a CSS file it gives a preview of what it selects. This is useful for beginners or if you just forget what a particular selector does.

What would make this even more useful is to also include the specificity of the selector in the preview popup. Many beginners/intermediate don't understand specificity, which is why you often see super specific selectors all over. Even for experts, it would be quicker than calculating yourself for longer selectors.

Example:

```
-----------------------------
<select>
…
<option :checked>
Specificity: 0,1,2
-----------------------------
select option:checked
```

Note: I used how CSS2.1 defines specificity. CSS3 Selectors defines it as 012, which I think is confusing as it makes it look like if there were 10 classes or pseudo classes it would be 102 rather than 0102. CSS 4 Selectors shows it as a=0 b=1 c=2.

Code already exists to calculate specificity in JS if you want to add using 3rd party code https://github.com/keeganstreet/specificity

**Comment by aeschli** [comment]
Good idea.

**Comment by yisibl** [comment]
Good idea.

Safari: 
![](https://img.alicdn.com/tps/TB1Z3BwKpXXXXXUapXXXXXXXXXX-300-259.png)

**Comment by debugme** [comment]
Would definitely be interested in seeing this too.

**Comment by asifkabani** [comment]
Hi was just wondering if this is still going on? I just realized how badly I need this.

**Comment by aeschli** [comment]
The code for the css selector hover is here: https://github.com/Microsoft/vscode-css-languageservice/blob/10853bb159d78214f3a8f6219ddc1213ea490d00/src/services/cssHover.ts#L28

**Comment by asifkabani** [comment]
@aeschli how would I implement this?

**Comment by Ragnoroct** [comment]
@aeschli Would it be okay if I added the npm module [specificity ](https://www.npmjs.com/package/specificity) or do you want the calculation to be custom?

@dstorey In your example you grouped the specificity and the html together.
Does this work as well? The specificity is separate and treated as text.
![image](https://user-images.githubusercontent.com/19155205/47535395-01f4c780-d881-11e8-92c6-aa40432cdf93.png)

Note: I'm going to remove the first score and comma because inlining inside a css document is impossible.

**Comment by aeschli** [comment]
@Ragnoroct No node module dependencies, also don't copy any code. We should make our own implementation based on the [spec](https://www.w3.org/TR/selectors-3/#specificity).
Most of the node module is about parsing he code but we already have an AST with all the information.

**Comment by aeschli** [comment]
implemented by https://github.com/Microsoft/vscode-css-languageservice/pull/129

**Comment by joaomoreno** [comment]
@aeschli I am confused, why did you add `testplan-item` to this?

**Comment by aeschli** [comment]
I mean 'on-testplan'.
