### ISSUE TITLE
Python parser-16 always on cannot disable linting on files

### ISSUE THREAD

**Issue by fiddycodes** [Microsoft/vscode#72997]
Issue Type: <b>Bug</b>

1. Install the python langauge server that is required.
2. Open a python file

Linting happens automatically and gives the source as python Parser-16. I have disabled all python linting in Visual Studio Code.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
Bookmarks|ale|10.4.3
vscode-browser-preview|auc|0.5.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
disableligatures|Coe|0.0.8
gitlens|eam|9.6.3
vscode-npm-script|eg2|0.3.5
carbon-now-sh|eri|1.2.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.8
vscode-pull-request-github|Git|0.6.0
todo-tree|Gru|0.0.130
vscode-power-mode|hoo|2.2.0
latex-workshop|Jam|6.5.1
vscode-peacock|joh|2.1.1
unity-code-snippets|kle|1.3.0
restructuredtext|lex|106.0.0
python|ms-|2019.4.11987
csharp|ms-|1.19.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.7.0
java|red|0.43.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.2.9
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.7.5
unity-tools|Tob|1.1.0
unity-debug|Uni|2.7.2
highlight-matching-tag|vin|0.9.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.2
ws-rainmeter|wil|0.2.7
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.2.0

(2 theme extensions excluded)

</details>

**Comment by bn-l** [comment]
I had this problem as well. It seems it is impossible to disable error checking / linting in python with vscode. Getting the same error message twice from "parser-16"

**Comment by fiddycodes** [comment]
Turns out the error for me was coming from the JavaScript extension pack or the visual studio intellisense extension. Uninstalling these seemed to get rid of the of the problem and now the limiting is disabled again. Hope this helps.

**Comment by bn-l** [comment]
Yeah, you can disable the python language server (i.e. python error / syntax checking) but then you get a warning every single time you open the file and the only way to stop the warning is to disable intellisense everywhere.

This issue was closed to early. *Guy with gold watch tapping head meme*: You never need to solve issues if you just close them.

Not to get on the soap box here but vscode is seems to be a massively feature creeping without solving fundamental issues like this one. I suppose it's not as fun or rep worthy.
