### ISSUE TITLE
add support for TFVC in on-premise TFS resp. Visual Studio Team Services

### ISSUE THREAD

**Issue by Daniel-Steiner** [Microsoft/vscode#73]
both TFS 2015 and VSO support REST API to access TFVC besides GIT and therefore it would be possible to add basic support for TFVC.

**Comment by mrcaron** [comment]
YES!! :+1:

**Comment by egamma** [comment]
The other thing missing is an 'scm provider' API, that currently does not exist.

**Comment by Code-DJ** [comment]
Does it mean implementing in javascript something like this? https://github.com/apache/maven-scm/tree/master/maven-scm-providers/maven-scm-provider-tfs

and/or SOAP in JavaScript:
http://www.codeproject.com/Articles/12816/JavaScript-SOAP-Client

I have not gone into the details of either project so don't know if those are too simplistic or incomplete projects.

**Comment by egamma** [comment]
@Code-DJ this is the next step. What I mean by an 'SCM provider API' is an API that avoids that you end up with a git viewlet, a TFS viewlet, a mercurial viewlet, etc. The provider API abstracts a bit from the underlying SCM so that you can build some common UI on top of it.

**Comment by jennylu89** [comment]
yes, please!!!!

**Comment by seanmcbreen** [comment]
Plugable SCM support in included in 1.11 🎉 
http://code.visualstudio.com/docs/extensionAPI/api-scm 

@joaomoreno was the guy and with luck we will see additional SCM providers popping up soon.  We know of at lest two and I'm going to let those authors tell you about them when they are ready but I know they are very close.  One of the teams works in Microsoft :)

Thanks everyone for pushing for this.

Sean - VS Code team member

**Comment by seanmcbreen** [comment]
Good news, the Visual Studio Team Services team just updated their extension:
https://marketplace.visualstudio.com/items?itemName=ms-vsts.team

The extension now supports TFVC using the new SCM Provider model.

So I'm going to close this request and let you start to give the extension a try and provide feedback in that repo.

Thank you all,
Sean
