### ISSUE TITLE
Allow debugging an extension with a native napi addon

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#73008]
I have a VS Code extension that is mostly implemented in C++ via an NAPI addon. When I debug my extension I can set breakpoints in the extension.ts, but I cannot set breakpoints or step into the native portion of the extension.

Unless I've missed something, it appears this isn't a supported workflow. None of the extension documentation I've been able to find even mentions using native addons.

Is there perhaps a workaround where I can launch the extension host process manually under cppvsdbg or something?

**Comment by isidorn** [comment]
I suggest to ask this question also here https://github.com/Microsoft/vscode-cpptools

**Comment by weinand** [comment]
@alexandrudima I remember that you did this successfully, correct?

**Comment by alexandrudima** [comment]
No, I never did C++ debugging inside a VS Code extension.

I managed to do C++ debugging inside a node native module, when running it directly from nodejs (i.e. not in a VS Code extension). Here's a launch config I managed to get working -- https://github.com/microsoft/node-native-keymap/blob/master/.vscode/launch.json
