### ISSUE TITLE
Suggestion / parameter hints rendering issues

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7300]
From @FeaRCODE

The dropdown has some issues with the icon (I dont think i am zoomed into the editor - there is no way to tell):
![image](https://cloud.githubusercontent.com/assets/6901336/15841639/6fb4c2d8-2c18-11e6-939f-cd15fdd525ce.png)

I also have an issue with the tooltip now, i am assuming it scales with fontSize?, it is VERY big now:
![image](https://cloud.githubusercontent.com/assets/6901336/15841694/a425a5c8-2c18-11e6-860d-a40b6c5e9ff2.png)

My user settings are below:

```
{
	"editor.fontSize": 15,
	"editor.roundedSelection": false,
	"editor.wrappingIndent": "indent",
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
	"editor.detectIndentation": true
}
```

**Comment by FeaRCODE** [comment]
Thanks for posting this issue. I reset my user settings, changed the zoom back to 0, and the fontSize to 15 and the icons render perfectly. However the tooltip is still a bit large. 

Again if we could set the intellisense fontSize and the tooltip fontSize that would be great.

**Comment by haibison** [comment]
May I ask if parameter hints supports Java? It seems it doesn't. I searched but couldn't find the answer.

If not, would you plan to support Java? I can make new issue if you want to.

Thanks,

**Comment by joaomoreno** [comment]
@haibison You should try out some of the [Java extensions in the Marketplace](https://marketplace.visualstudio.com/search?term=java&target=VSCode&sortBy=Relevance).
