### ISSUE TITLE
Using shellArgs.linux runs then immediately closes the terminal

### ISSUE THREAD

**Issue by j-james** [Microsoft/vscode#73007]
- VSCode Version: 1.33.1
- OS Version: Manjaro 18.0.4 Illyria

When trying to launch the integrated terminal (bash) with multiple arguments, it runs them and then closes the terminal. 

```
"terminal.integrated.shellArgs.linux": ["-c", "echo abc"]
```

To reproduce, add this to your settings.json file and try to open the integrated terminal on linux. 

Doing something like

```
"terminal.integrated.shellArgs.linux": ["-l"],
```
works fine.

Does this issue occur when all extensions are disabled? **Yes**

**Comment by Tyriar** [comment]
This is by design because `bash -c` runs the command then exits, which makes the terminal exit.
