### ISSUE TITLE
Duplicate of (VSCode Won't Quit - Icon is Gone, Application Still Open)

### ISSUE THREAD

**Issue by cbfx** [microsoft/vscode#73004]
The other two related issues were closed citing that a version upgrade was requested or that crash logs were requested. I am submitting both.

I also noticed that Github attempted to show me related issues around vs code and offline bugs. The vs code application was frozen with the mac spinning beach ball upon opening the laptop without a wifi connection present.

- VSCode Version: 1.33.1 (1.33.1)
- OS Version: Mac OS X 10.12.6
- Crash report: [Code Helper_2019-04-28-025827_Chriss-MacBook-Pro.log](https://github.com/Microsoft/vscode/files/3125260/Code.Helper_2019-04-28-025827_Chriss-MacBook-Pro.log)

**[DUPLICATE]**
Steps to Reproduce:

1. Open VS Code and leave open for a few days....
2. VS Code crashes, right-click force-quit the application
3. The black VS Code Window is still open on desktop, with the menu, but the icon is gone
4. The menu cannot be clicked into

Does this issue occur when all extensions are disabled?: Yes/No
Unsure, still trying to figure out how to shut it down so I can re-start it for the VSCode version. I also don't know how to test this again.

### Related
https://github.com/Microsoft/vscode/issues/46255
https://github.com/Microsoft/vscode/issues/62674

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)
