### ISSUE TITLE
'Real' Auto backup session feature...

### ISSUE THREAD

**Issue by erikdemarco** [microsoft/vscode#73002]
Hi I like vscode Very much. The only downside is only 1. It can’t auto backup our current work when our computer suddenly crash. It will not resume our work if the file is gone. (for example when working with Filezilla, it creates a temp file for you to work with in your local computer. When computer crash this file is also gone, because as the name suggest, its temporary file only. When the file is gone our work is gone to, vscode cant restore it. vscode can only restore if the file is still there.) the thing i can't understand is why vscode can only restore session if the file is still in there??? So the current feature is not useful when our computer crash. its not real auto save session.

You name it, I have tried every single code editor out there. The only code editor can restore file when computer crash is only Notepad++ (the way it does its job is by auto backup the current session every 7 seconds to another file). the keyword is 'another'

Yes, vscode also has “autosave" feature. But it’s totally different level of backup when compared to NotePad++. All code editor can only restore our work when the file is still there. If the original file is gone, all of them can't restore it. including vscode

That’s why i cant move from Notepad++. No other code editor offer this kind of backup.

Please vscode add this feature. I like vscode very much only because of this.

**Comment by gjsjohnmurray** [comment]
You write about Filezilla and temporary files. Are you using an extension in VSCode and editing remote files? If so, which extension?

**Comment by erikdemarco** [comment]
Idont use anything. all software is fresh install.

Its really easy to reproduce without filezilla or any ftp software:
1. do fresh install vscode.
2. create 1 file named test.txt
3. open it vscode and type something without saving
4. delete test.txt from your computer (simulate filezilla, all ftp software will delete the file you are working with when you close the ftp program or when the computer crash)
5. force close vscode from task manager (simulate computer crash)
6. open vscode, voilaa all your work is gone. nothing restored

**Comment by gjsjohnmurray** [comment]
@erikdemarco I assume you know about VSCode's existing [auto save](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) features but these don't meet your need, right?

**Comment by erikdemarco** [comment]
I reopened the issue because I keep losing all my work when my computer crash

Here's the problem once again:

I'm using filezilla to modify server file. When I'm working with my file via vscode, suddenly my electricity goes down for several hours. Then I opened vscode again it just show setting page not restoring my previous work.

Notes:
-) All app I mention is in mint condition without any additional plugin
-) Fresh install newest vscode
-) Fresh install filezilla (filezilla stores the file we are working with in /tmp folder, the file will get removed if filezilla or computer restarted/crashed)
-)Vscode will successfully restore session if I force restart by pushing reset button in my cpu (simulating crash). But vscode wont restore session if the electricity goes down for several hours, maybe something to do with ram? because ram data will get lose if there's no power supply

**Comment by erikdemarco** [comment]
@gjsjohnmurray any update about this? :(

**Comment by Tyriar** [comment]
VS Code does exactly what you're asking for already with hot exit. The problem seems to be this:

> Fresh install ftp software (all ftp software stores the file we are working with in /tmp folder, the file will get removed if computer restarted/crashed)

If the files and more importantly the folder is gone from the system, the backup system will not know how to restore them. I strongly suggest you to change your workflow as it sounds horrible, especially if your power goes out frequently. For example, instead of working on files on some server via FTP, why don't you persist them in source control (such as git) and then connect to your server and pull them down from there. Or perhaps even better we just released the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) to allow easy editing of files on a server via SSH.

There is also auto save available as @gjsjohnmurray called out and of course saving more frequently.
