### ISSUE TITLE
User defined keyboard shortcut doesn't work when editor is focused

### ISSUE THREAD

**Issue by seanmccay** [microsoft/vscode#73003]
Issue Type: <b>Bug</b>

Occurs in both stable and insiders with extensions turned off.

1. create a shortcut 'ctrl+shift+u' that runs the default test task
2. open an editor window and focus on it
3. enter ctrl+shift+u
4. see that 'u' gets printed to the editor instead of the task being run

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic (Pop!_OS 19.04)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1501)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.40GB (23.45GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
gitlens|eam|9.6.3
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
docomment|k--|0.1.6
csharp|ms-|1.19.0
vscode-typescript-tslint-plugin|ms-|1.0.0
material-icon-theme|PKi|3.7.0

</details>

**Comment by alexandrudima** [comment]
What is the content of your `keybindings.json`?

**Comment by seanmccay** [comment]
@alexandrudima my keybindings.json is:
```
 // Place your key bindings in this file to override the defaultsauto[]
[
	{
		"key": "ctrl+shift+u",
		"command": "workbench.action.tasks.test"
	},
	{
		"key": "ctrl+w",
		"command": "workbench.action.terminal.kill",
		"when": "terminalFocus"
	}
]

```

There are no workspace bindings.

**Comment by alexandrudima** [comment]
@seanmccay Is the keybinding received by VS Code?
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by seanmccay** [comment]
Using that method, code receives `ctrl+shift+u` as `unknown`.

**Comment by alexandrudima** [comment]
@seanmccay This indicates that `ctrl+shift+u` does not reach VS Code. Have you been able to use the keyboard shortcut in other software on your machine? Can you try pressing the key combination at https://www.w3.org/2002/09/tests/keys.html with Chromium?

Here I am pressing ctrl+shift+u in Chrome, the relevant bit is the `keydown(4)/(5)` which have ctrl:true, shift:true and keyCode:85. Do you see those on your machine?

![image](https://user-images.githubusercontent.com/5047891/63013512-ae458000-be8c-11e9-9985-ed3424f8866f.png)

In the past, this was most likely caused by the OS or some other 3rd party software eating up the keybinding...

**Comment by seanmccay** [comment]
Moving to Linux is more painful than I would have hoped. It's just a bunch of little things that irk. :angry: 

It looks like it gets picked up, but not on keydown? I'm not sure how to find if I've got an extension grabbing it... I don't have anything at the OS level that is set to use `ctrl + shift + u`

Here's my result:
```
keydown (0): [keyCode: 17][shift: false][ctrl: false][alt: false][meta: false]

keydown (1): [keyCode: 17][shift: false][ctrl: false][alt: false][meta: false]

keydown (2): [keyCode: 16][shift: false][ctrl: true][alt: false][meta: false]

keydown (3): [keyCode: 16][shift: false][ctrl: true][alt: false][meta: false]

keydown (4): [keyCode: 229][shift: true][ctrl: true][alt: false][meta: false]

keydown (5): [keyCode: 229][shift: true][ctrl: true][alt: false][meta: false]

keyup (6): [keyCode: 85][shift: true][ctrl: true][alt: false][meta: false]

keyup (7): [keyCode: 85][shift: true][ctrl: true][alt: false][meta: false]

keyup (8): [keyCode: 229][shift: false][ctrl: false][alt: false][meta: false]

keyup (9): [keyCode: 229][shift: false][ctrl: false][alt: false][meta: false]
```

**Comment by seanmccay** [comment]
I'm also not sure why it only occurs when the editor or a terminal is focused...

**Comment by alexandrudima** [comment]
@seanmccay Thanks for following up. Unfortunately, this means that neither we nor Chromium get the keybinding correctly and there isn't really anything we can do on our side.

From my searching, it looks like 229 is a key code that means "something was pressed", so Chromium doesn't know what it is...

IMHO, I think there is something on your system that is eating up that keybinding ... I've seen a similar issue with ctrl+shift+e on Linux (#72947) and that was related to some emoji input...
