### ISSUE TITLE
Visual Studio Code doesn't update changes of files and folders

### ISSUE THREAD

**Issue by saitam1** [Microsoft/vscode#73005]
- VSCode Version:
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.5-050005-generic (Ubuntu 18.10)

I am working on a Django project and when deleting the sqlite database + the python migration files and then running `python manage.py makemigrations` and `python manage.py migrate` to create these files again doesn't work for VSCode.
  
![vscode-issue](https://user-images.githubusercontent.com/23245678/56868444-ccc55f80-69f2-11e9-886b-7e53b53d7bce.png)

Steps to Reproduce:
1. Start a Django project
2. Delete migration files + sqlite db
3. run makemigrations & migrate

Does this issue occur when all extensions are disabled?: Couldn't find out yet

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/72916
