### ISSUE TITLE
CPU usage spikes just by opening the app

### ISSUE THREAD

**Issue by aaguilerav** [microsoft/vscode#73013]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by aaguilerav** [comment]
Issue Type: <b>Performance Issue</b>

CPU usage spikes just by opening the app, Nothing else done.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (2.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    98	 11328	code main
    0	    66	 11329	   gpu-process
    0	   213	 11330	   window (ledger-assets-ws (Workspace))
    0	    49	 11491	     watcherService
   24	    66	 11492	     extensionHost
    0	    82	 11496	     searchService
  310	    66	 11523	       electron_node package.js 
    0	    98	 11595	   shared-process
    0	    82	 11717	   window (Issue Reporter)
    0	     0	 11718	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ledger-assets-ws (Workspace))
|    Folder (LISP): 1 files
|      File types: lisp(1)
|      Conf files:
|    Folder (SCRIPTS): 28 files
|      File types: sh(18) txt(4) log(2) DS_Store(1) py(1) csv(1)
|      Conf files:
|    Folder (remix-ide): 143 files
|      File types: sol(119) js(17) md(2) sh(2) json(2) gitignore(1)
|      Conf files: package.json(1)
|    Folder (GITHUB): more than 21608 files
|      File types: h(2077) js(1708) cc(1668) go(1653) py(1551) md(1368)
|                  json(1186) cpp(1084) sol(742) html(678)
|      Conf files: sln(129) package.json(107) csproj(91) makefile(84)
|                  cmake(38) settings.json(26) tsconfig.json(23)
|                  webpack.config.js(7) grunt.js(6) tslint.json(5) tasks.json(2)
|                  launch.json(2) gulp.js(1)
|    Folder (HASHICORP): 83 files
|      File types: pem(17) sh(11) hcl(5) jks(3) old(3) cnf(2) txt(2) zip(1)
|                  yml(1) bkp(1)
|      Conf files:
|    Folder (LEDGER-ASSETS): 9064 files
|      File types: js(1689) html(1594) sol(1519) md(1031) jpg(625) class(516)
|                  json(242) java(207) png(121) sh(119)
|      Conf files: package.json(30) launch.json(1) settings.json(1)
|    Folder (Alejandro): more than 25424 files
|      File types: jpg(5722) jar(4061) tgz(2374) json(1892) plist(1342)
|                  pdf(1296) data(979) png(487) xml(337) JPG(334)
|      Conf files: package.json(29) tslint.json(6) settings.json(6)
|                  makefile(3) tsconfig.json(2) gulp.js(1)
|                  launch.json(1) sln(1);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.8.2
solidity|Jua|0.0.53
Lisp|mat|0.1.8
dotenv|mik|1.0.1
python|ms-|2019.4.11987
azure-account|ms-|0.8.2
cpptools|ms-|0.22.1
Go|ms-|0.10.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.7.0
vscode-icons|vsc|8.6.0
markdown-all-in-one|yzh|2.3.1

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Sorry for the slow response but I need more info - for example, does this happen if you start with `--disable-extensions`, or can you tell me exactly which process is using CPU, from the Process Explorer or `ps`?
