### ISSUE TITLE
createWebviewPanel to Return the Existing Panel of the Same viewType

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#73017]
## Scenario:
An extension presents a webview in a command. This webview is maintained as a singleton in the extension code. A serializer is also implemented to restore the webview after reload.

When VS Code reloads, if the webview is not active before the reload, then VS Code keeps it inactive after reload. We can see the title of the webview but it is not actually rendered.

Now, when the user triggers the command again, a new webview panel is created by calling createWebviewPanel. So we see two webviews with the same title in VS Code.

## Problems:
1. Is there a way to iterate the existing webviews? I didn't find a way to do so. If I can iterate and activate the existing webviews, then I can solve this problem.
2. Should createWebviewPanel create a new panel or return the existing instance?

## Requests:
1. VS Code to provide APIs to iterate and activate existing webviews.
2. createWebviewPanel to reuse webview panel when the specified viewType already exists.

**Comment by jrieken** [comment]
> VS Code to provide APIs to iterate and activate existing webviews.

The API is designed so that web view objects aren't discoverable because extension A wouldn't know what to do with WebView of extension B...

**Comment by akaroml** [comment]
> > VS Code to provide APIs to iterate and activate existing webviews.
> 
> The API is designed so that web view objects aren't discoverable because extension A wouldn't know what to do with WebView of extension B...

This looks like a security concern, to access webviews that were created by other extensions.

But the case here is to access what was created by myself. createWebviewPanel and the WebviewPanelSerializer should coordinate to avoid duplicating the webview panels of the same viewType. Does that make sense?

**Comment by jrieken** [comment]
> createWebviewPanel and the WebviewPanelSerializer should coordinate to avoid duplicating the webview panels

I think they do, the doc says ['The serializer should take ownership of this panel. The serializer must restore the webview's `.html` and hook up all webview events.'](https://github.com/Microsoft/vscode/blob/acf97a576be7e4d0bedcdde529c779e23faabe0d/src/vs/vscode.d.ts#L5961-L5962) which makes me believe this should/could work.

**Comment by mjbvz** [comment]
This is a problem but I agree that querying webviews is not an api we want to add. We also don't want to move away from making webview restoration lazy. Giving webview some sort of unique id that we can de-duplicate by VS Code could work but needs some more thought.

You can also sort of work around this. Here's what the markdown preview does:

1. In your extension, track all the webviews that you create or are restored from serialization 
1. When a webview is restored just check to see if there is already a "duplicate" view showing somewhere
1. If there is a duplicate, dispose of the duplicate and make the restored webview into the primary view.

With this, there may be multiple tabs for a webview singleton: some that are awaiting restoration and at most one active one. But once any pending webviews are restored, they will get de-duplicated by your extension so there is conceptually ever only one active one. No one's reported the duplicate tabs being problematic for markdown in the year+ since it was added (although now that I say that, I can already sense the incoming issue)

**Comment by akaroml** [comment]
> This is a problem but I agree that querying webviews is not an api we want to add. We also don't want to move away from making webview restoration lazy. Giving webview some sort of unique id that we can de-duplicate by VS Code could work but needs some more thought.
> 
> You can also sort of work around this. Here's what the markdown preview does:
> 
> 1. In your extension, track all the webviews that you create or are restored from serialization
> 2. When a webview is restored just check to see if there is already a "duplicate" view showing somewhere
> 3. If there is a duplicate, dispose of the duplicate and make the restored webview into the primary view.
> 
> With this, there may be multiple tabs for a webview singleton: some that are awaiting restoration and at most one active one. But once any pending webviews are restored, they will get de-duplicated by your extension so there is conceptually ever only one active one. No one's reported the duplicate tabs being problematic for markdown in the year+ since it was added (although now that I say that, I can already sense the incoming issue)

Thanks for the info. First of all, it does not look good to have multiple tabs:
![image](https://user-images.githubusercontent.com/16755094/57191169-1cf17400-6f55-11e9-8468-35938513995f.png)

Second, it's not true when one tab is activated and then others can be disposed (see screenshot above). The `deserializeWebviewPanel` is only called when users click on one of the tabs (no objection regarding lazy restoration), and that's when we can check for duplicates and dispose. That means users need to click on each tab to get them disposed. And the behavior itself makes no sense.

The singleton to check for duplicates and dispose was already implemented and shipped, but the workaround is still problematic. So my goal here is to have only one tab and I'm open for options.

**Comment by mjbvz** [comment]
I think this is a good use case of the custom editor api proposal: #77131

To implement this, you'd:

1. Register a file system provider for your welcome page
1. Register a custom editor for some special file on that file extension.
1. Using the normal VS Code commands, invoke `open` for your welcome page resource in the target group 

The custom editor api will ensure that only a single webview for a given resource exists in a group at a time
