### ISSUE TITLE
'Go To Definition' not working for Java maven project

### ISSUE THREAD

**Issue by poornesh-sharma** [Microsoft/vscode#73016]
- VSCode Version: 1.33.1 (1.33.1)
- OS Version:MAC OS 10.14.4 (18E226)

Steps to Reproduce:

1. Open any java maven poject and try to open any method defination or type definition using 'F12' or right click and 'Go To Definition' showing as 'No definition found'

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please file this against your java extension
