### ISSUE TITLE
New lines are removed when copy in tmux in terminal.

### ISSUE THREAD

**Issue by eddylin** [Microsoft/vscode#73012]
Issue Type: <b>Bug</b>
copy in tmux:
![image](https://user-images.githubusercontent.com/2252263/56873506-5c0b5b00-6a65-11e9-8858-cb13dbaa19cc.png)
![image](https://user-images.githubusercontent.com/2252263/56873509-60d00f00-6a65-11e9-863b-43afb585329f.png)

copy in normal:
![image](https://user-images.githubusercontent.com/2252263/56873516-69284a00-6a65-11e9-8458-4807b7b95cc8.png)
![image](https://user-images.githubusercontent.com/2252263/56873517-6cbbd100-6a65-11e9-953d-a8d1cb3c4f29.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (5.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
project-manager|ale|10.5.1
vscode-intelephense-client|bme|1.0.13
tortoise-svn|fan|0.1.1
url-encode|fle|1.1.0
code-runner|for|0.9.8
shell-format|fox|4.0.5
mdmath|goe|2.3.9
reg|ion|0.0.2
svn-scm|joh|1.48.1
vscode-phpfmt|kok|1.0.30
vs-color-picker|lih|1.0.0
xzg|lin|0.0.8
AWK|lug|0.0.2
bash-ide-vscode|mad|1.3.3
ecdc|mit|1.0.5
vscode-remote-workspace|mkl|0.42.0
python|ms-|2019.4.11987
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
powershell|ms-|1.12.1
sublime-keybindings|ms-|4.0.0
vscode-paste-image|mus|1.0.4
remote-vscode|raf|1.1.0
shellman|Rem|4.3.1
code-settings-sync|Sha|3.2.9
trailing-spaces|sha|0.3.1
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.7.5
shellcheck|tim|0.6.0
ghosttext|tok|1.1.0
vscode-lua|tri|0.12.4
shell-launcher|Tyr|0.3.0
sort-lines|Tyr|1.8.0
unity-debug|Uni|2.7.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is by design and is one of the many downsides to using tmux; tmux wraps lines itself instead of letting the terminal do it.
