### ISSUE TITLE
api for getting error log and running environment

### ISSUE THREAD

**Issue by 10142904** [microsoft/vscode#73015]
Issue Type: Feature Request

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18309

   The vscode is a great editor and open source, so the plug-in is rich, autocompletion and snippet greatly improve the programming efficiency. Another place that can improve efficiency is to solve programming problems. It is always a headache to solve problems in programming. At the same time, the problems you encounter are believed to have been suffered or even solved by many others. If you can combine the two together, you will avoid  trying to Reinvent the Wheel. At present, one of the conventional problem solving modes is search, and the biggest problem of searching is that only keywords can be input, it is difficult to fully describe the problem, and it takes a lot of time to filter the search results. The editor itself is the platform that can best perceive user programming information and error information, so the running environment and premise of the problem are known. we can share and solve the problem based on these infomation, it will be a dream. So I really want to know if vscode will add api for getting vscode programming environment and error log information, and look forward to reply!

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by 10142904** [comment]
@jrieken thank you. my question is:

- Is there an API to get the detailed version of the system and vscode system including extension information?   for example:

1) detailed version of OS
        CPUs                Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)GPU Status          
        2d_canvas: enabled                    
        checker_imaging: disabled_off                    
        flash_3d: enabled                    
        flash_stage3d: enabled                    
        flash_stage3d_baseline: enabled                    
        gpu_compositing: enabled                    
        multiple_raster_threads: enabled_on                    
        native_gpu_memory_buffers: disabled_software                    
        rasterization: enabled                    
        surface_synchronization: enabled_on                    
        video_decode: enabled                    
        webgl: enabled                    
        webgl2: enabled
        Memory (System)     15.84GB (7.59GB free)
        Process Argv
        Screen Reader      noVM                 33%

2）the detailed version of the vscode
        Version: 1.33.1 (user setup)
        Commit: 51b0b28
        Date: 2019-04-11T08:27:14.102Z
        Electron: 3.1.6
        Chrome: 66.0.3359.181
        Node.js: 10.2.0
        V8: 6.6.346.32
        OS: Windows_NT x64 10.0.18309

3）the detailed version of the extension

        Extension                    Author (truncated)                            Version
        vscode-file-peek               abi                                         1.0.1
        vscode-translate               chu                                         0.1.5
        codestream                     Cod                                         0.52.1
        vscode-eslint                  dba                                         1.8.2
        search                         dba                                         1.1.3
        githistory                     don                                         0.4.6
        gitlens                        eam                                         9.6.3
        vscode-html-css                ecm                                         0.2.0
        EditorConfig                   Edi                                         0.13.0
        LogFileHighlighter             emi                                         2.4.3
        prettier-vscode                esb                                         1.9.0
        php-debug                      fel                                         1.13.0
        php-intellisense               fel                                         2.3.10
        auto-close-tag                 for                                         0.5.6
        .....
        JavaScriptSnippets             xab                                         1.7.2

-  Is there an API to get all logs in  panels below the editor region for output or debug information, errors and warnings, or an integrated terminal ?

`

**Comment by garyng** [comment]
Try describe your use case for this feature request (see https://github.com/microsoft/vscode/labels/feature-request for examples)? 

Like, for sharing users' system info while reporting issues? Or?

**Comment by jrieken** [comment]
not actionable
