### ISSUE TITLE
Can you add more left padding to file tree view items?

### ISSUE THREAD

**Issue by doppiogancio** [Microsoft/vscode#73029]
VSCode for MAC:    **Version 1.33.1 (1.33.1)**
System Version:	**macOS 10.14.4 (18E226)**
Kernel Version:	**Darwin 18.5.0**

On Mac version is really hard to understand which file/folder belongs to which folder due to very bad left padding. Most probably you should just add some left padding to fix this issue.

Thanks in advance.

<img width="308" alt="Screenshot 2019-04-26 at 15 29 35" src="https://user-images.githubusercontent.com/7829649/56886842-3a63a100-6a70-11e9-926a-548de48a987a.png">

**Comment by gjsjohnmurray** [comment]
Try increasing the `workbench.tree.indent` setting

**Comment by isidorn** [comment]
@gjsjohnmurray thanks!
@doppiogancio yes, please use the workbench.tree.indent

**Comment by doppiogancio** [comment]
@gjsjohnmurray @isidorn Thanksss, you did my day!
