### ISSUE TITLE
[loc]Request to add Croatian (hr) language to VS Code project in MLCP

### ISSUE THREAD

**Issue by dominikvitt** [microsoft/vscode#73027]
Hello,
I would like to enable Croatian language for VS code localization.
I can see that Croatian was enabled last year, but it was probably disabled later because of inactivity.
https://github.com/Microsoft/vscode/issues/26680

I would like to actively work on VS Code translations, so would like that Croatian language is added to list of maintained languages.

My profile: https://www.transifex.com/user/profile/dominik.vitt.hr/

**Comment by danyeh** [comment]
Thank you for showing interest!
We don't have plan to enable additional language in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
