### ISSUE TITLE
php Code highlighting

### ISSUE THREAD

**Issue by a1392429292** [Microsoft/vscode#73025]
<img width="573" alt="WX20190429-162817@2x" src="https://user-images.githubusercontent.com/25346902/56884436-5846fb00-6a9c-11e9-84d5-0a03af84164f.png">
<img width="519" alt="WX20190429-162843@2x" src="https://user-images.githubusercontent.com/25346902/56884442-5c731880-6a9c-11e9-9a6e-c985d4a82397.png">

Writing div labels in PHP files highlights all divs
In HTML files, this is not the case

**Comment by a1392429292** [comment]
Write HTML tags in PHP files and highlight all divs when selected，It feels confusing.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/2915#issuecomment-403626500
