### ISSUE TITLE
Terminal actions need cleanup

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7302]
I find it hard to figure out what to do when typing `>terminal` in the command prompt:

![screen shot 2016-06-07 at 09 23 00](https://cloud.githubusercontent.com/assets/22350/15849183/81835b0e-2c91-11e6-8434-87cacac8afa3.png)

Maybe something more like this?

- Open System Terminal
- Open Integrated Terminal
- Focus Integrated Terminal

Or, with the category sections:

- Terminal: Open System Terminal
- Terminal: Open Integrated Terminal
- Terminal: Focus Integrated Terminal

**Comment by Tyriar** [comment]
It's standard to have View: prefixed for actions in the view menu.

**Comment by Tyriar** [comment]
I guess doing something like how Debug does as there are a bunch of commands coming for multi terminal handling in June.

![image](https://cloud.githubusercontent.com/assets/2193314/15849436/6d1c3c2a-2c47-11e6-97ab-759374f35632.png)

**Comment by joaomoreno** [comment]
Yeah I see the `View:` argument... but I'd not be very happy in having:

- Terminal: Open System Terminal
- View: Open Integrated Terminal
- Terminal: Focus Integrated Terminal

**Comment by Tyriar** [comment]
I see you confused yourself there :smile: 

Maybe you should pose the question to the rest of the team in slack or something, this is how it's done now and I agree it's a bit ugly.

**Comment by weinand** [comment]
Shouldn't we not try to address this issue by starting to consolidate the two Terminals in VS Code first?

I propose to have only one "Terminal" in VS Code. This can be either opened from the Explorer's "Open in Terminal" action (which supports a 'cd' to the selected folder) or with a global "Open Terminal" action (which opens the terminal at the project root).

Whether this Terminal is a 'System Terminal' or the 'Integrated Terminal' can be controlled via a setting.

**Comment by Tyriar** [comment]
@weinand I was initially opposed to that idea, but I think my aversion to it was due to multiple terminals not being supported which should come in June :+1:

**Comment by waderyan** [comment]
As far as commands go I am in favor of @joaomoreno's later suggestion. 

Terminal: Open System Terminal
Terminal: Open Integrated Terminal
Terminal: Focus Integrated Terminal

Personal preference based on how I search for commands and what I would expect. 

Also 👍 on @weinand's consolidation suggestion.

**Comment by Tyriar** [comment]
I'm proposing the following, all commands start in `workbench.action.terminal.` - I haven't checked for conflicts yet.

| Command | Description | Keybinding
|---|---|---
`close` | Terminal: Close the current terminal | <kbd>ctrl</kbd>\|<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>x</kbd>
`closeAll` | Terminal: Close all terminals | -
`copy` | Terminal: Copy text from the terminal | <kbd>ctrl</kbd>\|<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>c</kbd>
`focus` | Terminal: Focus the terminal panel,<br>toggling it if not visible | -
`focusNext` | Terminal: Focus the next terminal | <kbd>ctrl</kbd>\|<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>j</kbd>
`focusPrevious` | Terminal: Focus the previous terminal | <kbd>ctrl</kbd>\|<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>k</kbd>
`new` | Terminal: Create a new terminal | <kbd>ctrl</kbd>\|<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>t</kbd>
`paste` | Terminal: Paste into the terminal | <kbd>ctrl</kbd>|<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>v</kbd>
`toggle` | Terminal: Toggle visibility the terminal panel | <kbd>ctrl</kbd>+<kbd>`</kbd>

Also regarding the external terminal, I think it would be better to just hijack the keybinding from it and leave the command there in case people want it. That is more flexible and feels less messy to me than having a toggle switch in settings.

**Comment by Tyriar** [comment]
Actually the above has some issues:

- <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>j</kbd>, k and x are all taken
- I was looking into chords but it's not possible to use them from within the terminal as it needs to consume the keys.
