### ISSUE TITLE
the dubug console view has some question with Chinese comment

### ISSUE THREAD

**Issue by nimapier** [Microsoft/vscode#73022]
Issue Type: <b>Bug</b>

when I run a simple  test.js with two lins:
console.log(a)//报错
let a=2

C:\Program Files\nodejs\node.exe --inspect-brk=30231 src\test.js
Debugger listening
on ws://127.0.0.1:30231/25715e7b-a8e3-45f8-953c-74975e59c634
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
c
:
\
U
s

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU G1620 @ 2.70GHz (2 x 2693)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.97GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
vue-snippets|hol|0.1.11
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.4.11987
debugger-for-chrome|msj|4.11.3
vetur|oct|0.19.2
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
Maybe being caused by an extension? Try disabling yours. If the problem goes away, re-enable one by one until you find the culprit.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for jumping in!

**Comment by nimapier** [comment]
I just disabled all my extensions and restarted,,but this bug remained.

**Comment by isidorn** [comment]
I can not reproduce this using the following code sample
```javascript
let a = '报错';
console.log(a);
```

Let me know what code sample you are using to see this?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
