### ISSUE TITLE
Image View Remembers Zoom

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#73021]
Issue Type: <b>Bug</b>

In VSC, load a small image, zoom in a lot, close the image.
Resize the small image by 10 times.
In VSC, load the resized image.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vetur|oct|0.19.2
github-actions-vscode|Oma|2.6.1
rust|rus|0.6.1
RustyCode|sav|0.19.1
vscode-hexdump|sle|1.7.2
sort-lines|Tyr|1.8.0
markdown-all-in-one|yzh|2.3.1

(1 theme extensions excluded)

</details>

**Comment by hwhung0111** [comment]
I would like to take this. I think we can store more information in `cacheKey`. In my opinion, we can add the size or add the SHA1 value of the image? @mjbvz Do you have any suggestions?

**Comment by cedric05** [comment]
can i work on this?

**Comment by cedric05** [comment]
i didn't know that @hwhung0111 already started working on this, both prs work. as far as mine considered, i'm resetting scale to 1.

**Comment by hwhung0111** [comment]
@cedric05 I'm sorry that I forgot to reply to you immediately. Do you reset the scale every time you close the image? It makes the editor cannot remember the scale and offset even the image isn't modified.

**Comment by cedric05** [comment]
yes you are write. let me close mine. :+1:
