### ISSUE TITLE
Click to follow link

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode#73035]
Instead of having to use the keyboard with one's other hand to hold down Ctrl, Cmd, and/or Alt, it would be nice if it were possible to simply click, double-click, or select to follow from the context menu of a link to follow it.

**Comment by jrieken** [comment]
Yeah, I had a similar idea, maybe adding a real link into the hover so that you can navigate from there

**Comment by burtek** [comment]
> Yeah, I had a similar idea, maybe adding a real link into the hover so that you can navigate from there

Love this idea. Double-clicking is not as good, since lots of people often use double-click to faster select whole link to replace/remove it

**Comment by Richhoef** [comment]
Very good idea! I would also like to be able to click or double click from the terminal to open a file without having to press ctrl on my keyboard

**Comment by zapateo** [comment]
> Very good idea! I would also like to be able to click or double click from the terminal to open a file without having to press ctrl on my keyboard

This would be really useful.

**Comment by rebornix** [comment]
We have a solution proposed in https://github.com/microsoft/vscode/issues/69719 , which should allow you to click to follow link from the hover directly. You should be able to use this feature from tomorrow's Insiders.

**Comment by zapateo** [comment]
@rebornix seems like it's still not possible to open links on terminal just clicking on them (or double-clicking) without using a modifier key.

This feature is already implemented in the `DEBUG CONSOLE` panel.

**Comment by rebornix** [comment]
that's right, it's up to @Tyriar if we should / when to implement this feature in the terminal.

**Comment by Tyriar** [comment]
👉 https://github.com/microsoft/vscode/issues/77964
