### ISSUE TITLE
Lates insider build covers bottom of the window

### ISSUE THREAD

**Issue by vitek-karas** [Microsoft/vscode#73033]
Issue Type: <b>Bug</b>

In the latest insider build when I maximize the VS Code window on my main monitor (2560x1440) about 5% of the bottom of the window is covered with black/gray area which is empty. It covers the status bar and all of the the other UI there. UI elements in that area don't interact with mouse either.

The effect disappears when the window is not maximized (even if I resize it to be as large as if it was maximized). The effect is also not present when I maximze it on my other monitor which is in portrait mode (1440x2560).

VS Code version: Code - Insiders 1.34.0-insider (0200bdd71e409954ae12149fe493f38065306555, 2019-04-29T05:18:26.523Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (11.02GB free)|
|Process Argv|--folder-uri file:///f%3A/dotnet/core-setup|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.6.0
cpptools|ms-|0.23.0-insiders
csharp|ms-|1.19.0
powershell|ms-|1.12.1
code-spell-checker|str|1.7.5
cmake|twx|0.0.17

</details>

**Comment by vitek-karas** [comment]
Screenshot of the bottom left corner of the window (you can barely see the settings button):
![image](https://user-images.githubusercontent.com/10670590/56893385-5a2aa300-6a37-11e9-8745-1e6f97891c9e.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by vitek-karas** [comment]
Thanks @bpasero . The exploration builds definitely don't have that problem. And now I don't see it even on the insiders builds (after reboot)… not sure what it was about.
