### ISSUE TITLE
All extensions are non-responsive after one extension fails

### ISSUE THREAD

**Issue by pjsteele** [microsoft/vscode#73041]
Issue Type: <b>Bug</b>

Unsure how, but either the Tomcat or Mavon extension is failing. Then ALL extensions ae non response. I cannot even open the GIT window

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tomcat|ada|0.11.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jsontotype|dan|0.0.3
githistory|don|0.4.6
gitlens|eam|9.6.3
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-npm|fkn|3.3.0
test-one-file|Fyl|0.3.0
vscode-pull-request-github|Git|0.6.0
vscode-nuget-package-manager|jmr|1.1.6
svgpreview|kis|0.2.0
sftp|lix|1.12.3
mssql|ms-|1.6.0
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
live-server-preview|neg|0.1.4
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.23.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.6.0
vscode-manifest-yaml|Piv|1.6.0
vscode-spring-boot|Piv|1.6.0
java|red|0.43.0
vscode-checkstyle|she|1.0.2
code-spell-checker|str|1.7.5
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-maven|vsc|0.16.2
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5
vscode-icons|vsc|8.6.0

</details>

**Comment by RMacfarlane** [comment]
@pjsteele Is this happening on startup? Do you see any kind of notification when this happens? Can you try disabling the Tomcat or Mavon extension to narrow down which one it is?

**Comment by pjsteele** [comment]
I apologize for such an empty issue. If I restart VS complete, the extensions will run. I will create a WAS (using Maven extension), Debug WAR (using Tomcat extension), eventually all extensions stop working. 

Is there a place I can look for extension logs to get more info?

**Comment by RMacfarlane** [comment]
Two things that might be helpful for diagnosing the issue would be to

1. Run the `Developer: Show Running Extensions` command. This should show a list of all of the currently active extensions, there's a button at the top right to start profiling.
2. Run `Developer: Open Process Explorer` and try to reproduce the issue while that is open, looking for anything strange going on there

**Comment by pjsteele** [comment]
This may help. I did the following
- Restarted VSCode
- Performed *clean* from Maven for Java Extension
- Clicked *custom* from Maven for Java Extension
- All extensions are now frozen

The Process explorer has extensionHost at 100%
```
CPU %	Memory (MB)	pid	Name
2	131	24479	code main
0	98	24480	     gpu-process
0	262	24481	     window (pom.xml — adw)
0	0	24489	         /bin/bash -l
0	49	24492	         watcherService
100	197	24495	         extensionHost
0	98	24502	             electron_node server.js 
0	459	24512	             /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /Users/pj.steele/.vscode/extensions/redhat.java-0.43.0/server/plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar -configuration /Users/pj.steele/.vscode/extensions/redhat.java-0.43.0/server/config_mac -data /Users/pj.steele/Library/Application Support/Code/User/workspaceStorage/e768e937c6204149d948d7960bcc2342/redhat.java/jdt_ws
0	328	24764	             /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java -Dloader.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/lib/tools.jar -Dspring.lsp.client-port=45556 -Dserver.port=45556 -Dsts.lsp.client=vscode -Dsts.log.file=/var/folders/z6/tc__8jx563q1x8qpsc7_s71dwv9j99/T/vscode-spring-boot-1556733393564.log -Dlogging.file=/var/folders/z6/tc__8jx563q1x8qpsc7_s71dwv9j99/T/vscode-spring-boot-1556733393564.log -jar /Users/pj.steele/.vscode/extensions/pivotal.vscode-spring-boot-1.6.0/jars/spring-boot-language-server-1.6.0-SNAPSHOT.jar
0	33	24496	         searchService
0	0	24783	         /bin/bash -l
0	66	24505	     window
0	98	24543	     shared-process
1	82	24654	     window (Process Explorer)
0	0	25139	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
0	279	24744	     window
```

Console output from Developer Tools
```
extensionHost.ts:311 [Extension Host] debugger listening on port 11620
extensionService.ts:804 [adashen.vscode-tomcat]: Command `tomcat.war.browse` appears multiple times in the `commands` section.
extensionService.ts:804 [fknop.vscode-npm]: Command `npm-script.start` appears multiple times in the `commands` section.
extensionService.ts:804 [fknop.vscode-npm]: Command `npm-script.test` appears multiple times in the `commands` section.
textMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/pj.steele/.vscode/extensions/ms-mssql.mssql-1.6.0/syntaxes/SQL.plist
register @ textMateService.ts:52
textMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/pj.steele/.vscode/extensions/pivotal.vscode-concourse-1.6.0/yaml-support/yaml.tmLanguage
register @ textMateService.ts:52
textMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Users/pj.steele/.vscode/extensions/pivotal.vscode-concourse-1.6.0/yaml-support/yaml.tmLanguage.
New grammar file: file:///Users/pj.steele/.vscode/extensions/pivotal.vscode-manifest-yaml-1.6.0/yaml-support/yaml.tmLanguage
register @ textMateService.ts:52
textMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Users/pj.steele/.vscode/extensions/pivotal.vscode-manifest-yaml-1.6.0/yaml-support/yaml.tmLanguage.
New grammar file: file:///Users/pj.steele/.vscode/extensions/pivotal.vscode-spring-boot-1.6.0/yaml-support/yaml.tmLanguage
register @ textMateService.ts:52
console.ts:134 [Extension Host] [vscode-icons] v8.6.0 activated!
console.ts:134 [Extension Host] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
t.log @ console.ts:134
console.ts:134 [Extension Host] Starting Java server with: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /Users/pj.steele/.vscode/extensions/redhat.java-0.43.0/server/plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar -configuration /Users/pj.steele/.vscode/extensions/redhat.java-0.43.0/server/config_mac -data /Users/pj.steele/Library/Application Support/Code/User/workspaceStorage/e768e937c6204149d948d7960bcc2342/redhat.java/jdt_ws
console.ts:134 [Extension Host] 1 May 13:56:33 - Proposed protocol extensions loaded!
extensionHost.ts:215 Extension Host
extensionHost.ts:216 Debugger attached.
```

The *debugger attached* message is in red.

**Comment by ctf0** [comment]
am also having the same issue with `Debugger attached` error and here is my Process explorer output after all the editor extensions has stopped

```
CPU %	Memory (MB)	pid	Name
0	85	7100	code main
0	74	5276	     gpu-process
0	206	7200	     window (Running Extensions - six)
0	46	4020	         searchService
0	37	7372	         watcherService
0	11	7424	         electron-crash-reporter
0	248	7576	         extensionHost
0	59	4876	             electron_node server.js 
0	58	5832	             electron_node intelephense.js 
0	48	6936	             "C:\Users\Razo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Razo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=7576
0	176	7860	             electron_node server.js 
0	67	7464	     window (Process Explorer)
0	70	7668	     shared-process
```

i was wondering if there is a way to make `Extension Host: Debugger attached` more meaningful.

**Comment by alexandrudima** [comment]
This is the current VS Code architecture: extensions run in a separate process than the core editor, so when an extension crashes badly or misbehaves really badly, it will at most take down the extension host and other extensions and not the core VS Code... i.e. saving your files will still work.

Obviously having one extension that goes crazy and breaks the other extensions (including built-in ones like git) is not a great situation and we could spawn a process for each extension, and we might investigate doing that in the future, but for now, may I please ask that you reach out to the misbehaving extension directly and create an issue with them.

**Comment by Lennon925** [comment]
> This is the current VS Code architecture: extensions run in a separate process than the core editor, so when an extension crashes badly or misbehaves really badly, it will at most take down the extension host and other extensions and not the core VS Code... i.e. saving your files will still work.
> 
> Obviously having one extension that goes crazy and breaks the other extensions (including built-in ones like git) is not a great situation and we could spawn a process for each extension, and we might investigate doing that in the future, but for now, may I please ask that you reach out to the misbehaving extension directly and create an issue with them.

I think this architecture is very stupid. Some extension is watching file system, when git checkout and  there are many file changed/deleted/added, extension will be blocked and response will be very slow. The feeling is very terriable.

**Comment by Lennon925** [comment]
> This is the current VS Code architecture: extensions run in a separate process than the core editor, so when an extension crashes badly or misbehaves really badly, it will at most take down the extension host and other extensions and not the core VS Code... i.e. saving your files will still work.
> 
> Obviously having one extension that goes crazy and breaks the other extensions (including built-in ones like git) is not a great situation and we could spawn a process for each extension, and we might investigate doing that in the future, but for now, may I please ask that you reach out to the misbehaving extension directly and create an issue with them.

I think currently we can't give up to use misbehaving extensions or those extensions which do something that cost a lot of time. 
You can't close this kind of issue unless they are solved.

**Comment by gjsjohnmurray** [comment]
@Lennon925 according to https://github.com/microsoft/vscode/issues/24441#issuecomment-292969713 the current architecture requires all extensions to run in a single extension host (EH) process.

**Comment by Lennon925** [comment]
> @Lennon925 according to [#24441 (comment)](https://github.com/microsoft/vscode/issues/24441#issuecomment-292969713) the current architecture requires all extensions to run in a single extension host (EH) process.

So you mean I can't do something that cost a lot of time in extensions, right? Otherwise, other extensions will be blocked,right? I think it's stupid.
