### ISSUE TITLE
`code-insiders --help` has wrong format

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#73045]
Version: 1.34.0-insider (user setup)
Commit: 0200bdd71e409954ae12149fe493f38065306555
Date: 2019-04-29T05:18:26.523Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/4033249/56914603-5fa0e100-6a69-11e9-9743-3abbc1c42476.png)

Repro:

- Install code-insiders on Windows
- Open a WSL shell
- `code-insiders --help`

**Comment by octref** [comment]
Working fine in built-in terminal, though:

![image](https://user-images.githubusercontent.com/4033249/56914717-ac84b780-6a69-11e9-8091-47f11af92397.png)

**Comment by roottool** [comment]
Working fine in `./scripts/code-cli.sh --help`, though:
![CodeCLI shIsFine](https://user-images.githubusercontent.com/11808736/57018403-5cbb1180-6c5e-11e9-8afc-d9d6067db9b2.jpg)

Currently, I don't know how to verify that my fix is ​​correct.
How can I check that my fix is correct?

**Comment by Tyriar** [comment]
@roottool looks like you're in WSL, I thought that was the only repro 😕

**Comment by octref** [comment]
Seems fixed for me too, we probably had a bad insider:

![image](https://user-images.githubusercontent.com/4033249/57029296-2b0e6000-6bf6-11e9-8fc4-c7029e18bb8c.png)
