### ISSUE TITLE
[powershell] add here-string autoClosingPairs to PowerShell

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#73047]
Consider adding autoClosingPairs to PowerShell language configuration for `@'..'@` and `@"..."@`.

However, to do so would require fixing some issues, such as #72177 because these patterns conflict with regular quoted string patterns.  Ideally the closing pair should inject a `\n` (newline, before the closing token), but that causes the cursor to jump to after the newline (in the cases were I have tested it with non-conflicting pairs).  Alternatively, if a newline was allowed in the opening pair detection, that could be an option too.

These pairs would probably also require `"notIn": ["string", "comment"]`.

**Comment by rmunn** [comment]
The linked issue (https://github.com/microsoft/vscode/issues/72177) is also in danger of being closed if it doesn't get upvotes. Anyone interested in getting this annoyance fixed should probably upvote https://github.com/microsoft/vscode/issues/72177 so it can get moved to the VS Code backlog and the VS Code devs have a chance of seeing it.
