### ISSUE TITLE
'Find In Files' without opening the folder

### ISSUE THREAD

**Issue by erikdemarco** [Microsoft/vscode#73055]
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-18-generic snap

Steps to Reproduce:
1. open VSCode
2. click Find In Files from the menu
3. search whatever from any folder
4. vscode says nope 'You have not yet opened a folder. Only open files are currently search'.

Doesn't make any sense all other editor can easily 'find in files' without distrubing the user with this kind of request, its really annoying. Currently vscode the only code editor requesting such task before you can do 'find in files'.

Note: According to issue #17164, in version 1.14, Find in Files should allow you to search outside of the workspace. But still why do we need to 'open the folder' first???

**Comment by roblourens** [comment]
This is a bug, tracked in https://github.com/Microsoft/vscode/issues/72938
