### ISSUE TITLE
VSCode Extremely slow after about a minute

### ISSUE THREAD

**Issue by Alavan** [Microsoft/vscode#73051]
Issue Type: <b>Performance Issue</b>

I have disabled all extensions, and when I reload VSCode, it is fine for about a minute, but then any action takes about a second to register (render).  That includes clicking around in a document, switching tabs, opening top menus, highlighting text, and scrolling (whether mouse or manual).  I am editing html and javascript and only have 5 tabs open.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (0.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    78	 23060	code main
    1	    63	  4480	   gpu-process
    1	    61	  4576	   window (Issue Reporter)
    0	    74	 10484	   shared-process
    0	   164	 18104	   window (SOProcess.html - CA - Visual Studio Code [Administrator])
    0	    62	  4492	     extensionHost
    0	    79	 23080	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=4492
    0	    34	 13224	     searchService
    0	     5	 16824	     winpty-process
    0	     3	 13004	       "C:\Program Files\Git\bin\bash.exe"
    0	    11	 20744	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    10	 21432	     watcherService 
    1	    71	 23128	   window (Process Explorer)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SOProcess.html - CA - Visual Studio Code [Administrator])
|    Folder (CA): 370 files
|      File types: png(116) js(108) txt(51) sql(42) xml(34) json(5) html(5)
|                  properties(3) css(3) gif(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by Alavan** [comment]
I should add that this only started happening today, and I have been using VSCode like this for months.

**Comment by SupinePandora43** [comment]
you're said Memory (System) = 7.95GB (0.46GB free)
only 0.46gb free? chromium needs a lot of memory!

// sometimes i'm have same issue

**Comment by Alavan** [comment]
I never have this issue with other Chromium apps (Google Chrome for
instance).  And I've been maxing out my memory for weeks without issue.
Next time it happens, though (for some reason it has stopped today even
though I have the same programs open), I will close high-memory programs to
see if the issue is alleviated.

**Comment by Tyriar** [comment]
> 7.95GB (0.46GB free)

It looks like this is probably the issue, VS Code itself isn't using that much as per your process info posted above but when it tries to do thing's it's probably maxing out memory.
