### ISSUE TITLE
Windows terminal issue caused by conpty

### ISSUE THREAD

**Issue by puneetpr** [Microsoft/vscode#73050]
- VSCode Version: 1.33.1
- OS Version: win10 18362

Steps to Reproduce:

1. Open VS Code terminal
2. VS Code crashes with error "This window has crashed" error

Mitigation:
Added below to settings, fixes the issue
{
    "terminal.integrated.windowsEnableConpty": false
}

Does this issue occur when all extensions are disabled?: Yes

Crash log:
[Code__PID__30124__Date__04_29_2019__Time_01_27_53PM__101__Log.txt](https://github.com/Microsoft/vscode/files/3129216/Code__PID__30124__Date__04_29_2019__Time_01_27_53PM__101__Log.txt)

**Comment by Tyriar** [comment]
Upgrade to the 64-bit VS Code client

/duplicate https://github.com/Microsoft/vscode/issues/72190
