### ISSUE TITLE
paste too long command to vscode's terminal, no response

### ISSUE THREAD

**Issue by liuyingqq123** [microsoft/vscode#73059]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.open vscode's terminal

2.copy as follows:
node ./../bin/banlangen.js login 登录
node ./../bin/banlangen.js payentry 在线购买入口
node ./../bin/banlangen.js payprocess 在线购买流程
node ./../bin/banlangen.js order 订单
node ./../bin/banlangen.js personalcenter 个人中心
node ./../bin/banlangen.js ForgetPassword 忘记密码页面 login 登录
node ./../bin/banlangen.js SettingNewPassword 设置新密码 login 登录
node ./../bin/banlangen.js GoldenMeal 黄金版套餐页面 payentry 在线购买入口
node ./../bin/banlangen.js PlatinumMeal 铂金版套餐页面 payentry 在线购买入口
node ./../bin/banlangen.js DiamondsMeal 钻石版套餐页面 payentry 在线购买入口
node ./../bin/banlangen.js ProductIntroduction 产品介绍详情连接 payentry 在线购买入口
node ./../bin/banlangen.js AuthRealName 实名认证 payprocess 在线购买流程
node ./../bin/banlangen.js Questionnaire 风险承受能力问卷 payprocess 在线购买流程
node ./../bin/banlangen.js AnswerPage_1 答题页 payprocess 在线购买流程
node ./../bin/banlangen.js QuestionnaireConfirm 能力问卷确认页 payprocess 在线购买流程
node ./../bin/banlangen.js PersonalInformation 个人信息页 payprocess 在线购买流程
node ./../bin/banlangen.js OrderConfirm 确认订单页 order 订单
node ./../bin/banlangen.js InvoiceOnline 电子发票页 order 订单
node ./../bin/banlangen.js InvoicePaper 纸质普通发票页 order 订单
node ./../bin/banlangen.js InvoiceAddedValueTax 增值税专用发票页 order 订单
node ./../bin/banlangen.js InvoiceNot 不开发票页 order 订单
node ./../bin/banlangen.js PayForCMB 招行支付 order 订单
node ./../bin/banlangen.js PayForOffLine 线下支付页 order 订单
node ./../bin/banlangen.js PaySuccess 订单支付成功页 order 订单
node ./../bin/banlangen.js MyOrder 我的订单 personalcenter 个人中心
node ./../bin/banlangen.js OrderDetail 订单详情 personalcenter 个人中心
node ./../bin/banlangen.js OrderDetail 订单详情 personalcenter 个人中心
node ./../bin/banlangen.js OrderDetail 订单详情 personalcenter 个人中心
node ./../bin/banlangen.js OrderDetail 订单详情 personalcenter 个人中心
node ./../bin/banlangen.js OrderDetail 订单详情 personalcenter 个人中心
node ./../bin/banlangen.js OrderDetail 订单详情 personalcenter 个人中心
node ./../bin/banlangen.js AuthRealNameDetail 查看实名认证页 personalcenter 个人中心
node ./../bin/banlangen.js PersonalInformationDetail 个人信息页 personalcenter 个人中心
node ./../bin/banlangen.js BankCardManage 管理银行卡 personalcenter 个人中心
node ./../bin/banlangen.js RiskLevelAssessment 风险等级测评 personalcenter 个人中心
node ./../bin/banlangen.js ModifyMobile 修改手机号 personalcenter 个人中心
node ./../bin/banlangen.js SettingNewPassword 修改密码 personalcenter 个人中心

3.paste the command to vscode's terminal, terminal have no response

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Can't reproduce on mac or Windows, what platform are you on? Also by no response do you mean the terminal is "dead" or it doesn't get any text but operates normally after?

**Comment by liuyingqq123** [comment]
> Can't reproduce on mac or Windows, what platform are you on? Also by no response do you mean the terminal is "dead" or it doesn't get any text but operates normally after?

The above commands can be executed with fewer copies, but not more.

**Comment by liuyingqq123** [comment]
> Can't reproduce on mac or Windows, what platform are you on? Also by no response do you mean the terminal is "dead" or it doesn't get any text but operates normally after?

In fact, what I want to do is copy a batch command, but too many words, in vscode, paste does not respond.
