### ISSUE TITLE
 directory can not be expand!

### ISSUE THREAD

**Issue by athinboy** [microsoft/vscode#73057]
I have a directory , the name of it  is  "Core".
the directory can not be expand in  vscode .
 
 
版本: 1.33.1 (system setup)
提交: 51b0b28134d51361cf996d2f0a1c698247aeabd8
日期: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
