### ISSUE TITLE
Can't cancel search when in progress...

### ISSUE THREAD

**Issue by erikdemarco** [Microsoft/vscode#73053]
When you are ini the middle of "find in files" process then press 'cancel search', it does nothing. the only way to stop this is force close the app.

Steps to reproduce:
1. Click 'find in files' from the menu bar
2. type any keyword, 'for files to include' type 'c:/' or any big folder
3. click stop
4. still not stopping? ok i will wait.
5. grab coffee for 15 minutes, still searching...

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/72208
