### ISSUE TITLE
PATH not being set in fish shell on macOS

### ISSUE THREAD

**Issue by albireox** [Microsoft/vscode#73058]
- VSCode Version: 1.34.0-insiders
- OS Version: macOS 10.14.4

I'm opening a new issue since #21655 is locked. Not sure if this was ever fixed but when I open VSCode (stable or Insiders) from the App icon the PATH is not set correctly. If I run `process.env` on the developer tools I get just the default `PATH="/usr/bin:/bin:/usr/sbin:/sbin"`. If I open VSCode from a terminal using the `code` command I get my full PATH.

I'm running fish shell 3.0.2. Not sure if this has been a long standing issue but I'm only noticing it now since several extensions are not able to find executables that are not in default PATH directories.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/30847
