### ISSUE TITLE
Mac version vscode Click the sidebar new file icon, invalid, but open the sidebar filter function

### ISSUE THREAD

**Issue by zhang-hongwei** [Microsoft/vscode#73063]
Issue Type: <b>Bug</b>

When creating a new file through the commond+n shortcut key, no file is generated, but the filtering function of the sidebar is turned on. Clicking the new file icon does not work.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
markdown-toc|Ala|1.5.6
jsx|Twe|0.0.1
better-comments|aar|2.0.3
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|10.5.1
vscode-refresh-html|baj|0.0.2
vscode-custom-css|be5|3.0.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.26.0
jshint|dba|0.10.20
vscode-eslint|dba|1.8.2
vscode-dash|dee|2.1.0
githistory|don|0.4.6
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.2.1
gitlens|eam|9.6.3
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.47
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.8
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|0.1.11
beautify|Hoo|1.4.11
emoji-code|idl|0.7.5
path-autocomplete|ion|1.13.3
docthis|joe|0.7.1
svn-scm|joh|1.48.1
vscode-regexp-preivew|le0|0.0.3
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
json-to-ts|Mar|1.5.5
evermonkey|mic|2.4.5
code-beautifier|mic|2.2.1
HTMLHint|mka|0.6.0
vscode-scss|mrm|0.6.2
vscode-language-pack-zh-hans|MS-|1.33.2
mssql|ms-|1.6.0
azure-account|ms-|0.8.2
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
js-atom-grammar|ms-|0.1.14
node-debug2|ms-|1.33.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.91
debugger-for-chrome|msj|4.11.3
korofileheader|OBK|3.6.0
vetur|oct|0.19.2
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
typescript-hero|rbb|3.0.0
vscode-evernote|rha|0.1.2
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.6.0
code-settings-sync|Sha|3.2.9
stylelint|shi|0.49.0
autoimport|ste|1.5.3
open-in-browser|tec|2.0.0
vscode-react-native|vsm|0.9.2
JavaScriptSnippets|xab|1.7.2
vscode-preview-server|yui|1.2.1
html-css-class-completion|Zig|1.18.0

(6 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@zhang-hongwei I haven't been able to reproduce this issue, can you include some more information? What happens when you click the new file icon?

If you press `F1` and use `Developer: Reload Window With Extensions Disabled`, do you still see the problem? If you use `Preferences: Keyboard Shortcuts` and search for "cmd + n", do you see any other commands with the same shortcut?

**Comment by zhang-hongwei** [comment]
I am very sorry to have responded for so long. I have found the reason for the failure of the new file. When I enable the live share plugin, I can't create a new file in the empty directory by using the new file icon. I made a video, I hope you can see if it is due to my improper operation, or if he is really a bug.

[https://www.youtube.com/watch?v=k10CR50Ilzs](url)

**Comment by RMacfarlane** [comment]
Thanks for the video! This looks like a bug. Can you press `F1` and then run `Developer: Toggle Developer Tools` and see if there is any output in the console when the problem happens?

**Comment by zhang-hongwei** [comment]
Operate as you said, without any output. When I click the icon of the newly created file before the live share plugin is started, it will fail to create. At this time, even if the live share plugin is fully started, it cannot be newly created. Close the vscode, then restart, wait for the live share plugin to start completely and then click the icon to create a new one. This time you can create it successfully.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/72139
