### ISSUE TITLE
Prevent VS Code from closing when watching/debugging

### ISSUE THREAD

**Issue by Wozza365** [Microsoft/vscode#73068]
I would like the ability to prompt before closing VS code when an ongoing command line task is running and/or the project is currently being debugged. Accidental closures are a little too easy for my personal liking.

**Comment by isidorn** [comment]
fyi @alexr00

**Comment by alexr00** [comment]
@Wozza365 there is a setting that adds a promp if you try to close and there is a terminal running if that helps: `"terminal.integrated.confirmOnExit": true`

**Comment by Wozza365** [comment]
Thanks @alexr00 this was exactly what I was looking for! Closing request.
