### ISSUE TITLE
Broken TAB spacing in less after variables

### ISSUE THREAD

**Issue by wUFr** [Microsoft/vscode#7306]
- VSCode Version: 1.2.0
- OS Version: Win 10 x64 Pro (CZ) - current "non-insider" build

Steps to Reproduce:

1. ```@grid_sm_end:767px;``` when i want to align variables in config and press TAB after :
2. it will do this ```@grid_sm_end::;767px;``` pressing tab again will just add more: ```@grid_sm_end:::::;767px;```

i had problems with this before, when it would completely rewrite variable name with something else

**Workaround:** use space after : then press TAB

---

im using TABs, becouse i know people around world preffer different spacing, like 2 spaces or even 8. In code 2 tabs can look like 2 spaces or 4 spaces for me.. it just depends on your editor settings. I hate spaces, it forces people to use someone elses spacing... TAB can be as wide as you want with still having same code in background <-- just in case someone gonna try respond "use spaces" (:

**Comment by aeschli** [comment]
The tab key invokes emmet.  For reasons unknown to me, emmet expands ':' to ':::'.

**Comment by egamma** [comment]
This is the standard emmet behaviour and the problem repros in other emmet integrations in other editors. I suggest to file an issue against emmet. 

As a work around you can disable emmet expansions on tab using the `emmet.triggerExpansionOnTab` setting.

Closing this issue as an upstream issue.

**Comment by ramya-rao-a** [comment]
With the new Emmet improvements in VS Code 1.15, this is no longer a problem

Tab will no longer trigger Emmet, instead Emmet abbreviations will show up in suggestion/auto-completion list.

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
