### ISSUE TITLE
No tasks with Gulp

### ISSUE THREAD

**Issue by xiionika** [Microsoft/vscode#73064]
VSCode Version: 1.33.1
OS Version: Windows 7 Enterprise (Service Pack 1) x64 Build 7601

Steps to Reproduce (following official docs [https://code.visualstudio.com/docs/languages/css#_automating-sassless-compilation]):

1. Install node and npm
2. Create any SCSS file, f.e.:
```$padding: 6px;

nav {
  ul {
    margin: 0;
    padding: $padding;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: $padding 12px;
    text-decoration: none;
  }
}
```

3. Install needed node-modules:

```
npm install -g node-sass less
npm install -g gulp
npm install gulp gulp-sass gulp-less
```

4. Create a Gulp task (below is the code from the official docs):
```
// Sass configuration
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', function(cb) {
    gulp.src('*.scss')
        .pipe(sass())
        .pipe(gulp.dest(function(f) {
            return f.base;
        }));
    cb();
});

gulp.task('default', gulp.series('sass', function(cb) {
    gulp.watch('*.scss', gulp.series('sass'));
    cb();
}));
```

5, Run the task (doesn't matter it's default of sass)
6. CSS are suppossed to be generated from SCSS

CSS are not generated anywhere. Terminal said that:
```
> Executing task in folder www: "C:\Users\User\AppData\Roaming\npm\gulp.cmd" default <

[07:17:19] Using gulpfile c:\wamp64\www\gulpfile.js
[07:17:19] Starting 'default'...
[07:17:19] Starting 'sass'...
[07:17:19] Finished 'sass' after 21 ms
[07:17:19] Starting '<anonymous>'...
[07:17:19] Finished '<anonymous>' after 24 ms
[07:17:19] Finished 'default' after 51 ms
```

Does this issue occur when all extensions are disabled?: Yes
Also I tried restarting VS Code, (re)installing npm-modules both from CMD and Termina and moving my SCSS across all the country, sorry, the project. With just tasks.js and no Gulp it works, but no autosave or other pretty things, of course. And I tried extensions. They all seem to either doesn't work or doing something wrong (like converting relative path to absolute (omg, what human being possibly could come up with this idea).

Thanks in advance for any help.

**Comment by alexr00** [comment]
I followed the same docs and a file styles.css was output next to my styles.scss folder. It contained:
```
nav ul {
  margin: 0;
  padding: 6px;
  list-style: none; }

nav li {
  display: inline-block; }

nav a {
  display: block;
  padding: 6px 12px;
  text-decoration: none; }
```

I copied the contents of my gulpfile.js directly from the docs.
