### ISSUE TITLE
Overzealous autocompletions

### ISSUE THREAD

**Issue by mweiczorek** [Microsoft/vscode#73062]
Hi.

Not really a bug, not really a feature request - just an annoyance...

Whenever I type `onClose` or `onClick`, then add parentheses, auto-complete removes the camel-casing and corrects to `onclose` and `onclick`. 

May I suggest that the intellisense not correct if parentheses are typed when it should be obvious that if one of the characters typed is uppercase, the intent of the user is to use the camel-cased symbol name?

It really puts a dent in productivity.

**Comment by mjbvz** [comment]
This is the designed behavior

You can disable accepting completions on `(` by setting `"editor.acceptSuggestionOnCommitCharacter": false` or pressing `esc` to hide the suggestions before typing the `(`
