### ISSUE TITLE
我想有个账号， 可以自动加载插件不用换个环境又要去下载插件

### ISSUE THREAD

**Issue by HuDaHei** [Microsoft/vscode#73065]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by Wyntau** [comment]
**translation**:
I want a account, so vscode can automatically sync extensions list when the development environment changed

**Comment by mgenware** [comment]
Can try this popular plugin: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

可以尝试这个插件: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
