### ISSUE TITLE
In "files to include/exclude", should recognize semicolons as separators

### ISSUE THREAD

**Issue by stevchin** [microsoft/vscode#73066]
I realize that there have been a couple of earlier requests for this that have been closed, but considering the common text editors for Windows (i.e. Notepad++, gVim, etc) that use a semicolon to separate file types, it's a bit frustrating to have a search come up with no results, only to realize that out of habit, you used a semicolon instead of a comma.

If only for the fact that the program is advertised as "Visual Studio" Code, you should recognize the same format, since there are probably a lot of users who use both.  Visual Studio Code is great for more lightweight operations where you don't want to deal with the overhead of opening Visual Studio, but VS Code isn't really meant to support more complex projects.

Keep up the good work, but *please* give this request some serious consideration before closing it...  :)

Thanks!

**Comment by roblourens** [comment]
The only thing keeping me from supporting both is that they are both valid characters for a filename and we have enough characters that you can't include in a filter without writing a confusing glob pattern. But it would be nice to have both, I would understand someone expecting semicolon to work.

**Comment by stevchin** [comment]
Don't suppose it could be configurable then so the user could choose either comma or semicolon, so you'd just swap the filter used depending on the setting?

**Comment by roblourens** [comment]
It seems too niche for a setting, tbh. Would rather come up with a better way to escape special characters which I need for other things too.
