### ISSUE TITLE
mac版本vscode  点击侧边栏新建文件图标，无效，反而打开了侧边栏的筛选功能

### ISSUE THREAD

**Issue by zhang-hongwei** [Microsoft/vscode#73060]
Issue Type: <b>Feature Request</b>

mac
在通过commond+n快捷键新建文件的时候，没有生成文件，而是打开了侧边栏的筛选功能，点击新建问价图标也不行

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.0.0

**Comment by byyxx128** [comment]
There's lots of typos and grammar errors in the author's description, so you may not understand what he said via a translator app. This is **NOT** a **Feature Request**.
Translation here. I don't have his issue.

> When trying to create a new file via `Command+N`, no new file but the filter of the sidebar was opened, and the icon for New File doesn't work as well.

***
大哥你不说英文也罢了，中文也有错别字也是服了……而且你这也不是新功能请求……
![image](https://user-images.githubusercontent.com/20079289/56940683-edb6af00-6add-11e9-8b42-6a21007966b7.png)
![image](https://user-images.githubusercontent.com/20079289/56940689-f7401700-6add-11e9-8360-62953a2d5539.png)

**Comment by zhang-hongwei** [comment]
真尴尬。。。谢谢啊

**Comment by mgenware** [comment]
Translation: `Cmd+N` seems not working properly, instead of opening a new file, it opens the filter on sidebar, neither does clicking new file icon works.

I think you can refer to this [issue](https://github.com/Microsoft/vscode/issues/54605) regarding keybindings
