### ISSUE TITLE
invalid PHP problem regarding end }

### ISSUE THREAD

**Issue by MircoBabin** [Microsoft/vscode#73074]
Visual Studio code reports an invalid problem in PHP code. An end brace } should be missing. This is not true however.

I don't know if this is reported by Visual Code or by an extension.

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Store attached [404.txt](https://github.com/Microsoft/vscode/files/3130743/404.txt) as **404.php**
2. Open 404.php in VS Code
3. A problem will be reported, see also attached 
![screenshot](https://user-images.githubusercontent.com/8981285/56954929-5afb2c00-6b40-11e9-80de-40cf974466a5.png)

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
This error is coming from a PHP extension. Please file the issue on the PHP extension that you are using.

**Comment by mattacosta** [comment]
This isn't a bug either, as `<?` is not a valid open tag. You should change it to `<?php`.

**Comment by MircoBabin** [comment]
<? is a valid [short open tag](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag)

I agree it's nowadays almost never used. But this legacy code has loads of <? and <?= tags in it.

**Comment by MircoBabin** [comment]
&lt;? is a valid [short open tag](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag)

I agree this is deprecated. But this legacy project has loads of &lt;? and &lt;?= tags inside. It's a PHP 5.6 project, and upgrading in the short run is not an option.

So it would be great if short-open-tags would be recognized.
