### ISSUE TITLE
Terminal cursor is not in the right position on first show

### ISSUE THREAD

**Issue by Haosvit** [Microsoft/vscode#73079]
Issue Type: <b>Bug</b>

Step 1: Show Terminal

- Expect: Cursor is on the same line with directory text (Ex: D:\>)
- Actual result: Cursor is on the third line from the directory line.

Step 2: Split Terminal. New Terminal shows.
Step 3: Split Terminal again. The third terminal shows.

- Expect: See all initial texts (Ex: 'Microsoft Widnows [Version ...]....')
- Actual result:  Terminal automatically scrolls all the way to the its bottom, hide texts if the layout is not high enough.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-jest-runner|fir|0.3.4
beautify|Hoo|1.4.11
debugger-for-chrome|msj|4.11.3
code-settings-sync|Sha|3.2.9
vscode-fileutils|sle|2.13.7
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.7.6
sort-lines|Tyr|1.8.0
gitflow|vec|1.2.1
highlight-matching-tag|vin|0.9.1
glean|wix|4.10.3
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
markdown-all-in-one|yzh|2.3.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by Tyriar** [comment]
All text wrapping related issues should also improve in Windows 1903 due to the introduction of ConPTY, see https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423
