### ISSUE TITLE
Can't create a file or folder in empty root folder with the left pane

### ISSUE THREAD

**Issue by a-gn** [Microsoft/vscode#73078]
Issue Type: <b>Bug</b>

1. Open an empty folder in VSCode.
2. Click on the "New File" or "New Folder" button in Explorer in the left pane.

What should happen: a textbox appears where I can type a name, and the file/folder is created when I press Enter.
What happens: the new file/folder appears with the name textbox, and disappears after a few milliseconds. Nothing is created.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.6.3
r|Iku|1.0.9
latex-workshop|Jam|6.5.1
python|ms-|2019.4.11987
cpptools|ms-|0.22.1
vscode-scheme|sjh|0.4.0

</details>

**Comment by a-gn** [comment]
This seems to happen only when the root folder is empty. I created a few folders in it with Windows Explorer and now VSCode can create files and folders again.

**Comment by isidorn** [comment]
Dup of #72626 and some other issues. We plan to fix this
