### ISSUE TITLE
C/C++ .i header files taken as plain text

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode#73089]
In C language, there's usually header files that end in `.h`, but these can be pre-processed by compilers such as `gcc` to produce a `.i` file which serves the same purpose, but has already underwent macro text substitutions, and can also be included with `#include "file.i"`.

These are currently not recognized as C header files in vscode with the C/C++ extension.

**Comment by RMacfarlane** [comment]
Hey @david-cortes, since this is a feature request for the C++ extension, could you please file it in the extension's repo? https://github.com/Microsoft/vscode-cpptools

Thank you!

**Comment by sean-mcmanus** [comment]
@RMacfarlane Can you re-activate this? The request is to have VS Code automatically associate ".i" files with the "C" language without having to add it to files.associations. Also, ".ii" and ".cp" should be added for the "C++" language according to the gcc docs.

**Comment by RMacfarlane** [comment]
Got it, thanks for clarifying

**Comment by tristan957** [comment]
While file extensions for C/C++ are being updated, can `.C` and `.H` also be recognized as C++ files? Those are _fairly_ (take that with a grain of salt) common extensions for C++.

**Comment by sean-mcmanus** [comment]
@tristan957 Unfortunately, the files.associations in VS Code is case-insensitive; however, our C/C++ added code that will add specific files named with ".C" to have "cpp" association to workaround that VS Code limitation. For ".h" and ".H" files, VS Code already associates those with C++, but the icon looks like a "C" still (and our extension tries to fix the header file associations when it finds them as include targets).

**Comment by tristan957** [comment]
Ahh thanks for the clarification @sean-mcmanus. I had thought the extension addressed this in an earlier version, but could not remember. Is the case-insensitivity to stay?

**Comment by sean-mcmanus** [comment]
@tristan957 I don't know -- I filed bug https://github.com/microsoft/vscode/issues/59369, but it was marked as a duplicate, but I couldn't find the duplicate issue, and I never got a response from the VS Code team. Let me know if you find the issue that is tracking it.

**Comment by tristan957** [comment]
I troll the VSCode issue board frequently and have never found it. I wonder if they would accept a PR. I would be willing to add one since it is probably a one line change.

**Comment by tristan957** [comment]
@sean-mcmanus I am pretty sure that this might be the original case insensitivity issue that yours was closed by: https://github.com/microsoft/vscode/issues/12448

**Comment by sean-mcmanus** [comment]
The fix incorrectly associates "*.i" files with "cpp" instead of "c". Can someone please fix this to move ".i" to the "c" extension section and add ".ii" for the C++ part? We've made the change in our internal processing, but it requires us to add a files.associations to fix this.
