### ISSUE TITLE
python without debugging won't start if there is a breakpoint

### ISSUE THREAD

**Issue by tmdag** [Microsoft/vscode#73086]
- VSCode Version: 1.33.1
- OS Version:Linux 5.0.7-200.fc29.x86_64
Steps to Reproduce:

1. Open Python code
2. create a breakpoint
3. run python without debugging (ctrl+F5)

Terminal output:
```
cd /home/user/dev/Pytool ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/user/.vscode/extensions/ms-python.python-2019.4.11987/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 36019 /home/user/dev/Pytool/mypytool.py
Terminated
```

Does this issue occur when all extensions are disabled?: Yes/No
Not sure - Python extension is required

Enabled Extensions:
- Anaconda Extension PAck 1.0.1
- Bookmarks 10.4.3
- C/C++ 0.221
- Gist 3.0.3
- Git History 0.4.6
- GitLens - 9.6.3
- markdownlint 0.26.0
- Python 2019.4.11987
- Syncing 2.1.6
- OpenCL 0.5.2
- VEX 0.4.0
- TAML 0.4.0

**Comment by tmdag** [comment]
How do you know it’s an extension? If you have such info, could you please at least provide information- which extension ??

**Comment by isidorn** [comment]
Python extension. https://github.com/Microsoft/vscode-python
