### ISSUE TITLE
How to hide icon showing file status as (M: modified, U: untracked ... ) ?

### ISSUE THREAD

**Issue by abhijais2** [Microsoft/vscode#73085]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by RMacfarlane** [comment]
Hi @abhijais2, to keep our work manageable, we ask that issues created in this repository be either bug reports of features requests. In the future, please submit questions to stackoverflow.

You can use set the "git.decorations.enabled" setting to false to remove the file statuses from the file explorer.
