### ISSUE TITLE
There are 2 Node Debug extensions installed (come builtin)

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#73080]
![2019-04-30 at 14 42](https://user-images.githubusercontent.com/6391776/56962187-3b6efe00-6b56-11e9-9d26-f7e9d9c4b217.png)
 
Is it safe to remove one of them? Is this a bug?

**Comment by isidorn** [comment]
I have no clue how you got into this state. Forwarding to @sandy081 since there should never be two of the same extensions installed.

**Comment by sandy081** [comment]
@nikitavoloboev In which version of VS Code do you see this? Can you please open the extensions folder using the command `F1 -> Open Extensions Folder` and check if you have node debug extension `ms-vscode.node-debug2` exists there?

**Comment by nikitavoloboev** [comment]
```
~/.vscode/extensions
❯ ls
alefragnani.bookmarks-10.4.3				formulahendry.code-runner-0.9.8				ms-vscode.go-0.10.1					sleistner.vscode-fileutils-2.13.7
deerawan.vscode-dash-2.1.0				github.vscode-pull-request-github-0.6.0			ms-vscode.node-debug2-1.33.0				vscodevim.vim-1.4.0
eamodio.gitlens-9.6.3					james-yu.latex-workshop-6.5.1				ms-vscode.vscode-typescript-tslint-plugin-1.0.0		vscodevim.vim-1.7.0
esbenp.prettier-vscode-1.9.0				ms-kubernetes-tools.vscode-kubernetes-tools-0.1.18	nonoroazoro.syncing-2.1.6				wakatime.vscode-wakatime-2.0.7
fabiospampinato.vscode-monokai-night-1.4.1		ms-python.python-2019.4.11987				peterjausovec.vscode-docker-0.6.1
fabiospampinato.vscode-todo-plus-4.13.0			ms-vscode.cpptools-0.22.1				redhat.vscode-yaml-0.4.0
```

No `ms-vscode.node-debug2` there.

**Comment by sandy081** [comment]
I see it is there in your user installed extensions - `ms-vscode.node-debug2-1.33.0`. Any idea if you have installed it explicitly?

**Comment by nikitavoloboev** [comment]
> Any idea if you have installed it explicitly?

I am not sure to be honest. I certainly didn't install this specific extension from the marketplace but I may have installed things like [TSLint](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) and maybe ms-vscode is transitive dependency of it. Not sure.

What should I do in this case?

**Comment by sandy081** [comment]
I can try out installing the extensions you have and see if we auto install it. To fix the issue you can delete it from the directory.

**Comment by nikitavoloboev** [comment]
> To fix the issue you can delete it from the directory.

There is only one folder of it in directory. But VSCode shows two in the sidebar. 

If I delete I lose both of them? And thus something will break?

**Comment by sandy081** [comment]
No, node debug is a built in extension and is packaged already. So even if you delete this, the packaged one exists.

I just figured out that following extension could be a culprit that installs the extension - https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing

I will file an issue against it.

**Comment by sandy081** [comment]
https://github.com/nonoroazoro/vscode-syncing/issues/58

**Comment by nikitavoloboev** [comment]
Ше

**Comment by sandy081** [comment]
@nikitavoloboev It is not entirely sure if sync extension would have caused this or not. Even thought it has checks for built in extensions, it is unpacking extensions by itself which means it is not going through VS Code to install extension. 

Is it possible if you can repro it?

**Comment by nikitavoloboev** [comment]
> Is it possible if you can repro it?

Not sure how. Will close this and reopen if I ever will. Thanks.
