### ISSUE TITLE
execvp(3) failed.: No such file or directory in MAC OS

### ISSUE THREAD

**Issue by mahegd** [Microsoft/vscode#73087]
- VSCode Version:1.33.1 (1.33.1)
- OS Version: MAC OS version 10.14.4 (18E226)

Steps to Reproduce:

1.Create the below tasks
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "JC",
            "command": "java",
            "osx": {
                "command": "\/Library\/Java\/JavaVirtualMachines\/jdk1.8.0_172.jdk\/Contents\/Home\/bin\/javac -d ${workspaceFolder}\/bin"
            },
            "args": [
                "${file}"
            ]

        }    ]
}
2. Compile any file we get the below exception:
Executing task in folder javacode: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/javac -d ./bin /work/code/javacode/src/ch9/p1/Protection.java <

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by mahegd** [comment]
The issue is not observed if I compile it manually from the terminal.

**Comment by alexr00** [comment]
What is the command line you use to compile from the terminal?

**Comment by mahegd** [comment]
I am running the below command from terminal "/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/javac -d /work/code/javacode/bin /work/code/javacode/src/ch9/p1/Protection.java".

which is the same command executed as part of task created in VS code. Below is the screenshot

<img width="1439" alt="vscode_error" src="https://user-images.githubusercontent.com/50145466/57113188-75383400-6d11-11e9-96d0-7a1fecb1ea56.png">

Attached is the tasks.json 
[tasks.json.zip](https://github.com/Microsoft/vscode/files/3140265/tasks.json.zip)

**Comment by alexr00** [comment]
Can you try moving all your args into the args attribute? I think that it's getting escaped oddly because you are mixing and matching using `args` with putting args in your `command`

**Comment by mahegd** [comment]
The changes mentioned worked. I have moved it to args. Below is the task:

{
            "label": "JC",
            "command": "java",
            "osx": {
                "command": "\/Library\/Java\/JavaVirtualMachines\/jdk1.8.0_172.jdk\/Contents\/Home\/bin\/javac"
            },
            "args": [
                "-d",
                "${workspaceFolder}\/bin",
                "-classpath",
                "${workspaceFolder}\/bin:${workspaceFolder}\/src",
                "${file}"
            ]

        }
