### ISSUE TITLE
Variable Naming completions

### ISSUE THREAD

**Issue by SupinePandora43** [Microsoft/vscode#73098]
such as:
i write "String "
and: completions are "myString|_String|mString"

**Comment by RMacfarlane** [comment]
@SupinePandora43 What languages is this for?

**Comment by SupinePandora43** [comment]
i see'd it in c# in visual studio, but it can be for other languages too.

**Comment by RMacfarlane** [comment]
Can you explain a little more? Is this about completions for existing variables, or suggestions for new variables?

**Comment by SupinePandora43** [comment]
for new variables. @RMacfarlane

**Comment by SupinePandora43** [comment]
i think about extension, but it's hard!
