### ISSUE TITLE
Expose offline/online detection to extensions

### ISSUE THREAD

**Issue by jdoklovic** [microsoft/vscode#73094]
Our Atlassian extension relies heavily on an internet connection and when the user goes offline, we need to disable some functionality and enable it when the user comes back online.

Currently, vscode doesn't expose offline/online events to extensions and so we have to use our own polling to do this which is not great.

It would be awesome if vscode allowed extensions to register to receive offline/online events.

**Comment by muuvmuuv** [comment]
Yes searching for the same! My temp solution is:

```ts
import dns from 'dns'

checkConnection(): Promise<boolean> {
    return new Promise(resolve => {
      dns.resolve('code.visualstudio.com', (err: any) => {
        if (err) {
          // No connection
          window.showInformationMessage(
            'Sundial detected that you are offline but will still try to run.'
          )
          resolve(false)
        } else {
          // Connected
          resolve(true)
        }
      })
    })
  }
```

**Comment by jdoklovic** [comment]
any word on this?

**Comment by nbransby** [comment]
Looking for this too - looks straight forward with access to electron api:

https://electronjs.org/docs/tutorial/online-offline-events

Would a PR along these lines be accepted?

**Comment by muuvmuuv** [comment]
Hey, currently working on natively integrating auto dark mode to VS Code and there we make use of the native browser functionalities, therefore I would use them here too. So no electron, just pure JavaScript, which would allow VS Code for the browser to make use of this new exposed API too:

```javascript
function updateOnlineStatus(event) {
    var condition = navigator.onLine ? "online" : "offline";
console.log("OFF/ON:", condition);
console.log("EVENT:", event.type);
  }

  window.addEventListener('online',  updateOnlineStatus);
  window.addEventListener('offline', updateOnlineStatus);
```
