### ISSUE TITLE
DocumentSymbolProvider's return type definition is maybe incorrect

### ISSUE THREAD

**Issue by PrsPrsBK** [Microsoft/vscode#73093]
- VSCode Version: 1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64
- OS Version: Microsoft Windows [Version 10.0.17763.437]

The return type of `provideDocumentSymbols` of `DocumentSymbolProvier` is `ProviderResult<SymbolInformation[] | DocumentSymbol[]>`([vscode.d.ts](https://github.com/Microsoft/vscode/blob/94ba9cfe20cc2e7f5a7b895a2bbf5005610f37f2/src/vs/vscode.d.ts#L2649)).
You can use `SymbolInformation`, but it's `containerName` does not work.

This method's [declaration](https://github.com/Microsoft/vscode/blob/0200bdd71e409954ae12149fe493f38065306555/src/vs/editor/common/modes.ts#L908) does not include `SymbolInformation` as return type, 
so I titled this issue as 'definition file (and [documentation](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider) ) issue'. If this is implementation issue, excuse me.

Steps to Reproduce:

1. use `SymbolInformation` and it's `containerName` like [that](https://github.com/PrsPrsBK/vs-symbol-by-ctags/blob/container-arg-of-SymbolInformation/src/extension.ts#L128).
2. `tsc -p ./`, then go debug with test_tree2/(by [Sym-By-C02](https://github.com/PrsPrsBK/vs-symbol-by-ctags/blob/container-arg-of-SymbolInformation/.vscode/launch.json#L18) setting)
3. `Ctrl+Shift+p` and `Symbol by Ctags` command.
4. open `main.pony` file, then you can see flattend (not nested) symbols, like a following screenshot.

![2019-05-01_syminfo](https://user-images.githubusercontent.com/24764443/56978564-c0880080-6bb2-11e9-8582-c85f3056e08b.png)

5. Otherwise, when you use `DocumentSymbol` and set `children` property like [that](https://github.com/PrsPrsBK/vs-symbol-by-ctags/blob/useDocSym/src/extension.ts#L140), you will get symbols in nested tree, like a following screenshot.

![2019-05-01_docsymbol](https://user-images.githubusercontent.com/24764443/56979062-dc3fd680-6bb3-11e9-8b30-f39e51b63730.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
The `containerName` is only shown when rendering outline items in quick outline, the outline panels works best when returning a document symbol tree (which the former don't support)

**Comment by PrsPrsBK** [comment]
Thanks for reply. I can understand, so if there is no issue in type definition, I find no problem.
