### ISSUE TITLE
Insiders not updating on Windows

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#73095]
VS Code insiders failing to update
- VSCode Version: 1.34.0-insiders
- OS Version: Windows 10 enterprise

Steps to Reproduce:

1. I click on the gear to update Insiders, it immediately crashes
2. I open Insiders again, open a folder, it crashes again
3. Open Insiders again, click check for updates, and the gear shows there is still an update.

About:
Version: 1.34.0-insider (user setup)
Commit: 0200bdd71e409954ae12149fe493f38065306555
Date: 2019-04-29T05:18:26.523Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
What does the crash look like? Is there any extra information about the crash?

**Comment by sana-ajani** [comment]
Tried updating again on that specific version and it works now!
