### ISSUE TITLE
Please add support for Command Prompt/ WIndows powershell 

### ISSUE THREAD

**Issue by sibinx7** [Microsoft/vscode#731]
Visual Studio Code is great tool for developers, it need some more features. If there is command prompt ( like in PHPStorm/WebStorm/RubyMine) it will be very useful. Frontend developers can easily use bower/grunt/gulp/npm to install,run gulp/grunt commands. It will be a very useful feature.

**Comment by bpasero** [comment]
We have an integrated terminal since many versions.
