### ISSUE TITLE
Visual Studio Code doesn't come up in the Windows 10 start bar search

### ISSUE THREAD

**Issue by addMitt** [Microsoft/vscode#73107]
Issue Type: <b>Bug</b>

The program is called "Visual Studio Code." I open the start menu with the Windows key and type "visual" and wait. Nothin. "visual studio." Nothin. "visual studio code." Nothin. I go to all programs, scroll down to the "Visual Studio Code" folder, expand it, find "Visual Studio Code," click on it, start it up.

Why doesn't this thing come up in the search??

Sorry if this isn't necessarily a bug, I guess it could be a Windows 10 issue, but there's something about this app in particular that makes it immune to search.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (25.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2

</details>

**Comment by msftrncs** [comment]
Did you just recently install it for the first time?

Are you using the 'user' edition or the 'system wide' edition?  If the user edition, make sure you are logged in to the same user account you installed it in.

The user edition comes up right away on my system, same version of VS Code.

**Comment by vivekmalhotra** [comment]
^ 
Same for me as well. Have the same windows and VS code builds as yourself.  "User" version comes up in windows start search right away.

But, I remember having some random issues with Windows start search in the past (comes as a part of using Windows system). Over time, this has resolved by itself. Few suggestions depending upon how much this issue frustrates you:

1. Search "Indexing Options" in start > If it shows up, click on it 
          - Click Modify > See that nothing weird is in the Exclude list > Click OK
          - Then, click Advanced in Indexing Options window > Click Rebuild.
          - It will take some time for your computer to rebuild the index. Once it says complete, see if that resolves the issue.

2.  Simple suggestion without any headaches - I suggest that you may pin VS code program to your taskbar for an easy access if this is the only app that does not show in windows start search.

**Comment by adil-s** [comment]
in start search box, type "code" and it should show up.

**Comment by RMacfarlane** [comment]
I'm not sure how much influence we have over we get indexed for search - @sbatten @joaomoreno any windows insights?

**Comment by msftrncs** [comment]
I think this might be a case of the Windows Indexer is stuck, faulted, or busy.  I have seen the indexer get stuck on a file (3rd party filter) and it prevents further items from being indexed until the service gets restarted.  It might require a reboot (or a few) and some time, and then everything will be fine.

**Comment by addMitt** [comment]
Yeah this is obviously an issue on my end since it seems to work fine for everyone else. Rebuilding the index didn't work, however I'm sure a few reboots should get it populating.
