### ISSUE TITLE
Extension "marketplace" tags mis-linked to Azure Devops

### ISSUE THREAD

**Issue by SamB** [Microsoft/vscode#73105]
- VSCode Version: All.
- OS Version: All.

I was unable to find an ideal place to report this issue with the web interface to the extension gallery ("marketplace"), so I'm reporting it here instead. (I'm not about to pay $500 just to report a single copy and paste error!)

Steps to Reproduce:

1. Go to an extension's page on the gallery. For example, [Mediawiki](https://marketplace.visualstudio.com/items?itemName=jakeboone02.mediawiki)
2. Click on one of the tags, say, "**mediawiki**".

**Actual** results: I arrive on a page (typically) saying "Your search for 'tag:mediawiki' didn't match any extensions".  If I look closely, I'll notice higher up where "Azure DevOps" is highlighted instead of "Visual Studio Code". In my example, the link pointed to <https://marketplace.visualstudio.com/search?term=tag%3Amediawiki&target=VSTS>, which ultimately redirected to <https://marketplace.visualstudio.com/search?term=tag%3Amediawiki&target=AzureDevOps&category=All%20categories&sortBy=Relevance>.

**Expected** results: a page listing Visual Studio Code extensions with that tag, including the one I started from. Based on the links for the categories, I conclude that the link in my example should have pointed to <https://marketplace.visualstudio.com/search?term=tag%3Amediawiki&target=VSCode>

Does this issue occur when all extensions are disabled?: Yes?

**Comment by RMacfarlane** [comment]
@viradhamMS @pkuma-msft

**Comment by pkuma-msft** [comment]
Thank you for reporting this @SamB, we will take a look and get it fixed soon.

**Comment by smadala** [comment]
Thanks @SamB for reporting this. We have fixed the issue.
