### ISSUE TITLE
Make Comment.*command not read-only

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#73100]
Right now, all command properties on [`vscode.Comment`](https://github.com/Microsoft/vscode/blob/21dc41b583d4d61fa7b44d6fa6b7addf6dabc002/src/vs/vscode.proposed.d.ts#L885) are read-only. It also has become a class recently (it used to be an interface that extension would be providing). 

Because of that, there is no type-safe way of changing these command properties now, or even providing them, given that `vscode.Comment` constructor doesn't accept commands as args.

**Comment by IlyaBiryukov** [comment]
Same applies to the `label` and `userIconPath` properties on `vscode.Comment`

**Comment by jrieken** [comment]
@rebornix Maybe we should go back to an interface for `Comment` - that fixes this issue, allows for more freedom and communicates that we don't expect change in the object, e.g that we use a copy and that subsequent changes are ignored

**Comment by IlyaBiryukov** [comment]
@jrieken well, the subsequent changes are not ignored if you also change the thread where the comment belongs to, e.g. with this code:
```typescript
// Suppose vscodeThread is a vscode.CommentThread with some comments on it
vscodeThread.comments[0].userName = 'New user name';

// This will trigger the update of the thread and the changes to the comment will have effect
vscodeThread.comments = vscodeThread.comments; 
```

**Comment by jrieken** [comment]
> @jrieken well, the subsequent changes are not ignored if you also change the thread where the comment belongs

Trust me, I know that but often people do this

```typescript
// Suppose vscodeThread is a vscode.CommentThread with some comments on it
vscodeThread.comments[0].userName = 'New user name';

// This will trigger the update of the thread and the changes to the comment will have effect
vscodeThread.comments = vscodeThread.comments; 

// does not work, needs another 'update'
vscodeThread.comments[0].label = 'Some Label';
```

**Comment by IlyaBiryukov** [comment]
I see your point from the API's point of view, and, given that comments are really rarely mutable, I agree that making them live objects is not worth it. I'm fine with that, provided that API would guarantee that, if `vscode.CommentThread` is updated, all its comments are updated too (up to their current state), and that future changes to the comments may not go live until the next update of the comments thread.

Technically speaking, I think `@debounce` on `ExtHostCommentThread.eventuallyUpdateCommentThread()` will make your example update `comments[0].label` even if it runs after `vscodeThread.comments = vscodeThread.comments;`. All code that runs before debounce-scheduled function runs will have effect.

**Comment by rebornix** [comment]
`Comment` is an interface now.

**Comment by alejessi** [comment]
Non voglio più ricevere queste emali
