### ISSUE TITLE
Add option to disable auto removing matching brackets

### ISSUE THREAD

**Issue by kerrytazi** [microsoft/vscode#73102]
Example:
`|` is cursor position
step 1: `(|)`
step 2: Backspace
And it removes both brackets, left and right.

I find it annoying while you starting remove brackets from right. Example:
step 1: `(some text ()|)`
step 2: Backspace
step 3: Backspace
result: `(some text |`

None of other options solves this problem:

	"editor.matchBrackets": false,
	"editor.autoClosingBrackets": "never",

**Comment by trusktr** [comment]
Can you please turn this off. I come from vim, and it drives me crazy. Plus, even in non-vim mode, it is driving me crazy, wasting my time.

**Comment by alexandrudima** [comment]
The setting `"editor.autoClosingBrackets": "never"` does disable the closing bracket deletion for me:

![Kapture 2019-07-30 at 12 02 47](https://user-images.githubusercontent.com/5047891/62120497-faf05f00-b2c1-11e9-90c8-fb7349fe4594.gif)

**Comment by kerrytazi** [comment]
Indeed, tried again. Problem in Vim-extension.
