### ISSUE TITLE
Go To Definition opens first match

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#7310]
Is this the desired behaviour when having multiple matches? I mean, you still have to confirm with Esc or Enter to close the preview so I argue that it should behave just like Peek Definition instead and not open the first match.

![go_to_definition_open](https://cloud.githubusercontent.com/assets/1297882/15851950/813949b6-2c9f-11e6-886c-9992b4cb2652.gif)

The downside of opening the first match is that with the default `"explorer.autoReveal": true`, you potentially expand a lot of folders permanently which clutters the tree view.

1.2.0-insider
Win10

**Comment by jrieken** [comment]
Yes - that's the designed behaviour and the difference between _go to_ definition and _peek_ definition.
