### ISSUE TITLE
VS code can't find my compiler

### ISSUE THREAD

**Issue by ParsifalBlake** [Microsoft/vscode#73109]
Issue Type: <b>Feature Request</b>

the compiler is in the PATH but when I try to build (I'm a first time user of VSC), I get a message saying it can't find the compiler.     Can you help?   

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

**Comment by vivekmalhotra** [comment]
* Consider changing your issue to a question
* Not quite sure what you mean exactly. What are you trying to build? Take screenshots if necessary.

**Comment by RMacfarlane** [comment]
Hey @ParsifalBlake, this repository is meant to track bug reports and feature requests. In the future, if you have a question, please ask it on stackoverflow.

If you think this is a bug, please include information about language you are working with, what the compiler is, what steps you are taking to build, etc.
