### ISSUE TITLE
Django extension breaks emmet explansion when it handles HTML files

### ISSUE THREAD

**Issue by bn-l** [Microsoft/vscode#73113]
- VSCode Version: 1.33.1
- OS Version: win 7
- "Django" extension version: 0.19.0

Steps to Reproduce:

1. vscode with the installed by default django extension 
2. open an html file

Does this issue occur when all extensions are disabled?: No

The django extension takes priority over the default HTML file handling and breaks emmet tap expansion. Curiously emmet expansion works selecting it using the command palette.  Huh?

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/57029950-0dda9100-6bf8-11e9-81f0-b451466aa107.png)

![image](https://user-images.githubusercontent.com/4033249/57030056-6742c000-6bf8-11e9-902c-fe4f9a671634.png)
