### ISSUE TITLE
Trouble with jsconfig.json in VSCode (dependencies intellisense on import not working)

### ISSUE THREAD

**Issue by cbdeveloper** [Microsoft/vscode#73118]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Does this issue occur when all extensions are disabled?:** Yes

**Steps to Reproduce:**

1. Open new project and run `npm init --yes` in root folder.
2. Create `jsconfig.json` in root folder exactly like described below.
3. Install some dependencies.
4. Create `src` folder and a `example.js` file inside of it.
5. Try to import some installed dependency and check for autocomplete.

**NOTE:** I had to downgrade to 1.32 because I was getting that issue with extremely slow intellisense when using `styled-components` library with VScode 1.33.

**Root folder structure:**

```
functions/
node_modules/
src/

.babelrc
.firebaserc
jsconfig.json
firebase.json
package.json
wepack.config.js
```

**jsconfig.json**

Exactly like the example from [https://code.visualstudio.com/docs/languages/jsconfig](https://code.visualstudio.com/docs/languages/jsconfig)

```
{
  "compilerOptions": {
      "target": "es6"
  },
  "include": [
    "src/**/*"
  ]
}
```

I'm almost sure that I've been using it like this without any problems before.

I can't tell exactly when it happened, but right now I'm **not getting intellisense for my installed dependencies.**

![ImportNotWorking](https://user-images.githubusercontent.com/43407798/57009273-825c0280-6bed-11e9-9334-ea579a94d87d.gif)

If I delete `jsconfig.json` or simply rename to deactivate it, it goes back to normal:

![ImportWorking](https://user-images.githubusercontent.com/43407798/57009281-8ee05b00-6bed-11e9-934b-28f5fa71f185.gif)

**Comment by cbdeveloper** [comment]
Just found out that if I add `"module" : "commonjs"` it works again.

Not sure why, and I didn't see any mention to this in:
[https://code.visualstudio.com/docs/languages/jsconfig](https://code.visualstudio.com/docs/languages/jsconfig)

Why is this happening? What is the proper way to configure `jsconfig.json` ?

**jsconfig.json**

```
{
  "compilerOptions": {
      "target": "es6",
      "module": "commonjs"
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by mjbvz** [comment]
Yes if you are importing modules from `node_modules`, you generally need to set `"module": "commonjs"` (`"moduleResolution": "node"` should also work I believe). `commonjs` is the default setting, but `"target": "es6"` overrides it to use `"module": "es6"` unless you explicitly specify another `"module"` setting

The module options are covered in a bit more detail here: https://stackoverflow.com/questions/41993811/understanding-target-and-module-in-tsconfig
