### ISSUE TITLE
Debug: hit count breakpoint can't work well  in required module

### ISSUE THREAD

**Issue by qianliu013** [microsoft/vscode#73116]
Issue Type: <b>Bug</b>

The execution always breaks when hit count breakpoint in required codes. 

Reproduce:
```js
// main.js
require('./lib');
[1, 2].forEach(i => {
  console.log(i, 'main hit count') // set hit count in this line. For example: 100
})
```
```js
// lib.js
[1, 2].forEach(i => {
  console.log(i, 'lib hit count') // set hit count in this line. For example: 100
})
```

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Does a normal breakpoint (non-hit count) work?

**Comment by qianliu013** [comment]
Yes, a normal breakpoint or conditional breakpoint can work.

**Comment by roblourens** [comment]
What is the hit condition you are using?

**Comment by qianliu013** [comment]
In the code above, set expression `i === 2`

**Comment by roblourens** [comment]
i will start at 0, then be 1, it will never be `== 2` in your code

**Comment by qianliu013** [comment]
i is the element in the array, so it will be 2 in the second iteration.

**Comment by roblourens** [comment]
Ack, I was thinking it was the index parameter. Sorry.

**Comment by roblourens** [comment]
I can't reproduce this. Please set `"trace": true` in your launch config and upload the log from the path written to the debug console.

**Comment by qianliu013** [comment]
[debugadapter.txt](https://github.com/microsoft/vscode/files/3195812/debugadapter.txt)

**Comment by roblourens** [comment]
I just see `setBreakpoints({"source":{"name":"lib.js","path":"/Users/liuqian26/project/common/playground/node/lib.js"},"lines":[3],"breakpoints":[{"line":3,"hitCondition":"100"}],"sourceModified":false})`, so hitCondition=100, I don't see `i == 2` like you said

**Comment by qianliu013** [comment]
I only set hit count and debug code as shown in the last log file. 
Remove the old log file and replace the hitCondition with condition(i==2) in lib.js: [debugadapter.txt](https://github.com/microsoft/vscode/files/3196052/debugadapter.txt)

**Comment by roblourens** [comment]
I think I got confused, so you said that the conditional bp __does__ work but the hit count doesn't work? So what is the hit count that doesn't work? `100` will not be hit because the code doesn't run 100 times.

**Comment by qianliu013** [comment]
I'm sorry that I didn't make myself clear. In lib.js, When setting hit count 100,  expect code does not hit the breakpoint, but in fact, the code will always hit the breakpoint, so I said the hit count doesn't work. When set the conditional breakpoint i==2, the code only hit breakpoint once, so  I said it does work.


![May-21-2019 11-06-23](https://user-images.githubusercontent.com/12949166/58065531-a42b2280-7bb8-11e9-9422-b5bb2c0f738d.gif)

**Comment by roblourens** [comment]
Oh, now I've got it.

I think I just need to move addHitConditionalBp above this line: https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L1712

**Comment by roblourens** [comment]
We are rebuilding the debug adapters currently, so this isn't going to get fixed.
