### ISSUE TITLE
Switching workspace briefly shows icon in editor title?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#73121]
In insiders (with tabs disabled) when I switch workspaces, I briefly see an icon which then disappears, even though I have icons disabled:

![before](https://user-images.githubusercontent.com/900690/57010717-73ca1700-6bfe-11e9-9402-e1fe1d747e11.gif)

**Comment by isidorn** [comment]
I am not sure when and where do we apply the icon theme. Also assinging to @aeschli

**Comment by bpasero** [comment]
@isidorn reproduces for me even with a fresh user data directory with the only change I did to disable file icons.

**Comment by bpasero** [comment]
I can reproduce in insiders but not stable, so it must be a regression. I tried with `--user-data-dir` and all extensions disabled.

**Comment by bpasero** [comment]
I take it back, this reproduces in stable too, steps:
* macOS 10.14.x
* `code --user-data-dir <fresh dir> --disable-extensions`
* open any folder with files
* open command palette, select to change file icon theme
* arrow up until you reach the first entry (no icons)
* quit
* start
* 🐛 flickers

**Comment by bpasero** [comment]
@aeschli a regression from https://github.com/microsoft/vscode/commit/618bc0a8037ba50dd8f25744abc4eb2a2d817b03#diff-376c987350ff44c94e8045bd03a83444. We no longer cached icon themes when "none" was picked.

PS: shouldn't you also check for remote authority in the other place where we store themes or does it not apply here: https://github.com/microsoft/vscode/blob/36065e6b95568b1de18e38811b1e21b49ba52aa3/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L422

**Comment by aeschli** [comment]
> PS: shouldn't you also check for remote authority in the other place where we store themes or does it not apply here

It only applies to icon themes as they reference (possibly remote) fonts and icons.
Color themes do not have any references to the outside.

**Comment by bpasero** [comment]
You are welcome.

**Comment by aeschli** [comment]
@bpasero Thanks for chasing this down and for the fix
