### ISSUE TITLE
Enable FileSystemProvider to stat a file as readonly

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#73122]
Currently a [`FileSystemProvider`](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider) can register as readonly, meaning that every file it provides is opened in a readonly editor. This is nice, but even better if the [`FileStat`](https://code.visualstudio.com/api/references/vscode-api#FileStat) it returns from its stat() method had an optional `readonly` property. Then I think [this line](https://github.com/Microsoft/vscode/blob/c1abf7978d59415dcfcf8cfcb15e0ee30c5e45a5/src/vs/workbench/services/files/common/fileService.ts#L206) could easily treat a true readonly value as a signal to set `isReadonly` true. @bpasero what do you think?

**Comment by bpasero** [comment]
I think this is generally a nice idea, but I am worried that it will make file operations very complicated: imagine a folder where just a few files are readonly. Now a fs operation runs that operates on all files in the folder, not just one (e.g. rename of the folder? delete?). Naturally with this we would first have to ask the provider if any of the files that are potentially modified are readonly before even starting the operation, which seems quite crazy to me.

**Comment by gjsjohnmurray** [comment]
Fair point, but what happens at the moment in such scenarios if the user has set restrictive OS-level file permissions to protect just a few of the files in a folder tree? Does VSCode already run a preflight check on, say, a parent folder delete and decline to start the operation if any of the descendant files isn't deletable?

**Comment by bpasero** [comment]
@gjsjohnmurray yeah we are not doing anything but rely fully on the OS to do the right thing. If one file in a folder is write protected, the OS may decide that a rename on the parent folder is not possible (have not validated that).

**Comment by gjsjohnmurray** [comment]
@bpasero I'd also argue that it **shouldn't** be VSCode's responsibility to recursively check the readonly stat of every file within a folder before asking the `FileSystemProvider` to delete the folder. The FSP is best placed to know if that's an appropriate check to make. For example my FSP might simply fail the folder delete request immediately because it's a root folder. I certainly don't want you to have wasted time (yours and mine) walking the entire tree and asking me to stat each file for you if I'm always going to reject your subsequent request to delete the root folder.

**Comment by bpasero** [comment]
@gjsjohnmurray yeah good point 👍

**Comment by gjsjohnmurray** [comment]
Please can this issue get some love soon?

**Comment by gjsjohnmurray** [comment]
@jrieken are you open for a PR to implement this? I'm guessing it needs to be treated as proposed API. I'd copy the `FileStat` interface into vscode.proposed.d.ts, add `readonly?: boolean`, and wire this up. That has become a bit more complicated since @bpasero did some restructuring in https://github.com/microsoft/vscode/commit/920d80e28a6689a2f7158059a2f7da03b242e5c0 but ultimately the new readonly from `FileStat` would have its effect here.
https://github.com/microsoft/vscode/blob/8134d8c9e7ca00b43ec7ec36034c4dd345eed36b/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L1031

**Comment by jrieken** [comment]
Proposing API is usually the very last step and requires an "internal" API first and I don't think there is one. I believe that would be around [here](https://github.com/microsoft/vscode/blob/31c034604e5e70366b335c743ccdfb5eea6b7408/src%2Fvs%2Fplatform%2Ffiles%2Fcommon%2Ffiles.ts#L779-L780) and than needs options for editors, custom editor etc

**Comment by gjsjohnmurray** [comment]
I have submitted draft PR #111237 for comment and guidance.

**Comment by bpasero** [comment]
One thing to note is that if we decide to push this, the experience for readonly files will be different from how we treat OS readonly files. We would probably not adopt this for OS local files to preserve this:
* you can always type in readonly files, even if they are readonly
* you can save readonly files and be asked to overwrite the write protection at that point
* you can still decide to "Save As" to a different file name to avoid readonly'ess

With this solution all you see is a readonly editor. I would not adopt this new API for OS local files.

**Comment by bpasero** [comment]
Little update to https://github.com/microsoft/vscode/issues/73122#issuecomment-733572863: with https://github.com/microsoft/vscode/commit/5a8936ae639316163e89e08920d2120515ab55e6 there is a new notion of `FileWriteLock` errors that a provider can throw and a new `unlock` write capability. As such, the feature of unlocking write protected files is fully independent from "readonly" notion. As such I think it would be possible to allow for readonly files that turn the editor readonly without impacting the scenario of write protected files.

Timing wise I cannot make any better promises than tackling this in our issue grooming iteration.

**Comment by bpasero** [comment]
Proposal after API call:

```ts
export enum FileStatPermissions {
	/**
	 * The file is readonly.
	 */
	Readonly = 1
}

/**
 * The `FileStat`-type represents metadata about a file
 */
export interface FileStat {

	/**
	 * The permissions of the file, e.g. whether the file is readonly.
	 *
	 * *Note:* This value might be a bitmask, e.g. `FileStatPermissions.Readonly | FileStatPermissions.Other`.
	 */
	permissions?: FileStatPermissions;
}
```

**Comment by jrieken** [comment]
Let's keep this open to have a single item for API proposal to finalization

**Comment by gjsjohnmurray** [comment]
@bpasero when retrospecively reviewing your much-appreciated updates to my original PR I noticed this:

https://github.com/microsoft/vscode/blob/c4f3f8f9bea635a0bd7d1aff29c55382597922fa/src/vs/platform/files/test/electron-browser/diskFileService.test.ts#L92-L94

Is there a reason why line 93 isn't as follows?

```ts
this.readonly = enabled;
```

**Comment by bpasero** [comment]
@gjsjohnmurray yeah good point, I can change that.

Btw https://github.com/microsoft/vscode/commit/23dc403a17884a113087647afee371d6d1e867a2 has a couple more changes that were needed. I forgot that in many places we do a check for readonly on the file system provider, but now with individual files potentially being readonly, that check needs to change.

**Comment by gjsjohnmurray** [comment]
I think this shipped in 1.57 so can be closed, right?

https://code.visualstudio.com/updates/v1_57#_enable-file-system-providers-to-declare-a-file-as-readonly

**Comment by bpasero** [comment]
@gjsjohnmurray it is only proposed API, not finalized yet.

**Comment by gjsjohnmurray** [comment]
@bpasero sorry, I misread the 1.57 release notes. I often find I miss the point where the "Proposed Extension APIs" section begins. Maybe the text of each subsection of that could helpfully reiterate "proposed API" in future release notes?

**Comment by bpasero** [comment]
**Verification**

Test that you can mark a file as readonly without enabling proposed API via the `permissions` property on a file. https://github.com/microsoft/vscode/issues/124846 has details how to use it.

**Comment by DavyLandman** [comment]
I hope this isn't considered an annoying question, but what is the process for an api change like this to graduate out of the insiders/proposed status?

**Comment by bpasero** [comment]
Not at all, see: https://github.com/microsoft/vscode/wiki/Extension-API-process

**Comment by DavyLandman** [comment]
@bpasero thanks, I was already clicking through the wiki, but seemed to have missed that.

So without jumping on calls, is there a way I can help move this forward? The change seems quite minimal, and would help 2 extensions I'm developing (both are languages with their own virtual file systems for some parts).

I saw this list, in the wiki:

- [ ] Is there a non-trivial usage-sample for this new API?
- [ ] Are there multiple (ideally not similar) use-cases that this proposal solves?
- [ ] Is the proposal too narrow (not solving enough) or too broad (trying to solve too much)?
- [ ] Who would use this new API?

And I'm not completely sure where this should be discussed? Should I raise a new issue, there are already quite a few issues about this topic on file specific read-only status.

**Comment by bpasero** [comment]
@DavyLandman this API will be available in our upcoming release next week.

**Comment by DavyLandman** [comment]
Thanks @bpasero!

**Comment by rchiodo** [comment]
I believe this was verified by https://github.com/microsoft/vscode/issues/124846?

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray if you are able to verify in current insiders, that would be ideal 👍

/verified

First I had to work out how to make fsprovider-sample use the new API because it is no longer in vscode.proposed.d.ts but not yet published in `@types/vscode`
