### ISSUE TITLE
Can't click on paths in terminal window

### ISSUE THREAD

**Issue by jonantoine** [microsoft/vscode#73129]
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

I can't click on any paths in the terminal window. I have two co-workers running the exact same code and versions that I am running and they have no issues. Can some one please help with this?
![image](https://user-images.githubusercontent.com/2699833/57017431-d6161e00-6be4-11e9-9a1b-73920f20fde0.png)

Above is a sample of my terminal window. Hovering over paths does not underline them and ctrl+click does nothing either.

**Comment by tnrich** [comment]
I am also experiencing this bug right now but in a slightly different flavor. For me, after I cmd-click the link/path once, it loses its highlighting and is no longer clickable. 

I find that if after that, if I hit enter again, the highlighting comes back and I can click it as many times as I want. 

I'm using the latest vsCode v1.38.1
