### ISSUE TITLE
Tab key on refactoring window skips to next item but keeps the original highlighted

### ISSUE THREAD

**Issue by fbanyai** [microsoft/vscode#73126]
Issue Type: <b>Bug</b>

1. Call the refactoring window over any element with many available refactoring options (e.g.: a widget in Flutter)
2. Hit tab
3. The selection won't move BUT if you hit enter it will choose an option other than the highlighted one

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.93GB (3.95GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment]
Assigning @sbatten because this only happens when using custom title bars.

**Repo**
1. On Windows with custom title bar enabled
1. Open the ts file:

```ts
function foo() {
    const a = 1 + 2;
}
```

1. Select `1 + 2`
1. Trigger code actions and press tab

The second or third code action ends up being applied even though the visible selection never changes
