### ISSUE TITLE
JSDoc ignores scoped methods

### ISSUE THREAD

**Issue by thoughtsunificator** [Microsoft/vscode#73128]
https://github.com/Microsoft/vscode/issues/70162
Probably has to do with https://github.com/Microsoft/TypeScript/issues/31061

**Comment by thoughtsunificator** [comment]
Please do not ignore it even if you don't fix it now that does not mean it should never be fixed it aknowledge the issue first and then we will see..

**Comment by mjbvz** [comment]
We already reviewed this issue in Microsoft/TypeScript#31061 and decided it is a wont-fix. The reasons are clearly covered in the upstream issues's comments
