### ISSUE TITLE
Enabling an extension doesn't remove it from disabled list

### ISSUE THREAD

**Issue by fiendish** [microsoft/vscode#73133]
Issue Type: <b>Bug</b>

Disable an extension. 
See that it moves to the Disabled section of the extensions list. 
Enable the extension again. 
It doesn't move back.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (4.10GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|1.0.6
emojisense|bie|0.5.1
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.26.0
gitlens|eam|9.6.3
gc-excelviewer|Gra|2.1.32
vscode-power-mode|hoo|2.2.0
nsis|idl|3.16.1
r|Iku|1.0.9
nbpreviewer|jit|1.2.2
theme-dark-plus-contrast|k3a|0.1.101
vscode-lua-format|Koi|1.2.0
restructuredtext|lex|106.0.0
rainbow-csv|mec|1.0.0
python|ms-|2019.4.12954
cpptools|ms-|0.22.1
autodocstring|njp|0.3.0
vscode-luaformatter|sta|0.0.4
rewrap|stk|1.9.1
vscode-lua|tri|0.12.4
markdown-all-in-one|yzh|2.3.1
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
> See that it moves to the Disabled section of the extensions list.

I do not think it is moved automatically to disabled section. You have to refresh the view. Can you please confirm?
