### ISSUE TITLE
Add a window.title variable for the folder the workspace file is in

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/vscode#73138]
Just discovered the window.title feature and **LOVE** it!  How have I lived before this???  You guys rock

We currently have a .code-workspace file committed to be re-used across branches / devs.

Adding `rootPath` _kind of_ helps, but on windows it can be too long to show up in toolbar tiles, alt + tab and you have to actually switch to the window or hover to see the full path.  In alt + tab, hover doesn't even reveal :(

It would be **awesome** if there was a `rootFolder` that just displayed the parent folder of the workspace, which is in my experience is the big difference between workspaces.

i.e. for `${rootName}${separator}${rootFolder}`

C:\users\me\src\app\folder1\foo.code-workspace ->  `foo (Workspace) - folder1`
C:\users\me\src\app\folder2\foo.code-workspace ->  `foo (Workspace) - folder2`

**Comment by RMacfarlane** [comment]
@cmeyertons Can you describe your setup for your workspace files slightly more? Are they all named the same thing?

A couple of things that might achieve what you want:
- having distinguishing names for the code-workspace files themselves and using `$rootName`
- Adding a `name` property to the folder(s) in the code-workspace files and using `$folderName`

```
{
        "folders": [
                {
                     "name": "folder1",
                     "path": "path"
                }
        ],
        "settings": {}
}
```

**Comment by cmeyertons** [comment]
Yeah its the same workspace file name, mainly because we have it committed to source control and have multiple branches open often enough.
FVC at work, so we have different branches in different directories .  So I'll have `dev/foo.code-workspace` open as well as `prod/foo.code-workspace` open.

I would prefer not to rename the file in one of the branches because sooner or later I always accidentally commit that change!

**Comment by cmeyertons** [comment]
Will I have a decent shot of getting this done if I submit a PR?

Don’t want to get to that effort if it never gets accepted....

**Comment by joerg-walter-de** [comment]
I second that:

We have two base folders with identical repo names in both folders:
-- services
---- service1
---- service2
-- infrastructure
---- service1
---- service2

I would like to have in my window title
services / service1
infrastructure / service1

So a placeholder for the name of the folder the  repo is in would be very helpful

**Comment by afspies** [comment]
Bump!
