### ISSUE TITLE
Removing the first comment from vscode.CommentThread screws up Comments panel if the thread has more than one comment

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#73147]
- VSCode Version: latest insiders (1.34.0)
- OS Version: Windows 10

Steps to Reproduce:

1. Using new VSCode comment API, create a new `vscode.CommentThread` with two comments that have ids "1" and "2" and text "comment 1" and "comment 2" in file called `bar.js`. 
2. Open Comments panel and ensure that there is `bar.js -> comment 1 -> comment 2` tree.
3. Execute the following code to remove the first comment from the thread:
```typescript
vscodeThread.comments.splice(0, 1);

// Trigger vscode comment thread update
vscodeThread.comments = vscodeThread.comments;
```

*Expected:*
The comment thread is updated properly on the Comments panel and it has `bar.js -> comment 2' tree.

*Actual:*
The comment thread is not updated properly on the Comments panel and it has just `bar.js` without any sub items.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Tracked in https://github.com/microsoft/vscode/issues/77663 and fixed.
