### ISSUE TITLE
Additional debugger options in command pallet

### ISSUE THREAD

**Issue by jitcoder** [Microsoft/vscode#73148]
This is more of a nice to have feature. Wouldn't be the end of the world if it got rejected.

Scenario:
Mono repo with 10+ packages each with a debug config.

Sometimes when you're launching and debugging services multiple times it can be cumbersome going to the Debug section, choosing a launch configuration and hitting play.

I would be great if I could use the command pallet and type in `debug app1` or something along those lines.

essentially any way of running specific launch configuration without having to use a cursor.

**Comment by endormi** [comment]
Yeah, that would be a good feature.

**Comment by isidorn** [comment]
Quick Open > type "debug "

![debug](https://user-images.githubusercontent.com/1926584/57064417-89a30f00-6cc6-11e9-8211-56ac0a28f602.gif)

**Comment by jitcoder** [comment]
> Quick Open > type "debug "
> 
> ![debug](https://user-images.githubusercontent.com/1926584/57064417-89a30f00-6cc6-11e9-8211-56ac0a28f602.gif)

Thanks! you've directly improved my quality of life lol.

**Comment by isidorn** [comment]
Glad to help
