### ISSUE TITLE
VSCode always crashing when UWP game (Forza Horizon 4) is running.

### ISSUE THREAD

**Issue by mavanmanen** [microsoft/vscode#73142]
I am trying to create a Vue app to display telemetry data from the game, for this I have both the game and VSCode open, however, is VSCode is started first, the game will crash and vice versa. I have never had this happen in combination with any other game, but this is also the only UWP game I own and have played and I think this is related to that in some way.

I am not sure yet whether this issue is on just my machine and would be hard for others to repro as you'd need the game, I'd like help with steps to figure out what is exactly happening so I can report more useful data on the crash.

- VSCode Version: 1.33.1
- OS Version: W10 Enterprise 1809 17763.437

Steps to Reproduce:

1. Launch game
2. Launch VSCode
VSCode will instantly crash

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mavanmanen** [comment]
I will definitely try later.
I have also tried to disable the GPU accel to see if that helped but no change.

**Comment by bpasero** [comment]
Thanks
