### ISSUE TITLE
Ctrl+/ no longer properly comments out elements in HTML

### ISSUE THREAD

**Issue by dmdabbs** [Microsoft/vscode#73143]
Issue Type: <b>Bug</b>

I seeem to remember when positioning on an HTML element, say <script> in an HTML doc and pressing Ctrl+/ that it use to properly comment out the element by surrounding it with 
`<!--   -->`

Now it "dumbly" and incorrectly prefixes the line with 
//

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.4.12954

</details>

**Comment by RMacfarlane** [comment]
@dmdabbs Can you include the HTML you're seeing this with? I haven't been able to reproduce it on a test file, so there may be some specific syntax that is throwing us off

**Comment by dmdabbs** [comment]
In the file I have _any_ HTML tag is getting commented out this way.

**Comment by dmdabbs** [comment]
@RMacfarlane here is the URL to my file: http://mojotest.com/~davidd/gdpr/IAB_noimg.html

**Comment by RMacfarlane** [comment]
Thanks @dmdabbs!

Looks like syntax highlighting/commenting is breaking after this piece:

```html
<script>
	switch (location.hash) {
		case "#stub":
			!function () { var c = window, t = document, n = function () { if (!c.frames.__cmpLocator) if (t.body) { var a = t.body, e = t.createElement("iframe"); e.style.cssText = "display:none", e.name = "__cmpLocator", a.appendChild(e) } else setTimeout(n, 5) }; n(); var a = function (t) { var n = "string" == typeof t.data; try { var a = n ? JSON.parse(t.data) : t.data; if (a.__cmpCall) { var p = a.__cmpCall; c.__cmp(p.command, p.parameter, function (a, e) { var c = { __cmpReturn: { returnValue: a, success: e, callId: p.callId } }; t.source.postMessage(n ? JSON.stringify(c) : c, "*") }) } } catch (a) { } }; "function" != typeof __cmp && (c.__cmp = function () { var a = arguments; if (__cmp.a = __cmp.a || [], !a.length) return __cmp.a; "ping" === a[0] ? a[2]({ gdprAppliesGlobally: !1, cmpLoaded: !1 }, !0) : __cmp.a.push([].slice.apply(a)) }, __cmp.msgHandler = a, c.addEventListener("message", a, !1)) }();
			console.log("Using standard freestanding stub.");
			break;
		case "#stubdbg":
			!function () { var c = window, t = document, n = function () { if (!c.frames.__cmpLocator) if (t.body) { var a = t.body, e = t.createElement("iframe"); e.style.cssText = "display:none", e.name = "__cmpLocator", a.appendChild(e) } else setTimeout(n, 5) }; n(); var a = function (t) { var n = "string" == typeof t.data; try { var a = n ? JSON.parse(t.data) : t.data; if (a.__cmpCall) { var p = a.__cmpCall; c.__cmp(p.command, p.parameter, function (a, e) { var c = { __cmpReturn: { HandledByStub: true, returnValue: a, success: e, callId: p.callId } }; t.source.postMessage(n ? JSON.stringify(c) : c, "*") }) } } catch (a) { } }; "function" != typeof __cmp && (c.__cmp = function () { var a = arguments; if (__cmp.a = __cmp.a || [], !a.length) return __cmp.a; console.log('Stub queueing __cmp( "' + a[0] + '", ' + a[1] + ' )'); "ping" === a[0] ? a[2]({ gdprAppliesGlobally: !1, cmpLoaded: !1 }, !0) : __cmp.a.push([].slice.apply(a)) }, __cmp.msgHandler = a, c.addEventListener("message", a, !1)) }();
			console.log("Using 'debug' freestanding stub.");
			break;
		default:
			console.log("Using no freestanding stub.");
			break;
	}
</script>
```

**Comment by aeschli** [comment]
The JavaScript grammar seems to be confused by the `!` in front of the 'function'.
Created https://github.com/Microsoft/TypeScript-TmLanguage/issues/746

HTML highlighting (and smart editing functionality) then gets lost due to 
 https://github.com/Microsoft/vscode/issues/20488

Mark as dup of #20488
