### ISSUE TITLE
TextEditorDecorators should also be rendered in minimap

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#73140]
How about rendering text decorators in the minimap?  It looks like textmate colorization is applied, but decorators are not.

We'd like to colorize based on EDG parser results.  We're investigating doing colorization programmatically from our extension using text decorators.

**Comment by RMacfarlane** [comment]
Hey @Colengms, this looks similar to https://github.com/Microsoft/vscode/issues/20934. Please add any feedback to that issue. Thanks!

**Comment by Colengms** [comment]
I think this has been duped incorrectly.  I am not requesting a new API to allow for adding decorators to the minimap.  I am requested that text decorators added to the editor are also reflected propertly in the minimap (just as the textMate color are).  Perhaps this is even a bug, not a feature request.

**Comment by aaron-bond** [comment]
I think this has been closed incorrectly. I'm having the same issue with my Better Comments extension.
Is there some way to force a refresh of the minimap when drawing the decorators so that we could workaround the issue?
