### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TUSHJUX** [microsoft/vscode#73159]
Issue Type: <b>Feature Request</b>

I can't type anything on my visual code

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by eddiemonge** [comment]
Do you have a file open?

**Comment by RMacfarlane** [comment]
@TUSHJUX Can you provide some more details? Were you able to type in VS Code previously and it stopped working? What kind of files are you editing? What happens when you type?
