### ISSUE TITLE
Show in Explorer/Finder

### ISSUE THREAD

**Issue by drew-gross** [Microsoft/vscode#73152]
When I'm editing a file, sometimes I want to look at that file in Explorer/Finder (note that I'm talking about the built-in file browser for the OS, not the pane on the left that lists the files in the project, which VS Code also calls Explorer).

In Sublime this is done via right-click/context menu.

**Comment by isidorn** [comment]
F1 > reveal in explorer / finder
For the context menu you can write an extension to add it
You can also assign a keybinding to this action
