### ISSUE TITLE
New emmet 

### ISSUE THREAD

**Issue by StephenTANM** [microsoft/vscode#73155]
- VSCode Version:
- OS Version:
Ok so Im trying to use emmet and sometimes it auto expands and sometimes it doesn't. Even when I try to abbreviate actual components being imported. PS I did check my keyboard shortcuts etc...

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by octref** [comment]
Please give **reproducible steps**, like "Opening a html file with below content, and typing in line x character x..." etc
