### ISSUE TITLE
No ICodeLensCache for Monaco/Standalone

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#73150]
- VSCode Version: master

Ran into this issue while preparing Monaco release 

* `yarn run watch` in vscode repo
* open monaco-editor test page
* switch monaco-editor-core source to `src`
* `ICodeLensCache` not found error in Dev Console

`ICodeLensCache` is registered through https://github.com/Microsoft/vscode/blob/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/src/vs/editor/contrib/codelens/codeLensCache.ts#L120 which is only read by *workbench* https://github.com/Microsoft/vscode/blob/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/src/vs/workbench/browser/workbench.ts#L181

We can add the singleton services to standalone but a simple standalone service can also fix the problem

<img width="576" alt="image" src="https://user-images.githubusercontent.com/876920/57054778-8e76ad00-6c4b-11e9-9e8a-870cf95a9d34.png">

@jrieken let me know if you have time for a quick fix, if not I can push my change to branch `standalone/0.17.x` first to unblock publishing.

**Comment by rebornix** [comment]
FYI https://github.com/Microsoft/vscode/commit/bcafa5c971aec230cb4136802fb7bf966ae3e614 is also made to ensure `editor-distort` work at this moment. Unluckily our intermediate typescript files for tree shaking don't apply to `noImplicitAny` yet.

**Comment by jrieken** [comment]
@rebornix There is no need for `SimpleCodeLensCache`, the default implementation is good enough and just needs to be brought into the editor land.

**Comment by jrieken** [comment]
Oh wait, no storage service at it seems...

**Comment by jrieken** [comment]
@rebornix please review https://github.com/Microsoft/vscode/pull/73219

**Comment by RMacfarlane** [comment]
@rebornix can you clarify the steps for this? I'm not sure where the monaco-editor test page is

**Comment by sbatten** [comment]
@RMacfarlane I can take this one
