### ISSUE TITLE
Logout missing when command run from Terminal 

### ISSUE THREAD

**Issue by jbcpollak** [Microsoft/vscode#73151]
I'm getting this exact problem: https://github.com/Microsoft/vscode/issues/41600 except its happening when running a shell command from _terminal_, not in a debug output. Since its running in terminal, its not clear to me how to apply the workaround.

- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: Mac OS 10.14.2

**Comment by Tyriar** [comment]
The terminal doesn't know anything about stderr, it's just printing whatever the process is giving it. You probably have to tweak whatever you're running to get the output to display.

**Comment by jbcpollak** [comment]
@Tyriar the exact same process works fine in a terminal outside of VS Code.

**Comment by Tyriar** [comment]
@jbcpollak sounds fishy, I'll need some steps I can try reproduce it with in order to action this though.

**Comment by jbcpollak** [comment]
👍 I'm working on it!

**Comment by jbcpollak** [comment]
eh.... now I'm having trouble reproducing this, so lets call it closed and I'll re-open if it comes up
