### ISSUE TITLE
Incorrect linting as "declared but never used" of imported GraphQL fragments

### ISSUE THREAD

**Issue by JonJamesDesign** [Microsoft/vscode#73164]
- VSCode Version: 1.33.1
- OS Version: macOS Mojave 10.14.2

Steps to Reproduce (creating a Gatsby site):

### 1.  Create a valid GraphQL fragment:
`/src/graphql/fragments.js:`
```javascript
import { graphql } from 'gatsby'

/**
 * Blog Article
 */
export const prismicBlogArticleFields = graphql`
  fragment prismicBlogArticleFields on PRISMIC_Blog_article {
    article_type
    headline
    thumbnail
    image
    content
    _meta {
      uid
    }
  }
`

```
### 2.  Create a Gatsby template file:
`/src/templates/BlogArticle.jsx:`
```javascript
import React from 'react'
import { graphql, Link } from 'gatsby'
import { prismicBlogArticleFields } from '../../graphql/fragments'

const BlogArticle = ({ data: { prismic } }) => {
  const data = prismic.blog_article
  return (
    <>
      <hgroup>
        <h1>{data.headline[0].text}</h1>
        <h2>{data.article_type}</h2>
      </hgroup>

      <Link to="/blog">Back to Blog</Link>
    </>
  )
}

export default BlogArticle

export const query = graphql`
  query PrismicBlogArticleByDocumentID($uid: String!) {
    prismic {
      blog_article(uid: $uid, lang: "en-gb") {
        ...prismicBlogArticleFields
      }
    }
  }
`

BlogArticle.query = query
```

---

**Expected result:**

The imported `prismicBlogArticleFields` should not be marked as, "declared but never used" because it _is_ used in the exported graphql query below.

**Actual result:**

The imported `prismicBlogArticleFields` is marked as, "declared but never used", despite the fact it is used successfully in the exported graphql query below.

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
There's no general way to understand that `prismicBlogArticleFields` in a string is a reference to a variable in the code but a TypeScript language service plugin could possible add this for graphql
