### ISSUE TITLE
Integrated terminal doesn't respect .nvmrc file

### ISSUE THREAD

**Issue by HintikkaKimmo** [Microsoft/vscode#73166]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Build any javascript project using with mac with NVM installed. Use node version other than one set with default alias.
2. When VSCode is started integrated terminal always starts the default version not respecting .nvmrc file in the project. 

There is quite a bit of Stackoverflow discussion on this topic as well. 

https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm

https://stackoverflow.com/questions/54569606/vscode-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-lau

https://stackoverflow.com/questions/38671534/cannot-set-node-module-path-for-visual-studio-code

Expected behavior based on other editors I've used would be to automatically use whatever version is specified in the .nvmrc file.

I can fix the issues by running nvm use XXXX, but with next restart nvm version is incorrect again. To mitigate this is there a project level node part I can setup?  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
What OS and VS Code version are you on?

**Comment by HintikkaKimmo** [comment]
> What OS and VS Code version are you on?

Hi, @Tyriar I'm using Hight Sierra 10.13.6 and VSCode 1.33.1.

This does happen extensions turned off as well, but I realized there I have one less of a standard piece of configuration in my side. My terminal of choice. 

"terminal.external.osxExec": "Hyper.app",

I just also double check that I have nothing funny in my .bash_profile or .bashrc file which would seem unlikely as nvm works fine outside of VSCode.

**Comment by HintikkaKimmo** [comment]
I thought that this would mean error was due to Hyper.app terminal but changing my terminal settings in settings.json to 

```
    "terminal.integrated.shell.osx":"/bin/bash",
    "terminal.explorerKind": "integrated",
```

Seem to make no difference.

**Comment by Tyriar** [comment]
@HintikkaKimmo if that extension fixes the problem that means you have a configuration issue as all it seems to do is run `nvm use`? You should looking into tweaking `terminal.integrated.shellArgs.osx` to either `[]` or `[ "-l" ]` and also looking into how nvm is setup in your .bashrc or .bash_profile files.
