### ISSUE TITLE
Unable to create new file

### ISSUE THREAD

**Issue by themitigater** [Microsoft/vscode#73167]
Issue Type: <b>Bug</b>

- Open a folder
- Use the create file icon on left navbar.
- The view refreshes continuously.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_32776|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|9.6.3
vsc-material-theme|Equ|2.8.2
json-tools|eri|1.0.2
gc-excelviewer|Gra|2.1.32
ecdc|mit|1.0.5
python|ms-|2019.4.12954
Go|ms-|0.10.2
vsliveshare|ms-|1.0.91
vscode-docker|Pet|0.6.1
material-icon-theme|PKi|3.7.0
vscode-icons|vsc|8.6.0

(2 theme extensions excluded)

</details>

**Comment by mittalyashu** [comment]
Does it show the file input to type the file name?

**Comment by themitigater** [comment]
Only for the first time, once I focus on the input field it vanishes and then the above error occurs.

**Comment by gjsjohnmurray** [comment]
Have you followed the recommended diagnostic procedure of restarting VSCode with all extensions disabled to see if you can still recreate the problem?

**Comment by themitigater** [comment]
> Have you followed the recommended diagnostic procedure of restarting VSCode with all extensions disabled to see if you can still recreate the problem?

Thanks, turns out is an issue with one of the plugins that I'm using.
