### ISSUE TITLE
Terminal display bug

### ISSUE THREAD

**Issue by KInGATiLLa** [Microsoft/vscode#73163]
- VSCode Version: 1.33.1
- OS Version: Windows_NT x64, 1809update, build10.0.17763
- Node(local): 10.15.3
I'm using Git bash in my VSCode terminal.
I don't know why this issue appears.

![iss](https://user-images.githubusercontent.com/17881842/57066705-7e200a00-6cff-11e9-9ce0-3d2bb28f452c.PNG)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
