### ISSUE TITLE
Debug console clear command focuses the debug console

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#73169]
Issue Type: <b>Bug</b>

When executing the "Debug: Clear Console" command, the debug console gains focus.

This is inconsistent with the behaviour of the Output and Terminal panels, as running their clear commands does not focus those respective panels.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by isidorn** [comment]
Let's leave this open as a feature request.
I actually changed it on purpose as other users complained that they would like clear to move focus to the debug console.
I am fine with either.

fyi @Tyriar to see what he thinks is the correct behavior

**Comment by SpectralKH** [comment]
@isdorn Is there a reason people complained specifically about the debug console, and not the terminal and output panels?

**Comment by isidorn** [comment]
No. They just wanted it for debug console. You can try to find the issue in our old issues if you would like to find more details.

**Comment by SpectralKH** [comment]
@isidorn Weird, would assume that people want behaviour consistent.

**Comment by Tyriar** [comment]
@isidorn so the `Terminal: Clear` command does not focus the terminal, much like the majority of terminal commands. Is the main purpose of the debug console one for use in the clear button at the top-right of the debug console panel? If so it makes sense for that to re-focus just like all the button in the terminal panel.

Maybe there should be 2 commands/actions, one in the command palette that does not refocus (so you can use it in the editor without focusing the debug console), and one for the debug console button that does focus (as it's preferable to focusing the button)? Looking at the issue that caused the change could help decide what to do?

**Comment by SpectralKH** [comment]
@Tyriar Not sure if that's really so important. There could very well be a clear button in the terminal panel, I don't think that should affect the command's behaviour.

It would actually make sense to not want to focus the debug console as it will often output more information without you having to type anything in there.

To me, the debug console would actually be even more useful to not focus than the terminal because I rarely type commands in the debug console - I would for instance just want to clear the debug console, save a file and see the logs from Flutter's hot reload.

**Comment by isidorn** [comment]
@Tyriar what you are saying makes sense, it should focus when executed from the debug console title bar and should not focus when from the command palette. However we are now reusing code and we do not disgutinish these two cases.

**Comment by probablykasper** [comment]
> However we are now reusing code and we do not disgutinish these two cases.

@isidorn Sorry for replying so much later, but what did you mean by this?

**Comment by isidorn** [comment]
I was replying to Daniel.

**Comment by probablykasper** [comment]
Oh sorry, my bad
