### ISSUE TITLE
Typescript error points to non-existant line

### ISSUE THREAD

**Issue by FBalazsBme** [microsoft/vscode#73168]
- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:
Sorry, currently I do not have time for that.
But I basically have the same situation as described in another issue, which was closed without a real solution (I even deleted all those lines where the error could be in the file, so the error message point to a non-existent line, I als logged out and logged in to user, and created a new folder, and reimported files, but error still persists!!): https://github.com/Microsoft/vscode/issues/55257
Please investigate the issue, because it is very annoying.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate, such as steps to reproduce this
