### ISSUE TITLE
White bar on title after maximize it two times

### ISSUE THREAD

**Issue by torra87** [Microsoft/vscode#73176]
Issue Type: <b>Bug</b>

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

1. Open Visual Studio Code.
2. With the window not maximized, click on the Maximize button.
3. Visual Studio Code now is maximized and title bar is OK.
4. Click on Maximize to make the window small and then maximize it again.
5. Now the title bar should have a thin white bar on top.

The same happens dragging the window to maximize it.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
EditorConfig|Edi|0.13.0
vscode-typescript-tslint-plugin|ms-|1.0.0

</details>

**Comment by sbatten** [comment]
@torra87 this issue is resolved in a newer version of Windows 10 and not VS Code. For more info, see https://github.com/Microsoft/vscode/issues/52265
