### ISSUE TITLE
User author instead of user

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#73170]
The comments API uses `userInfo` and `userIconPath` and IMO the better name would be `autherXYZ` because it's the author of the comments and (optionally) the user of the system that hosts/stores comments

**Comment by jrieken** [comment]
After talking to @joaomoreno there is also a desire to have `CommentAuthorInfo` which encapsulates this and has potential for future growth, e.g name and nickName

**Comment by rebornix** [comment]
The author prefix change is https://github.com/Microsoft/vscode/pull/73137 but since not only one thinks we may want to enrich `author` information, I'll make it an object.
