### ISSUE TITLE
Move inputBox from CommentController to CommentThread

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#73172]
https://github.com/Microsoft/vscode/blob/816a31517667f1ed8b0098ef6e20273614c31d1b/src/vs/vscode.d.ts#L9157-L9161

cc @jrieken

**Comment by jrieken** [comment]
That appeal because that would simplify the inbox again, e.g resource and range are given by the containing thread, it might enable us have the input box always set (never undefined) and it simplifies that handling generally, e.g otherwise you cannot do async-operations between using the input box and working with a thread (synth input box "moves" from thread to thread)

**Comment by rebornix** [comment]
It makes sense for manipulating existing `CommentThread` but it won't work when creating new comment threads. When users click + button, we create Comment Widget from the `CommentThreadTemplate`, in which case, there is no `CommentThread` object.

That means, if we want to make `inputBox` a property of `CommentThread`, we need to

* When users attempt to create a new comment thread, we create a real `CommentThread` object, which contains `inputBox`
* Then when users run commands to create/reply comments, extensions need a way to access the newly created comment thread, as it's created by VS Code and extensions have no reference to it. A proper way is adding `CommentController.activeCommentThread`.

For short, if `inputBox` is not singleton, we need to expose comment thread created from template. Right now I'm in favor of current design.

**Comment by jrieken** [comment]
> https://github.com/Microsoft/vscode-pull-request-github/blob/8bc541c8e43a63f66db8218e8c3c54def8715541/src/view/treeNodes/pullRequestNode.ts#L651-L659

I think [these lines](https://github.com/Microsoft/vscode-pull-request-github/blob/8bc541c8e43a63f66db8218e8c3c54def8715541/src/view/treeNodes/pullRequestNode.ts#L651-L659) show the issue that the current singleton approach has:

<img width="1359" alt="Screenshot 2019-05-06 at 09 53 33" src="https://user-images.githubusercontent.com/1794099/57215324-c899d300-6fec-11e9-8560-b348d484198c.png">

There is no way to know for which thread the widget currently shows and there is no way to change for what thread the widget is showing. In above sample during the async call the user might select another comment (and thereby changing the "scope" of the widget) and then the code changes the wrong widget. That's a real problem and (strictly speaking) the API doesn't allow to write correct code...

> It makes sense for manipulating existing CommentThread but it won't work when creating new comment threads.

Yeah, I don't have a good idea yet. We could differentiate between the input widget of existing threads and that of to-be-created threads. We could allow to denote a (live) comments thread objects as the template thread object. That would allow for a scoped input widget but has the a similar problem when multiple comments are started at the same time. 

Another idea/wish is that the use of (statically) contributed commands in package.json is enough to replace the comments template, e.g there could be a context key that represents a template-thread (`commentThread == template`)

```json
"comments/commentsThread": [
        {
          "command": "myCreateCommand",
          "when": "commentController == myComments && commentThread == template",
        }
]
```

With that we could re-consider the the factory approach, e.g have

```ts
interface CommentsController {
  // callback which enables a user-gesture to create new comments threads
  // resulting comment thread must be for the given document and range
  handleUserRequestForCommentThread?: (doc: TextDocument, range: Range, input: string | MarkdownString): CommentThread;
}
```

or a richer object with more control

```ts

interface CommentThreadFactory {
  // static/shared default value when creating a thread
  defaultLabel: string;

  // control declared commands
  contextValue: string;

  // call 'createCommentThread' inside createCommentThread function...
  // params: document, range, and text typed till now...
  createCommentThread(doc: TextDocument, range: Range, input: string): CommentThread;
}
```
