### ISSUE TITLE
syntax highlighting breaks w/ PHP in style tags

### ISSUE THREAD

**Issue by jeffreysbrother** [Microsoft/vscode#73179]
Issue Type: <b>Bug</b>

If a PHP file contains markup, and we attempt to conditionally define styles within the style tags, syntax highlighting will break.

![Screen Shot 2019-05-02 at 10 27 27 AM](https://user-images.githubusercontent.com/11843681/57094274-046b2a80-6cc5-11e9-980e-cd2ba7c2ff83.png)

This happens with both `<?php ?>` and `<? ?>`, and appears to be similar to [#65649](https://github.com/Microsoft/vscode/issues/65649).

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|16.00GB (1.79GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
project-manager|ale|10.5.1
beautify|Hoo|1.4.11
vscode-duplicate|mrm|1.2.1
Go|ms-|0.10.2
subtle-brackets|raf|3.0.0

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/33519
