### ISSUE TITLE
Use menus and statically contributed commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#73174]
Today, the comments API uses many explicit commands like `acceptInputCommand`, `deleteCommand`, or `additionalCommands`. Instead, menus should be used, I see two a title and a 'bottom' menu...

<img width="709" alt="Screenshot 2019-05-02 at 15 32 14" src="https://user-images.githubusercontent.com/1794099/57078958-a0aa2700-6cef-11e9-9331-bd87706075b6.png">

**Comment by rebornix** [comment]
Implemented in master.
