### ISSUE TITLE
An option to hide the side bar when it's toggled

### ISSUE THREAD

**Issue by brashaw** [Microsoft/vscode#7317]
The **Toggle Sidebar** action only *minimizes* the sidebar.  It would be really nice to get an option to completely hide the sidebar when it's toggled.

Sometimes I use it but most of the time I do not, and it just takes up space.

A user setting named, for example, `hideSidebarWhenToggled` would be perfect.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1105
