### ISSUE TITLE
powershell core 6 doesn't show the terminal by default

### ISSUE THREAD

**Issue by mhamri** [Microsoft/vscode#73181]
Issue Type: <b>Bug</b>

per subject, if i put the terminal address to the pwsh.exe and i open the terminal i see empty window. if i click there and start to type i can type, if i preress enter then i get prompt 
by default it should show the prompt when i open the terminal

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
rainbow-brackets|2gu|0.0.6
angular-extension-pack|ale|1.0.0
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.11
angulardoc-vscode|Ang|6.1.3
vscode-browser-preview|auc|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
angular-schematics|cyr|1.23.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
json2ts|Gre|0.0.6
angular2-switcher|inf|0.2.0
path-autocomplete|ion|1.13.3
angular-essentials|joh|0.6.1
Angular2|joh|7.1.4
vscode-peacock|joh|2.1.1
angular-extension-pack|loi|0.7.1
ts-extension-pack|loi|0.2.0
Angular2Tests|Mar|0.7.3
Angular-BeastCode|Mik|8.0.6
powershell|ms-|1.12.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.125
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
ng-fortytwo-vscode-extension|NG-|0.0.9
angular-console|nrw|7.4.19
material-icon-theme|PKi|3.7.0
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
simontest|Sim|1.3.0
autoimport|ste|1.5.3
move-ts|str|1.11.3
Angular2|UVB|0.4.1
vscodeintellicode|Vis|1.1.5
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
