### ISSUE TITLE
terminate unresponsive built-in shell

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#7318]
- VSCode Version:1.2.0
- OS Version:ubuntu 16.4
cannot terminate running shell in case shell becomes unresponsive

in case ssh connection dropt or simply shell stops responding there is no way to terminate running shell and start new one

**Comment by Tyriar** [comment]
Going to close this in favor of https://github.com/Microsoft/vscode/issues/6458 as the UX will change quite a bit with that.
