### ISSUE TITLE
${env:USER} or ${env:USERNAME} is not available.

### ISSUE THREAD

**Issue by ryanpcmcquen** [Microsoft/vscode#73184]
- VSCode Version: 1.33.1
- OS Version: Mac OS 10.14.x

Steps to Reproduce:

1. Use `${env:USER}` inside of `settings.json`, notice that it does not work.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

According to the documentation here, this should work:
https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

**Comment by RMacfarlane** [comment]
Hey @ryanpcmcquen , environment variables are currently only available in `tasks.json` and `launch.json`. (This is at the top of the documentation page.) There's an open feature request to add support for `settings.json` (https://github.com/Microsoft/vscode/issues/2809), so I will close this as a duplicate. Thanks!
