### ISSUE TITLE
Attach by process for node seems broken when specifying script argument

### ISSUE THREAD

**Issue by scolestock** [microsoft/vscode#73189]
Issue Type: <b>Bug</b>
Repro:
1) Add a "Attach by process ID" launch configuration
2) From terminal window, do "node --inspect"
3) Use the attach by process ID config - you'll see your process appear in the list in vs code - nice!
4) From terminal window, do , "node --inspect someScript.js"
See that it really is listening on a debug port...
5) Try to attach.  You can't attach - it doesn't show in the list of node processes now.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
sqlformatter|bre|0.0.7
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.18.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
vscode-dash|dee|2.1.0
githistory|don|0.4.6
xml|Dot|2.4.0
EditorConfig|Edi|0.13.0
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
dotnet-test-explorer|for|0.6.6
todo-tree|Gru|0.0.130
ReplaceWithNewline|jma|0.0.1
expand-region|let|0.1.2
dotenv|mik|1.0.1
csharp|ms-|1.19.0
debugger-for-chrome|msj|4.11.3
vscode-paste-image|mus|1.0.4
vsnotes|pat|0.7.0
vscode-yaml|red|0.4.0
code-settings-sync|Sha|3.2.9
code-spell-checker|str|1.7.4
vscode-react-native|vsm|0.9.2
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by weinand** [comment]
I cannot reproduce this problem:

![2019-10-16_12-38-48 (1)](https://user-images.githubusercontent.com/1898161/66912014-02e2b400-f012-11e9-90b9-945beae2ff9a.gif)
