### ISSUE TITLE
Allow open settings complex command to target extension settings

### ISSUE THREAD

**Issue by bnookala** [microsoft/vscode#73190]
There exists an (undocumented) internal complex command that can open vscode settings:

```ts
vscode.commands.executeCommand("workbench.action.openSettings2")
```

Which I _think_ eventually makes its way to here https://github.com/Microsoft/vscode/blob/059a3e1642f74c0f97589e4739a1a303fe8cdd23/src/vs/workbench/services/preferences/browser/preferencesService.ts#L185

I see in the codebase that it's possible to pass a query directly to this function, which I imagine filters the settings shown. It would be useful for an extension to be able to do this as well. For example: a vscode error message could direct a user to the extension's settings immediately via a button click.

This feature request is two parts:
- Document this complex command in the docs somewhere :)
- Allow a user to pass a string/id to filter the shown settings to the extension's settings.

**Comment by roblourens** [comment]
Now `workbench.action.openSettings` will take a query. However, these are not well documented and that is an issue with commands for extensions in general :(
