### ISSUE TITLE
Cannot Stop Tests

### ISSUE THREAD

**Issue by matsapo** [Microsoft/vscode#73199]
Issue Type: <b>Bug</b>

- I'm using PyTest and have it enabled in the settings
- I'm using Python 3.7.2 64-bit
- Windows 10 64-bit
- 16 GB Ram

1. Open VSCode with my project workspace
2. Click on Test panel
3. Click on the test I'd like to run
4. Click Play button to run test

Note: This test uses selenium and the locators in the script need to be updated.  The test output actually shows that an error occured because the element is not interactable.

5. Click Stop button located in the top of the test panel 

Expected Result: The test immediately stops executing with an error
Actual Result: The test appears to be hung and never reaches a time-out

Note: Clicking on the "Running Tests" button at the bottom of the UI has no effect either despite saying "(Click to stop)."  When I click it, nothing happens and it looks like if I hold down the mouse button the button clicks repeatedly and does so very quickly.

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|1.4.2
vsc-material-theme|Equ|2.8.2
vsc-material-theme-icons|equ|0.12.0
file-icons|fil|1.0.17
vscode-icon-theme|jtl|1.6.5
mssql|ms-|1.6.0
python|ms-|2019.4.12954
material-icon-theme|PKi|3.7.0
vscodeintellicode|Vis|1.1.5

(8 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
VS Code doens't have a test panel, it must be an extension

**Comment by matsapo** [comment]
Thanks, I think this actually belongs in the Python extension repository.
