### ISSUE TITLE
Problems Window - Errors State "Unable to open: File not found"

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#73195]
Many threads that are closed with this issue or say duplicate of, state that this issue has been fixed. It's happening... No extensions. Basic .Net Core API.

This happens every now and then but often enough. I'll be shown errors and clicking on some will state that the file does not exist. There is a duplicate set of the same errors from the same file below. Both show a slightly different path. Have no idea what's happening here.

![image](https://user-images.githubusercontent.com/16159685/57109245-f3d9a500-6d02-11e9-8291-51402d2e6cde.png)

- VSCode Version: 1.33.1
- OS Version: 1803

Steps to Reproduce:

1. Very hard to reproduce. Seems random. Been running the same .Net Core app all day. All of a sudden this happened.
2. Doesn't seem like it has steps to reproduce.
3. Occurs with all extensions disabled.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Hey @DanJ210, the problems in the panel are populated by the C# extension, it's responsible for creating them with the correct file URI. Can you please reopen this issue on the extension here: https://github.com/OmniSharp/omnisharp-vscode/issues? I'm not able to transfer the issue. Thanks!

**Comment by DanJ210** [comment]
Sure, thanks @RMacfarlane
