### ISSUE TITLE
Closure Compiler Generated Source Maps Don't Let Preview Values

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#73197]
Issue Type: <b>Bug</b>

The source maps works itself, but I can't hover over variables to get their names. It's not the case in Chrome. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.0.0

## map.js
This is the source code.
```js
const get = async () => {
  const { hash, port  } = process.env
  return { hash, port }
}
(async () => {
  const res = await get()
  console.log(res)
})()
```
## map1.js
This is the generated source code using Google Closure Compiler.
```js
'use strict';
const c = async() => {
  const {hash:a, port:b} = process.env;
  return {hash:a, port:b};
};
(async() => {
  const a = await c();
  console.log(a);
})();


# sourceMappingURL=map1.js.map
```
## map1.js.map
This is the map produced by the compiler.
```json
{
"version":3,
"file":"t/map-vs/map1.js",
"lineCount":10,
"mappings":"A;AAAA,MAAMA,IAAMA,KAAM,EAANA,IAAY;AACtB,QAAM,CAAE,KAAAC,CAAF,EAAQ,KAAAC,CAAR,CAAA,GAAkBC,OAAAC,IAAxB;AACA,SAAO,CAAEH,KAAAA,CAAF,EAAQC,KAAAA,CAAR,CAAP;AAFsB,CAAxB;AAIC,MAAM,EAAN,IAAY;AACX,QAAMG,IAAM,MAAML,CAAA,EAAlB;AACAM,SAAAC,IAAA,CAAYF,CAAZ,CAAA;AAFW,CAAZ,CAAD,EAAA;;",
"sources":["t/map-vs/map.js"],
"sourcesContent":["const get = async () => {\n  const { hash, port  } = process.env\n  return { hash, port }\n}\n(async () => {\n  const res = await get()\n  console.log(res)\n})()"],
"names":["get","hash","port","process","env","res","console","log"]
}
```

It's great that the source map works, and I know I can't hover over { hash, port } because of return optimisations, but I should be able to preview `res`. And it's the simplest example, there's the same problem in more complex code. 

![IMG_0282](https://user-images.githubusercontent.com/21156791/57111610-7aaf7180-6d45-11e9-87c2-319e8ca506f5.JPG)

[this is the visualisation](http://sokra.github.io/source-map-visualization/#base64,J3VzZSBzdHJpY3QnOwpjb25zdCBjID0gYXN5bmMoKSA9PiB7CiAgY29uc3Qge2hhc2g6YSwgcG9ydDpifSA9IHByb2Nlc3MuZW52OwogIHJldHVybiB7aGFzaDphLCBwb3J0OmJ9Owp9OwooYXN5bmMoKSA9PiB7CiAgY29uc3QgYSA9IGF3YWl0IGMoKTsKICBjb25zb2xlLmxvZyhhKTsKfSkoKTsKCgovLyMgc291cmNlTWFwcGluZ1VSTD1tYXAxLmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidC9tYXAtdnMvbWFwMS5qcyIsImxpbmVDb3VudCI6MTAsIm1hcHBpbmdzIjoiQTtBQUFBLE1BQU1BLElBQU1BLEtBQU0sRUFBTkEsSUFBWTtBQUN0QixRQUFNLENBQUUsS0FBQUMsQ0FBRixFQUFRLEtBQUFDLENBQVIsQ0FBQSxHQUFrQkMsT0FBQUMsSUFBeEI7QUFDQSxTQUFPLENBQUVILEtBQUFBLENBQUYsRUFBUUMsS0FBQUEsQ0FBUixDQUFQO0FBRnNCLENBQXhCO0FBSUMsTUFBTSxFQUFOLElBQVk7QUFDWCxRQUFNRyxJQUFNLE1BQU1MLENBQUEsRUFBbEI7QUFDQU0sU0FBQUMsSUFBQSxDQUFZRixDQUFaLENBQUE7QUFGVyxDQUFaLENBQUQsRUFBQTs7Iiwic291cmNlcyI6WyJ0L21hcC12cy9tYXAuanMiXSwic291cmNlc0NvbnRlbnQiOlsiY29uc3QgZ2V0ID0gYXN5bmMgKCkgPT4ge1xuICBjb25zdCB7IGhhc2gsIHBvcnQgIH0gPSBwcm9jZXNzLmVudlxuICByZXR1cm4geyBoYXNoLCBwb3J0IH1cbn1cbihhc3luYyAoKSA9PiB7XG4gIGNvbnN0IHJlcyA9IGF3YWl0IGdldCgpXG4gIGNvbnNvbGUubG9nKHJlcylcbn0pKCkiXSwibmFtZXMiOlsiZ2V0IiwiaGFzaCIsInBvcnQiLCJwcm9jZXNzIiwiZW52IiwicmVzIiwiY29uc29sZSIsImxvZyJdfQ==,Y29uc3QgZ2V0ID0gYXN5bmMgKCkgPT4gewogIGNvbnN0IHsgaGFzaCwgcG9ydCAgfSA9IHByb2Nlc3MuZW52CiAgcmV0dXJuIHsgaGFzaCwgcG9ydCB9Cn0KKGFzeW5jICgpID0+IHsKICBjb25zdCByZXMgPSBhd2FpdCBnZXQoKQogIGNvbnNvbGUubG9nKHJlcykKfSkoKQ==)

**Comment by zavr-1** [comment]
This works in Chrome btw https://contexttesting.github.io/mask/ 
![Screenshot 2019-05-03 at 01 56 40](https://user-images.githubusercontent.com/21156791/57111952-b72f9d00-6d46-11e9-989b-3e09dc4d8e3a.png)

**Comment by isidorn** [comment]
@zavr-1  When you are stopped at that point do you see a variable `res` in the variables view?

**Comment by zavr-1** [comment]
nope I see `a` which is closure's variable. you can copy the scripts i've attached you'll be able to reproduce.

**Comment by isidorn** [comment]
Well that is the issue, our debug hover has that limitation that it only looks in the variables view to find variables.
And node debug is returning the closure variable name. Not sure if something can be done here @roblourens

**Comment by roblourens** [comment]
This looks like https://github.com/Microsoft/vscode/issues/12066

**Comment by zavr-1** [comment]
@roblourens @isidorn thanks for looking into it. Didn't know VSCode doesn't support this feature.
