### ISSUE TITLE
Find in Files not working anymore

### ISSUE THREAD

**Issue by thomiel** [microsoft/vscode#73198]
Issue Type: <b>Bug</b>

When using Find in Files I get much too less hits. This is really bad.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2819)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (5.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0
vscode-language-pack-de|MS-|1.33.2
python|ms-|2019.4.11987
vscode-docker|Pet|0.6.1
preview-vscode|sea|2.0.3
markdown-preview-enhanced|shd|0.3.13
vscodeintellicode|Vis|1.1.5
markdown-pdf|yza|1.2.0

</details>

**Comment by RMacfarlane** [comment]
Hey @thomiel, thanks for reporting this issue. Can you include some more details, like information about a specific search that failed? What did you search, and what results were missing? Are any of the search options turned on?
![Screen Shot 2019-05-02 at 4 21 36 PM](https://user-images.githubusercontent.com/3672607/57112832-950e2e80-6cf6-11e9-85d9-69b99fb80e63.png)

**Comment by thomiel** [comment]
none of the two options were active and no files to include/exclude. the search term was 'hidden' and it occured in multiple files in this pyhton project. only one csv file containing it was shown in search results.

**Comment by gjsjohnmurray** [comment]
@thomiel the blue border around the button in the bottom right corner of your screenshot indicates the "Use Exclude Settings and Ignore Files" feature is active for your search. If you deactivate that do you still not get the matches you expect?

**Comment by thomiel** [comment]
If I click on the gearwheel so there is no blue border anymore, find in files seems to be working as before. But this should be of no relevance, if there are no files to exclude in the first place, if you ask me. What's the function of the gearwheel if there is nothing to exclude? Why does it harm the search function?

**Comment by thomiel** [comment]
@gjsjohnmurray I clearly miss the function of the gearwheel button. If I want to disable the file exclusion, I would simply delete the text. Wouldn't an 'empty field' button be a better choice here? If I click a gearwheel button, I usually expect an options window to open.

**Comment by RMacfarlane** [comment]
@thomiel The gearwheel indicates whether or not the `files.exclude` setting is being used. So you can enter a temporary exclude in the text box, and have a persistent set of files that you don't want to search. There's a default value for `files.exclude` that includes things like the .git folder.

Can you check the value of your `files.exclude` setting?

**Comment by thomiel** [comment]
These are the excluded files:

**/.git
**/.svn
**/.hg
**/CVS
**/.DS_Store
**/*.pyc

*.pyc files, for example, don't show up no matter if I activate the exclude button. 

These are the files that show up if I have the exclude button activated while searching 'function':

[Screenshot 1](https://seafile.c3s.cc/f/3ce83ca0126a4ed48dfc/)

Here while deactivated:

[Screenshot 2](https://seafile.c3s.cc/f/158947ab41c642549a75/)

To me, there is no obvious regularity in what files vscode finds.

**Comment by roblourens** [comment]
That button controls whether the .gitignore file, and the files.exclude and search.exclude settings are used, so those extra files must be covered by one of those three things.

**Comment by thomiel** [comment]
I have a checkmark at Search: Use Ignore Files. If I uncheck, search will work as expected. There is no .ignore file. The .gitignore looks like this:

    # Swap files
    *~

    # Byte-compiled / optimized / DLL files
    __pycache__/
    *.py[cod]

    # C extensions
    *.so

    # Distribution / packaging
    .Python
    env/
    build/
    develop-eggs/
    dist/
    downloads/
    eggs/
    lib/
    lib64/
    parts/
    sdist/
    var/
    *.egg-info/
    .installed.cfg
    *.egg

    # PyInstaller
    #  Usually these files are written by a python script from a template
    #  before PyInstaller builds the exe, so as to inject date/other infos into it.
    *.manifest
    *.spec

    # Installer logs
    pip-log.txt
    pip-delete-this-directory.txt

    # Unit test / coverage reports
    htmlcov/
    .tox/
    .coverage
    .cache
    nosetests.xml
    coverage.xml
    ado/cover

    # Translations
    #*.mo   unless we integrate the translation tools into the build process, 
    #*.pot  we need to version these files

    # Django stuff:
    *.log

    # Sphinx documentation
    docs/_build/

    # PyBuilder
    target/

    # Ado
    ado/etc/*.sqlite
    ado/src
    ado/ref
    ado/tmp
    postgresql-data

    # pyramid_mailer.debug
    ado/mail

    # Configuration files for docker container
    /*.env
    /ado/etc/trytonpassfile

    # VS Code remnants
    /.vscode/*

So it will allow *.py files in my Python project. If I search for 'def' (Python function definitions), code returns 81 results in 16 files. It seems to only delve two folder levels deep but occasionally includes files currently opened. If I switch off exclusion, I get >10,000 matches.

**Comment by roblourens** [comment]
Your screenshot shows files in `ado/cover` being excluded. Sure enough, your .gitignore includes `ado/cover`. That's all I can see from the info you've given. I don't see any evidence that vscode is doing the wrong thing.

**Comment by thomiel** [comment]
This is the main repo, you can consult for the folder structure:

https://github.com/C3S/c3s.ado.repertoire

below ado/src, submodules will be cloned like those two:

https://github.com/C3S/collecting_society.portal
https://github.com/C3S/collecting_society.portal.repertoire

Just tell me what you need as evidence.

**Comment by roblourens** [comment]
So I clone this repo and search "function" and get results that seem correct... just tell me exactly what you search for, what results are you missing that should not be missing? I don't have a `ado/cover` folder so there is probably some setup I am missing. I just need you to tell me exactly step by step what the issue is.

**Comment by thomiel** [comment]
Forget about ado/covers, focus on ado/src/*/*...

After you have cloned the repo, run the ./update script to clone the submodules (Python 2.7 and a 64 bit Linux could help).

Open folder c3s.ado.repertoire in VS Code, activate the exclude button, and search for 'def'. If you  can reproduce the problem, it should show 81. Were there no problems, it should return >10,000 occurances, because .py files are not excluded anywhere.

**Comment by roblourens** [comment]
`ado/src` is also in your .gitignore.

**Comment by thomiel** [comment]
oops, my bad.

it would be good to have some stats about how many folders/files were excluded due to a certain exclusion mechanism.

**Comment by thomiel** [comment]
ps: thanks for your patience.
