### ISSUE TITLE
HTML outline bug: <body> comes before <head>

### ISSUE THREAD

**Issue by jluisgarcia** [Microsoft/vscode#73192]
- VSCode Version: 1.33.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Just open a HTML file
2. Click on Outline and see for yourself from screenshot.  `<body>` and `<head>` tags are upside down.

![s1](https://user-images.githubusercontent.com/24752182/57105981-7fb3f700-6d2c-11e9-8c1a-672eae29aa6f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@jluisgarcia you need to investigate the "More actions" menu on the Outline panel:
![image](https://user-images.githubusercontent.com/6726799/57108603-3c0cbd80-6d2b-11e9-8283-642437da7499.png)

Setting "Sort By: Position" should do the trick.

**Comment by jluisgarcia** [comment]
That's right.
Thanks.
