### ISSUE TITLE
[TypeScript] Add support emmet for typescript react (tsx) files

### ISSUE THREAD

**Issue by moostad** [Microsoft/vscode#732]
Please add emmet features for typescript react

**Comment by egamma** [comment]
Good idea. Need to explore whether we can just take over the tab key in .tsx files as we do in the other file types.

See also: http://wesbos.com/emmet-react-jsx-sublime/

**Comment by deathmood** [comment]
+1 I would like to have emmet also for JavaScript React

**Comment by egamma** [comment]
It is now enabled in both jsx and tsx files and for both the jsx filter is used that converts class -> className

**Comment by mikesigs** [comment]
Apparently the new wisdom is to not use .jsx file extensions, but rather to use .js instead. Can you enable this same functionality for .js extensions too please?

**Comment by stevematdavies** [comment]
TSX (Typescript react) in VSCODE now complains of double quotes in html, it seems this support is only half way there
