### ISSUE TITLE
Unfold line handle

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#73208]
The unfold handle hit-box from right edge of relevant "..." button to end of the folded line are much less ergonomic than if it would be a normal space that would place cursor to end of the line without the unfolding.

**Comment by RMacfarlane** [comment]
@Ilias48rus Can you add a screenshot to help illustrate what you mean?

**Comment by Ilias48rus** [comment]
@RMacfarlane ![viZmisZvisualStudioCode](https://user-images.githubusercontent.com/13949704/57173148-bf193b00-6e33-11e9-8f60-68c53ce72778.gif)

**Comment by aeschli** [comment]
@Ilias48rus  Is this a dup of https://github.com/Microsoft/vscode/issues/53886 ?

**Comment by Ilias48rus** [comment]
@aeschli yes, sor

**Comment by aeschli** [comment]
np, just wanted to be sure. Marking as dup of #53886
