### ISSUE TITLE
VSC crashes when files are saved or opened

### ISSUE THREAD

**Issue by dhanasekar416** [microsoft/vscode#73204]
**Issue Summary :** VSC Crashes when files are opened / saved
**First Occurance :** October 2018
**File Formats (Most Frequent) :** .java, .txt, .properties, .json

**_Bug Description :_**
- VSC crashed when files are opened / saved.
- This happens when new / existing files are saved or modified.
- Unsaved Data in _Untitled tabs_ are _not lost_ and are available when VSC is reopened.
- Git Project opened in VSC using Open Folder also experience this issue.

**Comment by dhanasekar416** [comment]
**_Hardware Description_**

- CPUs | Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)
- GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
- Memory (System) | 15.84GB (7.58GB free)
- Process Argv |  
- Screen Reader | no
- VM | 0%


_**Extension Description**_

- Extension | Author (truncated) | Version
- better-comments | aar | 2.0.3
- html-snippets | abu | 0.2.1
- gitlens | eam | 9.6.3
- json-tools | eri | 1.0.2
- mssql | ms- | 1.6.0
- java | red | 0.44.0
- vscode-java-debug | vsc | 0.18.0
- vscode-java-pack | vsc | 0.7.1
- vscode-maven | vsc | 0.16.2

**Comment by RMacfarlane** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by dhanasekar416** [comment]
I will get the crash logs and attach it soon.

**Comment by dhanasekar416** [comment]
The process has 9 log file in addition to dmp file and thus I has compressed it and added to drive and shared the link below for accessing crash logs.

Link : https://drive.google.com/file/d/1zSRXRgUFSM3knRKF0ufedjYtbyvbaJ1n/view?usp=sharing

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dhanasekar416** [comment]
I have tried with Insider and I am not getting the issue and I will be using the insider version for a few days with the debugger running in background and see if I can reproduce it.

**Comment by dhanasekar416** [comment]
I have reproduced it in nightly insiders build and attached the logs as a zip file and uploaded to drive and you can access it using below link.

Link : https://drive.google.com/open?id=1E9vvhPDJ5BPLQR-wOUjheghjmy5zRIhD

**Comment by bpasero** [comment]
@dhanasekar416 can you tell when exactly the crash happens? is it e.g. when a native file dialog is about to open or when you simply save a file?

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dhanasekar416** [comment]
I had observed that after I installed VSC nightly build and it was fresh without any extension, I did not get any crashes and only after I installed 2 extension (java extension _recommended_ and JSON Tools extension),I was able to reproduce the crash bug.

I will try without extensions and confirm.

**Comment by bpasero** [comment]
Ok please do

**Comment by dhanasekar416** [comment]
I used VSC without examples and VSC and VSC Insider did not crash and thus I can conclude that it is due to extensions.

In VSC Insider - I had installed Java Extension Pack (Microsoft) and Json Tools (Erik Lynd) before it started to crash and I was unable to determine which of the extensions are causing the crash.
