### ISSUE TITLE
Is it possible to stream a file into vscode from terminal 

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#7320]
- VSCode Version:1.2.0
- OS Version:ubuntu 16.4

on a remote server or while editing root needed config files from builtin terminal i have to use vim at the moment . 
Is there or will there be a functionality to pipe file into current code pane from builtin terminal

**Comment by Tyriar** [comment]
Not possible right now, interesting idea though

**Comment by sivy** [comment]
Similarly, would be nice to be able to pipe/stream output of a command through the command line `code` binary, like so:

```
$ ls -lah | code
```

Right now, this command does nothing (though Code seems to try to do something and does seem to become the active process).



* OS X Yosemite

**Comment by jcush** [comment]
@NikosEfthias and anyone else searching for this - maybe this will help in the meantime?

https://codepen.io/ginfuru/post/remote-editing-files-with-ssh

**Comment by khimaros** [comment]
Some exciting news on this front. Extension support for remote file providers is being tested: https://github.com/Microsoft/vscode/issues/35009

**Comment by gedw99** [comment]
This would be a dream.

Run your Dev environment inside vagrant 

Connect up to all your Linux servers, and see a view of the filesystem in the tree.

Would be so much more productive than neovim. Neovim is great but it's got a hell of a learning curve.

Btw I tried VSCode Remote. With the golang binary on each Linux server. Works as it's should, but it only handles a single file.
I had a look around and found some golang libs using sshftp to SSH in and sync a filesystem.

Any progress updates ??

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6161

**Comment by mjbvz** [comment]
We just announced remote development with VS Code, check out the [blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development) for details
