### ISSUE TITLE
after git add, the highlight of latest changed code should disappear

### ISSUE THREAD

**Issue by chenxichao-zingbox** [microsoft/vscode#73200]
- VSCode Version:1.30.2 (1.30.2)
- OS Version: mac os 10.14.3

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/47121401/57114617-ea4e3e00-6cfe-11e9-8914-5db0ccca4d24.png)

1. choose a file tracked by git
2. change some lines of code in it
3. you will see green mark in left side 
4. ```git add``` this file
5. the mark is still there

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Your [`git add`](https://www.git-scm.com/docs/git-add) command only **stages** your changes. The green mark will remain until you **commit** the staged changes (e.g. using [`git commit`](https://www.git-scm.com/docs/git-commit)).

If you haven't already seen [this section](https://code.visualstudio.com/docs/editor/versioncontrol#_git-support) of the VSCode docs I recommend it to you.

**Comment by chenxichao-zingbox** [comment]
Thanks for response!

I tried it again, and found even after `git commit` and `git push` the change, the green mark is still there.

**Comment by gjsjohnmurray** [comment]
Did you test with all extensions disabled, in case you're using one that's interfering with standard VSCode handling of this stuff?

**Comment by joaomoreno** [comment]
Did you open the root of the git repository as a folder in VS Code?
