### ISSUE TITLE
VSCode does not work with node-gyp

### ISSUE THREAD

**Issue by zhulika** [Microsoft/vscode#73205]
Issue Type: <b>Bug</b>

The latest VSCode keeps locking folders when it shouldn't. I have a node native addon that is built with node-gyp. One of the things that node-gyp does is to delete the 'build' folder.

When I try to use VSCode to develop this project, I get EPERM errors (http://prntscr.com/njsgb4) even when there are no extensions loaded (I removed them all to eliminate that as a possible cause).

It works the very first time that I load VSCode but fails after that. This means that a build cycle now requires me to restart VSCode which is a pain.

LockHunter shows that it is VSCode that is locking the folder: http://prntscr.com/njsigo

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

EDIT:

After some more experimentation, it appears as though this may be happening when there is a problem with the Node JS source code, so that it throws a SyntaxError. Once that happens, it node-gyp starts to fail because VSCode is locking the build folder (as above).

In other words the following sequence seems happy:

1. start VSCode.
2. run "node-gyp [...]" in a VSCode Terminal to build the native addon.
3. run "node test" in a VSCode terminal to execute some JavaScript that uses the native addon.
4. edit the source (JavaScript and/or C++).
5. repeat steps 2-4 as desired, provided there is no fatal (syntax error) in the Javascript.

If I introduce a syntax error in the JavaScript, then Node throws a SyntaxError exception in step 3 and bombs out to the Terminal (which is reasonable and expected) but step 1 will now fail with a EPERM sharing error on the build folder (which is not expected and rather annoying). Restarting VSCode gets everything back to normal (step 1-4 all work until the next SyntaxError)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (17.32GB free)|
|Process Argv|--folder-uri file:///d%3A/work/gml/serenity/0.2/src/serenityNode|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Sounds like it could be https://github.com/Microsoft/vscode/issues/68576#issuecomment-463865605/https://github.com/Microsoft/TypeScript/issues/29407 which is fixed in insiders

**Comment by zhulika** [comment]
Agreed. When will the fix make it onto the mainline?

**Comment by Tyriar** [comment]
@zhulika in the next 1-2 weeks

**Comment by zhulika** [comment]
thank you
