### ISSUE TITLE
Remember session not working

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#73209]
Issue Type: <b>Bug</b>

VS Code doesn't properly remember which files where open the last time it ran. When I close Code normally and start it again, it does indeed reopen the files I had open previously. But when I shutdown my pc, it does *not* save & remember which files where open.

I verified that the shutdown caused a graceful exit for Code. The shutdown also didn't happen "too quickly" (which shouldn't be possible) since it was waiting for VS2017 to close (that's always the slow one).

Perhaps you need to respond to [WM_QUERYENDSESSION](https://docs.microsoft.com/en-us/windows/desktop/Shutdown/wm-queryendsession) in addition to other exit signals.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (23.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|10.4.3
html-class-suggestions|And|1.0.7
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.5.0
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.6.1
vscode-versionlens|pfl|0.23.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.9
vscode-svg-previewer|vit|0.5.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
#12058 I guess

**Comment by thany** [comment]
As for #12058, saving the UI is probably a good idea, but the issue is not due to an unexpected shutdown. I am doing a perfectly normal/clean/graceful shutdown, which should never result in loss of anything.

WM_QUERYENDSESSION is your friend here. Windows sends different signals to applications for a normal exit, and a system shutdown.

**Comment by Noiredd** [comment]
@vscodebot
Thanks for creating this issue! We figured it's covering the same as another one we already have. But even though we know, we will not tell you which one is it - because honk you, that's why. You can search the entire 5400 issues yourself [here](https://aka.ms/vscodeissuesearch) though, spending half an hour on what took me 20 milliseconds ;)
Happy wasting your time! :+1:

**Comment by gjsjohnmurray** [comment]
@Noiredd I think you're crediting the bot with greater intelligence than it has. My guess is it merely responded to @bpasero adding the *duplicate tag. Many times such tagging is accompanied by a reference to the duplicate. Didn't happen this time, which is why I added a pointer to a candidate.
