### ISSUE TITLE
Background tasks with activeOnStart:false shouldn't show problems if beginsPattern isn't matched

### ISSUE THREAD

**Issue by justingrant** [microsoft/vscode#73202]
Currently, background tasks where `activeOnStart` is `false` emits problems into the Problems pane, even if `beginsPattern` is not matched by the output. If begin/end patterns do match, then problems are shown immediately after the matching line(s) is output. But if they begin pattern doesn't match, then problems are still shown-- albeit after a few-second delay.

I assume that this behavior is intentional as a fallback if begin/end patterns are missing. But if begin/end pattens are preset but incorrect (which will often be the case when building or troubleshooting task configs) then this behavior makes is really hard to debug the begin/end patterns because you don't know if they're working or not.

Furthermore, the problems that show up in this case cannot be removed until you close and re-open VSCode.  This means you can't tell the difference between a successful iteration of task config and left-over problems from the previous task run. If you're building a new task config, you might need 50+ iterations before getting the all the regexes right. Each iteration requires closing VSCode, reopening VSCode, re-opening the workspace, and re-running the task.  This is incredibly frustrating.

Instead of the current behavior, I suggest that VSCode should not emit any problems if all the following conditions are satisfied:
* `isBackground` is `true`
* `activeOnStart` is `false`
* `beginsPattern` is present (truthy)
* `beginsPattern` is not matched by the task output

Changing this behavior would make it clear whether a begin/end pattern pair is working or not, because if it's not working then no problems will show up in the problems pane.

BTW if you want to see the current behavior with a test repo, here are repro steps: 

1. `git clone https://github.com/justingrant/problem-matcher-cra.git`
2. `cd problem-matcher-cra`
3. `npm install`
4. break the `beginsPattern` in tasks.json, e.g. by replacing "^" with "^xxxxx" at the start of the `beginsPattern` regex and save the tasks.json file
5. run the `npm start` task using the Debug->Run Task... menu

Expected: no problems shown in the Problems pane (because `beginsPattern` doesn't match anything)
Actual: after a few-second delay, one problem is shown

6. Now press CMD+C (or Ctrl+C on Windows) to quit the task. 
7. Break the `beginsPattern` in some other way, e.g. by changing "xxxxx" to "yyyyy". This simulates the normal, iterative process of building a problem matcher where you try different regxes until you get the right ones.
8. Go to App.tsx and comment out this line of code: 
```typescript
const eslintWillComplain = 'foo';
```
9. Save that file, which will trigger a background recompilation. 

Expected: no errors shown in the Problems pane (because we just commented out the only line of code that was causing a problem) 
Actual: the old problem persists, even though we've fixed the problem in code. 

Once that persistent problem is shown, there's no way to get rid of it without closing and reopening VSCode or by running a working version of the task config, which you won't have because you generally only run into this problem when you don't (yet) have a working version of task config!

**Comment by justingrant** [comment]
BTW I just added a demo repo and repro steps to the original request, so you can see the problem live in action in a simplified repo.

**Comment by alexr00** [comment]
Thank you for the very detailed issue!
