### ISSUE TITLE
[TypeScript] Go to definition goes to *.d.ts when across project references

### ISSUE THREAD

**Issue by shivawu** [microsoft/vscode#73201]
The issue is, with project reference, going to the generated declaration file is really inconvenient. It should be possible to go directly into the source file.

Not sure this is a dup since many issues have been reported and it's unclear whether they're fixed, or whether it's a vscode or TS issue.

Maybe it's related to https://github.com/Microsoft/TypeScript/issues/16792 ?

- VSCode Version: 1.33.1
- OS Version: OS X 10.14.4

Steps to Reproduce:

1. clone https://github.com/RyanCavanaugh/project-references-demo.git
2. run `gulp core; gulp animals`
3. open the project using vscode
4. navigate to `animals/dog.ts`
5. do `go to definition` on the second line, either on the file name or the symbol name
6. vscode will go into `utilities.d.ts`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please try adding `"declarationMap": true` to the `compilerOptions` in your `tsconfig`. This will generated a map so that go to definition can just back to the original ts source instead of the generated d.ts

**Comment by shivawu** [comment]
I think you're right. I did not know that! 

Thanks a lot! Closing
