### ISSUE TITLE
Ctrl + A is interpreted as Ctrl + Q

### ISSUE THREAD

**Issue by CKortylak** [microsoft/vscode#73216]
Issue Type: <b>Bug</b>

I have an azerty keyboard.

When i press `a` on Visual Studio,  `a` is written on the editor. OK, this was expected
However, when i press `Ctrl + a`, Visual Studio exits.

Visual Studio seems to see my keyboard as qwerty when `Ctrl` is pressed.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 3.16.0-4-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3556)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 16, 16|
|Memory (System)|7.67GB (0.90GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-flylint|jbe|1.2.4
cpptools|ms-|0.23.0-insiders2
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
clang-format|xav|1.9.0

</details>

**Comment by alexandrudima** [comment]
@CKortylak Did you try configuring `keyboard.dispatch: "keyCode"`

**Comment by CKortylak** [comment]
@alexandrudima: Your advice was right:
`Ctrl+,`->`Application`->`Keyboard`->`Dispatch`->`KeyCode` 
fixes the issue.

Thank you !
