### ISSUE TITLE
VS Code is not working in windows 7

### ISSUE THREAD

**Issue by skotlex** [microsoft/vscode#73211]
If the latest version of the VS Code runs on Windows 7, the program will not run without an error.
This has been observed on a number of Windows 7 computers.
As a result of several tests, the last version of the VS Code running on Windows 7 is June 2018 (version 1.25)
I tried many things, but no message occurred. (ex. code --help, code --verbose etc.)
I hope this problem will be corrected as soon as possible.

**Comment by WSLUser** [comment]
Works fine on my Win 7 VM and I run Insiders.

**Comment by RMacfarlane** [comment]
Version 1.26 corresponded with when we updated from Electron 1.7.12 to 2.0.5. Possibly related: https://github.com/electron/electron/issues/12980

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by skotlex** [comment]
@bpasero I owe you for your services. Since it's a holiday here, I'll test it on May 7 and deliver the results. (I can't test it at home because the computer that doesn't work is a company computer.)

**Comment by bpasero** [comment]
Thanks

**Comment by skotlex** [comment]
@bpasero I ran the test today and successfully ran it in Windows 7 environment through the installation file you uploaded. Thank you for the correction. 

However, if there is one more request, I would like to request a portable version of VS Code for which the problem has been fixed. What do you think of this request? 

And I wonder when the fixed version of this issue will be officially released.
Thank you for your kindness.
