### ISSUE TITLE
Add *.repo file to Linux RPM repository

### ISSUE THREAD

**Issue by guoyunhe** [microsoft/vscode#73210]
For a RPM repository, it is good to have a `vscode.repo` file at the root folder of repository.

```
[vscode]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
type=rpm-md
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

Then the installation commands can be shorter (take openSUSE/SLE as example):

```
sudo zypper addrepo https://packages.microsoft.com/yumrepos/vscode/vscode.repo
sudo zypper refresh
sudo zypper install code
```

Skype for Linux already has this file https://repo.skype.com/rpm/stable/skype-stable.repo

**Comment by Tyriar** [comment]
I let the repo admins know 👍
