### ISSUE TITLE
Title constantly flickering on save, grunt watchify constantly rebuilding

### ISSUE THREAD

**Issue by doyintade** [Microsoft/vscode#7322]
- VSCode Version: 1.2.0
- OS Version: WIndows 7 Enterprise

Steps to Reproduce:

1. Run grunt watchify on a javascript project .

2. Modify the Js flie, so only new changes is built, the entire title area starts flickering, if you do in new Terminal addition that comes with latest VSCode, it makes it look like its on oveer drive, its also as if it's constantly building.

3. If you open the terminal, you will see the projects keeps rebuilding, whilst before it;s only meant to build once.

Very strange

**Comment by doyintade** [comment]
On further investigation, noticed this might be a save issue, when I save a file it seems like it's not saving then it tries to save again, hence the flickering the only I have seems to stop the flickering is my Control+Z which is undo command, and even though it's undo, when the flickering is happening it will allow the file to be saved.

**Comment by Tyriar** [comment]
By title area do you mean the part with "TERMINAL" or the file name? It would be great if you could make a gif of the flickering.

**Comment by doyintade** [comment]
![flickering](https://cloud.githubusercontent.com/assets/3006809/15963290/ad29f262-2f08-11e6-8c91-57f7fb0faad8.Gif)

I have attached the a gif screen shot, mind you the flickering looks slow only because I am capturing at 40 frames per second, so it happens a lot faster

**Comment by Tyriar** [comment]
Thanks @doyintade, it's clear who the owner is now :smiley:

**Comment by bpasero** [comment]
@doyintade are you able to share the workspace with me and give me further instructions how to replicate your setup on my machine?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
