### ISSUE TITLE
VSCode crashes when opening a 300kb JS file

### ISSUE THREAD

**Issue by vomc** [microsoft/vscode#73222]
- VSCode Version: 1.33.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. I was setting up a demo project using Laravel. I built the project and then opened the pre-built directories
2. As it was for a typical web app, there was a /public folder with an app.js file in it. I was curious as to what that file was. But clicking on it caused the editor to crash multiple times. Later macOS popped up a window saying 'Electron crashed'. 
3. In the folder, the file is shown as 337kb in size. 

Does this issue occur when all extensions are disabled?: Yes/No
YES

I am posting the file in question here: 
https://gist.github.com/vomc/d45adbe8a56330766e71ea84fbe40936

**Comment by rebornix** [comment]
@vomc sorry for coming late. Can you please try `code --max-memory=4096` and see if you can reproduce? I can't reproduce this issue locally even without modifying max memory.
