### ISSUE TITLE
The problem with syntax highlighting

### ISSUE THREAD

**Issue by Sovgut** [Microsoft/vscode#73220]
![image](https://user-images.githubusercontent.com/26426861/57130355-e1627880-6da1-11e9-89ce-d2011375ae52.png)

- VSCode Version: 1.33.1
- OS Version: Windows 10 17763 x64

Steps to Reproduce:

1. https://github.com/electron/electron-quick-start
2. Open index.html

Does this issue occur when all extensions are disabled?: Yes

**Comment by daggilli** [comment]
This is independent of language. It is application-wide.

**Comment by aeschli** [comment]
Looks like a problem of the HTML grammar.
Spaces are valid after the end tag id: https://www.w3.org/TR/html5/syntax.html#end-tags

**Comment by aeschli** [comment]
Duplicate of https://github.com/textmate/html.tmbundle/issues/97
