### ISSUE TITLE
Remote WSL: Integrated terminal ignores $SHELL

### ISSUE THREAD

**Issue by scy** [Microsoft/vscode#73236]
Issue Type: <b>Bug</b>

I'm using [fish](https://fishshell.com/) as my default shell in my WSL Debian installation:

```
sudo apt install fish && sudo chsh -s /usr/bin/fish $(whoami)
```

After doing this, relogin. You should now be running fish instead of bash. To check, run something like `X=y echo`. In bash, this will output a blank line. In fish, it will display an error. Also, you should have syntax highlighting while you type. Also, `$SHELL` should now be set to `/usr/bin/fish`.

Running `code-insiders .` will work fine, but when you start the integrated Terminal (<kbd>Ctrl+\`</kbd>), you'll find yourself inside of bash, not fish. Running `echo $SHELL` will still tell you `/usr/bin/fish` though, but repeating the test command from above (`X=y echo`) will not return in an error, showing that you're indeed running bash.

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.64GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/home/scy --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2801)|
|Memory (System)|15.89GB (5.64GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.32.0

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode-remote-release/issues/38
