### ISSUE TITLE
JavaScript object hover view squashes white space.

### ISSUE THREAD

**Issue by enalposi** [microsoft/vscode#73241]
Issue Type: <b>Bug</b>

Hi. 

I am assigning trade_.occId = occId; i.e. `"GD    190517P00155000"` to a property (in this case it contains 4 spaces. In the JavaScript hover view however, the property on 'trade' reads `occId:"GD 190517P00155000"` (only one space) [btw, I copied both these values right out of the IDE view]. I've just been chasing ghosts for some time because of this discrepancy and not expecting the IDE altering assigned values when viewing objects.
 
Update --->
Alright, sorry. I am not sure how to submit the first value on GitHub with the 4 spaces between GS and 1 preserved, even when using 'code' quotes (same as the VSC issue...). So the first value is "GD....190517P00155000" when replacing spaces with dots...

Thanks for VS Code otherwise :-)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.11.3
vscode-scss-formatter|sib|1.4.1
vscodeintellicode|Vis|1.1.5

</details>

**Comment by sandy081** [comment]
Can you please provide a screenshot of what you see? Also try disabling all extensions. I am not sure if such an hover is provided by out of the box typescript/javascript extension.

**Comment by enalposi** [comment]
Hi. Please see below. I disabled all extensions besides Debugger for
Chrome, which I need to set a break-point to be able to inspect values.
The issue is in most obvious in the field 'occId', which in fact has 4
spaces after 'GD' and not just one as displayed. Thanks for following up.

[image: image.png]

**Comment by sandy081** [comment]
Ah I see.. its an hover while debugging.

**Comment by isidorn** [comment]
You did not attach an image.
So please attach an image and some reproducable steps so we can investigate more. Thanks

**Comment by isidorn** [comment]
VSCode insiders will have the fix for this on monday.
Try it out and let us know if it is ok for you. Though I verified and the fix from @jeanp413  looks good

**Comment by enalposi** [comment]
Thanks for the work and update. Unfortunately I can't switch from VSCode stable, so I'll take your word for it until this hits release :-)
