### ISSUE TITLE
Terminal Bug: When running 'zsh', terminal window is cut off on scroll

### ISSUE THREAD

**Issue by valko92** [Microsoft/vscode#7324]
- VSCode Version: 1.2.0
- OS Version: OS X El Capitan 10.11.5

Steps to Reproduce:

1. Open terminal in VS Code and run a long, scrollable command
2. Scroll terminal window up and see that it stays where it should
3. Run `zsh` and then try to scroll terminal window
4. See the terminal window jump to the left and get cut off.

Closing the terminal window and opening it back up again, solves the issue. Also, running without extensions still makes the bug appear.
![vscodeterminalbug-](https://cloud.githubusercontent.com/assets/6547112/15858732/0c306b0e-2c90-11e6-95f4-b95bd6c8a744.gif)

**Comment by Tyriar** [comment]
This should be fixed by https://github.com/Microsoft/vscode/issues/6838, or it will come after that at least.

**Comment by weinand** [comment]
@Tyriar after running zsh I can no longer scroll up. So the terminal window no longer jumps to the left and it is not cut off. The the issue seems to be gone.
