### ISSUE TITLE
Unable to install because, the extension 'ms-vscode-remote.remote-containers' compatible with current version '1.33.1' of VS Code is not found.

### ISSUE THREAD

**Issue by bjayakumar** [Microsoft/vscode#73246]
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Tried to install: `ext install ms-vscode-remote.vscode-remote-extensionpack`
2. Got the following error: `Unable to install because, the extension 'ms-vscode-remote.remote-containers' compatible with current version '1.33.1' of VS Code is not found.`

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
@bjayakumar - per step 1 of the [Getting Started doc](https://code.visualstudio.com/blogs/2019/05/02/remote-development#_get-started) you need to be on the current Insiders build of VSCode (i.e. 1.34). Or wait a couple of weeks until 1.34 is expected to ship.

**Comment by bjayakumar** [comment]
My bad. I installed Builders but then I opened the stable version to install the extension. Thanks

**Comment by doronAtuar** [comment]
I still get the error for the official 1.34 version

**Comment by gjsjohnmurray** [comment]
My bad. It wasn't dependent on 1.34 but rather on Insiders. My guess is these extensions use APIs that aren't yet finalized. So you'll still need to use Insiders (currently 1.35).

**Comment by yurvor** [comment]
Unfortunately, I have this error for VSCode v1.34 and VSCode Insiders v1.35. Should they match?
```
user@host:~$ apt show code
Package: code
Version: 1.34.0-1557957934
...
user@host:~$ apt show code-insiders 
Package: code-insiders
Version: 1.35.0-1559280320
```
