### ISSUE TITLE
Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': 

### ISSUE THREAD

**Issue by GrosSacASac** [Microsoft/vscode#73253]
Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': Request vscode/content failed

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

0. be offline
1. look at package.json 

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
That's the expected result. 
Also see https://github.com/Microsoft/vscode/issues/51032
