### ISSUE TITLE
login to account to sync extensions/settings

### ISSUE THREAD

**Issue by Foroughi** [Microsoft/vscode#73251]
Like Google Chrome , it would be nice if we can login to our Microsft account and as soon as we login, our extensions, and  theme/key bindings settings restore into the IDE. so we don't have to install them again

**Comment by WSLUser** [comment]
Related: This would help with establishing the Azure extensions since you need an MS account.

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/2743

For settings, you might try https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
