### ISSUE TITLE
Excluding from problems.

### ISSUE THREAD

**Issue by Palidino** [Microsoft/vscode#73250]
So I've searched around and looked into the following, none of which worked: a folder exclusion setting on the Java linter, problems.exclude suggested but closed as a duplicate, and the duplicate closed because files.problemExclude worked. After testing, files.problemExclude is not excluding folders from Java linting and the setting is listed as unknown in vscode.

I have a folder containing Java code which I don't want to exclude from the sidebar, but that I do want to exclude from being linted with the rest of my project. It's a large amount of really old code with many warnings (but not errors). I'd like to ignore the problems from this directory so that I can easily manage my newer code. I'm aware that I can filter out the problems by using the filter field, but I'd like a permanent solution for specific directories.

EDIT:
As a temporary workaround, I commented out the src entry in the .classpath file of this directory. This so far appears to remove it from being linted automatically with the rest of my code. Scratch that, I can no longer run my launch configuration on that section of the project.

EDIT 2:
I downloaded eclipse and used it to hide warning messages for the directory, which carried over to vscode. Issue solved, though maybe down the road a way to pick these settings directly from vscode.

**Comment by sandy081** [comment]
I would expect this to be a feature in Java extension. Please file it there.
