### ISSUE TITLE
Proposal: smoother design for error squiggles

### ISSUE THREAD

**Issue by darknoon** [microsoft/vscode#73257]
The error squiggle is very angular in VSCode / monaco. I think a more rounded design would be less anxiety-inducing and would harmonize more with the typography.

Zooming in on what I mean
<img width="836" alt="Screen Shot 2019-05-03 at 18 13 49" src="https://user-images.githubusercontent.com/355540/57168337-66b05200-6dcf-11e9-820e-0c65d68857f4.png">

Here are some explorations I did at full size:
<img src="https://squiggle.darknoon.now.sh/explorations.svg" />

I created a more rounded version of the underline would be a drop-in replacement for [the current SVG pattern](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/widget/codeEditorWidget.ts#L1793):

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="6px" height="3px" viewBox="0 0 6 3" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<path d="M0,2 C1.5,2 1.5,0.5 3,0.5 C4.5,0.5 4.5,2 6,2" stroke="#D60A0A" fill="none" />
</svg>
```

```css
background-image: url("data:image/svg+xml,%3C%3Fxml version='1.0' encoding='UTF-8'%3F%3E%3Csvg width='6px' height='3px' viewBox='0 0 6 3' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3Cpath d='M0,2 C1.5,2 1.5,0.5 3,0.5 C4.5,0.5 4.5,2 6,2' stroke='%23D60A0A' fill='none' /%3E%3C/svg%3E%0A");
```

I didn't see any process listed for UI design, so I though I would bring this up as a feature request. I would be happy to go through the designers for VSCode before submitting a pull request to change it, as they would have more context on why it is this way

----

Usability issues with squiggles for errors are brought up in https://github.com/Microsoft/vscode/issues/16204, but I think it's outside the scope of this issue

**Comment by darknoon** [comment]
Oh, just noticed there is some design discussion going on in https://github.com/Microsoft/vscode/issues/8017 with regard to visual style, perhaps @misolori is one of the right people to see this since it should all look good together.

**Comment by misolori** [comment]
I think I'll be able to tackle this for this month, I do like the smoother lines you proposed. Thanks!

Code pointer:
https://github.com/microsoft/vscode/blob/877ce7ac034390e31c5ecebccbb0683bd2c51c3d/src/vs/editor/browser/widget/codeEditorWidget.ts#L1797-L1798

**Comment by misolori** [comment]
@darknoon  I've currently got a branch under `misolori/squiggles` that updates the squiggles to be just as you suggested and I'm not sure I'm a fan of the smoother lines:

## Current
<img width="521" alt="image" src="https://user-images.githubusercontent.com/35271042/66965862-100e9b80-f030-11e9-9755-4a4a2170c069.png">



## Proposed

<img width="495" alt="image" src="https://user-images.githubusercontent.com/35271042/66965872-19980380-f030-11e9-84db-52d8e76b19d9.png">

Our current version is a lot crisper, which the straight edges help with, and with the proposed they feel a bit "smudged".

**Comment by jrieken** [comment]
Unsure - the proposed design looks somewhat flat despite having the same hight (I assume)

**Comment by misolori** [comment]
After thinking this over and playing with the new squiggles, I don't think this something that we'd want to introduce since this doesn't looks crisp as I mentioned above. For this reason I'll be closing this issue and marking it as `out-of-scope`. If we ever revisit this in the future we can re-open.
