### ISSUE TITLE
Unable to use emmet in HTML it shows no suggestion when I click  ctrl + space key 

### ISSUE THREAD

**Issue by Reddy06** [Microsoft/vscode#73254]
Unable to use emmet in HTML it shows no suggestion when I click  ctrl + space key
https://user-images.githubusercontent.com/31631136/57165672-663aaa00-6e15-11e9-8e07-f7f58780ade7.png

**Comment by octref** [comment]
Open a html file first.

**Comment by Reddy06** [comment]
Hi Team,

Can you please provide complete solution in detail . I didn't understand
what exactly your refering to in the above mail.

Regards.

**Comment by Reddy06** [comment]
Got the solution .
