### ISSUE TITLE
tasks.json as a symlink isn't reloaded when changed

### ISSUE THREAD

**Issue by GloobyBoolga** [microsoft/vscode#73252]
Issue Type: <b>Bug</b>

# Steps to reproduce:
 1. edit any of the tasks, add a `"label": "some string to confirm re-load v1"`
 1. save
 1. check that the project now has a `.vscode/tasks.json`
 1. 
    ```
    mv .vscode/tasks.json ~/temp_tasks.json
    ln -s  ~/temp_tasks.json .vscode/tasks.json
    ```
 1. quit vscode, reopen vscode.
 1. edit label
 1. _Terminal_ -> _Run Task..._, 
 1. check name (label) of task

# Expected Result:
The label of the task should have been modified.
as #24739 is allegedly not reproducible.

# Observed result
The label of the task is still the old name.
<img width="840" alt="Screen Shot 2019-05-03 at 13 37 59" src="https://user-images.githubusercontent.com/5705972/57164371-bf202900-6da8-11e9-9a08-900831c69fe2.png">

# Workaround
```
touch -h .vscode/tasks.json
```
 - _Terminal_ -> _Run Task..._, 
 shows label has changed as soon as the `touch` is done.

---

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
githistory|don|0.4.6
gitlens|eam|9.6.3
global-config|Gru|0.0.7
rust-doc-viewer|JSc|1.0.4
python|ms-|2019.4.12954
cpptools|ms-|0.23.0-insiders2
proto|pet|0.0.2
vscode-docker|Pet|0.6.2
rust|rus|0.6.1
code-spell-checker|str|1.7.6
vscode-capnp|xmo|1.0.0

</details>

**Comment by derekpock** [comment]
Issue still present and exists also on Windows with `mklink`.
