### ISSUE TITLE
Support file-level snippet variables. 

### ISSUE THREAD

**Issue by ScottMGerstl** [microsoft/vscode#73261]
## Scenario
Working on various projects but using a lot of the same tooling between them, I would love to have the ability to specify file-level snippet variables so I could lift the whole snippet file from one project to another and only have to change the app specific strings in one place. 

### Example
I have snippets that automatically pull in the file name to use in stencil tag names and Component names. However, I scope my components with a namespace (e.g. `xapp-button`).

I would like to have the ability to specify the prefix `xapp-` in one place in the file and reference it though a common variable. This would allow my to copy the snippets file and place it in another project, change `xapp-` in one place to, say, `xapp2-`.

I completely realize a global find a replace accomplished this but I can see it being useful far beyond this simple use case. If snippets could reference variables, or other snippets, we could start creating composable snippets that contain other snippets letting us reduce the duplication of code and, when an issue is found or an enhancement is needed, thigs can be changed from a single location instead of all over the file.

Thank you for your consideration of this feature.

**Comment by lastobelus** [comment]
This is one of three features needed for VSCode snippets to approach the productivity-enhancing capability of Textmate snippets. The second is granular scope. And the third is for snippets to reliably work at 70wpm.

The full productivity benefit of snippets is only realized when they can become completely unconscious. As soon as you have to make conscious contextual choices you lose most of the benefits to flow.

in textmate, `col<TAB>` was a log statement in every language/framework I used. And `str<TAB>` was a labelled variable inspect inside a string -- in every language/framework.

so seeing a variable (whose name was on the clipboard) was a completely unconscious touch type: `col<tab>str<tab>` (with no lag, textmate snippets worked at typing speed & vscode snippets do only about half the time) and then `cmd<tab>` to console and it would generally already be in the (auto-running via guard or webpack watch or whatever) test output. 

:wistful-face

**Comment by jrieken** [comment]
Can someone point me to the Textmate doc/spec about file level snippet variables?

**Comment by lastobelus** [comment]
@jrieken I don't know if there is a spec. It isn't really snippet specific -- you can use any shell variable in a snippet & there are a variety of ways to contextualize shell variables: by scope, by file glob, by bundle (textmate equivalent of extension). Granular scope is probably more important/useful.
