### ISSUE TITLE
Editor swaps text with another panel

### ISSUE THREAD

**Issue by xer0x** [Microsoft/vscode#73268]
- VSCode Version: 1.34.0 (insiders)
- OS Version: Win NT x64 10.0.18362

Sometimes Undo corrupts my editor panels. I'm not sure what triggers this, but it is really annoying. The text from one panel can get into another, or a small undo will cause many many undos. 

This can be very frustrating and makes it hard to trust VS Code. I assume it has something to do with my vim and maybe prettier extensions. So maybe this isn't the correct place to mention this? It seems similar to https://github.com/Microsoft/vscode/issues/21305

Steps to Reproduce:

Sorry, I'm not exactly sure how to mix this up.. but it's sorta like this:

1. Enable VIM bindings
2. Open at least 2 files
3. Edit text in both files
3. Switch to split panels
4. Edit more test in both files
5. Type `u` for undo.
6. The text in the panels should get slowly get swapped

Does this issue occur when all extensions are disabled?: No..  I have Vim -vscodevim, and Prettier -Esben Petersen installed.

**Comment by RMacfarlane** [comment]
Since the vim extension controls what happens when you press `u`, I think the bug is with the extension. Can you reopen this issue there? https://github.com/VSCodeVim/Vim
