### ISSUE TITLE
Debug console outpu chaos

### ISSUE THREAD

**Issue by Peorz** [Microsoft/vscode#73265]
- VSCode Version: 1.33.1 (1.33.1)
- OS Version: MacOS 10.14.4 (18E226)

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/16849027/57173257-927b1880-6e5f-11e9-9da7-7f1eaf28b316.png)
![image](https://user-images.githubusercontent.com/16849027/57173260-a1fa6180-6e5f-11e9-89ac-8c8255915ddd.png)
![image](https://user-images.githubusercontent.com/16849027/57173263-ade62380-6e5f-11e9-8d5d-1c0310e15fc0.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
This is fixed in latest insiders https://code.visualstudio.com/insiders/
