### ISSUE TITLE
CompletionItems should control if they are auto acceptable

### ISSUE THREAD

**Issue by user414** [Microsoft/vscode#7326]
- VSCode Version: 1.1.1-insider
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:
1. Type any word that conflicts with one of your variable, for example if you have a variable CustomerComponent and you want to have a comment saying "this is the problem with my Customer." when you start typing Customer the CustomerComponent will popup and when you want to insert a period it will auto complete with CustomerComponent

I come across similar behavior when typing import statement like

```
import {CustomerComponent} from '/widget/customer.model.ts'
```

Intellisense will try to autocomplete again in when I type "customer.". There the only two instance when this happen, and it seems to happen quite often. I would suggest to switch Intellisense to spellcheck in a comment and perhaps turn it off on import, or have an option where a period wouldn't trigger autocomplete. I'm not too sure about how best to address the import case. The comment case seem to be clearer to have a spellcheck mode, or just simply turn it off if there's no built-in spellcheck.

**Comment by jrieken** [comment]
We have a new configuration option to disable word based suggestions

**Comment by user414** [comment]
@jrieken we tried and in 

Version 1.2.0-insider
Commit 24e811aaa256f9d45c10fbe2491a5938f57482c0

the changing of 

```
"editor.wordBasedSuggestions": true|false
```
As no effect on the issue originally described. Does changing those setting fix the problem for you?

**Comment by jrieken** [comment]
Yes - with that setting set to `false` you should not get completions inside comments unless you have another extension installed that does that

**Comment by dbaeumer** [comment]
@jrieken: I could still think about use cases where I want work based completion and still want different accept characters per scope. Any suggestions how to best realize that?

**Comment by user414** [comment]
@jrieken  Thank you it was an extension that was causing it to do that even when set to false.

So that solves the comment, I thought about the import and could we make it that, for typescript at least, it autocomplete with whatever you have inside your folder. So for example if you have a class CustomerComponent located at <folder root>/widget/customer.component.ts starting to type ```import``` would bring up a list of typescript construct that you could choose and it would autocomplete the path for you. Or something similar.

**Comment by jrieken** [comment]
@dbaeumer There is little custom control about accept characters, *internally* we have a property [`noAutoAccept`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L387) which should be set to false for textual completions

**Comment by dbaeumer** [comment]
@jrieken do we have an issue to provide more control here. If not I will open one.

**Comment by jrieken** [comment]
Well, you have have control over the behaviour cos it's defined as keybinding

```
{ "key": ".",                     "command": "^acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible && suggestionSupportsAcceptOnKey && editorLangId == 'typescript'" },
```

The question if it makes sense to encode the provider of the suggestion, maybe even instead of the `acceptOnKey` condition.

**Comment by dbaeumer** [comment]
@jrieken may be I am misunderstanding it but the keybinding is currently not sensitive to a scope. From the discussion I see a need to disable '.' as a accept character in comments and strings. But to my understanding there is no way to control this right now. Is your suggestion to expand the key binding feature with a scope or should we add that information to a completion item.

**Comment by jrieken** [comment]
I don't think that the scope is sufficient but that the completion item will know. Think of such JS code and the cursor being inside the curly brackets. In that case it makes sense to complete on dot.

```js

/**
 * @param {foo.ba|} a
 */ 
function foo(a) {

}
```

A sample the other way around would be writing a number literal for which someone proposes completions. I then might not make sense to complete on dot

```js
var n = 33.|
```

Therefore I think either the provider or the item should define if it can be completed on a completion character.

**Comment by dbaeumer** [comment]
Makes sense to me. How do we tackle this ? Should I make a corresponding API request.

**Comment by jrieken** [comment]
Let's use this issue for that

**Comment by jrieken** [comment]
So, thanks to some new API on the editor widget we are planning to make the following change: Instead of a command (https://github.com/Microsoft/vscode/issues/7326#issuecomment-225510985) accepting a completion we will allow completion items to say which characters automatically insert them. Something like this:

```ts
const item = new CompletionItem('foo')
item.autoAcceptCharacters = ['.', ';'];
```

That specifies that the completion item instance will be accepted/inserted *before* the editor types the actual character. Each completion item can have a different set of accept characters, e.g. `console` can be accept with `.` because it has members, like `console.log` but something like a snippet or keyword doesn't make much sense to be accepted when typing certain characters. An import statement might be completed when typing `'` or `"` but not when typing `.` etc ect

**Comment by jrieken** [comment]
fyi @DustinCampbell This will allow you to make remove [those](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L445) keybindings which by itself should make things nicer and it also gives you more freedom.

**Comment by DustinCampbell** [comment]
nice!

**Comment by DustinCampbell** [comment]
We fine tune C# IntelliSense with different commit characters per item in Visual Studio, so this will be a huge help. Note that sometimes C# will commit items differently depending on the commit characters typed in Visual Studio.

**Comment by jrieken** [comment]
Yeah, I reckon so. Especially after looking for inspiration in [CompletionItemRules.cs](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionItemRules.cs,86) ;-)

**Comment by mjbvz** [comment]
@jrieken Thanks for the quick followup on this

I'm putting together a prototype using TypeScript to test this out: #18380 It seems to work well so far, but I'm going to keep looking into tuning the behavior for the various completion entry types TS supports

**Comment by mjbvz** [comment]
Kai and I were talking about this issue today, and there was some concern that we may still need a way to control the commit characters for word based suggestions. This would likely involve asking TypeScript for a list of valid completion characters at a given position, and using these to commit  word  based completion items.

In this example: 

```ts
class Foo {
    bar: number
}

/**
 * @param {Fo|} 
 */
function x() {}
```

We presumably would want to complete `Foo` if the user typed `.`. Being able to change the global commit characters that word based suggestions use based on context would allow us to do that. 

@kieferrm Does that sound like a correct description of the problem? Are scenarios like the above the main concern and, if so, could we instead investigate getting proper completion items from TS in that case?

**Comment by jrieken** [comment]
Word based suggestions never completed on commit characters and still do not. Looking the above sample and the jsdoc comment, the `Foo` suggestion that commits on `.` should then be computed by TypeScript because only that knows if Foo is valid in that context and what it means. So, not word based but semantic suggestions. I am against entangling them by some commit-character-exchange logic.

**Comment by aeschli** [comment]
start verifying...

**Comment by aeschli** [comment]
verified by implementing an extension that uses the new API.
