### ISSUE TITLE
mac - insider version - not getting latest build

### ISSUE THREAD

**Issue by minoseah629** [Microsoft/vscode#73262]
I have noticed for the past couple days that my VS Code insider would not get an update. 

The version my VS Code is on this commit 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
which was done on April 30th, so I got this on May 1st. 

[Screen Recording 2019-05-03 at 10.06.34 PM.zip](https://github.com/Microsoft/vscode/files/3143963/Screen.Recording.2019-05-03.at.10.06.34.PM.zip)

**Comment by minoseah629** [comment]
Additionally, I attempted to download the insider version from website, but still was same version.

**Comment by mjbvz** [comment]
That is the latest insiders. We did not publish one Thursday and there are none on weekends
