### ISSUE TITLE
Intellisense not working (C# Omnisharp)

### ISSUE THREAD

**Issue by SrinidhiKR** [Microsoft/vscode#73269]
Issue Type: <b>Bug</b>

In my VS code even after installing the extension, intellisense is not working. For example: When I press F12, it is not showing any definition. It is not identifying any error or debugging is not working

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.83GB free)|
|Process Argv|E:\Installed\VisualStudio\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.15.2

</details>

**Comment by RMacfarlane** [comment]
Hey @SrinidhiKR, can you see if this still reproduces after upgrading the latest version of VS Code? Can you also see if restarting VS Code fixes the issue?

If neither of these work, please file this bug on the C# extension here - https://github.com/OmniSharp/omnisharp-vscode. Sorry, I'm not able to transfer issues. Thank you!
