### ISSUE TITLE
freezing for 2-25 seconds on a regular basis

### ISSUE THREAD

**Issue by mo** [Microsoft/vscode#73274]
VSCode is freezing for 2-25 seconds on a regular basis, this is driving me nuts! This has been going on for a few months, but I feel like it's gotten worse lately. I tried disabling all extensions but it still happens.

Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-13-generic

Steps to Reproduce:
1. happens. all. the. time.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mo** [comment]
It often happens when I do code completion or press some key combination. I wonder if maybe it's related to AT-SPI2 and/or DBUS somehow? Something that you call into but that is never seen on Windows?

**Comment by thecodercoder** [comment]
I'm having the exact same thing happen on Windows 10, even with all extensions disabled/uninstalled. My whole system will freeze for 5-7 seconds, then be not-frozen for 2 seconds, then go back to frozen. This happens as soon as I open VS Code, even if there's no files/folders/workspaces open in it. Will continue until I close the program, then the freezing stops immediately.

I tried downgrading to the previous 2 versions but it is happening on all versions. Anecdotally, I posted a survey on social media and multiple others are experiencing the same thing, on both Windows and Linux.

**Comment by RMacfarlane** [comment]
@mo @thecodercoder Can you open the process explorer (`F1`, `Developer: Open Process Explorer`) and see if there is any particular process with high CPU usage?

**Comment by mo** [comment]
@RMacfarlane all of the items listed in the process explorer that is built in to VSCode are showing low CPU usage but if I instead look at "top" from a linux terminal instead I see that the "/usr/share/code/code --type=renderer --no-sandbox ..." process is spinning at 100% CPU during the entire freeze.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by thecodercoder** [comment]
@bpasero I installed the Insider build (1.34.0) and it works perfectly. Also, for some reason my regular VS Code is now working without freezing, even when I re-enabled all my extensions. (When it was freezing, I didn't see any process tasks using a larger-than-normal amount of CPU.)

Very mystifying!

**Comment by mo** [comment]
@bpasero the freezes got a bit better using insiders (they went from 2-30 seconds to 2-3 seconds) so something was fixed for sure but the user experience for me is still very unsatisfactory using insiders
