### ISSUE TITLE
Intergrated [CMD] Terminal cursor position

### ISSUE THREAD

**Issue by XXerxesG** [Microsoft/vscode#73270]
Issue Type: <b>Bug</b>

In the Intergrated Terminal [CMD]  at launch the cursor is few lines below the directory address and the address is not visible. The window seems to be scrolled down and cursor position is shifted below This issue is only there when you start the terminal for the first time after that the cursor is on the same line.  The address is not visible on first launch and after executing a command the directory address is visible again

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-glsllint|CAD|0.0.5
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
php-intellisense|fel|2.3.10
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
python|ms-|2019.4.12954
notepadplusplus-keybindings|ms-|1.0.2
vetur|oct|0.19.4
laravel-blade|one|1.20.0
laravel5-snippets|one|1.5.0
material-icon-theme|PKi|3.7.0
java|red|0.44.0
laravel-artisan|rya|0.0.25
shader|sle|1.1.4
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.2
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
