### ISSUE TITLE
Live server plugin feature is not working.

### ISSUE THREAD

**Issue by Reddy06** [Microsoft/vscode#73271]
When I tried to open the My HTML code in Live server it giving blank webpage  please find the attachment.

https://user-images.githubusercontent.com/31631136/57175226-eb9a7a80-6e66-11e9-85f2-0aa183a95aeb.png

**Comment by TheCloudSaver** [comment]
Have you tried another browser or reloading VS Code?

**Comment by RMacfarlane** [comment]
Please file this on the Live Server extension - https://github.com/ritwickdey/vscode-live-server - I'm not able to transfer the issue. Thank you!
