### ISSUE TITLE
folder replace is weird, something changed, but something remain.

### ISSUE THREAD

**Issue by readingsnail** [microsoft/vscode#73276]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4

Steps to Reproduce:
1. replace from } > ]
<img width="997" alt="스크린샷 2019-05-04 오후 5 55 47" src="https://user-images.githubusercontent.com/1904967/57176689-e6a0ef80-6e95-11e9-948a-c215bce12de9.png">

after replace, replace is leave remains
<img width="997" alt="스크린샷 2019-05-04 오후 5 57 33" src="https://user-images.githubusercontent.com/1904967/57176710-1ea83280-6e96-11e9-9b1c-b22fd0ae18bf.png">

Does this issue occur when all extensions are disabled?: Yes/No
yes

Testing File -
[trans.zip](https://github.com/Microsoft/vscode/files/3144178/trans.zip)

**Comment by sandy081** [comment]
@readingsnail Tried your sample and it replaced correctly.

Am I missing anything here?

**Comment by readingsnail** [comment]
so in my case, for example,
} > ]

ip_generic_6_b_tooltip:0 "Every City in the #Y Province of [SCOPE.sP('ip_generic_6_province').GetState.GetShortName **}** #! receives the following modifier:"

so that's reason, i put the correct replaced(first one), but someone } is remained.

**Comment by sandy081** [comment]
I can reproduce it now. Here are the steps I followed

- Used the attached zip
- Opened VS Code on that zip
- Do Search and Replace with `}' with `]`
- Everything is good 
- Go to the finder and delete the root folder 
- Refresh the Explorer in VS Code
- Get the folder back again by unzipping it
- Refresh the Explorer in VS Code
- Do Search and Replace with `}' with `]`
🐛 Not all files in the result are replaced. There is following error in console

```
ERR Error: Overlapping ranges are not allowed!
    at PieceTreeTextBuffer.applyEdits (pieceTreeTextBuffer.js:163)
    at TextModel._applyEdits (textModel.js:1009)
    at TextModel.applyEdits (textModel.js:967)
    at EditStack.pushEditOperation (editStack.js:109)
    at TextModel._pushEditOperations (textModel.js:961)
    at TextModel.pushEditOperations (textModel.js:886)
    at ModelEditTask.apply (bulkEditService.js:82)
    at BulkEditModel.apply (bulkEditService.js:173)
    at BulkEdit.<anonymous> (bulkEditService.js:304)
    at Generator.next (<anonymous>)
    at fulfilled (bulkEditService.js:16)
```

**Comment by sandy081** [comment]
@rebornix @alexandrudima What does this error explain?

**Comment by alexandrudima** [comment]
@sandy081 This happens for the file `rel_flavor_l_english_ko.properties`

Somebody asks to replace overlapping edits. Of the 436 edits in that file, two edits are identical... the edit to replace `[356,556 - 356,557]` is twice in the edits list.
