### ISSUE TITLE
eslint not working after update 1.33.1

### ISSUE THREAD

**Issue by chengweiou** [microsoft/vscode#73288]
It's just updated 1h ago, before was ok
extensions: dbaeumer.vscode-eslint 1.8.2

- VSCode Version: 1.33.1
- OS Version: mac mojave 10.14.4

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
I just tried install eslint on version 1.33.1 and it seems to be working for me. Does the extension just not start at all for you? Can you try `F1` `ESLint: Show Output Channel` and see what's printed there?

**Comment by chengweiou** [comment]
i just checked, it works fine on .js file. Open the show Output Channel. problem also counting.
but It doesn't work on .vue file.it's showing:
[Info  - 10:16:56 PM] ESLint server stopped.
[Info  - 10:16:56 PM] ESLint server running in node v10.2.0
[Info  - 10:16:56 PM] ESLint server is running.
[Info  - 10:16:57 PM] ESLint library loaded from: 
......./project/vue2/node_modules/eslint/lib/api.js

here is the .eslintrc.js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  'extends': [
    'plugin:vue/essential',
    '@vue/standard',
  ],
  rules: {
    // 'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    // allow async-await
    'generator-star-spacing': 'off',
    'space-before-function-paren': ['error', 'never'],
    'comma-dangle': ['error', 'always-multiline'],
    // allow debugger during development
    'no-tabs': 0,
  },
  parserOptions: {
    parser: 'babel-eslint',
  },
}

**Comment by chengweiou** [comment]
fixed by add new config:
