### ISSUE TITLE
corrupted GUI after screensaver

### ISSUE THREAD

**Issue by tmdag** [microsoft/vscode#73280]
I'm getting corrupted GUI when exiting screensaver. Only VS code gui is corrupted, other, previously opened applications are not affected (like with sublime never had that issue).
I have to close whole application and reopen in order to get my UI working which makes it very annoying.
I have checked multiple different Nvidia and/or cuda drivers and It does not make any difference

![noise](https://user-images.githubusercontent.com/9139248/57182314-8472cb00-6e52-11e9-9b46-2c54b321d805.png)

## Environment data
- VS Code version: 1.33.1
- OS and version: 5.0.7-200.fc29.x86_64

- Nvidia Driver Version: 418.39
- CUDA Version: 10.1 

## Steps to reproduce:
1. open vscode
2. start screensaver
3. close screensaver

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by tmdag** [comment]
happy to try, do you have build for redhat ? (as lined version is for debian and I'm running Fedora 29)

**Comment by bpasero** [comment]
@tmdag https://az764295.vo.msecnd.net/exploration/39c4800ca7ffc78a6256428e51425332b3898117/code-exploration-1557124866.tar.gz

**Comment by tmdag** [comment]
Thx! doesn't look like it's helping :(. And to be more precise, this issue is happening after hibernation (not screensaver as i initially thought)
![gui_issues](https://user-images.githubusercontent.com/9139248/57267732-f6efd080-7035-11e9-97e7-7b4be50f47bc.png)

**Comment by tmdag** [comment]
ok, before I will get deeper, there is a possibility that my GFX card is corrupted :
https://devtalk.nvidia.com/default/topic/1051405/cuda-setup-and-installation/inforom-is-corrupted-at-gpu/post/5336375/#5336375

**Comment by DarthBo** [comment]
All our Ubuntu/Arch desktops suffer the same problem at work. It's an nvidia driver issue. 
Gnome suffers from it as well: https://gitlab.gnome.org/GNOME/mutter/merge_requests/600

More info: https://www.khronos.org/registry/OpenGL/extensions/NV/NV_robustness_video_memory_purge.txt

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
