### ISSUE TITLE
Error opening task.json in linu/unix

### ISSUE THREAD

**Issue by DanKline** [microsoft/vscode#73287]
Type: LanguageService
Terminal - Configure Task

Describe the bug

    OS and Version: Debian 9 Stretch Arm64

    VS Code Version:
    Version: 1.32.0 (user setup)
    Commit: aeaef41d51201e555735f5e8d2f38a9d0ddb9026
    Date: 2019-02-20T06:32:49.577Z
    Electron: 3.1.3
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux arm64 4.4.154.c83-00028-gaeed0d91c4a7

    C/C++ Extension Version: ?? current

    Other extensions you installed (and if the issue persists after disabling them): only c# and C++ language related

To Reproduce

This is an attempt to set up a build task for phantomjs on ARM64
Create a task from template (e.g. echo)
From the "Terminal" menu select "Configure Task" and select Echo

when attempting to modify the task echo, the following message is displayed

Unable to open '.vscode\tasks.json': File not found
file:///media/nvme/phantomjs/.vscode\tasks.json)

NOTICE! The backslash in the path is OS dependent ... should be a forward slash for Unix
.vscode \ tasks.json should be .vscode / tasks.json

Expected behavior
The tasks.json file should be opened

Screenshots

Additional context

**Comment by alexr00** [comment]
Tried on Ubuntu 18 and I'm not able to reproduce.

**Comment by alexr00** [comment]
@DanKline, how did you install VS Code?

**Comment by DanKline** [comment]
I installed the "HeadMelted" version compiled for ARM 64 and I'm running on a RockPi 4B

**Comment by alexr00** [comment]
It looks like the problem is specific to that build then. Perhaps an incorrect library, or a library doing the wrong thing when compiled for ARM. I recommend reaching out to whoever produced the build and seeing if they can help!
