### ISSUE TITLE
Settings dropdown does not work with touch screen

### ISSUE THREAD

**Issue by Bas-vanHarten** [microsoft/vscode#73283]
On Windows 10 select the settings of VSCode (via File->Preferences->Settings) and try the change the value of a setting using a system with touchscreen (e.g. Files: Auto Save). VSCode does not respond at all :-(

**Comment by RMacfarlane** [comment]
@Bas-vanHarten Do other dropdowns respond to touch? View > New Terminal, there's a dropdown there as well

**Comment by Bas-vanHarten** [comment]
Other dropdowns (like that of Terminal) do respond as expected (with showing a list of options).

BTW: I tested with the following version:

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by rzhao271** [comment]
CC @TylerLeonhardt for testing this on iPad

**Comment by TylerLeonhardt** [comment]
Works on iPad ✅

**Comment by fotiDim** [comment]
Works now on Surface Pro.
