### ISSUE TITLE
Spaces in files names break links in the Output panel

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#73281]
When console output is turned into a link, it doesn't properly handle spaces in paths. In attached screenshot the link breaks after the space between "Test" and "Comments". Spaces appear to get handled when they occur between path separators, but when they occur between path separators then the file extension.

![image](https://user-images.githubusercontent.com/484784/57183499-c146be00-6e62-11e9-936d-fcf92cbf6864.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026
