### ISSUE TITLE
VS Code Showing 'mvn' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by cedverd** [microsoft/vscode#73285]
I'm trying to create a maven project with VS Code but when I run the command it says :
> 'mvn' is not recognized as an internal or external command,operable program or batch file.
but mvn -version is running on command prompt

Environment varaible for User :
MAVEN_JOME : `C:\MAVEN\apache-maven-3.6.1`, `M2_HOME : C:\apache-maven-3.6.1`, `JAVA_HOME : C:\Program Files\Java\jdk1.8.0_212\jre` and

System Variables
path is set to `C:\apache-maven-3.6.1\bin`, `C:\Program Files\Java\jdk1.8.0_212\bin` for maven and java respectively.

The command I'm running to create the project is:  `mvn archetype:generate -DgroupId=com.cs.test-project -DartifactId=test-project -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false` 

The Reference to Command(https://stackoverflow.com/questions/46671308/how-to-create-a-java-maven-project-that-works-in-visual-studio-code) 

The VS Code Reference to Command(https://code.visualstudio.com/docs/java/java-project#_generate-project-from-maven-archetype)
> The same command is running in Command prompt and it created the project successfully on Desktop.
>I'm Running vs code 1.32 Version and Windows 10 18890.1000 32 bit

`code -status ` is 

`CPU %     Mem    MB        PID       Process

Process Argv:'

`GPU Status:       2d_canvas:                    enabled

                  checker_imaging:              disabled_off

                  flash_3d:                     enabled

                  flash_stage3d:                enabled

                  flash_stage3d_baseline:       enabled

                  gpu_compositing:              enabled

                  multiple_raster_threads:      disabled_off

                  native_gpu_memory_buffers:    disabled_software

                  rasterization:                enabled

                  surface_synchronization:      enabled_on

                  video_decode:                 enabled

                  webgl:                        enabled

                  webgl2:                       enabled

CPU %   Mem MB     PID  Process

    6       58    9604  code main

    0       50      68     gpu-process

    0      106    3304     window (Welcome - Visual Studio Code)

    0       53    3908       extensionHost

    1       58    5332     window (Welcome - Untitled (Workspace) - Visual Studio Code)

    0       10    4000       electron-crash-reporter

    0       17    9048       watcherService

    0       22   10228       extensionHost

    0       99    5792     window (ΓùÅ Untitled-1 - .vscode (Workspace) - Visual Studio Code)
    0        4     564       winpty-process

    0        3    2380         C:\WINDOWS\System32\cmd.exe

    0        7    8936         console-window-host (Windows internal process)

    0       17    4472       searchService

    0       35    4884       extensionHost

    0       17    7320       watcherService

    1        4    9136       winpty-process

    0        7    4444         console-window-host (Windows internal process)

    0        3    9952         C:\WINDOWS\System32\cmd.exe

    0       48    6228     shared-process`

Workspace Stats:

|  Window (ΓùÅ Untitled-1 - .vscode (Workspace) - Visual Studio Code)
|    Folder (projects): 0 files
|      File types:
|      Conf [files:]
C:\Users\EDVERD>`

**Comment by Tyriar** [comment]
Can you check the path in the integrated terminal and check the difference between conhost/cmd.exe?
