### ISSUE TITLE
version 1.32.3, Search setting input font-size bug 

### ISSUE THREAD

**Issue by garuhester** [microsoft/vscode#73291]
Issue Type: <b>Bug</b>

when i use ctrl+middle mouse button to enlarge some file's font-size, and in search setting top input, the font-size is wrong, it's incomplete display.

: )

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (12.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
vscode-ant-design-vue-helper|ant|1.0.6
app-migrator|deb|0.0.6
xml|Dot|2.4.0
vscode-great-icons|emm|2.1.47
minify|Hoo|0.4.3
rest-client|hum|0.21.2
docthis|joe|0.7.1
code-beautifier|mic|2.2.1
vscode-autoprefixer|mrm|2.2.0
python|ms-|2019.3.6558
csharp|ms-|1.19.0
sublime-keybindings|ms-|4.0.0
vetur|oct|0.19.5
polacode|pnp|0.2.2
vscode-css-peek|pra|2.2.0
minapp-vscode|qiu|1.13.3
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
unity-debug|Uni|2.7.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
somehow ended in my inbox but being ignored.

**Comment by roblourens** [comment]
@rebornix this was https://github.com/microsoft/vscode/issues/58784#issuecomment-460481329 which was closed but probably is not fixed

**Comment by roblourens** [comment]
Can no longer reproduce this
