### ISSUE TITLE
Output pane is a performance bottleneck once it gets big enough

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7329]
I started self hosting on the output pane, keeping it visible at all times. I feel the workbench getting super sluggish after 15 minutes of smooth development. I feel it while typing: it becomes slow. Clearing the output from the Output pane fixes it.

In the following screenshots / timelines, I merely enter a newline and wait for the workbench to react and update all decorations.

#### Before

When the output is really big (after 15 minutes of development) this is what I get:

[Chrome timeline](https://github.com/Microsoft/vscode/files/302815/before-clear.json.txt)

![screen shot 2016-06-07 at 16 23 30](https://cloud.githubusercontent.com/assets/22350/15861232/397690fc-2ccc-11e6-944d-20f85ad589e5.png)

#### After

Once I clear the output, all of the sluggishness disappears.

[Chrome timeline](https://github.com/Microsoft/vscode/files/302818/after-clear.json.txt)

![screen shot 2016-06-07 at 16 25 12](https://cloud.githubusercontent.com/assets/22350/15861342/6ba433cc-2ccc-11e6-8917-891d418d7a85.png)

**Comment by joaomoreno** [comment]
I feel it may be related to link detection, since those seem to take their time to appear in the output pane, but I'm sure the timelines attached above will tell the truth.

**Comment by bpasero** [comment]
@joaomoreno please run "out of dev" with link detection commented out (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputMode.ts#L80) to see if it is related.

I rather believe you are running into memory pressure and full GCs are causing rendering slowdown.

**Comment by joaomoreno** [comment]
Clearly not, just compare both timelines. I think there is enough information here already...

**Comment by bpasero** [comment]
Btw link detection is running in outputWorker.ts which as far as I understand runs inside a worker (@alexandrudima can confirm). I believe most time is being spend in tokenizing the output using this monarch mode: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/outputMode.ts#L21

**Comment by bpasero** [comment]
@joaomoreno let me know how it goes in selfhost, I pushed a change to disable monarch coloring and also some of the language configuration that imho does not make much sense there.
