### ISSUE TITLE
 live server plugin is disabled

### ISSUE THREAD

**Issue by LFlifeng** [Microsoft/vscode#73298]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
The  live server plugin is disabled and the bottom toolbar go live is not displayed

**Comment by RMacfarlane** [comment]
@LFlifeng You can enable the extension again from the extensions viewlet:

<img width="622" alt="Screen Shot 2019-05-05 at 8 36 35 AM" src="https://user-images.githubusercontent.com/3672607/57196352-032e3d80-6f11-11e9-981e-84e24b70bb9a.png">

When the extension is disabled, it is expected that the "Go Live" button is not displayed.
