### ISSUE TITLE
Bad coloring for C++

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vscode#73292]
- VSCode Version:
Version: 1.34.0-insider
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T05:15:04.403Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-29deepin-generic

- OS Version:
Linux x64 4.15.0-29deepin-generic

Steps to Reproduce:

1. start code with `code-insiders --disable-extensions`
2.
```c++
int main() {
    int test_enum = 1
}
```
and save the file with `.cpp` extension.
the coloring will be
![image](https://user-images.githubusercontent.com/1279292/57188266-43e87f80-6f2e-11e9-9827-3018bfbe6aa8.png)

**Issue**:
the enum substring in identifier `test_enum` is taken as `enum` keyword.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cloudhan** [comment]
For additional information, with stable release
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-29deepin-generic

the coloring is correct.

**Comment by jeff-hykin** [comment]
Sorry about the bug, this was caused upstream from `https://github.com/jeff-hykin/cpp-textmate-grammar`. A fix was pushed just now for it. Since the grammar normally gets re-pulled with VS Code updates, a quick fix in the meantime is to install the Better C++ Syntax extension.

**Comment by cloudhan** [comment]
Fixed in

Version: 1.35.0-insider
Commit: 4ca38ce5584d7cd67b435b3c32ef1240c6a29628
Date: 2019-05-21T05:15:14.763Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-29deepin-generic
