### ISSUE TITLE
Folder open dialog not scaling with resolution of system

### ISSUE THREAD

**Issue by joshij1979** [microsoft/vscode#73295]
<img width="960" alt="scaling_issue" src="https://user-images.githubusercontent.com/5530733/57188880-ee0eda00-6f23-11e9-8e21-d52a26289819.PNG">

The file /folder open dialog is not scaling properly with the native screen resolution

Window 10

**Comment by mikecalligaro** [comment]
This is especially troublesome on a 29 inch 4K monitor.  I've got to set Windows Scaling to 175% to be able to see the text on this monitor.  Getting the file open dialog at 100% makes the text _tiny_.

**Comment by kwinz** [comment]
Issue still exists. Please reopen.

**Comment by kwinz** [comment]
Possible duplicate of #85898
