### ISSUE TITLE
Terminal Doesn't Show Current Directory When Initialization

### ISSUE THREAD

**Issue by modmeister** [microsoft/vscode#73290]
Issue Type: <b>Bug</b>

New Terminal

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.77GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.19.0

</details>

**Comment by genericandy** [comment]
Following -- seeing the same issue

**Comment by fatherofinvention** [comment]
Same issue here. Cursor also does not work well. Does not respect blinking configuration and suffers from lag.

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by lukasskull** [comment]
Me too
After update the windows to 1809 version

**Comment by lukasskull** [comment]
Me too after update the windows version to 1809

**Comment by lukasskull** [comment]
![image](https://user-images.githubusercontent.com/50363767/57294841-1dc00c80-70f3-11e9-8dc7-7db2b3ca2fea.png)

Me too

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
