### ISSUE TITLE
拆分终端：无法同时显示两个终端窗口

### ISSUE THREAD

**Issue by koala0521** [microsoft/vscode#73293]
Issue Type: <b>Bug</b>

点击【拆分终端】报错。
错误信息：终端进程命令“/bin/bash -l”无法启动 (退出代码: 1)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|-psn_0_9509137|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.4.2
tortoise-svn-for-vscode|cds|0.1.1
path-intellisense|chr|1.4.2
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
es7-react-js-snippets|dsz|2.2.2
vscode-html-css|ecm|0.2.0
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|1.9.0
vue-format|feb|0.1.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
Hap|hap|0.0.8
beautify|Hoo|1.5.0
vscode-elm-jump|joe|0.0.1
vscode-apache|mrm|1.2.0
vscode-language-pack-zh-hans|MS-|1.33.2
vetur|oct|0.19.5
live-preview|pro|0.0.3
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.3.13
html5-boilerplate|sid|1.0.3
open-in-browser|tec|2.0.0
local-history|xyz|1.7.0
markdown-all-in-one|yzh|2.3.1

(2 theme extensions excluded)

</details>

**Comment by byyxx128** [comment]
Translation here.

> An error is caused by clicking `Split Terminal`.
"The terminal process command `/bin/bash -l` failed to launch (exit code: 1)".

***
以后自己用英文反馈，非英文反馈都会被直接 close。
![image](https://user-images.githubusercontent.com/20079289/57188570-ec66f700-6ece-11e9-873e-cb775932b16e.png)

**Comment by byyxx128** [comment]
Translation here:
> ### **Split Terminal: Unable to Display Two Terminal Windows**
> An error is caused by clicking `Split Terminal`.
> "The terminal process command `/bin/bash -l` failed to launch (exit code: 1)".
***
以后自己用英文反馈，非英文反馈都会被直接 close。
![image](https://user-images.githubusercontent.com/20079289/57188570-ec66f700-6ece-11e9-873e-cb775932b16e.png)

**Comment by starship863** [comment]
> Translation here:
> 
> > ### **Split Terminal: Unable to Display Two Terminal Windows**
> > An error is caused by clicking `Split Terminal`.
> > "The terminal process command `/bin/bash -l` failed to launch (exit code: 1)".
> 
> 以后自己用英文反馈，非英文反馈都会被直接 close。
> ![image](https://user-images.githubusercontent.com/20079289/57188570-ec66f700-6ece-11e9-873e-cb775932b16e.png)

A possible reason might be that he/she is not so confident with his/her English. A possible approach is to post in English with help from google/sogou translation. Origional chinese post could also be attached so that Chinese speakers could help to improve the English translation.
可能他就是对英语不自信吧。今后可以考虑借助谷歌或者搜狗翻译成英语。中文原文也可以考虑附上，这样其它中文使用者也能帮忙改进英语翻译。

**Comment by byyxx128** [comment]
It is an effective solution to write in English and native language together well if the author is not confident with his/her English. Nevertheless, I have to mention that somebody used puzzling Chinese even I cannot understand what he/she was saying...
中英双语是种解决方式。不过不得不说有好多人连中国话都说不利索，我都看不懂……想给他们翻译都没法翻……这要命……

**Comment by Tyriar** [comment]
> Split terminal: Cannot display two terminal windows at the same time
> 
> Click [Split Terminal] to report an error.
> Error message: Terminal process command "/bin/bash -l" failed to start (exit code: 1)

Does changing `terminal.integrated.splitCwd` help?
