### ISSUE TITLE
What are the values for "kind" when defining a task

### ISSUE THREAD

**Issue by andrewufrank** [Microsoft/vscode#73304]
I define a new task and can enter a "kind" - I have seen that a value of "build" is possible and assume that "debug" is another one. 
I cannot find any documentation what the permited values are and what effect they have.

Please improve the documentation!
thank you

Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.0-4-amd64

**Comment by alexr00** [comment]
The documentation is here: https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks
Please see the [tasks.json schema](https://code.visualstudio.com/docs/editor/tasks-appendix) and try using intellisense to see all the options for task groups.
