### ISSUE TITLE
Named exports importing not working consistently

### ISSUE THREAD

**Issue by jordyvandomselaar** [microsoft/vscode#73308]
Issue Type: <b>Bug</b>

When installing a package VSCode won't try importing named exports untill I've done so atleast once manually.

Is this intended behaviour?

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 5|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|1.3.0
vscode-custom-css|be5|3.0.4
vscode-intelephense-client|bme|1.0.14
scratchpads|bue|0.0.5
better-phpunit|cal|1.4.0
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.2.5
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.3
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|2.8.2
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|1.9.0
git-project-manager|fel|1.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-jest-runner|fir|0.3.4
flow-for-vscode|flo|1.1.1
code-runner|for|0.9.9
macros|ged|1.2.1
rest-client|hum|0.21.2
php-namespace-resolver|Meh|1.1.7
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.125
debugger-for-chrome|msj|4.11.3
php-docblocker|nei|1.8.0
react-proptypes-intellisense|OfH|1.0.3
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.5.0
laravel5-snippets|one|1.5.0
vscode-jest|Ort|2.9.2
material-icon-theme|PKi|3.7.0
text-power-tools|qcz|1.11.1
markdown-preview-theme-one-dark|rae|0.0.1
vscode-yaml|red|0.4.0
laravel-artisan|rya|0.0.25
code-settings-sync|Sha|3.2.9
mdx|sil|0.1.0
laravel-goto-controller|ste|0.0.7
vscode-laravel-assist|tia|0.1.6
vscode-markdown-link-suggestions|Tom|13.0.0
vscode-mdx-preview|xyc|0.1.5
vscode-surround|yat|1.0.2
markdown-all-in-one|yzh|2.3.1

(3 theme extensions excluded)

</details>

**Comment by jordyvandomselaar** [comment]
Another example;

I have 3 files in `/list`:

**index.tsx**

```tsx
import List from "./List";
import ListItem from "./ListItem";

export { List, ListItem };
```

**List.tsx**

```tsx
import styled from "styled-components";

const List = styled.ul`
  list-style: none;
`;

export default List;
```

**ListItem.tsx**

```tsx
import styled from "styled-components";

const ListItem = styled.li`
  padding: 10px 20px;
`;

export default ListItem;
```

Now, when typing `List` inside another component located at `/MenuBar/index.tsx` I expect VSCode to show a popup to import it which would insert something like this:

```tsx
import { List } from "../List";
```

Instead, when hitting `ctrl+space` I get

> No Suggestions.

**Comment by mjbvz** [comment]
Do you have a tsconfig and are all files part of this tsconfig? Run `TypeScript: Go to project configuration` from a typescript file in vscode to check

If you already have a config, please share it

**Comment by jordyvandomselaar** [comment]
Thanks for the reply @mjbvz! 

Everything is in the config, here it is;

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

**Comment by jordyvandomselaar** [comment]
![image](https://user-images.githubusercontent.com/12712484/57283418-6229b900-70af-11e9-8eba-171e90fa23ca.png)

As you can see, all the files in the example are in `src/`
