### ISSUE TITLE
Touch control does not work by default on Linux

### ISSUE THREAD

**Issue by carmenbianca** [microsoft/vscode#73305]
- VSCode Version: 1.33.1
- OS Version: Fedora 30

Steps to Reproduce:

1. Open vscode
2. Use your finger to touch on anything in the vscode window.
3. Nothing happens.

Does this issue occur when all extensions are disabled?: Yes

More info:

Launching vscode with `code --touch-events` enables touch controls.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by carmenbianca** [comment]
I use Fedora, so unfortunately the .deb doesn't work for me. Is there an .rpm available?

**Comment by bpasero** [comment]
https://az764295.vo.msecnd.net/exploration/39c4800ca7ffc78a6256428e51425332b3898117/code-exploration-1557124866.tar.gz

**Comment by carmenbianca** [comment]
In that version, clicking works, but scrolling does not.

When I run that version using `./code-exploration --touch-events`, both clicking and scrolling work.

When I run the live version using `code --touch-events`, both clicking and scrolling work.

**Comment by bpasero** [comment]
@deepak1556 thoughts?

**Comment by carmenbianca** [comment]
May this issue be re-opened?

**Comment by carmenbianca** [comment]
Fixed in 1.36.0
