### ISSUE TITLE
Allow for uninstalling extensions using the API

### ISSUE THREAD

**Issue by arnohovhannisyan** [microsoft/vscode#73309]
There is already a command for installing extensions (`workbench.extensions.installExtension`), and it would be really nice if there was also a command to uninstall extensions, like `workbench.extensions.uninstallExtension`. I'm currently working on a PR for code-settings-sync (https://github.com/shanalikhan/code-settings-sync/pull/859), and this is all we need to completely switch to using the API from the CLI.

**Comment by sandy081** [comment]
A command `workbench.extensions.uninstallExtension` to uninstall an extension

Usage:

`vscode.commands.executeCommand('workbench.extensions.uninstallExtension', 'extensionId');`
