### ISSUE TITLE
Upgrading a theme currently requires a window reload

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#73306]
If you publish an update to a theme, VS Code will download it automatically but not apply the changes until you do a full reload. There is also no button to reload the window in the extension viewlet.

**Comment by sandy081** [comment]
@aeschli Do you update the current theme when it (extension) is updated

**Comment by aeschli** [comment]
I added the code to reload the file once I get the extension update event.

But the extension viewlet requires a reload once it updates the extension.

**Comment by aeschli** [comment]
back to @sandy081

**Comment by sandy081** [comment]
This works now. Extension viewlet show reload action for theme extensions after getting updated.
