### ISSUE TITLE
Feedback Systen

### ISSUE THREAD

**Issue by zwenboy** [Microsoft/vscode#73307]
Issue Type: <b>Bug</b>

When I got to feedback you can choose how your experience was. Choosing happy face alows me to have 257 characters to type. By choosing sad face I am allowed to type 270 characters. I don't think this was on purpose?

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X4 635 Processor (4 x 2913)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.75GB (4.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3

</details>

**Comment by RMacfarlane** [comment]
Hey @zwenboy, this is actually intentional - in the happy face case we append " #HappyCoding" to the end of your feedback which you can submit to twitter.
