### ISSUE TITLE
Allow to open the same folder in multiple windows

### ISSUE THREAD

**Issue by danekan** [Microsoft/vscode#7330]
second window will not open same working folder as first window
- VSCode Version: 1.1.1 / also 1.2.0-insider 
- OS Version: 8.1

Steps to Reproduce:
1. Open first window and standard working folder.
2. File -> new window
3. Second window opens with blank workspace; attempt to select same working folder as first window. Folder does not open in second window.

**Comment by bpasero** [comment]
This is currently by design and was reported already.

**Comment by danekan** [comment]
I can work-around this by doing subst r: c:\profilefolder\ to open the second window w/ same folder/profile as first, but I don't really understand why this is by design--is there a feature I'm missing?  

How can I split the editor and have those windows not be side by side by rather actually take advantage of my screen resolution?  Also, since the profiles themselves are tied to the folder.  So, if you want different settings than default, you essentially have to set up a new profile for each directory the way this is designed now?

**Comment by codyrigney92** [comment]
We are looking for the same thing.  I'll try your workaround.

**Comment by factormystic** [comment]
In march, @weinand mentioned opening the same folder in multiple windows as a possible solution to https://github.com/Microsoft/vscode/issues/4507 (multiple debuggers in same project). I'm also surprised to hear that not being able to do this is "by design".

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
