### ISSUE TITLE
Command Prompt (cmd.exe) - Starts with no output on start after typing a character

### ISSUE THREAD

**Issue by nekobit1** [Microsoft/vscode#73313]
When using cmd.exe (Path: C:\Windows\System32\cmd.exe), when you open the integrated terminal, everything is fine until you type on character, then the ouput bugs out for a second. This isnt a huge problem, but still annoys me.

When i open the integrated terminal (notice the missing block cursor as indication of this bug possibly):
![image](https://user-images.githubusercontent.com/43082574/57201742-32719880-6f6b-11e9-8e91-c66b6d958f64.png)

After typing approximately 1 character:
![image](https://user-images.githubusercontent.com/43082574/57201771-7a90bb00-6f6b-11e9-802e-6c3aa4f94bc2.png)

\>inb4 use powershell, loser

- VSCode Version: 1.33.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. type "cls"
OR
1. run your command like normal, trigger your OCD instead

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by nekobit1** [comment]
Alright, thank you!
