### ISSUE TITLE
Workspace folders pointed to the same path, with individual ability to exclude files

### ISSUE THREAD

**Issue by dluc** [microsoft/vscode#73312]
When creating a workspace with multiple folders, it would be useful to have the ability to include the same path multiple times, with a customized view, e.g. allowing to exclude files on a folder basis.

For example:

```json
{
    "folders": [
        {
            "name": "view without FOO",
            "path": "my-folder",
            "files.exclude": {
                "**/FOO": true
            }
        },
        {
            "name": "view without BAR",
            "path": "my-folder",
            "files.exclude": {
                "**/BAR": true
            }
        }
    ],
    "settings": {
        "files.exclude": {
            "**/.git": true
        }
    }
}
```

This would allow using a single workspace for team members focused on different areas of a project, rather than defining a workspace for each role (PMs, designers, frontend devs, backend devs, doc writers, etc.). There are other scenarios, e.g. having 2 views for a React project, one with build output and node_modules, one without; for .NET devs one view with bin and obj, and one without; etc.

**Comment by eine** [comment]
#76904 is now a candidate for `Backlog`. @dluc, @HaaLeo I'd like you to please consider upvoting it.
