### ISSUE TITLE
Solarized light color scheme doesn't change color of `Run Tests` in status bar

### ISSUE THREAD

**Issue by paymog** [microsoft/vscode#73316]
- VSCode Version: 1.33.1 (1.33.1)
- OS Version: 10.14.4

Steps to Reproduce:

1. Install vscode as above
2. change theme to solarized light
3. open a python workspace with unit tests and discover the tests
4. notice that `Run Tests` in the status bar is green

![image](https://user-images.githubusercontent.com/1986950/57203788-eae02080-6fed-11e9-80d1-8392f3b0bcbf.png)

Does this issue occur when all extensions are disabled?: Yes/No
No, extensions are needed for python test discovery

**Comment by misolori** [comment]
This is an issue with the Python extension as they are setting this color (and it applies to all themes).

https://github.com/microsoft/vscode-python/blob/498279fcd421bd05892d7797a2562ac1a8a954b0/src/client/testing/display/main.ts#L85

Please file an issue with the [Python extension.](https://github.com/microsoft/vscode-python/)
