### ISSUE TITLE
Windows & Mac Support for Remote Development

### ISSUE THREAD

**Issue by nateman1352** [Microsoft/vscode#73314]
The new [remote development](https://code.visualstudio.com/blogs/2019/05/02/remote-development) feature currently only supports Linux as the remote system. Windows or Mac servers are currently not supported. This makes the remote development feature largely useless for the original use case of #5243, which involves remote access to a Windows system in an corporate environment.

For Windows, it seems reasonable to use SMB via something like [SysInternals PsExec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) over a corporate network or an SSH based mechanism for secure transport over the public Internet for cloud use cases (Windows 10 RS5 or later has an OpenSSH Server built in.) Having both options would be ideal.

For Mac, SSH is built in to the OS (under the name "Remote Login" in System Preferences->Sharing) and would be the obvious choice.

**Comment by RMacfarlane** [comment]
Hey @nateman1352, there are open feature requests for both of these:
https://github.com/Microsoft/vscode-remote-release/issues/24
https://github.com/Microsoft/vscode-remote-release/issues/25

Please go thumbs those up and add any additional feedback there. Thanks!
