### ISSUE TITLE
Renaming the directory when an opened file is not saved should ask for confirmation

### ISSUE THREAD

**Issue by zavr-1** [microsoft/vscode#73310]
- VSCode Version: Version 1.33.1 (1.33.1)

Steps to Reproduce:

1. create a file in dir/index.js
2. enter data, don't save
3. rename dir to dir2
4. loose data

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@zavr-1 that should not happen, can you tell the exact steps how to reproduce? e.g. is that file you create already on disk or not?

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/57209075-405d0300-6fd7-11e9-97ec-cb4ff2bc728b.gif)

**Comment by zavr-1** [comment]
@bpasero 
![abcd](https://user-images.githubusercontent.com/21156791/57209201-31c71980-6fe0-11e9-98ec-74d1047a77bc.gif)
i've tried in another project and it kept the content there's something edgey

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
