### ISSUE TITLE
activeTextEditor.selection.active.character occasionally returns 0 when it's not

### ISSUE THREAD

**Issue by randrade23** [microsoft/vscode#73327]
Issue Type: <b>Bug</b>

const editor = vscode.window.activeTextEditor;
const positionInLine = editor!.selection.active.character;

When debugging an extension, positionInLine will occasionally be 0, even when the text cursor is not at the start of a line and the window is focused. 

I have not been able to reproduce this reliably. It happens only occasionally. I noticed, however, that this happens more often if you set a breakpoint immediately after declaring positionInLine 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

</details>

**Comment by jrieken** [comment]
What does does `activeTextEditor.document.uri` read? Know that also output channels et al are editors and that the active editor might not be what you expect

**Comment by jrieken** [comment]
not actionable
