### ISSUE TITLE
colors in terminal

### ISSUE THREAD

**Issue by andrewufrank** [microsoft/vscode#73328]
The default setup for the terminal colors cannot be changed - and in my case are very unfortunate: much of the output is dark-blue which is not readable on a black background. 
I am working on Linux - Debian - Xfce; the default terminal color is indeed dark-blue for the terminal   for some elements, but I have changed this in the terminal preferences. Is vscode not reading thepreferences for the terminal when using the build in terminal? 
I have selected the internal terminal in setup, but switching to external has no effect in vscode. There are no other settings for the terminal color selection available. 

I am using vs code Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64

**Comment by Tyriar** [comment]
Change your theme to change the terminal colors.

You can also override themes by adding settings like so:

```
  "workbench.colorCustomizations": {
    "terminal.ansiBlue": "#0000ff"
  },
```

**Comment by andrewufrank** [comment]
Thank you for the information - but my issue was more concerned with the selection of the terminal as identified in `Terminal › External: Linux Exec
Customizes which terminal to run on Linux.` where a specific value seems to work (as I found since), but not the generic, indirect setting `x-terminal-emulator`.

**Comment by Tyriar** [comment]
All that does is launches an external terminal emulator, to customize that you should refer to its documentation. I think you might need an absolute path for this so `x-terminal-emulator` might not work.
