### ISSUE TITLE
Allow to open .code-workspace as a workspace file (file without name)

### ISSUE THREAD

**Issue by ypapouin** [microsoft/vscode#73326]
- VSCode Version:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a workspace and name it `.code-workspace` (no name before extension)
2. Close VSCode
3. Double-click on `.code-workspace`, VSCode is only opening the `.code-workspace` file in edit mode.
4. Close VSCode
5. Right-click on the project folder and "Open With Code"
6. Observe that no notification popup appears with the common message "This folder contains a workspace file 'workspace.code-workspace'. Do you want to open it?"

Rename `.code-workspace` to `workspace.code-workspace` and all is working correctly.
Since we will probably have only one `.code-workspace` per folder/project on most of use cases, VSCode should allow `.code-workspace`.

**Comment by bpasero** [comment]
If someone wants to look into this, I think it should not be too much of work.

//cc @aeschli if there are any concerns

**Comment by charlyx** [comment]
@bpasero I'm willing to give it 😄

**Comment by hwhung0111** [comment]
@bpasero  Are you still working on it?

**Comment by charlyx** [comment]
Sorry, I’ve been busy but I’m still willing to make it. I’ll try to work on it soon!

**Comment by 1138-4EB** [comment]
Possible duplicate #70915.

**Comment by 1138-4EB** [comment]
@bpsero, since this is discarded now, would you mind tagging it as `good first issue` so that potential contributors can more easily find it? https://github.com/microsoft/vscode/issues/73326#issuecomment-489975965
