### ISSUE TITLE
VSC uses full process time.

### ISSUE THREAD

**Issue by dslpp056193** [Microsoft/vscode#7332]
- VSCode Version: 1.2.0
- OS Version: windows 7 ultimate

Steps to Reproduce:

1. Open VSCode
2. Write issue, because VSC has used full process time in loading.

PC resources:
intel core 2 duo, 2.26GHz 2.27 GHz

Before this update (1.2.0) i haven't this problem.

**Comment by alexandrudima** [comment]
@dslpp056193 Lots of things happen when starting up VS Code and they take CPU time. What is the difference between the previous version? Is it taking longer to start up? Is it constantly using 100% CPU?

**Comment by dslpp056193** [comment]
Yestarday i removed 1.2 and installed 1.0.. 1.0 is working stable, but 1.2 version eats 99% CPU time on load, on opening and on save (on save ~60 CPU time).

_p.s.: sorry for my english_

**Comment by dbaeumer** [comment]
@dslpp056193 can you give 1.2.1 a try. We fixed issues around performance https://github.com/Microsoft/vscode/issues?q=milestone%3A%22June+13th+Stable+Recovery%22+is%3Aclosed

**Comment by dslpp056193** [comment]
All works, thanks, fine work!

**Comment by dbaeumer** [comment]
Closing then.
