### ISSUE TITLE
Microsoft .NET Core Debugger ？

### ISSUE THREAD

**Issue by molibeibei** [microsoft/vscode#73324]
Issue Type: <b>Bug</b>

You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.

VS Code version: VSCodium 1.33.1 (ac42eadd6845f13e09b29b992eff42d8bb7aa5c4, 2019-04-11T18:30:22.049Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
supersharp|cra|0.1.4
json-tools|eri|1.0.2
auto-using|Fud|0.7.8
csharpextensions|jch|1.3.0
csharpextensions|kre|1.3.0
csharpfixformat|Leo|0.0.81
atom-keybindings|ms-|3.0.6
csharp|ms-|1.19.0
Go|ms-|0.10.2
csharp-code-snippets|Som|0.0.1
json|Zai|1.0.1

</details>

**Comment by chrmarti** [comment]
Could you explain what your request is?
