### ISSUE TITLE
Performance shit with gpu enabled

### ISSUE THREAD

**Issue by Vlad412** [microsoft/vscode#73335]
Hello, sorry for salt but it's my

2nd attemt to submit performance issue, I'm using thinkpad T480 you have my config with report and on big projects (like normal web app) it's just impossible to work, but works pretty well when I launch vs code with  --disable-gpu.

I only 2 extensions : one dark and vetur. Performance slightly better without one dark but wtf I would like to use vs code with extensions and all and get normal perf, this laptop is pretty good and new and I just want to edit code nothing crazy, thanks for listening and for support have a nice day

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by jrieken** [comment]
not actionable
