### ISSUE TITLE
Doesn't support / in quick open

### ISSUE THREAD

**Issue by ensky** [microsoft/vscode#73331]
Issue Type: <b>Bug</b>

1. Ctrl + P to toggle quick open
2. enter xxx/
3. couldn't find files under xxx folder

Extension version: 0.34.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-143-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: build.fct|
|OS|Linux x64 4.4.0-143-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (24 x 2394)|
|Memory (System)|15.67GB (8.57GB free)|
|VM|0%|
</details>

**Comment by bpasero** [comment]
I cannot reproduce on Linux at least when trying without WSL setup:

![image](https://user-images.githubusercontent.com/900690/57217031-cf771480-6ff1-11e9-944d-037a500e520d.png)

**Comment by bpasero** [comment]
I still think this is WSL/remote specific, possibly some hardcoded path separator that causes this because on Windows we assume `/` to not be a path separator.

**Comment by bpasero** [comment]
I suspect a problem with the search service because on Windows without WSL I can type both `/` and `\` and see results.

**Comment by ensky** [comment]
It's likely not general vscode problem because I can quick open with '/' without remote plugin.

**Comment by roblourens** [comment]
Yeah this is true for all remotes from a windows client so it's probably the filter step on the client.
