### ISSUE TITLE
TS/JS basic extensions are running as workspace extensions

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#73336]
Due to their usage of jsonValidation, they are classified as workspace extensions.

**Comment by egamma** [comment]
One mitigation is to factor the json validation into its own extension, then only the json validation extension has to be a workspace extension.

//fyi @aeschli @sandy081

**Comment by sandy081** [comment]
Instead of creating its own extension, Why not moving json validation contributions to the language features extension?
