### ISSUE TITLE
Remote-SSH connecting stuck: "Confirming that {Host} is reachable..."

### ISSUE THREAD

**Issue by shanehou** [Microsoft/vscode#73337]
- VSCode Version:
Version: 1.34.0-insider (system setup)
Commit: 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9
Date: 2019-05-01T00:22:05.899Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
- OS Version:
Windows 10 1803

SSH config (example):
```
Host devhost
    User shanehou
    HostName 100.200.100.200
    Port 3456
```

Then I clicked to "Connect to Host in New Window", but it kept saying "Confirming that devhost is reachable..."

**Comment by shanehou** [comment]
Got it. Need to set `remote.SSH.showLoginTerminal` to `true`

**Comment by pc-robelbois** [comment]
@shanehou Thanks

IMO this should be yes by default, without @shanehou hint I would still be stuck.

**Comment by cljk** [comment]
Is there a possibility to set the password or copy and paste it?
I use a password manager and my passwords are kind of complex... and not typable manually...

**Comment by primoz-k** [comment]
> @shanehou Thanks
> 
> IMO this should be yes by default, without @shanehou hint I would still be stuck.

I agree, I thought there is something wrong with my connection configuration.

**Comment by GregWoods** [comment]
So glad I came across this. I agree it should be default to have the prompt come up when needed.
But as to saving passwords, most SSH clients don't allow this (or strongly discourage it) in favour of using SSH keys.
