### ISSUE TITLE
Ctrl click opens peek

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7333]
- Ctrl click on a class name, defined in another file
- Editor switches to that file, but opens the reference peek UI on top as well

**Comment by csholmq** [comment]
With multiple matches, user should be notified before jumping. Perhaps a drop down list?

I believe this is only true for functions. Variables does not present peek UI but just jumps directly to first match.

**Comment by jrieken** [comment]
@joaomoreno I cannot reproduce. Please give me proper steps and notice that incase of multiple definitions that's the designed behaviour.

**Comment by joaomoreno** [comment]
Yesterday it reproduced very clearly. I was about to close this since I can't reproduce today, until I was able to... just once, just now.

There is something about the combination of <kbd>Ctrl Click</kbd> and `Find all References` that triggers this behaviour, can't seem to quite put my finger on it.

**Comment by joaomoreno** [comment]
Closing as designed. Need a better way to solve that problem though.
