### ISSUE TITLE
Settings editor goes empty

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#73334]
1. Open Settings Editor
2. Search for `git`
3. Click the `Git` section in the TOC
4. Focus back into the search box and clear it

![image](https://user-images.githubusercontent.com/22350/57217376-bde23c80-6ff2-11e9-9396-dc4e7e4e2834.png)

**Comment by roblourens** [comment]
From https://github.com/Microsoft/vscode/issues/72778
