### ISSUE TITLE
External file changes only detected if file is open

### ISSUE THREAD

**Issue by randrade23** [microsoft/vscode#73342]
Issue Type: <b>Bug</b>

I am using the onDidChangeTextDocument event to catch changes to files in a workspace, however it only fires if changes are made inside VSCode or externally but to files that are open. It is not firing for files changed externally which are in the workspace, but are not open.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

</details>

**Comment by bpasero** [comment]
That is right because the document does not exist anymore when you close the last editor. @jrieken to confirm + close.
