### ISSUE TITLE
Find all references does not show references to imports

### ISSUE THREAD

**Issue by alvarorahul** [Microsoft/vscode#7334]
Version 1.2.0-insider
Commit 7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f
Date 2016-05-30T12:59:38.593Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Steps to Reproduce:

```
foo.ts
export enum X {  A, B, C}

bar.ts
import foo = require("foo");

module Main {
    import X = foo.X;
}
```

1.  Click on the word foo on line 1 of bar.ts
2. Press Shift + F12 to get all references

EXPECTED: it shows the import as an usage of foo
ACTUAL: it doesn't show any usage and seems like it is unused in bar.ts

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9018
