### ISSUE TITLE
Installing extension from extension page "Install" button keeps the notification baloon in bottom right

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#73341]
Issue Type: <b>Bug</b>

I noticed when I install extension by clicking on the green "Install" button from within the VScode extension page, as opposed to the "Would you like to install..." notification/chat bubble in the lower right corner of the editor, the chat bubble stays there, asking me if I want to install the extension I just installed.

Would be great if the state was in sync and the bubble would be dismissed when I installed the extension, no matter how.

<details>
<summary>Screenshot after installation</summary>
<img width="2032" alt="Screen Shot 2019-05-06 at 17 54 50" src="https://user-images.githubusercontent.com/67437/57221123-239ceb80-7028-11e9-9078-5305e376e4ac.png">

</details>

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
solargraph|cas|0.19.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.2
gitlens|eam|9.7.1
prettier-vscode|esb|1.9.0
rails-snippets|Hri|1.0.8
rest-client|hum|0.21.2
vscode-codemetrics|kis|1.18.0
vscode-language-babel|mgm|0.0.22
ruby-rubocop|mis|0.8.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
JavaScriptSnippets|nat|0.2.0
ruby|reb|0.22.3
code-settings-sync|Sha|3.2.9
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by skprabhanjan** [comment]
@sandy081 , I would like to try this , Some starter and code pointers would be helpful :)

**Comment by sandy081** [comment]
It depends on how @vfonic got this notification. @vfonic can you please let us know how you got this?

**Comment by vfonic** [comment]
It shouldn't depend on that.

I got it by clicking install button in VS Code Extension Marketplace
website, in the browser.

**Comment by sandy081** [comment]
@skprabhanjan This notification comes from here - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/extensions/node/extensionsWorkbenchService.ts#L1083

**Comment by skprabhanjan** [comment]
@sandy081 , I checked the code but just wanted to discuss on one thing .

Is that notification **needed** in the first place , clicking on install button on top will do the same job , Also removing that notification will keep the two scenarios  consistent and same (Normally opening that extension page and opening the extension page from browser)
We can remove the notification prompt to fix the inconsistency .

**Comment by skprabhanjan** [comment]
@sandy081 , were you able to look into this ?
I can remove the notification bubble and send a PR, please confirm :)

**Comment by sandy081** [comment]
@skprabhanjan Yeah it look unnecessary for me. Please remove it.
