### ISSUE TITLE
Debug Console won't auto scroll to end

### ISSUE THREAD

**Issue by julioct** [Microsoft/vscode#73349]
Issue Type: <b>Bug</b>

1. Create a new .net core app:
``` dotnet new webapi ```

2. Open the created project in VS Code and accept the prompt to add the required assets to build and debug the app.

3. Hit F5

![Scrolling issue](https://i.imgur.com/KIjxKdP.gif)

EXPECTED: The debug console continuously scrolls to the end with the "Application started. Press Ctrl+C to shut down." line focused shortly after debugging started.

ACTUAL: The debug console barely scrolls down to 1/4 of the window from the top. I have to manually scroll down to reach the end.

This started happening at some point after version 1.31.1 which is why I'm stuck in that version until a fix is provided.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (3.53GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.19.0

</details>

**Comment by isidorn** [comment]
Fixed in latest insiders
