### ISSUE TITLE
On restart/open of VSC it opens with older templates/editors not recent ones.

### ISSUE THREAD

**Issue by abhinashtripathy** [microsoft/vscode#73340]
Issue Type: <b>Bug</b>

On restart of Visual studio it opens with some other editors which are not my last used editors. The editors that opens on restart are old ones, everytime I have to update or choose the folder from my source project location to open in here.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|9.7.1
tslint|eg2|1.0.43
csharp|ms-|1.19.0
debugger-for-chrome|msj|4.11.3
typescript-hero|rbb|3.0.0
autoimport|ste|1.5.3

</details>

**Comment by bpasero** [comment]
@abhinashtripathy you are restarting Windows while VSCode is running right?

**Comment by abhinashtripathy** [comment]
@bpasero  No. Whenever I open or restart Visual Studio Code, it does not open with last opened editors. I think this is related to issue no. 15949. You can close this issue. Thanks.
