### ISSUE TITLE
Fishy code action sorting

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#73344]
I might be missing something but this looks fishy because the `SourceFixAll` is sorted to the front or end depending on where it occurs

https://github.com/Microsoft/vscode/blob/9ce42976fb1690c2cfdbc2a4a22dade51fc57657/src/vs/workbench/api/browser/mainThreadSaveParticipant.ts#L269-L274

**Comment by skprabhanjan** [comment]
@mjbvz , So what should ideally happen here ?
I can fix this but will need a little more information from you on this , Thanks :)

**Comment by mjbvz** [comment]
@skprabhanjan `fix all` code action should come before any other source actions. Here's an example test you can copy to test the fix: https://github.com/microsoft/vscode/blob/0e580b6ee39932b4b75e3ae70dda1928f313a1db/src/vs/editor/contrib/codeAction/test/codeAction.test.ts#L172

**Comment by skprabhanjan** [comment]
@mjbvz , I went through the code and I could not understand the functionality properly and therefore I have a clarification.
The point you made saying 

> `fix all` code action should come before any other source actions 

So should we correct that behaviour somewhere so that the code snippet @jrieken has pointed out works properly ? 
Can you please provide me a few more details code wise to fix this issue ?

**Comment by mjbvz** [comment]
Yes, the code actions returned from this function should always be sorted so that the `fixAll` comes first. In the tests, try creating a code action provider that returns multiple code actions in unsorted order (such as: [RefactorAction, SourceFixAllAction, ....]` ). Then confirm that `getCodeActions` returns the actions with the `SourceFixAllAction` first

The fix should be to adjust the [sort function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) here. I believe it just needs to return `1` in both cases but am not sure that is correct. The new tests should help verify your fix

**Comment by skprabhanjan** [comment]
@mjbvz , SourceFixAll is not being returned only in the actions
I created code action provides like this
`{ title: 'a', kind: CodeActionKind.QuickFix.value },
 { title: 'b', kind: CodeActionKind.SourceFixAll.value },
{ title: 'c', kind: CodeActionKind.Refactor.value },`

and then called getCodeActions like this

`const { actions } = await getCodeActions(model, new Range(1, 1, 2, 1), { type: 'auto', filter: { kind: CodeActionKind.SourceFixAll } }, CancellationToken.None);
assert.equal(actions.length, 1);
assert.strictEqual(actions[0].title, 'b'); `

actions.length is 0 , when i try filters for QuickFix and Refactor it will return 1 .
Without any filter it will return 2 actions (QuickFix and Refactor but not SourceFixAll)
Is there something i am doing wrong ?

**Comment by mjbvz** [comment]
`getCodeActions` does not return source actions by default. Try passing in the `includeSourceActions` flag to return them too:

```ts
const { actions } = await getCodeActions(model, new Range(1, 1, 2, 1), { type: 'auto', filter: { kind: CodeActionKind.SourceFixAll, includeSourceActions: true } }, CancellationToken.None);
```

I don't think we want to fix this in `codeActionsComparator`. The intent is that only the on save code actions are sorted this way. But that also means that you can't write a test in the `codeActions` folder for this. I don't think we have any tests for these yet

**Comment by skprabhanjan** [comment]
@mjbvz , Sorry my bad for missing `includeSourceActions`.
Confirming that SourceFixAll is not returned first  , in the example I have given above SourceFixAll is not returned first. ( I have written test to check if `getCodeActions` return SourceFixAll but to make that work we have to change `codeActionsComparator` )
So as you said it is not rite to write test in `codeActions` and it should work only for save code actions, 
Just changing the sort function for `codeActionsOnSave` and writing new tests somewhere else ?
so what do you suggest I should do next ?

**Comment by mjbvz** [comment]
Thank you for looking into this @skprabhanjan. I ultimately decided to look into this myself as it was more complicated that I originally thought and there are no tests for this code currently

**Comment by mjbvz** [comment]
To verify this:

1. Create extension that activates on `*` with the contnets:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(['markdown'], new Provider(), {
            providedCodeActionKinds: [
                vscode.CodeActionKind.SourceOrganizeImports,
                vscode.CodeActionKind.SourceFixAll,
            ]
        })
    )

    context.subscriptions.push(
        vscode.commands.registerCommand('example.organize', () => {
            console.log('organize');
        })
    )
    context.subscriptions.push(
        vscode.commands.registerCommand('example.fix', () => {
            console.log('fix');
        })
    )
}

class Provider implements vscode.CodeActionProvider {
    provideCodeActions(document: vscode.TextDocument, range: vscode.Range, context: vscode.CodeActionContext, token: vscode.CancellationToken): vscode.ProviderResult<vscode.CodeAction[]> {
        const organize = new vscode.CodeAction('organize', vscode.CodeActionKind.SourceOrganizeImports);
        organize.command = { title: 'or', command: 'example.organize' };

        const fix = new vscode.CodeAction('fix', vscode.CodeActionKind.SourceFixAll);
        fix.command = { title: 'or', command: 'example.fix' };

        return [
            organize,
            fix,
        ];
    }
}
```

1. Run extension and open folder
1. In workspace settings, add:

```json
"editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.organizeImports": true
}
```

1. Open md file
1. Make an edit and save

Confirm that `fix` is run (logged to output) before `organize`. Try messing around with the returned actions to confirm that fixes is always run first

**Comment by RMacfarlane** [comment]
Using the example extension provided, I still see "organize" printed before "fix"

**Comment by mjbvz** [comment]
Yes they seem to be sorted to be exactly reversed. Fix is simple and should be safe

**Comment by isidorn** [comment]
@mjbvz with the latest when running the extension you provided I get the following output in the Extension Host Output. I do not think this is expected, thus reopening and you can close again if I am mistaken.

```
2019-05-31 10:54:16.062] [exthost] [warning] isidor.june-ext -Code actions of kind 'source.fixAll 'requested but returned code action is of kind 'source.organizeImports'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
[2019-05-31 10:54:16.068] [exthost] [warning] isidor.june-ext -Code actions of kind 'source.organizeImports 'requested but returned code action is of kind 'source.fixAll'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
```

**Comment by mjbvz** [comment]
This is expected for that simple example. It does not check what type of code actions are being requested. This alert notifies extension authors that doing so is a good practice
