### ISSUE TITLE
terminal error in win10

### ISSUE THREAD

**Issue by InsaneBlue** [microsoft/vscode#73354]
Issue Type: <b>Bug</b>

The terminal does not display correctly  in win 10.
The first line does not show when the terminal is called at the first time, after you input some infomation, it turns normal.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.7.1
vscode-html-css|ecm|0.2.0
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.33.2
debugger-for-chrome|msj|4.11.3
vetur|oct|0.19.5
open-html-in-browser|pea|1.0.4
vscode-wechat|qin|0.0.6
minapp-vscode|qiu|1.13.3
vscode-icons|vsc|8.6.0

(1 theme extensions excluded)

</details>

**Comment by lukasskull** [comment]
![image](https://user-images.githubusercontent.com/50363767/57294867-34666380-70f3-11e9-9a88-40003d04d3f0.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
