### ISSUE TITLE
source control (side panel) highlight file when viewing changes

### ISSUE THREAD

**Issue by Ricard** [microsoft/vscode#73357]
When you select a file on source control changes list, it is highlighted and its diff opened. But the highlight is lost after focusing any other file and coming back to original (Ctrl + Tab)

**Would be very useful to highlight source control file when viewing/focusing its diff.**

You are awesome, thanks for all 👏

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/72973
