### ISSUE TITLE
Update workspace configuration before firing onDidChangeWorkspaceFolders event

### ISSUE THREAD

**Issue by jomiller** [microsoft/vscode#73353]
Starting from VS Code v1.32, when a workspace folder is opened or closed, the following sequence of events is visible to extensions:

1. Update `workspace.workspaceFolders`
2. Fire the `onDidChangeWorkspaceFolders` event
3. Update the workspace configuration (available through `workspace.getConfiguration()`)
4. Fire the `onDidChangeConfiguration` event

I would like step 3 to occur before step 2, so that the new workspace configuration is available to subscribers to the `onDidChangeWorkspaceFolders` event.

**Comment by sandy081** [comment]
@jomiller I see your request is similar to #66246. Can you please go through it and see if [comment](https://github.com/microsoft/vscode/issues/66246#issuecomment-454441345) helps you?

**Comment by jomiller** [comment]
@sandy081 , yes I'd implemented the caching solution as noted in #66246, and it worked until VS Code v1.32. 

> But I think you can fix it by caching the configuration on your side. Revalidate it when workspace folders or configuration change.

In my `onDidChangeWorkspaceFolders` subscriber, I cache the workspace configuration for the newly opened folders. In my `onDidChangeConfiguration` subscriber, I read the new configuration, and compare it against the cached configuration.

Since VS Code v1.32, the new workspace configuration is not available to `onDidChangeWorkspaceFolders` subscribers. So my caching step is broken unless I insert a workaround like awaiting on a Promise to delay execution of the caching step until after the workspace configuration has become available.

**Comment by sandy081** [comment]
@jomiller You are right, there is a configuration change event before folder change event. But configuration is not updated. Will investigate.

**Comment by sandy081** [comment]
I was wrong, configuration is up to date when there is a change to workspace folder. Can you please provide sample code if you are seeing otherwise?

**Comment by jomiller** [comment]
I've reproduced the issue in a simple test extension in [issue_73353_test.zip](https://github.com/microsoft/vscode/files/3163378/issue_73353_test.zip). Start this extension in the VS Code debugger, and it will print the following to the console:

    Before await
    Folder URI: file:///home/jonathan/Downloads/code/temp/test1, test config: foo
    Folder URI: file:///home/jonathan/Downloads/code/temp/test2, test config:
    After await
    Folder URI: file:///home/jonathan/Downloads/code/temp/test1, test config: foo
    Folder URI: file:///home/jonathan/Downloads/code/temp/test2, test config: bar

These messages are printed when the `test2` folder is added, and the `onDidChangeWorkspaceFolders` subscriber is called. As you can see, the `test.config` setting is only available for the `test2` folder after awaiting on a Promise. The configuration was not immediately available to the subscriber.

**Comment by jomiller** [comment]
@sandy081 , were you able to reproduce the issue with my sample code?

**Comment by jomiller** [comment]
@sandy081 , can we at least remove the `needs more info` label now?

**Comment by jomiller** [comment]
@sandy081 , just a reminder about this issue. I believe it's a bug, and it's still present in VS Code 1.38.1. Thanks.

**Comment by sandy081** [comment]
Assigning to November for investigation
