### ISSUE TITLE
Watch tasks not working on Windows version 1903 with terminal.integrated.windowsEnableConpty set to true

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#73351]
Steps to reproduce:

- clone https://github.com/Microsoft/vscode-eslint.git
- open a terminal
- Debug viewlet
- Launch client
- Observe that building never finishes
- Now switch the terminal to the npm: watch task

Observe: building finished. Looks like the terminal is not delivering any output as long as the view is not visible.

**Comment by alexr00** [comment]
@Tyriar are there any differences on when onLineData occurs in the terminal with conpty?

**Comment by sbatten** [comment]
discovered a new issue https://github.com/microsoft/vscode/issues/73555
