### ISSUE TITLE
Each line of output shifts in relations to the previous one

### ISSUE THREAD

**Issue by alfredmyers** [microsoft/vscode#73356]
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04.1 LTS (WSL)

Ubuntu on WSL:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Code:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. On a Windows 10 box, open a WSL/Ubuntu terminal (doesn't matter if from within Code's terminal or directly from Windows.
2. run 

```bash
code --list-extensions
```

Each line appears shifted in relation to the previous one. It seems to be an issue with the difference in line endings between Windows and Linux.

```shell
DavidAnson.vscode-markdownlint
                              docsmsft.docs-article-templates
                                                             docsmsft.docs-markdown
                                                                                   docsmsft.docs-preview
                                                                                                        EditorConfig.EditorConfig
                                                                                                                                 GitHub.vscode-pull-request-github
                             ms-azuretools.vscode-azureappservice
                                                                 ms-azuretools.vscode-azurefunctions
                                                                                                    ms-azuretools.vscode-azurestorage                                                                                                                                    ms-azuretools.vscode-cosmosdb
                            ms-mssql.mssql
                                          ms-vscode.azure-account
                                                                 ms-vscode.azurecli
                                                                                   ms-vscode.cpptools
                                                                                                     ms-vscode.csharp
```

------
Edited to add:

Things work just fine on:
- Ubuntu 18.04VM;
- PowerShell on Windows
- Windows Command Prompt (cmd.exe)

**Comment by Tyriar** [comment]
Can repro in both external WSL terminal and integrated. It also happens with --help:

<img width="979" alt="Screen Shot 2019-05-10 at 8 10 05 PM" src="https://user-images.githubusercontent.com/2193314/57564383-a04d0400-735f-11e9-8c73-348b67b9a919.png">

@octref I think you saw this recently. FYI @aeschli

**Comment by Tyriar** [comment]
I can no longer reproduce.
