### ISSUE TITLE
JSDoc Inteli-sense quirks for namepath tildes and @scoped module names

### ISSUE THREAD

**Issue by Codelica** [microsoft/vscode#73363]
- VSCode Version: 1.33.1
- OS Version: MacOS 10.14.4

It seems that the tilde (~) [JSDoc namepath](http://usejsdoc.org/about-namepaths.html) character gets parsed as a strikethrough when two of them wrap words.  Also `@scoped` module names seem to get parsed unique JSDoc entities. For example, this gets generated:

![vscode-intel](https://user-images.githubusercontent.com/386101/57242104-d9981380-6fef-11e9-9aaf-72c75952f085.png)

From:

![jsdoc-def](https://user-images.githubusercontent.com/386101/57242109-df8df480-6fef-11e9-81fb-6ed6f04f05ec.png)

Seems to parse fine with other consumers like jsdoc-to-markdown.

Steps to Reproduce:

1. Include a full JSDoc namepath with two tildes wrapping words and a scoped namespace for the module. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by Codelica** [comment]
No problem, sorry about that.  

That function has the following JSDoc:

```js
  /**
   * Add a Websocket listener at a specified path
   * @param {object|string} [options] Websocket configuration options
   * @param {string} [options.path=/] Path to offer Websocket at
   * @param {boolean} [options.parseJson=false] Automatically JSON message bodies
   * @param {string} [options.logName] NodeFuel log name/id to use
   * @param {string} [options.logLabel] NodeFuel log label to use
   * @returns {module:@nodefuel/web~Webserver~wsServer} Websocket server object
   */
  addWebsocket(options='/') {
...
```
With that return referencing something that is defined in an `@typedef`. Not sure if that matters.

```js
    /**
     * A Websocket service endpoint (extends WS Server instance)
     * @typedef {object} module:@nodefuel/web~Webserver~wsServer
     */
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/31298 to track root cause of this upstream
