### ISSUE TITLE
find/replace "Find in selection" is disabled when only one line selected

### ISSUE THREAD

**Issue by mjohnsonengr** [Microsoft/vscode#7336]
- VSCode Version:1.2.0
- OS Version:Windows 10

Steps to Reproduce:
1. Use Ctrl+F or Ctrl+H to run the Find or Replace commands
2. Select something on one line.
   The "Find in selection" toggle is disabled:
   ![image](https://cloud.githubusercontent.com/assets/7274059/15865175/0329d804-2c97-11e6-9cc6-aa9d0d4105db.png)

_Note: it works when selecting multiple lines, but the replacement does not adhere to the selection, but rather the lines selected; e.g. if you select the first half of a line, the replacement will replace parts in the entire line_

**Comment by mjohnsonengr** [comment]
This may be considered a duplicate of #5239 actually

**Comment by alexandrudima** [comment]
Fixed via #15566

**Comment by BillDenton** [comment]
Verified fixed in 1.10.1
