### ISSUE TITLE
Unable to type in the text editor

### ISSUE THREAD

**Issue by jaimealc** [microsoft/vscode#73369]
Issue Type: <b>Bug</b>

After certain time I am unable to type on the text editor. Just after a few minutes typing is possible again. No bugging session active, tried to kill terminal window, etc. 

Editing in Phython.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
python|ms-|2019.4.12954
cpptools|ms-|0.22.1
csharp|ms-|1.19.0
vim|vsc|1.7.1

</details>

**Comment by Tyriar** [comment]
Does this happen when you never launch a terminal?

**Comment by jaimealc** [comment]
Hi! 

It happens after I run a python file (not debugging it). Somehow it gets stuck somewhere.. 

Best, 
Jaime
