### ISSUE TITLE
Source Control icon showing changes for higher folder.

### ISSUE THREAD

**Issue by akulbe** [microsoft/vscode#73364]
Issue Type: <b>Bug</b>

"Source Control" is showing 3K+ changes. This seems odd because there's only a single file in the repo I have open.

I have ~/Code/local_ansible/scratch_project/ open in Code. It has a single README file in it.

What "Source Control" reflects is everything under ~/Code.

VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:21:48.884Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vagrant|bbe|0.5.0
inspec|bur|0.5.2
bracket-pair-colorizer|Coe|1.0.61
transformer|dak|1.6.0
vscode-dash|dee|2.1.0
ansible-vault|dho|0.1.3
docs-yaml|doc|0.2.1
vscode-diff|fab|1.4.0
gc-excelviewer|Gra|2.1.32
ruby-linter|hoo|1.0.0
vscode-rust|kal|0.4.2
chat|kar|0.15.0
sftp|lix|1.12.4
VS-code-vagrantfile|mar|0.0.7
terraform|mau|1.3.11
vscode-rufo|mbe|0.1.1
prettify-json|moh|0.0.3
vscode-azurefunctions|ms-|0.17.0
vscode-azureterraform|ms-|0.2.3
python|ms-|2019.4.12954
remote-containers|ms-|0.48.0
remote-ssh|ms-|0.35.0
remote-ssh-edit|ms-|0.34.0
remote-ssh-explorer|ms-|0.34.0
remote-wsl|ms-|0.32.0
vscode-remote-extensionpack|ms-|0.12.0
azure-account|ms-|0.8.2
azurecli|ms-|0.4.5
Go|ms-|0.10.2
powershell|ms-|1.12.1
vsliveshare|ms-|1.0.125
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.2.12
indent-rainbow|ode|7.4.0
chef|Pen|0.7.1
vscode-docker|Pet|0.6.2
ruby|reb|0.22.3
vscode-yaml|red|0.4.0
rust|rus|0.6.1
code-settings-sync|Sha|3.2.9
vscode-nginx|sha|0.6.0
fish-vscode|sky|0.2.1
vscode-autohotkey|sle|0.2.2
vscode-icons|vsc|8.6.0
vscode-ansible|vsc|0.5.2
propertylist|zho|0.0.2
azure-rest-for-ansible|zik|0.0.18
vsc-docker|Zim|0.34.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
You have initialized a git repo in `~/Code`. If that was a mistake, remove the `~/Code/.git` folder.
