### ISSUE TITLE
Does Peek Reference only search opened tabs?

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#73375]
Maybe I missed something obvious, but when I use `Shift-F12` to peek reference, files in the workspace that are not currently open won't be searched. In other words, the result of `shift-F12` is different every time based on what tabs I have opened. If I only have one tab open, I won't get any result, unless my function definition and function calls are in the same file.

Is this the intended behavior? I think it kind of defeats the purpose. Supposedly, Peek Reference should answer the question "I wonder which files imported this function?" 

By the way, if I press `Shift-F12` on a reference, it'll always be able to find its definition even if the definition is not open, but it doesn't work the other way around - if I presss `Shift-F12` on a definition, it'll only find references that are inside open tabs.

**Comment by ZYinMD** [comment]
I'm happy to provide sample code files if needed.

**Comment by roblourens** [comment]
What language?

**Comment by ZYinMD** [comment]
@roblourens JavaScript

**Comment by mjbvz** [comment]
@ZYinMD If you want references to look at all js files in your project, not just opened ones, you need to create a [jsconfig](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson)
