### ISSUE TITLE
settings Pane doesn't capitalize settings correctly

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#73374]
- VSCode Version: 1.34.0-insiders
- OS Version: macOS

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/2644648/57262163-cf8e0900-701f-11e9-9ce4-629ab431bbf6.png)

See how the first "Powershell" only has the `P` capitalized and the second "Power Shell" has a space?

This is, I'm guessing, because the first "Powershell" is all lowercase and the second "Power Shell" is camelCase in the setting:
```
powershell.powerShellExePath
```

How can I get the desired casing of "PowerShell"?

**Comment by roblourens** [comment]
Right now we don't give extensions any control over the formatting of this label. I have some formatting for proper nouns, I can try to fix PowerShell the same way.

**Comment by TylerLeonhardt** [comment]
Thanks @roblourens!
