### ISSUE TITLE
vs code using too much memory

### ISSUE THREAD

**Issue by martinsnelson** [microsoft/vscode#73384]
vs code using too much memory 2 gb
just to stay open with nothing

**Comment by zizifn** [comment]
Maybe some of cause by Extensions, Try open "help"->"Open Process Explorer"?

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by jrieken** [comment]
not actionable
