### ISSUE TITLE
source control providers: can not drag the border to lengthen the vertical size

### ISSUE THREAD

**Issue by Silent47** [microsoft/vscode#73385]
requirement: show more items in the view.

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Please explain some more about what you are looking for

**Comment by Silent47** [comment]
![image](https://user-images.githubusercontent.com/12785155/57272748-8d200700-70c7-11e9-9073-4efd211baf7e.png)

I just want to show all items without scrolling.

**Comment by joaomoreno** [comment]
Set `"scm.providers.visible": 0`.

**Comment by Silent47** [comment]
Thanks. It works.
