### ISSUE TITLE
Allow to open all files of a folder when dropping it into editor area

### ISSUE THREAD

**Issue by DarkLite1** [microsoft/vscode#73388]
It would be great if one could drag a folder from the `Explorer` to the `Editor` pane. When this happens VS Code should try to open all files in the folder, instead of displaying the error message `Unable to open 'Folder name': File is a directory`.

In the example below I wanted to open all files in the folder `Home drives quota`. So I dragged the folder `Home drives quota` to the editor on the right and the pop-up came. 

![image](https://user-images.githubusercontent.com/10828570/57277678-f04c7200-70a4-11e9-9cf5-4b2089cf3e6e.png)

**Comment by isidorn** [comment]
This is a fair feature request.
Leaving it open and if more people request it we can implement it.
fyi @bpasero

**Comment by daniandl** [comment]
Has anyone found an extension that achieves this? Would be a very useful feature :)

**Comment by DarkLite1** [comment]
I think this one should stay open. It would be of great help and I'm sure others agree. Can you reconsider please?

**Comment by isidorn** [comment]
Sure I can reopen, however we do not plan to tackle this in the near future.

**Comment by Croccifixio** [comment]
For anyone coming across this issue, there is an extension that provides similar functionality: [Open Multiple Files](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-multiple-files&ssr=false#overview).

It modifies the context menu, allowing you to right click on a folder in the `Explorer` and select `Open Multiple Files`.
