### ISSUE TITLE
Blurry font in title bar(not always, but often) in 2k display

### ISSUE THREAD

**Issue by wlchn** [microsoft/vscode#73389]
Software
- VSCode Version: 1.33.1
- OS Version: 10.14.3

Hardware
- 2K Display DELL U2713HM: default 2560*1440
- MacBook Pro (15-inch, 2017)

Look below two screenshots title bar, Font `event.go - kubernetes` in the title bar(not the tab)  is evident blurry. `qos.go - kubernetes` is not blurry. (This is display on dell 2k display, on mac default is fine)

![Screen Shot 2019-05-07 at 2 54 45 PM](https://user-images.githubusercontent.com/4652410/57278058-222afc00-70d8-11e9-8ee2-2fe7e3126ead.png)
![Screen Shot 2019-05-07 at 2 54 08 PM](https://user-images.githubusercontent.com/4652410/57278086-340c9f00-70d8-11e9-9749-ece6622ff07f.png)

**Comment by wlchn** [comment]
I mean font in the `title bar` not the tabs.
It still exists when I disable all extensions and themes.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by wlchn** [comment]
@bpasero Everything looks fine in the exploration build as far as I trying it. Awesome work!
