### ISSUE TITLE
Remote-SSH not working

### ISSUE THREAD

**Issue by Wayne-Shen** [microsoft/vscode#73382]
- VSCode Version:1.34.0-insider
- OS Version:macOS 10.14.4

When I am trying to connect to my centos vm on Azure, it always failed because of following error:

- Could not establish tunnel to "azure-centos" (Max wait time exhausted).
- Tunnel(34311) stderr: Permission denied, please try again.

I already add inbound rule for port 22 and 34311.

The full log can be found below:

```
SSH Resolver called for "ssh-remote+azure-centos"
SSH Resolver called for host: azure-centos
Setting up SSH remote "azure-centos"
Using commit id "daf71423252a707b8e396e8afa8102b717f8213b" and quality "insider" for server
Install and start server if needed
> Password: 
> 
> Last failed login: Tue May  7 03:14:35 UTC 2019 from myipaddress on ssh:notty
> There were 11 failed login attempts since the last successful login.
> bash: no job control in this shell
> Found existing installation...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> bf252f93-b071-4a6b-9b9b-997c40d949da==34311==
"install" terminal command done
Received install output: bf252f93-b071-4a6b-9b9b-997c40d949da==34311==
Server is listening on port 34311
Spawning tunnel with: ssh  azure-centos -N -L localhost:62761:localhost:34311
Spawned SSH tunnel between local port 62761 and remote port 34311
Waiting for ssh tunnel to be ready
Could not establish tunnel to "azure-centos" (Max wait time exhausted).
Could not establish tunnel to "azure-centos" (Max wait time exhausted).
Tunnel(34311) stderr: Permission denied, please try again.

Tunnel(34311) stderr: Permission denied, please try again.

Tunnel(34311) stderr: Received disconnect from myserver port 22:2: Too many authentication failures
Disconnected from myserver port 22
```

**Comment by liugangtaotie** [comment]
you'd better change the ssh config file in your Azure ,so you do this as following：
![WechatIMG31](https://user-images.githubusercontent.com/22477383/57282256-42aa8480-70df-11e9-837f-6747df93a716.jpeg)
![WechatIMG32](https://user-images.githubusercontent.com/22477383/57282257-43431b00-70df-11e9-9e7a-b5660f5eaa7f.jpeg)

**Comment by csesivakumar** [comment]
I'm getting the same issue, connecting to remote server using password.

ssh config:

Host name
    HostName XXXX
    User XXXX


SSH Resolver called for host: AIA-Qira
Setting up SSH remote "XXXX"
Using commit id "daf71423252a707b8e396e8afa8102b717f8213b" and quality "insider" for server
Install and start server if needed
> user@xx.x.x.xx's password: 
> 
> Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-47-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  * Ubuntu's Kubernetes 1.14 distributions can bypass Docker and use containerd
>    directly, see https://bit.ly/ubuntu-containerd or try it now with
> 
>      snap install microk8s --classic
> 
>  * Canonical Livepatch is available for installation.
>    - Reduce system reboots and improve kernel security. Activate at:
>      https://ubuntu.com/livepatch
> 
> 384 packages can be updated.
> 13 updates are security updates.
> 
> bash: cannot set terminal process group (25365): Inappropriate ioctl for device
> bash: no job control in this shell
> Found existing installation...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> 4717a29d-8a80-43b2-811f-f1636f283f6c==42687==
"install" terminal command done
Received install output: 4717a29d-8a80-43b2-811f-f1636f283f6c==42687==
Server is listening on port 42687
Spawning tunnel with: ssh  XXXX -N -L localhost:50240:localhost:42687
Spawned SSH tunnel between local port 50240 and remote port 42687
Waiting for ssh tunnel to be ready
Tunnel(42687) stderr: Permission denied, please try again.

Tunnel(42687) stderr: Permission denied, please try again.

Tunnel(42687) stderr: XXXX@XX.X.X.XX: Permission denied (publickey,password).

Could not establish tunnel to "XXXX" (Max wait time exhausted).
Could not establish tunnel to "XXXX" (Max wait time exhausted).

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/75

Please try: https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods

**Comment by changxw** [comment]
settings.json
+"remote.SSH.showLoginTerminal": true
