### ISSUE TITLE
Remember settings in Search

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#73392]
![Code_2019-05-07_03-16-33](https://user-images.githubusercontent.com/206498/57288391-9a60d580-7076-11e9-8d02-7e70a8a75673.jpg)

For instance, I often have to change the "files to include" input to narrow the search to different parts of my codebase. The problem is that I don't remember the paths very well so I have to check, and then type them. Would be much better if it remembers recent paths I've typed and let me select them easily. This can also apply to the other fields.

**Comment by roblourens** [comment]
You can navigate history in these fields with the up/down arrow keys.
