### ISSUE TITLE
NodeJS 10 with Visual Studio 2015 getting [DEP0062] DeprecationWarning:

### ISSUE THREAD

**Issue by debasissahu** [microsoft/vscode#73399]
I have upgrade the NodeJS 7 to 10. And now for testing purpose I'm trying to create a basic 'Hello World' web app with NodeJS v10.15.3 using Visual Studio 2015. See the below warning.

I am not able to run my previous app as well !!

![Error](https://user-images.githubusercontent.com/46349396/57293157-81d9d500-70e1-11e9-8ff2-e329f33dd000.PNG)

**Comment by isidorn** [comment]
This repository is for visual studio code, not for visual studio 2015.

**Comment by debasissahu** [comment]
Sorry for that!
Thank you very much.
