### ISSUE TITLE
Terminal find widget actions should be disabled when input is invalid

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#73396]
Related to https://github.com/microsoft/vscode/issues/59378

1. Search for regex expression in Terminal
2. Type `(`

The previous/next actions should be disabled since the input is invalid.

![image](https://user-images.githubusercontent.com/22350/57290717-42e65800-70be-11e9-987d-a36a869a7477.png)

**Comment by skprabhanjan** [comment]
@Tyriar , I tried fixing this and here is what I could do

- `_updateButtons()` in `findWidget.ts` is the function which handles this in normal search
- This is not replicated in `simpleFindWidget.ts` , so we have to do this
- In the newly added try catch block for RegEx I am trying to do` setEnabled(false)` on the two buttons in **catch**, but the changes are not reflected ( if i try calling` focus()` on the buttons it works)
- Also when no search input matches we are not disabling the next and forward button and we are not showing "No Results Found" ( **Condition** in normal search is 		`this._prevBtn.setEnabled(this._isVisible && findInputIsNonEmpty && matchesCount);` )


Please help me on this and let me know how to proceed.

**Comment by Tyriar** [comment]
@skprabhanjan I think copying what findWidget does with its `_updateButtons` is probably the right approach. /cc @cleidigh

**Comment by skprabhanjan** [comment]
> @skprabhanjan I think copying what findWidget does with its `_updateButtons` is probably the right approach. /cc @cleidigh

So that means we should also handle the case when there is no match for the input and show "No Results" similar to findWidget ?
In that case this fix will in a way look similar to the normal search or should we just handle this regex error part similar to `_updateButtons` ?

**Comment by Tyriar** [comment]
@skprabhanjan that would be good too, just make sure it works in the webview as well since the simple find widget is shared there.

**Comment by skprabhanjan** [comment]
@Tyriar , There is already a PR to fix (I think it still needs few changes ) , I have not yet finished my changes based on our conversation to keep it similar to `_updateButtons` functionality. 
My changes are similar to the current PR but I am following `FindWidget` standards.
Please let me know if I have to continue working on this or not ?
Thanks :)
