### ISSUE TITLE
Intellisense issue HELP!

### ISSUE THREAD

**Issue by hamzazarki** [microsoft/vscode#73395]
Issue Type: <b>Bug</b>

Hello,

I've installed VS code the latest version for the first time but the intellisense is not working , whether i type the code in HTML or CSS , it's not colored and no suggestion if i click on the pattern CTRL+ space .

could you please help me in this matter ?

Regards,

Hamza ZARKI

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (6.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
namespace|adr|1.1.0
vscode-intelephense-client|bme|1.0.14
scss-block-comments|cha|0.0.5
npm-intellisense|chr|1.3.0
vscode-html-css|ecm|0.2.0
php-intellisense|fel|2.3.10
extbundles-csharp|Fel|2.0.0
cshtml|fir|0.1.3
cshtml-tm|fir|1.0.0
auto-using|Fud|0.7.8
html-slim-scss-css-class-completion|gen|1.5.14
csharpextensions|jch|1.3.0
snippetica-csharp|jos|0.9.1
docomment|k--|0.1.6
csharpextensions|kre|1.3.0
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.2.1
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.14.0
vscode-kubernetes-tools|ms-|0.1.18
azure-account|ms-|0.8.2
csharp|ms-|1.19.0
team|ms-|1.149.2
scss-generator|nat|1.2.9
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.23.0
vscode-scss-formatter|sib|1.4.1
csharp-code-snippets|Som|0.0.1
javascript-typescript|sou|0.0.7
html-preview-vscode|tht|0.2.5
msbuild-project-tools|tin|0.2.54
rf-intellisense|Tom|2.5.0
vscodeintellicode|Vis|1.1.6
html-css-class-completion|Zig|1.18.0

</details>

**Comment by garyng** [comment]
Did you change the language mode?
Press `Ctrl + Shift + P` then type `Change Language Mode`. Choose your target language there.

**Comment by hamzazarki** [comment]
Thank you very much , it' working fine now after i've changed Language Mode

**Comment by chrmarti** [comment]
Does this reproduce with extensions disabled? (`F1` > `Developer: Reload Window With Extensions Disabled`)

**Comment by hamzazarki** [comment]
Hello Chris ,
The problem has been resolved , i didn't chose the laguage .

regards,

**Comment by chrmarti** [comment]
Thanks.
