### ISSUE TITLE
Request toggle for bottom-docked view to be side-docked or a column

### ISSUE THREAD

**Issue by JVimes** [Microsoft/vscode#7339]
It would be nice if the bottom-docked pane (integrated terminal, Output view, etc.) could optionally appear as a column alongside the editors, instead of docked to the bottom. My team has a command-line test watcher and node server that we keep an eye on while developing. Our terminal output tends to be tall and narrow. A column view or side-docked view would fit better and not cover vertical space of the editors.

**Comment by bgashler1** [comment]
#2806 duplicate
