### ISSUE TITLE
Integrated Terminal gets blocked working with git

### ISSUE THREAD

**Issue by rushmata** [microsoft/vscode#73398]
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Click on View --> Terminal
2. at first you see blank terminal
3. Click return key then you are able to see that cursor
4. just try a git branch from a git repository path 
5. you'll get blocked that terminal, you have to open a new one to carry on working

Does this issue occur when all extensions are disabled?: Yes

**Comment by rushmata** [comment]
![image](https://user-images.githubusercontent.com/8111571/57292149-62cb4b00-70c1-11e9-97af-838a74a33d9c.png)

**Comment by garyng** [comment]
Probably need more information. Like
1. what is the terminal inside vscode you are using? Seems like `powershell` to me. Sometimes powershell need time to launch.
1. can you see the terminal prompt after launching a new terminal? 
1. does the same command block if you use terminal outside of vscode?
1. ...

**Comment by rushmata** [comment]
1. That happen with `powershell` and also with `git console` even waiting for a longer,  just try to run `git branch` it get blocked.
2. the same behaviour opening a new terminal
3. Not at all. Windows Cmd works perfectly

**Comment by Tyriar** [comment]
The blank terminal issue is https://github.com/Microsoft/vscode/issues/57803

What do you mean by blocked? The terminal just doesn't work anymore? Can you show a screenshot in this state?

**Comment by rushmata** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/8111571/57618304-52184a80-7583-11e9-96ad-bab599ed33b8.png)

after run git branch it gets blocked as shown, i have to open a new terminal to get it running again.
