### ISSUE TITLE
Bash

### ISSUE THREAD

**Issue by Hoseinkangavarnazari** [microsoft/vscode#73394]
Issue Type: <b>Bug</b>

clear command doesn't work in bash terminal of visual code studio

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.78GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
arepl|alm|1.0.14
vscode-eslint|dba|1.8.2
jquerysnippets|don|0.0.1
eppz-code|epp|1.2.41
vsc-material-theme|Equ|2.8.2
easy-icons|jam|0.3.1
code-beautifier|mic|2.2.1
prettify-json|moh|0.0.3
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
debugger-for-chrome|msj|4.11.3
vscode-wakatime|Wak|2.0.9

(16 theme extensions excluded)

</details>

**Comment by tristan957** [comment]
For reference, I cannot reproduce on 1.33.1 macOS 1.14.4

**Comment by Tyriar** [comment]
Can you elaborate on what running `clear` does for you?

**Comment by bjubes** [comment]
I also am experiencing this. I found a gif that shows the problem from #33730

![gif of problem](https://user-images.githubusercontent.com/3108592/30512331-684bbade-9aed-11e7-863e-fb627ba53dbb.gif)
