### ISSUE TITLE
Search within search

### ISSUE THREAD

**Issue by tojamrok** [microsoft/vscode#73390]
There are two searches: 

- one with Ctrl+P can search for file names and file paths with a fuzzy match (typing "blok" would find "blocker.cpp") and updates with every key stroke,

- other with Ctrl+Shift+F can search with regexp for text inside files, you can also define files to include and exclude, executed after hitting <enter> key.

It would be nice to be able to first do the regexp search executed on <enter> key;  and then do the fuzzy file name search updated with every key stroke, which would filter the results of the first search.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/19940
