### ISSUE TITLE
search.exclude in settings is invalid now.

### ISSUE THREAD

**Issue by yanhuiinf** [microsoft/vscode#73391]
Issue Type: <b>Bug</b>

I added a exclude path in search.exclude, but it still occurred in search results.The same path in in files.exclude is valid.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

**Comment by chrmarti** [comment]
Matches in currently open files are always shown. Would that explain what you see?

**Comment by yanhuiinf** [comment]
On the results in search view, The tip said: "30 results in 18 files - exclude settings and ignore files are disabled", but I can't find where can I set the exclude settings to enable.

**Comment by yanhuiinf** [comment]
By googling the tip "exclude settings and ignore files are disabled", the first result is #64561. So the switch is the gear symbol in the "files to exclude" box of search view. You buddy are too subtle.
I think it's better to add an option in settings.
