### ISSUE TITLE
vscode doesn't show images on markdown previewer over proxy

### ISSUE THREAD

**Issue by mattn** [Microsoft/vscode#734]
```
![](http://example.com/image.png
```
This always

![](http://go-gyazo.appspot.com/14b35d7b295b1231.png)

Maybe proxy issue.

**Comment by mattn** [comment]
additional: The image is HTTP link not HTTPS.

**Comment by bpasero** [comment]
Please reopen if you still see this in our June release.

**Comment by mattn** [comment]
confirmed the fix. thanks.
