### ISSUE TITLE
File Explorer highlights unexpected node in workspace

### ISSUE THREAD

**Issue by hirikarate** [microsoft/vscode#73405]
Issue Type: <b>Bug</b>

I have a Lerna monorepo with following structure:
```
_ my-app-monorepo
 |_ packages
   |_ service
     |_ app.ts
   |_ lib
     |_ common.ts
```

I create VS Code Workspace like this:
```
|_ my-app-monorepo
|_ service
|_ lib
```
which "service" and "lib" are shortcuts to "my-app-monorepo/packages/service" and "my-app-monorepo/packages/lib"

**EXPECTED:**

In previous VS Code version, when I opened `app.ts`, the File Explorer highlighted it in a convenient manner.
```
_ my-app-monorepo
_ service
  |_ app.ts <= highlighted
_ lib
```

**ACTUAL:**

After recent VS Code update (I'm not sure since which version), the File Explorer behaves like this:
```
_ my-app-monorepo
  |_ packages
     |_ service
        |_ app.ts <= highlighted
_ service
_ lib
```
which negates my goal when adding "service" and "lib" folder to Workspace to save clicks.

Would you please restore the behaviour or show me a way to configure it.
Thank you.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.10GB free)|
|Process Argv|F:\gennova\event-checkin\event-checkin-hub-repo\event-checkin.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
vscode-eslint|dba|1.8.2
javascript-ejs-support|Dig|0.5.0
tslint|eg2|1.0.43
postgresql|JPT|0.0.2

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/72299
