### ISSUE TITLE
File Explorer renders so small it's hard to read

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/vscode#73409]
Issue Type: <b>Bug</b>

On my Surface Book 2, when I try to open a file through the File Explorer via File->Open File, the File Explorer that is opened is rendered so small I can't actually read anything.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.44GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.25.0
flutter|Dar|2.25.0
xml|Dot|2.4.0
tslint|eg2|1.0.43
chat|kar|0.12.0
vscode-cudacpp|kri|0.1.1
python|ms-|2019.3.6215
cpptools|ms-|0.22.1
csharp|ms-|1.18.0
powershell|ms-|1.12.0
vsliveshare|ms-|0.3.1403
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.10
xaml|ste|0.0.1
pdf|tom|0.5.0

</details>

Here's a screenshot of the issue. You can see how small the font in File Explorer is compared to the text document
![image](https://user-images.githubusercontent.com/9649518/57299485-896d8f80-7089-11e9-9680-2389cc896274.png)

**Comment by stevenbrix** [comment]
This is likely similar to #72129, but this issue doesn't seem limited to an RDP session

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by aditya-giri** [comment]
As the person responsible for opening #72129 I should probably mention that I see this issue only during RDP sessions and not locally.
