### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#73403]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/9205389/57294073-c60bac00-70c6-11e9-92fd-c5ebfb54e565.png)

Tracked this down to: https://github.com/microsoft/vscode/blob/8099c01477c4fbe62c5248dceca217250096ceb7/src/vs/workbench/contrib/files/browser/fileActions.ts#L878

It looks like either the Tree's typing is wrong or the Tree wrongly returned null.

VS Code version: Code - Insiders 1.34.0-insider (9ce42976fb1690c2cfdbc2a4a22dade51fc57657, 2019-05-06T11:08:23.316Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|24.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
my-test-ext|chr|0.0.1
vscode-pull-request-github|Git|0.6.0
remote-containers|ms-|0.48.0
remote-ssh|ms-|0.35.0
remote-ssh-edit|ms-|0.34.0
remote-ssh-explorer|ms-|0.34.0
remote-wsl|ms-|0.32.0
vscode-remote-extensionpack|ms-|0.12.0
azure-account|ms-|0.8.2
azurecli|ms-|0.4.5
vscode-docker|Pet|0.6.2
vscode-open-in-github|sys|1.12.0

</details>

**Comment by joaomoreno** [comment]
Any chance you can repro this?

There's no chance the tree can return null: https://github.com/microsoft/vscode/blob/8099c01477c4fbe62c5248dceca217250096ceb7/src/vs/workbench/contrib/files/browser/fileActions.ts#L876

IMO the cast here is problematic: https://github.com/microsoft/vscode/blob/8099c01477c4fbe62c5248dceca217250096ceb7/src/vs/workbench/contrib/files/browser/fileActions.ts#L876

**Comment by chrmarti** [comment]
I have seen this only once.

**Comment by isidorn** [comment]
Without reproducable steps not sure what to do here.
But yeah those commands run under the assumption that the last focused list is the explorer (since they are only enabled then).
Even without the cast the thing is a listWidget which has a getFocus() which should never return undefined. 
https://github.com/Microsoft/vscode/blob/8a6ddacc954c2a5dbc25a5ea673c4511aab943fe/src/vs/base/browser/ui/list/listWidget.ts#L1497
