### ISSUE TITLE
Collapse destructured variables like objects in JavaScript/TypeScript

### ISSUE THREAD

**Issue by lxender** [microsoft/vscode#73402]
Hey,

I noticed that whatever is in charge of collapsing/folding blocks of code doesn't recognize destructured variables as collapsable.

![see this image for an example](https://user-images.githubusercontent.com/20384895/57294023-a7a5b080-70c6-11e9-9391-b6a770a11a03.PNG)

The alternative is to cramp everything into one line, which leads to even less readable code.

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/31303 to track this upstream
