### ISSUE TITLE
Update description of files.encoding when it applies

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#73400]
Refs: https://github.com/Microsoft/vscode/issues/72479

`files.encoding` setting is only applied to newly created files.
Which I guess is fine, but the description of the setting is confusing as it does not mention that. I would suggest we at least clarify the setting description.

**Comment by bpasero** [comment]
I checked this back and this is only true for very few cases where we actually know the encoding of the file (UTF8, UTF16). Only in that case we do not change the encoding even if the setting is different. For all other encodings we do it. I think this should be an update to the settings description.
