### ISSUE TITLE
Minimize\Maximize works strangely if minimized window is set to a minimum width

### ISSUE THREAD

**Issue by semuserable** [microsoft/vscode#73407]
Maximize doesn't work as expected if a minimized window is set to its minimum width. After a click on 'maximize' button the topmost elements swaps, another click maximizes the window.

- VSCode Version: 1.33.1
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open VSC
2. Click minimize button
3. Drag VSC window until it reaches the minimum available width
4. Click maximize button

**Actual Result:** 
![image](https://user-images.githubusercontent.com/2175097/57297148-7a153300-70d7-11e9-92ce-d1fe49a87c8e.png)

**Expected Result:** window maximizes as usual, without additional step

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@semuserable I cannot reproduce with the above steps, can you provide a short video of your steps and experience?

**Comment by sbatten** [comment]
Also, @semuserable There are issues with electron window management on the version of Windows 10 you are using. Can you verify on a newer build of Windows?

**Comment by semuserable** [comment]
@sbatten hello! I'm attaching *.gif. I've also noticed that I got it 100% reproducible if I have 'Explorer' and some file with text opened.

![VSCodeStrangeMaximize](https://user-images.githubusercontent.com/2175097/57331683-e026a800-7121-11e9-8006-cec560d8b861.gif)

**Comment by semuserable** [comment]
@sbatten regarding Windows 10 update. I'll try to update my OS tomorrow and check it again.

**Comment by sbatten** [comment]
@semuserable While I won't suggest you don't update Windows 10, I was able to reproduce now on a newer build of Windows 10 so that is not the issue. The trick for me was putting the sidebar back on the left.

**Comment by sbatten** [comment]
@bpasero you can actually trigger this behavior by clicking a lot of places (of course very little is visible) in the workbench at those dimensions. The buttons aren't actually being triggered by the click. IMO the size is so unrealistic, I don't know if making the window this small should even be allowed.

**Comment by Northurland** [comment]
> 
> 
> @bpasero you can actually trigger this behavior by clicking a lot of places (of course very little is visible) in the workbench at those dimensions. The buttons aren't actually being triggered by the click. IMO the size is so unrealistic, I don't know if making the window this small should even be allowed.

@sbatten Sometimes the resize just automatically happen when you call out a minimized VSC window (so this is when the size becomes realistic), but for me it's almost completely random, there's no stable way of reproduction.

**Comment by sbatten** [comment]
this appears to be working with the new layout
