### ISSUE TITLE
Emmet: Update Tag changes wrong tag pair in invalid HTML

### ISSUE THREAD

**Issue by the-ress** [microsoft/vscode#73415]
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:08:08.969Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:
1. Create a new HTML document
2. Type:
```html
<form>
    <invalid>
    <span></span>
</form>
```
3. Put cursor into the `<span>` tag
4. Invoke "Emmet: Update Tag" command
5. Type `form`

Expected result: `<span>` gets changed to `<form>` even though it's a part of an invalid HTML. (Alternatively it could do nothing and show an error.)

Actual result: `<div>` gets changed to `<form>` unexpectedly.

Related issue: #39789

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

![ed2a6f5e-9302-49e9-a857-8d3eb0304ab2](https://user-images.githubusercontent.com/1612377/57306796-be0e3500-70e3-11e9-87ce-c9fccacd89c3.gif)

**Comment by rzhao271** [comment]
Merging this issue into #99896
