### ISSUE TITLE
How to capture a CPU profile of an extension loading?

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#73419]
I've had a few users report that VS Code shows a warning about bad "High CPU" from my extension. I managed to get one of them to attach a profile trace, and it shows really bad performance during the loading of my extension:

![Screenshot 2019-05-07 at 3 45 30 pm](https://user-images.githubusercontent.com/1078012/57308972-2a3a6a00-70df-11e9-8c01-25a45f5dd216.png)

It seems like lots of time is spend loading and compiling the JS files (a surprising amount - for ex. the big "(anonymous)" blog bottom left-of-center is seemingly compiling a 300 line file.

In order to improve things (which will probably be via cutting down on the number of files, or packing the extension) I'd really like to be able to measure the impact of the changes I'm making - however I can't find any way to profile the initial loading of an extension like this (the users profile was auto-generated by VS Code).

Once the extension is loaded, I can profile it from the "Running Extensions" page, but that's too late.

Is this possible? If not, please consider this a request for such.

**Comment by DanTup** [comment]
As a sort-of workaround, you can force the automatic dump of a profile by putting a loop that lasts for >3 seconds in top-level code:

```ts
const time = Date.now();
let i = 0;
while (Date.now() - time < 3000) {
	i++;
}
console.log(i);
```

The profile seems to cut off at 5s though, so seems you need to aim for the total to be >3s but <5s to get everything you need in the profile.

**Comment by jrieken** [comment]
* F1> Show Running Extensions
* Select 'start extension host profile'
* Activate your extension, e.g trigger its activation event
* Stop profiling, save profile

If that doesn't work for you, e.g when you must be *-activated then use this cmd-line switch

```
--inspect-brk-extensions <port>    Allow debugging and profiling of extensions with the extension host being paused after start. Check the developer tools for the connection URI.
```


> It seems like lots of time is spend loading and compiling the JS files (a surprising amount - for ex. the big "(anonymous)" blog bottom left-of-center is seemingly compiling a 300 line file.

That's very likely and likely doesn't reproduce on a fast machine, see https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading. We strongly encourage to bundle extensions as this cuts down loads costs dramatically

**Comment by DanTup** [comment]
> F1> Show Running Extensions
> Select 'start extension host profile'
> Activate your extension, e.g trigger its activation event

To activate my  extension I need to open a folder, which seems to restart the extension host, which seems to cancel this profiling?

> We strongly encourage to bundle extensions as this cuts down loads costs dramatically

That's specifically what I was trying to measure. Since bundling is going to cause pain with testing (or result in not testing the same code I'm shipping) I want to be sure I can see the benefits.

As it turned out, measuring by forcing the profile with my loop above, on my (fast) machine it seemed to go from around 1s to around 0.1s so it does seem like a good saving. I'll see if I can come up with a reasonable compromise for the tests.

**Comment by DanTup** [comment]
(Thanks!)
