### ISSUE TITLE
Could not update lightning components: Cannot read property 'Id' of undefined

### ISSUE THREAD

**Issue by sasha96** [microsoft/vscode#73410]
- VSCode Version: 1.33.1
- OS Version: Windows 10 PRO

Steps to Reproduce:

1. Create an aura component from dev console, as well as had done it before.
2. Refresh metadata index using MavensMate;
3. Update Project using MavensMate;
4. Try to change the new component that created and receive an error.

**Compile File: Failed
Could not update lightning components: Cannot read property 'Id' of undefined**

I had this error before, but deleting .lightnig  helped me, but not now. I have tried to create several other aura components with different API ( 40-45 ), and have tried to reinstalled visual studio and mavensMate. Unfortunately, nothing helped me.

**Comment by jrieken** [comment]
@sasha96 how is this related to VSCode?

**Comment by sasha96** [comment]
@jrieken I tried to find a solution.  It can be some problem with VSC or no.

**Comment by jrieken** [comment]
> It can be some problem with VSC or no.

I pick 'no' then. @sasha96 It's your responsibility to provide enough information so that we can reproduce the issue. You haven't done that yet.

**Comment by sasha96** [comment]
@jrieken please tell me, what kind of informations do you need?

**Comment by jrieken** [comment]
> Create an aura component from dev console, as well as had done it before.

Does this ship with VS Code? I believe not. Is this an extension I should install?

> Refresh metadata index using MavensMate;

Does this ship with VS Code? I believe not. Is this an extension I should install?

> Try to change the new component that created and receive an error.

Where, how? Dev console? Log? Do you have a stack trace? Does this reproduce without extensions enabled?

**Comment by sasha96** [comment]
extension - mavensMate ; Aura components;

It depends on Salesforce CRM. Dev console it from salesforce.

I have no logs

**Comment by sasha96** [comment]
@jrieken let me know if you can help me with this issue(depends on salesforce and mavensMate).

Thanks, Alex

**Comment by jrieken** [comment]
> It depends on Salesforce CRM. Dev console it from salesforce.

It's an extension issue then

**Comment by sasha96** [comment]
@vscodebot, @jrieken thanks
