### ISSUE TITLE
Terminate task: all running tasks polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#73417]
1. "All runnings tasks" -> "All Running Tasks"
2. Put a separator between list of tasks and "All Running Tasks"
3. "Select task to terminate" -> "Select a task to terminate" (though I trust your native english speaking here)

![Screenshot 2019-05-07 at 16 34 38](https://user-images.githubusercontent.com/1926584/57308184-2a8a3380-70e6-11e9-977e-f4658bb7c377.png)

**Comment by alexr00** [comment]
I agree that "Select a task to terminate" is better! That is an old string that I will update.
