### ISSUE TITLE
Terminate task: do not show picker if only one task running

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#73416]
1. Have a long running task
2. F1 > Terminate task
3. Picker is shown with only one task in the list. Just terminate it wihtout showing the picker, this step is not needed

**Comment by alexr00** [comment]
Currently this is intentional (See https://github.com/microsoft/vscode/issues/40508#issuecomment-352701786). I'll revisit this though.

**Comment by isidorn** [comment]
Ok, terminate I understand how this could this behave as a prompt. But agree with the user, others non terminating actions should definetely not ask.

**Comment by alexr00** [comment]
Per discussion in #40508, terminate should still show the pick.
