### ISSUE TITLE
Solution to #19917, alternative GUI for codelens that preserves line heights

### ISSUE THREAD

**Issue by baybal** [microsoft/vscode#73413]
In #19917 people raised the issue of codelens making text jump, and went to great length devising a solution with caching, animation delays and etc. Despite the effort spent, the existing solution only partially mitigates the issue, but introduces a lot of complexity for a "half measure."

I propose a much simpler GUI that will preserve line heights and allow for codelens to still run in one go:

Add a new column next to line numbers and show counts there. This way line heights will remain unchanged. And it be possible to quickly hide/show it without triggering a laggy reflow.

I feel that 16/9 screen are becoming more common than 4/3 or 5/4 screen these days. Why not to use extra screen width that now comes for free?

@jrieken @lonix1

**Comment by lonix1** [comment]
Great idea for another reason - codelens sometimes feels like a distraction/messy, sitting right above my code, but it's still so useful. This is a nice compromise.

**Comment by jrieken** [comment]
> Add a new column next to line numbers and show counts there

You say counts but reality is that there are longish labels in there. I have hard time imagining how this should look. Given the sample below can you mock up something (photoshop, paint...)

<img width="480" alt="Screenshot 2019-05-07 at 17 23 57" src="https://user-images.githubusercontent.com/1794099/57311963-ee0e0600-70ec-11e9-8e43-2cd446a3263e.png">

**Comment by mike-lischke** [comment]
Code lenses are horizontally oriented (partially long text, expand to the right), a number column will almost never give even a remotely similar experience. What might be a good use for such an extra column is to add markers for code lense lines. They are sometimes difficult to spot.

**Comment by lonix1** [comment]
It's true that one can only stuff so much info into a narrow column - so it can have only a marker that represents the codelens. And on hover it shows a popup with the whole horizontal text.

Then codelens is there, you know it's there and can see it, but it doesn't get in your way until you need it.

**Comment by baybal** [comment]
@jrieken Shure! Give me a day or two

**Comment by jrieken** [comment]
> @jrieken Shure! Give me a day or two

Thanks - remember, nothing crazy needed just some quick sketches "on paper". I share the same scepticism as @mike-lischke as most code lens are designed to fill a row

**Comment by baybal** [comment]
I uploaded mockups to

https://github.com/baybal/vscode-gui-design-mockups

First idea is to use some onhover popups and a "tip" icon that will trigger them. I think this has more or less clear implementation way. A very easy way to avoid reflows without API change. The downside is that things like warnings are kind of obscure until you hover over them. For that, I suggest to have colour variation or graphic effect put onto tip icon if there are warnings like messages in the lens.

![1](https://user-images.githubusercontent.com/3344988/57582006-7facb780-74e1-11e9-8876-7a4c706e6284.png)
![4](https://user-images.githubusercontent.com/3344988/57582008-8804f280-74e1-11e9-884a-7da85c57043e.png)
![2](https://user-images.githubusercontent.com/3344988/57582009-8affe300-74e1-11e9-8ee0-37c9607a9f73.png)


Second, is to expand on the customisable "tip" and display some kind of "shorthand" representation to lens messages. This will require API changes, and we may explore this is you are ready for them.

![6](https://user-images.githubusercontent.com/3344988/57582016-9a7f2c00-74e1-11e9-9a3c-e13c2da2129b.png)
![5](https://user-images.githubusercontent.com/3344988/57582018-9e12b300-74e1-11e9-8ea6-b8071fabc569.png)

Third idea is to put a column left or right of the text, where a wrapped text of the lens will be show. You can add some spacing or separators in between lens messages. If lens messages will overlap, you can put text-overflow: ellipsis on the text, or some visual effect to signal the overlap. The user will be then able to click on or hover over the particular lens to raise it. This design also allows avoiding text reflow, but the amount of effort to code it seem to be bigger to me that the two above. It also allows to preserve existing VS "comic book" style popups more or less unchanged.

If you want to lookup existing implementations, you can check how Google Docs does comments, and edit suggestions. MS Word has something similar, but doesn't layout comments nearly as much as good as Google Docs do.

![3](https://user-images.githubusercontent.com/3344988/57582021-a4a12a80-74e1-11e9-99c5-c9683ffa505c.png)

@jrieken @lonix1

**Comment by lonix1** [comment]
@baybal Your ideas are awesome. So neat... less cluttered than current codelens. Thanks for your efforts, I hope this will be seriously considered!

**Comment by jrieken** [comment]
Is this like the gitlens gutter?

<img width="815" alt="Screenshot 2019-05-13 at 17 45 12" src="https://user-images.githubusercontent.com/1794099/57662982-df20cb00-75a6-11e9-8347-2e6261dc6ec8.png">

**Comment by mike-lischke** [comment]
While I appreciate the nice designs from @baybal  (which however also have usability issues like the mid gray text on a light gray background -> difficult to read), I'm generally not very fond of these ideas. The code lenses are not only about git commits, which indeed could go into a space-saving popup. Instead they can show all kind of information (like reference counts for methods/rules), which must not be hidden permanently, or they will be totally useless. Code lenses are a totally different UI element than gutter information, and serve different purposes.

I stand by my previous verdict: if we can avoid frequent animations then the current implementation is totally fine.

**Comment by lonix1** [comment]
I think he took git information only as an example.

I agree that codelens is also about method references, etc. That is what I am most interested in.

But I like the idea of hiding that info until it is actually needed. Personally I find that info to be noise most of the time, until I actually need it (in which case it is right there in the margin, will be shown on hover).

**Comment by baybal** [comment]
@jrieken Yes, that UI is also fine, if there will be provisions for "smart" wrapping and/or multi-line output with rolodex effect (probably using z-order)

@mike-lischke exact choice of colour scheme was not my concern here, but yeah, I think something like code lens text should also be theme stylable, and not hardcoded

I also provided opinion above what I think about code lens output that has to be visible all the time: use some kind of shorthand output that will later be expanded in a more complete popup. Like "R:5" for reference count

**Comment by DanTup** [comment]
Moving them out of the editor would make actions like running tests much less convenient:

<img width="356" alt="Screenshot 2019-07-24 at 5 30 55 pm" src="https://user-images.githubusercontent.com/1078012/61811184-da935100-ae38-11e9-8e94-aa4107c01d69.png">

If they're moved out, please make it a user or extension preference. I'd prefer the editor shift than have these actions not immediately visible.

**Comment by jrieken** [comment]
fyi - there is an exploration item about rendering code lenses at the end of lines: https://github.com/microsoft/vscode/issues/90235
