### ISSUE TITLE
NPM Scripts: vertical sizing too aggressive

### ISSUE THREAD

**Issue by hughanderson4** [microsoft/vscode#73423]
Issue Type: <b>Bug</b>

NPM Scripts launcher panel is super nice feature!

But I think he tries to gobble up my precious vertical space too much.  He wants too much height!  My files list is what's most important.

Let's make his default about 280px instead of gobbling up 50% of vertical space, tame his aggressive nature.

At least if NPM Scripts panel remembered how high I set him last, and then when he opens again he goes back to remembered height, I would agree it is optimal solution.  We can use a shadow setting like { npm_scripts_height: '280px' } and persist it along with User Preferences.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
comment-ts|sal|0.9.11

</details>

**Comment by sandy081** [comment]
@hughanderson4 For me window remembers previous height of the npm explorer and retains it when the window is opened/reloaded. 

Do you have any specific steps to repro?

**Comment by hughanderson4** [comment]
Srsly it is big problem.
Try running 2 instances of VS Code.
2nd instance the npm scripts is like 75% of sidebar height.  WAY TOO AGGRESSIVE!  come on it is easy to fix.

**Comment by hughanderson4** [comment]
@sandy081 try running 2 instances of VS Code.  2nd+ instances have crazy tall npm scripts
