### ISSUE TITLE
Debug console automatic smart scroll broken

### ISSUE THREAD

**Issue by drez769** [microsoft/vscode#73425]
- VSCode Version: 1.33.1
- OS Version: Windows Server 2016

When I start debugging a Java Spring Boot app, the debug console only auto scrolls along with log output for a little while but then will just stop scrolling even though more output is being logged. It's like smart scroll only works for a certain number of lines then stops. If I manually ctrl+end, it still doesn't stick. Clearing console also doesn't work.

I'm pretty sure this wasn't a problem earlier this year, I think prior to the last 2 releases. I tested with only Java extension pack enabled after a completely fresh install today

**Comment by isidorn** [comment]
Fixed in latest insiders
