### ISSUE TITLE
Task that invokes CMake installed from pip on WSL doesn't work

### ISSUE THREAD

**Issue by galah92** [microsoft/vscode#73421]
- Version: 1.33.1 (user setup)
- Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
- Date: 2019-04-11T08:27:14.102Z
- Electron: 3.1.6
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

**On WSL**, I installed cmake via `pip3 install cmake` (supposedly this is the best way to get the latest version of CMake on linux). Then I defined the following `tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "CMake: Version",
            "type": "shell",
            "command": "cmake",
            "args": [
                "--version"
            ],
            "problemMatcher": []
        }
    ]
}
```
And got:
```
> Executing task: cmake --version <

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
Default shell is `WSL Bash`. When using `Command Prompt` it's all working (using Windows's CMake).

**Comment by alexr00** [comment]
@galah92 I installed cmake in wsl using `sudo apt install cmake` then ran your task. It worked as expected and printed the version of cmake. When I installed with pip3, it didn't work. Seems like that install path doesn't add cmake to the path.

**Comment by galah92** [comment]
> @galah92 I installed cmake in wsl using `sudo apt install cmake` then ran your task. It worked as expected and printed the version of cmake. When I installed with pip3, it didn't work. Seems like that install path doesn't add cmake to the path.

But it does:

```
gal@GalA-T480:~$ which cmake
/home/gal/.local/bin/cmake
gal@GalA-T480:~$ echo $PATH
/home/gal/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/IncrediBuild:/mnt/c/Program Files (x86)/Microchip/xc32/v2.15/bin:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Users/gal/AppData/Local/Programs/Python/Python37/Scripts:/mnt/c/Users/gal/AppData/Local/Programs/Python/Python37:/mnt/c/Users/gal/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/gal/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/CMake/bin:/snap/bin
gal@GalA-T480:~$
```

Even after adding the full `/home/gal/.local/bin/cmake` path (manually) it doesn't work.
