### ISSUE TITLE
Intellisense is slow and takes 20 seconds before loading suggestions

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [microsoft/vscode#73429]
win7 x64
vscode installed using zip version
6gb ram
ssd hard drive

**I type: Array. and 15-20 seconds after i get the list.**

no extensions installed
v 1.3.3

**Comment by chrmarti** [comment]
Could you append the source code you are doing this in? Which language are you editing?

**Comment by hp8wvvvgnj6asjm7** [comment]
jsx react, js

I could even open a new js file and type Array. 
same thing.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Closing as more information is needed
