### ISSUE TITLE
Refresh file while window open

### ISSUE THREAD

**Issue by ChesterCamm** [microsoft/vscode#73428]
While swapping git branches it would be great for the currently open file to automatically refresh, rather than having to tell it to or swap windows

**Comment by bpasero** [comment]
@ChesterCamm provided there are changes on disk, we do refresh the active file in the editor. Can you give me steps to reproduce how you got there? Does it reproduce all the time?

**Comment by ChesterCamm** [comment]
Yes

**Comment by bpasero** [comment]
@ChesterCamm does that reproduce even with a small sample, e.g. a folder (under git control) with a few files and then switching branches?
