### ISSUE TITLE
VoiceOver reads the text after the blank lines the amount of lines which were pressed.

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#73439]
- VSCode Version: 1.33.1 (1.33.1)
- OS Version: MacOS

Reported by: Taylor Arndt, Accessibility specialist, taylor.e.arndt@wmich.edu

Steps to Reproduce:

 I am not sure if it is an electron issue or a vs code issue.

In summary, the issue is when trying to edit code or navigate a file which has some blank lines voiceover on the mac reads the text after the blank lines the amount of lines which were pressed. For example, let’s say I have been provided with a python file which has 2 blank lines separating the block of code  the first line after the block of code would read twice because there were 2 blank lines. Where this can get  obnoxious  is when there are more than 2 lines that are blank in a row. From that point, you could here the text 4-5 times in a row.

Potential duplicate of https://github.com/microsoft/vscode/issues/51034

**Comment by alexandrudima** [comment]
Let's continue tracking in #70033 , where the OP has reached out directly to Chromium.

**Comment by alexandrudima** [comment]
May I also kindly encourage that you subscribe and comment at https://bugs.chromium.org/p/chromium/issues/detail?id=951777
