### ISSUE TITLE
Show line/column information when including in search filter string

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#73438]
When using the quick pick to access a file, you can specify which line to land on via `{file} :113`. However, there is no indication on the quickpick that this will work:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/35271042/57337078-f52d1800-70dc-11e9-8747-5fe4321ab5ab.png">

Suggestion is to append ` - Line 113` in the details line (and also column if they specify `:113:10`:
![image](https://user-images.githubusercontent.com/35271042/57337116-142baa00-70dd-11e9-8ee3-0fbc8f5e126b.png)

**Comment by bpasero** [comment]
@misolori I am not 100% sure this hint would be visible in most cases where the path is long and that part would get pushed out. But I can add it and we see then. To be clear, this would appear on every result in the list if there are multiple?

![image](https://user-images.githubusercontent.com/900690/76880916-ae6d8a00-6878-11ea-9732-694f91136a06.png)

**Comment by misolori** [comment]
That's a good point that the text might get truncated. Unless we try to truncate the path a bit like:

> **searchResultsView.ts** monaco • ../contrib/search/browser - Line 133

or update the title

> **searchResultsView.ts** (Line 133) monaco • sr/vs/workbench/contrib/search/browser

**Comment by bpasero** [comment]
@misolori yeah, it might look a bit crowded if suddenly all results show the line number, maybe only the selected one should.

**Comment by misolori** [comment]
Oh yea I only meant the selected row

**Comment by bpasero** [comment]
Tricky to get right with the current API for quick input (e.g. I cannot just update a label it seems when focus changes). Waiting for more people to ask for this before making a move. 

As for the original complaint that this feature is not discoverable, it is now:

![image](https://user-images.githubusercontent.com/900690/77536214-492f1f80-6e9c-11ea-8aa0-b5b05ddfa224.png)
