### ISSUE TITLE
wordBasedSuggestions: false does not turn off word-based completion

### ISSUE THREAD

**Issue by stanf0rd** [microsoft/vscode#73431]
Issue Type: <b>Bug</b>

Setting `wordBasedSuggestions: false` does not turn off word-based completion.
![image](https://user-images.githubusercontent.com/28190898/57322628-a303eb00-710c-11e9-87ca-3efc71859bbd.png)

![image](https://user-images.githubusercontent.com/28190898/57322553-7bad1e00-710c-11e9-8ee8-b87fa55bf048.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (4.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
fest|ang|0.2.0
vscode-django|bat|0.19.0
bracket-pair-colorizer|Coe|1.0.61
language-postcss|cpy|1.0.5
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
vscode-npm-script|eg2|0.3.6
vscode-todo-plus|fab|4.13.0
todo-tree|Gru|0.0.130
dummytextgenerator|gur|1.0.0
path-autocomplete|ion|1.13.3
svelte-vscode|Jam|0.8.0
vscode-text-pastry|jkj|1.2.0
docthis|joe|0.7.1
sftp|lix|1.12.4
theme-monokai-pro-vscode|mon|1.1.13
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
vscode-jest|Ort|2.9.2
material-icon-theme|PKi|3.7.0
markdown-preview-enhanced|shd|0.3.13
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0

</details>

**Comment by mjbvz** [comment]
Do you have word based suggestions enabled in your user settings?

**Comment by stanf0rd** [comment]
No, they are also disabled there:
![image](https://user-images.githubusercontent.com/28190898/57333212-06017c00-7125-11e9-933c-71c7679a8c25.png)

**Comment by jrieken** [comment]
Cannot reproduce, needs more steps

**Comment by jrieken** [comment]
not actionable

**Comment by kapple19** [comment]
I have this issue too. Please reopen. It's ridiculously annoying.

![image](https://user-images.githubusercontent.com/48305293/59820208-45e79000-936e-11e9-9cd0-f96e4ed36a8e.png)
