### ISSUE TITLE
silence update notifications

### ISSUE THREAD

**Issue by msandy** [microsoft/vscode#73433]
There should be an option to disable the update-available **notifications**.  Please note this is _not_ a duplicate of e.g. https://github.com/microsoft/vscode/issues/9539, which is to support automatic updates.  Rather, my system is corporate-managed and updates are automatically pushed to my machine after a vetting process by IT.  This makes the update notification completely inactionable for me.

**Comment by chrmarti** [comment]
Would setting the update channel to `none` in the settings do what you need?

**Comment by joaomoreno** [comment]
Set `update.mode` to `manual`.
