### ISSUE TITLE
Cannot save Workspace when using "Save Workspace As..." to save on top of currently opened .CODE-WORKSPACE files

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#73430]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open VS Code.
2. Open new document.
3. Save file to any directory. This will be the current working directory.
2. File > Save Workspace As...
3. Save Workspace to the current working directory.
4. Close VS Code.
6. Open VS Code.
7. Open the .CODE-WORKSPACE file in the current working directory.
8. File > Save Workspace As...
9. Save the workspace on top of the opened .CODE-WORKSPACE file.
10. It will fail to save/overwrite .CODE-WORKSPACE.

Expected:

The currently opened .CODE-WORKSPACE should be overwritten by the VS Code, because it is the current .CODE-WORKSPACE being overwritten by the current Workspace. In other words, the behavior should act like "Save Workspace". (Yo dawg...)

Actual:

You cannot save to a currently opened .CODE-WORKSPACE, even if the Workspace currently opened is the .CODE-WORKSPACE.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v3 @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (5.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
@tommai78101 what is the usecase of saving the same workspace that is opened on the same file?

**Comment by tommai78101** [comment]
Huh.....

It is not mentioned that Workspaces can auto-save changes here:

https://code.visualstudio.com/docs/getstarted/settings

**Comment by tommai78101** [comment]
@bpasero 

Huh.....

It is not mentioned that Workspaces can auto-save changes here:

https://code.visualstudio.com/docs/getstarted/settings

**Comment by bpasero** [comment]
@tommai78101 yeah it is, closing then.

**Comment by bpasero** [comment]
Wow, GH does have issues...

**Comment by bpasero** [comment]
@tommai78101 but making changes to the workspace does not require you to save the workspace at all, these changes are automatically saved. There is never a need to save the workspace if it already exists on disk.
