### ISSUE TITLE
Problems don't refresh after removing folder from workspace

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode#73434]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Add a folder to the workspace that contains errors or warnings that will appear in Problems view.
2. Remove folder from workspace.
3. Check Problems view. Associated problems should disappear but do not.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Please file an issue against the extension that is generating those problems. It is responsibility of the extension to remove them.
