### ISSUE TITLE
Locked keys

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#73445]
Issue Type: <b>Bug</b>

I haven't installed anything or modified settings since when it was fine, was just working and got "(S) was pressed. Waiting for second key".. shown on statusbar and the input not passed, happen on each S key press.
(of course the S are not listed/defined in the Keybindings)

Anyone **please** help.

p.s. its about 5th brickwall issue i meet with the VSCode (had 1 with Atom in a 3 times longer time).

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (4.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gjsjohnmurray** [comment]
@Ilias48rus have you tried disabling all your extensions temporarily? There's an F1 command for doing that (F1, then start typing 'reload')

If that doesn't help I suggest you first update to the latest version (1.33.1) and see if the issue remains. Or is there some reason you're still on 1.30.1 ?

**Comment by Ilias48rus** [comment]
@gabrieljacobsen didn't help

**Comment by Ilias48rus** [comment]
it persist trough system restarts, no idea what to do, even if reinstall of the VSCode would help without knowing the reason it ca happen again.

**Comment by gjsjohnmurray** [comment]
If you run the `Preferences: Open Keyboard Shortcuts (JSON)` command, what does it show in your keybindings.json file?

**Comment by alexandrudima** [comment]
@Ilias48rus Please check for keybindings of `s` in your `keybindings.json` file.

**Comment by Ilias48rus** [comment]
@alexandrudima. i'm sorry that didn't close it, think it was something about content displaying in the keybindings window and was solved with the .json .
