### ISSUE TITLE
[folding] configure plain text to use offSide folding

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#73444]
Please make, in case of indentation folding, the whitespace lines after last symbol do not fold, like Atom do.

![New Project](https://user-images.githubusercontent.com/13949704/57344136-a0c28080-714e-11e9-8452-8e0c8d3bfc7b.gif)

(or make it optional, you've partially added it to markdown, but this is an issue for all the languages)

**Comment by gjsjohnmurray** [comment]
@Ilias48rus In your example the file's language mode is Plain Text, so you're seeing VSCode's default indent-based folding.

Since [this 2017 change](https://github.com/Microsoft/vscode/issues/3353#issuecomment-330797736) it has been possible for languages to define that they are offSide style. But I don't know of a way of making Plain Text documents do their indent-based folding that way.

**Comment by Ilias48rus** [comment]
@gjsjohnmurray Thats why i posted the request :) ?

**Comment by aeschli** [comment]
To verify:
Create a plan test document with content
```
aaa1
  bbb
  bbb

aaa2
```

Verify that that only the `bbb` get folded for aaa1 (not the empty line)

**Comment by Ilias48rus** [comment]
Why is it closed?
![misZfoZplainTextXvsCode](https://lh3.googleusercontent.com/dGy6SQvHXX3tJWwGMjg5qIOdrPkPDDi04_3OG-4kJSKpZ62OCiJidzcBUYOxgCNAnws9ESS3UFKOrCQQ-VoZ8eANqp3ZTzXacE9iGekIK6rkvEi6xlb9KHVzfZ5eCtqcrnm9WYUZs8pGszZIBijwki3u-nHJY1bjrv6t9W_OyLtTSoZmfeVgIxiS8C1bWPHyIIDRp0cFlMtngLdbHrqydl4PCaNGfaCqHIR4RrWXRh84Gj7WiBxVIAcT6HpCAHwxtBQCT050U6SJbBGni5Pw67UoTbjt8cPHrLzWnKsqLdoTwQe6_mUJXeHwH34tlZBWvprO2nONm28zn7wbbkTTjeKn0PHrldWKzMw2sLFhkIJPlgg0X4CjjwuYd6cQF23_igdh9-jKGZHioF_qCmtEmxZeiREB9hVXRGFQiHZNfoR6Aazg5Fab6C-LrfAw0QMpGFshWg1PJsJye1X7pysnTHc-W7o-5-HGnYSeX49i_ZlY8JS24jcepRZItzpdbxJT72j7TjSFO82tV2LpK5GkJ4Fpc6RCmR49yRr5jR2FpU1zqZiOnJBOnYpY0z5DTGaZoAUKgCGAAeDq5CSBcRO8TomjVqstMIyOqyoiwv4DjkLttia4kJHKslfjmOrtr-Y55b8VlJAc2x41K9-XeCNkr4j5ay8UBLK6LbX14Bw5s3FGTE04FA_aW0M=w500-h190-no)

**Comment by aeschli** [comment]
The issue got closed as the issue got fixed by https://github.com/microsoft/vscode/commit/d32da8db592e6f032e2c09c464740047122bbbe3
and is available in October 2019.
