### ISSUE TITLE
Terminal is not working after last update

### ISSUE THREAD

**Issue by omkarsalunkhe1** [microsoft/vscode#73447]
After last VS Code update termianl is not working properly. It does not show current directory. Just show blank screen and cursor is placed on random location.
![bug](https://user-images.githubusercontent.com/13252858/57351199-97510c80-717e-11e9-9914-f97eb25449d4.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
