### ISSUE TITLE
Global Search Chinese can only search for open files. Searching English will not. Should not be a configuration error

### ISSUE THREAD

**Issue by terminator800s** [microsoft/vscode#73448]
Version：1.33.1 Global Search Chinese can only search for open files. Searching English will not. Should not be a configuration error

- VSCode Version:1.33.1
- OS Version:windows 7

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by terminator800s** [comment]
After setting Files:Encoding, I can search for it. But modifying this is more troublesome, I hope I can find it without setting this.

**Comment by roblourens** [comment]
Yes, this is not supported. Currently you have to configure the encoding and can only search one encoding at a time. https://github.com/microsoft/vscode/issues/34315
