### ISSUE TITLE
Splitview: support to exclude certain views from proportional resize when they are at their minimum

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#73453]
From #72969

**Comment by akbyrd** [comment]
Maximizing is basically useless without this fix and a way to toggle maximize state with a single keybinding.

**Comment by babakmahmoudian** [comment]
The issue also applies when the currently visible sidebar is hidden.

**Steps to Reproduce**

1. Toggle sidebar's visibility to shown.
2. Split the editor group horizontally _(Note: unlike the original issue, in this case the issue does not appear when editor group is split vertically)._
3. Maximize editor group (workbench.action.minimizeOtherEditors)
4. Hide the sidebar
5. Notice that when focusing an editor group, it does not get maximized anymore.

<details>
<summary>Code and OS version</summary>
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)<br>
OS version: Linux x64 5.3.0-19-generic</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2010 @ 2.80GHz (2 x 2628)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.72GB (0.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
vscode-intelephense-client|bme|1.2.3
laravel-goto-view|cod|1.3.2
EditorConfig|Edi|0.14.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
vscode-test-explorer|hbe|2.14.6
dotenv|mik|1.0.1
team|ms-|1.149.2
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
vscode-phpunit|rec|2.0.72
laravel-artisan|rya|0.0.26
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by akbyrd** [comment]
With this closed can we re-open https://github.com/microsoft/vscode/issues/72969?

**Comment by primozs** [comment]
It would be epic if the whole thing could be disabled.

**Comment by smitbarmase** [comment]
Hey everyone. I created this new issue for that. It needs 20+ votes in 60 days to get accepted.

https://github.com/microsoft/vscode/issues/125997
