### ISSUE TITLE
Terminal search skips some entries while searching upwards

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#73459]
- VSCode Version: 1.33.1
- OS Version: linux

Steps to Reproduce:

1. Open a terminal on the right side (about 80 chars wide)
2. cat attached file [LOG2.txt](https://github.com/microsoft/vscode/files/3156818/LOG2.txt)
3. Press search and enter `error` to the searchbar, search upwards (shift + enter)
4. line 373 e.g. got skipped, check with `grep -i error`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I believe this will be fixed when we update xterm.js, there were 2 recent fixes to search https://github.com/xtermjs/xterm.js/pull/1866 and https://github.com/xtermjs/xterm.js/pull/2025
