### ISSUE TITLE
Introduce concept to show changed but not dirty files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#73454]
From LiveShare people:

1. Host: Share a node.js web read only session
2. Guest: join this session
3. Host: edit some code and Start debugging
4. Guest: an error pops up on guest side :bug:

This is because the file is dirty and it seems like VS Code attempts to save it before starting a debug session.

@bpasero currently I call the `textFileService.saveAll` before each debug session starts.
Does it make sense that the `saveAll` simply skips all readonly resources?

**Comment by bpasero** [comment]
@isidorn having a readonly file appear dirty on the guest is asking for trouble, no? I mean the user could have auto save configured on focus lost, what would happen then when focus is lost?

I think the file somehow needs to show changed for the guest but not dirty at the same time. A concept we currently do not have.

**Comment by isidorn** [comment]
@bpasero yeah agree that is a better solution. Renaming this.
