### ISSUE TITLE
provideCompletionItems cannot be invoked when input in quota on language 'xml'

### ISSUE THREAD

**Issue by PuffLady** [microsoft/vscode#73455]
🚨 The issue tracker is not for questions 🚨

PLEASE HELP ME 🙏

This is my first time to submit an issue, please forgive me for my bad expression.
I want to implement an autocomplete feature for the language 'xml'. But i have no idea why the input in a quota cant invoke provideCompletionItems.
eg. in a file named 'test.xml'
content:
<Container style="w"></Container>

when I type 'w', 'width' is suggested, fortunately, provideCompletionItems didnt called.

But when i type in file named 'test.html', the input in a quota can invoke provideCompletionItems.

I want to know why different language trigger conditions are different, how can I change the trigger condition?

PLEASE HELP 🤕

**Comment by jrieken** [comment]
please refer to these samples: https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample
