### ISSUE TITLE
breakpoints are not correct when saving the source file after changed the file

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#73457]
- VSCode Version: 1.33.1
- OS Version: win 10

I write a lisp debug extension, but hit the following defect. And even in the "MockDebug" example I can also reproduce the issue.

Steps to Reproduce:

1.  Add one break in source file (for example at line 5)
2. start the debugger, it will start the debugger adapter
3. edit the source file (for example to add 10 line codes before the line 5),
4. save the source (ctrl + s)
5. Vscode send the "setbreakpoints" request to the debugger adapter, but the location for the breakpoint is still 5 instead 15

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
It is up to the debugger to update the breakpoint location.
@whlkw  What debugger are you using?

**Comment by whlkw** [comment]
@isidorn I am writing the vscode extension for a common lisp dialect language. We think VSCODE is a powerful IDE.
>> It is up to the debugger to update the breakpoint location.
Do you mean that the debugger should track the file changes, and track the breakpoints location for the file changes? I was thinking that the breakpoints information are from vscode side.

**Comment by whlkw** [comment]
I want to clarify one point:
In the above "step 5", after saved the source file, in the VSCODE UI the breakpoint is in line 15, but the request received by debugger adapter is line 5. 
If I "restart" the debug session, the breakpoint line information is correct in the "setbreakpoints" request.

**Comment by whlkw** [comment]
@isidorn Any update on this?

**Comment by isidorn** [comment]
No. Can you update the initial comment the have all the details clearly and consily please. Thanks

**Comment by whlkw** [comment]
I have updated the initial comment for the issue.

**Comment by isidorn** [comment]
Yes, I can reproduce and I acknowledge the issue.
VSCode should always send its notion of the line number, not what the debug adapter has reported.

**Comment by whlkw** [comment]
Thanks! Hope it can be fixed in future release!
