### ISSUE TITLE
Can't open multiple files through the context menu if VScode is not open

### ISSUE THREAD

**Issue by CatKasha** [microsoft/vscode#73467]
Can't open multiple files through the context menu if VScode is not open. If VScode is open, all works fine.

Steps to Reproduce:
1. Make sure that VSCode is closed
2. Select multiple files and "Open with VSCode" through context menu

If I do this, only one file opens in VSCode and appear multiple error message for each files:
![error](https://user-images.githubusercontent.com/19823797/57374706-2fadb800-71a4-11e9-9b39-9858c49b5037.png)

- VSCode and VSCodium Version: 1.33.1 (system setup)
- VSCode insiders Version: 1.34.0-insider (system setup) | daf71423252a707b8e396e8afa8102b717f8213b
- OS Version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by joaomoreno** [comment]
@bpasero Funny how it's the second one we see recently... did maybe something change during some refactorings?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/72531

**Comment by bpasero** [comment]
@joaomoreno yeah weird, not to my knowledge, but maybe a Windows 10 change somehow.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/72531 is on Linux :(
