### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by anayak-alphasense** [microsoft/vscode#73461]
Issue Type: <b>Bug</b>

Hi, 
I am runnign VS code on windows 8 dell i7 16GB laptop but its wokking very slow but at the same if i am using it on windows 7 its workig fine.
Can someone please check and help me out.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chrmarti** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for providing additional information on performance issues.

**Comment by jrieken** [comment]
not actionable
