### ISSUE TITLE
Syntax highlighting based on TypeScript types

### ISSUE THREAD

**Issue by yorrd** [microsoft/vscode#73463]
I'd like to highlight rxjs subjects differently from other variables, like primitives. As far as I understand, in a color theme, I don't have access to the token's TypeScript type. 

Forgive me if I misunderstand color themes. If this already exists, a pointer to an example would be greatly appreciated.

**Comment by aeschli** [comment]
See https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide for more information on how theming works.
As explained, color themes work on 'scopes' that are returned by a textmate grammar. In the case of TS this is the [TypeScript grammar](https://github.com/Microsoft/TypeScript-TmLanguage).
TextMate grammars are regexbased and only understand the syntax, no semantics, e.g they can't know what a identifier resolves.

- you can either file a request against the grammar to emit more scopes.
- you can come up with your own grammar
- you can use the editor.decorations API to add highlighting on top of the existing highlighting: https://github.com/microsoft/vscode/blob/7006ca07723ba3ea2b73f9fa0db5b1c122ffbf2b/src/vs/vscode.d.ts#L1144
See sample: https://github.com/microsoft/vscode-extension-samples/tree/master/decorator-sample

**Comment by yorrd** [comment]
Thanks!
