### ISSUE TITLE
Highlight and paste triggers copy command instead of overwrite (paste) highlighted text

### ISSUE THREAD

**Issue by Akumzy** [microsoft/vscode#73462]
Issue Type: <b>Bug</b>

Open any file with code in it 
copy any text
highlight another text then either press ctrl+v or right clip to prompt contextmenu then select paste

VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:03:41.613Z)
OS version: Linux x64 5.0.0-13-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1821)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|7.67GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
dart-code|Dar|3.0.0
flutter|Dar|3.0.0
gitlens|eam|9.7.1
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.6.0
vue-snippets|hol|0.1.11
path-autocomplete|ion|1.13.3
remote-containers|ms-|0.49.0
remote-ssh|ms-|0.35.0
remote-ssh-edit|ms-|0.34.0
remote-ssh-explorer|ms-|0.34.0
remote-wsl|ms-|0.32.0
vscode-remote-extensionpack|ms-|0.12.0
azure-account|ms-|0.8.2
Go|ms-|0.10.2
sublime-keybindings|ms-|4.0.0
vetur|oct|0.19.5
polacode|pnp|0.3.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
vscode-icons|vsc|8.6.0
quokka-vscode|Wal|1.0.211
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by chrmarti** [comment]
Does this also happen when reloading with extensions disabled? (`F1` > `Developer: Reload Window With Extensions Disabled`)

**Comment by Akumzy** [comment]
@chrmarti Not that I'm aware of 
I didn't even know such feature do exist.

**Comment by chrmarti** [comment]
@Akumzy Could you run `Reload Window With Extensions Disabled` and see if you can still reproduce the problem while extensions are disabled?

**Comment by Akumzy** [comment]
@chrmarti I ran the command `Reload Window With Extensions Disabled` and it's working as it's supposed  to.

**Comment by chrmarti** [comment]
@Akumzy Not sure which extension this might be causing, maybe try disabling them one by one until the problem disappears. When you find that extension please open an issue for it.
