### ISSUE TITLE
Line breaks in Windows integrated terminal ignored when pasted

### ISSUE THREAD

**Issue by danekan** [Microsoft/vscode#7346]
- VSCode Version: Windows 1.2.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Copy several lines of code (open notepad, type mkdir directory1[enter]mkdir directory2)
2. Paste code in integrated terminal, it pastes as a single command 'mkdir directory1mkdirdirectory2' with any line breaks removed.

This happens on both default cmd.exe integrated terminal and powershell integrated terminal.

**Comment by chrmarti** [comment]
Cannot reproduce with the current insiders build on Windows 8.1/10.

**Comment by Tyriar** [comment]
@chrmarti can you checkout the related https://github.com/Microsoft/vscode/issues/8617 as well? I thought they probably have the same root cause and t he latter was repro'd on Insiders.

**Comment by chrmarti** [comment]
#8617 still reproduces under Windows, taking a closer look.

**Comment by chrmarti** [comment]
This issue still reproduces if the source comes with LF. (Which is not the case if you use notepad, that adds CRLF.)

**Comment by danekan** [comment]
Now with the latest insiders build (and actually one prior I had noticed earlier this week) I cannot even copy/paste into the integrated powershell console. Right click does nothing, CTL V literally displays the ^V.

**Comment by Tyriar** [comment]
@danekan this is expected, use <kbd>ctrl</kbd>+<kbd>c</kbd> to copy and <kbd>shift</kbd>+<kbd>v</kbd> to paste until #6451 is resolved (see that issue for details on future plans). Also related: #8818
