### ISSUE TITLE
<img> tag destroying html format

### ISSUE THREAD

**Issue by remcobirdy** [microsoft/vscode#73460]
When i use a img tag in my html my format gets 'destroyed'. With a small file it's not a huge problem, but when my html file is getting bigger it's annoying. When i disable the VScode HTML formatter the problem is gone. I'm using Visual Studio Code version 1.33.1.

I really want to use the html formatter, am i doing something wrong or is this a known bug?

This code:

![image](https://user-images.githubusercontent.com/48443866/57368487-8955b880-718b-11e9-8ac8-7fd17769c064.png)

Gets formatted into this:

![image](https://user-images.githubusercontent.com/48443866/57368523-98d50180-718b-11e9-8c99-21c3091da87c.png)

Because of the img tag.

**Comment by remcobirdy** [comment]
I'm working on Windows 10, maybe that makes a difference?

**Comment by remcobirdy** [comment]
> Unable to reproduce the issue.
> 
> ![html-format](https://user-images.githubusercontent.com/9017268/57379129-df465280-71c3-11e9-81ee-bbc970a264f8.gif)

I'm working on Windows 10, maybe that makes a difference?

**Comment by NizamLZ** [comment]
@remcobirdy I tried it on windows 10 itself. Do you have any extensions installed which might interfere with the default HTML formatter?

**Comment by remcobirdy** [comment]
@NizamLZ i disabled all my extensions, still no effect.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
