### ISSUE TITLE
API to get a list of available snippets

### ISSUE THREAD

**Issue by luikore** [microsoft/vscode#73471]
I need to get a list of available snippets in current document. But seems no API can return them.

**Comment by jrieken** [comment]
Can you elaborate your use-case? You can invoke completions for a file and filter down to snippet-type completions - that will give you (per file) the whole list of static and dynamic snippets

**Comment by luikore** [comment]
I'm writing an extension to just avoid popping up the menu like you suggested. It is very inefficient for me.

More specificly, 

```typescript
vscode.commands.registerTextEditorCommand("MySnippetExpander", (textEditor, edit) => {
  let snippets = textEditor.availableSnippets(); // I'm asking for some API like this
  for (let s in snippets) {
    if (s.prefix === "..." /* some condition */) {
      textEditor.insertSnippet(s.body, textEditor.selection.active)
    }
  }
})
```

**Comment by jrieken** [comment]
Ok, use the `vscode.executeCompletionItemProvider` command, as described here https://code.visualstudio.com/api/references/commands#commands

**Comment by jrieken** [comment]
Oh, what you are trying to achieve looks very similar to the built-in tab completion feature, e.g. `"editor.tabCompletion": "onlySnippets",`
