### ISSUE TITLE
High usage of cpu

### ISSUE THREAD

**Issue by schneiderbruno** [microsoft/vscode#73479]
Hello,

I'm facing the problem that sometimes the vs code uses a lot of processing, such as for now.
I have a seventh generation i5, ie it's not a bad cpu let's say so.

I leave the print attachment on the screen.

I hope they can solve it.

Any doubt I am available.

![image](https://user-images.githubusercontent.com/8595383/57391533-1d784d80-7195-11e9-85a3-f07f92cd173f.png)

**Comment by gjsjohnmurray** [comment]
I suggest you look at https://github.com/microsoft/vscode/wiki/Performance-Issues and work through the advice there, adding information to this issue here.

**Comment by jrieken** [comment]
not actionable
