### ISSUE TITLE
Performance Issues with VScode and Typescript

### ISSUE THREAD

**Issue by Morphexe** [microsoft/vscode#73470]
Issue Type: <b>Bug</b>

I have trouble with vscode, this hapeens quite frequently and after open/close it goes away for a few minutes, sometimes over a couple of hours.

Vscode intellisense and even typings lags like hell, I can see the characters being typing slowly, also its using HUGE ammounts of ram for GPU rendering.
I have caught vscode hogging around 8GB of ram, although it was debugging, but I still feel thats too much.

I can't seem to pin point what exactly is causing this, I have tried without extentions and eventually it all does the same.

Attached is a print of my process explorer where you can see that the GPU process is hogging around 1GB, and so is TSServer. Notice that although I am currently on a surface pro, this happens in my own Desktop which has a 1080GTX and a 16gb Ram with Ryzen 1700. So something else is causing this.

On a side note, the project is not that big, it has around 2000  lines across 20ish files. 

Any ideas on how to debug this?

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134
<details>
<summary>Process Explorer</summary>
<img width="776" alt="VscodePerformance" src="https://user-images.githubusercontent.com/17990387/57377712-09cfe580-719b-11e9-8bc5-e56536bed9d8.png">
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.82GB free)|
|Process Argv|C:\Users\Eduardo\Desktop\Projects\ResearchAdjustmentApp\Starlizard.Service.ResearchAdjustmentApp.ClientApp|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.3
vscode-browser-preview|auc|0.5.4
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.7.1
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
easy-snippet|inu|0.1.4
vscode-styled-components|jpo|0.0.26
graphql-for-vscode|kum|1.13.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vscode-jscpd|pau|0.3.4
quicktype|qui|12.0.46
yo|sam|0.9.3
code-settings-sync|Sha|3.2.9
highlight-matching-tag|vin|0.9.1
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.6.0
quokka-vscode|Wal|1.0.212
glean|wix|4.10.3

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by FishOrBear** [comment]
In fact it is very difficult to restore, I often press F1, then restart the TS Service

**Comment by jrieken** [comment]
> On a side note, the project is not that big, it has around 2000 lines across 20ish files.

Do you have node-module dependencies? Do you have a rough estimate how many children the node_modules-folder has?

**Comment by ben-denzer** [comment]
@jrieken I came here to report the same issue, and I have been able to determine that the slowness does not happen after I remove my node_modules folder. I'm using create-react-app with a few added dependencies so my node_modules folder is pretty large (281Mb) - but uninstalling VS Code 1.33 and installing the Feb release (1.32) fixes my problem.

**Comment by mjbvz** [comment]
@Morphexe Can you share your project? Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by FishOrBear** [comment]
Is it likely to be related to this?

https://github.com/microsoft/TypeScript/issues/30663

**Comment by ben-denzer** [comment]
In my case I use styled components withe Typescript 3.3.333 - I had initially suspected styled-components as I have had issues w/ their VS Code extension before.

But downgrading VS Code is the easy solution for me

**Comment by mjbvz** [comment]
Closing as more information is needed from the original poster

@Morphexe  Please test this using the latest VS Code insiders builds (using TS 3.5-insiders) and let us know if you still see this issue
