### ISSUE TITLE
Deleting Files on Copy-Paste

### ISSUE THREAD

**Issue by jeremy-coleman** [microsoft/vscode#73478]
- VSCode Version:
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
x64
- OS Version:
windows 10 latest
Steps to Reproduce:
1. copy file
2. paste file

When copying the same file , ie: Component.ts and pasting into the same folder , instead of renaming the the file to Component.1.ts, vscode will (very rarely) not rename the file, and over-write the old one. The file explorer often doesn't update as well, but just restarting vscode fixes that. Unrecoverable file deletion is the big issue

**Comment by isidorn** [comment]
I can not reproduce this.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes please try to provide exact reproducable steps. Thank you
