### ISSUE TITLE
Automatic click on right click button 

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode#73474]
I have a weird problem.
When i right click (click and release button) automatic select first in menu. Its happen 75% times.
I have to click and hold button (don't release) and hover on my menu and release it.
I test with touchpad also and same problem.
I have Ubuntu 18.04 , before its Ubuntu 16.04 and had this problem too.

![ezgif-3-28967fecf1c1](https://user-images.githubusercontent.com/20030910/57380487-4e20ad00-71be-11e9-84a2-8872d5b32879.gif)

**Comment by sbatten** [comment]
@fakhamatia can you share a larger screen capture so we can see  the full window dimensions as well as version info?

**Comment by fakhamatia** [comment]
> @fakhamatia can you share a larger screen capture so we can see the full window dimensions as well as version info?

I figure out when problem in clicking.
In lines 1-12 click is OK , but in lines 13-20 the menu don't fit in windows and menu placed under mouse  and click automatic , and lines 21-26 its OK because menu open to top of mouse.
here full capture :

![ezgif-3-f8230f286ac1](https://user-images.githubusercontent.com/20030910/57567067-295c4d80-73e9-11e9-8b50-31f872546ca9.gif)


Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-18-generic

**Comment by sbatten** [comment]
Thanks @fakhamatia, I actually think this is resolved by https://github.com/microsoft/vscode/pull/73553

**Comment by m1keil** [comment]
this seems to be the same re-occurrence of previous cases:
https://github.com/eamodio/vscode-gitlens/issues/518
https://github.com/microsoft/vscode/issues/60119
https://github.com/microsoft/vscode/issues/73607

for me switching back to `"window.titleBarStyle": "native"` instead of "custom" helps

**Comment by fakhamatia** [comment]
The `"window.titleBarStyle": "native"` work but not use original TitleBar of VSCode ,
The problem just not with right-click in editor, I can't right-click when renaming in custom or native, and I can't resize sidebar menu.

**Comment by sbatten** [comment]
fixed by 4d50f8b699bad3a400b98b58782acd6280fff36e
