### ISSUE TITLE
.eslintrc should be associated with language "json with comment"

### ISSUE THREAD

**Issue by golopot** [microsoft/vscode#73483]
Version:
- VSCode Version:  1.33.1

Steps to Reproduce:
1. Open a .eslintrc file.
2. Notice that comments are flagged as error.

Eslint can parse .eslintrc files with comments and trailing commas. The file .eslintrc should be associated with language jsonc.

**Comment by Tyriar** [comment]
From https://eslint.org/docs/user-guide/configuring#configuration-file-formats

> JSON - use .eslintrc.json to define the configuration structure. ESLint’s JSON files also allow JavaScript-style comments.
