### ISSUE TITLE
Debug console prints new line character instead of creating new lines

### ISSUE THREAD

**Issue by mbkupfer** [microsoft/vscode#73489]
I honestly tried my best to ensure that I'm not raising a duplicate issue here and the closest thing I could find was this closed issue  https://github.com/Microsoft/vscode/issues/255, but it doesn't seem like this issue has been fixed, at least in my case. And yes, I also downloaded the latest insiders and see that the issue is still occurring there. 

My issue is regarding the debugger console printing the new line character: `\n` as opposed to actually printing a new line. This makes it very difficult to inspect my python code in the vscode debugger. This particular issue came up when using the pandas library, but I'm sure there are many other situations where this can make it very difficult to debug. . 

- VSCode Version:
$ echo $(code -v)
1.33.1 51b0b28134d51361cf996d2f0a1c698247aeabd8 x64
- OS Version:
macOs 10.14.4 (18E227)

Steps to Reproduce:

1. Create the following python file and put a break point after assigning df:
```python
import pandas as pd

df = pd.DataFrame({'A': list(range(1, 10))})

pass # It seems like this was necessary to insert a breakpoint
```
2. Debug the program and once in the debug console:
```
df
   A\n0  1\n1  2\n2  3\n3  4\n4  5\n5  6\n6  7\n7  8\n8  9
df.head()
   A\n0  1\n1  2\n2  3\n3  4\n4  5
```

For reference, here is how those command get printed in the regular terminal:
```
ins] In [2]: df                                                                
Out[2]: 
   A
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

[ins] In [3]: df.head()                                                         
Out[3]: 
   A
0  1
1  2
2  3
3  4
4  5
```

Does this issue occur when all extensions are disabled?: Yes/No

Not applicable since the script will not be debuggable without the python extension. That said, when testing out in the insiders addition, the python extension was the only thing downloaded. Just to be exact, the extension I'm referring to is the Python extension for Visual Studio Code named `ms-python.python`

**Comment by isidorn** [comment]
This should be fixed in latest vscode insiders. If you still see it please file it against the python extension
