### ISSUE TITLE
Add a "Reinstall" option next to "Uninstall" that calls "Developer: Reinstall extension"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#73485]
There is already a "Developer: Reinstall extension" command, but we would like the "Reinstall" option added next to the "Uninstall" option in the extension context menu to make it more discoverable to users, because we still get reports of users doing uninstall/install and it's failing because they don't know they need to either run the command or restart VS Code after the uninstall. The reason our C/C++ extension requires a reinstall sometimes is if the extension enters some corrupted state (i.e. deleted/missing files). See https://github.com/microsoft/vscode-cpptools/issues/3610 as an example.

**Comment by KRChapman** [comment]
I am new to working on vscode where would be a good place to start to tackle this problem. For example where is the code for "Developer: Reinstall extension".
