### ISSUE TITLE
UI bugs - missing all the debug buttons and indicators

### ISSUE THREAD

**Issue by zooldk** [Microsoft/vscode#7348]
- VSCode Version: 1.2.0
- OS Version: Windows 7

Steps to Reproduce:

1. launch visual code with the cordova plugin enabled
2. try to add break points in the editor

When doing this - all the visual indications of a break point are gone. On my mac I can visually see a red dot indicating a breakpoint. Also in the debug window, the "play" button is missing and when launched (cordova) , I can't see the "play", "stop" etc. buttons that I can on my mac. This is tested on two windows machine (both window 7 version).

**Comment by zooldk** [comment]
Attached a screenshot. Even though I have pressed mouse button to create a break point - it is not visually shown.

![image001](https://cloud.githubusercontent.com/assets/1841838/15871021/c1620a70-2cf2-11e6-8da7-5f0b842e3355.png)

**Comment by weinand** [comment]
@zooldk I just verified node debugging in VS Code 1.2 on Windows 7 and could not find any issues. Since you are using the Cordova extension I suggest that you file this problem against the Cordova extension.
