### ISSUE TITLE
not support input requests.

### ISSUE THREAD

**Issue by Carlos9122** [microsoft/vscode#73494]
When I run the code ##input("Hello Word"), show me this message:
1 #%%
----> 2 input("Hello Word")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py in raw_input(self, prompt)
    846         if not self._allow_stdin:
    847             raise StdinNotImplementedError(
--> 848                 "raw_input was called, but this frontend does not support input requests."
    849             )
    850         return self._input_request(str(prompt),

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

**Comment by chrmarti** [comment]
Please file for https://github.com/Microsoft/vscode-python
