### ISSUE TITLE
pug syntax highlighting

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#73497]
There are a number of PUG syntax highlighting issues that have been closed, either labeled 'caused by extension', or moved upstream.

I think most of these are fixed in version 4.1.1 of VSCode-TextMate.   VSCode is still building with version 4.0.1.

Can this be updated, please?
Thanks.

Reference:
#70535
#65983 
maybe #57152

/cc: @angelul, @tenrys, @neilsoult, @dan503

**Comment by msftrncs** [comment]
I can confirm through a test build that the vscode-textmate 4.1.1 will fix #70535, and from what I can tell, all of #65983.

![image](https://user-images.githubusercontent.com/26179051/57425505-ffd0d580-71e0-11e9-8fcd-fe36a43e683a.png)

#57152 however appears to be complicated and partially related to the JavaScript grammar inclusion.

**Comment by alexr00** [comment]
I'll look into updating the version of textmate!

**Comment by msftrncs** [comment]
@alexandrudima seems to have gotten to this with https://github.com/microsoft/vscode/commit/f0ba210ef93504af548442b7428dc25ebab91e2e and later fixture cleanup by @mjbvz with https://github.com/microsoft/vscode/commit/6b081a9f0089062b2cd105e1f1ab366591291534.

This also helps with an HTML issue, https://github.com/microsoft/vscode-textmate/issues/49 and with issues I was having with https://github.com/PowerShell/EditorSyntax/pull/155 and https://github.com/PowerShell/EditorSyntax/pull/156.

Thanks all.
