### ISSUE TITLE
TypeScript Intellisense very slow with some projects

### ISSUE THREAD

**Issue by AmrN** [Microsoft/vscode#7349]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 14.04

I'm using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter), and after cloning the repo and doing an `npm install` typescript intellisense is extremely slow.
One thing I've noticed is that the `exclude` list paths in **tsconfig.json** are written like this:

```json
{
  "exclude": [
    "./node_modules",
    "./typings/main.d.ts",
    "./typings/main"
  ]
}
```
But once I remove the dot slashes and restart VS Code things seem to be fixed and intellisense works fast:

```json
{
  "exclude": [
    "node_modules",
    "typings/main.d.ts",
    "typings/main"
  ]
}
```

I've reported the issue AngularClass/angular2-webpack-starter#660 but it seems the problem lies with VS Code since I've tried Atom with its typescript plugin and it works properly with that starter by default.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9019
