### ISSUE TITLE
autoAttachChildProcesses doesn't work when restarting

### ISSUE THREAD

**Issue by dimitarnestorov** [microsoft/vscode#73491]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4, Windows 10

Video showcase: https://youtu.be/KpcmK2SP69I

Steps to Reproduce:

1. Create a new folder and open it in VS Code
2. Create `index.js` with the following contents:
```javascript
const cluster = require('cluster');
const http = require('http');

if (cluster.isMaster) {
	console.log(`Master ${process.pid} is running`);

	console.log(`Forking 2 workers.`);
	// Fork workers.
	cluster.fork();
	cluster.fork();

	cluster.on('exit', (worker, code, signal) => {
		console.log(`worker ${worker.process.pid} died`);
	});
} else {
	// Workers can share any TCP connection
	// In this case it is an HTTP server
	http.createServer((req, res) => {
		res.writeHead(200);
		res.end('hello world\n');
	}).listen(8000);

	console.log(`Worker ${process.pid} started`);
}
```

3. Create `.vscode/launch.json` with the following contents:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/index.js",
			"autoAttachChildProcesses": true
		}
	]
}
```
4. Start debugging `Launch Program`
5. Restart

Does this issue occur when all extensions are disabled?: Yes

**Comment by valerio-battaglia** [comment]
This bug is still up.

Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by kinsi55** [comment]
Still present

Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Chrome: 69.0.3497.128
Node.js: 10.11.0

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/) that handles child processes in a more relaible way. Please let us know if you're still running into problems, and if so open an issue on that repo.
