### ISSUE TITLE
vscode.TerminalRenderer.onDidChangeMaximumDimension doesn't fire if renderer window height increases

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#73496]
Issue Type: <b>Bug</b>

details

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (22.10GB free)|
|Process Argv|--folder-uri file:///c%3A/src/cascade/vscode/extension|
|Screen Reader|no|
|VM|0%|

</details>

**Repro steps:**
1. In VSCode extension, create a terminal render with `vscode.window.createTerminalRenderer(name)`;
2. Subscribe to `onDidChangeMaximumDimensions` event on the renderer.
3. In the event handler, set `renderer.dimensions` to the new maximum dimensions after some time the event has fired (like in 100 ms).
4. Try to resize the terminal pane in VSCode UI.

**Expected:**
`onDidChangeMaximumDimensions` event fires whenever the terminal pane is resized, regardless of whether it is increasing its height, or decreasing.

**Actual:**
`onDidChangeMaximumDimensions` event fires only when the terminal pane height is decreased. It does not fire when the height is increased. It does fire for both increasing and decreasing of the panel width though.

**Comment by Tyriar** [comment]
To verifier:

1. Clone, build and run https://github.com/Microsoft/vscode-extension-samples/tree/master/terminal-sample
2. Run the "Create terminal renderer" command and focus the new terminal renderer in the panel
3. Open devtools console
4. Resize the terminal vertically, you should see logs saying the dimensions changed
5. Run the "Set dimensions" command and put something small
6. Resize the terminal vertically, you should _still_ see logs when resizing beyond what was set in step 5
