### ISSUE TITLE
终端 powershell 不显示

### ISSUE THREAD

**Issue by zdz1715** [microsoft/vscode#73501]
Issue Type: <b>Bug</b>

每次开启一个新的powershell，不显示路径，输入命令才会显示

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
vscode-intelephense-client|bme|1.0.14
path-intellisense|chr|1.4.2
ycy|for|0.1.2
docthis|joe|0.7.1
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hans|MS-|1.33.2
php-docblocker|nei|1.8.0
vetur|oct|0.20.0
vscode-docker|Pet|0.6.2
view-in-browser|qin|0.0.5
code-settings-sync|Sha|3.2.9
language-stylus|sys|1.11.0
vscode-icons|vsc|8.6.0

(1 theme extensions excluded)

</details>

**Comment by wawaforya** [comment]
Translation: Use PowerShell as the integrated terminal, path is not displayed before typing a command into the new terminal instance.

**Comment by byyxx128** [comment]
这是 Win10 的 bug，1903 解决了，等着升级吧。

> This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate #57803

**Comment by Bikashd4332** [comment]
what  @zdz1715 is trying to say is when you leave the terminall (powershell) open and close vscode then the next time you open vscode then you can the terminal open however nothing appears even after waiting long. When you start typing it shows the characters but the prompt `PS` . Its a general problem which I found too.
![image](https://user-images.githubusercontent.com/23401383/57428295-540da100-7245-11e9-890e-74aad6496db6.png)

There are no prompt above as you can see on the image.

**Comment by byyxx128** [comment]
@Bikashd4332 Same thing... #57803

**Comment by zdz1715** [comment]
@byyxx128 好的

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
