### ISSUE TITLE
Press the right mouse button and select the function to display all the functions

### ISSUE THREAD

**Issue by yshengwu** [microsoft/vscode#73504]
Press the right mouse button and select the function to display all the functions of the current page, which is very convenient for quickly checking the position of the positioning function.

**Comment by chrmarti** [comment]
You can enable Follow Cursor for the Outline view:
![image](https://user-images.githubusercontent.com/9205389/57436648-676a3d80-7240-11e9-960a-1ba1c2d7b669.png)

You get to that menu from the view's titlebar:
![image](https://user-images.githubusercontent.com/9205389/57436735-9a143600-7240-11e9-811e-1b2b1495ee64.png)

Does that address your request?

**Comment by yshengwu** [comment]
ok, thanks.
