### ISSUE TITLE
Support javascript private properties defined with #

### ISSUE THREAD

**Issue by aduh95** [microsoft/vscode#73502]
I'm trying to resuscitate #56566 now that the [proposal](https://tc39.github.io/proposal-class-fields/) is stage 3 and the syntax has shipped to V8 7.3 (chromium 73+, Node JS 12+).

Currently vscode throws an invalid character error when defining javascript private methods or properties started with `#` symbol:

![example](https://user-images.githubusercontent.com/29608698/44212183-101bbe80-a141-11e8-9c4c-dcf3269508e0.png)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/9950
