### ISSUE TITLE
Some questions about vsCode

### ISSUE THREAD

**Issue by luxuefengGIT** [microsoft/vscode#73503]
First of all, thank you for taking the time to reply to my letter

Secondly, I apologize for not paying attention to the written language

Yesterday, when my MAC started the project set up by dva, suddenly the fan went crazy. The CPU was occupied by code heliper, which was 142%, and several such processes appeared at the same time. It caused my MAC to slow down and freeze.

**Comment by gjsjohnmurray** [comment]
Probably a good idea to start at this wiki article:
https://github.com/microsoft/vscode/wiki/Performance-Issues

And this one may help you improve your report:
https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by jrieken** [comment]
not actionable
