### ISSUE TITLE
i am not able to zoom out.

### ISSUE THREAD

**Issue by AbhilashaBaghel** [microsoft/vscode#73508]
Issue Type: <b>Bug</b>

i tried to zoom in by the following steps in visual studio code version-1.33.1.0
1.go to preference 
2. go to setting.
3. Then i made the zoom from -1 to 100%.
4. Now i am not able to zoom out.

**Comment by chrmarti** [comment]
Did you use `%` in the value, like `"100%"`?

**Comment by AbhilashaBaghel** [comment]
yes

**Comment by bpasero** [comment]
@AbhilashaBaghel can you try without using the `%` character, it should just be a literal number.

**Comment by AbhilashaBaghel** [comment]
I am not able to open it now. not getting popover in zoom mode to open preference settings

**Comment by bpasero** [comment]
@AbhilashaBaghel you should be able to open the settings file directly and make that change. It is located in `C:\Users\<name>\AppData\Roaming\Code\User\settings.json`

**Comment by AbhilashaBaghel** [comment]
thanks bpasero now it is coming fine. I am able to zoom out.
