### ISSUE TITLE
Mac --disable-gpu failing

### ISSUE THREAD

**Issue by thomashrabe** [microsoft/vscode#73506]
- VSCode Version: 1.32.1 (1.32.1)
- OS Version: OSX 10.14.3

Steps to Reproduce:

1. Install OSX 10.14.3 in a Parallels VM on a OSX host
2. Install VS Code
3. Run `open /Applications/Visual\ Studio\ Code.app --args --disable-gpu`

Before the update VS Code used to work and VS Code was useable within the VM. Parallels has known rendering issues with OSX as guess system. Chrome, VSCode and other apps become unusable when using GPU rendering. 
Now, seems `disable-gpu` is broken and renders VS Code unusable in a VM environment.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by thomashrabe** [comment]
This build works in the VM. Again, this is a Parallels GPU driver problem and `--disable-gpu` is a workaround. Thank you!

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
