### ISSUE TITLE
Regular expression look-ahead becomes unexpected behavior

### ISSUE THREAD

**Issue by popurax** [microsoft/vscode#73518]
Issue Type: <b>Bug</b>

goal: search "ishoge".
sample Code:
```
hoge = 1;
ishoge = hoge != null;
```

Ctrl+F to Search mode.
type `(?=[a-zA-Z])hoge `.
→ hit only "ishoge". but,"hoge" also matchs.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|2.18.2
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
pgsql|dou|0.1.3
gitlens|eam|9.7.1
vscode-npm-script|eg2|0.3.6
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.0.15
shell-format|fox|4.0.11
harurow-util|Har|1.3.2
svgeditor|hen|2.9.0
rest-client|hum|0.21.2
docthis|joe|0.7.1
language-haskell|jus|2.6.0
node-module-intellisense|lei|1.5.0
cmake-tools-helper|mad|0.2.1
evermonkey|mic|2.4.5
code-beautifier|mic|2.2.1
vscode-language-pack-ja|MS-|1.33.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
powershell|ms-|1.12.1
vsliveshare|ms-|1.0.125
debugger-for-chrome|msj|4.11.3
printcode|nob|3.0.0
java|red|0.44.0
npmsmartimporter|ref|3.0.0
partial-diff|ryu|1.4.0
theme-arakaki|vsc|0.1.10
cmake|twx|0.0.17
sort-lines|Tyr|1.8.0
vscode-terminal-here|Tyr|0.1.1
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-maven|vsc|0.16.2
vscode-react-native|vsm|0.9.2
vscode-todo-highlight|way|1.0.4
wandbox-vscode|wra|2.2.3
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.3.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
You want lookbehind like `(?<=[a-zA-Z])hoge`
