### ISSUE TITLE
Allow addition of individual files to a workspace

### ISSUE THREAD

**Issue by johndog** [microsoft/vscode#73511]
Workspaces can currently consist of one or more folders.  

It would be great to be able to add a selection of files to the workspace, since it's not always possible to make a scenario revolve entirely around a directory.  For example, I might create a workspace for one of my git repos, but add a .gitconfig file from my profile directory.

**Comment by TuxVinyards** [comment]
There are currently 28 people signed up for notifications on this issue. This parallel thread continues to stay active despite its status being auto-changed to 'closed' during a mass crud cull this time last year.

Unless #45177 becomes re-opened this is NOT a duplicate.

I understand quite well that the development team has over 5000 open issues at present & even has to utilise a bot to help. However, there is a lot of strong feeling over this feature request.

**Comment by MrRobboto** [comment]
Thanks @TuxVinyards 

+1 for this feature - it's an obvious progression for workspaces, has clear use cases detailed in #45177, and growing support.

**Comment by ferSoto** [comment]
+1 I came for the same reason. The project I'm working on uses workspaces because each folder needs a different configuration and uses different environment to run but also has two files at the root level (README is one of them) and it would be nice to be able to edit them without using a new window or launch vim from the console.

Please make it happen.

**Comment by lloydsargent42** [comment]
+1 for the same reasons everyone else it talking about. Ran into this myself. I have project that uses an SDK that requires FILE level, not folder level (difference between a scalpel and a nuke).

**Comment by thdk** [comment]
We have a asp.net mvc website with all typescript files in one folder.
Development for mvc is done in visual studio, but typescript development is done in vscode.

We would like to only add the web.config file from the mvc project into the vscode workspace.
So we can easyly switch connection strings, and environment specific settings from vscode.

I could add the parent folder of this web.config to the workspace but then I also get folders containing c# and razor files into my workspace which I don't want to see ofcourse.

**Comment by OwenPattison** [comment]
> There are currently 28 people signed up for notifications on this issue. This parallel thread continues to stay active despite its status being auto-changed to 'closed' during a mass crud cull this time last year.
> 
> Unless #45177 becomes re-opened this is NOT a duplicate.
> 
> I understand quite well that the development team has over 5000 open issues at present & even has to utilise a bot to help. However, there is a lot of strong feeling over this feature request.

Given #45177 is now re-opened this could be closed as a dupe at this point

**Comment by johndog** [comment]
> Given #45177 is now re-opened this could be closed as a dupe at this point

It's interesting that this issue asks for a user-facing feature, whereas #45177 asks for a schema change.  

Also interesting:  if @malefficient's workaround mentioned in https://github.com/microsoft/vscode/issues/45177#issuecomment-499339944 could be refined and supported through UI, a schema change might not even be required.  In fact, if it works reliably, maybe we should actually close #45177 since a semantic change has already been made that allows both files and dirs to be used in the existing schema?
