### ISSUE TITLE
Please add expandall in sidebar

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/vscode#73516]
Searched dupes, didn't find this.

I use the side bar for searching but search results do not return until you expand the folder where the file is found. There is currently a Collapse All button. A lot of times, the opposite of Collapse All is Expand All and you can just hit the same button over and over to get them to expand/collapse. Can that please be added to better enable searches?

![image](https://user-images.githubusercontent.com/8278033/57435291-481de100-723d-11e9-8845-8ed40b651ba8.png)

Thanks

**Comment by gjsjohnmurray** [comment]
Some related discussion in #66811, where I also learned that Alt+click on an expanded twistie will recursively collapse it, so next time you expand it with an unmodified click its subfolders will be in the closed state. Conversely, Alt+click on a collapsed twistie will recursively expand it **but** only for folders that have previously been manually expanded. AFAIK that constraint is to avoid the scenario where a single user action (Alt+click) on a root folder of a huge tree causes VSCode to go wild.

**Comment by potatoqualitee** [comment]
Perhaps the ability can be disabled/reenabled in Settings? I don't mind VSCode going wild if I can get my search results to work without all the manual expansion I'm doing now.

**Comment by roblourens** [comment]
I agre, there is an issue for this here: https://github.com/microsoft/vscode/issues/70357
