### ISSUE TITLE
wrong twitter link on home page

### ISSUE THREAD

**Issue by ranjan-ranjan** [microsoft/vscode#73517]
The link marked in the snapshot doesn't redirect to https://twitter.com/code
![wrong link](https://user-images.githubusercontent.com/16834561/57437448-6d234b80-725f-11e9-9ce8-ac21bd98e9a0.png)

**Comment by octref** [comment]
Yes, it opens a new window like this, which is intended:

![image](https://user-images.githubusercontent.com/4033249/57485079-9d6aea00-725f-11e9-91de-a13e99eaa163.png)

**Comment by ranjan-ranjan** [comment]
No, it doesn't for me.

**Comment by octref** [comment]
Probably because you blocked the JavaScript that would open the page, either through adblocker or disabling JavaScript.
