### ISSUE TITLE
Running PowerShell script hangs

### ISSUE THREAD

**Issue by seajhawk** [microsoft/vscode#73510]
Issue Type: <b>Bug</b>

I have a powershell script with the following contents:
```
$a = "ok"
Write-Host "Hello World!"
Write-Host $a
```

When I run this script in VSCode via F5 or ctrl+F5, VSCode just hangs.

However, when I tried Code Runner, the script runs just fine.

Also, while this doesn't work on the computer where I am sending this Issue from, the same script works just fine on another computer running the same version of VSCode and the same OS.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.4.12954
powershell|ms-|1.12.1

</details>

**Comment by Tyriar** [comment]
By hangs do you mean the entire window or you just can't interact with the terminal?

**Comment by seajhawk** [comment]
I am able to interact with the terminal, as well as the rest of the window.


  1.  Create test.ps1 with one line:
write-host “Hello World!”
  2.  Press F5 to run the code
  3.  Blue bar at the bottom turns orange and debug toolbar appears
  4.  Nothing else happens.
     *   There is no change to Terminal window or Output window
     *   I can type commands in the Terminal window like “dir”

I just removed VS Code and reinstalled it, but I’m seeing the same behavior.

Thanks,
Chris

**Comment by Tyriar** [comment]
Thanks for the info. This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
