### ISSUE TITLE
Issue Reporter falls back to filing an Extension report here if extension doesn't offer a GH repo

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#73515]
The repo for my small extension called [The Folding Stuff](https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff) is hosted on GitLab rather than GitHub. If I use Issue Reporter to try and open an issue about it my issue gets directed here (i.e. microsoft/vscode).

The same fallback behaviour occurs if I try to file against another extension of mine that doesn't declare a repo at all.

In both cases the GH issue that gets drafted doesn't mention the extension name, only its version number.

Maybe Issue Reporter should tell the user that the selected extension doesn't support filing of reports this way.

**Comment by connor4312** [comment]
Verified. It may be nice to hide or make readonly the "title" and "steps" inputs, though, since filling them out doesn't do anything/doesn't enable the "preview on github" button.

![](https://memes.peet.io/img/20-01-c868337b-57c7-492e-9dbc-9b04353589fd.png)
