### ISSUE TITLE
[html] Closing markup tags should auto-format/indent

### ISSUE THREAD

**Issue by trstringer** [microsoft/vscode#7351]
- VSCode Version: 1.2.0
- OS Version: Windows (10.0.10586.0)

Steps to Reproduce:
1. Create a new HTML file
2. Type the following into the editor

``` html
<html>
  <head>
```
1. Go to a newline (hit enter, should be on line 3 of the editor)
2. Type in `</head>`
3. Notice that the closing head tag stays indented as if it was a child element

**Desired result**

When closing tags, VS Code should auto-indent (in this case move `</head>` to the same indentation as the `<head>` tag on the previous line).

**Comment by marcoms** [comment]
I would really love this fixed! A closing curly brace de-indents JS, surely the same should be done for HTML?

**Comment by cvharris** [comment]
I've seen an extension try to do this but they're very inconsistent. Feels like something VSCode should do itself.

**Comment by atom-morgan** [comment]
Are there any updates on this? Has it been fixed? I'm experiencing the same behavior as @trstringer and it's quite annoying.

**Comment by seanvaleo** [comment]
please fix this
