### ISSUE TITLE
Issue Reporter - link to wiki page about writing good reports

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#73512]
[This wiki page](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) contains good guidance but I have the feeling some folk find the Report Issue option on VSCode's Help menu without also finding that wiki page.

I suggest the Issue Reporter dialog gets a link added to it.

**Comment by gjsjohnmurray** [comment]
@RMacfarlane any chance of adding a sentence to the top of this dialog, with a link to the wiki page headed "Submitting Bugs and Suggestions"?
![image](https://user-images.githubusercontent.com/6726799/113485864-b90cb880-94a7-11eb-9e8f-950e11c6e53a.png)

Something like this:

> Before you report an issue here please review [the guidance we provide](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

I'm willing to submit a PR if you wish.

**Comment by TylerLeonhardt** [comment]
@gjsjohnmurray I think that's a great idea. Feel free to send a PR 😁
