### ISSUE TITLE
Option to disable only angle bracket highlighting 

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#73521]
Hi

I think in options should be exist option like - _Disable **angle** bracket highlighting match_

`"editor.matchBrackets": false,` it's not a solution because it disable highlight match for any other brackets like a braces

Or maybe i can do it in another way?

**Comment by nardev** [comment]
Never heard of more stupid reason for closing the issue. Is it company policy to do so or something else.

This is pretty annoying thing. Should be possible to make it not so annoying! Why not just replicate functionalities of atom/sublime?

**Comment by irfancnk** [comment]
This is still an issue for me, with angle bracket matching highlight it is really hard to locate the editor cursor.
