### ISSUE TITLE
Multi File Search result disappears

### ISSUE THREAD

**Issue by LucasBrd** [microsoft/vscode#73526]
Issue Type: <b>Bug</b>

When using a regex to search multiple files, the results disappear when you click on different results

Search regex used : 
```
throw Error\(\{.*
.*error
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nsp|ada|1.0.1
solidity-extended|bea|3.0.2
systemd-unit-file|coo|1.0.3
javascript-ejs-support|Dig|0.5.0
jquerysnippets|don|0.0.1
xml|Dot|2.4.0
tslint|eg2|1.0.43
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
docker-explorer|for|0.1.6
timing|Haa|2.1.0
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.0
solidity|Jua|0.0.56
vscode-liquid-snippets|kil|1.2.0
sftp|lix|1.12.4
twig-language|mbl|0.8.3
twig-language-2|mbl|0.8.3
dotenv|mik|1.0.1
mssql|ms-|1.5.0
python|ms-|2019.1.0
csharp|ms-|1.17.1
language-liquid|nei|0.1.1
vscode-docker|Pet|0.6.2
ejs-language-support|Qas|0.0.1
shopify-liquid|sis|1.6.5
numbermonger|sof|0.4.0
unity-debug|Uni|2.7.2

</details>

**Comment by roblourens** [comment]
1.30 is a bit old, can you try updating vscode and let me know whether it still happens?

If so, can you include the full text of the match that shows this issue?

**Comment by LucasBrd** [comment]
Ok I upgrade to 1.33.1 and the bug is not present anymore.
