### ISSUE TITLE
How to find a command identifier in VSCode?

### ISSUE THREAD

**Issue by anurbol** [microsoft/vscode#73528]
So I can see commands list by pressing `ctrl+shift+p`. The list however shows only human-readable titles (`Foo Bar`), not command identifiers (`editor.foo.bar`). How do I find the identifiers? 

If no one knows a generic way, maybe someone knows the identifier of `Debug: Start Debugging` command?

P.S. I need this for extension development, i.e. launching the command from my extension.
P.P.S. No one answers/views the question on SO: https://stackoverflow.com/questions/56059194/how-to-find-a-command-identifier-in-vscode

**Comment by isidorn** [comment]
Preferences > keyboard shortucts there you have a bunch of commands > right click > copy command
`workbench.action.debug.start` is the one you want

**Comment by anurbol** [comment]
@isidorn wow, so easy. Not very intuitive though. Thanks!
