### ISSUE TITLE
Include full path in windows taskbar hover for code workspaces

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/vscode#73529]
When opening a recent code-workspace using the Windows taskbar, on hover the only information shown is `Code Workspace`. When hovering over a folder, the folder name w/ the path is shown

If a dev has multiple of the same workspace name in their recents, it can become a guessing game to which one they want.

![code_workspace_taskbar_hover](https://user-images.githubusercontent.com/19917677/57459615-31758b00-7239-11e9-9bb1-9ba443435f64.gif)

**Comment by bpasero** [comment]
This might require new API from Electron, but adding "help wanted" if someone wants to investigate.

**Comment by cmeyertons** [comment]
Really?  I just noticed Code already does it with non .code-workspace files.  

Steps to repro:

Go to text file in Windows explorer -> right click -> open with Code.
Close Code.
Right click Code in taskbar -> hover over text file -> see path displayed in parentheses to the right of the text file.

**Comment by bpasero** [comment]
Great, then maybe even easier for someone to contribute 👍
