### ISSUE TITLE
Formatting CPP files

### ISSUE THREAD

**Issue by cjfudge** [microsoft/vscode#73525]
Issue Type: <b>Bug</b>

Reformatting a CPP files makes it syntactically incorrect.

e.g.
```
  std::vector<std::vector<int> >::iterator
```
becomes
```
  std::vector<std::vector<int>>::iterator
```

Which will result in a compilation error:

```
error: ‘>>’ should be ‘> >’ within a nested template argument list
```

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sequence-diagrams|Ale|0.3.1
comments|Ale|1.0.4
mermaid-markdown-syntax-highlighting|bpr|1.0.1
thrift|cdu|0.0.1
xml|Dot|2.4.0
gitlens|eam|9.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
code-runner|for|0.9.9
beautify|Hoo|1.5.0
vscode-phpfmt|kok|1.0.30
prettify-json|moh|0.0.3
python|ms-|2019.4.12954
azure-account|ms-|0.8.2
cpptools|ms-|0.23.0
Go|ms-|0.10.2
php-docblocker|nei|1.8.0
vscode-docker|Pet|0.6.2
vscode-mermaid-preview|vst|0.12.0
prettify-selected-json|vth|1.0.3
debug|web|0.23.1
vscode-proto3|zxh|0.2.2

</details>

**Comment by chrmarti** [comment]
Could you file this for https://github.com/microsoft/vscode-cpptools ? Thanks.
