### ISSUE TITLE
Activate command only after rebuilding native module

### ISSUE THREAD

**Issue by Vyshakh18** [microsoft/vscode#73527]
Hi,
I am developing an extension which has native modules. I have currently put code to rebuild the native modules as per platform in the 'activate' method of the extension.
So i want the commands to appear in the command palette only after this 'rebuild exercise' is done.
Because otherwise if the user chooses the command, it would complain saying 'command not found'
Is there some way to achieve this - basically command should appear in the palette only after i finish the rebuild of native modules

**Comment by sandy081** [comment]
I see your extension depends on platform and for such extensions we are planning to support platform specific extensions. With that you can precompile your native modules and publish and we would pick them based on the run time platform. But this is still yet to implement - https://github.com/microsoft/vscode/issues/23251

There are couple of extensions which has similar requirements and I assume they would wait until their runtime dependencies are resolved before running the commands. It means all your commands that depend on runtime dependencies have to wait until they are resolved. So there is no way to delay commands to be available in the command pallette. But as I said, the real fix is to use platform specific extensions when available.
