### ISSUE TITLE
Browsing folders/files in workspace that uses remote folder shares is slow

### ISSUE THREAD

**Issue by wjens** [microsoft/vscode#73538]
I mount a remote Windows share to my Mac over a VPN. When I load a vscode workspace that uses folders on this share it can take a very long time to load and browsing subfolders within the workspace is slow. It didn't used to do this.

If I go into Finder and open the same folder, it usually speeds things up in vscode. I don't know if vscode is hanging while waiting on macOS to reply or something else. It did seem faster after disabling extensions but that could also be a caching bump within macOS.

The only extensions I'm running are:
Classic ASP Syntaxes and Snippets - Classic ASP Language Support and Snippets from tmBundle
C# - C# for Visual Studio Code (powered by OmniSharp).

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by wjens** [comment]
It's definitely faster, even with the same extensions loaded.

It takes ~53 seconds on vscode vs. ~15 seconds on your preview release. This is the time from when the window appears to when the folder list is expanded to show files. Subsequent loads are quicker, as long as I don't disconnect / reconnect the mounted drive.

I'll stick with the preview release for now.

Thanks,
William
