### ISSUE TITLE
Add docs.rs to list of approved badge providers

### ISSUE THREAD

**Issue by reuvenpo** [microsoft/vscode#73531]
Trying to display a badge from docs.rs in the markdown preview with "Strict" security enabled fails. This is because docs.rs is not listed in the list of [Approved Badges](https://code.visualstudio.com/api/references/extension-manifest#approved-badges).

The text after the list instructs opening an issue here in order to add to the list, so here we are :)

Example badge:

```markdown
[![Documentation]][docs.rs]
[Documentation]: https://docs.rs/py-comp/badge.svg
[docs.rs]: https://docs.rs/py-comp
```

EDIT: accidentally referred to crates.io instead of docs.rs

**Comment by reuvenpo** [comment]
I'd gladly submit a PR with the relevant changes myself, just point me the right way. Where is that list maintained

**Comment by joaomoreno** [comment]
Is is `docs.rs` or `crates.io`?

**Comment by reuvenpo** [comment]
It's `docs.rs`.
Try my example in a new markdown file and you should see the issue (if your previewer is configured in strict mode)

**Comment by joaomoreno** [comment]
- https://github.com/microsoft/vscode/commit/c0004e95442755874c2010ce1036f3d0c6c4d1eb
- https://github.com/microsoft/vscode-vsce/commit/dd2b0efd98e051338182e1eea0cc5f763d320e92
- https://github.com/microsoft/vscode-docs/commit/f8c80d3d252528318aff810500c30312471fb74f

**Comment by reuvenpo** [comment]
Thanks @joaomoreno!
Can you please link to the PRs?

**Comment by joaomoreno** [comment]
There were no PRs.

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/58600156-4772dc00-8238-11e9-8c5c-f92e35dfa2b4.png)

I'm still seeing it blocked but probably @mjbvz can tell if I made anything wrong.

**Comment by mjbvz** [comment]
Looks like `https://docs.rs/py-comp/badge.svg` does a redirect to `http://docs.rs/py-comp/badge.svg?version=0.1.3`?

We don't allow loading content over plain old http which would explain why this content is still blocked

**Comment by reuvenpo** [comment]
>Do you know any more about what docs.rs is doing here?

No, not really.

But, if this is a blocking issue on your part (fetching content over HTTP) then I'm sure we can open a change request to the docs.rs repository. It's right here:

https://github.com/rust-lang/docs.rs

Are you saying that this would be necessary?

**Comment by mjbvz** [comment]
Yes, please follow up with them. They are doing a 302 redirect to an http endpoint which is no good:

```
$wget https://docs.rs/py-comp/badge.svg
--2019-05-30 10:26:04--  https://docs.rs/py-comp/badge.svg
Resolving docs.rs... 13.32.255.185, 13.32.255.149, 13.32.255.111, ...
Connecting to docs.rs|13.32.255.185|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://docs.rs/py-comp/badge.svg?version=0.1.3 [following]
--2019-05-30 10:26:04--  http://docs.rs/py-comp/badge.svg?version=0.1.3
Connecting to docs.rs|13.32.255.185|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://docs.rs/py-comp/badge.svg?version=0.1.3 [following]
--2019-05-30 10:26:04--  https://docs.rs/py-comp/badge.svg?version=0.1.3
Connecting to docs.rs|13.32.255.185|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 884 [image/svg+xml]
Saving to: 'badge.svg'

...
```

**Comment by reuvenpo** [comment]
Sorry for the delay.

I opened an issue in the docs.rs:

https://github.com/rust-lang/docs.rs/issues/363

I guess this issue will wait until this is resolved upstream.

**Comment by pietroalbini** [comment]
Pietro from the Rust infrastructure team here.

Sorry for the disruption caused by this! We have updated the server configuration to issue proper redirects.

**Comment by reuvenpo** [comment]
Thanks a lot for the quick response @pietroalbini !

When do you estimate that this will be deployed?

**Comment by pietroalbini** [comment]
The changes should already be deployed, do you see any issue?

**Comment by mjbvz** [comment]
Thanks @pietroalbini! I confirmed this is now fixed in VS Code:

![Screen Shot 2019-06-04 at 10 43 45 AM](https://user-images.githubusercontent.com/12821956/58901271-b9727780-86b5-11e9-99ee-003d6c2dd460.png)
