### ISSUE TITLE
Path modification order not preserved

### ISSUE THREAD

**Issue by Willowlark** [microsoft/vscode#73532]
- VSCode Version: 1.33.1
- OS Version: OSX 10.13.2

# Steps to Reproduce:

When using `conda`, the terminal path is updated to place the new environment into the path ahead of other path entries. When doing so in the terminal for VSC, VSC places values ahead of this modified path which cause a different `python` to appear first in the path. 

1. Open VSC terminal
2. conda activate environment

# Samples

## Expected Behavior

Output of $PATH (in a standard terminal) should look like this:
`/Users/bill/anaconda3/bin:/Users/bill/anaconda3/condabin:/anaconda3/bin:/Users/bill/.cargo/bin:/Users/bill/.rvm/gems/ruby-2.4.1/bin:/Users/bill/.rvm/gems/ruby-2.4.1@global/bin:/Users/bill/.rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bill/.rvm/bin`

And like this following the `conda activate environment`

`/Users/bill/anaconda3/envs/gmv/bin:/Users/bill/anaconda3/condabin:/anaconda3/bin:/Users/bill/.cargo/bin:/Users/bill/.rvm/gems/ruby-2.4.1/bin:/Users/bill/.rvm/gems/ruby-2.4.1@global/bin:/Users/bill/.rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/`

## Actual Behavior

In Visual Studio code the same comparison is:

`/Users/bill/.cargo/bin:/Users/bill/.rvm/gems/ruby-2.4.1/bin:/Users/bill/.rvm/gems/ruby-2.4.1@global/bin:/Users/bill/.rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bill/anaconda3/bin:/Users/bill/anaconda3/condabin:/anaconda3/bin:/Users/bill/.cargo/bin:/Users/bill/.rvm/gems/ruby-2.4.1/bin:/Users/bill/.rvm/gems/ruby-2.4.1@global/bin:/Users/bill/.rvm/rubies/ruby-2.4.1/bin:/Users/bill/.rvm/bin`

`/Users/bill/.cargo/bin:/Users/bill/.rvm/gems/ruby-2.4.1/bin:/Users/bill/.rvm/gems/ruby-2.4.1@global/bin:/Users/bill/.rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bill/anaconda3/envs/gmv/bin:/Users/bill/anaconda3/condabin:/anaconda3/bin:/Users/bill/.cargo/bin:/Users/bill/.rvm/gems/ruby-2.4.1/bin:/Users/bill/.rvm/gems/ruby-2.4.1@global/bin:/Users/bill/.rvm/rubies/ruby-2.4.1/bin:/Users/bill/.rvm/bin`

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@joaomoreno Could this be due to `getUnixShellEnvironment()` spawning the subprocess with a non-empty PATH?

**Comment by chrmarti** [comment]
@Tyriar @joaomoreno Would it make sense to come up with a fix specific to PATH until we figure out #70248?

**Comment by Tyriar** [comment]
@chrmarti tampering with the environment sounds like it would be risky. There is a workaround you can do to just override your PATH in the terminal, I think the Python ext does this.

```
"terminal.integrated.env.osx": {
  "PATH": ""
}
```

**Comment by chrmarti** [comment]
Couldn't we run `$SHELL -lic ...` with an empty PATH and then check if the original PATH as any additional entries compared to the one from `$SHELL -lic ...` and just add these back?

Educated tampering might be better than having this subtle pitfall.

**Comment by Tyriar** [comment]
@chrmarti but I believe it also depends on the user setup, and you might run into other issues if you do that. People have lived with this issue since the terminal initially shipped so I think waiting a bit longer is better than potentially introducing another set of problems?

**Comment by chrmarti** [comment]
Extensions are also affect by this, which made me wonder if there is an incremental improvement we can make while #70248 is being discussed.
