### ISSUE TITLE
Cannot alt+click relative links in terminal Version 1.33.1

### ISSUE THREAD

**Issue by ohabash** [microsoft/vscode#73530]
- VSCode Version: 1.33.1
- OS Version: MacOS 10.14.1

Steps to Reproduce:

1. Get error pointing to a relative path in terminal
2. try to hover but no link found
3. try to alt click and "[[C^[[C^[[C^[[C^[[C^[[C^[[C" prints in terminal

Does this issue occur when all extensions are disabled?: No

I know this error was discussed and solved for in this thread but i followed all advices and still have the issue. https://github.com/microsoft/vscode/issues/58256

**Comment by Tyriar** [comment]
Some things to try/answer:

- Does the underline appear on hover?
- Are you using tmux or some other terminal shell by chance?
- Does this setting fix the problem? `"terminal.integrated.macOptionClickForcesSelection": true`
