### ISSUE TITLE
Latest Version Tag 

### ISSUE THREAD

**Issue by NathanTheGr8** [microsoft/vscode#73539]
It appears that the latest version of VScode on GitHub is tagged as 1.11.2. Is that intentional?
https://github.com/microsoft/vscode/releases/tag/1.11.2
https://api.github.com/repos/microsoft/vscode/releases/latest

Steps to Reproduce:

1. Go to the urls above and see that 1.11.2 is tagged as the latest version

**Comment by NathanTheGr8** [comment]
![image](https://user-images.githubusercontent.com/2585114/57469437-47407b80-724c-11e9-966b-ac78242f54d2.png)

**Comment by Tyriar** [comment]
Weird, I guess we published a release accidentally 2 years ago. I deleted the release so it not says not found.
