### ISSUE TITLE
VSCode is stuck off screen.

### ISSUE THREAD

**Issue by smultani** [microsoft/vscode#73534]
- VSCode Version: 1.33.1
- OS Version: Windows 10 

Related to #35148, #36122

Steps to Reproduce:

1. Laptop connected to external monitor
2. Start vscode
3. Use normally
4. Leave VS code running and undock/disconnect from monitor
5. VScode is stuck offscreen
6. Attempted all these steps to fix: https://www.technipages.com/bring-off-screen-window-back-onto-screen. None of them worked
7. Restarted laptop
8. Started vscode - it is still stuck off-screen

How did I fix it:
1. I had to connect back to my external monitor to start using vscode again

This makes vscode unusable. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by msftrncs** [comment]
I cannot reproduce this.  My VS Code instance always switches to the laptop screen and resizes itself to fit in the screen.   There is probably some missing detail, a particular video driver or video feature that is tripping this.

I also don't see why VS Code wouldn't resond to the normal method for retrieving an off screen window (click on taskbar tile, ALT-SPACE, M, arrow-key, then move mouse.) 

However, I was able to get Explorer to lock up when I moved VS Code's window offscreen.  However, when I restarted Explorer, the VS Code window that had been off screen popped back to its original position.

**Comment by bpasero** [comment]
> I also don't see why VS Code wouldn't resond to the normal method for retrieving an off screen window (click on taskbar tile, ALT-SPACE, M, arrow-key, then move mouse.)

Possibly due to the custom menu, @sbatten ?

@smultani does it reproduce when you configure the title to be native?

**Comment by sbatten** [comment]
@sbatten custom menu/title does not prevent the alt+space m trick. In fact I use this sometimes myself.

**Comment by bpasero** [comment]
@sbatten is there something you want/can change?
