### ISSUE TITLE
Terminal Wrapping

### ISSUE THREAD

**Issue by brolewis** [microsoft/vscode#73540]
Issue Type: <b>Bug</b>

I hate to open a bug report, but haven't had any luck figuring out what I've done wrong. My terminal session will type-over the current line when it extended too long instead of wrapping to a new line. I have attached a couple of videos to demonstrate the problem. I also disabled all extensions and the problem persisted.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_90134|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-pull-request-github|Git|0.6.0
restructuredtext|lex|107.0.0
dotenv|mik|1.0.1
mssql|ms-|1.6.0
python|ms-|2019.4.12954
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.7.0
code-settings-sync|Sha|3.2.9
unique-window-colors|stu|1.0.51
vim|vsc|1.7.1

</details>

![Screen Recording 2019-04-12 at 7 21 32 AM](https://user-images.githubusercontent.com/1481911/57470713-b9ae5d00-7246-11e9-9933-ed5aef76a853.gif)
![Screen Recording 2019-04-12 at 8 20 58 AM](https://user-images.githubusercontent.com/1481911/57470715-bca94d80-7246-11e9-8eab-95afe5251661.gif)

**Comment by Tyriar** [comment]
What's in your `$PS1` environment variable? Do you have plugins for bash or something that tweak your prompt behavior?

**Comment by brolewis** [comment]
```
$ echo $PS1
$(show_virtual_env)\033]0;${PWD##*/}\007\ $(if [ -n "${VIRTUAL_ENV+x}" ]; then echo "🐍 "; fi)\ $(if [ "$SHLVL" -gt 1 ]; then echo "(${SHLVL}) "; fi)\ \[\e[${P_C_DEFAULT}\][\ \[\e[${P_C_CWD}\]\w\ \[\e[${C_PURPLE}\]$(__git_ps1 " (%s)")\[\e[${P_C_DEFAULT}\]\ $(if [[ $? == 0 ]]; then echo "\[\e[32m\]:)"; else echo "\[\e[31m\]:("; fi)\ \[\e[${P_C_DEFAULT}\]]\$ \ \[\e[m\]
```

I do have a personal script that updates my PS1:

[colorsh.sh.txt](https://github.com/microsoft/vscode/files/3170690/colorsh.sh.txt)

**Comment by Tyriar** [comment]
It's likely related to something in your script. Does it work if you remove the `🐍`?

**Comment by brolewis** [comment]
@Tyriar Yeah, I can definately step through each element of my `$PS1` and see if I can determine the cause; it just didn't even click that `$PS1` could be the cause.

**Comment by brolewis** [comment]
Ok, so removing the following snippet from my `$PS1` appears to have fixed the problem
```
\033]0;${PWD##*/}\007
```
which I added at one point to try and get the current working directory as the title of my terminal, but I have other mechanisms for managing that now, so deleting that one line got me where I needed. Thanks, @Tyriar, for the suggestion.
