### ISSUE TITLE
Crashes after last update

### ISSUE THREAD

**Issue by mrtkp9993** [microsoft/vscode#73543]
- VSCode Version: 1.33.1
- OS Version: macOS Mojave Version 10.14.4

Steps to Reproduce:

1. Open VS Code.
2. Whole system crashes in 5-10 minutes after opening VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Does the system freeze or slow-down or reboot? What do CPU and memory usage look like leading up to that?

**Comment by russellr86** [comment]
@chrmarti I just spent about 2 hours disabling extensions trying to figure out what was spiking my CPU.  Decided to remove all extensions and settings and do clean install, CPU still spiking to 100%.. downgraded to from 1.33.1 to 1.32.3, CPU issues went away immediately and have been normal since.

**Comment by mrtkp9993** [comment]
@chrmarti System freezes. Memory usage seems ok but CPU usage continuously increasing.

**Comment by chrmarti** [comment]
Which process uses that much CPU? Does this also occur with extensions disabled? (See https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu for detailed instructions.)

**Comment by mrtkp9993** [comment]
The issue occurs with extensions disabled.

I'll share profiling information.

**Comment by mrtkp9993** [comment]
```gpu-process``` gone over 100% before freezing the computer.

**Comment by russellr86** [comment]
Same here, no extensions clean install, even manually cleared all extensions and settings from drive. CPU pegs at 100%

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by mrtkp9993** [comment]
I cannot record the profiling result due to freezing.

**Comment by russellr86** [comment]
`Version:          Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS Version:       Darwin x64 18.5.0
CPUs:             Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)
Memory (System):  16.00GB (2.27GB free)
Load (avg):       2, 2, 2
VM:               33%
Screen Reader:    no
Process Argv:     -psn_0_47672692
GPU Status:       2d_canvas:                    disabled_software
                  checker_imaging:              disabled_off
                  flash_3d:                     disabled_software
                  flash_stage3d:                disabled_software
                  flash_stage3d_baseline:       disabled_software
                  gpu_compositing:              disabled_software
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                disabled_software
                  surface_synchronization:      enabled_on
                  video_decode:                 disabled_software
                  webgl:                        disabled_off
                  webgl2:                       disabled_off

CPU %	Mem MB	   PID	Process
    0	    98	 29529	code main
    0	    66	 29532	   gpu-process
    0	    98	 29895	   shared-process
    0	   246	 29939	   window (FlipImageTout.molecule.tsx — Frontend)
    0	     0	 29940	     /bin/bash -l
    0	    82	 29956	     extensionHost
  113	   279	 30121	       electron_node tsserver.js
    0	    82	 30138	         electron_node typingsInstaller.js typesMap.js
    0	    49	 30151	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=29956
    0	    49	 30082	     watcherService

Workspace Stats:
|  Window (FlipImageTout.molecule.tsx — Frontend)
|    Folder (Frontend): 121 files
|      File types: ts(35) tsx(18) js(14) json(11) eot(8) woff(8) woff2(6)
|                  DS_Store(3) map(3) ico(2)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  webpack.config.js(1)`

**Comment by russellr86** [comment]
@mjbvz I just want to re-iterate, that downgrading to 1.32.3 completely alleviates the problem.

**Comment by russellr86** [comment]
confirmed same exact issue with `1.34`

**Comment by mjbvz** [comment]
@russellr86 Please open a different issue

@mrtkp9993 Using the latest code insiders build, please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`
