### ISSUE TITLE
I would like to be able to clear the references list

### ISSUE THREAD

**Issue by m-wheeler** [microsoft/vscode#73548]
I would like to be able to clear the references history. Mine is now pages long with a scroll bar.
![references](https://user-images.githubusercontent.com/25334301/57482765-52020d00-725a-11e9-8a63-878715886563.PNG)

**Comment by guywald1** [comment]
Added a PR to add this in the repo for the extension: https://github.com/microsoft/vscode-references-view/pull/51.

**Comment by jrieken** [comment]
👏 @guywald1
