### ISSUE TITLE
Goto definition never returns

### ISSUE THREAD

**Issue by AlanNevill** [microsoft/vscode#73541]
Issue Type: <b>Performance Issue</b>

In javascript file highlighted a function call then right click and goto definition which is in the same file. 
Blue progress flash across top to panel but never returned.

VS Code version: Code - Insiders 1.34.0-insider (693a13cd32c5be798051edc0cb43e1e39fc456d9, 2019-05-08T21:17:09.160Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.92GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    86	 17240	code-insiders main
    1	   171	   472	   gpu-process
    0	    68	  4820	   shared-process
    0	    66	  9880	   window (Issue Reporter)
    0	   299	 12216	   window (bookingMaint.js - crud1 (Workspace) - Visual Studio Code - Insiders)
    0	    13	  3548	     electron-crash-reporter
    0	    11	  6796	     watcherService 
    0	     6	 16124	       console-window-host (Windows internal process)
    0	    36	 12984	     searchService
    1	   242	 14416	     extensionHost
    0	    16	  6464	       C:/xampp/php/php.exe c:\Users\User\.vscode-insiders\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:58816 --memory-limit=4095M
    0	     4	  4868	         cmd.exe /c "C:\xampp\php\php.exe -n -c C:\Users\User\AppData\Local\Temp\117A.tmp c:\Users\User\.vscode-insiders\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:58816 --memory-limit=4095M"
   23	   131	 16892	           C:\xampp\php\php.exe  -n -c C:\Users\User\AppData\Local\Temp\117A.tmp c:\Users\User\.vscode-insiders\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:58816 --memory-limit=4095M
    0	     6	  5772	         console-window-host (Windows internal process)
    0	     5	  8740	       "C:\Program Files\Git\cmd\git.exe" config --local branch.newCottageBook.github-pr-owner-number
    0	     6	  3960	         console-window-host (Windows internal process)
    0	     5	 15092	         git.exe config --local branch.newCottageBook.github-pr-owner-number
   18	    29	 10708	       electron_node eslintServer.js 
    0	     4	 14960	         C:\WINDOWS\system32\cmd.exe /d /s /c "npm.cmd config get prefix"
    0	    28	  7096	           "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" config get prefix
    0	     6	 16896	           console-window-host (Windows internal process)
    0	   130	 12924	       electron_node tsserver.js 
    0	    57	  7400	         electron_node typingsInstaller.js typesMap.js 
    0	     4	  7248	           C:\WINDOWS\system32\cmd.exe /d /s /c "npm install --ignore-scripts types-registry@latest"
   20	    30	 13404	             "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" install --ignore-scripts types-registry@latest
    0	     6	 13616	             console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (bookingMaint.js - crud1 (Workspace) - Visual Studio Code - Insiders)
|    Folder (crud1): 674 files
|      File types: php(430) jpg(77) sql(29) js(19) svg(14) json(11) txt(11)
|                  html(7) rst(7) key(6)
|      Conf files: package.json(1) launch.json(1);
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
apacheconf-snippets|eim|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.6.0
todo-tree|Gru|0.0.130
vscode-apache|mrm|1.2.0
python|ms-|2019.4.12954
csharp|ms-|1.19.1
powershell|ms-|1.12.1
debugger-for-chrome|msj|4.11.3
vscode-icons|vsc|8.6.0
markdown-all-in-one|yzh|2.3.1
bootstrap-v4-snippets|Zac|0.2.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please file an issue on the PHP extension you're using
