### ISSUE TITLE
Generic Window Background Color (eg. Settings window background color)

### ISSUE THREAD

**Issue by cyraid** [microsoft/vscode#73552]
As far as I've searched for, I can't seem to find how to set a different background color for windows that don't have an editor? There is editor.background, but a setting to have a color for windows like the settings window, etc.

**Comment by bpasero** [comment]
`editorGroup.emptyBackground`

**Comment by cyraid** [comment]
That doesn't seem to change the settings background, and extensions background .. But did help for an empty window! Happen to know the ones for the settings / extensions background, etc?
