### ISSUE TITLE
Unable to write windowsAllowConpty setting

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#73555]
While verifying https://github.com/microsoft/vscode/issues/73351

I was unable to set the new setting in the settings UI

![image](https://user-images.githubusercontent.com/6561887/57494332-8804b880-727d-11e9-9e01-0945c80805dc.png)

**Comment by roblourens** [comment]
It seems that having settings that start with "tasks" or "launch" is not allowed, because that is how we identify things in the tasks.json or launch.json?

**Comment by Tyriar** [comment]
Here's a fix for it by just moving the setting under terminal (it's temporary anyway). https://github.com/microsoft/vscode/pull/73562
