### ISSUE TITLE
Unable to debug a remote authority resolver extension

### ISSUE THREAD

**Issue by jasongin** [microsoft/vscode#73551]
Issue Type: <b>Bug</b>

Since updating VS Code Insiders sometime last week (sorry I don't know exactly which build), I've been unable to debug our remote authority resolver, using the same steps that had worked with builds prior to that.

First, some background... We have a resolver extension for the "cloudenv" remote authority. It has the appropriate activation event declared in package.json:
```
"activationEvents": [
  "onResolveRemoteAuthority:cloudenv"
],
```
And we register the resolver in the extension activate() function:
```
    context.subscriptions.push(
        vscode.workspace.registerRemoteAuthorityResolver('cloudenv', resolver));
```

This "Cloud Environments" resolver mostly works; in fact we demoed it at the build event. But not being able to debug it makes further development very difficult. I'm trying two approaches, both of which worked previously.

1. Launch VS Code with a remote URI specified directly in launch.json:
```
"name": "Launch Extension",
"type": "extensionHost",
"request": "launch",
"runtimeExecutable": "${execPath}",
"args": [
  "--extensionDevelopmentPath=${workspaceRoot}",
  "--folder-uri",
  "vscode-remote://cloudenv+..."
],
```
Now the launched VS Code seems to ignore the remote URI: the resolver extension does not get activated at all. It's the same if I launch from the command-line with the exact same arguments. But if I remove the `--extensionDevelopmentPath` arg (and actually install the extension) then the resolver does get activated. Apparently it can no longer handle both at the same time.

2. Open a remote folder via a command:
```
vscode.commands.executeCommand(
  'vscode.openFolder', vscode.Uri.parse('vscode-remote://cloudenv+...'));
```
Since launching a remote URI directly doesn't work, I tried first launching a local window and then opening a remote folder with a command. Then the resolver does get activated after the reload. But the debugger does not attach to it. Breakpoints in either the extension activate() method or the resolve callback don't get hit.

VS Code version: Code - Insiders 1.34.0-insider (693a13cd32c5be798051edc0cb43e1e39fc456d9, 2019-05-08T21:17:09.160Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jasongin** [comment]
I'm also seeing the first problem above with the `vscode-remote-wsl` extension. But I don't have the second problem there: I can debug the resolver after loading a remote URI from a command. I can't figure out what's different though; even if I strip our extension down to the absolute minimum code to register the resolver, the debugger doesn't attach when the resolver activates. Note the debugger _does_ attach to the command activation, so it's not a source map issue.

**Comment by LeuisKen** [comment]
I think this problem due to the code here: https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L1215

Maybe this behavior is by designed？

**Comment by jasongin** [comment]
So here's something interesting... if I set the VS Code debugger to break on **All Exceptions**, then after continuing past 7 exceptions in internal VS Code code (none in my extension code or dependencies) then it will hit my breakpoints. I suppose it could be just a timing issue, in that stopping at those other exceptions delays activation of my extension. (This is when using command activation; the launch.json activation still doesn't work.)

**Comment by jasongin** [comment]
@LeuisKen Thanks for the pointer, that might explain why that way of launching a remote authority folder URI (approach 1 above) doesn't work when debugging an extension. That seems overly restrictive though because it's breaking an extension development scenario that used to be very helpful.

I'm not aware of any public documentation for building a resolver extension beyond the [registerRemoteAuthorityResolver API](https://github.com/microsoft/vscode/blob/522eb0a04ceb9befbef90f5827d5cc06e22b106a/src/vs/vscode.proposed.d.ts#L113) added to `vscode.proposed.d.ts`.

**Comment by jasongin** [comment]
A couple further observations:
  - Breakpoints in _later_ steps of the resolver (after a couple seconds of work) may get hit.
  - If I have the resolver callback initially show a notification and wait for me to dismiss it, then afterward a debug breakpoint on the next line will get hit.

These seem to support the idea that there is a timing issue: something about the debugger is not initialized yet when the resolver callback is first invoked.

**Comment by weinand** [comment]
Since VS Code uses a [new debugger](https://github.com/microsoft/vscode-js-debug/), please let us know if you're still running into problems, and if so open an issue on that repo.
