### ISSUE TITLE
Git has made of itself a Repo of System32 on Hosts file opening

### ISSUE THREAD

**Issue by Stig124** [microsoft/vscode#73554]
Issue Type: <b>Bug</b>

1. Open a file located on System32, or is inside a subfolder, (I used Hosts (%windir%\system32\drivers\etc\hosts)
2. **Without** any user input on the opening, Source Control tries to find the System32 repo (not even /etc), as it fail, it configure the repo *(and show a error popup which says that there is too much active change (5k on the icon))* 
3. Here is the output :
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.21.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Windows\System32
> git fetch
> git status -z -u
> git show :drivers/etc/hosts
> git check-ignore -z --stdin
error: cannot open .git/FETCH_HEAD: Permission denied
> git ls-files --stage -- drivers/etc/
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git show :drivers/etc/hosts
> git ls-files --stage -- drivers/etc/
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied
> git fetch
error: cannot open .git/FETCH_HEAD: Permission denied

``` 
Even If Git explicitly return that the folder isn't a repo *(at the begining by the `git rev-parse --show-toplevel` command)* and that the permission to fetch is denied, It continues to repeat the command
EDIT : It successfully created a folder at %WINDIR%\System32\.git but as I said 

>and that the permission to fetch is denied,
 
Git made System32 a repo **without** any user action on the file opening which *as I think Is not normal*. Even when the file is closed Git continue indefinitly to refresh the Sys32 repo. You need to reboot the app in order to prevent Git to refresh.

> If you can repro it, retry with all of your extensions disabled (your friend here is the 'Developer: Reload Window With Extensions Disabled' command). If it still happens then there's a chance others here will be able to repro it too.

I did absoulutly nothing to repro it and already disabled my extensions

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (5.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.1.1
html-class-suggestions|And|1.0.7
gitkraken-glo|axo|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-npm-script|eg2|0.3.6
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
auto-close-tag|for|0.5.6
shell-format|fox|4.0.11
discord-vscode|icr|3.6.0
discord-js-tools|jas|0.0.3
Angular-BeastCode|Mik|8.0.6
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.13
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
Go|ms-|0.10.2
notepadplusplus-keybindings|ms-|1.0.2
powershell|ms-|1.12.1
team|ms-|1.149.2
material-icon-theme|PKi|3.7.0
quicktype|qui|12.0.46
java|red|0.44.0
vscode-yaml|red|0.4.0
vscode-hexdump|sle|1.7.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
@stig124 can you produce a clear set of repro steps for this? e.g.

1. Create dummy textfile called c:\foo\system32\drivers\etc\hosts
2. Open something in VSCode. From your description it sounds like you use "Open Folder" and point to c:\foo\system32
3. In VSCode browse to the hosts file and open it.
4. Discover that VSCode at some point created c:\foo\system32\.git subtree.

AFAIK VSCode would only create the git repo (see step 4 above) if you clicked this button after step 2:
![image](https://user-images.githubusercontent.com/6726799/57529620-416e9700-732d-11e9-868f-f5c3b35099a5.png)

If you can repro it, retry with all of your extensions disabled (your friend here is the 'Developer: Reload Window With Extensions Disabled' command). If it still happens then there's a chance others here will be able to repro it too.

**Comment by Stig124** [comment]
@gjsjohnmurray Done

**Comment by joaomoreno** [comment]
VS Code will not automatically create a repository without a user action. I also cannot reproduce this. Can you reproduce it from scratch?
