### ISSUE TITLE
No Intellisense shows using Ctrl+ Space on Chinese OS with English Mode

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#73557]
Copied from https://github.com/microsoft/vscode-azurearmtools/issues/184, posted by @v-xuanzh 

- VSCode Version: 1.34.0-insider
- OS Version: Win10

Steps to Reproduce:

**Version:** 1.32.0-insider (user setup)
**Node.js**: 10.2.0
**OS:** All
**Extension Version**: [20190305.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3720)

Steps to reproduce:
1. Make sure your machine is Chinese Operating System or installed the language package of Chinese.
2. Change the current mode to English.
![image](https://user-images.githubusercontent.com/34729022/53853694-60daf380-3f7b-11e9-959f-de8a9b5927e0.png)

3. Open one .json file on VS Code, try to press 'Ctrl + Space' on the opened file.
4. Check whether there is Intellisense list shows or not.

**Expect:**

The Intellisense list shows well.

**Actual**:
1. No Intellisense list shows.
2. The current mode has been changed to ‘Chinese Mode’ after pressing 'Ctrl +Space'.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Ctrl+Space is Windows' built in keyboard shortcut for switching IMEs. You may want to change it to others which don't conflict with VS Code's keybindings, or modify VS Code's keybindings.
