### ISSUE TITLE
Git smoke test failures on Linux

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#73558]
These two tests consistently time out for me on linux:
![Screen Shot 2019-05-09 at 5 25 41 PM](https://user-images.githubusercontent.com/3672607/57494730-863bf480-727f-11e9-875f-d3627a3b7284.png)

**Comment by joaomoreno** [comment]
@RMacfarlane I can't repro this on Linux. Do you still see it?

![image](https://user-images.githubusercontent.com/22350/58331578-b8318700-7e39-11e9-983f-f331a5b76ea0.png)
