### ISSUE TITLE
Breakpoint is duplicated if line is moved while editing the breakpoint condition

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#7356]
- VSCode Version: 1.2.0 stable
- OS Version: Tried it on OS X 10.10.5 and Ubuntu 16.04

Steps to Reproduce:

1. Open a file where breakpoints are supported
2. Set a breakpoint at any line
3. Right click the breakpoint and select "Edit Breakpoint"
4. While the "Edit Breakpoint" dialog is open, move the line where the breakpoint is set
5. Hit Enter to confirm the "Edit Breakpoint" dialog
6. The breakpoint gets duplicated, but it should just move like it does if escape is pressed instead of Enter.

Note that this reproes without actually starting debugging.

Here's a recording of the repro:

![double_breakpoint_repro](https://cloud.githubusercontent.com/assets/637952/15873703/b6abbed4-2cb4-11e6-8a33-913c7251c05c.gif)

@isidorn @weinand

**Comment by weinand** [comment]
@isidorn editing (or moving focus) should dismiss the peek.

**Comment by edumunoz** [comment]
@weinand, something to keep in mind is sometimes you might want to copy & paste a value from code into the condition of the breakpoint, which your suggested fix does not totally prevent, but makes it a little harder.

I'm ok with the suggestion, though. I just wanted to bring that up.

**Comment by isidorn** [comment]
@weinand we already had this discussin with @stevencl on whether focus lost should close the breakpoint widget and we came to the conlucission to not do that. One of the reasons is as @edumunoz points out - users might want to copy & paste. Though we try to make it easy for the user to close the widget by simple pressing esc when focus is anywhere.

**Comment by isidorn** [comment]
The issue here is that the breakpoint widget is talking about line 75 (as it correctly says in the message) and once you dismiss the widget with an enter that means you have entered a condition and a brekapoint on line 75 gets added. Though in the meantime you have moved the breakpoint on line 75 a couple of lines down. Thus in the end you get 2 breakpoints

I understand this can be a bit confuzing to the user - but not very important imho -> backlog

**Comment by isidorn** [comment]
Closing as 'do not plan to fix'. Will reopen if users complain about this behavior.

**Comment by ramya-rao-a** [comment]
Removing the "bug" tag so that this does not appear in the "need to be verified" list
