### ISSUE TITLE
Tools menu missing

### ISSUE THREAD

**Issue by JoeVincentt** [microsoft/vscode#73565]
![Screen Shot 2019-05-10 at 1 39 30 AM](https://user-images.githubusercontent.com/42827967/57505006-c96c8680-72c4-11e9-9ec4-f70c55240273.png)

Issue Type: <b>Bug</b>

Tools option is not presented in menu bar.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
expressjs|ama|2.0.0
ng-template|Ang|0.1.11
vscode-apollo|apo|1.6.4
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.0.1
flutter|Dar|3.0.1
es7-react-js-snippets|dsz|2.2.2
vscode-npm-script|eg2|0.3.7
eppz-code|epp|1.2.41
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
next-js|fox|0.0.2
expressjs-4-snippets|gur|1.0.2
icon-fonts|idl|2.1.5
vscode-angular2-emmet|jak|2.0.3
unity-code-snippets|kle|1.3.0
graphql-for-vscode|kum|1.13.1
csharpfixformat|Leo|0.0.81
vscode-cosmosdb|ms-|0.10.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.4.12954
azure-account|ms-|0.8.2
csharp|ms-|1.19.1
material-icon-theme|PKi|3.7.0
vscode-yaml|red|0.4.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.9
hyper-javascript-snippets|t7y|2.1.0
python|tht|0.2.3
unity-tools|Tob|1.1.0
unity-debug|Uni|2.7.2
JavaScriptSnippets|xab|1.7.2
unity-snippets|Ycl|0.1.2

(2 theme extensions excluded)

</details>

**Comment by jaqra** [comment]
Did you checked 'Window: Menu Bar Visibility' setting? It must be 'custom'

**Comment by chrmarti** [comment]
I'm not aware of a Tools menu. Could you explain where it should be shown?

**Comment by JoeVincentt** [comment]
![1VS2019-theme-1543982242505 (1)](https://user-images.githubusercontent.com/42827967/57545994-cd7ebf80-7329-11e9-9188-c972453c7711.jpg)

Here is a Tools menu

![Screen Shot 2019-05-10 at 1 41 37 PM](https://user-images.githubusercontent.com/42827967/57546007-d7082780-7329-11e9-9189-88337503de4e.png)

I am missing on this one.

![Screen Shot 2019-05-10 at 1 41 48 PM](https://user-images.githubusercontent.com/42827967/57546021-e1c2bc80-7329-11e9-8d24-3cfb95f0054b.png)
In the Window menu, I don't have any options.

**Comment by jaqra** [comment]
Visual Studio and Visual Studio Code are not same project. So there is no tools menu already on vscode

**Comment by chrmarti** [comment]
Indeed, thanks @jaqra!
