### ISSUE TITLE
git pull and code do not refresh and do not save

### ISSUE THREAD

**Issue by Dlogon** [microsoft/vscode#73564]
Issue Type: <b>Bug</b>

Hi

When i made a pull on git repo, the code do not refresh at actual commit , and then create a file, and write  lot of code and save, the file do not save.

I am so sad, cause this is not the first time

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
gitlens|eam|9.7.1
php-debug|fel|1.13.0
backbone-js-snippets|Hri|1.0.0
smarty|imp|0.3.0
php-cs-fixer|jun|0.1.119
vscode-language-pack-es|MS-|1.33.2
laravel-blade|one|1.20.0
code-spell-checker|str|1.7.9
code-spell-checker-spanish|str|1.0.1

</details>

**Comment by chrmarti** [comment]
When you tried to save, did you get a message box telling you that the file had changed on disk?
