### ISSUE TITLE
外部js方法不能跳转到定义的地方

### ISSUE THREAD

**Issue by xiaoweizhang** [microsoft/vscode#73563]
外部js方法不能跳转到定义的地方
提示“为找到***的定义”

**Comment by byyxx128** [comment]
Please describe in detail in English.
我都没看懂你说的啥，想帮你翻译都没法翻……

**Comment by xiaoweizhang** [comment]
Call the external js method, press F12, can not jump to the defined place, prompt "to find the definition of ***"
