### ISSUE TITLE
connot launch integration terminal

### ISSUE THREAD

**Issue by alannotnerd** [microsoft/vscode#73570]
Issue Type: <b>Bug</b>

I can launch powershell separatelly, but it shows "Cannot find drive. A drive with the name '.C' does not exist." when I launcher it in vscode. 
![image](https://user-images.githubusercontent.com/24879490/57515620-a635eb80-7345-11e9-9f24-e0aa68fccaee.png)
![image](https://user-images.githubusercontent.com/24879490/57515631-afbf5380-7345-11e9-8878-7e1f33971d08.png)
![image](https://user-images.githubusercontent.com/24879490/57515639-b51c9e00-7345-11e9-8b56-6844bb59a740.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.74GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
mdmath|goe|2.3.9
latex-workshop|Jam|6.5.1
python|ms-|2019.4.12954
powershell|ms-|1.12.1
vetur|oct|0.20.0
material-icon-theme|PKi|3.7.0
LiveServer|rit|5.6.1
vscode-leetcode|she|0.14.1
clang-format|xav|1.9.0

</details>

**Comment by Tyriar** [comment]
It's complaining about a psm1 file in conda, this doesn't appear to be an issue with vscode as powershell launches and tried to run some script that you (or an extension?) set up.
