### ISSUE TITLE
Go to definition does not work with Jinja Template files

### ISSUE THREAD

**Issue by rbhanot4739** [microsoft/vscode#73573]
- VSCode Version:1.33.1
- OS Version: Ubuntu 16.04 LTS

I am working on a Python Flask project which has number of Jinja Template files. The native Go to Definition/Declaration functionality does not work with Jinja files. I am not sure if it is a problem with Python extension not supporting Jinja files or VsCode not supporting Jinja files yet. 

Steps to Reproduce:

I have the following snippet from my Jinja template file.

```
{% extends "base.html" %}
{% from "_posts_jinja.html" import delete_post %}
{% block body %}
```
Now If I try to jump to let's say  `base.html` or `_posts_jinja.html` file or to `delete_post` macro inside the  `_posts_jinja.html`, VsCode shows a popup balloon saying "no definition can be found" for this symbol.

Infact these symbols in Jinja/html files are not even recognized or indexed because if I hit `ctrl-t` and try to look up for `delete_post` macro, it does not show up. However the other symbols in the python files show up just fine.

So am I missing something here or is it not yet supported feature in VsCode ?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
There seem to be a few extensions you could try: https://marketplace.visualstudio.com/search?term=Jinja&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by rbhanot4739** [comment]
I have already installed extensions for Python and Jinja and since it does not work even after installing the extension, i thought of reporting the issue.

**Comment by chrmarti** [comment]
@rbhanot4739 Please file an issue for the Jinja extension that seems the most promising then. You could also file an issue for the Python extension, but my guess is that Jinja templates are to specific for that.

**Comment by rbhanot4739** [comment]
Sure ! Will file issue for both Jinja and Python extension.
