### ISSUE TITLE
In-product keyboard shortcuts tutorial

### ISSUE THREAD

**Issue by 1Jesper1** [microsoft/vscode#73577]
Issue Type: <b>Feature Request</b>

Hello, I would like to have a Visual Studio Code keyboard shortcut tutorial build in Visual Studio Code to learn the Keyboard shortcuts.

OS version: Windows 10

**Comment by auchenberg** [comment]
Hi!

Have you seen our docs on keyboard shortcuts? https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-layouts

We also have these cheatsheets for each platform
- https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf
- https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
- https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

**Comment by 1Jesper1** [comment]
Very useful indeed! But how cool would it be to have a shortcut tutorial in Visual Studio Code itself? How I see it: Have a challenge for each shortcut to let the user know how he/she can use the shortcut.
E.g. Challenge for Ctrl+f (search for word in tutorial document): show challenge in popup, detect if user presses Ctrl+f, detect if user search for the word in the tutorial document.

**Comment by auchenberg** [comment]
@1Jesper1 That's a great idea. I've renamed the issue. Let's use this issue to track an In-product keyboard shortcuts tutorial

**Comment by 1Jesper1** [comment]
@auchenberg Nice, do you have some ideas on how to implement such an in-product keyboard shortcuts tutorial?
