### ISSUE TITLE
i can't install extensions

### ISSUE THREAD

**Issue by Ali1Ammar** [microsoft/vscode#73572]
Issue Type: <b>Bug</b>

i can't install some extensions like Azure cosmo , Mongorunner and Syu 
it is happen after update.
this extensions  don't work so i try to reinstall but it uninstall and won't to install agian 
i have some error when try install like
"Failed to install 'joeyyizhao.mongo-runner'."
"Failed to install 'teabyii.ayu'."
but before uninstall it I get this
"command 'cosmos DB.refresh' not found"
and like that for Mongorunner.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.95GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
go-snippets|ban|0.1.2
dart-code|Dar|3.0.1
flutter|Dar|3.0.1
azure-account|ms-|0.8.2
Go|ms-|0.10.2
go-doc|msy|0.1.1
material-icon-theme|PKi|3.7.0
vscode-icons|vsc|8.6.0

</details>

**Comment by Ali1Ammar** [comment]
i reinstall vscode and now i can install Azure cosmo , Mongorunner but it don't work 
 I get this
"command 'cosmos DB.refresh' not found"
"Running the contributed command: 'mongoRunner.refresh' failed."

**Comment by sandy081** [comment]
Please file an issue against cosmos extension why these commands are not working.
