### ISSUE TITLE
execvp(3): failed. No such file or directory

### ISSUE THREAD

**Issue by xiagw** [microsoft/vscode#73574]
- VSCode Version: 1.34.0-insider
Commit: daf71423252a707b8e396e8afa8102b717f8213b
Date: 2019-05-07T05:14:45.885Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-18-generic
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:

1.install zsh
2.install oh my zsh
3.remote ssh server default shell is bash
4.open vscode insider connect to remote server,
5.opening terminal in vscode, exit with "execvp(3): failed. No such file or directory"
6. but when installed zsh and oh-my-zsh on remote server, opening terminal is ok .

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/38
