### ISSUE TITLE
Expose FileSystemProvider stat information to the resource when clause

### ISSUE THREAD

**Issue by plus-** [microsoft/vscode#73576]
**Feature Request:**
Right now the [when clause context](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) for resources is limited to `resourceScheme` `resourceFilename` `resourceExtname` `resourceLangId`

When implementing a FileSystemProvider, it would be usefull to either be able to hook a function from the provider to the when clause context, or at least expose the result of the provider stat function for any given resource in order to use one of our custom boolean properties.

**Use case example:** 
Implementing a remote fs that supports locking resources, I would like to implement explorer contextual menu actions (lock or unlock) that are filtered based on the lock status of the resource.
This is the same idea behind any permission based actions.

**Comment by jrieken** [comment]
> Implementing a remote fs that supports locking resources,

Hm, the fs provider API doesn't support locking... How would you represent that in the stat model?

**Comment by plus-** [comment]
Well since any provider can extend the stat model it could be a non issue.

For example in [my fileSystemProvider](https://github.com/plus-/vscode-cmis/blob/master/src/cmisProvider.ts#L11) `stat` is returning my [own implementation of the FileStat](https://github.com/plus-/vscode-cmis/blob/master/src/cmisAdapter.ts#L7) to add some custom properties like `isCheckedOut` 

Now I'm not sure how the _when clauses_ are evaluated (is there a templating engine?), but my thinking was we could expose the stat result to do something like:

`stat.name == foo` or in my previous example we could evaluate on the fly when we right click:

```
"menus": {
    "explorer/context": [{
        "command": "cmis.cancelCheckout",
        "when": "resourceScheme == cmis && stat.isCheckedOut"
```

Hope it make sense

**Comment by jrieken** [comment]
> Well since any provider can extend the stat model it could be a non issue.

It actually is because the extension runs in a different process than the UI - in which context keys are evaluated. So, this actually is the challenge...
