### ISSUE TITLE
Drop `.txt` for new untitled files in Save As... dialog

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#73580]
`.txt` is usually not what you want:
![image](https://user-images.githubusercontent.com/9205389/57531150-1c802100-7339-11e9-972d-acdea26d0c37.png)

Maybe the 'new untitled file' is marked as a text document?

**Comment by alexr00** [comment]
There was actually a specific request to add the `.txt` 😄 On Windows, the `.txt` is automatically added. On Ubuntu, it is not added. This matches what the system file dialogues on Windows and Ubuntu both do.

**Comment by chrmarti** [comment]
There are many different file extensions used with VS Code. Replicating the system dialog's behavior makes it harder to set the filename with extension in all except the `.txt` case.

**Comment by alexr00** [comment]
I'll think about how we can pick a better default. Currently the file dialog receives an array of extensions, and both the simple picker and the system picker just grab the first one.

**Comment by chrmarti** [comment]
You could just drop the extension (or include it in the selection, but dropping seems preferable to me).

**Comment by alexr00** [comment]
To verify, enable the simple file picker with `"files.simpleDialog.enable": true` then use it to save an untitled file. Verify that `.txt` is not post-pended to the file name.
