### ISSUE TITLE
Have a context key to indicate which editor group is focused

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#73586]
In a custom key binding, is there a way to specify a `when` clause of "when the first editor group is in focus" ? I read everything is the [keybinding doc](https://code.visualstudio.com/docs/getstarted/keybindings), but didn't find the answer. 

I did find two conditions that I suspect might help, but couldn't understand what it meant. Did some guessing and experiments, but no luck:

Context name | True when
-- | --
view | True when view identifier matches. Example: "view == myViewsExplorerID".
viewItem | True when viewItem context matches. Example: "viewItem == someContextValue".

**Comment by alexandrudima** [comment]
I think this can only work if a new context is added specifically for the first editor group.
