### ISSUE TITLE
"editor.fontFamily" does not change pop-up window font

### ISSUE THREAD

**Issue by Azureki** [microsoft/vscode#73583]
I use `fire code`, and the font of  code  is changed, while the parameter hints are not.

- VSCode Version: 1.33.1
- OS Version: linux x64

Steps to Reproduce:

1. Input a function, and then its definition will pop up.
2. The font of its definition is different from the code.

<img width="345" alt="issue" src="https://user-images.githubusercontent.com/22387028/57534285-4570d800-7372-11e9-96f5-ae0545de1fa6.png">

(Well, In fact, the first line uses `fira code`.)

I also use the develop tools. 
<img width="747" alt="first-line" src="https://user-images.githubusercontent.com/22387028/57534490-b87a4e80-7372-11e9-8fbd-a784d9a015ab.png">

<img width="755" alt="docs" src="https://user-images.githubusercontent.com/22387028/57534591-f11a2800-7372-11e9-9019-b5a58aa3945d.png">

The `code` uses `fira code`, while `docs` not.

Does this issue occur when all extensions are disabled?:  
No...If all extensions were disalbed, there would  be not function definition window.

**Comment by sandy081** [comment]
It is expected that doc is not code and hence it does not uses editor font.

**Comment by Azureki** [comment]
@sandy081 Thanks.
Then is there a easy way to change font of `doc`?  
Or can you tell me what font does it use? The system font?

**Comment by sandy081** [comment]
it uses the same font that workbench uses. I assume its the system font but can't confirm. @bpasero will know it.

**Comment by Azureki** [comment]
Thanks for your reply.  
Changing workbench font works. I have no more problem.  
Ref:  
#519  
#26128
