### ISSUE TITLE
After scrolling with the thumb, it unselects the file list or open editors

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/vscode#73587]
- VSCode Version: 1.33.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Select multiple files in the "Open Editor" or your project file list.
2. Scroll the list with a mouse click with the thumb

ACTUAL:
The files becomes unselected

EXPECTED:
Keep the file selection

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Can you repro with latest vscode insiders https://code.visualstudio.com/insiders/
If yes can you please attach a video showing the issue. Thanks!

**Comment by jsgoupil** [comment]
I can repro on insiders build.

[20190513_132204.zip](https://github.com/microsoft/vscode/files/3174672/20190513_132204.zip)

**Comment by isidorn** [comment]
This looks like a tree issue. Forwarding to @joaomoreno as he might have better ideas

**Comment by joaomoreno** [comment]
> with the thumb

What does this mean?

**Comment by jsgoupil** [comment]
https://tkdocs.com/images/scrollbar_elements.png
