### ISSUE TITLE
Reverse like button for find and replace

### ISSUE THREAD

**Issue by lmlacerda** [microsoft/vscode#73585]
Hello!

First of all just let me congratulate the team for a fantastic tool. I have searched similar issues but haven't found what I was looking for.

What I would like to propose is that when you open the find and replace box, there is a button/shortcut to reverse from what you want to find and replace (similar to when you search for directions on google maps from home -> work and then work->home).

<img width="730" alt="Screen Shot 2019-05-10 at 16 34 16" src="https://user-images.githubusercontent.com/26628337/57539072-93b9b300-7341-11e9-868b-c27e4e09cee4.png">

Cheers!

**Comment by roblourens** [comment]
Interesting idea! I am not sure that it would be generally useful, and it wouldn't work when you are using any of the switches in the find box. People might assume that it would "undo" their previous replacement but it would not always work that way. But I will leave open for comments.

**Comment by HA07Z7XE** [comment]
Personally I'm not seeing the use case for this either. Maybe if you aren't using scm and need to undo a find/replace. I've never found myself needing to switch these round

**Comment by WayneLambert** [comment]
This definitely does have a use case. I am currently switching between two domain names within my code base, back and forth, and thought I would check to see if this has been requested yet.

It is of course easy enough to type the changes between the two but a switch-like button like @lmlacerda suggested would be a great little addition.
