### ISSUE TITLE
tryShowTextDocument failed to show text document ..., should show in editor #undefined

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#73595]
- VSCode Version: 1.33.1
- OS Version: MacOS 18.5.0

Steps to Reproduce:

Our extension runs the following code snippet when user opens a file in source control panel for the guest in Live Share collaboration session. Our customers reported that it fails with `Failed to show text document vsls:.... should show in editor #undefined` error in [Live Share github issue #2078](https://github.com/MicrosoftDocs/live-share/issues/2078). In vscode sources I see that [`showTextDocument()`](https://github.com/microsoft/vscode/blob/56693de122b1345d9df1c2c37fb2cb7a23705bf7/src/vs/workbench/api/common/extHostTextEditors.ts#L82) can throw this error.

Is there anything our code is doing incorrectly? Is there anything we can do to workaround the issue (e.g. catch and ignore exceptions from `showTextDocument`)? Or is there anything we can do to help you guys investigate and fix this issue? Given that we cannot repro it ourselves, creating a small repro extension is not an option yet.

Here is [our code](https://devdiv.visualstudio.com/DevDiv/_git/Cascade?path=%2Fvscode%2Fextension%2Fsrc%2FsourceControl%2FguestSourceControlManager.ts&version=GBmaster&line=798&lineStyle=plain&lineEnd=799&lineStartColumn=1&lineEndColumn=1) that fails:

```typescript
// uris array contain one uri with vsls: scheme for which we have registered a file system provider.

            const activeTextEditor = vscode.window.activeTextEditor;
            for (const uri of uris) {
                const opts: vscode.TextDocumentShowOptions = {
                    preserveFocus,
                    preview: false,
                    viewColumn: vscode.ViewColumn.Active
                };

                const document = await vscode.workspace.openTextDocument(uri);

                if (activeTextEditor && activeTextEditor.document.uri.toString() === uri.toString()) {
                    // preserve not only selection but also visible range
                    opts.selection = activeTextEditor.selection;
                    const previousVisibleRanges = activeTextEditor.visibleRanges;
                    const editor = await vscode.window.showTextDocument(document, opts);
                    editor.revealRange(previousVisibleRanges[0]);
                } else {
                    await vscode.window.showTextDocument(document, opts);
                }
            }
```

It is very similar to git extension code that does the same thing.

Does this issue occur when all extensions are disabled?: No. Our customer reported it only with Live Share extension

**Comment by jrieken** [comment]
> Given that we cannot repro it ourselves, creating a small repro extension is not an option yet.

That's kinda what we need. So, you guys implement a document content provider or a file system provider for that scheme? Do you log errors? Do customers see errors on the console?

**Comment by IlyaBiryukov** [comment]
Yep, we have registered a `vscode.FileSystemProvider` for `vsls:` scheme. There are no errors logged from that provider in the customer logs. Does VSCode read the document in `workspace.openTextDocument()` or in `window.showTextDocument()`?

I've asked the customer to check out the dev tools console.

If we ignore that exception from `showTextDocument`, is anything else going to be broken?

**Comment by jrieken** [comment]
> There are no errors logged from that provider in the customer logs. Does VSCode read the document in workspace.openTextDocument() or in window.showTextDocument()?

cc @bpasero for that... the code calls [`openEditor`](https://github.com/Microsoft/vscode/blob/1e663934f17ac7eb00e043533b9d3712ad40d713/src/vs/workbench/api/browser/mainThreadEditors.ts#L129-L134) and doesn't seems to get an editor, nor an error

> If we ignore that exception from showTextDocument, is anything else going to be broken?

Yeah, you don't have an editor, so that's broken for sure...

**Comment by bpasero** [comment]
Timing issue maybe? After all the error originates from the extension host side and not the main side, so the editor could be there but maybe not synchronized over yet. Just speculation though without a repro. I cannot make a statement about error logging without seeing this for myself with a sample...

**Comment by jrieken** [comment]
> After all the error originates from the extension host side and not the main side, so the editor could be there but maybe not synchronized over yet.

No, the editors (which means documents) are sync'd as soon as they come to live. The underlying issue (and that why the extension host throws an error) is that `openEditor` returns nothing.

**Comment by bpasero** [comment]
That will happen if the opening of an editor fails for some reason. It should print an error to the dev tools, though that may not contain a lot of info.

**Comment by jrieken** [comment]
not actionable
