### ISSUE TITLE
OutputEvents now have newlines appended to them

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#73593]
Recently I've noticed output sent from my debugger is getting lots of newlines in:

![newlines](https://user-images.githubusercontent.com/1078012/57554210-bf03c880-7368-11e9-99a4-7fd649dab569.png)

It seems that every `OutputEvent` is getting its own newline, even though this is often output from another process being streamed and should be untouched.

Here's a simple code example:

![output event newlines](https://user-images.githubusercontent.com/1078012/57554127-7c41f080-7368-11e9-9881-0a628db349cb.png)

**Comment by isidorn** [comment]
Isi this with latest insiders? We fixed an issue in this area recently.

**Comment by DanTup** [comment]
Aha, sorry, it's fine in latest Insiders 👍  I failed to find existing issues at the time, but now I just found https://github.com/microsoft/vscode/issues/72110 which this seems a dupe of.

Thanks!
