### ISSUE TITLE
Breadcrumbs bar with GitLens revisions/diffs

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#73594]
Issue Type: <b>Bug</b>

Originally reported: https://github.com/eamodio/vscode-gitlens/issues/739

The breadcrumbs bar shows up for GitLens revisions, both in diffs and in normal editors, but doesn't function (as you can see in the image it just opens an empty menu).

![image](https://user-images.githubusercontent.com/641685/57556096-12175480-7344-11e9-8c95-1cae44695462.png)

Is there a way to disable the breadcrumbs bar when it "shouldn't" apply (or won't work properly)? Or is there something that I can be doing to make it work?

/cc @jrieken 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
@eamodio Do you implement a file system provider?

**Comment by eamodio** [comment]
I do: https://github.com/eamodio/vscode-gitlens/blob/26cbee6d60554e201d61226510e3d33b0eba5557/src/git/fsProvider.ts

**Comment by jrieken** [comment]
@eamodio This is actually an issue with the provider. For some reason it doesn't return `gitlens://commit/path/foo.js` when asking for children of `gitlens://commit/path/`

**Comment by eamodio** [comment]
@jrieken I'll look more into that. But I would still consider the empty dropdown a bug. Especially even if I can fix the provider to return the correct data, I won't be able to for the earlier parts of the path (that are outside the repo completely)

**Comment by jrieken** [comment]
Hm... I would also assume that I am a child of my own parent... That's why I don't wanna jump on tweaking the picker yet, the element on which you have clicked you always show...

**Comment by eamodio** [comment]
@jrieken So I've partially fixed the issue:

![image](https://user-images.githubusercontent.com/641685/57908139-4eb7e400-784d-11e9-90ac-4aaf295c2fd2.png)

In the above example, if I click on `fsProvider.ts`, `git`, or `src`, everything works, because my file system provider will return the files (because those paths are inside the repo), but clicking on any of the parents won't work, because they are outside the repo, so the fs provider throws `FileSystemError.FileNotFound`

Looking at the breadcrumbs code, it tries to look up a workspace folder for the Uri, but since it is using `.toString()` vs `.fsPath` it won't find one. I wonder if there is a way to either have a fallback to `.fsPath` there, or some way to express a "root" for a uri or something like that.

**Comment by jrieken** [comment]
> In the above example, if I click on fsProvider.ts, git, or src, everything works, because my file system provider will return the files (because those paths are inside the repo),

Oh, that's a lot more than I was thinking about ;-). I thought it's enough to have the path itself being contained, e.g. without sibling from the `file`-world. So `code` has 1 child which is `vscode-gitlens`, that has one child being `src` etc

**Comment by eamodio** [comment]
@jrieken yeah, I tried making the url be a relative path, but that caused me a bunch of issues, since I'm currently assuming all the Uris are absolute paths -- just like the `git:` uris are
