### ISSUE TITLE
Same file appears twice in today's insider build - vscode thinks from two different paths

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#73596]
I noticed in my open editors that the same file was listed twice.  Once with an absolute path and again with a relative path (also differing in case).  Those paths on Windows are the same.  My workspace root is `C:\users\hillr\git\pskal`.

![image](https://user-images.githubusercontent.com/5177512/57558905-dc22a200-733c-11e9-8757-ef2e97f7123b.png)

- VSCode Version: 1.34.20-insider (system setup)
- OS Version: Windows 10 1809

Steps to Reproduce:
I'm not sure how I got into this state to be honest.

Does this issue occur when all extensions are disabled?: Don't know, can't easily repro.

**Comment by chrmarti** [comment]
Do both come and go with the same editor? What if you close all editors?

**Comment by isidorn** [comment]
This is from the editorGroupService, forwarding to @bpasero as he might have more questions.
