### ISSUE TITLE
Strange Behavior in Terminal/command window

### ISSUE THREAD

**Issue by pevans360** [microsoft/vscode#73591]
Issue Type: <b>Bug</b>

Description:
When a terminal window is opened, there's no cursor next to the prompt.  Start to type and the prompt disappears and the typed command appears ... still no cursor.  

Expected behavior:
Cursor should appear next to the prompt and typed commands should appear at the cursor.  

Steps:
user: open VS Code
user: open a project
user: open a terminal window (ctrl+` )
system: opens terminal window
	system prompt appears
	there is no cursor
user: start to type a command
system: prompt disappears
	typed letters appear
	still no cursor
user: finish typing command and press Enter
system: starts to execute the command

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (3.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
debugger-for-chrome|msj|4.11.3

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
