### ISSUE TITLE
disable bracket auto closing in string?

### ISSUE THREAD

**Issue by towry** [Microsoft/vscode#736]
Bracket auto closing in string will make string concat in JS difficult.

For example, `|` is the cursor position:

`'translate'` -> `'translate(|)'` -> `'translate(' + '|')'`

What I want is `'traslate(' + ')'`, I have to remove a quote to wrap the last `)` in string.

**Comment by rebornix** [comment]
Closing this first as now I can't reproduce this issue and it has been more than 1 year. Feel free to reopen it if you still have this issue.

**Comment by towry** [comment]
Confirm bug fixed.
