### ISSUE TITLE
setting.json: editor.scrollbar.horizontal  suggestion 'Unknown configuration setting'

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [microsoft/vscode#73609]
- VSCode Version: 1.33
- OS Version: macOS 10.14.4 

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Please see the picture:
![B7F2EC42-02A7-4E39-B2ED-08D52DEEC46C](https://user-images.githubusercontent.com/22312092/57565699-046dd780-73f5-11e9-9440-98ef87ed3c4d.png)

**Comment by alexandrudima** [comment]
@Mr-jiangzhiguo You are using a non-official setting "editor.scrollbar.horizontal" to permanently hide the horizontal scrollbar. You have two options:
- remove the setting and see horizontal scrollbars and not have warnings.
- keep the setting and not see horizontal scrollbars, but have a warning in your settings.json.

The choice belongs to you.

**Comment by Mr-jiangzhiguo** [comment]
ok
