### ISSUE TITLE
Toggle case block on switch

### ISSUE THREAD

**Issue by dathoangnd** [microsoft/vscode#73605]
Issue Type: <b>Feature Request</b>

Can you please consider to add feature that toggle code block in each case branch so it would be easier to navigate between case branches in switch-case?

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.18.0-17-generic

**Comment by chrmarti** [comment]
Which languages would you like this for? Could you give a before/after example?

**Comment by mjbvz** [comment]
Closing as more information is needed, see https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
