### ISSUE TITLE
Git: avoid asking to save unstaged files when commiting

### ISSUE THREAD

**Issue by jrz** [microsoft/vscode#73613]
Issue Type: <b>Bug</b>

If you've staged some changes and you have dirty files open, you get a prompt to save all files. This is unneccessary 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
So you'd suggest not to prompt to save files whenever there are staged changes? What if the unsaved file is also in the staged changes?

**Comment by jrz** [comment]
No. The suggestion is to ignore unstaged files

So:  
If a file hasn’t been staged, but is dirty, don’t even offer to ask for that file. 

Or:
Go through all staged files. Check if any of them have dirty editors, if so, offer to save them and stage them 

When someone does a commit all.m, the current behavior makes sense

Staged:
F1
F2 dirty editor
F3 
F4
Unstaged:
F2 - dirty editor -> ask
F3 - dirty editor -> ask
F5 - dirty editor 

No change (saved file is still same as staged):
F4, but dirty. -> ask

**Comment by joaomoreno** [comment]
Verification:

1. Have two SCM resources: file A, modified in the index and file B, unstaged in the working tree
2. Have unsaved changes in both

Then:

1. Try to commit. It should warn about unsaved changes in A. Cancel that.
2. Save A and try to commit. It should succeed.
1. Try to commit. It should warn about unsaved changes in B. Accept it.
4. Repo should have no changes any more.

**Comment by alexr00** [comment]
I'm never getting warnings about unsaved changes.

**Comment by joaomoreno** [comment]
@alexr00 Make sure you disable auto save.

**Comment by alexr00** [comment]
I did disable autosave :)

**Comment by joaomoreno** [comment]
![Peek 2019-10-31 10-48](https://user-images.githubusercontent.com/22350/67936414-08bcc580-fbcc-11e9-9bcd-535536874124.gif)

**Comment by alexr00** [comment]
I must be doing something wrong...
![commiting](https://user-images.githubusercontent.com/38270282/67938167-440cc380-fbcf-11e9-82fa-56cc653f61de.gif)

**Comment by joaomoreno** [comment]
@alexr00 Check the setting maybe:

![image](https://user-images.githubusercontent.com/22350/67938356-9a7a0200-fbcf-11e9-844a-08bbed9ffb0c.png)

**Comment by alexr00** [comment]
Yep, it's set to always.

**Comment by alexr00** [comment]
Only `"git.ignoreLimitWarning": true,`, which comes from the VS Code workspace settings.
I don't have any git user settings set
`

**Comment by joaomoreno** [comment]
Yup, just tried it in Windows, completely broken!

**Comment by joaomoreno** [comment]
OK that took a while...

![image](https://user-images.githubusercontent.com/22350/67966265-e0e95400-fc03-11e9-8026-aa3288aa2679.png)

**Comment by joaomoreno** [comment]
@alexr00 The whole feature was simply never working for Windows since forever. :fearful: Thanks for testing!
