### ISSUE TITLE
VS Code Crashes while working on Angular

### ISSUE THREAD

**Issue by ihybrid11** [microsoft/vscode#73616]
Issue Type: <b>Performance Issue</b>

Hi Team,
While working on Angular projects - yes I face this issue specifically while working with Angular projects - when I make some changes in a file and try to save it, VS Code hangs and it also hangs my system and I have to do a restart. Sometimes even force restart is required.

Other windows opened while working on this is Chrome only with 1 or at max 2 tabs running localhost output and stackoverflow or angular documentation.

Please let me know if I can do something from my end to provide you more information or to get this fixed.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    84	  5300	code main
    0	    64	  3900	   shared-process
    0	    68	  8808	   window (Issue Reporter)
    0	   197	 12928	   window (home.component.ts - locator - Visual Studio Code)
    0	    12	 10568	     electron-crash-reporter
    0	    11	 11056	     watcherService 
    0	     9	 12560	       console-window-host (Windows internal process)
    0	    39	 12396	     searchService
    0	   138	 15284	     extensionHost
    0	    90	  4572	       electron_node server.js 
    0	    34	  6540	       "C:\Users\Ultron\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Ultron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=15284
    0	    95	  7712	       electron_node server.js 
    0	    73	  9332	       "C:\Users\Ultron\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Ultron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=15284
    0	   146	 13336	       electron_node tsserver.js 
    0	    44	  3920	         electron_node typingsInstaller.js typesMap.js 
    0	    85	 12968	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (home.component.ts - locator - Visual Studio Code)
|    Folder (locator): 73 files
|      File types: ts(21) js(9) json(9) map(7) html(7) css(6) ico(2) jpg(2)
|                  editorconfig(1) svg(1)
|      Conf files: tslint.json(2) package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
node-snippets|chr|1.0.0
javascript-ejs-support|Dig|0.5.0
Angular2|joh|7.1.5
Angular-BeastCode|Mik|8.0.6
vscode-css-peek|pra|2.2.0
ejs-snippets|Tao|0.1.0
html-css-class-completion|Zig|1.18.0

</details>

[operation_log.txt](https://github.com/microsoft/vscode/files/3169045/operation_log.txt)

**Comment by chrmarti** [comment]
Sounds similar to #73543. Did you see this with 1.32?

**Comment by jrieken** [comment]
not actionable
