### ISSUE TITLE
UI suggestion for the Composite Title's font weight

### ISSUE THREAD

**Issue by pmkary** [microsoft/vscode#73612]
Can we have the "explore" text to be bold?. Almost everything in VS Code is bold around Explore, but itself, which makes it weird...

So this is the normal version (font-weight: 400)

<img width="451" alt="Screen Shot 1398-02-21 at 11 36 58 AM" src="https://user-images.githubusercontent.com/2157285/57566396-3ecd7980-73e1-11e9-9866-c923564fa617.png">

And this is the very bold version (font-weight: bold)

<img width="560" alt="Screen Shot 1398-02-21 at 11 42 04 AM" src="https://user-images.githubusercontent.com/2157285/57566469-290c8400-73e2-11e9-9fad-730fcdd25eec.png">

Both of which are weird. But if you go for a weight between, it becomes very nice on (font-weight: 550)

<img width="589" alt="Screen Shot 1398-02-21 at 11 42 56 AM" src="https://user-images.githubusercontent.com/2157285/57566478-43466200-73e2-11e9-89dd-547e842af916.png">

<br><br>

And it's just so easy to spot the difference it makes: Full-screen on 400:

<img width="1280" alt="Screen Shot 1398-02-21 at 11 49 19 AM" src="https://user-images.githubusercontent.com/2157285/57566554-fd3dce00-73e2-11e9-8ea2-f77c3652e064.png">

Full-screen on 550:

<img width="1280" alt="Screen Shot 1398-02-21 at 11 50 03 AM" src="https://user-images.githubusercontent.com/2157285/57566575-64f41900-73e3-11e9-8b76-6f4bd1157ee7.png">

And it's also true on dark themes:

<img width="1280" alt="Screen Shot 1398-02-21 at 11 52 47 AM" src="https://user-images.githubusercontent.com/2157285/57566577-6b829080-73e3-11e9-9127-e56aff9a7a07.png">

**Comment by misolori** [comment]
@pmkary thanks for the suggestion! I believe this is intentionally not bold because the explorer items are meant to be the primary focal point, as opposed to the title, and to reduce a bit of the visual noise. 

I'd love to know more about why you'd like this to be bold, besides unification.

**Comment by pmkary** [comment]
@misolori thanks a lot for the kind words :D &bullet; Very light-weighted typefaces&mdash;while are excellent on the print&mdash;really should not be used within the monitor screens. That is because the printed page does not have back lamps, but the screen has and therefore the white space around the typeface produce such white lights that makes it both harder to read the text, and the typeface to look bad and not as clean as it should.

So it's actually a rule of thumb for design that you shouldn't really use light-weighted typefaces on the screen's text (and if you're doing you should have extremely big titles not the normal text). 

To me it's not unification, but rather pixel perfect design. That light titles makes the design to have less quality than when it can be with a better typeface setup. 

For the point of focal point, I agree, but the eye-flow can also be adjusted via the choice of colors, which as far as I've seen the native themes within the vscode itself and most of the major community themes have colors that already implement a great focal point. So 100 units of type weight won't make that much of problem, that it can do to help vscode have a nicer look.

Again, thanks for the kind words and you're every-going great work ❤️

**Comment by misolori** [comment]
@pmkary thanks for expanding on that! We actually are using the default/normal font-weight for the title, which is not light:

https://github.com/microsoft/vscode/blob/41991cdf493da72ecf7fba854f1ec9516a5c8687/src/vs/workbench/browser/media/part.css#L41-L44

I'll leave this open in case others feel the same. Thanks!

**Comment by pmkary** [comment]
@misolori I used white as an adjective, it's technically regular (that's why I said weight 400) but then as you can see it's just really better on 550. 400 makes the font not be rendered pixel perfect and the design to be weird. I hope this simple change be accepted because it's just a very simple thing that results in a very nicer design.
