### ISSUE TITLE
Please do not use esoteric jargon in the error messages

### ISSUE THREAD

**Issue by zhulika** [microsoft/vscode#73611]
I'm not sure whether this error is reported by VSCode itself or some extension. Does anyone recognize the cause? It's being displayed in a header file that is part of a Windows node-gyp (C++) project that just builds fine:

http://prntscr.com/nn3zm1

Can someone translate it for me into normal English? Thanks. :)

**Comment by chrmarti** [comment]
Please file for https://github.com/microsoft/vscode-cpptools
