### ISSUE TITLE
Cannot go to Definition that Importing a module from node_modules  without open a folder

### ISSUE THREAD

**Issue by supperchong** [microsoft/vscode#73610]
- VSCode Version:1.33.1
- OS Version:Windows_NT x64 10.0.17763

Steps to Reproduce:

1.Open a javascript file without open a folder.
2. Go to the definition of a symbol that import  from node_modules or Node.js built-in module.
![image](https://user-images.githubusercontent.com/26317926/57566017-156d1780-73fa-11e9-9825-8c48d7945073.png)

It will await all the time and cause memory leak.
![image](https://user-images.githubusercontent.com/26317926/57566036-6250ee00-73fa-11e9-9c6a-dc194bf4a6a7.png)

It is ok only when open a folder that contain node_modules where the javascript file import from.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I can't repo this in the latest vscode insiders. Are you still seeing this? Is the js file next to `node_modules`?
