### ISSUE TITLE
Search UI in file can block a result.

### ISSUE THREAD

**Issue by cfjedimaster** [microsoft/vscode#73619]
Issue Type: <b>Bug</b>

This is pretty rare, but imagine you have a file open and are looking for X. There are 2 results. As you navigate through them, you can see result 2, but not the first. Why?

The first match is on line one towards the right of the editor pane and is covered by the file UI itself. 

Now that I know it happened I'll know to look for it in the future, but it's still something that maybe the UI could handle better.

VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
simple-timer|bur|1.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vscode-great-icons|emm|2.1.47
coldfusion|ili|1.0.1
search-node-modules|jas|1.3.0
vscode-sshfs|Kel|1.16.2
wordcounter|kir|1.6.0
dotenv|mik|1.0.1
vetur|oct|0.20.0
material-icon-theme|PKi|3.7.0
polacode|pnp|0.3.2
htmlescape-vscode-extension|ray|0.0.6
java|red|0.44.0
nativescript|Tel|0.10.0
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-maven|vsc|0.16.2
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
We fail to reveal the find result when it's being covered by the find widget.
