### ISSUE TITLE
Limited 'Source Controll Providers' view

### ISSUE THREAD

**Issue by rutkowskimarek** [microsoft/vscode#73621]
Issue Type: <b>Bug</b>

I think can disply only 11 providers. I see only 11 form my 14 submodules (i have more but for nao i reduce the number of them). 

1 superproject and 14 submodules.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.80GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.26.0
xml|Dot|2.4.0
vscode-npm-script|eg2|0.3.7
latex-workshop|Jam|6.5.1
vscode-nuget-package-manager|jmr|1.1.6
cpptools|ms-|0.23.0
csharp|ms-|1.19.1
powershell|ms-|1.12.1
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
vscode-docker-registry-explorer|Tqr|0.1.3
vscode-icons|vsc|8.6.0

</details>

**Comment by joaomoreno** [comment]
You should be able to scroll that list. Also, you can control how many providers taht list can show without scrolling with the `scm.providers.visible` setting.

**Comment by rutkowskimarek** [comment]
> You should be able to scroll that list. Also, you can control how many providers taht list can show without scrolling with the `scm.providers.visible` setting.

I not that dumb to do not scroll - I have set value to zero and I VSCode do not attach to list more than 11 - not UI - here no list Item!!!
