### ISSUE TITLE
Remember scroll position in SCM changes list when switching to other views and back

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#73622]
Issue Type: <b>Feature Request</b>

Not remembering the scroll position makes it very annoying in certain situations, esp. with long change lists during merging of upstream changes. It also resets to the top. The explorer on the other hand remembers the position.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by hwhung0111** [comment]
I would like to try to resolve this.

**Comment by babakks** [comment]
Since I saw no changes going on, I made a fix (PR #74723). Hope it helps.
