### ISSUE TITLE
Proposal: Visual Spatial Focus Selection

### ISSUE THREAD

**Issue by matthewwithanm** [microsoft/vscode#73620]
I often find myself using the mouse to get around the workspace. There are just way too many keyboard shortcuts to have to memorize to be able to do it. It would be great if there were a way to do it spatially. I would've taken a shot at just doing this in code but I know UI changes should go through the UX team so I just faked a video quick instead:

![small](https://user-images.githubusercontent.com/126263/57571738-8e527c00-73c6-11e9-8601-25bd939df5a8.gif)

A summary:

- While a certain key or combination is held down, the arrows (or wasd) can be used to select the item to focus. Once the modifier key is released, the focus is given to the selected item.
- Editors, sidebar views, panel views, terminals, and tabs (or analogous navigation buttons in the sidebar and panel cases) are all available via this method. In the case of a tab-like being selected, the item it represents receives the focus.
- When navigating, tab containers are skipped if there's only one tab in them.
- Tab containers can only be entered via a direction perpendicular to their orientation (e.g. you can't → from the sidebar and wind up selecting a tab).
- When the selection moves to a tab container (or analogous in the case of the sidebar and panel), the tab representing the currently active view is always selected first.
- The selection opens the sidebar and panel but, if you change the selection to something outside of them without releasing the modifier, they're closed again.

Just to drive the point home: I made the video using a script of keyboard shortcuts (and then overlayed the focus border and key indicators) and it took 10 different shortcuts! (And that's counting `⌘K ⌘<arrow>` as one.)

h/t @wbinnssmith and @captbaritone. I can't remember which of us had this idea originally 🤣

**Comment by captbaritone** [comment]
This is still marked as "under-discussion". I'd be curious to hear what if anything became of the discussion, or if the discussion itself is still pending.

**Comment by misolori** [comment]
While I do think this sounds like a great concept, I'm not sure this is something we'll tackle in the near future. You can partially do this with editor views via `Navigate to the View...` and you can assign this to keyboard shortcuts like:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/35271042/66412992-67b36400-e9ab-11e9-86ee-e4803029c621.png">

And that will allow you to at least jump around the editor views. Given that this isn't something that we'll tackle soon, I'm going to close this as `out-of-scope`. If in the future we'll decide to re-visit this we'll open this back up. Thanks again!
