### ISSUE TITLE
Have vertical scrollbar and overview ruler represent only the text portion of the file (not the extra page at the end)

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode#7362]
- VSCode Version: 1.2.0
- OS Version: OS X el capitan

Steps to Reproduce:
1. scroll to the bottom of an editor, so that the last line is aligned with the bottom of the editor
2. notice that the scroll bar position indicator is not at the bottom of the scroll bar

Expected behavior:
- the scroll bar position is mapped to the full length of the file without the overflow that allows scrolling further.
- the dark scroll position that indicates the beginning and the end of the page shrinks as you scroll beyond the end of the file

**Comment by wmertens** [comment]
Screenshots to clarify:

* Current situation
![image](https://cloud.githubusercontent.com/assets/54934/23493694/032bd790-ff0e-11e6-87aa-2c581e8300c0.png) ![image](https://cloud.githubusercontent.com/assets/54934/23493737/4b026ebc-ff0e-11e6-8a42-00617c009788.png)

* Desired situation
![032bd790-ff0e-11e6-87aa-2c581e8300c0](https://cloud.githubusercontent.com/assets/54934/23493824/00f754da-ff0f-11e6-8230-3775a4fe0b36.png)
![4b026ebc-ff0e-11e6-8a42-00617c009788](https://cloud.githubusercontent.com/assets/54934/23493829/070957a6-ff0f-11e6-82cb-7e0006229472.png)

**Comment by alexandrudima** [comment]
The dark horizontal line shows where the cursor is. The scrollbar slider is artificially enlarged to be at least 20px high I think (to allow for clicking on it). The scrollbar is mapped to the full height of the file (which includes the extra page at the bottom). You can remove this via `editor.scrollBeyondLastLine`.

**Comment by wmertens** [comment]
@alexandrudima I think you are misunderstanding me.

Basically, I would like the scrollbar to be mapped to the full height of the file _without_ the extra page at the bottom.

That way, there is more space available to show markings.

Right now, the last page-equivalent of the scrollbar is basically unused. I really like scrolling beyond the last line, so I'd rather not give that up.

**Comment by wmertens** [comment]
An example of the same behavior is when you do overscroll in e.g. Chrome. The size of the scrollbar handle is constant throughout the page, because it reflects page size compared to the full document, and while you overscroll, it shrinks.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
