### ISSUE TITLE
Terminal is not displaying correctly

### ISSUE THREAD

**Issue by shipcommit** [microsoft/vscode#73636]
The internal terminal has started to display with several lines of space before the prompt. It wasn't like this earlier today, and I haven't made any system changes.

The terminal works, but it looks kind of weird:

![VS Code](https://user-images.githubusercontent.com/35367024/57582456-b082f180-74cd-11e9-9469-20322adb02c3.gif)

- VSCode Version: 1.33.1
- OS Version: Windows 10 Pro 17763.475

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
