### ISSUE TITLE
Frequent freezes when git repo has lots of changes

### ISSUE THREAD

**Issue by a-gn** [microsoft/vscode#73637]
Issue Type: <b>Performance Issue</b>

I added a large dataset in my repo folder without adding it to git. The git sidebar button rightly reports 5000 changes waiting to be added.

The problem is that every few minutes, and when I do something that requires updating that number, VSCode freezes completely for several seconds, like the whole editor is waiting on git to finish processing the repo again.

The freezes happen even when the large folder is added to .gitignore.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 11420	code main
    0	    66	  3180	   window (Issue Reporter)
    0	   596	 15356	   window (dataset.py - anicog - Visual Studio Code)
    0	   221	  9272	     extensionHost
    0	    32	  4308	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=9272
    0	    71	 17128	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=9272
    0	    46	 20400	       C:\Users\arnog\AppData\Local\Programs\Python\Python37\python.exe completion.py
    0	    26	  2204	         C:\Users\arnog\AppData\Local\Programs\Python\Python37\python.exe lib\python\jedi\evaluate\compiled\subprocess\__main__.py lib\python
    0	    11	  1980	           console-window-host (Windows internal process)
    0	    11	 17448	         console-window-host (Windows internal process)
    0	    35	 12404	     searchService
    0	    14	 17732	     watcherService 
    0	    11	  7160	       console-window-host (Windows internal process)
    0	    13	 18772	     electron-crash-reporter
    0	    70	 19780	   shared-process
    0	   289	 22056	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dataset.py - anicog - Visual Studio Code)
|    Folder (anicog): more than 497381 files
|      File types: jpg(497375) json(3) gitignore(1) md(1) py(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.7.3
r|Iku|1.0.9
latex-workshop|Jam|6.5.1
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
vscode-scheme|sjh|0.4.0

</details>

**Comment by joaomoreno** [comment]
When you add the large folder to gitignore and commit that, how many changes are left?

**Comment by a-gn** [comment]
> When you add the large folder to gitignore and commit that, how many changes are left?

No changes are left. Sorry for missing your question.
