### ISSUE TITLE
Have a button to create a new file on the tabs stripe

### ISSUE THREAD

**Issue by kirubiel** [microsoft/vscode#73631]
Hello, is it possible to have a new file tab button like there is on browsers? Except it would be on the File Tabs area instead of the File Explorer.
![SharedScreenshot](https://user-images.githubusercontent.com/39803957/57580013-3d698300-74ad-11e9-9e29-5168119eb875.jpg)

**Comment by sneakyvince** [comment]
Great idea but how would it work once you click the '+' button?

Would the cursor instantly move to the file explorer like this?

![Schermafbeelding 2019-05-12 om 19 28 20](https://user-images.githubusercontent.com/10743051/57585727-4ded1e00-74ec-11e9-9125-5fbf13b0afc6.png)

Or would a similar input field be added inside the actual tab?

The first option might be a little jarring.

**Comment by gndelia** [comment]
Double-clicking on that empty area (Where you are suggesting to have the "+" button) creates a new empty file. You then just need to Ctrl + S to save it

**Comment by kirubiel** [comment]
@sneakyvince Interesting suggestion. I think it would be very beneficial to have an input field added inside the actual tab. It would be weird to move to the file explorer when it's the very thing you are trying to avoid.

@gndelia Cool I just noticed that now. I'm not sure how many people use that but to me it looks obscure. Having the plus sign can show that the option is there if you need it.

**Comment by gndelia** [comment]
It is a bit obscure, I agree. Notepad++ and Sublime have the exact same behaviour (and the same "obscure UX")

I would love to contribute to implementing this 😄

**Comment by kirubiel** [comment]
Awesome!
