### ISSUE TITLE
"Open with Code" context menu option opens two instances if you don't have any workspace created or didn't have one opened in previous session

### ISSUE THREAD

**Issue by atiyar** [microsoft/vscode#73638]
- VSCode Version: 1.33.1
- OS Version: Windows 10 Version 1809

Steps to Reproduce:
1. Fresh install VS Code
2. Right click on a folder or on the background of Windows explorer and select "Open with Code"

Or,
1. Remove any existing workspace from the VS Code explorer (so that the explorer is empty)
2. Close VS Code
3. Right click on a folder or on the background of Windows explorer and select "Open with Code"

Or,
1. Open a folder (not a workspace) in the VS Code explorer
2. Close VS Code
3. Right click on a folder or on the background of Windows explorer and select "Open with Code"

As I tried to test, I found some other scenarios too when this happens. I could not pin-point them all, but every time it is related to not having any workspace created or not having any workspace (not folder) opened in previous session. I hope this helps.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@atiyar can you try if this also happens if you just do "code <folder>" from the command line?

**Comment by atiyar** [comment]
@bpasero sure :)
command: MY\PROJECTS\ARE\HERE>code
result: opens a single instance

command: MY\PROJECTS\ARE\HERE>code my-project-folder
result: opens two instances

command: MY\PROJECTS\ARE\HERE\my-project-folder>code .
result: opens two instances

If you had opened a workspace in your previous session, then the second and third cases open a single instance.

**Comment by bpasero** [comment]
@atiyar any chance you can demo this to me with screenshots or screen recording?

**Comment by atiyar** [comment]
@bpasero could you be a bit more specific about what exactly you want me to do?

**Comment by bpasero** [comment]
@atiyar I am curious to see what the second instance is that open. I assume the first one is the folder, but curious about the second one. A screen shot would help maybe.

**Comment by atiyar** [comment]
The second instance is a VS Code instance in a state you closed it after your previous session, unless you closed it with a workspace opened in it, in which case the second instance doesn't show up. Below are the steps to reproduce the issue along with the screenshots -

Commands used in the tests-

![cmd](https://user-images.githubusercontent.com/20378536/57836250-1f1fc200-77e2-11e9-99c4-a918966b481e.png)

Test#1:
1. This is VS Code empty -

![1  vscode-empty](https://user-images.githubusercontent.com/20378536/57835495-6c9b2f80-77e0-11e9-818d-6e44ceb2e197.png)

2. Close VS Code
3. Enter one of the commands
4. Result -

![result-1](https://user-images.githubusercontent.com/20378536/57835688-e92e0e00-77e0-11e9-88da-c70e6dd34ace.png)

Test#2:
1. Add a folder in VS Code explorer using the "Add Folder" button -

![2  vscode-my-other](https://user-images.githubusercontent.com/20378536/57835840-41fda680-77e1-11e9-97c5-4990c5b056b7.png)

2. Close VS Code
3. Enter one of the commands
4. Result -

![result-2](https://user-images.githubusercontent.com/20378536/57836418-76259700-77e2-11e9-92d9-b29c2c3556b5.png)

Test#3:
1. Add a folder in VS Code explorer using the "Add Folder" button and save it as a workspace -

![3  vscode-workspace](https://user-images.githubusercontent.com/20378536/57836493-a5d49f00-77e2-11e9-812d-acea41b5b7bf.png)

2. Close VS Code
3. Enter one of the commands
4. Result -

![result-3](https://user-images.githubusercontent.com/20378536/57836552-c270d700-77e2-11e9-9457-97ef95f62485.png)

**Comment by atiyar** [comment]
@bpasero found another scenario when you don't have two instances -

1. Open a folder with the "File->Open Folder" menu option (it'll ask you "Do you want to save your workspace configuration as a file?" Click "Don't Save", because we don't want a workspace, we want just a folder) - 

![2](https://user-images.githubusercontent.com/20378536/57850716-716fdb80-7800-11e9-890a-ee5a13b3917d.png)

2. Close VS Code
3. Try the "code" or "code ." command (or use the "Open with Code" context menu option) to open a new folder - 

![cmd](https://user-images.githubusercontent.com/20378536/57850770-995f3f00-7800-11e9-9213-d233dbe507f7.png)

4. Result: a single instance with the intended folder - 

![3](https://user-images.githubusercontent.com/20378536/57850804-af6cff80-7800-11e9-95bd-9d5c7596158e.png)

With the this scenario in mind, I think the following observations might help you narrow down the source of the overall issue -
1. When you open a folder clicking the "Add Folder" button, the folder is opened in the explorer under "UNTITLED (WORKSPACE)"

![X1](https://user-images.githubusercontent.com/20378536/57850901-f955e580-7800-11e9-919d-30f4e6e922e6.png)

2. When you open a folder with the "File->Open Folder" menu option, the folder is opened in the explorer as if it were a workspace (folder name capitalized as workspace name) - 

![X2](https://user-images.githubusercontent.com/20378536/57850964-27d3c080-7801-11e9-8710-2a7fa364437d.png)

3. After opening a folder with the "File->Open Folder" menu option -
   i) add another folder in the explorer ("File->Add Folder to Workspace..." or context menu from right click in the explorer
   ii) now you are in the "UNTITLED (WORKSPACE)" scenario with two folders opened under it - 

![X3](https://user-images.githubusercontent.com/20378536/57851059-6e291f80-7801-11e9-89f1-ad82a1d50e51.png)
    
   iii) close VS Code
   iv) try the "code" or "code ." command (or use the "Open with Code" context menu option) to open a new folder
   v) Result: two instances - 

![X4](https://user-images.githubusercontent.com/20378536/57851112-96188300-7801-11e9-9b4b-c7a576db05bc.png)

Disclaimer: I always use the "Add Folder" button in VS Code explorer to open a folder (because I'm lazy enough not to go through the File menu and also I'm bad with keyboard shortcuts, or because it's a wide, big beautiful button just sitting there waiting to be clicked). I don't know while opening a new folder if the difference between using the "Add Folder" button and the "File->Open Folder" menu option is intentional, but I must say its very much confusing.

**Comment by bpasero** [comment]
@atiyar ok so this is about restoring an extra window with "Untitled Workspace" and so you end up with two windows, right? This is intentional behaviour:
* use VSCode and end up with an untitled window
* close the application
* start it again on a folder
* it should open 2 instances, one for the folder and one for the untitled workspace

The reason we restore untitled workspaces is because you as a user did not yet make a choice of discarding this workspace or not. 

Does that make sense?

**Comment by atiyar** [comment]
@bpasero does it? Wouldn't it make more sense if it asks me if I want to save my Untitled Workspace when I attempt to close VS Code?
If I said "No" to whether I want to save my Untitled Workspace, the next time when I'm trying to -
 - open a folder in VS Code, there's no need to restore my previous work because I already made a choice about it
 - open VS Code only, not any folder with it, its always nice to have my previously opened folder(s) under that Untitled Workspace

Most of the times I open VS Code, I don't need a Workspace saved for my work, and create hundreds of .code-workspace files.

**Comment by bpasero** [comment]
@atiyar we discussed this back when we designed this experience and we felt that asking to save the workspace each time you quit the application would be odd. Imagine you simply want to have multiple folders quickly appear in your window and you quit and start again many times, we would end up asking each time you just quit the application. We felt this would make the experience too heavy weight.

**Comment by atiyar** [comment]
@bpasero OK, I think I'm starting to get the picture. Because most of the time I myself use VS Code the way you described.
So, I'm considering this a "by design".

**Comment by bpasero** [comment]
You can always save a workspace to disk and then you will not see this second instance opening.

**Comment by atiyar** [comment]
@bpasero I'm really sorry, but I think we still have an issue to talk about -

1. Start VS Code without opening any folder or workspace. At this point you don't have anything opened in the explorer

![1  vscode-empty](https://user-images.githubusercontent.com/20378536/57877837-8e290500-783a-11e9-9325-2daec13957fd.png)

2. try the "code" or "code ." command (or use the "Open with Code" context menu option) to open a new folder
3. Result: two instances - one with the intended folder and another is an empty instance

![result-1](https://user-images.githubusercontent.com/20378536/57877890-a9941000-783a-11e9-80fe-97d35d459217.png)

In this case there was no previously left Untitled Workspace to restore. Please take a look at the screenshots.

**Comment by bpasero** [comment]
@atiyar this is configurable, can you check the `window.openFoldersInNewWindow` setting?

**Comment by atiyar** [comment]
@bpasero the setting "window.openFoldersInNewWindow": "off" seems to work if you already have VS Code open. 

If you don't have VS Code already open and try the "code" or "code ." command (or use the "Open with Code" context menu option) to open a new folder, the result is two instances as the above screenshot shows.

**Comment by bpasero** [comment]
@atiyar yeah you are doing this right: 

![image](https://user-images.githubusercontent.com/900690/57882773-59389600-77d9-11e9-8368-1272071c3124.png)

That will indeed turn your workspace into an untitled workspace, which is possibly up for debate. The better way to get into an empty state is to  pick File > Close Folder, and then you are all set.

**Comment by atiyar** [comment]
@bpasero I really didn't expect to consider the empty explorer an Untitled Workspace. But, I get it now. Thanks a lot for your time.  :-)
