### ISSUE TITLE
Open in terminal option not visible on load

### ISSUE THREAD

**Issue by emceearjun** [microsoft/vscode#73633]
Issue Type: <b>Bug</b>

"Open in terminal" option is not visible in the context menu when a new VS Code window is loaded. The option is again visible when a new file/folder is created.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.90GB (0.53GB free)|
|Process Argv|C:\ws\nest-apps|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.0.1
flutter|Dar|3.0.1
prettier-vscode|esb|1.9.0
dart-syntax-highlighting-only|osc|1.0.0
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
Can you be more specific on how you bring up the context menu where it's missing? A screenshot might help

**Comment by emceearjun** [comment]
When vscode is opened:
![IMG_20190514_115846](https://user-images.githubusercontent.com/9413392/57675641-25763880-7640-11e9-9e26-bccac4ae1eeb.jpg)

After creating a file:
![IMG_20190514_115920](https://user-images.githubusercontent.com/9413392/57675642-25763880-7640-11e9-9295-5bc2bc38d8a8.jpg)

**Comment by isidorn** [comment]
Thanks for reporting this. I have pushed a fix and the vscode insiders from Monday will have the fix. You can try it out and let us know if the fix solves the issue for you. Thank you

**Comment by emceearjun** [comment]
Thanks @isidorn I'll check it out and revert.
