### ISSUE TITLE
A snippet definition should not require a "prefix" property to be considered valid

### ISSUE THREAD

**Issue by frou** [microsoft/vscode#73635]
Snippets are typically for things we use often, but they are also useful for things we use less often, but all the same want to automate.

In those cases, it's not worth having to come up with a `prefix` (a.k.a `tabTrigger` in TextMate/Sublime parlance) for autocompletions purposes, because we can just use VSC's `Insert Snippet` command to find and insert those snippets.

Unfortunately, when defining snippets in a `.code-snippets` file, if we omit a `"prefix": "foo"` key/value, that snippet is considered invalid (gets a squiggly underline) and hence is not offered in the list shown by the `Insert Snippet` command.

Please make the `prefix` property optional.

REF: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by jrieken** [comment]
The easy workaround is to use a fake/dummy prefix

**Comment by GinnyPotter** [comment]
I will take a stab.
