### ISSUE TITLE
Spaces in javascript loop leads to bad syntax highlighting

### ISSUE THREAD

**Issue by battmatt** [Microsoft/vscode#7363]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

See Image
![screen shot 2016-06-07 at 2 49 12 pm](https://cloud.githubusercontent.com/assets/1753879/15875942/5e7df83e-2cbf-11e6-9d13-b3e762cce1c9.png)

**Comment by battmatt** [comment]
After removing spaces:

![screen shot 2016-06-07 at 2 52 20 pm](https://cloud.githubusercontent.com/assets/1753879/15875956/7867025e-2cbf-11e6-9a8d-9088dd688530.png)

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#180
