### ISSUE TITLE
Show branch name near commit message box

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#73644]
Issue Type: <b>Feature Request</b>

It would be sweat to show the current branch name **near** the commit message box.
Many times I committed the changes to the wrong branch (I know we can see it in the status bar. I just forgot to take a look)

![where](https://user-images.githubusercontent.com/7588612/57587001-0a97ad00-74f6-11e9-93a5-d199c90fb918.png)

---

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18895

**Comment by joaomoreno** [comment]
How about we just add `... to commit to master` in the placeholder, instead?

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L579

Care to submit PR?

**Comment by yzhang-gh** [comment]
Glad to do that.

One concern is it seems not to be enough space for the branch name in a normal width input box.
It is the max width that prevents the extension logo from showing up in the extension list.

Would you mind omitting "press"?

**Comment by joaomoreno** [comment]
Yeah let's remove `press`.

**Comment by importnetminecraft** [comment]
How does the current implementation for this work?
I couldn't find any documentation of localize used this way.

**Comment by joaomoreno** [comment]
Here is it: https://github.com/Microsoft/vscode/blob/91885dd9e3e392d476071f759e391748e250df0f/extensions/git/src/repository.ts#L579

**Comment by burknator** [comment]
I think the solution of @importnetminecraft breaks localization of the placeholder. I added comments to his PR and created a new one.
