### ISSUE TITLE
vscode in mac Mojave 10.14 doesn't understand it's a git repo if i open a subfolder

### ISSUE THREAD

**Issue by happyrahman** [microsoft/vscode#73646]
Issue Type: <b>Bug</b>

I have a repo that has some project inside. if i open the subfolder with vscode directly, the vscode fail to understand it's a git repo. if i open to root folder of the repo the vscode works correctly. it's a bug because in windows if i open a subfolder the vscode automatically understand that this is a git repo. 

but in mac, the only way to workaround it is to open the root folder

i checked the other issues and they belong to 2017 or early 2018. is it still a bug? 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?
