### ISSUE TITLE
VS Code can not access `marketplace.visualstudio.com`

### ISSUE THREAD

**Issue by webwurst** [microsoft/vscode#73641]
I saw this error reported multiple times, but could not find a solution working for me. I don't use a proxy or vpn, there are no hostnames overridden in /etc/hosts, I am directly connected to the internet.

This problem persists for me since several weeks while no other applications show similar connection problems.

- VSCode Version:
```
$ code-insiders --version
1.34.20-insider
57b550c559b945eb9d871dbf2b2e4cb9e31e2551
x64
```

- OS Version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

Steps to Reproduce:
```
$ sudo snap install --classic code-insiders

$ code-insiders --install-extension ms-python.python
Installing extensions...
getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443
Failed Installing Extensions: ms-python.python
```

Locally the address can be resolved:
```
$ ig marketplace.visualstudio.com +short
13.107.6.175
```

The marketplace is working fine including the search functionallity in my browsers and on the commandline:
```
$ curl -sfSL -o /dev/null -w '%{http_code}' 'https://marketplace.visualstudio.com'
200

$ curl -sfSL -o /dev/null -w '%{http_code}' 'marketplace.visualstudio.com/search?term=test&target=VSCode&category=All%20categories&sortBy=Relevance'
200
``` 

This error shows up with `code-insiders` and `code`. I also removed the apps and re-installed with the issue persisting:
```
snap remove code
rm -r ~/.vscode/
rm -r ~/.config/Code/
snap install --classic code
```

Current workaround: Installing downloaded `vsix` files from the markatplace within VSCode works.

**Comment by webwurst** [comment]
Another finding: When I add the failing hostnames explicitly to `/etc/hosts` it works.
```
echo "13.107.6.175 marketplace.visualstudio.com ms-python.gallery.vsassets.io ms-kubernetes-tools.gallery.vsassets.io" >> /etc/hosts

code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
```

**Comment by chrmarti** [comment]
Does it work from within the VS Code UI?

**Comment by webwurst** [comment]
No, does not work out of the box. After adding the hostname to `/etc/hosts` then it also works within the VS Code UI.

**Comment by chrmarti** [comment]
- Can you point Chrome or Chromium at marketplace.visualstudio.com and see if that works?
- What do you get for `node -e 'require("dns").resolve("marketplace.visualstudio.com", console.log)'`?

**Comment by webwurst** [comment]
Accessing `marketplace.visualstudio.com` via Chromium works.

I don't have `node` installed locally, output by running `node` in a Docker container:
```
$ docker run -ti node:11-slim node -e 'require("dns").resolve("marketplace.visualstudio.com", console.log)'
null [ '13.107.6.175' ]
```

**Comment by sandy081** [comment]
@joaomoreno Can you help me in understanding why we have connectivity issues whereas user could do it from curl?

**Comment by joaomoreno** [comment]
Does this repro without snap?
