### ISSUE TITLE
Search histrory

### ISSUE THREAD

**Issue by voquanghoa** [microsoft/vscode#73642]
Hi everyone, 

On the search dialog

<img width="602" alt="search-dialog" src="https://user-images.githubusercontent.com/10450325/57585809-66bef900-7517-11e9-9b7a-a5624ffcdc2a.png">

Some times, I want to reuse the search patterns I've used before. So, it's nice to have the search history feature similars to the existing one on Notepad++

![Search-history](https://user-images.githubusercontent.com/10450325/57585890-3f1c6080-7518-11e9-8bc8-d3ef433e8e91.png)

Is it possible to implement?

Thank you ❤️❤️❤️❤️

**Comment by roblourens** [comment]
You can actually navigate find history by using the up/down arrow keys.
