### ISSUE TITLE
Upper-case aware completion when opening folder with remote ssh

### ISSUE THREAD

**Issue by Noezor** [microsoft/vscode#73658]
Hi,

When opening folders or files while using remote access through ssh with VS Code insiders (thanks, it is working fantastic and as expected),  text completion seems oblivious to upper-case when suggesting files. Let me show you with an example.

Let's say you want to open ./Axyz but . also contains folders abc.
What happens usually is that one would press "A" and then tab, expecting it to get completed as Axyz. Instead, VS Code Insiders puts the prompt over the first choice in alphabetical order, abc. Thus, doing "A"+TAB complets as /abc/.

It is counter-intuitive with every other text completion that I know, including Intellisense, could you please change that or add an option ?

It is clearly more a nice-to-have than a must have, as it saves max 2 key press by completion, but we are all lazy.

**Comment by chrmarti** [comment]
Is this in the terminal? (Trying to find the UI you describe.)

**Comment by Noezor** [comment]
Sorry, you need to establish SSH connection to a server and then Ctrl+O for example. This does not provide a regular window UI but one which explores a path, at least on my computers. 

Went back from work, will post screenshots tomorrow if needed.

**Comment by Noezor** [comment]
![example-UI](https://user-images.githubusercontent.com/8218350/57677140-75e09c80-7626-11e9-93c9-9dd9341fbf91.png)

Here's the UI I'm talking about.
