### ISSUE TITLE
Can's select portable VSCode as default program for opening files on Windows 7

### ISSUE THREAD

**Issue by Servail** [microsoft/vscode#73650]
- VSCode Version: 1.33.1
- OS Version: Windows 7 x64 build 6.1.7601

Steps to Reproduce:

1. Rightclick some file -> Open with... -> Choose program...
2. Browse... to VSCode.exe

It doesn't appear in the list as expected!
Every other program does (at least VSCode is the first program with this unexpected behaviour).

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur in insiders build?: Yes

**Comment by joaomoreno** [comment]
Portable shouldn't appear on that list, by definition, since it's not registered in any system application list. Do other portable programs work?

**Comment by Servail** [comment]
> 
> 
> Portable shouldn't appear on that list, by definition, since it's not registered in any system application list. Do other portable programs work?

Yes. If I select any other application.exe like that, it registers itself in that list. But VSCode not.

**Comment by Servail** [comment]
Nevermind, found a fix! Issue was a wrong path in registry at "\HKEY_CLASSES_ROOT\Applications\Code.exe\shell\open\command\". It was pointing to Program Files directory, where I've set up VSCode once ago. Still can't understand why it don't reregister itself with the right path (since "wrong" path .exe is gone). Can it be a VSCode bug?

**Comment by joaomoreno** [comment]
Not really sure. :thinking: Glad to know you're unblocked.
