### ISSUE TITLE
Quick suggestions aren't triggered inside words

### ISSUE THREAD

**Issue by PuffLady** [microsoft/vscode#73657]
Hello？
Is there any progress in this discussion? https://github.com/microsoft/vscode/issues/30811
I have encountered the same problem. What should I do when developing the xml auto-complete plugin? I want the character that is entered after " can also trigger the provideCompletionItems method

eg. 
\<Contaner style="w"\> // when I type here, I want to provide completion item

PLEASE HELP ME~

**Comment by chrmarti** [comment]
Looks like we decided to keep the existing behavior in #30811.
