### ISSUE TITLE
cmd+T activates python linting

### ISSUE THREAD

**Issue by louisabraham** [microsoft/vscode#73659]
Hi,

I have a strange bug:

- open a Python file in vscode with the Python extension activated
- try cmd+T (I'm on macOS, maybe you can reproduce on windows) for "Go to Symbol in Workspace"
- the python pane begins to lint your code

It is strange because when I search in the  Keyboard Shortcuts, the only command bound to "cmd+T" is workbench.action.showAllSymbols.

**Comment by alexandrudima** [comment]
@louisabraham Can you please show a screenshot of the keyboard shortcuts UI when you search for "cmd+t"?

Here it is on my machine:
![image](https://user-images.githubusercontent.com/5047891/61626372-75dfc700-ac7d-11e9-9a59-548025223646.png)

**Comment by louisabraham** [comment]
![image](https://user-images.githubusercontent.com/13174805/62865213-276a9900-bd0e-11e9-89e7-31b284c87383.png)
As I said previously, no other command uses this shortcut.

I just tried and it worked flawlessly in the repo I was working on. I'll reopen if I can reproduce again.
