### ISSUE TITLE
VSCode auto-updating even with the "do not update automatically" option disabled.

### ISSUE THREAD

**Issue by guiherzog** [microsoft/vscode#73652]
Issue Type: <b>Bug</b>

Version 1.33.1 is buggy and the code helper runs at 99% of the CPU all the time. I downgraded to the previous version and it was working fine now. I disabled the auto-update on Preferences, however, it did not respect that and it has updated itself two times already. 

I had to downgrade it three times. VSCode is a nice software, but these two critical bugs are a dent on its reputation. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 48, 35|
|Memory (System)|16.00GB (3.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
line-counter|dol|0.5.2
prettier-vscode|esb|1.9.0
vscode-styled-components|jpo|0.0.26
graphql-for-vscode|kum|1.13.1
prettify-json|moh|0.0.3
vscode-typescript-tslint-plugin|ms-|1.0.0
team|ms-|1.149.2
color-highlight|nau|2.3.0
java|red|0.44.0
vscodeintellicode|Vis|1.1.6
vscode-todo-highlight|way|1.0.4

</details>

**Comment by chrmarti** [comment]
You might disabled auto update only for extensions. Make sure disable it for VS Code itself:
![image](https://user-images.githubusercontent.com/9205389/57643480-ad8c0d80-756e-11e9-9108-3a576e0f1e6f.png)

**Comment by chrmarti** [comment]
Any idea what could trigger the helper consuming that much CPU? What work are you doing that time? Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide more information.

**Comment by jrieken** [comment]
The performance is 💩 because of a TypeScript issue, assigning @joaomoreno for the downgrade problem

**Comment by guiherzog** [comment]
@chrmarti thank you for you reply. Unfortunately, that was not the issue. I really double checked if I was disabling the auto-updates for extensions or for VSCode. I am not sure how this is happening.

And the CPU consumption is indeed caused by the TypeScript issue. Downgrading the version solves the issue as well as other solutions proposed on other issues here on GitHub.

Thanks to you all anyway!
