### ISSUE TITLE
Pass cwd into extension provided tasks

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [microsoft/vscode#73651]
Issue Type: <b>Bug</b>

Created a task that used `"option: { "cwd": "${workspaceFolder}/examples" }"` to run the `npm start` at the child repo, then typed `Ctrl+Shift+B` to launch it.

It seems that `VSCode` attemped to check if the task configuration exist in the `package.json`, but it ignored the `cwd` option.

For example, I have a task like this:
``` json
        {
            "type": "npm",
            "script": "start",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceFolder}/examples"
            }
        }
```
Then, if both the `${workspaceFolder}/package.json` and the `${workspaceFolder}/examples/package.json` has the `npm start` script, everything works well. But if I removed the `npm start` script from the `${workspaceFolder}/package.json`, it would failed to launch the task, just output like `error: npm task check not support the configured task`.
![image](https://user-images.githubusercontent.com/12682063/57601992-90683680-7590-11e9-8279-059824faedf4.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (4.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-translate|chu|0.1.5
dart-code|Dar|3.0.1
flutter|Dar|3.0.1
vscode-eslint|dba|1.8.2
vscode-elixir|mjm|1.1.0
vscode-language-pack-zh-hans|MS-|1.33.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.0
csharp|ms-|1.19.1
Go|ms-|0.10.2
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
background|sha|1.1.19
vscode-hexdump|sle|1.7.2
unity-debug|Uni|2.7.2
intelligence-change-case|zhe|1.1.0
vscode-proto3|zxh|0.2.2

</details>

**Comment by alexr00** [comment]
Currently, none of the of the attributes you set on a task are passed into the extension provided npm task. All attributes set in tasks.json on an extension provided task are added on top of the task after the task as been created by the extension. Because of this, the npm start task that the npm extension provides doesn't know that you've set the cwd. The feature request here is to pass cwd into the extension provided task.

You can do this now if you make a task of `"type": "script"` and run npm start from there.

**Comment by zhengxiaoyao0716** [comment]
Thanks, but if  `the npm start task that the npm extension provides doesn't know that you've set the cwd`, why it works correctly after we add any same name script into the `${workspaceFolder}/package.json`? The problem just happend in checking stage, and if the check passed, then everything works well (the script witch launched in fact is in the child `examples` project), which indicate that it's not an problem of `extension ...doesn't know ...the cwd`.

**Comment by alexr00** [comment]
You can see how the tasks are created by the extension here: https://github.com/Microsoft/vscode/blob/release/1.34/extensions/npm/src/tasks.ts
Specifically, we only look in the workspace folders: https://github.com/Microsoft/vscode/blob/release/1.34/extensions/npm/src/tasks.ts#L119

**Comment by zhengxiaoyao0716** [comment]
As the task in fact could launched correctly, the checking should be passed too. Now it can't, so I wonder that maybe it is really unreasonable. If the checking prevented the correctly task executing, I prefer to close the checking.

**Comment by alexr00** [comment]
I think if you correctly provide the `"path"` in your task then it should work. The path should be the relative path do the package.json with the script, and should not include the basename of package.json
