### ISSUE TITLE
Auto update off by default

### ISSUE THREAD

**Issue by Anisubhra** [microsoft/vscode#73655]
Issue Type: <b>Feature Request</b>

VSCode has auto update enabled by default and I have limited data usage limit . Due to the problem I have lost my data for today without even knowing and later on I realised that it auto updated, that's really annoying and quite a downside for me. Previously I've been using "Sublime Text" and it was really good then I decided to give VSCode a shot after the incident I think I'll have to switch back to my old editor. Such a waste of my time as well as my data usages

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18343

**Comment by chrmarti** [comment]
Sorry to hear that. You can show all relevant settings to internet connectivity with the `@tag:usesOnlineServices` filter (also available in the `...` menu):
![image](https://user-images.githubusercontent.com/9205389/57645796-ed092880-7573-11e9-87c0-d078c666731d.png)

Note that extensions can have their own features using data that are not shown here.

Closing as we are unlikely to change the default.
