### ISSUE TITLE
DocumentLink has no way to provide the target column

### ISSUE THREAD

**Issue by dmartingit** [microsoft/vscode#73653]
So far, `DocumentLink` has an optional `target` property that is a `uri`. The `uri` has the ability to specify a line in its fragment, and when you click on it, a `TextEditor` is created, which already places the cursor on the correct line.
However, in some cases it is necessary to specify a column or even a range.

**Comment by jrieken** [comment]
Sure, works like this `file:///some/file.js#73,84`

**Comment by dmartingit** [comment]
> Sure, works like this `file:///some/file.js#73,84`

Thank you for pointing this out!
Is there also a special syntax for creating the `TextEditor` in another view column?
If not, it might be better for a `DocumentLink` to have a callback where the user can specify special behavior.

**Comment by jrieken** [comment]
That doesn't exist - valid feature request tho
