### ISSUE TITLE
Checking for updates and installing extensions doesn't work behind corporate proxy

### ISSUE THREAD

**Issue by marcoliceti** [microsoft/vscode#73661]
- VSCode Version: 1.33.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open VSCode.
2. Try to check for updates.

Does this issue occur when all extensions are disabled? Yes

The error is `net::ERR_NAME_NOT_RESOLVED`.

This is basically the same as [this issue](https://github.com/Microsoft/vscode/issues/32210).

Proxy-related environment variables are set, but VSCode seems to be ignoring them. Relevant settings such as `http.proxy` seem to be ignored too. The only way to make it work is to start VSCode from a terminal with the `--proxy-server` option.

Notes:

* other software (e.g. Firefox) works fine
* Except Chrome, which required the `--proxy-server` option too
* I tried to put the `--proxy-server` option in the .desktop launcher: works for Chrome, doesn't work for VSCode (very strange)

**Comment by chrmarti** [comment]
Have you tried searching for 'Proxy' in Ubuntu's settings and configured the proxy there? That should work for VS Code and Chrome (since both are Chromium based).

**Comment by marcoliceti** [comment]
> Have you tried searching for 'Proxy' in Ubuntu's settings and configured the proxy there?

No, because by default network settings in Ubuntu are managed by NetworkManager, which I had to replace with systemd-network. And since the GUI in Settings > Proxy assumes that you're using NetworkManager, it's not useful in my case.

**Comment by chrmarti** [comment]
@marcoliceti Have you tried using Settings > Proxy? I'm not sure where Chromium reads the proxy settings, but might get it from there even if you replaced NetworkManager.

**Comment by marcoliceti** [comment]
Yes I tried but that window just shows a message that tells me that NetworkManager should be running.

Anyways, this morning VSCodes updates magically started to work :)

It works even when I remove the `--proxy-server` option from the .desktop launcher and the `http.proxy` from VSCode settings.

I don't what happened, but the problem is now solved.

Thank you!

**Comment by marcoliceti** [comment]
I'm sorry but it stopped working :(

Right now, this is ok:

```
$ code --proxy-server="http://127.0.0.1:3128"
```

And this is not:

```
$ code
```

This are my settings:

```
{
    "workbench.colorTheme": "Github"
}
```

This is the (relevant part of) my environment:

```
$ env
http_proxy=http://127.0.0.1:3128
https_proxy=http://127.0.0.1:3128
```

**Comment by chrmarti** [comment]
This is a limitation of Chromium.

**Comment by marcoliceti** [comment]
Ok, thanks. At least there's the `--proxy-server` workaround.

**Comment by marcelocg** [comment]
I'm using VSCode 1.35.1 installed on an Ubuntu 19.04 virtual machine running in VirtualBox. Host is Windows 10, behind NTLM corporate proxy.

Situation is the same as with @marcoliceti. I can only search/install extensions when starting VS Code with `--proxy-server`.
