### ISSUE TITLE
Run to cursor to a previously executed line results in a leaked breakpoint

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#7366]
- VSCode Version: 1.2.0
- OS Version: OS X

I understand this is a result of the implementation of RunToCursorAction, which basically creates a breakpoint at the specified location, continues the execution, and remove the breakpoint once it has been hit.

Steps to Reproduce:

1. Set a breakpoint and start debugging.
2. Select Run to cursor in the context menu for a line that won't be executed
3. Stop the program

Result: there is a leaked breakpoint where run to cursor was called.

![runtocursorbug](https://cloud.githubusercontent.com/assets/637952/15877533/45f1b3f0-2cc9-11e6-85bb-3a82a03b1030.gif)

@isidorn @weinand

**Comment by edumunoz** [comment]
I opened PR https://github.com/Microsoft/vscode/pull/7367.

The best experience would also hide these breakpoints from the UI.

**Comment by weinand** [comment]
@isidorn we should clear all temporary breakpoints after the program has stopped again (step 3 from above)

**Comment by weinand** [comment]
while verifying this I found https://github.com/Microsoft/vscode/issues/8731
