### ISSUE TITLE
Folder not opening on click sidebar in angular project

### ISSUE THREAD

**Issue by emilalsgndr** [microsoft/vscode#73668]
Folder(name="SHARED") not opening on mouse click on sidebar(file explorer), i restart vs code and os. Problem not fixed. with command p vs code find files but not show current open file location on sidebar. 

VSCode Version:version 1.33
OS Version: macOS Mojave 10.14.2

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by emilalsgndr** [comment]
<img width="353" alt="Screen Shot 2019-05-13 at 10 28 35 PM" src="https://user-images.githubusercontent.com/36768068/57645166-bf050200-75ce-11e9-98e5-5e30020046e4.png">

after 2-3 hours later works, but some times not opening again. also some times cursor not showing in vs code full screen mode. After change window with three finger swipe(mac) showing again. Thanks for time.

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by emilalsgndr** [comment]
![Screen Shot 2019-05-14 at 10 16 46 AM](https://user-images.githubusercontent.com/36768068/57674881-7c284600-7631-11e9-972f-f040e9dbea9d.png)
this problem happens again and i take a screenshot
