### ISSUE TITLE
CPU spikes 200%+ when opening large Ember.js project

### ISSUE THREAD

**Issue by danielkroon** [microsoft/vscode#73669]
Issue Type: <b>Performance Issue</b>

CPU spikes 200%+ when opening large Ember.js project. 
I don't have the issue with when opening other projects. For example, the whole back end (Python) of this project runs smoothly.

Steps to reproduce:
1) $ cd into reef (frontend project folder)
2) $ code .

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 8, 6|
|Memory (System)|8.00GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	    90	  8284	code main
    0	    57	  8287	   gpu-process
    0	   172	  8290	   window (Welcome — reef)
  279	  1319	  8586	     watcherService
    0	    74	  8587	     extensionHost
    0	    82	  8588	   shared-process
    0	    74	  8615	   window (Issue Reporter)
    0	     0	  8748	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome — reef)
|    Folder (reef): more than 242004 files
|      File types: js(227403) json(2226) md(1990) scss(1180) html(1099)
|                  png(1016) svg(800) hbs(670) txt(655) map(586)
|      Conf files: package.json(1258) grunt.js(72) gulp.js(37)
|                  webpack.config.js(36) tslint.json(24) settings.json(1);
```

</details>
Extensions: none

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by danielkroon** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

@mjbvz unfortunately I can reproduce this in the latest vs code insiders build. Here is my output:

VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:35:18.558Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 11, 9|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv|-psn_0_721072|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   48	   106	  5750	code-insiders main
    7	    49	  5800	   gpu-process
    0	    74	  6131	   shared-process
    0	   115	  6747	   window (Welcome — reef)
    0	    49	  6751	     extensionHost
  126	  1008	  6752	     watcherService
    4	    74	  6899	   window (Issue Reporter)
    0	     0	  6927	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome — reef)
|    Folder (reef): more than 241985 files
|      File types: js(227399) json(2225) md(1990) scss(1180) html(1099)
|                  png(1016) svg(799) hbs(670) txt(655) map(586)
|      Conf files: package.json(1258) grunt.js(72) gulp.js(37)
|                  webpack.config.js(36) tslint.json(24);
```

</details>
Extensions: none

**Comment by danielkroon** [comment]
I fixed the issue by setting adding  "files.useExperimentalFileWatcher": true to my settings.json file. I still think this is an issue. I shouldn't have to use the useExperimentalFileWatcher setting in order to use VS code.

**Comment by bpasero** [comment]
@danielkroon the alternative is to add the folder with lots of files to the `files.watcherExclude` setting, can you try?
