### ISSUE TITLE
Different font for different content

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#73664]
I thought that would be nice if comments' font was different from codes,like `fira code` for comments and `monaco` for codes
Not different colors or different styles,I know these settings.

**Comment by chrmarti** [comment]
@joaomoreno Don't you use a theme doing that?

**Comment by joaomoreno** [comment]
@chrmarti I use https://github.com/kencrocken/FiraCodeiScript which changes italic text to another font. Not really the same.

Forwarding this to editor.

**Comment by alexandrudima** [comment]
Duplicate of #30925
