### ISSUE TITLE
Internal terminal can not handle unicode on Linux

### ISSUE THREAD

**Issue by bszabo-hortonworks** [microsoft/vscode#73662]
VSCode internal terminal can not handle unicode characters on Linux

- VSCode Version: 1.33.1
- OS Version: Linux Mint 19 x64 (Hungarian UI and Keyboard set)

Steps to Reproduce:
1. Issue a not existing command (i.e. qwert) in the internal terminal with not English UI setting
or
2. Input any not ASCII key into the terminal (on Hungarian keyboard i.e. "é" key)
or
3. Paste a unicode containing text from the clipboard (i.e. 我是)

In case (1) the result of the system terminal:
`mymint@mymint:~$ qwert`
`qwert: a parancs nem található`
In the internal terminal:
`mymint@mymint:~ qwert`
`qwert: a parancs nem tal\xe1lhat\xf3`

In case (2) on pressing the key (it is a simple key without any modifiers) the system terminal handles it correcty, the internal terminal based on the key either does not insert anything or interprets it incorrectly and shows (i.e. on "í" key): (arg: -1) waiting for input.

In case (3) pasting works perfectly to the system terminal, but does not insert anything to the internal terminal.

The used shell seems the same in both cases:
From system terminal:
`mymint@mymint:~$ echo "$SHELL"`
`/bin/bash`
`mymint@mymint:~$ echo "${BASH_VERSION}"`
`4.4.19(1)-release`
From internal terminal:
`mymint@mymint:~$ echo "$SHELL"`
`/bin/bash`
`mymint@mymint:~$ echo "${BASH_VERSION}"`
`4.4.19(1)-release`

On the other hand, if I start a python debug with a python script like:
`print(input())`
during the debug I can enter unicode characters, but when the program finishes and returns to the shell it does not work again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What's the result of `echo $LANG`?

**Comment by bszabo-hortonworks** [comment]
System terminal:
`mymint@mymint:~$ echo $LANG`
`hu_HU.UTF-8`
VSCode internal terminal:
`mymint@mymint:~$ echo $LANG`
`hu.UTF-8`
