### ISSUE TITLE
Git:Failed to execute git

### ISSUE THREAD

**Issue by stevenruizhang** [microsoft/vscode#73671]
- VSCode Version: 1.33.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. open local git project
2. see error below
![image](https://user-images.githubusercontent.com/13114985/57629976-59654580-75cf-11e9-881f-67bb5519566a.png)

![image](https://user-images.githubusercontent.com/13114985/57629994-62eead80-75cf-11e9-8535-d0dc9dd925d2.png)

Git OUTPUT results

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.14.1.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Project\CAPP\Git
> git status -z -u
> git show :Lambda/sample.js
> git symbolic-ref --short HEAD
> git check-ignore -z --stdin
> git rev-parse HEAD
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse DEV
> git rev-parse --symbolic-full-name DEV@{u}
> git rev-list --left-right DEV...refs/remotes/origin/DEV
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```

Does this issue occur when all extensions are disabled?Yes

**Comment by joaomoreno** [comment]
Does the error appear out of nothing, or only when you run a specific action?
