### ISSUE TITLE
Editor Keeps Asking for Credentials when Sync Git

### ISSUE THREAD

**Issue by DanJ210** [microsoft/vscode#73679]
Issue Type: <b>Bug</b>

I have no idea what's going on. I've disabled all extensions. This happens only with one project. All other projects seem to be normal. All projects are on the same VSTS cloud repository. All are .Net Core 2.2.

Every time I open this project or sync with git I'm asked for crendentials. I get the white Visual Studio window that opens up, type in creds, and then the command pallete in VS Code opens up asking for username and password as well, type in again, and I get value can't be null below. Login failed. If I have extensions on, all of them work like GitLens and Azure extensions using the same credentials. 

I've deleted my .git folder, I've created a brand new project on VSTS to push to. Still the same thing keeps happening with all extensions disabled. So I don't know what feature in VS Code is doing this here.

Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.18.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Users\daniel.jackson\Source\Bid2Buy
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git show :Bid2Buy.sln
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git show :Bid2Buy.sln
Logon failed, use ctrl+c to cancel basic credential prompt.
Missing or invalid credentials.
Skip fetch commands
Missing or invalid credentials.
Skip fetch commands
fatal: ArgumentNullException encountered.
   Value cannot be null.
Parameter name: credentials
fatal: Authentication failed for 'https://dev.azure.com/chsfl/Bid2Buy/_git/Bid2Buy/'

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
> All other projects seem to be normal. All projects are on the same VSTS cloud repository. All are .Net Core 2.2.

Maybe that repo uses HTTP git url, while the others use SSH? Can you check?
