### ISSUE TITLE
error while typing a code

### ISSUE THREAD

**Issue by Syeda-Humaira** [microsoft/vscode#73675]
Issue Type: <b>Bug</b>

whenever i am trying to write a code the cursor is changing its position to the bottom of the page

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.42GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
vscode-JS-CSS-HTML-formatter|lon|0.2.3

</details>

**Comment by chrmarti** [comment]
Does this occur with extensions disabled? (`F1` > `Developer: Reload Window With Extensions Disalbed`)

**Comment by Syeda-Humaira** [comment]
Thanku so much... :)  its started working properly after extensions disabled (Y)

**Comment by chrmarti** [comment]
Please try disabling the installed extensions one-by-one to find the one cause the issue and open an issue for that extension. Thanks!
