### ISSUE TITLE
(Debug)Extension Development, Start Without Debugging

### ISSUE THREAD

**Issue by peni4142** [microsoft/vscode#73672]
- VSCode Version:
- OS Version:
![image](https://user-images.githubusercontent.com/33463108/57634706-22c70500-75a6-11e9-994f-1e1a601ce75d.png)

Steps to Reproduce:

1. Don't have a launch.json
2. Debugging a debug-extension.

Press Strg + F5 (German shortcut)/Start Without Debugging
`noDebug` of `LunchRequestArguments` is not set, when `launchRequest` of the extension is called

```
 interface LaunchRequestArguments {
        /** If noDebug is true the launch request should launch the program without enabling debugging. */
        noDebug?: boolean; // is undefined
        /** Optional data from the previous, restarted session.
            The data is sent as the 'restart' attribute of the 'terminated' event.
            The client should leave the data intact.
        */
        __restart?: any;
    }

```
![image](https://user-images.githubusercontent.com/33463108/57634209-2443fd80-75a5-11e9-94fe-98744e176447.png)

If you have a launch.json, `noDebug` is set.
![image](https://user-images.githubusercontent.com/33463108/57634390-80a71d00-75a5-11e9-9b7b-2c035e51207f.png)

`launchRequest` is a Method of `LoggingDebugSession`.
CALLSTACK:
![image](https://user-images.githubusercontent.com/33463108/57634574-e398b400-75a5-11e9-94a9-c0fd171ec917.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by peni4142** [comment]
Do you need more information?

**Comment by isidorn** [comment]
How exactly do you debug an extension development scenario without a `launch.json`? I do not think we even support this. Can you share how you do this exactly?

If I just "Start without debugging" for a regular javascript file the `noDebug` is properly passed.

**Comment by peni4142** [comment]
I debug my debugging extension. I don't have one launch.json for my extension debug process but I have one for debugging my extension.

Or in other words: The test-workspace, where the debugging of my extension is running on, has no launch.json.

extensioDevelopment
|-.vscode
|   |-launch.json
|-src
|-TestWorkspace
|   |-.vsocde
|       |-No-launch.json
|-package.json

**Comment by weinand** [comment]
@peni4142 the your steps are misleading:
Your workspace where you are debugging the extension has a launch.json, but the workspace where you are testing the running extension has no launch.json, correct?

**Comment by peni4142** [comment]
correct

**Comment by isidorn** [comment]
I can not reproduce this.
What are you doing differently than me

1. I have a freshly generated vscode extension repository
2. F1 > start without debugging
3. `noDebug` is passed in the launch request. I verified that breakpoints do not get hit

![extensionDebug](https://user-images.githubusercontent.com/1926584/58466159-69396980-8139-11e9-9ed7-5a20bcd89852.gif)

**Comment by peni4142** [comment]
Sry I was sick.

Ans sry was my bad in that function:
`resolveDebugConfiguration(folder: WorkspaceFolder | undefined, config: IExtendedDebugConfiguration, token?: CancellationToken): ProviderResult<DebugConfiguration> `

:-/
