### ISSUE TITLE
Fix tasks under ConPTY

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#73677]
Follow up from https://github.com/microsoft/vscode/issues/73351

We need to:

- Flush line data when cursor is moved
- Remove the tasks setting that was added as a workaround

**Comment by alexr00** [comment]
To verify:
1. Open any of the extension samples and npm install.
2. Run the npm watch task. You should see the word "Building..." show up in the status bar.
3. Verify that the word "Building..." goes away after a minute or two.

**Comment by Tyriar** [comment]
Note that you need to be on Windows build 18309+ and have this setting `"terminal.integrated.windowsEnableConpty": true` (true is the default)
