### ISSUE TITLE
Wait until file saved before opening its associated source control repo

### ISSUE THREAD

**Issue by DragWx** [microsoft/vscode#73686]
Right now, whenever you open a file which is part of a source control repository, VS Code automatically opens the repo and adds it as a source control provider, which seems like a nice idea, but I don't usually want/need that to happen.

My usage pattern with VS Code and Git is:
- I will open the folder in VS Code when I want to work on the project, and therefore, want to have the repo opened.
- When I open a single file from a project, without opening the folder itself, it's because I want to check something in the file, or I want to reference the content of the file, with no intention of editing it.
- My environment is such that I have several small projects which I often need to cross-reference, each with their own Git repo.

A simple improvement would be to wait until a file is modified and saved before opening its associated repo. It could even be a setting:
- Open on file open (current behavior)
- Open on file modified
- Open on file saved w/ changes (what I would use)

**Comment by skprabhanjan** [comment]
@DragWx , When I open a file which is part of a source control repository, It does not open the repo automatically .
@joaomoreno , Can you please confirm on this scenario ?

**Comment by joaomoreno** [comment]
@skprabhanjan You might have configured the `git.autoRepositoryDetection` setting.

**Comment by skprabhanjan** [comment]
@joaomoreno , This is what I am doing 

- `git.autoRepositoryDetection` is already set to true.
- I open one file from the repo but it does not open the repo(that whole folder) ( It shows You have not opened any folder yet )
PS : I did a bit of debugging and it is not entering the loop [here](https://github.com/microsoft/vscode/blob/master/extensions/git/src/model.ts#L100) , The value of `workspace.workspaceFolders` is `undefined`

Am I doing something wrong ?

**Comment by joaomoreno** [comment]
Steps:

1. New Window. Notice the SCM panel shows no repositories.
2. Open File, choose a file which lives inside a git repo.

Notice the SCM panel now shows that repository.

**Comment by skprabhanjan** [comment]
@joaomoreno , so it is about the SCM panel .
I assumed it will open the complete repo ( as folder I mean)
Thanks for the clarification  , I will work on this :)

**Comment by joaomoreno** [comment]
I'd like to see a setting for this. Either a new one, or a modification to the current one. What do you propose?

**Comment by skprabhanjan** [comment]
@joaomoreno , does this require a new setting gievn that there are already many settings for git now.
I will try with the current one and let you know.
Thanks :)

**Comment by joaomoreno** [comment]
How about we add another value `fileSaved`? We should also make the setting accept an array, so people can mix and match the values.
