### ISSUE TITLE
Terminal window - By default it is not showing command prompt.

### ISSUE THREAD

**Issue by codebizness** [microsoft/vscode#73683]
Issue Type: <b>Bug</b>

I'm facing a behaviour in VS Code, everytime when I try to land on terminal window, by default it is not showing command prompt.  It happens when I restart VS Code and  I've to press enter or scroll down to see to see command prompt.

This seems somehow UX issue, 

![issue in VS Code](https://user-images.githubusercontent.com/16349394/57643768-f924d280-75d3-11e9-8171-59cfae21198b.PNG)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2891)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
docker-explorer|for|0.1.6
mssql|ms-|1.6.0
powershell|ms-|1.12.1
vscode-docker|Pet|0.6.2
vsc-docker|Zim|0.34.0

(1 theme extensions excluded)

</details>

**Comment by iansan5653** [comment]
I have an almost identical issue. If my default terminal is set to `cmd` and I reload VSCode with the terminal closed, when I drag from the status bar to open the terminal, it only appears as one line at the bottom:
![image](https://user-images.githubusercontent.com/2294248/57644340-e9809c00-7589-11e9-986e-57a07411159d.png)
This stays if I start typing, but goes away if I make a new terminal or resize the terminal. If I run a command, only the bottom line of the command output shows. All new terminals after the initial one that's made on startup work totally fine. The issue does not occur if the terminal path is set to the path of the powershell executable.

> Version: 1.34.20-insider (user setup)
> Commit: 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
> Date: 2019-05-10T17:36:45.765Z
> Electron: 3.1.8
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.15063

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
