### ISSUE TITLE
Stacks: Cannot split editor in Git Diff View

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#7368]
- VSCode Version: commit a3c38e902fc6dbe06d80f43d5cf527b066499f51
- OS Version: Mac OS X

Steps to Reproduce:

1. Make some changes to a file and view it in the Git Diff View from the activity bar
2. Note that there is no affordance to split the editor

<img width="485" alt="screen shot 2016-06-07 at 4 12 58 pm" src="https://cloud.githubusercontent.com/assets/11839736/15877806/ff2f590c-2cca-11e6-928a-73fbbf674dea.png">

**Comment by bpasero** [comment]
We never showed the split action for the diff editor. I do not think there is much of a use case. Editors can opt in to allow for split and the diff is not included. E.g. we would also not show a split action for the editor that hosts the extensions once we go there.
