### ISSUE TITLE
Debug is adding extra white space/carriage returns

### ISSUE THREAD

**Issue by walkingbytrees** [microsoft/vscode#73689]
Issue Type: <b>Bug</b>

I can't figure out why I'm getting extra white space between my output. If I code for a space with " ", I get a line break. No idea how to find a solution.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.4.12954
vscode-yaml|red|0.4.0

</details>

**Comment by roblourens** [comment]
Please give exact steps for how to reproduce this issue. What language, what is a code snippet that shows the issue, etc.

**Comment by walkingbytrees** [comment]
It's python. I've attached a screen shot, but any sort of code that should
produce ouptut like:
1
2
3
Produces output instead like:
1

2

3
(With an extra return)

**Comment by roblourens** [comment]
Please file this on the python extension's repo. Also you need to use github.com to include your screenshot, I can't see an email attachment.

**Comment by walkingbytrees** [comment]
It would be helpful if you could provide me a link to the python extension's repo.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-python/issues

**Comment by walkingbytrees** [comment]
Thanks!
