### ISSUE TITLE
"Toggle Terminal" Keyboard Shortcut not working | Code Exploration

### ISSUE THREAD

**Issue by electricarts** [microsoft/vscode#73688]
- VSCode Version: Code - Exploration Version 1.34.0-exploration 2019-05-09T07:43:26.671Z
- OS Version: MacOS 10.14.4

In the latest version of VSCode Exploration the keyboard shortcut to call the integrated terminal ctrl+` does not work. In VSCode Insider and in VSCode Stable it works without problems. All settings are identical (synchronized with "Settings Sync"). 

What's also very strange is that if I want to change the keyboard shortcut manually and type in the right key combination, ctrl+[IntlBackslash] is displayed.

![VSC-Terminal](https://user-images.githubusercontent.com/625286/57646783-ab06d380-75c1-11e9-9bc9-c68c17eeba99.gif)

**Comment by Tyriar** [comment]
@electricarts  can you check if this happens on the Insiders build?

**Comment by electricarts** [comment]
No. In the Stable and the Insider Build (Version 1.34.20-insider) the Key Command works.

**Comment by bpasero** [comment]
This is a known issue until we pick up the official electron builds.
