### ISSUE TITLE
Setting to Disable Outline Sidebar

### ISSUE THREAD

**Issue by nathanjd** [microsoft/vscode#73694]
## Search Terms

performance, outline, sidebar, settings, markdown, typescript

## Suggestion

A setting to disable the sidebar outline altogether.

```javascript
userSettings.outline.isDisabled = true;
workspaceSettings.outline.isDisabled = true;
```

Alternatively, if it could be hidden by default and the work could be deferred until the first expansion that would be satisfactory.

```javascript
userSettings.outline.shouldHideByDefault = true;
workspaceSettings.outline.shouldHideByDefault = true;
```

## Use Cases

- Outline sidebar can cause UI non-responsiveness. Particularly on large markdown documents.
- Personally, I dislike the visual noise so would at least like a setting to hide by default. Having to manually collapse it upon opening every window is frustrating.

## Examples

The following are bugs, but represent a few reasons why a developer might want to disable the outline to improve performance. At least until a plugin's performance issues are resolved, which could be dependent on a 3rd party.

- https://github.com/microsoft/TypeScript/issues/28389
- https://github.com/yzhang-gh/vscode-markdown/issues/42

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by mjbvz** [comment]
Right click on an explorer side bar header, then uncheck `Outline`:

<img width="541" alt="Screen Shot 2019-05-13 at 3 33 28 PM" src="https://user-images.githubusercontent.com/12821956/57658641-7fb9bf80-7594-11e9-8bdc-b86118acdf48.png">

**Comment by nathanjd** [comment]
Thank you! If this setting is not stored in settings, where is it stored?
