### ISSUE TITLE
Go to definition on network drives not working 

### ISSUE THREAD

**Issue by DeadRabbits307** [microsoft/vscode#73705]
Following configuration:
Windows 10 Pro, 10.0.1563 Build 15063
VS Code: 1.31.1
C/C++ Extension: 0.22.2

If my Project is placed on a Network drive, the go to definition functionality is not working properly. The popup window "no definition found" appears. Additionally files open with ist filenames in uppercase letters (f.e. ioport.h opens as IOPORT.H)

Working with the same Project on a local drive, everything works fine, so I assume c_cpp_properties.json is set correctly:

```
 {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}",
                "../linux-4.15.16_include_linux"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64"
}
```

**Comment by DeadRabbits307** [comment]
Solution was found, hope this helps other VS code sympathizers:

Network drive has to be mapped to a local drive letter!
**Example:**
`\\anydriver\dir1\dir2\myproject `                           does not work
`X:\anydriver\dir1\dir2\myproject `                          works!

**Comment by mjbvz** [comment]
Please file this issue against the c++ extension
