### ISSUE TITLE
activate extension tab in a split view by mouse click

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#73704]
in case you have the extension tab in a split view, because the view is read-only it means u cant activate it with a mouse click like any other tab,
which means if u tried to close it you will close a different tab "the previously focused one" and your only solution would clicking on the extension tab it self to make it active.

**Comment by gjsjohnmurray** [comment]
I think #71774 has fixed this in 1.34 Insiders

**Comment by ctf0** [comment]
just tested it out and u r correct
