### ISSUE TITLE
When using a variable-width font, line numbers should use tabular numbers

### ISSUE THREAD

**Issue by gubikmic** [microsoft/vscode#73700]
(This is obviously very low priority)

When using a variable-width (i.e. non-monospaced) font, the line numbers look bad since e.g '1' is more narrow than '0'.

With the CSS `font-variant-numeric: tabular-nums` all digits would be of equal width.

<img width="51" alt="line numbers" src="https://user-images.githubusercontent.com/152910/57667961-31f69300-7638-11e9-9c76-dc91d13c7202.png">

**Comment by rebornix** [comment]
It's a good thing to add once the css property becomes standard https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric
