### ISSUE TITLE
Assembly line comment toggle support

### ISSUE THREAD

**Issue by James4Deutschland** [microsoft/vscode#73701]
Issue Type: <b>Feature Request</b>

Currently VS Code does not support toggle line comment in an .asm file.
Please add this feature soon or I have to hack into your software.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by sbatten** [comment]
@James4Deutschland Please look for an extension that supports ASM files to have this feature. If you have already chosen an extension that you like, please file an issue against that extension.
