### ISSUE TITLE
How to hide the suggestionWidget when no suggestion

### ISSUE THREAD

**Issue by PuffLady** [microsoft/vscode#73709]
I wish get suggestions when type inside a word,so my code is like:
` vscode.workspace.onDidChangeTextDocument(event => {
		if (event.document.languageId !=='xml') {
			return;
		}
		if (/*some condition*/) {
			vscode.commands.executeCommand('editor.action.triggerSuggest');
		}
}, null, context.subscriptions); `

it will trigger the call of provideCompletionItems, but when it return no suggestions,the suggestionWidget still show on the editor with text 'No suggestions.'
This is not what i want.
Is there any way to solve it?

I really hope to get help 🙏

**Comment by gjsjohnmurray** [comment]
```if (/*some condition*/) {```

Make ```some condition``` work out whether your extension is going to make any suggestions?

**Comment by PuffLady** [comment]
This is okay too，but it would be more complicated,I need to make more judgments.

I want to know if there is a way to decide by parameter that it will not be displayed when there are no more suggestions when I call triggerSuggest

**Comment by jrieken** [comment]
What you are trying to do is very shaky. However, you can following your approach and invoke the corresponding hide command (that one that's bound to ESC) when no suggestions have been returned (assuming its you computing those suggestions)

**Comment by PuffLady** [comment]
ok,thank you for your reply~
