### ISSUE TITLE
Terminal not working fine

### ISSUE THREAD

**Issue by vijay14887** [microsoft/vscode#73708]
Issue Type: <b>Bug</b>

My Terminal is not working fine. I am getting error as "The terminal process command 'C:\Users\Feather\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell' failed to launch (exit code: 2)"

Could you please help in resolving this issue?

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.0.2
flutter|Dar|3.0.2
gitlens|eam|9.7.3
vscode-gutter-preview|kis|0.19.0
debugger-for-chrome|msj|4.11.3
awesome-flutter-snippets|Nas|2.0.2
color-highlight|nau|2.3.0

</details>

**Comment by nikolovski** [comment]
Open **Preferences** -> **Settings** (Ctrl+,) then search for **terminal.integrated.shell.windows**. The value should be the location of Powershell `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` if you like to use Powershell. You can also go with Command Prompt `C:\Windows\System32\cmd.exe`.

**Comment by vijay14887** [comment]
Issue resolved now!
Thanks a million for all your help @nikolovski .

**Comment by Tyriar** [comment]
Even better, there is a command accessible via the command palette (F1) that makes swapping this easy on Windows:

![image](https://user-images.githubusercontent.com/2193314/57716460-e9d27300-762d-11e9-895f-892662895df6.png)
