### ISSUE TITLE
Opening a base tsconfig with ctrl + click does not work for Node.js package paths

### ISSUE THREAD

**Issue by qtiki** [microsoft/vscode#73718]
Issue Type: <b>Bug</b>

1. Open a tsconfig.json file with a Node.js style extends path (support added in TypeScript 3.2): https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#tsconfigjson-inheritance-via-nodejs-packages
2. Ctrl + click the path to open the file

This will result in an error "Unable to open tsconfig.json: File not found". The path in the error shows that the file is not looked up inside node_modules as it should.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Duplicate of #71639. Fixed in April release (1.34)
