### ISSUE TITLE
Opening a new terminal causes text input to be in the wrong place

### ISSUE THREAD

**Issue by lloydjatkinson** [microsoft/vscode#73716]
Issue Type: <b>Bug</b>

 - Open VS Code
 - Open new terminal
 - It has scrolled far enough down to hide the "Windows Powershell - All rights reserved" message
 - Text input starts randomly offset from the left
 - Not obvious that the terminal has opened yet

This issue has been present for at least a few months (not sure of exact versions).

![image](https://user-images.githubusercontent.com/5633938/57688184-c0691580-7634-11e9-8917-6754f958f245.png)
![image](https://user-images.githubusercontent.com/5633938/57688199-c959e700-7634-11e9-917a-2a517333e551.png)
![image](https://user-images.githubusercontent.com/5633938/57688208-cfe85e80-7634-11e9-863b-67d12c8b9727.png)
![image](https://user-images.githubusercontent.com/5633938/57688225-dbd42080-7634-11e9-8365-68a001874732.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (20.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
vetur|oct|0.20.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.6.0
vscode-status-bar-format-toggle|tom|1.5.0
highlight-matching-tag|vin|0.9.1
vuetify-vscode|vue|0.2.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by 0x4c6565** [comment]
I am having the exact same symptoms. Also using Windows 10 build 17763

**Comment by lloydjatkinson** [comment]
I've seen this in Windows 8.1 as well as 10

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by lloydjatkinson** [comment]
We need to wait for Windows 10 updates to stop VS Code's terminal scrolling too far? I thought the terminal was implemented in JS? 👎

**Comment by Tyriar** [comment]
@lloydjatkinson most of it is, [the backend](https://github.com/rprichard/winpty) that talks to the conhost window is C++ and something in Windows that it relied upon broke in 1809.
