### ISSUE TITLE
Git extension lag in March 2019 (version 1.33) Update 1.33.1

### ISSUE THREAD

**Issue by MainaMurage** [microsoft/vscode#73712]
So basically there is a major lag when I make changes on my files after the update 
Where the git extension that handles commit messages and commits, in general, does not pick up changed files and queue them for committing!
Which is highly annoying

**Comment by joaomoreno** [comment]
> So basically there is a major lag when I make changes on my files after the update

Can you explain? Lag while typing? While refreshing? Can you also provide more details about your system?

```
<!-- Please search existing issues to avoid creating duplicates. -->
<!-- Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/ -->

<!-- Use Help > Report Issue to prefill these. -->
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes/No
```
