### ISSUE TITLE
Failed to connect to a remote Jupyter notebook

### ISSUE THREAD

**Issue by arnaudlegout** [microsoft/vscode#73714]
VSCode Version:1.33.1
OS Version: Windows 10.0.17763
VS Code Jupyter Notebook Previewer Version: 1.2.2

Steps to Reproduce:
I'm trying to connect to a remote Jupyter notebook.

Using CTRL+ Shift + P -> Python: Specify Jupyter server URI
Then I select
Type in a URI to connect to a running Jupyter server

I enter the URI of my running jupyter server
http://localhost:8090/?token=9efe2458be0637d5ebf134806ec2b4d3e8946b84f1f5e811

When I press enter, nothing happen. 

I can access the Jupyter notebooks using Firefox with the same URL.
I made sure the server is actually running. When I enter the URI in VS code, I do not see any log in the Jupyter server console. 

I am completely new to VS Code, so if you ask me to give you additional information, please consider I am a newbie.

**Comment by sbatten** [comment]
Hi @arnaudlegout, please direct issues with extension functionality to the extension you are using. In this case https://github.com/jithurjacob/vscode-nbpreviewer
