### ISSUE TITLE
Integrated terminal does not focus windows that are opened by terminal commands

### ISSUE THREAD

**Issue by kasrasadeghi** [microsoft/vscode#73710]
## VSCode Version: 
```
 $ code --version
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
x64
```

## OS Version:
```
 $ cat /etc/os-release 
NAME="Antergos Linux"
PRETTY_NAME="Antergos Linux"
ID=antergos
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
```
```
 $ uname -r
5.0.13-arch1-1-ARCH
```

## Steps to Reproduce:

1. Open `code`
2. Run an executable that opens a window in the `integrated-terminal`
-> It's not focused

This happens inconsistently and I have not been able to differentiate what kinds of windows are focused and what kinds aren't.

But in a specific instance:
- I compiled the hello world project for [zserge/webview](https://github.com/zserge/webview#webview-for-cc-developers) and it does not focus when I run it on my integrated terminal. It opens in the background.
```bash
g++ example.cpp -DWEBVIEW_GTK=1 `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0`  -o webview-example
./webview-example
```
As a counter-example:
- running `cmake-gui .` in a directory with a CMakeLists.txt focuses the window. Very strange.

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by Tyriar** [comment]
I suspect this is related to the OS suppressing it somehow, I can't reproduce in Ubuntu 18.04.
