### ISSUE TITLE
VS Code listens to random port when opened

### ISSUE THREAD

**Issue by DavSanchez** [microsoft/vscode#73719]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.4

I have realised that some VS Code functionality seems to begin listening to a random port whenever it's opened. Apparently it is for WebSockets requests.

```
$ sudo lsof -PiTCP -sTCP:LISTEN
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
# Other process
# Other process
Code\x20H 14404 ****   37u  IPv4 0xcc5f858ae8e4fa6d      0t0  TCP localhost:27741 (LISTEN)

$ ps -p 14404
  PID TTY           TIME CMD
14404 ??         0:04.32 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --nolazy --inspect=27741 /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork --type=extensionHost
```

My question is, is this normal? I thought it could be due to some extension, but I tried disabling all extensions and reloading VS Code and the issue persists.

Does this issue occur when all extensions are disabled?: Yes

Thank you!

**Comment by jrieken** [comment]
Yeah, that's the extension host process and it enabling the inspector protocol. We use this to profile extensions when the extension host process becomes unresponsive.
