### ISSUE TITLE
json

### ISSUE THREAD

**Issue by crownkola** [microsoft/vscode#73711]
Issue Type: <b>Bug</b>

json issue

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E-450 APU with Radeon(tm) HD Graphics (2 x 1646)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.60GB (1.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
output-link-to-file|93a|0.0.15
vscode-standard-format|che|0.0.12
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
terminal|for|0.0.10
composer|ika|0.7.1
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
js-atom-grammar|ms-|0.1.14
powershell|ms-|1.12.1
java|red|0.44.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
wallaby-vscode|Wal|1.0.127
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
> Issue Type: Bug
> 
> json issue

@crownkola assuming you are a software developer yourself, how would you start investigating a bug report like this?

**Comment by Kieran-Bacon** [comment]
It would seem that their issue is with the JSON standard itself :P it is a fickle master indeed.
