### ISSUE TITLE
Make the activitybar thinner with smaller icons

### ISSUE THREAD

**Issue by Girijapathi** [microsoft/vscode#73713]
Issue Type: <b>Feature Request</b>

Please reduce width of activity bar, and reduce icons size as well :).
Also provide options in theme to change color of sidebar so that we don't miss sublume theme ;)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sbatten** [comment]
@Girijapathi there are several feature requests here. Please file a single issue per request. As for the sidebar color, this is currently themeable with https://code.visualstudio.com/api/references/theme-color#side-bar

**Comment by sbatten** [comment]
Maybe title request is a duplicate @bpasero @misolori

**Comment by misolori** [comment]
I attempted to do this with https://github.com/microsoft/vscode/pull/52641 but need to consider a few things:
- Allow this to be configurable via a setting
- Options to include:
  - Responsive (based on dpi and window size)
  - Small/large
  - None (current)

**Comment by HubKing** [comment]
The activity bar's icons are humorously large, and the bar has lots of empty wasted space.And the icons are not even that intuitive. Why not provide an option to make it look like Visual Studio or Android Studio, where the labels are thin vertical text? It will be more consistent with other IDE's, taking less space, and easier to see what they are, instead of cryptic images.

![image](https://user-images.githubusercontent.com/10900489/82087466-1e8a7600-972b-11ea-9297-777db38309ab.png) ![image](https://user-images.githubusercontent.com/10900489/82087536-437ee900-972b-11ea-8204-6c72462c5abc.png)

**Comment by AntonioNoack** [comment]
What is the status on this? I only see multiply closed feature-requests.
Also adding options doesn't limit anyone.

**Comment by marcodallagatta** [comment]
> What is the status on this? I only see multiply closed feature-requests. Also adding options doesn't limit anyone.

Agree. I've been using [this solution](https://stackoverflow.com/questions/45048214/activity-bar-width-in-visual-studio-code) but it creates other problems.

**Comment by naourass** [comment]
Waste of space... So unfortunate.

**Comment by bolololololo** [comment]
I wish they were like in Obsidian, it's the ideal size (or even a little smaller). I can't believe this can't be changed, has anyone tried to tweak it?
![sadasdsd](https://user-images.githubusercontent.com/80776140/233528259-a2a35ce9-afe1-45ed-87b8-6eb15a2cf102.png)

**Comment by temasaguru** [comment]
For those who looking for solution, [APC extension](https://github.com/drcika/apc-extension) can modify activity bar size like this:

```json
  "apc.activityBar": {
    "size": 32
  }
```

**Comment by RokeJulianLockhart** [comment]
https://github.com/microsoft/vscode/issues/129771#issue-955874182

**Comment by Alecton4** [comment]
Sadly the APC extension [mentioned above](https://github.com/microsoft/vscode/issues/73713#issuecomment-1684616394) stops working starting from VSCode 1.93. I don't understand why this issue has been closed and is not being solved. 

Any benefits of having a wide activity bar if VSCode is not targeting touch screens?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/vscode/issues/73713#issuecomment-2345378753

@Alecton4, see my previous comment - https://github.com/microsoft/vscode/issues/73713#issuecomment-2334038322 - because it contains a URI to a duplicate issue.

**Comment by oliveryasuna** [comment]
I've opened a new issue: https://github.com/microsoft/vscode/issues/247466
