### ISSUE TITLE
Accessibilty: allow highlight current line styling

### ISSUE THREAD

**Issue by wulftone** [Microsoft/vscode#7372]
Related to https://github.com/Microsoft/vscode/issues/5678, but I have always had trouble seeing which line my cursor is on, so I like to have a nice light transparent grey across the entire line (See screenshot)

<img width="588" alt="screen shot 2016-06-07 at 4 41 20 pm" src="https://cloud.githubusercontent.com/assets/142784/15878315/c069a0f2-2cce-11e6-99c2-ffe622777c65.png">

I'd like to be able to select my own line highlight style for my own accessibility concerns.

Unfortunately the cursor is not in the screenshot, but it's a bright white vertical line for me.

**Comment by alexandrudima** [comment]
We do have a current line highlight:

![image](https://cloud.githubusercontent.com/assets/5047891/15885826/0501fd46-2d5a-11e6-999e-40d0002566d0.png)

**Comment by wulftone** [comment]
Ok your style is different. I'll need to look into how to edit that for the default dark theme because it just looks like two very faint lines on mine (screenshot was from sublime), and it doesn't do line highlight during find, just word highlight.
