### ISSUE TITLE
Right Clicking preview window when hovering over the VSCode icon in the TaskBar activates the VSCode window instead of opening the right-click context menu

### ISSUE THREAD

**Issue by thered121** [microsoft/vscode#73722]
Issue Type: <b>Bug</b>

I use VSCode on a laptop that has a docking station.  Somtimes, after undocking, the VSCode window opens partially off screen due to the change in screen resolutions from my monitors to my laptop monitor.  Other applications (like Outlook) also sometimes exhibit this behavior however, I am able to right-click the preview window in the taskbar for those applications and get a context menu that allows me to move the window back onto my screen.  When attempting the same in the latest version of VSCode the VSCode window activates rather than displaying the right-click context menu.  

Steps to Reproduce:

1. Open VSCode
2. Hover over the VSCode icon in the Windows Task Bar so the preview window for VSCode pops up
3. Right Click

Expected Behavior: Right click context menu appears allowing the user to Restore, Minimize, Close, Move etc the VSCode window

Actual Behavior: The VSCode window in activated (same as left-clicking the preview window)

Does this issue occur when all extensions are disabled?: Yes
Does this issue occure in VSCode Insiders?: Yes

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.38GB (19.42GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by sbatten** [comment]
@thered121 Please see the info in this issue. https://github.com/microsoft/vscode/issues/73534#issuecomment-491369081
