### ISSUE TITLE
Line position when comparing

### ISSUE THREAD

**Issue by lucasbaccan** [microsoft/vscode#73726]
Issue Type: <b>Bug</b>

When I compare two files, only the file on the right side hava the "status bar", i don't know if is this the name, but only the right side have this.

For me, i need to compare the selected text between, but it not show the exactly place, and i need to count.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.23GB free)|
|Process Argv|C:\Users\Baccan\Desktop\SEFIP_GTECH_04.2019.RE|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|10.4.3
pascal|ale|8.0.1
pascal-formatter|ale|2.2.0
vscode-eclipse-keybindings|alp|0.10.0
google-translate-ext|ben|1.3.1
vscode-postgres|cko|1.1.10
githistory|don|0.4.6
gitlens|eam|9.7.3
prettier-vscode|esb|1.9.0
code-runner|for|0.9.9
vscode-google-translate|fun|1.1.5
innosetup|idl|1.2.0
vscode-add-angular-native-files|jos|0.0.11
vsliveshare|ms-|1.0.181
vscode-docker|Pet|0.6.2
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.2.9
javascript-typescript|sou|0.0.7
open-in-browser|tec|2.0.0
nativescript|Tel|0.10.0
vscode-icons|vsc|8.6.0
local-history|xyz|1.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot and point out what the "status bar" is?

**Comment by lucasbaccan** [comment]
I posted two pictures, one i have the mouse focus on the left, and the status bar only show the position of my cursor on the right text.

Focus os left
![Screenshot_28](https://user-images.githubusercontent.com/2676484/58051914-ccb80b80-7b29-11e9-821f-d7c854894571.png)

Focus os right
![Screenshot_27](https://user-images.githubusercontent.com/2676484/58051913-ccb80b80-7b29-11e9-92a3-8b2d20945356.png)
