### ISSUE TITLE
Ability to customize deleted/inserted hunk colors

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode#73727]
The [color theme I'm using](https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai) has nice palette overall, but the diff colors shown in git's manual hunk edit mode (and in some other contexts) are not very pleasant. I've tried to customize them but none of the documented keys seem to work. The colors are [defined in the keys named `diff.deleted` and `diff.inserted`](https://github.com/azemoh/vscode-one-monokai/blob/a648dd4602e0a3a145ad1d75a9f2259e8c723046/themes/OneMonokai-color-theme.json#L390-L403) of the theme definition file.

Quoting [the PR](https://github.com/azemoh/vscode-one-monokai/pull/31) where I proposed a change to the theme's default colors:

> These colors are visible, for example, in the diff underneath a commit message that's being edited using vscode (`git -c core.editor='code --wait' -c commit.verbose=true commit`), or when editing a hunk during staging in patch mode (`git -c core.editor='code --wait' add -p`, then <kbd>e</kbd>)
>
> Unfortunately, these colors don't seem to be customizable via `settings.json` :( the [`diffEditor.*`](https://code.visualstudio.com/api/references/theme-color#diff-editor-colors) settings only apply to virtual editors (e.g. when clicking on an edited file in the git sidebar), and the [`gitDecoration.*`](https://code.visualstudio.com/api/references/theme-color#git-colors) are for the files themselves in the sidebar.

If there's indeed a way to customize these colors via `settings.json` that I'm not aware of, I'd be happy to submit a PR adding the missing documentation. Otherwise, it would be nice to expose keys to customize them from the end-user side.

**Comment by joaomoreno** [comment]
Can you take a screenshot of the features you want to customize?

**Comment by waldyrious** [comment]
Sure. These are the colors I would like to be able to change by editing `settings.json`:

<img width="955" alt="Screenshot 2019-05-24 at 17 14 21" src="https://user-images.githubusercontent.com/478237/58343391-c340e300-7e4a-11e9-9598-cb4f7b77aa87.png">

**Comment by joaomoreno** [comment]
![screenshot QmR8sa](https://user-images.githubusercontent.com/22350/58414234-1bf6c280-807b-11e9-8954-a4a006dfd984.png)

```
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "markup.deleted",
				"settings": {
					"foreground": "#ff00ea",
					"fontStyle": "bold"
				}
			},
```

**Comment by waldyrious** [comment]
@joaomoreno thanks! I couldn't find these in the [theme color reference documentation](https://code.visualstudio.com/api/references/theme-color). Should I be looking somewhere else? I'd be happy to contribute the documentation if it's missing.

**Comment by joaomoreno** [comment]
These are token colors. More here: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#tokens-and-scopes

**Comment by waldyrious** [comment]
@joaomoreno thanks, I can see that a link to the syntax highlighting guide is indeed available in the color theme guide, but I missed it at first.

That said, even if I had found that page earlier, I don't think I'd have been able to figure out how to customize those colors. Even in the [reference documentation for TextMate scopes](https://macromates.com/manual/en/language_grammars) linked from there there is no mention of the `markup.deleted` scope.

I'm not sure that's something that the VSCode documentation should cover, but at least I'm glad this issue may help others who have the same question.

**Comment by joaomoreno** [comment]
cc @alexandrudima @rebornix
