### ISSUE TITLE
Extension Marketplace doesn't load (Linux + Proxy)

### ISSUE THREAD

**Issue by theirpuppet** [microsoft/vscode#73720]
Issue Type: <b>Bug</b>

Searching the extensions marketplace appears to timeout with an error that it is unavailable. We have a proxy in use, but I can definitely see VSCODE using it (set in the shell via /etc/profile.d/proxy.sh). I am posting this bug from the same system; so the proxy does work.

1557836574.245    161 X.X.X.X TCP_MISS/200 455 POST https://vortex.data.microsoft.com/collect/v1 - HIER_DIRECT/40.77.226.250 application/json
1557836709.065    417 X.X.X.X TCP_MISS/200 455 POST https://vortex.data.microsoft.com/collect/v1 - HIER_DIRECT/65.55.44.109 application/json
1557836871.246    494 X.X.X.X TCP_MISS/200 455 POST https://vortex.data.microsoft.com/collect/v1 - HIER_DIRECT/65.55.44.109 application/json

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 3.10.0-957.12.1.el7.x86_64 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (2 x 2199)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.80GB (3.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by schwobr** [comment]
I have the same problem. I configured my proxy in vscode but still can't even load marketplace. Development tool shows `Failed to load resource: net::ERR_CONNECTION_TIMED_OUT` and `workbench.main.js:5503 POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery 0 ()`. 

I'm on same vscode version and linux 18.04.

**Comment by sandy081** [comment]
@chrmarti is our proxy expert. Any insights here?

**Comment by chrmarti** [comment]
Does Chromium work? (Same network library as VS Code's UI.)

**Comment by schwobr** [comment]
It does not for me.

**Comment by chrmarti** [comment]
@schwobr Chromium's settings have a link to the OS proxy settings, I think. Try configuring these to get Chromium working and VS Code should start working too.

**Comment by schwobr** [comment]
My OS settings are configured so that everything else works. Is there anything particular I need to add for chromium/vs code ?

**Comment by chrmarti** [comment]
Ubuntu has UI for network settings with properties for the proxy. Which distro are you using?

**Comment by schwobr** [comment]
I use ubuntu, and I know there is UI for proxy, I configured that. Internet works on the machine and with every app except for vscode and chromium. Is there an exception to add or something ?

**Comment by chrmarti** [comment]
Does this apply: https://askubuntu.com/questions/513840/google-chrome-proxy-settings?

**Comment by schwobr** [comment]
I did that and it made me notice something strange: it now works, but only when I start the app from the "show applications" window, which I never tried before. I always start it with the `code` command, and when I do it still doesn't work for some reason. It is possible it was working all along as I never tried to start it directly. 
Anyway, I guess it can be closed as I now have a workaround. But still strange that both chromium and vscode don't get proxy support when started from command line.

**Comment by theirpuppet** [comment]
> @schwobr Chromium's settings have a link to the OS proxy settings, I think. Try configuring these to get Chromium working and VS Code should start working too.

Hello! Thanks for your input. "OS proxy settings", in Linux, is not that clear. Some applications will honour http_proxy as set in ~/.profile (or /etc/profile). Some applications will honour HTTP_PROXY from /etc/environment. Some applications will only honour settings in a Window Manager / Desktop Environment. I think vscode and firefox are the latter.

For example: the following will enable CLI utilities, like wget, to work:
$ echo '#!/bin/sh' > /etc/profile.d/proxy.sh
$ echo 'export http_proxy="http://IP.ADDR:3128/"' >> /etc/profile.d/proxy.sh
$ echo 'export https_proxy="https://IP.ADDR:3128/"' >> /etc/profile.d/proxy.sh
$ echo 'export no_proxy="127.0.0.0/8, localhost, ::1, LOCAL.NET/X"' >> /etc/profile.d/proxy.sh
$ chmod 755 /etc/profile.d/proxy.sh

A simple command will prove the shell has these settings:
$ set | grep proxy

But vscode and firefox do not appear to honour this. So I tried some system-wide settings in Gnome, and firefox started working but not vscode. I have since recreated the experiment, with a perfected dconf setup, and I have no issues. Therefore I believe vscode uses the proxy settings from the Window Manager / Desktop Environment only.

Is that true or do you expect vscode to honour $http_proxy and $https_proxy from the shell's environment?

**Comment by schwobr** [comment]
What's strange to me is that vscode/chromium don't take any proxy setting into account when started from a shell, as I configured both shell proxy and window manager proxy and still don't get connection on either of them. I wonder which configuration they load when started from shell.

**Comment by chrmarti** [comment]
I expected it to pick up the OS settings when started from the shell too. Not sure what might play into this.

You can also pass a command line argument: https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by schwobr** [comment]
Even with using `code . --proxy-server="http=addr:port;https=addr:port"` it doesn't work, that's very strange. I set my proxy everywhere I could think of, seems there is some place where it misses.
