### ISSUE TITLE
Provide a homeDir system variable for use in launch.json

### ISSUE THREAD

**Issue by gmariani** [microsoft/vscode#73730]
*** This is just a revival of ticket 11337 since it was closed. I would still like this feature and having to mess with environmental variables isn't a great solution in my mind **

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I have VS Code installed on two computers and use settings sync between the two. But both computers have different usernames. So the settings don't match up. Having a profile variable would make it seamless.

So instead of 
"php.executablePath": "/Users/<username>/Documents/php-7.3.5-nts-Win32-VC15-x64/php.exe",
it would be
"php.executablePath": "${homeDir}/Documents/php-7.3.5-nts-Win32-VC15-x64/php.exe",

Below is the original ticket
https://github.com/microsoft/vscode/issues/11337

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/11337
Bet let's keep it open for now.

**Comment by roblourens** [comment]
Is this for launch.json? That looks like a setting. But this seems exactly like a use case for using an environment variable. The only unfortunate part is that if you are supported multiple platforms, windows uses a different env var name vs mac/linux.

**Comment by gmariani** [comment]
I'm unfamiliar with launch.json, but that is from my settings.json file. I have a PHP linter that requires a path to a PHP executable. But due to the path differences I have to manually adjust it for each. Additionally, it forces me to keep the Settings Sync extension from running automatically because it would break for one of the two computers each time it updates.

**Comment by connor4312** [comment]
It sounds like the meta-issue is using Settings Sync to sync per-device settings between machines. You can configure settings sync to [ignore certain settings](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#ignoring-certain-settings) to avoid having it overwrite the executable path when syncing them between machines. It sounds like the extension is the cause of your particular issue.

I think I agree with @roblourens here about the usage of environment variables in general. While [os.homedir](https://nodejs.org/api/os.html#os_os_homedir) is accessible, using it inside a setting shared by multiple machines will depend upon each machine having the exact same layout of whatever files we're looking for inside the home directory. Using an environment variable would be a more resilient approach for this scenario, once https://github.com/microsoft/vscode/issues/2809 happens.
