### ISSUE TITLE
Ctrl+F12  memory overflow

### ISSUE THREAD

**Issue by wagnerfonseca-luizalabs** [microsoft/vscode#73736]
Issue Type: <b>Bug</b>

Hi

When I press ctrl+12 memory overflow. This is common on any files, small or big file.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.50GB (0.18GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
code-runner|for|0.9.9
theme-monokai-pro-vscode|mon|1.1.13
Go|ms-|0.10.2
material-icon-theme|PKi|3.7.0
vscode-yaml|red|0.4.0
vscode-icons|vsc|8.6.0
vscode-react-native|vsm|0.9.2
JavaScriptSnippets|xab|1.7.2
vscode-proto3|zxh|0.2.2

(4 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
I'm guessing you are using JS, is this correct? @wagnerfonseca-luizalabs

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Test using the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled and share the output of `code-insiders --status`

**Comment by wagnerfonseca-luizalabs** [comment]
> I'm guessing you are using JS, is this correct? @wagnerfonseca-luizalabs

I don't.

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
