### ISSUE TITLE
Breakpoints are not hit on Windows if they are set on lines of a file opened using JUNCTION path names (Node debugger)

### ISSUE THREAD

**Issue by spiralsam** [microsoft/vscode#73739]
Code version: 1.33.2 x64
Node version: 12.2.0

When using [junction](https://docs.microsoft.com/en-us/windows/desktop/fileio/hard-links-and-junctions) paths, for example, in user Home Folder using powershell:

`New-Item -Type Junction -Path "node_project" -Value 'H:\projects\node_project'`

So now the junction point link is
`<Home Folder>\node_project ==> H:\projects\node_project'`

If you open a file in Code as &lt;Home Folder&gt;\node_project\test.js, then set breakpoints, Code will not break on any of them using the node debugger (the F5 internal one that uses node.exe --inspect-brk).

However, if you open the same file as H:\projects\node_project\test.js, then set breakpoints, the node debugger breaks as expected.

I only tried node debugger - not any others.

**Comment by roblourens** [comment]
Can you try setting `--preserve-symlinks` and tell me whether it helps? Like so: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks

**Comment by spiralsam** [comment]
It looks like the symlink options do address this. For the above example test.js: including `--preserve-symlinks-main` worked.

If the test.js is then changed to `require` another junction'd .js, then `--preserve-symlinks` was _also_ needed to hit breakpoints that `require`'d .js. However, if only `--preserve-symlinks` was included in that scenario, then breakpoints weren't hit anywhere. However, that documentation reads as if that _could_ be the intended behavior (the `require` would act relative to the parent's file path as "currently" recognized by node.exe at runtime).

Anyway, using both `--preserve-symlinks-main` and `--preserve-symlinks` seems to work best so far (I guess there's some [warning/caveat](https://nodejs.org/api/cli.html#cli_preserve_symlinks)). So this looks like probably a working solution, and one which does not apply only to explicitly having used the `npm link` command.

**Comment by roblourens** [comment]
Glad you figured it out, what you describe is the correct behavior. I made a change to our docs to clarify why `npm link` is mentioned.
