### ISSUE TITLE
Allow extensions to prevent task configuration for tasks from their task providers

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#73749]
If some extension provides tasks with `workspace.registerTaskProvider`, users can configure these tasks in `tasks.json`. 

There may be a problem with that if the task provider doesn't support any task configuration, or if `tasks.json` is coming from a custom file system provider (not with `file:` scheme).

The proposal is to add an optional arg with provider options to `registerTaskProvider` where the extension can specify if the tasks from that provider are not configurable.

**Comment by alexr00** [comment]
@IlyaBiryukov you can't overwrite the properties in a task definition by configuring the task in tasks.json. Usually configuring a task is used to set a label, modify the presentation options, set the build group, etc.

Can you give a concrete example of where configuring a task would break it?
