### ISSUE TITLE
New Empty Window != New Empty Window

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#73747]
I'm using Ubuntu 18.04. this may be a GDE issue?

I have vscode pinned to the sidebar. When I right click on it there's a context menu with "New Window", "New Empty Window" etc. 

They don't really seem to be labelled well, or even behave consistently.

It seems that both options do the same thing if vscode isn't running (restore the previous workspace), and both also do the same thing when vscode is running (create a new instance of vscode)?

it's a bit annoying if I want to create a new project. I have to do "New Window" which opens my previous workspace, then "New Window" again to get a new window, then close the first window.

**Comment by Tyriar** [comment]
New Empty Window passes in the `--new-window` CLI argument as documented in `code --help`:

```
-n --new-window                   Force to open a new window.
```

If this does not work as expected please create a new issue.
