### ISSUE TITLE
Insiders can't start Go debug session: "Cannot find Delve debugger."

### ISSUE THREAD

**Issue by lirao** [Microsoft/vscode#7374]
- VSCode Version: Version 1.3.0-insider 2016-06-07T14:59:54.411Z
- OS Version: OSX El Capitian

Steps to Reproduce:

1. Set up a Go project for debugging.
2. Try to start debugging.
3. Error pops up at the top of the screen:  
```
Failed to continue: Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`.
``` 
With a prompt to edit my launch.json.

This happened in my Go projects after today's update. Did launch.json change? I can't find the Insiders nightlies release notes...

**Comment by lirao** [comment]
Upon looking at my launch.json, VSCode gives me 4 warnings messages (which can't be copied??? my cursor keeps hitting the "problem" json and there's no context menu)

basically it's:
Missing property "cwd"
"type":"go" is not valid. Valid values: ["node"]
Property "mode" and "host" are not allowed.

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-go#358
