### ISSUE TITLE
Javascript Syntax highlighting bug

### ISSUE THREAD

**Issue by Cow258** [microsoft/vscode#73757]
Issue Type: <b>Bug</b>

If you are editing the HTML file, it’s fine.
But if you try to edit the Handlebars (.hbs) file, you will feel very bad when the problem occurs.

### Reproduce Bug
1. Create a HTML file
2. Insert the following code to head tag
`<script>function foo() { if ('bar' == 'bar') { return true; } } </script>`
3. Then you will see the bug
4. Please observe the color of the code `</script>` (Closing tag)

### Personal analysis
This bug will come out when `} }` appearing.
Syntax highlighting system can't close the block correctly.
This issue occurs after VSCode version 1.32

### Expected results
![image](https://user-images.githubusercontent.com/14261588/57746083-37b8ab00-7702-11e9-85b4-0d1e50783d22.png)

### Exceptional result
![image](https://user-images.githubusercontent.com/14261588/57746271-0e4c4f00-7703-11e9-9f9b-2a4399c9a1b6.png)

### Support video
![2019-05-07 12 11 19](https://user-images.githubusercontent.com/14261588/57746171-92ea9d80-7702-11e9-8af9-42ff519dc1a5.gif)
Please observe the color of Handlebars curly braces.
Please note the end of line 4, The `} }` is appearing!

### Related Issues
From [daaain/Handlebars#103](https://github.com/daaain/Handlebars/issues/103)

### System Infomation
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-06T22:07:35.830Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|24.00GB (0.02GB free)|
|Process Argv|-psn_0_2736796|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
gltf-vscode|ces|2.2.5
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
gitlens|eam|9.7.3
vscode-mysql|for|0.4.0
minify|Hoo|0.4.3
mysql-syntax|jak|1.3.1
code-beautifier|mic|2.2.1
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hant|MS-|1.34.1
mssql|ms-|1.6.0
vsliveshare|ms-|1.0.181
material-icon-theme|PKi|3.7.0
ejs-language-support|Qas|0.0.1

</details>

**Comment by alexr00** [comment]
Thank you for the detailed bug! I have updated the grammars and pulled in the fix for this. It will be available in an insiders build soon.
