### ISSUE TITLE
VScode占用内存过高

### ISSUE THREAD

**Issue by Darrenfck** [microsoft/vscode#73752]
- VSCode Version:1.33.1
- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:

1.打开多个窗口
2.文件保存后，直接关掉编辑器
3.再次通过鼠标右键打开编辑器

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
1. Open multiple windows
2. After saving the file, close the editor directly
3. Open the editor again with the right mouse button
