### ISSUE TITLE
API to grab keystrokes before they are entered in editor

### ISSUE THREAD

**Issue by onolox** [microsoft/vscode#73753]
In VS Pro you can grab the keystrokes before they are entered in editor, this is useful to make changes in the behavior of them.

In my case I want to port my extension "Smart Semicolon", that is based in the function that exists in Eclipse IDE. 
When you press semicolon it is put in the end of line without changing the caret position.

If this API exists, sorry, but I have searched without finding a thing.

**Comment by jrieken** [comment]
Internally everything is command driven and the command is called `type`. So, if you register that and make it call `default:type` then you can intercept and trigger typing in the editor. You can take a look at the VIM extension that uses this. 

Alternatively, esp. as intercepting *all* typing is dangerous, you can register the `;` as keybinding to an arbitrary command
