### ISSUE TITLE
Warnings when triggering onTouchStart and onTouchMove events

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode#73750]
- VSCode Version: 1.34.20-insider
- OS Version: Linux 5.0.13

Steps to Reproduce:

1. Scroll using touch
2. Notice the following warnings being printed to the console `onTouchStart` and `onTouchMove`:
```
workbench.main.js:162 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
onTouchStart @ workbench.main.js:162
_register.s.addDisposableListener.e @ workbench.main.js:161
workbench.main.js:165 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
onTouchMove @ workbench.main.js:165
_register.s.addDisposableListener.e @ workbench.main.js:162
workbench.main.js:165 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
onTouchMove @ workbench.main.js:165
_register.s.addDisposableListener.e @ workbench.main.js:162
...
```

1. Zoom/pinch using touch
2. Notice lag and the following warning being printed:

```
[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```

Does this issue occur when all extensions are disabled?: Yes

I can also reproduce using the exploration build and Monaco on Chrome with the only difference being that they classify the warnings above as errors. I used https://microsoft.github.io/monaco-editor/playground.html to test Monaco. I've only tested this on Linux with a single device so I don't know if other operating systems or devices are affected.

Adding `touch-action: none` suppresses the warnings and removes the lag when trying to pinch the editor on VSCode. This blog post has more information: https://developers.google.com/web/updates/2017/01/scrolling-intervention. You can find the documentation for `touch-action` here: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action.

`touch-action: none` breaks panning and zooming gestures when using Monaco but since VSCode doesn't support those gestures in the first place it shouldn't be a problem. Monaco can also use `touch-action: manipulation` for Chrome to keep the gestures but I wouldn't recommend using it for VSCode since the pinch issues will still exist.

**Comment by alexdima** [comment]
Fixed via #91218
