### ISSUE TITLE
double click word highlight can't have the right selection highlight color.

### ISSUE THREAD

**Issue by likecreep** [microsoft/vscode#73754]
I configure the selection highlight background color should be white. But when I double click on the word to select it, the background color changes.
![image](https://user-images.githubusercontent.com/28685148/57743431-a0e6f100-76f7-11e9-94cf-172ce1045b5a.png)
![image](https://user-images.githubusercontent.com/28685148/57743435-a6443b80-76f7-11e9-93f4-09e12eb2293f.png)

**Comment by rebornix** [comment]
@likecreep can you share your custom setting for changing the background color of selection?
