### ISSUE TITLE
Can't Create a folder that has the same name as a file with no extension.

### ISSUE THREAD

**Issue by GeoffreyEmery** [Microsoft/vscode#7376]
- VSCode Version:
version 1.2.0
shell 0.47.6
- OS Version:Win 10

Steps to Reproduce:
In my use case i needed to move my dockefile to a folder called dockerfile for docker hub. When i treid this i get a error.  The issue i believe is that this file doesn't have a file type and it can't distinguish if its a folder or not. Probably failry big edge case and not a critical bug. 
1. Create a file with no extension. mine is called dockerfile
2. right click on the site and select add new folder
3. type in dockerfile
![image](https://cloud.githubusercontent.com/assets/3301804/15879296/b2c3d248-2cd7-11e6-8286-eab710bbbcf0.png)
![image](https://cloud.githubusercontent.com/assets/3301804/15879300/b6546a58-2cd7-11e6-9768-1e6f113f25bc.png)

**Comment by bpasero** [comment]
Do you run on a filesystem that allows to create a file and folder with the exact same name at the same location?

**Comment by GeoffreyEmery** [comment]
yes.. windows 10. Funny this doesn't occur on my mac which i created this zip on for you. I retested on windows machine again and it is still a issue. 
[vscode-test.zip](https://github.com/Microsoft/vscode/files/305063/vscode-test.zip)

**Comment by bpasero** [comment]
@GeoffreyEmery I am not able to create a file and folder with the same name using windows explorer so I wonder what you do different?

![screen shot 2016-06-08 at 17 11 32](https://cloud.githubusercontent.com/assets/900690/15899470/1b98b526-2d9c-11e6-9ed5-db88ab8cbd8d.png)

**Comment by GeoffreyEmery** [comment]
VIDEO OF BUG
[VSCODE-VIDEO.zip](https://github.com/Microsoft/vscode/files/305091/VSCODE-VIDEO.zip)

**Comment by GeoffreyEmery** [comment]
Hey,
  your doing it in explorer which is possible i did it in the ide as shown in video. once again this is very small bug.

**Comment by bpasero** [comment]
Ok, thanks for the video. We show this error because you are trying to create a file or folder that already exists. I am closing this because you cannot create a file or folder that already exists.

**Comment by GeoffreyEmery** [comment]
actually this is a bug with the IDE. you can create a file and folder with the same name in explorer as you showed in your own example. In my use case i was uploading my site to bitbucket and setting up a automatic build for a docker repo. The docker hub repo's require you to create a folder called dockerfile and then move your dockerfile inside of that instead of having in the root of the site as I did.

**Comment by bpasero** [comment]
@GeoffreyEmery my screenshot is showing that windows does not allow it. see the dialog in the screenshot that pops up.

**Comment by GeoffreyEmery** [comment]
Yes,
  close as resolved. This is a os issue. 
  Keep up the good work on the product. Its coming along very nicely.
G
