### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by nvnram** [microsoft/vscode#73764]
Issue Type: <b>Bug</b>

inside the terminal i cant use "ctrl+shift+c" to copy in ubuntu 18.04
but i can able use "ctrl+shift+v" to paste, if u resolve this might be helpful

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-29-generic

**Comment by Tyriar** [comment]
Works for me? Can you share your settings.json and keybindings.json files?

**Comment by nvnram** [comment]
Thanks for your help
verified keybinding.json  
i have installed "IntelliJ IDEA Keybindings",
it override the ctrl+shift+c, thats why copy didnt work .
