### ISSUE TITLE
Allow Disabling Updates for Individual Extensions

### ISSUE THREAD

**Issue by afrazkhan** [microsoft/vscode#73766]
Please make it possible to disable updates for individual extensions. There's a single extension I have to pin due to a bug in recent versions, which means I have to update _all_ extensions manually :P

Thanks!

**Comment by sandy081** [comment]
@afrazkhan You can install a version of an extension using the context menu on the installed extension. This will ignore automatic updates on that extension. Did you try that?

**Comment by afrazkhan** [comment]
@sandy081 Well this is odd. I was just replying to say how I had tried this and still updated after a restart of VSCode, when I thought to just double check it and try again — and it works as you described!

Might have been some combination of odd steps I was previously trying, but I can confirm that enabling auto updates, then downgrading an extension, keeps that downgraded version in that extension.
