### ISSUE TITLE
Automatically changing imports to a random named import when selecting from suggestion

### ISSUE THREAD

**Issue by purplecandy** [microsoft/vscode#73765]
- VSCode Version: 1.33.1 (user setup)
- OS Version: Windows 10 Home v1809 / Windows_NT x64 10.0.17763
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32

Steps to Reproduce:

1.  CtrL+Spacebar to show suggestion
2. Move selection it changes to prefix10.
3. Select a value adds a named import

Does this issue occur when all extensions are disabled?: Yes

It works fine for few minutes when the editor is restarted then it starts to happen.

I have attached a gif below please take look at it, it's hard to explain what it does

![editor gif](https://i.imgur.com/X64FZUR.gif)

**Comment by mjbvz** [comment]
Please file this against the dart extension
