### ISSUE TITLE
Expand PHP code with placeholders on tab press 

### ISSUE THREAD

**Issue by bmpf** [microsoft/vscode#73769]
I think my VSCode has a bug. When I press `tab` to expand code doesn't do anything as expected.

Example Problem: 
![Capturar](https://user-images.githubusercontent.com/33966960/57781558-5c247f80-7722-11e9-91c9-4add058d93e7.JPG)
Expected: 
![ex](https://user-images.githubusercontent.com/33966960/57781592-6cd4f580-7722-11e9-89f9-9b9bc9271737.JPG)

**Comment by sbatten** [comment]
this behavior is as designed. For the behavior you are looking for, the PHP extension would need to define a snippet.
