### ISSUE TITLE
Node.js unverified breakpoints when opening from a symbolically linked directory

### ISSUE THREAD

**Issue by Kh4n** [microsoft/vscode#73760]
Issue Type: <b>Bug</b>

1. Create a symlink using the `mklink` tool: https://www.techrepublic.com/article/how-to-take-advantage-of-symbolic-links-in-window-10/
The command I used was `mklink /D c:\Users\...\Documents E:\Documents`
You must use a soft link (`/D`) to reproduce
2. Open VSCode using the context right click (Shit+right click) and open the folder in the symlinked folder. 
3. Add a node project (`npm init`, add some code) and set a breakpoint. Now try running it. It will turn from solid red to a hollowed out grey circle while debugging is happening, making the debug impossible. Hovering the breakpoint will say "Unverified breakpoint set but not yet bound". Once the process is done "debugging" it will go back to solid red

(Temporary) solution:
Simply open the folder from the actual location in the file system instead. Everything works as it should

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|1.0.0
python|ms-|2019.4.12954
veriloghdl|msh|1.0.3

</details>

**Comment by roblourens** [comment]
Does it work if you add the options described here? https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks

**Comment by Kh4n** [comment]
That did not work. It appears that setting is for links created via `npm link` which serves an altogether different purpose. However, I did find that adding these settings in the `launch.json` made it work:

`"localRoot": "${workspaceRoot}",`
`"remoteRoot": "E:\\Documents\\STS",`

where `localRoot` just points to the symlinked folder (accessible via `workspaceRoot`) and `remoteRoot` points to the actual folder location on disk. Not sure if this is relevant, but the symlink is across drives, with the symlink on the SSD pointing to the actual location on the hard drive.

**Comment by roblourens** [comment]
Those settings are for any symlink. From what you describe, `"--preserve-symlinks-main"` should work, but using localRoot and remoteRoot is also a valid fix, I'm glad you found that.
