### ISSUE TITLE
Frequent crashing 

### ISSUE THREAD

**Issue by senthil-auxolabs** [microsoft/vscode#73762]
Issue Type: <b>Bug</b>

Unexpectedly VS Code is crashing and prompting to reopen. this is happening most often. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|7.92GB (1.33GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
html-slim-scss-css-class-completion|gen|1.5.14

(1 theme extensions excluded)

</details>

**Comment by mkhamat** [comment]
I think that's because of the WSL terminal. Or do you use cmd/powershell?

**Comment by mkhamat** [comment]
No. It just crashes every minute or two, I just open my file and wait. Then I got crash, reopen, and it crashes again.
