### ISSUE TITLE
Crash when opening a PowerShell file (*.ps1).

### ISSUE THREAD

**Issue by kefujino** [microsoft/vscode#73768]
Issue Type: <b>Bug</b>

After updating VSCode, I am facing to this behavior.

Repro steps 
-------------
・[File] - [Open file] -> select .ps1 file.
・[File] - [Save as] -> set .ps1 extension from .txt

VS code will crash.
![image](https://user-images.githubusercontent.com/13634805/57995212-e5113180-7afb-11e9-973f-a882251ea90f.png)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:09.080Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (23.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
sp-tools|Mik|0.3.0
vscode-language-pack-ja|MS-|1.33.2
csharp|ms-|1.19.1
powershell|ms-|1.12.1
python|tht|0.2.3

</details>

**Comment by sbatten** [comment]
@kefujino I am not facing this behavior, can you follow the steps for native crashes here and post back? https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by bpasero** [comment]
Also: Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kefujino** [comment]
@sbatten

Thank you for your comment and sorry for my late reply.
I tried to get crash dump and repro steps.
But, clash dump size was 400MB and could not be uploaded. 
So, I uploaded a text file of process.

[reprosteps.zip](https://github.com/microsoft/vscode/files/3195949/reprosteps.zip)
[Code__PID__12684__Date__05_20_2019__Time_10_32_53AM__976__Log.txt](https://github.com/microsoft/vscode/files/3195967/Code__PID__12684__Date__05_20_2019__Time_10_32_53AM__976__Log.txt)
s ID specified in Diagnostic tool.

Please let me know if there is any missing information

Thanks.

**Comment by kefujino** [comment]
@bpasero 
No repro in VSCode Insiders.
