### ISSUE TITLE
Package.json and jsonc (json with comment)

### ISSUE THREAD

**Issue by leoniDEV** [microsoft/vscode#73770]
Issue Type: <b>Bug</b>

When the file association for `.json` is set to `jsonc`, in `package.json` the suggestion for npm packages in `dependencies` and `devDependencies` stop to work

VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.18895

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.03GB free)|
|Process Argv|--extensions-dir=D:\ProgramData\Dev\VSCode-Insider\extensions|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.4
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.7.4
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
vscode-solution-explorer|fer|0.3.4
vscode-npm|fkn|3.3.0
dotnet-test-explorer|for|0.7.0
vscode-pull-request-github|Git|0.6.0
todo-tree|Gru|0.0.132
webpack|jer|2.1.3
docthis|joe|0.7.1
chat|kar|0.15.4
dotnet-core-essentials|Kis|0.0.6
azure-pipelines|ms-|1.152.0
vscode-language-pack-it|MS-|1.34.2
mssql|ms-|1.6.0
csharp|ms-|1.19.1
powershell|ms-|1.12.1
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.181
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.2.12
team|ms-|1.149.2
debugger-for-edge|msj|1.0.9
quicktype|qui|12.0.46
vscode-xml|red|0.5.1
LiveServer|rit|5.6.1
stylelint|shi|0.49.0
sonarlint-vscode|Son|1.6.0
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.6.0

</details>

**Comment by aeschli** [comment]
npm `package.json` does not allow comments, so setting the language to `jsonc` seems wrong to me.
I'd rather not change the current behaviour.
