### ISSUE TITLE
How to run memory profiling for an extension?

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#73773]
This was sort-of requested in #54818 but it was closed with instructions that only seem to cover CPU.

I've had a CPU profile sent to me that showed quite a few long GC pauses:

![Screenshot 2019-05-14 at 11 52 29 am](https://user-images.githubusercontent.com/1078012/57692538-eabfd080-763e-11e9-85e1-d67115a0a95a.png)

I'm unable to reproduce this (the user has very low available RAM which I suspect might not be helping), but I'd be interested in profiling the memory usage for this code to see if there's anything bad going on (or easy wins). I can't find a way to do anything except get CPU profiles though. Is it possible?

**Comment by jrieken** [comment]
Start with `--inspect-extensions <port>`, attach chrome dev tools (as for node.js), and use the mem-profiling tools

**Comment by DanTup** [comment]
Aha, that works :) I thought the `--inspect-extensions` thing was old, since where it's mentioned in the docs (for capturing an extension host CPU profile) it doesn't seem to be required - the profile works without it.

Thanks!
