### ISSUE TITLE
Add a Windows Explorer Preview Handler for associated file types

### ISSUE THREAD

**Issue by zspitzer** [microsoft/vscode#73771]
Currently you can't preview vs-code associated file types in Windows Explorer's Preview pane, it just says no preview available.

https://docs.microsoft.com/en-us/windows/desktop/shell/preview-handlers

**Comment by sbatten** [comment]
@deepak1556 does electron support this?

**Comment by deepak1556** [comment]
@sbatten its not supported at the moment, but seems like something we could add via a node native module.

**Comment by geekley** [comment]
Having a simple text preview like notepad would already help a lot. It just needs to properly handle encoding and line endings. I won't even ask for syntax highlighting, etc.

Although I think that formatted Markdown preview would be a nice thing to have.

**Comment by stamminator** [comment]
Any ideas one how it can be optimized for performance? The vscode instance it launches for the preview should be lightweight as possible while supporting particular extensions, such as syntax highlighting for additional languages. Perhaps all extensions should be disabled in preview mode by default, with a setting allowing the user to specify extensions to be enabled in preview mode?

**Comment by geekley** [comment]
> Any ideas on how it can be optimized for performance?

Well, complete *syntax* highlighting would be overkill for me, so if it's done, it should be limited to lexicon (token-only) highlighting (typically doable with just regex). As long as it's done properly, of course. I've seen some sites do this poorly, with things like highlighting keywords inside strings or comment blocks.

> Perhaps all extensions should be disabled in preview mode by default, with a setting allowing the user to specify extensions to be enabled in preview mode?

I like this idea.

Also, there should be a way to disable the feature for specific file types, to use the external preview.

---

If you go for the full, ideal implementation, previews should let you switch between views as applicable:
1. Text view, with at least:
    - encoding auto-detected
    - line wrapping
    - ability to copy text
    - tab size selection (by default the user setting)
    - line numbers
    - lexicon highlighting?
    - search feature?
    - use theme?
2. Structure view, mostly for types like JSON, XML, HTML, YAML - essentially the outline (tree) view.
3. Rendered view, for types like SVG, Markdown, HTML.

**Comment by iyerusad** [comment]
This presumably could enable VS Code as a previewer within Outlook as well?

Seemingly most recent updated previewer for any code is one from 2006/2010, that has long since been abandoned since CodePlex days:
https://archive.codeplex.com/?p=previewhandlers

**Comment by iyerusad** [comment]
If this ever gets picked up, would be nice to have following option:
- Format/Beautify (and button to revert back to original)
  - Selectable language if not enough context.

Use case in particular when receiving JSON/XML file in email, would love to be able to preview them within Outlook.
