### ISSUE TITLE
Stale Powershell Scripts in Debugger

### ISSUE THREAD

**Issue by sean-sel** [microsoft/vscode#73779]
Issue Type: <b>Bug</b>

Frequently, when I go to Debug powershell scripts it is debugging against a version before my last changes.
The breakpoints and error messages don't match what is displayed but match a version before my most recent changes.
I have to regulary relaunch Visual Studio Code to refresh the debugger to run the code that I see.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (12.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|1.12.1

</details>

**Comment by isidorn** [comment]
Please file against powershell extension. Thank you
