### ISSUE TITLE
Reset file dialog working directory when clearing history

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#73774]
Issue Type: <b>Bug</b>

I don't know why when I try to open a file by clicking File->Open File, VScode always shows me the files in a specific folder:

1) type "code" in a linux terminal and clike enter key;
2) select file->open file from the menu.

I have tried to clean recent openned files, editor history etc. but it doesn't help.

I also tried to clean install VScode by removing folder "~/.vscode" and "~/.config/code" first, and this doesn't help either.

Why does VScode remember that folder? Is there any other folders or files I should clear?

This happens with both stable and insider version of VScode.

VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:32:52.030Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|187.41GB (11.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.23.1

</details>

**Comment by sweettyler** [comment]
I found there is also a hidden folder, ".vscode" in the folder that is always being shown in the open file menu, and it is readable only. Removing this ".vscode" folder seems to cure the problem.

The only remain question is: how does vscode know there are other ".vscode" folders in the file system tree?

**Comment by bpasero** [comment]
@sweettyler I do not understand the issue here, can you record a video to show and explain better?

**Comment by sweettyler** [comment]
Sorry for the confusing. Let me start over again in another way:

1) suppose I already has a folder named "folder_A" in mu home directory, and in "folder_A" I have a file named "file1.cc";
2) lauch vscode and open "file1.cc" in "~/folder_A" by clicking from menu File-Open file->Home->folder_A->file1.cc, and finally clicking "open" botton. "file1.cc" is loaded in one of my vscode tabs .
3) close all tabs and press "ctrl+shift+P" and then choose " clear recent history" and "clear editor history".
4) exit vscode.
5) launch vscode again and click from menu File-"Open file" and I'll see the content of "folder_A" is already shown on the right of the file picker window.

Not sure if this is clear. Please let me know.

Thanks.

**Comment by sweettyler** [comment]
I think in ./Code - Insiders/storage.json, the value of "pickerWorkingDir" is not cleared as expected.

**Comment by bpasero** [comment]
@sweettyler so you would like an option that the file dialog that opens does not open at a specific folder from last time? And if so, which folder should it pick then?

**Comment by sweettyler** [comment]
my point is, the folder I opened last time is part of my "opened file" history. If I decide to clear the history then it should be cleared as well.

I think vscode starting from where it is launched (if it is launched from a terminal)  or from user's home directory (in other cases) may be an idea, though I am not sure.

**Comment by sweettyler** [comment]
@bpasero actually I am not requesting for a new feature and I would rather not have one that resets "file dialog working directory when clearing history" because the logic isn't right.

As for your question, "...which folder should it pick then?". Iet me ask you a question: if this is the FIRST time I install vscode on my computer, when I launch it for the FIRST time, where does the file picker point to? That location / folder should also be where it points to after I clean my "opened file" history. This is exactly what "sublime text 3" does and I personally think this is right.

Thank you.

**Comment by bpasero** [comment]
@sweettyler if you start first time it is really the OS that decides on the directory to show, possibly the last one you used in any other program or a default one the OS picks. I think the summary of this issue now reflects the intent.

**Comment by sweettyler** [comment]
Yes. I think what are decided by the OS are the right things to display. I am not sure what they are in MacOS and Windows, but in Linux (CentOS 7.4) that's exactly what I see in vscode (and also in sublime text 3 linux version) when I press "ctrl+O" and then click the "recent" button on the top left corner.

Anyway, it's not a big deal whatsoever.

Thanks again for your time.

**Comment by sweettyler** [comment]
Not a feature request.
