### ISSUE TITLE
Option to minimise the terminal

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [microsoft/vscode#73772]
Since the Windows terminal doesn't remember the history, once it is closed, one would like to minimise it using a button so that we can have more space. Currently the option is only to drag it to minimise.

**Comment by gjsjohnmurray** [comment]
What do you mean by "doesn't remember the history"? If I launch a Terminal (`Ctrl+'`), enter a command (e.g. `date`), then close the panel using the [X] in the upper right corner, next time I open it (`Ctrl+'` again) I still see my previous command and its output.

**Comment by vijayaraghavanramanan** [comment]
I don't see it on my Windows 8.1!

**Comment by gjsjohnmurray** [comment]
Here's a recording of mine (Windows 10):
![junk](https://user-images.githubusercontent.com/6726799/57792903-01961e00-7738-11e9-9a24-56e8647aa77e.gif)

**Comment by vijayaraghavanramanan** [comment]
Yes, that's because it's a Powershell as it says.

**Comment by gjsjohnmurray** [comment]
I get the same persistence with cmd (no animation this time, so take my word for it):
![image](https://user-images.githubusercontent.com/6726799/57793918-5cc91000-773a-11e9-879f-ca67017a637b.png)

**Comment by vijayaraghavanramanan** [comment]
Not on my Windows 8.1. I checked with stackoverflow (not specifically for VS Code but generally) and everyone seems to think that cmd doesn't remember history for Windows 8.1 and recommend the powershell.

**Comment by Tyriar** [comment]
The `x` button closes the panel, it does not kill the terminal.  Hitting that is essentially the same thing as dragging the panel down to the bottom to minimise is.

**Comment by vijayaraghavanramanan** [comment]
It's not exactly that as opening again ends up opening two. Or is there a trick to bring it back without opening "2:cmd"

**Comment by Tyriar** [comment]
By default ctrl+` will _toggle_ the terminal and will not create new ones, ctrl+shift+` will create a new terminal, maybe you're doing the latter?

**Comment by vijayaraghavanramanan** [comment]
No button then?

**Comment by Tyriar** [comment]
> The x button closes the panel

**Comment by vijayaraghavanramanan** [comment]
Thanks for confirming that there's no button. 

The x button closes the panel but you need a **button** to open it again. Which is not there at the moment. I mean why have anything if everything can be done using shortcuts?

**Comment by Tyriar** [comment]
We explored exposing the panel buttons in the activity bar but ended up against it. It would be trivial to write an extension that toggles the terminal if you really want this. Similar to https://github.com/Tyriar/vscode-terminal-tabs but you would just want the button to trigger the `workbench.action.terminal.toggleTerminal` command

**Comment by gjsjohnmurray** [comment]
Or click here
![image](https://user-images.githubusercontent.com/6726799/57829862-3f328f80-77a8-11e9-9cc6-ea5c52049e6d.png)
to open the panel on its Problems tab, then click on the Terminal tab.
