### ISSUE TITLE
Linux integrated terminal mouse-wheel scrolling problems

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#7377]
- VSCode Version: 1.2.0
- OS Version: Ubuntu Xenial - .deb install

Steps to Reproduce:

1. Open the integrated terminal
2. Do something that overpopulates the window with a lot of output (ie, 'make', or a long 'ls')
3. Try and scroll using the mouse wheel

In windows, the terminal scrolls smoothly as expected.
On linux, the terminal scrolling is very jerky, unresponsive, and occasionally it scrolls horizontally instead of vertically, and the terminal display gets stuck scrolled to the right with the left-hand text cut off/not-visible.

Expect: Scrolling the terminal on linux should be smooth, and work properly.

**Comment by Tyriar** [comment]
If possible could you capture a gif? I've never seen any issues like that on Xenial.

**Comment by TurkeyMan** [comment]
Ummmm, yeah, I'll see if I can find the time. We're pedal-to-the-metal at the moment! >_<

**Comment by riula** [comment]
Encountering something similar myself on OSX 10.11.4

Using two fingers to scroll after doing a "git status" (or anything else that overpopulates the window), terminal will scroll up and quickly stop. Literally just noticed that when the mouse isn't over any content in the terminal scrolling won't work. The moment I move my cursor over some content scrolling works fine. 

Expect: Scrolling to be smooth and consistent regardless of what part of the terminal my cursor is over.

**Comment by Tyriar** [comment]
@riula that issue is https://github.com/Microsoft/vscode/issues/6743 and I believe it's already fixed on master.

**Comment by TurkeyMan** [comment]
That may very well be the problem I was experiencing... except the horizontal scrolling was weird too.

**Comment by riula** [comment]
Thanks @Tyriar, thats great to hear!

I have experienced the horizontal scrolling issue that @TurkeyMan is reporting. Gets stuck and can't see the left hand site without closing and reopening the terminal.

**Comment by Tyriar** [comment]
@TurkeyMan I think this may be fixed when we switched to xterm.js, if you manage to repro in insiders please comment/reopen.

**Comment by aeschli** [comment]
Seem to work for me in Version 1.7.0-insider, Elementary OS, Freya
