### ISSUE TITLE
About snippets: perfix can't begin with "="

### ISSUE THREAD

**Issue by jackey79** [microsoft/vscode#73777]
Hi, if my perfix is `!=`, it doesn't work.
Are there any rules of setting perfix? 
![image](https://user-images.githubusercontent.com/50488600/57790172-c95d0280-776c-11e9-9ccc-660aed2aa593.png)

**Comment by jrieken** [comment]
Please provide the snippet in source. Also, in what language should this work and how did you try this?

**Comment by jackey79** [comment]
It's a user snippet which I defined by myself. I hope it works in **latex**. But actually, it doesn't.
![image](https://user-images.githubusercontent.com/50488600/57895489-812e0500-787e-11e9-8c06-517678f7fc33.png)
And if I add an `@` before the `!=`, it works.
![image](https://user-images.githubusercontent.com/50488600/57896066-74f77700-7881-11e9-9de2-267225c21db9.png)
Are there any difference between latex and other languages in snippet? 
PS: Thanks for your comment.

**Comment by jrieken** [comment]
> Are there any difference between latex and other languages in snippet?

Yes - each language defines (via a regex) what a word is and IntelliSense "as you type" only happens when typing at the end of words. That's why you see the snippet when pressing Cmd+Space but not as you type. That's done on purpose because otherwise IntelliSense would happen too often.
