### ISSUE TITLE
Add gutter icons for classes and members navigation

### ISSUE THREAD

**Issue by sestegra** [microsoft/vscode#73784]
In order to navigate into class hierarchy, it would be nice to have gutter icons at the beginning of a line that contains for instance:
- inherited classes (click goes to go parent class)
- overridden members (click goes to go parent member)
...

As an example, see what IntelliJ is doing for Dart language
![image](https://user-images.githubusercontent.com/109060/57799168-b804fd80-774e-11e9-8483-89cfb5f6caaa.png)

One option would be to add behaviours (on hover, on click...) in gutter icons from DecorationRenderOptions.

**Comment by rebornix** [comment]
cc @jrieken it sounds like another use case of breadcrumb.

**Comment by jrieken** [comment]
Yeah, the outline/breadcrumb information could be sufficient here

**Comment by zeljkoantich** [comment]
I would like to see gutter icons in vscode.
But after reading this, I see that I must switch to IntelliJ.

**Comment by mitar** [comment]
There is no extension providing this?

**Comment by escamoteur** [comment]
> Yeah, the outline/breadcrumb information could be sufficient here

pretty sad that his proposal was shot so quick down because it's far from being solved by breadcrumbs

**Comment by rodolvbg** [comment]
How can we reopen this issue? I would like use vscode instead Jetbrains
