### ISSUE TITLE
Pin task in the npm script explorer

### ISSUE THREAD

**Issue by michaeljota** [microsoft/vscode#73786]
Currently, in the npm script explorer, a section is created for every package.json. This is great, as we can search for all the npm scripts we have in all the modules. It's even better when using the workspace feature, as it would separate the sections in a project basis. 

But, as you have many modules, sometimes is hard to navigate between the packages, and the sections, and the projects. 

It would be nice to be able to pin some scripts, for them to always appears in the top of the script explorer.

**Comment by egamma** [comment]
@michaeljota as a workaround you can quickly find a particular task in the quick pick dialog shown by `Terminal>Run Task...`
