### ISSUE TITLE
Spurious output on console that launched VSCode

### ISSUE THREAD

**Issue by NielsFerguson** [microsoft/vscode#73789]
Issue Type: <b>Bug</b>

I just launched VSCode through a file association for .cs files. Below is what my console now looks like. I'd expect that VSCode just launches without polluting my console. (And I've seen these type of messages show up later in the same console window when I'm doing other work; most disconcerting.)

```
s:\os\src\symcrypt>scbuild\scbuild.cs

s:\os\src\symcrypt>
[main 2019-05-15T19:59:14.825Z] update#setState idle
[main 2019-05-15T19:59:44.840Z] update#setState checking for updates
[main 2019-05-15T19:59:44.907Z] update#setState 
```

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18898

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (22.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.23.1
csharp|ms-|1.19.1

</details>

**Comment by msftrncs** [comment]
This does not seem to happen if `code.cmd` is used instead.

```
code.cmd scbuild.cs
```

I'm only mentioning this work around, as it may help direct to where the problem is.

I think the problem is that the handler that VS Code sets up uses `code.exe` instead of using the same command set that code.cmd uses, and I think this was because the possibility of using the handlers from a console was not considered.  The script appears to be specifically set up to handle the situation of preventing the output to the console.

**Comment by Tyriar** [comment]
@joaomoreno is this a CLI issue? I'm not sure what default files are calling into.

**Comment by joaomoreno** [comment]
@NielsFerguson Can you associate with `code.cmd` instead of `Code.exe`?

**Comment by NielsFerguson** [comment]
I thought this was going trough the ‘ASSOC’ command on CMD.EXE, but that doesn’t have a mapping for .C files at all. The “Choose default apps by file type” page in Settings.exe does list the mapping of .C files to Visual Studio Code, but it isn’t clear how I can change the details of the association. The drop-down box only lists the apps as tiles.

So how do you want me to change the association? In general it is not a good idea to directly change the registry without knowing the details of what you are doing. And I can see the following in regedit:

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.c\OpenWithList]
"a"="Code.exe"
"b"="devenv.exe"
"c"="abc"
"d"="abcd"
"e"="abcde"
"f"="abcdef"
"g"="abcdefg"
"h"="abcdefgh"
"i"="abcdefghi"
"j"="abcdefghij"
"k"="abcdefghijk"
"l"="a"
"m"="a"
"n"="a"
"o"="a"
"p"="a"
"q"="a"
"r"="a"
"s"="a"
"t"="abcdefghijklmnopqrst"
"u"="a"
"v"="abcdefghijklmnopqrstuv"
"w"="a"
"x"="abcdefghijklmnopqrstuvwx"
"MRUList"="a"
"y"="abcdefghijklmnopqrstuvwxy"

Which seems to indicate that “code.exe” and “devenv.exe” are associated with .C files, but what are all the other entries? It looks like significant pollution of the registry.

Cheers!

Niels

**Comment by msftrncs** [comment]
@NielsFerguson, I think you might be looking at the wrong registry entries.   For a user install, this is probably where to go:

`HKEY_CURRENT_USER\Software\Classes\.c\OpenWithProgids`

which points to

`HKEY_CURRENT_USER\Software\Classes\VSCode.c\shell\open\command`

It appears as if the `ASSOC` command only sees system wide associations, which also means it should only work from an elevated prompt, but I didn't try changing anything with it myself.

**Comment by NielsFerguson** [comment]
So in my registry I have

[HKEY_CURRENT_USER\SOFTWARE\Classes\.c\OpenWithProgids]
"VSCode.c"=""
"VisualStudio.c.706dfbdf"=""

Except that regedit shows them in the reverse order. But values within a key are unordered. I don’t know why the VisualStudio.c.706dfbdf entry would not be used.

I changed the Software/Classes/VSCode.cshell/open/command entry to point to the bin/code.cmd file. I don’t get the extra text on my console window all the time, but I do get an additional newline. With this change the newline does not appear when I launch on a .C file, but it does appear when I launch on a .H file, so the fix is working.

But I don’t understand why you would ever have any output to STDOUT or STDERR. VSCode is a windowed program and it should NEVER have console output. Even more baffling is that this is a know problem, and instead of not using STDOUT/STDERR the developer added a CMD file and a CLI.JS file to fix this problem but only in certain situations. And then the installer doesn’t know about this and points to the EXE file creating this bug.

Cheers!

Niels

**Comment by msftrncs** [comment]
VS Code really isn't an application in the conventional sense.  The file Code.EXE is actually an interpreter for the scripts that make up VS Code.  This is significantly different than a natively compiled C++ application.   The CLI kludge you mention is actually a work-around for a feature that is not desired here, that comes from Electron, the interpreter/graphical interface, which is effectively just a web browser.

I might be concerned that using Code.CMD would potentially cause a console window to briefly flash on the screen when opening files via the association.

**Comment by NielsFerguson** [comment]
Be that as it may, there is no reason for Code.EXE to print to stdout/stderr when launched from the command line. The file associations are set up by VSCode to begin with, and they simply don't work properly. There are many ways to fix this. The CMD hack is ugly and as you point out might flash a console window. Or you could add a command line option that closes Stdout/Stderr before running the rest of the code. Or you could remove the locations where the data is printed.

**Comment by msftrncs** [comment]
Technically code.exe contains console functionality and so must be able to output to a console,  however once it has formed a window interface it probably shouldn't.   Also all Electron apps I have seen use the same hack when they anticipate they'll be used from a console, which is quite regularly in 'nix environments. 

On May 30, 2019 4:58:05 AM GMT+09:00, Niels Ferguson <notifications@github.com> wrote:
>Be that as it may, there is no reason for Code.EXE to print to
>stdout/stderr when launched from the command line. The file
>associations are set up by VSCode to begin with, and they simply don't
>work properly. There are many ways to fix this. The CMD hack is ugly
>and as you point out might flash a console window. Or you could add a
>command line option that closes Stdout/Stderr before running the rest
>of the code. Or you could remove the locations where the data is
>printed.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/microsoft/vscode/issues/73789#issuecomment-497086093

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by pcolmer** [comment]
I've just started seeing this when launching `code-insiders` from WSL. Before today's update, running `code-insiders .` would launch VS Code **and return to the command prompt**. Now, the WSL console displays a couple of messages from "update#setState" but doesn't return to the command prompt until I quit VS Code.

**Comment by Tyriar** [comment]
@deepak1556 I think this is Electron attaching to the console when we don't want it to, do you know how we can disable this? Or are we setting `ELECTRON_ENABLE_LOGGING` when we shouldn't be?

**Comment by joaomoreno** [comment]
No, this is the same I mentioned before: check your `PATH` variable. The part related to Code should end in `\bin`.

**Comment by pcolmer** [comment]
@joaomoreno Nothing has changed at my end with regards to the path. This is either a VS Code or WSL Remote update issue, I think. It has only started happening for me over the last couple of days with Code Insider. If I use Code instead, it works normally, confirming that `PATH` does not seem to be the factor here.

**Comment by joaomoreno** [comment]
Can you show me the `PATH` variable from within WSL, where you invoke `code-insiders`?

**Comment by pcolmer** [comment]
```
PATH=/home/philip/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Docker/Docker/Resources/bin:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/c/WINDOWS/System32/OpenSSH/:/c/Program Files (x86)/PuTTY/:/c/Program Files/dotnet/:/c/Program Files/Git/cmd:/c/Users/phili/AppData/Local/Microsoft/WindowsApps:/c/Users/phili/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/phili/AppData/Local/Programs/Python/Python37-32:/c/Users/phili/AppData/Local/Programs/Python/Python37-32/Scripts:/c/Users/phili/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/snap/bin
```
```
philip@DESKTOP-HU2D28P:~$ which code-insiders
/c/Users/phili/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders
philip@DESKTOP-HU2D28P:~$ which code
/c/Users/phili/AppData/Local/Programs/Microsoft VS Code/bin/code
```

**Comment by joaomoreno** [comment]
@aeschli Have you see this on WSL?

**Comment by pcolmer** [comment]
In case it helps, a related issue is https://github.com/microsoft/vscode-remote-release/issues/1369.

**Comment by pcolmer** [comment]
@joaomoreno It looks like @aeschli has fixed this.

Thank you all.
