### ISSUE TITLE
Peek at search result

### ISSUE THREAD

**Issue by ThomasKagan** [microsoft/vscode#73796]
When you click on a search result from the "Search" sidebar, it navigates your currently active editor to that result. That's fine if I was intending to completely change contexts, but in some cases, I don't want to do this, like if I just want to reference a function implementation. So in those cases, it would be nice to be able to peek at the search result or easily open it in a split editor pane.

Thanks for reading

**Comment by roblourens** [comment]
You can cmd+click to open the result to the side (ctrl+click on windows) does that help?

**Comment by ThomasKagan** [comment]
Yeah, that's fine

**Comment by roblourens** [comment]
> When I I do this, sometimes it opens a new editor to the side twice

I think this was fixed in 1.34, can you make sure you are updated?

**Comment by ThomasKagan** [comment]
Ah! That's it, thanks for the suggestion.
