### ISSUE TITLE
Support Visual Studio's 'Concord' debug engine in windows?

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#7379]
- VSCode Version: 1.2.0
- OS Version: Windows

Feature Request:

Please support Visual Studio's Concord debug engine? Using GDB to debug local windows apps is pretty awkward. I think everyone agrees; Visual Studio has the best debugger in the world, and it's available to everyone via the free community edition.

**Comment by edumunoz** [comment]
Thanks for the suggestion, @TurkeyMan. I see you also created this feature request in the C/C++ extension repo https://github.com/Microsoft/vscppsamples/issues/66.

This feature request should not be in the vscode repo, so moving the discussion over there.

**Comment by TurkeyMan** [comment]
Yup, I realised I put this in the wrong place. Sorry for the noise!
