### ISSUE TITLE
Performance degrades over time

### ISSUE THREAD

**Issue by shadymoses** [microsoft/vscode#73797]
Issue Type: <b>Performance Issue</b>

After time, performance degrades and linter/intellisense/prettier features stop working. I suspect this is due to some plugin, but I have no idea which one would cause the problem or if it's something.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    98	 76014	code main
    0	    49	 76016	   gpu-process
    0	   295	 76017	   window (ExpenseWizard.jsx — zb-ui-base)
    1	   180	 76031	     extensionHost
    0	   442	 76034	       electron_node tsserver.js 
    0	    66	 76040	         electron_node typingsInstaller.js typesMap.js 
    0	    82	 76036	       electron_node eslintServer.js 
    0	    49	 76255	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=76031
    0	    49	 76032	     watcherService
    0	    49	 76049	     searchService
    0	   115	 76038	   shared-process
    0	    82	 77430	   window (Issue Reporter)
    0	     0	 77450	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
vscode-multi-line-tricks|big|0.0.3
vscode-toggle-quotes|Bri|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
gitlens|eam|9.7.4
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
todo-tree|Gru|0.0.132
vscode-styled-components|jpo|0.0.26
vscode-language-babel|mgm|0.0.22
atom-keybindings|ms-|3.0.6
vsliveshare|ms-|1.0.182
color-highlight|nau|2.3.0
vscode-react-refactor|pla|1.0.4
code-settings-sync|Sha|3.2.9
mdx|sil|0.1.0
indenticator|Sir|0.6.0
vscode-status-bar-format-toggle|tom|1.5.0
vscode-icons|vsc|8.6.0
joinlines|web|1.1.1
change-case|wma|1.0.0
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
My guess is either bracket-pair-colorizer or auto-close/rename-tag.
