### ISSUE TITLE
Search Results are cleared after clicking on "Toggle Search View Position"

### ISSUE THREAD

**Issue by skprabhanjan** [microsoft/vscode#73809]
@roblourens , When we click on the "Toggle Search View Position" the search results are cleared and we need to search again after the position was toggled.
I stumbled upon this when I was trying to implement #73465 .
So I can take a look at this if you feel this should not happen and it is supposed to be fixed.
Thanks :) 

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is basically https://github.com/microsoft/vscode/issues/44491, and it's not easy, thanks though
