### ISSUE TITLE
Having many file path in terminal output consumes a lot of memory

### ISSUE THREAD

**Issue by fcrick** [microsoft/vscode#73802]
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open VSCode and open new terminal that uses Git bash
2. Run the command on the next line, and give it a minute or two:

`powershell 'dir c: -Directory -Recurse | foreach { $_.FullName }' | while IFS="" read -r p || [ -n "$p" ]; do   printf '%s\n' "$p"; sleep .25; done`

Does this issue occur when all extensions are disabled?: Yes - still occurs

After 2-3 minutes, vs code will be using tons of ram and cpu, and get really sluggish.
![image](https://user-images.githubusercontent.com/283047/57817799-ee824e80-7735-11e9-979c-27981a31a940.png)

**Comment by fcrick** [comment]
Note that as this is only printing 4 paths a second, after 3 minutes, that's only 720 paths in terminal output, and yet vscode is using half my cpu and more than a gig of ram - more than a megabyte per path printed.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

---

I tried to repro this and couldn't, I suspect that's happening is a bunch of redundant data is getting added to the text stream and maybe the terminal can't keep up. If so then this one should fix it https://github.com/xtermjs/xterm.js/issues/2077
