### ISSUE TITLE
Please implement block (scope) highlighting

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#73800]
Issue Type: <b>Feature Request</b>

Highlight the current (potentially nested) scope/block, similar to Qt Creator (the screenshot below) and XCode.

![block highlighting](https://user-images.githubusercontent.com/13824553/57816689-1fac5000-7731-11e9-9b15-28677e7df740.PNG)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

**Comment by gjsjohnmurray** [comment]
@tlemo did you see #19690?

**Comment by tlemo** [comment]
Thanks for the pointer @gjsjohnmurray. I assume you're referring to #4 in that list? It's not clear to me if it's the same thing (could be, although the description and screenshots don't seem very specific around the block highlighting part)

At any rate, the block highlighting is not strictly related to folding and I think it's better to track it on its own.

**Comment by anatolyburakov** [comment]
+1 for this, i've gotten used to this in Qt Creator, and i think it's a great feature. There is an extension that kinda-sorta does this, but it is far from being as elegant looking as what Qt Creator has (see OP's screenshot).

**Comment by tlemo** [comment]
I agree that this functionality would be a good candidate for an extension, the question is: does VS Code allow arbitrary decorations, ex. the changing the color of a sub-region of the editor pane? (this would be required to allow an extension to implement block/scope highlighting)

The few extensions which attempt to implement this are limited in that they can only highlight the text and/or the full line background:
https://marketplace.visualstudio.com/items?itemName=byi8220.indented-block-highlighting
https://marketplace.visualstudio.com/items?itemName=imagio.vscode-dimmer-block

Also, while I like the extensibility model, one can argue that the scope highlighting is such a core functionality that it would make sense to implement it in VS Code proper. After all, this is the case for block folding and indent guides.
