### ISSUE TITLE
SSL Error on Update behind company proxy

### ISSUE THREAD

**Issue by thibaultdelor** [microsoft/vscode#73806]
- VSCode Version: Version 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8) 
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

1. Be behind a "man in the middle" company proxy (which rewrite SSL certs)
2. Open VsCode
3. "Check for updates..."
4. Update fail and the following message appears
![error](https://user-images.githubusercontent.com/693797/57823338-6dc95e00-77da-11e9-8937-c437b5905d57.png)

Does this issue occur when all extensions are disabled?: Yes

VSCode is launched using:
`code --verbose --log trace --ignore-certificate-errors --disable-extensions`

User Config contains:
```json
{
    "http.proxyStrictSSL": false,
    "http.proxy": "http://127.0.0.1:3128/",
} 
```
(Proxy points to my cntlm proxy which then proxy to our company proxy with correct authentication.)

Relevant message in the vscode logs:
```
[main 2019-05-16T02:54:21.543Z] update#checkForUpdates, state =  idle
[main 2019-05-16T02:54:21.543Z] update#setState checking for updates
[main 2019-05-16T02:54:21.752Z] menubarService#updateMenubar 1
2019-05-16 12:54:22.689 Electron[34392:1657898] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
[main 2019-05-16T02:54:22.691Z] UpdateService error: An SSL error has occurred and a secure connection to the server cannot be made. Would you like to connect to the server anyway?
[main 2019-05-16T02:54:22.691Z] update#setState idle
[34392:0516/125422.692725:INFO:CONSOLE(2370)] "An SSL error has occurred and a secure connection to the server cannot be made. Would you like to connect to the server anyway?", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (2370)
```

I can make it temporarily work by adding the following lines to `/Applications/Visual Studio Code.app/Contents/Info.plist`:
```xml
<key>NSAppTransportSecurity</key>
<dict><key>NSAllowsArbitraryLoads</key><true/></dict>
```

Sadly, VsCode overwrite this file quite frequently (not sure when exactly) and the fix seems to do the trick only for a one off update.

**Comment by joaomoreno** [comment]
What about with `--ignore-certificate-errors`?

https://code.visualstudio.com/docs/setup/network

**Comment by thibaultdelor** [comment]
@joaomoreno s mentionned in the ticket I already use this option and it is not solving the issue

**Comment by joaomoreno** [comment]
Odd... Not really sure what goes on here.

**Comment by thibaultdelor** [comment]
@joaomoreno I couldn't find anywhere in the code of VSCode a reference to `--ignore-certificate-errors`. Is it a Microsoft specific argument (I mean one which doesn't appear in the OSS) ?

If that's the case then I'll suggest bringing this parameter to the OSS version and use to configure the electron auto updater. I can do the PR, please just confirm my thought and whether you see it as an acceptable solution.

**Comment by thibaultdelor** [comment]
My other theory is that command line argument of vscode are forwarded to electron (`--ignore-certificate-errors` being an electron option) but in that case I can't find the piece of code doing the forwarding...

**Comment by thibaultdelor** [comment]
I ended up thinking it's actually a bug with electron itself.

I keep investigating, please let this issue open, I'll give updates here.

**Comment by joaomoreno** [comment]
`ignore-certificate-errors` is a Chromium (Electron) specific setting.

It's possible that Squirrel (auto updating framework on macOS) uses some other stack to download... Can you provide a link to the upstream Electron issue?

**Comment by MarshallOfSound** [comment]
> It's possible that Squirrel (auto updating framework on macOS) uses some other stack to download

This is correct 👍 Squirrel.Mac uses `NSURLRequest` directly --> https://github.com/Squirrel/Squirrel.Mac/blob/cb838776ce22bcbf41def7b9a1352f24120bab29/Squirrel/SQRLUpdater.m#L202-L217

**Comment by thibaultdelor** [comment]
@MarshallOfSound Can you advise on the way forward? Do you think that should be handled by electron or somewhere else? 

I am happy to work on a PR on any of those repo, I am just not sure what is the right way to do it.

**Comment by MarshallOfSound** [comment]
@thibaultdelor Unless I'm missing something it sounds like your proxy or machine is mis-configured.  If your proxy is rewriting SSL certs then the SSL cert that your proxy uses needs to be trusted by your machine.  The answer should never be "disable SSL" because that's how you get pwned.

This matches VS Codes documentation:

> Since Chromium simply uses the OS's certificate trust infrastructure, the preferred option is to add your proxy's certificate to your OS's trust chain. Click here to read more about the Root Certificate Policy in Chromium.

Along with `--ignore-certificate-errors`:

> Warning: This is dangerous and not recommended, since it opens the door to security issues.

The _correct_ solution here if for your proxy to be configured / trusted correctly by your OS 👍

**Comment by thibaultdelor** [comment]
@MarshallOfSound 

> Then the SSL cert that your proxy uses needs to be trusted by your machine.

It is. the CA has been added to my keychain and all other applications are fine with it. I am browsing using Chrome behind the same proxy.
Obviously there is a mismatch here between what my chrome checks and what Squirrel.Mac checks.

> The correct solution here if for your proxy to be configured / trusted correctly by your OS

Sometimes proxy will use an invalid certificate and the only work around is to ignore the error. I know it's dangerous and using this flag is at my own risk. This is what this flag is for. Seems like right now you can only partially ignore certificate errors which is a bug IMO.

**Comment by MarshallOfSound** [comment]
> Seems like right now you can only partially ignore certificate errors which is a bug IMO.

Strong disagreement on that, those command line flags are documented and known to only affect Chromium.  If you doing stuff with nodes `https` module or native `NSUrlRequest`s those flags won't affect them at all.

It's an auto-updating framework, one of the most sacred things is ensuring the update is legit.  Adding a flag to disable SSL doesn't sound like a great idea to me.

Gonna stand by my original assessment, Squirrel.Mac uses `NSUrlRequest` which is _the_ OS native way of making http requests.  If that doesn't trust your cert, it probably isn't installed in the correct place.  I'm not super familiar with installing self-signed / proxy certs on macOS so I'd suggest just googling around to figure out how to make it work.

**Comment by dreilly1982** [comment]
I have this issue as well on the Mac and have tracked it down to Apple's App Transport Security (ATS) system.  Even if the SSL cert provided by your replacement proxy is trusted, it still must support a number of different conditions to be considered "valid" for ATS, among those are:

1) Must be incorporated in the system trust chain
2) Must be TLS 1.2
3) Connection must use one of a select few ciphers
4) Leaf must be signed by an appropriately long key. (RSA 2048, ECC 256) w/ digest of at least SHA-256.

In my particular case the site I was at only had a 1024 bit signature on the leaf certificate.  This is baked into OS X and the only way around it is the NSAllowArbitraryLoads. 

More info can be found here:
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW35

**Comment by tjx666** [comment]
![image](https://user-images.githubusercontent.com/41773861/124411447-223de980-dd7f-11eb-81d0-f4dde60073f3.png)

very annoying

**Comment by deepak1556** [comment]
Closing based on https://github.com/microsoft/vscode/issues/73806#issuecomment-496334904
