### ISSUE TITLE
Don't dev depend on "vscode" package in our built-in extensions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#73803]
**Problem**
Our built-in extensions that have tests currently have a devDependency on the `vscode` package. This is used for running their integration tests. This package pulls in a lot of extra dependencies for development 

We should see if we can use some built-in runner for these integration tests or potentially look into using the `vscode-test` module @octref created

**Comment by octref** [comment]
Depends on https://github.com/microsoft/vscode/issues/71048

**Comment by octref** [comment]
- [ ] emmet
- [ ] markdown-language-features
- [ ] typescript-language-features
- [ ] vscode-api-tests
- [ ] vscode-colorize-tests
- [ ] vscode-test-resolver

**Comment by octref** [comment]
Need to do after release, otherwise integration test won't pass because the new test runner signature won't be supported yet.

**Comment by madelineliao** [comment]
@octref  does the VSCode debugger for extension tests still depend on the vscode module?

**Comment by octref** [comment]
Not sure what you mean, but if you are using `@types/vscode` and `vscode-test` you can drop `vscode` module.
