### ISSUE TITLE
Chinese characters overlaps in terminal

### ISSUE THREAD

**Issue by localvar** [Microsoft/vscode#7380]
- VSCode Version: 1.2.0
- OS Version: Windows 10 Professional

below is the terminal:
![terminal](https://cloud.githubusercontent.com/assets/504447/15880040/27c90f70-2d5c-11e6-9d01-5392ea577031.PNG)

below is the native command console:
![terminal](https://cloud.githubusercontent.com/assets/504447/15880066/6cc31e4a-2d5c-11e6-9ede-f04fd9b3d490.PNG)

**Comment by f111fei** [comment]
Duplicate of #7062
