### ISSUE TITLE
PPA for Ubuntu?

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#7381]
- VSCode Version: 1.2.0
- OS Version: Ubuntu Xenial

Manual install via .deb feels kinda 1990's... a lot like Windows! ;)
Can MS register a Launchpad account and host an official MS PPA, which would contain vscode, and potentially other software too?
Other people already have unofficial PPA's for vscode to solve this inconvenience, but it never feels good getting software from unknown sources... MS should take ownership of the common distribution channels.

**Comment by Tyriar** [comment]
We wanted a system that wasn't just made for Ubuntu and it's mostly in place. It's based on how Chrome is distributed, once the .deb/.rpm is installed a repository is installed into the apt/yum source list so updates are available. So you need to download the package once or add the repository manually.

Unfortunately it's been blocked for quite some time on how we're going to sign the repo and with what key. Closing in favor of https://github.com/Microsoft/vscode/issues/2973 which has another update towards the end.

**Comment by badmonster-nc** [comment]
Someone did it. You can find information here. 
https://github.com/tagplus5/vscode-ppa

**Comment by TurkeyMan** [comment]
Random PPA's are not okay. You never know who that guy is, or what he may or may not have done with the binaries he's distributing. Apt repos need to be signed.

**Comment by Tyriar** [comment]
@badmonster-nc instructions to set up the official apt repository are here https://github.com/Microsoft/vscode/issues/2973#issuecomment-280575841, installing the 1.10 deb package will also automatically install the repository and key for you.

**Comment by badmonster-nc** [comment]
nice!
