### ISSUE TITLE
Where can I see all (default) settings?

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#73811]
Issue Type: <b>Bug</b>

In earlier versions of VS Code, when you open Settings, it would open a split pane, showing default and user-entered settings. This is no longer the case. 

Where can I see all the default settings?
I don't remember all the setting names by heart and it's a pain to have to search **online** every time I want to change a setting whose name I forgot. This shouldn't be the way it should work. The settings page should show all the settings.

The settings and extension pages have a UI that could really use some improvement (not deterioration in functionality). It would be really appreciated if more time would be invested in these two pages...

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (3.27GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
jest-snippets|and|1.7.0
vscode-toggle-quotes|Bri|0.3.2
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
xml|Dot|2.4.0
es7-react-js-snippets|dsz|2.2.2
LogFileHighlighter|emi|2.4.3
prettier-vscode|esb|1.9.0
vscode-browser-refresh|fab|1.1.5
vscode-debug-launcher|fab|2.0.0
vscode-github-notifications-bell|fab|2.1.5
vscode-highlight|fab|1.3.4
vscode-markdown-todo|fab|1.1.0
vscode-open-in-github|fab|1.1.5
vscode-open-in-marketplace|fab|1.2.7
vscode-projects-plus|fab|1.22.0
vscode-statusbar-debugger|fab|2.0.6
auto-rename-tag|for|0.0.15
rails-snippets|Hri|1.0.8
rest-client|hum|0.21.3
vscode-codemetrics|kis|1.18.0
vscode-language-babel|mgm|0.0.22
ruby-rubocop|mis|0.8.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
JavaScriptSnippets|nat|0.2.0
vscode-versionlens|pfl|0.23.0
vscode-css-peek|pra|2.2.0
ruby|reb|0.22.3
code-settings-sync|Sha|3.2.9
markdown-preview-enhanced|shd|0.3.13
stylelint|shi|0.49.0
code-spell-checker|str|1.7.10
ada-lightbulb|vfo|0.2.1
vscodeintellicode|Vis|1.1.6
glean|wix|4.11.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
The command `Preferences: Open Default Settings (JSON)` is probably what you are looking for.

**Comment by vfonic** [comment]
Yeeees! Thank you! I also found `Preferences: Open Default Keyboard Shortcuts (JSON)`

Would be really great to see this more easily accessible when opening Settings. As a reference, Sublime Text opens split pane with default settings on the left (I can't remember how it looked on VS Code before).

**Comment by roblourens** [comment]
You can see all settings with intellisense in the json file or by using the GUI. You can also set `workbench.settings.useSplitJSON` to get the old split view back if you prefer.
