### ISSUE TITLE
Editor occasionally stuck

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#73819]
Issue Type: <b>Bug</b>

The editor still gets stuck occasionally. I can't type any text, but I can do everything else. VSCode is not "not responding" or anything; it appears to be fully 100% functional. Except for typing text.

This appears to happen randomly, about once or twice in a day of coding. Happens in various kinds of files as well. I can't really say if this happens after a certain action or something.

Usually the editor gets unstuck after "some" time, which could be 5 seconds or 30 seconds, or more, or less. No idea. It seems utterly random. Usually I just restart VSCode and be done with it, but I think we can probably agree that's not a great solution.

I have disabled/uninstalled any addons that need to do stuff on every keystroke. I used to have that, and in an earlier issue, this freezing behaviour was sort of brushed off to those addons (which may well have been just). So now it's happening again without them.

Like I said, this problem occurs occasionally, so trying without any addons unfortunately isn't going to cut the mustard, because I can't really do my work properly without some of these addons. So maybe we can get to the bottom of this without me having to do that. I'm willing to help, but hopefully in another way.

Maybe there's some kind of monitoring tool that I can enable to capture what going on *before* it's too late. Because frustratingly, when this problem happens, by the time I remember how to capture it (and actually do it as well), the problem is already gone.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (19.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
Bookmarks|ale|10.4.3
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.9.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
file-icons|fil|1.0.17
duplicate|gee|1.0.1
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.9
vscode-svg-previewer|vit|0.5.0

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@thany can you please run `code --status` to provide more info? I know it's hard to troubleshoot but if there is a good way to reproduce this issue, or any hint of how to run into this issue more often, that would be super useful. You may also want to take a look at https://github.com/microsoft/vscode/wiki/Performance-Issues to see if you can do any possible profiling when possible.

**Comment by thany** [comment]
Well, I can run `code --status` now, while vscode is running happily like a kitten, which produces the following.

<details>
<summary>Status</summary>

```
Version:          Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS Version:       Windows_NT x64 10.0.17763
CPUs:             Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)
Memory (System):  31.74GB (17.44GB free)
VM:               67%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       73   13640  code main
    0      284     932     window (css-loader.js - Landal - Visual Studio Code)
    0        5    9736       winpty-process
    0        8    8948         console-window-host (Windows internal process)
    0        4   16568         C:\WINDOWS\System32\cmd.exe
    0       29   11704       watcherService
    0        5   10852         console-window-host (Windows internal process)
    0      150   14724       extensionHost
    0       29    1160         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=14724
    0       21   15296         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=14724
    0       54   16608         electron_node eslintServer.js
    0      211   17284         electron_node tsserver.js
    0       55    4080           electron_node typingsInstaller.js typesMap.js
    0       62   20808       searchService
    0     1092   11180     gpu-process
    0       57   15140     shared-process

Workspace Stats:
|  Window (css-loader.js - Landal - Visual Studio Code)
|    Folder (Landal): more than 26501 files
|      File types: dll(9135) xml(4453) cs(3987) pdb(2148) config(2012) _(1024)
|                  txt(537) cache(376) nupkg(330) gif(198)
|      Conf files: csproj(143) package.json(15) sln(7) grunt.js(5) gulp.js(4)
|                  launch.json(1) settings.json(1) tsconfig.json(1)
|                  webpack.config.js(1)
```
</details>

**Comment by rebornix** [comment]
I'll suggest follow https://github.com/microsoft/vscode/wiki/Performance-Issues  to provide information to help troubleshoot when you can reproduce this issue. There is no hint from the `status` or log when the editor is running smoothly. Thanks!

Close it for now and reopen when we have more data.

**Comment by thany** [comment]
A stuck editor is not a performance issue, mind you.

Regardless, the issue hasn't resurfaced since, so I suppose something fixed it. Or it's a crazy coincidence. Either way, thanks for closing 😄
