### ISSUE TITLE
Why font looks bold in macOs?

### ISSUE THREAD

**Issue by kkseven07** [microsoft/vscode#73812]
- VSCode Version: 1.33.1
- OS Version: Sierra 10.12.6

The link to example: [https://superuser.com/questions/1437445/why-vscode-fonts-always-look-bold-in-macos](url)

Tried : `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
Also tried: to edit workbench.main.css, add to .editor.container -webkit-font-smoothing: antialiased; 

These does not work

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)
