### ISSUE TITLE
Can't execute task inside VS Code after VS Code update

### ISSUE THREAD

**Issue by stiltet** [microsoft/vscode#73817]
After I updated VS Code I can't run any NPM tasks anymore. I only receive "npm ERR! missing script" even though the script specified exists in the package.json. The same script works to execute from Power Shell.

Screenshot showing the error in VS Code and the same script running in Power Shell:
![image](https://user-images.githubusercontent.com/4058653/57852357-46c35a00-77e3-11e9-8cbe-85b5e3f30f45.png)

VS Code info: 
![image](https://user-images.githubusercontent.com/4058653/57852241-f21fdf00-77e2-11e9-92c4-2ebc8d791002.png)

tasks.json file: 
![image](https://user-images.githubusercontent.com/4058653/57852153-b84ed880-77e2-11e9-9b10-ba862c3a5a1f.png)

**Comment by alexr00** [comment]
Can you try setting your shell to cmd.exe? I'm wondering if you're hitting some powershell escaping issue that others have seen. In your task:
```
"options": {
	"shell": {
		"executable": "cmd.exe"
	}
},
```

**Comment by stiltet** [comment]
Hi,

Just to clarify, I have not specified to use Power Shell inside VS Code. In my tasks.json I didn't have a "options" property set before. 

When I added what you suggested the only thing that happens when I try to execute the build task is that a command prompt opens. See this screenshot;

![image](https://user-images.githubusercontent.com/4058653/57912210-05d25080-788a-11e9-9892-c1be0967fef4.png)
****

**Comment by stiltet** [comment]
My full tasks.json is as follows:

`// Available variables which can be used inside of strings.
// ${workspaceRoot}: the root folder of the team
// ${file}: the current opened file
// ${fileBasename}: the current opened file's basename
// ${fileDirname}: the current opened file's dirname
// ${fileExtname}: the current opened file's extension
// ${cwd}: the current working directory of the spawned process

{
  "version": "2.0.0",
  "tasks": [{
    "label": "Run app in development mode with express mock middleware",
    "type": "shell",
    "command": "npm run start:disconnected",
    "isBackground": true,
    "group": {
      "kind": "build",
      "isDefault": true
    },
    "options": {
      "shell": {
        "executable": "cmd.exe"
      }
    },
    "problemMatcher": {
      "owner": "webpack",
      "source": "webpack",
      "fileLocation": "absolute",
      "severity": "error",
      "pattern": [{
        "regexp": "^ERROR in (.*)$",
      }, {
        "regexp": "^.*$"
      }, {
        "regexp": "^([^:]*): ([^:]*): ([^\\(]*) \\((\\d+):(\\d+)\\)$",
        "file": 2,
        "message": 3,
        "line": 4,
        "column": 5
      }],
      "background": {
        "activeOnStart": true,
        "beginsPattern": "^.*: Hash: *$",
        "endsPattern": "^.*(Compiled successfully)|(Failed to compile).*$"
      }
    }
  }]
}`

**Comment by stiltet** [comment]
Hi,

After some testing I was able to fix the issue by changing the default Terminal to be cmd.exe. But adding that as a option to the tasks.json, didn't work for me.
