### ISSUE TITLE
File dialogs should get seeded with selected folder of explorer

### ISSUE THREAD

**Issue by wpdavenport** [microsoft/vscode#73821]
Issue Type: <b>Bug</b>

1. Create two folders - folder1 and folder2
2. Click on folder1
3. Press keyboard command to create a new file
4. No need to save the file but you can.
5. Click on folder2
6. Press keyboard command to create a new file

EXPECTATION: The save folder should show folder2

RESULT: You'll see that the the folder that the file will be saved in is folder1

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
githistory|don|0.4.6
gitlens|eam|9.7.4
rainbow-end|jdu|0.6.0
endwise|kai|1.4.2
vsliveshare|ms-|1.0.182
rails-run-spec-vscode|nok|0.1.3
ruby|reb|0.22.3
vscode-yaml|red|0.4.0
partial-diff|ryu|1.4.0
trailing-spaces|sha|0.3.1
haml|vay|1.0.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Works fine for me in latest vscode insiders
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by wpdavenport** [comment]
I was able to reproduce with vscode insiders. Steps to repro.

1. Pulled down a git repo https://github.com/wpdavenport/auto_mate
2. Opened VS Code Insiders and opened project using File -> Open
3. Clicked into the lib -> configs folder
4. Used key command to create a new file: Command + N

![Screen Shot 2019-05-17 at 7 47 16 AM](https://user-images.githubusercontent.com/3083/57926143-82f4ca00-7878-11e9-9462-86272548e7d9.png)

**Comment by isidorn** [comment]
This works just fine for me. But @bpasero might know more about the save as command, thus forwarding to him

**Comment by bpasero** [comment]
@wpdavenport there is no connection of the file explorer in VSCode with the selected folder when you do "Save As". I assume you expect that the native dialog picks the folder that is selected in the explorer?

**Comment by wpdavenport** [comment]
@bpasero Thanks, that does help me understand. Yes, I would think that the native dialog would pick the folder that is selected in the explorer.
