### ISSUE TITLE
Auto close single/double quotes aren't working with Intl language

### ISSUE THREAD

**Issue by andremacola** [microsoft/vscode#73828]
- VSCode Version:  1.34.20-insider 
- OS Version: OSX
- Keyboard: USA International (I'm from Brazil)
- Related: #26820

Steps to Reproduce:
1. See below

Does this issue occur when all extensions are disabled?: Yes

![aaaaa](https://user-images.githubusercontent.com/3408809/57871756-745ad400-77e0-11e9-912b-071e48a8d2fd.gif)

**Comment by andremacola** [comment]
If the function has space inside the `()` the auto close works fine with the international keyboard. For ex. Not only PHP but any other language like Javascript

![quotes](https://user-images.githubusercontent.com/3408809/58575738-1fc04b80-8219-11e9-8fa5-f9c926102c73.gif)

**Comment by andremacola** [comment]
In multicolumn/line even outside () or [], VScode only close the first line.

**Comment by andremacola** [comment]
In multicolumn/line even outside () or [], VScode only close the first line.

![quote](https://user-images.githubusercontent.com/3408809/59699982-e4d28780-91c8-11e9-894d-13a01b6daba8.gif)

**Comment by alexandrudima** [comment]
Let's track in #59990
