### ISSUE TITLE
VSCode randonly hangs / becomes unresponsive

### ISSUE THREAD

**Issue by garethc123** [microsoft/vscode#73825]
Issue Type: <b>Bug</b>

Since Monday , VSCode randonly hangs / becomes unresponsive when I'm performing any action in it. For example, it hangs sometimes when I'm typing, other times when I'm opening a menu; it actually hanged when I was typing this bug report.

What happens is that the keys I'm typing don't appear on the screen for 10 - 20 seconds after actually being typed - then they all appear at once.  Sometimes the VSCode window turns entirely black for 10 - 20 seconds too. VSCode never entirely crashes - i.e., I never have to restart it after this problem happens.

I use VSCode for several hours daily and this problem might happen every 5 - 10 minutes. It first happened on Monday of this week, so it's a brand new problem.

VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:06:45.467Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-spell-checker|str|1.7.10

</details>

**Comment by sja1n** [comment]
I am facing the same issues though on Ubuntu 19.04. It hangs for a brief amount of time.

**Comment by rebornix** [comment]
Can you please follow our wiki to help provide more info https://github.com/microsoft/vscode/wiki/Performance-Issues ?
