### ISSUE TITLE
Multiple containers in multi-root workspaces using Remote Container debugging

### ISSUE THREAD

**Issue by elliottyates** [microsoft/vscode#73824]
Support for Multi-root workspaces spinning off multiple containers using Remote Container debugging would be great. The documentation for these new features (the FAQ) implies it is a known limitation; if there is no other way for users to track this feature, perhaps this issue could serve as a starting point. Thanks!

**Comment by Chuxel** [comment]
@elliottyates Just to double check - are you talking about the Remote - Containers extension?  Also I assume you mean not just debugging but editing, etc? 

If so, we can move the feature request to the `vscode-remote-release` repo.

You are correct that currently a workspace can only be in one container, but [there is a way to use multiple windows](https://code.visualstudio.com/docs/remote/containers-advanced#_connecting-to-multiple-containers-at-once) to work with separate containers managed by Docker Compose.

**Comment by elliottyates** [comment]
@Chuxel sorry for the delay in responding. I think what you're saying is the same as what I'm thinking, yes -- I'd like to have a single window open (e.g. for search purposes, across code sources run across multiple different containers) and have the window understand the context I'm in while (a) editing (e.g. understanding which versions of the libraries are referenced, for code introspection) and (b) debugging (effectively a case of (a)). Thanks! I hope that helps?
