### ISSUE TITLE
Visual Studio Code (The windows has crashed)

### ISSUE THREAD

**Issue by sachinhd517** [microsoft/vscode#73822]
The window has crashed
We are sorry for the inconvenience! You can reopen the window to continue where you left off. This showing pop window. I don't know how to open visual studio code?

**Comment by sbatten** [comment]
Please provide additional details. From your description, it is difficult to understand the issue. Also please see this page for instructions on how to report crashes. https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by sachinhd517** [comment]
Two days before I have clicked Visual Studio Code icon It has showing error (The window has crashed)
I am using windows 10 Single Lang. 

![ErrorVsCode](https://user-images.githubusercontent.com/34281384/57916079-c159ab80-78af-11e9-9e5f-733abf3861fe.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sachinhd517** [comment]
I have already download and installed VS Code insider. But this vs code not running...

**Comment by sachinhd517** [comment]
I have solved this. 
https://stackoverflow.com/questions/31270774/visual-studio-code-always-reopens-previous-file-or-folder
