### ISSUE TITLE
[debug] add option to select workspace folder when calling 'Add Configuration'

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/vscode#73826]
**Description**

At the moment, when running the debug command **`Add Configuration...`**, the new configuration is always added to the first workspace folder when a user currently has multiple folders present in his/her workspace.

In order to properly support multiple folder workspaces, I suggest that a prompt be provided to end users to choose in which workspace folder they'd like to add a new debug configuration to. (similarly to how the `New Terminal` command works and users select their desired current working directory from all possible folders).

**Steps to Reproduce**
1. Open a workspace with multiple folders
2. Open the menu item `Debug` and select  **`Add Configuration...`**
3. Notice that the new configuration is always added to the first workspace folder despite multiple folders being present

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/57866321-238db000-77cd-11e9-905c-b8772fd4e453.png)

</div>

**Comment by isidorn** [comment]
This is a fair feature request. However currently is not on the plan.
Also it does not always add it to the first launch.json but to the selected launch, which basically means the last used one.

**Comment by ArulDhandapani** [comment]
I recommend to extend this launch.json configuration to .code-workspace file under respective language sections to improve debugger configurations and the usability.
