### ISSUE TITLE
  Message: Request initialize failed with message: Cannot read property 'replace' of null   Code: -32603

### ISSUE THREAD

**Issue by richie50** [microsoft/vscode#73836]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Opened vscode after MacOs mojave update
![image](https://user-images.githubusercontent.com/7333599/57877381-b63a4900-77e5-11e9-9086-ec08cb3b1d79.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Closing as this issue is not actionable without more information about what is going wrong and steps to reproduce the issue
