### ISSUE TITLE
"Edit in settings.json": generate settings placeholders

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#73847]
Issue Type: <b>Feature Request</b>

When editing a setting with "Edit in settings.json" insert a default/empty setting placeholder. Currently this is more painful than it has to:

1. It's not obvious what the setting ID is (the "copy setting ID" is not particularly discoverable, nor convenient)

2. Even if a user happens to find the semi-hidden "copy setting as JSON", it's not a great starting point, since the default value is null. It's not clear if the setting is supposed to be an array for example.

![edit_in_settings_json](https://user-images.githubusercontent.com/13824553/57886446-16c78700-77e2-11e9-9d20-c6749f9bb09e.PNG)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/67908
