### ISSUE TITLE
Monaco API Request : Ship standalone languages

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#7384]
Please still ship standalone languages in monaco :heart: 

Specifically talking about this commit : https://github.com/Microsoft/vscode/commit/3268ae1e5e4d6f0d510bb34ded4a2705e859ccc1 

They actually work quite nicely e.g. you can see a c# file here in [alm](http://alm.tools/): 

![image](https://cloud.githubusercontent.com/assets/874898/15882448/e9787654-2d81-11e6-8845-4846ecbc4f0e.png)

Indeed they might not be as good as the textmate languages, but they are good enough for an editor that isn't focused on these other languages but still allows you to make quick edits (or just read) these.

Thanks for a great editor component :rose:

**Comment by alexandrudima** [comment]
We will still ship them, just not out of the vscode repo. Things are still in flux as I refactor and move things around.

**Comment by basarat** [comment]
Thanks! :rose:

**Comment by basarat** [comment]
I can see them at https://github.com/Microsoft/monaco-languages and already have them being pulled in for alm automatically so all good from my side :heart:
