### ISSUE TITLE
Terminal display issue on first open

### ISSUE THREAD

**Issue by aaronplummeridgelumira** [microsoft/vscode#73842]
(Windows) 

Make sure VSCode is closed.

1) Open VSCode
2) Navigate to the Terminal

The cursor is not visible. If you click in the box, the cursor flashes but the current directory is not visible. If you hit enter, it resolves the issue.

**Comment by SoulSeekkor** [comment]
I've had this issue for months, very frustrating, didn't know that hitting enter would fix it (though I hit it quite a few times before it finally did).  Been reopening VSCode like 10+ times to get it to show for months now.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
