### ISSUE TITLE
SelectBox is missing title

### ISSUE THREAD

**Issue by YurongHe** [microsoft/vscode#73844]
DEBUG selectBox, when hover over, can't see title.
Checked with latest insider build, has the same issue.

While in version 
![image](https://user-images.githubusercontent.com/43652751/57883019-eda2f880-77d9-11e9-98a3-3959cf7c96b0.png)

There is title

![image](https://user-images.githubusercontent.com/43652751/57882973-d2d08400-77d9-11e9-8807-644ed2b7ddc5.png)

May be caused be https://github.com/microsoft/vscode/commit/6bab1c3ee1f5c580ac14579be88b2da09064cd57

**Comment by isidorn** [comment]
@cleidigh do you have time to look into this?

**Comment by isidorn** [comment]
@YurongHe do you see this for other dropdowns as well. For example the terminal dropdown, or the output channel name dropdown?

**Comment by YurongHe** [comment]
Terminal dropdown has no title either.

**Comment by isidorn** [comment]
Ok, so it is a general select box issue. Let's see if @cleidigh has time to look into this

**Comment by cleidigh** [comment]
@isidorn 
Absolutely.  I've been a bit awol...
Will look at this tomorrow.
