### ISSUE TITLE
Themes: changing theme colors in settings running out of sources does not update color anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#73855]
Not sure why.

**Comment by aeschli** [comment]
Not able to reproduce.
- Running from sources,
- Set
```
	"workbench.colorCustomizations": {
		"statusBar.background": "#ff0011"
	}
```
- save settings
- status bar color changes

Maybe you have workspace settings?
Best ist to debug it... [browser/workbenchThemeService](https://github.com/microsoft/vscode/blob/6ac87465f297a9068bf767f45d6f372fc5697de9/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L301)

**Comment by bpasero** [comment]
@aeschli on macOS?

**Comment by bpasero** [comment]
An issue with the file watcher on my end.
