### ISSUE TITLE
Remote Extensions addition: Windows Remote Desktop

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#73851]
We're a Windows shop, so when we're remoting we don't use SSH, but instead Windows' remote desktop service via a remote desktop only VPN.

I know this can't be *that* uncommon, because my SO's work does the same thing -- remote desktop VPN only, only Windows Remote Desktop supported.

Adding a flavor of remote extension to use this (because, honestly, when I remote in all I'm doing is in VSCode anyway!) would be fantastic.

**Comment by roblourens** [comment]
Are you asking for a way to keep the vscode window on your local machine but access the remote through the RDP protocol? I don't believe this is practical as we can't set up a connection to send arbitrary data using RDP, sorry.
