### ISSUE TITLE
Stacks - Debugger frequently covers actionable editor buttons requiring editor resize

### ISSUE THREAD

**Issue by anyong** [Microsoft/vscode#7385]
This was always an issue but with more actionable buttons in the new editors like the overflow menu, it is more of an issue now.

- VSCode Version: 1.3 insider
- OS Version: Win10

Steps to Reproduce:

1. Open an editor on the left
2. Run a program

![](http://i.imgur.com/EwUE5YG.png)

I'm not sure what the solution is here. Maybe a small handle on either side of the debugger that allows us to drag the debugger out of the way? Maybe putting the debugger in the completely blank header of the debug panel?

![](http://i.imgur.com/TAI9o91.png)

**Comment by isidorn** [comment]
This should get adressed in the future by #4580 
So closing as a dupilcate
