### ISSUE TITLE
Auto save - EBUSY Resource busy or locked

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode#73852]
Issue Type: <b>Bug</b>

Error received at times when file is being auto saved.

I have all extensions disabled and I'm using vanilla instance of VS Code Insiders.

Reference previous issue that was closed #71808

![image](https://user-images.githubusercontent.com/11204251/57890960-3caf5480-77ff-11e9-8256-94b3d16e71ed.png)

Only fix for this is reload VS Code. Since VS Code still keeps the contents I don't tend to loose any content but it does effect my workflow when I'm uploading these scripts to Azure Automation account and the file has to be saved before it is uploaded.

VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:06:45.467Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.42GB free)|
|Process Argv|--folder-uri file:///c%3A/git/aa-dbatools|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by wsmelton** [comment]
My workflow on this is literally just working on scripts. I'm not using shortcuts or menu to save any file, that I can recall it has come from the auto save trying to save the file.

**Comment by bpasero** [comment]
@wsmelton possibly some external tool you use is locking the file? Can you please find out which process locks the file?

**Comment by wsmelton** [comment]
According to process explorer a process spawned by VS Code has the file locked...I use no external tools for editing these files.

![image](https://user-images.githubusercontent.com/11204251/57971441-49958a80-795c-11e9-9072-8249a6bd25f0.png)

**Comment by bpasero** [comment]
Looks like PowerShell.

**Comment by Tyriar** [comment]
Whatever you're running in your powershell terminal is holding onto it, nothing to do with vscode.

**Comment by wsmelton** [comment]
Yeah sorry that would be wrong because Code is the one that opened the the process. As well I am not running anything in my pwsh session when this happens...that is completely visible in the screen shot.

**Comment by Tyriar** [comment]
The pwsh.exe executable is holding onto it, we just create that process, not tell it what to do. FYI @TylerLeonhardt

**Comment by wsmelton** [comment]
I didn't do anything to this file when it happened, or before. I'm not using the PS extension terminal.

In this particular project I'm just uploading the code to a runbook in Azure. The command I use from the Az.Automation module doesn't put a lock on the file.

**Comment by TylerLeonhardt** [comment]
So based on your 2nd screenshot, the `Get-DatabaseSpace.ps1` shows up locked by `pwsh.exe` that's spawned from VSCode. Am I interpreting that correctly?

And you're not running anything in that terminal before the issue occurs?

And this is an intermittent problem, is that right (since you're able to restart and save with no problem)? 

I wanna make sure we rule out everything. Is there any chance there's something in your profile that might be interacting with the file system?

**Comment by wsmelton** [comment]
Correct on all accounts. Nothing in my profile that touches the files.

I run import-azautomationrunbook to upload the code. It had been 15-20 minutes though since I had last run the command, I recall.
