### ISSUE TITLE
Closed file is rehydrated after close folder and saved content is lost

### ISSUE THREAD

**Issue by YurongHe** [microsoft/vscode#73854]
1. Open vs code without any file/folder is open
2. Create a new file with default name (Untitled-1)-> put some input -> save and close it. Make sure no editor is open
3. Open the folder, which content the file created in step 2. No editor is open. Everything is good so far.
4. Close the folder from File menu
   Now Untitled-1 is opened in editor and blank.

**Comment by sbatten** [comment]
Is your setting for `workbench.startupEditor` set to `newUntitledFile`? If so, this is the designed behavior.

**Comment by YurongHe** [comment]
Yes. that is set.
