### ISSUE TITLE
Search - When file to include set a abs path，search did not work and raise a error！

### ISSUE THREAD

**Issue by lovelyworm** [microsoft/vscode#73859]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/7920142/57898325-264eda80-788b-11e9-97fd-12ee0a62bf18.png)

![image](https://user-images.githubusercontent.com/7920142/57898335-323a9c80-788b-11e9-8c27-6e23cd7d9498.png)

VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:06:45.467Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (17.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gemfile|bun|0.0.2
vscode-eslint|dba|1.9.0
gitlens|eam|9.7.4
beautify|Hoo|1.5.0
typelens|kis|1.6.6
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
codemap|ole|1.6.0

</details>

**Comment by roblourens** [comment]
Is vscode installed on the D drive?

Does it work if you search a folder on the c: drive?

**Comment by lovelyworm** [comment]
my vscode installed in D drive, search is ok when include a folder, failed when I include a absoulte path.

**Comment by roblourens** [comment]
Does it work if you include an absolute path on the C: drive?

Does it work if you use a path like `./foo/bar` from the root of the open folder?
