### ISSUE TITLE
C++ syntax highlighting error

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode#73858]
Issue Type: <b>Bug</b>

![捕获1](https://user-images.githubusercontent.com/20399194/57896997-05d05180-7886-11e9-9f74-8e3b8c0e55b7.PNG)

![捕获2](https://user-images.githubusercontent.com/20399194/57896999-08cb4200-7886-11e9-816e-df50d4327a6a.PNG)

```cpp
#include <cstdio>

int main()
{
	char **sss = new char *[3];
	for (int i = 0; i < 3; ++i)
		sss[i] = new char[2];
	return 0;
}
```

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.1.6
language-gas-x86|bas|0.0.1
doxdocgen|csc|0.4.2
disasexpl|dse|0.0.4
gitlens|eam|9.7.4
vsc-material-theme|Equ|2.8.2
vsc-material-theme-icons|equ|0.12.0
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hans|MS-|1.34.2
cpptools|ms-|0.23.1
markdown-preview-enhanced|shd|0.3.13

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
This has been fixed in Insiders, and will be fixed in the next release. We need more C++ users in insiders to help catch bugs like this before we release, so if you can please try using Insiders for a bit! 
https://code.visualstudio.com/insiders/
