### ISSUE TITLE
Semantic bracket matching

### ISSUE THREAD

**Issue by parindawm** [microsoft/vscode#73864]
1. please make test.cpp file using following code
 
```cpp
#undef x
int main() 
{
  int a=0, b=0, c=0;
#ifndef x
  if(b==2){
    if(a==0){
    }
    else
#else
  if(c==1){
#endif 
    a=1;
  }// wrong matching
  return 0;
}// wrong matching
```

2. Observe wrong bracket pairing at commented places. "// wrong machine"

![Capture17052019](https://user-images.githubusercontent.com/50728959/57904861-1513c700-78a7-11e9-9765-ca0d8fc18019.PNG)

**Comment by alexr00** [comment]
@parindawm do you have the C/C++ extension installed? Without that extension, you wont have as good an experience with coloring when you use preprocessor keywords. However, even with that extension, the bracket pairs are incorrect. Please file this issue with the C/C++ extension!

**Comment by parindawm** [comment]
thank you for the quick attention . it seems to vscode-cpptools problem. I raised a ticket 
https://github.com/microsoft/vscode-cpptools/issues/3681

**Comment by sean-mcmanus** [comment]
@alexr00 I don't think the C/C++ extension can solve this because VS Code's current brace matching API relies on regex, which doesn't have any way to determine which section of the `#if #else` is active. Our extension adds our own "inactive" coloring, but it's not understood by the brace matching TextMate system.

**Comment by alexr00** [comment]
@sean-mcmanus you're right, re-opening.

**Comment by alexandrudima** [comment]
I can confirm bracket matching is done in the editor, programming language agnostic, (except for knowing to skip comments, strings and regular expressions) and it is not semantic.
