### ISSUE TITLE
SharePoint SiteAssets files empty post saving and closing VS Code

### ISSUE THREAD

**Issue by e-kk** [microsoft/vscode#73862]
Please follow the below steps,
1. Open any sharepoint website siteassets folder using "open folder" option from menu "File"
2. add any file(ex: .js) to this library  and add some code and then save it.
3. It happens rarely but that time it saves empty file even though you save it before you close visual studio code.

Temp Solution: we enabled versioning for the library so that even though its empty we restore previous working version when we find the page empty.

**Comment by bpasero** [comment]
@e-kk can you actually reproduce that the file gets empty during the running session or does this only happen on close?

**Comment by e-kk** [comment]
It's happening on close  also at the time when its disconnect from
internet connection. When we try to open or use the opened session of
vscode , it will show like working but when you  close and open it again in
next working day , everything gets empty.

Thanks,
Kiran.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by e-kk** [comment]
My understanding is that while you save these files ,we need to provide
sometime to save them to server from vscode.

If we save hit ctrl+s and close immediately is the reason for this i guess,
we need to allow vscode to contact server and to save the data.


But we don't how much time it require for this. If we have response from
server to vscode then it would be good.

Thanks,
Kiran.

**Comment by bpasero** [comment]
You are on Windows right and open the folder through the Windows dialog?

**Comment by e-kk** [comment]
Yes, following the same. Sometimes front taskbar.

Thanks,
Kiran.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
