### ISSUE TITLE
调试的时候特别特别卡，几乎吃满了cpu

### ISSUE THREAD

**Issue by BieZhiYong** [microsoft/vscode#73868]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by byyxx128** [comment]
### The author is reporting a performance issue in his native language. I'm telling him how to report a performance issue in English.
To be simple, I will contact to him in his language directly.
This issue can be closed and the author will open a new one to report the performance issue.
***
1. 用英文反馈。这个 issue 直接 close，新开一个。
2. 反馈性能问题，不要在 GitHub 上直接开 issue，看这里——
![image](https://user-images.githubusercontent.com/20079289/57961272-cb919f00-78db-11e9-9f00-d2f335360409.png)
3. 你要说一下详细的重现步骤，或者在进行什么操作时出现这个问题（高 CPU）。
祝你好运。
