### ISSUE TITLE
import snippets in runtime

### ISSUE THREAD

**Issue by chnliquan** [microsoft/vscode#73861]
I want to dynamically introduce snippets on the remote server in my extension. Before the entry file executes the active function, I get these snippets through the http request and put them into the local directory and then modify the package.json file to increase the pointing of the snippets, but these Snippets does not take effect

**Comment by jrieken** [comment]
Yes, the snippets from package.json are read only once, early on startup and before running your extensions. For dynamic extensions you should use a completion item provider as doc'ed here: https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample
