### ISSUE TITLE
vscode cannot read property 'trim' of null  error with vscode insider 1.35

### ISSUE THREAD

**Issue by ttbug** [microsoft/vscode#73867]
Issue Type: <b>Bug</b>

when i debug python file, set breakpoint and  F5 ,vscode cannot read property 'trim' of null  error occured  in vscode insider 1.35,  while 1.34.20 works well，so i install  1.34.20 again.

VS Code version: Code - Insiders 1.34.20-insider (e83e24a0c9225becd7341e56952177a20d5d4629, 2019-05-15T18:06:45.467Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: alias|
|OS|Linux x64 4.9.0-9-amd64|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (2 x 2807)|
|Memory (System)|3.85GB (0.55GB free)|
|VM|100%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.9
pyright|ms-|1.0.28
python|ms-|2019.4.12954
Go|ms-|0.10.2
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.1.6
vscode-language-pack-zh-hans|MS-|1.34.2
remote-containers|ms-|0.53.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
remote-wsl|ms-|0.35.0
vscode-remote-extensionpack|ms-|0.14.0
material-icon-theme|PKi|3.7.0

(1 theme extensions excluded)

</details>

**Comment by zzzJH** [comment]
the same problem after update 1.35.0-insider

**Comment by jerrylususu** [comment]
same bug too, on 1.35.0-insider, appears whenever I start debugging.

**Comment by ypapouin** [comment]
Link to previous version:
https://update.code.visualstudio.com/1.34.20-insider/win32-x64-user/insider

**Comment by magic-k** [comment]
It worked yesterday with 1.35 so this problem came with todays update

**Comment by AeneasZhu** [comment]
I also have this problem too on the 'Exploration' Version. So I switch to Insider Version of 1.34, but when it update today, the same bug happened again.

**Comment by allenwu5** [comment]
> Link to previous version:
> https://update.code.visualstudio.com/1.34.20-insider/win32-x64-user/insider

Mac ver. https://vscode.cdn.azure.cn/insider/d6aa8eaf30c71df32d4543290675808440def630/VSCode-darwin-insider.zip

**Comment by beachbc** [comment]
You can work around this issue by updating your launch.json with  `"console": "internalConsole"`

Python: Current File example:
`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "internalConsole"
        }
    ]
}
`

**Comment by katsos** [comment]
Is anyone working on this one? I can give it a try

**Comment by bevo009** [comment]
FYI the console workaround  "console": "internalConsole" doesn't work with any input(), otherwise I would just use code runner until this was fixed.
 A bit maddening that any restart reinstalls the borked 1.35.0, now I have to reinstall 3.4 AGAIN to get around this bug?  Why don't you flag borked upgrades as incompatible so vscode-insiders ignores them?  Forcing buggy installs doesn't seem a positive path to take...

**Comment by rchinna** [comment]
Hit the same issue, thanks to @beachbc for the workaround.

**Comment by Sherlock92** [comment]
same issue here, dg to 1.35 for now. I'm not so familiar with vscode otherwise i would like to contribute

**Comment by roblourens** [comment]
Another possible workaround: set the terminal to bash: https://github.com/microsoft/vscode-remote-release/issues/350#issuecomment-493619458

**Comment by Cow258** [comment]
Same issue here...
Unable to debug anything.
And some log can't display on "internalConsole".
So I switch back to VSCode for this moment.

**Comment by guyhuang** [comment]
> You can work around this issue by updating your launch.json with `"console": "internalConsole"`
> 
> Python: Current File example:
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Python: Current File",
>             "type": "python",
>             "request": "launch",
>             "program": "${file}",
>             "console": "internalConsole"
>         }
>     ]
> }
> ```

That's the answer. But I donnot know why. Maybe corrected in release version.

**Comment by egamma** [comment]
Adding the important label since the breaks the 'vscode-remote-try-python' sample.

**Comment by Norbinsh** [comment]
> You can work around this issue by updating your launch.json with `"console": "internalConsole"`
> 
> Python: Current File example:
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Python: Current File",
>             "type": "python",
>             "request": "launch",
>             "program": "${file}",
>             "console": "internalConsole"
>         }
>     ]
> }
> ```

This works - changing to internal console.

Thanks.

**Comment by liedav** [comment]
I have the same issue: vscode cannot read property 'trim' of null when running python code with/without debug in version 1.35, whereas 1.34.20 works.  I have tried the workaround of replacing "console": "integratedTerminal" with "console": "internalConsole" in the launch.json file and it did NOT work for me.  I have reverted back to 1.34.20.

**Comment by PeterJPRoche** [comment]
Having the same issue debugging Python code. VS Code - Insiders 1.35.0. The workaround of replacing "console": "integratedTerminal" with "console": "internalConsole" worked for me (thankfully!)

**Comment by yamcenutzer** [comment]
which commit fixes this? I don't see any change.

**Comment by weinand** [comment]
@yamcenutzer Commit 15a0e88d2755c4a37c44c1bd326b2de2e5b5d5e2. See 4 comment above:

![2019-05-22_16-38-51](https://user-images.githubusercontent.com/1898161/58183724-192d5380-7cb0-11e9-8fe8-57f6e322fb45.png)

**Comment by yamcenutzer** [comment]
either that commit isn't in 1.35.0
- or it doesn't help with remote cpp debug with gdb.
- or the cpp exension needs to know about "console" (which it doesn't)
- or the remote extension doesn't know about it

Like I said, I have no idea whether my original issue, which was about remote cpp debugging on real linux (not WSL, ever), is the same as this one. There are 3 teams involved, which in the, past, seem to not know of each other: vscode, cpp, and as of recently: remote-ssh.

So I ask again, do I need to ask someone else, or simply wait until my insiders build offers me an update beyond 1.35.0?

**Comment by weinand** [comment]
@yamcenutzer but you are setting the `externalConsole` in your launch config to false, correct?

**Comment by yamcenutzer** [comment]
yes, 
and that's nice...

If you say it should be in 1.35.0, then I'll reinstall from scratch..

**Comment by weinand** [comment]
@yamcenutzer and you are seeing the "cannot read property 'trim' of null error" or the never ending progress indicator?

**Comment by yamcenutzer** [comment]
never ending progress...

hangon...
I'm installing again, I believe I'm getting updates now...

**Comment by bevo009** [comment]
' updating your launch.json with "console": "internalConsole"  '

Not an answer if your code is interactive ie using input(), the internal
console doesn't work with that
The internal console is much neater in output though, if it worked with
input() I'd always use it...debugger output always makes a mess of the
terminal

**Comment by isidorn** [comment]
@tyriar thanks for fixing. The fix looks good.
