### ISSUE TITLE
Multiple monitors: git password prompt

### ISSUE THREAD

**Issue by akoskm** [Microsoft/vscode#7386]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:
1. Commit
2. Click Synchronize Changes

github password prompt will appear on the secondary monitor under all others windows. If there is anything in fullscreen on the secondary monitor you won't even notice that it has appeared.

**Comment by joaomoreno** [comment]
As a workaround, I suggest using a credential manager or ssh keys.

**Comment by joaomoreno** [comment]
This can be solved by using the new modal dialog from Electron, once we update.

**Comment by joaomoreno** [comment]
Not using the dialog any more.
