### ISSUE TITLE
Add color swatch for css variable in intellisense description

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#73866]
Would be really handy to have the color swatch appear in the description of the intellisense:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/35271042/57907059-fd99f700-7830-11e9-958f-f879be92b5b6.png">

**Comment by jrieken** [comment]
This should be doable from the extension

**Comment by octref** [comment]
> description of the intellisense

That is impossible. The only thing possible is to make it show in the left kind icon. @misolori would that be good enough for you?

![image](https://user-images.githubusercontent.com/4033249/64194009-f96f0500-ce32-11e9-91fc-c982dcea78ae.png)

**Comment by misolori** [comment]
It sort of helps, it's better than no indication though so I'll take it.

**Comment by octref** [comment]
I don't think this can be a possible addition, since we use Markdown in description and there's no standardized way to write color swatch in Markdown.

**Comment by octref** [comment]
Verifier: Verify that both `color: -|` completion and `color: var(|)` completion reveals the color if variable is color.

**Comment by misolori** [comment]
👏 This looks great!

<img width="321" alt="image" src="https://user-images.githubusercontent.com/35271042/66080192-6ea92500-e51a-11e9-872a-0a9e1b976728.png">


<img width="318" alt="image" src="https://user-images.githubusercontent.com/35271042/66080182-6b159e00-e51a-11e9-8154-8a6b61533948.png">
