### ISSUE TITLE
New Embedded Command Line issue

### ISSUE THREAD

**Issue by ahmetatar** [Microsoft/vscode#7387]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open the new embedded command line (CTRL + ")
2. Close CLI and change vscode theme
3. Then open embedded CLI again

It is not working!

**Comment by Tyriar** [comment]
Thanks for the report @ahmetatar, this is likely a duplicate of https://github.com/Microsoft/vscode/issues/7251
