### ISSUE TITLE
Windows installer icon is blurry

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#73872]
- VSCode Version: 1.34.0
- OS Version: Windows 10

The installer icon (on the right) is blurry when installing VSCode in Windows 10 with a high DPI screen (3000x2000, scaling set to 200%):

![image](https://user-images.githubusercontent.com/199648/57916575-6619c000-7893-11e9-94bd-d73cbf0701ba.png)

**Comment by joaomoreno** [comment]
Closing as https://github.com/microsoft/vscode/issues/38354

**Comment by warpdesign** [comment]
> It's fine...

I'm sorry, but it's not fine at all... This is ugly: I can understand there are higher priorities. But it's been more than a year than #38354 has been closed and the problem is still there.

**Comment by joaomoreno** [comment]
How to fix:

> When multiple files are specified, Setup will automatically select the one which best matches the system's DPI setting.

- http://www.jrsoftware.org/ishelp/index.php?topic=setup_wizardsmallimagefile
- http://www.jrsoftware.org/ishelp/index.php?topic=setup_wizardsmallimagefile

We need more sizes for these icons, @misolori. Could we get them>

**Comment by misolori** [comment]
This should have support for HiDPI screens now:

![image](https://user-images.githubusercontent.com/35271042/59853605-0d23c880-9326-11e9-9f5a-4aa663500b30.jpg)

**Comment by misolori** [comment]
⚠️ Verification steps requires a HiDPI screen ⚠️

Steps:
1. Download .exe file
2. Run installer
3. Verify that icons are not blurry on HiDPI screen (Retina, 4k, etc.)
