### ISSUE TITLE
Asan / sanitizers integration

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/vscode#73875]
Doing the same as https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-the-linux-workload-in-visual-studio-2019/
would be a major improvement to developper well being and performance.

It would be even nicer to get the outputs of Ubsan, tsan and Msan too.

**Comment by Tyriar** [comment]
I think this is only applicable to C++, see https://github.com/Microsoft/vscode-cpptools/issues
