### ISSUE TITLE
Terminal default font not useful if editor font is proportional

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode#73879]
Issue Type: <b>Bug</b>

If the editor is set to use a proportion font, Terminal tries to use it, which causes it to default to a some font with a really wide character spacing. It should default to something nice looking instead, such as Consolas. Additionally, when you change the terminal font manually, the layout is initially wrong.

Repro:
1. Set the editor font to Calibri.
2. Open Terminal.
3. Notice that it looks like this:
> W i n do w s   P o w e r S h e l l
4. Set the Terminal font to Consolas.
5. Notice that the font looks good now, but the right margin is misplaced (about 2/3 of the way across).
6. Delete the terminal and create a new one. It looks right now.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.26.0
githistory|don|0.4.6
gitlens|eam|9.7.4
git-project-manager|fel|1.7.1
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1

</details>

**Comment by breyed** [comment]
This issue is distinct from #35681. The other issue is basically, "Please support proportional fonts in the terminal." This issue is, "Please don't default to an unsupported proportional font in the terminal just because the editor is using a proportional font."

**Comment by Tyriar** [comment]
Unfortunately the only means for checking is something is monospace is measuring different characters and that doesn't seem to work all the time, so if some fallback was added I believe it would break several fonts. You probably shouldn't be using a proportional font in the editor either tbh as that messes with the editor columns (down/up), rulers, etc.

**Comment by Tyriar** [comment]
The font metrics thing you're suggesting is essentially exactly what is being done, just using the web platform to measure instead:

https://github.com/microsoft/vscode/blob/1dd67cb2ce6882ea25e8a7c725eb67fcd07c3b03/src/vs/workbench/contrib/terminal/browser/terminalConfigHelper.ts#L64-L76

Right now when it happens you should get a notification (provided the terminal is visible) that tells you that the font doesn't work and gives you a button to set it to `monospace`, this is a decent compromise imo.

**Comment by breyed** [comment]
I agree that the compromise is reasonable. I'd suggest additionally changing the terminal fallback code (for before the user updates the font setting) to use monospace rather than wide-spaced Times New Roman as it does now - if you have to fall back to something, might as well make it something that looks good.

----

The code snippet is similar to what I suggested, though not quite the same. I looked a little closer. It appears the best approach to determining whether a font is proportional is to call [GetFontMetrics](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-gettextmetrics) and see if `tmPitchAndFamily` has the `TMPF_FIXED_PITCH` bit set.

The snippet is nice in that it's cross platform, and it generally works, but it's not deterministic. For example, it suffers from a gender bias bug.... Currently the proportion of women in tech is low, but what happens as it increases? The likelihood increases that a woman, nostalgic for her grade school days, will want to code using a cute font with hearts instead of dots on the 'i' and 'j'. If the heart is just the right size, the 'i' and 'w' will happen to be the same width, even though the font is proportional, breaking the heuristic in the code snippet. :-)

**Comment by Tyriar** [comment]
We definitely don't want to add Windows-specific native logic to calculate the width, we could probably fallback relatively safely by appending ", monospace" to the `font-family`, maybe with a small check to ensure any quotes are closed.

**Comment by Tyriar** [comment]
@breyed my point is that right now we're using a cross platform solution provided by Chromium, it would be silly to invest in a native node module that has separate implementations for all platforms.

> Except why would you put quotes around , monospace?

The setting could be set to: `"'somefont"`, meaning the font would probably be interpreted by the browser as `"'somefont, monospace'"`

**Comment by breyed** [comment]
I concur, except that I wouldn't say it's silly, just more effort than the feature is worth. A deterministic query for whether a font is fixed width is better than an imperfect heuristic, but they're the same for practical purposes. Ironically, Chromium [keeps track](https://github.com/chromium/chromium/blob/6efa1184771ace08f3e2162b0255c93526d1750d/third_party/blink/renderer/platform/fonts/simple_font_data.h#L108) of the needed data (average and max font width) and even [used to](https://chromium.googlesource.com/chromium/blink/+/89c065eaa778ed55f80d7e3f9205fb6e25e7b2e2/Source/WebCore/platform/graphics/FontPlatformData.h) hold `isFixedPitch` directly; it just doesn't expose this data to Javascript.

**Comment by MananTaneja** [comment]
Hey @Tyriar @meganrogge, if work has not already been done on this, would it be alright if I can pick this up?

**Comment by antonioprudenzano** [comment]
This issue seems resolved now, i can see that @Tyriar added the necesary code to fallback to monspace font.
https://github.com/microsoft/vscode/blob/c6aaa761fd7a2d24dea85fbb1e9f2737f680e210/src/vs/workbench/contrib/terminal/browser/terminalConfigHelper.ts#L174-L175
Can we close the issue?

**Comment by Tyriar** [comment]
@antonioprudenzano thanks for the ping, yes this is fixed 👍
