### ISSUE TITLE
Custom colour for bottom bar

### ISSUE THREAD

**Issue by juanma-lora-pepephone** [microsoft/vscode#73885]
Issue Type: <b>Feature Request</b>

It could be nice if we could change the colour of the bottom bar. It helps to distinguish between opened projects in different windows.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.13.0-46-generic

**Comment by DNonov** [comment]
If you mean the **status bar** this may help you:
``` Json 
   "workbench.colorCustomizations": {
      "statusBar.background": "#5f00af",
      "statusBar.foreground": "#546789"
   }
```
Just adjust the colors and put it in your settings.json file.

**Comment by sbatten** [comment]
Thanks @DNonov
