### ISSUE TITLE
Quick open gives wrong result with uppercase letters

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#73881]
- VSCode Version: Insiders from today (17th May 2019)
- OS Version: OSX 10.14.4

Steps to Reproduce:

1. Open a large folder.
2. Press Ctrl-P
3. Type a filename that you know is in that folder and that you haven't opened recently.
4. It doesn't find the file.

Does this issue occur when all extensions are disabled?: Yes

Most of the time it just doesn't search at all (no progress bar), or I get the progress bar for ~2 seconds (way too short to search for all of the files in my huge workspace) and then "No result found..."

Is there any way to debug this? Also does `.gitignore` affect "Go to file..."?

**Comment by Timmmm** [comment]
Here's an example from LLVM:

![image](https://user-images.githubusercontent.com/376842/57923434-3326fa80-789a-11e9-90d5-8c79bb586afa.png)

But it finds some files perfectly well:

![image](https://user-images.githubusercontent.com/376842/57923464-4b971500-789a-11e9-8f77-37b3f27f450d.png)

**Comment by Timmmm** [comment]
It seems there is a setting `"search.useIgnoreFiles"` but I had actually already set it to `false`, so I don't think `.gitignore` is the issue.

**Comment by Timmmm** [comment]
Ok a colleague worked this out and it is really weird. It works fine if you start with a **lowercase** search string! Check it out, exactly the same situation but with lowercase:

![image](https://user-images.githubusercontent.com/376842/57936050-046d4c00-78bb-11e9-9096-506c8b87dfab.png)

**Comment by Timmmm** [comment]
Perhaps related to #12448.

**Comment by roblourens** [comment]
New regression, thanks

**Comment by Timmmm** [comment]
Thanks!
