### ISSUE TITLE
Display all typescript errors and warning of a folder/project

### ISSUE THREAD

**Issue by llgcode** [Microsoft/vscode#7388]
- VSCode Version: 1.2
- OS Version: Windows 7

It would be useful to have a separate command to display all errors and warnings (tslint) of a typescript project. Can't see how to do this in an integrated way.

**Comment by dbaeumer** [comment]
@llgcode you can setup up a task that runs tslint over the entire workspace using gulp, jake, or evem npm. 

Will move the issue to tslint since project validation support for tslint needs to be implemented there. For the TS compiler we do have a similar request.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-tslint#54

**Comment by llgcode** [comment]
Please can you show me the issue for ts compiler ?
thanks

**Comment by dbaeumer** [comment]
https://github.com/Microsoft/vscode/issues/7253. See section Explorations.
