### ISSUE TITLE
Path delimiters in ${workspaceFolder} and friends ...

### ISSUE THREAD

**Issue by g40** [microsoft/vscode#73888]
VS Code is a marvellous piece of work. Thanks.

One small feature request: It would be very useful to specify which path characters (`/` or `\`) were used when expanding macros such as `${workspaceFolder}`. 

The current default can be problematic in some scenarios - [https://github.com/microsoft/vscode-cpptools/issues/3627](https://github.com/microsoft/vscode-cpptools/issues/3627)

Thanks for listening.

**Comment by weinand** [comment]
Path delimiters in variables like `${workspaceFolder}` are defined by the OS where the folder is located.
In your case the path starts with the drive letter "R:" which confirms that the path is a Windows path. 
Why would a tool that can deal with drive letters choke on backslashes?
I think that the backslash issue needs to be fixed where it happens.
