### ISSUE TITLE
How to restart extension host

### ISSUE THREAD

**Issue by bardware** [microsoft/vscode#73895]
🚨 The issue tracker is not for questions 🚨
Some extension crashes and VSCode shows a dialog that offers to restart the `Extension host`. I do not click instantly and the popup vanishes.
How do I now restart extension host? Do I have to exit `code` and restart? Is there a menu?

**Comment by RMacfarlane** [comment]
@bardware You can bring the notification back by clicking on the bell in the corner:
![Screen Shot 2019-05-17 at 9 50 01 AM](https://user-images.githubusercontent.com/3672607/57943574-3796e780-7889-11e9-9b36-a09b0972bfaa.png)

Exiting code and restarting will also restart the extension host
