### ISSUE TITLE
Can we add an environmental variable when we fireup terminal so that the terminal session knows it's in a VS~ code environment?

### ISSUE THREAD

**Issue by fsw0422** [microsoft/vscode#73899]
for example, I run TMUX and i have a zsh config file saying launch tmux every time I open a terminal session. 

For Intellij, they have an environmental variable indicating that the terminal is running in intellij so I can disable tmux from firing up in intellij terminal.

**Comment by Tyriar** [comment]
See `$TERM_PROGRAM` and `$TERM_PROGRAMM_VERSION`

**Comment by fsw0422** [comment]
@Tyriar this only tells what app you are using. for example, I get `iTerm` on `$TERM_PROGRAM` that does not help if my terminal is opened in Intellij or VSCode

**Comment by Tyriar** [comment]
@fsw0422 I don't understand what you mean?

1. Launch iterm
2. `echo $TERM_PROGRAM` gives `iTerm.app` (expected)
3. Launch `code-insiders` from iterm
4. Open integrated terminal `echo $TERM_PROGRAM` gives `vscode` (as designed)

Am I misunderstanding?

**Comment by fsw0422** [comment]
sorry my bad. my terminal launches tmux by default and it didn't carry the `$TERM_PROGRAM` environment. thanx

**Comment by Tyriar** [comment]
Do you share your tmux session? If so then this is by design, tmux should inherit the environment fine if it's a new session.
