### ISSUE TITLE
Use variables inside tasks.json inputs config

### ISSUE THREAD

**Issue by donovanhiland** [microsoft/vscode#73896]
I'd love to be able to create an input variable in tasks.json which defaults to a predefined variable:

```
"inputs": [
  {
    "type": "promptString",
    "id": "filePath",
    "description": "Enter file path",
    "default": "${relativeFile}"
  }
]
```

however currently the default is literally `${relativeFile}`

**Comment by alexr00** [comment]
Duplicate of #64358
