### ISSUE TITLE
Improve update experience

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7389]
For me the daily (or even hourly) update notification in the insiders channel is not adding any value. I would like to just ditch this message when you are on the insiders channel. Depending on the platform, this has some consequences:

**Mac**: best experience, when you restart you just get the update. 

**Windows**: when you restart, the installer runs to do the update. OK if you expect it, otherwise might be confusing so we have to educate users.

**Linux**: since we do not have auto update, we could just hide the message and the user can go to the package manager to do the update when he wants.

@Microsoft/vscode ping for opinions.

**Comment by aeschli** [comment]
Yes, agree, the popup is too distracting.

**Comment by joaomoreno** [comment]
I really like this idea. We would:

- never show the update popup again
- automatically update on startup, if available

**Comment by weinand** [comment]
It would be great it if there was a "Downgrade to previous" in case something is seriously broken in the latest.

**Comment by stevencl** [comment]
I agree, the popup is distracting. But I am not sure about automatically applying the update, especially if it could lead to breakages. There have been some issues recently with other products that automatically apply updates...

Many products show a message box on launch to communicate that an update is available. Once that is dismissed it never shows up again. This is still distracting but when we are releasing daily updates that haven't been fully tested I think it might be better to let the user know before we apply an update. Many people (especially those with bad network connections) get annoyed when they don't have control over when an app uses their network. 

We could also have yet another setting that allows the user to choose whether or not to automatically apply updates.

**Comment by joaomoreno** [comment]
@weinand Supporting that opens many doors. I'd rather we jump on the issue, fix it and publish an update instead.

**Comment by joaomoreno** [comment]
> We could also have yet another setting that allows the user to choose whether or not to automatically apply updates.

👍

**Comment by AaronFriel** [comment]
I would be a proponent of never seeing the message and having it automatically update in the background. That's how evergreen ought to be, yeah?

**Comment by rebornix** [comment]
I'm eager to see that there is no popup window anymore, Besides, it would be perfect if the Windows binary doesn't require admin privilege (just a wish, not ask for it as I know there must be some limits).

I have Insider build on both my devbox and laptop, so the first thing to do everything during coffee time is manually re-installing VS Code twice. We may want to put this issue in the backlog to make true vscode-windows-insider users life easier.

**Comment by Rubenisme** [comment]
Would be nice to get a feature like Google Chrome has. Apparently [this](https://github.com/google/omaha) is how they do it on Windows.

**Comment by joaomoreno** [comment]
Closing this as this is too generic. Improving the Windows update is coming.
