### ISSUE TITLE
VSC is not passing the language in a new window

### ISSUE THREAD

**Issue by angel-luis** [microsoft/vscode#73893]
Issue Type: <b>Bug</b>

By default, I've set the language to Spanish.

When I open a new window, the new window is opened in English, not in Spanish.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
dotenv|mik|1.0.1
vscode-jade-snippets|mrm|1.0.1
vscode-language-pack-es|MS-|1.34.2
python|ms-|2019.4.12954
csharp|ms-|1.19.1
colonize|vms|2.2.2

</details>

**Comment by dbaeumer** [comment]
@angel-luis after you have changed the language you need to close all VS Code Windows as restart it. The UI language can not be changed dynamically and not for new Windows with an active running VS Code.

If this is not the case for you, can you provide the exact steps you do when seeing this?

**Comment by angel-luis** [comment]
I tried to replicate again the case several times but all the times passed the language properly. So for me this can be closed.

But, I'm not aware to did it changing the language without reload. I always have the Spanish language in the program, since it's provided as an extension.

**Comment by dbaeumer** [comment]
Thanks for getting back. I will close the issue then. 

Just to clarify again: a reload is not the same as a restart.

**Comment by angel-luis** [comment]
It happened again. It was after update VSC.

I opened a new window, and it was in English instead of Spanish.

**Comment by dbaeumer** [comment]
@angel-luis do you use --locale=de to set the language or do you configure Spanish in the UI itself. What is the language of your operating system.

**Comment by angel-luis** [comment]
SO in spanish and the Spanish language extension from Microsoft.

**Comment by dbaeumer** [comment]
So no configuration (it could have been https://github.com/microsoft/vscode/issues/75241 otherwise). And everything is fine I guess after a close of VS Code and then a reopen. It only happens during the update

**Comment by angel-luis** [comment]
Yes, after the three last updates, I confirm that its caused by the update.
