### ISSUE TITLE
Tree: setting for clearing filter when focused

### ISSUE THREAD

**Issue by rossvz** [microsoft/vscode#73891]
I constantly use the Outline view, and specifically the keybinding to quickly focus on the outline view. However, the outline view persists the previous filters on focus, which is a really inefficient workflow. Ideally this could be a preference/setting that gets toggled. I would love for every time I hit the keyboard shortcut to focus the outline view and start typing, I'm starting with a fresh input.

For now, I've changed the keybinding I would use to trigger "Outline focus" and bound that to "Go To Symbol" which DOES clear previous input on each re-focus

**Comment by joaomoreno** [comment]
@jrieken I wouldn't make this a tree thing (ie. make **programmatic** calls to `focus()` always clear the filter). Could we have this for Outline?
