### ISSUE TITLE
ctrl+D selection doesn't work

### ISSUE THREAD

**Issue by mukerong** [microsoft/vscode#73898]
- VSCode Version: 1.32.3
- OS Version: Windows 1- Enterprise Version 1709

Hello,

ctrl+d for same text selection doesn't work. It happened before several times, and it happened more often now. It works and suddenly doesn't work. Restart VSCode can fix but it is annoying. There is no sign or specific actions trigger this dysfunction. It happened randomly.

Does this issue occur when all extensions are disabled?: Yes

Thanks,
Rachel

**Comment by alexandrudima** [comment]
@mukerong What exactly does not work? Is the keybinding not working? Are you aware that `ctrl+d` honours the match case & whole words settings from the find widget ?
