### ISSUE TITLE
Change matching HTML tag when either is edited

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode#73907]
This is a re-open of #43402. (The conversation for the prior issue is locked.) It is worth looking into whether the extension system supports implementing this feature effectively. In the year plus since that issue was created, no one has created a working extension to implement the feature.

There is an extension, [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag), that tries to do this, but it only works if you type slowly (formulahendry/vscode-auto-rename-tag#62) and has lots of issues reported for high CPU load. I don't know if it's a matter of the developer knowing how to use the VS Code API correctly or the API not supporting well what the extension is trying to do.

This issue requests that the VS Code team look into (1) making sure a suitable extension is practical to develop and (2) making such an extension available.

**Comment by octref** [comment]
We talked internally a bit on this. Makes sense to make this built-in.
We'd likely need some incremental parsing before this can take place.

**Comment by aeschli** [comment]
dup of #76619

**Comment by breyed** [comment]
#76619 is about CSS and looks to me to be distinct from this issue, which is about HTML close tags (which CSS doesn't even have). @aechan Can you elaborate on the dup?

**Comment by octref** [comment]
@aeschli Linked to wrong issue? Should be dup of this one: https://github.com/microsoft/vscode/issues/47069

**Comment by aeschli** [comment]
sorry for that, thanks for the correction
