### ISSUE TITLE
Open Recent initially blank

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode#73902]
Issue Type: <b>Bug</b>

If you create a new VS Code instance and quickly press Alt+F, R, the Open Recent menu has no folders or files. If you try agian in a few seconds, it works. This isn't acceptable, however. The first thing you often do after opening VS Code is open a recent folder. The list of recent items and their paths only takes a few hundreds or thousands of bytes. There's no reason that it shouldn't be accessible so quickly (a few milliseconds) that it's always faster than the human. Worst case is that the Open Recent should show a progress indicator while the data loads, or if that's too much work, just block the UI. If it blocks long enough for the user to notice, then the data isn't stored efficiently enough.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|2.1.1
vscode-markdownlint|Dav|0.26.0
githistory|don|0.4.6
gitlens|eam|9.7.4
git-project-manager|fel|1.7.1
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1

</details>

**Comment by sbatten** [comment]
@breyed I am not able to reproduce this behavior. This issue has been reported in the past on older versions of VS Code but it has since been addressed. Are you reproducing this on 1.34? If so, can you help nail down a consistent repro?

**Comment by breyed** [comment]
The generated version info in the bug report is correct; it is 1.34. The problem is tricky to reproduce. After a system restart, it reproed twice, but on the third and subsequent attempt to open VS Code, the recent items appeared.

If you can fix the key buffering bug (#73988), you can likely repro by making an AutoHotKey script to automated launching the app and pressing the keys. Otherwise, if you add test code to call [SendInput](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-sendinput) for the Alt+F and R immediately after the main menu is created, I would expect that to repro the issue.

**Comment by sbatten** [comment]
@breyed can you verify your `window.titleBarStyle` setting?

**Comment by breyed** [comment]
It's the default: custom. The behavior when the title bar style is native may provide a clue. If you type Alt+F, R during load, the Alt+F is picked up from the buffer; however, the R is missed.

If you keep hitting R, when the Recent menu eventually does open, it is fully populated; however, that just due to the difficulty of reproing the issue.

**Comment by sbatten** [comment]
we haven't seen reports of this, not sure if it still reproduces. if it still causing problems, we can re-open
