### ISSUE TITLE
Write File Error

### ISSUE THREAD

**Issue by prgodwin** [microsoft/vscode#73908]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I keep getting this write  error message when running Visual Studio Code:

"C:\Program Files\Microsoft VS Code\unins000.exe
An error occurred while trying to create a file in the destination directory:
Access denied.
Click Retry to try again; Ignore to skip this file (not recommended) or Abort to cancel installation."

Selecting the "Abort" option is the only one removes the error message.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.84GB (22.30GB free)|
|Process Argv|C:\Users\PERRYGODWIN\Documents\CV_Wizard\On-the-Bench_Worksheet_Perry_Godwin_2019-05-16.txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.45.0
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.2

</details>

**Comment by joaomoreno** [comment]
@prgodwin Can you show me a screenshot of the error?
