### ISSUE TITLE
Open containing folder does not working on Kubuntu 19.04

### ISSUE THREAD

**Issue by nguyen14ck** [microsoft/vscode#73901]
- VSCode Version: 1.34
- OS Version: Kubuntu 19.04

Steps to Reproduce:

1. Open VSCode Project in Kubuntu 19.04
2. Click on "Open Containing Folder" of Context menu

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@nguyen14ck I don't quite follow your repro steps. Can you either add more details or share a gif of your experience?

**Comment by radium-v** [comment]
Same issue here, Kubuntu 19.04 with Visual Studio Code 1.35.1.

Here are clearer reproduction steps:
1. Open a folder in a Visual Studio Code workspace
2. Right-click a file in the sidebar and select "Open Containing Folder" (this label is specific to Linux systems, on MacOS and Windows it is different!)
3. Nothing happens.

I've seen people suggest adding `inode/directory=org.kde.dolphin.desktop;` or similar lines to their `~/.config/mimeapps.list` but this doesn't have any effect.
