### ISSUE TITLE
Terminal Problems

### ISSUE THREAD

**Issue by EvgeniVasilev** [microsoft/vscode#73906]
Information about VS Code Version and Windows: 
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open Terminal 
Looks normal:
![base](https://user-images.githubusercontent.com/4688971/57948636-dbfd4600-78ea-11e9-85b5-26e9b0afea53.PNG)
2. Start Typing
Looks Odd:
![bad](https://user-images.githubusercontent.com/4688971/57948975-c2103300-78eb-11e9-924d-0d36f06d70b3.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by EvgeniVasilev** [comment]
Thank you, for quick response!
