### ISSUE TITLE
Allow TreeItem to revive serialized Uri

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode#73909]
I'm building an extension that would like to serialize icon Uris using the memento object so that I can later restore them without parsing on startup. However, TreeItem.iconPath does not seem to accept the object restored from the memento which forces me to needlessly parse my stored Uris. Since the api does not expose any methods to revive Uris, I believe it is necessary for the TreeItem to do the conversion. I'm basing this assumption on the fact that WebviewPanel.iconPath does accept Uris in serialized form and that this functionality is expected behavior. If this feature request doesn't seem like a good idea, could the api instead expose the Uri.from or Uri.revive methods?

**Comment by jrieken** [comment]
> WebviewPanel.iconPath does accept Uris in serialized form and that this functionality is expected behavior

That would be oversight or un-intended feature - we don't specify how uris are serialised and therefore we don't expose revive. You can use `toString` and `parse` to deal with externalised uris and that's a good option

**Comment by diabolicle** [comment]
If that isn't the intended behavior then I'll close the issue. I just thought that since I'm loading a bunch of unique icons it would be more efficient to skip the parsing, but since I haven't run into any problems with `parse` I guess this isn't worth pursuing.
