### ISSUE TITLE
IntelliSense slow as sticking

### ISSUE THREAD

**Issue by huanhexiao** [microsoft/vscode#73903]
Issue Type: <b>Bug</b>

IntelliSense is the worst feature i ever see, i remember at least two big issues:
======
1. It takes long long long time to jump to functions' definations, load suggestions, just as it sticks;
2. Further more, it costs much ram(more 1gb) when jumping to definations or loading suggestions;
3. if i F12 two funcitons in a short time interval, it appears two IntelliSenses, this ooubles the ram costs. You can imagine if i open two Codes or more, i can do nothing else.
======
Such issue exsits in each version i use, including the latest. 
Fix it, please !

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1850)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|7.67GB (0.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
mdmath|goe|2.3.9
todo-tree|Gru|0.0.132
comment-translate|int|1.4.1
vscode-language-pack-zh-hans|MS-|1.34.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-icons|vsc|8.6.0
crs-al-language-extension|wal|1.1.3

</details>

**Comment by mjbvz** [comment]
What language are you using?

/needsMoreInfo

**Comment by huanhexiao** [comment]
> What language are you using?
> 
> /needsMoreInfo

C++

**Comment by alexr00** [comment]
In that case, this issue should be filed on the C++ tools extension.

**Comment by huanhexiao** [comment]
> In that case, this issue should be filed on the C++ tools extension.

actually,i removed the cpp intellisense extension,the issue isn't gone.

**Comment by alexr00** [comment]
VS Code doesn't provide any go to definition for C++ without installing an extension, so it has to be an extension 😊. It seems likely that you have another extension installed that is providing this. Perhaps ms-vscode.cpptools.

**Comment by huanhexiao** [comment]
> VS Code doesn't provide any go to definition for C++ without installing an extension, so it has to be an extension . It seems likely that you have another extension installed that is providing this. Perhaps ms-vscode.cpptools.

Yeah, i have such an extension, thank u for your answer.
Sorry for my late reply
