### ISSUE TITLE
"Close Folder" menu option gets disabled for all open windows if used in one of them

### ISSUE THREAD

**Issue by StasD** [microsoft/vscode#73900]
- VSCode Version: 1.34 (the issue was present in 1.33 as well)
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Open some folder in VS Code.
2. Choose File -> New Window. In the new window, open another folder.
3. Select File -> Close Folder in one of the windows.
4. Go to another window. Now, if you want to select File -> Close Folder, you won't be able to, as this option would be disabled.

Does this issue occur when all extensions are disabled?: Don't know

**Comment by StasD** [comment]
VS Code is now at 1.38.0. The problem still there...

**Comment by sbatten** [comment]
@StasD thanks for resurfacing

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/2710db93e2378dd7d9cba121960195a16678195e
