### ISSUE TITLE
Command for keybindings to input specific characters (like utf-8)

### ISSUE THREAD

**Issue by ceymard** [Microsoft/vscode#7390]
- VSCode Version: any ?
- OS Version: Mac OSX

This is not really a bug ; is there a command that would allow me to define a keyboard shortcut that would enter specific text ?

The reason is I want to use a utf-8 character in my text that my keyboard can't produce (ᐅ to be exact). I had it bound on ctrl+shift+o in Sublime text thanks to a command "insert" that takes `"args": {"characters": "ᐅ"}` in the key bindings.

It seems there is no such command. Is there another way ? Should this command be created ?

**Comment by alexandrudima** [comment]
We don't support assigning arguments to commands when defining a keybinding, today the only option is to write an extension, but I like the idea as a general mechanism.

**Comment by franklinyu** [comment]
Another use case: I want to map curly quotes `“”` on Windows to <kbd>Alt</kbd> <kbd>[</kbd> and <kbd>Alt</kbd> <kbd>Shift</kbd> <kbd>[</kbd>, same as on macOS.

**Comment by alexandrudima** [comment]
It is possible to do the following via `keybindings.json`:

```
    {
        "key": "alt+2",
        "command": "type",
        "args": { "text": "“"}
    }
```
