### ISSUE TITLE
All blue seems purple (not only status bar)

### ISSUE THREAD

**Issue by filipetoyoshima** [microsoft/vscode#73910]
Issue Type: <b>Bug</b>

1. Open VSCode
2. See anything that should be blue (status bar, link highlights, icons, images preview...)
3. Feel strange with color rendering.

Note that is not a duplicate of #27538. *Everything* is with some weird color.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-47-generic

**Aditional OS info**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Aditional info that may help**
When stalling Chrome, I've found a very similar problem, all links, and other blue things, including images, was rendering some color that seems more purple than blue. To solve this, I set a flag `Force Color Profile` to `sRGB` on chrome://flags/. I couldn't find some similar option in VSCode settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/29482983/57952430-9e38f700-78c3-11e9-9549-f8c9460d65bd.png)
Above is Chrome rendering images on a GitHub Readme section, above is VSCode previewing the same `README.md`.

-----
![image](https://user-images.githubusercontent.com/29482983/57952559-025bbb00-78c4-11e9-9f15-947acdeca4e2.png)
At left, an image I've found on Google Images, at right, my VSCode.

---
![image](https://user-images.githubusercontent.com/29482983/57957629-4dc99580-78d3-11e9-94cc-5a8b51b64d91.png)

---
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2361)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.71GB (0.22GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-prolog|art|0.8.23
color-info|bie|0.5.1
react-native-react-redux|EQu|2.0.3
language-haskell|jus|2.6.0
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
vscode-react-native|msj|0.9.3
material-icon-theme|PKi|3.7.0
git-file-history|pom|1.0.1

</details>

I've tested `code . --disable-extensions` and still the same.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by filipetoyoshima** [comment]
It's is working propperly!

![image](https://user-images.githubusercontent.com/29482983/58041527-b0f33c00-7b0e-11e9-9731-8034ec0b1423.png)

Obs: tested only on Linux, I have no access to a Windows or macOS.
