### ISSUE TITLE
#else is confused with the C++ else keyword

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#73912]
Issue Type: <b>Bug</b>

Type #else and watch the suggestions list

![else_snippet_bug](https://user-images.githubusercontent.com/13824553/57956109-b2252e80-78ac-11e9-9fea-4c78b7529688.PNG)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
vscode-cudacpp|kri|0.1.1
cpptools|ms-|0.23.1
code-settings-sync|Sha|3.2.9
perforce|sle|3.2.0

</details>

**Comment by alexr00** [comment]
Only reproduces with the C/C++ extension installed. Please file the issue in their repo!
