### ISSUE TITLE
Settings AND OTHER windows background color

### ISSUE THREAD

**Issue by cyraid** [microsoft/vscode#73917]
As far as I've searched for, I can't seem to find how to set a different background color for windows that don't have an editor? There is editor.background and editorGroup.emptyBackground, but a setting to have a color for windows like the settings window, etc.

Can you please not slap a "editorGroup.emptyBackground", and not close the issue assuming it actually satisfied the feature request. :)

For example, the release notes have my very specific code colors, which make the most sense with code, not generic window colors.

There should be at least color settings for generic window textmate rules for window colors bgColor, and fgColor (for text), then use the actual code colors when having code areas. Perhaps one for headers as well? At this point I'd pretty much be happy with fgColor and bgColor for windows.

**Comment by bpasero** [comment]
You can use `editorGroup.emptyBackground` for that.

**Comment by cyraid** [comment]
No, this is not a question.. Sorry, I apparently am not being straight forward enough, and I don't think you are reading my **FEATURE REQUEST** very well. The functionality is NOT IMPLEMENTED by VSCODE currently, and I am ASKING for this FUNCTIONALITY.

Sorry, but this is the second time you've done this, without reading the issue entirely.

`editorGroup.emptyBackground` DOES NOT .. I repeat .. **DOES NOT** change the settings window background, OR the extensions background.

Please take off the question tag, and perhaps add a feature request.
