### ISSUE TITLE
clone時にpasswordが表示されない

### ISSUE THREAD

**Issue by Medical-Tribune-DevOpsTeam** [microsoft/vscode#73926]
1. terminalに接続
2. コマンドラインにてssh
3. gitでclone　<git clone URL>
4. usernameとpasswordを聞かれるが、passwordを打っても表示されない
ただし、打ってenterするとclone自体は可能

多分、powershellの問題かも

**Comment by byyxx128** [comment]
English please...

**Comment by tech201823** [comment]
セキュリティ上の観点からパスワードが実際に見えていないだけで、実際は打てています。
