### ISSUE TITLE
VSCode command for showing Comments panel

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#73920]
When an extension adds comments, the extension should be able to show the Comments panel to bring users' attention to them.

It will be very helpful to have something like VSCode command `workbench.actions.view.comments` that would show up the Comments panel.

**Comment by rebornix** [comment]
`workbench.action.focusCommentsPanel` was added to support focusing into the Comments Panel, it only works when there is comment controller registered.
