### ISSUE TITLE
Labelling Files in the Workspace

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#73929]
Is there a feature in which any file in the workspace could be labelled(or tagged) with particular keywords for easy reference later? 

Say, for example I have 100 files in my workspace, where there are files on which no further progress is needed, some which require quick fixes, and others on which work needs to be done. 
Each of these files may have different priorities; Multiple files might require the same fix(like for example, new language features etc.)

So if a file was labelled (just as how GitHub has this labels feature) and files could be searched according to their labels(like GitHub's issue search), it would simplify my work a lot more.

Currently, I save filenames with their labels in a separate file, and modify labels accordingly, but this could be simplified a lot if this feature was implemented.

Some labels : Completion Status:Completed, Priority:High, Priority:Low, ...(custom labels should also be allowed) 

Please take this idea into consideration!

**Comment by isidorn** [comment]
Sounds like a great idea for an extension that would contribute a new viewlet and keep the files there.
