### ISSUE TITLE
Crash when viewing Changelog of various extensions

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#73925]
Issue Type: <b>Bug</b>

1. Go to Extensions tab.
2. Double-click an extension (happened with johnstoncode.svn-scm and vscode-ext.sync-rsync).
3. Click Changelog.
4. App spins for a few seconds then crashes.

I opened #69550 with the same issue. It got closed, but it still happens all the time.

Crash report: [crash.zip](https://github.com/microsoft/vscode/files/3193530/crash.zip)

There's nothing in the console when I start VS Code again after the crash.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.1
vscode-intelephense-client|bme|1.0.14
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
mustache|daw|1.1.1
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.7.4
vscode-npm-script|eg2|0.3.7
vscode-powertools|ego|0.41.1
php-debug|fel|1.13.0
vscode-pull-request-github|Git|0.6.0
vscode-favorites|how|1.4.0
svn-scm|joh|1.48.4
vscode-apache|mrm|1.2.0
python|ms-|2019.4.12954
debugger-for-chrome|msj|4.11.3
java|red|0.45.0
vscode-hexdump|sle|1.7.2
slack|soz|0.0.14
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.2
sync-rsync|vsc|0.34.7
jinja|who|0.0.8

</details>

**Comment by sandy081** [comment]
@jacobweber Does it happen when you have all extensions disabled?
