### ISSUE TITLE
Diff file in UTF-16LE

### ISSUE THREAD

**Issue by RainmakerUA** [microsoft/vscode#73922]
Issue Type: <b>Bug</b>

File is shown in ASCII/UTF8

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vsc-rustfmt|Con|0.1.0
vscode-markdownlint|Dav|0.26.0
gitlens|eam|9.7.4
vsc-material-theme|Equ|2.8.2
cpptools|ms-|0.23.1
powershell|ms-|1.12.1
rust|rus|0.6.1
wow-bundle|Sep|1.3.0
crates|ser|0.4.3
rust-pack|Swe|0.2.15
vscode-lua|tri|0.12.4

(2 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/1702751/57962557-e5a1a080-7920-11e9-8bb8-2975f0c1a183.png)

**Comment by joaomoreno** [comment]
#48038
