### ISSUE TITLE
vscode wont remove old file when update extension

### ISSUE THREAD

**Issue by Cologler** [microsoft/vscode#73927]
- VSCode Version: 1.34.0 (user setup)
- OS Version: win 10

ref: #62347

![Snipaste_2019-05-18_11-24-33](https://user-images.githubusercontent.com/10906962/57963981-b65e5400-795f-11e9-8fb1-028b7e896915.png)

And my `.obsolete` file:

``` json
{
    "grapecity.gc-excelviewer-2.1.31":true,
    "ms-python.python-2019.3.6352":true,
    "ms-vsliveshare.vsliveshare-1.0.67":true,
    "eamodio.gitlens-9.7.3":true
}
```

`.obsolete` has not changed even restart vscode.

**Comment by sandy081** [comment]
@Cologler Are you sure these are not removed after restarting VS Code

**Comment by Cologler** [comment]
Yes, I am sure.

**Comment by sandy081** [comment]
@Cologler Can you please do following

- Quit VS Code
- Start VS Code in verbose mode from command prompt `code --verbose`
- Open the Shared process logs `F1 > View: Open View > Log (Shared Process)`

Please check in the logs if there are any requests to delete outdated or uninstalled extensions folders?
