### ISSUE TITLE
Search file too slowly now.

### ISSUE THREAD

**Issue by yanhuiinf** [microsoft/vscode#73931]
Issue Type: <b>Bug</b>

When I use earlier version 1.2x, the performance of the search file is in time, but it is slower and slower now. Some times, it will be always searching. But the file will be searched in the second time.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by lightyaer** [comment]
The search is too slow for huge projects, Its the only thing that takes me to webstorm.
Please add indexing of projects.

**Comment by roblourens** [comment]
Nothing has changed substantially with search in quite a long time so I'm not sure what you're seeing. Are you talking about text search or file search (quick open)? Can you explain some more?

**Comment by lightyaer** [comment]
I'm talking about text search throughout the repo/project, the file search(cmd/ctrl + p) works fine, the search in a file(cmd/ctrl + f) works fine, but search a keyword throughout the project(shift + cmd/ctrl + f) is very slow for huge projects.
Expectation is to be snappy like file search.

**Comment by roblourens** [comment]
When you start a text search, do you see a process named MsMpEng.exe taking lots of CPU?

**Comment by yanhuiinf** [comment]
I'm talking about file quick search(cmd/ctrl + p), sometimes, when I input a filename, the waiting progress bar is always visible and never stop, finally, nothing was searched. But when you cancel the searching and input it again, the file was listed. I must say that my project 's code-volume is barely changed during the vscode versions.

**Comment by lightyaer** [comment]
@roblourens 
> When you start a text search, do you see a process named MsMpEng.exe taking lots of CPU?

I'm using a mac, I see `rg` in CPU section in Activity Monitor while doing a keyword search(shift + cmd/ctrl + f)
In the memory section, I see `Code helper` taking alot of memory

**Comment by roblourens** [comment]
@lightyaer clearly you are talking about a different issue entirely, please open your own issue.

@yanhuiinf Can you see whether the tips here help at all? https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
