### ISSUE TITLE
Make debugger use cache

### ISSUE THREAD

**Issue by loftusa** [microsoft/vscode#73939]
I'm not sure if there's a way to do this that I just haven't found

I have a data analysis pipeline written in Python that takes a long time to run, and every time I set a breakpoint near the end of the program it takes 10 minutes to get to that point.

It would be nice to see a cache for the debugger, such that you only have to run a long program once, and then you can debug parts near the end without having to wait 10 minutes for each debugging session to start.

Not sure if there's already a way to do this or how technically feasible it is :)

**Comment by weinand** [comment]
Debuggers are not part of VS Code. They are extensions. 

So a "debugger cache" for Python would have to be a feature of the Python debugger. So you might want file a feature request against the Python extension.

However, I do not think that the Python extension will implement such a feature anytime soon...

I suggest that you structure your data analysis pipeline in a way that allows to store intermediate results in files. With that approach you can debug parts at the end without having to process all the data again.
