### ISSUE TITLE
When installing extensions cause Xorg process CPU to use soaring

### ISSUE THREAD

**Issue by fcharlie** [Microsoft/vscode#7393]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Open Visual Studio Code
2. Install Extension, such as C/C++
   ![2016-06-08 16-43-27](https://cloud.githubusercontent.com/assets/6904176/15888168/746480ee-2d98-11e6-98f5-e1350cf24a35.png)

**Comment by joaomoreno** [comment]
@fcharlie We recently changed the UI concerning this. It is already available in our insiders release: https://code.visualstudio.com/insiders

Can you check whether you still have this issue there?

**Comment by fcharlie** [comment]
@joaomoreno When install c/c++ ext, This problem still exists。
![2016-07-07 10-23-18](https://cloud.githubusercontent.com/assets/6904176/16640699/e224e3c6-442c-11e6-9863-37ca4c137431.png)


I think This problem is most likely caused by Xorg and Nodejs

**Comment by joaomoreno** [comment]
Is this the UI you saw when installing the extension?

![image](https://cloud.githubusercontent.com/assets/22350/16646051/5f959274-4428-11e6-9eac-dfdb8f450414.png)

**Comment by fcharlie** [comment]
@joaomoreno  Yes。

**Comment by joaomoreno** [comment]
@fcharlie Is this still an issue?

**Comment by fcharlie** [comment]
@joaomoreno fixed tks.
