### ISSUE TITLE
Function Name Drop down Request

### ISSUE THREAD

**Issue by vijaynet10** [microsoft/vscode#73932]
Everything looks good in VS Code . Function Name Drop down required at Type Script editors window like visual studio. Navigation between function also required.

**Comment by sbatten** [comment]
@vijaynet10 are you referring for a way to navigate a file by symbols? This is possible with Ctrl+Shift+O or the outline view

**Comment by gjsjohnmurray** [comment]
@vijaynet10 you might also want to toggle breadcrumbs on. See the View menu. Then look at the top of your open documents for the breadcrumb trail.

**Comment by vijaynet10** [comment]
@sbatten sbatten , @gjsjohnmurray thanks for the response , great work..
