### ISSUE TITLE
Add option to disable animations in the status bar

### ISSUE THREAD

**Issue by rnarkk** [microsoft/vscode#73944]
Every time I edit my code this spins and I've found it disturbing visually or just mentally which makes me less inclined to write code. I need to focus on the logic rather than such visual effect.

<img width="255" alt="Screenshot 2019-05-19 at 2 05 25" src="https://user-images.githubusercontent.com/13822753/57972903-66bd6e00-79db-11e9-904b-8bd1ec03a32c.png">

Then I would suggest that we change 🔄with ⏺.
Thanks

**Comment by misolori** [comment]
@rnarkk is this an overall reaction to any animations?

**Comment by rnarkk** [comment]
@misolori It was in particular to the animation above. If I would abstract that I say 1) when you're concentrating on coding, 2) unintentionally triggered 3) repetitive animation can be mentally 
 disturbing.

**Comment by misolori** [comment]
@rnarkk would disabling animations in the status bar help? That’s one of the only places where use animations.

**Comment by rnarkk** [comment]
@misolori Yes, certainly. I would appreciate it.

**Comment by misolori** [comment]
@bpasero we only use the spinning animation on the sync icons (for git and remote) but other extensions can use it as well. We should look into adding an option to disable animations.

**Comment by bpasero** [comment]
Yes we can think of a setting, though I would only add this if more people complain. As a workaround, https://github.com/microsoft/vscode/issues/3874 will allow you to hide the item altogether.

**Comment by dequation** [comment]
Having this issue as well. Every time I some code and pause, a little animation runs under the imported libraries in the 'Outline'-bar.

Being very sensitive to visual movement, it distracts mightily. Adding an option to disable all  animations would be a lifesaver.
