### ISSUE TITLE
Formatting Problems

### ISSUE THREAD

**Issue by RaspberryPeach** [microsoft/vscode#73941]
Dear Mr./Ms.

I think there is formatting problems in Visual Studio Code.

If the file I'm trying to access is located in NAS or Google Drive, formatting function is malfunctioning.
But access files which located in my computer, there is no problem.

Problems were identified in the following environments:
Test file: C or CPP

Access environment: 
Synology Nas via CloudStation or File explorer
Google Drive via RaiDrive
Remote access to another computer(Uniquely, not applicable in all cases)

**Comment by rebornix** [comment]
@aeschli do you have any idea about this one?

**Comment by aeschli** [comment]
Can you give describe what the problem is? No formatting applied? No format action available?
What about other editing operations? Do they work?

**Comment by RaspberryPeach** [comment]
@aeschli Finally, I knew what the problem was. The problem was Synology Cloud Station Drive(The program that synchronizes pc and nas). What's unusual is that there's no problem with other programs.

The following programs did not cause problems:
Visual Studio 2017
Visual Studio 2015 
intelliJ

Tested with the following file:
c, cpp, .java

It seems to be an error if open files with Visual studio code via Synology Cloud Station Drive.

![12](https://user-images.githubusercontent.com/45388022/58447733-5fffcb00-8140-11e9-8455-7f19535b6fac.png)
*There was nothing in the output window.

**Comment by aeschli** [comment]
What formatter do you use?
I checked, we don't have such a error message in VSCode.

**Comment by RaspberryPeach** [comment]
I use C/C++ made by microsoft.

![123](https://user-images.githubusercontent.com/45388022/58473555-d5d95600-8183-11e9-8cb3-0041a824f08f.png)

**Comment by aeschli** [comment]
Thanks for the information. It's an error reported by the C++ extension that has a underlying tto that does the formattimg.
Similar issue here: https://github.com/Microsoft/vscode-cpptools/issues/3271
Can you file this against CPP?

Can you test if the same problem appears for JSON or HTML files?

**Comment by RaspberryPeach** [comment]
Thank you for your continued interest. 

I don't know exactly what the problem was, but in my case, I solved the problem by reinstalling VS code.
