### ISSUE TITLE
Startup very slow or how to activate/load extension for specific file type

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#73945]
- VSCode Version: v1.34.0
- OS Version: macOS 1.13.6

Steps to Reproduce:

1. Install some extension
2. Restart VS Code

Does this issue occur when all extensions are disabled?: Yes. Faster by 2+ times, but still not fast as older versions (when i first tried in 2017, it was been very fast, almost same as Sublime, but now it's isn't)

Here my logs:
```
## System Info

* Code: 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758)
* OS: darwin(17.7.0)
* CPUs: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz(4 x 2500)
* Memory(System): 8.00 GB(0.05GB free)
* Memory(Process): 302.93 MB working set(0.00MB peak, 237.58MB private, 65.05MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                    | Duration | Process          | Info                    |
| ------------------------------------------------------- | -------- | ---------------- | ----------------------- |
| start => app.isReady                                    | 306      | [main]           | initial startup: true   |
| nls:start => nls:end                                    | 3        | [main]           | initial startup: true   |
| require(main.bundle.js)                                 | 448      | [main]           | initial startup: true   |
| app.isReady => window.loadUrl()                         | 925      | [main]           | initial startup: true   |
| window.loadUrl() => begin to require(workbench.main.js) | 1259     | [main->renderer] | NewWindow               |
| require(workbench.main.js)                              | 1400     | [renderer]       | cached data: YES        |
| require & init workspace storage                        | 50       | [renderer]       | -                       |
| init workspace service                                  | 69       | [renderer]       | -                       |
| register extensions & spawn extension host              | 2634     | [renderer]       | -                       |
| restore viewlet                                         | 205      | [renderer]       | workbench.view.explorer |
| restore panel                                           | 83       | [renderer]       | workbench.panel.output  |
| restore editors                                         | 1128     | [renderer]       | 1: PerfviewInput        |
| overall workbench load                                  | 1775     | [renderer]       | -                       |
| workbench ready                                         | 5770     | [main->renderer] | -                       |
| extensions registered                                   | 7720     | [renderer]       | -                       |

## Extension Activation Stats

| Extension                                   | Eager | Load Code | Call Activate | Finish Activate | Event                                 |
| ------------------------------------------- | ----- | --------- | ------------- | --------------- | ------------------------------------- |
| vscode.debug-auto-launch                    | true  | 6         | 1             | 58              | *                                     |
| vscode.emmet                                | true  | 10        | 5             | 53              | *                                     |
| vscode.git                                  | true  | 60        | 5             | 652             | *                                     |
| vscode.merge-conflict                       | true  | 8         | 4             | 58              | *                                     |
| 2gua.rainbow-brackets                       | true  | 8         | 15            | 43              | *                                     |
| christian-kohler.path-intellisense          | true  | 41        | 1             | 42              | *                                     |
| cssho.vscode-svgviewer                      | true  | 99        | 1             | 41              | *                                     |
| dbaeumer.vscode-eslint                      | true  | 20        | 17            | 23              | *                                     |
| EditorConfig.EditorConfig                   | true  | 72        | 2             | 21              | *                                     |
| esbenp.prettier-vscode                      | true  | 189       | 67            | 39              | *                                     |
| hitode909.zentabs                           | true  | 22        | 0             | 39              | *                                     |
| joelday.docthis                             | true  | 187       | 1             | 38              | *                                     |
| kisstkondoros.vscode-gutter-preview         | true  | 440       | 18            | 20              | *                                     |
| PKief.material-icon-theme                   | true  | 15        | 0             | 33              | *                                     |
| Shan.code-settings-sync                     | true  | 67        | 1             | 244             | *                                     |
| spywhere.guides                             | true  | 527       | 17            | 2               | *                                     |
| wayou.vscode-todo-highlight                 | true  | 5         | 2             | 0               | *                                     |
| vscode.configuration-editing                | false | 16        | 3             | 20              | onLanguage:jsonc                      |
| vscode.extension-editing                    | false | 51        | 2             | 15              | onLanguage:markdown                   |
| vscode.json-language-features               | false | 40        | 20            | 0               | onLanguage:jsonc                      |
| vscode.markdown-language-features           | false | 53        | 13            | 2               | onLanguage:markdown                   |
| vscode.typescript-language-features         | false | 43        | 86            | 71              | onLanguage:javascript                 |
| christian-kohler.npm-intellisense           | false | 65        | 0             | 71              | onLanguage:javascript                 |
| DavidAnson.vscode-markdownlint              | false | 5         | 2             | 0               | onLanguage:markdown                   |
| ms-kubernetes-tools.vscode-kubernetes-tools | false | 2368      | 74            | 205             | onView:extension.vsKubernetesExplorer |
| ms-vscode.vscode-typescript-tslint-plugin   | false | 9         | 1             | 116             | onLanguage:javascript                 |
| redhat.vscode-yaml                          | false | 126       | 25            | 0               | onView:extension.vsKubernetesExplorer |
| shinnn.stylelint                            | false | 3169      | 11            | 59              | onLanguage:javascript                 |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1558203764218	0	0
main:appReady	1558203764524	306	306
nlsGeneration:start	1558203764565	41	347
nlsGeneration:end	1558203764568	3	350
willLoadMainBundle	1558203764569	1	351
didLoadMainBundle	1558203765017	448	799
main:loadWindow	1558203765449	432	1231
renderer/started	1558203766646	1197	2428
willShowPartsSplash	1558203766660	14	2442
didShowPartsSplash	1558203766678	18	2460
willLoadWorkbenchMain	1558203766708	30	2490
didLoadWorkbenchMain	1558203768108	1400	3890
main/startup	1558203768108	0	3890
willInitWorkspaceService	1558203768141	33	3923
willInitWorkspaceStorage	1558203768152	11	3934
didInitWorkspaceStorage	1558203768202	50	3984
didInitWorkspaceService	1558203768210	8	3992
willStartWorkbench	1558203768213	3	3995
LifecyclePhase/Ready	1558203768218	5	4000
willRestoreEditors	1558203768860	642	4642
willRestoreViewlet	1558203768860	0	4642
willRestorePanel	1558203768892	32	4674
didRestorePanel	1558203768975	83	4757
willResolveExplorer	1558203769013	38	4795
didRestoreViewlet	1558203769065	52	4847
willLoadExtensions	1558203769304	239	5086
didRestoreEditors	1558203769988	684	5770
LifecyclePhase/Restored	1558203769988	0	5770
didStartWorkbench	1558203769988	0	5770
didResolveExplorer	1558203770252	264	6034
extensionHostReady	1558203771856	1604	7638
didLoadExtensions	1558203771938	82	7720
LifecyclePhase/Eventually	1558203776982	5044	12764
```

**Comment by jrieken** [comment]
@dalisoft Can you try to run `code --prof-startup` and attach the profiles here?

**Comment by dalisoft** [comment]
## System Info

* Code: 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758)
* OS: darwin(17.7.0)
* CPUs: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz(4 x 2500)
* Memory(System): 8.00 GB(1.48GB free)
* Memory(Process): 279.95 MB working set(0.00MB peak, 207.92MB private, 72.04MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                    | Duration | Process          | Info                                       |
| ------------------------------------------------------- | -------- | ---------------- | ------------------------------------------ |
| start => app.isReady                                    | 150      | [main]           | initial startup: true                      |
| nls:start => nls:end                                    | 1        | [main]           | initial startup: true                      |
| require(main.bundle.js)                                 | 254      | [main]           | initial startup: true                      |
| app.isReady => window.loadUrl()                         | 607      | [main]           | initial startup: true                      |
| window.loadUrl() => begin to require(workbench.main.js) | 595      | [main->renderer] | NewWindow                                  |
| require(workbench.main.js)                              | 1407     | [renderer]       | cached data: NO                            |
| require & init workspace storage                        | 31       | [renderer]       | -                                          |
| init workspace service                                  | 53       | [renderer]       | -                                          |
| register extensions & spawn extension host              | 2242     | [renderer]       | -                                          |
| restore viewlet                                         | 93       | [renderer]       | workbench.view.explorer                    |
| restore panel                                           | 0        | [renderer]       | -                                          |
| restore editors                                         | 929      | [renderer]       | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                  | 1296     | [renderer]       | -                                          |
| workbench ready                                         | 4138     | [main->renderer] | -                                          |
| extensions registered                                   | 5867     | [renderer]       | -                                          |

## Extension Activation Stats

| Extension                                 | Eager | Load Code | Call Activate | Finish Activate | Event                 |
| ----------------------------------------- | ----- | --------- | ------------- | --------------- | --------------------- |
| vscode.debug-auto-launch                  | true  | 7         | 1             | 74              | *                     |
| vscode.emmet                              | true  | 41        | 3             | 71              | *                     |
| vscode.git                                | true  | 192       | 3             | 340             | *                     |
| vscode.merge-conflict                     | true  | 24        | 2             | 71              | *                     |
| 2gua.rainbow-brackets                     | true  | 2         | 6             | 65              | *                     |
| christian-kohler.path-intellisense        | true  | 22        | 1             | 64              | *                     |
| cssho.vscode-svgviewer                    | true  | 68        | 0             | 64              | *                     |
| dbaeumer.vscode-eslint                    | true  | 76        | 7             | 57              | *                     |
| EditorConfig.EditorConfig                 | true  | 70        | 2             | 55              | *                     |
| esbenp.prettier-vscode                    | true  | 470       | 17            | 38              | *                     |
| hitode909.zentabs                         | true  | 8         | 0             | 38              | *                     |
| joelday.docthis                           | true  | 861       | 0             | 38              | *                     |
| kisstkondoros.vscode-gutter-preview       | true  | 1330      | 4             | 34              | *                     |
| PKief.material-icon-theme                 | true  | 22        | 0             | 60              | *                     |
| Shan.code-settings-sync                   | true  | 201       | 0             | 118             | *                     |
| spywhere.guides                           | true  | 1212      | 25            | 10              | *                     |
| wayou.vscode-todo-highlight               | true  | 5         | 1             | 9               | *                     |
| vscode.typescript-language-features       | false | 175       | 707           | 79              | onLanguage:javascript |
| christian-kohler.npm-intellisense         | false | 53        | 0             | 80              | onLanguage:javascript |
| mgmcdermott.vscode-language-babel         | false | 2         | 0             | 80              | onLanguage:javascript |
| ms-vscode.vscode-typescript-tslint-plugin | false | 12        | 0             | 104             | onLanguage:javascript |
| shinnn.stylelint                          | false | 177       | 4             | 75              | onLanguage:javascript |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1558438389256	0	0
main:appReady	1558438389406	150	150
nlsGeneration:start	1558438389409	3	153
nlsGeneration:end	1558438389410	1	154
willLoadMainBundle	1558438389411	1	155
didLoadMainBundle	1558438389665	254	409
main:loadWindow	1558438390013	348	757
renderer/started	1558438390572	559	1316
willShowPartsSplash	1558438390578	6	1322
didShowPartsSplash	1558438390579	1	1323
willLoadWorkbenchMain	1558438390608	29	1352
didLoadWorkbenchMain	1558438392015	1407	2759
main/startup	1558438392016	1	2760
willInitWorkspaceService	1558438392043	27	2787
willInitWorkspaceStorage	1558438392051	8	2795
didInitWorkspaceStorage	1558438392082	31	2826
didInitWorkspaceService	1558438392096	14	2840
willStartWorkbench	1558438392098	2	2842
LifecyclePhase/Ready	1558438392107	9	2851
willRestoreEditors	1558438392464	357	3208
willRestoreViewlet	1558438392464	0	3208
willResolveExplorer	1558438392535	71	3279
didRestoreViewlet	1558438392557	22	3301
willLoadExtensions	1558438392881	324	3625
didRestoreEditors	1558438393393	512	4137
LifecyclePhase/Restored	1558438393393	0	4137
didStartWorkbench	1558438393394	1	4138
didResolveExplorer	1558438393831	437	4575
extensionHostReady	1558438395061	1230	5805
didLoadExtensions	1558438395123	62	5867
LifecyclePhase/Eventually	1558438396581	1458	7325
```
[prof-dca3.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/3202282/prof-dca3.extHost.cpuprofile.txt)
[prof-dca3.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/3202283/prof-dca3.main.cpuprofile.txt)
[prof-dca3.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/3202284/prof-dca3.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
I agree things are slow but nothing stands up as being particularly slow. Something fishy is that cached data isn't used but that might be related to a known issue with Electron. There a bunch of extensions that load quite slowly but outside our control. Closing without action.

**Comment by dalisoft** [comment]
Okay, thanks for describe. Latest update even slower. I love times where VSCode has been on the one of fastest IDE :)
