### ISSUE TITLE
extension child process exits with code 127

### ISSUE THREAD

**Issue by Ayanrocks** [microsoft/vscode#73940]
- VSCode Version: 1.34.1
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. add a worker process to an extension
2. Run the worker it will exit

Does this issue occur when all extensions are disabled?: Yes

However this used to work on code v1.30.2 on the december 2018 version. And after January the worker process exits with code 127. Any Help?

**Comment by Ayanrocks** [comment]
Know what the issue is @sandy081

**Comment by Ayanrocks** [comment]
@alexandrudima Know what the issue is?

**Comment by Ayanrocks** [comment]
Any progress @alexandrudima ?

**Comment by Ayanrocks** [comment]
Any updates? @alexandrudima

**Comment by alexandrudima** [comment]
@Ayanrocks I don't understand your issue. What are the steps to reproduce?

**Comment by Ayanrocks** [comment]
Create an extension and create a child process from the main extension.ts
file. The worker will exit with code 127. This used to work before January
2019 version of vscode.

**Comment by alexandrudima** [comment]
There are countless features in VS Code that depend on being able to spawn a process from an extension. Here is me selfhosting and seeing 4 processes spawned and working from extensions:

- json language server
- 2 x typescript language servers
- TS Lint server

![image](https://user-images.githubusercontent.com/5047891/62138654-43bb0e80-b2e8-11e9-9129-4b8563f5cf32.png)

**Comment by Ayanrocks** [comment]
Well I am trying to use solc compiler and it is not working on worker
process after January update. Any major changes there.
P.s which app screenshot is that to track processes?

**Comment by alexandrudima** [comment]
Yes, the January release contained an Electron update, which contained a nodejs upgrade. See https://code.visualstudio.com/updates/v1_31#_nodejs-update

![image](https://user-images.githubusercontent.com/5047891/62140136-ba590b80-b2ea-11e9-9069-1967e9cffdd3.png)

See https://nodejs.org/en/blog/release/v10.0.0/#deprecations

Perhaps you were using some node API that was deprecated in node v10 ?
