### ISSUE TITLE
remote-ssh: jupyter server not starting for Python Interactive Window

### ISSUE THREAD

**Issue by hofimax** [microsoft/vscode#73943]
I am using remote-SSH to connect to an Azure Ubuntu 18.04 VM.
I want to execute a python script in Python Interactive Window.
VSCode is stuck at "Starting Jupyter Server" with "Python Extension: Getting jupyter server options ..." being the last log item in the developer console.

Steps to Reproduce:

Ubuntu Setup:
- create Ubuntu 18.04 VM
- add sudoer user
- install Anaconda3-2019.03 in /opt/anaconda
- conda create --name azureml python=3.7 pylint
- conda activate azureml
- try to execute any line in python script (.py file) with "run selection/line in Python Interactive Window"

![image](https://user-images.githubusercontent.com/2486593/57971840-d0b22500-7993-11e9-890d-d0343cd395b7.png)

![image](https://user-images.githubusercontent.com/2486593/57971848-e7f11280-7993-11e9-8e70-d378e857beb2.png)

Version: 1.35.0-insider (user setup)
Commit: 6ac87465f297a9068bf767f45d6f372fc5697de9
Date: 2019-05-17T17:48:07.036Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by geevi** [comment]
I am also getting the same problem.

**Comment by AlekseiMalkov** [comment]
I'll second this. It used to work till couple of days ago..

**Comment by rogerjbos** [comment]
Did anyone ever figure this out?  I am having the same problem.

**Comment by IanMatthewHuff** [comment]
@rogerjbos Insiders build 1.35 had an issue with remote development using webviews (which is what the python interactive window uses)

The tracking issue is here:
https://github.com/microsoft/vscode-remote-release/issues/376

Seems like a fix might just have been put in.

**Comment by rogerjbos** [comment]
Thanks Ian.  I just updated and tested it and it works.
