### ISSUE TITLE
hotkeys don't work

### ISSUE THREAD

**Issue by Rahkovsky** [microsoft/vscode#73949]
Issue Type: <b>Bug</b>

When I try to set my own hotkeys (Rub Selection in the Terminal) it does not work. Cntr or Alt are not regonized. Don't know what to do

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
graphviz-preview|EFa|1.3.2
r|Iku|1.0.9
latex-workshop|Jam|7.0.0
python|ms-|2019.4.12954
dot|Ste|0.0.1

</details>

**Comment by Tyriar** [comment]
What's the keybinding that doesn't work? Where is your focus when it doesn't work?
