### ISSUE TITLE
Add link in "How-To-Contribute" to GitHub Fork Help Page

### ISSUE THREAD

**Issue by jamesralstin** [microsoft/vscode#73946]
In the <a href="https://github.com/Microsoft/vscode/wiki/How-to-Contribute">"How-To-Contribute"</a> wiki page under the <a href="https://github.com/Microsoft/vscode/wiki/How-to-Contribute#getting-the-sources">"Getting the sources"</a> subsection, recommending a hyperlink to the <a href="https://help.github.com/en/articles/fork-a-repo">"Fork A Repo"</a> GitHub article for users/developers that might be new to the term "Fork", albeit familiar with the concept. Also maybe a link to <a href="https://help.github.com/en/articles/cloning-a-repository-from-github">"Clone"</a> as well.

![InclusivityEnhancement](https://user-images.githubusercontent.com/37027037/57974028-b6158700-7966-11e9-9b79-48d6aa831d95.png)

**Comment by gregvanl** [comment]
Hi @jamesralstin Thank you for your suggestion. I'm reluctant to add links, that we would have to maintain if they move. Forking and cloning are part of the basic vocabulary of open-source development and I'd rather users searched and found their own guidance, which matches their level (beginner, advanced, refresher).
