### ISSUE TITLE
the vscode desktop icon  is  ugly

### ISSUE THREAD

**Issue by 392223903** [microsoft/vscode#73942]
future versions we should use configuration items to customize desktop icons

**Comment by AeonFr** [comment]
I like it

**Comment by albertofustinoni** [comment]
More than that, it still uses the Visual Studio 2017 icon template (which *is* ugly): why is VSCode not updating the icon to keep consistency?

**Comment by gjsjohnmurray** [comment]
Did you see #71827 ?

**Comment by albertofustinoni** [comment]
@gjsjohnmurray Just had a look at it. Love the new proposed icons :)

**Comment by misolori** [comment]
Thanks @gjsjohnmurray, and yes this is being tracked in #71827.
