### ISSUE TITLE
Maybe wrong error about confusing snippet-variables and snippet-placeholders

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#73956]
Issue Type: <b>Bug</b>

Hello, I am the creator of a very simple snippets for javascript extension.
I am getting the following error message while debuging my extension:

```
[danielo515.danielo-node-snippets]: One or more snippets from the extension 'danielo-node-snippets' very likely confuse snippet-variables and snippet-placeholders (see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details)
```

I double checked the snippets syntax and I'm sure it is correct. In fact, if I debug the extension all the snippets are available on any JS file, but when it get's plubished the ones using variables with the `${...}` syntax are not offered as an option. The same snippets also works if I add them as a personal snippet to my personal javascript.json extensions file.

You can see the extension snippets (just one fille) here: https://github.com/danielo515/vscode-node-snippets/blob/7920f445b5224c0f2a6a4ad3adb475178e9685c1/snippets/snippets.json#L58

I will be very grateful if you explain to me what is wrong because according to docs my snippets are correct.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (5.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
It's likely the `$object`, see https://github.com/danielo515/vscode-node-snippets/blob/7920f445b5224c0f2a6a4ad3adb475178e9685c1/snippets/snippets.json#L91

**Comment by danielo515** [comment]
Thanks for your answer @jrieken, but according to documentation that syntax is correct for placeholders:
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables

> When a variable is unknown (that is, its name isn’t defined) the name of the variable is inserted and it is transformed into a placeholder.

Maybe that is not supported anymore and you must use existing variables or placeholders? But that is for sure not what documentation says.

**Comment by jrieken** [comment]
That's to be understood as mitigation in the presence of such unknown variables (and the reason for the warning). For some time we wrongly supported that syntax (which isn't valid Textmate) If at a future point `$object` becomes a variable, your snippet will change and that's why we want to migrate snippets to the correct syntax.

**Comment by danielo515** [comment]
Yes, I totally understand. But the fact that it is supported on normal snippet files but disabled on extensions is what is confusing. I don't have a problem now that I know it, but probably it could confuse other people. Maybe if you add a more concrete message about this on the docs or on the error message (eg, unknown variable used...)

Regards
