### ISSUE TITLE
Git pull from ssh URL should prompt for password

### ISSUE THREAD

**Issue by devvpm** [microsoft/vscode#73951]
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

When I do git pull using UI option from my ssh URL it shows the below error. 

![image](https://user-images.githubusercontent.com/1164077/57977049-91321a00-7a21-11e9-8c6f-b63585e954b5.png)

However, when I do from the terminal it shows that message from the server and asks for the password, 
![image](https://user-images.githubusercontent.com/1164077/57977096-2b469200-7a23-11e9-9ec2-893f64238c9a.png)

So, while doing git pull using git pull option from menu it should prompt like this - 

![image](https://user-images.githubusercontent.com/1164077/57977085-e0c51580-7a22-11e9-98ff-e81a8c6e0328.png)

**Comment by joaomoreno** [comment]
#13680
