### ISSUE TITLE
UnderLine shown as a white space

### ISSUE THREAD

**Issue by ali-abz** [microsoft/vscode#73957]
Issue Type: <b>Bug</b>

In terminal, UnderLines are shown as white spaces and there is no way to distinct them with each other.
I am using Ubuntu 18.04 and installed vscode with snap package. I didn't changed the default font setting.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-50-generic snap

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
format-python-docstrings|ian|1.0.0
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
code-spell-checker|str|1.7.10

</details>

**Comment by ali-abz** [comment]
here is a preview of  this problem:
![Screenshot from 2019-05-19 12-51-03](https://user-images.githubusercontent.com/23415604/57979576-00fdd000-7a35-11e9-8782-17e0ce8b44ad.png)

**Comment by BradGunnerSGT** [comment]
So this is an issue that has been around for over 2 years and no one has actually fixed it?

**Comment by Tyriar** [comment]
@BradGunnerSGT I've been trying to fix it in my spare time with https://github.com/xtermjs/xterm.js/pull/1790, it's not as trivial as it seems though.
