### ISSUE TITLE
Breakpoint problem by having two file with same name

### ISSUE THREAD

**Issue by aminlatifi** [microsoft/vscode#73955]
Issue Type: <b>Bug</b>

Hi,

I have two files with name http.c, and I put breakpoint on a line in one of them. When I try to debug, debugger does not stop on specified line. Instead, it stops on a line in other http.c file

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 2805)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (0.90GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bro|aep|0.5.1
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
vscode-perl|cfg|1.18.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
systemd-unit-file|coo|1.0.3
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
githistory|don|0.4.6
gitlens|eam|9.7.4
vscode-npm-script|eg2|0.3.7
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
yara|inf|1.3.5
presentationmode|jsp|1.1.5
solidity|Jua|0.0.56
node-module-intellisense|lei|1.5.0
autoconf|mae|0.0.9
vscode-clang|mit|0.2.3
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
cpptools|ms-|0.23.1
Go|ms-|0.10.2
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.21.0
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.7.0
java|red|0.45.0
vscode-sort-json|ric|1.13.0
partial-diff|ryu|1.4.0
vscode-status-bar-format-toggle|tom|1.5.0
vscode-icons|vsc|8.6.0
vim|vsc|1.8.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by weinand** [comment]
Please file this issue against the C/C++ extension.
