### ISSUE TITLE
Python Jupyter:The "Run Cell | Run Above | Run below" is shaking when coding

### ISSUE THREAD

**Issue by ZhiYuanZeng** [microsoft/vscode#73950]
[record_of_problem.zip](https://github.com/microsoft/vscode/files/3205082/record_of_problem.zip)

- VSCode Version:1.33.1
- OS Version:

Steps to Reproduce:

1.activate python extension
2.types #%% in .py file
3.code in the new cell, the line "Run Cell | Run Above | Run below" keeps shaking

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
Not sure what that means? Can you attach a recording? Can you try with latest version?

**Comment by ZhiYuanZeng** [comment]
> Not sure what that means? Can you attach a recording? Can you try with latest version?
I'm sorry I failed to give a clear description, and I upload a record of  the problem. The version is the latest, but the problem still exists.

**Comment by jrieken** [comment]
That looks funny... Can you try to reproduce with latest stable 1.34 or insiders 1.35?

**Comment by ZhiYuanZeng** [comment]
The current version is already the latest(1.34). Does that condition only  happens on me? That's terrible

**Comment by jrieken** [comment]
> The current version is already the latest(1.34). Does that condition only happens on me? That's terrible

You initially [reported](https://github.com/microsoft/vscode/issues/73950#issue-445770400) this against 1.33.1. I guess that means it reports for both versions. And yeah, seems like you are the only one setting this

**Comment by jrieken** [comment]
not actionable, closing
