### ISSUE TITLE
Some C++ Code Crashes Insider

### ISSUE THREAD

**Issue by Blaok** [microsoft/vscode#73952]
## Version and Environment
|Key|Value|
|-|-|
|Version| 1.35.0-insider (user setup)|
|Commit| 6ac87465f297a9068bf767f45d6f372fc5697de9|
|Electron| 3.1.8|
|Chrome| 66.0.3359.181|
|Node.js| 10.2.0|
|V8| 6.6.346.32|
|OS| Windows_NT x64 10.0.17763|

The stable build doesn't have the same issue and two days ago this problem wasn't present in the insider build (I have been upgrading pretty frequently in the insider channel).

## Steps to Reproduce

1. Save the following in a `foo.cpp`
```C++
struct A {
 private:
  explicit A(B *p) : p(std::experimental::coroutine_handle<B>::from_promise(*p)) {
  }
};
```
2. Open the file with vscode

## Expected behavior
I can edit the file.
## Actual behavior
The whole window is stuck and not responding to any of my input. After a while, it will prompt to reopen or close the window. A single CPU core is running 100% for vscode. I am not seeing any output in the chromium debugging console.

## Does this issue occur when all extensions are disabled?
Yes. I have tried to launch vscode with `--disable-extensions` and the problem remains the same.

**Comment by cyliang** [comment]
I also encounter this problem today. Is there a workaround?

**Comment by matter123** [comment]
This was fixed upstream at https://github.com/jeff-hykin/cpp-textmate-grammar in version 1.8.15, see https://github.com/jeff-hykin/cpp-textmate-grammar/issues/174

The fix should make it to vscode insiders the next time the grammars are updated. If you need the fix now you can install https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax&ssr=false

**Comment by cyliang** [comment]
@matter123 Thanks. This fixed the problem for me.

**Comment by Blaok** [comment]
Thanks!
