### ISSUE TITLE
\Users\Student\AppData\Local\Temp\vscode-inno-update-1558259159.log

### ISSUE THREAD

**Issue by LEONGV** [microsoft/vscode#73966]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
@LEONGV It looks like you are trying to report an issue regarding update. You will want to upload you log file as an attachment.

**Comment by LEONGV** [comment]
please help.
what should I do to update my visual code?

**Comment by joaomoreno** [comment]
Please fully remove VS Code and manually reinstall.
