### ISSUE TITLE
Python increases tabsize in file with for loop in function

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/vscode#73969]
- Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-15-generic

Steps to Reproduce:

1. Python file.
2. The default tabsize used is `Spaces: 4`
3. However when opening a file that has a `for` loop within a function definition, the tabsize is increased to `Spaces: 8`

example code:
```
li = [1, 2, 3]
def do():
    for i in li:
        pass
```
when opening a file with the above code, the tab size will be 8 spaces.

**Comment by yankyhoffman** [comment]
The issue is occuring with `python` files, not `javascript` (although I didn't test it with `js`)

**Comment by pkkid** [comment]
You're not alone. This is happening for me as well, very annoying as I need to set the options back to 4 spaces with pretty much every file I open. Is there anyway to force it for all python files?

**Comment by yankyhoffman** [comment]
Got the issue now with any file that defines a docs string with the quotation marks and content on the same column as follows:
```
"""
some content
"""
```

**Comment by pkkid** [comment]
I added this to my settings to force myself around the issue. I don't really deal with Python files that have different tab sizes, but it this solution won't be ideal for anyone that does.

```python
    "[python]": {
        "editor.detectIndentation": false,
        "editor.tabSize": 4,
        "editor.insertSpaces": true,
    },
```

**Comment by yankyhoffman** [comment]
Thanks, didn't think of the `editor.detectIndentation` setting

**Comment by rebornix** [comment]
No longer see this issue in latest version.
