### ISSUE TITLE
Typescript duplicate import autocomplete

### ISSUE THREAD

**Issue by BuckAMayzing** [microsoft/vscode#73965]
I haven't been able to find anyone mentioning the same issue. If I manually type an import statement, I get a duplicate line showing what I've already typed. This happens when hitting Enter, Tab, or clicking on the auto complete suggestion. See below for an explanation:

```
import React // Suggestion shows up at this point in the autocomplete dialog
```
I then press Enter, and here are the results:
```
import React from 'react';
import React
```
My settings file has a few things in it, but I've gone through each one, so I don't think it's a configuration issue. Any ideas? Is this a known issue?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

/needsMoreInfo

**Comment by BuckAMayzing** [comment]
I went through this and forgot to update the ticket. My mistake. It seems to be related to the [TypeScript Importer](https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter) extension. Thanks for taking a look though!
