### ISSUE TITLE
Sometimes starts syntax highlighting in the middle of a block comment

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#73967]
VSCode will sometimes stop treating a comment as a comment and start syntax highlighting it in the middle of the block. I've noticed this occasionally in both Python and JavaScript. This particular time, it happened after formatting the document by selecting all and formatting selection.

The effect looks like this: 
![image](https://user-images.githubusercontent.com/2294248/57985291-afa11100-7a33-11e9-803d-e0933a9015bc.png)

Upon inspecting with the developer tools, this is the HTML behind it:
![image](https://user-images.githubusercontent.com/2294248/57985284-98faba00-7a33-11e9-8cc0-e107cc0294d0.png)

I was able to resolve the issue by inserting a new line in the comment at that point and then removing the line.

**Comment by hinell** [comment]
May be there are plugins that handle JSDoc like comments? Have you tried to turn them off?

**Comment by mjbvz** [comment]
I can't reproduce this issue. Can you please test this in [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled).

If you still see problems, please share some example code (as text).
