### ISSUE TITLE
CSS Formatter

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#73971]
Hello VS Code crew

I see VS Code can formatting html, json, js, but can't do it with css, scss. It is possible to make it native too?

Of course i know there is a lot of add-ons in marketplace, but if you support html or js formatter, maybe it a good idea to support css, scss too ?

It always better to have native functions. Add-ons often fail

**Comment by octref** [comment]
Try https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode.
