### ISSUE TITLE
In terminal, a way to show a folder in the sidebar, e.g. hyperlink folder paths

### ISSUE THREAD

**Issue by benliddicott** [microsoft/vscode#73972]
It would be great to have some method of selecting a folder in the sidebar, from the terminal.

### Suggestion: Hyperlink folder names. If clicked, the folder would be selected in the sidebar.

Paths to valid files are hyperlinked, and a Ctrl+Click opens the file. The folder is then selected in the sidebar. I often find myself doing a `find .` to get a file I can click to open the folder.

### Suggestion: provide a command-line interface to control the GUI

e.g. `vscode open $PATH`

* If $PATH is a regular file, would open it as if from Menu->File->Open.
* If $PATH is a folder, would select it in the sidebar.

Users could then open the current terminal folder by typing `vscode open .`

**Comment by Tyriar** [comment]
> Hyperlink folder names. If clicked, the folder would be selected in the sidebar.

I like this suggestion 👍
