### ISSUE TITLE
Why the "edit button" in setting.json can't work?

### ISSUE THREAD

**Issue by yichengsu** [microsoft/vscode#73977]
Issue Type: <b>Bug</b>

I remember when clicking the edit button in setting.json , it will create a copy in the side where you can edit, but now it seems not to do that.
And I have reinstalled the latest version while clean the config files, It still can't work.
![GIF](https://user-images.githubusercontent.com/13522803/57992912-3b28a980-7ae9-11e9-9c4f-15d7ce653524.gif)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.60GB free)|
|Process Argv|C:\Users\suyic\Desktop|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.9
matlab|Gim|1.1.0
latex-workshop|Jam|7.0.0
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
vscode-paste-image|mus|1.0.4
vscode-hexdump|sle|1.7.2
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.3.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Hm, you should see a context menu show up when you click the pencil. Are you seeing context menus other places? e.g if you right click in the editor, does the context menu show up?

**Comment by yichengsu** [comment]
Just like this, when I click the pencil, the Edit alert will disappear. 
![GIF](https://user-images.githubusercontent.com/13522803/58065266-b6589100-7bb7-11e9-8af1-72acf5999176.gif)

Does the context mean it will give a true/false box that I can choose directly? I remember that was the case before. But it seems not to appear now.
![未命名1558408059](https://user-images.githubusercontent.com/13522803/58065585-d50b5780-7bb8-11e9-93d6-d66cd4eb9b45.png)

**Comment by roblourens** [comment]
Yes that's what should happen

**Comment by roblourens** [comment]
Did it start working?

**Comment by yichengsu** [comment]
Yes, Thanks a lot~

**Comment by imba-tjd** [comment]
So how did you solve it? I have the same issue.

**Comment by imba-tjd** [comment]
Left click is broken but right click works. It's introduced in 1.34.0. I can reproduce it by installing 1.31.1 and 1.40.0 respectively in my VM. Occurs when all extensions are disabled.

```
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:53.881Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 6.1.7601

CPUs	Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (4 x 2494)
GPU Status	2d_canvas: enabled
checker_imaging: disabled_off
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: unavailable_off
surface_synchronization: enabled_on
video_decode: enabled
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	2.00GB (1.01GB free)
Process Argv	
Screen Reader	no
VM	33%
```
