### ISSUE TITLE
Visual Studio code does not appear in the mac dock

### ISSUE THREAD

**Issue by Trannosaur** [microsoft/vscode#73978]
Issue Type: <b>Bug</b>

It happens consistently. Across reboots. It's bizarre. It just isn't there. (Yes the app is open... obviously)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 12, 9|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv|-psn_0_73746|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
node-debug2|ms-|1.31.2
vscode-react-native|vsm|0.9.2

</details>

**Comment by gjsjohnmurray** [comment]
@Trannosaur please look at #63068

If that issue matches yours, there's a workaround there. I suggest you close this one and maybe watch the other one.
