### ISSUE TITLE
Branch panel not auto close when lose focus

### ISSUE THREAD

**Issue by yubaoquan** [microsoft/vscode#73979]
- VSCode Version: 1.34.0
- OS Version: win10 family 17134.765

Steps to Reproduce:

1.Click the branch button on left bottom of vscode to open the branch panel.
2.Click other place

Expected behavior: branch panel close
Actual behavior: branch still visible

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@yubaoquan I'm not quite understanding what panel to which you are referring. Can you provide a screenshot?

**Comment by yubaoquan** [comment]
![xxx4](https://user-images.githubusercontent.com/2340296/58013105-81e9c400-7b28-11e9-9f86-649b2b9ab451.jpg)

**Comment by gjsjohnmurray** [comment]
@yubaoquan - I'm not one of the VSCode devs but my guess is, it's intentional that this dialog doesn't disappear as soon as you focus away from it, because you might want to look somewhere else for information to help you make your choice. Pressing the Esc key will close it.

**Comment by joaomoreno** [comment]
This is intentional.
