### ISSUE TITLE
Keys not buffered at startup

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode#73988]
Issue Type: <b>Bug</b>

Keystrokes that are pressed when VS Code is starting are lost. Windows has a built-in mechanism for preserving keystrokes for when the UI thread is busy, and it works in almost all apps, including when they are starting up, but it doesn't work for startup keystrokes in VS Code.

Repro:
1. Start VS Code.

2. As the spash screen is displayed, press Alt+F, R. **-or-** After the spash screen is displayed, but while the app is laying itself out, press Alt+F, R.

3. In either case, when the app is ready, the expected behavior is that the File > Open Recent menu is opened. However, pressing the keys have no effect.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
gitstash|art|2.1.1
spellright|ban|3.0.38
vscode-markdownlint|Dav|0.26.0
githistory|don|0.4.6
gitlens|eam|9.7.4
git-project-manager|fel|1.7.1
ginfuru-vscode-jekyll-syntax|gin|0.1.0
vscode-jekyll-snippets|gin|0.9.1
vscode-css-peek|pra|2.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by breyed** [comment]
When using the custom title bar style, Alt+F and R are missed. When using the native title bar style, Alt+F is accepted, but R are missed.

**Comment by Tyriar** [comment]
Not sure we can do anything about this as the components listening for key presses aren't hooked up until the individual components (like monaco) are loaded?

@breyed switching the title bar to native will fix the issue there `"window.titleBarStyle": "native"`

**Comment by breyed** [comment]
@Tyriar I mentioned my experience with a native title bar in an earlier comment. It improved, but did not fix, the issue.
> When using the native title bar style, Alt+F is accepted, but R are missed.

**Comment by breyed** [comment]
As to the fix, I would expect that if in the native bootstrapper, you can hold off on the call to [DispatchMessage](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-dispatchmessage) until the initial components are loaded, the keystrokes would get picked up. I haven't looked into the code or design at all, though. Just speaking generally based on my experience with Win32.
