### ISSUE TITLE
open a .cc file(2000 lines) window will be blocked and no response

### ISSUE THREAD

**Issue by leeaction** [microsoft/vscode#73982]
Issue Type: <b>Bug</b>

1. open folder with remote-ssh
2. open a .cc file such as render_frame_impl.cc(in chromium project)

and then the window will be blocked and no response

VS Code version: Code - Insiders 1.35.0-insider (a5536b8f5a16a10d859f3dec1e59701671bf069e, 2019-05-20T05:15:57.974Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (7.11GB free)|
|Process Argv|-psn_0_340051|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.31
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
vscode-gn|npc|1.0.0

</details>

**Comment by matter123** [comment]
This was fixed upstream at jeff-hykin/cpp-textmate-grammar in version 1.8.15, see jeff-hykin/cpp-textmate-grammar#174

The fix should make it to vscode insiders the next time the grammars are updated. If you need the fix now you can install marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax&ssr=false

**Comment by leeaction** [comment]
> This was fixed upstream at jeff-hykin/cpp-textmate-grammar in version 1.8.15, see [jeff-hykin/cpp-textmate-grammar#174](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/174)
> 
> The fix should make it to vscode insiders the next time the grammars are updated. If you need the fix now you can install marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax&ssr=false

Thank you  It's worked..
