### ISSUE TITLE
Visual Studio Profile

### ISSUE THREAD

**Issue by rasoulian** [microsoft/vscode#73981]
Issue Type: <b>Feature Request</b>

Dear Microsoft,

The @vscode needs to add user's profile, save user settings to load next installing.

Many thanks.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
@rasoulian Not sure if I understand your request. Can you please elaborate in detail?

**Comment by joehbenti** [comment]
A user profile like in android studio... the user can save/sync their setting/extensions etc 

We need this Feature @VScode @microsoft
