### ISSUE TITLE
Settings UI coule be improved

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#73983]
Issue Type: <b>Bug</b>

I'm trying to use Settings UI to change some settings. I believe this is one of the fundamental features/parts of this app. However, it's very hard to use the Settings UI easily.

## Finding settings is hard

I noticed that recently you removed the split pane settings, where default settings were visible in the left pane, and user-defined settings in the right pane. I couldn't find default settings at all after this. I found them only after asking online. Is this how you intended this to be used? I doubt.

I re-enabled split-pane. However, the UI is unintuitive.

## Starting search works differently

When working in split pane, and I want to search, after pressing CMD+F, a new, special "settings search" appears on top, searching the default settings in the left pane. The usual behavior (and for me expected behavior) is to search in the current pane, the pane where my cursor is. Whether it's default settings pane or user-settings pane is left for user to decide.

Fine, I'll have to remember how to use this specific search box.

## Searching filters items

So I continue searching. I find the setting I'm looking for and now I want to select, copy and paste the setting into the user-defined settings so that I can modify its value. Normally, everywhere else in the editor, and in many other apps, the text I searched for gets selected and, after I press ESC, the focus goes to the text editor and selected text.

I press ESC, to stop searching and focus on the default settings pane. However, this changes the UI, since pressing ESC cleared the search input. This also loses the search result somewhere in the huuuuge default settings JSON file.

Ok, another thing to remember: don't press ESC like you usually do. You have to  move your mouse and click and select the setting you want, while the search input is still open.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.2
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
LogFileHighlighter|emi|2.5.0
prettier-vscode|esb|1.9.0
vscode-markdown-todo|fab|1.1.0
vscode-projects-plus|fab|1.22.0
vscode-language-babel|mgm|0.0.22
ruby-rubocop|mis|0.8.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
vscode-versionlens|pfl|0.23.0
ruby|reb|0.22.3
code-settings-sync|Sha|3.2.9
stylelint|shi|0.49.0
code-spell-checker|str|1.7.10
ada-lightbulb|vfo|0.3.2

</details>

**Comment by roblourens** [comment]
Thanks for the feedback. First, there is some general discussion about the split json editor here: https://github.com/microsoft/vscode/issues/68386. Default settings can still be found in intellisense when typing in settings.json, or in the settings GUI, or there is a command to show the default settings.

I agree in general about some of your feedback about the split json editor but that editor is considered deprecated now so I am not going to be changing it.

**Comment by vfonic** [comment]
I hope you do read what other users wrote in there.

> Default settings can still be found in intellisense when typing in settings.json, 

Are you serious? You're proposing the users to find the "API" for settings they want to change, by blindly typing in and reading autocomplete suggestions?

> or in the settings GUI

Settings GUI is an issue of its own. Since I don't use it (I gave up after failing to figure out how to use it), I won't comment on that, but for me, it doesn't work. And I don't think I'm the issue here. There have been thousands of settings/preference panes. The one in VS Code is one of the worst ones I've ever used.

> or there is a command to show the default settings.

...that I discovered by searching online. Or should I read the manual before starting to use VS Code? What's the first-time scenario? "User opens the app, presses CMD+SHIFT+P and runs Open Default Settings command"? 🤔 


> I agree in general about some of your feedback about the split json editor but that editor is considered deprecated now so I am not going to be changing it.

Which editor is not deprecated now? The "you only get to see blank `{}` JSON the first time you open VS Code settings? That's the non-deprecated one?
I simply can't understand it. I've seen some bad UI, but this is beyond my comprehension.

**Comment by roblourens** [comment]
The first run experience is using the GUI, which is simply a list of every setting available. I'm happy to discuss whatever issue you have with that. The user will only find the JSON if they go looking for it and I consider it an "advanced" feature for power users.

Intellisense also gives you simply a list of every setting available which you can filter if you want. And they can open the JSON list if that's what they prefer. So it seems like we are still giving people several ways to do this.

**Comment by vfonic** [comment]
@roblourens you're right. I'll switch back to Settings UI and report back what were my issues with using it. I just prefer the JSON, because I'm a developer. And I believe most of VS Code users are. (duh! 😁)
Thanks for following up!
