### ISSUE TITLE
when using powershell in terminal.integrated.shell.windows the terminal text is highlighted in white

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#73984]
Issue Type: <b>Bug</b>

**To reproduce:** 
in setting.json, set `"terminal.integrated.shell.windows":  "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"` then launch a python file. In the termainl the text will be highlighted in white (very hard to read).

I asked [this question on stack exchange](https://superuser.com/questions/1438893/vscode-how-to-remove-the-white-highlight-on-the-terminal/1438911#1438911) before finding the answer. I'm not sure it's a bug, but that's confusing.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
transformer|dak|1.6.0
vscode-eslint|dba|1.9.0
beautify|Hoo|1.5.0
vscode-favorites|how|1.4.0
reg|ion|0.0.2
vscode-opn|lfu|1.1.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
powershell|ms-|1.12.1
debugger-for-chrome|msj|4.11.3
vscode-fileutils|sle|2.13.7
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
local-history|xyz|1.7.0

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
