### ISSUE TITLE
High CPU and Memory Usage on code helper(watcherService)

### ISSUE THREAD

**Issue by Zyruis11** [microsoft/vscode#73980]
Issue Type: <b>Performance Issue</b>

Occurs while VSCode is open. 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 10|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   25	    90	  6597	code main
    9	    66	  6598	   gpu-process
    0	   188	  6599	   window (settings.json — Frontend (Workspace))
    0	     0	  6810	     /bin/bash -l
    0	    66	  6822	     extensionHost
    0	    49	  7214	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=6822
  263	  2531	  6962	     watcherService
    0	    66	  7016	   shared-process
    4	    74	  7231	   window (Issue Reporter)
    0	     0	  7234	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json — Frontend (Workspace))
|    Folder (freshops-frontend): more than 21519 files
|      File types: js(10832) hbs(2689) md(1262) css(968) json(874) html(766)
|                  png(575) scss(533) gitkeep(427) txt(424)
|      Conf files: package.json(468) grunt.js(32) gulp.js(3) makefile(1)
|                  jsconfig.json(1);
```

</details>
Extensions: none . 
<details>
<summary> Settings.json </summary>
```
`"window.zoomLevel": -1,
    "breadcrumbs.enabled": true,
    "editor.detectIndentation": false,
    "git.autorefresh": false,
    "git.autoRepositoryDetection": false,
    "files.useExperimentalFileWatcher": true,
    "files.exclude": {
        "/.git": true,
        "/.DS_Store": true,
        "/node_modules": true,
        "/node_modules/": true,
        "/bower_components/": true
        },
        "search.exclude": {
        "/node_modules": true,
        "/bower_components/": true

        },
        "files.watcherExclude": {
            "**/bower_components/**": true,
            "/bower_components/": true,
            "/node_modules/": true
        },`
```
</details>

**Comment by nakonechniyd** [comment]
Have the same problem

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-50-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 2139)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|0, 1, 2|
|Memory (System)|15.55GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   43	   159	 16295	code main
    0	    32	 16297	   zygote
    0	   271	 16349	     window (serpc2 : worker/app/app.py)
    0	   159	 16376	       extensionHost
    0	    48	 16479	         /snap/code/7/usr/share/code/code /snap/code/7/usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=16376
    0	    32	 16577	         /home/ndm/Projects/evo/serpc2/.venv/bin/python3 completion.py
    0	    16	 16581	           /home/ndm/Projects/evo/serpc2/.venv/bin/python3 lib/python/jedi/evaluate/compiled/subprocess/__main__.py lib/python
    0	   111	 16508	     shared-process
    0	    96	 17976	     window (Issue Reporter)
    0	     0	 18024	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 18025	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (serpc2 : worker/app/app.py)
|    Folder (serpc2): more than 1112664 files
|      File types: py(3090) pyc(1104) log(724) ldb(719) old(391)
|                  db-journal(377) db(376) so(271) txt(207) h(139)
|      Conf files: makefile(1) launch.json(1) settings.json(1) package.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
gitlens|eam|9.7.4
prettier-vscode|esb|1.9.0
rest-client|hum|0.21.3
vscode-simple-icons|Lau|1.11.7
metago|met|2.11.0
python|ms-|2019.4.12954


</details>
