### ISSUE TITLE
Apply update fails on Remote Desktop with multi-user running VSCode

### ISSUE THREAD

**Issue by suphu** [microsoft/vscode#73992]
Trying to update VSCode in a Remote Desktop session with other session users running VSCode.

It appears the update code is not filtering on current user Code.exe processes.  The below excerpt from log show Code.exe process id's that are other session users processes.

from vscode-inno-updater-1558356022.log
May 20 08:40:52.755 INFO Checking for possible conflicting running processes... (attempt 1)
May 20 08:40:52.768 INFO Kill process if found: 22068, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 8216, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 27132, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 15748, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 15348, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 18704, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 11156, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 22956, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 18292, Code.exe
May 20 08:40:52.769 INFO Kill process if found: 24128, Code.exe
May 20 08:40:52.769 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.
May 20 08:40:52.770 WARN Kill error Failed to open process: Access is denied.

**Comment by joaomoreno** [comment]
@suphu Yup, the update can't continue because Code.exe is in use. Code.exe can't be killed because other users own those processes. To fix this, install the User Setup of VS Code. That way each user can update independently.

**Comment by suphu** [comment]
All users have installed the User Setup of VS Code.
Code.exe process path for users = C:\Users\anyuser.name\AppData\Local\Programs\Microsoft VS Code\Code.exe


Larry Parker
Product Environment Manager
Direct: +1-850-205-0677
Email: larry.parker@aderant.com
Aderant
Aderant
https://www.aderant.com  |  LinkedIn  |  Twitter  |  Facebook
Any e-mail sent from Aderant may contain information which is CONFIDENTIAL and/or privileged. 
Unless you are the intended recipient, you may not disclose, copy or use it. Please notify the sender immediately and delete it and any copies from your systems. You should protect your system from viruses etc; we accept no responsibility for damage that may be caused by them.

**Comment by joaomoreno** [comment]
Interesting. And each user runs his own independent instance of Code?

**Comment by suphu** [comment]
This is an example from today – where user.b is attempting upgrade – from user.b vscode-inno-updater-1558693344.log
You can see that the update process is attempting to kill processes that do not belong to user.b

May 24 06:23:13.867 INFO Checking for possible conflicting running processes... (attempt 11)
May 24 06:23:13.877 INFO Kill process if found: 22068, Code.exe
May 24 06:23:13.877 INFO Kill process if found: 8216, Code.exe
May 24 06:23:13.877 INFO Kill process if found: 27132, Code.exe
May 24 06:23:13.877 INFO Kill process if found: 15748, Code.exe
May 24 06:23:13.877 INFO Kill process if found: 15348, Code.exe
May 24 06:23:13.878 INFO Kill process if found: 18704, Code.exe
May 24 06:23:13.878 WARN Kill error Failed to open process: Access is denied.
May 24 06:23:13.878 WARN Kill error Failed to open process: Access is denied.
May 24 06:23:13.878 WARN Kill error Failed to open process: Access is denied.
May 24 06:23:13.878 WARN Kill error Failed to open process: Access is denied.
May 24 06:23:13.878 WARN Kill error Failed to open process: Access is denied.
May 24 06:23:13.878 WARN Kill error Failed to open process: Access is denied.
May 24 06:23:15.947 ERRO Failed to open process: Access is denied.

Code.exe     22068 C:\Users\user.a\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe      8216 C:\Users\user.a\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     27132 C:\Users\user.a\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     15748 C:\Users\user.a\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     15348 C:\Users\user.a\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     18704 C:\Users\user.a\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     27992 C:\Users\user.b\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     14952 C:\Users\user.b\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     12736 C:\Users\user.b\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     29448 C:\Users\user.b\AppData\Local\Programs\Microsoft VS Code\Code.exe
Code.exe     19660 C:\Users\user.b\AppData\Local\Programs\Microsoft VS Code\Code.exe


Larry Parker
Product Environment Manager
Direct: +1-850-205-0677
Email: larry.parker@aderant.com
Aderant
Aderant
https://www.aderant.com  |  LinkedIn  |  Twitter  |  Facebook
Any e-mail sent from Aderant may contain information which is CONFIDENTIAL and/or privileged. 
Unless you are the intended recipient, you may not disclose, copy or use it. Please notify the sender immediately and delete it and any copies from your systems. You should protect your system from viruses etc; we accept no responsibility for damage that may be caused by them.
