### ISSUE TITLE
Progress bar for long file operations

### ISSUE THREAD

**Issue by thenem** [microsoft/vscode#73996]
I would like the see some kind of visual progress of long file operations, like when deleting a folder which takes a long time to delete due to a large number of items within the folder.

**Comment by isidorn** [comment]
For what exact operations would you expect this progress.
We already show progress in the explorer when resolving the roots of the explorer. Do you only miss it for the delete operation?

**Comment by thenem** [comment]
I just mean something similar to what you see when you delete files or folders from Windows Explorer or macOS Finder. If I delete a folder from the explorer side bar in vscode, I see no visual indication of whether it’s actually in the process of being deleted.

**Comment by isidorn** [comment]
Also for copy / paste

**Comment by iansan5653** [comment]
I'd like to see this as well, along with a way to cancel the operation. I've recently encountered two use cases:
1. I sometimes want to delete my `node_modules` folder and reinstall dependencies. It would be nice to see how long is left / if and why the operation has failed. Also if I accidentally delete it, I'd like to be able to cancel.
2. I dragged about two dozen large image files into a folder in VSCode to copy them into that folder. This task took some time but nothing showed up, so I wasn't sure when it finished.

**Comment by leonjanzen-work** [comment]
If a progress bar is too difficult, I would like at least see an indicator that shows when the file operation (copy/transfer/delete) is complete. At this point there is no way to even determine when/whether a file operation has completed.

**Comment by lamnguyen95** [comment]
This feature would be absolutely helpful, especially when working with machine learning data!

**Comment by thernstig** [comment]
Drag & drop from Windows -> VS Code (connected to a remote via ssh) could definitely use an indicator. I copied a large file, tried to run some script on the file on the "ssh side" and could not understand why it did not work, until I realize the upload had not finished.

**Comment by isidorn** [comment]
We now show progress for all long running (more than 500ms) file operations in the File Explorer.
We show an infinite progress bar on top of the Explorer viewlet, and we show a statsu bar entry.

Curretnly it is not possible to cancel these operations, for this requrest please follow this item as we plan to add this in the future https://github.com/microsoft/vscode/issues/111208

You can try it out in vscode insiders and let me know how it works for you

![recording (2)](https://user-images.githubusercontent.com/1926584/100145846-40627380-2e99-11eb-99db-cf60d36b5951.gif)

**Comment by isidorn** [comment]
Correction this is the follow up item for the cancelation of long running operations
https://github.com/microsoft/vscode/issues/111281
