### ISSUE TITLE
[Dev Container] allow specifying docker-compose services to start (or customizing docker-compose command line)

### ISSUE THREAD

**Issue by lbssousa** [microsoft/vscode#73997]
I use [laradock](https://github.com/laradock/laradock) to set up a clean development environment for my project. Now I'm trying VSCode Remote Development Extension to connect to workspace container in my laradock environment.

It works flawlessly, except for one thing: I can't start my containers directly from VSCode. This is due to a particular behaviour of laradock: I need to explicit in command line which services I want to start, so, instead of running just `docker-compose up`, I need to run e.g. `docker-compose up -d nginx postgres`.

Unfortunately, VSCode Dev Container currently only starts a docker-compose set of containers by running `docker-compose up` with no arguments. So it would be very helpful for laradock users, like me, if one could specify in devcontainer.json which services should be started with `docker-compose up`, or, more generally, customize docker-compose command line.

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/211
