### ISSUE TITLE
video are not working on remote development blogpost

### ISSUE THREAD

**Issue by hwmrocker** [microsoft/vscode#73990]
Issue Type: <b>Bug</b>
The advertised blog in the new version does not show any videos.

The video loading just hangs and when I try to watch in on youtube I get the error that the video does not exist.

https://code.visualstudio.com/blogs/2019/05/02/remote-development

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.1.3-arch1-1-ARCH

**Comment by chrisdias** [comment]
Hi, sorry about this. 

Are you able to watch the videos directly on YouTube?  for example, here: https://www.youtube.com/watch?time_continue=12&v=mIHprjsSO9o

Are there any errors in your browser console?

**Comment by hwmrocker** [comment]
:see_no_evil:
I was not able to see them back then. It is now fixed though
