### ISSUE TITLE
Vim modal editing

### ISSUE THREAD

**Issue by snowiow** [Microsoft/vscode#74]
Hi, I wanted to ask, if anyone is already working on a plugin for vim like modal editing and is looking for some help?

**Comment by ZombieProtectionAgency** [comment]
The github issue tracker is not really the place for questions.

**Comment by sharwell** [comment]
> The github issue tracker is not really the place for questions.

I disagree. The primary problem with pushing questions away from GitHub issues is there is not a clear line between "questions" and "bugs". For example, a user experiencing a problem might have simply misconfigured something on their local system, but just as easily could have found a bug that affects many people. Alternately, a bunch of repeated questions (duplicates) likely indicates a problem in the user documentation should should be addressed. GitHub issues is the place where people who are interested in participating in the project should feel comfortable participating, and never be dismissed based on something like the "kind" of issue they reported.

**Comment by ZombieProtectionAgency** [comment]
I have always assumed the best practice is to ask on StackOverflow or a forum first. You have obviously been around a lot longer than I have so I guess I was wrong, thank you for the correction.

**Comment by sharwell** [comment]
> I have always assumed the best practice is to ask on StackOverflow or a forum first. You have obviously been around a lot longer than I have so I guess I was wrong, thank you for the correction.

No problem. :smile: By the way, please don't take my comment as dismissing *you* either. You obviously have a knack for picking out bugs from other issues. I'd love nothing more than seeing you continue to give feedback as those items start to get fixed (perhaps even by you!).

**Comment by guillermooo** [comment]
@snowiow  https://github.com/VSCode-Extension/VSCodeVim

**Comment by snowiow** [comment]
Thx @guillermooo, I am currently getting myself comfortable with the plugin system and typescript and hope I can contribute something soon :)
