### ISSUE TITLE
Odd quotes auto-adding when editing in multi-cursor mode

### ISSUE THREAD

**Issue by juristr** [Microsoft/vscode#740]
There's an odd behavior currently when using multi-cursor support do change `"` to `'` (for instance).

I basically select the first " and hit `Ctrl+D` to select the next one, then I use `backspace` to delete them and add single quotes `'` instead.

In VSCode this results in the following odd behavior:
![vscode-replace](https://cloud.githubusercontent.com/assets/542458/11437098/1d4daa6a-94eb-11e5-947c-3f105b7da36f.gif)

Sublime Text instead seems to handle this:
![sublime-replace](https://cloud.githubusercontent.com/assets/542458/11437128/64f5da9a-94eb-11e5-865c-4fc20b64e25a.gif)

**Comment by Spown** [comment]
![](https://drive.google.com/uc?id=0B-OJBofmehO3bkd3R1BoN3dyamM)
fixed?

**Comment by juristr** [comment]
:raised_hands: yes, works now :smile: :+1:
