### ISSUE TITLE
Terminal don't refresh

### ISSUE THREAD

**Issue by AdrianDuan** [microsoft/vscode#74007]
Issue Type: <b>Bug</b>

Terminal don't refresh when quit htop
<img width="768" alt="Snipaste_2019-05-21_00-38-35" src="https://user-images.githubusercontent.com/26034046/58037974-4c150180-7b61-11e9-8be4-2b84043df26a.png">

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (26.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by AdrianDuan** [comment]
and the command `clear` also can not refresh the terminal window

**Comment by Tyriar** [comment]
Can you check the devtools console to see if there are any errors? (Help > Toggle Developer Tools)

**Comment by AdrianDuan** [comment]
@Tyriar I didn't get any errors from console. But this doesn't always happen.
<img width="1127" alt="Snipaste_2019-05-21_18-48-28" src="https://user-images.githubusercontent.com/26034046/58090321-8fbb4a00-7bf9-11e9-898e-4ed820870b1e.png">
