### ISSUE TITLE
User snippets

### ISSUE THREAD

**Issue by Perkin5** [microsoft/vscode#74004]
I use Codeigniter and have created a number of user snippets which work fine, including one for the important expression
`<?php echo base_url(); ?>`
which is important as the first part of any absolute path. When I start typing 'base', up pops the list including the snippet.
Except that one of the places I want this to work is inside the double-quotes for the href of a link tag but for some extraordinary reason when I locate the cursor there and start typing, the list of snippets does not appear. Is this a bug in vscode or can it be configured to do what I want?

**Comment by jrieken** [comment]
> Is this a bug in vscode or can it be configured to do what I want?

IntelliSense as-you-type only shows when typing at word ends and that means that you have to use Ctrl+Space once in a while. That all I can say with the information provided here

**Comment by Perkin5** [comment]
That will do nicely! Thank you, problem solved
