### ISSUE TITLE
Toggle Word Wrap does not show a check mark, different from other toggles like Toggle Minimap

### ISSUE THREAD

**Issue by BradL-Msft** [microsoft/vscode#74009]
Issue Type: <b>Bug</b>

Create a long line of text, big enough to wrap in current window size.
Toggle Word Wrap with View|Toggle Word Wrap.

Actual behavior:
Line of text wraps/unwraps as Toggle is selected multiple times.  
However, there is no visual indication in the menu whether Word Wrap is enabled or not.

Expected Behavior:
Toggle Text Wrap behaves like Toggle minimap or other toggle commands and shows a checkmark or other visual state indication in the menu.

VS Code version: Code - Insiders 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551, 2019-05-10T17:36:45.765Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.90GB (42.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
vscode-nmake-tools|Mic|2.0.190425008
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
powershell|ms-|1.12.1
shader|sle|1.1.4
clang-format|xav|1.9.0

</details>

**Comment by msftrncs** [comment]
Duplicate #71364

**Comment by msftrncs** [comment]
Also #62307

**Comment by msftrncs** [comment]
Even goes all the way back to #14986.   Looks like there has been complications completing this.

**Comment by alexandrudima** [comment]
Let's track in #62307
