### ISSUE TITLE
Updating VS Code from 1.31.0 to latest (1.34) causing error

### ISSUE THREAD

**Issue by bhaskarmac** [microsoft/vscode#74002]
Issue type - Bug

Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:37:01.048Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 6.1.7600

Steps to Reproduce:

1. Update using `Help` menu
2. After update downloaded you see `Restart Visual Studio Code to apply the latest update.` notification click on `Update Now` button
3. The error dialog will be displayed, please refer below screenshot

![vsCode_UpdateError](https://user-images.githubusercontent.com/4056847/58030569-65578700-7b3c-11e9-9eaf-d8ade5d44758.png)

Do I need to manually update the VS Code?

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
That's pretty strange. Could you install the Visual C++ Redistributable for Visual Studio 2015? https://www.microsoft.com/en-in/download/details.aspx?id=48145

**Comment by bhaskarmac** [comment]
@joaomoreno 
After installing `Visual C++ Redistributable for Visual Studio 2015` Can I try update?

**Comment by joaomoreno** [comment]
Yes, let me know how it goes.

**Comment by bhaskarmac** [comment]
After installing `Visual C++ Redistributable for Visual Studio 2015` still the same error, don't know what was the reason but I freshly installed latest `VS Code 1.34` now its working fine.
