### ISSUE TITLE
VS Code has not String IntelliSense

### ISSUE THREAD

**Issue by androllen** [Microsoft/vscode#7400]
- VSCode Version:  v1.2.0  
- OS Version: MacBook Pro v10.11.5  

Steps to Reproduce:

1. when input string ,vs code can not IntelliSense api

**Comment by alexandrudima** [comment]
@androllen Can you please help us understand better the issue: what language are you in, what are you typing (a small snippet), and what would you expect to get?

**Comment by androllen** [comment]
when vs code is updated, this issue is resolved

**Comment by androllen** [comment]
but can not formate code.please view output window for details.
Command failed: autopep8 --diff "d:\Program Files (x86)\Visual Studio 2015\Projects\Python\Demo\main.py"
'autopep8' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by dbaeumer** [comment]
@androllen I assume you have the python extension installed. Please file the issue there since the error message comes from that extension.
