### ISSUE TITLE
Moving cursor away from line corrupts vscode's display

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#74012]
Issue Type: <b>Bug</b>

See screenshot below.

![image](https://user-images.githubusercontent.com/172594/58040963-caa47b80-7b2e-11e9-93fd-c53a71c105b8.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18898

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
prettier-vscode|esb|1.9.0
svelte-vscode|Jam|0.9.1
powershell|ms-|1.12.1
vscode-typescript-tslint-plugin|ms-|1.0.0

</details>

**Comment by mikemaccana** [comment]
@vscodebot is wrong again, this isn't anything to do with the Integrated Terminal. maybe @vscodebot's author could make it stop tagging everything with 'Integrated Terminal'?

**Comment by Tyriar** [comment]
Can you see if this still happens with our exploration build? This contains a newer version of Electron:

https://az764295.vo.msecnd.net/exploration/1bdebe7e66e42d73b62c578b46fdc9a3e84c99d5/VSCodeUserSetup-x64-1.35.0-exploration.exe
