### ISSUE TITLE
Expand Selection does not work as expected for multiline blocks

### ISSUE THREAD

**Issue by anooprh** [microsoft/vscode#74025]
There are relevant issues regarding this, but previous ones have been closed without completely implementing the fix https://github.com/microsoft/vscode/issues/4795. Tested this issue on the insiders version. 

- VSCode Version: Version 1.35.0
- OS Version: Mac OS High Sierra 10.13.6

Steps to Reproduce:

1. Successively try expand region for multiline blocks. After the first line, it eagerly expands to the entire file. 
2. It also does not expand strings to include to include strings with and without quotes. 

This is what is happening right now. 
![code](https://user-images.githubusercontent.com/2604518/58058373-8f4d8100-7b1d-11e9-826c-6b2a20cea9dd.gif)

This is the same code in JetBrains pycharm. 
![charm](https://user-images.githubusercontent.com/2604518/58058529-2d414b80-7b1e-11e9-964a-fc9774b7b958.gif)

Specifically, I find the following lacking in VSCode expand region. 

* It does not treat anything beyond a line a single region. 
* It does not treat contents within a string and the string as separate regions. 
* It is too eager to expand the region to the entire line and to the entire file. (notice in the example when the cursor is within "main" string. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
There is now API so that extensions can provide selection ranges. There is a default/catch-all implementation but that isn't working for all languages.
