### ISSUE TITLE
[Feature request] View only the breakpoints in the current file in the debugger tab

### ISSUE THREAD

**Issue by GaurangTandon** [microsoft/vscode#74029]
- OS and Version: Ubuntu 18.04.2
- VS Code Version: 1.34.0

**Feature request:**

When I open a folder (Ctrl K, Ctrl O), put some breakpoints in one file, then switch to another file and put breakpoints there, the breakpoints of both the files are visible in the Breakpoints tab of the Debugger.

I wish to have a toggle switch in settings due to which it would display only the breakpoints of the currently active file. Is it possible? Thanks!

(Previously posted on [vscode-cpptools](https://github.com/microsoft/vscode-cpptools/issues/3665))

**Comment by isidorn** [comment]
Currently this is not possible. However this is a fair feature request, thus leaving it open and assigning to backlog (not currently planned).
