### ISSUE TITLE
Opening a special header file hangs up VS Code

### ISSUE THREAD

**Issue by pratikone** [microsoft/vscode#74023]
Issue Type: <b>Bug</b>

Hi, 

I open a .h file with COM objects and it hangs VS Code. I can see it gets hung up in syntax highlighting. I have disabled all addons to isolate the issue and it seems to be a main VS Code problem.  This doesn't happen with other .h or source files.

VS Code version: Code - Insiders 1.35.0-insider (a5536b8f5a16a10d859f3dec1e59701671bf069e, 2019-05-20T05:17:36.269Z)
OS version: Windows_NT x64 10.0.18899

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (12.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
vscode-nmake-tools|Mic|2.0.190403001
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
vsliveshare|ms-|1.0.182
vscode-gn|npc|1.0.0
gitblame|wad|2.7.0

(1 theme extensions excluded)

</details>

**Comment by matter123** [comment]
This was fixed upstream at jeff-hykin/cpp-textmate-grammar in version 1.8.15, see jeff-hykin/cpp-textmate-grammar#174

The fix should make it to vscode insiders the next time the grammars are updated. If you need the fix now you can install https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax&ssr=false

**Comment by alexr00** [comment]
I just updated the C++ and pulled in the fix (https://github.com/microsoft/vscode/commit/b8b79709b73a22e59778ba48a20c550bc1ed2cd5). Thanks for the heads up @matter123!
