### ISSUE TITLE
Keyboard shortcut for Codelenses 

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#74020]
Issue Type: <b>Feature Request</b>

What are the keyboard shortcuts to access the codelenses feature ?

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
Not implemented. #41579
