### ISSUE TITLE
Install code-insiders in PATH should not override code

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#7403]
When using code-insiders and selecting "Install code-insiders in PATH", it also overrides the code command. I would like to have both commands so I can choose whether to use insiders or not.

**Comment by joaomoreno** [comment]
Code Insiders will create a `code-insiders` shortcut. Stable Code will create a `code`.

**Comment by OliverJAsh** [comment]
When I installed code-insiders, it also seemed to override my exisiting
code command to link to Code Insiders.

**Comment by joaomoreno** [comment]
That is odd. Looking at the code, it is not supposed to do that... If so, what did it overwrite it with?
