### ISSUE TITLE
terminal can't show path

### ISSUE THREAD

**Issue by PhoenixNil** [microsoft/vscode#74034]
Issue Type: <b>Bug</b>

just like this
[img](https://i.loli.net/2019/05/21/5ce37b346329a71378.png)
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (10.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-search|bur|1.0.1
bracket-pair-colorizer|Coe|1.0.61
code-runner|for|0.9.9
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.34.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
vetur|oct|0.21.0
code-settings-sync|Sha|3.2.9
vscode-icons|vsc|8.6.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
