### ISSUE TITLE
remap 'ctrl+k' as new 'leader' key

### ISSUE THREAD

**Issue by GraysonGao** [microsoft/vscode#74032]
There are many key bindings start with 'ctrl+k', so the 'ctrl+k' is like the 'leader' key in Vim. But I have bound 'ctrl+k' to a new shortcut, so all the key bindings strat with 'ctrl+k' were invalid. Please provide a way to remap 'ctrl+k' as new leader key.

**Comment by gjsjohnmurray** [comment]
@GraysonGao does this SO post help you?

https://stackoverflow.com/questions/51907158/how-to-remap-all-ctrlk-chords-at-once-in-vscode

**Comment by GraysonGao** [comment]
> @GraysonGao does this SO post help you?
> 
> https://stackoverflow.com/questions/51907158/how-to-remap-all-ctrlk-chords-at-once-in-vscode

That really works! Thank you very much. Although there are many "ctrl+k" shortcuts, I only use a few of them, it's OK to remap manually.
