### ISSUE TITLE
isBackground property in tasks.json not work

### ISSUE THREAD

**Issue by lijian4607** [microsoft/vscode#74033]
- VSCode Version: 1.34.0
- OS Version: Ubuntu 16.04

launch.json:
`{

    "configurations": [
        {
            "name": "debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "Program.bin",
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "miDebuggerPath": "arm-linux-gdb",
            "miDebuggerServerAddress": "XXXX:2345",
            "preLaunchTask": "launch"
        }
    ]
}`

Note that my task "launch" use telnet to run a program on the remote ARM linux board, meanwhile the connection will retain, so this task will not finish. In older version such as 1.30.2, if I set the isBackground property of task to true, debug session will not wait the task to finish, but if I use the version 1.31.0 or newer, the debug session will wait the task to finish and the stuck.

Does this issue occur when all extensions are disabled?: Only use C/C++ extension

**Comment by lijian4607** [comment]
@isidorn Please help to solve the problem as soon as possible.

**Comment by isidorn** [comment]
@alexr00 did something change in the task frameworks since 1.31?
Can you maybe investigate this one?

**Comment by alexr00** [comment]
@lijian4607 can you paste in the task `launch`?

**Comment by lijian4607** [comment]
@alexr00 
launch:
`
        {

            "label": "debug",
            "type": "shell",
            "command": "./Common.sh",
            "args": [
                "kill $(pidof gdbserver) &> /dev/null",
                "kill $(pidof Program.bin) &> /dev/null",
                "tftp -gl Program.bin ${env:DTU_CLIENT}",
                "chmod 777 Program.bin",
                "./gdbserver :2345 Program.bin"
            ],
            "presentation": {
                "echo": false,
                "focus": true,
                "clear": true
            },
            "isBackground": true
        }
`

Common.sh
`
#!/usr/bin/expect
set timeout -1
spawn telnet $env(DTU_SERVER)
expect "login: "
send "root\n"
expect "Password: "
send "123\n"
expect "/ # "
send "cd /opt\n"
expect "/opt # "
if {$argc == 0} {
    set format "%Y-%m-%d %H:%M:%S"
    send "date \"+$format\"\n"
    interact
}
for {set i 0} {$i < $argc} {incr i} {
    send "[lindex $argv $i]\n"
    expect "/opt # "
}
`
This is an expect script, and it will not finish, because the last "expect" command will not catch "/opt"
 until the debug session end.

**Comment by lijian4607** [comment]
@alexr00 Do you have any idea?

**Comment by alexr00** [comment]
To use a background task as a debug `preLaunchTask` you must also have a problem matcher so that we know when the task is "done". Problem matchers: https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks
