### ISSUE TITLE
Terminal is blank

### ISSUE THREAD

**Issue by vishalah01** [microsoft/vscode#74035]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by vishalah01** [comment]
The terminal is blank and not showing the path like CMD.
Tried starting a new terminal, but nothing happened.

Strange thing is, when i start writing the terminal is showing my words and functionality is working.

For example: when i write 'ng serve' and hit enter the Angular server starts and works perfectly.

I request you to please fix this issue as soon as possible.
I am fond of VS Code and didnot liked this.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
