### ISSUE TITLE
Chinese character gash problem in Terminal .

### ISSUE THREAD

**Issue by liamwang** [Microsoft/vscode#7404]
- VSCode Version:1.2.0
- OS Version:Windows 7

Steps to Reproduce:

### Problem 1
1. Ctrl + `
2. Chinese character gash in Terminal.

![2016-06-08_174351](https://cloud.githubusercontent.com/assets/5000396/15890455/322fce9a-2da2-11e6-9ce4-4b99be7f52ef.png)

### Problem 2
1. 创建一个目录： D:\新建文件夹
2. 打开VS Code， 文件 -> 打开文件夹，选择创建好的“新建文件夹”
3. Ctrl + ` 无法打开 Terminal。

**Comment by ZCShou** [comment]
这个问题早就反馈过了！现在 1.3版 依旧如此

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7062
