### ISSUE TITLE
Markdown "{", "}"

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#74046]
Issue Type: <b>Bug</b>

"{" and "}" are a normal/formalized text symbols, used to separate parts of text, the VSC's Markdown asset do not support them for Auto-Surround.

p.s. why would any current language package do not support some braces for Auto-Surround at all?

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Braces / surround are designed to handle syntax elements for each language. Braces have no special meaning in markdown files so we do not include them

**Comment by Ilias48rus** [comment]
@mjbvz , this is non sence, the markdown is an extension to literal language, its is not a self sufficient one which can be used on its own, so everything the literal language have the markdown have too.

**Comment by Ilias48rus** [comment]
@mjbvz , and its just purely **nothing** good from making such inconvenience

**Comment by Ilias48rus** [comment]
@mjbvz , like an audio recorder without ability to playback or export the audio because its a subject of data management and not the recording, the same logic.
