### ISSUE TITLE
Weird 1px black border at bottom [Win10]

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#74047]
Hello,

I'm sorry to bother you with low priority bugs, but it's a really annoying visual bug.
In Win 10 i have weird 1px black border at VSCode bottom
It happen when `Window: Title Bar Style` is set to `Custom`

**Screen below:**
![obraz](https://user-images.githubusercontent.com/30685349/58085829-c1aebb00-7bbd-11e9-8303-63e44c7a9199.png)

_And yes, it's a duplicate but all tickets are closed and it's still not fixed_

```
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

`Insider version`: the same problem

**Steps to Reproduce:**

1. Run vs code
2. Maximize windows

Does this issue occur when all extensions are disabled?: **YES**

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by kanlukasz** [comment]
Thank you for your reply. Unfortunately the same situation, screen below:

[Win 10]
![obraz](https://user-images.githubusercontent.com/30685349/58175204-e67b5f00-7c9f-11e9-82f7-9f812c908d01.png)

**Comment by kanlukasz** [comment]
#### Old references to this problem ( _maybe it will help somehow_ ) :
- https://github.com/Microsoft/vscode/issues/61445
- https://github.com/microsoft/vscode/issues/58427
- https://github.com/microsoft/vscode/issues/66448
- https://github.com/microsoft/vscode/issues/65792

**Comment by kanlukasz** [comment]
It may be interesting that PHPStorm has similar problem with the latest version:
- https://youtrack.jetbrains.com/issue/IDEA-215445

This 1px drives me crazy 😿

**Comment by kanlukasz** [comment]
Wow, after the last release of Insiders there is no strange border !!!!!
Great news, I hope this will be fixed permanently

![obraz](https://user-images.githubusercontent.com/30685349/65262781-5c3aee80-db0b-11e9-8999-f3ea84eb917b.png)

**Comment by kanlukasz** [comment]
Update:

With version:
```
Version: 1.39.0-insider
Commit: 575062278d181c075ea8dce345ab3d20a127309c
Date: 2019-09-20T06:11:13.647Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```
**was OK**

but

with another update:
```
Version: 1.39.0-insider
Commit: 79978f96d3501f14b235ed0a33a7360772a726a3
Date: 2019-09-30T14:18:14.941Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
the problem is back 😥
