### ISSUE TITLE
clean nodes in FS explorer are marked as modified

### ISSUE THREAD

**Issue by ZuBB** [microsoft/vscode#74044]
- VSCode Version: 1.34
- OS Version: macos 10.14.5

Steps to Reproduce:

1. open some project in vs code
2. do some changes
3. switch to external terminal. commit changes
4. switch back to code. FS explorer still marks committed nodes as modified

Does this issue occur when all extensions are disabled?: Yes

Couple of notes:
* I am not sure that STR above are valid. they are part of my regular flow. and this happens almost every time;
* I am pretty sure this started to happen with 1.34;
* I have guess that this might be related to next

> Extensions have been able to provide their own filesystem implementations for custom resources (read more here). However, VS Code's own implementation for local files was not implemented with the same extension APIs. This resulted in subtle differences when dealing with local file resources compared to resources coming from extensions. Over the last two milestones, we rewrote our local file system provider to use the extension APIs for consistency.

See screen for example of this bug

<img width="2560" alt="Screen Shot 2019-05-21 at 11 06 45" src="https://user-images.githubusercontent.com/597016/58079991-f2412580-7bba-11e9-9bb0-db3552e756e0.png">

**Comment by isidorn** [comment]
This is coming from the git decoration provider, forwarding to @jrieken as I believe he is the owner (let me know if I am wrong)

**Comment by jrieken** [comment]
What does the git viewlet show?
