### ISSUE TITLE
cs file bug

### ISSUE THREAD

**Issue by huyang1619** [microsoft/vscode#74042]
Issue Type: <b>Bug</b>

some references overlapping with variable

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.19.1
unity-tools|Tob|1.1.0
unity-debug|Uni|2.7.2

</details>

**Comment by alexr00** [comment]
@huyang1619 can you provide an example?
