### ISSUE TITLE
VSCode freezes opening (some) cpp files

### ISSUE THREAD

**Issue by albestro** [microsoft/vscode#74043]
- VSCode Version: 1.35.0-Insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628)
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. Copy these three commented lines of code and save them in a .cpp file
```
// std::unique_ptr<hpx::threads::thread_pool_base> pool(
// new hpx::threads::detail::scheduled_thread_pool<high_priority_sched>(
// std::move(scheduler), notifier, pool_index, pool_name, mode, thread_offset));
```
2. As soon as you uncomment the first two lines, VSCode freezes

By uncommenting any other combination of lines does not show any problem.

These three lines are extracted from one of the files that were causing the problem.

Does this issue occur when all extensions are disabled? Yes

**Comment by alexr00** [comment]
Updated the C++ grammar to pull in the fix for this: https://github.com/microsoft/vscode/commit/b8b79709b73a22e59778ba48a20c550bc1ed2cd5
