### ISSUE TITLE
TS: first auto import statement above copyright header

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74051]
* create a new TS file
* add copy right header on line 1
* below the copyright header, accept a completion that inserts an import statement
* :bug: the import is above the header-comment, it should be below

this is a paper-cut-issue

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/31508 for this. It was previously supposed to have been fixed by https://github.com/microsoft/TypeScript/issues/15515 but looks like the comment case was not handled
