### ISSUE TITLE
highlight bug after certain code

### ISSUE THREAD

**Issue by davidwangd** [microsoft/vscode#74057]
- VSCode Version:latest
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. std::vector<pair<int,int>> *g = new std::vector<pair<int,int>>[n];
2. the highlight code after this line of code broken out..
3. add {} after this line the highlight recovered.

Does this issue occur when all extensions are disabled?: No
but i was using the official cpp extension

**Comment by alexr00** [comment]
Looks like the folks who make the C++ grammar we use are already looking at this. Next time I pull in the C++ grammar from https://github.com/jeff-hykin/cpp-textmate-grammar/ I'll pick up their fix.
