### ISSUE TITLE
wrong coloring of variables of name number/boolean/string

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#7406]
- VSCode Version: Version 1.3.0-insider (1.3.0-insider)
- OS Version: 6bc81df453ab2156d2630fbb89ad7d0c80620420

The highlighting is a bit off for JavaScript/Typescript
![screen shot 2016-06-08 at 11 41 56 2](https://cloud.githubusercontent.com/assets/3898363/15891809/3c0cff20-2d6e-11e6-9304-3cb8d1aea4ca.png)

**Comment by massimocode** [comment]
Another one that I often see
![screen shot 2016-06-08 at 11 45 27 2](https://cloud.githubusercontent.com/assets/3898363/15891856/84fa5304-2d6e-11e6-8bb9-9038a3d713a5.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#186
