### ISSUE TITLE
python docstring code folding without write #region and #endregion

### ISSUE THREAD

**Issue by randomseed42** [microsoft/vscode#74062]
This is an old topic closed earlier in #37052 and #3422, but just want to know can we define python language-aware folding using triple double quote which is used for docstring, rather than #region and #endregion?

![image](https://user-images.githubusercontent.com/50793718/58101061-7b834700-7c11-11e9-9b17-caad0857842e.png)

Thanks!

**Comment by aeschli** [comment]
You are asking for Python language aware folding regions. These need to come from a Python extension.

Are you using the vscode python extension? If yes, the request for the feature is here: https://github.com/microsoft/vscode-python/issues/1847.
