### ISSUE TITLE
VS Code installation for npm test extension host hijacks Windows taskbar jumplist entries

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#74066]
I have not found any other issues dealing with this. This is for VS Code 1.34, but I have observed this for more than a year now. This issue only applies to Windows as far as I know, specifically Windows 10.

1. Start with a fresh installation of Windows and VS Code (pinned to the taskbar)
2. Go through the extension development tutorial
3. Download a `.vscode-test` VS Code instance as a part of that tutorial when running `npm test`
4. Run tests and generally develop the extension
5. Close VS Code, go to the taskbar, hover over VS Code pinned icon, click the extension directory

You will notice, that the VS Code version used for VS Code extension hosts opens up with your extension directory instead of the VS Code version you installed. Usually these versions will be close to each other or identical, but you can always tell, because the extension one is 32 bit and will display a notification telling you to use the 64 bit one - which the main VS Code version won't because you've downloaded it 64 bit already.

I don't know why this happens, I have been working around it by opening VS Code by clicking the taskbar icon, not using the jump list, and selecting my directory in the VS Code start page instead. Starting VS Code using the icon directly will launch the proper version.

As far as I know this is not affected by whether extensions are installed or not.

I don't know why this happens, but I have a guess:

- VS Code registers a protocol handler on startup (like `vscode://` or similar)
- The instance used for testing extensions is the last one to start up as you need to kill the main one in order for `npm test` to run - it won't allow multiple VS Code instances while running
- The protocol handler is rewritten by the test instance
- The Windows taskbar jump list entries use that protocol link not direct binary launch path
- The Windows taskbar icon is just a regular shortcut which does lead to the actual correct binary path
- After opening the right binary with the icon, the handler is fixed and points to the right thing again

Like I said, I actually have no idea what's happening, so I'm curious how close I am with the above.

**Comment by bpasero** [comment]
This sounds like a Windows issue to me. It is true that we download a VSCode version to run for tests but that version should not be associated with the windows registry at all. Are you saying that the VSCode instance that opens when you click the taskbar is the one downloaded for the tests and not the one installed globally on the OS?

**Comment by TomasHubelbauer** [comment]
Not when I click the task bar icon but yes, when I use a jump list link for the extension repository. I've had this happen on two computers where I developed extensions. I might be able to reproduce this in a VM to be able to share the disk image.
