### ISSUE TITLE
Panel active border inconsistent

### ISSUE THREAD

**Issue by mythio** [microsoft/vscode#74067]
- VSCode Version: 1.34.0
- OS Version: Ubuntu 1904

Steps to Reproduce:
For any theme with panel title active border color,
1. Open the panel (control + `)
2. Select PROBLEMS panel
3. The panel is not highlighted initially
4. Click on the panel or anywhere in the vscode window
5. The PROBLEMS panel is now highlighted

When launching VSCode by `code --disable-extensions`, the issue is different.
When clicking on the panels, the highlight turns blue and then grey. But for the PROBLEMS panel, it stays blue, and changes to grey after clicking anywhere in the VSCode.

**Comment by sandy081** [comment]
Each panel has different focus areas and problems panel has its content has focus area and hence it is highlighted when focused.
