### ISSUE TITLE
Click on settings icon shows collapsed menu

### ISSUE THREAD

**Issue by yuoo655** [microsoft/vscode#74069]
<img width="253" alt="屏幕快照 2019-05-22 上午12 06 04" src="https://user-images.githubusercontent.com/48611913/58112137-716b4380-7c25-11e9-92ed-5ae239471460.png">
Click the gear icon always get a  a collapsed menu list.  I don't like this.   Because this kind of collapsed seem saved space and makes itself look small , it tooks me more time to click what i want ,  though it  didn't save much space for me.

**Comment by yuoo655** [comment]
<img width="533" alt="屏幕快照 2019-05-22 上午12 22 23" src="https://user-images.githubusercontent.com/48611913/58113264-b55f4800-7c27-11e9-9af7-c5ca881b062c.png">

I think this icon should not be collapsed like other menu.  And I think this is the only icon or button  that shows collapsed / folded menu.

**Comment by yuoo655** [comment]
I think  a collapsed menu is only needed when the space is not enough.   but the left side cornor obviously have enough space to show all the items. so why use a collapsed menu?
<img width="253" alt="屏幕快照 2019-05-22 上午12 06 04" src="https://user-images.githubusercontent.com/48611913/58113695-b04ec880-7c28-11e9-957e-09f81d68747a.png">

**Comment by sbatten** [comment]
electron bug https://github.com/electron/electron/issues/14261
