### ISSUE TITLE
Task echo text not showing with conpty

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#74063]
Example of how a task runs and shows echo text. The first line is the echo text:
```
> Executing task: echo %FOO% <

%FOO%

Terminal will be reused by tasks, press any key to close it.
```
When conpty is enabled, this is what shows:
```
%FOO%

Terminal will be reused by tasks, press any key to close it.
```

You can't scroll up and see the echo text. It isn't there. It does seem to flicker in and out of existence for a moment. though.

Task for reproducing:
```
		{
			"label": "TESTING",
			"type": "shell",
			"command": "echo %FOO%",
			"problemMatcher": [],
		}
```

**Comment by Tyriar** [comment]
There's no way around this on our side unfortunately as conpty aggressively reprints the entire screen.

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/terminal/issues/919

**Comment by Tyriar** [comment]
We should use `PSEUDOCONSOLE_INHERIT_CURSOR` in [`CreatePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole)

https://github.com/microsoft/node-pty/blob/f8045ab74667c24ea25a9c40888dfbeba6e58cd9/src/win/conpty.cc#L138

**Comment by alexr00** [comment]
I that case, I'll add back in the setting for winpty in tasks.

**Comment by Tyriar** [comment]
@alexr00 if I can get node-pty updated (hoping to this week)  I'll be able to make this change pretty easily.

**Comment by Tyriar** [comment]
node-pty PR https://github.com/microsoft/node-pty/pull/309

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/73597, verified it locally
