### ISSUE TITLE
Git: support passing extra environment variables on git spawn

### ISSUE THREAD

**Issue by nathan-prat** [microsoft/vscode#74064]
Hi,

I would like a way to access the path to the current workspace in the git hooks.

My use case is for running a precommit hook in a 'monorepo'.

Let's say I have something like:
.
├── .git/
├── README.md
├── ProjectA/
|   ├── CMakeLists.txt
|   └── src/
├── ProjectB/
|   ├── CMakeLists.txt
|   └── src/

"ProjectB" is opened in vscode, but when the hook is executed the current dir is the root of the monorepo(which is the expected behavior).

In the hook script(Python but not relevant), I have currently no way to know on which project I am working. Without knowing if I am "ProjectA" or "ProjectB", I can not compile & test & clang-tidy & etc the changes.

I have printed the whole `os.environ` in the hook's code, and I see nothing useful.
But maybe I am missing another way to do what I want?

The solution could be as simple as adding a new VSCODE_WORKSPACE_FOLDER var to the environment.

PS: I obviously could try & compile each project, but this not a proper solution.

**Comment by joaomoreno** [comment]
What would happen if you run `git commit` from the command line?

**Comment by nathan-prat** [comment]
The same behaviour as when vscode calls it.

That is why it is a feature request and not a bug: vscode is just calling git and everything works as expected.
But I can not use my git hook in a monorepo right now.

As a workaround I start vscode with `WORKSPACE_FOLDER code .`, and use that env var in the hook script.

**Comment by joaomoreno** [comment]
What if there's more than one folder in your workspace?

**Comment by nathan-prat** [comment]
I should have said: when I run `WORKSPACE_FOLDER=$(pwd) code .` it is from `ProjectA` or `ProjectB`.

If I try to run the hook(or commit) from the root of monorepo, it obviously will not work.
But this is fine, it is not my use case.
And we can imagine the different projects are in different languages and using different build systems, so a generic script that would work from root makes no sense.

PS: what I call workspace here is either `ProjectA` or `ProjectB`. Those are the folders I open in vscode. I never open the root directly.

**Comment by joaomoreno** [comment]
I mean... if we automate this and add a new `VSCODE_WORKSPACE_FOLDER` variable, what do you suggest the value should be, when in a multi-root workspace?

**Comment by nathan-prat** [comment]
Ok, I guess you can call that `VSCODE_WORKSPACE_ROOT`, and that would be the top-most folder open.
Note that CMake plugin does not support multi-workspace so this not my use case.

But really it would be nice if it at least worked in non-multiroot workspaces.

Alternatively instead of an hardcoded variable, it would be nice to set whatever env vars we want using eg `settings.json`. That could work.

**Comment by joaomoreno** [comment]
A multi-root workspace can have multiple, independent folders in it. They don't need to be related at all.

> Alternatively instead of an hardcoded variable, it would be nice to set whatever env vars we want using eg settings.json. That could work.

That's more interesting. We can definitely add a git setting to add environment variables when spawning. Would that help?

**Comment by nathan-prat** [comment]
That would be perfect.

**Comment by joaomoreno** [comment]
Wanna attempt a PR?

**Comment by nathan-prat** [comment]
Why not. I will try.

**Comment by joaomoreno** [comment]
PR still accepted if submitted, just cleaning out the issue.
