### ISSUE TITLE
Render process crashes on 67 kB file

### ISSUE THREAD

**Issue by Eviathor** [microsoft/vscode#74061]
Issue Type: <b>Bug</b>

**First encountered the issue during remote editing to Ubuntu 14.04, but it was also replicated locally on Windows.**

running Visual Studio Code - Insiders, updated.

When opening a cpp file (size: 67kB, ~4k lines) vscode freezes. Most of the times the only solution is to kill the process, and in the few rare occasions where vscode regains functionality, it crashes a few moments later.

running code-insiders --disable-gpu and --disableExtensions didn't help.
I also saw issue #64389, which seems to be dealing with the same problem, but the solution there was to use the latest version which uses Electron 3.0.x, which to my knowledge is already the situation on my machine.

Thanks!

VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'ssh-remote+cardif_vm' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.53.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
remote-wsl|ms-|0.36.0
vscode-remote-extensionpack|ms-|0.14.0
code-gnu-global|aus|0.2.2
cpptools|ms-|0.23.1
vscode-proto3|zxh|0.2.2

</details>

**Comment by Eviathor** [comment]
Tried it with the latest visual studio code (not insiders), not replicating. This is only relevant to the latest Insiders version.

**Comment by alexandrudima** [comment]
@Eviathor I believe this might be something specific to the file you are opening and the C++ grammar. If you rename the file to `.txt` and open it, does the crash occur?

**Comment by Eviathor** [comment]
I guess it was related to the c++ grammar, but it has been gone for a while now. Closing.
