### ISSUE TITLE
Support tree-sitter based code folding

### ISSUE THREAD

**Issue by TDHolmes** [microsoft/vscode#74074]
It would be great to utilize tree-sitter for code folding detection. This was done in atom with great success, especially for C based projects with `#if` pre-processor commands on column zero in the middle of deeply nested code.

I tried my best to search for an existing issue for this, but the closest I found was #50140 which is using tree-sitter for syntax highlighting.

**Comment by georgewfraser** [comment]
It would be straightforward to add this to https://github.com/georgewfraser/vscode-tree-sitter . The hard part of creating and mantaining the tree-sitter syntax tree is done, we just need to implement a [FoldingRangeProvider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider)

**Comment by Razzeee** [comment]
I'm actually already using tree sitter to fold with my language server.
https://github.com/elm-tooling/elm-language-server/blob/master/server/src/providers/foldingProvider.ts

**Comment by aeschli** [comment]
The idea is that language aware folding providers are contributed by language extensions.
Typically a language extension runs a language server that already parses the file for other features, so it can easily also emit folding regions. And of course if can also do this using treesitter.

-> If you miss a language aware folding regions, make a request against a language extension of your language to add this.
Having this provided by an extension like https://github.com/georgewfraser/vscode-tree-sitter is also a good idea, except that I think it would be better to have an extension per language so users can avoid conflicts by selectivity installing and uninstalling extensions.
