### ISSUE TITLE
Blue background in vscode terminal

### ISSUE THREAD

**Issue by ace411** [microsoft/vscode#74071]
- VSCode Version: April 2019 version 1.34
- OS Version: Windows 10 version 1809

Steps to Reproduce:

1. Restarting the editor multiple times

Does this issue occur when all extensions are disabled?: Yes

![vscode-terminal-color](https://user-images.githubusercontent.com/11040337/58114165-d90e9800-7bff-11e9-9d64-7d0a80d0e9fc.png)

I've been experiencing the blue-colored text background problem since last fall. It has made terminal usage harder in recent months.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
