### ISSUE TITLE
Feature Request: Add an option to ignore commented-out search results

### ISSUE THREAD

**Issue by KatieProchilo** [microsoft/vscode#74070]
When I search a file (```ctrl+f```) or a project (```ctrl+shift+f```), there are options to match casing and an entire word. It would help the DX if there was an option to to ignore search results that are commented out.

For example:
* I press ```ctrl+shift+f``` and search for "foo."
* ```var foo = 5;``` would appear in the search results.
* ```// var foo = 5;``` would not.

**Comment by roblourens** [comment]
This is a common request but it's not really practical for us to have language-specific features for search. It's just a simple text search and I want to keep it simple.
