### ISSUE TITLE
Extension fails to load in the second VSCode instance

### ISSUE THREAD

**Issue by LunaLovegoood** [microsoft/vscode#74078]
I'm currently developing an extension and lately i started having an issue that extension successfuly works when there's one VSCode instance but fails to load if i open second instance of VSCode.

From dev console:

WARN UNRESPONSIVE extension host, 'undefined_publisher.[extension-name]' took 99% of 5127.735ms, saved PROFILE here: 'C:\Users\[USER]\AppData\Local\Temp\exthost-28913e.cpuprofile'

Extension load time in first instance: ~10ms

- VSCode Version: 1.34.0
- OS Version: Windows 10

Steps to Reproduce:

1. Launch VSCode
2. Launch second instance of VSCode

**Comment by alexr00** [comment]
I can't reproduce this with other extensions, so it is likely a problem with your extension. Do you have any other repro steps?

**Comment by LunaLovegoood** [comment]
Unfortunately, no.
When trying to debug extension, it doesn't seem to even reach activate() function.
Any ideas what could've caused such issue?

**Comment by LunaLovegoood** [comment]
Also there's always a 'Debugger attached statement' in dev console when extension failes to load.

**Comment by LunaLovegoood** [comment]
It was my fault. CPU profile help to detect the reason.
Closing issue now.
