### ISSUE TITLE
extension api: port mapping for websockets not working

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#74085]
The new port mapping API doesn't work for websockets, e.g.
`http://localhost:3000` is mapped to `http://localhost:4000`
`ws://localhost:3000` is not mapped to `ws://localhost:4000`

Steps to Reproduce:
```js
// extension.js
const vscode = require('vscode')
const { createServer } = require('http')

createServer((req, res) => {
  res.end('ok')
}).listen(4000)

const html = `<!doctype html>
	<html>
    <h1>hello world</h1>
		<script>
			fetch('http://localhost:3000')
			new WebSocket('ws://localhost:3000')
		</script>
	</html>
	`

exports.activate = () => {
  const webViewPanel = vscode.window.createWebviewPanel(
    'my-extension',
    'my-extension',
    {
      viewColumn: 1,
    },
    {
      enableScripts: true,
      portMapping: [
        {
          extensionHostPort: 4000,
          webviewPort: 3000,
        },
      ],
    }
  )
  webViewPanel.webview.html = html
}
```

![screenshot](https://user-images.githubusercontent.com/23744935/58126703-d322b200-7c13-11e9-94f2-0e0eb0636567.png)

**Comment by SimonSiefke** [comment]
I have made a pr: https://github.com/microsoft/vscode/pull/74086

**Comment by SimonSiefke** [comment]
I have tried to test redirecting websockets, but the fix doesn't actually work (sorry about that). I found out that redirecting Websockets is not supported. 

From the spec (https://fetch.spec.whatwg.org/#websocket-opening-handshake): 
"The reason redirects are not followed and this handshake is generally restricted is because it could introduce serious security problems in a web browser context. For example, consider a host with a WebSocket server at one path and an open HTTP redirector at another. Suddenly, any script that can be given a particular WebSocket URL can be tricked into communicating to (and potentially sharing secrets with) any host on the internet, even if the script checks that the URL has the right hostname."

Here is a workaround I currently use instead of port mapping for connecting to a random free port from inside a webview:

```js
// extension.js
const vscode = require('vscode')
const getPort = require('get-port')
const WebSocket = require('ws')

function startServer(port) {
  const wss = new WebSocket.Server({
    port,
  })
  wss.on('connection', ws => {
    ws.send('hello world')
  })
}

function getPreviewHTML(context, port) {
  const previewBase = vscode.Uri.file(context.extensionPath).with({
    scheme: 'vscode-resource',
  })
  return `<!DOCTYPE html>
<html>
  <body data-port="${port}">
    <script src="${previewBase}/index.js"></script>
  </body>
</html>
`
}

exports.activate = async context => {
  const port = await getPort()
  startServer(port)
  const webViewPanel = vscode.window.createWebviewPanel(
    'my-extension',
    'my-extension',
    {
      viewColumn: 1,
    },
    {
      enableScripts: true,
    }
  )
  webViewPanel.webview.html = getPreviewHTML(context, port)
}
```

```js
// index.js
const port = document.body.dataset.port
const ws = new WebSocket(`ws://localhost:${port}`)
ws.addEventListener('message', ({ data }) => console.log(data))
```

I guess it would also be useful to document in `vscode.d.ts` that port mapping doesn't work with websockets.

**Comment by mjbvz** [comment]
Ok, do you want to submit a PR that reverts your change and also documents this in the `vscode.d.ts` file?

**Comment by SimonSiefke** [comment]
yes: https://github.com/microsoft/vscode/pull/74185

**Comment by mjbvz** [comment]
Closing again. #74185 added the note about websockets to the vscode documentation
