### ISSUE TITLE
Tab groups except last one are lost after Windows crash

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#74083]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

This has happened to me many times with various versions, that after a BSOD, all tab groups **except the last one** were lost.

When trying to reproduce this, I crashed VSCode by killing certain process and after launching VSCode, tab groups were lost, except for the last one.

Then, when I tried to reproduce it again with gif capture, I wasn't able to kill "the right" process that would crash the VSCode in a same way so I could not reproduce this again... Long-pressing power button doesn't force my DELL XPS13 9370 to shut down, so I can't test it to reproduce the issue.

Steps to Reproduce:

- Open several groups of tabs.
- Crash computer/vscode

![image](https://user-images.githubusercontent.com/2313018/58125841-d321b280-7c11-11e9-9117-7f069099ae1b.png)

- Only the last group of tabs is restored, all other groups and their tabs are lost.

**Comment by ackvf** [comment]
Forgive me, but I have spent over an hour searching on the internet, reading through similar issues here in github and spent another half hour trying to reproduce and document this issue. I couldn't resolve the issue nor I was able to find an issue with this specific scenario.

After all, all my sessions were **restored** after the crash, but **wrongly**.

If you could at least point me to those issues, this one is a duplicate of, I would be grateful.

**Comment by ackvf** [comment]
So I was able to reproduce this issue 3 times in a row with `taskkill` command.
You can see that Group2 out of 3 is missing in the left window.

BEFORE:
<img width="1826" alt="01 0" src="https://user-images.githubusercontent.com/2313018/58270522-4fd79c80-7d8a-11e9-956f-989a922856cd.png">

AFTER:
<img width="1826" alt="02 13" src="https://user-images.githubusercontent.com/2313018/58270543-59f99b00-7d8a-11e9-9570-b279acda264e.png">

GIF:
![vscode-crash-tabs](https://user-images.githubusercontent.com/2313018/58270550-5d8d2200-7d8a-11e9-90e6-f1518eb574a3.gif)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/12058
