### ISSUE TITLE
Git detects 5k+ changes during a checkout

### ISSUE THREAD

**Issue by jineens** [microsoft/vscode#74087]
Issue Type: <b>Bug</b>

When I rebase between branches vscode says I have ~5k files with changes. This can be resolved by refereshing - which changes to 0 files changed, but it will not resolve on it's own. I noticed it goes from 0 files changed (before checkout) and then during the checkout process goes to ~5k files changed, and then finishes checkout out the branch. Did the logic change on when the pane refreshes?

This started happening today after I updated, but I've been using vscode for a while now and i've never seen this before (so it's very new).

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (56 x 2600)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.91GB (104.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-instant-markdown|dba|1.4.4
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
powershell|ms-|1.12.1
proto|pet|0.0.2
rewrap|stk|1.9.1
change-case|wma|1.0.0
clang-format|xav|1.9.0

</details>

**Comment by joaomoreno** [comment]
Once the 5K limit is reached, automatic git refreshing is disabled. One has to restart the workbench to get it working. Is it a normal use case for you to have such amount of changes?

**Comment by jineens** [comment]
The point was that I didn’t have any changes (I had 0 open files, actually). I was on master and then checked out my topic branch. (and now it’s happening most times I move between branches.)

Jineen

**Comment by joaomoreno** [comment]
Got it. Did you run the checkout in VS Code, or using the command line?

**Comment by jineens** [comment]
Command line.

________________________________

**Comment by joaomoreno** [comment]
And in the integrated terminal, or in an external one?

If you run the checkout via the command palette, does it reproduce?

**Comment by jineens** [comment]
I use the integrated terminal, it does not reproduce via the command palette.

Jineen

**Comment by joaomoreno** [comment]
Closing as designed.
