### ISSUE TITLE
move large files are too slow

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#74097]
Issue Type: <b>Bug</b>

I am trying to move a file.

eg. `node_modules/typescript/typescript.js`

It takes up a lot of CPU calculations and response slowly.

finally receive notification "extension host crash"

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 13, 17|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.4.3
vscode-browser-preview|auc|0.5.4
vscode-auto-schema|axe|0.1.0
vscode-changelog-generator|axe|0.3.1
vscode-gpm|axe|2.3.0
vscode-http-proxy|axe|0.1.3
vscode-imagemin|axe|0.5.1
vscode-markdown-script|axe|0.2.2
vscode-movie|axe|0.3.7
vscode-npm-import-package-version|axe|0.6.1
vscode-open-in-browser|axe|1.0.0
vscode-static-server|axe|0.3.1
vscode-django|bat|0.19.0
color-info|bie|0.5.1
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-tldr|bmu|1.0.0
EnglishChineseDictionary|Cod|0.0.11
gitignore|cod|0.6.0
path-intellisense|crz|1.4.3
vscode-eslint|dba|1.9.0
docs-yaml|doc|0.2.1
xml|Dot|2.4.0
gitlens|eam|9.7.4
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
vscode-diff|fab|1.4.0
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.132
vscode-nginx-conf-hint|han|0.1.0
svgeditor|hen|2.9.0
npm-dependency-links|her|1.0.1
px2rem-plus|hex|0.3.4
rest-client|hum|0.21.3
comment-translate|int|1.4.1
path-autocomplete|ion|1.13.3
vscode-jetbrains-keybindings|isu|0.1.8
vscode-placeholder-images|Jak|0.1.0
statusbarerror|Joe|0.3.0
vscode-deno|jus|1.3.1
github-gist-explorer|k99|0.0.9
vscode-colorize|kam|0.8.10
vscode-sshfs|Kel|1.16.2
graphql-for-vscode|kum|1.13.1
git-indicators|lam|2.1.1
image-resizer|luk|0.1.0
hexinspector|mat|1.0.0
rainbow-csv|mec|1.0.0
git-graph|mhu|1.5.0
dotenv|mik|1.0.1
vscode-filesize|mkx|2.1.2
vscode-language-pack-zh-hans|MS-|1.34.2
python|ms-|2019.4.12954
github-issues-prs|ms-|0.9.1
Go|ms-|0.10.2
typescript-javascript-grammar|ms-|0.0.50
vscode-typescript-tslint-plugin|ms-|1.1.0
vscode-gn|npc|1.0.0
vetur|oct|0.21.0
indent-rainbow|ode|7.4.0
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
nginx-formatter|ray|0.0.4
vscode-yaml|red|0.4.0
vscode-sort-json|ric|1.13.0
extension-update-reporter|ryu|1.0.3
px-to-rem|sai|1.2.7
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.2.9
vscode-nginx|sha|0.6.0
trailing-spaces|sha|0.3.1
gitconfig|sid|2.0.0
svg-preview|Sim|2.1.7
code-spell-checker|str|1.7.10
tabnine-vscode|Tab|1.1.0
vscodeintellicode|Vis|1.1.6
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.3.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders? 
https://code.visualstudio.com/insiders/
