### ISSUE TITLE
Can't open Git Source Control "More Actions" menu if commit message line is over max length

### ISSUE THREAD

**Issue by Tenrys** [microsoft/vscode#74091]
Issue Type: <b>Bug</b>

https://tenrys.pw/ShareX/2019/May/qoAg.webm

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.86GB free)|
|Process Argv|E:\Projects\GMod\novus\mingeban|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
glua|aSt|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
gitlens|eam|9.7.4
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.0.15
vscode-yarn|gam|1.6.0
vscode-glualint|goz|0.4.1
vscode-nginx-conf-hint|han|0.1.0
discord-vscode|icr|3.6.0
vscode-sshfs|Kel|1.16.2
Lua|key|0.0.9
git-indicators|lam|2.1.1
gmod-luadev|lix|0.1.2
HTMLHint|mka|0.6.0
vscode-apache|mrm|1.2.0
csharp|ms-|1.19.1
vsliveshare|ms-|1.0.249
vetur|oct|0.21.0
polacode|pnp|0.3.2
vscode-css-peek|pra|2.2.0
gi|rub|0.2.11
partial-diff|ryu|1.4.0
glassit|s-n|0.1.4
vue-vscode-snippets|sdr|1.6.0
code-settings-sync|Sha|3.2.9
vscode-nginx|sha|0.6.0
vscode-icons|vsc|8.6.0
snippet|vsc|0.5.1
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@sbatten Context views are competing.
