### ISSUE TITLE
serial port

### ISSUE THREAD

**Issue by Lemarchandl** [microsoft/vscode#74109]
Issue Type: <b>Bug</b>

When trying to connect to pysense, it try to connect to the bad port. It is impossible to change the port  to launch the code

Extension version: 1.1.2
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.43GB (10.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details>

**Comment by alexr00** [comment]
Are you using the Python extension?

**Comment by Lemarchandl** [comment]
No i'm using the Pymakr extension. I finally managed to forced it with the .json and .conf but I can't use the autoconnect option

________________________________
De : Alex Ross <notifications@github.com>
Envoyé : mercredi 22 mai 2019 12:04:03
À : microsoft/vscode
Cc : Lemarchand Lucie; Author
Objet : Re: [microsoft/vscode] serial port (#74109)


Are you using the Python extension?
