### ISSUE TITLE
Global Keyword search is too Slow

### ISSUE THREAD

**Issue by lightyaer** [microsoft/vscode#74100]
All the previous issues on this topic were closed due to inactivity.
Referencing #33254 #65945  #73931 

Global searching a keyword(shift + cmd/ctrl + f) is too slow to be productive.

- VSCode Version: 1.34
- OS Version: MacOS 10.14.5

Steps to Reproduce:
1. Use a huge project with a lot of symlinks or webpack aliases
2. Search a keyword in it

Usually takes a lot of time about a minute or so, or maybe 30s sometimes,
 
Expectation to be snappy like file search.

One fix could be introduce some sort of indexing for fast search.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Is it faster if you disable `search.followSymlinks`?

**Comment by lightyaer** [comment]
Nope, it takes a good 15 seconds to get the first result, then at 30 seconds it completes, if I search a keyword which in like 3 places in the project even after disabling `search.followSynlinks`.

if I search a fairly common keyword, like `import _ from 'lodash'`, then its kinda quick.

I expect it to snappy like in Webstorm.

**Comment by roblourens** [comment]
Other possible workarounds are excluding some folders that you don't need with the exclude settings or just opening a subfolder in your workspace. There are some other tips written up here: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by lightyaer** [comment]
Anyways, that's not the point, I wanted some sort of indexing so that global search doesn't hog up so many resources, especially when I'm doing it very often, I'm sure you have other priorities, but please add it to the roadmap.

For expectation on how it should work, please check global search `(ctrl/cmd + shift + f)` in  [webstorm](https://www.jetbrains.com/webstorm/)
