### ISSUE TITLE
Different behaviors when open symlink folder in VS Code

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#74104]
- VSCode Version: 1.34.0 & 1.35.0 - insider
- OS Version: MacOS Mojave 10.14.5 & Fedora Workstation 30

Steps to Reproduce:

1. Prepare a folder as a workspace folder in VS Code, let's name it as `demo`
2. Generate a symlink for that folder: `ln -s demo demolink`
3. Open the symlink `demolink` in VS Code

### Behavior on MacOS Mojave
The VS Code will open the folder `demo` as the workspace folder.

<img width="295" alt="Screen Shot 2019-05-22 at 1 23 15 PM" src="https://user-images.githubusercontent.com/6193897/58149283-cf833f80-7c94-11e9-9347-3a42e62dbb14.png">

### Behavior on Fedora
The VS Code will open the folder `demolink` as the workspace folder.

<img width="270" alt="Screen Shot 2019-05-22 at 1 22 18 PM" src="https://user-images.githubusercontent.com/6193897/58149290-d9a53e00-7c94-11e9-9b38-d5db16200d44.png">

Because of the differences, some APIs calling behavior will become different as well. For example, when calling `workspace.getWorkspaceFolder(uri)`.

**Comment by bpasero** [comment]
there should be no differences, help wanted to investigate + fix if possible 👍

**Comment by bpasero** [comment]
@jdneo I cannot reproduce, here is what I did
* followed your instructions how to get the linked folder
* from the command line type code `demolink`
* result:

![image](https://user-images.githubusercontent.com/900690/58372080-cacebd80-7f18-11e9-9465-e46dada6197f.png)

**Comment by jdneo** [comment]
@bpasero it seems that you are using macos? Could you please try it on Fedora? I can repro it on Fedora 30

**Comment by bpasero** [comment]
@jdneo I do not see an issue with that, you are asking Code to open the link and it does. Do you expect to follow the symlink when opening?

**Comment by hwhung0111** [comment]
I can reproduce it. And I get the same result while opening files. 

Step to reproduce:
1. `touch demo.txt`
2. `ln -s demo.txt demolink.txt`
3. open both of these files in vscode insider
In debian: the file name on the editor will show `demo.txt` and `demolink.txt` respectively. 
In macos: both of these will show `demo.txt` 
4. `mv demolink.txt folder/`
5. Open the demolink.txt in folder
The file name will show `demolink.txt` in macos.

The issue might happen on macos.

**Comment by jdneo** [comment]
Hi @bpasero,

Sorry for the late reply. I was on vacation days before.

Regarding the issue, actually, I'm not sure what's the right behavior should be. But the thing I've observed is that the name of the opened folder is not the same on Mac and Linux. Please let me know anything I can help to help you reproduce the issue.

**Comment by bpasero** [comment]
The right behaviour in VSCode is to not follow the symlink but actually open it as instructed by the user. However this probably also depends on how the file was opened, e.g. from a native dialog or not.

@hwhung0111 @jdneo thanks for providing steps, but you are missing to tell me how you actually open the file. Just to give an example, here are various ways how you can open files in VSCode:
* from the command line directly
* from File > Open
* from the VSCode explorer by clicking on it
* via quick open when typing the name of the file

**Comment by jdneo** [comment]
I see. For me, I'm using `File` > `Open` to open the symlink.

**Comment by hwhung0111** [comment]
I also open from File > Open. For me, macos don't have the same behavior even I open the same symlink.

**Comment by jdneo** [comment]
Hi @bpasero,

Can we repro this issue? I have several users who have encountered the same problem. It would be great if VS Code can fix this.

**Comment by bpasero** [comment]
I do not think VSCode can do anything because we get the path from the system dialog and do nothing with it. I suspect platform differences here with the path we get back from the system dialog via Electron.

**Comment by Spongman** [comment]
this is a disaster, it completely messes up the git panel. `.gitignore` handling is broken, all the changed paths are listed as absolute paths. unusable.

**Comment by amgodoi** [comment]
Hi @jdneo 

As a workaround you could open the folder from command line:

$ code .

I got the same behavior described for @bpasero and it is system dialog dependent. My system is using "GtkFileChooserDialog" to open files and directories ... I have a lot o problems with other applications too. I am Using ubuntu 22.04 with gtk4 and I think this is the problem ... gtk4 is not working properly yet.

**Comment by mat-wang** [comment]
The same issue happened on

> Linux code-capsule 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux

I'm using vscode tunnel to develop java project.

The application could run as formal, but when test, it shows the error.

**Comment by mat-wang** [comment]
> The same issue happened on
> 
> > Linux code-capsule 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
> 
> I'm using vscode tunnel to develop java project.
> 
> The application could run as formal, but when test, it shows the error.

I found an interesting thing during duplicating this issue:

- Server: 
  - Vscode CLI 1.85.1 (commitee: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2)
  - OS Version: Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
  - Test Runner for Java: v0.40.1

- Test Client1: 
   - Client: Microsoft Edge (120.0.2210.91 (64 bits))
   - OS Version: Windows 11 Professional 23H2
  
- Test Client2: 
  - Client: Visual Studio Code 1.85.1 (commitee: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2)
  - OS Version: Same as test client 1

Tested project is a simple project built by [spring initializr](https://start.spring.io/) and just add spring web as dependency.

There is no error shown when I connect the tunnel from test client 2 (using VS Code), and all things going as normal. However, when I connect the tunnel from test client 1 (using vscode.dev/tunnel/my-tunnel), this issue happened.

Hope these info could help someone to figure this out~
