### ISSUE TITLE
Using env.openExternal() should automatically forward ports

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74105]
I was under the impression that the new `env.openExternal()` function in VS Code was specifically to support automatically forwarding ports (like happens automatically with `serverReadyAction`) but in my testing, this doesn't seem to be the case.

I'm not sure if this is a) a bug or b) a feature request, nor whether it belongs a) here or b) in VS Code, so feel free to point me elsewhere if appropriate :-)

**Comment by DanTup** [comment]
@chrmarti ah, we're using `127.0.0.1` (for ex. `http://127.0.0.1:39941/522LRE1U5xk=/`). The reason for this is that using localhost we sometimes have issues where the binding process resolves to 127.0.0.1 and then the connecting process resolves it to `::1` and fails. I think you've had this in places before (for ex. https://github.com/microsoft/vscode-remote-release/issues/215).

Could `127.0.0.1` and `::1` by included in the auto-forwarding?

**Comment by mjbvz** [comment]
Tracked by https://github.com/microsoft/vscode-remote-release/issues/108

Originally by-design since using `127.0.0.1` gives webviews a way to ensure they are accessing the local machine but we can reconsider this

**Comment by DanTup** [comment]
Thanks, I've added a comment to that. If it's not going to be supported, I think there should at least be an API to forward ports ourselves to handle this (without spawning a browser) so that we can work around it. This blocks a few things for me, as I can't change the behaviour of some of the tools that are binding the ports.
