### ISSUE TITLE
Unable to install Remote-WSL on Mac OS 10.14.4

### ISSUE THREAD

**Issue by trishulpani** [microsoft/vscode#74101]
Issue Type: <b>Bug</b>

Trying to install VS Code Remote-WSL on VS Code (v1.34.0) shows the following error:
"Unable to install because, the extension 'ms-vscode-remote.remote-wsl' compatible with current version '1.34.0' of VS Code is not found."

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv|-psn_0_9423100|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Please see documentation [here](https://code.visualstudio.com/docs/remote/remote-overview). You need the latest insiders.
