### ISSUE TITLE
Add command ID for 'Collapse All' in Files Explorer

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#7411]
I would like to setup a keyboard shortcut for this action, but there is no corresponding command ID.

**Comment by bpasero** [comment]
I have added `workbench.files.action.collapseFilesExplorerFolders` and `workbench.files.action.refreshFilesExplorer` as global actions. I also added `explorerViewletVisible` as context if you want to assign a keybinding that only runs when the explorer is visible.

**Comment by OliverJAsh** [comment]
That's lovely, thank you! Will it be available in the Insiders release tomorrow?

**Comment by bpasero** [comment]
@OliverJAsh yes :)
