### ISSUE TITLE
up/down keys not working in ui settings

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#74115]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:53.881Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 10.0.10586

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
I need you to explain exactly what the issue is, please be very specific.

**Comment by byehack** [comment]
> I need you to explain exactly what the issue is, please be very specific.

thanks for your reply.
when we are in the ui settings we must use scroll to go to up/down settings. it is very hard when there are a lot of settings. currently is not possible to move the page slowly with up/down key in the ui settings page. currently the up/down key don't do anything in the settings ui. and i should use tab key for this and it isnt good choose for me

**Comment by roblourens** [comment]
Ok, yes I am tracking that here: https://github.com/microsoft/vscode/issues/66237
