### ISSUE TITLE
problem with show extension details,contributions,changelog

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#74118]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:53.881Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 10.0.10586

when this occur the and i am in full-screen mode the `alt` key doesnt work

![Screenshot (657)](https://user-images.githubusercontent.com/26390254/58164778-b6ca5800-7c9b-11e9-835a-f6ea595dd620.png)

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by byehack** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

latest build but not with all extensions disabled

**Comment by mjbvz** [comment]
Can you please try going through your extensions then to see which one is causing this

**Comment by byehack** [comment]
> Can you please try going through your extensions then to see which one is causing this

worked thanks.
