### ISSUE TITLE
Installer unnecessarily claims reboot necessary for PATH additions

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#74116]
Issue Type: <b>Bug</b>

The vscode installer unnecessarily claims a reboot is necessary for PATH additions:

![image](https://user-images.githubusercontent.com/172594/58163888-af478680-7c7c-11e9-9c2b-851fc26e71f3.png)

'Requires restart' is a bit vague, but may imply it's necessary to restart the entire Windows kernel to add something to path (which surely isn't the case).

This should probably read:

> Add to PATH (restart shell to see changes)

Or

> Add to PATH (requires shell restart)

etc.

VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:18:31.618Z)
OS version: Windows_NT x64 10.0.18898

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mikemaccana** [comment]
@vscodebot you are wrong about this being integrated-terminal. You are always erong.

**Comment by joaomoreno** [comment]
I'd argue that, although probably correct, a "shell restart" is not a common enough concept that would warrant changing this and risking getting users confused on what that actually means.

**Comment by mikemaccana** [comment]
@joaomoreno That's a good point - the term 'shell' is ambiguous on Windows. 

I think better, more accurate messaging is still possible - and may save users from either restarting their OS unnecessarily or thinking Windows needs to be restarted when it doesn't.

Maybe @bitcrazed could provide some thoughts here - he's written a lot about termina, shell etc on Windows and it would be good to be consistent.

Here are a few altrnatives that don't suggest an OS restart:

# 1 use 'Terminal'

> Add to PATH (restart your terminal app to see the change)

A terminal app is more specific (that's the term used by eg, Windows Terminal). Although technically only the command shell needs restarting, 'Terminal' means the command line, unambiguously. 

# 2 use 'Command shell'

> Add to PATH (restart your command shell to see changes)

Since 'shell' could mean explorer.exe, saying 'command shell' is a good way to distinguish we mean pwsh, bash, cmd, zsh, etc.

# 3 mention specific command shells

> Add to PATH (restart pwsh, powershell, bash, etc to see changes)

What do you think? Also @bitcrazed?

**Comment by joaomoreno** [comment]
I think that we should go with the worst common denominator: suggest to restart. At best we can rephrase to `might require restart`.

**Comment by mikemaccana** [comment]
Hi Joao. Visual Studio *proper* may add debug symbols to Windows, requiring the entire OS to be restarted. vscode does not do this, and hence does not require the OS to be restarted. If I'm not correct on that please let me know.

I agree the lowest common denominator approach is best, but that is restarting the terminal app. Restarting the terminal app may not be necessary (we actually just need to restart the shell) but restarting is guaranteed to apply the changes, and there's no ambiguity there.

**Comment by mikemaccana** [comment]
>a "shell restart" is not a common enough concept 

Note the vscode release notes also expect that users are familiar with the term 'shell':

![image](https://user-images.githubusercontent.com/172594/59020845-b062e100-8842-11e9-9e5e-8fa5d0301e65.png)


@joaomoreno why was this closed? It might take some discussion to find the best language but restarting the entire OS clearly isn't necessary.

**Comment by joaomoreno** [comment]
I've seen situations in which new shells do not have Code in the path after installing. I've also seen situations in which they do. Not being a Windows expert, and not understanding the full scope of the problem, I opted for the lcd: suggesting to restart.

For those reasons, I'd rather keep this message in. Again, at best we can add a `might` in there, if you really feel passionate about it.

**Comment by mikemaccana** [comment]
> I've seen situations in which new shells do not have Code in the path after installing. 

That sounds like a bug - if you can replicate it, you should file it as one.

The Windows kernel absolutely does not need to be restarted to add an item to PATH. You work at Microsoft and have access to experts in this area who can confirm this.

**Comment by joaomoreno** [comment]
Alright, removed it. I'll be going after you if this bites back. 🏃

https://twitter.com/mikemaccana/status/1136594325251534848

We are watching. 👀

**Comment by mikemaccana** [comment]
Thanks Joao! 😃 And fair enough. 🙂

Maybe add "requires shell restart" - that really should be the lowest common denominator.

**Comment by joaomoreno** [comment]
Pushed!
