### ISSUE TITLE
Vscode 提示 Code 安装似乎损坏。请重新安装。

### ISSUE THREAD

**Issue by codegrady** [microsoft/vscode#74112]
- VSCode Version:  1.34.0 (1.34.0)
- OS Version: macOS Mojave  10.14.5 (18F132)

Steps to Reproduce:

1.  When I open or restart vscode ,always remind 'Code 安装似乎损坏。请重新安装。'
2. When reinstall vscode , remind me again.

**Comment by byehack** [comment]
this is for an extension.

**Comment by sandy081** [comment]
This could be due to an extension you have installed. Please find out the extension (by disabling) that is causing it and report the issue against it.
