### ISSUE TITLE
Extensions panel hangs forever

### ISSUE THREAD

**Issue by davidemania** [microsoft/vscode#74124]
The extensions manager hangs forever (see attached picture). No extensions are shown.

Developer tools console only shows "[Extension Host] debugger listening on port 60420"

- VSCode Version: 1.35.0-insider (1.35.0-insider) 4ca38ce5584d7cd67b435b3c32ef1240c6a29628
- OS Version: macOS 10.13.3 (High Sierra)

Steps to Reproduce:

1. open VS Code Insiders
2. click on the extensions button

Does this issue occur when all extensions are disabled?: Yes

![Schermata 2019-05-22 alle 12 59 20](https://user-images.githubusercontent.com/6617948/58169907-4cf98080-7c92-11e9-961c-620c52fcea39.png)

**Comment by davidemania** [comment]
After clearing "$HOME/Library/Application Support" directory and restarting VSCode the issue did not show anymore. The old content of the directory is available should someone wants to have a look at it for debugging.

**Comment by jonathan-dilorenzo** [comment]
I'm having the same issue, but I'm on Ubuntu 18.04.2 LTS and am not sure what the moral equivalent of the suggested solution is. Trying to show existing extensions also doesn't work.

Developer tool console shows a bunch of stuff. I wiped out names with the assumption that they're not important.
Before clicking Extensions:
```
workbench.js:7 renderer did not receive lazyEnv in time
(anonymous) @ workbench.js:7
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3272 [Extension Host] debugger listening on port 60601
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] Sync : Connected with user : [name]
```

After I click Extensions:
```
[Extension Host] Sync : File Change Detected On : /home/[name]/.config/Code/User/workspaceStorage/d7aa10e13438a7aa3d61618e375c26d3/state.vscdb-journal
workbench.main.js:238 [Extension Host] Sync : File Change Detected On : /home/[name]/.config/Code/User/workspaceStorage/d7aa10e13438a7aa3d61618e375c26d3/state.vscdb
workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: Error: EEXIST: file already exists, open '/home/[name]/.config/Code/User/sync.lock'
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:238 [Extension Host] stack trace: Error: EEXIST: file already exists, open '/home/[name]/.config/Code/User/sync.lock'
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3178
_doInvokeHandler @ workbench.main.js:3252
_invokeHandler @ workbench.main.js:3252
_receiveRequest @ workbench.main.js:3251
_receiveOneMessage @ workbench.main.js:3249
_protocol.onMessage.e @ workbench.main.js:3248
fire @ workbench.main.js:77
a @ workbench.main.js:321
e @ workbench.main.js:321
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:330
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:327
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:323
_register._socket.onData.e @ workbench.main.js:323
t @ workbench.main.js:332
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:1402   ERR EEXIST: file already exists, open '/home/[name]/.config/Code/User/sync.lock': Error: EEXIST: file already exists, open '/home/[name]/.config/Code/User/sync.lock'
```

Looks like maybe an issue with the sync extension?

- VSCode Version: 1.34.0
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:

1. open VS Code
2. Click on the extensions button

Does this issue occur when all extensions are disabled?: No idea, I'm not sure how to disable them without the panel :(

**Comment by evertiro** [comment]
Yet another report on Linux (Pop!_OS, specifically).

**Comment by evertiro** [comment]
For what it's worth @jonathan-dilorenzo I did a complete purge, updated the `mlocate` database, and removed any leftover files that it could come up with related to VSCode, then reinstalled and still had the same issue. Don't think the proposed fix is a relevant on Linux...

**Comment by sandy081** [comment]
@davidemania Are you still able to repro with old content (directory)?

**Comment by jonathan-dilorenzo** [comment]
I am still having this problem. Please let me know precisely what information you require and I will do my best to provide it.

**Comment by sandy081** [comment]
@jonathan-dilorenzo Please update to latest insiders and try. 

Please check all Log (..) channels in Output panel
Please check the console by opening developer tools

Provide us above information.
