### ISSUE TITLE
Can't unit test code that calls the openExternal API

### ISSUE THREAD

**Issue by sstone1** [microsoft/vscode#74121]
Same issue as #69608, not sure why that has been closed without a fix.

It is difficult/impossible to write automated unit tests for extensions that call the openExternal API, as it cannot be stubbed (using sinon or other such library), and so you cannot stop it opening browsers (not ideal in CI/CD pipelines), or make assertions that it was actually called.

This happens because the `vscode.env` object is frozen:

https://github.com/microsoft/vscode/blob/d5534b86040250bc69bd34438062caa1c20d36d8/src/vs/workbench/api/node/extHost.api.impl.ts#L237

Sinon cannot stub methods/properties of frozen objects, so you get the following error message:

```
TypeError: Cannot redefine property: openExternal
      at Function.defineProperty (<anonymous>)
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:95:16)
      at stub (node_modules/sinon/lib/sinon/stub.js:76:44)
      at Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:311:33)
```

Does the env object really need to be frozen? None of the other API objects appear to be frozen.

**Comment by jrieken** [comment]
What exactly are you testing? That you are making the right call to the API? that the API does the right thing? Can you not test the argument you are going to call `openExternal` with instead of stubbing openExternal?

**Comment by sstone1** [comment]
> That you are making the right call to the API?

**Comment by jrieken** [comment]
Freezing is something we do to prevent extensions to change the API for other extensions, however that's also from a time where extensions would share the same API instance. I will push a change that doesn't freeze the env object when running tests.
