### ISSUE TITLE
Allow that folded range starts below the line with the folding marker

### ISSUE THREAD

**Issue by jimmyko** [microsoft/vscode#74122]
Currently, the code folding is working as below.
```js
// before code folding
const func = () =>
{
  // dummy code line 1
  // dummy code line 2
  // dummy code line 3
}

// after code folding
const function = () =>
}
```
```html
<!-- before code folding -->
<div id="dummy-id"
    class="dummy-class"
    data-dummy="dummy-data"
    data-dummy2="dummy-data2">
    dummy text line 1
    dummy text line 2
    dummy text line 23
</div>

<!-- after code folding -->
<div id="dummy-id"
</div>
```

This folding method hides some important information and looks misleading that the start of code block is incomplete

I would suggest to have extra settings option for changing the folding behaviour as below. it looks more make sense to me.

```js
// before code folding
const func = () =>
{
  // dummy code
}

// after code folding
const function = () =>
{
}
```
```html
<!-- before code folding -->
<div id="dummy-id"
    class="dummy-class"
    data-dummy="dummy-data"
    data-dummy2="dummy-data2">
    dummy text line 1
    dummy text line 2
    dummy text line 23
</div>

<!-- after code folding -->
<div id="dummy-id"
    class="dummy-class"
    data-dummy="dummy-data"
    data-dummy2="dummy-data2">
</div>
```

**Comment by aeschli** [comment]
Note that it's up to each folding provider to define which lines are folded and which ones stay.

But intsead of keeping multiple lines I think the right approach is if we allow folding providers to define a custom text for the folded line: #70794. That text could also e.g. show the HTML tag as well as the attributes.

**Comment by aeschli** [comment]
Closing in favor of #70794. Please speak up if you disagree.
