### ISSUE TITLE
File explorer not updating

### ISSUE THREAD

**Issue by JLa2r** [microsoft/vscode#74128]
Issue Type: <b>Bug</b>

Not sure how to reproduce, but the "file explorer" was not correctlying displaying items within a subfolder. I tried the refresh button in "file explorer" but it did not update. I was able to search for a file within the folder and it opened, but still did not show any items in the folder. I dragged the file from Window Explorer into the VS Code window, at which time the "file explorer" view updated to display the contents of the folder.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.17GB free)|
|Process Argv|TEXT-REMOVED-BY-USER|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
vscode-tfs|gen|1.0.1
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.7.0

</details>

**Comment by isidorn** [comment]
Can you try to get more precise steps?
F1 > developer tools > console > do you see some errors there?
