### ISSUE TITLE
[html] path intellisense <input type="image" src="/">

### ISSUE THREAD

**Issue by nn-hh** [microsoft/vscode#74129]
The following is supported.
`<img src="/">`

But, the following is not supported.
`<input type="image" src="/">`
![test](https://user-images.githubusercontent.com/38947828/58172715-425fdb00-7cd4-11e9-8d93-8f4791c2accd.jpg)

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/58191417-5f17f680-7c73-11e9-9527-b93c3686ac51.png)
