### ISSUE TITLE
VSCode freezes with Clangd extension

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#74120]
- VSCode Version: 1.35-insider 4ca38ce5584d7cd67b435b3c32ef1240c6a29628 (latest as of now)
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Set up the *Remote - SSH* and *vscode-clangd* extensions.
2. Work on a C++ project remotely for a while. Sometimes when you open a file the entire VSCode UI freezes. It usually recovers after about 5 minutes. The freeze is always immediately after opening a file.

I have tested without the vscode-clangd extension installed, and the problem does not seem to occur (it's quite random when it happens), so I am fairly sure it is a problem with that extension.

However surely an extension shouldn't be able to make VSCode freeze since everything is done asynchronously via JSON?

Here's the output from the `vscode-clangd` extension - you can see where it froze for 3 seconds in this case:

```
I[10:48:21.861] <-- textDocument/didClose
I[10:48:22.368] <-- textDocument/didOpen
I[10:48:22.368] --> textDocument/clangd.fileStatus
I[10:48:22.369] Updating file /home/me/project/MyFile.cpp with command [/home/me/project] /usr/bin/clang++ <the build command for MyFile.cpp - sorry there's some private info in here>
I[10:48:22.411] <-- textDocument/codeAction(13)
I[10:48:22.411] --> reply:textDocument/codeAction(13) 0 ms
I[10:48:22.412] <-- textDocument/documentSymbol(14)
I[10:48:22.453] <-- $/cancelRequest
I[10:48:25.719] --> textDocument/publishDiagnostics
I[10:48:25.732] --> reply:textDocument/documentSymbol(14) 3319 ms
I[10:48:25.732] --> textDocument/clangd.fileStatus
I[10:48:54.158] <-- textDocument/hover(15)
I[10:48:54.163] --> reply:textDocument/hover(15) 5 ms
I[10:48:54.164] --> textDocument/clangd.fileStatus
```

Between these two lines the UI is completely unresponsive:

```
I[10:48:22.453] <-- $/cancelRequest
I[10:48:25.719] --> textDocument/publishDiagnostics
```

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
