### ISSUE TITLE
Arch Linux AUR/community package

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#7412]
- VSCode Version: 1.2.0
- OS Version: Arch Linux

vscode is (as expected) available via 3rd-party maintained PKGBUILD's in the AUR, but I think it would be much better if MS officially provided the PKGBUILD script to AUR (if desired, it can just wrap installation from the existing .deb as many AUR packages do).
This would really help increase confidence in the packages legitimacy and that the install script is genuine and trustworthy. It's also a great statement for MS to make, and really not a lot of work.
I suspect the package would quickly be promoted to the community or extra repos with such 'official' backing, which allows pacman to access vscode without additional tooling.

**Comment by Tyriar** [comment]
@TurkeyMan you'd be interested in the discussions at https://github.com/Microsoft/vscode/issues/6484 and https://github.com/Microsoft/vscode/issues/6495

**Comment by TurkeyMan** [comment]
Awesome, looks like you're already on it!
I'm confident it'll be promoted from AUR in no time if there is a system in place for coordinating with the package maintainers.

**Comment by Tyriar** [comment]
@TurkeyMan well, I was going to go and do more but the existing maintainer made some good points https://github.com/Microsoft/vscode/issues/6495#issuecomment-220158936

The expertise and time arguments are very good, I haven't used Arch Linux and I have my toes in a lot of other stuff within vscode. Learning how to and then setting up an official repository like this takes time away from other stuff.

One thing I was considering we could do was 'blessing' community led efforts, like how Chrome does (or did do, I think the package wiki page broke when they change something). So setting up a page on the website which featured links to the various repos.

**Comment by TurkeyMan** [comment]
Ah, well if you haven't used arch, you're missing out! Difficult to go back once you've seen the light ;)

Linking to arch repos or packages from the website is not necessary, that's not the arch way. Perhaps just a comment that vscode is available from the AUR (or pacman if it gets promoted) with the package name and a little Arch icon somewhere so people know it's available at a glance and that it's endorsed. That's the main attraction of arch, the community just take care of software distribution via pacman and the AUR. There's no manual package installs, no PPA's to wrangle or keep track of, no major version numbers or periodic releases. AUR is a backup plan for when software isn't present on official repos (it's never failed me yet!), but quality packages always seem to make it into 'community' or 'extra'.

Your cooperation with the maintainer is great. Nudge him with an early link to the new build before releases go live, and it might not hurt to incorporate a test into your test plan that the Arch package is available promptly prior to release, then you can send a prompt email if it's not.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode-docs/issues/369
