### ISSUE TITLE
Unable to write program user data when invoking VS Code Portable in a singularity image

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#74130]
**Problem description:**
I am trying to install vs code inside a singularity image. I, unfortunately, haven't been able to do this as I keep running into some problems. I first tried to install vs code inside the container using the[ .dep package](https://code.visualstudio.com/Download). However, as inside this container, the *vs code* program doesn't have write permissions to the user data and data folder on the main system it wont start. To solve this I tried using the portable version as this is explained in the [vscode portable documentation](https://code.visualstudio.com/docs/editor/portable). Unfortunately, also this gave me the `user-data and data directories should be writable` error.

**System information:**
- VSCode Version: 1.34.0
- OS Version: Ubuntu 16.04 (Singularity container)

**Steps to Reproduce:**
1. Install singularity according to [this guide](https://www.sylabs.io/guides/3.2/user-guide/).
2. Build a ubuntu 16.04 singularity image by running the following command:
`sudo singularity build --sandbox ubuntu1604 docker://ubuntu:16.04`
3. When finished run the shell as sudo by using `sudo singularity run --nv --writable ubuntu1604`
4. Download the lates tar.gz and unzip it:
```
curl -L "https://go.microsoft.com/fwlink/?LinkID=620884" > vscode-stable.tar.gz
tar xzf vscode-stable.tar.gz
```
5. Go into the *VSCode-linux-x64* folder.
6. Create a *user-data* and *data* folder as explained in the [vscode portable documentation](https://code.visualstudio.com/docs/editor/portable).
7. Try to run the VSCode program by executing `sh ./bin/code`.
8. You will now get the following error message:

![image](https://user-images.githubusercontent.com/17570430/58173708-5ab40380-7c9c-11e9-81dc-96abfaf69f64.png)

This can be solved by running the shell as sudo but as this has some risks I was wondering if I can solve the error so that I can run vscode as a normal user from within a singularity container.

**Extra information:**
Does this issue occur when all extensions are disabled?: Yes

**--verbose output:**
``Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[9043:0522/143121.884272:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[main 2019-05-22T12:31:27.080Z] Error: listen EACCES /run/user/1000/vscode-5f7fbcc5-1.34.0-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1477:5)
    at Promise (/jan/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:184:637)
    at new Promise (<anonymous>)
    at Object.t.serve (/jan/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:184:574)
    at n (/jan/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:490:263)
    at R (/jan/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:492:559)
    at l.invokeFunction (/jan/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:221:331)
    at then (/jan/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:494:347)
[main 2019-05-22T12:31:27.084Z] Lifecycle#kill()``

**Comment by joaomoreno** [comment]
This sounds more like an issue with how you configured the container. Just make sure those folders are writable by whatever user Code is run as.

**Comment by rickstaa** [comment]
@joaomoreno thanks for your response. I moved the issue to the [singularity repository](https://github.com/sylabs/singularity/issues/3609) since I think this is indeed caused by a misunderstanding on my side on how singularity sets its user and group permissions.

**Comment by rickstaa** [comment]
@rherban of the singularity repository looked into my issue and stated that he thinks this issue is caused by a deeper issue with vscode. This can be seen from the fact that while vscode gives the error writability error (see below) is is able to write data to the two data folders.

![image](https://user-images.githubusercontent.com/17570430/58405914-cd402d00-8068-11e9-9dfe-429c4a3f84f1.png)

This can be seen from the fact that after the error is displayed visual code appears to have populated the two folders with files.

```
[ricks@vscode]:~$ tree VSCode-linux-x64/data/
VSCode-linux-x64/data/
├── extensions
└── user-data
    ├── Backups
    ├── CachedData
    │   └── 5e1f9440d280b0b04cba843df6a0032bf517a2f0
    │       ├── bom-handling-b1716cdee35ff4762811cdcc843d7e96.code
    │       ├── dialog-34d1f7eee309f38a5250515ce6dcdb2b.code
    │       ├── extend-node-07ba1a9859a18c5869c4e0f59e54c27d.code
    │       ├── index-2a8af058d3e45af3b803c37f72a9379d.code
    │       ├── index-df4365cf379486c71562b3dc7304f303.code
    │       ├── main-7d4c18276698f568d0569214f70350a5.code
    │       ├── main.nls-90db9fc49f10cddf806fc31152c6dd1e.code
    │       ├── safer-1a434c00da794394212555f5808d94d1.code
    │       └── streams-e0cd9dcbbe043b48a9f4efe0e37b647f.code
    ├── logs
    │   ├── 20190524T110722
    │   ├── 20190524T111335
    │   ├── 20190524T113408
    │   ├── 20190524T113522
    │   ├── 20190524T124920
    │   └── 20190524T125223
    └── User
        ├── globalStorage
        └── workspaceStorage

15 directories, 9 files
```

**Comment by truatpasteurdotfr** [comment]
can you retry with the singularity flag `-B /run` and without it? code starts fine with `-B /run` but yields the same misleading errors.

**Comment by rickstaa** [comment]
@truatpasteurdotfr that indeed solved my problem! I can however not find anything on the -B flag inside the documentation. Can you explain to me what it does?

**Comment by rickstaa** [comment]
The solution given by @truatpasteurdotfr solved my problem and therefore is a good workaround for people that experience the same issue. @joaomoreno do you maybe know why *vscode* needs access to the `/run` directory to run inside a singularity image. As @truatpasteurdotfr pointed out on the [related singularity issue](https://github.com/sylabs/singularity/issues/3609) google chrome, and the brave browser also require the `/run` directory to run.

**Comment by joaomoreno** [comment]
Oh I see what's happening:

The `XDG_RUNTIME_DIR` is taking precedence, regardless of portable. That is definitely wrong. Must fix.

**Comment by rickstaa** [comment]
@joaomoreno Thanks a lot for looking into it? Is there a way to watch this bug so I know when it is fixed? I looked into the may 2019 milestones but it is already closed there.

**Comment by rickstaa** [comment]
Ah, I tested it out and this bug appears to be fixed! Thanks a lot, @joaomoreno.

**Comment by joaomoreno** [comment]
It was fixed today, so the next Insiders build (tomorrow) will have the fix. The next stable (next week) will have the fix.
