### ISSUE TITLE
Exclusive Ranges and TextEditorCursorStyle.Block problem.

### ISSUE THREAD

**Issue by aminroosta** [Microsoft/vscode#7413]
For a [vim plugin](https://github.com/aioutecism/amVim-for-VSCode) we are using `TextEditorCursorStyle.Block` to style the cursor in vim visual mode.

But Selection and Ranges are not inclusive in vscode, that's why the character behind the cursor is not selected in the range.

<img width="231" alt="screen shot 2016-06-08 at 5 06 26 pm" src="https://cloud.githubusercontent.com/assets/2920178/15894615/06575456-2d9c-11e6-9eb4-ee23c2ed935c.png">
<img width="239" alt="screen shot 2016-06-08 at 5 06 38 pm" src="https://cloud.githubusercontent.com/assets/2920178/15894616/065f2fa0-2d9c-11e6-99b5-96fc3ff05006.png">

As you can see in the image above.
I recommend one of the following:
1- supporting inclusive ranges
2- adding option to explicitly set cursor position irrelevant of `window.activeTextEditor.selections` array.

**Comment by alexandrudima** [comment]
I suggest to use cursor style line when in visual mode.
