### ISSUE TITLE
Code Helper 300% CPU Usage on Mac OS (10.14.1 )

### ISSUE THREAD

**Issue by cyberz** [microsoft/vscode#74138]
Issue Type: <b>Performance Issue</b>

Extra excludes
"files.watcherExclude": {
        "**/.DS_Store/**": true,
        "**/.nuxt/**": true,
    },
    "files.exclude": {
        "**/.nuxt": true,
        "**/node_modules": true
    }

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (vin.js — repo)
|    Folder (repo): 416 files
|      File types: js(161) woff(48) ttf(48) eot(48) vue(19) json(14) env(12)
|                  DS_Store(10) md(10) html(8)
|      Conf files: package.json(6) webpack.config.js(4);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.0
vscode-angular-html|gha|1.1.1
vscode-angular-components-intellisense|ipa|1.0.0
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.22
dotenv|mik|1.0.1
vetur|oct|0.21.0
webstorm-icons|pms|1.0.0

(4 theme extensions excluded)

</details>

**Comment by FusionBY** [comment]
As a temp solution, you can decrease your VS Code typescript version to 1.3.3333. It was helped me. Other proposes had zero results.
Here you can find how to specify typescript version.
https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by cyberz** [comment]
> Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

![f9d2e630f2](https://user-images.githubusercontent.com/2190074/58323537-ee1c3e80-7e2c-11e9-8a3c-7422d5bdc7a1.jpg)



> As a temp solution, you can decrease your VS Code typescript version to 1.3.3333. It was helped me. Other proposes had zero results.

I downgraded VS Code to 1.33.1 and It helped.

**Comment by mjbvz** [comment]
That trace shows no cpu usage from code. Are you sure you captured this when the high cpu usage was happening?

**Comment by SirCameron** [comment]
I have the same issue. I've disabled all the extensions and added node_modules et al to watcherExclude. I stopped using Atom for this same issue. 

If I stop using VSCode for a bit, it calms... as soon as I start working again, cpu goes nuts.
This only happens with React web apps so far.. React Native nope...

```
Version:          Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS Version:       Darwin x64 18.6.0
CPUs:             Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)
Memory (System):  16.00GB (0.95GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_off
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	    98	  9455	code main
    0	    49	  9518	   gpu-process
    0	    82	  9547	   shared-process
    0	   262	  9923	   window (user.js — [app])
    1	    82	  9924	     extensionHost
  108	   442	  9927	       electron_node tsserver.js
    0	    49	  9943	         electron_node typingsInstaller.js typesMap.js
    0	    33	  9942	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=9924
    0	    49	 10115	       electron_node server.js
    0	    33	  9925	     watcherService

Workspace Stats:
|  Window (user.js — [app])
|    Folder ([app]): 51 files
|      File types: js(27) json(5) map(4) DS_Store(3) ico(2) html(2) css(2)
|                  md(1) svg(1) ttf(1)
|      Conf files: package.json(1)
```

settings:
```
"files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/bower_components": true,
        "**/jspm_packages": true,
        "**/node_modules": true
    },
    "search.exclude": {
        "/node_modules": true
    },
    "files.watcherExclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/bower_components": true,
        "**/jspm_packages": true,
        "**/node_modules": true
    }
```

**Comment by mjbvz** [comment]
@SirCameron Please open a separate issues, but also make sure you use the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by SirCameron** [comment]
@mjbvz it's the same issue, though?

**Comment by mjbvz** [comment]
@SirCameron Open a separate issue and test using the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)
