### ISSUE TITLE
VS code is unable to format a certain sequence of HTML Tags

### ISSUE THREAD

**Issue by gabrielhfgomes** [microsoft/vscode#74139]
- VSCode Version: 1.34
- OS Version: Linux 64bit

Steps to Reproduce:

1. Create a new HTML file with the follow code:
```
<div><span><p></p></span></div>

<div><div><div></div></div></div>
```
2. Try to format the document(the second div will be formatted correctly, the first won't)
```
<div><span>
        <p></p>
    </span></div>

<div>
    <div>
        <div></div>
    </div>
</div>
```

I tested with the built in HTML formatting and with a lot of extensions like beautify, and couldn't solve it. I just solved roling back to the version 1.17.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by iansan5653** [comment]
This is invalid HTML, so I'm not sure that this is a case that really should be supported. It's not allowable to have block elements inside inline elements: 
![image](https://user-images.githubusercontent.com/2294248/58193584-5504f080-7c91-11e9-8aaa-3a88ca19c48d.png)

**Comment by gabrielhfgomes** [comment]
Sorry, that was a bad example of my part, let me put some real example... I have this code:

  ```
              <div>
                    <a ng-if="accessMeasureGoalConfigs > 1" href="#/measuregoalconfigs/{{ paramIDMeasure }}/new"
                        title="{{::'ADD' | translate}}" class="bt-primary top-button"><i 
                        class="fas fa-plus"
                            aria-hidden="true"></i>
                        <span translate-once="ADD"></span>
                        &nbsp;
                        <a ng-click="backToMeasures()" class="bt-primary top-button pointer">
                            <i class="fas fa-arrow-left"></i>&nbsp;
                            <span translate-once="BACK_TO_MEASURE" />
                        </a>
                    </a>
                </div>
```
In the current version he formats the "i" tag in the same line of the attributes  of "a" tag. In the older versions he breaks line and put the "i" in the line below, like this...

```

<div>
                    <a ng-if="accessMeasureGoalConfigs > 1" href="#/measuregoalconfigs/{{ paramIDMeasure }}/new"
                        title="{{::'ADD' | translate}}" class="bt-primary top-button">
                        <i class="fas fa-plus"
                            aria-hidden="true"></i>
                        <span translate-once="ADD"></span>
                        &nbsp;
                        <a ng-click="backToMeasures()" class="bt-primary top-button pointer">
                            <i class="fas fa-arrow-left"></i>&nbsp;
                            <span translate-once="BACK_TO_MEASURE" />
                        </a>
                    </a>
                </div> 
```

**Comment by octref** [comment]
Please report issue to https://github.com/beautify-web/js-beautify.

**Comment by gabrielhfgomes** [comment]
It's not caused by any extension since I uninstalled all extensions and the behavior still occurs in the 1.34 version and the version 1.17 works perfectly... Could you try these steps?

**Comment by octref** [comment]
Yes, vscode html formatter uses js-beautify under the hood. 1.17 and 1.34 uses 2 different versions of js-beautify.
