### ISSUE TITLE
Autocompletion is matched against truncated filterText to 54 characters

### ISSUE THREAD

**Issue by jlelong** [microsoft/vscode#74133]
When providing a list of `completionItem` with a non empty `filterText`, it seems that when typing only the `54` first characters of `filterText` are considered.

![Capture d’écran 2019-05-22 à 12 18 40](https://user-images.githubusercontent.com/2910140/58174276-cf3b7200-7c9d-11e9-9b74-0a03b7373cfb.png)

1. The first entry has `filterText`: `RoWill2 Rogers, L. C. G. and William Diffusions, Markov processes, and martingales. Vol. 1 undefined`. The `o` of `Markov` is in position `54` (counting from `0`). 
1. The second entry has `filterText`: `RoWill3 Rogers, L. C. G. and Willia Diffusions, Markov processes, and martingales. Vol. 2 undefined`. The `o` of `Markov` is in position `53` (counting from `0`).

When typing `o` to narrow the completion to `Marko`, the first entry vanishes.

![Capture d’écran 2019-05-22 à 12 18 48](https://user-images.githubusercontent.com/2910140/58174283-d2cef900-7c9d-11e9-9176-87e4d81f2625.png)

I apologise for not providing a reproducing example but I do not know how to simply provide a list of completions outside of an extension. I noticed this issue in [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop) (I am a maintainer of it).

- VSCode Version: 1.34.0
- OS Version: OS X 10.14.5

**Comment by jrieken** [comment]
Yeah - that's the current design and keep things fast. At some point a table is being populated and that's what we cap it. I agree that the limit is arbitrary but there some limit is required. We figured that few programming symbols have names that long and from your sample it seems that you are pushing it will headings...

**Comment by jlelong** [comment]
I think those limits should be clearly written in the API documentation. It would really help extension maintainers.
In my example, we use intellisense to autocomplete bibliography entries and `filterText` is used to allow global filtering on several fields concatenated together (author, title and journal), hence the length of the field. I am surprising that there is a real efficiency issue forcing you to put such a small limit.

**Comment by Bynsu** [comment]
Can you please make this limit configurable, at least for custom language extensions, or just make it larger, like at least 128? I'm developing an extension for custom script syntax, and the goal was to allow filtering game NPCs scripts by either their map or part of their full name by making label a string of concatenated name and map. This short limit makes it impossible to do so.

**Comment by clsmt** [comment]
This is really unfortunate. For the scientific community, doing citations is a daily business. This funky behavior basically renders the citation search unusable. I sometimes have to go back to atom just to do citations. I think something small like this can drive people away with time. 

I second the proposal of making the limit customizable.

**Comment by jrieken** [comment]
I have increased the limit 128, let's see how far we get with that...
