### ISSUE TITLE
Open editable file when trying to edit a staged file

### ISSUE THREAD

**Issue by JoshuaLamusga** [microsoft/vscode#74149]
Staged files in VS Code are not editable. Attempting to make an edit gives the tooltip "Cannot edit in read-only editor". There's some friction here because there's no quick flow to take me to a read-write editor for the file. This is a real problem because I do encounter this condition with some frequency (applying stashed changes, editing a rebase patch, soft-reverting a PR and editing, just editing a staged file, etc.) I think it should be possible to tell whether the editor is read-only because it's a staged file, or for some other reason. Tracking this reason should make it possible to improve this workflow.

There can be unstaged changes to the same file, so when editing a staged file, we can do two things:

- If there is no unstaged change to this file, open it as read-write when first opened.
- If there are unstaged changes as well, offer to jump to the editable file.

Thoughts?

**Comment by JoshuaLamusga** [comment]
Juuust noticed this looks similar, right before making the issue, but my hand was already pressing it:
https://github.com/microsoft/vscode/issues/15785

In any case, not really resolved.

**Comment by joaomoreno** [comment]
> There's some friction here because there's no quick flow to take me to a read-write editor for the file.

There's a couple actions which take you to the file. Namely, the first icon in the top right corner of the editor:

![image](https://user-images.githubusercontent.com/22350/58318783-c622e000-7e18-11e9-94fd-2c7e92dcf939.png)

That and the `Git: Open File` global command, to which you can assign a keyboard shortcut.
