### ISSUE TITLE
@cfjedimaster: out of memory error after some time

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#7414]
- VSCode Version: 1.2.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

I'm not sure. I was working on a new file when this error appeared:

![image](https://cloud.githubusercontent.com/assets/393660/15895149/583bbbd8-2d4f-11e6-9e1a-7caed7cad5b1.png)

**Comment by alexandrudima** [comment]
@cfjedimaster Can you please provide additional details to help us reproduce the problem? e.g. Did you open a folder, does the crash occur often, does the crash occur only when opening a certain folder, when editing a certain file, do you have installed extensions that could cause this crash.

**Comment by cfjedimaster** [comment]
I definitely agree it needs more info, but unfortunately I don't have any. I was editing a file, a relatively new file with maybe 5 lines or so. This is the first time I've ever seen it so I can't say how often it happens. I use Code a *heck* of a lot, but as I said, this was the first time I saw it. I do have extensions too. I've got a bunch - need me to list em all?

**Comment by alexandrudima** [comment]
We've made many changes in the core of VSCode, but given you were using these extensions before it doesn't make sense that they would all of the sudden cause a crash. Is there something different in your usage of VS Code? e.g. Did you start using the integrated terminal?

**Comment by cfjedimaster** [comment]
Nope. Well, I tried the terminal just to see it in action. But I'm not using it regularly.

**Comment by bpasero** [comment]
@cfjedimaster is this happening when you open any folder? do you happen to open folders below your home directory maybe?

**Comment by cfjedimaster** [comment]
If I remember right, this project was rather shallow. (And again - I apologize for having so little information. As my first real crash w/ Code, I thought it was important to file it, but it hasn't happened again yet.)

**Comment by joaomoreno** [comment]
@cfjedimaster, just to confirm: it only happened once?

**Comment by cfjedimaster** [comment]
Yep. I switched to Code pretty much at release, so I've been using it every day, all day, for quite some time, and I've only seen it once. Since it was close to a recent release though, I was a bit worried that it may be a new issue. But no repeat yet.

**Comment by cfjedimaster** [comment]
Ok - I just got it again. I used the CLI to open code in a project. Reopen worked. Is there any log I can check? Anything I can do when Code is in the state itself?

**Comment by bpasero** [comment]
@cfjedimaster the full core dump should appear when you open the "Console" application and search for it under "User Diagnostics Reports".

Does it always happen for the same folder you open? What folder is that?

**Comment by DonMartin76** [comment]
I can also pitch in and say I am experiencing this more often than before. I have a largeish repository of `.js` files (around 50k lines of code), I usually never close any windows (why would I need to?). What happens is that editing gets slower and slower over time, and then after a further while, sometimes just leaving Code sitting there doing nothing, I get the above crash report window.

I never open via CLI, and it does not really seem to be related to a specific folder.

I am also on Mac OS X 10.11.5.

**Comment by cfjedimaster** [comment]
@bpasero It was not the same folder as last time.

I found one log that seems like it may be related. It was: Electron Helper_2016-06-13-etc etc

Here is the log: https://gist.github.com/cfjedimaster/0580efb59e9b78f90564ceec175ab5d6

**Comment by bpasero** [comment]
Smells like out of memory. Do you see the process gaining memory a lot?

**Comment by cfjedimaster** [comment]
I haven't noticed that - but I'll start checking. I'm about to head out to a conference so my coding may be slower this week than normal, but I'll report back.

**Comment by cfjedimaster** [comment]
Just happened. Opened up Activity Monitor, Memory tab. Code is taking 68.4MB of ram, which seems pretty small. For CPU, it is relatively small - like 0%. 

I checked Electron Helper (that's related, right?) and for memory, I've got 3 processes, all small too (<35MB each). 

Anything else I can check?

**Comment by bpasero** [comment]
@cfjedimaster well but if you checked for memory after the crash happened, it is likely that the memory is already freed. So it would be interesting if memory grows large while using Code (when it gets to 1 GB on a specific process, it will soon die with an out of memory crash).

**Comment by cfjedimaster** [comment]
Ok - I'll start checking every couple of hours or so.

**Comment by cfjedimaster** [comment]
Btw - what process should I focus on, Code or Electron Helper?

**Comment by bpasero** [comment]
@cfjedimaster ideally find a tool that is able to show you a detailed list of all processes below Code so that we find the one responsible.

**Comment by cfjedimaster** [comment]
Ok - just had a crash. Had about 10 "Electron Helper" processes, one was
555 megs - way above the rest. I have no idea how to get that detailed list
though.

On Tue, Jun 21, 2016 at 10:07 AM, Benjamin Pasero <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> ideally find a tool that
> is able to show you a detailed list of all processes below Code so that we
> find the one responsible.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode/issues/7414#issuecomment-227450576>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYBvGmSOouAIaL0ySWeHveFjXEBi9BDks5qN_AggaJpZM4Iw7xV>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by bpasero** [comment]
Hm, 555 MB should still be ok though. What workspace are you using Code with?

**Comment by bpasero** [comment]
@DonMartin76 trying to keep issues distinct, please open a new one for your case, otherwise it is hard to track.

@cfjedimaster does this always happen when you open a workspace? or single file? do you run with extensions?

**Comment by DonMartin76** [comment]
@bpasero I'll just sit tight and see what gives here. It does though seem to be a related behavior I have.

**Comment by bpasero** [comment]
For all of these cases it would be incredible helpful to get a snapshot of memory before the crash happens. This is a bit of work because you cannot do the snapshot when memory is too close to crashing. It should be fine though to do it up to 500 MB. 

Also of interest is usage patterns (what kind of workspace where it happens, what kind of files).

**Comment by cfjedimaster** [comment]
1) Snapshot
What is the best way to do this on OSX?

2) Unfortunately, I tend to do a lot of different stuff. I primarily work
on Node.js apps and Apache Cordova mobile apps. I'll fire up Code to do my
editing, sometimes forget the window, open up more via CLI, etc. So maybe
that's part of it - just having so many windows around. I use extensions
too, but not heavily.


On Tue, Jun 28, 2016 at 10:50 AM, Benjamin Pasero <notifications@github.com>
wrote:

> For all of these cases it would be incredible helpful to get a snapshot of
> memory before the crash happens. This is a bit of work because you cannot
> do the snapshot when memory is too close to crashing. It should be fine
> though to do it up to 500 MB.
>
> Also of interest is usage patterns (what kind of workspace where it
> happens, what kind of files).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode/issues/7414#issuecomment-229072906>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYBvPb867-doUFs36GVHeBxGvS07h3vks5qQTSmgaJpZM4Iw7xV>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by bpasero** [comment]
@cfjedimaster all from within Code!
* open developer tools (from help menu)
* click profile tab
* record a snapshot

When you do 2 you can even compare them.

**Comment by bpasero** [comment]
@cfjedimaster and it would be interesting if this reproduces without extensions. From the command line, execute: `code --disable-extensions`.

**Comment by cfjedimaster** [comment]
Thanks. Next week I'm back home and will be using Code more heavily, so
will get back to you.

On Tue, Jun 28, 2016 at 1:37 PM, Benjamin Pasero <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> and it would be
> interesting if this reproduces without extensions. From the command line,
> execute: code --disable-extensions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode/issues/7414#issuecomment-229123875>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYBvPbJpiV3bkCY46dM91IXmOg_l8Vcks5qQVvZgaJpZM4Iw7xV>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by TotzkePaul** [comment]
I am also get getting the "The window has crashed" popup. This after a fresh install of VS Code. I have no extensions. It consistently crashes on a particular 12Mb file.

**Comment by bpasero** [comment]
Any updates after using 1.3?

**Comment by cfjedimaster** [comment]
I barely had a chance to use it to so far and I'm on a week long vacation.
:) I'll be back at it next week and will definitely let y'all know.

On Monday, July 11, 2016, Benjamin Pasero <notifications@github.com> wrote:

> Any updates after using 1.3?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode/issues/7414#issuecomment-231667270>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYBvL85OcMPh7I9I6DiaHY8BnGoheDuks5qUflGgaJpZM4Iw7xV>
> .
>


-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by DonMartin76** [comment]
OK, so I had an instance now where one Electron Helper reached 1.78 GB of memory, which sounds a little too much. I took a snapshot, it went to 100%, and then got stuck at "Loading". What now?

**Comment by bpasero** [comment]
@DonMartin76 ok good one, you will not be able to get the snapshot though if it is that high. maybe try again when it is at 900 MB or 1 GB? the process of taking a snapshot will also consume memory unfortunately.

If you find you can reproduce this with some steps and workspace content, let me know.

**Comment by cfjedimaster** [comment]
So, while not exactly the same, I thought it would make sense to add on to this bug. If not - forgive me. I pasted a bit of code into a CSS file and Code froze today. After about a minute, I got the warning you see here:

![image](https://cloud.githubusercontent.com/assets/393660/18600557/db80934c-7c23-11e6-83fa-41e387264031.png)

You can see the cursor. The original HTML was style="..." in a div. I was moving that code into CSS. I had pasted the style="" part and was in the process of removing style=" when Code froze. 

I was able to open DevTools and go to Profiles - but when I tried to do a Snapshot, it just said "Snapshotting..." and never finished. (Well, I gave it 5 minutes at least.)

Activity Monitor shows "Code Helper" taking 99.1% CPU

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. On Windows a tool like **Process Explorer** or **Process Hacker** helps.

Once you have the information please update this issue with it. Thanks!
