### ISSUE TITLE
Misspelled notification tooltip

### ISSUE THREAD

**Issue by snydermb** [microsoft/vscode#74145]
Issue Type: <b>Bug</b>

Open VSCode when you have a notification. Notification text reads "The window must be reloaded for changes to take *effet*" instead of *effect*. For me, the notification Source was Simple icons (Extension).

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.0
gitlens|eam|9.8.0
tslint|eg2|1.0.43
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
plantuml|jeb|2.11.0
vscode-simple-icons|Lau|1.11.7
material-icon-theme|PKi|3.7.0
vscode-icons|vsc|8.6.0

(2 theme extensions excluded)

</details>

**Comment by idanpa** [comment]
This issue is not in vscode but in the [mentioned extension](https://github.com/LaurentTreguier/vscode-simple-icons/blob/65482a80f8916ed322a2fe8d341800fbc9bb56c8/source/extension.ts).
