### ISSUE TITLE
Open File dialog hangs the app

### ISSUE THREAD

**Issue by moizgh** [microsoft/vscode#74148]
Issue Type: <b>Bug</b>

Go to File menu and click on Open file... or use the control + O shortcut key to open a file.
The app hangs.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|9.8.0
prettier-vscode|esb|1.9.0
git-tree-compare|let|1.7.0
vscode-typescript-tslint-plugin|ms-|1.1.0

</details>

**Comment by moizgh** [comment]
![image](https://user-images.githubusercontent.com/25937675/58194469-95fe0480-7c93-11e9-860a-928a2c6d288a.png)

**Comment by alexr00** [comment]
Can you grab a trace as specified [here](https://github.com/microsoft/vscode/wiki/Performance-Issues) please?

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)
