### ISSUE TITLE
Editor not saving changes to disk!

### ISSUE THREAD

**Issue by cmeuser** [microsoft/vscode#74152]
Issue Type: <b>Bug</b>

Code was not saving my changes to disk when editing a file.  Myself and two colleagues wasted almost two hours determining it was a tool issue and not our code.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cordova-tools|vsm|1.8.1

</details>

**Comment by servusDei2018** [comment]
Were you using <kbd>CTRL</kbd>+<kbd>S</kbd>?

**Comment by alexr00** [comment]
How were you trying to save?
