### ISSUE TITLE
Improvements to outline view

### ISSUE THREAD

**Issue by FreHu** [microsoft/vscode#74156]
The oultine view could be a lot more powerful than it currently is:

![image](https://user-images.githubusercontent.com/5097067/58201476-7982bc00-7cd5-11e9-98ca-25b6b9e1189a.png)

## Right click menu
I would like to be able to right click each item where it would be possible to:
- rename. allow F2 to edit the name directly from the outline. this applies the rename refactoring, not just renames the symbol if possible
- find references
- goto definition/implementation if those are separate things in your language
- delete
- format
- run unit tests
- duplicate. duplicates the definition and the implementation if those are separate things in your language. you can then immediately rename the duplicate from the outline
- diff. compare similar looking methods

## Reordering

Drag and drop to reorder items in the code.
If alphabetical sort is selected, add a button to sort items alphabetically. This might be tricky as you want to keep public/protected/private members together. But some kind of category grouping mechanism would also allow for static/instance and other similar cases.

## Multiple selection
- mass move
- mass delete
- mass format

**Comment by V-ed** [comment]
I really like the ideas you have proposed here, which would actually make me use the outline alot more if those functions would be implemented, but I highly suggest you to break down your feature requests (you have 3 in here) into separate issues, linking to here if necessary, it will allow for better tracking and a less daunting task per issue / feature request.

Cheers!

**Comment by FreHu** [comment]
I split it into two issues as multiple selection makes little sense with nothing to do with the items. The listed refactorings are not a must-have list, just a list of possibilities this enables.

**Comment by FreHu** [comment]
Will be discussed in separate issues.
