### ISSUE TITLE
Problem with Polish signs

### ISSUE THREAD

**Issue by Bonifacy666** [microsoft/vscode#74154]
Issue Type: <b>Bug</b>

Hello, 

I'm trying to get familiar with Python but I'm having some language issue in Terminal tab. My projects are in folder with a Polish diacritic name in it and when I'm trying to start the programme only thing I can see is red info "Cannot find path ...". 

For example, the real path is like "C:\Users\Łukasz\Projects" and Python terminal is seeing "C:\Users\ukasz\Projects".

 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (10.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.4.12954

</details>

**Comment by Tyriar** [comment]
Can you show a screenshot of the problem?

**Comment by Bonifacy666** [comment]
Of course!
It should be "C:\Users\Łuki", but it is only "uki"

![zrzut](https://user-images.githubusercontent.com/50731619/58206246-a092bb00-7ce0-11e9-8f64-db9e6348fe13.jpg)

**Comment by Tyriar** [comment]
I suspect this an issue with the extension not vscode, please report over at https://github.com/microsoft/vscode-python
