### ISSUE TITLE
Intellisense suggestion should order by Type match first

### ISSUE THREAD

**Issue by maRci002** [microsoft/vscode#74150]
- VSCode Version
1.34.0

- OS Version:
Windows 10

- Extensions:
       - Dart 3.0.2
       - Flutter 3.0.2

- Language
Dart

My problem is that when a constructor (let's say `new ListView.builder(...)`) waits for specific type of arguments then the IDE should consider type matching while using autocomplete feature.

Here's a simplified example of this issue, the `padding` argument shoud implemet `EdgeInsetsGeometry` abstract class but autocomplete shows me random methods / keywords...:
![VS code autocomplete](https://user-images.githubusercontent.com/8436039/58193408-34ee2500-7cc3-11e9-9e32-346f1f1bd402.gif)

I think the IDE is smart enough to know there are some classes which implement `EdgeInsetsGeometry` abstract class like: `class EdgeInsets extends EdgeInsetsGeometry` and should offer them as first results.

I don't know maybe the autocomplete results come from Dart analysis server and not related to VSCode at all. I tried to make some changes in the Settings.json but no success, [even I tried the original recommended settings](https://dartcode.org/docs/recommended-settings/).

However in Android Studio everything works is fine, I hope this behavior can be implemented in VSCode too :ok_hand:
![Android Studio autocomplete](https://user-images.githubusercontent.com/8436039/58194582-3705b300-7cc6-11e9-9fb1-378974d71766.gif)

I would like to mention in Android Studio autocomplete is 2x times faster than in VSCode, but this is not related to this issue.

**Comment by mjbvz** [comment]
Please file this against your Java extension

**Comment by maRci002** [comment]
https://github.com/Dart-Code/Dart-Code/issues/1742
