### ISSUE TITLE
Allow to color-theme all icons

### ISSUE THREAD

**Issue by JavierReyes945** [microsoft/vscode#74155]
Themes for workbench cannot set colour for some icons as the icons in the top right of an open editor, the top right icons of the problem-output-debug-terminal windows, and the top right icons for the sidebar spaces.

![58050782-9346c680-7b50-11e9-8f29-891c4a4ff3a3](https://user-images.githubusercontent.com/17864163/58201331-2446aa80-7cd5-11e9-8f99-0e75053464a2.png)

![58050793-9cd02e80-7b50-11e9-99d9-5b059f16815b](https://user-images.githubusercontent.com/17864163/58201341-2872c800-7cd5-11e9-988d-86c557f2021f.png)

![58050801-a22d7900-7b50-11e9-92fc-fd5f6013c579](https://user-images.githubusercontent.com/17864163/58201348-2b6db880-7cd5-11e9-8fda-f04c22c1f7e0.png)

The theme set a custom style, but the icons shown above still are default. For consistency, there could be a way to get the reference of the icons in top right workbench, bottom workbench in the different sections, side panel icons, etc.

Reference to [this](https://github.com/jdinhify/vscode-theme-gruvbox/issues/18) issue in [this](https://github.com/jdinhify/vscode-theme-gruvbox) theme.

**Comment by misolori** [comment]
This should be covered by https://github.com/microsoft/vscode/issues/78889 as we're allowing icons to be themeable
