### ISSUE TITLE
Tsserver constant high cpu usage

### ISSUE THREAD

**Issue by mustafahafidi** [microsoft/vscode#74162]
Unfortunately, electron_node tsserver.js runs with high cpu usage randomly on multiple occasions. The only particular case I could capture is this one: on a .ts file with type errors the CPU usage is 0%, but after a parse error has been added, the cpu usage goes up and stays constant around 15% and stays like that until the file has been corrected.
Is this supposed to be normal behavior?

- VSCode Version:1.34.0
- OS Version: Win 10

Steps to Reproduce:

1. Open a .ts file
2. Add random stuff that would make the tsserver parser fail

Does this issue occur when all extensions are disabled?: Yes

![bugtsserver](https://user-images.githubusercontent.com/7404972/58207932-ffa5ff00-7ce3-11e9-9b2f-57e16211a902.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mustafahafidi** [comment]
@mjbvz Unfortunately yes.

**Comment by mjbvz** [comment]
Can you please test using the [insiders build](https://code.visualstudio.com/insiders/)? It is version 1.35

**Comment by mustafahafidi** [comment]
@mjbvz it works fine now. Thanks.

**Comment by mustafahafidi** [comment]
EDIT: The issue is actually still there even in the insiders build. The only difference is that now I can't capture what actually makes tsserver consume constantly cpu with no interaction. Not going to reopen the issue and I will live with it until they will hopefully fix it by chance.
