### ISSUE TITLE
Add drag-and-drop capabilities to outline to reorder items

### ISSUE THREAD

**Issue by FreHu** [microsoft/vscode#74161]
#74156 
## Reordering

Drag and drop to reorder items in the code.

If alphabetical sort is selected, add a button to sort items alphabetically. This might be tricky as you want to keep public/protected/private members together. But some kind of category grouping mechanism would also allow for static/instance and other similar cases.

**Comment by usernamehw** [comment]
#58107

**Comment by usernamehw** [comment]
Or is it not a duplicate? Not a great day.
