### ISSUE TITLE
EACCES error when watching directories containing inaccessible paths

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#74169]
- VSCode Version: 1.34.0
- OS Version: macOS 10.14

Steps to Reproduce:

1. Install [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus&ssr=false)
1. `mkdir test-repo`
1. `mkdir test-repo/inaccessible-dir`
1. `chmod 000 test-repo/inaccessible-dir`
1. `code test-repo`
1. Click on the `Todo+` activity bar extension (this will start watching the filesystem, [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/fb764a46040b72b8aa093977e1fc9e34c28a6e29/src/utils/files.ts#L48-L98) and [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/fb764a46040b72b8aa093977e1fc9e34c28a6e29/src/utils/embedded/providers/abstract.ts#L47-L94), which I think triggers the issue?)

Does this issue occur when all extensions are disabled?: I guess

**Comment by bpasero** [comment]
@fabiospampinato please provide a reproducible case with a simple extension. Btw if this is our watcher triggering it I would expect this to already produce errors when just opening the folder.
