### ISSUE TITLE
settings.json not visible except for the changes that I made

### ISSUE THREAD

**Issue by odomosis** [microsoft/vscode#74163]
![VSCode issue](https://user-images.githubusercontent.com/50924749/58208731-5a733280-7cb3-11e9-9aa5-2fad2f48d07b.jpg)
Issue Type: <b>Bug</b>

I had VSCode a few months ago. The settings.json file was displaying exactly as it should then. I made a change to the settings.json to add the WSL bash terminal in the settings.json file (one line of code).  Then, I uninstalled VSCode.
Now, I reinstalled VSCode today and tried to open the settings.json file. I see the settings UI version as I should, but when I try to open the settings.json version, all I see is the one line of change that I made months ago to the settings.json. No other settings are displaying in the .json version. I am not sure what went wrong. I have literally done nothing else. Maybe I am missing something obvious...?

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.4.12954
octave|toa|0.0.3

</details>

**Comment by gjsjohnmurray** [comment]
There's a setting that controls whether the JSON view of settings should also show all the defaults:
![image](https://user-images.githubusercontent.com/6726799/58241514-0add4700-7d45-11e9-997d-35225ade4857.png)

Try setting that setting and then seeing if your settings show the default settings as well as the settings you've set (including that setting!).

**Comment by odomosis** [comment]
Thanks! That worked!

**Comment by roblourens** [comment]
Also see https://github.com/microsoft/vscode/issues/67908
