### ISSUE TITLE
Command S doesn't work in a python file

### ISSUE THREAD

**Issue by staceysern** [microsoft/vscode#74165]
Issue Type: <b>Bug</b>

Even with extensions disabled, command s to save an individual file doesn't work in a python file. Seems to work in everything else.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 16, 11|
|Memory (System)|16.00GB (2.61GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by alexr00** [comment]
Does it work if you disable the python extension?

**Comment by staceysern** [comment]
Hi,

Even if I disable all extensions and/or run with —disable-extensions options, it doesn’t work for python files.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by staceysern** [comment]
Hi Alex,

The problem doesn’t occur with that version, even with the four extensions that I have installed on my regular vscode.

I’m curious, did you have other reports of this? And when do you think it will make it into the official release?

Thanks so much for looking into this!

Stacey

**Comment by bpasero** [comment]
Ok you can continue using insiders until it becomes stable in around 2 weeks.

**Comment by staceysern** [comment]
Hi Alex,

I’ve been using the regular version of vscode, not the insider version. It seemed like the problem went away for a while but I’m seeing it again as of today.

Stacey
