### ISSUE TITLE
Add right click menu to outline items

### ISSUE THREAD

**Issue by FreHu** [microsoft/vscode#74160]
#74156 

![image](https://user-images.githubusercontent.com/5097067/58201476-7982bc00-7cd5-11e9-98ca-25b6b9e1189a.png)

## Right click menu
I would like to be able to right click each item where it would be possible to:
- rename. allow F2 to edit the name directly from the outline. this applies the rename refactoring, not just renames the symbol if possible
- find references
- goto definition/implementation if those are separate things in your language
- delete
- format
- run unit tests
- duplicate. duplicates the definition and the implementation if those are separate things in your language. you can then immediately rename the duplicate from the outline
- diff. compare similar looking methods

## Multiple selection
Adding multiple selection as well would allow the following:
- mass move (#74161)
- mass delete
- mass format

**Comment by usernamehw** [comment]
#49925

**Comment by FreHu** [comment]
Mutliple selection and some of my menu options are not mentioned there. Should I copy these to #49925 and close this one as duplicate or keep it open?
