### ISSUE TITLE
Odd intellisense sorting for property completion in TS

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74164]
Issue Type: <b>Bug</b>

**Repo**
With the TS file:

```ts
class A {
    private detail = '';

    foo() {
        det
    }
}
```

Trigger completions after `det`.

**Expected**
`detail` should be the first suggestion

**Actual**
Suggestion for the `delete` keyword comes first

Here are the relevant VS Code completion entries:

```
 {
                    "label": "detail",
                    "kind": 3,
                    "sortText": "1",
                    "filterText": "this.detail",
                    "insertText": "this.detail",
                    "insertTextRules": 0,
                    "range": {
                        "startLineNumber": 5,
                        "startColumn": 9,
                        "endLineNumber": 5,
                        "endColumn": 12
                    }
                },
```

```
 {
                    "label": "delete",
                    "kind": 17,
                    "sortText": "2",
                    "insertText": "delete",
                    "insertTextRules": 0,
                    "range": {
                        "startLineNumber": 5,
                        "startColumn": 9,
                        "endLineNumber": 5,
                        "endColumn": 12
                    }
                },
```

I believe the root cause of this is that `detail` completes  to `this.detail`. With recent TS work, we now give keywords a lower `sortText`, but this did not fix this case. @jrieken let me know if you have ideas on how I may be able workaround this

VS Code version: code-oss-dev 1.35.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|25%|
</details>

**Comment by JonWallsten** [comment]
Is this the same bug causing this?
![image](https://user-images.githubusercontent.com/5993909/58233859-73282a80-7d3d-11e9-8859-23c0b1d9ee35.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/5993909/58233946-a9fe4080-7d3d-11e9-943f-d98f29434134.png)

**Comment by jrieken** [comment]
The logic matches `del` against `delete` and `this.detail` which gives **de**le**t**e and this.**det**ail. The former is ranked higher because the match occurs at the word start. The sortText only comes to play when ranking yields equal scored. 

I don't think that we should tweak the ranking so that late, but contiguous, matches rank higher. Having `this.detail` as filter text is causing this I would strongly reconsider that choice.  The goal is to complete to `this.detail` when typing `det` (or any other member), I would say it's a none-goal to complete to `this.detail` when typing `thi` (which is actually part of the confusion in https://github.com/microsoft/vscode/issues/70974).

**Comment by mjbvz** [comment]
Thanks for explaining this. I'll try removing the custom filterText. We added that specially for IntelliCode, so I'll see if I can do this in a way that will not break them
