### ISSUE TITLE
Terminal errors when toggle visibility

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#74172]
Issue Type: <b>Bug</b>

* Toggle terminal
* Devtools showed up with error

```
Cannot read property '_renderLayers' of undefined: TypeError: Cannot read property '_renderLayers' of undefined
    at e._measureRenderTime (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3645:727)
    at _xtermReadyPromise.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3645:643)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-window.js:5 [uncaught exception]: TypeError: Cannot read property 'onIntersectionChange' of undefined
onUnexpectedError @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-window.js:5
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-window.js:5 TypeError: Cannot read property 'onIntersectionChange' of undefined
    at e._resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3657)
    at (/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/anonymous function).setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:22:936)
```

VS Code version: Code - Insiders 1.35.0-insider (955afd60a5e4177d1fdf1c3a4a02dc4e0ca7d781, 2019-05-22T18:03:07.494Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_12667924|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
markdown-emoji|bie|0.0.9
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.9.0
xml|Dot|2.4.0
gitlens|eam|9.8.0
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
flow-for-vscode|flo|1.1.1
vscode-tree-sitter|geo|0.1.10
vscode-pull-request-github-insiders|Git|1.137.0
ocaml|hac|0.6.43
beautify|Hoo|1.5.0
vscode-ghc-mod|hoo|1.2.0
references-plusplus|jri|0.0.5
language-haskell|jus|2.6.0
vscode-colorize|kam|0.8.10
graphql-for-vscode|kum|1.13.1
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.13
vscode-azurefunctions|ms-|0.17.0
vscode-language-pack-zh-hans|MS-|1.34.2
python|ms-|2019.4.12954
RichCodeNav|MS-|0.1.31
remote-containers|ms-|0.47.0
remote-containers|ms-|0.53.0
remote-ssh|ms-|0.32.0
remote-ssh-edit|ms-|0.32.0
remote-ssh-explorer|ms-|0.32.0
remote-wsl|ms-|0.31.0
vscode-remote-extensionpack|ms-|0.10.0
azure-account|ms-|0.8.4
cpptools|ms-|0.23.1
Go|ms-|0.10.2
powershell|ms-|1.12.1
vscode-typescript-tslint-plugin|ms-|1.1.0
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.249
debugger-for-chrome|msj|4.11.3
debugger-for-ios-web|msj|0.1.2
vetur|oct|0.21.0
subtitles-editor|pep|1.0.4
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
seti-icons|qin|0.1.3
ruby|reb|0.22.3
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.5.1
rust|rus|0.6.1
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.3
vscode-swiftformat|vkn|1.3.2

(12 theme extensions excluded)

</details>

**Comment by huanghe2015** [comment]
I want to post a similar issue,but you had got first.Here is my screenshot.
![图片](https://user-images.githubusercontent.com/16605447/58221977-21849d80-7d47-11e9-8f3d-117e3b37759a.png)
![图片](https://user-images.githubusercontent.com/16605447/58221992-2fd2b980-7d47-11e9-9f86-83d4da79d94b.png)

**Comment by Tyriar** [comment]
Already fixed, didn't spot this one 😃
