### ISSUE TITLE
Ctrl + Shift + L to replace the selected items may remove surrounding code in Java

### ISSUE THREAD

**Issue by Rasul-Esmaeilbeigi** [microsoft/vscode#74171]
I use Ctrl + Shift + L frequently to select multiple matches and then replacing the selected items with something else. When writing a C++ code, this works very well. I recently started coding in Java and installed Java Extension Pack. vscode version 1.34.0, operating system Ubuntu 18.04.

Here is how the problem occurs:

Suppose you have a variable I that is used throughout the code. Consider the for loop

for(int i = 0 ; i < I ; i++ )

Move the cursor next to I and press Ctrl + Shift + L to select all matches of I. Then start typing. A window comes up and you select one of the suggestions, say Global (a class). Once you press enter, some of the code is just disappeared. For example, the for loop is changed to

for(int i = 0 ; iGlobal ; i++ )

which means that the < sign as well as the surrounding spaces are all repalced with the Global. As in C++, I expect that only the I variable is replaced with Global not the surrounding characters including the spaces. I attached a toy java project to reproduce the issue.

[Reproduce.zip](https://github.com/microsoft/vscode/files/3209833/Reproduce.zip)

This issue also occurs in other cases than the attached example and also when you use Ctrl + D to add selection. It makes the add-selection approach highly unreliable and risky to use.

EDIT: I think the source of issue is not in the add-selection, although add-selection is also affected by the issue. I just realized after pressing the enter button to select one of the suggestions for a variable A in [A], the right bracket of the array is removed.

**Comment by rebornix** [comment]
Hey, sorry for replying late. As I can't reproduce this issue, can you help check if you can still reproduce with all extensions disabled?
