### ISSUE TITLE
Support `process.stdout.write` from Extension Host to debug output

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#74173]
Root cause of #56211

Repro:

```ts

/**
 * @param {vscode.ExtensionContext} context
 */
function activate(context) {
	console.log('console.log');
	process.stdout.write('process.stdout.write\n')
}
```

![image](https://user-images.githubusercontent.com/4033249/58220718-c90cbc00-7cc4-11e9-839c-6c4c04443b69.png)

This is not specific to debug console. `process.stdout.write` does nothing in extension code.

**Comment by octref** [comment]
I'm on:
Version: 1.35.0-insider
Commit: 4ca38ce5584d7cd67b435b3c32ef1240c6a29628
Date: 2019-05-21T05:17:12.031Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.5.0

**Comment by alexandrudima** [comment]
It looks like this was done intentionally a long time ago - https://dev.azure.com/monacotools/_git/Monaco/commit/309d5296ab7f09d50f3e04f391617a26fe3335d2?_a=compare&path=%2Fsrc%2Fbootstrap.js

It currently is here -- https://github.com/microsoft/vscode/blob/465d9489d2c239777e25de0580dac082fb4c3625/src/bootstrap-fork.js#L153

I don't know exactly why we did this or if it is now safe to remove...

**Comment by bpasero** [comment]
@alexandrudima yeah I cannot recall for sure, probably some Electron issue which may easily no longer hold true. I think we can try to remove it and see what breaks.

**Comment by bpasero** [comment]
@joaomoreno hey, do you remember maybe? Looking at `EBADF` issues on Electron I see some old discussions with you involved: https://github.com/electron/electron/issues/3482 and https://github.com/electron/electron/issues/1471

**Comment by joaomoreno** [comment]
![long time ago](http://gph.is/2bBlEGo)

:man_shrugging:

**Comment by bpasero** [comment]
Maybe we push this rather early in debt week and not now so close before endgame.

**Comment by alexandrudima** [comment]
Thanks @bpasero !

**Comment by roblourens** [comment]
The code change is clearly correct but I'm not sure it makes a difference because as far as I know, the extension host stdout isn't actually going anywhere? When I run `process.stdout.write('something\n')` in an extension, it doesn't show up in the debug console. And if I use the 'dot' reporter from the original issue, I still don't see the dots, in the debug console or when running in the terminal.

**Comment by roblourens** [comment]
It does go to the devtools for the window running the extension. It would be on vscode (not the DA) to pass that along to the Debug Console. But if we do that, we would get duplicate messages in the Debug Console.

So I wonder whether the fix you really want is to redirect `process.stdout.write` to the same place `console.log` is redirected to. cc @isidorn

**Comment by bpasero** [comment]
Thanks, I do not think this warrants anymore changes for November.

@octref feel free to check out Robs suggestion if you can make it work.

**Comment by bpasero** [comment]
This does not seem possible due to https://github.com/nodejs/node/issues/8033

**Comment by connor4312** [comment]
I did this in a more primitive way in https://github.com/microsoft/vscode/commit/538988cf720422bdc9f6b960398e98375c747f56
