### ISSUE TITLE
Integrated terminal in Ubuntu crashes when launching external programs

### ISSUE THREAD

**Issue by freedmand** [microsoft/vscode#74179]
- VSCode Version: 1.34.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. launch the integrated terminal (Ctrl-`)
2. type in `nautilus` to launch the file manager. In a normal shell this will work. In the integrated terminal, a segmentation fault (segfault) is reported.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Maybe related to snap, any ideas @flexiondotorg?

```
❯ nautilus

(org.gnome.Nautilus:18075): GLib-GObject-CRITICAL **: 19:48:20.147: g_object_run_dispose: assertion 'G_IS_OBJECT (object)' failed

(org.gnome.Nautilus:18075): Tracker-WARNING **: 19:48:20.147: Falling back to bus backend, the direct backend failed to initialize: Could not find database file:'/home/daniel/snap/code/common/.cache/tracker/meta.db'.
Segmentation fault (core dumped)
```

**Comment by flexiondotorg** [comment]
@kenvandine What can we do to mitigate the above?

**Comment by josecm** [comment]
Does someone have a solution for this?
