### ISSUE TITLE
Terminal does't activate proper virtualenv in multi-project workspace

### ISSUE THREAD

**Issue by akospasztor** [microsoft/vscode#74189]
Issue Type: <b>Bug</b>

## Summary
When having a workspace with multiple projects (i.e. a folder for each project, and each have different virtualenv), creating a new terminal window activates the first project's virtualenv, regardless of currently active project or explicit selection.

## Steps to reproduce
1. Create two folders, representing two different projects.

2. Create two virtualenvs.

3. Add both folders to a vscode workspace, then assign the first project to a virtualenv and the second project to the other virtualenv. As shown on the following screenshots, vscode handles the  virtualenv selection correctly whenever I change between projects, i.e. switching back and forth between the files of the two projects:
![step1](https://user-images.githubusercontent.com/6011126/58236844-154b1100-7d44-11e9-961d-5daddeb77813.jpg)
When selecting a file from the second project, everything seems to be correct:
![step2](https://user-images.githubusercontent.com/6011126/58236849-18460180-7d44-11e9-9844-e4e4f25a6c85.jpg)

4. Create a new terminal window, and try to select project 2.
![step3](https://user-images.githubusercontent.com/6011126/58236969-60fdba80-7d44-11e9-93af-9c19b7c38188.jpg)

5. However, instead of activating the correct virtualenv (in this case, it should be `demo2`), the virtualenv assigned to the first project of the workspace is activated:
![step4](https://user-images.githubusercontent.com/6011126/58237181-c81b6f00-7d44-11e9-9a94-1a5b593fb282.jpg)

## Information
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode-python
