### ISSUE TITLE
Crashes when quickly press ctrl+` twice

### ISSUE THREAD

**Issue by ColinTree** [microsoft/vscode#74181]
- Version: 1.34.0 (user setup)
- Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
- Date: 2019-05-15T21:59:37.030Z
- Electron: 3.1.8
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. When there is no terminal opened, quickly press ctrl+` twice
2. Window pop up(maybe at the back of the vs code window). Whatever which button I choose, vs code window would tell me there was a crash and need to restart window
  ![image](https://user-images.githubusercontent.com/22613139/58229189-5a873700-7d74-11e9-991f-d4a48e57b43a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Does this happen consistently for you? I can't reproduce it.

This check is meant to prevent this exception from occurring:

https://github.com/microsoft/node-pty/blob/5924d76d6765ac4da3996f49e1282eaafd591452/src/windowsTerminal.ts#L140-L142

Unless the process crashes or something? 😕

**Comment by ColinTree** [comment]
@Tyriar Yes It crashes every time on my computer. Maybe you didn't press keyboard quick enough? XD
I looks like terminal cannot initialize if the intergrated terminal is not visible.
I think I can send a screen record later

**Comment by ColinTree** [comment]
I had failed to record a meaningful capture.... Just simply press the keyboard as quick as possible

**Comment by wsmelton** [comment]
Video of making it crash with extensions enabled or disabled: [VSCODE_Crash.zip](https://github.com/microsoft/vscode/files/3235729/VSCODE_Crash.zip)

Logs from these sessions: [logs.zip](https://github.com/microsoft/vscode/files/3235726/logs.zip)

**Comment by wsmelton** [comment]
```
Version: 1.35.0-insider (system setup)
Commit: e9c50663154c369a06355ce752b447af5b580dc3
Date: 2019-05-30T05:19:53.372Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

@Tyriar I can confirm this is with user setup version only on my machine. I installed the system installer and removed the user setup. I cannot duplicate this issue anymore.

**Comment by Tyriar** [comment]
@wsmelton thanks for the video 👍

**Comment by Tyriar** [comment]
@wsmelton could you enable trace logging (F1 > "log level" > "trace"), then repro the issue again and check the logs if there is a IPty.resize entry at the end? These will be located in your user data directory, something like this: `%APPDATA%\Code - Insiders\logs\<latestdatetime>\renderer1.log`

**Comment by Tyriar** [comment]
Related https://github.com/microsoft/vscode/issues/71789

**Comment by wsmelton** [comment]
Did the trace and find this entry and the end of the render1.log:

```
[2019-05-31 06:49:55.367] [renderer1] [debug] Terminal process ready (shellProcessId: 12116)
[2019-05-31 06:49:55.370] [renderer1] [trace] IPty#resize NaN NaN
```

**Comment by Tyriar** [comment]
@wsmelton perfect! You found the bug 😃

**Comment by Tyriar** [comment]
Can add an extra defensive check in https://github.com/microsoft/node-pty/issues/316 too

**Comment by alexr00** [comment]
I can't reproduce the original issue using 1.34 user install so I'm not sure how to verify. Any repro/verification steps?

**Comment by Tyriar** [comment]
Verify via code review, I could not reproduce the issue either.
