### ISSUE TITLE
Tabs: grouped split views

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#7418]
I often work between two or three files, e.g. 1 CSS, JS, and HTML file each. When multi tasking I need to switch between groups of these files. For example:

foo.js
foo.html
foo.css

bar.js
bar.html
bar.css

When I'm finished working on foo, and I want to work on bar, I want to switch to a split view of each file in bar. This workflow is not really supported using the latest tabs interface.

**Comment by bpasero** [comment]
Sounds like a fun extension to write :)

**Comment by OliverJAsh** [comment]
I have recently switched to vim which does this very well.

I can have one tab for each component, within which I can have splits for the JS, HTML, and CSS of that component.

**Comment by OliverJAsh** [comment]
Are there any other issues/feature requests similar to this? I suspect it may be a popular feature request

**Comment by mattwilson1024** [comment]
This would be a really great feature. From what I can tell the extension API doesn't expose enough to make this possible with an extension either though at the moment - see https://github.com/Microsoft/vscode/issues/15178

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
