### ISSUE TITLE
Formatter doesnt work At times

### ISSUE THREAD

**Issue by ramaHruday** [microsoft/vscode#74184]
Issue Type: <b>Bug</b>

edit  5 six files for whole day, by the end of day. the formatter refuses to work

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (3.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.43
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-typescript-tslint-plugin|ms-|1.1.0
vscode-scss-formatter|sib|1.4.1
code-spell-checker|str|1.7.10
html-css-class-completion|Zig|1.19.0

</details>

**Comment by Tyriar** [comment]
What type of file are you formatting?

**Comment by ramaHruday** [comment]
TS,HTML

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ramaHruday** [comment]
My version is 1.34.0 which is the latest.Do i have to disable extensions??

**Comment by mjbvz** [comment]
Yes, try on the [insiders build (1.35)](https://code.visualstudio.com/insiders/) with all extensions disabled
