### ISSUE TITLE
terminal: strange font after update

### ISSUE THREAD

**Issue by gioboa** [microsoft/vscode#74183]
Issue Type: <b>Bug</b>

After the last nightly update the font in console it's broken.

VS Code version: Code - Insiders 1.35.0-insider (94f7de61ece171f4390ece488a220d22cbb0fddd, 2019-05-23T05:15:43.589Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 10, 6|
|Memory (System)|16.00GB (5.33GB free)|
|Process Argv|-psn_0_262208|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
angulardoc-vscode|Ang|6.1.3
ng-template|Ang|0.1.11
githistory|don|0.4.6
gitlens|eam|9.7.4
tslint|eg2|1.0.43
jira-plugin|gio|0.16.1
svn-scm|joh|1.48.4
vscode-kubernetes-tools|ms-|1.0.0
csharp|ms-|1.19.1
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
angular-console|nrw|7.4.25
vetur|oct|0.21.0
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
vscode-yaml|red|0.4.0
code-settings-sync|Sha|3.2.9

(1 theme extensions excluded)

</details>

![Screenshot 2019-05-23 at 09 08 08](https://user-images.githubusercontent.com/35845425/58232641-550cfb00-7d3a-11e9-8526-83771264a703.png)

**--- UPDATE ---**

Changing any font setting solve the issue.
e.g. actual font-size: 12 (issue) - change to 13 (fixed) - return to 12 (fixed)
if I open a new terminal the problem will occur.

**Comment by frankintrahouse** [comment]
FYI: Setting the Terminal Renderer Type, fixed it for me
![Selection_129](https://user-images.githubusercontent.com/29704925/58233169-9b168e80-7d3b-11e9-9672-b0f8787794a7.png)

**Comment by gioboa** [comment]
Render type: `auto` or `canvas` solve the issue. Thanks 👍

**Comment by Tyriar** [comment]
Other report:

<img width="579" alt="Screen Shot 2019-05-23 at 9 53 55 AM" src="https://user-images.githubusercontent.com/2193314/58271347-b2a44600-7d40-11e9-92af-209b679619b2.png">

https://twitter.com/code/status/1131600226479890432

**Comment by Tyriar** [comment]
Might be related to https://github.com/xtermjs/xterm.js/pull/2067

**Comment by Tyriar** [comment]
I can't reproduce for some reason. @gioboa what's your rendererType set to? It looks like your g's are cut off which normally happens on the canvas renderer but @frankintrahouse is saying switching to that fixed the issue 🤔

**Comment by gioboa** [comment]
I had `dom` rendererType. I solved the issue by change renderer type into `auto`

**Comment by Tyriar** [comment]
@gioboa thanks for clarifying 🙂

**Comment by fritz-flaconi** [comment]
Can confirm, "auto" as rendererType  fixes the issue

**Comment by Tyriar** [comment]
I'm not sure this was actually fixed.

**Comment by Tyriar** [comment]
Tracking the xterm.js side https://github.com/xtermjs/xterm.js/issues/2136

**Comment by Tyriar** [comment]
It looks like the width of cells is correctly measured for a monospace font, but the font being used is proportional.

**Comment by Tyriar** [comment]
Managed to repro with these settings on macOS thanks to @yairEO

```
  "terminal.integrated.rendererType": "dom",
  "terminal.integrated.fontFamily": "Fira Mono",
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.fontWeight": "400",
```

**Comment by Tyriar** [comment]
Upstream PR is out https://github.com/xtermjs/xterm.js/pull/2140, will probably pull into the build tonight.
