### ISSUE TITLE
Indicate a setting is overridden by language overrides

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#74195]
When a setting for e.g., `"editor.wordWrap` is overridden by language overrides, then it will be helpful if settings UI indicate it.

**Comment by alexilyaev** [comment]
This will hopefully eliminate the frustration of setting `wordWrap` in the user settings and not have it apply to some specific language, due to default settings of that language (like in Markdown).

More details in https://github.com/microsoft/vscode/issues/72559

**Comment by rzhao271** [comment]
Merging to #131707
