### ISSUE TITLE
Heavy RAM Usage

### ISSUE THREAD

**Issue by jaideep-zogato** [microsoft/vscode#74190]
Issue Type: <b>Performance Issue</b>

I am using VS Code on Ubuntu 18.04. Have noticed since the last few updates, VS Code is eating over 1.5GB of memory. It slows down the system and causes delays.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-50-generic

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.1.11

</details>

**Comment by servusDei2018** [comment]
A possible solution is to cap VS Code's RAM usage. The following would limit vs Code to 500mb of physical memory.

First, create a control group:
```
$ cgcreate -g memory:/vsCode
$ echo $(( 500 * 1024 * 1024 )) > /sys/fs/cgroup/memory/vsCode/memory.limit_in_bytes
$ echo $(( 5000 * 1024 * 1024 )) > /sys/fs/cgroup/memory/vsCodememory.memsw.limit_in_bytes
```
Then, run vsCode under that group:
`$ cgexec -g memory:vsCode code helloworld.cs`

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
