### ISSUE TITLE
Error processing "launch": Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by Flians** [microsoft/vscode#74197]
D:\ProgramFiles\Microsoft VS Code\node.dll --inspect-brk=27588 test\test-all.js
Error processing "launch": Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at Object.spawn (child_process.js:540:9)
    at NodeDebugAdapter.launchInInternalConsole (d:\ProgramFiles\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:346:32)
    at NodeDebugAdapter.<anonymous> (d:\ProgramFiles\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:197:28)
    at Generator.next (<anonymous>)
    at fulfilled (d:\ProgramFiles\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:7:58)

**Comment by weinand** [comment]
@dcsgman did you install node.js on your system?

**Comment by dcsgman** [comment]
@weinand 
The launch.json:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\test\\test-all.js"
        }
    ]
}`
I run this project with VScode on another computer,  It works properly. 
But In this computer which has installed VScode and nodejs, it doesnt work.

**Comment by weinand** [comment]
- Where does the output (in the first comment) come from?
- Inside VS Code open the integrated terminal and run "where node". What's the output?

**Comment by dcsgman** [comment]
- The first comment is from the wrong info, which is printed when I try to debug with VS code.

- After I run "" where node", there is nothing in the integrated terminal. But I can get the info when I run this command in cmd.

**Comment by weinand** [comment]
The node executable path `D:\ProgramFiles\Microsoft VS Code\node.dll` looks fishy to me. 

When I debug a simple node.js program on Windows I see this:

![2019-05-24_11-13-39](https://user-images.githubusercontent.com/1898161/58316969-1d26b600-7e15-11e9-9995-da6b9d9e9703.png)

So my node.js path is `C:\Program Files\nodejs\node.exe`

If running "where node" in the integrated terminal returns nothing, this means that VS Code cannot find node.js on the Path.

What is the node.js executable path when running "where node" outside of VS Code?

Use this path in a launch config with the "runtimeExecutable" attribute like this:
```js
{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeExecutable": "C:\\Program Files\\nodejs\\node.exe",
            "program": "${workspaceFolder}\\test\\test-all.js"
}
```

**Comment by dcsgman** [comment]
Thank you, your solution is useful. But I dont why it doesnt work.
when I run "where node" in cmd. It looks like:
![image](https://user-images.githubusercontent.com/16850481/58317867-45c8a300-7e49-11e9-8061-38598458ba72.png)

**Comment by weinand** [comment]
Something in your "Path" seems to be strange. Node.js is installed in the expected location `C:\ProgramFiles\nodejs\node.exe` but there is a `node.dll` in `D:\ProgramFiles\Microsoft VS Code` that I don't have. 
In addition my my "Program Files" folder ahs a space between in "Program Files" whereas yours doesn't. Did you change that?

**Comment by dcsgman** [comment]
Yes, before I installed all softwares, I have changed the path "D:\ProgramFiles" where doesnt include any space. For node.dll, it existed when I installed the VS code.

**Comment by weinand** [comment]
I'm not sure whether changing "D:\Program Files" was a good idea...
But if you do, do it via the registry.
See:
- https://answers.microsoft.com/en-us/windows/forum/windows_7-files/can-i-rename-program-files/452cc0a0-7500-44d9-a939-46f65332f229
- https://social.msdn.microsoft.com/Forums/vstudio/en-US/25558d61-de42-4ec8-bfba-3d4814b42ddc/changing-programfiles?forum=vcgeneral

**Comment by dcsgman** [comment]
Ok, I will try it. Thank you very much!

**Comment by roblourens** [comment]
Let me know if this is still an issue.
