### ISSUE TITLE
trimTrailingWhitespace Not Working for May Update VSCODE

### ISSUE THREAD

**Issue by vinod-a-ext** [Microsoft/vscode#7419]
- VSCode Version:Latest (May Update)
- OS Version:windows 7

Steps to Reproduce:
1. Add this
   {
     "files.trimTrailingWhitespace": true
   } 
   in your user settings file
2. Type
   function hi(){
   
   var ldsfjsdlf;
   }
   Actual :Not Clearing empty lines when i press enter/any trigger
   Excepeted:Should clear empty lines 

Proof:
![image](https://cloud.githubusercontent.com/assets/12810078/15897827/9f976720-2db3-11e6-803a-3320a7569c32.png)

**Comment by alexandrudima** [comment]
@vinod-a-ext The whitespace is trimmed when saving the file. (Or all the time when enabling autosave)
