### ISSUE TITLE
problem with code suggestion

### ISSUE THREAD

**Issue by bahmanbs** [microsoft/vscode#74193]
hi dear developers !
VS code is great , but have some issues ,
some times it errors and tells extensions host error ...
and sometimes code suggestion doesn't work
and sometimes it can not complete my code and have no suggestion , after restart it will be fixed ;

thank !s

**Comment by mjbvz** [comment]
Please follow [this guide](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to report issues

/needsMoreInfo
