### ISSUE TITLE
Ctrl+Shift+M Keyboard Shortcuts  invalid

### ISSUE THREAD

**Issue by waitingsong** [microsoft/vscode#74196]
Issue Type: <b>Bug</b>

I use keyboard shortcuts Ctrl+Shift+M to toggle Problem panel.
Showing and hiding worsk with VSC v1.31.1 and older.
Showing works and hiding not works with VSC v1.34.0.
If click focus on Problem panel then hiding (via Ctrl+Shift+M) works with VSC v1.34.0.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (55.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.34.2
guides|spy|0.9.3

</details>

**Comment by letrunghai** [comment]
According to #19400, the way toggling panel works is like this: if the panel is hidden then shortcuts open it, if it is shown but not focused then using the shortcuts focus it. If the panel is focused then the shortcuts close it.
This behavior has been there since v1.28. Don't know why 1.31.1 still has the behave like you said though.

**Comment by waitingsong** [comment]
@letrunghai 
I open the Problem panel through Ctrl+Shift+M,  then the panel is not focused with Ctrl+Shift+M agagin. So i can not toggle the Problem panel with Ctrl+Shift+M, but both `Ctrl+Shift+U` and `Ctrl+Shift+Y` works..
