### ISSUE TITLE
Bogus build error

### ISSUE THREAD

**Issue by gahisee** [microsoft/vscode#74198]
Issue Type: <b>Bug</b>

After day or two of debugging a java app, on two occasions now, I have run into following two situations:

1) hitting F5 to debug, VSC reports it cannot find the class MainApp which clearly has and presently exist.
2) VSC reports there are build errors but in fact, there are none.

in both instances, i resort to deleting the cache directory
$HOME/.config/Code/User/workspaceStorage/

upon restart, all is well.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3783)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|23.46GB (18.51GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
java-decompiler|dgi|0.0.2
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.8.0
vsc-material-theme|Equ|2.8.2
csharp|ms-|1.19.1
material-icon-theme|PKi|3.7.0
java|red|0.45.0
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
This is most likely an issue with the java extension that provides your launch configuration. Please open an issue in the java extension's repository!
