### ISSUE TITLE
Debug console no longer shows Console.log?

### ISSUE THREAD

**Issue by teimaj** [Microsoft/vscode#742]
Sorry if this isn't quite the right place for it, but i just updated vs code and noticed that there is a new debug console window that opens up in code, whereas previously it would open an external command prompt window that displayed everything that was written to Console.log.

Now it just shows the start up path for my Electron application and doesn't show anything else.

Is there a way to enable it with a setting in the launch.json configurations? Or is there something else i need to do.

I mean, its not the end of the world if its no longer there, i just liked it

Thanks

**Comment by bpasero** [comment]
@isidorn we have a flag to control this right?

**Comment by isidorn** [comment]
there is `externalConsole: true`
More details https://code.visualstudio.com/docs/editor/debugging

**Comment by teimaj** [comment]
Ah thank you, i didn't have this flag in my launch.json
