### ISSUE TITLE
Auto Update fails each month

### ISSUE THREAD

**Issue by gbargsley** [microsoft/vscode#74205]
- VSCode Version:
- OS Version:

Each month when VS Code attempts to update I get the failure.  The log file is attached.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gbargsley** [comment]
[vscode-inno-updater-1558619121.log](https://github.com/microsoft/vscode/files/3212467/vscode-inno-updater-1558619121.log)

**Comment by joaomoreno** [comment]
Can you fully remove and reinstall VS Code and let us know next release whether it doens't work?
