### ISSUE TITLE
Closing "About window" spoils clipboard value

### ISSUE THREAD

**Issue by heretic13** [microsoft/vscode#74202]
- VSCode Version: 1.34.0 (user setup)
- OS Version: Windows Windows 10 x64

Steps to Reproduce:

1. Copy some text in clipboard.
2. Open About window.
3. Closing about window by clicking window close button (cross), NOT (!!) by buttons "Ok" or "Copy".
4. Press Shift-Insert. I see that inserted "about info", not my my text, that i copied in point 1.

**Comment by gjsjohnmurray** [comment]
/confirm

Good catch, and clear repro instructions.

**Comment by bpasero** [comment]
Up for grabs.
