### ISSUE TITLE
HTML comments in Markdown not rendering correctly

### ISSUE THREAD

**Issue by gmarino-preemptive** [microsoft/vscode#74201]
- VSCode Version: 1.35.0-insider
- OS Version: Windows 10 Enterprise 1809 17763.503

Steps to Reproduce:

1. Open a markdown file
2. Create an HTML `div`
3. Put a comment with an empty line inside the `div`
4. Nothing below the comment will be rendered in the previewer

Does this issue occur when all extensions are disabled?: Yes

Image Examples:

![Markdown Render 1](https://user-images.githubusercontent.com/49040882/58256617-54299880-7d3d-11e9-9d96-0cc14b665289.png)

![Markdown Render 2](https://user-images.githubusercontent.com/49040882/58256631-58ee4c80-7d3d-11e9-9969-3312b4d87e06.png)

Text:

```md
# HTML Comment parsing example

This is some plain text.
We can have any number of sentences or paragraphs before the HTML comment.

<div id="example">
<!--
This is a multi-line comment. Works great...

Until you wrap it in an HTML div for some reason.
-->
</div>

And then nothing below is rendered correctly.
```

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by gmarino-preemptive** [comment]
I've updated the original report to include the text.

**Comment by mjbvz** [comment]
This is consistent [with how the commonmark dingus parses the file](https://spec.commonmark.org/dingus/?text=%23%20HTML%20Comment%20parsing%20example%0A%0AThis%20is%20some%20plain%20text.%0AWe%20can%20have%20any%20number%20of%20sentences%20or%20paragraphs%20before%20the%20HTML%20comment.%0A%0A%3Cdiv%20id%3D%22example%22%3E%0A%3C!--%0AThis%20is%20a%20multi-line%20comment.%20Works%20great...%0A%0AUntil%20you%20wrap%20it%20in%20an%20HTML%20div%20for%20some%20reason.%0A--%3E%0A%3C%2Fdiv%3E%0A%0AAnd%20then%20nothing%20below%20is%20rendered%20correctly.) Github does the same

Seems like this is the design of markdown specification
