### ISSUE TITLE
Integrated terminal for windows (cmd) renders unnecessary lines when I open it.

### ISSUE THREAD

**Issue by officer47p** [microsoft/vscode#74200]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
Steps to Reproduce: I don't know!

Does this issue occur when all extensions are disabled?: Yes

![Screenshot (324)](https://user-images.githubusercontent.com/40776589/58253537-ed789f00-7d7d-11e9-9d9b-b54731364bad.png)

When I open integrated cmd or PowerShell in the vs code, it renders some unnecessary lines, and the cursor is invisible, when I type into the terminal, the text starts at the middle and after hitting enter and running the initial command, everything gets ok. anyone knows why?

PS: I'm in GitHub and submitting issues, but I saw some other friends had this problem in other 

Thanks

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
