### ISSUE TITLE
Pull via UI

### ISSUE THREAD

**Issue by dmarins** [microsoft/vscode#74206]
Issue Type: <b>Bug</b>

1 - Create a remote branch
2 - Open VS Code
3 - Click in Source Control menu
4 - Click in Pull, in the more actions menu
5 - Look that the remote branch is not downloaded
6 - Open the terminal
7 - Type git pull
8 - Now the remote branch is downloaded

The behavior not should be same using the UI?

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
chat|kar|0.15.4
vsliveshare|ms-|1.0.249
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.2.12
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.21.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by joaomoreno** [comment]
The correct command would be `Git: Fetch`. `Git: Pull` will only pull the current branch, in VS Code.

**Comment by dmarins** [comment]
There is no "Git Fetch" in the git part of VS Code
