### ISSUE TITLE
Extension doesn't get Activated in VS-Code 1.34

### ISSUE THREAD

**Issue by Mehmetcanss** [microsoft/vscode#74209]
- VSCode Version: 1.34
- OS Version: MacOS Mojave

My Extension is not being activated since I upgraded to VS-Code 1.34
We developed an extension for VSCode however it doesn't get activated in VS-Code 1.34
In Version 1.33.x, it works.
It also gets activated if I run the extension in debug mode.

However if I install the extension using the .vsix File, it never gets activated, regardless of which activation event I use.

**Comment by CyriacBr** [comment]
I have the same issue. Developed an extension yesterday and it was perfectly working in debug mode. Once packaged it never activates. I even published it so you guys can see for yourself: https://marketplace.visualstudio.com/items?itemName=CyriacBr.promise-warning.

**Comment by carloslahrssen** [comment]
Can you show me the engines portion of the package.json, you might not be supporting versions 1.34.0 and above.

**Comment by Mehmetcanss** [comment]
This is resolved, was due to a uncaught exception in extension code
