### ISSUE TITLE
Terminal 256 color FG is printing wrong colors

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#74215]
- VSCode Version: Version 1.35.0-insider (1.35.0-insider) 
 94f7de61ece171f4390ece488a220d22cbb0fddd
- OS Version: macOS Mojave

Steps to Reproduce:

1. Open terminal and compare foreground colour with that of Stable Release

Does this issue occur when all extensions are disabled?: Yes/No
Yes

See below. (top is Stable and bottom is insiders)
Stable Version 1.34.0 (1.34.0)
Insider Version 1.35.0-insider (1.35.0-insider) 94f7de61ece171f4390ece488a220d22cbb0fddd

<img width="896" alt="Screen Shot 2019-05-23 at 09 07 07" src="https://user-images.githubusercontent.com/1948812/58268757-e41a1300-7d3a-11e9-8907-e39a122dde8e.png">

**Comment by octref** [comment]
Same happens to me. This is reproducible by:

- Make a few changes in a git repo
- Run `git diff --color | diff-so-fancy` (you need https://github.com/so-fancy/diff-so-fancy)

**Comment by Tyriar** [comment]
@DonJayamanne can you share your `$PS1`?

**Comment by DonJayamanne** [comment]
Here it is (for home directory):
```
\[\033]0;\W\007\]\[\]\n\[\]\u\[\] at \[\]\h\[\] in \[\]\w$(prompt_git "\[\] on \[\]" "\[\]")\n\[\]$ \[\]
```
<img width="765" alt="Screen Shot 2019-05-24 at 10 06 15" src="https://user-images.githubusercontent.com/1948812/58344823-991c0080-7e0b-11e9-83de-b75c11162b73.png">

**Comment by Tyriar** [comment]
@DonJayamanne what's `prompt_git` do? I'm looking for the colors/attributes it uses. Also you're using the dark+ theme with no color customizations right?

**Comment by DonJayamanne** [comment]
> what's prompt_git do?

Unfortunately I'm no expert in this area. I'm using https://github.com/mathiasbynens/dotfiles (possibly something from there). Been using that for years now.

On a side note, this issue cam up recently. Was ok in an older (probably 2 weeks ago) version of Insiders.

> using the dark+ theme with no color customizations right?

Yes

**Comment by Tyriar** [comment]
Using this script to test 256 colors, they look good as well 😕 

<img width="847" alt="Screen Shot 2019-05-24 at 10 38 22 AM" src="https://user-images.githubusercontent.com/2193314/58346547-1f3a4600-7e10-11e9-8e58-56786ad1921e.png">

**Comment by Tyriar** [comment]
Repro:

```
echo -e '\x1b[38;5;166mdaimms\x1b[97m at \x1b[38;5;136mWU2TEHPV08CX-01\x1b[97m in \x1b[38;5;64m~/dev/Microsoft/vscode\x1b[97m on \x1b[38;5;61mmaster\x1b[38;5;33m [$]'
```

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2124
